### ISSUE TITLE
Delete file: inconsistent confirmation wordings

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#10001]
File browser
<img width="300" alt="01" src="https://user-images.githubusercontent.com/62179190/211150723-0d3342f4-c16e-47e0-8da2-40e88ede16ae.png">

History
<img width="300" alt="02" src="https://user-images.githubusercontent.com/62179190/211150725-2b9d8065-aea0-445b-a0b0-5c2b3b10c1a2.png">

Reader (end of the document action)
<img width="300" alt="03" src="https://user-images.githubusercontent.com/62179190/211150727-220fdc22-4372-4449-a3e5-e4b9d18964c5.png">

(1) Unified wording must be discussed and found.
(2) If a book has been opened, additional text can be shown: "Book settings, highlights and notes wil be permanently lost" (see https://github.com/koreader/koreader/issues/9978).

**Comment by mergen3107** [comment]
Also, “the book will be removed from history”?

**Comment by Frenzie** [comment]
> (1) Unified wording must be discussed and found.

The first is the canonical one.

> Also, “the book will be removed from history”?

That only happens if you enabled that setting.

**Comment by mergen3107** [comment]
Yes, but it doesn’t inform about this. The delete message is the same regardless the setting

**Comment by offset-torque** [comment]
We have this message in KDE (they have really good attention to UI/UX). 
It combines that two sentences in the KOReader dialog into one and it is pretty clear I think:

> Do you really want to permanently delete this file ?

**Comment by Frenzie** [comment]
The phrasing was pretty much copied from or very heavily inspired by Dolphin, Explorer, and Thunar ftr.
![image](https://user-images.githubusercontent.com/202757/211196541-423c792f-4161-4d52-bf46-5003c70182b3.png)
![image](https://user-images.githubusercontent.com/202757/211196645-8b4f1110-1db4-4f1a-9d43-5e008e392419.png)
