### ISSUE TITLE
Kobo Glo HD: power button doesn't wake up

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#10007]
Device: Kobo Glo HD (not my device)
Version: 2022.11

When KOReader is running, the power button doesn't wake up the device from sleep, connecting to a charger does.

**Comment by poire-z** [comment]
No issue with my GloHD over the last months with the nightlies (although I'm running an old Kobo firmware and have koreader patched, but without anything related to resume).
Also, if suspended, connecting it to a computer with usb doesn't wake it up.

Does the power button work in other contexts (ie. suspending, or in Nickel) ?

**Comment by hius07** [comment]
As the author says, the power button wakes up the sleeping device when in Nickel without KOReader running.

**Comment by NiLuJe** [comment]
Verbose debug logs would be helpful, but that sounds mildly weird, yeah.

(I would almost ask to try with a from-scratch installation...).
