### ISSUE TITLE
Vocabulary builder Font size

### ISSUE THREAD

**Issue by 13879885572** [koreader/koreader#10005]
Can you enlarge the font size of the words and example sentences in the Vocabulary builder slightly? Especially for example sentences, the font size is too small. Plus, Google Translate's font size is a little smaller.

**Comment by weijiuqiao** [comment]
Thanks for the advice. The example sentence for me on kindle is ok but indeed a bit on the smaller end on android. I can make a pr to enlarge it a little.
As to the "font size of the words", do you mean the words listed for reviewing? I believe they should be big enough and quite easy to read?

**Comment by 13879885572** [comment]
Sorry, my eyesight is not very good, and the font needs to be very large to read comfortably. In the dictionary function, I always set the font to the maximum.
In fact, I'm talking about the kindle. Example sentences are too small for me and require some effort to read; The words can be read clearly, but it would be more comfortable for me if you made the font larger.
Thanks!

**Comment by weijiuqiao** [comment]
If that's the case, maybe changing the device DPI is a better solution :)

**Comment by 13879885572** [comment]
Thank you, your method is very useful!
