### ISSUE TITLE
FR: User Presets: Import and Export the lower menu per-book layout and font settings

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#10015]
**Does your feature request involve difficulty completing a task? Please describe.**

I have more than one favorite font, my font preference changes depending on the type of book I am reading.

I spend a lot of time tweaking parameters in the settings menu to optimize the layout of a book based on the particular font I have chosen.  

The parameters I adjust the most are font weight, contrast, margins, line spacing, and word space, but all of the settings are important to the appearance of a book.

If I load a new book it will adopt the settings I have assigned as defaults, but if I change the font I then need to  manually adjust each of those parameters to optimize the new font.     

**Describe the solution you'd like**

Currently the KOReader  saves each set of parameters with each book.  This is a great feature.

I would like to have the ability to save and load the entire group of these per-book settings so that when I find a particularly good combination I can export them and later I can import them into another book. 

**Describe alternatives you've considered**

I've been writing these settings down on paper, but it is time consuming to enter all those parameters. 

**Additional context**

 I'm sure the list of bottom menu parameter settings are stored in some meta-data file for each book, it would be nice for the user to have a collection of presets they could select from the top menu.

**Comment by hius07** [comment]
Existing features that may be useful:
(1) Profiles plugin
(2) Upper menu Typeset - Document settings

**Comment by mergen3107** [comment]
Yes, just use Profiles plugin. You need to have a few profiles with the same set of options in each. 

So what it does is manually applies all those to current setup. 

If you then enable «Show in action list» for each of them, you can find them in gestures list and assign “Show as quick menu”. This will show you all profiles with a gesture! Here is an example: https://github.com/koreader/koreader/issues/9594#issuecomment-1270086354

**Comment by zmixnyc** [comment]
Thank you for the reply

> (2) Upper menu Typeset - Document settings

I couldn't find a "Typeset" menu item, there is a "Document setting" menu, unfortunately it has only 2 choices: 

"Reset document settings to default"

and 

"Save document settings as default"

I am hoping to save several settings, I'll check out the Profiles Plugin.

**Comment by zmixnyc** [comment]
> Yes, just use Profiles plugin. You need to have a few profiles with the same set of options in each.
> 
> So what it does is manually applies all those to current setup.
> 
> If you then enable «Show in action list» for each of them, you can find them in gestures list and assign “Show as quick menu”. This will show you all profiles with a gesture! Here is an example: [#9594 (comment)](https://github.com/koreader/koreader/issues/9594#issuecomment-1270086354)


Thank you for the suggestion, I will check it out (Can you please send me a link to this plugin - also, I have no experience with using them, so any guidance would be welcome..!)

It does sound a bit complicated, I was hoping for something more straightforward, but happy to experiment with it..!

**Comment by mergen3107** [comment]
It is included already. Top menu - Tools icon - More plugins

**Comment by zmixnyc** [comment]
> It is included already. Top menu - Tools icon - More plugins

Ah, thanks, so it is.!!  I can see it, but how do I use it? (RTFM?)

**Comment by mergen3107** [comment]
Yep, good luck! Let me know (ping me by including @mergen3107 ) if you need more help

**Comment by zmixnyc** [comment]
> Yep, good luck! Let me know (ping me by including @mergen3107 ) if you need more help

Very Kind of you , thanks.  I've been busy saving all my various profiles, will test to see how much of the overall settings these Profiles actually save..!

**Comment by offset-torque** [comment]
New update to the guide is coming (probably in a few days) @zmixnyc. 
**Profiles** and **QuickMenu** features will be explained there.

**Comment by zmixnyc** [comment]
I've been testing the Profiles plug-in, and I have to say it's functionality is very thorough, but doesn't really address my feature request.

The main issue is that it requires the user to create a profile first, and then manually go through an elaborate series of menus in order too add the preferences one by one, without the benefit of any feedback or the ability to open the lower menu to see what settings you have used.    It requires the user to resort to my paper-and-pencil method.  It is tedious.

If the Profiles plug-in is going to be the preferred method for saving and recalling user preferences, it would be useful if it had an option to "save all current user preference settings"  when creating a new profile, and then the user could go through all of the various menus and disable those that they don't need, rather than making them create a profile and then manually change each parameter. It seems backwards to me as a user.

It's important to view this from the user's perspective, in my case: "I have set up all my font and layout preferences and I really like the way this book looks now, I'd like to be able to apply this to future books from this author or publisher" (and have the ability to have several choices saved).

Perhaps my feature request could be incorporated into Profiles, or perhaps a more simple, user-friendly version could be added?

**Comment by poire-z** [comment]
More thoughts around your post just above in #8590 (and mine at https://github.com/koreader/koreader/issues/8590#issuecomment-1259955165).

**Comment by zmixnyc** [comment]
> More thoughts around your post just above in #8590 (and mine at [#8590 (comment)](https://github.com/koreader/koreader/issues/8590#issuecomment-1259955165)).

Thank you, I'll read that thread..!

**Comment by zmixnyc** [comment]
I read the other thread, and  I didn't want to hijack it, so I will try to clarify my request as best I can here: 

There are 2 categories of user settings: Global preferences and  Per-Book settings, I am mostly interested in having the ability to save the 21 (Per-Book) user parameters in the lower settings menu and the Font selection from the upper menu to a user accessible file.

Here are the 21 parameters available in the Lower menu

Rotation
Two Columns On/Off

L/R Margins
Sync T/B Margins
Top Margin
Bottom Margin

View Mode
Render Mode
Zoom (dpi)
Line Spacing

Font Size
Word Spacing
Word Expansion

Contrast
Font Weight
Font Hinting
Font Kerning

Alt Status Bar - (I think the  this should be in the upper menu as a Global preference.)
Embedded Style
Embedded Fonts
Image Scaling


The reason I am requesting this feature is that I have found that these parameters need to be adjusted whenever you change to a different Font.  Most of the features in the upper menu are universal enough that they can be globally applied and not need any further adjustments.  "Font" is the exception. Changing the Font requires at least 11 of the lower menu parameters to be adjusted to optimize the layout for the selected font:

L/R Margins
Sync T/B Margins
Top Margin
Bottom Margin
Line Spacing

Font Size
Word Spacing
Word Expansion

Contrast
Font Weight
Font Hinting
Font Kerning

There may be several different solutions to this issue, maybe the 11 items above can be set as Font specific defaults?
That would allow the use to change fonts without concern for the changes required to maintain a consistent layout.

**Comment by offset-torque** [comment]
@zmixnyc 
Your problem is nearly same as this issue I opened (https://github.com/koreader/koreader/issues/7708#issue-894834173) which resulted with **hius07** kindly implementing **"Reset current document settings to defaults"**.

I want to ask @hius07: 
We already have **"Save current settings as defaults"** implemented recently.
Can't this feature save these **"default settings"** to a file under some directory ?
Then user can select which **"defaults file"** they want to apply to the current document.

**Comment by zmixnyc** [comment]
> @zmixnyc Your problem is nearly same as this issue I opened ([#7708 (comment)](https://github.com/koreader/koreader/issues/7708#issue-894834173)) which resulted with **hius07** kindly implementing **"Reset current document settings to defaults"**.
> 
> I want to ask @hius07: We already have **"Save current settings as defaults"** implemented recently. Can't this feature save these **"default settings"** to a file under some directory ? Then user can select which **"defaults file"** they want to apply to the current document.

Thanks for the link, it seems that between that FR, mine and [THIS](https://github.com/koreader/koreader/issues/8590) one, we're all looking for the same solution..!
