### ISSUE TITLE
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

### ISSUE THREAD

**Issue by gionlime** [koreader/koreader#10014]
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?  https://github.com/flutter/flutter

**Comment by NiLuJe** [comment]
No, and there never will be. This isn't a standard Android app, we have more in common with a custom game engine than an App, which makes an UI/App toolkit entirely irrelevant to us.
