### ISSUE TITLE
feature request: authentication in OPDS catalog

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1001]
Hi

I am trying to test calibre integration on Linux version. It works, i can login to my local calibre and browse however it is complaning that the file cant be saved to "/sdcard", other folders do not work either. 

Is this a limitation or similar issue to I bugged about calibre download fails on Kobo?

thanks

**Comment by HLFH** [comment]
@chrox I understand that OPDS itself doesn't have any provision for authentication. The authentication we need is the standard [RFC 2617 http auth](https://en.wikipedia.org/wiki/Digest_access_authentication). Is that kind of Lua code helpful for this issue? https://github.com/catwell/lua-http-digest

**Comment by HLFH** [comment]
@chrox Thank you so much!!! You rock!!!!
