### ISSUE TITLE
Gestures: update properly if profile gets renamed

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10026]
* KOReader version: 2022.11-85 (one of the latest nightlies)
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
Gesture manager is confused when profile gets renamed. 

#### Steps to reproduce
1) Set up profiles, check each as “Show in action menu”. 
2) Add them to a Gesture and check “Show as quick menu”.  For example, I added 20 profiles. 
3) Rename a profile. 
4) Gesture manager now still shows “20” profiles, but the new profile name is unchecked. If I check it, it will show 21 profiles, and the old one is not found in the list.

**Comment by hius07** [comment]
This will be fixed:
- if a profile is renamed, all its calls in all gestures and other profiles will be renamed respectively
- if a profile is deleted, all its calls in all gestures and other profiles will be deleted

The question:
if a profile is unregistered from Dispatcher (unchecked Show in action list) - what to do?
Unregistered profile cannot be executed, and it is not visible in the list of actions in gestures and profiles (so it cannot be removed manually and remains as a dead code).
On the other hand, if we register it back, it will reappear in gestures and profiles, no need to restore it manually.

**Comment by mergen3107** [comment]
Yes, maybe just remove it from the Dispatcher list completely, if it is being unchecked? 
Otherwise, I can imagine so many profiles being renamed constantly, that are just piled as dead code

**Comment by hius07** [comment]
Can you explain please?
If a profile is being unchecked, should it be removed from all gestures and other profiles (in the same way as deleting)?
Note that currently checking it back restores the profile in action lists of gestures and profiles.
If the current behaviour is changed, you will need to restore the profile in action lists manually.

**Comment by mergen3107** [comment]
Ok, sorry, maybe I have confused what you mean by “so it cannot be removed manually and remains as a dead code”. 

The way I simply see it as a user is this:
1) Unchecking just removes the profile from Dispatcher list
2) Profile is still there in the profiles list, if it never needs to be

**Comment by hius07** [comment]
Look at your first post.
In p.3 do not rename the profile, but uncheck Show in action list.
(1) Gesture manager will not show this unchecked profile in the list of 20 profiles (QM) for this gesture.
(2) If you check the profile back, it will reappear in this QM automatically.
(Technically it is still saved in the settings for this gesture, but not shown in QM and in the list of actions for this gesture)

The question: is (2) good?
Or after unchecking I should delete the profile from all gestures and other profiles?

**Comment by mergen3107** [comment]
`Or after unchecking I should delete the profile from all gestures and other profiles?`

I think deleting it from all gestures is better, because it will be consistent. What I mean is, when a user unchecks the “Show in action list”, they would expect this profile to be gone both from QM and gesture selection. 

But I don’t quite understand what does “delete it from other profiles” mean.
