### ISSUE TITLE
FR: Improve Intervals  - Vocabulary builder

### ISSUE THREAD

**Issue by Kelamir** [koreader/koreader#10028]
**Does your feature request involve difficulty completing a task? Please describe.**
Current vocabulary builder intervals are inefficient. They are not usable at all and detrimental for one's study process. One sees cards way too many times. It's overstudying(cramming) for little benefit.  Intervals have to be longer to allow one to reinforce memory by making the card appear just when it's about to be forgotten.

**Describe the solution you'd like**
1) Use intervals increasing by 250%. It's used in spaced repetition as Good, and it's simple enough to add. This is not a lot but something to begin with.
2) Randomize future review time a bit, in order to prevent context hints from constantly having words next to each other, and to prevent excessive load if you studied a lot on a certain day. Example: a card scheduled to appear in 60 days will appear at a random value of 55-65.

**Additional context**
For example, say you studied 100 new cards today. These 100 new cards will be scheduled always on the same day if you get them all done on the scheduled day(as you are expected), so you will always have a bad day of having to review a lot, and there will be days when you studied little, thus have an easy time. This is very unbalanced, and even worse so because intervals are overquestioning you, effectively cramming the words. This software should not be intended for memorization - no, it is one's own responsibility to memorize a word, by means of mnemonics and such. The intended preferred purpose is to reinforce memory of those who already have a word in short or long term memory.

250% interval is Anki's(spaced repetition software) default setting for Good. See on spaced repetition:
https://en.wikipedia.org/wiki/Forgetting_curve
https://en.wikipedia.org/wiki/Spaced_repetition

Idea for randomizing future reviews taken from A Stochastic Shortest Path Algorithm for Optimizing Spaced Repetition Scheduling https://dl.acm.org/doi/10.1145/3534678.3539081?cid=99660547150

**Comment by Kelamir** [comment]
For ease of access, referring to https://github.com/koreader/koreader/blob/master/plugins/vocabbuilder.koplugin/db.lua#L219

**Comment by Kelamir** [comment]
#10029 here is my implementation. These are the minimal changes that make this addon usable.

**Comment by poire-z** [comment]
Pinging @weijiuqiao .

**Comment by weijiuqiao** [comment]
>They are not usable at all and detrimental for one's study process.

This is some serious accusation :/

>Randomize future review time a bit

This is actually good advice.

>250% interval is Anki's(spaced repetition software) default setting for Good.

I don't find mentioning of this particular number in the quoted pages. Also we are not the Anki plugin after all? The intervals used in the VocabBuilder plugin are based on a paper I found through Google (not exactly the same numbers though, IIRC something like 20min -> 30min, 9hours -> 12hours, to be more "symmetrical" :)

>This software should not be intended for memorization - no, it is one's own responsibility to memorize a word, by means of mnemonics and such.

Well, I believe it's intended for memorizing words for some people, at least for me :)

**Comment by Kelamir** [comment]
Thank you for taking the time to consider the issue, weijiuqiao. I'm honestly sorry if my tone was condescending. I like the addon you made a lot, it really is the last thing KOReader needed to help people study languages effectively - it already has advanced dictionary/look up support and statistics, each being cornerstone of immersion-based language learning in my experience. 

Admittedly, the changes proposed are subpar, and my pull request is a demonstration at best - I'm a junior programmer with neither experience in Lua nor contributing to open source projects. A change of intervals is merely a personal taste, which I am aware of and I can see why this might be an issue. I do hope to sparkle further discussion and improve the intervals of the addon.

**Comment by Kelamir** [comment]
I made the issue limited to what what I could implement, so as not to burden weijiuqiao with ideas. I think it would be great to be able to add customize settings such as customizable intervals in the app, but that's out of my league for now.

**Comment by Kelamir** [comment]
Speaking of the intervals. I mentioned Forgetting Curve. It looks like this 
![image](https://user-images.githubusercontent.com/61295121/212542502-0afd370c-b710-4566-ae64-28024e03555d.png)
_Ebbinghaus’ original forgetting curve._


 This is effectively how information gets forgotten. We can counter it by setting up optimal review times by reviewing information just as it is about to be forgotten. This allows to optimize number of reviews across time, and improve efficiency. 
 
![image](https://user-images.githubusercontent.com/61295121/212542761-847f1378-39e7-4e08-9534-c0325c33d3a4.png)
_Wozniak’s Supermemo take on dealing with the forgetting curve using a spaced repetition schedule._

This is the reasoning behind intervals chosen.

**Comment by weijiuqiao** [comment]
From Ebbinghaus’ original forgetting curve, in the first hour we forget very quickly, so it seems quite reasonable to arrange for more repetitions within?
I encourage you to add the functionality of custom intervals, maybe as a practice of programming. It would be nice for users to have them at their own paces.

**Comment by Kelamir** [comment]
Updated the code to include more short-term intervals. 

> I encourage you to add the functionality of custom intervals, maybe as a practice of programming. It would be nice for users to have them at their own paces.

Thank you! I will start on that one shortly. 

If you prefer, would you like to close this issue in favor of custom intervals approach?

**Comment by Kelamir** [comment]
Closing this issue due to a better solution being developed here https://github.com/koreader/koreader/pull/10035
