### ISSUE TITLE
FR: Releasing to the Snap Store

### ISSUE THREAD

**Issue by xmha97** [koreader/koreader#10024]
Please releasing this app to the snap store.
https://snapcraft.io/docs/releasing-to-the-snap-store

**Comment by offset-torque** [comment]
Since no one answered yet, I am asking out of curiosity **xmha97**:
We have an **Appimage** version of KOReader which works on all distros without installation.
Snap store doesn't even come installed by default on many distros.
Only Ubuntu and Manjaro has it by default AFAIK.

So what problem a snap store release will solve which can't be done with the current Appimage ?

**Comment by xmha97** [comment]
The snap version makes installation easier, people can easily go into the store and install KOReader.

Also, this version will be updated by snap.

Finally, I should add that the AppImage version did not work on my Ubuntu and I use the Deb version.

**Comment by pazos** [comment]
Hi. I think none of the maintainers is willing to spend time building and keep updating yet another recipe. 

IMHO time is better spent in a few other things:

1. Improve compatibility with appimage (manifest, arm64, appimagehub...)
2. Improve compatibility with debian (remove legacy archs, GPG signed repo...)
3. Provide a generic linux image for x86_64 and aarch64 to make possible for others to repackage the program without relying on deb/appimage binaries. (at least archlinux aur and a future flathub recipe are using this to re-bundle the app)

> Also, this version will be updated by snap.

from the PoV of the user, sure. From the PoV of the maintainer it doesn't hold true :/

> Finally, I should add that the AppImage version did not work on my Ubuntu 

Assuming you're on a x86_64 host that's either not true or a bug. Please try again and report the error log when you run the AppImage binary from a terminal emulator. (Create a new ticket if you find a bug)

**Comment by xmha97** [comment]
Thank you for your explanation, if you can close this issue.
