### ISSUE TITLE
Show wrong alphabet mode in UI (add unneeded space to beginning of text)

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#10030]
* KOReader version: v2022.11-86-g16fb32d5_2023-01-11
* Device: kindle PW3

#### Issue
in Persian, Arabic, etc... each alphabet has two modes (technically it has more than that but not related to this bug)
1. When it connected to other alphabet like `ش‍`  in `شبکه`
2. When it is not connected, like  `ش` in `خاموش`

Sometimes, UI show connected alphabet (mode 1) instead of mode 2 in specific element of UI. it is not random, and you can reproduce them.
For example, wrongly show ‍` خاموش‍`
![19878826-ae1a-4ead-8366-d004e7d541d6](https://user-images.githubusercontent.com/25131576/212535920-58b5271e-176e-402b-9174-c60f9ffb85d6.jpg)
Instead of Correct way `خاموش`
![fa841a87-bb9f-4379-82a4-6c0146ffd37b](https://user-images.githubusercontent.com/25131576/212535962-186aad0b-0b45-49a0-a6b3-1d78b4e6a22b.jpg)

#### Steps to reproduce
1. Download last version of Persian translation [here](https://hosted.weblate.org/download/koreader/koreader/fa/) and copy to `/l10n/fa/koreader.po` for last version of translation
2. change KOReader language to فارسی
3. open an EPUB document
4. Swipe up to open bottom menu
5. press gear icon
6. see `خاموش` in this menus
7.  press gear icon again
8. with each time you press gear icon, you see a change between `خاموش` and `خاموش‍`

####  when usually it happens?
1. just happen in menu text of UI (not in book content or anywhere else)
2. just happen on last letter of word (not middle of that)
3. sometime if you change menu, it changes which word affected with this bug

#### anything else should be known about this problem?
In Persian keyboard, if you add ‍\` after a Persian alphabet, it changes alphabet mode
for example, in Persian layout `a` key represent `ش` in Persian. If keyboard layout be in Persian layout than press these keys
```
a     -----> ش
a + ` -----> ش‍
``` 

Maybe KOReader use \` around text \`خاموش\` and it is made this bug.
Maybe some mechanism in KOReader try to compact text inside button and that made this problem?

If it is not enough to debug the problem? Do you have any idea to how gather more clue about this bug

UPDATE:
in menu entry it became more clear what happen. Some weird unneeded space added to the beginning of text

normal
![c556a076-6384-42b1-9bcc-0b45fc24dbde](https://user-images.githubusercontent.com/25131576/212540528-4648dd97-44ac-4d5a-a254-4c1733f39604.jpg)

Bug happen
![1033a099-1c00-4b66-846a-eb499a229366](https://user-images.githubusercontent.com/25131576/212540198-89da4888-8529-4733-9146-b5df33ba0516.jpg)
![34826a83-51e3-421b-8e9a-4ed32bd24150](https://user-images.githubusercontent.com/25131576/212540505-23c18a02-e99f-4fa5-afbe-a054a059c690.jpg)

**Comment by poire-z** [comment]
Played with the bottom menu, and I get the unwanted rendering changes you see: it's a bit random (I have to click many times on the gear icon or change menu to get it wrong then good then good then wrong....).
The randomness feels like some unitialized value somewhere.
It does not happen when I revert the last commit of https://github.com/koreader/koreader-base/pull/1543:
https://github.com/koreader/koreader-base/commit/08efc6da7dbe6859f4bc614d67b71caee127a9a7 so, probably in there... I'll have a look.

**Comment by poire-z** [comment]
Probably just me having messed up again with C/Lua indexes, and how xtext handle the given indexes (some excluded, some not)...

This should fix it:
```diff
         // Fill HarfBuzz buffer
         hb_buffer_clear_contents(_hb_buffer);
         // for (int i = start; i < end; i++) {
         //     hb_buffer_add(_hb_buffer, (hb_codepoint_t)(m_text[i]), i);
         // }
-        int extra = (end == m_length) ? 1 : 0; // in case we added ZWJ+Ellipsis at end
+        int extra = (end > m_length) ? 1 : 0; // in case we added ZWJ+Ellipsis at end
         hb_buffer_add_codepoints(_hb_buffer, (hb_codepoint_t*)m_text, m_length+extra, start, end-start);
         hb_buffer_set_content_type(_hb_buffer, HB_BUFFER_CONTENT_TYPE_UNICODE);
```
`end` being exluded, if drawing the full string without truncation request, we have `end == m_length`, and we were giving to harfbuzz some extra char - unitialized when we actually don't truncate and don't add ZWJ+Ellipsis.

And because I'm still totally not confident about my boundary skills... and I had a hard time triggering the edge case this was supposed to handle (truncating off the last char of a string if unsafe to break from previous char), putting some debug code and some logs:
```diff
--- a/xtext.cpp
+++ b/xtext.cpp
@@ -1045,2 +1045,4 @@ public:
                 m_charinfo[t].flags |= CHAR_IS_RTL;
+            if ( cur_cluster_unsafe_to_break )
+                printf("%d is unsafe to break\n", t);
             if ( cur_cluster_unsafe_to_break )
@@ -1302,2 +1304,3 @@ public:
             // (All this applies similarly with an ellipsis at start, considering the next char.)
+            printf("ellipsis %d (/%d)\n", idx_to_substitute_with_ellipsis, end);
             bool ellipsis_at_end = idx_to_substitute_with_ellipsis == end-1 && end-2 >= start;
@@ -1307,2 +1310,3 @@ public:
             if ( ellipsis_at_end ) {
+                printf("ellipsis at end\n");
                 // Set the bidi level of our ellipsis (and our zwj) to be the same as the
@@ -1311,2 +1315,3 @@ public:
                 if ( m_charinfo[idx_to_substitute_with_ellipsis].flags & CHAR_IS_UNSAFE_TO_BREAK_BEFORE ) {
+                    printf("ellipsis at unsafe to break\n");
                     idx_to_substitute_with_zwj = idx_to_substitute_with_ellipsis;
@@ -1319,2 +1324,3 @@ public:
             else if ( ellipsis_at_start ) {
+                printf("ellipsis at start\n");
                 idx_to_mimic_bidi = idx_to_substitute_with_ellipsis + 1;
@@ -1749,3 +1755,4 @@ public:
         // }
-        int extra = (end == m_length) ? 1 : 0; // in case we added ZWJ+Ellipsis at end
+        int extra = (end > m_length) ? 1 : 0; // in case we added ZWJ+Ellipsis at end
+        printf("end %d m_length %d => extra %d - hb(%d: %d +%d)\n", end, m_length, extra, m_length+extra, start, end-start);
         hb_buffer_add_codepoints(_hb_buffer, (hb_codepoint_t*)m_text, m_length+extra, start, end-start);
@@ -2407,2 +2414,3 @@ static int XText_shapeLine(lua_State *L) {
         idx_to_substitute_with_ellipsis--; // Lua to C index
+        printf("idx_to_substitute_with_ellipsis %d\n", idx_to_substitute_with_ellipsis);
     }
```

```diff
--- a/reader.lua
+++ b/reader.lua
@@ -206,6 +206,26 @@ end

 local UIManager = require("ui/uimanager")

+--if false then
+local logger = require("logger")
+local TextWidget = require("ui/widget/textwidget")
+local Font = require("ui/font")
+local text = "Ø¨Ù<87>ØªØ±Û<8C>Ù<86>"
+local text = "Ø¨Ù<87>ØªØ¨Ù<87>Øª" -- that's 6 unsafe to break arabic chars بهتبهت
+xtext = require("libs/libkoreader-xtext")
+-- z = xtext.new(text, Font:getFace("cfong", 20), true, true, "fa")
+z = xtext.new(text, Font:getFace("NotoSansArabicUI-Regular.ttf", 20), true, true, "fa")
+z:measure()
+print(z:getWidth())
+z:shapeLine(1, 5, 5)
+z:shapeLine(1, 6, 6)
+-- logger.warn(z:shapeLine(1, 6, 6))
+os.exit(0)
+--end
+
```
(yep, that's my way of debuging xtext...)

```
01/15/23-15:31:20 DEBUG Found font: NotoSansArabicUI-Regular.ttf in ./fonts/noto/NotoSansArabicUI-Regular.ttf
1 is unsafe to break
2 is unsafe to break
3 is unsafe to break
4 is unsafe to break
5 is unsafe to break
56

idx_to_substitute_with_ellipsis 4
ellipsis 4 (/5)
ellipsis at end
ellipsis at unsafe to break
end 6 m_length 6 => extra 0 - hb(6: 0 +6) -- 6 chars (4 arabic + zwj + ellipsis)
end 6 m_length 6 => extra 0 - hb(6: 5 +1) -- ellipsis drawn from a fallback font

idx_to_substitute_with_ellipsis 5
ellipsis 5 (/6)
ellipsis at end
ellipsis at unsafe to break
end 7 m_length 6 => extra 1 - hb(7: 0 +7) -- 7 chars (5 arabic + zwj + ellipsis)
end 7 m_length 6 => extra 1 - hb(7: 6 +1) -- ellipsis drawn from a fallback font

```

It looks like this does not break the better ellipsis support shown at https://github.com/koreader/koreader/issues/5359#issuecomment-1287904250 : 

![image](https://user-images.githubusercontent.com/24273478/212548387-956495d9-ee8d-4eba-a95d-3eee82c42f5b.png)

Couldn't reproduce the leading space in the top menu, but hopefully, this will fix that too.
I'll make a PR with this after v2023.01.
