### ISSUE TITLE
KOreader 2022-v8/10/11 crashed in Hanvon N10plus

### ISSUE THREAD

**Issue by mabier** [koreader/koreader#10034]
* KOReader version: Android-ARM-2022v8/10/11
* Device: Hanvon N10plus

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/10425781/crash.log)

**Comment by NiLuJe** [comment]
An actually actionable log(cat) would be helpful ;o).

As well as an idea of which Android version the ROM is based on.

**Comment by pazos** [comment]
Agree with @NiLuJe, please attach logs.

Also, the line `onAppBleachConfigChanged bleach` doesn't look good.

It looks like a ConfigChange that's not part of android. Maybe something used to optimize apps for eink screen?. Anyways, *this* program needs to handle **all** configuration changes by itself to prevent the app to be restarted by the framework. We already do that, in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/AndroidManifest.xml#L46 but we cannot handle changes that are not part of the (android) framework.

So please attach logs that confirm or deny my assumptions ;)
If I'm correct you'll see a message like https://github.com/koreader/koreader-base/blob/master/ffi/input_android.lua#L277

In that case you have two options:

1. Look in your device for ways to disable any kind of optimization and see if the problems goes away.
2. Raise a ticket with the company and tell them to blacklist any kind of nonsense in `org.koreader.launcher` and `org.koreader.launcher.fdroid`

**Comment by mabier** [comment]
> An actually actionable log(cat) would be helpful ;o).
> 
> As well as an idea of which Android version the ROM is based on.

The Android version is 11 . 
This crash occurred after a system update from the OEM Hanvon several days ago, KOReader(2022-v11) worked perfect before this firmware update .

**Comment by pazos** [comment]
I'm going to close this ticket since it is not our bug and we cannot fix it.

You're still welcome to paste logs here and help us understand how they manage to break android :)
