### ISSUE TITLE
FR:i hope  calibre can connect on wired,not only wireless

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#10048]
Thanks for all contributors .
Des:
I am using a koreader docker image[https://registry.hub.docker.com/r/wardwouts/koreader-novnc/] to read lan calibre server ,as you know, docker image doesn't have a wireless.when i open calibre connection,it support wireless only

**Describe the solution you'd like**
I hope open a connection operation can supports wired option

**Describe alternatives you've considered**

**Additional context**
Sorry for my poor english
Hope anyone's reply

**Comment by pazos** [comment]
> i hope calibre can connect on wired,not only wireless

It already works that way.

> as you know, docker image doesn't have a wireless.when i open calibre connection,it support wireless only

Agree on the first part. Disagree on the second :)

To make KOReader and calibre able to see each other you need to run them in the same docker bridge network on the same host.

If you're running calibre outside docker (in localhost or any other lan host) you need to run koreader on the host network so it is able to broadcast to real devices on your lan, not to virtual devices on the docker network.

There're plenty of tutorials online, just google `docker host network` and apply the knowledge to your koreader container ;)

**Comment by pazos** [comment]
+1:

If you run both apps as docker containers on different hosts you'll need to run them both in host network mode.
