### ISSUE TITLE
Possibly incorrect layout on kindle 3 legacy

### ISSUE THREAD

**Issue by alexkiri** [koreader/koreader#10041]
* KOReader version: koreader-kindle-legacy-v2022.11
* Device: Kindle 3 Keyboard WiFi

#### Issue
The layout of the homescreen looks good when starting the app:
![20230120_193850](https://user-images.githubusercontent.com/6061770/213789965-83e15197-8d23-4fc7-be75-f18b66873510.jpg)

After ~1 sec the layout changes, and it looks worse:
![20230120_193851](https://user-images.githubusercontent.com/6061770/213789977-93665820-4a7c-4427-9368-f56bf9f9b254.jpg)

Issues with incorrect layout:
- Line separators have no margin
- Letter hint boxes are incorrectly positioned (not centered, overlapping text labels), have incorrect size and incorrect background colors 

#### Steps to reproduce
- Start KOReader
- Observe the initial layout
- The layout changes after ~1 sec

**Comment by poire-z** [comment]
Not really an issue. You probably have `in File browser > Cabinet icon > Display mode >`:
![image](https://user-images.githubusercontent.com/24273478/213797096-51c4d5f6-21e0-4500-9e6a-4f65b98fab78.png)

KOReader when started with file browser starts with the Classic mode - and then (which may take 1s, as you noticed), a plugin (CoverBrowser) takes over and somehow hack (like a skin/theme) the Classic mode to make it look fancy (the Mosaic or Detailed mode you see above).
That's just how this plugin work, nothing that really needs fixing.

If you prefer Classic, stick with Classic - but you may prefer to see the covers like all of us. It may happen that the Detailed list modes don't really look nice with the "Letter hint boxes", but that's not something we really tuned, as I think only really old Kindles, those with a keyboard, get them.

**Comment by alexkiri** [comment]
@poire-z  Thanks for the quick reply. Yes, it makes sense. And yes, this is indeed the case, because I'm using an ancient Kindle 3 with a keyboard. 

I can try to make some adjustments to those letter hint boxes. Can you direct me to the part of the code that builds the "detailed list with *" layouts?

**Comment by poire-z** [comment]
The letter box sizing and positionning:
https://github.com/koreader/koreader/blob/198a84a772b6bc2f2b652c7537d41a61405efca4/plugins/coverbrowser.koplugin/listmenu.lua#L121-L134

https://github.com/koreader/koreader/blob/198a84a772b6bc2f2b652c7537d41a61405efca4/plugins/coverbrowser.koplugin/listmenu.lua#L791-L803

They are just painted over the normal (without letter boxes) drawing.
If you would wish to tune/hack the normal drawing so it looks different when `self.shortcut` is defined (that must be when the device has a keyboard), it would need hacks in many other places in this file :/

**Comment by alexkiri** [comment]
Thanks for the detailed info. The hacky solution seems pretty dirty, and requires a little more effort than I thought. And since this affects only the old devices with keyboard, I think it's ok to close this issue.
