### ISSUE TITLE
KOReader 2022.11 "Froggy" Highlighting text intermittent

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#10058]
PocketBook ERA PB700

I have been experiencing intermittent problems when highlighting text.

I've come up with a number of workarounds to deal with this issue, but I think it deserves a look here.

The symptom is that sometimes the screen doesn't respond to touch at all, but the most frequent symptom is that the highlight follows the finger down the page - highlighting the text as expected - but then stops after a line or two. After lifting the finger the highlighted section does not persist.

My initial workaround was to power down the reader completely - this was based on my (then) assumption that it was a touchscreen error, but subsequent observations that the screen responded to other selected functions dispelled this as a myth.

Here is a list of some other workarounds that I have tried and found *mostly* successful:

**Changing the "Zoom (dpi) setting**

This sometimes works, but sometimes does not, no single Zoom DPI setting is immune to this issue, and I suspect that changing the setting resets or recalibrates something. I have found that changing and then resetting the Zoom DPI to the original value is just as likely to fix it as staying on the new setting does. It is not 100% effective.

**Changing the "Render Mode" setting**

This sometimes works, I find that switching from "Book" to "Legacy" mode reduces the frequency of this issue but does not eliminate it.

**Additional Observations**

Seems to happen after extended reading (greater than an hour), which to me smells like a memory leak somewhere.

Seems to be worse at the end of a book, especially a book with a lot of highlights. It's possible that the operations required to add additional notes is buggy?

Please let me know if there additional tests I can try or files I can provide to help clarify this issue.

**Comment by hius07** [comment]
What is the device?

**Comment by zmixnyc** [comment]
Sorry, I forgot to mention (added to OP now)

PocketBook ERA PB700

**Comment by NiLuJe** [comment]
Verbose debug logs would be mandatory her,e tosee if we're actually getting a contact lift event from the system (at which point we could file this one as a gameover ;)).

**Comment by zmixnyc** [comment]
Great.!  How do I generate / find those?

**Comment by NiLuJe** [comment]
By reading [the issue template](https://github.com/koreader/koreader/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) ;o).

**Comment by zmixnyc** [comment]
So this?

go to [Tools] → More tools → Developer options, and tick both Enable debug logging and Enable verbose debug logging

**Comment by zmixnyc** [comment]
Is this what you need?

[crash.log](https://github.com/koreader/koreader/files/10538440/crash.log)

**Comment by NiLuJe** [comment]
If you can point to a rough timestamp of when the issue happened, yeah ;).

**Comment by zmixnyc** [comment]
I think I can. 

Looking at the timestamps of my highlights and notes, I can remember which ones were giving me the most trouble.

These were all (eventually) saved on 01/30/23 from about 8:51 until around 9:30

**Comment by NiLuJe** [comment]
On mobile right now, so I can't cross-check, but we'll want to catch a
failure happening *after* you enabled verbose debug logging, as it's
obviously not retroactive :).

**Comment by zmixnyc** [comment]
Debug was already enabled..!

**Comment by NiLuJe** [comment]
Given that first session in the the log starts at 9:29.51 and ends at 9:32:00, you might have to try to replicate it in a controlled setup to actually be able to pinpoint it *exactly* :/.

(Sidebar: The MT handling in our PB input translation layer looks fishy as all hell, but that's probably unrelated).

**Comment by zmixnyc** [comment]
I don't think I did anything but open the book, try to highlight then export highlights.

Within that I went through several iterations of my workarounds (mentioned in the OP)

I could easily try the same now and send another log if it would help?

**Comment by zmixnyc** [comment]
Here you go,  I powered up the reader, launched KOReader, loaded the book attempted to highlight a paragraph and ll it did was create a grey rectangular highlighted area across some of the text, but  never made the actual highlight.

I repeated this 2 or 3 times.

Here is the resulting log..!

[18.03.Crash.log](https://github.com/koreader/koreader/files/10540718/18.03.Crash.log)

**Comment by NiLuJe** [comment]
Oops, forgot to mention another PB shenanigan: check if disabling autostandby helps (as would a topped up/plugged in device)?

**Comment by zmixnyc** [comment]
Auto Standby was selected in the Plugin management menu, I toggled it off and after re-booting the highlighting seemed to work, *however* when I toggled it back on and rebooted the problem didn't return, so I am not sure if that was the issue?

I repeated testing with different settings and couldn't provoke the problem, but like I said in the OP , it's intermittent..!

**Comment by NiLuJe** [comment]
Given that I'm seeing some spurious MovableContainer moves in your log, and that lifting a contact after a highlight creates a... MovableContainer for the popup asking you what yo do about your selection, mixed with the PB factor, AutoStandby, and your battery comment, it *smells* very much like a PB-special around background standby wrecking havoc...

**Comment by zmixnyc** [comment]
I didn't specifically mention, but should:

The symptom of it *not* working is that the KOReader popup highlight editor window with the 'delete/style/add note/..."
does not appear - leaving the selected text sitting there in it's grey box!!

**Comment by NiLuJe** [comment]
xref #9385, #9493, #10058

I think @rjd22 has an autostandby rework in the pipes, that *should* alleviate these issues...

**Comment by rjd22** [comment]
@NiLuJe still need to make some time to finish that and test it. :P

**Comment by pazos** [comment]
Closing in favor of #9493

**Comment by zmixnyc** [comment]
Updated both the Pocketbook FW and the latest KOReader beta this morning (April 9 2024)and this problem persists.

It's now confined to selecting tect in the middle of the page - my highlight style is 'underline' and text selected in the middle of the page is represented as 'lighten' - grey blocking around the selected text, but never saved as a highlight.

**Comment by pazos** [comment]
> Updated both the Pocketbook FW and the latest KOReader beta this morning (April 9 2024)and this problem persists.
> 
> It's now confined to selecting text in the middle of the page - my highlight style is 'underline' and text selected in the middle of the page is represented as 'lighten' - grey blocking around the selected text, but never saved as a highlight.


I understand. Please read the "favorite" ticket, try all the workarounds suggested there.  

If you find a workaround keep us updated. If you have a question ask there :)

**Comment by zmixnyc** [comment]
> > Updated both the Pocketbook FW and the latest KOReader beta this morning (April 9 2024)and this problem persists.
> > It's now confined to selecting text in the middle of the page - my highlight style is 'underline' and text selected in the middle of the page is represented as 'lighten' - grey blocking around the selected text, but never saved as a highlight.
> 
> I understand. Please read the "favorite" ticket, try all the workarounds suggested there.
> 
> If you find a workaround keep us updated. If you have a question ask there :)

Thank you for the reply.  What is the "favorite ticket"?

My workaround is to change the display from 'portrait' to 'landscape' and then select the text, or double click the button to put the Pocketbook to sleep then click again to wake, either of these will allow me to select the text as expected.

**Comment by rjd22** [comment]
> > > Updated both the Pocketbook FW and the latest KOReader beta this morning (April 9 2024)and this problem persists.
> > > It's now confined to selecting text in the middle of the page - my highlight style is 'underline' and text selected in the middle of the page is represented as 'lighten' - grey blocking around the selected text, but never saved as a highlight.
> > 
> > 
> > I understand. Please read the "favorite" ticket, try all the workarounds suggested there.
> > If you find a workaround keep us updated. If you have a question ask there :)
> 
> Thank you for the reply. What is the "favorite ticket"?
> 
> My workaround is to change the display from 'portrait' to 'landscape' and then select the text, or double click the button to put the Pocketbook to sleep then click again to wake, either of these will allow me to select the text as expected.

Sounds like an sleeping issue. It might be that selecting text while the device has gone to sleep will results in unexpected behavior.

**Comment by zmixnyc** [comment]
> > > > Updated both the Pocketbook FW and the latest KOReader beta this morning (April 9 2024)and this problem persists.
> > > > It's now confined to selecting text in the middle of the page - my highlight style is 'underline' and text selected in the middle of the page is represented as 'lighten' - grey blocking around the selected text, but never saved as a highlight.
> > > 
> > > 
> > > I understand. Please read the "favorite" ticket, try all the workarounds suggested there.
> > > If you find a workaround keep us updated. If you have a question ask there :)
> > 
> > 
> > Thank you for the reply. What is the "favorite ticket"?
> > My workaround is to change the display from 'portrait' to 'landscape' and then select the text, or double click the button to put the Pocketbook to sleep then click again to wake, either of these will allow me to select the text as expected.
> 
> Sounds like an sleeping issue. It might be that selecting text while the device has gone to sleep results in unexpected behavior.

Some more fact points to consider:

When the issue occurs, I can select text  anywhere else on a page - except in the middle of the screen. 

When playing the built-in card game ("Klondike" aka Solitaire aka Patience) it will not register any attempt to move a card to or from the center positions.  Examining the behavior there reveals that the card you are trying to move becomes 'de-selected' immediately after you slide your finger to the new location.

In each case re-booting, forcing sleep/wake resets the correct behavior.
