### ISSUE TITLE
FR: Reading statistics - replace time spent with book to time read the book

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10054]
**Does your feature request involve difficulty completing a task? Please describe.**
Can you please replace the time spent with the book to time actually read the book in Reading statistics? (In the menu where I can delete them one by one) 

**Describe the solution you'd like**
Current showed time is not useful, because it shows the time I read + time I spent tweaking the book and opened a bunch of menu with the book on the background. If I tweak the book in the beginning, I usually wipe the statistics before actually reading. If I do it after a few hours of good reading, I don’t want to wipe the statistics anymore. However, the end result is that the books’ time in Readings statistics is not representative and comparable.  

**Describe alternatives you've considered**
I just try to keep the clean statistics from the beginning, but sometimes I need to test or troubleshoot bugs mid-book. 

**Additional context**
What was the intent for this “Time spent in the book” overall? I can’t imagine it being useful other than debugging time maybe. 

*P.S.* Maybe I should open a separate ticket, but I think “Delete statistics one by one” (forgot the exact wording, sorry) should be renamed to something like “Statistics overview” which shows the same information as it does now, but with “Long press a title to delete it”. The time ranges (delete books < x min) can go in there with a triple-line menu icon maybe?

Otherwise, reading statistics is great, it has no match in any eink and non-eink reading apps! I can now finally quantitatively judge what time I spend in books of different languages :D 

Thank you everyone who participated in this feature design and implementation!

**Comment by jospalau** [comment]
This would be nice. I also spend some time tweaking books while reading. 

And I totally agree with this:
 _it has no match in any eink and non-eink reading apps!_

**Comment by Kelamir** [comment]
Interesting. Can confirm - you can reproduce this by starting a session with statistics enabled, open a menu for a while such as the VocabularyBuilder addon, go back to the book and flip a page. You will see that it has counted the time spent in that menu in "Tme spent reading this session". 

Normally, this can be dealt with setting "read page duration limits" - limits time not spent reading fairly well, and for most use cases I'd call this sufficient. So what I can see proposed here is a further optimization for improving precision of the statistics. 

How exactly can this be accomplished? @mergen3107  this is the point you have to make clear. Perhaps, the addon would have to stop counting time anytime there's any menu opened, and continue going when the text is back full screen. However, that brings its own issues: you can read while a menu is opened, which is a normal situation. Consider for example reading books inside the translation window, where you are provided line by line translations. This is a parallel reading of sorts and should be included in statistics.

**Comment by mergen3107** [comment]
1) Currently I am not asking to change the way it counts the time read. I am asking to replace one existing variable with another. If you go to the Book information (with all details about times like time per page), it already has both time read and time time spent. So in this FR I am just asking to use the time read in the Reading statistics delete menu. 

2) IMHO, “Count statistics while menu is open” should be an optional setting, disabled by default. Most of the devices (I suppose) have 6-inch screen that do not probably allow comfortable reading with menus open.

**Comment by NiLuJe** [comment]
Toggling 2 off is not going to happen, it would be extremely messy to handle properly.

**Comment by mergen3107** [comment]
Maybe any user patches can be made?

**Comment by mergen3107** [comment]
Is this just a matter of reaplacing `total_time_book` with `book_read_time` here?

https://github.com/koreader/koreader/blob/3c63a5d8a80724506b39fcbf64a16895cb903501/plugins/statistics.koplugin/main.lua#L2451
