### ISSUE TITLE
FR: Page information

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#10053]
It would very useful to have a handy way like a menu entry to check the information for a given page while reading like number of lines, words and characters.

Thanks

**Comment by poire-z** [comment]
Just asking: _very useful_ for what ? What will you do or gain knowing these info for that page ? And for that other page, and for that other page ?

**Comment by mergen3107** [comment]
I wouldn’t mind to have line numbers as well. Actually, I did 30 lines for each of my 21 profiles so that 1) book size is about the same a paperback size; 2) all profiles yield about the same number of pages (+\- 5%). For this I also change font size and line spacing.

**Comment by jospalau** [comment]
I didn't know you could select different a font in the profiles. I think that was not possible when I checked 1 year ago and wanted to use them. Thanks. That really helps and changes the game.

**Comment by mergen3107** [comment]
Yes, welcome to the club :D ask me all about it if you need. You can start by going to the USER GUIDE (pinned ticket at the very top of Issues), then search by adding “author:mergen3107 profile” in the Issues, including closed ones to get a better picture

**Comment by jospalau** [comment]
Wow, I just found this:
https://github.com/koreader/koreader/issues/9594

I can list the profiles and apply individual settings after listing a given profile with a quick gesture. Is it a way to apply the full profile? 

The idea is to create all the profiles for all my devices and activate the ones I am interested in for a given device.

**Comment by mergen3107** [comment]
So a “profile” is not a full profile - it is only the number of settings that you select specifically. 

There are recent ongoing discussions and implementations of saving all current settings into a profile. I am on mobile right now but try to search for it, it’s been around a week. 

As for the crash, open a new ticket and include crash.log file so we can investigate.
