### ISSUE TITLE
DictQuickLookup: add a "More..." button ?

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#10056]
Been reading some book with Ancient Greek words recently, and I got a bit frustrated with the results I got from my dictionaries (I have 2 Greek>FR/EN dicts that did not give good results), and I would have liked to fallback to Translate to at least get something from know-it-all-Google.
And to reach Translate, I had to close the DictQuickLookup window, re-do the highlight, wait for the long-long-press duration to get the HighlightDialog instead (or hit Highlight in the DictQuickLookup, close it, tap on the highlight, tap `...` then finally hit `Translate`.

So, I wonder if it would make sense to replace one of these 3 buttons with a `More...`, that would launch the Highlight dialog ? And if yes, which one among these 3 ?

![image](https://user-images.githubusercontent.com/24273478/215260430-28f1694a-f1a0-40c9-a1a7-f8f069f9cb89.png)

I would think having it at the bottom left one would feel right, but then it makes it harder with its twin brother:
![image](https://user-images.githubusercontent.com/24273478/215260678-6ba6b20e-2323-48ac-8bac-5c6d545104fc.png)
So, the simpler to replace would be the `Highlight` top middle button.

I also thought it would be nice to introduce a PopupButtonWidget, that we don't have yet, that could popup from an existing button, showing something similar to a single column ButtonTable, not standalone, but anchored on the originating button, poping above or below depending on its height and the space available. This could also be used for the top left and right TitleBar buttons (poping below).
So, this could work on such a `More...` button.

Mockups with mspaint:
![image](https://user-images.githubusercontent.com/24273478/215261436-dd5ced5d-4afd-4d29-ae67-cbbf5387e420.png)

![image](https://user-images.githubusercontent.com/24273478/215261714-34a06833-f074-462b-9eb9-f1691eab0372.png)

(Anyway, too busy with other things currently to work on that, just throwing this for discussion :))

**Comment by hius07** [comment]
> And to reach Translate

Why didn't you press the pencil button in DQL?

**Comment by poire-z** [comment]
Because I never use it, and didn't know Translate was available in it :)

![image](https://user-images.githubusercontent.com/24273478/215263714-97e37cf4-641b-45a2-a51a-05c7cb2c0470.png)

So, ok, that would solve my main issue :)

Anything else that would still be useful in a More... button or from the existing Highlight dialog, that would not be reachable from the DictQuickLookup itself or the pencil button ? :)

**Comment by hius07** [comment]
We've discussed it in https://github.com/koreader/koreader/issues/7511.

After closing DQL the highlight is kept and its popup menu is still opened. To achieve it we need the same one tap as with the proposed More... button.

**Comment by poire-z** [comment]
My memory of everything we dicussed can overflow :)

> After closing DQL the highlight is kept and its popup menu is still opened. 

Not following you here - as after a normal single word highlight and DQL launch, no popup menu opens and the highlight is cleared when closing DQL. So, you must have another "workflow" in mind that I don't manage to guess.

**Comment by hius07** [comment]
Oh, yes, I have unchecked Dictionary on single word selection.

**Comment by poire-z** [comment]
> I also thought it would be nice to introduce a PopupButtonWidget, that we don't have yet, that could popup from an existing button, showing something similar to a single column ButtonTable, not standalone, but anchored on the originating button, poping above or below depending on its height and the space available. This could also be used for the top left and right TitleBar buttons (poping below).

I had a little light-bulb moment :) we don't really need any new widget, we can just "anchor" any widget to an existing button, when that widget is movable, by having its MovableContainer compute the initial "move offsets" so it gets anchored to the provided button ! (and after that initial display, we can move/detach it for free).

I'm not suggesting we should switch these examples, I'm just showing off :):
```lua
                     callback = function()
+    local ButtonDialog = require("ui/widget/buttondialog")
+    local widget = ButtonDialog:new{
+        width = 100,
+        buttons = {
+            {{ text="Wikipedia", callback = function() end }},
+            {{ text="Translate", callback = function() end }},
+            {{ text="Copy to clipboard", callback = function() end }},
+            {{ text="Append to clipboard", callback = function() end }},
+            {{ text="QR Code", callback = function() end }},
+        },
+        anchor = function()
+            return self.button_table:getButtonById("wikipedia")
+        end,
+    }
+    UIManager:show(widget)
+    if true then return end
+
```

![image](https://user-images.githubusercontent.com/24273478/223541784-2d29c907-f5b8-4e94-bd70-bfb23dfea46e.png)

```lua
         bm_dialog = ButtonDialogTitle:new{
             title = dialog_title,
+            width = 250,
             title_align = "center",
             buttons = buttons,
+            anchor = function()
+                return bm_menu.title_bar.left_button.image
+            end
         }
```

![image](https://user-images.githubusercontent.com/24273478/223541913-debb05c5-183a-4330-bb9d-88be54b2adf4.png)

I actually want to add some CSS "poor man cheat sheet" to the Book style tweak dialog (because I never remember these 2 first ones.... stupid idea I had to name it `footnote-inpage` where everywhere else we say "in-page footnotes"...):
![image](https://user-images.githubusercontent.com/24273478/223542834-70f67c8c-d748-4fc4-9df5-3e6aebcfc24f.png)

Would you agree it's best put into a button as above, rather than as an additional button in the popup we get with long-press (which is partially about pasting, but firstly about the clipboard - that these suggestions aren't really):
![image](https://user-images.githubusercontent.com/24273478/223543464-326def74-20da-4044-a145-c393296c4d83.png)

**Comment by Frenzie** [comment]
That's an excellent idea. It has been suggested to do the top menu that way too, but there I've always appreciated being able to use it from both sides and I felt it would be a bit form over function (that's not an objection per se, but definitely a lack of enthusiasm for the proposal :-) ). But for these types of widgets that's never been a thing in the first place, nor can it be.

**Comment by poire-z** [comment]
I absolutely don't want to change our top menu ! :) and I don't plan on adding some kind of sub_menu feature to anything we use build that way.
But it can indeed be useful when we need more actions, ie. in Bookmap or PageBrowser where I could associate only 2 actions to the top left (i) icon, one for tap and one for long-press.

**Comment by poire-z** [comment]
Any preference among these 3 different styles?:

![image](https://user-images.githubusercontent.com/24273478/224501862-81835890-0584-43ee-a6c1-b94ea979d29c.png) **A**

![image](https://user-images.githubusercontent.com/24273478/224499578-c5c8952b-694a-4b52-bd97-adc2c4f10ecf.png) **B**

![image](https://user-images.githubusercontent.com/24273478/224499832-71a325c3-3ca1-4a04-ae44-d60c9c4e5281.png) **C**

**Comment by NiLuJe** [comment]
Minor preference for the third one, but I may have a weird fetish for center aligned text ;p.

**Comment by hius07** [comment]
If the button table is placed in the center of the screen I would prefer the third one.
So the question: is anchoring to the title bar left button required?

**Comment by NiLuJe** [comment]
I feel like the anchoring makes perfect sense given that it's a context menu, anchoring it to its context (the hamburger icon) makes sense. (i.e., I see this as a right-click menu; its anchored to your cursor).

**Comment by hius07** [comment]
I think that the popup menus called via titlebar must be consistent, anchored or centered, not jumping out unexpectedly.
If anchored, some of the existing menus should be reconstructed, for example bookmarks filtering.

**Comment by NiLuJe** [comment]
> If anchored, some of the existing menus should be reconstructed, for example bookmarks filtering.

How does that one behave right now?

**Comment by poire-z** [comment]
I'm biased towards the anchored way, as it's new :)
Also, I think it depends on what's in it. There, I may have overcrowded it because I could :) At minima, it could be just a few "menu" items showing some help in an InfoMessage.
It also depends on whether it's 1 column or more, and the width required. That is, if it looks like a menu (like my initial attemps here), or like a real button table :)
For bookmarks or the filebrowser + menu, given the amount of info and actions they allow, having it centered feels ok.
(Also, I initially thought having that menu at the top left wasn't really practical for right handed people - but one actually has to use its left hand to tap on the top left icon and open it :)

But may be we can decide that later, once we see and use the various possibilities, if there's really a will to go toward hard consistency ?

**Comment by NiLuJe** [comment]
> But may be we can decide that later, once we see and use the various possibilities, if there's really a will to go toward hard consistency ?

Yeah; this one makes perfect sense (to me) anchored; but that may be somewhat context-sensitive, so unification on that point may not be a great ide aanyway ;).

**Comment by hius07** [comment]
> It also depends on whether it's 1 column or more, and the width required. That is, if it looks like a menu (like my initial attemps here), or like a real button table :)

Exactly, the first one (a classical menu) is good to be anchored, but the third one (which content looks better) asks to be centered.

**Comment by poire-z** [comment]
So, what about the second ? :)

The thing is that I may have more than one simple menu items, like "About page browser", "Available gestures", which feels they should be in a "classical menu", left aligned. If I mix them with the +/-, and have the thing centered, it would look a bit odd - or I would have to center all items, which would also feel odd (in my above screenshot, the standalone "About page browser" could feel like a dialog title - would feel more strange if they were manu).

So, if we prefer to get it to look like a non-fancy "classical menu", logically, we should have:
```
About page browser
Available gestures
Columns and rows                 (which would launch a DoubleSpinWidget)
Bottom ribbon chapter levels     (which would launch a SpinWidget)
```

The thing is that we don't need these spinwidgets :), as we can already change them with swipe on the sides - I just thought I could duplicate them for free and to somehow give more "body" to this menu. And may be one could then add some FocusManager magic to it so PageBrowser is usable on non-touch devices.

**Comment by mergen3107** [comment]
+1 to the third one.

**Comment by poire-z** [comment]
Another idea (will be a bit more complicated to get the widths right):
![image](https://user-images.githubusercontent.com/24273478/224505954-91b4adf7-94d8-46ff-b417-9ecfce09382b.png)

**Comment by NiLuJe** [comment]
That one *may* be slightly less confusing from a UX standpoint, buuuut, yeah, might need to be wider to accomodate that ;).

**Comment by hius07** [comment]
The last one is interesting as well.

**Comment by poire-z** [comment]
Closing as the original issue has some solutions.
Widget ideas have been added via #10230.
