### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by rayman3003** [koreader/koreader#10063]
Can we have a Windows version already?

KOreader has some good potentials & I'm sure Windows users gonna love this good full-featured ebook reader.

So why not?

Please make the KOreader more popular.

**Comment by NiLuJe** [comment]
Because it runs under WSL2 ;o).

It used to possibly run when built via a MinGW TC, but this hasn't been tested in years (due to lack of developer interest, mainly due to the above point).

**Comment by rayman3003** [comment]
> Because it runs under WSL2 ;o).

But it is not user-friendly for a normal windows user, to install a DISTRO on windows, to run just an ebook reader! 😅 Don't u think so?

> due to lack of developer interest

So bad. 😢

**Comment by pazos** [comment]
Duplicate of #7653

**Comment by pazos** [comment]
Yes. Please don't open duplicates. 

You can comment there if you wish.
