### ISSUE TITLE
FR: [Improve Epub Files Loading]

### ISSUE THREAD

**Issue by HuangSmith** [koreader/koreader#10069]
I have some Epub files contains 10, 20 or even 100 books in a single file.  (Not to mention that these files have lots of texts, pics, etc.) It's frustrating to open it in KoReader since it always renders all the pages before I read.
If KoReader can render the first page (For new books), or the last page I've read (For opened books), then render the other pages on demand when I read forward or backward (or even jump to other pages), my e-ink reader (a jailbroken Kindle 8) won't have to take 20 miuntes or even a hour just to open a book.
Time's Precious, Everyone.

**Comment by hius07** [comment]
You can become a tester: https://github.com/koreader/koreader/issues/9087#issuecomment-1407852568

**Comment by poire-z** [comment]
> You can become a tester

This won't help with the initial opening, just rerenderings (we need the full DOM to allow these later partial rerenderings).

> I have some Epub files contains 10, 20 or even 100 books in a single file. 
> won't have to take 20 miuntes or even a hour just to open a book.

Even with the above, and even if we were to have partial rendering on open, we would NEED to have a full rerendering in background. So, if opening/rendering takes 20 minutes or 1 hour, that means your device probably lost 20% or 60% of battery doing that :)
So, you're probably best not having such huge epub files, and split them - KOReader/crengine won't/can't do what you want, that's just not how the engine works.
