### ISSUE TITLE
Crash when exporting all highlights to Markdown: author is nil

### ISSUE THREAD

**Issue by CRCulver** [koreader/koreader#10070]
* KOReader version: 2023.01
* Device: Kobo Libra 2

#### Issue

When attempting to export all highlights  from my library to Markdown, Koreader crashes immediately, with luajit complaining about an attempt to index a nil value for field "Author". Even with verbose logging turned on, the crash log does not provide any information about what file, if any, is causing the problem.

My library consists of thousands of PDFs and Djvu files. As is common with these kinds of files, they may lack any Author and/or Title field in the metadata.

#### Steps to reproduce

From main menu "Export all notes in your library", with Markdown already selected as the sole export format.

[crash.log.txt](https://github.com/koreader/koreader/files/10574413/crash.log.txt)

**Comment by NiLuJe** [comment]
Relevant excerpt:

```
./luajit: plugins/exporter.koplugin/template/md.lua:42: attempt to index field 'author' (a nil value)
stack traceback:
	plugins/exporter.koplugin/template/md.lua:42: in function 'prepareBookContent'
	plugins/exporter.koplugin/target/markdown.lua:128: in function 'export'
	plugins/exporter.koplugin/main.lua:184: in function 'action'
	frontend/ui/uimanager.lua:987: in function '_checkTasks'
	frontend/ui/uimanager.lua:1428: in function 'handleInput'
	frontend/ui/uimanager.lua:1551: in function 'run'
	./reader.lua:315: in main chunk
	[C]: at 0x000140bd
```

**Comment by hius07** [comment]
Fixed by https://github.com/koreader/koreader/pull/10278.
