### ISSUE TITLE
Pagebreak not respecting margin

### ISSUE THREAD

**Issue by Kayzels** [koreader/koreader#10073]
* KOReader version: 2023.01
* Device: Kindle Paperwhite 3

#### Issue
If an ebook has a forced pagebreak in a certain place (`page-break-after: always`), then the top margin of the element following it is not used. This means that the element is close to the top of the screen. This occurs whether the margin is stated in percentage or em.

### Expected Behaviour
The margin of the second element should be included. It should ignore the bottom margin of the element preceding it with the pagebreak, if possible.

### Calibre Viewer Screenshots
![calibre_page1](https://user-images.githubusercontent.com/72696811/216575304-223beef8-f6f8-488b-95b7-93bc5cacf151.png)
![calibre_page2](https://user-images.githubusercontent.com/72696811/216575332-3420c6bf-f340-4f3f-86e4-b664cae384db.png)

### Koreader Screenshots
![Reader_2023-02-03_121910](https://user-images.githubusercontent.com/72696811/216575853-049f9fcf-91d8-4a70-b989-913849328e42.png)
![Reader_2023-02-03_121927](https://user-images.githubusercontent.com/72696811/216575884-76e092c9-a46c-4677-9e52-0890b647a0ef.png)

#### Steps to reproduce
1. Create an ebook with an element that contains the css rule `page-break-after: always`. Assign this element a margin of some value.
2. Create an element after the above element, and assign this element a top margin.
3. Open the ebook, and see that the second element's top margin isn't respected.

### Sample epub3 ebook with the above elements, in zip file
[pagebreak.zip](https://github.com/koreader/koreader/files/10578006/pagebreak.zip)

**Comment by poire-z** [comment]
Thank you for the simple sample file.
I agree with your observations and expectations, and that this is a bug.

I had many suspects:
- my collapsing margins code from https://github.com/koreader/crengine/pull/299 and the tedious parts handling them https://github.com/koreader/crengine/blob/dd3cb231b9abc9132af33a5a1c837e189b66878d/crengine/src/lvrend.cpp#L5834-L6258 . The fact that the margin is there when choosing `Render mode: legacy`, which is explicitely not using this code, makes it feel like the suspect. But the fact that the margin is there in scroll mode limits the involved code: it must be the page splitting stuff, and the AddLine() there.
- my alternative page splitting code from https://github.com/koreader/crengine/pull/443 - as reenabling the original page splitting code gets that margin shown !

Adding a few printf here and there, and I got to see an unexpected value for `last_split_after_flag` : 130, when I expect only 0, 1 or 2.

So, it might be not really much of the above tedious code, but a slight oversight at the bottom (my code) of this:
https://github.com/koreader/crengine/blob/dd3cb231b9abc9132af33a5a1c837e189b66878d/crengine/include/lvpagesplitter.h#L32-L58

```diff
 #define RN_GET_SPLIT_BEFORE(flags) (flags & 0x7)
-#define RN_GET_SPLIT_AFTER(flags) (flags >> 3)
+#define RN_GET_SPLIT_AFTER(flags) ((flags >> 3) & 0x7)
```
seems obvious and logical, and it does fix this margin issue ! (And I won'd hide that I'm happy that I don't have to look more at any collapsing margins and page splitting code :)

Revamped page splitting before (with your sample, and a hardcode 150px margin-top, but all other margins removed to make it simpler, so the 0s in there):
```
pushing vertical margin 0 (0 0) last_split_after_flag=0 next_split_before_flag=0
pushing vertical margin 0 (ca11f3c0 0) last_split_after_flag=0 next_split_before_flag=0
pushing vertical margin 0 (ca11f3d0 1) last_split_after_flag=0 next_split_before_flag=0
PS: AddLine (5647450, #0): 0 > 0 (10)
PS: AddLine (5647450, #1): 0 > 17 (0)    # the blockquote text
pushing vertical margin 0 (0 1) last_split_after_flag=0 next_split_before_flag=0
PS: AddLine (5647450, #2): 17 > 17 (1040)
pushing vertical margin 150 (ca11f410 4) last_split_after_flag=130 next_split_before_flag=0
         # this last_split_after_flag=130 is odd and unexpected, probably causing what happens next
PS: AddLine (5647450, #3): 17 > 167 (1024) # the 150px top margin
         # this 1024 = DISCARD_AT_START should not be there, and is what make the margin discarded
PS: AddLine (5647450, #4): 167 > 190 (0)  # the H2 text
pushing vertical margin 0 (0 4) last_split_after_flag=0 next_split_before_flag=0
PS: AddLine (5647450, #5): 190 > 190 (9)
pushing vertical margin 0 (0 4) last_split_after_flag=1 next_split_before_flag=0
PS: splitting lines into pages, page height=568
PS:   line 0>0 h=0, flags=<2|1>
PS:   line 0>17 h=17, flags=<0|0>
PS: adding (0+17) to current page 0>0
PS:   line 17>17 h=0, flags=<0|2>
PS: adding (0+0) to current page 0>17
PS: ========= ADDING PAGE 0: 0 > 17 h=17 [rtl l:0/3 fl:0/0]
PS:   line 17>167 h=150, flags=<0|0>
PS: adding (0+150) to current page 17>17     somehow these 150 won't make it to the page
PS:   line 167>190 h=23, flags=<0|0>
PS:   line 190>190 h=0, flags=<1|1>
PS: adding (0+23) to current page 167>167
PS: ========= ADDING PAGE 1: 167 > 190 h=23 [rtl l:0/2 fl:0/0]
```


Revamped page splitting after:
```
pushing vertical margin 0 (0 0) last_split_after_flag=0 next_split_before_flag=0
pushing vertical margin 0 (8fed91f0 0) last_split_after_flag=0 next_split_before_flag=0
pushing vertical margin 0 (8fed9200 1) last_split_after_flag=0 next_split_before_flag=0
PS: AddLine (28a51060, #0): 0 > 0 (10)
PS: AddLine (28a51060, #1): 0 > 17 (0)
pushing vertical margin 0 (0 1) last_split_after_flag=0 next_split_before_flag=0
PS: AddLine (28a51060, #2): 17 > 17 (1040)
pushing vertical margin 150 (8fed9240 4) last_split_after_flag=2 next_split_before_flag=0
PS: AddLine (28a51060, #3): 17 > 167 (0)
        # these 2 lines above feel more correct
PS: AddLine (28a51060, #4): 167 > 190 (0)
pushing vertical margin 0 (0 4) last_split_after_flag=0 next_split_before_flag=0
PS: AddLine (28a51060, #5): 190 > 190 (9)
pushing vertical margin 0 (0 4) last_split_after_flag=1 next_split_before_flag=0
PS: splitting lines into pages, page height=568
PS:   line 0>0 h=0, flags=<2|1>
PS:   line 0>17 h=17, flags=<0|0>
PS: adding (0+17) to current page 0>0
PS:   line 17>17 h=0, flags=<0|2>
PS: adding (0+0) to current page 0>17
PS: ========= ADDING PAGE 0: 0 > 17 h=17 [rtl l:0/3 fl:0/0]
PS:   line 17>167 h=150, flags=<0|0>
PS: adding (0+150) to current page 17>17     # does make it into the page
PS:   line 167>190 h=23, flags=<0|0>
PS:   line 190>190 h=0, flags=<1|1>
PS: adding (0+23) to current page 17>167
PS: ========= ADDING PAGE 1: 17 > 190 h=173 [rtl l:0/3 fl:0/0]
```

I'll push a fix with just this in my next crengine PR (after using this for a bit and being sure it causes no other issue):
```diff
-#define RN_GET_SPLIT_BEFORE(flags) (flags & 0x7)
-#define RN_GET_SPLIT_AFTER(flags) (flags >> 3)
+#define RN_GET_SPLIT_BEFORE(flags) ((flags >> RN_SPLIT_BEFORE) & 0x7)
+#define RN_GET_SPLIT_AFTER(flags)  ((flags >> RN_SPLIT_AFTER)  & 0x7)
```

(Congrats for reporting this bug, which might be the first report related to these collapsing margins and page splitting code. I thought that spending that much time on these bits, and with no issue reported for years, I was sometimes able to write bug free code :) I can now come back to earth :)
