### ISSUE TITLE
Can't change font - only in specific epub

### ISSUE THREAD

**Issue by doozan** [koreader/koreader#10079]
I just started reading a new book and I can't seem to get the font to change. I can change the font just fine in other documents. The list of fonts shows everything as expected and even renders each font correctly in the list, but no matter what I select it just pauses for a second and then checks the box next to the font without actually applying it to the document. I'm guessing it's just something silly with CSS in the book but I'm not sure where to look. I enabled verbose debug logging (attached) but I don't see anything interesting, there are no errors in the logs when I try to change fonts.

* KOReader version: v2023.01 (also exists in v2022.07)
* Device: kindle
[verbose_debug_log.txt](https://github.com/koreader/koreader/files/10593634/no_font_change.txt)

**Comment by mergen3107** [comment]
Disable embedded fonts (bottom menu, rightmost tab)
