### ISSUE TITLE
kodev wbuilder crashes with "attempt to index global 'G_defaults' (a nil value)"

### ISSUE THREAD

**Issue by salexan2001** [koreader/koreader#10084]
* KOReader version: commit 3881899338fbd05d1acd3e08d0dcf012f748bab4
* Device: Linux 6.1.7-arch1-1 (archlinux)

#### Issue

I tried to run the command `./kodev wbuilder` from the main kodev directory.

The program does not start with luajit reporting the following error message:

```
./luajit: frontend/ui/widget/iconwidget.lua:10: attempt to index global 'G_defaults' (a nil value)
stack traceback:
	frontend/ui/widget/iconwidget.lua:10: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:25: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/menu.lua:4: in main chunk
	[C]: in function 'require'
	./tools/wbuilder.lua:30: in main chunk
	[C]: at 0x5635233cb79d
```

By comparing `reader.lua` and `tools/wbuilder.lua` the solution turns out to be pretty straight-forward:
Adding the line `G_defaults = require("luadefaults"):open()` close to the beginning to `wbuilder.lua` makes the program run normally.

I just started developing a little bit in koreader, so I'm not completely familiar with the dev-workflow yet (and thought it's probably best to submit an issue before just creating a pull request). Maybe I just missed something during setup?

#### Steps to reproduce

Just run `./kodev wbuilder` from a fresh build environment on the above commit.
(Setup was done as described in https://github.com/koreader/koreader/blob/master/doc/Building.md#getting-the-source)
(`./kodev run` works correctly)

**Comment by Frenzie** [comment]
That'll be new since #9546. You probably shouldn't add but replace. Want to make a PR? ^_^

```diff
diff --git a/tools/wbuilder.lua b/tools/wbuilder.lua
index b0f4fd98d..861333914 100755
--- a/tools/wbuilder.lua
+++ b/tools/wbuilder.lua
@@ -1,7 +1,8 @@
 -- widget test utility
 -- usage: ./luajit tools/wtest.lua
 
-require "defaults"
+-- Load default settings
+G_defaults = require("luadefaults"):open()
 print(package.path)
 package.path = "common/?.lua;rocks/share/lua/5.1/?.lua;frontend/?.lua;" .. package.path
 package.cpath = "common/?.so;common/?.dll;/usr/lib/lua/?.so;rocks/lib/lua/5.1/?.so;" .. package.cpath
```

> I just started developing a little bit in koreader, so I'm not completely familiar with the dev-workflow yet (and thought it's probably best to submit an issue before just creating a pull request). Maybe I just missed something during setup?

Sometimes it's helpful, much of the time it doesn't make a difference. So yeah, the workflow is simply to fix it up when you need it because it's usually forgotten (although breaking changes are hopefully fairly rare).

**Comment by salexan2001** [comment]
ok, done. :-)
