### ISSUE TITLE
Unresponsive tab icons in the top menu

### ISSUE THREAD

**Issue by IvoFelix** [koreader/koreader#10089]
* KOReader version: 2023.01
* Device: Kobo Aura
* Firmware version: 4.35

#### Issue

Tab icons in the top menu are unresponsive while reading an .epub file, while the menu items themselves work.

#### Steps to reproduce

Open an .epub file, click the top section of the page to open the top menu, then try to use one of the tab icons to change menu tabs.

Note: I've tested with .epub files only, not sure if it happens in other formats.

**Comment by NiLuJe** [comment]
That's... weird?

I assume you have no issue witth the exact same menu (well, nearly) while in the filemanager?

As usual, i'm going to ask for verbose debug logs, in case something jumps out in there...

**Comment by NiLuJe** [comment]
Does tapping nearer to either the left or right corner (but not exactly, unless you've disabled said corner tap zones) lead to a different behavior than tapping in the center?

(That should affect the starting tab: left forces the leftmost tab, right forces the rightmost tab, anything else opens same tab as last time).

**Comment by IvoFelix** [comment]
> That's... weird?
> 
> I assume you have no navigation issues with the exact same menu (well, nearly) while in the filemanager?
> 
> As usual, I'm going to ask for verbose debug logs, in case something jumps out in there...

The menu in the filemanager has the same issue, I'm afraid, so I cannot enable verbose logs that way... Is there a config file somewhere for me to manually enable it?

> Does tapping nearer to either the left or right corner (but not exactly, unless you've disabled said corner tap zones) lead to a different behavior than tapping in the center?
> 
> (That should affect the starting tab: left forces the leftmost tab, right forces the rightmost tab, anything else opens the same tab as last time).

Clicking to the left or right instead of the center has no effect as well, the entire upper section where the menu tab icons are located is unresponsive and I did not change any settings (I can only access the first tab of the menu anyway, which is the one active when you open it).

**Comment by NiLuJe** [comment]
> Clicking to the left or right instead of the center has no effect as well, the entire upper section where the menu tab icons are located is unresponsive and I did not change any settings (I can only access the first tab of the menu anyway, which is the one active when you open it).

I meant *before* opening the menu ;).

> Is there a config file somewhere for me to manually enable it?

It's probably going to be easier to edit the startup script (`.adds/koreader/koreader.sh`) to pass `-d -v` args to the main script.

https://github.com/koreader/koreader/blob/9d2ac3a0fc79f5984f3d793042f41029f0ab254a/platform/kobo/koreader.sh#L401

=>

```
    ./reader.lua -d -v "$@" >>crash.log 2>&1
```

**Comment by NiLuJe** [comment]
I assume you've ruled out the obvious "the touch screen is borked in those top few pixels"?

**Comment by IvoFelix** [comment]
Sorry for taking so long to reply, it's been some hectic few days.

> I meant _before_ opening the menu ;).

Ah, I see what you mean! Yes, clicking to the left or right for opening the menu has the inteded effect of opening the left-most or right-most tab.

> I assume you've ruled out the obvious "the touch screen is borked in those top few pixels"?

Yes, of course. That top section of the touch screen works fine on the main menu of the kobo and on koreader I can even click there to open the menu that is having problems.

I've enabled verbose logging as you described and here is the [crash.log](https://github.com/koreader/koreader/files/10702194/crash.log) file, let me know if you need any more info :)

**Comment by NiLuJe** [comment]
That's... interesting. I'm seeing a series of taps from 22:36:57 to 22:37:08 at differing x coordinates, but a low y coordinates that should more or less match the top status bar.

What's interesting is that the y coordinates is... ruler straight, the very exact same y coordinate (at 62, to be precise ;p). That's... highly unlikely for a human-made tap ;).

Do you have nerves of steel, or were the tap actually more erratic? Can you try again and vary the y coordinates, starting at the very edge of the bezel?

I wouldn't mind a screenshot to confirm where that exactly falls on your device, because I don't have a 758x1024 one on hand (I... think? :D). (That might be tricky to get, but a two-finger tap on opposite corners *should* work).

**Comment by IvoFelix** [comment]
That's curious! Maybe I was too fast clicking on the exact same spot but still seems unlikely, maybe the touch screen is not that precise at recognizing taps? I'm not familiar with the Kobo Aura's quirks.

Here a screenshot on the file browser:
![FileManager_2023-02-10_102930](https://user-images.githubusercontent.com/93539834/218070243-f39dde72-c620-4718-963f-907cb6361d29.png)

And here is the [crash.log](https://github.com/koreader/koreader/files/10706460/crash.log) after opening what is in the screen shot and trying to open the third tab from the left, I clicked progressively lower until the first item on the menu was activated, hopefully there's no superhuman accuracy this time :P

**Comment by NiLuJe** [comment]
Thanks for the details, that's always helpful ;).

And... yeah, that looks like a very weird and specific touchscreen breakage: it seems unwilling to report an y coordinate below 62 ^^. And that's possibly riiiiiight outside the tab's tapzone.

You can try to drop this patch in `.adds/koreader/patches/1-adjust_touch_deadzone.lua`
```lua
local Kobo = require("device/kobo/device")
local ffi = require("ffi")
local C = ffi.C
require("ffi/posix_h")
require("ffi/linux_input_h")

local kobo_input_hooks = Kobo.initEventAdjustHooks
function Kobo:initEventAdjustHooks()
	kobo_input_hooks(self)
	
	local adjust_deadzone = function(this, ev)
		-- We come *after* the stock Kobo hooks (i.e., SwitchXY), so we need to operate on ABS_MT_POSITION_Y
		if ev.type == C.EV_ABS and ev.code == C.ABS_MT_POSITION_Y and ev.value <= 62 then
			ev.value = 31
		end
	end
	self.input:registerEventAdjustHook(adjust_deadzone)
end
```

It should effectively move the taps inside that deadzone ever-so-slightly higher, so that hopefully they fall inside the icon's tapzone, which should make this weird defect mostly unnoticeable (until the day you need to higlight stuff higher than (x, 62) ;p).

**Comment by IvoFelix** [comment]
I'm sorry for taking so long to reply! I took a week vacation and totally forgot about this when I came back.

> Thanks for the details, that's always helpful ;).

No problem! :) I try my best to help, other than actually contributing code as right now my time is a bit limited.

I tried your patch and it seems to be working pretty well! I can change menu tabs now. This being a screen breakage is a bit disappointing as I just bought it but that's always a risk with used devices, and if other Kobo Auras are working fine then there does not seem to be anything else that can explain this behavior.

Should I close this issue?

**Comment by NiLuJe** [comment]
You could double-check if highlighting something in those top few pixels in Nickel behaves to confirm my theory, but, yeah, I figure we can close this one, thanks for getting back to us ;).

(FWIW, the Aura's screen *is* at a slight offset... but the other way around ;). (e.g., the screen's bottom 10 rows or so are hidden behind the bezel)).
