### ISSUE TITLE
Feature Request: gesture manager in which users can customize gestures for other functions

### ISSUE THREAD

**Issue by slobma** [koreader/koreader#1008]
Hi there,

Big thanks and congrats for your hard work, this app is getting better and better. In my humble opinion is lacking two very important features that still make me use CoolReader. We really need a quick one touch way to open history or "recent opened books" 90% of the times I open a previously opened book and is really too many touches away to do it, just a reminder to please add this option onto the Gesture Manager. Another feature that I really miss big time is the text search, you guys just add the dictionary look-up but still are not considering the text search please give some priority.

Thanks and keep up the good work!

**Comment by AlanSP1** [comment]
At least tap zone for toggling light and controlling light level is done here: https://github.com/koreader/koreader/issues/2270
