### ISSUE TITLE
Koreader profile function

### ISSUE THREAD

**Issue by saisot2006** [koreader/koreader#10090]
Hi, I'd like a profile for my all pdf settings in koreader. For example, I often use page in view mode instead of default continuous, fit width.

Regards,

**Comment by hius07** [comment]
So, make a profile with your preferred settings. What's the problem?

**Comment by mergen3107** [comment]
Did you update to the latest nightly version?
That is in Top menu - last icon - Update - settings - channel - development. Then check for updates. 

After that, go to document, top menu - second tab - document settings - save to a profile. 

Then go to top menu - tools - profiles to apply. 
or make it “Show in action list” and add to a gesture

**Comment by ryanwwest** [comment]
> That is in Top menu - last icon - Update

For some reason, I'm not seeing this 'Update' button after following these steps on version 2023.3. I'm resorting to downloading the latest version and installing from github for now, but is there a certain place you need to be in the app or setting you must enable to see this? It doesn't come up when using the settings menu search feature, either.

**Comment by NiLuJe** [comment]
@ryanwwest: You were probably running an fdroid build. Those have a few features disabled (mostly those related to being able to inject custom code or modify the app) as opposed to a standard build.

**Comment by ryanwwest** [comment]
Ah yes, that was my suspicion. Is there a place other disabled features are missing (like e.g. plugins)? In either case I'll just download direct from now on. This is why I don't use iOS (freedom for features like this) - thanks for confirming!
