### ISSUE TITLE
When I select a sentence in a Chinese book to highlight, I cannot select the Chinese period at the end of the sentence normally.

### ISSUE THREAD

**Issue by kamelija** [koreader/koreader#10099]
* KOReader version: both 2022.11 and 2023.01
* Device: Android 11

#### Issue

When I select a sentence in a Chinese book to highlight, I cannot select the Chinese period at the end of the sentence normally. Because when I select the Chinese period, the first character of the next sentence is automatically selected.
But I do not want to highlight any part of the next sentence.

Thank you very much in advance for the improvement.
KOReader is my favourite reading app.

**Comment by poire-z** [comment]
KOReader selects words. When you cross a punctuation, it skips to selecting the next word (with "word" in Chinese text being a glyph).
But, even if you don't select it yourself (as you can't, as you've seen), if what you selecter is from a start of a "sentence" to a end of a "sentence" (that is, you selected up to before the punctuation), KOReader will extend the highlight to include the punctuation.
If you're not happy with any of that, you can always do the highglight as you can, tap on the highlight made, and adjust it with the arrows.
More info, screenshots,... among https://github.com/koreader/koreader/issues?q=sort%3Aupdated-desc+punctuation+chinese.
And in the User guide page 15: https://koreader.rocks/koreader-user-guide.pdf

**Comment by kamelija** [comment]
Thanks for your reply.
Even if i use the highlight editing toolbar (as described in the user guide) and expand my selected text, the issue still exists.

**Comment by poire-z** [comment]
You need to long-press on the arrow (tap skips by word, long-press skips by character).
![image](https://user-images.githubusercontent.com/24273478/217751274-1f08dffc-177b-415a-944a-a6537ed669b0.png)

**Comment by kamelija** [comment]
Clicking this button still does not work on my mobile phone (Android 11). I downloaded the APK file (arm64) from f-droid.org. Is it different from the one released on GitHub?
