### ISSUE TITLE
Hard crash when selecting text KOReader 2023.01

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#10108]
* KOReader version:  KOReader 2023.01
 
* Device: Pocketbook Era PB700

#### Issue: 

Selecting text causes "bomb" graphic to appear  time stamp 2/11/2023 10:39

#### Steps to reproduce

Attempted to highlight a chapter title.

##### `crash.log` (if applicable) See attached Crash Log
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to
[crash.log](https://github.com/koreader/koreader/files/10713997/crash.log)
 us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hius07** [comment]
Thank you. Have you noticed the difference in selecting actions of these two fragments?
```Lua
pos0 = "/body/DocFragment[13]/body/div/p[120]/b/i/text().0",
pos1 = "/body/DocFragment[13]/body/div/p[120]/b/i/text().12",
text = "Fleur-de-Lis"
```
```Lua
pos0 = "/body/DocFragment[13]/body/div/p[120]/b/i/text().0",
pos1 = "/body/DocFragment[13]/body/div/p[120]/br[2].1",
text = "Fleur-de-Lis"
```
The text selected is the same.

**Comment by zmixnyc** [comment]
I may have tried selecting right to left in one selection when left to right didn't work?

Please let me know if I can perform any tests or provide any other examples.

**Comment by NiLuJe** [comment]
Relevant stacktrace for bystanders:

```
./luajit: frontend/apps/reader/modules/readerbookmark.lua:248: attempt to compare nil with number
stack traceback:
	frontend/apps/reader/modules/readerbookmark.lua:248: in function 'isBookmarkInPositionOrder'
	frontend/apps/reader/modules/readerbookmark.lua:901: in function 'getBookmarkInsertionIndexBinary'
	frontend/apps/reader/modules/readerbookmark.lua:911: in function 'addBookmark'
	frontend/apps/reader/modules/readerhighlight.lua:1760: in function 'saveHighlight'
	frontend/apps/reader/modules/readerhighlight.lua:1548: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:253: in function 'handleEvent'
	frontend/ui/uimanager.lua:882: in function 'sendEvent'
	frontend/ui/uimanager.lua:51: in function '__default__'
	frontend/ui/uimanager.lua:1406: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1504: in function 'handleInput'
	frontend/ui/uimanager.lua:1551: in function 'run'
	./reader.lua:315: in main chunk
	[C]: at 0x00013f5d
```

**Comment by hius07** [comment]
> Relevant stacktrace for bystanders:

Yes, we must have a check for invalid xpointers prior to comparing them, I am just wondering how they appear.
