### ISSUE TITLE
Build issue on Alpine with tesseract

### ISSUE THREAD

**Issue by mio-19** [koreader/koreader#10116]
* KOReader version: 91ff6ce2d81c299153d99fe0eba7f4bfa9d742b7

#### Log

```
/base/thirdparty/leptonica/build/aarch64-alpine-linux-musl-debug/leptonica-prefix/src/leptonica/src/. -Og -g -pipe -fno-omit-frame-pointer -march=native -fPIC -O3 -MT boxread.lo -MD -MP -MF .deps/boxread.Tpo -c boxread.cpp  -fPIC -DPIC -o .libs/boxread.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I../cutil -I../viewer -I../opencl -I/root/Apps/koreader/base/thirdparty/leptonica/build/aarch64-alpine-linux-musl-debug/leptonica-prefix/src/leptonica/src/. -Og -g -pipe -fno-omit-frame-pointer -march=native -fPIC -O3 -MT coutln.lo -MD -MP -MF .deps/coutln.Tpo -c coutln.cpp  -fPIC -DPIC -o .libs/coutln.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I../cutil -I../viewer -I../opencl -I/root/Apps/koreader/base/thirdparty/leptonica/build/aarch64-alpine-linux-musl-debug/leptonica-prefix/src/leptonica/src/. -Og -g -pipe -fno-omit-frame-pointer -march=native -fPIC -O3 -MT detlinefit.lo -MD -MP -MF .deps/detlinefit.Tpo -c detlinefit.cpp  -fPIC -DPIC -o .libs/detlinefit.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I../cutil -I../viewer -I../opencl -I/root/Apps/koreader/base/thirdparty/leptonica/build/aarch64-alpine-linux-musl-debug/leptonica-prefix/src/leptonica/src/. -Og -g -pipe -fno-omit-frame-pointer -march=native -fPIC -O3 -MT ccstruct.lo -MD -MP -MF .deps/ccstruct.Tpo -c ccstruct.cpp  -fPIC -DPIC -o .libs/ccstruct.o
In file included from blamer.h:27,
                 from blamer.cpp:21:
matrix.h: In constructor 'MATRIX::MATRIX(int, int)':
matrix.h:33:24: error: invalid cast from type 'std::nullptr_t' to type 'BLOB_CHOICE_LIST*'
   33 | #define NOT_CLASSIFIED reinterpret_cast<BLOB_CHOICE_LIST*>(NULL)
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
matrix.h:292:63: note: in expansion of macro 'NOT_CLASSIFIED'
  292 |     : BandTriMatrix<BLOB_CHOICE_LIST *>(dimension, bandwidth, NOT_CLASSIFIED) {}
      |                                                               ^~~~~~~~~~~~~~
In file included from blamer.h:27,
                 from pageres.h:22,
                 from boxword.cpp:24:
matrix.h: In constructor 'MATRIX::MATRIX(int, int)':
matrix.h:33:24: error: invalid cast from type 'std::nullptr_t' to type 'BLOB_CHOICE_LIST*'
   33 | #define NOT_CLASSIFIED reinterpret_cast<BLOB_CHOICE_LIST*>(NULL)
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
matrix.h:292:63: note: in expansion of macro 'NOT_CLASSIFIED'
  292 |     : BandTriMatrix<BLOB_CHOICE_LIST *>(dimension, bandwidth, NOT_CLASSIFIED) {}
      |                                                               ^~~~~~~~~~~~~~
make[8]: *** [Makefile:569: blamer.lo] Error 1
make[8]: *** Waiting for unfinished jobs....
make[8]: *** [Makefile:569: boxword.lo] Error 1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccutil -I../cutil -I../viewer -I../opencl -I/root/Apps/koreader/base/thirdparty/leptonica/build/aarch64-alpine-linux-musl-debug/leptonica-prefix/src/leptonica/src/. -Og -g -pipe -fno-omit-frame-pointer -march=native -fPIC -O3 -MT dppoint.lo -MD -MP -MF .deps/dppoint.Tpo -c dppoint.cpp  -fPIC -DPIC -o .libs/dppoint.o
make[7]: *** [Makefile:482: all-recursive] Error 1
make[6]: *** [Makefile:391: all] Error 2
make[5]: *** [Makefile:108: libtesseract.so] Error 2
make[4]: *** [CMakeFiles/libk2pdfopt.dir/build.make:86: libk2pdfopt-prefix/src/libk2pdfopt-stamp/libk2pdfopt-build] Error 2
make[3]: *** [CMakeFiles/Makefile2:83: CMakeFiles/libk2pdfopt.dir/all] Error 2
make[2]: *** [Makefile:91: all] Error 2
make[2]: Leaving directory '/root/Apps/koreader/base/thirdparty/libk2pdfopt/build/aarch64-alpine-linux-musl-debug'
make[1]: *** [Makefile.third:327: build/aarch64-alpine-linux-musl-debug/libs/libk2pdfopt.so.2] Error 2
make[1]: Leaving directory '/root/Apps/koreader/base'
make: *** [Makefile:86: all] Error 2
Failed to build emulator! Try run with -v for more information.
```

**Comment by NiLuJe** [comment]
Which compiler is that?

**Comment by NiLuJe** [comment]
In any case, this should be a `static_cast` (and a real `nullptr`), which it is in current leptonica versions; so this'll just resolve it self whenever the PDF backend migration is over.

**Comment by mio-19** [comment]
> Which compiler is that?

Latest gcc of alpine edge

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/12.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-12-20220924/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-languages=c,c++,d,objc,go,fortran,ada --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libsanitizer --enable-shared --enable-threads --enable-tls --with-bugurl=https://gitlab.alpinelinux.org/alpine/aports/-/issues --with-system-zlib --with-linker-hash-style=gnu --with-pkgversion='Alpine 12.2.1_git20220924-r9'
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 12.2.1 20220924 (Alpine 12.2.1_git20220924-r9)
```

**Comment by mio-19** [comment]
The definition is `static_cast<BLOB_CHOICE_LIST *>(nullptr)` in the latest tesseract

**Comment by mio-19** [comment]
After patched matrix.h:
```
make[2]: Entering directory '/root/koreader/base/thirdparty/sdcv/build/aarch64-alpine-linux-musl-debug'
[ 12%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/sdcv.cpp.o
[ 25%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/readline.cpp.o
[ 37%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/libwrapper.cpp.o
[ 50%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/utils.cpp.o
[ 62%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/stardict_lib.cpp.o
[ 75%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/dictziplib.cpp.o
[ 87%] Building CXX object sdcv-build/CMakeFiles/sdcv.dir/src/distance.cpp.o
[100%] Linking CXX executable sdcv
/usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: CMakeFiles/sdcv.dir/src/sdcv.cpp.o: undefined reference to symbol 'libintl_gettext'
/usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: /usr/lib/libintl.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[4]: *** [sdcv-build/CMakeFiles/sdcv.dir/build.make:195: sdcv-build/sdcv] Error 1
make[3]: *** [CMakeFiles/Makefile2:98: sdcv-build/CMakeFiles/sdcv.dir/all] Error 2
make[2]: *** [Makefile:156: all] Error 2
make[2]: Leaving directory '/root/koreader/base/thirdparty/sdcv/build/aarch64-alpine-linux-musl-debug'
make[1]: *** [Makefile.third:457: build/aarch64-alpine-linux-musl-debug/sdcv] Error 2
make[1]: Leaving directory '/root/koreader/base'
make: *** [Makefile:86: all] Error 2
Failed to build emulator! Try run with -v for more information.
```

`gettext-dev` is installed on the system

**Comment by NiLuJe** [comment]
That's probably a musl special; you probably need to link against `-lintl` specifically. CMake is pain, though, so no idea how this is supposed to be handled.

**Comment by NiLuJe** [comment]
FWIW, we already have a dirty hack in place for this very issue on Android & macOS, where we just link to a static glib + gettext.

c.f., https://github.com/koreader/koreader-base/blob/96b2a16e685a75de1b7fcfe30b9dd19d54f5f306/thirdparty/sdcv/CMakeLists.txt#L50-L58

(You'll have to dig around some more, because there are other branches earlier to make sure those components are built, either at all, or properly to be used like that).

**Comment by bjesus** [comment]
@mio-19 did you manage to get it running on Alpine? if so, can you please show how or create a package for it? I'm trying to get KOReader working on PostmarketOS so I can use it on my Kobo Clara HD, but so far without luck. PostmarketOS is built on top of Alpine so if it works for you it should also work here...

**Comment by mio-19** [comment]
> @mio-19 did you manage to get it running on Alpine? if so, can you please show how or create a package for it? I'm trying to get KOReader working on PostmarketOS so I can use it on my Kobo Clara HD, but so far without luck. PostmarketOS is built on top of Alpine so if it works for you it should also work here...


The easiest way would be chroot

**Comment by NiLuJe** [comment]
A glibc chroot? Definitely.

While I tend to be marginally careful about this, it is entirely possible we rely on more or less severe GNUisms that would break on musl.

(e.g., I caught [a pretty simple but common one](https://github.com/koreader/koreader-base/blob/4d39446285161ab3b3041264049f763f74b28711/ffi/util.lua#L178-L182) a few days ago).

**Comment by Frenzie** [comment]
> we do run mostly unscathed on bionic (and it's the worst)

Because it's the exact opposite of a POSIX libc. :-P

**Comment by comcloudway** [comment]
> @mio-19  After patched matrix.h:

Do you mind sharing the patch?

**Comment by Oppen** [comment]
> While I tend to be marginally careful about this, it is entirely possible we rely on more or less severe GNUisms across the codebase that would break in fun and interesting ways on musl (or other strictly POSIX libcs).

Maybe there's a way to lint against those? Kinda like one does with bashisms when writing shel

**Comment by Frenzie** [comment]
In C maybe, in LuaJIT FFI doubtful.

**Comment by skyleecm** [comment]
> @mio-19 did you manage to get it running on Alpine? if so, can you please show how or create a package for it? I'm trying to get KOReader working on PostmarketOS so I can use it on my Kobo Clara HD, but so far without luck. PostmarketOS is built on top of Alpine so if it works for you it should also work here...

I manage to get koreader running in pinephone PostmarketOS.
Extract files in koreader-2024.03.1-arm64.deb and copy them to the target device.

Install gcompat for GNU C Library compatibility layer.
Install the other external dependencies: sdl2, font-noto, font-droid-nonlatin

The fonts path are different in Debian and Alpine, so can either copy those fonts files into koreader fonts subfolder or fix the symlinks.

I fix the symlinks with:

cd /usr/share/fonts
sudo ln -s . truetype

cd /usr/lib/koreader/fonts/droid/
sudo ln -s /usr/share/fonts/droid-nonlatin/DroidSansFallback.ttf DroidSansMono.ttf

Lastly, replace koreader libsqlite3.so by Alpine one; because there is a symbol not found: posix_fallocate64

cd /usr/lib/koreader/libs/
sudo rm libsqlite3.so
sudo ln -s /usr/lib/libsqlite3.so.0 libsqlite3.so

Generally, I do not use most of the koreader menu functions, so I am unsure whether there are any other such errors.

**Comment by benoit-pierre** [comment]
With #11930, tesseract builds fine in docker. I can build everything except for sdcv (another gettext related issue). Installed packages: `apk add autoconf automake bash ccache cmake coreutils curl diffutils g++ gcc gettext-dev git grep gzip libtool linux-headers make ninja-build ninja-is-really-ninja patch pkgconf tar unzip wget`.

**Comment by benoit-pierre** [comment]
There's an issue with the background runner tests, however: `spec/front/unit/background_runner_spec.lua @ 236: BackgroundRunner widget tests should block long binary job` hangs.

To run the testsuite:
- `apk add add sdl2 lua5.1-busted luarocks5.1`
- `make LUAROCKS_BINARY=luarocks-5.1 test`
