### ISSUE TITLE
(Hard to catch) Swipe Gesture gets Pass through instead of profiles quick menu

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10112]
* KOReader version: 2023.01-14
* Device: Onyx Boox Kon-Tiki 2

#### Issue
Upon some KOReader restarts, gesture (left edge down) loses all profiles assigned and sorted as quick menu and defaults to “Pass through”. 

This happened to me twice, but I cannot reproduce it forcibly. 
1) Today, when KOReader crashed.
- I had a user patch to replace Noto Sans by a new font. 
- I temporarily disabled the patches by renaming the patches dir to patches_ . 
- I then removed and forgot about the new font. 
- Reverted the patched dir, restarted KOReader and it crashed (no surprise, but I then restored the font, it is OK now). 
2) About a week ago when I edited the profiles.lua file manually to add the font kerning option to all font-profiles. I found it easier than doing it in menu. (Also, I found that only some profiles ahd their options sorted in the file, but I probably did to some of then and then duplicated). 

So after I edited and saved the file with KOReader closed, upon the start the issue happened too.

#### Steps to reproduce
(Figuring out how to reproduce this with verbose logs, no success yet). 

Any ideas?

**Comment by NiLuJe** [comment]
2. feels like a step ripe for introducing weird and funky PEBCAK errors, FWIW ;).

**Comment by mergen3107** [comment]
Well, the same profiles.lua file works well after that :D so I hope I’m following the syntax correctly

**Comment by jospalau** [comment]
This happened to me a couple of times while setting up my profiles but it hasn't happened anymore. I am using the same profiles.lua file for my 6 devices.

**Comment by NiLuJe** [comment]
> I am using the same profiles.lua file for my 6 devices.

Keep in mind there's no guarantee of portability, this may be a very fine way of triggering weird and interesting issues ;).

**Comment by jospalau** [comment]
> > I am using the same profiles.lua file for my 6 devices.
> 
> Keep in mind there's no guarantee of portability, this may be a very fine way of triggering weird and interesting issues ;). 
> 

So far it is working amazingly. I try to keep up to date the versions in all my devices. It is a great improvement this one.

**Comment by mergen3107** [comment]
Haven't encountered this for quite a while!

**Comment by mergen3107** [comment]
FWIW, I switched from Onyx Boox to Kindle Scribe: still haven't seen this issue.
