### ISSUE TITLE
Timestamps seem to be touched after shutdown

### ISSUE THREAD

**Issue by Iey4iej3** [koreader/koreader#10121]
* KOReader version: 2023.01
* Device: Kobo Elipsa

#### Issue

Timestamps seem to be touched after shutdown of device from KOReader (at least reproducible after auto-shutdown or long-pressing the power button).

#### Steps to reproduce

1. Install Syncthing (under KOReader);
2. Set up a "Receive only" folder in Syncthing;
3. Synchronize with another device;
4. Set a timeout in the auto-shutdown and wait until the device shutdown, or shutdown the device by long-pressing the power button.
5. Power on and start KOReader and Syncthing. Then there are a lot of files with "local change".

cf. https://forum.syncthing.net/t/a-lot-of-revert-local-changes-after-a-shutdown-of-kobo/19709

**Comment by NiLuJe** [comment]
You cannot rely on timestamps in a FAT32 filesystem, their granularity is too coarse for that.

Sane two-way sync framework *should* have settings/heuristics in place to deal with it.

**Comment by Iey4iej3** [comment]
I have already set the difference to be 2 seconds, and it works on Android without such issues. It is also unclear whether it is an issue of KOReader or Syncthing or both. I put the debug log of Syncthing at that forum post.

**Comment by Iey4iej3** [comment]
Also, it seems that I cannot reproduce this issue if the shutdown is performed in Nickel (although I do not do that frequently).

**Comment by NiLuJe** [comment]
We shutdown the exact same way as Nickel, and a KOReader exit behaves the exact same way as a KOReader reboot, so nothing really weird is happening here.

I can't really tell you much without an exact list of the files involved and how much syncthing thinks the timestamps deviate (and from what?).

**Comment by Iey4iej3** [comment]
The list is long, but I posted an output of `syncthing cli debug file` of a file claimed to be changed in that forum.

**Comment by NiLuJe** [comment]
I'm going to need an actual `stat` output on the same file, because that mess is unreadable ;o).

**Comment by NiLuJe** [comment]
> We shutdown the exact same way as Nickel

Turns out we didn't, not on sunxi ;o).

**Comment by Iey4iej3** [comment]
This issue does not seem to be as producible as I thought. I did reproduce it every shutdown, but really after a heavy usage. I just tried to shutdown a bit but it did not reproduce the issue. It seems plausible that this would be related to unmount behaviors.

**Comment by Iey4iej3** [comment]
They say that the debug log shows that the timestamps are of an hour difference. Maybe this is about timezone.

**Comment by Iey4iej3** [comment]
It now seems possible that it is a bug of Linux kernel on vfat: https://unix.stackexchange.com/questions/640555/

**Comment by NiLuJe** [comment]
> and that's without taking into account the local vs. UTC hilarity.

;o).

**Comment by Iey4iej3** [comment]
This seems unfixable.
