### ISSUE TITLE
FR: Maximal retries for WiFi connection

### ISSUE THREAD

**Issue by Iey4iej3** [koreader/koreader#10120]
**Does your feature request involve difficulty completing a task? Please describe.**
It happened that, when I enable the WiFi connection, it got stuck there, retrying to connect (more precisely, after `Authenticated...`, seemingly the connection was failed and then a new attempt followed), for unknown reasons, which was solved by rebooting.

**Describe the solution you'd like**
Set up a maximal retries to avoid this infinite loop.

**Comment by NiLuJe** [comment]
On which device was that?

**Comment by Iey4iej3** [comment]
Kobo Elipsa (I cannot reproduce the issue after reboot and until now, thus not really debugable), but that maximum of retries would suppress such issues.

**Comment by NiLuJe** [comment]
Is the SSID in question known (and saved) in Nickel, or just in KOReader?

**Comment by Iey4iej3** [comment]
> a retry/failure counter (with a cap at 30)

Sorry, the upper limit is 30 times? I did not wait so long (every retry needs about half a minute, and I was in a hurry). I would like that there is an easy way to stop retries.

**Comment by NiLuJe** [comment]
No, 30s, but it's not necessarily as straightforward (i.e., it's 30 steps of 1s if and only if wpa_supplicant is not busy). Can't tell much about what happened without logs ;).

**Comment by Iey4iej3** [comment]
I would still propose to have ways to minimize this dialog or whatever so that one can do something else simultaneously, or click "Disconnect" to stop it.

**Comment by NiLuJe** [comment]
We're not multi-threaded, so that would be a somewhat complex overhaul.

#patcheswelcome

**Comment by NiLuJe** [comment]
(Left the info label on, as you'd need to track system logs to check what wpa_supplicant is doing).
