### ISSUE TITLE
KOReader on Pocketbook Era inconsistent when orientation is inverted (180 degrees)

### ISSUE THREAD

**Issue by fcr** [koreader/koreader#10123]
* KOReader version: 2023.01
* Device: Pocketbook Era PB700

#### Issue: 
180 degree rotation of the Pocketbook Era from different starting states produces inconsistent behaviors where sometimes buttons are not reversed or sometimes the display is upside down but the buttons are correct. 

#### Steps to reproduce
This was checked using portrait mode.
##### Case 1:
Open the KOReader while the buttons are on the right.  
Quickly rotate the device 180 degrees so that the buttons are now on the left. (It is easier if the `Lock auto rotation to current orientation` is checked but this is not a necessary condition)  
The display is rotated correctly, and the tap and slide functions are correctly reversed.  
However, pressing the upper page button pages backwards while pressing the lower page button pages forwards.  
##### Case 2.
Repeat case 1. 
Now while the buttons are still on the left, press the home button, (which is now the top button).
The Pocketbook's Home screen now is displayed and is correctly orientated.
While leaving the buttons on the left, reopen the KOReader.
The page is now upside down. The tap and slide functions are also reversed such that they are consistent with the page. However the page buttons have been reversed so the the upper one pages forwards and the bottom one backwards which would be good except that the page is upside down. :-(
Now rotate the device once again so that the buttons are on the right. The page inverts so it is still upside down and the page buttons reverse so that the top button pages backwards and the bottom button pages forwards.
##### Case 3.
Repeat case 1.
Now while the the buttons are still on the left, put the device into sleep mode.
Wake the device up. The behavior is the same as case 2.
##### Case 4.
This case is good news. :-)
Open the KOReader while the buttons are on the right. 
BEFORE rotating, put the device to sleep.
Rotate the device 180 degrees so that the buttons are on the left.
Wake the device up.
Everything is working correctly!
##### Case 5.
This case is almost good news. :-)
Open the KOReader while the buttons are on the right. 
BEFORE rotating, press the home button to display the Pocketbook's Home screen.
Rotate the device 180 degrees so that the buttons are on the left. The home display rotates correctly.
Reopen the KOReader.
Most times it is correct, but sometimes, the page is again upside down. 
However, if it is upside down, a slight rotation of the device will correct things. 

It seems that as long as the KOReader is not active when the device is rotated 180 degrees, the KOReader handles the rotation correctly when activated.

**Comment by NiLuJe** [comment]
Possibly related to #9556

**Comment by NiLuJe** [comment]
IIRC, this behavior was FW-specific, so it's entirely plausible the behavior actually changed *again*...

**Comment by philipvanlaar** [comment]
Solution: in device/associate file extensions select enable all and open file from pb700's own file browser. Era very well integrates with koreader and needs koreader to give up it's own file browser.

**Comment by peterrus** [comment]
@philipvanlaar is that a workaround for the inverted rotation bug? I am asking because I don't see how it is related to this issue.

@gjabell Are you still using this patch with success? And if so does this consistently work? If that is the case we can maybe find a way to get this into the codebase.

**Comment by philipvanlaar** [comment]
I am afraid there is no solution for the issue. Rotating still always
activate both host and client is. It is not difficult to rotate koreader by
rotating its host, as others already stated.

**Comment by breiti-oi** [comment]
> @gjabell Are you still using this patch with success? And if so does this consistently work? If that is the case we can maybe find a way to get this into the codebase.

I use the patch with latest stable koreader 2024.01, and I can confirm it still works.

**Comment by marcelmu** [comment]
Oh god.

Of course it's consistently flipped, because I had the "Invert Buttons" setting enabled when trying to figure out the issue originally.

So with the patch it all still works fine.

**Comment by heksesang** [comment]
For my Era Color I had to set `inkview_translates_buttons` to `false` here:
https://github.com/koreader/koreader/blob/15f5dbef83b84beb5ef3ddd8c21fc6b7f7c615fc/frontend/device/pocketbook/device.lua#L700

After that the buttons act as expected.

Maybe `inkview_translates_buttons` should be a toggle in the KOReader settings UI when running on Pocketbook devices?

**Comment by cel-n** [comment]
> I tried using a user patch to re-enable the keys back to the defaults but that still didn't give me the expected behavior. This combination works for me as I would expect the keys to function based on rotation:
> 2-set-hw-button-rotation.lua

Thanks for sharing the patch, @gjabell. I can confirm it still works on 2025.10. 

I adapted it slightly to fit my preferences. This variation uses inverted page-turn buttons in upright and upside-down orientation, but keeps the buttons behaving intuitively in the horizontal/landscape rotations. Make sure to disable “invert page-turn buttons” in KOReader, as this patch already handles the inversion.

```
local logger = require("logger")
local Device = require("device")

Device.input.rotation_map = {
    -- DEVICE_ROTATED_UPRIGHT (0°)
    [0] = {
        LPgFwd = "LPgBack",
        LPgBack = "LPgFwd",
        RPgFwd = "RPgBack",
        RPgBack = "RPgFwd",
    },

    -- DEVICE_ROTATED_CLOCKWISE (90°)
    [1] = {
    },

    -- DEVICE_ROTATED_UPSIDE_DOWN (180°)
    [2] = {
    },

    -- DEVICE_ROTATED_COUNTER_CLOCKWISE (-90°)
    [3] = {
        LPgFwd = "LPgBack",
        LPgBack = "LPgFwd",
        RPgFwd = "RPgBack",
        RPgBack = "RPgFwd",

    },
}

logger.info("Hardware button rotation updated by user patch (Page-Buttons inverted for upside-down and counter-clockwise)")
```

**Comment by nhannam** [comment]
I bought a Pocketbook Era recently and encountered the same button issues in [2026.03].

As a left-handed person, I primarily hold the device in portait but "upside down".

With koreader defaults, the page turn buttons are in fixed positions.  When holding "upside down" the bottom button turns forward a page, whereas holding the "right way up" it is the top button that pages forward.
Using the UI option to invert the buttons is not really helpful as they are still in fixed posiitons so swapping orientation still requires you to change whether you press the top or bottom button to page forwards.

Switching "inkview_translates_buttons" to false improves behaviour a bit - in portrait, regardless of the orientation the top button always pages forwards and the bottom button always pages backwards.  In landscape however, the buttons are the wrong way round - right hand button pages backwards.

The patch posted [here](https://github.com/koreader/koreader/issues/10123#issuecomment-1597474715) gives correct intuitive button button behaviour in all orientations - in portrait top button pages forwards, in landscape right hand button pages forwards.   Is there any reason this has not been adopted as default behaviour?
