### ISSUE TITLE
Two-way Dropbox Sync on Kobo Elipsa

### ISSUE THREAD

**Issue by paulusm** [koreader/koreader#10126]
This is a little niche, but I wondered if anyone had some insights. I use my Elipsa to read PDFs, together with Zotero / Zotfile to send them to the reader via Dropbox. Highlighting in the default Kobo app is not recognised by Zotero (ie not split out into notes automatically), so I was delighted to see that KOReader did do the right kind of highlighting. Odd thing is that Kobo app  Dropbox feature doesn't then think the file has changed and needs syncing. 

Steps to reproduce

1. Sync a PDF over via Dropbox
2. Go to .kobo/Dropbox in KOReader and make some highlights, saving changes
3. Exit KOReader and go to Dropbox folder. PDFs not flagged as needing sync (appear unchanged). 
4. Open the file in Kobo app and make a pen squiggle to force change
5. Dropbox then flags change, and you can upload.
6. Open file on Mac, then it shows **BOTH  the Kobo squiggle AND the KOReader Highlights**

Ideally, the KOReader highlights would flag the file as dirty when you return to the Kobo app side. Even better would be two way sync from within KOReader, which I see someone has already requested before. Does the Kobo app not use file modified metadata to determine what needs syncing (I can see that the modified date changes when you add the KO Reader highlights)?

**Comment by NiLuJe** [comment]
Someone would have to do some SQL forensics to check how Nickel flags file for sync.

**Comment by NiLuJe** [comment]
I'm flagging this as out of scope, as nothing in KOReader currently interacts with the Nickel database (for very good reason).

(c.f., [my dumb reading stats script](https://svn.ak-team.com/svn/Configs/trunk/Kindle/Kobo_Hacks/Scripts/sync_koreader_progress_to_nickel.py) for a simple example of Nickel database fudging based on KOReader's state).
