### ISSUE TITLE
Q: Tapping on the same book from History

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10158]
* KOReader version: 2023.01-82
* Device: Kon-Tiki 2 (Android 10)

1) Open a book
2) Go to History
3) Tap the same book which is the first one. 
4) KOReader starts opening it with the notification. 

Shouldn’t 4) just close History? 
Is there a reason to force reopen the same book?

**Comment by poire-z** [comment]
No specific reason, we just didn't think about it :)
Also no real reason to bother making it behave differently than when opening another book.
Somehow, I had found it useful in the past to reload the same book when I wanted too (for dev reasons, I don't really remember when/why).
Could also be a way to reset the start of the current session (for those who care, ie. with the recent arrows over the footer progress bar.

**Comment by Frenzie** [comment]
It's come up before; I don't recall if we purposefully decided anything in particular other than not finding it particularly bothersome.
