### ISSUE TITLE
Q: What does reading statistics treat as unique identifier

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10157]
(Hi all, this ticket is a Q&A alternative. I remember you guys complaining that Q&A section is not really searchable, there are some questionable moderation limitations, and so on. So I decided to create this issue ticket to ask probably a common question)
 
What does reading statistics use to “identify” a book? MD5? Then if so what makes it different?

Reason I am asking is that I found myself, like, a fourth time in a about a year now when I can see duplicate statistics of a book I opened and didn’t finish a long time ago. 

So, for example, I have a book that has hh:mm:ss of read time, and then another entry with the same book title but with fresh new 00:mm:ss time. 

weird part is that I didn’t do anything to this book. I understood it back then when I played around with compression and dithering in CBZ files, but this book is fb2, like many others I also didn’t touch. And it shows up as a duplicate. 

My resort was to take the sqlite file of the statistics, open it with Sqlite DB Browser, assign the “new” hash to the old statistics. Then go to KOReader and delete the “new entry”, because I don’t want to delete it by hand in DB Browser (I don’t know what KOReader also does when doing it properly). 

The result is that the old statistics now picks it up and keeps growing instead of creating duplicates. 

Thanks!

**Comment by poire-z** [comment]
Should be (title, author, partial_md5):
https://github.com/koreader/koreader/blob/81c0bc396ab65e4f18f6912c13f3dc727b316f39/plugins/statistics.koplugin/main.lua#L773-L812
https://github.com/koreader/koreader/blob/81c0bc396ab65e4f18f6912c13f3dc727b316f39/plugins/statistics.koplugin/main.lua#L433-L454

There was also this migration/fix that should fix possible past duplicates:
https://github.com/koreader/koreader/blob/81c0bc396ab65e4f18f6912c13f3dc727b316f39/plugins/statistics.koplugin/main.lua#L592-L596

**Comment by mergen3107** [comment]
Thanks @poire-z !

I’ll try to track down this obscure issue. I don’t modify or overwrite these books, so it’s difficult to say what’s going on with the file :D 

I am closing this until someone else or me again finds that issue. 

P.S. When highlights are written into PDF bu KOReader, the md5 probably changes? I never used that feature yet but I suppose the new md5 is recalculated and passed through to statistics?

**Comment by poire-z** [comment]
> P.S. When highlights are written into PDF bu KOReader, the md5 probably changes? I never used that feature yet but I suppose the new md5 is recalculated and passed through to statistics?

Not using that featue either, but this old code/idea from 2015 is what handles that:
https://github.com/koreader/koreader/blob/5c9ba533532a452240b4e99fcbfb4995f38fa1c0/frontend/document/document.lua#L146-L158
