### ISSUE TITLE
QuickMenu/Gesture Manager has two reading statistics in Chinese translation

### ISSUE THREAD

**Issue by w316525096** [koreader/koreader#10161]
* KOReader version: 2023.01
* Device: KT3

#### Issue
手势快捷有两个“阅读统计”，一个“阅读统计“是当前阅读书籍的统计，另一个“阅读统计”是所有已经阅读书籍的统计。
—————translation————
Gesture shortcut has two reading statistics, One reading statistic is a statistic of books currently read, and the other is a statistic of all books that have been read.

![Reader_2023-02-25_132733](https://user-images.githubusercontent.com/25398881/221340536-6d564174-dd40-4a81-ba6a-bcdee25b1720.png)

**Comment by Frenzie** [comment]
Pinging @weijiuqiao. I suspect `book status` isn't translated quite correctly?

Book status being this widget:
<img src=https://user-images.githubusercontent.com/202757/221347267-a3b21f2d-3d14-4658-811e-161636a45a17.png width=45%>

**Comment by weijiuqiao** [comment]
Somehow those different terms have all been translated to the same phrase "阅读统计" (reading statistics). Let me make some corrections.

**Comment by Frenzie** [comment]
Minor sidenote, in the search Weblate doesn't show if a string is marked as fuzzy ("needs editing"). But also note that fuzzy translations aren't displayed in the UI.

The flow goes like:

1. A new translation is added.
2. It's automatically fuzzy matched to existing translations. If "book statistics" exists and "reading statistics" is new, then it'll be prefilled with the translation for "book statistics" while it's simultaneously marked fuzzy ("needs editing").
3. The translator either replaces it completely, replaces a single word, or in some cases just marks it finished.

Perhaps these were incorrectly or accidentally marked as finished?

**Comment by Frenzie** [comment]
This seems to have been fixed 3 months ago.
