### ISSUE TITLE
FR: Dynamic number of items per page in Bookmarks view

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#10163]
## Mockup:
![bookmarks mockup smaller](https://user-images.githubusercontent.com/10296053/221381538-81ebe591-f474-48ba-8888-2c68bb415334.png)

## Current:
![221381254-5af7f505-2452-4449-a678-2aebfd3a5d47 2](https://user-images.githubusercontent.com/10296053/221381321-377946f2-1727-4eca-b450-1ee2b93bef81.png)

## Deets
I think the Bookmarks view would be improved if all the bookmarks/notes/highlights could be shown with the same font size and same amount of separation from one another. Pretty much how exported notes/highlights look. The current implementation can be a little overwhelming and limited in how it presents highlights for browsing.

I think having each row expand to fit its contents while maintaining the same font size would be a good way to get visual balance and make the list readable. Instead of having a preset number of rows per page, the sizing would adapt to the content instead. Overflowing notes would continue onto the next page

This is probably hard/impossible to do with the current pure Menu widget that's used, but I think it would be cool

**Comment by mergen3107** [comment]
Fixed font size looks really nice! I would add “up to N rows” to show per each bookmark. 

N being discussed: should 5 be enough? 7? 10?

Another suggestion is to show the start, and then `…` + the last M characters of the bookmark. M is like 20, maybe? Idea is to show where the bookmark ends.

**Comment by melyux** [comment]
I was thinking you'd show the entirety of the highlight, since highlights by definition aren't very long. Though not opposed to an option to truncate if the user wants
