### ISSUE TITLE
Book status indicators for file browser

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#10170]
This is an UI improvement that might especially help with academic reading. When reading about a new topic I generally download 10-15 articles and books into a folder. And then go through these documents (which generally have very similar names). 

If I can see at a glance which ones I have opened / finished and which ones have highlights and notes it would be very useful. For example after going through the folder, I can directly delete the ones which are `Finished` but doesn't contain any highlights. Currently I have to open them one by one to check if they contain highlights/notes before deleting.

Yes we currently have an **Opened** indicator and a **Finished** indicator. **Opened** indicator is very tiny and at the opposite corner of the book name. **Finished** indicator get lost between the clutter of book size, type etc. text. Yes they are visible of course but not glanceable. And we don't have a **"contains highlights/notes"** indicator AFAIK.

Here is a mockup of how it might look like. Icons are from Noto Emoji font and their scale is for demonstration. Icons are on the left side so when looking at the file name we can glance the status of the book too. If there are other users that think this might be useful, something like this maybe implemented.

![file browser tags](https://user-images.githubusercontent.com/84420582/222164617-069818c6-d93c-4024-9da8-d4833c1dbe00.png)

**Comment by hius07** [comment]
If somebody is going to implement: I believe that storing the actual number of highlights/bookmarks in doc_settings (new fields) would be cheaper than calculating it every time while showing the list of files (without opening a book).

**Comment by poire-z** [comment]
I get this is just a mockup, but not fond of this idea of having icons on the left:
- the widgets layout is very complicated, so not fond of making it even more complicated (with either icons vertically aligned between the cover and the title/author lines - or as another line below title/author, making these title/author font size even smaller)
- I don't really want this Detailed list mode to look too much like a christmas tree with such striking icons (so if really going with that, it should be an option)
- about the thought of having them on the left near the title, I guess that if you are able to read books and lines of text taking your full screen width, and doing that 99.9% of the time spent on KOReader, your brain should be able to scan file items from left to right and back to gather title/authors and some icons that would be on the right.

So, it's probably easier to prepend or append Unicode symbols to the little bits of text (file size/format or pages) on the right, the same Unicode symbols we already use for notes and highlights (in Bookmarks and in Book map) - and may be a little new unicode symbol alongside "Finished" if you want it more striking (although for the rare books I keeep as Finished, I wouldn't want them to be more striking).

**Comment by offset-torque** [comment]
@poire-z 
1. I guessed that widget would be complicated yes, too much work it seems
2. I agree that extra icons can be overwhelming with a busy screen
3. Fair enough yeah that is not a big problem, our screens are not that big yet :)

Actually most useful item for me is a flag for highlight/notes, which was the starting point of this issue. Rest is just brainstroming. 

So a **"this book contains highlights/notes"** indicator anywhere is enough (using the same Unicode symbol as you said is even better). Number of notes is not even relevant in my use case (but might be useful for some other users). It would be just an indicator that tells me **"you can delete this finished file without exporting"**.

I don't know if other users need this feature too but I guess it might be useful for people who needs exporting often.

**Comment by hius07** [comment]
Finding out whether a book has highlights is simple, notes - not so.

**Comment by offset-torque** [comment]
> **hius07** - Finding out whether a book has highlights is simple, notes - not so (without opening it).

I am a highlighter. I don't take notes so this is fine for me. I added "notes" to the issue thinking that other users might want to know about their notes in the books for the same purpose.

---

Please take this issue not as a "Feature Request" but as a query. Since I can't estimate confidently how many users might benefit from this, I am assuming this is currently a personal issue. Because of this I can't justify the implementation of this feature if it requires too much effort. If it is hard, we can wait for other users to request this to decide.

(Now I am thinking loudly, I noticed that there might be a performance impact since file list probably should be refreshed each time FB is opened to reflect the **hl/note status** of the file. I assumed there might be a one-time flag in the sdr when the first highlight is made in the book but didn't think of the details. Hmmm, maybe this is not that easy to implement as I thought :)

**Comment by hius07** [comment]
I see a couple of issues in the Detailed list mode.

<img width="300" alt="01" src="https://user-images.githubusercontent.com/62179190/227852997-64a5d89f-cbf6-4f1d-ba58-f7682ceb2d7a.png">

<img width="300" alt="02" src="https://user-images.githubusercontent.com/62179190/227853013-2a0b6410-9986-423e-9191-8bafede513ba.png">

(1) For supported file types we accept the double extension as file format:
https://github.com/koreader/koreader/blob/df9c2bcb7f9f1d3f60bfaad20996a2b029d5b584/frontend/apps/filemanager/filemanagerbookinfo.lua#L42-L53.
It is not shown in the ListMenu.

(2) The new mandatory now can be a read last date, it is longer than the file size and we get too narrow space for the filename.

(3) In Classic mode the mandatory (showing filesize, dates etc) is the rightmost field. ListMenu shows the file type as the rightmost field.

So the idea to discuss is to move the filetype to some other place in the ListMenu book slot.

**Comment by poire-z** [comment]
> The new mandatory now can be a read last date, it is longer than the file size and we get too narrow space for the filename.

Or for the sample in the screenshot: don't show the hour:minute, just the YYYY-MM-DD.

**Comment by NiLuJe** [comment]
As far as the double-extension thing goes, I'd be inclined to show FB2 instead of ZIP for FB2.ZIP?

(Or whip up a custom portmanteau extension like FBZ, àla .tar.gz => .tgz).

**Comment by hius07** [comment]
How should we sort by type?
```
a.fb2
c.fb2
a.pdf
b.pdf
b.fb2.zip
d.fb2.zip
```
or
```
a.fb2
b.fb2.zip
c.fb2
d.fb2.zip
a.pdf
b.pdf
```
or
```
a.fb2
c.fb2
b.fb2.zip
d.fb2.zip
a.pdf
b.pdf
```

**Comment by poire-z** [comment]
No real opinion - no idea why somebody would need to sort by file type :) Possibly to regroup files of a same format, assuming they were related (ie. Wikipedia epubs generated from lookups done when reading a bunch of PDFs in that directory).
As for fb2 vs. fb2.zip, you and your fellow FB2 readers are the best to decide about that.

**Comment by offset-torque** [comment]
> How should we sort by type?

Third one looks logical to me, at least this is what I would expect to see when I sort by filetype:
a.fb2
c.fb2
b.fb2.zip
d.fb2.zip
a.pdf
b.pdf

**Downsides of 1 and 2:**
1. Probably users want to see fb2's together
2. Interleaved list (fb2-zip-fb2) might look very cluttered

**Comment by Frenzie** [comment]
The first or the third — the second would annoy me. ;-)

**Comment by hius07** [comment]
A mark for books with highlights as proposed in https://github.com/koreader/koreader/pull/10276.

<img width="300" alt="01" src="https://user-images.githubusercontent.com/62179190/229271741-8fcd2ffe-cd69-495a-afad-b8f45b98bc35.png">

**Comment by offset-torque** [comment]
This looks very pleasant (in addition to being useful), thanks for spending effort on this **hius07** 🙏

**Comment by offset-torque** [comment]
I am closing this issue because I think it served its purpose.

**Summary:**
- We got a "highlights indicator" from this issue by **hius07** (thanks again) and concluded that "notes indicator" is hard.
- "Currently reading" indicator is not very important because unopened books are relatively easy to differentitate.
- I want to repeat that a more visible kind of "finished indicator" would be better in crowded directories, but it is not terribly important.

Thanks everyone for discussion.
