### ISSUE TITLE
Screen orientation problem.

### ISSUE THREAD

**Issue by nulllee** [koreader/koreader#10173]
* KOReader version:2023.01
* Device: kindle paperwhite3 5.14.2

#### Steps to reproduce: My spoken English is poor. Hope someone can help me translate my words more accurately.
Chinese: 在kindle系统中进行最后一次阅读时选择“横屏”，之后在kindle原系统中点击epub、pdf一类的文件打开，而不是通过kual先打开koreader再用koreader打开文件，此时屏幕显示的操作界面与实际的操作界面会不在同一位置——大体上是顺时针旋转了90°（更精确的位置我不确定，有时候有些按钮好像根本按不到）。只要回到kindle原系统中选择“竖屏”，再用koreader进行阅读就会恢复正常。
English: Choose landscape mode in kindle system and open a book(epub, pdf, cbz and etc.) directly without using Kual. Then the displayed UI location is not the same as its actual location. Come back to kindle system, open a book and choose portrait mode, then the koreader will work properly.

##### `crash.log` : No crash.

**Comment by hius07** [comment]
> open a book(epub, pdf, cbz and etc.) directly without using Kual

What is it? KPVBooklet or something else?

**Comment by nulllee** [comment]
> > open a book(epub, pdf, cbz and etc.) directly without using Kual
> 
> What is it? KPVBooklet or something else?

Yes, KPVBooklet. I have installed it. More accurately, open a koreader-supported book on kindle UI. Not start koreader in kual then open the book in koreader file brower. Sorry for my poor English.

**Comment by hius07** [comment]
I'm afraid it won't be fixed. KPVBooklet is unsupported and archived.
See readme at https://github.com/koreader/kpvbooklet.
