### ISSUE TITLE
how can i hide shortcut letter

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#10177]
![IMG_20230303_174449](https://user-images.githubusercontent.com/5170835/222687576-69e0f60a-5afc-4310-95c4-7bce48d815af.jpg)

is it possiable to hide the letter(shortcut?,like Q W E R T),i cannot find any options to hide it

**Comment by Frenzie** [comment]
Which device is that?

**Comment by dandelions** [comment]
> Which device is that?

It's a docker app, based on linux maybe

**Comment by Frenzie** [comment]
You could create a file `patches/2-no-keyboard-shortcuts.lua` with the following content. See <https://github.com/koreader/koreader/wiki/User-patches#overview> for more information.

```lua
-- 2-no-keyboard-shortcuts.lua
--
-- Hides keyboard shortcuts on devices with keyboard.

local Device = require("device")

Device.hasKeyboard = function () return false end
```

**Comment by zwim** [comment]
Thanks, I have updated  https://github.com/koreader/koreader/wiki/User-patches#overview

**Comment by dandelions** [comment]
Yes,it works,thanks very much!

**Comment by mr-scrawley** [comment]
If you want to keep other keyboard functionaliy (e.g. shortcuts), you can use the following instead:

```lua
-- 2-disable-item-shortcuts.lua
--
-- Hides keyboard item shortcuts on devices with keyboard.

local Menu = require("ui/widget/menu")

Menu.is_enable_shortcut = false

```

**Comment by filviu** [comment]
Could it be that something changed in koreader lately (I'm running 2025.10) and this seems to have stopped working.

**Comment by Frenzie** [comment]
Not in that regard, no.

**Comment by filviu** [comment]
Thank you, then it must be me, I'll keep searching.
