### ISSUE TITLE
Cannot change the home directory

### ISSUE THREAD

**Issue by Grooveofmimosa** [koreader/koreader#10181]
* KOReader version: 2023.01
* Device: Hisense A9

#### Issue
I customized the home directory several days ago, and I tried to change it. However, the home directory always changes back to previous settings after exiting the app. The folder shortcuts disappear as well.

**Comment by hius07** [comment]
Looks like an Android related issue.

**Comment by pazos** [comment]
> Looks like an Android related issue.

Indeed. Hopefully not all of them but some bad apples :p

> I customized the home directory several days ago, and I tried to change it. However, the home directory always changes back to previous settings after exiting the app.

Try to set the new home or any other setting and, just after that, exit the app from the hamburguer menu -> exit.

Some android eink devices break AOSP compatibility (purposely or by accident) and in these devices changes in settings might get lost if the program doesn't get the chance of flushing the new settings.

**Comment by Grooveofmimosa** [comment]
> Try to set the new home or any other setting and, just after that, exit the app from the hamburguer menu -> exit.
Thanks! It works
