### ISSUE TITLE
FR: filter bookmarks by style

### ISSUE THREAD

**Issue by benasocj** [koreader/koreader#10189]
Currently, when listing the bookmarks, it's possible to filter by "highlights", "notes" or "page bookmarks", using the menu button on the top left. It would be great to extend this by adding additional filters for the different bookmark styles ("lighten", "underline", "strikeout", "invert"). This way, I could only list bookmarks with the strikeout style, for example.

My use case for this is that I highlight errors in the ebook with the strikeout style. Once I completed reading the ebook I would like to display all strikeouts so that I can then report the errors to the publisher.

**Comment by hius07** [comment]
My dream is to combine highlight and bookmark databases.
