### ISSUE TITLE
FR: calibre - add "Connect" action to dispatcher

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#10191]
Asked in https://www.mobileread.com/forums/showthread.php?t=352660.

**Comment by pazos** [comment]
Current implementation makes impossible to call `CalibreWireless:connect` or `CalibreWireless:disconnect` twice in a row by toggling the action of the button based on current state.

If somebody is going to implement this please make sure to test what happens and implement checks on these functions.

**Comment by pazos** [comment]
Added in #11806
