### ISSUE TITLE
Plugin Vocabulary Builder: resetting word progress doesn't function properly

### ISSUE THREAD

**Issue by Kelamir** [koreader/koreader#10194]
* KOReader version: KOReader master branch(latest release being [2023.01 "Winter Ivy"](https://github.com/koreader/koreader/releases/tag/v2023.01)
* Device: Running through `kodev run`

#### Issue
If you add a word, then click reset word progress, and press "Got it", you can notice the word's interval is not reset. Instead, it's going to be higher than the last one before a reset happened.
#### Steps to reproduce
![reset](https://user-images.githubusercontent.com/61295121/224487508-c1f87847-6258-430f-9eda-d67e85074902.gif)

**Comment by weijiuqiao** [comment]
Thanks for catching it. I missed one property when doing the reset.
