### ISSUE TITLE
Instant translation possible ? 

### ISSUE THREAD

**Issue by Jeanaimarre** [koreader/koreader#10199]
Koreader kindle

 Good morning I can't figure out if this already exists or not by browsing the forums.

 I saw that it is possible to highlight a text and translate it into the desired language.

What I would like is to know if it is possible to ask Koreader to translate the entire book page by page (instant translation) without having to highlight the content?

Thx :)

**Comment by Frenzie** [comment]
That'd be very difficult to do, on top of which I suspect you'd quickly get rate limited. It sounds like a something more suited for something like a calibre plugin for example.

**Comment by NiLuJe** [comment]
Or even... bear with me here... a human being whose job it is to translate literary works?! ;o).

**Comment by Frenzie** [comment]
Machine translation is impressive yet atrocious, but I imagine the question implies no proper translation exists. ;-)

**Comment by Jeanaimarre** [comment]
In reality, I would have just liked a small button to select the entire page and translate into the language chosen from the options... If there was already that, that would be good!
