### ISSUE TITLE
FR: search by file title/author

### ISSUE THREAD

**Issue by dmalinovsky** [koreader/koreader#10207]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently, the file browser allows to search by the file name, which isn't very useful if you want to find a specific book.

**Describe the solution you'd like**
File browser should allow searching by the book's title and/or author. This information should be taken from the file metadata.

**Describe alternatives you've considered**
The other alternative is to use the built-in file browser and open the books from it. It's not perfect, but it works. It's still preferable to be able to do all operations without leaving KOReader.

There's also similar looking "Calibre metadata search" function, but it's not documented and doesn't seem to work.

**Comment by NiLuJe** [comment]
WIll be fixed by #10198
