### ISSUE TITLE
FR: option for double-page layout in muPDF

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10204]
**Does your feature request involve difficulty completing a task? Please describe.**
I would like to have an option to show two pages at once in landscape mode in muPDF.

**Describe the solution you'd like**
Similar to crengine's `two columns` option.

**Describe alternatives you've considered**
For now I am using Page Browser with one row and two columns. However  I use it a lot in crengine as well where I set 9 pages overview, and I need to change the layout each time I switch between the file types by swiping (it takes a while).

**Additional context**
So in this double-pages mode I am not able to actually read text on 7,8-inch screen, of course, but it gives a good overview for repetitive plots. Page Browser has a lot of extra things around the pages, so it makes it harder to read.
In the long term I plan to get a larger screen eReader, so this feature will be awesome to have.

**Comment by mergen3107** [comment]
@poire-z 

With Kindle Scribe also being able to have KOReader now, does this FR have a chance to have attention? :D

**Comment by NiLuJe** [comment]
Probably not, MuPDF is pain ;).

**Comment by poire-z** [comment]
Don't ask me, I'm not familiar with the PDF/Kopt/ReaderPaging stuff.
(I guess if MuPDF/Kopt do not do it themselves, it would need us to combine 2 output, and adjust all x/y... so probably some quite heavy work.)

**Comment by mergen3107** [comment]
Alright, I will resort to Page Browser then :D 

Thank you guys!

**Comment by gingerbeardman** [comment]
Came here to request this :(

**Comment by mergen3107** [comment]
@gingerbeardman 
We can ask upstream mupdf, I am just not sure they are willing to implement new features :D

**Comment by gingerbeardman** [comment]
I'll try. 

Also I'm reading above: what is crengine? Can I use that? 

So it's clear my goal is to read magazines with two page spread.

**Comment by Frenzie** [comment]
> We can ask upstream mupdf, I am just not sure they are willing to implement new features :D

I think they'd just say downstream should render two pages themselves. But you can always ask I suppose. :-P

**Comment by gingerbeardman** [comment]
*insert jpg of two Spiderman pointing at each other*

**Comment by mergen3107** [comment]
Let's reopen this issue since it gets more attention :D

**Comment by gingerbeardman** [comment]
I just read that apparently mupdf already supports it

core.setDisplayPages(2);

https://github.com/joniks/Android-MuPDF/blob/6d544a72e82ee89a48db965c7fa07f4c1b71274a/library/src/com/artifex/mupdflib/MuPDFActivity.java#L504

**Comment by benoit-pierre** [comment]
That's their Android App, not the core MuPDF library.

**Comment by gingerbeardman** [comment]
> That's their Android App, not the core MuPDF library.

Interesting! I have tried their android app and it doesn't show two pages in Landscape.

**Comment by gingerbeardman** [comment]
I registered for MuPDF bug tracker and it's a WONTFIX for them to implement it (in their own app?)

https://bugs.ghostscript.com/show_bug.cgi?id=702484

**Comment by Frenzie** [comment]
> > We can ask upstream mupdf, I am just not sure they are willing to implement new features :D
> 
> I think they'd just say downstream should render two pages themselves. But you can always ask I suppose. :-P

But more seriously, then it also wouldn't work in DjVu or picture documents (like GIF or TIFF), so it makes a lot more sense to do it somewhere around here regardless.

**Comment by wnmagardician** [comment]
I would also like this! Would like to get this to work on my kindle scribe

**Comment by OGKevin** [comment]
👋🏾 Since the MR didn’t make it upstream, I’ve extracted it into a separate plugin.

It’s still early days, but it seems to work on my machine.
Feel free to give it a test, and please make sure to make backups before you do.

If you encounter any bugs or have feedback, please open an issue. 🙂

https://github.com/OGKevin/comicreader.koplugin
