### ISSUE TITLE
FR: Option for removing endnote section from progress bar

### ISSUE THREAD

**Issue by 8dcc** [koreader/koreader#10209]
**Does your feature request involve difficulty completing a task? Please describe.**
In books with lots of notes, the *Notes* chapter can use more than 50% of the progress bar, making it less useful.

**Describe the solution you'd like**
A simple checkmark option under `Gear -> Status bar -> Progress bar` that ignores the *Notes* chapter when displaying it.

**Describe alternatives you've considered**
I am not sure if it's possible to do, or if there is no way of knowing what the *Notes* chapter is. I tried searching but I could not find anything related to this, maybe I can fix it by editing a file or some styles.

**Additional context**

![Screenshot_20230315-101416](https://user-images.githubusercontent.com/29655971/225263288-c07b236f-d794-4ea1-81ba-674b94afa86f.jpg)

**Comment by hius07** [comment]
Previous discussions: https://github.com/koreader/koreader/issues/8254, https://github.com/koreader/koreader/pull/8265.

**Comment by 8dcc** [comment]
> Previous discussions: #8254, #8265.

I see, thank you. I thought this could be a duplicate but I could not find the issue.

> Footnotes can be excluded with checking `Hide non-linear fragments`.

Where is this option?

**Comment by hius07** [comment]
If a book is structured with non-linear fragments the item appears in the upper menu first tab Navigation.

**Comment by 8dcc** [comment]
I see, I guess the none of the publishers I checked enabled that. Although it's inconvenient, I will try to use the tweak from the comment you linked.

Thank you.

**Comment by poire-z** [comment]
Ideally, a proper (and better than "set last page" and the ugly attempt I had to turn it into page flows) solution could be combined with the handmade ToC I suggested at https://github.com/koreader/koreader/issues/10193#issuecomment-1464453447.
In Page browser, we could long-press on page thumbnail and "Start/end non-linear flow here", "Start chapter here"...

**Comment by 8dcc** [comment]
> In Page browser, we could long-press on page thumbnail and "Start/end non-linear flow here", "Start chapter here"...

Yes, that would be more convenient.
