### ISSUE TITLE
The magnetic sleep cover stopped working on the Kobo Glo

### ISSUE THREAD

**Issue by Nanco300** [koreader/koreader#10200]
* KOReader version: KOReader 2023.01 "Winter Ivy"
* Device: Kobo Glo

#### Issue

I'm using the latest version of Koreader and magnet-based sleep is working on the original firmware of the Kobo Glo.

[crash.log](https://github.com/koreader/koreader/files/10951090/crash.log)

**Comment by NiLuJe** [comment]
That's not a verbose debug log, so it doesn't tell us anything ;).

Double-check that you simply haven't disabled sleep cover events in [Gear] > Device settings.

**Comment by Nanco300** [comment]
Think you!
