### ISSUE TITLE
Highlights of a specific book turned into notes

### ISSUE THREAD

**Issue by 8dcc** [koreader/koreader#10210]
* KOReader version: 2023.01
* Device: Android

#### Issue
All my previous highlights from a specific epub book turned to notes. The highlighted text and style is the same, but now there is also a note (just like if I pressed "Add note" on a highlight) with the same text of the highlight. For example if I highlighted this section:
```
... [Lorem ipsum dolor sit amet, consectetur adipiscing elit.] ...
```
Now there is also a note "attached" with the text:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

The icon on the bookmarks tab changed as well, and now clicking the highlight brings up the note. Of course if I edit the note and remove it, the highlight turns back to a normal one, with no pencil icon and no note.

If I add new highlight or note it's displayed okay, and my other books are fine. The actual notes I had written are okay and in the same location.

#### Steps to reproduce
As far as I know, I did not touch any specific option regarding notes or highlights that could cause this, and I did not edit the `metadata.epub.lua` file.

I feel like editing it back would be the easiest way of fixing this, but I am not sure what parts of the file actually indicate notes of highlights (Inside that file there is a `["highlight"]` and a `["bookmarks"]` section, inside each bookmark there is a `["text"]` and a `["notes"]` section, but because they now have the same text, except the page number and timestamp, I am not sure which one is the "wrong" one).

**Comment by 8dcc** [comment]
Fixed it by replacing the `["text"]` part of the bookmarks with `""`:
```regex
s/\["text"\] = "Page .*",$/\["text"\] = "",/
```
In the `metadata.epub.lua` file.

Still no clue what caused this.

**Comment by hius07** [comment]
This may be caused if you had the setting "Add page number / timestamp to bookmark" checked, and then changed the language of the KOReader interface.
