### ISSUE TITLE
Context menu option for defining / searchng the selected phrase in google / browser 

### ISSUE THREAD

**Issue by unacceptablet** [koreader/koreader#10211]
I am new to Koreader & already in love with it. So much tweaking can be done on this app! Here is the request I would like to put before the esteemed developers: 

It takes too many steps to search for the definition of a word / phrase in the web - copying the word from koreader then opening EinkBro (in Onyx Boox Leaf 2) to search it's definitin in google. (Sometines multiple dictionaries / wikipedia etc. are not enough to clearly understand a word / concept; you just have to google it.)

Here is the solution I would like: When I long press a word in a book, the pop up menu should include an option called 'Define'. Clicking this option will open the default brower with a link like this : 
`https://www.google.com/search?q=Define%20%s`
Here, the selected word / phrase takes the place of `'%s'`.  After viewering the definition, I should be able to quickly switch back to Koreader again. 

An alternative solution may be creating a pop-up browser window inside Koreader. But that may be too much work. 

If someone can show me a way to do this without going too deep into coding, then parhaps I can do it myself. (I am not a programmer/coder but sometimes edit some autohotkey scripts.)

Here is a video showing this implemented in Ankidroid (a popular memorization / flash card app in android):

https://user-images.githubusercontent.com/127971612/225367751-27680f48-6104-4653-8c98-c3c0ac805557.mp4

**Comment by Frenzie** [comment]
Under dictionary settings you can select to use an external dictionary.

See https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-dictionary-list for how to customize it further.

**Comment by unacceptablet** [comment]
> Under dictionary settings you can select to use an external dictionary.
> 
> See https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-dictionary-list for how to customize it further.

Thanks for your quick reply. I am trying this out on my android phone. 
For some reason Chrome does not come up in the dictionary list ( even though Aard2, Alpus, ColorDict etc are showing)

Here is what I have done:
As per the link you provided, I created koreader/dictionaries.lua & pasted the the code from this link-
https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L49-L63

Then I insterted these lines in the .lua file:
```
return {
    { "Generic", "App picker", true, nil, "send" },
    { "Chrome", "Chrome", false, "com.android.chrome", "chrome" }, 
}
```
This does not show chrome in the dictionary list & does not open up chrome when I long press a word (though Aard2 is working fine).

One more thing, when i use external dictionaries, i cant use the internal ones. But i dont want that. Is there a way to eneable both? When i long press a word internal dictionaries should work normally but should have and extra button/option that takes me to the external app.

Thanks

**Comment by pazos** [comment]
chrome is not a valid action. `send`, `search` and `text` are. If chrome is not enumerated in the app picker with the first option it means it doesn't handle send intents. Probably you want to try the two others.

The `send` action is already available as "share text" in the context menu when you highlight.

> One more thing, when i use external dictionaries, i cant use the internal ones. But i dont want that. Is there a way to eneable both? When i long press a word internal dictionaries should work normally but should have and extra button/option that takes me to the external app.

It doesn't work that way, I'm afraid. The less annoying thing we can do would be expand the "share text" button to pop up a submenu with "send, share, process".

It would work for a bunch of android stuff but won't be as customizable as custom dicts is.

**Comment by unacceptablet** [comment]
After tinkering with Einkbro, I found solutions to a few of my problems.

>A more pressing issue is, when I click 'share text' option, a number of apps shows up but none of them are Google app or Kiwi browser or Chrome. There is an edit option to add more apps to the list but again those browser apps / Chrome / Google app is absent. So web look-up for a word can not be performed using those apps. It seems only apps that hadle texts items shows up including Aard 2. Is there a way to add browser app to the list? Or parhaps an app that can push the selected words to chrome or google search.

Einkbro does show up. So I will use that instead of Chrome.

>Joining these 2 strings gives us the URL ([www.google.com/search?q='the](http://www.google.com/search?q=%27the) selected text')

I was able to accomplish this using options inside Einkbro. Go to settings>search>custom search engine>(put whatever search engine or words you like). I used : "www.google.com/search?q=Define ". This will put the word 'Define ' before whatever text you selected in Koreader & used 'share text' option to push to Einkbro.

>But the problem is I have to press a word a long time (like 3 seconds) to find 'share text' option (along with all other context menu items). Is there a way to reorder these items so that 'share text' option comes up as soon as a word is highlighted? (lets say, can we replace 'close' or 'wikipedia' option with 'share text' option).

The only remaining problem - Is there any way, I can change options shown in the pop up dictionary menu table?

![Screenshot 2023-03-18 215630](https://user-images.githubusercontent.com/127971612/226116642-502d3e59-c776-471a-93e2-7f6f824b3c55.png)

**Comment by unacceptablet** [comment]
For anyone who is looking for a similar feature - A plug in has been created by EinkBro dev that adds a button to pop-up dictionary window that takes us directoly from Koreader to EinkBro.

link: https://github.com/einkbro/askeinkbro/releases/tag/v0.3

![252021748-207aaf9f-1b57-48c8-8134-1206ca1511de](https://github.com/koreader/koreader/assets/127971612/20dab42d-3a51-428e-a3fd-48dff7759ac7)
