### ISSUE TITLE
FR: mupdf: highlight links or add long tap to follow link

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10213]
**Does your feature request involve difficulty completing a task? Please describe.**
I read articles that have tons of internal links to source citations. These are the worst, I keep taping the links instead of turning pages, opening top and bottom menus. 

**Describe the solution you'd like**
Can you please make an option to highlight the links in mupdf?

A better alternative is to allow to follow links not by tapping but by long tapping. 

**Describe alternatives you've considered**
The only alternative is to disable following links by taps. But I need these links most of the time because I use them to find referenced articles. 

Thanks!

**Comment by poire-z** [comment]
If you turn pages with tap, just disable tap to follow links - if you don't use swipe for other things, enable `Swipe to follow nearest link` ?

As for highlighting links with MuPDF, no idea if that is possible.

**Comment by mergen3107** [comment]
I tried swiping for links, but it is imprecise :(

I use tap mostly because many times I need to skim through fast by tapping

**Comment by jonnyl2** [comment]
@mergen3107 Note that when you swipe to follow links, it only matters where you **start** the swipe motion, not where you end it or some middle point. Also, when you long press on a link, the default dictionary view screen will also have a `Follow Link` button on the bottom.

**Comment by mergen3107** [comment]
@jonnyl2 
Thanks for suggestion! 
The swipe take me time to learn because in condensed articles line spacing is tight, and swipe sometimes gets confused for page swiping. I am still trying to enable/disable various taps and swipes :D
