### ISSUE TITLE
FR:Expand "tag" function to support global tag expressions. When there is a file name in a text file,You can jump to another text file or Floating display size adjustable text viewer or Display another text in columns.

### ISSUE THREAD

**Issue by D22699** [koreader/koreader#10215]
We mainly look at (. cpp/. h) code files on a 13.3 inch ink screen device, and it feels like KOReader is too easy to use.
However, KOReader does not support. cpp files, although they can also be opened.

Expand  "tag" function to support global tag expressions. When there is a file name in a text file,You can jump to another text file or Floating display size adjustable text viewer or Display another text in columns.

When the "tag" has a file name, the above three functions are supported, mainly for the convenience of. CPP files, viewing the output text, or jumping to another file.

The key point is support, where two or more texts can be displayed side by side for easy viewing.

If the above functions can be implemented, a further extension can be made to support limited script expressions in text files, and expand a floating small window to display multiple pieces of text.

This works in scenarios such as test papers/code/tutorials/thesis links, and so on.

**Comment by poire-z** [comment]
I also don't understant what you call "tags", and neither what could be this "tag" support we have and that we could "expand".
If it's something like https://en.wikipedia.org/wiki/Ctags, it's totally out of scope of the project. We're a book reader, not a source code viewer.
If what we could "expand" is our support for links, well, we have it, there's nothing more fancy to support. We support href links from HTML to other HTML files. We support intra links inside a document.

If you want to have what I think I understand you want, it's not KOReader's job.
It's your job to find or build a tool to process all your plain sources code files and turn them into HTML files, find out the names and their target, and make the HTML files accordingly. This tool could even build a standalone EPUB from many source files.
You make a book out of your source code - and you read that book with KOReader.

A quick search: https://www.google.com/search?hl=en&num=25&q=source+code+to+epub
and this might be what you want: https://github.com/agentzh/code2ebook
And we render the sample EPUBs at https://github.com/agentzh/code2ebook#sample-ebooks pretty well, we may (with luck) even catch and consider linked functions at footnotes popup :):
![image](https://user-images.githubusercontent.com/24273478/226063383-38c0f210-9ebf-4dbc-b9bf-8537d9e06501.png)

**Comment by poire-z** [comment]
Out of scope, any feature like that should be in the hand of another project that would generate an EPUB with proper internal links.
