### ISSUE TITLE
Garbled characters when reading gb2312 text file.

### ISSUE THREAD

**Issue by himisawww** [koreader/koreader#10218]
* KOReader version: 2023.01
* Device: Paperwhite 2, Android

#### Issue
same as [issue #561.](https://github.com/koreader/koreader/issues/561)

When reading txt file encoded in cp936 (gb2312), sometimes the tail of one paragraph will be garbled, as if 1 byte is lost.

Bug: 
![ansi_cp936_bug](https://user-images.githubusercontent.com/127312115/226109640-b15056bf-8a22-45c1-bd2a-735800921221.jpg)

Actuall file content:
![ansi_cp936](https://user-images.githubusercontent.com/127312115/226109660-d61fc8e4-b0aa-4b99-be95-f4f12209df7a.png)

The txt File:
[cp936_garbled.zip](https://github.com/koreader/koreader/files/11008649/cp936_garbled.zip)

Is this a over 9-year-old bug? Please fix this....

**Comment by poire-z** [comment]
Hard to debug for a non-chinese reader like me :/
If I strip some lines before, it gets displayed ok (I think), so it may not be a gb2312 encoding issue, but something about reading chunk of the text file, and may be stopping/stumbling inside a multibyte char and then losing sync... A bit like what I described at https://github.com/koreader/koreader/issues/9824#issuecomment-1326365540 - but it's not exactly there (if I increase these 2000 to 200000, I get the same crap at this point in the file...)

**Comment by himisawww** [comment]
> If I strip some lines before, it gets displayed ok (I think), so it may not be a gb2312 encoding issue, but something about reading chunk of the text file,

Yes! I found the starting point of the garbled text is at a whole kiB offset! ( 416kiB = 425984 Bytes in example) 
Clearly this bug is occurring at reading files by chunks of whole kiBs and spliting a whole character!

**Comment by poire-z** [comment]
:)

I was seeing this:
![image](https://user-images.githubusercontent.com/24273478/226114327-653d8544-4c4d-46d0-94eb-c461518c0f43.png)
and wondered: how am I supposed to notice this chinese is garbled chinese !!!

Until I removed a few lines, and saw this:
![image](https://user-images.githubusercontent.com/24273478/226114366-bd18b3f1-7d75-4f58-87c2-b32960e5b2f9.png)

So, thanks for this sample file :)
(Not sure I'll manage to get anything, the text parsing code is quite complex...)

**Comment by poire-z** [comment]
Looks like both your test cases are solved when tweaking https://github.com/koreader/crengine/blob/17bd24ede606592a04be79c68b54dcf19093b43d/crengine/src/lvxml.cpp#L423-L475 with:
```diff
--- a/crengine/src/lvxml.cpp
+++ b/crengine/src/lvxml.cpp
@@ -432,6 +432,8 @@ int LVTextFileBase::ReadChars( lChar32 * buf, int maxsize )
             lUInt16 ch = m_buf[m_buf_pos++];
             int twoBytes = ch >= 0x81 && ch < 0xFF ? 1 : 0;
             if ( m_buf_pos + twoBytes>=m_buf_len ) {
+                if (twoBytes) // 2nd byte not yet in buffer: rewind, process them on next call
+                    m_buf_pos--;
                 checkEof();
                 return count;
             }
```
The whole thing is hard to grasp, there's various filling of a byte buffer, and then of a Unicode char buffer, with sliding windows, reading ahead so enough data is available... hard to figure out if fixes wouldn't better be done in these parts.
The above somehow fixes the case down - similarly to what happens in the `case ce_utf8` with Utf8ToUnicode() which, when meeting an incomplete multibyte sequence ignore it and only `m_buf_pos += srclen` to what has been read correctly.
I fear issues and infinite loop if an incomplete twobyte is at end of file, but somehow this doesn't happen.
If this is the right fix, I guess it should also be done in all the other `case encoding:` that follow (jis, big5, euc_kr). If you are familiar with one of these other encoding, it would be nice to also have a test case for some of them to confirm it's also needed there.

If by chance you are C litterate (looks like you are :), you could have a look at this section and see if, like me, it feels this kind of being careful before `m_buf_pos++` is done better (and so, if it is done, it's what we have to do!) in the other sections (utf8, utf16, utf32) than in the ce_gbk and similar branches, and that this carefulness is all there is to do :)

**Comment by himisawww** [comment]
Thanks!!!

I think your current modification is indeed the exact solution of this bug. The former code just dropped 1 byte at the end of buffer, as if it's the last incomplete byte at the end of file, however it isn't! This mistake cannot be repaired anywhere else. 

When a file ends with an incomplete byte, the checkEof() call will force eof and avoid the infinite loop.
(see https://github.com/koreader/crengine/blob/3ff7558e8aeabba74105499898ddb470dd887227/crengine/src/lvxml.cpp#L222 )

For other encodings, similar patch should also be needed. I created a Shift-JIS test file for more test (but i know little about Big5 or euc_kr).

[easytest_shift_JIS.txt](https://github.com/koreader/koreader/files/11009418/easytest_shift_JIS.txt)

**Comment by Frenzie** [comment]
(moved the duplicate label to the other one)

**Comment by himisawww** [comment]
> When a file ends with an incomplete byte, the checkEof() call will force eof and avoid the infinite loop.
(see https://github.com/koreader/crengine/blob/3ff7558e8aeabba74105499898ddb470dd887227/crengine/src/lvxml.cpp#L222 )

However this checkEof logic is also BUGGY, texts with normal endings will also be forced to eof if the length of file is 8kiB+0~3Bytes. The following file will be able to illustrate this bug.

[EndofFileTest.txt](https://github.com/koreader/koreader/files/11009490/EndofFileTest.txt)

This bug will occur only for files with specific length, and will only affect no more than 3 characters at the end of file, I don't know if it's worth to fix it.

**Comment by NiLuJe** [comment]
Quick drive-by with no way to double-check, but that "is non-ASCII" check can probably be simplified to `ch & 0x80` (if it's non-zero, it's non-ASCII, e.g., potentially multibyte).

I also haven't checked if it's just an infortunate variable name, or if the code indeed only assumes than non-ASCII means two-bytes, because... that's not the case ;o). (Hence my previous use of "multi", e.g., it could be up to 4-bytes).

**Comment by himisawww** [comment]
> However this checkEof logic is also BUGGY, texts with normal endings will also be forced to eof if the length of file is 8kiB+0~3Bytes. The following file will be able to illustrate this bug.

To solve this bug, I think a new flag ( say m_filetail ) should be present.

When the first time checkEof() goes into its if code block, it can check if m_filetail is set, if not, it set this flag and just return. When second time checkEof() is called and this flag is set, it can do force eof and drop any remaining bytes.

I don't know much about code arrangement of koreader, and these are just my suggestion.

**Comment by poire-z** [comment]
@NiLuJe : yes, m_buf is lUInt8 and it uses `lUint16 ch` so it can reuse that variable to later make it hold a larger value.
But all these bits of code are marked `// based on ICONV code, gbk.h` and as often, don't want to change what's not needed (and there, what I don't really care about and will never revisit :)

@himisawww : thanks for the test file, same kind of fix makes it work. I'll visit the other branches to make the same kind of fixes, should hopefully not really need test files.

I agree with your remark about checkEof() - thought we could just ignore it (losing a few chars at end of file, in english or french, we could still guess the final word of a novel :) but I guess with Chinese, it may be ambiguous/unguessable :)
I'll try your `m_filetail` suggestion. Thanks for having given it some thoughts :)

**Comment by poire-z** [comment]
Btw, isn't there another bug there (if buffer ends on a non-twoByte char, we might drop it ?)
```c
        for ( ; count<maxsize; count++ ) {
            if (m_buf_pos >= m_buf_len) {
                checkEof();
                return count;
            }
            lUInt16 ch = m_buf[m_buf_pos++];
            int twoBytes = ch >= 0x81 && ch < 0xFF ? 1 : 0;
            if ( m_buf_pos + twoBytes >= m_buf_len ) {  // HERE : shouldn't it be > and not >= ??
                if (twoBytes) // 2nd byte not yet in buffer: rewind, process them on next call
                    m_buf_pos--;
                checkEof();
                return count;
            }
            lUInt16 ch2 = 0;
            if (twoBytes)
                ch2 = m_buf[m_buf_pos++];
```

**Comment by NiLuJe** [comment]
We're not checking for overflow of ch itself, but for overflow of its subsequent byte, i.e., ch + 1, so, no, both of those make sense to me?

I'd be more worried about the return value, though, because without checking the context, I'm not quite sure what `count` points to and whether it should account for the chopped byte or not ;).

**Comment by poire-z** [comment]
> We're not checking for overflow of ch itself, but for overflow of its subsequent byte, i.e., ch + 1, so, no, both of those make sense to me?

But we did `m_buf_pos++` when reading the first byte, so we are in the same situation: checking if we can read one byte, so we should do it the same way : `if (m_buf_pos >= m_buf_len) {` (and no need to check if not twoBytes).

**Comment by NiLuJe** [comment]
> But we did `m_buf_pos++` when reading the first byte, so we are in the same situation: checking if we can read one byte, so we should do it the same way : `if (m_buf_pos >= m_buf_len) {` (and no need to check if not twoBytes).

Oh, duh', right; the multibyte branch should only account for the rewind itself, not the end-of-buffer check.

**Comment by himisawww** [comment]
> Btw, isn't there another bug there (if buffer ends on a non-twoByte char, we might drop it ?)

Yes you are right. The sign should be > and not >=. This bug can be tested by following file.

[TestGreaterorEqual.txt](https://github.com/koreader/koreader/files/11009713/TestGreaterorEqual.txt)

**Comment by poire-z** [comment]
> I'd be more worried about the return value, though, because without checking the context, I'm not quite sure what `count` points to and whether it should account for the chopped byte or not ;). (By which I mean, we rewind the cursor `m_buf_pos`; but we don't correct `count`, and I would naively assume that it should be reporting the amount of bytes written to the buffer, and we just dropped one ;)).

`count` is the number of unicode chars we made into the output buffer, and not how many bytes we moved along in the input buffer - so it all feels ok everywhere: count starts at 0, and we have `for ( ; count < maxsize-1; count++ ) {` so it gets incremented to the correct number of what's been created when we re-loop - then, we can get out anywhere inside that loop with `return count` as long as we haven't added anything new to the output buffer - and we should keep the input buffer pos `m_buf_pos` consistent with what we consumed, for a possible next call to this whole function.

**Comment by poire-z** [comment]
Ok, proposed fixes in https://github.com/koreader/crengine/pull/515.
It solves all your 5 test files issues - but please have a look if all that makes sense, and if my comments are right :)
For the checkEof() issue, I'm not sure we can go with your m_filetail idea, mostly not really knowing where I should reset it (everytime we return a count > 0 ? would add quite a bit of code here and there).
So, it feels better going with providing how much bytes would be needed. Not sure I got that right.
Still some possible content lost with UTF8, as the inspection/decoding is done in Utf8ToUnicode(), we don't here know if we are interrupted while needing a 1 or 2 or 3 or 4 bytes sequence. I guess we'd need to redo a quick analysis here ?

**Comment by himisawww** [comment]
I'm revieweing the commit...

void LVTextFileBase::checkEof(lvsize_t bytes_needed)
{
    // Should here '>=' be '>' ? i.e.  if(m_buf_fpos + m_buf_len > this->m_stream_size - bytes_needed)
    if ( m_buf_fpos+m_buf_len >= this->m_stream_size - bytes_needed)
        m_buf_pos = m_buf_len = m_stream_size - m_buf_fpos; //force eof
}

**Comment by poire-z** [comment]
You can do a proper github review in the crengine PR (I think you don't need to be a project member for that).
Anyway, I had a hard time understanding this m_buf_fpos business :/ so I'll trust your thoughts on that.
Previously, we had this with >= and bytes_needed = 4 hadcoded.
Now, I would be providing 1, 2, 3 or 4. But, when we provide 2 or 3 or 4, we may already have 1 or 2 or 3 bytes already in. Dunno if that should affect anything.
Me and indices are not friends :)

**Comment by poire-z** [comment]
Assuming we are with
```
m_buf_fpos = 0
m_buf_len = 3
this->m_stream_size = 4
```
and we need `bytes_needed = 1`, that we can get
with `if ( m_buf_fpos+m_buf_len >= this->m_stream_size - bytes_needed)`
`if ( 0 + 3 >= 4 - 1 )` would be true, and we would fail getting it.
So I guess `>` is indeed what we want.

**Comment by himisawww** [comment]
Also I'm confused with the parameter of all the checkEof calls.

For example, 

    if (twoBytes && m_buf_pos >= m_buf_len) {
            m_buf_pos--; // 2nd byte not yet in buffer: rewind, process them on next call

            //why is here checkEof called with 2 ?  m_buf_pos is subtracted by 1 above but m_fbuf_pos is not changed, and checkEof checks with m_fbuf_pos which is the offset of the buffer starting point, not m_buf_pos which is buffer current reading point.

            checkEof(2);
            return count;
        }

**Comment by himisawww** [comment]
I'm not familiar with github's functions...

I would like to change the source file on my computer and upload it here for you to review/commit.  This may take a while...

**Comment by poire-z** [comment]
> //why is here checkEof called with 2 ?  m_buf_pos is subtracted by 1 above but m_buf_fpos is not changed, and checkEof checks with m_buf_fpos which is the offset of the buffer starting point, not m_buf_pos which is buffer current reading point.

You're probably right...
Dunno if we should do the computation in each `checkEof(2 - (m_buf_len - m_buf_pos))`, or if, as we reset m_buf_pos, we can assume in checkEof() to do that.

You can get the raw file:
https://raw.githubusercontent.com/koreader/crengine/0b8f97c547e8bab9f52fc2c148364d65f6b0b1c3/crengine/src/lvxml.cpp
and just upload it edited here (renamed as .txt) and I'll see the diff.

**Comment by himisawww** [comment]
I went through the code and made lots of modifications. Hopefully my comments are clear.

[lvxml_modified.txt](https://github.com/koreader/koreader/files/11012169/lvxml_modified.txt)

**Comment by poire-z** [comment]
I guess `// require 1 byte as 2nd byte in stream` should be read as `// require 1 more byte from stream to be the 2nd by in this multibyte char` ? or `// require 1 more byte from stream to complete this char` ?

You didn't change checkEof().
Are you sure all your additions can't be factorized in checkEof() , and it would be equivalent?
ie:
`size_t really_needed_from_stream = bytes_needed - (m_buf_len - m_buf_pos);`

**Comment by himisawww** [comment]
> Are you sure all your additions can't be factorized in checkEof() , and it would be equivalent?

You're right, this can be done in checkEof.

[lvxml_modified_3.txt](https://github.com/koreader/koreader/files/11012233/lvxml_modified_3.txt)

is lvsize_t unsigned? This makes me afraid of overflowing to a huge value ...

**Comment by poire-z** [comment]
So, your diff comes down to:
```diff
 void LVTextFileBase::checkEof(lvsize_t bytes_needed)
 {
+    //bytes remain in buffer
+    lvsize_t bytes_remain = m_buf_len - m_buf_pos;
+    bytes_needed-=bytes_remain;
+
     // If we would need bytes_needed more bytes to correctly complete a multibyte
     // char, and we would meet EOF before getting that many, this multibyte char
     // is truncated and invalid: do as if EOF was reached.
     if ( m_buf_fpos+m_buf_len > this->m_stream_size - bytes_needed)
         m_buf_pos = m_buf_len = m_stream_size - m_buf_fpos; //force eof
         //m_buf_pos = m_buf_len = m_stream_size - (m_buf_fpos+m_buf_len);
 }
```
which I guess works for me and your test cases :)
(I'll give it more proper re-thoughts tomorrow.)

> is lvsize_t unsigned? This makes me afraid of overflowing to a huge value ...

Yes indeed - we could use `lvoffset_t` (which is  for that, or just `int` and stop worrying :)
https://github.com/koreader/crengine/blob/17bd24ede606592a04be79c68b54dcf19093b43d/crengine/include/lvstream.h#L38-L46

**Comment by poire-z** [comment]
So, we keep the initial `>=` in:
`if ( m_buf_fpos+m_buf_len >= this->m_stream_size - bytes_needed)`
right ?

**Comment by himisawww** [comment]
> So, we keep the initial >= in:

But why... I afraid not.

I changed the checkEof( the > sign, and rearranged inequality) and the logic in utf8.

[lvxml_modified_checkEof&utf8.txt](https://github.com/koreader/koreader/files/11014713/lvxml_modified_checkEof.utf8.txt)

for utf8 part, I use the return value of Utf8ToUnicode as the count of characters, also I check the last character to determine if we are in middle of 1 character and actually need some more bytes in stream.

**Comment by poire-z** [comment]
OK. I guess I can rewrite it to make it easier to grasp as:
`if ( m_buf_fpos + m_buf_len + bytes_needed > this->m_stream_size )`

Btw, I've seen in the past code from previous chinese contributors to crengine, that looked like your code :):
```c
while(last_ch_pos>0&&(m_buf[last_ch_pos-1]&0xc0)==0x80)--last_ch_pos;
for(lUInt8 testflag=0xc0; nchbytes<4 && (testflag & ch) == testflag; testflag>>=1) ++nchbytes;
if(nchbytes+last_ch_pos>m_buf_pos){// if one character is cut by buffer end
```
This is _extremly_ hard to read for us westerners, and I wondered how people can write code like this. That was before I learned about Chinese and Japanese text not using spaces :) So, I guess your habit of not needing spaces in chinese text leaks into your code, and that is the reason :)

**Comment by Frenzie** [comment]
That looks like someone drew it through a minifier that removes spaces. See https://www.crockford.com/jsmin.html

![image](https://user-images.githubusercontent.com/202757/226381736-191fd167-3f2b-4c2f-93f1-a6cd956718f0.png)

**Comment by poire-z** [comment]
> for utf8 part, I use the return value of Utf8ToUnicode as the count of characters, also I check the last character to determine if we are in middle of 1 character and actually need some more bytes in stream.

(The Utf8ToUnicode() we use there is a `void Utf8ToUnicode(a,b,c,d)` which doesn't return anything, quite confusing with the number of similarly named functions, and not being able to compile and being told of the error :)

> EDIT: Please ignore any change in utf-8 codes. Since I cannot produce any utf-8 test case with visible bug, I think the best way is to just not change the previous code.

Yes, hard to decide what to do without actually seeing any bug.
Still a bit confused if we should keep our `checkEof(1);` when about to start reading a char, or go with your `checkEof(0);` idea - or if both are equivalent when this common situation arise.

Trying to do the right thing for UTF8 "on paper", I came up with:
```diff
@@ -402,7 +408,35 @@ int LVTextFileBase::ReadChars( lChar32 * buf, int maxsize )
             Utf8ToUnicode(m_buf + m_buf_pos, srclen, buf, dstlen);
             m_buf_pos += srclen;
             if (dstlen == 0) {
-                checkEof();
+                /*
+                    // we don't really know how much more are needed:
+                    // we'd need to inspect the coming up chars we can reach
+                    checkEof(4);
+                */
+                // We didn't decode anything: we might be on a multibyte char
+                // at end of buffer, that will be either filled when reading
+                // from file, or not if already at end of file.
+                if (m_buf_pos >= m_buf_len) {
+                    checkEof(1);
+                }
+                else {
+                    lUInt16 ch = m_buf[m_buf_pos];
+                    if ( (ch & 0x80) == 0 ) { // Should be a 1-byte wide char
+                        // Should not happen, it should have been consumed
+                    }
+                    else if ( (ch & 0xE0) == 0xC0 ) { // Should be a 2-bytes wide char
+                        checkEof(2);
+                    }
+                    else if ( (ch & 0xF0) == 0xE0 ) { // Should be a 3-bytes wide char
+                        checkEof(3);
+                    }
+                    else if ( (ch & 0xF8) == 0xF0 ) { // Should be a 4-bytes wide char
+                        checkEof(4);
+                    }
+                    else {
+                        // Should not happen, invalid char ?
+                    }
+                }
             }
             return dstlen;
         }
```
What do you think ?

**Comment by himisawww** [comment]
> What do you think ?

Since the old code looks buggy but no bug can be seen, I think this code block is actually never executed in runtime. You may put a compliable infinite loop (make sure not being optimized) to test this.

I don't want to change anything without visible bug and a test file.

**Comment by poire-z** [comment]
> EDIT: Your modified code is equivalent to checkEof(1), since after srclen = m_buf_len - m_buf_pos; and m_buf_pos += srclen; , m_buf_pos >= m_buf_len must be true.

Actually, Utf8ToUnicode() may change srclen to what it has been able to read.
https://github.com/koreader/crengine/blob/17bd24ede606592a04be79c68b54dcf19093b43d/crengine/src/lvstring.cpp#L3142-L3232
ie.:
```c
void Utf8ToUnicode(const lUInt8 * src,  int &srclen, lChar32 * dst, int &dstlen)
[...]
    const lUInt8 * s = src;
[...]
        ch = *s;
[...]
        } else if ( (ch & 0xE0) == 0xC0 ) { // 2-bytes char
            if (s + 2 > ends) // 2nd byte not yet available
                break;
            if (IS_FOLLOWING(1)) { // all ok & valid
                matched = true;
                *p++ = ((ch & 0x1F) << 6)
                        | CONT_BYTE(1,0);
                s += 2;
            }
[...]
        // unexpected character // that is, enough char, but unexpected continuation, not valid utf8
        if (!matched) {
            *p++ = '?';
            s++;
        }
    }
    srclen = (int)(s - src); // srclen 
    dstlen = (int)(p - dst);
}
```
So, at the point we are trying to fix, it looks to me that if there are char(s) left in the buffer not consumed, it's always because there are enough of them to not look yet invalid, but not enough of them to have the full sequence valid.

> I don't want to change anything without visible bug and a test file.

Yes, I get that :)
But it indeed looks buggy - as it may eats and hide chars at end of file.
And we may indeed trigger infinite loop if we badly fix it :/

**Comment by himisawww** [comment]
> Actually, Utf8ToUnicode() may change srclen to what it has been able to read.

Good! Then all your modified code make sense for me.

**Comment by poire-z** [comment]
OK, added that and more comments to https://github.com/koreader/crengine/pull/515.
If you can please have again a quick review, that all looks coherent with what we hopefully managed to understand and discussed :)
I'll be testing this for a few days just to be sure I don't get any bug on regular books, so it will reach KOReader only in a few days. (If you have a Kobo, I can provide a libcrengine.so for you to also test - I can't for other devices.)
