### ISSUE TITLE
FR: Add 'display folders on top' toggle

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#10222]
**Current behavior**
Currently, only 'Sort by name' has a `mixed files and folders` variant.

**Desired behavior**
Whether to 'always display folders on top' (or not) should be determined by a toggle independent of 'Sort by name', since most of the other file sorting methods can also be combined with this preference.

For example, when sorting by `date added`, we should display new files above directories — unless the user has explicitly enabled the 'display folders on top' toggle.

**Minor observation**
We have 'Sort by filename' and 'Sort by name - …' in the same menu. We should choose either 'name' or 'filename' and stay consistent.

**Comment by hius07** [comment]
Thank you, I like the idea. Will be done as a part of https://github.com/koreader/koreader/pull/10198.

**Comment by hius07** [comment]
Closed by https://github.com/koreader/koreader/pull/10198.
