### ISSUE TITLE
Latest Release 2023.03 misses AppImage binary 

### ISSUE THREAD

**Issue by zephyr** [koreader/koreader#10239]
#### Issue

The last release [2023.01 "Winter Ivy"](https://github.com/koreader/koreader/releases/tag/v2023.01) had 17 assets, including a `koreader-appimage-x86_64-linux-gnu-v2023.01.AppImage`.

But the latest release [2023.03 "Cherry Blossom"](https://github.com/koreader/koreader/releases/tag/v2023.03) has only 16 assets—the file `koreader-appimage-x86_64-linux-gnu-v2023.03.AppImage` is missing.

But the AppImage is still mentioned in [Installation on desktop Linux](https://github.com/koreader/koreader/wiki/Installation-on-desktop-linux), so maybe it was just forgotten to upload?

BWT, thanks for this amazing piece of Software, i use it exclusively on my good old PocketBook Touch Lux 3 and it is fantastic :-).

**Comment by Frenzie** [comment]
Thanks, rectified. I'm not really sure what happened there.

The build is automated and so is the following process that puts it on http://build.koreader.rocks/download/stable/ after every build. The GH upload is not at this time; I basically just do `wget --user-agent=Mozilla --no-directories --accept='*.*' -r -l 1 http://build.koreader.rocks/download/stable/v2023.03` and upload all the files. Perhaps I accidentally didn't select it.
