### ISSUE TITLE
Show print/reference pages in the Reading Statistics.

### ISSUE THREAD

**Issue by ShinxA1** [koreader/koreader#10234]
The Reading Statistics and Book Status use the reflowable page numbers generated by the KOReader renderer as reference to calculate the estimated reading time etc. Would it be possible to implement an option for reading statistics to use the print/reference page to calculate this information?

**Comment by poire-z** [comment]
Why ?
As for calculating estimated reading time, I think you would get the same result, "reflowable pages" should globally linearly map to "print/reference" pages.

**Comment by ShinxA1** [comment]
So the only information that would change would be the pages read/total pages information, would the estimated time remain the same? Oh looking at it that way, it really doesn't make much sense. I think it was a crazy idea. Sorry!
