### ISSUE TITLE
A couple of options more for the Status Bar

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#10231]
I don't know how difficult it would be to implement this or if more people would be interested in but I would find useful to have the following information in the Status Bar:

- Time past since the current session started: While reading I find myself checking constantly how long since I started reading. Maybe it is just a bad habit but I also check constantly the time or how many pages in chapter and it is very handy.

- Number of words per page: I also would find useful to be able to see the number of words per page. That would help when setting a font size to have a page with around 350 words.

In any case, nothing urgent. Just for you to consider it.

Thanks.

**Comment by poire-z** [comment]
Duration of the current session in the footer does not look like it should be complicated (but footer is not my cup of tea, so don't count on me :)

As for number of words, it could be complex and expensive.
At least with PDF. With EPUBs, we could get crengine to count the number of "move by word" actions it has to do, starting at top, reaching to bottom, navigating the nodes' text - but what feels like it's easy for a human, could be complex and could get the engine "stuck" with HTML, tables , floats, when the text nodes linear content could actually be on previous or next pages and come back on current page. So, still costly and expensive. (And words depends on the language/scripts, hard with PDF to get that right - crengine does have a notion of words at least.)
You talked about lines in https://github.com/koreader/koreader/issues/10053#issuecomment-1406417171 _I always try to fit the screen to have 32 lines so it can look more or less like a paperback._ - and OK, I could understand that wish. (But easier for the rare user to count them and make a profile and get done with it, than having us write some code to do that - which also can be complex with edge cases like I mentionned above.)
But 350 words ?! It looks a bit artificial to want pages with 350 words.
It feels we would do you a favor not implementing any of that, and getting you to forget about this strange fixation on number of words and lines :) Just choose a font and size that looks nice and is confortable to read, and stop worrying about numbers :)

**Comment by poire-z** [comment]
But, because KOReader is wonderful with its [user patches](https://github.com/koreader/koreader/wiki/User-patches), and I thought I could have a quick try:

Download [2-footer-count-words.lua.txt](https://github.com/koreader/koreader/files/11023142/2-footer-count-words.lua.txt)
Remove the .txt extension, create koreader/patches/ and put that file in here, and you'll get:

![image](https://user-images.githubusercontent.com/24273478/226468681-e16cec4e-d2ed-45a9-a171-3f344c3a56e0.png)
instead of the "mem usage" info, if you enable it in the menu.
(You can chose another item you are not using instead from that list: https://github.com/koreader/koreader/blob/068809bb936edac2696818fee7a0929d887690ac/frontend/apps/reader/modules/readerfooter.lua#L32-L51.)

Code in that file:
```lua
local ReaderFooter = require("apps/reader/modules/readerfooter")
local Screen = require("device").screen
local logger = require("logger")
local util = require("util")

-- Like util.splitWords(), but not capturing space and punctuations
local splitToWords = function(text)
    local wlist = {}
    for word in util.gsplit(text, "[%s%p]+", false) do
        if util.hasCJKChar(word) then
            for char in util.gsplit(word, "[\192-\255][\128-\191]+", true) do
                table.insert(wlist, char)
            end
        else
            table.insert(wlist, word)
        end
    end
    return wlist
end

-- XXX change "mem_usage" below to any other name you were not using from
-- https://github.com/koreader/koreader/blob/068809bb936edac2696818fee7a0929d887690ac/frontend/apps/reader/modules/readerfooter.lua#L32-L51
ReaderFooter.textGeneratorMap.mem_usage = function(footer)
    if not footer.ui.rolling then
        return "n/a"
    end
    local res = footer.ui.document._document:getTextFromPositions(0, 0, Screen:getWidth(), Screen:getHeight(), false, true)
    -- logger.warn(res.text)
    local nbwords = 0
    if res and res.text then
        local words = splitToWords(res.text)
        -- logger.warn(words)
        nbwords = #words
    end
    return "W: " .. nbwords
end
```

No garantee about its performance or accuracy, but here you got it - enable it when you need it to choose a font - and remove it when you're fine and don't need it.

**Comment by jospalau** [comment]
It works like a charm. You rock matey!

**Comment by mergen3107** [comment]
Wow! Can something similar be done to show number of lines on the page right now? Would save my time when I try to adjust font faces and sizes :D

**Comment by poire-z** [comment]
Sure. Here one single user patch that does the 3 requested things: word count, line count, and current session duration (time elapsed actually, as requested, different from statistics):
[2-footer-line-word-counts-sessionduration.lua.txt](https://github.com/koreader/koreader/files/11024080/2-footer-line-word-counts-sessionduration.lua.txt)

```lua
local ReaderFooter = require("apps/reader/modules/readerfooter")
local Screen = require("device").screen
local datetime = require("datetime")
local logger = require("logger")
local util = require("util")

WORD_SYMBOL = "W:"
WORD_COUNT = "none"
-- Uncomment one of these to have word count replace this item in the footer
-- WORD_COUNT = "page_progress"
-- WORD_COUNT = "pages_left_book"
-- WORD_COUNT = "time"
-- WORD_COUNT = "pages_left"
-- WORD_COUNT = "battery"
-- WORD_COUNT = "percentage"
-- WORD_COUNT = "book_time_to_read"
-- WORD_COUNT = "chapter_time_to_read"
-- WORD_COUNT = "frontlight"
-- WORD_COUNT = "mem_usage"
-- WORD_COUNT = "wifi_status"
-- WORD_COUNT = "book_title"
-- WORD_COUNT = "book_chapter"
-- WORD_COUNT = "bookmark_count"
-- WORD_COUNT = "chapter_progress"
-- WORD_COUNT = "frontlight_warmth"
-- WORD_COUNT = "custom_text"

LINE_SYMBOL = "L:"
LINE_COUNT = "none"
-- Uncomment one of these to have line count replace this item in the footer
-- LINE_COUNT = "page_progress"
-- LINE_COUNT = "pages_left_book"
-- LINE_COUNT = "time"
-- LINE_COUNT = "pages_left"
-- LINE_COUNT = "battery"
-- LINE_COUNT = "percentage"
-- LINE_COUNT = "book_time_to_read"
-- LINE_COUNT = "chapter_time_to_read"
-- LINE_COUNT = "frontlight"
-- LINE_COUNT = "mem_usage"
-- LINE_COUNT = "wifi_status"
-- LINE_COUNT = "book_title"
-- LINE_COUNT = "book_chapter"
-- LINE_COUNT = "bookmark_count"
-- LINE_COUNT = "chapter_progress"
-- LINE_COUNT = "frontlight_warmth"
-- LINE_COUNT = "custom_text"

SESSION_SYMBOL = "S:"
SESSION_DURATION = "none"
-- Uncomment one of these to have session duration replace this item in the footer
-- SESSION_DURATION = "page_progress"
-- SESSION_DURATION = "pages_left_book"
-- SESSION_DURATION = "time"
-- SESSION_DURATION = "pages_left"
-- SESSION_DURATION = "battery"
-- SESSION_DURATION = "percentage"
-- SESSION_DURATION = "book_time_to_read"
-- SESSION_DURATION = "chapter_time_to_read"
-- SESSION_DURATION = "frontlight"
-- SESSION_DURATION = "mem_usage"
-- SESSION_DURATION = "wifi_status"
-- SESSION_DURATION = "book_title"
-- SESSION_DURATION = "book_chapter"
-- SESSION_DURATION = "bookmark_count"
-- SESSION_DURATION = "chapter_progress"
-- SESSION_DURATION = "frontlight_warmth"
-- SESSION_DURATION = "custom_text"


-- Like util.splitWords(), but not capturing space and punctuations
local splitToWords = function(text)
    local wlist = {}
    for word in util.gsplit(text, "[%s%p]+", false) do
        if util.hasCJKChar(word) then
            for char in util.gsplit(word, "[\192-\255][\128-\191]+", true) do
                table.insert(wlist, char)
            end
        else
            table.insert(wlist, word)
        end
    end
    return wlist
end

ReaderFooter.textGeneratorMap[WORD_COUNT] = function(footer)
    if not footer.ui.rolling then
        return "n/a"
    end
    local res = footer.ui.document._document:getTextFromPositions(0, 0, Screen:getWidth(), Screen:getHeight(), false, true)
    -- logger.warn(res.text)
    local nbwords = 0
    if res and res.text then
        local words = splitToWords(res.text)
        -- logger.warn(words)
        nbwords = #words
    end
    return WORD_SYMBOL .. nbwords
end

ReaderFooter.textGeneratorMap[LINE_COUNT] = function(footer)
    if not footer.ui.rolling then
        return "n/a"
    end
    local res = footer.ui.document._document:getTextFromPositions(0, 0, Screen:getWidth(), Screen:getHeight(), false, false)
    local nblines = 0
    if res and res.pos0 and res.pos1 then
        local segments = footer.ui.document:getScreenBoxesFromPositions(res.pos0, res.pos1, true)
        -- logger.warn(segments)
        nblines = #segments
    end
    return LINE_SYMBOL .. nblines
end

ReaderFooter.textGeneratorMap[SESSION_DURATION] = function(footer)
    if not footer.ui.statistics then
        return "n/a"
    end
    local session_started = footer.ui.statistics.start_current_period
    local user_duration_format = G_reader_settings:readSetting("duration_format", "classic")
    -- best to force it to letters, to get '2m' ?
    user_duration_format = "letters"
    local duration = datetime.secondsToClockDuration(user_duration_format, os.time() - session_started, true)
    return SESSION_SYMBOL .. duration
end
```

**Comment by poire-z** [comment]
Word count and line count, given they only work with EPUBs and are not optimized and may be innacurate, are best left to this user patch.
Time elapsed since reading session start could be made a proper footer menu I guess, but well, here it is.

**Comment by mergen3107** [comment]
Thank you so much! Will definitely try it :D 
Epubs only, ok I can just tweak everything in a epub, then go read my fb2 books :D

**Comment by mergen3107** [comment]
@poire-z 
Thank you so much again! Line count works like a charm :) even in fb2!

**Comment by jonnyl2** [comment]
@poire-z: I remember you providing the above user patches and I was quite impressed by them, although I don't really have a use for them myself. However, I was wondering if something similar would be possible to show the average number of characters per line? It wouldn't be necessary to get an average of all lines (to not waste resources), but let's say, count the number of characters (including spaces) of lines 11-15, then show the mean value per line (/5)?

**Comment by jonnyl2** [comment]
@poire-z: In that case, I'd like to get the average nb of chars per line using the entire page. With your patch as a very helpful template I was able to get the line and character count per page into the mem_usage field:

```lua
local ReaderFooter = require("apps/reader/modules/readerfooter")
local Screen = require("device").screen
local util = require("util")

CHAR_COUNT = "mem_usage"

local splitToChars = function(text)
    local clist = util.splitToChars(text)
    return clist
end

ReaderFooter.textGeneratorMap[CHAR_COUNT] = function(footer)
    if not footer.ui.rolling then
        return "n/a"
    end
    
    local res = footer.ui.document._document:getTextFromPositions(0, 0, Screen:getWidth(), Screen:getHeight(), false, true)
    local nbwords = 0
    if res and res.text then
        local chars = splitToChars(res.text)
        nbchars = #chars
    end

    local nblines = 0
    if res and res.pos0 and res.pos1 then
        local segments = footer.ui.document:getScreenBoxesFromPositions(res.pos0, res.pos1, true)
        nblines = #segments
    end
   
    return nblines .. ":" ..  nbchars
end
```

This is working fine; however, instead of `return nblines .. ":" ..  nbchars`, I'd like to do `return nbchars / nblines`, but this is causing the entire reader engine to crash. How come? What's the problem with this?

<details>
  <summary>[!] doShowReader coroutine crashed:</summary>

```
[!] doShowReader coroutine crashed:
frontend/apps/reader/modules/readerfooter.lua:1969: attempt to index local 'text' (a number value)
stack traceback:
	frontend/apps/reader/modules/readerfooter.lua:2103: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:2089: in function 'updateFooterPos'
	frontend/apps/reader/modules/readerfooter.lua:2241: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/apps/reader/modules/readerrolling.lua:1243: in function '_gotoPos'
	frontend/apps/reader/modules/readerrolling.lua:1286: in function '_gotoXPointer'
	frontend/apps/reader/modules/readerrolling.lua:294: in function 'setupXpointer'
	frontend/apps/reader/modules/readerrolling.lua:434: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/apps/reader/readerui.lua:498: in function 'init'
	frontend/ui/widget/widget.lua:46: in function 'new'
	frontend/apps/reader/readerui.lua:686: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:639: in function <frontend/apps/reader/readerui.lua:638>06/15/24-21:26:12 INFO  Restoring user input handling 
```

</details>

**Comment by poire-z** [comment]
Try: `return tostring(nbchars / nblines)`

**Comment by jonnyl2** [comment]
Thank you!!

**Comment by jonnyl2** [comment]
If `mem_usage` is not added to the status bar, this patch will not use any resources – is this correct?

**Comment by poire-z** [comment]
This is correct.
