### ISSUE TITLE
Emulator crashes on Linux

### ISSUE THREAD

**Issue by melvinkcx** [koreader/koreader#10237]
* KOReader version: v2023.03
* Device: Linux

#### Issue

Hi, I'm trying to set up my dev environment, but the emulator quits immediately after starting. Any idea what could cause this? I tried using older images, but the same still occurs. Any help will be much appreciated. 

#### Steps to reproduce

```
git clone https://github.com/koreader/koreader.git
git checkout tags/v2023.03 -b releases/v2023.03
docker run -v $(pwd)/koreader:/home/ko/koreader -it koreader/koappimage:latest bash
cd koreader && ./kodev fetch-thirdparty
```

```
docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd)/koreader:/home/ko/koreader -it koreader/koappimage:latest bash -c "source ~/.bashrc && pushd koreader && ./kodev run --no-build -s=kobo-aura-one"
```

The emulator flashes and quits immediately with a segfault. 

Please see this terminal output:
[crash.log](https://github.com/koreader/koreader/files/11041345/crash.log)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by melvinkcx** [comment]
Apologies, I misread the instructions. The docker image is not supposed to be used to run dev env. Closing it

**Comment by Frenzie** [comment]
Incidentally, which Linux?

**Comment by melvinkcx** [comment]
I'm using PopOS:
```
             /////////////                -@- 
         /////////////////////            ---------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: -
   /////76767//7676767//////////////      Kernel: 6.2.0-76060200-generic 
  /////767676///*76767///////////////     Uptime: 4 days, 16 hours, 50 mins 
 ///////767676///76767.///7676*///////    Packages: 2472 (dpkg), 32 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 2880x1920 
///////////76767676//////7676//////////   DE: GNOME 42.5 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU:-
    /////767676767676767676767/////       GPU: -
      ///////////////////////////         Memory: -
         /////////////////////
             /////////////                                        
                                                                  


```
