### ISSUE TITLE
Changing the font size would not change the content font size

### ISSUE THREAD

**Issue by winstonma** [koreader/koreader#10235]
* KOReader version: 2023.03
* Device: Linux

#### Issue

The font size of this book can't be modified (I tried both Android and Linux version). Not sure how I can get this work.

#### Steps to reproduce

1. Download [Test.zip](https://github.com/koreader/koreader/files/11035669/Test.zip) and rename the file extension to epub
2. Use KOreader to open the Test.epub
3. Change font size
4. The font size of the title is changed but the font size of the content didn't get modified

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by mergen3107** [comment]
That probably means publisher fonts and css rules are used. 
Try disabling them on the bottom menu, rightmost tab.

**Comment by NiLuJe** [comment]
IIRC, there's also a dedicated style tweak for those cases. Should be slightly more chirurgical than the nuclear option of disabling publisher styling altogether ;).

**Comment by winstonma** [comment]
Thanks for the help.
