### ISSUE TITLE
FR: Possibility of adding multiple actions of the same kind to QuickMenu

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10249]
I very much enjoy the new QuickMenu feature and have set one up via long tap from all 4 corners of the screen. I use all 4 QuickMenus regularly.

However, what would make the feature even better would be the possibility to add multiple actions of the same kind to a QuickMenu. Most notably, this feature would make choosing some pre-selected brightness/warmth settings or fonts/font sizes a breeze.

For example, one could set up a QuickMenu for font size: 8; 10; 11; 11.5; 12; 14; 16. etc... or one for font name, where one could add the 5-10 most used fonts. And one for brightness/warmth: 3%/3%; 3%/10%; 10%/10%; 10%/20%; 20%/10%; 30%;0%.. etc.  Or instead of preselected brightness/warmth settings, just set up a QuickMenu to increase/decrease it by a certain amount, e.g. -20; -10; -5; -4; -3; -2; -1, 1; 2; 3; 4; 5; 10; 20, etc.

It would also be useful to quickly select a number of pages to turn: e.g. -20; -10; -5; 5; 10; 20. etc. 
Or use it to change to one of a few preselected zoom factors. And so on. 

I am aware that for some of these, like setting a certain brightness, I could set up separate profiles. However, the amount of different profiles needed if I also wanted to set them up with different fonts or font sizes etc. would quickly become unmanageable.

Is this something that would be feasible to implement?

Thank you for reading and btw, the latest 2023.03 release is fantastic. KOReader just keeps getting better and better.

**Comment by hius07** [comment]
I am not sure I understand correctly. Can you describe the dialogs you'd like to see when creating a new profile with desirable actions.
You are no doubt aware that profiles can call the nested profiles, and the nested profiles can contain any number of actions or subnested profiles (there is no check for infinite loops).

**Comment by jonnyl2** [comment]
Thanks @hius07; I hadn't considered creating profiles for just single actions. Also, the duplicate profile feature makes this very convenient. So I am closing this issue.

**Comment by hius07** [comment]
Okay, thanks for the feedback.
