### ISSUE TITLE
[Question] Koreader supports (specifically named/organized) zip files. Has anyone figured out the easiest way to batch zip ebooks in that way?

### ISSUE THREAD

**Issue by AnatolyIliev** [koreader/koreader#10252]
Koreader supports viewing zip files, as long as they're named like "file.epub.zip" and the zip contains just the book itself. 

This has the potential to save a lot of space, but manually zipping and renaming hundreds of ebooks is an absurd undertaking, so how can you easily automate it across all selected folders and subfolders (ideally with something as easy as context menu option)? 

Command line solutions (e.g. 7-zip) I've seen don't seem to do what is needed here - namely, compress individual files (not individual subfolders) and append *.zip to the extension (so that it looks like "file.epub.zip" instead of "file.zip"). 

Has anyone figured this out?

**Comment by poire-z** [comment]
(Just for info: an epub is already a zip file - so zipping an epub won't gain you much space, and may need more power/memory when you actually read it. But for other formats like fb2, txt, html, it may.)

**Comment by NiLuJe** [comment]
PDFs are *also* a compressed format (osrta, it's more complicated than a simple container compression, but, still), FWIW ;o).

**Comment by Frenzie** [comment]
You can stick something like uncompressed TIFF in PDF but yeah, I would imagine that there's rarely much gained from doing anything to PDF, and a whole lot of CPU cycles wasted.

**Comment by iFUCKINGHATEcomputers** [comment]
ChatGPT avails. A batch script:

```
setlocal enabledelayedexpansion

for /r %%F in (*.txt) do (
  set "filename=%%~nF"
  set "extension=%%~xF"
  set "newname=!filename!!extension!.zip"
  "C:\Program Files\7-Zip\7z.exe" a -tzip "%%~dpnF.zip" "%%F"
  ren "%%~dpnF.zip" "!newname!"
)

endlocal`
```
