### ISSUE TITLE
FR: Exclude index, bibliography pages, etc. from reading statistics

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10253]
Many non-fiction books have several dozens of pages of bibliography, indexes, notes, etc. at the end that are not meant to be read page by page. As a result, a book may be read to the end but the reading progress says that only 80% has been read. It also skews with the information on estimated time to finish the book, and makes the number of pages to finish unreliable. 

Let's consider the following generic book structure:

Page no; Contents

1; Cover page
2-4; Copyright, dedication
5-6; ToC
7-8; Acknowledgments
9-11; Preface
12-13; Foreword
14-17; Introduction
18-159; Chapters 1-9
160-165; Conclusion
166-180; Appendix
181-195; Notes and Bibliography
196-199; Index
200-202; Empty pages and back cover

Now if you're at say page 140, it'll say you you're at 69% (140/202) and still have 62 pages to read until finished (and it will measure the remaining time estimate based on 62 pages), even though page 165 will be the last page you read. (Or page 180, if the Appendix is read-worthy, which will depend on the book and the reader.)

I have thought of 2 potential solutions to this issue; one simpler and one slightly more complex one:
__
**Suggestion 1:**

The user can manually set the final page to read in the book. This would depend on preference, but in the given example most likely be either 165 or 180 (I'll pick 165 now).

On page 140, reading progress will say 140/165 (85%), and 15 pages left to read.
Time spent on pages 166+ will not count toward read pages and be disregarded by statistics.
If you're on, say, page 190, reading progress could say 190/165 (115%) or just stay at 100% (which might make more sense to some users). No. of pages left to read will say 0.

**Suggestion 2:**

User can specify a **range** of pages to be read in the book, e.g. [9-165]. The advantage would be that one could also exclude title pages, ToC, and other immaterial pages that skew reading statistics. Again, only pages within the specified range would be considered for the reading statistics and any time spent on pages outside that range would not be counted. 

In the status bar, the actual page number would be shown (e.g. 5 / 202), but the reading progress would only start at page 9 (so 0%). While on page 30, page no. would show as 30 / 202, but progress would show as 13% (21/156), and so on.

While this solution would be a bit more elegant, it would probably take more work and the pages to exclude at the beginning are usually much fewer than the ones at the end of a book. Also, once they are skipped, they don't skew the number of pages and time remaining to read anymore.
__

I'd be interested to know your opinion on this suggestion. This is by no means anything I'd consider essential; just an idea I wanted to share. Thanks for reading.

**Comment by poire-z** [comment]
It's been discussed on a few issues, ie. #8265, mostly related to footer and page progress - I don't remember if we evert thought about the need to handle that also in statistics, which is obviously related, but possibly even more tedious.
We have a feature that works with EPUBs that advertize sections of the book as "non-linear" (ie. excluding footnotes) so they are not accounted in the linear reading flow, and can be excluded from page progress/count: #6809 #6847. (We also support that in the Wikipedia EPUBs KOReader generates, where the footnotes section at end are tagged as non-linear, and appear gray in the Book map.)
My idea is that if we were to support that kind of thing in other book formats, or with EPUBs that don't provide that, we should use the existing infrastructure and allow the user to set one or many parts of the book as "non-linear" - setting only where the book ends would be one particular use case for this.
(See also https://github.com/koreader/koreader/issues/10209#issuecomment-1469907243 and https://github.com/koreader/koreader/pull/10230#issuecomment-1476810313 for a non-implemented but possible UX solution to tagging sections of the book.)

**Comment by jonnyl2** [comment]
Thank you. It probably doesn't make sense to keep this open as an extra case then as the issue is already being addressed via other avenues.
