### ISSUE TITLE
koreader cannot see a specific folder in the root folder(/onboard)

### ISSUE THREAD

**Issue by windirt** [koreader/koreader#10251]
* KOReader version:2023.03
* Device: Kobo Libra2  4.35.20400

#### Issue

I installed koreader 2023.03 fresh and started it with nickelmenu, then I found that in the file manager, I couldn't see my `kepub` folder.

![ba304d56724258e501717624a6cdacff](https://user-images.githubusercontent.com/6456747/227905958-6a4e452e-c4f9-4070-aec0-65cbf3a85f96.jpg)

the `kepub` folder is not a hidden folder, Although I also checked the Show hidden files and folders in the file manager settings.

![f44045e4fa388a2cccfdf26099d240db](https://user-images.githubusercontent.com/6456747/227906469-27ae508b-c0f3-4806-8448-ff5b3c7e47d8.png)

In the file manager, the onboard folder shows only three folders, which is not what I was expecting.

![6e5087f14cc180d71ccaa7bed68899d4](https://user-images.githubusercontent.com/6456747/227906657-7f9fe50b-4981-4459-b574-77dec7e2de1f.jpg)

I checked the file attributes and permissions on the disk in the terminal and they are normal.

![105500c984c6150232daf5db88005d58](https://user-images.githubusercontent.com/6456747/227907547-88c1250a-301a-426e-a674-5f58b1cae298.png)

rebooted device and restarted koreader, but no help.

The kepub files with epub extension in the `kepub` folder can be viewed in the Nickel properly.

**Comment by Frenzie** [comment]
That's on purpose. As for the rationale you'll have to ask @NiLuJe 

https://github.com/koreader/koreader/blob/d2ed7402da7a8920704701a7094cb060f6a5dc31/frontend/ui/widget/filechooser.lua#L27-L55

**Comment by windirt** [comment]
thanks for the fast response.

**Comment by NiLuJe** [comment]
That's because that folder only contains direct-from-the-store Kobo ePub files, and those have an extremely high chance of being DRM protected, so we wouldn't be able to do anything with them anyway.

Theit filenames also happen to be UUIDs, which would make them extremely unfriendly to the filemanager, which is another strike against even attempting to display it ;).

**Comment by jeff47** [comment]
> (If you're actually putting your own stuff in there: you're doing it wrong ;p).
> 

Just as a minor point, and maybe this is a rare use case, but some people (me included) have changed the Kobo store url to match our Calibre-Web address so that we can easily sync and load books.  So that's a case where that directory contains user-loaded content that is DRM free.  Plato, at least, displays all of these using the correct title and author, which it must be reading from the metadata?

**Comment by NiLuJe** [comment]
I never checked whether we have sane mime mappings for those, precisely because they're blacklisted by default anyway ;).

But, technically, nothing should prevent anyone from parsing/reading those, it's just a a bastardized ePub 2 w/ extra spans and a few ePub 3 features thrown in.

**Comment by jeff47** [comment]
I copied one from the .kobo tree to the root folder and added the .epub extension and it looks fine.  Would be nice to have an option to include the native folder, even if it's disabled by default.

**Comment by NiLuJe** [comment]
***koreader/patches/2-dont-hide-kepub-folder.lua***

```lua
-- NOTE: Still requires "Show hidden files" to be enabled to actually access .kobo (unless you favorite it).
-- NOTE: And also still requires "Show unsupported files" to display the native UUID filenames.
local FileChooser = require("ui/widget/filechooser")

local shift
for k, v in ipairs(FileChooser.exclude_dirs) do
    if v == "^kepub$" then
        shift = true
    end
    -- I sure wish we had a table.move in the standard library...
    if shift then
        local next = FileChooser.exclude_dirs[k+1]
        if next then
            FileChooser.exclude_dirs[k] = next
        else
            FileChooser.exclude_dirs[k] = nil
        end
    end
end
```

I have no idea how much sense it makes given all the constraints, but there you have it.

**Comment by jeff47** [comment]
Yeah, I think they are extensionless.  However, maybe this is unnecessary anyway.  Doing this via Calibre-Web and native sync was convenient, but is probably unneeded if you've got OPDS.

**Comment by OGKevin** [comment]
(sorry for the necropost)

In case anyone new stumbles on this there is: [kobo.koplugin](https://ogkevin.github.io/kobo.koplugin/scenarios/komga-calibre.html) that addresses the kobo store url change use-case.
