### ISSUE TITLE
FR: Adding a "myClippings" format to export your highlights

### ISSUE THREAD

**Issue by Mochitto** [koreader/koreader#10262]
**Does your feature request involve difficulty completing a task? Please describe.**
I think it would be nice to have one of the exporting options mimic that of Kindle devices, so that other software that parses "myClippings" can reference the exported file to get the highlights information.

**Describe the solution you'd like**
Adding a "myClippings" option to the exporting menu, along "text", "markdown" etc.

**Describe alternatives you've considered**
Another possibility could be having the option of changing the template used when formatting the files.

**Additional context**
This feature would, indirectly, allow for Obsidian support when exporting your highlights: https://github.com/hadynz/obsidian-kindle-plugin

**Comment by hius07** [comment]
Also: https://github.com/koreader/koreader/issues/9592

**Comment by zenminimalist** [comment]
I would also love this feature as I use Obsidian as well.
