### ISSUE TITLE
FR: [accessible auto rotate lock]

### ISSUE THREAD

**Issue by xIUPITERx** [koreader/koreader#10268]
**Does your feature request involve difficulty completing a task? Please describe.**
Thanks to #9873 we now have support for the G-Sensor, but it's a little to responsive. 
it would be nice if the function to deactivate rotation could be reached quickly and without having to go through many submenus.

**Describe the solution you'd like**
In my opinion, it is rather impractical to hide the function under screen-settings when there is already a category rotation in the bottom menu where one could introduce a small lock symbol to switch auto-rotation on or off. 

**Describe alternatives you've considered**

**Additional context**

**Comment by offset-torque** [comment]
You can assign "Toggle accelerometer" setting to any gesture or add it to a **QuickMenu**. 
This will disable/enable the sensor based rotation. I am currently using this setting in my QuickMenu and it is one tap away.

**Comment by NiLuJe** [comment]
> In my opinion, it is rather impractical to hide the function under screen-settings when there is already a category rotation in the bottom menu where one could introduce a small lock symbol to switch auto-rotation on or off.

The bottom menu predates any and all kind of gsensors being seen on eInk devices (and is there regardless of the presence of a gyro) ;o).

I'm not quite sure we could finagle an extra toggle in there (and/or if it even makes sense), but I kinda see your point; will try to look at it.

**Comment by pazos** [comment]
Yup. Gestures or quick menu is the way to go.
