### ISSUE TITLE
FR: Add number of pages by chapter/section in Table of Contents

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10261]
It would be helpful if the ToC would show at a glance the number of pages each chapter/section contains.

Especially for books that don't have to be read linearly (e.g., non-fiction), or documents that contain a whole collection of books in one file, it would be convenient to be able to choose a chapter/section/book of a certain size without having to look over to the right edge at the page numbers and mentally calculate the number of pages the sections contain. 

I have attached a screenshot of ToC page with manual edits of what I had in mind. Chapters and collapsed sections would just show the number of pages in parentheses, right next to the chapter/section name. Once a section is expanded, it would also show the page numbers of the additional level(s) of the ToC. (**Note**: In the edit I began with the number of pages of the lowest level but looking at it again it might make more sense to list them in a descending order, e.g. (116/3/0); (20/0).

![KOR-ToC-Section pages](https://user-images.githubusercontent.com/95502269/228352188-0478967c-1d6f-46ff-83ee-11c986cb51f6.png)

As for the style, I was thinking of the same font and size as the ToC, or slightly smaller. But this could be up for discussion.

Thank you.

**Comment by offset-torque** [comment]
**+1**
There were a few times I wished KOReader had this feature.
Although in my case I just needed the main chapter lengths, not the whole tree.

**Comment by jonnyl2** [comment]
Came up with a new design idea, simplified and not interfering with the overall polished look of the ToC (imho). Uses only the available left margin space and displays only one level of the page count: when collapsed the sum of all lower level pages, and when expanded (or not nested at all) the chapter page count:

![Reader_2023-04-26_170428](https://user-images.githubusercontent.com/95502269/234626574-7b723a65-c5ad-44ca-9106-b290b330b204.png)

Curious if you have any feedback perhaps, @poire-z?

**Comment by poire-z** [comment]
> Curious if you have any feedback perhaps, @poire-z?

Your non-artificial custom-made-personal-software personal assistant has none [monthy focusing bandwidth credit exceeded]. :)

I like our ToC as it is, and not keen on looking again at its code :/ (at least, for now).
When I feel the need for getting the length of a chapter, I would look at bookmap, I guess I don't need a precise number.
It would also need to be an option, so a top left icon and a menu.

There are various other layout possibilities than the sample you gave, that could get in the way of it looking nice:
The key shortcut for devices with a keyboard, getting in the way:
![image](https://user-images.githubusercontent.com/24273478/234657707-89355737-db6c-43f5-a54d-abe82708b2f0.png)

No expand/collapse icons, so the title really near the margin and your numbers:
![image](https://user-images.githubusercontent.com/24273478/234657585-9f816285-ac5b-49c0-85c4-7300e056e986.png)

If you end up being fine with a single number, I guess it make more sense to have it on the right, with the page number, so one can infer lengths and do page numbers arithmetic more easily.
`Act V ....... (15)   2804`

**Comment by poire-z** [comment]
Or your vertical numbers in the right margin.
When looking at the ToC, I mostly read the titles and rarely care about moving my eyes to the numbers on the right, so any noise added on this side won't bother left-side readers.

Also, ReaderToC, based on the commonly used Menu object, is a lot less flexible and less dynamic (dynamism needed with your changing numbers are you expand/collapse) than the dedicated BookMap/PageBrowser - so probably harder and less fun to implement in there.

**Comment by jonnyl2** [comment]
>Your non-artificial custom-made-personal-software personal assistant has none [monthy focusing bandwidth credit exceeded]. :)

:-D 

>I like our ToC as it is, and not keen on looking again at its code :/ (at least, for now)

I didn't mean to rush anything. I just like to throw it out there.

>When I feel the need for getting the length of a chapter, I would look at bookmap, I guess I don't need a precise number.
It would also need to be an option, so a top left icon and a menu

The bookmap is great to get an overall feel for the lengths of the chapters, but less so when you want to read the chapter titles one by one and pick one out of order based on chapter name _and_ length. 

>If you end up being fine with a single number, I guess it make more sense to have it on the right, with the page number, so one can infer lengths and do page numbers arithmetic more easily.
>`Act V ....... (15)   2804`

One number is definitely enough, but this might just make the page numbers on the right too "noisy". Also, it defeats the purpose of not having to glance over to the right when going through chapter titles. (Same for using the right margin.)

If the lengths can be toggled on/off (so they won't bother anyone), then I think this would be more useful:

`Act V (15) .......   2804`

Besides toggling chapter/section lengths, a menu could also be used for helpful features like expand/collapse all; expand/collapse 1 level, etc...

But again, none of this is anything pressing or even really necessary, so we can also put the issue at rest for now. 

Thanks

**Comment by jonnyl2** [comment]
@poire-z, I'd like to do a personal patch that shows me the current location in the current (bolded) chapter in the form of ([location in chapter]/[total chapter pages]). E.g., like this

Chapter 1 (10) ..... 20
**Chapter 2 (5/15) .... 30**
Chapter 3 (12) .... 45

Is there a simple and obvious (to you) way to do this? (I'm not asking for a finished user patch, just trying to understand what needs to be changed. Can't really wrap my head around `readertoc.lua`. If it requires multiple lines, don't worry about it.)

Bonus question: is there method to check whether a given chapter title is truncated? Something like `item.text:isTruncated()`? (This doesn't work.)

Finally, I noticed that if the first chapter of a ToC starts at say page 25, if you are on page 1-24 it will still show the first chapter bolded. This seems like a bug to me? It shouldn't show anything as bold if the location doesn't exist in the TOC. 

Thanks as always for your help and for adding this original FR. It's very useful and I see myself using the TOC a lot more now.

**Comment by poire-z** [comment]
> Is there a simple and obvious (to you) way to do this?

Nothing obvious has all this is buried in the middle of a big function.
But by change, we can hack around :)
```lua
local ReaderToc = require("apps/reader/modules/readertoc")
local T = require("ffi/util").template

local orig_ReaderToc_completeTocWithChapterLengths = ReaderToc.completeTocWithChapterLengths
ReaderToc.completeTocWithChapterLengths = function(self)
    orig_ReaderToc_completeTocWithChapterLengths(self)
    for k, v in ipairs(self.toc) do
        -- Hack this so we can dynamically update post_text when the item is shown
        -- (fortunately, in menu.lua, text_func is called before post_text is used)
        v.text_func = function()
            if not v.orig_post_text then
                v.orig_post_text = v.post_text
            end
            if self.pageno >= v.page and self.pageno  < v.page + v.chapter_length then
                v.post_text = T("(%1/%2)", self.pageno - v.page + 1, v.chapter_length)
            end
            return v.text
        end
    end
end
```
(It will also od it for non-bold parent ToC items - but I figure that's as good, so you know how far you are in the bigger picture.)



> Bonus question: is there method to check whether a given chapter title is truncated? Something like `item.text:isTruncated()`? (This doesn't work.)

item.text is the text string. Only the TextWidget rendering it knows it's truncated. But it is hard to reach and not referenced easily. You'd need to follow how Menu and its Menu item is setup, and you could reach it with something like `self.toc_menu[1][2][1][2][indexOfTheItem][1][2]:isTruncated()` (random indices here)...

> Finally, I noticed that if the first chapter of a ToC starts at say page 25, if you are on page 1-24 it will still show the first chapter bolded. This seems like a bug to me? It shouldn't show anything as bold if the location doesn't exist in the TOC.

Maybe, it feels this has been discussed in the past and there may be an issue somewhere (possibly created by you :)) where I may have say why it was somehow tricky.

**Comment by jonnyl2** [comment]
Thank you very much! That's more than I asked for but I probably wouldn't have been able to solve that. 

>(It will also od it for non-bold parent ToC items - but I figure that's as good, so you know how far you are in the bigger picture.)

Yes, that's perfect!

**Comment by poire-z** [comment]
Corrected the code (previous `6/34` were sticking when you moved to another chapter), and my typos.
