### ISSUE TITLE
FR: Manually saving current document metadata

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10277]
**Does your feature request involve difficulty completing a task? Please describe.**

It occasionally happens that KOReader crashes after having made some adjustments to the book layout, font/size, etc. or having added notes or bookmarks. The changes effected after the last periodic automatic saving as well as the reading statistics for the pages read afterwards are then lost.
For peace of mind, it would be nice to be able to quickly save the settings after having made some document changes via a gesture or QuickMenu.

**Describe the solution you'd like**

Add a function in the menu:
Document-> Document settings -> `Save current document settings` or `Save current document metadata`
For easy access, this function should also be available to call via gesture/profile.

**Additional context**

Current workarounds are to manually exit KOReader and restart it, or to suspend the device and wake it. These work fine but (depending on device) can take up to several seconds and are not very satisfying. In addition, the current reading session time resets to 0. 
Decreasing the timespan of automatic saving from the default 15 min is not an option I'd consider an alternative as I'd only want the extra saves after having made some document adjustments or have added bookmarks that are tedious to redo. Also, certain books (usually scanned PDFs or ePubs over 10 MB) are more prone to crashing than simple and clean documents.

**Comment by Frenzie** [comment]
> Current workarounds are to manually exit KOReader and restart it, or to suspend the device and wake it. These work fine but (depending on device) can take up to several seconds and are not very satisfying. In addition, the current reading session time resets to 0.

The best way to perform that workaround is to go to the filebrowser and then to reopen the file. I don't think the alternative you propose is likely to be much faster, while the other methods you describe add many additional seconds.

**Comment by jonnyl2** [comment]
Thanks for the input. Not sure how the filebrowser would be a better or faster workaround having to look for the file. Also, it still resets the current reading progress. 
Seconds used for saving the document in the background don't affect the user experience, so I'm not sure how one compares to the other.

**Comment by poire-z** [comment]
> It occasionally happens that KOReader crashes after having made some adjustments to the book layout, font/size, etc. or having added notes or bookmarks. 

Can't reproduce ! :)

Unless you have one of the newer Kobo that are known to crashs (but there are workarounds, like disabling notifications), or a Kindle with limited memory, you could provide the crash.log or the books if this is reproducible. We'd rather fix that than providing tools to hide the fact our software is crap :)

> after having made some adjustments to the book layout, font/size

Since a few weeks ago and partial rendering, there is a seamless document reload (without session lost) soon after such adjustments, so the settings are saved then.

> or having added notes or bookmarks

We could have an additional `Save book metadata> [x] Force save when bookmarks/highlight added/edited/removed`.

**Comment by Frenzie** [comment]
@jonnyl2 
> Thanks for the input. Not sure how the filebrowser would be a better or faster workaround as it involves several steps. Also, it still resets the current reading progress.
Seconds used for saving the document in the background don't affect the user experience, so I'm not sure how one compares to the other.

An equivalent alternative would be to switch between two files. Either way, it would take a split second and it's not comparable to the many seconds involved in restarting the program or suspending the device.

`Document-> Document settings -> Save current document settings` also means 4 steps. In that sense it's identical. With gestures it'd be down to one step vs two, so there's that. ;-)

I'm mostly just saying you could improve the workaround you're using right now.

@poire-z 
I think adding a manual "save now" action could also make sense for peace of mind even if it doesn't make sense from a technical perspective. Though on the flip side, it might suggest this is something people should be doing which really isn't the case. :-/ As such providing more "save here" options might indeed be better.

**Comment by jonnyl2** [comment]
>Since a few weeks ago and partial rendering, there is a seamless document reload (without session lost) soon after such adjustments, so the settings are saved then.

@poire-z That's a good point; this certainly solves the issue when it comes to changing layouts on reflowable docs.

@Frenzie Thanks, I appreciate the advice. I've set up a gesture for `Open previous document` so using this gesture twice I can quickly use this as a workaround. (Only potential issue is that if the previous document is some 100 MB PDF file, it won't be as quick, but that should be rare. And the reading progress for the document is still being reset, but that's a minor thing.)

The use case I am mostly concerned about (although I sometimes also make adjustments in the middle of reading) is that when I first open a new PDF file that has no meta-ToC, I first go through the document and add bookmarks to the ToC-page(s), and all pages marking the beginning of a new chapter. This is usually 10-20 bookmarks. Then I adjust the screen layout and graphics (margins, view mode, contrast, dewatermark etc.). This is often where the crashes happen, forcing me to redo the bookmarks. 

(Unfortunately I don't have a current case on hand. I have been using KOReader on various devices for about 2 years. I will gladly submit a crash report next time this happens.)

So if the document settings are saved after each bookmark, this would mean about 10-20 savings in the span of minutes. I don't know how resource intensive that would be, but it doesn't seem very efficient to me.

**Comment by Frenzie** [comment]
In theory merely adding an additional bookmark could be fairly light, but unfortunately in actual practice right now that'd be quite heavy.

Which device are you on? Dewatermark and such can be fairly intense but on my 2014 H2O (with a quite reasonable 512 MB RAM) I've only ever noticed that in the form of some slowness.

Though I'll add that what you're describing sounds like you may be able to do it much faster in k2pdfopt for desktop, before putting it on the device. https://www.willus.com/k2pdfopt/ It's the same library that we also expose to a slightly more limited extent in KOReader, where it's workable because we only operate on a page by page basis.

I suspect you might be on a semi-recent Kindle? Those would be much faster in CPU but severely constrained in RAM.

**Comment by jonnyl2** [comment]
@Frenzie K2pdfopt is an amazing tool and I have used it extensively, but only for small devices that lack KOReader support, such as an old Sony and an older Onyx clone. Nothing beats the usability and versatility of loading the raw file directly into KOReader and adjusting the viewing options directly from within. Fortunately, crashes are relatively rare and seemed to have only gotten rarer with each subsequent release. I am currently using a Kobo Aura One and an Onyx Boox Nova 3, previously Likebook Mars (Android 8) and Tolino Epos (Android 4.4).

**Comment by Frenzie** [comment]
A Kobo Aura One will have slightly higher memory pressure due to the larger resolution screen, but I shouldn't think it'd be enough to matter. Strange.

**Comment by jonnyl2** [comment]
As an idea, would you consider releasing a user patch for this issue? I think it'd be a nice optional feature to have. Not sure if gestures can be assigned within user patches; if not, just an extra menu item `Book -> Save current settings` would also be okay.

**Comment by poire-z** [comment]
No, too many little things involved for a user patch.
But it looks like it's easy for us to add it - the event handler is already there:
```diff
--- a/frontend/dispatcher.lua
+++ b/frontend/dispatcher.lua
@@ -113,2 +113,3 @@ local settingsList = {
     -- reader settings
+    flush_settings = {category="none", event="FlushSettings", title=_("Save book metadata"), reader=true},
     open_next_document_in_folder = {category="none", event="OpenNextDocumentInFolder", title=_("Open next document in folder"), reader=true, separator=true},
@@ -293,2 +294,3 @@ local dispatcher_menu_order = {
     -- reader
+    "flush_settings",
     "open_next_document_in_folder",
```
We just need to decide where in the Reader> menu to place it (the above places it first in the list, no obvious other separator'ed related section in my eyes).
