### ISSUE TITLE
KOReader can't see kindle books on Android device

### ISSUE THREAD

**Issue by Phoenicia15** [koreader/koreader#10272]
Hey Y'all. I just installed KOReader on my android tablet (Samsung Galaxy Tab S6 Lite, running Android 13). But KOReader can't import or even see any of my Kindle e-books that are stored on my device. 

I know the books are there. There in the Android>data>com.amazon.kindle>files folder, with more individual subfolders each containing the various ebooks (it looks like something called a ".ticr" file extension). But when I open KO Reader, it can't see the com.amazon.kindle folder at all. 

And when I tried copying the subfolders from com.amazon.kindle into a new folder, KO Reader can see the new folder, and the subfolders, but can't see any of the .ticr or other files inside the subfolders. 

What should I do?

**Comment by Frenzie** [comment]
If you´d like to read them in something that isn´t Kindle, your best bet is probably calibre.

**Comment by NiLuJe** [comment]
They're also quite likey DRM-protected, so even if you had access to them, we couldn't actually *do* anything with them.

**Comment by pazos** [comment]
Even if the files were not DRMed we cannot use them, as they belong to other app's private storage. It is a restriction that applies to every application in Android11+ 

See https://developer.android.com/about/versions/11/privacy/storage#other-private-dirs
