### ISSUE TITLE
FR: Page turns while touch input is disabled on ereaders lacking physical buttons

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10273]
**Does your feature request involve difficulty completing a task? Please describe.**

Disabling touch input is very useful for reading while using a finger to track the text (e.g., for speed reading or for reading very tiny text so a lot of text can fit on one screen). However, it makes it impossible to turn pages on ereaders without physical buttons. Some ereaders have at least one physical button (e.g., back or home button), which can be defined as a page turn button, which solves this problem. On ereaders without any buttons (besides power) however, one needs to gesture to enable touch input again, turn page, then toggle touch input off again. 

**Describe the solution you'd like**

Personally I'd like to be able to optionally exclude the 4 corner areas from the `disable touch input` feature. I've defined the corners as using just 3-5% of the screen length/width so accidental touches wouldn't be a problem. Using existing functionality, corner gestures can be set up to turn pages, call QuickMenus etc. 

**Describe alternatives you've considered**

If all four corners are considered too much, to exclude just one or two corners (e.g., bottom right or bottom left and right) would also solve the main issue.

Alternatively, being able to define just two special gestures that only take effect when touch input is disabled. For example, two-finger swipe gestures to left and right. (A drawback would be that this could again be prone to accidental page turns; also, it could get confusing if the same gestures are already defined for a different function while touch input is enabled.)

Another option I was thinking of is that each user-defined gesture could have a tickbox `allow while touch input is disabled` so any gesture could optionally be excluded and used for page turns or to call a QuickMenu etc.

**Comment by NiLuJe** [comment]
They all incur a much higher technical cost, which is why this isn't implemented differently.

**Comment by luutuankiet** [comment]
hey @jonnyl2 I have the same thought, chiming in with a workaround to this : you can set a gesture to trigger 2 actions, one to toggle touch input and the other to page turn; this is possible since in touch disabled mode the only trigger koreader expects is another touch toggle so you're kinda piggybacking that to make a page turn possible while touch disabled.

only caveat is you'd need to set another gesture to toggle touch input back to disabled whenever you execute a page turn gesture this way - I've set mine to a diagonal short swipe. In the end it should cost one less gesture to toggle touch on, then page turn, then toggle touch off.

perhaps a FR to have dedicated touch OFF and touch ON? @NiLuJe

**Comment by jonnyl2** [comment]
@luutuankiet I thought of this workaround and also had set it up for a while but it wasn't very practical. Having to do two separate gestures/taps really distracted from the reading experience and the constant notifications (`Disabled touch input`/`Restored touch input`) were also a bit irritating. (I know you could turn them off but then you're never sure if the tap/gesture was accepted and I wouldn't want to suppress any other notifications either.) 

Thanks for reaching out though.

**Comment by luutuankiet** [comment]
@jonnyl2 thanks to your tip that I can turn of gesture's notifications i came up with another (dirty) solution : create a profile that triggers a touch input toggle, then append this as another action to the aforementioned multi action gesture:
1. toggle touch input 
2. launch profile that toggles another touch input
3. page turn

So in the end, given that touch input is OFF, I can achieve one gesture swipe to page turn while keeping touch input OFF.

**Comment by luutuankiet** [comment]
bummer, worked on android boox poke device.
