### ISSUE TITLE
ireader Smart XS can't use touching function

### ISSUE THREAD

**Issue by superliujian** [koreader/koreader#10293]
* KOReader version: 2023.03
* Device: iReader Smart XS (maybe all the iReader devices after googled) 

#### Issue
It's the same issue of #9154 , but I could help to provide the debug info.
1. When in the File Browser page, I could touch "Home" button and "+" button"  on the top corner of the screen.  But for the other actions: like tap to show menu, swipe to next/previous page,  nothing happens. 
2. When in the read page,  the same problem even I cannot do any "Touch" things. Touch is not working.   no tap to show menu, no swipe to show menu, no way to navigate pages, highlight .etc. 
After googled, this is a known issue looks like all the "iReader" devices have the same problems.

PS: when I first open the koreader, it pops up message to show " this device will use color display to show the device, if your device support gray display , you could disable "color display"  in "Screen" menu item" (I translate from Chinese by myself, maybe not accureate, but from the setting file should be color_rendering = false) , so maybe the device is recognized as a normal Android device not e-ink device? 

#### Steps to reproduce
1.Just install on iReader device, no special steps are required. 

I'm ready to do any debug with you (I'm a developer too although not so skilled in Android), but one challenge is there is no way to "enable USB debugging" in this device.

**Comment by pazos** [comment]
Hi.

Unfortunately we don't have the time, nor the hardware or resources to assist with every android eink device that behaves badly.

Instead we have a standalone ticket for everything android eink related: https://github.com/koreader/koreader/issues/8482

In the specific case of your device/issue, please reuse the ticket you've linked. That contains a potential workaround (enabling wakelocks) and the instructions to get logs.

I saw your post there but no new info: did you try the workaround? did you got logs? so I didn't comment as there's nothing to comment :p 

This one is a duplicate. Please don't open duplicates :)

Duplicate of #9154

**Comment by plateaukao** [comment]
Fixed in my fork, and binary is here: https://github.com/plateaukao/koreader/releases/tag/ireader-v2026.07

**Comment by tempestnano** [comment]
> Fixed in my fork, and binary is here: https://github.com/plateaukao/koreader/releases/tag/ireader-v2026.07

Are you planning to PR this into main? I am about to embark on toying with Musnap/iReader touch/stylus interactions, and I don't want to collide with your fix.

**Comment by plateaukao** [comment]
@tempestnano 
No, it's hard to send PR into main, since I make that fork support so many other devices with stylus drawing too, and touch not only koreader base repo, but also other related repositories.
