### ISSUE TITLE
[Kindle 4/NT] How to remove home and "+" buttons from top of file chooser? They result in a lot of needless clicking

### ISSUE THREAD

**Issue by AnatolyIliev** [koreader/koreader#10301]
Older versions of Koreader didn't have those two buttons - when I opened a new directory, or switched to the next/previous page of my current directory, I could press the down key and start selecting files right away. Now with those buttons on top, I have to click three times until I reach down to the file chooser - every time.

This also happens if I click the up key (to start selecting files from the bottom) - instead then it takes 4 clicks for some reason.

If there's some bit of code I could delete to just get rid of them, that would be great.

**Comment by AnatolyIliev** [comment]
Let's make this easier:
[https://i.imgur.com/pkyRL3I.png](url)
What is this bar called? I'll ctrl+F it and find the file myself.

**Comment by NiLuJe** [comment]
Sidebar: Unless I'm thinking of something else, that must have been some *really* old version, because those two have been there for approximately forever (in one form or another, at least) ;).

**Comment by poire-z** [comment]
You could also help yourself with a [user patch](https://github.com/koreader/koreader/wiki/User-patches), ie. `2-menu-no-titlebars-focus.lua`
```lua
local Menu = require("ui/widget/menu")
Menu.mergeTitleBarIntoLayout = function(self)
    -- Do nothing.
    -- Or you could copy/paste the logic and rewrite it a bit
    -- to insert title bar items at the bottom of the key focus layout
    -- (but it's not really obvious)
end
```
(Dunno if this could have unwanted effect in other "Menu" instances.)

**Comment by Frenzie** [comment]
@NiLuJe 

> Sidebar: Unless I'm thinking of something else, that must have been some really old version, because those two have been there for approximately forever (in one form or another, at least) ;).

Not entirely, the top menu has a + in it on non-touch because those buttons weren't accessible. It may well not have worked until https://github.com/koreader/koreader/pull/8712 for example. And that may more or less accidentally have offered a superior user experience regardless due to not requiring an extra keypress when you just want to deal with the files.

**Comment by Commodore64user** [comment]
> You could also help yourself with a [user patch](https://github.com/koreader/koreader/wiki/User-patches), ie. `2-menu-no-titlebars-focus.lua`
> 
> ```lua
> 
> local Menu = require("ui/widget/menu")
> 
> Menu.mergeTitleBarIntoLayout = function(self)
> 
>     -- Do nothing.
> 
>     -- Or you could copy/paste the logic and rewrite it a bit
> 
>     -- to insert title bar items at the bottom of the key focus layout
> 
>     -- (but it's not really obvious)
> 
> end
> 
> ```
> 
> (Dunno if this could have unwanted effect in other "Menu" instances.)

It does affect other instances, example, Bookmarks. The hamburger becomes inaccessible.
