### ISSUE TITLE
How to get the element  in Main activity by uiautomator?

### ISSUE THREAD

**Issue by lusaty** [koreader/koreader#10317]
I want to get the element + in the main activity. But I just get a result as shown follow.
![2023-04-12_170843](https://user-images.githubusercontent.com/20251783/231411331-6daf82a9-5c57-4781-8e14-03962d88d32e.png)

I can not get the home element, the + element, and other elements.

**Comment by pazos** [comment]
You can't.

All you see in the screen is a giant black box without any nested elements.

Android tooling won't help you with that.

**Comment by lusaty** [comment]
> You can't.
> 
> All you see in the screen is a giant black box without any nested elements.
> 
> Android tooling won't help you with that.

Then，What about that tool that automatically click on the KOreader? I want to simulate the manual click to manipulate it.

**Comment by lusaty** [comment]
> > You can't.
> > All you see in the screen is a giant black box without any nested elements.
> > Android tooling won't help you with that.
> 
> Then，What about that tool that automatically click on the KOreader? I want to simulate the manual click to manipulate it.

**Comment by pazos** [comment]
> Then，What about that tool that automatically click on the KOreader? I want to simulate the manual click to manipulate it.

There's no way to do it programatically using an external tool.

The best case scenario involves a device with permissions to execute `adb shell input tap x y` on non-debuggable builds (rooted?) and even then you'll need to hardcode x/y coordinates to something available on that device and that's not portable.

What I was trying to say in my previous response is: we're not an android app in the general sense of an android view hierarchy so you cannot use any android tooling to deal with playing/mocking the ui.

**Comment by Frenzie** [comment]
On not-Android it might potentially be surprisingly simple to expose some of these FocusManager things to the built-in accessibility tools. (Of course it might also not be.) On Android I'd expect it to be highly convoluted though.

**Comment by lusaty** [comment]
> > Then，What about that tool that automatically click on the KOreader? I want to simulate the manual click to manipulate it.
> 
> There's no way to do it programatically using an external tool.
> 
> The best case scenario involves a device with permissions to execute `adb shell input tap x y` on non-debuggable builds (rooted?) and even then you'll need to hardcode x/y coordinates to something available on that device and that's not portable.
> 
> What I was trying to say in my previous response is: we're not an android app in the general sense of an android view hierarchy so you cannot use any android tooling to deal with playing/mocking the ui.
If I use "adb shell input tap x y", the value of x and y can be get by my feel.

**Comment by lusaty** [comment]
If I use "adb shell input tap x y", the value of x and y can be get by my feel.

**Comment by lusaty** [comment]
> > Then，What about that tool that automatically click on the KOreader? I want to simulate the manual click to manipulate it.
> 
> There's no way to do it programatically using an external tool.
> 
> The best case scenario involves a device with permissions to execute `adb shell input tap x y` on non-debuggable builds (rooted?) and even then you'll need to hardcode x/y coordinates to something available on that device and that's not portable.
> 
> What I was trying to say in my previous response is: we're not an android app in the general sense of an android view hierarchy so you cannot use any android tooling to deal with playing/mocking the ui.

If I use "adb shell input tap x y", the value of x and y can be get by my feel.
