### ISSUE TITLE
Crash after viewing Book cover 

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10314]
* KOReader version: 2023.03
* Device: Kobo Aura One (Also happens on Android version on Huawei phone)

#### Issue

KOReader crashes after viewing Book cover image

#### Steps to reproduce

1. Have any book open (epub or pdf)
2. Open `Book cover` (directly via a Quick Menu action)
3. Book cover displays fine
4. KOReader crashes when trying to close Book cover (either via multiswipe gesture or via single tap and then tapping `close`)

It has also happened that the cover image closed fine but then the crash occurred immediately at the next page turn. I couldn't reproduce this behavior, however.

[crash.log](https://github.com/koreader/koreader/files/11193206/crash.log)

This bug did not occur in the previous KOReader versions.

Thanks.

**Comment by NiLuJe** [comment]
Assuming that's the one, it seems pretty specific to PDFs ;).

```
./luajit: frontend/document/pdfdocument.lua:106: attempt to index field '_document' (a boolean value)
stack traceback:
	frontend/document/pdfdocument.lua:106: in function 'getPageTextBoxes'
	frontend/document/koptinterface.lua:519: in function 'getTextBoxes'
	frontend/document/koptinterface.lua:1281: in function 'getPageBoxesFromPositions'
	frontend/apps/reader/modules/readerview.lua:546: in function 'drawPageSavedHighlight'
	frontend/apps/reader/modules/readerview.lua:510: in function 'drawSavedHighlight'
	frontend/apps/reader/modules/readerview.lua:218: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:82: in function 'paintTo'
	frontend/ui/uimanager.lua:1225: in function '_repaint'
	frontend/ui/uimanager.lua:1446: in function 'handleInput'
	frontend/ui/uimanager.lua:1549: in function 'run'
	./reader.lua:295: in main chunk
	[C]: at 0x000140bd
```
