### ISSUE TITLE
[Kobo Clara 2E] Koreader freezes randomly 

### ISSUE THREAD

**Issue by petertsai0224** [koreader/koreader#10313]
KOReader version: 2023.03
Device: Kobo Clara 2E
Issue
Koreader has been freezed

Steps to reproduce

I found past articles mentioning this issue
Version 2023.03 fix this problem?
Because I still have freezed issues ;(

**Comment by NiLuJe** [comment]
Duplicate of #9806

----

FWIW, the most successful workaround so far *seems *to be disabling Notifications.
