### ISSUE TITLE
FR: [`Status Bar→Current page in chapter` display the Current Page of the chapter]

### ISSUE THREAD

**Issue by winstonma** [koreader/koreader#10324]
**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]

**Describe the solution you'd like**
I have a book with the following format in `toc.ncx` file

```
    <navPoint id="navPoint14">
      <navLabel>
        <text>CH1</text>
      </navLabel>
      <content src="xhtml/p-005.xhtml#mokuji-0005" />
      <navPoint id="navPoint15">
        <navLabel>
          <text>CH1.1</text>
        </navLabel>
        <content src="xhtml/p-005.xhtml#mokuji-0005-1" />
      </navPoint>
      <navPoint id="navPoint16">
        <navLabel>
          <text>CH1.2</text>
        </navLabel>
        <content src="xhtml/p-005.xhtml#mokuji-0005-2" />
      </navPoint>
      <navPoint id="navPoint17">
        <navLabel>
          <text>CH1.3</text>
        </navLabel>
        <content src="xhtml/p-005.xhtml#mokuji-0005-3" />
      </navPoint>
```

The `Current page in chapter` shows the page number of the subchapter (e.g. CH1.1, CH1.2...) but I would like to have the page number of the whole chapter (`xhtml/p-005.xhtml` file) instead.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by poire-z** [comment]
You can try disabling some ToC levels in `Top menu > first item > Settings > Progress bar: NN ticks >` and play with the other checkboxes:
![image](https://user-images.githubusercontent.com/24273478/231968459-e793cf20-15fe-4567-b9f7-05c1b73842bd.png)

**Comment by winstonma** [comment]
Thanks for the help and also the photo. It helps a lot.
