### ISSUE TITLE
Can't select words in the OCR layer correctly.

### ISSUE THREAD

**Issue by xingwu-yu** [koreader/koreader#10332]
* KOReader version: 2023.03

I use ABBYY FineReader (15.0.114.4683) to create an OCR layer for a pdf file, and it looks _all alright_ in FineReader (and the exported docx file, the pdf file opened with PC browser, etc., just everywhere). Take the word "warranted" as an example:
![screenshott](https://user-images.githubusercontent.com/130893794/232283349-f7ad5822-9dcd-4144-9172-8d9cd7fae877.png)

But, when I open the exported PDF file in KOReader, I can't select the whole word:
![screenshottt](https://user-images.githubusercontent.com/130893794/232283464-87538167-90c9-4e22-b9ad-8ee82f9fc466.jpg)

Then I copy & paste, and find out that it becomes: w a r r a n t e d

So my question is, where do these blank spaces come from? This makes it almost impossible to use the dictionary function.

Thanks.

**Comment by Frenzie** [comment]
That comes from the text layer. You should see the same thing with `pdftotxt` for example.

**Comment by xingwu-yu** [comment]
> That comes from the text layer. You should see the same thing with `pdftotxt` for example.

Thank you for replying. I just tried using `PyPDF2` to extract text from the same pdf file, but there isn't any blank space:

![screenshottt](https://user-images.githubusercontent.com/130893794/232305511-53c4ee12-15e6-4962-ba1a-825b5686b8c9.png)

So I wonder if there's (maybe) something wrong with KOReader when loading the text layer?

**Comment by Frenzie** [comment]
The program you mention uses complex heuristics: https://pypdf2.readthedocs.io/en/stable/user/extract-text.html#why-text-extraction-is-hard

Perhaps of particular relevance:
> The PDF format is meant for printing. It is not designed to be read by machines. The text within a PDF document is absolutely positioned, meaning that every single character could be positioned on the page.
> 
> The text
> 
> >     This is a test document by Ethan Nelson.
> 
> can be represented as
> 
> >     [(This is a )9(te)-3(st)9( do)-4(cu)13(m)-4(en)12(t )-3(b)3(y)-3( )9(Et)-2(h)3(an)4( Nels)13(o)-5(n)3(.)] TJ
> 
> Where the numbers are adjustments of vertical space. This representation used within the PDF file makes it very hard to guarantee correct whitespaces.

So the short answer is probably not. For example, see this PDF I OCR-ed. 
[Lievens V6903000247_20140402125113015-001-readable.pdf](https://github.com/koreader/koreader/files/11242125/Lievens.V6903000247_20140402125113015-001-readable.pdf)

The outcome of a random selection looks fine (`interne` is supposed to have spaces, `heeft` and `fel` are not; such is the outcome of OCR):

> Reeds lang geleden heef t Pater van Mierlo op in t e r n e gronden bewezen dat de XII Dogheden (I) niet op de lijst van Ruusbroecs werken thuishoort. Mijns inziens terecht. Het is nl. moeilijk te aanvaarden dat Ruusbroec, die zich zo f el tegen Eckhart heef t gekeerd, teksten van de bestreden meester in het kompilatiewerk van

![Screenshot_20230416_133658](https://user-images.githubusercontent.com/202757/232307292-b45abc6b-a9c7-47e1-ad5f-c1228cbd5efa.png)

**Comment by xingwu-yu** [comment]
> The program you mention uses complex heuristics: https://pypdf2.readthedocs.io/en/stable/user/extract-text.html#why-text-extraction-is-hard
> 
> Perhaps of particular relevance:
> 
> > The PDF format is meant for printing. It is not designed to be read by machines. The text within a PDF document is absolutely positioned, meaning that every single character could be positioned on the page.
> > The text
> > > ```
> > > This is a test document by Ethan Nelson.
> > > ```
> > 
> > 
> > can be represented as
> > > ```
> > > [(This is a )9(te)-3(st)9( do)-4(cu)13(m)-4(en)12(t )-3(b)3(y)-3( )9(Et)-2(h)3(an)4( Nels)13(o)-5(n)3(.)] TJ
> > > ```
> > 
> > 
> > Where the numbers are adjustments of vertical space. This representation used within the PDF file makes it very hard to guarantee correct whitespaces.
> 
> So the short answer is probably not. For example, see this PDF I OCR-ed. [Lievens V6903000247_20140402125113015-001-readable.pdf](https://github.com/koreader/koreader/files/11242125/Lievens.V6903000247_20140402125113015-001-readable.pdf)
> 
> The outcome of a random selection looks fine (`interne` is supposed to have spaces, `heeft` and `fel` are not; such is the outcome of OCR):
> 
> > Reeds lang geleden heef t Pater van Mierlo op in t e r n e gronden bewezen dat de XII Dogheden (I) niet op de lijst van Ruusbroecs werken thuishoort. Mijns inziens terecht. Het is nl. moeilijk te aanvaarden dat Ruusbroec, die zich zo f el tegen Eckhart heef t gekeerd, teksten van de bestreden meester in het kompilatiewerk van
> 
> ![Screenshot_20230416_133658](https://user-images.githubusercontent.com/202757/232307292-b45abc6b-a9c7-47e1-ad5f-c1228cbd5efa.png)

Wow. Thanks again for your detailed reply! It indeed is all about the OCR software and its formatting mechanism. When I use Acrobat Pro (instead of FineReader) to do the OCR, it perfectly works:

![screenshoot](https://user-images.githubusercontent.com/130893794/232319962-f0e52bba-f66c-4526-bea3-b535db37fb67.jpg)

Then I try to check the source code of both pdfs. The FineReader version is a bit shattered:
>[(war)10.2(rant)13.4(ed)]TJ

But the Acrobat version is absolutely fine:
>(warranted ) Tj

**Comment by Frenzie** [comment]
Feel free to try to improve the heuristics a bit because they're currently fairly primitive, but at the core I think it's not an issue then. :-)
