### ISSUE TITLE
"Reference Pages / Show reference page labels" can't be disabled as default settings.

### ISSUE THREAD

**Issue by ScrambleTheRamble** [koreader/koreader#10335]
* KOReader version: 2023.03
* Device:  PocketBook Inkpad 3 & Boyue Likebook Minas

#### Issue
When displaying epubs generated with KCC (Kindle comic Converter) I get random text shown in on the right of the page that corresponds to a bookmark. This can be hidden by going to "Reference pages" and turning of "Show reference page labels in margin".

It seems to be impossible to set this off by default even when going to "Document Settings" > "Save document settings as default".

#### Steps to reproduce
Open an epub generated by kcc with a ToC, toggle setting and save as default. Open another document.

**Comment by NiLuJe** [comment]
Whazt about the standard long-press?

(I'm pretty sure this is how all my devices are srt-up, and It Works(TM)).

**Comment by ScrambleTheRamble** [comment]
Err.... TIL I guess? That works :)

**Comment by NiLuJe** [comment]
Though shall not skip reading the quickstart guide ;p.

**Comment by NiLuJe** [comment]
On another note, I'm not entirely sure if this fits of the bill of what should be part of the "document settings" for the purposes of the stuff mentioned in the OP and/or profiles. Thoughts, @hius07 ?

**Comment by hius07** [comment]
Currently we save as default the settings from the bottom menu, and only a few more:
https://github.com/koreader/koreader/blob/5dd88535bab6e8208cadcd3ebc66581ad38b1d6e/frontend/apps/reader/modules/readermenu.lua#L347-L354
