### ISSUE TITLE
Using webdav to synchronize reading statistics when the database is too large can cause the synchronization to take too long.

### ISSUE THREAD

**Issue by xsdjt** [koreader/koreader#10342]
**Does your feature request involve difficulty completing a task? Please describe.**
Use webdav to quickly synchronize reading statistics

**Describe the solution you'd like**
Simplify reading statistics part of the database statistics.sqlite3

**Comment by xsdjt** [comment]
I don't know why this file is so big

1.5G Apr 19 06:55 statistics.sqlite3

**Comment by xsdjt** [comment]
Maybe just syncing the reading data alone might be good

**Comment by NiLuJe** [comment]
> I don't know why this file is so big
> 
> 1.5G Apr 19 06:55 statistics.sqlite3

That does indeed seem like rather a lot ;o).

How many pages have been actively read on this device?

**Comment by xsdjt** [comment]
just a little.
________________________________
发件人: NiLuJe ***@***.***>
发送时间: 2023年4月19日 13:11
收件人: koreader/koreader ***@***.***>
抄送: zhouguoqiang ***@***.***>; Author ***@***.***>
主题: Re: [koreader/koreader] Using webdav to synchronize reading statistics when the database is too large can cause the synchronization to take too long. (Issue #10342)


I don't know why this file is so big

1.5G Apr 19 06:55 statistics.sqlite3

That does indeed seem like rather a lot ;o).

How many pages have been actively read on this device?

―

**Comment by NiLuJe** [comment]
Ping @weijiuqiao in case that sort of thing rings a bell?

**Comment by weijiuqiao** [comment]
@xsdjt  If you could take a look at the tables inside the sqlite file and give us their entry count, that might be helpful. It's a bit astonishing how big the file has got!
