### ISSUE TITLE
FR: Option to NOT show the new progress "Sprite" animation and restore progress bar

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#10347]
Ever since I updated to KOReader 2023.03 "Cherry Blossom" there is a new graphical animation that appears in the upper left hand corner of the screen, often it persists there for minutes and obscures the text.  

In my opinion it degrades the appearance of KOReader.  

I spend a lot of time customizing my reading experience using the fantastic assortment of options in KOReader.

In previous versions, I used to see a very slim, elegant progress bar across the top of the screen when changes in the layout were being implemented.

Now, in 2023.03 "Cherry Blossom", there is a new graphical element that appears in the upper left hand corner and it really kills the "mood" when it appears.  It looks like the sort of graphical  sprite you might see on a 1990s mobile phone LCD display, shattering any illusion of style, and violently pulling you from the world of "reading a book" into the world of "playing with an electronic toy".

Can we please have an option to suppress these graphics entirely?

**Comment by Frenzie** [comment]
I understand you don't like it, but I still don't know what you're actually talking about or what you do to trigger it. Is this in reference to <https://github.com/koreader/koreader/pull/10086>?

**Comment by zmixnyc** [comment]
> I understand you don't like it, but I still don't know what you're actually talking about or what you do to trigger it. Is this in reference to #10086?

It's a series of graphical icons that were not in any previous release:

![IMG_7975](https://user-images.githubusercontent.com/48537231/233794448-49dcfcd0-eb6d-4444-a865-108aa56fd0ed.jpg)
![IMG_7976](https://user-images.githubusercontent.com/48537231/233794459-6dc12ba1-a277-4f39-9c45-be8dd3940264.jpg)
![IMG_7974](https://user-images.githubusercontent.com/48537231/233794461-180b3ae0-ea4d-4177-ad5b-2f17cee78314.jpg)
![IMG_7973](https://user-images.githubusercontent.com/48537231/233794464-511450cf-b874-4770-bb36-6ff61987bdd7.jpg)

**Comment by poire-z** [comment]
> Can we please have an option to suppress these graphics entirely?

You do have that option. See the quoted section in gray with these nice 1990s icons in https://github.com/koreader/koreader/releases/tag/v2023.03 (so you at least get to understand what they mean, may be you'll get to love them :)

> This feature can be disabled per book with tap, or globally with long-press, on `Gear > Document > [x] Enable partial renderings`.

> into the world of "playing with an electronic toy".

Isn't that what you're doing when tweaking book settings ? :)

**Comment by zmixnyc** [comment]
> > Can we please have an option to suppress these graphics entirely?
> 
> You do have that option. See the quoted section in gray with these nice 1990s icons in https://github.com/koreader/koreader/releases/tag/v2023.03 (so you at least get to understand what they mean, may be you'll get to love them :)
> 
> > This feature can be disabled per book with tap, or globally with long-press, on `Gear > Document > [x] Enable partial renderings`.
> 
> > into the world of "playing with an electronic toy".
> 
> Isn't that what you're doing when tweaking book settings ? :)

Thank you. I cannot find any mention of disabling them, could you quote that text here?

If I want to see them again. I'll just buy a Nokia Mobile Phone.

**Comment by poire-z** [comment]
I quoted it in my post above. Showing a screenshots as an alternative:
![image](https://user-images.githubusercontent.com/24273478/233795082-cb8d3799-07b0-49de-9875-83811ff31b8c.png)

**Comment by zmixnyc** [comment]
Thank you ...!

I missed that at first,  then I edited my post - too late..!


Thank you thank you thank you..!

I feel so much more modern already!!!

**Comment by zmixnyc** [comment]
PROBLEM:

I went to another book and found I  cannot de-select "enable partial renderings"

short press = nothing

long press = my new default "disabled" is starred

**Comment by zmixnyc** [comment]
Next time I'll RTFM, thanks again for the help...!
