### ISSUE TITLE
FR: BookInfo: add total book words

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#10340]
Since information about the number of [lines and words on each page](#10255) has been added, wouldn't it be useful to add the total number of words in the book?

**Comment by poire-z** [comment]
> Since information about the number of lines and words on each page has been added

Because it's cheap to compute for the current page.

> wouldn't it be useful to add the total number of words in the book?

Useful, maybe. Cheap and easy, not really :) It might block for a few minutes counting the words in ALL the pages of the book.

**Comment by ichnilatis-gr** [comment]
Well, never mind; it was just a thought...
