### ISSUE TITLE
FR: when saving Wikpedia articles - default settings for including images and the image quality

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#10356]
**Does your feature request involve difficulty completing a task? Please describe.**
Saving Wikipedia articles is an amazing feature, but it is unnecessarily tedious. 
Whenever an article is saved, the user gets two popups: `Would you like to download and include [the article images] in the generated EPUB file?` and `Would you like to use slightly higher quality images?`, and these choices must be made every single time.

I've saved dozens of articles over the years, and the number of times I wanted to avoid saving images or use lower-quality images is vanishingly small.

**Describe the solution you'd like**
1. Setting for saving images:
`Save/Don't save/Always ask` and then: either make `Save` the default, or keep `Always ask` the default and add an additional button to the popup that sets a default, or make the popup inform the user that they can save a default
2. Setting for image quality:
`Higher quality/Standard quality/Always ask` and make `Higher quality` the default. or simply remove `Standard quality` entirely. with modern storage sizes, I think it makes little sense.

**Describe alternatives you've considered**
Choosing the same options every time an article is saved

**Comment by poire-z** [comment]
You're picky, pickx !

The `Wikipedia settings>`  is not crowded, so I guess it could have 2 more settings.

Previous Wikipedia complains at https://github.com/koreader/koreader/issues/3757#issuecomment-374201294 : 

> >    I need to reply standard or hi-res pictures do I want (oh man.... every time!!!)

> On a bus, with a slow internet link, I guess you may want to know how many images there are, before deciding, also based on the article (depending on the subject, you may not care about images, and you just want them inline in the epub), if you really need standard or hi-res. The few taps you want to avoid are nothing compared to the 30-120 seconds needed to download 146 images.

**Comment by pickx** [comment]
@poire-z If you're fine with it, I guess I'll give it a stab and see if I can add those 2 settings as my first PR here.

**Comment by poire-z** [comment]
Go ahead.
(Settings menu items in frontend/apps/reader/modules/readerwikipedia.lua, with inspiration from the other existing ones proposing Ask/Prompt, Always, Never - some in frontend/ui/elements/. Use of the settings at the bottom of frontend/ui/wikipedia.lua.)
