### ISSUE TITLE
logical text misaligned with the graphical text if the line spacing is lower than 100% with this font

### ISSUE THREAD

**Issue by Ceynou** [koreader/koreader#10354]
* KOReader version: 2023.03 "Cherry Blossom"
* Device: Kindle Paperwhite 4 (5.15.1.1)

#### Issue
The title + if you're not precise enough you can select/highlight something around what you actually wanted.

#### Steps to reproduce
any japanese epub
using the following font(I don't know its proprieties, serif? you can easily find it online)
A-OTF-KyokaICAPro-Regular

**Line spacing 100%**
![Reader_2023-04-24_195412](https://user-images.githubusercontent.com/41862916/234108477-9b32f5e0-8829-4d41-af7d-ec23f0b44a9c.png)

**Line spacing 70%**
![Reader_2023-04-24_195343](https://user-images.githubusercontent.com/41862916/234108484-4c1878f2-ba03-49ed-beca-25ae67284de0.png)

I just checked on [ttu](https://reader.ttsu.app) and I can't set it lower than 100% is it because it obviously leads to issues depending on the font but koreader let you do it anyway for customizability freedom?

**Comment by poire-z** [comment]
So ? :)
Crappy font, may be not aimed at being used with HTML and Books, where, unlike mostly all other fonts, the glyphs stroke sit at the bottom of the glyph square (which makes the gray are when you select text when line spacing is 100%), so all the interline spacing is put above.
It would moreover be odd if we were to use some other fallback fonts to render some non-supported text alongside.
Not for us to do anything about it I think.
For you to may be fix it with font editing software if you really like it - or find another font that don't exhibit this crappiness.

**Comment by Ceynou** [comment]
Okay
