### ISSUE TITLE
"Lock status bar" prevents hiding/showing the status bar via gestures

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#10355]
* KOReader version: 2023.03
* Device: (all of them)

#### Issue
The setting "lock status bar" prevents hiding the status bar by tapping it, but it also prevents hiding it with a gesture, if that gesture is set to toggle the visibility of the status bar.

The use case for changing this behavior is that I often accidentally hide the status bar by tapping the bottom of the screen. I would rather toggle it with a custom gesture that is harder to accidentally trigger.

I think the setting "lock status bar" should be changed to "toggle status bar by tapping it", and disabling this setting should not change the behavior of the above-mentioned gestures.

**Comment by NiLuJe** [comment]
That's probably because it predates the gesture manager.

I don't quite recall how it's implemented though, so it might be easier said than done ;).
