### ISSUE TITLE
"Start with" menu initializes as nil

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#10368]
* KOReader version: 0db042f
* Device: emulator

#### Issue
![Screenshot_20230429_110911](https://user-images.githubusercontent.com/202757/235294828-515d159b-8b5f-473c-ae99-a3de12cb93b0.png)

Regression from <https://github.com/koreader/koreader/pull/10198>?

#### Steps to reproduce
Close the program and start it.

Clicking on the nil and going back up fixes the string.

**Comment by Frenzie** [comment]
df9c2bcb7f9f1d3f60bfaad20996a2b029d5b584 doesn't display the issue, 4d26650 does. So regression from https://github.com/koreader/koreader/pull/10198

**Comment by Wladefant** [comment]
I encountered the same issue. After updating to the latest version, the sort by option displays nil. Moreover, the app crashes whenever I tap on a folder, unless I change the sort by option first.

**Comment by Frenzie** [comment]
I don't see any crashes. Could you share the crash.log?

**Comment by Wladefant** [comment]
Yes, will do that tomorrow

**Comment by Frenzie** [comment]
This was probably accidentally auto-closed by merging the pull request. Do you mean it was fixed by updating?

**Comment by Wladefant** [comment]
@Frenzie are you asking me. I said sorry because I did not do my duty

**Comment by Frenzie** [comment]
Alright, thanks. :+1:
