### ISSUE TITLE
Current Page symbol changed from / to //

### ISSUE THREAD

**Issue by edent** [koreader/koreader#10375]
* KOReader version: v2023.04
* Device: Likebook Ares

#### Issue

The current page symbol should show `12 / 345` - instead, it's showing `12 // 345`.  I've tried disabling and re-enabling the setting, restarting the device, etc. This started after a recent update (although I haven't updated for a while)

![Screenshot_20230403-224300](https://user-images.githubusercontent.com/837136/235367778-2ee1f039-544a-4055-9484-1863570a690d.png)

**Comment by poire-z** [comment]
Happens on the rare books that advertise "non linear fragments", cf #6809 , #6847 .
The sections considered "non-linear" will happen in gray in the Book map. Usually it should be some footnotes sections, at end of chapter or end of book - but sometimes, it's just the cover, and not at all useful.

You can disable them, and get back your /, by unchecking:
![image](https://user-images.githubusercontent.com/24273478/235368535-a8ea40d6-702d-4a6f-ae59-f1ce979deda7.png)

Long-press on it to never be bothered by them. The default is to show and use them when available, so at least, you know there is this info/feature (and personally, once I'm happy being informed that the book have them, I disable them :).

**Comment by edent** [comment]
Ah! Yeah, it was only on that one book. I hid the fragments, restarted, and they were gone. Perfect. Thanks for the help.
