### ISSUE TITLE
Pocketbook OPDS - Book missing in Library

### ISSUE THREAD

**Issue by sascharucks** [koreader/koreader#10383]
* KOReader version: 2023.04
* Device: Pocketbook Era

#### Issue
I downloaded a book via the OPDS integration (from Calibre). The book is saved into /books.
I see the book in Koreader but not in the Pocketbook Library (or startpage) until I open the book in Koreader.

**Comment by pazos** [comment]
If `/books` is indeed the directory "books" on the root filesystem I doubt the pocketbook system will show documents there. And you shouldn't store documents anyways.

If `/books` is "books" on your home folder and you didn't change it should be picked by the pocketbook homepage in a few minutes. In that case your books is `/mnt/ext1/books`

Anyways, not our bug :)

**Comment by sascharucks** [comment]
Sorry for confusion. Folder is at /mnt/ext1/books. Waited longer (>10 min) and the book appeared. 
Thanks for help and sorry for the unnecessary issue. Closing ticket.
