### ISSUE TITLE
FR: Expose "lock auto rotation" as gesture

### ISSUE THREAD

**Issue by sascharucks** [koreader/koreader#10384]
Sometimes when I read in bed the device (Pocketbook Era) rotates when I don't want it to, but often I like the auto-rotation. To de- and activate this feature I need a lot of taps:

Under Settings - Screen - Rotation - "Lock auto rotation to current orientation"

I would like to have this feature exposed to the gesture settings. Would this be possible or is there another way to easily active this?
I couldn't find a hardware feature on the Pocketbook. Thanks!

**Comment by offset-torque** [comment]
You can add it as a Quick Menu item. And you can access this Quick Menu with any gesture. Of course you can add other frequently used settings to this menu. More info in the user guide.

**Comment by sascharucks** [comment]
Thanks. The quick menu wasn't my problem, but I found that the rotation lock has a different name in the gesture menu than in the normal settings. Maybe worth unifying that.

"Toggle accelerometer" is the rotation lock setting. 
I will close the issue.
