### ISSUE TITLE
Cannot run in wsl2 properly

### ISSUE THREAD

**Issue by Dorapower** [koreader/koreader#10380]
* KOReader version: v2023.04
* Device: Ubuntu 22.04.2 LTS, run and installed by wsl2 on windows11

#### Issue

crash on startup

#### Steps to reproduce
1. install the amd64 deb package in wsl with wget and apt
2. launch the software in the windows start menu button or directly enter the name in wsl terminal
3. a white box blinks and disappears, if run in the terminal an error message will be printed which is provided below

##### `crash.log` (if applicable)

```
/usr/bin/koreader: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/02/23-21:38:16
 [*] Version: v2023.04

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
Starting SDL in /usr/lib/koreader/
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
05/02/23-21:38:16 INFO  initializing for device Linux
05/02/23-21:38:16 INFO  framebuffer resolution: {
  h = 800,
  w = 600
} --[[table: 0x7f1f9b05aa18]]
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
05/02/23-21:38:16 INFO  Performing one-time migration for 20191129
05/02/23-21:38:16 INFO  Performing one-time migration for 20200421
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
05/02/23-21:38:16 INFO  /home/lokdora/.config/koreader/cache/fontlist/fontinfo.dat fopen: No such file or directory -> initializing it
05/02/23-21:38:17 INFO  Performing one-time migration for 20210306 (1/2)
05/02/23-21:38:17 INFO  Performing one-time migration for 20210306 (2/2)
05/02/23-21:38:17 INFO  Performing one-time migration for 20210330
05/02/23-21:38:17 WARN  Error when loading plugins/statistics.koplugin/main.lua: frontend/cache.lua:68: cannot open /home/lokdora/.config/koreader/cache/: No such file or directory
05/02/23-21:38:17 INFO  Performing one-time migration for 20210404
05/02/23-21:38:17 INFO  Performing one-time migration for 20210409
05/02/23-21:38:17 WARN  os.rename: /home/lokdora/.config/koreader/cache/fontinfo.dat: No such file or directory
/usr/lib/koreader/luajit: frontend/ui/data/onetime_migration.lua:175: loop or previous error loading module 'document/doccache'
stack traceback:
        [C]: in function 'require'
        frontend/ui/data/onetime_migration.lua:175: in main chunk
        [C]: in function 'require'
        ./reader.lua:193: in main chunk
        [C]: at 0x560026c08bb0
```

**Comment by NiLuJe** [comment]
I'm mlildly puzzled as to how you could even be in a state where the `cache` folder doesn't exist?

I'm not in a position to check further than the fact that we do ship it in build artifacts right now...

**Comment by NiLuJe** [comment]
Oh, wait. Linux, XDG. Blegh.

**Comment by Frenzie** [comment]
Fun fact, it's also an issue with the AppImage but not if you run
reader.lua after doing --appimage-extract.

@NiLuJe ***@***.***> The cache/whatever doesn't exist thing is
deceptive; that'll also happen on normal Linux because it's applying a ton
of irrelevant migrations. Perhaps there's a trick we can use to say it's
definitely post-2021 so in that case initialize to current date instead of
0.

**Comment by Frenzie** [comment]
Reproducible with  KO_MULTIUSER=1

**Comment by Frenzie** [comment]
Apologies for the spam. Logging in to GH is annoying. Anyway, something like this would probably do the trick.

```
    local datadir = DataStorage:getDataDir()
    if lfs.attributes(datadir, "mode") ~= "directory" then
        lfs.mkdir(datadir)
    end
    for _, dir in ipairs(sub_data_dirs) do
        local sub_data_dir = string.format("%s/%s", datadir, dir)
        if lfs.attributes(sub_data_dir, "mode") ~= "directory" then
            lfs.mkdir(sub_data_dir)
        end
    end
```

**Comment by Dorapower** [comment]
Manually creating the `.config` folder works, and now the app runs properly.

Thanks for the help.

**Comment by NiLuJe** [comment]
> something like this

We've got https://github.com/koreader/koreader/blob/0533ec46d82f8a850c423c56ebf42ac6844dc5ae/frontend/util.lua#L760-L793 ;).

**Comment by Frenzie** [comment]
I worry that might be a bit excessive in this context? But yes, it's an
option.

**Comment by mendelct** [comment]
I was having the same issue as the OP with an AppImage, now I'm getting the following error.
`---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/04/23-11:56:44
./luajit: ./datastorage.lua:38: No such file or directory
stack traceback:
        [C]: in function 'error'
        ./datastorage.lua:38: in function 'getDataDir'
        ./datastorage.lua:84: in function 'initDataDir'
        ./datastorage.lua:93: in main chunk
        [C]: in function 'require'
        frontend/userpatch.lua:34: in main chunk
        [C]: in function 'require'
        ./reader.lua:25: in main chunk
        [C]: at 0x55e26b62c330
`

**Comment by Frenzie** [comment]
Ah yes, there's a typo on line 28/29.
