### ISSUE TITLE
KOREader does not start on Kobo Elipsa 2E

### ISSUE THREAD

**Issue by ealex** [koreader/koreader#10408]
* KOReader version: v2023.04
* Device: Kobo Elipsa 2E

#### Issue
KOReader can't start on Kobo Elipsa 2E.
I can see the following error in the log file: `./luajit: frontend/device/kobo/device.lua:1560: unrecognized Kobo model condor with device id 389`

#### Steps to reproduce
Install KOReader on a Kobo Elipsa 2E device, with firmware `4.36.21095` and try to start it.
The device will freeze for 10+ seconds and then it will reboot.

This is the relevant crash log portion (full file attached)
<details>
  <summary>crash.log</summary>

```
Original fb rotation is set @ 1
Original fb bitdepth is set @ 32bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Unidentified Kobo device code (389)!
[FBInk] Detected a Kobo Unknown! (389 => ?? @ Mark ?)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 167 dpi
[FBInk] Variable fb info: 1404x1872, 32bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 10543104 bytes & line length: 5616 bytes
[FBInk] Canonical rotation: 2 (Upside Down, 180°)
[FBInk] Fontsize set to 16x16 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 87 cols, Page size: 117 rows
[FBInk] Detected a change in framebuffer rotation (1 -> 3)
[FBInk] Reinitializing...
[FBInk] Variable fb info: 1404x1872, 32bpp @ rotation: 3 (Counter Clockwise, 270°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 10543104 bytes & line length: 5616 bytes
[FBInk] Canonical rotation: 0 (Upright, 0°)
[FBInk] Fontsize set to 16x16 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 87 cols, Page size: 117 rows
[FBDepth] Screen is 1404x1872 (1404x1877 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 10543104 bytes with a scanline stride of 5616 bytes
[FBDepth] Requested canonical rota 0 translates to 3 for this device
[FBDepth] Switching fb to 8bpp @ rotation 3 . . .
Updating bitdepth from 32bpp to 8bpp
Sanitizing grayscale flag for 8bpp
Updating rotation from 1 (Clockwise, 90°) to 3 (Counter Clockwise, 270°)
Bitdepth is now 32bpp (grayscale: 1) @ rotate: 3 (Counter Clockwise, 270°)
[FBDepth] Screen is 1404x1872 (1404x1877 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 10543104 bytes with a scanline stride of 5616 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/09/23-14:27:19
 [*] Version: v2023.04

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
./luajit: frontend/device/kobo/device.lua:1560: unrecognized Kobo model condor with device id 389
stack traceback:
	[C]: in function 'error'
	frontend/device/kobo/device.lua:1560: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:61: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 05/09/23 @ 14:27:19)
Running FW 4.36.21095 on Linux 4.9.77 (#1 SMP PREEMPT 39a784229346-20230331T162906-B0331164118)
Attempting to restart KOReader . . .
!!!!
```
</details>

It tries several times, and then it quits and crashes the entire system:
<details>
  <summary>crash.log</summary>

```
Too many consecutive crashes, aborting . . .
!!!! ! !!!!
Restoring original fb bitdepth @ 32bpp & rotation @ 1
[FBInk] Unidentified Kobo device code (389)!
[FBInk] Detected a Kobo Unknown! (389 => ?? @ Mark ?)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 167 dpi
[FBInk] Variable fb info: 1404x1872, 32bpp @ rotation: 3 (Counter Clockwise, 270°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 10543104 bytes & line length: 5616 bytes
[FBInk] Canonical rotation: 0 (Upright, 0°)
[FBInk] Fontsize set to 16x16 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 87 cols, Page size: 117 rows
[FBInk] Detected a change in framebuffer rotation (3 -> 1)
[FBInk] Reinitializing...
[FBInk] Variable fb info: 1404x1872, 32bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 10543104 bytes & line length: 5616 bytes
[FBInk] Canonical rotation: 2 (Upside Down, 180°)
[FBInk] Fontsize set to 16x16 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 87 cols, Page size: 117 rows
[FBDepth] Screen is 1404x1872 (1404x1877 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 10543104 bytes with a scanline stride of 5616 bytes
[FBDepth] Current bitdepth is already 32bpp, but the grayscale flag is bogus!
[FBDepth] Switching fb to 32bpp @ rotation 1 . . .
Updating bitdepth from 32bpp to 32bpp
Sanitizing grayscale flag for bitdepths > 8bpp
Updating rotation from 3 (Counter Clockwise, 270°) to 1 (Clockwise, 90°)
Bitdepth is now 32bpp (grayscale: 0) @ rotate: 1 (Clockwise, 90°)
[FBDepth] Screen is 1404x1872 (1404x1877 addressable, fb says 1404x1872)
[FBDepth] Buffer is mapped for 10543104 bytes with a scanline stride of 5616 bytes
```
</details>

I am available to test new device support, but I don't know how to add it myself.

[crash.log](https://github.com/koreader/koreader/files/11431066/crash.log)

**Comment by Frenzie** [comment]
For a quick test, change for example this in device/kobo/device.lua:

```lua
elseif codename == "goldfinch" then
    return KoboGoldfinch
else
```

to codename == "condor" and see what happens.

(Better, look into the actual chips etc.)

**Comment by ealex** [comment]
there's a new error reason:
```
./luajit: frontend/device/kobo/device.lua:745: Error opening input device </dev/input/by-path/platform-bd71828-pwrkey-event>: No such file or directory
stack traceback:
	[C]: in function 'open'
	frontend/device/kobo/device.lua:745: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x000140bd
!!!!
``` 

I've attached the new log file.
Do you know how I can gather more data without tearing down the device ? 
From the firmware update, I think it's based on a MT8113T SOC.
I'll start digging trough that - maybe I can enable telnet, or move the dmesg logs to somewhere user accessible.

[crash.log](https://github.com/koreader/koreader/files/11432638/crash.log)

**Comment by Frenzie** [comment]
You can always just comment out that line with `--`.

**Comment by NiLuJe** [comment]
Won't help, it's running on a new SoC.

I'm waiting on the kernel sources to start the port.

**Comment by NiLuJe** [comment]
As an actual owner of the device, you might have a valid reason to poke the Kobo CS for that, because my own https://github.com/kobolabs/Kobo-Reader/issues/126 hasn't seen lmuch action so far ;).

**Comment by Frenzie** [comment]
I believe one time in the past they immediately committed it but took a little longer to push it, leading to some minor miscommunication. :-)

**Comment by Knut0730** [comment]
What is the current status of the kernel sources @NiLuJe? 

Sincerely Elipsa 2E waiting _semi_-patiently to be able to read academic papers on my device :)

**Comment by NiLuJe** [comment]
[Nothing yet](https://github.com/kobolabs/Kobo-Reader).

**Comment by Knut0730** [comment]
Weird that it is taking such a long time. Is there anything I can do to help, since I have the device? I really “need” KOReader to work soon on my Elipsa… @NiLuJe

**Comment by NiLuJe** [comment]
Besides bugging Kobo CS in the vague hope that it could help get the ball rolling, not really.

**Comment by Knut0730** [comment]
Glad to hear it! Kobo Messenger couldn't give me an ETA on the release, but it's great that they were so quick. I guess they just needed a push.

**Comment by NiLuJe** [comment]
I'm only going to be able to deal with the screen, though.

Wi-Fi will probably be... fun.

You can see what @Bartvelp had to go through for the Clara 2E over here, because it's going to be pretty similar ^^.
https://github.com/koreader/koreader/issues/9552

**Comment by Knut0730** [comment]
I believe in you! Do you have an estimate on how long it will take before its possible to update?

**Comment by NiLuJe** [comment]
I'm going to have people with the device run custom things way before anything hits a release.

**Comment by NiLuJe** [comment]
Okay, I've got a first batch of tests to run ;).

Basically, for now, a devcap run, as described in the [first part of this post](https://github.com/koreader/koreader/issues/9552#issuecomment-1256555076), but with the binaries for *this* thread, of course ;).

[Kobo-DevCap-Test.tar.gz](https://github.com/koreader/koreader/files/12065404/Kobo-DevCap-Test.tar.gz)

**Comment by NiLuJe** [comment]
And for the later tests, you'll need [this build of strace](http://files.ak-team.com/niluje/mrpub/Other/strace-kobo-r3.tar.gz), which should decode the refresh ioctls properly; but we'll get to that later, I'd like to check that the basics work first ;).

**Comment by ealex** [comment]
> Okay, I've got a first batch of tests to run ;).
> 
> Basically, for now, a devcap run, as described in the [first part of this post](https://github.com/koreader/koreader/issues/9552#issuecomment-1256555076), but with the binaries from _this_ thread, of course ;).
> 

Hello
Check the attached Kobo-DevCap-Results.tar.gz file
Sorry for the delay, I did not have the device with me yesterday. 

[Kobo-DevCap-Results.tar.gz](https://github.com/koreader/koreader/files/12076164/Kobo-DevCap-Results.tar.gz)

**Comment by NiLuJe** [comment]
Great, thanks :).

Did everything actually show up on screen?

(i.e., did it look something like that at the end: https://github.com/NiLuJe/FBInk/blob/master/utils/devcap_expected_results.png).

Was the number at the bottom of the screen 1 like in that example, or 3? (Don't mind the letters for now, I'm concerned with the numbers). Which number was on the left edge, and which on the right egde?

(Do make sure you start the test with the device in the "standard" Portrait rotation).

**Comment by Knut0730** [comment]
Give a shout if you want me (as a person with limited technical knowledge) to help out here as well, seeing as I have the device as well. Looking to make this go as fast as possible, so happy to help!.. though I don't know how to do these tests in practice.

**Comment by ealex** [comment]
I've run another test with the proper orientation
and added a photo of the screen's state at the end of the test
[Kobo-DevCap-Results.tar.gz](https://github.com/koreader/koreader/files/12077773/Kobo-DevCap-Results.tar.gz)
![20230718_110534](https://github.com/koreader/koreader/assets/5410392/d6ccda0d-87d2-404b-bb36-f934256892df)

**Comment by ezuk** [comment]
> Without physical access to a device,

Now that kernel sources are out, if you wanted a device to work on, just say the word (well, and email me a shipping address). :)

**Comment by NiLuJe** [comment]
> I've run another test with the proper orientation and added a photo of the screen's state at the end of the test [Kobo-DevCap-Results.tar.gz](https://github.com/koreader/koreader/files/12077773/Kobo-DevCap-Results.tar.gz) ![20230718_110534](https://user-images.githubusercontent.com/5410392/254191332-d6ccda0d-87d2-404b-bb36-f934256892df.jpg)

FWIW, that *isn't* the standard orientation, that's the "lefty" Portrait ;).

I meant the "righty" orientation (i.e., the Kobo logo on the bottom right).

In any case, the picture should be enough for me to figure it out; and I have a few things to fix before the next round of tests anyway ;).

**Comment by NiLuJe** [comment]
> Now that kernel sources are out, if you wanted a device to work on, just say the word (well, and email me a shipping address). :)

We *should* be able to deal with most things remotely, but I'll keep that in mind if we hit a wall ;). Thanks, though!

(I mean, unless you *really* have a spare device that's doing nothing, in which case... ;p).

**Comment by NiLuJe** [comment]
Okay, this version *should* print a more sensible rotation map, *and* should actually poke at the right input device for the final input test ;).

[Kobo-DevCap-Test.tar.gz](https://github.com/koreader/koreader/files/12084844/Kobo-DevCap-Test.tar.gz)

**Comment by Knut0730** [comment]
How do I put this on my device @NiLuJe ? I will gladly join in to help, but I don't know the process of launching these files on my device...

**Comment by NiLuJe** [comment]
You'll need SSH access (or, well, Nickel's builtin telnet if you're on a budget ;p), which is why I linked to the last time we went over this for the Clara 2E: https://github.com/koreader/koreader/issues/9552#issuecomment-1256555076

**Comment by ezuk** [comment]
> (I mean, unless you really have a spare device that's doing nothing, in which case... ;p).

This would be a new unit I'll just get you - I ended up using the one I bought, it doesn't freeze as often.

**Comment by NiLuJe** [comment]
Well, that's very generous; you can grab my email from any of my GH commits to discuss logistics.

**Comment by ezuk** [comment]
> you can grab my email from any of my GH commits to discuss logistics.

email sent! :)

**Comment by ealex** [comment]
This it the latest Kobo-DevCap-Results file, and a new photo
[02_Kobo-DevCap-Results.tar.gz](https://github.com/koreader/koreader/files/12101930/02_Kobo-DevCap-Results.tar.gz)
![20230720_064045](https://github.com/koreader/koreader/assets/5410392/fd13f3fa-2539-48d3-9ee2-59c208f985df)

**Comment by NiLuJe** [comment]
Okay, that should do it for the screen & touch, thanks.

Now come the gnarly bits...

You'll need [the strace build](http://files.ak-team.com/niluje/mrpub/Other/strace-kobo-r3.tar.gz) I linked earlier, as the one bundled in KoboStuff won't know how to decode the refresh ioctls; so, once you've unpacked that, don't forget to replace the `strace` calls in the linked post to `./strace`, obviously ;).

* First, to confirm how the charging LEDs behave, follow the [second part of this message](https://github.com/koreader/koreader/issues/9552#issuecomment-1256555076).
(Like mentioned at the end, logging to a file may be more practical; it'll be necessary for the next test anyway ;)).
* The main part of the show will be figuring it out WiFi. I'd have recommended doing this over USBNet, but KoboStuff doesn't support switching to USBNet on that device (I'll need to work on that eventually, but that's another kettle of fish).
So, make sure you *disable* ForceWifi if you've enabled it in the previous step, and restart the device for good measure.
Enable Wi-Fi, SSH in, and jot down the output of `lsmod`.
The run `./strace -fittvTyY -e trace=ioctl,write,system -p -o nickel_wifi.log $(pidof nickel) -o &`
Logout, then turn Wi-Fi off. Wait a bit for it to take, then turn Wi-Fi back on. SSH in again, then kill strace (`pkill -TERM strace`), and send me the log file.

Thanks!

**Comment by ealex** [comment]
For the power led:
`[admin@condor bd71828-green-led]# pwd
/sys/class/leds/bd71828-green-led
[admin@condor bd71828-green-led]# ls
brightness      device          max_brightness  power           subsystem       trigger         uevent
[admin@condor bd71828-green-led]# cat trigger 
[none] bd71827_bat-charging-or-full bd71827_bat-charging bd71827_bat-full bd71827_bat-charging-blink-full-solid bd71827_ac-online mmc0 timer 
[admin@condor bd71828-green-led]# echo 255 > brightness 
[admin@condor bd71828-green-led]# echo 0 > brightness 
[admin@condor bd71828-green-led]# 
`
it looks like it's the standard linux led  class - i can make it blink on mmc0 access for example.

and the respective sysctl log:
`
[pid   313] 20:13:16.017448 [b1a5ff44] write(21</mnt/onboard/.kobo/BookReader.sqlite-wal>, "9F\372\370\257\20\261\r\343\364\235M\266\345\312\22\216\37>b4'f\221uj._\376\6\34\34"..., 1024) = 1024 <0.000477>
[pid   313] 20:13:16.024854 [b1a5ff44] write(55</sys/devices/platform/10019000.i2c/i2c-1/1-004b/bd71828-led.2.auto/leds/bd71828-green-led/brightness>, "0", 1) = 1 <0.000692>
[pid   313] 20:13:16.026980 [b1a5ff44] write(55</sys/devices/platform/10019000.i2c/i2c-1/1-004b/bd71828-led.2.auto/leds/bd71828-green-led/brightness>, "1", 1) = 1 <0.000594>
[pid  1101] 20:13:16.031345 [b185c4ec] ioctl(41<socket:[6607]>, FIONREAD, [14400]) = 0 <0.000559>
[pid  1101] 20:13:16.166774 [b185c4ec] ioctl(51<socket:[6612]>, FIONREAD, [31]) = 0 <0.000515>
[pid  1101] 20:13:16.168566 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000511>
[pid  1101] 20:13:16.171577 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000547>
[pid  1101] 20:13:16.207499 [b185c4ec] ioctl(41<socket:[6607]>, FIONREAD, [18720]) = 0 <0.001291>
[pid  1101] 20:13:16.212065 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000113>
[pid  1101] 20:13:16.217072 [b185c4ec] ioctl(41<socket:[6607]>, FIONREAD, [10080]) = 0 <0.000639>
[pid   313] 20:13:16.225732 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000656>
[pid   313] 20:13:16.237287 [b185c4ec] ioctl(3</dev/fb0>, _IOC(_IOC_WRITE, 0x46, 0x2e, 0x24), 0xbef222ec) = 0 <0.003131>
[pid   313] 20:13:16.244608 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid  1101] 20:13:16.245807 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000398>
[pid   313] 20:13:16.247583 [b1854ee4] <... write resumed>) = 8 <0.002679>
[pid   313] 20:13:16.277829 [b185c4ec] ioctl(3</dev/fb0>, _IOC(_IOC_WRITE, 0x46, 0x2e, 0x24), 0xbef222ec) = 0 <0.000543>
[pid   313] 20:13:16.278953 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000347>
[pid   313] 20:13:16.280467 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000523>
[pid   313] 20:13:16.282081 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000354>
[pid  1101] 20:13:16.388654 [b185c4ec] ioctl(41<socket:[6607]>, FIONREAD, [9394]) = 0 <0.000370>
[pid  1101] 20:13:16.390704 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000421>
[pid  1101] 20:13:16.392079 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000416>
[pid  1101] 20:13:16.395412 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000435>
[pid   908] 20:13:16.417342 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000385>
[pid  1101] 20:13:16.549554 [b185c4ec] ioctl(52<socket:[6613]>, FIONREAD, [31]) = 0 <0.000364>
[pid  1101] 20:13:16.550663 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000333>
[pid  1101] 20:13:16.552870 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000415>
[pid  1101] 20:13:17.026867 [b185c4ec] ioctl(41<socket:[6607]>, FIONREAD, [31]) = 0 <0.000372>
[pid  1101] 20:13:17.028027 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000320>
[pid  1101] 20:13:17.029810 [b1854ee4] write(29<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000355>
[pid   313] 20:13:18.775830 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000853>
[pid   313] 20:13:18.798693 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "3", 1) = 1 <0.007344>
[pid   313] 20:13:18.974875 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "2", 1) = 1 <0.007295>
[pid   313] 20:13:19.165388 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "1", 1) = 1 <0.003445>
[pid   313] 20:13:19.357649 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "0", 1) = 1 <0.005801>
[pid   313] 20:13:19.534295 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000845>
[pid   313] 20:13:19.776026 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000598>
[pid   313] 20:13:21.369238 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000893>
[pid   313] 20:13:21.399668 [b1a5ff44] write(41</sys/devices/platform/10019000.i2c/i2c-1/1-004b/bd71828-led.2.auto/leds/bd71828-green-led/brightness>, "0", 1) = 1 <0.000716>
[pid   313] 20:13:21.411898 [b1854ee4] write(8<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000614>
[pid   313] 20:13:21.446307 [b185c4ec] ioctl(3</dev/fb0>, _IOC(_IOC_WRITE, 0x46, 0x2e, 0x24), 0xbef222ec) = 0 <0.003044>
[pid   313] 20:13:21.836339 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "1", 1) = 1 <0.007066>
[pid   313] 20:13:22.203479 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "2", 1) = 1 <0.002859>
[pid   313] 20:13:22.589439 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "3", 1) = 1 <0.007356>
[pid   313] 20:13:22.957160 [b1a5ff44] write(36</sys/devices/platform/ntx_bl/backlight/mxc_msp430.0/brightness>, "4", 1) = 1 <0.013226>
[pid   313] 20:13:22.974473 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.001287>
[pid   313] 20:13:23.775570 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000951>
[pid   313] 20:13:24.807767 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000071>
[pid   313] 20:13:29.778882 [b1854ee4] write(4<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8 <0.000894>
^Cstrace: Process 313 detached

`

**Comment by ealex** [comment]
This is the lmod:
[admin@condor root]# lsmod
wlan_drv_gen4m 1908365 0 - Live 0xbf14a000 (O)
wmt_cdev_bt 16871 0 - Live 0xbf141000 (O)
wmt_chrdev_wifi 12825 1 wlan_drv_gen4m, Live 0xbf138000 (O)
wmt_drv 1058767 4 wlan_drv_gen4m,wmt_cdev_bt,wmt_chrdev_wifi, Live 0xbf000000 (O)
[admin@condor root]# 

and the nickel_wifi.log:
[04_nickel_wifi.log](https://github.com/koreader/koreader/files/12112512/04_nickel_wifi.log)

**Comment by NiLuJe** [comment]
Sorry, I forgot about the module shenanigans, can you re-try the wifi stuff with this updated strace call: `./strace -fittvTyY -e trace=ioctl,write,finit_module,delete_module,%process -o nickel_wifi.log -p $(pidof nickel) &`

**Comment by ealex** [comment]
started the test at 06:26, reactivated the wifi after 06:27
[nickel_wifi.log](https://github.com/koreader/koreader/files/12115997/nickel_wifi.log)

**Comment by NiLuJe** [comment]
Ohkay, perhaps they've stopped unloading the modules at runtime, then?

On the off-chance I missed somethign stupid with the strace args, what does it look like with a *full* strace (i.e., `./strace -fittvTyY -o nickel_verbose.log -p $(pidof nickel) &`).

(That one will be super verbose, but I'll have a definitive answer at last, and I'll probably stop bothering you after that ;p).

**Comment by ealex** [comment]
i've re-enabled the wifi at ~ 08:50 in the log file
ping me whenever you need some extra  test or log

[nickel_verbose.log](https://github.com/koreader/koreader/files/12116762/nickel_verbose.log)

**Comment by NiLuJe** [comment]
I've got a first build to test over on #10719 ;).

(With more tests to run @ealex ;p).
