### ISSUE TITLE
FR: Export notes in current folder

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10402]
**Does your feature request involve difficulty completing a task? Please describe.**

The `Export highlights` feature produces a nicely formatted document when exporting all notes in the library. However, the entire library can be rather large and could contain notes that one would not like to include in the document. Also, if older books are not removed, the old notes are being duplicated every time new notes are exported using the entire library option.

**Describe the solution you'd like**

Allow the additional option `Export all notes in current folder`  in the Tools -> Export highlights menu. This would produce a notes document with all notes/highlights from all books saved in the folder the currently opened book is saved in. 

Subfolders should not be included (or only as an additional option `include subfolders`).

**Advantages:**
- One could produce notes files with just content from books of a certain author/topic/genre etc. if they are organized in separate folders (as probably often already the case for many users)
- One could move specific books to a separate folder in order to get a single notes document with just notes from those selected books
- After all notes have been exported, one could save new books to a separate folder (e.g., /May_2023) so the next time one only has to export the notes from the new folder

**Describe alternatives you've considered**

An alternative would be to allow selection of specific books to export notes to one file, but that would presumably involve a lot more work in the UI and wouldn't necessarily be more user friendly as it would require manual selection of books that may already be organized by folders.

**Comment by poire-z** [comment]
Given that we have a "select mode" (long-press on a file and hit Select), where you can then select additional file with just tap, and have a "Select all" in the top left "checkmark menu", I think there could be an additional button in that checkmark menu to Export notes for the selected books (just talking about the UX, I have no experience with the exporting subsystem).
Feels less cumbersome than having to create subdirectories to move there books to include or exclude from the export :)

**Comment by jonnyl2** [comment]
@poire-z True, that would also be a convenient option. I was more thinking for users who already have their books organized by folders. Then, a one-tap export option (as it currently works for the entire library) would be really cool.
