### ISSUE TITLE
FR: [Add white space between lines when highlighting a quote]

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10416]
**I’ll show you in the photo, when you select a quote, it is merged between the lines there is no free space, as, for example, in Kindle**

**Please add a little space between the highlighted lines, it's much prettier and more aesthetic.**

**Pls add this in new update & color highlights too!
PocketBook 633 Color**

![IMG_20230510_203658.jpg](https://github.com/koreader/koreader/assets/119916135/3b35fec4-7f3a-4ce6-a6f6-18a4aadcbf9d)

**Comment by hius07** [comment]
Maybe it makes sense

![1](https://github.com/koreader/koreader/assets/62179190/3fa73a2a-0f86-4aa1-9f23-8b546ef83420)

**Comment by ZHANYLone** [comment]
> Maybe it makes sense
> 
> ![1](https://github.com/koreader/koreader/assets/62179190/3fa73a2a-0f86-4aa1-9f23-8b546ef83420)
> 

How did you do that? I don't get it...
Why is my book not like this? 
I'm from Kazakhstan and sometimes I read books in Russian, like in my photo.

**Comment by hius07** [comment]
> How did you do that? I don't get it...

It is not implemented yet (until discussed and approved by the developers).

**Comment by ZHANYLone** [comment]
> > How did you do that? I don't get it...
> 
> It is not implemented yet (until discussed and approved by the developers).

It's a perfect idea. But maybe add some more space between lines

**Comment by offset-torque** [comment]
@hius07 
As a heavy highlighter I want to give my opinion. Actually we currently have this feature as a side effect in PDFs. Here is a real example of  how it looks like from an article I am reading now:
![Reader_2023-05-10_182020](https://github.com/koreader/koreader/assets/84420582/c425892a-dd8b-4bf1-be08-d313bcc4a045)


This is not readable at all. All those lines clutter the text and turns it into a giant barcode. "Space between lines" proposal might look nice in some combinations of font height/font metrics/line spacing. In other cases it will degrade text legibility by disrupting the outlines of letters and words. So it shouldn't be implemented as the "default" view.

**Comment by NiLuJe** [comment]
FWIW, it's definitely awful with a full invert like on PDFs, as @offset-torque just showed, but I *also* don't really like it with CRe milder gray highlight ;).

**Comment by poire-z** [comment]
A few thoughts:
- crengine own drawing of the highlight (while it is being made) would always stay as it is - only the drawing of past highlights by our frontend code could possibly be tweaked, as @hius07 did it I guess
- I like (like most of our users I guess) our current behaviour, and I find it a feature vs. the classic "with space in between" web browsers (and possibly other ereader software) do:
![image](https://github.com/koreader/koreader/assets/24273478/f9322d86-f1c6-49c3-90a8-b2138419646b)

- I assume @hius07 did as you did for other highlight styles: work with the full-line rectangles, and draw a line a the bottom or in the middle - so I guess the trick would be to draw the rectangle (gotten from crengine) with trimming some pixels at top and at bottom
- with doing that, there's always the risk with some font and CSS combinations we won't have the text centered in the highlight (this may happen only on the first or last line with our current mulitline single block highlight - but with all our single line highlight, but less noticable as we use the full rectangle height). So, it shouldn't be the default, and the pixel trimming should stay minimal
- but maybe the amount of trimming could be made dependant on our Line Spacing bottom widget value, to answer "But maybe add some more space between lines", assuming one will need to increase the line spacing to get the room
- but the line spacing can already be big in the book with our value at 100%, so one may still get too thick bars...
- so yes, it will be hard to get something that will look nice by default - even if we give a "Set thickness % for highlights", a user may have to tweak it per book, or even per sections in a single book...
- not much thoughts about PDF, where we have no control or knowledge of the interline
- so I agree it's hard to propose something that we can't ensure will most of the time look nice

So, may be best left as a user patch of `ReaderView:drawHighlightRect()` ? May be you could quickly make one with your text code @hius07 ?

**Comment by ZHANYLone** [comment]
> Maybe it makes sense
> 
> ![1](https://github.com/koreader/koreader/assets/62179190/3fa73a2a-0f86-4aa1-9f23-8b546ef83420)
> 

I remembered that, by the way, in Kindles, the line spacing looks very nice
