### ISSUE TITLE
Marking the current position in the book chapter

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10419]
* KOReader version: 2023.04
* Device: PocketBook 633 Color

#### As you can see in my photo, the position mark in the book and chapter is out of sync with the actual correct position in the book chapter. It's late, stays where it is. Only when I go to the file manager and go back, it gets to the right place. But if I'm not it's late. 

p.s. I'm not a programmer, so it would be better if you fix this bug yourself, for example in a future update. Thank you, I really love your app

![IMG_20230511_115719.jpg](https://github.com/koreader/koreader/assets/119916135/86a92e48-b956-43de-bf38-546eef31d179)

**Comment by Frenzie** [comment]
What happens if you do a full refresh (diagonal swipe from corner to corner)?

**Comment by ZHANYLone** [comment]
> What happens if you do a full refresh (diagonal swipe from corner to corner)?

It works, thank you. But do I have to do it all the time? It is desirable that it be automatically. And yet, I don’t know how to use touch and gestures, can I turn on only this one refresh function? And how to understand the diagonal swipe? Can you explain. From where to where?

**Comment by Frenzie** [comment]
I don't know why the marker wouldn't update if the letters do, but that just part of trying to figure out what the problem is. "The marker is positioned incorrectly" and "the screen didn't update when expected" are fairly different. :-)

Maybe @NiLuJe has an idea, but if not you can always set a higher refresh frequency in settings → device → screen.

**Comment by ZHANYLone** [comment]
> Is Gear -> status bar -> settings -> autorefresh enabled?

Yes

**Comment by dcruzbosco** [comment]
@ZHANYLone, are you referring to the little black arrow in the status bar in the region you have circled?

**Comment by NiLuJe** [comment]
Umm, it's not *supposed* to move, it's a "start of session" marker, not a "you are jere" marker (as that would be where the fillbar ends ;)).

If autorefresh actually repositions the session marker, that'd be a bug.
