### ISSUE TITLE
Mouse input does not respect output scaling on wayland

### ISSUE THREAD

**Issue by hrdl-github** [koreader/koreader#10420]
* KOReader version: 2023.04
* Device: Surface Go (mainline Linux), PineNote (both sway and plasma-wayland with the wayland backend)

#### Issue
Output scaling is taken into account for touch input, but not for pointer-based input. ac93e1a8d already contains a rant about output scaling -- I'm mostly curious about an opinion whether this is a KOReader issue or an SDL issue. plasma-wayland and sway are consistent in this regard: the relevant wayland events contain the unscaled coordinates for all types of events.

#### Steps to reproduce
1. Use output scaling on wayland (e.g. `swaymsg output * scale 2`)
2. Generate pointer-based (e.g. mouse or pen) input events

**Comment by Frenzie** [comment]
Wayland or SDL, works fine on macOS.

**Comment by Frenzie** [comment]
Regarding SDL things may differ fairly significantly between versions btw. Hopefully normally for the better. Incidentally, this commit from 2 days ago sounds relevant?

https://github.com/libsdl-org/SDL/commit/785b7c66365c600fd988964432549cae0040a486

**Comment by Frenzie** [comment]
I see you added something about fullscreen in the meantime; I never tested that on macOS and possibly not on Wayland either. You'll have to be more detailed as to the precise steps to reproduce the problem in that case.

**Comment by Frenzie** [comment]
Yes, I was referring to SDL_VIDEODRIVER=wayland

**Comment by Frenzie** [comment]
My bad, I hadn't noticed that Plasma Wayland had reset itself to "100%". I mistakenly thought it was at ~130%.

**Comment by Frenzie** [comment]
PS On macOS the problem is identical. Apparently I either didn't test it well enough or I messed it up while refactoring a bit.

**Comment by Frenzie** [comment]
Haha nice, that'll save me some effort. :-)
