### ISSUE TITLE
Entire app is cut off on the bottom

### ISSUE THREAD

**Issue by redstonekasi** [koreader/koreader#10422]
* KOReader version: v2023.04
* Device: OnePlus Nord (avicii), LineageOS May 11, 2023

#### Issue
The entire app is rendering into the bottom of the screen, when rotated to landscape this is instead on the right. Everything, including the keyboard, the bottom menu, the file list and the text reader itself is like this.

#### Steps to reproduce
Launch KOReader

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/11454971/crash.log)

**Comment by NiLuJe** [comment]
Dupliocate of #9446
