### ISSUE TITLE
is there any way to increase or reduce the margins and fit width the page of the pdf ?

### ISSUE THREAD

**Issue by konos93** [koreader/koreader#10421]
hello
i read black and white pdf with images

i press the button on the middle and see the window
page grop
margin
auto straighten 

i change margin and it is not work , they dont reduce or increase the left and right margins

is there any way to increase or reduce the margins and fit width the page of the pdf ?

**Comment by offset-torque** [comment]
1. From the bottom menu change `Page crop` to `Semi-auto` or `Manual`
2. KOReader will enter the **full page view** to define crop area
3. Define the boundaries of your page by touching the corners of your text on the page

This way you can get rid of the white space around your text and fit it to your screen

**Comment by poire-z** [comment]
Referencing some possible issues/bugs with the way all this works: https://github.com/koreader/koreader/issues/4255#issuecomment-1465283273

**Comment by konos93** [comment]
![a](https://github.com/koreader/koreader/assets/18540037/e686699f-6b36-4859-9904-ff8c6375efff)

in the pdf i use to read all the odd pages have one size and the even have one another
to be honest i want to reduce the screen and rescale fit width all the images inside the white margins .
here is page crop-semi auto ,auto  margins - 1.50 ,fit to width ,zoom to all page (the first one)

**Comment by konos93** [comment]
in the pdf i use to read all the odd pages have one size and the even have one another
to be honest i want to reduce the screen and rescale fit width all the images inside the white margins .
here is page crop-semi auto ,auto margins - 1.50 ,fit to width ,zoom to all page (the first one)
![a](https://github.com/koreader/koreader/assets/18540037/cc9b6809-0566-4068-a811-72cd4d64ff1a)

**Comment by konos93** [comment]
ok to be honest i found the feature with the margins helpful
