### ISSUE TITLE
No settings persist.

### ISSUE THREAD

**Issue by redstonekasi** [koreader/koreader#10423]
* KOReader version: v2023.04
* Device: OnePlus Nord (avicii), LineageOS May 11, 2023

#### Issue
Setting the HOME folder does not persist through restarts, neither do any other settings, such as night mode.

#### Steps to reproduce
 - Set HOME folder
 - Restart KOReader
 - See that it has not saved the change.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/11454992/crash.log)

**Comment by pazos** [comment]
> Restart KOReader

```
05-11 19:43:55.457 I/KOReader(17078): Engine thread destroy requested!
05-11 19:43:55.457 I/KOReader(17078): Preparing to quit UIManager
05-11 19:43:55.457 I/KOReader(17078): Tearing down UIManager with exit code:
[...]
05-11 19:43:56.999 W/KOReader(27314): LuaSettings: Failed reading /storage/emulated/0/koreader/settings.reader.lua (probably corrupted).
```

You probably killed KOReader without a clean exit using the menu.
Try to reproduce using the menu to exit KO after changing some setting.

Settings aren't flushed inmediatly. Given you **must** put the program in the background to be able to kill it that would led to eventually flush the settings, but android is a whole mess and not all vendors/versions/... signal activity lifecycle states the same way.

Last time I've checked (a few years ago) it worked correctly on my test rig, but we cannot guarantee it behaves the same way now.

If it happens on all devices I can give it a 2nd look now. Until confirmed I'm going to label it firmware dependant.

If somebody wants to try on other devices here're my expected results:

1. Apply changes, clean exit the program, open again (settings saved)
2. Apply changes, switch between reader and filemanager (settings saved)
3. Apply changes, put the app in the background, put the app in the foreground, kill it and open it again (?)
4. Apply changes, kill the app and open it again (?)

Both 1 and 2 should work on all devices. 3 and 4 I dunno

**Comment by pazos** [comment]
No response. Closing

**Comment by redstonekasi** [comment]
I am very sorry for not providing you an answer. Yes, that was indeed the issue. I just wasn't used to closing the app through the menu since, on my old device, it used to save everything even when not exiting it gracefully. Thanks for the help.
