### ISSUE TITLE
Error open fb2 in zip-archive

### ISSUE THREAD

**Issue by PalachMB** [koreader/koreader#10435]
* KOReader version: 2023.03-2023.04
* Device: Kobo Clara HD / Android Phone

#### Issue

The application does not open fb2 files in zip archives if the archive name does not contain .fb2.
For example, fb2 archive "mybook.zip" will not be opened by the application, it will not open if the file is renamed to "mybook.fb2.zip"

#### Steps to reproduce
Just try it

**Comment by hius07** [comment]
It's by design.
To open fb2.zip: long-press the file - Open with... - CoolReader Engine.
