### ISSUE TITLE
FR: "Book time to read" depending on the actually read pages

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#10436]
I've noticed that the "book time to read" in the book statistics depends on the current page. Given that some pages or chapters/articles may have been skipped during reading, or may have been scheduled to be read later, I think it would be more accurate if the "book time to read" depended on the number of actually read pages.

What do you think?

**Comment by NiLuJe** [comment]
> I've noticed that the "book time to read" in the book statistics depends on the current page.

What makes you think that?

(Spoiler alert: it doesn't, it's based on your actual reading history.... in *that specific book*. So, yeah, if you chekc it on the first page of a book, it has no meaningful history to pull from and will do its best based on your time-per-page thresholds).

**Comment by poire-z** [comment]
I do think it's based on the current position. Isn't it just pages left to read in the book divided by the mean time spent per page ?
Which is totally fine by me. I don't think that if I skipped the first half of the book, and I'm at the end of the second half having read if for 2 hours, it should tell me that book time to read is another 2 hours. I'm fine if it tells me 5 minutes. (But ok, I read books linearly - dunno how common it is to not :).
It might also be more computing intensive if we need each time it is displayed (in the footer?) to know how many distinct pages have been read.

**Comment by NiLuJe** [comment]
Oh, yeah, I misunderstood OP. (I read that as "time spent on the current page") ;p.

**Comment by ichnilatis-gr** [comment]
Let me give you another idea (if it is feasible): How about having the ability to define a range of pages (or specific chapters) that should be excluded from the pages to be read, as far as statistics are concerned? This would allow us to remove various appendices and tables that are usually found at the end of the book or chapters. Otherwise "book time to read" will only apply to literature books.
It could allow various ranges: e.g. 125-130, 245-256...

It may be very complicated to accomplish. I don't know. I'm just making a suggestion as an idea... Otherwise just forget it... :-)

**Comment by ichnilatis-gr** [comment]
Fine, but this thread was closed by its author (@jonnyl2) due to other similar ones going on at that time, but nothing happened in the meanwhile. So, is it not feasible or has it been forgotten?

**Comment by poire-z** [comment]
> but nothing happened in the meanwhile.

But many other unrelated things happened in the meawhile :)

> So, is it not feasible or has it been forgotten?

Not forgotten. It's complicated - so it needs time, energy, interest, and bright ideas (so the implementation get to be less complicated that what it would be if we'd jumped at it right now without such bright ideas).

**Comment by ichnilatis-gr** [comment]
Very well! So, I leave it to you to close this thread if you think there is no point in it being open.
