### ISSUE TITLE
Highlighting using stylus input causes SDL to terminate KOReader

### ISSUE THREAD

**Issue by hrdl-github** [koreader/koreader#10443]
* KOReader version: 2023.04
* Device: PineNote (Arch Linux): sway (affects both wayland and x11 SDL backend)

#### Issue
I was using the pen tool to highlight a PDF file that I got from https://en.wikipedia.org/w/index.php?title=Special:DownloadAsPdf&page=Mathematical_formulation_of_quantum_mechanics&action=show-download-screen. I can reliably cause KOReader to quit by performing a selection in said file using a stylus input. I cannot using touch input. I'll see if I can reproduce this using a regular mouse later or another tablet device. The log shows that an Alt-F4 triggers the shutdown. This one is triggered by https://github.com/koreader/koreader-base/blob/e2778f3863136c5b885c8ba560ea603bb699abc7/ffi/SDL2_0.lua#L503 in turn, which is probably sent by SDL, as I did not see any relevant wayland events. Disabling the handling of the event causes the window to close without the process terminating.

Have you seen anything like this before? I can start debugging this sometime this week.

#### Steps to reproduce
1. Open document
2. Use stylus to start selection, change selection by moving the stylus a lot for a few seconds
3. Witness KOReader terminating

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/11478802/crash.log)

**Comment by Frenzie** [comment]
What concretely do you mean by reliably and what do you do precisely? I've been randomly moving my pen around while in selection as well as selecting some individual words and whatnot and nothing unexpected happens for me.

**Comment by Frenzie** [comment]
Is there some kind of pen gesture to close an app?

**Comment by NiLuJe** [comment]
> Disabling the handling of the event causes the window to close without the process terminating.

I'd be curious about seeing the logs of that specific behavior ;o).

**Comment by NiLuJe** [comment]
Also, were the `debug.traceback()` calls at the end something you added, and if so, where?

**Comment by NiLuJe** [comment]
> Are you still interested in a full log, i.e. a mixture of wayland and koreader output?

Seems like you pinned it down, but, yeah, more data is always fun :).

**Comment by Frenzie** [comment]
It's that much chattier than finger gestures?

I'd also be interested in a profiler run on that.

**Comment by Frenzie** [comment]
> So am I. Do you have any pointers on that? I haven't profiled lua code before.

In a case like this just running something like `./luajit -jp reader.lua` might potentially yield interesting results.

If you want to get more detail somewhere you can put something like:
```lua
require("jit.p").start()
[…]
require("jit.p").stop()
```
around it.

There are also potentially interesting resources over at Löve sometimes for example: https://github.com/2dengine/profile.lua

**Comment by NiLuJe** [comment]
Also keep in mind that the verbose debugging flag is responsible for decoding input events for logging, and that will put a much much higher burden on input storms than a standard non-logging release build ;).

**Comment by Frenzie** [comment]
That's an excellent point. Similarly, the release binaries are also faster than the debug binaries, though that impact should be less pronounced here than in document loading/rendering times.

**Comment by NiLuJe** [comment]
> I imagine the seven layers of indirection involved in our SDL waitForEvent implementation + SDL's own internal wayland shenanigans make the whole thing slightly more funky to deal with than the native evdev loop ;o).

In particular, I have no idea how much writing a custom polling loop based on `SDL_PeepEvents` would help; with the idea being to be able to drain *a lot* of SDL events in a single call (similar to how we [drain ~4K of evdev events](https://github.com/koreader/koreader-base/blob/e2778f3863136c5b885c8ba560ea603bb699abc7/input/input.c#L391-L399) in the native evdev codepath).
