### ISSUE TITLE
KOReader can't start on pocketbook inkpad 4

### ISSUE THREAD

**Issue by pattila97** [koreader/koreader#10444]
* KOReader version:  v2023.04
* Device: pocketbook inkpad 4  (PocketBook model PB743g)

Issue
KOReader can't start on pocketbook inkpad 4.

Steps to reproduce

Install KOReader to the device, with SoftwareVersion: U743g.6.8.885 and try to start it.

Instant crash log and then it will close.

crash.log
 [crash.log](https://github.com/koreader/koreader/files/11488206/crash.log)

I am available to test new device support, but I don't know how to add it myself.

**Comment by lorenzlm** [comment]
Same here...

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/blob/710614752dea0ff76ee186f6228e45204e977385/frontend/device/pocketbook/device.lua#L747-L748

For a quick test you could change that line to `elseif codename == "PB740-2" or codename == "PB740-3" or codename == "PB743g" then `. If that seems to work we can go from there.

**Comment by pattila97** [comment]
i added this 2 to the device.lua 3 days ago . So far everything is working fine.

-- PocketBook InkPad 4 (PB743g)
local PocketBookPB743g = PocketBook:extend{
    model = "PBInkPad4",
    display_dpi = 300,
    isAlwaysPortrait = yes,
    usingForcedRotation = landscape_ccw,
    hasNaturalLight = yes,
}

elseif codename == "PB743g" or codename == "PocketBook PB743g" then
    return PocketBookPB743g

[device.txt](https://github.com/koreader/koreader/files/11521747/device.txt)

The battery seems to drain faster with koreader, so I deleted it and see how it is with the basic reader. Maybe there will be no change in the battery.
