### ISSUE TITLE
Screen space assigned to navigation bar not used

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#10447]
* KOReader version:2023.04-44
* Device:Nova3Color (FW 3.3.2, Android 10)

#### Issue
If navigation bar at bottom of the screen enabled, Koreader does not use screen space where bar appears, leaving white or black strip there,
![Screenshot_20230517-085656](https://github.com/koreader/koreader/assets/11670320/8ee09858-6e67-49d3-9f75-6eea1a2df29f)

#### Steps to reproduce

Enable navigation bar in Setting/Gestures/Bottom. Start KOreader. (If one starts KOReader with navigation bar disabled and then enables the bar, the problem does not appear until KOReader is restarted. Correspondingly, if one disables the navigation bar after KOReader is started, the problem does not go away until restart of KOReader.)

**Comment by ilyats** [comment]
Possibly caused by the recent firmware upgrade from 3.3.1 to 3.3.2

**Comment by NiLuJe** [comment]
Possibly related to https://github.com/koreader/android-luajit-launcher/pull/415 then...

Android continues to be awesome to deal with, yay.

**Comment by pazos** [comment]
> Possibly related to [koreader/android-luajit-launcher#415](https://github.com/koreader/android-luajit-launcher/pull/415) then...
> 
> Android continues to be awesome to deal with, yay.

In this case android is fine.

Onyx is broken. You'll need to talk to onyx support and request them to fix their issues.

We just draw a rectangle based on the available size reported by the system.

**Comment by matt08-prog** [comment]
This continues to be an issue on the Nova2, Nova 3 Color, and Boox Palma (https://www.reddit.com/r/koreader/s/IpYwZhnrVY). I have never had this issue with any other applications using the Palma.

I was wondering if there have been any new discoveries related to Onyx devices compatibility with the KOReader? If not then I will contact Onyx again.

Thanks,

**Comment by pazos** [comment]
It should be fixed on latest nightlies, sinze v70, did you tried that, @matt08-prog ?

**Comment by matt08-prog** [comment]
> It should be fixed on latest nightlies, since v70, did you tried that, @matt08-prog ?

Yes, that fixed it. Thank you.
