### ISSUE TITLE
FR: [Image gesture for zoomed images]

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#10445]
When I hold the finger on a image the image is zoomed and to close the image I need to show the panel options and press close.

![zoom](https://github.com/koreader/koreader/assets/4573505/bb000da0-e392-425e-a5c2-51da6ba5feac)

Would be cool some kind of gestures so I can close the image faster without using the panel, such as hold and drag my finger to the left or hold the press again.

Would be useful to read some kind of comics that we want to zoom to have a better or closer look on the frame and you can return quickly and go to the next frame.

**Comment by hius07** [comment]
Swipe down in the middle (6/8) zone of the screen:
https://github.com/koreader/koreader/blob/946f7931ae61d57d465241746de12568f47f51ea/frontend/ui/widget/imageviewer.lua#L567-L571

**Comment by hugleo** [comment]
thanks
