### ISSUE TITLE
terminal plugin : send POST request?

### ISSUE THREAD

**Issue by luutuankiet** [koreader/koreader#10454]
* KOReader version: 2023.04
* Device: kindle PW3

#### Issue
hi, looking into terminal plugin to send a POST request I found that curl seems to be broken and wget with specific busybox version (1.28.3) only supports GET method.

can someone advise how to achieve this? the background is that i have a simple shell script aliased to capture input from terminal and send it to my todo list (ticktick) with a POST request. A perk I used to have done with tasker on android with the Boox while reading with koreader.

#### Steps to reproduce
type `curl` in terminal receives exception `segmentation fault`

type `wget` returns busybox v1.28.3 greetings and manual but dont seem to support POST request in that version

**Comment by poire-z** [comment]
Dunno if @NiLuJe has better curl/wget binaries built for Kindle among its Kindle stuff https://www.mobileread.com/forums/showthread.php?t=225030.

Or you can write your own curl/wget in Lua :) and execute it like the koreader startup script: `./luajit myuploader.lua`. There are some POST request done in:
```
frontend/apps/cloudstorage/dropboxapi.lua
plugins/opds.koplugin/opdspse.lua
plugins/exporter.koplugin/target/joplin.lua
plugins/exporter.koplugin/target/readwise.lua
plugins/wallabag.koplugin/main.lua
plugins/kosync.koplugin/api.json
```

Or, if like I do reading your post, you feel that having to use the terminal is cumbersome, you could create a plugin or a user patch so that when you highlight some text in a book (that you could edit to replace it with your own notes/todo), you get a button and some inputdialog in KOReader to edit the text, and then do the POST to your server.
(I actually do patch my own KOReader to replace "Add note" with my own "add to my own little note service", that do a POST to some CGI script of mine.)

**Comment by luutuankiet** [comment]
thanks for the pointers, gonna check them out!

**Comment by luutuankiet** [comment]
@NiLuJe python package seems like a better alternative. quick look around your archive on mobiread I noticed different python variant (p3, p3g etc) - but no pw3... which variant would be recommend here?

**Comment by NiLuJe** [comment]
Wrong packages, probably. The FW 5.x builds only have two variants, you'll want the pw2+ one, much like KOReader itself.

**Comment by luutuankiet** [comment]
indeed usbhack shipped with curl - just have to install the bin from [NiLuJe's thread](https://www.mobileread.com/forums/showthread.php?t=225030) with mrpackage in kual - thanks!

**Comment by luutuankiet** [comment]
@poire-z this sounds really interesting. may i somehow get a clone of your plugin to mess around with?

> Or, if like I do reading your post, you feel that having to use the terminal is cumbersome, you could create a plugin or a user patch so that when you highlight some text in a book (that you could edit to replace it with your own notes/todo), you get a button and some inputdialog in KOReader to edit the text, and then do the POST to your server.
> (I actually do patch my own KOReader to replace "Add note" with my own "add to my own little note service", that do a POST to some CGI script of mine.)

**Comment by poire-z** [comment]
It's not a plugin, but some patching I do to KOReader at manual update time.
Anyway, I made what I could from it into a "user patch" https://github.com/koreader/koreader/wiki/User-patches.

[2-add2mystuff.lua.txt](https://github.com/koreader/koreader/files/11524453/2-add2mystuff.lua.txt)
Remove the .txt and drop that into koreader/patches.

You'll need to adapt the HTTP request part to what your receiver script/app expects.
This user patch plugs a button into the highlight dialog (with its name `04_add_note` or `20_add2mystuff`, you can replace or order it among existing buttons), and into the external link dialog (so you can post external URLs to your todo list to read these links in a browser later).

My real patch also plugs it into the Dict result window (but this is less essential), and into the screenshoter "Set as screensaver", so I can directly upload screenshots elsewhere (useful when developping, probably not that useful to normal users :)
