### ISSUE TITLE
FR: Extended corner touch area for two-finger tap gesture

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10455]
The two-finger tap corner gesture requires that both fingers touch inside the defined corner touch area, which means that the touch area must be defined relatively large. The large area sometimes interferes with other gestures using the corner and the text, e.g. when long pressing the corner (which I'm aware can be temporarily disabled). 

Would a set-up as sketched below be technically feasible, such that only one finger must touch inside the main corner touch area and the second touch point may fall within an automatically expanded area (suggested size: width and height * 2, but it could be even larger; up to an entire quadrant of the screen)?

The advantage would be that the corner touch areas could be kept small while still taking advantage of the two-finger touch gestures. 

![image](https://github.com/koreader/koreader/assets/95502269/f2e0c683-f439-4b31-9adf-2d563c8bfe62)

**Comment by Frenzie** [comment]
To be clear, it already works that way. Only one finger needs to be within the area. The other one just shouldn't be too far outside it or the average will be outside too.

**Comment by jonnyl2** [comment]
I see; so it depends on the average of the two points. Thank you for clarifying this. I had the touch areas defined just large enough for one finger (5% each direction on a 7.8" screen), so the second finger would fall much further outside this area and I could never get the two-finger gestures to work. I just assumed both fingers had to be within the area. 

This probably complicates things a bit, am I right? Or is it still possible to code it so that only one finger needs to be in the area? (It wouldn't be a big deal if not, but I'd rather not enlarge the touch areas.)

**Comment by NiLuJe** [comment]
Yeah, two-finger gestures use the midpoint as the effective coordinates, it doesn't matter whatsoever were the actual fingers are relative to the zone.

**Comment by NiLuJe** [comment]
If you wanted to enforce a "one contact ought to be inside" approach, we'd have to attach extra metadata to the gesture to store the coordinates or both contacts, and do something with it.

I... no. ;p.

**Comment by jonnyl2** [comment]
Understood :) Thank you all for your help.
