### ISSUE TITLE
Removed PDF highlight permanently deteriorates PDF text

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10456]
* KOReader version: 2023.04-44
* Device: Onyx Boox Kon-Tiki 2

#### Issue
Removing a written PDF highlight leaves the original text of slightly lighter color. 

#### Steps to reproduce
I was in the midst of texting Exporter plugin. 
I highlighted a sentence in PDF.
Hit Share in the Exporter. It crashed. 
Returned to KOReader, highlight is not there as expected since I believe it crashed before writing the highlight to file. 
Highlighted again, exited KOReader, returned, highlight is there, exported it without the plugin. 
Then removed the highlight, as noticed that the original text is now lighter.

##### `crash.log` (if applicable)
(I don’t have the device on me right now, I’ll add logs later)

**Comment by hius07** [comment]
What is your setting "Save document (write highlights into PDF)"?
Do you see anything in the place in other pdf viewers (IIRC SumatraPDF shows saved highlights in yellow)?

**Comment by mergen3107** [comment]
IIRC, it was on “save upon exit” all that time. 

Will check the PDF on PC later too. 

Thank you!

**Comment by poire-z** [comment]
I remember having written about that (highlights various opacity, because doubling up or not), so sharing them:
https://github.com/koreader/koreader/issues/8084#issuecomment-899471911
https://github.com/koreader/koreader/issues/7928#issuecomment-879859250 and follow ups

**Comment by mergen3107** [comment]
> What is your setting "Save document (write highlights into PDF)"? Do you see anything in the place in other pdf viewers (IIRC SumatraPDF shows saved highlights in yellow)?

1) Setting was Always, and book metadata saving only on close and suspend. 

2) Yes, I see the yellow highlight in the Foxi Reader on PC. The problem is that if I remove the highlight, and put it back to KOReader, the reading statistics thinks this is a new book and starts a new entry.

So for now I just disabled the highlight writing into PDF, and just keep highlights in KOReader. 

However I must say this is weird: shouldn’t KOReader be removing the yellow highlights as well when removing KOReader-highlight?

**Comment by mergen3107** [comment]
> 2\. The problem is that if I remove the highlight, and put it back to KOReader, the reading statistics thinks this is a new book and starts a new entry.

Sorry, I retract. The edited file is the same, I must have been playing with multiple files back then. All good now!
