### ISSUE TITLE
v2023.04 from v2021.05 for device KindlePaperWhite3  cant start koreader

### ISSUE THREAD

**Issue by konos93** [koreader/koreader#10467]
i tried to drag n drop version v2023.04 from v2021.05 for device KindlePaperWhite3 

 [*] Current time: 05/20/23-05:11:15
 [*] Version: v2023.04

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
05/20/23-05:11:15 INFO  initializing for device KindlePaperWhite3 
05/20/23-05:11:15 INFO  framebuffer resolution: {
  h = 1448,
  w = 1072
} --[[table: 0x4040e6e0]] 
[ko-input] Forked off fake event generator (pid: 2843)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
05/20/23-05:11:16 INFO  Performing one-time migration for 20210622 
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
./luajit: ./ffi/zstd.lua:41: Failed to allocate ZSTD decompression buffer (1.844674407371e+19 bytes)
stack traceback:
	[C]: in function 'assert'
	./ffi/zstd.lua:41: in function 'zstd_uncompress'
	frontend/persist.lua:127: in function 'deserialize'
	frontend/persist.lua:227: in function 'load'
	frontend/fontlist.lua:173: in function 'getFontList'
	frontend/ui/font.lua:157: in main chunk
	[C]: in function 'require'
	frontend/apps/reader/modules/readerfooter.lua:7: in main chunk
	[C]: in function 'require'
	frontend/ui/data/onetime_migration.lua:226: in main chunk
	[C]: in function 'require'
	./reader.lua:193: in main chunk
	[C]: at 0x00013e9d
lipc-wait-event exited normally with status: 0

**Comment by konos93** [comment]
thank you 

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

**Comment by NiLuJe** [comment]
Another contender for #10429, except this one might genuinely make sense, so, yay? ;o).
