### ISSUE TITLE
Koreader crashes on Share all notes in this book to any format

### ISSUE THREAD

**Issue by 672493** [koreader/koreader#10463]
* KOReader version: 2022.11-2023.04 (latest nightly build too)
* Device: Samsung Galaxy note 10 plus, Xiaomi Redmi note 9s note, Onyx boox Kontiki 2

#### Issue
Koreader crashes on "Share all notes in this book" to any format. Export works fine. Sharing of a single highlight also works fine. This bug persists since v2022.11. The last version which worked fine is 2022.10. I may suppose that the problem is probably in the code here https://github.com/koreader/koreader/commit/3530aef891da01125fe08f5576a96cb92ffee2c7 (but I'm not sure). I'm really surprised, that nobody yet reported this problem. I thought that this is some local problem with my phone, but I have it on 3 very different devices (Samsung Galaxy note 10 plus, Xiaomi Redmi note 9s note, Onyx boox Kontiki 2), two of which are even not mine and have absolutely different settings. 
#### Steps to reproduce
1. Open a book. 
2. Highlight some text. 
3. Choose export highlights - share all notes in this book - share as (markdown, html, text, doesn't matter).
4. App crashes immediately. 

##### `crash.log` (if applicable)
Unfortunately no `crash.log` is being saved (verbose debug logging is checked), and koreader crash handler doesn't seem to have any relevant info.

**Comment by mergen3107** [comment]
Duplicate:
https://github.com/koreader/koreader/issues/9988

**Comment by Frenzie** [comment]
Thanks for the report! Closing in favor of the other one.
