### ISSUE TITLE
Android: can't see half of the bottom bar

### ISSUE THREAD

**Issue by BoBoFunKy** [koreader/koreader#10474]
* KOReader version: 2023.04 and older
* Device: Xiaomi 11t pro

When opening any file I can't get it paged or get the borders removed by using the bottom bar, the only thing possible is rotating the page.
I can't really use the app in this state.

**Comment by NiLuJe** [comment]
Assuming you're running Android 13, this ought to be fixed via #10439

(Dupe of #9446)

**Comment by whatever4kindle** [comment]
The fix doesn't work as of 2025.08
