### ISSUE TITLE
FR: Select one of multiple overlapping highlights

### ISSUE THREAD

**Issue by ryanwwest** [koreader/koreader#10482]
### Discussed in https://github.com/koreader/koreader/discussions/10480

<div type='discussions-op-text'>

<sup>Originally posted by **ryanwwest** May 24, 2023</sup>
Sometimes, I want to highlight the same text multiple times (e.g. highlight an entire paragraph with 'lighten' style to pay attention to it, then highlight a few words inside the paragraph with 'underline' style with a note). This is supported in the `.sdr` Lua file and displays, but I can only select one of the two highlights after creating them. 

![image](https://github.com/koreader/koreader/assets/31378238/19919606-c6e7-461a-88d4-f73ceebe193e)
</div>

From @hius07, who suggested possibly having a popup menu to select which highlight to choose, if there are multiple choices:

> Tapping the overlap region shows the popup menu for the highlight made first (usually, sometimes can be the second - depending on the highlights configurations/overlaps).
Adding a note to or deleting a highlight made second can be done via the Bookmarks list.
Changing a style or boundaries for the second highlight is impossible currently.
> 
> Technically: we stop searching the highlight containing the touch coordinates after the first found entry.
**Maybe it is worth to continue searching in all the highlights and show a popup menu with all highlights found.**

**Comment by ryanwwest** [comment]
Thank you!

**Comment by hius07** [comment]
It's a pleasure.
