### ISSUE TITLE
Some problem with zip files

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10484]
* KOReader version: Latest 2023.04
* Device: PocketBook Color 633

#### I have fb2.zip files that are simply .zip files with fb2 inside (renamed)
I have this problem: As in my photo, it says I need an engine to view the zip file or something like this. I just wanted to see the book's metadata, or rather the cover. Without opening the book itself, only the cover as in the menu. But it became impossible, writes the engine is necessary. Where to download it? I'm not a programmer, I don't understand how to fix it. I needed to display the cover in full screen to make a TikTok video with a selection of books - I am a book blogger.

![IMG_20230525_204123.jpg](https://github.com/koreader/koreader/assets/119916135/c7139e62-85c9-48d0-9ae5-5bb111bbf51f)

```
Please fix this in future patches. I love your program, by the way, I'm from Kazakhstan.

**Comment by hius07** [comment]
Can you rename the books to book-name.fb2.zip?

**Comment by ZHANYLone** [comment]
> Can you rename the books to book-name.fb2.zip?

I think it's impossible for me
I have 3000+ books in zip format
5 years library

**Comment by hius07** [comment]
If you have access to the KOReader folder on your device, change 10 to 50 in the line
https://github.com/koreader/koreader/blob/d54c5acc11f1d6293dcf4977c73cb7a4101b9069/frontend/document/credocument.lua#L1543
restart KOReader, tap upper right Plus icon in the home screen and select Extract and cache book info.

**Comment by poire-z** [comment]
Can't he just long-press on the zip file, choose "Open with...", select crengine, and check "always use for this file type" ?
![image](https://github.com/koreader/koreader/assets/24273478/22b3fdbb-1051-417f-9c6b-41258e5134c5)

**Comment by ZHANYLone** [comment]
> Can't he just long-press on the zip file, choose "Open with...", select crengine, and check "always use for this file type" ?
> ![image](https://github.com/koreader/koreader/assets/24273478/22b3fdbb-1051-417f-9c6b-41258e5134c5)
> 

It's only open & read file. But I need just a cover of zips shown in the file manager. And for this task it doesn't show the covers of zips, but open - yes

**Comment by ZHANYLone** [comment]
> If you have access to the KOReader folder on your device, change 10 to 50 in the line
> https://github.com/koreader/koreader/blob/d54c5acc11f1d6293dcf4977c73cb7a4101b9069/frontend/document/credocument.lua#L1543
> restart KOReader, tap upper right Plus icon in the home screen and select Extract and cache book info.

It's working
But I didn't. Cause for all my books it will take 3 hours to be done
So sad
I don't want to wait 😭
Thank you

**Comment by ZHANYLone** [comment]
> If you have access to the KOReader folder on your device, change 10 to 50 in the line
> https://github.com/koreader/koreader/blob/d54c5acc11f1d6293dcf4977c73cb7a4101b9069/frontend/document/credocument.lua#L1543
> restart KOReader, tap upper right Plus icon in the home screen and select Extract and cache book info.

Thank YOU
IT'S WORKING

**Comment by ZHANYLone** [comment]
> If you have access to the KOReader folder on your device, change 10 to 50 in the line
> https://github.com/koreader/koreader/blob/d54c5acc11f1d6293dcf4977c73cb7a4101b9069/frontend/document/credocument.lua#L1543
> restart KOReader, tap upper right Plus icon in the home screen and select Extract and cache book info.

I did it one time, but after update ⬇️

After the update (today, Snowy Summit version) - I see that ZIP files don't work again, I had to change the same lines again in the same document.

Is it possible to do something so that even after the update and in general, this document with these lines does not change?

 I would be very grateful for your help!

**Comment by hius07** [comment]
Userpatch
[2-zip-crengine-provider.lua.txt](https://github.com/koreader/koreader/files/13998801/2-zip-crengine-provider.lua.txt)

**Comment by ZHANYLone** [comment]
> Userpatch
> [2-zip-crengine-provider.lua.txt](https://github.com/koreader/koreader/files/13998801/2-zip-crengine-provider.lua.txt)
> 

Put it in a folder 

applications/koreader/patches

And done? Right?
Need to remove txt extension or not?

**Comment by NiLuJe** [comment]
> Need to remove txt extension or not?

Yes

**Comment by ZHANYLone** [comment]
> Userpatch
> [2-zip-crengine-provider.lua.txt](https://github.com/koreader/koreader/files/13998801/2-zip-crengine-provider.lua.txt)
> 

Thank you all guys very very much! It's working 😍😍😍
