### ISSUE TITLE
FR: Partial screenshots

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10483]
**Does your feature request involve difficulty completing a task? Please describe.**

Sometimes one only wants to take a screenshot of a part of the screen (e.g., a graph or a table on a page). A screenshot of the whole screen then needs to be cropped in an external program. Dedicated e-readers usually don't have an image editor, so this means a different device as well.

**Describe the solution you'd like**

Add an extra option to gestures named `Screenshot (area)` (or similar), which allows the selection of a rectangle on the screen. As such a selection tool is already available in the page crop settings, this might be adaptable for screenshots as well.

**Describe alternatives you've considered**

Alternatively, allow the option to crop the image after it has been saved:

Via a button in the pop-up window:

![IMG_20230524_165928](https://github.com/koreader/koreader/assets/95502269/2dc0744d-acbb-438b-b3cb-4e3f7bee189f)

And/or a button in the image viewer:

![Screenshot_20230524_170037_org koreader launcher_1_1](https://github.com/koreader/koreader/assets/95502269/d55ac578-4006-4e1a-a474-483ef0d3ec09)

**Comment by NiLuJe** [comment]
That's a lot of UX (and potentially code) for a niche feature ;).

**Comment by jonnyl2** [comment]
OK, thanks for the feedback. I'll close it.

**Comment by gd4c** [comment]
> That's a lot of UX (and potentially code) for a niche feature ;).

Shouldn't page crop logic and UI do most of the heavy lifting? This feature is useful for sharing quotes.
