### ISSUE TITLE
FR: Keyboard Shortcuts for Search

### ISSUE THREAD

**Issue by ryanwwest** [koreader/koreader#10499]
It would be nice to have a physical keyboard shortcut for searching in two places:
1. When a file is open, as an alternative to clicking on upper settings menu -> magnifying glass -> fulltext search
2. When in the file browser, as an alternative to clicking on upper settings menu -> magnifying glass -> file search

This is particularly nice since if you already have an external keyboard, you can just keep typing on it without needing to tap/use mouse after pulling up the corresponding search utility.

I think the shortcut could be the same for both cases since they are mutually exclusive (and is logical anyway). Cmd-F for Mac and Ctrl-F for Linux (and Windows via WSL) seem to be the most universal.

Additionally, if the (external) keyboard shortcut is used to invoke either search utility, then I think it's pretty much guaranteed that the user can and wants to continue typing on their external keyboard and not use the built-in virtual one. Therefore, when this happens it would be nice if the virtual keyboard were automatically hidden when typing into the search utility. This logic of course could apply outside of this scenario as well, but might require more complexity to detect when an external keyboard is available and preferred over the virtual one. So I'd opt for just changing it for this case for the moment, unless more complex logic is already built-in.

As a final question, https://github.com/koreader/koreader/wiki/Keyboard-navigation indicates that only the Linux build supports shortcuts (though Mac does as well) - does that mean no shortcuts work on Android even though external keyboards can be attached?

**Comment by pazos** [comment]
> As a final question, https://github.com/koreader/koreader/wiki/Keyboard-navigation indicates that only the Linux build supports shortcuts (though Mac does as well) 

Technically it works on any sdl target but mac builds are not supported, there're no binary packages and none of the recent vms available on github actions produce a working app bundle. I would leave the wiki as is but a change that says

> SDL targets, such as [desktop Linux](https://github.com/koreader/koreader/wiki/Installation-on-desktop-Linux) of KOReader implement keyboard shortcuts for navigating the user interface and reading books.

Is cool too. Feel free to change it :)

> - does that mean no shortcuts work on Android even though external keyboards can be attached?

Yup, we're still waiting for a contributor in https://github.com/koreader/android-luajit-launcher/issues/338

**Comment by ryanwwest** [comment]
Thanks for answering the question! I'll monitor the other thread.

**Comment by ryanwwest** [comment]
Could someone direct me to where other keyboard shortcuts are defined in the code (if it's simple)? Adding the basic search functions above seem perhaps trivial enough that I could do it. Hiding the virtual keyboard, on the other hand, is probably too complex for me for now (and probably requires a debate first anyway).

**Comment by ryanwwest** [comment]
FWIW, aside from PDF reflow causing constant crashes in macos, it is surprisingly nice to use as a Desktop reader. Especially for ePUB since there are few good desktop apps, but even for PDFs because of the dark mode rendering, and accessible since you can set KOReader as the default app for opening all these filetypes.

**Comment by ryanwwest** [comment]
@pazos With https://github.com/koreader/koreader/pull/10945 nearing close to merging (I think), I was thinking of implementing the following from this FR:

> I think the shortcut could be the same for both cases since they are mutually exclusive (and is logical anyway). Cmd-F for Mac and Ctrl-F for Linux (and Windows via WSL) seem to be the most universal.

Though I'd probably also map `/` to search since that is also pretty universal and more friendly for keyboards without modifier keys. And I might suggest adding a few other desktop-friendly shortcuts too and implement if there's support.

I wanted to make sure this would be okay before I dive into a PR.

**Comment by poire-z** [comment]
Just thought about hitting Ctrl-F (implemented for Alt-F in #4720 by @Frenzie , extended to Ctrl-F in #12347 by @Commodore64user ), and I got the File search while I expected Full text search (and the dialog looked not different, so I did a full text search and got no result, without really noticing it was about files and not the text).
I would expect the full text search to rise up - it feels File search has no real reason to be available while in Reader.

**Comment by Commodore64user** [comment]
full text search is <kbd>ctrl</kbd> + <kbd>s</kbd>, but all these shortcuts predate hotkeys anyway, so if you don't like one well.. change it through the ui? 

<img src="https://github.com/user-attachments/assets/25d89665-c8ae-49d8-bfd4-f77d46bdace3" width=40%>

**Comment by jonnyl2** [comment]
> [poire-z] File search has no real reason to be available while in Reader.

Strong disagree. It's very useful to be able to search if I have a specific book on my device without having to close the current book.

> [Commodore64user] all these shortcuts predate hotkeys anyway, so if you don't like one well.. change it through the ui?

Maybe he couldn't find it because it's under `Navigation >` rather than `Device > Keyboard >` ;)

**Comment by cameronj86** [comment]
> Maybe he couldn't find it because it's under `Navigation >` rather than `Device > Keyboard >` ;)

**EDIT**: Is the functionality only for readers and not for desktop apps? Counter-intuitive but that would explain why there's nothing in the expected section:

<img width="391" height="196" alt="Image" src="https://github.com/user-attachments/assets/ddda42f5-516b-42dd-97be-24c5a91044c4" />

**Original Text**
Is this still the case? For the life of me I can't find the way to edit it:
**Options under Navigation**
<img width="191" height="207" alt="Image" src="https://github.com/user-attachments/assets/188e99d5-af1c-4500-ac05-81fcff99e0a5" />
**Options under Keyboard**
<img width="191" height="207" alt="Image" src="https://github.com/user-attachments/assets/2ec28e52-b010-4059-b33d-57e58afe9f48" />

**Comment by Frenzie** [comment]
Under physical buttons.

**Comment by cameronj86** [comment]
> Under physical buttons.

Sorry, I edited in that part after the initial post. My physical buttons section just has `invert page-turn buttons`. I'm on desktop if that matters

**Comment by Frenzie** [comment]
If you disabled the hotkeys plugin or are running a version that predates it it wouldn't be there.

**Comment by cameronj86** [comment]
Must've disabled the hotkey plugin for an unrelated manner b4. Thanks again!
