### ISSUE TITLE
Automatic Night Mode doesn't automatic 

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10491]
* KOReader version: Latest 2023.04
* Device: PocketBook Color 633

#### Before after 21:30 o'clock my night mode (inversion) automatically turned on by the set of sun. But now it DOESN'T turn AUTOMATICALLY (maybe cause I turned it on myself, one day in the morning, l and I pushed some next appearing buttons). I need to work it like before - automatically turning on when sun sets, not by turning it on myself by pushing button.
What I need to do?

**Comment by jonnyl2** [comment]
Top menu -> ⚙ -> Screen -> Auto night mode -> Activate -> ☑ According to the fixed schedule

**Comment by ZHANYLone** [comment]
> Top menu -> ⚙ -> Screen -> Auto night mode -> Activate -> ☑ According to the fixed schedule

It didn't work. I pushed the button in settings like u said, but it didn't turn on night mode automatically - it's about 23:21 now. I had to turn it on manually by myself. Sad

**Comment by jonnyl2** [comment]
Try this: 

Top menu -> ⚙ -> Screen -> Auto night mode -> Night mode settings -> Sunset and sunrise -> `Set`

**Comment by ZHANYLone** [comment]
> Try this: 
> 
> Top menu -> ⚙ -> Screen -> Auto night mode -> Night mode settings -> Sunset and sunrise -> `Set`
> 
> EDIT: Also, you may have to uncheck and immediately recheck the previously mentioned (...) Activate -> ☑ According to the fixed schedule.

Nah
It doesn't help

**Comment by ZHANYLone** [comment]
> Can you show me your "Warmth and night mode settings" -> It should look like
> ![grafik](https://github.com/koreader/koreader/assets/36999612/e904c5b9-8bb2-4d17-9a98-a0baa07a29ab)
> 
> Additionally the info message shown with "Currently active parameters" would be helpful -> It should look similar to
> ![grafik](https://github.com/koreader/koreader/assets/36999612/bd31c04c-9fd9-43e5-bf38-9d5e4ad7ed0a)
> 
> 

On my e-reader I don't have Warm Light Mode, because it's Color e-reader.
PocketBook 633 Color
I pressed something wrong in the pop-up window when I turned on the night mode myself (not automatically)
And nothing helps. Now I can only turn on night mode by myself, not automatically. Sad.
Can You fix it in the new version?

![IMG_20230603_152546.jpg](https://github.com/koreader/koreader/assets/119916135/8ff0ef2b-6897-4d53-8819-c3a8d49c8073)

![IMG_20230603_152528.jpg](https://github.com/koreader/koreader/assets/119916135/b9741170-779e-40ab-b875-d73a6a25dc56)

![IMG_20230603_152521.jpg](https://github.com/koreader/koreader/assets/119916135/4602e6bb-0c56-496a-8f91-eeda191b13fe)

![IMG_20230603_152538.jpg](https://github.com/koreader/koreader/assets/119916135/9a737559-74e4-4143-a6d5-89678699b599)

**Comment by ZHANYLone** [comment]
> I think I have got the problem. Could it by chance be, that you had copied settings from another installation?

I don't know. I think no
