### ISSUE TITLE
Kobo: KOReader crashes when opening a folder in the file manager

### ISSUE THREAD

**Issue by illbone** [koreader/koreader#10509]
* KOReader version: 2023.05
* Device: Kobo Clara HD

#### Issue
KOReader instantly crashes when opening a folder from the start screen. Same crash happens in 2023.04 but 2023.03 works normally.

#### Steps to reproduce
Open any folder from the file manager.
Also crashes when going from a book to the file manager.

##### `crash.log` 
[crash.log](https://github.com/koreader/koreader/files/11607105/crash.log)

**Comment by NiLuJe** [comment]
Do you remember which sorting option you were using before the update?

(In particular, was it actually a "reading completion percentage" based one?)

**Comment by NiLuJe** [comment]
Extra Q: Is there anything funky in the home directory ?

(Say, has this thing been mounted on macOS  in the past or something?)

**Comment by hius07** [comment]
Exit KOReader, in the file koreader/settings.reader.lua remove the line starting with ["collate"].

**Comment by NiLuJe** [comment]
Still curious about what it's actually set to, if anything ;).

**Comment by hius07** [comment]
`strcoll_mixed`

**Comment by NiLuJe** [comment]
Oh, right, this one's gone now; we probably need a migration step to drop it from setting though, right?

(There's an existing related example for 20210715 FWIW).
