### ISSUE TITLE
Quick Menu cut

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#10508]
I have several profiles added in a quick gesture to be listed so I can change quickly among them.

I have been adding profiles over the weeks and I have now a big list. You can swipe down but it goes straight to the end missing some of the profiles. 

It seems they are not paginated and I don't know if it is by design or maybe something is wrong in my configuration.

**Comment by hius07** [comment]
It can be moved by shorter distance not with swipe but with hold+pan.
