### ISSUE TITLE
Cannot scroll pdfs reliably

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#10519]
* KOReader version: 2023.05
* Device: Android POCO X4 GT

I'm starting to use koreader as a pdf reader. I'm using continuous page mode. Tapping the left and right part of the screen to move to the next part works fine, but I'm having some issues with scrolling through dragging on the screen. Sometimes it works, sometimes it doesn't and I need to experiment a bit with different positions to start the scroll in order to get it to work. The position where I can manage to start the scroll is not consistent either....

**Comment by Frenzie** [comment]
The top and bottom will trigger the menu unless you disable that.
