### ISSUE TITLE
FR: Show available space in File Manager

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10516]
I think it would be helpful if the available space in the current directory is shown in the File Manager, for example like this:

<img width="695" alt="image" src="https://github.com/koreader/koreader/assets/95502269/7060a008-c292-4c2a-993a-e70c3e2e5eb8">

Currently, the only way to check the available disk space (that I know of) is via the System Statistics, and I'm not sure if that would also show the available space on an external SD-card or other connected drive. Since KOReader has built-in features to receive files (e.g., SSH, dictionary/news downloads etc.), it would make sense to keep users aware of available storage space. Many users will probably not think of checking the system statistics regularly, but will open the file browser now and again.

**Comment by NiLuJe** [comment]
`du` can be *extremely* slow, hard veto ;).

**Comment by jonnyl2** [comment]
I suspected the usefulness may vary by platform. On Android I never felt the need for it because the OS file manager supplies all that information. Now that I mainly switched to Kobo I never exit KOReader :)

But I'm OK closing the FR. It just would have been a nice-to-have, but nothing essential.
