### ISSUE TITLE
Wikipedia Lookup does not retrieve all the article

### ISSUE THREAD

**Issue by Villard** [koreader/koreader#10529]
* KOReader version:
* Device:

#### Issue
Wikipedia Lookup does not retrieve all the article. It seems to depend on the interpretation by Koreader of the links given below a chapter.

For example, I can get all the full and correct epub for the wikipedia article "Jérusalem" in French.
But for the wikipedia article "Jérusalem" in English, the epub ends just after the first title "Etymology and names".

The two articles have a first chapter on Etymology and just after the title of this chapter, there is an hyperlink to open a detailed article. But the writing of this hyperlink is different in the two versions(see below).
Maybe Koreader misinterprets this link in the English version.

In this English article, the source code is :
<h2><span class="mw-headline" id="Etymology_and_names">Etymology and names</span></h2>
<link rel="mw-deduplicated-inline-style" href="mw-data:TemplateStyles:r1033289096"><div role="note" class="hatnote navigation-not-searchable">Further information: <a href="https://en.wikipedia.org/wiki/Names_of_Jerusalem" title="Names of Jerusalem">Names of Jerusalem</a></div>

The code source of the French article is :
<h2><span id=".C3.89tymologie_et_d.C3.A9nominations"></span><span class="mw-headline" id="Étymologie_et_dénominations">Étymologie et dénominations</span></h2>
<div class="thumb tright"><div class="thumbinner" style="width:362px;"><a href="https://commons.wikimedia.org/wiki/File:Western_Wall_Panoramic.jpg?uselang=fr" class="image"><img src="./Jérusalem — Wikipédia_files/Western_Wall_Panoramic.jpg" decoding="async" width="360" height="132" class="thumbimage" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Western_Wall_Panoramic.jpg/540px-Western_Wall_Panoramic.jpg 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Western_Wall_Panoramic.jpg/720px-Western_Wall_Panoramic.jpg 2x" data-file-width="3276" data-file-height="1200"></a> <div class="thumbcaption"><div class="magnify"><a href="https://fr.wikipedia.org/wiki/Fichier:Western_Wall_Panoramic.jpg" class="internal" title="Agrandir"></a></div><a href="https://fr.wikipedia.org/wiki/Vieille_ville_de_J%C3%A9rusalem" title="Vieille ville de Jérusalem">Vieille ville</a>&nbsp;: panorama du <a href="https://fr.wikipedia.org/wiki/Mur_des_Lamentations" title="Mur des Lamentations">Mur occidental</a> (Mur des Lamentations) surmonté du <a href="https://fr.wikipedia.org/wiki/D%C3%B4me_du_Rocher" title="Dôme du Rocher">dôme du Rocher</a> et de la <a href="https://fr.wikipedia.org/wiki/Mosqu%C3%A9e_al-Aqsa" title="Mosquée al-Aqsa">mosquée al-Aqsa</a>.</div></div></div>
<div class="bandeau-container bandeau-section metadata bandeau-niveau-information"><div class="bandeau-cell bandeau-icone-css loupe">Article détaillé&nbsp;: <a href="https://fr.wikipedia.org/wiki/Noms_de_J%C3%A9rusalem" title="Noms de Jérusalem">Noms de Jérusalem</a>.</div></div>

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
If that is indeed the case then they changed what the API spits out.

**Comment by poire-z** [comment]
No feedback, and no other user comment - so probably solved.
(There's an other recent with about images missing, that will be fixed in the coming weeks.)
