### ISSUE TITLE
Custom cover disappears

### ISSUE THREAD

**Issue by mzelyony** [koreader/koreader#10526]
I was excited about the custom cover feature in the 2023.05 version. I copied the .jpg image directly into the .sdr directory, and was happy to see the cover on the screen with my Kobo turned off. But when I went to Book Information -> Cover Image: Tap to display next time it was not there anymore. The cover.jpg disappeared from the .sdr directory too

**Comment by Frenzie** [comment]
Oops, I forgot to click publish on https://github.com/koreader/koreader/releases/tag/v2023.05.1

Could you check if it's still an issue there?

**Comment by mzelyony** [comment]
Yes, this works now. Thanks!
Another question: How do I find the custom image file on the Kobo from the koreader itself? In the file manager I see only books

**Comment by Frenzie** [comment]
Pinging @hius07

**Comment by hius07** [comment]
Custom covers are stored in sdr folders alongside the books.
sdr folders are hidden in KOReader file browser.

Custom cover is deleted from the sdr folder via "Reset custom cover" button in the Book information window.

**Comment by moe123s** [comment]
@mzelyony how do u make custom cover show up on kobo? Adding custom cover does not make it display off screen for me. But books with normal cover do. Can you help with steps u did?

**Comment by mzelyony** [comment]
@hius07 I do not see the  "Reset custom cover" button in the Book information window in the latest patch release.
 I used to see the "Select custom cover" in the 2023.05, but I can not find it anymore. When  that was available I was trying to find a screenshot in the kobo storage, but could not. 
 After that I was trying to do the same via File Browser too, but it shows only books, and filters out everything else

**Comment by mzelyony** [comment]
@moe123s 
1) In menu -> Settings (the gear icon) -> Screensaver -> Check "Use last book's cover as screensaver"
2) connect the Kobo to the PC
3) copy the selected image to the Kobo's storage. Find relevant book's .sdr directory as cover.jpg or cover.png or whichever is appropirate
4) After you disconnect the Kobo from PC and koreader restarts you should be able to see the custom cover in the  Book Information window -> Tap to See Custom cover, and on the Kobo's screen when it is turned off

**Comment by hius07** [comment]
> I do not see the "Reset custom cover" button in the Book information window in the latest patch release.

Is there an icon in the upper left corner?

**Comment by mzelyony** [comment]
Yes, I do see it under the hamburger menu icon, and it works

**Comment by mzelyony** [comment]
Update to my previous. I do see the custom cover for the book where I assigned it via the Book Information, but nor for that one where I copied the file directly to the .sdr directory

**Comment by hius07** [comment]
Long-press the book and choose Refresh cached book info.

**Comment by mzelyony** [comment]
Yep, that works. Thanks!
