### ISSUE TITLE
Back light toggle does not work

### ISSUE THREAD

**Issue by cy8aer** [koreader/koreader#10536]
* KOReader version: 2023.05
* Device: Pocketbook Touch Lux 3

#### Issue

The back light toggle does not work with the version 2023.05. This worked with 2023.04

#### Steps to reproduce

* check if gesture for down left edge is set to "switch back light" (default)
* click down left edge

Expected:

* the back light state is switched (on->off or off->on)
* a dialog message occurs (Back light switched on/off)

Actual behaviour:

Nothing happens

##### `crash.log` (if applicable)

no `crash.log` generated.

**Comment by NiLuJe** [comment]
Is the only thing affected the gesture? Does the frontlight toggle button in the frontlight widget behave? What about simply changing the brightness value?

**Comment by cy8aer** [comment]
Ok, I now made the following tests:

* Option light and toggle: works
* Gestures for increasing/decreasing the light: works
* Changed the down left gesture to night view: works
* Switched back to toggle frontlight toggle. Then: /works/

Hm, though I do not know why it did not work before I am happy with it (because it now works again) and would close the issue, except @NiLuJe: do you want to have some other test?

**Comment by NiLuJe** [comment]
Huh. I can't think of anything that would explain that, except a weird gesturemanager config quirk :?.

Oh, well; ping us if it goes wonky again ;).
