### ISSUE TITLE
FR: specify  size of the image it will be displayed  full-width.

### ISSUE THREAD

**Issue by jackjin-cn** [koreader/koreader#10535]
**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by poire-z** [comment]
That was really a "handful" of words, from a really little hand :)
Please edit and add more details, and re-open if needed.
