### ISSUE TITLE
[Question] Can i get koreader keyboard for regular use?

### ISSUE THREAD

**Issue by bheeshmpita** [koreader/koreader#10541]
I tried the keyboard in the app and liked it and want to try it as full-time keyboard for my android device. Is there anyway i can do so?

**Comment by Frenzie** [comment]
The short answer is no, but I do think someone's made a copy of it as an Android keyboard. I just can't quite recall who it was atm.

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/discussions/8099
