### ISSUE TITLE
Clock auto-update causes bottom status bar to cover open footnote container

### ISSUE THREAD

**Issue by Atrate** [koreader/koreader#10542]
* KOReader version: tested on 2023.04, but did not see anything mentioning this in 2023.05 release description, so I presume it's not fixed
* Device: BOOX Note 3

#### Issue

When opening a footnote by tapping on the superscript, if clock auto-update is turned on, after the clock updates, the bottom status bar partially covers the opened footnote container (by one line or so).

#### Steps to reproduce

1. Set the status bar clock to auto update
2. Open a footnote by clicking on a superscript
3. Wait a minute
4. Status bar now covers the bottommost line of the footnote container

**Comment by poire-z** [comment]
It is a dedicated and standalone widget:
https://github.com/koreader/koreader/blob/18cd6b79d838570100f61c8ddc0c52b0ceebd0d4/frontend/apps/reader/modules/readerlink.lua#L1463-L1492
(I remember we somewhere indeed did write names, I think I advocated for a property.)

**Comment by NiLuJe** [comment]
Oh, cool ;).

> I think I advocated for a property.

It is indeed a prop ;).

----

So, assuming it actually *always* covers the footer by design, this ought to do it:

```diff
diff --git a/frontend/ui/widget/footnotewidget.lua b/frontend/ui/widget/footnotewidget.lua
index 22b13625f..d708badf7 100644
--- a/frontend/ui/widget/footnotewidget.lua
+++ b/frontend/ui/widget/footnotewidget.lua
@@ -113,6 +113,7 @@ body > section > title {
 
 -- Widget to display footnote HTML content
 local FootnoteWidget = InputContainer:extend{
+    covers_footer = true,
     html = nil,
     css = nil,
     -- font_face can't really be overriden, it needs to be known by MuPDF
```

If it doesn't, more thinking will be necessary ;).

**Comment by poire-z** [comment]
Any feedback, if the above solution works?
