### ISSUE TITLE
FR: Save custom cover location

### ISSUE THREAD

**Issue by mshoumans** [koreader/koreader#10546]
Device: Android

Feature:
Save custom cover image to a chosen path upon loading book. This should be separate option from save cover image path

**Comment by hius07** [comment]
Can you describe your use case?
Currently you can set any image on your device as custom cover (it will be copied to a book sdr folder).
If you reset custom cover, the original image will remain in place.

**Comment by mshoumans** [comment]
> Can you describe your use case? Currently you can set any image on your device as custom cover (it will be copied to a book sdr folder). If you reset custom cover, the original image will remain in place.

Use case:
Have android device display custom cover image as screensaver.

Current feature:
Currently with existing cover image feature. If you choose save path as a fixed location e.g. sdcard\pictures\cover.png, set file as screensaver, then any loaded book will immediately overwrite the cover.png, therefore you get different book cover for each book.

Custom cover existing feature:
Currently custom cover saves in book .sdr so there is no fixed location to use to set screensaver, you have to go each time to .sdr folder to press set as screensaver.

Request:
Create a copy of custom cover in .sdr folder to a fixed location set by user similar e.g. sdcard\pictures\customcover\cover.png. This means that everytime a book with custom cover loads, it will copy cover from .sdr and overwrite the cover.png in sdcard\pictures\customcover\cover.png. This way we have a central location for screensaver feature to load cover from

**Comment by hius07** [comment]
Screensaver has an option: Use last book's cover as screensaver. If a book has custom cover, it will be used as a screensaver. Isn't it what you need?

**Comment by poire-z** [comment]
I think all this is about the "Cover Image" plugin, which is useful on some devices where our screensaver can't work, and saves the cover to some configurable place, so the OS own screensaver system, or some other app, can use and display it (and this plugin is disabled on our Kobo & Kindle, so we're excused when we don't remember it exists :)
https://github.com/koreader/koreader/blob/master/plugins/coverimage.koplugin/main.lua

**Comment by mshoumans** [comment]
@hius07 @poire-z  poire-z is absolutely correct and described it better than I did. Screensaver option from koreader does not exist on android. The cover image plugin however exists on android and is as poire-z described. Thus kobo as far as i know can make use of "use last book" while android doesn't have it so has to rely on cover plugin, which uses a fixed path for OS to use as screencover

**Comment by hius07** [comment]
Got it, thanks.
I've fixed CoverImage plugin to support custom covers.
The issue is that its cache (its hash) doesn't know about setting the custom cover.
Since this plugin is not widely used, I would prefer to not add automatic cache cleaning into the core (BookInfo).
I'd better add a new menu item `Refresh current document cache` to CoverImage submenu, a user would do it manually after setting/resetting the custom cover.
@zwim ?

**Comment by poire-z** [comment]
Couldn't you just send an event "CoverImageUpdated", that only this plugin would catch ?

**Comment by mshoumans** [comment]
I am just curious. Is this not a case of having cover plugin upon book load automatically scan current book folder .sdr and copy cover image to same fixed location of cover plugin w\overwrite (as the absolute easiest fix) ? 

I am sure what's discussed above thats flying over my head is more comprehensive and great! :D

**Comment by poire-z** [comment]
> Always copy file titled cover.ext (if it exists) to same fixed location as cover plugin

The plugin wants to avoid copying over and over a file, and wear your SDCard/storage.

> We have no files there, just blitbuffers.
Maybe get the data from the cover_bb structure and add its md5 to the hash name?

But we have the bb saved as a file, right? So, cheaper than a md5 of it, just use the date (include the date in what is md5'ed) of the file we created ?

**Comment by hius07** [comment]
The cache is checked before saving bb to a file, to avoid saving.

**Comment by poire-z** [comment]
I don't know how you modified the plugin to support a custom cover, but it looks to me that, in CoverImage:getCacheFile(), you could use DocSettings:getCoverFile() to get the cover file, and if one, gets its "file modified timestamp", and append it to the `key` before md5(key) ?

**Comment by hius07** [comment]
We can take a part of bb data to calculate md5 and use it in the hash name.

**Comment by poire-z** [comment]
> is changed to FileManagerBookInfo:getCoverImage

You could have that method `return cover_bb, is_custom_cover(true/false)` if it helps.
Or just use an additional DocSettings:findCoverFile() to get that info.
(Not a problem if this plugin needs to do some additional work, you and I are not using it :)
