### ISSUE TITLE
FR: Disable long-press on corner gestures while Select mode is active

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10552]
**Does your feature request involve difficulty completing a task? Please describe.**

While selecting text using the select mode and the ▨ symbol is being displayed in the upper-left hand corner, long-press on corner must first be manually disabled if the 2nd word being selected (to complete the selection) falls on a corner area. 

**Describe the solution you'd like**

I think it would make sense to disable 'long-press on corner' gestures by default while Select mode is active and KOReader is awaiting the long-press to complete the selection.

**Comment by hius07** [comment]
How do you start highlighting/selecting in that corner areas?

**Comment by jonnyl2** [comment]
I don't; I would select the other end first.

**Comment by poire-z** [comment]
I guess this issue can be closed by #11327 ?
(I think that even with select mode to select long parts of text, autoscroll may have its edge case use :) Users annoyed by that like you could now disable it completly.)

**Comment by jonnyl2** [comment]
It is fine for me personally if this issue is closed; you're correct in that I will probably disable the autoscroll feature anyway and not need the 'two-part-Select' feature for same-page selections anymore. (Although it could still happen that the last or first word of a selection ends or begins in a corner tap-area, odds of this happening will be small enough for this not to be an issue.)

From a UX perspective though, I still think it would make sense for text selection to take precedence over any long-press corner gesture while this feature is active. The Select Mode indicator in the corner advises the user, "please complete your text selection" and for the duration of this select mode I think the user would not expect to be able to do any long-press corner press gesture (the user-assigned top left corner tap is also suspended at this time btw). 

But I am okay with it being closed, also considering that this issue hasn't attracted any other users' interest. Thank you for the PR #11327.

**Comment by poire-z** [comment]
Oh right, I misread the request - not having any long-press in corner, and focused on scroll-in-corner, I read that as disabling corner-scroll when in select mode.
Despite not using any long-press-in-corner gesture, it feels like your request makes sense.
