### ISSUE TITLE
WebDAV - Nextcloud - files are uploaded with 0 bytes

### ISSUE THREAD

**Issue by wojtek1171** [koreader/koreader#10564]
Recently files uploaded from the device to cloud using WebDAV protocol occurs to be uploaded with 0 bytes size. It's probably server side issue related to fastcgi parameters, however `fastcgi_request_buffering` is enabled in my nginx settings and other WebDAV clients seems to work fine.

To not messing too much with the server settings I found that adding `Content-Length`  header to `uploadFile` function in `webdavapi.lua` fixes the problem. The same way it is done in `dropboxapi.lia`:

https://github.com/koreader/koreader/blob/f7d633cc3d0efd273a875132ac2de4fb4754dd02/frontend/apps/cloudstorage/dropboxapi.lua#LL147C13-L147C68

For anyone struggling with the same problem it can be a simple solution.
If you also find it useful and without harm for the rest of the code maybe it's worth to include that header in code repository.

**Comment by Frenzie** [comment]
Please open a PR for that. Seems like it can't hurt. :-)
