### ISSUE TITLE
Question: How does the translation feature in KOReader work?

### ISSUE THREAD

**Issue by aaalkoud** [koreader/koreader#10589]
Hey. Sorry if this issue isn't labeled correctly, I've never raised an issue before. I am building an app, and I'd like to use Google Translate without paying for the api. I am not trying to translate on my server and send the translations to clients; I am planning on querying the api on each app instance, locally, if the user wants to translate something. I checked the code and this seems like what KOReader does, though I couldn't figure out what the url of the request to google's servers would look like. Unless this is all wrong and KOReader has an api key for google translate... 

Thanks a ton.

**Comment by hius07** [comment]
There are some comments right there:
https://github.com/koreader/koreader/blob/master/frontend/ui/translator.lua
