### ISSUE TITLE
Frontlight enabled/disabled message 

### ISSUE THREAD

**Issue by mikebluu** [koreader/koreader#10588]
* KOReader version: 2023.05.1
* Device: Tolino Epos 2 (rooted Android 4.4.2)

#### Issue

Frontlight enabled/disabled message no longer shows up when enabling/disabling the frontlight through gesture (bottom left corner tap, if it matters). In previous versions, if I'm not mistaken up to 2023.03, I would receive the message as usual. It isn't very pleasant because when having the brightness level set to 2-3, and reading surrounded by natural light, I don't know if my frontlight is on or off even after using the gesture. (although it should be turned off by "frontlight off during day", it is not. But that's a story for another bug report:).)

#### Steps to reproduce

Just turn on/off the frontlight using the gesture, and nothing appears on the screen.

**Comment by offset-torque** [comment]
**Reminder:** You can add frontlight state to the Status Bar. I have it there for the exact reason you described.

**Comment by NiLuJe** [comment]
Unless you've actively disabled notifications, that one should still be there ;).

The only thing I can think of would be an Android-specific quirk related to... something (because I did touch a few things related to that for 2023.05), but it's definitely still there on Kobo, for instance.

**Comment by hius07** [comment]
Confirm bug on Kindle: no frontlight toggle notifications.

**Comment by mikebluu** [comment]
> Unless you've actively disabled notifications, that one should still be there ;).
> 
> The only thing I can think of would be an Android-specific quirk related to... something (because I did touch a few things related to that for 2023.05), but it's definitely still there on Kobo, for instance.

I did not change anything as far as I'm concerned (cannot update my tolino or change anything related to software), and I've just upgraded KOReader as usual (installed the new .apk through Android's update pop-up)

**Comment by NiLuJe** [comment]
> Confirm bug on Kindle: no frontlight toggle notifications.

Huh. God to know, I'll try to look into it soon-ish.

FWIW, they're working on the device I've got on hand running 2023.04-56 (possibly WIP code from the fl ramp shenanigans PR, though).

And a quick update later, they're still working on 2023.05.1-27, huh.

**Comment by hius07** [comment]
2023.05.1-27 no notification on toggling, there is a notification on left edge swipe (intensity).

**Comment by NiLuJe** [comment]
By gesture, right? (As opposed to the *toggle* button in the frontlight
widget).

**Comment by hius07** [comment]
Yes, no notification on frontlight toggling by a gesture.

**Comment by hius07** [comment]
After https://github.com/koreader/koreader/pull/10305.

I do not see where the Kindle should show the notification (`done_callback`)?
https://github.com/koreader/koreader/blob/64f778d97d26a267a48c5a0cd123ba15e7e3bdd4/frontend/device/generic/powerd.lua#L62-L63

I see it for Kobo
https://github.com/koreader/koreader/blob/64f778d97d26a267a48c5a0cd123ba15e7e3bdd4/frontend/device/kobo/powerd.lua#L314-L320

**Comment by NiLuJe** [comment]
Yup, that's probably it, I moved stuff around between generic and imps so much during that PR that this probably skipped my mind in the end ;/.
