### ISSUE TITLE
Kobo Clara HD random freeze

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10586]
* KOReader version: current stable (2023.05.1)
* Device: Kobo Clara HD, FW 4.34

#### Issue
While reading a page and not doing anything, KOReader randomly freezes. It forces to reboot the device itself.

#### Steps to reproduce
I can’t really reproduce this consistently, will be trying to do so over this weekend, I got some more time.

Can’t remember when exactly this started to happen, but probably around Jan-Feb stable updates. 

Symptoms look similar to ones in https://github.com/koreader/koreader/issues/9806

I tried to disable notifications - but it crashed again. 

Next I am going to try increasing the timeout you mentioned and other patches. 

@NiLuJe (and other who are very well versed in Kobo debugging), could you please share some “excavation” tools? 
1) SSH à la usbnetwork for Kobo? Because I suppose if KOReader hangs, then its ssh session hangs too?
2) If (1) is correct, then how do I force it to switch to Nickel? So I don’t have to reboot the whole device. 
3) If not only KOReader, but whole kernel hangs, then only way is serial port you mentioned? Do you have instructions for this? Are they similar to Kindle serial debug?

##### `crash.log` (if applicable)
Will get logs with verbose ON if I can get a crash.

Thank you!

**Comment by NiLuJe** [comment]
The Clara HD is on the list of "may randomly crash" kernels (basically all the Mk. 7 lineup is affected, but to a much lesser extent than Mk. 9), so there's not much we can do there.

It's alsmo similarly tied to power delivery, in that having WiFi enabled or the device plugged in will workaround the issue, making this issue completely imùpossible to even debug without serial access (and quite likely a custom more verbose kernel, anyway).

**Comment by NiLuJe** [comment]
Note that my own experience with these on a Mk. 7 device (Forma) would *not* trip a watchdog reboot (i.e., it'll just hang), and it is specifically tied to screen refreshes (i.e., it'll likely hang right after or right before a refresh), and it was ever so slightly more frequent on mixed content (e.g., CBZ) vs. plain text.

If the device actually reboots itself, you may be hitting another kernely/hardwary failure ;).

**Comment by NiLuJe** [comment]
As for 3., you'll have to look at a teardown of your specific device, but, yeah, it's basically the same as on Kindle (except I expect the pads will be much easier to find and clearly labeled ;p).

**Comment by mergen3107** [comment]
Thanks @NiLuJe ! Super extensive reply as in your kind usual :)
Let me summarize things that I experience here so other people can follow and add:
- Hangs are permanent, i.e. it doesn’t get to reboot by itself. Only user hard reboot revives things. 
- Books where it hanged were fb2 and epub, so plain text, eith not much going on with regards styling and images. 
- Yes, Wi-Fi was always off during hangs. Now that slightly pinches me to remember and try enabling Wi-Fi and letting Wi-Fi autosleep to kick in. Last time it hanged was when I shared LTE from my phone to the Clara HD, updated KOReader and let KOReader restart, and left Wi-Fi on (forgot about it, basically).

**Comment by SamLeatherdale** [comment]
Experiencing similar behaviour on my device(Kobo Libra 2) twice yesterday, and it happened right as I turned the page (the new page didn't have a chance to display yet.

The crash log doesn't provide anything super useful (there is no actual stack trace from a crash, just a hang as mentioned), although this line from the Progress Sync was right before it restarted both times:
```
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
Original fb rotation is set @ 0
Original fb bitdepth is set @ 32bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Libra 2 (388 => Io @ Mark 9)
```
I'm guessing the restart happens before the `fb rotation set` line?

I'm not sure if attempting to sync to the Progress Sync service is a red herring or the actual cause, but it is the last log line before the restart both times. 
The `host or service not known` is confirming that Wi-Fi was off at the time, however.

Full details of my device and version (2023.05.1) are as follows:
```
[FBInk] Detected a Kobo Libra 2 (388 => Io @ Mark 9)
[FBInk] Enabled Kobo Mark 7 quirks
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 300 dpi
[FBInk] Variable fb info: 1264x1680, 32bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 5120 bytes
[FBInk] Canonical rotation: 0 (Upright, 0°)
[FBInk] Fontsize set to 32x32 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 39 cols, Page size: 52 rows
[FBInk] Vertical fit isn't perfect, shifting rows down by 8 pixels
[FBInk] Detected a change in framebuffer bitdepth (32 -> 8)
[FBInk] Reinitializing...
[FBInk] Variable fb info: 1264x1680, 8bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 1280 bytes
[FBInk] Canonical rotation: 0 (Upright, 0°)
[FBInk] Fontsize set to 32x32 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 39 cols, Page size: 52 rows
[FBInk] Vertical fit isn't perfect, shifting rows down by 8 pixels
[FBDepth] Screen is 1264x1680 (1280x1792 addressable, fb says 1280x1792)
[FBDepth] Buffer is mapped for 9175040 bytes with a scanline stride of 5120 bytes
[FBDepth] Requested canonical rota 0 translates to 1 for this device
[FBDepth] Current rotation is already 1!
[FBDepth] Switching fb to 8bpp @ rotation 1 . . .
Updating bitdepth from 32bpp to 8bpp
Sanitizing grayscale flag for 8bpp
Updating rotation from 1 (Clockwise, 90°) to 1 (Clockwise, 90°)
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 1 (Clockwise, 90°)
[FBDepth] Screen is 1264x1680 (1280x7168 addressable, fb says 1280x3584)
[FBDepth] Buffer is mapped for 9175040 bytes with a scanline stride of 1280 bytes
[*] Version: v2023.05.1
```

**Comment by NiLuJe** [comment]
@SamLeatherdale:

Logs are mostly irrelevant here (especially if not verbose debug), so don't try to unpack too much from those, they're fairly standard (and, as such, meaningless).

And, in the case of this specific set of issues, you're most likely going to get truncated logs anyway because it's a kernel crash (on your device, at least). And the important bit of logging wouldn't be here, but in the kernel logs anyway ;).

As a reminder, the Libra 2 and associated issues have been looked into in much more detail in the dedicated issues:

Libra 2: #8414
Clara 2E: #9806 
Nia: #10558

**Comment by mergen3107** [comment]
( @SamLeatherdale I edited your comment to hide the long log under the spoiler).

@NiLuJe 
Some updates so far:

1) The culprit (at least one of a few?) seems to be the sleep cover. I tried to lock-unlock-lock in a quick succession - **I was (!) able to achieve this weird state** when the device is unlocked so I see the page I was reading, but no frontlight and no response to touch AND power button. I was then able to swing sleep cover closed/open and the responsiveness came back, but frontlight stayed off.
So for now I checked the "Ignore sleep wake event in KOReader" to see if this works.

2) My wife says that one time it froze when she saw at night that the frontlight was on while the sleepcover was closed. After she opened it in the morning, the battery was drained to 0%, although it was around 70% last evening. I can see that the cover-side magnet piece is a little bent, so that it is not completely flush with the body-side, but wiggling the cover around while the magnet is engaged did not yield any wakeups. My suspicion is that the Hall sensor is tripped sometimes due to some power saving, when the board changes the current draw. Then it sees the magnet strength less than threshold for locking, but as board gets more even power, it trips the lock again. Probably, the timing on the IC chip is too loose to catch these power transients timely. Oscilloscope might tell more, if I knew where to probe the Hall sensor.

3) Among other fruitless efforts:
- My wife reported that last time two days ago it froze while she was holding the Clara HD by the frame, single-handedly on the right hand side. So I opened the back cover to see if battery has swollen - but everything seems OK. So is the microSD card, it was fit snugly, I took it out to check read/write and bad sectors - no issues whatsoever.

4) Here is the crash.log from the time when it froze in (3) but before I found (1), but as you said, this is more likely kernel-panic one, so there are no interesting faults to report even in KOReader verbose mode.
[crash.log](https://github.com/koreader/koreader/files/11926464/crash.log)

**Comment by mergen3107** [comment]
Also, does enabling verbose logs in KOReader cause more power drain while the reading page is shown?
Like in cases when it gets unlocked by itself like it (2) above.
I have some plugins turned on, like battery stats, system stats, autostandby (maybe) and some others.

**Comment by NiLuJe** [comment]
> KOReader cause more power drain while the reading page is shown?

Not noticeaby so. You're more likely to notice a latency hit than a battery hit ;).

----

Note that 1 & 2 *might* simply cause soft-locks, because handling covers properly is a PITA. I may or may not have touched some of this recently, and the verbose debug logs should be clear about these sort of things, though.

**Comment by NiLuJe** [comment]
> 4\. Here is the crash.log

Yeah, the logs from the 29th are *riddled* with a chattering sleepcover, in lift->contact cycles, most often at the exact same timestamp.
That's obviously indicative of a hardware issue; but, looking at a number of those, I haven't pinpointed any "wrong" handling of it, though (but, those patterns *will* lead to confusing at the best of time, and I haven't checked *all* of the: there are *a lot*).

I'm also seeing a weird flood of touch events after a resume (starting at 07/01/23-01:49:36), I would have said it might be something tripping the IR grid (as a bent cover is wont to do ;)), but the Clara doesn't use an IR grid?

Things look sound later one, though.

**Comment by mergen3107** [comment]
Thanks @NiLuJe !

The cover front and the magnet are bent, but bent away from the screen though :D

AFAIK, Clara HD uses the touch screen layer, since the bezel depth is so shallow (in comparison to Kindle Touch or Kobo Aura HD, I guess). 

I checked the screen, it doesn’t seem to be concerningly dirty :D 

Is there a way to constrain the verbose logs to catch only sleep cover events? Maybe there are so many more than shown in the log file now that the logging skips some of them?

**Comment by NiLuJe** [comment]
> Is there a way to constrain the verbose logs to catch only sleep cover events?

grep ;o


> Maybe there are so many more than shown in the log file now that the logging skips some of them?

Nope.

**Comment by mergen3107** [comment]
3 days update: **disabling the cover wake function in KOReader** was enough to not have any more crashes. Device still goes to sleep if I close the cover, but needs to be woken up by pressing the power button. 

At least for reading this is enough. 
I think I should create a label “Work around available” and assign that to this ticket. So people who stumble upon here will see how to remediate the issue. What do you guys think?

**Comment by NiLuJe** [comment]
It's extremely specific to a very very broken cover, so someone would be very lucky to stumble on that one on purpose ;p.

But, yeah, we can probably close it ;).

**Comment by mergen3107** [comment]
> so someone would be very lucky to stumble on that one on purpose

I found about 6-7 reddit posts and about 3-4 mobileread posts about the random freezes, where people were suggesting two things: stop using the cover and plug/unplug the battery (this one I don’t believe should have worked, sounds like placebo - didn’t work for my case). 

Those people were not using KOReader necessarily, and because Nickel (I think) doesn’t allow to block only wake up cover action, but allows only to block all cover actions, - I believe in this particular ticket this KOReader-oriented workaround deems appropriate to at least avoid the issue. 

Also, this case of mine is one from Fintie - a very popular barring the scarcity and cost of the original Kobo Clara HD sleepcover. So I still think people gonna come back as soon as their magnet bends :D

**Comment by mergen3107** [comment]
Sorry, small correction: the case is from kwmobile, not Fintie. Looks like this: 
![IMG_9094](https://github.com/koreader/koreader/assets/6279855/b720657d-cb3b-4341-a14d-dd561fc4ce65)

**Comment by NiLuJe** [comment]
Oh, for sure, sleep covers have been fucking up left and right forever; but I've never seen one spazz out quite like what your logs showed ;).
