### ISSUE TITLE
FR: Filter for Statistics calendar view

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10592]
**Does your feature request involve difficulty completing a task? Please describe.**

The statistics calendar often gets clogged up with many books that one hasn't read seriously but only taken a quick glance at or browsed a few pages. While individual titles may be removed manually, for a large number of titles this is not practicable.

**Describe the solution you'd like**

Implement a filter option to only show books that one has read seriously. For example:

- Books with at least 10 _consecutive_ pages read; _and_
- Books spent at least 15 minutes on

(For example, a reference work one regularly spends a few minutes on but never reads several consecutive pages would be filtered out even if total time spent on it is hours.)

**Additional context**

The setting could be added to the menu at Tools -> Reading statistics -> Settings -> □ Filter books in calendar view

The filter criteria could either be hard-coded (e.g., with the criteria suggested above), or made adjustable in the settings as well (e.g., min. time spent, min. pages read [consecutive or total]). If hard-coded, the suggestions are just rough ideas and different thresholds or criteria may work better.

**Comment by christian-ho** [comment]
You could use the menu where you can reset all statistics for the books you have read for less than a certain amount of time?

**Comment by jonnyl2** [comment]
Thank you @christian-ho, I was actually not aware of this option. This is certainly helpful for books I decide not to read any further. But often I go back to them weeks or months later and pick up reading again. Then I wouldn't want to lose the statistics data for those books. 

Rethinking the filter criteria for this FR however, it would probably make more sense to apply the filter by day rather than by book. E.g., only show books for a day's statistics calendar that have been spent a minimum amount of time on (e.g., > 15 min.).
