### ISSUE TITLE
FR: Open .docm files

### ISSUE THREAD

**Issue by ejoejoejo** [koreader/koreader#10599]
.docm files do not show up in the file browser (or in the file search). Since they are Word files, I expect Koreader can open them. It seems like a simple improvement to show them.

**Comment by hius07** [comment]
To show them in FM check Show unsupported files in the file browser Settings menu.

**Comment by ejoejoejo** [comment]
Well, following your instructions: CoolReader engine can't open it.

But thanks for your reply. I donated 10 euro this afternoon, I really appreciate KoReader.

**Comment by Frenzie** [comment]
It's probably a good idea to add a sample .docm to the issue just in case. That being said, the little bit of support comes from a library that hasn't received any updates for a very long time.

**Comment by pkb** [comment]
docm is actually docx with macros enabled. It has different content type identifier. if you want to open it in crengine you need to modify it a little bit:
- add `docm_DocumentContentType = U"application/vnd.ms-word.document.macroEnabled.main+xml";`
- modify DetectDocXFormat() format function to return true when `package.partExist(package.getContentPartName(docm_DocumentContentType))`
- modify ImportDocXDocument() to open `docm_DocumentContentType` content part when docx_DocumentContentType stream is null

**Comment by poire-z** [comment]
Thanks @pkb . If you have done these changes on any crengine repo/fork, can you provide a patch ? I'll adapt it to our crengine layout. (Unless you want to do a PR to our crengine :)

**Comment by pkb** [comment]
@poire-z [something like this](https://gist.github.com/pkb/1a67f7e3d66605222df3d3b4cf01d522) should work, I think.

**Comment by Frenzie** [comment]
> docm is actually docx with macros enabled

For any onlookers, that's the kind of thing a sample file would've clarified. ;-)

**Comment by ejoejoejo** [comment]
I attach an example. Github didn't support .docm either, I had to zip it.

[](url)
[docm example.zip](https://github.com/koreader/koreader/files/11995172/docm.example.zip)

**Comment by poire-z** [comment]
> @poire-z [something like this](https://gist.github.com/pkb/1a67f7e3d66605222df3d3b4cf01d522) should work, I think.

Thanks, that works ! (with a sample of mine and @ejoejoejo one).
I'll PR this in the coming weeks (bumping crengine is currently prevented by other works).

**Comment by poire-z** [comment]
Fixed by #10702.
