### ISSUE TITLE
Read timer 

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#10596]
* KOReader version: 2023.05.1
* Device: Pocketbook Era

#### Issue
Read timer does not work

#### Steps to reproduce
Set interval and start timer. After the timer has expired, no message appears on the screen.

**Comment by mergen3107** [comment]
Have you disabled notifications in the top menu?

**Comment by NiLuJe** [comment]
I don't recall if the PB + autosuspend + notifications thing is still an issue? (in which case, yeah, known issue because autosuspend).

**Comment by elvvis** [comment]
> Have you disabled notifications in the top menu?
Notifications are enabled.

**Comment by rjd22** [comment]
> I don't recall if the PB + autosuspend + notifications thing is still an issue? (in which case, yeah, known issue because autosuspend).

This is still an issue. I didn't have time yet to implement the KoReader managed suspend and wake to solve this. It's now managed by pocketbook itself making timers without user input impossible.

**Comment by pazos** [comment]
Closing in favor of #9493
