### ISSUE TITLE
Koreader does not adjust the screen when we change the orientation

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#10593]
* KOReader version: Last nighty
* Device: Likebook Mars - Android  6.0.1

1) We have an image in the folder ready to be opened.
![photo_2023-06-17_20-22-32](https://github.com/koreader/koreader/assets/4573505/b100648c-345e-45a5-9a5a-f6e98dd8f434)

2) We opened the image. Things seem normal.
![photo_2023-06-17_20-22-33](https://github.com/koreader/koreader/assets/4573505/1ac1f23f-7aaf-49ce-aec1-f4a599afaeb3)

2) We changed the orientation to landscape, and the screen didn't auto-adjust, so part of the screen went black.

![photo_2023-06-17_20-22-34](https://github.com/koreader/koreader/assets/4573505/f99f07aa-d785-4f06-8381-6b0324d1a271)

![photo_2023-06-17_20-22-35](https://github.com/koreader/koreader/assets/4573505/88dc30b6-a952-4505-97ae-f555116b192a)

![photo_2023-06-17_20-22-35 (2)](https://github.com/koreader/koreader/assets/4573505/2fa51483-ae99-495a-a71d-29098ced5913)

3) Then we close Koreader and go back to the folder again.

![photo_2023-06-17_20-22-32](https://github.com/koreader/koreader/assets/4573505/b100648c-345e-45a5-9a5a-f6e98dd8f434)

4) We opened the image. Things seem normal now.

![photo_2023-06-17_20-22-35](https://github.com/koreader/koreader/assets/4573505/97dea5cd-78b0-4f3b-b5df-8a84465f7b15)

5) We go back to the folder listing, and things break again.

![photo_2023-06-17_20-22-35](https://github.com/koreader/koreader/assets/4573505/d3415088-c590-4173-a951-59d650ca8749)

![photo_2023-06-17_20-22-36](https://github.com/koreader/koreader/assets/4573505/92f6e8b5-50a8-4419-970e-b2d62332e0e3)

**Comment by hugleo** [comment]
Now that I've seen that it's a duplicate of https://github.com/koreader/koreader/issues/10591.

I don't remember exactly when this problem started to occur but I believe it was several months ago.

**Comment by mergen3107** [comment]
(Sorry guys, I tried to close it as duplicate from mobile :D)
