### ISSUE TITLE
FR: Font replacing according to font-family for epub

### ISSUE THREAD

**Issue by yuanshuai0217** [koreader/koreader#10607]
**Does your feature request involve difficulty completing a task? Please describe.**

There are four frequently used typefaces in Chinese text: Song, Hei, Kai and Fangsong (For more information, please refer to [_Requirements for Chinese Text Layout_, §2.2.1](https://www.w3.org/TR/clreq/#four_commonly_used_typefaces_for_chinese_composition)). Song and Hei typefaces correspond to
css generic names `serif` and `sans-serif`, and Fangsong has its own generic name(`fangsong`). According to [this css spec](https://www.w3.org/TR/css-fonts-4), Kai shall correspond to `cursive`, which is [disputed](https://github.com/w3c/csswg-drafts/issues/4606).

However, after reviewing stylesheets in some Chinese epub files, here are what I've found:

- Most Song and Hei `font-family` properties fallback to `serif` and `sans-serif`, which can be easily handled.
- Few Kai and Fangsong `font-family` properties fallback to `cursive` and `fangsong`, many just lack a fallback name, and some fallback to `serif` or `sans-serif`, displayed as Song or Hei typefaces.
- Due to the difference in publishers, there are a dozen common-used font names for Kai and Fangsong font, e.g., `Kai, Kaiti, "楷体", STKai, STKaiti, "华文楷体", BiauKai, “標楷體”`.

In order to make these fonts display properly, a font replacing mechanism is needed.

**Describe the solution you'd like**

Currently, there are only generic names (like Serif and Fangsong), emoji and math in ”Font“→”Font-family fonts“. Font names of `font-family` properties appeared in css stylesheets could be added, and the user can set the font to be replaced to. 

Recently, Moon+ Reader implemented this feature.

**Describe alternatives you've considered**

I've tried to use `@font-face` in styletweaks, but according to [this issue](https://github.com/koreader/koreader/issues/10604), due to limitations of styletweaks, this is not going to work.

**Additional context**

**Comment by poire-z** [comment]
serif, sans-serif, cursive, fangsong... are generic font-family names as defined by the CSS specs, so we added support to associate one of your font to each of them.
I understand that what you wish, in a non-chinese context, would be like a way to associate another prefered font to, say, "Georgia", so it is used instead whenever we see `font-family: Georgia`.

> In order to make these fonts display properly, a font replacing mechanism is needed.

Well, I'm not sure we will do anything like that. If the fonts are named by name, they will be used if found. If there is a fallback generic family name, it will use the font you have set for them. If not, well, it's a publisher issue (not providing fonts) or a user issue (not adding fonts).
And if you want to fight that, you'll do like all of us Western readers: you'll target elements with style tweaks. It's painful, but it's the way to do it. Our just "Ignore publish font names", and use your single preferred font for the book.
Web browsers don't do more.
