### ISSUE TITLE
ota.koreader.rocks is down (should be back up on the 26th)

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#10603]
Several years ago I donated an Ubuntu 16 box with ip 23.101.194.64 to host koreader services like progress sync.
I haven't monitored it for a while. But today I received a notification from azure that the machine has been shut down. So the services running on it if any would be offline until 26th when my subscription is reset.
So I'd confirm with you about it.

Thank you and sorry for the inconveniences.

**Comment by danepowell** [comment]
As of a few minutes ago, progress sync has stopped working for me on all devices, and it's actually blocking Koreader execution entirely on Android (it's presumably hung waiting for a server response). I have to think this is connected.

**Comment by Frenzie** [comment]
Yup, everything runs on there. ;-) Thanks for providing it!

(Also I should keep some backup copies of some scripts on there…)

**Comment by danepowell** [comment]
It seems like koreader runs in a single thread, at least on Android. Progress sync should really run in its own thread to avoid blocking page turns, which probably generates a lot of confusion and issues like #9306, or crashing the app entirely when the sync server is down, as happened here.

Should I open a separate issue for this? I'm not sure if it would be dead in the water if there's some technical reason why it can't run in a separate thread.

**Comment by NiLuJe** [comment]
Lua is inherently singlethreaded, so, no it's not going to happen ;o).

**Comment by poire-z** [comment]
Dunno what/how progressync does/work, and what it updates and if the main process needs to know/reload - but these poor-man-threading-ersatz are available:
```lua
local child_pid = ffiutil.runInSubProcess(function(my_pid)...) -- needs a collector to avoid zombies
local completed, result = Trapper:dismissableRunInSubprocess(function() ...) -- if there is some UI
```

**Comment by NiLuJe** [comment]
It's networking, so the idea was to use turbo's bespoke coroutines (and it pretty much was the driving force behind looking inot turbo in the first place, IIRC). Unfortunately, turbo was a crashing mess the last time we tried (granted, that was over ten years ago).

**Comment by poire-z** [comment]
> It's networking

So ? :)
The idea of *RunInSubprocess is to use a simple techno from the 1960s that works everywhere. No need to use the fancy schmancy turbo or threading from the 2000s.

**Comment by Frenzie** [comment]
Also see https://github.com/nikneym/picodns which I bookmarked a while ago. It's related to luasocket not being nice with slow DNS resolution.

**Comment by NiLuJe** [comment]
> So ? :)

It's standalone enough that it could probably do the job, but the main issue is actually with WiFi setup more than what KoSync actually does (which is basically a single HTTP request), and that's our internal state, so we can't just shove it in a fork ;).

**Comment by Frenzie** [comment]
True, but fwiw we can probably still do quite a bit better with coroutines à la Trapper in some cases without jumping to lanes or turbo. But I would imagine the sync plugin uses the small timeout?

**Comment by Hzj-jie** [comment]
I think the binaries are still on the virtual volume, but I just need to start the vm instance on 26.
I noticed the shutdown was caused by overcharging, and the overcharging was caused by a much higher network traffic. It's uncommon, but I cannot tell which services were over used, or abused during last month.

**Comment by Frenzie** [comment]
The binaries should be served via Cloudflare so it would be weird if they used more than usual.

**Comment by NiLuJe** [comment]
> True, but fwiw we can probably still do quite a bit better with coroutines à la Trapper in some cases without jumping to lanes or turbo. But I would imagine the sync plugin uses the small timeout?

The issue is that coroutines would have to be plugged into the main loop to be used in a truly meaningful (i.e., async) way, which is what the turbo integration in the main loop was doing.

What Trapper does works because it's used for things that we expect to "block" on, but just want to be able to cancel.

(Granted, that's better than blocking, period, but since this isn't an UI task, it feels like it would fall more in the turbo usecase than the Trapper one ;)).

**Comment by NiLuJe** [comment]
> Granted, that's better than blocking, period, but since this isn't an UI task at all, it feels like it would fall more in the turbo usecase than the Trapper one ;)).

The trapper approach makes more sense for the actual Wi-Fi stuff, though; but the fact that this relies on a lot of lower level moving parts might make this complicated in practice ;o).

**Comment by Hzj-jie** [comment]
I just started the vm. But I cannot recall if I need to start the services manually.

**Comment by Frenzie** [comment]
Yeah, they weren't added to init.d/systemd. I started them, thanks!

**Comment by Frenzie** [comment]
@Hzj-jie Btw, can it upgrade to a newer LTS within the VM or would that be technically problematic somehow (like with some of those KVM systems)?

**Comment by Hzj-jie** [comment]
Yes I think so, and likely it needs to be migrated to a different vm type. I am not sure how the virtual volume would be preserved. I will create a new bug to track the effort.

**Comment by ilyats** [comment]
If case others haven't noticed, ota.koreader.com is down again since about a weak ago. Latest version on mirrors is 2023.06.1-94 dated 2023-08-19.

**Comment by ilyats** [comment]
The server is down again, latest APK on a mirror are from 08/23/23

**Comment by Frenzie** [comment]
Discussion in https://github.com/koreader/koreader/issues/10615
