### ISSUE TITLE
@font-face in styletweaks not working

### ISSUE THREAD

**Issue by yuanshuai0217** [koreader/koreader#10604]
* KOReader version: v2023.05.1
* Device: moaan mix7 (with Android 11)

#### Issue

Adding `@font-face` in styletweaks can not change the font apperance.

#### Steps to reproduce

Here are the epub book file and css styletweak file for testing:

[font_test.epub.zip](https://github.com/koreader/koreader/files/11846017/font_test.epub.zip)

```html
<style>
@font-face {font-family:"times"; src: local("Times New Roman"), local("FreeSerif")}
</style>

<body>
  <p style="font-family:times">This is a paragraph in Times.</p>
  <p style="font-family:timesltstd">This is another paragraph in Times.</p>
</body>
```

[font-tweak.css.txt](https://github.com/koreader/koreader/files/11846018/font-tweak.css.txt)

```css
@font-face {font-family:"timesltstd"; src: local("Times New Roman"), local("FreeSerif")}
```

With tweak enabled, the book will look like:

![Reader_2023-06-23_153530](https://github.com/koreader/koreader/assets/31814374/a46f590f-a259-49b0-aedf-0bf45ee73a8e)

**Comment by poire-z** [comment]
It looks like `@font-face` support is quite dedicated : it's not handled by our generic stylesheet parser, but by the epub parser only. At EPUB reading time, we quickly check for `@font-face` at the start of each embedded .css files, and at the start of each `<head><style>`, just to gather the name and urls of the font files, to register these font files in our font manager.
We don't do it for .html and other formats.
We also don't do it for "user agent" stylesheets, that is: our epub.css or html5.css, to which we APPEND all styletweak content.
Moreover, per specs, `@font-face` should come first in a stylesheet - so if they would come from a styletweak, they will be at the bottom of the user agent stylesheet, and the content before coming from epub.css would prevent them from being parsed.

So, given the complexities, and the limited use case (there are probably other ways to achieve that if you're not using `url(...fontfile.ttf)`, ie. just overriding `font-family: FreeSerif !important` with the font you want for the affected elements), this will probably not be fixed.

**Comment by yuanshuai0217** [comment]
> It looks like `@font-face` support is quite dedicated : it's not handled by our generic stylesheet parser, but by the epub parser only. At EPUB reading time, we quickly check for `@font-face` at the start of each embedded .css files, and at the start of each `<head><style>`, just to gather the name and urls of the font files, to register these font files in our font manager. We don't do it for .html and other formats. We also don't do it for "user agent" stylesheets, that is: our epub.css or html5.css, to which we APPEND all styletweak content. Moreover, per specs, `@font-face` should come first in a stylesheet - so if they would come from a styletweak, they will be at the bottom of the user agent stylesheet, and the content before coming from epub.css would prevent them from being parsed.
> 
> So, given the complexities, and the limited use case (there are probably other ways to achieve that if you're not using `url(...fontfile.ttf)`, ie. just overriding `font-family: FreeSerif !important` with the font you want for the affected elements), this will probably not be fixed.

Thanks for your reply. I’ll detail this problem in a new (feature-requesting) issue.

**Comment by poire-z** [comment]
We both detailed it above :) no need to create another issue/FR.
