### ISSUE TITLE
Lighting settings change erratically and show wrong value

### ISSUE THREAD

**Issue by NextTherapist** [koreader/koreader#10628]
* KOReader version: 2023.04
* Device: Tolino shine 3

#### Issue
The lighting settings seem not to be stable during the usage of the Tolino. 
- Plugging it to USB port to download new books and plugging off again seems to change the lighting intensity. 
- Switching between KOReader and the standard Tolino Reader, too.
- Changing lighting intensity inside the KOReader App seems not to change the displayed lighting value - not until you end and restart the application.

**Comment by pazos** [comment]
Yes. The light settings you apply on KO only have effect when the app is in the foreground.

> Changing lighting intensity inside the KOReader App seems not to change the displayed lighting value.

That's unexpected and a bit weird, given that we have feedback for a few different tolino owners in the past.

Assuming your device is at least android 4.3 then patches welcome!
