### ISSUE TITLE
FR: Open QuickMenu pop-ups at location of gesture

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10631]
As most KOReader users would surely attest to, QuickMenus have made accessing the countless menu options a breeze without having to memorize too many or too complex gestures.

As it currently is, the QuickMenu pop-ups always open centered on the screen. For even faster and easier selection of one of the options after calling a QuickMenu, opening the pop-up near the location of the gesture would make the feature even better in my opinion. 

E.g., if called via a corner gesture, open the QuickMenu in the respective corner; or if called via a gesture from somewhere in the middle of the screen, open it in that area of the screen. 

**Advantages:**

- Faster and more efficient user experience (less hand movement required)
- Will more often be able to be operated one-handed (e.g., call QuickMenu from bottom right hand corner with thumb, select option also with thumb. Currently this would in all likelihood require the use of another finger or moving the device in one's hand to reach the menu with the same thumb.)

**Example** (QuickMenu called from bottom right corner):

![Reader_2023-07-02_142014](https://github.com/koreader/koreader/assets/95502269/91343269-622b-4e51-a44d-acc086a464cb)

(Note: On my installation I have tweaked the QuickMenu window size to be more narrow, which I believe would also help with this FR, but is not strictly necessary for the advantages proposed here.)

**Comment by NiLuJe** [comment]
I have (very) vague memories of @poire-z discussing his experience with this when developing the widget itself, but I can't quite remember much of it beyond that ;p.

As far as I'm concerned and in a vacuum, the idea sounds sensible, but I'm neither a gesture not a quickmenu user, so eh' ;).

**Comment by poire-z** [comment]
I just added support for a `anchor =` (function returning a Geom object) to ButtonDialog (which is used for QuickMenu), that is currently used when opening the ones we want to appear as popup menus.
The problem for the above would be to pass the gesture coordinates via the event down to Dispatcher that is the one showing the ButtonDialog, so it can set that anchor property.
Not much familiar with Dispatcher and the profiles & gestures plugins to tell much more.

**Comment by yparitcher** [comment]
Pass the gesture object as a second argument here: https://github.com/koreader/koreader/blob/b24059b2cb2f24016f82f41a3dc7698a2c313e77/frontend/dispatcher.lua#L1027

Somewhere in `_showAsMenu` figure out x,y from the gesture (depends on the gesture type).
Then add a anchor here: https://github.com/koreader/koreader/blob/b24059b2cb2f24016f82f41a3dc7698a2c313e77/frontend/dispatcher.lua#L1009

**Comment by jonnyl2** [comment]
Thank you to all devs for implementing this FR. I'm really enjoying this feature. Works exactly as expected and makes QMs much more convenient. 💯
I hope it will be popular among other users as well.
