### ISSUE TITLE
FR: Port aard or slob-format

### ISSUE THREAD

**Issue by x3oo** [koreader/koreader#10630]
**Does your feature request involve difficulty completing a task? Please describe.**
Offline wikipedia isnt possible with current dicts.

**Describe the solution you'd like**
aard dict is a solution that provides wikipedia, other wikis and other dictionaries to provide wikipedia offline. Aard is using the slob-fileformat for its dictionary lookup. You could make the slob format accessible.
https://aarddict.org/
https://github.com/itkach/slob
https://github.com/itkach/

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by Frenzie** [comment]
Duplicate of #2333.
