### ISSUE TITLE
frequent crashes/unresponsive on android tablet (was working fine some months ago)

### ISSUE THREAD

**Issue by unusualpepe** [koreader/koreader#10644]
* KOReader version:
v2023.05.1 but also a previous version (unknown to me)

* Device:
Lenovo Tab M10 Plus (Android 12)

#### Issue

I've been experiencing some crashes while using the "Translate" function on highlighted text, and also, during the translation, Android po
[crash.log](https://github.com/koreader/koreader/files/11952320/crash.log)
ps a message saying the app is unresponsive (but everything in the app is working apparently right, the translation had been in most cases already fetched and I was reviewing it).

This was not happening some months ago, as I was reading books and using the translation function every day just fine. After experiencing this unusual behavior I updated to the version mentioned above, but the behavior continues.

#### Steps to reproduce

Open a book, select a sentence and click on "translate". It does not always crash, so this might not be the only way to reproduce/might not be related to the translation function at all.

##### `crash.log`

[crash.log](https://github.com/koreader/koreader/files/11952324/crash.log)

I have just enabled verbose debug in the Developer options, so if the current log is not enough, I will be happy to provide additional logs on request, as soon as I experiment new crashes.

Thanks.

**Comment by pazos** [comment]
There're a bunch of lines like that

```
07-03 23:16:40.385 I/KOReader(13505): Inhibiting user input
07-03 23:16:40.809 I/KOReader(13505): Restoring user input handling
07-03 23:17:38.514 I/launcher.fdroi(13505): Thread[5,tid=13511,WaitingInMainSignalCatcherLoop,Thread*=0xb40000742fe44b20,peer=0x12fc01c0,"Signal Catcher"]: reacting to signal 3
```

The last line indicates that something blocked the main/ui thread for a long time so the framework decided to kill it. Not sure what is causing this.

The lines happen after input handler inhibiting/restoring so might worth to investigate that.
Maybe the translator uses a coroutine to fetch data?. That could explain why the input processing is restored earlier (a minute before the crash in the example above).

**Comment by unusualpepe** [comment]
Let me know if there's anything I can do.

**Comment by pazos** [comment]
Same underlying cause as in #10644.
