### ISSUE TITLE
KOReader cant start with PocketBook Inkpad 4 (PB743G) new firmware

### ISSUE THREAD

**Issue by mezvadasz** [koreader/koreader#10643]
* KOReader version: "koreader-pocketbook-v2023.05.1" and "koreader-pocketbook-v2023.06"
* Device: PocketBook Inkpad 4 (PB743G)

#### Issue

After installed the fresh new PocketBook firmware (v 6.8.1719) the KOReader won't start.

(The issue resolved locally by editing the file: /applications/koreader/frontend/device/pocketbook/device.lua
I replaced the line 
elseif codename == "PB743g" or codename == "PocketBook 743g" then
with
elseif codename == "PB743g" or codename == "PocketBook 743g" or codename == "PB743G" then

After it, KOReader started without error and seems to work normally.
It seems, that the new firmware replaced the "g" to "G" in the model name.)

#### Steps to reproduce

Install new firmware.

##### `crash.log` (if applicable)

 [*] Version: v2023.06

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
ffi.load: inkview
07/04/23-19:48:35 INFO  SoftwareVersion:  U743g.6.8.1719 
./luajit: frontend/device/pocketbook/device.lua:771: unrecognized PocketBook model PB743G
stack traceback:
	[C]: in function 'error'
	frontend/device/pocketbook/device.lua:771: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:61: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x00013f5d
!!!!
Uh oh, something went awry... (Crash nÂ°5: 07/04/23 @ 19:48:35)
Too many consecutive crashes, aborting . . .
!!!! ! !!!!

**Comment by Frenzie** [comment]
An obvious thought is case insensitive matching, or is there a realistic risk of a 743g and 743G being different models in combination with another number?

**Comment by mezvadasz** [comment]
According to KOReader device.lua file, each PB has unique number in model name.
Furthermore, the PB software (firmware) versions seems completely unique (independently from the model). So far, (according to PB homepage) there were only two firmware for my Inkpad 4: 6.8.885 and 6.8.1719. and Google can not find any other devices with these fw versions. In the KOReader crash.log, my device had "SoftwareVersion:  U743g.6.8.885" before (old, KOReader-compatible fw), and "SoftwareVersion:  U743g.6.8.1719" now (new, uncompatible fw).
I am a very new PocketBook user, but based on the above, I think there is not a realistic risk of a 743g and 743G being different models.

**Comment by Frenzie** [comment]
I mean forward-thinking, all of them could be replaced by

```
matchCaseInsensitive(codename, "PBwhatever")
```

**Comment by Frenzie** [comment]
Whoops, life got in the way and I forgot. Fixed by #10655, thanks @ElimGarak1

**Comment by ElimGarak1** [comment]
The PocketBook InkPad 4 is identical hardware. The difference between PB743g and PB743G is only in the software version.

- Here is an example;
with firmware 6.8.885:
![scr0006](https://github.com/koreader/koreader/assets/84080014/bfd03d11-4b6d-452a-9a1e-af27e74b65d7)

with new firmware 6.8.1719:
![scr0007](https://github.com/koreader/koreader/assets/84080014/61159818-a226-4e98-a8e0-599e5745e513)

[ #10655](https://github.com/koreader/koreader/pull/10655) causes KOReader to start with PB743g (with older firmware) and PB743G (with newer firmware).

[crash.log](https://github.com/koreader/koreader/files/11984134/crash.log)
