### ISSUE TITLE
French translation: Wallabag menu incorrectly translated as Marque-Page in 2023.05.1 → 2023.06 update 

### ISSUE THREAD

**Issue by Merinorus** [koreader/koreader#10650]
* KOReader version: 2023.06
* Device: Kobo Libra H2O

#### Issue

Hello!
The Wallabag menu seems to have disappeared on Koreader since the last update. It seems it was there on the 2023.05.1 update.

#### Steps to reproduce

- have a previous version and check that the Wallabag menu exists
- update to the 2023.06 (main channel): the menu disappeared

The latest dev channel version didn't fix the problem and a manual update to the 2023.05.1 version put Koreader in a bootloop:
````log
./luajit: frontend/ui/widget/filechooser.lua:222: attempt to compare two nil values
stack traceback:
	frontend/ui/widget/filechooser.lua:222: in function <frontend/ui/widget/filechooser.lua:219>
	[C]: in function 'sort'
	frontend/ui/widget/filechooser.lua:257: in function 'genItemTableFromPath'
	frontend/ui/widget/filechooser.lua:100: in function 'init'
	frontend/ui/widget/widget.lua:46: in function 'new'
	frontend/apps/filemanager/filemanager.lua:133: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:413: in function 'init'
	frontend/ui/widget/widget.lua:46: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1140: in function 'showFiles'
	./reader.lua:300: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 07/06/23 @ 08:09:18)
Running FW 4.37.21582 on Linux 4.1.15-00417-g0c800cffe1f9 (#102 SMP PREEMPT Mon Mar 29 09:24:11 CST 2021)
```

Unfortunately, I'm unable to reproduce the bug since I cannot start Koreader anymore.

**Comment by Frenzie** [comment]
The crash.log would be extremely relevant ;)

**Comment by hius07** [comment]
Two different issues, I think.
Looks like you have file browser setting Sort by "date", not supported in 2023.05.1.
To start version 2023.05.1 please manually change `["collate"] = "date"` to `["collate"] = "strcoll"` in settings.reader.lua.

To investigate the wallabag issue: is the plugin enabled in More tools menu?
If yes and doesn't show up, look into the crash.log.

**Comment by Merinorus** [comment]
Indeed the crash was related to the version rollback. Modifying the `.adds/koreader/settings.reader.lua` file fixed the boot loop issue. Thank you!

So let's return to the 2023.05.1 version: the "Wallabag" menu is there and I can tick/untick it in the plugin menu.
After the 2023.06 update: the "Wallabag" disappears from both the main menu and the plugin menu.

So... the issue is confirmed from the 2023.06 version!

**Comment by Merinorus** [comment]
There are some UI error codes but I'm not sure... I did the following:
- Boot on 2023.05.1
- Update to 2023.06
- Exit to Kobo firmware to manually rollback to 2023.05.1 (USB mass storage mode)
- Boot on 2023.05.1 again

Here is the `crash.log` extract:
[2023-07-06-crash.log](https://github.com/koreader/koreader/files/11970242/2023-07-06-crash.log)

**Comment by Frenzie** [comment]
The Wallabag plugin hasn't changed since https://github.com/koreader/koreader/pull/10147 btw.

But yeah, I don't see anything mentioning Wallabag in those logs. For reference, if it crashed it'd look something like this:

```
07/06/23-18:23:16 WARN  Error when loading plugins/wallabag.koplugin/main.lua plugins/wallabag.koplugin/main.lua:5: '=' expected near 'local'
```

**Comment by NiLuJe** [comment]
You can enable debug logging, that'll tell us whether we actually even *attempt* to load the plugin at all. And, since you'll be near the Tools menu for that, do check that it actually *is* enabled in the plugin management ;).

**Comment by Frenzie** [comment]
Warnings aren't logged without going verbose? That seems unwise if so.

**Comment by NiLuJe** [comment]
Yeah, but that would be a hint that either the file is missing/unreadable, or the plugin is actually disabled ;).

Or that the plugin has loaded and the menu just went... somewhere ;D.

**Comment by Risike** [comment]
Same issue here. No Wallabag menu appear... And no wallabag relative text in the crash.log.

**Comment by supersarma** [comment]
Hi there. Same issue here but I was able to find something...
I am using the app in **French** and seems something went wrong with translation.

Solution : Set the app on English : 
- Menu
- Languages
- Select Englsh

You well be able to see the Wallabag as usually. 
In French, instead of Wallabag, it show "**Marque-Pages**" which means "Bookmark"

If you are not able to see the Wallabag menu in your language, follow these steps (translete it in your language) :
1. Open KOreader
4. Click somewhere in order to open KOReader Toolbar (top on the screen)
5. Click on the "hamburger" menu (right up corner)
6. Click on "Help"
7. "Menu Search"
8. Search for Wallabag 
It will show you where is the Wallabag menu.

**Comment by Frenzie** [comment]
Perhaps we should include language in the issue template?

Anyway, this seems to have been fixed recently already.

![image](https://github.com/koreader/koreader/assets/202757/f89b6b94-8b75-42a7-bf9e-460a4dcbc0ec)
