### ISSUE TITLE
FR: Toggle on whether clockwise rotation should invert page buttons, or userpatch workaround

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [koreader/koreader#10659]
**Does your feature request involve difficulty completing a task? Please describe.**
The Kindle 4 has a pair of buttons on each side - a small one on top (page back) and a bigger one below it (page forward). When you rotate the device clockwise, the buttons are oriented left and right (respectively). 

![kindle](https://i.imgur.com/f6Y0G24.png)

In this orientation, Koreader makes top/bottom (now L/R) act as back/forward (respectively), which is an inversion of the original button scheme.

**Describe the solution you'd like**
While this may be intuitive for some people (because it resembles L/R directions on an actual book), it kind of messes with my muscle memory, which remembers "small button = back, big button = forward". A userpatch or toggle to disable this inversion would be nice.

**Comment by iFUCKINGHATEcomputers** [comment]
On second thought... I think the default scheme might actually be fine to get used to. If anyone from the future has more interest in tweaking this, comment on here.

**Comment by NiLuJe** [comment]
FWIW, one of the "User patch available" issue should have something for that (it'll be a PocketBook issue, because InkView).
