### ISSUE TITLE
FR: Profiles - make an option to "Tap to dismiss notifications"

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10668]
**Does your feature request involve difficulty completing a task? Please describe.**
I use Profiles that define Font face, Font size, Line spacing, Font Weight, and Font Kerning for different font faces that yield in the same number of lines on the page (30). To quickly use trigger them, I assigned them all to one gesture in a Quick Menu. The problem with this many different settings is that I don't get to read the values of all of them.

**Describe the solution you'd like**
Can you please make an option in the Profile menu that allows to `Tap to dismiss notifications` instead of running them out by timer?

**Describe alternatives you've considered**
For now I either go to bottom menu after I triggered a Profile, or trigger it again to read things I missed.

**Additional context**
Yes, there is this `Show past notifications` button that shows all of them, but it is 1) in Top menu - third tab - Screen- Notifications; 2) yet another window to show the information that simply can be instead delayed in its time out.

Thank you!

**Comment by NiLuJe** [comment]
Err, Notifications should *always* dismiss on tap?

**Comment by mergen3107** [comment]
On my device, they show all at once for a second and dismiss.

**Comment by NiLuJe** [comment]
Notifications have a 2s timeout, and they'll go poof on *any* user input (the intent being you cna just ignore them and go on with whatever you ere supposed to do, and that'll dismiss them if that happens before the timeout).

**Comment by mergen3107** [comment]
This is definitely not the case on Android 10 (Onyx Boox Kon-Tiki 2), and never have been.
Here is the zip archive with the video:
[notif_dismiss_1sec.zip](https://github.com/koreader/koreader/files/11995848/notif_dismiss_1sec.zip)

**Comment by poire-z** [comment]
> Notifications have a 2s timeout, and they'll go poof on any user input 

I understand @mergen3107 would prefer if they had no timeout, and would ONLY go poof with tap. Not with time :)

The default of `timeout = 2` is set in frontend/ui/widget/notification.lua, so a user patch to re-set it to false could work (which would apply to all Notifications), if this is a super nice user/use case :) (who reads notification indeed!)

**Comment by NiLuJe** [comment]
Yup; still doesn't explain why they appear to stick for far less time than 2s, though.

(Is timekeeping borked as all hell on Onyx, too?)

**Comment by poire-z** [comment]
> so a user patch to re-set it to false could work 

```lua
local Notification = require("ui/widget/notification")
Notification.timeout = false
```

**Comment by NiLuJe** [comment]
> Yup; still doesn't explain why they appear to stick for far less time than 2s, though.

Hmm, unless they're refreshed via one of those weird android refresh modes that has an internal delay?

**Comment by mergen3107** [comment]
> so a user patch to re-set it to false could work

I could use this for now, but I really wouldn't like to have tap-to-dismiss notifications when I am going through bottom menu settings. For example, when I set the font size via the scroll wheel, I see the font I am setting there, so I don't need notifications for that :D  Or I could just disable bottom notifications... (the only reason I kept them is because of contrast values in pdf).

**Comment by mergen3107** [comment]
I tried this patch by creating a  file `2-notifications-no-timeout.lua`, and it works for the no timeout part. However, when I tap to dismiss, it dismisses the notifications, and then does whatever action is there under the screen, e.g., turn to next page.

Is this expected?

**Comment by poire-z** [comment]
> Is this expected?

Yes it is. Notification has:
`toast = true, -- closed on any event, and let the event propagate to next top widget`
So, you could add `Notification.toast = false` in the user patch. But you'll get the same bad effect I describe below :/

Or, if you would want to only tweak those of dispatcher:
```lua
local Notification = require("ui/widget/notification")

local Notification_init_orig = Notification.init
Notification.init = function(self)
    if Notification.notify_source == Notification.SOURCE_DISPATCHER then
        self.timeout = false
        self.toast = false
    end
    Notification_init_orig(self)
end
```
but then, if you have 5 notifications, you need to tap 5 times to dismiss each of them - they are nowhere considered as a batch, and there's currently no support for that :/
(Moreover, I don't really know why, I got only 2 notifications displayed with this patch, instead of the expected 5...)

So, well, no easy solution (and not even easy for us if we would want to implement that behaviour in the code)...

**Comment by mergen3107** [comment]
@poire-z 
Thanks! I tried that, and revision 1 is better: I only get the first notification to be shown in revision 2 above.
I think I will just resort to using the patch in revision 1, but remember to diagonally swipe when I want to dismiss notifications instead of tapping :D

**Comment by mergen3107** [comment]
From other approaches to that problem, I only can think of having Profiles to be expandable in Quick Menu (as, for examples, are chapter titles with subchapters in TOC). So users can expand and see all items the profile has before applying it. 

There was an option like that, I remember, to show profile as a QM, let me try that...

**Comment by mergen3107** [comment]
OK, so in the Profile 1 (or whatever) - Edit Actions - Show as QM (check). Now, when I summon gesture-QM with Profiles and click that profile, the old QM is closed and the Profile-specific QM is opened. Great!

@hius07 @yparitcher 
Is there an option to make the following:
1) Open Quick Menu with Profiles checked via gesture (as it is now), and leave the single tap on the profile to do the same thing (apply the profile).
2) Add an expandable arrow (or maybe a long tap?) to summon profile-specific QM to see what things are in this profile.
3) In that smaller QM, add a button called "Apply this Profile"?

Another way:
1) Only add a long tap in gesture-QM to show profile-specific QM.


This way I can just disabled the patch above and look into the profile only when needed.

Thanks! And sorry if this is too much what I am asking, you can just say no :D

**Comment by poire-z** [comment]
Well, buttons in QuickMenu currently has no hold_callback for long-press.
Dunno how complicated it would be for each QuickMenu items to also provide some help_text, which could dynamically build from a profile stuff.
(Or even popup the individual components :) as with:
![image](https://github.com/koreader/koreader/assets/24273478/b66e0913-d2ad-47ec-98c1-8ea8bcc1199b) )

Which seems to be what @mergen3107 just wrote while I was writting that :)

**Comment by hius07** [comment]
Maybe so:
-on long-press on any entry of a QM the new QM containing all actions of this entry is shown
-this new QM has a button "Execute all"

**Comment by mergen3107** [comment]
Thanks @hius07 !
This looks like an even better solution
