### ISSUE TITLE
2023.06-20 nightly not on all platforms

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10661]
Hey guys,

Did something happen to the compilation of -20 nightly? I can only see builds for kobo, both kindle types, and cervantes.

Thanks!

**Comment by Frenzie** [comment]
Not with the compilation, but somewhere along the way they must've got lost.

https://gitlab.com/koreader/nightly-builds/-/pipelines/924955585

**Comment by mergen3107** [comment]
Can I help diagnose this somehow?

**Comment by Frenzie** [comment]
It was probably just a minor Gitlab issue of some sort, for example https://gitlab.com/gitlab-com/gl-infra/production/-/issues/15997

It's hardly worth worrying about unless it persists. :-)

**Comment by mergen3107** [comment]
@Frenzie 
Thanks for the heads up :D 

I just wanted to test “Quick Menu Anchoring - 3” PR, I’ll resort to compiling the debug apk for now 😅

**Comment by mergen3107** [comment]
By the time I gave up on building Android apk (bunch of errors, again), the server received the new apk builds :D

**Comment by Frenzie** [comment]
Haha, well, there you go. :+1:
