### ISSUE TITLE
FR: Anki plugin for Koreader

### ISSUE THREAD

**Issue by unacceptablet** [koreader/koreader#10676]
Hello, good people.

Is it possible to create an Anki plugin for Koreader which auto adds looked-up words (and their dictionary definitions) and synchs to Anki ?

Like this but for android e-ink devices: https://github.com/Ajatt-Tools/anki.koplugin

Link to their API: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API

Thanks in advance.

**Comment by Frenzie** [comment]
On Android use `/sdcard/koreader/plugins` (and probably our build instead of the F-Droid flavor).

**Comment by pazos** [comment]
>  (and probably our build instead of the F-Droid flavor).

I *think* plugins ough to work as is on both flavors. Not sure if that's a feature or an attack vector, but I'm fine calling it a feature :p

**Comment by unacceptablet** [comment]
Alright. I managed to follow [this tuorial](https://github.com/Ajatt-Tools/anki.koplugin) untill step 3 after which I need SSH in Koreader. But my Koreader on android does not have this feature.

So,
1. Any plan to add SSH in Koreader (android)?
2.  In absence of SSH, is there any other way to synch to Anki?
3. Can the ankidroids [API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API) be used to directly synch to anki from Koreader?

**Comment by Frenzie** [comment]
No, but step 3 is just a slightly complicated way of saying "copy this folder".

**Comment by unacceptablet** [comment]
> No, but step 3 is just a slightly complicated way of saying "copy this folder".

I copied the anki.koplugin folder and it has been installed successfully. But its the synching via SSH that is not working.

**Comment by Frenzie** [comment]
It's just using HTTP from the looks of it.

https://github.com/Ajatt-Tools/anki.koplugin/blob/67a3b9e988e82ab0964e23893afe64b447e9d276/config.lua#L6-L11

It looks like localhost can also be Android.
https://github.com/KamWithK/AnkiconnectAndroid

**Comment by unacceptablet** [comment]
> It's just using HTTP from the looks of it.
> 
> https://github.com/Ajatt-Tools/anki.koplugin/blob/67a3b9e988e82ab0964e23893afe64b447e9d276/config.lua#L6-L11
> 
> It looks like localhost can also be Android. https://github.com/KamWithK/AnkiconnectAndroid

Note understood. Can you please give me a clear step-by-step instruction?

**Comment by Frenzie** [comment]
I don't know it either so not really. But it says you need to run AnkiConnect somewhere with an IP and port of where it runs.

In case you run it on the same device that'll be something like http://localhost:8765 as per the sample config.

**Comment by unacceptablet** [comment]
> I don't know it either so not really. But it says you need to run AnkiConnect somewhere with an IP and port of where it runs.
> 
> In case you run it on the same device that'll be something like http://localhost:8765 as per the sample config.

I installed [AnkiconnectAndroid](https://github.com/KamWithK/AnkiconnectAndroid), put http://localhost:8765/ in CORS Host settings, start service. When I press add to anki, I get these errors:

![image](https://github.com/koreader/koreader/assets/127971612/751223b6-3cc2-4754-803b-142d6a2aac91)

Any solution?

**Comment by Frenzie** [comment]
I'd try asking the author.

**Comment by unacceptablet** [comment]
Alright. Thanks. I will request the devs of AnkiconnectAndroid.

**Comment by pazos** [comment]
> Alright. Thanks. I will request the devs of AnkiconnectAndroid.

The suggestion was to ask to the authors of the plugin, in their repo: https://github.com/Ajatt-Tools/anki.koplugin

They will know better than us as they're already using anki, anki tools and wrote a plugin for KOReader.

Please try to explain to them what you're trying to achieve, so they will let you know if that's feasible on the first place and/or the workarounds you have available.
