### ISSUE TITLE
"Sort by last read" option dissappeared in file explorer

### ISSUE THREAD

**Issue by AxelSkye** [koreader/koreader#10695]
* KOReader version: 2023.06.1
* Device: Kobo Libra 2

#### Issue
In file explorer ordering options, "sort by last read" option dissappeared, I can sort by name, date modified (the file itself), file type, etc. but "by last read" option, which previously was available, is not there anymore. Already tried rebooting koreader, restoring settings and reinstalling.

#### Steps to reproduce
Go to Menu > File explorer > Sort by..> "last read" option is not there.

**Comment by benoit-pierre** [comment]
See https://github.com/koreader/koreader/pull/10682.

**Comment by AxelSkye** [comment]
Oh, I was looking if it existed beofre but didn't find it. Sorry and thank you!
