### ISSUE TITLE
./kodev run android fails 

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10699]
* KOReader version: 2023.06.1-24
* Device: Ubuntu MATE 22.04 VM

#### Issue
Freshly running `./kodev run android` fails after a few minutes of building with this in the end:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:externalNativeBuildArmRocksDebug'.
> Could not resolve all dependencies for configuration ':app:armRocksDebugRuntimeClasspath'.
   > Could not create task ':app:minifyArm64FdroidReleaseWithR8'.
      > Failed to find Build Tools revision 30.0.2
```

#### Steps to reproduce
I had severe problems with Android building in recent weeks.
In the end I nuked all my previous koreader directories and started afresh by git clone, etc.

First issue I had was that sdkmanager was throwing XMLschema error. This seemed to be solved by accepting all licenses (with Android Studio installed with API 29) first in koreader/base/toolchain/android-sdk-linux/tools/bin :
`sdkmanager --licenses`
Then it started to build after `./kodev run android`, but fails.

Can you please help me a little?
Thank you!

My goal is just to have fun with building debug apks, nothing serious.

**Comment by mergen3107** [comment]
Full terminal log:
[koreader_error.txt](https://github.com/koreader/koreader/files/12063087/koreader_error.txt)

**Comment by NiLuJe** [comment]
I have *never* used `kodev android run` (I couldn't even tell you what the hell it does).

I've always build a real APK, signed it (or not if debug), uninstall the previous version if key change or necessary for testing reason, run `adb install fancy_new.apk` and voilà.

**Comment by mergen3107** [comment]
Thanks @NiLuJe for your quick reply!

I tried the `./kodev release android` and it gave a proper explanation: I was missing API 30 in Android studio. Next run told me that licences were missing, so I copied the `licenses`from `~/Android/SDK` to `~/koreader/base/toolchain/android-sdk-linux/` and it worked!

Now, `./kodev run android/` also works now, it seems to be building the apk and then switching to adb to install/run with these in the end:
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
- waiting for device -
```
Didn't connect to the reader yet, probably will try later.

This ticket is now solved, thank you!

**Comment by Frenzie** [comment]
> I've always built a real APK with kodev release android, signed it (or not if debug), uninstalled the previous version if key change or necessary for testing reasons, then ran adb install fancy_new.apk and voilà.

You just described what it does (except it also runs it).

**Comment by mergen3107** [comment]
I am having a blast with `./kodev run android` - it so quick to test changes on the fly! Also, without spoiling my main KOReader build for actual reading :D

**Comment by melyux** [comment]
Is there a way to sign the APK from inside the `koreader/koandroid` Docker container?

**Comment by Frenzie** [comment]
Docker just packages some prerequisites, the instructions are otherwise identical?

**Comment by melyux** [comment]
Found the pages. Ran into a problem with the latest `koreader/koandroid:0.6.0` image for the virtual environment. The release build failed with

> error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

Had to do `sudo apt install libncurses5` and then re-run the release command. This time it worked
