### ISSUE TITLE
Hidden nav elements aren't actually hidden

### ISSUE THREAD

**Issue by Leseratte10** [koreader/koreader#10703]
* KOReader version: latest (2023.06.1)
* Device: Linux

#### Issue

In #6004, support for EPUB3 page lists have been added. However I've been unable to hide the page list from view using the "hidden" attribute. 

#### Steps to reproduce

I have an EPUB with a TOC that contains both chapters and page numbers, like this: 

```
<body>
<nav epub:type="toc" id="toc">
	<h1>toc</h1>
	<ol>
	<li><a href="03_chapter1.html">Test 1</a></li>
	<li><a href="04_chapter2.html">Test 2</a></li>
	</ol>
</nav>
<nav epub:type="page-list" id="page-list" hidden="">
	<h2>pages</h2>
	<ol>
	<li><a href="./03_chapter1.html#page5">5</a></li>
	<li><a href="./03_chapter1.html#page6">6</a></li>
	<li><a href="./03_chapter1.html#page7">7</a></li>
	</ol>
</nav>
</body>
```

The TOC is intended to be displayed to the user to be able to jump to specific chapters. The page list isn't (because a list of all ~300 pages of a book is annoying) so it has the [`hidden=""` attribute](https://www.dofactory.com/html/nav/hidden) to make it invisible. 

This works fine in readers like Calibre (and on my physical Pocketbook eReader), and epubcheck also doesn't complain, but KOReader seems to ignore the "hidden" attribute and still displays the page list. 

Am I doing something wrong with the book or is this a bug in KoReader? I mean, I could just set a CSS style or something to completely hide that element, but why, when "hidden" should already do that.

I have attached the EPUB file (with all the actual content removed so there's no copyright issues). When I open it in Calibre or other readers, it just shows the Table of Contents. When I open it in KOReader 2023.06.1, it shows both the ToC and the page list. 

[ufo.zip](https://github.com/koreader/koreader/files/12063931/ufo.zip)

**Comment by poire-z** [comment]
We indeed have no specific support for hiding them.
I wasn't aware of the nav attribute `hidden`. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav doesn't mention it.
Although there is https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden.

Is it also not handled in our html5.css (https://github.com/koreader/crengine/pull/300) which was supposed to have us behave more like current browsers.

Moreover, publisher don't have to include it in the fragments that make up the book. If it is in the opf, it is enough for the reading app to allow access to it via other means (our menu). If it is part of the book pages, we may as well show it :) And if we hide it, users can't see it.
Also, why include it with `hidden=` ?

Dunno if we should really in our stylesheets (epub.css, html5.css) really hide all things with an attribute `hidden=`.
Anyway, you can solve it with a style tweak (may be we should add one into Miscellaneous> ?
`[hidden] { display: none; }`

**Comment by Leseratte10** [comment]
If it's not in the fragments that make up the book (= not included in the OPF), then a reader is not going to parse it and use the page numbers in there to display print-book page numbers, is it?

Why include it with hidden=? Because that's the way it's defined in the EPUB3 standard - https://idpf.org/epub/30/spec/epub30-contentdocs-20111011.html#sec-xhtml-nav-def-hidden . The page list (a list of all page numbers in the book) is not something that's useful for the reader, it's used by the reading software (KOReader, in this case) to figure out where in the book a given page number starts. That means it does have to be referenced in the book for software to find it, but not displayed to the user.

**Comment by poire-z** [comment]
It can be included in the opf for it to be known, but it may not have to be in the `<spine>` that states the order of fragments to be concatenated and shown as the book.

In one of my epub with a nav, I have in the opf:

```xml
    <item id="ident1-2" href="ident1-2.xhtml" media-type="application/xhtml+xml"/>
    <item id="nav" href="nav.xhtml" properties="nav" media-type="application/xhtml+xml"/>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
...
  <spine toc="ncx">
    <itemref idref="html-cover-page"/>
    <itemref idref="rights567"/>
...  <!-- no itemref with idref=nav or ncx among these -->
    <itemref idref="ident1"/>
    <itemref idref="ident1-2"/>
  </spine>
```
And KOReader and other software should be able to find and use it (in their other UI parts related to TOC and NAV, not in the books).

**Comment by Leseratte10** [comment]
If I understand the standards correctly, then that's not possible. 

The item has to have "properties=nav" to be considered a navigation, and there may only be ONE item with that nav property. 

This means if I have a table of contents (which I want to be visible) and a page list (which I want to be hidden), and I would do that by having them in two different HTML files to be able to add one to the spine but omit the other, then I'm not allowed to give them both the properties=nav tag, and a standards-compilant reading software may not parse them.

**Comment by poire-z** [comment]
> What downside would there be to just globally hide all elements with a "hidden" attribute? Just in case there's a broken book that has actual text marked as hidden? But these would then be broken on most other readers anyways.

That's what we're going to discuss here :)
I'd be more inclined to add it just for nav (`nav[hidden] { display: none; }`) as 1) it's available via other UI means and 2) it's what the publisher means.

I'm not so keen on hiding all elements with an attribute `hidden` - even if it's in the HTML5 specs. We may not just be fed compliants EPUBs - user may save some old webpage as html or epub and expect to see as much of them.
But if there is in the CSS `style="display: none"`, we indeed hide it.
So, well :)

But it already is in our html5.css ! So, just use it :) And allow our epub.css to diverge from the standard (which it already does):

```css
/* Hidden elements */
[hidden], area, base, basefont, datalist, head, link,
meta, noembed, noframes, param, rp, script, source, style, template, track, title {
  display: none;
}
```
Note that it also has:
```css
tfoot, tfoot[hidden] {
  display: table-footer-group;
}
tr, tr[hidden] {
  display: table-row;
}
```
Also, not that simple: https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute

**Comment by poire-z** [comment]
Anyway, nothing against adding `nav[hidden] { display: none; }` into our (default) epub.css, and close this specific issue about hidden nav parts.

**Comment by Leseratte10** [comment]
> I'm not so keen on hiding all elements with an attribute `hidden` - even if it's in the HTML5 specs. We may not just be fed compliants EPUBs - user may save some old webpage as html or epub and expect to see as much of them.

That's true and I did forget about that - if HTML5 adds that attribute you can't be sure if some publisher in an HTML4 book used that attribute for another purpose. 

> But it already is in our html5.css ! So, just use it :)

Interesting, didn't know that this existed. I'm not a regular KOReader user, just tried to find an application to test my page maps with (as my eReader doesn't support these yet), found KOReader, and noticed the bug and reported it. When I switch to html5.css it's indeed gone. (Even though I don't understand why, since "nav" doesn't appear in the list of hidden elements in the html5.css).

**Comment by poire-z** [comment]
I'll add it in our epub.css - may take a few weeks (until the next batch of crengine fixes) to reach KOReader.

It's also possible web pages uses that attribute `hidden` with its expected behaviour - but have some javascript means to reveal their content with user interaction. (Which is also possible if it uses` div.showIfRequested { display: none; }` which we will indeed hide...)
