### ISSUE TITLE
Standard Ebooks images do not render

### ISSUE THREAD

**Issue by Whayme** [koreader/koreader#10711]
* KOReader version: 2023.06.1
* Device: Kobo Sage

#### Issue
Every format of Standard Ebooks (whether obtained through the website or the OPDS repository available by default) will not render the cover image correctly, instead only leaving text.  These _do_ render correctly in Nickel and Plato.  I'll note that images in other ebooks generally seem to work but are displayed at extremely small sizes that I don't see in Nickel or Plato, often to the point where they don't even fill the small thumbnail despite being near the device's full resolution or larger.
#### Steps to reproduce
Download any standard ebooks format and view the cover either in the file view or in the document itself.  For example, [Ragged Dick](https://standardebooks.org/ebooks/horatio-alger-jr/ragged-dick) by Horatio Alger Jr.

**Comment by hius07** [comment]
I can see the cover image of the above book in the following ways:
-OPDS catalog: tap the book, choose "Book cover" button
-file browser: choose Mosaic or Detailed list with cover images display mode
-file browser: long-press the book, choose "Book cover" button
-file browser: long-press the book, choose "Bool information" button, tap "Cover image"
-file browser: long-press the book, choose "Open with...", choose "Archive viewer", go to /epub/images folder of the archive, tap "cover.jpg", choose "View" button
-reader: go to the upper menu - Hamburger - "Book information"

The cover image is not displayed as the first page of the book in reader.
Due to Standard Ebooks Section Patterns (https://standardebooks.org/manual/1.7.1/6-standard-ebooks-section-patterns):
_**6.3.1** The Standard Ebooks titlepage is the first item in the ebook’s content flow. Standard Ebooks do not have a separate cover page file within the content flow._

The titlepage (which is an image showing the book author/title as a text) can be found in the epub file as /epub/images/titlepage.png.

**Comment by Whayme** [comment]
In each of those locations I've tested, namely the Mosaic / Detailed with images views, I simply get a text cover with the title and author, not the intended image.  The only exception is the OPDS catalog option for the book cover.  But after downloading the book through OPDS, it acts identically to the versions I put on my device manually.

Apologies for the photos of a screen, I'm not sure how to screenshot on this device.

A folder of different formats and copies of the same book in the mosaic view:
![image](https://github.com/koreader/koreader/assets/63085504/1ffa2c01-68d6-4c66-af9b-291c1a9cb441)

Another standard ebooks file when I long press and choose the "book cover" option.
![image](https://github.com/koreader/koreader/assets/63085504/33f3dd2a-1847-4655-86bd-0ed1f654f619)

**Comment by hius07** [comment]
I've downloaded "Recommended compatible epub" from OPDS:

![1](https://github.com/koreader/koreader/assets/62179190/e483a940-12d9-4e6b-af70-cc2ae74a1d87)

**Comment by Whayme** [comment]
When I download "Recommended compatible epub" it is again only the text cover.  On my machine, it's not only the "Advanced epub" experiencing it.

**Comment by hius07** [comment]
![2](https://github.com/koreader/koreader/assets/62179190/483e6198-c45e-491f-97fe-f9b0fa7128b9)

The first one is "Recommended compatible epub", the second is "Advanced epub".
"Advanced epub" contains "cover.svg" that is displayed.

Please investigate the content of epubs with Archive viewer.

**Comment by hius07** [comment]
Sorry, you need the latest nightly to have a "View" button in the Archive viewer.

**Comment by Whayme** [comment]
After updating to the nightly build and clearing the info cache, I'm able to see the cover.jpg in the compatible epub, where it displays correctly.  However, it still does not display on the mosaic view or contextual "book cover" option even after the cache reset.

**Comment by Whayme** [comment]
Ah, here's something!  When I copy the files from my device to my desktop and view them using the KOreader AppImage of the same version, everything displays correctly.

Is this a Kobo Sage-specific issue, then?

**Comment by hius07** [comment]
> However, it still does not display on the mosaic view or contextual "book cover" option even after the cache reset.

Is it "Refresh cached book information" button in the long-press popup dialog?

**Comment by Whayme** [comment]
I used that as well as the option under "Book info cache management" to "Delete cache database".  On top of that, as I've been testing things I've occasionally used the "Clear caches" option in the developer menu just in case.

**Comment by Whayme** [comment]
Ah, I've found the problem!  I set the default engine to open these up with as MuPDF because it displays the other formatting properly whereas Cool Reader Engine has a pretty ugly result where the text runs to the edges and it generally doesn't seem to respect the formatting of Standard Ebooks files whether they're epub, advanced epub, or kepub.  Anyway, apparently if you change the default engine, that also changes what is used to grab the thumbnails and the like, which explains why it stops displaying.  Apologies for not identifying this in the first place.

I suppose this brings up a different question which may be deserving of its own issue:  Cool Reader Engine does not display these books as other readers do, seemingly incorrectly.  Nickel and Plato both have attractive results.

**Comment by poire-z** [comment]
> as MuPDF because it displays the other formatting properly whereas Cool Reader Engine has a pretty ugly result where the text runs to the edges and it generally doesn't seem to respect the formatting

CRE is our cherished engine, so you'll have to explain that better :)
Anyway, I think we mostly all prefer text justified (runnign to the edges), so that's what our epub.css enforces.
You can try, with the book opened with CRE, 2nd top menu, `Style> [x] html5.css` (instead of epub.css) and you should get the text left-aligned. (After that, you can tweak margins and many things with the bottom menu). Long-press on html5.css if you really want it to apply on all your futur books.

**Comment by hius07** [comment]
Can you describe the issues with CRE?

![1](https://github.com/koreader/koreader/assets/62179190/7f11da4a-80a3-4b78-a992-3507b1010232)

![2](https://github.com/koreader/koreader/assets/62179190/6b72c0a8-7827-4261-aeb8-74c089769698)

The first image is by CRE, the second by muPDF.
I definitely can adjust CRE settings (smaller font, margins, justification etc.) as I need.

**Comment by poire-z** [comment]
![image](https://github.com/koreader/koreader/assets/24273478/c75d320f-5859-45b7-a110-4baa6552d4e0)
Left is their compatible EPUB, Right is their advanced EPUB, a SVG with the background JPEG embedded. Looks like I have a little bug in the SVG support where, for such embedded images, I expect a Document object, so it would have worked if it was used in the book, but the JPEG is not found when the SVG is viewed from outside, like from Book information or file browser.

**Comment by hius07** [comment]
> SVG with the background JPEG embedded

ImageViewer doesn't show it correctly as well (unarchived file).

**Comment by Whayme** [comment]
> You can try, with the book opened with CRE, 2nd top menu, Style> [x] html5.css (instead of epub.css) and you should get the text left-aligned. (After that, you can tweak margins and many things with the bottom menu). Long-press on html5.css if you really want it to apply on all your futur books.

Being able to change it myself is nice and I'm sure I could get it in a state similar to what's intended, but I enjoy Standard Ebooks because of their formatting by default.  They look roughly the same without tweaking in other readers but CRE is far off by default (even with the html5.css or fb2.css options), making it undesirable for them.

> Can you describe the issues with CRE?

Mine does not have nearly that much margin space by default, though that may just be skewed by yours being a screenshot.  It looks cramped onto the page:

![image](https://github.com/koreader/koreader/assets/63085504/5c095cac-a780-4ae7-adb7-7bf99c6643d8)

MuPDF for comparison, also default:

![image](https://github.com/koreader/koreader/assets/63085504/2d92314c-26f7-44d7-833f-15e441b80044)

**Comment by hius07** [comment]
> Mine does not have nearly that much margin space by default

If you do not want to change your defaults, you can adjust just this book as you want and then save all the document settings as a "New profile with current document settings". Then you will be able to apply these settings to any book with just a couple of taps.

I think CRE is more flexible for epub/fb2 than muPDF.

**Comment by Whayme** [comment]
Apologies for the potentially stupid question as someone with no technical knowledge, but is CRE overriding formatting prescribed by the epub that other readers are respecting, or do readers have to define margins and the like on their own?  From my perspective, I have a file that looks great and as intended on every other reader I've used, but which looks quite rough on CRE.  My mental model here is that I have a pre-formatted file which is intended to look a certain way with a little bit of wiggle room for different screens and other readers display that for me, while CRE isn't handling that task as I would expect.  But maybe it _has_ to be reader-defined more than I'm imagining.

However, if that information isn't contained in the epub and it's always a reader making those dispaly decisions (and other readers just *happen* to have similar defaults), I can understand why you wouldn't want to change that as it's a stylistic decision on your part...just one I happen not to like.

**Comment by poire-z** [comment]
If you use html5.css, you should get something as other renderers.
crengine should respect most of the formatting, like margins, indentation, italic...
As for the outside margin, we respect what the publisher has put into the EPUB (for that Ragged Dick EPUB, there is ZERO publisher set outer margin). We add to that the margin _you_ have defined in the bottom menu (and there again, you can set as the default for all your books with long-press).
Other renderers (like our MuPDF) may themselve add some _fixed_ outer margin so indeed the books look not too cramped. So, they probably just add more than our defaults in the bottom menu. Just increase them if you like airy pages.

**Comment by Whayme** [comment]
Got it.  In that case I just don't like the default and that's just a matter of preference, not your problem.  Thanks for the troubleshooting help and explanations.

**Comment by Frenzie** [comment]
There are some de facto standards in default stylesheets that we "break," like indenting paragraphs instead of just having blocks of text with whitespace in between. But a quick peek at the EPUB in the OP doesn't seem to suggest they do anything with margin or padding, leaving that entirely up to the defaults in the program.

calibre for example may come with much larger margins by default because it expects a big screen rather than a small ereader. But in both programs the defaults are easy to change. ^_^
