### ISSUE TITLE
Tap zones outline

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#10716]
Do we need a reminder of the tap zones configuration, accessible from the Taps & Gestures menu?
Sort of this (default configuration, thick vertical line is a page turn frontier):

![1](https://github.com/koreader/koreader/assets/62179190/f72bce17-a231-43c4-8220-78a723a8d581)

**Comment by poire-z** [comment]
No strong opinion about the need for this - but it seems you have already coded it :)
(Also, feels a bit confusing with just the lines, ie in the top row, are these 5 zones? so there's a top left corner, + another zone on its right of the same size :)

**Comment by hius07** [comment]
There are 4 zones at the top of the screen: left and right corners, menu (of the same height) and menu_extension (higher and less wider).
Menu and menu_extension zones are handled separately, both activating the menu.

**Comment by hius07** [comment]
The same in the bottom, plus the footer zone.

**Comment by poire-z** [comment]
I know all that - my point was that your screenshot doesn't make _all that_ obvious. As-is, what it shows may be more confusing than helpful.

**Comment by NiLuJe** [comment]
I mean, even the [color shaded variant](https://github.com/koreader/koreader/pull/6918#issuecomment-735002746) takes a bit of staring at to grok, so readability *could* very well be a concern.

Depending on how you were thinking of implementing that, I could perhaps see an interactive variant where... I was going to say hovering over it, but that doesn't quite make sense for our use-case, so, a tap? will shade the relevant zones.
But most importantly, perhaps stick a big number inside 'em to denote their Z-order? And perhaps letters when their are no conflicts? (Basically, like a key for a map).

**Comment by hius07** [comment]
Sure, I love that colorful picture, I've included it into the user guide at 4pda.ru.
Here I just tried to make a simple outline, available in the program, to help a user to visualize the zones.
Not a complex zones/actions handbook.

Well, it doesn't have a great benefit.
