### ISSUE TITLE
Koreader not in kual menu

### ISSUE THREAD

**Issue by greatlybabled** [koreader/koreader#10712]
Koreader version: pw2 
Kindle version: KT2, 5.12.2.2

Hi there, sorry if this has been asked before, but I am having difficulty running koreader. I have kual and kpv installed and have downloaded and unzipped the koreader folder to the root directory but it doesn't appear in the kual menu. Is there something I am not doing? Thanks.

**Comment by hius07** [comment]
Have you unzipped the "extensions" folder as well? It is shipped in the KOReader installation archive.

**Comment by greatlybabled** [comment]
yes I have, do I need to move both koreader and the extension folder out of the original unzipped folder? I can't put the extension folder in the root directory due to the kual extension folder already exisitng.

**Comment by hius07** [comment]
Yes, the "extensions" folder must be unzipped to the usb-root of the device. It will add a subfolder to the existing folder.

**Comment by hius07** [comment]
You'll get "koreader" subfolder in the "extensions" folder.

**Comment by greatlybabled** [comment]
That fixed it, sorry i was being silly, thanks for your patience.

**Comment by hius07** [comment]
Good luck with using the program.
