### ISSUE TITLE
Clara HD: KOReader suddenly quits when going back to file manager

### ISSUE THREAD

**Issue by jperon** [koreader/koreader#10718]
* KOReader version: 2023.06.1 (and 2023.06.1-28)
* Device: Kobo Clara HD

#### Issue

KOReader suddenly quits when going back to file manager from an open file.

#### Steps to reproduce

1. Open any document
2. Go back to file manager, either by clicking on the icon on top, or by clicking on the dialog entry after the end of the document

The issue doesn’t occur when deleting the file after the end of reading: in that case, it goes back to file manager as usual.

##### Detailed `crash.log` (relevant part only)

[crash.log](https://github.com/koreader/koreader/files/12130303/crash.log)

**Comment by NiLuJe** [comment]
Anything funky/custom about that setup? (i.e., I'm seeing that `COUCOU` logger.info that I'm pretty sure is not stock ;p).

It's exiting sanely with a `07/21/23-17:13:30 INFO  no dialog left to show`, which is usually what happens on, well, exit ;).

**Comment by NiLuJe** [comment]
Oh, and since you mentioned the end of document dialog, does this still happen if you disable that?

**Comment by jperon** [comment]
> Anything funky/custom about that setup? (i.e., I'm seeing that `COUCOU` logger.info that I'm pretty sure is not stock ;p).

Sorry, you lead me to the right origin: it was a "wakeup" of https://github.com/koreader/koreader/issues/7738, cause I copied my [clock](https://github.com/jperon/clock.koplugin) plugin from a backup of my old reader that was out-of-date. Sorry for the noise!

**Comment by NiLuJe** [comment]
Nice catch, I'd completely forgotten about that one ;o).
