### ISSUE TITLE
Language metadata not persisting on PDF documents.

### ISSUE THREAD

**Issue by JasonWilmotGlobal** [koreader/koreader#10729]
* KOReader version: 2023.06.01
* Device: Samsung Galaxy S20 FE 5G

#### Issue
Language metadata does not appear correctly on .pdf documents.  After attempting to correct the files in the `.sdr` folder, the information still did not appear correctly.  I also attempted downloading and creating metadata with Calibre, but it still did not display correctly in KOReader.

#### Steps to reproduce
Version 1
1. Upload pdf to your device to read KOReader.
2. Update the language fields in the metadata files in the `.sdr` folder.
3. Restart KOReader, open the pdf, click the top right menu, then click the 'Book information' button to check the metadata.

Version 2
1. Download pdf's metadata from Calibre.
2. Upload pdf to your device to read KOReader.
4. Open the pdf, click the top right menu, then click the 'Book information' button to check the metadata.

#### Screenshots
Version 1: `.sdr` folder metadata
- Changed all language fields to "es"
![image](https://github.com/koreader/koreader/assets/77940558/d2c7b651-dc6a-4137-a5c3-bc9ab8b26ad4)
![image](https://github.com/koreader/koreader/assets/77940558/22215041-a0c7-449f-b15d-c560f49ca5e3)

Version 2: Calibre metadata
![image](https://github.com/koreader/koreader/assets/77940558/f01c0224-421f-4285-8a84-41b5bee7d342)
![image](https://github.com/koreader/koreader/assets/77940558/7b12a9e5-e3ff-4057-909f-b86b69e5a7f8)

#### Context
I'm trying to import upload KOReader Vocab Builder info to VocabSieve, but the importer does not detect the book since the metadata does not match my target language.  More details can be found here: https://wiki.freelanguagetools.org/vocabsieve_reader_import 

(Also, feel free to give me formatting tips, I don't use GitHub often)

**Comment by hius07** [comment]
Yes, the pdf `language` field is absent in getting doc props function.
https://github.com/koreader/koreader/blob/d350418367ddf39d752d05e0587e562d7d4af2c4/frontend/document/pdfdocument.lua#L328
Custom (edited by a user) metadata is not implemented (yet).
So some modules take it from sdr, others ask the document `getProps()`.

**Comment by hius07** [comment]
Now we have custom metadata.

**Comment by zeeyado** [comment]
> Now we have custom metadata.

Where to edit custom metadata? I tried editing the metadata.pdf.lua in doc_props -> title and also stats -> title but there was no change after refreshing cached book information

**Comment by mergen3107** [comment]
Go to Book Information, long tap fields you want to edit
