### ISSUE TITLE
Frontlight toggle stops working

### ISSUE THREAD

**Issue by hasezoey** [koreader/koreader#10722]
* KOReader version: 8a240dd635d188b1e4178b89d8d109ea9577722e
* Device: Tolino Vision 5 (android 4.4.2 arm)

First version i encountered this issue in is `2023.06.1`
Last version where i know it did not happen is `2023.03`
anything in-between has not been tested yet.

device system did not change aside from koreader

#### Issue

After some time, the frontlight toggle (gesture tap corner) stops working, no frontlight is toggled and no notification about `Frontlight enabled / disabled` shows up.

Changing tap-corner (removing and re-adding, and different corner) does not fix it.

Frontlight control (set brightness and warmth) still work

Restarting the app fixes it.

#### Steps to reproduce

i have not been able to reliably reproduce the issue yet

##### `crash.log` (if applicable)

no crash

---

i could not find anything relating to a error or not working in the logcat yet, its just like that tap corner does not have any action

**Comment by pazos** [comment]
Most likely affects a subset of android devices. Probably just Tolinos. Who knows?

Android support here is a bit of a mess. We support workarounds for more than a hundred devices without access to a single one :p. So help welcome.

> First version i encountered this issue in is 2023.06.1
> Last version where i know it did not happen is 2023.03

You can try to triage a bit more seeing if you can reproduce in monthly versions between .03 and .06, so we can look at the git commit tree without too much noise.

FWIW the backend didn't change at all. So it should be something in this repo.

**Comment by hasezoey** [comment]
i did some testing and it turns out there are multiple levels to this:
- if koreader is started with backlight on, but intensity 0 (ie off), then koreader would in `2023.03` display `Frontlight Enabled` / `Fronlight Disabled`, but change nothing
  in around `2023.04` under the same conditions it would only show `Frontlight disabled` but not actually change anything
  00b3594d442f2c76475ab1c434f12f560848ae02 (bisected) changed that no notification is shown anymore under the same conditions (which is the main reason for this issue being opened)
- next is that when koreader is started with backlight intensity 0, but changed later through (koreaders own) `frontlight widget`, then action `ToggleFrontlight` still works as if it had intensity 0 and requires a app restart
- lastly and i dont know if this is custom android behavior, if in tolino the frontlight has been disabled outside of koreader (like clicking on the status bar would do), the frontlight will not be re-enabled by koreader (but always show a `Frontlight Enabled / Disabled` notification if the intensity is higher than 0)

*with `0` i mean `fl_min`, the minimal intensity, which is effectively off

Things that would improve this:
- show a notification if the intensity did not change on toggle (like in `2023.04`), even just a `Frontlight disabled` would be enough (to know that the gesture is not broken)
- correctly set all variables so that if started with 0 intensity but changed through the `frontlight widget` to actually work without restart

as a aside, it would be great if koreader could log all detected gestures and executed event if debugging (or verbose debugging) is enabled, because i could not find any relation to this in the logs (logcat), something along the lines `Gesture: "tap_top_left_corner", executing "toggle_frontlight"` even if no action has been assigned to that gesture (if possible)

**Comment by hasezoey** [comment]
i also just noticed that `dialogState` is only called once - that is right after the lights dialog has opened, but never once it gets closed, basically making the code dead:
https://github.com/koreader/koreader/blob/d350418367ddf39d752d05e0587e562d7d4af2c4/frontend/device/android/device.lua#L501-L517
action is always `0`, mapped to `ALIGHTS_DIALOG_OPENED`

**Comment by hasezoey** [comment]
the following patch makes that window actually work and actually set the variables so that `ToggleFrontlight` will detect it correctly, though i dont like the implementation:

```diff
--- a/frontend/device/android/device.lua
+++ b/frontend/device/android/device.lua
@@ -499,8 +499,12 @@ function Device:_showLightDialog()
     android.lights.showDialog(title, _("Brightness"), _("Warmth"), _("OK"), _("Cancel"))
 
     local action = android.lights.dialogState()
+    while action == C.ALIGHTS_DIALOG_OPENED do
+        FFIUtil.sleep(1) -- dont pin the CPU
+        action = android.lights.dialogState()
+    end
     if action == C.ALIGHTS_DIALOG_OK then
-        self.powerd.fl_intensity = self.powerd:frontlightIntensityHW()
+        self.powerd.setIntensityHW(self.powerd:frontlightIntensityHW())
         logger.dbg("Dialog OK, brightness: " .. self.powerd.fl_intensity)
         if android.isWarmthDevice() then
             self.powerd.fl_warmth = self.powerd:frontlightWarmthHW()

```

**Comment by pazos** [comment]
@hasezoey: the light dialog worked fine when it was merged, in https://github.com/koreader/koreader/pull/6426.

Probably I, or something else, screwed stuff on a refactor.  It is a good point to recover the cancel behaviour. Please see how it was implemented back then.

**Comment by hasezoey** [comment]
> Probably I, or something else, screwed stuff on a refactor. It is a good point to recover the cancel behaviour. Please see how it was implemented back then.

it was also a loop, at least in the PR itself:
https://github.com/koreader/koreader/blob/a6763465b4e2384f6e03fc789e1d167a1494f970/frontend/device/android/device.lua#L385-L387

**Comment by hasezoey** [comment]
it was removed in 1ac0ad2f1a42e7bb1578fb1dfc46a1425c979087, which i assume since then it is broken, but unnoticed because the lights were still set, but the cancel button did not work (and other things that depended on a correct state)

**Comment by NiLuJe** [comment]
Right, I was under the impression that the previous behavior was only there to avoid ANRs, not that it ad actual UX purposes, my bad ;o).

**Comment by pazos** [comment]
@NiLuJe: based on the conversation in https://github.com/koreader/koreader/issues/7552 it looks like we need to restore the processEvent/voidEvent function to eat everything that happens when KOReader is in foreground but the focus is on the frontlight widget. Or make sure we drain the input queue just before opening the widget, since a timestamp of +5 seconds will trigger an ANR when we gain focus again.

Maybe I'm missing something.

**Comment by NiLuJe** [comment]
> Note: it also works without the change of `self.powerd.setIntensityHW(self.powerd:frontlightIntensityHW())`, but it is the more correct way, if i understand it correctly

That appears to do some extra... Android "stuff" that I'm not sure are desirable here?

**Comment by NiLuJe** [comment]
> Or make sure we drain the input queue just before opening the widget

We should be, that was the whole point of the changes mentioned. The loop refactor + a nextTick ensures that.

**Comment by pazos** [comment]
Cool, so the loop in https://github.com/koreader/koreader/pull/10726/files will do the job.

**Comment by hasezoey** [comment]
> Or make sure we drain the input queue just before opening the widget, since a timestamp of +5 seconds will trigger an ANR when we gain focus again.

just as note in case it was related to the lights dialog:
currently with #10726 applied in my testing and having the dialog open for ~1 minute did not trigger any ANR while open or when closed afterwards
also no input was allowed aside from the lights dialog (both sliders, and both buttons)

**Comment by pazos** [comment]
@hasezoey:

Feel free to close this ticket if

https://github.com/koreader/koreader/pull/10731
https://github.com/koreader/koreader/pull/10727
https://github.com/koreader/koreader/pull/10726

address all your issues here :)

**Comment by hasezoey** [comment]
those PR's basically all addressed the issues from the issue, there is only thing that may or may not be related (or should be outsourced to another issue):
if koreader is exited while `ToggleFrontlight` as set to to `Frontlight Disabled` (but before `fl_intensity` was not `0`), then re-opening koreader makes it seem like `fl_intensity` is always `0` and has to be re-set through the lights dialog

**Comment by hasezoey** [comment]
closing issue because main issues have been addressed
