### ISSUE TITLE
Device becomes unresponsive / random wifi connection dialog

### ISSUE THREAD

**Issue by maciejla** [koreader/koreader#10723]
* KOReader version: KOReader 2023.06.1
* Device: Kindle Paperwhite 3 (G090G1)

#### Issue
I have two Kindle Paperwite 3 devices (SN starting with G090G1). One was jailbroken using KindleBreak and has been running KOReader for a few months without any problems. The other has been jailbroken using WatchThis. After upgrading KOReader on both devices to version 2023.06.1 I have noticed two problems:
- device becomes unresponsive for 10-15s when returning from book to main menu (using the "drawer" icon from the top menu)
- device randomly displays the `Do you want to turn on Wi-Fi?` dialog (the same one which pops up when you try to do a OTA update with wifi switched off)
Both problems happen on both devices. I have tried to reinstall KOReader on both of them, but that didn't help

#### Steps to reproduce
- Install KOReader 2023.06.1 on a G090G1 PW3 device
- Open a epub / mobi file
- Try to quit the file

**Comment by pazos** [comment]
revert to 2023.06 or update to a nightly

**Comment by maciejla** [comment]
Installed a OTA update from the development channel, seems to be working now, thank you!
