### ISSUE TITLE
FR: Page flipping: progress bar / location stack / text selection

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10720]
**Progress bar**

I recently came across this old Issue (#9277) and learned that in Page flipping mode, the progress bar can be used to quickly jump to any location in the book by tapping a point on the bar. This is really helpful as unlike in Skim document mode, where page numbers may be cropped out in the current view of a PDF, Page flipping mode always shows the full page.

However, since introduction of the Book map (overview) feature, I no longer use the progress bar while reading, and it therefore also doesn't show in page flipping unless manually enabled beforehand.

Desired solution: Always show the progress bar while in page flipping mode (at least when the status bar is already enabled, or force-enable both bars when entering page flipping).

Alternatively, create a `Toggle progress bar` option for gestures/profiles, so a profile could be created that toggles both Page flipping and progress bar together.

**Location stack**

After exiting Page flipping mode, `Go back to previous location` doesn't always go back to the location one was before. @poire-z [mentioned](https://github.com/koreader/koreader/issues/9277#issuecomment-1172949395) that a location needed to be added to the stack; perhaps this is still pending?

**Text selection**

While flipping through the pages with left-right and up-down swipes, sometimes fast and sometimes slow, it can easily happen that one accidentally starts selecting text. As the purpose of page flipping is specifically to browse the book, is text selection really necessary to be available in this mode? I would suggest that if not completely disabled, then at last that the interval for selecting text is at least doubled or tripled the normal time while in flipping mode.
__
As always, thank you for all your awesome support.

**Comment by NiLuJe** [comment]
> Desired solution: Always show the progress bar while in page flipping mode (at least when the status bar is already enabled, or force-enable both bars when entering page flipping).

This very very vaguely rings a bell, FWIW. So it might have been discussed in the (way, way) past.

Or I'm imagining things ;p.

**Comment by poire-z** [comment]
> After exiting Page flipping mode, `Go back to previous location` doesn't always go back to the location one was before. @poire-z [mentioned](https://github.com/koreader/koreader/issues/9277#issuecomment-1172949395) that a location needed to be added to the stack; perhaps this is still pending?

Yep, still pending.
I had a quick look at the time - and I think I did not find an elegant (not too kludgy) solution to this, so didn't pursue. Didn't feel this was really used and needed a solution :/

**Comment by jonnyl2** [comment]
No problem, a quick swipe always reverts to the initial position as well, so one just has to remember to do that prior to exiting the page flipping mode (or else look at the Book map bars).

**Comment by poire-z** [comment]
> Alternatively, create a Toggle progress bar option for gestures/profiles, so a profile could be created that toggles both Page flipping and progress bar together.

Looks like we already have that (since before your post), `... > Reader > Toggle status bar`.

**Comment by jonnyl2** [comment]
>Looks like we already have that (since before your post), ... > Reader > Toggle status bar.

I meant for the progress bar separately, not the status bar. I already had the status bar enabled but without the progress bar.

But I've since enabled the progress bar again; the thin style and just 1px thick. That way it barely uses any space and mostly works as a separater bar between the page and the footer, but I can still use it to navigate in Page flipping mode.

**Comment by jonnyl2** [comment]
Closing as these issues will be solved via the improved Skim widget (#12046).
