### ISSUE TITLE
Pocketbook: Getting stuck when opening next file.

### ISSUE THREAD

**Issue by rezackacz** [koreader/koreader#10724]
* KOReader version: 2023.06.1
* Device: PB632 (Touch HD 3)

#### Issue
KOReader gets stuck on "Searching for the next file" then after a long while asks whether I want to turn on Wifi or not.
#### Steps to reproduce
Open any document, go to the end, press the next page and select "Open next file".

**Comment by hius07** [comment]
Update to the latest nightly build please.

**Comment by rezackacz** [comment]
> Update to the latest nightly build please.

Okay, that seems to help the issue, I just hope the nightly build isn't too unstable.
