### ISSUE TITLE
"Do you want to turn on wifi" after sleep

### ISSUE THREAD

**Issue by jamescridland** [koreader/koreader#10730]
* KOReader version: 2023.06.1
* Device: Boox Poke 3

#### Issue

When turning device on from sleep, it asks me if I want to turn on wifi (but wifi is on)

#### Steps to reproduce

* Read a book in Koreader
* Put device into sleep (hit the power button)
* Wait thirty seconds or so
* Turn on device
* "Do you want to turn on wifi?" appears

![PXL_20230723_070254452](https://github.com/koreader/koreader/assets/231941/518897c6-fc28-4012-a2f5-c7e75cd20bd6)

This device runs Android and wifi *is* turned on, using the system controls (but is probably not connected at the precise moment this device wakes from sleep).

This appears to be a regression - this device has never prompted this before now. (I've used KOReader for probably three years or more).

**Comment by pazos** [comment]
Duplicate of https://github.com/koreader/koreader/issues/10718, https://github.com/koreader/koreader/issues/10723, https://github.com/koreader/koreader/issues/10724

**Comment by jamescridland** [comment]
Unsure that it's a duplicate of #10718 but agree with the other two.

A workaround is to turn off the sync feature, which appears to trigger this.

**Comment by NiLuJe** [comment]
Or update to a nightly ;).

**Comment by ruffson** [comment]
> Or update to a nightly ;).
> 
> (Fixed by [#10669](https://github.com/koreader/koreader/pull/10669) & [#10697](https://github.com/koreader/koreader/pull/10697))

Is this really fixed? I still observe that problem on my Boox Go 7 and Supernote Nomad both running Koreader `2026.03`. Both have WiFi enabled and it seems that Koreader checks slightly too early still.

**Comment by goncaloMgomes** [comment]
I still see this on a Boox Go 7 Color. Is there any way of disabling this without turning off the sync feature?

**Comment by ssuds** [comment]
Also experiencing this on a Boox Go Color 7 still

**Comment by titandrive** [comment]
Seeing this as well
