### ISSUE TITLE
Doesn't respect screen rotation lock

### ISSUE THREAD

**Issue by Ryder17z** [koreader/koreader#10748]
* KOReader version: 2023.06.1
* Device: KingPad K10

#### Steps to reproduce
Lock screen orientation to landscape and start the app. 
Then observe disrespectful app behaviour. 

I can't test behaviour on a different android device because my current phone doesn't implement screen orientation lock properly, it's either stuck in portrait mode or running auto-rotate.
But the tablet is designed to be used in landscape mode and will lock in any orientation properly. (except for when apps disrespect the lock and force it into portrait mode) 

Logs: [koreader.zip](https://github.com/koreader/koreader/files/12167752/koreader.zip)

**Comment by pazos** [comment]
> Then observe disrespectful app behaviour.

This app isn't designed to respect android. It is designed to respect you :)

> when apps disrespect the lock and force it into portrait mode

This app [doesn't force portrait mode](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/AndroidManifest.xml#L44). It just start on the default orientation your device specifies.

If you want to setup a different orientation for this app you'll need to do it from this app. 
Go to Settings -> screen. 
Enable "keep orientation across views"
Select orientation you want.
Exit the app from the hamburguer menu
Start the app again
Profit

If the orientation you selected doesn't match the orientation your device starts with you'll probably see artifacts for a couple of seconds between the launch screen (device default orientation) and the main screen (your select orientation).

**Comment by pazos** [comment]
> Yes it does force portrait mode.

No, it doesn't. But feel free to believe what you want :)

> "keep orientation across views" has no effect on the issue.

You need to pair it with a non 0º orientation on KOReader settings.

**Comment by NiLuJe** [comment]
> You need to pair it with a non 0º orientation on KOReader settings.

Is there something specific about 0 on Android? (I'm asking because IIRC, that setting *should* work to make UR stick on Kobo).

**Comment by NiLuJe** [comment]
Now that I think about it, that's pretty much what it means for LinuxFB, too ;).

(After all, the constant is named upright, not Portrait ;). And it refers to the physical state of the display, so, that tracks).

**Comment by pazos** [comment]
> I still find it really disrespectful to override the rotation lock.

A reminder: 

1. This is NOT an android app. Is a program that works on a bunch of devices, including Android.
2. We're not developing an android app. We just maintain the glue code that makes possible to get the improvements of the program on android too.
3. We do not care about android users. We care about KOReader users, even if they use android :)

So take these points in consideration. You're free to use other applications developed for android that behaves as you would expect. No hard feelings :)
