### ISSUE TITLE
Android: app not responsive unless in airplane mode

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#10740]
KOReader version: 2023.06.01
Device: Android POCO XT G4

Sometimes the app becomes completely unresponsive. I can't figure out exactly under which circumstances it occurs, but when it does, the app becomes responsive again when I put the device in airplane mode.

adb logs below:

[koreader log anr.txt](https://github.com/koreader/koreader/files/12146062/koreader.log.anr.txt)

Some sort of race condition in "NetworkListener: onNetworkConnected" perhaps?

Might be the same issue as #10644

**Comment by mergen3107** [comment]
Most probably related to recent woes about KOReader trying to sync. Have you got any sync plugins enabled?

**Comment by pbienst** [comment]
I tried turning off the progress sync plugin, but that didn't help...

**Comment by NiLuJe** [comment]
Do check on the latest nightly please ;).

**Comment by pbienst** [comment]
Where do I find these? https://build.koreader.rocks/download/nightly/ seems to be timing out....

**Comment by NiLuJe** [comment]
Any if the ota mirrors should do in the meantime, e.g.,
http://koreader-fr.ak-team.com/

**Comment by pbienst** [comment]
Seems to have worked, thanks!
