### ISSUE TITLE
Progress sync plugin stopped working

### ISSUE THREAD

**Issue by whatever4kindle** [koreader/koreader#10747]
* KOReader version: last nightly on Android phone, and last stable version on a KPW3, older versions on KPW2, Kindle 4 NT and Kindle Keyboard
* Device: Android Phone, KPW3, KPW2, Kindle 4 NT, Kindle 3 Keyboard

#### Issue

Since yesterday, trying to push progress from other devices, makes the device very slow. After logging out from the Progress sync plugin, slowness problem is solved. But now I can't login or register on the Progress sync plugin, it says: "unknown server error". I have already tried on 5 different devices, and two networks, always same result. It was a feature that I used pretty often. I have tried the newest nightly on my android phone, and still "unknown server error".

Relevant crash.log:

07/25/23-18:11:59 INFO  Powerd resume state: active 
07/25/23-18:12:05 INFO  opening file /mnt/us/koreader/crash.log 
GET https://sync.koreader.rocks:443/users/auth
522
07/25/23-18:16:12 INFO  opening file /mnt/us/koreader/crash.log 
POST https://sync.koreader.rocks:443/users/create
522

**Comment by poire-z** [comment]
Looks like this/our *.koreader.rocks server is unavailable, see https://github.com/koreader/koreader/issues/10615#issuecomment-1646784861 .
You can check manually until https://build.koreader.rocks/download/nightly/ answers.
So, patience :/

**Comment by poire-z** [comment]
Does it work now? The server seems to be back.

**Comment by whatever4kindle** [comment]
> Does it work now? The server seems to be back.

Yes, thank you :)
