### ISSUE TITLE
FR: gesture action for jumping to a random page within a book

### ISSUE THREAD

**Issue by fingerpad** [koreader/koreader#10744]
**Does your feature request involve difficulty completing a task? Please describe.**
opening to a random page is a common method of approaching a book. diaries and journals, reference works, collections of poems and letters, and works like The Pillow Book, The Book of Disquiet, and Dictionary of the Khazars are often read this way. it's also popular for religious and spiritual texts.

**Describe the solution you'd like**
a gesture action for jumping to a random page within a book.

**Describe alternatives you've considered**
a button to jump to a random page could be added to the Skim popup, or the Go to page popup.

**Additional context**
there is a similar issue here: https://github.com/koreader/koreader/issues/6036. but it seems the gesture wasn't implemented.

**Comment by poire-z** [comment]
Launch Book map, close your eyes, tap anywhere :)
Not that different from _the common method of approaching a paperbook_ !
And what if your book is the first 60% of content you'd want to have random, and the last 40% footnotes - you'd be disappointed half of the time - so a visual random tap in some area you know will be interesting feels somehow less random.

I _personally_ don't get the need for these kind of features (we have open random book I think somewhere), they sound silly, childish, and somehow step down the seriousness of the app.

In any case, if this is to be implemented, I'd prefer we would not add a menu item for that, and neither a button in the Skim widget.

**Comment by hius07** [comment]
Seems it **is** serious.
https://en.m.wikipedia.org/wiki/Bibliomancy

**Comment by NiLuJe** [comment]
I was going to say I feel like I've seen a "jump to random... something" method somewhere, but that something might very well be "book" and not "page" ;).
