### ISSUE TITLE
FR: Refactor dictionary functionality

### ISSUE THREAD

**Issue by ckilb** [koreader/koreader#10759]
I'm wondering if there were already any plans or thoughts about replacing StarDict / sdcv with a different format.
I see a few downsides regarding StarDict:

- With a lot of installed dictionaries it's slow (sdcv needs a long time to find all the dictionaries in data/dic, while it should actually be very fast - it's basically just a look up of *.ifo files) -> We could workaround this in KOReader but it would always be a bit hacky.
- The current implementation into KOReader is already a bit hacky. See patches in _base/thirdparty/sdcv_ 
- The dictionary files are binary and therefore hard/impossible to read with a text editor. 
- It feels very dated. Just look at the website http://www.huzheng.org/stardict/ Also, the last release was 2 years ago. 
- The developer of _sdcv_ works - according to LinkedIn - for some sanctioned "Moscow Design Bureau" supporting the Russian aircraft.

Don't understand me wrong. The current implementation works good enough for the end user. I'm just wondering what's the opinion here in general. Are there already any plans or thoughts maybe? I was wondering if it would be a better approach to maybe move to some format that is directly supported by LUA (SQLite?), maybe together with a migration script (StarDict to xyz).

**Comment by NiLuJe** [comment]
> I'm just wondering what's the opinion here in general.

That there really aren't any portable alternatives? We'd be happy to be proven wrong.

**Comment by ckilb** [comment]
Well... CSV? :)

**Comment by NiLuJe** [comment]
Err, no. That's barely usable as an intermediary authoring format, but it's woefully inadequate as a performant user-facing one.

**Comment by ckilb** [comment]
I have a different opinion here.
- StarDict is a format only few know. You can't edit it without having the specific software installed. 
+ CSV as a plain text format can be read and modified by a lot of up-to-date software (LibreOffice, Excel, Numbers, the text editor you know and love)

The performance is totally dependent on the implementation. 
I'm optimistic enough that a good implementation in Lua would be equally or more performant than the current SDCV implementation. 
I find it anyway weird that in StarDict the format it uses has performance-related requirements - like an idx file. This all should be part of the implementation, not of the data format.

**Comment by NiLuJe** [comment]
We target woefully underpowered devices, so, no, it doesn't really strike ma as a strange requirement ;).

**Comment by NiLuJe** [comment]
Like I said, 

> We'd be happy to be proven wrong.

(i.e., #patcheswelcome)

**Comment by ckilb** [comment]
That’s why I said the implementation (of the reading and searching) process has to be fast of course. The source data format does not need to have anything in it that helps the implementation to do be fast. 
Let Lua build an index (tree) whenever it needs it.
Let Lua build some cache it can easily serialize/deserialize.
Usually dictionaries contain a few thousands of lines, not a few millions. 

I don’t say CSV  it is. I don’t say we should get rid of SDVC. But I still like you to seriously think about it.
The code base would like it. The dictionary lookup performance will be faster (and less power hungry). Only disadvantage is that a proper indexing has to take place some time.

**Comment by Frenzie** [comment]
> With a lot of installed dictionaries it's slow (sdcv needs a long time to find all the dictionaries in data/dic, while it should actually be very fast - it's basically just a look up of *.ifo files) -> We could workaround this in KOReader but it would always be a bit hacky.

???

> I find it anyway weird that in StarDict the format it uses has performance-related requirements - like an idx file. This all should be part of the implementation, not of the source data format.

In e.g. slob and zim the index is simply somewhere within the file, isn't it? That may be more convenient as a user but I don't see how that's technically any different.

It also doesn't seem like a strange requirement. Why would I want to waste minutes if not hours on some underpowered device to generate an index when it could've already been done while creating the reference work?

>  I'm just wondering what's the opinion here in general. Are there already any plans or thoughts maybe? I was wondering if it would be a better approach to maybe move to some format that is directly supported by LUA (SQLite?), maybe together with a migration script (StarDict to xyz).

See #2333. It seems a bit weird to complain that StarDict is niche and then to suggest SQLite, heh. ;-) Don't get me wrong, it wouldn't surprise me if SQLite could serve the task quite well, but it's not like there's much content available in it in some kind of standardized structure.

> Usually dictionaries contain a few thousands of lines, not a few millions.

Famous last words. Incidentally, my Petit Larousse here says it contains 84 2000 articles.

**Comment by poire-z** [comment]
> I find it anyway weird that in StarDict the format it uses has performance-related requirements - like an idx file. This all should be part of the implementation, not of the source data format.

Well, stardict is actually _mostly_ just packing the info from some CSV into some binary files to make lookups performant :)
That is, it is:
- a .ifo with some metadata info about the dict
- a dict.dz which is a plain text file, zipped (actually with a program called dictzip, which must do something specific to allow easier seeking into the compressed data) - if you dictunzip it, you get some plain text as shown in my screenshot in https://github.com/koreader/koreader/issues/10672#issuecomment-1655999219
- a .idx that maintain a list of headwords and associate them to some seek index in the dict.dz file - somehow encoded in some binary format for easier binary search I guess.
- some optional .syn with synonyms, which feels like another list of headwords.

So, it is packing + preprocessing, so sdcv and other apps are able to do it fast (and not have to redo the preprocess work like you suggest). Which it does - may be it is just when you have MANY such dicts that things get slower. 

More info about dicts and some python code to read/write/decode/encode at:
https://www.albertopettarin.it/penelope.html
https://github.com/pettarin/penelope

**Comment by pazos** [comment]
>  thoughts about replacing StarDict / sdcv with a different format.

No. Replacing is not an option :)

Adding something new as an alternative might be an option and a refactor that allows more than one backend is ok.

> The current implementation into KOReader is already a bit hacky. See patches in base/thirdparty/sdcv

Not hacky at all. Just mandatory changes to make it work on android (there're other changes on android-luajit-launcher as well) and to avoid being spammy.

>  a plain text format [that] can be read and modified by a lot of up-to-date software

A dictionary is a compressed blob with a header for a very good reason: it makes possible to query the header and get a pointer to a definition, so we're able to fseek there without runtime overhead. Anything plain text is going to be painfully slow.

> The performance is totally dependent on the implementation.

There're already two very good implementations available: slob and zim. Both are popular, fast and well thought. Sadly both rely on ICU, which is a huge 3rd party lib to bundle.
