### ISSUE TITLE
Autorstart in Profiles

### ISSUE THREAD

**Issue by ShinxA1** [koreader/koreader#10750]
* KOReader version: 2023.06.1
* Device: PW5

#### Issue
"Autostart" setting in Profiles does not work when opening a new file through the file browser. But it works when starting KOReader with "last file".

#### Steps to reproduce
1. Select "file browser" under "Start with" 
2. Create a profile in Profiles. 
3. Enable the "Autostart" option. 
4. Open a new epub file or one that has not yet been opened.

**Comment by mergen3107** [comment]
This is intended behavior. Profile can only be applied inside the document. 

If you want these settings to be applied to new documents, you need to make them “default” by long pressing them.
