### ISSUE TITLE
Custom daily timeline start time doesn't work as expected

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10752]
KOReader version: 2023.05.1-8
Device: Kobo Aura H2O

I set my daily timeline start time to 04:00, expecting that the reading time between 00:00 and 04:00 would be counted towards the previous calendar day. The following screenshots were taken at 00:27 after a 57 min reading session:

The daily calendar view displays fine:

<img width="538" alt="image" src="https://github.com/koreader/koreader/assets/95502269/ff7b97af-880c-44df-8313-933166b260a7">

However, on the monthly view the reading period after midnight already crosses into the next day:

![image](https://github.com/koreader/koreader/assets/95502269/977209d9-f36e-4fcb-b071-10d61acb815a)

Also, in the Book statistics, the time after midnight counts for the next day (the current calendar day):

![image](https://github.com/koreader/koreader/assets/95502269/8464f657-5324-4102-bd3b-95eab29144e4)

Same on the `Days reading this book` screen, where the time shortly after midnight counts toward the next day:

![image](https://github.com/koreader/koreader/assets/95502269/30575f95-4ed5-4d6b-be1d-826196f8bac7)

___

I took the following screenshots at the end of the day. The Current statistics (1h35) includes the time from last night's session, which should be counted toward the previous day (25.07.) I would expect the time in the Current statistics to match the Daily Calendar's reading time (1h08):

![image](https://github.com/koreader/koreader/assets/95502269/230c334b-c32e-4073-a3ff-73c74d5c18cf)

![image](https://github.com/koreader/koreader/assets/95502269/50d77ea0-e286-4d55-a888-7fa17db646b7)

Was this option only intended to change the timeline view, and not to shift the assigned dates of those reading blocks after midnight?

Thank you.

**Comment by poire-z** [comment]
> Was this option only intended to change the timeline view, and not to shift the assigned dates of those reading blocks after midnight?

I think so.
https://github.com/koreader/koreader/issues/10250#issuecomment-1484179128
#10254

I think we (mostly @weijiuqiao) went to just having it for timeline, and as an option for the monthly view for people who would be bothered by the lack of sync in these visual views.
We didn't go at having it impact all the other statistics (which might be complicated, no real idea, but I assume for many other statistics, we just truncate a timestamp to the day or month, which could possibly become messy if we have to account for that "day start at hh:00" in them too).

**Comment by jonnyl2** [comment]
Thank you. Unfortunately, this makes views like these not very meaningful, if reading sessions often extend beyond midnight:

<img src="https://github.com/koreader/koreader/assets/95502269/4029b7a7-3734-4af6-8288-26c8cb516013" width=60% height=60%>
<br/><br/>
What does the setting `Also use in calendar view` (below the timeline start time setting) do? I had it activated, but as you can see in the 2nd screenshot on the initial post, the book _did_ carry over into the next day after midnight.

**Comment by jonnyl2** [comment]
>Not sure what you mean with "carry over".

I see. I was referring to the book title.

Thanks

**Comment by poire-z** [comment]
Oh, yes, the book title spans.
I think I indeed have seen the book title span on the current day after midnight while all the black vertical bars where on the previous day, which may indeed look a bit odd.
(But then, also having the current day frame not-grey but empty for the few hours could look odd.)
