### ISSUE TITLE
.fb2.zip support

### ISSUE THREAD

**Issue by MERLev** [koreader/koreader#1075]
I don't know if this is an issue, but when I tried to open zipped fb2 file:
   "book.fb2.zip"
which contains only one file inside:
   "book.fb2"
i got a message
   "No reader engine for this file"

Same unzipped file is opened normally.

Is this an issue, or koreader just doesn't support .fb2.zip ? (zip format is listed on the wiki among supported formats)

DEVICE Kindle PW
VERSION koreader-kindle-arm-linux-gnueabi-v2014.04-929-g197c2f5

**Comment by timofonic** [comment]
Is this fixed or not?

**Comment by tigran123** [comment]
I think so, yes.

**Comment by MERLev** [comment]
Yes, issue was fixed
Thx devs for a great work
