### ISSUE TITLE
ExportHighlights: Author metadata concatenates multiple authors into one name ("John Mitchell William Black")

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#10755]
* KOReader version: 2023.6
* Device: PW5

#### Issue
When exporting, the names of multiple authors on a book are concatenated with just a space (or not... maybe a newline?); this should be an ampersand or a comma, because it ends up like that in targets (like Readwise).

So you get "John Mitchell William Black" instead of "John Mitchell, William Black" or "John Mitchell & William Black". The comma one is probably simpler to implement when you have 3+ authors.

It may actually be a newline, not a space, because I just saw the exported thing display as "Tobias SmollettJohn P. ZomchickGeorge S. RousseauO M Brack, JrW. H. Keithley" with them all stuck together, but also displayed with spaces in between somewhere else. Either way, still not ideal

#### Steps to reproduce
Export highlights for a book with multiple authors. Look at what gets exported for the author.

Pinging @Mochitto perhaps? Thanks for making this even possible in the first place back in April.

**Comment by hius07** [comment]
You mean export to html I guess.

The source authors are separated with "\n".
json export leaves them as is.
md export changes to commas.

**Comment by melyux** [comment]
I think both HTML and Readwise have the issue

**Comment by Mochitto** [comment]
Will look into it in the weekend ☺️💕

**Comment by melyux** [comment]
@Mochitto Any luck? I briefly tried myself but got lost in the weeds

**Comment by hius07** [comment]
For html you can add `booknotes.author:gsub("\n", ", ")` to line 61 of note.tpl.

**Comment by melyux** [comment]
That seems to have done the trick. For `readwise.lua`, the same change would be on line 104.
