### ISSUE TITLE
File manager: Filename truncated in selected files list

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#10760]
* KOReader version: koreader-pocketbook-v2023.06.1-41-g4fa278ff0_2023-07-26
* Device: PBlux2

#### Issue
Not visible full document name in selected files list.

#### Steps to reproduce

1. open file browser and browse deep into subfolder structure
2. tap on "+" at top right corner
3. tap on "Select files"
4. select some files
5. tap on "check" ikon at top right corner
6. tap on "Show selected files list"

List of selected files is shown, but filenames are truncated if the full path length exceed display width.

![selected_files](https://github.com/koreader/koreader/assets/29783895/a28eab05-4ded-4fb9-a875-56962201a7d1)
![selected_files_list_highlight](https://github.com/koreader/koreader/assets/29783895/c06c6e01-33a7-4dff-ae42-a17fb00d7639)

**Comment by hius07** [comment]
Please try: upper menu - File browser (1st tab) - Settings - Classic mode settings - Shrink item font size to fit more text.

**Comment by sonix-github** [comment]
Thanks @hius07 for the hint. Now it is shrinked, but it is small on device display. Is it possible to split the string to several lines without changing font size? For example each line will end with nearest "/" from right side according to display width. Something like line wrapping.

![selected_files_list_shrinked_font](https://github.com/koreader/koreader/assets/29783895/c4f0a7b1-8dfb-424e-be9c-922a5d49b44f)

**Comment by hius07** [comment]
Please try to adjust the font size with "Items per page" and "Items font size" in the same menu.

**Comment by poire-z** [comment]
@hius07 : there is an option to TextWidget, `truncate_left`, that may help in here (like it does for the subtitle of the top title with the full path) if you're showing a full path - in case it would be easy to plug it all down to Menu.lua.

**Comment by hius07** [comment]
Agree, if "Shrink" is unchecked, it's better to truncate the path, not the filename.
