### ISSUE TITLE
PocketBook 626: Koreader version: 2023.06 and 2023.06.1  crash at launch. 

### ISSUE THREAD

**Issue by Drmax** [koreader/koreader#10764]
* KOReader version:  2023.06 and 2023.06.1
* Device: PocketBook 626

#### Issue
Crash at lauch

#### Steps to reproduce
Install and laucnh

##### `crash.log`

[crash.log](https://github.com/koreader/koreader/files/12208120/crash.log)

```
</details>

**Comment by Drmax** [comment]
I'm going to test older release

**Comment by Drmax** [comment]
V2023.05.1 is running ok

**Comment by NiLuJe** [comment]
Well that's... interesting.

Does a current nightly work?

**Comment by NiLuJe** [comment]
Yeah, do try on a current nightly, they *definitely* export that symbol.
