### ISSUE TITLE
Koreader v2023.06.1 always hangs on exit on Android

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#10766]
* KOReader version: v2023.06.1
* Device: Samsung Galaxy Tab S4 with Android 10

#### Issue
Koreader hangs when selecting the menu option Exit.

#### Steps to reproduce
Start koreader, open any book in fb2 format (I tested with http://www.bibles.org.uk/3-Chas-Byka.fb2.zip) turn a few pages and then select menu option Exit. Observe that nothing happens for a long time and then the system dialog appears giving the option to "Close app" or "Wait". The previous working version was v2022.10 -- I did not try any other versions in between.

I found a workaround, namely if you turn on Mobile Data (or some other form of Internet connectivity, e.g. WiFi) then it does not hang, so it seems that upon exit koreader tries to do some network activity, without my permission to do so. This workaround is unacceptable -- please make sure that no network activity is ever performed by koreader without explicit permission of the user. Needless to say I would never read a book with internet switched on.

I will try to see if there is some data in the log and include it here.

**Comment by tigran123** [comment]
Oh, I have some good news! If I disable the option "Automatic Sync" in the plugin "Progress Sync" then the problem goes away. Well, it is still a bug, of course, because such a dangerous option should never be turned on by default.

**Comment by pazos** [comment]
It is already fixed on nightlies. Either roll back to 2023.06 or update to a nightly.

Also see: https://github.com/koreader/koreader/issues/10730, https://github.com/koreader/koreader/issues/10723, https://github.com/koreader/koreader/issues/10706

There're a few more that can't get after a quick look. All with the same underlying cause.

**Comment by tigran123** [comment]
Ah, ok, thank you. Then we can close this. But can you please tell me if the solution mentioned above (disabling automatic sync in "Progress Sync" plugin) is going to work or are there other places where network activity will be attempted, causing this hang?

**Comment by pazos** [comment]
Either disabling kosync plugin entirely, its requirement to check network connectivity when exiting a book or enabling some sort of internet access is enough for the problem to go away :)

But nightlies or the **true** :tm:  release v2023.06 don't have this issue, at all. Is just an unfortunate consequence of releasing v2023.06.1 because https://github.com/koreader/koreader/issues/10614 just after a proper release and when the merge window was wide open :p

**Comment by tigran123** [comment]
Thank you, now we can safely close this issue.
