### ISSUE TITLE
bad layout of tables

### ISSUE THREAD

**Issue by tartanpion** [koreader/koreader#10770]
* KOReader version: latest
* Device: libra2

#### Issue
bad layout of tables
#### Steps to reproduce
results with calibre's viewer and with koreader

![1690503096381](https://github.com/koreader/koreader/assets/3924779/98931f41-beea-4c47-ba7e-666720a91fd5)
![1690503096389](https://github.com/koreader/koreader/assets/3924779/f48a1301-80ef-4ed6-9a08-a6cd53c4db84)
![Capture d’écran du 2023-07-28 04-46-43](https://github.com/koreader/koreader/assets/3924779/e307bc80-6814-4030-aa72-6c4bbd12acc5)
[scrambled.epub.zip](https://github.com/koreader/koreader/files/12232742/scrambled.epub.zip)

**Comment by mergen3107** [comment]
Have you tried Top Menu’s style tweaks? I think there were some for tables as well.

**Comment by poire-z** [comment]
Had a hard time understanding this horror, but it's all explainable in the end :)

- the images are huge, so in the sizing, when there is nothing to limit their size, they are allowed to take the most width from a TABLE.
Calibre seems to go with 50 / 50, but my Firefox would not and would give it a lot, just ensuring (like KOReader) a min width for the left column so words are not broken (so the width of the longest word).
![image](https://github.com/koreader/koreader/assets/24273478/e6013230-0e43-4da1-b7d1-115191a05d64)

- Then in the EPUB, there is:
```html
<colgroup>
<col width="60%"/>
<col width="40%"/>
</colgroup>
```
that should probably ensure this ratio for the best - but crengine's table rendering algorithm does not (yet) parse and support that.
That's probably something I should try to implement.

- Then, not noticable on your screenshot, but it was when testing: the first column started below the image !
![image](https://github.com/koreader/koreader/assets/24273478/1950d9d0-3cf4-49c6-8130-3095b49ce680)
which make me think there was some unbalanced XHTML tags and it was in another row (the scrambler app using such hideous image with blank/fuzziness on the edges does not help grasping stuff).
But actually, the basline of the image and the baseline for the first line of text in the 1st column do align, which is the default when table cells have `vertical-align: baseline` (confirmed with Firefox).

- But they don't have `vertical-align: baseline`, but they have `valign="bottom"` - that we support in plain HTML files, but not in EPUBs (such HTML/table attributes were deprecated I guess) - so we went with the default of vertical-align: "baseline" - and no specific override in our epub.css.

- And only then I thought about **what should be our first reflex when having strange issues: switch from `Style> epub.css` to `html5.css`**, and you solve some bits of the above:

html5.css has more rules, and should render like web browsers:
```css
thead[valign=bottom i], tbody[valign=bottom i], tfoot[valign=bottom i],
tr[valign=bottom i], td[valign=bottom i], th[valign=bottom i] {
  vertical-align: bottom;
}
```
which will solve the vertical-align stuff.

Then, if the image is too wide, you could reduce its size with the bottom Zoom/Dpi.
Or you can use a style tweak with:
`img { max-width: 40vh !important; }`
(40% of your screen width), which will affect all your images - or the following to only affect images in tables:
`table img { max-width: 40vh !important; }`

and you can go on reading:
![image](https://github.com/koreader/koreader/assets/24273478/3014d0ea-80df-4c58-82c9-c01babae658f)

**Comment by poire-z** [comment]
I regularly have some thoughts about switching our default from epub.css to html5.css - mostly because it solves many issues.
It should be fine with most publishers' EPUBs, which should test their stuff on web browser engine based readers.
But it looks bad with our Wikipedia EPUBs (because their stylesheet assume epub.css and just adds what's needed). And it should look bad on unstyled old/simple EPUBs.

Some of you readers could try to switch their default Style> to html5.css, and see how it goes with their next readings - if it changes too many things and you end up using more style tweaks to correct them - or the contrary - or if it changes nothing :)

**Comment by tartanpion** [comment]
The first time I used koreader, it took me a while to realize that I had a bad alignment of the interparagraph signs because koreader was adding an indentation in epub.css.
Since then I use html.css by default.
For this epub there is still a difference between borderless rendering of calibre and epub.css versus html.css.
And the image is not centered in the cell.
(with table img { max-width: 40vh !important; })
![1690924091160](https://github.com/koreader/koreader/assets/3924779/8d7f7b51-e474-4e24-aef1-bf10af24fb53)

**Comment by poire-z** [comment]
> And the image is not centered in the cell.

Not sure it should be. In calibre, with some added borders (red around the image, blue for the right cell):
![image](https://github.com/koreader/koreader/assets/24273478/560eacf8-7768-4c49-899e-2e21c22bb228)
The paragraph in the cell is `text-align: justify`, not `center`, and Firefox and KOReader renders a single item (the image) left aligned, and not centered when "justify".

**Comment by tartanpion** [comment]
It looks like the cell padding 7 and the border 0 is not respected
<table border="0" cellpadding="7" cellspacing="0">
It gives the glued appearance of the text and the image.

Another thing I just saw that is not connected to the table. There is a page break after DSC_0029_NY.jpg which is present with epub.css/calibre and not with html.css. And it is wanted because :
<p class="txt_courant_ssalinea">Ofza rnokemkppl :
is unscrambled
<p class="txt_courant_ssalinea">Page précédente :
(Previous page :)

**Comment by poire-z** [comment]
> It looks like the cell padding 7 and the border 0 is not respected with html.css only.
<table border="0" cellpadding="7" cellspacing="0">

Yes, again some old HTML with attributes that are now deprecated - and that we don't handle.


> * Then in the EPUB, there is:
> ```
> <colgroup>
> <col width="60%"/>
> <col width="40%"/>
> </colgroup>
> ```
> 
> that should probably ensure this ratio for the best - but crengine's table rendering algorithm does not (yet) parse and support that. That's probably something I should try to implement.

Looks like there is support for COLGROUP & COL. But again, the `width=` attribute (deprecated) is translated for a `style=width:` only for HTML documents.
It's a bit annoying that we have 2 parsers:
- one for HTML documents, that I have made robust (but slower) to handle autoclosing and missing tags - which has some bits of code to translate some attributes (align= valign=...) to styles (which is still a bit ugly, but helps).
- one for EPUB document, that expects (as per epub specs) to have XHTML and perfectly balanced tags (so, faster) - and that does not go thru the bit of codes that translate attributes.

Also, we can think about using CSS to translate atteibute to styles (like in html5.css, `td[valign=bottom i] {  vertical-align: bottom; }` - which is an easy and clean solution - but it can't deal with `<col width=60%`> (unless we implement calculation like `col[width] { width: calc(attr(col[width]))` - dunno if that would be a proper syntax :)
So, we'd need some code to handle the attributes - and most of them are deprecated - but we may meet them in old documents...
COLGROUP and COL have lots of attributes https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col that we don't handle - supporting them all would add a lot of code.
Among my EPUBs, may be 10% of them have COLGROUP/COL - and half of these have them empty. Some use other attributes. There is even some styling that can be done and should be reported to table cells: i've seen no documentation that states how this works, styling without proper inheritance, ie the bgcolor in https://htmlreference.io/element/colgroup/.).
So.... dunno, I'd rather not think anymore about all that :)

I remember I may have read that EPUB specs deprecate the use of HTML attributes, and expect everything to be done with CSS. 
But latest EPUB specs mention that the HTML should follow the HTML5 living standard, which permits 1) non-balanced HTML (so, no more XHTML) (or may be it means XHTML5 living standard) and 2) many of the old attributes are documented and expected to be supported...

**Comment by tjaderxyz** [comment]
> Some of you readers could try to switch their default Style> to html5.css, and see how it goes with their next readings - if it changes too many things and you end up using more style tweaks to correct them - or the contrary - or if it changes nothing :)

I've been using html5.css as default for a while, never had any issues. Most noticeable difference for me is lack of justification and paragraph indentation by default, but I don't mind either.

**Comment by mergen3107** [comment]
@tjaderxyz 
To make a style tweak by default, long press it and select “Apply to all documents”

**Comment by poire-z** [comment]
A question for users of html5.css by default:
I don't know if you read Wikipedia Saved as EPUB by KOReader on KOReader, so if you don't, please save a substantial one (ie; the article about your country in your language) so you can tell your opinion :)

**A** Would you read it as-is with html5.css ?
**B** Would you switch to using epub.css ?
**C** If fine with html5.css, try switching to epub.css: any preference between the two?

With html5.css, we get:
- no paragraph indentation + spacing between paragraphs, that I don't like but it is what we get in our web browsers
- headings have a large font size and top/bottom margins
- list items are quite a lot more indented

With epub.css, we get what I am so used to, so I can just describe this as "normal, like a book" :)

As I am somehow the "publisher" of our Wikipedia EPUBs :), as I have control of the CSS we use in the EPUB KOReader generates, should I "force" somethow some (which?) of these points so they look like what we have when using epub.css, and more like a book than like a web page?
(Currently, that CSS assumes epub.css is used, and doesn't set/reset much styles.)

**Comment by Frenzie** [comment]
While I'm not strictly speaking who you're aiming your question at, I don't think it makes much sense to force any of those things. If you don't want it to look like standard HTML paragraphs why would you use html5.css in the first place?

**Comment by poire-z** [comment]
> why would you use html5.css in the first place?

Because it's the common "base" stylesheet some publishers start building on, so it's safer/saner to use it to get the publishers intended rendering.
If our books still look like books and not like web pages even when using html5.css, it's because publishers have "counteracted" what they don't like in html5.css, ie. _adding_ `p.commonParagraph { text-indent: 1.5em; text-align:justify; margin-top:0; margin-bottom:0 ]` but _not needing to add_ `p.intertitle { text-indent: 0; }` as it's the default.
(When using epub.css on such a book, you'll get these p.intertitle with our default `text-indent: 1.2em`, and if centered, they would look miscentered - a very frequent reason for me to switch to html5.css when I see them :))

So, the question is: should I do like these publishers :) to force ensure Wikipedia EPUBs have a "book look", or let it free so they get a "Web page look".
If "force ensure", users could still get the "web page look" with our "Web browser paragraph style" styletweak if they really want it.
if not forcing it, people using html5.css for safety/sanity (but still expecting publishers to provide a book look) will need to manually switch to epub.css each time they open a Wikipedia EPUB.

**Comment by Frenzie** [comment]
I'd prefer it with fwiw.

**Comment by poire-z** [comment]
_it_ = what ? :)

**Comment by Frenzie** [comment]
The text-indent: 1em.

**Comment by pazos** [comment]
>> why would you use html5.css in the first place?

> Because it's the common "base" stylesheet some publishers start building on, so it's safer/saner to use it to get the publishers intended rendering.

Yup. Most publishers build their stylesheets on top of  browser defaults, mostly [blink/chromium](https://raw.githubusercontent.com/chromium/chromium/main/third_party/blink/renderer/core/html/resources/html.css), Maybe [gecko/firefox](https://raw.githubusercontent.com/mozilla/gecko-dev/master/layout/style/res/html.css) gets some love too but I don't know any framework that let you build apps on top of that.

All the tools used as a "golden standard" for comparing how a document is properly rendered are built on top of chromium (sigil, calibre, thorium) or webkit (apple stuff, foliate).


> So, the question is: should I do like these publishers :) to force ensure Wikipedia EPUBs have a "book look", or let it free so they get a "Web page look".

If you want to switch to html5.css by default then yes. You're the publisher and we trust you :)

The real question is: is it a good change to switch to html5?

**I** don't need it. But I think users will gladly accept it as the document will be rendered pretty much like any other software, and the things that mismatch can be easily spotted by a pro (you) as limitations in crengine, instead of explaining each time to those users the issues they find are caused by their publishers's css applied on top of a magic, invisible default stylesheet that nobody knows. And ours is different by default :)

**Comment by poire-z** [comment]
> If you want to switch to html5.css by default then yes

Not yet ready to think about changing out default epub.css :)
I'm for now here just asking about Wikipedia EPUBs.

> The real question is: is it a good change to switch to html5?

Dunno, again not ready to think about that.
Users having experienced these small issues can themselves set html5.css as the default (only problem with that is for readers that reads FB2 sometimes, as they won't have "auto" and fb2.css used after that switch).
epub.css is good for unstyled or low-styled EPUBs (which may be less common that in the past), and ensures that anything looks at least like a book and not like a webpage, which may still be the prefered default for new users that want to appreciate KOReader (if testing some app with a few books, and seeing left aligned text and spacing between paragraphs, _I_ may throw it out immediately and not dig into testing it further).

**Comment by Commodore64user** [comment]
> I don't know if you read Wikipedia Saved as EPUB by KOReader on KOReader, so if you don't, please save a substantial one (ie; the article about your country in your language) so you can tell your opinion :)

I have epub.css as default but, in the spirit of helping out, I downloaded a wikipedia file and can now safely and confidently confirm that: at least on a 6" kindle voyage, the epub.css looks a lot better than the html5 counterpart.

with html5.css, tables look totally disorganised and messy, text appears busier, with links and more internet stuff clogging it. Images and their accompanying captions tend be weirdly placed (although this also happened a few times with epub.css, only less) 

I don't normally download wikipedia articles, but if I did, I would personally choose to render them with epub.css

**Comment by poire-z** [comment]
Thanks for the feedback!

> I downloaded a wikipedia file [...]
> and more internet stuff clogging it. Images and their accompanying captions tend be weirdly placed 

Just to be sure, we're talking about the `Lookup Wikipedia` > `Full article` > `Save as EPUB button` feature, right ? (and not just Save page as file in your PC web browser, and transfer that to your Kindle?
(There shouldn't be more "internet stuff clogging" with either of our CSS, and image/floats captions should render the same.)

**Comment by Commodore64user** [comment]
yes, `lollipop (man) > wikipedia lookup > save as ePub.` that's what I did.

I think I figured out why it looks more "internet-ish", well for a start the internet is html so there is that, but also, it looks just like rendering wikipedia on a browser, the spacing between paragraphs and the layout in general is much like it would look on an iPad, only the screen is not wide enough so squishes images and tables in terrible, unreadable ways. The text is a lot more 'compact' and with a ton of links and footnotes, makes it look busier. 

the epub.css instead makes it look more book-like, or at least ebook-like (or at least what I consider an ebook looks like). the paragraph gaps are gone, the opening of paragraphs is indented (as every ebook should), images and captions look [a little] less bad, compared to the html5 render, with the html I found some panoramic images are cropped, and that does not happen with the epub.css render.

**Comment by poire-z** [comment]
Ok, thanks.
So, your descriptions of what and why you prefer stuff (I agree with all that) are in line with the comments I added in the (updated) epub.css I pasted in https://github.com/koreader/koreader/issues/11494#issuecomment-1963045594 .
May be you have read it before ? Anyway, yes, paragraphs like books, and smaller font size in tables make Wikipedia epubs look better.

So, I guess I should hardcode some of these important bits of epub.css into the CSS I bury in each Wikipedia EPUBs, so they would look similar whether one use epub.css or html5.css as his default. People who really like the "web page" look can still use some of our styletweaks to get that look, like they'd have to with publishers' EPUBs.

**Comment by poire-z** [comment]
@tartanpion : with tomorrow's nightly, things should look better with this book (except for the image size, that you still have to limit the size yourself, I couldn't think about anything the code could do to handle that, as per specs, and as Firefox does, nothing says a big image shouldn't take as much room as it can).
