### ISSUE TITLE
Kobo frozen after waking up from standby and doing some reading.

### ISSUE THREAD

**Issue by WillScarlettOhara** [koreader/koreader#10772]
* KOReader version: 2023.06.1
* Device: Kobo Libra 2

#### Issue
Freeze of koreader and automatic reboot of my kobo after 1-2min. This happens when I want to change page after about 30min of reading (I've never counted) after waking from standby.
When the kobo restarts after a freeze and I relaunch koreader, I have to turn a few pages to get back to where I was at the time of the freeze and I can read for at least 3 hours without any freeze. I've never read for very long without a pause, but I don't think I'll have any more freezes after restarting the kobo. It only happens after waking up from standby.

#### Steps to reproduce

- Take the kobo out of standby

- Read for a while without problems

- Wanting to turn a page and finding that the kobo is frozen.

##### `crash.log` (if applicable)
verbose version
[crash.log](https://github.com/koreader/koreader/files/12234596/crash.log)
I forgot to note the exact time of last night's crash, but I think it was around 1:30 a.m.

**Comment by NiLuJe** [comment]
Extremely likely to be another sibling of #8414

(Do note that there's an explicit warning about this in the autostandby help message on those devices; and that reminds me that i've left it in in #10771. Oh, well).
