### ISSUE TITLE
Convert dictionary from .mobi format to stardict

### ISSUE THREAD

**Issue by unacceptablet** [koreader/koreader#10789]
There is not many decent Bangla to Bangla dictionary on the internet. The only decent one I found is in .mobi format, which works for Kindle but is not supported by Koreader.

How do I convert this dictionary from .mobi format to stardict.

[BN_bn_Dictionary_compiled_by_Nihal.mobi.txt](https://github.com/koreader/koreader/files/12270092/BN_bn_Dictionary_compiled_by_Nihal.mobi.txt)

**Comment by NiLuJe** [comment]
AFAIK, you can't, that dictionary format is woefully undocumented.

**Comment by poire-z** [comment]
(Pinging @uroybd (assuming Bangla is related to Bangladesh and Bengali), if you have any suggestion for stardict dicts in this language.)

**Comment by pazos** [comment]
https://github.com/ilius/pyglossary is the golden standard for dictionary conversion. Try to get a format with a :heavy_check_mark: mark on the `read` column and you will be able to convert it to stardict

**Comment by anezih** [comment]
You can try to to convert your dictionary with this: https://github.com/anezih/mobi2stardict

**Comment by unacceptablet** [comment]
> You can try to to convert your dictionary with this: https://github.com/anezih/mobi2stardict

Tried it but did not work:

```
ok@SomePCName:~/mobi2stardict$ ls -l
total 7556
-rw-r--r-- 1 ok ok    2357 Aug  7 19:52 README.md
-rw-r--r-- 1 ok ok 7712544 Dec 19  2020 dic.mobi
-rw-r--r-- 1 ok ok    6630 Aug  7 19:52 mobi2stardict.py
-rw-r--r-- 1 ok ok   11586 Aug  7 19:52 mobi2textual.cpp
ok@SomePCName:~/mobi2stardict$ python3 mobi2stardict.py --fix-links --dict-name dic.mobi --author blah --gls --textual
Could not open the file. Check the filename.
ok@SomePCName:~/mobi2stardict$
```


> https://github.com/ilius/pyglossary is the golden standard for dictionary conversion. Try to get a format with a ✔️ mark on the `read` column and you will be able to convert it to stardict

Does not accept .mobi as input.

**Comment by anezih** [comment]
> > You can try to to convert your dictionary with this: https://github.com/anezih/mobi2stardict
> 
> Tried it but did not work:
> 
> ```
> ok@SomePCName:~/mobi2stardict$ ls -l
> total 7556
> -rw-r--r-- 1 ok ok    2357 Aug  7 19:52 README.md
> -rw-r--r-- 1 ok ok 7712544 Dec 19  2020 dic.mobi
> -rw-r--r-- 1 ok ok    6630 Aug  7 19:52 mobi2stardict.py
> -rw-r--r-- 1 ok ok   11586 Aug  7 19:52 mobi2textual.cpp
> ok@SomePCName:~/mobi2stardict$ python3 mobi2stardict.py --fix-links --dict-name dic.mobi --author blah --gls --textual
> Could not open the file. Check the filename.
> ok@SomePCName:~/mobi2stardict$
> ```
> 
> > https://github.com/ilius/pyglossary is the golden standard for dictionary conversion. Try to get a format with a ✔️ mark on the `read` column and you will be able to convert it to stardict
> 
> Does not accept .mobi as input.

@unacceptablet 
Did you unpack the MOBI file via KindleUnpack (or its Calibre plugin)? If so, it names the output html as `book.html`. You need to pass the path of html in the `--html-file` parameter. 
I was able to convert your dictionary successfully. Here are the steps I took:
```
mobitool -s .\BN_bn_Dictionary_compiled_by_Nihal.mobi
python.exe mobi2stardict.py --fix-links --dict-name "Bangla to Bangla Dictionary Compiled by Nihal" --author "Nihal" --textual --chunked
```
After that you can give the textual xml to either stardict-editor or PyGlossary.
Here is the .ifo file of the StarDict dictionary:
<details><summary>.ifo</summary>

StarDict's dict ifo file 
version=3.0.0 
bookname=Bangla to Bangla Dictionary Compiled by Nihal 
wordcount=31949 
idxfilesize=1118777 
author=Nihal 
date=07/08/2023 
sametypesequence=h 

</details>

<details><summary>On GoldenDict</summary>

![image](https://github.com/koreader/koreader/assets/90565940/1885800a-0171-4182-80ec-3ee76d4b2067)

</details>

**Comment by unacceptablet** [comment]
I forgot how I did it before. Now I get this error:

```css
python3 mobi2stardict.py --html-file ./home/ok/mobi2stardict/book.html --fix-links --dict-name "Obhidhan" --author "ok" --textual --chunked 
Could not open the file. Check the filename.
```
My file:

[asdf.mobi.txt](https://github.com/koreader/koreader/files/12467074/asdf.mobi.txt)

**Comment by unacceptablet** [comment]
```css
ok@SomePCName:~/mobi2stardict$ python3 mobi2stardict.py --html-file "/home/ok/mobi2stardict/book.html" --fix-links --dict-name "Obhidhan" --author "ok" --textual --chunked
```
Ok. This command worked before without any problem. But it does not work for this file [asdf.mobi.txt](https://github.com/koreader/koreader/files/12467074/asdf.mobi.txt)

It throws this error:

```css
Traceback (most recent call last):
  File "/home/ok/mobi2stardict/mobi2stardict.py", line 155, in <module>
    convert(args.html_file, args.dict_name, args.author, args.fix_links, args.gls, args.textual, args.chunked)
  File "/home/ok/mobi2stardict/mobi2stardict.py", line 31, in convert
    last_part = parts[-1]
IndexError: list index out of range
```
Any solution? @anezih

**Comment by anezih** [comment]
> ```css
> ok@SomePCName:~/mobi2stardict$ python3 mobi2stardict.py --html-file "/home/ok/mobi2stardict/book.html" --fix-links --dict-name "Obhidhan" --author "ok" --textual --chunked
> ```
> 
> Ok. This command worked before without any problem. But it does not work for this file [asdf.mobi.txt](https://github.com/koreader/koreader/files/12467074/asdf.mobi.txt)
> 
> It throws this error:
> 
> ```css
> Traceback (most recent call last):
>   File "/home/ok/mobi2stardict/mobi2stardict.py", line 155, in <module>
>     convert(args.html_file, args.dict_name, args.author, args.fix_links, args.gls, args.textual, args.chunked)
>   File "/home/ok/mobi2stardict/mobi2stardict.py", line 31, in convert
>     last_part = parts[-1]
> IndexError: list index out of range
> ```
> 
> Any solution? @anezih

The file you provided is not a dictionary file. There is no idx tags for the script to parse.

**Comment by shuvashish76** [comment]
> The dictionary above is better than nothing but it is quite lacking and not rich at all. For a language spoken by more than 280 million people, Bangla does not have its dictionary in epub / mobi format.

@unacceptablet https://github.com/xxyzz/wiktionary_stardict/releases/download/20260329/bn-en.tar.zst
@xxyzz official list at KOR includes [outdated one](https://github.com/koreader/koreader/blob/b62b1ddd031f9fbcb3cb7aae9d5797d50677be26/frontend/ui/data/dictionaries.lua#L1343) maybe replace all `Vuizur/Wiktionary-Dictionaries` list with your updated version _if available_?

**Comment by xxyzz** [comment]
I don't mind if my files are added. But I don't know whether .tar.zst is supported.

**Comment by Frenzie** [comment]
I'd say chances are good but you'd have to try it.

**Comment by unacceptablet** [comment]
> > The dictionary above is better than nothing but it is quite lacking and not rich at all. For a language spoken by more than 280 million people, Bangla does not have its dictionary in epub / mobi format.
> 
> [@unacceptablet](https://github.com/unacceptablet) https://github.com/xxyzz/wiktionary_stardict/releases/download/20260329/bn-en.tar.zst [@xxyzz](https://github.com/xxyzz) official list at KOR includes [outdated one](https://github.com/koreader/koreader/blob/b62b1ddd031f9fbcb3cb7aae9d5797d50677be26/frontend/ui/data/dictionaries.lua#L1343) maybe replace all `Vuizur/Wiktionary-Dictionaries` list with your updated version _if available_?

Bangla to Bangla dictionary would be best. But thanks anyway.

**Comment by shuvashish76** [comment]
There are few Bangla dictionaries at https://github.com/indic-dict/stardict-bengali/tree/gh-pages
