### ISSUE TITLE
FR: Implement adjustable color saturation and temperature sliders

### ISSUE THREAD

**Issue by rjd22** [koreader/koreader#10782]
Devices with color e-ink screens seem to be released more often now. But the hassle with them is that you can't just send the original picture to them to get the right perceived color temperature. More often than not they need to be adjusted based on medium (comics need different adjustments than normal picture books).

At this moment there are no document controls to adjust color temperature or saturation. My idea was to implement a way to adjust these when dealing with a device that has these controls.

My question would be since this is quite a niche functionality, if this would be a welcome feature or not?

**Comment by Frenzie** [comment]
It sounds welcome to me? It makes a lot more sense to me than the frontlight color temperature stuff in any case; I've never been bothered by it provided it can go sufficiently low.

**Comment by rjd22** [comment]
What place would be the most correct place in your opinion to implement this? I myself was thinking about document settings next to the contrast controls. But maybe you have a better location for this?

**Comment by Frenzie** [comment]
That would indeed seem to be the most logical place to put it.

The main potential alternative would be somewhere in settings → screen. For example with color rendering as a submenu rather than a checkbox, but that would likely pose some conditional challenges since it'd still need to be a checkbox on most devices.

**Comment by poire-z** [comment]
>  I myself was thinking about document settings next to the contrast controls. But maybe you have a better location for this?

Can't think of a better location, moreover if there's more values than 2 and it can't just be a checkbox - and ought to be some kind of progress bar.
But I will be annoyed (or may be not as I don't have a color device and it then won't be shown :) to have the Contrast panel have 5 items, when we tried hard to make all of them be 4 items for CRE/EPUB documents (except the 1st one, Rotation, that has only 2 items).
With PDF, the number of items per panel is quite a bit more variable, and some (including the Contrast panel) do not yet have 4 items, so it should hurt less.

**Comment by NiLuJe** [comment]
Yup, next to contrast sounds good.

**Comment by grabi678** [comment]
@rjd22 Many thanks for your efforts to bring color to Pocketbook color devices so far. Your idea of having controls for color saturation and temperature sounds very interesting and useful. Is there any chance to realize it in the near future?

**Comment by SilverGreen93** [comment]
Hi. I just purchased a PocketBook Color 2, but the color saturation in the images is very low compared to the one in the built-in reader. From what I read here, there is no user setting yet for adjusting this, correct?

**Comment by NiLuJe** [comment]
There is *a* setting, but it isn't user facing:

https://github.com/koreader/koreader/blob/39d54956ec42e97e0c3e57ea3ff994b6ebe57e31/frontend/device/pocketbook/device.lua#L690

It's a Device member though, so it could be updated in a 2- userpatch (c.f., any of the userpatch examples in the wiki that do that, e.g., the keyboard one).

**Comment by SilverGreen93** [comment]
> There is _a_ setting, but it isn't user facing:
> 
> https://github.com/koreader/koreader/blob/39d54956ec42e97e0c3e57ea3ff994b6ebe57e31/frontend/device/pocketbook/device.lua#L690
> 
> It's a Device member though, so it could be updated in a 2- userpatch (c.f., any of the userpatch examples in the wiki that do that, e.g., the keyboard one).

I changed that value to 3.0, but it seems that there is no difference, at least in color PDF page rendering that I tried. The colors are still pretty desaturated. Do I need to apply or do something else?

**Comment by rjd22** [comment]
> > There is _a_ setting, but it isn't user facing:
> > https://github.com/koreader/koreader/blob/39d54956ec42e97e0c3e57ea3ff994b6ebe57e31/frontend/device/pocketbook/device.lua#L690
> > 
> > It's a Device member though, so it could be updated in a 2- userpatch (c.f., any of the userpatch examples in the wiki that do that, e.g., the keyboard one).
> 
> I changed that value to 3.0, but it seems that there is no difference, at least in color PDF page rendering that I tried. The colors are still pretty desaturated. Do I need to apply or do something else?

Make sure you enable dithering for the document you're viewing. It uses that flag to figure out if there are images in the document.

**Comment by SilverGreen93** [comment]
> > > There is _a_ setting, but it isn't user facing:
> > > https://github.com/koreader/koreader/blob/39d54956ec42e97e0c3e57ea3ff994b6ebe57e31/frontend/device/pocketbook/device.lua#L690
> > > 
> > > It's a Device member though, so it could be updated in a 2- userpatch (c.f., any of the userpatch examples in the wiki that do that, e.g., the keyboard one).
> > 
> > 
> > I changed that value to 3.0, but it seems that there is no difference, at least in color PDF page rendering that I tried. The colors are still pretty desaturated. Do I need to apply or do something else?
> 
> Make sure you enable dithering for the document you're viewing. It uses that flag to figure out if there are images in the document.

Yes! Thanks! That did the trick. The colors are much more vibrant now. Didn't even know about that option until now. We should definitely include a color saturation option directly in the menu. In my case it seems that on PB Color 2, a value somewhere around 3.0 looks similar to the default reader app.

**Comment by rjd22** [comment]
For now I'm going to close this as the new changes made for pocketbook should for now cover this without bloating KoReader. If the need really arises we can make a new ticket.
