### ISSUE TITLE
'Automatically keep documents in sync' locked after 'Action when Wi-Fi is off' changed

### ISSUE THREAD

**Issue by jaydenlo08** [koreader/koreader#10784]
* KOReader version: 2023.06.1
* Device: Kobo Libra 2

#### Issue
'Automatically keep documents in sync' is kept on after 'Action when Wi-Fi is off' is turned to prompt

#### Steps to reproduce
1. Change 'Settings > Network > Action when Wi-Fi is off' to 'turn on'
2. Toggle 'Progress sync > Automatically keep documents in sync' to on
3. Change 'Settings > Network > Action when Wi-Fi is off' to 'prompt'
4. Automatically keep documents in sync option is kept on, and attempting to turn off will yield the 'you have to switch the 'action when Wi-Fi is off' setting to be able to enable this feature'

This is a minor bug and should be relatively simple to fix, but I neither have experiences in building KOReader nor experiences with Lua.

**Comment by NiLuJe** [comment]
It'll be disabled the next time you switch view.

Interlocking the two UI knobs live was too much hassle for something that'll never be a practical issue ;).

**Comment by NiLuJe** [comment]
c.f.,

https://github.com/koreader/koreader/blob/ccd29d36c0cde78d956bbd01b7232a9d70c81ffd/plugins/kosync.koplugin/main.lua#L86-L90

**Comment by NiLuJe** [comment]
I also didn't want to complicate the warning in the KOSync side of things to account for the current state of the Network knob, because I felt that would be too brittle and annoying to deal with.

Especially given the fact that that network knob is something that you should basically set once and then never ever touch again.

**Comment by NiLuJe** [comment]
> I also didn't want to complicate the warning in the KOSync side of things to account for the current state of the Network knob, because I felt that would be too brittle and annoying to deal with.

I may revisit that ;o).
