### ISSUE TITLE
KOreader crashes when trying to assing It as (main) reader to a file in Meebook M7 

### ISSUE THREAD

**Issue by otagaudencio** [koreader/koreader#10786]
KOReader version: 2023.06.1
Device: Meebook M7
OS: Android 11

**Issue**

KOreader crashes when, by longpressing, I try to set it as the main app to open a file from the main "Read" tab in the home screen. 

**Steps to reproduce**

After lonpressing the file in the "read" main screen, I get the following window:

![Screenshot_20230805-215040](https://github.com/koreader/koreader/assets/101954482/2da30448-410c-4eed-a86b-85aad5624a77)

By pressing KOreader, either for it to open one time or with the check box to always open it, I get the following crash
 
![Screenshot_20230805-215149](https://github.com/koreader/koreader/assets/101954482/f6822d00-47c3-48b6-b619-159189f0329c)

So I went to the apps system to see if it was a matter of permission or assigment of files, but KOreader doesn't seem to have any request, and I am not capable to assign any file to it.

![Screenshot_20230805-235836](https://github.com/koreader/koreader/assets/101954482/13eb2838-353b-4106-90a7-df7d5d626493)

![Screenshot_20230806-000027](https://github.com/koreader/koreader/assets/101954482/27965b0d-db79-48cf-ba4f-3620fa811057)

 `crash.log`:

[crash.log](https://github.com/koreader/koreader/files/12268625/crash.log)

<details>
  <summary>crash.log</summary>
--------- beginning of crash
08-06 00:22:57.452 E/AndroidRuntime(16426): FATAL EXCEPTION: Thread-20
08-06 00:22:57.452 E/AndroidRuntime(16426): Process: org.koreader.launcher, PID: 16426
08-06 00:22:57.452 E/AndroidRuntime(16426): java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{27e859 16426:org.koreader.launcher/u0a126} (pid=16426, uid=10126) that is not exported from UID 1000
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.os.Parcel.createException(Parcel.java:2357)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.os.Parcel.readException(Parcel.java:2340)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.os.Parcel.readException(Parcel.java:2282)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6816)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2946)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at org.koreader.launcher.extensions.UriExtensionsKt.absolutePath(UriExtensions.kt:6)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at org.koreader.launcher.MainActivity.getFilePathFromIntent(MainActivity.kt:3)
08-06 00:22:57.452 E/AndroidRuntime(16426): Caused by: android.os.RemoteException: Remote stack trace:
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7139)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7579)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2397)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
08-06 00:22:57.452 E/AndroidRuntime(16426): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
08-06 00:22:57.452 E/AndroidRuntime(16426): 
--------- beginning of main
08-06 00:42:43.444 V/NativeGlue(17623): User FIFO already exists at `/[data/user/0/org.koreader.launcher/files/alooper.fifo](http://data/user/0/org.koreader.launcher/files/alooper.fifo)`
08-06 00:42:43.444 V/NativeThread(17623): waiting for activity
08-06 00:42:43.452 I/Lights  (17623): Using Generic driver
08-06 00:42:43.473 V/Surface (17623): Using Native Content implementation
08-06 00:42:43.474 V/MainActivity(17623): native orientation: portrait
08-06 00:42:43.474 V/EventReceiver(17623): Filtering 3 events: 
08-06 00:42:43.474 V/EventReceiver(17623): android.intent.action.ACTION_POWER_CONNECTED
08-06 00:42:43.474 V/EventReceiver(17623): android.intent.action.ACTION_POWER_DISCONNECTED
08-06 00:42:43.474 V/EventReceiver(17623): android.intent.action.DOWNLOAD_COMPLETE
08-06 00:42:43.497 V/NativeGlue(17623): Start: 0xef4e68c0
08-06 00:42:43.500 V/NativeGlue(17623): Resume: 0xef4e68c0
08-06 00:42:43.501 V/Timeout (17623): onResume: updating system timeout: 35791
08-06 00:42:43.501 V/Timeout (17623): onResume
08-06 00:42:43.503 D/HqAdditionManager(17623): HqAdditionManager constructor
08-06 00:42:43.509 V/NativeGlue(17623): InputQueueCreated: 0xef4e68c0 -- 0xf335db00
08-06 00:42:43.557 V/NativeGlue(17623): NativeWindowCreated: 0xef4e68c0 -- 0xf33abc08
08-06 00:42:43.557 V/NativeThread(17623): Activity window ready.
08-06 00:42:43.560 W/ion     (17623): ION_IOC_FREE failed with code -1: Inappropriate ioctl for device; might be caused by that current kernel is NEW.
08-06 00:42:43.580 V/Surface (17623): surface changed {
08-06 00:42:43.580 V/Surface (17623):   width:  1236
08-06 00:42:43.580 V/Surface (17623):   height: 1648
08-06 00:42:43.580 V/Surface (17623):  format: RGB_565
08-06 00:42:43.580 V/Surface (17623): }
08-06 00:42:43.581 V/NativeGlue(17623): NativeWindowResized: 0xef4e68c0 -- 0xf33abc08
08-06 00:42:43.602 V/NativeGlue(17623): ContentRectChanged: l=0,t=0,r=1236,b=1648
08-06 00:42:43.604 V/NativeGlue(17623): NativeWindowRedrawNeeded: 0xef4e68c0 -- 0xf33abc08
08-06 00:42:43.663 V/NativeGlue(17623): WindowFocusChanged: 0xef4e68c0 -- 1
08-06 00:42:43.663 V/NativeThread(17623): Activity gained focus.
08-06 00:42:43.664 D/Activity(17623): isFullScreenEnabled :true
08-06 00:42:43.664 D/HqAdditionManager(17623): setSysProp
08-06 00:42:43.667 V/NativeThread(17623): Launching LuaJIT assets
08-06 00:42:43.668 D/HqAdditionManager(17623): setHighTextContrast,open:false
08-06 00:42:43.670 D/HqAdditionManager(17623): setSysProp
08-06 00:42:43.696 I/Assets  (17623): Skip installation for revision v2023.06.1
08-06 00:42:43.702 D/HqAdditionManager(17623): setSysProp
08-06 00:42:43.704 I/dlopen  (17623): dl.dlopen - libs/libkoreader-lfs.so => /[data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so)
08-06 00:42:43.705 V/dlopen  (17623):     dl.dlopen - needed => [libluajit.so](http://libluajit.so/) (1 of 3) <= /[data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so)
08-06 00:42:43.705 V/dlopen  (17623):     dl.dlopen - [libluajit.so](http://libluajit.so/) => /[data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so](http://data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so)
08-06 00:42:43.713 V/dlopen  (17623):         dl.dlopen - needed => [libm.so](http://libm.so/) (1 of 3) <= /[data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so](http://data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so)
08-06 00:42:43.714 V/dlopen  (17623):         dl.dlopen - [libm.so](http://libm.so/) => /system/lib/libm.so
08-06 00:42:43.714 V/dlopen  (17623):         dl.dlopen - skipping /system/lib/libm.so (system lib)
08-06 00:42:43.714 V/dlopen  (17623):         dl.dlopen - needed => [libdl.so](http://libdl.so/) (2 of 3) <= /[data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so](http://data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so)
08-06 00:42:43.722 W/Thread-17(17623): type=1400 audit(0.0:3130): avc: granted { execute } for path="/[data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so)" dev="mmcblk2p23" ino=16957 scontext=u:r:untrusted_app:s0:c126,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c126,c256,c512,c768 tclass=file app=org.koreader.launcher
08-06 00:42:43.716 V/dlopen  (17623):         dl.dlopen - [libdl.so](http://libdl.so/) => /system/lib/libdl.so
08-06 00:42:43.720 V/dlopen  (17623):         dl.dlopen - skipping /system/lib/libdl.so (system lib)
08-06 00:42:43.720 V/dlopen  (17623):         dl.dlopen - needed => [libc.so](http://libc.so/) (3 of 3) <= /[data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so](http://data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so)
08-06 00:42:43.721 V/dlopen  (17623):         dl.dlopen - [libc.so](http://libc.so/) => /system/lib/libc.so
08-06 00:42:43.721 V/dlopen  (17623):         dl.dlopen - skipping /system/lib/libc.so (system lib)
08-06 00:42:43.721 V/dlopen  (17623):     sys_dlopen - loading library /[data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so](http://data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so) (in local namespace)
08-06 00:42:43.723 V/dlopen  (17623):     dl.dlopen - needed => [libc.so](http://libc.so/) (2 of 3) <= /[data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so)
08-06 00:42:43.723 V/dlopen  (17623):     dl.dlopen - [libc.so](http://libc.so/) => /system/lib/libc.so
08-06 00:42:43.723 V/dlopen  (17623):     dl.dlopen - skipping /system/lib/libc.so (system lib)
08-06 00:42:43.723 V/dlopen  (17623):     dl.dlopen - needed => [libdl.so](http://libdl.so/) (3 of 3) <= /[data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so)
08-06 00:42:43.724 V/dlopen  (17623):     dl.dlopen - [libdl.so](http://libdl.so/) => /system/lib/libdl.so
08-06 00:42:43.724 V/dlopen  (17623):     dl.dlopen - skipping /system/lib/libdl.so (system lib)
08-06 00:42:43.724 V/dlopen  (17623): sys_dlopen - loading library /[data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so) (in local namespace)
08-06 00:42:43.725 W/linker  (17623): Warning: "/[data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so](http://data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so)" unused DT entry: DT_RPATH (type 0xf arg 0x325) (ignoring)
08-06 00:42:43.736 W/dlopen  (17623): could not find library rt.so.1
08-06 00:42:43.737 D/HqAdditionManager(17623): setSysProp
08-06 00:42:43.739 D/HqAdditionManager(17623): setSysProp
08-06 00:42:43.740 W/System.err(17623): java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{4ac19f6 17623:org.koreader.launcher/u0a126} (pid=17623, uid=10126) that is not exported from UID 1000
08-06 00:42:43.740 W/System.err(17623): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
08-06 00:42:43.740 W/System.err(17623): 	at android.os.Parcel.createException(Parcel.java:2357)
08-06 00:42:43.740 W/System.err(17623): 	at android.os.Parcel.readException(Parcel.java:2340)
08-06 00:42:43.740 W/System.err(17623): 	at android.os.Parcel.readException(Parcel.java:2282)
08-06 00:42:43.740 W/System.err(17623): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
08-06 00:42:43.740 W/System.err(17623): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6816)
08-06 00:42:43.740 W/System.err(17623): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2946)
08-06 00:42:43.740 W/System.err(17623): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
08-06 00:42:43.740 W/System.err(17623): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
08-06 00:42:43.740 W/System.err(17623): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
08-06 00:42:43.740 W/System.err(17623): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
08-06 00:42:43.740 W/System.err(17623): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
08-06 00:42:43.740 W/System.err(17623): 	at org.koreader.launcher.extensions.UriExtensionsKt.absolutePath(UriExtensions.kt:6)
08-06 00:42:43.740 W/System.err(17623): 	at org.koreader.launcher.MainActivity.getFilePathFromIntent(MainActivity.kt:3)
08-06 00:42:43.741 W/System.err(17623): Caused by: android.os.RemoteException: Remote stack trace:
08-06 00:42:43.741 W/System.err(17623): 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7139)
08-06 00:42:43.741 W/System.err(17623): 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7579)
08-06 00:42:43.741 W/System.err(17623): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2397)
08-06 00:42:43.741 W/System.err(17623): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
08-06 00:42:43.741 W/System.err(17623): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
</details>

**Comment by Frenzie** [comment]
Pinging @pazos

**Comment by pazos** [comment]
Hi. This is one of the few cases where the Crash Activity contains a valid crash and a lenghty stackstrace. Please press "save report" and attach the full text here.

It looks like your system doesn't like the trick we're using to open files. So probably the issue you're seeing will go away with https://github.com/koreader/koreader/issues/10050#issuecomment-1405434292.

Looks related to https://github.com/koreader/koreader/issues/9787, https://github.com/koreader/koreader/issues/10050

**Comment by otagaudencio** [comment]
The asked report:
--------- beginning of main
08-06 12:09:33.160 E/reader.launche(13578): Not starting debugger since process cannot load the jdwp agent.
08-06 12:09:33.255 D/NetworkSecurityConfig(13578): No Network Security Config specified, using platform default
08-06 12:09:33.255 D/NetworkSecurityConfig(13578): No Network Security Config specified, using platform default
08-06 12:09:33.262 I/MultiDex(13578): VM with version 2.1.0 has multidex support
08-06 12:09:33.262 I/MultiDex(13578): Installing application
08-06 12:09:33.263 I/MultiDex(13578): VM has multidex support, MultiDex support library is disabled.
08-06 12:09:33.634 D/EinkManager(13578): EinkManager constructor
08-06 12:09:33.666 V/NativeGlue(13578): User FIFO already exists at `/data/user/0/org.koreader.launcher/files/alooper.fifo`
08-06 12:09:33.666 V/NativeThread(13578): waiting for activity
08-06 12:09:33.676 I/Lights  (13578): Using Generic driver
08-06 12:09:33.684 V/Surface (13578): Using Native Content implementation
08-06 12:09:33.685 V/MainActivity(13578): native orientation: portrait
08-06 12:09:33.685 V/EventReceiver(13578): Filtering 3 events: 
08-06 12:09:33.685 V/EventReceiver(13578): android.intent.action.ACTION_POWER_CONNECTED
08-06 12:09:33.685 V/EventReceiver(13578): android.intent.action.ACTION_POWER_DISCONNECTED
08-06 12:09:33.685 V/EventReceiver(13578): android.intent.action.DOWNLOAD_COMPLETE
08-06 12:09:33.693 V/NativeGlue(13578): Start: 0xea0e21c0
08-06 12:09:33.696 V/NativeGlue(13578): Resume: 0xea0e21c0
08-06 12:09:33.698 V/Timeout (13578): onResume: updating system timeout: 35791
08-06 12:09:33.699 V/Timeout (13578): onResume
08-06 12:09:33.707 D/HqAdditionManager(13578): HqAdditionManager constructor
08-06 12:09:33.718 V/NativeGlue(13578): InputQueueCreated: 0xea0e21c0 -- 0xcfab6a00
08-06 12:09:33.795 V/NativeGlue(13578): NativeWindowCreated: 0xea0e21c0 -- 0xee3a2c08
08-06 12:09:33.795 V/NativeThread(13578): Activity window ready.
08-06 12:09:33.822 W/ion     (13578): ION_IOC_FREE failed with code -1: Inappropriate ioctl for device; might be caused by that current kernel is NEW.
08-06 12:09:33.831 I/System.out(13578): change paint.conf 1689460589000
08-06 12:09:33.853 V/Surface (13578): surface changed {
08-06 12:09:33.853 V/Surface (13578):   width:  1236
08-06 12:09:33.853 V/Surface (13578):   height: 1648
08-06 12:09:33.853 V/Surface (13578):  format: RGB_565
08-06 12:09:33.853 V/Surface (13578): }
08-06 12:09:33.854 V/NativeGlue(13578): NativeWindowResized: 0xea0e21c0 -- 0xee3a2c08
08-06 12:09:33.874 V/NativeGlue(13578): ContentRectChanged: l=0,t=0,r=1236,b=1648
08-06 12:09:33.875 V/NativeGlue(13578): NativeWindowRedrawNeeded: 0xea0e21c0 -- 0xee3a2c08
08-06 12:09:33.931 V/NativeGlue(13578): WindowFocusChanged: 0xea0e21c0 -- 1
08-06 12:09:33.931 V/NativeThread(13578): Activity gained focus.
08-06 12:09:33.932 D/Activity(13578): isFullScreenEnabled :true
08-06 12:09:33.933 D/HqAdditionManager(13578): setSysProp
08-06 12:09:33.934 V/NativeThread(13578): Launching LuaJIT assets
08-06 12:09:33.980 D/HqAdditionManager(13578): setHighTextContrast,open:false
08-06 12:09:33.981 I/Assets  (13578): Skip installation for revision v2023.06.1
08-06 12:09:33.986 D/HqAdditionManager(13578): setSysProp
08-06 12:09:33.989 I/dlopen  (13578): dl.dlopen - libs/libkoreader-lfs.so => /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
08-06 12:09:33.990 V/dlopen  (13578):     dl.dlopen - needed => libluajit.so (1 of 3) <= /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
08-06 12:09:33.991 V/dlopen  (13578):     dl.dlopen - libluajit.so => /data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so
08-06 12:09:33.992 V/dlopen  (13578):         dl.dlopen - needed => libm.so (1 of 3) <= /data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so
08-06 12:09:33.992 V/dlopen  (13578):         dl.dlopen - libm.so => /system/lib/libm.so
08-06 12:09:33.992 V/dlopen  (13578):         dl.dlopen - skipping /system/lib/libm.so (system lib)
08-06 12:09:33.992 V/dlopen  (13578):         dl.dlopen - needed => libdl.so (2 of 3) <= /data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so
08-06 12:09:33.993 V/dlopen  (13578):         dl.dlopen - libdl.so => /system/lib/libdl.so
08-06 12:09:33.993 V/dlopen  (13578):         dl.dlopen - skipping /system/lib/libdl.so (system lib)
08-06 12:09:33.993 V/dlopen  (13578):         dl.dlopen - needed => libc.so (3 of 3) <= /data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so
08-06 12:09:33.993 V/dlopen  (13578):         dl.dlopen - libc.so => /system/lib/libc.so
08-06 12:09:33.993 V/dlopen  (13578):         dl.dlopen - skipping /system/lib/libc.so (system lib)
08-06 12:09:33.993 V/dlopen  (13578):     sys_dlopen - loading library /data/app/~~xwsAtYJ9zqJWcQfDtMK-5g==/org.koreader.launcher-2Yymt8XAsSPSuhMHJmObsw==/lib/arm/libluajit.so (in local namespace)
08-06 12:09:33.994 V/dlopen  (13578):     dl.dlopen - needed => libc.so (2 of 3) <= /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
08-06 12:09:33.995 W/Thread-15(13578): type=1400 audit(0.0:539): avc: granted { execute } for path="/data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so" dev="mmcblk2p23" ino=16957 scontext=u:r:untrusted_app:s0:c126,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c126,c256,c512,c768 tclass=file app=org.koreader.launcher
08-06 12:09:33.995 V/dlopen  (13578):     dl.dlopen - libc.so => /system/lib/libc.so
08-06 12:09:33.995 V/dlopen  (13578):     dl.dlopen - skipping /system/lib/libc.so (system lib)
08-06 12:09:33.995 V/dlopen  (13578):     dl.dlopen - needed => libdl.so (3 of 3) <= /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
08-06 12:09:33.995 V/dlopen  (13578):     dl.dlopen - libdl.so => /system/lib/libdl.so
08-06 12:09:33.995 V/dlopen  (13578):     dl.dlopen - skipping /system/lib/libdl.so (system lib)
08-06 12:09:33.995 V/dlopen  (13578): sys_dlopen - loading library /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so (in local namespace)
08-06 12:09:34.000 W/linker  (13578): Warning: "/data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so" unused DT entry: DT_RPATH (type 0xf arg 0x325) (ignoring)
08-06 12:09:34.013 D/HqAdditionManager(13578): setSysProp
08-06 12:09:34.018 W/dlopen  (13578): could not find library rt.so.1
08-06 12:09:34.036 D/HqAdditionManager(13578): setSysProp
--------- beginning of crash
08-06 12:09:34.036 E/AndroidRuntime(13578): FATAL EXCEPTION: Thread-16
08-06 12:09:34.036 E/AndroidRuntime(13578): Process: org.koreader.launcher, PID: 13578
08-06 12:09:34.036 E/AndroidRuntime(13578): java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{f9dcc21 13578:org.koreader.launcher/u0a126} (pid=13578, uid=10126) that is not exported from UID 1000
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.os.Parcel.createException(Parcel.java:2357)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.os.Parcel.readException(Parcel.java:2340)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.os.Parcel.readException(Parcel.java:2282)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6816)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2946)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at org.koreader.launcher.extensions.UriExtensionsKt.absolutePath(UriExtensions.kt:6)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at org.koreader.launcher.MainActivity.getFilePathFromIntent(MainActivity.kt:3)
08-06 12:09:34.036 E/AndroidRuntime(13578): Caused by: android.os.RemoteException: Remote stack trace:
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7139)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7579)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2397)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
08-06 12:09:34.036 E/AndroidRuntime(13578): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
08-06 12:09:34.036 E/AndroidRuntime(13578): 
08-06 12:09:34.037 W/System.err(13578): java.lang.SecurityException: Permission Denial: opening provider androidx.core.content.FileProvider from ProcessRecord{f9dcc21 13578:org.koreader.launcher/u0a126} (pid=13578, uid=10126) that is not exported from UID 1000
08-06 12:09:34.037 D/HqAdditionManager(13578): setSysProp
08-06 12:09:34.037 W/System.err(13578): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
08-06 12:09:34.037 W/System.err(13578): 	at android.os.Parcel.createException(Parcel.java:2357)
08-06 12:09:34.037 W/System.err(13578): 	at android.os.Parcel.readException(Parcel.java:2340)
08-06 12:09:34.037 W/System.err(13578): 	at android.os.Parcel.readException(Parcel.java:2282)
08-06 12:09:34.037 W/System.err(13578): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5728)
08-06 12:09:34.037 W/System.err(13578): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6816)
08-06 12:09:34.037 W/System.err(13578): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2946)
08-06 12:09:34.037 W/System.err(13578): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
08-06 12:09:34.037 W/System.err(13578): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1967)
08-06 12:09:34.037 W/System.err(13578): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1798)
08-06 12:09:34.037 W/System.err(13578): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
08-06 12:09:34.037 W/System.err(13578): 	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
08-06 12:09:34.037 W/System.err(13578): 	at org.koreader.launcher.extensions.UriExtensionsKt.absolutePath(UriExtensions.kt:6)
08-06 12:09:34.037 W/System.err(13578): 	at org.koreader.launcher.MainActivity.getFilePathFromIntent(MainActivity.kt:3)
08-06 12:09:34.038 W/System.err(13578): Caused by: android.os.RemoteException: Remote stack trace:
08-06 12:09:34.038 W/System.err(13578): 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7139)
08-06 12:09:34.038 W/System.err(13578): 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7579)
08-06 12:09:34.038 W/System.err(13578): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2397)
08-06 12:09:34.038 W/System.err(13578): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2867)
08-06 12:09:34.038 W/System.err(13578): 	at android.os.Binder.execTransactInternal(Binder.java:1154)

**Comment by otagaudencio** [comment]
I already tried to open the file with other third part apps (file managers). I used the native file explorer and Solid Explorer, and in both KOreader opens the files without any problem. The reported error only happens with the files shown in the "Read" main screen tab.

**Comment by pazos** [comment]
> I already tried to open the file with other third part apps (file managers). I used the native file explorer and Solid Explorer, and in both KOreader opens the files without any problem. The reported error only happens with the files shown in the "Read" main screen tab.

Thanks for the feedback.

I'm aware of a few "broken" apps that fail. I wish I could blame them but I cannot. We're the ones doing something that's not standard. We do it for a very good reason.

At some point we might end implementing the standard way. Until then some apps will fail and that's expected (Onedrive & Dropbox) and other apps will fail because they're badly coded. I guess you could try to report back to Meebook the stacktrace above. Sadly the kind of apps that fail without a very good reason are the kind of apps that are obscure, creepy and have no proper support.

I repeat, I wish I could blame them, but in the end we're the ones doing tricks, so the blame is on us.
The only workaround is to avoid the usage of broken apps and use the FM -> + -> Import to get documents from cloud document providers such as Dropbox or OneDrive.

**Comment by pazos** [comment]
Will be fixed when #9787 is closed

**Comment by kaeff** [comment]
Unfortunately, the bug still appears with 2024.07 on the M7. Crash log is attached. 
[---------.txt](https://github.com/user-attachments/files/17249858/---------.txt)


It would be amazing if something could be done. The app opening the file is the launcher app, "Mee OS". It shows a nice books list similar to on a Kindle. It shows recently opened files placed in the public file system. Opening those same files via the file explorer within Koreader works.
