### ISSUE TITLE
PDF contrast: incorrect set by a gesture

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#10795]
PDF contrast (called "font gamma" in notifications) can be set via the bottom menu and by a gesture.
Setting by a gesture works incorrectly but differently depending on a document reflow mode.

For example setting the contrast to 4 by a gesture (that is the fifth square of the progress bar).

**Reflow off**: rendered text contrast is set to correct 4, the progress bar shows incorrect 1/4, the popup info shows correct 4.
![1](https://github.com/koreader/koreader/assets/62179190/6558c252-c7cf-4557-b1a1-5d20b12dd3fa)

**Reflow on**: rendered text contrast is set to incorrect 1/4, the progress bar shows incorrect 1/4, the popup info shows correct 4.
![2](https://github.com/koreader/koreader/assets/62179190/01b3c241-081c-4802-b002-9b8a8f4d933d)

-------------------------
The reason is that the "contrast" setting of koptoptions is handled in a special tricky way: https://github.com/koreader/koreader/issues/1299#issuecomment-65183895.

That requires unusual:
https://github.com/koreader/koreader/blob/f3fc2ac353008216f3772a4402d7fcacef65865b/frontend/apps/reader/modules/readerkoptlistener.lua#L27
and in sdr:
```
["gamma"] = 4,
["kopt_contrast"] = 0.25,
```
The bug can be fixed with a (ugly) patch to Dispatcher (specially for `kopt_contrast` setting) or with a significant rewriting of passing the contrast value to mupdf (non-reflow) and k2pdfopt (reflow) modules.

(This causes the incorrect value of Contrast displayed in the QuickMenu of the New profile with current document settings).

(Another minor UI inconsistency: there is no "more options" item `⋮` in the bottom menu, the contrast can be chosen of the preset values within the progress bar only. "Taps and gestures" item shows the SpinWidget with a full range of values, but with a wrong precision, so the 0.8 value is displayed as `00`.)

**Comment by NiLuJe** [comment]
Can't we simply move the division to the single `onGammaUpdate` handler? (And remove it from the callers & koptoptions args)?
