### ISSUE TITLE
Home folder “Sort By: Last read date” option missing

### ISSUE THREAD

**Issue by colinkarr** [koreader/koreader#10791]
* KOReader version: 2023.06.01
* Device: Boox Leaf 2 (Android)

#### Issue
My inkpalm 5 (Android v. 2023.04) has the ability to sort by Last Read Date in the home folder. It appears that this function has disappeared with a recent update, although I have not determined which one. I am wondering whether this was intentional and if the functionality will return?

#### Steps to reproduce
1. Navigate to home folder with 2023.06.01 android
2. Open “Sort By:” submenu
3. Note that “Date Added” and “Last read date” options are not present
4. Repeat steps with 2023.04 and note that those options are present.

**Comment by hius07** [comment]
Fixed in https://github.com/koreader/koreader/pull/10682.
