### ISSUE TITLE
FR: Swipe down to close Top Menu

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#10804]
I have started using a new gesture to open the top menu and have noticed that it's not possible to close the menu by swiping down. (Although it works for going one level up if deeper in a menu.) 

This seems rather inconsistent as it works in virtually every other screen where swipe-down doesn't have any other assigned function (including the bottom menu). 

Could swipe down be implemented to close the top menu as well?

Thank you and I hope you are all having a nice summer.

**Comment by poire-z** [comment]
It was limited to the top menu for technical reasons: #9304 #9308.
Still feels easier that way, than going trying to handle conflicting events or refectoring stuff :/

**Comment by jonnyl2** [comment]
That makes sense, thanks for the info. I couldn't find it when I searched because I was looking for swipe "down" instead of "south".
