### ISSUE TITLE
Android [Pixel 5] controls issue, wrong screen size detection

### ISSUE THREAD

**Issue by ed-fruty** [koreader/koreader#10808]
* KOReader version:  v2023.06.1
* Device: Android 13, Pixel 5

#### Issue
It seems koreader detects screen size incorrect . It cut screen from the top (where front camera is) but the bottom buttons are not visible, like moved to the hidden area 
![Screenshot_20230813-123748](https://github.com/koreader/koreader/assets/3379337/52551469-2fb1-4030-870c-9f9e04e0150b)

#### Steps to reproduce
Just open an app, you can't use controls.

**Comment by NiLuJe** [comment]
Known issue, can't quite find the existing issues though (there are a few of them, though, e.g., #10591 for related discussions).

**Comment by hugleo** [comment]
I believe koreader is  drawing before obtaining the correct dimensions in the surface method. This issue occurs more frequently on some devices than on others. You can attempt to open a document, rotating the screen and/or opening and closing koreader multiple times. See if the controls are displayed correctly at least once so  we can confirm this behavior.

**Comment by ed-fruty** [comment]
Thanks a lot. I tried to open document, rotate device, close etc. few times and got the correct controls display.

**Comment by Bluemoondragon07** [comment]
> You can attempt to open a document, rotating the screen and/or opening and closing koreader multiple times. See if the controls are displayed correctly at least once so we can confirm this behavior.

Wow! This worked for my Meebook M7! Thank you sooooo much! I was seriously about to downgrade Koreader to a months-old release.

**Comment by hugleo** [comment]
Good to know ;)

That message was intend to just confirm the bug (random surfacechanged method called after configchanged method) also for Android 13 :)

Should be fixed in the future with https://github.com/koreader/android-luajit-launcher/pull/439
