### ISSUE TITLE
FR: [Addition to pocketbook user guide]

### ISSUE THREAD

**Issue by jjrrw174** [koreader/koreader#10800]
**Does your feature request involve difficulty completing a task? Please describe.**
No it doesn't. Just a few lines to add

**Describe the solution you'd like**
Over on Mobile Reader a few user and I managed to figure out how to change the @koreader app icon and name. I have created the steps to do this over on https://github.com/jjrrw174/PocketBook-Desktop-and-App-Customizations

**Describe alternatives you've considered**
Feel free to add the link or rip the instructions from the GitHub and paste in the guide. Doesn't matter to me :)

**Additional context**
N/A. Described by request and details

**Comment by Frenzie** [comment]
Do you mean you'd like to add a reference to it on <https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices>?

**Comment by jjrrw174** [comment]
> Do you mean you'd like to add a reference to it on <https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices>?

Either reference or take the instructions. I'm good either way. 

Just a suggestion that some users may find useful who aren't around on mobilereads or the ebook de fourms.

I understand if it can't be added either just trying to get the word out :)

**Comment by pazos** [comment]
Done. Feel free to review, @jjrrw174

**Comment by jjrrw174** [comment]
> Done. Feel free to review, @jjrrw174 

That's great thanks :)
