### ISSUE TITLE
Progress sync crashing/freezing koreader when leaving a fixed layout document when Wi-Fi is off and auto sync is on.

### ISSUE THREAD

**Issue by nonameVHSM** [koreader/koreader#10806]
* KOReader version: 2023.06.1-67
* Device: PW3

#### Issue
Similar problem to issue #10704 maybe?
If you turn off Wi-Fi on a fixed layout document while you have "Automatically keep documents in sync" turned on and try to leave the document Koreader will crash. This doesn't happen in epub files.
#### Steps to reproduce
1. Open a fixed layout document
2. Have "Automatically keep documents in sync" turned on (Requires "Action when Wi-Fi is off: turn on" under Network)
3. Turn off Wi-Fi connection under Network
4. Go back to file browser
5. "Connecting to Wi-Fi..." prompt shows up for a while
6. Koreader goes back to file browser and crashes after a second or two.

In one instance it instead froze with the "Error connecting to network" message on top and I had to force reboot the device.

[crash.log](https://github.com/koreader/koreader/files/12328590/crash.log)

**Comment by NiLuJe** [comment]
Verbose debug logs, please ;).

**Comment by NiLuJe** [comment]
(Because the traceback is from an *constructor*, not a *destructor*, so I'm missing context).

```
./luajit: frontend/apps/reader/modules/readerzooming.lua:525: attempt to index field 'document' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerzooming.lua:525: in function 'getZoom'
	frontend/apps/reader/modules/readerhinting.lua:19: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/apps/reader/modules/readerview.lua:106: in function 'action'
	frontend/ui/uimanager.lua:991: in function '_checkTasks'
	frontend/ui/uimanager.lua:1437: in function 'handleInput'
	frontend/ui/uimanager.lua:1557: in function 'run'
	./reader.lua:321: in main chunk
	[C]: at 0x00013ead
```

**Comment by NiLuJe** [comment]
Okay, that one is maybe slightly more relevant, but still not enough context ;).

```
./luajit: frontend/ui/network/manager.lua:326: attempt to call local 'callback' (a nil value)
stack traceback:
	frontend/ui/network/manager.lua:326: in function 'beforeWifiAction'
	frontend/ui/network/manager.lua:495: in function 'willRerunWhenOnline'
	plugins/kosync.koplugin/main.lua:716: in function 'getProgress'
	plugins/kosync.koplugin/main.lua:716: in function 'callback'
	frontend/ui/network/manager.lua:68: in function 'action'
	frontend/ui/uimanager.lua:991: in function '_checkTasks'
	frontend/ui/uimanager.lua:1437: in function 'handleInput'
	frontend/ui/uimanager.lua:1557: in function 'run'
	./reader.lua:321: in main chunk
	[C]: at 0x00013ead
```

**Comment by nonameVHSM** [comment]
> Verbose debug logs, please ;).

Sure, on it.

**Comment by nonameVHSM** [comment]
Here is the verbose crash log
[crash.log](https://github.com/koreader/koreader/files/12328774/crash.log)

**Comment by NiLuJe** [comment]
The second one was an actual bug, but isn't the bulk of your crashes, FWIW ;).

**Comment by nonameVHSM** [comment]
> The second one was an actual bug, but isn't the bulk of your crashes, FWIW ;).

I'm not sure what that means, am I doing something else or something wrong that is causing crashes?

**Comment by NiLuJe** [comment]
Nope, you're not doing anything wrong ;).

Caught the other one: ReaderView was unscheduling the pre-rendering task too early, and the plugin was triggering a repaint *after* that (because of the popups), which scheduled another hinting task that would never be dropped, resulting in it attempting to run way after the document and ReaderUI instances were torn down => kablooey.
