### ISSUE TITLE
FR: Sync highlights and notes to Omnivore

### ISSUE THREAD

**Issue by peterrus** [koreader/koreader#10818]
**Does your feature request involve difficulty completing a task? Please describe.**
When reading a book I like to make highlights and take notes. I can currently export those to Readwise but not to a similar open source service called [Omnivore](https://docs.omnivore.app/).

**Describe the solution you'd like**
An integration in the [exporter plugin](https://github.com/koreader/koreader/wiki/Highlight-export) with Omnivore that generally offers the same kind of export we can now do to Readwise.

**Describe alternatives you've considered**
I see no feasible alternatives.

**Additional context**
-

**Comment by peterrus** [comment]
I realize know this might not be as trivial as I think it is, as Omnivore doesn't have a 'web clipping' data type like Readwise does. You would have to convert the full list of annotations and highlights into an 'article' and then somehow expose that somewhere so Omnivore can download and import it, which sounds very hacky and a bit out of scope for Omnivore.

**Comment by zenminimalist** [comment]
Can we keep an eye on this as Omnivore is still adding features and I'm sure they'll make this easier in the future? Also, I would you this feature as well.
