### ISSUE TITLE
FR: [Option to show .sdr sidecar folders for cloud exporting]

### ISSUE THREAD

**Issue by AaronKnowls** [koreader/koreader#10815]
**Does your feature request involve difficulty completing a task? Please describe.**
I have to rely on plugging the Kobo to the PC or an SSH server instead of the quicker and more convenient cloud exporting for read and highlighted books.

**Describe the solution you'd like**
Since .sdr folder is not updated when uploading to cloud, I found that having the option to show .sdr folders in Koreader browser would allow to upload them to the cloud with the book and not lose them for good.

**Describe alternatives you've considered**
Plugging to a computer and using SSH, but in both cases I'd need a device at hand that I don't have when I'm reading.

---
I've spent a lot of time trying to find an answer before posting, here in GitHub and also online, but couldn't find anything.

**Comment by hius07** [comment]
You can do it by yourself as a patch.
Download the attached file, rename its extension to `lua`, put it into `koreader/patches` folder.
[2-show-sdr-folders.txt](https://github.com/koreader/koreader/files/12332685/2-show-sdr-folders.txt)
