### ISSUE TITLE
No proper return to the Home screen

### ISSUE THREAD

**Issue by otagaudencio** [koreader/koreader#10810]
* KOReader version: 2023.06.1
* Device: Meebook M7 
* OS: Android 11

Issue

I have my home screen set to be "shorten" and "locked", so it can look more clean and to make the app to stay resticted to the folder I place my books. But every time I leave a book and return to the home screen (by returning to the fille browser), I get it "unlocked" and  "unshortened". I always have to press the Home botton in the top left for it to reload properly (locked and shotened) the folder I'm already in. 

I already looked in every configuration of the device to see what was causing it or if I was missing something, but everything seems correct. It seems that returning to the file browser doesn't mean returning to the home screen in the way it is set (even though there's no way to return to the home screen without being through the broswer).  In the gestures configurations, there's no option to go to the home screen specificly, only "File browser". I can remember clearly in older verions of Koreader, it being possible to return to the home screen in the right way. As it is not a crash issue, i don't have a crash log.

 Steps to reproduce

How it is configured: 
![Screenshot_20230813-171215](https://github.com/koreader/koreader/assets/101954482/cad1e981-5f75-43ce-bb0d-c0fb086a0157)

The way the home screen is:
![Screenshot_20230812-211007](https://github.com/koreader/koreader/assets/101954482/de54e459-1346-4fce-a0bf-d5a4f1de2b23)

How it gets when I leave the book 
![Screenshot_20230812-210949](https://github.com/koreader/koreader/assets/101954482/fc38fe20-be69-47ae-a417-a926253287ab)

**Comment by hius07** [comment]
Yes, it should be shorten and locked when leaving a book in any way.

Cannot reproduce on Kindle and Android phone.
When it is unshoretn, can you show:
-the dialog Settings - Home folder settings - Set home folder
-the folder menu (long press on the Home icon)

**Comment by otagaudencio** [comment]
Well, I did this small video to show the whole process. 
It seems that the issue happens when the book creates metadata (I think). Because when I open a "virgin" book (never opened before) and then return to the home screen, everythinhg seems ok. But if I open a book already opened (I assume, with metadadata created), it starts to happens and keeps happening even with other "virgin" books being opened.  As you can see in the video: 
- I set the home screen folder
- I open the never opened book
- I return home, and it is ok (locked and shortened)
- I open a already opened book
- I return to the home screen and it is unlocked and unshortened 
- I open the first book and go the home screen is unlocked and unshortened 
- I open a new never opened book and the issue persists
- I then press the home botton and note that it takes time to identify my touch and a black dot above it seems to indicate that the app is processing something. 

https://github.com/koreader/koreader/assets/101954482/04396d82-24e2-4713-a345-74d0d68a1771

**Comment by hius07** [comment]
Thank you, still cannot reproduce, maybe some Android specific issue on your device.
Can you please, at the moment when you see the unshortened/unlocked home dir, exit the program, look into the file koreader/settings.reader.lua and show me the values of the keys `home_dir` and `lastfile`.

**Comment by otagaudencio** [comment]
![Screenshot_20230814-040256.png](https://github.com/koreader/koreader/assets/101954482/d95feaf3-d99b-47ab-bde5-df65abf4804c)

![Screenshot_20230814-040149.png](https://github.com/koreader/koreader/assets/101954482/fc510bfd-2a23-4091-974d-2cfcc708c0d7)

**Comment by hius07** [comment]
Thank you, you can see the difference "Books" and "books" that is the reason of the issue.

**Comment by hius07** [comment]
Does the issue occur after leaving **any** book in your library? Or just after some of them?

**Comment by otagaudencio** [comment]
> Does the issue occur after leaving **any** book in your library? Or just after some of them?

It is explained in my second post.

**Comment by otagaudencio** [comment]
> Does the issue occur after leaving **any** book in your library? Or just after some of them?

I see. So it'd be fixed if I change the folder to lower case? Let's try...

**Comment by hius07** [comment]
> It is explained in my second post.

I do not mean opened / not yet opened books, but just `every` book?
The folder name is "Books" and I try to understand why we get a lowercased book filepath.

**Comment by otagaudencio** [comment]
> > It is explained in my second post.
> 
> I do not mean opened / not yet opened books, but just **every** book?
> The folder name is "Books" and I try to understand why we get a lowercased book filepath.

As it is explained in my second post, yes, after a while it happens with every book. 

So, I changed the folder to all lower case "books" and the issue disappeared. It seems it was caused by the fact that all the folders of the E-reader system starts with higher case, and the app was taking  to a lower case folder. Thanks for the help.

**Comment by NiLuJe** [comment]
Is this on an actually case sensitive filesystem?

**Comment by hius07** [comment]
I think yes because setting the Home folder saves "Books" in the path (from the PathChooser).
