### ISSUE TITLE
Formatting should not affect highlight page.

### ISSUE THREAD

**Issue by mengzhu28** [koreader/koreader#10817]
* KOReader version: v2023.05.1
* Device: Boox Poke 4 Light

#### Issue
(I am using epub).
When exporting my highlights to Readwise, I notice some highlights are placed in the wrong order. I exported the highlights again and find out something like:

```
        {
            "text": "Lorem ipsum dolor sit amet",
            "time": 1692047307,
            "chapter": "chapter 1",
            "sort": "highlight",
            "drawer": "lighten",
            "page": 277
        },
        {
            "text": "consectetur adipiscing elit",
            "time": 1683770579,
            "chapter": "chapter 1",
            "sort": "highlight",
            "drawer": "lighten",
            "page": 252
        },
```

As you can see, the second highlight's page is before the first one.  One thing to note is that the second highlight was made several month ago (as the timestamp suggests) and I probably changed the format of the book (e.g. font, orientation)

#### Reproduce
I was able to reproduce this by make some changes to the format (use much smaller font) and change the orientation. Then (under the new format), make an extra highlight beside the original one). And then I export the highlight in json again.

my expectation is:
the new highlight and the old highlight just above it, should have roughly the same page location.

in reality:
these two highlights is apart by about 10 pages.

conclusion: it seems when I change format, it affects the page property of the highlight.

#### Why it matters
For me, the issue manifests when I use Readwise export which probably includes the page as metadata. And thus on Readwise side, some highlights are rendered out of order which is confusing. There could be other cases where it could be confusing as well.

I am not familiar with epub or ebook formats in general, I wonder if there is any formatting neutral location data. If not, I feel we should consider removing the page property (since it seems to be a function of formatting which isn't very meaningful with that context). And highlight export plugin like Readwise shouldn't make use of the page property.

**Comment by hius07** [comment]
Your analysis is correct.
Unfortunately we cannot fix page numbers in highlights.
The only way is to enforce the Readwise server to ignore page numbers and sort the exported highlights by the original order.
I do not use Readwise, what way is preferrable:
-to have a manual setting (checkbox) "Ignore page numbers" in the Readwise exporter settings, or
-to automatically check the page numbers before exporting and set this flag if the order is wrong?

**Comment by mengzhu28** [comment]
Thanks for looking into this. 

AFAIK, the exact location isn't used by readwise for exports from koreader. I suggest let's (have an option to) replace page number with the highlight index on our side (i.e. the index of the highlight in the json array). This way if I makes a new highlight in the middle, all the subsequent highlight's index will change as well during export.
