### ISSUE TITLE
FR: Disable Touch Action

### ISSUE THREAD

**Issue by ryanwwest** [koreader/koreader#10812]
Boox Ereaders come installed with the proprietary NeoReader app for reading documents, and this app has a handy action that disables the touch screen for interacting with the app except within a small, hovering app action toolbar - see 'Hand Touch' in the image below. This is useful because in that app, you can still use volume/page turn physical buttons or the next/previous page buttons _within that toolbar_, but any other touch to the application is disabled. Why? This prevents accidental swipes/presses on the edge of the screen when holding or moving the device around, especially on devices with increasingly thin bezels, and is very handy (especially on larger devices where you may be looking at the same page for a long time.

![image](https://github.com/koreader/koreader/assets/31378238/739b6752-9fb6-45b1-bf89-15105aa600b9)

It would be nice to have a similar action in KOReader to temporarily disable the touch screen, with the exception of some indicator/icon on the screen that, by pressing, re-enables the touch screen. 

Challenges: I'm not aware of any equivalent hover-UI for KOReader that could house a button to re-enable the rest of the touch screen UI, which makes implementation less trivial. Implementing all of the NeoReader actions on their hovering toolbar is overkill, though if this design choice were copied here, it might be nice to also have next/previous page turn buttons on it that remain usable while the (rest of the) touchscreen is disabled. There may be other simpler options to disable and enable the touch screen as well (but they should somehow allow quick, one-tap enable/disable).

**Comment by poire-z** [comment]
I don't think we'd really want some ui element hovering over the book content, attracting your eyes by its anomality :)
But we have enable/disable/toggle touch input among the actions you can associate to a gesture - so you could associate a tap/swipe on a corner/edge to that.
Recently discussed/documented aroung https://github.com/koreader/koreader/issues/8058#issuecomment-1665154694.

**Comment by offset-torque** [comment]
As **poire-z** said, we already have "disable input" and you can actually achieve a very similar workflow to the NeoReader in KOReader:
1. Set a gesture for **"Toggle touch input"** (for example "tap upper left corner")
2. Create a QuickMenu from your favorite items and assign it to another gesture ("tap upper right corner")
3. Make QuickMenu gesture always active

Now you can disable the touch input with a single tap and access your menu (equivalent of that toolbar) with a second tap while the touch input is disabled. This feature is already implemented and will be added to the user guide soon.

**Comment by ryanwwest** [comment]
Yes thank you, this is exactly what I wanted. If we don't need more UI, better to not have it. Thanks so much! Closing this.

**Comment by hius07** [comment]
> 3\. Make QuickMenu gesture always active

The QM itself will not be active.

**Comment by offset-torque** [comment]
@hius07 
Actually worse than that it seems. I just tried, QM shows up and blocks any further gesture so touch input can not be toggled back. This essentially locks up KOReader. 

Since **ryanwwest**'s use case is a logical use of QM, can we make a change something like this:
- QM activation temporarily enables touch input as long as QM is visible

**Comment by hius07** [comment]
> This essentially locks up KOReader.

It can be unlocked with physical button sleep/wake-up.

**Comment by jonnyl2** [comment]
@hius07:

Besides QuickMenus, the above mentioned issue (KOReader locking up until touch is reenabled after sleep/wake-up) also occurs when using 'Show footnotes in popup'. When the footnote popup is being displayed, the device doesn't respond to any touch, not even the gesture defined to toggle the touch input. 

I'd like to put forward a different suggestion how this could potentially be addressed. Seeing that two-finger taps are currently only available for corner gestures, could they be made available as single-tap equivalents on the remainder of the screen as a user option, while touch is disabled? 

Then, a two-finger tap could be used to select a QM option, to dismiss a pop-up, or even to turn pages (without having to define separate always active gestures). 

Just an idea; not sure how feasible this is. Anyway, I really like the disable-touch feature and thank you for its implementation.

**Comment by NiLuJe** [comment]
Possibly related to modals being funky somehow. I don't remember how this works, and don't really have time to look into it right now, but it's proooobably not trivial to deal with.

The whole "disable gestures" thing is already kind of a magical hack, I don't really want to push it into an even hackish territory ;).

**Comment by jonnyl2** [comment]
I was quite impressed with how well the exempting of gestures works. I'm also okay giving up conveniences like QuickMenus while touch is disabled. And the end-of-book dialog can be anticipated ahead of time so touch can be enabled beforehand, or if one forgets then the sleep/resume workaround isn't such a big deal either, for once per book. 

The thing with the in-page footnotes is that they happen throughout the book. So if there's no simple solution for this touch problem, I would like to be able to toggle `Show footnotes in popup` along with `Toggle touch input`. Unfortunately, the former is currently not available in the Gesture manager. So I'd humbly request if this could be added in that case, but I'll wait and see how this develops.
