### ISSUE TITLE
Can't quit from application, still restarts

### ISSUE THREAD

**Issue by Glover1969** [koreader/koreader#10828]
Every time I want quit, Koreader restarts.
![20230819_095056](https://github.com/koreader/koreader/assets/92929735/e92e385f-570a-4ad0-8fee-35d1f14c9078)

**Comment by NiLuJe** [comment]
Are you using any custom plugin?

**Comment by Glover1969** [comment]
I don't use any plugins.  Rolling back to a lower and stable version solved
the problem on two readers.


Pozdrawiam

*Piotr Pachowicz*

sob., 19 sie 2023, 10:42 użytkownik NiLuJe ***@***.***>
napisał:

**Comment by NiLuJe** [comment]
> Rolling back to a lower and stable version solved the problem on two readers.

Rolling back *to* which version and *from* which version? And if that was a stable, what about a current nightly?

**Comment by NiLuJe** [comment]
I'm assuming that was a nightly, so, new question: *how* are you attempting to quit, exactly?

**Comment by Glover1969** [comment]
By menu and gesture. I have set tap on the lower right corner. Same on both
readers.


Pozdrawiam

*Piotr Pachowicz*

sob., 19 sie 2023, 12:41 użytkownik NiLuJe ***@***.***>
napisał:

**Comment by NiLuJe** [comment]
You still haven't told me on which version you were experiencing this ;).

**Comment by NiLuJe** [comment]
I'd also like a look at the full logs involved.

**Comment by NiLuJe** [comment]
> I'd also like a look at the full logs involved.

Specifically, I'm confused by the lack of `Tearing down UIManager with exit code` info message in there...

Unless something is killing us mid-`UIManager:run` in a very weird manner and at a very conspicuous timing, I don't see a way for this to *not* show up...
