### ISSUE TITLE
Question related to supporting javascript

### ISSUE THREAD

**Issue by k-aito** [koreader/koreader#10822]
Hello everyone,

I had asked last year for making a plugin and after losing few hairs I got it working pretty well.
If the concerned website gives me the approval that it may be used openly, I will add it on GitHub.

But... now that I finally can understand a little more about KOReader I want to do that for another website because I like to read on my e-reader but for this site it's not easy to display the pictures because it uses a JavaScript to set the picture in the correct way back. I guess that the better way to fix that would be to rewrite the JavaScript code, but I think it will be difficult, so I wanted to avoid it if it is possible?

Based on my research I didn't find any but with a bit of luck. Or maybe there exist an application that could interpret html / css / JavaScript and then "make a kind of screenshot"?

Anyway I'm accepting any ideas lol
Cheers

**Comment by poire-z** [comment]
There probably won't be any kind of support for Javascript in KOReader.
Moreover, if I guess correctly what you're willing to do (request some pages from a website to save them as local files or EPUB to read them offline in KOReader), you'd need more than just Javascript: you'd need a real web browser engine, as the Javascript on a web page manipulates the "object representation" of the web pages: nodes, elements, text, style, resources - and it's the web browser engine that expose all that to Javascript. We'll probably never have that.

Alternatives are to use some external web service that would render and simplify a web page (like the old "mobile view", before browsers on mobile phone became performant). (No idea if such thing still exist.)
Or create your own web application that KOReader would query - I guess Python or NodeJS have a way to copilot some "headless" browser engine to render the page, and save the resulting HTML or indeed make a screenshot of the whole page (but such a big fixed image will probably be not friendly to read on KOReader).

Or you manually saving web pages you like as EPUB in your web browser, ie. with https://github.com/alexadam/save-as-ebook.

Or use services like Wallabag to add URLs to and reveice them on your KOReader (I have no experience with them). https://github.com/koreader/koreader/wiki/Wallabag

> I had asked last year for making a plugin 

For reference, that was #9201

**Comment by k-aito** [comment]
Thanks, yes for the previous plugin I finally got it working, and I still save the picture locally because I could not make it work for using it directly from Lua after download but if it works it's good enough for me ^^

I will take a look in the few links because yes the headless thing could work in my opinion because from what I understand from the website it uses a picture where blocks are "randomized" and the JavaScript modify the HTML canvas to draw it back together.

The other way would to do that in Lua directly but yes I already see how painful it can be if they change their method... that will be awful ^^
