### ISSUE TITLE
2023.06.1 Turning off wifi triggers return to file browser process crash

### ISSUE THREAD

**Issue by isPoto** [koreader/koreader#10827]
* KOReader version:2023.06.1
* Device: Moaan inkPad X with Android 8

#### Issue
Returning to the file browser when not connected to wifi causes a crash and a popup asking if you want to connect to wifi.
Connected to wifi, back to normal

#### Steps to reproduce
Turn off the device wifi.
Open any document in any format.
Click on the File Browser (second button from the right in the top menu bar).
The process crashes, clicking on any area of the screen will indicate that the process is not responding. Wait half a minute for the process to return to normal and go back to the file browser.
At this point, Koreader will pop up two overlapping windows, prompting that wifi is not turned on and asking if you want to turn on wifi.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
This is fixed in current nightlies ;).

**Comment by isPoto** [comment]
> This is fixed in current nightlies ;).

When will the next version be available? Because this bug is very impactful to use, I hope to update it as soon as possible

**Comment by Frenzie** [comment]
I'll hopefully be able to work at it this weekend, but you can change the update channel to development and get something that's very close to the upcoming release.
