### ISSUE TITLE
Unreadable cbz format with folders

### ISSUE THREAD

**Issue by isPoto** [koreader/koreader#10829]
* KOReader version: 2023.06.1
* Device: Moaan inkPad X with Android 8

#### Issue
Unreadable cbz format with folders

#### Steps to reproduce
Merge folders with names 1~10 respectively into zip format.
Inside each of the 10 folders are sequentially named manga images.
Rename the .zip to .cbz
Import the .cbz into the device.
Koreader shows that the file cannot be read.

Read the .cbz file normally in Moon+ Reader Pro.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hugleo** [comment]
I've created a CBZ file with two folders and three files. It seems to open normally on my Android phone.

![comic](https://github.com/koreader/koreader/assets/4573505/0fd23ea7-3b1f-4ae6-a461-5a89db14a969)

[comic.zip](https://github.com/koreader/koreader/files/12420223/comic.zip)

**Comment by Frenzie** [comment]
Indeed, the sample file shows 6 pages.

**Comment by isPoto** [comment]
@hugleo @Frenzie 

https://www.swisstransfer.com/d/1cdf71e7-ee87-4a24-a4a4-f564e41828c3

I have uploaded the problem cbz file, please download and test it.

Koreader cannot read the cbz file, but other reading programs such as Moon+ Reader Pro and SumatraPDF software can read it normally.

**Comment by NiLuJe** [comment]
I'll wager it's simply a case of OOM given the file size ;).

**Comment by isPoto** [comment]
> I'll wager it's simply a case of OOM given the file size ;).

Do you mean that the file size is more than Koreader can handle?

**Comment by NiLuJe** [comment]
It'll depend on the device, IIRC, something along the way doesn't use mmap'ed I/O, so you'll need something like 1.5x to 2x the file size in free RAM.

**Comment by isPoto** [comment]
> It'll depend on the device.
> 
> IIRC, something along the way doesn't use mmap'ed I/O, so you'll need something like 1.5x to 2x the file size in free RAM.

Moaan inkPad x has only 2G RAM. can this be optimized?
Because other apps, reading apps and comic reader apps can be read

**Comment by hugleo** [comment]
Maybe is something else, is not loading even on my device with 8 gb ram.

![cbz](https://github.com/koreader/koreader/assets/4573505/f7340106-2f81-491a-809c-0649fbbf87d1)

**Comment by NiLuJe** [comment]
@hugleo: There might be 32-bit shenanigans on top of that if that's a 32-bit host.

**Comment by NiLuJe** [comment]
```
08/23/23-21:27:10 WARN  cannot open document /var/tmp/niluje/test/源君物语.cbz frontend/document/pdfdocument.lua:35: ./ffi/mupdf.lua:78: MuPDF cannot open file.: cannot seek: Invalid argument (2)
```

**Comment by NiLuJe** [comment]
Probably from `read_zip_dir_imp` not built to handle large offsets.

**Comment by NiLuJe** [comment]
Yup, backported yet another random upstream fix ;).

**Comment by NiLuJe** [comment]
FWIW, bread crumbs:

```
fz_seek to 0 @ 0
fz_seek to 0 @ 0
ensure_zip_entries
fz_seek to 0 @ 2
size = 3915788070
init back = 512
ensure_zip_entries: fz_seek to 3915787558
fz_seek to 3915787558 @ 0
fz_seek to -379179248 @ 0
error: cannot seek: Invalid argument
```

from some random printf debugging peppered around `fitz/unzip.c` & `fitz/stream-read.c` (I, err, dropped the patch during a rebase ;p).

**Comment by Frenzie** [comment]
@NiLuJe I'm pretty sure I've read 450+ MB CBZs fwiw.

**Comment by hugleo** [comment]
I applied the patch to my personal build, and it's running quite fast on my Android 6 Likebook with 2 GB of RAM. Even after moving all the files outside the multifolder, it still works.
Tried some random pages, the first, the last all good.

Memory doesn't seem to change too much, which means it's not loading the whole thing into memory.

Memory Statistics for the First Snapshot:
- Total RAM: 2041836 kB (status: normal)
- Free RAM: 1351366 kB (95870 cached pss + 1197980 cached kernel + 57516 free)
- Used RAM: 546619 kB (327535 used pss + 219084 kernel)
- Lost RAM: 143851 kB
- ZRAM: 4 kB physically used for 0 kB in swap (520908 kB total swap)

Memory Statistics for the Second Snapshot:
- Total RAM: 2041836 kB (status: normal)
- Free RAM: 1299329 kB (94729 cached pss + 1117752 cached kernel + 86848 free)
- Used RAM: 620828 kB (401696 used pss + 219132 kernel)
- Lost RAM: 121679 kB
- ZRAM: 4 kB physically used for 0 kB in swap (520908 kB total swap)

I still see the message 'No book information: not readable by the engine' in the file browser, but the openings are all working fine ;-)

**Comment by poire-z** [comment]
> I still see the message 'No book information: not readable by the engine' in the file browser, but the openings are all working fine ;-)

After a few unsuccesful tries, it caches that and stop trying. Just long-press on it and "Refresh cached book info".

**Comment by NiLuJe** [comment]
> @NiLuJe I'm pretty sure I've read 450+ MB CBZs fwiw.

Might have been PDFs-only then. Or it might have been magically fixed somehow. Or it might have been something else altogether, as it's admittedly been years since I looked into that ;o).

**Comment by NiLuJe** [comment]
> it's not loading the whole thing into memory

From what I vaguely recall (again: years ;p), that wasn't allocations for the reader, but... something happening during the document parsing/opening (i.e., it would have been reclaimed once opened).

I'm way too lazy to fire up valgrind to double-check all that ;).

**Comment by NiLuJe** [comment]
> it's running quite fast on my Android 6 Likebook

Good to know, I was mildly worried when I noticed it was managing to make my CPU fans spin up when paging like a madman (but, again 28°C ambient doesn't help ;p).

No memory concerns either, DocCache behaving as expected.

**Comment by Frenzie** [comment]
> Might have been PDFs-only then.

You may be right. On the left something I read on my H2O, on the right something I would've checked out on my desktop or laptop on account of color.

<img src=https://github.com/koreader/koreader/assets/202757/8ebb5a8c-4504-4892-be0b-70a7bf21aa4f width=40%>
<img src=https://github.com/koreader/koreader/assets/202757/2e82664e-4cba-48bc-a157-f70db2a48fb6 width=40%>
