### ISSUE TITLE
"Update information not available on stable channel" error

### ISSUE THREAD

**Issue by hightide591** [koreader/koreader#10839]
* KOReader version:2023.06.1
* Device: Kobo Clara2E

#### Issue
When i check for updates I get "Update information not available on stable channel."
#### Steps to reproduce

Press "check for updates"
Error occurs on different wifi networks.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
WARN cannot find update files: timeout
```
</details>

**Comment by NiLuJe** [comment]
The main OTA server is down (c.f., #10615).

In the meantime, you can switch to any of the mirrors, which are as up-to-date as they cna be (i.e., up to when koreader.rocks went down).
