### ISSUE TITLE
Koreader app crashing when opening in Pocketbook Inkpad Color 2

### ISSUE THREAD

**Issue by icclau** [koreader/koreader#10832]
* KOReader version: koreader-pocketbook-v2023.06.1
* Device: Pocketbook Inkpad Color 2

#### Issue
When I try to start Koreader from Apps section in Pocketbook, the icon remains highlighted for like 20 seconds, but then it goes back to the main screen without opening Koreader. This device is new, released only 2 months ago or so. Is it not supported yet?

#### Steps to reproduce
Open Koreader from Apps section.

[crash.log](https://github.com/koreader/koreader/files/12386920/crash.log)

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/pull/10685

You can grab a nightly from http://build.koreader.rocks/download/nightly/
