### ISSUE TITLE
FR: Automatic unit conversion in books

### ISSUE THREAD

**Issue by Atrate** [koreader/koreader#10834]
**Does your feature request involve difficulty completing a task? Please describe.**
Oftentimes when reading books written and published in the United States, I find
myself slightly frustrated with not being able to easily imagine the scale of
things if they are described in imperial units, say if it is written "she fell
30 feet down".

**Describe the solution you'd like**
I think it would be useful if KOReader supported automatically converting such
units to the metric system, for example by underlining the units in the book and
presenting a conversion on tap. The same would go for converting the other way
around, from the metric system to imperial. This way, if I see "20 yards"
written somewhere, I can just tap on it to see how many meters it is, instead of
having to take my phone out and look that up online.

**Comment by poire-z** [comment]
My natural intelligence is frowning at you for this feature request :) (The parsing, gathering possible units, and currencies, and the evolution of currency rate over the years, because I have no idea what 100$ meant in 1923...)
I think this is best left to artificial intelligences that can't frown !
ie. https://www.reddit.com/r/koreader/comments/12fpg62/askgpt_a_new_koreader_plugin_that_enhances_your/

**Comment by Atrate** [comment]
Given the inherent volatility, ambiguity ($ = AUD, USD, CAD?) and the fact that
an internet connection would be required, I think it's safe to say that currency
conversions are way out of the scope of this FR.

When it comes to parsing and heuristics, the sensitivity of an algorithm of
detecting units in text is not that big of a deal (in terms of false positives)
if the conversion possibility is inconspicuous enough, like an underline or
slight lightening of the text.

On the topic of AskGPT, I feel like this would be even more inconvenient than
just taking my phone out to check the units, at least for this specific use
case.

**Comment by Atrate** [comment]
> If you like that, it should be easy to add a function pass a selected text directly to the calculator, so you can perform the conversion there.

This sounds like a great idea, assuming it can auto-detect that e.g. "20 yards" means that it is to convert from yards

**Comment by Atrate** [comment]
Thanks! I presume I'll be able to test it out with the new KOReader release?

**Comment by NiLuJe** [comment]
No, it's in the contrib plugin tree, you just need to install the plugin yourself.

**Comment by poire-z** [comment]
Out of scope for the main program, but @zwim 's user plugin https://github.com/zwim/calculator.koplugin may help.
