### ISSUE TITLE
Android arm 2023.06 crashes 

### ISSUE THREAD

**Issue by wvhulle** [koreader/koreader#10838]
--------- beginning of system
08-22 09:03:52.606 E/OplusCustomizeRestrictionManager( 1929): sInstance is null, start a new sInstance

**Comment by wvhulle** [comment]
Device Realme 6i Android 11

**Comment by Frenzie** [comment]
Did you try if the arm and arm64 builds behave differently?

**Comment by pazos** [comment]
@wvhulle when reporting a bug please follow the template and attach the logs as requested. The only bit of info you attached seems totally unrelated with the crash you're experiencing.

**Comment by pazos** [comment]
no response
