### ISSUE TITLE
Wallabag plugin does not show in tools menu

### ISSUE THREAD

**Issue by Napator** [koreader/koreader#10844]
* KOReader version: 2023.06.01
* Device: Kobo Clara HD

#### Issue

Wallabag plugin does not show in tools menu

#### Steps to reproduce

Since an update of my Kobo clara device, i had to reinstall koreader. Everything works properly, but i've lost the wallabag line in the menu. 

Wallabag seems to be loaded properly : 
08/26/23-11:04:35 DEBUG FM loaded plugin wallabag at plugins/wallabag.koplugin 

It is not as well in the list of more tools -> "manage plugin" ("gestion des modules d'extensions" en francais).

Thank you for your help

**Comment by hius07** [comment]
Try English interface language. Maybe related: https://github.com/koreader/koreader/issues/10650.

**Comment by Frenzie** [comment]
Yes, the French translation had an issue there.

**Comment by Napator** [comment]
I confirm the English interface works well. Thank you
