### ISSUE TITLE
g-sensor events and autostandby

### ISSUE THREAD

**Issue by cgm999** [koreader/koreader#10846]
* KOReader version: v2023.06.1

* Device: Kobo Sage
* 
I have autostandby enabled, however it looks like rotating it is waking it up.. (seen on a usb meter when battery is at 100%).
Is there a chance to disable g-sensor at all from doing this ?  Thank you

**Comment by NiLuJe** [comment]
Not without mangling the dtb, I think (i.e., to stop it from being a wakeup source).

**Comment by cgm999** [comment]
I figured for the Sage this will disable the g-sensor
echo 1-001e > /sys/bus/i2c/drivers/kx122/unbind
I've put this in /mnt/onboard/.adds/koreader/koreader.sh at begining of the file.
