### ISSUE TITLE
FR: Launch directly into fullscreen

### ISSUE THREAD

**Issue by AngryAnt** [koreader/koreader#10858]
Platform: Linux desktop (Plasma Mobile).

Issue: Whenever I launch KOreader, my first step is always to fullscreen it. I am not interested in running the reader non-fullscreened.

Request: If holding the fullscreen toggle could pop up the dialogue requesting whether I’d like to change the default, this would be ideal and feel natural in the flow of the app.

**Comment by AngryAnt** [comment]
Ah! Most excellent - it is very effective. Thank you for the rapid response :)

**Comment by Frenzie** [comment]
You can also run it with SDL_FULLSCREEN=1

**Comment by Atrate** [comment]
I'd like to comment that with the release of the PineNote, this could not be considered "too specific" anymore. KOReader launches as "fullscreen" on most platforms (Android, Kobo, etc.) and the fact it does not on Linux is understandable on Desktop, but I think it would make sense for it to launch in fullscreen automatically (configurably) on Linux e-reader devices like the PineNote.
