### ISSUE TITLE
Bookmarks VS highlights 

### ISSUE THREAD

**Issue by yannvu** [koreader/koreader#10856]
I was trying to make highlights in an epub I'm reading. 
Using long press then select the words sentences. 
It kind of gets highlighted. 

But seems like everything I selected I can only find as bookmarks. 
Really don't understand how highlights work.

**Comment by poire-z** [comment]
They all (bookmarked pages and your highlights) end up being considered bookmarks and shown via the Bookmarks menu item/gesture in the Bookmark fullscreen view (where you can filter them with the top left "hamburger" menu).
Nothing much more to understand :)

**Comment by ryanwwest** [comment]
Should this be closed?
