### ISSUE TITLE
KOA3: Adjust brightness based on the light sensor does not work.

### ISSUE THREAD

**Issue by sndwichm4n** [koreader/koreader#10870]
* KOReader version: 2023.08
* Device: Kindle Oasis 3

#### Issue
The screen brightness does not change in small steps, but only completely off or on. In the Amazon reader, the brightness changes in small steps.

#### Steps to reproduce
Read with Koreader on a KOA3 in the Dark and go slowly in the light.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
What exactly do you mean by "go slowly"? How and where using which method?

**Comment by sndwichm4n** [comment]
I have expressed myself incorrectly. Go slowly in the light, means: Slowly change the light from dark to light. Go from the sun into the darkness.

But I still tried and had success. I have disabled the "Auto-frontlight"[1] plugin. Now the gradual brightness control works with the light sensor in Koreader.

I should have tried this months ago.

[1] https://github.com/koreader/koreader/wiki/Auto-frontlight

**Comment by Frenzie** [comment]
It's disabled by default by the way, so there doesn't seem to be anything that could be done.

**Comment by sndwichm4n** [comment]
Feature Request: Show the adjusted brightness in the status bar. Now is it static.

**Comment by NiLuJe** [comment]
Depending on how exactly the ALS works, that may not be possible.

I never had a Kindle with an ambient light sensor, but, given that this is a Kindle, I'm guessing that we defer everything to the native system, so we don't actually *know* when the ALS decides to change the brightness, and by how much, so we very well might not be able to track the updated state.

**Comment by NiLuJe** [comment]
Yup, in fact, we don't do *anything* with the ALS, the only thing that actually *queries* it is the aforementioned AutoFrontlight plugin.

So, yup, #cantfix.

**Comment by sndwichm4n** [comment]
Ok, thanks for the answer.
