### ISSUE TITLE
BQ Cervantes 4 can I still install koreader?

### ISSUE THREAD

**Issue by roozx** [koreader/koreader#10878]
Hello, 

Sorry for digging up this old thread but i really like the device, i own the one that was never activated and i am unable to do so now (white page - servers already down?) 
So i'm unable to install the developers firmware because theres noone to accept my device to the developers program - without it device does not update (i tried to force it and got error) 

Are there any ways for me to install koreader on official bqOS- 7.0.2 software?

**Comment by Frenzie** [comment]
Pinging @pazos

I think there was discussion about this 9n the MobileRead forum.

**Comment by pazos** [comment]
Somebody did it: https://www.mobileread.com/forums/showpost.php?p=4225738&postcount=36

Instructions there are 95% of what you need.

I'm sorry but we can't help until you get developers firmware installed.

But if/when you do please be nice and document the 5%, so the next time somebody asks we can provide a 100% link.
