### ISSUE TITLE
[PocketBook] Fail to open book at startup

### ISSUE THREAD

**Issue by Arias800** [koreader/koreader#10886]
* KOReader version: 2023.08-18
* Device: PocketBook 627

#### Issue
When I try to open a book from the device's library, the hourglass appears and nothing happens.
From what I understand from the logs, Koreader closes for no apparent reason.
I've discovered that the problem only occurs during the first start of Koreader. If I open Koreader manually and then try to open a book from the library, everything works.

#### Steps to reproduce
- Start the device
- Try opening a book from the base device library (Koreader must not be running in the background, otherwise the bug will not occur).

##### `crash.log`
[crash.log](https://gist.github.com/Arias800/ed018c4339a6125d24b2f818680c3296)

**Comment by NiLuJe** [comment]
> I've discovered that the problem only occurs during the first start of Koreader.

What's the timeframe there? Does it works until a reboot?

Or...


> If I open Koreader manually and then try to open a book from the library, everything works.

Is that with KOReader still *open* in the background or not?

(My train of thought being what actually matters is whether you start KOReader on the FM or on a specific book, and possibly only when that happens via the PB Library too boot).

----

In any case, it looks like a sane Close gets tripped, so, assuming you don't have any misbehaving custom plugins, you could stick a traceback in there to see what's actually happening:

```diff
diff --git a/frontend/apps/reader/readerui.lua b/frontend/apps/reader/readerui.lua
index b5b44f298..df63a3696 100644
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua
@@ -776,6 +776,7 @@ end
 
 function ReaderUI:onClose(full_refresh)
     logger.dbg("closing reader")
+    print(debug.traceback())
     PluginLoader:finalize()
     Device:notifyBookState(nil, nil)
     if full_refresh == nil then
```

**Comment by NiLuJe** [comment]
Also, since you're on a nightly, is this new behavior, or did this happen on the latest stable?

**Comment by Arias800** [comment]
I reinstalled Koreader from scratch and the problem disappeared.
It may have been a bug of my device.
I'm closing the issue and will reopen it if the problem occurs again.
