### ISSUE TITLE
Crash after Reflow pdf

### ISSUE THREAD

**Issue by TheFuzzStone** [koreader/koreader#10887]
* KOReader version: 2023.08
* Device: Onyx Boox Page

#### Issue

The title.

#### Steps to reproduce

1. Open Koreader
2. Open any .pdf
3. Bottom menu -> Reflow On -> select any value -> tap on screen

Crashlog: 

[crashlog.txt](https://github.com/koreader/koreader/files/12566883/crashlog.txt)

**Comment by NiLuJe** [comment]
Dupe of #10533 (and quite a few others).
