### ISSUE TITLE
FR: Android: change Settings > Screen Timeout from `Use system settings` to `Keep screen on`

### ISSUE THREAD

**Issue by foss-** [koreader/koreader#10884]
New to KOReader on Android and the initial usage feelt difficult since some default behaviors are unexpected. The most obvious being that the screen kept turning off while reading.

After looking into the settings for a while found the relevant switch: changing `Settings > Screen Timeout` from `Use system settings` to `Keep screen on` did the trick.

**Describe the solution you'd like**
It would be great (at least for the Android version) to default to `Keep screen on`. After all this is a reader and having the device continuously turn off the screen while reading is not helpful. Would it be possible to change the default?

It's probably fair to assume the same logic that video players use and keep the screen on.

**Comment by Frenzie** [comment]
That analogy doesn't work. Reading a page of text in your browser takes just as long, so if the system-wide timeout setting is too low it's too low. Keeping the screen on like a video player would be much less expected behavior.

**Comment by foss-** [comment]
Tend to disagree here. I would compare an ebook reader app more to a media center app or video player app and those try to keep screen on as soon as media is playing. The analogy would then be: as soon as an ebook is open in an ebook reader that should keep the screen on.
Since you've been involved in this space much longer than me and have more experience I am certainly more than happy to accept your decision.
