### ISSUE TITLE
Missing build dependency for Debian (and probably Ubuntu)

### ISSUE THREAD

**Issue by mytskine** [koreader/koreader#10896]
* KOReader version: master
* Device: PC with Debian testing

#### Issue
Building fails at the lilzmq step with the message:
```
autogen.sh: error: could not find libtool.  libtool is required to run autogen.sh.
```
#### Steps to reproduce
Follow the official guide to build koreader:
```
sudo apt install build-essential git patch wget unzip \                                                     
    gettext autoconf automake cmake libtool nasm ragel luarocks lua5.1 libsdl2-dev \
    libssl-dev libffi-dev libsdl2-dev libc6-dev-i386 xutils-dev linux-libc-dev:i386 zlib1g:i386
./kodev fetch-thirdparty
./kodev build
```
#### Solution
Add `libtool-bin` to the required dependencies.

**Comment by NiLuJe** [comment]
Was libtool kicked out of `build-essentials`? (Or whatever the base "I need to build stuff" set is actually named... Oh, how I love binary distros...)

**Comment by Frenzie** [comment]
@NiLuJe It was never in build-essentials; that's just a shortcut for gcc, g++, make and like two or three packages of header files. You'll note it says `libtool` right in between `cmake` and `nasm` in that line. ;-)

Anyway, this is indeed an oversight in the README, and a very old one to boot it would seem. https://github.com/koreader/virdevenv/pull/26
