### ISSUE TITLE
Orietantion change only didplays on half the screen

### ISSUE THREAD

**Issue by lweendela** [koreader/koreader#10891]
* KOReader version: v2023.08
* Device:a01 corextc

#### Issue
Orietantion change from vertical to landscape and vise versa works but the document will only be dispayed on half the screen. Display will only go to full screen after reluanching app

#### Steps to reproduce
Change document orientation from vertical to landscape and vise versa

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hugleo** [comment]
Duplicated from https://github.com/koreader/koreader/issues/10808 and a few others.

@pazos will look into it in the future. I have created two patches and comments that can be helpful in solving the problem.

**Comment by NiLuJe** [comment]
Closing in favor of the earlier/more detailed issue(s) ;).
