### ISSUE TITLE
After I resize the text, application freezes for 10 seconds, then "error connecting to wifi" comes up. Can I not use this without internet access?

### ISSUE THREAD

**Issue by ForHelvete** [koreader/koreader#10898]
Installed on Galaxy S5.

After I resize, a little icon in the top left comes up that looks like a document with refresh-arrows at the bottom, program remains locked for 10 seconds and then "error connecting to wifi" comes up. What is it doing? How do I turn it off?

**Comment by Galunid** [comment]
It should work without internet. By any chance do you have automatic syncing enabled?
Top Menu -> 4th tab -> Progress sync -> Automatically keep documents in sync

**Comment by NiLuJe** [comment]
And which version of KOReader are you running?

**Comment by NiLuJe** [comment]
(Also, on what kind of ePub are you trying that, because an S5 is possibly going to have a hard time on very large and/or pathologically complex documents).

**Comment by ForHelvete** [comment]
> It should work without internet. By any chance do you have automatic syncing enabled? Top Menu -> 4th tab -> Progress sync -> Automatically keep documents in sync

That fixed it.

> (Also, on what kind of ePub are you trying that, because an S5 is possibly going to have a hard time on very large and/or pathologically complex documents).

1000 page books at most. Doesn't seem to strain it too much.
