### ISSUE TITLE
FR: Add support to Remarkable 2 virtual directory structure and show ebooks on KO Reader's Home, similarly to Remarkable 2 

### ISSUE THREAD

**Issue by paulolc** [koreader/koreader#10907]
**Does your feature request involve difficulty completing a task? Please describe.**

KOReader installed on Remarkable 2 (RM2) does not show in Home, the ebooks that RM2 and not with the directory structure that appears in RM2

After installing KOReader on my RM2 to open the ebooks I already have in Remarkable 2 I have to change explicitely to the xochitl directory (/home/root/.local/share/remarkable/xochitl). Even there KOReader only is capable of showing the low level filesystem structure. It doesn't recognize the RM2 virtual folder structure and doesn't filter any files, making it very cumbersome to access the RM2 existing ebooks as all types of RM2 low level files are listed. The files KOReader supports are listed but also the files that KOReader cannot open which are a lot of them. Remember that in RM2 virtual filesystem the files are named with hashes and each file has a directory with metadata.

**Describe the solution you'd like**

Ideally, it should be possible to see the ebooks in KO Reader's Home, as they are listed in Remarkable 2 with the same (RM2 virtual) directory structure.

**Describe alternatives you've considered**

The only solution/workaround I know and use is to create a folder shortcut in KOREADER to the RM2 xochitl directory (/home/root/.local/share/remarkable/xochitl). Even then I have to click on the menu and then click on the folder shortcuts and only then to select the saved RM2 xochitl directory shortcut)

**Additional context**
I've used instructions to install KOReader on RM2 using this gist: https://gist.github.com/ryuheechul/f8c656efeec635b9b5292a6bd51ca00c

**Comment by NiLuJe** [comment]
I would argue that's extremely out of scope, mainly because that's a platform-specific implementation detail that's outside of our control, and also because potentially filled with unsupported or DRM'ed stuff.

If someone wants to build a plugin for that, go wild, but I don't see that happening any time soon, and certainly not in core ;).

**Comment by NiLuJe** [comment]
And we're not treating rM as a special snowflake here, FWIW.

On Kobo, we explicitly hide the system folders (#10251), and on Kindle, we don't support the file formats, so they're also hidden by default.

**Comment by NiLuJe** [comment]
Full disclosure: I've never used a rM, so I only have a vague inkling of what's actually happening here re: how rM implements their stuff.

**Comment by Eeems** [comment]
> I would argue that's extremely out of scope, mainly because that's a platform-specific implementation detail that's outside of our control, and also because it's potentially filled with unsupported or DRM'ed stuff, which would be unusable anyway.

The rM2 doesn't have DRM, or a store to download books. Epubs are converted to PDF on device when you try to open them from what I understand, and it's just a simple flat filesystem with JSON files for the metadata, including user drawn content, and the virtual filesystem.
You can find more information in the linked page in this stub article (at least until the stub is flushed out with the content instead): https://remarkable.guide/devel/device/documents.html

Whatever is implemented would probably want to use the usb web interface to make sure user content (notebook, notes on pdfs and epubs, etc) can be viewed: https://remarkable.guide/tech/usb-web-interface.html

> 
> If someone wants to build a plugin for that, go wild, but I don't see that happening any time soon, and certainly not in core ;).

I agree, a plugin seems like the better place for this.

**Comment by paulolc** [comment]
> Whatever is implemented would probably want to use the usb web interface to make sure user content (notebook, notes on pdfs and epubs, etc) can be viewed: https://remarkable.guide/tech/usb-web-interface.html

Why use the usb web interface? I mean, the KOReader installed in rM2 would have direct access to its filesystem, so I think it wouldn't need the usb web interface. What am I missing?

**Comment by Eeems** [comment]
> > Whatever is implemented would probably want to use the usb web interface to make sure user content (notebook, notes on pdfs and epubs, etc) can be viewed: https://remarkable.guide/tech/usb-web-interface.html
> 
> Why use the usb web interface? I mean, the KOReader installed in rM2 would have direct access to its filesystem, so I think it wouldn't need the usb web interface. What am I missing?

The web interface allows exporting user generated content (lines, highlights, notebooks, etc) in a PDF form. This means you don't have to write and maintain a parser for the format to display this content, which is a lot of ongoing work.

**Comment by pazos** [comment]
Hey, I'm going to close the ticket as not planned. Feel free to keep the conversation going on.

In case somebody implements a working solution that cannot be addressed cleanly as a plugin feel free to PR against this repo, as a draft. We might want to have a "fuse" view for the file manager, so it is able to list things that are not on the filesystem, and provide hooks that 3rd party plugins can use to do their business.
