### ISSUE TITLE
Crash when double finger swipe is used as gesture in file manager

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#10903]
* KOReader version: 2023.08 and earlier

#### Issue
Gesture manager seems to confuse gestures as front light intensity change when in File manager

#### Steps to reproduce
1. Set toggle wifi (and possibly other actions as double finger swipe up/down).
2. Go to file manager
3. Execute the gesture
4. 💥BOOM💥

<details>
  <summary>crash.log</summary>

```
09/15/23-05:53:49 INFO  Restoring user input handling 
./luajit: frontend/device/devicelistener.lua:123: attempt to perform arithmetic on local 'delta_int' (a boolean value)
stack traceback:
	frontend/device/devicelistener.lua:123: in function 'onChangeFlIntensity'
	frontend/device/devicelistener.lua:147: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:887: in function 'sendEvent'
	frontend/dispatcher.lua:1104: in function 'execute'
	plugins/gestures.koplugin/main.lua:1160: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:253: in function 'handleEvent'
	frontend/ui/uimanager.lua:887: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1416: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1514: in function 'handleInput'
	frontend/ui/uimanager.lua:1558: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 09/15/23 @ 05:54:15)
Running FW 4.19.14123 on Linux 4.1.15-00084-gcd0d3a4 (#29 SMP PREEMPT Wed Nov 21 11:31:06 CST 2018)
Attempting to restart KOReader . . .
!!!!
```
</details>

**Comment by NiLuJe** [comment]
That's... weird. The *only* caller for `IncreaseFlIntensity`/`DecreaseFlIntensity` is Dispatcher itself, so something is getting confused in there somehow :?.

I'll let our resident dispatcher wizards figure this one out ;).

(Obvious question is obvious: have you double-checked that you don't actually have a "frontlight brightness" action that snuck into your gesture somehow?)

**Comment by Galunid** [comment]
Yeah, now that I checked there seems to be something wrong with my gestures configuration, there was some decrease frontlight in the `gestures.lua` that wasn't displayed in gesture manager. I had this install since like 2019/2020, so it was probably some left-over from dispatcher rework I was using nightly builds too at the time.
