### ISSUE TITLE
2023.08 Lavender causes screen flickering on Kindle 4

### ISSUE THREAD

**Issue by Darthagnon** [koreader/koreader#10910]
* KOReader version: KOReader v2023.08 Lavender
* Device: Kindle 4

#### Issue
I just updated to [koreader-kindle-v2023.08.zip](https://github.com/koreader/koreader/releases/download/v2023.08/koreader-kindle-v2023.08.zip) from **koreader-kindle-v2022.11.zip** and now every menu item I toggle through causes a full screen blank refresh (not a dark refresh, just a blank one). So it looks like it's flickering (very jarring) as I scroll the list of books, menu options, etc.

#### Steps to reproduce
Install Lavender on a Kindle 4. I use **koreader-kindle-v2023.08.zip** rather than Legacy packages as per the Wiki.

##### `crash.log` (if applicable)
No crash log

**Comment by Darthagnon** [comment]
Bug also present in:
- [2023.06.1](https://github.com/koreader/koreader/releases/tag/v2023.06.1)

**Comment by Darthagnon** [comment]
I wonder if it's a bug with Partial Rendering, introduced in [2023.03](https://github.com/koreader/koreader/releases/tag/v2023.03)? I can't find where to switch partial rendering off, though, to test.

**Comment by Darthagnon** [comment]
Last good version for Kindle 4 I thought was [KOReader 2022.11 "Froggy"](https://github.com/koreader/koreader/releases/tag/v2022.11), but now that seems to be doing the full screen blank flicker while navigating menu items, too... 😭

**Comment by NiLuJe** [comment]
> I wonder if it's a bug with Partial Rendering (#10124), introduced in [2023.03](https://github.com/koreader/koreader/releases/tag/v2023.03)? I can't find where to switch partial rendering off, though, to test.

Ought to be irrelevant, as that's a CRe-specific feature, and you're talking about something happening in the Ui (possibly outside of the reader entirely, e.g., in the filemanager?).

Stupid question is stupid: does is still happen after a full device reboot? Does it also happen with native Kindle menus (probably the in-Reader ones ought to be closest in behavior)?
Does it happen if you start KOReader in no framework mode?

**Comment by NiLuJe** [comment]
I can't reproduce on a K4 over here, FWIW.

I thought it might have been a nightmode snafu, but, nope, that works okay, too.

**Comment by Darthagnon** [comment]
It does seem something else is at play, as I came home today to find the battery completely drained, in less than a day idle. I reckon some prior experiments with VNC and SSH access must have glitched something and caused the battery drain as well as possibly the glitches with KOReader. Currently no framework Froggy is working as it should. I will attempt an update back to the latest and see if it's all working.

**Comment by Darthagnon** [comment]
Update to latest Lavender now works, testing no framework. I think it must have been some temporary bug with SSH or VNC, or perhaps some sort of incompatibility.

**Comment by NiLuJe** [comment]
VNC sounds like a good candidate for screwing things up, FWIW.

**Comment by Darthagnon** [comment]
Is VNC on Kindle known to cause issues? I was a bit mystified, because as far as I could tell I had killed sshd and nothing related to VNC was running when I booted up KOReader. But I guess something must have stayed running in the background...

**Comment by NiLuJe** [comment]
Depends on the implementation, but I can definitely think of myriad ways it could upset the system.
