### ISSUE TITLE
Pocketbook Verse PB629 unrecognized model

### ISSUE THREAD

**Issue by gutegeschmack** [koreader/koreader#10913]
* KOReader version: v2023.08-23-g3f677a7fd_2023-09-13
* Device: Pocketbook Verse (PB629)

#### Issue
KoReader crashes on start

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/12651853/crash.log)

**Comment by gutegeschmack** [comment]
Okay i fixed it through try and error by adding the PB629 (copy&pasted the parameters of the PB700 with correct dpi=212). I will attach the new device.lua as .txt for everyone with the same Problem BUT I'm a complete newbie and have no idea if this is a sufficient fix but everything looks good so far.
[device.txt](https://github.com/koreader/koreader/files/12653666/device.txt)

**Comment by Frenzie** [comment]
Sounds good! If the conclusion remains the same after a few days of testing I think we can merge that.

**Comment by ElimGarak1** [comment]
https://github.com/koreader/koreader/pull/10938
