### ISSUE TITLE
FR: Use System Frontlight level (Android app)

### ISSUE THREAD

**Issue by criztovyl** [koreader/koreader#10920]
**Does your feature request involve difficulty completing a task? Please describe.**

It seems KOReader as Android is not able to reuse the system frontlight intensity.

**Describe the solution you'd like**

I would like to have an checkbox for simply using the screen brightness android has set (manually or automatically).

**Describe alternatives you've considered**

Adjusting brightness manually is quite annoying.
turning frontlight off is too dark on my device (Fairphone 4).

**Additional context**

While searching for similar issues I found some mentions of "use system intensity", but my dialog looks quite different (native) to the screenshits there (internal dialog).

<details>
  <summary>screenshots</summary>

I refer to this "frontlight" option here:

![Screenshot_20230920-135348_KOReader](https://github.com/koreader/koreader/assets/2174918/4393d8ae-eb7f-4f04-8a82-9adcca925200)

which opens this dialog:

![Screenshot_20230920-083603_KOReader](https://github.com/koreader/koreader/assets/2174918/50681c03-8b0a-45a8-8a7b-b9a54e586a4d)

this is how my system-wide brightness is set (note it's "auto" brightness)

![Screenshot_20230920-083817_KOReader_1](https://github.com/koreader/koreader/assets/2174918/d9aa9699-71a2-4dff-82ef-19c62b5641a0)

about koreader dialog:

![Screenshot_20230920-083618_KOReader](https://github.com/koreader/koreader/assets/2174918/3609ba3f-9509-4ee5-bd86-7ed926882bc9)

</details>

**Comment by Frenzie** [comment]
> I would like to have an checkbox for simply using the screen brightness android has set (manually or automatically).

Isn't that the default behavior?

**Comment by criztovyl** [comment]
Hmm, not sure, at least currently the intensity is always the one manually set within koreader app and i am not sure how to revert back to the default then.

**Comment by Frenzie** [comment]
Pinging @pazos

**Comment by criztovyl** [comment]
I have also added a screenshot how i got to the dialog.

**Comment by pazos** [comment]
Actually a PR to add a checkbox for drivers with a fallback isn't a bad idea.

The program, in its current state, doesn't provide any means to restore system brightness other than killing the entire app. I'm going to assume that users that want to use system brightness will want to avoid to change brightness in KO entirely and avoid using the gestures et al to modify such settings.

As  @Frenzie said, that's the default behaviour: we inherit system settings and never change them unless you use frontlight gestures or the dialog in your screenshot.

If somebody wants to implement said checkbox it should be a matter of modifying https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/dialog/LightDialog.kt

The `show` function receives a controller as a parameter. You can query if a driver has a fallback with `controller.hasFallback()`. If that's true then draw the checkbox. The checkbox should be auto-checked when activity brightness matches system brightness and auto-unchecked when they don't match. Clicking on the checkbox when it is unchecked should disable the activity brightness override and restore the seekbar position to whatever system brightness is appropiate.

I'm going to label as won't fix as I think none of the maintainers is going to work on that, but certainly I would be glad to help with the details if somebody else wants to do the job :)

**Comment by criztovyl** [comment]
> As @Frenzie said, that's the default behaviour: we inherit system settings and never change them unless you use frontlight gestures or the dialog in your screenshot.

Is there a workaround available to return to default behavior after accidentially changing it (i initially acidentially changed it via the gesture)?

**Comment by criztovyl** [comment]
Static Frontlight level seems to reset to system setting at some point.
i have to check whether a full reboot is required (I noticed koreader uses system brightness again just now, and I rebooted recently for LineageOS updates...)

**Comment by criztovyl** [comment]
ah, yes, closing the app helps.

this means that after unintentionally touching the setting, you can revert to system setting by restarting the app.

that solves the issue for me, closing.
