### ISSUE TITLE
Cover image: size and background doesn't apply for pdf/cbz

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#10922]
* KOReader version: 2023.08
* Device: PB970

#### Issue
Cover image has a function to crop the cover to fit on the screen within a certain aspect ratio treshold and if it doesn't crop, to set the background to white, grey or black. This works well in epub books, but I've noticed that neither function apply to image based formats, such as pdf and cbz. Backgrounds within the treshold don't crop and always have a white background.

#### Steps to reproduce
1. Turn on cover image
2. Open an image based book
3. Put the device to sleep
4. The cover should look as described

I do know that text and image handling is handled by different engines, so my assumption is that the image formatting is only applied to the text engine. I think that this should be the case for both.

**Comment by pazos** [comment]
I'm afraid it is not possible.

Each supported `document` has a method `getCoverImage`. In the case of non reflowable documents [the image is just the first page](https://github.com/koreader/koreader/blob/55daf9fbf4d315a898f6c3826c82a4b904f77f19/frontend/document/koptinterface.lua#L327-L335)

You would also get the same result on reflowable documents if the cover image has borders within the image itself, as in:
![Sin nombre](https://github.com/koreader/koreader/assets/975883/5b6ba88c-bd46-4074-bd12-844623890bd9)

**Comment by Frenzie** [comment]
Though usually a PDF just has a full image as the first page in which case it'll all work out.
