### ISSUE TITLE
Long press books sorting gone for current book

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#10933]
* KOReader version: 2023.08
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
I remember bringing up this issue before until it was fixed. 

So the “Read”/“On hold”/“Reading” buttons are gone from the History’s long press menu. 

#### Steps to reproduce
Open a book. 
Go to History
Long press current book, see menu - these options are missing. 
Long press any other book - they are here and work as usual. 

This not a critical bug or anything, I just close History and open Book Status menu and do changes there. 

Thanks!

##### `crash.log` (if applicable)
Please let me know if the log is really necessary so I will make myself take them and upload :D (too lazy otherwise, sorry)

**Comment by Frenzie** [comment]
In https://github.com/koreader/koreader/pull/10132 it says fixes due to their addition.

**Comment by mergen3107** [comment]
Can I try removing `or is_currently_open`?

**Comment by hius07** [comment]
I'm afraid the status will not be saved after closing the document.

**Comment by mergen3107** [comment]
But how does it gets saved through Book status? Can’t the same mechanism be implemented in this context menu as well?

**Comment by mergen3107** [comment]
As alternative, can Book status button be added to currently open book menu?

**Comment by hius07** [comment]
Why not to call Book status from the book?

**Comment by mergen3107** [comment]
Habits? 
I usually open and skim 5-7 books, then sort them all to these three categories. I do this from History and its sections. The missing current book buttons adds extra steps to this process.
