### ISSUE TITLE
Profiles not working in Android devices if just font face

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#10930]
I recently changed all my profiles to not set up font size and I realized they don't work anymore in my phone. They work fine in Kobo devices.

It is quickly tested creating a couple of profiles with just font. The font is not changed when selecting them.

I have a few profiles that change just margins and line height and they don't work either.

Thanks.

**Comment by hius07** [comment]
Can you give more details.
What is the version of KOReader?
Do gestures work? How do you start profiles that do not work?
Can you try other actions in a profile (frontlight, restart, show history etc).
Can you create a profile with, say, set font size to 20, open a document, go to Profiles and show this profile as QuickMenu. Does it change the font size of the text?

**Comment by jospalau** [comment]
> Can you give more details. What is the version of KOReader?
> 
> Do gestures work? How do you start profiles that do not work?
> 
> Do you apply font size, margins, line height to a reflowable document?
> 
> Can you try other actions in a profile (frontlight, restart, show history etc).
> 
> Can you create a profile with, say, set font size to 20, open a document, go to Profiles and show this profile as QuickMenu. Does it change the font size of the text?

Pulled the trigger too quickly, sorry 😳. I use a modified version I pack from time to time. I tested and works fine.

 I will close it

**Comment by jospalau** [comment]
I have a bit of code to adapt the font size of the profiles to my devices. It was crashing silently... Sorry again
