### ISSUE TITLE
Timesync and wifi issue

### ISSUE THREAD

**Issue by diff111** [koreader/koreader#10932]
* KOReader version: 2023.08
* Device: Kindle Voyage

#### Issue

First, I would like to thank the developers for their fantastic work.

I have two issues. 

The first issue is that timesync is not working. Time is always lagging a few minutes. I don't know if it's supposed to update automatically. And yes, I am connected to wifi. In any case, I also apply "Synchronize time" from the menu, and I get a message that the time was updated but the updated time is still wrong.

The second issue I have is that toggling wifi crashes Koreader once every 2-3 times.

#### Steps to reproduce

Apply "Synchronize time" from the menu, the time is updated but it is wrong (lagging a few minutes).

Toggling wifi crashes Koreader once every 2-3 times.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
[crash.log](https://github.com/koreader/koreader/files/12702684/crash.log)

  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
> I don't know if it's supposed to update automatically.

Not from KOReader anyway; the Kindle system might. For reference, my Kobo Aura H2O v1 is off by about 20 seconds and the last time I synchronized it was probably a few years ago, or at the very least a great many months.

Pinging @NiLuJe

**Comment by NiLuJe** [comment]
I'm mildly sure timesync isn't supposed to work on Kindle. Unless you've setup drastic iptables rules, it should already sync on its own.

As for the crashes, logs would be helpful.

**Comment by NiLuJe** [comment]
> I'm mildly sure timesync isn't supposed to work on Kindle.

Assuming it actually ships ntpdate (I haven't checked, but the author of the plugin had access to the device, so I'm going to assume it does, or at least it did at the time), it'll just do a one-shot clock reset, it won't start a network time server like it does on Kobo.

Now, Kindles being Kindles, that's... not really how you're supposed to handle time there. You *can*, but the framework doesn't really like it.

That should be mostly irrelevant here, though, unless you are actually talking about native UI time being out of sync, becaus,e yeah, that's what'll happen if you do that.

**Comment by NiLuJe** [comment]
> not really how you're supposed to handle time there.

Conversely, the not-in-a-plugin manual "set time and date" menu entry *will* do it correctly.

**Comment by hius07** [comment]
Log is here
https://github.com/koreader/koreader/files/12702684/crash.log

**Comment by NiLuJe** [comment]
```
./luajit: frontend/apps/reader/modules/readerrolling.lua:1043: attempt to index field 'document' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerrolling.lua:1043: in function 'onUpdatePos'
	frontend/apps/reader/modules/readerrolling.lua:1013: in function 'action'
	frontend/ui/uimanager.lua:992: in function '_checkTasks'
	frontend/ui/uimanager.lua:1438: in function 'handleInput'
	frontend/ui/uimanager.lua:1558: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013ead
```

*After* an `onCloseDocument`... Possibly fixed in master already, or it's from a weird plugin I never actually have enabled (autoturn?).

**Comment by diff111** [comment]
> Conversely, the not-in-a-plugin manual "set time and date" menu entry _will_ do it correctly.

Yes, but after a crash (which happens because of the wifi problem) the time will again be wrong.

**Comment by NiLuJe** [comment]
> _After_ an `onCloseDocument`... Possibly fixed in master already, or it's from a weird plugin I never actually have enabled (autoturn?).

@diff111: Do you remember what prompted the network connection? (09/22/23-18:17:51)

**Comment by NiLuJe** [comment]
Did you *also* happen to be playing with profiles and/or bottom-menu settings at the time?

https://github.com/koreader/koreader/blob/38d468f36cf973838381600c393f6eaf208049f4/frontend/apps/reader/modules/readerrolling.lua#L1006-L1016

(That's racy, can't guarantee nextTick won't happen *after* a CloseDocument).

**Comment by diff111** [comment]
I was indeed playing with the menus. I just installed Koreader and I was adjusting it to my liking. I have a shortcut for the wifi toggling (corner tap).

**Comment by diff111** [comment]
> > _After_ an `onCloseDocument`... Possibly fixed in master already, or it's from a weird plugin I never actually have enabled (autoturn?).
> 
> @diff111: Do you remember what prompted the network connection? (09/22/23-18:17:51)

I guess it's either the wifi being turned on or the "Synchronize time" from the menu.

**Comment by NiLuJe** [comment]
> it won't start a network time server like it does on Kobo.

Correction: `ntpd` is *also* used in one-shot mode ;).

**Comment by NiLuJe** [comment]
AFAICT, WiFi was kind of a red herring here, it was simply involved because the N stands for network in NTP ;p.

**Comment by oldman63** [comment]
KOReader Nightly v2023.10-79-g35333356ff_2023-12-28
Kindle PW5

Current time is 14:03
"Synchronize time plugin" is wrong time synchronized

From Terminal Emulator:

```
# ntpdate -s hu.pool.ntp.org
# date
Thu Dec 28 13:23:14 GMT+0:20100 2023
```

Why? What am I doing wrong?

**Comment by NiLuJe** [comment]
You might need to fix your timezone first. I'd recommend doing it the Kindle way via `settz` (or just the Linux way by doing it yourself, IIRC, the symlink is somewhere in /var/local).

**Comment by mergen3107** [comment]
When I had my PW3 on hand, I did replace the /var/local/system/tz file, it is for time zones. I replaced it with the same one from Ubuntu to have proper Dst switch.

https://www.mobileread.com/forums/showpost.php?p=4209181&postcount=7

**Comment by mergen3107** [comment]
> I'm mildly sure timesync isn't supposed to work on Kindle.

It works on Kindle Scribe (5.16.2) :D 
I hit "Synchronize time", wait 1-2 seconds and I see a popup that say what date and time were set up to a second.
