### ISSUE TITLE
Default KoSync server down

### ISSUE THREAD

**Issue by Bartvelp** [koreader/koreader#10936]
* KOReader version: N.A.
* Device: N.A.

#### Issue

The default server used for the progress sync, https://sync.koreader.rocks is down. This results in error messages when trying to sync progress or login.

#### Steps to reproduce

Please visit: https://sync.koreader.rocks/healthcheck
to see the Cloudflare error page.

I'll probably install my own instance, but this should be fixed for other users. Please ignore/close if already reported through other channels.

**Comment by Frenzie** [comment]
See discussion in https://github.com/koreader/koreader/issues/10615#issuecomment-1722075351
