### ISSUE TITLE
Crash log appears in the reader and is recognized as a new book

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10947]
* KOReader version: Latest on 25.09.23 (08.2023 Lavender)
* Device: PocketBook Color 633

#### The crash log constantly pops up on the main screen of the reader as a new discovered book. I delete or hide it, it appears again, it’s unpleasant when an incomprehensible crash log pops up among the books.
Is there the way to hide it forever? I'm tired of deleting it, it always appears seconds later. 

Look at photo of this problem below. I hope you will fix it in new version. Because I can't program it even if you give instructions.

![IMG_20230925_131621.jpg](https://github.com/koreader/koreader/assets/119916135/5c03cd56-ab6c-4a4c-ba50-810b1f901f96)

**Comment by Frenzie** [comment]
The PocketBook system is detecting files from `system` or `applications` as new books?

**Comment by ZHANYLone** [comment]
> The PocketBook system is detecting files from `system` or `applications` as new books?

Yes
From applications, I suppose

**Comment by pazos** [comment]
It is covered on the installation guide.

https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices#integration-with-pocketbook-os-optional
