### ISSUE TITLE
FR: [Add a SEPARATE section (app, menu) with notes to the application]

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#10949]
**Add a separate section with ONLY NOTES to the application so that you can view the notes of all books in one place without opening books separately (itself). With the Search option that will search words you type through all books every one**

**This is already in the Pocketbook itself, the application is called NOTES (photo below)**
You can copy the idea from PocketBook Notes application

**It is very inconvenient to open EVERY book just for notes search

![IMG_20230925_164704.jpg](https://github.com/koreader/koreader/assets/119916135/09862c9b-c6fb-4fbb-b5e5-f63a1895167d)

**

**Comment by pazos** [comment]
It isn't easy nor hard. It is plainly not doable.

The best thing that can be done is to lurk on all the notes on the history. That's the only "database" of books we have available to grasp their notes.
