### ISSUE TITLE
FR: allow both physical page turn buttons to "page forward"

### ISSUE THREAD

**Issue by sdothum** [koreader/koreader#10943]
After installing and uninstalling KOReader countless times, i finally gave it good look and now cannot go back to my Kobo Nickel+kobopathes configuration. All it took was the patience to spend a day to get comfortable with the breadth of its power and set up the gestures to make my long reading sessions even smoother -- should have done this way sooner!.

One thing i miss from kobopatches is the ability to configure both page turn buttons to page forward. Sounds odd but i will during long reading sessions change my hand position so the thumb rests on one or the other button. Using my thumb to tap the screen for the odd time i need to page back i find is still more convenient than contorting the thumb to reach for the opposite button.

i've set up, of course, a gesture to invert the page turn buttons, so this would just be icing on the cake. Just curious whether this option could be something easily accommodated.

**Comment by pazos** [comment]
@sdothum: [keymappings](https://github.com/koreader/koreader/wiki/Keymapping) are exactly what you want ;)

**Comment by sdothum** [comment]
@pazos: Thank you Thank you Thank you!!!

This works like a charm!
