### ISSUE TITLE
Support for Xbox joystick controls and customizable keystrokes

### ISSUE THREAD

**Issue by isPoto** [koreader/koreader#10955]
Please support the Xbox joystick Koreader by default, and provide a setting to specify the key functions

Almost all reading apps support xbox joystick operation, hopefully Koreader supports it by default!

**Comment by Frenzie** [comment]
This is missing some vital info like OS/device. ;-)

**Comment by Frenzie** [comment]
NB Vital info in https://github.com/koreader/koreader/issues/6544#issuecomment-1738592436

**Comment by pazos** [comment]
ok, my bad. Closing this one. Reopening the original. Sorry :p
