### ISSUE TITLE
FR: "Show all files" and "Show only supported files" when on cloud storage

### ISSUE THREAD

**Issue by amigaosz** [koreader/koreader#10964]
Hey,

please allow me to start by saying a quick but heartfelt thanks for the development of KOReader. I installed it today on my Kobo Elipsa 2E and I'm mostly excited about being able to adjust the contrast and margins of the PDFs I use on this e-reader to my liking. More importantly, English is not my first language and in the native Kobo software I can't translate in PDFs unfortunately, here I can and that's really great for me. Then I saw that with KOReader I can also access my WebDAV storage, which is also awesome.

Well, the only thing missing is support for CBR files:
https://github.com/koreader/koreader/issues/1517

But it sounds here like CBR support won't come, at least in the near future. However, I would have a suggestion that might satisfy at least some of the people (like me).

I don't know what the situation is on other e-readers, but the Kobo Elipsa 2E is relatively new and can open CBR files out of the box. My problem is that I don't have any native WebDAV access in the Elipsa 2E, only Google Drive and Dropbox and I don't use either. I have a lot of space somewhere else and access it via WebDAV. But KOReader can help here again. Unfortunately KOReader doesn't show me any CBR files when I'm accessing the cloud via WebDAV.

I am so close to the goal and yet so far.

Maybe there is a solution for this, only I didn't find it, but if not: would it be possible to integrate an option: "Show only supported files" and "Show all files"? That would already help me a lot if I could just download the files with KOReader.

**Comment by Frenzie** [comment]
Does it do anything there if in the file browser, top left icon (file browser icon) → settings → show unsupported files?

**Comment by amigaosz** [comment]
Oh hell, yes! :D Thank you so much! This was so easy and exactly what I was looking for.
