### ISSUE TITLE
FR: Open book from History without changing its History position

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#10962]
It's been a long time since I could think of any missing feature that I'd like to see implemented, although KOReader still adds more and more useful things with every new release.
So I had to try with a nitpick that probably none else ever needed and that I also don't have the slightest idea about its implementation.

Here is my testcase:
I use the `History` in KOReader as ... actual history (🤦‍♂️),  and I like it that I can see the order and dates of my past readings.
Now, the problem arises when I try to quickly check the e.g. rating that I gave to a specific book that I had read a year ago, or do any other check with it.
This book gets marked as the last read and now its reading date and position is updated and reading order is messed up.
Same thing when I open to check something from the first book of a series while I'm reading the 7th (OCD I know)..
Of course, many times I open a past book to continue the reading, so the current behavior is the logical thing to do.

So, I was wondering if there was a way to open a book without changing it's position in `History`.
Maybe another entry at a history item's long press dialog (I know that already has enough things there, but hey..)?

I don't except this anytime soon, just putting it here for consideration.. 😀

**Comment by Frenzie** [comment]
I think that might be technically challenging, but @hius07 probably knows the most about it without having to spend time looking at the code and/or experimenting.

**Comment by hius07** [comment]
(1) New button "Open preserving timestamp" shown on long-pressing on a book.
The button should be added to File browser, History, Collections and some other places (eg we can open a book from File search results). Besides, accidental tapping the book will update timestamp anyway.

(2) "Pin" a book in History.
Pinned book never updates its history timestamp on opening. Pinned book cannot be removed from History.
Pinning is done via a button in the long-press dialog in History, pinned book have marker/indicator in the history list.

Option (2) looks better I believe.

**Comment by noembryo** [comment]
Both are nice but since for my test case this is something I do on occasion, (1) looks much easier as opposed to (2) that needs permanently change something on almost every book manually (Very big history here.. ;o).
Also, (2) might complicate the delete/remove/clear actions..

**Comment by hugleo** [comment]
3) When marking a book as finished, associate a timestamp and sort all finished books by that date.

**Comment by noembryo** [comment]
> Maybe: do not change the timestamp in History for finished books ("finished" status to be a sort of pinning).
Good idea! 👍

**Comment by hius07** [comment]
@mergen3107, what do you think?

**Comment by poire-z** [comment]
> Maybe: do not change the timestamp in History for finished books ("finished" status to be a sort of pinning).

Good idea indeed.
It feels flexible (if one wants to move a reference book up in the History as he will access it often, he can mark as reading, open, mark as finished).
May be it could also prevent statistics from being accounted ? I usually don't mind (and rather wish the current behaviour to move the book I needed to re-open up in History), but often, I go in Calendar view to reset statistics for the day for such books I open quickly.
But I guess this should be an option/toggable feature, some people may be fine with the current behaviour.

**Comment by NiLuJe** [comment]
I don't rightly recall how it works for History itself, but it might also make sense to preserve the actual filesystem timestamps, with some lfs.stat & lfs.touch magic?

**Comment by poire-z** [comment]
I don't think we should bother about any timestamps of the sdr or the metadata.epub.lua: we open them, we write them with the update book location (so we can be at the latest page on re-opening), it's fine it is updated. Some people (not me) would just like it to not move up in History, it's just a history.lua thingy.

**Comment by hius07** [comment]
Both timestamps of the history item and of the file itself will be preserved, they are here together
https://github.com/koreader/koreader/blob/08555ad68be0efdceb0944e6588f2884653461b4/frontend/readhistory.lua#L255
"lastfile" will not be updated.
sdr will be updated as usual.

**Comment by mergen3107** [comment]
Yeah, I always found it weird that statistics keeps running for finished books. I agree with the agree to freeze timestamps and statistics for finished books. Not sure about new buttons for the other types of books (reading, on hold) just because I won’t use it myself.

**Comment by NiLuJe** [comment]
Freezing statistics might need a *different* knob, but it could sort of make sense (and should be fairly trivial to implement; basically kill the handlers on init if state == finished).

**Comment by Frenzie** [comment]
I think leaving statistics running for finished books makes a lot of sense. ;-) You're just tracking referencing things from that point.

**Comment by jonnyl2** [comment]
Perhaps each book could get a flag: `Record statistics` `on`/`off` regardless of reading status.
Newly opened books will have it set to `on` by default. 
Finished books could be automatically switched to `off` (unless a user-setting prevents this)
All books set to `Record statistics` `off` AND Status `Finished` will keep their position in the History.
