### ISSUE TITLE
FR: extend highlight time after dictionary is closed

### ISSUE THREAD

**Issue by sdothum** [koreader/koreader#10961]
i was wondering if there is a way to tweak the highlight time of the lookup word after the dictionary is closed.

The word looked up is often covered by the dictionary and occaisionally when the dictionary is closed, i loose track of its location on the page to resume reading. Extending its highlight time a smidgen would aid these senior eyes :)

i've been culling through the source code but haven't spotted the obvious place to modify or inject a line of code.

**Comment by poire-z** [comment]
It's done here:
https://github.com/koreader/koreader/blob/7d3456edc104940af1445e48194d3bb919ab7593/frontend/ui/widget/dictquicklookup.lua#L1150-L1157
You can probably copy the whole DictQuickLookup:onClose() in a [user-patch](https://github.com/koreader/koreader/wiki/User-patches) and have yours (with a larger value than this `0.5`) override this one.

**Comment by sdothum** [comment]
Thank YOU! And much thanks for pointing out the user-patch approach (i'm enjoying reading with KOReader immensely.. and poking under the hood :) A great piece of sw and community!

Tx again.
