### ISSUE TITLE
FR: Update of the installation guide on BQ devices

### ISSUE THREAD

**Issue by Piecho2** [koreader/koreader#10978]
**Does your feature request involve difficulty completing a task? Please describe.**
Understanding the attached instruction, improving it and posting.

**Describe the solution you'd like**
Update installation guide for BQ devices https://github.com/koreader/koreader/wiki/Installation-on-BQ-devices

**Describe alternatives you've considered**
Any help with installation of the FW is welcome.

**Additional context**
Looking for help with installation on BQ C 4. Officially servers are down, so there is not possible to flash develop firmware. However, I found a post about successful installation. I do not understand all the steps myself to be honest, but would be great if documentation could be updated with a better described new process. I am happy to help supporting photos or any other info from my device. 

Post I mentioned - https://www.mobileread.com/forums/showpost.php?p=4225738&postcount=36

Motivated user here. I freed a Cervantes 4 a few weeks ago.

Registering the device with the now defunct online service would just have created one of this flag files, depending on the model:
/mnt/private/hackers_ok
/mnt/private/hackers_e60q22_ok
Installing hackers firmware checks if the file exists.

1. Open the device by sliding a guitar pick around it. The screen sticks with some adhesive to the top half of the case. Be careful not to break your screen.
2. There are at least 3 groups of the four pads that look like serial ports. The boot console is the one at the top.
It uses TTL, so you'll need a level shifter. I used a BusPirate to connect.
3. Send ESC early at boot to enter the U-Boot console.
4. Add the kernel parameter 'init=/bin/bash' and boot. This will bypass most of the startup an go straight to a root shell.
5. Use sed to clear the root password from /etc/passwd (or /etc/shadow, I don't remember), reboot.
6. Login as root.
7. touch /mnt/private/hackers_ok /mnt/private/hackers_e60q22_ok
8. Clean the adhesive residue (not the strip, the other side) with alcohol, reassemble the device.
9. Now you can flash the hackers firmware as if your device was registered.

This instructions are from memory, so details like the pinout of the serial port, sed usage and how to set U-Boot environment variables are left as an excercise to the reader.
It might be possible to skip 5 and 6 and create the flag files from the recovery shell if /mnt/private is available or can be mounted from there. I did not try that.

It might be possible to get the flag files written without opening the device. The original firmware is pretty old, I would be surprised if there is no vulnerability in it that allows that.
~QuixoteDon

**Comment by pazos** [comment]
Hi, nope. It won't work that way. Not here. Instructions are what they are because there're no other instructions.

We would be more than happy to document the new instructions when they arrive :)
I'm going to reply in the mobileread thread you created, since it belongs there, not here.

Duplicate of #10878
