### ISSUE TITLE
Fast typing triggers umlaut

### ISSUE THREAD

**Issue by ja350exl** [koreader/koreader#10976]
* KOReader version: Koreader 2023.08
* Device: Kindle Paperwhite 2

Issue:
When fast typing on the built in English keyboard, umlauts are triggered

Steps to reproduce:
1. Open text editor
2. Using English keyboard, type fast

**Comment by mergen3107** [comment]
You are probably triggering the swipes. Long press, for example, U and see were these symbols you hit are. So if you swipe in that symbol’s direction from keyboard, it will trigger

**Comment by ja350exl** [comment]
Oh I see. Is there any way to disable this behaviour?

**Comment by ryanwwest** [comment]
This happens to me all the time when typing too.

**Comment by hius07** [comment]
Download the attached file, remove the txt extension and put it to the koreader/patches folder.
(based on https://github.com/koreader/koreader/pull/9104#issuecomment-1509160619)

[2-kbd-disable-swipe.lua.txt](https://github.com/koreader/koreader/files/13196139/2-kbd-disable-swipe.lua.txt)

**Comment by ja350exl** [comment]
Ok thanks a lot, the patch works 👍

**Comment by poire-z** [comment]
May be this could be made an option into our Keyboard submenu, where there is room?

**Comment by ryanwwest** [comment]
I'd appreciate that option.

**Comment by hius07** [comment]
Okay
