### ISSUE TITLE
Front-light delay when turned off

### ISSUE THREAD

**Issue by UserCel** [koreader/koreader#10970]
* KOReader version: 2023.08
* Device: Kobo Clara 2E
#### Issue
When turning off the front-light there is a noticeable delay of maybe 1 second or so, there is no delay when turning it on. This did not occur on older versions of koreader.
#### Steps to reproduce
Turn front-light on and off be it with a gesture, settings menu or putting the device to sleep.

**Comment by Frenzie** [comment]
My guess would be that's related to workarounds to prevent freezing on those devices. Pinging @NiLuJe

**Comment by Galunid** [comment]
> My guess would be that's related to workarounds to prevent freezing on those devices. Pinging @NiLuJe

This seems to happen on Kobo Clara **HD** too, but only when going/waking from sleep.

**Comment by Frenzie** [comment]
By those devices I mean everything listed as `hasReliableMxcWaitFor = no` in https://github.com/koreader/koreader/blob/5b5b4d9ebc970ee80d49adf66021d71af15b317c/frontend/device/kobo/device.lua (which doesn't include the Clara HD).

On my H2O it also takes about half a second or so after touching to turn off the light while it turns on faster, but I don't remember if it's always been that way.

**Comment by UserCel** [comment]
> By those devices I mean everything listed as `hasReliableMxcWaitFor = no` in https://github.com/koreader/koreader/blob/5b5b4d9ebc970ee80d49adf66021d71af15b317c/frontend/device/kobo/device.lua (which doesn't include the Clara HD).
> 
> On my H2O it also takes about half a second or so after touching to turn off the light while it turns on faster, but I don't remember if it's always been that way.

You can test it on the kobo os (reader/launcher?), there isn't a delay there for me at least.

**Comment by UserCel** [comment]
> @Galunid
> 
> > This seems to happen on Kobo Clara HD too, but only when going/waking from sleep.
> 
> I just realized that you may be referring to something slightly different. Going to sleep (less so waking from sleep) is a process that takes something like 10 seconds. I'd have to look up the exact amount. This is because on some devices unloading the wifi module and such can take quite a while, but if they're not unloaded then suspend will fail.
> 
> So in that case you're probably just seeing that turning off the light isn't the very first thing it does.
> 
> @UserCel
> 
> > You can test it on the kobo os (reader/launcher?), there isn't a delay there for me at least.
> 
> The delay on the H2O is the same for turning the light off, which takes longer than turning it on or switching between levels of brightness. But you may be referring to the delay I mean as no delay (i.e., some 300-500 ms).

Nope, I meant that there is a delay regardless. Turning the light off, or simply putting the device to sleep exhibit the same delay. It is very noticeable and does not happen on the base kobo os.
That said, it's not a huge issue I suppose.

**Comment by UserCel** [comment]
@Frenzie 
It's still happening on the latest nightly, but I think I figured out why.
I always use the front-light on 1% when it's dark, it was always enough for me. It looks like a fade-in/out effect was added to the front light. If the front-light is on a higher % then it turns on/off at the same speed with the fade-in/out effect.
When it's at 1% it feels like it plays out the fade-out effect but there's no more steps to go down, so it feels like a delay.

**Comment by Frenzie** [comment]
#10305?

**Comment by UserCel** [comment]
> #10305?

Probably this, but it was merged at .05 and I've only noticed the issue since .08.
It's an issue with the ramp, it should simply not ramp down if it's at 1%, or even 2% as it just looks glitchy.

**Comment by Frenzie** [comment]
Nah, it looks like a delay on my H2O too. My first reply actually misidentified me being at 2% or something as a 500 ms delay but it was simply ramping with no perceptible difference.

**Comment by NiLuJe** [comment]
I can't reproduce (on a Clara 2E), FWIW.

Going to sleep *will* introduce a bit of variance into the process, but a simple toggle should be effectively instantaneous... unless your device is currently in standby. DO you happen to have autostandby enabled? (It's opt-in, so you'd have to have enabled it manually).

**Comment by NiLuJe** [comment]
Oops, missed the 1% thing. Yeah, that... might do weird things ;p.

As for the H2O thing, that's another kettle of fish entirely: turning the lights *off* takes a variable amount of time, because ntx. So, the final step in the ramp (i.e., the one that actually turns it off) will appear to "stutter", as the kernel takes its sweet time to power it down. Nothing we can do about it, and it's reproducible in Nickel.

**Comment by NiLuJe** [comment]
> Oops, missed the 1% thing.

Yeah, can repro on both the Sage & Clara 2E, so it's indeed related to the aw99703 ramping workaround.

**Comment by Frenzie** [comment]
@NiLuJe It was acting strange either because I was running a build from a few weeks ago or because it had simply been running for a few weeks.
