### ISSUE TITLE
Rendering Issue: Unwanted Numbers on the Right Side of EPUB Pages in Chinese

### ISSUE THREAD

**Issue by 7enChan** [koreader/koreader#10977]
* KOReader version:v2023.08
* Device:Onyx boox Nova 3（Android）

Hello,
I've come across a rendering issue in KOReader while reading certain Chinese EPUB books. On the displayed pages, numbers are appearing on the right side. These numbers predominantly show up at the beginning of chapters and on pages containing images. Notably, they don't match the page numbers nor do they align with any content within the book. When opening the same book in other reading software, these numbers are absent.

![331696493483_ pic](https://github.com/koreader/koreader/assets/20963768/52c0e036-6fd7-4b3d-84d6-4d44f3cca3c4)

**Comment by poire-z** [comment]
See #6004.
Shown when the books have them (as such books were rare) - you can disable by unchecking "Refernce page numbers > Show in margins" for a book, long-press for always not showing them.
