### ISSUE TITLE
Serbo - Croatian, non-existent language that exist on Koreader

### ISSUE THREAD

**Issue by Dabareapapa** [koreader/koreader#10985]
The Serbo-Croatian language does not exist and has never existed, it was only a political construct that served in imperialistic and subjugate purposes which, when it was wanted to be presented, was created with some strange mixture of both languages. I'm looking for Croatian in the dictionary and I can't find it for a long time, neither under H nor under C. I found it by simple scrolling and it's an understatement to say that I'm surprised that one of the official languages of the EU has been put on this otherwise excellent reader like Koreader, either by mistake or with bad intentions, in the service of political agendas from some long ago past times, let's hope they are finished permanently. But anyway, when that "language" is used in the dictionary, we come to the discovery that it is only the Croatian language here about, not that strange mixture or perhaps even Serbian. So, it's just a matter of the Croatian language being wrongly misnamed and called Serbo-Croatian. Well, if you had at least called it Croatian-Serbian, since it's only about the Croatian language anyway, and not Serbian at all. Considering that this is an obvious mistake that certainly has no place in a reader of this high level, and also that it is an otherwise sensitive topic between the two nations and also two languages, I would like to ask you to correct this mistake, especially since it does not require an exhaustive review of the entire dictionary, but only a changing a name in the banner.
I understand that working with the dictionaries of the world is a gargantuan undertaking and that it is quite normal to sneak a mistake, but try to understand me, especially since I am thereby depriving you of possible future objections that will surely arise. Therefore, if it is an unintentional mistake, there is no objection from my side. And if it is a non-accidental mistake, I have only one thing to say: Tebra! Dobra...

**Comment by pazos** [comment]
Hi, welcome.

First of all. This is a repository of code. We're not going to discuss approximations to imperialistic subjugations here.

A quick look at the code in repo show this for the term "croatia": https://github.com/search?q=repo%3Akoreader%2Fkoreader%20croatia%20&type=code

Serbo-croatian is labeled as a macrolanguage there, as per ISO 639-3 spec. See https://iso639-3.sil.org/code/hbs

The dictionary you're talking about comes from Wikidictionary, see https://en.wiktionary.org/wiki/Category:Serbo-Croatian_language

As you can see Wikidictionary provides also the Bosnian, Serbian and Croatian dictionaries. We would gladly include them if somebody does the job, like @Vuizur did in https://github.com/koreader/koreader/pull/9767 to include wikidictionaries with over 1000 entries.

> Considering that this is an obvious mistake that certainly has no place in a reader of this high level, and also that it is an otherwise sensitive topic between the two nations and also two languages, I would like to ask you to correct this mistake, especially since it does not require an exhaustive review of the entire dictionary, but only a changing a name in the banner.

There's no mistake here. Either provide your own serbian, bosnian and croatian wikidictionaries to include in the project or raise your demand to the Wikimedia foundation. We just serve dictionaries that already exist.

**Comment by Frenzie** [comment]
As @pazos said, the reason that string exists is because such a dictionary was provided by <https://github.com/Vuizur/Wiktionary-Dictionaries>. The selection is somewhat haphazard based on a combination of what people find, contribute, and is available without violating copyright.

**Comment by Dabareapapa** [comment]
Never mind. Koreader sucks anyway, so I want be using it. But 'll have to excuse my self, don't have the time to translate, I lost all the spare time I had trying to figure out at least two functions on Koreader, but I'm affraid I figured out only half of this one function, but not so sure even about that one, all I know it's one way or another, first try is allways random but according to T/F of the first one by that I can figure out the second command. Phuu, even this explanation tired me
