### ISSUE TITLE
Display is not normal after landscape

### ISSUE THREAD

**Issue by isPoto** [koreader/koreader#10989]
* KOReader version: 2023.08
* Device: Moaan inkPad X with Android 8

#### Issue
Display ratio is not normal after landscape

#### Steps to reproduce
Open any document;
Selecting landscape;
The ratio is not normal after displaying in landscape, and it does not completely spread the screen;
Exit to the document browser;
Reopening the document;
The horizontal screen scaling returns to normal;

![image](https://github.com/koreader/koreader/assets/59009389/8d490461-57ae-4e4d-b389-2945f4d57ae8)

**Comment by hugleo** [comment]
Okays,

One more duplicate 😅 https://github.com/koreader/koreader/issues/10983

**Comment by Frenzie** [comment]
Closing in favor of that one.
