### ISSUE TITLE
can't sync book stats from quick menu (in file browser)

### ISSUE THREAD

**Issue by frozencircle** [koreader/koreader#10984]
* KOReader version: 2023-08.50
* Device: android

#### Issue
- can't sync book stats from quick menu (in file browser)
- no crash

![Screenshot_20231007-080147_KOReader.jpg](https://github.com/koreader/koreader/assets/50252443/8f692cd0-5d3e-4427-a516-8969eb580073)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hius07** [comment]
It is available from the Reader (opened book) only.
