### ISSUE TITLE
Bug: Renaming containing folder using in-app file manager breaks book availability via history

### ISSUE THREAD

**Issue by foundObjects** [koreader/koreader#10995]
* KOReader version: 2023.08-67
* Device: Android (any)

#### Issue

Renaming a folder containing previously read books makes any books in History from this folder behave as if they were deleted.

This seems like unintended behavior as moving a read book (via in app file manager) to a new folder will update the file path for the history item.

I've reproduced this behavior on a Boox Nova Air, Samsung tablet and OnePlus Phone (Android versions 10, 12 and 13)

#### Steps to reproduce

Open in-app file browser, rename a folder containing previously read books then open History. Any books from that folder will appear as deleted.

##### `crash.log` (if applicable)
n/a

**Comment by hius07** [comment]
Thank you, this doesn't depend on a device, it is coded in such a way.
I wouldn't call it a bug, maybe "the absent feature".
We update the History on renaming/moving a file, I agree that would be nice to do so for folders.

**Comment by mergen3107** [comment]
Yeah, I remember this was quite a journey to go through maybe a year ago. I had to open history.lua and Find-Replace old folder name with new one. 
I never renamed a folder again :D
