### ISSUE TITLE
FR: Allow standard file browser operations on file browser search results

### ISSUE THREAD

**Issue by foundObjects** [koreader/koreader#10991]
**Does your feature request involve difficulty completing a task? Please describe.**
File search seems like the ideal way to find all files by an author to move them to a new location, or find a specific book I'd like to add to favorites or mark read (or just delete) - but I can't do those things from the search results page so I have to go find files by hand and select or operate on them one at a time.

This enhancement would help me do things like move all titles by an author into a new folder or quickly find a previously-read book to move it to a different location (without breaking any file locations in read history) or change read status of a book I've forgotten to update without first opening it (and disturbing its place in my read history) or paging through many pages in history to locate it to make the same update.

**Describe the solution you'd like**
I would like to be able to change read status, open book info, add or remove from favorites or multi-select and move (or delete) multiple files directly from file browser search results.

Essentially I'd like search results to behave like the standard file browser rather than the existing pop up list that only allows tap to open.

**Describe alternatives you've considered**
I could do these tasks by manually hunting through 1000+ files by hand with the file browser, or I could manage files using an external file browser tool (which would break file locations in favorites and read history and might leave behind stray sidecar directories.)

**Additional context**
n/a

**Comment by hius07** [comment]
Some button can be added I think.
Currently, besides Open, there are Book info and Show folder.
