### ISSUE TITLE
Kobo: Unable to *read back* a previously set RTC alarm on a Touch C

### ISSUE THREAD

**Issue by formula-spectre** [koreader/koreader#10996]
**Does your feature request involve difficulty completing a task? Please describe.**
no, it does not 

**Describe the solution you'd like**
i would like to set the autoshutdown timer in hours, not days; on my standard kobo I have standby in 15 minutes, and poweroff in 2 hours, and I would like to replicate that with koreader

**Describe alternatives you've considered**
I.. haven't tried anything else, guilty as charged

**Additional context**
I don't think there is more needed? I have a kobo n905c

**Comment by NiLuJe** [comment]
c.f., https://www.mobileread.com/forums/showthread.php?t=356479

**Comment by NiLuJe** [comment]
If by "rebuild", you meant restart, then, yeah.

Can't do it from within KOReader's text editor, because the settings will be overwritten on exit.

That leaves USBMS, or whatever else you might want to do, as long as it's done while KOReader isn't running.

**Comment by formula-spectre** [comment]
a quick `udevil mount /dev/sdb` and `settings.reader.lua` later I did it, thank you very much! I have one more question: what's the difference between autostandby and autosuspend? I mean, the difference between suspend and standby, aren't they the same?

**Comment by NiLuJe** [comment]
Standby keeps the lights on and the input wakeup sources active; suspend actually goes into full suspend to ram.

You probably shouldn't be using standby on such an old device, it won't serve much purpose, and it hasn't been optimized for, so it's likely to suffer a large wakeup latency penalty.

**Comment by Frenzie** [comment]
Isn't the AutoStandby plugin disabled on anything other than PB?

**Comment by NiLuJe** [comment]
Yes, but AutoSuspend provides an opt-in standby timer elsewhere ;).

**Comment by formula-spectre** [comment]
UPDATE:
i tried to modify `settings.reader.lua`, but it appears that koreader hasn't picked up the changes,even though I've shut down and powered on the kobo many times. did I do wrong? I mounted via USBMS, edited the file (it was in .app iirc) and put 7200

**Comment by NiLuJe** [comment]
Check debug logs for `AutoSuspend:` stuff, and `grep autoshutdown_timeout_seconds /mnt/onboard/.adds/koreader/settings.reader.lua`

**Comment by formula-spectre** [comment]
> grep autoshutdown_timeout_seconds /mnt/onboard/.adds/koreader/settings.reader.lua
`7200`, which is two hours
as for logs, do I search for crash.log or something else?

**Comment by Frenzie** [comment]
Thanks @zwim that's what I was thinking of in https://www.mobileread.com/forums/showthread.php?t=356479 but I was missing a key component.

**Comment by formula-spectre** [comment]
@zwim I tried your method, still nothing, it does not power off.  
note: to me power off is seeing the screen either with inverted color (I noticed this behavior, but it might be that i'm using dark mode) with Powered off on the top right corner. which is not happening.  
which log should I check? where are they located?

**Comment by NiLuJe** [comment]
There's only one log, the slightly unfortunately named `crash.log` ;).

You'll need to enable verbose debug logging first, though (and restart KOReader).

c.f., the [issue template](https://github.com/koreader/koreader/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by NiLuJe** [comment]
Unrelated, but

> seeing the screen either with inverted color (I noticed this behavior, but it might be that i'm using dark mode) with Powered off on the top right corner. which is not happening.

sounds extremely unclear. Unless the Touch C has yet another wonky quirk, night mode is honored no matter what. Keep in mind we do "fix" images while in night mode so that they don't look like negatives, which is perfectly normal.

**Comment by formula-spectre** [comment]
attached to this is crash.log  
i made sure to have verbose logging on! 
[crash.log](https://github.com/koreader/koreader/files/12885449/crash.log)

**Comment by NiLuJe** [comment]
Okay, the RTC on your device is dead (or at the very least the "setting a wakeup alarm" bits), and you have a suspend timer lower than the shutdown timer, so it fails to wakeup during suspend to trigger shutdown ;).

Given that device, it's also possible that RTC alarms just never worked, period.

**Comment by formula-spectre** [comment]
@NiLuJe 
> Unrelated, but
> 
>    > seeing the screen either with inverted color (I noticed this behavior, but it might be that i'm using dark mode) with Powered off on the top right corner. which is not happening.
> 
> sounds extremely unclear. Unless the Touch C has yet another wonky quirk, night mode is honored no matter what. Keep in mind we do "fix" images while in night mode so that they don't look like negatives, which is perfectly normal.  

idk sometimes when I turned the kobo off with koreader the image of the book i'm reading has inverted color, idk why

**Comment by formula-spectre** [comment]
> Okay, the RTC on your device is dead (or at the very least its "setting a wakeup alarm" bits are), and you have a suspend timer lower than the shutdown timer, so it fails to wakeup during suspend to trigger shutdown ;).
> 
> Given that device, it's also possible that RTC alarms just never worked, period. You'd have to double-check with a sane Touch C to confirm. Which would involve going back in time, so, good luck ;o).

uhh is it bad? why the standard kobo interface autosuspend fine then?

**Comment by formula-spectre** [comment]
is there a way I can troubleshoot this further?

**Comment by NiLuJe** [comment]
If you can find a way to set an rtc alarm in a way that actually stick, sure.

**Comment by NiLuJe** [comment]
You can also enable developer mode in Nickel, with the power management related bits enabled in the dev menu logging knobs, then check the syslog.

As well as stracing Nickel to see if it does something funky with the rtc (or nothing at all).

**Comment by NiLuJe** [comment]
Checking `/proc/driver/rtc`, `cat /sys/class/rtc/rtc0/name` and `ntx_hwconfig -s /dev/mmcblk0 2>/dev/null` might be interesting, too.

(i.e., there might not be a sane rtc capable of alarms *at all* on those devices).

**Comment by NiLuJe** [comment]
Might also be similar to #7994, in which a drying battery makes *reading* the alarm wonky. As mentioned there, that's not something we're prepared to handle.

**Comment by formula-spectre** [comment]
I just timed the normal kobo suspend and poweroff method, and they work? so it's a problem with nickelmenu/plato/koreader/ANYTHING interacting with the RTC?

sorry but i'm a bit frustrated, don't take

**Comment by NiLuJe** [comment]
This ought to bypass the read check (and assumes nothing else actually sets an alarm, which should mostly hold true in current condition).

```diff
diff --git a/ffi/rtc.lua b/ffi/rtc.lua
index 7a0743a2..883783f7 100644
--- a/ffi/rtc.lua
+++ b/ffi/rtc.lua
@@ -279,7 +279,10 @@ function RTC:validateWakeupAlarmByProximity(task_alarm, proximity)
 
     -- Those are in UTC broken down time format (struct tm)
     local alarm_tm = self:getWakeupAlarm()
-    local alarm_sys_tm = self:getWakeupAlarmSys()
+    -- Battery is dying, assume nothing else ever sets an alarm.
+    --local alarm_sys_tm = self:getWakeupAlarmSys()
+    -- FIXME: try to figure that out heuristically, perhaps by checking if getWakeupAlarmSys returns somethign EPOCH-like?
+    local alarm_sys_tm = self:getWakeupAlarm()
 
     if not (alarm_tm and alarm_sys_tm) then return end
```

**Comment by NiLuJe** [comment]
This variant ought to do this heuristically (and I'd like to see logs of it, to see if I got it right).

```diff
diff --git a/ffi/rtc.lua b/ffi/rtc.lua
index 7a0743a2..c2afa949 100644
--- a/ffi/rtc.lua
+++ b/ffi/rtc.lua
@@ -22,6 +22,9 @@ require("ffi/rtc_h")
 
 -----------------------------------------------------------------
 
+-- Custom errors
+local RTC_BOGUS_ALARM_READ = "RTC reports bogus alarm on read"
+
 local RTC = {
     _wakeup_scheduled = false,  -- Flipped in @{setWakeupAlarm} and @{unsetWakeupAlarm}.
     _wakeup_scheduled_tm = nil, -- The tm struct of the last scheduled wakeup alarm.
@@ -209,6 +212,22 @@ function RTC:getWakeupAlarmSys()
         return nil, re, err
     end
 
+    -- Some aging batteries are (supposedly) causing reads to report a bogus value...
+    -- c.f., https://github.com/koreader/koreader/issues/7994 & https://github.com/koreader/koreader/issues/10996
+    local e = ffi.new("struct tm")
+    e.tm_sec = wake.time.tm_sec
+    e.tm_min = wake.time.tm_min
+    e.tm_hour = wake.time.tm_hour
+    e.tm_mday = wake.time.tm_mday
+    e.tm_mon = wake.time.tm_mon
+    e.tm_year = wake.time.tm_year
+    local alarm_time = C.mktime(e)
+    print("RTC:getWakeupAlarmSys:", alarm_time) -- FIXME: Debugging
+    if alarm_time <= 1 then
+        -- Epoch-like, sounds fishy...
+        return nil, alarm_time, RTC_BOGUS_ALARM_READ
+    end
+
     -- Seed a struct tm with the current time, because not every field will be set in wake
     local t = ffi.new("time_t[1]")
     t[0] = C.time(nil)
@@ -279,7 +298,14 @@ function RTC:validateWakeupAlarmByProximity(task_alarm, proximity)
 
     -- Those are in UTC broken down time format (struct tm)
     local alarm_tm = self:getWakeupAlarm()
-    local alarm_sys_tm = self:getWakeupAlarmSys()
+    local alarm_sys_tm, val, err = self:getWakeupAlarmSys()
+    if alarm_tm and not alarm_sys_tm and err == RTC_BOGUS_ALARM_READ then
+        -- NOTE: If we've previously set an alarm, but reading it back produced something completely bogus,
+        --       assume nothing actually overrode it, and there's still a chance it'll fire properly.
+        --       We've seen this behavior on aging NTX devices...
+        print("getWakeupAlarmSys: Read back a bogus value (" .. val .. "), assuming our previously set alarm will fire as expected anyway")
+        alarm_sys_tm = alarm_tm
+    end
 
     if not (alarm_tm and alarm_sys_tm) then return end
```

**Comment by formula-spectre** [comment]
> Checking `cat /proc/driver/rtc`, `cat /sys/class/rtc/rtc0/name` and `ntx_hwconfig -s /dev/mmcblk0 2>/dev/null` might be interesting, too.
> 
> (i.e., there might not be a sane rtc capable of alarms _at all_ on those devices).

[procrtc.log](https://github.com/koreader/koreader/files/12885968/procrtc.log)
[sysrtc.log](https://github.com/koreader/koreader/files/12885969/sysrtc.log)
[ntx_hwconf.log](https://github.com/koreader/koreader/files/12885970/ntx_hwconf.log)
i've attached the three commands' logs. do I apply the patch that you provided now or you want to inspect them before?

**Comment by NiLuJe** [comment]
I've just edited it, but you can go ahead and try it now ;).

**Comment by formula-spectre** [comment]
just patched; gonna restart my kobo and then use koreader, will report back if it still won't autopoweroff :+1:  thanks for the support and patience!

**Comment by NiLuJe** [comment]
And in case that didn't quite pan out, this is closer to the simplified version that'll probably end up in a PR:

```diff
diff --git a/ffi/rtc.lua b/ffi/rtc.lua
index 7a0743a2..843d94c3 100644
--- a/ffi/rtc.lua
+++ b/ffi/rtc.lua
@@ -23,6 +23,8 @@ require("ffi/rtc_h")
 -----------------------------------------------------------------
 
 local RTC = {
+    dev_rtc = "/dev/rtc0",
+    dodgy_rtc = true,
     _wakeup_scheduled = false,  -- Flipped in @{setWakeupAlarm} and @{unsetWakeupAlarm}.
     _wakeup_scheduled_tm = nil, -- The tm struct of the last scheduled wakeup alarm.
 }
@@ -58,13 +60,13 @@ function RTC:toggleAlarmInterrupt(enabled)
     enabled = (enabled ~= nil) and enabled or true
 
     local err
-    local rtc0 = C.open("/dev/rtc0", bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
-    if rtc0 == -1 then
+    local fd = C.open(self.dev_rtc, bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
+    if fd == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("toggleAlarmInterrupt open /dev/rtc0", rtc0, err)
-        return nil, rtc0, err
+        print("toggleAlarmInterrupt open " .. self.dev_rtc, fd, err)
+        return nil, fd, err
     end
-    local re = C.ioctl(rtc0, enabled and C.RTC_AIE_ON or C.RTC_AIE_OFF, 0)
+    local re = C.ioctl(fd, enabled and C.RTC_AIE_ON or C.RTC_AIE_OFF, 0)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
         if enabled then
@@ -74,10 +76,10 @@ function RTC:toggleAlarmInterrupt(enabled)
         end
         return nil, re, err
     end
-    re = C.close(rtc0)
+    re = C.close(fd)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("toggleAlarmInterrupt close /dev/rtc0", re, err)
+        print("toggleAlarmInterrupt close " .. self.dev_rtc, re, err)
         return nil, re, err
     end
 
@@ -118,22 +120,22 @@ function RTC:setWakeupAlarm(epoch, enabled)
     wake.enabled = enabled and 1 or 0
 
     local err
-    local rtc0 = C.open("/dev/rtc0", bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
-    if rtc0 == -1 then
+    local fd = C.open(self.dev_rtc, bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
+    if fd == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("setWakeupAlarm open /dev/rtc0", rtc0, err)
-        return nil, rtc0, err
+        print("setWakeupAlarm open " .. self.dev_rtc, fd, err)
+        return nil, fd, err
     end
-    local re = C.ioctl(rtc0, C.RTC_WKALM_SET, wake)
+    local re = C.ioctl(fd, C.RTC_WKALM_SET, wake)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
         print("setWakeupAlarm ioctl RTC_WKALM_SET", re, err)
         return nil, re, err
     end
-    re = C.close(rtc0)
+    re = C.close(fd)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("setWakeupAlarm close /dev/rtc0", re, err)
+        print("setWakeupAlarm close " .. self.dev_rtc, re, err)
         return nil, re, err
     end
 
@@ -190,22 +192,22 @@ function RTC:getWakeupAlarmSys()
     local wake = ffi.new("struct rtc_wkalrm")
 
     local err, re
-    local rtc0 = C.open("/dev/rtc0", bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
-    if rtc0 == -1 then
+    local fd = C.open(self.dev_rtc, bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
+    if fd == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("getWakeupAlarm open /dev/rtc0", rtc0, err)
-        return nil, rtc0, err
+        print("getWakeupAlarm open " .. self.dev_rtc, fd, err)
+        return nil, fd, err
     end
-    re = C.ioctl(rtc0, C.RTC_WKALM_RD, wake)
+    re = C.ioctl(fd, C.RTC_WKALM_RD, wake)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
         print("getWakeupAlarm ioctl RTC_WKALM_RD", re, err)
         return nil, re, err
     end
-    re = C.close(rtc0)
+    re = C.close(fd)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("getWakeupAlarm close /dev/rtc0", re, err)
+        print("getWakeupAlarm close " .. self.dev_rtc, re, err)
         return nil, re, err
     end
 
@@ -233,22 +235,22 @@ function RTC:readHardwareClock()
     local rtc = ffi.new("struct rtc_time")
 
     local err, re
-    local rtc0 = C.open("/dev/rtc0", bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
-    if rtc0 == -1 then
+    local fd = C.open(self.dev_rtc, bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
+    if fd == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("readHardwareClock open /dev/rtc0", rtc0, err)
-        return nil, rtc0, err
+        print("readHardwareClock open " .. self.dev_rtc, fd, err)
+        return nil, fd, err
     end
-    re = C.ioctl(rtc0, C.RTC_RD_TIME, rtc)
+    re = C.ioctl(fd, C.RTC_RD_TIME, rtc)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
         print("readHardwareClock ioctl RTC_RD_TIME", re, err)
         return nil, re, err
     end
-    re = C.close(rtc0)
+    re = C.close(fd)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("readHardwareClock close /dev/rtc0", re, err)
+        print("readHardwareClock close " .. self.dev_rtc, re, err)
         return nil, re, err
     end
 
@@ -302,6 +304,13 @@ function RTC:validateWakeupAlarmByProximity(task_alarm, proximity)
             "\ncurrent time is     " .. now .. os.date(" (%F %T %z)", now))
     end
 
+    -- On dodgy RTCs, some aging batteries are (supposedly) causing reads to report a bogus value...
+    -- c.f., https://github.com/koreader/koreader/issues/7994 & https://github.com/koreader/koreader/issues/10996
+    if self.dodgy_rtc and alarm_sys <= 1 then
+        print("Read back a bogus alarm value from a dodgy RTC, assuming our previously set alarm fired as expected anyway")
+        alarm_sys = alarm
+    end
+
     -- If our stored alarm and the system alarm don't match, we didn't set it.
     if alarm ~= alarm_sys then return end
 
@@ -342,25 +351,25 @@ Heavily inspired by busybox's hwclock applet.
 --]]
 function RTC:HCToSys()
     local ok, err, re
-    local rtc0 = C.open("/dev/rtc0", bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
-    if rtc0 == -1 then
+    local fd = C.open(self.dev_rtc, bor(C.O_RDONLY, C.O_NONBLOCK, C.O_CLOEXEC))
+    if fd == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("HCToSys open /dev/rtc0", rtc0, err)
-        return nil, rtc0, err
+        print("HCToSys open " .. self.dev_rtc, fd, err)
+        return nil, fd, err
     end
 
     -- Read the hardware clock
     local tm = ffi.new("struct tm") -- tm is a superset of rtc_time, so we're good.
-    re = C.ioctl(rtc0, C.RTC_RD_TIME, tm)
+    re = C.ioctl(fd, C.RTC_RD_TIME, tm)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
         print("HCToSys ioctl RTC_RD_TIME", re, err)
         return nil, re, err
     end
-    re = C.close(rtc0)
+    re = C.close(fd)
     if re == -1 then
         err = ffi.string(C.strerror(ffi.errno()))
-        print("HCToSys close /dev/rtc0", re, err)
+        print("HCToSys close ".. self.dev_rtc, re, err)
         return nil, re, err
     end
```

**Comment by formula-spectre** [comment]
UPDATE  
it did work, but as i said, color inverted:![PXL_20231013_054113178.MP.jpg](https://github.com/koreader/koreader/assets/61557475/52232e93-4e61-4afc-a87f-0027ce9f580f)


do i still apply the patch?

**Comment by formula-spectre** [comment]
UPDATE  
it did work, but as i said, color inverted:
![PXL_20231013_054234994.jpg](https://github.com/koreader/koreader/assets/61557475/e36bf064-4e35-43cd-903d-f2cf6b552791)


do i still apply the patch?

**Comment by NiLuJe** [comment]
> color inverted:

Is the book in question an ePub or a PDF?

> do i still apply the patch?

Which one?

If that was with https://github.com/koreader/koreader/issues/10996#issuecomment-1760152525, then, first, I'd like to see the logs from it; and, yes, do double-check that https://github.com/koreader/koreader/issues/10996#issuecomment-1760677434 still works.

**Comment by NiLuJe** [comment]
> > color inverted:
> 
> Is the book in question an ePub or a PDF?

Also, does this *always* happen? Does it happen when going to *suspend*? Does it happen if you trigger a shutdown manually (via the Exit menu)?

**Comment by formula-spectre** [comment]
> > color inverted:
> 
> Is the book in question an ePub or a PDF?
> 
epub
> > do i still apply the patch?
> 
> Which one?
> 
> If that was with [#10996 (comment)](https://github.com/koreader/koreader/issues/10996#issuecomment-1760152525), then, first, I'd like to see the logs from it; and, yes, do double-check that [#10996 (comment)](https://github.com/koreader/koreader/issues/10996#issuecomment-1760677434) still works.

before patching, I'm gonna share the crash.log (I hope it's the right one and not the old one, but it should be constantly dumping right? checked and it has today's date)
[crash.log](https://github.com/koreader/koreader/files/12896444/crash.log)

**Comment by formula-spectre** [comment]
> > > color inverted:
> > 
> > 
> > Is the book in question an ePub or a PDF?
> 
> Also, does this _always_ happen? Does it happen when going to _suspend_? Does it happen if you trigger a shutdown manually (via the Exit menu)?

it happens at seemingly random, both in sleep mode, power off mode, and sometimes even in "awake" mode; i'm gonna try to get out of a pattern of it and see if it's really random or it's triggered by something  
may the omnissiah help me

**Comment by formula-spectre** [comment]
> > > color inverted:
> > 
> > 
> > Is the book in question an ePub or a PDF?
> 
> Also, does this _always_ happen? Does it happen when going to _suspend_? Does it happen if you trigger a shutdown manually (via the Exit menu)?

here is a log when this happened; i just turned on the kobo from standby mode
[crash.log](https://github.com/koreader/koreader/files/12896865/crash.log)

**Comment by NiLuJe** [comment]
> it's the right one

Yup, that was the right one, and it confirms that the new approach ought to be more correct ;o).

> a pattern

That's enough of a pattern to tell me that it's a kernel issue ;). It vaguely rings a bell, so it must have been affecting a few other devices at some point.

There's nothing we can do about it, given its random and "not our bug" nature, but you *can* work it around by disabling HW inversion.

Here's a [user patch](https://gist.github.com/NiLuJe/4be737eb123cf1199590b626be131345) doing just that.

**Comment by formula-spectre** [comment]
so do I apply the patch suggested here? 
https://github.com/koreader/koreader/issues/10996#issuecomment-1760677434  
and the user patch for the inverted colors?

**Comment by NiLuJe** [comment]
Yup, (revert the previous one before, of course)

**Comment by formula-spectre** [comment]
I apply the user patch that you mention (I think, I plopped it in ~/.adds/koreader/patches), do I close this issue or further investigation or testing is needed?

**Comment by NiLuJe** [comment]
I'm just waiting on confirmation that the new rtc/suspend/shutdown patches work ;).

**Comment by formula-spectre** [comment]
uhh do you want the current log?

**Comment by NiLuJe** [comment]
That, too. But mainly an actual confirmation that it actually works? ;o).

**Comment by formula-spectre** [comment]
i'm an idiot, the actual patch works, the device does goes in autopoweroff after the set time. the color inversion one is acting.. funny, I permanently have everything negative now. anyway here's the log.
i'm gonna remove the user patch and live with the problem
[crash.log](https://github.com/koreader/koreader/files/12906705/crash.log)
(if you see a bunch of standby to wake to standby is when I realized the negative colors problem)

**Comment by NiLuJe** [comment]
Oh, you'll have to toggle nightmode off and on again for the userpatch not to screw things up, yeah.

**Comment by NiLuJe** [comment]
Actually, you might even need to drop the userpatch, restart KOReader, disable nightmode; apply the userpatch, restart; and *then* it'll behave.

**Comment by formula-spectre** [comment]
> Actually, you might even need to drop the userpatch, restart KOReader, disable nightmode; apply the userpatch, restart; and then it'll behave.
I roughly followed this procedure, but the user patch still screwed it up. I will try again with this exact procedure and report back though

**Comment by NiLuJe** [comment]
Works as expected this way on my end, FWIW ;).

**Comment by formula-spectre** [comment]
@NiLuJe confirmed, that patch makes the autopoweroff work fine, still testing the user patch for the color inversion thing

**Comment by NiLuJe** [comment]
I've just updated the userpatch to fix the breakage, which only happened starting KOReader with both the patch applied *and* nightmode enabled.

**Comment by formula-spectre** [comment]
UPDATE: The patch for the autopoweroff is working fine, but the user patch is not; just started my kobo to read, and after starting koreader i was greeted with negative covers, no matter night mode being on or off

**Comment by NiLuJe** [comment]
#worksforme with the fixed revision

**Comment by formula-spectre** [comment]
probably :/ i'll try to debug to debug some more. do I close the issue? since the main problem, the autopoweroff patch works for me

**Comment by NiLuJe** [comment]
It'll get closed automatically once the PR is merged ;).

**Comment by formula-spectre** [comment]
:+1: thanks for the support!
