### ISSUE TITLE
Crash at start on Android 14

### ISSUE THREAD

**Issue by bassmannate** [koreader/koreader#11009]
* KOReader version: 2023.08
* Device: pixel 8 pro

#### Issue
KOReader crashes at start up

#### Steps to reproduce
Start KOReader and grant permissions when prompted. Open KOReader again and it instantly gives a crash log.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
--------- beginning of main
10-14 09:59:00.732 W/Thread-13( 6669): type=1400 audit(0.0:31): avc:  granted  { execute } for  path="/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" dev="dm-56" ino=61605 scontext=u:r:untrusted_app_30:s0:c48,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c48,c257,c512,c768 tclass=file app=org.koreader.launcher.fdroid
10-14 09:59:00.692 V/Surface ( 6669): surface changed {
10-14 09:59:00.692 V/Surface ( 6669):   width:  1008
10-14 09:59:00.692 V/Surface ( 6669):   height: 2131
10-14 09:59:00.692 V/Surface ( 6669):  format: RGB_565
10-14 09:59:00.692 V/Surface ( 6669): }
10-14 09:59:00.692 V/NativeGlue( 6669): NativeWindowResized: 0xb40000799249a0d0 -- 0xb400007a324b5330
10-14 09:59:00.694 V/NativeGlue( 6669): ContentRectChanged: l=0,t=0,r=1008,b=2077
10-14 09:59:00.695 V/NativeGlue( 6669): NativeWindowRedrawNeeded: 0xb40000799249a0d0 -- 0xb400007a324b5330
10-14 09:59:00.698 V/NativeGlue( 6669): NativeWindowRedrawNeeded: 0xb40000799249a0d0 -- 0xb400007a324b5330
10-14 09:59:00.708 V/NativeGlue( 6669): WindowFocusChanged: 0xb40000799249a0d0 -- 1
10-14 09:59:00.709 V/NativeThread( 6669): Activity gained focus.
10-14 09:59:00.715 V/NativeThread( 6669): Launching LuaJIT assets
10-14 09:59:00.721 V/NativeGlue( 6669): ContentRectChanged: l=0,t=0,r=1008,b=2131
10-14 09:59:00.726 I/Assets  ( 6669): Skip installation for revision v2023.08
10-14 09:59:00.730 I/dlopen  ( 6669): dl.dlopen - libs/libkoreader-lfs.so => /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
10-14 09:59:00.730 V/dlopen  ( 6669):     dl.dlopen - needed => libluajit.so (1 of 2) <= /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
10-14 09:59:00.730 V/dlopen  ( 6669):     dl.dlopen - libluajit.so => /data/app/~~s5maF1uE4nHb1Ksf4ilXAA==/org.koreader.launcher.fdroid-2TrxH4geQsCx-33lPR_fjw==/lib/arm64/libluajit.so
10-14 09:59:00.730 V/dlopen  ( 6669):         dl.dlopen - needed => libm.so (1 of 3) <= /data/app/~~s5maF1uE4nHb1Ksf4ilXAA==/org.koreader.launcher.fdroid-2TrxH4geQsCx-33lPR_fjw==/lib/arm64/libluajit.so
10-14 09:59:00.733 W/dlopen  ( 6669): could not find library libm.so
10-14 09:59:00.733 E/KOReader( 6669): error: [string "dl.lua"]:164: could not find library libm.so
10-14 09:59:00.733 W/dlopen  ( 6669): could not find library /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
10-14 09:59:00.734 E/KOReader( 6669): error: [string "dl.lua"]:164: could not find library /data/user/0/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so
10-14 09:59:00.734 W/linker  ( 6669): Warning: "/data/data/org.koreader.launcher.fdroid/files/libs/libkoreader-lfs.so" unused DT entry: DT_RPATH (type 0xf arg 0x2a6) (ignoring)
10-14 09:59:00.737 W/dlopen  ( 6669): could not find library rt.so.1
10-14 09:59:00.754 I/dlopen  ( 6669): dl.dlopen - libs/libutf8proc.so.2 => /data/user/0/org.koreader.launcher.fdroid/files/libs/libutf8proc.so.2
10-14 09:59:00.754 V/dlopen  ( 6669):     dl.dlopen - needed => libc.so (1 of 1) <= /data/user/0/org.koreader.launcher.fdroid/files/libs/libutf8proc.so.2
10-14 09:59:00.755 W/dlopen  ( 6669): could not find library libc.so
10-14 09:59:00.755 E/NativeThread( 6669): Failed to run script: setupkoenv.lua:27: Not able to load dynamic library: libs/libutf8proc.so.2

```
</details>

**Comment by Frenzie** [comment]
Did you try the 64-bit version?

**Comment by bassmannate** [comment]
I tried what ever is in fdroid. It doesn't seem to differentiate and I didn't have a problem on Android 13. Let me poke around here on GitHub for the 64 bit.

**Comment by bassmannate** [comment]
Nope. Downloaded latest version and made sure it's 64 bit arm. Looks like a different crash report, though.
`--------- beginning of main
10-14 11:17:13.053 V/dlopen  ( 6679):     dl.dlopen - needed => libluajit.so (1 of 2) <= /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
10-14 11:17:13.053 V/dlopen  ( 6679):     dl.dlopen - libluajit.so => /data/app/~~FXI3DrM3liJ3uHFYtoEBmA==/org.koreader.launcher-ATyx9WXnrWvactrUKW04tQ==/lib/arm64/libluajit.so
10-14 11:17:13.054 V/dlopen  ( 6679):         dl.dlopen - needed => libm.so (1 of 3) <= /data/app/~~FXI3DrM3liJ3uHFYtoEBmA==/org.koreader.launcher-ATyx9WXnrWvactrUKW04tQ==/lib/arm64/libluajit.so
10-14 11:17:13.058 W/dlopen  ( 6679): could not find library libm.so
10-14 11:17:13.059 E/KOReader( 6679): error: [string "dl.lua"]:164: could not find library libm.so
10-14 11:17:13.059 W/dlopen  ( 6679): could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
10-14 11:17:13.059 E/KOReader( 6679): error: [string "dl.lua"]:164: could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
10-14 11:17:13.060 W/linker  ( 6679): Warning: "/data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so" unused DT entry: DT_RPATH (type 0xf arg 0x2a6) (ignoring)
10-14 11:17:13.063 W/dlopen  ( 6679): could not find library rt.so.1
10-14 11:17:13.091 I/dlopen  ( 6679): dl.dlopen - libs/libutf8proc.so.2 => /data/user/0/org.koreader.launcher/files/libs/libutf8proc.so.2
10-14 11:17:13.091 V/dlopen  ( 6679):     dl.dlopen - needed => libc.so (1 of 1) <= /data/user/0/org.koreader.launcher/files/libs/libutf8proc.so.2
10-14 11:17:13.092 W/dlopen  ( 6679): could not find library libc.so
10-14 11:17:13.092 E/NativeThread( 6679): Failed to run script: setupkoenv.lua:27: Not able to load dynamic library: libs/libutf8proc.so.2
`

**Comment by Frenzie** [comment]
Strange, but could you try the latest nightly? http://build.koreader.rocks/download/nightly/v2023.08-78-g6ccf19b99_2023-10-13/koreader-android-arm64-v2023.08-78-g6ccf19b99_2023-10-13.apk

**Comment by NiLuJe** [comment]
A nightly will probably work ;).

c.f., #10998

**Comment by bassmannate** [comment]
Nightly does it. Should be fixed in the next release, then. Thanks, guys!
