### ISSUE TITLE
RFC: UI for a package manager

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#11001]
Hi. I want to get some feedback about an UI for a future package manager.

I call it "package manager" instead of "plugin manager" because it could be used to handle other kind of packages such as fonts or css snnipets.

Just sketched a base UI and I need to know if this route is okay before commiting time improving it.

The entry point for the Package Manager is just a `ButtonDialogTittle` with some buttons.

![prev1](https://github.com/koreader/koreader/assets/975883/423af1ce-1535-4f3e-8ff5-99281303b3a7)

The top row is just about featured | installed | available **packages**.

After clicking of one of those buttons we get an array of packages that matches the filter and show a paginated ~~details~~ **list** view ~~with as many pages as packages on the array~~.

## Current design
![Peek 13-10-2023 12-22](https://github.com/koreader/koreader/assets/975883/95ce18eb-ceb4-4498-92dd-d413e6906af9)

## Previous sketches

<details>
<summary>show me</summary>

For instance, an array of 3 available packages:

## First page:
![prev2](https://github.com/koreader/koreader/assets/975883/9bfca297-ca12-4a6a-995a-da45cdba7820)

## Second page:
![prev3](https://github.com/koreader/koreader/assets/975883/be4107cd-48ef-4748-a717-b2c5930f409d)

</details>

~~As you can see it is something like a `KeyValuePage`, but the results of each package always fit into a single page, so the pagination is made based on the elements of the array.~~

I plan to add some support for long descriptions and buttons to enable/disable, install/uninstall, update etc.

So, my questions:

1. Does this usage of a paginated view makes sense to manage packages?. If not, which other widget do we have that fits better to this "model"?. I don't mind if I need to modify it a lot, just wondering what's available. Remember I'm mostly an UI noob :)

2. I would want to make it possible for packages to be self documented. As in: include an html string as part of their metadata, and when that field isn't nil just show a button with a callback that invokes a html widget. What do you think?

3. For installing local packages, made possible with https://github.com/koreader/koreader/pull/9615, clicking on a package would show the same details view as shown above but without the bottom page navigation menu. What do you think, is that ok or might be confusing?

**Comment by poire-z** [comment]
> As you can see it is something like a KeyValuePage, but the results of each package always fit into a single page, so the pagination is made based on the elements of the array.

Might be ok as long as we have 3 such "packages" :)
But once we get 15, it will suck to have to tap >> to iterate all of them and see what they are about.
Usually, UIs start with a list with short info, enough to see if interesting or curious enough to go tap an see more.
You could build your own items like CoverMenu, but it's some work & hacks - so at minima, you could go with Menu with just a title per row (or title + description, truncated).

Then, the user tap, and there he sees what you had in mind: a fullscreen widget with all the info about that package. It will have to be something custom for your purpose (like Book status that @NiLuJe mentionned), and there, your free to combine them in fancy ways. You'll want to use scrollhtmlwidget.lua (like DictQuickLookup) to display your HTML descriptions.

About the initial view with Featured|Available|Install, @hius07 has done that kind of thing with Bookmarks (bookmark, highghlight, notes) and History (reading/finished/on hold). Not much a user of all that to see if that can be reused.

**Comment by Frenzie** [comment]
I don't really have anything to add to the above. Some custom widget or a menu you can click to details seems like it would scale better. There's also the NetworkSetting widget.

2 and 3 sound good.

**Comment by pazos** [comment]
Thank you very much!

I'm glad I asked before spending time. Now I see how clumsy my proposal was :smile: 

So a list view it is. The details view ends as a callback for each element on the list. So I guess I can skip the paginated details view and just pass the selected package. Or shall I keep the details view with the entire array to prevent users from switching between list and details view?

**Comment by poire-z** [comment]
We also have something a little bit more fancy than our plain Menu: `Download dictionaries`, after selecting a language, which is just a KeyValuePage, with some indent, no-value items, and separato, and pagination for free.
https://github.com/koreader/koreader/blob/ee7a6455cea89c7b5be8463ef17f5320d264567d/frontend/apps/reader/modules/readerdictionary.lua#L1053-L1078

From there, a tap would just launch another fullscreen widget that would just cover the list / KeyValuePage widget. Swipe south to close, and you see that list again.

That is, if you want to get down quickly by reusing what we have and get our common unsuprising user experience.
(The only other quite different UI look we may have is the Vocabulary builder plugin, which looks a bit different from our other stuff.)

**Comment by Frenzie** [comment]
> We also have something a little bit more fancy than our plain Menu: Download dictionaries, after selecting a language, which is just a KeyValuePage, with some indent, no-value items, and separato, and pagination for free.

I'm still quite pleased with how that one turned out. ^_^

**Comment by pazos** [comment]
Thank you again.

I think I'm going to focus on a custom details view à la Book status.

For the list view a standard KV page is enough and scales well to hundred of packages. No problem if somebody wants to make it fancier on the future but for now I think it is enough.

I've updated the screenshot and description in OP. Feedback always welcome :)

**Comment by poire-z** [comment]
> I've updated the screenshot and description in OP.

Looks like you did not :)

**Comment by pazos** [comment]
> > I've updated the screenshot and description in OP.
> 
> Looks like you did not :)

LOL.

It wasn't a good idea to write a comment and update OP at the same time :p

Updated.

**Comment by poire-z** [comment]
(TBH, I would probably be more interested by your other "New: Awesome shit" project :))

**Comment by pazos** [comment]
> (TBH, I would probably be more interested by your other "New: Awesome shit" project :))

I'm afraid you won't.  It is a json endpoint that I use to pull highlights and notes from emacs.

I was playing with the idea of decoupling the UI and the web server logic. The UI can be made generic as a *pointless* task. That's it, a task that's pointless so it blocks on the foreground until you cancel it.

I *want to believe* there's some purpose for an endpoint in a pointless interface :smile:

**Comment by hugleo** [comment]
> Might be ok as long as we have 3 such "packages" :)

Maybe could this be used to install packages from here?
https://github.com/koreader/contrib
Already sum 7 projects.

**Comment by pazos** [comment]
Closing this one as I don't have time, won't plan to use the feature. I'll still ask here if I need it :)
