### ISSUE TITLE
FR: Gestures for folder views in File browser

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11007]
**Does your feature request involve difficulty completing a task? Please describe.**

Depending on the folder I'm browsing or the files I am looking for, I often switch between different display and sorting modes. E.g., file name sorted by size; file name sorted alphabetically; cover images sorted by last read; metadata sorted by percent completed; etc.

As these settings are only available in the menu, adjusting the sorting requires quite a few taps each time.

**Describe the solution you'd like**

Add the `Display mode>` (above the divider) and `Sort by>` menu trees, as well as the `Reverse sorting` and `Folders and files mixed` menu options to Dispatcher so they can be used to create profiles and QuickMenus with folder view presets.

**Comment by offset-torque** [comment]
+1 for this. An always visible simple **"Sort by..."** button would be an improvement. It might be next to the **PLUS** button in the corner and can provide one touch access to sorting options.

**Comment by jonnyl2** [comment]
Another idea would be the possibility to override the default folder view and sort settings by folder, and optionally for all its subfolders.

E.g.; an extra menu item `Override display settings for current folder` under which the user could choose a different display mode and sort order, with a checkbox `Apply to subfolders`.
