### ISSUE TITLE
In Reader screen, can't use gesture to access file search and folder shortcuts

### ISSUE THREAD

**Issue by frozencircle** [koreader/koreader#11005]
* KOReader version: 2023-08-78
* Device: android

#### Issue
In Reader screen, I can't use gesture to access file search and folder shortcuts anymore. I often use these to easily explore and open books, which are in several folders. If I have to go back to file browser first, it's an extra step.

#### Steps to reproduce
- no crash

**Comment by hius07** [comment]
You were able to call File search with a gesture only, right?
Please add to this gesture File browser as the first action.

**Comment by hius07** [comment]
Okay, does adding the first action help?

**Comment by hius07** [comment]
Open a book.
Go to Taps and gestures - Gesture manager - your gesture to call File search.
Go to General section.
Check "File browser".
Go up and switch to the page 2 of the menu.
Go to Sort and put File browser as the first action.
Close the menu.

Can you call File search with your gesture in Reader?

**Comment by jonnyl2** [comment]
I am also affected by this issue (on Kobo). I regularly used Folder shortcuts and File search via a QuickMenu from within the reader. If my required folder wasn't in the shortcuts list, or my file search didn't return what I was searching for, I could just exit out without having to reopen the last book.

**Comment by hius07** [comment]
Okay, I'll revert.
