### ISSUE TITLE
Cloud storage path with extra slash prevents downloading (webdav)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11025]
* KOReader version: 2023.08
* Device: Android 10, Kobo Clara HD 

#### Issue and Steps to reproduce
If I put "/Books/" in webdav path, it opens the folder alright, but fails when trying to download. 

If I put "/Books", downloads are successful.

##### `crash.log` (if applicable)
I am sure the problem is in that extra slash symbol. 

My suggestion is to either truncate that extra slash by the code, or add a little note of how the path should look like in that webdav settings window.

**Comment by hius07** [comment]
Where is the extra slash?

**Comment by mergen3107** [comment]
Sorry, I types too fast. In my first first example, I fixed the typo.

**Comment by hius07** [comment]
We have two hints (examples) without trailing slash already:
https://github.com/koreader/koreader/blob/f3520effd679eb24a352e7dec600c5b378c3d376/frontend/apps/cloudstorage/webdav.lua#L83
https://github.com/koreader/koreader/blob/f3520effd679eb24a352e7dec600c5b378c3d376/frontend/apps/cloudstorage/webdav.lua#L89
Add one more?
