### ISSUE TITLE
FR: Cloud Storage - Come back to cloud folder

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11024]
**Does your feature request involve difficulty completing a task? Please describe.**
I copied a few books to Yandex webdav, which still works great on KOReader.
I downloaded a book, it asked me if I wanted to open it. I said yes, skimmed the book, and then wanted to go back to other books on the cloud. So I went to FM, and it just brought me to my local books list.
**Describe the solution you'd like**
Can a feature be added that allows me to come back to that cloud folder?

**Describe alternatives you've considered**
I had to go to cloud storage from scratch and navigate to the same folder I used before. 

**Additional context**
I imagine simplest solution is replacing "Last item" in top menu with last cloud folder. Maybe optional (disabled by default), so people don't complain :D 
Another idea is making a dispatcher item, that can be triggered by a quick menu or gesture.

**Comment by pazos** [comment]
The cloudstorage code needs a rewrite. It can be extended without one but adding new features makes a future rewrite even less plausible :/
