### ISSUE TITLE
Some fonts are not working on Koreader

### ISSUE THREAD

**Issue by devKyanon** [koreader/koreader#11027]
* KOReader version: latest one
* Device: Onyx BOOX Palma, Leaf2, and Air C.

#### Issue

Some fonts are not working on Koreaer. 
For certain fonts, koreader will not recognize them (I have checked it on the popup message that I can see when pressing long a disable embedded font menu) and will output in the default font.

#### Steps to reproduce

-----------

Hello, I am a user who asked how to change a SPECIFIC font of a epub file before (https://github.com/koreader/koreader/issues/10969#issuecomment-1746580881).

Thanks to a quick and friendly response from the Koreader developers, I was able to play around with koreader and epub files (e.g., font face and font family).

And, with a bunch of tests and tries, I found that some font files are not working on Koreader. 
(I here attach the font file that doesn't work on Koreader; https://drive.google.com/file/d/1Bmw5Q-k3uKMl0ienGB_c_AWJ5KjmYFbm/view?usp=share_link)

The font works fine in other ebook apps, but only in Koreader does the font not output properly.

How can I solve this problem? 
This is a Korean font, do I need to set something else?

(This problem is the reason actually why I asked how to change a specific font)

**Comment by NiLuJe** [comment]
Logs would be helpful ;).

**Comment by devKyanon** [comment]
Hu,,,;; 

To get a clean log, I deleted a existing log file and opened an epub that didn't show the font correclty,
but suddenly the font is working correctly...😨

I don't know what happened... 

Anyway, I am going to close this issue and then I will ask about it in the future if I met this issue again. 

Thank you and sorry for bothering you!
