### ISSUE TITLE
FR: Add a multi-result search page

### ISSUE THREAD

**Issue by LTHPKBTE** [koreader/koreader#11038]
When I look for a specific person in a document, the current search control does not provide good guidance and quick jump functions. If the person is mentioned in many places in the article, it may take many jumps to find required paragraph.

If possible, Add a complete search page, showing multiple search results (and nearby partial paragraphs) at the same time to provide better jump and preview effects (Similar to Kindle’s in-book search) .

I'm using automatic translation, please forgive my grammatical and tone errors.

**Comment by ryanwwest** [comment]
I like this idea - maybe one line per result with a bit of surrounding context, and if you click one it takes you to the page with the current search navigation tool. Though I'm not sure how it would integrate with the existing search functions.

**Comment by dbhavasagar** [comment]
Great idea!
