### ISSUE TITLE
FR: Quicker 'add to folder shortcuts'

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11040]
**Does your feature request involve difficulty completing a task? Please describe.**

In my opinion, adding a new folder to the folder shortcuts takes too many steps for a feature that is probably relatively widely and often used.

1. Open folder shortcuts
2. Plus button
3. Long-press on folder
4. Select 'Choose'

**Describe the solution you'd like**

Replace the `Set as HOME folder` button in the long-press folder menu with `Add to folder shortcuts`. 

Rationale: Setting the Home folder is something users usually only do once and then never again, while preferences for favorite folders can change regularly, and adding a folder from the long-press menu would make this much more convenient. The Plus button in any folder still allows the setting of a new Home folder easily and quickly at any time.

**Describe alternatives you've considered**

Alternatively, add a 2nd button next to the `Set as HOME folder` or make the button dual-purpose (short tap add to favorite, long press HOME or vice-versa). 

(Or at the minimum, add the option to add the folder to the shortcuts from the Plus menu.)
__
As always, thank you for this outstanding software and continuous updates and support.

**Comment by jonnyl2** [comment]
> It's interesting that you change it frequently. ^_^

I add monthly folders for each new month and maintain some folders for non-fiction categories as well :)

> I might be more inclined to remove it from there completely

You're referring to the HOME folder option in the folder long-press menu, right? If so, I agree, I don't think it's needed there as it's not something that is used regularly.

>it's clear that an Add to folder shortcuts action would make sense.

In the Plus menu? Yes, that would make it a lot quicker and more convenient already, too.

**Comment by Frenzie** [comment]
> You're referring to the HOME folder option in the folder long-press menu, right? If so, I agree, I don't think it's needed there as it's not something that is used regularly.

Also it dates back nearly a decade. At the time the top left home button (long press to set current folder as home folder) wasn't available yet, nor was the plus menu.

> In the Plus menu?

Yes, but implicitly I meant that if such an action is added it should also be available in the gesture manager.

**Comment by jonnyl2** [comment]
Looks like this was added via #11108. Thank you @hius07.
