### ISSUE TITLE
FR: Page rotation as a gesture

### ISSUE THREAD

**Issue by SandroJk** [koreader/koreader#11043]
**Does your feature request involve difficulty completing a task? Please describe.**
I think it would be better if there was a gesture that allows for page rotation without going into menu while reading .cbz or .pdf

**Describe the solution you'd like**
It would be very nice to have a choice of rotation while assigning taps for corners, for example

**Describe alternatives you've considered**
Alternative is to just go to bottom menu and then click it from there, but if you have to switch from horizontal to vertical view often, it can become tiring and would work better if you just had one gesture. Not crucial addition by any means, but it would be nicer

**Additional context**
I apologize if this feature already exists, I have tried for a long time to find it in gesture manager but could not

**Comment by benoit-pierre** [comment]
Should be in the gesture manager "device" sub-menu.

**Comment by SandroJk** [comment]
Thank you so much! I can't believe I missed it like that :(
