### ISSUE TITLE
FR: Kindle Scribe support

### ISSUE THREAD

**Issue by reminon** [koreader/koreader#11045]
A Jailbreak released today that includes the scribe.

[https://www.mobileread.com/forums/showthread.php?t=356872](url)

Running koreader with kual ends with koreader crashing back to the home menu.
Willing to test anything if you guys need it.

**Comment by NiLuJe** [comment]
You can try the aforementioned PR, and double-check that input, lights & battery behave as expected.

Otherwise, poke at things over SSH to fix it ;).

**Comment by mergen3107** [comment]
I think you can looking for the crash.log file in the koreader folder. Please attach it here if you find it.

**Comment by NiLuJe** [comment]
Nope, that won't help (much) ;).

**Comment by reminon** [comment]
Marek modified the device.lua and added scribe settings based on the pw5 values and it surprisingly worked.

**Comment by NiLuJe** [comment]
That doesn't really help us test that the PR in question actually works, though ;).

**Comment by reminon** [comment]
your commits fixed this issue for me.
