### ISSUE TITLE
Windows 11 support?

### ISSUE THREAD

**Issue by Levantosa** [koreader/koreader#11042]

**Comment by benoit-pierre** [comment]
See #7653.

**Comment by hugleo** [comment]
An alternative should be Windows Subsystem for Android (WSA), but should be a more complex step to install apks not in amazon repository.

**Comment by Levantosa** [comment]
> An alternative should be Windows Subsystem for Android (WSA), but should be a more complex step to install apks not in amazon repository.
> 

does it adapts display size.

**Comment by Korb** [comment]
"Koreader on Windows" #920
