### ISSUE TITLE
Ko reader crashing on start on paper white 6.8 16gb.

### ISSUE THREAD

**Issue by dbhavasagar** [koreader/koreader#11048]
* KOReader version:Lavender
* Device: Kindle paper white 6.8 16gb

#### Issue
Crashing at startup.
#### Steps to reproduce
Launch via kual

Jail broken via New language break.

**Comment by mergen3107** [comment]
Please attach crash.log file from koreader folder here.

**Comment by dbhavasagar** [comment]
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 10/29/23-03:15:58
 [*] Version: v2023.08

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
ffi.load: sqlite3
10/29/23-03:15:59 INFO  initializing for device KindlePaperWhite5 
10/29/23-03:15:59 INFO  framebuffer resolution: {
  h = 1648,
  w = 1236
} --[[table: 0xb698de10]] 
./luajit: frontend/device/kindle/device.lua:1219: Error opening input device </dev/input/by-path/platform-1001e000.i2c-event>: No such file or directory
stack traceback:
	[C]: in function 'open'
	frontend/device/kindle/device.lua:1219: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x00013ead

**Comment by NiLuJe** [comment]
In case you're someone else than on Discord: is this a Signature Edition?

**Comment by NiLuJe** [comment]
Ought to be fixed by the linked PR ;).

**Comment by dbhavasagar** [comment]
No its not signature edition its Paper White 5 16GB  6.8 inch released in September 2022.

**Comment by dbhavasagar** [comment]
Also after failing to open KO reader kindle became visibly slow like scrolling library takes couple of seconds so I've reset kindle. No longer provide logs.
I'll wait for the changes to be merged as this is a new device.

**Comment by dbhavasagar** [comment]
You might find this useful?
log from mrpi kual unidentified device name
Running 'install.sh' for 'KUALBooklet ff4134d I' (Update_KUALBooklet_ff4134d_install.bin) @ Sun, 29 Oct 2023 03:14:17 +0000

system: I ota_script:install::installing booklet
system: I ota_script:install::registering booklet
**[FBInk] Unidentified Kindle device 2DK (0x9B3) [G002DK]!**
[mrinstaller.log](https://github.com/koreader/koreader/files/13197209/mrinstaller.log)

system: I ota_script:install::creating application
system: I ota_script:install::cleaning up
system: I ota_script:install::done

Success! :)
