### ISSUE TITLE
Pocketbook cannot update koreader

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#11055]
* KOReader version: 2023.08
* Device: Pocketbook Inkpad Color 2

#### Issue
Koreader detects a new version is available (2023.10), tries to download, but it says that "Koreader couldn't be updated." and asks to retry. If I choose retry, it says it downloads a full package, but this fails as well after a couple of minutes, then asks to delete temporary files.
Wi-Fi is on.

I activated verbose logging and you can see the full crash.log here (and also an abridged version containing only the logs from the download step)

[crash.log](https://github.com/koreader/koreader/files/13209814/crash.log)
[brief.log](https://github.com/koreader/koreader/files/13209815/brief.log)

**Comment by Frenzie** [comment]
How much free space is there? It's known that we'd really better check in advance.

**Comment by SilverGreen93** [comment]
PB is new, out of the box, with 10-20 books loaded. Around 20GB free :)

**Comment by Frenzie** [comment]
Ahh, segmentation faults. That looks nasty.

**Comment by SilverGreen93** [comment]
> Ahh, segmentation faults. That looks nasty.

I saw that, but can't really tell if they are related to the download/update process or they appear in other contexts.

**Comment by Frenzie** [comment]
On Kobo it all seems to be working fwiw.

**Comment by SilverGreen93** [comment]
> On Kobo it all seems to be working fwiw.

Tested myself on Kobo Forma as well. No problems.

**Comment by NiLuJe** [comment]
Quite likely InkvView + OpenSSL not playing nice (or Inkview + <insert random vendroed lib we share with InkView here>, basically).

re: #9442 (and other assorted PB SIGILL/SEGV issues)

**Comment by SilverGreen93** [comment]
I had an issue with 2024.01 update on Pocketbook PB743K3 (Color 3) as well. After clicking on the Install button from the message, the whole UI hangs and nothing can be done further except force closing koreader from task manager.
