### ISSUE TITLE
FR: Unified Search Selector

### ISSUE THREAD

**Issue by ryanwwest** [koreader/koreader#11054]
**Does your feature request involve difficulty completing a task? Please describe.**

There are currently at least 5 different search mechanisms:
1. Fulltext search (for the opened document's text)
2. Dictionary lookup
3. Wikipedia lookup
4. Menu search
5. File search
6. (Calibre metadata search - plugin only)

Some of these are available in the magnifying glass settings drawer when the Reader is opened, others in the same drawer when the File Browser is opened, and Menu search is separately available in the Hamburger icon -> Help. These are all useful individually but it's a bit tedious to navigate to each of them.

**Describe the solution you'd like**

It would be nice to have a single search action that displays all search types together. When I say 'together', I do not mean unifying any of the existing search algorithms or combining results. Instead, I mean something similar to Google's search sites for Web/Images/Maps/etc:

![image](https://github.com/koreader/koreader/assets/31378238/5e195705-4347-494f-b384-c3d199f65185)

As we know from modern Google Web/Images/Maps/etc., if you click on a particular search 'type' tab, the search query interface changes between regular Web, Maps, and Shopping, as each search type has specific requirements. But it's easy to get to any of those search programs. Similarly, with KOReader I could imagine a UI that pops up that displays each of the 5+ search types above as icons, and when one is selected, displays the (unmodified) search query interface associated with that particular search interface (similar to the top settings drawer icons that display specifc settings when one icon is touched). The search mode tabs do not go away when you click a search icon, so you can easily switch around.

Once a user opens Unified Search, the first-time default in File Browser would be File search and in Reader would be Fulltext search, but the UI would remember the last-used search mode and display the same mode upon next opening (and if users know they want a specific search, all existing search actions still exist to open that mode of search either with or without tabs). Both search query UI/parameters and results display would be unchanged.

**Describe alternatives you've considered**

Keep using searches all separately. But I think this would help users find more search options earlier, especially hard-to-locate ones like Menu Search (which in my opinion should be one of the first ones they become aware of). I'd love to hear other perspectives.

By the way, release 2023.10 is awesome! Thanks for all the work in preparing it.

**Comment by poire-z** [comment]
My perspective:
With Google, one actually goes to Google to search something - so why not quick buttons to quickly switch the kind of something.
With KOReader, we're already in some context: the book your are reading - and one usually knows what he looks for where, either some character or word/notion he remember or expect seeing in the book - or something to go lookup in Dict/Wikipedia (not unified, but first dict as its quick - the go to Wikipedia if needed and the need to go online).
I don't think File search has a place there - and Menu search is nothing related to the document you're reading (so I really don't want to see it in my UI - I did advocate for it to go hide under Help> :/ it may be useful when you're a bit lost, but soon one should not being using it very often.)

**Comment by offset-torque** [comment]
> **ryanwwest** - I think this would help users find more search options earlier, especially hard-to-locate ones like Menu Search (which in my opinion should be one of the first ones they become aware of).

I totally agree with this. **Menu Search** is a useful function especially for the new users and it is totally hidden. When writing about it for the guide, it took me a while to find it even though I knew it exists. And it came up in the last place I expected. There is no way a user expects to find it there. This zero discoverability prevents the usage of the feature of course.

Another benefit of this **Unified Search** would be that users can access all the searches by assigning a single gesture for it instead of setting up several gestures for each of the file/text/dictionary/wikipedia/bookmark/menu/metadata searches.

So +1 for this proposal from me.

---

Also this is slightly related to the search usability so I am writing it here:

**Why "Fulltext search" ?**

I came across this term for the first time in KOReader and web search tells me this is something related to SQL databases. None of the programs I have ever used for reading/writing (PDF readers, IDEs, text editors, office suites...) refers to this function with this name. It is either **Find** or **Search**. 

Why KOReader chose this obscure term going against the user habits. What is wrong with **Find in document** which is much more clear and something users expect to see based on their experiences with other software.

**Comment by ryanwwest** [comment]
I share a similar opinion about discovering (and continuing to navigate to) the menu search as I still use it heavily after using KOReader for over a year. The menu is complex enough that its search stays convenient (almost reminds me a bit of ctrl-shift-p in VSCode or ctrl-p in Obsidian—and now I'm thinking about subsequent FRs lol). The single gesture map to Unified Search is something I would also use. 

I understand @poire-z's point that file and menu search differ from the other searches and aren't related to the specific document. That doesn't really bother me as my brain first thinks about the function (search) and then _what_ I want to search, but that's just me. Of course the fulltext search (which I have no problem renaming, was a bit strange to me at first but now I'm used to it) has no meaning in File Browser, and the file search, while maybe possible within a document (i.e. opens File Browser to that search), probably isn't needed within a document. So you could have one of the search type 'icons' toggle between fulltext/file depending on which 'app' is currently open.

**Comment by hius07** [comment]
Maybe just a profile?

![1](https://github.com/koreader/koreader/assets/62179190/d8f84031-c8a5-499e-bd71-990fdfb093e0)

**Comment by offset-torque** [comment]
> Maybe just a profile?

I think this is a nice workaround **hius07** if we can include this by default and assign a default gesture. So I can just tell the users to **"Double tap right bottom corner (or smt like that) to open the Unified Search dialog"**. They won't even need to memorize where each search item is in the menu system. And it is lower effort than designing a whole new search interface and changing the menu structure. I liked this idea.

**Comment by ryanwwest** [comment]
I recreated this profile and mapped it to lower-right corner single tap, and it works well, good idea. This always requires a second click to select which search you want (vs. have the last-used search type icon opened to the UI) but maybe that's okay. Some sort of default for users (like a pre-configured profile, for example) would be nice I agree. Has there ever been discussions about default hot corners?

**Comment by ryanwwest** [comment]
Another search type I just discovered and added is Bookmark serach

**Comment by hius07** [comment]
> Has there ever been discussions about default hot corners?

They are here
https://github.com/koreader/koreader/blob/master/plugins/gestures.koplugin/defaults.lua

**Comment by Frenzie** [comment]
> Has there ever been discussions about default hot corners?

What are you actually trying to ask? Because they exist and they have defaults…? ;-P

**Comment by Frenzie** [comment]
> I totally agree with this. Menu Search is a useful function especially for the new users and it is totally hidden. When writing about it for the guide, it took me a while to find it even though I knew it exists. And it came up in the last place I expected. There is no way a user expects to find it there. This zero discoverability prevents the usage of the feature of course.

Disagree on that one. It's in Help which not only makes sense in and of itself, but it's also the same in every other app for the same reason. For example, Kate has `Help` → `Find Action` and VS Code has `Help` → `Show All Commands`.

> Why "Fulltext search" ?
>
> I came across this term for the first time in KOReader and web search tells me this is something related to SQL databases. None of the programs I have ever used for reading/writing (PDF readers, IDEs, text editors, office suites...) refers to this function with this name. It is either Find or Search.
> 
> Why KOReader chose this obscure term going against the user habits. What is wrong with Find in document which is much more clear and something users expect to see based on their experiences with other software.

I think you may be ascribing too much intent to something someone added a decade ago.

As to why I never changed it ­in the past half decade or so — just `search` isn't very clear and `search/find in text/document` is still awkward and wouldn't fit well without changing the entire context, and as such it's still pending inspiration.

It might also be worth pointing out the string tends to localize fairly well, e.g. Dutch `Volledige tekst doorzoeken` and French `Recherche en texte intégral`.

**Comment by ryanwwest** [comment]
@hius07 @Frenzie Thanks for confirming that defaults exist, I wasn't sure. I guess the next question is could a default profile like this be considered? Or more generally for helping users, any type of default profile assigned to a default hot-corner, that lets users see what they are more easily to get ideas (as long as it has a good use). It sounds like the location of menu search is very debatable with multiple users preferring it in Help vs with the other searches, so maybe a default tap corner with menu search and other searches discoverable in another way could alleviate the biggest gripes (hard by many to initially discover and several 'taps' to reach).

@jonnyl2 I only really understand the second approach in your FR (recent actions dropdown) but I like it. _Where_ to display that I'm not sure but something like a command selector would be very handy and I think could fully cover the role of the current menu search. Other app command selector UIs fuzzy autosearch the possible commands as you type each letter (no enter required - rather enter selects the first list result) but display the history in the results below before you begin typing (can press enter immediately to rerun the last run command)—this may or may not be too intensive for KOReader devices (and could be by default disabled). There might also be an issue that some KOReader actions have the same name ('Bookmarks' appears twice in current menu search first results page).

**Comment by ryanwwest** [comment]
Autosearching each command when a new letter is entered might not be too intensive since the number of commands isn't monumentally high, but you could also somehow cache the resulting command subset for typing each of the first 26 letters typed to further diminish the remaining command subset needed to search thereafter.

**Comment by jonnyl2** [comment]
>I only really understand the second approach in your FR (recent actions dropdown) but I like it. Where to display that I'm not sure

@ryanwwest Admittedly this wasn't the most careful put-together mock-up, but I meant to show it as an extension of the search dialog, so not really a drop-down at all, but a larger search window that has the recently accessed menu locations listed in the bottom half:

<img width="541" alt="255519445-e0146723-1046-44da-939c-f6263af5806e" src="https://github.com/koreader/koreader/assets/95502269/85168508-4f4c-4842-a088-fb00c9955857">

This would also take care of menu options with the same name, as the whole path would be displayed.

I also like your idea with the fuzzy search results, which could be listed in the same area instead. However, the advantage of the recent selections would be that no keyboard input is required at all once a few frequently accessed menu options are listed (and presumably those won't be many, as relatively few options cannot be accessed via gestures directly).

**Comment by ryanwwest** [comment]
Yes, I understand—drop-down was a poor choice of words. With the fuzzy action search I described, the recent selections are displayed in order before any keyboard input is entered so the keyboard isn't required. For example, see Obsidian's command selector:

![image](https://github.com/koreader/koreader/assets/31378238/a3c5ce3c-5c58-4c17-b086-abbc4051a208)

In the pic, no letters/keys have been entered yet. The few results nevertheless listed could be the last 5 commands used and require just a tap (or on keyboard, enter and down arrow to navigate to lower recent actions). As soon as you do type a letter into the search box, however, the recent actions get replaced with menu search results (and could possibly have some sort of ranker that takes into account recent usage in search results). Displaying the complete settings navigation path would disambiguate same-named actions (and help for navigation) though I wonder if it makes it harder to read the most relevant part of the search result—the action name—since they aren't horizontally justified. What about this format: `Manage dictionaries ([Magnifying glass icon] > Settings > Dictionary settings)`?

**Comment by jonnyl2** [comment]
Gotcha, I like this a lot! If that'd be feasible and cheap, I think that would be a superb enhancement to the menu search.

**Comment by hius07** [comment]
> we can include this by default and assign a default gesture. So I can just tell the users to **"Double tap right bottom corner (or smt like that) to open the Unified Search dialog"**.

How about "long-press on bottom right corner" both in FM and Reader?
Double-tap is disabled by default.

**Comment by poire-z** [comment]
long-press on corner may not be welcome in the Reader (looks like there are no action assigned by default) as it may prevent long-press on words near the corners to dict lookup (it has precedence I think - but if it has not, it's useless as it will work only on blank pages, or when big margins).

(I'd still rather not include "developper-made user-profiles" ala "we know what's best for you". I thought the same about gestures, and I don't like/understand our default ones choice :) #4659 I wonder how many people did feel the same and went reset their gesture on first installation.)

**Comment by offset-torque** [comment]
> hius07 - How about "long-press on bottom right corner" both in FM and Reader?

Surely. I wrote that as an example. Any available gesture should be ok.

> hius07 - Also please note that even if we supply the Unified Search profile...

That's interesting. So existing installations can't get this with an update. Is there a way they can add this to an existing installation ?

> poire-z - I'd still rather not include "developper-made user-profiles" ala "we know what's best for you"

I see this more like the **presets** in video encoders. Surely as an advanced user I can tweak 50 parameters for the best encoding performance/quality but for most of the users a "4K - Fast" profile is good enough. Now they can encode a video even if they have zero knowledge about the codecs.

In our case, to make this search menu, users have to first learn about **profiles**, then about **quick menu**. Only then they will be able to re-create this. With this "profile-shipping" approach, users can just learn a gesture and start using it in seconds. And advanced users can just ignore this or create their own menu inspired by this.

**Comment by mergen3107** [comment]
I just treated these gestures as an example and remapped everything :D 
Yes, I confirm poire-z point, I removed all long-taps because they prevent me from selecting words in specific areas.

**Comment by ryanwwest** [comment]
I feel like a default profile as an example, especially a possibly useful one to a lot of people, would be better to have. I'm a developer but didn't realize what profiles were until I asked about a very specific use case and eventually I think @hius07 told me about them. Having even one and using it might help others, even less technically inclined users, to discover them earlier. Maybe one will decide to add another action to the search list, then realize they can delete the one they don't use, then make their own new profile...

The idea of presets is fine with me, though I'm not sure how that manifest differently than a few default profiles (that may not necessarily have default gestures assigned).

**Comment by Frenzie** [comment]
I think the problem with default profiles is more technical in nature. When to remove/update/etc. It's already a bit of a headache for something as simple as OPDS (i.e., basically just a URL).

**Comment by ryanwwest** [comment]
I was thinking could just have a single or double bottom right tap default to this profile on new installs with the updated version, not doing any sort of migration for existing apps. As for adding the actual profile (not the gesture), the same could be done for simplicity - though in that case adding the profile is less intrusive as it doesn't change anything for existing users except a new profile is available to use. I guess this fits the idea of 'presets' a bit more since a some other program with a new version could add new presets in a similar way that users just don't use if they don't want.

**Comment by ryanwwest** [comment]
Well, I'm going to close this issue as the original FR was given a pretty good solution via creating a profile 'menu' and assigning it a gesture. There's still the question of whether a default profile assigned to a default gesture could be beneficial to educating new users, but that doesn't need to leave this issue open. There was also some discussion about having a command selector, somewhat similar to but more usable than the menu search including recent action history that's also being somewhat tracked [here](https://github.com/koreader/koreader/issues/10686#issuecomment-1647382453).
