### ISSUE TITLE
Can't enable automatic progress sync on amd64

### ISSUE THREAD

**Issue by everdred** [koreader/koreader#11059]
* KOReader version: 2023.10
* Device: amd64

#### Issue
The setting "Automatically keep documents in sync" has become disabled (I don't think I did it), and trying to re-enable it produces the error `You have to switch the 'Action when Wi-Fi is off' Networks setting to 'turn on' to be able to enable this feature!` The network setting doesn't exist on  the amd64 version, and setting `["auto_sync"] = true,` also fails to re-enable auto progress sync.

**Comment by Frenzie** [comment]
That sounds like a regression. Maybe @NiLuJe remembers the changes he did? xD

**Comment by NiLuJe** [comment]
Are you perhaps using an imported config file from another platform?

**Comment by everdred** [comment]
> Are you perhaps using an imported config file from another platform?

I see you already discovered the cause of the issue, but in case it helps to know: nope, and it also reproduces on a fresh config.
