### ISSUE TITLE
koread can not run in Kindle pw3 5.15.1 jb

### ISSUE THREAD

**Issue by skypebj** [koreader/koreader#11065]
* KOReader version:2023.10.31
* Device:pw3 5.15.1

#### Issue
jailbreaked!

#### Steps to reproduce

---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/02/23-01:36:10
 [*] Version: v2023.10-1-gb70f86665_2023-10-31

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
./luajit: ./ffi/framebuffer_linux.lua:55: cannot open framebuffer
stack traceback:
	[C]: in function 'assert'
	./ffi/framebuffer_linux.lua:55: in function 'init'
	./ffi/framebuffer_mxcfb.lua:803: in function 'init'
	./ffi/framebuffer.lua:138: in function 'new'
	frontend/device/kindle/device.lua:839: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x00013ebd

**Comment by NiLuJe** [comment]
Your JB is incomplete.
