### ISSUE TITLE
FR: Shortcut to disable touch

### ISSUE THREAD

**Issue by hojabri** [koreader/koreader#11061]
Hi,
Sometimes I would like to lock the screen touch, so no random touches or taps will do unwanted actions during reading.
Can we define a feature so we can lock the screen by some shortcuts, and can be unlocked by a certain gesture or number of taps? It can be unlocked by either a very long tap and vice versa.

**Comment by NiLuJe** [comment]
That's already available in the Gesture manager.

**Comment by hojabri** [comment]
Thank you, found it!
