### ISSUE TITLE
Linux Desktop: Cannot enable "Automatically keep documents in sync" in 2023.10

### ISSUE THREAD

**Issue by zephyros-dev** [koreader/koreader#11075]
* KOReader version: 2023.10
* Device: Linux

#### Issue
The "Automatically keep documents in sync" settings can only be enabled after turning on "Action when Wi-Fi is off" on Linux desktop. This toggle works without needing to change "Action when Wi-Fi is off" on 2023.08 however.

**Comment by Frenzie** [comment]
Duplicate of #11059. The nightly from a few hours ago includes the fix. Please report back if it works. ^_^

**Comment by Frenzie** [comment]
PS See #11068 but you can probably also check for updates on the development channel.
