### ISSUE TITLE
KOReader crash when attempting to rename/delete a profile and removing style tweak from action list

### ISSUE THREAD

**Issue by agk29** [koreader/koreader#11071]
* KOReader version: 2023.10
* Device: Kobo Libra 2

#### Issue
KOReader is crashing when either trying to rename or delete an existing profile, or removing a style tweak from the action list. Not sure if this bug was present in the last stable build - I don't think I did any of the steps before updating to 2023.10 so I can't be sure.

#### Steps to reproduce
Any of the 3 steps:
- Style tweaks -> For any style tweak that is shown in action list: press button "Don't show in action list". Does **not** crash when pressing button "Add to action list", only when trying to remove from action list.
- Profiles -> Select a profile -> Delete
- Profiles -> Select a profile -> Rename -> Save

##### `crash.log` (if applicable)
<details>
  <summary>crash.log</summary>

```
11/03/23-14:54:50 INFO  Inhibiting user input 
11/03/23-14:54:51 INFO  Restoring user input handling 
./luajit: plugins/profiles.koplugin/main.lua:377: attempt to index local 'gesture' (a boolean value)
stack traceback:
	plugins/profiles.koplugin/main.lua:377: in function 'updateGestures'
	frontend/apps/reader/modules/readerstyletweak.lua:571: in function 'toggle_tweak_in_dispatcher_callback'
	frontend/apps/reader/modules/readerstyletweak.lua:131: in function 'callback'
	frontend/ui/widget/buttontable.lua:80: in function 'callback'
	frontend/ui/widget/button.lua:454: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:261: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:889: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1418: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1516: in function 'handleInput'
	frontend/ui/uimanager.lua:1560: in function 'run'
	./reader.lua:289: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 11/03/23 @ 14:55:01)
Running FW 4.38.21908 on Linux 4.1.15-00866-g3a75628c73c (#96 SMP PREEMPT Thu Nov 17 14:25:47 CST 2022)
Attempting to restart KOReader . . .
!!!!
```
</details>

Crash log is the exact same for each scenario

**Comment by xversion1** [comment]
I have Koreader crashed as well every time I adjust fonts or styles on Galaxy Tab S9 FE, both the old version (202308) and the newest (202310) have this issue. It works fine on my phone and other devices so I think this error is particularly caused by Tab S9 FE.

**Comment by hius07** [comment]
@xversion1, your issue is not related, you may want to open a new ticket.

**Comment by xversion1** [comment]
> @xversion1, your issue is not related, you may want to open a new ticket.
Did you open it already, the above #11072?

**Comment by hius07** [comment]
> Did you open it already, the above #11072?

No

**Comment by xversion1** [comment]
> @xversion1, your issue is not related, you may want to open a new ticket.

Done it.
