### ISSUE TITLE
FR: Possible to customize the behaviour and position of the long-press, pop-up menu?

### ISSUE THREAD

**Issue by AdamSitar** [koreader/koreader#11081]
Talking about this menu:
![image](https://github.com/koreader/koreader/assets/68128060/94573064-36bf-4217-b649-5b69f6defdcd)

**Does your feature request involve difficulty completing a task? Please describe.**
I think this behavior for the popup menu could be more ergonomic, most people hold the e-reader in a portrait mode, so the menu appearing at the bottom of the screen would be easier and more comfortable to access - especially for when the reader is used for language learning purposes

**Describe the solution you'd like**
The popup menu already is draggable -  I wish it would remember the location (or the location could be set somewhere in the menu or a lua config file, aka top | center | bottom), so it's not always displayed in the center of the screen

**Describe alternatives you've considered**
I just use the menu as it is, or always quickly drag it down where it is more reachable 

**Additional context**
If the customization is possible through a lua file somewhere already, that would be awesome

Thank you!

**Comment by ryanwwest** [comment]
I share the interest in remembering the position of this and other dialogs. I have a 13 inch ereader and sometimes it would be nice for this and other dialogs to open closer to the bottom of the screen. Not sure how to design a good implementation though.

**Comment by jonnyl2** [comment]
Possibly this pop-up menu could (optionally?) be made to open anchored to where the finger was lifted for a selection?
C.f. #10631 (FR: Open QuickMenu pop-ups at location of gesture).

I usually do selections/highlights with my index finger rather than my thumb, so the pop-up location hasn't been bothering me too much (much easier to reach with the index finger). However, now that I think about it, I think I would also prefer it to open right where I select a word or end a selection of a block of text.

**Comment by mergen3107** [comment]
My main gripe with the popup menu is that if the selected words are in the middle, the popup menu shows up and covers them completely. 

I remember on very old Kindles (Keyboard and 4 Non-Touch), depending on the word selection the dictionary popup shows up at the top or the bottom of the screen.

**Comment by NiLuJe** [comment]
I seem to recall that we *do* position the popup relative to the selection box (at least when selecting a *single* word).

**Comment by mergen3107** [comment]
Ah, sorry - I don't know what single word selection popup looks like because I made it go to dictionary right away :D
