### ISSUE TITLE
WSA: Encoding/Codepage issue when copy/pasting text

### ISSUE THREAD

**Issue by mmschzs** [koreader/koreader#11083]
* KOReader version:2023.08
* Device:wsa

#### Issue
when I copy the text from koreader to paste on other app, the text is messy code.
![image](https://github.com/koreader/koreader/assets/67103160/2bd55ed1-08bd-4d8e-aba1-f4e24a3e45b8)
![image](https://github.com/koreader/koreader/assets/67103160/b87b06a0-3142-4531-b3e8-c02621457d8c)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
WSA meaning Windows Subsystem for Android?

**Comment by mmschzs** [comment]
yes, other apps on wsa seems got no problems获取Outlook for Android

**Comment by mmschzs** [comment]
> WSA meaning Windows Subsystem for Android?

yes, other apps on wsa seems got no problems获取Outlook for Android

**Comment by pazos** [comment]
WSA is being deprecated. Support ends in March 5, 2025.

Please use another emulation/virtualization system.
