### ISSUE TITLE
Top and down screen not reacting to some gestures in Boox devices

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#11082]
* KOReader version:
Last one, 2023.10

* Device:
Boox Palma

#### Issue
I got a Boox Palma today and noticed that the one finger swipe gestures doesn't work on the last 5mm of the screen. Top menu buttons don't work either if tapped in the first 5mm of the top of the screen. I tried with my Nova Air C and it is the same issue so it is something in principle related to these devices. I suspect it has to do with the System Navigation of the platform. I use last firmware in both so didn't try with the previous firmware.

**Comment by hugleo** [comment]
For Ultra C I've tested it with the stylus and the movement was detected for 1 mm or so.

11-05 16:01:29.021  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 871.397749
11-05 16:01:29.021  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 871.397749
11-05 16:01:29.021  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 947, time: 871.397749
11-05 16:01:29.021  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 2467, time: 871.397749
11-05 16:01:29.021  8047  8075 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 871.397749
11-05 16:01:29.021  8047  8075 V KOReader: slot 0 in tap state...
11-05 16:01:29.021  8047  8075 V KOReader: set up hold timer
11-05 16:01:29.066  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 871.442290
11-05 16:01:29.067  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 949.54840087891, time: 871.442290
11-05 16:01:29.067  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 2438.2043457031, time: 871.442290
11-05 16:01:29.067  8047  8075 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 871.442290
11-05 16:01:29.067  8047  8075 V KOReader: slot 0 in tap state...
11-05 16:01:29.092  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 871.468606
11-05 16:01:29.093  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 960.19354248047, time: 871.468606
11-05 16:01:29.093  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 2419.3291015625, time: 871.468606
11-05 16:01:29.093  8047  8075 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 871.468606
11-05 16:01:29.093  8047  8075 V KOReader: slot 0 in tap state...
11-05 16:01:29.118  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 871.488885
11-05 16:01:29.118  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 970, time: 871.488885
11-05 16:01:29.118  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 2404, time: 871.488885
11-05 16:01:29.118  8047  8075 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 871.488885
11-05 16:01:29.118  8047  8075 V KOReader: slot 0 in tap state...
11-05 16:01:29.118  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 47 (ABS_MT_SLOT), value: 0, time: 871.498841
11-05 16:01:29.119  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: -1, time: 871.498841
11-05 16:01:29.119  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 970, time: 871.498841
11-05 16:01:29.119  8047  8075 V KOReader: input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 2404, time: 871.498841
11-05 16:01:29.119  8047  8075 V KOReader: input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 871.498841
11-05 16:01:29.119  8047  8075 V KOReader: slot 0 in tap state...
11-05 16:01:29.119  8047  8075 V KOReader: Contact:handleDoubleTap: single tap detected @ 970 2404

**Comment by jospalau** [comment]
I should have used the stylus in the Nova Air to test too :)

In any case Palma buttons are so tiny and it is a bit annoying to tap them.

**Comment by hugleo** [comment]
You can try to increase the DPI in Koreader screen settings.

**Comment by jospalau** [comment]
That's definetely a good tip, thanks.

**Comment by mergen3107** [comment]
I had the "problem" with bottom edge taps. Then I disabled all Onyx gestures and never had a problem :D

**Comment by jospalau** [comment]
Is it an easy way to do that or you need to be root?

**Comment by jospalau** [comment]
Yes it is :) and that fixes it. In principle I don't mind since not having gestures since I will be using just KOReader. Thanks

**Comment by hugleo** [comment]
There is also a possibility that it could be a faulty device.

**Comment by jospalau** [comment]
Definitely no, because the issue also happens in my Nova Air C.

**Comment by hugleo** [comment]
Does this problem also occur on the Neoreader app?

**Comment by jospalau** [comment]
It works properly in Neoreader. In any case the adapted patch fixed it for KOReader

**Comment by matt08-prog** [comment]
> It works properly in Neoreader. In any case the adapted patch fixed it for KOReader

Would you mind sharing the patch that works on the Palma? Thanks.

**Comment by jospalau** [comment]
Hi. I didn't do a patch. I changed frontend/device/android/device.lua and generated a new apk. This is the change:
    local adjust_deadzone = function(this, ev)
    -- We come *after* the stock Kobo hooks (i.e., 
    SwitchXY), so we need to operate on ABS_MT_POSITION_Y
    		if android.prop.flavor == "rocks" and ev.type == 
      C.EV_ABS and ev.code == C.ABS_MT_POSITION_Y and ev.value <= 5 then
    			ev.value = 31
    		end
            if android.prop.flavor == "rocks" and ev.type == C.EV_ABS 
    and ev.code == C.ABS_MT_POSITION_Y and ev.value >= 1640 
    then
    			ev.value = 1635
    		end
     	end
        self.input:registerEventAdjustHook(adjust_deadzone)
