### ISSUE TITLE
FR: Dismiss Search UIs by tapping outside of search dialog

### ISSUE THREAD

**Issue by ryanwwest** [koreader/koreader#11092]
**Does your feature request involve difficulty completing a task? Please describe.**

From experimenting with https://github.com/koreader/koreader/issues/11054, I realized that all of the various search UIs there do not allow the user to exit or dismiss the search UI without clicking the 'cancel' button in the UI. Many other more frequently used dialog boxes do allow this, such as the highlight UI or some search result boxes like from the Dictionary (and these also have cancel/close buttons). This behavior is rather inconsistent, and on my 13 inch ereader, it is more tedious to have to reach to the center of the screen to use the cancel button.

**Describe the solution you'd like**
For all of these search query UIs, allow the user to click outside of the UI to dismiss the search.

**Comment by hius07** [comment]
Clicking outside of the dialog hides the keyboard.

**Comment by ryanwwest** [comment]
Yes, and it should if the virtual keyboard is open. But after it is not open, it would be nice if the dialog could be dismissed with another click outside the dialog for consistency with other dialogs.

**Comment by hius07** [comment]
Yes, maybe. I'll try if it is comfortable.

**Comment by ryanwwest** [comment]
Awesome, thank you!
