### ISSUE TITLE
Don't use REAGL waveform update modes in night mode

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#1109]
This is sort of a preventive report, now that we've enabled REGAL waveform update mode on the Kobo ;p.

Because it ghosts oh so very much.

Fair warning: I'm not a big fan of night mode, so this might take me a while to muster the will to even start looking at it... ;).
(Meaning even though I assigned myself to it, anyone is welcome to chime in, I'll be doing a brain dump in the next few comments ;)).

That would perhaps be the perfect occasion to handle [this TODO](https://github.com/koreader/koreader/blob/master/frontend/ui/uimanager.lua#L29) [WAVEFORM_MODE_GL16_INV on the KT2/KV], if someone has the hardware to check that this works as advertised ;).

**Comment by NiLuJe** [comment]
Note to self:

Turns out I've been reading the kernel sources right, right now, the H2O is *NOT* using REAGL update modes. The only Kobo doing so is the Aura. Which totally explains what we've been seeing in strace.

Way to go, Kobo. -_-".

**Comment by Markismus** [comment]
Couldn't we use PW2-implementation for the Carta screen for the H2O, too?

**Comment by NiLuJe** [comment]
@Markismus: It relies on the waveform being tailored for that, and the Kernel supporting it. We appear to have one of those two only on the H2O (kernel), so requesting REAGL updates behaves weirdly (flashes whereas it shouldn't).
