### ISSUE TITLE
FR: Start USB Storage via gesture

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11106]
I often keep my Kobo device connected to the computer while tweaking its code and/or transferring files, thereby often connecting and disconnecting USB Mass Storage several times. It would be very helpful if USBMS could be started via a gesture.

Could `Start USB Storage` be added to Dispatcher to make this possible?

**Comment by NiLuJe** [comment]
Fairly trivially, would need a new dedicated event in `DeviceListener` that does

```lua
local MassStorage = require("ui/elements/mass_storage")
MassStorage:start(true)
```

**Comment by jonnyl2** [comment]
Thank you for the PR @NiLuJe! 

I have another question. If I disable the USBMS confirmation popup, it will automatically start USBMS on plugging in the cable. And if I disable mass storage functionality, I can't start it manually either. Is there any way to set it up so that it doesn't do anything when I plug in the cable (on the UI), but I can still start USBMS manually on demand?
