### ISSUE TITLE
FR: Synchronize Progress after reading with Kavita

### ISSUE THREAD

**Issue by majora2007** [koreader/koreader#11105]
**Does your feature request involve difficulty completing a task? Please describe.**
I'm the developer of Kavita and was wondering if there is any possibility of enhanced synchronization between Kavita and Koreader (I can build new APIs just for this app integration)

**Describe the solution you'd like**
My users have asked for better synchronization. Progress reporting after reading a book from Kavita via OPDS (Panels does this by calling some dedicated APIs I built for them) or perhaps shelf syncing (I'm not sure if this is a thing, but users keep mentioning for the base Kobo).

I'm open to having more of a discussion and seeing what might be possible between us.

**Comment by NiLuJe** [comment]
You'll probably have to give more details about what exactly you're thinking of, because most of us have never used Kavita, and barely use OPDS (or at least not for that purpose).

For context (and IIRC), OPDS streaming (or whatever it's actually called), which is what I *think* this concerns, was a user contribution, so none of the maintainers are really familiar with any of it (or even of the concepts involved, as far as I'm concerned).

**Comment by Frenzie** [comment]
Pinging @bigdale123 who wrote the streaming support.

**Comment by hius07** [comment]
We ask the server for the last page when opening a Kavita book
https://github.com/koreader/koreader/blob/ed46dca8865d82afa657dc7975d64c25fb778599/plugins/opds.koplugin/opdspse.lua#L17-L18

**Comment by majora2007** [comment]
Is it possible to send the updated progress to Kavita after the reading session or manually/scheduled? 

Is there a concept of a book shelf where you could pull books from an OPDS feed onto your bookshelf? 

Is this app mainly about consuming on device books or are there more hooks into external services for acquisition? 

Please note, I have very limited understanding of Koreader/Kobo in general and going just off what I've been told over the year, so if my understanding is off, please inform me.

**Comment by offset-torque** [comment]
> Is this app mainly about consuming on device books or are there more hooks into external services for acquisition?

In short, probably majority of our users use **USB/SSH** or **Calibre transfer** to manage an on-device library. And a smaller percentage use **RSS/ATOM** and **Wallabag** services which are integrated to KOReader as plugins.

This part of our user guide summarizes book transfer options:
[Transferring books to KOReader](https://koreader.rocks/user_guide/#transferring)

And this part summarizes general capabilities of KOReader:
[WHAT CAN YOU DO WITH KOREADER ?](https://koreader.rocks/user_guide/#whatcanyoudo)

**Comment by majora2007** [comment]
I really appreciate the reply. After looking through the documentation and getting a hold of some of my users, I think the OPDS with KOReader is where I should leave it. Looks like they are wanting something with Kobo directly where Kavita intercepts the store APIs to provide books and sync progress. 

Again, really appreciate the information.

**Comment by offset-torque** [comment]
I am glad it helped. By the way, **Kavita** looks like an impressive piece of software. Good luck on your journey Joe.

**Comment by NiLuJe** [comment]
Oh, yeah, the shelves stuff is how Nickel (the native software) implements what we usually know as "collections", FWIW.

**Comment by stanthewizzard** [comment]
Hello
I'm also using Kavita to read on computer (mostly at work eating in front of computer ... what a life)
But using Kobo at home
So there is no way to have a sync between those two ?
Thanks

**Comment by gianlucalauro** [comment]
Hello, i have a problem.
I installed the latest version of kavita and koreader. Can download and read books from kavita, but the sync is not working. I also want to do page stream but it shows me the koreader logo only. What can i do?

**Comment by vuquangtam** [comment]
Have you resolved the issue @gianlucalauro. I got the same problem but dont know how to fix it.

**Comment by gianlucalauro** [comment]
I switched to calibre web and enabled the kobo store 'cause i got a Clara 2E

**Comment by gianlucalauro** [comment]
> Have you resolved the issue @gianlucalauro. I got the same problem but dont know how to fix it.

I switched to calibre web and enabled the kobo store 'cause i got a Clara 2E

**Comment by majora2007** [comment]
Just wanted to come back and say that in Kavita v0.8.7, Koreader progress sync will function.

**Comment by offset-torque** [comment]
> Just wanted to come back and say that in Kavita v0.8.7, Koreader progress sync will function.

I will add this information to our user guide. I see that you already wrote a nice guide for OPDS/synchronization, so I will directly link to your wiki page: https://wiki.kavitareader.com/guides/3rdparty/koreader/


Also I will add **Kavita** to our "library management" chapter to make our users aware of its existence. I am sure many of them will find it very useful.
