### ISSUE TITLE
Crash when writing a Note on a highlight

### ISSUE THREAD

**Issue by LukasKnuth** [koreader/koreader#11111]
* KOReader version: v2023.10
* Device: PocketBook Verse Pro

#### Issue

After creating a new highlight of text in an epub file, I clicked the highlight and selected "Note".
The input box for the note was rendered, but the UI was not responsive.
Shortly after, the crash screen appeared.

I have had two issues with this before where the screen was frozed for multiple seconds while entering text into the textbox.
The app did NOT crash these times though.

Worst yet, I lost all my highlights/notes of the last 30 or so minutes that I was reading.

#### Steps to reproduce

Unsure. Happened randomly.

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/13/23-21:01:56
 [*] Version: v2023.10

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
ffi.load: inkview
11/13/23-21:01:57 INFO  SoftwareVersion:  U634.6.8.1834 
ffi.load: inkview
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
Atached mp shm: id 0 addr a6f52000 size 17624
attach_shm: mtfb key=251348437 size=1657600
Atached mtfb shm: id c8009 addr a41a4000 size 1657600
-------------------------
Starting task - koreader.app
flags: 0x00000080
gpid: 1493
fb=0xa41a4000 xres=1072 yres=1448 scanline=1072 vdepth=8 orient=0
-------------------------
attach_shm: mttempfb key=251308714 size=1584128
Atached mttempfb shm: id 8001 addr a4021000 size 1584128
Atached mqueue: id 8001
[hw_setglobalkeymask] gka0 = 4000000; gka1 = c800002; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 10720000 0 -10000 0 10000 0
attach_shm: mtfb key=251348437 size=1657600
Atached mtfb shm: id c8009 addr a2b59000 size 1657600
ffi.load: librt.so
ffi.load: inkview
[1499 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: inkview
11/13/23-21:01:57 INFO  initializing for device PB634 
11/13/23-21:01:57 INFO  framebuffer resolution: {
  h = 1448,
  w = 1072
} --[[table: 0xa6bf6930]] 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: sqlite3
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
11/13/23-21:01:58 INFO  opening file /mnt/ext1/synced_ebook_library/technology/how_design_makes_the_world/book.epub 
11/13/23-21:01:58 INFO  Inhibiting user input 
11/13/23-21:01:58 INFO  Loading plugins from directory: plugins 
11/13/23-21:01:59 WARN  Terminal: can not open /dev/ptmx: Permission denied 
11/13/23-21:01:59 WARN  Error when loading plugins/terminal.koplugin/main.lua nil 
11/13/23-21:01:59 INFO  Restoring user input handling 
[1631] Nov 13 21:02:13 Running in background
ping: permission denied (are you root?)
[1634] Nov 13 21:02:20 Child connection from 192.168.178.50:56536
[1634] Nov 13 21:02:21 Login attempt with wrong user root from 192.168.178.50:56536
[1634] Nov 13 21:02:23 Exit before auth (user 'root', 1 fails): Error reading: Connection reset by peer
[1631] Nov 13 21:05:20 Early exit: Terminated by signal
11/13/23-21:05:27 INFO  Inhibiting user input 
11/14/23-12:15:30 INFO  Restoring user input handling 
11/14/23-12:19:11 INFO  Inhibiting user input 
11/14/23-12:19:11 INFO  Restoring user input handling 
11/14/23-12:19:23 INFO  opening file /mnt/ext1/synced_ebook_library/technology/how_design_makes_the_world/Scott Berkun - How Design Makes the World (2020, Berkun Media LLC) - libgen.li.epub 
11/14/23-12:19:23 INFO  Inhibiting user input 
11/14/23-12:19:24 INFO  Restoring user input handling 
11/14/23-12:25:39 INFO  Inhibiting user input 
11/14/23-13:53:33 INFO  Restoring user input handling 
11/14/23-13:54:06 INFO  Inhibiting user input 
11/14/23-13:54:51 INFO  Restoring user input handling 
11/14/23-13:55:43 INFO  Inhibiting user input 
11/14/23-13:55:55 INFO  Restoring user input handling 
11/14/23-14:13:37 INFO  Inhibiting user input 
11/14/23-16:20:59 INFO  Restoring user input handling 
[1499 : ./luajit] (GetTouchInfoI)NO TOUCH INFO!!! index = 1
[1499 : ./luajit] (GetTouchInfoI)NO TOUCH INFO!!! index = 1
[1499 : ./luajit] (GetTouchInfoI)NO TOUCH INFO!!! index = 1
[1499 : ./luajit] (GetTouchInfoI)NO TOUCH INFO!!! index = 1
[1499 : ./luajit] (GetTouchInfoI)NO TOUCH INFO!!! index = 1
[1499 : ./luajit] (GetTouchInfoI)NO TOUCH INFO!!! index = 1
11/14/23-16:32:48 INFO  Inhibiting user input 
11/14/23-16:32:49 INFO  Restoring user input handling 
11/14/23-16:32:49 INFO  Inhibiting user input 
11/14/23-16:32:49 INFO  opening file /mnt/ext1/synced_ebook_library/technology/design_data_intensive_applications/book.epub 
11/14/23-16:33:07 INFO  Restoring user input handling 
11/14/23-16:33:24 INFO  Inhibiting user input 
11/14/23-16:33:30 INFO  Restoring user input handling 
11/14/23-16:33:30 INFO  opening file /mnt/ext1/synced_ebook_library/technology/how_design_makes_the_world/book.epub 
11/14/23-16:33:30 INFO  Inhibiting user input 
11/14/23-16:33:31 INFO  Restoring user input handling 
11/14/23-16:36:29 INFO  Inhibiting user input 
11/14/23-17:25:43 INFO  Restoring user input handling 
11/14/23-17:38:15 INFO  Inhibiting user input 
11/14/23-19:03:01 INFO  Restoring user input handling 
[1499 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1499 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1499 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1499 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1499 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
[1499 : ./luajit] (mt_push_mtsection_to_current_container)full container, last pointer will be substituted
11/14/23-19:15:02 INFO  Inhibiting user input 
11/14/23-22:48:51 INFO  Restoring user input handling 
11/14/23-22:50:26 INFO  Inhibiting user input 
11/14/23-22:50:34 INFO  Restoring user input handling 
11/14/23-22:51:27 INFO  Inhibiting user input 
11/14/23-22:51:57 INFO  Restoring user input handling 
11/14/23-22:52:20 INFO  Inhibiting user input 
11/14/23-23:02:24 INFO  Restoring user input handling 
./luajit: frontend/device/gesturedetector.lua:1049: attempt to index field 'initial_tev' (a nil value)
stack traceback:
	frontend/device/gesturedetector.lua:1049: in function 'state'
	frontend/device/gesturedetector.lua:225: in function 'feedEvent'
	frontend/device/input.lua:822: in function 'handleTouchEv'
	frontend/device/input.lua:1367: in function 'waitEvent'
	frontend/ui/uimanager.lua:1505: in function 'handleInput'
	frontend/ui/uimanager.lua:1560: in function 'run'
	./reader.lua:242: in main chunk
	[C]: at 0x00013f6d
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 11/14/23 @ 23:55:02)
Attempting to restart KOReader . . .
!!!!
```
</details>

**Comment by NiLuJe** [comment]
Hard to say without a verbose debuig log, but I'm mildly worried by those `inhibitInput` pairs if those aren't actually suspend-induced o_O.

**Comment by NiLuJe** [comment]
I'm not familiar with the various short ones peppered around some UI elements, but I'm vaguely thinking we should just NOP `Input:inhibitInput` on PB because it's probably hilariously broken by the native standby behavior ;).

**Comment by LukasKnuth** [comment]
Looking at the timestamps for those events, you can see that the device was in standby quite a lot over the day.

Followup question: Is there perhaps a better way to guard against loosing all metadata on application crashes? As a workaround I have set the auto-save interval from 15 to 5min, but apparently too much IO causes wear on the internal storage.

Perhaps on a crash, we could write the current in-memory metadata to an `metadata.lua.crash` file and attempt to parse it (if present) when loading that same ebook again?

**Comment by NiLuJe** [comment]
Might also be related to the currently mysterious MT handling on PB, which could possibly cause stuff to be assigned to completely unexpected slots or something.

c.f., https://github.com/koreader/koreader-base/pull/1662

**Comment by NiLuJe** [comment]
> Perhaps on a crash, we could write the current in-memory metadata to an `metadata.lua.crash` file and attempt to parse it (if present) when loading that same ebook again?

Not really ;).

**Comment by NiLuJe** [comment]
> you can see that the device was in standby quite a lot over the day.

Do you mean suspend? (i.e., actually alseep, with a screensaver shown).

standby != suspend != hibernate; the distinctions are critical, especially on platforms that implement more than suspend (i.e., PB, where we control suspend, but where we don't really control standby, but where it exists and loves to screw us over).0

**Comment by hius07** [comment]
> Is there perhaps a better way to guard against loosing all metadata on application crashes?

There is an action "Save book metadata" in the Gesture manager (in the Reader section).
You can assign it to a gesture and trigger manually when needed.

**Comment by LukasKnuth** [comment]
> Do you mean suspend? (i.e., actually alseep, lights off, with a screensaver shown).

I use their own "Lock" function, thats what I meant by "standby". By default, thats assigned to double-tap the off button. It displays the logo with the sleeping PocketBook and turns off screen light and Wifi (as far as I have found up until now).

**Comment by LukasKnuth** [comment]
> > Perhaps on a crash, we could write the current in-memory metadata to an `metadata.lua.crash` file and attempt to parse it (if present) when loading that same ebook again?
> 
> Not really ;).

Is there documentation on why the application was designed this way?

I would contribute an auto-save option like "after every highlight change", but it seems to me the entire system was purposely build to avoid writing to disk as much as possible. Is there reasoning or historical data on why this was done?

**Comment by Frenzie** [comment]
> Is there reasoning or historical data on why this was done?

SD cards are not historical, and for that matter even cheap non-SD cards can wear down surprisingly quickly sometimes if they don't have advanced wear leveling. The highlight thing may or may not have slipped through the cracks, but actually in the current design it's specifically highlights that are problematic due to quickly adding up in the number of writes. See #2789 for some context.

**Comment by poire-z** [comment]
Long-press on `Gear>Document>Save book metadata: every...` and we will tell you all about our life story :)
![image](https://github.com/koreader/koreader/assets/24273478/c52a79c4-8756-4fe6-9323-9f040c23e395)

Also:
https://github.com/koreader/koreader/blob/ed46dca8865d82afa657dc7975d64c25fb778599/frontend/ui/elements/common_settings_menu_table.lua#L510-L516

About forcing it after every highlight change, it feels it has been discussed in the past - when we used to crash much often :) but now we don't - except on platforms like yours when you may use external-to-us-features, and well, we're no longer in an ideal world.
So, it may better be left to a [user patch](https://github.com/koreader/koreader/wiki/User-patches) for users in such situations.
We have events for when bookmarks added/remove:
https://github.com/koreader/koreader/blob/ed46dca8865d82afa657dc7975d64c25fb778599/frontend/apps/reader/modules/readerthumbnail.lua#L526-L530
so it may be just a matter of plugging these handlers in some module that doesn't have them yet to send that FlushSetting event.

**Comment by LukasKnuth** [comment]
@poire-z Do I need to enable the user patches somewhere? I'm attempting to build one on MacOS and have placed the Lua code into `KOReader.app/Contents/koreader/patches/2-smart-save.lua` but it's not being loaded.

I'm determining this by looking at the CLI output of `Contents/MacOS/koreader -d -v` and looking for the [info print](https://github.com/koreader/koreader/blob/ed46dca8865d82afa657dc7975d64c25fb778599/frontend/userpatch.lua#L70) in the userpatch file.

Any ideas?

**Comment by poire-z** [comment]
Dunno if there's anything special with MacOS. Or if we never thought about it :)
the `patches/` directory should be alongside the existing `settings/`, `screenshots/` or `settings.reader.lua`.
Also, we have a "Patch management" plugin, which should add itself in the Tools>More tools submenu, where you can see if your user patch was discovered, and if it ran or failed.

**Comment by Frenzie** [comment]
That's normally something like `$HOME/Library/Application Support`. `KOReader.app/Contents/koreader` sounds like where the app itself is, not the settings.

**Comment by NiLuJe** [comment]
Err, wasn't the issue on a PocketBook? Why are we talking about a mac>>OS bundle all of the sudden? o_O.

**Comment by Frenzie** [comment]
For trying/changing the user patch a tiny bit quicker I presume. ;-)
