### ISSUE TITLE
(Android 10) I broke Wi-Fi updates

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11112]
* KOReader version: 2023.10
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
Due to my (unhealthy) willingness to tinker with stuff, I disabled a bunch of apk's as I described here: https://www.mobileread.com/forums/showpost.php?p=4371799&postcount=95

Now KOReader Wi-Fi updates stopped working. Upon request, it gets the info that there is a nightly update, I hit update - it says wait until it downloads. And then nothing happens. If I try again, it says update is queued, wait until it's done. 

I was able to remove the "No internet warning" with `settings put global captive_portal_mode 0`, but it seems that wasn't the culprit. 

What package I shouldn't have uninstalled in the above list?

Cloud storage works though! So KOReader has no problem with accessing internet. 

I also know that I was able to update from 2023.10 to 2023.10-1 earlier (downgraded since then). 

(I will try to fetch the logs soon). 

Thanks!

**Comment by mergen3107** [comment]
[crash_broke_wifi.log](https://github.com/koreader/koreader/files/13358464/crash_broke_wifi.log)
Here are the logs. Tried to update in the very end. Sorry, cannot truncate the beginning at the moment, attaching it from Onyx itself :D

**Comment by hugleo** [comment]
Well,

The log also seems silent.

Put some logger.dbg(" from here on:

https://github.com/koreader/koreader/blob/ed46dca8865d82afa657dc7975d64c25fb778599/frontend/ui/otamanager.lua#L180C1-L180C1


Can you download a dictionary?

**Comment by mergen3107** [comment]
Thanks @hugleo !

Will try soon

**Comment by pazos** [comment]
> Now KOReader Wi-Fi updates stopped working. Upon request, it gets the info that there is a nightly update, I hit update - it says wait until it downloads. And then nothing happens. If I try again, it says update is queued, wait until it's done.

Unlike the rest of downloads, which we do on our own, APK downloads are done with an android feature called DownloadManager. This makes possible to do the download on the background and be notified on completion.

You managed to screw your device's download manager. A factory reset should recover that.

**Comment by mergen3107** [comment]
Thanks @pazos! I will do factory reset, but I wanted to figure out what was I broke exactly :D 
So I won't screw it up again next time. 

Interestingly, browser downloads work OK.

**Comment by offset-torque** [comment]
Have a look at this project **mergen3107** : [Universal Android Debloater](https://github.com/0x192/universal-android-debloater)

It provides community created safe lists for debloating your device and includes descriptions for packages found on your device if you want to disable them individually.

Also go light handed with system apps. Most of the apks in your disabled list are inert ones that doesn't use any system resources. And even problematic ones can be generally dealt with denying **RUN_IN_BACKGROUND** permission which is much safer (disabled apps can cause loops while the system is trying to start them, restricted ones just complain to logcat).

**Comment by mergen3107** [comment]
Thank you @offset-torque !
Yes, I should be more careful with all those…

**Comment by mergen3107** [comment]
Thank you everyone again!
I used the Universal Android Debloater to restore apps that might be casuing problems overall (and of course uninstall new ones that I found >:D).

To my shame, I then realized that I lost the ability to upgrade KOReader due to (stupid) me simply disabling access to internet for Download Manager via AFWall+ ...

Now everything is back to normal, oh well, at least I learned a thing or two ._.
