### ISSUE TITLE
FR: add X-Purism-FormFactor=Workstation;Mobile; in Linux .desktop file to have it displayed in Phosh

### ISSUE THREAD

**Issue by Popolon** [koreader/koreader#11118]
**Does your feature request involve difficulty completing a task? Please describe.**
Just add "X-Purism-FormFactor=Workstation;Mobile;" line on .desktop file for Linux. It will allow to be seen as compatible application on some Linux mobile devices desktops. Else need to show all application (including not compatibles one), however koreader works perfectly, and fit well the screen on Linux Mobile.

By default, application that are not compatible, don't have this line, and are then not displayed, at least in Phosh interface. I agree this is a weird choice, and not very wide standard.

**Comment by Frenzie** [comment]
Somewhat related, the AppStream metadata for this kind of thing https://blog.tenstral.net/2023/10/how-to-indicate-device-compatibility-for-your-app-in-metainfo-data.html
