### ISSUE TITLE
Dialogs cause the app to be unusable when touch input is disabled

### ISSUE THREAD

**Issue by mjtimblin** [koreader/koreader#11117]
* KOReader version: v.2023.10
* Device: Onyx Boox Page (Android)

#### Issue

I use a hot corner to toggle the touch input on my device. I often read books using page turn buttons with touch input disabled to prevent accidental interactions. When touch is disabled, the "You've reached the end of the document..." dialog cannot be interacted with. Hot corners are disabled when dialogs are visible, so I can't enable touch input to interact with the dialog. Page turn buttons have no effect on the dialog. The only workaround I've found is to use system level gestures (or buttons on some devices) to exit the app. Re-opening KOReader automatically enables touch input.

This issue is applicable to all dialogs and is not exclusive to the "You've reached the end of the document..." dialog. A previous version of KOReader had a bug that would cause the "Enable WiFi" dialog to appear seemingly randomly while reading books. I had the same problem with this dialog and could only get around it by using my device's home gesture and reopening KOReader.

I can think of a 3 different solutions to this problem:
1. Touch input is enabled when dialogs are shown
2. Dialogs do not disable hot corners
3. Page turn buttons dismiss dialogs

#### Steps to reproduce

1. Setup a hot corner to toggle touch input
2. Open a book
3. Disable touch input using the hot corner
4. Use page turn buttons to complete the book
5. A dialog will popup when the book is completed

**Comment by mjtimblin** [comment]
@hius07 Yes. That's another workaround. I forgot to mention it since I have a password on my lock screen and don't use that method often.

**Comment by NiLuJe** [comment]
https://github.com/koreader/koreader/issues/10812#issuecomment-1815180315

**Comment by NiLuJe** [comment]
Well, first round of testing went swimmingly. Pulled out a Clara, opened a test book, checked that I still had the EoB popup enabled, enabled a toggle touch input gesture... then realized that device didn't have buttons to turn pages. :D.

So, more on that later (with more sleep) and a charged device with buttons ;p.

(I had a quick glance at the code, and don't see anything obvious; unless I forgot even more stuff about modals and event propagation ;p)
