### ISSUE TITLE
FR: Reference layouts by file extension

### ISSUE THREAD

**Issue by federicodilo** [koreader/koreader#11125]
**Does your feature request involve difficulty completing a task? Please describe.**
Comic files generally requires a vertical layout type and the switching off of night mode, whereas, a text file has other requirements (I find horizontal layouts quite comfortable) that implies resetting the layout each time I switch from file type to file type.

**Describe the solution you'd like**
Similar file extensions typically require similar formatting. It would be convenient to have a reference layout referring to an extension rather than a single file. Or even multiple layouts (placeholders between layout options) to which refer a file to.

**Describe alternatives you've considered**
Unfortunately, having the option of saving only one type of reference layout makes the process of resetting the layout tedious.

**Comment by NiLuJe** [comment]
Not exactly per-format, but per-folder is doable, because [There's a Plugin For That(TM)](https://github.com/koreader/koreader/blob/master/plugins/docsettingtweak.koplugin/directory_defaults_template.lua) ;p.

**Comment by Frenzie** [comment]
Also you could make a profile attached to a gesture/corner tap or something to toggle night mode and orientation simultaneously.

**Comment by federicodilo** [comment]
> Not exactly per-format, but per-folder is doable, because [There's a Plugin For That(TM)](https://github.com/koreader/koreader/blob/master/plugins/docsettingtweak.koplugin/directory_defaults_template.lua) ;p.
> 
> (c.f., #5428 for context)

I cannot find any clue for assignable commands. Any guidance would be appreciated. 😃 

Nevertheless I thank you, I will follow your advice.

**Comment by Frenzie** [comment]
First you make a profile (under tools → profiles, could be second page on shorter devices), then you can find it in the gesture manager under the general category (possibly after enabling "show in action list" on the profile? not sure otoh)
