### ISSUE TITLE
Books sent with a cable will not appear in the Calibre device's library if you connect wirelessly.

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#11136]
* KOReader version: 2023.10-22-gdea94026f_2023-11-19
* Device: Kindle paperwhite

when i connect my kindle with cable to my computer, calibre detects all my books on my device. in my library, calibre shows a ✔ corner of books (meaning i have that on device too).
But when I connect the device wirelessly, only some of the books have ✔ instead of all of them.

#### Steps to reproduce
1. connect device with cable and send some book to device
2. eject device
3. connect device with wireless device connection 
4. you cant see books on device that you send with cable

In wireless device connection Calibre only shows books that send in wireless mode, not with cable.

**Comment by pazos** [comment]
all device drivers are calibre plugins, go to manage plugins on calibre and uncheck kindle device driver.

**Comment by mkacuba** [comment]
You want to connect to the Kindle folder, not to the library folder on Your computer, that would be pointless. Connect your Kindle with USB and select 'documents' folder on your Kindle device.
In plugins search for "kindle device interface" and disable those 4 plugins from screenshot below. I wasn't sure which exactly so I turned off all of them.
![2023-11-21 16_42_55-Window](https://github.com/koreader/koreader/assets/18098813/6c1afd70-40e4-4da5-be83-ae05b898736a)
