### ISSUE TITLE
FR: Option to leave QuickMenu open after executing an action

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11131]
**Does your feature request involve difficulty completing a task? Please describe.**

Some QuickMenu actions can be very useful to use as incremental settings (e.g., brightness +1/-1, font size +1/-1, turning pages or chapters, etc.), or to add several options that one uses in succession (but not simultaneously), e.g., turn on wifi and then start SSH server (this doesn't work together IME). 

However, after each time an action was selected, the QuickMenu closes and first has to be relaunched before another (or the same) option can be (re)selected.

**Describe the solution you'd like**

- Add an option in the Gesture Manager (below `Show as QuickMenu`) that prevents the closing of the dialog, e.g., `Leave QuickMenu open`

This way, the user can create a separate QuickMenu for those actions they would like to use without immediately closing the QuickMenu. (The QuickMenu then has to be closed manually by tapping outside of it.)

**Describe alternatives you've considered**

An alternative I had considered was that long-pressing a QuickMenu item would prevent the dialog from closing. The problem with this, however, is that long press on profiles is already reserved. (Should this alternative be considered, perhaps one could bypass the current behavior for profiles if the profile contains only 1 action.)

**Comment by offset-torque** [comment]
+1 for this.
I think about this whenever I adjust the font size and execute wifi actions via QM as in the **jonnyl2**'s examples. 
Proposed solution is logical too.
(Although this is not a serious inconvenience for me. More like **"would be nice if it is not too much effort"**.)
