### ISSUE TITLE
Q: What is the best practice for migration docsettings between different devices?

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11132]
**Goal**: Move all books from KOReader (Android) to KOReader (Kindle).
**Current settings**: docsettings are in the koreader folder on Android.

A) Should I move docsettings next to books on Android first, then copy the whole Home folder with Books on Kindle, and then move docsettings to koreader folder on Kindle?

Or

B) Should I transfer koreader/docsettings, but change the directories inside? Because they are different in Android and Kindle.

(I will also, of course, change the paths in history.lua and settings.lua).

Thanks!

**Comment by hius07** [comment]
Assume all books on the source device are in the Home folder and its subfolders.
Open the file browser, go to Home.

(1) In the menu Settings - Document set Book metadata location to "book folder".
In that menu, do "Move book metadata".
Now all books metadata is near the book in Home.
Move Home folder to the target device.

(2) In the menu Settings - Document set Book metadata location to "./hashdocsettings".
In that menu, do "Move book metadata".
Now all books metadata is in the koreader/hashdocsettings folder.
Move this folder and Home folder to the target device.

**Comment by mergen3107** [comment]
Thank you @hius07 !

Now I understand the meaning of hashsettings added recently. It is path-agnostic :D 

I'll do backups and try later (if I am lucky with brand new Kindle's FW…)
