### ISSUE TITLE
All highlights become populated with notes

### ISSUE THREAD

**Issue by ironhak** [koreader/koreader#11145]
* KOReader version: Last
* Device: Kobo Libra 2

#### Issue
I had several highlights with no notes in them. Suddenly all highlights reported a note inside them, all of them had a note like this: "/time of highlight /text". So for example if I had highlighted a line that goes like: "This is a sample line.", the highlight would have a note with it's content like: "@2023-11-10  This is a sample line.". 
#### Steps to reproduce
I don't know how it happened.

**Comment by offset-torque** [comment]
Pinging @hius07 - I noticed this too. Started maybe 2-3 versions prior.

**Comment by hius07** [comment]
Menu Settings - Language set the language which the highlights have been made with.
Open the document.
In the upper menu select 1st tab - Settings - Bookmarks, uncheck Add page number...
Open Bookmark list.
Long-press the upper left icon, it should change to checkmark.
Tap it, press Select all.
Tap it again, press Reset.

Report here on results.

**Comment by ironhak** [comment]
> Menu Settings - Language set the language which the highlights have been made with. Open the document. In the upper menu select 1st tab - Settings - Bookmarks, uncheck Add page number... Open Bookmark list. Long-press the upper left icon, it should change to checkmark. Tap it, press Select all. Tap it again, press Reset.
> 
> Report here on results.

I already manually removed all notes so I can't report back to you, maybe someone who still have them or wait for a new occourence of this problem.

**Comment by hius07** [comment]
Did you change the language of the interface?
It supposed to be the reason of the issue.

**Comment by ironhak** [comment]
I "cahnged" it meaning that it was english interface, I went to language settings and checked "English" despite it was unchecked. Device restarted and nothing changed (no new notes spawned).

**Comment by offset-torque** [comment]
In my case, my interface language was always English and never changed. This is an interesting bug. It doesn't happen all the time. I couldn't determine a pattern like "number of highlights" or PDF/EPUB difference. I just checked the latest books I have been reading and they look all ok (no notes). I will try to find some older ones with this.

**Comment by ZHANYLone** [comment]
> * KOReader version: Last
> * Device: Kobo Libra 2
> 
> #### Issue
> I had several highlights with no notes in them. Suddenly all highlights reported a note inside them, all of them had a note like this: "/time of highlight /text". So for example if I had highlighted a line that goes like: "This is a sample line.", the highlight would have a note with it's content like: "@2023-11-10  This is a sample line.". 
> #### Steps to reproduce
> I don't know how it happened. 
> 

I don't know about now. But some time ago I had the same problem on my device
PocketBook 633. Is this problem fixed? Please fix this in the new version. 

p.s. I ADORE KOREADER.

**Comment by ZHANYLone** [comment]
> Did you ever change the language of the interface?
> It supposed to be the reason of the issue.

I had (maybe now too, I didn't check) the same problem. I changed the language once I installed KOReader from English to Russian. But I read books in both languages. Did you fix the problem?

**Comment by offset-torque** [comment]
**Giving an update:**
I started a book (EPUB) at the same time this issue opened (November 2023) and finished it last month. It is a thick book and I have ~120 highlights and ~30 notes. Everything looks ok. None of the highlights turned into notes. I am also reading some other books and PDF articles with highlights. They all look ok too.

**Comment by hius07** [comment]
There is no way to automatically fix the issue.
In https://github.com/koreader/koreader/pull/11563 there is a new button "Delete note" in the dialog for selected bookmarks.

**Comment by skylarsoulmate** [comment]
> Menu Settings - Language set the language which the highlights have been made with.
> Open the document.
> In the upper menu select 1st tab - Settings - Bookmarks, uncheck Add page number...
> Open Bookmark list.
> Long-press the upper left icon, it should change to checkmark.
> Tap it, press Select all.
> Tap it again, press Reset.
> 
> Report here on results.

I already unchecked the Add page number button a long time ago and it solved the problem! But after the latest update (nightly) I don't see this button in settings.

And this problem doesn't show now...
