### ISSUE TITLE
build.koreader.rocks down

### ISSUE THREAD

**Issue by Eeems** [koreader/koreader#11146]
http://build.koreader.rocks is returning a 522, due to a timeout while cloudflare is trying to connect to the host. This means that nightlies are unavailable, as well as the following dictionaries:

https://github.com/koreader/koreader/blob/bf03f40ef218797cc1288efaaac817ee479d1e3a/frontend/ui/data/dictionaries.lua#L5-L12
https://github.com/koreader/koreader/blob/bf03f40ef218797cc1288efaaac817ee479d1e3a/frontend/ui/data/dictionaries.lua#L13-L20
https://github.com/koreader/koreader/blob/bf03f40ef218797cc1288efaaac817ee479d1e3a/frontend/ui/data/dictionaries.lua#L61-L68

**Comment by Frenzie** [comment]
See #10615 for discussion. Btw, you should normally be able to download releases from <https://github.com/koreader/koreader/releases/download/v2023.10/koreader-remarkable-v2023.10.zip> according to the same pattern?

**Comment by Eeems** [comment]
> See #10615 for discussion.

It took a while, but I finally found https://github.com/koreader/koreader/issues/10615#issuecomment-1722075351 as the reason. It might be a better idea to pull this out into its own discussion with a relevant title.

> Btw, you should normally be able to download releases from https://github.com/koreader/koreader/releases/download/v2023.10/koreader-remarkable-v2023.10.zip according to the same pattern?

Is this the same file as would be served on build.koreader.rocks? If so, I'm not entirely sure why we aren't using it to begin with.

**Comment by Frenzie** [comment]
> It might be a better idea to pull this out into its own discussion with a relevant title.

There's not much to discuss; setting up a different VPS not on Azure is a very straightforward path forward but I just haven't found the time. I'll change the title.

> Is this the same file as would be served on build.koreader.rocks? If so, I'm not entirely sure why we aren't using it to begin with.

Yes, it's identical. You'll just be able to find it on build.koreader.rocks slightly sooner.

**Comment by Eeems** [comment]
> > It might be a better idea to pull this out into its own discussion with a relevant title.
> 
> There's not much to discuss; setting up a different VPS not on Azure is a very straightforward path forward but I just haven't found the time. I'll change the title.

Fair enough, thanks!

> 
> > Is this the same file as would be served on build.koreader.rocks? If so, I'm not entirely sure why we aren't using it to begin with.
> 
> Yes, it's identical. You'll just be able to find it on build.koreader.rocks slightly sooner.

Alright, I'll switch to using that. Should we close this issue since #10615 is tracking this?

**Comment by Frenzie** [comment]
Yes, let's do that.
