### ISSUE TITLE
Frontlight is enabled on device wakeup

### ISSUE THREAD

**Issue by CyberRoamer** [koreader/koreader#11142]
* KOReader version:KOReader 2023.10 "Ovis"
* Device: PW3

#### Issue
Whenever I wake my device from sleep, frontlight automatically gets enabled at low level(maybe at 2 or 3 only slightly noticeable in darkness) and needs to be manually disabled. 

This issue is not present in my last backup of koreader from Dec 2022. Don't know when it started.
 
#### Steps to reproduce
1) Put the device(with frontlight disabled) to sleep using power button.
2) Turn on the device using power button(frontlight enabled at level 2 or 3)

P.S.: I also think that the swipe gesture area at top and bottom should be easily adjustable. So far been editing ../koreader/plugins/gestures.koplugin/main.lua after every update to reduce it to avoid accidentally getting page turn swipe registered as swipe gesture. Would appreciate to know of a better way, if there is. Im also having troubles with dictionary lookup for a few pdf files since a long time.

**Comment by NiLuJe** [comment]
IIRC, the firmware does that for us.

When you mentioned a backup on an older version, was that running on the *same* FW, or was that just a memory of yore? ;).

**Comment by NiLuJe** [comment]
> P.S.: I also think that the swipe gesture area at top and bottom should be easily adjustable. So far been editing ../koreader/plugins/gestures.koplugin/main.lua after every update to reduce it to avoid accidentally getting page turn swipe registered as swipe gesture.

Err, which gestures are we talking about here?

**Comment by CyberRoamer** [comment]
> IIRC, the firmware does that for us.
> 
> When you mentioned a backup on an older version, was that running on the _same_ FW, or was that just a memory of yore? ;).

same FW. I had copied(backupped?) the koreader folder in the root directory of kindle after customizing and all somewhere around Dec, 2022. After noticing the frontlight, i replaced the koreader folder with my backup and started the koreader(the issue was gone). But after, I updated koreader(using inbuilt updater(tried both stable and beta channels)), the issue reappeared. Although i don't know how much that would even affect the battery but there seemed to be no noticeable differences between latest version and the dec 2022 one, so am currently using with that.

**Comment by CyberRoamer** [comment]
> > P.S.: I also think that the swipe gesture area at top and bottom should be easily adjustable. So far been editing ../koreader/plugins/gestures.koplugin/main.lua after every update to reduce it to avoid accidentally getting page turn swipe registered as swipe gesture.
> 
> Err, which gestures are we talking about here?

edge swipe gestures zones. to be specific, the definition of zones in lines 782-802. 

I apologize for my caveman habits if that has already been done and Im just not up-to-date with changes.

**Comment by NiLuJe** [comment]
I can't reproduce the frontlight thing on a PW5.

How and when are you toggling the frontlight off?

**Comment by NiLuJe** [comment]
> I can't reproduce the frontlight thing on a PW5.

Ah. For good reason: #5989 

I'll see if I can reproduce on a PW2 instead, then...

**Comment by hius07** [comment]
Voyage: set frontlight to 0.
Sleep/wakeup keeps 0, restarting KOReader sets it to 1 (which is known to be the system minimum).

**Comment by NiLuJe** [comment]
> restarting KOReader sets it to 1 (which is known to be the system minimum).

But is it still *off*?

(By which I mean, since "off" doesn't exist in the native UI, 0 in the Kindle UI *should* map to *1* in the KOReader UI).

(Can't check right now on my end, PW2 was flat).

**Comment by hius07** [comment]
No, it's physically on at the minimum level but visible.

**Comment by NiLuJe** [comment]
Sorry, I worded that question badly.

When you mentioned 0, was that in the native UI or in KOReader? (i.e., if that 0 was in the native UI, then the frontlight was never actually off, so it's all good).

**Comment by NiLuJe** [comment]
Okay, repro'd, there was indeed a big mess, unearthed by a stupid regression (I duplicated a method name in #10426 >_<"), mixed in with very old bugs because the whole PowerD API is a gigantic mess.

**Comment by NiLuJe** [comment]
For future reference: when suspending with the light turned off (the hard way, since lipc won't), the native system *will* indeed resume the device at lipc 0, which effectively means the light is ever slightly on.

We fix that ourselves a few moments later, so it *will* briefly flicker on.

**Comment by hius07** [comment]
BTW, when toggling with a gesture, I see "Frontlight disabled", but do not see "Frontlight enabled" notification.

**Comment by NiLuJe** [comment]
> BTW, when toggling with a gesture, I see "Frontlight disabled", but do not see "Frontlight enabled" notification.

Indeed, hadn't noticed in the dark ;p.

Fixed it, too, thanks!
