### ISSUE TITLE
Toggle flashing on the next page with images as well

### ISSUE THREAD

**Issue by dmalinovsky** [koreader/koreader#11143]
* KOReader version: 2023.10
* Device: Pocketbook Inkpad Color

#### Issue

If you have the "E-ink settings" set this way:

- Full refresh is "Never".
- "Always flash on pages with images" to "on".

Then the next page after an image will have ghosting. 

#### Steps to reproduce

Get any document with the big image and set settings identical to the above.

<details>
<summary>See the photos for illustration.</summary>

![Page with image](https://github.com/koreader/koreader/assets/483357/51aeef95-bedf-48e9-8211-9b8208d36bbb)

![Next page with ghosting](https://github.com/koreader/koreader/assets/483357/6e06645c-d152-4e15-94b7-a1634d4c568b)
</details>

#### Suggestion solution

We should copy the behavior of the builtin Pocketbook reader — if we flash on the page with the image, then we should always flash on the next page to clear the image artifacts. In this case, the setting can be renamed like this "Always flash on and after the pages with images".

**Comment by NiLuJe** [comment]
That's a fair point, the chapter break one does this on both sides of chapter breaks because of whitespace, but I guess I don't encounter image content often enough to have been bothered by that one.
