### ISSUE TITLE
Kindle Scribe: Wrong orientation on start

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11144]
* KOReader version: 2023.10-23
* Device: Kindle Scribe (FW 5.16.2)

#### Issue
I started KOReader in upside-down orientation (wide bezel on the right).
Touch map was OK, but the actual picture was upside down. I had to mirror-guess where to hit in order to quit :D 

First ever startup crash.log:
[crash_Kindle_Scribe.log](https://github.com/koreader/koreader/files/13445803/crash_Kindle_Scribe.log)

**Comment by mergen3107** [comment]
After Upright launch, all orientations work great!

**Comment by NiLuJe** [comment]
Quite likely a similar issue as the Oases, c.f., https://github.com/koreader/koreader/blob/bf03f40ef218797cc1288efaaac817ee479d1e3a/frontend/device/kindle/device.lua#L1019-L1052

**Comment by mergen3107** [comment]
`help-wanted`: please let me know how I can help :) 
I've got my fav SSH xD

**Comment by mergen3107** [comment]
I didn't kill `showlog -f` and the boys just yet, I keep it mostly in Airplane anyway lol

**Comment by NiLuJe** [comment]
Basically, poke around for something similar to what's done on Oasis in the snippet above and see what makes sense. If touch input isn't borked, it might be nicer to just force a *koreader* rotation instead of enforcing the native one (e.g., something in the spirit of what isAlwaysPortrait does on PB).

**Comment by NiLuJe** [comment]
(But enforcing the native portrait will *probably* be simpler, and offer better performance).

**Comment by mergen3107** [comment]
I copied the same snippet from the Oases into KindleScribe:init, but this didn't help.

I also noticed that there is no mention of the accelerometer device. Should we add it?

**Comment by mergen3107** [comment]
`/proc/bus/input/devices` has this:
```
I: Bus=0018 Vendor=003d Product=0000 Version=0000
N: Name="kx132-accel"
P: Phys=
S: Sysfs=/devices/platform/11007000.i2c/i2c-0/0-001f/input/input1
U: Uniq=
H: Handlers=event1 perfmgr 
B: PROP=0
B: EV=9
B: ABS=1000007
```
Other things are Stylus, Wacom digitizer, power button, and something called `pt_mt`.
The whole thing:
```
I: Bus=0019 Vendor=0001 Product=0001 Version=0100
N: Name="bd71828-pwrkey"
P: Phys=gpio-keys/input0
S: Sysfs=/devices/platform/10019000.i2c/i2c-1/1-004b/gpio-keys.7.auto/input/input0
U: Uniq=
H: Handlers=event0 perfmgr 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0018 Vendor=003d Product=0000 Version=0000
N: Name="kx132-accel"
P: Phys=
S: Sysfs=/devices/platform/11007000.i2c/i2c-0/0-001f/input/input1
U: Uniq=
H: Handlers=event1 perfmgr 
B: PROP=0
B: EV=9
B: ABS=1000007

I: Bus=0018 Vendor=2d1f Product=0158 Version=1827
N: Name="WacomDigitizer"
P: Phys=
S: Sysfs=/devices/platform/1001e000.i2c/i2c-2/2-0009/input/input2
U: Uniq=
H: Handlers=event2 perfmgr 
B: PROP=2
B: EV=b
B: KEY=1c03 0 0 0 0 0 0 0 0 0 0
B: ABS=f000003

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="pt_mt"
P: Phys=2-0024/input0
S: Sysfs=/devices/platform/1001e000.i2c/i2c-2/2-0024/input/input3
U: Uniq=
H: Handlers=event3 perfmgr 
B: PROP=2
B: EV=f
B: KEY=0
B: REL=0
B: ABS=ee18000 0

I: Bus=0018 Vendor=2d1f Product=0158 Version=1827
N: Name="stylus-custom"
P: Phys=
S: Sysfs=/devices/virtual/input/input4
U: Uniq=
H: Handlers=event4 perfmgr 
B: PROP=0
B: EV=b
B: KEY=1c03 0 0 0 0 0 0 0 0 0 0
B: ABS=f000003
```

**Comment by mergen3107** [comment]
> and something called `pt_mt`.

Maybe that's the premium pen button or eraser.

**Comment by mergen3107** [comment]
By the way, there is no G-sensor support as well in Kindle Scribe.
I copied the snippet about getting the accelerometer input device, added `hasGsensor = true,` in the KindleScribe description, but I can't get the acceloremeter events to work. I found two gestures that are named "Rotation - Rotate 90 deg CW arrow" and "Rotation - Rotate 90 deg CCW arrow" and assigned actions to them, but they don't seem to work.

**Comment by NiLuJe** [comment]
kx132 is the gyro, but I don't even know if/how we support gyros on Kindle. Never had one with a gyro myself.

**Comment by mergen3107** [comment]
I got it working!
I'll make a PR shortly.

**Comment by mergen3107** [comment]
https://github.com/koreader/koreader/pull/11157

**Comment by mergen3107** [comment]
Having G-sensor working and enabling "Lock rotation to current orientation" is great!
Now it rotates, for example, only in Portrait: 0/180 deg, or only in Landscape (if set by hand): 90/270 deg.

@NiLuJe,
Can we just force KOReader to start in upright position only?

If the user has started KOReader in upside-down, they will need to rotate the device back and forth, but at least the UI won't be broken.

**Comment by NiLuJe** [comment]
> Can we just force KOReader to start in upright position only?

That's the intent of the Oasis hack, IIRC.

**Comment by mergen3107** [comment]
In this case it didn't do the trick - upside down stays upside down, but touch is inverted (the same stroy as OP).

**Comment by mergen3107** [comment]
How about making `orientationLock` in the `koreader.sh` before KOReader actually lanuches?
https://www.mobileread.com/forums/showthread.php?t=263246

**Comment by mergen3107** [comment]
`eboard` chess uses it, I recently made it Portrait only by 
`lipc-set-prop com.lab126.winmgr orientationLock U`

**Comment by NiLuJe** [comment]
That sounds like something feasible, except I'd keep it inside that device block, via `set_string_property\ on an lipc handle like what the snippet did.

**Comment by mergen3107** [comment]
I tried to add `lipc_handle:set_string_property("com.lab126.winmgr", "accelerometer", "U")` right before `lipc_handle:close()`, didn't work, but didn't crash neither :D

**Comment by mergen3107** [comment]
Having so much fun:
added `logged.dbg("Accelerometer = ", rotation_code) only to find out it is:
```
11/25/23-19:39:11 DEBUG Accelerometer =  nil 
```
I can verify that the command
```
lipc-get-prop com.lab126.winmgr accelerometer
```
from SSH takes about 30 sec to think then gives a time-out response whne KOReader is open.
When it is closed, it reports "U":
```

[root@kindle root]# lipc-get-prop com.lab126.winmgr accelerometer
com.lab126.winmgr failed to access property accelerometer (0xf lipcErrTimedOut)

[root@kindle root]# lipc-get-prop com.lab126.winmgr accelerometer
U
```

**Comment by mergen3107** [comment]
Looks like lipc is having fun during the call:
```
11/25/23-20:10:39 DEBUG lipc =  {
  ERROR = {
    ACCESS_NOT_ALLOWED = 9,
    BUFFER_TOO_SMALL = 10,
    DUP_SERVICE_NAME = 17,
    DUP_SUBSCRIPT = 20,
    INIT_DBUS = 18,
    INTERNAL = 2,
    INVALID_ARG = 12,
    INVALID_HANDLE = 11,
    NAME_TOO_LONG = 16,
    NONE = 0,
    NO_SUCH_PARAM = 7,
    NO_SUCH_PROP = 8,
    NO_SUCH_SOURCE = 3,
    OP_NOT_ALLOWED = 13,
    OP_NOT_SUPPORTED = 4,
    OUT_OF_MEMORY = 5,
    PARAM_SIZE_EXCEEDED = 14,
    SUBSCRIPT_FAILED = 6,
    TIMED_OUT = 15,
    UNKNOWN = 1,
    UNSUBSCRIBE_FAILED = 19
  } --[[table: 0xb6c030d0]],
  init = function() --[[..skipped..]] end --[[function: 0xb6c03018]],
  run_event_loop = function() --[[..skipped..]] end --[[function: 0xb6c03088]],
  set_error_handler = function() --[[..skipped..]] end --[[function: 0xb6c03038]]
} --[[table: 0xb6c02ff0]] 
```

**Comment by mergen3107** [comment]
This is in modified snippet:
```
    --- @fixme The same quirks as on the Oasis 2 apply ;).
    local haslipc, lipc = pcall(require, "liblipclua")
    logger.dbg("lipc = ", lipc)
    if haslipc and lipc then
        local lipc_handle = lipc.init("com.github.koreader.screen")
        if lipc_handle then
            local orientation_code = lipc_handle:get_string_property(
                "com.lab126.winmgr", "accelerometer")
            logger.dbg("Accelerometer = ", orientation_code)
            local rotation_mode = 0
            if orientation_code then
                if orientation_code == "U" then
                    rotation_mode = self.screen.DEVICE_ROTATED_UPRIGHT
                elseif orientation_code == "R" then
                    rotation_mode = self.screen.DEVICE_ROTATED_CLOCKWISE
                elseif orientation_code == "D" then
                    rotation_mode = self.screen.DEVICE_ROTATED_UPSIDE_DOWN
                elseif orientation_code == "L" then
                    rotation_mode = self.screen.DEVICE_ROTATED_COUNTER_CLOCKWISE
                end
            end

            if rotation_mode > 0 then
                self.screen.native_rotation_mode = rotation_mode
                self.screen.cur_rotation_mode = rotation_mode
            end
            lipc_handle:set_string_property("com.lab126.winmgr", "accelerometer", "U")
            lipc_handle:close()
        end
    end
```

**Comment by mergen3107** [comment]
I played around with the rotation again.
Commented out the whole lipc part, then just did straight:
```
...
    self.screen.native_rotation_mode = 1
    self.screen.cur_rotation_mode = 1
    Kindle.init(self)
...
```
`1` gave Lanscape-left, `2` gave upside down, `3` gave lanscape-right.
Then I tried `0` and Kindle crashed, see: https://www.mobileread.com/forums/showpost.php?p=4375644&postcount=531

After things got back to normal, tried `0` again, and it worked OK. However, this didn't fix the problem in the OP.

**Comment by mergen3107** [comment]
By the way, I am using this great gesture to Exit KOReader (https://github.com/koreader/koreader/pull/11157#issuecomment-1826225998):
Pivot rotation (like compass) using two fingers (it should really be renamed in the dispatcher).
Even if KOReader boots up upside down, I don't have to guess where to tap to find Top menu - then long-press Exit :D

**Comment by mergen3107** [comment]
Important details I kept failing to tell: I launch KOReader via KOL 1.3.6

**Comment by mergen3107** [comment]
I tested change of rotation in Kindle books. It seems like Kindle treats `U` and `D` the same, as in:
```
lipc-set-prop com.lab126.winmgr orientationLock D
lipc-set-prop com.lab126.winmgr orientationLock U
```
It reports the letter correctly, if I ask `lipc-get-prop com.lab126.winmgr orientationLock`, but the interface doesn't change.
Landscape guys works as expected though:
```
lipc-set-prop com.lab126.winmgr orientationLock L
lipc-set-prop com.lab126.winmgr orientationLock R
```

**Comment by mergen3107** [comment]
The same mirror story if I go to Landscape by hand from the Kindle books menu, then try `L`/`R`: no change, try `U`/`D`: rotates OK.

**Comment by mergen3107** [comment]
@NiLuJe 
Anything else I can try?

**Comment by NiLuJe** [comment]
Figure out what happens when the native UI is upside-down vs. upright and try to replicate that, yeah ;).

lipc timing out is... interesting, you might want to see if it behaves any better when *not* in no framework mode, if that wasn't the case already.

**Comment by NiLuJe** [comment]
We *do* SIGSTOP awesome (but then again, that should already have been the case when those Oasis hacs were implemented :?), so that might be a key factor in the timeout.

See if it works any better if sandwiched between a `killall -CONT awesome` & `killall -STOP awesome`.

**Comment by mergen3107** [comment]
Thanks!
All these times I only KOReader in normal mode, didn't try framework-less mode.
Let me see `awesome` stuff...

**Comment by mergen3107** [comment]
Outcome of the `lipc-get-prop com.lab126.winmgr orientationLock`:
`Regular start`: timeout
`ASAP`: timeout
`KOL`: timeout
`Stop framework`: success, reported correctly, `U`. Let me see if the snippet works...

**Comment by mergen3107** [comment]
Yep, it all works great in `no framework` mode!
Once I started KOReader-no-framework while Kindle was in `D` orientation, KOReader started upside down. It only took me rotation to 90 deg back and forth to make it straight. Touch map and Screen are now correct.

@NiLuJe 
Is there something wrong with `no framework` mode? Why don't I just keep using it?

Otherwise, what's the best path to fix the `regular mode`?

**Comment by NiLuJe** [comment]
> Is there something wrong with `no framework` mode? Why don't I just keep using it?

Slightly longer boot time, and much longer exit time. There used to be missing features at one point, but I think everything's been fixed now.

> Otherwise, what's the best path to fix the regular mode?

Probably awesome being stopped is what's breaking it, like I mentioned earlier.

**Comment by mergen3107** [comment]
> Probably awesome being stopped is what's breaking it, like I mentioned earlier.

I am a little confused at the moment, while reading koreader.sh.
Isn't `awesome` also stopped in `no framework` startup?

**Comment by NiLuJe** [comment]
> Isn't `awesome` also stopped in `no framework` startup?

Nope, that's under the messy `STOP_FREAMEWORK` = "no"` branch ;).

**Comment by mergen3107** [comment]
"Oh, joy" (c) NiLuJe, 2023
:D 
Alright, let me see what I can do ...

**Comment by mergen3107** [comment]
> Slightly longer boot time, and much longer exit time.

Although, restarts from inside KOReader while in `no framework` are much faster now! Like, 4 seconds, instread of 8-10 in `regular mode`.

**Comment by NiLuJe** [comment]
Yeah, I'm assuming those lipc timeouts weren't helping ;p.

**Comment by mergen3107** [comment]
Why do need to stop `awesome` in the first place?

**Comment by mergen3107** [comment]
So, in that maga branch when `STOP_FRAMEWORK = no`, in the `if` statement where we kill awesome, I added this log:
```
                if [ "${FROM_KUAL}" = "yes" ]; then
                    logmsg "Stopping awesome . . ."
                    touch /mnt/us/awesomekill.log
                    echo "AWESOME ALIVE:" $(lipc-get-prop com.lab126.winmgr orientationLock) >> /mnt/us/awesomekill.log
                    killall -STOP awesome
                    AWESOME_STOPPED="yes"
                    echo "AWESOME DEAD:" $(lipc-get-prop com.lab126.winmgr orientationLock) >> /mnt/us/awesomekill.log
                fi
```

Can't we just export/extract what we need (in this case rotation thing) right before awesome is killed and pass through?

**Comment by mergen3107** [comment]
Logs yielded:
```
AWESOME ALIVE: R
AWESOME DEAD:
```
(so second response is empty, because I also didn't redirect `$2` anywhere...

**Comment by mergen3107** [comment]
Dead `awesome` only breaks the `lipc` call to get `com.lab126.winmgr` properites, other ones are OK:

https://github.com/koreader/koreader/blob/6527d7f1ab1845d56dea655f99cd675de44cb5da/frontend/device/kindle/device.lua#L89-L91

gives:
```
[root@kindle koreader]# echo $(lipc-get-prop com.lab126.blanket load)
langpicker blankwindow usb
```

**Comment by mergen3107** [comment]
So, here is the summary.
1) It works correctly with the snippet (https://github.com/koreader/koreader/issues/11144#issuecomment-1823863512)
When KOReader is started at the `D` upside-down orientation (wide frame on the right), KOReader starts up upside-down. Touch and screen are calibrated to each other, so it only takes a 90 deg rotation back and forth.

2) What's more insteresting, if I use KOL 1.4.2 (https://github.com/yparitcher/KUAL_Booklet/releases/tag/V1.4), KOReader even starts up in the same orientation! I don't even need to rotate 90 deg back and forth, touch and screen are good as well, gyro works too.

From here, two options to proceed:
A) I can make a PR that just adds that snippet to `KindleScribe:init` (plus comments about `no framework`), and we can add this to the User Guide as out official response.

or

B) If you guys can help me extract/export the `lipc-get-prop com.lab126.winmgr orientationLock` and then pass to `KindleScribe:init` directly, I could try that. I just don't know how `self.screen.native_rotation_mode = rotation_mode` would respond without `awesome` up - I think I tried it by hand before and it didn't work either. So, not really sure. I don't know how to `logger.dbg` the error code `2` (like in cmd, `$2 > log.txt`).

**Comment by mergen3107** [comment]
The thing I found is that upon exit from no-framework KOReader, Kindle itself doesn't show any screensavers when locking the screen.

**Comment by mergen3107** [comment]
Another time Home screen didn't show up at all upon exiting from no-framework KOReader. 

It is not ready yet

**Comment by NiLuJe** [comment]
> So I think we could just export the `orientation` parameter and pass it along to the `reader.lua`.

IIRC, it's not portable, which is why we can't do it outside of later, device-specific code blocks where we know it's supported ;).

**Comment by NiLuJe** [comment]
> IIRC, it's not portable, which is why we can't do it outside of later, device-specific code blocks where we know it's supported ;).

And you can just bracket what's needed between a couple of conditional SIGSTOP/SIGCONT, e.g., https://github.com/koreader/koreader/blob/d3787eee6495479d66f4452d75d7256a66d65d25/frontend/device/kindle/device.lua#L1341-L1343

**Comment by NiLuJe** [comment]
Because 

> it's not portable

And, as you saw, querying invalid lipc properties can do random unwanted things ;).

**Comment by mergen3107** [comment]
Alright, thank you for your patience and sorry for my annoyance :D

**Comment by mergen3107** [comment]
> but it seems like awesome didn't have time to wake up

Should we somehow ensure that awesome woke up?

This solution doesn't seem reliable in case if the code runs much faster (on newer CPUs, for example) it won't have time to wake up again. But on the other hand, I don't wanna hinder the whole bootup process just because to wait for awesome to wake up…

**Comment by NiLuJe** [comment]
That's... interesting. And, no, not really, signals are.... fun.

Short of sleeping for a bit, I don't really see a great way to handle that :s.
