### ISSUE TITLE
Q: User Patch for Aligning Text in Status Bar?

### ISSUE THREAD

**Issue by Bluemoondragon07** [koreader/koreader#11141]
I'm not sure if this is the right place to ask, but does anyone know how I might go about making a user patch to style the status bar? 
What I'm trying to do is align different elements of the status bar. For example, I'd like to have battery and time on the left, page number and book progress on the right.  I do not know Lua, but I do know CSS. Is there a way to manipulate the styling in a user patch?

Here is an example of the look I am trying to achieve with the status bar (the app is eReader Prestigio).
![](https://apollo.neocities.org/images/prestigio-notes2.png)

**Comment by hius07** [comment]
Before a userpatch, there is an element Custom text.
Filled with a bunch of spaces, it can produce a gap between groups of elements.

**Comment by Bluemoondragon07** [comment]
@hius07 Wow, thanks for the tip! That works perfectly!
