### ISSUE TITLE
OCR for other language too

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#11151]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently koreader can be used for english and chinese. it may be good if we use this feature for other languages too.

**Describe the solution you'd like**
OCR option can also select another language

**Additional context**
I see that Tesseract is for version 3, can we update that too?
Is there a specific problem?

**Comment by mergen3107** [comment]
https://github.com/koreader/koreader/issues/7860

**Comment by mergen3107** [comment]
Please attach crash.log here. 

Did you add the setting for English in the defaults.custom.lua?

Tesseract version 2?

**Comment by mergen3107** [comment]
I remembered I put explanation in the Wiki:

https://github.com/koreader/koreader/wiki/Dictionary-support#dictionary-lookups-in-scanned-pages
