### ISSUE TITLE
Directory defaults don't apply on a fresh book marked as finished

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11153]
* KOReader version: 2023.10-23
* Device: Kindle Scribe (5.16.2)

#### Issue
If you guys remember, long time ago I set up directory defaults for my manga directory: to page flip in the opposite direction. 

They work great for newly opened books (fresh or Reset in KOReader). 

#### Steps to reproduce

However, they don't apply if I mark a fresh book as finished and then open it. 

#### Context
The reason why I even discovered this is because I was in the middle of a manga (Volume 8/13) at the moment of my Boox-to-Scribe move. 

So, on Scribe I marked those first 7 Volumes as finished, then went back into them just to see how they look. Then I realized, the pages didn't advance in opposite direction, as I expect manga to do.

##### `crash.log` (will upload later if needed)

**Comment by hius07** [comment]
Maybe you have deleted old books settings (reset them), where the flip direction was set, then marked them as finished (this recreated the sdr file so directory settings became inapplicable).

**Comment by hius07** [comment]
> these Scribe CBZ files are completely new and they didn't have .sdr at all.
> I just marked them as finished first

They are not new anymore after you've marked them.



> 1. If there is a directory default, it should apply whenever docsettings are created.

It overwrites progress, highlights etc.

**Comment by mergen3107** [comment]
> It overwrites progress, highlights etc.

I see. Can it be changed so that it appends these directory defaults to current sdr instead of replacing them?

Or maybe at least provide user a notification when directory defaults cannot be applied because book was opened before. This might be useful when for example any other open book was moved into this folder with directory defaults. It tries to apply - and fails. And now it is up to user to apply these settings by hand. 

Also, can these settings be put into a profile? Like, can we create a button that takes all directory defaults and suggests to create a profile? One directory with defaults - one profile. 


This is absolutely not critical, but I am just trying to help fix UX to make it more obvious to the user of what's going on.

**Comment by hius07** [comment]
> can we create a button that takes all directory defaults and suggests to create a profile?

Put a new book to the directory, open it, go to Profiles, create New with current document settings.

**Comment by mergen3107** [comment]
Thanks @hius07 !

How about just a notification wtith `else` before line 124 in that snippet?
Like, if sdr is not there - create one with directory defaults (as it is now), but if not - notify with something like "There are a directory defaults that won't be applied to this book because is it now newly opened".

**Comment by Frenzie** [comment]
I'm not sure if I agree that directory defaults should retroactively apply, at least automatically.
