### ISSUE TITLE
FR: Improvements for Gesture Unlock and Screensavers

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11164]
**Does your feature request involve difficulty completing a task? Please describe.**
Unlocking bu selected gesture works really great!
However, I found that it could be improved in some areas.

**Describe the solution you'd like**
1) From KOReader-sleeping device, if I hit power button of open the magnet case, and don't do the gesture, the screen stays on, probably until KOReader's main sleep timer.
I think more feasible is to have it go back to sleep after 1 minute (or other option) - if the user is about to unlock, they would unlock it very soon after hitting power or opening the cover.
That way many phones and tablets act.

2) Now, in that position as in (1), if I now put device back to sleep (power button / cover), the notification popup stays. Can we please remove it back so that I can enjoy the screensaver again?

3) (not for the gesture unlock specifically, but I don't think it is worth a separate ticket)
There is a great option to have screensavers as random images from a folder.
Can we please have them as an image from the sorted list in a folder?

**Describe alternatives you've considered**
There is no alternative to KOReader! Ha-ha!

**Additional context**
Thank you guys! You rock! KOReader rocks! (I think I deciphered why the server was named this way...)

**Comment by mergen3107** [comment]
> 3\. I'm on pain meds

Ouch, get well soon! 

What I meant in 3 is Top menu - Gear - Screen - Screensaver - there as options to choose.
There is `Use random image from folder as screensaver`, whereas in 3 I was asking to have images from a folder, but in a sorted order (by name, for example).

**Comment by NiLuJe** [comment]
> whereas in 3 I was asking to have images from a folder, but in a sorted order (by name, for example).

Isn't there already an option to select an image manually?

Or did you mean making the "random" bit not really random somehow?

**Comment by mergen3107** [comment]
> Isn't there already an option to select an image manually?
Yes, there is, but it select only one image :D 
I'd like to have all images cycle through in a non-random order.

**Comment by NiLuJe** [comment]
Essentially like what the stock Kindle screensavers do, right.

(I imagine the random option currently picks a different image on *each* suspend, right?).

**Comment by mergen3107** [comment]
Yep!

**Comment by mergen3107** [comment]
> Essentially like what the stock Kindle screensavers do, right.

Thanks NiLuJe!
How about the non-random order of screensavers?

**Comment by NiLuJe** [comment]
> How about the non-random order of screensavers?

That one will have to wait for someone actually interested in it ;p.
