### ISSUE TITLE
"Info lists items per page" - hard limit, no settings in the settings.reader.lua

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11171]
* KOReader version: 2023.10-23
* Device: Kindle Scribe (5.16.2)

#### Issue
`Top menu (FM)` - `first tab` - `Settings` - `Info lists items per page`:
this value is not saved in the `settings.reader.lua`, and has hard limit of 24.

I was only able to find it via file search (line 405):
https://github.com/koreader/koreader/blob/6527d7f1ab1845d56dea655f99cd675de44cb5da/frontend/apps/filemanager/filemanagermenu.lua#L402-L406

#### Steps to reproduce
I changed the 24 to 30,
restarted KOReader,
changed the setting in the UI,
changed the limit back (to simulate update override),
restarted KOReader - the value and the settings stays the same :D 
That's all I neede.

I think it would be better if this value was in the `settings.reader.lua`.
Not critical at all.

Thanks!

**Comment by hius07** [comment]
I have this setting saved:
https://github.com/koreader/koreader/blob/dce12de09d4c4030954ce00e72f3986c89a2a932/frontend/apps/filemanager/filemanagermenu.lua#L415

**Comment by mergen3107** [comment]
Oh, interesting! Thanks! I'll have another look. I was looking for "info", "lists", but not "keyvalue_per_page" 😅

**Comment by mergen3107** [comment]
Yep, confirm:
```
    ["keyvalues_per_page"] = 30,
```
I set them up with the hack before, but this sting can just be added/modified. The limit does not enforce it. Fro example, I have `30` here, limit still is `24`, but unless I change it in the UI, it stays.
Thank you @hius07 !

**Comment by mergen3107** [comment]
Undoing my mess I did in https://github.com/koreader/koreader/issues/11186#issuecomment-1858616343

Let's continue here.

Here is how it looks when there 30 lines per page:
![FileManager_2023-12-16_130005](https://github.com/koreader/koreader/assets/6279855/ca7747df-381b-442e-9a99-aaf3f2dfd6cf)
