### ISSUE TITLE
Kindle: Wi-Fi toggle notification too quick

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11176]
* KOReader version: v2023.10-23
* Device: Kindle Scribe (5.16.2)

#### Issue
Wi-Fi toggle notification is very quick - I don't have a chance to read it.

#### Steps to reproduce
Open top menu, go to network, toggle Wi-Fi network.

See video (in the archive):
[crash_wifi_IMG_0307.zip](https://github.com/koreader/koreader/files/13493585/crash_wifi_IMG_0307.zip)

##### `crash.log` (if applicable)
Clean log with me starting KOReader and doing the things in the video:
[crash_wifi.log.txt](https://github.com/koreader/koreader/files/13493589/crash_wifi.log.txt)

Wi-Fi connection works otherwise - connects if Kindle was connected to it before in the Kindle menu.
However, it seems to me that something is wrong.

P.S. Is it still the case that we cannot select and connect to Wi-Fi networks from within KOReader?
Networks need to be first connected outside KOReader?

**Comment by Frenzie** [comment]
Related to #11126?

**Comment by mergen3107** [comment]
Oh! Probably, thanks!
I'll test it tomorrow in 2023.10-36. 

The fix appeared in -25, the one I currently have is -23.

**Comment by NiLuJe** [comment]
Nope, Kindle things. It's async, so it just says something to the effect of "Connecting", but it's gone as soon as the lipc call returns basically.

**Comment by mergen3107** [comment]
OK, thanks :D
