### ISSUE TITLE
What is wrong with this PDF?

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11187]
* KOReader version: v2023.10-37
* Device: Kindle Scribe (5.16.2)

#### PDF is very slow
It slow to open, flip pages, and even load up its cover in Mosaic view or Detailed list view.

What is fundamentally wrong with this file?

Is it just too heavy on images? If so, I could then process it in Foxit PhantomPDF to compress images.

Or is there a problem with how KOReader tries to address the file?
Here is log of me opening KOReader in this PDF, then quitting to FM, then resetting the cache and docsettings so it can load up the cover and then opening it, and then flipping through pages. Archive also includes the fresh docsettings.
[cyberbug.zip](https://github.com/koreader/koreader/files/13520319/cyberbug.zip)

The file itself (too large for GH): https://disk.yandex.com/d/WabNTwA2d7XMjg

**Comment by mergen3107** [comment]
I mean, Kindle Scribe is a monster: it munches through 600 MB CBZ waifu2x-upsacled and dithered manga, but not with with 60 MB PDF lol.

**Comment by Frenzie** [comment]
Probably some combination of layers and compression algorithms.

**Comment by offset-torque** [comment]
That PDF has very good compression (also 8 megapixel images). When exported to JPG, same images take around 500 MB. And that much decompression needs lots of CPU time as you can guess. Just importing it to LibreOffice used more than 7 GB of RAM. I think this is the heaviest PDF I have ever seen.

**Comment by mergen3107** [comment]
Wow, 7 GB! 
Thank you guys,
I will definitely take some tome optimizing it :D 
It also shows how greatlyKOReader is optimized on memory, what a champion!

**Comment by mergen3107** [comment]
@jonnyl2 
FoxitPhantomPDF, the same one I used to try to optimize it. 

The size is now 150 MB, but the processing times are 10 times smaller, because all images are pre-processed. 

For manga, this is moderately large size, but I didn't have any problems even with 500 MB manga recently, not difference in speed!
