### ISSUE TITLE
FR: Mediatek Kindles - page animation direction

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11180]
**Does your feature request involve difficulty completing a task? Please describe.**
Is the animation direction on Mtk Kindles configurable?
I feel like the current one "looks like" it is swiping to previous page.
What I mean is:
1) I swipe from right to left (RTL) to advance to the next page.
2) Animation kicks in the opposite, LTR, direction.
So you start the swipe on the left, then go the right and stop there. Then animation starts from that side and goes to the opposite side. It feels unnatural, to say the least.

**Describe the solution you'd like**
Animation needs to follow correspoding direction:
For regular books:
animation from right to left in page forward;
animation from left to right in page backward.

For books where pages are flipped in reverse (manga, RTL languages):
the opposite animation directions.

**Describe alternatives you've considered**
I just disable it for now, it does not distinguish between forward and backward page flips.
This makes me double check whether I am on the right page way too many times.

**Additional context**
Otherwise the text looks great even with this animation! I don't know what lab126 have done with the hw/sw integration, but Kindle Scribe is the faster eink screen I've even seen yet.

**Comment by NiLuJe** [comment]
Behaves as expected in all orientations over here on a PW5, FWIW.

When in doubt, either check on pages with images, as it makes the fade roll more obvious, or tweak the amount of steps to a larger value, to, again, make the roll more obvious.

https://github.com/koreader/koreader-base/blob/f252e58a361c783c93a66d87607949dd0caea3f9/ffi/framebuffer_mxcfb.lua#L901-L902

**Comment by mergen3107** [comment]
> paging forward should animate from right to left?

That's what I would expect, as if following behind the swipe right-to-left. 

Interesting, I am sure I tested it in both auto-orientations. I'll test again with KOReader exits in between. 

Thanks!

**Comment by mergen3107** [comment]
PW5 doesn't have gyroscope, does it?

**Comment by mergen3107** [comment]
Alright, so this issue only happens when I start KOReader in `D` orientation (upside-down portrait).

Previously, I tested orientation U/D, but I forgot that all those were after I started KOReader in `D`.

Can I solve this somehow?

**Comment by mergen3107** [comment]
How is this `forward` defined?
Maybe I should add it to the `KindleScribe:Init()` to be `forward = not forward` or something?

**Comment by yparitcher** [comment]
It is awhile since i did this, but we convert the koreader rotation to a native framebuffer rotation here: https://github.com/koreader/koreader-base/blob/f252e58a361c783c93a66d87607949dd0caea3f9/ffi/framebuffer_mxcfb.lua#L605-L628

It probably requires adding some sort of rotation factor at init (based on what direction koreader started in), and then adding that to the rotation here, to get the correct swipe direction

**Comment by mergen3107** [comment]
Thank you @yparitcher !

**Comment by mergen3107** [comment]
Please correct me if I am wrong, but Kindle Scribe seems to be the only device affected by this issue so far, because both of these conditions must be met at the same time:
1) It needs to be MTK SOC Kindle: Kindle PW5, Kindle Scribe
2) It must have gyroscope: All Kindle Oases, Kindle Scribe.

SO, I can proceed by adding stuff only in the `Device:init()` for Kindle Scribe only?
I don't have any other devices to test anyway.

**Comment by mergen3107** [comment]
I enabled framebuffer logs
https://github.com/koreader/koreader-base/blob/f252e58a361c783c93a66d87607949dd0caea3f9/ffi/framebuffer_mxcfb.lua#L626

and did some tests.

D - wide frame on the right
U - wide frame on the left

Fresh started in "U":
When turning pages in "U":
12/24/23-22:13:07 DEBUG MTK Rota: 0 Swipe: 3 Comp: 3
When turning pages in "D":
12/24/23-22:13:30 DEBUG MTK Rota: 2 Swipe: 3 Comp: 3
All animations (if device is flipped to U/D) are correct if KOReader is freshly started in `U` orientation.

Fresh started in "D":
When turning pages in "D":
12/24/23-22:14:58 DEBUG MTK Rota: 2 Swipe: 3 Comp: 3
When turning pages in "U":
12/24/23-22:15:41 DEBUG MTK Rota: 0 Swipe: 2 Comp: 2
All animations (if device is flipped to U/D) are in reverse, if KOReader is freshly started in `D` orientation.

So, my next step is to add `swipe_direction` variables here, right?
https://github.com/koreader/koreader/blob/9ba66ac382ab8778978d075d0de15b73617de49b/frontend/device/kindle/device.lua#L1335-L1361

**Comment by mergen3107** [comment]
I need to redo the tests, I am afraid I used both forward and backward page turns.
I'll redo only forward page turns.

**Comment by mergen3107** [comment]
OK, updated tests. Now they show correctly, swipe directions when starting in `U` and `D` are "mirrored" with respect to each other.

**Comment by mergen3107** [comment]
I think I found a solution.

If the device was started in `D`, I need to rotate `swipe_direction` by 180 deg before any manipulations with it.

After this modification, I tested all other in-KOReader rotations - swipe direction for animation rotates accordingly (I tested all four).

So, the framebuffer part is then:
```
function framebuffer:_MTK_SetSwipeDirection(left)
    local swipe_direction = left and C.MTK_SWIPE_LEFT or C.MTK_SWIPE_RIGHT

    -- If device was started in D orientation, rotate swipe_direction by 180 deg.
    if self.native_rotation_mode == self.DEVICE_ROTATED_UPSIDE_DOWN then
        swipe_direction = bxor(swipe_direction, 1)
    end
    -- Account for KOReader rotation not matching the FB rotation with some bit trickery.
    -- Alternatively here is a LUT:
    -- local lut = { -- L R D U
    --                { 2,3,0,1},
    --                { 0,1,3,2},
    --                { 3,2,1,0},
    --                { 1,0,2,3}
    --             }
    -- swipe_direction = lut[self.cur_rotation_mode][swipe_direction]
    local rota = self.cur_rotation_mode
    if rota ~= self.DEVICE_ROTATED_UPRIGHT then
        if rota == self.DEVICE_ROTATED_UPSIDE_DOWN then
            swipe_direction = bxor(swipe_direction, 1)
        elseif bor(swipe_direction, 1) == bor(rota, 1) then
            swipe_direction = bxor(swipe_direction, 3)
        else
            swipe_direction = bxor(swipe_direction, 2)
        end
    end
    self.debug("MTK Rota:", rota, "Swipe:", swipe_direction, "Comp:", swipe_direction)
    self.update_data.swipe_data.direction = swipe_direction
end
```

Can I proceed with a PR? Is this acceptable?
Or should I do this somewhere else once, because this one is calculated upon each page turn?

**Comment by NiLuJe** [comment]
That sounds much more sensible that way to me, yeah ;).

**Comment by mergen3107** [comment]
This must be done from the koreader-base rather than koreader, right?

**Comment by yparitcher** [comment]
Might it not be better to force the device into `U` mode via lipc/fbdepth in `koreader.sh` (and restore on exit) like we do for kobo, and kill a bunch of birds with one stone?

**Comment by mergen3107** [comment]
#11265
#11269
I'd like to have KOReader adjust and show up in whatever orientation Kindle is in right now instead :D

**Comment by yparitcher** [comment]
Yes, in koreader.sh export the current orientation. Then use lipc to reset to `U` (portrait). Then in device init in lua (set the current rotation (native_rotation) based on the original), and at exit in lua or koreader.sh use lipc to reset the orientation to either the original/or to match the users current rotation.

As if you are anyway going to tweak the rotation based on the kindle rotation we might as well reset the fb to U sk as not to need any workarounds in koreader (touch, etc) only once at startup, and once at the end.

**Comment by mergen3107** [comment]
Thanks! I see your point, this indeed might be simpler. Let me try :D

**Comment by mergen3107** [comment]
> Then use lipc to reset to `U` (portrait).

My problem at the moment is that I cannot force Kindle to rotate via commands.
`lipc-set-prop com.lab126.winmgr orientationLock U` only updates `orientationLock`, orientation stays the same (outside KOReader).
`lipc-set-prop com.lab126.winmgr accelerometer U` says it is not permitted.

**Comment by yparitcher** [comment]
Yes, but do the page turns etc rely on the accelerometer orientation or on `orientationLock`?

**Comment by yparitcher** [comment]
Setting orientationLock might be enough to tell the kindle system to ignore the accelerometer for while we start up koreader.

**Comment by mergen3107** [comment]
> Yes, but do the page turns etc rely on the accelerometer orientation or on `orientationLock`?

They rely on the accelerometer. From `Kindle:init()`:
```
local orientation_code = lipc_handle:get_string_property(
                "com.lab126.winmgr", "accelerometer")
```
Another of the puzzle is this part in the generic `Device:init`:
https://github.com/koreader/koreader/blob/b949d07f4fbf7ffb0a145684f98f196bb0492aea/frontend/device/generic/device.lua#L265-L271

So I tried this:
1) In `koreader.sh`, store current accelerometer value (testing in `D` as most problematic).
2) Then set `orientationLock` to `U`.
3) Then `Kindle:init()`, it still gets the `D` from accelerometer to rotate fb (otherwise, it is back to the old issue).
4) Comment out the snippet above in generic part. Without this change, touch and rendering are opposite again.
5) However, swipe animations are still mirror if started in `D`.

**Comment by mergen3107** [comment]
For now, I reverted back to what I had in https://github.com/koreader/koreader/issues/11180#issuecomment-1869083861

**Comment by mergen3107** [comment]
@yparitcher 
I was able to find another solution, without changing the framebuffer.lua.
https://github.com/koreader/koreader/blob/b949d07f4fbf7ffb0a145684f98f196bb0492aea/frontend/apps/reader/modules/readerview.lua#L973-L979
Here is added
```
if Device.native_rotation_mode == self.DEVICE_ROTATED_UPSIDE_DOWN then forward = not forward end
```

and now it works the same!
Do you think this is better?

Since this is in the common `readerview.lua`, should I guard it with more checks (Kindle+Gyro or Scribe)?

**Comment by NiLuJe** [comment]
Nope, I'd much rather the platform-specific fix be inside the actually platform-specific code ;).

**Comment by mergen3107** [comment]
OK! Framebuffer fix is the best one so far then, though not perfect.

**Comment by mergen3107** [comment]
Hacky fix above is working, but otherwise that's a minor issue.
I got a new case that virtually forces me to stick to `U` orientation all the time, so I rarely fire up KOReader in `D`.
