### ISSUE TITLE
FR: History/Favorites - option to remember page number when opening a book

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11186]
**Does your feature request involve difficulty completing a task? Please describe.**
Can you please make History/Favorites remember what page I was in when a book is opened from it

**Describe the solution you'd like**
For example, I have 8 pages of 3x3 grids of books in "Finished" category of History. 

I go through books one by one (#11185), but each time I open the next book I need to swipe until I get to the same page in History. 

**Describe alternatives you've considered**
Viewing them in Detailed lists helps,since more items can be, but I really like History being in Mosaic views.

**Additional context**
Speaking of fitting more content, is there a way to adjust the grid size in History/Favorites? 
3x3 is great for small screen sizes (6-7 inch), but on 10 inch it looks ridiculously large.

4x4 or 5x5 might be a better suit. 

Thank you!

**Comment by mergen3107** [comment]
Another good option is to tap the page number and enter there, but this is:
1) tap page number
2) enter digits
3) tap OK. 

Instead, doing three swipes I get to Page 4, so it doesn't much time. 

Also, since there are only a dozen pages and swiping works both ways (I can get to last page from the first one), it is not too bad. 

Having this option to remember current page is just a nice to have.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/dce12de09d4c4030954ce00e72f3986c89a2a932/plugins/coverbrowser.koplugin/mosaicmenu.lua#L862-L869

**Comment by mergen3107** [comment]
I double clicked `nb_cols_portrait` in the code and it led me to there.

**Comment by hius07** [comment]
Thanks author it's simple.
```Lua
local FileChooser = require("ui/widget/filechooser")
FileChooser.nb_cols_portrait = 4
```

**Comment by mergen3107** [comment]
Thanks! Where should I put these?
I tried putting them inside and outside the `function MosaicMenu:_recalculateDimen()`. Didn't work.

Also didn't work uncommenting the lines in `main.lua`.

**Comment by hius07** [comment]
It's a userpatch.

**Comment by mergen3107** [comment]
This patch works great in FM!
Can't wait to see it in History/Favorites :D

**Comment by mergen3107** [comment]
I think I solved it!
Let me make a PR and you guys can blame me it is not optimized xD

**Comment by mergen3107** [comment]
Thank you @poire-z for chiming in and suggesting a very nice and elegant solution!

I put all the files I mentioned in the PR back to stock and then edited the user patch ``:
```
-- Tweak these numbers of rows and columns for Mosaic mode in History/Favorites and Filemanager.
local Menu = require("ui/widget/menu")
Menu.nb_cols_portrait = 4
Menu.nb_rows_portrait = 5
Menu.nb_cols_landscape = 5
Menu.nb_rows_landscape = 4
```

This is how it looks like (_c'est magnifique!_):

Portrait (4x5):
![Reader_2023-12-03_002120](https://github.com/koreader/koreader/assets/6279855/2ceb5c89-28eb-41ca-80e0-7c1b5f2a609d)

Landscape (5x4):
![Reader_2023-12-03_002136](https://github.com/koreader/koreader/assets/6279855/4b9ddac0-ee82-48ac-b518-86c56ed414e3)

The same user-patch for those interested as well (remove .txt):
[2-mosaic-mode-grid.lua.txt](https://github.com/koreader/koreader/files/13539709/2-mosaic-mode-grid.lua.txt)

**Comment by mergen3107** [comment]
Thank you very much everyone! That was a lot of fun and learning :)

**Comment by mergen3107** [comment]
I tweaked it so now I have 20 covers per page instead of 9 before, which made my 14 pages of History only 7 pages!
I also made it the same number of row*columns both in portrait and landscape for consistency.

**Comment by hius07** [comment]
Coming soon

![1](https://github.com/koreader/koreader/assets/62179190/bf76d680-ccb7-4a9d-b26d-feb210cd8466)

**Comment by mergen3107** [comment]
Thank you @hius07 !
Do you think it is worth increasing the limit of Info list items per page as well? #11171

**Comment by hius07** [comment]
You are the master of big screens, tell me the limits.

**Comment by mergen3107** [comment]
Alright, I'll test something and come up with some numbers :D 
I was also thinking to maybe make this limit calculable depending on the screen size and dpi?

**Comment by mergen3107** [comment]
Here is some background math, for now.
This is to calculate the max number of items per page in Info lists to something reasonable based on screen properties.

There are 72 points/inch, which is 28 points/cm.

To get points, pt = px * 72 / dpi, where px is the height in pixels. This converts the screen to physical dimension.

Let’s say, we would like to limit each row height to 20 pt, which is 0.7 cm. Anything smaller starts to get really hard to read, especially in landscape.

For Kindle Scribe, px = 2480, dpi = 300, then pt = 595.20, which is 29.76 rows.

For Onyx Boox Kon-Tiki 2, px = 1872, dpi = 300, then pt = 449.3, which is 22.46 rows. 

For Kobo Ellipsa, px = 1872, dpi = 227, then pt = 593.76, which is 29.69 rows. 

We can take math.ceiling on these to get 30 rows, 23 rows, and 30 rows, respectively. 

I am currently using 30 rows.

Do you guys think this is a reasonable scale?
If so, I’ll try to implement it in the code :D 

@hius07 @NiLuJe @poire-z

**Comment by poire-z** [comment]
> If so, I’ll try to implement it in the code :D

Looks like @hius07 has already done it, as he shared a screenshot.

> Let’s say, we would like to limit each row height to 20 pt, which is 0.7 cm. Anything smaller starts to get really hard to read, especially in landscape.

Don't forget about text covers. I'm sure among your 30 x 23 thumbnails, there will be one without a cover image :) And we have a minimal font size for text, so you'll need some reasonable size to display something. I also don't know how truncation works in such extreem cases.

Plus, for text covers, we start from some regular big reasonable size, and see if text fit untruncated, and if not, we reduce the size and try again and repeat until it fits. So, you may do a lot more computation with small thumbnails, and even displaying 10x10 of them, you will feel this slowdown.
So, there may be more maths to find out the upper font size to start from...

Plus, if you think it's needed, the need to keep track of the geometry in the "M" tags, so thumbnails get refreshed to the final size when you tweak Cols and Rows. (I don't think I cared about the fact that the size change when one switch from portrait to landscape.)

**Comment by mergen3107** [comment]
@poire-z 
Sorry, I mixed everything up in one ticket xD
I meant number of rows of text in Info lists, like System Statistics or Reading stats for a book.

**Comment by mergen3107** [comment]
C.f., #11171 where I just overwritten the value in the settings.reader.lua by hand to 30, although the limit in the Spin Widget is less than that.

**Comment by mergen3107** [comment]
> Waiting for @mergen3107 with big screen limits.

I can't find these settings in the `settings.reader.lua`, do you think we should put them there?

Meanwhile, let me try some extremes by setting grids in the code...

**Comment by mergen3107** [comment]
User Patch deprecated, superseeded by #11232
