### ISSUE TITLE
Q: Kindles with light sensor

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11205]
Hey guys,

Just wondering how hard would it be to implement auto-brightness based on light sensor (on Kindle Scribe, PW5 Signature, Oasis, others)?

Is it at all possible, or it is turned off along with something being turned off during KOReader startup?

Thanks!

P.S. The idea comes from my great experience of using the auto warmth widget, based on location coordinates. This one works really nicely, I don't remember when I tweaked warmth by hand last time.

Many times in darkness I forget how bright even 12/24 is, and blast my eyes with the bright screen :D

**Comment by NiLuJe** [comment]
No idea, no clue how any of it works.

**Comment by NiLuJe** [comment]
Just remembered that there *is* actually something that already does... *something* with the ALS: https://github.com/koreader/koreader/blob/master/plugins/autofrontlight.koplugin/main.lua

This should *probably* be using a proper Device cap check instead of a hardcoded list of devices ;).

**Comment by mergen3107** [comment]
Thanks @NiLuJe !
I added `KindleScribe` in the device check and it let me enable it.

However, it's functionality is rather limited:
```
https://github.com/koreader/koreader/blob/3c63a5d8a80724506b39fcbf64a16895cb903501/frontend/device/kindle/device.lua#L408-L421
```

I'll see if I can tie these values to scale brightness level, not just toggle it.

**Comment by mergen3107** [comment]
(stupid GH UI :D, sorry)

**Comment by mergen3107** [comment]
It seems that Kindle’s native `Auto-brightness` works through launched KOReader, although in a peculiar way. 

Tested with a bright flashlight.

1) There are two light sensor locations along the wide edge, I still don’t fully understand which one takes precedence when deciding for the light adjustment - both seem to work :D 
2) When I direct the bright flash light to one of them, screen light goes down considerably. 
3) When I then remove it, screen light goes back up, but only up to KOReader’s current setting, wherever it is (e.g., 12 or 20 - it goes back to either at the same lighting conditions in the room, this seemed strange to me).

My main goal from this feature was to reduce front light intensity in very bright light to preserve power (like outdoors), and resume it when I go back into darker environment. 
So, for my case this works great and I don’t use Autofrontlight plugin anyway.

Closing for now, please feel free to reopen if someone needs finer controls in future.

**Comment by mergen3107** [comment]
P.S. When screen light goes down in (2) above, KOReader doesn’t show what level it went down to, which is fine by me with these requirements.
