### ISSUE TITLE
Kindle Basic 11th Gen fails to launch KoReader

### ISSUE THREAD

**Issue by ExoticMarbles** [koreader/koreader#11202]
* KOReader version: v2023.10
* Device: Kindle Basic 11th Generation (Serial Prefix G092)

#### Issue 
KOReader fails to launch, Kindle FW 5.16.2.1.1
I'm no expert, but it fails to resolve a path to the touch input device (I think? I have no idea, Windows is more my thing).
I'm assuming there just isn't a case for handling this particular device, and I wasn't comfortable just editing the paths myself, becuase, again, I have no idea what I'm doing, haha.

#### Steps to reproduce
- Jailbreak Kindle 11th Gen via LanguageBreak 16.11.23, En-US hotfix
- Install MRPI, KUAL (coplate), KoReader PW2 edition v2023.10
- Launch KoReader (regular mode) via KUAL 

##### crash.log
<details>
  <summary>crash.log</summary>

```
 [*] Current time: 12/05/23-17:44:54
 [*] Version: v2023.10

ffi.load: libs/libutf8proc.so.2
ffi.load: blitbuffer
ffi.load: sqlite3
12/05/23-17:44:55 INFO  initializing for device KindleBasic4 
12/05/23-17:44:55 INFO  framebuffer resolution: {
  h = 1448,
  w = 1072
} --[[table: 0xb6d12ff8]] 
./luajit: frontend/device/kindle/device.lua:1285: Error opening input device </dev/input/by-path/platform-1001e000.i2c-event>: No such file or directory
stack traceback:
	[C]: in function 'open'
	frontend/device/kindle/device.lua:1285: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x00013ebd
```
</details>

**Comment by mergen3107** [comment]
We need the result of the command `ls /dev/input/by-path/`

**Comment by ExoticMarbles** [comment]
> We need the result of the command `ls /dev/input/by-path/`

God, I knew I forgot to put something in my report. 'pologies.

`platform-10019000.i2c-platform-gpio-keys.7.auto-event`

**Comment by hius07** [comment]
Unfinished jailbreak.

**Comment by ExoticMarbles** [comment]
😮‍💨 God, please, are you sure? Everything else is working, and I've re-installed several times :(

**Comment by hius07** [comment]
Try to reinstall the latest hotfix from https://www.mobileread.com/forums/showthread.php?t=225030.

**Comment by ExoticMarbles** [comment]
No dice, unfortunately.

**Comment by hius07** [comment]
Can you try the latest nightly build
https://build.koreader.rocks/download/nightly/v2023.10-44-g3c63a5d8a_2023-12-04/

**Comment by mergen3107** [comment]
Yeah, I forgot there had to be a fix for new Kindle Basic :D

**Comment by ExoticMarbles** [comment]
Thanks you all! :D The nightly build works! I was gonna just stick to stock amazon software if I had to re-install a jailbreak again, haha.

I'm not very familiar with GitHub etiquette, do I close this now or is it closed when it's fixed in the next update?

**Comment by Frenzie** [comment]
Auto-closing only happens from PRs, but keeping a non-issue open would be distracting at best. ^^

**Comment by rybi** [comment]
I had the same issue with the LanguageBreak jailbreak, but reinstalling the latest hotfix helped. Thanks!

> Try to reinstall the latest hotfix from https://www.mobileread.com/forums/showthread.php?t=225030.

**Comment by Victor-EEE** [comment]
> Can you try the latest nightly build https://build.koreader.rocks/download/nightly/v2023.10-44-g3c63a5d8a_2023-12-04/


Thank you so much, this one really helped!

I tried for such a long time to fix possible issues with the jailbreak (Kindle 11), Kual- and Koreader installation, and finally this one worked without any troubles! 

👍👍👍✌️✌️✌️🙏🙏🙏
