### ISSUE TITLE
FR: Frozen statistics - do not create if "new" finished book is opened

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11201]
**Does your feature request involve difficulty completing a task? Please describe.**
I copied a bunch of books I read before just for collection. In KOReader I marked those as Finished from FM.
Then I opened them, played around, was happy to see old books in new environment. 

However, when I went to Statistics, those books were all having 00:00 time read.

**Describe the solution you'd like**
Can we please not add those books to statistics at all if there was no entry in statistics before? By "those" I mean Finished books that properly have statistics frozen. 

**Describe alternatives you've considered**
For now I just go and delete statistics for books < 5 min.

**Additional context**
KOReader has become my and my family's number-one reading and librarian app throughout these five years since my old PW3, and across so many devices. I really like how Reading Statistics works overall, so thank you everyone who made it!

**Comment by hius07** [comment]
Agree, if "Freeze statistics of finished books" is checked and the book is marked as finished, it should not be added to the statistics db.

**Comment by poire-z** [comment]
What's with all these closings ?
It's not because there's been no immediate discussion that they should be "not planned". And this one looks like it was agreed on :/

**Comment by mergen3107** [comment]
I closed all my old tickets as they are not really that important to be honest. It is just me nitpicking.

Please feel free to reopen.

**Comment by mergen3107** [comment]
@hius07 
Should this condition be added here?
https://github.com/koreader/koreader/blob/f3305932335dd109a1d86bce45a1a307465dca83/plugins/statistics.koplugin/main.lua#L169-L173

"Condition" being "finished book" + "Freeze statistics of finished books (enabled)"

**Comment by mergen3107** [comment]
Correction: condition needs to be also with "book never opened"
https://github.com/koreader/koreader/blob/f3305932335dd109a1d86bce45a1a307465dca83/plugins/statistics.koplugin/main.lua#L919-L922

Added here?

**Comment by mergen3107** [comment]
How to check for "book never opened"?

**Comment by hius07** [comment]
> How to check for "book never opened"?

`not self.id_curr_book`

**Comment by mergen3107** [comment]
Thanks @hius07 
Do if statements honor parentheses?

For example, can I do
if (a and b) or (c and) ,
where I need either both a and b or both c and d to be true?

**Comment by Frenzie** [comment]
Yes, that's how that works.

**Comment by mergen3107** [comment]
So I tried adding ` or not (self.id_curr_book and self.is_doc_not_finished)` in the insertDB I showed above, but it didn't work. Plugin starts, but it still adds an entry with 00:00:00 for a finished but fresh book.

I tried to add it to https://github.com/koreader/koreader/blob/f3305932335dd109a1d86bce45a1a307465dca83/plugins/statistics.koplugin/main.lua#L103-L106

but resuts is much wors, plugin didn't start at all:

```
06/06/24-22:36:40 ERROR failed to call event handler onPageUpdate plugins/statistics.koplugin/main.lua:207: attempt to index field 'settings' (a nil value) 
06/06/24-22:36:40 ERROR failed to call event handler onReaderReady plugins/statistics.koplugin/main.lua:1012: attempt to index field 'settings' (a nil value) 
```

**Comment by hius07** [comment]
Cannot test at the moment (no electricity, russia destroyed generation).
You can try:
add `if not self.id_curr_book then return end` after
https://github.com/koreader/koreader/blob/81d2db150f24118f3dfb31510c7568b6a80f2f72/plugins/statistics.koplugin/main.lua#L191
and `and self.is_doc_not_frozen` in
https://github.com/koreader/koreader/blob/81d2db150f24118f3dfb31510c7568b6a80f2f72/plugins/statistics.koplugin/main.lua#L761
