### ISSUE TITLE
Calibre metadata search: crash

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#11215]
* KOReader version: 2023.10
* Device: Pocketbook Era

#### Issue
Clicking on an entry in the search results list leads to a crash.

#### Steps to reproduce
Calibre metadata search -> Enter search text -> Click on an entry in the search results list

[crash.log](https://github.com/koreader/koreader/files/13627476/crash.log)

**Comment by NiLuJe** [comment]
`./luajit: not enough memory`

**Comment by NiLuJe** [comment]
How large is your calibre library?

**Comment by NiLuJe** [comment]
(c.f., #7800, #7159 & #9016 for context).
