### ISSUE TITLE
Launching KOReader on PW3 from KUAL goes home, white window flashes on screen, then home screen again

### ISSUE THREAD

**Issue by spaghettiScreen** [koreader/koreader#11213]
I just rooted my Kindle PW3 using [LanguageBreak](https://github.com/notmarek/LanguageBreak). (The jail breaking process did not go smoothly, so I'm kind of wondering whether this might have something to do with it).

I installed KUAL, it seems to work correctly. I then followed the instructions to install KOReader. I copied the contents of `koreader-kindlepw2-v2023.10.zip` to the kindle root when plugged in to my computer. 

When I open KUAL from my library on the Kindle, KOReader shows up as one of the options. I select **KOReader** > **Start KOReader**, and the following happens. 

1. I get taken to the home screen 
2. A blank white application appears on screen for less than a second
3. The white application disappears and I'm back at the home screen again

I also tried **KOReader** > **Start KOReader (no framework)** (goes home, but white window doesn't flash on screen),  **KOReader** > **Start KOReader (ASAP)** (exact same behaviour as **Start KOReader**, white window flashes up).

If this looks like a crash that is occurring here, I'd be happy to look at/provide logs, but I'm not sure how to access them.

**Comment by spaghettiScreen** [comment]
Thank you! I had already installed the LanguageBreak hotfix, but installing the hotfix from [here](https://www.mobileread.com/forums/showthread.php?t=225030) fixed the issue, KOReader opens now!

Again, tyvm :)

**Comment by sandroborg** [comment]
> > this might have something to do with it
> 
> Highly likely.
> 
> Install the latest hotfix snapshot (yes, even if you installed Marek's already), then reboot your device and try again.

This worked for me as well. Didn't have the mkk folder, so probably the hotfix did not apply. Re-did the hotfix, but the NiLuJe's one this time and koreader started.
