### ISSUE TITLE
"Page %1 of %2" not displayed in full

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11222]
* KOReader version: 2023.10-50
* Device: PocketBook Touch Lux 5

#### Issue
In the "Filter words from books" window the indication "Page %1 of %2" is not displayed in full in Greek and I think the same happens in other languages as well. The same problem happens in other similar windows, when there are the tick and cancel symbols.
One solution could perhaps be to put a slash instead of the word "of" and thus have "Page %1 / %2" but: a) I am not sure that it would work and b) the same phrase is used in other cases, where there are not the tick and cancel symbols and it would be a pity to change it.
I think the problem could be solved if the arrows and the tick and cancel symbols were placed closer to the edge.

![FileManager_2023-12-10_114936 (Medium)](https://github.com/koreader/koreader/assets/76203123/ca2e3e92-3c1d-473e-b1f9-ba5d5b2b2b36)

**Comment by Frenzie** [comment]
Given the screenshot I'd imagine it's also cut off in English?

**Comment by hius07** [comment]
![4](https://github.com/koreader/koreader/assets/62179190/85979e65-0f3a-49fc-b1b2-868385e450b0)

**Comment by Frenzie** [comment]
I'm not sure if that's the same width on mobile, but either way it doesn't say 15 of at least 15. :-)

**Comment by hius07** [comment]
![5](https://github.com/koreader/koreader/assets/62179190/f03c324d-35b1-439b-ab07-0f264c6b9db6)

**Comment by hius07** [comment]
Change the wording or change the width of the buttons.

**Comment by poire-z** [comment]
Or truncate on the left (assuming 12 of 23 is at the end on the wording in most languages), so we see `...ge 12 of 23`.
Or rebuild the sort widget so that the width of the buttons are computed from the remaining width after the full text is rendered untrucated. But then, the button positions may change when we cross 9 to 10 or 99 to 100.

**Comment by NiLuJe** [comment]
Or cheap out: `%1 / %2`

**Comment by Frenzie** [comment]
Sounds fine to me.
