### ISSUE TITLE
FR: Kindle - Gestures - Equal steps for warmth

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11220]
**Does your feature request involve difficulty completing a task? Please describe.**
Can we please have an option to increment frontlight warmth by a fixed and equal amount?

Currently, "Decrease warmth by 1" is doing 5%, "Increase warmth by 1" is doing 4%. 

I understand that this might because of the ceiling/floor roundings, and because there are 24 levels in Kindle, and 100/24 = 4.16 :D 

However it is very distracting when I want to compare before and after of the screen warmth by swiping up and down the right edge. 

Currently I am just using a gesture to call the whole frontlight dialog.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/aabd6d7a2602e75d7e12d4d8e48f291f7e11275e/frontend/device/devicelistener.lua#L162

**Comment by mergen3107** [comment]
Thanks @hius07 !
Can I user patch it?
I am thinking to make like "if int > 0, then use ceiling, if int < 0 use floor".

**Comment by mergen3107** [comment]
Also, why warmth is so much different than intensity (Line 123)? Intensity is very nice in gestures, because it can be changed by fixed amount. Although it is not normalized against 100.

**Comment by hius07** [comment]
Sorry, cannot say anything about the warmth, got no device.

**Comment by NiLuJe** [comment]
Because intensity is always normalized to a [0, 100] scale, while warmth isn't, and the range of that scale varies wildly across platforms.

**Comment by mergen3107** [comment]
More standards - more frustration!

Can I make a user patch to override it to have a common fixed percentage value up and down?

**Comment by mergen3107** [comment]
Or just two new dispatcher items that replicate what + and - buttons currently do in the frontlight dialog?

**Comment by NiLuJe** [comment]
The Dispatcher gesture should arguably be using a different codepath than the distance based swipe gesture, yeah, where whatever amount is set in the gesture manager is the actual amount of device-specific steps.

This is mostly irrelevant on Kobo because there are ten steps, so 1 does indeed do 1 step ;p.

**Comment by mergen3107** [comment]
It is a little tough. 
Intensity's gesture is nice, that unit = 1/24 levels. If 0 is set, then the swipe amount kicks in.

Warmth's gesture cannot be set to 0. It's unit is the scale of the swipe gesture. So "1" gives 4-5% per "unit of gesture", "2" gives 9-10%, and so on...

**Comment by mergen3107** [comment]
> If 0 is set, then the swipe amount kicks in.

Sorry, I retract. That must have been something else. Intensity doesn't go to 0. It can go to 24 max, whereas warmth goes to 100 max, but it is deceptive. `1` does either 4% or 5%, depending on the direction.

**Comment by hius07** [comment]
> Warmth's gesture cannot be set to 0.

https://github.com/koreader/koreader/blob/fe02b83b6adebb066c2a1093d0100451f4a8f54f/frontend/dispatcher.lua#L101
Set `min=0` in this (and next) line, the same for the warmth.

**Comment by NiLuJe** [comment]
IIRC, it's very much on purpose for the intensity, to avoid mishaps when doing this in the dark (i.e., not allowing to actually turn the fl off).

Talking about the `absolutenumber` actions here; for the `incrementalnumber` ones, I was assuming that the min value only affects the actual increment value, not whatever the absolute value ultimately ends up as?

**Comment by hius07** [comment]
> for the `incrementalnumber` ones, I was assuming that the min value only affects the actual increment value

0 means "gesture distance", right?

**Comment by mergen3107** [comment]
> > Warmth's gesture cannot be set to 0.
> 
> 
> 
> https://github.com/koreader/koreader/blob/fe02b83b6adebb066c2a1093d0100451f4a8f54f/frontend/dispatcher.lua#L101
> 
> Set `min=0` in this (and next) line, the same for the warmth.

Thanks @hius07 ! Will try

**Comment by NiLuJe** [comment]
> 0 means "gesture distance", right?

Ah! That's the piece I was missing. Cool trick ;).

**Comment by NiLuJe** [comment]
With what kind of gestures were you trying the increment/decrement stuff?

**Comment by mergen3107** [comment]
One-finger swipes along the side edges (left and right)

**Comment by mergen3107** [comment]
Yay, thanks @NiLuJe for stepping in to help with this mess :D

**Comment by NiLuJe** [comment]
Okay, that'll (probably) need a scale tweak in the magic maths thingy that I don't understand ;).

I just fixed the *other* cases, where the event is called from a non-gesture... gesture ;D (a "static" gesture, with no movement, e..g., corner tap)

**Comment by mergen3107** [comment]
Thanks in any case, since maybe now the ice will melt a little :D 

(I was thinking about making swipes along an edge as intensity sliders and top and bottom respective corners as warmth incrementors. But I really can't give up TOC or Bookmark in the top edge corners :D so using my jerryrig "patch" for now...)

**Comment by mergen3107** [comment]
Closed by #11226
