### ISSUE TITLE
Crash: when opening an image with Image Viewer

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11228]
* KOReader version: v2023.10-53
* Device: PocketBook Touch Lux 5

#### Issue
When I try to open an image with Image Viewer, KOReader crashes.

##### `crash.log` (if applicable)
[crash 14-12-2023.log](https://github.com/koreader/koreader/files/13673237/crash.14-12-2023.log)

**Comment by hius07** [comment]
Confirm crash with checked new Auto-rotate for best fit.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/f4a5a2b60a8a92a980b04c67956f3f835f2f8c95/frontend/ui/widget/imageviewer.lua#L159-L161
When opened via Open with..., we pass a filename, not image.

**Comment by poire-z** [comment]
I guess we could just add a check on self.image in `if self.image and G_reader...` and have that feature only with images from books.
Feels a bit tedious (and not _my_ use case at all :/) to get autorotation with a file as we need the image rendered with no-rotation to know if rotation is needed, and then re-render it.

**Comment by hius07** [comment]
Totally agree.

**Comment by hius07** [comment]
I can add the fix to https://github.com/koreader/koreader/pull/11227.

**Comment by poire-z** [comment]
^ go ahead :)

**Comment by ichnilatis-gr** [comment]
> Confirm crash with checked new Auto-rotate for best fit.

It was checked, if I remember well.
