### ISSUE TITLE
koreader randomly removes book data

### ISSUE THREAD

**Issue by allen20010405** [koreader/koreader#11247]
* KOReader version: KOReader 2023.08 "Lavender"
* Device: kobo

#### Issue
ko reader randomly removes book data, rendering .edups glitched or unreadable
#### Steps to reproduce
while tranfering a book from computer to kobo it reboots and transfered books sometimes become gliched # this only happens with large ebooks
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

doesn't really crash at all, life just goes on as normal.

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
On which device?

Transferring books how?

Also, you're not running an up to date version.

**Comment by allen20010405** [comment]
transferring books via usb, also, upgraded to latest version, there is no problems now, sorry for bothering you.
