### ISSUE TITLE
Move to Archive plugin : crash if folder is missing

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11245]
* KOReader version: v2023.10-55
* Device: Kindle Scribe

#### Issue and Steps to reproduce
I created a folder Archive, then set up Move to archive plugin. After a while I renamed that folder (don't remember, over sftp or in KOReader). Upon next restart KOReader crashed.

I would think that instead of crashing KOReader should probably fallback to an existing folder? Like, Home or create a default folder and use that.

##### `crash.log` (if applicable)
I sadly lost the log, but I remember reading it: it said that the Archive folder wasn't found.

I can reproduce later, if absolutely needed.

##### P.S.
Maybe Wikipedia (and other plugins/features like News Downloader) have the same issue? Will check those too.

**Comment by Frenzie** [comment]
@hius07 has done some fixes on that plugin in recent months.

**Comment by hius07** [comment]
The check for target folder never existed.

**Comment by Frenzie** [comment]
Oh, I didn't mean you broke it or anything, lol

I meant you can probably add a check in the right place the quickest if it piques your interest.

**Comment by mergen3107** [comment]
Closed by merged #11262.
