### ISSUE TITLE
Opening footnote for a large epub (> 10MB) is slow when the file is opened the first time, but it is fast to open the footnote when the file is opened second time

### ISSUE THREAD

**Issue by milanglacier** [koreader/koreader#11254]
* KOReader version: 2023.10
* Device:
Boox Page (Android 12)

#### Issue

I know that koreader reads the entire document for the first time. And the second time to open the file it uses cache to open the data so I can expect that it will be responsive. However, I notice that, if you are opening the footnote when the file is opened first time then it is slow. The file is already formatted, so there are no additional waiting time for reformatting. And then if you exit the file and reopen it again, then opening footnote is responsive.

#### Steps to reproduce

Below is a video to demonstrate what is happening here (I clipped the waiting time (>20s) for the first time to open the epub):

https://github.com/koreader/koreader/assets/45728125/643d1881-6fff-4cd3-94a7-41078ee67e2c

#### Expected Result

Opening footnote when the file is opened first time should be as fast as the second time.

**Comment by Frenzie** [comment]
@poire-z Any idea?

**Comment by poire-z** [comment]
Dunno.
I somehow don't reproduce that with a 4MB epub of 6000 pages of French text, when on page 60 showing in a footnot popup a small footnote from page 5800.

So, may be it's really bigger, and see if there's some logs like "CRE WARNING some limit reached..." in your crash.log.
Or it could be something specific with CJK, or the book organisation (big single fragment, or multiple small xhtml fragments), or the code that handles footnote popup detections and what content to gather and display. Hard to say without the EPUB.
(Also see if the option "Show more links as footnote" changes something in the behaviour, it may do more or less work.)

Or it might just all be normal with really big stuff and things being trashed and rerendered more often while they are not yet cached in a cache.

**Comment by milanglacier** [comment]
> Dunno. I somehow don't reproduce that with a 4MB epub of 6000 pages of French text, when on page 60 showing in a footnot popup a small footnote from page 5800.
> 
> So, may be it's really bigger, and see if there's some logs like "CRE WARNING some limit reached..." in your crash.log. Or it could be something specific with CJK, or the book organisation (big single fragment, or multiple small xhtml fragments), or the code that handles footnote popup detections and what content to gather and display. Hard to say without the EPUB. (Also see if the option "Show more links as footnote" changes something in the behaviour, it may do more or less work.)
> 
> Or it might just all be normal with really big stuff and things being trashed and rerendered more often while they are not yet cached in a cache.

Yes, this file is insanely large: 20K pages. And it also contains a huge amount of footnotes, because it is a classic illustration book. I can share with you the epub file for debugging.

https://drive.google.com/file/d/1tPeCyU0UCqekY0ugKIOUmTrfvA1VJgwK/view?usp=drivesdk

And as for caching, I think this is not the case where something is not cached at the first time opened but get cached at second time, I believe they should be already cached at the first time. Because opening arbitrary footnotes at arbitrary location is responsive even this link has never been opened before in the second time.

**Comment by milanglacier** [comment]
Hi, the access has been granted! Thanks so much for digging in into this again!

**Comment by poire-z** [comment]
Had a hard time finding some footnotes among 70000 pages :)

But confirmed, just putting some logs here for reference:
```
12/28/23-21:08:57 DEBUG nearest selected_link {
  a_xpointer = "/body/DocFragment[10782]/body/div[4]/a.0",
  end_x = 296,
  end_y = 202,
  link_y = 222,
  section = "#_doc_fragment_10781_ anchor2",
  segments = {
    {
      x0 = 275,
      x1 = 293,
      y0 = 202,
      y1 = 222
    } --[[table: 0x7f98ff8acbd0]]
  } --[[table: 0x7f98ff8acb88]],
  start_x = 273,
  start_y = 202
} --[[table: 0x7f98ff8ac9e8]]
12/28/23-21:08:57 DEBUG ReaderLink:onGotoLink: Internal link: {
  a_xpointer = "/body/DocFragment[10782]/body/div[4]/a.0",
  from_xpointer = "/body/DocFragment[10782]/body/div[4]/a.0",
  link_y = 222,
  marker_xpointer = "#_doc_fragment_10781_ anchor2",
  xpointer = "#_doc_fragment_10781_ anchor2"
} --[[table: 0x7f98fc0486e0]]
12/28/23-21:08:57 DEBUG Checking if link is to a footnote: 57183 /body/DocFragment[10782]/body/div[4]/a.0 #_doc_fragment_10781_ anchor2

<time spent here>

12/28/23-21:09:04 DEBUG is a footnote: no decision, default to be a footnote
12/28/23-21:09:04 DEBUG   not extended because: end of document fragment met
12/28/23-21:09:04 DEBUG _refresh: Enqueued ui update for region 0 0 600 610 dithering: false
```
Disabling Show footnotes in popup and following the link is instantaneous - so probably not a crengine issue.
The "is link to a footnote test" is in base/cre.cpp, so I'll follow my investigation from there when I find the time.

> I believe they should be already cached at the first time

Things are cached in memory, and are only saved to disk when you quite the document. On the next opening, stuff are read from the cache files. It's a different kind of cache.

**Comment by milanglacier** [comment]
Thanks for digging into this hole! I also find that when "show pop up" is disabled, opening links are fast. But opening links in a pop up is a very useful feature, thus I think “disable popup” as the workaround is not ideal.

**Comment by poire-z** [comment]
Ok, so it doesn't get slow when I comment this out:
https://github.com/koreader/koreader/blob/63329569eb8afb00a29a723f215c6c5fcc9041aa/frontend/apps/reader/modules/readerlink.lua#L1337-L1338

And indeed, on initial load, when requesting the TOC (Table of Content) to do this check, the page numbers from all the TOC entries were each time recalculated...

I think we can solve this with:
```diff
--- a/crengine/include/lvtinydom.h
+++ b/crengine/include/lvtinydom.h
@@ -2610,6 +2610,7 @@ public:

 #if BUILD_LITE!=1
     bool isTocFromCacheValid() { return _toc_from_cache_valid; }
+    void setTocFromCacheValid() { _toc_from_cache_valid = true; }

     /// save document formatting parameters after render
     void updateRenderContext();
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -834,6 +834,7 @@ LVTocItem * LVDocView::getToc() {
         if (!m_doc->isTocFromCacheValid() || !m_doc->getToc()->hasValidPageNumbers(getVisiblePageNumberCount())) {
             updatePageNumbers(m_doc->getToc());
             m_doc->setCacheFileStale(true); // have cache saved with the updated TOC
+            m_doc->setTocFromCacheValid();  // consider it valid now that page numbers are updated
         }
        return m_doc->getToc();
 }
```

The variable and method names got a bit less true to their name with time, and it could probably be reworked to make all this cleaner, but well, too lazy to give this more thoughts. I'll push that in the coming days or weeks if I don't get any afterthought.

So, the reason was not so much the size of the book, but the size of its Table of Content: 9238 items.

**Comment by Frenzie** [comment]
> the size of its Table of Content: 9238 items.

Wow!
