### ISSUE TITLE
reMarkable: "Update information not available"

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#11258]
* KOReader version: 2023.10-70
* Device: reMarkable 1

#### Issue
"Update information not available on Stable channel"

#### Steps to reproduce
1. Turn Wi-Fi off
2. Check for updates
3. Choose "Turn on" when prompted about Wi-Fi
4. "Update information not available on Stable channel"
5. Check for updates again immediately
6. Update check is successful

The result is the same with the Development channel and with all other update servers

#### Hypothesis
Error started only a few months ago. Perhaps there used to be a tiny delay between Wi-Fi connection established and querying the update server. Such delay may need to be added back for certain devices.

**Comment by NiLuJe** [comment]
That's usually device, AP and connectivity dependent, to a certain extent. In any case, fairly hard to account for.

**Comment by gbyl** [comment]
Fair point. Something may have changed in a newer firmware version -- instead of KOreader. Which files should I look at to test out some delay values?

**Comment by NiLuJe** [comment]
Depending on how long ago you checked, we did revamp that a bit a while ago, so we are indeed likely catching up faster than we used to. (Again, not familiar with rM, so I don't recall how it was historically implemented).

c.f., https://github.com/koreader/koreader/blob/9ba66ac382ab8778978d075d0de15b73617de49b/frontend/ui/network/manager.lua#L230-L275 and the history/PRs linked to that chunk ;).

**Comment by arooni** [comment]
I am getting this error message on both my Kindle Scribe (development channel), and my Paperwhite 3 (stable channel).

**Comment by gbyl** [comment]
@arooni I think the default update server was down today temporarily. Switching to another server should fix it for your devices though

**Comment by arooni** [comment]
Seems like the progress server is down too.  Was trying to login with new credentials today and I got "Unknown server error"

**Comment by NiLuJe** [comment]
Yeah, the main server is down (the usual Azure thingy around the late twenties); ought to be back up in ~48H.

It went down on the 24th, ~6AM UTC.

**Comment by mergen3107** [comment]
Server is back!

**Comment by ryanwwest** [comment]
Working now for me too (was not working yesterday).

**Comment by ryanwwest** [comment]
I wonder if the error message could be improved to indicate 'try again later' since I've seen this happen every few months e.g. https://github.com/koreader/koreader/issues/9251. I always forget what it means at first.

**Comment by NiLuJe** [comment]
That message being super unhelpful and not user-friendly at all is actually a pretty good point, yeah ;).

**Comment by Frenzie** [comment]
Though that specific linked issue was definitely something else.

**Comment by gbyl** [comment]
@NiLuJe I tried various delay values in `koreader/frontend/ui/network/manager.lua` without any luck. What ultimately fixed it reliably was adding: `os.execute("sleep 1")` right before this line

https://github.com/koreader/koreader/blob/63329569eb8afb00a29a723f215c6c5fcc9041aa/frontend/ui/otamanager.lua#L225-L227

I am not sure how to interpret that. Some sort of race condition perhaps?

**Comment by Frenzie** [comment]
fetchAndProcessUpdate() will only be called after the device thinks it's connected. Broadly see https://github.com/koreader/koreader/commit/96850c23a010d3175b98b754faba898481736b00

**Comment by Miladiir** [comment]
Right now, the server is actually down :( Cloudflare 522 error

**Comment by gbyl** [comment]
Closing issue as this is an edge case only affecting the remarkable 1. Keeping it open can mislead users who may encounter `"Update information not available on Stable channel"` with other devices due to server issues.

**Comment by NiLuJe** [comment]
> Keeping it open can mislead users who may encounter `"Update information not available on Stable channel"` with other devices due to server issues.

That warning is no longer relevant, it was updated months ago to be slightly less unhelpful.
