### ISSUE TITLE
PocketBook touchscreen unresponsive after update

### ISSUE THREAD

**Issue by Deekee62** [koreader/koreader#11250]
* KOReader version: Pocketbook 2023
* Device: Pocket Book InkPad Pro PB740-2

##### `crash.log` (if applicable)

Unfortunately I'm unable to add the crash log, as I don't have access via USB anymore.

Below picture of the screen

![A99C19E2-214E-47BB-AC93-F96B122656DF_1_105_c](https://github.com/koreader/koreader/assets/33904339/bc67c09f-0cc8-4b66-9adb-b49b47164713)

Many thanks in advance for any hint

**Comment by pazos** [comment]
that's not an issue on our side
