### ISSUE TITLE
Kindle with Gyro - starts upside down when launching in U after D (or vice versa)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11269]
* KOReader version: v2023.10-55
* Device: Kindle Scribe

#### Issue
Each time the orientation in Kindle menu is changed from `U` to `D` (or vice versa), KOReader starts as upside down. It doesn't hurt anything, because a simple +/- 90 deg rotation is enough to bring it back.

#### Steps to reproduce
1) Start KOReader in `U`.
2) Exit KOReader.
3) Rotate Kindle in hand by 180 deg to go into `D`.
4) Start KOReader.
5) The `Starting KOReader` message shows up upright, but the message about the book being open and KOReader itself then show up upside down.
6) The same is true if you continue exiting/rotating/starting from this orientation, so it is there each time reliably.

##### `crash.log` (if applicable)
I don't yet where to look for.
My suspicion would be it the gyroevent that doesn't account for it?

**Comment by mergen3107** [comment]
Where in the code is the place where it gets first orientation to render the content?

**Comment by mergen3107** [comment]
> Where in the code is the place where it gets first orientation to render the content?

I guess, it is here:
https://github.com/koreader/koreader/blob/b949d07f4fbf7ffb0a145684f98f196bb0492aea/frontend/device/generic/device.lua#L265-L271

**Comment by mergen3107** [comment]
This part is before `Kindle:init()`, right?
I tried to put `self.screen:setRotationMode(self.screen.cur_rotation_mode)` in the end of the `Kindle:init()`, where `self.screen.cur_rotation_mode` was calculated already from the lipc call. However, this didn't work.

**Comment by NiLuJe** [comment]
c.f., the whole Oasis block in Kindle's device.lua, which we already discussed, IIRC.

**Comment by mergen3107** [comment]
Yes, I remember this. I fixed the touch input vs rendering orientation mismatch, but I don't know what to do next. People having Oases didn't chime in either :D 
This is isn't critical, but still, it surprises me that it takes so much effort to override this behavior in the OP.

**Comment by mergen3107** [comment]
> > Where in the code is the place where it gets first orientation to render the content?
> 
> I guess, it is here:
> 
> https://github.com/koreader/koreader/blob/b949d07f4fbf7ffb0a145684f98f196bb0492aea/frontend/device/generic/device.lua#L265-L271

I simply commented this out and now it works great!
Maybe I can guard it will something like `if not (Device:isKindle() and Device:hasGSensor()) ...`

**Comment by mergen3107** [comment]
It works with these changes! Had to use `self.` instead of `Device`:
```
    -- Ensure the proper rotation on startup.
    -- We default to the rotation KOReader closed with.
    -- If the rotation is not locked it will be overridden by a book or the FM when opened.
    if not (self.isKindle() and self.hasGSensor()) then
        local rotation_mode = G_reader_settings:readSetting("closed_rotation_mode")
        if rotation_mode and rotation_mode ~= self.screen:getRotationMode() then
            self.screen:setRotationMode(rotation_mode)
        end
    end
```

**Comment by mergen3107** [comment]
Now if I quite KOReader, rotate 180 degree and start KOReader - it will greet me upside down relative to me :D Yay!

Any objections? Can I commit a PR?

**Comment by NiLuJe** [comment]
Hell no, this is there for a reason ;).

**Comment by mergen3107** [comment]
What does it break?
I tested it quickly, everything works great :D

**Comment by NiLuJe** [comment]
It effectively breaks restoring the correct rotation on startup.

That it happens to to... something on your device is probably thanks to the Oasis shenanigans on init, but this is very much not widely applicable.

**Comment by mergen3107** [comment]
> It effectively breaks restoring the **correct rotation** on startup.

See, in my case, **correct rotation** is only achieved with this little fix. By correct I mean it starts upright no matter what orientation Kindle was, and everything works (touch aligned with render, swipe animations).

I also didn't lose generality, so all other devices without Kindle+Gyro properties will still have this function. That means everything except Kindle Scribe and Kindle Oasis 1/2/3.

**Comment by mergen3107** [comment]
To me it seems like this:


> 5\. The `Starting KOReader` message shows up upright

This is Kindle:init() of Kindle Scribe doing it right with gyro fixes I made recently.



> 5\. but the message about the book being open and KOReader itself then show up upside down.

This is `generic` device rotating the screen _again_ after the startup.

So, if it behaved well all this time before, this second rotation is redundant in the case of Kindle+Gyro.

**Comment by mergen3107** [comment]
So unless you suggest me test specifically what can break, I am convinced that this is the fix I need :D

**Comment by NiLuJe** [comment]
> I also didn't lose generality, so all other devices without Kindle+Gyro properties will still have this function. That means everything except Kindle Scribe and Kindle Oasis 1/2/3.

Which isn't something we can guarantee will always be true, hence it cannot be an assumption we make in generic code.

**Comment by NiLuJe** [comment]
You can try to do something in an appropriate `Kindle:exit` implementation instead.

**Comment by mergen3107** [comment]
By overriding `G_reader_settings:readSetting("closed_rotation_mode")` just for Kindle+Gyro?

**Comment by mergen3107** [comment]
But the problem is not in the setting, but the fact it is applied at startup and it is fixed, whereas by the next startup Kindle might be in different orientation due to gyro

**Comment by NiLuJe** [comment]
In don't know what you need to do exactly, but it has to stay inside Kindle's Device imp ;).

**Comment by mergen3107** [comment]
Can I override `G_reader_settings:readSetting("closed_rotation_mode")` upon init?

**Comment by NiLuJe** [comment]
What do you mean by "override"?

I expect you might need to play around with `setRotationMode`, possibly depending no that setting at some point, or something.

Or, assuming that works properly, what @yparitcher said about doing something sensible with the framebuffer rotation on startup like on Kobo. I don't recall how that works on Kindle, and it's prooobably slightly different on MTK than on the Oases.

**Comment by NiLuJe** [comment]
Oh, okay, I see the problem.

I remembered that the `closed_rotation_mode` stuff was implemented in `reader.lua`, but I moved it to `Generic`, so there's indeed an ordering issue with the Kindle gyro hacks, because it does Kindle -> Generic instead of Generic -> Kindle...

Can you try simply moving the `Kindle.init(self)` line just above the aforementioned `winmgr` lipc block mess?

**Comment by NiLuJe** [comment]
> Can you try simply moving the `Kindle.init(self)` line just above the aforementioned `winmgr` lipc block mess?

You might also need an explicit `self.screen:setRotationMode(rotation_mode)` in the `rotation_mode > 0` branch?

**Comment by mergen3107** [comment]
> You might also need an explicit `self.screen:setRotationMode(rotation_mode)` in the `rotation_mode > 0` branch?

I tried that before - no dice.



> Can you try simply moving the `Kindle.init(self)` line just above the aforementioned `winmgr` lipc block mess?

Thanks! I'll try soon

**Comment by mergen3107** [comment]
> > You might also need an explicit `self.screen:setRotationMode(rotation_mode)` in the `rotation_mode > 0` branch?
> 
> I tried that before - no dice.

And I think that was because


> it does Kindle -> Generic instead of Generic -> Kindle...

so, whatever `self.screen:setRotationMode(rotation_mode)` did, Generic undid

**Comment by NiLuJe** [comment]
Yup, exactly!

**Comment by mergen3107** [comment]
> Can you try simply moving the `Kindle.init(self)` line just above the aforementioned `winmgr` lipc block mess?

Thanks @NiLuJe ! That did it!
1) I reverted generic device.lua back to stock.
2) Move `Kindle:init(self) just above the lipc abomination.
3) Added the rotation call in the `rotation_mode > 0` part, so now it looks like this:
```
            if rotation_mode > 0 then
                self.screen.native_rotation_mode = rotation_mode
                self.screen.cur_rotation_mode = rotation_mode
                self.screen:setRotationMode(rotation_mode)
            end
```

**Comment by NiLuJe** [comment]
I assume it didn't do anything without 3., right?

**Comment by mergen3107** [comment]
It didn't work when there was 3, but that was when I didn't shift Kindle:init() up. 

And yes, it didn't work with 1 and 2, but no 3 :D

**Comment by NiLuJe** [comment]
You can also drop the `self.screen.cur_rotation_mode = rotation_mode` line, as `setRotationMode` already handles it ;).

**Comment by mergen3107** [comment]
Thanks! Yep, I confirm it is redundant now. `framebuffer.lua`:
```
function fb:setRotationMode(mode)
    -- This, on the other hand, is responsible for the internal *buffer* rotation,
    -- as such, it's inverted compared to the DEVICE_ROTATED_ constants; i.e., it's in 90° CCW steps).
    self.bb:rotateAbsolute(-90 * (mode - self.native_rotation_mode - self.blitbuffer_rotation_mode))
    if self.viewport then
        self.full_bb:setRotation(self.bb:getRotation())
    end
    self.cur_rotation_mode = mode
end
```
The last command is the same as `self.screen.cur_rotation_mode = rotation_mode`.

Tested too, just in case! Works! :D

**Comment by mergen3107** [comment]
@NiLuJe 
I found another problem.
1) Start KOReader in any orientation.
2) Rotate 180 degrees.
3) Restart - KOReader will show up upside down. Nothing critical though, touch and input are still aligned, so I need to rotate back and forth to get it upright.

Can I fix this?

**Comment by mergen3107** [comment]
This is including the abovementioned PR.

**Comment by NiLuJe** [comment]
> 3\. Restart

Restart what? KOReader or the Kindle?

And does it perhaps only happen if you restart upright or something?

**Comment by mergen3107** [comment]
> Restart what? KOReader or the Kindle?

Restart KOReader from top menu.

> And does it perhaps only happen

This is now consistent with changes introduced to `Kindle:init()`.
I think I see what's the problem now.

When I start KOReader fresh, it gets Kindle orientation (`U` or `D`).

When I then restart KOReader, it takes the same rotation again and uses that, no matter what actual orientation KOReader was before restart. This is because Kindle menu does not rotate at all behind KOReader.

If I put `Kindle.init()` back to after rotation detection, then it has correct upright restart orientation, but not fresh start orientation.

So unless there will a new flag to distinguish between a fresh start or restart, this problem will stay.

**Comment by mergen3107** [comment]
I found where it declares Device:exit, but I have a hard time finding the restart function.
https://github.com/koreader/koreader/blob/5d2a4410648dfc993e6dbc01cbf23941a92404c3/frontend/device/generic/device.lua#L545-L563

**Comment by NiLuJe** [comment]
There isn't anything specific to a restart, a restart just exits KOReader and restarts KOReader ;). (i.e., it gets detected as "not a crash" by the startup script which will just respawn us).

**Comment by NiLuJe** [comment]
So, yeah, we'd probably need to *write* to the native lipc rotation thingy to update it to match whatever is done while KOReader is alive, otherwise, we'll trust the *initial* native rotation from the gyro.

**Comment by mergen3107** [comment]
> Does it behave in no framework mode?

Let me see :D 

As for awesome stuff, I have yet to see when Kindle home menu rotates while KOReader restarts, or when it is exited. 

I was thinking, is there a way to simulate gyro events? 

Like, to write stuff to the dev input device responsible for the gyro.

Write +90 deg and back, for example - this is what I have to do by hand to bring it upright.

**Comment by mergen3107** [comment]
> Does it behave in no framework mode?

The same story in no framework mode

**Comment by yparitcher** [comment]
Btw,

The underlying issue is that the framework orients the hardware devices correctly (relative to the accelerometer), however we open the touch device directly so it stays in the `U` orientation.

Now we were trying to fight the orientation to reset it (at least in koreaders eyes) to `U` yo match the touch, and then (in this pr) rerotate it back to match the accelerometer. 

We might want to try another approach, that when started in `D` use the input touch hooks to rotate the touch to match the devices orientation which should nicely solve all the problems.

https://github.com/koreader/koreader/blob/5d2a4410648dfc993e6dbc01cbf23941a92404c3/frontend/device/input.lua#L347-

**Comment by yparitcher** [comment]
There is not an existing hook to do this but something like
```lua
function Input:adjustABS_MirrorXY(ev, max_x, max_y)
    if ev.code == C.ABS_X or ev.code == C.ABS_MT_POSITION_X then
        ev.value = max_x - ev.value
    else if ev.code == C.ABS_Y or ev.code == C.ABS_MT_POSITION_Y then
        ev.value = max_y - ev.value
    end
end
```

**Comment by mergen3107** [comment]
Thanks @yparitcher !
I'll be happy to test :D

**Comment by yparitcher** [comment]
As usual i am a few hours late :)
I just figured this out. (Tested on pw5 by setting `orientationLock` to `D`)

Koreader (on kindle) does all rotation in sw, therefore our rotations don't affect the hw swipe direction. 

The native kindle does hw rotations, the default panel orientation (at least on the pw5) is 1/CW, when the kindle is rotated down the panel is put to 3/CCW

So the solution to fixing the startup rotation, is to get rid of the `self.native_rotation` etc, and just do a `self.screen:setHwRotation(1)` to reset the panel to its native rotation which koreader expects, and then manually trigger a sw rotation back to the current, via `setRotation(current)`.
I am not sure about the exact required startup timing of the `setRotation` call. This will work in frameworkless, howeverthis needs to be checked in regular mode to see if the native will fight us and set the hw rotation back while we are running.

Also `ffi/framebuffer_linux.lua` has a crash in `setHwRotation` when `forced_rotation` is not enabled. The line `self.forced_rotation[mode+1] or mode` needs to be patched to `self.forced_rotation and self.forced_rotation[mode+1] or mode`

**Comment by Frenzie** [comment]
I'm fine with reverting/changing/updating #11277, but if you'd like it in the release please do so today. I'll then do the release on Saturday or Sunday rather than tonight. :-)

**Comment by yparitcher** [comment]
I dont have time or hw to do further testing, this needs someone with hw to take this further. @mergen3107 @NiLuJe 

#11277 is fine (probably better than what was before) but just not the whole fix, so i dont see a need to revert.

**Comment by yparitcher** [comment]
This would also need changes in base, so dont delay the release

**Comment by mergen3107** [comment]
Thank you very much @yparitcher !
Appreciate your help.

I agree, the fix in above mentioned PR is OK by itself. I'll have some time to play around no earlier this weekend, so it is fine.

**Comment by NiLuJe** [comment]
> I am not sure about the exact required startup timing of the `setRotation` call. This will work in frameworkless, howeverthis needs to be checked in regular mode to see if the native will fight us and set the hw rotation back while we are running.

IIRC, that shouldn't be a problem, as long as we restore the expected rotation on exit (otherwise, X11 loses its lunch ;p).

**Comment by yparitcher** [comment]
> > I am not sure about the exact required startup timing of the `setRotation` call. This will work in frameworkless, howeverthis needs to be checked in regular mode to see if the native will fight us and set the hw rotation back while we are running.
> 
> IIRC, that shouldn't be a problem, as long as we restore the expected hw rotation on exit (otherwise, X11 loses its lunch ;p).

we probably have to restore the ending rotation on exit, as the scribe auto rotates and is expecting the rotation to be according to the gyro

**Comment by yparitcher** [comment]
It might not be needed at all, as we will always be in the correct portrait / landscape, as we can only start koreader in `U` or `D` not `R` or `L`, so x11 will probably be fine, the only question is will awesome re rotate to the gyro direction, or do we have to do it ourselves on exit. so i would try first without and see what happens

**Comment by mergen3107** [comment]
> the only question is will awesome re rotate to the gyro direction, or do we have to do it ourselves on exit

@yparitcher 
Any suggestions of how to make `awesome` rotate?
It is the same as `orientationLock`?

**Comment by yparitcher** [comment]
Did you try without, and see if awesome self adjusts based on the gyro?

**Comment by mergen3107** [comment]
@yparitcher 
Without framework, you mean?

**Comment by mergen3107** [comment]
Ah, I see. Thanks! I'll try it in the init.

**Comment by mergen3107** [comment]
@yparitcher 

Thanks!
On Scribe, I have to use `3` as the HW rotation - this the "default" correct rotation `U`, whereas `3` is `D`.

I commented out this part:
```
            if rotation_mode > 0 then
                self.screen.native_rotation_mode = rotation_mode
            end
            self.screen:setRotationMode(rotation_mode)
```
and added (`HW` must be capital in the `setHWRotation`)
```
self.screen:setHWRotation(3)
```
SW rotation is still done by
```
self.screen:setRotationMode(rotation_mode)
```

Upon start in either `U` or `D` KOReader's screen orientation as well as page animations are correct (I made sure to remove my hacky patch in framebuffer).

However, if I start KOReader, then rotate 180 degrees, then either exit or restart KOReader - the screen becomes upside down.

I think this upon exit KOReader should also do `self.screen:setHWRotation(current_mode)` to make sure Kindle rotates accordingly.

**Comment by mergen3107** [comment]
For the `Exit` I solved it this way:
In `generic/device.lua` added to `Device:Exit()` this:
```
    if self.screen:getRotationMode() == 2 then
        self.screen:setHWRotation(1)
    else    
        self.screen:setHWRotation(3)
    end
```

The reason is that HW and SW rotations are off by 2:
```
    SW  HW
U   0   3
L   1   2
D   2   1
R   3   0
```

Now I am trying to make KOReader restart in the same orientation when I do `Restart`.

**Comment by mergen3107** [comment]
OK, I retract. 

If I forcefully rotate HW upon Exit, then screen and touch are opposite again. I have to "rotate" 180 degrees back and forth, then touch becomes normal again. During this "rotation", screen stays the same.

**Comment by mergen3107** [comment]
I think I found how solve the `Restart` :D 
Instead of just
```
            self.screen:setRotationMode(rotation_mode)
```
I did:
```
            local closed_rotation_mode_EXIT = G_reader_settings:readSetting("closed_rotation_mode")
            self.screen:setRotationMode(closed_rotation_mode_EXIT or rotation_mode)
```

Now when I restart KOReader, preference is in the saved rotation mode. If it is not there (yet - as in fresh start), then the lipc-found rotation mode kicks in. I will try to optimize this whole thing later - I might just end up calling the lipc command only if `closed_rotation_mode_EXIT` isn't there...

**Comment by mergen3107** [comment]
Ah, no, this is also broken, if I then flip Kindle 180 degrees and start KOReader again - it start upside down, but touch and screen are aligned :D

**Comment by mergen3107** [comment]
@NiLuJe 
I think the problem of Restart I described above can be solved if we ask KOReader to distinguish between Restart and Exit. Is this possible?

Then, closed_rotation_mode will be saved only if Restart is scheduled. Otherwise, it will be assigned nil. 

On a fresh start, Device:init() takes care of the rotation anyway.

**Comment by yparitcher** [comment]
> For the `Exit` I solved it this way:
> In `generic/device.lua` added to `Device:Exit()` this:
> ```
>     if self.screen:getRotationMode() == 2 then
>         self.screen:setHWRotation(1)
>     else    
>         self.screen:setHWRotation(3)
>     end
> ```


You can check the exit code (there is a special one for restart, and only call this (reset HWRotation) on exit not restart which should solve all the issues, restart will do 0 rotations, and a exit will reset to what the kindle native expects.

Does this behave the same w or w/o frameworkless?

**Comment by mergen3107** [comment]
Thanks! 
I only tried with framework. I'll test without framework later, it takes much longer to start/restart

**Comment by mergen3107** [comment]
Tested quickly (without exit code changes yet) - no-framework works OK the same

**Comment by mergen3107** [comment]
> on exit not restart

@yparitcher @NiLuJe 
Can you pleas help me understand how to distinguish exit and restart?
Sorry if I asked this before, but I probably have forgotten :D 

I found the exit code in the Generic device.lua, but I don't really understand how it is being summoned.
Is it coming from the dispatcher? I found both exit and restart events in the Dispatcher, and the Exit and Restart KOReader buttons end up broadcasting these events, but I don't know what happens next.

Thank you!

**Comment by NiLuJe** [comment]
Something along the lines of

```diff
diff --git a/frontend/device/generic/device.lua b/frontend/device/generic/device.lua
index eb45d1cc0..e992d20ee 100644
--- a/frontend/device/generic/device.lua
+++ b/frontend/device/generic/device.lua
@@ -552,7 +552,7 @@ function Device:toggleKeyRepeat(toggle) end
 --[[
 prepare for application shutdown
 --]]
-function Device:exit()
+function Device:exit(restart)
     -- Save any implementation-specific settings
     self:saveSettings()
 
diff --git a/frontend/device/kindle/device.lua b/frontend/device/kindle/device.lua
index f93bb17f7..af7d45f7a 100644
--- a/frontend/device/kindle/device.lua
+++ b/frontend/device/kindle/device.lua
@@ -1447,7 +1447,7 @@ function KindleScribe:init()
     self.input.open("/dev/input/event4")
 end
 
-function KindleTouch:exit()
+function KindleTouch:exit(restart)
     if self:isMTK() then
         -- Disable the so-called "fast" mode
         self.screen:_MTK_ToggleFastMode(false)
diff --git a/reader.lua b/reader.lua
index d4769f5b0..241b29f38 100755
--- a/reader.lua
+++ b/reader.lua
@@ -284,7 +284,7 @@ end
 -- Exit
 local function exitReader()
     -- Shutdown hardware abstraction (it'll also flush G_reader_settings to disk)
-    Device:exit()
+    Device:exit(exit_code == 85)
 
     if Profiler then Profiler.stop() end
```

`restart` will be true if it's a restart ;).

**Comment by mergen3107** [comment]
Thank you so much @NiLuJe !
