### ISSUE TITLE
FR: Kindle with Gyro - Rotate Kindle accordingly upon exit from KOReader

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11265]
I came up with this upon testing of rotations in #11180.

**Does your feature request involve difficulty completing a task? Please describe.**
1) I start KOReader in `U`, Kindle framework stays in `U`.
2) Then rotate device inside KOReader to `D`.
3) Exit KOReader - the Kindle framework still stays in `U`, which means I will see it upside down.
The same is true is started in `D` first, then rotated to `U` and exited.

**Describe the solution you'd like**
@NiLuJe,
is it possible to add rotation command to `koreader.sh`, in the section that follows after clean exit?
Can these rotation variables be extracted so that `koreader.sh` can use them?
Or are they isolated or destroyed upon exit?

**Describe alternatives you've considered**
Just rotating the device to +/-90 deg is enough to bring it back, not a big deal.

**Additional context**
Absolutely not necessary to fulfill. Please feel free to close if this is too much work for no return :D

**Comment by NiLuJe** [comment]
Can't test it, so it's unlikely to be something I'd work on myself.

But one could check the kobo startup scripts for how we handle fbdepth there.

**Comment by mergen3107** [comment]
Thanks! By the way, is there a way I can check the codes on GH that usually ship with target devices? For example, `koreader.sh` for Kindle, and `koreader.sh` for Kobo?
For now I just downloaded it from the releases.

**Comment by mergen3107** [comment]
After exiting `reader.lua`, Kobos do this:
```
# Restore original fb bitdepth if need be...
# Since we also (almost) always enforce Portrait, we also have to restore the original rotation no matter what ;).
if [ -n "${ORIG_FB_BPP}" ]; then
    echo "Restoring original fb bitdepth @ ${ORIG_FB_BPP}bpp & rotation @ ${ORIG_FB_ROTA}" >>crash.log 2>&1
    ./fbdepth -d "${ORIG_FB_BPP}" -r "${ORIG_FB_ROTA}" >>crash.log 2>&1
else
    echo "Restoring original fb rotation @ ${ORIG_FB_ROTA}" >>crash.log 2>&1
    ./fbdepth -r "${ORIG_FB_ROTA}" >>crash.log 2>&1
fi
```

where `ORIG_FB_ROTA` is obtained before `reader.lua` started:
```
# Restore original fb bitdepth if need be...
# Since we also (almost) always enforce Portrait, we also have to restore the original rotation no matter what ;).
if [ -n "${ORIG_FB_BPP}" ]; then
    echo "Restoring original fb bitdepth @ ${ORIG_FB_BPP}bpp & rotation @ ${ORIG_FB_ROTA}" >>crash.log 2>&1
    ./fbdepth -d "${ORIG_FB_BPP}" -r "${ORIG_FB_ROTA}" >>crash.log 2>&1
else
    echo "Restoring original fb rotation @ ${ORIG_FB_ROTA}" >>crash.log 2>&1
    ./fbdepth -r "${ORIG_FB_ROTA}" >>crash.log 2>&1
fi
```

Let's see if I can do something similar here with `lipc`.

**Comment by mergen3107** [comment]
> echo "Original fb rotation is set @ ${ORIG_FB_ROTA}" >>crash.log 2>&1

(Should this say "Original fb rotation is **stored** @..."?

**Comment by mergen3107** [comment]
My main question is this: how do I safely (in terms of memory and runtime) pass the current rotation variable from inside KOReader to `koreader.sh` environment? I remember LuaJIT is a sandbox, so all things must stay within it during runtime, correct?

**Comment by mergen3107** [comment]
Something like `os.execute(export lipc-get-prop com.lab126.winmgr orientationLock)`?

**Comment by mergen3107** [comment]
For example, here?
https://github.com/koreader/koreader/blob/b949d07f4fbf7ffb0a145684f98f196bb0492aea/frontend/ui/uimanager.lua#L1686-L1689

With an if-block that checks that this is a Kindle with Gyro, so nothing else is affected.

**Comment by mergen3107** [comment]
> KOREADER_ROTATION="lipc-get-prop com.lab126.winmgr orientationLock"

On a second thought, I remembered that `orientationLock` does not change while KOReader is running. So I need something like `os.execute("export KOREADER_ROTATION=Screen.cur_rotation_mode")`, or whatever the current rotation is called.

**Comment by mergen3107** [comment]
and then I can use this value in koreader.sh ...

**Comment by NiLuJe** [comment]
> > echo "Original fb rotation is set @ ${ORIG_FB_ROTA}" >>crash.log 2>&1
> 
> (Shouldn't this say "Original fb rotation is **stored** @..."?)

No, the wording is meant to refer the system status, not what's happening in the script ;).

**Comment by mergen3107** [comment]
OK, I think I found proper syntax of os.execute.
`os.execute("export KOREADER_ROTATION=" .. Screen.cur_rotation_mode)`

**Comment by NiLuJe** [comment]
> I remember LuaJIT is a sandbox, so all things must stay within it during runtime, correct?

Whut?



> My main question is this: how do I safely (in terms of memory and runtime) pass the current rotation variable from inside KOReader to `koreader.sh` environment?

Script -> KOReader or KOReader -> script?

For the latter, `export FOO` in script , `os.getenv("FOO")` in Lua (c.f., the AWESOME stuff which is already handler this way on Kindle).

For the former `C.setenv("FOO", "value", 1)` via ffi in KOReader, `$FOO` in script.

**Comment by mergen3107** [comment]
> Whut?

Lol, that's what I remember from android-luajit when I tried to export brightness to system. Nevermind :D

**Comment by mergen3107** [comment]
> By the way, is there a way I can check the codes on GH that usually ship with target devices?

https://github.com/koreader/koreader/tree/master/platform/kindle

**Comment by mergen3107** [comment]
> Script -> KOReader or KOReader -> script?

I believe, your recipies are swapped? Former/latter

**Comment by mergen3107** [comment]
I added
```
local C = require("ffi").C
...
    logger.dbg("EXIT: ROTATION MODE", Screen:getRotationMode())
    koreader_current_rotation_for_script = Screen:getRotationMode()
    C.setenv("KOR_CUR_ROT", tostring(koreader_current_rotation_for_script), 1)
```
in `uimanager.lua`, where the three lines are in the end of this function now (around L813):
```
function UIManager:quit(exit_code, implicit)
    if exit_code == false then
        logger.err("UIManager:quit() called with false")
        return
    end
    -- Also honor older exit codes; default to 0
    self._exit_code = exit_code or self._exit_code or 0
    if not implicit then
        -- Explicit call via UIManager:quit (as opposed to self:_gated_quit)
        if exit_code then
            logger.info("Preparing to quit UIManager with exit code:", exit_code)
        else
            logger.info("Preparing to quit UIManager")
        end
    end
    self._task_queue_dirty = false
    self._window_stack = {}
    self._task_queue = {}
    for i = #self._zeromqs, 1, -1 do
        self._zeromqs[i]:stop()
    end
    self._zeromqs = {}
    if self.looper then
        self.looper:close()
        self.looper = nil
    end
    logger.dbg("EXIT: ROTATION MODE", Screen:getRotationMode())
    koreader_current_rotation_for_script = Screen:getRotationMode()
    C.setenv("KOR_CUR_ROT", tostring(koreader_current_rotation_for_script), 1)
    return self._exit_code
end
```
Then, in `koreader.sh` I added (in the very end, right before `exit ${RETURN_VALUE}`)
```
echo "KOR_CUR_ROT=" ${KOR_CUR_ROT} >>crash.log 2>&1
```

Crash.log reports the `logger.dbg` correctly as
```
12/25/23-11:54:57 DEBUG EXIT: ROTATION MODE 2
```
However, `koreader.sh`'s `echo` is showing it as empty:
```
lipc-wait-event exited normally with status: 0
KOR_CUR_ROT=
```

What am I doing wrong?

**Comment by mergen3107** [comment]
I tried just a generic string "123" with the `C.setenv` above, and it seems it doesn't work at all.

**Comment by mergen3107** [comment]
Tried to guard the `C.setenv` with `pcall()`, like this:
```
    if pcall(C.setenv("KOR_CUR_ROT", tostring(koreader_current_rotation_for_script), 1)) then
        logger.info("C.setenv worked!")
    else
        logger.info("C.setenv didn't work!")
    end
```
but I just got confirmation, it doesn't work :D 

```
12/25/23-13:19:00 INFO  C.setenv didn't work!
```

**Comment by Frenzie** [comment]
Try something like `ok, msg = pcall(etc); print(msg)` to see what the reason is. ^_^

**Comment by mergen3107** [comment]
Using just s string also yields the same error O_O

**Comment by Frenzie** [comment]
That probably means you're calling the result of the function, meaning it's the equivalent of pcall(0). (0 means success). But I'm quickly typing this on my phone, more later if necessary.

**Comment by NiLuJe** [comment]
> > Script -> KOReader or KOReader -> script?
> 
> I believe, your recipes are swapped? Former/latter

Nope, unless we grok things differently ;). I meant setter -> getter.

**Comment by NiLuJe** [comment]
Oh, wait, minor brainfart. That won't work, because that'd be child -> parent, so, nope.

You'll probably want to handle this in Lua, at the tail end of reader.lua, there's a bit of code that saves the current *koreader* rotation (there... may be other places where this happens, can't check right now).

**Comment by mergen3107** [comment]
Thanks! I'll have a look.


> handle this in Lua, at the tail end of reader.lua

IIRC, I'd need to wake up `awesome` to ask it to process `lipc` call then

**Comment by mergen3107** [comment]
> at the tail end of reader.lua

This is in the end of the `reader.lua`, where it refers to `Device:exit()`, and that function inlcudes:
```
    -- Save current rotation (or the original rotation if ScreenSaver temporarily modified it) to remember it for next startup
    G_reader_settings:saveSetting("closed_rotation_mode", self.orig_rotation_mode or self.screen:getRotationMode())
```
Let me play around these.

**Comment by mergen3107** [comment]
> My problem at the moment is that I cannot force Kindle to rotate via commands.
> `lipc-set-prop com.lab126.winmgr orientationLock U` only updates `orientationLock`, orientation stays the same (outside KOReader).
> `lipc-set-prop com.lab126.winmgr accelerometer U` says it is not permitted.
https://github.com/koreader/koreader/issues/11180#issuecomment-1869180423

I realized I am stuck here. I won't able to change Kindle orientation by commands at all.

**Comment by mergen3107** [comment]
I give up on this ticket. Kindle doesn't let me rotate the screen UI, I can only "rotate" touch sensor and orientation lock.
