### ISSUE TITLE
Crash on tolino page 2

### ISSUE THREAD

**Issue by RubixDev** [koreader/koreader#11264]
* KOReader version: v2023.10
* Device: tolino page 2 (should be similar to Kobo devices)
  * Android version: 4.4.2
  * tolino version: 16.1.0

#### Issue
I installed KOReader on my tolino following [this guide](https://gist.github.com/hasezoey/d16ba0f980f00cd2193132afe4714c7c), but every time I try to launch the app I get a crash message. I also tried with v2023.06.1 with the same result, and with nightly v2023.10-70-ge7ee900cb_2023-12-22 which resulted in another crash, also at startup.

It looks like the issue is related to KOReader not being able to find/initialize luajit. Further up the log it also says `VM with version 1.6.0 does not have multidex support`, in case that's important or related.

#### Steps to reproduce
Follow [this guide](https://gist.github.com/hasezoey/d16ba0f980f00cd2193132afe4714c7c) to install KOReader and some launcher, then launch KOReader and observe the crash.

##### `crash.log` (if applicable)
~Sorry, but I was unable to find the crash log file anywhere on the device, and I wasn't able to save the report as no app was installed to "send" it to. Instead I made screenshots of what I deemed to be the critical parts of the log.~

<details>
  <summary>crash.log</summary>

```
--------- beginning of /dev/log/main
12-25 10:53:55.393 I/MultiDex( 4864): VM with version 1.6.0 does not have multidex support
12-25 10:53:55.393 I/MultiDex( 4864): Installing application
12-25 10:53:55.393 I/MultiDex( 4864): MultiDexExtractor(/data/app/org.koreader.launcher-2.apk, /data/data/org.koreader.launcher/code_cache/secondary-dexes)
12-25 10:53:55.393 I/MultiDex( 4864): Blocking on lock /data/data/org.koreader.launcher/code_cache/secondary-dexes/MultiDex.lock
12-25 10:53:55.393 I/MultiDex( 4864): /data/data/org.koreader.launcher/code_cache/secondary-dexes/MultiDex.lock locked
12-25 10:53:55.393 I/MultiDex( 4864): MultiDexExtractor.load(/data/app/org.koreader.launcher-2.apk, false, )
12-25 10:53:55.403 I/MultiDex( 4864): loading existing secondary dex files
12-25 10:53:55.403 I/MultiDex( 4864): load found 1 secondary dex files
12-25 10:53:55.403 I/MultiDex( 4864): install done
12-25 10:53:55.403 I/dalvikvm( 4864): Could not find method android.content.Context.getExternalMediaDirs, referenced from method androidx.core.content.FileProvider.parsePathStrategy
12-25 10:53:55.403 W/dalvikvm( 4864): VFY: unable to resolve virtual method 288: Landroid/content/Context;.getExternalMediaDirs ()[Ljava/io/File;
12-25 10:53:55.403 D/dalvikvm( 4864): VFY: replacing opcode 0x6e at 0x00af
12-25 10:53:55.423 I/dalvikvm( 4864): Could not find method android.os.Environment.isExternalStorageManager, referenced from method org.koreader.launcher.MainActivity.hasMandatoryPermissions
12-25 10:53:55.423 W/dalvikvm( 4864): VFY: unable to resolve static method 845: Landroid/os/Environment;.isExternalStorageManager ()Z
12-25 10:53:55.423 D/dalvikvm( 4864): VFY: replacing opcode 0x71 at 0x000d
12-25 10:53:55.423 I/dalvikvm( 4864): Could not find method android.os.PowerManager.isIgnoringBatteryOptimizations, referenced from method org.koreader.launcher.MainActivity.canIgnoreBatteryOptimizations
12-25 10:53:55.423 W/dalvikvm( 4864): VFY: unable to resolve virtual method 903: Landroid/os/PowerManager;.isIgnoringBatteryOptimizations (Ljava/lang/String;)Z
12-25 10:53:55.423 D/dalvikvm( 4864): VFY: replacing opcode 0x6e at 0x001f
12-25 10:53:55.423 I/dalvikvm( 4864): Could not find method android.provider.Settings$System.canWrite, referenced from method org.koreader.launcher.MainActivity.canWriteSystemSettings
12-25 10:53:55.423 W/dalvikvm( 4864): VFY: unable to resolve static method 927: Landroid/provider/Settings$System;.canWrite (Landroid/content/Context;)Z
12-25 10:53:55.423 D/dalvikvm( 4864): VFY: replacing opcode 0x71 at 0x000d
12-25 10:53:55.433 I/dalvikvm( 4864): Could not find method android.app.NativeActivity.onRequestPermissionsResult, referenced from method org.koreader.launcher.MainActivity.onRequestPermissionsResult
12-25 10:53:55.433 W/dalvikvm( 4864): VFY: unable to resolve virtual method 212: Landroid/app/NativeActivity;.onRequestPermissionsResult (I[Ljava/lang/String;[I)V
12-25 10:53:55.433 D/dalvikvm( 4864): VFY: replacing opcode 0x6f at 0x000a
12-25 10:53:55.443 I/MainActivity( 4864): loading libluajit
12-25 10:53:55.443 D/AndroidRuntime( 4864): Shutting down VM
12-25 10:53:55.443 W/dalvikvm( 4864): threadid=1: thread exiting with uncaught exception (group=0x40d32ba8)
12-25 10:53:55.443 W/System.err( 4864): java.lang.UnsatisfiedLinkError: Couldn't load luajit from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.koreader.launcher-2.apk", zip file "/data/data/org.koreader.launcher/code_cache/secondary-dexes/org.koreader.launcher-2.apk.classes2.zip"],nativeLibraryDirectories=[/data/app-lib/org.koreader.launcher-2, /system/lib]]]: findLibrary returned null
12-25 10:53:55.443 W/System.err( 4864): 	at java.lang.Runtime.loadLibrary(Runtime.java:358)
12-25 10:53:55.443 W/System.err( 4864): 	at java.lang.System.loadLibrary(System.java:526)
12-25 10:53:55.443 W/System.err( 4864): 	at org.koreader.launcher.MainActivity.<init>(MainActivity.kt:6)
12-25 10:53:55.443 W/System.err( 4864): 	at java.lang.Class.newInstanceImpl(Native Method)
12-25 10:53:55.443 W/System.err( 4864): 	at java.lang.Class.newInstance(Class.java:1208)
12-25 10:53:55.443 W/System.err( 4864): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
12-25 10:53:55.443 W/System.err( 4864): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
12-25 10:53:55.443 W/System.err( 4864): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
12-25 10:53:55.443 W/System.err( 4864): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
12-25 10:53:55.443 W/System.err( 4864): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
12-25 10:53:55.443 W/System.err( 4864): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-25 10:53:55.443 W/System.err( 4864): 	at android.os.Looper.loop(Looper.java:136)
12-25 10:53:55.443 W/System.err( 4864): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
12-25 10:53:55.443 W/System.err( 4864): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-25 10:53:55.443 W/System.err( 4864): 	at java.lang.reflect.Method.invoke(Method.java:515)
12-25 10:53:55.443 W/System.err( 4864): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
12-25 10:53:55.443 W/System.err( 4864): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
12-25 10:53:55.443 W/System.err( 4864): 	at dalvik.system.NativeStart.main(Native Method)
```

</details>

<details>
  <summary><strike>Crash in v2023.10</strike></summary>

![screenshot_20231225_090429](https://github.com/koreader/koreader/assets/35602040/73c4a422-4224-4dde-805d-5dab9d8e6ce7)
</details>

<details>
  <summary><strike>Crash in v2023.10-70-ge7ee900cb_2023-12-22</strike></summary>

![screenshot_20231225_094009](https://github.com/koreader/koreader/assets/35602040/26f7e113-8f86-4710-86ee-332cb410e355)
</details>

**Comment by mergen3107** [comment]
> I was unable to find the crash log file anywhere on the device, and I wasn't able to save the report as no app was installed to "send" it to.

Are you able to install a file manager? E.g., Total Commander?

**Comment by mergen3107** [comment]
You device, `Tolino Page 2`, is not added to list of supported devices yet: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt

However, first step is at least to make KOReader open, so you can get enough information about device specs and make a request here: https://github.com/koreader/koreader/issues/8482

**Comment by mergen3107** [comment]
> * Device: tolino page 2 (should be similar to Kobo devices)

Don't steer in the wrong direction, they might be identical in hardware, but completely different in software. Android is... not great with eink, to put it mildly.

**Comment by RubixDev** [comment]
> Are you able to install a file manager? E.g., Total Commander?

I edited the issue to include the full log now.

> Your device, Tolino Page 2, is not added to list of supported devices yet: [koreader/android-luajit-launcher@master/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/DeviceInfo.kt?rgh-link-date=2023-12-25T02%3A47%3A03Z)

Oh I see. From that guide I somehow assumed all tolino devices would work :shrug:.

> However, first step is at least to make KOReader open, so you can get enough information about device specs and make a request here: https://github.com/koreader/koreader/issues/8482

Sadly, even trying to launch the TestActivity with ADB only shows me the tolino error popup saying "An error has occurred and all actions have been aborted. Please try again or restart your tolino." and as far as i can tell no `test.log` is created anywhere :cry:.

**Comment by mergen3107** [comment]
Which version of apk did you try to install?

**Comment by RubixDev** [comment]
> Which version of apk did you try to install?

KOReader is on v2023.10 again

**Comment by mergen3107** [comment]
No, I meant which architecture.
https://github.com/koreader/koreader/releases/tag/v2023.10
There are: "arm", "arm64", "x86" for Android. I believe you need only "arm".

**Comment by RubixDev** [comment]
oh pff i feel stupid now. the arm version launches just fine. However I can't find the "Developer options" to run the driver tests, and from what I can tell the frontlight isn't working.

**Comment by RubixDev** [comment]
Thanks for your help, everything is working now. I didn't realize that FM stands for File Manager and the manual was still open so I didn't see the developer tools, and the frontlight slider obviously only does something when the frontlight is turned on :facepalm:.

**Comment by mergen3107** [comment]
You are on the right track!

Dev options are available only from File Manager, so you need to exit the book

**Comment by mergen3107** [comment]
Great, welcome to KOReader! 
I am surprised it started working as is. 

If you have time, please add a request to add your exact model (and other specs) in the ticket I mentioned earlier.

**Comment by Frenzie** [comment]
> Oh I see. From that guide I somehow assumed all tolino devices would work 🤷.

In short all Android devices should work but special eink support needs to be implemented separately.
