### ISSUE TITLE
Can't go to next file when 'show_finished' is disabled and the book is marked as finished

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#11266]
After https://github.com/koreader/koreader/pull/10895, when disabling the 'show_finished' option and reaching the end of the book menu, we can't go to the next file if the current book is marked as finished.

mark_finished
![mark_finished](https://github.com/koreader/koreader/assets/4573505/d0dd7494-3678-41d6-88dd-8a7c97188f3b)

next_file
![next_file](https://github.com/koreader/koreader/assets/4573505/c8d402e4-e723-4f3e-a7fc-b6152ffcebb3)

message
![message](https://github.com/koreader/koreader/assets/4573505/73a4ea4c-4951-459f-833f-b4d2f7488b24)

**Comment by hius07** [comment]
If "Show finished" is **unchecked**, searching for the next book should skip finished books, definitely, the user explicitly doesn't want to see them.
What if "Show finished" is **checked**? Skip finished books too?

**Comment by NiLuJe** [comment]
For the "next file" thing? I would naively assume skip finished, always, but that's not my usual flow, so don't take this too seriously ;).

**Comment by hius07** [comment]
> For the "next file" end of book thing?

And we have an action in Dispatcher for this.

I also feel to always skip finished books.

**Comment by Frenzie** [comment]
> For the "next file" end of book thing? I would naively assume skip finished, always, but that's not my usual flow, so don't take this too seriously ;).

I would too.
