### ISSUE TITLE
FR: "Auto warmth on" option

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11274]
**Does your feature request involve difficulty completing a task? Please describe.**
Since there is the option "Auto warmth off", could there also be the option "Auto warmth on" or at least the option "toggle Auto warmth"?

Thank you!

**Comment by NiLuJe** [comment]
What are we talking about here?

**Comment by NiLuJe** [comment]
(And on which device. Sidenote: please don't ignore the issue template).

**Comment by ichnilatis-gr** [comment]
> (And on which device. Sidenote: please don't ignore the issue template).

Excuse me, but in the feature request there isn't such a template that asks for the device brand.
We can set for a gesture the option "Auto warmth off", but there isn't an option such as "Auto warmth on", instead we have to cycle through all the warmth modes to find the one we want, when we want to turn on the warm light.

**Comment by NiLuJe** [comment]
> Excuse me, but in the feature request there isn't such a template that asks for the device brand.

Good to know, that's potentially a problem for potentially hardware-specific requests ;).

**Comment by NiLuJe** [comment]
> there isn't an option such as "Auto warmth on"

Because there's no really a notion of "on", AFAICT, it's a multistate between off/whatever/all/the/enabled/modes/are ;).

**Comment by ichnilatis-gr** [comment]
@zwim is this possible?
The problem is that, if we want to enable the "Auto warmth" with a gesture, we have to cycle through all the warmth modes till we find the one we had before we close it. This means 4 gestures.
