### ISSUE TITLE
Q: Developer options from Reader - Guidance

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11276]
Many (_many_) times I've seen people stumble upon this situation:
1) A user opens a brand new KOReader - it opens User Guide in Reader.
2) Finds a bug soon, then go to create a new bug report ticket on GH.
3) It says, enable Verbose logs from top menu - developer options, do the bug again and bring the crash.log here.
4) User gets stuck, because `Developer options` menu entry is only available from FM. The come here to ask - making useful debugging times to be postponed by hours/days.

Now that we have this (phenomenal!) feature called `Menu search` - `Walk me there`, I suggest the following:
1) In the Reader's Top menu - `Tools` - `More Tools`: create another menu entry that says `Developer Options (walk me there)`.
2) Once pressed, the button would close the top menu, exit to FM, then use the same code path as if the user searched for "developer" in the `Menu search` and hit the `Walk me there` button.

This will, I think/hope, tremendously improve the quality of bug reports.

Alternatively, just making a passive grayed out button that says `Developer options (open from File Manager)`.

Thanks!

**Comment by Frenzie** [comment]
> Alternatively, just making a passive grayed out button that says `Developer options (open from File Manager)`.

I think that's just an awkward way of saying to enable it there too. :-D

I forget what the exact rationale was, probably to have it a bit out of the way most of the time.

**Comment by mergen3107** [comment]
I meant more like asking user to open it from FM. Or maybe "...(must be opened from FM)".

**Comment by offset-torque** [comment]
> **zwim** - I never understood why the tools menu is differemt in reader amd fm.

I remember being confused by this too. Unification might be the logical solution.

**Comment by pazos** [comment]
>> zwim - I never understood why the tools menu is differemt in reader amd fm.

> I remember being confused by this too. Unification might be the logical solution.

No real idea about the underlying cause, pinging @poire-z about CRe specific actions and @NiLuJe about the blitbuffer. Are they safe to run from a reader instance?.

If they're safe I would also vote for unification.

**Comment by poire-z** [comment]
No idea - I don't really want to look and guess, and possibly guess bad, and have them in Reader where they may not work as expected and cause more issues and bad feedback :)
Lots of those items just ask for a restart. If the CRE ones don't, it's because they may work on the next CreDocument instance and a restart is not needed.
May be just have the log related ones in Reader: might be useful to just enable them for a few second doing the action.

**Comment by NiLuJe** [comment]
I couldn't tell you anything about the history of this, but many things are indeed specific to the view they only appear on, so I don't quite think a total unification would make any sort of sense?

But, yeah, we could definitely duplicate a few of the "generic enough" ones ;).

**Comment by mergen3107** [comment]
> But, yeah, we could definitely duplicate a few of the "generic enough" ones ;).

+1! Main motivation in the OP is only because Issue template asks for verbose logs. I don't think most people understand any other dev options (including me, except dithering :D)

**Comment by hius07** [comment]
In the Help menu (last tab) there is an item "Report a bug" that mentions and shows the path to crash.log.
Maybe place "Verbose log" next to it?

**Comment by NiLuJe** [comment]
Hmm, *also* moving the debug options out of the dev settings is another interesting idea, yeah...

**Comment by mergen3107** [comment]
Since #11366 was implemented, would you like to edit the ticket template so it points to `Top menu - Hamburger menu - Help - Report a bug - Enable verbose logging`, then ask them to agree to restart and reproduce the bug?

**Comment by Frenzie** [comment]
I don't have time atm, but the template lives in https://github.com/koreader/koreade/.github/ISSUE_TEMPLATE/bug_report.md
