### ISSUE TITLE
FR: Full page refresh after waking up from a deep sleep.

### ISSUE THREAD

**Issue by sndwichm4n** [koreader/koreader#11270]
I have a Kindle OA3. When it is in sleep mode and is woken up, there is a shadow of the cover until a few pages have been turned and the page is fully refreshed.

Please add a function to automatically refresh the page after sleep mode.

**Comment by sndwichm4n** [comment]
And than you very much for Koreader <3

**Comment by mergen3107** [comment]
Short diagonal swipe will fully refresh the screen.

**Comment by sndwichm4n** [comment]
OhoOoooo... that is nice.


But what do you think of my suggestion to add this as an option?

**Comment by mergen3107** [comment]
I don't really have an opinion on this. Let's wait for others

**Comment by Frenzie** [comment]
I thought a full refresh already happened automatically on resume (on Kobo).

**Comment by NiLuJe** [comment]
I seem to recall already doing something funky to handle deep sleep, so I'm not quite sure we can do much more than what already happens.

**Comment by sndwichm4n** [comment]
> double flashing would be way way way worse

Why that? I thinks it is better to have a clean picture.

**Comment by NiLuJe** [comment]
Because we don't control the timing, making it extremely irritating for no good reaosn, as it doesn't serve much purpose without precise control over the timing, and you can instead

> Short diagonal swipe will fully refresh the screen.

**Comment by jospalau** [comment]
This happens to me at least in my Clara 2E. You can set up Keep the screensaver on screen after wake-up to 1 second. That fixed it for me.

**Comment by sndwichm4n** [comment]
How did you do that?

**Comment by jospalau** [comment]
You will find the option in the screensaver configuration

**Comment by sndwichm4n** [comment]
Foud it. But doesn't solve the problem on kindle.

But thanks anyway.

**Comment by NiLuJe** [comment]
The here's a stupid [userpatch](https://github.com/koreader/koreader/wiki/User-patches):

`2-double-refresh-on-outofscreensaver.lua`
```lua
local DeviceListener = require("device/devicelistener")
local UIManager = require("ui/uimanager")

function DeviceListener:onOutOfScreenSaver()
    UIManager:tickAfterNext(function()
        UIManager:setDirty(nil, "full")
    end)
end
```

**Comment by sndwichm4n** [comment]
> Then here's a stupid [userpatch](https://github.com/koreader/koreader/wiki/User-patches):
> 
> `2-double-refresh-on-outofscreensaver.lua`
> 
> ```lua
> local DeviceListener = require("device/devicelistener")
> local UIManager = require("ui/uimanager")
> 
> function DeviceListener:onOutOfScreenSaver()
>     UIManager:tickAfterNext(function()
>         UIManager:setDirty(nil, "full")
>     end)
> end
> ```

Best patch of the world!

**Comment by na1coss** [comment]
> > Then here's a stupid [userpatch](https://github.com/koreader/koreader/wiki/User-patches):
> > `2-double-refresh-on-outofscreensaver.lua`
> > local DeviceListener = require("device/devicelistener")
> > local UIManager = require("ui/uimanager")
> > 
> > function DeviceListener:onOutOfScreenSaver()
> >     UIManager:tickAfterNext(function()
> >         UIManager:setDirty(nil, "full")
> >     end)
> > end
> 
> Best patch of the world!

I tried it on my Boox Palma 2 but apparently the black screen keeps on appearing now and then...
