### ISSUE TITLE
Progress sync not working

### ISSUE THREAD

**Issue by beam0511** [koreader/koreader#11271]
* KOReader version: 23.10 
* Device: Kobo Libra 2 and Clara 2E

#### Issue
Hello. This is my first time using KOReader. The setup process and everything is working well but the progress sync feature seems to be not working. I tried to register an account in the "Progress sync" menu but failed because of an "Unknown server error".
I would appreciate any support as the Progress sync is the main reason I use KOReader for my two Kobo devices.

**Comment by mergen3107** [comment]
Servers are down temporarily. Wait 1-2 days

**Comment by beam0511** [comment]
> Servers are down temporarily. Wait 1-2 days

Thank you for the kind response!

**Comment by mergen3107** [comment]
Server is back!
