### ISSUE TITLE
Kindle Scribe: enable HW dithering support

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11286]
https://github.com/koreader/koreader/blob/57cbde5901cfd9c5d637575ec3309cb87ab54659/frontend/device/kindle/device.lua#L642-L643

I changed this to `yes`, then restarted KOReader and now I can see two mutually exclusive `Disable HW dithering` and `Disable SW dithering` in the Developer's options. 

I can confirm dithering works in muPDF with the bottom menu toggle.
I can say there is much difference between SW/HW dithering (by eye).

Is there anything else I should test? Somewhere where it can break?

**Comment by NiLuJe** [comment]
Nope, it didn't do anything at all on the PW5, so that's kinda it ;p.

**Comment by mergen3107** [comment]
Cool! :D 
Are there any advantages of HW vs SW dithering?
What is _hardware_ dithering, by the way? I many times didn't understand this, because ultimately all computations are done by the same chip :D

**Comment by NiLuJe** [comment]
Nope, they're handled by the "GPU" in the HW cases (e.g., the PxP on NXP SoCs, or the MDP on MTK).

**Comment by mergen3107** [comment]
Thanks! Got it :)
