### ISSUE TITLE
FR: Better D-pad support on K4/5

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11295]
Hi KoReader team,

I am a new KoR user, I am using a Black Kindle 4/5 (B023, K4) and running version 2023.10.
My issue concerns the D-pad, currently the D-pad is set to individual page turns (either forwards or backwards) for both up/down and left/right, however the kindle already has two sets of turn page buttons which makes it a total of FOUR sets of buttons doing exactly the same job. 

I was wondering if you guys could make the D-pad behave the same way the stock firmware does, i.e left/right moves you to previous/next chapter and up/down allows you to select words for dictionary lookup or highlights.

This leads me to another issue and much in the same spirit as before, the only way of selecting words is using 'content selection' which is at best annoying on non-touch kindles. so once again, I am wondering whether 'content selection' could be added via d-pad instead in much the same way stock firmware does it (up/down).

Also, the keyboard button does not do anything whatsoever, it would be nice if you could map it to either 'full text search' or to give the user the option to select what they'd like to do. For example turn wifi on/off.

thank you for your time and consideration.
commodore64user

**Comment by Commodore64user** [comment]
Thinking about this, would it be possible to re-map the left/right to next chapter (when inside a book), and up/down to trigger this feature from #8877 using a user patch?

**Comment by Frenzie** [comment]
If any of those are currently mapped to any button events it might be simpler still.
https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/device/kindle/event_map_keyboard.lua

I don't have time to investigate right now, but what you're asking should probably be relatively straightforward (although you never know when something's strongly dependent on something else).

**Comment by Commodore64user** [comment]
> If any of those are currently mapped to any button events it might be simpler still. https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/device/kindle/event_map_keyboard.lua
> 
> I don't have time to investigate right now, but what you're asking should probably be relatively straightforward (although you never know when something's strongly dependent on something else).

if you find some time to look into it, it would be amazing, as I don't know how to implement it.

**Comment by Commodore64user** [comment]
I've removed the `hasFewKeys` but continues to work the same way, I've also created two more but don't know what to use in the `event` field.

```lua
self.key_events.GotoNextPage = {
    { "RPgFwd", "LPgFwd" },
    event = "GotoViewRel",
    args = 1,
}
self.key_events.GotoPrevPage = {
    { "RPgBack", "LPgBack" },
    event = "GotoViewRel",
    args = -1,
}
-- self.key_events.GotoNextChapter = {
--     { "Right" },
--     event = "",
--     args = 1,
-- }
-- self.key_events.GotoPrevChapter = {
--     { "Left" },
--     event = "",
--     args = -1,
-- }
```

**Comment by Frenzie** [comment]
Ah sorry, that was slightly more of a note to self, but you're probably testing ReaderRolling:
https://github.com/koreader/koreader/blob/d3011571a391fea30a2dfa2ecfc2cc215d9e061a/frontend/apps/reader/modules/readerrolling.lua#L119-L130

It's broadly speaking PDF/DjVu/CBZ/etc. ("paged") vs EPUB/FB2/etc (er, "rolling" in the code but something like "dynamic" might be more descriptive).

**Comment by Frenzie** [comment]
PS I think GotoNextChapter should be correct.

**Comment by Frenzie** [comment]
hasFewKeys primarily implies that a device doesn't have a back button, which really gets in the way of regular navigation. For a proper interface at a minimum you want four directions, back, and enter. Unfortunately that doesn't imply also having page up/down.

Annoyingly, I don't really see a way out of that without `hasPageUpDownKeys`, although it's possible that it's better left as a user patch.

**Comment by Commodore64user** [comment]
Kindles definitely have back button, and a d-pad

**Comment by Frenzie** [comment]
It's not Kindles I'm talking about. My point is we don't want to make something else unusable where the left/right thing isn't redundant but actively necessary.

**Comment by Frenzie** [comment]
That's the bad version of `hasPageUpDownKeys`. ;-)

**Comment by Commodore64user** [comment]
But isn’t `hasPageUpDownKeys` a subgroup of `hasDPad`?

**Comment by Frenzie** [comment]
Currently it's merely the outline of a potential concept.

But I think it is (or rather, would be) its own independent thing. It's only the combination of `hasKeys` and/or `hasDPad` together with `hasPageUpDownKeys` that would enable a repurposing of left/right for chapter navigation.

**Comment by Frenzie** [comment]
But to explain a bit more, something like `isKindle()` should almost never be seen in code, or at least not at this level of abstraction. `canDoSwipeAnimation()` is currently Kindle-exclusive but that way it's useful in the future rather trouble in the future.

https://github.com/koreader/koreader/blob/87c85bf94d16a00df87d970522b36a2755197aa3/frontend/device/generic/device.lua#L26-L139

**Comment by Commodore64user** [comment]
I see, so a little more complex than expected. What would I need to do to re-map locally (user patch) the up/down buttons to 'start content selection' and the keyboard button to do something? For now at least.

**Comment by Commodore64user** [comment]
Screenshots, that too

**Comment by Commodore64user** [comment]
Wait a second, but the `hasFewKeys` is only used for PDF/DjVu/CBZ/etc. Seems to me ePubs are not constrained by that? Or am i reading something wrong?

**Comment by Frenzie** [comment]
That is likely an oversight on my end. Quoting from #6195:

> In the reader, the right is repurposed to open the menu. Left in turn closes it.

I'm building the program right now, but on this older laptop it'll take a while.

So on a normal device, left/right and up/down are already in use for page turning vs relative position changing. The former is somewhat similar in purpose to what you'd prefer to be chapters instead. (A PDF page is typically taller than the screen, meaning it'll take two page turns to get through fully.)

**Comment by Commodore64user** [comment]
another thing, for some reason the top menu does not respect the hierarchy of the 'Home' button. When you go deep into the menus the 'home' button doesn't do anything, when it should take you back to the file browser.

**Comment by Frenzie** [comment]
Home button?

**Comment by Commodore64user** [comment]
![Screenshot 2024-04-19 at 15 48 56](https://github.com/koreader/koreader/assets/97603719/e0ff4edd-80a1-4ad3-b00f-01de6f8d2245)

Here is a picture of a kindle 4/5 non-touch. They have: `back`, `keyboard`, `menu` and `Home` buttons on top of the `D-Pad` and `Enter`. They are all underutilised in KOReader.

**Comment by Frenzie** [comment]
That home button is implemented already. Feel free to add it elsewhere if appropriate.

**Comment by Commodore64user** [comment]
> That home button is implemented already.

Yes, but not across the whole UI, deep in menus it won't take you back to the Home Screen (file browser). that is what I was trying to say.

**Comment by Commodore64user** [comment]
So, I came up with this idea to temporarily add the previous/next chapter functionality to devices with page-turning redundancy, would this be something that could be added?

as far as I could see, the `if Device:hasKeys() and Device:hasDPad()` rules out everyone apart from non-touch kindles.

```lua
    if Device:hasKeys() and Device:hasDPad() then
        self.key_events.GotoNextView = {
            { { "RPgFwd", "LPgFwd" } },
            event = "GotoViewRel",
            args = 1,
        }
        self.key_events.GotoPrevView = {
            { { "RPgBack", "LPgBack" } },
            event = "GotoViewRel",
            args = -1,
        }
    elseif Device:hasKeys() then
        self.key_events.GotoNextView = {
            { { "RPgFwd", "LPgFwd", "Right" } },
            event = "GotoViewRel",
            args = 1,
        }
        self.key_events.GotoPrevView = {
            { { "RPgBack", "LPgBack", "Left" } },
            event = "GotoViewRel",
            args = -1,
        }
    end
    if Device:hasDPad() and Device:hasKeys() then
        self.key_events.MoveUp = {
            { "Up" },
            event = "Panning",
            args = {0, -1},
        }
        self.key_events.MoveDown = {
            { "Down" },
            event = "Panning",
            args = {0,  1},
        }
        self.key_events.GotoNextChapter = {
            { "Right" },
            event = "GotoNextChapter",
            args = 1,
        }
        self.key_events.GotoPrevChapter = {
            { "Left" },
            event = "GotoPrevChapter",
            args = -1,
        }
    elseif Device:hasDPad() then
        self.key_events.MoveUp = {
            { "Up" },
            event = "Panning",
            args = {0, -1},
        }
        self.key_events.MoveDown = {
            { "Down" },
            event = "Panning",
            args = {0,  1},
        }
    end
```

**Comment by Frenzie** [comment]
Perhaps, but my point with `hasPageUpDownKeys` is that I don't know if `hasKeys` means those are available. I think `hasKeys` is just a catchall to register events for a bunch of keys.

**Comment by Commodore64user** [comment]
> Perhaps, but my point with `hasPageUpDownKeys` is that I don't know if `hasKeys` means those are available. I think `hasKeys` is just a catchall to register events for a bunch of keys.

yes, I understand. I too tried to make sense of the `hasKeys` and it seems to refer to page turn buttons (at least) or more excluding DPads, for example, kindle Oasis (which has just two page turn buttons) has the tag `hasKeys`. The problem I had was then, with Remarkable, which has the tag `hasKeys` but it does not have keys, so who knows
https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/device/remarkable/device.lua#L32-L50

If I understand correctly, the remarkables are inheriting from the generic model, right? why does it say that they have keys, I don't know.

the `hasFewKeys` seems to refer to devices that might have page turn buttons but are not exclusively used for that, some act like back buttons when not in reading mode. pocketbook 611 is an example.

Anyway so my approach then was to see, which devices have both `hasKeys` and `hasDPad` and only kindles do (sdl too, which I assume is the emulator, right?). So this would maintain existing behaviour everywhere and only change it for kindles.

**Comment by Frenzie** [comment]
That sounds like you tried to find a way to write `isKindle` without writing `isKindle`, which strongly suggests a user patch would be more appropriate than changing anything at all imho.

**Comment by Commodore64user** [comment]
> That sounds like you tried to find a way to write `isKindle` without writing `isKindle`, which strongly suggests a user patch would be more appropriate than changing anything at all imho.

Not really, that was just a happy coincidence. It is still abstract and doesn't break anything for anyone else.

and as I said, it would be temporary until the whole thing gets sorted out with your older laptop. 😅

**Comment by Frenzie** [comment]
I only meant I couldn't test hasFewKeys right then and there. I'm not sure what bearing that has on anything else.

> It is still abstract and doesn't break anything for anyone else.

As stated a couple of weeks ago it "breaks" devices without page up/down if you don't add hasPageUpDownKeys. It also breaks the person's workflow who appreciates how it's always worked. Worse and far more fatally, it breaks DjVu/PDF (and crengine in continuous view mode).

If something is needed to facilitate user patching, let's focus on that. But this is for a user patch.

**Comment by Commodore64user** [comment]
> As stated a couple of weeks ago it "breaks" devices without page up/down if you don't add hasPageUpDownKeys. It also breaks the person's workflow who appreciates how it's always worked.

Wait, are you saying add a `hasPageUpDownKeys` to all kindles that have them and call them that way instead of the `if Device:hasKeys() and Device:hasDPad()`?

also, i am not breaking anything for anyone as this change would be limited to readerrolling only (i.e ePubs) for non-touch kindles, where the dpad is functioning 100 pc as redundancy.

> Worse and far more fatally, it breaks DjVu/PDF (and crengine in continuous view mode).

Could you talk a little bit more about this. In continous mode, the up/down do panning, which incidentally moves at a rate of about 2 lines per press.

**Comment by Commodore64user** [comment]
okay, how about this https://github.com/koreader/koreader/compare/master...Commodore64user:KOReader_fork:hasPageUpDownKeys?expand=1

I don't think I am breaking anything for anyone, just repurposing the left/right keys, which again are redundant. for the up/down we still would need to write new functions and discuss the "panning" on continuous mode issue. 

side note I found an example of a device that `hasKeys` but does not `hasPageUpDownKeys`, that is the kindle touch which has one, and only one button. a home button.

**Comment by Commodore64user** [comment]
I am trying to add this function that calls the content selector,

```lua
function ReaderRolling:onContentSelection()
    return self:onStartHighlightIndicator()            --  LINE 490
end
```
but I am getting this error 

> ./luajit: frontend/apps/reader/modules/readerrolling.lua:490: attempt to call method 'onStartHighlightIndicator' (a nil value)

I am clearly missing something, but not sure what exactly.

I have a `local ReaderHighlight = require("apps/reader/modules/readerhighlight")` also.

**Comment by poire-z** [comment]
You're missing some understanding on what is `self`.

`ReaderRolling:onContentSelection()` is equivalent to (with a dot instead of a colon):
`ReaderRolling.onContentSelection(self)` and the thing implicitely passed as `self` is the ReaderRolling instance on which the method is called (when calling `self:onContentSelection()`, self is the ReaderRolling instance).

So, when wanting to call `self:onStartHighlightIndicator()`, `self` is that ReaderRolling  instance, and it has no such onStartHighlightIndicator method (no `ReaderRolling.onStartHighlightIndicator` exists in that module).
It only exists in the ReaderHighlight module, and it wants a ReaderHighlight instance.
Which is/may be available, from the `self` ReaderRolling instance, as `self.ui.highlight`, so `self.ui.highlight:onStartHighlightIndicator()` should work.

And no need for a `local ReaderHighlight = require("apps/reader/modules/readerhighlight")` , which would just make the ReaderHighlight class available in the module (ie. to create a new ReaderHighlight instance, or call static methods not needing an instance) , but not the current/valid/lively instance.

**Comment by Frenzie** [comment]
> okay, how about this https://github.com/koreader/koreader/compare/master...Commodore64user:KOReader_fork:hasPageUpDownKeys?expand=1

Is the inversion between the conditions on purpose?

**Comment by Commodore64user** [comment]
> Is the inversion between the conditions on purpose?

do you mean `if hasPageUpDownKeys and hasDPad then` and `if hasDPad and hasPageUpDownKeys then`? if so, yes, kind of, I think it makes it easier for someone else to understand (maybe I am wrong?) that `if hasDPad and hasPageUpDownKeys` is a subset of `hasDPad`, same for the other one where `hasPageUpDownKeys` is a subset of `hasKeys`, although that might be less clear to someone unfamiliar with those functions/tags.

I thought about having the whole thing under one single `if` but then it would make the whole thing more complicated as nesting would be involved.

> so self.ui.highlight:onStartHighlightIndicator() should work.

well, well, well. Look who decided to show up. My favourite pear (i.e poire), version -z, saving the day once again. Thanks for the explanation!

**Comment by Frenzie** [comment]
> I think it makes it easier for someone else to understand (maybe I am wrong?)

I don't think that's wrong per se, but it does harm greppability.

**Comment by Commodore64user** [comment]
well in that case they could both be `hasPageUpDownKeys and hasDPad`, does not bother me at all.

> https://github.com/koreader/koreader/compare/master...Commodore64user:KOReader_fork:hasPageUpDownKeys?expand=1

now it is time to have _that_ conversation, my recent push does now break panning when on continuous mode. what to do? I tried adding a nested `if self.view.view_mode == "scroll"` and reverting up/down back to panning but it didn't seem to like that.

**Comment by Frenzie** [comment]
> not sure what it means, but it sounds terrible. In that case they could both be `hasPageUpDownKeys and hasDPad`, does not bother me at all.

It means that if you search for "this and that" to see if it occurs anywhere you'll miss "that and this". grep in its various forms is the standard text searching program. So yes, make them the same please.

> now it is time to have _that_ conversation, my recent commit does now break panning when on continuous mode. what to do? I tried adding a nested `if self.view.view_mode == "scroll"` and reverting up/down back to panning but it didn't seem to like that.

That wouldn't work; the event handlers are registered on load.

How bothered are we about continuous mode there @poire-z, if at all?

**Comment by poire-z** [comment]
> How bothered are we about continuous mode there @poire-z, if at all?

Haven't followed what's all this all about (happily not having a non-touch device, so not bothering), and not sure what you're asking me :/
Quick looking at the PR, if I get it right:
For devices with pageUp/pageDown, PageUp/pageDown moves one page (in page and in scroll mode). And because these PgUP/PgDown are available, we repurpose ArrowUp/Down (which did next/prev pages too, in page mode) to do "content selection" (= start text seection ?) ? And because of that, we lose the effect arrowUp/Down had in scroll mode where it moved by a fraction of the screen height (so, a few lines)?
If I get it right, I do think it's sad to lose that scroll by a few lines. I guess I'll miss that on the emulator.

If I got it right and you want to fix that, I guess you should send new events in your new code for ArrowUp/Down, and in the new handler(s), dispatch new events depending on the mode. 

I'm not really familiar with the non-touch stuff, and I don't really know the differences between hasKeys/hasDpad - and what the emulator "has".
And what keys NT Kindle users do use to change page - the equivalent of PgUp or ArrowUp? No risk of breaking anyone workflows if both did the same work? And they will have now different effects whether in page mode (content selection) and scroll mode (scroll by a few lines), so people possibly getting a confusing and non-consistent behaviour in one mode or the other.

And it seems it's all again different with PDF (no content selection?) :/

Again, not sure if I got it right and if it changes that much stuff, would be nice to ping some other Kindle NT users to discuss the changes and agree on some new behaviour if it's that much.

**Comment by Frenzie** [comment]
> If I get it right, I do think it's sad to lose that scroll by a few lines. I guess I'll miss that on the emulator.

Yes, me too. I think it's the evidently correct behavior but that might differ per device.

**Comment by Frenzie** [comment]
What I said was closer to calling that code smell.

But the fact is:

a. we like the current behavior 
b. the current behavior was originally implemented for Kindle and only for Kindle

**Comment by Commodore64user** [comment]
> a. we like the current behavior 

with all due respect, you might do, but you don't use non-touch kindles.

> b. the current behavior was originally implemented for Kindle and only for Kindle

yes, but there was no "content selection" at that time. why anyone thought having four sets of buttons doing the same was a great idea is beyond me. #4329 here is another example a somewhat similar suggestion btw

**Comment by Frenzie** [comment]
> with all due respect, you might do, but you don't use non-touch kindles.

Exactly, that's my point. :-) Everything has to be carefully considered, not just non-touch Kindles. And on non-touch Kindles you also have to consider everything, not just one particular document type in one particular view mode.

But we'll get there.

**Comment by Frenzie** [comment]
This might do the trick:

```lua
    if not Device:hasKeyboard() and Device:hasDPad() and Device:hasPageUpDownKeys() then
```

* `hasKeyboard` has better ways to trigger functionality (e.g., press `h` for highlight), so we want to maintain d-pad convenience when `hasKeyboard()` is true
* `hasDPad` by itself doesn't guarantee separate page up/down buttons (even if that might potentially be the case today), so:
* `hasPageUpDownKeys` means we can get rid of page turning functionality on the d-pad

**Comment by Frenzie** [comment]
> ```lua
>     if not Device:hasKeyboard() and Device:hasDPad() and Device:hasPageUpDownKeys() then
> ```

It might be preferable to abstract that away in a different manner to make it explicit rather than fully emergent. That would probably make it more obvious to future readers why it's doing these things.

Something along these lines for example:

```diff
diff --git a/frontend/device/generic/device.lua b/frontend/device/generic/device.lua
index a2f24426c..0e83dfe9b 100644
--- a/frontend/device/generic/device.lua
+++ b/frontend/device/generic/device.lua
@@ -43,6 +43,7 @@ local Device = {
     hasKeys = no,
     canKeyRepeat = no,
     hasDPad = no,
+    hasDPadWeaponSelect = no,
     hasExitOptions = yes,
     hasFewKeys = no,
     hasWifiToggle = yes,
@@ -231,6 +232,10 @@ function Device:init()
         end
     end
 
+    if not Device:hasKeyboard() and Device:hasDPad() and Device:hasPageUpDownKeys() then
+        self.hasDPadWeaponSelect = yes
+    end
+
     if self:hasGSensor() then
         -- Setup our standard gyro event handler (EV_MSC:MSC_GYRO)
         if G_reader_settings:nilOrFalse("input_ignore_gsensor") then
```

**Comment by poire-z** [comment]
Is that the device ? http://www.btobey.com/review/kindle-4-buttons.jpg
And the PgUP/Down buttons are on the ones on the side ?
Do people really use them ?! I'd find using the ones on the middle 5xsubbuttons-button easier, holding the device by its bottom. And if I do, other people may.
(So, may be it should be an option ? :/)

**Comment by Commodore64user** [comment]
> This might do the trick:
> 
> 
> 
> ```lua
> 
>     if not Device:hasKeyboard() and Device:hasDPad() and Device:hasPageUpDownKeys() then
> 
> ```
> 
> 
> 
> * `hasKeyboard` has better ways to trigger functionality (e.g., press `h` for highlight), so we want to maintain d-pad convenience when `hasKeyboard()` is true
> 
> * `hasDPad` by itself doesn't guarantee separate page up/down buttons (even if that might potentially be the case today), so:
> 
> * `hasPageUpDownKeys` means we can get rid of page turning functionality on the d-pad

But this is fragmenting the everything even more, and i'll be the devil's advocate this time, that does not seem good. I might as well say "model == Kindle4" or whatever it is. I think it is better to cover all non-touch equally in terms of dPad options. 

How about adding an option under "cog > navigation > physical buttons" where you choose either panning or content selection, even more options could be added (and force a restart like when activating/deactivating plugins). But that would require some effort from your end as i doubt i could pull that off.

**Comment by Frenzie** [comment]
> But this is fragmenting everything even more, and i'll be the devil's advocate this time, that does not seem good. I might as well say "model == Kindle4" or whatever it is. I think it is better to cover all non-touch equally in terms of dPad options.

People who like to use the d-pad would beg to differ. But I never said that adapting to the situation on the ground was bad, only that `== Kindle4` is almost always the wrong way to do so.

> How about adding an option under "cog > navigation > physical buttons" where you choose either panning or content selection, even more options could be added (and force a restart like when activating/deactivating plugins). But that would require some effort from your end as i doubt i could pull that off.

I suppose so. The defaults should still be as stated above or much like it regardless though. 

> Edit: should i make a PR now so we can all commit stuff?

At least as far as code goes that's easier to talk about, yes.

**Comment by Commodore64user** [comment]
> Is that the device ? 

Yes, it is. There was a picture in an earlier https://github.com/koreader/koreader/issues/11295#issuecomment-2066747242 

> And the PgUP/Down buttons are on the ones on the side? 

Yes, on both sides for right or left hand holding.

> Do people really use them?

Yes, although I personally prefer the page-turn-button style on the previous kindle 3 (keyboard), the device is light and quite easy to hold.

> I'd find using the ones on the middle 5xsubbuttons-button easier, holding the device by its bottom. And if I do, other people may.

I can't argue with that, preferences are indeed a personal thing.

>  (So, may be it should be an option ? :/)

That seems to be where we all have finally landed. yay all of us. #11749 is now open, so if you find yourself in need of helping someone out, feel free to drop by.

**Comment by poire-z** [comment]
> #11749 is now open, so if you find yourself in need of helping someone out, feel free to drop by.

Unlike Little Timmy, I'm quite disciplined: it's written "Non-touch", so non-touching it :)

**Comment by Commodore64user** [comment]
Hello all,

So I am trying to bring screenshots to non-touch devices but I was found wanting.

for reference this is our file and init()
https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/ui/widget/screenshoter.lua#L16-L34

and I am adding something like this to it (i.e `init()`):

```lua
if not Device:isTouchDevice() then
    if Device:hasKeyboard() then
        -- self.key_events = {
        --     KeyPressShoot = {
        --         Screenshot = { { "Shift" and "S" } },
        --     },
        -- }
    elseif Device:hasKeys() then     
        self.key_events.KeyPressShoot = { { { "Press", "Menu" } }, event = "KeyPressShoot", args = 1 }
    end
end
```

and this function of course:
```lua
function Screenshoter:onKeyPressShoot()
    return self:onScreenshot()
end
```

but it is not working as expected. With that code, `Press` alone is triggering the screenshots. any help would be highly appreciated. BTW, I am focusing on the `elseif` just now, so ignore the `hasKeyboard` if you want.

ps: I pay the screenshot tax (kindle 4) yay!
![Reader_2024-05-07_014905](https://github.com/koreader/koreader/assets/97603719/cd236057-78d8-473e-b1bd-77d8c0d4d86a)

**Comment by hius07** [comment]
Try to remove one pair of curly brackets.

**Comment by Commodore64user** [comment]
> Try to remove one pair of curly brackets.

I added the extra one `{ }` in the first place because it would not work without them, there is something else I am clearly ignoring but not sure what that might be.

**Comment by davigamer987** [comment]
Would be nice if there was a way to map the unused keyboard key on Kindle 4 to the selection mode

**Comment by Commodore64user** [comment]
> Would be nice if there was a way to map the unused keyboard key on Kindle 4 to the selection mode

there is a PR https://github.com/koreader/koreader/pull/11749 that will add better support, including selection mode tied to a press key, maybe not the ScreenKB key as it would not be consistent with the older kindles with keyboards.

**Comment by Commodore64user** [comment]
trying to run this now:
`self.key_events.KeyPressShoot = { {Key:match({ "ScreenKB", "Menu" })}, event = "KeyPressShoot", args = 1, }`
ps. I changed from "Press" to "ScreenKB", more inoffensive that way.
I get this: 

```
05/07/24-13:33:59 DEBUG input event => type: 4 (EV_MSC), code: 4 (nil), value: 0, time: 1715088839.177812 
05/07/24-13:33:59 DEBUG key event => code: 29 (ScreenKB), value: 0, time: 1715088839.177827 
05/07/24-13:33:59 DEBUG input event => type: 4 (EV_MSC), code: 4 (nil), value: 1, time: 1715088839.177836 
05/07/24-13:33:59 DEBUG key event => code: 139 (Menu), value: 0, time: 1715088839.177964 
05/07/24-13:33:59 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1715088839.177968 
05/07/24-13:33:59 DEBUG AutoSuspend: onInputEvent 
```

**Comment by Commodore64user** [comment]
Note to self: https://github.com/koreader/koreader/blob/e94550a26165dd94875ae31a62bddea0125caa71/frontend/ui/widget/touchmenu.lua#L513
