### ISSUE TITLE
(muPDF) crop issue when opening an image

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11291]
* KOReader version: v2023.10-55
* Device: Kindle Scribe (5.16.2)

#### Issue
When opening a PNG image with muPDF, it get cropped in a weird way that produces "holes" behind the canvas.

#### Steps to reproduce
I set crop to `auto` by default.
Open an image (PNG) using muPDF (long-tap in FM - open with).

See below images.

Crop `auto`: has a strip on the right from FM, and on the bottom there are remnants of the bottom menu (currenty closed). The image also looks to be shifted left.
![crop_auto_Reader_2023-12-27_205315](https://github.com/koreader/koreader/assets/6279855/0c27756e-59ae-4118-a5b2-476540364294)

Crop `none`: no issues, image is centered.
![crop_none_Reader_2023-12-27_205328](https://github.com/koreader/koreader/assets/6279855/779a4f7a-a506-4cd4-8351-b6ee7a264d95)

Original image:
![original_image_I, Robot](https://github.com/koreader/koreader/assets/6279855/42f6c7ee-76e7-49e2-89af-5e033a15e632)

##### `crash.log` (if applicable)
Here is the crash.log of:
- open KOReader (opened last file)
- go to FM
- go to Folder shortcuts - Pictures
- Long-tap an image, reset its settings
- Long-tap the image again, open with muPDF
- opened with crop `auto`
- go to bottom menu, switch to crop `none`
- refresh with a diagonal swipe

[mupdf_image_crop_crash.txt](https://github.com/koreader/koreader/files/13782662/mupdf_image_crop_crash.txt)

**Comment by NiLuJe** [comment]
Since it vaguely reminds me of the ReaderStatus thing: does it happen with the device at its default DPI?

**Comment by hugleo** [comment]
Can you also test if revering this commit https://github.com/koreader/koreader/pull/11194 you see any difference?

**Comment by mergen3107** [comment]
> does it happen with the UI set at its default auto DPI?

Yes, it does - image get shrinked down even more (slightly).



> Can you also test if revering this commit (or test semi-auto mide) #11194 you see any difference?

Reverting this solves it, it seems. There is no difference between `auto` and `none` now.

**Comment by hugleo** [comment]
I've read a lot of images and haven't found any that fail, so I've excluded auto-cropping from the rule and fixed the margins in some of my comics :). You provide a test case for failure now. Would ibe better to revert for now and revisit this in the future?

**Comment by NiLuJe** [comment]
> Would ibe better to revert for now and revisit this in the future?

Probably? This looks slightly worse than missing cropping, after all ;).

**Comment by hugleo** [comment]
Yes, to be safe I think. I can't reproduce here, maybe depends on device sizes.

**Comment by hugleo** [comment]
Looks like a letter was missing. I try all the letter possibilities at the end and guess the correct link :)
https://we.tl/t-2wzVfKgr2U

**Comment by hugleo** [comment]
I was reading a comic and saw the problem here on my device in one of the images.
When I find enough time I'll try to reproduce it on desktop for easy debugging and see if another fix is possible.

![-4949812065200091611_121](https://github.com/koreader/koreader/assets/4573505/b9a2b404-1b87-48de-9dff-48cbee4f7903)

**Comment by mergen3107** [comment]
Fixed by #11325 in v2024.03 release.
Thank you @hugleo !
