### ISSUE TITLE
No Network Settings - Desktop [flatpak]

### ISSUE THREAD

**Issue by F-U-B-AR** [koreader/koreader#11305]
**KOReader (flatpak)
Debian Linux**

Hello, I am trying to get "automatically keep documents in sync" option to work but I am met with "You will have to switch the "Action when WIFI is off" bar popping up. 

On the desktop version of KOReader program, I have no settings under the network section other than the HTTP proxy option. The time is also wrong, yet I have network access as I can sync progress manually?

Any help would be appreciated, 

Cheers

**Comment by Frenzie** [comment]
That should be fixed in the latest nightly but you'd have to try the AppImage or Debian package for thar instead of Flatpak.
