### ISSUE TITLE
FR: mixed view mode

### ISSUE THREAD

**Issue by Almaaa7** [koreader/koreader#11309]
**Does your feature request involve difficulty completing a task? Please describe.**
No, this is just a would-be-nice-to-have feature.

**Describe the solution you'd like**
A setting that would enable a "mixed view mode", where chapters of a book are displayed in continuous mode, but each chapter would be on its own separate 'page' (so the user would scroll to read within a chapter, but swipe/tap at the end of the chapter to jump to the next one).

**Additional context**
Some epub readers (like Lithium) function like this:

https://github.com/koreader/koreader/assets/70007627/d184c884-b3f5-47fc-8a21-5048accfaec8

**Comment by mergen3107** [comment]
Unless you need to keep positions within each chapter separately, just assign a gesture to go next/previous chapters (swipe with two fingers right/left, or along top/bottom edges), but stay in continuous mode.

**Comment by poire-z** [comment]
> Some epub readers (like Lithium) function like this:

It feels this behaviour is just the result of a simple (and fast) implementation of EPUB rendering: EPUBs are made of multiple html files, and this reader just loads and render one html file (what you call "chapter"), that it presents like in a web browser (so the scrolling of this single html page). When you reach the bottom, it loads and renders the next html file, etc...
There's no garantee in the EPUB specs that html files are split at chapters, nor that there is a page break at each new HTML file, or that there's only one chapter per HTML file.
This behaviour feels cheap and illogical, too bad you got used to liking it :) It does not fit in our model of a document (we concatenate all html files, and render the whole thing), so we probably will never have it.
Does Lithium have other "views" than this "mixed view", ie. full scroll or real pages cut ? Can it properly tell you the length of a book ?

**Comment by Almaaa7** [comment]
> assign a gesture to go next/previous chapters (swipe with two fingers right/left, or along top/bottom edges), but stay in continuous mode.

Thank you, this works for me.

> There's no garantee in the EPUB specs that html files are split at chapters

Most, if not all, of the epubs I own have each chapter in its own html file, but I agree that this implementation could be annoying to use with books that have multiple chapters per html file (or multiple html files per chapter).

> Does Lithium have other "views" than this "mixed view", ie. full scroll or real pages cut ?

Yes, paged.

> Can it properly tell you the length of a book ?

No.
