### ISSUE TITLE
Pocketbook Inkpad Color 3 viewport

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#11301]
* KOReader version: 2023.10
* Device: PB743K3

#### Issue

The screen for this device is covered by the bezel at about 3-4 pixels on each side.

#### Steps to reproduce

Cropping a pdf for example, will get the first/last character in a line partially visible. If you tilt the reader 45 degrees, you can see the full letter is displayed, but under the bezel.

I have the fix for this and I adjusted the viewport size for this model. Maybe other models with similar bezel have the same issue (Color 2? Inkpad 4?)

I can raise the PR to fix this soon or if you have any thougths on this, please let me know.

**Comment by hugleo** [comment]
Would be related to https://github.com/koreader/koreader/issues/11291 somehow?

**Comment by Frenzie** [comment]
Don't do anything for devices you haven't personally checked but please submit a PR for the Color 3. ^_^
