### ISSUE TITLE
Q: Can sdcv render images in word definitions?

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11312]
Some dictionaries have built-in images in the word definitions. For example, Longman Dictionary of Contemporary English 5th edition.

Can sdcv how them in word look up?

**Comment by Frenzie** [comment]
MuPDF can do that, yes. You might need to adjust the image path through a custom Lua file. I've written some samples… somewhere, but I can't find them right now. But it doesn't really matter because it's probably all very different and incompatible regardless. ;-)

**Comment by Frenzie** [comment]
The principle is the same. If the output references images you might have to give it a hand, for example:

```lua
return function(html)
    html = html:gsub('<img src="', '<img src="/path/to/')  
    return html
end
```

The specifics depend on the exact content.

There was a good test dictionary somewhere that I wanted to use to do some experiments with, but I can't find it. I think it may have been some other repo.

**Comment by mergen3107** [comment]
Thanks @Frenzie !

**Comment by mergen3107** [comment]
I placed images in `res/` directory.
Here is the raw output from sdcv:
```
<k>gull</k>
<c c="blue"><b>gull</b></c> /ɡʌl/ <abr>BrE</abr> <rref>bre_gull0205.wav</rref> <abr>AmE</abr> <rref>ame_gull1.wav</rref><i><c> noun</c></i><c c="green"> [countable]</c>
<blockquote><blockquote>[<c c="lightcoral">Date: </c><c c="darkgray">1400-1500</c>; <c c="lightcoral">Origin: </c><c c="darkgray">From a </c><c c="darkgray">Celtic</c><c c="darkgray"> language. </c>]</blockquote></blockquote>
<blockquote><blockquote><rref>gull.jpg</rref></blockquote></blockquote>
<blockquote><blockquote>  a large common black and white sea bird that lives near the sea<b><c c="darkblue"> SYN </c></b><b>seagull</b></blockquote></blockquote>
```

I am trying to follow this syntax for `<img>` tag: https://www.w3schools.com/tags/tag_img.asp

I did:
```
    html = html:gsub('<rref[^>]*>', '<img src="/mnt/us/koreader/data/dict/Longman/res/')
    html = html:gsub('.jpg</rref>', '.jpg">')
```

which converts
```
<rref>gull.jpg</rref>
```
to
```
<img src="/mnt/us/koreader/data/dict/Longman/res/gull.jpg">
```

However, in KOReader dict lookup it shows as `[image]`. Am I doing something wrong?

**Comment by mergen3107** [comment]
Here is my full `.lua` file that has been working all this time (I only added these two new `gsub`s):

```
return function(html)
    html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊')
    html = html:gsub('<k[^>]*>[^<]*%</k>', '')
    html = html:gsub('<c>', '<span>')
    html = html:gsub('</c>', '</span>')
    html = html:gsub('<c c=\"', '<span style=\"color:')
    html = html:gsub('\"color:indigo\"', '\"color:#4B0082\"')
    html = html:gsub('\"color:darkgray\"', '\"color:#A9A9A9\"')
    html = html:gsub('\"color:lightcoral\"', '\"color:#F08080\"')
    html = html:gsub('\"color:lightseagreen\"', '\"color:#20B2AA\"')
    html = html:gsub('\"color:darkgoldenrod\"', '\"color:#B8860B\"')
    html = html:gsub('<rref[^>]*>', '<img src="/mnt/us/koreader/data/dict/Longman/res/')
    html = html:gsub('.jpg</rref>', '.jpg">')
    return html
end
```

**Comment by Frenzie** [comment]
If you're sure it's indeed outputting what you think it's outputting, test it in MuPDF.

In XHTML that should be `<img/>`. I imagine you're just seeing the plain text fallback.

**Comment by mergen3107** [comment]
I enabled debug log to see the definition, and it seems to have problem with the double quotation mark:
```
<img src=\"/mnt/us/koreader/data/dict/Longman/res/gull.jpg\">
```

It is `\"` instead of `"`. Do you know how to escape it?
I tried `&quot;` and `&#34;`, but then even `[image]` doesn't show up.

**Comment by Frenzie** [comment]
Both at the very beginning and before the return, stick something like this:
```lua
local file = io.open("entry-with-image.xhtml", "w")
file:write(html)
file:close()
```

**Comment by mergen3107** [comment]
What should be `entry-with-image.xhtml`?
data/dict/Longman/Longman.dict.dz?

**Comment by Frenzie** [comment]
No, I mean you want to:

a. know the exact contents
b. test them in MuPDF independently because making adjustments is an estimated 10 million times faster ;-P

This is saying create a new file of that name with that content in it.

```lua
return function(html)

local file = io.open("entry-unprocessed.xhtml", "w")
file:write(html)
file:close()

    html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊')
    html = html:gsub('<k[^>]*>[^<]*%</k>', '')
    html = html:gsub('<c>', '<span>')
    html = html:gsub('</c>', '</span>')
    html = html:gsub('<c c=\"', '<span style=\"color:')
    html = html:gsub('\"color:indigo\"', '\"color:#4B0082\"')
    html = html:gsub('\"color:darkgray\"', '\"color:#A9A9A9\"')
    html = html:gsub('\"color:lightcoral\"', '\"color:#F08080\"')
    html = html:gsub('\"color:lightseagreen\"', '\"color:#20B2AA\"')
    html = html:gsub('\"color:darkgoldenrod\"', '\"color:#B8860B\"')
    html = html:gsub('<rref[^>]*>', '<img src="/mnt/us/koreader/data/dict/Longman/res/')
    html = html:gsub('.jpg</rref>', '.jpg">')


local file2 = io.open("entry-processed.xhtml", "w")
file2:write(html)
file2:close()

    return html
end
```

**Comment by mergen3107** [comment]
> In XHTML that should be <img/>.

The Longman dictionary in question is in html mode.

So now I am just looking how to properly add the forward slashes :D

**Comment by mergen3107** [comment]
> test them in MuPDF

Which file do I open in muPDF?

**Comment by mergen3107** [comment]
Alright, success! It turns out, the problem was that I included absolute path, but KOReader is happy with a path relative to `reader.lua`.

![Reader_2024-01-03_200051](https://github.com/koreader/koreader/assets/6279855/88adeccd-72c4-43d2-900e-268ed2d43e81)

Thank you @Frenzie for your help!

**Comment by mergen3107** [comment]
The final version of the file:
```
return function(html)
    html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊')
    html = html:gsub('<k[^>]*>[^<]*%</k>', '')
    html = html:gsub('<c>', '<span>')
    html = html:gsub('</c>', '</span>')
    html = html:gsub('<c c=\"', '<span style=\"color:')
    html = html:gsub('\"color:indigo\"', '\"color:#4B0082\"')
    html = html:gsub('\"color:darkgray\"', '\"color:#A9A9A9\"')
    html = html:gsub('\"color:lightcoral\"', '\"color:#F08080\"')
    html = html:gsub('\"color:lightseagreen\"', '\"color:#20B2AA\"')
    html = html:gsub('\"color:darkgoldenrod\"', '\"color:#B8860B\"')
    html = html:gsub('<rref[^>]*>', '<img src="data/dict/Longman/res/')
    html = html:gsub('.jpg</rref>', '.jpg"/>')
    return html
end
```

**Comment by mergen3107** [comment]
The escape character was not an issue: it is `crash.log` being smart with double-quotes.
I did this suggestion to take in unprocessed .xhtml to produce processes (took me a while to realize what I was doing). And in the processed version it produced correctly:
```
<img src="/mnt/us/koreader/data/dict/Longman/res/gull.jpg">
```

No extra slash in the end needed (with `sametypesequence=h` dictionary).

**Comment by mergen3107** [comment]
Updated the wiki as well.

**Comment by Frenzie** [comment]
> The […] dictionary in question is in html mode.

The version of MuPDF we're using doesn't support HTML, or at least not meaningfully. There must be an exception for elements that are self-closing in HTML, but it's definitely not related to that property. That's just determining whether we render it as plaintext (i.e., ourselves) or whether we pass the contents off to MuPDF.

In any case, that's why I said to test it in MuPDF directly so you know exactly what's going on without complicating matters prematurely.

**Comment by mergen3107** [comment]
I noticed that dictionary doesn't render images anymore.
It shows them as `[image]`.
`crash.log` says:
```
warning: html: cannot load image src='data/dict/Longman/res/gull.jpg'
```

The path is correct.

Does this has something to do with a muPDF update a few months ago?
I don't really know when exactly it started doing this.

I am on `2024.07-241-g85591c75c` now.
@benoit-pierre

**Comment by mergen3107** [comment]
I tried using full path
```
/mnt/us/koreader/data/dict/Longman/res/
```
very short one
```
res/
```
and the current one
```
data/dict/Longman/res/
```
It still doesn't work.

**Comment by mergen3107** [comment]
This is what `crash.log` reports around the context of this image:
```
<blockquote><blockquote><img src=\"data/dict/Longman/res/gull.jpg\"></blockquote></blockquote>
```

Seems fine (extra slashes are again from the logger itself, not the render)

**Comment by Frenzie** [comment]
I can't confirm. Are you sure the image in question actually exists? Just because the HTML thinks it shouldn't doesn't necessarily mean it does.

**Comment by Frenzie** [comment]
Or if it does, that it can be opened.

**Comment by mergen3107** [comment]
Yes, I can even open it

**Comment by Frenzie** [comment]
Apologies, I *can* confirm. The problem is I had tested with PNG. So it's specifically JPEG that's broken.

![Screenshot_20241010_214249](https://github.com/user-attachments/assets/652ecf84-7627-4cde-bff2-bcbb6bbc560f)

**Comment by Frenzie** [comment]
Test case attached.
[bla.zip](https://github.com/user-attachments/files/17333364/bla.zip)

**Comment by Frenzie** [comment]
Well, that's embarrassing. I somehow typod the filename:

```html
    <img src="bla.png">
    jpg
    <img src="blaa.jpg">
```

So we're back to I can't confirm I'm afraid.

**Comment by mergen3107** [comment]
So, I need to open this html in KOReader's muPDF, correct?

**Comment by mergen3107** [comment]
I did this and it shows PNG OK, but after `jpg` it is again `[image]`

**Comment by mergen3107** [comment]
Maybe the relative path changed?

How can I check what path is "now"? Is it `koreader`?

**Comment by Frenzie** [comment]
I don't think the relative path of `data/dict/etc` should change regardless.

Open the terminal emulator and type `pwd`.

**Comment by mergen3107** [comment]
From KOReader's Terminal emulator pluging, pwd is in koreader folder.

**Comment by mergen3107** [comment]
How can I see the output from sdcv after gsub substitutions are done?

**Comment by Frenzie** [comment]
Like I wrote in https://github.com/koreader/koreader/issues/11312#issuecomment-1875867066 you can write out a file(s) along the way. ;-)

**Comment by mergen3107** [comment]
Ah, thanks! I forgot all that. 

So, entry-unprocessed.xhtml is just raw output from sdcv?

**Comment by Frenzie** [comment]
Provided you put it before you apply any transformations :-D

**Comment by mergen3107** [comment]
@Frenzie 
I replaced the `.lua` file with the one you suggested.
It worked OK:
Unprocessed rref part:
```
<rref>gull.jpg</rref>
```

Processed img part:
```
<img src="/mnt/us/koreader/data/dict/Longman/res/gull.jpg">
```
This path is correct!


I tested the same `.lua` file in emulator - same result.

**Comment by mergen3107** [comment]
Closed in favor of the linked ticket.

**Comment by mergen3107** [comment]
Does anyone know if I can center images in dictionary lookup?
I tried these, but it didn't work:
```
img {
    text-align: center !important;
}
```

and 

```
img {
   display: block;
   margin-left: auto;
   margin-right: auto;
   width: 50%;
}
```

**Comment by Frenzie** [comment]
With any particular sample HTML? Note that if you save it as .html and open it with MuPDF (whether the separate program or by the long press action) you can test more quickly.

**Comment by mergen3107** [comment]
I'll try to get raw sdcv output again, thanks :D 
I forgot
