### ISSUE TITLE
ONYX BOOX Palma Viewport

### ISSUE THREAD

**Issue by matt08-prog** [koreader/koreader#11319]
* KOReader version: 2023.10
* Device: ONYX BOOX Palma

#### Issue
The Bezzel at the top of the screen hides the bookmark icon and the Alt Status Bar.

#### Steps to reproduce
Enabling the Alt Status Bar causes it to get cut off on its sides. Without the Alt Status Bar, only the very corner of the bookmark indicator is visible.
This issue can also be seen in a recent [post](https://www.reddit.com/r/koreader/comments/18nkpfw/help_with_onyx_boox_palma/?utm_source=share&utm_medium=web2x&context=3) from the KOReader subreddit.

![image](https://github.com/koreader/koreader/assets/58103083/3680bc96-e33c-461e-be7e-df6b8ffa3198)

The Palma's screen specs are:
Display type (e ink) - HD Carta 1200
Display resolution - 824x1648 (greyscale)
Display size - 6.13'' (15.5702 cm)

**Comment by mergen3107** [comment]
Onyx is getting real mean with these bezels...

Look up here in KOReader issues about how to modify viewport. I think I saw a user-patch once

**Comment by pazos** [comment]
Yup, we expect a rectangle.

We workarounded the main, supported, status bar by using [material design guidelines](https://github.com/koreader/koreader/commit/2f831bebc7707602ec2f523f16d72a273f9ff420).

Not sure if it's possible to do the same on the alt bar. Also not sure we might to encourage to hack on the alt bar :/

Won't fix, patches welcome.

**Comment by mergen3107** [comment]
You can try wm overscan, some discussion here: https://www.mobileread.com/forums/showthread.php?p=4152773&nojs=1

However, this will offset all apps, not only KOReader :D

**Comment by matt08-prog** [comment]
> You can try wm overscan, some discussion here: https://www.mobileread.com/forums/showthread.php?p=4152773&nojs=1
> 
> However, this will offset all apps, not only KOReader :D 

Unfortunately the Palma comes with Android 11 which doesn't allow wm overscan.

**Comment by mergen3107** [comment]
Ah, bummer. 

Then your best bet for now is to:
- set larger margins, both for reflowable documents and muPDFs
- Move to using bottom status bar, ehich you can set higher when needed.

At least for reading books this should be enough. Top status bar is white old and unsupported anyway.

**Comment by mergen3107** [comment]
Also try wm size: https://android.stackexchange.com/questions/230374/decrease-the-screen-size-not-resolution-on-android-11-wm-overscan-is-deprec

**Comment by matt08-prog** [comment]
> Also try wm size: https://android.stackexchange.com/questions/230374/decrease-the-screen-size-not-resolution-on-android-11-wm-overscan-is-deprec

wm size did fix the bezel issue and is what I will be sticking with. Unfortunately, it broke the [input fix for BOOX devices ](https://github.com/koreader/koreader/issues/11082#issuecomment-1878460083) but at least I can see the entire screen now. Thanks!

**Comment by mergen3107** [comment]
You can try adjusing these input values as well :D they just shifted
