### ISSUE TITLE
Does not translate: "From bottom menu u{00b1} / u{22ee} buttons"

### ISSUE THREAD

**Issue by kaznelson** [koreader/koreader#11328]
* KOReader version: koreader-pocketbook-v2023.10-86-gcc52c022d_2024-01-09
* Device: PocketBook Era

https://github.com/koreader/koreader/blob/master/frontend/ui/elements/screen_notification_menu_table.lua#L55
https://hosted.weblate.org/translate/koreader/koreader/en/?checksum=945bcfac02cc3bac

https://github.com/koreader/koreader/blob/master/frontend/ui/elements/screen_notification_menu_table.lua#L56
https://hosted.weblate.org/translate/koreader/koreader/en/?checksum=59090aecd948197b

![Reader_2024-01-10_105112](https://github.com/koreader/koreader/assets/90417439/a226313d-943d-4010-b111-27b123fba6aa)

**Comment by kaznelson** [comment]
Change in **screen_notification_menu_table.lua** and **koreader.po**:
u{00b1} -> ±
u{22ee} -> ⁝
These menu items are translated.

genMenuItem(Notification.SOURCE_BOTTOM_MENU_FINE, _("From bottom menu ± buttons")),
genMenuItem(Notification.SOURCE_BOTTOM_MENU_MORE, _("From bottom menu ⁝ buttons")),

**Comment by poire-z** [comment]
Similar stuff already happened, cf #10845 and link to discussion therein.
