### ISSUE TITLE
Single touch transposed on Kobo Touch B

### ISSUE THREAD

**Issue by BruceDenney** [koreader/koreader#11322]
* KOReader version:  
* 2023.10
* Device:  
* Kobo Touch 905B 

#### Issue
The touch screen is transposed or mixed up or something.
The x and y seem to be mixed up.
It is hard to tell but i think that long pressing may be different to a single click

touching the top left actually touches the top right.
moving down touching on the far left the top mid and top left are touched.
touching a centimetre to the right of the left edge touches a centimetre down from the top.

Hard to explain, here is a video look at the icons at the top turning black https://photos.app.goo.gl/UwAzfzDW3oAkFyBr6

#### Steps to reproduce
Install on a Kobo Touch 905b and try to use!

**Comment by Frenzie** [comment]
Is it still the same on a current nightly? Switch to the development channel under update → settings or download one from http://build.koreader.rocks/download/nightly/

**Comment by NiLuJe** [comment]
You might also want to double-check on a current nickel version, or an older one.

There's an issue about mosidentified Kobo devices in recent nickel versions. No connectivity to cross ref efficiently right now ;).

**Comment by NiLuJe** [comment]
You might also want to double-check on a current nickel version, or an older one.

There's an issue about mosidentified Kobo devices in recent nickel versions. No connectivity to cross ref efficiently right now ;).

EDIT: verbose debug logs would be extremely helpful, too.

**Comment by BruceDenney** [comment]
I have downloaded koreader-kobo-v2023.10-83-gccbfbabb2_2024-01-05, unpacked and copied to my kobo.

There is no change in the behavior

I was launching using KFMon, I have added an extra Nickle Menu shortcut to launch via Nickle Menu

There is no change in the behaviour launching via nicklemenu or kfmon it is the same.

I would love to include verbose debug logs, but I can't find a reference on how to do this

Here is the non verbose crash.log file
[crash.log](https://github.com/koreader/koreader/files/13861784/crash.log)

**Comment by BruceDenney** [comment]
I have had a better play with this now and the long press appears to not be transposed.

I discovered this whilst setting verbose debug

Here is the video of my attempt https://photos.app.goo.gl/T9cUPzJtBJp559em7

the crash.log is bigger now see attached
[crash.log](https://github.com/koreader/koreader/files/13862140/crash.log)

**Comment by NiLuJe** [comment]
It's a nickel issue that misidentifies some device. Apparently still not fixed for the Touch B. There's a dedicated issue with workarounds available, but I don't have the bandwidth (literally ;p) to cross ref right now.

**Comment by BruceDenney** [comment]
I have had a look and can't find it, a pointer in the right direction would be very much apreciated.

Thanks

**Comment by NiLuJe** [comment]
Back in the civilized world, it's #10107 

Supposedly fixed a few Nickel versions ago, but you're the second person with a Touch B where, apparently, not so much ;p.

And, yes, your device exhibits the Touch B quirks, and is mistakenly detected as a C because of the aforementioned Nickel bug.

**Comment by YolloPlays** [comment]
Hi, i had the same error. Fixed it with the bug fix in #10107. I was using KFMon at first. Same bug. Reset the kobo and installed nickelmenu. Same error. Needed the bug fix. 
Log:
[crash.log](https://github.com/koreader/koreader/files/14114951/crash.log)

So its no Koreader bug correct? If so, sorry for my post.

**Comment by NiLuJe** [comment]
Yup, it's a Nickel issue.
