### ISSUE TITLE
RFC: crengine private CSS syntax extension for matching text

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#11323]
I'll be implementing support for [functional pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes) in crengine, at least `:is() :not() :where()`.

(`:is()` has replaced in the specs `:matches()`, so it will allow implementing https://github.com/koreader/crengine/blob/ffc7662f125281397a8c564734918af7cf101f17/cr3gui/data/html5.css#L340-L343 and simplify a few other selectors.)

(I got a book where the normal paragraphs had no `class=`, while various sort of others had a `class=`, and I couldn't get rid of margin-top/bottom set on all P by the publisher, on the normal paragraphs only, without affecting (or needing to redefine) all the others classy P... Having support for `P:not([class]) { margin-top:0 !important }` will be a solution for that case.)

There is a 4th functional pseudo class that is quite different, `:has()`, and that is very powerful and allows stuff that is otherwise impossible with CSS: styling an upper node depending on the lower nodes it may have or not have.
It would be quite expensive when doing its checks. It has been implemented only recently by web browsers, for reference the issues they discussed their implemention:
https://bugzilla.mozilla.org/show_bug.cgi?id=418039
https://bugs.chromium.org/p/chromium/issues/detail?id=669058
I'm sure there's been situations in the past when I would have like to have that - but I can't remember :/ a single case to think if it would be really worth spending time on it.
So, I won't implement it, for now.

But thinking about that, I remembered there is another more common case that I would like to have a solution for: **styling a node depending on its text content**.
There is no existing CSS syntax that allows for that, so I thought we could add a similar functional pseudo classe: `:hastext()` or `:text()`, so I could use `:text("^Chapter")` to match a node whose text content starts with "Chapter".
It would be a bit tedious to define/document what's allowed in the content: plain strings with some kind of flags somewhere to indicate where to match and if it's case insensitive (or different pseudoclass names, `:itext()`, `:matchatstart()`), or if it could be a regexp (which means some quite harder parsing, and using [srell](https://www.akenotsuki.com/misc/srell/en/) that @zwim has already added to crengine, but it's limited in what it can catch - ie. you can't match all punctuations or letters, just ascii stuff - and if we enable Unicode support, the syntax to match punctuations would be hideous... and well, it's regexp, so non-power-user-unfriendly.)

Then, light bulb moment: CSS has already some syntax to do that kind of matching, on strings, but on attribute values only, with [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors).
```c
        case set:           // E[foo]
        case eq:            // E[foo="value"]
        case eq_i:          // E[foo="value" i]
        case has:           // E[foo~="value"]     // see below
        case has_i:         // E[foo~="value" i]   // see below
        case starts_word:   // E[foo|="value"]     // see below
        case starts_word_i: // E[foo|="value" i]   // see below
        case starts:        // E[foo^="value"]
        case starts_i:      // E[foo^="value" i]
        case ends:          // E[foo$="value"]
        case ends_i:        // E[foo$="value" i]
        case contains:      // E[foo*="value"]
        case contains_i:    // E[foo*="value" i]
```

If we allow us to introduce some kind of special character to use in place of the attribute name (`foo` above), so it means that it's not an attribute, but the node full inner text that we want to be checked against, we could have a handy solution for many cases !
The good thing is that the syntax (`^=`, ` i`) ...is already documented, quite simple and obvious, and may be known to some, and it could be intuitively guessed that `~=` and `|=`, which expects a space at boundaries with attribute values, would expect any space or punctuation char at boundaries with text.

So, I'm asking for permission :) and for ideas about that special char (which should be ASCII, and not conflict with real attribute names), and if you think this is a bad idea and may cause issues I have not thought about.

I implemented some of them, using `_` as this special char, and with such an unstyled and not-fun to read book with no ToC:
![image](https://github.com/koreader/koreader/assets/24273478/6e1c7dbf-def7-4f73-b064-ebc1760d3f94)

![image](https://github.com/koreader/koreader/assets/24273478/ac5660a4-f49f-4b62-803d-3a5e4315c1fd)

by making such a style tweak:
```css
p[_^=ACTE] { font-weight: bold; font-size: 1.5em;-cr-hint: toc-level1;}
p[_^=scène i] { font-weight: bold; font-size: 1.2em; margin-top: 1em; -cr-hint: toc-level2;}
p[_^=Antoine i] { color:blue; padding-right: 1em; }
p[_^=MONIQUE] { color:red; padding-left: 1em; }
p[_^=MONIQUE]::before { content:"\26D4"; }
p[_^=MONIQUE][_~=Jeanne i] { background-color:yellow; }
p[_*="Jeanne." i] { color:green; }
```
one could get himself something like that, and a auto-generated Alternative ToC:
![image](https://github.com/koreader/koreader/assets/24273478/1b455151-c3ce-46a5-97e7-f42636b4d505)

So, no regex support, no way to match all paragpraphs starting with a number with `^[\d]+` (but we could may be later use the not really interesting `|=` to accept some regexp bits).

These checks could also be a bit slow, and the presence of a single one will require a re-rendering on the first book opening (because the inner text is not parsed yet when we build the DOM), but it's good to have that solution in spite of that.

I don't think this could conflict with publisher styles, but if really required, I could limit this support to the user-agent stylesheet (epub.css, html5.css) + style tweaks, and disable it on publisher stylesheets.

I used `_` as this special char - because it's already supported in what is allowed in attribute names, so no special hack needed. `p[@^="Chapter"]` would jump more obviously (even if `@` doesn't really evoke "text") than our discreet `_`, it would need some special parsing to accept it, and may be it could be mistaken with @-rules or considered invalid by foreign CSS editors... so dunno if there's anything better than `_`.

**Comment by Frenzie** [comment]
> I'll be implementing support for [functional pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes#functional_pseudo-classes) in crengine, at least `:is() :not() :where()`.

Just a minor warning, the specificity rules might require an annoyingly large amount of attention. It is nice to write `:where()` though. :-)

> I'm sure there's been situations in the past when I would have like to have that - but I can't remember :/ a single case to think if it would be really worth spending time on it.

Many things where you'd add a special `class="something-container"` could potentially be replaced by :has(), though indeed for performance reasons I wonder if that's a good idea regardless.

You could also have something like:

```css
h1:has(+h2) {margin-bottom: .5rem}
```

Traditionally you'd either have to do `h1+h2{margin-top: -1rem}` or add a class to `<h1 class="mb-1">` neither of which quite match how you'd intuitively want that to be solved.

> But thinking about that, I remembered there is another more common case that I would like to have a solution for: **styling a node depending on its text content**.

I'm not quite sure how useful that is unless you have only an ereader for many days, in which case you could do some quick hacks locally. :-) But as soon as you're on a PC or laptop to easily write a stylesheet you can just about as quickly perform a global search & replace on the actual EPUB.

**Comment by Frenzie** [comment]
Anyway, Prince thinks it's a good idea too, so you're in good company.
https://www.princexml.com/doc/css-selectors/
```
The Contains Pseudo-class
--
E:contains(foo) | The contains pseudo-class represents an element E containing the text foo.
```

**Comment by poire-z** [comment]
> I'm not quite sure how useful that is unless you have only an ereader for many days, in which case you could do some quick hacks locally. :-) But as soon as you're on a PC or laptop to easily write a stylesheet you can just about as quickly perform a global search & replace on the actual EPUB.

PCs are not for that - PCs are for hacking KOReader and crengine, so one doesn't need a PC to tweak his books' looks :)

> E:contains(foo) | The contains pseudo-class represents an element E containing the text foo.

(I've read about it in the mozilla issue, it had `:has()` or an equivalent before all the major browsers.)
But I think it's more limited (matching a single plain string anywhere) than what I'd like us to have :)

**Comment by Frenzie** [comment]
> (I've read about it in the mozilla issue, it had `:has()` or an equivalent before all the major browsers.)

Hm, I don't think so? Prince is pretty unique there. It does mention that Prince already implemented `:has()` but that's all just normal selectors.

> But I think it's more limited (matching a single plain string anywhere) than what I'd like us to have :)

Just because it is in Prince doesn't mean the concept is. ^_^

The main reason I bring it up is because I think for example a `:-cr-contains(needle, options)` (or even simply as `:contains(foo|="value" i)`) is a bit cleaner than the `_` solution, which strikes me as more likely to hit the CSS standard doing something else. I'm not advocating for it per se but I still think it's an option that needs to be mentioned.

It also gives me some flashbacks to this. :-)
```css
color: red;   /* all browsers */
*color: blue;   /* IE7 and below */
_color: green;   /* IE6 and below */
```

**Comment by poire-z** [comment]
Went with my proposal in https://github.com/koreader/crengine/pull/552, because this syntax is easier to parse in crengine without needing much kludge (the other syntax proposals would need some duplicated parsing code, not worth for something that private), and easier to write for users.
I limited its support to the useragent+styletweaks stylesheet, so no risk of doing anything if met in book stylesheets.
