### ISSUE TITLE
FR: Donate a Pocketbook Device

### ISSUE THREAD

**Issue by peterrus** [koreader/koreader#11338]
Hi! KOReader on Pocketbook devices is definitely usable. Have been using it as a daily driver for about two years now (HD3 Touch and Era). There are however still some quirks here and there, and I have the feeling that donating a Pocketbook to one of the maintainers might help resolve these quirks.

Some things we have to find out:

1. Is there currently a core maintainer that would be interested in receiving such a device and can say with a high degree of certainty that they will test against the Pocketbook device.
2. Would it be a problem if that device is second hand? I can imagine some people not feeling comfortable with receiving an unsealed device from a stranger on the internet.
3. If there are other people that want to contribute financially (or even better, have a fairly recent device they want to donate) I'd be willing to pool a few payments through Paypal or SEPA and then ship a new or second hand device (depending on how much money will be available). If there is not a lot of interest from other donators but there is a core maintainer that is interested then I might just try to find and buy a second hand device from my own funds and ship it.

Wondering what your thoughts are!

**Comment by pazos** [comment]
@cellaris donated me a HD3 long time ago.

I received it just on time to review @ezdiy set of patches, which fixed most of the bugs the PB had back then. On top of that I added support for warmth.

It is on a shelve for more than two years now, so if somebody wants it I have no problems sending it to somebody else.

For me, personally, doesn't worth my time. A device doesn't buy motivation. 
AFAIK nobody here has the motivation to work on devices or features they don't use.

> There are however still some quirks here and there

AFAICT there're two main issues: WiFi is broken (so everything network related might fail) and the cpu sleeps after a couple of seconds (so longer timers are broken).

The first issue requires a motivated user with one of the devices/fw versions that are affected.
The second issue can be workarounded  and what is lacking is documentation.

**Comment by NiLuJe** [comment]
Same, already stretched way too thin, and I have no particular love for the platform that would help motivate me ;).

**Comment by Frenzie** [comment]
Indeed, I'm not opposed to receiving a no longer wanted device but I can't promise to do much of anything with it.

**Comment by peterrus** [comment]
Alright! Thanks for your replies. In regards to @pazos's reply: Makes a lot of sense and I would probably have said the same if I was in your situation.

and Re: the state of KOReader on the Pocketbook platform: It is definitely usable. Only issues I have encountered on the 'new' Era is:

- A desync between what KOReader thinks is the state of the Wifi connection and what the actual state is (Also happened on my previous Touch HD3)
- An occasional crash when swiping with two fingers (not entirely sure if that really is the trigger)

But besides that everything seems to working like a charm (at least the stuff I use) so I want to thank you all for your work!

I might try to pick up some contributing if there is an issue that really irks me, but nothing so far, and like all of you I too am stretched too thin most of the time ;) My intention with this issue first and foremost was to check if there was dire need for a device.

**Comment by peterrus** [comment]
I was wondering @Frenzie @pazos and @NiLuJe, assuming you are all using Kobo devices: What makes Kobo interesting to you (in the context of KOReader development)? Just the fact that you happened to buy a Kobo device one day and now just stick to it because you have experience with that specific platform and it's quirks? Or is Kobo somehow more friendly to third party devs?

And do you have any thoughts about the future of KOReader on the Pocketbook platform? Would it be significantly harder to maintain because Pocketbook devs are consistently screwing things up?

Feel free to leave some random musings. I am just trying to decide whether or not I am better of switching to Kobo (Even though I am not a big fan of their mandatory account policy, yes it's bypassable) or maybe invest some time in getting acquainted with KOReader development on the Pocketbook platform.

**Comment by NiLuJe** [comment]
> Or is Kobo somehow more friendly to third party devs?

This.

We're always root, the update process is dumb as rocks and comletely unsigned (it's just a tarball unpacked during boot), the init system is extremely simple, and the stock system is fairly monolithic.
The only downside is the age of the software stack, but that's true of pretty much everything besides rM.

**Comment by NiLuJe** [comment]
> (Even though I am not a big fan of their mandatory account policy, yes it's bypassable)

It's been *trivially* bypassable for a good while now, as Nickel implements a "sideload only" mode as a hidden setting.

**Comment by pazos** [comment]
> assuming you are all using Kobo devices

My main device is a Bq Cervantes 4. It is like a Kobo Clara 1st gen with much faster storage and not so advanced screen refreshes. 

> What makes Kobo interesting

You can interface with kernel APIs, no undocumented mess on top of it.
You run as root, so unsafe but powerful :)

> in the context of KOReader development

Hopefully most people can play, tweak and develop ignoring how the `Device` HAL works.
Of course, having partially non-working `Device` HALs on some platforms acts as a claim for new contributors for the `Device` itself :)

> And do you have any thoughts about the future of KOReader on the Pocketbook platform? 

The wifi thing ought to be fixable. Same for your issue with particular input events.

The main problem of KO on some platforms is that we act as a regular app and we don't "own" the system. So we need to deal with stuff that's mostly undocumented and mostly probably broken for particular device + fw combos :/

Also, pocketbook refresh is slow, much slower than kobos.

**Comment by peterrus** [comment]
Again: Thanks for sharing your views on things! This motivated me to actually borrow a Kobo Libra 2 to experience things for myself and I am going to sum up some of my findings for future readers that might have the same questions as I had and sum up some statements to check if I've understood them correctly. There will be some of my personal opinions mixed. Warning, long post, and probably the last one because I am going quite off topic. Please understand that I am just trying to sum up some of my findings and by no means want to discredit all the hard work being put into the project.

> Also, pocketbook refresh is slow, much slower than kobos.

When comparing the Libra 2 to the Era I found no difference, they are both using the same carta screen. But your statement probably holds true for older devices.

> They're also not completely terrible at actually shipping the GPL sources

Yeah I tried finding sources for Pocketbook, but no luck. Maybe because they didn't modify anything? (I find that hard to believe).

> There's no middleware "required" to interact with the hardware
> The HAL

I suppose this is also refered to as the 'SDK' by Pocketbook itself? While I do believe a proper abstraction is a lot wiser in most cases than accommodating for every specific device in the KOReader codebase I can understand this currently isn't feasible because the SDK is not properly documented according to your experiences. And since KOReader will run on many different manufacturers devices there will never be just one SDK/HAL that we can write against.

This brings me to a noticeable difference between Pocketbook and Kobo devices: It seems KOReader on the Kobo completely 'takes over' the entire UI (and kicks out Nickel?). Going back to Nickel to change some device settings requires me to exit KOReader and wait until Nickel is started again (which takes at least 5 seconds for me). This did suprise me because on Pocketbook I can just press the home button once to instantly go back to Pocketbooks home screen or long press it to switch to other apps or kill them. So Pocketbook seems to have better multitasking capabilities.

And because we are not talking to a HAL KOReader seems to have no idea what the state of the frontlight was in Nickel. So when I turn it off in Nickel it might still turn on once I start KOReader.

Another example of this is pluging the reader into another device as USB mass storage. On Pocketbook a native dialog gets overlain on top of KOReader asking you if you want to charge the device or mount the device. On Kobo this all seems to be handled by KOReader.

Furthermore I am a bit wary of the Kobo device as Rakuten has more incentives to push ads for books on you and I noticed a `.kobo/Kobo/Analytics.conf` file containing a unique tracking ID and a queue of events describing probably some of my behaviour that were to be sent to Google Analytics once I connected to Wifi. I nulled the ID and removed the queued events from that file just to be sure. I don't seem to have the option to disable tracking in any privacy related settings menu's but maybe nothing will actually be sent because I am in sideload mode. I have no idea. There is no indication as far as I know that Pocketbook engages in such activities.

And finally: No audiobook functionality except the rudimentary 'hidden mp3 player' or Kobo's DRM'ed distributions (out of the question). And the beta web browser feels (understandably) a lot more rudimentary than Pocketbook's

If you just want a device to run KOReader perfectly (and rely on the earlier mentioned features that are currently broken on Pocketbook) and nothing else it seems the Kobo devices are the better choice because of wider support from the devs (and thus less bugs).

**Comment by NiLuJe** [comment]
> And because we are not talking to a HAL KOReader seems to have no idea what the state of the frontlight was in Nickel. So when I turn it off in Nickel it might still turn on once I start KOReader.

Unless you borked the defaults, that isn't true: we resync the frontlight state with Nickel on startup.

**Comment by peterrus** [comment]
You are absolutely correct and I can not reproduce this so I stand corrected!

**Comment by pkb** [comment]
>  There is no indication as far as I know that Pocketbook engages in such activities.

Pocketbook sends usage statistics by default but there is the option to disable it in privacy settings.

**Comment by Biep** [comment]
> > And because we are not talking to a HAL KOReader seems to have no idea what the state of the frontlight was in Nickel. So when I turn it off in Nickel it might still turn on once I start KOReader.
> 
> Unless you borked the defaults, that isn't true: we resync the frontlight state with Nickel on startup (and vice-versa on exit).

I have this same issue with my Kobo Aura One.  Never bothered to report it, but the bug is there.  (I **think** sometimes WiFi status gets mixed up too when switching between Nickel and KOReader.)

**Comment by Biep** [comment]
Maybe it has been repaired since - I can't remember whether it has happened recently.

**Comment by NiLuJe** [comment]
The Aura One is a special snowflake as far as its frontlight setup is concerned, so there's a fairly high probability something was broken there at one point.

It's irrelevant to the discussion, though, as it's a special snowflake, and no other devices was implemented that way ever again.

**Comment by Biep** [comment]
All right, I see.  Well, mine is melting down anyway..

**Comment by Biep** [comment]
I got my PocketBook Era.  Looking for the KOReader PocketBook package [here](https://github.com/koreader/koreader/releases?q=PocketBook&expanded=true) in vain.  Should I look somewhere else, or use a generic package?
I am following [these instructions](https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices).

**Comment by poire-z** [comment]
![image](https://github.com/koreader/koreader/assets/24273478/8a7eb418-d94e-4a32-88e5-9bbe59bfff26) => ![image](https://github.com/koreader/koreader/assets/24273478/da7122cf-2817-4c16-ab99-48d560abb837)

**Comment by Biep** [comment]
Yes, sorry.  I **had** expanded the view, but for some reason had been blind to the *pocketbook* package.  Thanks!
