### ISSUE TITLE
Crash when deleting last and only book from history when trying to sleep/power off/reboot

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#11336]
* KOReader version: 2024.01 (firmware 4.37.21586)
* Device: Kobo Libra 2

Libra 2 crashes (Sage doesn´t) when (trying to) Sleep/Power off/Reboot the device.

[crash.log](https://github.com/koreader/koreader/files/13916632/crash.log)

**Comment by Frenzie** [comment]
Not for me, but might have a slightly older firmware version? I'll check at home tonight.

**Comment by gerhaher** [comment]
>  but might have a slightly older firmware version?

No, I updated to latest firmware (4.38.21908). No change to the better.

**Comment by Frenzie** [comment]
Sorry, I typed that on my phone and somehow an "I" fell off. But looking at the release dates in all likelihood I have 4.38.21908 as well since that seems to be from September 2023.

**Comment by NiLuJe** [comment]
@gerhaher: I assume you don't have anything recorded as your "last opened document"?

**Comment by gerhaher** [comment]
No.

**Comment by NiLuJe** [comment]
> @gerhaher: I assume you don't have anything recorded as your "last opened document"?

Or perhaps you're using the weird "use a specific documlent cober" feature?

(In any case: what's your *exact* screensaver setup. Or, better yet, just attach your `settings.reader.lua`).

**Comment by gerhaher** [comment]
[settings.reader.zip](https://github.com/koreader/koreader/files/13920910/settings.reader.zip)

**Comment by NiLuJe** [comment]
Not having a `lastfile` recorded is super-weird. Did you actually manually clear your history or something?

(Does something like that sound plausible, @hius07 ?).

**Comment by gerhaher** [comment]
> Did you actually manually clear your history or something?

I have recently deleted my whole library. That's all.

**Comment by gerhaher** [comment]
By the way v2023.10 works for me. And 2023.10-54 doesn't

**Comment by gerhaher** [comment]
OK, so I opened a book and there is no crash. Resetting the same book, and the crash is back.

**Comment by NiLuJe** [comment]
Papered over it in #11341, waiting for @hius07 to confirm whether the fact that this should accept a `nil` or not was a conscious change or a regression on the DocSettings front ;).

**Comment by hius07** [comment]
> Resetting the same book

What does it mean?

**Comment by gerhaher** [comment]
Reset

**Comment by hius07** [comment]
> Reset. I reset the book I had opened.

Got it, thanks.
