### ISSUE TITLE
FR: Czech keyboard layout?

### ISSUE THREAD

**Issue by sdasda7777** [koreader/koreader#11339]
I think it would be nice to have Czech keyboard layout available. I would be willing to look into it myself as I assume it would be just a few simple files.

However, I am confused about the choices made when creating the Slovak keyboard. It is not, in fact, a standard Slovak keyboard one would expect when selecting a "Slovak" keyboard. I would go as far as to say I struggle to find anything different about it when compared to other keyboards, aside from Y and Z being swapped. The actual Slovak layout (and the Czech layout as well, which is why I mention it) has regional special characters in the top row, to make it simple to write them, because they are used much more than the numbers. If that be the mandate for all layouts, then I don't see a point in having a Czech layout at all, because there would be nothing different about it compared to the Slovak layout. Could you clarify on this?

**Comment by pazos** [comment]
keyboard layouts are user contributions.

For instance, the slovak layout was requested in https://github.com/koreader/koreader/issues/9440 and contributed (by the same user) in https://github.com/koreader/koreader/pull/9656, so you'll need to ask its creator about the choices made.

> as I assume it would be just a few simple files.

It really depends on the script, the layout differences between a regular latin script layout (like english or spanish) and your desired one and the level of composition required to generate glyphs from the input method.

Assuming there's no composition and you just display as many elements as required to input all the glyphs used by your language it should be easy, yes.

About the 1/1 ratio between glyphs and "input elements". Most of the languages require a few extra bits and there's no space to fit them, so a long-press popup is displayed on top of each key to let you input "near" glyphs.

**Comment by Frenzie** [comment]
Layouts are what someone contributed. Those can be very elaborate (look at some of the Asian keyboards) or just the "English" keyboard with a number of keys adjusted, which is typically the way to go for a QWERTY/AZERTY/QWERTZ variation.

You'd have to ask @sonix-github if there was any specific rationale. I see that many of the popups/swipes are customized. Given your description my guess would be the author felt that swiping left/right on a key (for example) was more convenient than having to press another key first. That's also the design principle behind our French keyboard for example, or perhaps rather it's already built into the English keyboard. A traditional physical keyboard needs such separate keys for diacritics. There was some discussion here: <https://github.com/koreader/koreader/issues/9440#issuecomment-1221529883>.

**Comment by sdasda7777** [comment]
So there should be no issue having special characters instead of the number row? I don't particularly care about the Slovak keyboard as I am not and I will not be using it, but it is odd to be sure, so I wanted to check. I can see that there are images in that issue where the diacritics are above the numbers, but that is not what I see on my reader, on my reader it really differs from the English keyboard in the Y and Z.

**Comment by Frenzie** [comment]
> So there should be no issue having special characters instead of the number row?

That depends on the special characters in question. It's possible that you'd have to write some glue code akin to the Japanese/Korean keyboards for example, or it might just work. But no problem from some kind of design perspective if that's what you mean. Technically speaking I'd prefer authors to follow the example of the French keyboard if reasonably possible, but if it's not it's not.

> on my reader it really differs from the English keyboard in the Y and Z.

Like I said, the difference is in the swipes/popups. See http://koreader.rocks/user_guide/#keyboard

**Comment by sonix-github** [comment]
> So there should be no issue having special characters instead of the number row? I don't particularly care about the Slovak keyboard as I am not and I will not be actively using it, but it is odd to be sure, so I wanted to check. I can see that there are images in that issue where the diacritics are above the numbers, but that is not what I see on my reader, on my reader it really differs from the English keyboard in the Y and Z.

You are right @sdasda7777 There is some issue with Slovak keyboard layout. It should be like on my last screens I have attached in #9440 There should be also diacritics on first row. It seems that I probably messed it up by uploading from git desktop. I am going to fix it.

**Comment by sonix-github** [comment]
I have fixed it and made new pull request https://github.com/koreader/koreader/pull/11343#issue-2079342397
Also I have tested it on emulator and on my pocketbook device.

![SK_standard](https://github.com/koreader/koreader/assets/29783895/abb62ee8-5702-4eb5-beaf-005e7b0d7ab2)
![SK_standard_shift](https://github.com/koreader/koreader/assets/29783895/166d0a2f-26a4-465c-8e4c-dd0c356eb379)
