### ISSUE TITLE
FR: [Support for DictTango, a new Android dictionary app work with mdict format]

### ISSUE THREAD

**Issue by offlineface** [koreader/koreader#11340]
**As a simple user, I use koreader and external dict app both for better experience, then I find dictTango, a new modern, multifunctional, and beautiful dictionary app which is unsupported in koreader yet.**

https://play.google.com/store/apps/details?id=cn.jimex.dict&hl=en

I tried some research and found this[https://github.com/koreader/koreader/pull/5108](https://github.com/koreader/koreader/pull/5108), which may be a good way to solve. Unfortunately I can't code, so I expect other advanced users or developers to help me.
> how to add support for new dictionary apps ?

> find a target dict app (already installed, configured and ready to work)
> find its package name (using an app like "Package Names Viewer")
> try generic actions in this order: picker-share -> picker-send -> picker-text.
> hopefully the application is available as an option to open the query.
> try again removing the "picker-", It should open your dictionary without questions.

**Additional context**
![image](https://github.com/koreader/koreader/assets/67045102/126146b6-938c-4e5a-9043-c9249ab4d457)
Given the description, I also fully recommend this new dictionary app for everybody to try.

**Comment by poire-z** [comment]
You can add support for any dict app yourself on your own Android, see https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-dictionary-list

(Not using Android and not having much thought about android dict apps, this app has `1K+ downloads` only, so intersection with the KOReader android users base may come up with only one user present in both sets: _you_ :))

**Comment by offlineface** [comment]
> You can add support for any dict app yourself on your own Android, see https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-dictionary-list
> 
> 
> 
> (Not using Android and not having much thought about android dict apps, this app has `1K+ downloads` only, so intersection with the KOReader android users base may come up with only one user present in both sets: _you_ :))

I see.
After checked the page you provided, I created such a file /koreader/dictionaries.lua

```

-- thirdparty app support
local external = require("device/thirdparty"):new{
    dicts = {
        { "Aard2", "Aard2", false, "itkach.aard2", "aard2" },
        { "Alpus", "Alpus", false, "com.ngcomputing.fora.android", "search" },
        { "ColorDict", "ColorDict", false, "com.socialnmobile.colordict", "send" },
        { "Eudic", "Eudic", false, "com.eusoft.eudic", "send" },
        { "EudicPlay", "Eudic (Google Play)", false, "com.qianyan.eudic", "send" },
        { "Fora", "Fora Dict", false, "com.ngc.fora", "search" },
        { "ForaPro", "Fora Dict Pro", false, "com.ngc.fora.android", "search" },
        { "GoldenFree", "GoldenDict Free", false, "mobi.goldendict.android.free", "send" },
        { "GoldenPro", "GoldenDict Pro", false, "mobi.goldendict.android", "send" },
        { "Kiwix", "Kiwix", false, "org.kiwix.kiwixmobile", "text" },
        { "LookUp", "Look Up", false, "gaurav.lookup", "send" },
        { "LookUpPro", "Look Up Pro", false, "gaurav.lookuppro", "send" },
        { "Mdict", "Mdict", false, "cn.mdict", "send" },
        { "QuickDic", "QuickDic", false, "de.reimardoeffinger.quickdic", "quickdic" },
        { "dictTango", "dictTango", false "cn.jimex.dict", "send"},
    },
    check = function(self, app)
        return android.isPackageEnabled(app)
    end,
}
```

as you can see, I put dictTango at the end of the list.

However it didn't work.

I want to know what's wrong and how to solve it.

**Comment by offlineface** [comment]
there isn't any change in external dictionaries options.

![image](https://github.com/koreader/koreader/assets/67045102/a263c8da-fb36-4450-82a2-d9e86de9ae41)

**Comment by Frenzie** [comment]
It should simply read:

```lua
return
{
    { "dictTango", "dictTango", false "cn.jimex.dict", "send"},
}
```

It's possible that `send` isn't the right intent, but it's worth a try.

**Comment by offlineface** [comment]
> It should simply read:
> 
> 
> 
> ```lua
> 
> return {
> 
>     { "dictTango", "dictTango", false, "cn.jimex.dict", "send"},
> 
> }
> 
> ```
> 
> 
> 
> It's possible that `send` isn't the right intent, but it's worth a try.

You are right! It really works well! Thanks for your help! Thanks to community!
