### ISSUE TITLE
User defined rota isn't restored at launch

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#11345]
* KOReader version: 2024.1
* Device: android (all of them)

#### Issue

Keep rotation across views no longer restores user defined rotation at launch.

#### Steps to reproduce

1. Enable settings->screen->rotation->keep rotation across views
2. Select any of the non 0º rotation options.
3. Exit KO
4. Start the app

Expected result: rota in step 2 is restored (it is what happens on 2023.10 - ovis)
Result: back to 0º rotation.

I don't know if this affect non-android devices. I keep my cervantes on a very old version on purpose :)

**Comment by Frenzie** [comment]
I thought that was a Libra 2 issue I still wanted to investigate sometime. I didn't realize it was generic. Unless that's something else.

**Comment by pazos** [comment]
Nope, my bad.

It seems something related to a particular device. Just tested on my tablet and there both versions work fine.

**Comment by pazos** [comment]
It looks that I have a nice phone to play with, because there rota isn't restored, which it also happen on some legacy devices, like in https://github.com/koreader/koreader/issues/10849#issuecomment-1889825422

**Comment by Frenzie** [comment]
And I don't see it on the Libra 2 anymore either, which would suggest it was either fixed in the last 2-3 weeks or it's something that only crops up after doing something else (like an OTA-update → restart automatically or switching between documents)

**Comment by NiLuJe** [comment]
FWIW, I don't recall anything having changed on that front recently, except on the very few Kindle devices with gyro since #11277 ;).

It's not something I test regularly (read: ever), though ;).

**Comment by NiLuJe** [comment]
Screensaver can enforce a specific rotation while it's up, regardless of the rotation lock, but I don't see how you could do something funky before it restores it when it gets closed ;).

**Comment by hugleo** [comment]
Seems like the same for my device android 13.

Is 0° by default:

![photo_2024-01-12_20-42-00](https://github.com/koreader/koreader/assets/4573505/1cbdb199-f794-4757-b6c1-20301121770b)

Changed to 90° and the screen is rotated:

![photo_2024-01-12_20-41-50](https://github.com/koreader/koreader/assets/4573505/36abb48d-a921-4c52-bd9f-8830b6e49ab4)

Quit koreader and the rotation is back to 0° again, including the menu option:

![photo_2024-01-12_20-41-54](https://github.com/koreader/koreader/assets/4573505/0f93a81e-a44a-4e87-8718-1efeb86efab0)

I didn't debug yet but maybe the rotation option is not being saved or being read correctly from the config file.

**Comment by NiLuJe** [comment]
It's saved on `Device:exit` (and restored on `Device:init`), soooo, possibly Android lifecycle issues or something?

**Comment by NiLuJe** [comment]
Oh, no, it's much simpler: Android.exit doesn't callGgeneric.exit(self) ;p.

**Comment by pazos** [comment]
> Oh, no, it's much simpler: Android.exit is failing to call Generic.exit(self) ;p.

So it works on my tablet now just because it worked before and it is saved as default?, lol

**Comment by NiLuJe** [comment]
> > Oh, no, it's much simpler: Android.exit is failing to call Generic.exit(self) ;p.
> 
> So it works on my tablet now just because it worked before and it is saved as default?, lol

Yeah, you probably have an "old" `closed_rotation_mode` key in your settings.

Quick question while I've got you: this should be done *before* `android.lib.ANativeActivity_finish(android.app.activity)`, right?

**Comment by pazos** [comment]
Quick question while I've got you: this should be done before android.lib.ANativeActivity_finish(android.app.activity), right?

Yup, I think it makes sense to put it even before the log statement. But that's up to you ;)

**Comment by NiLuJe** [comment]
Cool, done ;).

**Comment by NiLuJe** [comment]
Fun fact: it probably also fixes the various "my settings are never saved" issues, because 21de1a832e5fc5c600aae1b98f6447db3c94dd3b ;p

**Comment by NiLuJe** [comment]
And, yeah, it used to run in `reader.lua` prior to `Device:exit` before 71378b0b503061557408afbafa871f60b5dbced1

**Comment by pazos** [comment]
wow

so no settings saved since v2023.08?

I didn't notice :smile:

**Comment by mergen3107** [comment]
> so no settings saved since v2023.08?

Thank can't be true :D ay least most of yhd settings were saving OK on my old Kon-Tiki 2 (otherwise I'd have created a ticket here long time ago, you know me xD)
