### ISSUE TITLE
[BUG] On screen keyboard and "Add Note" popup close repeatedly while typing a note, and nothing gets saved.

### ISSUE THREAD

**Issue by litetaker** [koreader/koreader#11357]
* KOReader version: v2024.01
* Device: Kobo_goldfinch (Kobo Clara 2E)

#### Issue

When I am typing a note using the on-screen keyboard, after selecting some text, at some random point the keyboard just automatically closes, along with the Add Note popup and nothing gets saved. There is no highlight, nor is there any note. It is as if I clicked on the "Cancel" button to dismiss everything, but this happens on its own while typing. It is 100% reproducible, making adding notes extremely unreliable. Additionally, the page also turns (probably because I am still in the typing motion, and once the keyboard gets dismissed when my finger taps the screen thinking I am entering some text, it actually activates the page turn tap gesture). 

This may happen more consistently if you type faster.

#### Steps to reproduce

1.  Highlight some text, so that the popup shows up asking you what to do.
2. Select, "Add note"
3. Enter some text at a somewhat fast typing speed.
4. After a random amount of time (usually after typing a few words worth of text) the keyboard and the add note popup close. 
5. Nothing is saved.

#### Video demonstration of bug
https://www.youtube.com/shorts/XvIxPBPviNw

##### `crash.log` file: [crash.zip](https://github.com/koreader/koreader/files/13933312/crash.zip)
Note: The attached `crash.log` file has some initial portion that did not have debug (and verbose debug) logging enabled. Then, I enabled it and reproduced the issue again several times (5-6 times) to capture any relevant logs.

**Comment by NiLuJe** [comment]
I'll need to look at the logs in more details tomorrow (as well as try to replicate), but it *looks* like the panel is spazzing out, and spitting out an input frame with inaccurate coordinates that happens to fall *outside* of the VirtualKeyboard area, which triggers the hide.

(Not quite sure why that would kill the popup, though).

I have noticed that the panel on the Claar 2E was less than great, and we have seen wonky behavior from some panels where multiple contacts (or long swipes) are involved, where they'll sometimes spit out completely bogus data.

**Comment by NiLuJe** [comment]
Eh, nah, got confused by the native panel orientation ;o).

I can definitely repro (on the same device, but that might be a red herring).

And you lose the popup because it becomes much easier to tap outside of it once the VK is gone ;p.

**Comment by NiLuJe** [comment]
Oh, it's sneakier than that.

It's when you tap on a key's *border* that it falls through ;p.

**Comment by poire-z** [comment]
> so, if you hit that 4px border, it falls through

Shouldn't it somehow better _not_ fall through and _not_ be ignored (ignoring is what your patch does I think) ? As it means some of your taps on keys will have no effect, so you'll miss some letters.
Shouldn't each key touch area extend to include the border, so there's no hole ? (dunno if that's easy or possible, just asking :))

**Comment by Frenzie** [comment]
I agree that having the border as part of the touch area seems more intuitive, if reasonably possible.

**Comment by NiLuJe** [comment]
The big question is how you handle overlaps, because contiguous keys share one or more borders ;).

**Comment by poire-z** [comment]
Looks like VirtualKey has a bordersize field, but it must stay 0 (if we make it 2px, we would get:
![image](https://github.com/koreader/koreader/assets/24273478/24e6e4ef-90b1-4b40-80aa-1d127134d266)
)
The "border" we see is actually a full gray background over all the keyboard area, + some padding.small between frameless keys...
So, hard to "fix" this without rethinking the whole virtualkeyboard and risk breaking things or look...
(Even if you disable key borders, this just change the full background to white, so the untouchzone'd padding is still there.)

**Comment by Frenzie** [comment]
By border I meant the black. If that's already included you can ignore my earlier comment completely.

**Comment by poire-z** [comment]
There is no such black (it's there when i hack `bordersize = 0` to `= 2` as I did for the screenshot).

But even if we don't change the layout, and keep the padding, we could extend the VirtualKey touch zone to be wider on each size by `math.ceil(key_padding / 2)`, the possible overlap would be taken care of by the touch zones stack ?

**Comment by NiLuJe** [comment]
Yeah, that seems to work, that just leaves the actual borders at the edge of the keyboard unhandled ;).

**Comment by Frenzie** [comment]
> There is no such black (it's there when i hack `bordersize = 0` to `= 2` as I did for the screenshot).

That comes to the same thing. That's not a border but space in between. I was only referring to the concept of a border. :-)

**Comment by litetaker** [comment]
That was a really quick investigation and fix @NiLuJe! Thank you 🙂 

I am glad this issue is now fixed, and with that I think I can consider using KOReader full time. Part of the reason I wanted to switch back to KOReader (though I like the library layout of the default Kobo software) is that I have been having difficulty figuring out how to export and save my extensive annotations, i.e. highlights, notes etc. when I do these to sideloaded books on the device. Kobo does not offer any elegant or free solution to backup highlights and the ones via Calibre plugins are also severely limited I think. But KOReader creates a `.cbr` file which should make taking a backup and restoring (or even using it on other software?) possible! And I know @poire-z has made a few prototypes for a metadata based virtual folders to help offer a library view like the default one. I hope these things come together to give us all some excellent options to browse books. 

Anyway, that is a bit of a tangent. Now, if I want to apply this fix to my installed version of KOReader, what is the best way to go about it? Install today/tomorrow's nightly or simply copy the changed file to my installed version?

**Comment by Frenzie** [comment]
That pretty much comes down to the same thing, give or take how old your current version is in which case the one file may not be compatible.
