### ISSUE TITLE
'Extract and cache...' feature finds no books in cache database

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#11375]
* KOReader version: 2024.01-30
* Device: Libra2, Sage

The feature extracts metadata from books already extracted.

**Comment by NiLuJe** [comment]
Despite choosing "Don't refresh", I assume?

**Comment by gerhaher** [comment]
Yes, of course.

**Comment by NiLuJe** [comment]
I think I can repro on the emu, FWIW. Not super familiar with how it's supposed to perform, but I do recall testing it a while back at @poire-z behest for... something, so this is probably recent. Ping @hius07?

**Comment by NiLuJe** [comment]
#11380 seems to have taken care of it ;).
