### ISSUE TITLE
FR: Ability to disable virtual keyboard

### ISSUE THREAD

**Issue by tarkeez** [koreader/koreader#11374]
**Does your feature request involve difficulty completing a task? Please describe.**

KOReader on non-touch devices where you have a physical keyboard could benefit from the ability to disable the virtual keyboard because it just takes up space on screens with input boxes (search etc).

**Describe the solution you'd like**

Setting to disable virtual keyboard

**Comment by Frenzie** [comment]
I think the main reason is for special characters, also see #8859. But perhaps that could go in two steps: first minimize, then unfocus.

**Comment by NiLuJe** [comment]
`Back` is already bound to close the VK, FWIW.

**Comment by tarkeez** [comment]
Yeah but from a quick test on PC, pressing back (esc) to hide the keyboard will unfocus the input field or something, as you can't input after that. And other things.

1. Open file search
2. Esc to hide virt keyboard
3. Typing isn't registered

also

1. Open file search
2. Type something
3. Esc to hide virt keyboard
4. Enter key doesn't search, but brings up virt keyboard again
5. Can only type with virt keyboard now
6. Esc will close the search box completely from here

I guess it's minor stuff, but hey. I like KOReader on PC (unified interface, highlighting synced across devices, dictionaries all set up, translate working well for multiling reading etc), so it would be nice to be able to contribute to improvements on PC/non touch.

**Comment by pazos** [comment]
> I guess it's minor stuff, but hey. I like KOReader on PC (unified interface, highlighting synced across devices, dictionaries all set up, translate working well for multiling reading etc), so it would be nice to be able to contribute to improvements on PC/non touch.

SDL targets don't receive much love here.  After all they're just repackaged emulators.

I think the people who like KO enough to run it on a regular desktop without touchscreen, myself included, takes "unified interface" over specific platform quirks :)

But I wouldn't mind an opt-in **hide virtual keyboard** option for such targets.

**Comment by ryanwwest** [comment]
In some issue last year I asked about how to hide it as well, though my request was about dynamically doing it according to keyboard detection and I think there were some challenges with detection. But @pazos 's opt-in idea is much simpler and easier to implement, I like it and would use it.

**Comment by Commodore64user** [comment]
having just installed KOReader on kindle keyboard (K3), yes please let us hide the virtual keyboard. the way stock works is that you press the `Sym` key and that way you get access to special characters, otherwise they are just hidden.

Also, kind of related too, the `Del` key does not actually delete anything.

**Comment by Commodore64user** [comment]
#12078 includes a shortcut to hide the virtual keyboard without losing focus ("Shift" + "Home")  albeit, on a case by case basis, so you will have to manually hide it every single time.

Question, is there an equivalent key for "Home" on normal keyboards?

**Comment by NiLuJe** [comment]
There's a `⇱` *button* in some widgets (most prominently anything based on the Text Editor).

**Comment by Frenzie** [comment]
Ctrl + up/down is the same as Home/End, but why?

**Comment by Commodore64user** [comment]
> Ctrl + up/down is the same as Home/End, but why?

Just making sure it could be used everywhere not just on readers with keyboards.

**Comment by Commodore64user** [comment]
no promises atm but if one were to embark on this somewhat tedious task, would something like this be acceptable or do you have any other ideas,

replacing all these instances: https://github.com/koreader/koreader/blob/7ebd067a95886392b3894bed0d4a0c50de475b59/frontend/apps/reader/modules/readersearch.lua#L273

with something like:

```lua
if Device:hasKeyboard() then
    if G_reader_settings:nilOrTrue("virtual_keyboard_enabled") then
        self.input_dialog:onShowKeyboard()
    end
    return
else
    self.input_dialog:onShowKeyboard()
end
```

**Comment by poire-z** [comment]
> replacing all these instances: 

Well, I'd rather see a single instance of that trick, and not have this in the ~50 places that call it.
Are there contexts where you don't want it (readersearch) and others where you want it?
If no, it's easier to fix it in the InputText/InputDialog:onShowKeyboard() themselves.
If yes, your choices of affected contexts will probably be very personal and questionable :)

**Comment by Frenzie** [comment]
Setting aside what would be the desired behavior for a second, from a code perspective wouldn't it make more sense to put that general concept at the top of onShowKeyboard.

**Comment by Commodore64user** [comment]
> > replacing all these instances: 
> 
> 
> 
> Well, I'd rather see a single instance of that trick, and not have this in the ~50 places that call it.
> 
> Are there contexts where you don't want it (readersearch) and others where you want it?
> 
> If no, it's easier to fix it in the InputText/InputDialog:onShowKeyboard() themselves.
> 
> If yes, your choices of affected contexts will probably be very personal and questionable :)

Well, that seems like the more reasonable approach, idiot me didn't think of it last night, at 3am in the morning 😅

**Comment by edo-jan** [comment]
> #12078 includes a shortcut to hide the virtual keyboard without losing focus ("Shift" + "Home") albeit, on a case by case basis, so you will have to manually hide it every single time.
> 
> Question, is there an equivalent key for "Home" on normal keyboards?

The shortcut hides the on-screen keyboard but also removes the focus from the edit window. As the result the external keyboard cannot be used. The only way to make it work is to click inside the edit window. However, this also brings back the on-screen keyboard. So, back to square one.

**Comment by Commodore64user** [comment]
Works fine on kindle 3, could anyone else confirm if it works for them?

**Comment by poire-z** [comment]
Is that similar to what I described at the bottom of https://github.com/koreader/koreader/pull/12162#discussion_r1688799627 ?:

> It also happens (before or after this PR) that when hiding VK, I can't input from my PC keyboard. When I bring it up again, PC keys work. May be related to SDL start/stopTextInput, @Frenzie ?

**Comment by Frenzie** [comment]
Yes, focus is of course immaterial if SDL_TextInput isn't active, but focus is a prerequisite as well.

**Comment by ToxicFrog** [comment]
> The shortcut hides the on-screen keyboard but also removes the focus from the edit window. As the result the external keyboard cannot be used. The only way to make it work is to click inside the edit window. However, this also brings back the on-screen keyboard. So, back to square one.

This still appears to be happening in 2025.10. I can turn off "show virtual keyboard", but if I do I can't type with the hardware keyboard, either. Pressing shift-home opens the VK and lets me type (but obscures half the screen). Shift-home again hides the VK and removes my ability to type.

**Comment by Commodore64user** [comment]
> This still appears to be happening in 2025.10. I can turn off "show virtual keyboard", but if I do I can't type with the hardware keyboard, either. Pressing shift-home opens the VK and lets me type (but obscures half the screen). Shift-home again hides the VK and removes my ability to type.

see https://github.com/koreader/koreader/pull/12162#issuecomment-2336663923

**Comment by Commodore64user** [comment]
> This still appears to be happening in 2025.10. I can turn off "show virtual keyboard", but if I do I can't type with the hardware keyboard, either. Pressing shift-home opens the VK and lets me type (but obscures half the screen). Shift-home again hides the VK and removes my ability to type.

SDL targets had issues that needed sorting out first. It should work fine now everywhere once #14901 is merged. Mothers! Hide your keyboards 'cause we're comin' to town.
