### ISSUE TITLE
Menu item is not tapped if tapping not on the menu item name

### ISSUE THREAD

**Issue by 672493** [koreader/koreader#11379]
* KOReader version:
* Device:

#### 
Starting from v2024.01-30-g3b129e2ad_2024-01-16 menu item works only if you tap exactly on the menu item title. If you touch menu item line but not it's title menu doesn't work, nothing happens. 

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
Probably due to #11364.

**Comment by poire-z** [comment]
Mentionned at https://github.com/koreader/koreader/pull/11364#issuecomment-1894454657
Fix coming soon with #11366.
