### ISSUE TITLE
bellow menu not show up correctly

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#11389]
* KOReader version: v2024.01-42g7f33d94c4_2024-01-19
* Device: kindle paperwhite

#### Issue
after problem fix that mention in #11379
Bellow menu not show correctly in kindle pw
Sometime it is not show up, or partial, or not clear for old content in screen.
For example swap from down to up to open bellow menu show noting but if you lock and unlock kindle that you see menu.
Or tap on icons just show them

#### Steps to reproduce
- update to last version
- open a book
- try to open bellow menu with swape from down to up.

See it is not show menu correctly
![dcdbfca4-007d-4712-8647-d7ca482d9d42 jpg](https://github.com/koreader/koreader/assets/25131576/45c7f6ff-16bb-41ba-ae4b-eeb67d672e61)
![3d1ff0c2-7161-4877-94e6-f9152eb8038e jpg](https://github.com/koreader/koreader/assets/25131576/3cd30227-ee9a-4143-a31d-d9de77d26642)
![93773e5d-81b7-4b11-8cee-dd3f4c4dd063 jpg](https://github.com/koreader/koreader/assets/25131576/2f1abaef-86c0-4de0-869b-7c2259b494c5)

If you lock and unlock kindle it show correct menu but switch in menus just update partially

**Comment by poire-z** [comment]
Indeed, even on the emulator, if I tap at the bottom, I don't see anything show up - but I can tap where I guess the bottom widgets could be, and they react.
Probably another side effect of @NiLuJe 's "dimen" / FrameContainer tweaks.
