### ISSUE TITLE
segfault in mupdf on large CBZ

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11386]
* KOReader version: 2023.10-82
* Device: Kindle Scribe (5.16.2)

#### Issue
Tried to open a large CBZ file with images of 1200 dpi. File itself is not the heaviest one I tried to open before, but it doesn't open - KOReader complains that there is no engine to read this file.
Also, long-pressing the file (I wanted to refresh the cache) kills KOReader with stackoverflow (porbably OOM?)

File: https://disk.yandex.com/d/pEs-5Suhzu7w5Q

#### Prequel
This file is me trying to convert a very heavy PDF (400+ MB) to CBZ. PDF is so heavy because there are heavy pages with vector-images of maps (page 5 and on).
However, CBZ didn't work out as well.

##### `crash.log` (if applicable)
Me trying to open the file and then long pressing it:
[crashlog_large_cbz.txt](https://github.com/koreader/koreader/files/13980621/crashlog_large_cbz.txt)

**Comment by mergen3107** [comment]
`no book information: too many interruptions or crashes`: it what it says when it didn't open the file, but before the crash.

I then processed the same files with my manga-script to make it true 8-bit grayscale with dithering, and it opened OK!

**Comment by mergen3107** [comment]
Also, when that huge PDF didn't show up on page 5 (with heavy maps), KOReader basically froze. I hit power button twice, and was greeted with `No gesture is setup, tap to unlock`. I did tap, and it stayed on the screensaver with this message - most probably because it was still frozen.

But why did it loose the fact that there was a gesture setup? Is there something that needs a fix in the screensaver life cycle? After doing `killall reader.lua` and starting KOReader again I confirm that settings were still in place and screensaver worked OK.

**Comment by mergen3107** [comment]
Also, after another `killall reader.lua` I deleted this CBZ on Kindle via sftp, and started KOReader again.
It started with a prompt, that file cannot be found because it was deleted or Kindle is connected to computer (or something). I hit cancel, but it froze again - with the same screensaver losing gesture to unlock.

**Comment by Frenzie** [comment]
My understanding is that the FUSE file system on Kindle is very brittle.

**Comment by hius07** [comment]
> * KOReader version: 2023.10-82

Can you try the latest nightly?
It's hard to trace old version crash.

**Comment by hius07** [comment]
Do not forget to remove your grid userpatch.

**Comment by mergen3107** [comment]
OK, I can try a little later :D need to figure which one of my multiple patches were merged already

**Comment by mergen3107** [comment]
Similar but not the same story on 2024.01-36 (applied last two commits as patch):
[_LARGE.CBZ.log_2024.01-36.txt](https://github.com/koreader/koreader/files/13981505/_LARGE.CBZ.log_2024.01-36.txt)

I renamed the huge file to `_LARGE.CBZ` so it is easier to follow in the log.
1) Opened KOReader, went to FM, tried to open the file.
2) It said, no engine found. The text underneath says things about too many interruptions.
3) Long-tap - worked OK, no crash. Hit refresh cache. Text in the filename changed to that state when it is usually time to refresh cache, with an ellipsis in the end.
4) Cache extraction however has never ended.
5) Long-press again, there is no button to refresh cache (it is still "ongoing").

**Comment by hugleo** [comment]
```
error: malloc of array (13200 x 30600 bytes) failed
[!] doShowReader coroutine crashed:
./ffi/mupdf.lua:78: could not run page: malloc of array (13200 x 30600 bytes) failed (1)


01/18/24-15:46:37 DEBUG Seen 1 previous attempts at info extraction /mnt/us/books/Physics/_LARGE.CBZ , trying again 
01/18/24-15:46:37 DEBUG DocumentRegistry: Increased refcount to 3 for /mnt/us/books/Physics/_LARGE.CBZ 
error: malloc of 403933200 bytes failed
error in subprocess:	./ffi/mupdf.lua:78: could not run page: malloc of 403933200 bytes failed (1)
```


Is it a non-compressed zip (CBZ) file? 
Does the CBZ consist of small images, each one representing a PDF document page? 
You can divide the CBZ into parts, for example, 100 MB for each group of pages. 
Additionally, try placing some of the images in a folder and attempt to open them individually.

**Comment by mergen3107** [comment]
Yes, this is uncompressed zip renamed to cbz. 

It contains "folders" which contain chapters, which contain 1 image = 1 page (1200 dpi) files. 

I eventually opened the whole CBZ after making changes the same way I usually do manga (see my post above).

**Comment by NiLuJe** [comment]
> 1200 dpi

Menaingless, talk to me in amount of pixels, please ;).

Also, what's the pixel format?

The crash is a malloc failure for a *single* pixmap, so the way the container is built is irrelevant, the issue stems from an actual image file and how it's encoded (and/or its resolution).

**Comment by NiLuJe** [comment]
> to make it true 8-bit grayscale with dithering, and it opened OK!

^ This is the way ;).

**Comment by hugleo** [comment]
Yes,

> 500 M just for the first 1.6 m png image ;-)

$ echo "Memory Usage: $(ps -p $(pgrep mupdf) -o rss=) KB"
Memory Usage: 543144 KB
$ echo "Memory Usage: $(ps -p $(pgrep okular) -o rss=) KB"
Memory Usage: 686944 KB

**Comment by mergen3107** [comment]
> Meaningless, talk to me in amount of pixels, please ;).

`identify` says:
```
PNG 10200x13200 10200x13200+0+0 8-bit sRGB 1.60328MiB 0.000u 0:00.000
```

**Comment by NiLuJe** [comment]
Yeah, that's not going to work ;p.

**Comment by mergen3107** [comment]
Alright :D what's the max size allowance?

**Comment by hugleo** [comment]
apply proportionality I suppose?

Dimension        memory required
10200x13200  - 543144 KB
X              -         Y

**Comment by Frenzie** [comment]
> Alright :D what's the max size allowance?

Depends on your available memory. ;-)

Though practically speaking at most a few hundred MB on most devices

**Comment by NiLuJe** [comment]
I wouldn't go above the screen resolution (or something like twice that if you're a panel zoom aficionado). But if you're reading in what essentially amount to 1:1 zoom (which is what you should be doing on a large device), higher resolution images make absolutely no sense anyway ;).

**Comment by mergen3107** [comment]
Thanks everyone :D
