### ISSUE TITLE
FR: Tell KOR where a book actually ends.

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11393]
**Does your feature request involve difficulty completing a task? Please describe.**
Some eBooks include a myriad of stuff at the end of the actual text, i.e pictures, footnotes, notes, chapters from next book in series, etc. and some data is therefore skewed by all these extras, i.e pages, progress etc.

**Describe the solution you'd like**
An option to 'voluntarily' tell the reader where a book actually ends so it displays this on the progress bar settings, i.e 206 pages instead of 233 pages. it could look something like this: 83 / 206 (233), and the % to also adjust accordingly, it would use 83 div 206 instead of 233.
you could also add some options in the settings to let user  decide whether you want to show actual file page length or not:
87 / 206   or   87 / 206 (233).
if you have told the software where the last page is, and then you make any changes to font size, margins etc, it would prompt you to re-enter the new last page.

**Describe alternatives you've considered**
Dealing with it.

**Additional context**
I am not sure if it is something that could be automatically figured out by the software, therefore a manual option is perhaps the best approach.

**Comment by poire-z** [comment]
You asked... you have it!
In books where you need that, enable in top menu first panel `Settings > [x] Custom hidden flows`
and read about it in the subsection `Custom layout feature > About custom hidden flows`.
As a user meeting this feature for the first time, read this, try to figure it out, play with it and tell us if that was enough to get you started and how it works for you.

(Only later, if you want to read more about it, it was added by #10982 and discussed in the linked other issue.)

**Comment by poire-z** [comment]
(Well, I have no idea - and don't really want to know :) - how this works on a non-touch device, if that's the only device you own, according to your other issue #11295 :/)

**Comment by Commodore64user** [comment]
Wow, this is a lot more than I thought it could be. Bravo!, i tried it and it works brilliantly. I took me two attempts to realise i am supposed to ‘hide’ the extras, not the main text but it’s working fine now.

some notes, I don’t think a newbie would know or understand what “hidden flows” are nor how to set them up. For me reading the descriptions made sense because i already knew what i was trying to achieve, to someone unaware, perhaps they would simply skip all over it.

Praise the koreader gods.

**Comment by poire-z** [comment]
> some notes, I don’t think a newbie would know or understand what “hidden flows” are nor how to set them up. For me reading the descriptions made sense because i already knew what i was trying to achieve, to someone unaware, perhaps they would simply skip all over it.

I guess that's fine, and in the spirit of the whole program: have it work simply by default, and allow users that need advanced features (ie. Style tweaks, Typography, alternative Toc...) to get them when they need them (and spend the time learning and experimenting) - which justify to have them a bit hidden in submenus (with the side effect, like it happened with you, that users don't know that these features exist).

**Comment by offset-torque** [comment]
I am currently adding this feature for our user guide, **Commodore64user**. And I am writing it in a simpler way that even non-technical users will understand clearly. Screen space for information tooltips in KOReader is limited so it is not possible to explain whole feature in those popups. So they tend to be more concise and technical unfortunately.

**Comment by Frenzie** [comment]
Suggestions for changed wordings for popups in the program are also welcome of course.

**Comment by Commodore64user** [comment]
one of the things I've noticed is, that if you long press on a setting, it will 1) let you change default behaviour and 2) give you a little explanation of what that setting is. For some options however, like hidden flows, nothing happens (I understand you don't want this to be on by default, thus number 1 would not apply) but that could be an opportunity to explain what hidden flows are. 

In my opinion, the second paragraph (and last one too) on 'About custom hidden flows' could be moved to a long press on 'custom hidden flows' that way freeing up some space for more technical details in the About popup.

in the spirit of not knowing which settings give you an explanation of what they do with a long press, it would be cool if there was some sort of indication of which ones have that available, maybe the circle with the i in the middle as an exponent?

But once again, great job guys, and thank you for your hard work.
