### ISSUE TITLE
Checkered Screen When Using Screensaver

### ISSUE THREAD

**Issue by swaggy-p-jp** [koreader/koreader#11390]
* KOReader version: 2024.01
* Device: Kindle Paperwhite 5

#### Issue

I've set a folder called `screensavers` that I save images to on the root folder of the kindle and have that set as my screensaver folder in KOreader. However, from time to time, it's unable to load the images and I get this checkered image as a result. 
![PXL_20240119_174918687](https://github.com/koreader/koreader/assets/86895685/53eeb96e-f541-43a8-993f-3b57785ad3cf)

#### Steps to reproduce

1 - Create folder called `screensavers` on root of kindle
2 - Save pngs to folder
3 - Set that folder to be your screensavers folder on KOreader

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
error: unknown image file format
01/19/24-11:48:29 WARN  failed rendering image (MuPDF): ./ffi/mupdf.lua:78: could not load image data: unknown image file format (2) 
01/19/24-11:48:29 WARN  ImageWidget: Failed to render image file: /mnt/us/screensavers/._dZ9H2sT.png 
```
</details>

#### Thoughts

I've checked to see if there were any hidden files but there doesn't seem to be any in the folder. Not sure why it's putting the dot and underscore in front of the name 🙁 
Posted below are the names of the file and their sizes:

|Name | Size |
-------|:----:|
DenS7hK.png | 496 KB | 
dZ9H2sT.png | 123 KB | 
EnVOpu7.png | 875 KB |
mfxqzNz.png | 136 KB |
qXabFbi.png | 451 KB |
screenshot_2024_01_19T11_17_56-0600 copy.png | 635 KB |
screenshot_2024_01_19T11_18_13-0600.png | 1 MB |
VwzYiXq.png | 554 KB |

**Comment by NiLuJe** [comment]
That's the fallback for a broken image, IIRC.

**Comment by NiLuJe** [comment]
> Not sure why it's putting the dot and underscore in front of the name 🙁

Oh. because you're on macOS (or your device was browsed in that folder over USB from a macOS device), and this is a resource fork (a.k.a., Apple Double), not an actual image file.

We should already be ignoring those, so, that's weird (or a regression).

**Comment by Frenzie** [comment]
My guess would be the file picker widgets ignore it but that the screensaver uses straight up lfs instead of such an interim.

**Comment by NiLuJe** [comment]
Regression it was ;).

The old implementation was inlined in the dir walk, so it got a relative path; the new one gets fed an absolute one, which broke the first check.

**Comment by NiLuJe** [comment]
It'll be in tomorrow's nightly, yeah.
