### ISSUE TITLE
Minor next image offset issue in CBZ when applying zoom modes

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#11405]
When applying certain zoom modes to a CBZ file, I've noticed a slight downward shift in the placement of the next image instead of it appearing at the top
Ideally, the top of the image should be displayed first.

zoom:
![set_zoom](https://github.com/koreader/koreader/assets/4573505/2febec7b-cf7d-4b25-8feb-f0ae16690887)

go to the next page and the image is shifted:
![page_2](https://github.com/koreader/koreader/assets/4573505/39873caf-c4ad-41fd-b4b1-58274d404b66)

how should be:
![should_be](https://github.com/koreader/koreader/assets/4573505/eab6883e-3544-4844-a179-fa58db508a77)

[test_case.zip](https://github.com/koreader/koreader/files/14051320/test_case.zip)

**Comment by poire-z** [comment]
Fixed by #11408.
