### ISSUE TITLE
Is it possible to build the koreader on the RISC-V architecture?

### ISSUE THREAD

**Issue by KirillYatsenko** [koreader/koreader#11406]
I'd like to use Milk-V Duo SBC to interface with some SPI Eink Display.

However, this SBC is the RISC-V architecture.

The main application would be the koreader which I want to run on boot.

But, I'm not sure if it's can be cross-compiled for RISC-V

![image](https://github.com/koreader/koreader/assets/14968248/00311909-0fd4-4296-a8d7-ec462e9dcbe0)

**Comment by Frenzie** [comment]
The short answer is no, since LuaJIT doesn't support it: `https://github.com/LuaJIT/LuaJIT/issues/628`

**Comment by braydonf** [comment]
@kyatsen It is now possible with a few small changes to the KOReader base to build for RISC-V. As detailed, the most signifigant change necessary is support for RISC-V in LuaJIT, there is however an open pull request to add support (https://github.com/LuaJIT/LuaJIT/pull/1267) 

All of the steps that were necessary have been documented at:
https://gist.github.com/braydonf/44558bb0862c9aa188df20a3f7ec9307

**Comment by braydonf** [comment]
Related issue: https://github.com/koreader/koreader/issues/11624
