### ISSUE TITLE
KOReader crashed when searching text

### ISSUE THREAD

**Issue by linchangyi** [koreader/koreader#11409]
* KOReader version: 2024.01
* Device: kobo libra2

#### Issue

KOReader crashed when searching text in some epub books

#### Steps to reproduce

- open the epub book provided in attachments.
- excute fulltext searching.
- then KOReader crashed like this ![IMG_20240126_104452](https://github.com/koreader/koreader/assets/6831676/d088316f-ad9f-4332-b91b-c35d2442ce7e)

[epub file and crash screen.zip](https://github.com/koreader/koreader/files/14059924/epub.file.and.crash.screen.zip)

**Comment by hius07** [comment]
CJK book.

Confirm, on forward/backword search got
```
01/26/24-08:02:03 WARN  unwrapped dismissablePopen(), falling back to blocking io.popen() 
01/26/24-08:03:03 WARN  unwrapped dismissablePopen(), falling back to blocking io.popen() 
lipc-wait-event exited normally with status: 0
Segmentation fault
```
https://github.com/koreader/koreader/blob/b832d43d985778e36841b7d08cf3db5436f26249/frontend/ui/trapper.lua#L341

"All" search gives no results for any search string, even for a symbol copied from the text.

**Comment by hius07** [comment]
> * KOReader version: 2024.1

So, not related to recent adding the "All" search feature.

**Comment by poire-z** [comment]
Consistent backtrace:
```
Thread 1 "luajit" received signal SIGSEGV, Segmentation fault.
ldomNode::getAbsRect (this=0x0, rect=..., inner=inner@entry=false) at crengine/src/lvtinydom.cpp:18548
18548     ASSERT_NODE_NOT_NULL;
A debugging session is active.

 Inferior 1 [process 8948] will be killed.

Quit anyway? (y or n) n
Not confirmed.
(gdb) bt
#0  ldomNode::getAbsRect (this=0x0, rect=..., inner=inner@entry=false) at crengine/src/lvtinydom.cpp:18548
#1  0x00007fffe0cbf521 in ldomNode::elementFromPoint (this=this@entry=0x55555727bca0, pt=..., direction=direction@entry=3, strict_bounds_checking=strict_bounds_checking@entry=false)
    at crengine/src/lvtinydom.cpp:18901
#2  0x00007fffe0cbfc84 in ldomDocument::createXPointer (this=this@entry=0x55555713f330, pt=..., direction=3, strictBounds=strictBounds@entry=false, fromNode=fromNode@entry=0x0)
    at crengine/src/lvtinydom.cpp:9581
#3  0x00007fffe0ccab55 in ldomDocument::findText (this=0x55555713f330, pattern=..., caseInsensitive=caseInsensitive@entry=true, reverse=reverse@entry=false, minY=minY@entry=2928, maxY=349914,
    maxY@entry=-1, words=..., maxCount=2048, maxHeight=1220, maxHeightCheckStartY=3491, patternIsRegex=false)
    at crengine/src/lvtinydom.cpp:11644
#4  0x00007fffe0c888d8 in findText (L=0x7ffff7cb6380) at cre.cpp:3735
```
(Haven't yet looked at the code.)

Does not happen with all CJK books.
Does not happen on this book when either "Embedded styles off" or "Render mode flat".
The CSS stylesheets don't look too bad. They contain a few `float: left/right`, so possibly related to that (although no crash when searching in my huge test-float.html file).

> `unwrapped dismissablePopen(), `

Do you get that on your own Kindle(s) too ? (I don't get it on the emulator and neither on my Kobo.) Is it logged when doing a search, and yes, is the search interruptible? Might be some other unrelated issue to investigate.

**Comment by hius07** [comment]
> Do you get that on your own Kindle(s) too ? (I don't get it on the emulator and neither on my Kobo.) Is it logged when doing a search, and yes, is the search interruptible? Might be some other unrelated issue to investigate.

Yes, got it on Voyage.
The search (fwd and all) is very quick, no time to interrupt.

**Comment by poire-z** [comment]
Do you get it logged also with other (English) books ? If yes, you can search for "e" or "the", which should be less quick :)

**Comment by hius07** [comment]
No for en/ru books for any search.

**Comment by linchangyi** [comment]
> Does not happen on this book when either "Embedded styles off" or "Render mode flat".

It does not crash on your device when turning off embedded styles? But mine is the same.

**Comment by poire-z** [comment]
We're talking here about the log `unwrapped dismissablePopen()` only, right? So you mean this depends on the kind of book, and it is logged before any search is done and get the chance to crash ?!
Or is it that for some reason, on a fresh koreader startup, a first search is done in a subprocess, crash that subprocess (but not the koreader), and subsequent searches are then no longer done in a subprocess (so this log) and crash koreader?

**Comment by poire-z** [comment]
> It does not crash on your device when turning off embedded styles? But mine is the same.

After giving koreader the time to re-render the book and reload the document (icon in the top left corner gone away)?
And what if you let it do that re-render and re-load, and then exit and relaunch koreader - and the only do a search?

**Comment by linchangyi** [comment]
> > Does not happen on this book when either "Embedded styles off" or "Render mode flat".
> 
> It does not crash on your device when turning off embedded styles? But mine is the same.

I tried again, but this time I quit the book first after turning off embedded styles, then open the book again, and the searching performs well this time.

**Comment by hius07** [comment]
I see now it segfaults on fwd search without trapper warning.

**Comment by hius07** [comment]
I think the trapper warning was caused with an interrupted prerendering, so not an issue.

**Comment by poire-z** [comment]
Well, I can't manage to get any `WARN  unwrapped dismissablePopen(), falling back to blocking io.popen()` logged, and this is not normal. (And the segfault is another totally different issue, that I'll investigate later).

Could you put in trapper.lua after the function that prints the warning:
`logger.warn(debug.traceback())`
so we can maybe see a bit more of where from / what is calling this dismissablePopen() ?

Also, to my surprise, it seems there is only one caller of dismissablePopen(): when readerdictionary call sdcv - so totally unrelated to our stuff here (unless may be if the Search is invoked from DictLookup ? but then the sdcv lookup is done and long gone...)

**Comment by poire-z** [comment]
About the segfault, it sems to be some really edgy case :)
When doing a search forward, we somehow need to get the xpointer of the bottom of the document.
In the last page of this EPUB, there is a float left (the QR code image), and some text on its right.
![image](https://github.com/koreader/koreader/assets/24273478/9acc68a8-585f-40eb-ac5c-03e523401f34)

If I add in the text enough content (some `<br><br><br>zzz` here) so the float is no longer the bottomest thing that makes the "bottom" of the document, no segfault:
![image](https://github.com/koreader/koreader/assets/24273478/34469426-51e3-4021-891f-87dd71b46af8)

So, I guess it's just that edgy case that I never met nor think about :) that I will have to fix.
But it's indeed not really related to the search feature (except that search may be the only thing requesting a xpointer for the bottom; when reading and leaving on the last page, we store as last_xpointer the top of this page, which would be the first character of the first list of regular text).

**Comment by hius07** [comment]
No, cannot reproduce trapper warning.
Deleted sdr, cr3cache, db cache, changed different fonts, made searches, interrupted prerendering - cannot reproduce.

**Comment by poire-z** [comment]
Try a dict lookup. And then a second dict lookup. Zero, one or two such warnings ?
If zero, try another dict lookup with a not-real word (so it takes time to lookup with fuzzy search, nd you can interrupt it). Then a second such dict lookup: zero, or or two such warnings ?

**Comment by hius07** [comment]
Oh, I got the warning on 2024.01 release (with "All search" patches).
Now I'm on the latest nightly.

**Comment by hius07** [comment]
Gotcha, dictionary lookup of selected cjk symbol causes trapper warning.
Lookup of selected "Madame" goes well.

**Comment by hius07** [comment]
```
01/26/24-16:23:17 WARN  unwrapped dismissablePopen(), falling back to blocking io.popen() 
01/26/24-16:23:17 WARN  stack traceback:
	frontend/ui/trapper.lua:342: in function 'dismissablePopen'
	frontend/apps/reader/modules/readerdictionary.lua:818: in function 'rawSdcv'
	plugins/japanese.koplugin/main.lua:188: in function <plugins/japanese.koplugin/main.lua:112>
	[C]: in function 'pcall'
	frontend/pluginloader.lua:32: in function <frontend/pluginloader.lua:31>
	[C]: in function 'pcall'
	frontend/languagesupport.lua:117: in function 'callPlugin'
	frontend/languagesupport.lua:145: in function '_findAndCallPlugin'
	frontend/languagesupport.lua:209: in function 'improveWordSelection'
	frontend/apps/reader/modules/readerhighlight.lua:1294: in function 'handler'

```

**Comment by poire-z** [comment]
> Looks like the Japanese plugin doesn't wrap the dict call.

Indeed (I have that plugin disabled, so didn't see it).
And may be he can't really wrap it (if done in the synchronous text selection part - or the whole code would need to be wrapped by Trapper:wrap(), which may cause issues).
So, ok, Japanese/CJK users do get these bits of log, but they have not been bothered by it. And neither will us, now that we know where that comes from :)
(Or we would add a third param, `no_warning_if_not_wrapped` to avoid it, that ReaderHighlight/ReaderDict would have to pass down...)

**Comment by poire-z** [comment]
Ok, segfault fixable with:
```diff
--- a/crengine/src/lvtinydom.cpp
+++ b/crengine/src/lvtinydom.cpp
@@ -18898,7 +18898,15 @@ ldomNode * ldomNode::elementFromPoint( lvPoint pt, int direction, bool strict_bo
             if ( pt.y >= fmt.getY() + fmt.getHeight() ) { // pt.y is inside the box bottom overflow
                 // Get back absolute coordinates of pt
-                lvRect rc;
-                getParentNode()->getAbsRect( rc );
-                lvPoint pt0 = lvPoint(rc.left+pt.x, rc.top+pt.y );
+                lvPoint pt0;
+                ldomNode * parentNode = getParentNode();
+                if ( parentNode ) {
+                    lvRect rc;
+                    parentNode->getAbsRect( rc );
+                    pt0 = lvPoint(rc.left+pt.x, rc.top+pt.y );
+                }
+                else {
+                    // No parent node: we are the root node (and the origin of absolute coordinates)
+                    pt0 = pt;
+                }
                 // Check each of this element's children if pt is inside it (so, we'll
                 // go by here for each of them that has some overflow too, and that
```
@linchangyi : as this is very edge case, I'm not hurrying commiting it and bumping the fix into KOReader, I'll do that next time I have other substantial changes to bring it with.
In the meantime, for this book if you want to use search, just switch Render mode (in the bottom menu) to "flat" (instead of "book" or "web") - I checked that there is no other "float" in this book, so you shouldn't miss any much formatting when using "flat".
