### ISSUE TITLE
in fdroid build: PDF file turns "invalid" after saving annotation in KOReader #9313 

### ISSUE THREAD

**Issue by xebeque** [koreader/koreader#11403]
* KOReader version: latest fdroid builds 2024.01
* Device: several devices running treble/aosp/lineage

#### Issue
Saving annotations turns PDF "invalid", cannot be opend AS decibed in Bug #9313 

#### Steps to reproduce
Annotate, save, try to open: file is invalid with any pdf reader, seems exactly like bug #9313 to me.
Had not been a problem in recent releases before the last 2 fdroid builds.

**Comment by Frenzie** [comment]
Please keep discussion in the other issue.

**Comment by xebeque** [comment]
OK, thanks for moving the report 

Am 24. Januar 2024 21:30:59 MEZ schrieb Frans de Jonge ***@***.***>:
