### ISSUE TITLE
Unresponsive file browser when touch is disabled

### ISSUE THREAD

**Issue by mjtimblin** [koreader/koreader#11400]
* KOReader version: v.2024.01
* Device: Onyx Boox Page (Android)

#### Issue

I previously reported an issue (#11117) related to this that was addressed in the most recent release. Thank you! I have just had a chance to update to the latest version of KOReader, and I found the following issue when I attempted to re-create issue #11117.

Essentially, a user is able to navigate to the file browser when touch is disabled. If a user does so, KOReader is unresponsive. The tap corner gestures don't work in the file browser, and the user must use a workaround (e.g. locking and unlocking the device, exiting and re-opening the app, etc) to use KOReader again. 

#### Steps to reproduce

1. Setup a tap corner gesture to toggle touch input
2. Open a document
3. Disable touch input using the tap corner gesture
4. Use page turn buttons to complete the book
5. When the end of the document modal appears, select "File browser"
6. Touch input is now disabled in the file browser

**Comment by Frenzie** [comment]
What precisely is the issue from your perspective? Naïvely I would think 6 is the desired result, which would make the main issue the fact that it's slightly laborious to set up the same gesture in both the file browser and the reader. (Although perhaps ideally it would note that no exit method has been set up yet.) But as a regular user of the feature perhaps you feel is should cancel in such scenarios regardless?

**Comment by mjtimblin** [comment]
I wasn't aware of the separate gesture definitions for the file manager and document viewer. I thought the custom gestures aren't enabled in the file browser since mine weren't working (weren't defined for the file browser). Re-defining my gestures for the file browser solves this issue.

Are the separate gesture definitions for the file manager and the document viewer documented in the manual? I didn't see it mentioned anywhere, but I wouldn't be surprised if I just missed it. "File browser" and "Reader" actions are also both visible in the gesture manager regardless if I'm creating a gesture for the reader or the file browser. Is this intentional?

**Comment by Frenzie** [comment]
I don't think it did that when I originally wrote it, but I don't know if it was purposefully changed in the current iteration or if it's some kind of oversight. Maybe it has something to do with profile functionality where you can construct actions involving both.

Given that it's a little bit buried, targeting advanced users I'm not too bothered by it but it does go against the general design (i.e., don't show a ton of distracting irrelevant stuff that's harmless at best).

**Comment by mjtimblin** [comment]
That makes sense. Thanks for the help!
