### ISSUE TITLE
Text selection for dictionary does not work in all corners

### ISSUE THREAD

**Issue by mini54** [koreader/koreader#11413]
* KOReader version: v2024.01
* Device: Onyx boox Nova3 - android

#### Issue
I use stardict diktionary and this works very well, but it is impossible to select text in all 4 corners. It is not a problem with my device, because selecting text in the corners works very well, for example in cool reader and other ebook reader applications. This problem has also occurred with previous versions of koreader

**Comment by Frenzie** [comment]
I think the corners default to pass through, unless you set them to something else.

What precisely happens when you try to do this?
<img src=https://github.com/koreader/koreader/assets/202757/a4d57cdb-3a16-4fa7-a57a-8fbb8fdeacf9 width=50%>

**Comment by mini54** [comment]
Nothing happens. As I described, I cannot select the text in the corners. All other places work the same way as you show in your picture.

**Comment by mergen3107** [comment]
What's your gestures on "Hold corners"?

**Comment by mini54** [comment]
Long-press on corner:
Top left (Nothing)
Top right (Nothing)
Bottom left (Nothing)
Bottom right (Nothing)

**Comment by mini54** [comment]
Ok, I have changed to:
Long-press on corner:
Top left (Pass through)
Top right (Pass through)
Bottom left (Pass through)
Bottom right (Pass through)
and now it is working correctly for me.
Thank you for your help !!

**Comment by mergen3107** [comment]
Great!

For future reference, "Pass-through" means there is no override to the action if the gesture happens to be this one (hold corners). 

"Nothing" means there **is** override, specifically to cancel any actions of this gesture.
