### ISSUE TITLE
FR: Option to render footnotes on current page similar to print books

### ISSUE THREAD

**Issue by trini** [koreader/koreader#11411]
**Does your feature request involve difficulty completing a task? Please describe.**

Footnotes are hard to read in context currently. In footnote heavy documents this is a problem.

**Describe the solution you'd like**

Visually, what I would like to see is a display option to render a given footnote as part of currently generated and displayed "page". This would look similar to a printed book where typically a footnote will be on the same page, in the footer area and as needed potentially displace the rest of one page on to the next.

Part of why I want this is for ease of reading, I don't want to have to tap on a single letter sized symbol to read something and tap again to return, or even tap to open a display box. As someone who often reads at night for relaxation I don't want to move around a bunch, just get comfortable and tap the screen to change the page.

**Describe alternatives you've considered**

The Kindle app will do an on-screen pop-up, but this isn't as helpful in all cases.

**Additional context**

In more specific context, examples I have in mind would be the Discworld novels where often times a footnote itself will take up half a page.

**Comment by hius07** [comment]
Look at the upper menu - Typeset (2nd) tab - Style tweaks - In-page footnotes.

**Comment by poire-z** [comment]
We already have them (and how pretty, and tweakable!, you'll be amazed when you'll see them for the first time :)).
(When enabling these style tweaks, you may not always see their effects immediatly - some needs to have the book reloaded, so wait for the icon at the top left corner to disappear.)

It just can't be down automatically, it needs help from the publisher (by using the proper attributes in their HTML, or common class names) or from the user to use style tweaks to flag elements that may be considered footnotes. The menu suggested by @hius07 provides these simple ways (long-press on each item to see a description and the CSS).
Many issues discuss that, for example: #9780, #5015.

(If you have never seen them, it means the publishers of the books you read have not done the minimal efforts that most do when making/selling EPUBs.)

**Comment by trini** [comment]
> Look at the upper menu - Typeset (2nd) tab - Style tweaks - In-page footnotes.

Perhaps the problem I have then is that the book itself is badly formatted. What I think of as a foot note does show up with an asterisk (`*`) and touching it links to the reference, and then will link back to where I was. But checking the style tweaks in the Typeset tab doesn't change anything on screen (and I went and increased the font size from the bottom menus to force a re-render, in case that was also needed).

**Comment by Frenzie** [comment]
It might just be older, predating the attributes in question. But definitely try enabling classic classname footnotes, which aren't enabled by default.

**Comment by trini** [comment]
> It might just be older, predating the attributes in question. But definitely try enabling classic classname footnotes, which aren't enabled by default.

Nope, it does recognize it as some sort of link, but in page nor pop-up seem to work. FWIW, the Kindle app for the same epub recognizes it and does the pop-up style it usually does.

**Comment by poire-z** [comment]
Read #9780.

**Comment by Frenzie** [comment]
Also see the calibre ScrambleEbook plugin: https://www.mobileread.com/forums/showthread.php?t=267998

I think it leaves classnames intact.

**Comment by Commodore64user** [comment]
is there some sort of rule for very long footnotes? my copy of the master and margarita (RP and LV translation) has 4 footnotes on very first page, and all put together take about two pages. I am wondering whether I can't see them as in-page because it would be ridiculous to display them that way (which is probably a wise idea) or because koreader does not recognise them as footnotes.

**Comment by poire-z** [comment]
No, there's no specific rule, no wide idea.
If the publisher or you flag some 3-screens-height section of the book as being a footnote, when a link to it in the middle of page 42 of the main book text happen, you will see:
page 42: half of the main book text + half of the screen with 1/6 of the footnote
page 43: only footnote text (so, the little separator at the top, with no main book text)
page 44: only footnote text (so, the little separator at the top, with no main book text)
page 45: the remaining 1/6 of the footnote at the bottom, and the main book text continuation of what was on first page running at top

**Comment by Commodore64user** [comment]
well that seems like a reasonable way of doing it, I suppose, koreader doesn't recognise them as footnotes then.
this is the code from the file.

`<p class="x03-CO-Body-Text">At the hour of the hot spring sunset two citizens appeared at the Patriarch’s Ponds.<a href="47_Notes.xhtml#EndnoteNumber1" id="SuperscriptNumber1"><sup class="endnote">1</sup></a> One of them, approximately ...`

`<p class="x13-BM-Endnotes"><a href="13_CHAPTER_1_Never_Talk_.xhtml#SuperscriptNumber1" id="EndnoteNumber1">1</a>.				<i>the Patriarch’s Ponds</i>: Bulgakov uses the old name for what in 1918 was rechristened ‘Pioneer Ponds’. Originally these were three ponds, only one of which remains, on the place where Philaret, seventeenth-century patriarch of the Russian Orthodox Church, had his residence.</p>`

**Comment by poire-z** [comment]
Because there's nothing standard there that indicates the second snippet is a footnote. A link is not enough, it could be a link to another chapter, and you would get that full other chapter as a footnote :)

For popup footnotes, we can take a bit more risks and [use heuristics to guess if the link and its target are a footnote](https://github.com/koreader/koreader/blob/38a14ff3a070d0d31d9d7d369863d0af5390ae16/frontend/apps/reader/modules/readerlink.lua#L1292-L1386).

For in-page footnotes, as this involves rendering the book (to make pages), we don't take any risks, and follow publisher or user hints.
So, for the snippet above, as the publisher has not set any hint (like tagging the 2nd paragraphe with `<p epub:type="footnote">`, you, seeing the HTML you just copied and pasted (that you can view on device with "View HTML") can set a Book style tweak with:
`p.x13-BM-Endnotes { -cr-hint: footnote-inpage; }`
or, if your publisher is nasty and use other x13... x14... x15:
`p[class$="BM-Endnotes"] { -cr-hint: footnote-inpage; }`

Then, you can use the other style tweaks in the submenu "footnote font size & fixup" to tweak these sections of the document that are put there as inpage footnotes.

**Comment by Commodore64user** [comment]
Looks like I don’t have a nasty publisher.
Adding the first style tweak worked. Nice.
Thank you!

**Comment by poire-z** [comment]
You probably can't use long diagonal swipe in these widgets as they themselves handle swipe their own way.
There's an alternative gesture for taking screenshots, that should rarely/never conflict with other stuff: 2 finger taps, each finger tap in diagonaly opposite corners.

**Comment by Commodore64user** [comment]
hello,

sorry to bother you again.

I am trying the specific style tweak  `p.notes { -cr-hint: footnote-inpage; }` with another book, but it does not work, any ideas?

here is the html:
`<p class="notes" id="shi0005446"><a id="N1_n2"/><a href="chapter001.xhtml#N1n2"><strong>2.</strong></a>   <em>Levitical</em>: Relating to ‘Leviticus’, the third book of the Old Testament. One reviewer complained at Brontë’s ‘jesting with scriptural names, and… light usage of scriptural expressions’ (<em>Atlas</em>, November 1849 in <em>Letters</em>, p. 248).</p>`

I looked at all the footnotes, and they all use the class=notes.

**Comment by poire-z** [comment]
I guess the reason for the failure is what I wrote in the note in https://github.com/koreader/crengine/blob/b5f97c4560ddb9d1ddfad20c858c997045a89649/crengine/src/lvrend.cpp#L4755-L4768
```
            // Notes:
            // It fails when that block element has itself an id, but links
            // do target an other inline sub element id (getFirstInnerAttributeValue()
            // would get the block element id, and there would be no existing footnote
            // for the link target id).
```
So, I guess I must have met the same situation before.
I had no idea at the time how to workaround the case, and still none today :/
Maybe by coding support for another `-cr-hint: footnote-inpage-ignore-id;` that you could add to the declaration. But I'm a bit short on the number of such cr-hint I can still add (~4 left out of 32) without much rework.

(You could edit the epub and substitute all `<p class="notes" id=` with `<p class="notes" fukid=` and I guess it should work then.)

**Comment by Commodore64user** [comment]
okay, I tried substituting the code `<p class="notes" id=` with the `fukid=` and that worked, but it was a bit of a fuss. I am also wondering whether there are any drawbacks or downsides to doing this? 
I think adding the `-ignore-id;` might be more helpful as it would not require to fiddle with the file, or files every time you encounter this problem.

is there a list of all cr-hints that are currently supported? I am curious now.
thanks again.

**Comment by poire-z** [comment]
As with all things style tweaks, we will sometimes meet one book where we can't managed to get what we want, for various reasons (often because the publisher did crap work), so, well, we'll have to live with it - and fallback to popup footnotes on such books.

> I am also wondering whether there are any drawbacks or downsides to doing this?

It's fine, it's your book. I did that a lot before style tweaks existed, and I never do that since then (and sometimes just live with what I can't change - or go coding some reusable solution into crengine :))

> I think adding the -ignore-id; might be more helpful as it would not require to fiddle with the file, or files every time you encounter this problem.

Sure it would - but still postponing the idea as I'm nearly out of bits :)

> is there a list of all cr-hints that are currently supported? I am curious now.

https://github.com/koreader/crengine/blob/b5f97c4560ddb9d1ddfad20c858c997045a89649/crengine/src/lvstsheet.cpp#L3265-L3306
https://github.com/koreader/crengine/blob/b5f97c4560ddb9d1ddfad20c858c997045a89649/crengine/include/cssdef.h#L394-L453

Most are used in some of the style tweaks in our categorized menu.

**Comment by Commodore64user** [comment]
> Sure it would - but still postponing the idea as I'm nearly out of bits :)

sending you lots of bits. ;)

**Comment by poire-z** [comment]
I'm sorry, I didn't receive your bits - they must have been lost or stolen :(

So, I had to give it more thougts.:

> ```
>             // Notes:
>             // It fails when that block element has itself an id, but links
>             // do target an other inline sub element id (getFirstInnerAttributeValue()
>             // would get the block element id, and there would be no existing footnote
>             // for the link target id).
> ```
> So, I guess I must have met the same situation before.
> I had no idea at the time how to workaround the case, and still none today :/

Well, looks like I could just associate the same footnote to the multiple ids found in it, somehow like creating aliases.
I can't remember & find any book that had this issue. Could you share the one you got (the original version, before you fukid'ed it), possibly [scrambled](https://www.mobileread.com/forums/showthread.php?t=267998) if copyrighted - or just upload it here, I get it, and you edit your post to remove the link, and delete the original post under the "edited" history) ?

**Comment by Commodore64user** [comment]
> I'm sorry, I didn't receive your bits - they must have been lost or stolen :(

😳 I feel like I am being called out or something.

this is the book [https://play.google.com/store/books/details/Charlotte_Bronte_Shirley?id=0EwZ8eEgJR0C](url)

there is one thing I didn't mention before, that book has both footnotes and a glossary (a lot of french words being thrown there). I fucked (😅, fukid'd) up the id's on the footnotes but was able to use the `footnote-inpage` just fine with the glossary. So yes, I have both footnotes and glossary as in-page footnotes.

I hope you understand my hesitation for not wanting to post it here, but I suppose if you really, REALLY need it, I could send it to an email address. But only if you pinky promise to delete afterwards.

**Comment by poire-z** [comment]
I understand, no worry :)
I found this book on the chocolate web, with the same HTML bits you pasted, so it must be the same book.
Enough to confirm my changes have it working without the need to fukid it:

![image](https://github.com/koreader/koreader/assets/24273478/db67ca81-01a8-4d6b-81f2-9a5d4510e06a)

![image](https://github.com/koreader/koreader/assets/24273478/d54265a6-5d85-4927-9904-6d891f020099)

Thanks, will be in crengine/KOReader in a few days or weeks.

**Comment by Commodore64user** [comment]
![Reader_2024-02-05_232702](https://github.com/koreader/koreader/assets/97603719/45b38859-1eeb-4f03-89bd-601187512648)

lol, funny how I had captured that very same screenshot a few nights ago. It does indeed seem to be the same edition.

> Thanks, will be in crengine/KOReader in a few days or weeks.

Great news, and no, thank you! for doing the lord's work.

I have a question regarding the nightlies, are they cumulative? I downloaded the latest one 2023.01-63 last night to test the 'search all' new function but was also looking forward to the percentage sorting someone else updated a few weeks ago #11369. But I don't see that option anywhere on that nightly.

**Comment by poire-z** [comment]
> I have a question regarding the nightlies, are they cumulative?

Yes, they include everything that has been merged: https://github.com/koreader/koreader/commits/master

> was also looking forward to the percentage sorting someone else updated a few weeks ago https://github.com/koreader/koreader/pull/11369. But I don't see that option anywhere on that nightly.

Because it as not yet been merged: ![image](https://github.com/koreader/koreader/assets/24273478/a442d347-f300-4961-a3ea-3c530cae7f64)

**Comment by Commodore64user** [comment]
Slightly embarrassed face, i guess I misunderstood what the nightlies were, all clear now. What’s the average time frame for new features being merged to the main branch?

**Comment by jonnyl2** [comment]
@poire-z, I have this book where the preset H1/H2/etc. page break style tweaks are not working. I suspect it might also have something to do with the unique id? 

Here is an example of an H1 heading: 

```html
    <p class="H1" id="_idParaDest-60"><span class="Bold"><a id="_idTextAnchor060"/>S</span><span class="Bold">ummary</span></p>
```

If I'm not mistaken and it is not the id to blame, will this also be fixed by your recent PR? Or is this a separate issue altogether? Thanks.

**Comment by poire-z** [comment]
> where the preset H1/H2/etc. page break style tweaks are not working

If you really mean "page break" and these style tweaks:
![image](https://github.com/koreader/koreader/assets/24273478/711ecb59-f3c4-4550-aac3-6aa437d241af)
these target real `<h1>` `<h2>` elements, and not `<p class="H1">` where this `"H1"` is just some litteral class name (that happens to "look" like an element name :)).
So, these won't have any effect. You'd need to use some book (or user if it's common accross books) style tweak and use `p.H1 { break-before: always !important; }`.

If you are really talking about inpage-footnote, using `p.H1 { -cr-hint: footnote-inpage }` and you have before that in a page in a book a `<a href="#_idTextAnchor060"`, so indeed targetting an inner ID that would currently be "masked" by the one in `<p id="_idParaDest-60">`, then yes, my coming up PR would fix this situation.

**Comment by jonnyl2** [comment]
Thank you; the manual tweak initialized the page breaks.

**Comment by Commodore64user** [comment]
> ![Reader_2024-02-05_232702](https://private-user-images.githubusercontent.com/97603719/304078883-45b38859-1eeb-4f03-89bd-601187512648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzMxMjAsIm5iZiI6MTcxMTk3MjgyMCwicGF0aCI6Ii85NzYwMzcxOS8zMDQwNzg4ODMtNDViMzg4NTktMWVlYi00ZjAzLTg5YmQtNjAxMTg3NTEyNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEyMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxOWQxOGU5OTg1MmRiZjFjMzc5ZTgzM2EwMTAyN2QwYTNhYzRlNWEyYWE1YzhhY2MxZDNkNjJiMmEzNTBkYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4sLBxHtrz8wQsV3bQ6qYrM11dYsSIx9AyBr14Ba9N7s)

Quick Q? @poire-z How can i make the “italian-iron” bit of text italic? Reading the book now and it is not contrasting enough. I tried adding `p.EB26… { font-style: italic; } ` but that changes the text on the glossary not on the actual text. The html for those words goes like this: `<a href=“#_doc_fragment_46_shi0006180” id=“_doc_fragment_7_gloss199” > tub</a>`

**Comment by Frenzie** [comment]
You might be able to reach them with a selector along the lines of `a[href^="#_doc_fragment"]` but I'm not entirely sure how those interact with the generated doc fragment things.

**Comment by Commodore64user** [comment]
Thank @Frenzie 👍
