### ISSUE TITLE
Artifacts on page after Menu

### ISSUE THREAD

**Issue by QuAzI** [koreader/koreader#11416]
* KOReader version: koreader-pocketbook-v2024.01
* Device: PB741 (PocketBook 740 Color)

#### Issue
Even if `Settings -> Screen -> E-ink settings -> Full refresh rate` enabled for every page and for images (always flash on pages with images) I see artifacts on manga
![image](https://github.com/koreader/koreader/assets/1897605/fee1880e-c92d-41a1-ae55-333d4a0c566b)

#### Steps to reproduce
Enable refresh at all, open any manga page (CBZ) with not white background, open Menu, close Menu

**Comment by QuAzI** [comment]
The same story when the reader opens a page first time (I can see desktop parts in the background)

**Comment by NiLuJe** [comment]
That's e-ink ghosting, nothing to do wit us, that's just how the hardware works.

**Comment by dmalinovsky** [comment]
> The same story when the reader opens a page first time (I can see desktop parts in the background)

This particular issue is fixed with https://github.com/koreader/koreader-base/pull/1752. As for the artifacts after menu, my other PR (https://github.com/koreader/koreader-base/pull/1755) should help.
