### ISSUE TITLE
Can't hide menu on the second "Menu" pressing

### ISSUE THREAD

**Issue by QuAzI** [koreader/koreader#11417]
* KOReader version: koreader-pocketbook-v2024.01
* Device: PB741 (PocketBook 740 Color)

PocketBook 740 Color has 4 buttons: "Home", "Left", "Right", "Menu".
The Menu button properly shows Koreader's menu, but I can't close it by second pressing "Menu" button (default behavior with all other software on book)
Only one way to back into reading mode - tap on the screen between the top and bottom panels
![image](https://github.com/koreader/koreader/assets/1897605/10cb4a6b-c3ef-4e04-a565-e25ded3f1dc9)

**Comment by hius07** [comment]
Another way: swipe north the upper menu.

**Comment by NiLuJe** [comment]
That's the expected behavior for devices with a menu button, IIRC (e.g., K4).

**Comment by Commodore64user** [comment]
https://github.com/koreader/koreader/blob/f8df76e5c40b491fa5f31ca2a2872218a078d52b/frontend/ui/widget/touchmenu.lua#L514

fixed by #11749
