### ISSUE TITLE
FR: [File Browser Corner Provides Refresh Button]

### ISSUE THREAD

**Issue by isPoto** [koreader/koreader#11426]
I sometimes transfer files to my device, but the KO File Browser doesn't refresh in real time!
I can only go to any folder and back to refresh the file list with the files I have just transferred.

It's a pain in the ass.

I would like to have a refresh button in the corner, which when clicked, refreshes the current file list to show the file I just transferred in.

**Comment by hius07** [comment]
It's a default action for the upper right corner long-press.
Or you can assign it to any other gesture.

**Comment by mergen3107** [comment]
I added to short diagonal swipe, so that this gesture refresh both screen and content :D
