### ISSUE TITLE
KoReader does not start anymore after update (PocketBook Color 3)

### ISSUE THREAD

**Issue by runningman84** [koreader/koreader#11428]
* KOReader version: 2024.1
* Device: PocketBook Color 3

#### Issue

First I tried to update within koreader to the latest release (from 2023.12 to 2024.1). The update was a bit strange because there was no success or error message.

After power off / power on I tried to start koreader. The app icon got highlighted but the app does not really start.

Afterwards I also tried the latest nightly release by copying all files from my pc to the device via usb.

What can I do to solve this issue?

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

there is no crash.log file.

**Comment by Frenzie** [comment]
If there's no crash.log that sounds like /system/bin/koreader.app is missing or broken.

**Comment by runningman84** [comment]
deleting all files and copying them again somehow fixed the issue, thanks for your help!
