### ISSUE TITLE
FR: Force "Flash" Screen Refresh in Android Devices

### ISSUE THREAD

**Issue by Bluemoondragon07** [koreader/koreader#11429]
So, some Android e-ink devices, such as the Meebook, don't refresh automatically in dark mode. Why? I dunno. BUT, I do know what feature would help with that!

If we could have a "screen flash" every x pages on Android--say, have the screen flash white briefly in dark mode, have it flash black in light mode--that would simulate a page refresh on most eink devices. It would also fix heavy ghosting in dark mode.

I know this is currently a feature on many non-android ereaders, such as the Kobo. However, I think it would also be a good idea to have the option to simulate this on Android as well.

**Comment by Frenzie** [comment]
I'll briefly point out that SDL uses this code for emulation.
https://github.com/koreader/koreader-base/blob/f7482e5dea67bfb8cd90abffddffc210911bb954/ffi/framebuffer_SDL2_0.lua#L143-L154

**Comment by hugleo** [comment]
ref. https://github.com/koreader/koreader/issues/11288

**Comment by pazos** [comment]
Hi. Not planned.

It should be easy to implement a proper driver for your device given somebody with that device, skills (mostly search skills, not exactly code skills) and time.

**Comment by Bluemoondragon07** [comment]
Oh. I'll just do it, then. Are there instructions for this somewhere?

**Comment by pazos** [comment]
> Oh. I'll just do it, then. Are there instructions for this somewhere?

Nope. There're a bunch of tickets scattered across https://github.com/koreader/android-luajit-launcher which show how people managed to do the same for their devices. 

That's why I mentioned the "search skills" :)

The steps required are briefly mentioned in https://github.com/koreader/android-luajit-launcher/issues/344#issuecomment-801238156
