### ISSUE TITLE
FR: kindle ambient brightness level detection may need to be adjustable

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#11431]
The Kindle:ambientBrightnessLevel (https://github.com/koreader/koreader/blob/f836f6a237b7f9ac52720cc50073c2bdfc711305/frontend/device/kindle/device.lua#L441C17-L441C39) uses constants to decide the level and is used to turn on and off the frontlight on supported models.

But recently I noticed different kindle voyage units return different values, even with the same os version. I think it may never be a problem for the native kindle software, as it won't turn off the frontlight, only adjust the brightness.
Different units may need different scales to multiply the raw value.

**Does your feature request involve difficulty completing a task? Please describe.**
It should be trivial to add a configuration or constant, but a better solution may need extra consideration.

**Describe the solution you'd like**
Simple choice is to add a scale factor, but it's definitely less user friendly.

**Describe alternatives you've considered**
A better solution would be learning the user behavior, e.g. the brightness when user decided to adjust the frontlight, but always turn on the front light if the ambient brightness dropped sharply to a low threshold.

**Additional context**
I can provide several data samples in different environments from different voyage units. I am not sure about the oasis or other models.

**Comment by Nikvothe** [comment]
I own a kindle voyage and it seems to override my selected brightness setting. I have this feature disabled in the native settings and within Koreader, but still the frontlight suddenly turns on or off depending on my surroundings. Seems to be a bug?

**Comment by pazos** [comment]
Closed by #12809
