### ISSUE TITLE
FR: Close all popups when clicking on document

### ISSUE THREAD

**Issue by Gabriel85** [koreader/koreader#11440]
If you open a (dictionary) popup and click on the background document it closes. If you open several popups and do the same only the last opened one closes. Currently there is no way to close all at once and go back to reading the document with just one (short) click.
It would be faster and more consistent when a click anywhere on the opened file in background just closes all popups at once!

**Comment by hius07** [comment]
Try long-press on the Close button.

**Comment by Gabriel85** [comment]
> Try long-press on the Close button.

Thanks, that is a neat trick! 👍

But it still would be useful to just close them all when you click on the background, since popups are opened on top of each other and it is a bit of a hassle to remember that more than one are opened. Also I think clicking on the background is a clear indication of the intention of the user to continue reading the document.

**Comment by poire-z** [comment]
I understand what you want, but you won't have it.
The "tap outside to dismiss a popup" is technically handled by each popup: each just kills itself. That's _our_ consistent behaviour: it makes sense technically, and we all are, as readers, used to that behaviour - and that behaviour makes sense in many other contexts than the dictionary lookup stack you're thinking specifically about.
The dictionary popup stack has some dedicated code to be able to close them all down, with a long-press. It may not go down to the document, if for example it was invoked from Dict lookup history.
This wouldn't easily be possible when you have mixed kind of popup stacked.

> Plus those pop-ups behave like windows on every OS. Therefore clicking on a window on the background should bring it into the foreground immediately.

They don't. We're not like every OS :) we're not even an OS, we're an app that just has a stack, we don't/can't move widgets across the stack to the foreground or backgrounds, we just open and close at the top.

**Comment by Gabriel85** [comment]
> I understand what you want, but you won't have it. The "tap outside to dismiss a popup" is technically handled by each popup: each just kills itself. That's _our_ consistent behaviour: it makes sense technically, and we all are, as readers, used to that behaviour - and that behaviour makes sense in many other contexts than the dictionary lookup stack you're thinking specifically about. The dictionary popup stack has some dedicated code to be able to close them all down, with a long-press. It may not go down to the document, if for example it was invoked from Dict lookup history. This wouldn't easily be possible when you have mixed kind of popup stacked.

OK, thanks for the explanation! So there is no way to just close everything? I mean I love KOReader for the tons of features, but sometimes it can be counter intuitive. If I haven't used it for a couple of months it is every time a bit of a steep learning curve.
Or would it be possible to have an option that every new popup, just kills the old one? I don't really need more than one at a time. 
And what about just stacking them (like Windows 3.1 did it)? So you can easily switch between them and and see immediately how many popups are open. Maybe it is already possible, but I can't find the option..

> They don't. We're not like every OS :) we're not even an OS, we're an app that just has a stack, we don't/can't move widgets across the stack to the foreground or backgrounds, we just open and close at the top.

Well I would say it is pretty much like an OS, at least on non-Android devices! And even on Android all other apps I use are just for administration of the device. And the amount of skill somebody needs to fully understand and make use of KOReader are comparable...

**Comment by hius07** [comment]
We can modify the Close button text to, say, `Close(3)` when more than one popups are opened.

**Comment by hius07** [comment]
I mean a number of the upper window within the Close button. Some kind of invitation for long-pressing.

![1](https://github.com/koreader/koreader/assets/62179190/900b8d1b-fb0c-4939-ad3a-3e933bfcb774)

**Comment by Gabriel85** [comment]
> I mean a number of the upper window within the Close button. Some kind of invitation for long-pressing.

Any indication would be nice! Doesn't need to be a number, some sort of double X or a very bold X already would be enough. 👍
Then people could know there more than one popup and maybe they figure out themselves that they can longpress it to close them all.

**Comment by Frenzie** [comment]
> I mean a number of the upper window within the Close button. Some kind of invitation for long-pressing.

I'm not a fan; maybe if it was in the titlebar it wouldn't look so busy.

**Comment by poire-z** [comment]
Not a fan either.

> a very bold X already would be enough

Enough, and probably the less bothering/distracting indication for most people who didn't really care about knowing that previously.

**Comment by Gabriel85** [comment]
> Not a fan either.
> 
> > a very bold X already would be enough
> 
> Enough, and probably the less bothering/distracting indication for most people who didn't really care about knowing that previously.

I made some mockups for a double X icon, but they look a bit weird if the icon has only one color. I guess a  clearly bold X would be the easiest, although it would not be as self explanatory.
