### ISSUE TITLE
koreader crash

### ISSUE THREAD

**Issue by crucco37** [koreader/koreader#11441]
* KOReader version: 2024.01
* Device: Motorola Moto g82 5G
[240205_koreadercrash.txt](https://github.com/koreader/koreader/files/14167800/240205_koreadercrash.txt)

#### Issue
it crashes after last update

#### Steps to reproduce
it crashes and crashes and won't start

##### `crash.log` (if applicable) attached
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

**Comment by NiLuJe** [comment]
If that's an f-droid build, try an uninstall and a reinstall.

**Comment by runejuhl** [comment]
Had the same issue with koreader from f-droid. Uninstall and reinstall worked for me, FWIW.

**Comment by kolAflash** [comment]
See also: https://github.com/koreader/koreader/issues/11399 _Latest KOReader from F-Droid crashes on startup_
