### ISSUE TITLE
Failure to connect to Calibre Content Library.

### ISSUE THREAD

**Issue by Farsuperslime** [koreader/koreader#11450]
* KOReader version: 2024.01
* Device: Kobo Clara

#### Issue
When attempting to add a Calibre content library to app and connect to it, the button turns black and then does nothing.

#### Steps to reproduce
Add the address to a Calibre content library and attempt to connect to it.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/14204990/crash.log)

**Comment by pazos** [comment]
https://github.com/koreader/koreader/wiki/OPDS-support

**Comment by Farsuperslime** [comment]
I attempted following that guide, but my app does not look at all like the photos and does not have the "Local Calibre Library" option.

**Comment by hius07** [comment]
Just create a new catalog, with your details in catalog url, smth like:
http://192.168.1.1:8080/opds

**Comment by Farsuperslime** [comment]
This helped thank you! It turns out I needed to add the "/opds" to the URL and it works no issue now.
