### ISSUE TITLE
FR: Perform selective search on a specific chapter of a book

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11454]
**Does your feature request involve difficulty completing a task? Please describe.**

Currently reading a copy of 'A Clockwork Orange' which contains a Nadsat glossary at the end. I know the author intended for you to figure stuff out from context but sometimes I really can't figure out what some slang words mean and so try to perform a text search (to get to the glossary, as the words are not linked to it), but I can't easily reach the one used in the glossary as using the 'last instance' doesn't necessarily take you to the glossary and one word might be used multiple times so not easy to find the one I want (adding book map for clarification).
<img src="https://github.com/koreader/koreader/assets/97603719/93d76f60-e821-4398-bf90-0c2fe0edae92" width=40% height=40%>

**Describe the solution you'd like**
An option to limit the scope of a search, kindle stock fw allows you to do a system wide search or book only, I would like koreader to sort of do the same but with the option to pin point a search result to a specific chapter or chapters. So in this example, to perform the search only on the 'Nadsat chapter'.
Also, when performing a search, it would be useful to know how many matches were found (1 of 10 matches, for instance) and maybe show a list with the results.

**Describe alternatives you've considered**
I have added a bookmark to the glossary and usually go manually looking for the word, but that takes extra time.

**Additional context**
I know this is probably a bit niche, but it might help someone in the future.

**Comment by hius07** [comment]
Can you try the recent nightly build. It has "Find all" button, to show search results in the whole book.
It cannot be limited to a chapter or to a range of pages though. Maybe an idea for further development.

**Comment by Commodore64user** [comment]
How do i install the nightly?

> Maybe an idea for further development.

certainly. I know I won’t see it before finishing my book, but future readers still can benefit from it.

**Comment by hius07** [comment]
> How do i install the nightly?

https://build.koreader.rocks/download/nightly/

**Comment by Commodore64user** [comment]
okay, so I have been testing it on 2024.01-63 and the fullSearch works a lot better now. kudos to you.

I did notice that when you look at the results list, and go to the one you are interested in, when you swipe left (or right?) to go back to your last read location (where you left off, started the search) it doesn't do the blinky thing where it hints at the line you were in. 

Also, I have the "Dictionary on single word selection" active, I think it would perhaps be a better idea to have the "fullSearch" as the option for 'search' in the dictionary pop-up when you do a word selection. Currently to start a fullSearch it takes this many steps, 1) select word, 2) press search in pop-up, 3) select magnifying glass, 4) make adjustments (if any needed), 5) press All. 
Or maybe (this is quite a stretch though), the buttons for << and >> could be shrunk by half, therefore making space for one more option. Ok, maybe not that one.

**Comment by poire-z** [comment]
> when you swipe left (or right?) to go back to your last read location (where you left off, started the search) it doesn't do the blinky thing where it hints at the line you were in.

That happens when you follow a link, when there is actually a specific line we can go to (the line with that link).
If you do a search and jump from that list, there is just a page to go back to, no specific line (that is, until we hack your camera and implement some AI that can follow your eyes movements and guess which line you were in - not coming soon :))

> Or maybe (this is quite a stretch though), the buttons for << and >> could be shrunk by half, therefore making space for one more option. Ok, maybe not that one.

Some ideas have been discussed in the PR, ie. around https://github.com/koreader/koreader/pull/11313#issuecomment-1879254906

**Comment by Commodore64user** [comment]
> If you do a search and jump from that list, there is just a page to go back to, no specific line

But it could do the blinky thing to the line with the word you started the selection from, no?

**Comment by poire-z** [comment]
Ah, maybe, but that's a bit remote, there's some travelling from the dict lookup to doing a search to showing results to selecting one to jump to a page, and a state to pass all along that - a link jump is more direct, so easy.

**Comment by hius07** [comment]
If we have the "find All" button in DQL (or maybe long-press on "Search"), it would be easier, `self.selected_text` would be intact (didn't check, just guess).

**Comment by Commodore64user** [comment]
> Ah, maybe, but that's a bit remote, there's some travelling from the dict lookup to doing a search to showing results to selecting one to jump to a page, and a state to pass all along that - a link jump is more direct, so easy.

All the more reason to have it as default when starting a search query.

**Comment by Commodore64user** [comment]
Another book that would benefit from this: Dune.

**Comment by Commodore64user** [comment]
When you do a dictionary look-up, you get the dict pop up which contains two ways of closing the window. One the X at the top-right of the window, and a “close” button at the bottom-left, is there any difference between them? Could the “close” be re-assigned to “find all” so you no longer have to go through the 25 steps one currently has to go through with the nightly?

**Comment by Commodore64user** [comment]
Hey @poire-z, going through some old threads i found this: [https://github.com/koreader/koreader/issues/10658#issuecomment-1627041186](url)

could i use something similar to get “find all” replacing the “close” button (see previous comment), should i wait until this makes it to a stable release? If safe doing now, what would i need to replace in that code block?

btw, how is that AI tracking you promised coming along? 😅

**Comment by poire-z** [comment]
> should i wait until this makes it to a stable release? 

Probably not - it hasn't been discussed, and I'm rather against being bothered by a Find all in my dict lookup. At most, it could be a non intrusive long-press on Search.

> could i use something similar to get “find all” replacing the “close” button (see previous comment), 

Sure :) for stuff that is rather specific to you and your use case, and you'd rather not be involved in a discussion war :) a user-patch is perfect for that, when it's possible to make on, and it seems it is:

You could try:
```lua
local DictQuickLookup = require("ui/widget/dictquicklookup")
local _ = require("gettext")

local DictQuickLookup_init_orig = DictQuickLookup.init
DictQuickLookup.init = function(self)
    -- The Vocabulary builder plugin may have plugged such a function if enabled
    local orig_tweak_buttons_func = self.tweak_buttons_func
    -- Replace it with ours
    self.tweak_buttons_func = function(obj, buttons)
        -- Let original tweak func add buttons
        if orig_tweak_buttons_func then
            orig_tweak_buttons_func(obj, buttons)
        end
        -- And do our tweaks
        local close_button
        for i, row in ipairs(buttons) do
            for j, button in ipairs(row) do
                if button.id == "close" then
                    close_button = button
                    break
                end
            end
        end
        if close_button then
            close_button.text = _("Find owl")
            close_button.callback = function()
                -- Hackathon !
                obj.dialog.search.last_search_text = obj.word
                obj.dialog.search:findAllText(obj.word)
                obj:onClose()
            end
        end
    end
    DictQuickLookup_init_orig(self)
end
```

> btw, how is that AI tracking you promised coming along? 

Dunno/don't remember what you're talking about. I may have joked about AI in a few places, but not sure how funny I was :/

**Comment by Commodore64user** [comment]
find owl??? really? it made me chuckle though. It works (maniacal laugh, maniacal laugh, lighting and thunder, maniacal laugh). Thank you!

I am happy to discuss this here, but nobody seems to want to discuss it with me so...

regarding the AI, there it is
> That happens when you follow a link, when there is actually a specific line we can go to (the line with that link).
> If you do a search and jump from that list, there is just a page to go back to, no specific line (that is, until we hack your camera and implement some AI that can follow your eyes movements and guess which line you were in - not coming soon :))

I still think it would be helpful to do the Blinky thing after the "find owl", and we don't need AI for that because I am telling the software where I was by selecting the word for the owl to find.

**Comment by Commodore64user** [comment]
![Reader_2024-03-01_000644](https://github.com/koreader/koreader/assets/97603719/02c3511f-567c-4872-ab2b-77886205c9c0)
 
is it possible to have another patch for "find owl" in this menu? possibly next to 'Search' instead of hijacking anything, and if that is not possible maybe hijack "highlights"?, I mean I already highlight by default any multiple word selection so that button is kinda redundant.

another question regarding patches, what is the deal with updates? do they survive them fine or is there something I need to do after every update to get them back?

**Comment by poire-z** [comment]
> is it possible to have another patch for "find owl" in this menu? 

Probably possible, but not keen on spending time doing it.
May be @hius07 can add a hold_callback (for long-press) on the 2 <kbd>Search</kbd> buttons to launch his find all stuff?

> another question regarding patches, what is the deal with updates? do they survive them fine or is there something I need to do after every update to get them back?

They survive, they are not replaced. They are supposed to "monkey patch" existing code, so as long at we don't tweak too much the code they want to hack, they will keep working. And the day they don't apply, one needs to see what changed and adapt them to the new situation.

> I am happy to discuss this here, but nobody seems to want to discuss it with me so...

That's how we do our wars around here. It's nerve wracking, but causes no casualties :)

**Comment by Commodore64user** [comment]
> Probably possible, but not keen on spending time doing it.

fair enough, i didn't even want it the first place ;), joke aside, no worries man! 

> That's how we do our wars around here. It's nerve wracking, but causes no casualties :)

In that case, I am going to keep talking about this wonderful feature.

Now I was thinking on the implementation of the original idea, if anyone is still interested in working on it, and the best implemantion I can think of would be similar to how "custom hidden flows" work. You go to the book map and page browser and do the long press on the page and it shows you three options, `1) toggle page bookmark, 2) start hidden flow here and 3) start selective search here`, then you would get `end selective text here` and you could do that multiple times should the user wish to have multiple, non-consecutive chapters or whatever. 

Then when you are reading and go to "findAll", it would have a third tick-box on the prompt: `1) case sensitive, 2) regular expression, 3) selective search`. that last option could be greyed out if the user hasn't made a selection (see previous paragraph) or would simply work as a full text search until a selection is made. It would also be helpful for the tick to remain in that state, for people who might be using a "find owl" button (as that skips the prompt and jumps straight to the results)

**Comment by poire-z** [comment]
IMHO, this selective search is overkill, it's not needed (even if _you_ need it) for the little ebook reader this is, it's not worth having this edge feature leak into bookmap/pagebrowser (and I'm not interested in implementing it).

**Comment by Commodore64user** [comment]
> IMHO, this selective search is overkill, it's not needed (even if _you_ need it) for the little ebook reader this is, it's not worth having this edge feature leak into bookmap/pagebrowser (and I'm not interested in implementing it).

I disagree, omnibuses are another example of when this would be useful. You might have 5 books in one and perhaps don’t want spoilers from the other books, just because it would not be useful to you, it does not mean it wouldn’t be useful to other users.

as for you not wanting to implement it, fair enough. I am just proposing an idea, maybe some one else does want to do it.

**Comment by poire-z** [comment]
I know you disagree as you opened this FR :) I'm just adding and explaining a vote for "we don't need it".

There are lots of "user problems" that don't need a technical solution from us:
- your omnibus search: well, just figure the min and max page numbers, and visually ignore the others :)
- somebody reading a PDF with german text on the left page and english on the right page could indeed find it useful to have search working only on even, or only on odd pages - to not get false positive easy to get with the other language.
- somebody having such a PDF could also ask us to have a feature to skip odd or even pages when turning pages, because it's painful tapping twice, and the code probably could do that :)

What you're requesting in your latest suggestion is somehow to be able to set "search hidden flows".
So, my possibly only acceptable solution would be to not add another set of "hidden flows" useful only for search - but just use the existing "hidden flows", and a checkbox in Search to limit results to those in hidden flows. No added UI kludge or page selections business, just some little filtering at the tail end before displaying results.
It's possible you would already have set these hidden flows when reading that omnibus book, so benefit from them. Others who have no need for hidden flows for page left to read and stats could then use them just for search.

**Comment by Commodore64user** [comment]
@poire-z I don't disagree because I opened it, I am happy to be told that my idea is not as good as I might think it is, so long as it is based on valid arguments. But saying something is not needed because you won't use it, does not constitute (in my book at least, pardon the pun) a valid reason or argument.

I disagree because I actually think it would be useful to someone, and I include myself there and the person reading the German pdf. Now, I am only proposing or selling you (all developers) on the idea, I don't know if that is the best way of implementing it, I only thought about what already exist and tried to build it on top of that. 

> What you're requesting in your latest suggestion is somehow to be able to set "search hidden flows".

First of all, I am proposing an idea. And what I said was to activate the searchable area, like one does in hidden flows. But again, like I said before, it might not be the best way, I am just trying to build on what is already out there, to make easier. 

> That's how we do our wars around here. It's nerve wracking, but causes no casualties :)

I am just doing exactly what you said, trying to get some traction here.

**Comment by Commodore64user** [comment]
> There are lots of "user problems" that don't need a technical solution from us:

the more I think about this response, the more I realise how shortsighted it is. thing is, everything is technically a "user problem". to read a book, all you need is the text, everything else around it, is superfluous, a user improvement. For example, if you remember the movie the devil wears Prada, the twins get a copy of the unreleased Harry Potter manuscript and read on the train. on A4 paper, nothing else, it doesn't even need to be bound together because that is all you need, the text (although in the movie it is bound together). But enough of romantic comedies.

your example, particularly the second one, which I must admit I had not considered, are perfectly valid reason to make it available, remember everything besides displaying the main text is technically superfluous.

> What you're requesting in your latest suggestion is somehow to be able to set "search hidden flows".

what I had originally said was it could work "like" hidden flows. but...

> So, my possibly only acceptable solution would be to not add another set of "hidden flows" useful only for search - but just use the existing "hidden flows", and a checkbox in Search to limit results to those in hidden flows. 

I thought about this, and this could work. I tried to do something (and failed miserably) but made and important discovery. Use the book map at the top for reference, I tried to split the second block (i.e starts at notes end at end of book) of hidden flows into 3 (that is: one for notes, one for **Nadsat glossary**, and one for the rest), and this is where I failed because currently, you can't have multiple non-consecutive hidden flows. But if you could, one could easily filter to show the results from that one particular hidden flow(s), which in this case would be `[x-y]3`.

**Comment by poire-z** [comment]
> your example, particularly the second one, which I must admit I had not considered, are perfectly valid reason to make _it_ available, remember everything besides displaying the main text is technically superfluous.

To make _what_ available ? How would we allow a user to tell us to not show search results from odd pages? Some AI "show us what you want on a few pages, and we will figure out what you really want"? Some "input in this text box some Lua function returning the page numbers you want to hide" ?
This is a limited user problem we don't need to provide a (obviously complex) solution for. There are other problems you don't have because we did provide a solution because we found an easy and elegant one :)

You can have problems, and you can think of ideas for solutions. But we (developpers, long-time users) may have some thoughts about how complicated or twisted it could be as a UX, and as its implementation, and how maintanable it is (depending on the code it spans, it can become nightmarish), and we can decide what feels alright to go in or not, in the hope of keeping the already complex KOReader kinda intuitive. If some feature solving one or two user problems require visible menu items and popups that will go in the way of normal users and will look odd and _wtf?!_ and are clumsily usable or make no real sense, we can decide it's not "a user problem worth needing solving from us".
(And if Little Timmy shall die on this hill, so be it :))

> what I had originally said was it could work "like" hidden flows. but...

Yes, we can talk, and discuss, until we maybe find a common ground that only solve "half" of your user problem, without being too clumsy/intrusive in the code and the UX.

> I tried to split the second block (i.e starts at notes end at end of book) of hidden flows into 3 (that is: one for notes, one for Nadsat glossary, and one for the rest), and this is where I failed because currently, you can't have multiple non-consecutive hidden flows.

An exemple of intuitiveness: you indeed can't, consecutive flows are auto-merged, because that's what one expects when making/fixing them - otherwise it would be a mess with many other needed menu items, like: merge, unmerge, start hidden flow, end hidden flow, start regular flow... instead of the 2 "Start hidden flow" and "Restart regular flow" we have), and a need to show boundaries in Bookmap...). There is currently no real and practical need (until we have your search in individual flows, which we may not) to have consecutive individual flows. (and if some unpractical person really wants to see that some stuff is in flow no2 or flow no3, well, join Little Timmy, it's not worh the added complexity elsewhere).
Solution for a user needing that on some rare books where it may feel needed: let a blank page (or the last page of the first flow) be out of that hidden flow and in the normal flow, so you can get 2 non-consecutive hidden flows.

> But if you could, one could easily filter to show the results from that one particular hidden flow(s), which in this case would be [x-y]3.

Not sure how necessary it is to provide search in individual hidden flows - but anyway, if we were to have that (or even just regular/hidden), it would better and simpler be indeed at the tail end of the process, "filtering" (as you write) (after seeing them all) the displayed results (like we allow for example filtering History to show finished or reading books). We don't need (or "I don't want") a user to be bothered with "where do you want to search" when making the search, or have a global option for where to next search - and having to handle that in all the code that does the search. And so, this won't solve your "spoiler" point ("I don't want to see results from other sections"), but I guess you could compromise on that :)

**Comment by Commodore64user** [comment]
> To make _what_ available ? How would we allow a user to tell us to not show search results from odd pages? Some AI "show us what you want on a few pages, and we will figure out what you really want"? Some "input in this text box some Lua function returning the page numbers you want to hide" ?
> This is a limited user problem we don't need to provide a (obviously complex) solution for. There are other problems you don't have because we did provide a solution because we found an easy and elegant one :)

I was only messing with you on that one, relax, I don't actually think having a feature that ignores German pages is necessary. 

> You can have problems, and you can think of ideas for solutions. But we (developpers, long-time users) may have some thoughts about how complicated or twisted it could be as a UX, and as its implementation, and how maintanable it is (depending on the code it spans, it can become nightmarish), and we can decide what feels alright to go in or not, in the hope of keeping the already complex KOReader kinda intuitive.

this is totally fair, and I am open to be told something is too complicated and so forth. I am not a developer so can only speak from a user perspective, so please have some patience.

> (And if Little Timmy shall die on this hill, so be it :))

How dare you? don't bring Little Timmy into this, this is way to advanced for him. He's only concerned about the marker indicator (at the moment).

Anyway back to business...

> Solution for a user needing that on some rare books where it may feel needed: let a blank page (or the last page of the first flow) be out of that hidden flow and in the normal flow, so you can get 2 non-consecutive hidden flows.

this is what I was thinking too, I was also wondering if one could "make" appear a blank page with some sort of style tweak magic, I mean, if one can make them disappear, could not one make them appear somewhere too?

> it would better and simpler be indeed at the tail end of the process, "filtering" (as you write) (after seeing them all) the displayed results (like we allow for example filtering History to show finished or reading books)

that seems reasonable. I think that is quite along the lines of what I was describing, you fetch all the results, but only show me the ones that I want from this "hidden flow", or better yet, show me all the results but put the ones you find in this "hidden flow" right at the top of the queue. so if I have three matches and the one I want is the second one, the result would look like this: 

2nd match
--------
1st match
2nd match
3rd match

**Comment by poire-z** [comment]
> don't bring Little Timmy into this, this is way to advanced for him

How condescending of you! Little Timmy is actually clearer, simpler and intuitive with what he wants.

> I was also wondering if one could "make" appear a blank page with some sort of style tweak magic, I mean, if one can make them disappear, could not one make them appear somewhere too?

Depends on the elements at boundaries. If you want a blank page at start of a DocFragment (which all already have one), and as margins collapse, and so do `break-before`s, you need to give a bit of consistency to one, here with a padding-top, so they are no longer consecutive-(x)-margins and don't collapse, and both `break-before: always` are applied.

```css
DocFragment[id=_doc_fragment_14] { padding-top: 1px; }
DocFragment[id=_doc_fragment_14] > body { break-before: always; }
```
(Select text spanning the 2 pages you want to double-break, View HTML, long-press on the `<DocFragment>`, tap the button with stuff similar to `DocFragment[id=_doc_fragment_14]` to copy it in the clipboard, and then back to Book style tweak editor.)

(You could actually do that the other way around, with the previous `DocFragment`, `padding-bottom` and `break-after: always` I think.)

(x): the world is full of consective merging stuff: hidden flows, margins... Little Timmy finds all this amazing everytime.
