### ISSUE TITLE
Custom metadata is not reflected in the Alt Status Bar

### ISSUE THREAD

**Issue by christian-ho** [koreader/koreader#11461]
#### Issue
If you change for example the title of the book on the book information page, this is displayed correctly in the lower status bar. However, the old title is still displayed in the alt status bar on the top

Is there anything that can be done?

![image](https://github.com/koreader/koreader/assets/57492542/48bd7af6-fe18-4b2d-962b-2cc5917b74f6)

**Comment by poire-z** [comment]
I don't really care about the top status bar (which is evil, ugly, and managed by crengine), but if @hius07 is willing to plug some stuff in the places he knows, we could update the metadata internal to crengine with:
```diff
--- a/cre.cpp
+++ b/cre.cpp
@@ -818,2 +818,10 @@ static int getDocumentProps(lua_State *L) {

+static int overrideDocumentProp(lua_State *L) {
+    CreDocument *doc = (CreDocument*) luaL_checkudata(L, 1, "credocument");
+    const char *prop = luaL_checkstring(L, 2);
+    const char *value = luaL_checkstring(L, 3);
+    doc->text_view->getDocProps()->setString(prop, value);
+    return 0;
+}
+
 static int getDocumentRenderingHash(lua_State *L) {
@@ -4056,2 +4080,3 @@ static const struct luaL_Reg credocument_meth[] = {
     {"getDocumentProps", getDocumentProps},
+    {"overrideDocumentProp", overrideDocumentProp},
     {"getDocumentRenderingHash", getDocumentRenderingHash},
```

```diff
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua
@@ -471,2 +471,3 @@ function ReaderUI:init()
     self.doc_props = FileManagerBookInfo.extendProps(props, self.document.file)
+    self.document._document:overrideDocumentProp("doc.authors", "Foo G. Bar")

```
and get crengine to use that:
![image](https://github.com/koreader/koreader/assets/24273478/064a245e-d12c-4645-acf7-3515fa63cfd1)

The strings to provide as key are at:
https://github.com/koreader/crengine/blob/b5f97c4560ddb9d1ddfad20c858c997045a89649/crengine/include/lvtinydom.h#L91-L110
(Dunno which of them crengine can use for which purpose, and if stuff other than authors and title, like keywords, description, coverfile, get displayed anywhere.)

**Comment by hius07** [comment]
Yes, I think we should do it, alt bar is still popular.
