### ISSUE TITLE
Enhancement request: splitting long titles on more lines

### ISSUE THREAD

**Issue by gegamit** [koreader/koreader#1147]
Could it be possible to give the choice to split long book titles on more lines? 
Thank you and regards!

**Comment by gegamit** [comment]
Do you plan to introduce this feature? 
I use kobo also for reading papers that often have very long and similar titles. 
I reduce for this reason the font size of the file manager (see #1345) by modifying a configuration file.

**Comment by robert00s** [comment]
What do you think about adding full filename in properties of selected item in file manager?
To see the full name of file simply long press on the item in FM.

Long file name:
![1](https://cloud.githubusercontent.com/assets/22982594/20970085/2ebdfa9c-bc8c-11e6-83cc-8dc05739972b.png)
short file name:
![2](https://cloud.githubusercontent.com/assets/22982594/20970096/35c90c00-bc8c-11e6-877b-509a5859902c.png)

**Comment by houqp** [comment]
@robert00s what you have is definitely a good addition to the filemanager menu.

**Comment by robert00s** [comment]
@houqp 
I think we can close that task.
