### ISSUE TITLE
OTA is only working with HTTPS on Tolino Android 4.4 devices

### ISSUE THREAD

**Issue by Gabriel85** [koreader/koreader#11470]
* KOReader version: 2024.1
* Device: Tolino Android 4.4

#### Issue
OTA fails with Tolino Android 4.4 devices with all servers, despite good internet connection and other online functions working (e.g. Wikipedia and dictionary download). The local file gets created, but is empty and the sever can be pinged from the device. This is a long term issue (> 2 years). It works on my phone without problems.

EDIT: it works when I change the OTA-server from HTTP to HTTPS for some unknown reason.

#### Log
```
V/KOReader(10591): downloading update file http://ota.koreader.rocks/koreader-android-latest-stableˋ
W/KOReader(10591): cannot find update file: timeout
V/KOReader(10591): Response headers: nil
```

**Comment by hasezoey** [comment]
because i also have a tolino device, let me ask which model and if you have enough storage space on the system partition (or is koreader apk downloaded to the data partition)?
i ask because on my tolino vision 5 (with stock layout), i have less than 100mb after installing & opening koreader on the system partition, which is not enough for tolino's own firmware updates

**Comment by Gabriel85** [comment]
> because i also have a tolino device, let me ask which model and if you have enough storage space on the system partition (or is koreader apk downloaded to the data partition)? i ask because on my tolino vision 5 (with stock layout), i have less than 100mb after installing & opening koreader on the system partition, which is not enough for tolino's own firmware updates

No it is not a space problem!

I tested it on a Epos 2 and Shine 3 (both from the same generation). Yes, there is plenty of space (213MB on the system partition, >2GB on the data partition). But this file gets created in the usual Koreader directory and it is only the text file with the latest Koreader version. It is supposed to be 33 BYTES!

Therefore it is probably related to the connection. Maybe it is a problem with LuaSocket or with the HTTP request? I increased the time-out, but it didn't change anything.

**Comment by pazos** [comment]
> Maybe it is a problem with LuaSocket or with the HTTP request? I increased the time-out, but it didn't change anything.

Not at all.

Tolinos are known for having the DownloadManager broken, at least some of them. In those instances the users see a warning "Unable to download: retry using the browser?"

But, a few months (years?) ago somebody reported the tolino browser is now also unable to download APKs.

So, whatever it is, it's most likely non fixable. OTAs working fine on 99'9999% of android devices is kind of a proof of that :)

Two workarounds come to my mind:

a) switch to FDroid flavor (if you're not using any kind of userpatches)
b) install a proper browser and disable the one bundled with the os (this will only work if the DownloadManager succeds to report its error, which was the case when the "download in browser" workaround was implemented.

**Comment by Gabriel85** [comment]
> Tolinos are known for having the DownloadManager broken, at least some of them. In those instances the users see a warning "Unable to download: retry using the browser?"
> 
> But, a few months (years?) ago somebody reported the tolino browser is now also unable to download APKs.

Yes, the DownloadManager is indeed broken, and I disabled it completely because of that. But what has that to do with Koreader? And my main question is why does the other download stuff work then? The problem doesn't even seem to be the download of the actual update, the problem is (so far) the download of the text file which tells Koreader what the latest version is.
 
> So, whatever it is, it's most likely non fixable. OTAs working fine on 99'9999% of android devices is kind of a proof of that :)

I am pretty sure it is fixable (somehow), but I guess I have to look into it myself. Other users report similar obscure problems with Lua on older Android versions.

> Two workarounds come to my mind:
> 
> a) switch to FDroid flavor (if you're not using any kind of userpatches) b) install a proper browser and disable the one bundled with the os (this will only work if the DownloadManager succeds to report its error, which was the case when the "download in browser" workaround was implemented.

I was using the FDroid version, but by now I use many userpatches and FDroid has become practically useless on such old Android versions and on slow devices. And other browsers have the same DownloadManager problems and there haven't been any modern ones for Kitkat in years. The build-in Webkit is also so outdated by now that you can''t hardly open any website with them. Those ancient "Android" devices are still great for Koreader and very simple or old apps, but not for anything else.

**Comment by Gabriel85** [comment]
I have already fixed it! It had indeed nothing to do with the DownloadManager. Well it turned out that it works if I change the OTA server to HTTPS. I am not sure if that is a general problem or just related to the OTA-servers. Does anybody have an idea why this weird behaviour occurs?

But sadly I also have the bad Tolino DownloadManager you warned me about, which prevents the download of the actual APK by KOReader.

@pazos Why is the Android DownloadManager only used to download APKs and not for downloading anything else? I see no technical reason why they can't also be downloaded by LuaSockets like all other files? That would allow OTA-updates even on Tolino devices.

But there is a workaround for that:
1. install "Download Navi" from FDroid (it can handle download links and is totally independent of the crippled Tolino DownloadManager)
2. start the OTA-update and press "Retry"
3. Download the APK to "/sdcard1/Android/data/org.koreader.launcher/files"
4. wait a couple of seconds until the APK is downloaded and start the OTA-update again
5. KOReader will install the APK automatically

@hasezoey KOReader doesn't download the APK to the system partition. It downloads it the the folder mentioned above.

**Comment by pazos** [comment]
> @pazos Why is the Android DownloadManager only used to download APKs and not for downloading anything else? 

It is part of  platform code, not frontend/common code: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/ApkUpdater.kt

> I see no technical reason why they can't also be downloaded by LuaSockets like all other files? That would allow OTA-updates even on Tolino devices.

I don't want to screw a perfectly fine working solution just because a certain branch releases broken software. If you want it so badly and no workaround is enough then do it properly: reimplement a DownloadManager within the JVM in kotlin an use that.

**Comment by pazos** [comment]
> I have already fixed it! It had indeed nothing to do with the DownloadManager. Well it turned out that it works if I change the OTA server to HTTPS. I am not sure if that is a general problem or just related to the OTA-servers. Does anybody have an idea why this weird behaviour occurs?

> But sadly I also have the bad Tolino DownloadManager you warned me about, which prevents the download of the actual APK by KOReader.

LOL

**Comment by Gabriel85** [comment]
> > I have already fixed it! It had indeed nothing to do with the DownloadManager. Well it turned out that it works if I change the OTA server to HTTPS. I am not sure if that is a general problem or just related to the OTA-servers. Does anybody have an idea why this weird behaviour occurs?
> 
> > But sadly I also have the bad Tolino DownloadManager you warned me about, which prevents the download of the actual APK by KOReader.
> 
> LOL

This is not the same issue! They certainly have nothing to do with each other. The DownloadManager is only involved with downloading the APK, but my original bug (why I opened this) was, it not being able to download the "koreader-android-latest-stable" text file by LuaSockets.

> I don't want to screw a perfectly fine working solution just because a certain branch releases broken software.
> If you want it so badly and no workaround is enough then do it properly: reimplement a DownloadManager within the JVM in kotlin and use that.
> 
> If you go that route please keep the spec as is:
> 
> * It downloads in the background
> * It puts files in the app cache dir
> * It notifies on completion (or on error)
> * It handles android activity lifecycle changes.
> 
> Some things won't be possible (ie: download in the background without a system notification) but I will be fine with this if the rest work as is.

Why does it need to be in Kotlin? And why didn't you just use LuaSockets like EVERY other of the countless downloads of all kind of files in the app and its plugins?

And at least on my device it is saved in the data-folder in /sdcard and not in the cache.

I tried to rewrite it in Lua with a userpatch, but for some reason the whole app crashes, if I try to overwrite any function related to OTA. Maybe I set up build environment later and write a proper patch.

**Comment by Frenzie** [comment]
> I have already fixed it! It had indeed nothing to do with the DownloadManager. Well it turned out that it works if I change the OTA server to HTTPS. I am not sure if that is a general problem or just related to the OTA-servers. Does anybody have an idea why this weird behaviour occurs?

Perhaps that suggests local blocking of some sort? HTTPS requires more working parts to function so in principle it's more fragile.

**Comment by pazos** [comment]
> Why does it need to be in Kotlin? 

Because the rest of https://github.com/koreader/android-luajit-launcher/tree/master is written in Kotlin and C/C++. And using C/C++ is not a really good option unless there're no alternatives. That's not the case here, just use AsyncTask and reimplement a generic downloader that just uses DownloadManager on every device and fallbacks to the AsyncTask for tolinos.

> And why didn't you just use LuaSockets like EVERY other of the countless downloads of all kind of files in the app and its plugins?

I could repeat myself ad infinitum. I won't. My previous post has the specs and the only reliable way of getting to them is to write some native code (we do the same in other parts of the codebase, where android has its own implementation and the frontend just calls a  wrapper that invokes native functions)

 Any changes that make the APK update as part of the frontend code (ie: not coding running within the JVM) is a bad idea and **shall not be merged**

**Comment by Gabriel85** [comment]
> > I have already fixed it! It had indeed nothing to do with the DownloadManager. Well it turned out that it works if I change the OTA server to HTTPS. I am not sure if that is a general problem or just related to the OTA-servers. Does anybody have an idea why this weird behaviour occurs?
> 
> Perhaps that suggests local blocking of some sort? HTTPS requires more working parts to function so in principle it's more fragile.

No, there is no local blocking here, HTTP connections work perfectly fine in other apps. It seems Koreader almost everywhere uses HTTPS so I am not sure if that is an freak issue with all HTTP connection and LuaSocket on my device. I only found it out while debugging. I could not get any connection until I put in just some random URL, which turned out to be an HTTPS one...
But HTTPS is preferred anyways, so I probably won't bother with it anymore.

By the way, there are still a few scattered hardcoded HTTP URLs in KOReader and its plugins, except in OTA. I guess they also should be changed to HTTPS as best practice.
But at the same time there should be some fallback to HTTP,  since there are maybe some old devices around which struggle with HTTPS nowadays. Plus certain HTTPS connections probably are blocked in some countries (e.g. Wikipedia).

> Because the rest of https://github.com/koreader/android-luajit-launcher/tree/master is written in Kotlin and C/C++. And using C/C++ is not a really good option unless there're no alternatives. That's not the case here, just use AsyncTask and reimplement a generic downloader that just uses DownloadManager on every device and fallbacks to the AsyncTask for tolinos.

My point is that there is most likely no need of special (and device-dependent) code for Android just for the mundane task of downloading an APK-file. All other downloads in KOReader seem to handled by LuaSocket on ALL devices in ALL instances. 

> I could repeat myself ad infinitum. I won't. My previous post has the specs and the only reliable way of getting to them is to write some native code (we do the same in other parts of the codebase, where android has its own implementation and the frontend just calls a wrapper that invokes native functions)
> 
> Any changes that make the APK update as part of the frontend code (ie: not code running within the JVM) is a bad idea and **shall not be merged**

I have no doubt that there are many valid reasons to use OS-dependent code (like installing and APK), but I don't get why there needs a special case, with several functions in several language for something which can be also be done in LUA. Just for ONE type of file in ONE special instance. Especially, if it leads to compatibility problems and can't be used on any other platform.

**Comment by pazos** [comment]
> My point is that there is most likely no need of special (and device-dependent) code for Android just for the mundane task of downloading an APK-file. All other downloads in KOReader seem to handled by LuaSocket on ALL devices in ALL instances.

> I have no doubt that there are many valid reasons to use OS-dependent code (like installing and APK), but I don't get why there needs a special case, with several functions in several language for something which can be also be done in LUA. Just for ONE type of file in ONE special instance. Especially, if it leads to compatibility problems and can't be used on any other platform.


Do some research first, please.

Do you know that LuaJIT is mostly single threaded?

Do you know that all the benefits from the multithreaded capable `android_app_glue` get lost when we handle the entire `android_app_state` to a single luajit instance?

Do the rest of instances trigger an ANR when a blocking task, like a network download, takes more than 5s?

Do the rest of instances run LuaJIT in a separate thread that communicates with the OS/platform middleware using some kind of IPC?

Please stop the **WHATABOUTISM**, it doesn't help. Either stick with a solution that goes beyond the workaround for a broken device and implement it as the maintainer requests or move on, find another device, another app, another ...

And yes, I'm the maintainer for the android port as well as the cervantes port. I have plenty of knowledge about the kobo port too and some about Pocketbooks. They share most of the frontend codebase because we spent time writting proper device abstractions so users, like yourself, won't need to realize about each platform specific quirks.

These platforms specific quirks is what make KOReader a hell to maintain, specially on non standard, broken as hell, undocumented mess that some Eink readers are.

**Comment by Gabriel85** [comment]
> > My point is that there is most likely no need of special (and device-dependent) code for Android just for the mundane task of downloading an APK-file. All other downloads in KOReader seem to handled by LuaSocket on ALL devices in ALL instances.
> 
> > I have no doubt that there are many valid reasons to use OS-dependent code (like installing and APK), but I don't get why there needs a special case, with several functions in several language for something which can be also be done in LUA. Just for ONE type of file in ONE special instance. Especially, if it leads to compatibility problems and can't be used on any other platform.
> 
> Do some research first, please.
> 
> Do you know that LuaJIT is mostly single threaded?
> 
> Do you know that all the benefits from the multithreaded capable `android_app_glue` get lost when we handle the entire `android_app_state` to a single luajit instance?
> 
> Do the rest of instances trigger an ANR when a blocking task, like a network download, takes more than 5s?
> 
> Do the rest of instances run LuaJIT in a separate thread that communicates with the OS/platform middleware using some kind of IPC?
> 
> Please stop the **WHATABOUTISM**, it doesn't help. Either stick with a solution that goes beyond the workaround for a broken device and implement it as the maintainer requests or move on, find another device, another app, another ...
> 
> And yes, I'm the maintainer for the android port as well as the cervantes port. I have plenty of knowledge about the kobo port too and some about Pocketbooks. They share most of the frontend codebase because we spent time writting proper device abstractions so users, like yourself, won't need to realize about each platform specific quirks.
> 
> These platforms specific quirks is what make KOReader a hell to maintain, specially on non standard, broken as hell, undocumented mess that some Eink readers are.

Yes, thanks for the explanation! That even I can understand...
Next time please just give the technical explanation in one sentence and we can save the back and forth.

So a multi-threaded general solution for all devices in Lua with a progress bar (something like https://love2d.org/forums/viewtopic.php?t=84484), would be acceptable, too?

**Comment by hasezoey** [comment]
i am somewhat following what this issue will bring, and my current understanding is basically:
> OTA file download should be in another thread than the front-end to not cause ANR. Lua (or at least the current implementation) is not good at multi-threading and needs to handle platform-specific events (android in this case), so it should be done in the "native" script (in this case kotlin).

is this understanding correct?

**Comment by Frenzie** [comment]
I think "platform specific events" is rather understating the situation, but in essence yes.
