### ISSUE TITLE
FR: Review of words from a single book in Vocabulary Builder

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11471]
**Does your feature request involve difficulty completing a task? Please describe.**
In Vocabulary Builder, if someone wants to review the words of only one book or a few books, one has to deselect all other books one by one. This takes a long time and becomes tedious, if there are many books. Could there be a shorter way?

**Describe the solution you'd like**
There could be a checkbox on each page to select/deselect all books on the page. Also a long press on a book could give the following options: "rename book" (already enabled by the long press) and "select only this book".

@weijiuqiao, what do you think?

Thank you!

**Comment by weijiuqiao** [comment]
Hi. The checkbox on each page is not easy to implement because I'm using one of koreader's stock widgets. However, the long-press popup could theoretically have more functions. I'll take a look :)

**Comment by ichnilatis-gr** [comment]
Thank you!
