### ISSUE TITLE
After koreader is updated to 2024.01, the status bar is not displayed

### ISSUE THREAD

**Issue by SuperLevn** [koreader/koreader#11480]
* KOReader version:2024.01
* Device:Kindle Oasis 3

#### Issue
After updated to 2024.01, the status bar is not displayed. Before update, the status bar was displayed normally. After the update, it was also displayed initially, but the status bar was not displayed the next night.
![01](https://github.com/koreader/koreader/assets/102505927/421e83cf-48b0-41c8-9011-c61e4a477c51)
![02](https://github.com/koreader/koreader/assets/102505927/328f26ee-5389-42d5-a787-69e1fdda1150)
![03](https://github.com/koreader/koreader/assets/102505927/6c63caac-ac46-4d4f-90ac-2e9e2361ef8a)
![04](https://github.com/koreader/koreader/assets/102505927/c9404c0a-cf05-45be-916f-765e2c24fbf6)
![05](https://github.com/koreader/koreader/assets/102505927/905ab889-3f97-412e-8695-00ee0ddbe052)
![06](https://github.com/koreader/koreader/assets/102505927/ecf3542b-11a6-4ef8-93dc-345894fdfc3a)

**Comment by Frenzie** [comment]
Have you tried tapping on the bottom part of the screen? By default that toggles it.

**Comment by SuperLevn** [comment]
I had tried tapping on the bottom, but it didn't work

**Comment by Frenzie** [comment]
Maybe @NiLuJe has an idea about Kindles.

**Comment by SuperLevn** [comment]
Good news, my Koreader status bar is back. Just a minute ago, I wanted to wake up the bottom toolbar to adjust the font size. I clicked on a position in the lower right corner and the status bar suddenly came back. It was really amazing. , I tried clicking various positions at the bottom before, but failed to display the status bar. Maybe the status bar is too tired and it wants to take a nap.
![微信图片_20240219203758](https://github.com/koreader/koreader/assets/102505927/62c93d4a-9abd-4c15-923e-168314066b16)

**Comment by Frenzie** [comment]
I don't think that should have any different results than turning a page or something. Incidentally, there's also a long diagonal swipe to do a full screen refresh.

**Comment by NiLuJe** [comment]
Possibly a wonky touch panel near the bottom of the screen, or a misconfigured bottom tap zone?

(In any case, it seems to work as intended, and I'd wager the issue is just the hardware lying to us or being wonky, or the tap zone being wonky).
