### ISSUE TITLE
Cropping: Show a transparent overlay

### ISSUE THREAD

**Issue by equwal** [koreader/koreader#11489]
**This is probably quite a challenge to pull off, but would be very cool.**

When you select to crop a book, you only get one page to look at. Then you might have some pages that are offset a bit, and you cropped away the actual content. The Briss program solves this with a transparent overlay feature, so you can see all the pages at once and crop.

![i hate the antichrist](https://i.redd.it/q6esq1oqegkc1.png)

**Describe alternatives you've considered**
I usually use briss to crop instead of koreader.

**Additional context**
ereaders >8" are pretty expensive, but and ironically most people who want an ereader get into it it with the idea that they will "use it to read PDFs". When they discover their device is too small...it is very sad. Having this interface could really improve the usability of 7-8" devices for reading most PDFs without the annoying interference of selecting a bad crop.

**Comment by hugleo** [comment]
Ereaders aren't powerful enough to process all pages at the same time to detect such overlay. Manual cropping for even and odd pages is implemented, though.

**Comment by Frenzie** [comment]
Fit to content width covers most use cases quite well I think.

Incidentally you can use landscape mode for wide PDFs.

**Comment by equwal** [comment]
> Ereaders aren't powerful enough to process all pages at the same time to detect such overlay. Manual cropping for even and odd pages is implemented, though.

Good point, is this true though? I suspect this isn't as resource intensive as it seems. A naïve implementation is to just overwrite the contents of a buffer with N pages, which is O(n) time, then finally display it on the screen. Most ereaders have 1Ghz+ processors so I think this should be doable.

**Comment by equwal** [comment]
> Fit to content width covers most use cases quite well I think.
> 
> Incidentally you can use landscape mode for wide PDFs.

This is for removing the margins of the PDF, which fitting to width doesn't do. For literature the margins can be 20% of the page!

**Comment by hugleo** [comment]
> > Ereaders aren't powerful enough to process all pages at the same time to detect such overlay. Manual cropping for even and odd pages is implemented, though.
> 
> Good point, is this true though? I suspect this isn't as resource intensive as it seems. A naïve implementation is to just overwrite the contents of a buffer with N pages, which is O(n) time, then finally display it on the screen. Most ereaders have 1Ghz+ processors so I think this should be doable.

But the pages are not loaded instantaneous.  Some pages can take several seconds to load.

**Comment by hugleo** [comment]
> > Fit to content width covers most use cases quite well I think.
> > Incidentally you can use landscape mode for wide PDFs.
> 
> This is for removing the margins of the PDF, which fitting to width doesn't do. For literature the margins can be 20% of the page!

Unless you have a very bad scan, such irregular PDFs are rare nowadays? You can use semi-auto crop to remove some undesired footer that should be common to all pages. The white part will be cropped automatically for all pages. You can perform the process two times if you want, once for the even pages and once for the odd pages. All the even pages will become similar to the first crop, and all the odd pages will behave similarly to the second crop.
