### ISSUE TITLE
Wallabagger extension (not related to KOReader) results in incorrect output

### ISSUE THREAD

**Issue by hightide591** [koreader/koreader#11481]
* KOReader version: latest
* Device: kobo

#### Issue
After retrieving articles from server in Wallabag, the articles do not appear in download folder on Kobo. I realized the issue is related to filenaming. When I FTP into the device's wallabag folder from my computer, I can see the articles but they do not show up on the device. When I add .epub extension to the articles on my kobo from my FTP client, they suddenly appear on the device. It appears koreader isn't adding the correct extension (.epub) when it retrieves them from wallabag.

This ONLY occurs when the article was saved manually from wallabag. If i right click a link and "add to wallabag" the .epub extension is added correctly when I retrieve them. But if I run wallabagger from the extension menu, I get this issue. 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hightide591** [comment]
I figured out a workaround for the time being. The articles show up on kobo if I enable "show unsupported files" in settings. Then I add the .epub extension manually in the kobo to be able to read them.

**Comment by Frenzie** [comment]
That sounds more like a Wallabag issue? Which version? I don't have it set up right this moment but I've tested it with the plus button there in the past.

**Comment by hightide591** [comment]
> That sounds more like a Wallabag issue? Which version? I don't have it set up right this moment but I've tested it with the plus button there in the past.

2.6.8

**Comment by hightide591** [comment]
> I figured out a workaround for the time being. The articles show up on kobo if I enable "show unsupported files" in settings. Then I add the .epub extension manually in the kobo to be able to read them.

Update: adding .epub does not actually work. The files appear on the device but the formatting is actually all fucked up. They are not readable when I do this. My new workaround: export the articles to epub on my computer then add manually via USB or FTP to Kobo. This works for now but is inconvenient.

**Comment by hightide591** [comment]
> > I figured out a workaround for the time being. The articles show up on kobo if I enable "show unsupported files" in settings. Then I add the .epub extension manually in the kobo to be able to read them.
> 
> Update: adding .epub does not actually work. The files appear on the device but the formatting is actually all fucked up. They are not readable when I do this. My new workaround: export the articles to epub on my computer then add manually via USB or FTP to Kobo. This works for now but is inconvenient.

Update: the issue appears to be only for NYT articles. Other sites behave normally.

**Comment by Frenzie** [comment]
Could you follow the instructions from the issue template for the debug logs from the Wallabag plugin.

> If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with verbose debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both Enable debug logging and Enable verbose debug logging.
You'll need to restart KOReader after toggling these on.

**Comment by Frenzie** [comment]
I added `https://www.nytimes.com/2024/02/21/world/europe/us-russia-nuclear-weapon-space.html` to Wallabag 2.6.8 using the + button.

I've attached the result the plugin downloaded for me. I don't see any problems.

[[w-id_1] U.S. Warns Allies Russia Could Put a Nuclear Weapon Into Orbit This Year.zip](https://github.com/koreader/koreader/files/14361475/w-id_1.U.S.Warns.Allies.Russia.Could.Put.a.Nuclear.Weapon.Into.Orbit.This.Year.zip)

**Comment by hightide591** [comment]
> I added `https://www.nytimes.com/2024/02/21/world/europe/us-russia-nuclear-weapon-space.html` to Wallabag 2.6.8 using the + button.
> 
> I've attached the result the plugin downloaded for me. I don't see any problems.
> 
> [[w-id_1] U.S. Warns Allies Russia Could Put a Nuclear Weapon Into Orbit This Year.zip](https://github.com/koreader/koreader/files/14361475/w-id_1.U.S.Warns.Allies.Russia.Could.Put.a.Nuclear.Weapon.Into.Orbit.This.Year.zip)

Yes, the problem only arises if I save the article to Wallabag by using the extension (Content fetching from the browser). If I use the + the epubs look fine once I retrieve them. But the problem with using the + is wallabag does not get by paywalls. I have a subscription so I have to use content fetching from browser to get the full article to show up in Wallabag.

**Comment by hightide591** [comment]
> Could you follow the instructions from the issue template for the debug logs from the Wallabag plugin.
> 
> > If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with verbose debug logging enabled before providing the logs to us.
> > To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both Enable debug logging and Enable verbose debug logging.
> > You'll need to restart KOReader after toggling these on.

I have followed these instructions and reproduced the issue. What now?

**Comment by Frenzie** [comment]
You'd share the part where it downloads to see if there's anything odd going on.

**Comment by hightide591** [comment]
> You'd share the part where it downloads to see if there's anything odd going on.

What folder stores the logs?

**Comment by Frenzie** [comment]
I can't reproduce anything odd with the Wallabagger extension either.

![image](https://github.com/koreader/koreader/assets/202757/46e55fc7-bee9-442a-9f03-bfbd2ccd4d23)


[[w-id_4] Wallabagger extension (not related to KOReader) results in incorrect output · Issue #11481 · koreader_koreader.zip](https://github.com/koreader/koreader/files/14393670/w-id_4.Wallabagger.extension.not.related.to.KOReader.results.in.incorrect.output.Issue.11481.koreader_koreader.zip)

**Comment by Frenzie** [comment]
> * `/mnt/private/koreader` for Cervantes
> 
> * `koreader/` directory for Kindle
> 
> * `.adds/koreader/` directory for Kobo
> 
> * `applications/koreader/` directory for Pocketbook

**Comment by hightide591** [comment]
> I can't reproduce anything odd with the Wallabagger extension either.
> 
> ![image](https://private-user-images.githubusercontent.com/202757/307537557-46e55fc7-bee9-442a-9f03-bfbd2ccd4d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTQ0MTcsIm5iZiI6MTcwODc5NDExNywicGF0aCI6Ii8yMDI3NTcvMzA3NTM3NTU3LTQ2ZTU1ZmM3LWJlZTktNDQyYS05ZjAzLWJmYmQyY2NkNGQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxNzAxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDk4ZDQyYjI0NTJkNzJlMTJiNTUwNjFlMzFhNDEzZWI3YTUzMmFiMTg2MTNkNzBiZmQ1YmY5ZmRmMjhlYWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tRrhYI0GxYXUalDsabI-hBlLqwxUMTp3lU-_jR-zFhM)
> 
> [[w-id_4] Wallabagger extension (not related to KOReader) results in incorrect output · Issue #11481 · koreader_koreader.zip](https://github.com/koreader/koreader/files/14393670/w-id_4.Wallabagger.extension.not.related.to.KOReader.results.in.incorrect.output.Issue.11481.koreader_koreader.zip)

Ok so this epub you uploaded. How did you get it? Did you get it by going to wallabag on your computer and clicking "export to epub?" Or did you retrieve it from Koreader? Because the issue only occurs when I retrieve articles (that I saved with the extension) in Koreader. If I export to EPUB on my computer they are fine.

**Comment by Frenzie** [comment]
* I installed Wallabagger and enabled the setting in the screenshot.
* Then I added this very page. You can see it's from me because otherwise it wouldn't say anything about deletion. Curious thing to pick out as the content but that aside :-)
* Then I retrieved it using KOReader. Export as EPUB from the web interface has a name like `Wallabagger extension not related to KOReader results in incorrect output Issue 11481 koreaderkoreader.epub`. The `[w-id_4]` at the front is from the KOReader plugin.

**Comment by hightide591** [comment]
> * I installed Wallabagger and enabled the setting in the screenshot.
> 
>     * Then I added this very page. You can see it's from me because otherwise it wouldn't say anything about deletion. Curious thing to pick out as the content but that aside :-)
> 
>     * Then I retrieved it using KOReader. Export as EPUB from the web interface has a name like `Wallabagger extension not related to KOReader results in incorrect output Issue 11481 koreaderkoreader.epub`. The `[w-id_4]` at the front is from the KOReader plugin.
> 
> 
> PS Retrieved by Wallabag directly instead of from Wallabagger the output looks like this: [[w-id_4] Wallabagger extension (not related to KOReader) results in incorrect output · Issue #11481 · koreader_koreader.zip](https://github.com/koreader/koreader/files/14393697/w-id_4.Wallabagger.extension.not.related.to.KOReader.results.in.incorrect.output.Issue.11481.koreader_koreader.zip)

Ok just to try something. Go to this page: https://www.nytimes.com/2024/02/24/world/europe/lessons-choices-war-in-ukraine.html. The save with the extension: 

![Screen Shot 2024-02-24 at 12 23 24 PM](https://github.com/koreader/koreader/assets/125679198/dd8144ee-339f-48a8-b823-c39fb9979f5c)

Then retrieve it in Koreader and send me the epub. 

Btw what reader are you using?

**Comment by hightide591** [comment]
Also I have the crashlog. How do I privately share with you?

**Comment by hightide591** [comment]
[crashlog.txt](https://github.com/koreader/koreader/files/14393761/crashlog.txt)

Here is the log.

**Comment by Frenzie** [comment]
There's a part of the logic that's mainly intended to prefer downloading the original PDF over text extracted by Wallabag. This logic effectively said to always download the original source unless the mimetype is `text/html`, in which case we prefer EPUB (by far the most common scenario).

But in this extension case the mimetype came out as `text/html; utf-8`, thus triggering the behavior of downloading the original page. This is different than when you use the + button in Wallabag itself, in which case it comes out as `text/html`.
