### ISSUE TITLE
incorrect ordering of chapters inside cbz

### ISSUE THREAD

**Issue by KeePach** [koreader/koreader#11497]
* KOReader version: 2024.01
* Device: KindlePaperWhite3

#### Issue
when a cbz file contains folders for chapters, if the folder names contain decimal numbers, those chapters appear before the chapter without the decimal number instead of after.

#### Steps to reproduce
create a cbz file with folders for chapters like:
ch.-1
ch.-2
ch.-2.5
ch.-3
ch.-4
ch.-4.5
etc
when opening the file with koreader, the order presented is:
ch.-1
ch.-2.5
ch.-2
ch.-3
ch.-4.5
ch.-4

**Comment by Frenzie** [comment]
See solution in https://www.mobileread.com/forums/showthread.php?p=4401079#post4401079

> someone on other forum told me that the naming convention should be uniform in order for koreader to be able to be read it correctly so if there is a folder with a dot, all other folders should accomodate to that, in my case being that the names where 24, 25, 26, 26.005, the folders should be renamed to 24.000 25.000, 26.000, 26.005, and that worked great.

**Comment by axu2** [comment]
@KeePach 

If you name the folders

Hello/
Hello./
Hellos/

Does it preserve the order?
