### ISSUE TITLE
Virtual keyboard unexpectedly minimizes when typing (dead area around keys and keyboard)

### ISSUE THREAD

**Issue by tarkeez** [koreader/koreader#11490]
* KOReader version: 2024.01
* Device: Android, Linux

#### Issue
Initial observation/experience: 
When using the virtual keyboard and typing fast, the keyboard is unexpectedly minimized. **This causes loss of any input you've made** as you are likely to press outside of the input box with your next press (after the keyboard has been minimized) when you are typing fast, and so you have to start over. **This is frustrating when adding notes especially.**

**Upon testing, it seems that the outline of the keyboard and each key is transparent, meaning, when touched/pressed, it registers as a touch outside of the keyboard and minimizes it.**

#### Steps to reproduce
1. Open an input box (search, add note, etc) and be greeted by the virtual keyboard. 
2. Press on the gray outline around the keyboard itself, or around each key (if you don't have borders on in Keyboard Appearance settings, it isn't gray, but the behavior is the same -- the area around keys and the keyboard registers as an outside touch/press). 
3. If your touch registers on the outline itself, it minimizes the keyboard.

This is very easy to verify with a mouse.

#### Proposed solution
1. Make the whole keyboard layer area opaque, so that a press on the border (around the keyboard or around the keys) is **never** registered as an outside-the-keyboard press.
4. Have 0 pixels separation between keys and between the keyboard and right, left, and bottom edges of the screen. 
5. Always pick the key closest to the press. Not sure exactly how this is handled. I don't think it is wise to ignore presses on the outline as a solution, but it is certainly better than registering them as outside-the-keyboard presses. Imo a key should always be chosen, **but this is secondary to making sure the presses within the keyboard frame aren't registered as outside the keyboard and thus minimize it.**

**Comment by poire-z** [comment]
Possibly the same issues as in #11357 , fixed by https://github.com/koreader/koreader/commit/40d27ac3e59d95ff271478e89d7f040bb2bf418f which should be in the coming up v2024.02 release ?

**Comment by tarkeez** [comment]
Well hey would ya look at that

I profess that today I have learned to search for similar issues before opening one :)
