### ISSUE TITLE
Exiting to Nickel from Koreader in Kobo Glo 3.8 firmware causes reboot and Adobe DRM issue

### ISSUE THREAD

**Issue by chandravadans** [koreader/koreader#1151]
I'm on a Kobo Glo, firmware version 3.8.0. Latest nightly release as of today.
When I select the Home icon, the device reboots, and opening any books outside of koreader gives a wierd "Oops, this document couldnt be opened, this document is protected by Adobe DRM" notice. I have to reboot the device by pulling the power switch to make everything work normally again.
This is the first time (older versions of koreader, atleast till July didn't have this issue) I'm facing this issue, and do find it quite strange. Could someone possibly look into this? Or atleast take a guess at where the root of the problem is at so that even I could take a look at it?

**Comment by chrox** [comment]
Seems no progress. And the "fmon" launching method for koreader is deprecated with the "KSM" being the recommended way. I'll close this now.
