### ISSUE TITLE
Should pc read truncate instead of round up?

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11516]
This is more of a question for you all, then a request or bug.

![IMG_5367](https://github.com/koreader/koreader/assets/97603719/8bcb6234-10e5-4588-be41-0d2d560ab9b8)

i was mildly annoyed when i had to stop reading three pages short from the end of the story, but even more [mildly] annoyed when i realised that KOReader thinks that 684/687=1

i know it is because the percentage is being rounded up instead of being truncated, so my question is: should it not truncate instead? I am happy with the rounding up until around 90%, after that i feel like i want my percentages to be more strict. Thoughts…

**Comment by Frenzie** [comment]
And at 0 it should then round up. Seems reasonable.

**Comment by Commodore64user** [comment]
> And at 0 it should then round up. Seems reasonable.

0 of 300 = 0
1 of 300 = 1%
3 of 300 = 1%
5 of 300 = 2%
6 of 30l = 2%

i’m okay with that.

**Comment by offset-torque** [comment]
I agree with **Commodore64user**. Normal percentages give users an idea where they are, but **0** and **100** are special numbers which (should) indicate that **"you haven't opened this book yet"** and **"you have seen all the pages in this book"**. Maybe **0** is not that useful in this situation (you can't show it in screensaver because once you open a book, you have seen the first page so it is already over 0) but **100%** should be reached only when user sees the last page to avoid confusion IMHO.

**Comment by Commodore64user** [comment]
Anyone knows if it’s possible to adjust the font size for the screen message? I have a book with over a thousand pages and when you get to the thousandth page, the battery percentage (i.e the pc in brackets) drops to a second line, i would prefer to reduce the font maybe by one so that does not happen.

**Comment by Frenzie** [comment]
If you're fine with all fonts everywhere you can change the DPI in settings. If you're talking about some very specific font somewhere you'd have to override it with a user patch.

**Comment by Commodore64user** [comment]
> If you're fine with all fonts everywhere you can change the DPI in settings. If you're talking about some very specific font somewhere you'd have to override it with a user patch.

The one on the screen saver message, like in the picture.

**Comment by Commodore64user** [comment]
So how about replacing this [code line](https://github.com/koreader/koreader/blob/dd8560cef8a50c0c55934f55db4554413b0aa1d0/frontend/ui/screensaver.lua#L151C9-L151C63) (and the other cases too as well of course) with:
`if ((currentpage / totalpages) * 100) < 1 then
            percent = 1
        else
            percent = math.floor((currentpage * 100) / totalpages)
        end`
what do think about that?

**Comment by Frenzie** [comment]
That seems to be missing `if currentpage == 1 then percent = 0` (or is that currentpage == 0, but either way)

**Comment by Commodore64user** [comment]
Ok, there is a brach ready for a PR, unfortunately, it will need to wait until after #11524 is resolved as I clumsily made that PR on the forked master instead of a branch… oops. 🙊 in other words, i forked up.

**Comment by Commodore64user** [comment]
@hius07 you flatter me, but I am only an enthusiast not a pro, some of that is beyond my capabilities, and by capabilities I mean: my coding skills are the equivalent of poking animals with a stick to see what they do 😅. Joke aside, what I have done is rearrange the "Screensaver" menu so it uses better wording and is more user friendly. I would like to make a few more changes in the menus (in general) but would like to show you guys that one first to see what you [maintainers] think.

**Comment by Commodore64user** [comment]
@Frenzie and @hius07: I am trying to add this `if` statement to the widget to "fix" the multi-line **lock screen** message inconvenience, but it crashes the programme. probably something to do with `textw` or `textw:getWidth()`, maybe? any help would be great 

```lua
        local message_widget
        local screen_w = Screen:getWidth()
        local face = Font:getFace("infofont")
        local textw = InfoMessage:new{
            text = screensaver_message,
            face = face,
        }
        if message_pos == "middle" then
            message_widget = InfoMessage:new{
                if textw:getWidth() > screen_w * 0.9 then
                    local face1 = Font:getFace("smallinfont")
                    text = screensaver_message,
                    readonly = true,
                    dismissable = false,
                    --face = face1,
                else
                    text = screensaver_message,
                    readonly = true,
                    dismissable = false,
                end
            }
```

**Comment by Frenzie** [comment]
What exactly is the multiline inconvenience?

**Comment by Commodore64user** [comment]
#https://github.com/koreader/koreader/issues/11516#issuecomment-1979433527

@Frenzie

**Comment by Frenzie** [comment]
There is some code for that kind of thing

https://github.com/koreader/koreader/blob/5d2782ddfefe63ca2007c4e9019bc74c0ec6efcb/frontend/ui/widget/menu.lua#L154-L167

https://github.com/koreader/koreader/blob/5d2782ddfefe63ca2007c4e9019bc74c0ec6efcb/frontend/ui/widget/textwidget.lua#L67-L88

**Comment by Commodore64user** [comment]
Yes, I knew there was something like that somewhere, as I have noticed that behaviour in the 'detailed list file-browser view'. When opening a book with a long name, it shrinks the font size to fit in the mandatory. Problem is, I have no idea how to implement that. I have rudementary coding skills but a can-do attitude.
