### ISSUE TITLE
text selection cannot be adjusted

### ISSUE THREAD

**Issue by elandorr** [koreader/koreader#11519]
* KOReader version: koreader-appimage-x86_64-linux-gnu-v2023.10.AppImage to koreader-appimage-x86_64-linux-gnu-v2024.03.AppImage
* Device:

#### Issue

From the docs:
![image](https://github.com/koreader/koreader/assets/56206745/37811ce7-360e-4f89-9348-00cf8e127219)

The lower row is missing all of a sudden.

![image](https://github.com/koreader/koreader/assets/56206745/a8477c59-3398-419c-9bdb-f6a1ee93c781)

Maybe I've missed a change, but I couldn't find anything in the changelog on the release page or in the settings.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hius07** [comment]
Is the book opened an epub file? Adjusting is not available for pdf.
