### ISSUE TITLE
FR: Allow setting of status bar item prefix per element/item

### ISSUE THREAD

**Issue by veonru** [koreader/koreader#11512]
Hi,

I am using the status bar with the compact style/item prefix and am mostly satisfied with how it looks.
However, I would prefer the battery percentage to be shown next to the battery icon, like the two other styles. This is not possible, since one can only change the item prefix globally.

Possible solution:
It would be great to be able to set the item prefix individually/overwrite the item prefix for individual items.

Alternatives:
For me personally a user patch changing the battery icon in compact mode to include percentage would be enough. Unfortunately I lack the skills to implement such a patch myself and I wasn't able to find one either.

It's just a very small issue/wish, but maybe others are interested too.

Thanks!

**Comment by poire-z** [comment]
The footer bits are a little hidden inside readerfooter.lua (local variables, not easily patchables).
Moreover, what you want is not replacing a symbol, it's in the function that generate the little battery string to do the work it does when in other modes (it uses the same symbol, you want more text near the symbol).
These little functions/generators of the item text bits are a bit more accessible, so you can have a quite not too complex user patch - where you just hardcode the things you want as text for each item.
ie.:
2-my-footer-hack.lua
```lua
local BD = require("ui/bidi")
local Device = require("device")
local ReaderFooter = require("apps/reader/modules/readerfooter")

-- Cut and pasted from ReaderFooter, and tweaked/cleaned from alternative options we don't want
-- https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerfooter.lua
local my_battery = function(footer)
    local prefix = "" -- hope this is ok, if not properly paste it from the code line 83
    local powerd = Device:getPowerDevice()
    local batt_lvl = 0
    local is_charging = false

    if Device:hasBattery() then
        local main_batt_lvl = powerd:getCapacity()

        if Device:hasAuxBattery() and powerd:isAuxBatteryConnected() then
            local aux_batt_lvl = powerd:getAuxCapacity()
            is_charging = powerd:isAuxCharging()
            -- Sum both batteries for the actual text
            batt_lvl = main_batt_lvl + aux_batt_lvl
            -- But average 'em to compute the icon...
            prefix = powerd:getBatterySymbol(powerd:isAuxCharged(), is_charging, batt_lvl / 2)
        else
            is_charging = powerd:isCharging()
            batt_lvl = main_batt_lvl
           prefix = powerd:getBatterySymbol(powerd:isCharged(), is_charging, main_batt_lvl)
        end
    end

    if footer.settings.all_at_once and batt_lvl > footer.settings.battery_hide_threshold then
        return ""
    end

    -- Use the one you prefer:
    return BD.wrap(prefix) .. batt_lvl .. "%"
    -- return BD.wrap(prefix) .. " " .. (is_charging and "+" or "") .. batt_lvl .. "%"
end

local orig_ReaderFooterr_init = ReaderFooter.init

ReaderFooter.init = function(self)
    orig_ReaderFooterr_init(self)
    print("hacking footer")
    ReaderFooter.textGeneratorMap.battery = my_battery
    self:updateFooterTextGenerator()
    -- We only needed to do this once, so restore the original
    ReaderFooter.init = orig_ReaderFooterr_init
end
```
And as peoples' needs may be really different (ie. only an icon change, or more text like you), it's best left to this kind of user patch where people can do what they want (even hardcoding "100 %" if a user feels he is less stressed when the battery is full :))

**Comment by veonru** [comment]
Thank you very much for the patch, it works great!

I understand your reasoning. I guess it really is too user-specific to implement.
