### ISSUE TITLE
appimage: relative paths don't work, and if attempted max out a CPU core indefinitely

### ISSUE THREAD

**Issue by elandorr** [koreader/koreader#11518]
* KOReader version: koreader-appimage-x86_64-linux-gnu-v2023.10.AppImage to koreader-appimage-x86_64-linux-gnu-v2024.03.AppImage
* Device:

#### Issue
If you run e.g. `../../../appimages/koreader-appimage-x86_64-linux-gnu-v2024.03.AppImage Handout-1.pdf` you get a white screen and 1 core at 100% until you kill `./luajit ./reader.lua`.

Iirc appimages are broken that way and they never resolved the relative path issue, but I'm not sure. Either way it should probably not lock up.

#### Steps to reproduce
see above

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by pazos** [comment]
Can't reproduce here any of the statements.

A relative path to a document doesn't work. But it starts the program like if you start without a path argument.
An absolute path to a document works fine even when you're invoking the appImage from a different path.

>  you get a white screen and 1 core at 100% until you kill ./luajit ./reader.lua.

Can't reproduce.

Please follow the bug template: attach info about your device (in this case os, version, compositor, wm) and the logs the app writes to stdout when you call it.

**Comment by Frenzie** [comment]
What pazos said. A relative path indeed doesn't work, but it simply shows the file browser.

**Comment by pazos** [comment]
Can't reproduce here in i3, sway, hyperland.

Are you a troll?. If not OS and wm

**Comment by pazos** [comment]
> What pazos said. A relative path indeed doesn't work, but it simply shows the file browser.

@Frenzie: that should be easy to fix. The debian package uses https://github.com/koreader/koreader/blob/master/platform/debian/koreader.sh#L7-L12, which isn't too battle tested, but seems to work fine here with:

```bash
koreader Descargas/es8051530148.pdf
koreader ../pazos/Descargas/es8051530148.pdf
koreader ../../home/pazos/Descargas/es8051530148.pdf
```
