### ISSUE TITLE
FR: Exporting your notes and highlights on Nextcloud Note

### ISSUE THREAD

**Issue by llaumgui** [koreader/koreader#11522]
Currently, only Joplin is supported as selfhosted solution. Readwise, Memos, Flomo and XMNote are services.
It's would be nice to allow to sync with Nextcloud Note.

**Comment by pazos** [comment]
Documentation: https://github.com/nextcloud/notes/blob/main/docs/api/v1.md

**Comment by kotnik** [comment]
I am heavy user of Nextcloud Notes, and I find this very useful. So I have started working on plugin support [here](https://github.com/kotnik/koreader/commits/nc_notes_export/).
