### ISSUE TITLE
Wallabag: epubs being converted to htm in 2024.03+

### ISSUE THREAD

**Issue by dlgoodr** [koreader/koreader#11528]
* KOReader version: 2024.03
* Device: android (leaf2 and inkpalm) (can test kindle if needed)

#### Issue
EPUB files downloaded through the wallabag plugin are being converted to HTML and lots of the cruft wallabag strips is restored, along with guesses about chapter marks. 

#### Steps to reproduce
Install latest, download article epub, weep. Restore to 2024.01 for the expected behavior. 

This isn't a crash, just an unwelcome change in experience that I can't figure out how to revert without going back to 2024.01

**Comment by poire-z** [comment]
Probably #11492 (not using Wallabag, so no idea of the context).
Try reverting manually the small changes in https://github.com/koreader/koreader/commit/3e7ab199e7fd6a60e813ebd48abfc05af9bac635.

**Comment by dlgoodr** [comment]
Based on my poor understanding of LUA, we shouldn't be affected, we're correctly returning `application/epub+zip` for the file:

<details>
<summary>direct wget of pub</summary>

```
dlg@manila ~ % wget https://wb.example.org/api/entries/1668524955/export.epub
--2024-03-09 10:09:13--  https://wb.example.org/api/entries/1668524955/export.epub
Resolving wbip.dsrw.org (wb.example.org)... 100.12.12.12
Connecting to wbip.dsrw.org (wb.example.org)| 100.12.12.12 |:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 890444 (870K) [application/epub+zip]
Saving to: ‘export.epub’

export.epub         100%[===================>] 869.57K   711KB/s    in 1.2s    

2024-03-09 10:09:15 (711 KB/s) - ‘export.epub’ saved [890444/890444]

dlg@manila ~ % file export.epub 
export.epub: EPUB document
dlg@manila ~ % 
```

</details>


_but_ reverting https://github.com/koreader/koreader/commit/3e7ab199e7fd6a60e813ebd48abfc05af9bac635 definitely fixes the issue for me.

**Comment by poire-z** [comment]
Quick reading, and it feels this change negate its aim:
```diff
-    if article.mimetype ~= "text/html" then -- different from text/html
+    if type(article.mimetype) == "string" and article.mimetype:find("^text/html") then -- starts/equal to text/html
```
@Frenzie ?

**Comment by Frenzie** [comment]
No time today but based purely on the line you posted there a not is
missing

**Comment by dlgoodr** [comment]
Just adding a `not` does not fix the issue.

**Comment by Frenzie** [comment]
@dlgoodr Could you share a URL where you see this issue and your Wallabag version for good measure?

**Comment by dlgoodr** [comment]
@Frenzie 
https://wbip.dsrw.org/api/entries/1668524955/export.epub

**Comment by Frenzie** [comment]
@dlgoodr That's an export.

**Comment by dlgoodr** [comment]
@Frenzie sorry, the original article URL?

https://www.theatlantic.com/magazine/archive/2024/04/secret-gospel-mark-controversial-forgery-jesus/677472/

**Comment by Frenzie** [comment]
Curious, my Wallabag gives `text/html; utf-8` for that. In any case, so will have simply been the obvious case of an exact `text/html` match, thanks.

**Comment by Frenzie** [comment]
Tests welcome.
