### ISSUE TITLE
covers in History not shown

### ISSUE THREAD

**Issue by kokoreader** [koreader/koreader#11521]
* KOReader version: 2024.03
* Device: Kobo Aura One

#### Issue

After installing v2024.03, covers in History for ebooks that were deleted before installing this version are not shown. Previous koreader versions did show the covers of deleted books. I was wondering if this behavior is due to a change in the default value of some feature or may be a bug. Thank you for your attention.

**Comment by poire-z** [comment]
We indeed changed a bit of the geometry of the cover grid, and the logic for refreshing cover bitmaps when it changes. #11232.
So, its side effect is that with v2024.03, all covers needed to be refreshed to get the best bitmap sized for the new geometry - and we didn't indeed think about deleted books for which we can't fetch an updated cover :/ (dunno if it would have been feasible / not too clumsy to detect that and keep the older not-optimal-sized cover in this case...)

**Comment by poire-z** [comment]
^ Oh, so, these old covers were not trashed - they were still there, just not shown? Good!

**Comment by Frenzie** [comment]
Indeed. I was afraid I was going to need to tag a second point release to prevent data loss, but I think we'll manage if it's just a display issue. ;-)

**Comment by hius07** [comment]
Please give me an hour to test thoroughly.

**Comment by hius07** [comment]
> Without the fix they can be done visible by reducing the displayed thumbnails size (increasing grid dimensions).

@kokoreader can you check this please.

**Comment by kokoreader** [comment]
Indeed. Thank you for your interest.

The following may be related to this issue:

When exiting History by any means (swipe down, tap on the X, tap on the cover) the bottom menu pops up automatically in the ebook. Again, I am not aware this behavior happened in previous koreader versions.

**Comment by hius07** [comment]
> I was afraid I was going to need to tag a second point release to prevent data loss, but I think we'll manage if it's just a display issue. ;-)

Sorry about that.
There is a risk that users when getting covers invisible, try to press "Refresh cached book info" and that would trash the cache for sure.

**Comment by poire-z** [comment]
So, need for a v2024.03.2, or minor enough issue to not need it?
I tend for the latter :) but @hius07 is holding off merging his opened PRs, so?

**Comment by Frenzie** [comment]
It doesn't seem important enough to me.
