### ISSUE TITLE
KOReader is not up to date on F-Droid

### ISSUE THREAD

**Issue by charleshan** [koreader/koreader#11526]
At the time of writing, the he latest stable release of KOReader on github is 2024.03.1 ([link](https://github.com/koreader/koreader/releases)). However, latest version on F-Droid Version is v2024.01 ([link](https://f-droid.org/en/packages/org.koreader.launcher.fdroid/)) which is two stable versions behind.

**Comment by Frenzie** [comment]
F-Droid takes a few days before it gets around to compiling the new version. But as you can see it's already picked up on it: https://gitlab.com/fdroid/fdroiddata/-/blob/c382b4552d96175c15a8dcfabdf7b7ad65db83e4/metadata/org.koreader.launcher.fdroid.yml
