### ISSUE TITLE
Directory Defaults Settings not being applied

### ISSUE THREAD

**Issue by felipemeamaral** [koreader/koreader#11539]
* KOReader version: 2024.03.1
* Device: Kindle Paperwhite 11th 32GB

#### Issue

Create a new directory_defaults.lua file on /koreader/settings/ with thie content:

```lua
return {--do NOT change this line

[[
  ["/mnt/us/data/mangas/20th Century Boys"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/21th Century Boys"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Akira"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Bakuman"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Bastard"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Bleach"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Death Note"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Dragon Ball"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Dragon Ball Z"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Fullmetal Alchemist"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Grappler Baki"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Great Teacher Onizuka"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Haikyuu"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Hikaru No Go"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Hunter x Hunter"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Jujutsu Kaisen"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Kimetsu no Yaiba"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Love Hina"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Lovely Complex"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Nanatsu no Taizai"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Neon Genesis Evangelion"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Oh! My Goddess!"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Ranma 1-2"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Rurouni Kenshin"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya Episode G"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya Episode G - Assassin"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya Episode G - Requiem"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya Next Dimension"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya Saintia Sho"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Saint Seiya The Lost Canvas"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Slam Dunk"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/The Prince of Tennis"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/The Prince of Tennis II"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Video Girl Ai"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/X 1999"] = {
    "inverse_reading_order" = true
  },
  ["/mnt/us/data/mangas/Yu Yu Hakusho"] = {
    "inverse_reading_order" = true
  },
]]

}--do NOT change this line
```

#### Steps to reproduce

After creating the file and opening a comic/manga, the reading order still like in the eastern, left to right, instead of reverse like configured on directory_defaults file.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
That `[[` and `]]` looks very suspicious. I'd try removing it?

**Comment by mergen3107** [comment]
I agree with @Frenzie , it looks like these were remnants of the multi--line commenting out, but the bottom one should be `--]]` for the comments to work out. Most probably KOReader doesn't like this lua file and ignores it completely.

This is how my settings look like (they work):
```
 -- ADD YOUR DEFAULTS HERE:
return {--do NOT change this line
    ["/mnt/us/Books/[manga]"] = {
        ["inverse_reading_order"] = true,
        ["kopt_zoom_direction"] = 0,
    },
}
```

**Comment by pazos** [comment]
A quick question to @mergen3107: does `/mnt/us/Books/[manga]/whatever` inherits the settings from ``/mnt/us/Books/[manga]`?

If it does this OP might want to simplify its settings to a single root dir.
If it doesn't do this, why not? is there any reason to avoid inheritance on this kind of scenarios?.

**Comment by mergen3107** [comment]
Yes, it does inherit. 

I have sub-folder with manga titles in there, and all of them have the same settings applied from the file.

**Comment by pazos** [comment]
Great, so, @felipemeamaral, you can use:

```lua
return {
  ["/mnt/us/data/mangas"] = {
    "inverse_reading_order" = true
  }
}

**Comment by komadorirobin** [comment]
I'm having trouble adding this rule to an SD card.

This is what I've entered:

["/storage/3435–3332/Manga"] = {
["inverse_reading_order"] = true,
["kopt_zoom_direction"] = 0,
},
