### ISSUE TITLE
FR: Non-blocking progress sync

### ISSUE THREAD

**Issue by danepowell** [koreader/koreader#11535]
**Does your feature request involve difficulty completing a task? Please describe.**
Progress sync currently runs in the same thread as the UI and everything else. If progress sync is automatic, this means that any network delays get added to page turns. At best, this is mildly annoying. At worse, it results in complete program crashes, confusing behavior, and support requests like #9306

**Describe the solution you'd like**
Progress sync should not block page turns or the main thread. 

**Additional context**
There is a lot of technical discussion in #10603 about how this might be accomplished. Although Lua itself is single threaded, it sounded like there were promising workarounds.

**Comment by Frenzie** [comment]
This is one of those things that doesn't really need a ticket, though I guess #5002 is the most concrete actually open issue.

Depending on which device you use you may potentially be able to get async as we speak (though it might not be functional right now).
https://github.com/koreader/koreader/blob/0eaa2d82487a9105a4b94e9278f568fe0c3adb35/defaults.lua#L190-L192

**Comment by NiLuJe** [comment]
> and support requests like #9306

This is no longer relevant, as the series of rework that happened a few months ago means it'll just timeout in a much more palatable fashion (IIRC, 1s, and a flashing refresh on resume already blocks for 500ms anyway ;)).

I don't really have anything else to add to what I said the last time this came up on the technical side of it (which, full disclosure, in my mind right now is: hahaha, nope).

But, on the practical "right now" side of things, if you actually can reproduce something that feels noticeably slow/broken right now, that's another matter entirely, and I'd be much more open about finding a way to deal with that instead ;).

**Comment by danepowell** [comment]
Interesting, I wasn't aware the timeout experience had been improved. Last I checked page turns we're still frequently freezing for >1 second, but I don't remember exactly what version that was.

I'll try auto syncing again and let you know if it's still problematic.
