### ISSUE TITLE
Screensaver as current book cover doesn't work properly

### ISSUE THREAD

**Issue by deepakonwww** [koreader/koreader#11538]
* KOReader version: 2024.03.1
* Device:
Kobo Sage
#### Issue
Screensaver as current book cover doesn't work properly. Instead of book cover image it shows KOReader logo as screensaver, when device is locked.
#### Steps to reproduce
Set Current Book Cover as Screensaver and lock the device, KOReader logo will appear as screensaver instead of book cover image.

**Comment by deepakonwww** [comment]
Is it because of some issue, or we are not supposed to use the previous option anymore?

**Comment by hius07** [comment]
If "the previous option" is Document cover, look at https://github.com/koreader/koreader/issues/11515.

**Comment by deepakonwww** [comment]
Thanks for your kind help, very grateful for your guidance and patience!
