### ISSUE TITLE
Brightness widget Pinenote running Debian

### ISSUE THREAD

**Issue by bytebolt** [koreader/koreader#11556]
Thank you for this lovely project! I have been using KO reader from years!

I have a Pinenote e ink tablet by Pine64 which is running an experimental OS which is not ready for shipping. It's running Debian and comes with KOReader preinstalled.
Is there a way to add brightness widget to it? I can't find it, I am not sure if I need to install a plugin. I know the shell commands that supposedly works from their discord.

* KOReader version: 2023.05.1
* Device: Pine64 PineNote (https://pine64.org/devices/pinenote/)

Any help would be greatly appreciated.

**Comment by pazos** [comment]
Hi. No, ATM the desktop version has no control over brightness. I think we should keep it that way and let the system to manage the hardware.

You can also userpatch yourself or craft a patch for pinenote/debian users. In that case and assuming it is using proper drivers [brightnessctl](https://github.com/Hummer12007/brightnessctl) should do the work.
