### ISSUE TITLE
Hyperlinks won’t open

### ISSUE THREAD

**Issue by colinkarr** [koreader/koreader#11567]
* KOReader version: 2024.03.1
* Device: Boox Leaf 2 and Inkpalm 5

#### Issue
Tapping a hyperlink to an external website, followed by “Open in Browser” does not launch to the browser. No errors - nothing occurs. ~Attempting to copy the URL also does not result in anything.~

#### Steps to reproduce
1. Open any document with a URL hyperlink.
2. Tap the hyperlink
3. Tap “Open in browser”
4. ~Observe nothing happens~
5. ~Tap “Copy”~
6. ~Observe that nothing gets copied to the clipboard.~

**Comment by hugleo** [comment]
Copy text is unimplemented on Android I think? https://github.com/koreader/koreader/issues/4471#issuecomment-453773155
https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerlink.lua#L143
At least is not working on my normal android 13 phone.

Open in browser is working here. Would be good a test case here.

**Comment by Frenzie** [comment]
> Copy text is unimplemented on Android I think?

It is and it works (on Android 4-12, anyway).

**Comment by Frenzie** [comment]
But as to the bug report, copy link is indeed broken on all platforms.

**Comment by Frenzie** [comment]
My bad, the bug report was about something subtly different. If no browser is launched I'd say it's more likely to be a firmware-related issue.

**Comment by hugleo** [comment]
> My bad, the bug report was about something subtly different. If no browser is launched I'd say it's more likely to be a firmware-related issue.

Is working on my onyx device with Android11, the device not the same indeed, but the android version is the same.
Now to go further only with proper logs.

**Comment by Frenzie** [comment]
Could it potentially be as simple as nothing being set under (Android) settings → apps → default apps → browser app?

**Comment by colinkarr** [comment]
Turns out I am at least only 50% an idiot :) I didn’t think to check whether einkbro (my only browser app) was being detected as a browser by android. Apparently it isn’t! So that part of the issue is a non-issue.
