### ISSUE TITLE
Crash on Reading statistics > Current book

### ISSUE THREAD

**Issue by MartinHammarstedt** [koreader/koreader#11564]
* KOReader version: 2024.03.1
* Device: Kobo Libra H2O

#### Issue

KOReader crashes when opening Reading statistics > Current book for the book I just finished.

#### Steps to reproduce

This only happens for one of my books, so I don't know how to reproduce. The statistics screen worked just fine while reading the book, but after I marked it as finished, it crashes.

From checking the log, it seems like it crashes when trying to parse the date I marked the book as finished, i.e. `self.ui.doc_settings:readSetting("summary").modified`. The problem is that there is no modified date for this book:
```
    ["summary"] = {
        ["status"] = "complete",
    },
```
I see by looking at the same section for other books that there usually is a "modified" field there.
I marked the book as finished by selecting the option in the menu that pops up after finishing a book.

##### `crash.log`

<details>
  <summary>crash.log</summary>

```
./luajit: frontend/datetime.lua:314: attempt to index local 'datetime_string' (a nil value)
stack traceback:
	frontend/datetime.lua:314: in function 'stringToSeconds'
	plugins/statistics.koplugin/main.lua:1669: in function 'getCurrentStat'
	plugins/statistics.koplugin/main.lua:1308: in function 'callback'
	frontend/ui/widget/touchmenu.lua:921: in function 'onMenuSelect'
	frontend/ui/widget/touchmenu.lua:216: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:907: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1436: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1536: in function 'handleInput'
	frontend/ui/uimanager.lua:1580: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x000140cd
```
</details>

**Comment by hius07** [comment]
Currently we set the `modified` field on opening a new book, so normally every book should have it.
Looks like this book was opened a long ago, when we didn't set this field yet.
Thank you, this should be fixed.

**Comment by MartinHammarstedt** [comment]
I transferred the book to my e-reader (and opened it for the first time) just two days ago, so something must have gone wrong.
