### ISSUE TITLE
Issue with "left pages number"

### ISSUE THREAD

**Issue by ghost** [koreader/koreader#11561]
* KOReader version: 2024.03.1 (Latest)
* Device: PocketBook 633 Color

I enabled the function to show only as many pages as in the physical book.

And I ran into this problem:
In the status bar it shows the same on different indicators, that is, it shows only one thing correctly - the current page in the book.

And the same number is shown in “how many pages are left until the end of the book”, although there should be a different number, a different indicator.

I hope I explained clearly...

The photo shows and makes it clear what the problem is (circled in red)

![IMG_20240317_123531.jpg](https://github.com/koreader/koreader/assets/119916135/e584e586-852d-4fe4-8841-31b5cb821f12)

How to fix this problem? Can you help me?
Please fix it!!!

I adore KOReader!

**Comment by poire-z** [comment]
> I enabled the function to show only as many pages as in the physical book.

I think you mean `Reference pages > Use reference page numbers`.

And indeed, when this is enabled, both items show the same thing:

https://github.com/koreader/koreader/blob/5d2782ddfefe63ca2007c4e9019bc74c0ec6efcb/frontend/apps/reader/modules/readerfooter.lua#L238-L244

https://github.com/koreader/koreader/blob/5d2782ddfefe63ca2007c4e9019bc74c0ec6efcb/frontend/apps/reader/modules/readerfooter.lua#L262-L271

The reason being that, even if this may be rare, `(Page labels might not be numbers)`, that is: they are just strings, they can be roman numerals, ie. you could get as current page: `xxviii / 243` - and we can't assume we can do the substraction, or that a substraction will give the right number of pages left in book.

Dunno if we should show something different for this when `pagemap:wantsPageLabels()`.

**Comment by Commodore64user** [comment]
> The reason being that, even if this may be rare, (Page labels might not be numbers), that is: they are just strings, they can be roman numerals, ie. you could get as current page: xxviii / 243 - and we can't assume we can do the substraction, or that a substraction will give the right number of pages left in book.

What if you parse the string? If it is an integer you convert it to such and perform the arithmetic, if not then just display the label/string, i.e xxviii / 243 or even just xxviii.

**Comment by poire-z** [comment]
It might give the right result in most books - but it's possible it doesn't: current and last pagelabels may be string that resolve to numbers, but it's possible they don't relate, one being in a counting sequence, the last one in another.
The right thing to do, that would work in all cases and give a more proper account of pages left, is probably to count the number of page label slots or use the index in that array of page labels, and substract these.
(I think I mentionned something like that in another issue related to "reference pages", maybe something about getting them for the top status bar.)

**Comment by Commodore64user** [comment]
just thinking out loud here, but I was also thinking, maybe one could use the last integer found in the array as the last page, so if you have something like `page_array = {i ,ii, iii, iv, 1, 2, 3, 4, 5, v, vi, vii}` you would say you are in page `1/5` and there are `5-1` pages missing.
