### ISSUE TITLE
dark mode makes picture in book negative (inverted)

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#11574]
* KOReader version: 2024.03.1 Latest
* Device: PocketBook 633

I turn on the dark mode and starting reading the book, the first page is with the cover of the book.
The picture inside the book became negative (inverted) anyway (see photos)

It seems that in the settings I turn on invert images - it’s still a negative image, then I turn off the function - it’s still a negative image, not a real color one! 

PHOTOS DESCRIBES PROBLEM
![IMG_20240319_210825.jpg](https://github.com/koreader/koreader/assets/119916135/e3bf0733-fda1-4f42-8720-50a939aeb9de)

![IMG_20240319_210759.jpg](https://github.com/koreader/koreader/assets/119916135/85095725-ac27-4422-848b-eaae48e8b90a)

Help me fix it please.
Please fix it in the new version.

**Comment by Frenzie** [comment]
I don't think MuPDF (easily) offers that through its API, but if it does it's still something that should probably be off by default (e.g., the whole document might consist of images, the images might count on transparency so you get black on black, etc.).

Interested parties could start investigating around `fz_invert_pixmap` and `fz_gamma_pixmap`.

**Comment by poire-z** [comment]
OK, the fix looks easy, will push that in the coming days.
```diff
--- a/crengine/src/lvdocview.cpp
+++ b/crengine/src/lvdocview.cpp
@@ -1161,6 +1161,7 @@ void LVDocView::drawCoverTo(LVDrawBuf * drawBuf, lvRect & rc) {
                        dst_dy = imgrc.height();
                //CRLog::trace("drawCoverTo() - drawing image");
         LVColorDrawBuf buf2(src_dx, src_dy, 32);
+        buf2.setInvertImages(drawBuf->getInvertImages());
         buf2.Draw(imgsrc, 0, 0, src_dx, src_dy, true);
         drawBuf->DrawRescaled(&buf2, imgrc.left + (imgrc.width() - dst_dx) / 2,
                 imgrc.top + (imgrc.height() - dst_dy) / 2, dst_dx, dst_dy, 0);
```
