### ISSUE TITLE
Cover image cannot be displayed

### ISSUE THREAD

**Issue by Huahddd** [koreader/koreader#11571]
* KOReader version: 2024.03,1
* Device: kobo forma

#### Issue
The cover image of some books cannot be displayed, and the text cover is displayed. (These e-book files themselves contain covers).
![IMG_20240319_232831_edit_4272241487613725](https://github.com/koreader/koreader/assets/142563515/7817599d-babb-4417-aab0-5d89c77d75fc)
![IMG_20240319_232842_edit_4272254521900181](https://github.com/koreader/koreader/assets/142563515/eebc90a9-7601-498b-9d44-38403b8b75e5)
![IMG_20240319_232857_edit_4272265283262680](https://github.com/koreader/koreader/assets/142563515/13640c7d-45b5-458b-b738-759b6e55e0ef)

I uploaded these ebooks.
[1.zip](https://github.com/koreader/koreader/files/14652909/1.zip)

**Comment by Frenzie** [comment]
They seem to vary a bit. Some mention some explicit things (though note it's not referring to the image directly).

```xml
<reference type="cover" title="封面" href="Text/%2A%2A%2A%7C%3A%7C%2A_%7C%7C_%3A%3A%3A%7C_%3A%2A_%3A.xhtml"/>
```

While others don't do anything other than:
```xml
    <svg xmlns="http://www.w3.org/2000/svg" height="100%" preserveAspectRatio="xMidYMid meet" version="1.1" viewBox="0 0 600 905" width="100%" xmlns:xlink="http://www.w3.org/1999/xlink">
      <image height="905" width="600" xlink:href="../Images/image00168.jpeg"></image>
    </svg>
```

I don't know if @poire-z will want to do anything with those, but some experimental patches in the general direction do exist. They wouldn't work on these files though.

**Comment by poire-z** [comment]
There was some work to parse the first docfragment for a cover, that didn't make it to crengine: https://github.com/koreader/koreader/pull/11491#issuecomment-1962947041
just because it wasn't really needed.
It may work with some of these books, from the snippets you pasted - haven't checked yet.

**Comment by Frenzie** [comment]
All of them show now. :+1: 
![image](https://github.com/koreader/koreader/assets/202757/9a425252-d972-4378-aa07-fb83cf4dd619)
