### ISSUE TITLE
FR: [Make the quote highlight line thicker]

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#11581]
I really like the highlight line, unlike other options. 

But there is a minus: it is too thin and therefore too hard to see.

![IMG_20240321_144738.jpg](https://github.com/koreader/koreader/assets/119916135/1db9a559-d5f5-49bc-86a5-ac2f483f5a90)

Can you make it bolder and more contrasting?  Can you make it customizable?

(1) I would highlight it in gray, but I don’t like the fact that there is no empty space between the lines, like in the Kindle. (2) And it’s a pity that there is no color highlighting... These two options are very necessary ;(((

**Comment by Huahddd** [comment]
I'm also looking forward to this feature

**Comment by Huahddd** [comment]
The current line drawing function is too thin.

**Comment by Commodore64user** [comment]
the underline is currently set to "medium" which does look a bit on the thinner side. Could be set to 'thick' without any issues so long as maintainers are okay with it.

pro tip: next time, consider not infantilising your own post (all those emojis), so as to make people more likely to help you.

**Comment by offset-torque** [comment]
**THICK** version in **Commodore64user**'s post  looks ideal. 
+1 vote for that one.

**Comment by poire-z** [comment]
I guess any thickness may also depend on the font size (or the line height, font-internal or user set, but this is quite complicated). A % of the font size would make it consistent whether a small or large font size is used.
(And the gray color does not help with noticability :))

**Comment by Commodore64user** [comment]
Here is a little test of the highlights working as they do on kindle firmware...

![IMG_5398](https://github.com/koreader/koreader/assets/97603719/d0a5ec30-e1db-4e7e-b1c8-9f204a558076)

**Comment by Commodore64user** [comment]
> I guess any thickness may also depend on the font size (or the line height, font-internal or user set, but this is quite complicated). A % of the font size would make it consistent whether a small or large font size is used. (And the gray color does not help with noticability :))

I tried it with 1/8 of height line, works fine. But seems a bit arbitrary so if you guys have a bigger (smaller) number in mind... For context at size 20, that would be 2.5 (pixels??? I think or whatever that measurement is)

**Comment by hius07** [comment]
> highlights working as they do on kindle firmware

This was rejected some time ago.

**Comment by poire-z** [comment]
> This was rejected some time ago.

Yes, in #10416 (opened by @ZHANYLone too ), for all the good reasons explained there.

**Comment by Commodore64user** [comment]
> > highlights working as they do on kindle firmware
> 
> This was rejected some time ago.

Candidate for user patch then

**Comment by ZHANYLone** [comment]
> Here is a little test of the highlights working as they do on kindle firmware...
> 
> ![IMG_5398](https://github.com/koreader/koreader/assets/97603719/d0a5ec30-e1db-4e7e-b1c8-9f204a558076)
> 

Can you make this as a userpatch or plugin (or how to name this)?.. 
I need space between the lines like in kindle so bad 😞

**Comment by poire-z** [comment]
[2-drawSeparatedHighlightLines.lua.txt](https://github.com/koreader/koreader/files/14968160/2-drawSeparatedHighlightLines.lua.txt)
Remove the .txt extension, create koreader/patches/, put the file in there, test, edit `VSPACE = 1` to 2, 3, 4... until you get enough space.

```lua
local ReaderView = require("apps/reader/modules/readerview")

-- This is removed from the top AND the bottom, so separation is twice that.
local VSPACE = 1

ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
    local xrect = rect:copy()
    xrect.y = xrect.y + VSPACE
    xrect.h = xrect.h - 2* VSPACE
    ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
end
```

**Comment by ZHANYLone** [comment]
> ~~[2-drawSeparatedHighlightLines.lua.txt](https://github.com/koreader/koreader/files/14968160/2-drawSeparatedHighlightLines.lua.txt)~~
> Updated: [2-drawSeparatedHighlightLines.lua.txt](https://github.com/koreader/koreader/files/14968182/2-drawSeparatedHighlightLines.lua.txt)
> 
> Remove the .txt extension, create koreader/patches/, put the file in there, test, edit `VSPACE = 1` to 2, 3, 4... until you get enough space.
> 
> ```lua
> local ReaderView = require("apps/reader/modules/readerview")
> 
> -- This is removed from the top AND the bottom, so separation is twice that.
> local VSPACE = 1
> 
> ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
> ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
>     if drawer ~= "lighten" and drawer ~= "invert" then
>         return ReaderView_orig_drawHighlightRect(self, bb, _x, _y, rect, drawer, draw_note_mark)
>     end
>     local xrect = rect:copy()
>     xrect.y = xrect.y + VSPACE
>     xrect.h = xrect.h - 2* VSPACE
>     ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
> end
> ```

Sorry for being annoying.
But one question:
How to set that number to look almost like a kindle? Most likely to kindle itself 
I think maybe 7?

**Comment by poire-z** [comment]
That's for you to try & test and find out the `VSPACE =` value that you like, with the normal font size you use (this patch won't adapt when you switch to a smaller or larger font size).

**Comment by skylarsoulmate** [comment]
> That's for you to try & test and find out the `VSPACE =` value that you like, with the normal font size you use (this patch won't adapt when you switch to a smaller or larger font size).

Can someone make the Full userpatch with auto adaptation when I change font or leading?

**Comment by poire-z** [comment]
You open the file you previously downloaded in some text editor, and you replace its content with the code I gave above.
As for the factor, _you_ test how it is with my 0.075, and if it's too large or narrow, you reduce or increase this 0.075 to 0.065 or 0.085. _You_ choose something, I have no idea how it is on a real Kindle.
Play, try, test, learn.

**Comment by skylarsoulmate** [comment]
> You open the file you previously downloaded in some text editor, and you replace its content with the code I gave above.
> As for the factor, _you_ test how it is with my 0.075, and if it's too large or narrow, you reduce or increase this 0.075 to 0.065 or 0.085. _You_ choose something, I have no idea how it is on a real Kindle.
> Play, try, test, learn.

THANK YOU VERY MUCH 😊

**Comment by skylarsoulmate** [comment]
> You open the file you previously downloaded in some text editor, and you replace its content with the code I gave above.
> As for the factor, _you_ test how it is with my 0.075, and if it's too large or narrow, you reduce or increase this 0.075 to 0.065 or 0.085. _You_ choose something, I have no idea how it is on a real Kindle.
> Play, try, test, learn.

Do I need to delete your lines with simple text instructions (not code) in the file? Or just leave them here?

**Comment by poire-z** [comment]
You remove everything from the orignal file.
You just copy and paste my new code as-is.
(My instructions in the new code, let them, they are comments (following `--`, which means "start of comment", the code will ignore them.)

**Comment by skylarsoulmate** [comment]
> You remove everything from the orignal file.
> You just copy and paste my new code as-is.
> (My instructions in the new code, let them, they are comments (following `--`, which means "start of comment", the code will ignore them.)
> 

Sorry, one more question. I tried the userpatch, but there is one problem. The space between the lines is too small like 1 mm, when I change ur code from 0.075 to 0.045 or 0.095 - nothing changes. 
In the previous userpatch I changed VSpace line from 1 to 9 and it was much better looking than 1. Can I change something in new code to make more space between lines?

**Comment by poire-z** [comment]
(Got a github mail, with a comment I don't see above. I assume you solved the problem and deleted that comment?)

**Comment by skylarsoulmate** [comment]
> (Got a github mail, with a comment I don't see above. I assume you solved the problem and deleted that comment?)

Yes, sorry. I think I solved the problem.
I wanna ask you now, did the code adapt space between lines when I change leading too or only it adapting when I change font size?

**Comment by poire-z** [comment]
Just the font size. Which means that if you change "interilne spacing", the hole will stay the same. Which I think.
I have no idea how it should adapt vs. the interline spacing (which is a %). I such at maths, but one could probably do something with it, like this (not test, no idea what this can give):
```lua
        local font_size = Screen:scaleBySize(self.ui.font.configurable.font_size)
        local line_spacing_pct = self.configurable.line_spacing * (1/100) 
        VSPACE = math.ceil(font_size * 0.075 * line_spacing_pct)
            -- so VPACE gets bigger if that line_spacing gets larger than 100%, maybe it needs a factor too
```

**Comment by skylarsoulmate** [comment]
> Just the font size. Which means that if you change "interilne spacing", the hole will stay the same. Which I think.
> I have no idea how it should adapt vs. the interline spacing (which is a %). I such at maths, but one could probably do something with it, like this (not test, no idea what this can give):
> ```lua
>         local font_size = Screen:scaleBySize(self.ui.font.configurable.font_size)
>         local line_spacing_pct = self.configurable.line_spacing * (1/100) 
>         VSPACE = math.ceil(font_size * 0.075 * line_spacing_pct)
>             -- so VPACE gets bigger if that line_spacing gets larger than 100%, maybe it needs a factor too
> ```

I need to add these lines to the first adapt userpatch, right?

**Comment by poire-z** [comment]
You need to replace the 2 similar lines with these 4 lines.
You also need to try to understand what these bits of code do, even if you're not a programmer, it's simple arithmetic.
You need to try things, if you do wrong, if it breaks it will tell you, and you can restart from scratch by copy & pasting my original bits.

**Comment by poire-z** [comment]
Ok, I made a typo :/ sorry, so the crash.
The full patch is:
```lua
local ReaderView = require("apps/reader/modules/readerview")
local Screen = require("device").screen

ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
    if drawer ~= "lighten" and drawer ~= "invert" then
        return ReaderView_orig_drawHighlightRect(self, bb, _x, _y, rect, drawer, draw_note_mark)
    end
    local VSPACE
    if self.ui.font then -- CreDocument
        local font_size = Screen:scaleBySize(self.ui.font.configurable.font_size)
        local line_spacing_pct = self.ui.font.configurable.line_spacing * (1/100)
        -- VSPACE = math.ceil(font_size * 0.075) -- choose your preferred factor
        VSPACE = math.ceil(font_size * 0.075 * line_spacing_pct)
        -- I guess we may not care about line spacing
    else
        -- I have no idea how font size works widh PDF
        VSPACE = 1
    end
    local xrect = rect:copy()
    xrect.y = xrect.y + VSPACE
    xrect.h = xrect.h - 2* VSPACE
    ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
end
```
There's still not much differences when you increase/decrease, so my simple mathematics may not be enough. But again, I don't know how you expect it to change with interline space % (and I don't really want to know :)).

**Comment by Commodore64user** [comment]
I believe i was using something like,

```lua

xrect.y = xrect.y + 1
xrect.h = xrect.h - xrect.h/8

```

when i tested it. Or something like that

**Comment by skylarsoulmate** [comment]
> Ok, I made a typo :/ sorry, so the crash.
> The full patch is:
> ```lua
> local ReaderView = require("apps/reader/modules/readerview")
> local Screen = require("device").screen
> 
> ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
> ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
>     if drawer ~= "lighten" and drawer ~= "invert" then
>         return ReaderView_orig_drawHighlightRect(self, bb, _x, _y, rect, drawer, draw_note_mark)
>     end
>     local VSPACE
>     if self.ui.font then -- CreDocument
>         local font_size = Screen:scaleBySize(self.ui.font.configurable.font_size)
>         local line_spacing_pct = self.ui.font.configurable.line_spacing * (1/100)
>         -- VSPACE = math.ceil(font_size * 0.075) -- choose your preferred factor
>         VSPACE = math.ceil(font_size * 0.075 * line_spacing_pct)
>         -- I guess we may not care about line spacing
>     else
>         -- I have no idea how font size works widh PDF
>         VSPACE = 1
>     end
>     local xrect = rect:copy()
>     xrect.y = xrect.y + VSPACE
>     xrect.h = xrect.h - 2* VSPACE
>     ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
> end
> ```
> There's still not much differences when you increase/decrease, so my simple mathematics may not be enough. But again, I don't know how you expect it to change with interline space % (and I don't really want to know :)).

Thank you, I will try it soon.
I think that when the leading increases, then the distance between the highlighted lines should increase, and when it decreases, then the distance between the lines decreases too.

**Comment by skylarsoulmate** [comment]
> I believe i was using https://github.com/koreader/koreader/issues/11581#issuecomment-2016138902 something like,
> 
> ```lua
> 
> xrect.y = xrect.y + 1
> xrect.h = xrect.h - xrect.h/8
> 
> ```
> 
> when i tested it. Or something like that

Should I change the above code with your lines? Or are you just thinking?

**Comment by skylarsoulmate** [comment]
> Ok, I made a typo :/ sorry, so the crash.
> The full patch is:
> ```lua
> local ReaderView = require("apps/reader/modules/readerview")
> local Screen = require("device").screen
> 
> ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
> ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
>     if drawer ~= "lighten" and drawer ~= "invert" then
>         return ReaderView_orig_drawHighlightRect(self, bb, _x, _y, rect, drawer, draw_note_mark)
>     end
>     local VSPACE
>     if self.ui.font then -- CreDocument
>         local font_size = Screen:scaleBySize(self.ui.font.configurable.font_size)
>         local line_spacing_pct = self.ui.font.configurable.line_spacing * (1/100)
>         -- VSPACE = math.ceil(font_size * 0.075) -- choose your preferred factor
>         VSPACE = math.ceil(font_size * 0.075 * line_spacing_pct)
>         -- I guess we may not care about line spacing
>     else
>         -- I have no idea how font size works widh PDF
>         VSPACE = 1
>     end
>     local xrect = rect:copy()
>     xrect.y = xrect.y + VSPACE
>     xrect.h = xrect.h - 2* VSPACE
>     ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
> end
> ```
> There's still not much differences when you increase/decrease, so my simple mathematics may not be enough. But again, I don't know how you expect it to change with interline space % (and I don't really want to know :)).

Can you add one small change or addition? Suppose that as the leading increases, the empty distance between the highlighted lines also increases and when the leading decreases, let the empty space between the lines decrease too. Please 🥺

**Comment by Commodore64user** [comment]
> ```lua
> 
> xrect.y = xrect.y + xrect.h/16 + 1
> xrect.h = xrect.h - xrect.h/8
> 
> ```

Use that instead of the ones with VSPACE

**Comment by skylarsoulmate** [comment]
> > ```lua
> > xrect.y = xrect.y + xrect.h/16 + 1
> > xrect.h = xrect.h - xrect.h/8
> > ```
> 
> Use that instead of the ones with VSPACE

all this time I tried to make a new addition to his code using AI cause I don't know how to code. And Copilot AI made this code for my requests. Can you check this and tell me which better in using and which is more beautiful and which is more similar to the Kindle experience, please? Please check this my code:

``local ReaderView = require("apps/reader/modules/readerview")
local Screen = require("device").screen

ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
    if drawer ~= "lighten" and drawer ~= "invert" then
        return ReaderView_orig_drawHighlightRect(self, bb, _x, _y, rect, drawer, draw_note_mark)
    end
    local font_size = Screen:scaleBySize(self.ui.font.configurable.font_size)
    local line_spacing_pct = self.ui.font.configurable.line_spacing * (1/100)
    -- Убедимся, что line_spacing_pct инициализирована
    line_spacing_pct = line_spacing_pct or 1
    local VSPACE = math.ceil(font_size * 0.14 * line_spacing_pct)
    -- Увеличиваем VSPACE при увеличении интерльяжа
    if line_spacing_pct > 1 then
        VSPACE = VSPACE + (font_size * (line_spacing_pct - 1) * 0.05)
    end
    local xrect = rect:copy()
    xrect.y = xrect.y + VSPACE
    xrect.h = xrect.h - 2 * VSPACE
    ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
end
``

**Comment by skylarsoulmate** [comment]
> > ```lua
> > xrect.y = xrect.y + xrect.h/16 + 1
> > xrect.h = xrect.h - xrect.h/8
> > ```
> 
> Use that instead of the ones with VSPACE

is that to which I reply is better than mine?

**Comment by Commodore64user** [comment]
this is the most beautiful user patch in the land:

```lua
local ReaderView = require("apps/reader/modules/readerview")
local Screen = require("device").screen

ReaderView_orig_drawHighlightRect = ReaderView.drawHighlightRect
ReaderView.drawHighlightRect = function(self, bb, _x, _y, rect, drawer, draw_note_mark)
    if drawer ~= "lighten" and drawer ~= "invert" then
        return ReaderView_orig_drawHighlightRect(self, bb, _x, _y, rect, drawer, draw_note_mark)
    end
    local xrect = rect:copy()
    xrect.y = xrect.y + xrect.h/16 + 1
    xrect.h = xrect.h - xrect.h/8
    ReaderView_orig_drawHighlightRect(self, bb, _x, _y, xrect, drawer, draw_note_mark)
end
```

it is so beautiful indeed, I am now running it myself. Its beauty also inspired me to take up poetry, so I can write beautiful verses to it ;)

**Comment by jonnyl2** [comment]
Thank you for this patch. Could this by chance be adapted to also apply to text selections, and not just finished highlights?
