### ISSUE TITLE
Just a question about the DocFragment[xxxx] numbers

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#11585]
[This post](https://www.mobileread.com/forums/showpost.php?p=4408093&postcount=144) made me think again for a way to sort highlights that are made with different devices and have different page numbers.
I know about the Adobe's absolute page number (which I think are not that smart), but there is nothing about them in the book's metadata.
And I was wondering if there is another way.

So, here is the question:
Are the DocFragment[xxxx] numbers the same for all devices, regardless of the text formatting?
Because if they are, I could use them to sort the highlights by them, if someone needs to see them with an absolute order. 🥳 

Any info/idea will be appreciated..

**Comment by poire-z** [comment]
> Are the DocFragment[xxxx] numbers the same for all devices, regardless of the text formatting?

Yes, these are the same and static: they follow
```xml
<spine toc="ncx">
 <itemref idref="cover"/>      => DocFragment[1]
 <itemref idref="intro"/>      => DocFragment[2]
 <itemref idref="chapter1"/>   => DocFragment[3]
...
</spine>
```

> Because if they are, I could use them to sort the highlights by them, if someone needs to see them with an absolute order. 

You would then only have them ordered by chapter - but you could still have them mis-ordered inside a same chapter/DocFragment.
Anyway, you can't accurately use these xpointers/xpath for sorting. You can't know (from the outside - while a running KOReader/crengine with that book open can) in which order these 2 comes:
```
/body/DocFragment[12]/body/p[27]/text()[2].223   -- The 27th P among all the Ps.
/body/DocFragment[12]/body/div[14]/text()[1].3   -- The 14th DIV among all the DIVs
```
Best to work with @hius07 on #11563 and see how he can help you. (ie. saving a the position in % on the whole document height, ie 0.13214932 < 0.133432432)

**Comment by noembryo** [comment]
>Best to work with @hius07 on #11563 and see how he can help you. (ie. saving a the position in % on the whole document height, ie 0.13214932 < 0.133432432)

This is a very helpful idea.
I do watch #11563 waiting for the first changes to stabilize.. 🍷

**Comment by hius07** [comment]
We can merge https://github.com/koreader/koreader/pull/11553, until further progress of new annotations.

**Comment by noembryo** [comment]
>We can merge #11553, until further progress of new annotations.

Is this going to do a page renumbering with every new entry?

>Update highlight page numbers (table keys):
-on closing the document
-on exporting current document highlights

If not, is reading the `metadata` with KOHighlights after some highlighting and before closing the document, will have wrong numbering?
Of course, at that moment, even the file might not be up to date.
Just asking out of curiosity.

Anyway, this might solve the ordering for pages on a single device for sure.

**Comment by hius07** [comment]
> Is this going to do a page renumbering with every new entry?

No.


> If not, is reading the `metadata` with KOHighlights after some highlighting and before closing the document, will have wrong numbering?

Currently new highlights are saved to sdr not immediately, but according to the setting "Save book metadata" (period of time or on closing the document), along with other doc settings.
We can add updating page numbers to every saving (while the document is opened).

**Comment by noembryo** [comment]
>We can add updating page numbers to every saving (while the document is opened).

Yes, this will be really helpful..
