### ISSUE TITLE
Unable to Push reading progress from Android phone (F-Droid)

### ISSUE THREAD

**Issue by qupufu** [koreader/koreader#11582]
* KOReader version: v2024.03.1 (from F-Droid)
* Device: Pixel 4a

#### Issue
I'm unable to push my progress from my phone to sync it with my Kobo Libra

#### Steps to reproduce
Unsure

I'm also having trouble figuring out how to dump my log, sorry

**Comment by Frenzie** [comment]
The server is down at the moment. It should be back up in a few days.

**Comment by qupufu** [comment]
Is there a way to know if the server is down?

**Comment by qupufu** [comment]
Server is back up and working
