### ISSUE TITLE
FR: Display highlight text instead of note text

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11587]
When we add a note to a highlighted text, the text of the note is displayed in the bookmarks list instead of the highlighted text. Could there be an option so that the highlighted text continues to be displayed in the bookmarks list, even after a note has been added to it?

Thank you!

**Comment by jonnyl2** [comment]
I'd also be in support of this proposal, but I think even better would be if both was displayed, e.g. like this:

<img width="537" alt="image" src="https://github.com/koreader/koreader/assets/95502269/7914aef9-ebcc-4adc-9276-84511e3c57a3">

For example, up to 50% of the space could be reserved for the note+time stamp (if applicable), and the first half (+whatever space remains) would be for the highlighted text.

**Comment by hius07** [comment]
We will have soon:

![3](https://github.com/koreader/koreader/assets/62179190/baacadc2-a61b-4268-89c3-c903ffb944c0)

**Comment by poire-z** [comment]
(Will review your other PR when I have more time) but just a quick note about this last screenshot.
It feels it would be clearer as (if that's what indeed really happens):
```
[ ] highlighted text only
[ ] highlighted text and note
[x] note, or highlighted text
```

**Comment by hius07** [comment]
Added in https://github.com/koreader/koreader/pull/11563.
