### ISSUE TITLE
Pure black and white function adjustment

### ISSUE THREAD

**Issue by Huahddd** [koreader/koreader#11589]
**Does your feature request involve difficulty completing a task? Please describe.**
The style adjustment has an option to force text and borders to black, and remove the background. But many times I only need one of these features, which is to change the text to black and white or remove the background.

**Describe the solution you'd like**
I would like to ask if it is possible to separate the two functions of this style adjustment into two options.

**Additional context**
![1](https://github.com/koreader/koreader/assets/142563515/0b681669-a389-4d8b-8843-dbcfdff66328)

**Comment by poire-z** [comment]
Dunno if we need to split it, other opinions welcome.

But my point is that you don't really need us to do it, you can help yourself by making your own "user style tweaks", which will be available in the submenu.
![image](https://github.com/koreader/koreader/assets/24273478/d5f63951-869c-45ee-bf40-bd923d7a5521)

![image](https://github.com/koreader/koreader/assets/24273478/ee84f4e8-c28f-4d3e-8a63-45b412f7fd53)

![image](https://github.com/koreader/koreader/assets/24273478/77cd2742-23b5-4569-9773-3304ae068a44)

You just need to create such files in that directory yourself.

**Comment by Huahddd** [comment]
> Dunno if we need to split it, other opinions welcome.
> 
> But my point is that you don't really need us to do it, you can help yourself by making your own "user style tweaks", which will be available in the submenu. ![image](https://private-user-images.githubusercontent.com/24273478/316307879-d5f63951-869c-45ee-bf40-bd923d7a5521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODM1NjQsIm5iZiI6MTcxMTI4MzI2NCwicGF0aCI6Ii8yNDI3MzQ3OC8zMTYzMDc4NzktZDVmNjM5NTEtODY5Yy00NWVlLWJmNDAtYmQ5MjNkN2E1NTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDEyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODA5NmZkOTQ1YTgyOTEwMDFjNjRjYWNkMjdhNGFmYTNkOTdiZTI5ODM4YTEyMzRjZmZhMzE5YTAwYmI3MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G14lWwcUeedHtzcpjDkXJJ0z182c9SXtnLYCHVAufjo)
> 
> ![image](https://private-user-images.githubusercontent.com/24273478/316307899-ee84f4e8-c28f-4d3e-8a63-45b412f7fd53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODM1NjQsIm5iZiI6MTcxMTI4MzI2NCwicGF0aCI6Ii8yNDI3MzQ3OC8zMTYzMDc4OTktZWU4NGY0ZTgtYzI4Zi00ZDNlLThhNjMtNDViNDEyZjdmZDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDEyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YzZmYWE3NTcxMjY3YjBhYmVkMzZlMDM2YTUwM2EyYjg0YWY2NjRkMjdhZmI0NDEzOWFlZGMyODUyOTI0ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.btRc4IDrWUpoOwt66CsJHi9enZJlaarex9N6q3ajFZc)
> 
> ![image](https://private-user-images.githubusercontent.com/24273478/316307984-77cd2742-23b5-4569-9773-3304ae068a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODM1NjQsIm5iZiI6MTcxMTI4MzI2NCwicGF0aCI6Ii8yNDI3MzQ3OC8zMTYzMDc5ODQtNzdjZDI3NDItMjNiNS00NTY5LTk3NzMtMzMwNGFlMDY4YTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDEyMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNjMyODg1NzJjZDZiYWYzNzViODVhYTIzMDFiMmQ2ODZhOTdhZGVmNjNmOTFlZGI2MmU1MGNlZjY3NjY0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qvrT8EiSWbaYv1Ut5oTgHtTpvJrlgh-z21RLoe3ksZU)
> 
> You just need to create such files in that directory yourself.

oh! I forgot about this feature, thanks for the reminder.

**Comment by Frenzie** [comment]
Closing then. :-)
