### ISSUE TITLE
FR: Paginated Status Bar, with multiple statuses per page

### ISSUE THREAD

**Issue by sdananjay93** [koreader/koreader#11590]
**Does your feature request involve difficulty completing a task? Please describe.**
The status bar currently either shows all of them together or shows them one by one. Having a combination of this might result in a cleaner look, where we can have groupings such as 
Page 1 - Time | Battery | WiFi Status
Page 2 - Time | Page number | Chapter Time to read
Page 3 - Book name | Chapter Name

**Describe the solution you'd like**
Move the current checkboxes for the settings under three similar sub settings (Page 1, Page 2, Page 3). 
In each page we can check / uncheck whatever statuses we want to see. 
The footer switches between pages on tap, similar to when we only want to see one item at a time.

**Describe alternatives you've considered**
1. A user patch which uses the "Custom text placeholder" and another lesser used options. 
2. In the user patch we get all of the required status, and concatenate them together in a string
And display it in the status.

Also, considering developing this as a plugin.

**Additional context**

**Comment by Huahddd** [comment]
Have you considered distributing the content of the status bar on both sides instead of only in the middle or one side.

**Comment by Commodore64user** [comment]
Currently there are some options to have a nice looking status bar. For instance, this one displays: battery level, brightness, wifi, time, pages, pages left in chapter and chapter name. 

![Image](https://github.com/koreader/koreader/assets/97603719/3a62c91d-dc63-48b1-ac55-8a07f5b52078)

now you might be wondering, where is the battery indicator? Well most of them are hidden when not necessary `Hide empty items`. For example, the wifi one will only be there when there is an active connection, the battery level will only appear when the device is in the low 20s or below `Hide battery status if level is higher than: 25%`, brightness when the screen is being lit (I think I could actually do without this one) and the chapter is set to use up to 50% of screen real state.

As for having different ones for different pages, I guess it would be more logical to have TWO max, odd and even type behaviour. But again you could also use the alt status bar and bottom one at the same time and have everything all at once.

**Comment by hius07** [comment]
> Are there any developer focused documentation available for anyone interesting in hacking the source code?

https://koreader.rocks/doc/

**Comment by poire-z** [comment]
> 1. User patch which hacks on top of existing readerFooter

You can do whatever you manage to do with a user patch, we don't need to know :)
Moreover, as it's for you, you can just hack in it what you want, you don't need to make any menu or stuff to allow free configuration.
Some recent one related to footer in #11512.

> 2. A plugin which takes over the status bar settings from the current Settings -> Status Bar

A plugin will probably not manage to hack or replace into our "core" ReaderFooter - and if it does, it would behave like a user-patch, so best to start as a user patch.
(Moreover, we won't probably accept it as a shipped plugin if it hacks our core feature.)

> 3. Edit ReaderFooter directly to support this?

We (I?) may not let you :)
Our ReaderFooter (and its related menu) is already complex and a mess. We don't really want to have it even more complex with 2 or 3 panels for checking and sorting items.
I also feel that your FR is a bit niche and won't be loved: one would need to tap or change page to see more - and the change of "geometry" or "text black density" between your 2 or 3 kinds would be distracting and attract the eyes more than a somehow stable single footer.

**Comment by poire-z** [comment]
> For egs: a How does :addToMenu(menu_items) automatically add items to the menu bar when I cannot find menu_items defined anywhere.

Modules registers themselves:
https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/apps/reader/modules/readermenu.lua#L559-L561
And the menu module calls each registered module's addToMainMenu by providing its single "menu_items"):
https://github.com/koreader/koreader/blob/ca8e9352ba962e48843cd1d86812e42bdade7708/frontend/apps/reader/modules/readermenu.lua#L184-L190

> Are there any developer focused documentation available for anyone interesting in hacking the source code?

Apart from the link given above, there is none but the source code - and there's no real alternative than reading that code and trying to understand how all this works :/

**Comment by sdananjay93** [comment]
@poire-z - Thank you for your detailed response. 
Option 3 - This was a personal change that I wanted to try out in my personal fork as a way to learn the inner workings of Lua and KOReader as an application. It was not intended to be an eventual PR 😅.

**Comment by offset-torque** [comment]
@sdananjay93 

> Have you considered distributing the content of the status bar on both sides instead of only in the middle or one side.

> Is this an existing feature, or are you referring to an implementation which does this?

Currently you can add a separator to divide status bar items into two groups (my current setup is like this).
Unfortunately this won't help with truncated chapter names.
Search for this in our user guide for how-to: **Using "Custom Text" item for status bar alignment**

**Comment by sdananjay93** [comment]
Closing as per solution in [12572](https://github.com/koreader/koreader/issues/12572)
