### ISSUE TITLE
InkPad X PRO. Android 8. Physical buttons (PgUp and PgDwn) inconsistent behavior

### ISSUE THREAD

**Issue by volatileman** [koreader/koreader#11599]
* KOReader version: 2024.03.1
* Device: PocketBook 1040D InkPad X PRO Mist Grey (PB1040D-M-WW)

#### Issue
When a book is opened in continuous view mode and the physical PgDwn or PgUp button is pressed the screen moves down or up two times and then all subsequent PgDwn or PgUp button clicks move the screen ones at a time as expected.
After some time (approx  1 min) I press  PgDwn or PgUp button once again and the screen moves two times again so I have to adjust it by clicking the opposing button.

#### Steps to reproduce
1. Open a book
2. Wait 1 min
3. Press PgDwn or PgUp button
4. Page scrolled two times
5. Press PgDwn or PgUp button
6. Page scrolled once
7. Wait 1 min
8. Goto step 3. Behavior is reproducible in the loop

### Expected behavior
Clicking physical buttons (PgUp and PgDwn) should scroll the page only once at any given time.

[crash.log](https://github.com/koreader/koreader/files/14790521/crash.log)

**Comment by Frenzie** [comment]
Probably related to suspend. Pinging @rjd22 for thoughts.

**Comment by rjd22** [comment]
> Probably related to suspend. Pinging @rjd22 for thoughts.

Yep sounds like something that has to do with the pocketbook going to sleep and sending the event twice when waking. No way to know for sure without replicating it tho.

**Comment by pazos** [comment]
I agree with you @Frenzie and @rjd22. It looks like and issue with cpu sleeping.

Since the device is android and not a genuine pocketbook @volatileman might want to try: "Settings-> Screen -> timeout -> keep screen on" and see if the issue can be reproduced there.

**Comment by volatileman** [comment]
@pazos I tried to use `timeout -> keep the screen on` and it didn't help. Sometimes when I open a book and immediately press the PgDwn or PgUp button it triggers two times scroll.
I installed an app https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en&gl=US
to see the key events and it showed some odd results. Below are the screenshots

![1710611282520_page-up_click](https://github.com/koreader/koreader/assets/104102414/ec9b1caa-81ed-4f40-a90f-e46bf5a7c349)
![1710611303141_page-down_click](https://github.com/koreader/koreader/assets/104102414/0fc7857a-35b0-4cb5-ae5e-eecb35a0ae2e)
![1710611317203_page-up_click](https://github.com/koreader/koreader/assets/104102414/d4b52113-4d70-4ccb-97e8-56282443789a)
![1710611345000_page-up_click](https://github.com/koreader/koreader/assets/104102414/37836d8b-3760-4b2f-8741-0d53842ccd2f)
![1710611373678_page-down_click](https://github.com/koreader/koreader/assets/104102414/3123733c-4ee4-474b-aa32-681884c9c73c)
![1710611424014_series_of_clicks](https://github.com/koreader/koreader/assets/104102414/b9c6f018-b157-43c4-b01b-4bc233166e01)
![1710611460838_series_of_clicks](https://github.com/koreader/koreader/assets/104102414/5e580a57-3ce5-419b-aeb4-3569f459b01e)

**Comment by volatileman** [comment]
@pazos `Settings-> Screen -> timeout -> keep screen on` didn't help. Sometimes when I open a book and press PgDown button it triggers the scroll two times. I installed this app https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en&gl=US and made screenshots for each button press to see the key events. 
[screenshots.zip](https://github.com/koreader/koreader/files/14806314/screenshots.zip) Maybe it could help.
Thanks,

**Comment by pazos** [comment]
> @pazos `Settings-> Screen -> timeout -> keep screen on` didn't help. Sometimes when I open a book and press PgDown or PgUp button it triggers the scroll two times. I installed this app https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en&gl=US and made screenshots for each button press to see the key events. [screenshots.zip](https://github.com/koreader/koreader/files/14806314/screenshots.zip) Maybe it could help. Thanks,

It helps, indeed. Please report the bug to Pocketbook and attach the same screenshots.zip. They will be able to fix the bug in a new firmware release.

We just do the expected thing, react to each key event that's forwarded by the system. As you can see there're plenty of repeated ones.

**Comment by volatileman** [comment]
I'll report a bug to Pocketbook
Thanks
