### ISSUE TITLE
Dictionary Render Problem

### ISSUE THREAD

**Issue by gwd0715** [koreader/koreader#11595]
* KOReader version: 2024.03.1
* Device: Kindle Oasis 9th generation

#### Issue
I used pyglossary to convert one of my .mdx dictionary to the koreader-supported filetype according to the instructions.
After I imported it into koreader, and here is what it looks like:
![Reader_2024-03-27_200839](https://github.com/koreader/koreader/assets/17922721/7e94eb0a-df7f-4157-8cb5-36fb72872d4c)

And then I read the dictionary support in wiki, and I tried sdcv in ssh, and here is the result:
<img width="1073" alt="image" src="https://github.com/koreader/koreader/assets/17922721/daf23893-4e48-48af-ad9f-a74e36bc9450">

After I format the code in editor, it looks like this:
<img width="544" alt="image" src="https://github.com/koreader/koreader/assets/17922721/e8f80e6c-62de-4824-b2ce-cf13d662d89d">

So my questions are:
1. why div tag is not treated as a block element? All the words are displayed in one line in koreader. But if I open the formatted html file with Mupdf, even though there's no css, all the paragraphs are correct. Here is the screenshot:
<img width="523" alt="image" src="https://github.com/koreader/koreader/assets/17922721/5a716b7b-0410-4e07-a99f-715211c63312">

2. What should I do, if I want to render this custom dictionary properly?  How should I write my lua file? And should I add a custom css file?(I tried some template lua files, but nothing works.)
Here is what I want to achieve:
<img width="648" alt="image" src="https://github.com/koreader/koreader/assets/17922721/b6e49222-f0da-4eda-9169-e0b3a4236e0e">

**Comment by Frenzie** [comment]
in the .ifo file change `sametypesequence=m` to `sametypesequence=h`.

**Comment by gwd0715** [comment]
> in the .ifo file change `sametypesequence=m` to `sametypesequence=h`.

I already did that. 
<img width="583" alt="image" src="https://github.com/koreader/koreader/assets/17922721/31c21576-458f-4f17-bf83-e0811554fac1">

**Comment by gwd0715** [comment]
> Did you also use css file next to your dictionary files? It is in the same Wiki place

no, not yet. I'd like to solve this "treat div as a block element and have paragraph style" problem first. Then, I'll start to add and custom my css.

**Comment by Frenzie** [comment]
I was misled by your second code screenshot in https://github.com/koreader/koreader/issues/11595#issue-2210717905 since the first clearly shows invalid XHTML while the second does not. Presumably you're seeing the fallback rendering.

**Comment by gwd0715** [comment]
> I was misled by your second code screenshot in [#11595 (comment)](https://github.com/koreader/koreader/issues/11595#issue-2210717905) since the first clearly shows invalid XHTML while the second does not. Presumably you're seeing the fallback rendering.

So you are saying that this converted version of this dictionary could not be render properly since this whole raw code is wrong? That means pyglossary didn't convert mdx to StarDict format in a right way?
<img width="1073" alt="image" src="https://github.com/koreader/koreader/assets/17922721/daf23893-4e48-48af-ad9f-a74e36bc9450">

**Comment by Frenzie** [comment]
I assume it didn't do much of anything to the HTML that was there. For your purposes it might potentially suffice to filter out that `<link>` (or change it to `<link/>` but since if you don't have any v.css…).

**Comment by gwd0715** [comment]
> I assume it didn't do much of anything to the HTML that was there. For your purposes it might potentially suffice to filter out that `<link>` (or change it to `<link/>` but since if you don't have any v.css…).

I just added`html = html:gsub('<link[:^>]*/>','')` in my lua file as you suggested. Still not working! :(
Frustrated.

**Comment by Frenzie** [comment]
If you paste it in some place like https://codebeautify.org/xmlvalidator it'll tell you what's invalid about it.

**Comment by gwd0715** [comment]
> If you paste it in some place like https://codebeautify.org/xmlvalidator it'll tell you what's invalid about it.

It says valid xml. However, I opened crash.log in koreader. It says:
<img width="916" alt="image" src="https://github.com/koreader/koreader/assets/17922721/32fa1ad5-23d1-4921-8395-fffeaed0454f">
What does that mean?

**Comment by Frenzie** [comment]
There is a variety of unquoted `class=p`, `class=c`, etc. in your screenshot. Does this pyglossary have an option to force its output through BeautifulSoup? It already uses it for a variety of things.

**Comment by Frenzie** [comment]
Glancing through their docs I don't see an option to fix HTML, but I do spot `-remove-html=tag1,tag2,tag3`. It might be worth trying it in exactly that form (that is, with fake tags instead of real tags assuming you want to keep those) to see if it fixes up the HTML as a side effect.

**Comment by gwd0715** [comment]
> Glancing through their docs I don't see an option to fix HTML,[1] but I do spot `-remove-html=tag1,tag2,tag3`. It might be worth trying it in exactly that form (that is, with fake tags instead of real tags assuming you want to keep those) to see if it fixes up the HTML as a side effect.
> 
> [1] To be clear it's fine as HTML. The problem is that we need XHTML for the moment.

In the end, I found the bad html problem was in my .mdx dictionary. I fixed it and converted it again. Now it works fine! 
Thank you so much for your patient support!

**Comment by Frenzie** [comment]
The next release will deal better with broken HTML, although of course broken HTML could also mean weirdly broken rendering.
