### ISSUE TITLE
History page should do `flashui` refresh on first display

### ISSUE THREAD

**Issue by dmalinovsky** [koreader/koreader#11602]
* KOReader version: 2024-03.1-32
* Device: Pocketbook Inkpad Color 3

#### Issue

Unlike FileBrowser, History doesn't refresh the screen when you open it. This is causing heavy ghosting on color devices, see the screenshot below.

<img src="https://github.com/koreader/koreader/assets/483357/aba3dbfe-1051-42f1-b070-becee6f2becc" width="40%">

With changes from https://github.com/koreader/koreader-base/pull/1755 it won't be a problem, if History page would do `flashui` refresh during its first render.

#### Steps to reproduce

I suspect it's impossible to reproduce with B&W devices.

**Comment by dmalinovsky** [comment]
@hius07, you were refactoring related files recently, perhaps you have some insights? I tried fixing it myself but got lost in the widget hierarchy and UI event handling. :)

**Comment by hius07** [comment]
The history is shown here:
https://github.com/koreader/koreader/blob/ee7c3ab551f320ff0095c276bdadfac77beeee69/frontend/apps/filemanager/filemanagerhistory.lua#L273
Is it what you are looking for? I would be happy to assist.
The same concerns Favorites I guess (have no color device to test).

**Comment by dmalinovsky** [comment]
> The same concerns Favorites I guess (have no color device to test).

No, Favorites are fine. They refresh the screen the same way the File Manager does.



> Is it what you are looking for? I would be happy to assist.

Looks like it, thanks! I'll experiment with "flashui" parameter.

**Comment by dmalinovsky** [comment]
Looks like it fixes the issue. Thanks again, @hius07!
