### ISSUE TITLE
CBZ files should honor `refresh_on_pages_with_images` setting

### ISSUE THREAD

**Issue by dmalinovsky** [koreader/koreader#11600]
* KOReader version: 2024-03.1-32
* Device: Pocketbook Inkpad Color 3

#### Issue

When paging through CBZ file, KOReader should flash on every page if "Always flash on pages with images" setting is ON.

Currently, it's only flashing if full refresh is set for "Every page". So if you read CBZ and then switch to ePub file, you have to turn "Every page" on and off depending of the file type.

#### Steps to reproduce

* Go to "E-ink Settings", set full refresh to "Never" and turn on "Always flash on pages with images". 
* Open any CBZ file and start paging down.
* KOReader doesn't do the full refresh, which leads to heavy ghosting.

**Comment by dmalinovsky** [comment]
Hmm, I guess it's only applicable for the color devices. What device do you use for manga, @mergen3107?

**Comment by dmalinovsky** [comment]
Looks like until there's a way to detect color content in the files, this change is too drastic. It can be an idea for the future.

**Comment by mergen3107** [comment]
I use Kindle Scribe
