### ISSUE TITLE
device:suspend does nothing

### ISSUE THREAD

**Issue by claus-von-gmx** [koreader/koreader#11612]
* KOReader version:V2020.03.2-260-ga4cfdf3f_2020-08-22
* Device: Opensuse Tumbleweed / Pocketbook Inkpad3pro / Pocketbook InkpadX

#### Issue 
Suspend is bound to a Tap (and Hold) corner action but does nothing 
#### Steps to reproduce
Bind device:suspend to a corner action - try to invoke it - nothing happens 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
@pazos You mean PB can't? It's not available in the AppImage so the OpenSUSE in the OP is a distraction afaict.

**Comment by pazos** [comment]
It can't: https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L31

`Device:canSuspend()` should be accurate on all platforms

**Comment by pazos** [comment]
ah, added in https://github.com/koreader/koreader/commit/893909146d6e406ca36c5f2d95b82526a4ed6167

No idea if it worked and/or still works. Pinging @rj22.

**Comment by rjd22** [comment]
@pazos if your device is not rooted it won't be able to suspend from screen touches. You will need to use your device button for that.

**Comment by Frenzie** [comment]
I was on mobile when I posted that one line (so I didn't know how to expand the selection), but the full context seems to account for that:

https://github.com/koreader/koreader/blob/dce92020c19c03c547ce62f88d7eef81f5374fa1/frontend/device/pocketbook/device.lua#L245-L254

**Comment by rjd22** [comment]
> I was on mobile when I posted that one line (so I didn't know how to expand the selection), but the full context seems to account for that:
> 
> https://github.com/koreader/koreader/blob/dce92020c19c03c547ce62f88d7eef81f5374fa1/frontend/device/pocketbook/device.lua#L245-L254

Honestly I've been thinking about removing the rooted code path. It doesn't give that much advantages and it's another thing to maintain and account for. Also rooting the pocketbook requires deep knowledge of your device and is risky. Chances are only a few people still use a rooted pocketbook.

**Comment by Frenzie** [comment]
I'm certainly not opposed to removing it, but for the record @claus-von-gmx did you root the device?

**Comment by pazos** [comment]
> but the full context seems to account for that

That's quite fishy, given OP report and https://github.com/koreader/koreader/blob/master/frontend/dispatcher.lua#L70

> Honestly I've been thinking about removing the rooted code path. It doesn't give that much advantages and it's another thing to maintain and account for. Also rooting the pocketbook requires deep knowledge of your device and is risky.

I wouldn't mind, too. But for now we're good removing the else branch in case OP report is valid (but how?)

**Comment by Frenzie** [comment]
Perhaps newer devices offer raw input without being root, or something like that. Or in any case the two don't necessarily feel connected to me. Perhaps there's an API to check if you have permission to `inkview.SendGlobalRequest(C.REQ_KEYLOCK)`?

**Comment by pazos** [comment]
Of course, it is invalid.

Closing
