### ISSUE TITLE
Dictionary not detected on PocketBook Verse Pro

### ISSUE THREAD

**Issue by p-czech** [koreader/koreader#11622]
* KOReader version: 2024.03.1
* Device: PocketBook Verse Pro

#### Issue
Dictionary Settings -> Manage dictionaries show 0.

Even when I downloaded my dictionaries in dict.dz formats and put them in applications/koreader/data/dict forlder, when I run my koreader app, and I go to dictionary settings, I have 0 dictionaries to manage.

#### Steps to reproduce
Connect device via USB
upload dict.dz file to applications/koreader/data/dict forlder
restart device
open koreader
go to Dictionary Settings
no dictionaries to manage
![image](https://github.com/koreader/koreader/assets/44318297/e638e1b4-0689-4cfd-ad7a-d078da7b6622)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by pazos** [comment]
Please follow https://github.com/koreader/koreader/wiki/Dictionary-support

**Comment by alemangui** [comment]
@pazos Same problem. I followed exactly the instructions in the link. Also attempted to install the dictionary from within the application.
