### ISSUE TITLE
Using any type of scroll keeps the previous row of text on the next page when reading a pdf.

### ISSUE THREAD

**Issue by MortalWombat-repo** [koreader/koreader#11630]
* KOReader version:2024.01
* Device:Kindle Paperwhite 4

#### Issue
I first experienced that issue on continuous mode, but playing around I see that it is presented in any mode.

Continue and margin adjustments only manage to reduce the continuation of previous text to one row at best.

Page overlap does not help anymore as after an update of a 2 years or more it was only allowed on paged mode.
Sometimes I manage to trick it but with each update it only becomes more stubborn.
If I use page overlap since I use grey out sometimes multiple pages can be greyed out and it disrupts my reading flow having to scroll through one or more empty pages.

Is there an lua option to make the next page start at the cutoff of the previous page?
I scanned through the entire device, read issues and the manual and I can't find anything.

#### Steps to reproduce
Open any pdf turn on continuous mode in landscape and scroll. Each time there is the text at the bottom repeated on the next page.

Switch to page mode use the page in portrait, depending on the margins sometimes the text is repeated too.
For visualization turn on page spacing.
Observe when scrolling that the line isn't staying fixed. When it should as each page is the same dimension.

#### Notes:
I think koreader starts the calculation from the bottom of the document and takes margins into consideration and there is no easy setting per chapter like in epub.

Hopefully there is an option of starting the render at each cutoff point and dealing with the headache at the last pages when it comes to that.

It would be happy to resolve this as I don't study from epubs anymore.

**Comment by hugleo** [comment]
Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.

![overlap](https://github.com/koreader/koreader/assets/4573505/0e69d732-c567-4091-bf49-d4293ce323ec)

**Comment by MortalWombat-repo** [comment]
> Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> 
> ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)

It worked!

Thank you so much. It is great that there is an option of customization.

When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on.
Is that normal behavior?

I'm guessing this will get closed now.
But do you know how to change in those options for page overlap to be enabled in continuous as it once were?

As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous.
Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.

I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic.
I wish there was a guide for the lua config.

**Comment by hugleo** [comment]
> > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> 
> It worked!
> 
> Thank you so much. It is great that there is an option of customization.
> 
> When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?


> 
> I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?

For what I understood the problem you are trying to fix is avoid overlapped lines like the test case I've created bellow?

![overlapped_lines](https://github.com/koreader/koreader/assets/4573505/d46482e3-b447-47c4-894c-28007986c112)

Happens when the pages have 0 margins, for example.

> 
> As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> 
> I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I wish there was a guide for the lua config.

**Comment by MortalWombat-repo** [comment]
> > > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> > 
> > 
> > It worked!
> > Thank you so much. It is great that there is an option of customization.
> > When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?
> 
> > I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?
> 
> For what I understood the problem you are trying to fix is avoid overlapped lines like the test case I've created bellow?
> 
> ![overlapped_lines](https://private-user-images.githubusercontent.com/4573505/320230715-d46482e3-b447-47c4-894c-28007986c112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzI5NTYsIm5iZiI6MTcxMjQzMjY1NiwicGF0aCI6Ii80NTczNTA1LzMyMDIzMDcxNS1kNDY0ODJlMy1iNDQ3LTQ3YzQtODk0Yy0yODAwNzk4NmMxMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTk0NDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZkMDYwYWEyYTcxZTU1NGNiNjZmMmFmZjA0OGZkNjRhYzBiNzQ4ZDdlNTcwMTBlODdmODA5Y2QzYWYxMTlmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QiB5JvZBcJdE6wBmC4lHlk_aaZwXXiu0m1VKS34RCDM)
> 
> Happens when the pages have 0 margins, for example.
> 
> > As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> > I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I w

> > > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> > 
> > 
> > It worked!
> > Thank you so much. It is great that there is an option of customization.
> > When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?
> 
> > I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?
> 
> For what I understood the problem you are trying to fix is avoid overlapped lines like the test case I've created bellow?
> 
> ![overlapped_lines](https://private-user-images.githubusercontent.com/4573505/320230715-d46482e3-b447-47c4-894c-28007986c112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzMwNDYsIm5iZiI6MTcxMjQzMjc0NiwicGF0aCI6Ii80NTczNTA1LzMyMDIzMDcxNS1kNDY0ODJlMy1iNDQ3LTQ3YzQtODk0Yy0yODAwNzk4NmMxMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTk0NTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA0NDlkN2NmNjJmYmI5ZDcyYWM1ZGUxMzljNDQ3NjAxNjJmYWFkMTFiZTk5YTcxNTdiMDAxNWRlZGJiMDZjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3FcVUbe8Y3LBTrw3yp1HslgniA5YsafPCICIndlBDNM)
> 
> Happens when the pages have 0 margins, for example.
> 
> > As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> > I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I wish there was a guide for the lua config.

I'm quoting everything since too many times I deleted comments when replying from the phone. Hopefully the devs don't mind.

No, everything is ok regarding render.
Thank you for taking some of your time to reproduce want you thought was the issue I really appreciate it.

What I meant was since you are familiar with the advanced settings, do they have a setting that allow turning on page overlap option when I have the continuous mode selected but then figured out that I don't need that option since the continuous works great.
It was my mistake.

Regarding page overlap in page scroll I do get a lot of wasted pages especially in landscape.
I don't know if there is a way to fix that so that is why I wanted to use continuous scroll.

Thank you for your help.
Have a lovely weekend.

**Comment by hugleo** [comment]
> > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> 
> It worked!
> 
> Thank you so much. It is great that there is an option of customization.
> 
> When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?

This happened to me a few times too.

> 
> I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?
> 
> As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> 
> I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I wish there was a guide for the lua config.

**Comment by MortalWombat-repo** [comment]
> > > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> > 
> > 
> > It worked!
> > Thank you so much. It is great that there is an option of customization.
> > When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?
> 
> This happened to me a few times too.
> 
> > I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?
> > As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> > I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I wish there was a guide for the lua config.

Thank you for clarifying.
I dance a lot around this device because I know if I brick it I will probably not open it to flash.

**Comment by hugleo** [comment]
> > > > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > > > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> > > 
> > > 
> > > It worked!
> > > Thank you so much. It is great that there is an option of customization.
> > > When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?
> > 
> > 
> > > I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?
> > 
> > 
> > For what I understood the problem you are trying to fix is avoid overlapped lines like the test case I've created bellow?
> > ![overlapped_lines](https://private-user-images.githubusercontent.com/4573505/320230715-d46482e3-b447-47c4-894c-28007986c112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzI5NTYsIm5iZiI6MTcxMjQzMjY1NiwicGF0aCI6Ii80NTczNTA1LzMyMDIzMDcxNS1kNDY0ODJlMy1iNDQ3LTQ3YzQtODk0Yy0yODAwNzk4NmMxMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTk0NDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZkMDYwYWEyYTcxZTU1NGNiNjZmMmFmZjA0OGZkNjRhYzBiNzQ4ZDdlNTcwMTBlODdmODA5Y2QzYWYxMTlmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QiB5JvZBcJdE6wBmC4lHlk_aaZwXXiu0m1VKS34RCDM)
> > Happens when the pages have 0 margins, for example.
> > > As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> > > I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I w
> 
> > > > Try more tools / advanced settings, changing DOVERLAPPIXELS to 0.
> > > > ![overlap](https://private-user-images.githubusercontent.com/4573505/320221235-0e69d732-c567-4091-bf49-d4293ce323ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MjUyOTgsIm5iZiI6MTcxMjQyNDk5OCwicGF0aCI6Ii80NTczNTA1LzMyMDIyMTIzNS0wZTY5ZDczMi1jNTY3LTQwOTEtYmY0OS1kNDI5M2NlMzIzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTczNjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTU0YTYxMWNiZDI5NmI0N2UyYTEyZTg0OWY3MjJmYWZiYTQyN2E1MDJlNjhkZmI0NGI5NTVhNzg0ZmM1ZGM0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPPZ8qQNyaSu-xoA6-dasdE9Cs6Ns0ugVmVieObP328)
> > > 
> > > 
> > > It worked!
> > > Thank you so much. It is great that there is an option of customization.
> > > When I changed the setting it said it needs to restart, but the only thing it did is freeze for a few seconds and then continued on. Is that normal behavior?
> > 
> > 
> > > I'm guessing this will get closed now. But do you know how to change in those options for page overlap to be enabled in continuous as it once were?
> > 
> > 
> > For what I understood the problem you are trying to fix is avoid overlapped lines like the test case I've created bellow?
> > ![overlapped_lines](https://private-user-images.githubusercontent.com/4573505/320230715-d46482e3-b447-47c4-894c-28007986c112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MzMwNDYsIm5iZiI6MTcxMjQzMjc0NiwicGF0aCI6Ii80NTczNTA1LzMyMDIzMDcxNS1kNDY0ODJlMy1iNDQ3LTQ3YzQtODk0Yy0yODAwNzk4NmMxMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTk0NTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA0NDlkN2NmNjJmYmI5ZDcyYWM1ZGUxMzljNDQ3NjAxNjJmYWFkMTFiZTk5YTcxNTdiMDAxNWRlZGJiMDZjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3FcVUbe8Y3LBTrw3yp1HslgniA5YsafPCICIndlBDNM)
> > Happens when the pages have 0 margins, for example.
> > > As I opened the book I realized it was in paged mode as I scrolled through a few pages and it was greyed out before I switched to continuous. Sometimes I can force it but probably mostly by luck. Something to override that warning that the overlap isn't supported in that page mode.
> > > I don't want to look at a gift horse mouth so if I'm asking too much I'll open another topic. I wish there was a guide for the lua config.
> 
> I'm quoting everything since too many times I deleted comments when replying from the phone. Hopefully the devs don't mind.
> 
> No, everything is ok regarding render. Thank you for taking some of your time to reproduce want you thought was the issue I really appreciate it.

I found a new problem then, but then let someone that cares report it first :rofl: 

> 
> What I meant was since you are familiar with the advanced settings, do they have a setting that allow turning on page overlap option when I have the continuous mode selected but then figured out that I don't need that option since the continuous works great. It was my mistake.
> 
> Regarding page overlap in page scroll I do get a lot of wasted pages especially in landscape. I don't know if there is a way to fix that so that is why I wanted to use continuous scroll.
> 
> Thank you for your help. Have a lovely weekend.
