### ISSUE TITLE
FR: [ please! Dicttango support is needed.]

### ISSUE THREAD

**Issue by dhuux** [koreader/koreader#11634]
i tried creating dictionaries.lua file in koreader directory but didn't work for me. Or maybe i did it wrong. 
![Screenshot_20240407-005649_MiXplorer~01](https://github.com/koreader/koreader/assets/63465816/31efb21f-dacb-42cf-9006-7921071766f2)

i was just hoping it to work out of the box like these Epub readers since i'm dumb at tweaking things.

Lithium app.
![Screenshot_20240407-001819_DictTango](https://github.com/koreader/koreader/assets/63465816/0cc5d00b-d6dc-485d-a94d-b13ce1932a14)

Or

Readsily app:
![Screenshot_20240407-003253_DictTango](https://github.com/koreader/koreader/assets/63465816/28973d19-e8e0-4f63-ab0b-3f697669cce9)

look up pro good on Koreader:
![Screenshot_20240407-004624_Lookup Pro](https://github.com/koreader/koreader/assets/63465816/b41a6258-0e61-4abf-8598-1f0618a0fd39)

 but  simple. I want those big, colorful and resourceful dictionaries which are handled pretty well by DictTango app than any other app.

Yes, i tried GoldenDict. it's taking the whole screen. I don't know how to make it small. it's a little slower than DictTango too. 
![Screenshot_20240407-012129_GoldenDict](https://github.com/koreader/koreader/assets/63465816/acbe8893-2e70-4773-82dd-cc4bb65b0d71)
 

 Please support. Thanks.

And my phone is very old. J4+.

**Comment by benoit-pierre** [comment]
Your `dictionaries.lua` is missing a comma after `false`, maybe that's why it did not work?

**Comment by dhuux** [comment]
@benoit-pierre  thanks. I'm really stupid. It worked!
![Screenshot_20240407-013853_DictTango](https://github.com/koreader/koreader/assets/63465816/60a55c36-dec7-4996-9872-bf4d9df3ffe1)
