### ISSUE TITLE
Classic mode settings items per page and item font size show %1

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#11631]
* KOReader version: 2024.03.1-36
* Device: all

#### Issue
When no value is set they show %1

This might occur elsewhere as well?

**Comment by hius07** [comment]
Even after https://github.com/koreader/koreader/pull/11626?

**Comment by Frenzie** [comment]
Oh my bad. I didn't have internet.

**Comment by Frenzie** [comment]
But actually yes.

**Comment by hius07** [comment]
Can you check once more please. I believe it is fixed.

**Comment by Frenzie** [comment]
Indeed, today's nightly seems to be fixed.
