### ISSUE TITLE
The QRcode is too big. 

### ISSUE THREAD

**Issue by Thamone** [koreader/koreader#11651]
**Does your feature request involve difficulty completing a task? Please describe.**
The QRcode is too big, I have to reach my whole arm length to scan the code. I've tried to find an option to change its size, but I can't find any where.
It's not a big problem, just not convenient. 

**Describe the solution you'd like**
If you would consider adding an option to resize the QRcode, I would appreciate it.

**Additional context**
I use Koreader on KOBO Clara 2E 

![Screenshot_2024-04-10-11-25-47-832_com xiaomi scanner](https://github.com/koreader/koreader/assets/28747875/1098b642-55f5-495a-8be5-3ee164ed56ab)

**Comment by hius07** [comment]
```Lua
local QRMessage = require("ui/widget/qrmessage")
QRMessage.scale_factor = 0.5

```
Create a file named `2-qr-scale.lua` containing the above lines, put the file into koreader/patches folder, restart KOReader.

**Comment by Thamone** [comment]
> ```lua
> local QRMessage = require("ui/widget/qrmessage")
> QRMessage.scale_factor = 0.5
> ```
> 
> Create a file named `2-qr-scale.lua` containing the above lines, put the file into koreader/patches folder, restart KOReader.

Thank you so much😃
![IMG_20240410_151222](https://github.com/koreader/koreader/assets/28747875/f9f74884-c266-474f-8b80-20043d20c52a)
