### ISSUE TITLE
Is there a 32-bit Android installation package available？

### ISSUE THREAD

**Issue by trbmagnet** [koreader/koreader#11663]
**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by Frenzie** [comment]
`koreader-android-arm-v2024.03.1.apk is the 32-bit package.
