### ISSUE TITLE
Icon overlays text 

### ISSUE THREAD

**Issue by ZHANYLone** [koreader/koreader#11672]
* KOReader version: Latest 2024.03.1
* Device: PocketBook 633 Color

![IMG_20240412_125825.jpg](https://github.com/koreader/koreader/assets/119916135/c66cc1ae-6d44-4894-9d89-4840c9410f12)

Icon that appears when you long press and hold text, Pokémon-like Icon I think it's in the wrong place, **you need to fix it in a new version (please)**, because it over text, it overlays it (name of the book and author in the top bar). So it looks bad over the text.

I think you need to replace this icon down a little.

Have a good day

**Comment by poire-z** [comment]
Read #11514.
It's supposed to show up when you long-press for > 3s, to tell you you did a very-long-press and stuff may act differently. It should disappear once you're done acting on this. And it's expected that it appears there over the text or the top status bar: it should just not stay there long.
If the icon stays, it's the same issue as @mergen3107 in #11514, and you should try to tell us how to reproduce that behaviour. Please comment in #11514 to keep all the info in a single place.

**Comment by ZHANYLone** [comment]
> * KOReader version: Latest 2024.03.1
> * Device: PocketBook 633 Color
> 
> ![IMG_20240412_125825.jpg](https://github.com/koreader/koreader/assets/119916135/c66cc1ae-6d44-4894-9d89-4840c9410f12)
> 
> Icon that appears when you long press and hold text, Pokémon-like Icon I think it's in the wrong place, **you need to fix it in a new version (please)**, because it over text, it overlays it (name of the book and author in the top bar). So it looks bad over the text.
> 
> I think you need to replace this icon down a little.
> 
> Have a good day 
> 

Yeah, it doesn't stay long. I just thought... it would be better... or prettier if you moved this icon a little lower.

**Comment by mergen3107** [comment]
Yes, this icon doesn't stay indefinitely anymore after the patch (which is in v2024.03.1-1)
