### ISSUE TITLE
emoji still don't work after installing emoji font and setting emoji font-family

### ISSUE THREAD

**Issue by neonpixii** [koreader/koreader#11670]
* KOReader version: v2024.03.01
* Device: kobo (don't know how to find model information)

#### Issue
emoji did not work to begin with. installed emoji font. emoji remain rendering as "?" instead of displaying in newly installed fontface

#### Steps to reproduce
- downloaded google's monochrome emoji font "noto emoji" https://fonts.google.com/noto/specimen/Noto+Emoji
- put all weights/italic/bold/variants font files into the font directory
- went into the font settings and set the default emoji font-family to noto emoji
- restarted ko reader and rebooted the entire device
- opened epub from ao3 containing emoji (i can link to the specific epub if requested, but be warned it is adult content)
- emoji do not render

#### additional information
example snippets from the epub file in question, if relevant. nonemoji text has been omitted
```html
<p class="calibre7">(...)<em class="calibre9">(...) 💖💖💖🌹🌹🌹</em> (...)</p>
```
```html
<p class="calibre7">(...)<em class="calibre9">(...) </em>💖💖💖🌹🌹🌹</p>
```
(note the emoji themselves are not italic in this snippet)

css for the epub
```css
.calibre7 {
  display: block;
  margin: 1em 0;
}
.calibre9 {
  font-style: italic;
}
```

- emoji properly render when the noto emoji font is set as the main font (but noto emoji is not designed as a body text font so this doesn't work as a solution)
-

**Comment by poire-z** [comment]
That menu you went it does not "set the font to be used for emoji". It sets the font to be use with CSS styles having "font-family: emoji".
So, you need to specify in the class name "font-family: emoji" (in the book CSS or via some style tweaks, which can be tedious if they are different per book) so it is used intead of the default font.

Or set it as the fallback font in the font menu with long-press (only one user-defined allowed though) to it can be used for non-found glyphs for any text.

There may be some user-patch discussed somewhere to insert additional font in that fallback font list (`CreDocument.fallback_fonts`).

**Comment by neonpixii** [comment]
that worked! thanks so much
