### ISSUE TITLE
Incorrect chapter shown in status bar

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11674]
* KOReader version: 2024.03.1-55 (Kobo) and ..1-62 (Android)
* Device: Kobo/Android

#### Issue

When located on a page before the TOC chapters begin, the status bar will  already show the name of the first chapter. Correct would be an empty field.

**Location in Book map:**

![image](https://github.com/koreader/koreader/assets/95502269/2ac5881d-8d11-48f1-8d43-643ab65d59c2)

**Incorrect chapter name in status bar:**

![image](https://github.com/koreader/koreader/assets/95502269/406b4742-889c-433e-9c25-e746ac17f18c)

I am quite sure this must be due to a recent change, as I have never seen this happen before.

Thank you all for your help and dedication.

**Comment by poire-z** [comment]
It was already happening with v2023.06.1.
(You may have not witnessed this often because it's rare, very often there is a toc item for the cover on page 1.)

**Comment by poire-z** [comment]
Logical fix could be this (we already return nil when no toc, so other code may be fine with it - but who knows, it needs testing):
```diff
--- a/frontend/apps/reader/modules/readertoc.lua
+++ b/frontend/apps/reader/modules/readertoc.lua
@@ -349,30 +349,30 @@ end
 function ReaderToc:getTocIndexByPage(pn_or_xp, skip_ignored_ticks)
     self:fillToc()
     if #self.toc == 0 then return end
     local pageno = pn_or_xp
     if type(pn_or_xp) == "string" then
         return self:getAccurateTocIndexByXPointer(pn_or_xp, skip_ignored_ticks)
     end
-    local prev_index = 1
+    local prev_index = 0
     for _k,_v in ipairs(self.toc) do
         if not skip_ignored_ticks or not self.toc_ticks_ignored_levels[_v.depth] then
             if _v.page == pageno then
                 -- Return the first chapter seen on the current page
                 prev_index = _k
                 break
             end
             if _v.page > pageno then
                 -- Return last chapter seen on a previous page
                 break
             end
             prev_index = _k
         end
     end
-    return prev_index
+    return prev_index > 0 and prev_index or nil
 end
```

**Comment by jonnyl2** [comment]
>It was already happening with v2023.06.1.

That's possible, but I'm positive it wasn't the case when testing the Custom TOC/ Hidden Flow updates. 

I will apply your patch and report back. Thanks!

**Comment by jonnyl2** [comment]
It works!

**Comment by jonnyl2** [comment]
Pulled out an old reader with version 2023.03 installed, and you're right, this bug already existed way back then. I could have sworn I had previously observed the chapter title changing from nothing to something on the status bar. My memory is playing tricks on me. Might have mixed it up with the Book map bar on the Page browser or something.
