### ISSUE TITLE
Crash when attempting to launch Advanced settings

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11679]
* KOReader version: 2024.03.1-63
* Device: Kobo Aura H2O

#### Issue

Tapping `Advanced settings` from the File browser's `Tools> / More tools> /` menu causes KOReader to crash.

<details>
  <summary>crash.log</summary>

```
04/14/24-11:28:12 INFO  Inhibiting user input 
04/14/24-11:28:13 INFO  Loading plugins from directory: plugins 
04/14/24-11:28:13 INFO  setting zoom mode to content 
04/14/24-11:28:16 INFO  Restoring user input handling 
./luajit: frontend/apps/filemanager/filemanagersetdefaults.lua:47: attempt to index a nil value
stack traceback:
	frontend/apps/filemanager/filemanagersetdefaults.lua:47: in function 'init'
	frontend/ui/widget/widget.lua:46: in function 'new'
	frontend/apps/filemanager/filemanagersetdefaults.lua:309: in function 'ok_callback'
	frontend/ui/widget/confirmbox.lua:118: in function 'callback'
	frontend/ui/widget/buttontable.lua:81: in function 'callback'
	frontend/ui/widget/button.lua:433: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:907: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1436: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1536: in function 'handleInput'
	frontend/ui/uimanager.lua:1580: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 04/14/24 @ 11:28:42)
Running FW 4.35.20400 on Linux 2.6.35.3-850-gbc67621+ (#3032 PREEMPT Mon Jan 9 13:37:40 CST 2017)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/14/24-11:28:57
 [*] Version: v2024.03.1-63-gc345de5d7_2024-04-13
```
</details>

Thank you for your help.

**Comment by hugleo** [comment]
Maybe something messing with the config?

What the contents of defaults.custom.lua file?

**Comment by jonnyl2** [comment]
Indeed, I commented out the `STARDICT` line and that fixed it. 

This is how the last 3 lines of defaults.custom.lua looked like before:

```lua
    },
    STARDICT_DATA_DIR = "/mnt/onboard/.adds/dict", 
}
```
Is this not the proper way to define a custom dictionary location? The dictionaries were loaded from there correctly. I don't remember when I last opened the Advanced settings -- it could have been months ago.

**Comment by hugleo** [comment]
Could you try like that?

```
STARDICT_DATA_DIR = /mnt/onboard/.adds/dict,
```

**Comment by hius07** [comment]
When building the list of the **default** default values the program iterates over all key-values from defaults.lua.
https://github.com/koreader/koreader/blob/c345de5d711134d40f9b5ccb0942d7a3b7b8e4a2/frontend/apps/filemanager/filemanagersetdefaults.lua#L37-L45
But defaults.lua contains
https://github.com/koreader/koreader/blob/c345de5d711134d40f9b5ccb0942d7a3b7b8e4a2/defaults.lua#L196
Lua `pairs` skips keys with `nil` values, so when building the list of **custom** default values we got crash in line 47
https://github.com/koreader/koreader/blob/c345de5d711134d40f9b5ccb0942d7a3b7b8e4a2/frontend/apps/filemanager/filemanagersetdefaults.lua#L46-L49
because `self.state[STARDICT_DATA_DIR]` is `nil`.

**Comment by hugleo** [comment]
yes, but not exactly.

The problem is here with dofile:  https://github.com/koreader/koreader/blob/master/frontend/luadefaults.lua#L46
dofile will not load STARDICT_DATA_DIR even if is explicit defined with nil value.

We use this var here: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerdictionary.lua#L110

I suggest change to STARDICT_DATA_DIR = false in defaults.lua, what do you  think?

**Comment by Frenzie** [comment]
Shouldn't we have seen this 2 or more years ago already? What changed since?

**Comment by hugleo** [comment]
PS:

There are one more item in config that is defined with nil value:

NETWORK_PROXY = nil,

Will be affected as well.

**Comment by hugleo** [comment]
for reference: https://stackoverflow.com/questions/40441508/how-to-represent-nil-in-a-table

**Comment by pazos** [comment]
> Shouldn't we have seen this 2 or more years ago already? What changed since?

**Four** since https://github.com/koreader/koreader/commit/f756a6aaa75b81201fbf302adc9d21cef560c810 🤔 

TBH I didn't check advanced settings back then so it is probably broken since its inception.

**Comment by hugleo** [comment]
> > Shouldn't we have seen this 2 or more years ago already? What changed since?
> 
> **Four** since [f756a6a](https://github.com/koreader/koreader/commit/f756a6aaa75b81201fbf302adc9d21cef560c810) 🤔
> 
> TBH I didn't check advanced settings back then so it is probably broken since its inception.

This one will not crash. Is since this: https://github.com/koreader/koreader/pull/9546 ;-)
