### ISSUE TITLE
Screen not flashing in PocketBook when Avoid mandatory black flashes in UI unchecked

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#11683]
* KOReader version: Last Version
* Device: PocketBook Era

I have noticed that my PocketBook Era is not flashing after closing the top menu or the search window even though Avoid mandatory black flashes in UI unchecked is unchecked.

It is the same for my Boox Palma and it works properly on Kobo devices.

Is it a way to make it flash? There is a bit of ghost every time the top menu is activated for instnace.

Thanks.

**Comment by jospalau** [comment]
Closing the ticket:
It looks like that this is not supported in Android devices, just Tolinos.

And for PocketBook devices, a change may be required.

**Comment by Frenzie** [comment]
You can use the e ink test utility on Android to see if any of the implemented drivers are relevant to that device. See more details here: https://github.com/koreader/koreader/issues/8482#issue-1063797731
