### ISSUE TITLE
Add CSV Export to Vocabulary Builder

### ISSUE THREAD

**Issue by andrew-lawlor** [koreader/koreader#11697]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently, the Vocabulary Builder plugin does not allow for the export of vocab words (and associated data) outside of Koreader.

**Describe the solution you'd like**
It would be useful to allow users to export their vocabulary data from koreader in CSV format to support importing that data into common SRS tools like Anki. Upon pressing a UI control for exporting, the system would export all vocab words, their definitions, and their context (if present) to a CSV file saved to the user's device. This would work similarly to how the notes/annotations export works.

**Describe alternatives you've considered**
Power users can already retrieve this information from the embedded SQLite Database using any scripting language, and then transform the data to the CSV format for import into Anki or another system.  This feature would greatly simplify that process, in addition to allowing non-technical users the ability to export their vocab data.

**Additional context**
Add any additional context or screenshots about the feature request here.

![image](https://github.com/koreader/koreader/assets/19480132/23485e28-7c38-4c51-821c-d6d78b9c03d9)

**Comment by Frenzie** [comment]
Pinging @weijiuqiao for thoughts.

**Comment by weijiuqiao** [comment]
Maybe one of these is already useful?
https://github.com/RasmusRendal/koreaderankiexport
https://github.com/yue-dongchen/KOReader2Flashcards
https://github.com/Dankoy/korvo-to-anki

**Comment by andrew-lawlor** [comment]
> Maybe one of these is already useful? https://github.com/RasmusRendal/koreaderankiexport https://github.com/yue-dongchen/KOReader2Flashcards https://github.com/Dankoy/korvo-to-anki

@weijiuqiao Thanks for the recommendations! The first link lead me to a really powerful FOSS program called [vocabsieve](https://github.com/FreeLanguageTools/vocabsieve), which fits the use case perfectly. Thanks again! And thanks so much for creating the Vocabulary Builder plugin -- it's head and shoulders above any other similar ereader software I've used for that purpose.

**Comment by weijiuqiao** [comment]
Good to know you found what you were looking for. And thanks for the compliments and I'm happy you like the plugin so much. I'm closing this issue since the links worked :)
