### ISSUE TITLE
Koreader doesn't save the last position

### ISSUE THREAD

**Issue by x3oo** [koreader/koreader#11706]
* KOReader version: 
* Device: Pocketbook Inkpad 3 Pro

#### Issue
Doesn't open book at last page.

#### Steps to reproduce
Open a book. Go to page 10. Turn off device. Turn on. Koreader opens at an earlier page. Page 2 for example.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by x3oo** [comment]
Here. Nothing relevant I think.

**Comment by x3oo** [comment]
[crash.log](https://github.com/koreader/koreader/files/15079528/crash.log)
second try,

**Comment by jonnyl2** [comment]
Are you using `Power off` from the menu or an assigned gesture/QuickMenu? If you use the power button the system probably doesn't get a chance to save the current settings and position.

**Comment by x3oo** [comment]
It seems to work if you shut down through the menu.
Thats very sad because pocketbook doesn't even turn off the device immediatly but puts it into sleep mode and turns it off after a rater long wait time in sleep mode.

**Comment by jonnyl2** [comment]
I'm not familiar with Pocketbooks, but if you want to turn it off completely immediately, you may have to long press the button or change some device settings. (If it goes to standby first then KOReader really should be saving the position, though.) 

Does using the menu do what you want (turn off immediately)? Then I'd suggest setting up a gesture for powering off the device.

**Comment by x3oo** [comment]
You are right, sadly this bug also appears after this 10min sleep phase, other settings to koreader are lost too.
One Option is to deactivate standby in the original os and only use koreader standby options.

**Comment by hugleo** [comment]
Ref. https://github.com/koreader/koreader/issues/11504

**Comment by x3oo** [comment]
The issue was cause by a jailbreak of the pocketbook.
