### ISSUE TITLE
Cover image is forced in landscape, but only sometimes?

### ISSUE THREAD

**Issue by GroenteLepel** [koreader/koreader#11713]
* KOReader version: 2024.03.1
* Device: PocketBook Touch HD 3

#### Issue
I am using the cover image plugin to generate a nice book cover when my PocketBook is off. This worked fine, but since a reading hiatus of a year I updated koreader from 2023.05.1 to the current version, and my PocketBook received some updates as well. And now the cover image is made as a screenshot in landscape mode it looks like. If i enable the black borders to fill up you can see that clearly (see picture).

![IMG_5993](https://github.com/koreader/koreader/assets/19837177/d8cb02bd-5081-4f7a-9970-4bd1c9cdf9a1)

I tried removing the cache, setting the default rotation to 0 degrees, actually closing/suspending when in portrait (and every time when changing I deleted the cache). I have tried changing the name of the file to pb_offlogo or whatever the tutorial says to use, but that's actually not helping for my PocketBook model.

#### Steps to reproduce
The annoying thing is, that I just now opened a new book that I haven't read yet with all the default settings and there the cover image is in portrait, just as I want it. So I tried it with the other book and it worked. But sometimes it doesn't but I don't know yet how to influence this.

![IMG_5994](https://github.com/koreader/koreader/assets/19837177/1b7ae461-aa54-4d56-92cf-9d6b095a3139)

**Comment by Manodragon** [comment]
Please fix this. I am encountering the same problem with my InkPad 4
![17144200856012409625704621105342](https://github.com/koreader/koreader/assets/6142132/c23283c4-4261-4ffd-b3a4-854b8dbd6a1f)

**Comment by GroenteLepel** [comment]
I’m getting consistently _good_ results now with new books. It is maybe related to my default orientation settings? I changed that to landscape and then I got these weird covers, now I changed it back to portrait and it seems to “work” (although some books that I was reading at that time did not adjust their cover).

**Comment by poire-z** [comment]
If I guessed right it's the CoverImage plugin at play, pinging @zwim.

**Comment by GroenteLepel** [comment]
amazing, thanks for the quick work. I'll patiently wait until it is included in the next release.

**Comment by Frenzie** [comment]
> amazing, thanks for the quick work. I'll patiently wait until it is included in the next release.

You can grab the latest nightly from http://build.koreader.rocks/download/nightly/
