### ISSUE TITLE
Tolino Vision 4 HD, tap2flip

### ISSUE THREAD

**Issue by eutampieri** [koreader/koreader#11720]
Tolino Vision 4 HD, FW Version 12.2.0.

Patch works fine.

Furthermore, to make the Tap2Flip thing (keycode 195, scancode 248 according to key event viewer) work, I've added this event map:

```
return {
  [195] = "LPgFwd",
  [248] = "LPgFwd"
}
```

Why one value isn't sufficient I don't know.  How would double tapping a button to go back a page work?

_Originally posted by @fuero in https://github.com/koreader/koreader/issues/3517#issuecomment-487280643_
            
  
  
Can we enable tap2flip on the aforementioned tolino? Can koreader support it?

**Comment by pazos** [comment]
> Can we enable tap2flip on the aforementioned tolino? Can koreader support it?

Nope. We aim to support a bunch of android devices without a bunch of effort and without having a single android eink device. 

The best we can do is try to support regular android ~~shit~~ stuff and particular eink and lights drivers for some models. Everything else is out of scope.

**Comment by eutampieri** [comment]
Speaking of which, I can control the colour temperature but not the brightness. I’ll open another issue then

**Comment by pazos** [comment]
> Speaking of which, I can control the colour temperature but not the brightness. I’ll open another issue then

No need for a new issue. Just follow https://github.com/koreader/koreader/issues/8482 and comment there if some other driver is able to control the brightness. If no driver work I'm afraid you'll need to wait until somebody submits a patch for that family of devices.
