### ISSUE TITLE
Not working on new Kobo Clara B/W

### ISSUE THREAD

**Issue by jrjove** [koreader/koreader#11731]
* KOReader version: last
* Device: Kobo Clara B/W

##### `crash.log` (if applicable)

```
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/29/24-17:32:35
 [*] Version: v2024.03.1

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
./luajit: frontend/device/kobo/device.lua:1682: unrecognized Kobo model spaBW with device id 391
stack traceback:
	[C]: in function 'error'
	frontend/device/kobo/device.lua:1682: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:61: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x000140cd
!!!!
Uh oh, something went awry... (Crash n°1: 04/29/24 @ 17:32:35)
Running FW 4.39.22801 on Linux 4.9.77 (#1 SMP PREEMPT d514d0df4-20240307T151406-B0307151713)
Attempting to restart KOReader . . .
!!!!

```

**Comment by olivierclermont** [comment]
I have the same problem. Also on Kobo Clara

**Comment by c0eos** [comment]
I have the same issue with my Kobo Clara Colour, with the difference in the crash.log file being `./luajit: frontend/device/kobo/device.lua:1682: unrecognized Kobo model spaColour with device id 393`

I edited the `frontend/device/kobo/device.lua` file to try to trick KOReader with:
```lua
elseif codename == "condor" then
    return KoboCondor
elseif codename == "spaColour" then
    return KoboGoldfish -- same as Clara 2E
else
    error("unrecognized Kobo model ".. codename .. " with device id " .. product_id)
end
```

However, this gives a new error:
```
04/30/24-11:34:31 INFO  Enabling Kobo @ 32bpp BGR tweaks 
Cannot open file `/sys/class/leds/aw99703-bl_FL1/color`:	No such file or directory
./luajit: frontend/device/kobo/device.lua:823: Error opening input device </dev/input/by-path/platform-bd71828-pwrkey-event>: No such file or directory
stack traceback:
	[C]: in function 'open'
	frontend/device/kobo/device.lua:823: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x000140cd
!!!!
```

I'll try to define a new device and find the right settings.

**Comment by meguminnet** [comment]
I don't have the device yet, but I'm assuming the Kobo Libra Colour will also need to be added for it to be supported.

**Comment by Diblox** [comment]
Same issue with Clara Colour

**Comment by c0eos** [comment]
OK, some progress.
In `frontend/device/kobo/device.lua`, I have added:
```lua
-- Kobo Clara Colour:
local KoboSpaColour = Kobo:extend{
    model = "Kobo_spa_colour",
    isMk7 = yes,
    hasEclipseWfm = yes,
    canToggleChargingLED = yes,
    led_uses_channel_3 = true,
    hasFrontlight = yes,
    display_dpi = 300,
    hasNaturalLight = yes,
    frontlight_settings = {
        frontlight_white = "/sys/class/backlight/mxc_msp430.0/brightness",
        frontlight_mixer = "/sys/class/backlight/lm3630a_led/color",
        nl_min = 0,
        nl_max = 10,
        nl_inverted = true,
    },
    battery_sysfs = "/sys/class/power_supply/battery",
    power_dev = "/dev/input/by-path/platform-bd71828-pwrkey.6.auto-event",
    -- Board is eerily similar to the Libra 2, so, it inherits the same quirks...
    -- c.f., https://github.com/koreader/koreader/issues/9552#issuecomment-1293000313
    hasReliableMxcWaitFor = no,
    isSMP = yes,
}
```
It's a copy of the Kobo Clara 2E (goldfinch) definition, where I changed `frontlight_mixer`, `power_dev` (from what seemed right in the `/sys/` path) and `isSMP` (because the new device is dual core).

The crash.log is now:
```---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/30/24-12:54:39
 [*] Version: v2024.03.1

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
04/30/24-12:54:39 INFO  Enabling Kobo @ 32bpp BGR tweaks 
[ko-input] Forked off fake event generator (pid: 1308)
04/30/24-12:54:39 INFO  initializing for device Kobo_spa_colour 
04/30/24-12:54:39 INFO  framebuffer resolution: {
  h = 1448,
  w = 1072
} --[[table: 0xb6b5fe80]] 
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: sqlite3
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libcrypto.so.1.1
04/30/24-12:54:39 INFO  Loading plugins from directory: plugins 
dhcpcd[1321]: dhcpcd not running
04/30/24-12:55:07 INFO  Kobo Wi-Fi: disabling Wi-Fi 
dhcpcd[1333]: dhcpcd not running
OK
04/30/24-12:55:07 INFO  WakeupMgr: scheduling wakeup in 259200 -> 1714733707 
04/30/24-12:55:07 INFO  Inhibiting user input 
04/30/24-12:55:08 INFO  Restoring user input handling 
04/30/24-12:55:11 INFO  Powering off the device... 
setWakeupAlarm ioctl RTC_WKALM_SET	-1	Numerical result out of range
toggleAlarmInterrupt open /dev/rtc0	-1	Device or resource busy
04/30/24-12:55:11 INFO  Preparing to quit UIManager with exit code: 88 
04/30/24-12:55:11 INFO  UIManager: No dialogs left to show 
04/30/24-12:55:11 INFO  Tearing down UIManager with exit code: 88 
[ko-input] Closed input device with fd: 8 @ idx: 3
[ko-input] Closed input device with fd: 7 @ idx: 2
[ko-input] Closed input device with fd: 6 @ idx: 1
[ko-input] Closed input device with fd: 5 @ idx: 0
Restoring original fb bitdepth @ 32bpp & rotation @ 3
[FBInk] Unidentified Kobo device code (393)!
[FBInk] Detected a Kobo Unknown! (393 => ?? @ Mark ?)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 167 dpi
[FBInk] Variable fb info: 1072x1448, 32bpp @ rotation: 3 (Counter Clockwise, 270°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 6243328 bytes & line length: 4288 bytes
[FBInk] Canonical rotation: 0 (Upright, 0°)
[FBInk] Fontsize set to 16x16 (IBM (Default) base glyph size: 8x8)
[FBInk] Line length: 67 cols, Page size: 90 rows
[FBInk] Horizontal fit is perfect!
[FBInk] Vertical fit isn't perfect, shifting rows down by 4 pixels
[FBDepth] Screen is 1072x1448 (1072x1456 addressable, fb says 1072x1448)
[FBDepth] Buffer is mapped for 6243328 bytes with a scanline stride of 4288 bytes
[FBDepth] Current bitdepth is already 32bpp, but the grayscale flag is bogus!
[FBDepth] Current rotation is already 3!
[FBDepth] Switching fb to 32bpp @ rotation 3 . . .
Updating bitdepth from 32bpp to 32bpp
Sanitizing grayscale flag for bitdepths > 8bpp
Updating rotation from 3 (Counter Clockwise, 270°) to 3 (Counter Clockwise, 270°)
Bitdepth is now 32bpp (grayscale: 0) @ rotate: 3 (Counter Clockwise, 270°)
[FBDepth] Screen is 1072x1448 (1072x1456 addressable, fb says 1072x1448)
[FBDepth] Buffer is mapped for 6243328 bytes with a scanline stride of 4288 bytes
```

KOReader seems to have stopped crashing, and I can use the power button, but the screen is unresponsive and simply shows the normal Kobo home screen.

From what I understand, the issue now lies with FBInk, and I really don't know how to handle that.

**Comment by meguminnet** [comment]
2024.04 dropped a few hours ago, but the issue will probably be the same.

**Comment by Diblox** [comment]
> 2024.04 dropped a few hours ago, but the issue will probably be the same.

Yeah, it is

**Comment by mergen3107** [comment]
These new Kobos probably have new board design and kernels. 

Ask @NiLuJe ?

In the meantime, maybe search for when other new Kobos were added? I remember Kobo Lcara 2E, but maybe something else. 

I mean, look for things you need to report: logs, file locations, etc.

**Comment by Frenzie** [comment]
> From what I understand, the issue now lies with FBInk, and I really don't know how to handle that.

FBInk is merely the last thing in your log, unless you mean something else. What's missing is likely something like https://github.com/koreader/koreader-base/pull/1642 but I don't think the kernel sources are available yet.

**Comment by ptrm** [comment]
> FBInk is merely the last thing in your log, unless you mean something else. What's missing is likely something like [koreader/koreader-base#1642](https://github.com/koreader/koreader-base/pull/1642) but I don't think the kernel sources are available yet.

And here I bought it hoping they just soldered the new Carta 1300 display to an old board :.>

**Comment by c0eos** [comment]
I thought that may have been FBInk because of that message:
```
[FBInk] Unidentified Kobo device code (393)!
[FBInk] Detected a Kobo Unknown! (393 => ?? @ Mark ?)
```
---
You are right. `cat /proc/cpuinfo` gives
```
processor	: 0
Processor	: ARMv7 Processor rev 4 (v7l)
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 15.60
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm aes pmull sha1 sha2 crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: MediaTek MT8110 board
Revision	: 0000
Serial		: 1234567890ABCDEF
```

After seeing that I added the line `isMTK = yes` to my new config, and KOReader finally started and showed the file manager! However, while I can suspend or wake the Kobo up, touching the screen does nothing... Well, not exactly nothing, since the crash.log (with debug and debug_verbose as true) shows the input events.

I looked at the commit you referenced, but it gets a bit too complex for me.

**Comment by ptrm** [comment]
> After seeing that I added the line `isMTK = yes` to my new config, and KOReader finally started and showed the file manager! However, while I can suspend or wake the Kobo up, touching the screen does nothing... Well, not exactly nothing, since the crash.log (with debug and debug_verbose as true) shows the input events.
> 
> I looked at the commit you referenced, but it gets a bit too complex for me.

@c0eos That's for Clara Colour, right? They have dual-core cpus, I wonder if for B/W they changed. Can you point me to an ssh build you use to get shell access on kobo without koreader?

**Comment by Frenzie** [comment]
> I looked at the commit you referenced, but it gets a bit too complex for me.

If `isMTK` does the trick then you can safely ignore all of that. I was giving it a 50/50 of needing isSomethingElseEntirely but I haven't really kept up with any specifics (if they've even been posted anywhere yet, besides here just now).

**Comment by Frenzie** [comment]
> Can you point me to an ssh build you use to get shell access on kobo without koreader? Or another method you had at hand ;)

https://www.mobileread.com/forums/showthread.php?t=254214

**Comment by c0eos** [comment]
@ptrm Yep, I have the Clara Colour. The processor isn't the same as the B/W, it's dual core.

I didn't use ssh, but followed [this telnet access](https://yingtongli.me/blog/2018/07/30/kobo-telnet.html).

I added a `/mnt/onboard/.adds/nm/run` file for NickelMenu consisting of:
```
menu_item : main : run.sh : cmd_spawn : quiet : exec /mnt/onboard/run.sh
```
and `/mnt/onboard/run.sh`
```sh
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

/bin/busybox telnetd &
```

Hacky, but I didn't want to spend the time for anything more complex.

**Comment by ptrm** [comment]
Here's a quick dump of Clara BW. Listed paths mentioned in `frontend/device/kobo/device.lua`

```
[root@spaBW root]# cat /proc/cpuinfo
processor	: 0
Processor	: ARMv7 Processor rev 4 (v7l)
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 26.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm aes pmull sha1 sha2 crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: MediaTek MT8110 board
Revision	: 0000
Serial		: 1234567890ABCDEF
```

```
[root@spaBW root]# ls -l /sys/class/backlight/
total 0
lrwxrwxrwx    1 root     root             0 Apr 30 16:42 lm3630a_led -> ../../devices/platform/10019000.i2c/i2c-1/1-0036/backlight/lm3630a_led
lrwxrwxrwx    1 root     root             0 Apr 30 16:42 lm3630a_leda -> ../../devices/platform/10019000.i2c/i2c-1/1-0036/backlight/lm3630a_leda
lrwxrwxrwx    1 root     root             0 Apr 30 16:42 lm3630a_ledb -> ../../devices/platform/10019000.i2c/i2c-1/1-0036/backlight/lm3630a_ledb
lrwxrwxrwx    1 root     root             0 Apr 30 16:42 mxc_msp430.0 -> ../../devices/platform/ntx_bl/backlight/mxc_msp430.0
```

```
[root@spaBW root]# ls -l /sys/class/power_supply/
total 0
lrwxrwxrwx    1 root     root             0 Apr 30 16:42 bd71827_ac -> ../../devices/platform/10019000.i2c/i2c-1/1-004b/bd71827-power.4.auto/power_supply/bd71827_ac
lrwxrwxrwx    1 root     root             0 Apr 30 16:42 bd71827_bat -> ../../devices/platform/10019000.i2c/i2c-1/1-004b/bd71827-power.4.auto/power_supply/bd71827_bat
```

```
[root@spaBW root]# ls -l /dev/input/by-path/
total 0
lrwxrwxrwx    1 root     root             9 Apr 30 16:42 platform-2-0024-event -> ../event1
lrwxrwxrwx    1 root     root             9 Apr 30 16:42 platform-bd71828-pwrkey.6.auto-event -> ../event2
lrwxrwxrwx    1 root     root             9 Apr 30 16:42 platform-ntx_event0-event -> ../event0
```

**Comment by ptrm** [comment]
Modified `frontend/device/kobo/device.lua` as below (copied from Clara 2e, the `hasReliableMxcWaitFor = true` is a wild guess attempt at fixing input, was false initially). Changed devices and added `isMTK = true`

```lua
-- Kobo Clara BW:                                                                                                                                             
local KoboSpaBW = Kobo:extend{                                                                                                                            
    model = "Kobo_spaBW",                                                                                                                                 
    isMk7 = yes,                                                                                                                                              
    hasEclipseWfm = yes,                                                                                                                                      
    canToggleChargingLED = yes,                                                                                                                               
    led_uses_channel_3 = true,                                                                                                                                
    hasFrontlight = yes,                                                                                                                                      
    display_dpi = 300,                                                                                                                                        
    hasNaturalLight = yes,                                                                                                                                    
    frontlight_settings = {                                                                                                                                   
        frontlight_white = "/sys/class/backlight/mxc_msp430.0/brightness",                                                                                    
        frontlight_mixer = "/sys/class/backlight/lm3630a_led/color",                                                                                            
        nl_min = 0,                                                                                                                                           
        nl_max = 10,                                                                                                                                          
        nl_inverted = true,                                                                                                                                   
    },                                                                                                                                                        
    battery_sysfs = "/sys/class/power_supply/bd71827_bat",                                                                                                        
    power_dev = "/dev/input/by-path/platform-bd71828-pwrkey.6.auto-event",                                                                                           
    -- Board is eerily similar to the Libra 2, so, it inherits the same quirks...                                                                             
    -- c.f., https://github.com/koreader/koreader/issues/9552#issuecomment-1293000313                                                                         
    hasReliableMxcWaitFor = yes,                                                                                                                               
    isMTK = yes,
}
[...]
elseif codename == "spaBW" then
    return KoboSpaBW
```

KOreader runs and displays UI. On the first run it displayed the manual, and tapping on the text selected it, as if koreader treated the display as being touched initially. On second runs I got file browser, and managed only to click the home icon before it froze. Log and photo below

[crash.log](https://github.com/koreader/koreader/files/15167243/crash.log)

![20240430_172817](https://github.com/koreader/koreader/assets/366258/ce110a02-e5c8-4a36-8718-fbe75d7d21cd)

**Comment by Frenzie** [comment]
Some simple things to try would be touch_snow_protocol and touch_phoenix_protocol even if that seems unlikely. There's also touch_mirrored_x and touch_mirrored_y (not relevant to touch being interpreted as hold but relevant to location).

**Comment by ptrm** [comment]
Confirming `touch_snow_protocol = true,` working on BW.

Wifi toggle, warmth, night mode, frontlight, sleepcover, power button sleep, simple multiswipes (two finger frontlight) tested so far

**Comment by c0eos** [comment]
Some more progress, the colours are now (temporarily) fixed! The issue was as I thought, with BGR instead of RGB.

I commented out `self.hasBGRFrameBuffer = yes` in the `function Kobo:init()` function and it works, but I think it'll be cleaner to add a flag such as `isRGB` in the `local Kobo = Generic:extend` function...

```lua
        if self.screen.fb_bpp == 32 then
            -- Ensure we decode images properly, as our framebuffer is BGRA...
            logger.info("Enabling Kobo @ 32bpp BGR tweaks")
            -- self.hasBGRFrameBuffer = yes
        end
```

---

If anyone with a Libra Colour can fill the device definition, I can then submit a preliminary pull request?

**Comment by tymmej** [comment]
I have two problems:
1) starting USB Mass Storage reboots device, after it `.kobo/Kobo/Kobo eReader.conf` is almost empty
2) connecting to Wifi also reboots device and `.kobo/Kobo/Kobo eReader.conf` is almost empty

`reboots` == screen with 3 dots and back to nickel

```
-- Kobo Libra Colour:
local KoboMonza = Kobo:extend{
    model = "Kobo_monza",
    isMk7 = yes,
    hasEclipseWfm = yes,
    canToggleChargingLED = yes,
    led_uses_channel_3 = true,
    hasFrontlight = yes,
    hasKeys = yes,
    display_dpi = 300,
    hasNaturalLight = yes,
    frontlight_settings = {
        frontlight_white = "/sys/class/backlight/mxc_msp430.0/brightness",
        frontlight_mixer = "/sys/class/backlight/lm3630a_led/color",
        nl_min = 0,
        nl_max = 10,
        nl_inverted = true,
    },
    battery_sysfs = "/sys/class/power_supply/bd71827_bat",
    power_dev = "/dev/input/by-path/platform-bd71828-pwrkey.6.auto-event",
    isSMP = yes,
    hasColorScreen = yes,
    isMTK = yes,
    touch_snow_protocol = true,
}
[...]

elseif codename == "monza" then
    return KoboMonza
```

**Comment by tymmej** [comment]
@c0eos fix for RGB also works on Libra Color, but it's necessary to refresh cache about books to fix wrong covers.

`touch_snow_protocol = true,` seems not requirued - there's warning in `crash.log` that hardware does not it and I do not see difference without that line.

**Comment by Frenzie** [comment]
@c0eos 
> I'll be damned, but `touch_snow_protocol = true,` works!

Very good, then with any luck nothing more needs to be done there. ;-)

**Comment by eddyfadeev** [comment]
Keys are working, but reversed. To scroll down you press up, to scroll up you press down

**Comment by eddyfadeev** [comment]
> Keys are working, but reversed. To scroll down you press up, to scroll up you press down

nvm, all good :)

**Comment by NiLuJe** [comment]
FWIW, for people with shell access, I posted a few more specific requests for logs/tests in https://github.com/koreader/koreader/pull/11737#issuecomment-2087856550 ;).

**Comment by erangaj** [comment]
> FWIW, for people with shell access, I posted a few more specific requests for logs/tests in [#11737 (comment)](https://github.com/koreader/koreader/pull/11737#issuecomment-2087856550) ;).

I'd love to help, but I cannot build koreader on my pc for some reason. Is there a downloadable koreader kobo package with your fix included, so I can install it and get the logs?

**Comment by NiLuJe** [comment]
You don't need to build anything, run a recent nightly and apply the PR any way you see fit (i.e., patch or replace).

**Comment by erangaj** [comment]
> You don't need to build anything, run a recent nightly and apply the PR any way you see fit (i.e., apply the GH diff via patch or just replace the affected files with the ones from the PR).

Managed to run with the patch. I am having  libra color, so didn't collect the log files. (Please let me know if you want logs from another libra color)

The rotation wasn't right, but @tymmej 's fix worked. The physical buttons are still swaped.

**Comment by tymmej** [comment]
There’s option to swap buttons in GUI so I left it as is.

**Comment by kyxap** [comment]
hey, is this still does not work? I've tried `[koreader-kobo-v2024.04-32-geb6e5e3c2_2024-05-10.zip]` and reader does not go into restart after eject and power cable take off. 
It just found some unknown authors...

Im just got the reader so I may missing something, what I've done so far:

- tried with and without this:
```bash
[FeatureSettings]
ExcludeSyncFolders=(\\.(?!kobo|adobe).+|([^.][^/]*/)+\\..+)
```
- downloaded zip
- extract to root of the clara bw
- eject/took cable off

anything else is missing? 

ps: I'm not sure how to read logs from the device

**Comment by meguminnet** [comment]
> extract to root of the clara bw

I have koreader into the .adds folder, not the root as per the guide:

https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices#manual-installation-method-based-on-kfmon

**Comment by kyxap** [comment]
oh yeah.... different manuals say diff folders... after multiple re-installs it start to work! thanks!

**Comment by Bapf** [comment]
While the fixes from @tymmej are fixing the rotation when triggering it (meaning rotating the device), the default rotation is still 180 degrees of, meaning when I start KOReader or when I exit from a book to the library the view it is upside down and I have to tilt the device to get the correct orientation.
Other than that (and the reboot when exiting) it really works great on the Libra Colour.

**Comment by tymmej** [comment]
@Bapf my fixes are no longer needed, it was fixed in fbink.

You can try `Keep current rotation across views` setting.

**Comment by Ciantic** [comment]
I have brand new Kobo BW, installed with the install.ps1 "OCP-KOReader-v2024.04.zip"  "OCP-KFMon-1.4.6-66-ga63e9af.zip" "OCP-Plato-0.9.42.zip"

NickelMenu appeared and KOReader underneath it, but it as I clicked it it just restarted.

Uninstalled for now.

But if I understand only thing I would have needed is: touch_snow_protocol = true?

**Comment by Frenzie** [comment]
Not the only thing, but the primary thing. Grab a nightly from http://build.koreader.rocks/download/nightly/

**Comment by raffaem** [comment]
> Not the only thing, but the primary thing. Grab a nightly from http://build.koreader.rocks/download/nightly/

I have tried that.

I renamed the zip file to `OCP-KOReader-v2024.04.zip` otherwise the install script would tell me that there was nothing to install.

But the installation failed with:
```
* Sanity check . . .
* Installation FAILED: Unpacking was ineffective (no KoboRoot tarball) o_O !
* As a result, the device may have been left in an inconsistent state!
* Please note that NO automatic cleanup will be done!
* As such, before unplugging your device, consider removing:
* The following folders:
        /run/media/raffaele/KOBOeReader/.adds/kfmon
        /run/media/raffaele/KOBOeReader/.adds/koreader
        /run/media/raffaele/KOBOeReader/.adds/plato                                                                   [OK: Already gone]
* As well as the following files:
        /run/media/raffaele/KOBOeReader/.kobo/KoboRoot.tgz                                                            [OK: Already gone]
        /run/media/raffaele/KOBOeReader/kfmon.png
        /run/media/raffaele/KOBOeReader/koreader.png
        /run/media/raffaele/KOBOeReader/icons/plato.png                                                               [OK: Already gone]
[ble: exit 255]
```

Maybe it's better to wait for the official release

**Comment by raffaem** [comment]
I have succeeded with the [Manual Installation Method based on KFMon](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices#manual-installation-method-based-on-kfmon)

**Comment by didier31** [comment]
KOReader is a very nice job. 
The last nightly build works for me on Kobo Libra Color with manual installation.

Thank you so much. I have no word to express my gratefulness.

**Comment by Kelvyn88** [comment]
@raffaem @didier31 can you explain how to do it? I followed the same manual steps but it is not orking for me in Kobo Libra Colour.

**Comment by mergen3107** [comment]
@Kelvyn88 
instead off current release you need currently nightly release from: https://build.koreader.rocks/download/nightly/

**Comment by dontcrash** [comment]
Installed koreader-kobo-v2024.04-220-g7ef3e475c_2024-06-29 on my Kobo Libra Colour
Working absolutely flawlessly so far.
Great work team!

**Comment by lostinpadania** [comment]
> I have succeeded with the [Manual Installation Method based on KFMon](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices#manual-installation-method-based-on-kfmon)

Yes, it works perfectly. The only problem is that you can't access koreader from the bottom menu bar, but only in the library

**Comment by meguminnet** [comment]
Latest update of firmware broke that in Kobo Clara Colour, but starting the installation from the beginning and overwriting the files  with KFMon 1.4.6 fixed the NickelMenu for me.

**Comment by mergen3107** [comment]
If you use One-Click Installer, then enable NickelMenu for KOReader, it will survive firmware updates.

See files in .adds/nm
There is one line to uncomment
(also remove kfmon’s link to KOReader, otherwise you will have two “KOReader” entries)

**Comment by KentBrockman** [comment]
I kept getting this error:

`Installation FAILED: Unpacking was ineffective (no KoboRoot tarball) o_O !`

And thought that was suspicious. After a bit of fiddling, I have koreader back on my device running latest. Here's a quick run-down of what I did. Everything done below was on the kobo USB mass storage device 
1. Download `KoboRoot.tgz` from [NickelMenu](https://github.com/pgaskin/NickelMenu) and put it in the `.kobo` directory
2. Run the one-click installer. I installed v2024.11 but I don't think this matters. Run whatever version you like. The "installation failed" error above was replaced by normal success message.
3. At this point I unplugged my device and it ran through the update. When it was complete, I had NickelMenu but no entry on it to start koreader. That indicated kfmon wasn't installed, so I plugged my Kobo back into my PC and created this file:  `.adds/nm/kfmon` and added the following text to it:

```
# Automatically populate NickelMenu with active KFMon watches

generator : main : kfmon
```

After ejecting my device, I now had a KOReader menu entry under NickelMenu and everything seems to work fine.
