### ISSUE TITLE
FR: Fainter overlap line

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11734]
Would it be easy for the horizontal line that indicates the page overlap to become fainter? Or at least have the option to select its thickness.
When it's as thick as the letters, it looks like a strikethrough and makes it hard to read when it falls on them.

Thank you!

**Comment by hius07** [comment]
Please try different thickness and colours and give your recommendation:
https://github.com/koreader/koreader/blob/8ff846ba6e1ad3f554d6409c231f569b3a147feb/frontend/apps/reader/modules/readerview.lua#L224-L227
https://github.com/koreader/koreader/blob/8ff846ba6e1ad3f554d6409c231f569b3a147feb/frontend/ui/size.lua#L63-L68

**Comment by ichnilatis-gr** [comment]
I made the line grey and I tried two sizes, medium and thin. I give you some screenshots.

Grey -  thin line in scanned pdf

![Reader_2024-04-30_202514 (Medium)](https://github.com/koreader/koreader/assets/76203123/6ef8fea6-b3a0-4b95-b531-ae3af89e1bd9)

Grey - thin line in generated pdf

![Reader_2024-04-30_194738 (Medium)](https://github.com/koreader/koreader/assets/76203123/2bec32f7-da05-44b5-a518-8ad8b00ffff5)

Grey -  medium line in scanned pdf

![Reader_2024-04-30_202715 (Medium)](https://github.com/koreader/koreader/assets/76203123/1330ac0f-c2dc-4cc5-937c-443731f5d075)

Grey -  medium line in generated pdf

![Reader_2024-04-30_195017 (Medium)](https://github.com/koreader/koreader/assets/76203123/630ee348-f54b-4c15-a911-c1dcb8bf2c9c)


I thin that the grey and medium line is better, as the thin one may not be visible to some.

**Comment by hius07** [comment]
Done in https://github.com/koreader/koreader/pull/11761.

**Comment by ichnilatis-gr** [comment]
Excuse me. May I ask if there is a way to have a dashed line? I would like to test it. Thank you!

**Comment by hius07** [comment]
Replaced the solid line.
[readerview.lua.txt](https://github.com/koreader/koreader/files/15282023/readerview.lua.txt)

**Comment by ichnilatis-gr** [comment]
Thank you!
I like it. What do you think?

![Reader_2024-05-11_130953 (Medium)](https://github.com/koreader/koreader/assets/76203123/7dace54f-5a39-405d-bff5-16e0c4a84439)

**Comment by hius07** [comment]
I do not use overlapped pages, no strong opinion. Looks pretty nice.

**Comment by ichnilatis-gr** [comment]
Could it be merged or perhaps a new option be added?
