### ISSUE TITLE
BUG: Does Not Trigger Refresh / Somehow 'Cheats' Tap Detection on Meebook M7

### ISSUE THREAD

**Issue by Bluemoondragon07** [koreader/koreader#11733]
* KOReader version: 2024.04 
* Device: Meebook M7
 
#### Issue

Using Meebook's default launcher, MeeOS, apps can be set to a specific refresh rate. A refresh rate of 5 refreshes the screen (full-screen refresh) every 5 taps. A refresh rate of 10 refreshes the screen every 10 taps. A refresh rate of 0 does not refresh the screen at all.

In most apps, such as Moon+ Reader or Pocketbook Reader, page turns are registered as taps and contribute to this refresh rate. I did notice that some UI elements, such as the menu button in Moon+ Reader, do not trigger this full-screen refresh. Tapping empty spaces in apps typically do not trigger the refresh either. However, in general, tapping an **element**, such as a button or a page-turn tap zone, triggers this refresh rate. 

However, KOreader will never trigger a  refresh. It does not matter what the refresh rate is set to; the app always behaves as if the refresh rate is set to 0 and has to be refreshed manually. Turning pages and tapping menu items, I guess somehow 'cheats' the Meebook's 'tap detection'? 

To find out what was going on, I set the app's refresh rate to 1. Still no refreshes. Inside KOreader I opened up Developer options > Start compatibility test to see if it would respond to any of the eInk refresh drivers. And, the screen started refreshing! 

No, none of the E-ink drivers work with the Meebook. It refreshed because it recognized me tapping elements--the dropdown menus. It didn't recognize the 'test e-ink' or 'test lights' buttons, so they didn't trigger a refresh. 

So, I'm guessing specific Android elements trigger this refresh, and KOreader does not have any of them. Therefore, KOreader never triggers refreshes (except in the compatibility test for Android devices).

By the way, I also tested the F-Droid version, and yields the same results.

Can this be changed? Can tap zones use this Android element? 

#### Steps to reproduce

1. open KOreader optimization from MeeOS, check **application refresh control** and change the application refresh rate to 1, so that it should refresh on every tap.
2. open the KOreader app and play around a bit. Tap on things. Turn pages in a book. Note that none of these activities triggers a refresh.
3. Open Developer options > start compatibility test and tap the dropdown buttons. Note that the screen is refreshing properly.

#### Note

One more thing I want to add is that the page up / page down functions in other reading apps usually trigger these refreshes as well. For example, the Meebook M7's physical page turn buttons can be set to pg up / pg down or volume up / volume down. In Pocketbook and Moon+ Reader, these buttons trigger refreshes just like taps. This is not the case in KOreader.

So, I guess there's also something weird with the way these button inputs are registered?

**Comment by Frenzie** [comment]
I assume that means for example ScummVM doesn't refresh either?

**Comment by Frenzie** [comment]
The cause seems clear: this isn't a "regular" app but closer to how most games work. I doubt there's a sane way to work around whatever MeeOS expects but pinging @pazos for more info.

**Comment by Bluemoondragon07** [comment]
Maybe we can work around this with this method?  - - > #11429

I tried making a profile that would simulate a refresh by toggling Night mode twice, but it executes both toggles at the same time anyway. There are more manual ways to get around this, but I think there should at least 'simulated' kind of fallback refresh that can be toggled.

**Comment by pazos** [comment]
> Can this be changed? 

Nope.

> Can tap zones use this Android element?

Nope.

> Maybe we can work around this with this method?

I hope nobody tries to implement that.


> The cause seems clear: this isn't a "regular" app but closer to how most games work. 

Yay, or like vlc while playing a video (but with a frame each few seconds). We just update a buffer each time there's a change.

What Mebook implemented is a hackish workaround that might work with apps that use android elements to build their UI but it will never work with KOReader.

Each device or family of devices requires a routine to refresh the screen.
You can keep an eye on https://github.com/koreader/android-luajit-launcher/issues/459 for this particular device.

**Comment by LeonidCherkashin** [comment]
I had a problem with the screen not refreshing completely on my Meebook m6, so I fixed it with this patch:

```lua

--[[
    KOReader user patch: e-ink full-refresh fix for Meebook M6 (Rockchip RK3566)

    PROBLEM
    -------
    On this device, KOReader's "Full refresh" menu action and the built-in
    "E-ink full refresh rate: every N pages" setting did nothing, while the
    "TEST E-INK" button under
        Tools -> More tools -> Developer options -> Start compatibility test
    (with "Rockchip RK3566" selected) did visibly flash the screen.

    ROOT CAUSE
    ----------
    frontend/ffi/framebuffer_android.lua (koreader-base) implements the full
    refresh like this:

        function framebuffer:_updateFull()
            if eink_platform == "rockchip" then
                android.einkUpdate(full)                                  -- (A) no-coordinates call
            else
                self:_updatePartial(full, delay_page, 0, 0, w, h)         -- (B) coordinate-based call
            end
        end

    android.isEink() reports eink_platform == "rockchip" on this device, so
    stock KOReader takes path (A). Testing showed that path (A) is actually
    the one that doesn't work on this specific unit/firmware, while path (B)
    (the one stock code reserves for non-"rockchip" platforms) does work.
    In other words, the platform detection is right, but the "rockchip"
    branch's assumption about which call works is backwards for this
    device/build.

    FIX
    ---
    Force _updateFull() to always take the coordinate-based path (B),
    regardless of the detected eink_platform.

    Once this is in place, both the "Full refresh" menu action and the
    built-in "E-ink full refresh rate" page-count setting work correctly on
    their own - no extra page-turn tracking logic is needed in this patch.

    INSTALL
    -------
    Copy this file to koreader/patches/2-meebook-m6-eink-fix.lua and restart
    KOReader. Note: user patches do NOT work on the F-Droid Android build
    (package id org.koreader.launcher.fdroid) - you need the regular release
    build (org.koreader.launcher).
]]--

local Device = require("device")
if not Device:isAndroid() then
    return
end

local ok_android, android = pcall(require, "android")
if not ok_android then
    return
end

local ok_fba, fba = pcall(require, "ffi/framebuffer_android")
if not ok_fba then
    return
end

local logger = require("logger")

local is_eink, eink_platform = android.isEink()
local full, _partial, _full_ui, _partial_ui, _fast, delay_page =
    android.getEinkConstants()

logger.info(string.format(
    "meebook-m6-eink-fix: isEink=%s platform=%s isEinkFull=%s",
    tostring(is_eink), tostring(eink_platform), tostring(android.isEinkFull())))

if not is_eink then
    logger.warn("meebook-m6-eink-fix: android.isEink() reports false, aborting.")
    return
end

-- Force the coordinate-based full-update call path (see rationale above).
function fba:_updateFull()
    logger.dbg("meebook-m6-eink-fix: full refresh via coordinate-based einkUpdate()")
    self:_updatePartial(full, delay_page, 0, 0, self:getWidth(), self:getHeight())
end

logger.info("meebook-m6-eink-fix: patch loaded")


```
