### ISSUE TITLE
Can't find new sleep screen menu

### ISSUE THREAD

**Issue by Kageetai** [koreader/koreader#11740]
* KOReader version: 2024.04
* Device: Samsung Galaxy Tab S9+ And Onyx Boox Leaf 2

#### Issue

After updating to version 2024.04 I can't find that [newly reworked sleep screen menu](https://github.com/koreader/koreader/pull/11549) any more. I had used the feature before and set it to use the last book cover. But now wanted to check out the changes, but can't find it.

#### Steps to reproduce

In the settings menu, I am looking into the "Screen" menu and don't see any "Lockscreen" setting, as mentioned in the PDF attached to [the PR](https://github.com/koreader/koreader/pull/11549).
See this screenshot:
![Screenshot_20240501_184702](https://github.com/koreader/koreader/assets/1738309/b9e7508f-8eb0-4796-979d-bf99cae5b566)

**Comment by Frenzie** [comment]
It's not a feature relevant to Android, which has its own lockscreen.

**Comment by Kageetai** [comment]
That is true, but before there was still the setting to safe the latest book cover in a specific folder, which then could be used by the native Android lock screen, therefore the feature was relevant. Is that gone now?

**Comment by Frenzie** [comment]
That's only available inside a book, to set the cover image for that specific book. I'd ping zwim to ask about it but he's busy. :-)

**Comment by Kageetai** [comment]
Oh right, found it now. Forgot that it's only visible when a book is opened. I guess then i misunderstood the new changelog in that regard. My mistake.
