### ISSUE TITLE
Duplicated options on Non-touch

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11747]
* KOReader version: 2024.03.1-55 (on older versions too)
* Device: Kindle 4/5 (non-touch in general)

#### Issue
There is one option duplicated in the menus, one comes from --#8877 and later #8914-- the other not sure.
Both `NEW: Long-press on text` and `Select on text` appear to be the exact same thing with different names.
#### Steps to reproduce
Open any book, go to "page with bookmark > NEW: Long-press on text" the other is found under "page with text > Select on text"

**Comment by Frenzie** [comment]
The former isn't supposed to show on non-touch devices. Maybe something like this would do the trick?

```diff
diff --git a/frontend/apps/reader/modules/readerhighlight.lua b/frontend/apps/reader/modules/readerhighlight.lua
index e80998717..abba38f1f 100644
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -593,6 +593,7 @@ Except when in two columns mode, where this is limited to showing only the previ
     if not Device:isTouchDevice() and Device:hasDPad() then
         menu_items.selection_text = util.tableDeepCopy(menu_items.long_press)
         menu_items.selection_text.text = _("Select on text")
+        menu_items.long_press = nil
     end
 
     -- main menu Search
```

**Comment by Commodore64user** [comment]
that works! should I PR this or will you?

**Comment by Frenzie** [comment]
If you have time to, please do.

**Comment by Commodore64user** [comment]
I found the [guilty] defendant here #8608. 😂

**Comment by Commodore64user** [comment]
> The former isn't supposed to show on non-touch devices. Maybe something like this would do the trick?
> 
> ```diff
> diff --git a/frontend/apps/reader/modules/readerhighlight.lua b/frontend/apps/reader/modules/readerhighlight.lua
> index e80998717..abba38f1f 100644
> --- a/frontend/apps/reader/modules/readerhighlight.lua
> +++ b/frontend/apps/reader/modules/readerhighlight.lua
> @@ -593,6 +593,7 @@ Except when in two columns mode, where this is limited to showing only the previ
>      if not Device:isTouchDevice() and Device:hasDPad() then
>          menu_items.selection_text = util.tableDeepCopy(menu_items.long_press)
>          menu_items.selection_text.text = _("Select on text")
> +        menu_items.long_press = nil
>      end
>  
>      -- main menu Search
> ```

But, with this line added, we do not need tableDeepCopy anymore.

**Comment by Commodore64user** [comment]
I tried to get it to work without `tableDeepCopy` and every approach I try fails... I am sure it will be something silly and obvious once it is solved but for now, I'm stuck.

**Comment by hius07** [comment]
You just have `menu_items.selection_text = menu_items.long_press`, right?

**Comment by Commodore64user** [comment]
> You just have `menu_items.selection_text = menu_items.long_press`, right?

that was the very first thing I tried, and it didn't work for some reason. But now it does, weird.
