### ISSUE TITLE
Close book on suspend

### ISSUE THREAD

**Issue by tymmej** [koreader/koreader#11751]
I want to close the book while suspending device.

The reason is that after wakeup I sometimes want to read different book, download new from OPDS or something else.
In that situation I have bogus entry in calendar view of reading statistics which slightly annoys me :)

The setting `Start with -> File manager` does not work as it's wakeup, not start up.

I've created following user patch to solve the issue:
```
local Device = require("device")

local _beforeSuspend_orig = Device._beforeSuspend

Device._beforeSuspend = function(inhibit)
    local ReaderUI = require("apps/reader/readerui")
    if ReaderUI.instance then
        ReaderUI.instance:onHome()
    end

    _beforeSuspend_orig(inhibit)
end
```

**Comment by poire-z** [comment]
Very use(r) case specific, so best to let it to a user patch; Thanks for sharing :)
