### ISSUE TITLE
Nested dictionary lookup uses original sentence instead of using respective sentence from dictionary

### ISSUE THREAD

**Issue by artjomsR** [koreader/koreader#11754]
* KOReader version: 2024.04
* Device: Kobo sage

#### Issue
When you save a word in vocab builder, it saves the word in context of its original sentence. So if you look up a word from a book, everything works as expected.

However, you can still do dictionary lookups _within_ dictionary's lookup. The problem is that in this case, the wrong sentence is used as context: it uses the original book sentence, rather than the dictionary one

I rely on these sentences for context so it's an important feature, especially since I'm using Anki's SRS to come back to these sentences+words multiple times

#### Steps to reproduce

1. Do a dictionary lookup from any book
2. Do another lookup from the dictionary definition popup
3. Add the word to the vocab builder
4. Close all popups, go to Vocabulary builder from the main menu, find the newly added word.
5. Press on the 3 dots which will show the word in the context of the sentence
6. Observe that the word from the dictionary lookup was used (from the 2nd step) but the original sentence was used (from the 1st step)

https://github.com/koreader/koreader/assets/6875790/6759b9d8-1a2c-4c1e-ac3d-b123baaa82c3

**Comment by poire-z** [comment]
Pinging @weijiuqiao - I guess we didn't think about this case :/

**Comment by weijiuqiao** [comment]
We didn't indeed. In this case, the context should theoretically be the surrounding sentence in the definitions? I'm not sure if its extractable. If not, then it can fallback to null context. I'm also not sure if the context of the bottom of the stack of words can be retained.

**Comment by artjomsR** [comment]
I agree, worst case scenario, if the context can't be extracted, it's better to have a word on its own with no sentence, rather inject the new (nested) word into the original sentence

**Comment by Steven630** [comment]
A related issue would be #12465.

In this case, however, the original context is still needed because it follows the user's tweak of the first query.
