### ISSUE TITLE
koreader doen't launches on kindle PW5 (8GB)

### ISSUE THREAD

**Issue by bheeshmpita** [koreader/koreader#11766]
* KOReader version: KOReader 2024.04 "Sourdough"
* Device: kindle PW5 11th gen (8GB)

#### Issue
koreader doesnt launches

#### Steps to reproduce

(for installation of koreader)
1. jailbreak
2. mrpi installation
3. kual (coplate) installation
4. moving _koreader pw2_ contents to kindle root directory

(koreader launching)
1. go to library section
2. open kual document
3. select 3rd entry 'koreader'
4. select 1st entry 'start koreader'
5. (kindle) interface jumps to kindle home screen, screen refreshes and nothing happens

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/15233794/crash.log)

**Comment by hius07** [comment]
Reinstall NiLuJe's hotfix.

**Comment by bheeshmpita** [comment]
> NiLuJe's hotfix

hi @hius07 , i am new to this ereader and jb thing. Can you please briefly explain about this package and mention its specific name  (is it _K5 JailBreak Hotfix | [JailBreak-1.16.N-FW-5.x-hotfix.zip] | 2024-Apr-21 13:37:00 | 150.2K | N/A | [JB Hotfix]_ mentioned on the tool snapshot page of NiLuJe). as you said 'reinstall' does that mean i was supposed to install it earlier too as i havent installed this before.

**Comment by bheeshmpita** [comment]
thanks, please share the link for the installation procedure as i am not good without guidance.

**Comment by bheeshmpita** [comment]
as the user @hius07 stated, niluje hotfix fixed the issue
