### ISSUE TITLE
Can't open books from library when files are associated on some Pocketbooks

### ISSUE THREAD

**Issue by sdasda7777** [koreader/koreader#11760]
* KOReader version: 2024.04
* Device: Pocketbook Basic Touch

#### Issue
I'm not sure why, but when I set up file associations (Device -> Associate file extensions -> epub, epub3, pdf) so that KOreader would open automatically when starting the reader, I can no longer reliably open books from the system library application or from the "recent books" on home screen. Sometimes it works, but most of the time nothing happens (the given book starts opening only when I manually start KOreader). I should also note that opening books on reader startup works flawlessly, and I have no such issues whatsoever on my other Pocketbook reader (Aqua 2).

If you have any ideas what might help with diagnostics, I'd be most happy to try it out.

**Comment by sdasda7777** [comment]
I do seem to have access to OpenDyslexic on the other reader, but I don't see it in the location mentioned above. Is is possible that KOreader comes with OpenDyslexic, and the error stems from the name clash, or something like that?

**Comment by Frenzie** [comment]
> I don't get any message in the UI, but there does in fact seem to be a `crash.log` entry in `applications/koreader`:

A slightly misleading name. There's always a little bit of info written there (device, version, etc.) but it's where you should look in case there's a crash.

In this case I'm not seeing any issues. The font thing is just a warning/diagnostic message.

**Comment by sdasda7777** [comment]
You're right, I removed the font files and no longer see the "error", but the behaviour prevails. Any other ideas?

I'm thinking whether I could write into the crash.log myself to trace whether the `koreader.app` is even launched or where approximately it crashes.

**Comment by Frenzie** [comment]
This stuff indicates the launch:
```
05/06/24-16:00:12 INFO  initializing for device PBBasicTouch 
05/06/24-16:00:12 INFO  framebuffer resolution: {
```

**Comment by sdasda7777** [comment]
Yes, but the first file, which is in the log after this line, worked without issues. I'm not even sure me trying to open the second file is in the log, because the mention in the log might be from when I opened the KOreader manually.

**Comment by Frenzie** [comment]
I don't know what the PB lifecycle is supposed to be like. Pinging @rjd22 @pazos

**Comment by sdasda7777** [comment]
It seems I can completely avoid the behaviour in question by always killing currently running KOreader instance beforehand. That does kind of sound like a new instance begins the start up, notices the one that is already running, passes on the arguments and quits, but does not switch the old instance to the foreground? Also when I trigger this behaviour, then kill the instance and open a different book, first the new book loads completely, and after that the book with which the behaviour was triggered starts loading, but I don't think that is very relevant.

**Comment by Frenzie** [comment]
A look around suggests https://github.com/koreader/koreader/pull/6620 and #6808.

**Comment by sdasda7777** [comment]
If I were to guess at the moment, my money would be on API for switching tasks changing somewhere between Touch Basic's 4.4 firmware and Aqua 2's 5.20 firmware, and KOreader's code being updated for or written for the newer API. I don't have any other hypothesis that would explain why the exact same configuration works on the newer reader but not on the older one.

**Comment by sdasda7777** [comment]
It seems to me the Pocketbook Basic Touch does not have the `/usr/bin/iv2sh` program, nor the `/usr/bin` directory. Running `find / -name "iv2sh" 2> /dev/null` revealed that two files of this name do exist, one in `/ebrmain/bin/` and one in `/ebrmain/cramfs/bin/`. The same is true for the newer reader, therefore I assume the `/usr/bin/iv2sh/` is a symlink which is not present on the older version?

**Comment by sdasda7777** [comment]
No, it seems like `/usr/bin` is actually itself a symlink to `/ebrmain/bin`. In fact, replacing the former with the latter in the `koreader.app` seems to fix the issue.
