### ISSUE TITLE
FR: Display note in differend line in bookmarks list

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11768]
If the option "highlighted text and note" is selected for the bookmark list, I would prefer the note to be displayed on different line from the highlighted text. 
Sometimes the pencil mark is on a different line from the note text.

This pertains to the new feature found in the nightly versions.

Thank you!

**Comment by ichnilatis-gr** [comment]
@hius07 what do you think?

**Comment by hius07** [comment]
Highly unlikely. You can see that we do not have new lines (paragraphs) in bookmark list.
Building items of several parts (highlighted text, note, page number) slows down the output.
The only improvement that is under construction now: flexible height of the items - the text will take as many lines as it requires, without empty space.

**Comment by ichnilatis-gr** [comment]
All right. You know better. You can close this issue, if you wish.
Thanks!
