### ISSUE TITLE
Missing text in Weblate 

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11767]
* KOReader version: v. 2024.04-15
* Device: PB 628

#### Issue
I can't find the text "Show in items" and the options "highlighted text and note", "highlighted text" and "note, or highlighted text" in Weblate.

**Comment by Frenzie** [comment]
It's caused by https://github.com/koreader/koreader/pull/11563#issuecomment-2094970832

**Comment by Frenzie** [comment]
Fixed by https://github.com/koreader/koreader/pull/11784.
