### ISSUE TITLE
Moving a book to another folder deleted my notes, highlights, bookmarks, and reading progress

### ISSUE THREAD

**Issue by GroenteLepel** [koreader/koreader#11773]
* KOReader version: 2024.04
* Device: PocketBook Touch HD

#### Issue
I moved a book one folder deeper into my folder hierarchy and all my highlights, notes, and reading position are deleted.

#### Steps to reproduce
 1. read book
 2. make note/progress reading/mark as finished
 3. make new folder in the same folder where book is placed
 4. move book to the new folder
 5. boom everything gone
 6. I first saw it was not marked as finished, so I marked it again as finished
 7. saw all my notes were gone, so i moved it back into `../`
 8. again everything gone.

Have I messed up by step 6 and overwritten my metadata file? I did some googling already about it and I think it has something to do with my `.sdr`, but the main reason for making this issue is that it is definetely not clear from koreader itself. I also cannot find anything in the koreader user guide about this when searching for "notes", "highlights", "metadata" or "moving".

[Here's a link to a Reddit post I tried to follow](https://www.reddit.com/r/koreader/comments/183szlc/moved_location_of_books_all_highlights_gone/) but I could not find the settings menu related.

##### `crash.log` (if applicable)
Not sure if applicable. If it is, let me know.

**Comment by hius07** [comment]
> 4\. move book to the new folder

How did you do that, in details?

**Comment by GroenteLepel** [comment]
I saw that there was a `metadata.lua` and a `metadata.lua.old` and both were identical, so I think by marking it as finished after moving it, and then moving it back, fucked me.

**Comment by hius07** [comment]
Yes, that is the proper way of moving a book, sdr folder (containing highlights/notes) is moved together with the book automatically.
Moving a book or marking it as finished should not affect the highlights.
Is the issue reproduced for any book?

**Comment by GroenteLepel** [comment]
Damn it I tried with another book and that worked fine. I don’t know what the issue then is with my original book. I retried it with the book that went wrong and that also worked fine now. 

It was one of the first books I synced via the Calibre extension, but when I try it on another book that was placed there by the Calibre extension and was still untouched, made a highlight and moved it to a new folder and it was also fine. 

Can’t reproduce, seems like a really unfortunate and difficult to trace bug then…

if you have any other ideas I’d be really glad to try to chase it. Otherwise I fear it must be closed for now.

**Comment by ryanwwest** [comment]
@GroenteLepel In the future, you can change the progress/highlights metadata storage mode so that it stores them based on the hash of your document instead of its location (so you can move and copy the document freely without fear of losing anything). Go to Settings cog -> Document -> Book metadata location and change it to the third option (ending in 'hashdocsettings').

Caveat is if you modify a document you're reading, its metadata will get unlinked. Calibre sync might modify the file, so this might only be viable if you don't plan to sync files after starting to read. I use Syncthing to sync my files and metadata to get around this.

**Comment by offset-torque** [comment]
@ryanwwest - Useful new feature, adding this to the user guide. Are you the author (for proofreading the guide text)?

**Comment by ryanwwest** [comment]
Yes, though a lot of others helped.

**Comment by hius07** [comment]
Probably fixed by https://github.com/koreader/koreader/pull/11878.
