### ISSUE TITLE
"Move to archive" action triggers directory metadata and cover refresh

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#11772]
![koreader_movetoarchive](https://github.com/koreader/koreader/assets/84420582/2d8dc176-558a-4faa-92a7-6adf57cd550c)

Choosing `Cancel` in this dialog opens the **File Browser** at the last used directory and starts a metadata and cover refresh. I think this is an unintended behavior. Because when I tap `OK` instead of `Cancel` and then open the **File Browser** manually, this refresh doesn't happen and everything still works ok.

**Comment by hius07** [comment]
Thank you, confirmed.
After testing the issue, I've got the `directory` records in the bookinfo_cache.sqlite3:
```
/mnt/us/books/
/mnt/us/books//
/mnt/us/books///
```
for every book.
