### ISSUE TITLE
Alignment of ruby text is affected by -epub-text-align-last

### ISSUE THREAD

**Issue by yuanshuai0217** [koreader/koreader#11771]
* KOReader version: 2024.04
* Device: moaan mix7 (with Android 11)

#### Issue

The alignment of ruby text is affected by `-epub-text-align-last`, which is not preferred, as according to [JLREQ](https://www.w3.org/TR/jlreq/), ruby text shall be always center-aligned.

#### Steps to reproduce
This is a MWE file: [test_ruby.zip](https://github.com/koreader/koreader/files/15244279/test_ruby.zip)

Ruby text get left aligned, which should be centered instead:

![Reader_2024-05-08_134025_proc](https://github.com/koreader/koreader/assets/31814374/35b26def-3617-462f-a9a6-8d11f93b4b26)

Deleting `-epub-text-align-last: left` from CSS can make it return to normal.

**Comment by poire-z** [comment]
I probably forgot about it in https://github.com/koreader/crengine/blob/1a9e79e25a5b4510d7aaff238d5239f2da70d8d0/cr3gui/data/html5.css#L240-L256 :)

You could (not sure you can on Android) add a line to koreader/data/html5.css:
```diff
--- a/data/html5.css
+++ b/data/html5.css
@@ -243,6 +243,7 @@ sup {
 ruby {
   display: ruby;
   text-align: center;
+  text-align-last: initial;
   text-indent: 0;
 }
 rb, rubyBox[T=rb] {
```
Seems to do the trick:
![image](https://github.com/koreader/koreader/assets/24273478/89f2e8f8-e769-413a-a6fa-a105cad724df)

You could add it to a user/book style tweak if you want to solve your issue today:
`ruby { text-align-last: initial }`

(Minor issue, so it will wait a bit before reaching KOReader.)
