### ISSUE TITLE
FR: Open links in PocketBook web browser

### ISSUE THREAD

**Issue by liskin** [koreader/koreader#11782]
Many PocketBook devices include a web browser, but when clicking a link in KOReader, there's no option to open the link in the browser, there's only an option to show a QR code (which can then be scanned by a smartphone). It would be useful if KOReader offered an option to open it directly on the device browser itself.

I was able to make this work on PB740 (InkPad 3) using the following userpatch (1-pocketbook-browser.lua):
```lua
local PocketBook = require("device/pocketbook/device")
local ffi = require("ffi")
local C = ffi.C
local inkview = ffi.load("inkview")

require("ffi/inkview_h")
ffi.cdef[[
/**
 * @brief OpenTask runs child process or make active existing process of specified exe if exist
 * @param path - path/to/exe
 * @param argc - args ptr
 * @param argv - args count
 * @param flags - TASK_* macros
 * @return 0 if created | 1 if already exist | -1 if fail
 */
int OpenTask(const char *path, int argc, const char * const* argv, int flags);
]]

function PocketBook:canOpenLink()
    return true
end

function PocketBook:openLink(link)
    if not link or type(link) ~= "string" then return end
    local argv = ffi.new("const char *[1]", {link})
    inkview.OpenTask("/usr/bin/browser.app", 1, argv, C.TASK_MAKEACTIVE)
end
```

I'm now seeking advice how to proceed if I wanted to submit this to KOReader as a PR. [`OpenTask`](https://github.com/pocketbook/SDK_6.3.0/blob/dd8de463733a2bc0d53d1214b64734586fac427e/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/local/include/inkview.h#L2375-L2383) is not available in [the old SDK that's used for building KOReader for PocketBook](https://github.com/koreader/koxtoolchain/blob/9ea32657fc942e52ddd1bce6011f05f2bccd7eb2/gen-tc.sh#L174), and I was unable to make this work using `NewTask` (it works once and then keeps segfaulting). So I can't just add `OpenTask` to `base/ffi-cdecl/inkview_decl.c` and use it.

Any ideas?

(I'll keep playing with NewTask and other inkview stuff a bit more but I'm not super hopeful.)

**Comment by liskin** [comment]
`OpenTask` itself seems to be implemented via `NewTaskEx`, but it also calls stuff like `hw_task_findbyappname` and `sendParametersToTaskNoWait` so I guess if I understood ARM assembly or used a decompiler I could theoretically piece a compat implementation of `OpenTask` together…

But then it's probably completely fine to just make this available on modern PocketBooks, if that's something that can be done.

**Comment by pazos** [comment]
https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L400-L402

**Comment by liskin** [comment]
> https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L400-L402

Well, that doesn't really solve anything. I can easily check for the existence of `OpenBook` this way:
https://github.com/koreader/koreader-base/blob/9a90ea881201ae64f188150b4e3c02daeb3901bc/ffi/input_pocketbook.lua#L17

But the issue is that it needs to be declared first, and I'm not meant to change `base/ffi/inkview_h.lua` manually, it's generated from `base/ffi-cdecl/inkview_decl.c` which uses the real `inkview.h`, but the one used is too old and doesn't have `OpenBook`.

I can obviously just `ffi.cdef` it manually but is that really something I'm meant to do?

**Comment by pazos** [comment]
> Well, that doesn't really solve anything. I can easily check for the existence of OpenTask this way

cool :)

>But the issue is that it needs to be declared first, and I'm not meant to change base/ffi/inkview_h.lua manually, it's generated from base/ffi-cdecl/inkview_decl.c which uses the real inkview.h, but the one used is too old and doesn't have OpenTask.

> I can obviously just ffi.cdef it manually but is that really something I'm meant to do?

It is totally ok to define platform's behaviour manually. see  [android cdefs](https://github.com/koreader/android-luajit-launcher/blob/c1c82a5db3d0989adf92140092108c55c110e1c6/assets/android.lua#L28-#L1288
)

Please keep `base/ffi/inkview_h.lua` as is and put your code somewhere else.

I'm not very fan of our current base/front split so maybe others can give you some suggestion.
I guess it belongs to base, I don't know if it worths the hussle to move it there.

**Comment by liskin** [comment]
Armed with https://ghidra-sre.org/, I've actually managed to make it work using `NewTaskEx` as well, so I might not need to declare `OpenTask` after all. I'll keep playing with it for a bit more as it's quite fun and then open a PR once I have something robust enough 🙂
