### ISSUE TITLE
Hot swapping dictionaries unavailable on NT devices

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11783]
* KOReader version: Sourdough
* Device: kindle 4 (Applies to all non-touch devices)

#### Issue
Hamburger menu in the dictionary lookup/wiki pop up box inaccessible to non-touch users.
When using the dictionary, this option allows the user to quickly hot swap dictionaries.

<img src="https://github.com/koreader/koreader/assets/97603719/75ed1b98-8799-4711-8d3b-af09cfe1a99e" width=40% height=40%>

#### Steps to reproduce
Select a word to bring up dictionary, press up/down to cycle through the menu. Suffer in silence as the menu loops back without ever reaching the burger. Cry.

**Comment by Commodore64user** [comment]
forgot to say, the edit button next to 1/2 also is inaccessible.

**Comment by hius07** [comment]
As a Master of NT devices you may want to investigate the work of FocusManager in, for example, the Menu widget (our lists).

`self.layout` is populated with menu items:
https://github.com/koreader/koreader/blob/12c3c190b012e8c4b070d3e0b4e66b2878a89c7a/frontend/ui/widget/menu.lua#L1081-L1082
then the TitleBar left and right buttons are added:
https://github.com/koreader/koreader/blob/12c3c190b012e8c4b070d3e0b4e66b2878a89c7a/frontend/ui/widget/menu.lua#L1096-L1097
and finally `self.layout` goes to FocusManager who handles key pressings:
https://github.com/koreader/koreader/blob/12c3c190b012e8c4b070d3e0b4e66b2878a89c7a/frontend/ui/widget/focusmanager.lua#L46-L53
and so on.

I'm afraid the touchscreen users are not much encouraged to dig into it.

**Comment by Commodore64user** [comment]
> As a Master of NT

I am not the master, @comphilip is true 'master of puppets' here. with his magnificent PRs #8712 and later #8859 and his masterpiece here #8877. I am at best a monkey with a typewriter.
