### ISSUE TITLE
FR: Paginated Bookmark details

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#11799]
Thanks to the new edit bookmark feature, it is now possible to correct small errors in bookmark details (thanks for this!). 

However, opening each bookmark requires one to go back to the Bookmarks screen and long-pressing each individual bookmark to open it. 

**Describe the solution you'd like**

A paginated view of the bookmarks (similar to the dictionary viewer) would offer the following advantages:

- Convenient review of all highlights and notes in the book page by page (particularly useful for highlights in scanned books, where the quality of the highlighted text can only be verified by opening the plain-text bookmarks)
- Ability to quickly correct small errors (e.g., from OCR or hyphenation) 'on the fly', without needing to long-press each bookmark separately.

Mock-up of Bookmark details with `current item` / `total items` in the header and additional previous / next arrow buttons 
(arrow buttons could also be placed on top of the existing buttons instead): 

![image](https://github.com/koreader/koreader/assets/95502269/260bc3fd-15d3-4d32-b6f2-1b9b2e69ded3)

**Comment by hius07** [comment]
Done in https://github.com/koreader/koreader/pull/11825.
