### ISSUE TITLE
Can not open feeds from Newsdownloder plugin after last update

### ISSUE THREAD

**Issue by pyromaker** [koreader/koreader#11808]
* KOReader version: 2024.04
* Device: Kobo Libra 2 BW

#### Issue
Hello guys, after the last update I can not open any feeds after syncing with Newsdownloader plug-in.

![IMG_8883](https://github.com/koreader/koreader/assets/102173856/0c917998-5e5f-4583-a858-5c871b2d4e70)

I apologise I do not have access to a pc these says. Perhaps this photo can help?

**Comment by Frenzie** [comment]
The photo doesn't really seem to say anything. What specifically is it that you do?

**Comment by pyromaker** [comment]
After syncing news feeds I attempt to open an article and immediately I receive this error

**Comment by Frenzie** [comment]
Is this still an issue in the current release?

**Comment by pyromaker** [comment]
Hi,I assume it was fixed since I hadn't this issue anymore with the next update

**Comment by Frenzie** [comment]
Thanks!
