### ISSUE TITLE
Screen is not full screen on Boyue T62

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1180]
Hi

I am trying to use KR on T62 and Koreader is not full screen. I mean it is missing some maybe %15 at the bottom (where the system tray  would be normally). I disabled tray in the system, and KR is the only one that not reclaiming that space. Normally I do not use the tray area.

It might not be related to tray at all. Just reporting it.

T62 is using Android 4.2.2

**Comment by chrox** [comment]
You can patch koreader to have a full screen now with the latest nightly build.
Just create a file `koreader/patch.lua` at your sdcard and write in the following content:
```
local screen = require("android").screen
screen.height = screen.height + 80
```
.

**Comment by ozairahmad** [comment]
Thanx chrox, 
This removed the black strip.
Initially I updated the app and did not uninstalled old version then typed the texts in device using "es explorer" but it didn't work, 
then i uninstalled old version, formatted the device using "backup and restore", created the file by copying text from your post, installed nightly release and restart again.
It worked flawlessly.

Thank you once again.

**Comment by gerroon** [comment]
I can confirm that the patch.lua solution work

**Comment by ozairahmad** [comment]
Hi,Thanks for the solution. Somehow nightly released are crashing too frequently on my t62d. Stable release is very stable in fact but has black strip on screen. I am wondering is there anything I can modify in setting or is it possible to ‎merge only this patch solution in stable release? Regards, Ozair                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: gerroonSent: Saturday 11 April 2015 9:51 AMTo: koreader/koreaderReply To: koreader/koreaderCc: ozairahmadSubject: Re: [koreader] Screen is not full screen on Boyue T62 (#1180)I can confirm that the patch.lua solution work

—Reply to this email directly or view it on GitHub.
