### ISSUE TITLE
Input box will reset if you change keyboard layout

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#11812]
* KOReader version: last nightly build
* Device: kindle PW3

#### Issue
if you try to add a new opds you should fill some data like server url or name. but if you change keyboard language you will lost anything you input in input box
#### Steps to reproduce
1. add two keyboard layout (for example english and persian)
2. from top menu tap on magnifire
3. tap on opds catalogs
4. tap on plus icon on to corner
5. in new dialog enter a name in `catalog name` field
6. go to next field `catalog url` and change keyboard layout to persian
as you see all input in catalog name lost

Note: English and Persian keyboard has different height (Persian keyboard not have row number). maybe that the resean of this bug. when you switch keyboard dialog redraw too.

do you need any more data to debug the problem?

**Comment by hius07** [comment]
True. We keep the entered text for one-line input
https://github.com/koreader/koreader/blob/2c6808ba78bb7dd38117d57643c86e6101aeb5fa/frontend/ui/widget/inputdialog.lua#L628-L630
but have not adapted this for multi-input dialog.
