### ISSUE TITLE
Kobo Clara BW: huge battery usage, gesture for light/warness lagging 

### ISSUE THREAD

**Issue by kyxap** [koreader/koreader#11820]
* KOReader version: koreader-kobo-v2024.04-32-geb6e5e3c2_2024-05-10
* Device: Kobo clara bw

#### Issue
I know this is maybe too early to talk since I'm using pre release version but I want to report/ask what to expect in future releases 

I'm completely new user of koreader but in the same time I'm surprised how many awesome stuff is already build and how much potential stuff can be build in the future!

Two issue that let me think if I should keep Clara BW or look for another e-readear for better koreader support

1) Battery life  
- I'm loosing around 10% per ~1.5h while reading 1 book with light/warm enabled, occasionally go back and force for footmarks

Is this expected? Is this kobo issue? clara? some improvement could be done in new release version? 

2) Default gesture up and down on left/right of the screen for light/warmness is lagging
UPD: 
By "lagging" I mean when you do swipe up/down it randomly ignores the move (no light/warmness change). 
It hard to understand how fast or slow you should do the swipe and it seems like it just randomly decide to change it. Same for how far from the left/right screen border you should do swipe. 
For example you can do 3 swipes up and device will react only on 1 of the swipes.
Mainly I'm comparing the same gesture with original firmware/reader app, it works much smoother with almost zero delay.
You can change the lights even without taking finger off the screen which is much cooler since you can't actually be sure if its will be +1 +3 +5 change. So not sure if its a bug or something to improve in ux 

#### Steps to reproduce

see above

**Comment by offset-torque** [comment]
Your total reading time of ~15 hours is nearly same as my Kobo Libra, which has the same capacity battery as your device **kyxap**. Remember that our devices has pretty small batteries. Even entry level phones these days has 3 times larger battery than these devices. And manufacturers mislead by promising **"weeks of battery life"** but when you read the small letters it is like **"30 minutes of reading per day with wifi off..."**.

Probably KOReader is already optimized to the max on your device which leaves your options to:
- Charge more frequently or carry a power bank
- Upgrade your battery with a larger one from third party sellers (void warranty, technical and risky)

There are devices with bigger batteries but they generally have Android OS which has relatively higher power consumption due to all background services. So I am not sure that would be a meaningful upgrade for reading time. Someone else who has experience with them can comment here.

**Comment by NiLuJe** [comment]
1. Enable a standby timer in the relevant device settings (this is disabled by default, and wouldn't have been accessible in the original PR if you ever tried that manually).

2. Define "lagging"? I don't see anything out of the ordinary on the Libra Colour, which supposedly uses the same PWM controller. Said controller is very very very awful, though.

**Comment by NiLuJe** [comment]
FWIW, the power efficiency on these SoCs is roughly as expected.

The lab126 imp is still more efficient, but it's nonetheless a fair bit better than previous NTX boards used on kobos (even the ones that weren't horribly broken like the sunxi ones ;)).

c.f., https://github.com/koreader/koreader/issues/9435#issuecomment-1214257679

(Which, yes, is completely useless as you can't compare shit in this table; re-doing proper captures to generate a table is on my pile of crap to eventually get to).

**Comment by jonnyl2** [comment]
>Also, never trust the actual value shown in the battery gauge. Trust how long it actually lasts until it shuts down instead. This has always been true, but is especially true on those new devices because the PMIC does wonderfully wonky things with the battery gauge.

@NiLuJe: Does this equally apply to the stock software? Or does that have different and more accurate ways of measuring charge state available to it than KOReader does?

**Comment by Frenzie** [comment]
I've never noticed any difference in that regard when reading in Nickel.

**Comment by kyxap** [comment]
> Your total reading time of ~15 hours is nearly same as my Kobo Libra, which has the same capacity battery as your device **kyxap**. Remember that our devices has pretty small batteries. Even entry level phones these days has 3 times larger battery than these devices. And manufacturers mislead by promising **"weeks of battery life"** but when you read the small letters it is like **"30 minutes of reading per day with wifi off..."**.
> 

Not sure if I understand how small letters (you mean font size) impacting the battery? I was using 25.5 for last book, not sure if can be considering "small". 

Also I'm coppering this to my previous kindles, the one I have is pw 7th gen which has similar battery capacity it actually takes weeks before re-change. Not like 3 days and you got 50% left. But there no "warm" light so maybe that is a difference?

**Comment by kyxap** [comment]
> 1. Enable a standby timer in the relevant device settings (this is disabled by default, and wouldn't have been accessible in the original PR if you ever tried that manually).

I forgot about this but some how I've enabled it the first hours of using of koreader

> Also, _never_ trust the actual value shown in the battery gauge. Trust how long it actually lasts until it shuts down instead. This has always been true, but is especially true on those new devices because the PMIC does wonderfully wonky things with the battery gauge.

I was reading somewhere that its not recommended to wait till device is goes to 0% and shuts down

> 2. Define "lagging"? 

I've updated the original post

**Comment by Frenzie** [comment]
> Not sure if I understand how small letters (you mean font size) impacting the battery? I was using 25.5 for last book, not sure if can be considering "small".

The small print refers to the illegible stuff they sometimes put on contracts.

**Comment by NiLuJe** [comment]
> @NiLuJe: Does this equally apply to the stock software? Or does that have different and more accurate ways of measuring charge state available to it than KOReader does?

Yup. There's no secret sauce anywhere.

> I was reading somewhere that its not recommended to wait till device is goes to 0% and shuts down.

Again, the battery meter is a lie ;). 0% does not mean a dead battery. It'll shut down well before the voltage gets low enough to be problematic.

**Comment by NiLuJe** [comment]
As for .2, the behavior is just different: the % delta is computed based on the gesture's distance, so it's *always* an "on lift" change.

If you want an "on pan" change, swipe *inside* the brightness/warmth bar in the frontlight widget itself.

**Comment by NiLuJe** [comment]
I cannot vouch for the accuracy of the gesture on your device, as it's using a different touch panel than mine.

Verbose debug logs will tell us whether there's a gesture misdetection or not.

**Comment by kyxap** [comment]
added debugs in upd2: ^

**Comment by NiLuJe** [comment]
Please attach an actual file, and please post it in a dedicated answer; updates are *extremely* hard to track and make everything super confusing when you review an issue later.

**Comment by NiLuJe** [comment]
This will also ensure that the log is complete, because that excerpt is way too short to be meaningful.

**Comment by kyxap** [comment]
[crash.log](https://github.com/koreader/koreader/files/15379306/crash.log)
done

**Comment by kyxap** [comment]
I've never turned off wifi on kindle manually :| it just automatically goes to some kinda sleep mode, why to stay connected if there no reason for that? Anyway I'm not sure I fully understand all settings that you mentioned above but now I have those:
 
![unnamed2](https://github.com/koreader/koreader/assets/3080529/844bcc56-a99d-4345-a6a3-a3107f13955d)

is what yo've recommended? 

Thanks for looking into power consumption, also I've uploaded the crash log more for issue #2 which is no response/lagging on swipes for lights, not sure if there any issue in the logs but seems to be in shows all screen manipulations

**Comment by Frenzie** [comment]
Which naming are you referring to precisely?

**Comment by NiLuJe** [comment]
> It seems to be off by default. Shall we change some defaults?

It's contingent on actually being implemented, and I don't recall exactly on which platforms that is exactly or why exactly, but, yeah, that would probably make more sense as a default where we can.
(e.g., I know it works on Kobo, that it theoretically works on Kindle but not practically unless you severely nerf the stock system to not call home every 2 seconds, but I don't remember if we actually have an easy Device cap to check for that).

Push comes to shove, if Kobo works ;).

**Comment by NiLuJe** [comment]
On means on, you're just conditioned by Nickel's own default which is to *aggressively* kill wifi. In the land of IoT, that's the exception, not the rule.

**Comment by NiLuJe** [comment]
> ![unnamed2](https://private-user-images.githubusercontent.com/3080529/332150629-844bcc56-a99d-4345-a6a3-a3107f13955d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDA2NzcsIm5iZiI6MTcxNjI0MDM3NywicGF0aCI6Ii8zMDgwNTI5LzMzMjE1MDYyOS04NDRiY2M1Ni1hOTlkLTQzNDUtYTZhMy1hMzEwN2YxMzk1NWQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMjEyNjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmMyNmY3ODQwOGZkNzY1YzUzNjVjMzlhMGZkZTM5Y2IyZDI2MTM4ZGVhZGU4MTNlYjQ0NGY1YzNlODQ0N2JhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Fvv8z4A7MBl63E0qrAi-yGuWOi9YJhB8Huii3t_d7JU)
> 
> is what you've recommended?
> 

Yup, looks good.

Just to double-check that there wasn't a weird bug, you *did* have "Restore Wi-Fi connection on resume" enabled when the logs were produced, right?

> 
> Thanks for looking into power consumption, also I've uploaded the crash log more for issue #2 which is no response/lagging on swipes for lights, not sure if there any issue in the logs but seems to be in shows all screen manipulations

**Comment by NiLuJe** [comment]
> Thanks for looking into power consumption, also I've uploaded the crash log more for issue #2 which is no response/lagging on swipes for lights, not sure if there any issue in the logs but seems to be in shows all screen manipulations

Oh, right, had forgotten about that.

There's no logging around the frontlight codepaths, so it'd be hard to tell exactly, but at least I can't see anything wrong with the swipe detection, so I'm assuming it behaves as expected.
It'd take someone with the exact same device to confirm whether the frontlight ramping needs some tuning there or not. I can only say that it looked terrible on the Libra Colour before I clubbed it over the head.

**Comment by NiLuJe** [comment]
> EDIT: There's probably a semi sensible way to check for that, since we don't expose the setting in the UI otherwise, duh' ;).

Yup: https://github.com/koreader/koreader/blob/40814bf12b75dc3c9aa36e1f3166422af8f8a956/frontend/ui/network/manager.lua#L1021-L1024

With the caveat mentioned earlier that it won't help on unmodified Kindles (because the native system is way too chatty).

**Comment by kyxap** [comment]
> Just to double-check that there wasn't a weird bug, you _did_ have "Restore Wi-Fi connection on resume" enabled when the logs were produced, right?

yes, correct

**Comment by kyxap** [comment]
> Which naming are you referring to precisely?

"Wi-fi connection" [checkbox ](https://private-user-images.githubusercontent.com/3080529/332150629-844bcc56-a99d-4345-a6a3-a3107f13955d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTAwODQsIm5iZiI6MTcxNjMwOTc4NCwicGF0aCI6Ii8zMDgwNTI5LzMzMjE1MDYyOS04NDRiY2M1Ni1hOTlkLTQzNDUtYTZhMy1hMzEwN2YxMzk1NWQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjFUMTY0MzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU5MTU2Zjg2Yjg1ZDI3NjE4YjI4NjNiMjBjY2M2NmQ3YzRiZWY4MDZhNDEzNTRjNjhlYzFkODBhMWY1N2Q3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zPcw3JMHmjvuBE3duHt7y02JZJisZUGdcMaNNdOBzVY)

**Comment by kyxap** [comment]
I guess this one can be closed?

**Comment by rommyno** [comment]
In my case I left to use Koreader due to this problem
My Kobo Clara HD with original firmware I haven't problems (40 hours of use) and with Koreader is the same time on the firsts uses,  but when I charge the battery two or three time is impossible to use it for more than 6-8 hours and then halts with freeze screen
I was reinstall the original firmware and the problem was disappears
After two months of normal use, I was reinstall again Koreader and the same battery problems appeared.
Finally I prefers use the Kobo original firmware.
I'm sorry
