### ISSUE TITLE
Koreader not response to touch in kindle device

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#11824]
* KOReader version: Last nightly release
* Device: Kindle PW3

#### Issue
after last update that release on nightly build koreader not response to any touch input and i stuck in koreader screen. turn on and of button work.
i just can force reboot kindle to get out of that

#### Steps to reproduce
update to last nightly build

I don't have any idea how should i install any update or collect more data while i can't touch anything in koreader.

**Comment by benoit-pierre** [comment]
Please provide `crash.log`.

**Comment by mergen3107** [comment]
```
[FBInk] /dev/input/event0: `max77696-onkey` = KEY | POWER_BUTTON
[FBInk] /dev/input/event1: `cyttsp4_mt` = UNKNOWN
```
@NiLuJe

**Comment by NiLuJe** [comment]
Ah.

I'm going to need the output of `evtest /dev/input/event1` (I'll dig up a few old devices on my end to see if I can repro, too).

**Comment by NiLuJe** [comment]
> (I'll dig up a few old devices on my end to see if I can repro, too).

Well, I'm *charging* a few of them now ;D.

So far, haven't found one w/o EVIOCGPROP  support (which is the crux of the issue) *and* a combination of reported events that trip a false-negative.

As far as a *matching* controller, I don't think I've got one, the closest is the Forma, but it's the later generation, and on a kernel that does support EVIOCGPROP, and properly reports it as DIRECT.

```
┌─(ROOT@frost:pts/0)───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~)─┐
└─(0.08:23%:19:02:20%:#)── ./input_scan                                                                                                                                                                                                                                                                                                                ──(Wed, May 15)─┘
[FBInk] /dev/input/event0: `gpio-keys` = KEY | POWER_BUTTON | SLEEP_COVER | PAGINATION_BUTTONS | ROTATION_EVENT
[FBInk] /dev/input/event1: `cyttsp5_mt` = TOUCHSCREEN
[FBInk] /dev/input/event2: `FreescaleAccelerometer` = ACCELEROMETER
```

**Comment by NiLuJe** [comment]
Okay, we've got a winner with a PW2 , looking into it.

**Comment by NiLuJe** [comment]
> w/o EVIOCGPROP support (which is the crux of the issue)

Turns out: not exactly. The kernel supports it, the driver just isn't flagged with *any* propery (i.e., DIRECT).

**Comment by NiLuJe** [comment]
> w/o EVIOCGPROP support (which is the crux of the issue)

That *was* causing issues on other devices, though (e.g., the Kindle Touch).
