### ISSUE TITLE
FR: Open a collection with a gesture

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#11826]
Would it be possible to have the option to set a gesture to open a [collection ](https://github.com/koreader/koreader/pull/11693 )?

Thank you!

**Comment by hius07** [comment]
Do you mean opening a certain collection?
There are actions for Favorites and Collection list.

**Comment by ichnilatis-gr** [comment]
Yes, a certain one.

**Comment by hius07** [comment]
Doubtful, the benefit is just one tap, not enough to blow up the code.
