### ISSUE TITLE
Light brightness adjustment no longer works in boox e-ink reader

### ISSUE THREAD

**Issue by dpicassom** [koreader/koreader#11828]
* KOReader version:
2024.04 "Sourdough"

* Device:
Boox Poke3
firmware version 2023-12-12_23-45_3.5_4687b1901

#### Issue

First of all , thanks for the app, it is great!!!

Light brightness adjustment no longer works in boox poke3 e-ink reader
I used to be able to adjust the brightness of the backlight with a leftside up or down gesture. The feature was the greatest ever because it allowed to adjust the brightness ON TOP of the device's adjustment, which is insufficiently fine, and won't let the brightness below a, in my liking,  too bright point, because it turns off altogether. So I was able to adjust to the accurate brightness level (below the lowest by the device's adjustment) by using KOreader's fantastic feature. This together with dark mode and the available options for text adjustment made reading the experience it ought to be.

Now although the message reads that it adjusts the light, it does nothing.

#### Steps to reproduce
Get a poke3, update firmware, download KOreader sdk 64 bits arm from github. Install using the device's installer. Open a book and try to adjust brightness.

Thanks for your help

**Comment by hugleo** [comment]
Maybe a new driver on eink-test you can test. 
And follow the instructions here: https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#onyx-devices 
But maybe not the currently one you need to wait for the next luajit-bump with some changes that can or can't work for you.

**Comment by dpicassom** [comment]
@hugleo 

thanks, but its Android 10
I did it anyway yet it didn't work
whgat's luajit-bump?

**Comment by dpicassom** [comment]
@hugleo 
Thanks nut it didn't work. i used the android cli to do it but no change
It's ANdroid 10 though
whats uajit-bump?

**Comment by dpicassom** [comment]
why is the issue closed?

**Comment by pazos** [comment]
> why is the issue closed?

You closed the issue yourself :)

But it is very well closed. We can't provide any help. Each FW update means a russian roulette in terms of support here.

I would suggest you to contact Onyx support, if there's any, and get a list of firmware changes they implemented, including their routines to update brightness and the sysfs nodes used on their kernel). Otherwise you'll need to wait until somebody pushes an updated driver, and still then we will need to choose between supporting the old, trusted method, and a new method that might screw users that didn't update their FW yet.

Everything sounds nasty because everything is nasty :/

**Comment by hugleo** [comment]
> @hugleo Thanks nut it didn't work. i used the android cli to do it but no change It's ANdroid 10 though whats uajit-bump?

I'm referring to these changes: https://github.com/koreader/android-luajit-launcher/commit/3191e4e2053f205e7eb82b65aabfa3d1e3be73ff. 
The bump will need to wait a little longer https://github.com/koreader/koreader/issues/11723#issuecomment-2083420037 and it will be after the next release.

Meanwhile I've created a test APK if you want to give it a try and confirm that it works, I'll let ready a PR for your device.

You need to do as said on the wiki: adb shell settings put global hidden_api_policy 1

https://we.tl/t-iL4ZqHy7VP
