### ISSUE TITLE
FR: Long-press on non-touch kindles

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11834]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently there is a sort of partial implementation of long-press on non-touch devices, via right arrow. It works in the file manager but not in the menus. This works mostly okay if you use classic mode or detailed list, but if you choose grid view "mosaic" then you have to jump through hoops as the navigation can only occur with up/down arrows, and again not implemented at all in menus. 

Once #11749 and #11802 are merged, a new door opens up for kindle devices. 

**Describe the solution you'd like**
Utilise `ScreenKB` + `Press` (on K4) or `Shift` + `Press` (on kindles with keyboards) for long press across the UI (except for content [text] selection), that way, we could have normal dPad behaviour in grid view and would be able to introduce it in the menus too.

**Comment by Commodore64user** [comment]
I don't mean to be rude or anything by calling you out like this but, @comphilip, is this (and #11821) something you would be interested in helping out with? I feel like this one is a bit above my non-developer level of expertise. If you can't it's absolutely fine. ;) cheers!

**Comment by Commodore64user** [comment]
just reporting here that, since no long-press is available in menus, book-specific tweaks become uneditable after setting them up (ask me how I know). btw this #11533 works great with non-touch @poire-z, nice one.

**Comment by comphilip** [comment]
@Commodore64user Look at here. Add your key combination and have a tried on your device.

https://github.com/koreader/koreader/blob/ba8891082c75a046e8e8c165a9d6b100df3740c3/frontend/ui/widget/focusmanager.lua#L60

**Comment by Commodore64user** [comment]
I have managed to get `Hold` (long press) to work on file manager and the menu, however I can't for the life of me figure out where the mappings for the up/down arrows are. If anyone has any clue I would be very grateful.

**Comment by Commodore64user** [comment]
So I am trying to add 

```lua
if Device:hasFiveWay() then
        self.key_events.Hold = { { "ScreenKB", "Press" }, event = "Hold" }
        self.key_events.FocusLeft = { { "Left" }, event = "FocusMove", args = {-1, 0} }
        self.key_events.FocusRight = { { "Right" }, event = "FocusMove", args = {1, 0} }
        self.key_events.FocusUp = { { "Up" }, event = "FocusMove", args = {0, -1} }
        self.key_events.FocusDown = { { "Down" }, event = "FocusMove", args = {0, 1} }
    elseif Device:hasDPad() then
```

to this block here
https://github.com/koreader/koreader/blob/40814bf12b75dc3c9aa36e1f3166422af8f8a956/frontend/ui/widget/menu.lua#L968-L976

however, up/down just continues to move sideways, and left/right do nothing which has led me to believe that perhaps on non-touch grid view might not be seen as a 2D grid but maybe just a fancy list... I might be wrong, but it would explain it won't work. I am stuck here so, if anyone could lend a hand, highly appreciated.

**Comment by poire-z** [comment]
Tssss.
Just search for "layout" and look around all matches in https://github.com/koreader/koreader/blob/master/frontend/ui/widget/buttontable.lua.
This is used for the button table (a grid) that we show on multiwords text selection, I guess it is this behaviour you want.

Quick try:
```diff
--- a/plugins/coverbrowser.koplugin/mosaicmenu.lua
+++ b/plugins/coverbrowser.koplugin/mosaicmenu.lua
@@ -930,6 +930,7 @@ function MosaicMenu:_updateItemsBuildUI()
     -- Build our grid
     local cur_row = nil
     local idx_offset = (self.page - 1) * self.perpage
+    local line_layout = {}
     for idx = 1, self.perpage do
         local index = idx_offset + idx
         local entry = self.item_table[index]
@@ -943,6 +944,8 @@ function MosaicMenu:_updateItemsBuildUI()
         end

         if idx % self.nb_cols == 1 then -- new row
+            table.insert(self.layout, line_layout)
+            line_layout = {}
             table.insert(self.item_group, VerticalSpan:new{ width = self.item_margin })
             cur_row = HorizontalGroup:new{}
             -- Have items on the possibly non-fully filled last row aligned to the left
@@ -975,13 +978,14 @@ function MosaicMenu:_updateItemsBuildUI()
         table.insert(cur_row, HorizontalSpan:new({ width = self.item_margin }))

         -- this is for focus manager
-        table.insert(self.layout, {item_tmp})
+        table.insert(line_layout, item_tmp)

         if not item_tmp.bookinfo_found and not item_tmp.is_directory and not item_tmp.file_deleted then
             -- Register this item for update
             table.insert(self.items_to_update, item_tmp)
         end
     end
+    table.insert(self.layout, line_layout)
     table.insert(self.item_group, VerticalSpan:new{ width = self.item_margin }) -- bottom padding
 end
```
Not sure how this is supposed to work, and may be it is caused by your recent changes, but when navigating with arrow keys on the emulator, <kbd>left</kbd> cycle correctly in the row, but <kbd>Right</kbd> triggers a long-press and show the popup menu.

**Comment by Frenzie** [comment]
It's expected on the emulator right now; I'd prefer a different solution though.

**Comment by Commodore64user** [comment]
> Tssss. Just search for "layout" and look around all matches in https://github.com/koreader/koreader/blob/master/frontend/ui/widget/buttontable.lua. This is used for the button table (a grid) that we show on multiwords text selection, I guess it is this behaviour you want.

I was referring more to the whole thing. Thank you for that but what I meant was, this needs a lot more attention and involvement that I am able to provide (again not a dev). It is just that I don't quite fully understand what is going on so I can't guarantee it will work on all devices. In other words, too advanced for me.

> Not sure how this is supposed to work, and may be it is caused by your recent changes, but when navigating with arrow keys on the emulator, left cycle correctly in the row, but Right triggers a long-press and show the popup menu.

and remember, I haven't touched the emulator at all. Only kindle, and non-touch in general for the content selection options.

**Comment by Commodore64user** [comment]
essentially, I can add the long-press, as all the heavy lifting is already done, but I can't do the grid bit

**Comment by poire-z** [comment]
> but I can't do the grid bit

Unless I misundertood what you're expecting, I think I did it for you in the patch above ("Quick try:").

**Comment by Commodore64user** [comment]
> > but I can't do the grid bit
> 
> Unless I misundertood what you're expecting, I think I did it for you in the patch above ("Quick try:").

I can't tell you whether it works or not, with your changes, the dpad stops working, I think the focus manager would need adjusting too.

for clarification, the behaviour I want, is to used the dpad to navigate through the grid in 2 dimensions. currently you can only go up or down.

**Comment by Commodore64user** [comment]
> It works, it's just not very clear.
> 
> It's also possible that you slightly typod this particular change, then it wouldn't do anything:
> 
> ```diff
> -        table.insert(self.layout, {item_tmp})
> +        table.insert(line_layout, item_tmp)
> ```

I am 100% sure I am copying the same, dPad still does not work.

**Comment by poire-z** [comment]
I don't know what else you need for dpad/NT.
But the above transforms the "fancy list" into a "grid", and I can navigate rows/columns with arrow keys on the emulator (except with the arrow right key, which triggers long-press - but the left key restart at the other end of the row, so it's usable).

**Comment by Frenzie** [comment]
It works with the caveat that you can't go right, so to go right you have to go left. But that's orthogonal. It's easier to merge 3 separate PRs:

1. add long-press (ScreenKB+press, simple)
2. fix mosaicmenu FocusManager (already done above, simple)
3. evaluate the right key thing

**Comment by Commodore64user** [comment]
> It works with the caveat that you can't go right, so to go right you have to go left. But that's orthogonal. It's easier to merge 3 separate PRs:
> 
> 1. add long-press (ScreenKB+press, simple)
> 2. fix mosaicmenu FocusManager (already done above, simple)
> 3. evaluate the right key thing

step one and three done. on k4 long press is mapped to `ScreenKB` + `Press` and `Right` is naked. #11872

**Comment by Commodore64user** [comment]
step 2, disables completely the dPad on K4. including the middle `Press` key

**Comment by Commodore64user** [comment]
could you test if the emulator works if you set it to NT and not has keyboard?

**Comment by Frenzie** [comment]
isTouchDevice() isn't used for these purposes (nor should it!)

anyway, hasKeyboard = no makes no difference, nor does hasFiveWay.

What concretely do you mean by it not working?

**Comment by Commodore64user** [comment]
Well as i said, the dPad does not do anything at all, normally you should get an underline to indicate what you would be selecting, it doesn't appear, also you should normally be able to select the first book without seeing that underline by pressing `Press`, can't do that either. 

If you go to the last book opened, `Screen` + `Back`, and then exit back to file manager, now you can select the home icon at the top and the big cross (fat plus sign) but that is it. No focus (underline) ever happens to the actual files.

If you change view mode, to either classic or list, up/down work again (as we expect) and switching back to grid again puts you in the situation where you can only select the home icon or the cross.

**Comment by Commodore64user** [comment]
> So if you press down, say, 3 times and then press enter or "hold" you don't see any result? (As distinct from whether you see any selection visually.)

Absolutely nothing happens, it's a if the dPad had been disconnected, if you do the open book and back, you are then only able to select the hone icon or cross, and `Press` will call the action assigned to them but nothing else is possible

**Comment by Commodore64user** [comment]
update: I just tried these changes on the kindle keyboard and the same thing happens. dPad does not work.

could you guys try to pretend to be `isKindle()` and non touch on the emulator

**Comment by Frenzie** [comment]
That's the same as what I said about isTouchDevice. FocusManager and CoverBrowser don't deal in isKindle (nor should they)

But anyway, the layout seems to be slightly malformed; I'd missed it because you can go down but only by going up.

**Comment by Frenzie** [comment]
Yes, I was wrong.

**Comment by Commodore64user** [comment]
> Yes, I was wrong.

No worries

> But anyway, the layout seems to be slightly malformed

so that is why we can't have nice things

**Comment by Frenzie** [comment]
I think this solves the problem.
```diff
diff --git a/plugins/coverbrowser.koplugin/mosaicmenu.lua b/plugins/coverbrowser.koplugin/mosaicmenu.lua
index 1dc2ffc81..b70d38886 100644
--- a/plugins/coverbrowser.koplugin/mosaicmenu.lua
+++ b/plugins/coverbrowser.koplugin/mosaicmenu.lua
@@ -930,6 +930,7 @@ function MosaicMenu:_updateItemsBuildUI()
     -- Build our grid
     local cur_row = nil
     local idx_offset = (self.page - 1) * self.perpage
+    local line_layout = {}
     for idx = 1, self.perpage do
         local index = idx_offset + idx
         local entry = self.item_table[index]
@@ -943,6 +944,10 @@ function MosaicMenu:_updateItemsBuildUI()
         end
 
         if idx % self.nb_cols == 1 then -- new row
+            if idx > 1 then
+                table.insert(self.layout, line_layout)
+            end
+            line_layout = {}
             table.insert(self.item_group, VerticalSpan:new{ width = self.item_margin })
             cur_row = HorizontalGroup:new{}
             -- Have items on the possibly non-fully filled last row aligned to the left
@@ -975,13 +980,14 @@ function MosaicMenu:_updateItemsBuildUI()
         table.insert(cur_row, HorizontalSpan:new({ width = self.item_margin }))
 
         -- this is for focus manager
-        table.insert(self.layout, {item_tmp})
+        table.insert(line_layout, item_tmp)
 
         if not item_tmp.bookinfo_found and not item_tmp.is_directory and not item_tmp.file_deleted then
             -- Register this item for update
             table.insert(self.items_to_update, item_tmp)
         end
     end
+    table.insert(self.layout, line_layout)
     table.insert(self.item_group, VerticalSpan:new{ width = self.item_margin }) -- bottom padding
 end
```

**Comment by Commodore64user** [comment]
I'll try it later when i get home and report back. Thanks!! 🙏 both of you.

**Comment by Commodore64user** [comment]
UPDATE: It works. yay! We have a functional dPad that moves in 2D through the grid.

**Comment by Commodore64user** [comment]
Should I PR this?

**Comment by Frenzie** [comment]
My "fix" was just quickly checking where it went wrong, but if @poire-z doesn't see a more elegant solution then sure.

**Comment by poire-z** [comment]
That's elegant ! That's how I would have done it if I had thought about this NT layout stuff :)

**Comment by Commodore64user** [comment]
I will PR it then, slightly unrelated question, would it be okay to remove "Bookmark current page" from the menu on `hasScreenKB or hasSymKey`  devices?we now have it mapped to key presses so...

**Comment by poire-z** [comment]
(I'd say: people may get used to use it, or don't know the new key press, so better to not change their habits.
At least as long as you don't need to to make that menu a single page if this menu item would make it 2 pages.
But you're the slow king of that NT land.)

**Comment by Commodore64user** [comment]
> (I'd say: people may get used to use it, or don't know the new key press, so better to not change their habits. At least as long as you don't need to to make that menu a single page if this menu item would make it 2 pages. But you're the slow king of that NT land.)

well two parts, first, in a very nice Apple fashion, removing it would force people to change their habits (for good) to the new key press, even if it requires them asking here.

and second, you see, I am trying to see how Page browser and book map behave on kindle NT. IF [capital IF] I can get it to work nicely, it would indeed spread the menu over two pages.

**Comment by poire-z** [comment]
~~slow king~~ fast dictator of that NT land

> even if it requires them asking here

You rule over only 5 people after all.
