### ISSUE TITLE
New Tolino Shine, Color and Vision Color

### ISSUE THREAD

**Issue by fohvok** [koreader/koreader#11841]
The new Tolino devices are as far as i know now based on Kobos OS and not Android anymore. Are these supported?

**Comment by pazos** [comment]
Not currently.

If they're supported in the future it will be under the `kobo` platform umbrella, I guess

**Comment by Frenzie** [comment]
They look like they're the Clara Bw, Clara Colour, and Libra Colour, so if they're based on the same software as well presumably that means supporting them should be very simple.

Someone with such a device would have to check though. ;-)

**Comment by fohvok** [comment]
In this case i might buy one and could test it maybe in a week.

**Comment by fohvok** [comment]
I tested the Nightly from 2024-05-20, besides Night Mode everything seems to work so far on the Tolino Shine 5 (Kobo Clara BW equivalent)

**Comment by Frenzie** [comment]
> I tested the Nightly from 2024-05-20, besides Night Mode everything seems to work so far on the Tolino Shine 5 (Kobo Clara BW equivalent)

You mean with no adjustments whatsoever? Meaning it'll say `Kobo_spaBW` under Help → Report a bug?

**Comment by fohvok** [comment]
Yes, no adjustments and it shows `Kobo_spaBW` there.

**Comment by Frenzie** [comment]
Well, that's even simpler than I had expected. :smile:

**Comment by beedaddy** [comment]
> I tested the Nightly from 2024-05-20, besides Night Mode everything seems to work so far on the Tolino Shine 5 (Kobo Clara BW equivalent)

Out of curiosity and since I would like to test it myself: How did you install KOReader on the shine 5? Do you use NickelMenu? How did you install it (did you just rename the KoboRoot.tgz, which is not recognized anymore?)?

**Comment by noiprocks** [comment]
> > I tested the Nightly from 2024-05-20, besides Night Mode everything seems to work so far on the Tolino Shine 5 (Kobo Clara BW equivalent)
> 
> Out of curiosity and since I would like to test it myself: How did you install KOReader on the shine 5? Do you use NickelMenu? How did you install it (did you just rename the KoboRoot.tgz, which is not recognized anymore?)?

#copythat I have a Tolino Shine Color here too and could not succeed yet to get Koreader and/or NickelMenu to work. Even after adjusting the eReader.conf / FeatureSettings or patching the latest Sourdough Nightly.

**Comment by fohvok** [comment]
I used the [One-Click Install Package](https://www.mobileread.com/forums/showthread.php?t=314220) and replaced koreader with the nightly version mentioned. It worked when it was on version 4.x.

In 5.x they changed the update process, but even after adjusting the OIP i was not able to get it to work (i also don't know for sure if the file are actually replaced or not, the upgrade worked because of the new version number, but kfmon did not work).

In 5.x they also changed the device name i think (so not Kobo_spaBW anymore) but kfmon or NickelMenu does not work anyways anymore. I created a issue [here](https://github.com/NiLuJe/kfmon/issues/9) for kfmon.

**Comment by noiprocks** [comment]
> I used the [One-Click Install Package](https://www.mobileread.com/forums/showthread.php?t=314220) and replaced koreader with the nightly version mentioned. It worked when it was on version 4.x.
> 
> In 5.x they changed the update process, but even after adjusting the OIP i was not able to get it to work (i also don't know for sure if the file are actually replaced or not, the upgrade worked because of the new version number, but kfmon did not work).
> 
> In 5.x they also changed the device name i think (so not Kobo_spaBW anymore) but kfmon or NickelMenu does not work anyways anymore. I created a issue [here](https://github.com/NiLuJe/kfmon/issues/9) for kfmon.

Thanks for your feedback. Followed your outlined steps, but I get the same result like the new posted issue from you. the When I klick Koreader Book Icon it just opens it as a Picture / first page of a book.  And NickelMenu also doesn't appear  at all.

**Comment by beedaddy** [comment]
So I think this issue should be re-opened, because, on firmware version 5.x, which will be applied immediately after setting up the device, KOReader is currently not working.

**Comment by Frenzie** [comment]
Please make a new one. This one is full of old info.
