### ISSUE TITLE
Please allow bigger font sizes for the alternate status bar

### ISSUE THREAD

**Issue by claus-von-gmx** [koreader/koreader#11850]
Max font size for the alternate status bar is currently "36". It would be nice to have bigger sizes and maybe Font families like "bold".

**Comment by hius07** [comment]
You can try to set it manually:
`cre_header_status_font_size` in koreader/settings.reader.lua
Edit this file out of KOReader.

**Comment by claus-von-gmx** [comment]
Thanx, this worked for me! I managed to set the font size to 44.
 

Gesendet: Samstag, 18. Mai 2024 um 14:52 Uhr
Von: "hius07" ***@***.***>
An: "koreader/koreader" ***@***.***>
Cc: "claus-von-gmx" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [koreader/koreader] Please allow bigger font sizes for the alterante status bar (Issue #11850)


 

You can try to set it manually:
cre_header_status_font_size in koreader/settings.reader.lua
Edit this file out of KOReader.
