### ISSUE TITLE
after sleep, ambient light sensor is in use

### ISSUE THREAD

**Issue by cani1see** [koreader/koreader#11857]
* KOReader version: 2024.03.1
* Device: Kindle voyage

#### Issue
after sleep, ambient light sensor is in use even it's disabled in kindle's system

**Comment by Commodore64user** [comment]
what do you mean by "is in use"? could you be a bit more specific as to what the problem is?

**Comment by cani1see** [comment]
> what do you mean by "is in use"? could you be a bit more specific as to what the problem is?

it's disabled in kindle's system，I didn't find menu to config in koreader. before sleep , ambient light  do not affect backlight, waking from sleep, ambient light is adjusting backlight.

**Comment by cani1see** [comment]
actually it's turning off backlight when in light enviroment

**Comment by Frenzie** [comment]
It's completely separate. You can disable the "Auto frontlight" plugin in Tools → More tools or in Plugin management.

**Comment by cani1see** [comment]
> It's completely separate. You can disable the "Auto frontlight" plugin in Tools → More tools or in Plugin management.

then I think when launch from kuai "auto frontlight" is not working is the bug here.

**Comment by mergen3107** [comment]
@cani1see 
Well, it is not a bug per se, but the way it is implemented is rather rudimentary. 
It is not the same as Kindle's own implementation.

There are only four deciding points, two of which are extremes (turn off when too bright, turn on when too dark). 

Just no one went further and added more logic to it (yet).

**Comment by cani1see** [comment]
@mergen3107 I mean for me, the "auto frontlight" only works after waking from sleep, not on the first boot from Kuai. That made me think that no "auto frontlight" is the default behavior.
