### ISSUE TITLE
Sleep screen image always assumes portrait orientation, even when reading in landscape

### ISSUE THREAD

**Issue by yfede** [koreader/koreader#11856]
* KOReader version: 2024.04
* Device: Kobo Aura (model N514)

#### Issue

Sleep screen image is always displayed in portrait orientation, even when the book was being read in landscape

If a message string is set, the string as well is displayed in portrait mode, i.e. the base of the string is parallel to the short side of the kobo, not the long one

#### Steps to reproduce

1. Set reading orientation to landscape
2. Set a sleep screen image that is 1024 px wide by 768 pixels high
3. Put the device to sleep

#### Expected result:

The image in the sleep screen should fill the whole display, with the long side of the image aligned with the long side of the device, like this (this is how the image is displayed when opened with the viewer):

![image](https://github.com/koreader/koreader/assets/639411/d1eb6a37-32a8-4dea-bde2-bc63fb7c04c5)

#### Actual result:

The image is scaled down, displayed in the center of the screen, with the long side of the image aligned with the short side of the device

![image](https://github.com/koreader/koreader/assets/639411/e6313710-eb20-4b47-8dc4-fb2b3e771115)

#### Final note:

You may say: "why don't you save your image with a rotation to compensate for the above behavior, so that it is 768 px wide and 1024 px high?" 

That may work for solving the problem of the image itself, but the string message would still be displayed conforming to the portrait orientation, while I would like it to appear at the bottom of the image in landscape mode, in order to take advantage of the bigger length of the long side of the device

**Comment by yfede** [comment]
If it's problematic to obtain/retain the current reading orientation and apply it to the sleep screen, an equally satisfactory solution would be IMHO to add an explicit setting in the recently overhauled "sleep screen" menu, to indicate the intended orientation of the sleep screen

**Comment by pazos** [comment]
> Final note:

> You may say: "why don't you save your image with a rotation to compensate for the above behavior, so that it is 768 px wide and 1024 px high?"

> That may work for solving the problem of the image itself, but the string message would still be displayed conforming to the portrait orientation, while I would like it to appear at the bottom of the image in landscape mode, in order to take advantage of the bigger length of the long side of the device

That's the expected behaviour. Sleep message/stats/picture/.., booting KOReader from KFMon, USBnet... All work on the native orientation. That's 0º.

While it might be yet another good feature for somebody I would suggest to implement it as an user patch.

**Comment by yfede** [comment]
but... if the sleep screen is set to show the reading statistics, then it follows the reading orientation instead (see proof below), so it doesn't seem mandatory to respect the native orientation in the sleep screen after all, or am I missing something?


![20240520_211746](https://github.com/koreader/koreader/assets/639411/62e83d5b-c6d1-4236-b6e2-f8b299f1bed4)
![20240520_211801](https://github.com/koreader/koreader/assets/639411/74006166-4ca0-4f66-9946-cab49797eb5f)


![20240520_211840](https://github.com/koreader/koreader/assets/639411/91831f0c-39e8-4047-a86d-bd5d382e44ec)
![20240520_211857](https://github.com/koreader/koreader/assets/639411/a972ee29-f375-4744-858e-e553e21cdff7)

**Comment by mergen3107** [comment]
Reading statistics (I believe) is a screenshot

**Comment by NiLuJe** [comment]
As @pazos's said, it's contextual.

There's a very limited things of things we know actually work in landscape, in which case the orientation is kept, and things we know will horribly break or look terrible, in which case we forcibly switch to Upright during the suspend process.

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/blob/2900eef2768ebb28b3372f32a824384b17ffdbc6/frontend/ui/screensaver.lua#L507-L520

**Comment by NiLuJe** [comment]
> look terrible (...in 99% of the use-cases)

In the OP's case, the assumption is that when an image is being used, it's highly likely to be a cover, in which case it's always Portrait. And when it isn't, it requires manual intervention anyway, so it's the user's responsibility to make sure whatever is being used is actually laid out sensibly.

**Comment by yfede** [comment]
Ok, I get why it works as it does now.
Before going to sleep or shut down, would it be possible to display the image in the desired orientation, overlap the widget also in the desired orientation, take a screenshot of the result and then display that image in portrait mode when the device goes sleeping?
(I mean all of the above done automatically by Koreader, obviously)

**Comment by NiLuJe** [comment]
Not... really? ^^

**Comment by yfede** [comment]
IDK, I'm used to work with a framework for desktop where all of this is possible, but I get if it is too complicated in this context. I was just suggesting a course of action in case it was feasible

**Comment by NiLuJe** [comment]
What could *theoretically* be feasible, given that images are full-screen, which should make them exempt from most of the potential weird interactions (*should*, there's a lot of weird crap involved, I may be wrong), would be to check if the image's orientation matches the screen's orientation, and go from there.

The issue is, we don't actually know the image's dimension until we *render* it... and it all happens in a single step, during which it is scaled to fit... to the screen's dimensions.

So there's a bit of a chicken-or-egg issue in doing that without a *massive* refactor ;).

----

Now, for your particular use-case, if *all* your images follow this trend, you can just user-patch the "should be Portrait" check to disable it for image modes.

e.g.,

```lua
local Screensaver = require("ui/screensaver")

local orig_modeExpectsPortrait = Screensaver.modeExpectsPortrait

function Screensaver:modeExpectsPortrait()
    if self.screensaver_type == "random_image" then
        return false
    else
        orig_modeExpectsPortrait(self)
    end
end
```

(In a late (e.g., `2-landscape-image-screensavers`) patch should do).

One minor caveat is that this'll skip the anti-ghosting flash-to-white because of how the code is laid out, but that may or may not be noticeable on modern devices.
