### ISSUE TITLE
Nothing happens when starting

### ISSUE THREAD

**Issue by xczbone** [koreader/koreader#11860]
* KOReader version: koreader-kindlepw2-v2024.04.zip
* Device: kindle oasis2
*Firmware version: 5.16.2.1.1 
#### Issue
When opening Koreader it seems to nothing had happened

##### `crash.log` (if applicable)
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|
KOReader version: KOReader版本：
Device: PocketBook 626

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/20/24-21:09:33
 [*] Version: v2024.04

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
killall: can't kill pid 5264: Operation not permitted
./luajit: ./ffi/framebuffer_linux.lua:55: cannot open framebuffer
stack traceback:
	[C]: in function 'assert'
	./ffi/framebuffer_linux.lua:55: in function 'init'
	./ffi/framebuffer_mxcfb.lua:749: in function 'init'
	./ffi/framebuffer.lua:138: in function 'new'
	frontend/device/kindle/device.lua:1053: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:151: in main chunk
	[C]: at 0x00013ebd

**Comment by hius07** [comment]
> * Device: kindle oasis2



> Device: PocketBook 626
