### ISSUE TITLE
NT not able to arrange status bar items

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11862]
* KOReader version: sourdough
* Device: kindle 4 (all non-touch)

#### Issue
Arranging status bar items is currently not possible on non-touch, one can select the item to be moved, but the triangles (arrows) do not become available,  or are mapped to any keys. Therefore making it impossible to make any changes.

Screenshot for clarification: "Wifi status" selected and ready to be moved, but triangles (at bottom) are touch only.

<img src="https://github.com/koreader/koreader/assets/97603719/b09d1fcb-35ee-4878-8cb1-184b1603c27a" width=50% height=50%>

#### Steps to reproduce
go to status bar on non-touch and try to re arrange the items.

**Comment by Commodore64user** [comment]
Issue seems to have been reported back in #6463

**Comment by Frenzie** [comment]
It's a bit harsh but it is realistic: tickets that combine multiple things are more likely to be ignored, unless it's basically just a notification to the world that you're working on something. You could make them as a tracking ticket with a list of different individual tickets.
