### ISSUE TITLE
FR: Count and show how many highlights are synced to the user

### ISSUE THREAD

**Issue by kyxap** [koreader/koreader#11876]
**Does your feature request involve difficulty completing a task? Please describe.**
I do not think so it should be simple counter

**Describe the solution you'd like**
When I do Export highlights into memos it shows multiple pop-ups if it was successfully or not (not sure about other services)
Would be nice to have simple counter that will show how many notes was synced and if there 0 - make something like, no new notes found, etc. Maybe show which books has what number of new notes, but this is optional.
This could be added to successful pop-up. Also would be nice to do not close pop-up automatically,  like you need press Ok to close the pop-up. I think it may improve user experience in case there some errors or user want to double check that all expected nodes are went to the memo.

**Describe alternatives you've considered**
n/a

**Additional context**
After discovering this issue #11875 I think it make sense to show this just there any other bugs. Also could help with testing.

**Comment by pazos** [comment]
> shows multiple pop-ups

Well, there're two, so the "multiple" part is true. The first message says "exporting might takes a while", the second shows you the result. I'm assuming you're exporting single books or a not so big history, so the second popup shows just after the first one.

> Would be nice to have simple counter that will show how many notes was synced and if there 0 - make something like, no new notes found, etc. Maybe show which books has what number of new notes, but this is optional.

I have being exporting to joplin for a couple of years and never saw a single instance where some notes were exported and other don't.

Is either all notes or none of them. The former is the expected operation. The latter suggest an issue with the 
 (remote) service, the user setup or that particular export module.

I'm going to close it as not planned. There's another issue with suggestions to improve the plugin in https://github.com/koreader/koreader/issues/9273. Some of the suggestions are still not implemented. Feel free to chime in to see how the plugin work, what other suggested and even request some improvements other than this one.

**Comment by kyxap** [comment]
is it make sense refer to a closed issue?

**Comment by pazos** [comment]
Yes, if they're relevant.

My point is maybe summarized in https://github.com/koreader/koreader/issues/9273#issuecomment-1172108094

Keep a count on which services were exported Ok and which failed is nice and doable. Keep a count on which notes were ok and which failed makes no sense.

**Comment by kyxap** [comment]
I mean who will pick up closed FR? I'm not sure how you track work in todo

**Comment by kyxap** [comment]
btw I've enabled html, myclippings and now it shows on last pop-up that those two was exported but nothing about `memos`. So I still think it make sense to wait for user input before closing it (its to fast to read what was there)
