### ISSUE TITLE
Export highlights to memos - UI shows successful, logs HTTP response code <> 200. Response status: HTTP/1.1 404 Not Found 

### ISSUE THREAD

**Issue by kyxap** [koreader/koreader#11875]
* KOReader version: koreader-kobo-v2024.04-32-geb6e5e3c2_2024-05-10
* Device: Kobo clara bw

#### Issue

After I've massed up with memo db due to misconfiguration I can't export my highlights (see https://github.com/usememos/memos/issues/3443) 
Everything was working with no issue before this happened (except couple duplicates, not sure why yet) .
After re-creating memos db I've create new token and update it in ereader. 

#### Steps to reproduce
- setup memos with local memos instance and new token
- create new highlights or note
- try to sync highlights (books or whole lib)
- see pop-up and check memo instance

expected: successful msg, new notes in the memo db
actual:  successful msg, 0 new notes in the memo db

##### `crash.log` (if applicable)

```
05/23/24-14:53:44 DEBUG blitFrom 134 687 0 0 72 72 
05/23/24-14:53:44 DEBUG _refresh: Enqueued flashui update for region 0 0 1072 1448 dithering: false 
05/23/24-14:53:44 DEBUG refresh: ui-mode w/ flash 0 0 1072 1448 false 
05/23/24-14:53:44 DEBUG refresh: wait for completion of (previous) marker 32 
05/23/24-14:53:44 DEBUG mxc_update: 1072x1448 region @ (0, 0) with marker 33 (WFM: 257 & UPD: 1) 
05/23/24-14:53:44 DEBUG refresh: wait for completion of marker 33 
05/23/24-14:53:44 WARN  Memos: HTTP response code <> 200. Response status: HTTP/1.1 404 Not Found 
05/23/24-14:53:44 DEBUG Response headers: {
  connection = "close",
  ["content-type"] = "application/json",
  date = "Thu, 23 May 2024 18:53:44 GMT",
  ["transfer-encoding"] = "chunked"
} --[[table: 0xac6b0fa0]] 
05/23/24-14:53:44 WARN  error creating highlights HTTP/1.1 404 Not Found 
05/23/24-14:53:44 WARN  Memos: HTTP response code <> 200. Response status: HTTP/1.1 404 Not Found 
05/23/24-14:53:44 DEBUG Response headers: {
  connection = "close",
  ["content-type"] = "application/json",
  date = "Thu, 23 May 2024 18:53:44 GMT",
  ["transfer-encoding"] = "chunked"
} --[[table: 0xac6b6420]] 
05/23/24-14:53:44 WARN  error creating highlights HTTP/1.1 404 Not Found 
05/23/24-14:53:44 DEBUG createHighlights success number: 0 createHighlights error number: 2 
05/23/24-14:53:44 DEBUG ImageWidget: _render'ing resources/icons/mdlight/notice-info.svg 72 72 
05/23/24-14:53:44 DEBUG ImageWidget: initial offsets 0 0 
05/23/24-14:53:44 DEBUG show widget: table: 0xac6b7648 
05/23/24-14:53:44 DEBUG setDirty nil from widget table: 0xac6b7648 w/ NO region; dithering: nil 
05/23/24-14:53:44 DEBUG setDirty via a func from widget table: 0xac6b7648 
05/23/24-14:53:44 DEBUG painting widget: table: 0xac6b7648 
```
</details>

Also wanted to ask, does this plugin saves what notes are already synced? Wandering if I can remote those records to re-sync my notes again.

**Comment by kyxap** [comment]
Something worth to mentioned: I've recently updated memos to v0.22 where I've discovered this issue and I'm not sure if they have changed the api since this version

**Comment by Frenzie** [comment]
Pinging @fierceX

**Comment by kyxap** [comment]
ok I've found the issue, some how I've removed last character of the url and that why I started to get 404...
but anyway it would be nice to see something meaningful about incorrect url in UI :)

**Comment by fierceX** [comment]
@kyxap Is this issue caused by an incompatible memos upgrade? Also, the plugin doesn't save which ones have been synced, it simply exports the notes for the book/all books. Adding which notes have been exported could add a lot of uncertainty.

**Comment by kyxap** [comment]
@fierceX no its just how plugin parse the response from memos 

I've used `https://demo.usememos.com/api/v1/memo` instead of `https://demo.usememos.com/api/v1/memos` which returns 404 but plugin thread it as successful

**Comment by fierceX** [comment]
@kyxap Okay, I'll investigate and fix the problem
