### ISSUE TITLE
[Linux version] Is there a way to reload the current book from disk, without restarting KOReader?

### ISSUE THREAD

**Issue by electrotype** [koreader/koreader#11870]
I'm using KOReader to create ePubs books, on my Linux machine. My flow is to make some modifications to the ePub I'm creating, and then validate it in KOReader.

Currently, I close and re-open KoReader in order to see the changes I have made.

I'd like to know if there is another way to reload the current book from disk? A keyboard shortcut maybe?

Thanks in advance.

**Comment by poire-z** [comment]
As you would do in a web browser: <kbd>F5</kbd> should work.

**Comment by electrotype** [comment]
Oh great! Works perfectly, thanks!
