### ISSUE TITLE
Highlights extraneous parts (dash) when quoting

### ISSUE THREAD

**Issue by skylarsoulmate** [koreader/koreader#11880]
* KOReader version: Latest 2024.04-88
* Device: PocketBook 633 Color

Issue:
When I highlight a quote along with the last word before the dot, **then after the dot the dash from the next sentence** is highlighted. But if you select without a dot, then it doesn’t select the extra, but I need a dot, and together with the dot happens the problem mentioned above. 
I know this is a very minor problem, I can live without a dot, but I really want KOReader to be perfect and without errors.
I switched to KOReader because I had a similar problem on my PocketBook, only much worse, I would not like to see this here.

I show the problem in the attached photo (marked with a red arrow).

![IMG_20240524_162809.jpg](https://github.com/koreader/koreader/assets/168462969/28baeeef-4fb2-43d6-a97c-13d2d41b54d0)

Thank you for best reading application 🙏

**Comment by jonnyl2** [comment]
You can adjust the highlight character by character by long-pressing on the extend/curtail highlight buttons (short tap is word by word). Short tap anywhere on the highlighted text, then it's the 3rd button in the 2nd row for your particular case.

**Comment by skylarsoulmate** [comment]
> You can adjust the highlight character by character by long-pressing on the extend/curtail highlight buttons (short tap is word by word). Short tap anywhere on the highlighted text, then it's the 3rd button in the 2nd row for your particular case.

THANK YOU VERY MUCH.
Long tap working! Best solution ever!

**Comment by Commodore64user** [comment]
> You can adjust the highlight character by character by long-pressing on the extend/curtail highlight buttons (short tap is word by word). Short tap anywhere on the highlighted text, then it's the 3rd button in the 2nd row for your particular case.

WHAT??? I didn't know about the long press. So many times I've longed for this and it was there the entire time.

**Comment by Commodore64user** [comment]
So it works great on touch devices, K4 however still needs long press support on widgets, any idea where that one in particular is (in the code i mean)?

**Comment by Frenzie** [comment]
> K4 however still needs long press support on widgets

Does not, or not that one anyway. As per https://github.com/koreader/koreader/pull/11871#issuecomment-2125659324

**Comment by Frenzie** [comment]
Which just made me realize that https://github.com/koreader/koreader/pull/11872 should be reverted and added to FocusManager.

**Comment by Commodore64user** [comment]
> Which just made me realize that https://github.com/koreader/koreader/pull/11872 should presumably be reverted and added to FocusManager?

If focusmanager encompasses more than the current implementation, probably a good idea. 

The thing is, I originally tried adding it there, but it didn't work... not sure why. Same with "Sym" + "Aa" even though it was already defined there, when i try using it on K3, does not work.

**Comment by Commodore64user** [comment]
But wait, that is a new nightly, let me download it and check...

**Comment by Commodore64user** [comment]
Okay @Frenzie, long press works on widgets on KK (K3) and appears to be truly global, so adding K4 there and reverting the other one would be a good idea. So would be fixing content selection (cough #11864)
