### ISSUE TITLE
Resolve Device:hasFiveWay() code debt

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#11887]
* KOReader version: current master

#### Issue
It doesn't describe what it does. It's confusing and badly named.

https://github.com/koreader/koreader/pull/11884#discussion_r1614524106

> To summarize, imho when reading the text `hasFiveWay` it implies one thing and one thing only: that you can click/press on the d-pad or stick itself as a "fifth" action.[1] This is almost entirely useless information, except potentially to see it as a kind of restriction: maybe it's difficult to press on it without accidentally triggering a direction. For all intents and purposes it simply means we have four directions and an a primary action key.[2]
> 
> Instead it's being used as a secret code for two or three other features: that page turning buttons exist, and that some sufficient selection of other additional buttons exist so that actions like hold can be triggered.

**Comment by Commodore64user** [comment]
What do you think it should be?

**Comment by Frenzie** [comment]
There's:

* `useDPadAsExtraActionKeys` (but not in mosaic menu to keep things simple xD)
   This is what I had originally proposed to call `hasPageUpDownButtons` but that requires a bit too much reasoning.
* `canTriggerHold`
   This is new but the exact kind of doom scenario I figured probably wasn't on the immediate horizon. It might make more sense as the reverse, similar to `hasFewKeys` but `cannotTriggerHold` or `hasNoHoldTrigger` for example.
* Something else? It's not impossible for there to be a space for Kindle-specific something or other, although it seems a bit unlikely. I don't particularly care for the name hasFiveWay but it could serve such a purpose if really desired.

The other obvious path is to duplicate everything.

`hasFiveWay or useDPadAsExtraActions`
`hasFiveWay or canTriggerHold`

But my basic problem with that is that it seems inelegant at best, obscurantist and confusing at worst.

**Comment by NiLuJe** [comment]
FWIW, whether it be `hasFiveWay` or https://github.com/koreader/koreader/pull/11749#discussion_r1602313981

>  it implies one thing and one thing only: that you can click/press on the d-pad or stick itself as a "fifth" action.

was very much my own reasoning. With the subtext that it means hasDPad, but better.

If that's not what actually happened in practice, my bad ;).

**Comment by Frenzie** [comment]
> allowing more flexibility.

The additional flexibility comes from other factors that always happen to be combined with the 5-way on Kindle: separate page up/down buttons that allow for using the d-pad in ways other than page turning (`useDPadAsActionKeys`) and a `Sym` button that can be used as a modifier (`hasHoldTrigger`).

Hence my original proposal was along the lines of `hasDPad and hasPageUpDownButtons and not hasKeyboard`, but there was a desire to use it on all Kindles for Kindle consistency, which is how you end up with a more explicit `useDPadAs…` formulation, to be manually added rather than derived from other properties. Which also adds the advantage of easily turning it on and off with a user patch.

So in short my proposal would be:

* `/hasFiveWay/useDPadAsActionKeys/s` in ReaderRolling and ReaderPaging, probably most other occurrences as well
* in the menu we use `not hasHoldTrigger` (default `yes`, override to `no` on specific devices)
* except in ReaderLink where we would use something like `hasFiveWay` because there we do want some behavior tailored to Kindle, but you can't set `isKindle = yes` for testing

**Comment by Frenzie** [comment]
> * except in ReaderLink where we would use something like `hasFiveWay` because there we do want some behavior tailored to Kindle, but you can't set `isKindle = yes` for testing

Alternatively we could just add all the shortcuts everywhere. Depends a bit how memory-conscious we want to be.

https://github.com/koreader/koreader/blob/b222900cb937c767d97587b7b2c36a16b1d330ae/frontend/apps/reader/modules/readerlink.lua#L230-L262

**Comment by Commodore64user** [comment]
> and a `Sym` and/or `ScreenKB` button that can be used as a modifier (`hasHoldTrigger`).

regarding that `Sym` key, it is only available on kindle with keyboards and it is not really necessary to be used as a mod as there are already two other ones there, Alt and Shift. Stock firmware uses it to show a symbols (sym for short) when needed. 

The older kindles have from 32-128MB ram and K4 has 256MB, so maybe not a good idea to have them store unnecessary stuff.

**Comment by Frenzie** [comment]
Is the program even usable on less than 128 MB? But to be clear even on 32 MB we're talking less than 0.001% of the total memory; it's just a couple of strings in a table.

**Comment by NiLuJe** [comment]
> So in short my proposal would be:

Sounds good to me ;).

----

I'm all for actually using these rather than always having the shortcuts setup, if for no other reason than to serve as practical documentation as for why the thing exists and what it's used for ;).

**Comment by Commodore64user** [comment]
> Is the program even usable on less than 128 MB? But to be clear even on 32 MB we're talking less than 0.001% of the total memory; it's just a couple of strings in a table.

It runs theoretically on kindle 2 which has 32MB, i only have the K3 and K4 which both have 256MB but the 3 has a significantly slower processor and that one feels sluggish. I can’t really imagine what nightmare it must be on the other older models.

kindle dx has 128MB and comphill has described it as “poor performance” so…

**Comment by NiLuJe** [comment]
> kindle 2 which has 32MB

Whut? I have some doubts about Wikipedia's claims here. For one, the Kindle 2i definitely has something like 128MB. Secondly: it's running the same Java UI, so, 32MB? not happening ^^.

(Same for us, really, we'd barely boot).

**Comment by Commodore64user** [comment]
> > kindle 2 which has 32MB
> 
> Whut? I have some doubts about Wikipedia's claims there. For one, the Kindle 2i definitely has something like 128MB (I'd have to charge mine to confirm, but that rings a bell). Secondly: it's running the same Java UI as the rest of the 2.x-to-4.x FW lineup, so, 32MB? not happening ^^.
> 
> (Same for us, really, we'd barely boot).

chatgpt says 128 so we’ll go with that. Still not pretty though.
