### ISSUE TITLE
Exporting highlights generically to http endpoint

### ISSUE THREAD

**Issue by parthshahp** [koreader/koreader#11903]
I'm currently writing my own small program to store synced / exported highlights from Koreader. I could use the export to json / markdown functionality to do it, but it would be nice if I could somehow configure an endpoint for sending a post request (similar to the functionality in the exporter for readwise).

https://github.com/koreader/koreader/blob/master/plugins/exporter.koplugin/target/readwise.lua

Tried looking through the documentation but couldn't find anything about it. I'd be happy to work on it if it something that's needed / wanted.

**Comment by pazos** [comment]
Hi.

A generic http endpoint is not needed. It is trivial to write one for new services.
But, while you work on your software, you might find useful to create a new target for yourself that does what you need.

I would suggest to copy `exporter.koplugin` with another name, tweak its metadata. Then restart KOReader, disable the original plugin and make sure yours is enabled.

When you finish your project you can choose between keep everything private (your service and your plugin tweaks) or share both.
