### ISSUE TITLE
Onyx Boox Leaf2 - Refresh issues (ghosting or flickering)

### ISSUE THREAD

**Issue by AryaTwirl** [koreader/koreader#11911]
* KOReader version: the latest one
* Device: Onyx Boox Leaf2

#### Issue
1.) So if I choose refresh every page using built in settings from Onyx:
KoReader turns the pages slightly later than the page refresh on the device, resulting a faint ghosting (not that visible on text, but visible on pictures)

2.) Solution is by using the refresh every page setting in KoReader and disable the Onyx one completely but:
Image rendering becoming a mess, with lots of banding and once in a while the text will flicker for a millisecond randomly, making the reading experience a bit uncomfortable.

#### Steps to reproduce
Try either of the settings mentioned above.

Already turning off all optimisations and turning them back on but still no changes.

**Comment by pazos** [comment]
Can't fix with current driver. A new driver or improvements to the current one are welcome in https://github.com/koreader/android-luajit-launcher

**Comment by hugleo** [comment]
A starting point can be this: [This is not a problem](https://github.com/koreader/android-luajit-launcher/pull/435)
