### ISSUE TITLE
What standards of reference pages are supported by KOReader?

### ISSUE THREAD

**Issue by NextTherapist** [koreader/koreader#11914]
This is not a bug report and not a feature request. Anything is fine. I am just curious, _why_. 

KOReader displays reference page numbers in a book that seems not to use one of the two standards mentioned in this thread:
https://github.com/koreader/koreader/issues/4521

These two ways are mentioned:
- the Adobe pagemap solution (with a pagemap.xml linked in content.opf)
- the toc.ncx solution with pageTarget entries in the toc.ncx

both with empty anchors in the html.

Now I saw books without a pagemap.xml file and without pageTarget entries in the toc.ncx, but only with spans in the html like
`...text of page nine...<span class="origpage" id="origpage_10">{10}</span>...text of page ten...`

and a CSS for the origpage class like
```
span.origpage {
font-family:sans-serif;
font-weight:normal;
display:inline;
background-color:#FFF;
color:#333;
font-size:8pt;
}
```

And KOReader faithfully offers the reference page options and shows these numbers. It looks so simple. Do I overlook a secret ingredience?

Is this a kind of magic or another standard?

**Comment by poire-z** [comment]
What we support is mentionned in https://github.com/koreader/crengine/pull/336 : 

> Supported sources of page map/list (reference URLs in the code), checked in this order:
> -    EPUB3 `<nav epub:type="page-list">` in nav document
> -    EPUB2 `<pageList><pageTarget>` in ncx document
> -    Adobe page-map document referenced as `<spine page-map="page-map">`

We don't support anything like `<span class="origpage" id="origpage_10">{10}</span>` with info inlined with the content.

Not sure what you mean works or does not work.
It may also depend on how a publisher of a specific book did it, may be some tweaks (allowed or not by the specs) cause our inspection/parsing to fail on some specific books.
But I remember I tested each of these 3 types with the few books I had at hand with each of them.

**Comment by Frenzie** [comment]
I think OP is saying that in some book the paper page numbers are simply inserted in the text without depending on special support, though in that case I'm not really sure what the question is.

**Comment by poire-z** [comment]
Ah, ok. Well, then indeed no special support - and nothing per-specs tells us these `<span class="origpage" id="origpage_10">{10}</span>` are page numbers. For us, they are just book content like any other `<span>` inlined with the text, so we display them in the text - and don't offer anything else like we do with our "reference page numbers" feature (display in margin, see the page number list, use them in footer).

I think it would be rather annoying to see them in the text, so I personally would hide them with a Book style tweak using `span.origpage { display: none !important; }`.

**Comment by NextTherapist** [comment]
Oh no... seems I mixed up an epub file on my KOReader app with another epub file in my Calibre Editor! Indeed those epubs which offer reference pages have pagelists embedded. So there is no magic simple solution unfortunately.

Thank you!
