### ISSUE TITLE
Does not start on Kindle Voyage

### ISSUE THREAD

**Issue by eoxb** [koreader/koreader#11927]
* KOReader version: v2024.04 also tried with v2024.03.1
* Device: Kindle Voyage

#### Issue
Launching from KUAL, it says Starting KOReader . . . on the bottom of the page, then I only see back to the home screen of the kindle.  The app does not launch at all.  I also tried with Start KOReader (ASAP) and Start KOReader (no framework) with the same results and same crash log error.

#### Steps to reproduce
Open KUAL
KOReader
Start KOReader

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
<---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/30/24-02:12:38
 [*] Version: v2024.04

ffi.load: libs/libutf8proc.so.3
ffi.load: blitbuffer
05/30/24-02:12:39 INFO  initializing for device KindleVoyage 
05/30/24-02:12:39 INFO  framebuffer resolution: {
  h = 1448,
  w = 1072
} --[[table: 0x4041c1c0]] 
[ko-input] Forked off fake event generator (pid: 11062)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: sqlite3
05/30/24-02:12:39 INFO  Performing one-time migration for 20191129 
05/30/24-02:12:39 INFO  Performing one-time migration for 20200421 
05/30/24-02:12:39 WARN  os.remove: ./cache/fontlist/fontinfo.dat: No such file or directory 
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
05/30/24-02:12:39 INFO  ./cache/fontlist/fontinfo.dat fopen: No such file or directory -> initializing it 
Bus error
lipc-wait-event exited normally with status: 0>
```
</details>

**Comment by hius07** [comment]
At first, reboot the device.
If no luck, what is the firmware version and jb method used?

**Comment by eoxb** [comment]
Used JB WatchThis https://www.mobileread.com/forums/showthread.php?t=346037
Firmware: 5.13.6

**Comment by hius07** [comment]
Similar to https://github.com/koreader/koreader/issues/10078.

**Comment by hius07** [comment]
Just in case install the hotfix, if you haven't:
https://storage.gra.cloud.ovh.net/v1/AUTH_2ac4bfee353948ec8ea7fd1710574097/mr-public/Touch/JailBreak-1.16.N-FW-5.x-hotfix.zip

**Comment by eoxb** [comment]
I'm getting the same error again

**Comment by hius07** [comment]
@NiLuJe please look at it. Anything related to fonts?

I'm on the Voyage too, haven't encountered the issue when was on 5.13.6 (downgraded to 5.9.6 because of the battery drain).

**Comment by NiLuJe** [comment]
A SIGBUS on Kindle is *usually* related to some userstore fuse proxy shenanigans, so I'd try a...factory reset, maybe? (with all the caveats this entails re: keeping the JB alive).

**Comment by NiLuJe** [comment]
A cold boot is indeed the first step, though, so i'd double-check whether what you've done is actually a proper cold boot (i.e., pressing the power button twice is *not* what we meant).

**Comment by Commodore64user** [comment]
> @NiLuJe please look at it. Anything related to fonts?
> 
> I'm on the Voyage too, haven't encountered the issue when was on 5.13.6 (downgraded to 5.9.6 because of the battery drain).

what battery drain? how many hours do you get of reading time?

**Comment by eoxb** [comment]
> A SIGBUS on Kindle is _usually_ related to some userstore fuse proxy shenanigans, so I'd try a...factory reset, maybe? (with all the caveats this entails re: keeping the JB alive).

I tried factory reset, reinstall JB hotfix, reinstall MRPI, reinstall KUAL, reinstall KOReader, but I get the same issue in the crash log.  Darn.

**Comment by eoxb** [comment]
Seems like I fixed it similarly to the linked issue.  I added log statement in the same method like this:
`logger.info(path, "-> collectFaceInfo it")`
Then found in the crash.log that it stopped at this file:
/usr/java/lib/fonts/STSongMedium.ttf
So I put in the similar fix at the top of the method:
`   if path == "/usr/java/lib/fonts/STSongMedium.ttf" then return end`
Also still working after restart.

**Comment by hius07** [comment]
The problematic STSongMedium.ttf is included to the Kindle blacklisted fonts:
https://github.com/koreader/koreader/blob/2f0e456a428ef81de7c0747208d581f39e9359da/frontend/fontlist.lua#L18-L23
Then the blacklisted fonts are not added to the fontlist:
https://github.com/koreader/koreader/blob/2f0e456a428ef81de7c0747208d581f39e9359da/frontend/fontlist.lua#L147-L150
But they are unconditionally cached
https://github.com/koreader/koreader/blob/2f0e456a428ef81de7c0747208d581f39e9359da/frontend/fontlist.lua#L152-L157
where `collectFaceInfo(path)` fails with the above `Bus error`.

@poire-z, if a font is not added to the fontlist, should it be cached?

**Comment by poire-z** [comment]
I don't really know, I'm not really familiar with this fontlist.lua (which is some generic font listing also affecting the UI, not strictly cre related).
But a quick look at its code, and I think you could just `if isInFontsBlacklist(file) then return end` on line 147 and ignore it completely - if this avoids that crash.

**Comment by NiLuJe** [comment]
It's been a while since I looked at this stuff, but, yeah, it would make sense to not actually touch blacklisted fonts at all ;).

What you proposed makes sense (and this looks like a regression from #6786), as we'll never actually query the metadata of a blacklisted fonts.

**Comment by StellaMeow** [comment]
> [@NiLuJe](https://github.com/NiLuJe) please look at it. Anything related to fonts?
> 
> I'm on the Voyage too, haven't encountered the issue when was on 5.13.6 (downgraded to 5.9.6 because of the battery drain).

I am curious about the power drain. May I ask how many reading hours you got before and after the downgrading. Thank you.
