### ISSUE TITLE
Keyboard settings not available on NT

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#11934]
* KOReader version: sourdough 
* Device: kindle 3 and 4

#### Issue
Keyboard settings normally found on top menu under `cog` > `Device` > `keyboard` are not available on non-touch devices.
Not sure why this is the case as all devices need a virtual keyboard, even those with physical ones like kindle keyboards.

#### Steps to reproduce
go to `cog` > `Device` and see that no `keyboard`  is to be found.

**Comment by pazos** [comment]
Indeed, good catch!

You might want to move `common_settings.keyboard_layout` from the `if Device:isTouchDevice()` block. See https://github.com/koreader/koreader/blob/master/frontend/ui/elements/common_settings_menu_table.lua#L273-L292

**Comment by Commodore64user** [comment]
Okay, i'll add this to #11933 later.
