### ISSUE TITLE
Long Press on text in epub book doesnt show translate option directly

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#11937]
Hello dear developers, I have kindle pw5 11th gen 6.8 inch with latest version of ko reader installed.

**issue:**

When I press single word, by default only highlight, Wikipedia, Search and Close options come.

**Comment by pazos** [comment]
"Cog wheel" -> "Taps and gestures" -> "Long-press on text" -> Uncheck "dictionary on single word selection"

**Comment by tarungupta2001** [comment]
ok, thanks a lot. My issue is resolved. Very much thanks again
