### ISSUE TITLE
Too big indentation. I can't fix it.

### ISSUE THREAD

**Issue by readinggirlfriend** [koreader/koreader#11935]
* KOReader version: 2024.04-117
* Device: PocketBook 633 Color

I noticed that the book has too big indentations. Unfortunately, I was unable to fix the error using the program settings.
Help me fix this with a new user styletweak. Can you write a code please?
The problem shown in the photos (with HTML). 

![IMG_20240531_200928.jpg](https://github.com/koreader/koreader/assets/171361008/4ba79d15-0b4b-4c1e-a0b0-5eb33674c91a)

![IMG_20240531_200919.jpg](https://github.com/koreader/koreader/assets/171361008/e75b1065-be72-4d50-ad86-131928ba50a0)

Steps to fix:
1. Write a user styletweak
2. Add a new reset setting to the styles menu.

**Comment by readinggirlfriend** [comment]
```
/* User style tweak для KOReader */
.calibre p, .calibre div, .calibre2 p, .calibre2 div, .Style, .calibre16 {
  text-indent: 0em !important; /* Убирает отступ первой строки абзаца */
  margin-top: 0em !important; /* Убирает верхний отступ абзаца */
  margin-bottom: 0em !important; /* Убирает нижний отступ абзаца */
}

```

I wrote this code, the indents have become smaller, but they are still larger than usual and than in other books. Please help me fix the code.

**Comment by readinggirlfriend** [comment]
```
/* User style tweak для KOReader */
.calibre p, .calibre div, .calibre2 p, .calibre2 div, .Style, .calibre16 {
  text-indent: 0em !important; /* Убирает отступ первой строки абзаца */
  margin-top: 0em !important; /* Убирает верхний отступ абзаца */
  margin-bottom: 0em !important; /* Убирает нижний отступ абзаца */
}

```

I wrote this code, the indents have become smaller, but they are still larger than usual and than in other books. Please help me fix the code.

**Comment by poire-z** [comment]
Didn't we already help you solve a similar issue of yours in https://github.com/koreader/koreader/discussions/11861 ?

**Comment by readinggirlfriend** [comment]
> Didn't we already help you solve a similar issue of yours in https://github.com/koreader/koreader/discussions/11861 ?

SORRY PLEASE. 
I accidentally deleted file, then I searched for this thread for a long time, couldn’t find it, so I had to create a new one!

**Comment by readinggirlfriend** [comment]
https://github.com/koreader/koreader/discussions/11947#discussioncomment-9627130
