### ISSUE TITLE
Book cover on the screen off

### ISSUE THREAD

**Issue by TaisekiRey** [koreader/koreader#11938]
Device: Pocketbook 629 Verse
Version: 2024.04
I'm looking for a feature that will allow me to put the book cover on the screen off (The function in the system settings puts the cover of the book that I opened in PBreader). I found a mention of screensaver, but in Settings -> Screen I can't find it. What do I need to do, or where can I find it?

**Comment by tymmej** [comment]
https://github.com/koreader/koreader/wiki/Coverimage

**Comment by TaisekiRey** [comment]
Thanks!
