### ISSUE TITLE
FR: A function to save notes directly without showing Note Edit Dialog

### ISSUE THREAD

**Issue by plateaukao** [koreader/koreader#11948]
**Does your feature request involve difficulty completing a task? Please describe.**
Yes. 
Now I am writing a [plugin](https://github.com/plateaukao/AskGPT) (which is forked from AskGPT plugin) to query OpenAI API, and also Google's Gemini API, as a dictionary and translator. 
After getting results from API, I would like to save them along with the selected highlight text. However, now I can only found following function in `readerhighlight.lua`. It first saves the highlight, and then show up the edit dialog with `self.editHighlight()`.

```lua
function ReaderHighlight:addNote(text)
    local index = self:saveHighlight(true)
    if text then -- called from Translator to save translation to note
        self:clear()
    end
    self:editHighlight(index, true, text)
    UIManager:close(self.edit_highlight_dialog)
    self.edit_highlight_dialog = nil
end
```

There's no way to skip the edit dialog, which means every time I want to save the results, I have to see the dialog, and then click Save.

<img width="180" alt="image" src="https://github.com/koreader/koreader/assets/4084738/6b72df5e-27df-41dd-a233-aca971cff10d"> ===> <img width="180" alt="image" src="https://github.com/koreader/koreader/assets/4084738/b549bed7-f72a-4970-acdf-a249c1ff8081">

**Describe the solution you'd like**
1. provide another function in ReaderHighligh class to add note directly, 
2. or, please help me to check why can't I access `self.ui.annotation` as other plugins. I couldn't figure out why it's not initiated in my case.

**Describe alternatives you've considered**
No.

**Additional context**
My PR that tries to do it: https://github.com/plateaukao/AskGPT/pull/1/files
Originally, with `ui.highlight:addNote(result_text)`, it works; just with an edit dialog.
```lua
            local function handleAddToNote()
              -- ui.highlight:addNote(result_text)
              local index = ui.highlight:saveHighlight(true)
              local a = ui.annotation.annotations[index]
              a.note = result_text
              ui:handleEvent(Event:new("AnnotationsModified",
                                    { a, nb_highlights_added = -1, nb_notes_added = 1 }))

              UIManager:close(chatgpt_viewer)
              ui.highlight:onClose()
            end
```
I tried to extract codes from `self.ui.bookmark:setBookmarkNote` but it always tells me that `ui.annotation` is nil.

Error log:
```Failed to run script: ...ulated/0/koreader/plugins//askgpt.koplugin/askdialog.lua:113: attempt to index field 'annotation' (a nil value)```

**Comment by hius07** [comment]
What KOReader version are you working at?

**Comment by plateaukao** [comment]
@hius07 
It's version 2024.04.

**Comment by hius07** [comment]
No annotations there yet, take the nightly build.

**Comment by plateaukao** [comment]
Got it. let me try! Thanks.

**Comment by plateaukao** [comment]
@hius07 
It works! Thanks for the hint!!
No wonder I can't figure out why. I keep checking latest codes on github, and debugging my plugin with stable version...
