### ISSUE TITLE
FR: ReaderFooter - why same as book margins are disallowed in alongside mode

### ISSUE THREAD

**Issue by tymmej** [koreader/koreader#11951]
I wonder why same as book margins are disallowed in alongside mode.

It looks like it was changed in #7391.

It looks like removing second part of condition at https://github.com/koreader/koreader/blob/99447414dc37cd3c81c1e081b78e545fdc1cb80a/frontend/apps/reader/modules/readerfooter.lua#L1268 allows to set this option and in my limited testing it looks like everything is OK:
- visually progress bar + text has same width as book
- changing margins causes changes in width of footer

I wonder if there's some edge case where everything breaks or it's leftover from old times.

**Comment by hius07** [comment]
Seems to work good. Actually they become not "Progress bar margins" but "Status bar margins".
