### ISSUE TITLE
Error when showing the sleep screen on Clara BW after mupdf update

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#11952]
* KOReader version: Building from scratch
* Device: Clara BW

#### Issue
After today changes in mupdf in development, all devices I have work well when setting the cover as sleep screen but the Clara BW. In the Clara BW I get an image with black and white squares when suspending the device 

This is the warning is showing crash.log:
06/01/24-17:04:38 WARN  failed rendering image (MuPDF): ./ffi/mupdf.lua:810: 'const struct 1969' is not callable

It could be a problem in my configuration but all other devices (PocketBook Era, Libra2, and Palma) work properly.

#### Steps to reproduce
Set book cover as sleep screen and suspend the device

**Comment by Frenzie** [comment]
Pinging @NiLuJe, because if it works on the Libra 2 that's a confusing datum.

**Comment by NiLuJe** [comment]
That's in the RGB -> BGR swap branch, which is pretty rarely exercised (and, in fact, shouldn't be exercised *at all* on that device, so I guess there are two issues ;p).

I'll look into why the Clara BW is flagged BGR (it shouldn't, but get me a *full* `crash.log` to confirm, though).

In the meantime, ping @benoit-pierre in case there have been API shenanigans that might have been missed around that specific `fz_convert_pixmap` call.

**Comment by NiLuJe** [comment]
That should do it for the actual API issue ;).

**Comment by jospalau** [comment]
Commenting self.hasBGRFrameBuffer = yes in device.lua for kobo makes it work. Thanks
