### ISSUE TITLE
OPDS Connection to Calibre does not display all books. Only in Title View.

### ISSUE THREAD

**Issue by SilhouetteCipher** [koreader/koreader#11968]
* KOReader version: v2024.04-134-g8977e5e12_2024-06-01
* Device: Kobo Clara BW

#### Issue
OPDS doesnt display all books in title view. Connected to Calibre. All books are accessable via author but when selecting title rather than getting a letter to pick to filter the books (like it does for author) KOreader displays the list of books but only three pages worth. 

Ive checked on android connected to same calibre library and im not getting the same issue. 

#### Steps to reproduce
Standard OPDS broswing behaviour.

**Comment by Frenzie** [comment]
Is there a calibre demo server or some such?

**Comment by SilhouetteCipher** [comment]
No but I can see that would be helpful. I can look to open the opds up to
remote access for a time. I’ll have an investigate.

**Comment by Frenzie** [comment]
I probably won't have time to look at it, but if I do I wouldn't want to waste a lot of time setting it up anyway, and I doubt anybody else would either. I think @NiLuJe uses calibre fwiw.

**Comment by SilhouetteCipher** [comment]
No worries. As I say it’s not a huge issue. I can work around it but wanted
to report it so it’s out there. It’s not happening on my android install of
KOreader either so it’s even less of an issue.

**Comment by Frenzie** [comment]
> It’s not happening on my android install of KOreader either

Wait, that's what you meant by Android? That's very odd. One thought in that case is that there may be some condition where the OPDS plugin gets slightly stuck and restarting the program might work around it?

**Comment by NiLuJe** [comment]
A dump of the affected XML could be helpful, though ;).

**Comment by NiLuJe** [comment]
Also: on which calibre version is that (and is that with the stock calibre OPDS server of a third-party one?)

**Comment by NiLuJe** [comment]
And, lastly: how many books are we talking about here?

**Comment by NiLuJe** [comment]
Okay, I can reproduce over here.

But I'm seeing the exact same thing when poking at the server directly via `http`, so, err, working as intended?

**Comment by NiLuJe** [comment]
What *is* broken is the detection of the search feature, as well as the navigation across such a list.

**Comment by NiLuJe** [comment]
I can only assume that when you meant that you checked on Android, you did so with another client entirely ;).
