### ISSUE TITLE
Setting of "Alt Status Bar" is not remembered

### ISSUE THREAD

**Issue by claus-von-gmx** [koreader/koreader#11960]
Every time I open a new book I have to set "show alt status bar" again (i.e. Version 2024)

**Comment by Commodore64user** [comment]
okay.

this ticket has an incredibly low amount of effort put into it.

**Comment by hius07** [comment]
Long-press on the `on` toggle.

**Comment by mergen3107** [comment]
That is because you need to long press this setting in the bottom menu to make it default for new books.
