### ISSUE TITLE
Norwegian-english dictionary 

### ISSUE THREAD

**Issue by jelle814** [koreader/koreader#11970]
* KOReader version: 2024.04
* Device: Hisense a5pro

#### Issue
the Norwegian bokmål-english wiktionary doesn't want to extract, all the other dictionaries I tried extracted automatically. I tried to extract this one with an app but that also gave an error
#### Steps to reproduce
go to the dictionary settings-> download dictionaries -> Norwegian bokmål -> wiktionary 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by jelle814** [comment]
thnx for solving!

**Comment by Frenzie** [comment]
np
