### ISSUE TITLE
(mupdf) Dictionary fallback symbols

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#11983]
* KOReader version: koreader-kindlepw2-v2024.04-147-gf33059323_2024-06-05
* Device: Kindle Scribe (5.16.2)

#### Issue
I believe since recent mupdf changes there are no more fallback fonts for "speaker" icons (and many others).

#### Steps to reproduce
Here is screenshot for 2024.04-147 of the word "quaint":
![Reader_2024-06-05_134406](https://github.com/koreader/koreader/assets/6279855/00b16dc2-c00e-4707-8668-be84e532f5f4)

Here is how it looked like before:
https://github.com/koreader/koreader/wiki/Dictionary-support#an-example-of-how-to-apply-this-on-a-dictionary

Can this be fixed?
Not a major issue by any means, just my observations.

@benoit-pierre ?

**Comment by benoit-pierre** [comment]
> * KOReader version: 2024.04-147

It's better to provide the full version, with the git commit hash (`v2024.04-147-gf33059323` can be used with git commands).

**Comment by mergen3107** [comment]
@benoit-pierre 
koreader-kindlepw2-v2024.04-147-gf33059323_2024-06-05

**Comment by mergen3107** [comment]
I don't know if that's related, but I found these lines in the crash.log:
```
warning: line feed missing after stream begin marker (5 0 R)
warning: line feed missing after stream begin marker (29 0 R)
```

upon quick search in the files, `line feed missing after stream begin marker` is in `koreader\libs\libmupdf.so`

**Comment by NiLuJe** [comment]
Ought to be fixed via https://github.com/koreader/koreader-base/pull/1815, bumped in https://github.com/koreader/koreader/commit/206de629d82904a078d16f129ec8638eb862d78d

Please re-open if tomorrow's nightly is still affected ;).

**Comment by mergen3107** [comment]
Thank you very much @benoit-pierre 
Speakers icons are back in 2024.04-164 nightly
