### ISSUE TITLE
Some DoubleSpinWidget UI components do not reflect their state correctly

### ISSUE THREAD

**Issue by Aurum-Vale** [koreader/koreader#11995]
* KOReader version: v2024.04-154-gc8f4008e9_2024-06-08
* Device: any (found on a Kobo Aura, reproduced on the dev emulator)

#### Issue

Some instances of the `frontend/ui/widget/doublespinwidget.lua` UI component do not reflect correctly on screen their intended internal state. This notably happens with the ones using callback to enforce custom minimums and maximum on the input values.

Exemples include:

- `frontend/ui/elements/page_turns.lua`, for setting custom tap zone widths: To increase the left value over "100 - right value", it is necessary to lower the right value, apply, leave and re-enter the component. Moreover, the sum of the two pickers can be over 100, which when applied, results in implicitly lowering the left value, which may be confusing for the user.
- `frontend/apps/reader/modules/readerdevicestatus.lua`, for the battery level alert thresholds. This is the same issue in reverse, as the constraint that is applied here is "left value <= right value".
- There might be another instance or two that I missed, I noticed few of them not being concerned by those kind of constraints which do not need fixing.

#### Steps to reproduce

Here are walkthroughs of the above exemples:
- Top Menu -> Third tab -> Taps and gestures -> Page turns -> Tap zones [...], Select Left/right or Top/bottom and play around with the tap zone sizes, for example, decreasing the right value and trying to increase the left value.
- Top Menu -> Third tab -> Device -> Device status alerts, tick Battery Level and play around with the thresholds.

I have tried to fix the bug by myself, but I couldn't find where to effectively correct the behavior (and I am not comfortable enough with extending the NumberPicker widget, which is widely used everywhere). I have tried unsuccessfully a few changes, and so I'm hoping to learn from contributors with more experience with the project's frontend.

**Comment by Frenzie** [comment]
@hius07 probably knows the most about those offhand.

**Comment by hius07** [comment]
(1) To comply with various relations/constraints between left and right min and max values you will need to introduce `left_min_func()`, `left_max_func()`, `right_min_func()`, `right_max_func()` defined in the caller and passed to the DSW.
Min/max values will be recalculated on every left/right numberpicker change:
https://github.com/koreader/koreader/blob/c8f4008e9bac064da26cff2550e48e5a327d0c93/frontend/ui/widget/doublespinwidget.lua#L121-L126 I believe it's an overengineering we do not need so far.

(2) I'm happy to just avoid saving incorrect values in the page turns settings:
https://github.com/koreader/koreader/blob/c8f4008e9bac064da26cff2550e48e5a327d0c93/frontend/ui/elements/page_turns.lua#L75-L77 Maybe it is worth to add something similar to ReaderDeviceStatus.

(3) Assume you have done (1), have 25%/75% backward/forward zones, and want to increase the forward zone.
You will need to decrease the backward zone at first.
Currently I can increase the forward zone immediately and the backward zone will be adjusted automatically.
I think it's not confusing but convenient, everyone understands the 100% limit.

**Comment by Aurum-Vale** [comment]
(1) I agree this would lead to over-engineering it, this comforts me that asking before rushing a PR was the good choice.

(2) I'm actually not sure I understand the expected behavior of the battery alarm feature. Is the alarm raised from reaching under the low threshold, and kept on until reaching over the high threshold again? If so, I'd be up to add a similar check in the callback: would you then have a preference on which value should take precedence over the other? I believe the low threshold should take precedence, with the **high threshold automatically adjusted to be higher or equal than the low threshold.**

(3) The opposite does not currently work. If you want to increase the backward zone, you must first decrease the forward zone, apply it, close the widget, reopen it, and then you will be able to increase the backward zone.
- If you don't open it again, you will have a dead zone instead, because the last snippet you shared only corrects the backward value.
- A **possible bandaid** could be to set the both left_min, right_min to 0 and left_max, right_max to 100 for the page_turns widget, and let the callback correct the backward value as is already the case.

https://github.com/koreader/koreader/blob/c8f4008e9bac064da26cff2550e48e5a327d0c93/frontend/ui/elements/page_turns.lua#L64

(4) I looked into the other instances of the DSW:
- `frontend/apps/reader/modules/readertypography.lua` does not need additional checks.
- `frontend/ui/elements/refresh_menu_table.lua` does not need additional checks. On a side note, maybe a "long press to edit" mention might be a plus?
- `frontend/apps/reader/modules/readertypography.lua` seems to already control everything using the callback.
- `frontend/ui/widget/configdialog.lua` : not sure I understood this one correctly, I think it relates to the instances in the bottom menu of the reader? All instances I found in the bottom menu did not need additional checks.
- `plugins/autowarmth.koplugin/main.lua` does not need additional checks.
- `plugins/coverbrowser.koplugin/main.lua` does not need additional checks.
- `plugins/statistics.koplugin/main.lua` **may need an additional check** to **ensure right value is >= left value** when saving to config.

https://github.com/koreader/koreader/blob/c8f4008e9bac064da26cff2550e48e5a327d0c93/plugins/statistics.koplugin/main.lua#L1067-L1098

If those proposals (in bold) for (2), (3) and (4) sound good to you, I'd like to make a PR integrating those as this is a good opportunity for myself to familiarize with the GitHub workflow.

**Comment by hius07** [comment]
(2) The high threshold is checked when the battery is charging, to avoid overcharging.
Actually low/high thresholds are rather independent.
(3) The dead central zone is on purpose, some users prefer to turn pages with narrow left/right edge zones.

**Comment by Aurum-Vale** [comment]
(2) Thanks for clarifying, then there's no need for modifications here.

(3) The proposed change would not affect the possibility of a dead zone (it's on me not to have said that I know it's part of the feature).

(4) What would you suggest for `plugins/statistics.koplugin/main.lua`? I believe it may need an additional check to ensure right value is >= left value when saving to config.

https://github.com/koreader/koreader/blob/c8f4008e9bac064da26cff2550e48e5a327d0c93/plugins/statistics.koplugin/main.lua#L1067-L1098
