### ISSUE TITLE
Not working on Kobo libra colour

### ISSUE THREAD

**Issue by Ghdhdhdh** [koreader/koreader#12001]
* KOReader version:Sourdough/Latest
* Device: Kobo libra colour

#### Issue
hen opening the softmod book, my kobo just crashes. That simple

#### Steps to reproduce
Donload https://github.com/NiLuJe/kfmon/raw/master/tools/install.ps1 and latest zip file into a folder on windows.
Run install.ps1
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:
Couldn't even acsess it.

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
Assuming you mean latest stable and not latest nightly, try https://build.koreader.rocks/download/nightly/

You'll need to overwrite .adds/koreader

**Comment by Ghdhdhdh** [comment]
overwrite what?

**Comment by CostcoFanboy** [comment]
> Assuming you mean latest stable and not latest nightly, try https://build.koreader.rocks/download/nightly/
> 
> You'll need to overwrite .adds/koreader

I'm unable to find the nightly -> stable/snapshot release cycle. 

Would you kindly be able to approximate when a stable release would be out?
(Nothing precise ofc, e.g. "2024 Q4")

This app seems to be a complete work of art that puts to shame the stock experience and I don't think I'd be purchasing a Libra Colour without this.

Thank you for all your work, patience and diligence.

**Comment by Ghdhdhdh** [comment]
Nightly builds imort the ko-reader folder but no png is showing up.

**Comment by Frenzie** [comment]
> Would you kindly be able to approximate when a stable release would be out?
> (Nothing precise ofc, e.g. "2024 Q4")

Every 1-2 months.

> Nightly builds imort the ko-reader folder but no png is showing up. And with latest stable. The Png doesn't do anything.

Install the latest stable as usual (NickelMenu, etc.), then overwrite .adds/koreader with a nightly build.

**Comment by jonnyl2** [comment]
Couldn't they just switch the Update channel in `Top menu -> Hamburger -> Update -> Settings -> Update channel ->` to Development and update OTA?

**Comment by Frenzie** [comment]
No, it's a new device that won't start on the current stable.

**Comment by bmidi** [comment]
> Assuming you mean latest stable and not latest nightly, try https://build.koreader.rocks/download/nightly/
> 
> You'll need to overwrite .adds/koreader

This domain doesn't seem to be working. Current build is not working for me either, seems to be the same.
[koreader-crashlog.txt](https://github.com/user-attachments/files/15945765/koreader-crashlog.txt)

**Comment by Frenzie** [comment]
That's the old version.

**Comment by bmidi** [comment]
> That's the old version.

where's the new version?

**Comment by benoit-pierre** [comment]
The nightlies 

> > Assuming you mean latest stable and not latest nightly, try https://build.koreader.rocks/download/nightly/
> > You'll need to overwrite .adds/koreader
> 
> This domain doesn't seem to be working.

See https://github.com/koreader/koreader/issues/12073.

> where's the new version?

You can get a zip from [there](https://gitlab.com/koreader/nightly-builds/-/jobs/7152185328).

**Comment by bmidi** [comment]
> The nightlies
> 
> > > Assuming you mean latest stable and not latest nightly, try https://build.koreader.rocks/download/nightly/
> > > You'll need to overwrite .adds/koreader
> > 
> > 
> > This domain doesn't seem to be working.
> 
> See #12073.
> 
> > where's the new version?
> 
> You can get a zip from [there](https://gitlab.com/koreader/nightly-builds/-/jobs/7152185328).

Thank you! And sorry I missed that
