### ISSUE TITLE
Power off cover image garbled on Kobo Libra H2O

### ISSUE THREAD

**Issue by alex12500** [koreader/koreader#12009]
* KOReader version: 2024-04 (stable)
* Device: Kobo Libra H2O

#### Issue
Although the sleep screen cover image displays ok, the power off cover image doesn't. It shows the full cover of the book only for a split second and then shrinks it to about 1/4th of the screen height. The rest of the power off screen shows an enlarged and  distorted small portion of the nickle home screen.
On Kobo Glo HD with same version of koreader there is no issue with the power off image, only on Kobo Libra H2O.
#### Steps to reproduce
Exit->Power off 
(with Screen->Sleep screen->Wallpaper settings = Show book cover on sleep screen)

**Comment by Frenzie** [comment]
I think there may have been some changes. Would you mind checking the nightly?

**Comment by alex12500** [comment]
2024.04-161: same behaviour

**Comment by NiLuJe** [comment]
What FW version is the affected device running on?

Because that very very very much looks like it's not actually powering off, but switching back to 16bpp and then restarting Nickel (and then nickel failing to switch to 32bpp again, which is... weird?).

(Also: verbose debug logs, please ;)).

**Comment by NiLuJe** [comment]
FWIW, because I had my own H2O sitting on the power-off screen: can't reproduce on 2024.04-71 on 4.37.

**Comment by NiLuJe** [comment]
Oh, wait, it's a Libra, not a H2O -_-". 

Yeaaah, definitely gonna want logs then ;).

**Comment by alex12500** [comment]
FW version 4.31.19086, launching Koreader from NickelMenu

[crash.log](https://github.com/user-attachments/files/15809775/crash.log)

**Comment by NiLuJe** [comment]
Hmm. Looks sane.

Couple things to try:

* Does this happen when the last opened book is an ePub instead of a PDF?
* Does this happen if you set an actual image as the sleep screen?

And, finally: try updating to the current FW version. There were a couple of dodgy ones in the 4.3x series, and I can't quite remember which ;).

**Comment by alex12500** [comment]
Does not happen with epubs or custom image as sleep screen. Only with pdf.

FW: I'm using 4.31.19086 because it is the last one where font mangement in kepubs works. (After that kobo introduced the supplmental font in kepubs that doesn't work at all and causes an annoying popup everytime I open a kepub that contaons words with diacritics which a lot of my books do)

If you still think it could be caused by the FW I can check by installing the latest one and then downgrading again, but the fact that the problem only occurs with pdfs probably means it is not caused by the FW?

**Comment by NiLuJe** [comment]
Is it a pure nickelmenu setup or a nm + kfmon one (e.g., like what the OCP
packages do)?

**Comment by alex12500** [comment]
nm + kfmon (installed with your one-click install package posted on mobileread)

**Comment by alex12500** [comment]
When unchecking Bypass the WAIT_FOR ioctls in the developer options, there is no more issue with the power off screen for pdfs.
No idea what this WAIT_FOR ioctls does or why it was checked.
On Glo HD it doesn't matter whether it is checked or not, only on Libra H2O selecting this option causes the power off screen issue.
I also noticed that (with 'Add custom message to sleep screen' selected and using the default message) on Libra H2O the power off screen has the centered 'Sleeping' info box on the power off screen and additionally a 'powered off' message at the upper right corner of the screen while the Glo HD displays 'Powered off' in the centered info box.

**Comment by NiLuJe** [comment]
> No idea what this WAIT_FOR ioctls does or why it was checked.

Because the driver is broken on your device, so it's disabled by default. You'll encounter random 5s stalls on flashing refreshes with it unchecked.

> I also noticed that (with 'Add custom message to sleep screen' selected and using the default message) on Libra H2O the power off screen has the centered 'Sleeping' info box on the power off screen and additionally a 'powered off' message at the upper right corner of the screen while the Glo HD displays 'Powered off' in the centered info box.

That's... interesting. But I don't even recall how this is all supposed to behave ;D.

**Comment by NiLuJe** [comment]
> > I also noticed that (with 'Add custom message to sleep screen' selected and using the default message) on Libra H2O the power off screen has the centered 'Sleeping' info box on the power off screen and additionally a 'powered off' message at the upper right corner of the screen while the Glo HD displays 'Powered off' in the centered info box.
> 
> That's... interesting. But I don't even recall how this is all supposed to behave ;D.

Double-checked, that would imply that the Glo HD doesn't actually have a custom message *set*, in which case the "custom" message inherits the event message's text (poweroff/reboot, suspend doesn't have one), and the actual event message overlay is disabled.
In short it just means that the event message inherits the display style set by the user for custom messages instead of using its default top-right overlay.

Now, the settings have been revamped recently, so it's entirely plausible that you can no longer not have a custom message being set, potentially explaining the confusion.

**Comment by alex12500** [comment]
> Double-checked, that would imply that the Glo HD doesn't actually have a custom message _set_, in which case the "custom" message inherits the event message's text (poweroff/reboot, 

Yes, when actually editing the default custom message on the GLO HD, it behaves the same way as the Libra H2O 

> > No idea what this WAIT_FOR ioctls does or why it was checked.
> 
> Because the display driver is broken on your device, so it's disabled by default. You'll encounter random 5s stalls on flashing refreshes with it unchecked.
> 
Ah, thanks, so I'll make sure it stays checked...
