### ISSUE TITLE
PDF links can result in crash

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#12017]
* KOReader version: 9724dcd
* Device: Kobo, desktop SDL

#### Issue
It seems that some links have changed with the MuPDF upgrade. They used to say `x = 0`, `y = 0`, now they're `0/0`.

```
06/12/24-18:19:00 DEBUG ReaderLink:onGotoLink: Internal link: {
  page = 9,
  pos = {
    x = 0/0,
    y = 0/0
  } --[[table: 0x7f0e5fa1eea0]],
  x0 = 65.1968994140625,
  x1 = 377.00799560546875,
  y0 = 153.42599487304688,
  y1 = 164.97799682617188
} --[[table: 0x7f0e5fa1ee58]]
```

Which ultimately leads to:

```
./luajit: frontend/apps/reader/modules/readerpaging.lua:907: attempt to get length of local 'new_page_states' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerpaging.lua:907: in function 'onScrollPanRel'
	frontend/apps/reader/modules/readerpaging.lua:1158: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/apps/reader/modules/readerlink.lua:784: in function 'onGotoLink'
	frontend/apps/reader/modules/readerlink.lua:642: in function 'callback'
	frontend/ui/widget/linkbox.lua:50: in function 'action'
	frontend/ui/uimanager.lua:1020: in function '_checkTasks'
	frontend/ui/uimanager.lua:1470: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x55f7991f079d
```

At a quick glance I'm not immediately sure at which level this should be solved (at its simplest an `or 0` somewhere). @benoit-pierre if it's still fresh in your mind perhaps you have a suggestion?

#### Steps to reproduce
Click a link in the table of contents on page 6.
[Swiss Mercenaries in the Dutch East Indies 9789400604599.pdf](https://github.com/user-attachments/files/15808376/Swiss.Mercenaries.in.the.Dutch.East.Indies.9789400604599.pdf)

**Comment by benoit-pierre** [comment]
The calls to `fz_resolve_link` on that page return NaNs for the position.

**Comment by NiLuJe** [comment]
Fixed via https://github.com/koreader/koreader-base/pull/1821, bumped in #12024 ;).

**Comment by Frenzie** [comment]
Oh right, it mislead be by saying close 1 & 2 but it should've said close 1 and close 2. xD
