### ISSUE TITLE
Vocabulary builder won't show focus on NT

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#12026]
* KOReader version: 2024.04.153
* Device: K4

#### Issue
vocabulary builder does not  show focus on currently selected items on non touch devices, i.e underline or black box on selected item. This makes it incredibly difficult to navigate and use.

#### Steps to reproduce
Open vocabulary builder on NT and try to use it.

**Comment by Frenzie** [comment]
Ping @weijiuqiao

**Comment by Commodore64user** [comment]
one more thing, the hamburger menu is not accessible either, a key event toggled by pressing the "Menu" key would be greatly appreciated too.

**Comment by weijiuqiao** [comment]
As I don't have a non-touch device, can I rely on the emulator for key events? But the hamburger is accessible on the emulator albeit with a bit of navigating, so maybe they are not quite equivalent?

Also, the contents of hamburger menu indeed do not respond to keys even though I'm already using `self:mergeLayoutInVertical`. Any pointers as to what might be the cause?

**Comment by Frenzie** [comment]
Yes, the arrow keys, page up/down, esc, f1 (menu), and enter are all equivalent.

For the full experience you can run it with DISABLE_TOUCH=1

(typing on my phone atm, can't check anything else)

**Comment by Commodore64user** [comment]
> But the hamburger is accessible on the emulator

yes, sorry about that (I have a patch that disables Menu.mergeTitleBarIntoLayout), the hamburger menu is in fact accessible but all other widgets support opening the menu by pressing the "Menu" key so still disirable here.

and also true, once inside the menu, there is no focus either, so same problem as with the vocab builder there.

**Comment by weijiuqiao** [comment]
I tried many hours but couldn't get the highlight to show up in the menu content. The navigation is working because I can press enter to select switch and buttons, but the log keeps saying `not painting 2 covered widget(s)`. Don't know how to solve it.

Apart from the menu, basic functionalities of the plugin should work fine without any change. At least it's the case for me on the emulator.
