### ISSUE TITLE
koreader installation on old kobo touch  2.0.3 (r41802, 03/08/12) does not work

### ISSUE THREAD

**Issue by benIT** [koreader/koreader#12029]
Hi,
I am trying to install koreader on my old 2011 kobo Touch but this does not work.

Kobo information from the parameters menu : `Version : 2.0.3 (r41802, 03/08/12)`

I follow instruction from [this post ]( https://www.mobileread.com/forums/showthread.php?t=314220 )as follow :

```
ben@desktop /media/ben/KOBOeReader $ cd /media/ben/KOBOeReader/
ben@desktop /media/ben/KOBOeReader $ wget https://storage.gra.cloud.ovh.net/v1/AUTH_2ac4bfee353948ec8ea7fd1710574097/kfmon-pub/OCP-KOReader-v2024.04.zip
...

ben@desktop /media/ben/KOBOeReader $ wget https://storage.gra.cloud.ovh.net/v1/AUTH_2ac4bfee353948ec8ea7fd1710574097/kfmon-pub/kfm_nix_install.zip
...

ben@desktop /media/ben/KOBOeReader $ ls -rtl
total 47420
-rw-r--r-- 1 ben ben   323877 juil. 17  2012 Welcome_Guide_NL.kepub.epub
-rw-r--r-- 1 ben ben   315624 juil. 17  2012 Welcome_Guide.kepub.epub
-rw-r--r-- 1 ben ben   397437 juil. 17  2012 Welcome_Guide_JA.kepub.epub
-rw-r--r-- 1 ben ben   341511 juil. 17  2012 Welcome_Guide_IT.kepub.epub
-rw-r--r-- 1 ben ben   348744 juil. 17  2012 Welcome_Guide_DE.kepub.epub
-rw-r--r-- 1 ben ben   342225 juil. 17  2012 Welcome_Guide_FR.kepub.epub
-rw-r--r-- 1 ben ben   344918 juil. 17  2012 Welcome_Guide_ES.kepub.epub
-rw-r--r-- 1 ben ben 46115380 mai    3 02:55 OCP-KOReader-v2024.04.zip
-rw-r--r-- 1 ben ben     2837 mai    3 02:55 kfm_nix_install.zip
ben@desktop /media/ben/KOBOeReader $ unzip kfm_nix_install.zip
Archive:  kfm_nix_install.zip
  inflating: install.sh              

ben@desktop /media/ben/KOBOeReader $ bash install.sh 
* Here are the available packages:
0: OCP-KOReader-v2024.04.zip
* Enter the number corresponding to the one you want to install: 0
* Preventing Nickel from scanning hidden directories . . .
* Installing OCP-KOReader-v2024.04.zip . . .
Archive:  OCP-KOReader-v2024.04.zip
   creating: /media/ben/KOBOeReader/.adds/
  inflating: /media/ben/KOBOeReader/kfmon.png  
  inflating: /media/ben/KOBOeReader/koreader.png  
  inflating: /media/ben/KOBOeReader/.kobo/KoboRoot.tgz  
   creating: /media/ben/KOBOeReader/.adds/kfmon/
   creating: /media/ben/KOBOeReader/.adds/koreader/
   creating: /media/ben/KOBOeReader/.adds/nm/
...
  inflating: /media/ben/KOBOeReader/.adds/koreader/libs/libzmq.so.4  
  inflating: /media/ben/KOBOeReader/.adds/koreader/libs/libfreetype.so.6  
  inflating: /media/ben/KOBOeReader/.adds/koreader/libs/libjpeg.so.8  
  inflating: /media/ben/KOBOeReader/.adds/koreader/libs/libdjvulibre.so.21  
* Sanity check . . .
* More sanity checks . . .
* Flush to storage device . . .
* Installation successful!
* Please make sure to eject & unplug your device safely!

ben@desktop ~ $ umount /media/ben/KOBOeReader/
```

Then, I remove the USB cable, Kobo says it's "updating"

When Kobo is started, I see the native UI, no change.

I try to click on the koreader png to launch it but this has no effect.

Is there a validated version for old kobo touch device ?

What am I missing ?

Cheers,
ben

**Comment by Frenzie** [comment]
NickelMenu require at least firmware version 4.6. The simplest method would simply be to update the device and to use the method above. 

You should be able to make things work with an older version of KSM but I'm not quite sure which version would be appropriate. For example this version of KSM: https://www.mobileread.com/forums/showthread.php?t=266821

You can also get older (but slightly less old) firmware versions here: https://pgaskin.net/KoboStuff/kobofirmware.html one of the later 2.x or the 3.x firmwares ought to work well with KSM for example.

**Comment by Frenzie** [comment]
PS KSM release instructions: https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices/aa366b55832a8f4a09a00302259639f518547b43#deprecated-alternative-manual-installation-method-based-on-kobo-start-menu

**Comment by pazos** [comment]
soft-float?

can't fix unless you update the firmware

**Comment by NiLuJe** [comment]
I don't recall the exact version for the hardfloat switch, but, regardless, you gain nothing by staying on such an old FW version anyway, so, err, just update ;).

**Comment by benIT** [comment]
Ok, I am new to kobo hacking, I try to upgrade without success.

I first reinitialize  factory settings  by long pressing the buttons, then I try to install the new firmware according to this [matrix compatibility](https://pgaskin.net/KoboStuff/kobofirmware.html)  : 
```
ben@desktop ~/Downloads $ wget https://ereaderfiles.kobo.com/firmwares/kobo5/Aug2023/kobo-update-4.38.21908.zip
--2024-06-15 21:00:04--  https://ereaderfiles.kobo.com/firmwares/kobo5/Aug2023/kobo-update-4.38.21908.zip
Resolving ereaderfiles.kobo.com (ereaderfiles.kobo.com)... 104.18.37.155, 172.64.150.101
Connecting to ereaderfiles.kobo.com (ereaderfiles.kobo.com)|104.18.37.155|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 104868372 (100M) [application/zip]
Saving to: ‘kobo-update-4.38.21908.zip.1’

kobo-update-4.38.21908.zip.1                         1%[>                                                                                                               ]   1,40M  1,36MB/s               ^C

ben@desktop ~/Downloads $ cp kobo-update-4.38.21908.zip /media/ben/KOBOeReader/.kobo/
ben@desktop ~/Downloads $ cd /media/ben/KOBOeReader/.kobo/
ben@desktop /media/ben/KOBOeReader/.kobo $ ls -rtl
total 111424
drwxr-xr-x 2 ben ben      4096 juin  15 20:46 kepub
drwxr-xr-x 2 ben ben     16384 juin  15 20:46 images
-rw-r--r-- 1 ben ben        73 juin  15 20:47 device.salt.conf
-rw-r--r-- 1 ben ben        83 juin  15 20:47 version
-rw-r--r-- 1 ben ben    308224 juin  15 20:47 KoboReader.sqlite
drwxr-xr-x 2 ben ben      4096 juin  15 20:48 Kobo
-rw-r--r-- 1 ben ben      3358 juin  15 20:48 Trolltech.conf
-rw-r--r-- 1 ben ben 113748289 juin  15 20:59 kobo-update-4.38.21908.zip
ben@desktop /media/ben/KOBOeReader/.kobo $ unzip kobo-update-4.38.21908.zip 
Archive:  kobo-update-4.38.21908.zip
  inflating: KoboRoot.tgz            
  inflating: manifest.md5sum         
   creating: upgrade/
   creating: upgrade/mx6sl-ntx/
  inflating: upgrade/mx6sl-ntx/u-boot_lpddr2_256-E60Q90-LPDDR2.bin  
  inflating: upgrade/mx6sl-ntx/u-boot_lpddr2_512-E70Q00-LPDDR2.bin  
  inflating: upgrade/mx6sl-ntx/uImage-E60Q90  
  inflating: upgrade/mx6sl-ntx/ntxfw-E60QM0.bin  
  inflating: upgrade/mx6sl-ntx/u-boot_lpddr2_512-E60QM0A-LPDDR2.bin  
  inflating: upgrade/mx6sl-ntx/u-boot_lpddr2_512-E60Q90-LPDDR2.bin  
  inflating: upgrade/mx6sl-ntx/uImage-E70Q00  
  inflating: upgrade/mx6sl-ntx/uImage-E60QL0  
  inflating: upgrade/mx6sl-ntx/uImage-E60QM0A  
  inflating: upgrade/mx6sl-ntx/ntxfw-E60QM0.bin.header  
  inflating: upgrade/mx6sl-ntx/u-boot_lpddr2_256-E60QL0-LPDDR2.bin  
  inflating: upgrade/mx6sl-ntx/uImage-E60QM0B  
  inflating: upgrade/mx6sl-ntx/u-boot_lpddr2_512-E60QM0B-LPDDR2.bin  
ben@desktop /media/ben/KOBOeReader/.kobo $ ls -rtl
total 210708
drwxr-xr-x 3 ben ben      4096 août  22  2023 upgrade
-rw-r--r-- 1 ben ben      1007 août  22  2023 manifest.md5sum
-rw-r--r-- 1 ben ben 101657596 août  22  2023 KoboRoot.tgz
drwxr-xr-x 2 ben ben      4096 juin  15 20:46 kepub
drwxr-xr-x 2 ben ben     16384 juin  15 20:46 images
-rw-r--r-- 1 ben ben        73 juin  15 20:47 device.salt.conf
-rw-r--r-- 1 ben ben        83 juin  15 20:47 version
-rw-r--r-- 1 ben ben    308224 juin  15 20:47 KoboReader.sqlite
drwxr-xr-x 2 ben ben      4096 juin  15 20:48 Kobo
-rw-r--r-- 1 ben ben      3358 juin  15 20:48 Trolltech.conf
-rw-r--r-- 1 ben ben 113748289 juin  15 20:59 kobo-update-4.38.21908.zip
ben@desktop /media/ben/KOBOeReader/.kobo $ echo "insert into user values('f^C', 'foo', 'foo', 'foo', 'foo');" | sqlite3 .kobo/KoboReader.sqlite 
ben@desktop /media/ben/KOBOeReader/.kobo $ sqlite3 KoboReader.sqlite 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> INSERT INTO user values("00000000-0000-0000-0000-000000000000","00000000-0000-0000-0000-000000000000","MyDummyUser@dummy.com","MyDummyUser@dummy.com","000011");
sqlite> .quit
ben@desktop /media/ben/KOBOeReader/.kobo $ cd
ben@desktop ~ $ umount /media/ben/KOBOeReader/```
```
The "updating screen" appears for a few minutes and kobo reboots.

An error message appears indicating my settings wasn't persisted on the device. After rebooting, the kobo wizard asks me : 
*  to connect wifi => does not work
or
* connect to computer => I plug usb, the ereader asks me to download kobo desktop, the kobo drive is not mounted anymore on my computer

=> I'm stuck at this step. Any help would be appreciated.

Cheers,
ben

**Comment by NiLuJe** [comment]
1. Don't mangle the db manually, that's entirely unnecessary; there's a sideload mode available nowadays.
2. You *may* have to jump through multiple FW versions to upgrade from such an old release... (To be completely safe, I'd go something like last FW 2.x to last 3.x to last 4.x or something).
3. Setup via Wi-Fi will be broken until you hit a recent enough release.

In case you're unsure of the current state of the device, you can start over by forcing a full factory reset (this involves button/tap combos during the early boot process, the exact procedure for your specific device should be detailed in the relevant doc on Kobo's website).

**Comment by pazos** [comment]
You'll also need the proper firmware since you are trying with the wrong one

**Comment by NiLuJe** [comment]
> he exact procedure for your specific device should be detailed in the relevant doc on Kobo's website

i.e., https://help.kobo.com/hc/en-us/articles/360017605174-Manual-reset-your-Kobo-Touch

**Comment by NiLuJe** [comment]
> You'll also need the proper firmware since you are trying with the wrong one

Oops, nice catch ;p.

**Comment by NiLuJe** [comment]
Which means you'll have to check the device's S/N to discriminate the Touch A/B from the Touch C (possibly visible on the device's shell in the model name, too, I can never remember).

IIRC, it's NnnnC for the C variant. I don't remember the actual model number, though (905?).

**Comment by NiLuJe** [comment]
> (905?).

Yep, N905, N905B & N905C.

**Comment by benIT** [comment]
Hi @pazos and @NiLuJe,
thanks for your help!
My kobo is : `Model N905C`, you will find below a fresh photo of this old device :smile:  :
![image](https://github.com/koreader/koreader/assets/2970652/308915d7-ae7b-4e03-a394-da2fc1146517)


So, could you teach me how can I map this information to the [firmware download matrix page](https://pgaskin.net/KoboStuff/kobofirmware.html) in order to catch the right firmware ?
Does my device is a `Kobo Touch A/B`, `Kobo Touch C` or `Kobo Touch 2.0` ?
Greetings,
ben

**Comment by NiLuJe** [comment]
I see you figured it out ;). I'll close this then ;).
