### ISSUE TITLE
FR: Reflow in colour

### ISSUE THREAD

**Issue by afonsoguerra** [koreader/koreader#12032]
**Does your feature request involve difficulty completing a task? Please describe.**
I read scientific literature on android tablet or computer. KOreader works great and the integration of k2pdfopt is perfect, but each time I reflow a PDF, it converts the figures to black and white. 

**Describe the solution you'd like**
An option to configure reflow parameters so that it retains figure colours. 

**Describe alternatives you've considered**
I tried browsing the menus and did menu search but nothing seems to be exposed to the user at the moment. 
I have looked at the k2pdfopt sources in the koreader GitHub organization, and found the -c flag, but have no idea where to use it. 

**Additional context**
I've used k2pdfopt outside of koreader before, so I'm aware of its capabilities, but not much experience with recent koreader. Thanks for your work!

**Comment by afonsoguerra** [comment]
This is not getting much traction. Did I miss something very obvious?

**Comment by poire-z** [comment]
None of us is really familiar with k2pdfopt, except may be @benoit-pierre who had to update it to latest upstream recently. So, it may be will happen when he gets a color device :).

**Comment by Frenzie** [comment]
It shouldn't be very difficult, just needs the time investment.

**Comment by afonsoguerra** [comment]
I'm happy to have a go if I'm given some pointers. Specifically, where is k2pdfopt called, and what is the chain I have to follow to get changes integrated back. 

For clarity, this applies to the emulators (e.g. - MacOS) as well as the kobo colour devices (for which I'm very grateful for the fact that you implemented support in the dev version so quickly). 

I've temporarily reverted back to pre-processing the PDFs I want to read in colour, but it would be happy to spend some time looking into this (even though I'm not a Lua programmer at all, just Python/Perl/R).

Thanks everyone.

**Comment by benoit-pierre** [comment]
Too late: https://github.com/koreader/koreader-base/pull/1836 :P

**Comment by Frenzie** [comment]
It'll drip down from somewhere like frontend/document/document.lua as well as possibly other files in that directory, possibly requiring some changes in base/ffi/koptcontext.lua as well as some changes in the underlying C, or rather the functions we add there to interface with it.

**Comment by Frenzie** [comment]
Er, or what he said in significantly more detail in the meantime apparently.

**Comment by afonsoguerra** [comment]
Thanks! You guys are awesome!
