### ISSUE TITLE
FR: Kindle wifi selector

### ISSUE THREAD

**Issue by notmarek** [koreader/koreader#12040]
**Does your feature request involve difficulty completing a task? Please describe.**
It is very annoying to leave koreader just to connect to a new wifi network.

**Describe the solution you'd like**
A simple wifi selector interacting through lipc with com.lab126.wifid

**Additional context**
Just putting this here so i don't forget to work on this, i have it mostly figured out just need to write some lua and the UI i will open a pull request ASAP.

**Comment by Frenzie** [comment]
The UI already exists; you'd just have to feed it data. (Also see ./kodev wbuilder)

**Comment by notmarek** [comment]
> The UI already exists; you'd just have to feed it data. (Also see ./kodev wbuilder)

thanks for the pointers :)

**Comment by Commodore64user** [comment]
Amazing! Thanks from the bottom of my heart

**Comment by notmarek** [comment]
I've stumbled upon a bit of a problem, kindles lualipc lib has no way to access hashmap properties (they are used by wifid for almost everything) so i guess I will write a small Lua wrapper with the help of https://github.com/arkq/openlipc i just don't know if this should be put into a different repo or added directly into koreader somewhere
