### ISSUE TITLE
Vocabulary builder doesn't grab the prev_context and next_context anymore

### ISSUE THREAD

**Issue by Ceynou** [koreader/koreader#12048]
* KOReader version: At least all from 23.10 to yesterday's nightly build
* Device: Bigme B751 (Android 11, arm)

#### Issue
Vocabulary builder doesn't grab the prev_context and next_context anymore and I don't know what to do, I have tried both enabling and disabling save context just in case they were somehow inverted, I started from scratch, no settings, no .old files either, and still the same issue. It was working on my PW4 but I gave it away in favor of an (TRASH) android device.
![image](https://github.com/koreader/koreader/assets/41862916/d1ba47bb-0e7b-49b1-bf24-9c0cd955dfce)

#### Steps to reproduce
🤷‍♂️

**Comment by NiLuJe** [comment]
> It was working on my PW4 but I gave it away in favor of an (TRASH) android device.

Has it *ever* worked on the new device (ideally, on a version similar enough to what you had working on your PW4)?

**Comment by Ceynou** [comment]
> Has it _ever_ worked on the new device (ideally, on a version similar enough to what you had working on your PW4)?

It never worked, I had not noticed, but they had at least had 23.10 and 24.01 in common.
I also often updated my kindle to nightly builds and before giving it away I backed up the settings, the data and the fonts.
When I got my new ereader I placed the backup in the sdcard0(?), installed koreader(24.03?), verified if it generated the other files and it did.
Did not notice that the vocabulary builder wouldn't grab the sentence until I wanted to sentence mine a few days ago.

**Comment by Ceynou** [comment]
I tried both, first from the backup, then, when I noticed it wasn't working properly, I tries all the versions mentioned with and without my settings, basically from scratch.

If you want me to try anything even if you don't think it will help, I'll do it

**Comment by Ceynou** [comment]
I should have known... I wasted your time, the issue was the [dictionarymode plugin](https://github.com/ckilb/dictionarymode.koplugin), so one tap and the dictionary pops up, would be nice if you "officially" supported it like the vocabulary builder plugin, or implemented it your own way.

Again, sorry for wasting your time.
