### ISSUE TITLE
Dispatcher: Different default values than these in bottom menu

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12057]
* KOReader version: 2024.04-191 (with minor non-related patches that don't affect this issue)
* Device: Kindle Scribe (FW 5.16.2)

#### Issue
I use Profiles for some fonts with six parameters to tweak:
- Font face (without SpinWidget)
- Font size (with SpinWidget, ~correct~ **wrong** default)
- **Line spacing (with SpinWidget, wrong default)**
- Weight (without SpinWidget)
- Kerning (without SpinWidget)
- Hinting (without SpinWidget)

The issue is that

#### Steps to reproduce
See pictures below.
Line spacing from Profiles' setup:
<img src= "https://github.com/koreader/koreader/assets/6279855/ac4455d7-aea6-45d9-b0ed-a2d83322843c" height="600">

Line spacing from the bottom menu:
<img src= "https://github.com/koreader/koreader/assets/6279855/6fc6362d-0b52-4fbe-b39a-9ace2d21e48e" height="600">

##### `crash.log` (if applicable)
I have not crash.log, because I believe this issue is easily reproducible.
I'll double-check in emulator as well.
I believe this issue looks similar to wrong SpinWidget default value passed through as in https://github.com/koreader/koreader/pull/11999/commits/a90c10fdbccb86ff2fd1e8e8e694b540a9172cdc

I'll also wanna double-check all other parameters with SpinWidget.

**Comment by mergen3107** [comment]
What I realized is that these items in Profiles are actually coming from the Dispatcher itself.
I'll see what's wrong with Dispatcher then...

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/fa4654cdfa56e7452f6e6ae43d19cd65c105401c/frontend/ui/data/creoptions.lua#L382
https://github.com/koreader/koreader/blob/fa4654cdfa56e7452f6e6ae43d19cd65c105401c/defaults.lua#L141

**Comment by mergen3107** [comment]
Thanks @hius07 
I searched with rip grep for `Line Spacing` and found these:
```
mergen3107@mateLTS22:~/koreader$ rg -C3 -g '!l10n/' "Line Spacing"
frontend/ui/data/creoptions.lua
361-            },
362-            {   -- ReaderFont
363-                name = "line_spacing",
364:                name_text = _("Line Spacing"),
365-                buttonprogress = true,
366-                values = {
367-                    G_defaults:readSetting("DCREREADER_CONFIG_LINE_SPACE_PERCENT_X_TINY"),

frontend/ui/data/css_tweaks.lua
404-                    title = _("Larger spacing between ruby lines"),
405-                    description = _([[
406-Increase line spacing of most text, so that lines keep an even spacing whether or not they include ruby.
407:Further small adjustments can be done with 'Line Spacing' in the bottom menu.]]),
408-                    css = [[p, li { line-height: 2 !important; }]],
409-                    -- no need for priority, this has higher specificity than lineheight_all_inherit below
410-                },

frontend/ui/data/koptoptions.lua
376-            },
377-            {
378-                name = "line_spacing",
379:                name_text = _("Line Spacing"),
380-                toggle = {C_("Line spacing", "small"), C_("Line spacing", "medium"), C_("Line spacing", "large")},
381-                values = {1.0, 1.2, 1.4},
382-                default_value = G_defaults:readSetting("DKOPTREADER_CONFIG_LINE_SPACING"),

```

I believe the new default setting that can be set in bottom menu should be overring it?

Something like:
```
default_value = self.BOTTOM_MENU_DEFULAT_LINE_SPACING or G_defaults:readSetting("DCREREADER_CONFIG_LINE_SPACE_PERCENT_MEDIUM"), 
```

where I need to find the actual variable name for `self.BOTTOM_MENU_DEFULAT_LINE_SPACING`.

**Comment by hius07** [comment]
Dispatcher does not read the user's "defaults", it shows the default "defaults", it's okay.
Dispatcher does not pass "units" to SpinWidgets (so you do not see the % sign), it can be fixed I believe.

**Comment by mergen3107** [comment]
I did
```
default_value = G_reader_settings:readSetting("copt_line_spacing") or G_defaults:readSetting("DCREREADER_CONFIG_LINE_SPACE_PERCENT_MEDIUM"),
```
and it worked! Although, without `%` sign, but at least correct. 

@hius07 Can I do PR or you have a better approach in mind?

**Comment by mergen3107** [comment]
Overall, I believe these DEFAULT_SETTINGS are legacy from `crengine` and they should be de-duplicated. I don't know how much work that is

**Comment by mergen3107** [comment]
> * Font size (with SpinWidget, correct default)

OK, this was a false positive - it just happened to be the same as `DCREREADER_CONFIG_DEFAULT_FONT_SIZE = 22,    -- default font size` in `defaults.lua`.

**Comment by mergen3107** [comment]
Ah, sorry.
I take my fix above back: `copt_` are not default settings, but rather just current ones.
Where are the default ones are stored?

**Comment by hius07** [comment]
> Overall, I believe these DEFAULT_SETTINGS are legacy from `crengine` and they should be de-duplicated.

Where do you propose to store the settings for the first run, after clean install?

**Comment by mergen3107** [comment]
In a file, but with proper notation with `copt_` and `kopt_` prefixes. By “legacy” I only mean that they now look different from current implementation of settings. 

Maybe copt_default_settingname or copt_setting_name_default.

**Comment by mergen3107** [comment]
Simplest way (I think) to solve these mismatches without major SpinWidget overhauls is replacing global defaults with something like:
```
DCREREADER_CONFIG_LINE_SPACE_PERCENT_MEDIUM = G_reader_settings:readSetting("copt_line_spacing_default") or 100,
```

So, if this is the fresh build, the value will be `100` beacause the `copt_line_spacing_default` doesn't exist yet. However, it needs to be assigned after each `Set as default` SpinWidget action (which I still don't understand where it is saved).

**Comment by yparitcher** [comment]
https://github.com/koreader/koreader/blob/fa4654cdfa56e7452f6e6ae43d19cd65c105401c/frontend/ui/widget/configdialog.lua#L395-396

**Comment by hius07** [comment]
@yparitcher, do you think we should introduce `G_reader_settings` in Dispatcher?
(Just for the user's default values in SpinWidgets - font size, line spacing etc)

**Comment by yparitcher** [comment]
This line:
https://github.com/koreader/koreader/blob/b5a822cf8b7dd3b584d2a6d78a14a557d5669c31/frontend/dispatcher.lua#L540
Should probably be:
```lua
                        settingsList[name].default = G_reader_settings:readSetting(name) or option.default_value
```
Untested, it may need:
```lua
                        default_name = prefix and name or 'copt_' .. option.name
                        settingsList[name].default = G_reader_settings:readSetting(default_name) or option.default_value
```

**Comment by hius07** [comment]
Generally speaking, I would remove "default value" from all SpinWidgets in Dispatcher.
For the consistency reason: there are many other actions that have their default values (in the meaning of applying them to a new book), but we do not mark them in action list because only SpinWidget has the Default button.
So we see the default values only for:
**CRE** Font Size, Line Spacing, Top/Bottom Margin
**PDF** H/V Overlap, Auto Straighten

**Comment by hius07** [comment]
But what definitely must be fixed: consistent min/max values and units in SpinWidgets in theDispatcher and in the ConfigDialog (bottom menu).

**Comment by hius07** [comment]
Is there anything to fix?

**Comment by mergen3107** [comment]
> consistent min/max values and units in SpinWidgets in theDispatcher and in the ConfigDialog (bottom menu)

This?

**Comment by hius07** [comment]
Or, if it is good that SpinWidget in the bottom menu **extends** the progress bar limits, Dispatcher should take extended min/max too.

**Comment by NiLuJe** [comment]
I very very vaguely recall extending the SpinWidget's range on purpose because it was less unwieldy than dealing with old defaults (maybe not for this setting in particular, but, then again, it rings a bell ;)).

**Comment by Frenzie** [comment]
> Or, if it is good that SpinWidget in the bottom menu extends the progress bar limits, Dispatcher should take extended min/max too.

This is the way I see it. The progressbar is for typical values while the spin widget includes values we might consider weirdly high or low.
