### ISSUE TITLE
Filtering annotations triggers a crash

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12052]
* KOReader version: v.2024.04-194
* Device: PB 268

#### Issue
I sorted the annotations of a book by date, in reverse order, and then I filtered them so as to have only the bookmarks. This triggered a crash. This happens with all annotation types.

**Comment by hius07** [comment]
Thank you, confirmed.

**Comment by hius07** [comment]
You can take it before nightly build.
[readerbookmark.lua.txt](https://github.com/user-attachments/files/15901962/readerbookmark.lua.txt)

**Comment by ichnilatis-gr** [comment]
Thanks!
