### ISSUE TITLE
Screenshot dialog not responsive in Text Editor

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12066]
* KOReader version: 2024.04-153
* Device: Kobo

#### Issue

'Screenshot saved to:' dialog is not responsive while in Text editor, and can also not be closed by tapping outside of it. 

#### Steps to reproduce

Open Text editor and take a screenshot. Dialog can only be closed after exiting Text editor.

**Comment by hius07** [comment]
Low hanging fruit.
[screenshoter.lua.txt](https://github.com/user-attachments/files/15931661/screenshoter.lua.txt)
