### ISSUE TITLE
Battery drain oasis 3

### ISSUE THREAD

**Issue by moe123s** [koreader/koreader#12070]
* KOReader version:latest nightly build
* Device:oasis 3

#### Issue
On my oasis 3 latest koreader build. I am having a severe battery drain. While active it is now 9% change per hour. I recall it used to be 3 or 4% has anything changed? Is there settings to make koreader more battery optimized?

**Comment by mergen3107** [comment]
Verbose crashlogs required - do not just blindly remove all template text, it explains stuff on purpose. 

Do you also have high battery drain outside KOReader? Maybe your battery just aged.

**Comment by mergen3107** [comment]
Get battery status from mobileread Snapshots and see what’s your maximum capacity in mAh. Compare this to maximum design capacity.
