### ISSUE TITLE
FR: Pocketbook: config for hardware buttons behaviour

### ISSUE THREAD

**Issue by reuschling** [koreader/koreader#12086]
I like to use both hardware buttons of my pocketbook era to switch to the next page, instead of switching back to the last one with one button. I. e. both buttons should do the same. 

The only config for the hardware buttons I found is inverting these buttons.

I am wondering if it is possible to just adjust hardware button behavior same as the wish and tap gestures, so there would be freedom for all possibilities, which was the behavior of coolReader. But adjusting it a bit more flexible would be fine too. 

Maybe as a fallback, is it possible to adjust this behavior inside a config file? Would be fine for me too.

**Comment by pazos** [comment]
See https://github.com/koreader/koreader/wiki/Keymapping

**Comment by reuschling** [comment]
Perfect, I will give it a try. Is it also possible to set 'go to previous page' to the left corners? I can not find this setting in the gesture config menu. Thanks a lot!

**Comment by hius07** [comment]
> go to previous page

`Turn pages`, -1

**Comment by reuschling** [comment]
It works like a charm, thanks again for your help
