### ISSUE TITLE
Will crash on Mi ReaderPro II

### ISSUE THREAD

**Issue by tianen1108** [koreader/koreader#12081]
* KOReader version: [v2024.04](https://github.com/koreader/koreader/tree/v2024.04)
* Device: Mi ReaderPro II 1.1.4.230529 (Latest System Version)

#### Issue
App Crash once started.
I tried 'SAVE REPORT' button, but it gives me empty file, whether I save it by app or just copying it.
I cannot find any .log file in the root folder of koreader, too.

#### Steps to reproduce
1. Install F-Droid
2. Install Latest Version of KOReader by F-Droid
3. Open KOReader
4. Asked for File Management Authority. Authorized.
5. Re-open KOReader
6. Crash. With Bomb Icon Upside and text "KOReader crashed", And "SAVE REPORT" below.

**Comment by benoit-pierre** [comment]
Please provide some logs, see [this comment](https://github.com/koreader/koreader/issues/10395#issuecomment-1537131597) for instructions.

**Comment by shuvashish76** [comment]
Also you could use LogCat apps like [LogFox](https://github.com/F0x1d/LogFox), add filter for KOReader & record the logs.

**Comment by pazos** [comment]
> Also you could use LogCat apps like [LogFox](https://github.com/F0x1d/LogFox), add filter for KOReader & record the logs.

Did you compare the output of LogFox with the output of pidcat? If not, please do so. We're eager to recommend convenient methods for users, but the only one that's tested is `pidcat` (or a non-filtered adb logcat)

**Comment by pazos** [comment]
No response, no fun
