### ISSUE TITLE
I screwed

### ISSUE THREAD

**Issue by polo2137** [koreader/koreader#12103]
KOReader version: most recent
Device: kobo libra 2

Weird rectangles instead of icons in menu items.

I accidentally deleted file called sth like "freesans" in fonts folder and now I'm left with this weird UI.
Here is a link to a ziped koreader folder: https://we.tl/t-6mLy29YyUj

![IMG_5007](https://github.com/koreader/koreader/assets/123873769/4dc524c5-2af9-451d-8937-26948a8a7a1d)

**Comment by Frenzie** [comment]
Just reinstall it (or go to hamburger → update → settings and pick the development channel, then update)

**Comment by polo2137** [comment]
Thanks!
