### ISSUE TITLE
hrefs in large epub (attached) not working. It works ok in other readers such as Kobo and Calibre

### ISSUE THREAD

**Issue by edo-jan** [koreader/koreader#12102]
* KOReader version: 2024.04-209
* Device: Kobo Libra 2

#### Issue  
Certain links in the (attached) epub do not work while they work fine in the native kobo reader or other epub reading aps (e.g. Calibre reader).

#### Steps to reproduce
Open the book (attached) in Koreader which is a Bible reading plan.  Navigate to TOC and select any month - e.g. January or February. This will open a page (like a mini-TOC) with specific links for each day of the month. None of these links work. I have reviewed the anchors and hrefs and they look fine. As mentioned, everything works in other readers.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
[The One Year Bible NKJV - Tyndale.zip](https://github.com/user-attachments/files/15994206/The.One.Year.Bible.NKJV.-.Tyndale.zip)

<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
Could you be a bit more precise about "certain links"? All links I tried work.

**Comment by Frenzie** [comment]
That is, when I click on "2" in January it takes me to January 2, same for all other numbers.

**Comment by edo-jan** [comment]
> That is, when I click on "2" in January it takes me to January 2, same for all other numbers.

This is exactly what is not working on my end. When I am on the January page and I click on any number nothing happens. I have tried converting the source epub to epub v3 - same result. Also updated Koreader to the latest build - no luck

**Comment by edo-jan** [comment]
all other links on TOC and other places work fine

**Comment by edo-jan** [comment]
btw, the same file works fine in Koreader android on my phone. The issue only occurs in Koreader installed on my Kobo Libra 2

**Comment by poire-z** [comment]
```
06/26/24-21:30:16 DEBUG Checking if link is to a footnote: 57183 /body/DocFragment[10]/body/div/p[2]/a[3].0 #_doc_fragment_12_ January_3_nav
06/26/24-21:30:16 DEBUG is a footnote: no decision, default to be a footnote
06/26/24-21:30:16 DEBUG   not extended because: H1..H6 met
```
So, it is detected as linking to a footnote, and footnote popup does not show up, probably because there is no content:
![image](https://github.com/koreader/koreader/assets/24273478/4ca81343-2e4c-42f8-b60a-ac6b58cfdf3f)
May be the footnote detection code should also check the content is not empty :)

For now, you can either:
- disable footnote popups, under `Gear > Tap & gestures > Links > [ ] Show footnotes in popup`
- or, when it doesn't work but the link stays highlighted (which is what we do when showing a footnote popup, this part still works), swipe to the left (when a footnote popup is displayed, we can do that to go to the page containing the footnote in-the-book) to go where the link leads to.

**Comment by edo-jan** [comment]
> For now, you can either:
> 
> * disable footnote popups, under `Gear > Tap & gestures > Links > [ ] Show footnotes in popup`
> * or, when it doesn't work but the link stays highlighted (which is what we do when showing a footnote popup, this part still works), swipe to the left (when a footnote popup is displayed, we can do that to go to the page containing the footnote in-the-book) to go where the link leads to.

Thank you! disabling footnote popups did the trick!
