### ISSUE TITLE
FR: Reading statistics adjustment

### ISSUE THREAD

**Issue by polo2137** [koreader/koreader#12101]
A big problem for me with the current state of reading statistics is that when I leave my device unlocked with a book's page open it will count the whole time I do something else as the time that it takes me to read a page. Due to mentioned issue the whole reading statistics for this particular book are inaccurate. This happens when for example I'm in work environment and need to make a really quick call or answer a phone or I'm learning and trying to memorise a certain information after already reading the whole page.
The whole problem works the other way around with fast scrolling through the book for example when going back to an information and then returning to the last point.

I propose a really simple solution to let users adjust minimum and maximum time for one page that will be counted in the reading statistics. If mentioned period of time is exceeded then reading statistics wouldn't count that page to the grand scheme of things and instead use previously gathered average. The same solution but backwards applies to minimum setting.

Additionally this new feature could count how many times the device was left for the time that exceeded maximum and then inform user how much battery would be saved if locked properly.

Sorry for my English and thanks in advance.

**Comment by Frenzie** [comment]
The minimum and maximum time can already be adjusted. See Reading statistics → Settings

**Comment by polo2137** [comment]
Oh, sorry then for taking your time! Please inform me should I delete this thread?

**Comment by mergen3107** [comment]
You can just close it as completed.
