### ISSUE TITLE
The popup dictionary shows words that are completely different because of the fuzzy search(?)

### ISSUE THREAD

**Issue by Ceynou** [koreader/koreader#12105]
* KOReader version: **24.01** (because the dictionarymode plugin doesn't work on newer version, also vocab context set to 25 instead of 15)
* Device: **Bigme B751**

#### Issue
Not at home at the moment so I can't prove it but I'll add a video to the comments tonight.
Both are in the vocabulary database, the first one is correct, I only have this example because dictionarymode prevented the vocabulary builder plugin from keeping the context.
> job in the Glass Fish-and-Flower department in a Boston museum) when she interrupted her voluble self to indicate Marina and Aqua, blankly **slinking*** across the hall in modish sullenness and bluish furs with Dan Veen and a dackel behind, and said: “Curious how that appalling actress resembles ‘Eve on

> job in the Glass Fish-and-Flower department in a Boston museum) when she interrupted her voluble self to indicate Marina and Aqua, blankly **stealthy*** across the hall in modish sullenness and bluish furs with Dan Veen and a dackel behind, and said: “Curious how that appalling actress resembles ‘Eve on

#### Steps to reproduce
I don't know, you may see this behavior when none of your dictionaries have the definition for the highlighted word but when the fuzzy search (I assume) still found a result (wrong)

**Comment by Frenzie** [comment]
You can disable fuzzy search in dictionary settings if you don't like it.

**Comment by Ceynou** [comment]
> You can disable fuzzy search in dictionary settings if you don't like it.

I don't dislike fuzzy search? Okay can we make it like I never mentioned fuzzy search, it was just stupid assumption of the culprit of my problem...

**Comment by Frenzie** [comment]
That's not a stupid assumption. It's just a fact. Fuzzy search frequently works out the way you want, sometimes it can come across as random.

**Comment by Ceynou** [comment]
Oh, welp, at least it's clear now, thank you

**Comment by Frenzie** [comment]
You can verify the behavior doesn't occur if you turn fuzzy search off (but I'd only potentially consider turning it off for performance reasons, not for sometimes showing irrelevant results).

**Comment by Ceynou** [comment]
I'll verify but I thought I needed fuzzy search to the word when highlighting something like word-ly, word-some, word-s, word-ed, etc.

**Comment by Frenzie** [comment]
That's correct, and I'd never turn it off myself. But as far as it goes that's the least annoying possibility, just edit and delete a letter or two. It's much more annoying without fuzzy search for words like déjà vu.

**Comment by Ceynou** [comment]
Understood, thank you!
