### ISSUE TITLE
FR: arbitrary zooming mode with pinch-to-zoom gestures for PDF documents

### ISSUE THREAD

**Issue by serdar0020** [koreader/koreader#1210]
I use this for non OCR'd pdf's when the print is too small for portrait mode, but too large to spread over the entire width in landscape mode. It used to be possible with koreader a couple of months ago, by wiping the vertical borders into the dark grey area, manual cropping mode

But no longer. Using Kobo Aura 6", FW 3.11, built 1141

**Comment by vossad01** [comment]
+1

**Comment by volfyd** [comment]
+1

**Comment by woojoo666** [comment]
+1

**Comment by Aliallameh** [comment]
what happened to this feature?

**Comment by goodevilgenius** [comment]
Not just PDFs, but any fixed size files, like comic archives, e.g.

**Comment by poire-z** [comment]
Probably solvable with the added zoom stuff from #6885.
