### ISSUE TITLE
FR: improving dev-x with git-hooks with commitizen and changesets

### ISSUE THREAD

**Issue by Mochitto** [koreader/koreader#12108]
**Does your feature request involve difficulty completing a task? Please describe.**
I think the project would benefit from using [commitizen](https://github.com/commitizen/cz-cli) and [changesets](https://github.com/changesets/changesets) support; implementation takes little effort, enforces consistent commit messages for contributors and delegates changelog writing to contributers.

Git hooks are handled through [husky](https://www.npmjs.com/package/husky), meaning contributors will be asked whether they want to add a changeset to the commit and a TUI walking them through writing the commit, upon writing `git commit`.
I'm not sure if the project has tests, but the hooks could also block commits if they fail any command that we could add (such as running tests).
Commits are also blocked if they do not match the decided commit message standard.

Maintainers can just run `changeset version` to build the CHANGELOG and update the package version automatically; this can be added into the CI/CD process as well.

I'm willing to add support myself, as I've done so at work and in personal projects.

**Issues**
This means adding as a development dependency some javascript code with npm.
An extra build step would be added as running `npm i` before contributing, to install these libraries.

**Comment by Frenzie** [comment]
Thanks for the suggestion, but I don't think anyone's waiting for this.

**Comment by Mochitto** [comment]
Np :) Thanks for considering it; I'll still be open if this comes up in the future
