### ISSUE TITLE
OTA manager crash: getZsyncFilename

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12115]
* KOReader version: anything after commit number 205 

https://github.com/koreader/koreader/commit/617618d5878591f47f7b0b35de9042de3d19a950#diff-78c3d893c874173e65c3668e2ea45fdc791c5abb719f3c90ff43111c7aa61bce

![image](https://github.com/koreader/koreader/assets/6279855/1287d64d-570e-4184-8604-11a600f68336)

* Device: Kindle Scribe (5.16.2)

#### Issue
Crash on KOReader update after it finds there is a new version and I hit Update.
Pinging @pazos 

##### `crash.log` (if applicable)
Full: [ota_crashlog.txt](https://github.com/user-attachments/files/16033087/ota_crashlog.txt)

Crash:
```
./luajit: frontend/ui/otamanager.lua:371: attempt to call method 'getZsyncFilename' (a nil value)
stack traceback:
	frontend/ui/otamanager.lua:371: in function 'zsync'
	frontend/ui/otamanager.lua:229: in function 'action'
	frontend/ui/uimanager.lua:1020: in function '_checkTasks'
	frontend/ui/uimanager.lua:1470: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013ebd
lipc-wait-event exited normally with status: 0
```

**Comment by mergen3107** [comment]
I suppose we need to ask those above -205 to update manually.
It worked for me by taking -213 and overriding the whole koreader folder on Kindle.

**Comment by mergen3107** [comment]
Reverting with `patch -p1 -R <12014.diff` works well as well.
https://github.com/koreader/koreader/pull/12014

**Comment by pazos** [comment]
Whops! Totally my fault, sorry :P 

Will fix now!

**Comment by mergen3107** [comment]
Thank! No worries :D glad to help!
