### ISSUE TITLE
Zotero koplugin help

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12116]
Hey guys,

I use this plugin every day, it works OK if you know all the quirks :D 
Thank you @stelzch for making this plugin!

If anyone is interested in Zotero and capable to help, could you please have a look at Zotero koplugin issues that I found?

It seems like the original author doesn't work on it actively in the recent days.

Kinda critical:
https://github.com/stelzch/zotero.koplugin/issues/7 (SOLVED)
https://github.com/stelzch/zotero.koplugin/issues/14 (SOLVED)
https://github.com/stelzch/zotero.koplugin/issues/15 (SOLVED)

Nice to have's:
https://github.com/stelzch/zotero.koplugin/issues/6
https://github.com/stelzch/zotero.koplugin/issues/8 (SOLVED)
https://github.com/stelzch/zotero.koplugin/issues/9 (SOLVED)

There are also other issues:
https://github.com/stelzch/zotero.koplugin/issues

Thanks!

**Comment by Frenzie** [comment]
I'm not interested in Zotero, but file_slurp() is an amusing function name.

**Comment by mergen3107** [comment]
Most of the OP issues are solved. Others are being solved actively looked at.
