### ISSUE TITLE
Kobo Nia unresponsive after suspend

### ISSUE THREAD

**Issue by noobyme** [koreader/koreader#12110]
* KOReader version:v2024.04
* Device:Kobo Nia

#### Issue
After the Nia suspends, there is no sleeping icon, and there is no way to turn it back on apart from hard reboot. At 12:58 I set suspend to 15 minutes, 20 minutes later I come back to reproduce it and it is not responsive. I have auto shutdown disabled but even if it was enabled it would have the same behavior. I turned verbose debugging on.

#### Steps to reproduce
Set suspend to 15 minutes, wait 20 minutes. 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
[crash.log](https://github.com/user-attachments/files/16022967/crash.log)


```
</details>

**Comment by noobyme** [comment]
Well it seems to be working correctly now. Unsure why

**Comment by NiLuJe** [comment]
The Nia is prone to unpredictable EPDC hangs we cannot account for nor workaround (unlike some of its brethren suffering from the same set of issues).

c.f., #10771 for more context, and #11511 for another device potentially affected, but to a lesser extent, where I posted a stupid experiment that no one ever gave me feedback on (at the very end of the thread) ;).

**Comment by noobyme** [comment]
Oh is that what it is? I have encountered the random crashes on stock non koreader firmware many many times. I didn't realise the two were the same thing as the koreader crashes were repeatable at least until it fixed itself. But koreader seems to have far fewer of these crashes so that's nice. Thanks for replying

**Comment by NiLuJe** [comment]
That would be my best guess given the device, yeah.

Note that I've also seen dying devices just plain crash on charging/suspend, too, but that's usually on older devices, or devices with a severely unhealthy battery.
