### ISSUE TITLE
"Folder up" gesture doesn't allways work.

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12125]
* KOReader version: 2024.04-209
* Device: PB 628

#### Issue
When the "Freeze last read date of finished books" option is enabled and we open and close a finished book we do not go to the folder that contains the book, as expected by this option. So, I tried to use the gesture I have assigned to "Folder up", when I had opened a finished book, so as to go the parent folder, even when the "Freeze last read date of finished books" option is enabled, but it didn't work; the gesture had no response. I don't know if this is a bug or maybe I haven't understood what exactly the "Folder up" command does.
Could there be the possibility of a gesture that takes us to the book folder, even when the book is finished and the "Freeze last read date of finished books" option is enabled?

Thanks!

**Comment by hius07** [comment]
On Folder up we go to the upper (parent) folder, that is `..`.
On closing a book, we go the folder containing the latest book in History.
Since the finished book date is frozen, it is **not** the latest book.

**Comment by ichnilatis-gr** [comment]
Yes, I understand this.
So, my bug report turns to a  feature request: Could there be a way, closing a finished book, to go to the folder that contains it, having the "Freeze last read date of finished books" option is enabled?

**Comment by hius07** [comment]
I think that makes sense: always exit to the book folder.

**Comment by Frenzie** [comment]
I think that would be more expected, yes.

**Comment by ichnilatis-gr** [comment]
I beg your pardon. Are you talking about an existing command or something else?

**Comment by Commodore64user** [comment]
I think they are agreeing with you

**Comment by ichnilatis-gr** [comment]
> I think they are agreeing with you

Thank you all!
