### ISSUE TITLE
Settings not saved when closing through task switcher on Android

### ISSUE THREAD

**Issue by shuvashish76** [koreader/koreader#12124]
* KOReader version: v2024.04 (102952)
* Device: Lenovo Tab4 8 plus

#### Issue

Night mode option doesn't work as intended for File browser, it's solely dependent on Reader's Night mode.

#### Steps to reproduce

1. Open KOReader i.e. view File browser
2. Change Night mode option
3. Close & reopen the KOReader > The previous change is not saved
4. Now if you open Reader & follow step 2,3 then after the restart File browser theme changes.

The easiest way to reproduce is: suppose I want to use _opposite_ theme for FM & Reader then with current implementation I can't do it.
Also
1. Open KOReader i.e. view File browser
2. Change Night mode option
3. Open any book to view Reader
4. Close & reopen the app > Now File browser theme shows correct theme

Conclusion : File Browser theme is dependent on Reader i.e. FM theme changes work if you atleast open the Reader or simply change theme from Reader...while both FM & Reader theme settings should be independent to each other.

**Comment by shuvashish76** [comment]
> Looks like the issue is device specific.

Tried on my 2nd android device & linux PC same issue exists. Yes looks like platform specific issue.

**Comment by hius07** [comment]
> Is it possible for you to set opposite theme for Reader & FM?

No, it's a common setting.

**Comment by NiLuJe** [comment]
> linux PC same issue exists.

How? (i.e., what did you test, exactly. An AppImage?)

I've just double-checked the emu, and it behaves just fine.

There's only a single codepath for both the menu and the event handling for that, so I can't quite think how something could go wrong there :s.

**Comment by NiLuJe** [comment]
... unless Android lifecycle issues strike again, and an exit from the FM fails to actually flush the settings properly.

But that doesn't explain your plain Linux experience.

**Comment by Frenzie** [comment]
I think the issue in the OP is merely the expectation that night mode would somehow be independent.

**Comment by shuvashish76** [comment]
I'm using [AUR](https://aur.archlinux.org/packages/koreader-bin) package. Sorry for the wrong info, just double checked it works as expected.
The issue is on android only.

**Comment by shuvashish76** [comment]
> I think the issue in the OP is merely the expectation that night mode would somehow be independent.
> And, yes, there's only one single setting for all the different views.

Ok got it thanks, issue title changed.

**Comment by Frenzie** [comment]
I can confirm that the night mode setting (and presumably any others as well) aren't saved if I force close it by swiping up on the running app selection screen. I'm not sure otoh if that's something with a possible resolution. For the moment you can use the hamburger menu → exit to be sure that it's saved as a workaround.

**Comment by pazos** [comment]
> I can confirm that the night mode setting (and presumably any others as well) aren't saved if I force close it by swiping up on the running app selection screen. I'm not sure otoh if that's something with a possible resolution. For the moment you can use the hamburger menu → exit to be sure that it's saved as a workaround.

At some point it was handled by https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L152-L153.

I have no idea if something changed and no interest in lurking. But it would be nice to know if that code path is reached on a faulty device (by inserting a print statement) when the app is killed via the task switcher.

**Comment by NiLuJe** [comment]
> I have no idea if something changed and no interest in lurking

I can see one obvious problem: only ReaderUI has a handler for that one, not FileManager ;o).

**Comment by shuvashish76** [comment]
> I can confirm that the night mode setting (and presumably any others as well) aren't saved if I force close it by swiping up on the running app selection screen.

Yes but for e.g  "Display Mode" not affected by this. Not sure how that implemented _differently_ from other settings.

**Comment by Frenzie** [comment]
> I have no idea if something changed and no interest in lurking. But it would be nice to know if that code path is reached on a faulty device (by inserting a print statement) when the app is killed via the task switcher.

Not a faulty device. Note the emphasis on file browser in the OP. Unless OP is saying it also happens in the reader; then it's a faulty device.

> Yes but for e.g "Display Mode" not affected by this. Not sure how that implemented differently from other settings.

Quite differently; CoverBrowser works with SQLite. It could still get interrupted.
