### ISSUE TITLE
FR: Make selection (underline focus) visible on NT [great again]

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#12132]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently in the FM on NT there is a subtle underline that indicates where the focus is, this can be hard to spot under some circumstances, in fact, let's play a game, in pictures A and B below, find where the underline currently is (it is there I promise)

<img src="https://github.com/koreader/koreader/assets/97603719/380689b8-b7d4-4cf5-a6fb-cb6db25bf391" width=40% height=40%>
<img src="https://github.com/koreader/koreader/assets/97603719/04581327-75f6-41fe-91d5-30f9e7548645" width=40% height=40%>

**Describe the solution you'd like**
We could have a thicker underline or a box that completely surrounds the focused file, or a temporary inversion (why not?)

**Comment by Commodore64user** [comment]
any suggestions to give this some oomph
https://github.com/koreader/koreader/blob/7b9c65ee1ed43020473dbcaf321ea85bee34eef5/plugins/coverbrowser.koplugin/mosaicmenu.lua#L412-L422

**Comment by Frenzie** [comment]
Did you try simply commenting out linesize?

**Comment by Commodore64user** [comment]
<img src="https://github.com/user-attachments/assets/7fff323e-c6af-4482-a4e3-22dfe36c52cd" width=40% height=40%>
<img src="https://github.com/user-attachments/assets/85bc12f9-f3b6-4d84-9456-73899b55d0d3" width=40% height=40%>

this is `self.underline_h` = `2` and `3` respectively and `padding = 1`. I like three but it slightly decreases the size of thumbnails, thoughts

**Comment by poire-z** [comment]
> (I mention this as there is this comment -- smaller than default (3), don't waste space), thoughts

I think it is a nicely written and thoughtful comment :)

**Comment by Commodore64user** [comment]
@poire-z  would this be acceptable?

```lua
if Device:isTouchDevice() then
    self.underline_h = 1 -- smaller than default (3), don't waste space
else
    self.underline_h = 5
end
self._underline_container = UnderlineContainer:new{
    vertical_align = "top",
    padding = 1,
blah blah 
```

**Comment by Commodore64user** [comment]
FWIW, it really doesn't make much of a difference (thumbnail size) on older lower resolution screens (800x600px), you can only notice it comparing the two images side by side

**Comment by poire-z** [comment]
Try this:
```diff
--- a/plugins/coverbrowser.koplugin/mosaicmenu.lua
+++ b/plugins/coverbrowser.koplugin/mosaicmenu.lua
@@ -422,6 +422,12 @@ function MosaicMenuItem:init()
     }
     self[1] = self._underline_container

+    if true then -- replace that with your conditions
+        -- Make it bigger on XYZ devices, without affecting our sizing
+        -- we'll keep doing with that small self.underline_h
+        self._underline_container.linesize = 5
+    end
+
     -- Remaining part of initialization is done in update(), because we may
     -- have to do it more than once if item not found in db
     self:update()
```

Not sure what are the best Device:isSomething conditions.

**Comment by Commodore64user** [comment]
Would it okay (NT ONLY), to _always_ show the focus indicator as opposed to only after one presses a cursor key?

**Comment by poire-z** [comment]
I guess so (no idea how this delay is implemented).
