### ISSUE TITLE
Question: zsync OTA and versioned libraries

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#12136]
Just wondering what happens with OTA updates when a device has a shared library that got bumped in its version scheme.

For instance `libleptonica.so.4` -> `libleptonica.so.6`

Does zsync takes care of removing the old, no longer present files?

**Comment by Frenzie** [comment]
No, those harmlessly remain behind.

**Comment by pazos** [comment]
So, no worries dlopening the wrong version?

**Comment by Frenzie** [comment]
No, https://github.com/koreader/koreader-base/blob/852f54eb3961068821c2e62a2eba4375f24c8526/ffi/koptcontext.lua#L76-L85

**Comment by Frenzie** [comment]
Or even more explicitly: https://github.com/koreader/koreader-base/commit/be04eb049dae438cf3347a52de7828fbb181123f#diff-b11a3dc5756b61ebcd1e9390445dd285a217db978ab27b36ab1fdea14afabb29

**Comment by Frenzie** [comment]
I don't find the idea of removing files attractive, but I suppose extremely targeted examples could be considered. But there seems to be a suggestion there that this is something that happens sufficiently frequently to worry about as opposed to effectively never.

**Comment by NiLuJe** [comment]
The only potentially problematic issue I could think of would be something with essentially broken DT_NEEDED entries pointing to old stuff, and that seems extremely far fetched (especially since the buildsystem cleanups), as it would probably mean poisoning of the build environment, which is... unlikely (cross-compliation, containers, etc.) ^^.

**Comment by pazos** [comment]
Thank you all for the feedback!

Nothing to change, great!

>  But I would suggest for future updates, that the outdated leftovers get removed maybe with a onetime_migration.

I agree on *clean after update*, but that can be implemented safely in the future.
We just need to generate a list of libraries at build time and prune what's not there after each update.

**Comment by benoit-pierre** [comment]
There's already `ota/package.index` that could be used for this.
