### ISSUE TITLE
Crash when cbz file contains a "__MACOSX" directory

### ISSUE THREAD

**Issue by FoxP** [koreader/koreader#12142]
* KOReader version: [KOReader 2024.04 "Sourdough"](https://github.com/koreader/koreader/releases/tag/v2024.04)
* Device: Vivlio Inkpad 3

#### Issue

Crash.

#### Steps to reproduce

Open [provided .cbz file](https://github.com/user-attachments/files/16115713/Les.Carnets.de.l.apothicaire.T0.-.Natsu.Hyuga.zip) (trimmed down to only keep last page, for copyright / legal issues), and go to last page. 
The KOReader app crashes.
The .cbz file contains a "__MACOSX" directory, it (may ?) explain the crash (?).

![image](https://github.com/koreader/koreader/assets/16615901/9b3b9221-d0da-4acb-831a-7cb999c8e35c)

**Comment by benoit-pierre** [comment]
I can reproduce with the 2024.04 AppImage, but not with master (~33ae788575).

**Comment by FoxP** [comment]
Thanks for the test !
So I guess next stable release ([2024.07](https://github.com/koreader/koreader/milestone/73)) should fix the issue. :thumbsup:
