### ISSUE TITLE
Corner action activation zone adjustment

### ISSUE THREAD

**Issue by polo2137** [koreader/koreader#12152]
Very often when trying to highlight text near to the corner of the device I accidentally activate whatever action that is assigned to it. Mentioned issue makes highlighting at the very corner impossible.

A simple solution would be to include a simple setting for the corner action activation range located in Taps and gestures menu. Another really neat enhancement is adding basic visualisation of the corners action activation range in the form of quarters of circles getting larger or smaller accordingly to chosen setting value.

**Comment by jonnyl2** [comment]
You can change the corner tap/long-press area in the Advanced Settings. Open File browser, then Top menu, Tools, More tools -> Advanced settings. The settings are `DTAP_ZONE_BOTTOM_LEFT` `DTAP_ZONE_BOTTOM_RIGHT` `DTAP_ZONE_TOP_LEFT` `DTAP_ZONE_TOP_RIGHT`.

There is also the option to assign a gesture to toggle long-press actions in corners. You can use that to temporarily disable long-press corner actions while you do your highlights/ dictionary look-ups.

**Comment by polo2137** [comment]
Oh perfect! Still I think that a clear and easy to use GUI would be great!

**Comment by polo2137** [comment]
[Unplugged > Start USB storage > plugged > eject.txt](https://github.com/user-attachments/files/16150315/Unplugged.Start.USB.storage.plugged.eject.txt)
[Unplugged > Plugged but with bug "waiting to be plugged in" > unplug > plug again > USB session > eject.txt](https://github.com/user-attachments/files/16150317/Unplugged.Plugged.but.error.waiting.to.be.plugged.in.unplug.plug.again.USB.session.eject.txt)
[Plugged > Start USB storage.txt](https://github.com/user-attachments/files/16150318/Plugged.Start.USB.storage.txt)

**Comment by jonnyl2** [comment]
Most users probably don't have a need to adjust the corner tap zones. And if they do, they generally only do it once. And changing them requires a restart of KOReader. For all these reasons I think it makes sense to keep these settings buried where they don't take up additional menu space. (Referencing them in the User Guide might be something to consider, though.)
