### ISSUE TITLE
Extremely slow highlighting when crossing to another page

### ISSUE THREAD

**Issue by polo2137** [koreader/koreader#12156]
* KOReader version: 202404000226
* Device: Kobo Libra 2
* Book format: epub

#### When highlighting text that exceeds its page, loading another section takes extremely long.
When pokeball icon appears in the top left corner highlighting will never cross to another section making it very frustrating to delete the whole highlight and then try again and again.

Steps to reproduce:
1. make a lot of highlights (762 in my case) using various styles in one book that is fairly long (1600 pages in my case);
2. try to highlight some text at the bottom of the screen so that koreader moves you to next section of text;
3. wait very long or forever if the pokeball icon appears in the top left corner;
4. enjoy the bug.

https://github.com/user-attachments/assets/5d8eddd9-ea8c-4c97-9f35-f6c23ca213d9

##### [logread.txt](https://github.com/user-attachments/files/16182834/logread.txt)

**Comment by hius07** [comment]
Why don't you use the Select button for multi-page highlights?

**Comment by polo2137** [comment]
> Why don't you use the Select button for multi-page highlights?

Because I use corner tap and long press to switch between highlight and ask with popup dialog when selecting text. This way I don't need to perform another action when I know a certain book will need a lot of highlights.

**Comment by poire-z** [comment]
Can't really reproduce (notice the slowness) on the emulator.
I also can't get the pokeball to show up when trying to do what you did (and neither did you on your video?).

Can you check how it does when the alt/top status bar is disabled ? It's possible some cached stuff gets reset when switching from page mode with top status bar to scroll mode without the top status bar, so some expensive recomputation of all highlights is happening.
If it's better, you can try re-enabling the top status bar, and add one line to the code:
```diff
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -1813,6 +1813,7 @@ function CreDocument:setupCallCache()
             -- Assume all set* may change rendering
             if name == "setBatteryState" then no_wrap = true -- except this one
             elseif name == "setPageInfoOverride" then no_wrap = true -- and this one
+            elseif name == "setViewMode" then no_wrap = true
             elseif name:sub(1,3) == "set" then add_reset = true
             elseif name:sub(1,6) == "toggle" then add_reset = true
             elseif name:sub(1,6) == "update" then add_reset = true
```
I'm not sure this is without side effects, but if it makes things better, it will be something to investigate more thoroughly.

**Comment by polo2137** [comment]
@poire-z Thats not it :/ Alt status bar disabled or enabled its all the same. I cleared caches with no luck, bug is still here. Changing font also doesn't work.

**Comment by poire-z** [comment]
Can you still try the one line patch?

**Comment by polo2137** [comment]
> Can you still try the one line patch?

Now it works great! Thanks so much!

**Comment by poire-z** [comment]
Oh, good.
Well, loooking at the code, it seems that should be fine, I can't foresee any side effect.
Please live with that one line added for some time, and see if you notice strange things (ie. highlights badly drawn or not drawn, following links or jumping not landing on the right page...) when/after you switch between page/continuous or when switching between two-columns off/on, stuff like that. And tell us in a week.

Also, still seeing that pokeball, or is that solved too?

**Comment by polo2137** [comment]
> Also, still seeing that pokeball, or is that solved too?

It is solved too!

**Comment by polo2137** [comment]
@poire-z After a week of testing all scenarios you enumerated I confirm all works as expected and the code can be updated.
