### ISSUE TITLE
Keypad Left/Right navigating chapters, not pages?

### ISSUE THREAD

**Issue by Darthagnon** [koreader/koreader#12168]
* KOReader version: 2024.07
* Device: Kindle 4

#### Issue
I read the release notes and PR comments, and it sounds like the Kindle 4 keypad, which I use all the time while reading one-handed, is being repurposed to navigate chapters rather than pages? Is this true, and can this behaviour be reverted? I can see it's useful, but I navigate pages with left/right. Wouldn't mind remapping up/down to navigate chapters, or holding center button as a shift modifier and pressing left/right to navigate chapters, but I'm holding off on updating KOReader for the moment, as this will break it for me.

#### Steps to reproduce
https://github.com/koreader/koreader/pull/11749#issuecomment-2229527541

**Comment by mergen3107** [comment]
@Commodore64user

**Comment by Commodore64user** [comment]
Thank you for the introduction @mergen3107 

> Is this true

Yes it is.

> can this behaviour be reverted?

Not really. What we can do is offer you different options. What I would say first of all, is, why don't you install the update, try it, and then decide weather you like the changes. There are a lot of improvements there, a lot.

**option 1:** invert one set of page turn buttons #11963.

**option 2:** update and then locally override the following functions found here (`koreader > frontend > apps > reader > modules > readerrolling) https://github.com/koreader/koreader/blob/7b9c65ee1ed43020473dbcaf321ea85bee34eef5/frontend/apps/reader/modules/readerrolling.lua#L118-L241 with this: 

<details>
  <summary>ReaderRolling</summary>
  
  ```lua
function ReaderRolling:registerKeyEvents()
    if Device:hasKeys() then
        self.key_events.GotoNextView = {
            { { "RPgFwd", "LPgFwd", "Right" } },
            event = "GotoViewRel",
            args = 1,
        }
        self.key_events.GotoPrevView = {
            { { "RPgBack", "LPgBack", "Left" } },
            event = "GotoViewRel",
            args = -1,
        }
    end
    if Device:hasScreenKB() then
        self.key_events.MoveUp = {
            { "ScreenKB", "RPgBack" },
            event = "Panning",
            args = {0, -1},
        }
        self.key_events.MoveDown = {
            { "ScreenKB", "RPgFwd" },
            event = "Panning",
            args = {0,  1},
        }
    end
end
  ```

</details>

this one too: https://github.com/koreader/koreader/blob/7b9c65ee1ed43020473dbcaf321ea85bee34eef5/frontend/apps/reader/modules/readerpaging.lua#L53-L149

<details>
  <summary>ReaderPaging</summary>
  
  ```lua
function ReaderPaging:registerKeyEvents()
    if Device:hasDPad() and Device:useDPadAsActionKeys() then
        self.key_events.GotoNextPos = {
            { { "RPgFwd", "LPgFwd", "Right" } },
            event = "GotoPosRel",
            args = 1,
        }
        self.key_events.GotoPrevPos = {
            { { "RPgBack", "LPgBack", "Left" } },
            event = "GotoPosRel",
            args = -1,
        }
    end
end
  ```

</details>

**option 3:** the above solution will not survive future software updates so, install an user patch with those changes. If you squint your eyes and stare at the sunset, a kind soul might read this and help you there.

**Comment by Darthagnon** [comment]
This is how I very often read my Kindle:
![IMG_1352](https://github.com/user-attachments/assets/06bbad9c-ab4e-43cd-b202-9527f7328107)

**Comment by poire-z** [comment]
> This is how I very often read my Kindle:

That's how I would use it too if I had such a device. And I think this is how I turned pages on my first device, a Sony PRX-505, which had a DPAD on the bottom right.
(I think we may have discussed that with @Commodore64user, his choices didn't feel obvious to me, and I thought people could be bothered by the change.)

**Comment by Frenzie** [comment]
Luckily you can easily user patch `Device:useDPadAsActionKeys()` as `return false` (and that's very much by my design ;-).

Something as simple as this will probably do the trick.
```lua
local Device = require("device")
Device.useDPadAsActionKeys = function() return false end
```

**Comment by Commodore64user** [comment]
> Luckily you can easily user patch `Device:useDPadAsActionKeys()` as `return false` (and that's very much by my design ;-).
> 
> 
> 
> Something as simple as this will probably do the trick.

That will do more harm than good, sadly. Up/down are prev/next page, left/right do nothing and no text selection at all. 

Best thing is to override the functions.

**Comment by Frenzie** [comment]
If left/right don't do anything anymore in the else condition doesn't that mean it was removed when it shouldn't have been?

**Comment by Commodore64user** [comment]
> If left/right don't do anything anymore in the else condition doesn't that mean it was removed when it probably shouldn't have been?

The problem is, it was originally thought out as `hasFiveWay` and not reorganised when the `useDPadAsActionKeys` was added.

**Comment by Commodore64user** [comment]
Here’s what we can do, @Darthagnon update (if you want) and temporarily overwrite the functions as mention in https://github.com/koreader/koreader/issues/12168#issuecomment-2229723529 

in the meantime, will look into fixing the function so we can do the `useDPap` patch

**Comment by Frenzie** [comment]
> That will do more harm than good, sadly. Up/down are prev/next page, left/right do nothing and ~no text selection at all~ text selection back to the top menu

Your comment seems to be incorrect.

**Comment by Commodore64user** [comment]
how so?

**Comment by Frenzie** [comment]
Just me probably.

**Comment by Darthagnon** [comment]
Changelog for 2024.11 release lists this issue as fixed. I will test it soon. Thank you very much!
