### ISSUE TITLE
New build has wrong version number

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12173]
* KOReader version: 2024.04-229 (yep, see details :D)
* Device: emulator

#### Issue and Steps to reproduce
I rebuilt and ran KOReader today with:
```
git pull upstream master
git merge upstream/master
git submodule update --recursive
git push origin
./kodev clean
make fetchthirdparty
./kodev run
```
What I got in the end is a working KOReader, but it has version `2024.04-229`, instead of `2024.07-1`.
What am I doing wrong here? :D

**Comment by benoit-pierre** [comment]
Did you fetch the tags? `git fetch --tags`

**Comment by mergen3107** [comment]
Lol, no I didn't :D (and never did actually, now I added it to the list above).

Thanks!
