### ISSUE TITLE
Bookmarks still named Bookmarks, not Annotations, after the latest update

### ISSUE THREAD

**Issue by AryaTwirl** [koreader/koreader#12170]
* KOReader version: 2024.07
* Device: Kobo Libra 2, Samsung S24

#### Issue
Bookmarks hasn't changed to Annotations as described in the release note

#### Steps to reproduce
Open top menu, select the first menu, see Bookmarks

**Comment by Frenzie** [comment]
Apologies, there was some confusion there on my end. :blush: But I already removed it some 3-4 hours ago. ;-)

**Comment by Frenzie** [comment]
Apparently I was distracted by something else and never pressed save. Done now.
