### ISSUE TITLE
[Kobo][Night mode] Extra vertical line at the right side

### ISSUE THREAD

**Issue by xsown** [koreader/koreader#12182]
* KOReader version: Kobo 2024.07 (202407000000 from the stable channel)
* Device: Kobo Clara Colour

#### Issue
When in night mode, there is a vertical white line at the right side of every page. Seems it is at the last horizontal pixel. (width - 1, 0) to (width - 1, height - 1)
If this is intended and there is an option to switch it off, please correct me and let me know where the option is, thank you!

#### Steps to reproduce
1) Launch KOReader from nickel menu on Kobo Clara Colour.
2) Open the night mode, the problem is always there.

##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/16328279/crash.log)

#### Screenshots

![IMG_2161](https://github.com/user-attachments/assets/b8cd29d7-038f-4a50-bb61-cf8aa970c8c6)

**Comment by Frenzie** [comment]
It doesn't have a viewport defined, so it seems unlikely that we can do anything about it. If you check in tools → more tools → developer options there might be an option to toggle between hardware and software. (I don't have a device at hand right now.)

https://github.com/koreader/koreader/blob/5342b8cc2a5493c0a956c3e298c427c28b3b45f3/frontend/device/kobo/device.lua#L578-L598

A quick way to verify the behavior is to enable night mode in Nickel. I think NickelMenu might have an option for it, or developer options.

**Comment by mergen3107** [comment]
This simply looks like physical pixel border. The screen tolerance just made only right-hand side line visible, but I am pretty sure there are all four such lines around the screen.

**Comment by mergen3107** [comment]
Also, why did you ifnore the issue template?

Where is the log?

Log will tell you whether it draws the whole viewport.

**Comment by xsown** [comment]
> It doesn't have a viewport defined, so it seems unlikely that we can do anything about it. If you check in tools → more tools → developer options there might be an option to toggle between hardware and software. (I don't have a device at hand right now.)
> 
> https://github.com/koreader/koreader/blob/5342b8cc2a5493c0a956c3e298c427c28b3b45f3/frontend/device/kobo/device.lua#L578-L598
> 
> A quick way to verify the behavior is to enable night mode in Nickel. I think NickelMenu might have an option for it, or developer options.

Thanks for reply. I haven't found an option like hardware/software rendering mode toggles. There is a "Disable HW dithering" in developer options, but there wasn't any visible difference by switching. 
I'm new to NickelMenu and will find how to trigger a global night mode from it.

**Comment by xsown** [comment]
> This simply looks like physical pixel border. The screen tolerance just made only right-hand side line visible, but I am pretty sure there are all four such lines around the screen.

Unfortunately, only a vertical line at the right side. If the lines appear at all four sides, I wouldn't bother sending a bug request here (try to persuade my brain that's a decorating feature 😂).

**Comment by xsown** [comment]
> Also, why did you ifnore the issue template?
> 
> Where is the log?
> 
> Log will tell you whether it draws the whole viewport.

Thought the "crash.log" only refers to crashes. Now attached file into the crash.log section. Only find lines related with the viewport:

07/22/24-13:20:54 DEBUG _refresh: Enqueued ui update for region 0 0 1072 1448 dithering: true 
07/22/24-13:20:54 DEBUG _refresh: Enqueued ui update for region 0 0 1072 1448 dithering: true 
07/22/24-13:20:54 DEBUG refresh: ui-mode 0 0 1072 1448 true 
07/22/24-13:20:54 DEBUG mxc_update: 1072x1448 region @ (0, 0) with marker 5 (WFM: 257 & UPD: 0) 

Further actions needed?

**Comment by NiLuJe** [comment]
> This simply looks like physical pixel border. The screen tolerance just made only right-hand side line visible, but I am pretty sure there are all four such lines around the screen.

This.

**Comment by NiLuJe** [comment]
Just enable dark mode in Nickel, it's readily available in the UI on those devices, you should see the exact same behavior.

As @mergen3107 said, it's possibly device-specific to some extant (tolerances), because we *have* seen NTX shove the panel further away behind the bezel when they add specific massive tolerance issues ;).

**Comment by NiLuJe** [comment]
Enabling a viewport won't help you, because we can't magic up a new pixel column out of nowhere ;).

**Comment by Frenzie** [comment]
> it's readily available in the UI on those devices

Oh right, it's available out of the box on the newer ones. I forgot. :-)

**Comment by NiLuJe** [comment]
What you *can* try, though, on the off-chance the issue is exacerbated by an alignment mishap in the MDP, is to disable HW inversion:

https://gist.github.com/NiLuJe/4be737eb123cf1199590b626be131345

**Comment by xsown** [comment]
> What you _can_ try, though, on the off-chance the issue is exacerbated by an alignment mishap in the MDP, is to disable HW inversion:
> 
> https://gist.github.com/NiLuJe/4be737eb123cf1199590b626be131345

Your patch works! You are awesome!!!

For the dark mode built in the stock firmware, I've been using it every night and it doesn't have any problem:

![IMG_2176](https://github.com/user-attachments/assets/138cde31-06f5-4a22-947b-81de74bdfa6a)

**Comment by benoit-pierre** [comment]
That `I' m` spacing really does not look right. O.o

**Comment by NiLuJe** [comment]
> That I' m spacing really does not look right. O.o

Double-wide apostrophe because CJK, perhaps? Or weird-ass formatting in the actual source?

----

FWIW, not reproducible on a Libra Colour, but I have seen weird-ass MDP crap happening, hence the hunch.

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/wiki/User-patches#device-specific for links to the "disable HW inversion" patch.

**Comment by xsown** [comment]
> That `I' m` spacing really does not look right. O.o

It's misplaced by the (MS Bing) translation process to the bilingual document. The original document is innocent. 😳
