### ISSUE TITLE
The issue of text overlap may occur on line 33 of the paragraph.

### ISSUE THREAD

**Issue by x-kalinu** [koreader/koreader#12183]
*KOReader version: v2024.07
*Device: KindlePaperWhite4
*Test file: "(NEW)第二性：合卷本 = Le Deuxième Sexe（简体台版译本） (西蒙‧德‧波娃 (Simone de Beauvoir) 著；邱瑞鑾 譯) (Z-Library).epub"

In open Simplified Chinese books, regardless of the typography style, there is a high probability of text overlap occurring on line 33 of the paragraph, as shown in the following image

![Reader_2024-07-19_172920](https://github.com/user-attachments/assets/488acc6c-3d88-4dff-8a22-24852f8b05bd)

![Reader_2024-07-19_173025](https://github.com/user-attachments/assets/323a394a-79b9-44d7-83d2-cbe1a75c2284)

![Reader_2024-07-19_171616](https://github.com/user-attachments/assets/58c8c5fc-7863-4666-b978-7b013e34397f)

**Comment by Frenzie** [comment]
Could you share the document after running it through ScrambleEbook?
https://www.mobileread.com/forums/showthread.php?t=267998

Maybe it's simply something about the markup.

Incidentally, I'm not immediately seeing anything on the first two screenshots?

**Comment by x-kalinu** [comment]
> Could you share the document after running it through ScrambleEbook? https://www.mobileread.com/forums/showthread.php?t=267998
> 
> Maybe it's simply something about the markup.
> 
> Incidentally, I'm not immediately seeing anything on
 the first two screenshots?

Sincerely appreciate your response and so sorry for the delay in responding to you. What a pity it is that I haven't created a ScrambleEbook accout! But the compressed file of the document has been attached to this reply.

[(NEW)第二性：合卷本 = Le Deuxième Sexe（简体台版译本） (西蒙‧德‧波娃 (Simone de Beauvoir) 著；邱瑞鑾 譯) (Z-Library).zip](https://github.com/user-attachments/files/16312750/NEW.Le.Deuxieme.Sexe.Simone.de.Beauvoir.Z-Library.zip)

The markup is also invalid at the overlap of text.

Yes,  the first two screenshots are only used to illustrate that the problem arises exactly on the next line of LINE 32. I suppose that the number 32 might have to do with it.

**Comment by x-kalinu** [comment]
> Could you share the document after running it through ScrambleEbook? https://www.mobileread.com/forums/showthread.php?t=267998
> 
> Maybe it's simply something about the markup.
> 
> Incidentally, I'm not immediately seeing anything on the first two screenshots?

So sorry again for my misunderstanding! I couldn't understand the meaning of ScrambleEbook just now(Actually, I have regarded it as an online data strorage like Onedrive!). Now the compressed file of the scrambled document is here:

[(NEW)Di Er Xing _He Juan Ben  = - Wei Zhi_scrambled.zip](https://github.com/user-attachments/files/16313338/NEW.Di.Er.Xing._He.Juan.Ben.-.Wei.Zhi_scrambled.zip)

**Comment by mergen3107** [comment]
@x-kalinu 
Did you try different kerning methods? They are in the bottom menu (third tab IIRC).

Also, sis you try with different fonts?

**Comment by mergen3107** [comment]
To check the tags:
Highlight text that contains portions that overlap. Hit “View HTML” button. Take a photo and paste it here please

**Comment by poire-z** [comment]
Thanks to this misunderstanding, I got the original EPUB :) (Would be harder to debug a scrambled/obfuscated EPUB).

I dont' see any HTML markup in this long paragraph: it's some long string of chars, so may be some overflow or hicups in the code when iterating chars in a single text node. The indices in the text node for the highlights I'm showing below are:
`/body/DocFragment[11]/body/p[7]/text().776 to 812, and 1576 to 1590`.
Way lower than our paragraph working buffer size of 8192.

I don't get the issue on my side when trying to get the same rendering (char per page) as the user - but I can then see the amount of chars that get squeezed into that 
![image](https://github.com/user-attachments/assets/6e118fd1-8654-4be0-bf55-b1d67e58ce67)

But with my original settings, I got a similar kind of issue:
![image](https://github.com/user-attachments/assets/60a0ee1d-3cb1-4839-af80-ef1ddf69936b)

This happens with Kerning `best`, but not with `good`. Same for you with the bug you've shown?

![image](https://github.com/user-attachments/assets/e3bd7ddd-664e-4d16-99e1-692a16da490e)

![image](https://github.com/user-attachments/assets/41f95e61-7417-40df-961f-5dbf9a5f8320)

How oftent - once every N pages? - have you witnessed that in that book / all books ? Only since v2024.07 ? Nothing similer ever seen with v2024.04 ?

**Comment by Frenzie** [comment]
> How oftent - once every N pages?

I can reproduce as well, but I can't really spot a pattern.

**Comment by poire-z** [comment]
Anyway, @x-kalinu , before trying changing any setting, make a backup of your book's blahblah.sdr/metadata.epub.lua. As it is hard to reproduce, we don't want to lose one test situation.
We will need you to restore it, confirm you see again the issue, before you try other suggestions to confirm if they solve your issue or not.

**Comment by poire-z** [comment]
It seems this may happen on bits of text having ASCII spaces or parens, AND when not using NotoSansCJK as the main font: it may be the Harfbuzz measurement code that measure "runs" of text with the main font, and when a sequence of CJK chars are found not supported by the main font, it switches to the fallback font, and then stop to get back to the main font on a space or parenthesis. Something may get messed up in there :(

@x-kalinu : can you tell which font you have set as your main font (I assume it is not a Chinese font) ?
And try selecting NotoSansCJKsc as the main font: do things get better?

**Comment by x-kalinu** [comment]
> Anyway, @x-kalinu , before trying changing any setting, make a backup of your book's blahblah.sdr/metadata.epub.lua. As it is hard to reproduce, we don't want to lose one test situation. We will need you to restore it, confirm you see again the issue, before you try other suggestions to confirm if they solve your issue or not.

@poire-z 
OK, the original file is here: 
[metadata.epub.zip](https://github.com/user-attachments/files/16318074/metadata.epub.zip)

I used NotoSerif as the main font, which could be found in the file.Things do get better after selecting NotoSansCJKsc!

**Comment by x-kalinu** [comment]
> Thanks to this misunderstanding, I got the original EPUB :) (Would be harder to debug a scrambled/obfuscated EPUB).
> 
> This happens with Kerning , but not with . Same for you with the bug you've shown?`best``good`
> 
> How oftent - once every N pages? - have you witnessed that in that book / all books ? Only since v2024.07 ? Nothing similer ever seen with v2024.04 ?
> 
> I can't read Chinese: anything similar in the 2 différent places highlighted that are affected by the issue?

@poire-z 

What a misunderstanding! :)

Things get better when I choose "good" and it comes back after selecting "best".

It seems a random event! At first, I found it in some paragraghs in some books. Then I try to correct the EPUB through Calibre but it made no sense. After counting lines, I found that the bug appear on the 33rd line though not each 33rd line of a book goes wrong. I think I may find that nothing goes wrong in books that have no paragraghs with more than 33 lines. The same can be seen with v2024.04, for which I upgraded to v2024.07, but only to find the same. >_<

I couldn't find anything else similar in the 2 différent places highlighted that are affected by the issue. What is so strange is that the 2 places you highlighted aren't affected on my device.How confusing!

**Comment by poire-z** [comment]
Thanks.
I found out the reason: when rendering (actually measuring the width of each char) a paragraph, we switch as needed between the main fonts (NotoSerif, only able to render space and `()`) and a fallback font (NotoSansCJKsc, able to render chinese).
We also stop measuring when we reach a width of what has been measured of 32767 pixels (we'll continue measuring the rest in another loop).
And when we are using a fallback font when we reach these 32767 pixels width, we don't stop properly - so bits of what's after these 32767 gets measured, but improperly, with crappy results (possibly negative widths, so the kind of next chars going back and overlapping previous chars: what we witness).

That's the reasons why:
- it depends on the font size : the larger the font, the sooner we'll reach 32767px (this is why each of us doesn't see the issue at the same location - and you usually on line 33 :))
- it needs very long paragraphs (we don't often meet paragraphs with runs of text larger than 32767px, so thanks to these pretentious French writers like Simone de Beauvoir).
- it needs to be using a fallback font - so it could probably only be witnessed by user of non-western languages who has not added their own preferred font, and keep our default western font (Noto Serif) as the main font.
- it happens only with `Kerning mode: best`, which is our default, and the most complex mode
- and yes, that bug has been present for a long time, I can reproduce it with v2024.01

Need to think about a not too ugly fix, should be solved in a nightly build in a few days.

**Comment by x-kalinu** [comment]
@poire-z Thanks for your great help! It truly helped me a lot! It is your zeal on this program that does impress me!
Once again, I sincerely thank everyone having done me a favor! @Frenzie @mergen3107 @poire-z :D

**Comment by poire-z** [comment]
Thanks.
Let's keep this issue open until the fix lands into this repository.
