### ISSUE TITLE
Joplin Export Issues

### ISSUE THREAD

**Issue by widdywalk1940** [koreader/koreader#12180]
* KOReader version: 202407000000
* Device: Kobo Libra 2

#### Issue: Joplin Export Failed
When I try to export my notes to Joplin, it says that it failed to export.  It can create a notebook, but there are no notes.

I could export my notes to Joplin just fine before I had an issue ( #12163 ) with corrupted files.  Before the issues, I set up Joplin and KOReader according to the instructions.  I tried uninstalling and reinstalling Joplin, but it didn't work.

[crash.log](https://github.com/user-attachments/files/16301688/crash.log)

**Comment by pazos** [comment]
Fixed in #12446
