### ISSUE TITLE
FR: popup dialog notification after toggle accelerometer action gesture

### ISSUE THREAD

**Issue by polo2137** [koreader/koreader#12199]
Recently I'm using the long press on top left corner for toggling accelerometer when I know that the only orientation I'll use is the current one in order to avoid accidental screen rotation.
The problem is the lack of a popup dialog message after using aforementioned action. Only solution to make sure the gesture had been executed successfully is rotating the device hence making the whole experience a little frustrating.

A very simple fix would be adding popup dialog notification informing user about successful action, as it is currently with e.g. "Default highlight action changed to 'highlight'."

**Comment by mergen3107** [comment]
As a temporary workaround, make this gesture show up as a Quick Menu.

When you trigger it, you will a window with that action, and when you press it you will know it activated.

**Comment by hius07** [comment]
It should show
https://github.com/koreader/koreader/blob/ad1286fbcc672516f24e38f24f121133f6fef390/frontend/device/devicelistener.lua#L199-L204
Look at your notificartions settings under the Cog - Screen menu.

**Comment by polo2137** [comment]
I confirm after turning on all notifications it now works. The weird thing is if all notification were off why highlight notification have been appearing?

**Comment by NiLuJe** [comment]
You'll have to be more specific about which notification you're actually talking about ;).

The classification system is (relatively) new, so there's a fair number of codepaths were thing just display a notification (or even something that *looks* like a notification, but might not even be using the notification widget), no matter what.
