### ISSUE TITLE
Use reference page numbers in markdown export

### ISSUE THREAD

**Issue by edo-jan** [koreader/koreader#12209]
I am using the "reference page numbers" feature +  "logical page count" user patch to harmonize page numbers across devices with different font sizes / screen resolutions. 
The issue arises when I export annotations to .md format (for subsequent processing in Obsidian). The exported page numbers are different from the "referenced" ones.

**Describe the solution you'd like**
When the "Use reference page numbers" is selected, the export process must use these numbers.

**Comment by benoit-pierre** [comment]
Related: #12153.

**Comment by hius07** [comment]
Can you point me to a public domain book with good reference pages, for testing?

**Comment by edo-jan** [comment]
> Can you point me to a public domain book with good reference pages, for testing?

 I am **not** using any of the supported sources of page map/list such as:

- EPUB3 <nav epub:type="page-list"> in nav document
- EPUB2 <pageList><pageTarget> in ncx document
- Adobe page-map document  <spine page-map="page-map">

I use regular epubs with User Patch [https://github.com/koreader/koreader/issues/9020](url)

**Comment by hius07** [comment]
Do you see the correct (your) page numbers in the right of the Bookmark list?

**Comment by edo-jan** [comment]
> Do you see the correct (your) page numbers in the right of the Bookmark list?

Yes, I do.  The logical numbers are correctly displayed across the devices once  I check the "Use reference page numbers" box
