### ISSUE TITLE
PW5 (2021, 11th Gen) - 5.16.2.1.1 - KOL V1.3 - is not targeting your device

### ISSUE THREAD

**Issue by ChiSla7** [koreader/koreader#12204]
@yparitcher

I can't install KOL V1.3 
Tested on KV PW2 PW3 PW4 KT4 PW5, 5.8.7 5.10.x 5.11.x 5.13.3 5.14.1.1

I have PW5 (2021, 11th Gen) - 5.16.2.1.1 
When installing the  KOL V1.3 in the logs

[2024-07-18 @ 22:50:26 +0300] :: [MRPI r19303] - Beginning the processing of package 'Update_KOLBooklet_0afc436_install.bin' (KOLBooklet 0afc436 I) . . .
Package 'Update_KOLBooklet_0afc436_install.bin' (KOLBooklet 0afc436 I) is not targeting your device [82A vs. 11
0F
10
24
1B
1C
1D
1F
20
D4
5A
D5
D6
D7
D8
F2
17
60
62
5F
61
C6
DD
13
54
53
2A
52
201
207
206
202
205
204
293
26B
26C
294
26E
26F
20C
20D
21C
219
21B
269
26A
2E8
341
34A
342
2E1
2E6
2F7
366
361
362
402
363
4DB
4D8
4DC
4DD
403
4D9
4DA
414
3D1
3AB
3CF
434
3D8
3D6
3D5
3D4
3D7
690
6FF], skipping . . . :(
[mrinstaller.log](https://github.com/user-attachments/files/16338953/mrinstaller.log)

**Comment by NiLuJe** [comment]
5.16.x is not currently supported.

**Comment by mergen3107** [comment]
@NiLuJe 
This is not completed yet.
The thing is, KOL repo doesn’t have Issues section :D 
@yparitcher ?

**Comment by NiLuJe** [comment]
It is very much technically not our bug ;).

**Comment by mergen3107** [comment]
> It is very much technically not "our" bug, though ;).
> 
> In the meantime, you can try using plain KUAL, which I may or may not have forgotten to repackage since that KindleTool commit ;p.

So were to ask about KOL??
