### ISSUE TITLE
[/e/OS v2.1 / Android v13] Issue when starting version 2024.07

### ISSUE THREAD

**Issue by artav4** [koreader/koreader#12211]
* KOReader version: 2024.07
* Device: Fairphone 5

#### Issue
See crash log for more details, it happens whether the app has been installed from F-droid or Github (not exactly the same error lines, but very close).

#### Steps to reproduce
1. Launch the app

##### `crash.log`

<details>
  <summary>crash.log (F-droid)</summary>

```
--------- beginning of main
07-23 21:11:01.935 V/NativeGlue( 3978): Pause: 0xb4000075d42e1d90
--------- beginning of kernel
07-23 21:11:00.024 I/binder  ( 4024): 4024:4024 ioctl 40046210 7fe41735f0 returned -22
07-23 21:11:00.091 I/binder  ( 4044): 4024:4044 ioctl 40046210 7494fce144 returned -22
07-23 21:11:00.112 I/binder  ( 4044): 4024:4044 ioctl 40046210 7494fd01a4 returned -22
```
</details>
<details>
  <summary>crash.log (Github)</summary>

```
--------- beginning of kernel
07-23 21:15:23.956 I/binder  ( 4832): 4832:4832 ioctl 40046210 7fe41735f0 returned -22
07-23 21:15:24.015 I/binder  ( 4851): 4832:4851 ioctl 40046210 74965bf144 returned -22
07-23 21:15:24.029 I/binder  ( 4851): 4832:4851 ioctl 40046210 74965c11a4 returned -22
07-23 21:16:43.672 W/audit   ( 5025): audit_lost=185209 audit_rate_limit=5 audit_backlog_limit=64
07-23 21:16:43.672 E/audit   ( 5025): rate limit exceeded
```
</details>

**Comment by benoit-pierre** [comment]
Please don't be MuPDF again…

We need more complete logs, try enabling debug logs and see [this comment](https://github.com/koreader/koreader/issues/10395#issuecomment-1537131597) for instructions.

**Comment by benoit-pierre** [comment]
Nothing useful, try with: `adb logcat KOReader:V k2pdfopt:V luajit-launcher:V dlopen:V "*:E"`.

**Comment by artav4** [comment]
Okay, I tried it but I have some logs that loop, here is a pastebin of it running for almost 3 minutes: [https://paste.hostux.net/?a07b7b70ee967693#CjECFjfKnnY6evXDtUrtuuXbyxBibBNA4ceQpvBvzeCP](https://paste.hostux.net/?a07b7b70ee967693#CjECFjfKnnY6evXDtUrtuuXbyxBibBNA4ceQpvBvzeCP)

**Comment by benoit-pierre** [comment]
Only koreader related trace:
> 07-23 22:23:09.512 19973 20096 E javaClass: ExodusInfo(packageName=org.koreader.launcher.fdroid, handle=org.koreader.launcher.fdroid, app_name=KOReader, uaid=A2C675416A06D5C96B86584044CE028BE34FAEA4, version_name=v2024.07, version_code=105233, source=fdroid, icon_hash=97507832750051062978855907342425678813, apk_hash=8a0f03a26a6e1226d337c5ae708fa05d3913cf86d94a606b081eb006baff59fb, created=2024-07-23T07:35:35.506Z, updated=2024-07-23T07:35:35.506Z, report=475415, creator=, downloads=, trackers=[], permissions=[android.permission.ACCESS_NETWORK_STATE, android.permission.INTERNET, android.permission.MANAGE_EXTERNAL_STORAGE, android.permission.QUERY_ALL_PACKAGES, android.permission.READ_EXTERNAL_STORAGE, android.permission.WRITE_EXTERNAL_STORAGE, android.permission.WRITE_SETTINGS])

Did you get a permission prompt on launch?

**Comment by artav4** [comment]
No I did not get anything at all

**Comment by benoit-pierre** [comment]
Pinging @pazos.

**Comment by artav4** [comment]
Here is another bin, I tried to launch the f-droid 2 times on the phone: [https://paste.hostux.net/?6daf8ea4fb4072d7#5DinWssj5dWm7LA2tbQj4VXAp91GCHZtLza5BBiARLD](https://paste.hostux.net/?6daf8ea4fb4072d7#5DinWssj5dWm7LA2tbQj4VXAp91GCHZtLza5BBiARLD)

**Comment by benoit-pierre** [comment]
That one is different:
> 07-23 23:07:56.916 29754 29960 E NativeThread: Failed to run script: ffi/zstd.lua:44: Failed to allocate ZSTD decompression buffer (1.844674407371e+19 bytes)

Look similar to #12010. Corrupted settings? See [comment](https://github.com/koreader/koreader/issues/12010#issuecomment-2166528003).

**Comment by artav4** [comment]
After I cleaned user data and cache and restarted the app, I got this report:
```
--------- beginning of main
07-23 23:20:26.283 V/NativeGlue(  447): Pause: 0xb4000075d42e04d0
07-23 23:20:26.331 E/launcher.fdroid(  931): Not starting debugger since process cannot load the jdwp agent.
--------- beginning of kernel
07-23 23:20:24.197 I/binder  (  931): 931:931 ioctl 40046210 7fe41735f0 returned -22
07-23 23:20:26.338 D/CompatibilityChangeReporter(  931): Compat change id reported: 171979766; UID 10310; state: DISABLED
07-23 23:20:26.347 V/GraphicsEnvironment(  931): ANGLE Developer option for 'org.koreader.launcher.fdroid' set to: 'default'
07-23 23:20:26.347 V/GraphicsEnvironment(  931): ANGLE GameManagerService for org.koreader.launcher.fdroid: false
07-23 23:20:26.347 V/GraphicsEnvironment(  931): Neither updatable production driver nor prerelease driver is supported.
07-23 23:20:26.351 D/NetworkSecurityConfig(  931): No Network Security Config specified, using platform default
07-23 23:20:26.351 D/NetworkSecurityConfig(  931): No Network Security Config specified, using platform default
07-23 23:20:26.352 I/MultiDex(  931): VM with version 2.1.0 has multidex support
07-23 23:20:26.352 I/MultiDex(  931): Installing application
07-23 23:20:26.352 I/MultiDex(  931): VM has multidex support, MultiDex support library is disabled.
07-23 23:20:26.369 D/CompatibilityChangeReporter(  931): Compat change id reported: 210923482; UID 10310; state: DISABLED
07-23 23:20:26.369 D/CompatibilityChangeReporter(  931): Compat change id reported: 37756858; UID 10310; state: ENABLED
07-23 23:20:26.371 D/CompatibilityChangeReporter(  931): Compat change id reported: 171228096; UID 10310; state: ENABLED
07-23 23:20:26.379 D/CompatibilityChangeReporter(  931): Compat change id reported: 237531167; UID 10310; state: DISABLED
07-23 23:20:26.381 W/Parcel  (  931): Expecting binder but got null!
07-23 23:20:26.395 I/AdrenoGLES-0(  931): QUALCOMM build                   : a3cdec2236, Ief33eea0db
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Build Date                       : 08/23/22
07-23 23:20:26.395 I/AdrenoGLES-0(  931): OpenGL ES Shader Compiler Version: EV031.35.01.12
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Local Branch                     : 
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Remote Branch                    : 
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Remote Branch                    : 
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Reconstruct Branch               : 
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Build Config                     : S P 10.0.7 AArch64
07-23 23:20:26.395 I/AdrenoGLES-0(  931): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
07-23 23:20:26.398 I/AdrenoGLES-0(  931): PFP: 0x016dc094, ME: 0x00000000
07-23 23:20:24.259 I/binder  (  966): 931:966 ioctl 40046210 749659d144 returned -22
07-23 23:20:26.411 E/OpenGLRenderer(  931): Unable to match the desired swap behavior.
07-23 23:20:24.275 I/binder  (  966): 931:966 ioctl 40046210 749659f1a4 returned -22
07-23 23:20:26.414 I/Gralloc4(  931): Adding additional valid usage bits: 0x8202000
07-23 23:20:48.297 E/launcher.fdroid( 1527): Not starting debugger since process cannot load the jdwp agent.
07-23 23:20:46.165 I/binder  ( 1527): 1527:1527 ioctl 40046210 7fe41735f0 returned -22
07-23 23:20:46.227 I/binder  ( 1527): 1527:1527 ioctl 40046210 7fe4172974 returned -22
07-23 23:20:46.300 I/binder  ( 1561): 1527:1561 ioctl 40046210 7496597144 returned -22
07-23 23:20:47.688 W/audit   ( 1567): audit_lost=185763 audit_rate_limit=5 audit_backlog_limit=64
07-23 23:20:47.688 E/audit   ( 1567): rate limit exceeded
```

**Comment by benoit-pierre** [comment]
As mentioned in the comment linked above:
> Cleaning storage and cache does not wipe koreader' settings, so you could try moving those out of the way.

**Comment by benoit-pierre** [comment]
Great! Re-opening to track when the fix is merged in master.

**Comment by benoit-pierre** [comment]
Never mind that last comment, wrong issue. :P

**Comment by artav4** [comment]
The issue came from the fact that I used AppLounge (the app store from /e/ that include play store and f droid packages) and I installed the first result of the search which is version 2021.05 and played with it for a while. Then I upgraded the package to 2024.07 and I think that KOReader was not meant for that

**Comment by benoit-pierre** [comment]
Yeah, that was a big version bump.

**Comment by fbriere** [comment]
> I installed [...] version 2021.05 and played with it for a while. Then I upgraded the package to 2024.07

Upgrading from 2021.05 straight to 2024.07 would very likely have triggered #12326.
