### ISSUE TITLE
KOReader fails to launch on Kindle KT5

### ISSUE THREAD

**Issue by keksbg** [koreader/koreader#12224]
* KOReader version: 2024.07
* Device: Kindle KT5 (FW: 5.15.0)

#### Issue
The application returns you to the Kindle home menu without launching the application

#### Steps to reproduce
1. Enter KUAL
2. Start KOReader (with any of the options)

##### `crash.log` (if applicable)
N/A (file is empty, but exists)

#### Additional info
I'm brand new to the jailbreaking scene but have decent IT knowledge, so originally when installing it, it still didn't function, but I tracked it down to the `koreader.sh` being empty, so I reinstalled. It still did not function, but now the `crash.log` file appeared, even if empty.

After this, I tried to get `ash` to write stdout to a file `/mnt/us/koreader.log` by appending `> /mnt/us/koreader.log` to the `params` field of the menu item, but the file simply remained empty (but was created!).

The device was jailbroken by following https://kindlemodding.gitbook.io/ with LanguageBreak.

**Comment by hius07** [comment]
Looks like incorrect unzipping of the KOReader installation package.

**Comment by keksbg** [comment]
I was using `file-unroller` but using `unzip` seems to have done the job. Interesting. Thanks for the help!
