### ISSUE TITLE
FR: Ability to manage collections from within collection view

### ISSUE THREAD

**Issue by tarkeez** [koreader/koreader#12225]
**Does your feature request involve difficulty completing a task? Please describe.**
When selecting a book in file view (and other views, e.g. History), you can press "Add to collection" which lets you manage the collection(s) that the book is in.

However, when selecting a book from inside a collection view, you can only "Remove book from collection".

I often first add books into general collections, and then want to use those collections to add books to other collections.

**Describe the solution you'd like**
From within a collection, when you select a book, have the same menu as when you select a book from file view.

Perhaps in addition to the "Remove from collection" option.

**Comment by hius07** [comment]
We'd like to have even number of buttons in that popup.
