### ISSUE TITLE
FR: Remove redundant steps to edit highlights

### ISSUE THREAD

**Issue by charleshan** [koreader/koreader#12234]
**Does your feature request involve difficulty completing a task? Please describe.**
There's a redundant step to delete/edit highlight when there's a note attached to a highlight.

**Describe the solution you'd like**
When you tap on the highlighted note, it should open the highlight menu right away and we should get rid of the "Note" menu with "Delete highlight" and "Edit highlight." Currently, in order to edit a note, we need to
1. Tap on the highlight
2. Tap "Edit highlight"
3. Tap "Edit note"

Step 2 is redundant.

**Additional context**
KOREADER Version: 2024.07

**Comment by hius07** [comment]
Step 2 was added (by a users' request) to have a quick way to view a note content.

**Comment by Commodore64user** [comment]
I suppose what @charleshan is really trying to say is that editing a note takes quite a long number steps.

currently when one taps on the highlight, it is show the note (great idea, Walter!) and two buttons `[delete highlight] [edit highlight]` perhaps these could be changed to `[edit note] [edit highlight]` or long-press on `[edit highlight]` could be edit note.

I personally like the `[edit note] [edit highlight]` better, as delete can also be found under edit.

**Comment by hius07** [comment]
> the `[edit note] [edit highlight]` better

In the beginning, the left button was `Cancel`.
Then it was changed to `Delete highlight` **by a user's request**, to have a quick way to delete a highlight.

**Comment by Commodore64user** [comment]
> [edit note] [edit highlight] 

it is a lot harder to edit a note now than it would be to delete a highlight with this. But I don't know, what would really be in the best interest of most users?

**Comment by jonnyl2** [comment]
A little 'pencil on square' icon could be added in the top right (as in the dictionary dialog) to edit the note.

Also, I think the buttons would be better as `Delete note` and `Edit highlight`. Currently, `Delete highlight` deletes both the note _and_ the highlight, which might be unexpected. And just deleting the note requires Edit highlight - Edit note - Backspacing the entire note - and then Save. Deleting highlight and note could still be done with two quick taps - Edit highlight - Delete. 

(But I rarely use notes on highlights myself, so not too invested in this.)

**Comment by Commodore64user** [comment]
> A little 'pencil on square' icon could be added in the top right (as in the dictionary dialog) to edit the note.

elegant solution.
