### ISSUE TITLE
FR: popup dialog for inverting page turn buttons

### ISSUE THREAD

**Issue by KraXen72** [koreader/koreader#12239]
**Does your feature request involve difficulty completing a task? Please describe.**
i set up the invert page turn buttons to bottom left corner. it works, but no popup is shown, so i have to test it each time to know if it's inverted or not

**Describe the solution you'd like**
show a popup like 'frontlight enabled' or 'frontlight' disabled

**Describe alternatives you've considered**
-

**Additional context**
boox go color 7 android 12 koreader 2024.07

**Comment by Commodore64user** [comment]
perhaps something fixed like this, could also indicate that one has inverted their page turn buttons.

![Reader_2024-04-06_144333](https://github.com/user-attachments/assets/f22218bc-e868-4f4d-ab20-d546e211f714)

**Comment by KraXen72** [comment]
good idea as well.

**Comment by Commodore64user** [comment]
> good idea as well.

But terrible implementation, what was i thinking?... the obvious way is to add an "item" (a complication) to the status bar.

**Comment by KraXen72** [comment]
oh, yeah. that way, we could have both a touch input indicator and a page button invert indicator items in the status bar
