### ISSUE TITLE
FR: Allow change of static margin (progress bar) & make the progress bar & alt bar more consistent

### ISSUE THREAD

**Issue by zenminimalist** [koreader/koreader#12238]
**Does your feature request involve difficulty completing a task? Please describe.**

Based on a question #12235, it would be nice to be able to **change the static margin in the process bar**. For me, I like the edge-to-edge view.

Also, it would make sense to allow users to **make the UI/margins it matches the alt status bar** that goes edge to edge. That would make it look more consistent for those who have the alt bar and the progress bar active.

Furthermore, **adding a `|` between items in the alt bar and allowing you to change the arrangement**, would make it consistent with the configuration options of the progress bar.

**Describe the solution you'd like**

Ideally, a standard feature or, if this is not applicable to most users, have it added to the advanced settings. That way, power users or users that wish to change it, can, and it would override any settings from future updates. 

According to @Frenzie it was suggested before in #[6157](https://github.com/koreader/koreader/issues/6157#issuecomment-629757688) 

**Describe alternatives you've considered**
I'm not seeing any alternative how to change it.

I'm using Android on Supernote. I would think that the Android version it the most-used one and would be sense to start there.

**Comment by pazos** [comment]
Hi.

Static margins are 10 by default on everything but android. On android it's calculed based on material guidelines, to take rounded corners into account.

On both cases you can set margins to 0.

Since, on android we just skip the inset at the top, the bottom, with 0 margin, should have the entire width available, like the top menu.

But I have nothing against making it configurable, as long as it defaults to rounded corners :)

**Comment by zenminimalist** [comment]
Thanks for explaining. 

Yeah, I seem to like the progress bar with a tiny bit (10) of space on both sides. It just looks better. 

Making it a customizable in advanced setting or something would be great as you don't over-burden the average user, but also caters to "tweakers" and what is so great about KOReader: it does everything, anywhere, anytime (well almost 😊)

**Comment by NiLuJe** [comment]
Fixed via #12243
