### ISSUE TITLE
Deleting a bookmark causes a crash

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12230]
* KOReader version: v2024.07-30
* Device: PB 268

#### Issue
Trying to delete a bookmark from the bookmarks list causes a crash.
I selected a bookmark by long pressing it and then I chose "delete". When I confirmed my choice a crash occurred.

##### `crash.log` (if applicable)
[crash 28-7-2024.log](https://github.com/user-attachments/files/16403766/crash.28-7-2024.log)

**Comment by hius07** [comment]
Thanks. To not wait a build:
[readerannotation.lua.txt](https://github.com/user-attachments/files/16403889/readerannotation.lua.txt)

**Comment by ichnilatis-gr** [comment]
Thank you!
