### ISSUE TITLE
option to remove progress bar in altbar

### ISSUE THREAD

**Issue by KarkanAlzwayed** [koreader/koreader#12233]
**Does your feature request involve difficulty completing a task? Please describe.**
No

**Describe the solution you'd like**
There is no problem to warrant a solution. This is merely a UI appearance thing. 

Setting up the altbar to display certain info while reading is great. There is a persistent progress bar under the items that can't be removed. There is already a progress bar at the bottom menu. Could there be an option to remove the progress bar on the top? 
Thank you
![IMG_20240728_115555](https://github.com/user-attachments/assets/5d6a2c10-46fb-4e68-99fa-8e84abd252c6)

**Comment by poire-z** [comment]
Duplicate of #12216.

**Comment by gilgulgamesh** [comment]
Well, I forked a patch to draw a second progress bar on top. If you colour it fully white and  position it, it can fully obscure the alt status bar. [link](https://github.com/gilgulgamesh/koreader-patches/blob/main/2-progress-bar-siblings.lua) (not on android)

Yes it's an even jankier version of drawing a white line, but it works. You could draw the bottom one white or below the screen to ignore it
