### ISSUE TITLE
FR: Do not split photos between pages.

### ISSUE THREAD

**Issue by tymmej** [koreader/koreader#12237]
Some photos in books are split between pages which  is undesirable.

Is it possible to make style tweak to show photos on one page?
It's not straightforward , because inserting new page before every photo isn't always necessary - some photos can fit on page without problem.

As seen on screenshot first photo fits the page, but second is split.

I've seen this behavior in many books.

![IMG_0221](https://github.com/user-attachments/assets/52263bba-e8a4-45f4-b5fd-ee9d63cf2d03)

**Comment by poire-z** [comment]
Normally, this should be taken care of by our page splitting code.
Unless there's some complex HTML (ie. all this being in a table) or the publisher uses CSS like `page-break-before: avoid` or `break-inside: avoid`. You could try setting `Embedded styles: off` in our bottom menu to confirm that.
Then, you can try a radical global style tweak to cancel any `avoid` (that may kill proper `break-before: always` at start of chapter, then not making a new page):
`* { break-before: auto !important; break-after: auto !important; break-inside: auto !important; }`

If it's too radical, you'll need to view the HTML/CSS and see if you can target these to something more precise that actually gets these publisher's `break-xyz: avoid`, like may be the DIV container of these images.
(`break-before:` and `page-break-before` are synonyms for the specs and for our code, so you can use one or the other, one would overwrite both one and the other).

**Comment by tymmej** [comment]
Disabling embedded styles works.

Each photo with description is in its own `div`
```
<div class="no"> <p class="img"><img alt="Świątynia Kali, bogini czasu i&nbsp;śmierci. Składa się jej krwawe ofiary&nbsp;– dawniej ludzi, dziś koguty, barany i&nbsp;koziołki" src="../Images/tab-27.jpg"/></p> <p class="img_podpis">Świątynia<span class="reset dark-gray2"> Kali, bogini</span> czasu i&nbsp;śmierci. Składa się jej krwawe ofiary&nbsp;– dawniej ludzi, dziś koguty, barany i&nbsp;koziołki</p> </div>
```
class `no`:
```
.no{
	page-break-inside: avoid;
}
```

After setting
```
.no { break-inside: auto !important; }
 ```
and enabling embedded styles images are no longer split between pages.

I do not see `break-inside` property in CSS files nor inline CSS.

**Comment by poire-z** [comment]
> I do not see `break-inside` property in CSS files nor inline CSS.

Not sure I understand what you mean by that last sentence.
You wrote above the following, which means you do see  `break-inside` (synonym of `page-break-inside`), isn't it?:

> class `no`:
> 
> ```
> .no{
> 	page-break-inside: avoid;
> }
> ```

**Comment by tymmej** [comment]
Didn't know that's synonym :)

**Comment by tymmej** [comment]
I'm reading https://developer.mozilla.org/en-US/docs/Web/CSS/break-inside:

> By default, it is possible for you to get a break between the image and its caption, which is not what we want. To avoid this, we have set break-inside: avoid on the <figure>, which causes them to always stay together.

It seems similar to book: `<figure>` corresponds to `<div class="no">.

Document says that it's to avoid split between image and caption, not to prevent splitting image.

I'm not familiar to CSS but it seems to like a bug in koreader's renderer. And if it isn't - the behavior is very unfriendly for user.

**Comment by poire-z** [comment]
So, you must also have a `break-after/before/inside: avoid` (or some negative margin) around/above `<div class=no>`
The bits you showed ensures that indeed, one full `div>p>img+caption` should stick together.
But 2 such combos should be split onto 2 pages at their boundary to ensure that each do not break inside (assuming they each fit on a page).
If this does not happen, there's something else at play. (If you can't find it, and you can share that book, I can have a look.)

KOReader should do all that as specified by the publisher (except in some specific cases like negative margins, or for some CSS properties trick we may not support), we do as the publisher specifies.
In the case where we are the publisher, with Wikipedia EPUBs, were I did set the proper `break-inside:avoid`, we get:
![image](https://github.com/user-attachments/assets/22cff9b5-c8f7-4575-8baa-61af6b6e0bf9)
![image](https://github.com/user-attachments/assets/4da669b8-70e4-4882-8df2-d30687e4c709)
![image](https://github.com/user-attachments/assets/8815e626-a42d-45a0-8ec7-73bb2da72ef9)

**Comment by Frenzie** [comment]
It might suffice to pull it through ScrambleEbook https://www.mobileread.com/forums/showthread.php?t=267998

**Comment by tymmej** [comment]
Here's scrambled version.

Problem is around 6%: 
![obraz](https://github.com/user-attachments/assets/e9e53a54-017b-4b65-a1d3-77645f19ac3c)


[Samsara. Na drogach, ktorych nie ma - Tomek Michniewicz_scrambled.zip](https://github.com/user-attachments/files/16411746/Samsara.Na.drogach.ktorych.nie.ma.-.Tomek.Michniewicz_scrambled.zip)

**Comment by poire-z** [comment]
OK, this might happen if the/some images are taller than the page height: as we're going to have to break it anyway, the whole break-inside:avoid block may be broken at some point.
Quick way to get the expected behaviour on my emulator : Zoom/DPI: 48, to get images half size, and it behave as I would expect.
You may be able to get this without such a drastic reduction with a style tweak like:
`img { max-height: 80vh }` meaning each image can take up to 80% of the viewport height, which may leave room for the caption.
(We ensure each image don't go over 100%, but we don't/can't ensure the image + its container and text won't by reducing the image just enough so it all fits.)

**Comment by tymmej** [comment]
`img { max-height: 80vh }` works for me.

Should the issue remain closed or reopened?

Is it expected behavior or bug?

**Comment by poire-z** [comment]
For me it's the expected behaviour: we ensure the break-* rules and the natural image sizes. If they conflict or the device screen is too small, there's not much we can do (automatically with tons of heuristics that will obviously fail in some cases).
It's a matter of the bothered user fighting publisher styles with style tweaks.
