### ISSUE TITLE
HTTP proxy setting isn't applied on startup

### ISSUE THREAD

**Issue by WillDawnlll** [koreader/koreader#12244]
* KOReader version: v2024.07
* Device: kindle kpw5

##### 1. translate proxy

the translate server host dns patch in issue not work now, then i noticed top menu Network has http proxy.
after some search and try in code, it finally work, but seem like got some "bug" or question?
   
i modified "frontend/ui/translator.lua" trans_servers https url to http, and restart koreader.
now the http proxy menu in Network is enable. but translate not work.
i need to turn off and on this checkbox once, then translate page got right result. 
is this a bug?
(and before change https to http(default koreader), only proxy menu stuff not get it work)

> in the end, i use settings.reader.lua to config it without code edit, but i'm not sure use it in right way.
> `["trans_server"] = "http://translate.googleapis.com/",`
> or may be i should use some user patch lua to hook it?

##### 2. wikipedia proxy

this https to http fix not work in wikipedia, what should i do ?
> wikipedia.lua  wiki_server = "https://%s.wikipedia.org",
> default koreader setting with normal http proxy menu config not work too.  

#### Steps to reproduce

just modiy frontend/ui/translator.lua  url https to http, then config top menu Network http proxy 
```
local Translator = {
    trans_servers = {
        "https://translate.googleapis.com/",

```
or put this `["trans_server"] = "http://translate.googleapis.com/",` in settings.reader.lua.

**Comment by Frenzie** [comment]
What do you mean by the host DNS patch?

**Comment by WillDawnlll** [comment]
this patch file https://github.com/koreader/koreader/issues/9574#issuecomment-1264292099

i add http.proxy in this first, but finally i use menu set proxy and delete this.

**Comment by Frenzie** [comment]
The key there is a working address/IP. `180.163.151.162` isn't functional, at least for me. `203.208.40.66` does work.

**Comment by WillDawnlll** [comment]
yes, do some manual DNS to find a good ip will working. but i thought there is a http proxy in menu, so i just use it. and it work, now just left some question . 

When the process is just started, the checkbox in this menu is checked, but the proxy does not work.
>only in translate page, i dnot know other function that the proxy can be work on it. 
>I thought proxy would be globally available to the entire process, but it seems I was wrong.

i need to trun the http proxy checkbox off and on once, then proxy translate page will work properly. 
I'm not sure if this is how it's designed to work.

**Comment by Frenzie** [comment]
Right, so the proxy isn't set on startup, or at least not in accordance with that menu setting.

https://github.com/koreader/koreader/blob/dbebf3f9961a5fdc43fe797939cd66e461c9ed45/frontend/ui/network/manager.lua#L1228-L1231

I guess that should be something like this:

```diff
diff --git a/frontend/ui/network/manager.lua b/frontend/ui/network/manager.lua
index 8559215fb..90f772b6f 100644
--- a/frontend/ui/network/manager.lua
+++ b/frontend/ui/network/manager.lua
@@ -1188,8 +1188,9 @@ function NetworkMgr:setWirelessBackend(name, options)
     require("ui/network/"..name).init(self, options)
 end
 
--- set network proxy if global variable G_defaults:readSetting("NETWORK_PROXY") is defined
-if G_defaults:readSetting("NETWORK_PROXY") then
+if G_reader_settings:readSetting("http_proxy_enabled") and G_reader_settings:readSetting("http_proxy") then
+    NetworkMgr:setHTTPProxy(G_reader_settings:readSetting("http_proxy"))
+elseif G_defaults:readSetting("NETWORK_PROXY") then
     NetworkMgr:setHTTPProxy(G_defaults:readSetting("NETWORK_PROXY"))
 end
```
