### ISSUE TITLE
Dictionary lookup broken

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#12268]
* KOReader version: 2024.07-49
* Device: Onyx Boox Page, FW 3.5.3

#### Issue
Dictionary lookup fails.
#### Steps to reproduce
Open a text, look up a dictionary word

I attach output of adb logcat with debug log enabled in developer settings, but there seems nothing in it, the query just returns with no results (again problems with the dictionary library?)
[koreader.log](https://github.com/user-attachments/files/16468171/koreader.log)

**Comment by benoit-pierre** [comment]
That's because the sdcv binary is missing (Cf. https://github.com/koreader/koreader/pull/12275).
