### ISSUE TITLE
Deleting selected bookmarks causes a crash 

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12269]
* KOReader version: v2024.07-30
* Device: PB 628

#### Issue
Trying to delete selected bookmarks from the bookmarks list causes a crash.
I chose the filter for the bookmarks, I selected some bookmarks and then I chose the delete command. When I confirmed my choice a crash occurred.

##### `crash.log` (if applicable)
[crash 2-8-2024.log](https://github.com/user-attachments/files/16470123/crash.2-8-2024.log)

**Comment by hius07** [comment]
I do not see the crash in the log. And I cannot reporduce. What filter was used?

**Comment by ichnilatis-gr** [comment]
I used the filter for the bookmarks. I give you the log again.

[crash 2-8-2024.log](https://github.com/user-attachments/files/16470389/crash.2-8-2024.log)

**Comment by hius07** [comment]
Got it, pdf again. Thanks.

**Comment by ichnilatis-gr** [comment]
Yes. It was the same file where the previous crash occured, when I selected to delete a single bookmark.

**Comment by hius07** [comment]
To not wait a build:
[readerannotation.lua.txt](https://github.com/user-attachments/files/16472073/readerannotation.lua.txt)

**Comment by ichnilatis-gr** [comment]
Thank you once again!
