### ISSUE TITLE
Backspace broken in terminal plugin

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#12271]
* KOReader version: 9b9898d4665167740442cccf43f895401289b6b9
* Device: desktop

#### Issue
Backspace isn't working. #11843 sounds like the most relevant possible culprit, but I don't think it is.

![Screenshot_20240802_182607](https://github.com/user-attachments/assets/9b712f9c-ef33-41d7-8b23-c25a620db8b1)

#### Steps to reproduce
1. Open terminal session
2. Press backspace either on the touch keyboard or the physical keyboard

##### `crash.log` 
Not much to see.

```
08/02/24-18:27:25 DEBUG key event => code: 8 (Backspace), value: 1, time: 68331.770618 
08/02/24-18:27:25 DEBUG AutoSuspend: onInputEvent 
08/02/24-18:27:25 DEBUG setDirty via a func from widget table: 0x744e3d14cb80 
08/02/24-18:27:25 DEBUG setDirty via a func from widget table: 0x744e3d14cb80 
08/02/24-18:27:25 DEBUG setDirty via a func from widget table: 0x744e3d14cb80 
08/02/24-18:27:25 DEBUG not painting 2 covered widget(s) 
08/02/24-18:27:25 DEBUG painting widget: table: 0x744e3d14cb80 
08/02/24-18:27:25 DEBUG painting widget: VirtualKeyboard 
08/02/24-18:27:25 DEBUG _refresh: Enqueued ui update for region 510 197 3 43 dithering: false 
08/02/24-18:27:25 DEBUG _refresh: Enqueued ui update for region 70 154 1263 688 dithering: false 
08/02/24-18:27:25 DEBUG _refresh: Enqueued ui update for region 41 125 1321 746 dithering: false 
08/02/24-18:27:25 DEBUG triggering refresh {
  mode = "ui",
  region = "1321x746+41+125"
} --[[table: 0x744e3c04bee8]] 
```

**Comment by Commodore64user** [comment]
in a somewhat, not really related to this issue way. Upon @hius07's request to check if hiding the keyboard on the Terminal plugin worked, I noticed there is no support for key_events there. Thanks to the focusmanager and inputtext gods you can move around but, not even back presses work there (which is I believe the minimum we should have).

also, why is there no consistency in the placement of the X and Menu buttons? some widgets have them at the top right and left respectively (the correct place) and this one just doesn't, same for book style tweaks.

**Comment by Frenzie** [comment]
I don't recall if there is a specific reason. Maybe @zwim knows. But as for the menu button this simply predates most of that.

**Comment by Commodore64user** [comment]
For clarification, yes the physical alphabet keys work fine, by key-events i was specifically referring to <kbd>back</kbd> <kbd>menu</kbd> and <kbd>home</kbd> keys. Back should close, menu should open/close the hamburger menu and home should send you to the FM’s home folder.

**Comment by NiLuJe** [comment]
Do you get the same behavior with the text editor?

I don't recall trying the terminal, but that worked in text edit a few days ago over here.

**Comment by Frenzie** [comment]
> Do you get the same behavior with the text editor?

No, I said desktop and terminal, not Android and text editor. ;-)

**Comment by Frenzie** [comment]
Indeed it does. Curious.

**Comment by Frenzie** [comment]
Dash isn't very good as an interactive shell. When I opened the issue I hadn't noticed it wasn't using `$SHELL`, which would be my system's designated interactive shell. I think the expected behavior would be something like this:

```diff
diff --git a/plugins/terminal.koplugin/profile b/plugins/terminal.koplugin/profile
index aa028aa57..0953b5773 100644
--- a/plugins/terminal.koplugin/profile
+++ b/plugins/terminal.koplugin/profile
@@ -7,6 +7,11 @@
 
 # shellcheck source=/dev/null
 
+if [ -x "${SHELL}" ] && [ "${SHELL}" != "$0" ]; then
+    exec "${SHELL}" "$@"
+    exit 0
+fi
+
 TERMINAL_HOME="$(pwd)"
 # make TERMINAL_DATA an absolute path
 cd "${TERMINAL_DATA}" || exit
```

**Comment by Frenzie** [comment]
It might be worth nothing that xterm, Konsole, etc. seem to be able manage backspace in Dash without rlwrap. Though I just checked in the terminal emulator code and by the time the byte is read it's a simple ASCII `^` representation of an escape character, which confuses me.

**Comment by NiLuJe** [comment]
Is the termifno db involved in any of this? Because if it is, I can guarantee that whatever's on device will not handle" dash at all either ;).

**Comment by Frenzie** [comment]
> Yes BS is ok, but not the Cursor Keys ...

Quite true, but it's still different. :-)

**Comment by Frenzie** [comment]
No rush. In any case it's a good thing we didn't really, otherwise I might not have noticed that $SHELL thing.
