### ISSUE TITLE
Kobo Libra Colour - File Browser: Last read time resets

### ISSUE THREAD

**Issue by spinktvis** [koreader/koreader#12277]
Using a Kobo Libra Colour, the last read time resets every time I plug in a USB device via a USB-C cable, in my case a Google Pixel 8 running the latest Android, without me even touching the folder which contain books.

The last read date remains the same, the tracked progress remains the same, just the last read time resets back to a time of 00:00 for each and every book I've previously opened and read. More of a weird "cosmetic" bug imo.

Attached are debug logs with the latest nightly build, starting with me reproducing a frontlight issue for another ticket, and trying to make the history page crash, and then plugging in the phone and mounting the Kobo as storage. Since I do not know if KOReader logging continues after that, I've included it just in case it does.
[crash.log](https://github.com/user-attachments/files/16481110/crash.log)

**Comment by NiLuJe** [comment]
*Where* are you seeing the timestamps exactly?

(And is the actual device clock affected somehow?).

**Comment by NiLuJe** [comment]
Also, second, mostly unrelated question: *why* are you plugging in a phone to it?

AFAICT, they managed to break OTG between the Elipsa 2E, where I've heard mostly successful reports (barring... power management quirks, surprise surprise, lol), and the newer MTK devices, where it doesn't work anymore, at all.

So I'm unclear on what exactly the intended workflow is here ;).

**Comment by NiLuJe** [comment]
Looking at the log, turns out both my questions might be related:

* Are you actually accessing the Kobo via USBMS *from the phone*?
* If so, are you only seeing time shenanigans *after* unmounting, or as soon as you plug in the cable?

What's handling USBMS on the phone's side, and is it perhaps dropping bogus Nickel-looking [epoch & tz](https://www.mobileread.com/forums/showpost.php?p=4064358&postcount=9) files to the root of the mounted storage?

If so, do dobule-check the date/time *after* unmount, because I couldn't see that in the logs ;).

**Comment by NiLuJe** [comment]
Keep in mind vfat timestamps are in *local* time, which is a... "fun" design decision for interoperability, so it's *possible* Android is actually massively updating timestamps behind your back, too.

(I dunno, I've never mounted anything to an Android device).

**Comment by NiLuJe** [comment]
So, as a third question/task: do double-check (i.e., `stat` in a terminal) the timestamps on affected files *from the device itself*, both before and after mounting.

**Comment by spinktvis** [comment]
> _Where_ are you seeing the timestamps exactly?
> 
> (And is the actual device clock affected somehow?).

I see the timestamps in the KOReader file browser, which is set to 'sort by: last read date'.

The device clock is unaffected. 

I just replicated the same behaviour by plugging in the Kobo on my Arch Linux desktop system, copying some books across, and the KOReader file browser shows all books at 00:00 again, even the ones I previously accessed and read. So its not Android specific. 

Attached is a picture of the Kobo with KOReader fille browser running that shows the issue. The KOReader file browser is set to 'sort by: last read date' to easily access the last read book. The KOReader history page does remember the last read book correctly.
![PXL_20240804_103443079](https://github.com/user-attachments/assets/a5e4b710-f632-4ca4-8873-1eb26caba047)

> Also, second, mostly unrelated question: _why_ are you plugging in a phone to it?

My phone used to be the primary ereader, so I stored some books on it. By connecting both devices directly I skipped the "middle" step of using my computer to transfer the books. 

>     * Are you actually accessing the Kobo via USBMS _from the phone_?

Yes.

>     * If so, are you only seeing time shenanigans _after_ unmounting, or as soon as you plug in the cable?

No shenanigans observed at all.

> What's handling USBMS on the phone's side, and is it perhaps dropping bogus Nickel-looking [epoch & tz](https://www.mobileread.com/forums/showpost.php?p=4064358&postcount=9) files to the root of the mounted storage?

No files are dropped, from the Android phone, nor from the Linux system.

> So, as a third question/task: do double-check (e.g., via `stat` in a terminal) the full timestamps on affected files _from the device itself_, both before and after mounting.

Do I need to perform this on the Kobo? It has a terminal? Excuse my ignorance, this is my first venture into ereaders, Kobo, and KOReader. If you can tell me how, that would be much appreciated.

**Comment by spinktvis** [comment]
A seemingly random crash happened while I opened a book, and the books last read time were all back to 00:00.

`08/04/24-14:42:05 ERROR Failed to initialize readtimer plugin: plugins/readtimer.koplugin/main.lua:167: attempt to index field 'crelistener' (a nil value) 
08/04/24-14:42:56 INFO  opening file /mnt/onboard/Books/Nobuyuki Yuasa - The Zen Poems of Ryokan.pdf 
08/04/24-14:42:57 INFO  Inhibiting user input 
08/04/24-14:42:57 ERROR Failed to initialize readtimer plugin: plugins/readtimer.koplugin/main.lua:167: attempt to index field 'crelistener' (a nil value) 
08/04/24-14:42:57 INFO  setting zoom mode to pagewidth 
08/04/24-14:42:57 INFO  setting zoom mode to contentwidth 
08/04/24-14:42:58 INFO  Restoring user input handling 
Killed
!!!!
Uh oh, something went awry... (Crash n°1: 08/04/24 @ 14:43:04)
Running FW 4.39.23027 on Linux 4.9.77 (#1 SMP PREEMPT 69bc51802-20240419T134452-B0419142243)
Attempting to restart KOReader . . .
!!!!`

Attached is a log file, unfortunately without debug.
[crash1.log](https://github.com/user-attachments/files/16487837/crash1.log)

**Comment by NiLuJe** [comment]
> A seemingly random crash

That's an an OOM kill.

I'm guessing you have reflow enabled?

**Comment by NiLuJe** [comment]
> Do I need to perform this on the Kobo? It has a terminal?

Yes, there's a terminal plugin. It would be slightly less unwieldy in an actual SSH shell, but that should do for a quick test.

**Comment by NiLuJe** [comment]
> No files are dropped, from the Android phone, nor from the Linux system.

Then, err, *what* are you doing with that USBMS session? ^^

**Comment by NiLuJe** [comment]
Okay, as usual, turns out FAT32 is the worst: I knew it had generally *terrible* time resolution, but it turns out it's *hilariously* bad for atime: 1 **day**.

c.f., https://stackoverflow.com/a/31521204

#notourbug
