### ISSUE TITLE
FR: Synchronize notes and highlights with Notion

### ISSUE THREAD

**Issue by david-vct** [koreader/koreader#12279]
**Description**
The synchronization sends the notes and highlights taken on books to a Notion page
*This feature follows the trend of opening KOReader to external private software*

**Some implementation options**
The synchronization may be with a Notion page or with a Notion database
The Notion structure data may be one book by page or all in one page
The synchronization may be one side only (KOReader changes updates Notion, but Notion changes doesn't update KOReader)

**Comment by pazos** [comment]
Notion is welcome as an exporter target, if somebody contributes it.

A proper notion plugin needs to happen elsewhere. At least until it is made generic to support multiple backends. 

> This feature follows the trend of opening KOReader to external private software

Mmm, having to **support** random APIs on the internet? Sounds not fun :/

We just use two well known endpoints from google (translate) and amazon (readwise exporter), unless I'm missing something.
