### ISSUE TITLE
Onyx Boox Page auto-shutdown causes last read dates to be reset

### ISSUE THREAD

**Issue by mjtimblin** [koreader/koreader#12284]
* KOReader version: 2024.07
* Device: Onyx Boox Page

#### Issue
The last read date/time of all ebooks are set to "1979-12-30 11:00:00 PM" when the device auto powers-off due to power settings (while KOReader is open). The history view shows the correct last read date/time though but often is missing the percent complete.

I've been running KOReader on this device for a year, and I have had the issue for the past couple months. I've definitly observed this behavior with the last version of KOReader (2024.04) since I waited to report the issue until after I updated. I don't recall when I first saw the issue (other than it's been for several months), so I can't say whether it started after a system update or not

#### Steps to reproduce
I have yet to test the different system power settings, so I'll just post the exact settings that I use below.

1. Open the device settings, and select the "Date & Time" option. Set "Power-off Timeout" to "Inactive after 12 hour(s)". I don't think it's relevant, but my "Auto Sleep" setting is set to "Inactive after 10 min(s)"
2. Open KOReader and navigate to the file browser
3. Set the Display mode to to "Detailed list with cover images and metadata". I'm sure any other detailed list option or classic would work since they all show the date.
4. Set the sort by setting to "last read date"
5. Open and close multiple ebooks/documents. On the file browser view, the last read dates show the appropriate date and times. This is preserved and is accurate when closing and re-opening KOReader, pressing the lock/unlock button, using a magnetic sleep cover, and letting the device sleep after 10 minutes of inactivity.
6. Close the sleep cover (or press the lock button on the device) and wait at least 12 hours for the device to auto-shutdown
7. Turn on the device with the power button
8. Open KOReader
9. All ebooks/documents in the file browser have had their last read date set to "1979-12-30 11:00:00 PM". Dates are accurate in the history view though, however often (but not always) the percent completed will be blank for some items.
    - e.g. In the history view, a book will have the last read date of "2024-08-02 10:06 PM", and no progress will be listed (not 0% but blank where the progress would be). In the file browser, the same book will have a last read date of "1979-12-30 11:00:00 PM". Opening the book, will bring me correctly to the last read page I read regardless of where I open it from (history vs file browser)

**Comment by NiLuJe** [comment]
Extremely likely not to be our bug. Apparently, atime is hard to get right.

re https://github.com/koreader/koreader/issues/12277#issuecomment-2267616477
