### ISSUE TITLE
InfoMessage while opening filemanager

### ISSUE THREAD

**Issue by noxhirsch** [koreader/koreader#12281]
Since it takes a moment to open (go back to) the file manager, I was never sure if my last gesture/tap was registered - for example when I reached the end of my book. Therefore I created a user patch that shows me an InfoMessage instantly, so that I know that the ereader is thinking and I have to wait a second instead of impatiently tapping again ;)

`patches/2-infomessage-open-filemanager.lua`

```lua
local ReaderUI = require("apps/reader/readerui")
local UIManager = require("ui/uimanager")
local InfoMessage = require("ui/widget/infomessage")
local _ = require("gettext")

local showFileManager_orig = ReaderUI.showFileManager
ReaderUI.showFileManager = function(self, file, selected_files)
    UIManager:show(InfoMessage:new{
        text = _("Open filemanager ..."),
        timeout = 0.0,
        invisible = seamless,
    })
    UIManager:forceRePaint()
    showFileManager_orig(self, file, selected_files)
end
```

**Comment by NiLuJe** [comment]
Please move this to [the wiki](https://github.com/koreader/koreader/wiki/User-patches#available_patches) so as not to clutter the issue tracker ;).

Also:

```diff
--- foo.lua.orig        2024-08-04 03:47:55.807126462 +0200
+++ foo.lua     2024-08-04 03:48:50.322576082 +0200
@@ -4,12 +4,11 @@ local InfoMessage = require("ui/widget/i
 local _ = require("gettext")
 
 local showFileManager_orig = ReaderUI.showFileManager
-ReaderUI.showFileManager = function(self, file, selected_files)
+ReaderUI.showFileManager = function(...)
     UIManager:show(InfoMessage:new{
-        text = _("Open filemanager ..."),
+        text = _("Opening filemanager…"),
         timeout = 0.0,
-        invisible = seamless,
     })
     UIManager:forceRePaint()
-    showFileManager_orig(self, file, selected_files)
+    showFileManager_orig(...)
 end
```

* That `seamless` is not referenced anywhere here, I'm guessing you just pulled a random IM invocation from somewhere that had it.
* varags FTW if you're just passing them around for a wrap

**Comment by hius07** [comment]
> * varags FTW if you're just passing them around for a wrap (also happens to make it future-proof)

I like it. Why don't we do
```Lua
function PdfDocument:findAllText(...)
    return self.koptinterface:findAllText(self, ...)
end
```
instead of
https://github.com/koreader/koreader/blob/030f4a15d4a2b13d3264968bf10d7b13b0c3ec97/frontend/document/pdfdocument.lua#L339-L341

**Comment by noxhirsch** [comment]
> Please move this to [the wiki](https://github.com/koreader/koreader/wiki/User-patches#available_patches) so as not to clutter the issue tracker ;).

Done!

> * That `seamless` is not referenced anywhere here, I'm guessing you just pulled a random IM invocation from somewhere that had it.

I copied it from the file-opening InfoMessage, wondered what "seamless" means in this context, but didn't realize that it is just a variable - stupid me 🤦‍♂️

> * varags FTW if you're just passing them around for a wrap (also happens to make it future-proof)
 
Great tip - thank you!

**Comment by poire-z** [comment]
> > * varags FTW if you're just passing them around for a wrap (also happens to make it future-proof)
> 
> I like it.

I don't. One would have to follow the functions all the way to get any idea what the parameters are. I prefer to see all of them in the first function I need to look at.

**Comment by hius07** [comment]
> One would have to follow the functions all the way to get any idea what the parameters are

No sense for a proxy like pdfdocument.

**Comment by poire-z** [comment]
That would just make it clear it's a proxy function. But I would still have to open koptinterface.lua to know what each parameter is named (which I would probably have to do to understand a bit more what each parameter really does).
And there are probably some other nearly-proxy functions that don't forward one or more of the last parameters, or force them to nil/false/true, that you would have to leave as-is, introducing some bit of inconsistency in our reading :))
