### ISSUE TITLE
FR: Headless Highlight Export

### ISSUE THREAD

**Issue by qzdl** [koreader/koreader#12298]
Hello folks.  Thank you for building and maintaining this excellent reader.

I’ve read through many issues relating to exports, and cannot find a means to export highlights without the UI or some HTTP services.

With readers as ‘dumb’ devices, I prefer to avoid complex syncing solutions; this way the device need only contain a SSH Authorized Key and some books.  This has excellent mileage, but suffers in only transporting raw data.

To increase the quality of synced data, it would be ideal to leverage the highlights/bookmarks parser in-situ.

Ideally; Given some set of options (format = JSON, scope = All books, min_created_at = …), trigger export.

Hopefully, this may be achieved by simply loading `exporter.koplugin` in some lua script, and calling the necessary functions:
- As a floundering novice to lua and this codebase, I thought it best to touch base before embarking.

Do let me know of any pertinent info I’ve missed — will share here anything I discover.

Cheers!

**Comment by Frenzie** [comment]
I'm not immediately sure if there's a reasonably elegant solution for that as is. As for a custom script, see the first few lines of tools/wbuilder for some basics.

https://github.com/koreader/koreader/blob/a6663202b7220e8069a7d1aa9b8d9431acab8e91/tools/wbuilder.lua#L4-L12
