### ISSUE TITLE
v2024-07 crash at startup on Tolino HD3

### ISSUE THREAD

**Issue by sennah-github** [koreader/koreader#12306]
* KOReader version: 2024-07
* Device: tolino hd3

#### Issue
KOReader crashes (see crash.log)

#### Steps to reproduce
Install v2024-07 and run it

[crash.log](https://github.com/user-attachments/files/16515490/crash.log)

I use KOReader on this device since several years with great fun. Thanx!
I always just downloaded the latest version and installed it w/o any issues. 
Well, v2024.07 crashes when trying to start it. I downloaded and installed v2024-07 several times w/o luck.

Fix: Delete data, cache and v2024-07. Then install v2024-04 which works well.

**Comment by benoit-pierre** [comment]
Nothing stand out in the log. Can you enable debug logging, uninstall v2024-04, and re-install v2024-07? Don't update, uninstall the previous version (koreader settings are not stored in the app data, so you should not loose anything).

**Comment by sennah-github** [comment]
Thank's for your feedback @benoit-pierre 

Here's a follow-up. I've
- deleted cache and data of KOReader
- uninstalled KOReader 
- removed KOReader folder
- upgraded tolino firmware from 15.3.0 to 16.2.0 which is the latest version
- installed KOReader v2024-04  which works fine
- enabled debug logging in KOReader v2024-04 (How could I enable this in a version that crashes?)
- uninstalled KOReader v2024-04
- installed KOReader v2024-07 which crashes on startup

I can only hope that this crash.log gives any hints:
[crash.log](https://github.com/user-attachments/files/16523602/crash.log)

Thanx for reading.

**Comment by benoit-pierre** [comment]
> enabled debug logging in KOReader v2024-04 (How could I enable this in a version that crashes?)

Since the settings are stored outside the application (e.g. `/sdcard/koreader/settings.reader.lua`), they do survive uninstallation.

Can you get a log with `pidcat` or `adb logcat`? See [this comment](https://github.com/koreader/koreader/issues/10395#issuecomment-1537131597) for instructions.

**Comment by benoit-pierre** [comment]
Also, you might want to try the [latest nightly](https://build.koreader.rocks/download/nightly/v2024.07-69-g975efae92_2024-08-06/koreader-android-arm-v2024.07-69-g975efae92_2024-08-06.apk).

**Comment by sennah-github** [comment]
Because it's easy and quick I decided to give 2024.07-69 a try.
This nightly seems to work fine :-) Thank's
