### ISSUE TITLE
Nightly builds are failing since last 3 days

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#12304]
@Frenzie https://gitlab.com/koreader/nightly-builds/-/pipelines/1399377616
@benoit-pierre since it seems related to your ci/build changes, or the recent base bump

**Comment by Frenzie** [comment]
Grmbl, it's supposed to email me. Anyway, thanks. :-)

**Comment by Frenzie** [comment]
Looks like resaving the settings worked. Yay! :-)

![image](https://github.com/user-attachments/assets/3dd5c243-2556-4abd-90a8-051045a91156)

**Comment by benoit-pierre** [comment]
> find_program (<VAR> name1 [path1 path2 ...])
> […]
> REQUIRED
>
>    New in version 3.18.
>
>    Stop processing with an error message if nothing is found, otherwise the search will be attempted again the next time find_program is invoked with the same variable.

Dammit, that's why it's not failing at setup if meson is missing…

**Comment by benoit-pierre** [comment]
BTW, shouldn't "Auto-cancel redundant pipelines" be used?

**Comment by Frenzie** [comment]
Every pipeline may well be "redundant" for over a year (but at the very least for many weeks) so I would say emphatically not.

Besides which, the specific scenario that made you say that only happens one a year or so. :-)

But more important, the Android builds seem to be failing. I don't have time to investigate atm.

https://gitlab.com/koreader/nightly-builds/-/jobs/7513467888
```
==== Successfully installed LuaJIT 2.1.ROLLING to  ====
Building KOReader release APK: Version v2024.07-63-g7e8cdbcf6_2024-08-06, release 10586, flavor Rocks
Checking the license for package Android SDK Build-Tools 34 in /opt/android-sdk-linux/licenses
License for package Android SDK Build-Tools 34 accepted.
Preparing "Install Android SDK Build-Tools 34 v.34.0.0".
Warning: Failed to read or create install properties file.
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

**Comment by Frenzie** [comment]
Alright, it seems less destructive than it sounded. In which case I wonder why that's not simply the default.
![image](https://github.com/user-attachments/assets/c90577eb-671e-410d-b067-f6ab888b5684)

**Comment by Frenzie** [comment]
Because it's already enabled. /shrug

![image](https://github.com/user-attachments/assets/00bb3181-1146-4393-bddc-dc3b35312e53)

**Comment by benoit-pierre** [comment]
What's the default value for a job's `interruptible` field?

**Comment by Frenzie** [comment]
The default is interruptible.

**Comment by benoit-pierre** [comment]
Did you receive a mail this time?

Diff to apply (I would have made a PR but still can't sign-in without phone number and credit card info):
```diff
 .gitlab-ci.yml   |  8 ++++----
 build_release.sh | 13 +------------
 2 files changed, 5 insertions(+), 16 deletions(-)

diff --git i/.gitlab-ci.yml w/.gitlab-ci.yml
index 406099f..a523953 100644
--- i/.gitlab-ci.yml
+++ w/.gitlab-ci.yml
@@ -99,14 +99,14 @@ build_appimage:
       - "/builds/koreader/nightly-builds/koreader/koreader-*.AppImage"
 
 
-build_android:
+build_android_arm:
   image: koreader/koandroid:0.8.3-20.04
   cache:
     key: koreader_android_cache
     paths:
       - /builds/koreader/nightly-builds/ccache
   script:
-    - bash build_release.sh android
+    - bash build_release.sh android-arm
     #- ls /builds/koreader/nightly-builds/koreader/base/thirdparty/libzmq/build/arm-linux-androideabi/libzmq-prefix/src/libzmq-build/lib
   artifacts:
     #when: always
@@ -116,10 +116,10 @@ build_android:
       - "/builds/koreader/nightly-builds/koreader/koreader-android-fdroid-latest"
   #allow_failure: true
 
-build_android_aarch64:
+build_android_arm64:
   image: koreader/koandroid:0.8.3-20.04
   cache:
-    key: koreader_android_aarch64_cache
+    key: koreader_android_arm64_cache
     paths:
       - /builds/koreader/nightly-builds/ccache
   script:
diff --git i/build_release.sh w/build_release.sh
index 0b52e23..a83a0a8 100755
--- i/build_release.sh
+++ w/build_release.sh
@@ -27,17 +27,6 @@ rm -f "${BUILD_LOG}"
 
 git checkout "$(cat ../commit)"
 echo "Building release..."
-if [ "$1" = 'android' ]; then
-	./kodev build android 2>&1 > "${BUILD_LOG}"
-	./kodev release android 2>&1 > "${BUILD_LOG}"
-elif [ "$1" = 'android-arm64' ]; then
-	ANDROID_ARCH=arm64 ./kodev build android 2>&1 > "${BUILD_LOG}"
-	ANDROID_ARCH=arm64 ./kodev release android 2>&1 > "${BUILD_LOG}"
-elif [ "$1" = 'android-x86' ]; then
-	ANDROID_ARCH=x86 ./kodev build android 2>&1 > "${BUILD_LOG}"
-	ANDROID_ARCH=x86 ./kodev release android 2>&1 > "${BUILD_LOG}"
-else
-	./kodev release "$1" 2>&1 > "${BUILD_LOG}"
-fi
+./kodev release "$1" 2>&1 >"${BUILD_LOG}"
 
 popd
```
