### ISSUE TITLE
Crash upon closing a file right after panel zoom

### ISSUE THREAD

**Issue by fbriere** [koreader/koreader#12300]
* KOReader version: 2024.07-49
* Device: Kobo Forma

#### Steps to reproduce

On a Forma¹, with Panel zoom enabled:

- Open the CBZ provided in https://github.com/koreader/koreader/issues/7961#issue-941562162;
- Tap and hold on the top center panel;
- Close the zoomed-in panel;
- Open the file browser to close the file.

The combination of the panel's small-ish dimensions, its aspect ratio close to the screen's and the Forma's high resolution results in a high zoom factor and a tile size that is apparently too much for our poor little device.

¹ I guess this could also be reproduced on a Sage or Aura One, given their similar specs.

##### `crash.log`

The last lines differ depending on which action was used to close the file, but the beginning remains the same:

```
./luajit: ./ffi/zstd.lua:29: Failed to allocate ZSTD compression buffer (84120300 bytes)
stack traceback:
	[C]: in function 'assert'
	./ffi/zstd.lua:29: in function 'zstd_compress'
	frontend/persist.lua:89: in function 'serialize'
	frontend/persist.lua:244: in function 'save'
	frontend/document/tilecacheitem.lua:45: in function 'dump'
	frontend/document/doccache.lua:97: in function 'serialize'
	frontend/apps/reader/readerui.lua:819: in function 'onClose'
```

**Comment by NiLuJe** [comment]
zstd *can* work with a smaller buffer than the worst-case computed here, but if a 80MB alloc fails, I don't think it's worth attempting that on swapless devices anyway ;).

**Comment by NiLuJe** [comment]
I'm also confused by the fact that it's trying to cache a different tile after panel-zoom, which doesn't make much sense to me?

**Comment by NiLuJe** [comment]
```
08/06/24-01:59:10 DEBUG Dumping cache item renderpg|/mnt/onboard/TEST/minamoto-0112-0003-kcc.cbz|1722900885|1|9.7959183673469|0|1|0|bw|22 
08/06/24-01:59:10 DEBUG Dumping tile cache to ./cache/8ecc2e8a51ac85693c7ae8c9de88ce7a "7876x10639+0+0" 
```

vs.

```
08/06/24-02:00:58 DEBUG Dumping cache item renderpg|/mnt/onboard/TEST/minamoto-0112-0003-kcc.cbz|1722900885|1|2.1461186539648|0|1|0|bw|22 
08/06/24-02:00:58 DEBUG Dumping tile cache to ./cache/bcc73ee5676c30f1500e09bbea9f13bf "1726x2331+0+0" 
```

Something's not properly resetting the zoom factor, is it? ^^

Ping @Galunid

**Comment by NiLuJe** [comment]
> EDIT: It also breaks forking (which is never a good sign ;p), as I can't even look at a `cat /proc/meminfo` via os.execute or io.popen from there...

With a very ugly hack based on `watch` instead, yeah, something's *really* going om nom nom nom in there ;p.

With a 100ms sample time:
```
MemAvailable:     305060 kB
MemAvailable:     305060 kB
MemAvailable:     305060 kB
MemAvailable:     305060 kB
MemAvailable:     304936 kB
MemAvailable:     290528 kB
MemAvailable:     270280 kB
MemAvailable:     247912 kB
MemAvailable:     228036 kB
MemAvailable:     204552 kB
MemAvailable:     180820 kB
MemAvailable:     156964 kB
MemAvailable:     134484 kB
MemAvailable:     112116 kB
MemAvailable:      89236 kB
MemAvailable:      67276 kB
MemAvailable:      59080 kB
MemAvailable:     173240 kB
MemAvailable:     328416 kB
MemAvailable:     330164 kB
MemAvailable:     410440 kB
```

The crazy leftover zoom factor might be affecting *other* things before it happens to make the tile compression choke...

**Comment by NiLuJe** [comment]
> Something's not properly resetting the zoom factor, is it? ^^

Or... is DocCache rewinding to the zoomed-in panel instead of the page, perhaps.

An easy fix would be to *not* flag those as `persistent`.

**Comment by NiLuJe** [comment]
> The crazy leftover zoom factor might be affecting _other_ things before it happens to make the tile compression choke...

Yeah, it was also creating a humongous BB by applying the scaling factor to the *page* an using that as the BB's dimensions.
