### ISSUE TITLE
"Change defaults file" cannot handle string "arrays" in defaults file

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1231]
When changing OCR languages and traineddata prefixes via filemanager>menu>Change defaults>file the changes are not persistent, nor can I add more than 2 languages.

I would like to be able to add more than 2 languages (Fraktur and Ancient Greek) and I would like them to be persistent. Is it a designed limitation of the menu or is it a bug?

**Comment by robert00s** [comment]
The problem doesn't appear in the latest version. KOReader correct handle string array in default.persistent.lua.
I think we can close it.
