### ISSUE TITLE
Wrong front light state after resume with AutoWarmth on

### ISSUE THREAD

**Issue by ghost** [koreader/koreader#12312]
* KOReader version: v2024.07-70-g2900eef27
* Device: Kobo Sage

#### Front light 
at a much too low brightness, after resume if AutoWarmth is enabled.

#### Cause
Most probably a regression from #12256

**Comment by NiLuJe** [comment]
I was fixated on the fl_was_on change as I noticed the plugin touches it, but didn't think there could be other interactions possible :/.
