### ISSUE TITLE
Various crashes

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12322]
* KOReader version: v2024.07-74
* Device: PB 628

#### Issue
Trying to open the Table of Contents of a book or the Collections by gesture or from the menu causes a crash.

##### `crash.log` (if applicable)
[crash 9-8-2024-TOC.log](https://github.com/user-attachments/files/16569127/crash.9-8-2024-TOC.log)
[crash 9-8-2024-collections.log](https://github.com/user-attachments/files/16569128/crash.9-8-2024-collections.log)

**Comment by Frenzie** [comment]
Not in today's nightly. ;-)

**Comment by ichnilatis-gr** [comment]
Does it also fix the problem with Collections?

**Comment by Frenzie** [comment]
It should have the same underlying cause (in menu.lua), yes.
