### ISSUE TITLE
Wiping the screen with my whole hand in ImageViewer sometimes triggers a crash

### ISSUE THREAD

**Issue by fbriere** [koreader/koreader#12327]
* KOReader version: v2024.07-63
* Device: Kobo Forma (rotated 180°)

#### Issue

While in ImageViewer, if I wipe the screen with my whole hand in one motion, I can sometimes trigger a crash.

#### Steps to reproduce

First of all, since this gesture is both difficult to describe and hard to reproduce, I strongly suggest you ignore this section and jump straight to the logs.  Whatever random sequence of gestures I happened to trigger this particular time will be in there.

Also note that I have my Forma rotated 180° (portrait mode, with buttons on the *left*).  You might need to account for that when following my directions or parsing the logs.  (I could attempt to trigger an example with 0° rotation if need be.)

With that out of the way, here's my (poor) description of the required steps:

- Enter ImageViewer (I used both panel-zoom and cover viewer)
- With the right hand (flat palm, all fingers but the thumb laid on the screen) wipe across the screen with a kinda-northeast motion, as if trying to get rid of some dust (which is exactly what I was doing the first time)
- Undo whatever random action this may have caused, if any
- Go back to step 2 and repeat for as long as it takes

My own success rate is quite variable: I once did it on the first try, and needed 50+ attempts the next time.  Hence my recommendation to not waste your time trying to reproduce this if you can avoid it.  :grin:

##### `crash.log`

The exact sequence of gestures that leads to the crash seems to vary from one instance to the next, but the stack trace itself remains the same:

```
./luajit: frontend/ui/widget/imagewidget.lua:484: attempt to perform arithmetic on field '_bb_w' (a nil value)
stack traceback:
	frontend/ui/widget/imagewidget.lua:484: in function 'panBy'
	frontend/ui/widget/imageviewer.lua:549: in function 'panBy'
	frontend/ui/widget/imageviewer.lua:588: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/uimanager.lua:911: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1438: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1538: in function 'handleInput'
	frontend/ui/uimanager.lua:1582: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x000140cd
```

Here is the last sequence of gestures of one particular time where I observed a delay of 1-2 seconds between each attempt to keep them apart: [crash-wipe.log](https://github.com/user-attachments/files/16570584/crash-wipe.log)

I'll post a few more examples afterwards, in case this can help detect a common pattern.

**Comment by fbriere** [comment]
Here are two more examples (KOReader version may vary and is indicated at the beginning): 
[crash-wipe2.log](https://github.com/user-attachments/files/16570906/crash-wipe2.log)
[crash-wipe3.log](https://github.com/user-attachments/files/16570907/crash-wipe3.log)

**Comment by NiLuJe** [comment]
Looks like a classic input event between instantiation and paint.

Does this help?

```diff
diff --git a/frontend/ui/widget/imageviewer.lua b/frontend/ui/widget/imageviewer.lua
index e3d76cdaa..b13858290 100644
--- a/frontend/ui/widget/imageviewer.lua
+++ b/frontend/ui/widget/imageviewer.lua
@@ -844,6 +844,7 @@ function ImageViewer:onCloseWidget()
         self._scaled_image_func(false) -- invoke :free() on the creimage object
         self._scaled_image_func = nil
     end
+    self._image_wg = nil
 
     -- Those, on the other hand, are always initialized, but may not actually be in our widget tree right now,
     -- depending on what we needed to show, so they might not get sent a CloseWidget event.
diff --git a/frontend/ui/widget/imagewidget.lua b/frontend/ui/widget/imagewidget.lua
index 7bfb7bd75..34cc53cb6 100644
--- a/frontend/ui/widget/imagewidget.lua
+++ b/frontend/ui/widget/imagewidget.lua
@@ -480,6 +480,10 @@ function ImageWidget:getPanByCenterRatio(x, y)
 end
 
 function ImageWidget:panBy(x, y)
+    if not self._bb then
+        return
+    end
+
     -- update center ratio from new offset
     self.center_x_ratio = (x + self._offset_x + self.width/2) / self._bb_w
     self.center_y_ratio = (y + self._offset_y + self.height/2) / self._bb_h
@@ -595,8 +599,10 @@ end
 -- BlitBuffer zombies
 function ImageWidget:free()
     --print("ImageWidget:free on", self, "for BB?", self._bb, self._bb_disposable)
-    if self._bb and self._bb_disposable and self._bb.free then
-        self._bb:free()
+    if self._bb then
+        if self._bb_disposable and self._bb.free then
+            self._bb:free()
+        end
         self._bb = nil
     end
     -- reset self.scale_factor to its initial value, in case
```

**Comment by fbriere** [comment]
That seemed to do the trick!  I added a debug message to confirm I had managed to hit the `return` at least once in my testing, and yet no crash, everything seems fine.
