### ISSUE TITLE
FR: Quick Exit from KOReader

### ISSUE THREAD

**Issue by Darthagnon** [koreader/koreader#12336]
**Does your feature request involve difficulty completing a task? Please describe.**
To Exit KOReader, I navigate to [Hamburger] (2 button presses minimum) >> Select (1 button press) >> Exit (1 button press minimum) >> Select (1 button press) >> Exit (1 button press minimum) >> Select (1 button press)

On a Kindle 4 or button-based eReader, it takes minimum 7 button presses to exit KOReader, and we need to say "Exit" twice. If it's running slowly and the user skips the menu option accidentally or the wrong keypad button is accidentally pressed, that's a bunch more button presses to exit.

**Describe the solution you'd like**
I would like to exit from the hamburger menu without having to confirm a second time to exit. The Restart KOReader and Sleep options are redundant, as the Kindle 4 and most eReaders have a power button to sleep, and I will relaunch KOReader immediately from KUAL after transferring books or rebooting the device.

**Describe alternatives you've considered**
The sleep option might be needed on touchscreen eReaders that lack power buttons (I don't know if any exist?), but it could be added to the primary Hamburger menu, above Exit, rather than to a submenu.

**Comment by Frenzie** [comment]
Long press. Pinging @Commodore64user because I forget the exact shortcut.

**Comment by Commodore64user** [comment]
ScreenKB + Press

**Comment by Commodore64user** [comment]
In any case, a restart shortcut is something that has been in my mind for a while now, unfortunately K4 might not get it as there aren't enough keys and other shortcuts are at time of writing, more important.

For example, and I only recently noticed, we need a refresh screen one too.

**Comment by NiLuJe** [comment]
A long-press on the top-level Exit will exit straight away.

**Comment by Darthagnon** [comment]
> But it needs 2024.07 that OP isn't running

I'm running 2024.04 until a future release because of [2024.07's thing with the buttons](https://github.com/koreader/koreader/issues/12168)

Sorry I didn't mention it. That's good to know about the long press on the top level exit; I did not know that.

**Comment by Commodore64user** [comment]
Hold on, Pressing the back key will also prompt you to exit KOReader.

**Comment by Darthagnon** [comment]
> Hold on, Pressing the back key will also prompt you to exit KOReader.

I'd forgotten I mapped Back to the more intuitive "Go back a folder".
