### ISSUE TITLE
NT: Crash while arranging status bar items

### ISSUE THREAD

**Issue by Commodore64user** [koreader/koreader#12342]
* KOReader version: 2024.07-89
* Device: kindle 3 and 4

#### Issue

whilst 'arranging items in the status bar' if you select an item, then press the <kbd>PgFwd</kbd> key to move it to page 2: then dPad becomes unresponsive and pressing <kbd>Press</kbd>  on the same item causes a crash

#### Steps to reproduce

open book, go to `status bar > configure items > arrange items` select an item, press either <kbd>PgFwd</kbd> or `>` (bottom of the screen) then, dPad is unresponsive, <kbd>press</kbd> on very item, kaboom!!!

```
08/03/24-13:42:01 DEBUG key event => code: 194 (Press), value: 1, time: 1722688921.308755 
08/03/24-13:42:01 DEBUG key event => code: 194 (Press), value: 0, time: 1722688921.443434 
08/03/24-13:42:01 DEBUG AutoSuspend: onInputEvent 
./luajit: frontend/ui/widget/focusmanager.lua:398: attempt to index a nil value
stack traceback:
	frontend/ui/widget/focusmanager.lua:398: in function 'getFocusItem'
	frontend/ui/widget/focusmanager.lua:402: in function 'handleEvent'
	frontend/ui/uimanager.lua:915: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1446: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1546: in function 'handleInput'
	frontend/ui/uimanager.lua:1590: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00015038
lipc-wait-event exited normally with status: 0
```

**Comment by NiLuJe** [comment]
Can you reproduce on other SortWidget users?

(e.g., sorting dictionaries or collections).

**Comment by hius07** [comment]
> whilst 'arranging items in the status bar' if you select an item

It doesn't crash if you select one of the upper items (up to the number of items in the second page of the Sorter), right?

**Comment by hius07** [comment]
> Correct, if you select an item from positions currently occupied by `favourites to test 2` it works fine, select any other and dPad is unresponsive and press on eponymous item and crash...

Moving the selection by keys is done in FocusManager
https://github.com/koreader/koreader/blob/d706a129fa14dadc4ba19547442989430f119e33/frontend/ui/widget/focusmanager.lua#L51
and `FocusManager:onFocusMove()` updates `self.layout`.

Going to page 2 is done by the Sorter itself
https://github.com/koreader/koreader/blob/d706a129fa14dadc4ba19547442989430f119e33/frontend/ui/widget/sortwidget.lua#L154
so you will want to investigate how `SortWidget:_populateItems()` updates `self.layout`.
