### ISSUE TITLE
Android not building as 64 bit

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#12352]
* KOReader version: Latest nightly
* Device: 

#### Issue
When building android with ANDROID_ARCH=arm64 on Ubuntu22, I get the following, repeated several times:
WARNING: [CXX5202] This app only has 32-bit [armeabi-v7a] native libraries. Beginning August 1, 2019 Google Play store requires that all apps that include native libraries must provide 64-bit versions. For more information, visit https://g.co/64-bit-requirement
when I install it, it crashes as soon as it loads. The last version that built properly was v2024.07-73-gcafa9c825

**Comment by Frenzie** [comment]
Are your submodules updated?

**Comment by mendelct** [comment]
Tried it with a fresh clone, same issue

**Comment by benoit-pierre** [comment]
Make sure the `platform/android/luajit-launcher` checkout is clean: `git -C platform/android/luajit-launcher clean -x -d -i`.

**Comment by benoit-pierre** [comment]
Also next time please fill-in the exact version being built: "latest nightly" is a moving target.

**Comment by mendelct** [comment]
Hi

Cleaned the `platform/android/luajit-launcher` it removed `.gradle`. When I rebuilt it it did not give the warning, however it did show the following:

`[*] Clean up, remove unused files for releases
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libkoreader-djvu.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libzstd.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libunibreak.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libwebp.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libczmq.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libssl.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libpng16.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libcrypto.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libz.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libsharpyuv.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/liblodepng.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libwebpdemux.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/liblunasvg.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libharfbuzz.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libfribidi.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libluajit.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libkoreader-cre.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libsdcv.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libblitbuffer.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libc++_shared.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libjpeg.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libgif.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libkoreader-xtext.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libwrap-mupdf.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libsqlite3.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libturbojpeg.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libleptonica.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libutf8proc.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libzmq.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libkoreader-nnsvg.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libk2pdfopt.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libfreetype.so'
removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libkoreader-lfs.so'
removed directory 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a'
Files in archive and to add differ`
On loading it crashes.

**Comment by benoit-pierre** [comment]
> Hi
> 
> Cleaned the `platform/android/luajit-launcher` it removed `.gradle`. When I rebuilt it it did not give the warning, however it did show the following:
> 
> ```
> [*] Clean up, remove unused files for releases
> removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libkoreader-djvu.so'
> removed 'koreader-android-aarch64-unknown-linux-android21/luajit-launcher/libs/arm64-v8a/libzstd.so'
> […]
> Files in archive and to add differ
> ```

That's not normal.
 
> On loading it crashes.

That's still not. Since you're building for arm64, check the latest nightly (Cf.: https://github.com/koreader/koreader-base/pull/1900 & #12360).

**Comment by mendelct** [comment]
Built the latest nightly 2024.07-112-g2403087f6 and I got the warning that it is 32 bit native libraries. Installed it on an Android 14 phone, this time it did not crash. Seems to be working fine.

**Comment by pazos** [comment]
> Built the latest nightly 2024.07-112-g2403087f6 and I got the warning that it is 32 bit native libraries. Installed it on an Android 14 phone, this time it did not crash. Seems to be working fine.

You can safely ignore the message. It is just google whinning we don't do splits as they would like: https://developer.android.com/build/configure-apk-splits
