### ISSUE TITLE
FR: Gestures "Cheatsheet"

### ISSUE THREAD

**Issue by christian-ho** [koreader/koreader#12363]
**Does your feature request involve difficulty completing a task? Please describe.**
If I want to check which gestures I have configured (or don't remember a specific rarely used gesture) I have to click and search through every item in the gesture manager.

**Describe the solution you'd like**
A page in the menu with an overview list of all configured gestures.

I know you can look at the `gestures.lua` file, but it would be nice to have this inside KOReader.

**Comment by hius07** [comment]
Duplicate of https://github.com/koreader/koreader/issues/7788.

**Comment by Frenzie** [comment]
I suppose it would be nice to have, yes.
