### ISSUE TITLE
Light brightness adjustment doesn't work on Boox Go Color 7

### ISSUE THREAD

**Issue by komadorirobin** [koreader/koreader#12364]
KOReader version:
2024.07 "Outside"

Device:
Boox Go Color 7
firmware version 2024-06-21_06-11_3.5.3_899fd4030

Issue

Light brightness adjustment doesn't work on Boox Go Color 7.

I've change the hidden_api_policy to 1 using adb.

All the best

**Comment by hugleo** [comment]
If all the best we have no problem here :)

As seems to be working for the same firmware version at least for e-ink test: https://github.com/koreader/koreader/issues/8482#issuecomment-2228947940

**Comment by hugleo** [comment]
Oh sorry,

The support should be on the nighties. If you plan to upgrade please do it tomorrow because a crash bug was fixed today.

**Comment by benoit-pierre** [comment]
It's already available (if you mean the `-ffast-math` issue).

**Comment by komadorirobin** [comment]
Yes, the latest nightly build fixed this. Thank you!

**Comment by komadorirobin** [comment]
Yes, the latest nightly build fixed this. Thank you!
