### ISSUE TITLE
Dog-ear mark on the current page is not updated after exiting the page browser

### ISSUE THREAD

**Issue by fbriere** [koreader/koreader#12387]
* KOReader version: 2024.07-90
* Device: Kobo Forma, Desktop

#### Issue

After exiting the page browser (via the top-right X), the dog-ear mark on the current page is not properly updated if a bookmark has been added/removed from within the browser.

#### Steps to reproduce

- Open the page browser
- Tap-and-hold on the current page to toggle a bookmark
- Exit the page browser (via the top-right X)

At this point, a bookmark for the current page has indeed been toggled, but the dog-ear mark shows the opposite.

**Comment by poire-z** [comment]
I could swear I did took care of this case - but on the past AppImages I have and that still work (many crash... for some reason), I can reproduce this issue :/
May be it was just the more complicated dogear toggling propagation across nested PageBrowser/BookMap/PageBrowser/BookMap that I too care of.

**Comment by fbriere** [comment]
> May be it was just the more complicated dogear toggling propagation across nested PageBrowser/BookMap/PageBrowser/BookMap that I too care of.

Yeah, probably.  I first tried to fix this myself, and hoped `self.editable_stuff_edited` would do the trick, but it's only used in the very situation you described.  Instead, the general route goes through here, and I lack the knowledge to figure out what to stuff in there:

https://github.com/koreader/koreader/blob/698fc35c3f1a10233cf69085a87fb912e2f79841/frontend/ui/widget/pagebrowserwidget.lua#L1087-L1090

**Comment by poire-z** [comment]
This seems to solve the issue (to be done also in the same place in bookmapwidget.lua):
```diff
--- a/frontend/ui/widget/pagebrowserwidget.lua
+++ b/frontend/ui/widget/pagebrowserwidget.lua
@@ -1084,9 +1084,11 @@ function PageBrowserWidget:onClose(close_all_parents)
             collectgarbage()
             collectgarbage()
         end)
-        -- As we're getting back to Reader, update the footer and do a full flashing
+        -- As we're getting back to Reader, update the footer and the dogear state
+        -- (we may have toggled bookmark for current page) and do a full flashing
         -- refresh to remove any ghost trace of thumbnails or black page slots
         UIManager:broadcastEvent(Event:new("UpdateFooter"))
+        self.ui.bookmark:onPageUpdate(self.ui:getCurrentPage())
         UIManager:setDirty(self.ui.dialog, "full")
     end
     return true
```
If you can test it and confirm :) and if good, include it in your "should also refresh" PR.
@hius07 : does that look alright to you?

**Comment by hius07** [comment]
Very good.

**Comment by fbriere** [comment]
> If you can test it and confirm :) and if good, include it in your "should also refresh" PR.

Confirmed and done.
