### ISSUE TITLE
PocketBook Verse Pro Color - KOReader not launching

### ISSUE THREAD

**Issue by MetroidFusion** [koreader/koreader#12395]
Hi

I just received the new PocketBook Verse Pro Color. Unfortunately, KOreader will not launch; I have tried both stable and nightly releases without success.

Do I have to edit a config file for the application to recognise the device?

Thanks so much for making KOReader - it's really an awesome utility for reading :)

/M

**Comment by Frenzie** [comment]
In essence. If you post the crash.log file here we'll know the model number. You can already edit that yourself into frontend/device/pocketbook/device.lua for the best matching device to see if it'll just work.

**Comment by pascalsiemsen** [comment]
I have the same issue (same reader).

The crash.log says "unrecognized PocketBook model PB634K3".

Here is the file:

>                 launching...
>   _  _____  ____                _
>  | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
>  | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
>  | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
>  |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|
> 
>  It's a scroll... It's a codex... It's KOReader!
> 
>  [*] Current time: 08/22/24-12:24:17
>  [*] Version: v2024.07
> 
> ffi.load: libs/libutf8proc.so.3
> ffi.load: blitbuffer
> ffi.load: inkview
> 08/22/24-12:24:17 INFO  SoftwareVersion:  U634k3.6.8.3806 
> ./luajit: frontend/device/pocketbook/device.lua:906: unrecognized PocketBook model PB634K3
> stack traceback:
> 	[C]: in function 'error'
> 	frontend/device/pocketbook/device.lua:906: in main chunk
> 	[C]: in function 'probeDevice'
> 	frontend/device.lua:61: in main chunk
> 	[C]: in function 'require'
> 	./reader.lua:151: in main chunk
> 	[C]: at 0x00013f61
> !!!!
> Uh oh, something went awry... (Crash n°5: 08/22/24 @ 12:24:18)
> Too many consecutive crashes, aborting . . .
> !!!! ! !!!!

**Comment by Frenzie** [comment]
Right, so in short see https://github.com/koreader/koreader/pull/11695 for what to try, just swap that with PB634K3.

**Comment by ElimGarak1** [comment]
https://github.com/koreader/koreader/pull/12476

**Comment by leomeyer** [comment]
Can confirm, works when applying the changes referenced in #12476.

**Comment by Frenzie** [comment]
Fixed in https://github.com/koreader/koreader/pull/12476
