### ISSUE TITLE
edit screen size that koreader runs.

### ISSUE THREAD

**Issue by konos93** [koreader/koreader#12400]
can i edit any config file to reduce the screen where the entire koreader runs?

my device is pocketbook inkpad 3 and the screen is broken.

however the blue part still working and i thought if koreader could run in this part of the screen.

![viber_image_2024-08-24_18-17-25-462](https://github.com/user-attachments/assets/3754cb0f-d298-4226-8a3a-78a6efeb3d20)

**Comment by hius07** [comment]
https://github.com/koreader/koreader/issues/4810

**Comment by NiLuJe** [comment]
FWIW, this would be clunky to user-patch, because the viewport affects the touch translation.

(But it would technically be feasible, Android does something like it to toggle the native status bar).

**Comment by konos93** [comment]
is there any way to check any logs?
i can't restart and can't use the backup
based on this https://github.com/koreader/koreader/issues/4810#issuecomment-473582136 i made some changes. the result is the image below. if i restart the device or koreader the image is the new screen size remain the same.

did something like 

cd koreader/frontend/device/kindle/
cp device.lua backup.device.lua.backup
nano device.lua 

![image](https://github.com/user-attachments/assets/731d479d-9429-47f4-8126-c6320e9a10cc)

**Comment by NiLuJe** [comment]
Looks like you reduced the height without moving the origin? (i.e., any amount subtracted from height should be added to top/y).

**Comment by konos93** [comment]
koreader/frontend/device/pocketbook


```bash
-- PocketBook InkPad Color 3 (743K3)
local PocketBook743K3 = PocketBook:extend{
    model = "PBInkPadColor3",
    display_dpi = 300,
    viewport = Geom:new{x=3, y=2, w=1395, h=1864},
    hasColorScreen = yes,
    canHWDither = yes, -- Adjust color saturation with inkview
    canUseCBB = no, -- 24bpp
    isAlwaysPortrait = yes,
    usingForcedRotation = landscape_ccw,
    hasNaturalLight = yes,
}
```

**Comment by hius07** [comment]
> ```shell
> viewport = Geom:new{x=3, y=2, w=1395, h=1864},
> ```

Original screen size 1404x1872.
So you need smth about y=350, h=1520.

**Comment by konos93** [comment]
personal notes 
 i need to edit 
F:\applications\koreader\frontend\device\pocketbook

-- PocketBook InkPad 3 (740)
--this is what i need to edit

local PocketBook740 = PocketBook:extend{
    model = "PBInkPad3",
    display_dpi = 300,
    isAlwaysPortrait = yes,
    usingForcedRotation = landscape_ccw,
    hasNaturalLight = yes,
   viewport = Geom:new{x=3, y=2, w=1395, h=1864},
}

**Comment by konos93** [comment]
```bash
}

-- PocketBook InkPad 3 (740)
--here we are
--    viewport = Geom:new{x=3, y=2, w=350, h=1520},
-- w =1404 which is the same
-- x=0
-- y=350
-- h=1520.
-- so a 1872 >= y+h
--i got an error with y=400 and h = 1500

local PocketBook740 = PocketBook:extend{
    model = "PBInkPad3",
    display_dpi = 300,
    isAlwaysPortrait = yes,
    usingForcedRotation = landscape_ccw,
    hasNaturalLight = yes,
    viewport = Geom:new{x=0, y=560, w=1404, h=1304},
}
```
![0-02-05-7bcbe440d483fc752cfaf6c7671ad0a067d5c6fe789bc0e042d2a82ff73e2530_e461a9b407f7f0e8](https://github.com/user-attachments/assets/64660d13-b28e-4d0c-b8de-fa067d4ed0a7)

i love the internet and the fact that i could edit it 

thank you
