### ISSUE TITLE
Android based Xiaomi 7 Reader page turn buttons inverted

### ISSUE THREAD

**Issue by jkl16** [koreader/koreader#12423]
* KOReader version: [v2024.07](https://github.com/koreader/koreader/releases/tag/v2024.07)
* Device: Xiaomi 7 Reader (rk3566_eink)

#### Issue

Xiaomi 7 Reader has asymmetrical (Kindle Oasis style) physical page turn buttons on the right-hand side of the screen.

![xiaomi7](https://github.com/user-attachments/assets/a9601103-a213-4178-aab4-fdc628cff575)

When the device is in up-right portrait position, buttons are triggering key events 24 & 25 which are handled correctly (upper button results in page back, lower button in page forward).

https://github.com/koreader/koreader/blob/f3005906d4236fa234a789b8e62df4ea7ed1dcea/frontend/device/android/event_map.lua#L15-L16

However when the device is upside down, buttons which are now on the left-hand side are triggering inverted key events. The upper button triggers 24 and the lower triggers 25, meaning that system is doing some kind of translation based on the rotation state of the device.

The issue is that KOReader is doing another translation of his own and now event 24 (upper button) results in page forward, event 25 (lower button) in page back, which is counterintuitive.

Is there a way to disable that translation in KOReader for Android devices with physical buttons?

#### Steps to reproduce

- Turn device upside down.
- Press lower physical page turn button.

**Expected**: page turn forward.
**Actual**: page turn back.

**Comment by jkl16** [comment]
I will try to address the issue myself, but I would like to ask for help with figuring out where the logic related to switching button behaviour based on the rotation is located in the code.
Would it be this repository or rather https://github.com/koreader/android-luajit-launcher for Android based devices?

**Comment by Frenzie** [comment]
That's normally handled by Android itself. Is there a specific reason you say KOReader is doing a rotation rather than the device failing to do one?

**Comment by pazos** [comment]
Regular android devices don't support "media keys follow gravity". Some custom roms do (ie: LineageOS) and I'm fairly sure it is somehow hardcoded on some eink devices as well.

On those devices android indeed does its thing and KOReader reverses that. 
There're user-patches available to avoid KOReader to mess with key layout on orientation.
