### ISSUE TITLE
Custom background is not working on the book level

### ISSUE THREAD

**Issue by edo-jan** [koreader/koreader#12420]
* KOReader version: 2024-07
* Device: WSL (Windows Subsystem Linux)

#### Issue
My intent is to use custom bagrounds on a book by book basis.
Custom image backgrounds do work globally (for all books) when the following line pointing to an image file `["cre_background_image"] = "/home/user/.config/koreader/styletweaks/Book10.jpg",`
is added to settings.reader.lua
However, the same line doesn't produce the desired result when added to the .sdr (metadata file) for the given book

#### Steps to reproduce
1. Put a background image file to "/home/user/.config/koreader/styletweaks/ directory
2. Add '["cre_background_image"] = "/home/user/.config/koreader/styletweaks/Book10.jpg",` line to the book metadata file in the book's .sdr folder 
3. Start Koreader => book background is not changed

**Comment by edo-jan** [comment]
> Because we nowhere advertise this works :) and there is no code that handle that setting taken form the document settings (metadata.epub.lua). 
> 
ah, now it makes sense 🫣

> 
You could probably user-patch the :onReadSettings() of one of our apps/reader/modules, but you'd still have the need to manually add this in the metadata.epub.lua of all your books.
> 
not sure exactly how... any tips would be much appreciated!

> Might also be easier to just use a "user style-tweak", something like:
> 
> ```css
> body {
> background-image: url("data:image/jpeg;base64,/9j/4AA.....==");
> }
> ```
What would be the exact url though?  I placed the image file into "/home/user/.config/koreader/styletweaks/Book10.jpg"
Also, since the settings.reader.lua has been modified with `["cre_background_image"] =....` none of the user style tweaks seem to work. Is this expected behavior?

**Comment by Frenzie** [comment]
>  I placed the image file into "/home/user/.config/koreader/styletweaks/Book10.jpg"

You're saying that didn't work?

**Comment by edo-jan** [comment]
> > I placed the image file into "/home/user/.config/koreader/styletweaks/Book10.jpg"
> 
> You're saying that didn't work?

It did not

**Comment by poire-z** [comment]
> What would be the exact url though? I placed the image file into "/home/user/.config/koreader/styletweaks/Book10.jpg"

I have no idea if crengine would go looking into a folder on the device, when you are reading an EPUB, and what crengine consider the root (from where it looks up paths) is the root of the EPUB container.
That's why I suggested using  a `url("data:image/jpeg;base64,/9j/4AA...` where the url contains the image encoded as base64, and the CSS is all standalone, not needing an external jpeg.
So, you need to convert your favorite image into such a url, which you can do manually if you know how, or by using online services like: https://ezgif.com/image-to-datauri
 
> Also, since the settings.reader.lua has been modified with ["cre_background_image"] =.... none of the user style tweaks seem to work. Is this expected behavior?

none of the "style tweaks" = all those in our menu ? or just the "user style tweaks" (your files created in koreader/styletweaks, assuming you knew about that before I mentionned it above) ?
Or only those touching colors ? I have no idea which take precedence between cre_background_image and CSS (I would expect CSS overrides any cre_background_image).
So, not sure what you're saying or what the behaviour you see is - but it doesn't sound expected :)

**Comment by poire-z** [comment]
Sample: [body_bg_image.css.txt](https://github.com/user-attachments/files/16787736/body_bg_image.css.txt) from: ![tx_old_paper](https://github.com/user-attachments/assets/23ea5d83-8084-46fa-b2af-d1834c13b07c)

**Comment by edo-jan** [comment]
@poire-z  Thanks you very much!  🍾🥂 This worked (and yes it overrides the image referenced in settings.reader.lua)

**Comment by poire-z** [comment]
The ["cre_background_image"] trick would still be preferred.

I noticed a side effect when using the CSS: hanging punctuation (ie. the hyphens on the right here) is no longer ensured:
![image](https://github.com/user-attachments/assets/5eafcb2a-1a31-400b-a93b-b6e3003ba4a4)
![image](https://github.com/user-attachments/assets/c3a68a50-6949-4562-8dbb-4a3b020b6bd4)

I remember there is some code to check if hanging would go put glyphs in some border (and/or outer background), so when some things are detected, we don't hang.

**Comment by edo-jan** [comment]
> The ["cre_background_image"] trick would still be preferred.
> 
> I noticed a side effect when using the CSS: hanging punctuation (ie. the hyphens on the right here) is no longer ensured: !

I agree.  If the ["cre_background_image"] trick worked on the book level it would make things so much easier!

**Comment by poire-z** [comment]
Given that this "feature" is not really documented, and even allowing it for a per-document setting would need people to edit their setting by hand, it's best to left this to a user patch.
And while at it, you could have it as a menu item (with a single hardcoded image path):
[2-cre-background-image-per-book.lua.txt](https://github.com/user-attachments/files/16825467/2-cre-background-image-per-book.lua.txt)

```lua
local ReaderRolling = require("apps/reader/modules/readerrolling")
local UIManager = require("ui/uimanager")

local MY_IMAGE = "/path/to/your//bg_paper1.jpg"

ReaderRolling_orig_addToMainMenu = ReaderRolling.addToMainMenu
ReaderRolling.addToMainMenu = function(self, menu_items)
    ReaderRolling_orig_addToMainMenu(self, menu_items)
    menu_items.toggle_vertical_hack =  {
        sorting_hint = "typeset",
        text = "Use my background image",
        checked_func = function()
            return self.ui.doc_settings:isTrue("use_my_background_image")
        end,
        callback = function(touchmenu_instance)
            self.ui.doc_settings:flipNilOrFalse("use_my_background_image")
            if self.ui.doc_settings:isTrue("use_my_background_image") then
                self.ui.document:setBackgroundImage(MY_IMAGE)
            else
                self.ui.document:setBackgroundImage()
            end
            UIManager:setDirty(self.view.dialog, "partial")
        end,
    }
end


ReaderRolling_orig_onReadSettings = ReaderRolling.onReadSettings
ReaderRolling.onReadSettings = function(self, ...)
    ReaderRolling_orig_onReadSettings(self, ...)
    if self.ui.doc_settings:isTrue("use_my_background_image") then
        self.ui.document:setBackgroundImage(MY_IMAGE)
    else
        self.ui.document:setBackgroundImage()
    end
end
```

**Comment by edo-jan** [comment]
> Given that this "feature" is not really documented, and even allowing it for a per-document setting would need people to edit their setting by hand, it's best to left this to a user patch. And while at it, you could have it as a menu item (with a single hardcoded image path): [2-cre-background-image-per-book.lua.txt](https://github.com/user-attachments/files/16825467/2-cre-background-image-per-book.lua.txt)
> 
@poire-z 
Thanks for the user patch! It works. However, with different types books I like using different backgrounds. I wonder if you could mod this so that so that one could create 2 or three user patches each pointing to its own image and show in the menu as "Use my background image1", "Use my background image2", etc. ?

**Comment by poire-z** [comment]
Well, it's feasible, try first by yourself, duplicate things, copy paste some lines, change some names to have a `2` and `3` suffix.

**Comment by edo-jan** [comment]
I tried changing it, using a suffix "1" for but my books no longer loads with the following error:
![2024-08-31_181904](https://github.com/user-attachments/assets/f9f970c0-861e-4c55-80d4-302249973598)

here is the my changes in the copied user patch that are causing the error 😟

```
local ReaderRolling = require("apps/reader/modules/readerrolling")
local UIManager = require("ui/uimanager")

local MY_IMAGE = "/home/edoj/.config/koreader/styletweaks/Book5c.jpg"

ReaderRolling_orig_addToMainMenu = ReaderRolling.addToMainMenu
ReaderRolling.addToMainMenu = function(self, menu_items)
    ReaderRolling_orig_addToMainMenu(self, menu_items)
    menu_items.toggle_vertical_hack =  {
        sorting_hint = "typeset",
        text = "Use my background image1",
        checked_func = function()
            return self.ui.doc_settings:isTrue("use_my_background_image1")
        end,
        callback = function(touchmenu_instance)
            self.ui.doc_settings:flipNilOrFalse("use_my_background_image1")
            if self.ui.doc_settings:isTrue("use_my_background_image1") then
                self.ui.document:setBackgroundImage(MY_IMAGE)
            else
                self.ui.document:setBackgroundImage()
            end
            UIManager:setDirty(self.view.dialog, "partial")
        end,
    }
end


ReaderRolling_orig_onReadSettings = ReaderRolling.onReadSettings
ReaderRolling.onReadSettings = function(self, ...)
    ReaderRolling_orig_onReadSettings(self, ...)
    if self.ui.doc_settings:isTrue("use_my_background_image1") then
        self.ui.document:setBackgroundImage(MY_IMAGE)
    else
        self.ui.document:setBackgroundImage()
    end
end
```

**Comment by poire-z** [comment]
```lua
local MY_IMAGE1 = "/path/to/your//bg_paper1.jpg"
local MY_IMAGE2 = "/path/to/your//bg_paper2.jpg"

ReaderRolling_orig_addToMainMenu = ReaderRolling.addToMainMenu
ReaderRolling.addToMainMenu = function(self, menu_items)
    ReaderRolling_orig_addToMainMenu(self, menu_items)
    menu_items.my_background_image1 =  {
        sorting_hint = "typeset",
        text = "Use my background image 1",
        checked_func = function()
            return self.ui.doc_settings:isTrue("use_my_background_image1")
        end,
        callback = function(touchmenu_instance)
            self.ui.doc_settings:flipNilOrFalse("use_my_background_image1")
            if self.ui.doc_settings:isTrue("use_my_background_image1") then
                self.ui.document:setBackgroundImage(MY_IMAGE1)
            else
                self.ui.document:setBackgroundImage()
            end
            UIManager:setDirty(self.view.dialog, "partial")
        end,
    }
    menu_items.my_background_image2 =  {
        sorting_hint = "typeset",
        text = "Use my background image 2",
        checked_func = function()
            return self.ui.doc_settings:isTrue("use_my_background_image2")
        end,
        callback = function(touchmenu_instance)
            self.ui.doc_settings:flipNilOrFalse("use_my_background_image2")
            if self.ui.doc_settings:isTrue("use_my_background_image2") then
                self.ui.document:setBackgroundImage(MY_IMAGE2)
            else
                self.ui.document:setBackgroundImage()
            end
            UIManager:setDirty(self.view.dialog, "partial")
        end,
    }
end


ReaderRolling_orig_onReadSettings = ReaderRolling.onReadSettings
ReaderRolling.onReadSettings = function(self, ...)
    ReaderRolling_orig_onReadSettings(self, ...)
    if self.ui.doc_settings:isTrue("use_my_background_image1") then
        self.ui.document:setBackgroundImage(MY_IMAGE1)
    elseif self.ui.doc_settings:isTrue("use_my_background_image2") then
        self.ui.document:setBackgroundImage(MY_IMAGE2)
    else
        self.ui.document:setBackgroundImage()
    end
end
```
Untested, but I hope you'll get the idea how to add a background image 3.

And check your crash.log for the explicte reason of any crash or error.

**Comment by edo-jan** [comment]
@poire-z Thanks a lot!
FYI,  I asked ChatGPT and it failed miserably. However, Claude produced a working code which is spooking similar to yours 
Check it out:
```
local ReaderRolling = require("apps/reader/modules/readerrolling")
local UIManager = require("ui/uimanager")
local MY_IMAGE_A = "/home/edoj/.config/koreader/styletweaks/Book6a.jpg"
local MY_IMAGE_B = "/home/edoj/.config/koreader/styletweaks/Book6b.jpg"

ReaderRolling_orig_addToMainMenu = ReaderRolling.addToMainMenu
ReaderRolling.addToMainMenu = function(self, menu_items)
    ReaderRolling_orig_addToMainMenu(self, menu_items)
    menu_items.toggle_background_a = {
        sorting_hint = "typeset",
        text = "Use background image A",
        checked_func = function()
            return self.ui.doc_settings:isTrue("use_background_image_a")
        end,
        callback = function(touchmenu_instance)
            self.ui.doc_settings:flipNilOrFalse("use_background_image_a")
            if self.ui.doc_settings:isTrue("use_background_image_a") then
                self.ui.document:setBackgroundImage(MY_IMAGE_A)
                self.ui.doc_settings:saveSetting("use_background_image_b", false)
            else
                self.ui.document:setBackgroundImage()
            end
            UIManager:setDirty(self.view.dialog, "partial")
        end,
    }
    menu_items.toggle_background_b = {
        sorting_hint = "typeset",
        text = "Use background image B",
        checked_func = function()
            return self.ui.doc_settings:isTrue("use_background_image_b")
        end,
        callback = function(touchmenu_instance)
            self.ui.doc_settings:flipNilOrFalse("use_background_image_b")
            if self.ui.doc_settings:isTrue("use_background_image_b") then
                self.ui.document:setBackgroundImage(MY_IMAGE_B)
                self.ui.doc_settings:saveSetting("use_background_image_a", false)
            else
                self.ui.document:setBackgroundImage()
            end
            UIManager:setDirty(self.view.dialog, "partial")
        end,
    }
end

ReaderRolling_orig_onReadSettings = ReaderRolling.onReadSettings
ReaderRolling.onReadSettings = function(self, ...)
    ReaderRolling_orig_onReadSettings(self, ...)
    if self.ui.doc_settings:isTrue("use_background_image_a") then
        self.ui.document:setBackgroundImage(MY_IMAGE_A)
    elseif self.ui.doc_settings:isTrue("use_background_image_b") then
        self.ui.document:setBackgroundImage(MY_IMAGE_B)
    else
        self.ui.document:setBackgroundImage()
    end
end 
```
We live in interesting times indeed...

**Comment by poire-z** [comment]
Scary indeed :/

**Comment by edo-jan** [comment]
@poire-z  I wonder if this thread should labeled with "user patch available" tag? I probably don't have permissions to do this

**Comment by thinha4k11** [comment]
Is there a way to display a semi-transparent or PNG texture over the entire KOReader interface on an Android e-ink eReader, such as a Boox device? Thanks.

**Comment by thinha4k11** [comment]
Is there a way to display a semi-transparent or PNG texture over the entire KOReader interface on an Android e-ink eReader, such as a Boox device? I know this can be annoying but if possible please help me, I'm haunted by the uneven backlighting :(. Thanks.

**Comment by thinha4k11** [comment]
@poire-z Please help me, thank you.

**Comment by poire-z** [comment]
> Is there a way to display a semi-transparent or PNG texture over the entire KOReader interface on an Android e-ink eReader, such as a Boox device? I know this can be annoying but if possible please help me, I'm haunted by the uneven backlighting :(.

No.
I guess your request in https://github.com/koreader/koreader/discussions/14565 is related, and that you went ok with that user patch.

**Comment by starstart426** [comment]
> Given that this "feature" is not really documented, and even allowing it for a per-document setting would need people to edit their setting by hand, it's best to left this to a user patch. And while at it, you could have it as a menu item (with a single hardcoded image path): [2-cre-background-image-per-book.lua.txt](https://github.com/user-attachments/files/16825467/2-cre-background-image-per-book.lua.txt)

@poire-z  Thanks for the user patch!
Is it possible to disable the full screen refresh every time a page is turned? I enabled the “Avoid mandatory black flashes in UI” and I disabled “Always flash on pages with images” options, but the full refresh still happens. Sorry to bother you with this again.

**Comment by poire-z** [comment]
Doesn't <img width="247" height="108" alt="Image" src="https://github.com/user-attachments/assets/cc76b8e3-f78e-456e-a943-13f932d0ee91" /> work ?

**Comment by thinha4k11** [comment]
@starstart426 I have used many devices from many brands, I have gained experience about screen flickering when using the wallpaper change feature.
On Kobo and Boox, the flickering is low (or very low, almost does not affect the reading experience). Kobo is better in this case.
On devices from other brands, the screen will still flicker completely (even though all screen refresh options are turned off), almost unable to use the patch because it is very uncomfortable for the eyes.

**Comment by starstart426** [comment]
> Doesn't work ?

Unfortunately, it doesn't work. With the user patch active, this option is ignored.

**Comment by starstart426** [comment]
> On devices from other brands, the screen will still flicker completely (even though all screen refresh options are turned off), almost unable to use the patch because it is very uncomfortable for the eyes.

I'm using a Paperwhite 12th. Enabling the page animation option helps a little, but it's still uncomfortable.

**Comment by poire-z** [comment]
Are you sure it is really a full refresh ?
On eInk (at least on my old Kobo Glo HD), as soon as there is some grey (neither solid black or solid white), the eInk hardware draws it from white to black and then to gray (so it actually looks like it is flashing).
There's nothing we can do about that (except not using gray :)).
Try (just for confirming) with a pure black and white images (ie. some b & w grid: <img width="119" height="133" alt="Image" src="https://github.com/user-attachments/assets/8f077208-f833-438c-9783-9ff1abd1215c" /> that you can probably find on Google images)

**Comment by starstart426** [comment]
> Are you sure it is really a full refresh ? On eInk (at least on my old Kobo Glo HD), as soon as there is some grey (neither solid black or solid white), the eInk hardware draws it from white to black and then to gray (so it actually looks like it is flashing). There's nothing we can do about that (except not using gray :)). Try (just for confirming) with a pure black and white images (ie. some b & w grid: <img alt="Image" width="119" height="133" src="https://private-user-images.githubusercontent.com/24273478/512820257-8f077208-f833-438c-9783-9ff1abd1215c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI4OTAwMTYsIm5iZiI6MTc2Mjg4OTcxNiwicGF0aCI6Ii8yNDI3MzQ3OC81MTI4MjAyNTctOGYwNzcyMDgtZjgzMy00MzhjLTk3ODMtOWZmMWFiZDEyMTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTExVDE5MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNmQxMzM5NGNlYzdjODc0YjQ4NTY2OGM4ZTg3NjYwNzAwZjQ0NjE3MzA2ODNlZDZjYWZkYzE2ZjhjNTViMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wdldkmkONMpr4-sIY6wXG-41yBbvLA62J5CCzeysO2o"> that you can probably find on Google images)

Thank you! That confirms that it is **not** a full refresh, even though the way the screen flickers is the same as a full refresh.
