### ISSUE TITLE
Kindle 4 - Buttons don't work for navigating

### ISSUE THREAD

**Issue by Eagle221** [koreader/koreader#12428]
* KOReader version: KOReader 2024.07 "Outside"
* Device: Kindle 4 NT Silver (2011)

Buttons don't work. I'm always stuck on the first page of the manga and can't move on to the next, left and right buttons simply don't work.

**Comment by Commodore64user** [comment]
left and right move through chapters, if they "don't work" is because your file does not contain chapters. Furthermore, what do you mean you can't change pages? you have two sets of buttons at either side of the screen that do just that.

**Comment by NiLuJe** [comment]
You might want to try a current nightly, there might have been an input classification issue on that device in the release that prevented the page turn button from being handled.

**Comment by Commodore64user** [comment]
> there might have been an input classification issue on that device in the release that prevented the page turn buttons from being handled.

wait, what is this all about? my k4 was fine on 2024.07, page turning wise (PDF and ePubs).

**Comment by Eagle221** [comment]
Nevermind, I'm silly. Just got my Kindle yesterday and didn't even realize there were buttons at the edges of the device. Thank you all.

**Comment by Darthagnon** [comment]
Related: [#12168](https://github.com/koreader/koreader/issues/12168) - release 2024.7 changed the behaviour of the Dpad to navigate chapters rather than pages. This behaviour is more inline with the vanilla Kindle 4 reader software, but a radical departure from KOReader's previous controls. 

The changelog for release 2024.11 lists this issue as fixed.

**Comment by Commodore64user** [comment]
> This behaviour is more inline with the vanilla Kindle 4 reader software, but a radical departure from KOReader's previous controls.


Mate, we are not a Shakespeare play, tone down the drama. We have already accommodated your personal preference (left/right turning pages), if you think that using buttons for anything else than page turning is such a terrible idea, you are not going to be happy with Hotkeys either.

Furthermore, OP's issue was that he hadn't realised that there are dedicated page turn buttons. Case closed.
