### ISSUE TITLE
FR: Direct access to the color menu from the highlight control.

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#12439]
Currently, to change the color you have to go through the style menu. An additional step.

Can't we just allow the color selector to be accessed directly from the highlight controls?

**Comment by hius07** [comment]
lol https://github.com/koreader/koreader/pull/11044#issuecomment-1785863758

**Comment by uroybd** [comment]
> lol https://github.com/koreader/koreader/pull/11044#issuecomment-1785863758

I agree with that in most cases. However, different colors in highlights means more context for me once exported. I believe style and color should be of the same priority in the menu.

**Comment by hius07** [comment]
The button is simple.
The hard question is where to place it?

**Comment by uroybd** [comment]
> The button is simple.
> The hard question is where to place it?

Right beside the style button perhaps?

Yes, there will be 5 buttons on the top row and 4 on the bottom...

**Comment by uroybd** [comment]
And the color button can be a square button showing only the color.

**Comment by hius07** [comment]
6 maybe

![1](https://github.com/user-attachments/assets/16a5b315-1dc4-43f3-853b-1e45f8e4024c)

**Comment by poire-z** [comment]
We also have the solution to use a popup, it would just be another tap nor far away:
![image](https://github.com/user-attachments/assets/e81ffc4a-691f-4e88-856c-1bc368f8c8e1)

**Comment by uroybd** [comment]
> 6 maybe
> 
> ![1](https://github.com/user-attachments/assets/16a5b315-1dc4-43f3-853b-1e45f8e4024c)
> 

This is nice!

**Comment by uroybd** [comment]
> We also have the solution to use a popup, it would just be another tap nor far away:
> ![image](https://github.com/user-attachments/assets/e81ffc4a-691f-4e88-856c-1bc368f8c8e1)
> 

Considering tap count (and that is the reason I asked for the direct access) is this same to the currant implementation?

**Comment by poire-z** [comment]
We also have to think about uglyness vs. your tap count economy :)
English has small words, so it looks only a bit ugly with 6 items.
In other languages, it may look uglier.

**Comment by uroybd** [comment]
> We also have to think about uglyness vs. your tap count economy :)
> English has small words, so it looks only a bit ugly with 6 items.
> In other languages, it may look uglier.

Ugliness is a legit concern.

A second route can be to merge style and color dialogue in one unified style dialog.

Maybe in two rows.

4 styles in two rows first, then a divider line, then 2 rows of colors. Users can select the combination in one go.

**Comment by hius07** [comment]
Go mysterious way;

![2](https://github.com/user-attachments/assets/f7606c5d-36ba-4339-bfcc-c4af9cce2af5)

**Comment by uroybd** [comment]
> Go mysterious way;
> 
> ![2](https://github.com/user-attachments/assets/f7606c5d-36ba-4339-bfcc-c4af9cce2af5)
> 

This is nicer!

**Comment by poire-z** [comment]
It would be a first :) we're usually not that mysterious.
But I guess I wouldn't mind that:
except for Delete, whose icon is quite explicite, the others (I think?) don't do any action directly, and open dialogs that may be explicite enough to explain what they allow, and are easily dismissable without causing any change.

But I also wonder about the need for the color button/icon on B&W devices. I know it's in the menu (because people with multiple devices, or wanting to set the color for the export or embedding in a pdf), but it may feel just unuseful and bothering on B&W devices where we won't see any feedback (cf. my prophecy).

**Comment by Frenzie** [comment]
It could simply be dependent on the color rendering toggle. (Granted, it's not made available on all devices.)

**Comment by NiLuJe** [comment]
Stupid idea is stupid: do we deal with long-taps on these buttons? Logn-tap on style to color, then?

**Comment by Frenzie** [comment]
Seems a bit obscure for color devices, but probably fine for b&w if you really want to access it.

**Comment by uroybd** [comment]
> Stupid idea is stupid: do we deal with long-taps on these buttons? Long-tap on style to jump to color, then? (It's... mysterious, but in a way we're used to ;D).

In that case allow the current route to colors also. So that unassuming users can still access them even if they don't know about the long tap.

**Comment by uroybd** [comment]
Meanwhile, anyone who wants to set colors directly can use this user patch: https://gist.github.com/uroybd/1f9af11fdf0bba6c6c7e728eaded4833

**Comment by theboomr** [comment]
> Currently, to change the color you have to go through the style menu. An additional step.
> 
> Can't we just allow the color selector to be accessed directly from the highlight controls?

Um, wait, Koreader has color highlighting? Sorry this isn't directly related to this issue but, is this feature device-specific? I have color rendering enabled on my Pocketbook Era Color, but I do not have any color options when I go into the Style sub-menu.

Or is this a feature that's only in nightly builds at the moment?

**Comment by NiLuJe** [comment]
> Or is this a feature that's only in nightly builds at the moment?

^ This.
