### ISSUE TITLE
FR: Add color in the JSON export

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#12436]
A recent PR introduced a highlight colour. Can we get the colour value in the JSON export of the highlights?

I would've liked to contribute to the feature myself. But, currently, I don't have a Linux machine and can't get to run KOreader on my Macbook (M1 Pro). :-(

**Comment by benoit-pierre** [comment]
> I would've liked to contribute to the feature myself. But, currently, I don't have a Linux machine and can't get to run KOreader on my Macbook (M1 Pro). :-(

What's the issue?

**Comment by uroybd** [comment]
> > I would've liked to contribute to the feature myself. But, currently, I don't have a Linux machine and can't get to run KOreader on my Macbook (M1 Pro). :-(
> 
> What's the issue?

All the `kodev` commands return this:

```
make TARGET= KODEBUG=1 VERBOSE= clean
awk: can't open file BEGIN { print (LR_VER_NUM >= 3.0); }
 source line number 1
************ CMAKE_MAKE_PROGRAM: "/opt/homebrew/bin/ninja" **********
************ Building for MACHINE: "-debug" **********
************ PATH: "/Users/meghnaad/.local/state/fnm_multishells/19167_1725082000383/bin:/opt/homebrew/opt/util-linux/bin:/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/opt/gnu-getopt/bin:/opt/homebrew/findutils/libexec/gnubin:/Users/meghnaad/.pyenv/shims:/Users/meghnaad/.local/bin:/Users/meghnaad/.cargo/bin:/Users/meghnaad/.bun/bin:/Users/meghnaad/.fnm:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/Users/meghnaad/.local/state/fnm_multishells/15786_1725078743436/bin:/opt/homebrew/opt/util-linux/bin:/opt/homebrew/opt/make/libexec/gnubin:/opt/homebrew/opt/gnu-getopt/bin:/opt/homebrew/findutils/libexec/gnubin:/Users/meghnaad/.pyenv/shims:/Users/meghnaad/.local/bin:/Users/meghnaad/.cargo/bin:/Users/meghnaad/.bun/bin:/Users/meghnaad/.fnm:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/Users/meghnaad/.local/state/fnm_multishells/15757_1725078719332/bin:/Users/meghnaad/.local/state/fnm_multishells/13996_1725078179132/bin:/Users/meghnaad/.pyenv/shims:/Users/meghnaad/.local/bin:/Users/meghnaad/.cargo/bin:/Users/meghnaad/.bun/bin:/Users/meghnaad/.fnm:/opt/homebrew/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/iTerm.app/Contents/Resources/utilities" **********
************ CHOST: "" **********
base/Makefile:62: warning: overriding recipe for target 'all'
Makefile:75: warning: ignoring old recipe for target 'all'
base/Makefile:249: warning: overriding recipe for target 'clean'
Makefile:143: warning: ignoring old recipe for target 'clean'
base/Makefile:253: warning: overriding recipe for target 'distclean'
Makefile:146: warning: ignoring old recipe for target 'distclean'
base/Makefile:1: Makefile.defs: No such file or directory
make: *** No rule to make target 'Makefile.defs'.  Stop.
```

**Comment by uroybd** [comment]
In docker, I'm just getting this:

```
************ CMAKE_MAKE_PROGRAM: "/usr/bin/ninja" **********
base/Makefile:1: Makefile.defs: No such file or directory
************ Building for MACHINE: "-debug" **********
************ PATH: "/home/ko/x-tools/*/bin:/home/ko/.luarocks/bin:/home/ko/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" **********
************ CHOST: "" **********
base/Makefile:62: warning: overriding recipe for target 'all'
Makefile:75: warning: ignoring old recipe for target 'all'
base/Makefile:223: Makefile.third: No such file or directory
base/Makefile:249: warning: overriding recipe for target 'clean'
Makefile:143: warning: ignoring old recipe for target 'clean'
base/Makefile:253: warning: overriding recipe for target 'distclean'
Makefile:146: warning: ignoring old recipe for target 'distclean'
make: *** No rule to make target 'Makefile.third'.  Stop.
```

**Comment by benoit-pierre** [comment]
OK, first, for developing you can probably use the latest [Github Actions artifact](https://github.com/koreader/koreader/actions/runs/10638579534), since you would only make change to the Lua code.

For the build issue:
- did you install all the necessary requirements? (see `doc/Building.md`)
- which version of make is that?
- are you submodules up-to-date? (you can use `./kodev fetch-thirdparty` to recursively update all submodules)

**Comment by benoit-pierre** [comment]
Docker would be useful for cross-compiling, but you want to build the emulator, right?

**Comment by uroybd** [comment]
> Docker would be useful for cross-compiling, but you want to build the emulator, right?

Yes. I need to test a few things.

**Comment by uroybd** [comment]
I did a fresh clone and it seems to be progressing.

**Comment by uroybd** [comment]
The emulator works now. However, couldn't open the top menu, even with the keyboard shortcut of F1. Can this be set to anything else since other shortcuts are working fine.

**Comment by hius07** [comment]
Added in https://github.com/koreader/koreader/pull/12431.

**Comment by Frenzie** [comment]
> However, couldn't open the top menu, even with the keyboard shortcut of F1.

By default Mac does things like changing the volume. In that case to activate F1 you need Fn+F1.

**Comment by Frenzie** [comment]
By more typically, just click near the top? ;-)

**Comment by uroybd** [comment]
> > However, couldn't open the top menu, even with the keyboard shortcut of F1.
> 
> By default Mac does things like changing the volume. In that case to activate F1 you need Fn+F1.

I had the settings to directly press the function keys. The problem was elsewhere in the system. I got it working later.

**Comment by uroybd** [comment]
> By more typically, just click near the top? ;-)

There is a problem in that. Whenever I click, it is being registered as a long click and context menus open up.

Anyway, @hius07 got this featured covered. Merging that PR will achieve what I wanted to do.

**Comment by hius07** [comment]
Closed by https://github.com/koreader/koreader/pull/12431.

**Comment by NiLuJe** [comment]
> There is a problem in that. Whenever I click, it is being registered as a long click and context menus open up.

Verbose debug logs, please ;).

**Comment by benoit-pierre** [comment]
@uroybd: ping! Can you open a new dedicated issue with some logs for the click registered as long click issue?
