### ISSUE TITLE
Keep-open QuickMenus not responding to touch

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12447]
* KOReader version: 2024.07-161
* Device: Kobo Aura H2O

#### Issue

Actions on QuickMenus set to 'keep open' can't be executed.

#### Steps to reproduce

Open a QuickMenu that is set to 'keep open'. 
Tap any action – nothing happens.

##### `crash.log` (if applicable)

[crash.log.zip](https://github.com/user-attachments/files/16834791/crash.log.zip)

**Comment by hius07** [comment]
Because of https://github.com/koreader/koreader/pull/12299.
@Frenzie

**Comment by Frenzie** [comment]
I'll take a look later this week.

**Comment by mergen3107** [comment]
Hasn't this been solved by the way?

**Comment by hius07** [comment]
Fixed in https://github.com/koreader/koreader/pull/12534.
