### ISSUE TITLE
Error when opening reconverted books with annotations

### ISSUE THREAD

**Issue by jospalau** [koreader/koreader#12443]
* KOReader version: Last nightly version, v2024.07-160-gd097dc0f8_2024-08-31
* Device: Any

#### Issue
After having reconverted all my books with Calibre, when I open a book sometimes I get a crash:
frontend/apps/reader/modules/readerannotation.lua:245: invalid order function for sorting

The crash has to do with some of the original xpointer in the previous books are not anymore due to the conversion changing them:
09/01/24-12:57:54 WARN  Invalid xpointer in highlight: /body/DocFragment[11]/body/div[340]/text()[1].59 /body/DocFragment[9]/body/div[363]/text().111
09/01/24-12:57:54 WARN  Invalid xpointer in highlight: /body/DocFragment[11]/body/div[340]/text()[1].59 /body/DocFragment[9]/body/div[352]/text().202
09/01/24-12:57:54 WARN  Invalid xpointer in highlight: /body/DocFragment[11]/body/div[340]/text()[1].59 /body/DocFragment[9]/body/div[595]/text().572
[!] doShowReader coroutine crashed:

**Comment by hius07** [comment]
> * KOReader version: Last version

?

**Comment by jospalau** [comment]
v2024.07-160-gd097dc0f8_2024-08-31

**Comment by hius07** [comment]
Unfortunately we cannot restore your highlights within a book.
You can export them from the file browser (via the Select action, wrong page numbers might appear) and then reset the doc settings.

**Comment by jospalau** [comment]
For me is not important. It is something that came up. I will reset doc settings if it comes back again for any book. Something that may not happen. Just if I reread a book, which I rarely do.

**Comment by hius07** [comment]
Thanks, maybe we should take care of such cases, we cannot repair but we can avoid crashes.
For memory, the case was discussed starting from https://github.com/koreader/koreader/issues/12167#issuecomment-2233687828.
