### ISSUE TITLE
German translation error: Physikalische Tasten

### ISSUE THREAD

**Issue by BurkSchu** [koreader/koreader#12455]
* KOReader version: 2024.07
* Device: Doesn't matter

#### Issue
In the menu "Navigation" the german text "Physikalische Tasten" should read "Physische Tasten".

#### Steps to reproduce
In the top menu choose the gear wheel, then Navigation

**Comment by Frenzie** [comment]
You can update it yourself over on https://hosted.weblate.org/projects/koreader/koreader/ btw. :-) (Except not right this very minute because it seems to be down for maintenance.)

**Comment by Frenzie** [comment]
I updated that one.
