### ISSUE TITLE
Tapping on the status bar moves the page to the top.

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12454]
* KOReader version: v2024.07-160
* Device: PB 628

#### Issue
In PDF files, tapping on the status bar to make it appear or disappear also takes us to the top of the page.

**Comment by NiLuJe** [comment]
In what kind of view/zoom modes? And status bar settings, for that matter.

(At a quick glance, can't repro w/ default settings on the emu).

**Comment by hius07** [comment]
Yes, the behaviour of the status bar in pdf has changed.
Previously, turning the status bar off kept its space empty, the text layout didn't change.
Now the text fills the empty space under the status bar. So the page is redrawn, jumping to its beginning.

**Comment by NiLuJe** [comment]
Something like that *should* only happen with reclaim status bar height *disabled* (i.e., the defaults), but I'm not sure it ever reliably did so.

I'm not seeing anything on the emu, so if you have more info about what combination of settings produce this, that could be helpful to pinpoint this (as I don't recall anything recent that should have affected this :?).

**Comment by hius07** [comment]
That's it, no jumping with checked "Overlap status bar".

**Comment by mergen3107** [comment]
I think this was introduced here (see Item 6 in the OP, which then got fixed).
https://github.com/koreader/koreader/issues/9979

**Comment by NiLuJe** [comment]
That's not particularly recent, but, yeah, explains why I had a vague memory of this ;p.

**Comment by ichnilatis-gr** [comment]
> In what kind of view/zoom modes? And status bar settings, for that matter.

It's set to fit width.
I give you below screenshots of the settings.

![Reader_2024-09-03 (Πολύ μικρό)](https://github.com/user-attachments/assets/e67d6a99-f182-416d-a849-03ccc738eea2)

![Reader_2024-09-03 (2) (Πολύ μικρό)](https://github.com/user-attachments/assets/29c88974-d4f8-497d-b209-c51c17cd6501)

![Reader_2024-09-03 (3) (Πολύ μικρό)](https://github.com/user-attachments/assets/8c4f6240-f57b-47bc-ae10-24e413226657)

![Reader_2024-09-03_(4) (Πολύ μικρό)](https://github.com/user-attachments/assets/3f10b113-db66-48ab-b0e0-f0423901868f)

![Reader_2024-09-03_(5) (Πολύ μικρό)](https://github.com/user-attachments/assets/138927d0-9c99-429d-8bdd-63aeed4dee8d)

![Reader_2024-09-03_(6) (Πολύ μικρό)](https://github.com/user-attachments/assets/c853c997-1857-4f71-8d19-9bde78c0b76e)

**Comment by hius07** [comment]
@ichnilatis-gr, check "Overlap status bar" to fix jumping.

**Comment by ichnilatis-gr** [comment]
> @ichnilatis-gr, check "Overlap status bar" to fix jumping.

Thank you, but this doesn't solve the problem, since the bar covers the text, something I don't want.

**Comment by NiLuJe** [comment]
Just to be clear: you've experienced this for a while, this isn't new?

**Comment by NiLuJe** [comment]
And more importantly: are you in scroll mode? Because, IIRC, that's (sort of) the expected behavior in scroll mode (or something, this thing is a nightmare).

**Comment by NiLuJe** [comment]
And just to be clear again: As the above question highlights, I was concerned about zoom/view settings, not status bar settings ;).

**Comment by ichnilatis-gr** [comment]
It's something new. I am in page mode.

> I was concerned about zoom/view settings, not status bar settings ;).

You said "And status bar settings, for that matter."
Excuse me. Could you explain to me what exactly you want from me? Thanks!

**Comment by NiLuJe** [comment]
Whether you're in scroll mode or not, and the rest of the zoom settings ;).

**Comment by NiLuJe** [comment]
> It's something new.

Any clue as to when it started happening?

**Comment by NiLuJe** [comment]
> You said "And status bar settings, for that matter."
> Excuse me. Could you explain to me what exactly you want from me? Thanks!

I was *mostly* concerned about zoom/View settings ;). Status bar was basically only to confirm reclaim and/or all-in-one.

**Comment by ichnilatis-gr** [comment]
> Any clue as to when it started happening?

Nope.

**Comment by ichnilatis-gr** [comment]
> Whether you're in scroll mode or not, and the rest of the zoom settings ;).

I'm in page mode. What are the rest? Sorry for my difficulty in understanding.

**Comment by Commodore64user** [comment]
> > Whether you're in scroll mode or not, and the rest of the zoom settings ;).
> 
> 
> 
> I'm in page mode. What are the rest? Sorry for my difficulty in understanding.

Bottom menu

**Comment by ichnilatis-gr** [comment]
Zoom to content.
(It takes me time, but I finally understand... :-)
