### ISSUE TITLE
Allow assigning "Export Notes" as a gesture

### ISSUE THREAD

**Issue by wrinkledeth** [koreader/koreader#12452]
It would be convenient if "Export all notes in this book / export all notes in your library" could be assigned as a gesture. 

Would this be a possible feature?

**Comment by pazos** [comment]
> It would be convenient if "Export all notes in this book / export all notes in your library" could be assigned as a gesture.

It would be a wonderful contribution :)

> Would this be a possible feature?

Yes. It is very easy to implement but nobody cared yet.

For instance see the calibre.koplugin.

1. configure desired callbacks: https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/main.lua#L28-L57
2. configure dispatcher actions: https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/main.lua#L71-L79
3. register dispatcher actions on plugin init: https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/main.lua#L83

That's it. The same needs to be done on exporter.koplugin.

Contributions very welcome :)
