### ISSUE TITLE
Onyx Boox Page LighControl doesn't work

### ISSUE THREAD

**Issue by oldman63** [koreader/koreader#12464]
* KOReader version: 2024.04 | 2024.07 | 2024.07-131 nightly armv64 version

* Device: Onyx Boox Page with 3.5.3 firmware

Lightcontrol is not working

[test.log](https://github.com/user-attachments/files/16870417/test.log)

**Comment by hugleo** [comment]
Hi,

Permission denied:

08-26 14:39:08.607 W/reader.launche(13574): Accessing hidden method Landroid/onyx/hardware/DeviceController;->setLightValue(II)V (blacklist, reflection, denied)

Please check wiki: https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#light-drivers-permissions

adb shell settings get global hidden_api_policy needs to return 1

**Comment by oldman63** [comment]
> adb shell settings get global hidden_api_policy needs to return 1

Thank you for Tip.

There is a definite improvement, but when I move the brightness or colour temperature slider under KOReader, the device restarts.
