### ISSUE TITLE
FR: Both Word stem & "word form in context" for Vocabulary Builder

### ISSUE THREAD

**Issue by Steven630** [koreader/koreader#12465]
First of all, thank you very much for this wonderful plugin (Vocabulary Builder).  This used to be the "killer feature" of Kindle.  Just a small problem though.  Koreader's vocabulary builder seems to store  whatever the dictionary query is, before combining the previous and next part of the context to form the whole.  This works quite well with English,  where fuzzy search can match different forms of a word (migrate, migrated, migrating etc.) However, when I try to look up korean words,  more often than not, the user has to tweak the query to get a hit.  For non-Korean speakers I will use English as an example. "He migrated to America and got married last year".  If this sentence is rendered in Korean and the user tries to look up "migrated", often there is not a single hit.  So the user has to manually change "migrated" to "migrate" ( The korean original form of a verb and its past tense in the middle of a sentence differ too much for fuzzy search to find a match). If the user chooses to add to VB in the modified lookup, The context would be "He migrate to America and got married last year", with the wrong form and tense. I also hope to export the words to Anki for future review, so getting the original form is necessary because of the need to fill the definition field.

**Possible solution**
A quick and fairly easy solution would be to take the approach of  Kindle's VB where both original word(word stem) and word form in the sentence are stored along with the context sentence.

Word stem: migrate
Word in context: migrated
Context: He migrated to America and got married last year.

When user has to manually tweak the query and do another lookup, the VB should store the second look up as word stem.

This will also be useful even for English words. Because if words are to be exported to Anki, their stems(original forms) will be needed to query the definitions that form the back of a card.

I don't know if I have made myself clear. If it is necessary, I can provide screenshots to clarify.

@weijiuqiao

**Comment by weijiuqiao** [comment]
I will take a look when I get some time.  And screenshots would be great.

**Comment by Steven630** [comment]
> I will take a look when I get some time.  And screenshots would be great.

Thank you for your reply.  I took four screenshots as an example.

![Screenshot_20240905_131243.jpg](https://github.com/user-attachments/assets/d6d317b5-c3fa-44c7-8f5d-f5de8b770902)

![Screenshot_20240905_131525.jpg](https://github.com/user-attachments/assets/0e8712cc-fbf8-4978-964e-533b698f7625)

![Screenshot_20240905_131200.jpg](https://github.com/user-attachments/assets/1882337e-850e-4284-8474-31e017b4a816)

![Screenshot_20240905_131505.jpg](https://github.com/user-attachments/assets/8a38ea26-919a-4677-9908-7cae0e1ea45d)

At the end of the first sentence is두 개를 노려보았다. Here, if I look up the last word (노려보았다), no match is found. 

I have to edit the query and look up  the original form 노려보다(without 았, which indicates past tense here). If I add 노려보다 to VB, the context sentence in VB is gramatically incorrect. But if I just add 노려보았다, the definition is gone when reviewing.  And since I wish to further export the words to Anki,  I have to export all the original forms and use Anki's plugin to fill the definitions. So I will end up having all the "wrong context". 

An improved the behaviour would be when user choose to add 노려보다 to VB( duringthe second look up), the context still shows 노려보았다 exactly as it is in the context.

That's why I recommend three columns in the database: Word stem(노려보다), word form in context (노려보았다) and the original context (the original whole sentence with 노려보았다).

BTW, it will be wonderful to allow the users to set a minimum number of words for the context sentence. Sometimes a context sentence is too short. If a context sentence is only, for example, three words long, VB can capture the sentence proceeding it for more context until the context is long enough. But this is another feature request.

**Comment by weijiuqiao** [comment]
By editing the query do you mean using this button? <img width="129" alt="image" src="https://github.com/user-attachments/assets/b3b44a40-a5ae-469b-b2d7-3a506661f6a8">

**Comment by Steven630** [comment]
> By editing the query do you mean using this button? <img width="129" alt="image" src="https://github.com/user-attachments/assets/b3b44a40-a5ae-469b-b2d7-3a506661f6a8">
> 

Yes, that's what I mean.  

For Korean words users may have to manually edit the query to get a hit.  So another dictionary pop up appears. When I choose to add to vocabulary builder in the second window, it should retain the word form in context rather than the edited query form.

**Comment by weijiuqiao** [comment]
What if someone use it to look up a unrelated word? Is it possible? (asking as I'm not with a device right now)

**Comment by Steven630** [comment]
Editing query may also be necessary for English.

For example:

He boxed the child's ears.

"boxed the child's ears" should be edited to "box ears" or "box someone's ears", depending on the dictionary, to have a match.  

There is going to be a mismatch between the query in the dictionary and the original context.

**Comment by weijiuqiao** [comment]
So someone can use it to look up a totally unrelated word?

**Comment by Steven630** [comment]
> What if someone use it to look up a unrelated word? Is it possible? (asking as I'm not with a device right now)

The current version of the vocabulary builder adds the context and the query anyway.

In the example of "he boxes her ears",  If someone looks up "boxes her ears and" then edits the query to "irrelevant", 

The current version of VB will save as:

irrelevant, he "irrelevant"

The modification of  VB I recommend will save:

irrelevant: he "boxes her ears."

Both contexts are not relevant to the query, but at least we have a real sentence in the modification.

**Comment by Steven630** [comment]
> So someone can use it to look up a totally unrelated word?

Yes,  even in this case, the modification I suggested is preferred. 

Please see my reply above.

**Comment by weijiuqiao** [comment]
Yes you have a point. It might be a bit complex if we also want to fix the other bug that words looked up from the explanation retain the original word's context.

**Comment by Steven630** [comment]
> Yes you have a point. It might be a bit complex if we also want to fix the other bug that words looked up from the explanation retain the original word's context.

So at least let's keep the context "unchanged" regardless of what word is looked up. :-)

**Comment by Steven630** [comment]
Before this issue is closed,  I'd like to mention a potential bug of VB I just noticed.  I am reading a pdf,  looking up words and adding them to VB.  If I add phrases(rather than single words), no context is retained(horizontal dots on the right and show only book names when clicked). Examples are "rough and ready", "par excellence" and so on.

Or shall I open another issue?

@weijiuqiao 

Here are three screenshots:

![IMG_20240906_205200.jpg](https://github.com/user-attachments/assets/5cf78d98-8260-4446-a5b7-9c0b1fe19c5b)

![IMG_20240906_205251.jpg](https://github.com/user-attachments/assets/64624849-beb3-4cd8-9c37-ac946a50e4f8)

![IMG_20240906_205326.jpg](https://github.com/user-attachments/assets/52b4c2f4-c850-414a-9d8e-8e2fb9f670c3)

**Comment by Steven630** [comment]
I have more screenshots to share and will open another issue. Thank you.

**Comment by Steven630** [comment]
> Oh I missed your last comment. We couldn't extract context from scanned pdf so a new issue won't really help...

But when I look up single words in the same scanned PDF, the contexts are there. I think this is a default feature of Koreader to use OCR to look up words in a scanned PDF.

I have opened a new issue #12475

**Comment by Steven630** [comment]
> Oh I missed your last comment. We couldn't extract context from scanned pdf so a new issue won't really help...

The PDF file actually has a text layer along with the scanned images. But this still does not explain why context is extracted for single words but not for phrases.

**Comment by Ceynou** [comment]
The only solution is probably to use yomitan deinflection rules, because fuzzy search is pretty much schizophrenic and you can't only get the relevant results.
