### ISSUE TITLE
Exports to Html do not have extension

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12462]
* KOReader version: v2024.07-160
* Device: PB 628

#### Issue
Exports of highlights to Html files do not have the .html extension and are thus not considered to be supported files.

**Comment by hius07** [comment]
Not only html.
This is because your pdf files give the book title with a trailing space.
You can fix it by setting a custom title.

**Comment by ichnilatis-gr** [comment]
But it wasn't like that.
