### ISSUE TITLE
Highlighting issues

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12473]
* KOReader version: v2024.07-165
* Device: PB 628

#### Issue
In Highlight style settings, choosing "Lighten" and a color other than grey causes a crash.
Also, the highlights are not displayed in the pdf file, if we choose to be saved in it. We can see that they exist in the comments list of the pdf application, but they are not visible in the text.

**Comment by benoit-pierre** [comment]
> Also, the highlights are not displayed in the pdf file, if we choose to be saved in it. We can see that they exist in the comments list of the pdf application, but they are not visible in the text.

In which application? Cf. #12186.

**Comment by ichnilatis-gr** [comment]
"Foxit Pdf Editor Pro" and "PDF-XChange Editor Plus"

**Comment by hius07** [comment]
crash.log

**Comment by benoit-pierre** [comment]
> "Foxit Pdf Editor Pro" and "PDF-XChange Editor Plus"

I don't know about those, but [not all readers work](https://github.com/koreader/koreader/issues/5010#issuecomment-2187721309). What about in Chrome?

**Comment by ichnilatis-gr** [comment]
> crash.log

[crash 2024-9-7.log](https://github.com/user-attachments/files/16917669/crash.2024-9-7.log)

**Comment by hius07** [comment]
It's for @NiLuJe.

**Comment by NiLuJe** [comment]
Oh, I somehow completely missed that there was a crash reported here, thanks for the ping! (I clearly need more sleep, as I did triage this issue, but somehow only remembered the "bake annotations in PDFs thing". Anyyyyway. >_<").

**Comment by NiLuJe** [comment]
@ichnilatis-gr: Err, did you explicitly disable the C blitbuffer in the dev settings?

AFAICT, that's not a color device, so it shouldn't be using the Lua blitter at all...

**Comment by ichnilatis-gr** [comment]
> Err, did you explicitly disable the C blitter in the dev settings ([Tools] > More tools > Dev settings)?

I can't find this option and I didn't migrate the settings form another device. I haven't another.

**Comment by benoit-pierre** [comment]
Some settings are not available when reading a document: go back to the file manager.

**Comment by ichnilatis-gr** [comment]
I have the "Disable C blitter" option checked.

**Comment by NiLuJe** [comment]
You really really shouldn't ;).

Were these settings migrated from another device?

**Comment by mergen3107** [comment]
> I didn't migrate the settings form another device. I haven't another.

It looks like it an accident?

Anyway, @ichnilatis-gr please remove the check mark and try again. Maybe this is enough to fix it

**Comment by NiLuJe** [comment]
Oh, it definitely doesn't crash the C blitter, yeah ;).

**Comment by ichnilatis-gr** [comment]
> You really really shouldn't ;).

I don't even know what C blitter is and what it does... :-)

> Anyway, @ichnilatis-gr please remove the check mark and try again. Maybe this is enough to fix it

I unchecked it, but the highlights are not saved in the pdf file. I can't even see the double line, when I have chosen "Underline".

**Comment by benoit-pierre** [comment]
Again, do they show in Chrome's PDF viewer?

**Comment by ichnilatis-gr** [comment]
The old highlights are visible, but not the ones I made today, after I unchecked the "Disable C blitter" option.

**Comment by hius07** [comment]
What is your setting Cog - Document - Save document (write highlights into PDF)?

Today nightly build, fresh highlights, pdf opened in Chrome:

![1](https://github.com/user-attachments/assets/ca3ffd06-97e8-4066-8f0c-0aee20c5597f)

**Comment by benoit-pierre** [comment]
> I opened it in Chrome browser. I don't have Chrome's PDF viewer.

Yes, that's what I meant, the Chrome browser's builtin PDF viewer (`pdfjs`.

**Comment by NiLuJe** [comment]
The blitter thing was related to the crash, not the pdf thing ;).

**Comment by mergen3107** [comment]
@ichnilatis-gr 
Sorry, I forgot to mention that you need to restart KOReader after unchecking the C blitter thing

**Comment by ichnilatis-gr** [comment]
With v2024.07-172 the highlights are visible in both Chrome and Firefox, but not in any pdf application.

**Comment by ichnilatis-gr** [comment]
Let me add (maybe I should open a new issue) that I had enabled saving highlights in pdf with a prompt, and after I closed a pdf file I was reading in landscape mode, I had the prompt window pop up at that point (part of it off screen).

![FileManager_2024-09-09_140222 (Πολύ μικρό)](https://github.com/user-attachments/assets/f8088c53-ad02-4988-b0e3-5619c09eac33)

**Comment by NiLuJe** [comment]
> (maybe I should open a new issue)

There may already be an existing one, this sounds vaguely familiar ;). (If not, please do, yes).

**Comment by ichnilatis-gr** [comment]
I still (with v2024.07-177) can't see the highlights in the pdf files with a pdf program. Has this actually been fixed?

**Comment by Frenzie** [comment]
Presumably that only refers to the crash then.

**Comment by hius07** [comment]
> can't see the highlights in the pdf files with a pdf program

If you can see them in Chrome, the questions are to the program.

**Comment by ichnilatis-gr** [comment]
> If you can see them in Chrome, the questions are to the program.

Do all the programs have this problem? It wasn't like that before.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/issues/12186#issuecomment-2326335356

**Comment by ichnilatis-gr** [comment]
Even with the latest Adobe Acrobat Reader? Well, let it be so...
