### ISSUE TITLE
App crashes at startup in Android 5.0.2 (Lollipop)

### ISSUE THREAD

**Issue by AllysonD2v** [koreader/koreader#12482]
* KOReader version: 2024.07
* Device: Samsung Galaxy Win2

Issue:
When I upgrade the app to version 2024.07 it crashes at startup. The log shows at the end that the error was due to "Not able to load dynamic library: libs/libwrap-mupdf.so". So I don't know how to fix it, because the version 2024.04 works perfectly. I know that both the device and the Android are old, but I would like to keep up with the updated versions of Koreader (if possible). 

Note: My device is rooted, I can download packages or libraries if needed to fix this issue

Please check the log:
[crash.log](https://github.com/user-attachments/files/16918079/crash.log)

**Comment by NiLuJe** [comment]
Does a current nightly fare any better?

**Comment by NiLuJe** [comment]
(Or is this a dupe or dupe-ish of #12348?)

**Comment by AllysonD2v** [comment]
> (Or is this a dupe or dupe-ish of #12348?)

Yes, maybe. Following the thread you quoted I downloaded the build v2024.07-148 and it worked quite well! No crash, no errors.
