### ISSUE TITLE
doShowReader coroutine crashed

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#12492]
* KOReader version: 2024.07 - 2024.07.172
* Device: kindle voyage, but may be irrelevant to the device model

#### Issue

Cannot open one specific text file, showing "No engine to open the file" then crash. I cannot reproduce the issue on other text files.
The file has been previously opened with notes and bookmarks, since the crash happens in the relevant stack, I think it should matter.

##### `crash.log` (if applicable)

```
[!] doShowReader coroutine crashed:
frontend/apps/reader/modules/readerannotation.lua:245: invalid order function for sorting
stack traceback:
        frontend/apps/reader/modules/readerannotation.lua:245: in function 'sortItems'
        frontend/apps/reader/modules/readerannotation.lua:86: in function 'getAnnotationsFromBookmarksHighlights'
        frontend/apps/reader/modules/readerannotation.lua:211: in function 'migrateToAnnotations'
        frontend/apps/reader/modules/readerannotation.lua:127: in function 'v'
        frontend/apps/reader/readerui.lua:471: in function 'init'
        frontend/ui/widget/widget.lua:46: in function 'new'
        frontend/apps/reader/readerui.lua:688: in function 'doShowReader'
        frontend/apps/reader/readerui.lua:641: in function <frontend/apps/reader/readerui.lua:640>09/08/24-20:21:33 INFO  Restoring user input handling
09/08/24-20:21:59 INFO  UIManager: No dialogs left to show
09/08/24-20:21:59 INFO  Tearing down UIManager with exit code: 0
[ko-input] Closed input device with fd: 12 @ idx: 2 (matched by idx)
[ko-input] Closed input device with fd: 11 @ idx: 1 (matched by idx)
[ko-input] Closed input device with fd: 10 @ idx: 0 (matched by idx)
lipc-wait-event exited normally with status: 0
```

</details>

**Comment by Hzj-jie** [comment]
So I took a look at the relevant functions, and believe the warnings before the stack trace are also useful.

```
CRE: failed reading index from cache file
09/08/24-20:21:33 WARN  Invalid xpointer in highlight: /FictionBook/body/section[205]/p[9]/text().2 /FictionBook/body/section[74]/p[33]/text().44
09/08/24-20:21:33 WARN  Invalid xpointer in highlight: /FictionBook/body/section[153]/p[62]/text().18 /FictionBook/body/section[74]/p[33]/text().44
09/08/24-20:21:33 WARN  Invalid xpointer in highlight: /FictionBook/body/section[74]/p[33]/text().44 /FictionBook/body/section[153]/p[62]/text().18
09/08/24-20:21:33 WARN  Invalid xpointer in highlight: /FictionBook/body/section[74]/p[33]/text().44 /FictionBook/body/section[205]/p[9]/text().2
```

**Comment by hius07** [comment]
The file has changed after the highlights had been made.
There is no way to restore correct xpointers so the only way is to reset doc settings in the file browser (or delete the sdr folder manually).

**Comment by hius07** [comment]
If the highlights (notes) are important, they can be exported via the Select mode in the file browser.

**Comment by Hzj-jie** [comment]
So the crash is actually because of the `return true`  https://github.com/koreader/koreader/blob/adbf3be6ec40872574684688f470e6bf0acb91a8/frontend/apps/reader/modules/readerannotation.lua#L295. In the case of invalid xpointer, I'd expect returning the results of string comparison instead of true which will cause the crash.

**Comment by jospalau** [comment]
[https://github.com/koreader/koreader/issues/12443](url)
