### ISSUE TITLE
Retrieving Wallabag articles cause crashes

### ISSUE THREAD

**Issue by Undomeno** [koreader/koreader#12499]
* KOReader version:
* Device:

#### Issue
Every time I retrieve articles from Wallabag with Wi-Fi disconnected (KOReader would turn the Wi-Fi on), KOReader crashes. If Wi-Fi is connected, then nothing happens.

#### Steps to reproduce
1. Disconnect wifi
2. retrieve articles from wallabag
3. turns wifi on
##### `crash.log` (if applicable)
[crash.log](https://github.com/user-attachments/files/16944822/crash.log)

**Comment by Frenzie** [comment]
It probably shouldn't crash nonetheless, but glad to hear it works. ;-)

**Comment by Frenzie** [comment]
The crash for reference:
```
./luajit: common/socket/http.lua:278: attempt to index local 'schemedefs' (a nil value)
stack traceback:
	[C]: in function 'request'
	plugins/wallabag.koplugin/main.lua:665: in function 'callAPI'
	plugins/wallabag.koplugin/main.lua:455: in function 'getBearerToken'
	plugins/wallabag.koplugin/main.lua:717: in function 'synchronize'
	plugins/wallabag.koplugin/main.lua:1207: in function 'complete_callback'
	frontend/ui/network/manager.lua:1103: in function 'requestToTurnOnWifi'
	frontend/ui/network/manager.lua:321: in function 'enableWifi'
	frontend/ui/network/manager.lua:399: in function 'toggleWifiOn'
	frontend/ui/network/manager.lua:431: in function 'ok_callback'
	frontend/ui/widget/confirmbox.lua:118: in function 'callback'
	frontend/ui/widget/buttontable.lua:81: in function 'callback'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:907: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1436: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1536: in function 'handleInput'
	frontend/ui/uimanager.lua:1580: in function 'run'
	./reader.lua:280: in main chunk
	[C]: at 0x000140cd
```

**Comment by NiLuJe** [comment]
Yeah, LuaSocket really really want t valid `protocol://` prefix to whatever you feed it that should have one ;).

(I hit something similar while working on the PROXY defaults stuff, as I ended up with a leftover proxy set to "foo", which tripped a very similar crash ;)).

**Comment by Frenzie** [comment]
The error message is the same regardless though. I can't immediately reproduce any crash since it happily ignores it (but as stated in the report, that ought to be a connection thing).
