### ISSUE TITLE
FR: Add support android adaptive icon support

### ISSUE THREAD

**Issue by nakibrayan3** [koreader/koreader#12490]
Currently Koreader does not have an adaptive icon, meaning that it does not look consistent on my homescreen where all app icons have the same color scheme and cosistent look.

See this for documentation on adaptive icons:
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by pazos** [comment]
They're adaptative for a few years.AFAICT they can be themed since https://github.com/koreader/android-luajit-launcher/pull/496

**Comment by nakibrayan3** [comment]
I have a colored icon in my phone?!

![Screenshot_20240909_032326_One UI Home](https://github.com/user-attachments/assets/75ab85e9-2395-4f27-b56f-31cd92ccf058)

**Comment by NiLuJe** [comment]
With an fdroid or a github APK? (in case it somehow matters...).

**Comment by Frenzie** [comment]
Perhaps something like night mode requires more than merely adaptive icons?

**Comment by nakibrayan3** [comment]
> With an fdroid or a github APK? (in case it somehow matters...).

I downloaded the apk from github

**Comment by pazos** [comment]
update to a nightly and test again

**Comment by nakibrayan3** [comment]
This build works: https://build.koreader.rocks/download/nightly/v2024.07-172-gadbf3be6e_2024-09-07/koreader-remarkable-v2024.07-172-gadbf3be6e_2024-09-07.zip

Thabk you :)
