### ISSUE TITLE
FR: Automatically applying profile according to book language

### ISSUE THREAD

**Issue by Steven630** [koreader/koreader#12491]
Hello. Wonder if Koreader can  have the features like Kindle's theme.  I read books in three languages and have to switch between them daily.  Chinese, English and Korean all have their suitable fonts and text sizes (even best line space may vary).

Can Koreader allow users to set a default ~~"theme"~~ profile for different languages? For example, when reading Korean the text size is 26, with Batang font; English files have text size 23, with Bookerly font... Koreader should be able to apply the ~~theme~~profile automatically according to the book language in the metadata.

There can be an option to save the ~~theme~~profile as default for a language.

~~Even if most users do not read multiple languages, they can save themes and switch more easily. For example, switching to bigger text sizes and line space at night.~~

It is really inconvenient to change settings every time I switch to a different language (I have news  files in three languages delivered daily).

Thank you.

**Comment by hius07** [comment]
> There can be an option called "theme manager" like the gesture manager, where users can pre-define fonts text sizes et c.

There is, called "Profiles".

**Comment by Frenzie** [comment]
You can also set them up on a per-folder basis so the only manual switch required is to put them in the /English vs the /Batang subfolder. See https://github.com/koreader/koreader/pull/5428

**Comment by Steven630** [comment]
Thank you both. Sorry for not doing my homework.  I will read the user manual sections on profile.

Is there a way for Koreader to switch  profiles automatically according to the language?

**Comment by Frenzie** [comment]
Not currently. But before embarking on such a quest you might also want to double check in book information that these documents actually specify an appropriate language. I strongly suspect most either won't have one at all or one that's nonsensical, but ymmv.

**Comment by Steven630** [comment]
My books and files mostly have correct language metadata.  Otherwise they couldn't be read correctly on Kindle's native system. I just jailbroke my kpw2 to switch to Koreader.  Even though Kindle has themes, I would rather it adjust according to the language automatically. For now, I'll just choose three gestures for my purpose.  Would be great if there is a new automatic feature to do that.
