### ISSUE TITLE
FR: Custom sort installed dictionaries

### ISSUE THREAD

**Issue by Deekee62** [koreader/koreader#12502]
**Does your feature request involve difficulty completing a task? Please describe.**
I've installed quite a few dictionaries, but as I mostly translate from English > German I've to press >> about 6 times until I see the English-German dictionary. 

**Describe the solution you'd like**
It would be nice to ba able to sort the dictionaries, so in my case e.g. I see the the English-German dictionary first, before all the others.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by benoit-pierre** [comment]
You can tap on the dictionary name in the lookup window to favorite it for the document.

And you can reorder them in the settings ("Dictionary settings", "Manage dictionaries…").

**Comment by Deekee62** [comment]
Thanks for the replies, sorry for the circumstances, I must have overlooked it.
