### ISSUE TITLE
How to unzip oxford english dictionary ?

### ISSUE THREAD

**Issue by namndtth** [koreader/koreader#12516]
Hi everyone.
I have downloaded Oxford English Dictionary. It has two tar.bz2 files which are 
1. stardict-Oxford_English_Dictionary_2nd_Ed._P1-2.4.2.tar.bz2
2. stardict-Oxford_English_Dictionary_2nd_Ed._P2-2.4.2.tar.bz2
Are they two parts of a dictionary ? And how can I unzip to use them ?
Any help will be appreciated. Thanks

**Comment by poire-z** [comment]
I guess these 2 files make out one dictionary. You can decompress tar.bz2 on Windows with 7-zip.
Once decompressed, you should have files named something.ifo, something.idx, something.dict or something.dict.dz.

**Comment by namndtth** [comment]
Hi @poire-z . I used winrar to extract these file. But after the process complete, I got to separate folders. I also used command tar -xvf to extract but did not success.

**Comment by poire-z** [comment]
What's in these 2 folders ? Copy & past each of these folders into a single folder, and may be that's it ?
(For tar.bz2, it's `tar xjvf`)

**Comment by namndtth** [comment]
Hi @poire-z, 
In `stardict-Oxford_English_Dictionary_2nd_Ed._P1-2.4.2.tar.bz2`, I got 
- Oxford_English_Dictionary_2nd_Ed._P1.dict.dz
- Oxford_English_Dictionary_2nd_Ed._P1.idx
- Oxford_English_Dictionary_2nd_Ed._P1.ifo

In `stardict-Oxford_English_Dictionary_2nd_Ed._P2-2.4.2.tar.bz2`, I got similar files but with P2 prefix. I tried your solution but i got no luck

**Comment by poire-z** [comment]
You also get a .ifo in P2 ?
Anyway, these 3 files may be enough, so use only the ones from P1 and forget about P2.
Anyway bis: ask the people that provided you these files how to use them :) It's hard to guess when not knowing the context of these P1 and P2.

**Comment by benoit-pierre** [comment]
This [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stardict-oed) might provide a clue how to install: merge the contents of each extracted directory into a common directory.

**Comment by namndtth** [comment]
Hmm, The dictionary can be used but I can not look up every word. I think It only load 1 part to the ereader

**Comment by benoit-pierre** [comment]
Then keep both extracted directories so KOReader see them as independent? I guess the split was done because of size.

**Comment by namndtth** [comment]
I tried to concat the content of files of two parts by command `cat P1.dict.dz P2.dict.dz > Merged.dict.dz`. Now, all the words can be looked up but the meaning of some words is not correct. If I try to read the content and find out the way to merge correctly, I can successfully load the file to eReader. But It's time consuming so I decide to use another dictionary.
Thank @poire-z and @benoit-pierre for helping me xD.

**Comment by benoit-pierre** [comment]
Yeah, a simple cat is not going to cut it. But are you sure merging is a good idea? It might increase sdcv memory use during lookup.

**Comment by namndtth** [comment]
I think It depends on the device you're using. I'm using boox note air 3 and the lookup does not affect performance of the device

**Comment by mergen3107** [comment]
Well, Kobos, Kindle, and Pocketbooks can't say the same :D

**Comment by namndtth** [comment]
yah xD, choosing smaller dictionary is more appropriate
