### ISSUE TITLE
Changing status in FM doesn't make book show up in History

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12515]
* KOReader version: 2024.07-173-g5b2cc5f63
* Device: Kindle Scribe (FW 5.16.9 hf)

#### Issue
I marked a bunch of books as Finished from File Manager. However, none of them show up in History under any category. 

#### Steps to reproduce
Go to FM
Mark a book as Finished via long tap
Go to History - book is missing.

If I then go to this book, Book status, mark it as Reading and then as Finished again - no difference.

However, if I reset the book via long tap in FM, open the book (it shows up in History) and then mark it as Finished in Book Status - it works! It shows up in History. 

##### `crash.log` (if applicable)
Let me know if logs are indeed needed. 
I think it is easy to reproduce.

**Comment by mergen3107** [comment]
I noticed that "On hold" books also didn't make it to History.

**Comment by mergen3107** [comment]
Reading status as well

**Comment by mergen3107** [comment]
@hius07 
Can this be culprit?
https://github.com/koreader/koreader/commit/f0c9a642d1743350de3d303ac1b8508bb58d5e60

**Comment by hius07** [comment]
A book is added to the History after opening only.

**Comment by mergen3107** [comment]
Yes, I remember that. 
But after I opened these marked books, they still don't show up.

**Comment by mergen3107** [comment]
Wait, I think previously when it worked, a marked book showed up in Finished section of History even without opening. 

Otherwise, I wouldn't see all those books in History (from times when I was asking to add a denser mosaic grid)

**Comment by hius07** [comment]
A book is added to the History on opening **only**.

If you have "Freeze last read date of finished books" checked, mark a book finished in FM and then open it, the book is **not** added to the History.

**Comment by mergen3107** [comment]
I see. Finished books depend on the check mark. 

But how about books marked as On hold?

Shouldn't they appear in History On Hold section?

I was about to out a bunch of books on hold to read later. I think this worked last time I did this, so that's why I think now is something broken

**Comment by Steven630** [comment]
What is the use of "on hold" and "finished"? Can anyone explain?

**Comment by hius07** [comment]
I do not have strong opinion if a book should be added to the History on changing its status in FM.

**Comment by mergen3107** [comment]
I went through my old backups and I found the source of my confusion! :D 

It is the findhistory.koplugin. 

My routine was:
1) Go around the books in FM, mark them reading, on hold, finished. 
2) Run this plugin
3) All books appear in History in their respective categories.

Then I also remembered that at some point it stopped working because KOReader updated formatting or something else and I stopped using it. This is why I didn't see it in my most recent backups on Kon-Tiki 2. 

In the light of this, @hius07 can we please have an option to add books to History if their status is changed in FM?

I would find it much more time effective than opening each book and setting its status in Book status. 

By the way, after changing status in FM **and** opening the book, it still doesn't show up in History anywhere (checkmark is checked), so this is a bug still.

**Comment by mergen3107** [comment]
This is the plugin: https://github.com/koreader/contrib/tree/main/findhistory.koplugin

**Comment by hius07** [comment]
> In the light of this, @hius07 can we please have an option to add books to History if their status is changed in FM?

Can be discussed, more opinions are welcome.



> after changing status in FM **and** opening the book, it still doesn't show up in History anywhere

To what status?

**Comment by mergen3107** [comment]
Any status! 
Even Reading

**Comment by mergen3107** [comment]
Oops, sorry. Let me test that again

**Comment by mergen3107** [comment]
OK, so after opening, Reading and On hold statuses show up. 

I take it back :D sorry

**Comment by mergen3107** [comment]
Finished status doesn't show up after opening - is this because of the check mark?

I though it only disables Statistics, not History as well

**Comment by NiLuJe** [comment]
> I do not have strong opinion if a book should be added to the History on changing its status in FM.

Before the filter feature, I would have probably said no, but I can sort of see this being useful given the filtering capabilities. (And, perhaps more importantly, how *not* doing adding them to history could be confusing for users ;)).

> Finished status doesn't show up after opening - is this because of the check mark?

Yes, c.f.,

>> A book is added to the History on opening only.

>> If you have "Freeze last read date of finished books" checked, mark a book finished in FM and then open it, the book is not added to the History.

**Comment by mergen3107** [comment]
Thanks guys!

Sorry for the confusion at first :D 

I can understand the books not being added marked as Finished - if they are finished you probably wouldn't like to come back to them (?). 

However, I'd vote for adding books marked as Reading and On hold to History - to help better line up. 

Otherwise, it is hard to manage even relatively large collections. I started afresh now, with 15-20 books, but still :D (previously I used to upload 200-250 books, but rarely even saw them in FM lol)

**Comment by Frenzie** [comment]
> Before the filter feature, I would have probably said no

History is things you opened. Marking as finished without opening is explicitly saying you *don't* want it added to history, isn't it?

**Comment by NiLuJe** [comment]
> History is things you opened. Marking as finished without opening is explicitly saying you _don't_ want it added to history, isn't it?

There's already the aforementioned checkmark to enforce that behavior regardless.

Otherwise, for people not reading seven things at once, your history is pretty much 99% finished stuff, so I'm not entirely following that argument ;).

**Comment by mergen3107** [comment]
Only for ... _historical_ reasons, haha :D

**Comment by mergen3107** [comment]
Basically my request for statistics was to avoid adding reading time to finished books. I didn't catch that it made it miss going to History as well, because I tested it on books which were already there

**Comment by Frenzie** [comment]
> Otherwise, for people not reading seven things at once, your history is pretty much 99% finished stuff, so I'm not entirely following that argument ;).

The argument is that history is history, not random things that aren't history. I don't understand what you're trying to say.

**Comment by Frenzie** [comment]
A book that is never opened is never history by definition.

**Comment by Frenzie** [comment]
It's short for recently opened files.

**Comment by mergen3107** [comment]
> The argument is that history is history, not random things that aren't history. I don't understand what you're trying to say.

This. I just meant that "Finished books" for me is "everything from files I found in FM I ever read, not necessarily in KOReader (meaning flipping through all pages in KOReader and marking it as finished in the end)". 

But that's not directly what KOReader is supposed to do (and I am not voting for it).

**Comment by mergen3107** [comment]
> It's short for recently opened files.

Alright, with this paradigm then please disregard my request about adding "Reading" and "On hold" to History.

Probably what I am asking is something like "To read" list, but I don't know if you guys would agree to add yet another category :D

**Comment by Frenzie** [comment]
> That interacting with a book's read status could be construed as interacting with that book, period, and that information being transferred to history sort of makes sense to me.

I don't quite buy that, at least not for finished. I might accept it for switching from finished to reading. However presumably it wouldn't be bothersome.

**Comment by NiLuJe** [comment]
Finished being treated as an exception is already something that exists in the current codebase, as far as I understood (again, that's not something that I'd find useful myself, though).

Where else besides the FM is the book status reflected, anyway?

**Comment by mergen3107** [comment]
Only in Book Status window itself, IIRC

**Comment by hius07** [comment]
> Probably what I am asking is something like "To read" list

Collections

**Comment by mergen3107** [comment]
I still can't quite get over with the fact that FM's "Finished" status for books is not reflected in History.

Can we please consider at least adding a toggle?
Something like `Add to History if marked in FM`

**Comment by mergen3107** [comment]
Nevermind, I just tried the plugin above with KOReader 2024.07-215 (https://github.com/koreader/contrib/tree/main/findhistory.koplugin) and it worked! All books I marked in FM went into respective History categories.

Thank you again @Hzj-jie !
