### ISSUE TITLE
FR: Lemmatization (use dictionary headwords to remove inflections) in Vocabulary Builder

### ISSUE THREAD

**Issue by Steven630** [koreader/koreader#12529]
**Does your feature request involve difficulty completing a task? Please describe.**
Since the last update of how Vocabulary Builder handles context #12465 , the user can manually change the query while keeping the context unchanged. However, the VB still displays the form of a word in the sentence.

_For example_, if I look up "dominated" in "wet-rice farming **dominated** the plains" and add the word to Vocabulary Builder. VB displays "dominated" and stores "dominated" to the sqlite3 file. It should be displayed as "**dominate**", the lemmatized original form.

I want to export the words to Anki and lemmatization is important for this purpose. Otherwise, Anki plugins like Wordquery won't be able to add definitions without the correct form.

@weijiuqiao  Sorry to bother you again, but this feature is really important. 

**Describe the solution you'd like**
When user presses "add to vocabulary builder" button, VB should add the headword of the dictionary (thus the lemmatized form) to the column of "word". This also has the benefit of letting user decide what the orginal form is. In "This is a **pressing** issue", "**pressing**" is the original form. In "He keeps **pressing** the button", "pressing" should be lemmatized to "**press**". When you look up "pressing" the entries of "press" and "pressing" all show up. The trick is to add the form where user chooses to add to VB.  (With current behaviour, adding two "pressing" is impossible. [Allowing duplicates is also necessary](https://github.com/koreader/koreader/issues/12506#issuecomment-2343889387).

For users who do review words in this plugin, lemmatization also saves time and CPU. Because the right form is already there, there's no need to use fuzzy search every time the user clicks on a word in the review mode.

Here are some screenshots to make myself clearer:

![Screenshot_20240918_184443](https://github.com/user-attachments/assets/c0c5aa13-267d-47aa-8d50-7a31cb73b640)

![Screenshot_20240918_184602](https://github.com/user-attachments/assets/53a89dca-94ea-43e2-a3fc-63071432d2ea)

![Screenshot_20240918_191237](https://github.com/user-attachments/assets/fb24824b-3487-4077-9b6e-565a26f1b6a9)

![Screenshot_20240918_191303](https://github.com/user-attachments/assets/0419ad9d-0f96-49a5-955e-f0eed43ed334)

![Screenshot_20240918_191448](https://github.com/user-attachments/assets/ee1c5388-b467-4528-b2df-95d188090fa0)

**Comment by weijiuqiao** [comment]
Your request does make sense but I'm simply too occupied this year and cannot say when I'll have time to investigate into this. 
@poire-z would you be so kind to take a look at this since it would involve getting the dict search results instead of the "word" that's being searched, which would change things in the core codebase.

**Comment by Steven630** [comment]
> Your request does make sense but I'm simply too occupied this year and cannot say when I'll have time to investigate into this. 
> @poire-z would you be so kind to take a look at this since it would involve getting the dict search results instead of the "word" that's being searched, which would change things in the core codebase.

Thank you for your reply. It would be nice of you to investigate when you have time.

**Comment by poire-z** [comment]
I don't even want to try to understand the OP, and neither how vocabbuilder.koplugin works :)

> since it would involve getting the dict search results instead of the "word" that's being searched, which would change things in the core codebase.

If it's this `dict_popup.word` that you wish would be the current result word:
https://github.com/koreader/koreader/blob/3401bed3d1dab14deee2a425a68b40225e298a35/plugins/vocabbuilder.koplugin/main.lua#L2037-L2041

You can probably already access it as `dict_popup.lookupword`, cf.:
https://github.com/koreader/koreader/blob/3401bed3d1dab14deee2a425a68b40225e298a35/frontend/ui/widget/dictquicklookup.lua#L285-L292

**Comment by Steven630** [comment]
>I don't even want to try to understand the OP, and neither how vocabbuilder.koplugin works :)

My bad. Long story short. When one looks up words like "pockets", "driving", the dictionary actually  returns results for "pocket", "drive". The latter(the original form that shows up as dictionary headword) is what I want.

**Comment by Steven630** [comment]
@poire-z  In the verbose log, I found what I'm looking for:

This is when I look up "declared". We want "declare":

> 09/18/24-01:56:12 DEBUG showing quick lookup window 1 : declared {
>   {
>     css = "...",
>     dict = "Shorter Oxford English Dictionary, 6th Ed.",
>     is_html = true,
>     **word = "declare"**
>   } --[[table: 0x413313c0]],
>   {


Would you please enlighten me as to how to get "declare" (in bold, after "word=")? Thank you.

**Comment by poire-z** [comment]
What you see logged in the snippet you pasted ends up as:
https://github.com/koreader/koreader/blob/3401bed3d1dab14deee2a425a68b40225e298a35/frontend/ui/widget/dictquicklookup.lua#L997-L1005
You can try changing in line 2041 `dict_popup.word` to `dict_popup.lookupword`:
https://github.com/koreader/koreader/blob/3401bed3d1dab14deee2a425a68b40225e298a35/plugins/vocabbuilder.koplugin/main.lua#L2037-L2041

But don't ask me more: I have no idea and don't want to think nor decide if this would make sense in vocabbuilder plugin.

**Comment by Steven630** [comment]
> What you see logged in the snippet you pasted ends up as:
> https://github.com/koreader/koreader/blob/3401bed3d1dab14deee2a425a68b40225e298a35/frontend/ui/widget/dictquicklookup.lua#L997-L1005
> You can try changing in line 2041 `dict_popup.word` to `dict_popup.lookupword`:
> https://github.com/koreader/koreader/blob/3401bed3d1dab14deee2a425a68b40225e298a35/plugins/vocabbuilder.koplugin/main.lua#L2037-L2041
> 
> But don't ask me more: I have no idea and don't want to think nor decide if this would make sense in vocabbuilder plugin.

It really helps. Thank you very much!

@weijiuqiao Seems an easy fix?

**Comment by weijiuqiao** [comment]
Thanks veteran dev :)

**Comment by poire-z** [comment]
Just asking:
this "lookupword"/current dict result is not the one that will be saved with the context (the few words before/after), right ? Otherwise this sentence won't read well.

Is this consistent with the other "onWordLookedUp" usage ?
```
$ rgrep WordLooked frontend plugins
frontend/apps/reader/modules/readerdictionary.lua:    self.ui:handleEvent(Event:new("WordLookedUp", word, book_title))
plugins/vocabbuilder.koplugin/main.lua:            dict_popup.ui:handleEvent(Event:new("WordLookedUp", dict_popup.word, book_title, true)) -- is_manual: true
plugins/vocabbuilder.koplugin/main.lua:-- Event sent by readerdictionary "WordLookedUp"
plugins/vocabbuilder.koplugin/main.lua:function VocabBuilder:onWordLookedUp(word, title, is_manual)
```

**Comment by weijiuqiao** [comment]
Now when using the "add to VB" button, both the lookupword and the highlighted word will be saved (when different) so the context still reads well.
If one uses automatic adding new words (off by default) then the `word` is saved because that's from `readerdictionary`.

**Comment by Steven630** [comment]
Thank you both. Never thought it could be solved so easily.
