### ISSUE TITLE
Highlight has problem with hyphenation at end of line

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1252]
It works in selection mode but when you choose highlight it will not highlight the last char and the following hyphen.

Problem appears on Kobo Aura with 20141121. And also 1213-g9b3ef8f (the most recent version).

![screenshot_2014-nov-26_092254](https://cloud.githubusercontent.com/assets/1377943/5198543/c6237264-7552-11e4-9b8d-4631cd7a60c7.png)
![screenshot_2014-nov-26_092705](https://cloud.githubusercontent.com/assets/1377943/5198544/c6288204-7552-11e4-81c4-6b0dae32d91f.png)
![screenshot_2014-nov-26_092712](https://cloud.githubusercontent.com/assets/1377943/5198545/c62b54c0-7552-11e4-991e-c00a07c5d5a8.png)

**Comment by Markismus** [comment]
Got it too on my Kobo H20:
![screenshot_2015-apr-22_091727](https://cloud.githubusercontent.com/assets/5269101/7271355/1908a180-e8e3-11e4-909e-d344cf7b9a67.png)

More annoying is the highlights shown on the botton, when the first line of the next page is highlighted (Shown are two consecutive pages):
![screenshot_2015-apr-22_091910](https://cloud.githubusercontent.com/assets/5269101/7271375/42ee623c-e8e3-11e4-9a8f-e73ee9268734.png)
![screenshot_2015-apr-22_091915](https://cloud.githubusercontent.com/assets/5269101/7271376/44507ef8-e8e3-11e4-814a-356200b6faf6.png)

**Comment by robert00s** [comment]
@lightonflux @Markismus 
Can you try most recent version. It can be fixed in koreader/crengine#204 by @poire-z.

**Comment by poire-z** [comment]
I think the original issue must be solved.

There's still one, that may affects only french texts: any hyphenated word preceded by `l'` or `d'` or `s'` is not highlighted (these are each one single highlight):
<kbd>![image](https://user-images.githubusercontent.com/24273478/42417922-709c6b12-8295-11e8-92a8-2445a925254d.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/42417929-7db0f6a6-8295-11e8-841c-0169f896984b.png)</kbd>

And some small uneven right side highlight limit (not as pretty as the left side):
<kbd>![image](https://user-images.githubusercontent.com/24273478/42417954-e394b750-8295-11e8-87cb-903d8b102401.png)</kbd>
