### ISSUE TITLE
FR: different e-ink refresh rates per book type

### ISSUE THREAD

**Issue by Elijah-C-G** [koreader/koreader#12535]
**Does your feature request involve difficulty completing a task? Please describe.**
When using an ePub file, I like to do a full refresh every 6 page turns. When viewing CBZ files, I prefer to refresh every page, since ghosting is more notable with digital comics and makes them look worse.

**Describe the solution you'd like**
Either: an option to change the refresh rate per book type, or: an option to change the refresh rate for individual books.

**Describe alternatives you've considered**
1. Using my reader's built-in reading application for some books. This is bad because I use KOReader to sync progress between multiple devices, and the default application has issues which KOReader solves.
2. Just setting full refresh to every page for all book types. This adds more processing than I'd like for ePub files.
3. Manually switching. This is what I do now, and is a bit of a hassle.

**Comment by dmalinovsky** [comment]
KOReader has a setting "Always flash on pages with images". Perhaps we can apply them to CBZ files as well and consider every page as one with the images? This will resolve this issue then.

**Comment by Frenzie** [comment]
I suppose it'd make more sense as a per document setting (whether with different defaults based on extension, it's an option I suppose). Or maybe just a user patch.

**Comment by NiLuJe** [comment]
We don't really have a framework for extension-specific setting (and, granted, it might be nice to have, but I'm also fairly hard-pressed to find any meaningful use-cases for it besides the OP's ;)).

In the meantime, having it work as a docsetting would allow using the docsettingstweak plugin to do a per-directory override, which might just be enough ;).

**Comment by NiLuJe** [comment]
> KOReader has a setting "Always flash on pages with images". Perhaps we can apply them to CBZ files as well and consider every page as one with the images?

Nope. That's based on information we get via CRe only.

I have no idea if anything of the sort could be achieved via MuPDF.

**Comment by offset-torque** [comment]
> Manually switching. This is what I do now, and is a bit of a hassle.

Are you using the menu to switch **Elijah-C-G**? If yes I want to point out that you can assign gestures to different refresh rates. So for example you can swipe up the left edge for "every page" and swipe down for "every x page" refresh. Action is under **"Gesture manager > Screen and lights > Full refresh rate"**. A single tap or swipe takes 1 second so I think this is a reasonable solution for now.

**Comment by Elijah-C-G** [comment]
@offset-torque thank you! That solves my problem. I'll close this in a day if nobody minds.

**Comment by offset-torque** [comment]
I am glad **Elijah-C-G**. I guess this ghosting/refresh issue is a common problem for comic readers, so I will add this tip to the user guide too.
