### ISSUE TITLE
FR: Source code file format support [like .c, .lua, .json]

### ISSUE THREAD

**Issue by stupidcoffee** [koreader/koreader#12536]
**Does your feature request involve difficulty completing a task? Please describe.**
The home screen of Koreader is a file browser on the root directory, first thing I figure it could be a good way to read large codebase. however I find it doesn't support (let me open) almost any source code format like [.c, .js .json] or any other. it will be great to have ability to open those file.

**Describe the solution you'd like**
Those source code format suppose to share same format as TXT files, it should be easy to implement myself. at the meantime it will be awesome to get any advice from experienced maintainer what file should I change and what should I watch out. 

**Describe alternatives you've considered**
Also syntax highlight could be nice for some of people (I don't need it, I think it is distracting) it could be work as a plugin maybe? there is many mature lib for syntax highlighting, it could be discussed which one should be choose. 

**Additional context**
It will also be cool to have script writing capability or SSH terminal function. but I guess in another day.

Also if the function I described already exist I am sorry I didn't take look into it. 

Best.

**Comment by hius07** [comment]
You can open any file with TextViewer or Text editor via long-press - Open with...
You can assign a viewer to a file extension to open it with a tap.
No syntax highlight there.

**Comment by Frenzie** [comment]
There's also the terminal plugin btw, under tools → more tools → terminal where you can run any command line editor.
