### ISSUE TITLE
FR: File search enhancements

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12544]
**Does your feature request involve difficulty completing a task? Please describe.**

1. Sometimes I am searching for more than one book at once and would like to open them in sequence. Or I'm not sure which file I need and have to open them one by one to find what I'm looking for. In either case, a new file search query has to be entered after each opened book.

2. When a search query did not return any results, the File search dialog has to be opened again and the query reentered, even if a quick search term correction could bring up the desired results.

**Describe the solution you'd like**

1. Similar to the 'Last fulltext search results' feature, add an option (available via gestures), `Last file search results` or `Repeat previous file search` that repeats the last file search. 

The last search should be available at least for the current session, but for some use cases (e.g., users routinely performing the same search) it would be helpful to save the last search for future sessions.

2. If a file search returns no results, return to the file search dialog still populated with the previous search query.

**Comment by hius07** [comment]
If you manage to test before the release.

**Comment by hius07** [comment]
But the results are not saved to disk, they are lost if you open a book from the results list.
(The cache lives in a FM/Reader session only)
So just tap a result to view its properties.

**Comment by jonnyl2** [comment]
>If you manage to test before the release.

Sure thing. Thank you for adding this!

**Comment by jonnyl2** [comment]
I tried the updates but unfortunately I'm not sure what the use case for the  `Last file search results` would be if the previous file search is not retained at least until the device is suspended or the application closed (sorry if that wasn't clear enough in the FR; I didn't consider opening a new book as a new session). 

(A current alternative would be to just create a temporary collection with the search results, but then the 'last file search results' wouldn't really be needed.)

I also don't think that populating the search field with the previous search term by default is a good idea. If users _don't_ want to repeat the search then clearing the field first is a bit of a hassle. If going directly to the search results in a new book is not a viable option, perhaps just rename the new action to `Last file search` and make only that one populate the file search field with the last search, while the regular File search dialog's field will remain empty?

And have you considered point 2. in the FR? Perhaps the file search dialog could remain open until a result is found. In that case, if no result is found, the user could just dismiss the 'no results found' info message (or wait for it to close) and enter a different search (or close the dialog himself). Same goes for cancelling the search -- instead of everything closed, the search dialog would still be available so a different search query (e.g., one that takes less time) could be entered right away.

**Comment by hius07** [comment]
New: "last search results" survives opening/closing books.

**Comment by jonnyl2** [comment]
Everything works great, thank you.

**Comment by jonnyl2** [comment]
@hius07: Thank you for implementing the book content search in Collections. I'm sure this will come in handy in due time.

I'd just like to drop an idea for an additional option for file search (and possibly also for History): 
Search in annotations (including highlights, edited highlights, and notes -- and perhaps also in the associated notebook files  when available), and list the books which contain the keyword searched in those files.

Use case would be to easily find books again where a certain highlight was made or a note added, especially in cases the user forgot the book's title. (And this search should be quite fast, being all text and only in the metadata files.)

Mockup, for illustration:

![Image](https://github.com/user-attachments/assets/9287fab8-25a0-4b84-9c2a-fca5d93e71aa)

![Image](https://github.com/user-attachments/assets/34143401-04e3-4d40-8ffb-af6f01b57d8e)

**Comment by hius07** [comment]
Thanks for the idea, noted.
