### ISSUE TITLE
Directory Defaults - not applied on marked books

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12559]
* KOReader version: koreader-kindlehf-v2024.07-214-ga1edbbf0c
* Device: Kindle Scribe (FW 5.16.21)

#### Issue
Directory defaults are not applied to a never-opened book that was marked (all three).

#### Steps to reproduce
Setup directory defaults. In my case this changed direction to RTL when a book is in folder `[manga]`.
Mark a never opened book as reading/on hold/finished in this folder.
Open.
Result: RTL direction is not applied.

##### `crash.log` (if applicable)
A working example with test books, settings, and crash.log, assuming this is in `/mnt/us/`:
[RTL_on_finished_books.zip](https://github.com/user-attachments/files/17153501/RTL_on_finished_books.zip)

Thank you!

**Comment by mergen3107** [comment]
It seems directory defaults are not applied if I mark books by any status. 

So this is probably not related to freezing stats for finished books, it is something else.

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/a1edbbf0c425ad67b08e5348629a60660e65149e/plugins/docsettingtweak.koplugin/main.lua#L102-L104

The first check probably needs to check more things about the book being really opened (ie. last_xpointer for cre document, dunno about pdf) - and just not the docsetting being non-empty, as they can be non-empty when metadata have been customized or the book status changed.

**Comment by hius07** [comment]
Good candidate 
https://github.com/koreader/koreader/blob/a1edbbf0c425ad67b08e5348629a60660e65149e/frontend/docsettings.lua#L293

**Comment by poire-z** [comment]
Sure you don't go thru there when you update metadata/status ?

**Comment by hius07** [comment]
Nope, bad idea.

**Comment by 0zd3m1r** [comment]
same for me. how can i fix it?

**Comment by mergen3107** [comment]
@0zd3m1r 
See linked PR. I tested, it works for me. 

Can you please test it too?

You need to patch existing koreader nightly.

**Comment by 0zd3m1r** [comment]
@mergen3107 

Yes it works for me too. Thanks.
