### ISSUE TITLE
Today's update (nb) causes a permanent crash

### ISSUE THREAD

**Issue by Glover1969** [koreader/koreader#12558]
* KOReader version:
* Device: InkPad 3
![20240926_075952](https://github.com/user-attachments/assets/9b563faf-c865-4a5b-8312-72a5c86a1330)
![20240926_075952](https://github.com/user-attachments/assets/05e234c0-79fe-4d9d-9b3a-d29d131c90ca)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
Given https://github.com/koreader/koreader/pull/12555 by today's do you perhaps mean yesterday's?

**Comment by NiLuJe** [comment]
Not on today's nightly, I think (given the line numbers in the trace) ;).

**Comment by jospalau** [comment]
My PocketBook Era is starting fine. 

I am having an error though in all devices when loading utf8proc.lua:
./luajit: ./ffi/utf8proc.lua:16: attempt to call field 'loadlib' (a nil value)

And another when restarting just the Kobo devices:
./luajit: frontend/device/input.lua:411: attempt to index local 'self' (a nil value)

Bear in mind it could be my configuration.

**Comment by NiLuJe** [comment]
> ./luajit: ./ffi/utf8proc.lua:16: attempt to call field 'loadlib' (a nil value)

Should go away after #12545 (actually confused how anything works without it right now ;D).

> ./luajit: frontend/device/input.lua:411: attempt to index local 'self' (a nil value)

Line number doesn't match the current codebase, so unclear what might be happening.

**Comment by benoit-pierre** [comment]
> > ./luajit: ./ffi/utf8proc.lua:16: attempt to call field 'loadlib' (a nil value)
> 
> Should go away after #12545 (actually confused how anything works without it right now ;D).

It does not: that part has not been bumped yet, which means mismatched base & frontend code.

**Comment by jospalau** [comment]
I introduced a condition to skip it, hence the different lines. It may be something related to my environment anyway. This happens after restarting:

./luajit: frontend/device/input.lua:408: attempt to index local 'self' (a nil value)
stack traceback:
	frontend/device/input.lua:408: in function 'teardown'

**Comment by jospalau** [comment]
It was my system. Rsync not bringing the source modified to the devices because size being the same after changing the . for : 
Working now. Thanks

**Comment by benoit-pierre** [comment]
Just to be clear, I meant that you're using mismatched base / frontend code @jospalau, not that master is broken.

**Comment by jospalau** [comment]
Yes. I sync the code to my devices via Rsync script and didn't bring the little change

**Comment by jospalau** [comment]
Can't suspend the Kobo devices pressing the button after last change. It works after passing the library version:
pcall(ffi.loadlib, "fbink_input", "1")

But again, it can be something in my system. Anyway, just letting it know here.

**Comment by benoit-pierre** [comment]
> Can't suspend the Kobo devices pressing the button after last change. It works after passing the library version: pcall(ffi.loadlib, "fbink_input", "1")
> 
> But again, it can be something in my system. Anyway, just letting it know here.

Nope, that one looks like a bug, both the original code and the new one should use a version, as the built library is `libfbink_input.so.1`.

**Comment by pazos** [comment]
Fixed by https://github.com/koreader/koreader/pull/12555
