### ISSUE TITLE
FR: Annotation/highlight autoexport?

### ISSUE THREAD

**Issue by thegreekgeek** [koreader/koreader#12556]
Hey all, 

So I'm using koreader android to read and annotate my college textbooks, and I'm using Obsidian.md to take notes. There is a plugin for Obsidian to sync your highlights and bookmarks and whatnot to your vault, but it's not really working very well.

So my question is, would there be a way to add a setting to automatically export your highlight files upon annotation? That way I could point my export folder to a location in my Obsidian vault and not have to worry about renaming the files to remove the timestamp like I do now.

**Comment by hius07** [comment]
Do you mean exporting highlights to markdown? At what moment "automatically"?

**Comment by hius07** [comment]
This will be possible after merging of https://github.com/koreader/koreader/pull/12564 and https://github.com/koreader/koreader/pull/12569.
Then you can create a profile containing an exporting action, and set this profile to auto-execute on document closing.

**Comment by pazos** [comment]
markdown is a local format. That will work if the obsidian vault runs on the same computer as KO.

If that's not the case you'll need to raise awareness with obsidian devs, so they can provide an API that we can use to push data to it. Finally implement another remote target that knows how to talk with obsidian.

As far as I'm concerned Obsidian is propietary crap. But we already support other propietary craps, such as readwise. All good here as long as the API is stable enough and somebody contributes time to add support and maintain the exporter.
