### ISSUE TITLE
FR: Communicate auto front light plugin being used to the user

### ISSUE THREAD

**Issue by cheywood** [koreader/koreader#12567]
**Does your feature request involve difficulty completing a task? Please describe.**

When the auto front light plugin is impacting the front light settings that should (at a minimum?) be communicated to the user in the frontlight settings UI.

As a user I didn't understand why the light kept on turning back on after I'd explicitly disabled it in the front light settings.

**Describe the solution you'd like**

Communicate to the user that the auto front light plugin is impacting the front light settings. Ideally, it would be possible to toggle auto front light usage in the front light settings (on devices which support auto front light).

**Comment by NiLuJe** [comment]
To clarify: what exactly are you calling "the frontlight settings UI"?

**Comment by cheywood** [comment]
⇑ TOP MENU → ![image](https://github.com/user-attachments/assets/113e3232-f2e9-4097-82d7-af43cbff4604) → Frontlight

**Comment by NiLuJe** [comment]
That is wholly separate from that plugin (or, well, anything else really), so I'm not quite sure what you're asking for ;).

**Comment by cheywood** [comment]
It's user-centric thought, UX, not architecture-centric :)

And it's just a thought, feel free to close the issue. I created the issue to attempt to help others in the same situation I was.

**Comment by NiLuJe** [comment]
I'm genuinely curious what you'd be expecting to see, and how, though ;).

**Comment by pazos** [comment]
Over the years, I've seen a lot of "two line" questions on the screen while reading on KOReader. It turns out to be the "perception expander" plugin.

The user had to enable it, while modifying the settings.

AFAICT the same thing happens here. The autofrontlight plugin doesn't do anything in its default configuration, right? The user must enable it to modify the behavior of the program.

If I'm right, there's nothing to improve here (aside from the documentation, as always). The behavior of the program with the feature enabled is, in itself, a reminder that the feature is enabled.

**Comment by Frenzie** [comment]
The plugin could theoretically add a checkmark or info icon or something on the frontlight dialog but it's definitely true that if you don't enable it, it doesn't do anything.

**Comment by cheywood** [comment]
> I'm genuinely curious what you'd be expecting to see

Something like eg. an "Auto brightness" toggle for devices with light sensors (I believe I've seen that in Kindle's UI), or "The ABC plugin is also updating this setting". These would communicate to the user that something beyond the controls that they're currently looking at are impacting the setting they're changing.

> but it's definitely true that if you don't enable it, it doesn't do anything

Oops I don't remember enabled the plugin long ago but it sounds like I must have. (presuming there's no logic to auto-enable the plugin on devices where a light sensor exists?). Communicating that a setting is being controlled elsewhere sure wouldn't hurt though, and I imagine I'm not the last user who might forget having configured plugins in the past, or had their device setup by a friend etc.

Anyway, it's just a an idea, thanks for all the great work!

**Comment by offset-torque** [comment]
I think this request is logical. **"Just remember what you have enabled"** is not a good idea for UI. Especially if there is a conflict like in this situation, where two different mechanisms are trying to control the same feature, this should be communicated to the user clearly. Our frontlight dialog is not that crowded, a single line message like **"Frontlight is currently controlled by Auto Frontlight plugin"** or something like this would prevent this kind of confusion. Just my 2 cents.

**Comment by hius07** [comment]
Frontlight level can be changed by gestures as well.

**Comment by NiLuJe** [comment]
Okay, I just realized you're talking about the Kindle-specific Autofrontlight plugin. A thing that is only enabled on the very few Kindle devices with an ambient light sensor.

It hasn't been touched in ages, looks extremely basic and opinionated, and very few of us (if any?) actually have the hardware to test this.

**Comment by mergen3107** [comment]
> and very few of us (if any?) actually have the hardware to test this.

@NiLuJe 
I can help with testing :D 
(Please ping me here, I think I unsubscribed from this ticket by accident)

**Comment by NiLuJe** [comment]
I'm unlikely to do anything about it any time soon, FWIW ;).

**Comment by cheywood** [comment]
For the record this wasn't the outcome I was aiming for and apologies to those negatively impacted :shrug:
