### ISSUE TITLE
FR: Page Turn Audio/sound effect

### ISSUE THREAD

**Issue by Bluemoondragon07** [koreader/koreader#12561]
Is this possible with a patch? It's a completely unnecessary feature, but it is just cool and pulls me into what I'm reading.

The idea of this feature is that any tap or swipe that triggers a page turn plays some sort of  crinkly page turn sound effect. Of course, this would only be triggered on devices with speakers, so that probably further complicates things.

Is there a way to do this with a patch?

**Comment by Frenzie** [comment]
On desktop perhaps, but I have this suspicion you mean Android which would at the very least be harder.

**Comment by pazos** [comment]
android would be impossible with an userpatch alone.
