### ISSUE TITLE
Japanese Font Consistency Issue Within Dictionaries

### ISSUE THREAD

**Issue by jeffh123** [koreader/koreader#12565]
* KOReader version: v2024.07
* Device: Kobo Libra H20

#### Issue
When searching a Japanese word that contains kanaji character(s) in a koreader dictionary, the dictionary result display the word in kanji characters 3 times. Once at the top in bold alongside a hiragana reading. A second time in the same format directly below but not in bold. And a 3rd time at the bottom in parentheses as the dictionary query. For words where the details of the kanji characters differ between the Japanese and Chinese variants of the same character, the Japanese version will display in the top bold one, while the other 2 will display the Chinese font. Changing Koreader language to Japanese does not fix this. Setting the stardict .ifo lang tag to ja or ja-en ensures that the top bold one is Japanese font, but does not change the others.

#### Steps to reproduce
Search a Japanese word in which the style of the kanji character(s) used differs from that of the Chinese equivalent character. Example: 直前. The first character 直 looks very different in both languages.

**Comment by poire-z** [comment]
> Setting the stardict .ifo lang tag to ja or ja-en ensures that the top bold one is Japanese font, but does not change the others.

Not sure what you added/changed into the .ifo, there is no notion of lang in the stardict specs, and dictionaries don't tell what languages they accept and return.
We ourselves add a `lang=in-out` for our downloadables dicts that we know what are the languages "in" (the queried words) and the "out" (the definitions). I don't think we have documented that anywhere (except in the code).
So, indeed, if you know that about your dicts, you can add yourself a `lang=ja-en`.
But you should probably use `lang=ja-ja`.
The first one is the input language, that may be used for the headword (the input) shown in bold, so ok, use `ja`.
The second one is used for the results (the definition, and the possible word at start of it, that is part of the definition). If you specify "en", we will use our shipped NotoSansCJKsc telling it the text in English, and it will use its default of sc "Simplified Chinese" for the Kanji glyphs.
If you use "ja", NotoSansCJKsc will gives Japanese Kanji glyphs.
I can't think of side effect with using `ja-ja` if all you want everywhere from that dict to use Japanese glyphs, so use that :)

**Comment by jeffh123** [comment]
Thank you for the thorough explanation. ja-ja indeed displays the correct characters and appears to produce no other issues. Thank you!
