### ISSUE TITLE
Fixed font size in epub

### ISSUE THREAD

**Issue by winstonma** [koreader/koreader#12570]
* KOReader version: 2024.07
* Device: Linux/Android

#### Issue
I tried to adjust the font size in both app didn't change the font size.

#### Steps to reproduce
Upload the epub  [file](https://github.com/user-attachments/files/17127483/Enterprise.Philosophy.and.The.First.Wave.of.AI.zip) for checking (I just convert the image in the epub file, other things untouched). Please rename the file into `.epub` extension and open with your favorite EPUB reader.

**Comment by benoit-pierre** [comment]
There's a style tweak for that: "Style tweaks" → "Text" → "Font size and families" → "Ignore publisher font sizes".

**Comment by winstonma** [comment]
Thanks

I also checked the CSS file inside the EPUB. And after the line is commented then KOReader can resize the EPUB:

```
html {
//	font-size: 12pt;
	line-height: 1.3;
	font-family: var(--main-font);
	-webkit-print-color-adjust: exact;
	tab-size: 2;
} 
```

Would like to know if the EPUB font size is fixed when `font-size` is being specified is EPUB antipattern?

**Comment by poire-z** [comment]
> Would like to know if the EPUB font size is fixed when `font-size` is being specified is EPUB antipattern?

I think you can call it that.
We render as the publisher tells, and there may be many annoying CSS properties a publisher can set. That's why we have all our style tweaks to counteract some of them.

**Comment by winstonma** [comment]
Thanks for the answer
