### ISSUE TITLE
FR: highlight the book in FM which you just exited from

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12574]
**Does your feature request involve difficulty completing a task? Please describe.**
It would be nice if the book was highlighted briefly in the list of books in FM once you exit from that book. This will improve visual feedback and continuity. 

**Describe the solution you'd like**
Maybe put an arrow or highlight the book row briefly (for 2 seconds) after exiting in Classic/Detailed views. I am not sure how mosaic view should look like though. 

**Describe alternatives you've considered**
No substitutes so far. 

**Additional context**
This will be especially helpful for multi-book series.

**Comment by benoit-pierre** [comment]
Giving the book keyboard focus could work, except for classic display mode, which is apparently not usable when navigating with arrows.

**Comment by hius07** [comment]
Design is the main question here.

**Comment by Commodore64user** [comment]
The focus underline (from NT) is already there. You would just need to temporarily make it visible on touch devices. As @mergen3107 says it could flash a few times and then disappear.

**Comment by jonnyl2** [comment]
It could also be something that stays put, just more discreet then? E.g. a thin centered bullet point in the margin in list view, or a little dot in one corner in the cover view.

**Comment by hius07** [comment]
I'll try the "focused item", if it looks good.

**Comment by hius07** [comment]
@mergen3107, is it visible? (crash.log is focused)

![1](https://github.com/user-attachments/assets/f870dfa3-9c8d-419e-bf21-c2aba565bf0b)

![2](https://github.com/user-attachments/assets/c321d76d-fa49-4b74-a3ec-54b3fa802d61)

**Comment by mergen3107** [comment]
It is visible, but barely. 
Can it be made thicker and as a dashed line?

**Comment by hius07** [comment]
Not easy, it's our standard focus for NT devices, it's geometry is tightly connected with the menu item shape.
@Commodore64user can say more on this.

**Comment by hius07** [comment]
I do prefer using the FocusManager for this.
Good side effect: when going up to the parent folder (`..`), the source folder is focused.

**Comment by NiLuJe** [comment]
Yep, we went over the whole thing last month, thicker lines affect the text layout, so, big mess ;o).

**Comment by mergen3107** [comment]
Got it!
Let's give it a try then?

**Comment by Commodore64user** [comment]
what @NiLuJe said, on the other hand the one on grid (mosaic) mode is actually nice and big so if you are using that it should work quite nicely there...

**Comment by mergen3107** [comment]
I personally use Mosaic only for History/Favorites, but I can see how it can be useful for someone :D
