### ISSUE TITLE
FR: Option to add a combination of status bar items in the footer status bar

### ISSUE THREAD

**Issue by arpanghosh8453** [koreader/koreader#12572]
**Does your feature request involve difficulty completing a task? Please describe.**

Currently it can rotate through the set items or show all the selected ones at once. I want to see a few together, but the number to too much to rotate through and too overwhelming when shown all of them together. 

**Describe the solution you'd like**

I would like to be able to add them as custom combination. I will have options to use a template for the available variables, and have two or three such combination to rotate through on tap. For example, it should show as following 

`Page left in chapter • Chapter name • Time left in chapter • Time • battery`

on tap it will rotate to the next combination 

`Pages left in book • Book name • Time left in book • Time • battery`

**Describe alternatives you've considered**

Currently I pick the items carefully, sometimes I miss some items otherwise it looks too cluttered or won't fit

**Additional context**

I think this will be relatively easy to implement. I am not very familiar with Lua but I worked with the dev team here before on some bugs and they were extremely helpful. If you don't wish to work on this, @Frenzie  @poire-z @NiLuJe Please give me some directions how I can do this. your help is very appreciated :)

**Comment by hius07** [comment]
I think it requires a huge rewriting.

**Comment by jonnyl2** [comment]
Duplicate of #11590

**Comment by poire-z** [comment]
Yes, too complicated, the UI to allow a user to define sets of item would be really complex.
I guess any adhoc solution for that would have to be implemented via a user patch (ie. listening for the event that rotate items, and rotating hardcoded sets of footer items).

**Comment by arpanghosh8453** [comment]
> Yes, too complicated, the UI to allow a user to define sets of item would be really complex. I guess any adhoc solution for that would have to be implemented via a user patch (ie. listening for the event that rotate items, and rotating hardcoded sets of footer items).

@poire-z I think it's doable via a user patch. If we select a few items individually, they do cycle through. So It would be possible in a user patch to replace them with sets. 

For example, I would like to replace the `wifi item` with `Page left in chapter • Chapter name • Time left in chapter • Time • battery` and the `chapter name` item with `Pages left in book • Book name • Time left in book • Time • battery`. Then I will select the `wifi item` and `chapter name` from the menu. and they will render as those sets in the footer. I hope the idea makes sense. I would just need a little guidance so I can craft the whole user patch. I think this will be helpful to solve need of a few user that needs this and also closes #11590 in the favor of the said user patch. 

Thank you.

**Comment by poire-z** [comment]
> I would just need a little guidance so I can craft the whole user patch.

Well, can't guide much, I quite not like our readerfooter.lua, which is the thing to user-patch. Probably:
ReaderFooter:TapFooter()
ReaderFooter:onToggleFooterMode()
I think you would still need to keep all_at_once enabled, but somehow in there switch between 2 sets (I guess the target is self.mode_index) and ReaderFooter:updateFooterTextGenerator().
My journey into footerhell stops here :) Good luck.

**Comment by offset-torque** [comment]
@hius07 
Can profiles be useful here since they are pretty powerful and can restore many settings? Maybe a profile can also save the status bar items and users can switch between different profiles. This removes the necessity of UI. Users can adjust the items then save the profile and recall it from a gesture or quick menu.

**Comment by NiLuJe** [comment]
@offset-torque: And how would you envision *writing* the profile in this scenario?

**Comment by hius07** [comment]
Show "Time and Battery" instead of Time:
```Lua
local ReaderFooter = require("apps/reader/modules/readerfooter")
local util = require("util")

local map = util.tableDeepCopy(ReaderFooter.textGeneratorMap)
ReaderFooter.textGeneratorMap.time = function(footer)
    local t = {}
    table.insert(t, map.time(footer))
    table.insert(t, map.battery(footer))
    return table.concat(t, footer:genSeparator())
end

```

**Comment by hius07** [comment]
@arpanghosh8453 names of all generators:
https://github.com/koreader/koreader/blob/e2d1c55ec56b50c929efba324e8d84a9e337a56d/frontend/apps/reader/modules/readerfooter.lua#L31

**Comment by poire-z** [comment]
Oh right, probably A LOT easier to hack some individual item generator to display multiple items !
Some other examples hacking the footer items at https://github.com/koreader/koreader/issues/11512#issuecomment-1975283349, https://github.com/koreader/koreader/issues/12251#issuecomment-2260936137

**Comment by arpanghosh8453** [comment]
@poire-z YES! that's what I was talking about. Replace/hack individual items with a set of items :)

Thank you @hius07 for the snippet. I will work on this and make my own userpatch. 

Just want to comfirm if I will additionally need the following at the bottom of the userpatch to make it work and update?

```lua
ReaderFooter.init = function(self)
    orig_ReaderFooterr_init(self)
    print("hacking footer")
    ReaderFooter.textGeneratorMap.battery = my_battery
    self:updateFooterTextGenerator()
    -- We only needed to do this once, so restore the original
    ReaderFooter.init = orig_ReaderFooterr_init
end
```

**Comment by poire-z** [comment]
> Just want to comfirm if I will additionally need the following at the bottom of the userpatch to make it work and update?

Dunno, you'll see if you need it :) (dunno why I used that ; if @hius07 snippet does not need it, it may be unnecessary).

> and is there any userpatch available to rename that item as combo-1 etc in the UI in place of the original item name?

You may need to user-patch `ReaderFooter:textOptionTitles()` to give your option another name, but keep that cosmetics for when you are done with the rest.

**Comment by arpanghosh8453** [comment]
Awesome! I will give it a try. Thank you @poire-z and @hius07

**Comment by offset-torque** [comment]
> **NiLuJe** - And how would you envision writing the profile in this scenario?

I am not a dev so I just share my ideas. And if they are possible, someone implements them as in quick menu, partial rendering, select and highlight mode... But I don't know if they are possible when sharing the idea because I am not a dev.

**But if you are just curious how I would do that, let's give it a shot >>>**
We have a "New profile with current settings" action which does what it says. It saves around 40 settings and when recalled it restores them. And our footer settings are kept in `settings.reader.lua`. 

So this is how I envisioned the procedure:

1. User arranges their first status bar config and runs "New profile with current settings"
2. Footer config is written into a profile
3. User arranges their alternative status bar config and runs "New profile with current settings"
4. Second footer config is written into a profile

When one of these profiles is run, it overwrites `settings.reader.lua`  as if the user changed it using the menu.

But at this point probably there are things I don't know about how all this works so one of our devs says: **"Nope this is problematic because tabledeepcopy triggers thingamabob in the crengine and we don't want to touch that ancient relic"**. Or it is doable but so niche that they decide it doesn't worth the effort, added complexity etc. But I leave these parts to our devs because I am not a dev. I just share ideas. And sometimes they work.

**Comment by arpanghosh8453** [comment]
> Userpatch to show "Time and Battery" instead of Time:
> 
> ```lua
> local ReaderFooter = require("apps/reader/modules/readerfooter")
> local util = require("util")
> 
> local map = util.tableDeepCopy(ReaderFooter.textGeneratorMap)
> ReaderFooter.textGeneratorMap.time = function(footer)
>     local t = {}
>     table.insert(t, map.time(footer))
>     table.insert(t, map.battery(footer))
>     return table.concat(t, footer:genSeparator())
> end
> ```

This is working! Thank you @hius07! Just like I wanted. 

@poire-z about changing `ReaderFooter:textOptionTitles()` I am sure that would work too, but can't replace the item I want selectably. If I copy the whole function, it has other dependencies such as _, C_ which are local to the original `readerfooter.lua` file. 
Any guidance there how I can I update those? I tried copying everything I need but that way, I get an error that the patch apply failed. 

```lua
local ReaderFooter = require("apps/reader/modules/readerfooter")
local util = require("util")
local _ = require("gettext")
local C_ = _.pgettext
local T = require("ffi/util").template

local map = util.tableDeepCopy(ReaderFooter.textGeneratorMap)

ReaderFooter.textGeneratorMap.time = function(footer)
    local t = {}
    table.insert(t, map.time(footer))
    table.insert(t, map.battery(footer))
    return table.concat(t, " ⸺ ")
end

local symbol_prefix = {
    letters = {
        time = nil,
        pages_left_book = "->",
        pages_left = "=>",
        -- @translators This is the footer letter prefix for battery % remaining.
        battery = C_("FooterLetterPrefix", "B:"),
        -- @translators This is the footer letter prefix for the number of bookmarks (bookmark count).
        bookmark_count = C_("FooterLetterPrefix", "BM:"),
        -- @translators This is the footer letter prefix for percentage read.
        percentage = C_("FooterLetterPrefix", "R:"),
        -- @translators This is the footer letter prefix for book time to read.
        book_time_to_read = C_("FooterLetterPrefix", "TB:"),
        -- @translators This is the footer letter prefix for chapter time to read.
        chapter_time_to_read = C_("FooterLetterPrefix", "TC:"),
        -- @translators This is the footer letter prefix for frontlight level.
        frontlight = C_("FooterLetterPrefix", "L:"),
        -- @translators This is the footer letter prefix for light warmth of the frontlight (redshift).
        frontlight_warmth = C_("FooterLetterPrefix", "LW:"),
        -- @translators This is the footer letter prefix for memory usage.
        mem_usage = C_("FooterLetterPrefix", "M:"),
        -- @translators This is the footer letter prefix for Wi-Fi status.
        wifi_status = C_("FooterLetterPrefix", "W:"),
        -- @translators This is the footer letter prefix for page turning status.
        page_turning_inverted = C_("FooterLetterPrefix", "Pg:"),
    },
    icons = {
        time = "⌚",
        pages_left_book = BD.mirroredUILayout() and "↢" or "↣",
        pages_left = BD.mirroredUILayout() and "⇐" or "⇒",
        battery = "",
        bookmark_count = "\u{F097}", -- "empty bookmark" from nerdfont
        percentage = BD.mirroredUILayout() and "⤟" or "⤠",
        book_time_to_read = "⏳",
        chapter_time_to_read = BD.mirroredUILayout() and "⥖" or "⤻",
        frontlight = "☼",
        frontlight_warmth = "💡",
        mem_usage = "",
        wifi_status = "",
        wifi_status_off = "",
        page_turning_inverted = "⇄",
        page_turning_regular = "⇉",
    },
    compact_items = {
        time = nil,
        pages_left_book = BD.mirroredUILayout() and "‹" or "›",
        pages_left = BD.mirroredUILayout() and "‹" or "›",
        battery = "",
        bookmark_count = "\u{F097}",
        percentage = nil,
        book_time_to_read = nil,
        chapter_time_to_read = BD.mirroredUILayout() and "«" or "»",
        frontlight = "✺",
        frontlight_warmth = "⊛",
        -- @translators This is the footer compact item prefix for memory usage.
        mem_usage = C_("FooterCompactItemsPrefix", "M"),
        wifi_status = "",
        wifi_status_off = "",
        page_turning_inverted = "⇄",
        page_turning_regular = "⇉",
    }
}

function ReaderFooter:textOptionTitles(option)
    local symbol = self.settings.item_prefix
    local option_titles = {
        all_at_once = _("Show all selected items at once"),
        reclaim_height = _("Overlap status bar"),
        bookmark_count = T(_("Bookmark count (%1)"), symbol_prefix[symbol].bookmark_count),
        page_progress = T(_("Current page (%1)"), "/"),
        pages_left_book = T(_("Pages left in book (%1)"), symbol_prefix[symbol].pages_left_book),
        time = symbol_prefix[symbol].time
            and T(_("Current time (%1) and Battery"), symbol_prefix[symbol].time) or _("Current time"),
        chapter_progress = T(_("Current page in chapter (%1)"), " ⁄⁄ "),
        pages_left = T(_("Pages left in chapter (%1)"), symbol_prefix[symbol].pages_left),
        battery = T(_("Battery percentage (%1)"), symbol_prefix[symbol].battery),
        percentage = symbol_prefix[symbol].percentage
            and T(_("Progress percentage (%1)"), symbol_prefix[symbol].percentage) or _("Progress percentage"),
        book_time_to_read = symbol_prefix[symbol].book_time_to_read
            and T(_("Time left to finish book (%1)"),symbol_prefix[symbol].book_time_to_read) or _("Time left to finish book"),
        chapter_time_to_read = T(_("Time left to finish chapter (%1)"), symbol_prefix[symbol].chapter_time_to_read),
        frontlight = T(_("Brightness level (%1)"), symbol_prefix[symbol].frontlight),
        frontlight_warmth = T(_("Warmth level (%1)"), symbol_prefix[symbol].frontlight_warmth),
        mem_usage = T(_("KOReader memory usage (%1)"), symbol_prefix[symbol].mem_usage),
        wifi_status = T(_("Wi-Fi status (%1)"), symbol_prefix[symbol].wifi_status),
        page_turning_inverted = T(_("Page turning inverted (%1)"), symbol_prefix[symbol].page_turning_inverted),
        book_author = _("Book author"),
        book_title = _("Book title"),
        book_chapter = _("Chapter title"),
        custom_text = T(_("Custom text (long-press to edit): \'%1\'%2"), self.custom_text,
            self.custom_text_repetitions > 1 and
            string.format(" × %d", self.custom_text_repetitions) or ""),
    }
    return option_titles[option]
end
```

**Comment by arpanghosh8453** [comment]
@poire-z @hius07 I would also like to stop the disappearing of the footer altogether step during cycling the item groups. is there a flag for it which I can use in the user patch?

**Comment by poire-z** [comment]
Untested, quickly written:
```lua
local orig_ReaderFooter_textOptionTitles = ReaderFooter.textOptionTitles
ReaderFooter.textOptionTitles = function(self, option)
    local text = orig_ReaderFooter_textOptionTitles(self, option)
    if option == "time" then
        text = "my new text"
    end
    return text
end
```

>  I would also like to stop the disappearing of the footer altogether step during cycling the item groups. is there a flag for it which I can use in the user patch?

No such flag.
You need to understand (I don't :)) how `ReaderFooter:onToggleFooterMode()` works and patch it (early) so that when it would meet/set `self.mode = self.mode_list.off (=0)`, you somehow skip it - and call the original.

**Comment by arpanghosh8453** [comment]
Thank you for the pointer @poire-z and @hius07 : I have solved it! 

Here is the userpatch code I am using to have two custom item sets and cycle between them. I have replaced the frontlight and frontlight_warmth parameters becasue I have no use for those variables. 

Basically the two sets have chapter specific and book specific stats. I have updated the UI labels too accordingly. Now I just turn those on in the menu and cycle between them. I have added `self:onToggleChapterProgressBar()` inside the modified function so that the progress bar shows the book and chapter specific progress on cycle in sync with the stat. This is exactly what I was looking for. 

Now the only final question I have for you is how I can change the icons with the userpatch. for example I want to replace `percentage = BD.mirroredUILayout() and "⤟" or "⤠"` with `percentage = nil` inside the symbol_prefix -> icons without modifying the original `readerfooter.lua` file. I am sure this is not complicated but with my limited lua knowledge, i can't figure it out.

```lua
local ReaderFooter = require("apps/reader/modules/readerfooter")
local util = require("util")
local logger = require("logger")
custom_seperator = " ⸺ "

local map = util.tableDeepCopy(ReaderFooter.textGeneratorMap)
local orig_ReaderFooter_textOptionTitles = ReaderFooter.textOptionTitles

ReaderFooter.textGeneratorMap.frontlight = function(footer)
    local t = {}
    table.insert(t, map.chapter_progress(footer))
    table.insert(t, map.pages_left(footer))
    table.insert(t, map.chapter_time_to_read(footer))
    table.insert(t, map.book_chapter(footer))
    table.insert(t, map.time(footer))
    table.insert(t, map.battery(footer))
    return table.concat(t, custom_seperator)
end

ReaderFooter.textGeneratorMap.frontlight_warmth = function(footer)
    local t = {}
    table.insert(t, map.percentage(footer))
    table.insert(t, map.page_progress(footer))
    table.insert(t, map.book_time_to_read(footer))
    table.insert(t, map.book_title(footer))
    table.insert(t, map.time(footer))
    return table.concat(t, custom_seperator)
end

-- Replacing UI text labels associated with the replaced items
ReaderFooter.textOptionTitles = function(self, option)
    local text = orig_ReaderFooter_textOptionTitles(self, option)
    if option == "frontlight" then
        text = "Chapter Stat Combo"
    elseif option == "frontlight_warmth" then
        text = "Book Stat Combo"
    end
    return text
end

-- Replacing function for stopping the disapperence of the footer step during cycling (copied from original with thanges)
function ReaderFooter:onToggleFooterMode()
    self:onToggleChapterProgressBar() -- This is to toggle the progress bar between book and chapter mode based on tap to show progress accordingly
    if self.has_no_mode and self.settings.disable_progress_bar then return end
    if self.settings.all_at_once or self.has_no_mode then
        if self.mode >= 1 then
            self.mode = self.mode_list.off
        else
            self.mode = self.mode_list.page_progress
        end
    else
        self.mode = (self.mode + 1) % self.mode_nb
        for i, m in ipairs(self.mode_index) do
            if self.mode == self.mode_list.off then
                break
            end
            if self.mode == i then
                if self.settings[m] then
                    break
                else
                    self.mode = (self.mode + 1) % self.mode_nb
                end
            end
        end
    end
    -- Added code for stopping the disapperence of the footer step during cycling
    if self.mode == 0 then
        for i, m in ipairs(self.mode_index) do
            -- Grab the first enabled option from settings
            if self.settings[m] then
                self.mode = i
                break
            end
        end
        logger.dbg("FooterHack : Replaced self.mode with", self.mode)
    end
    -- End of added code ---------------------------------------------------------
    self:applyFooterMode()
    G_reader_settings:saveSetting("reader_footer_mode", self.mode)
    self:onUpdateFooter(true)
    self:rescheduleFooterAutoRefreshIfNeeded()
    return true
end
```

**Comment by arpanghosh8453** [comment]
Awesome, I have used the `string.gsub` to replace the symbols with empty text before appending to the table. That worked out as I expected! Thank you everyone. I think this userpatch also closes #11590 in favor of the userpatch availability.

**Comment by arpanghosh8453** [comment]
@poire-z sorry to bother you again, but is it possible to have a userpatch on a plugin? or they need to be directly modified?

**Comment by poire-z** [comment]
You can user-patch a plugin.
Stuff added at the bottom of https://github.com/koreader/koreader/blob/master/frontend/userpatch.lua
Example on how to use it at https://github.com/koreader/koreader/pull/11838#issuecomment-2124493747

**Comment by arpanghosh8453** [comment]
Thank you @poire-z

**Comment by Commodore64user** [comment]
> > **NiLuJe** - And how would you envision writing the profile in this scenario?
> 
> I am not a dev so I just share my ideas. And if they are possible, someone implements them as in quick menu, partial rendering, select and highlight mode... But I don't know if they are possible when sharing the idea because I am not a dev.
> 
> **But if you are just curious how I would do that, let's give it a shot >>>** We have a "New profile with current settings" action which does what it says. It saves around 40 settings and when recalled it restores them. And our footer settings are kept in `settings.reader.lua`.
> 
> So this is how I envisioned the procedure:
> 
> 1. User arranges their first status bar config and runs "New profile with current settings"
> 2. Footer config is written into a profile
> 3. User arranges their alternative status bar config and runs "New profile with current settings"
> 4. Second footer config is written into a profile
> 
> When one of these profiles is run, it overwrites `settings.reader.lua` as if the user changed it using the menu.
> 
> But at this point probably there are things I don't know about how all this works so one of our devs says: **"Nope this is problematic because tabledeepcopy triggers thingamabob in the crengine and we don't want to touch that ancient relic"**. Or it is doable but so niche that they decide it doesn't worth the effort, added complexity etc. But I leave these parts to our devs because I am not a dev. I just share ideas. And sometimes they work.

kudos @offset-torque, without my having read this previously (or maybe I had but can't remember), this is pretty much the implementation we ended up with at #13689 save for a few minor differences. I did have to tackle `thingamabob` but totally worth the effort as far as I am concerned ;)

**Comment by offset-torque** [comment]
Aw, thanks. My proposal was based on piggybacking on the profile system to avoid adding a menu but your implementation is much more user friendly with its proper menus. I think this feature will be much appreciated by the users. I will add this to the guide when it lands on release.

One thing I was going to mention was conditional triggering via collections/profiles. This can be really useful like **"Show (the profile with) memory usage when opening big PDFs from this directory"** or **"Show the -book title- instead of -time left items- when opening short articles from the Wallabag collection"**. But I see that you have already started discussing this with **hius07**.

**Comment by Commodore64user** [comment]
> My proposal was based on piggybacking on the profile system

Those are the minor differences… ;)
