### ISSUE TITLE
Book text search - result is not highlighted

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12589]
* KOReader version: 2024.07-214-ga1edbbf0c and 229-gcba79bca1
* Device: Kindle Scribe HF (FW 5.16.21)

#### Issue
I can't **find** the text on the screen that I searched in a book.
It is not highlighted by any means. How do you guys use it?

#### Steps to reproduce
- Open a book
- Seach for a word or phrase
- Tap the magnifying glass icon
- It finds the page with this text, but I don't know where exactly it is.

##### `crash.log` (if applicable)
Let me know if needed.

**Comment by hius07** [comment]
Not clear how to reproduce, 2nd and 3rd steps?

**Comment by mergen3107** [comment]
This is a "Search text" dialog within a book (Find text?). In my case I summon it with a gesture

**Comment by hius07** [comment]
And then? Step 3?

**Comment by mergen3107** [comment]
Ah, sorry. 

In this dialog (Enter text to search for) I got only two options: hit enter, or one of the two arrows. I pressed Enter on keyboard here

**Comment by mergen3107** [comment]
Magnifying glass appears later, to bring back this dialog again

**Comment by mergen3107** [comment]
What's interesting is that if I tap the button "All" to search, it brings the menu with all found items (with matches in bold among some context)

Now, if I tap on any of them, it finds the page and does two more things:
- highlights the whole phrase
- puts a temporary black square on the left

Great! So code is there :D

**Comment by hius07** [comment]
And the "All" button.

When you press Enter, you search forward, jump to the page with the first found string, it gets highlighted.
Is it pdf? Do you see the full page?

**Comment by mergen3107** [comment]
But then the text stays highlighted, but it is not an annotation and will disappear after changing pages forth and back. This part is not very obvious. 

Maybe instead of a temporary black square there should be a permanent magnifying glass icon? That would disappear on page turning

**Comment by hius07** [comment]
What about the issue in the first post? The found string should be highlighted.

**Comment by mergen3107** [comment]
> When you press Enter, you search forward, jump to the page with the first found string, it gets highlighted.
Is it pdf? Do you see the full page?

Yes, everything happens as you describe. 

No, this is an fb2 book. 
Yes, I see the whole page in both cases. But only in the case with "All" I see it highlighted

**Comment by hius07** [comment]
Maybe the highlight is under the dialog? Drag it.

**Comment by mergen3107** [comment]
> What about the issue in the first post? The found string should be highlighted.

It is not highlighted if I search with Enter key or arrows. 

It is highlighted when I use "All" and tap a result

**Comment by hius07** [comment]
Maybe the highlight is under the dialog? Drag it.

**Comment by mergen3107** [comment]
OK, so I did this and confirmed that highlight doesn't appear at all in the first place:
- Search a piece of text that will definitely be outside this small dialog with magnifying glass. 
- After hitting Enter, screen flashed, small dialog appeared, but no highlight or black box next to the line

**Comment by mergen3107** [comment]
Here is a verbose crash log, but I don't see anything interesting in there:
[crash_log_search.txt](https://github.com/user-attachments/files/17253438/crash_log_search.txt)

**Comment by mergen3107** [comment]
[125589_no_highlight_on_text_search.zip](https://github.com/user-attachments/files/17253444/125589_no_highlight_on_text_search.zip)
Book itself with its .sdr.

This one is imported after using in KOReader on Onyx Boox Kon-Tiki 2 (Android 10), but this issue happens on newly opened books too.

**Comment by hius07** [comment]
Cannot reproduce on the latest nightly (229).

![1](https://github.com/user-attachments/assets/9186e992-8618-4b8b-92b6-46e5c54e88fb)

**Comment by mergen3107** [comment]
Yeah, I updated today after this ticket too. The same issue. The log is actually from 229

Weird!

**Comment by mergen3107** [comment]
What's current nightly build number?

I am on Kindle hf, so I compiled myself. 

I got 2024.07-229-gcba79bca1

**Comment by hius07** [comment]
koreader-kindlepw2-v2024.07-229-gcba79bca1_2024-10-02

**Comment by mergen3107** [comment]
Thanks! I realized I can just look here: http://build.koreader.rocks/download/nightly/

Weird, any suggestions what settings I should check?

Any logger.dbg I can add to track it?

I tried refresh rate settings and stuff, also highlights styles - no change.

**Comment by hius07** [comment]
No settings, highlighting is done by the crengine itself:
https://github.com/koreader/koreader-base/blob/d55129ff96de2f1cc22c1a07cff15f2581c9f588/cre.cpp#L3801-L3802

**Comment by mergen3107** [comment]
@benoit-pierre 
Can you please help me diagnose my build?

Is the matching hash (2024.07-229-gcba79bca1) enough to guarantee that I did the build right?

I did submodules update before building, but now I have a vague suspicion that maybe crengine is behind current upstream. 

Thanks!

**Comment by Frenzie** [comment]
No, that's just front. There is no identifier for the used base etc. repo. `git submodule update --recursive` will do all of them.

**Comment by mergen3107** [comment]
Ok, thanks!
Yes, I do recursive update before each build.

**Comment by NiLuJe** [comment]
There's a non-zero possibility you're getting an optimized refresh somewhere on a Scribe.

Do things magically appear if you force a refresh via a diagonal swipe?

**Comment by mergen3107** [comment]
I tried that, and I don't think swipe and other gestures work while this popup is up.

**Comment by mergen3107** [comment]
Yeah, it doesn't work. I tried two more things with no luck:
- Take a screenshot
- Rotate Scribe upside down and back. 
It flashes after each step, but doesn't draw highlights.

Here are screenshots (sorry, I should've supplied them in the OP, for better explanation):
Searching for `kovacs`:
<img src= "https://github.com/user-attachments/assets/6ba11d0e-3030-44bb-907f-436c834858fc" height="600">

No highlights:
<img src= "https://github.com/user-attachments/assets/fb4adcc2-5a43-47f0-b7d9-d8a1a6574bb0" height="600">

When moved too:
<img src= "https://github.com/user-attachments/assets/a6b85368-5fc7-496e-88c7-db03065549fd" height="600">

**Comment by mergen3107** [comment]
Here is how I usually prepare for a build (from Home folder on Ubuntu 24 LTS):
```
cd koreader
git pull upstream master
git submodule update --recursive
git push origin
git status
```

Last command shows something like this:
```
mergen3107@mateLTS22:~/koreader$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Then I check that I am with latest commits: 
```
mergen3107@mateLTS22:~/koreader$ git log --oneline
f0e5acfd2 (HEAD -> master, upstream/master, origin/master, origin/HEAD) android: drop unnecessary code (#12594)
7da143062 dispatcher: SpinWidget range (#12580)
706ab3bdf [plugin] Exporter: fix typo (#12592)
cba79bca1 Quickstart guide Kindle illustrations (#12577)
613877912 Disabled rotation map for Android devices where "hw media keys follow gravity" (#12557)
...
```
It matches the last three commits in https://github.com/koreader/koreader/compare/v2024.07...master :
![image](https://github.com/user-attachments/assets/fb846037-f49e-4d16-bf07-b725d07158b5)

So then I do:
```
# Alternative hf build (WORKED):
export PATH="/home/mergen3107/x-tools/arm-kindlehf-linux-gnueabihf/bin:$PATH"
make TARGET=kindlehf clean
make TARGET=kindlehf download
make TARGET=kindlehf
./kodev release kindlehf
```

This from like a few months ago when I first built kindlehf successfully (even before I actually switched).

Anything wrong you guys can see?

If not, then I have to try without settings...

**Comment by mergen3107** [comment]
What else did not work:
- turning off Kindle MTK's page turn animations
- changing top menu screen dpi.

**Comment by mergen3107** [comment]
Aha! Found it!
Thanks everyone for your kind consideration!

I only have three active patches:
[mergen3107_kopatches.zip](https://github.com/user-attachments/files/17264862/mergen3107_kopatches.zip)

Only one of them was the culprit!
Unfortunately, it is one of my favorite ones: `2-footer-line-word-counts-sessionduration.lua`  that lets me see number of lines in the book.

@poire-z Can you please see if this is fixable?
For the record, here is the original ticket were you presented this great patch :D 
https://github.com/koreader/koreader/issues/10231#issuecomment-1477138340

If not possible, not a big deal. I go back to counting lines by eye.
I don't need it much now anyway, because I have settled all my profiles with fonts and sizes.

**Comment by mergen3107** [comment]
Here is the patch file itself, easier to see in mobile web than the archive:
[2-footer-line-word-counts-sessionduration.lua.txt](https://github.com/user-attachments/files/17264872/2-footer-line-word-counts-sessionduration.lua.txt)

**Comment by mergen3107** [comment]
P.S. I only changed the icon to show in the Porgress bar, I hope it is not the issue.

**Comment by mergen3107** [comment]
> I hope it is not the issue.
Yep, it is not.

So, the way I see it, Full Text Search draws stuff correctly, then the patch goes and counts lines. This action resets the highlights somehow.

**Comment by hius07** [comment]
Yes, once the patch calls `getTextFromPositions`, the highlights made by the search are cleared.

**Comment by mergen3107** [comment]
So, I found out I can keep patch enabled.
But I need to keep its progress bar item unchecked to have the search highlights work.

I guess there is no good way to fix this order?

**Comment by hius07** [comment]
Btw, number of lines is shown in Book information as well.

**Comment by mergen3107** [comment]
@hius07 
Oh, thanks! I forgot about this.

My old use case was to have that progress bar line count to be able to quickly see changes after choosing fonts, sizes, etc in bottom menu.

**Comment by poire-z** [comment]
May be you could add these 4 lines in the WORD_COUNT and LINE_COUNT generators:
```diff
ReaderFooter.textGeneratorMap[WORD_COUNT] = function(footer)
    if not footer.ui.rolling then
        return "n/a"
    end
+   local top_wg = UIManager:getTopmostVisibleWidget() or {}
+   if top_wg.name ~= "ReaderUI" then
+       return "..."
+    end
    local res = footer.ui.document._document:getTextFromPositions(0, 0, Screen:getWidth(), Screen:getHeight(), false, true)
```

**Comment by mergen3107** [comment]
I got this:
```
./luajit: ./patches/2-footer-line-word-counts-sessionduration.lua:105: attempt to index global 'UIManager' (a nil value)
stack traceback:
	./patches/2-footer-line-word-counts-sessionduration.lua:105: in function 'gen'
	frontend/apps/reader/modules/readerfooter.lua:1921: in function 'genFooterText'
	frontend/apps/reader/modules/readerfooter.lua:2061: in function 'updateFooterText'
	frontend/apps/reader/modules/readerfooter.lua:2029: in function 'updateFooterPage'
	frontend/apps/reader/modules/readerfooter.lua:2009: in function 'onUpdateFooter'
	frontend/apps/reader/modules/readerfooter.lua:2379: in function 'refreshFooter'
	frontend/apps/reader/modules/readerfooter.lua:1086: in function 'callback'
	frontend/ui/widget/touchmenu.lua:922: in function 'onMenuSelect'
	frontend/ui/widget/touchmenu.lua:216: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:266: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:101: in function 'handleEvent'
	frontend/ui/uimanager.lua:911: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1438: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1538: in function 'handleInput'
	frontend/ui/uimanager.lua:1582: in function 'run'
	./reader.lua:265: in main chunk
	[C]: at 0x00013ea1
lipc-wait-event exited normally with status: 0
```

**Comment by mergen3107** [comment]
I need to require it in the beginning?

**Comment by mergen3107** [comment]
Yep, I added `local UIManager = require("ui/uimanager")` at the top and it worked.

Solution is fine, but in search I need to tap back/forth at least once to have this new `...` show up.

Right after search, I still see no highlights.

**Comment by poire-z** [comment]
I guess there is a transient few ms where the popup dialog is not yet displayed, so ReaderUI is still on top, and your user patch kills the search highlights.
I don't see in self.ui.search a property that could indicate a search is in progress, so no other idea for a thing to check to prevent your words/lines count to kill the search results highlights...
I suggest you drop words/lines count from your user patch, as they would most often always display the same kind of values, and tidy your footer of static crap :)

**Comment by mergen3107** [comment]
I just don't understand one thing. 

When I open Full Text Search Field window to type in search query, isn't this already non-ReaderUI?

So, by this logic, shouldn't it draw '...' after I hit Search first time?
Or it is late by two steps instead?

**Comment by poire-z** [comment]
Dunno, the input is closed and then the dialog with the arrows is shown. There's a small time frame when there is no dialog, and may be some footer refresh/repaint happens in there.
(If it doesn't draw "..." at the time it draws it, it's because ReaderUI is not the top widget :/)

**Comment by Biep** [comment]
I sometimes have more or less the same issue - but then I cannot find the text at all in the visual window.  Sometimes I find it on a nearby page.  I **think** I only have this with PDFs, and in particular with the Palmer Bible, which is a rather large PDF.
I had never bothered to report this, but it has been like this for - I think - years, both on my now defunct Kobo Aura One and on the PocketBook I have now.

**Comment by mergen3107** [comment]
Closing since the culprit was found (a user patch). 

@Biep 
Feel free to open a new ticket for your issue, it seems unrelated to this one.
