### ISSUE TITLE
2024.07 crashes on Tolino Epos 2

### ISSUE THREAD

**Issue by BurkSchu** [koreader/koreader#12595]
* KOReader version: 2024.07
* Device: Epos 2

#### Issue
KOReader crashes at start. Maybe the same problem as with version 2024.04 on Tolino: https://github.com/koreader/koreader/issues/12210
#### Steps to reproduce
Install 2024.07 (koreader-android-arm-v2024.07.apk) on Epos 2 and start
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by benoit-pierre** [comment]
Try the nightly.

**Comment by pazos** [comment]
> Try the nightly.

Yes please, use https://ota.koreader.rocks/koreader-android-arm64-v2024.07-229-gcba79bca1_2024-10-02.apk.

Also, while you're at it please follow https://github.com/koreader/koreader/issues/8482 and report your device, so we can add support warmth lights again (device was removed because we didn't have the strings to properly identify it)

**Comment by NiLuJe** [comment]
Detailed logs would be helpful.

**Comment by BurkSchu** [comment]
![Crash Nightly 2](https://github.com/user-attachments/assets/607dba63-d913-4b4e-bbea-a5732e1e88d7)
![Crash Nightly 1](https://github.com/user-attachments/assets/761d51c1-d3ea-4c42-a071-96858e742e5a)

That are the screenshots from the nightly build. Is that enough? Or should I post screenshots from the release, too?

**Comment by BurkSchu** [comment]
The order is reversed. ;-)

**Comment by BurkSchu** [comment]
And here come the 2 Screenshots from the release version.
![Crash Release 1](https://github.com/user-attachments/assets/695c4bb1-cc30-405e-9a55-28b94404b73e)

**Comment by BurkSchu** [comment]
![Crash Release 2](https://github.com/user-attachments/assets/080cb08f-f5da-46e4-8368-3917111e8328)

**Comment by NiLuJe** [comment]
I meant something more along the lines of output from `adb log`

**Comment by BurkSchu** [comment]
I think that's all I can give you.

**Comment by pazos** [comment]
> I think that's all I can give you.

I disagree, @BurkSchu. You can do a lot more :)


First of all, I linked you the wrong version (arm64) and your device belongs to a family (tolinos) which don't really care about aosp/android standards.

So please try again, with the latest nightly, this time for your device :): https://ota.koreader.rocks/koreader-android-arm-v2024.07-232-gf0e5acfd2_2024-10-04.apk.

In case it crashes please also attach screenshots like you did previously. They're very useful. Extra points if they're sorted ;)

And sorry about the missguide :/

**Comment by BurkSchu** [comment]
I should have seen that it was the wrong version. The 32-bit version is running!

**Comment by pazos** [comment]
Great!. Now please follow the second part of https://github.com/koreader/koreader/issues/12595#issuecomment-2394099824 to get warmth working for you and everybody else with that device :)

**Comment by BurkSchu** [comment]
[test.log](https://github.com/user-attachments/files/17267440/test.log)
