### ISSUE TITLE
"Saving current book settings as defaults" not working

### ISSUE THREAD

**Issue by 0zd3m1r** [koreader/koreader#12607]
* KOReader version: v2024.07-236
* Device: Kobo Libra 2

#### Issue
I can't apply default settings for all books. For example, when I try to set the _font settings, line spacing, paragraph settings, etc_., for a specific book as the default, it says 'saved,' but when I select "Reset document settings to default' while the same book is open, I realize that it hasn't saved them.

#### Steps to reproduce
1 >> ⇑ TOP MENU → Document→ Save document settings as default
2 >> ⇑ TOP MENU → Document→ Reset document settings to default

**Comment by hius07** [comment]
> when I select 'load default settings'

What is it?

**Comment by 0zd3m1r** [comment]
> > when I select 'load default settings'
> 
> What is it?
Sorry.

⇑ TOP MENU → Document→ Reset document settings to default

**Comment by hius07** [comment]
Can you give the details about the **exact** setting that is not saved: its value before 'Save document settings as default', and its value after 'Reset document settings to default'.

**Comment by 0zd3m1r** [comment]
All the changes I make within "_Style Tweaks_" settings revert to the previous settings. For example, when I select '_font size > ignore publisher font families_' and '_ignore publisher font sizes_,' and choose '_line heights > ignore publisher line heights_,' it says '_saved_' when I click '_Save document settings as default_,'. but when I click '_Reset document settings to default_,' all these settings are lost. I hope i've explained clearly.

**Comment by jonnyl2** [comment]
Style tweaks are distinct from regular document settings. If you want a style tweak to apply to all newly opened and reset books, you will have to long-press on each such tweak.

**Comment by hius07** [comment]
True, only font face and bottom menu settings can be made global via 'Save document settings as default'.
