### ISSUE TITLE
FR: View highlights of current book in a popup window linked to their location in book without exporting 

### ISSUE THREAD

**Issue by arpanghosh8453** [koreader/koreader#12600]
**Does your feature request involve difficulty completing a task? Please describe.**

I want to view the previous highlights of the book when I am reading. I do not want to export them each time I want to view. Additionally, if possible, I would like to view the highlights list hyperlinked to the location they are in the page of the book, so I can go back and read the context.  

**Describe alternatives you've considered**

Currently I export and then open the file if I want to view the highlights of my current book, but this requires too much back and forth and extra file saves on storage.

**Comment by poire-z** [comment]
Isn't this what you get when just hitting `Bookmarks` in the first top menu (or drawing the associated gesture) ? "A list of highlights in a popup windows" and when you tap on one of them, you jump to its page in the book. Without exporting :)

**Comment by arpanghosh8453** [comment]
Opps! Never tried that option as it said `Bookmarks` and I do not do bookmarks in my books. Maybe `Bookmarks/Highlights` would be a better indicator, but now I know this! I just tried it and it looks EXACTLY how I envisioned it. Thank you so much for the pointer. I will close this issue now.

**Comment by mergen3107** [comment]
@hius07 
I remember you replaced all "bookmarks/highlights" with "annotations"?

@arpanghosh8453 
Also, there is a Skim Widget. 
You can also summon it by long tapping the progress bar on the bottom. 

Skim Widget has buttons to jumps to next/previous bookmarks/highlights

**Comment by arpanghosh8453** [comment]
@mergen3107 Thank you so much! Exactly what I hoped for! Looks like you guys thought of every feature I can imagine

**Comment by mergen3107** [comment]
@arpanghosh8453 
When you have time... :D 

http://koreader.rocks/user_guide/
