### ISSUE TITLE
Running KOReader latest nightly on macos without building from source (VM, etc is acceptable)

### ISSUE THREAD

**Issue by zeeyado** [koreader/koreader#12604]
* KOReader version: latest nightlies
* Device: M3 macos 15.0

#### Issue
(I don't need a full dev enviroment as I only want to 1. run the app and 2. develop for fronted lua things, like plugins)

The are no binaries/releases for macos (I understand this is because they are prone to breaking?)

I found it very difficult to build for macos (inexperienced), ran into many issues I couldn't figure out.

Ran an arm64 linux vm (because native) and can run the latest stable .deb for arm64, but I want to run the latest nightlies

Tried building but had similar difficulties on linux arm64 as on macos.

What is the most pain free, least time consuming options for running the latest nightlies on macos on apple silicon?

Emulator VM of amd64 linux, use appimage nightly release?

All i need is a running instance of the latest nightly where I can do frontend plugin stuff.

**Comment by benoit-pierre** [comment]
Check the [Github Actions](https://github.com/koreader/koreader/actions?query=branch%3Amaster): we build artifacts for macOS, ARM64 and x86-64.

**Comment by benoit-pierre** [comment]
But note that the latest builds may be broken.

**Comment by benoit-pierre** [comment]
> > Check the [Github Actions](https://github.com/koreader/koreader/actions?query=branch%3Amaster): we build artifacts for macOS, ARM64 and x86-64.
> 
> Thanks. Sorry for the noob question, but I don't know how to approach this?

If you click on a run, at the bottom, you can download a macOS bundle:
![2024-10-06-160657_792x244_scrot](https://github.com/user-attachments/assets/b4af3fb1-c135-4bb2-af57-8031d6fd378f)

> > What were the issues you encountered when trying to build?
> 
> At first I ran into the issue described here: #12546 With the help of a chatbot and exporting homebrew stuff to path in .zshrc it seemed to build successfully, but no GUI elements were loading, and I didn't understand the discussion about .so and .dylibs so I reverted everything and left it
> 
> Later I tried starting from scratch with xcode 15.2 (because that had worked for the author of the above issue) but I ran into issues with luajit and libviconv and got stuck.
> 
> I am willing to give building another go from scratch, or using the artifacts as you mention (I don't know what these are yet)

The build issues with recent XCode version should be fixed in koreader-base' master, not yet available on the main repo's master. Wait for the builds to finish, and try one of [the artifacts](https://github.com/koreader/koreader/actions/runs/11202576218?pr=12605) from #12605 (which also contains additional macOS related fixes).

**Comment by zeeyado** [comment]
Thank you so much, the artifact from the latest build worked :) 

Are there artifacts like this for all architectures, like .deb for arm64 or appimage for arm64 etc? Or are the actions just for macos? Are these artifacts basically KOReader's "releases" for macos?

**Comment by benoit-pierre** [comment]
> Are there artifacts like this for all architectures, like .deb for arm64 or appimage for arm64 etc? Or are the actions just for macos?

Just for macOS, the nightlies are built by [another CI](https://gitlab.com/koreader/nightly-builds).

> Are these artifacts basically KOReader's "releases" for macos?

See [discussion](https://github.com/koreader/koreader/issues/8797#issuecomment-2303222053).

**Comment by zeeyado** [comment]
Thank you, I've learned a lot, i really appreciate it
