### ISSUE TITLE
FR: Text Editor - Show Line Number

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12618]
**Does your feature request involve difficulty completing a task? Please describe.**
It would be really nice to have an option to see line numbers in documents opened by Text Editor.

**Describe the solution you'd like**
Maybe another toggle button in the Text Editor View, above the keyboard, to enable/disable line numbers?

**Describe alternatives you've considered**
Currently, I can search text in Text Editor very well, and the notification popup tells me something like "Text found on Line X". So, at least, when searching I can be sure that I am on the right line now.

**Additional context**
This will be especially handy for editing KOReader lua files :D 
I understand that is very niche request, so feel free to close it xD

**Comment by poire-z** [comment]
Very niche, and complicated with our TextBoxWidget (or needing some left margin, and complicated code to handle long lines wrapped that makes multiple textboxwidget being the same original file line number).

**Comment by jonnyl2** [comment]
I actually thought about requesting this, but then let it go because yeah, it seemed a bit too niche :). 

My suggestion would have been to display the line number (and perhaps even the horizontal position, e.g. 432/24) in the top right corner of the title bar.

**Comment by Frenzie** [comment]
That's what I was going to suggest. ;-)

**Comment by hius07** [comment]
"Go to" dialog shows current line number as a hint.

**Comment by hius07** [comment]
I propose to change the "Go" button label to the interactive current line number.

![1](https://github.com/user-attachments/assets/f5726131-d45e-4a1a-b361-7b7bd2c65ba2)

![2](https://github.com/user-attachments/assets/e4023004-1eeb-491c-be24-00aaa624fd59)

**Comment by poire-z** [comment]
I find that a bit ugly.
If going with that, it should at least on startup, until the first move, show <kbd>Go</kbd> so a user get a chance to know what the futur replacement number means.

**Comment by hius07** [comment]
> a user get a chance to know

The first pressing on the button gives a good chance.

**Comment by hius07** [comment]
The bold **(line 555)** in the title bar looks ugly too.

**Comment by hius07** [comment]
We start Text editor with cursor at the previous session position, so a user see the current line number at once.

**Comment by hius07** [comment]
Consistent with Skim widget where we press the page number to go to page.

**Comment by poire-z** [comment]
But in SkimWidget, everything is related to pages, so we know that number is a page number.

May be try to find a symbol (evoking "lines") to prepend to that number ?

**Comment by Biep** [comment]
> I actually thought about requesting this, but then let it go because yeah, it seemed a bit too niche :).
> 
> My suggestion would have been to display the line number (and perhaps even the horizontal position, e.g. 432/24) in the top right corner of the title bar.

Same here.  If I know the number of, say, the top line, I can do the remaining counting myself.
Another option would be an addition to the long press pop-up, showing vertical and horizontal position of the cursor.

**Comment by hius07** [comment]
![11](https://github.com/user-attachments/assets/6e1949b7-2a53-4aa0-8062-2bb9aa0bc86e)

![12](https://github.com/user-attachments/assets/27d5bdcd-8929-4093-b6fe-2a32a29236e8)

![13](https://github.com/user-attachments/assets/25b50cb9-bc6f-4b4e-8b05-aee36ceac197)

**Comment by Biep** [comment]
> ![13](https://private-user-images.githubusercontent.com/62179190/375712186-25b50cb9-bc6f-4b4e-8b05-aee36ceac197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDEwOTIsIm5iZiI6MTcyODY0MDc5MiwicGF0aCI6Ii82MjE3OTE5MC8zNzU3MTIxODYtMjViNTBjYjktYmM2Zi00YjRlLThiMDUtYWVlMzZjZWFjMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5NTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMzMyZDg1NDlkMDFhMThjMGQyN2YxMGZiY2JkYzkwNzlhNDhmMmI4N2E0Y2U0NWVlNzFjZmY2ODFhM2QwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.goUkUkqxDaM6o_deZHZlvnKDPZaV0-pLgvCsZxOCgXk)

Of the three, I like this one the best - the lines are actually numbered.

**Comment by hius07** [comment]
The third one looks better in the screenshot than on the small eink screen.
One more:

![14](https://github.com/user-attachments/assets/dabda266-dcde-486d-a007-a210f98c1b08)

**Comment by jonnyl2** [comment]
I like the above one (408) and the 3rd one in the previous post (427) equally well, fwiw.

**Comment by Frenzie** [comment]
What happens with 1000+ lines?

**Comment by hius07** [comment]
Up to 9999 fits, then the font size is shrinked on my Voyage..

**Comment by jonnyl2** [comment]
Is it possible to make the line number not-bold, without affecting the other buttons' style? Not just for more space, it would also look a bit more discreet. (No problem for me either way, though.)

**Comment by poire-z** [comment]
The `☰ 408` example makes it look like a popup, like this one: ![image](https://github.com/user-attachments/assets/e4ce8cd3-5d26-459f-9c0e-d0c49a594168) and we may have a few other similar here and there - so it's probably not the symbol to use if we want UI consistency.
Or you could make it a popup with, in it, more infos and actions.

**Comment by NiLuJe** [comment]
Yup, what @poire-z said, waaay too close to the hamburger icon ;).

**Comment by hius07** [comment]
"Find" button goes to the first row, providing more symmetrical buttons positioning and giving more room for lines number.

![21](https://github.com/user-attachments/assets/72cf8597-2b4f-40ce-9ed8-e0a2a455afcc)

![22](https://github.com/user-attachments/assets/c31d931c-640a-4cdc-8334-e8081664c249)

**Comment by poire-z** [comment]
English has short words, so dunno how it will look (ugly as the smaller "Lua check"?).
Also, it's probably rare one will open a file with 11138 lines :) it will probably never goes over 1999.
But no strong opinion.

**Comment by hius07** [comment]
![25](https://github.com/user-attachments/assets/f1347a9c-10f6-4c61-84c5-a33a8d6d1fb2)

![26](https://github.com/user-attachments/assets/a2d639ac-0a81-4dfb-af5a-721af718f6bd)

**Comment by mergen3107** [comment]
Top one looks good

**Comment by NiLuJe** [comment]
I find the cramped "Lua check" more distracting than the non-bold line numbers (I also find the icon more readable non-bold, for that matter), so, my vote goes to bottom ;).

**Comment by mergen3107** [comment]
What is Lua check by the way?
Is it also new?
What does it check exactly?

**Comment by jonnyl2** [comment]
It checks for syntax errors in Lua code. I don't think it's new?

**Comment by mergen3107** [comment]
Thanks!

(Side thoughts:

It won't, however, save a user from foot gun situations :D 

For example, when you edit a lua file wrong (still with correct syntax), and KOReader crashes upon next restart. 

And you can't revert it if you don't have anything else to edit files on the device (Kobo, Kindle HF).

)

**Comment by jonnyl2** [comment]
For such emergencies (and for testing purposes), I keep a 2nd KOReader installation on my Kobo I can switch to to fix things. But usually it's more convenient to just connect it to a computer anyway.

**Comment by mergen3107** [comment]
How do you move between these two installations on Kobo?

Do you have them both in Nickel Menu / KFMon?

**Comment by jonnyl2** [comment]
Yes, they're both in NickelMenu and also KFMon. One is in folder .adds/koreader and the other in .adds/koreader-test. I just edited the icon for one and duplicated some entry in the configuration file for KFMon (IIRC).

**Comment by mergen3107** [comment]
That's cool! Thanks!
