### ISSUE TITLE
Cannot load Calibre metadata

### ISSUE THREAD

**Issue by andreaschari** [koreader/koreader#12610]
* KOReader version: 2024.07
* Device: Kobo Libra Colour

#### Issue

I cannot search for calibre metadata. Any "Search..." actions show no results, and when prompted to scan "/"mnt," the results always include 1 library with 0 books. I can see there's a metadata.calibre file on my home directory, and looking at it from a PC, I can see there are books in the metadata file.

##### `crash.log` (if applicable)
I found this relevant block of debug messages but doesn't really point me to any problem
```
10/07/24-16:18:22 DEBUG CalibreSearch:getMetadata: Cache timestamp   : 1728287860 2024-10-07T07:57:40.000000+00:00 (2024-10-07 08:57:40 +0100) 
10/07/24-16:18:22 DEBUG CalibreSearch:getMetadata: Metadata timestamp: 1728286560 2024-10-07T07:36:00.114269+00:00 (2024-10-07 08:36:00 +0100) 
10/07/24-16:18:22 INFO  metadata: 0 books imported from cache in 2.000 milliseconds 
10/07/24-16:18:22 WARN  no metadata to search, aborting 
```
Rest of crash log below:
[crash.log](https://github.com/user-attachments/files/17281008/crash.log)

**Comment by pazos** [comment]
> 09/29/24-20:18:40 WARN  Unable to load library from json file /mnt/onboard/metadata.calibre: not enough memory 

Go to the plugin settings -> json and see the options. Try to reproduce with the one named safe.

Just to know, how many books are there? How many MB is the `metadata.calibre` library.

**Comment by pazos** [comment]
Anyhow, it is our bug. The automatic mode shouldn't lead users to OOM errors.

**Comment by andreaschari** [comment]
I tried with "safe" and searched again, with no results, but it works now with the "fast" setting

**Comment by pazos** [comment]
That's.... unexpected. @NiLuJe: yet another evidence we should use "fast" unconditionally ;)

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by pazos** [comment]
> That's.... unexpected. @NiLuJe: yet another evidence we should use "fast" unconditionally ;)

@NiLuJe: Shall I go with it?
