### ISSUE TITLE
FR: Show book rating in File Manager

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12617]
**Does your feature request involve difficulty completing a task? Please describe.**
I would like to be able to see rating I set in books in File Manager as well.

**Describe the solution you'd like**
First of all, I think we should change icons for "Favorite book" or "Rating".
Currently, both of them have an icon of a star.
I think, "Favorites" (or rather Collections in general? A unique icon per collection chosen by user?) should have an icon of a heart (Unicode U+2625, for example, `♥`).

Then, FM should have a black star, added, say, in the string after file type. For example,
`★:5`.

**Describe alternatives you've considered**
No alternatives. Currently, rating is visible only in Book Information or Book Status (soon to be deprecated?).

**Additional context**
I realized that would be a nice feature to have after I started moving books I'd finished in Archive folder. This will give me a quick glance of what books I really liked/disliked.

Thanks!

**Comment by mergen3107** [comment]
This is how I imagine it:
![FileManager_2024-10-10_140116](https://github.com/user-attachments/assets/05ec3f13-2fbd-4d3e-a9b5-3fa823b2c72e)

**Comment by mergen3107** [comment]
Also, make FM show the rating only if there was a rating set in metadata. It is "no stars" by default, but if I understand it correctly, it doesn't say `rating = 0` in the metadata when you first open the book, rating appears only after you set it, right?

**Comment by jonnyl2** [comment]
Duplice of (my) #10381

**Comment by mergen3107** [comment]
Oops! My bad! Closing this ticket in favor of yours.
