### ISSUE TITLE
FR: Text editor: Landscape orientation 

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12622]
While text editor is getting some attention, I'd like to raise a separate issue:

**Does your feature request involve difficulty completing a task? Please describe.**

Line width in many text files is too wide, so that even at a very small font size, not all text fits on each line when viewed on a smaller screen. Text wrapping often makes the file unpleasant to look at and/or to edit. 

Landscape mode would fix this in most cases. Landscape mode is already supported, but can't be enabled from within Text editor. Opening a text file in landscape mode from the reader means having to switch the reader to landscape, wait for doc to rerender, then launching Text editor, and after exiting to Reader, switching back to portrait to continue reading.

**Describe the solution you'd like**

Add a small 'rotate' button, for example at the first position in the first row, (left to <kbd>QR</kbd>, which rotates 90deg clockwise on short-press, and 90deg counter-clockwise on long-press. (Or a toggle that switches between portrait and landscape, but the drawback would be that only one landscape and one portrait mode could be supported.)

**Describe alternatives you've considered**

Alternatively (or as an additional consideration), allow turning off text-wrapping and introduce horizontal scrolling. But that would probably be a lot more involved.

**Additional context**

Saving the last orientation state in the Text editor could be considered (without regard to a particular text file), but not saving would also be okay IMO (so that it just opens in the same orientation as the Reader/FM as i does now, and can then be adjusted by the user within Text editor).

**Comment by Frenzie** [comment]
One possibility is the little titlebar menubutton we've since been using (which could also contain a line number display).

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
