### ISSUE TITLE
FR: A command to open "the text file for this document".

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#12623]
**Does your feature request involve difficulty completing a task? Please describe.**
I, and I understand several others I know, so probably lots of people worldwide, like to have a text file associated with a single document, and that for many documents.  The file may be to collect notes while reading, or to write a review, or for questions about the content - whatever.

Currently, (creating and) opening a text file while reading a document is easy: Tools - Text editor - [choose file] does the trick.  However, dealing with a large number of text files is not trivial.  The command "open last opened text file" already helps a lot (I have a gesture for it), but when switching books one still needs to dive for the (only mentally) associated text file.

**Describe the solution you'd like**
I'd like to see a command "***(create if nonexistent and then) open the text file associated with the currently-open document***".  This will always open the same file for the same document, and different files for different documents.
My proposal would be: a file with the same name as the document, followed by ".txt", in the same folder.
This would allow for meta-files too: if I open such a text file as a document, I can open **its** associated file (which will then have a name ending in ".txt.txt").  One use for that would be in a written dialogue: I write a text, my colleague reads it and responds to it, I then respond to her response again, and so on.  I am not sure how useful this is, but it comes for free, so..

**Describe alternatives you've considered**
Opening up the notes feature - have them in a text file which is then editable - would be an option, but I prefer having the whole text available when I write.  Not every use case is about points that can be precisely attributed to individual passages, let alone follows the linear order of those passages.  Merging those two systems would still be nice, but won't be trivial.
I believe my request is rather trivial to implement, given that the text editor exists already.

**Additional context**
I can't think of any relevant additional context.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Biep** [comment]
Hmm - I got a suspicious comment by mail - and now I see it is **not** here, making it even more suspicious.
It contained a link, and the link contained a fake Captcha that wanted me to copy (Windows+R) and send (Ctrl+V) information.  If others received it - beware!

**Comment by Frenzie** [comment]
A related possibility would be to have recently opened per document rather than global.

**Comment by Biep** [comment]
Yes, that would already help a lot too.

**Comment by Frenzie** [comment]
PS Regarding the spam comment, looks like there was a slew of them. GH must've deleted them following a report.

**Comment by Biep** [comment]
And ideally, all those document-specific files would **not** show in the list of recent documents.  I'd still like a few globally often-used documents visible there.
(Unless there were a division there too: globally recent vs. per-document recent, with some way to prevent the latter to flow over into the former.)

**Comment by Frenzie** [comment]
Looks like they were reported 8 hours ago: https://github.com/koreader/koreader/issues/12660#issuecomment-2436713968

**Comment by jonnyl2** [comment]
I like the idea of a dedicated text file for each book (created on demand). I currently use the book review field to jot down some general notes/thoughts about the book that are not related to a specific part of the book I would otherwise have to highlight. The text editor would make editing the notes a lot more convenient, and a text file would also be more accessible from outside KOReader. (Personally I'd prefer it be stored in the sidecar folder though, along with the other metadata, but that's not super important.)

>[Frenzie] A related possibility would be to have recently opened per document rather than global.

I use the list of recently opened text files to edit non-book related files, such as general notes (e.g., KOReader FR ideas ;) )  and user patches.

**Comment by Biep** [comment]
Oh, the sidecar folder would work well too.  The main idea is not to have two same-titled files clash.
(Though it might kill the recursion - could there be sidecar folders inside sidecar folders?)
And making those text files the same as the book review field in the status window would be fine with me.  (I don't know whether any other people with different use cases would be hindered by it..)

If we want to go **really** wild, there could be a **number** of dedicated files, with the user assigning a use case to them (review, corrections, counterarguments, notes, .. - and the command asking for a character to indicate the intended file.  So, if I wanted to open the review file for the current document, I'd select the command (or perform the gesture), then type, say, `r`, and KOReader would open the `r` text file associated with this document (not knowing what `r` means to me).  That would allow more than enough different use cases for even the most discriminating taste, I'd say, especially with the beautiful gesture-sensitive keyboard KOReader now has.  And having gesture+tap open the precise file I want seems like a quite concise way to get at such files.  (Can the keyboard work such that no `Enter` is needed?)

**Comment by jonnyl2** [comment]
>Oh, the sidecar folder would work well too. The main idea is not to have two same-titled files clash.
(Though it might kill the recursion - could there be sidecar folders inside sidecar folders?)

The way I imagined this is that you would open these text files only using the text editor, which doesn't create any sidecar files itself, and only from the Reader. So for example you would have a gesture for 'Open associated text file' or similar, and then it would create/open the textfile `Shakespeare_RomeoandJuliet.sdr/notes.txt` (or similar) in the text editor. 

>And making those text files the same as the book review field in the status window would be fine with me.

That wasn't my intention at all and I was just doing that as a workaround, because highlighting portions of the book that have nothing to do with my note might be confusing to me when I go back looking at the notes later on. In fact I'd prefer if those types of notes would be kept separate, so the review field can be used for just that -- a review.

**Comment by Biep** [comment]
> The way I imagined this is that you would open these text files only using the text editor, which doesn't create any sidecar files itself, and only from the Reader. So for example you would have a gesture for 'Open associated text file' or similar, and then it would create/open the textfile `Shakespeare_RomeoandJuliet.sdr/notes.txt` (or `Shakespeare_RomeoandJuliet.sdr/Shakespeare_RomeoandJuliet.txt` if the same filename is important) in the text editor. (And it would not leave a record in the recently opened text files at all.)

I understand.  What I meant was: as a subsequent idea I imagined opening such text files themselves as documents, and allowing associated text files for them too.  That might not be possible with your idea - but then it was only a fringe elaboration that would happen to come for free with my approach.

> > And making those text files the same as the book review field in the status window would be fine with me.
> 
> That wasn't my intention at all and I was just doing that as a workaround, because highlighting portions of the book that have nothing to do with my note might be confusing to me when I go back looking at the notes later on. In fact I'd prefer if those types of notes would be kept separate, so the review field can be used for just that -- a review.

Yes - and other people might want to keep yet other kinds of notes separate.  Reviews are just one option - hence my idea of adding a letter.  But all that is secondary to the main step, of having dedicated text files in the first place.

**Comment by hius07** [comment]
Gateway: book information page and an action in Gesture manager to edit.
Screenshots in https://github.com/koreader/koreader/pull/12699.

**Comment by Biep** [comment]
I am back, and have been using the notebook files with great pleasure and gratitude.
My version was 11-44, and it had one serious bug: once in a while, if I opened another text file while reading a document, the opened text file became the notebook for that document: it would show as such in "book information", and open with the gesture for "open associate notebook file".  I'd then have to change the file back to the intended one.
I don't know whether the issue still exists; I haven't had it since upgrading.

I have many more comments, bug fix requests, and a few enhancement proposals - I hope to get around to those.

**Comment by Biep** [comment]
Not sure where we discussed this further - but despite the patch it happened again that the notebook changed.
This time I saw the change in the book information window, and not when I tried to open it - so it is not something to do with the act of opening the notebook file that causes the change.
Again it was changed into another notebook file that I had opened recently.
