### ISSUE TITLE
epub: On turning page, book gets stuck/loops in endnotes/references

### ISSUE THREAD

**Issue by zeeyado** [koreader/koreader#12625]
* KOReader version: 2024-07
* Device: macos, Android, Linux

#### Issue

Open book -> first chapter -> turn page -> endless endnotes

A specific epub ebook (bought officially from Verso Books) doesn't behave correctly in KOReader. 

It works fine in all other apps I have tried (NeoReader (Boox/Android), Callibre (Mac and Linux), Book Reader (Android)).

Navigating to chapters (in TOC) works, but upon turning the page in a given chapter, it seems to parse in the endnotes, and you get stuck flipping through the endnotes.

This happens no matter which chapter you go to.

I can provide more info if needed (book title etc), but perhaps there is a known issue where KOReader thinks an epub is thousands of pages and gets stuck in endnotes and there is an easy formatting/chapter linking fix?

**Comment by poire-z** [comment]
> Navigating to chapters (in TOC) works, but upon turning the page in a given chapter, it seems to parse in the endnotes, and you get stuck flipping through the endnotes.

This description feels like we're not stuck in an infinite loop.
It feels like you are turning page with tap, and you may end up taping on a link and jumping to its targer among the endnodes - and in there, just jumping again around ?
May be disable (in `Tap & gestures > Links >`) "tap to follow links" to see if it is that - and use "swipe to follow nearest link" like anybody sane :)
And use "Swipe to go back" (swipe towards the east) to get out of endnotes and back to the original page when this jumping happens.

**Comment by zeeyado** [comment]
This happens while using the physical buttons.

Basically the book is "normal", 4-600 pages depending on font size, but even in the file viewer it it shows up as having between 25k and 33k pages (depending on where in the book I've flipped to).

Flipping past the first page of the first chapter brings up the endnotes, with about 300 pages left in chapter. Flipping through all of those 300 or so pages brings up the first chapter again, and the same thing happens, except now the pages left in the chapter are in the order of 30k.

It's an interesting problem, especially considering it works fine in other readers/renderers. Must be something with the formatting, but I have no idea.

Will try the latest nightly as suggested above, otherwise if anyone is interested in having a look I guess they could acquire the book (obviously I won't send it here) for research -- I did get a copy from another source just to see, and the same thing happened.

**Comment by zeeyado** [comment]
This is on 2024.07-232 btw. Will test with -241 and edit this

**Comment by benoit-pierre** [comment]
Can you reproduce with a [scrambled version](https://www.mobileread.com/forums/showthread.php?t=267998)?

**Comment by zeeyado** [comment]
> Can you reproduce with a [scrambled version](https://www.mobileread.com/forums/showthread.php?t=267998)?

Yes. Same result

**Comment by benoit-pierre** [comment]
Then please share that version. :P

**Comment by zeeyado** [comment]
[Towers of Ivory and Steel_ How Israeli Uni - Maya Wind_scrambled.epub.zip](https://github.com/user-attachments/files/17347548/Towers.of.Ivory.and.Steel_.How.Israeli.Uni.-.Maya.Wind_scrambled.epub.zip)

**Comment by poire-z** [comment]
Can't reproduce any such behaviour with this scrambled book on the emulator, using my PC keyboard arrow keys to turn pages :/

**Comment by jonnyl2** [comment]
@poire-z: do you have in-page footnotes enabled? I can reproduce it on my 2024.07-232 AppImage.

With in-page footnotes it renders 18,161 pages here, and without 547 pages.

**Comment by zeeyado** [comment]
Changing the style (e.g. Document button -> style -> none/auto/html standard) seems to temporarily make it readable while you are in the book (the page count is still many thousands, though).

**Comment by jonnyl2** [comment]
@zeeyado: try Document button -> Style tweaks -> In-page footnotes -> and then uncheck everything `In-page EPUB footnotes (smaller)` is the default I think.

**Comment by zeeyado** [comment]
^ Can confirm this works

**Comment by poire-z** [comment]
> do you have in-page footnotes enabled?

Ah ah ! alright, so indeed, long or crappy inpage footnotes tagging/targeting indeed may put and duplicate large section of endnotes into the book flow.
The whole container of footnotes is indeed tagged as epub:type=note (singular):
![image](https://github.com/user-attachments/assets/68ac7f5c-2411-4fb9-96a3-29c219bdaace)
so we consider it all as a single footnote we have to show at the bottom of EACH page that has a link to an id inside that container.

So, not really our bug: disable the "In-page EPUB footnotes" style tweak, and enable the "In-page classic classname footnotes" one (it should work as the individual P have `class=note`).

**Comment by jonnyl2** [comment]
Yep, this works. If you want the in-page footnotes (recommended), go to Document menu, long press on Book-specific tweak, and then enter 

`p.note { -cr-hint: footnote-inpage; }`

And tap Apply.

**Comment by zeeyado** [comment]
Thank you for the help 

Is this something to be fixed in KOReader's epub footnote handling or do you consider it poor formatting from the publisher?

I'll leave it to you to close the issue

**Comment by poire-z** [comment]
Poor formatting: the publisher shouldn't use `epub:type="note"` ("note" singular) for the whole endnotes section ; it's supposed to be used to wrap each individual footnote.
