### ISSUE TITLE
FR: Larger delay for gyro rotation

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12666]
**Does your feature request involve difficulty completing a task? Please describe.**
Gyro rotation happen too quickly on Kindle Scribe.

**Describe the solution you'd like**
Would be great to have a delay (maybe customizable) that decides to rotate the screen.
Use case: when I would like to rotate by 180 deg.
Naturally, I just rotate CW or CCW until it is 180 deg apart.
KOReader is rotating once: only by 90 deg, then doesn't register another 90 deg (because it was busy rendering double columns in a epub book, I guess). So I have to rotate it back and forth by 90 deg again.

**Describe alternatives you've considered**
Try to rotate by pushing Kindle at the top, so it never sees any 90 degree rotations. However, it is awkward to handle Kindle in this case.

**Additional context**
I didn't use 90 deg rotations before exactly because of this (and too high sensitivity when it triggers the rotation), so I kept `Lock auto rotation to current orientation` turned on.

However, with the invention of https://github.com/koreader/koreader/pull/12612 now I really enjoy my auto-profiles, so I keep it off now.

**Comment by mergen3107** [comment]
I tested it again. It definitely disregards the second 90 deg rotation once it gets busy rotating and switching columns. However, this is only for an epub. PDF is OK. Presumably, because PDF rotation and zooming of a single page are much faster than re-arranging the whole document to double-column in CRE.

I'll get logs and videos later.

**Comment by mergen3107** [comment]
So, what I am saying is that the second 90 deg rotation out of two does not get queued

**Comment by mergen3107** [comment]
Here is the video (90 MB):

https://disk.yandex.com/i/85ky_M315VpSFg

**Comment by mergen3107** [comment]
Here is the crash.log from that video:
[crash_rotation180.txt](https://github.com/user-attachments/files/17467509/crash_rotation180.txt)

**Comment by mergen3107** [comment]
All my profile, including the ones that makes it double/single column upon rotation:
[crash_rotation180_profiles.lua.txt](https://github.com/user-attachments/files/17467513/crash_rotation180_profiles.lua.txt)

```
    ["Auto Double Column"] = {
        ["settings"] = {
            ["name"] = "Auto Double Column",
            ["order"] = {
                [1] = "visible_pages",
                [2] = "zoom",
            },
        },
        ["visible_pages"] = 2,
        ["zoom"] = "contentwidth",
    },
    ["Auto Single Column"] = {
        ["settings"] = {
            ["name"] = "Auto Single Column",
            ["order"] = {
                [1] = "visible_pages",
                [2] = "zoom",
            },
        },
        ["visible_pages"] = 1,
        ["zoom"] = "content",
```

**Comment by NiLuJe** [comment]
```
557:10/21/24-18:26:48 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 15, time: 1729549608.825355 
559:10/21/24-18:26:54 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549614.756684 
619:10/21/24-18:26:56 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 16, time: 1729549615.612695 
622:10/21/24-18:26:59 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549619.750856 
624:10/21/24-18:27:00 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 16, time: 1729549620.609972 
724:10/21/24-18:27:04 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549624.591122 
796:10/21/24-18:27:06 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 15, time: 1729549625.213275 
815:10/21/24-18:27:07 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549627.945962 
817:10/21/24-18:27:08 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 15, time: 1729549628.493023 
1221:10/21/24-18:27:17 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549637.393307 
1254:10/21/24-18:27:18 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 16, time: 1729549638.094763 
1325:10/21/24-18:27:21 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549641.528338 
1360:10/21/24-18:27:22 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 15, time: 1729549642.075349 
1431:10/21/24-18:27:34 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 17, time: 1729549654.026679 
1466:10/21/24-18:27:35 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: 15, time: 1729549655.275381
```

That's a lot of jitter for a 180 o_O.

**Comment by mergen3107** [comment]
> That's a lot of jitter for a 180 o_O.

Can be me holding it with one hand? 433 g Scribe + 198 g Cover is no joke :D I sort of touched after the first rotation.

**Comment by mergen3107** [comment]
In this FR, what is suggested is to let KOReader wait (say for 1.0 s) after a gyro event is detected (90 deg), then see if another gyro event was found (another 90 deg) and do only the final target rotation (i.e. 180 deg delta). This way the resources to draw it every 90 deg (like when it works properly in PDF) will be saved as well

**Comment by NiLuJe** [comment]
Too tired to make sense of the crap event reporting on Kindle but I'd wager some of what I'm seeing would sum to 0 here ;).

**Comment by mergen3107** [comment]
Can it also be a screen protector I applied? :D

**Comment by poire-z** [comment]
I believe that @mergen3107 , in addition to [being a better CI than any automated CI](https://github.com/koreader/koreader/issues/12339#issuecomment-2284959548), can now rival with [automated fuzzy testing tools](https://en.wikipedia.org/wiki/Fuzzing).
> fuzz testing is an automated software testing technique that involves providing invalid, unexpected, or random data as inputs to a computer program

**Comment by mergen3107** [comment]
Aww, too kind :D

**Comment by mergen3107** [comment]
By the way, pen was away at the time of video (it was usually a source of a lot of single-pixel coordinate reporting that bloats crash.log to as high as 5 MB sometimes).

**Comment by NiLuJe** [comment]
> Too tired to make sense of the crap event reporting on Kindle but I'd wager some of what I'm seeing would sum to 0 here ;).

```
10/21/24-18:26:48 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549608.825355
10/21/24-18:26:54 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549614.756684
10/21/24-18:26:56 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UD, time: 1729549615.612695
10/21/24-18:26:59 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549619.750856
10/21/24-18:27:00 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UD, time: 1729549620.609972
10/21/24-18:27:04 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549624.591122
10/21/24-18:27:06 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549625.213275
10/21/24-18:27:07 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549627.945962
10/21/24-18:27:08 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549628.493023
10/21/24-18:27:17 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549637.393307
10/21/24-18:27:18 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UD, time: 1729549638.094763
10/21/24-18:27:21 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549641.528338
10/21/24-18:27:22 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549642.075349
10/21/24-18:27:34 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549654.026679
10/21/24-18:27:35 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549655.275381
```

So, if I group things up:

```
10/21/24-18:26:54 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549614.756684
10/21/24-18:26:56 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UD, time: 1729549615.612695
```

```
10/21/24-18:26:59 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549619.750856
10/21/24-18:27:00 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UD, time: 1729549620.609972
```

```
10/21/24-18:27:04 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549624.591122
10/21/24-18:27:06 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549625.213275
```

```
10/21/24-18:27:07 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549627.945962
10/21/24-18:27:08 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549628.493023
```

```
10/21/24-18:27:17 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549637.393307
10/21/24-18:27:18 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UD, time: 1729549638.094763
```

```
10/21/24-18:27:21 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549641.528338
10/21/24-18:27:22 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549642.075349
```

```
10/21/24-18:27:34 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: CW, time: 1729549654.026679
10/21/24-18:27:35 DEBUG input event => type: 3 (EV_ABS), code: 24 (ABS_PRESSURE), value: UR, time: 1729549655.275381
```

Which looks much saner, but that's still *a lot* of turns. Does it roughly match with how the device was moved?

**Comment by mergen3107** [comment]
I don't think I jittered a lot when moving in that video. 

Maybe gyro is giving all these incremental points?

**Comment by mergen3107** [comment]
Ah, OK. In that case I think it is OK. 

In the video, I first rotated Kindle CW by 180 deg (from U to D). However, KOReader only rotated 90 deg (from U to R). So then I went back CCW from D to R to then rotate again CW from R to D.

Then I repeat all these steps in reverse, going from D to U - half rotation happened again. This is with epub.

Then I open PDF and do same rotations again. This time, KOReader catches up, rotating twice on the way from U to D and D to U.

**Comment by mergen3107** [comment]
Although, this doesn't answer why there so many same CW+UD/UR rotations. 

There are no DR, RD, or CCW

**Comment by NiLuJe** [comment]
Oh. It might be the input inhibition on document thingy (can't recall when exactly it happens. Reload?) that might be screwing with you there...

**Comment by NiLuJe** [comment]
Dunno which one exactly (because there's a few plausible sources), but you do get small windows of input inhibition on those logs, and they often clip part of those rota events.

**Comment by mergen3107** [comment]
Is this fixable?

**Comment by NiLuJe** [comment]
Unlikely, as I really really really don't want to debounce the gyro handles ;).

**Comment by mergen3107** [comment]
Thanks for having a look!

**Comment by mergen3107** [comment]
Unfortunately, I couldn't achieve the smoothest UX using gyro, as described in this ticket.

So, as a workaround (for anyone else interested), here is what I ended up with:
- Top menu - Screen - Rotation: Check `Lock auto rotation to current orientation`. This will make it so it will only rotate by 180 deg using gyro, between +/-90 or +/-180 deg orientations (U/D or L/R in Kindle terms
- Added a rotation-triggered profile (thank you @hius07 !) to make reflowable books double columns if screen is rotated to 0/180 deg, and single column when rotated to +/-90 deg. Similar idea for fixed-layout books.
- Added two simple profile to rotate by -90 or 90 deg. Automatic profile works in manual rotation too!

**Comment by hius07** [comment]
> * Added a rotation-triggered profile (thank you @hius07 !) to make reflowable books double columns if screen is rotated to 0/180 deg, and single column when rotated to +/-90 deg.

Currently this profile is not applied if you rotate the device when History/Collections is opened over the Reader.
Do you think this behaviour should be changed?

**Comment by mergen3107** [comment]
@hius07 
I think it is OK. 

In current setup, I locked rotation only between respective 180 deg. 

That means, I am not able to rotate History by 90 deg with gyro (and there is no setting to rotate manually, which is fine). So, I won't be in a situation where I rotated in History and came back to book to see Profile didn't apply (single column in landscape, for example).
