### ISSUE TITLE
Kindle Scribe: Upside down touch in D orientation (again)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12662]
* KOReader version: v2024.07-255-g54e33d27e + https://github.com/koreader/koreader/pull/12658
* Device: Kindle Scribe (5.16.2.0.1 - back to non-hf)

#### Issue
I am pretty sure this wasn't the case around June 5, 2024: https://github.com/koreader/koreader/pull/11809#issuecomment-2150787659

This was when I left attempt to fix swipe direction when starting in D orientation.

#### Steps to reproduce
Rotate Kindle upside down in Kindle UI, start KOReader.
Observe that 1) in rendered upside down; and 2) touch input is correct (so physical top part of the screen brings up the top menu, which is rendered upside down).

##### `crash.log` (if applicable)
[crash1_start_in_U.txt](https://github.com/user-attachments/files/17450495/crash1_start_in_U.txt)
[crash2_start_in_D.txt](https://github.com/user-attachments/files/17450496/crash2_start_in_D.txt)

What has changed since then? O_o

**Comment by mergen3107** [comment]
> 1) in rendered upside down; and 2) touch input is correct

Sometimes these two are opposite (but still misaligned).

**Comment by mergen3107** [comment]
Culprit found (but I don't know why O_O)
According to this code:
https://github.com/koreader/koreader/blob/54e33d27ea32f4feb99266dca9b42a53dc24e5cf/frontend/device/kindle/device.lua#L1614-L1624

if `orientation_code = D`, then `rotation_mode must have been `2`, but it ends up being `0`. 

```
10/20/24-10:17:03 DEBUG orientation_code = D 
10/20/24-10:17:03 DEBUG rotation_mode = 0 
10/20/24-10:17:03 DEBUG self.screen.DEVICE_ROTATED_UPRIGHT = 0 
10/20/24-10:17:03 DEBUG self.screen.DEVICE_ROTATED_UPSIDE_DOWN = 2 
```

**Why?**

**Comment by mergen3107** [comment]
(Last three debug lines I added myself)

**Comment by mergen3107** [comment]
`10/20/24-10:17:03 DEBUG orientation_code = D ` tells me that lipc works OK

**Comment by mergen3107** [comment]
I checked the type of `orientation` code and it looks OK:
```
10/20/24-10:28:04 DEBUG type(orientation_code) string 
```

**Comment by mergen3107** [comment]
I added more debugs:
```
            if orientation_code then
                logger.dbg("is this loop alive?")
                if orientation_code == "U" or "L" then
                    rotation_mode = self.screen.DEVICE_ROTATED_UPRIGHT
                    logger.dbg("is this loop alive? 1")
                elseif orientation_code == "D" or "R" then
                    rotation_mode = self.screen.DEVICE_ROTATED_UPSIDE_DOWN
                    logger.dbg("is this loop alive? 2")
                end
            end
```
It wrongly falls into the first part (as if `orientation_code` was U or L) in both cases (when I start in U or D):

```
10/20/24-10:31:51 DEBUG orientation_code = U 
10/20/24-10:31:52 DEBUG is this loop alive? 
10/20/24-10:31:52 DEBUG is this loop alive? 1 
10/20/24-10:31:52 DEBUG rotation_mode = 0 
10/20/24-10:31:52 DEBUG self.screen.DEVICE_ROTATED_UPRIGHT = 0 
10/20/24-10:31:52 DEBUG self.screen.DEVICE_ROTATED_UPSIDE_DOWN = 2 
10/20/24-10:31:52 DEBUG type(orientation_code) string 
```

```
10/20/24-10:33:12 DEBUG orientation_code = D 
10/20/24-10:33:12 DEBUG is this loop alive? 
10/20/24-10:33:12 DEBUG is this loop alive? 1 
10/20/24-10:33:12 DEBUG rotation_mode = 0 
10/20/24-10:33:12 DEBUG self.screen.DEVICE_ROTATED_UPRIGHT = 0 
10/20/24-10:33:12 DEBUG self.screen.DEVICE_ROTATED_UPSIDE_DOWN = 2 
10/20/24-10:33:12 DEBUG type(orientation_code) string 
```

**Comment by mergen3107** [comment]
Is this some Lua problem?

**Comment by mergen3107** [comment]
If I force `rotation_mode` to 2, it all works OK.

So the culprit is this loop...

**Comment by mergen3107** [comment]
OK, I think I fixed it, but still don't know why it worked :D 
I put these conditions in parentheses:
```
if orientation_code == **(**"U" or "L"**)** then
...
elseif orientation_code == **(**"D" or "R"**)** then
```
and it worked!

I double checked with and without parentheses, it actually is the culprit.

Can someone please let me know what happened here Lua-wise?

Should we go and check all `elseif var = A or B` statements?

**Comment by benoit-pierre** [comment]
It should be `orientation_code == "U" or orientation_code == "L"`.

**Comment by benoit-pierre** [comment]
```lua
▹ luajit -e 'print(("U" or "L"))'
U
▹ luajit -e 'orientation_code = "U"; print(orientation_code == "U" or "L")'
true
▹ luajit -e 'orientation_code = "L"; print(orientation_code == "U" or "L")'
L
▹ luajit -e 'orientation_code = "D"; print(orientation_code == "U" or "L")'
L

```

**Comment by mergen3107** [comment]
Thanks @benoit-pierre !

I am just puzzled why it had worked here: https://github.com/koreader/koreader/pull/11780 

I am pretty sure I tested them all (U, D, L, R). 

Did something change in Lua base (core? luajit?)?

**Comment by benoit-pierre** [comment]
Nope! :P
