### ISSUE TITLE
"Open previous document" lacks filename on new install

### ISSUE THREAD

**Issue by protist** [koreader/koreader#12675]
* KOReader version: 2024.07
* Device: Kobo Forma

#### Issue
This is an extremely minor issue, but I thought to report it anyway. I just migrated from a Kobo H2O Aura to a Kobo Forma, and of course the first thing I did was to install KOReader!

In the three-line "hamburger" menu in the top right, you can switch to the previous document. In my old install (originally installed ~10 years ago, but kept updated), this menu item includes the name of the document, i.e. `Previous: <filename.epub>`. However, in the new install, it just says `Open previous document`, without the filename.

#### Steps to reproduce
1. Tap the hamburger menu.
2. Look for the previous document.

**Comment by mergen3107** [comment]
There is a setting for exactly this in Top Menu (FM).

**Comment by protist** [comment]
Ahhh thank you @mergen3107 . I manually copied over all my settings, but I obviously forgot about the "hidden" file manager settings.

For anyone trying to find this in the future, navigate to the file manager, then tap on the filing cabinet icon > `Settings` > `History settings` > `Show filename in Open last/previous menu items`.

**Comment by mergen3107** [comment]
View settings (like Mosaic view, etc and types of things to show in detailed view) from FM Top menu are not in the settings.lua file. They are in a database file, along with all cover thumbnails. 

As a side effect, if you reset thumbnail cache from FM Top menu, your view settings will be reset as well.

**Comment by protist** [comment]
Thanks again. I originally `diff`ed files in my settings directories, but decided to manually reconfigure most of the new system instead, since it seemed a bunch of options had changed. I just forgot to check the file manager settings.
