### ISSUE TITLE
FR: Support exporting epub to PDF

### ISSUE THREAD

**Issue by mrdylanyin** [koreader/koreader#12671]
I know there are many tools for converting epub to pdf, but after trying them, the typesetting effects are not very good. If I use pandoc + LaTeX, all the styles in the original epub are lost, and style adjustments rely on templates. So I was thinking, if koreader could leverage its typesetting advantages to support exporting to PDF, that would be great. I'm not sure how much work this FR would involve. Additionally, if anyone can recommend a tool for converting epub to pdf with excellent typesetting, I would be very grateful.

**Comment by Frenzie** [comment]
There's an epub2pdf.sh script using Prince.

https://www.mobileread.com/forums/showthread.php?t=62939

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
