### ISSUE TITLE
Crash when opening

### ISSUE THREAD

**Issue by KindlyOnes** [koreader/koreader#12687]
* KOReader version: v2024.07 105231 (Android)
* Device: 
Android: 21
samsung
Model: GT-I9500
ROM: LRX22C.I9500XXUHPJ3
#### Issue
Crashes when opening.
#### Steps to reproduce
Open the app
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:
[1730029272767.txt](https://github.com/user-attachments/files/17533721/1730029272767.txt)

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
Try a current nightly instead: https://build.koreader.rocks/download/nightly/

**Comment by KindlyOnes** [comment]
> Try a current nightly instead: https://build.koreader.rocks/download/nightly/

Nights version works. Thank you.
