### ISSUE TITLE
Word of warning -- KOReader nightly killed my K4NT

### ISSUE THREAD

**Issue by cccslater** [koreader/koreader#12692]
Hello,

I have been using the unstable channel recently because of a bug fix I need.
I recently (past week) updated and noticed some odd behaviour when entering sleep.
I exited KOReader to see if it would go away, and the Kindle loading screen appeared. The progress bar didn't fill up at all and the screen kept blinking.
I did a proper reboot and got 'Your Kindle needs repair' screen with 'framework' (leftover KOReader or KUAL?) in the bottom right corner. Tried another reboot and now the screen is permanently blank.
Does not show up as a mass storage device either so can't fix.

Less a bug report more of a Watch out! if you are on an older Kindle :-)

**Comment by Commodore64user** [comment]
Plug it to a wall charger and let it be (don't fiddle with it) for up to 24 hours. Other than that i guess @NiLuJe can provide more guidance.

**Comment by cccslater** [comment]
Thanks. I don’t think charging will help, it was nearly full battery — something’s got corrupted I suppose. I’ve already bought a new one because they are SO cheap nowadays and koreader has become part of my daily life :-)

**Comment by NiLuJe** [comment]
Unlikely to be anything specifically related to something you did, device is just old, and Kindles like to softlock themselves at the first thing of trouble.

(The rootfs is RO on Kindles, so you can't really break anything without *really* trying to).

e.g., looks like some manner of storage failure to me.

**Comment by cccslater** [comment]
Thanks for that info. Good to know it probably wasn't my fault.

It _was_ doing some odd things when entering/exiting sleep while reading PDFs though. I would test on my next one but I'd rather stick to stable from now on :-)

**Comment by Commodore64user** [comment]
I have gotten the YKNR before and the endless boot loop and have been able to get around them by plugging the device to power and letting it do its thing, but since OP seems to be to good to try anything I won't bother trying to help.

**Comment by cccslater** [comment]
I don't think there's any need for name calling :-)
I just don't have time to mess with this stuff, I need it for my lecture notes.

**Comment by Frenzie** [comment]
> It was doing some odd things when entering/exiting sleep while reading PDFs though. 

Couldn't mess up anything beyond things related to that PDF. ^_^

**Comment by cccslater** [comment]
I did think it was unlikely. Just seemed a bit of a coincidence that I see bugs > I reboot > it dies, so I thought I'd mention it in case someone else were to have the same problem.
If I'm feeling brave when I get the new one I'll load the nightly and report the weirdness.

**Comment by NiLuJe** [comment]
Lie I said, nightly or not won't change a thing.

Depending on what exactly you're talking about, the fact that it went wonky before dying strongly suggests oncoming hardware failure ;). i.e., I see this as a logical progression, not a coincidence ;).

If you do have some spare time to throw at it (and assuming it's not actually failed storage or power, because that will just make an already confusing process downright intractable), if you manage to find a live mirror of Kubrick, and a suitable old host machine to boot it from, that device *can* be flashed from scratch.

**Comment by cccslater** [comment]
Ok, that makes a lot of sense. Kubrick is worth a go, thanks for pointing that out! I probably jumped to the conclusion in my title a little quickly :-)
Thank you everyone for your advice 👍
