### ISSUE TITLE
FR: [Wallabag] Do not treat `on hold` articles as finished

### ISSUE THREAD

**Issue by fenuks** [koreader/koreader#12698]
**Does your feature request involve difficulty completing a task? Please describe.**
Wallabag plugin has  `Remotely delete finished articles` option which not only removes articles marked as `Finished`, but also one which are `On hold`. It is [checked here](https://github.com/koreader/koreader/blob/c2d109997687c793a8592b36e0879bfdcfbbfe14/plugins/wallabag.koplugin/main.lua#L832). I find it rather surprising, because I don't consider such articles finished, and I tend to use this state to mark articles that are not readable (e.g. due to wrong conversion to an epub file).

**Describe the solution you'd like**
I would like articles `On Hold` to be ignored. Other possibility is adding new  `Remotely delete abandoned articles` to make this behaviour configurable.

**Comment by Frenzie** [comment]
Please feel free to submit a PR. :-)

**Comment by fenuks** [comment]
I will try. I think adding an option is generally better idea, so I will do that instead simply ignoring abandoned articles.
