### ISSUE TITLE
Bluetooth keyboard events are handled as `EVT_TOUCHDOWN` / `EVT_TOUCHUP` on Pocketbook

### ISSUE THREAD

**Issue by tommiv** [koreader/koreader#12703]
* KOReader version: 2024.07 "Outside"
* Device: Pocketbook Inkpad 4

#### Issue
This will be a rather long text, please bear with me.

So, I'm trying to make a tiny bluetooth gamepad (8bitdo micro) to work as a page turner on my Pocketbook Inkpad 4.

I've paired it with the device in 'K' mode, which is essentially a HID keyboard emulation (two other modes, which are Switch protocol and DirectInput are not pairing at all). I've confirmed it works like a hardware keyboard, pairing it with my laptop and desktop PC, in both hitting some keys literally emit a character input in the terminal or any other input app.

Next step was to try it with a native reader app. It works like intended, though one need to map keyboard "keys" to the reader's actions first.

Finally, I've tried to do the same with koreader and failed. `event_map.lua` like the one below made no difference.
```lua
return {
    [100] = "LPgBack",
    [99] = "LPgFwd",
}
```
(I can see in logs it's being loaded correctly).

So I started to dig deeper with verbose debug logging. This is what I've found so far:

Normal physical keys on the device are emitting "key events", like in this snippet:
```
11/03/24-18:41:07 DEBUG PB event => 25 (EVT_KEYPRESS), par1: 25, par2: 0 
11/03/24-18:41:07 DEBUG key event => code: 25 (LPgFwd), value: 1, time: 1730652094.464732 
...
11/03/24-18:41:07 DEBUG PB event => 26 (EVT_KEYRELEASE), par1: 25, par2: 0 
11/03/24-18:41:07 DEBUG key event => code: 25 (LPgFwd), value: 0, time: 1730652094.647482 
...
11/03/24-18:41:09 DEBUG PB event => 25 (EVT_KEYPRESS), par1: 24, par2: 0 
11/03/24-18:41:09 DEBUG key event => code: 24 (LPgBack), value: 1, time: 1730652096.457639 
...
11/03/24-18:41:09 DEBUG PB event => 26 (EVT_KEYRELEASE), par1: 24, par2: 0 
11/03/24-18:41:09 DEBUG key event => code: 24 (LPgBack), value: 0, time: 1730652096.585119 
```

The behavior above is what I was hoping to see with the gamepad as well, only with different key codes. However, this is what actually happens:
```
11/03/24-18:41:47 DEBUG PB event => 40 (EVT_TOUCHUP), par1: 36, par2: 0 
11/03/24-18:41:47 DEBUG PB event => 41 (EVT_TOUCHDOWN), par1: 36, par2: 0 

11/03/24-18:41:48 DEBUG PB event => 40 (EVT_TOUCHUP), par1: 35, par2: 0 
11/03/24-18:41:48 DEBUG PB event => 41 (EVT_TOUCHDOWN), par1: 35, par2: 0 

11/03/24-18:41:48 DEBUG PB event => 40 (EVT_TOUCHUP), par1: 34, par2: 0 
11/03/24-18:41:48 DEBUG PB event => 41 (EVT_TOUCHDOWN), par1: 34, par2: 0 

11/03/24-18:41:49 DEBUG PB event => 40 (EVT_TOUCHUP), par1: 23, par2: 0 
11/03/24-18:41:49 DEBUG PB event => 41 (EVT_TOUCHDOWN), par1: 23, par2: 0 
```
And if I read `ffi/input_pocketbook.lua:translateEvent()` correctly, such events are just being logged and ignored, so they are not translated to linux events to be consumed later.

Additionally:
- they look like they're in the wrong order (I assume you need to touch down first, then lift the finger up)
- reported `par1` is way out of range the gamepad actually emits – 36, 35, 34, 23, while the lowest code the gamepad reports is 99 on the dpad-up button, so I'm not sure it's safe to "translate" them to keyboard events.

I did one more exercise and connected a "real", full-sized physical bluetooth keyboard (MX Keys) to the device, just to make sure that discrepancy is within the "Inkview", whatever it is. Alas, exactly the same behavior: EVT_TOUCHUP/EVT_TOUCHDOWN events, wrong order, weird `par1`.

So, do you guys have any idea if this is fixable? I assume Inkview is some kind of a low-level c library you don't fully own or maintain (correct me if I'm wrong) and that's why you have lua code translating its events to normalized ones, and that's why solutions might be pretty limited.

One way I see is I just spend an hour or two in normalizing these touch events in `translateEvent()`, swapping the order and mapping `par1` to real key codes. This might and probably WILL work, but this will mean a system script edit, so I'll need to patch input_pocketbook.lua after every koreader update; also this solution won't help anybody but me, so I only see this option as a last resort.

The fact that the native reader has no problem with this, makes me think that it's not all lost.

Please let me know if you need me to try/debug something on the real device.

**Comment by NiLuJe** [comment]
Yep, InkView is PocketBook's middleware, and, clearly, it's reporting something funky ;).

Assuming these specific events don't occur naturally (and, err, while we don't use them, their names are... not encouraging, as I would expect to see them quite often for actual touch interactions), you could simply make sense of it in `translateEvent`and spit out sensible evdev events that we can actually use.

I'm not concerned about the up/down inconsistency, that's only an amusing minor detail.

Since you've tried a full keyboard, if you can somehow make sense of how the par1 gets mangled, you might be able to figure out a way to translate that to sensible Linux keycodes.
There *might* be a table of keycodes hidden somewhere in the InkView SDK (or not, good luck ;p). Or you might need to poke at the actual library to see if you can suss it out.

I'm vaguely hoping that whatever happens naturally does so with fairly innocuous par1, e.g., to distinguish between fingers or pen (àla ABS_MT_TOOL), which should make a generic approach viable, assuming a mapping to sane keycodes can be figured out.

**Comment by NiLuJe** [comment]
In any case, there's absolutely nothing we can about it ourselves, besides cheering someone from the sidelines, as none of us have access to such a device, and most of us have unfamiliar with the platform.

i.e., someone will have to do the actual work.

**Comment by NiLuJe** [comment]
> And it turns out that it's simply because the events have been renamed/reordered in InkView 6...

For reference, IIRC, what we're using was generated from a 5.17 SDK from https://github.com/blchinezu/pocketbook-sdk

As you might have surmised, getting up-to-date stuff out of PB is a bit of a "fun" experience...

**Comment by tommiv** [comment]
@NiLuJe thank you for such a detailed answer. I was afraid you'll say something like this. Please don't close the issue yet, I'm definitely going to play with it and will post results here.

I wonder though, is it possible to somehow make my `translateEvent` patch a plugin or something like this, so it could survive koreader update? Unless you want to incorporate it into the core distribution, of course.

**Comment by NiLuJe** [comment]
If you can figure out a sane and generic mapping translation, I'm all for merging that, definitely ;).

**Comment by NiLuJe** [comment]
That, and `translateEvent` is a local function anyway, so you can't easily user-patch it anyway ;).

(And even if you could, you'd have to duplicate it in full in any case).

**Comment by tommiv** [comment]
@NiLuJe So... I figured it out and it's embarassing. Basically it's a combination of two facts:

1) As you've already pointed it out, in v6 of SDK PocketBook introduced a breaking change with events constants.

While koreader's `inkview_h.lua` has
```cpp
static const int EVT_TOUCHUP = 40;
static const int EVT_TOUCHDOWN = 41;
static const int EVT_TOUCHMOVE = 42;
```

in SDK's `inkview.h` touch events have been moved to 47, 48 and 49, and "old" 40, 41 and 42 are now being called `EVT_KEY*_EXT`:
```cpp
#define EVT_KEYPRESS_EXT 40
#define EVT_KEYRELEASE_EXT 41
#define EVT_KEYREPEAT_EXT 42

#define EVT_TOUCHUP   47
#define EVT_TOUCHDOWN 48
#define EVT_TOUCHMOVE 49

// It also adds a bunch of new ones, but I don't think it's relevant now
```
Now, I have no idea what's so EXT about new events, they just report keys in `par1` while `par2` is 0. Maybe it start making sense when you connect a full keyboard and hold modifier keys, might check it later. In the end I made a patch (pr is [here](https://github.com/koreader/koreader-base/pull/1970)) changing constants in `inkview_h.lua` and consuming them in `translateEvent` – it all works now. It's probably safe to merge, since old `EVT_TOUCH*` were ignored in koreader anyway, but I can't be sure because I'm not aware of the koreader's architecture and might be missing something regarding BC to older PocketBooks.

2) _I have become comfortably dumb._ You might be asking now: how the hell it works with just constants replace if `par1` was mangled? Well it's because it wasn't. It was me, ignorant of the fact that virtual keycodes are platform dependant and readings I've got on my laptop and PC, while consistent with each other (I run mac os on both), are irrelevant to the reader, since it runs linux. I can confirm that `par1` reports correct keys according to the linux `input.h` table. At least to [this one](https://github.com/pocketbook/SDK_6.3.0/blob/dd8de463733a2bc0d53d1214b64734586fac427e/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/include/linux/input.h#L196) in SDK.

Here's a log example after the patch:
```
11/04/24-13:45:14 DEBUG PB event => 40 (EVT_KEYPRESS_EXT), par1: 46, par2: 0 
11/04/24-13:45:14 DEBUG key event => code: 46 (LPgFwd), value: 1, time: 1730720741.037432 
...
11/04/24-13:45:14 DEBUG AutoTurn: onInputEvent 
11/04/24-13:45:14 DEBUG goto relative screen: 1 in mode: page 
11/04/24-13:45:14 DEBUG CreDocument: goto page 437 flow 0 
...
11/04/24-13:45:14 DEBUG PB event => 41 (EVT_KEYRELEASE_EXT), par1: 46, par2: 0 
11/04/24-13:45:14 DEBUG key event => code: 46 (LPgFwd), value: 0, time: 1730720741.231596 
11/04/24-13:45:14 DEBUG AutoStandby:onInputevent() instance= table: 0x9ff5a358 
11/04/24-13:45:14 DEBUG AutoStandby: input packed too close to previous one, ignoring 
```

@biep: Indeed, during the **input** a hardware keyboard is being completely ignored in both koreader or any of native inputs, for instance the search box of the library. This must be something more fundamental, because 1) it doesn't work in native apps; 2) I see "key events" in koreader's log when I press keys (after my patch though, they are still _EXT events). Gladly, keyboard input was never my goal.

**Comment by Biep** [comment]
> Gladly, keyboard input was never my goal.

As for me - as an avid document commenter, having a working external keyboard would have been worth having.  Typing long texts on the screen keyboard is.. suboptimal.

**Comment by tommiv** [comment]
@Biep understandable. Yet, since it doesn't work in native apps, my assumption is your problem lays beyond koreader reach. You may try to create a separate issue about it, who knows. I can only confirm that maintainers solution for my problem doesn't solve yours – I've checked it.

**Comment by tommiv** [comment]
Closed in favor of https://github.com/koreader/koreader-base/pull/1971

**Comment by Biep** [comment]
> @Biep understandable. Yet, since it doesn't work in native apps, my assumption is your problem lays beyond koreader reach. You may try to create a separate issue about it, who knows. I can only confirm that maintainers solution for my problem doesn't solve yours – I've checked it.

Yes, that's what I feared all along.  I might create an issue for it - here I mentioned primarily because it seemed potentially relevant, and I wanted to indicate my willingness to experiment.  Thanks for checking, by the way!

**Comment by kaznelson** [comment]
> For reference, IIRC, what we're using was generated from a 5.17 SDK from https://github.com/blchinezu/pocketbook-sdk

Could this help?..
https://github.com/pocketbook/SDK_6.3.0/releases/tag/6.8

**Comment by NiLuJe** [comment]
> > For reference, IIRC, what we're using was generated from a 5.17 SDK from https://github.com/blchinezu/pocketbook-sdk
> 
> Could this help?.. https://github.com/pocketbook/SDK_6.3.0/releases/tag/6.8

Ugh. Good to know they hid the latest one in plain sight -_-".

What was committed was based on the 6.5 one, FWIW.
