### ISSUE TITLE
Crash on amazon kindle fire android

### ISSUE THREAD

**Issue by clach04** [koreader/koreader#12737]
* KOReader version: https://github.com/koreader/koreader/releases/tag/v2024.07 - https://github.com/koreader/koreader/releases/download/v2024.07/koreader-android-arm-v2024.07.apk also tried droid build
* Device: kindle fire, android 5.1.1

#### Steps to reproduce

1. Install
2. attempt to launch/open

[shared_text.txt](https://github.com/user-attachments/files/17762810/shared_text.txt)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by clach04** [comment]
Workaround, fdroid v2024.03.1 loads without error 🎉 . Not tested any other versions (or any ebooks yet).

**Comment by clach04** [comment]
Previous version https://github.com/koreader/koreader/releases/tag/v2024.04 works fine.

**Comment by NiLuJe** [comment]
Try a current nightly instead: http://build.koreader.rocks/download/nightly/

**Comment by clach04** [comment]
Confirming that https://github.com/koreader/koreader/releases/tag/v2024.11 also works 👍
