### ISSUE TITLE
The UI is not displaying correctly on the Android phone.

### ISSUE THREAD

**Issue by Hhsy083212** [koreader/koreader#12733]
Many thanks to the developers for porting KOReader to the Android platform. I have been using KOReader on my Android phone, and the functionality is working fine, but there are some issues with the UI display.

![mmexport1731491807495](https://github.com/user-attachments/assets/929a1a38-444d-4cd4-81b6-c17eba5866d5)
![mmexport1731491804519](https://github.com/user-attachments/assets/66fc45fd-f42b-4a09-96cc-c8f167c30aff)

Please see the attached image. The bottom of the phone screen displays correctly, but at the top, it shows a solid black area. This display looks very uncoordinated. Could you please improve it to make the layout more balanced?

Thank you.

**Comment by pazos** [comment]
Nope.

**Comment by Hhsy083212** [comment]
@pazos Since this is the case, could the bottom be changed to be the same as the top? That way, at least it would look more coordinated.

**Comment by pazos** [comment]
> could the bottom be changed to be the same as the top?

It could be but we want to keep the current implementation.

I'll give it a look at making at [userpatch](https://github.com/koreader/koreader/wiki/User-patches) for you. Give me a couple of days.

**Comment by Hhsy083212** [comment]
@pazos Thank you for your response! The number of Android devices in use is huge, especially among mobile users, so any improvement is meaningful. Making the bottom design similar to the top would at least make it more coordinated. Please consider this suggestion. Thanks again!

**Comment by hugleo** [comment]
@Hhsy083212 Maybe a userpatch similar to this one can work for you: https://github.com/koreader/koreader/issues/10698#issuecomment-1638383819

**Comment by pazos** [comment]
> @Hhsy083212 Maybe an userpatch similar to this one can work for you: [#10698 (comment)](https://github.com/koreader/koreader/issues/10698#issuecomment-1638383819)

I think that worked with static values. Not sure if it will work as is with dynamic resizes based on surface changes.
