### ISSUE TITLE
Does increasing contrast through KOreader change the VCOM setting.

### ISSUE THREAD

**Issue by notthatch** [koreader/koreader#12730]
Changing the VCOM can damage my screen so I want to know before I increase the contrast long term. Please let me know

**Comment by NiLuJe** [comment]
Nope, we don't do any of that (it's not actually supported on most of the platforms we run on anyway ;)).

**Comment by Frenzie** [comment]
Put another way, it's more similar to something like https://www.imagemagick.org/script/command-line-options.php#brightness-contrast
