### ISSUE TITLE
Rakuyomi entry not found after installation on a Kindle PW (Gen 5)

### ISSUE THREAD

**Issue by jovaniedelacruz** [koreader/koreader#12740]
* KOReader version: 2024.07
* Device: Kindle Paperwhite PW (Gen 5)

#### Issue
Installation seemed straightforward so I'm having difficulty understanding where I could be making a mistake. Does this plugin work on an older Kindle such as the original PW gen 5? Even if I had an invalid json file for settings I'd expect to see the plugin entry somewhere.
#### Steps to reproduce
1. Download Rakuyomi Kindle release 1.10.1
2. Place rakuyomi.koplugin folder into /koreader/plugins/
3. Place settings.json into /koreader/rakuyomi/ with a valid source_lists following configuration instructions
4. Eject and run Koreader
5. Click the "Search" menu to find "Rakuyomi" entry

![20241116_130437](https://github.com/user-attachments/assets/4bb7db66-e07a-4f27-b369-8e578f731d09)

**Comment by jovaniedelacruz** [comment]
Had the wrong repo open my mistake. Meant to post this issue to Rakuyomi

**Comment by Frenzie** [comment]
The device in question shouldn't matter unless potentially if there are binary parts involved btw.
