### ISSUE TITLE
FR: [Kindle NT] "Gesture manager" equivalent for Non-Touch devices

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12744]
**Does your feature request involve difficulty completing a task? Please describe.**
First and foremost, thank you very much @Commodore64user for supporting Non-Touch devices throughout the past year. Last time I tried KOReader legacy was on Kindle Keyboard back in Sep-Oct 2023, and it wasn't a great experience.

Now, I on Kindle 4 Non-Touch I was greeted with a cool quick start guide telling me there are now shortcuts that make life easier.

**Describe the solution you'd like**
This FR is about making a "gesture manager" ("Key shortcuts manager"?) for non-touch devices.

I noticed that `Top menu - Gear - Screen - Sleep screen - Wallpaper - Postpone screen update after wake-up` still has `Until 'exit sleep screen' gesture` option:
![Reader_2024-11-16_152052](https://github.com/user-attachments/assets/d59cad3f-6e28-4130-b614-3af15cd9d797)

However, due to lack of "gestures" on non-touch devices, there is no gesture manager per se and this option is a rudiment on such devices.

If it is to stay, it would great to make a "Key shortcuts manager" that can record a key combination (very much like multiswipe gesture manager can record a gesture) and then this could be assigned to other stuff.
- Unlock combination
- Quick Menu list (I don't know if QM is supported on non-touch at all). This would be especially handy for switching between my preset profiles that actually scaled very well between Scribe screen and this tiny 800x600 px screen, using a different global dpi :D 
- Any other dispatcher items basically (like book statistics, etc).

**Describe alternatives you've considered**
No alternatives, I have no idea how key combinations are mapped and maybe it is a difficult task to make a manager that can "record/capture" combinations.

**Additional context**
I was thinking about Keyboard + page turn buttons combinations mostly.

(By the way, Keyboard + Press combination is a very cool addition - it is basically the long press equivalent on touch devices! I am able to quickly apply profiles from top menu - profiles for now)

**Comment by mergen3107** [comment]
Overall, I am very impressed by KOReader running on such an archaic device!
It has a mere 256 MB of RAM and slow processor, but I am yet to find a situation where it struggles, even in regular mode (vs no-framework mode)...

Great job on optimization, guys! :D I saw memory usage go up to only 40-50 MB in the status even when I opened a large book with Dante's Divine Comedy with illustrations. What a champ!

KOReader gave a truly second life for this device, that even makes me hesitate about trading it in for a discount from Amazon, lol. It is tiny and lightweight, however lack light.

**Comment by Commodore64user** [comment]
Well @mergen3107 it is your lucky day, check out #12484. It doesn’t let you create shortcuts like in multiswipes but, you sure can do everything else gesture manager lets you do.

**Comment by mergen3107** [comment]
Thank you!! 

Let me see if I can squeeze in a few minutes of tests today before it gets sent out for trade-in. 

So I can provide you feedback :D 

(so far I think I only need to a get a Pocketbook to test KOReader, otherwise I've tested every platform KOReader supports xD)

**Comment by Commodore64user** [comment]
>Thank you!!

you're welcome.

> Let me see if I can squeeze in a few minutes of tests today before it gets sent out for trade-in.

I wouldn't trade it in, buy a damaged one for that, or an echo or anything else really.

> So I can provide you feedback :D

that'd be great.

**Comment by mergen3107** [comment]
Kindle 4 NT doesn't have `patch` :D 

So my usual routine to try a PR on the fly got stuck for now. 

I'll try to spin up Debian Jesse (armel) in a VM to try to get the binary from it...

**Comment by Commodore64user** [comment]
You could just download the three files and paste them in the plugin folder

**Comment by mergen3107** [comment]
> You could just download the three files and paste them in the plugin folder

So I did, thank you!
I didn't realize it was just a new plugin, so just adding new folder and files worked :D 

Feedback: AWESOME!
Look at this beautiful Quick Menu called by `ScreenKB+RPgFwd`:
![Reader_2024-11-18_120940](https://github.com/user-attachments/assets/8ad92a79-2bfc-4fa2-a1e1-6109810bbd4f)

However, one shortcut didn't work for me: `ScreenKB+Down` for `History` (it was `Book Map` by default).
It still summons Book Map.

Here is my hotkeys shortcuts settings file: 
[hotkeyshortcuts.lua.txt](https://github.com/user-attachments/files/17803981/hotkeyshortcuts.lua.txt)

**Comment by mergen3107** [comment]
Also, `ScreenKB+Press` didn't work to replace it to `Full Screen Refresh`, it still defaults to add current page to location history.

**Comment by mergen3107** [comment]
Other than that, I only have questions/suggestions:
- Can each button have also long-press or double-press?
- Can `Screensaver unlock gesture` analogy be implemented for buttons?

Long-press might be really helpful to do something like `10 pages Forward/Back` on long-press of page-turn buttons

**Comment by mergen3107** [comment]
Also, inspired by default actions (https://www.mobileread.com/forums/showthread.php?t=152104),
another shortcut might be added to `input` mode:
- `ScreenKB + PgFwd` to add a white space

**Comment by mergen3107** [comment]
> I'll try to spin up Debian Jessie (armel) in a VM to try to get the binary from it...

Welp, apparently this doesn't work, you can't use Oracle VM to run `arm` on a `amd64` architecture...

**Comment by Commodore64user** [comment]
I'm outside at the moment so can't answer yet but could you please transfer questions, suggestions and comments in general to the PR?  I can see those from the IDE which makes everything easier as opposed to here where i have to go to the website ;)

**Comment by mergen3107** [comment]
Sure thing!

**Comment by mergen3107** [comment]
Thanks @benoit-pierre 
I extracted it using PeaZip (on Windows)
`patch` from the link above yielded this:
```
[root@kindle koreader]# ./patch
./patch: /lib/libc.so.6: version `GLIBC_2.28' not found (required by ./patch)
./patch: /lib/libc.so.6: version `GLIBC_2.17' not found (required by ./patch)
```

I'll go try older versions

**Comment by mergen3107** [comment]
Hooray!

Thank you so much again!
This version worked great on Kindle 4 NT: https://archive.debian.org/debian/pool/main/p/patch/patch_2.6.1-3_armel.deb
Here is the local copy (remove .zip) for history: 
[patch_2.6.1-3_armel.deb.zip](https://github.com/user-attachments/files/17805041/patch_2.6.1-3_armel.deb.zip)

Quick How-To for those curious.
I usually do this:
1) Go to a PR link, and add `.diff` in the end.
2) Save that text file as say `XXX_patch.diff`, where `XXX` is the number of the PR
3) Put both `patch` and `XXX_patch.diff` to `koreader` folder on Kindle
4) From ssh/sftp terminal on Kindle:
```
cd /mnt/us/koreader
```
5) To apply a patch: `patch -p1 < XXX_patch.diff`
In case of success, the output will be ONLY lines like (the number of lines is the same as number of files pathed in the `diff` file)
```
patching file PATH_TO_FILE
```
6) To undo the patch: `patch -p1 -R < XXX_patch.diff`
The same lines as above should appear in case of success.

**Comment by mergen3107** [comment]
Follow https://github.com/koreader/koreader/pull/12484#issuecomment-2495768295 for details about implementation.

**Comment by Commodore64user** [comment]
Let the merge close the ticket ;)
