### ISSUE TITLE
Screenshots missing when taken when there is no folder for them

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12742]
* KOReader version: 2024.07-285-gfd3727274 (legacy)
* Device: Kindle 4 Non-Touch (FW 4.1.4)

#### Issue
I had copied KOReader settings from a Kindle Scribe backup (mostly just `settings.reader.lua`, patches and style tweaks).
It had Screenshots in KOReader configured to be stored at `/mnt/us/screenshots/`, however I forgot to create it on Kindle 4 Non-Touch.
When I did a screenshot in KOReader on K4NT, it showed the usual UI that screenshot is taken and stored in that folder. However, there was no screenshot because folder didn't exist and KOReader didn't create a folder. I don't know how other platforms behave in that case.

##### `crash.log` (if applicable)
I don't think crash.log captured it, but annyway here is all crash.log I got from the beginning of using KOReader on K4NT (it is the same as another issue):
[crash_K4NT_hidden_titles.log.txt](https://github.com/user-attachments/files/17788095/crash_K4NT_hidden_titles.log.txt)

**Comment by mergen3107** [comment]
Eventually, I created a folder and screenshots started to appear. 

I don't know where other screenshots where "saved", but KOReader even didn't know there is a problem :D 

IIRC, KOReader lets you select a screenshot folder from that selector UI, where you can long-press a folder or create a new one. So, in this context it is impossible to select a non-existing folder. 

This issue can reproduced in two ways:
- copy settings from another device, as I did with K4NT
- or select an existing folder but then delete it outside KOReader (or maybe even from withing KOReader).

Screenshot actions needs to check the folder and make one (or notify user and ask for action?)

**Comment by Commodore64user** [comment]
I am fairly confident that the screenshots folder is already included with stable releases. You should not need to create it, that is weird.

**Comment by benoit-pierre** [comment]
It is, but in that instance, the default was changed (`/mnt/us/screenshots/` instead of `/mnt/us//koreader/screenshots/`).

**Comment by mergen3107** [comment]
Yes, all of the above is true. 

I used to have a screenshot folder in the "USB root" for years, much easier to reach to them (including Android devices)

**Comment by mergen3107** [comment]
Thank you @hius07 !

**Comment by mergen3107** [comment]
By the way, similar thing happened to me with Exporter plugin.

Again, the path is in the `settings.reader.lua`, but folder doesn't actually exist.

When tried to export, an Info Message says `text: Failed to export.` (where `text` is the target name I chose).

**Comment by mergen3107** [comment]
Should I open a new ticket?

**Comment by benoit-pierre** [comment]
Yep, see https://github.com/koreader/koreader/pull/12655#issuecomment-2489527804.

**Comment by mergen3107** [comment]
Thanks!
