### ISSUE TITLE
Highlight options dialog: possible Delete/Details button confusion

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12754]
Just a minor thing I'd like to call attention to. This issue might want to be considered for the impending release, so I'm tagging @Frenzie and @hius07 due to possible urgency. 

While working with the new `ReaderHighlight` features I've been noticing that it's very easy to confuse the similarly named <kbd>Delete</kbd> and <kbd>Details</kbd> buttons. It is therefore very easy to accidentally tap the wrong one when working with document highlights and just glancing at the buttons:

![Screenshot_2024-11-20_15-16-27 (copy 1)](https://github.com/user-attachments/assets/710573ff-76a7-4c0a-8549-a2cb0161c932)

Besides renaming the Delete button to something like <kbd>Remove</kbd> or <kbd>Erase</kbd> (which are worse choices, IMO), one could also replace it with the trash can icon (`"\u{F48E}"`) (or rename "Details", but I wouldn't know to what):

![Screenshot_2024-11-20_15-19-25 (copy 1)](https://github.com/user-attachments/assets/acea4f36-b4b9-410b-96c5-c5c61e998543)

Just thought I'd bring this up before the release goes out (which I'm sure will be a great hit; amazing work went into it), but if it's considered a non-issue, that's also okay from my side.

**Comment by mergen3107** [comment]
I also found it weird one day to have `Delete` button as the first choice in that popup.

I would image, first thing you would like to do is maybe add a note, then change style/color, and only then Delete.

**Comment by Frenzie** [comment]
Depends how you look at it. To me it's the delete popup with an assortment of other random features. :-P

An icon is fine by me. Do we have a precedent?

**Comment by jonnyl2** [comment]
>An icon is fine by me. Do we have a precedent?

It's not currently in use in the actual code, AFAIK (a code search for the unicode also brought up nothing). It was one of the symbols originally proposed by @hius07 (for the icons-only version). 

I think we also don't have a precedent of mixing an icon button with other text buttons. I think in this case it would be an okay compromise because the alternative English words are not as good ("remove" is not quite harsh enough and feels like it is missing the 'what', and "erase" feels a bit too harsh for just a highlight/note).

**Comment by Frenzie** [comment]
Could you stick it in a PR so it can be merged at will?

**Comment by hius07** [comment]
It's a favorite @poire-z's button, pinging.
Since the release is delaying, if agreed it can be added to https://github.com/koreader/koreader/pull/12721 and merged.

**Comment by Frenzie** [comment]
> Since the release is delaying

It's ready to go now ftr. ;-)

**Comment by hius07** [comment]
I didn't mean to criticize, sorry.

**Comment by Frenzie** [comment]
I didn't take it that way, I just meant to convey that I'm now at a point where I'm confident tagging it.

**Comment by jonnyl2** [comment]
I didn't know a PR on my own repo would close this...

**Comment by poire-z** [comment]
> It's a favorite @poire-z's button, pinging.

I don't remember :) I think I indeed didn't mind the delete icon being a button, but I found https://github.com/koreader/koreader/issues/12439#issuecomment-2322975723 and https://github.com/koreader/koreader/pull/12461#issuecomment-2329312293 where I'm not sure I was thinking that :)
Anyway, no problem, we'll see how it looks.

> I also found it weird one day to have `Delete` button as the first choice in that popup.

It is not the _first_ choice, it is the _left most_ choice :)
It's consistent with how we layout other button tables: thinking about right handed people (who makes a users base larger than left-handed people), we put the most dangerous (including the ones that need to go online/enable wifi and cause an uninterruptible pause) buttons on the left, so that when holding the device in a single (the right) hand, they can't reach the dangerous left most buttons easily, and probably have to use their second hand.
We tested that on rats in labs, and all the rats survived ! so we shipped it to humans :)

**Comment by Frenzie** [comment]
While you're mostly being facetious, as a left-handed person I didn't think the UI was particularly optimized one way or the other. :-)

**Comment by Commodore64user** [comment]
> It is not the first choice, it is the left most choice :) 

It is on NT though.

> as a left-handed person I didn't think the UI was particularly optimized one way or the other. :-) 

That's where you went left... (for context, in England, "If you break down [on the motorway] - go left!" is an official slogan)

> It's ready to go now

So why not release it then?

**Comment by mergen3107** [comment]
> they can't reach the dangerous left most buttons easily

So let's put them in the very middle! No one will reach those >:D

**Comment by poire-z** [comment]
> > It is not the first choice, it is the left most choice :)
> 
> It is on NT though.

I think we discussed that in the past, and I may have tried to implement logical cycling of focus from right to left - and it may have been tough/impossible with non-regular layouts (ie. row of 3 then row of 2 then row of 3). Or something like that.
