### ISSUE TITLE
Q: Why Exporter plugin says "(outdated)" next to its name?

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12763]
I noticed on Kindle 4 NT that Exporter plugin has `(outdated)` next to its name.

Is it going to be deprecated?

**Comment by hius07** [comment]
Because it has features that will be removed soon
https://github.com/koreader/koreader/blob/9aa327a9dec259dcf407ae8eee2c9f963a0c6083/plugins/exporter.koplugin/_meta.lua#L6

**Comment by pazos** [comment]
A long press on the plugin will give you details (even translated!) :)

**Comment by mergen3107** [comment]
Thanks! 
I got confused because it sounds like it about to removed altogther :D  
Or that there is another, newer, plugin version somewhere else, but I don't have it.
