### ISSUE TITLE
[Kindle NT] Terminal plugin - Shell is not executable (and no Time Sync)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12760]
* KOReader version: 2024.07-285-gfd3727274 (legacy) newer versions don't have fixed at the moment (2024.11 just got released, with two more unrelated commits).
* Device: Kindle 4 Non-Touch (FW 4.1.4)

#### Issue
Terminal emulator doesn't launch with the default `su` or `sh` Shell executable.
Suggested default one (`%1`) gets accepted, but when launching terminal emulator nothing happens.

```
11/20/24-16:44:27 DEBUG Terminal: resolution= 74x22 
11/20/24-16:44:27 DEBUG Terminal: slave_pty /dev/pts/3 
sh: command: not found
sh: command: not found
11/20/24-16:44:27 ERROR failed to call event handler onTerminalStart plugins/terminal.koplugin/main.lua:193: attempt to index local 'shell' (a nil value)
```

#### Steps to reproduce
Try to open Terminal Emulator on Kindle 4 Non-Touch.

##### `crash.log` (if applicable)

![crash_no_terminal log](https://github.com/user-attachments/assets/a1dca256-0a33-463e-8eda-d02a1a04ec51)
[crash_no_terminal.log.txt](https://github.com/user-attachments/files/17837115/crash_no_terminal.log.txt)

**Comment by Frenzie** [comment]
`su` is substitute user, typo?

**Comment by mergen3107** [comment]
Probably a remnant from transferring from Scribe.

Do you know what is default one in a fresh install?

I don't have access to Scribe nor emulator right now...

**Comment by Frenzie** [comment]
sh should work on anything

**Comment by mergen3107** [comment]
Sorry, I forgot to link this comment: https://github.com/koreader/koreader/issues/12741#issuecomment-2484112118

So, K4NT is an archaic animal with non-POSIX-compliant shell.

Thus, `command` itself is NOT available, including KOReader calls.

**Comment by mergen3107** [comment]
Specifically, this check fails for sure:
https://github.com/koreader/koreader/blob/9aa327a9dec259dcf407ae8eee2c9f963a0c6083/plugins/terminal.koplugin/main.lua#L95-L98

You can see it in the beginning of the crash log, right after initialization of KOReader, Terminal Emulator plugin throws:
```
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
11/20/24-16:39:11 DEBUG Terminal: default shell is nil 
11/20/24-16:39:11 DEBUG RD loaded plugin terminal at plugins/terminal.koplugin 
```

**Comment by mergen3107** [comment]
There is also another one before time sync (can't test it right now though):
```
sh: command: not found
sh: command: not found
11/20/24-16:39:11 DEBUG Plugin plugins/timesync.koplugin/main.lua has been disabled. 
```

**Comment by benoit-pierre** [comment]
So the autodetection won't work, but you should be able to set it explicitly.

Other potentially impacted plugin, `plugins/timesync.koplugin/main.lua`:
```lua
local ntp_cmd
-- Check if we have access to ntpd or ntpdate
if os.execute("command -v ntpd >/dev/null") == 0 then
    -- Make sure it's actually busybox's implementation, as the syntax may otherwise differ...
    -- (Of particular note, Kobo ships busybox ntpd, but not ntpdate; and Kindle ships ntpdate and !busybox ntpd).
    local path = os.getenv("PATH") or ""
    for p in path:gmatch("([^:]+)") do
        local sym = lfs.symlinkattributes(p .. "/ntpd")
        if sym and sym.mode == "link" and string.sub(sym.target, -7) == "busybox" then
            ntp_cmd = "ntpd -q -n -p pool.ntp.org"
            break
        end
    end
end
if not ntp_cmd and os.execute("command -v ntpdate >/dev/null") == 0 then
    ntp_cmd = "ntpdate pool.ntp.org"
end
if not ntp_cmd then
    return { disabled = true, }
end
```

**Comment by mergen3107** [comment]
So, I guess it is no bueno for these plugins on K4NT?

No hard attachments to them, just trying to see what things can be fixed on K4NT (while I am at it).

If no fix is possible, then let's just disable them for K4NT.

**Comment by benoit-pierre** [comment]
For the terminal plugin, try setting the shell manually in `settings.reader.lua`:
```lua
["terminal_shell"] = "/bin/sh",
```

**Comment by mergen3107** [comment]
Oh, cool!
Thanks, that fixed it!

How about time sync? A worse case?

**Comment by benoit-pierre** [comment]
> How about time sync? A worse case?

I don't know: I tested 3 versions of `ntpd`: the executable provided by the Arch Linux `ntp` package, the executable on my kindle, and the busybox variant provided by Arch Linux 's package, and they don't all support `ntpd --version` for detection, but `ntpd --help` works, so that first check could be changed to:
```lua
if os.execute("ntpd --version >/dev/null") == 0 then
```

But both `ntpdate` versions I tested (kindle and Arch Linux `ntp` package) don't support a `--version` or `--help` argument, so no easy way to get rid of that `command` use.

**Comment by benoit-pierre** [comment]
Anyway, if you have a `ntpd` executable, give the patch above a try.

**Comment by mergen3107** [comment]
Can you please explain in short the purpose of `command` command? I found a link to IBM documentation, but I don't think I understood it

I can try running ntp things in ssh itself

**Comment by mergen3107** [comment]
> Anyway, if you have a `ntpd` executable, give the patch above a try.

I'll get back to you soon

**Comment by benoit-pierre** [comment]
> Can you please explain in short the purpose of `command` command? I found a link to IBM documentation, but I don't think I understood it

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html

**Comment by benoit-pierre** [comment]
Updated the patch: should be using `--help`, not `--version` (in case it's provided by busybox).

**Comment by mergen3107** [comment]
So, neither `ntp` nor `ntpd` are present on K4NT at all...
Let me see if Debian Pool can rescue me this time :D

**Comment by mergen3107** [comment]
```
[root@kindle root]# ntpd --help
-sh: ntpd: not found
[root@kindle root]# ntp --help
-sh: ntp: not found
```

**Comment by benoit-pierre** [comment]
The second executable the plugin checks for is `ntpdate`, not `ntp`.

**Comment by mergen3107** [comment]
```
[root@kindle bin]# ntpdate
20 Nov 22:31:46 ntpdate[5106]: no servers can be used, exiting
```

**Comment by mergen3107** [comment]
So, the `ntpdate --help` is not great:
```
[root@kindle bin]# ntpdate --help
ntpdate: unknown option --
ntpdate: unknown option -h
ntpdate: encryption delay lp is unlikely
usage: ntpdate [-46bBdqsuv] [-a key#] [-e delay] [-k file] [-p samples] [-o version#] [-t timeo] server ...
```

I replaced both `command` checks to their `--help` variants, plugin didn't show up

**Comment by benoit-pierre** [comment]
Yes, as already mentioned above `ntpdate` does not have a `--version` or `--help` flag we can use to detect the command is present.

**Comment by mergen3107** [comment]
As, sorry, it's getting late :D I am trying my best.

Good news is, the actual commands works fine:
```
[root@kindle bin]# ntpdate pool.ntp.org
20 Nov 22:39:02 ntpdate[5775]: adjust time server 172.234.37.140 offset 0.033500 sec
```

**Comment by mergen3107** [comment]
![TimeSync!](https://github.com/user-attachments/assets/d262f7f5-312f-4f2e-87bb-898adfd3c1fa)

**Comment by mergen3107** [comment]
Ta-da! :D 

I had this stupidest idea.
I replaced the second check with...
```
if not ntp_cmd and os.execute("ntpdate pool.ntp.org >/dev/null") == 0 then
    ntp_cmd = "ntpdate pool.ntp.org"
end
```
That means the Time Sync plugin will only work if... it works! :D That is, Kindle needs to be connected to Wi-Fi at the time.

If there absolutely are no other ways, we can a hint and/or user guide notification like `If you need Time Sync plugin, restart KOReader after enabling Wi-Fi`

**Comment by benoit-pierre** [comment]
Try this patch:
```diff
 plugins/timesync.koplugin/main.lua | 25 ++++++++++++++++---------
 1 file changed, 16 insertions(+), 9 deletions(-)

diff --git i/plugins/timesync.koplugin/main.lua w/plugins/timesync.koplugin/main.lua
index f1d2006f9..c6c8ed44e 100644
--- i/plugins/timesync.koplugin/main.lua
+++ w/plugins/timesync.koplugin/main.lua
@@ -9,21 +9,28 @@ if C.getuid() ~= 0 then
     return { disabled = true, }
 end
 
+local function which(command)
+    local path = os.getenv("PATH") or ""
+    for p in path:gmatch("([^:]+)") do
+        p = p .. "/" .. command
+        if lfs.attributes(p) and os.execute("test -x " .. p) == 0 then
+            return p
+        end
+    end
+end
+
 local ntp_cmd
 -- Check if we have access to ntpd or ntpdate
-if os.execute("command -v ntpd >/dev/null") == 0 then
+local ntpd = which('ntpd')
+if ntpd then
     -- Make sure it's actually busybox's implementation, as the syntax may otherwise differ...
     -- (Of particular note, Kobo ships busybox ntpd, but not ntpdate; and Kindle ships ntpdate and !busybox ntpd).
-    local path = os.getenv("PATH") or ""
-    for p in path:gmatch("([^:]+)") do
-        local sym = lfs.symlinkattributes(p .. "/ntpd")
-        if sym and sym.mode == "link" and string.sub(sym.target, -7) == "busybox" then
-            ntp_cmd = "ntpd -q -n -p pool.ntp.org"
-            break
-        end
+    local sym = lfs.symlinkattributes(ntpd)
+    if sym and sym.mode == "link" and string.sub(sym.target, -7) == "busybox" then
+        ntp_cmd = "ntpd -q -n -p pool.ntp.org"
     end
 end
-if not ntp_cmd and os.execute("command -v ntpdate >/dev/null") == 0 then
+if not ntp_cmd and which('ntpdate') then
     ntp_cmd = "ntpdate pool.ntp.org"
 end
 if not ntp_cmd then
```

**Comment by mergen3107** [comment]
It worked! Thank you :)

**Comment by mergen3107** [comment]
(and thank you @Commodore64user and your Commodore 64 again for hotkeys! I am happily using ScreenKB+PageTurnBack on both sides for quick Restart/Exit from KOReader :D)

**Comment by mergen3107** [comment]
> For the terminal plugin, try setting the shell manually in `settings.reader.lua`:
> 
> ```lua
> ["terminal_shell"] = "/bin/sh",
> ```

So, for this fix, what is the best way to approach this?
One-time migration to add the setting?
Or make Terminal Emulator default to `/bin/sh` on Non-Touch (any other?) Kindles?

**Comment by benoit-pierre** [comment]
We could add a last chance direct check for `/bin/sh`:
```diff
 plugins/terminal.koplugin/main.lua | 1 +
 1 file changed, 1 insertion(+)

diff --git i/plugins/terminal.koplugin/main.lua w/plugins/terminal.koplugin/main.lua
index 347f53050..8793392fc 100644
--- i/plugins/terminal.koplugin/main.lua
+++ w/plugins/terminal.koplugin/main.lua
@@ -110,6 +110,7 @@ function Terminal:getDefaultShellExecutable()
         "hush",
         "ksh",
         "mksh",
+        "/bin/sh",
     }
     local env_shell = os.getenv("SHELL")
     if env_shell then
```

**Comment by mergen3107** [comment]
Let me try this

**Comment by mergen3107** [comment]
Worked great! crash.log is now happy:
```
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
sh: command: not found
11/20/24-23:09:02 DEBUG Terminal: default shell is /bin/sh 
```

There first eight failures are exactly the eight other shells:
```
    local shell = {
        "bash",
        "ash",
        "sh",
        "zsh",  -- RPROMPTs aren't really handled well, so we deprioritize it a bit
        "dash",
        "hush",
        "ksh",
        "mksh",
        "/bin/sh",
    }
```

**Comment by mergen3107** [comment]
Thank you very much @benoit-pierre for all your help with this ticket!
You technically single handedly solved both problems :D 
I'll go make a PR
