### ISSUE TITLE
[Plugin Manager] "Enabled" Plugins in settings file are not checked on KOReader init

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12770]
I found this on
* KOReader version: 2024.07-285-gfd3727274 (legacy)
* Device: Kindle 4 Non-Touch (FW 4.1.4)

#### Issue
`settings.reader.lua` has a field for `plugins_disabled` like this (from Kindle Scribe):

```
    ["plugins_disabled"] = {
        ["SSH"] = true,
        ["autodim"] = true,
        ["autofrontlight"] = true,
        ["autoturn"] = true,
        ["autowarmth"] = true,
        ["backgroundrunner"] = true,
        ["batterystat"] = true,
        ["bookshortcuts"] = true,
        ["calibre"] = true,
        ["calibrecompanion"] = true,
        ["coverimage"] = true,
        ["evernote"] = true,
        ["goodreads"] = true,
        ["httpinspector"] = true,
        ["japanese"] = true,
        ["keepalive"] = true,
        ["kobolight"] = true,
        ["kosync"] = true,
        ["movetoarchive"] = true,
        ["newsdownloader"] = true,
        ["perceptionexpander"] = true,
        ["qrclipboard"] = true,
        ["readtimer"] = true,
        ["send2ebook"] = true,
        ["statistics"] = true,
        ["storagestat"] = true,
        ["systemstat"] = true,
        ["terminal"] = true,
        ["vocabbuilder"] = true,
        ["wallabag"] = true,
        ["zsync"] = true,
    },
```
This makes KOReader add those in the Top Menu - Tools - More tools - Plugin management list of plugins, even though a new device might support them. Like frontlight on K4NT.

Good news is that there is no crash: once you enabled these disabled plugins and restart, KOReader removed them from the list.

#### Steps to reproduce
- Enable/Disable a bunch a plugins on one device.
- Moved its `settings.reader.lua` to another device with different hardware (e.g. now with no front light)
- Open top menu settings, list of plugins on the new device.
- See plugins that shouldn't have been there.

##### `crash.log` (if applicable)
Easy to reproduce. For example: 
[settings.reader.lua.SCRIBE.txt](https://github.com/user-attachments/files/17849431/settings.reader.lua.SCRIBE.txt)

**Comment by mergen3107** [comment]
So, I think this check needs to also go though the actual device compatibility:
https://github.com/koreader/koreader/blob/0e2dadf6e03d908c6e4660b5ee0f6b68fe86c8d4/frontend/pluginloader.lua#L140-L142

Not sure, how to make it efficient

**Comment by mergen3107** [comment]
This is where confusion starts:
https://github.com/koreader/koreader/blob/0e2dadf6e03d908c6e4660b5ee0f6b68fe86c8d4/frontend/pluginloader.lua#L112

**Comment by mergen3107** [comment]
IMHO, it needs to do two things:
1) skip adding incompatible plugins to the list; and
2) remove those from `settings.reader.lua` and add a note to crash.log

**Comment by pazos** [comment]
You're missing an **ELEPHANT** in the room.

Plugins are self described. There's no way for core to know which plugins are incompatible without asking plugin's main routine or, to some extend, executing its metadata.

If your request is deemed relevant the work needs to happen in PluginLoader, which is the codepath that iterates over dirs and loads plugins.  And your request would be, mostly:  "auto-clean incompatible plugins after settings migration between different devices".

**Comment by mergen3107** [comment]
> auto-clean incompatible plugins after settings migration between different devices

Yes, basically. Such check is not happening right now at all, so that's why I am bringing attention to it :D

**Comment by benoit-pierre** [comment]
I think the onus if on the user to double check settings when migrating on another device.

**Comment by pazos** [comment]
Yup, there's no support for "settings migration between different devices", AFAICT. 
It is mostly "it works" and sometimes "you'll need to fix things manually".

But, even more basically, we have no way to clean up settings. 

If you setup a particular plugin in a particular device and move these settings to a device where you don't have that plugin enabled, your settings for that particular plugin will be preserved and loaded, albeit never used.

We can then argue each codepath that deals with a setting should be able to self repair to its defaults in case we detect an incompatible device.  And so on.

I'm trying to imply you're not reporting a bug, but an unsupported usercase, which is hard to deal with (and a mess!). Fixing the usercase "settings migration across devices" is a PITA. Self healing capabilities are even messier.

We try to load each borked setting without a crash. It is the best we can do. 
It makes no sense to deal with issues like this at a particular level without a proper "device migration" support.

**Comment by mergen3107** [comment]
OK, I guess it is good enough that it doesn't crash and kicks out the unsupported plugin once you enable it and restart :D
