### ISSUE TITLE
[Kindle NT] Text Input field - missing right-click option (to copy, etc)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#12772]
* KOReader version: 2024.07-285-gfd3727274 (legacy)
* Device: Kindle 4 Non-Touch (FW 4.1.4)

#### Issue
@Commodore64user 
Maybe I am missing it somehow, but is there a way to do "right-click" on the text field to be able to copy whole text, just line (and do other things which I don't remember).

#### Steps to reproduce
Currently, "right click" while keyboard is up does "right click" on each letter (which is great).

For example, from within a book, open Top Menu - second tab - Style tweaks - long-press on Book-Specific tweaks (with `ScreenKB+Press`).

Book style tweak editor appears.
Input a few character (optional).
Close keyboard using `Back` button, scroll down once to focus on the text field, then do "right-click (`ScreenKB+Press`): nothing happens. What I expected was a nice popup menu which shows the same text in a text field and a bunch of options to copy it, or copy just a line, paste, etc.

#### Other Questions about Book-Specific Style Tweaks text input field, or rather `text editor` module maybe (and maybe other ones that have extra buttons above the keyboard, like Terminal Emulator)
I can also close keyboard while editing with `ScreenKB+Home` combo. However, this one is different from closing it with `Back` in the sense that focus stays inside the text field. So, Dpad buttons move cursor inside the text rather than moving focus around buttons.
Is this intended behavior?
I scratched my head a little bit, then figured I need to hit `Back` button **twice** to lose focus to be able to move around the buttons.

##### `crash.log` (if applicable)
Let me know if it is needed, but I think this feature is simply missing.

**Comment by mergen3107** [comment]
I see, thank you for the explanation!
I tried turning off `Show virtual keyboard`, but I think I prefer having it on on K4NT.
In Book Style Tweaks, when keyboard is open with it on, it covers extra buttons - and I don't see what line number I am on.

Also, why does the menu `Keyboard appearance settings` gets grayed out as soon as you turn off `Show virtual keyboard`?

Doesn't make sense to me. So, if you have it off and would like to tweak how keyboard looks, you need to enable it temporarily, tweak keyboard and then turn it off again.

**Comment by mergen3107** [comment]
> What you are describing would require to refactor the "text selection" to work in other places besides the book's content and that is a bit of effort which might be just a bit too much for little reward.

**Comment by Commodore64user** [comment]
I'm going to fix this.

**Comment by Commodore64user** [comment]
I don't have the power to reopen issues, but it would be awesome if someone could do it here, it should be purple not grey.

**Comment by poire-z** [comment]
I just managed to get it green :/

**Comment by poire-z** [comment]
<img width="569" height="115" alt="Image" src="https://github.com/user-attachments/assets/c5e78904-7800-4143-a461-2151be78ecd3" />

^ Is this happening again (do you see it or just me?), when we mention an issue in a commit, every other people that sync their fork will get us to get that ?

**Comment by Frenzie** [comment]
References unfortunately work like that (even to the point of closing issues across repository boundaries) but I don't think there are notifications about it.
