### ISSUE TITLE
Frontlight automatically turning off

### ISSUE THREAD

**Issue by tetrahedon7** [koreader/koreader#12777]
* KOReader version: 2024.11
* Device: Kindle Voyage

#### Issue
The frontlight keeps turning off on its own after a few seconds of use. I thought that the gestures were being triggered for some reason, but the problem persists even after both frontlight related gestures (corner tap and left edge swipe) have been turned off.

**Comment by Commodore64user** [comment]
Deactivate `auto front light` plugin.

**Comment by tetrahedon7** [comment]
That fixed it. Thanks so much!
