### ISSUE TITLE
pdf document display on linux plarform ,the color is grey,but android is colourful 

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#12792]
* KOReader version:2024.11
* Device:linux x86_64.tar.xz/android

#### Steps to reproduce

is it possible set or build Linux platform,pdf document displayed colourful,thanks

**Comment by Frenzie** [comment]
Settings (cog), screen, color rendering.

But that's the default.

**Comment by dandelions** [comment]
ohh,it works,thanks very much

**Comment by benoit-pierre** [comment]
Weird that you had color rendering disabled. Did you maybe migrate settings from a grayscale device?
