### ISSUE TITLE
FR: Allow setting default highlight color

### ISSUE THREAD

**Issue by pdc1** [koreader/koreader#12806]
**Does your feature request involve difficulty completing a task? Please describe.**

The latest release supports color highlights, yay! However, the default is yellow, which is kind of muddy brown on my color e-reader (Kobo Libra Color). On a highlight-by-highlight basis (or perhaps a book-by-book basis?) I can set a different color. However, I can't long-press the selection to make it the new global default. There is a star by yellow, which suggests it could be a different color, but a long-press makes the dialog semi-transparent with no change to the global default.

**Describe the solution you'd like**
Allow some mechanism to set a new global default highlight color.

**Describe alternatives you've considered**
Setting the highlight color for each book.

**Side question**
As a workaround, is there some way to do this with a user patch?

**Comment by NiLuJe** [comment]
It's available somewhere in the topmenu in the Document tab IIRC. (Burger > Help > Search might help).

**Comment by pdc1** [comment]
Oh snap! I knew where the setting was, but I was not able to set the global default.

However, I just realized I need to long-press the ***menu item***, not the item in the dialog! Sorry about that!
![image](https://github.com/user-attachments/assets/c834ccbb-29e9-4fb7-b3d4-a22cd720d346)
