### ISSUE TITLE
Standby not scheduled after transitions

### ISSUE THREAD

**Issue by sebastien-maillard** [koreader/koreader#12814]
### Summary of the conversation relevant for this issue
Assuming default settings and a battery level above the _Always standby if battery below_ threshold, the `AutoStandby` plugin has the following issues:

1. After a transition (i.e. opening or closing a book), the device will never enter standby until a touch event happens to trigger the next schedule
    - This is because the standby scheduled following the input event leading to the transition has been unscheduled to avoid going into standby during the transition 
2. When KOReader starts, the device will instantly go into standby
    - This is because the plugin didn't get a chance to prevent the device from going into standby

Based off of [this suggestion](https://github.com/koreader/koreader/discussions/12791#discussioncomment-11381336), I created a patch to schedule the next standby when the plugin is initialized. This appears to fix both issues. I'll submit a PR accordingly.

**Comment by pazos** [comment]
1. When you're opening the document we don't want standby to kick in until the documented is parsered and the current page rendered by the engine.

Please make sure you test your changes with a, not previously opened, complex epub.

**Comment by sebastien-maillard** [comment]
PR submitted, see #12815.

> 1. When you're opening the document we don't want standby to kick in until the documented is parsered and the current page rendered by the engine.

Thanks for the reminder. Indeed, this point [was raised](https://github.com/koreader/koreader/discussions/12791#discussioncomment-11381336) during the discussion. I actually already put some extra thoughts regarding this topic and that made me wondered if we should slightly change the approach. See section [_Important note regarding the current approach_](https://github.com/koreader/koreader/pull/12815#issue-2703279855) for more details.

> Please make sure you test your changes with a, not previously opened, complex epub.

Done!
