### ISSUE TITLE
FR: Abilty to specify IU fonts

### ISSUE THREAD

**Issue by dtcyganok** [koreader/koreader#12812]
**The problem**
Currently the list of UI typefaces is hard-coded. Noto Sans is quite good, especially considering its extensive Unicode coverage. But the font style and legibility/readability are questionable. And I believe there are a great many users, who want to use another font.

**Describe the solution you'd like**
I'd like to see the three new options:
1. UI font
2. Dictionary font
3. Monospace font

**Describe alternatives you've considered**
Use a monkey patch

**Additional context**
Additionally I noticed that the html dictionary font is also hard-coded in a css chunk. And event monkey patching can help it :)
I also noticed that the fonts are not consistent across the app, but that's a separate issue albeit related.

**Comment by poire-z** [comment]
> Use a monkey patch

We call these "user patches": 
https://github.com/koreader/koreader/issues?page=2&q=+label%3A%22User+patch+available%22
For the UI fonts: https://github.com/koreader/koreader/issues/9951

I think it's simpler and safer for us to no provide some UI to tweak the UI font.

**Comment by dtcyganok** [comment]
> We call these "user patches"

You can call it as you want, and let me call it as I want :)

Thanks for the links. I already forced to use a "user/monkey patch", but I believe users deserve more friendly solution :)

**Comment by pazos** [comment]
We call them user patches because that's what they're: Hooks that developers intended for users to change runtime behaviour.

You can call them what you want, just not here.

**Comment by dtcyganok** [comment]
[pazos](https://github.com/pazos) no problem, and no offense. The difference between monkey patching and user patching isn't the question in this topic. So I'm not going to argue about that

**Comment by dtcyganok** [comment]
[pazos](https://github.com/pazos) Why it was closed? Is there some reason except resentment?

**Comment by pazos** [comment]
> Why it was closed? Is there some reason except resentment?

You received an answer:

> I think it's simpler and safer for us to no provide some UI to tweak the UI font.

 It isn't planned. A few years ago we would go with a "PR welcome" for almost everything but recently we moved to a saner "not all PRs welcome".

I enjoy the new mindset :). It is basically this one: New feature requests usually gets an answer for an interested maintainer, in this case @poire-z, who addressed your question with a "nope, thank you, it is easier to maintain this way. Use a patch".

Rejecting feature requests is wise, sometimes.

**Comment by dtcyganok** [comment]
@pazos Oh, it looks really strange to me. I just see no argumentation here. Following this logic, there is no point in developing at all. Because it's easier not to maintain anything than maintain something.

> Rejecting feature requests is wise, sometimes.

Of course, especially when decisions are based on strong argumenatation
