### ISSUE TITLE
The progress bar color is too pale

### ISSUE THREAD

**Issue by dtcyganok** [koreader/koreader#12813]
* KOReader version: 2024.11
* Device: Kobo Glo

#### Issue

The both types of the progress bar (thin and thick) are nearly invisible on my device. The color should be more contrast.

**Comment by NiLuJe** [comment]
There's been extensive bike-shedding about this subject in the past, we're unlikely to make any massive changes, especially for the sake of such an old device known to have subpar contrast ;).

**Comment by dtcyganok** [comment]
The contrast of Kobo Glo is probably not as good as the modern eInk screens, but I see no another contrast problems.

**Comment by offset-torque** [comment]
**Short answer:** Darker progress bar negatively affects the chapter mark visibility. If we make it darker, there is not much contrast left between the progress bar and chapter marks, and this is not good.

Here is a long discussion of the color decision if you are curious: https://github.com/koreader/koreader/pull/8195

**Comment by NiLuJe** [comment]
On the upside, the work done for that PR led to this being easily user-patchable, unless I'm dreaming that one up?

**Comment by dtcyganok** [comment]
The issue is not of great importance. So it is worth considering of closing.
