### ISSUE TITLE
Kobo Aura. Change brightness to 100% and redraw fails

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1282]
So when you change the brightness from 0% to 100% (in four steps) via the two finger gesture. Then the you have the screen redraw several times (half dotted screen + notifications) but at 100% most of the text gets greyish.

![img_20141128_121044](https://cloud.githubusercontent.com/assets/1377943/5227183/1b38fa20-76f8-11e4-8e9e-89d2f268addf.jpg)

Video: http://a.pomf.se/tgwinm.mp4

**Comment by NiLuJe** [comment]
Almost four years old, and can't reproduce, closing :).
