### ISSUE TITLE
The selected text is not displayed with the menu window.

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12830]
* KOReader version: 2024.11-40
* Device: PB 628

#### Issue
Select a text (2 or more words) and then choose to look it up in the dictionary or to translate it. After closing the dictionary or the translation window, the text is not no longer highlighted. I think this wasn't the case and if you want to make another choice for the same text, you may want to see the text you have selected.

**Comment by hius07** [comment]
Fixed in https://github.com/koreader/koreader/pull/12810.
