### ISSUE TITLE
Selection & highlight displaced Kobo Aura

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1283]
And again a Kobo Aura with 1238:

The selection is a few pixel of (to the right) same for the highlight.

![img_20141128_122850](https://cloud.githubusercontent.com/assets/1377943/5227377/bc5de1a2-76fa-11e4-90ef-4b723bb46934.jpg)

![img_20141128_122957](https://cloud.githubusercontent.com/assets/1377943/5227356/76f18a10-76fa-11e4-891f-836567679e57.jpg)

**Comment by poire-z** [comment]
Should be fixed by https://github.com/koreader/crengine/pull/204 , available in current nightly.
