### ISSUE TITLE
FR: Ability to specify an arbitrary auto shutdown timeout

### ISSUE THREAD

**Issue by dtcyganok** [koreader/koreader#12831]
**The problem**
Currently it's not possible to choose an auto shutdown timeout that's less than one day.

**The solution**
Give a user the ability to specify an arbitrary auto shutdown timeout.

**Additional context**
We all love unreasonable restrictions :/

**Comment by Frenzie** [comment]
I agree with the general sentiment. The spinner widget has the disadvantage of being overly strict, and would profit from the ability to have a true minimum applied to manual input (e.g., here 60 seconds) with the spinner limited to the sensible value.

**Comment by NiLuJe** [comment]
There's a hardly documented anywhere feature where you can blow past the spinner limits by doing something like prepending the value with a colon or an equal sign...

(But see above "hardly documented anywhere" ^^).

**Comment by NiLuJe** [comment]
Hey, I nearly remembered that right! :D 

https://github.com/koreader/koreader/pull/9182

**Comment by jonnyl2** [comment]
Unfortunately it only works with verbose debug logging enabled.

**Comment by Frenzie** [comment]
> Unfortunately it only works with verbose debug logging enabled.

I'd actually tried that but it didn't work. I thought I misremembered… so that's the reason.

As stated above, I support simply making it available in the UI, most obviously through the manual input dialog. That'd be either with a checkbox or with an additional nag popup.
