### ISSUE TITLE
Slow documents opening

### ISSUE THREAD

**Issue by dtcyganok** [koreader/koreader#12840]
* KOReader version: 2024.11
* Device: Kobo Glo

#### Issue

After about 10-15 minutes since start documents opening became slow. It literally takes approximately 5-6 seconds. File manager opening also takes 5-6 seconds. After restarting koreader everything becomes normal again.

#### Steps to reproduce

Nothing special. Just wait some time. Can't say precisely how long, but it's about 10-15 minutes

#### Additional info

After I disabled several plugins the problem's gone. I'm not sure, but my best guess is that the reading stats plugin causes this problem.

**Comment by Frenzie** [comment]
The reading statistics plugin is enabled by default, so that seems unlikely.

**Comment by dtcyganok** [comment]
Hm, I disabled 5 plugins:

- auto dimmer
- time sync plugin
- reading stats
- battery stats
- system stats

**Comment by Frenzie** [comment]
Time sync and system stats don't do anything by themselves, reading and battery stats are always on by default.

I'd say that leaves AutoDim. Some devices have much slower frontlights than others; maybe that's an issue.

**Comment by NiLuJe** [comment]
If you happened to have some kind of sync'ing enabled (reading, statistics) that might also be a strong contender ;).
