### ISSUE TITLE
FR: Some Questions about Tolino Epos 1

### ISSUE THREAD

**Issue by jeffersondarcy** [koreader/koreader#12843]
Sorry if this question is not directly related to Koreader 

I am currently running the latest nightly on Tolino Epos1 with Firmware v15
Would be there any benefits in updating to Firmware v16 when using mostly Koreader?

My Tolino is not rooted, so in my understanding I would have to root it before update or I won't have developer/adb access - is this correct or are there some new loopholes in v16 possible?

is there a good up-to date rooting tutorial for Epos1?

Currently I have generic adb which came with android studio on mac, but for rooting I would need something custom, correct?

I would be interested in being able to adjust front light warmth, but that also requires root, correct?

**Comment by pazos** [comment]
Most of these questions are better asked on a proper tolino forum. Here nobody touched a tolino.

I can answer:

> Would be there any benefits in updating to Firmware v16 when using mostly Koreader?

Most likely NO benefits

> I would be interested in being able to adjust front light warmth, but that also requires root, correct?

Correct

**Comment by pazos** [comment]
> I would be interested in being able to adjust front light warmth, but that also requires root, correct?

@jeffersondarcy: please try that on your v15 fw.

1. In last KOReader nightly
2. Go to file manager. Top Menu, "tools->more tools->developer->start compatibility test"
3. Se if the TolinoNtx light driver work.

If it works you can stay in v15 if you want. If it doesn't work it means you'll need root anyways to get warmth working.

**Comment by jeffersondarcy** [comment]
> > I would be interested in being able to adjust front light warmth, but that also requires root, correct?
> 
> 
> 
> @jeffersondarcy: please try that on your v15 fw.
> 
> 
> 
> 1. In last KOReader nightly
> 
> 2. Go to file manager. Top Menu, "tools->more tools->developer->start compatibility test"
> 
> 3. See if the TolinoNtx light driver work.
> 
> 
> 
> If it works you can stay in v15 if you want. If it doesn't work it means you'll need root anyways to get warmth working.
> 
> 

cool, warmth adjustment works now with no root - thx

**Comment by pazos** [comment]
> cool, warmth adjustment works now with no root - thx

it will be available on a nightly, soon.
