### ISSUE TITLE
Patch management plugin can't be disabled

### ISSUE THREAD

**Issue by dtcyganok** [koreader/koreader#12841]
* KOReader version: 2024.11
* Device: Kobo Glo

#### Steps to reproduce

1. Go to the plugins management
2. Disable the patch management plugin
3. Restart koreader
4. Go to the plugins management
5. See the status of the patch management plugin

**Comment by Commodore64user** [comment]
To disable it, you need to remove the folder from the directory manually. Patches are an advanced feature which is why they don't work quite the same as other plugins

**Comment by Frenzie** [comment]
There are two separate things here.

Patches themselves work on the basis of whether the folder exists or not. They can't be disabled.

Patch management merely changes the name from `some-patch.lua` to `some-patch.lua.disabled` and vice versa.

That the patch management plugin can't be disabled is weird if true.

**Comment by hius07** [comment]
Plugin folder must have the same name as the plugin itself.

**Comment by Frenzie** [comment]
Strange that it doesn't. Easy enough to fix. :+1:

**Comment by pazos** [comment]
Can the "check of patches dir" be moved from plugin init to plugin addToMainMenu?

I guess the plugin would also need to handle the case its UI is invoked and there's no patches dir.

**Comment by hius07** [comment]
And what to do in this case? Create the folder and then...

**Comment by Frenzie** [comment]
At a quick glance it looks like it could just do an early return in getAvailablePatches() based on the same check.

**Comment by pazos** [comment]
> And what to do in this case

What happens when there's a patches dir but no patches?. I would expect the same UI.

IMHO we don't need to create a patches dir as part of this plugin. It will end on all devices if the plugin stops disabling itself on init ;)

**Comment by hius07** [comment]
Agree, the same behaviour as when there are no patches.

**Comment by hius07** [comment]
At least, the About menu item is available.

**Comment by Frenzie** [comment]
You can actually achieve both: a plugin with exactly the same treatment as any other plugin, except it's disabled by default, to be enabled through plugin management.

**Comment by pazos** [comment]
That's another kettle of fish ;). I would love to have that one day and ship many things disabled :)))

**Comment by Frenzie** [comment]
But in any case the only real issue here is that `plugins/patchmanagement.koplugin/_meta.lua` says `patch_management` when it should say `patchmanagement`.

**Comment by hius07** [comment]
No, I have a rest after brainstorming https://github.com/koreader/koreader/pull/12845.

**Comment by pazos** [comment]
After some thinking I realized that it would be much better to have plugin management as part of core and enabled just when the patches dir exists.

That way there's one plugin less, one entry less and users that don't care won't see the word "patch" at all in any place across the program.

Also I love removing plugins :)

Just my two cents.

**Comment by Frenzie** [comment]
With the current behavior putting it in core makes sense to me, though it may be worth noting that we're talking about a one-line fix which I was just about to PR. But if you want to do more that's fine by me. ;-D

**Comment by pazos** [comment]
Nah. I'm just arguing. I don't plan to do a PR. 

The one-liner works for me, too :)

I was providing ideas. I'm a bit nitpicky with unexpected behaviours :p
