### ISSUE TITLE
PocketBook Verse Pro: missing OPDS icon

### ISSUE THREAD

**Issue by juk0de** [koreader/koreader#12855]
* KOReader version: 2024.11
* Device: PocketBook Verse Pro (`U634.6.8.4177`)

#### Issue

I tried to follow the description for [configuring OPDS support](https://github.com/koreader/koreader/wiki/OPDS-support), but the icon mentioned there is not visible in the file browser (see attached screenshot). The design seems to have been changed significantly (are the screenshots outdated?), so I searched everywhere for OPDS. The only thing I found was the menu entry where I can browse public OPDS catalogues, but I want to add my own OPDS catalogue (`calibre-web`).

As a workaround I decided to connect to `calibre` on my PC. So I started the OPDS server in `calibre` and enabled wireless device connection. However, when choosing `Calibre -> Connect` nothing happens (not even the error you get if `calibre` is not running). I can browse my OPDS catalogues without any issues using Firefox on my PC, but connecting from KOReader seems to be impossible.

![PocketBook](https://github.com/user-attachments/assets/3b8f632f-f0ad-45e4-91cd-2b2f4b9dde4b)

#### Steps to reproduce

Open KOReader File Browser.

**Comment by benoit-pierre** [comment]
The OPDS Catalog is still available in the same place: when not in book reading mode, click on the magnifying glass icon, and then on the last entry ("OPDS Catalog").

For the calibre problem, please create a dedicated issue and provide logs (preferably with verbose logging enabled).

**Comment by benoit-pierre** [comment]
I updated the screenshots on the wiki, hopefully this will make things clearer.

**Comment by hius07** [comment]
> The only thing I found was the menu entry where I can browse public OPDS catalogues, but I want to add my own OPDS catalogue (`calibre-web`).

Right there press the top left PLUS icon.

**Comment by hius07** [comment]
> and also the local `calibre` OPDS catalogue (called it "Calibre")

What's the server address?

**Comment by hius07** [comment]
Add `/opds` at the end.

**Comment by benoit-pierre** [comment]
After connecting (and selecting a destination folder the first time), you used it from Calibre itself: the UI should show a connected device, and you can then send and remove books from Calibre.
