### ISSUE TITLE
Auto front light stopped working on kindle voyage

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#12854]
* KOReader version: 2024.11-15
* Device: kindle voyage

#### Issue

Auto front light stopped working.

#### Steps to reproduce

It should turn off the front light when the environment is bright enough.
I saw it was marked as deprecated a while ago, but cannot understand the motivation, it worked perfectly fine until recently.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to [Menu] → Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file (zipped if necessary) on GitHub by dragging and dropping it onto this textbox.

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, go to `Top menu → Hamburger menu → Help → Report a bug` and tap `Enable verbose logging`. Restart as requested, then repeat the steps for your issue.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by mergen3107** [comment]
It has been moved to contrib

**Comment by Hzj-jie** [comment]
NVM, I updated to 2024.11-49 and it works again.

Thank you.

**Comment by pazos** [comment]
@Hzj-jie. 

That plugin will be removed soon.
The backgroundrunner plugin too!

We would like to keep autofrontlight working in contrib but it currently relies on the `backgroundrunner`. It would be amazing if you (or somebody that cares for the plugin) could adapt it to be standalone.
