### ISSUE TITLE
incompatible bash version: 3.2.57(1)-release, need >=4.0

### ISSUE THREAD

**Issue by jeankhawand** [koreader/koreader#12868]
* KOReader version: master
* Device: MacOS Sonoma 14.4 (23E214)

#### Steps to reproduce
1. install brew dependencies mentioned in doc
2.  export PATH="$(brew --prefix)/opt/findutils/libexec/gnubin:$(brew --prefix)/opt/gnu-getopt/bin:$(brew --prefix)/opt/make/libexec/gnubin:$(brew --prefix)/opt/util-linux/bin:${PATH}"
3. export PATH="/usr/local/bin:/usr/local/sbin:${PATH/:\/usr\/local\/bin/}"
4. export MACOSX_DEPLOYMENT_TARGET=10.14
5. clone repo and cd koreader && ./kodev fetch-thirdparty
6. unable to proceed due to `incompatible bash version: 3.2.57(1)-release, need >=4.0`

**Comment by benoit-pierre** [comment]
Are you sure about your `PATH` setting? What are you trying to do with that last part: `${PATH/:/usr/local/bin/}`?

Check which bash executable is used (`command -v bash`), and its version (`bash --version`, homebrew should be installing 5.2.37).

**Comment by NiLuJe** [comment]
And assuming your brew is setup properly, and you don't mangle your `PATH`, brew's version of bash should automgaically have precedence over macOS's horribly outdated one.

**Comment by NiLuJe** [comment]
Hey, turns out I wrote that piece of horror in the docs.

I'm pretty sure most of it is horribly outdated ^^.

**Comment by Frenzie** [comment]
I believe @benoit-pierre updated them recently, unless we're thinking of different docs.

**Comment by NiLuJe** [comment]
That specific bit of nonsense about playing with brew's path is still in there, and mine according to the blame ;p.

**Comment by Frenzie** [comment]
It's not that long I installed brew and I'm pretty sure I had to do things with PATH. (As per what brew tells you; I don't know about that other stuff.)

**Comment by NiLuJe** [comment]
Yeah, that's what I meant, I'm not quite sure what I was on about with the extra mess; the standard brew stuff should be fine (barring some GNU tools being in path but with an extra `g` prefix).

**Comment by jeankhawand** [comment]
@benoit-pierre  
``` bash --version
GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)
Copyright (C) 2007 Free Software Foundation, Inc.
```
Despite redoing the process and omitting the steps mentioned in #12873, I am still encountering the same error. Could you please provide guidance on resolving this issue?
Additionally, is there any plan to include a macOS DMG / PKG as part of each release? Having such an option would streamline the installation process for macOS users.

**Comment by Frenzie** [comment]
Not at the moment, but each commit comes with macOS artifacts.

https://github.com/koreader/koreader/actions/runs/12219931703

**Comment by benoit-pierre** [comment]
What are the outputs of:
- `echo "$PATH"`
- `command -v bash`
- `ls -l /usr/local/bin/bash`
- `/usr/local/bin/bash --version`

**Comment by NiLuJe** [comment]
And, if possible:

`brew shellenv`

**Comment by pazos** [comment]
Yay. At some point macos switched from an old GPL2 version of bash to zsh. 
Maybe brew no longer installs a modern version of bash by default.

**Comment by jeankhawand** [comment]
@benoit-pierre  exact! doc should mention that `bash` must be install now it's working fine. Thanks

**Comment by Frenzie** [comment]
Let's keep it open, otherwise people will think it's already fixed. ;-)
