### ISSUE TITLE
Default Page Crop method is not respected on new document start

### ISSUE THREAD

**Issue by KopiasCsaba** [koreader/koreader#12876]
* KOReader version: 2024.11
* Device: Pocktebook Era PB700

#### Issue
*  Upon setting auto (but probably anything but none) as default page crop, the newly opened documents does not respect that setting really.
*  It means that they show up as selected, but they are not put into action, the new document is not cropped based on the selected crop method.

#### Steps to reproduce
 * Open a doc, set default page crop to auto
 * Open another one (the selected one will be correct)
 * But the page will not be cropped.

I've made a video on it as well:
https://youtu.be/QD8QCCQSIGk

**Comment by pazos** [comment]
Duplicate of https://github.com/koreader/koreader/issues/7963
