### ISSUE TITLE
FR: Option to auto-execute profiles on book opening only on new books

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#12870]
**Does your feature request involve difficulty completing a task? Please describe.**

Auto-execution of profiles for certain criteria (e.g., words in filename or path) is great to set the document layout for newly opened books. However, sometimes small adjustments are needed on a per-book basis. If these adjustments are part of the profile, they get reverted any time the book is reopened.

**Describe the solution you'd like**

Add an option in the Profile/Auto-Execute/'on book opening' settings; e.g., `Only apply to new books`, which when enabled, will not auto-execute the profile on opening of a book that has existing sidecar files. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mergen3107** [comment]
Any examples of such action you want to be applied on new books?

Isn't setting a setting by default enough?

**Comment by jonnyl2** [comment]
For example, all books that have k2opt.pdf in its filename I'd like to open as no crop, full-page fit, paged view, and reflow off. These settings will be perfect for ~90% of books I preprocess with k2pdfopt. But not all of them. 

I plan to think of other 'hints' for KOReader I could put into the filenames so the books will open with predefined settings depending on a substring of the filename.

I admit it's kind of a luxury request, but I think this may be useful for other use cases as well, where a profile needs to be executed only once per book. I can't think of anything at the moment, though.

**Comment by mergen3107** [comment]
In that case, try directory defeaults feature.
Create a folder `k2opt` and put all those books there.
Then edit the directory defaults settings file (I forgot where it was exactly, somewhere in koreader folder or koreader/settings).

Just add the same lines for your book settings from book's metadata file

**Comment by jonnyl2** [comment]
Thanks @mergen3107. This works for me. I will close this but if someone sees this and has a different use case for which that workaround doesn't apply, feel free to comment here.
