### ISSUE TITLE
OTA update on Android doesn't report download is finished.

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#12881]
* KOReader version: 2024.11-40
* Device: Onyx Page FW 3.5.4 (Android 11)
#### Issue
When I an OTA update is available and I request to install it, Koreader never reports that download is ready to be installed, no matter how much time passed (The Android version of Koreader, unlike some other versions used to do, downloads OTA updates in background.) If I exit Koreader after a while, start it again and check for OTA updates, it shows again that an update is available and when I ask to install it, it reports immediately that it is ready for installation and proceeds to install it when I tell it to. The problem exists since long ago, I have not bothered to report it before.
#### Steps to reproduce
Check for OTA updates, when there is one available, choose to install it, then wait.

**Comment by Frenzie** [comment]
Does the device implement some kind of aggressive standby?

**Comment by pazos** [comment]
Please report the bug to onyx

**Comment by ilyats** [comment]
I [posted](https://help.boox.com/hc/en-us/community/posts/32916893238676-Problem-with-updating-KOReader-via-OTA-on-Page) a link to this issue on BOOX page, but is the problem really related to standby? It happens when I keep using the device after I requested the update.

**Comment by pazos** [comment]
Given its an onyx device I am not sure at all.

It seemed a good guess (they've screwed something that doesn't affect most apps, just us).

I doubt they screwed BroadcastReceivers, as most apps rely on them.
Anyways, you can check on your logs for strings containing:

`Received event DownloadManager.ACTION_DOWNLOAD_COMPLETE`

That (and a working non JVM thread) is what we need to prompt for updates.

**Comment by hugleo** [comment]
> Given its an onyx device I am not sure at all.
Not mine, also android 11, also 3.5.4 version.
>
