### ISSUE TITLE
KOReader crashes when trying to open a book from InkPad3's main menu

### ISSUE THREAD

**Issue by svkytbsld** [koreader/koreader#12882]
* KOReader version: v2024.11
* Device: PBInkPad3

I have done a factory reset to my Inkpad 3 and re-installed KOReader's newest version. It works fine when I open the app.

In order to open my books (pdfs) from main menu of the device directly, I made KOReader my default reader by checking pdf on Cogs/Device/Associated File Extensions.

But it doesn't work. KOReader crashes instantly. Hourglass shows up and disappears. Clicking on "Open with: Koreader.app" by long-pressing doesn't work either.

from crash log:

2/08/24-18:28:43 INFO  Loading plugins from directory: plugins 
12/08/24-18:28:43 WARN  Terminal: cannot open /dev/ptmx: Permission denied 
12/08/24-18:28:43 WARN  Terminal: Device doesn't meet some of the plugin's requirements 
12/08/24-18:28:47 INFO  Inhibiting user input 

[crash.txt](https://github.com/user-attachments/files/18060944/crash.txt)

**Comment by hius07** [comment]
Any other book?

**Comment by pazos** [comment]
pinging @sebastien-maillard. Are you able to reproduce?

**Comment by pazos** [comment]
@svkytbsld: try to reproduce disabling autostandby. (ie: disabling autostandby from the plugin itself, not disabling the plugin)

**Comment by svkytbsld** [comment]
> @svkytbsld: try to reproduce disabling autostandby. (ie: disabling autostandby from the plugin itself, not disabling the plugin)

OK, from Cogs/Device/Auto-Standby Settings I unchecked Allow Auto-Standby.

Nothings changed. Again, when I click on a book from the main menu of the device, hourglass shows up and disappears...

**Comment by sebastien-maillard** [comment]
> In order to open my books (pdfs) from main menu of the device directly, I made KOReader my default reader by checking pdf on Cogs/Device/Associated File Extensions.
> But it doesn't work. KOReader crashes instantly. Hourglass shows up and disappears. Clicking on "Open with: Koreader.app" by long-pressing doesn't work either.
> [...]
> pinging @sebastien-maillard. Are you able to reproduce?

I followed the same procedure but KOReader doesn't crash for me. I tried with both the AutoStandby plugin enabled and disabled, both with and without the recent #12815 patch.

**Comment by svkytbsld** [comment]
Additional note: When I first open a book inside from KOReader, later I can open it (but not the others) from the device's main menu instantly when I click on it. But when I turn off-turn on the device, I cannot open it like that anymore.

**Comment by pazos** [comment]
> I have done a factory reset to my Inkpad 3 and re-installed KOReader's newest version. 

@svkytbsld: Did you use KOReader on the same device before the factory reset? Did the "open in KOReader" work there?. Did you apply a FW update as part of the factory reset process?

From the description of the issue it looks like the codepath that writes the pocketbook config file for associations works just fine and the issue is from KOReader itself.

The behaviour you're describing is quite fishy. Even more considering

> When I first open a book inside from KOReader, later I can open it (but not the others) from the device's main menu instantly when I click on it. But when I turn off-turn on the device, I cannot open it like that anymore.

So, as a blind guess try to disable "partial rendering". It's the only thing that could match the definition of your issue. I don't know much about the technical aspect of it. It might be a total lost of time :D (but little time, so please try).

**Comment by svkytbsld** [comment]
> Did you use KOReader on the same device before the factory reset? Did the "open in KOReader" work there?. Did you apply a FW update as part of the factory reset process?

Yes, same device, same FW of Pocketbook. Before formatting and reinstalling, everything was superb. I was clicking on books on main menu and it was directly being opened. I don't remember the exact version of KOReader but it must be 2024.04 or 2024.07. So, yes, I had updated to 2024.11 and this started to happen. But nothing changes when I uninstall this newest version and turn back to v04 and v07.

What's partial rendering?

**Comment by pazos** [comment]
> What's partial rendering?

**Comment by svkytbsld** [comment]
It is solved.

In my previous reinstalling attempts I was copy-pasting only the applications folder and not the system folder into the root folder of PB. I thought that was the way and now it turns out to be wrong way. So it was my fault.

Sorry for taking your time and thanks for kindness and help.

**Comment by pazos** [comment]
Great!

I'm happy to hear that :)
