### ISSUE TITLE
`luajit` crashing on Linux (amd64) with `illegal hardware instruction`

### ISSUE THREAD

**Issue by benasocj** [koreader/koreader#12901]
* KOReader version: 2024.11
* Device: Debian GNU/Linux (amd64)

Koreader crashes upon startup:
```
% koreader
/usr/bin/koreader: line 25: 2305887 Illegal instruction     ./reader.lua "${ARGS}"
```

I noticed that `luajit` is also crashing (which seems to be the reason why KOReader is crashing):
```
% /usr/lib/koreader/luajit
zsh: illegal hardware instruction  /usr/lib/koreader/luajit
```

I installed KOReader through the `koreader-2024.11-amd64.deb` package.

Was there maybe a build issue with this architecture?

v2024.07 works fine by the way.

**Comment by benoit-pierre** [comment]
I get the same issue on my (old) machine. Try the AppImage instead.

**Comment by benoit-pierre** [comment]
How recent is your machine?

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader-base/blob/e71fdc1040688e9a15cdc6dde0b2cb74d90205fb/Makefile.defs#L599-L606

**Comment by benoit-pierre** [comment]
Yeah, but `LINUX` is not defined.

**Comment by benoit-pierre** [comment]
So we end up with `-march=native`.

**Comment by Frenzie** [comment]
In that case the cause is extremely clear.
