### ISSUE TITLE
Vocabulay Builder: no context when two words are added

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#12916]
* KOReader version: 2024.11-71
* Device: PB 268

#### Issue
In pdf files, when we select two words or a hyphenated word to add to Vocabulary Builder, the context is not saved. If I remember well, it wasn't the case.

Dear @weijiuqiao and @Frenzie any idea?
Thank you!

**Comment by ichnilatis-gr** [comment]
I have installed the nightly 2024.11-74 and I haven't see any change; the context is still not saved when I select two words or a hyphenated word.

**Comment by ichnilatis-gr** [comment]
Dear @Frenzie and @weijiuqiao, I'm sorry but I can't see any change after your PR was merged.

**Comment by weijiuqiao** [comment]
I was using an old version of the emulator when testing the pr. I can't build a newer version due to errors such as `error: 'exists' is unavailable: introduced in macOS 10.15`. I tried changing `MACOSX_DEPLOYMENT_TARGET` but didn't seem to work. So i'm afraid that I wouldn't be able to see to this problem for now.

**Comment by Frenzie** [comment]
10.15 should work; that's one of the automated checks. Perhaps you should clean and/or update submodules? Automated rebuild doesn't pick up on MACOSX_DEPLOYMENT_TARGET changes.

**Comment by weijiuqiao** [comment]
Thanks. It worked and I've identified the bug. New pr: #12938

**Comment by ichnilatis-gr** [comment]
After having installed the nightly version 2024.11-102, the problem still exist for the hyphenated words, i.e. for the words that are split into two lines.

**Comment by ichnilatis-gr** [comment]
@Frenzie and @weijiuqiao any idea about the above?

**Comment by weijiuqiao** [comment]
Does line-broken words' first half always end with a space in the `text_boxes`?
