### ISSUE TITLE
Query matches in fulltext search results are not in bold in landscape orientations.

### ISSUE THREAD

**Issue by Chairzard** [koreader/koreader#12937]
* KOReader version: 2024.11
* Device: Linux (flatpak) & Android (ARM64)

#### Issue

When running a fulltext search, the search query is in bold in the results in portrait mode (see the first image below, where I searched for "Grant"). However, when using a landscape orientation, the search query is not in bold in the results (see second image below).

#### Steps to reproduce

1. In the bottom menu (left-most button), change the rotation to a landscape orientation (leftmost button, or the second button from the right).
2. Run a fulltext search for a term.
3. In the results that pop up, the term is not in bold among the search results.

Portrait mode search results (this is the expected behavior):

![Portrait](https://github.com/user-attachments/assets/321dd380-d965-4ec8-8208-963a0b0c7a5d)

Landscape mode search results (this is the unexpected behavior; "Grant" is not bolded in results):

![Landscape](https://github.com/user-attachments/assets/c3907ffb-b899-4053-a26e-745848d9cc3b)

**Comment by hius07** [comment]
Thanks. The reason is not landscape mode, but **one-line items** in the second screenshot.
(Technically, it's the other text widget used).
I'll look if we can fix.
