### ISSUE TITLE
custom cover on sleep screen is not working

### ISSUE THREAD

**Issue by pipoprods** [koreader/koreader#12930]
* KOReader version: 2024.11
* Device: Kobo Clara

#### Issue

Selecting an epub file as custom cover for sleep screen leads to current book cover being used.

#### Steps to reproduce

- Go to "Gear" menu => "Screen" => "Wallpaper"
- select "Show custom image or cover on sleep screen"
- click "Custom images" submenu => "Choose image or document cover"
- select an epub file
- open another epub file for reading
- put device in sleep mode

actual behavior:

- the currently opened epub file cover gets used as sleep screen

expected behavior:

- the epub file that has been selected in config should be used to get sleep screen

**Comment by pipoprods** [comment]
Some useful notes:

- It's not a question of special characters/spaces in file path: i've tested with a full-ASCII path with no space and the behavior is the same.
- It's working fine if I'm selecting an image file (tested with a JPEG)

**Comment by hius07** [comment]
Cannot reproduce on Kindle, the latest nightly build.

**Comment by NiLuJe** [comment]
Has the epub in question ever been opened in KOReader?

(If yes, does it work with another never opened epub? And vice-versa ;)).

**Comment by pipoprods** [comment]
Yes, the selected epub has already been opened in KOReader (it's my "main book" of the moment).

I've tried selecting an epub that has never been opened prevously and the behavior remains the same: the currently opened ebook cover is displayed, not the one that's been selected.

**Comment by hius07** [comment]
Can you share your `koreader/settings.reader.lua`.

**Comment by pipoprods** [comment]
Sure!

Having a look at the file, I realise a point may be interesting here: I've copied my config from another device (a PocketBook e-reader) to my new Kobo.
Some keys are no more relevant like `cover_image_cache_path`.
May one of these lead to unexpected behavior?

Here's my complete conf. file:
[settings.reader.lua.txt](https://github.com/user-attachments/files/18228620/settings.reader.lua.txt)

**Comment by hius07** [comment]
Thanks. Can you try the latest nightly build, some fixes were in https://github.com/koreader/koreader/pull/12852.

**Comment by hius07** [comment]
> Some keys are no more relevant like `cover_image_cache_path`.
> May one of these lead to unexpected behavior?

Maybe. Remove this key while KOReader is not running.

**Comment by pipoprods** [comment]
(I first tried removing `cover_image_cache_path`, which didn't change anything).

> Thanks. Can you try the latest nightly build, some fixes were in #12852.

That was it 😀
Next time I encounter something unexpected I'll try the nightly first 😉

Thanks for your help!
