### ISSUE TITLE
Collections: Unextracted metadata in books when adding books to collection

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#12941]
* KOReader version: 2024.11-74
* Device: Kobo Libra 2 (I can´t reproduce it with my Kobo Sage)

#### Issue
When I use the "Add" feature in Collections (Add all books from a folder (and its subfolders), Add a book to collection) my books have temporarily lost its extracted metadata when I am to choose a file.

The reason I updated KOReader today is that it was something wrong with the "Extract and cache..." feature. When using the Extract feature after importing new books, it started to extract all my books. To only extract the new books I had to open a folder with already extracted books (and then go back to Home folder) before starting the extracting process. 
I could not reproduce this with my Sage either. So I suppose there is some connection with the "Add" feature bug.
After the update this problem is gone.

**Comment by hius07** [comment]
I would be glad to investigate but don't understand the issue.

**Comment by gerhaher** [comment]
OK, let's try a video.

https://1drv.ms/v/s!Avn92lO93-jvg4UiXOmjLbnfy3uayg

**Comment by hius07** [comment]
Looks like the "Science & Nature" folder has not been opened yet, and the metadata/covers are extracted for the first time. And it's not the fact, right?
If you open this folder one more time to add another book to a collection, does the extraction start again?
If not, how to reproduce the issue for the same folder?

**Comment by gerhaher** [comment]
> Looks like the "Science & Nature" folder has not been opened yet, and the metadata/covers are extracted for the first time. And it's not the fact, right?

Just to clarify. The metadata has been extracted for all my books. So if I close down Collections and go back to browser all metadata are still there. It is  only during the use of the "add" to collection feature the metadata has temporarily disappeared.
But if you mean that this was the first time I opened the folder for add a book to collection, you are right.

> If you open this folder one more time to add another book to a collection, does the extraction start again?

No, not for books already extracted _during the adding process_

> If not, how to reproduce the issue for the same folder?

I can't. Books that have been extracted  (when adding) are still extracted the next time I add, for example the books you saw in the video.

**Comment by hius07** [comment]
Thanks, I understand, I'll look at it.

**Comment by gerhaher** [comment]
Seems to work now. Thanks!
