### ISSUE TITLE
NewsDownloader: processing fails on single-entry feeds

### ISSUE THREAD

**Issue by hughbagan** [koreader/koreader#12953]
* KOReader version: v2024.11 "Slang"
* Device: Linux AppImage

#### Issue

I wanted to test the NewsDownloader feature in KOReader in anticipation of getting a Kobo. 

I tried adding my site's feed and various others I already use but got several errors. This is just one of them:

![Screenshot from 2024-12-28 15-57-51](https://github.com/user-attachments/assets/25312e04-946f-4cf6-a991-14842686cd7f)

> Could not process some feeds. Unsupported format in: https://hughtoons.com/feed.xml (Reason: Couldn't process RSS) (...) Please review your feed configuration file.

(As you can see I also want to get the CBC's news feed but that's a separate issue. Judging from a short survey it seems the news downloader has many problems?)

In `main.lua`, `NewsDownloader:processFeedSource`: `is_atom` seems to be `nil` even though the [feed](https://hughtoons.com/feed.xml) is an atom file. I tried picking apart the `feeds` table to verify the [right properties](https://github.com/koreader/koreader/blob/master/plugins/newsdownloader.koplugin/main.lua#L386-L390) are present, and they do seem to be, so rather than spend more hours debugging I hope to ask someone who knows the code better.

Also, as a side-effect it seems the wrong error message is being shown.

#### Steps to reproduce

Using a fresh AppImage: 

```
./koreader-appimage-x86_64-linux-gnu-v2024.11.AppImage --appimage-extract
```

Add my site's atom feed to the `feed_config.lua`:

```
 { "https://github.com/koreader/koreader/releases.atom", limit = 1, download_full_article=true, include_images=false, enable_filter=true, filter_element = "div.release-main-section"},
 { "https://hughtoons.com/feed.xml", limit = 5, download_full_article=true, include_images=true},
```

Then run the application and try to sync feeds using the GUI:

```
cd squashfs-root
./AppRun
```

Observe how the KOReader Releases atom feed is recognized, but my site's isn't.

##### `crash.log` (if applicable)

I couldn't find a crash.log; I'm debugging in lua using `logger.warn`

**Comment by Frenzie** [comment]
The plugin isn't really maintained, but it generally seems to work out for people who like it.

Anyway, the problem's fairly simple: because there's only a single `<entry>` it's `feeds.feed.entry`.

Very naively that'd give you:

```diff
diff --git a/plugins/newsdownloader.koplugin/main.lua b/plugins/newsdownloader.koplugin/main.lua
index 05289e34d..961befdf4 100644
--- a/plugins/newsdownloader.koplugin/main.lua
+++ b/plugins/newsdownloader.koplugin/main.lua
@@ -383,11 +383,13 @@ function NewsDownloader:processFeedSource(url, credentials, limit, unsupported_f
         and feeds.rss.channel.item[1].title
         and feeds.rss.channel.item[1].link
     -- Check to see if the feed uses Atom.
     local is_atom = feeds.feed
         and feeds.feed.title
-        and feeds.feed.entry[1]
-        and feeds.feed.entry[1].title
-        and feeds.feed.entry[1].link
+        and feeds.feed.entry[1] or feeds.feed.entry
+        and feeds.feed.entry[1].title or feeds.feed.entry.title
+        and feeds.feed.entry[1].link or feeds.feed.entry.link
     -- Process the feeds accordingly.
     if is_atom then
         ok = pcall(function()
```

But of course the rest of the code expects something else as well. Some quick data normalization seems to fix that:
```diff
diff --git a/plugins/newsdownloader.koplugin/main.lua b/plugins/newsdownloader.koplugin/main.lua
index 05289e34d..44cf2589d 100644
--- a/plugins/newsdownloader.koplugin/main.lua
+++ b/plugins/newsdownloader.koplugin/main.lua
@@ -383,11 +383,20 @@ function NewsDownloader:processFeedSource(url, credentials, limit, unsupported_f
         and feeds.rss.channel.item[1].title
         and feeds.rss.channel.item[1].link
     -- Check to see if the feed uses Atom.
-    local is_atom = feeds.feed
-        and feeds.feed.title
-        and feeds.feed.entry[1]
-        and feeds.feed.entry[1].title
-        and feeds.feed.entry[1].link
+    local is_atom = false
+    if feeds.feed and feeds.feed.title and feeds.feed.entry then
+        if type(feeds.feed.entry) == "table" then
+            if not feeds.feed.entry[1] and feeds.feed.entry  then
+                local entry = feeds.feed.entry
+                feeds.feed.entry = {}
+                feeds.feed.entry[1] = entry
+            end
+            if feeds.feed.entry[1] and feeds.feed.entry[1].title and feeds.feed.entry[1].link then
+                is_atom = true
+            end
+        end
+    end
+
     -- Process the feeds accordingly.
     if is_atom then
         ok = pcall(function()
```

**Comment by Frenzie** [comment]
> (As you can see I also want to get the CBC's news feed but that's a separate issue. Judging from a short survey it seems the news downloader has many problems?)

It times out so the message is accurate if slightly imprecise. That feels more like the server is silently ignoring the request. It's possible that https://github.com/koreader/koreader-base/pull/2010 will help.

**Comment by hughbagan** [comment]
Fantastic, thank you. I just tried it on master and it works. Although the CBC feed is still timing out even with libressl. If that's still happening on the next release I may file another issue about it if I can't find a substitute feed.

**Comment by Frenzie** [comment]
That was a long shot, but it does tell us the problem wasn't an older version of OpenSSL anyway.

Interestingly, it seems to work in my non-JIT Lua 5.1.5.

> http = require("socket.http")
> socket = require("socket")
> socketutil = require("socketutil")
> sink = {}
> url = "https://rss.cbc.ca/lineup/canada-edmonton.xml"
> request = {
>        url     = url,
>        sink    = ltn12.sink.table(sink),
>    }
> code, headers, status = socket.skip(1, http.request(request))
> print(code)
200

**Comment by Frenzie** [comment]
Turns out it's easily reproduced in cURL:
```
curl -v --http1.1 -A "KOReader/2024.04-623 (https://koreader.rocks/) LuaSocket/3.1.0" https://rss.cbc.ca/lineup/canada-edmonton.xml
```
So there's no problem at all. They're blocking/ignoring the user agent.

**Comment by hughbagan** [comment]
I got their server to accept the request by omitting the URL in the user-agent:

```
curl -v --http1.1 -A "KOReader/2024.04-623 LuaSocket/3.1.0" https://rss.cbc.ca/lineup/canada-edmonton.xml
```

Makes sense to me that they would find it suspicious.

**Comment by Frenzie** [comment]
It doesn't make that much sense. It's likely an incorrect assumption that it must be a bot because some bots include a link where you can read what they do.

Additionally they don't block anything if you only send a URL, among other combinations.

Not that I'm attached to having it in there; I think that's something @NiLuJe once added.

**Comment by hughbagan** [comment]
Hm, `curl -v --http1.1 -A "https://koreader.rocks/" https://rss.cbc.ca/lineup/canada-edmonton.xml` still times out when I try it. Omitting just the leading protocol `https://` however and leaving `koreader.rocks` is enough for it to accept.

**Comment by Frenzie** [comment]
Strange, I'd swear that worked yesterday.

Regardless, I think the only proper solution for idiosyncratic servers would be to add a user agent configuration.

For some related reading: <https://vivaldi.com/blog/user-agent-changes/>, <https://vivaldi.com/blog/technology/client-hints-or-client-lies/>, <https://vivaldi.com/blog/desktop/client-hints-and-a-sense-of-deja-vu-vivaldi-browser-snapshot-2950-3/>

**Comment by hughbagan** [comment]
I'm not an expert. A brief search on the subject of URLs in the User Agent says that it's generally a trait of crawlers, spiders-- bots. I'm not sure that KOReader fits that description. I suppose on principle it shouldn't matter, but in reality it's a practical, albeit dated, measure for this server to prevent abuse. There could be a config option, but as long as this is the default you're going to keep getting tickets about it since this is the most popular news server in Canada. (See #10186)

**Comment by Frenzie** [comment]
My point is merely that one server is one server. Changing things to please it might break a thousand others, and it might still break tomorrow.

> A brief search on the subject of URLs in the User Agent says that it's generally a trait of crawlers, spiders-- bots.

Perhaps more accurately, it's something not normally done by browsers. But any "evil" bot will simply pretend to greater or lesser degree to be a browser. Compare the innocuous [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr/) which literally runs an entire browser just to get around CloudFlare.

If CloudFlare thinks known KOReader with a URL is fine but without is probably a fake bot, there goes half the internet.

`LuaSocket/3.1.0` and anything like it (such as `curl/8.9.1`) is also indicative of what I'd more neutrally call tools. I wouldn't want to remove that though. There are even stories of people having to change their Apt user agent to be able to install packages behind corporate firewalls.

**Comment by Devnol** [comment]
Hey, I'm really new to koreader but I was having a similar issue and thought I might report this here or see if I could get some direction. I installed the nightly build for KindleHF (latest fw 5.17.x on a PW5/11th gen) and tried to add a couple news sites, getting similar errors. I tried The Verge's atom feed https://www.theverge.com/rss/index.xml and Engadget's RSS https://www.engadget.com/rss.xml and they both seem to have failed. XKCD's rss fetches comics fine. Is this something that was fixed and will be available in a later release or am I missing something?

**Comment by Frenzie** [comment]
None of those are single-entry feeds. They will have worked regardless. Set download full article to false.

![Screenshot_20250109_180507](https://github.com/user-attachments/assets/96520c58-afb6-46d6-b4d6-d6dbf479bb27)

**Comment by Devnol** [comment]
That seems to have worked for the verge, engadget still fails with a similar error, note that the w3c validator shows the engadget feed as invalid: (https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.engadget.com%2Frss.xml). Anyway I can make do without that specific source, if I notice it happens on others I'll see what's up

**Comment by Frenzie** [comment]
> That seems to have worked for the verge, but only for getting news headlines.

That means you're using a version from before two weeks ago.

**Comment by Devnol** [comment]
I'm on 2024.11-120 (kindlehf) from January 3rd

**Comment by Frenzie** [comment]
Maybe I'm misunderstanding something, but it looks to me like they are full articles (i.e., with download full article = false, really what that means is download the original source HTML page from the website).
<img src=https://github.com/user-attachments/assets/3f9c5c96-df5d-4ca7-a69a-a9747a662d99 width=45%> <img src=https://github.com/user-attachments/assets/e313e0fb-63f1-4085-a218-058d99470a14 width=45%>

**Comment by Devnol** [comment]
Yeah I'm not quite sure, some show up full with 2-4 pages of content and some like the article about the tiktok ban from earlier today only has a couple lines of content and then "read the full story on the verge". Maybe it's just a them thing but I can't tell

**Comment by Frenzie** [comment]
In that case they'll put that in for the occasional entry. There's nothing much to be done about that.
