### ISSUE TITLE
NewsDownloader: unknown image ext mimetypes

### ISSUE THREAD

**Issue by hughbagan** [koreader/koreader#12967]
* KOReader version: be5cab65d26ddfd0e71bb34ecfc689b7d4cbf508 
* Device: Linux emulator, built from source on Debian 12

#### Issue

I see that the news downloader [ignores images that don't have a file extension](https://github.com/koreader/koreader/blob/04c0ee5f04fd0375e6f66cc5917b495838ebcede/plugins/newsdownloader.koplugin/epubdownloadbackend.lua#L355-L360).

Fair enough; however, some images that are legitimate content are being ignored. This comic feed for example has no file extensions, presumably because the images are being treated as a mere bucket resources: https://artskydj.github.io/rss-previewer/?url=https://www.comicsrss.com/rss/betty.rss

`<img src="https://assets.amuniversal.com/0c44c980a36f013d84c6005056a9545d">`

The image knows it's a GIF, and if I save it as that, or even a PNG, it works:

![Screenshot from 2024-12-31 00-42-26](https://github.com/user-attachments/assets/c003ef6a-b234-4bf8-a580-bf665f0958cc)

Is there a different way the mimetype can be interpreted to account for this? I could always run my own fork for this hack but I'd rather not if there's a better way.

Not sure if this is a feature request.

#### Steps to reproduce

Add this to your `feed_config.lua`:
```
 { "https://www.comicsrss.com/rss/betty.rss", limit = 3 , download_full_article=false, include_images=true},
```

Sync it, and open one. You'll see an empty missing rectangle where the comic strip should be.

##### ~~`crash.log` (if applicable)~~

**Comment by Frenzie** [comment]
I'm not entirely sure what the rationale for the ignoring there is since it doesn't seem to check if any of the found extensions are supported. I suspect it was copied over from Wikipedia and perhaps it can simply be deleted.

Though as I write that I see it's used in EPUB metadata and may be obligatory? Pinging @poire-z 

The mimetype should normally be retrievable by asking for headers, but that could add a lot of extra server round trips.

**Comment by poire-z** [comment]
It indeed looks like it was copied from wikipedia.lua.
Dunno about what newsdownloader should do.

> Though as I write that I see it's used in EPUB metadata and may be obligatory? 

I tried to build a proper EPUB with Wikipedia :) discovering at the time how it all really works and its specifications, so I went at storing the guessed mimetype.
But I don't think crengine cares at all: no matter what's in the EPUB's .opf, if it see `<img src="somefile">` in some HTML file, it tries to find that somefile, no matter its presence in the .opf or the extension. If found, it loads it and try to see if it's an image it can decode and render.

**Comment by Frenzie** [comment]
If you simply go ahead and download the image, the headers should normally also have the mimetype (e.g., in this case `Content-Type: image/gif`), but unfortunately that would mean a reversal of the current code.

I think removing the condition's perfectly fine for the moment, but of course it won't be compatible with all EPUB viewers.

For example epubcheck says:
```
ERROR(PKG-011): ./24-12-30_01-00_Betty by Gary Delainey and Gerry Rasmussen for Mon_ 30 Dec 2024.epub/OEBPS/images/img00001.(-1,-1): Filename is not allowed to end with ".".
```

But visible in some/most is presumably better than in none. ;-)

**Comment by hughbagan** [comment]
Thanks guys for all your amazing work on KOReader!

**Comment by Frenzie** [comment]
Like I said NewsDownloader is more or less unmaintained at this point (and I'm not volunteering to take over at this time :-), but good bug reports go a long way, so thanks for writing them.
