### ISSUE TITLE
Why is Kobo Aura H2O NOT on the supported devices list?

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#1307]
Just wondering what is the list of major known problems for KOReader on Kobo Aura H2O. If there are no major issues then perhaps we should add it to the matrix of supported devices on the Wiki page.

I just bought a Kobo Aura H2O and am going to install KOReader+CoolReader+KSM today...

**Comment by Domistr** [comment]
May I ask which folder to put cool reader into?

**Comment by Frenzie** [comment]
If you're using KSM8 then you should be able to put it into the .adds folder next to koreader. So you'll have a `.adds/coolreader` and a `.adds/koreader`, or whatever the precise names are.

**Comment by KenMaltby** [comment]
It should be;
kbmenu
koreader
vlasovsoft

folders in the .adds directory.

**Comment by Domistr** [comment]
Thanks, I had them in the .kobo directory. Marek Domanski
+61 (0)416812309

**Comment by Domistr** [comment]
Thanks very much, got it working now. I had most things in the .kobo folder Marek Domanski
+61 (0)416812309
