### ISSUE TITLE
v1266: PDF stuck at last read page

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1315]
I have discovered a very weird bug. I have opened [this PDF](http://www.linuxvoice.com/issues/001/Linux-Voice-Issue-001.pdf) and am stuck at site 54 of it (last open page). Sometimes i can  change to 52 and back to 54, but else i am completely stuck.

Edit: so after crashing koreader several times and reopening LV issue 1 and tapping endless times on the next page area it works again, for limited time, then i have to bombard the right side of the screen with my finger again to get unstuck. Then after some time (can't notice a pattern) it gets stuck again.

Video (only the first 14 sec show the bug): https://mediacru.sh/ASITiVvjQ9nZ

When i try another [PDF – Farewell to Arms](https://archive.org/details/farewelltoarms01hemi) from the Internet Archive – koreader crashes and the crash.log is empty. But that might be a memory problem and another bug. Shall i open a new issue?

The PDF manual of my Kyocera printer works without problems but it doesn't has big pictures, only simple images with outline drawings (manual style).

**Comment by chrox** [comment]
The stuck issue should be already fixed by 1f09465 in #1662. Please reopen this if you still have this problem.
