### ISSUE TITLE
Kobo Aura HD: Long hold of the power slider results in suspend, not shutdown

### ISSUE THREAD

**Issue by wasamasa** [koreader/koreader#1326]
See title. Is this behaviour intentional? If not, how can I help debugging this? I'm using the latest nightly and can only power off by switching to the komenu screen, then selecting the shutdown option.

**Comment by chrox** [comment]
I agree with @NiLuJe, koreader is just a reader program. It should not be expected to control your device power on/off. I'm closing this now.
