### ISSUE TITLE
page flipping mode should have a large progress bar tap on which could jump to certain page

### ISSUE THREAD

**Issue by Juddd** [koreader/koreader#1327]
the koreader is a charming plug-in unit for my kpw2,if you can give me a “page-flip” like as official.i will thank you more.by the way, i do no like indeed yours flip,“Go to Page or Location”or click the top left corner.

**Comment by Frenzie** [comment]
I'll close this as implemented in #2460. (Also it has the progressbar at the bottom; not sure if that was there at the time this issue was opened.)
