### ISSUE TITLE
Export/broadcast progress%

### ISSUE THREAD

**Issue by apopagasm** [koreader/koreader#1332]
Hi- I'm wondering if it's possible for koreader to broadcast my progress in a book to a PC or web client that takes that and then plays music based on it? http://cl.ly/image/2q210P342S0i

I think I'm talking about wanting an API to let me access progress%, basically, and wondering if that's currently possible or if y'all would be willing to add that (no idea how difficult it would be to create, mind).

More details on what I want to do are here: http://www.mobileread.com/forums/showthread.php?t=252259

Thanks

**Comment by chrox** [comment]
Close this now.
