### ISSUE TITLE
LuaJIT won't do GC when popup/dismiss reader menu repeatedly

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#1352]
Interesting problem, reproducible easily in the emulator:
1. Run `watch -n 1 "ps aux | grep luajit" in a terminal
2. Open some epub file.
3. Go to History via menu (do NOT exit back to FileManager!) as it is now possible to do so.
4. Open the same file from History
5. Go back to step 2.

Now observe in the terminal that both the RSS and the total VM size is growing slowly but surely, by about 600K from each open. This is not critical as modern devices have plenty of memory, but in principle you can crash your system (cause OOM situation) by re-opening the same file enough times.

**Comment by chrox** [comment]
The "leak" is not limited to EPUB format and with valgrind I cannot trace explicit memory leaks. So probably it's from LuaJIT's GC as @hwhw suggested.

**Comment by Frenzie** [comment]
I'll close this issue now. :-)
