### ISSUE TITLE
Strange highlights with Floating punctuation off

### ISSUE THREAD

**Issue by Ebrehem** [koreader/koreader#1369]
A picture is better than any word:
![screenshot_2014-dec-20_161126](https://cloud.githubusercontent.com/assets/8835359/5515267/88675200-8863-11e4-8766-d1c864817287.png)

The highlight which extends to the bottom of the screen works as highlight, if touched, the option to delete comes up. With floating punctuation on they are normal. And it also doesn't seem dependant on the book read, but I don't know what. (In many cases highlights appear normally).

**Comment by chrox** [comment]
Could you provide a sample file for others to reproduce this issue? I could hardly reproduce this with English book.

**Comment by WS64** [comment]
It happens with EVERY book.

**Comment by Ebrehem** [comment]
Yes, also in English books. But here is one. http://data.hu/get/8420520/Ida_regenye_-_Gardonyi_Geza.epub

**Comment by WS64** [comment]
First highlight I tried on my PB Lux 2 again resulted in this behaviour. I cannot understand why other folks seem not to have this problem, I have it on every reader with every book!

**Comment by chrox** [comment]
Cool. I can now reproduce this behavior on emulator. The key point is as this title stated that when floating punctuation is turned off. I will investigate into this later.
