### ISSUE TITLE
Spurious bookmarks

### ISSUE THREAD

**Issue by mmjoshi** [koreader/koreader#1372]
I am using the 2014.11-stable and using the search highlight function heavily. That works perfectly., However, along with the highlighted text I have noticed some spurious bookmarks under the bookmarks tab. These occur in pair with slightly different time stamps and were never created by me. Moreover, if I go to the page pointed to by this bookmark I do not see the bookmark sign in the top right corner, hence I am unable to remove these bookmarks. Is there any way to remove these bookmarks as they unnecessarily clutter the bookmarks page.

**Comment by chrox** [comment]
Now text highlights are also shown in bookmarks but it won't show the dogear at the upper right corner.

**Comment by chrox** [comment]
Now text highlights are also shown in bookmarks but it won't show the dogear at the upper right corner.

**Comment by chrox** [comment]
Now text highlights are also shown in bookmarks but it won't show the dogear at the upper right corner.

**Comment by chrox** [comment]
Now text highlights are also shown in bookmarks but it won't show the dogear at the upper right corner.

**Comment by chrox** [comment]
Now text highlights are also shown in bookmarks but it won't show the dogear at the upper right corner.

**Comment by chrox** [comment]
Now text highlights are also shown in bookmarks but it won't show the dogear at the upper right corner.

**Comment by chrox** [comment]
This will be fixed in #1408 which brings the ability to delete bookmarks in bookmark window and duplicated bookmarks won't be added to bookmark list.
