### ISSUE TITLE
Ligature for epub and plain text

### ISSUE THREAD

**Issue by limelightful** [koreader/koreader#1378]
Is there any way to enable ligature in koreader ?
ex: fi ff fl etc.

**Comment by Frenzie** [comment]
Here's an example of how you'd have to use something on top of freetype, I think. 

https://github.com/anoek/ex-sdl-cairo-freetype-harfbuzz

**Comment by emacsomancer** [comment]
Is there still no way of enabling ligatures for epub?

**Comment by cramoisi** [comment]
just looking at the file, I noticed the classic one (ufb01 - 6) are just not defined in crengine (they are for [antiword](https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/thirdparty/antiword/wordconst.h#L306)). Don't know if it's complicated to do though.

**Comment by cramoisi** [comment]
yup, they render well, i tested that. I was wondering if it was possible to force the rendering like it's done wit the ae or oe (but the answer is no :))

**Comment by poire-z** [comment]
Should now be possible with the new kerning method `enhanced` after #4167
