### ISSUE TITLE
dictionary with DJVU

### ISSUE THREAD

**Issue by Muson117** [koreader/koreader#1379]
Hi,

Dictionary is working fine with PDF, problem just in DJVU.

When I hold a word for instance "Braid" in DJVU book it highlights correctly but searches dictionary for "Braidbraidbraidbraidbraidbraidbrai" (number of chars is exact, only first letter is upper case) and of course "no definition found". Word length does not matter it just repeats to fill line "obligatoryobligatoryobligatoryobligatory".

Also quite often holding word for dict lookup KOreader exist to Kindle homepage.

Thanks

Using:
koreader-stable-v2014.11
http://abloz.com/huzheng/stardict-dic/dict.org/stardict-dictd_www.dict.org_gcide-2.4.2.tar.bz2
tesseract-ocr-3.02.eng.tar.gz
KPV Booklet
Kindle PW2 5.4.2.1

**Comment by chrox** [comment]
This bug is confirmed.
