### ISSUE TITLE
Math charactor of equations in PDF not rendered

### ISSUE THREAD

**Issue by ptbsare** [koreader/koreader#1380]
* This is the screenshot when I open a PDF with koreader.
![screenshot_2014-dec-30_142922](https://cloud.githubusercontent.com/assets/3147576/5576276/d3d7d554-9031-11e4-9de6-7596751f0bc2.png)
* This is the screenshot when I open the same PDF with the local system reader. And it rendered correctly. 
![screenshot_2014_12_30t14_36_08 0800](https://cloud.githubusercontent.com/assets/3147576/5576286/15086d90-9032-11e4-9ba4-d01ab8c1c5be.png)
* So how can I fix this?

My device is Kindle Paper White 2. And the version of koreader is v2014.11-5-g199f864

**Comment by chrox** [comment]
Looks like a similar issue with #548.

**Comment by ptbsare** [comment]
Yeah, I agree. Anyway to fix this? I wonder if there is a way to manually add some fonts which the pdf reader can use or registered to the system?

**Comment by chrox** [comment]
You can try embedding the missing fonts in the document as I suggested [here](https://github.com/koreader/koreader/issues/548#issuecomment-40204360) in #548.

**Comment by chrox** [comment]
I will treat this as a duplicated issue to #548 and close this now.
