### ISSUE TITLE
OTA: Can't update nightly

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1384]
With a current nightly (n-2)  am not able to use the OTA function. It always ends in the following message:

> Error updating koreader. Would you like to delete temporary files?

The error message is less than stellar. And i couldn't find a log file.

Can we improve the error message and add such error to a/the log? (Which should be browsable by koreader itself!).

**Comment by Markismus** [comment]
I can confirm this on kobo Aura H2O. (As I wrote on #1383).

**Comment by NiLuJe** [comment]
We seem to currently only have a single outdated release available on the OTA mirrors (and on the master, too). Ping @chrox?

**Comment by chrox** [comment]
Probably I can test the OTA for PocketBook 840 after there are several OTA updates in the server.

**Comment by chrox** [comment]
OTA server is tested without problem here. Please reopen this if you still cannot update via OTA.

**Comment by NiLuJe** [comment]
Yup, everything in order on my end right now :).
