### ISSUE TITLE
Will koreader send annotations and highlights of kobo original system to evernote?

### ISSUE THREAD

**Issue by scokyfei** [koreader/koreader#1385]
Now KOReader can only send itself annotations and highlights to evernote on kobo. Could you add a function to send highlights and annotations of kobo original system  to evernote like it in kindle?

**Comment by chrox** [comment]
We can do it if we can get the highlight data first. I have no Kobo devices so probably cannot help you much. But in Kindle the original system writes all highlight data into a plain text we parse that text file to get highlight data.

**Comment by chrox** [comment]
Seems no progress on this issue. Close this now.
