### ISSUE TITLE
在使用中发现的一些问题

### ISSUE THREAD

**Issue by comcn** [koreader/koreader#1391]
我很喜欢koreader这个软件，我使用他有两年时间了，她使我在使我kindle的时候有个更好阅读软件，也是我喜欢kindle的原因之一，自从有了安卓版妈妈再也不用担心我看pdf文件的问题了，自从安卓版第一版我就用她来看pdf,那时候她在安卓上看书的效果就比多数软件都好，现在就更不用提了，但我总是小心翼翼的用着，稍微不注意她就自己退出去了，我又得从新把书打开，现在好多了只是轻点界面没什么问题，能正常使用，但是如果不小心在界面滑动一下手指，她直接退出去了，这跟很多其他软件不一样，他们即使不能正常工作了有时也死活关不了，我不认为这样是好的，但是也想你们在以后更新的时候考虑把他做强壮些，除非我想退出去，不然不要自己退掉，我知道这有很多问题需要克服，也需要时间，我还是希望在以后某一次更新后，koreader更加强壮了。我不确定有没有人提到过这个情况，我看不懂英文，也不确定你们看得懂中文不，废话了这么多只是想表达两个意思，一，我很喜欢这个软件跟网上很多人一样，二，希望这个软件强壮些
  最后向所有对项目作贡献的人致敬！

**Comment by chrox** [comment]
Short description is that Koreader sometimes crashes on Android. 

And it's a known problem and duplicated to #643. You can find more discussions there. Closing this ticket now.
