### ISSUE TITLE
 Is possible read all bookmarks without having to view ebook page?

### ISSUE THREAD

**Issue by namoplasta** [koreader/koreader#1395]
It's bad have to click and make all the time the same procedure to view all text hightllight in bookmarks.

In the bookmarks list only have a short text, it is not possible see all text expand only.

Is there a  feature for this?

**Comment by lightonflux** [comment]
> Is there a feature for this?

Not yet.

**Comment by namoplasta** [comment]
If possible implement is good.

Is good for users that need read all highlight text in book after finishing reading a book.

I thought of a way where I could go in the next previous highlighted text.

**Comment by lightonflux** [comment]
Here my idea how it could be implemented. But maybe a popup window would be better for longer quotes and/or screen refreshes. 

![bookmarks-expand](https://cloud.githubusercontent.com/assets/1377943/5829137/b8cfd9b8-a10d-11e4-94ba-901e2a0a52c4.png)

**Comment by namoplasta** [comment]
lightonflux, yes, good ilustration.

**Comment by chrox** [comment]
There is an option to export all highlights to your Evernote account or to a local HTML file in the koreader clipboard directory which are the recommended way to read the highlights. To read all highlights in Koreader bookmark window is awesome but it is of low priority to implement.

**Comment by namoplasta** [comment]
Yes, I understand, also did not know the resource for local export, i thought evernote was only in the cloud.

But give another idea, which would navigate next or previous highlighted on the document page. For example did a highlight on page 3, on page 12 did, he will go where the highlights are. This a suggestion.
