### ISSUE TITLE
Can't login evernote in koreader.

### ISSUE THREAD

**Issue by bananallm** [koreader/koreader#1401]
I Can't login evernote in koreader,kindle p2.      5.6.1        koreader2014.11stable.
When I touch the login button,nothing would happen,I have to restart my kindle.

**Comment by boplennon** [comment]
After upgrade it  to the newest nightly build, this bug has still happened. Moreover, when I downgrade to the version that I used to login successfully, I get the following message:
"An error occurred while logging in: plugins/evernote.koplugin/EvernoteOAuth.lua:339: OAuth verifier not found"

**Comment by candideu** [comment]
> 
> 
> After upgrade it to the newest nightly build, this bug has still happened. Moreover, when I downgrade to the version that I used to login successfully, I get the following message:
> "An error occurred while logging in: plugins/evernote.koplugin/EvernoteOAuth.lua:339: OAuth verifier not found" @chrox

I'm having the exact same issue with the latest KOReader version for Kobo devices (v06.2020)

**Comment by pazos** [comment]
@candideu: There's an open ticket in #6281
