### ISSUE TITLE
touch is not functional on new kindle(kindle 2014 with touch) with 5.6.1.0.2

### ISSUE THREAD

**Issue by bt4wang** [koreader/koreader#1403]
My device:new kindle(kindle 2014 with touch)
Firmware Ver. :5.6.1.0.2
KOReader Ver. :koreader-kindle-arm-linux-gnueabi-v2014.11-39-g917f45a

I've got my device jailbreaked via serial debug, also got kpvbooklet installed via MR Installer. The problem is that when I try to open a pdf file, koreader launched successfully with the first page showed up perfectly, but the touch screen stoped functional. So I can't turn pages, active menu or exit koreader. Hope you can fix this issue. 

Please let me know if any further information is required.

**Comment by NiLuJe** [comment]
Expected, since we don't have a device on hand ;).

So we'll need a couple of info, to fix first the input, and second the screen updates, which are potentially suboptimal right now. Could you post the output of:

```
ls -lash /dev/input/by-path/
```

&

```
eips -i
```

**Comment by bt4wang** [comment]
Just got these output you've required. Thanks for all your effort :D

[kterm]# ls -lash /dev/input/by-path/
   0 drwxr-xr-x    2 root     root          80 Jan 28 08:46 .
   0 drwxr-xr-x    3 root     root         120 Jan 28 08:46 ..
   0 lrwxrwxrwx    1 root     root           9 Jan 28 08:46 platform-imx-i2c.0-platform-max77696-onkey.0-event -> ../event0
   0 lrwxrwxrwx    1 root     root           9 Jan 28 08:46 platform-zforce2.0-event -> ../event1
[kterm]# eips -i

Fixed framebuffer info
    id:              mxc_epdc_fb    smem_start:       0x80C00000
    smem_len:            3268608    type:          PACKED_PIXELS
    type_aux:                  0    visual:   STATIC_PSEUDOCOLOR
    xpanstep:                  1    ypanstep:                  1
    ywrapstep:                 0    line_length:             608
    mmio_start:       0x00000000    mmio_len:                  0
    accel:                     0

Variable framebuffer info
    xres:                    600    yres:                    800
    xres_virtual:            608    yres_virtual:           5376
    xoffset:                   0    yoffset:                   0
    bits_per_pixel:            8    grayscale:                 1
    red.offset:                0    green.offset:              0
    red.length:                8    green.length:              8
    red.msb_right:             0    green.msb_right:           0
    blue.offset:               0    transp.offset:             0
    blue.length:               8    transp.length:             0
    blue.msb_right:            0    transp.msb_right:          0
    nonstd:                    0    activate:                128
    width:                    91    height:                  122
    accel_flags:               0    pixclock:           27027027
    left_margin:               8    right_margin:            100
    upper_margin:              4    lower_margin:              8
    hsync_len:                 4    vsync_len:                 1
    sync:                      0    vmode:                     0
    rotate:                    3

**Comment by chrox** [comment]
You may need to add a line 
```
self.input.open("/dev/input/event1")
```
below this line 
```
self.input.open("/dev/input/event0")
```
here: https://github.com/koreader/koreader/blob/master/frontend/device/kindle/device.lua#L181

**Comment by bt4wang** [comment]
Problem solved. You guys are amazing.
![2015-01-30_14-49-24_20d3b9](https://cloud.githubusercontent.com/assets/10733801/5972165/f5cefacc-a88f-11e4-9994-13b598fceff3.jpg)

**Comment by chrox** [comment]
Could you also send a pull request to fix this?
