### ISSUE TITLE
Is poweroff an alternative for 'echo mem > /sys/power/state' on Kobo

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1404]
I remember when I tried to hack a standby feature into Kobo Aura HD that busybox didn't have a command for it. So after reading on [mobileread that busybox knows `poweroff`](http://www.mobileread.com/forums/showthread.php?p=3032794#post3032794), I am wondering whether this would be a good alternative to 'echo mem > /sys/power/state'.

**Comment by hwhw** [comment]
It's an alternative, but not of equivalent functionality. Power off, well, powers off the device. It will boot from scratch when powered on again. "echo mem > /sys/power/state" is not a hack, but rather the standard kernel interface for putting the device into standby.

**Comment by Frenzie** [comment]
Indeed. I <3 everything is a text file. :)

**Comment by Markismus** [comment]
Thanks for clarifying.
