### ISSUE TITLE
page-turn buttons are not working on Kindle Voyage

### ISSUE THREAD

**Issue by mapingchao** [koreader/koreader#1406]
设备名称:kv
固件版本:5.6.1.0.2
KOReader版本:koreader-kindle-arm-linux-gnueabi-v2014.11-50-g5d81512.zip

此设备已通过串口调试完成越狱，并通过MR Installer安装了kpvbooklet 0.5.8。目前可通过kpvbooklet调用koreader使用。遇到的问题是kv左右两侧4个实体按键失效，希望能开发实体按键自定义功能，最低限度希望能如原生阅读器使用实体键翻页。

**Comment by bt4wang** [comment]
English Version:

Device: Kindle Voyage
Firmware Version: 5.6.1.0.2
KOReader Version: koreader-kindle-arm-linux-gnueabi-v2014.11-50-g5d81512.zip

The page turn sensors of KV are not available for use in this version of KOReader. Could you please make them functional. It will be fantastic if we can customize these sensors's mapping.

**Comment by chrox** [comment]
Congratulations you jailbreak your KV. Could you install @NiLuJe 's [USBNetwork](http://www.mobileread.com/forums/showthread.php?t=186645) on your jailbroken KV and in a SSH session run the following commands:

```
cd /mnt/us/koreader
./reader.lua -d /mnt/us/documents
```

And then press the page-turn buttons on your KV. You will see the button events like this:

```
# key ev {
	["type"] = 1,
	["time"] = {
		["usec"] = 608740,
		["sec"] = 1422776002
	},
	["code"] = 24,
	["value"] = 0
}
```
Please report the key ev for each button on your device and then we can add the support of what you request.

**Comment by bt4wang** [comment]
Mapingchao's KV has been stolen. We need another brave man to disassemble his KV and get it jailbroken.

**Comment by houqp** [comment]
Sorry to hear that @mapingchao  :(

**Comment by ieuYao** [comment]
左右的下一页按键都是：
# key ev {
        ["type"] = 1,
        ["time"] = {
                ["usec"] = 412303,
                ["sec"] = 1422873950
        },
        ["code"] = 109,
        ["value"] = 1
}

左右的上一页按键都是：
# key ev {
        ["type"] = 1,
        ["time"] = {
                ["usec"] = 59282,
                ["sec"] = 1422874390
        },
        ["code"] = 104,
        ["value"] = 1
}
