### ISSUE TITLE
Opening DjVu file results in "No reader engine for this file" Kobo Aura HD

### ISSUE THREAD

**Issue by SmilePlz** [koreader/koreader#1409]
hi guys!
I can not open the format *.djvu on Kobo Aura HD. release version koreader-stable-v2014.11 and koreader-nightly-20150131. I read this topic https://github.com/koreader/koreader/issues/1343, but the latest version KOreader error persists.

Apologies for the English, I use a translator.

**Comment by Reventl0v** [comment]
Same here on a Kobo Aura H2O.

**Comment by chrox** [comment]
Fixed by #1471.
