### ISSUE TITLE
extensions.cfg for PocketBook

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#1410]
I'm still not satisfied with the way Koreader overwrites the extensions.cfg file on Pocketbook devices.
Right now for example it will change the epub entry to <code>epub:@EPUB_file:1:koreader.app:ICON_EPUB</code>.
This will make my FB Reader and Coolreader unavailable since they got thrown out of this file.
Maybe the entry should look like this:
<code>epub:@EPUB_file:1:koreader.app,AdobeViewer.app,fbreader.app,cr3-pb.app:ICON_EPUB</code>
In that case people will see other entries in the "open with" menu in the library, even if they are not installed. I think this is better than not being able to use FB Reader and Collreader at all anymore.
I still don't know if this menu exists at all for 5.4 and 5.5, it does exist on 4.4 and does not exist on 5.2.
For starting Koreader from the applications menu I don't think this entry is necessary at all, and especially since for 5.2 (newest firmware for all Lux devices) this is the only way to start Koreader the actual behavior should be changed.

I can see the options
a) enhance the entry (like above)
b) remove this file completely (and maybe add a text file explaining how to manually add this entry)
c) to find another way to edit this file during the first start of Koreader (adding the entry on the first position for all necessary entries)
I am not sure which one I prefer, but the way it is handled now many entries get lost.

To compare it, here is a list of all I have in my 4.4 firmware:
<code>
acsm:@ACSM_file:1:AdobeViewer.app:ICON_ACSM
app:@APP_file:4:start.app:ICON_APP
asp:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTM
bmp:@BMP_image:2:jpegviewer.app:ICON_BMP
cgi:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTM
chm:@Z_HTML_file:1:fbreader.app,cr3-pb.app:ICON_CHM
djv:@DJVU_file:1:djviewer.app:ICON_DJVU
djvu:@DJVU_file:1:djviewer.app:ICON_DJVU
doc:@DOC_file:1:fbreader.app:ICON_DOC
docm:@DOC_file:1:fbreader.app:ICON_DOC
docx:@DOC_file:1:fbreader.app:ICON_DOC
epub:@EPUB_file:1:AdobeViewer.app,fbreader.app,cr3-pb.app:ICON_EPUB
fb2:@FB2_file:1:fbreader.app,cr3-pb.app:ICON_FB2
hrss:@HTML_file:1:links.app:ICON_HTM
htm:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTM
html:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTML
jpeg:@JPEG_image:2:jpegviewer.app:ICON_JPG
jpg:@JPEG_image:2:jpegviewer.app:ICON_JPG
jsp:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTM
mht:@HTML_file:1:cr3-pb.app:ICON_HTM
mobi:@PRC_file:1:fbreader.app:ICON_PRC
mp3:@Music_file:3:play.app:ICON_MP3
pbi:@APP_file:4:sysinstall.app:ICON_APP
pdb:@PRC_file:1:fbreader.app:ICON_PRC
pdf:@PDF_file:1:AdobeViewer.app,pdfviewer.app:ICON_PDF
php:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTM
pl:@HTML_file:1:fbreader.app,cr3-pb.app:ICON_HTM
png:@PNG_image:2:jpegviewer.app:ICON_PNG
prc:@PRC_file:1:fbreader.app:ICON_PRC
rtf:@RTF_file:1:fbreader.app,cr3-pb.app:ICON_RTF
tcr:@TCR_file:1:fbreader.app:ICON_TCR
tif:@TIFF_image:2:jpegviewer.app:ICON_TIFF
tiff:@TIFF_image:2:jpegviewer.app:ICON_TIFF
txt:@Text_file:1:fbreader.app,cr3-pb.app:ICON_TXT
wlnk:@weblink:5:fbreader.app:ICON_WWW
</code>

**Comment by chrox** [comment]
First of all, the current approach does not force the users to substitute the system `extensions.cfg` with the one from koreader package. As the installation guide stated:
> If you want to associate KOReader with all PDF, EPUB, DJVU, FB2, CBZ documents you could copy and merge the "system" directory from the unzipped content to your PocketBook's USB storage. (This step is optional.)

it's *optional* to make koreader the default reader. I'm not going to fiddle with the `extensions.cfg` and make complex sorting of apps for a specific format right now because on firmware 5.4 or 5.5 the apps list for one format as you listed above doesn't work anymore. And probably pocketbook guys have not decided how to reactivate this feature. We still need to wait.
