### ISSUE TITLE
Koreader on Android missing front light settings

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1415]
Hi

KR on Boyue T62 works in general but missing front light settings so there is no way to set light on it. 

This is an E-ink Android device.

thanks

**Comment by yasteora** [comment]
KR runs on T62 often crash

**Comment by gerroon** [comment]
@yasteora 

KR is really unstable on Android devices :( I get so many crashes as well

**Comment by hwhw** [comment]
It depends on the Android device - the memory layout is still a problem with some devices. Frontlight setting on Android should be there in latest versions, BTW.

**Comment by gerroon** [comment]
@houqp 

That is so cool. Thanks for implementing it. I am so eager to try this if we can get an Android build soon.

**Comment by houqp** [comment]
I just clicked the merge button, @chrox did all the work :P

**Comment by gerroon** [comment]
thanks @chrox
