### ISSUE TITLE
pdf missing lines at bottom on H2O 

### ISSUE THREAD

**Issue by noisebrain** [koreader/koreader#1422]
With several recent builds (Jan-Feb 2015, currently using v2014.11-81-g49c8ec2 )
the little progress slider bar at the bottom is partially obscured by the bezel.

Also, in fit-content-width zoom mode, the view misses a couple lines at the bottom of the page. Going to the next page skips over them, there is no way to see them without changing the view to the whole page (which is undesirable, very small type with an A4 scientific pdf).

In frontend/device/kobo/device.lua I tried changing 
>    viewport = Geom:new{x=0, y=10, w=1080, h=1430},

to 
>    viewport = Geom:new{x=0, y=10, w=1080, h=1420},

This did move the bottom progress bar up to be visible, but the last few lines are still cut off in fit-to-content-width.
It also may have killed several of the zoom modes, they seem to be missing now.

A question: several reviews say that the resolution of the H2O is 1080x1430, not 1440.  Is there some part of the koreader code that is incorrectly(?) assuming the resolution is 1440?

**Comment by Frenzie** [comment]
The problem is that the status bar is an overlay. It has nothing to do with the H2O as such. Normally I suppose it doesn't obscure anything but a page number or some such. But perhaps I misunderstand, because you say this didn't occur until January. I can easily reproduce the problem on an emulator compiled back in November.

My preferred way of using the program is having the statusbar set to display all. That way it just toggles on and off. I suppose that isn't the default because of devices with lower resolution displays. For reading PDFs and DjVus specifically, scroll mode is my default. Not because of this issue, mind you, but it does manage to avoid it completely.

> A question: several reviews say that the resolution of the H2O is 1080x1430, not 1440. Is there some part of the koreader code that is incorrectly(?) assuming the resolution is 1440?

I don't know if there are actual physical pixels hiding under the bezel, but I suppose so because that's what the hardware reports. KOReader has nothing to do with that besides having to come up with complicated workarounds.

**Comment by NiLuJe** [comment]
It's physically 1080x1440, but the top **11** pixels are obscured by the bezel (and blacked out by nickel), so the effective resolution is 1080x1029 ;).

**Comment by Frenzie** [comment]
Well, I suppose one of us should put that in a PR then. ;)

**Comment by noisebrain** [comment]
Two clarifications to the OP: 
1. I indicated the problem with the builds from January, however that is when I purchased the device,
   I did not try earlier builds, so not indicating the problem was not present in November.
2. "The view misses a couple lines at the bottom of the page", meaning a couple lines of text, not a couple lines of pixels. This is on a pdf that has approximatly 44 lines of text (hard to say exactly, it has some formulas on every page).

I have only just started using this, please treat me as a confused person.

I would like to try Frenzie's suggestions.  Are these what you intended?
> -- for statusbar set to display all 
> DCREREADER_PROGRESS_BAR = 1
> -- for continuous scroll
> DSCROLL_MODE = 1
> DCREREADER_VIEW_MODE = "scroll"

This did not seem to have any effect. Do I need to delete some files (e.g. some cache of previously jit-compiled files) for the new defaults.lua to take effect? That might explain some confusion.

**Comment by noisebrain** [comment]
New evidence:  zoom-to-fit-content-height also cuts off the last line of text. The top of the letters are barely visible above the small progress bar.

And a new thought:  this pdf is an OCR'd scan.  Is the problem actually to do with how it detects the content size (rather than an issue with the screen size)?

**Comment by Frenzie** [comment]
@noisebrain 
>  "The view misses a couple lines at the bottom of the page", meaning a couple lines of text, not a couple lines of pixels. This is on a pdf that has approximatly 44 lines of text (hard to say exactly, it has some formulas on every page).

Could you provide a screenshot (slide diagonally from top left to bottom right)? What I mean looks like this. Note how in the bottom right corner, the page number is cut off by the status bar when it is enabled.

![screenshot - 02082015 - 06 39 24 pm](https://cloud.githubusercontent.com/assets/202757/6097540/efd4d806-afc1-11e4-9aca-42992fb88193.png)

> I would like to try Frenzie's suggestions. Are these what you intended?

Regarding the progress bar, yes, that's the one. It should result in a progress bar that displays all information at once and is also easier to toggle on/off, but of course it wouldn't have any effect on the issue.

For scroll mode, that may be the one, but it's easier to set defaults by long-pressing on the relevant GUI options. More important, that's where you set and experiment with per-document settings. It's to be found under the second option from the bottom left. There are cached files, but per-document settings are also independent from global settings.

> And a new thought: this pdf is an OCR'd scan. Is the problem actually to do with how it detects the content size (rather than an issue with the screen size)?

In my experience it errs on the side of caution, but I suppose it's possible.

**Comment by noisebrain** [comment]
Thank you. Toggling off the progress bar makes the bottom line of text visible in fit-content-height zoom. I found and set the scroll mode.  Looks usable now!

I'm attaching two screenshots showing the problem, with fit-content-height zoom.
An apology, this pdf is from a commercial academic publisher and is not freely available (only for pay, or through a university library). Posting portions of it might be a violation, so I blurred most of the content. But you can see the borders of the page and the problem.  

![koboss2](https://cloud.githubusercontent.com/assets/494277/6099224/e8c082cc-b057-11e4-827a-bfa6f0fd7105.png)
![koboss1](https://cloud.githubusercontent.com/assets/494277/6099227/f4a687da-b057-11e4-9801-880371312209.png)

**Comment by chrox** [comment]
From your last two screenshots the behavior of koreader is totally expected. In fit-to-content-height zoom mode there is no margin at the top and the bottom of the page, this is unlike the fit-to-content-width zoom mode which will add margin at the left and right of the page which can also be adjusted by the page margin options. This difference is not noticed because fit-to-content-height zoom mode is used much less often than fit-to-content-width zoom mode. For consistency we probably also need to add top and bottom margin.

**Comment by chrox** [comment]
I realize that by setting relatively large page margin the last line won't be covered by the status bar.

**Comment by yshui** [comment]
This problem still exists on Kindle Voyage with latest build

**Comment by chrox** [comment]
Please refer to this comment: https://github.com/koreader/koreader/issues/1422#issuecomment-75923898, the behavior is by design and expected.

**Comment by houqp** [comment]
@chrox shouldn't https://github.com/koreader/koreader/pull/2079 fix this issue?

**Comment by yshui** [comment]
@chrox But if this behavior is annoying, maybe the design could be changed a little bit?
