### ISSUE TITLE
File names in file browser do not respect RTL

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#1426]
I have some files where the filename is in Hebrew.
Using the latest Android release, in the file browser, those names are displayed backwards.

**Comment by pickx** [comment]
I have since bought a Kobo H2O and can confirm the same issue exists in Kobo port as well.

**Comment by chrox** [comment]
Yes, it currently does not support RTL scripts and may not support them in near future.

**Comment by seefood** [comment]
@pickx Hebrew filenames are the least of our problems, ePub doesn't render RTL either. any plans for this? Android should be able to provide APIs for this, I don't think it needs to be implemented from scratch...

**Comment by Frenzie** [comment]
@seefood Fwiw, RTL seems to work ok in our new experimental MuPDF EPUB rendering. (Tables obviously do not. ;-))

## MuPDF
![screenshot_2018-03-07_17-08-32](https://user-images.githubusercontent.com/202757/37103349-49c6f6a4-222a-11e8-8caf-996c851206bc.png)

## crengine
![screenshot_2018-03-07_17-08-56](https://user-images.githubusercontent.com/202757/37103350-49e7573c-222a-11e8-8166-7aefe3da65f0.png)

**Comment by seefood** [comment]
that's a very different result, is the rendering supposed to break like that?

Also a good test would really be to pick a page with mixed latin and Hebrew, like this: https://he.wikipedia.org/wiki/%D7%9E%D7%A2%D7%A8%D7%9B%D7%AA_%D7%94%D7%99%D7%97%D7%99%D7%93%D7%95%D7%AA_%D7%94%D7%91%D7%99%D7%A0%D7%9C%D7%90%D7%95%D7%9E%D7%99%D7%AA

**Comment by Frenzie** [comment]
If by "break" you mean that MuPDF doesn't support tables then yes. You can just try it yourself, but here are a couple of screens.

![screenshot_2018-03-08_13-10-08](https://user-images.githubusercontent.com/202757/37150491-28c4055c-22d2-11e8-8e67-302b3d0c91d6.png)
![screenshot_2018-03-08_13-10-20](https://user-images.githubusercontent.com/202757/37150492-28e31c30-22d2-11e8-8825-a0db139cf744.png)
![screenshot_2018-03-08_13-10-28](https://user-images.githubusercontent.com/202757/37150493-2901dc24-22d2-11e8-9b1b-c86ba1ce8af0.png)

**Comment by seefood** [comment]
bullets broken too, I guess? :-)

Thanks though, I'm happy with this, at least it's much more readable.

**Comment by Frenzie** [comment]
It looks like lists don't support RTL correctly but the difference is that tables aren't supported at all. ;-)

**Comment by mtlive** [comment]
Why don't you use a bidi library to show RTL documents correctly?
I tried displaying a converted string using Fribidi (only the result string, I didn't use the library on the device itself) and here is the result:
![plugin](https://user-images.githubusercontent.com/2260557/56641751-4116a080-668b-11e9-93e7-37d666be91a7.jpg)

**Comment by Frenzie** [comment]
Documents and UI are two very different beasts. Some notes about crengine bidi [here](https://github.com/koreader/crengine/issues/267).

If you can make the UI work with FriBiDi and the said to be nicer text shaping/mirroring from HB doesn't really matter, I'd say go for it. Or is it complementary with HB? It's all a matter of time and knowledge. :-)

There's also some inspiration here: https://github.com/luapower/fribidi

PS If you know any good resources, it'd be nice if you could add some links too.

**Comment by mtlive** [comment]
Unfortunately I don't have the knowledge/time for it now. May other devs consider fixing it.

**Comment by NiLuJe** [comment]
[raqm](https://github.com/HOST-Oman/libraqm) might be worth looking into, if someone were to want to tackle this ;).

**Comment by Frenzie** [comment]
Ah, so they are indeed complementary. If I understand correctly you add some raqm on top of FT and you don't deal with FriBiDi or HB directly?

**Comment by NiLuJe** [comment]
Yep, you basically only deal with raqm, and it handles the HB & FriBiDi shenanigans ;).

**Comment by Frenzie** [comment]
Okay, so at a quick glance using raqm should be quite simple. You can basically just follow the example in Lua except of C: http://host-oman.github.io/libraqm/raqm-Raqm.html

```lua
    local rq = raqm.raqm_create()
    raqm.raqm_set_text_utf8(rq, text, #text)
    raqm.raqm_destroy(rq)
```

However, it doesn't do line breaking yet, see `https://github.com/HOST-Oman/libraqm/pull/76`. It's not really clear to me how one would do that in RenderText, except by taking the lines that `RenderText:getSubTextByWidth()` comes up with and rerendering them.

**Comment by houqp** [comment]
raqm does seem very promising. It would be nice if we can replace some of our implementation with their code. that said, the layout function layouts the whole text, which is wasteful for getSubTextByWidth's usecase. We will have to contribute a function that does the layout but stops when a given width is reached.
