### ISSUE TITLE
Release 119 freezes on Boyue T62

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1428]
Hi

#119 freezes on Boyue T62. Basically the app never starts properly and all I get is blank screen. I deleted settings and the cache and I reinstalled it from scratch but did not solve it however previous release seems to work.

thanks

**Comment by gerroon** [comment]
I can confirm that r119 is very crashy on normal android devices as well. I went back to r118 and it works.

**Comment by chrox** [comment]
Seems https://github.com/koreader/android-luajit-launcher/commit/576b42e8aedd29af20415fd840f26623258caaa3 doesn't work on all Android devices.

**Comment by gerroon** [comment]
@chrox 
I can confirm that. I have couple Android devices (all arm7) and r119 is broken on them.

**Comment by chrox** [comment]
It's fixed in #1461. Close this now.
