### ISSUE TITLE
Gesture for frontlight control not working on Kobo Aura H2O

### ISSUE THREAD

**Issue by gegamit** [koreader/koreader#1431]
Hello
Is it possible to control the frontlight intensity on Kobo Aura H2O?
Thank you

**Comment by Frenzie** [comment]
You can find the frontlight and other settings under the gear icon.

**Comment by gegamit** [comment]
And is a gesture defined to control it?

**Comment by Frenzie** [comment]
That'd probably be part of #1008.

**Comment by thebombsauce** [comment]
I'll second this it'd be nice to get the left side screen swipe toggle from nickel onto koreader.

**Comment by gerroon** [comment]
Supposed frontlight gesture does not work on Glo, Aura or Android version.

**Comment by lightonflux** [comment]
On the Aura i can "scroll" up and down with two fingers to de-/increase the intensity.

**Comment by gegamit** [comment]
In my request #1084 (a switch gesture to turn on/off the frontlight), WS64 said that there was already a gesture to change the intensity of the frontlight (two finger swipe up or down). 
Is this meaning that this gesture has been disabled in the meantime? Is it possible to enable it again modifying some configuration file?

**Comment by NiLuJe** [comment]
Two fingers would imply multi-touch, which AFAIK is a no-go on the devices with an IR Grid (i.e., the H2O). Correct me if I'm wrong ;).

**Comment by Frenzie** [comment]
@NiLuJe Afaik you're wrong in the sense that the hardware supports it, but the kernel doesn't. :P

**Comment by gegamit** [comment]
But could a switch to turn the frontlight on/off (like the add bookmark on th right/upper corner, or the change visualization in the left/upper one) be feasible without waiting for a more complex and time consuming gesture programming interface?  For example on the middle point of the left side. Thank you very much!

**Comment by chrox** [comment]
It's not a generic use case so I would like to redirect this to a generic gesture manager proposed in #1008. Closing this now.
