### ISSUE TITLE
sdcv is printing "save to cache" message to stdout causing JSON.decode to fail

### ISSUE THREAD

**Issue by slow-mo** [koreader/koreader#1432]
Discussion about this bug on mobileread, posts:
http://www.mobileread.com/forums/showpost.php?p=3051624&postcount=739
http://www.mobileread.com/forums/showpost.php?p=3052124&postcount=746
http://www.mobileread.com/forums/showpost.php?p=3052166&postcount=749

When dealing for the first time with a dictionary, sdcv creates a cache file and prints a "save to cache" message to stdout. The string is passed to JSON.decode which fails to decode it as it probably expects the input to start with char `[`. 
Koreader then shows a dummy result table giving the user the impression that the term is not found in any dictionary. 
As the cache file has now been created, the warning should not be printed again and any further search in the dictionary should go smoothly. Nevertheless, I got randomly stuck in situations where sdcv continues giving that warning, blocking the search in *any* dictionary.
The solution would be to have sdcv print the message to stderr instead of stdout, which also seems fairer from a conceptual point of view.
Line 592 of sdcv/src/lib.cpp seems to be involved.

Logs showing the issue:

```
# lookup word: test
# stripped word: test
# result str: test save to cache data/dict/test.idx
[{
		"dict":	"test",
		"word":	"test",
		"definition":	"\ndictionary works"
	}]
# JSON data cannot be decoded frontend/JSON.lua:525: frontend/JSON.lua:240: can't parse JSON at char 1 of: save to cache data/dict/test.idx
[{
		"dict":	"test",
		"word":	"test",
		"definition":	"\ndictionary works"
	}]
# dummy result table: test {
	[1] = {
		["dict"] = "",
		["word"] = "test",
		["definition"] = "Nessuna definizione trovata."
	}
}
# showing quick lookup window
# show widget
# close widget
```

**Comment by chrox** [comment]
Good catch. The "save to cache" message definitely should not be in the stdout to confuse the JSON decoder. Could you send a patch to the koreader/sdcv repo?

**Comment by slow-mo** [comment]
I'm afraid I could do more harm than good. I'm no programmer, just an amateur who never stepped out of beginner stage. And I don't know c++.
In this case the solution seems so simple that actually even I could write a patch: just changing line 592 of sdcv/src/lib/lib.cpp from
```
		printf("save to cache %s\n", url.c_str());
```
to
```
		fprintf(stderr, "save to cache %s\n", url.c_str());
```

But I have no access to a linux install at the moment so I can't compile koreader. Before I waste everybody's time submitting a non-working patch, could somebody try it?

### How to reproduce the issue

* Remove every .oft file from koreader/data/dict/
* Launch koreader in debug mode and make a dictionary search, koreader should give no results 
* Close koreader and open the logfile. Search for a line starting with `# JSON data cannot be decoded frontend/JSON.lua:525: frontend/JSON.lua:240: can't parse JSON at char 1 of: save to cache`

Before testing the "patch" remember to remove every .oft file again, as once those files are created you may not encounter the issue again.

With the dictionary files attached to this post:
http://www.mobileread.com/forums/showpost.php?p=3051624&postcount=739
which consist of a single term (test), sdcv continues giving that string even after the first search.

**Comment by chrox** [comment]
I can reproduce this and your patch solves this problem perfectly. Thanks.

**Comment by slow-mo** [comment]
I'm happy to hear that! :)
