### ISSUE TITLE
Can't see .djv files

### ISSUE THREAD

**Issue by CyberAndrew** [koreader/koreader#1433]
Koreader doesn't see .djv files, .djvu only. But this is actually the same format.
(Version is v2014.11-93-gac77808)

**Comment by Markismus** [comment]
The dvju file extension is registered [here](https://github.com/koreader/koreader/blob/master/frontend/document/djvudocument.lua#L124). Just add a duplicate line and remove the 'u':
```lua
function DjvuDocument:register(registry)
registry:addProvider("djvu", "application/djvu", self)
registry:addProvider("djv", "application/djvu", self)
end
```

**Comment by CyberAndrew** [comment]
I'm not a programmer. I don't understand it and don't know how to use github. It was hard to me to even install koreader and tell about this bug. Just hope someone'll fix it in new release.

**Comment by Markismus** [comment]
Plug your Kobo into your PC.
Browse to .kobo\ koreader\frontend\document
Install Notepad++ (Google it)
Open djvudocument.lua in notepad++.
Change the lines in the text document. 
Save.
Unplug.
There you go. You just hacked your own device to work just the way you want it. It's fun isn't it?
