### ISSUE TITLE
Change start folder

### ISSUE THREAD

**Issue by CyberAndrew** [koreader/koreader#1434]
I want ability to change start folder. For example, I always keep my ebooks on SD card, so it's annoying every time go to ../ ; sd/ ; books/.

**Comment by gerroon** [comment]
+1

**Comment by Markismus** [comment]
It is currently implemented as a command line option. See [here](https://github.com/koreader/koreader/blob/master/reader.lua#L36).
So just tweak [this line in `koreader.sh`](https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L65) to start in your folder of preference.

**Comment by CyberAndrew** [comment]
Maybe you can make more user-friendly way to do it than command line? For example, when one in explorer mode, one can choose in menu "save this path as home-path" or "always start koreader from this path"
