### ISSUE TITLE
FR: Odd - Even - Multiple page  support for Semi -Auto cropping 

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1435]
Hi

The cropping feature is great in KR. It would be even more awesome if there was  support for separate semi auto crop areas for odd, even pages and pages with multiple pages in (ie 2 pages scanned as single page).

thanks

**Comment by chrox** [comment]
The current page cropping does support odd/even crop even though it does not say so. You just need to crop one page at an odd page number and crop another page at an even page number then the program should know well how to crop a new page according to the page number. 

As for multiple columns layout probably an additional zoom mode is a better solution like a FR proposed in #501.

**Comment by gerroon** [comment]
@chrox thanks for the follow up
