### ISSUE TITLE
Links between HTML files don't work

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1436]
Example files: http://zsh.sourceforge.net/Guide/zshguide_html.tar.gz

When you use the "follow link" feature koreader follows the links in the document. But if a links directs to ./otherfile.html#chapter4 it wont open the other file but instead open the menu. 

A function that follows links over document borders would be nice and time saving.

**Comment by chrox** [comment]
I don't think koreader supports cross-document links. Did you try compressing several HTML files into a html.zip file and open it with koreader?

**Comment by lightonflux** [comment]
Did that and it does not follows the links, but instead goes to the first page. And it only opens the first html file in the zip.

**Comment by chrox** [comment]
This is an upstream bug and duplicated to #1355. Please refer to #1355 for further progress. I'll close this now.
