### ISSUE TITLE
incorrect cover in FictionBook (FB2) in Kindle PW

### ISSUE THREAD

**Issue by itspec-ru** [koreader/koreader#1438]
I have Kindle Paperwhite. FW 5.4.4.2
In new releases of koreader a book cover of FB2 is drawn not correctly
Koreader 2014.04 works correctly. The problem arose since 2014.11.

**Comment by lightonflux** [comment]
> In new releases of koreader a book cover of FB2 is drawn not correctly

Please specify how it looks and/or make a photo.

**Comment by itspec-ru** [comment]
1. cover of FB2 http://s008.radikal.ru/i305/1503/63/5b6328a2b83e.jpg
2. cover of EPUB http://s018.radikal.ru/i507/1503/9a/7fa048a8c17e.jpg

book FB2 https://yadi.sk/d/3pV9BhmuewzQy
book EPUB https://yadi.sk/i/hpj6y2Z3ewzWZ

Other pictures of the books in any formats look correctly. The problem only in cover of FB2

**Comment by NiLuJe** [comment]
Didn't we have similar issues with (some? all?) gif images somewhere?

**Comment by itspec-ru** [comment]
I have not problem with other images in books. ONLY IN COVER OF FB2.
koreader 2014.04 works correctly

**Comment by chrox** [comment]
The cover image is JPEG encoded but crengine seems cannot handle it properly.

**Comment by itspec-ru** [comment]
I'm build koreader from current source on linux, but with old crengine (commit 1b3afaafb9a9352764d59f63b45c539980e3910e, May 9 2014).
The problem still remained. I think the problem is not in the crengine.
Again, all images in the ebooks in all formats (fb2, epub, pdf) looks correct except for the cover in fb2.

**Comment by mergen3107** [comment]
> crengine seems cannot handle it properly.
Is this issue specific to crengine on Kindle? For example, on my Nook Simple Touch (Android 2.1) I use Cool Reader based on crengine and it shows all covers and images well.

**Comment by itspec-ru** [comment]
KOReader uses own crengene https://github.com/koreader/crengine. Which is different from Cool Reader' crengine http://sourceforge.net/projects/crengine.
This bug is platform independent. I'm build and run KOReader on linux. And result same as on Kindle PW

**Comment by mergen3107** [comment]
ok

**Comment by houqp** [comment]
This might have something to do with our libjpeg build.

**Comment by itspec-ru** [comment]
But all other images in books look correctly except for the cover in fb2

**Comment by houqp** [comment]
Is it broken for all the fb2s?

**Comment by itspec-ru** [comment]
Yes

**Comment by itspec-ru** [comment]
This bug was fixed in crengine https://github.com/koreader/crengine/commit/2eb08ee43ea52f53e543b7a0091505c9f3959271
thanks to frankyifei.
I'm built koreader with updated crengine on linux. Covers on FB2 looks perfect

**Comment by itspec-ru** [comment]
Fixed in koreader https://github.com/koreader/koreader/commit/7a1d6ccae822a6fe8d185ff36f3263fc156fc91d

**Comment by itspec-ru** [comment]
Не стал дожидаться релиза с исправленным багом, собрал из исходников сам (исходники от 26 октября).
Работает. Собрал только для kindle. Обложки в FB2 отображаются. Каких-либо проблем замечено не было.
Кому нужно, качайте архив koreader-kindle-arm-linux-gnueabi-v2015.11-658-g683b038.zip здесь
https://yadi.sk/d/RtKszxtsxoGZA
