### ISSUE TITLE
Custom gestures

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#1439]
This is a cross-post with the mobileread forum. 

Since things are really quiet with the koreader development (no major problems with the reader) I wanted to ask if its possible to add a custom gesture.

 This is what I mean:

 For a few months now I read I lot of pdfs that have code snippets in them.
 Since most of them are for python, the indentation is important, so I have to turn re-flow off.
 But after the code part, the re-flow is so much better than the original layout, that I have to turn it back on.
 For that, I need 4 taps before I can see the text with the new layout.
 This can happen sometimes in almost every page.

 So, back to the question.

 Is it possible to assign a 'tap zone' for a command to toggle the re-flow on-off?
 A mechanism for that can be used to change other parameters of the layout also.

 Thanks for your time anyway ...

**Comment by chrox** [comment]
You can tap the top-left corner of the screen to temporarily disable reflowing.

**Comment by embryo10** [comment]
I knew that, but I always thought that what you had was an overview of the page.
Just tried now to use the crop function and it worked!
Its great!
... hhmm!
... but the problem is that every time I use it, I have to put the cropping on again.
It doesn't remember it.
So that takes me back to 4 taps again... :o)
Oh, well ..

**Comment by chrox** [comment]
If your device supports multi-touch you can use "horizontal spread" gesture on the overview page to zoom   to fit content width so that it's reduced to two gestures. I agree the zoom mode in "fast browsering" mode should be persistent, and I will fix this later.

**Comment by embryo10** [comment]
I have a Kobo Glo, so AFAIK koreader does not recognize it as a multi-touch device (although in Android it is).
Thank you for your help.

**Comment by Markismus** [comment]
You can hack your Glo for multitouch. Info is [here](http://www.mobileread.com/forums/showthread.php?t=232431&highlight=multitouch). The work was done for older firmwares, though. I don't know whether they updated it.

**Comment by embryo10** [comment]
@Markismus Thank you.
I have seen that, but I'm not sure it will work on my system.
I have Nickel with KSM and dual boot Android.
I think there was some compatibility problems between some of them and multi-touch.
Don't remember.
I'm also still in 3.8 firmware (not much of a Nickel user... ;o) so the KoboMultitouch350a-Cecell3000-v002 version will work, but I'm not surs about koreader.
Does here http://www.mobileread.com/forums/showpost.php?p=2906793&postcount=152 says  that in koreader is single touch?
When I find some free time I'll upgrade Nickel and try it, just for the heck of it!

**Comment by embryo10** [comment]
@Markismus 
Well, I checked it and the problem is that I loose the dual booting option.
Oh well...
I'll have to wait for chrox to fix it.

**Comment by embryo10** [comment]
OK. The page crop is remembered now.
But the scroll mode is not.
And there is something weird happening when you change from one view to the other.
There is a jump backwards in the document?
This is not crucial, but I think the scroll mode is, because if you want to fix it you get more taps than the original four that I was trying to avoid.

**Comment by chrox** [comment]
It's relatively easy to let the flipping mode to remember scroll mode. You just need to load a variable `flipping_scroll_mode` when reading settings and use that variable when entering flipping mode and update the variable when exiting flipping mode and finally save the variable when saving settings. Just like what I did in this patch ea76d91 to support the zoom mode.

But I'm afraid I have no free time to fix this in the following few weeks. Feel free to hack for yourself, probably you need four lines of code to fix it. Please tell me if you have any difficulty to do this.

**Comment by embryo10** [comment]
Well, since I never wrote code in github and also never coded in lua maybe I'll skip it.I know how to code in python (beginner), I can understand what have to be done and I know its easy, but I don't know the syntax or the github procedure so I guess I'll have to wait.
Its not a big deal. Just some more tapping.Everything else is just great!
Thank you anyway... 


     On Monday, March 23, 2015 11:27 AM, Huang Xin <notifications@github.com> wrote:
   

 It's relatively easy to let the flipping mode to remember scroll mode. You just need to load a variable flipping_scroll_mode when reading settings and use that variable when entering flipping mode and update the variable when exiting flipping mode and finally save the variable when saving settings. Just like what I did in this patch ea76d91 to support the zoom mode.But I'm afraid I have no free time to fix this in the following few weeks. Feel free to hack for yourself, probably you need four lines of code to fix it. Please tell me if you have any difficulty to do this.—

**Comment by chrox** [comment]
Well, it's never late to learn. And I'm sure you will benefit from it sooner or later.

Btw, I never heard of Lua neither before I joined this project.

**Comment by Frenzie** [comment]
@embryo10 Lua is pretty much just as easy as Python. Git(hub) is the hard(er) part. :)

**Comment by embryo10** [comment]
@Frenzie 
This is what frightens me (git).
I'm using PyCharm as IDE and it has Git support, but I always postpone to dig in ...
Thats why I have to keep my programs local.
Checking in the PyCharm's settings I found that there is a Lua plugin that I can install, but the first obstacle is the git understanding.
Any good tutorials? (for when there is some free time ...)
or is it totally different depending on what IDE you use (or just web)?

**Comment by Frenzie** [comment]
The basics are still quite simple. First you fork it on Github. Then you go to your fork and you type

```
git clone URL_HERE
```

You make your changes, type

```
git commit CHANGED_FILE
```

And when you're ready to share it with the world:

```
git push
```

Then you can create a pull request on Github.

Let's see, Github has [their help](https://help.github.com/articles/set-up-git/) and I'm sure there are plenty of tutorials.

**Comment by embryo10** [comment]
A plethora of things to read ...
... in a few years I might learn some of them.
I was just reading about the differences between python and lua.
Too many fronts!

**Comment by hwhw** [comment]
As for learning - I suggest to learn Lua anew, not by the differences to something you know. Lua has a really small language core, it's easy to get going.

For Git, there are two ways to approach it. Either by starting with the fundamentals, i.e.: what is an object, what is a tree, what is a blob, what is a commit. The other way is by starting along the lines @Frenzie outlined above: The "how-do-I-..." approach. That's also the way I started, but in hindsight, that wasn't a good idea. I didn't really get Git until I started with the first approach. While it takes a few hours to be actually productive with Git, the memory footprint in your brain is much smaller, since when you know the fundamentals, you can extrapolate anything from that.

Both things a pretty nice knowledge to have. Git, because it's omnipresent nowadays. Lua - well, outside the gaming industry, it is still a small player. But it certainly has its uses. LuaJIT is fascinating technology and brought me to a better understanding of compiler technology. Lua itself is a nice thought experiment due to its flexibility and small core. A bit funny here and there (1-based arrays, implicit globals), but very nice indeed. You can realize many programming paradigms in Lua.

But right, keeping focused on the work at hand is a good thing to do, too. Especially if it earns your living. In a way, that's why I'll still be quite busy with exam preparation for the next 4-5 months and will refrain from focusing on other things - unfortunately, also Koreader.
