### ISSUE TITLE
kpw2:5.6.1.0.2 gets stuck on reading PDF screen frequently

### ISSUE THREAD

**Issue by mars00772** [koreader/koreader#1440]
kpw2:5.6.1.0.2 with kpvbooklet gets stuck on reading PDF screen frequently.
Cause it's been jailbreaked before kpw2 fw updated accidentally ,I used Update_jailbreak_bridge_1.14.N_install.bin to rejailbreak and then use MRinstaller to install kpvbooklet and koreader-nightly-20150212.
Now he gets stuck on reading PDF screen frequently,any logs can help to locate fault sources ?

**Comment by mars00772** [comment]
got this：warning: expected name after CMapName in cmap in crash.log

**Comment by chrox** [comment]
Never encountered this on kpw1. Some other kpw2 users also reported that turning on/off the buttom minibar may cause koreader frozen and reboot kindle native framework. Could you reproduce this behavior by tapping on the buttom bar?

I suspect there are still some issues on regional screen refresh on kpw2.
