### ISSUE TITLE
The last page is not saved when Pocketbook auto power off.

### ISSUE THREAD

**Issue by druss67** [koreader/koreader#1445]
I have noticed a strange behaviour.
 
If my device poweroff automatically, the last page is not saved and the last bookmark too. it is the same if I poweroff with the button.
 The only way to save all, it is to exit Koreader with the home button in the top menu.
 
It is a little bit annoying, do you have notice this on your PB ? 

Firmware : W626.4.4.1151 date: 20141024_140004
 Koreader v2014.11-93-gac77808
 
Best regards,
 Druss

**Comment by chrox** [comment]
It should be fixed in #1448.

**Comment by druss67** [comment]
Ok, perfect...

**Comment by chrox** [comment]
But you need to let the device go to suspend first so that it can be notified to save settings to a file. But if you directly power off the device the program gets nothing notified and is killed by the system so the settings are still not saved.

**Comment by druss67** [comment]
I understand, but on my kindle 4NT for exemple when I poweroff directly, the page is still saved. It is also the case with pocketbook with coolreader, I think the position in the book is saved just after turn the page.

**Comment by chrox** [comment]
If you still have this problem on the next nightly build, you may need to change this setting to 
`DAUTO_SAVE_PAGING_COUNT = 3` in the `koreader/defaults.lua` file which will save all settings to file every 3 page turns.
