### ISSUE TITLE
Percentage progression in minibar

### ISSUE THREAD

**Issue by druss67** [koreader/koreader#1446]
Is it possible to add in the minibar the reading percentage of the book ? Something like this...
B:68% | 23:20 | 289 / 669 | => 2 | R:43,2%

This feature was in the CR app, and it was nice. 
The only feature missing for me, just "nice to have".

Best regards,
Druss

**Comment by chrox** [comment]
So what does this 'R' mean in the "R:43,2%" string? I'm afraid it could sometimes be confused with the battery percentage indicator.

**Comment by druss67** [comment]
R = Reading. 
This setting could be set in defaults.lua like the other setting for the minibar.
So if this is confusing this is easily removable. But I use it on another reader and this nice to have.

**Comment by chrox** [comment]
That sounds reasonable. And I intend to move the minibar options to the top menus and add the progress percentage option as you requested.

**Comment by druss67** [comment]
Ok greats ! thanks to you.

**Comment by chrox** [comment]
It will be implemented in #1448 and looks like this:

![screenshot from 2015-03-12 14 37 51](https://cloud.githubusercontent.com/assets/751535/6613327/d88ce41e-c8c5-11e4-8c4a-c2b136692cd6.png)

![screenshot from 2015-03-12 14 37 55](https://cloud.githubusercontent.com/assets/751535/6613328/dcd8b8ea-c8c5-11e4-998d-15ecb3e09df3.png)

![screenshot from 2015-03-12 14 38 03](https://cloud.githubusercontent.com/assets/751535/6613330/e33fdcfe-c8c5-11e4-989e-b18f07643de1.png)

**Comment by Frenzie** [comment]
I think that should be "pages left in this chapter". Left pages and right pages are something you ideally don't have on your ereader. :)

**Comment by chrox** [comment]
Yeah, got that. :)
