### ISSUE TITLE
the latest version crashes on Android

### ISSUE THREAD

**Issue by Juddd** [koreader/koreader#1447]
when I update to "koreader-nightly-20150306",my koreader of kpw2 and android don't work any more.my android will become a black screen.it is worse,my kindle'll restart.But they are can be normal operation before this.Help me,please.I have some PDF to read now.

**Comment by chrox** [comment]
This version is tested on Meizu MX4 and PocketBook 840 and Kindle Paperwhite 1. Any crash log on your kpw2? 

Easy way is to re-install an older version.

**Comment by Juddd** [comment]
where can i get the crash log?

**Comment by chrox** [comment]
After a reboot/crash you can always find a `crash.log` file in the koreader directory of your Kindle. It's really helpful for developers to quickly locate the problem with the crash log file.

**Comment by Juddd** [comment]
i'm try to find the crash.log as you say,but it is empty.T_T.

**Comment by Juddd** [comment]
so i have to re-install the “koreader-nightly-20150212”，Then,everthing is normal.

**Comment by gerroon** [comment]
I have the same problem. Last two releases are borked on Android. I am using Android 4.4.4 CyanogenMod11

**Comment by Wacek** [comment]
Agree - the program regurarly hangs on my JellyBean tablet  - it does not matter if its stable or nightly to the point that have I decided to stop using it and switched to EbookDroid instead. I'm unable to root this device and there probably is not any alternative ROM available either. So I'm stick with 4.2 thus unable to test whether its simply a problem with the device itself, or just too old version of Android (or both). But since I see more people coming with Android hangup reports, then maybe there is something to it

**Comment by gerroon** [comment]
@Wacek 

I have never been able to use KR on Android properly it is always crashy, sometimes it crashes when I open a pdf sometimes it crashes when I am paging through the directories. I have not been able to really finish a book with it so like you I always give up an use something else.

On the other it hand it is very very stable on my Glo. Something about the way it is packaged for Android is fishy. But I am not a coder so no idea.

**Comment by gerroon** [comment]
@Wacek and @Juddd 

Can you guys tell us what you have on your system under this bug? Chrox is trying to find the memory issues. 

Do you have Xprivacy installed for example?

https://github.com/koreader/koreader/issues/1456

**Comment by irregularisnotrandom** [comment]
Sorry to bump this thread.

I have a NookHD+ and i have no exposed or xprivacy installed and Koreader still crashes. I do not remember the version but ones from last year were working perfectly fine on it. Now no recent versions work.

**Comment by Markismus** [comment]
@irregularisnotrandom Please report your find in issue #673. Could you also give the android firmware version on your NookHD+?
