### ISSUE TITLE
about the dictionary of koreader of android device.

### ISSUE THREAD

**Issue by Juddd** [koreader/koreader#1449]
i have a confusion for a long time about the dictionary of koreader of android device.I look up my document-manage but i can find the directory of "koreader".even so,how can i put my dict-data in my device?

**Comment by Markismus** [comment]
It's impossible on non-rooted devices. See the discussion in [issue 1420](https://github.com/koreader/koreader/issues/1420#issuecomment-76909282)

**Comment by Juddd** [comment]
i have already readed your link,but i'm a programme rookie.so i'm sorry for that i cannot help you.

**Comment by Markismus** [comment]
Alright, it'll get done in time. I just don't have time right now.

As this is a duplicate issue of #622, I'll close this now.
