### ISSUE TITLE
crash on kpw2 version 5.6.1.0.6

### ISSUE THREAD

**Issue by fromMars** [koreader/koreader#1450]
koreader freezes occanionally, and always the crash.log is empty, but this time I got the crash.log.
Can anybody figure out what this means?

koreader version: koreader-kindle-arm-linux-gnueabi-v2014.11-107-g5615948
crash.log:
```
warning: not building glyph bbox table for font 'LGKLIL+SimHei' with 22021 glyphs
warning: not building glyph bbox table for font 'LGKLLP+SimSun' with 22141 glyphs
[31m[E 2015/03/10 08:24:03] [ioloop.lua] Uncaught error in callback: frontend/ui/widget/imagewidget.lua:0: attempt to index a nil value[0m
stack traceback:
	common/turbo/ioloop.lua:492: in function '__index'
	frontend/ui/widget/imagewidget.lua: in function '_loadfile'
	frontend/ui/widget/imagewidget.lua:77: in function '_render'
	frontend/ui/widget/imagewidget.lua:95: in function 'getSize'
	frontend/ui/widget/container/centercontainer.lua:9: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:51: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:62: in function 'paintTo'
	frontend/ui/widget/horizontalgroup.lua:35: in function 'paintTo'
	frontend/ui/widget/container/bottomcontainer.lua:16: in function 'paintTo'
	frontend/ui/widget/overlapgroup.lua:46: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:51: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:62: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:36: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:51: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:62: in function 'paintTo'
	frontend/ui/uimanager.lua:403: in function '_repaint'
	frontend/ui/uimanager.lua:460: in function 'handleInput'
	frontend/ui/uimanager.lua:502: in function <frontend/ui/uimanager.lua:502>
	[C]: in function 'xpcall'
	common/turbo/ioloop.lua:496: in function <common/turbo/ioloop.lua:495>
```

**Comment by chrox** [comment]
It seems like the device runs out of memory. Did you try with restarting your device manually to see if the problem still exists?

**Comment by fromMars** [comment]
These days it worked just ok, no crash, no freezing any more. Maybe some of the files caused freezing, I don't know,  or maybe a bug caused this.

**Comment by bananallm** [comment]
thank you，my kindle update to 5.6.1.0.4,

在 2015-03-13 18:40:56，"Zhang Mingbo" <notifications@github.com> 写道：


These days it worked just ok, no crash, no freezing any more. Maybe some of the files caused freezing, I don't know, or maybe a bug caused this.

**Comment by lightevilaster** [comment]
I am also the owner of kpw 2 with the same firmware. My kindle totally freezes if I tap the screen at the very bottom. The device needs reboot after that. Happens with all the files.I use the last stable release (also happens with nightly builds). Crash logs are emppty Could anyone else confirm this issue? Are there any solutions yet?

**Comment by chrox** [comment]
Duplicated to #1440. Close this now.
