### ISSUE TITLE
"Open previous file" button in Reader View for basic multitasking (AltTab-like behavior) 

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#1451]
I use KOReader daily to do my university assignments and it is indeed fantastic!

This use case requires constant switching between two separate files, for example: a homework assignment file and a lecture notes file or a textbook. I do this sort of momentary file switching about 20 times a day.

It takes a while and can get quite tedious, especially if both files are not in the same folder.

By adding an "Open previously-read file" button right in the Reader View I can skip the file browser altogether and save myself hundreds of clicks.

**Comment by chrox** [comment]
There is a "History" menu in the top reader menus from which you can open recently closed documents directly.

![screenshot from 2015-03-12 09 07 49](https://cloud.githubusercontent.com/assets/751535/6610266/c4ba3456-c897-11e4-991e-d8f48fbecec7.png)

![screenshot from 2015-03-12 09 07 54](https://cloud.githubusercontent.com/assets/751535/6610269/caa2c1bc-c897-11e4-8280-73914725710e.png)

**Comment by pickx** [comment]
Awesome. I just assumed History is "Version History" aka changelog based on the two options under it. This feature works exactly as I wanted. Thank you so much!
