### ISSUE TITLE
Update brakes koreader

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1452]
./luajit: symbol lookup error: /usr/lib/libssl.so: undefined symbol: EVP_idea_cbc

After the update to v2014.11-132-g2aebba9 koreader crashes immediately on my kobo aura and is rendered useless. :(

 I could update my firmware to 3.13 if that helps.

**Comment by chrox** [comment]
Could you post the whole crash log here? From this release on, koreader should not use system provided libssl but use the bundled one in the koreader package.

**Comment by lightonflux** [comment]
That is the whole content of the crash.log, just this one line.

**Comment by thebombsauce** [comment]
Having this same crash on my kobo after updating.

**Comment by chrox** [comment]
For some reason [a patch](https://github.com/koreader/koreader-base/blob/master/turbo.patch) is not applied when building the release and it will affect all Kobo devices because Kobo system provides an out-dated libssl. I will fix this soon.
