### ISSUE TITLE
README_kobo.txt

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1457]
Hi the README_kobo.txt needs an update, but i could not find it in the repo. Where is it?

The following sentence is not uptodate with KSM 7:

>  Extract the koreader folder of the zip into the ".kobo" directory (both KoboRoot.tgz and the koreader.png file are only needed for the older installation based on Filemonitor. See below.). 

KSM by default (new install)  creates an .adds folder. So when you flash new firmware all your "extended" software stays where it is. Like koreader. So you can use the old path, or if the user does a new install .adds.

**Comment by chrox** [comment]
The `README_kobo.txt` is placed [here](https://github.com/koreader/koreader/tree/master/platform/kobo/fmon) and when building a release it's renamed from `README.txt` to `README_kobo.txt` [here](https://github.com/koreader/koreader/blob/master/Makefile#L166). Please feel free to update the instructions accordingly and send a pull request here. Thanks.
