### ISSUE TITLE
progress sync freeze on register 

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1458]
So I opened progress sync and just pressed register without any other input like mail or password.

No koreader is unusable, maybe a freeze or just a loop. 

Maybe the dialogue is lacking a check for nil input?

**Comment by houqp** [comment]
which version and what device are you using?

**Comment by lightonflux** [comment]
Kobo Aura with koreader-nightly-20150318

And the same with v2014.11-151-g34377cd. It just shows the message "Registering. Please wait..." and nothing happens. And it is not possible to abort the process. So koreader is locked.

**Comment by lightonflux** [comment]
An abort button would be nice.

**Comment by chrox** [comment]
Sorry I have no Kobo devices and I cannot reproduce this behavior on all my koreader devices. Probably a detail log of koreader on Kobo when registering would be better.

**Comment by lightonflux** [comment]
Where can i find the log? Or how can i produce it?
