### ISSUE TITLE
sometimes tap on the upper right corner doesn't create bookmark

### ISSUE THREAD

**Issue by druss67** [koreader/koreader#1472]
Hi,

sometimes i can't create a bookmark. I try to touch the right top corner of my PocketBook 626, but it seems that the touchscreen can't respond. Contrariwise if I touch the center of th top the menu appears, strange isn't it...

W626.5.5.720

**Comment by chrox** [comment]
I cannot reproduce this on my PocketBook 840 and Android? Could you check in the "Bookmark" menu to see if the bookmark is actually made?

**Comment by druss67** [comment]
No, the bookmark is not created. It is like a non responsive behaviour of the touch screen. Do you know if I can see a bad behaviour of the screen in a log file ?

**Comment by chrox** [comment]
Yes if your run koreader in an SSH session in debug mode it will log each touch gesture.

**Comment by chrox** [comment]
Seems unreproducible. Please reopen this if you still have this problem.
