### ISSUE TITLE
'Add new OPDS catalog' freezes KPW2 4GB Serial 9017

### ISSUE THREAD

**Issue by shapez0r** [koreader/koreader#1474]
Hi!
In all builds I've tried (couple of nightlies, last stable) when I try to add an OPDS catalog the reader freezes my Kindle Paperwhite 2 4GB.
Is it expected and not yet functioning?

Thanks

**Comment by chrox** [comment]
Could you run koreader in debug mode in an SSH session and post the log here? There seems not such problem on kpw1.
