### ISSUE TITLE
Support custom server URL for Calibre Wireless Connection

### ISSUE THREAD

**Issue by mobamoba** [koreader/koreader#1475]
I'm using the most recent nightly of Koreader on my Kobo Glo (via KSM) and have noticed two issues with the Calibre Wireless connection.

First, there's no place (that I was able to see) where I can entire a URL for my Calibre server, which is accessible over the internet. In Koreader's version, the wireless connection autodetects, meaning it only works over a LAN. In contrast, Calibre Companion's version (I dual boot Android on my Kobo so I can compare) allows you to enter a URL so you can connect from anywhere assuming you've setup Calibre and your network properly.

Second, there's something off with the way Koreader and Calibre are communicating. Despite the fact that I connect Koreader wirelessly and transfer my books using Calibre, Calibre never sees the books on reconnect. In fact, Calibre sees a completely empty device; I can then transfer all the books back over again (where they just get overwritten on my Kobo since they're actually already there) and Calibre will see them for the remainder of the session. But, on disconnect and reconnect, Calibre once again fails to find any books on the device. Again, Calibre Companion doesn't have this problem when connecting wirelessly, which is why I'm assuming the bug is something with Koreader. I store my books in /mnt/onboard if that makes a difference. Thanks.

**Comment by chrox** [comment]
The calibre wireless connection plugin only implements a subset of Calibre Companion funtions. Both of the features you mentioned above are not implemented yet.

**Comment by akamaus** [comment]
Does anybody have a plan how to implement it? Looks like calibre expects some kind of book database on device to be available. And AFAIK koreader just has a file browser to locate and open book files.

**Comment by KenMaltby** [comment]
The WiKi can be helpful. https://github.com/koreader/koreader/wiki/Calibre-wireless-connection  The thing that might not be intuitive is that the "Connect" menu item is in the Reader Menu, not in the File Manager Menu, where I would expect to find it.  (This means you have to open some unrelated book, to add files from calibre to your device.)

**Comment by protist** [comment]
I'm struggling to set up Calibre wireless connection, presumably because I don't broadcast avahi on my computer. It'd be useful if I could specify my computer's static internal IP to koreader instead.

**Comment by protist** [comment]
Just to confirm, this works well for me! Thank you!
