### ISSUE TITLE
Chinese Dictionary issue. Unable to search words in dictionary consisting of two and more characters.

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#1476]
Hi there,

I am using Kobo H2O, recently I have started to read a Chinese book and installed Chinese dictionary and found out that Koreader unable to search Chinese words that consisting of two and more characters that makes dictionary useless. Is there any workarounds to fix it? 

Bellow I provide the links for the book and dictionary I use (only for reference):

https://mega.co.nz/#!e4EwiJJI!JmUk5izdN7vAx-VoQjKKr14tl8Led0yZpGk2HegrNTc

https://mega.co.nz/#!211VBbxL!xJPbIn4fSKC4rb0JJCM6iych6Vy9ZibNBPBIW6w-VQs

Tell me if you will have any problems with downloading files from this service.

Thank you

**Comment by Sopheus** [comment]
To make it more interactive I have made a video to show the issue.

https://mega.co.nz/#!7xlTibZQ!5D7DEvS1YLtD__iGbXNlBc87bCv8qUnWUFDePKBgVNM

As you can see from the video, when I choose one character (么 for example) dictionary search works just fine, but when I try to select a word that consists of two characters (for ex. 时候 - which means "time") nothing happens and search dictionary function does not work.

To prove that it is possible to search words that consist of two character I choose simple sentence (放心 - which means "relax"). Overall, searching for Chinese words is a big pain, but the main issue is stated above. 

As a Chinese learner I do really hope there is a fix to this.

Thanks in advance

**Comment by chrox** [comment]
Yes, it's known limitation of no support of dictionary lookup on Chinese phrases. And it will be fixed after #975 is implemented.

**Comment by Sopheus** [comment]
Nice to know it could be fixed, question is when :)

**Comment by chrox** [comment]
I don't know neither.

**Comment by Sopheus** [comment]
Any news on the matter? Does it possible to search words in dictionary consisting of two and more characters now? 

Thanks in advance
