### ISSUE TITLE
Attempt to log into Evernote freezes the device

### ISSUE THREAD

**Issue by LucenaWoods** [koreader/koreader#1477]
1) Just as the title says. Latest stable version, every single time. Wi fi on. 

2) Plus, with the latest stable release, if you leave koreader with an open document (as opposed to leaving it from the file drive menu), when you open koreader back via KUAL's Open the last document, it opens the last page of the document you had viewed, but freezes. Happens every time, with different documents. 

Doesn't happen when you open koreader via KUAL by clicking on "open file drive ASAP" button

Downgrading to the latest stable release solved it. (but still can't login to evernote)

**Comment by LiuChuan92** [comment]
Same problem occured using kpvbooklet to start koreader.

**Comment by chrox** [comment]
Could you try with the nightly builds? There is a bug in Evernote Authentication in the stable release which is fixed in the latest nightly builds. And is your device kpw2 with firmware 5.6.x?

**Comment by boplennon** [comment]
I tried many nightly and stable builds and experienced many annoying bugs in my kpw2.
1. It freezes when when I use kpv booklet to open books. It worked normally until recently builds.
2. Sometime it also freezes when I touch mini bar.
3. Evernote function either causes freezeing or oAuth error
 Build v2014.04-929-g197c2f5 is the most stable though Evernote didnt work

**Comment by chrox** [comment]
There are emergent issues specific on Kindle Paperwhite 2 such as #1474 and #1440 and other forum threads. And all these issues are about freezing on kpw2 even with simple interaction like tapping the minibar.
