### ISSUE TITLE
Opening big epubs on PB(626) takes a loooooooooooong time

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#1478]
Really big books, around 10MB or bigger with no or just a few pictures, take a very long time to open.
I measured up to 20 minutes, that includes a few times tapping the screen or buttons to prevent the device going to sleep.
Same book opens on Kobo in about 20-30 seconds.
On MobileRead @chrox wrote already to my "too slow" comment: "On the contrary, I have a theory that Koreader on PocketBook is a little too fast and it triggers a bug in Koreader to prevent screen refresh after the splash."
Is that bug identified/solved by now?

**Comment by hwhw** [comment]
I don't think so - for the "identified" part, that is. It might have been "solved" somehow. That would need new testing. I don't own the device in question, so I wouldn't know how to even start. It would be interesting what exactly the device does during those 20 minutes.

**Comment by WS64** [comment]
At least the 0401 version did not solve it.
Is there anything I can do to find out what the PB is doing during the opening time?

**Comment by hwhw** [comment]
I'm not sure what the device offers (SSH access?). I guess profiling, strace and/or gdb and looking where it is spending its time would be the way to go. Plus enabling debug output and having a look at it while running Koreader, so to get an idea what the last things were before it fell into that trap.

**Comment by chrox** [comment]
On my PocketBook the "opening some file..." message sometimes won't get refreshed at all which may give users an impression that koreader is opening the document forever but actually the document is already rendered beneath the screen. There is an SSH tool developped by @rkomar for PocketBook [here](http://www.mobileread.com/forums/showthread.php?t=159636) with which you can run koreader script to verify this.

**Comment by WS64** [comment]
I'm afraid your "too fast" really refers just to that message not disappearing part, but that is not the main problem, although that happens here too.
But this is not the case here (although this happens too). At first i thought these big documents cannot be opened at all, because after clicking a few times nothing happened at all, the screen just stayed blank. After a few minutes I closed the application. until I finally really tried it and clicked a button and touched the screen every 3 or 5 minutes. And after 20 minutes or so the book finally opened. And it was not slow at all.
I am really afraid that PB is too slow here, not too fast.
It did not help to click "faster", like every 30 seconds or so.
Can I send one of the books in question to you, chrox, and you try if you can reproduce this problem? If yes I will send you an email to your gmail...

**Comment by chrox** [comment]
So in a ssh session on your pocketBook device. You can run koreader this way:
```
cd /mnt/ext1/applications/koreader
strace ./reader.lua
```
If the output ends like this:
```
cacheflush(0x4f2720, 0x4f2808, 0, 0xe8, 0x4025d370) = 0
cacheflush(0x4f2a94, 0x4f2a98, 0, 0x4f2a98, 0x4025d370) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f2700, 0x4f2720, 0, 0x20, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4ff088, 0x4ff08c, 0, 0x4ff6a4, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f26a0, 0x4f2700, 0, 0x60, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4ff4f8, 0x4ff4fc, 0, 0x4ff6a4, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f2480, 0x4f26a0, 0, 0x220, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4ff510, 0x4ff514, 0, 0x4ff6a4, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f21c0, 0x4f2480, 0, 0x2c0, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4feb08, 0x4feb44, 0, 0x4fedd8, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f20ec, 0x4f21c0, 0, 0xd4, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4fda0c, 0x4fda10, 0, 0x4fda34, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f1e7c, 0x4f20ec, 0, 0x26c, 0x4025d370) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f1c5c, 0x4f1e7c, 0, 0x220, 0x4025d370) = 0
mprotect(0x520000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x522ec4, 0x52305c, 0, 0x5230ac, 0x4025d370) = 0
mprotect(0x520000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f1b2c, 0x4f1c5c, 0, 0x130, 0x4025d370) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f17ac, 0x4f1b2c, 0, 0x380, 0x4025d370) = 0
mprotect(0x500000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x5004c4, 0x500504, 0, 0x500840, 0x4025d370) = 0
mprotect(0x500000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4f115c, 0x4f17ac, 0, 0x650, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_WRITE) = 0
cacheflush(0x4feaec, 0x4feaf0, 0, 0x4fedd8, 0x4025d370) = 0
mprotect(0x4f8000, 32768, PROT_READ|PROT_EXEC) = 0
mprotect(0x4f0000, 32768, PROT_READ|PROT_EXEC) = 0
ioctl(3, 0x4040462e, 0x40d87ac8)        = 0
gettimeofday({1428412214, 759721}, NULL) = 0
select(5, [4], NULL, NULL, NULL
```
It should be normal.

**Comment by chrox** [comment]
I'm interested to test that on my PB840. Thanks for sharing it.

**Comment by WS64** [comment]
Email is sent!

**Comment by rkomar** [comment]
The shell in the SSH session is very basic, and unusable for more complex applications like editors.  The simpler and better way of getting shell access on the PocketBook devices is by using telnet to utelnetd.  You can find utelnetd [here] (http://www.mobileread.com/forums/showpost.php?p=2133251&postcount=1).  You can get gdb from [here] (http://www.mobileread.com/forums/showthread.php?t=222077).  I don't think that gdb works under either the SSH or utelnetd sessions, but it does work under the pbterm application.  Other utilities can be obtained from the Debian Lenny armel distribution.

**Comment by chrox** [comment]
OK, I tested the huge epub document (about 10 MB and 25000 pages) on my PB840. It took koreader one minute and a half to open for the first time. And then for the second time koreader takes 10 seconds and then 3 seconds for the third time. Obviously when opening the document for the second and third time the cache file of the doc was prepared well.

**Comment by Frenzie** [comment]
Should be reduced by #3292. (Also see #3261.)
