### ISSUE TITLE
The EverNote(yinxiangbiji) export format

### ISSUE THREAD

**Issue by tiandongxv** [koreader/koreader#1479]
The possibility of increasing the section name derived containing notes, "the first chapter" in a line, Add black bold font. thanks! :-D

**Comment by tiandongxv** [comment]
[Example](https://dl.pushbulletusercontent.com/Md3iCk7rje6ZO8ZJ3GKipoaZJ7K3eP1O/%E6%88%AA%E5%9B%BE20150409105641.png)

**Comment by chrox** [comment]
Please tweak the template file [here](https://github.com/koreader/koreader/blob/master/plugins/evernote.koplugin/note.tpl) and send us a pull request. If the style is really better we will merge that PR.

**Comment by chrox** [comment]
Close this now.
