### ISSUE TITLE
 support for non-touch devices (Pocketbook Pro)

### ISSUE THREAD

**Issue by maslukov** [koreader/koreader#1480]

**Comment by chrox** [comment]
The koreader/koreader project is targeted on touch based E-ink devices. There is also a [koreader/kindlepdfviewer](https://github.com/koreader/kindlepdfviewer) project that should handle keyboard-based devices and probably that's a better place to request this feature. I'm close this issue now.

**Comment by houqp** [comment]
Actually, I tried koreader on Kind DXG, and it works fine. It's just really slow because DXG's hardware configuration is kind of old. So we should be able to run koreader on Pocketbook Pro fine if it has reasonable computing power.
