### ISSUE TITLE
App doesn't use the whole screen when navbar is hidden in Boyue T62+

### ISSUE THREAD

**Issue by diegopau** [koreader/koreader#1481]
Boyue T62+ (i guess is the same for T62) has an option to hide statuts/nav bar. When selected and opening KOReader there is a black part on the bottom of the screen (both in ladscape and portrait).

I tried with the last stable version and also with the last nightly version (v2014.11-167-gded6b89)

I attach pictures of how KOReader works and how other reader apps work:

![img_20150411_183122](https://cloud.githubusercontent.com/assets/315149/7102218/d2929a1a-e079-11e4-954c-ea74b1177c26.jpg)
![img_20150411_183024](https://cloud.githubusercontent.com/assets/315149/7102219/d29a0566-e079-11e4-8e8f-eb0445e2bc50.jpg)

**Comment by gerroon** [comment]
see this one for a solution
https://github.com/koreader/koreader/issues/1180

**Comment by diegopau** [comment]
@gerroon yes it works, thanks a lot. I close the issue then.
