### ISSUE TITLE
Option "Start with last opened file" freezes ePub on PW2

### ISSUE THREAD

**Issue by trekk2810** [koreader/koreader#1482]
Paperwhite 2, Serial 9017..., 4GB, FW 5.4.5. 

When I start KoReader with the option "Start with last opened file" any ePub opens, but instantly freezes, so I have to restart the device. Starting via KUAL with the option "Open the last document" also freezes KoReader. If the option "Start with last opened file" is not checked, I can bypass this by opening the ePub in the filemanager, but with many books on the device that's not comfortable. ;)

V2014.11-93-gac77808 is the last build without that problem. Every newer build gives me the same freeze. I did a fresh install, I even installed the PW firmware again, but no change.

**Comment by chrox** [comment]
Thanks for the precious information. Then I can locate the problem to be the "turbo" library. Could you try updating to the latest nightly build and adding this line: `export LD_LIBRARY_PATH=${KOREADER_DIR}/libs:$LD_LIBRARY_PATH`
at [line 111](https://github.com/koreader/koreader/blob/master/platform/kindle/koreader.sh#L111) of the file koreader/koreader.sh on your kindle device and report back the behavior of the koreader?

**Comment by trekk2810** [comment]
I updated to the latest build 20150407 and added the line, but KoReader still freezes!

**Comment by trekk2810** [comment]
Hi Huang Xin, 

I did as you suggested and added the line in koreader.sh, but sadly KoReader still freezes. The issue should not be closed.

trekk

Am 13.04.2015 um 04:40 schrieb Huang Xin <notifications@github.com>:
