### ISSUE TITLE
Freeze when launching files with KPV booklet on PW2

### ISSUE THREAD

**Issue by lightevilaster** [koreader/koreader#1486]
Hello everyone!
A nightly build it will freeze the kindle if I launch any file with KPV booklet or launch the recent file from KUAL. Everything is fine if I launch file-manager first. Last stable build is fine. Is it a well-known issue and is there a solution yet?
Thank you and best regards!

**Comment by chrox** [comment]
Could you try the latest nightly build which was uploaded several minutes ago? It fixed a bug that may cause freeze on kpw2.

**Comment by boplennon** [comment]
In KPW2, fw 5.6.1.0.6, Kindle still freezes when use KPV. I could access file manager by KUAL but if I try to open any books, it crashes and kick me out to main screen.
crash.log:
frontend/apps/filemanager/filemanager.lua:66: attempt to index local 'ReaderUI' (a boolean value)
stack traceback:
	frontend/ui/uimanager.lua:516: in function '__index'
	frontend/apps/filemanager/filemanager.lua:66: in function 'onFileSelect'
	frontend/ui/widget/filechooser.lua:185: in function 'onMenuSelect'
	frontend/ui/widget/menu.lua:293: in function 'action'
	frontend/ui/uimanager.lua:302: in function '_checkTasks'
	frontend/ui/uimanager.lua:453: in function 'handleInput'
	frontend/ui/uimanager.lua:514: in function <frontend/ui/uimanager.lua:514>
	[C]: in function 'xpcall'
	frontend/ui/uimanager.lua:514: in function <frontend/ui/uimanager.lua:511>
	[C]: in function 'xpcall'
	common/turbo/ioloop.lua:496: in function <common/turbo/ioloop.lua:495>

**Comment by boplennon** [comment]
when I use KPV to open books again after reboot Kindle, it stops freezing but still crashes.

./luajit: ./reader.lua:136: attempt to index local 'ReaderUI' (a boolean value)
stack traceback:
	./reader.lua:136: in main chunk
	[C]: at 0x0000be95

**Comment by chrox** [comment]
I can reproduce this on my new kindle voyage. I will look into this later.

**Comment by chrox** [comment]
I also got an instant freeze when opening a document directly in an SSH session like this:
`strace ./reader.lua -d /mnt/us/documents/some/document.pdf`.
The log ended that:
```
gettimeofday({1429006455, 867378}, NULL) = 0
write(1, "# assigned marker 1 to update: {"..., 176# assigned marker 1 to update: {
	["refreshtype"] = 1,
	["time"] = 1429006455867.4,
	["rect"] = {
		["y"] = 0,
		["x"] = 0,
		["h"] = 1,
		["w"] = 1
	},
	["waveform_mode"] = 8
) = 176
write(1, "}\n", 2}
)                      = 2
ioctl(3, MXCFB_SEND_UPDATE, {update_region={top=0, left=0, width=1, height=1}, waveform_mode=WAVEFORM_MODE_REAGL, update_mode=UPDATE_MODE_FULL, update_marker=1, hist_bw_waveform_mode=WAVEFORM_MODE_REAGL, hist_gray_waveform_mode=WAVEFORM_MODE_REAGL, temp=TEMP_USE_AUTO, flags=0, alt_buffer_data={phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}) = 0
# refresh: wait for submission
/mnt/us/koreader # ls
Connection to kindle closed by remote host.
Connection to kindle closed.
```

Is it valid to update region {top=0, left=0, width=1, height=1}? I remember there was such one-pixel-update-causing-freeze problem on kindle paperwhite2 probably it comes back again.

**Comment by hwhw** [comment]
Yes, freezing was the usual reaction of the framebuffer driver to data it didn't like. You can try to clamp refresh size to some minimum in framebuffer.lua https://github.com/koreader/koreader-base/blob/master/ffi/framebuffer.lua#L104..L120

I'd use something like

 if w == 1 then
   w = 2
   if x > 0 then x = x - 1 end
 end

plus something similar for h/y.

**Comment by chrox** [comment]
I found the old one-pixel issue #1299. And the patch for #1299 is just a workaround on `UnderlineContainer` other widgets may also have this problem. So a better solution is check the dimension in mxc_update.

**Comment by hwhw** [comment]
yes, mxc_update might be an even better place if the mxc framebuffer drivers are the only ones affected.

**Comment by chrox** [comment]
Yes, it seems only occurs on Kindle Paperwhite2 and Kindle Voyage and probably New Kindle Touch (no report yet). And it's confirmed that clamping the dimension in mxc_update solves this problem. I will send a PR soon.
