### ISSUE TITLE
OTA update doesn't work for me.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1487]
When I try to update koreader, I always (since at least a month and a lot of nightlies) get a message like "OTA update not available." I am on version 2014.11-167-gded6b89. Does this happen only on the kobo H2O? Or do others experience it, too?

WiFi on H2O has had a few problems (see issue  #939 ) with freezing koreader. However, now it works with at least Wikipedia lookup. So it is not due to WiFi not working.

**Comment by Frenzie** [comment]
I believe it's because of the new channels. You need to manually put in place a newer version and then it'll work.

**Comment by chrox** [comment]
The default OTA channel is "stable" channel now. Since there is no new stable release the OTA check will fail.  You may need to change to nightly channel to get the latest nightlies.

**Comment by Markismus** [comment]
Thanks! Works like a charm. 

I see that the code implementation is from last August. I used it after that. So when did the default channel change to "stable"? 
I can't find info about OTA updates and channels in the wiki. Is it there yet?

**Comment by chrox** [comment]
Oh, no. The [OTAManager](https://github.com/koreader/koreader/blob/master/frontend/ui/otamanager.lua) is last touched [two months ago](https://github.com/koreader/koreader/commits/master/frontend/ui/otamanager.lua).

**Comment by Markismus** [comment]
There is a compatibility problem with KSM7. 

I have moved koreader to the `/mnt/onboard/.adds/koreader` path, because Tshering had some reasons for that. (I think he wrote that it would allow a koreader installation to survive a factory reset.) However, the OTAManager places the new version in the `/mnt/onboard/.kobo/koreader` path. KSM stops looking for koreader after it has found a version in the `.adds` path, so I have to manually move it.

A way would be to change the koreader installation path to `/mnt/onboard/.adds/koreader` both in the creation of the update and the wiki. If people installed their koreader in the old path, they will only have to move their `persistent.defaults.lua` once.

Any other suggestions?

**Comment by Markismus** [comment]
Reading line 160 in [`otamanager.lua`](https://github.com/koreader/koreader/blob/master/frontend/ui/otamanager.lua#L160), I would expect `lfs.currentdir' to be independent of the installed path. Do the ZSync-files carry a hardcoded path with them?

**Comment by chrox** [comment]
Did you change the path here https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L12 and https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L5? They are the only two places that use hardcoded path.

**Comment by Markismus** [comment]
Finally got some time. Apparently KSM changed `koreader.sh`:
```sh
# working directory of koreader
KOREADER_DIR=$(dirname $0)
```
Executing `dirname /mnt/onboard/.apps/koreader/koreader.sh` in KSMterminal results in `/mnt/onboard/.apps/koreader`. So that doesn't seem to be the problem. 

I'll see whether the next nightly does install as it should. Maybe the KSM script change was later than the update.

**Comment by Markismus** [comment]
I should be able to update from 171 to 181 now. 

I get the choice to update, the message about updating at next restart is given, I restart by going to KSM and starting koreader, still at v171, rinse and repeat, no change. 

Since USB was enabled in KSM, I rebooted and restarted. Still v171. asking for an update takes very long now, but terminates with the message: no OTA update available.
Looking in `koreader/ota/` I do see updated files and what's more: I see a whole new koreader directory `.kobo/koreader`. 

So Tshering's tweak to the script doesn't work!

**Comment by Markismus** [comment]
See  #1499 for the PR.

**Comment by Markismus** [comment]
Ota update still doesn't work, since Tshering's KSM overwrites the new `koreader.sh` with his version. So the hardcoded path in line 12 returns. I'll post the problem in his thread over at mobilereads.
