### ISSUE TITLE
Uncentered touch or problem with Koreader in file manager

### ISSUE THREAD

**Issue by fabeuw** [koreader/koreader#1492]
I a Kobo touch, have installed start menu, and the latest stable build. Start menu works fine but when I enter in Koreader file manager it seems the bottom half of the screen doesn't work, the arrows don't work and when I tap it selects a file that is on the top part of the screen.

What could be the issue?

**Comment by houqp** [comment]
looks like the screen got rotated upside down? can you try tapping on the top of the screen randomly to see if you can trigger the arrow at the bottom?

**Comment by fabeuw** [comment]
@houqp I have tried that but it doesn't work. It seems no matter where I touch it only selects 1-2 files or folders, and once I get in a folder that has only a few files I can't even go up a level.
Does the FW have to be updated on the Touch to make Koreader work?

**Comment by hwhw** [comment]
I don't think it's a firmware problem. It rather looks like a 90-degree rotation of the touch input coordinates.

@fabeuw: can you give a try to adding/inserting a line
```lua
KOBO_TOUCH_MIRRORED=true
```
into the defaults.persistent.lua file in the koreader directory? (You can create that file if it doesn't exist yet)

**Comment by fabeuw** [comment]
@hwhw thank you that worked!

**Comment by hwhw** [comment]
Hm. Some Kobo Touch devices still have some different layout and we don't recognize them properly.
