### ISSUE TITLE
How to copy the text from pdf file in koreader?

### ISSUE THREAD

**Issue by amethystum** [koreader/koreader#1495]
Hi, I'm wondering how to copy text from a pdf file in koreader. Thx!

**Comment by Markismus** [comment]
There is no note feature in koreader, so there is no way to make a document that would contain the copied text.

One albeit circumspect way would be:
- highlight or if it is a scanned pdf, then turn on reflow and then highlight
- export highlights using Evernote
- open Evernote in another device with Evernote installed
- text is ready for copying.

I actually used this feature after highlighting an article and it works rather nice.

**Comment by Markismus** [comment]
Haven't tried this myself, but Koreader allows Evernote to make local html-files. The workflow would then become:
- Highlight with/without Reflow on/off
- Tools>Evernote>Log in
- Tools>Evernote> export to local html-files
- Open html-files in koreader or connect to PC and copy/edit html-files

**Comment by chrox** [comment]
Yes, there is no system clipboard in kindle or Kobo or other single-task eink reader so we cannot copy text to system clipboard for users to paste in other applications. As @Markismus suggested you can export highlights to a local HTML file in the koreader/clipboad directory.
