### ISSUE TITLE
where to find arm-kindle-linux-gnueabi?

### ISSUE THREAD

**Issue by abbaspour** [koreader/koreader#1496]
when compiling for kindle-legacy (armv6/k3), the cross-compiler is set to arm-kindle-linux-gnueabi-{tool}.
I just have arm-linux-gnueabi-{tool} for recent kindles (armv7) in my path.

where/how kind I find/build arm-kindle-linux cross compile binaries?

for the record, changed the base/Makefile.def to use arm-linux-gnueabi with v6 architecture but final executables crashes on k3.

**Comment by abbaspour** [comment]
I should have asked this in koreader-base I guess.

**Comment by hwhw** [comment]
Just edit the name - it is just using what we used at that point, but other toolchain names should work, too. I think it should be enough to set CHOST variable on the make command line, e.g. "make CHOST=arm-linux-gnueabi". The really relevant things are the flags that get set later: https://github.com/koreader/koreader-base/blob/master/Makefile.defs#L143 - it's a bit of a jungle there in the Makefile, I guess.

**Comment by abbaspour** [comment]
thanks. confirming it works with k3 (kindle-legacy) with arm-linux-gnueabi. closing issue.
