### ISSUE TITLE
I Can NOT log in the EverNote!

### ISSUE THREAD

**Issue by tiandongxv** [koreader/koreader#1501]
I Can NOT log in the EverNote!
My device is kindle paperwhite (5.4.4.2),Nightly builds(koreader-nightly-20150416),whatever evernote or 印象笔记,I can`t log in.
Please HELP me!
Thanks!
![Example](http://i.imgur.com/TmAXnOC.jpg)

**Comment by tiandongxv** [comment]
I have tested many versions !!

**Comment by chrox** [comment]
I can confirm this bug and will look into this later.
