### ISSUE TITLE
Problems with opening DjVu by KOreader on Kobo H2O.

### ISSUE THREAD

**Issue by TobiaszSML** [koreader/koreader#1515]
Hi everybody!

I have Kobo H2O ebook reader with firmware 3.12.1. I installed on Kobo KSM 7 with update 1 and 2. I always use the latest koreader nightly version, but I still can't open files in DjVu. When I'm trying to open this format, on screen appears information "no reader engine for this file". How solve this problem?

I apologize for my English.

**Comment by NiLuJe** [comment]
I'll check on a H2O, but AFAICT, worksforme on a PW2 :?.

Does that happen only with specific files, or all? (and did you only try a handful of them?)

**Comment by NiLuJe** [comment]
Yup, definitely worksforme, on a H2O, too.

![djvu](https://cloud.githubusercontent.com/assets/111974/7390119/1118b6c6-ee75-11e4-9ca5-ce35d37088b1.png)

**Comment by NiLuJe** [comment]
Keep in mind that I launch KOReader manually over SSH, but if launching it through KSM introduces some weird behavior, there's definitely something strange going on somewhere.

**Comment by Markismus** [comment]
Nope, works on H20 and KSM 7, update 2, too.

**Comment by TobiaszSML** [comment]
Well, I lauch KOreader always by KSM and I can't open any DjVu, no matter from where I have the file.

**Comment by Markismus** [comment]
You can open other filetypes from the same location as the dvju-files?

**Comment by TobiaszSML** [comment]
Yes, with PDF and epub files i don't have any problems.

**Comment by hwhw** [comment]
Do the file names (full path, i.e. including all directories) contain non-ascii characters? The djvu library is quite broken in this regard, unfortunately.

**Comment by TobiaszSML** [comment]
Thank you hwhw! Main folder with books I named "Książki", so in file path was at least two non-ascii polish letters. Because of that I can not open any DjVu files... Now I have to change almost all files names, but the problem is solve.

Thank you all guys for help, and you hwhw especially:)

**Comment by hwhw** [comment]
Welcome, glad it is "solved". Well, sort of. I looked into this issue before, but there is no easy solution, unfortunately. The djvu library considers the file path a "text" data type, and an Unicode encoded one for that, rather than an opaque number of bytes... And it's not easy to patch that.
