### ISSUE TITLE
# INFO: invalid widget for setDirty() stack traceback

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1516]
I looked at the logs for the first time in ages and I kept running into this stack traceback for nine times (15% of all log lines!). Is this expected behavior?

Typical example:
```
# INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:205: in function 'setDirty'
	frontend/apps/filemanager/filemanager.lua:236: in function 'restoreScreenMode'
	frontend/apps/filemanager/filemanager.lua:243: in function 'showFiles'
	frontend/apps/reader/modules/readermenu.lua:52: in function 'callback'
	frontend/ui/widget/touchmenu.lua:484: in function 'switchMenuTab'
	frontend/ui/widget/touchmenu.lua:226: in function 'callback'
	frontend/ui/widget/iconbutton.lua:52: in function 'action'
	frontend/ui/uimanager.lua:302: in function '_checkTasks'
	frontend/ui/uimanager.lua:453: in function 'handleInput'
	frontend/ui/uimanager.lua:514: in function <frontend/ui/uimanager.lua:514>
	[C]: in function 'xpcall'
	frontend/ui/uimanager.lua:514: in function <frontend/ui/uimanager.lua:511>
	[C]: in function 'xpcall'
	common/turbo/ioloop.lua:496: in function <common/turbo/ioloop.lua:495>
# cache image|resources/icons/appbar.chevron.first.png||
# cache image|resources/icons/appbar.chevron.last.png||
# cache image|resources/icons/appbar.arrow.left.up.png||
# show widget
```

**Comment by NiLuJe** [comment]
```
UIManager:setDirty(self, "full")
```

probably ought to be

```
UIManager:setDirty(nil, "full")
```

?

Someone more familiar with the intricacies of the UI Manager might shed some more light on this ;).

**Comment by hwhw** [comment]
Well, in most cases, not the whole screen but rather a single widget (i.e. the space it covers) should be set "dirty". In this case, the widget given ("self") might not be a widget but some other kind of object - or maybe it ceases to exist, which can also happen (thinking about this: can it?). I might have a look. However, that message is mostly debug output. The fallback action, I think, would be to refresh the whole screen, since at least there is *something*  that ought to be refreshed :-)

**Comment by Markismus** [comment]
So it is not something everyone sees in their logs or on the terminal output? 

Only extra info is that koreader started, opened a dvju-file and was probably exited to KSM. If someone wants, I could post the entire log.

**Comment by hwhw** [comment]
No, I guess everyone sees that.
