### ISSUE TITLE
StarDict files for koreader

### ISSUE THREAD

**Issue by zolrak** [koreader/koreader#1518]
This page https://github.com/koreader/koreader/wiki/Dictionary-support teaches how to install this dictionary with koreader, but the files to download are bigger than the space on my kindle. I tried searching other files, but without sucess. Can someone tell me where to find the files I need, please? This other link https://github.com/koreader/koreader/issues/552 gives some alternatives, but they are not working on the moment.

Thanks!

**Comment by NiLuJe** [comment]
I'm guessing the archive contains seventy billion dictionaries for all the languages of the known universe, so, just pick the ones you need instead of trying to copy everything?

**Comment by zolrak** [comment]
The problem is that it is all packed in one big file, divided between seven rar files, and all I need is the english-english version. I was looking for other option besides downloading it all, but couldn't find any.

**Comment by zolrak** [comment]
Anyone?

**Comment by Markismus** [comment]
Still can't find it? If that's typical than we really need to make a begin with providing our own dictionaries. See #1420 for the discussion about that intent. 

For now [here](https://copy.com/tSBGHh48z0tNq4vu) is a link to the dictionaries I use. An en-en dictionary is amongst them.

**Comment by Markismus** [comment]
BTW for those that download the seven tar-files under windows and find that WinRar doesn't know how to handle them: Combine them into one tar-file with this command:
```cmd
copy /b stardict-dic_20150131.tar.* stardict-dic_20150131.tar
```

Then WinRar will handle the tar-file.

**Comment by Markismus** [comment]
I found [a mirror of the old huzheng page](http://abloz.com/huzheng/stardict-dic/) on [the dictionary thread on mobilereads](http://www.mobileread.com/forums/showthread.php?p=2576622#post2576622). All dictionaries can still be downloaded individually.
