### ISSUE TITLE
Can record the current page when crash?

### ISSUE THREAD

**Issue by monkhou** [koreader/koreader#1519]
I run koreader on onyx c67ml
The program crashes frequently
Can it do this :when page changes,the current position can be recorded so after the collapse again, don't have to turn the page
thanks

**Comment by erosennin** [comment]
It might be a good idea to save current state every 10 pages or so.

**Comment by chrox** [comment]
You could checkout this https://github.com/koreader/koreader/blob/master/defaults.lua#L142-L143.

**Comment by erosennin** [comment]
Great, didn't know about that!

**Comment by monkhou** [comment]
solved
thanks
