### ISSUE TITLE
Back to nickel from koreader crash if wifi is still alive

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#1520]
I found this on my new Aura HD with fw 3.15 using fmon to launch koreader. Switching between koreader and nickel works ok with wireless disabled. If I enable wireless in nickel, then go to koreader and back to nickel again (without suspend, which already disables wireless) nickel does not work and I need to restart the device.

I fixed this disabling wifi before start nickel again on koreader.sh

Anyone facing this issue? @NiLuJe  ??

**Comment by NiLuJe** [comment]
Turned out to be more sneaky in my case : if anything is having any interaction with the shell when the WiFi goes down for good, the device shits a brick... 

For instance, having a tail or a strace running (without io redirection), boom. 
A simple shell on standby, OK, on the other hand. 

I have yet to check if backgrounding koreader and sending the output somewhere does the job...

**Comment by NiLuJe** [comment]
But if killing the WiFi helps, that's a great workaround, since nickel will kill it anyway.

**Comment by NiLuJe** [comment]
See if sticking suspend's wifi killing code at the beginning of nickel.sh helps?

```# disable wifi
if lsmod | grep -q sdio_wifi_pwr ; then
        wlarm_le -i eth0 down
        ifconfig eth0 down
        rmmod -r dhd
        rmmod -r sdio_wifi_pwr
fi
```

**Comment by pazos** [comment]
Yes, it works

I dunno why we check platform on koreader.sh & nickel but not in suspend.sh. AFAIK all kobos supported are != freescale

**Comment by pazos** [comment]
I checked your scenario with "strace yes" running from ssh and switching from/to koreader and everything worked fine for me.

**Comment by NiLuJe** [comment]
Great, I'll put this in a PR, thanks for testing :).

----

As for keeping the freescale checks, that's because I tried to keep the logic of the init script intact, so it's easier to keep track of/spot the differences ;).
