### ISSUE TITLE
[Feature request] NEWS (RSS/Atom) plugin to Koreader ?

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#1524]
Could you create a NEWS (RSS/Atom) plugin for Koreader?

Koreader already supports XML/HTML, and there are many RSS parsers ~~(rss2html) for linux, 
so hopefully it's a quick change of adding a parser and a 2 menu configs: 
"download RSS feeds" and "Start with RSS feeds"?~~
Simplier idea (with LUA Rss parser) describe 3 posts below

Thank you
Marcin
ps: configuration could be done as config file (editable outside the koreader)

**Comment by gerroon** [comment]
Yeah this would be nice

**Comment by mwozny123** [comment]
there's a lua rss parser:
https://github.com/slact/lua-feedparser

maybe it would be useful?

**Comment by mwozny123** [comment]
There could be a plugin button "download current RSS feeds" which will download rss feeds context to Koreader/RSS directory (or other), and user could navigate (and open it) using Koreader fileManager.

Unfortunately I'm not so expirenced in programimng to do it:( 
Could some else do it?

**Comment by timofonic** [comment]
Any news?

**Comment by mwozny123** [comment]
I propose such simple "business concept":
- use external tool to edit rss config file (out of the scope) 
- use Lua rss parser (link above) to parse data and get data url for download 
- use wget (or something similar) to download the feeds (under url) to separate directory and store as html
-use koreader to view downloaded HTML (no changes needed)

**Comment by aipie0066** [comment]
It's a wonderful feature.

**Comment by lenisko** [comment]
Hmm, I must admit. That would be a great idea.
KOReader is taking a path of multifunctional software not just a reader : )

**Comment by KenMaltby** [comment]
The main thing would be that it remain at heart a reader, and the plugins provide features that support that.  That the reader not be diminished by any plugin. It sounds like an RSS feed would provide another thing to be read, by the reader. Hopefully, the separation provided by the plugin concept will keep the reader well protected, no matter how much gets hung onto it.

**Comment by timofonic** [comment]
RSS are news. It's a reader feature. The reader feature isn't a problem to
be "protected", as long as it works.

My concept of reading is maybe "wider", maybe ;)

**Comment by Markismus** [comment]
I think that Ken raises a valid point. The plugins should be easily plugged in an out without a performance penalty to the functioning of the reader. Sloppy plugins that can't be removed or need a restart of the program should be avoided. 

A clear description of how the plugins should conform to run within koreader would therefore be very welcome.

I don't think we need to go into the width of a concept of reading. I don't even think that Ken's comment was meant to introduce such a topic.

**Comment by mwozny123** [comment]
@KenMaltby [my simplified concept of plugin](https://github.com/koreader/koreader/issues/1524#issuecomment-164431933) (Koreader already supports viewing HTML files) doesn't require any changes to Koreader. 

It just requires development of plugin that would use RSS framework (e.g. [lua-feed-parser](https://github.com/koreader/koreader/issues/1524#issuecomment-118501196) or [wallabag](https://github.com/koreader/koreader/issues/1634#issuecomment-139858065)), and download it contents.

**Comment by KenMaltby** [comment]
@mwozny123;  What you describe sounds like something that should fit what I was attempting to get at.  
@Markismus makes my point better than I.

**Comment by mwoz123** [comment]
Simple News (rss /atom) Downloader : https://github.com/koreader/koreader/pull/2592

**Comment by silberzwiebel** [comment]
I do like the RSS / Atom downloader, but I do have a https feed that is currently not supported (it's actually framabag.org, a wallabag instance).

Should I open another issue / feature request to support https feeds or is my request in a good place here?
Thanks!

**Comment by Frenzie** [comment]
I suppose it's probably clearer to close this one and open a new issue.

**Comment by silberzwiebel** [comment]
opened #3041 but can't close this one.
