### ISSUE TITLE
New device: Kobo Glo HD

### ISSUE THREAD

**Issue by tarlou** [koreader/koreader#1525]
Hi, it is my first time to try koreader. It seems that the device Glo HD is not supported yet. Koreader won't start unless I added the following to */.kobo/koreader/frontend/device/kobo/device.lua* (found this with the help of crash.log).
```
local KoboAlyssum = Kobo:new{
    model = "Kobo_alyssum",
    hasFrontlight = yes,
    display_dpi = 300,
}
```
and near the end of the file
```
elseif codename == "alyssum" then
	return KoboAlyssum
```
However, I'm not sure if there are other parameters that need to be set. So far koreader is working except all touches are treated as "long press". It is very tricky to make a short press (turn page or open menu). For most touches, dictionary (or cut/copy/delete/... at the file manager screen) is opened. I haven't figured out a way to fix this.

It would be great if Glo HD can be supported!

**Comment by Markismus** [comment]
[Official specs Kobo GLo HD](http://gl.kobobooks.com/products/kobo-glo-hd):
6” HD Carta E Ink touchscreen, 1448 x 1072 resolution 300 pixels per inch with bezel like the Aura H2O.
[Official specs Aura HD H2O](http://gl.kobobooks.com/products/kobo-aura-h2o): 
Extra-large 6.8” Carta E Ink HD touchscreen with high, 1430 x 1080 resolution, 265 dpi

Looking at the specs for the Dahlia (Aura HD H2O ):
```
-- Kobo Aura H2O:
local KoboAlyssum = Kobo:new{
    model = "Kobo_alyssum",
    hasFrontlight = yes,
    touch_phoenix_protocol = true,
    display_dpi = 300,
    -- the bezel covers the top 11 pixels:
    viewport = Geom:new{x=0, y=11, w=1080, h=1429},
}
```

I would suggest as a first try to use _all_ the info from the H2O. 
The line about `touch_phoenix_protocol` could already solve your long press problem. 
The line about the viewport allows you to specify your width and height. Start with a viewport of `x=0, y=11, w=1072, h=1447`. You can tweak those to get the ideal viewport given the bezel of the Glo HD.
The result would be:
```
-- Kobo Glo HD:
local KoboDahlia = Kobo:new{
    model = "Kobo_dahlia",
    hasFrontlight = yes,
    touch_phoenix_protocol = true,
    display_dpi = 265,
    -- the bezel covers the top 11 pixels:
    viewport = Geom:new{x=0, y=11, w=1072, h=1447},
}
```

**Comment by Markismus** [comment]
@tarlou How is the device working? Does it have a faster processor and more memory than the Kobo Aura?

**Comment by tarlou** [comment]
Thanks! This is my first e-reader so I don't know how it compares to others. But it's indeed slower than I expected.

`touch_phoenix_protocol = true` doesn't seem to solve the problem.

`viewport = Geom:new{x=0, y=11, w=1072, h=1447},` results a crash with "bad viewport"  in crash.log (ffi/framebuffer.lua, line 137, where it checks `viewport.y+viewport.h > self.screen_size.h`, etc.). I tried some different parameters, to make koreader run there must be y+h<=1448. Setting y=11, h=1437 or something like that, things will work. The parameters for Auro H2O (where y+h=1440>1430) look strange to me now.. Anyway this isn't a big problem.

**Comment by Markismus** [comment]
"`touch_phoenix_protocol = true` doesn't seem to solve the problem." is kind of uninformative. The two kobo touch protocols are that different, that I only expect one to be working, not both. So you could try `false` and see whether that changes much.

If we're going to get the Glo HD working for touch, we need information: both a debug log and ev.log. 

To generate them change [line 65 in koreader.sh](https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L65):
```sh
./reader.lua $args 2> crash.log
```
to 
```sh
./reader.lua -d /mnt/onboard > koreader.log.`date +%s` 2>&1
```

The koreader.log will contain all output send by koreader to standard out (,s.a. the terminal if your running from the prompt.) The ev.log will contain all touch events as send by the kernel to koreader.

**Comment by Markismus** [comment]
The resolution given by the official site is not always the resolution of the screen.The Kobo Aura had a flush bezel which also obscured some text, depending on your reading angle. The pixelheight and width varied wildly between sites, only keeping the dpi constant. 

It's quite likely the height of the H2O is 1440. Apparently marketing has taken the obscured pixels into consideration.

**Comment by tarlou** [comment]
Thanks for the instructions! I studied the logs a bit, and I think `touch_phoenix_protocol = true` is correct. Below is a part of ev.log (a short tap), it seems to be the protocol explained in the comments of `Input:handleTouchEvPhoenix`.
```
3|57|1|72|190548
3|48|1|72|190550
3|50|1|72|190551
3|53|151|72|190555
3|54|879|72|190557
3|24|1024|72|190560
1|330|1|72|190564
0|2|0|72|190566
0|0|0|72|190568
3|57|1|72|207898
3|48|0|72|207902
3|50|0|72|207904
3|53|151|72|207906
3|54|879|72|207910
3|24|0|72|207913
1|330|0|72|207915
0|2|0|72|207916
0|0|0|72|207918
```

I debugged a bit, and it seems that the above `tap` is changed to `hold` in the timer set in `GestureDetector:handleNonTap` (change to `holdState` after `HOLD_INTERVAL`). The following is a part of `koreader.log`, corresponding to the press down part of the above tap in `ev.log`:
(I added some more debugging information here. The second `set up hold timer` is added by me, it's in `GestureDetector:handleNonTap`, after the first `set up hold timer`, outputting the `deadline` in the timer. The `timer callback` is in `Input:waitEvent` where `tv_now >= self.timer_callbacks[1].deadline` holds, it outputs the current time `tv_now` and `self.timer_callbacks[1].deadline`.)
```
# tev fed| 72 | 190568 | 193 | 150 | 1 | Evt 1
# in tap state...
# set up hold timer
# set up hold timer {
	["usec"] = 690568,
	["sec"] = 72
}
# handle input in turbo I/O looper
# timer callback {
	["usec"] = 398630,
	["sec"] = 1431588785
} {
	["usec"] = 690568,
	["sec"] = 72
}
# hold gesture detected in slot 1
```
The problem here is `tv_now` obtained by `TimeVal:now()` is very different from the time of the events (maybe they are different formats, I don't know).
I can solve the problem by changing the `deadline` in the timer, use 
```
local deadline = TimeVal:now() + TimeVal:new{
            sec = 0, usec = self.HOLD_INTERVAL
        }
```
instead of 
```
local deadline = tev.timev + TimeVal:new{...
```
Then in `Input:waitEvent` the two times will have the same format. Now I can turn pages without problem. 

There seems to be other (but more or less tolerable) glitches, e.g. a part of the top menu becomes white sometimes, but recovers when I select another menu item. I'll take a look at that when I got a time.

**Comment by Markismus** [comment]
You are missing the milliseconds. I would have expected 6 columns, instead of your 5!
Alright, we'll have to work around that.


Typical ev.log as created by Aura HD:
```
3|57|0|1385896867|432216
3|48|1|1385896867|432262
3|50|1|1385896867|432269
3|53|38|1385896867|432277
3|54|456|1385896867|432286
0|2|0|1385896867|432297
3|0|38|1385896867|432308
3|1|456|1385896867|432317
3|24|1024|1385896867|432327
```

Kobo Aura ev.log:
```
3|57|0|1388602230|529833
3|48|1|1388602230|529876
3|50|1|1388602230|529882
3|53|483|1388602230|529891
3|54|686|1388602230|529899
0|2|0|1388602230|529910
3|0|483|1388602230|529922
3|1|686|1388602230|529930
3|24|1024|1388602230|529940
```

**Comment by tarlou** [comment]
Yes, it can be different from 72. After tried a few times, I believe it is the number of seconds since powered on. (I was rebooting the device frequently...) The 10-digit number obtained by TimeVal:now() or generated in the older models should be the number of seconds since the Epoch, 1970-01-01 00:00:00 +0000 (UTC). Instead of the work around in my previous post, adding a line `ev.time = TimeVal:now()` in `function Input:eventAdjustHook(ev)` also seems to solve the problem.

It seems that the protocol is not exactly the same as in the old models. Here is an `ev.log` file: https://github.com/tarlou/mystaffs/blob/master/ev.log
On Glo HD, the protocol is as following:
```
3 | 57 | finger_id | sec | usec
3 | 48 | (1 for press/hold, 0 for release) | sec | usec
3 | 50 | (1 for press/hold, 0 for release) | sec | usec
3 | 53 | X | sec | usec
3 | 54 | Y | sec | usec
(only at press/release, not exist when holding) 3 | 24 | (1024 for press, 0 for release) | sec | usec
(only at press/release, not exist when holding) 1 | 330 | (1 for press, 0 for release) | sec | usec
0 | 2 | 0 | sec | usec
0 | 0 | 0 | sec | usec
```
The above is for single tap/hold/drag. If there are two fingers, the first finger won't have `0 | 0 | 0 | sec | usec` when both fingers are touching the screen and only the second finger has this line.

**Comment by Markismus** [comment]
Yes, input:eventAdjustHook is indeed meant for those tweaks.  

I suggest that you look at the function input:init and define eventAdjustHook there for the alyssum only. Upon initialization the function will than be defined as is needed for the device model.

After that it would be nice to see an pull request from you containing the changes to device.lua and input.lua. Some of the other developers will join the discussion and maybe even improve on your code.

**Comment by Markismus** [comment]
I see that you haven't forked koreader yet. To create a pull request first fork koreader on github. On your personal forked koreader repository you can edit the files. When you compare your repo with koreader's it will show the changes and ask you whether you want to create a pull request. Select yes and in the koreader repo an PR will be made. 

Someone will have to merge it before your code changes become part of the koreader program.

**Comment by Markismus** [comment]
Closing this as the latest nightly release now supports Glo HD.
