### ISSUE TITLE
Need two taps to turn a page even at default zoom mode (because of an issue with floating point)

### ISSUE THREAD

**Issue by tarlou** [koreader/koreader#1529]
I have a book with some pages of size 1666x2400. The screen of my device is 1072x1448.
So `zoom = 1448 / 2400 = 0.60333333333333338810`,
after zooming, the height of the page is `page_area.h = 2400 * zoom = 1448+2.2737367544323205948e-13`. However, the height of the visible area is `visible_area.h = 1448`, so the page does not fit in one screen.
The small error comes from floating point arithmetics. I need to tap twice to turn every page so tracked into the code and found this.

An easy solution is to use a slightly safer value when calculating `zoom` (In `ReaderZooming:getZoom`):
```
-- calculate zoom value:
    local zoom_w = self.dimen.w / page_size.w - 1e-9
    local zoom_h = self.dimen.h / page_size.h - 1e-9
    if self.rotation % 180 ~= 0 then
        -- rotated by 90 or 270 degrees
        zoom_w = self.dimen.w / page_size.h - 1e-9
        zoom_h = self.dimen.h / page_size.w - 1e-9
    end
```
(Subtract 1e-9 after the divisions.)
There may be a better way, e.g. check if the zoom mode is fit height/width/page (instead of just multiplying the dimension by `zoom`) when calculate the page size.

**Comment by Markismus** [comment]
Why not determine zoom with visible area? 

I am a bit lost, though. In [`ReaderZooming:setzoom`](https://github.com/koreader/koreader/blob/2e15c6cbc0058b243b2b68e909dfddd006acec52/frontend/apps/reader/modules/readerzooming.lua#L275) `self.dimen` is coupled with `self.ui.dimen`, which isn't defined in `readerZooming.lua`. So it's just available? 
If that one refers to the screen dimensions, it would be nice to let it refer to the visible area. I am a bit another loss as to how `kobo.viewport.h` form `device.lua` is available in `Readerzooming.lua`. Yep, can't figure it out, sorry.

**Comment by chrox** [comment]
Probably some `round` operations could save these floating point issues?

**Comment by chrox** [comment]
@markismus The readerui widget is inited with full screen dimension which is then passed to other widgets like readerzooming. The reader app should never know the details of the viewport configuration since the Screen exposed to it is already an abstract screen on which all pixels are perfectly visible. And the Screen will report less width/height if the viewport is configured as so.

**Comment by Markismus** [comment]
Thanks!

**Comment by tarlou** [comment]
Yes, if the result of division is rounded down, the issue will be solved. I don't know a way to do this kind of rounding (unless use some bit operations, which may not be good here) though...
