### ISSUE TITLE
Enhancement request - retain Calibre wireless connection in Spanner menu

### ISSUE THREAD

**Issue by pdo-smith** [koreader/koreader#1531]
Currently:
To establish Calibre wireless connection one must 1) first open a book, 2) enter the 'Spanner' menu and then 3) select 'Calibre wireless connection'

Problem:
This functionality is not available in the folder view as the 'Calibre wireless connection' entry is not shown in the 'Spanner' menu while in folder view mode.

Enhancement:
Retain the 'Calibre wireless connection entry in the 'Spanner' menu when switching to folder view mode.

Benefit:
Calibre wireless connection can be established from either folder view or book view modes increasing the convenience and creating a greater feeling of consistency.

**Comment by chrox** [comment]
Sounds reasonable, thanks for the suggestion.

**Comment by chrox** [comment]
Preferably we will move "Calibre wireless connection" from the reading menu to the filemanager menu as it has nothing to do with the current reading book as suggested in #1871. Close this in favor of #1871.
