### ISSUE TITLE
Kobo Aura HD crash at sleep (sometimes)

### ISSUE THREAD

**Issue by Ebrehem** [koreader/koreader#1535]
Around once every week my Aura HD creashes instead of gonig to sleep, and I am returned to KSM (KSM7). I changed the suspend.sh to the one used in coolreader (consumption is usually lower this way). I assume the error in the crash.log is coming before starting this script:

[util.lua] Could not load rt.so, falling back to gettimeofday.
[33m[W 2015/05/23 10:35:07] _G.__TURBO_USE_LUASOCKET__ set, using LuaSocket (degraded performance).[0m
Segmentation fault 

(It is strange, crash happened today, time of the file is 28 May, 16:57:46. 

Anybody has any solution?

**Comment by Markismus** [comment]
No solution yet, but I see the same behavior without the changed suspend.sh on Kobo Aura H2O. See issue #1498. Also see issue #1485. I am wondering whether the notice of degraded performance might have to do with more than speed issues?

I haven't seen `Segmentation fault` for quite some time, though. Not on the Aura H2O, but I had them with my Aura HD quite a lot, though: Drove me mad! I think I ran a thorough disk check and got rid of most of them. Can't remember whether I did it at the command prompt or via USB and windows....Probably did both and it did decrease the frequency significantly, but didn't solve it entirely.

**Comment by hwhw** [comment]
If a disk check solved it, then probably just by chance. A segfault is a bad memory (as in virtual memory, nothing about physical memory, block devices and/or flash) access. I guess the turbo lib copes badly with connections dying under its fingers...

**Comment by Markismus** [comment]
How do the Kobo device handle swap memory? There isn't a swap partition, right?

**Comment by Markismus** [comment]
But the strange thing is that no turbo seems to be enabled. Could it be that the fallback isn't complete and parts of the turbo code still cause havok?

**Comment by Markismus** [comment]
Let's rephrase that: wouldn't the use of luasocket by turbo be the common factor in all these seemingly random crashes?

**Comment by NiLuJe** [comment]
IIRC, the turbo/luasockets thing is a warning printed right at startup, there may very well be no correlation at all between that the the segfaults.

A proper stacktrace would (probably) be helpful, but running stuff under gdb is *slightly* painful on those devices (and I don't have a gdb build on hand, although it's simply a matter of asking ct-ng nicely ;)).

**Comment by Ebrehem** [comment]
Ah, that explains why the time is far from the day it crashed. And seems to make the solution more remote :).

**Comment by chrox** [comment]
Although I have no evidence that the segfault is caused by turbo, it gives me an impression that more crashes are encountered after we upgraded the Turbo library and used the luasocket/luasec to do all the HTTP(S) requests. Turbo on top of luasocket is a quite new feature in the turbo project and the new feature makes turbo on Android possible. We could be more patient to wait for the evolution of the Turbo project.

We use Turbo to handle async HTTP(S) requests and it will fallback to synchronized requests if turbo is not present. So currently we can make Turbo module totally plugin(out)able by adding an option to disable it.
