### ISSUE TITLE
Look up text selection (multiple words) in dictionary

### ISSUE THREAD

**Issue by jedick** [koreader/koreader#1537]
Can a Dictionary Lookup option be added to the text highlight dialog for multiple-word selections? As an example of the use case, suppose I select the text "ex libris" in a document. It is currently not possible to look up this selected text in the dictionary. It can of course be manually searched by typing the term in the "Dictionary lookup" from the menu (giving matching entries in e.g. Webster's 1913 and Wiktionary), but this is much less convenient than a direct lookup of selected text. There are many English compound words, Latin phrases, place names, etc. where this would be useful.

**Comment by chrox** [comment]
Sounds reasonable, I will add this feature in the following release.
