### ISSUE TITLE
koreader timezone

### ISSUE THREAD

**Issue by lenisko** [koreader/koreader#1539]
Is there any way to change timezone for koreader?
Right now: Kindle software: 00:40 | koreader: 06:40

I'm using Kindle PW2, and last dev version of koreader.

**Comment by chrox** [comment]
It sounds weird. But I did encounter this on my old K3 when my Kindle was not registered. After the device is registered to Amazon I never run into this on all my Kindle devices including K3, KPW and KV. Koreader has no concept of timezone and may not need that as an eBook reading application.

**Comment by NiLuJe** [comment]
I have no friggin' clue how the Kindle UI selects a timezone, but it is indeed highly weird, and doesn't necessarily match the systsme's date/TZ, which, on the other hand, is what KOReader will rely on.

You can either forget the system UI and set date/tz manually the unix way, or try to please the UI by using Amazon's setdate & settz wrapper (with the framework running).

Alternatively, as @chrox mentioned, a quick wireless phone in from a registered device will put things to right.

**Comment by lenisko** [comment]
Well, I didn't registered my kindle nor wan't to. If there is no plans on supporting timezone in koreader settings, I'll try @NiLuJe solution.
Anyway thanks for hints.

**Comment by maciejla** [comment]
For anyone wondering how `settz` works: it expects offset from UTC in _seconds_. So, for example in GMT+2 it would be `settz 7200`
