### ISSUE TITLE
Requested feature - select search in dictionary window

### ISSUE THREAD

**Issue by lenisko** [koreader/koreader#1541]
This might be a good idea.
When dictionary popup is open, sometimes we want to look further in words, eg:
I'm selecting word "pass" in text, my dictionary found it. Inside dictionary popup I see word "enter" and want look in dictionary for it, so it would be nice to select it in dictionary popup, and get answer for it.

**Comment by chrox** [comment]
I like this feature. +1

**Comment by Markismus** [comment]
+1

**Comment by lenisko** [comment]
Idea was taken from GoldenDict

**Comment by Markismus** [comment]
I remember that mobireader for windows allowed me to do this, tol. Was a nice feature, especially with etymology.

**Comment by Markismus** [comment]
This would also allow sdcv to work with dictionaries with synonyms. All what's needed for a synonym is: see: synonym.

See also the discussion on mobilereads.
