### ISSUE TITLE
Kobo Touch (fw 3.11.0): koreader doesn't start at all

### ISSUE THREAD

**Issue by indexless** [koreader/koreader#1545]
Hi koreader users and developers,

Sorry but I've made a lot of attempts to install and reinstall both Kobo StartMenu and koreader, but I still can't get it launched on my Kobo Touch. I made factory reset, then updated it with Kobo Desktop (I'm under OSX if it matters), then installed Kobo StartMenu07 together with all three updates.

Finally I downloaded the last koreader build from https://github.com/koreader/koreader/releases, copied kbmenupng to kobo fs root (the copied png's became visible from nickel, that's nice), extracted 'koreader' folder and copied it to /.adds/. The 'koreader' item appeared in the KSM menu, but when I press it all that I see is FileManger app with contents of root folder listed. Nothing is clickable here, so what I can do is return to start menu by pressing 'Home' on the device.

Also I've installed vlasofsoft with CoolReader included (http://www.mobileread.com/forums/showthread.php?t=240302), and had no problem with launching it. The nickel itself is also launched from menu.

The soft versions I use:
Kobo Touch FW 3.11.0 (4d8eac1207)
Kobo Start Menu 07: http://www.mobileread.com/forums/showthread.php?t=255978
and
Koreader build koreader-kobo-arm-linux-gnueabihf-v2014.11-255-ga30fe26

Thank you for any assistance!

**Comment by Markismus** [comment]
>The 'koreader' item appeared in the KSM menu, but when I press it all that I see is FileManger app with contents of root folder listed. Nothing is clickable here, so what I can do is return to start menu by pressing 'Home' on the device.

I am going to assume that you installed koreader quite alright. However, your problem seems to be that there is nothing clickable. One known problem with Kobo Touches is that the touchscreen has swapped X- and Y-coordinates. So instead of tapping the top-middle for the menu, you should be able to tap the left-middle (or right-middle) for the menu. 

I can't find the easy way to correct that. However, in `frontend/device/kobo/device.lua` in lines 13-17:
```lua
    -- most Kobos have X/Y switched for the touch screen
    touch_switch_xy = true,
    -- most Kobos have also mirrored X coordinates
    touch_mirrored_x = true,
```
there are 2 switches you can try. Just replace `true` with `false` and see whether it helps.

**Comment by indexless** [comment]
Markismus, thanks for your reply.

At first I played with those switches, and nothing happened. Then, immediately after switches I found the following configuration
```lua
local KoboTrilogy = Kobo:new{
    model = "Kobo_trilogy",
    touch_switch_xy = false,
    hasKeys = yes,
}
```
I guessed that they are custom settings that overwrite the general ones, so I've just commented out xy switch, left it switched in general settings
```lua
local Kobo = Generic:new{
    -- ...
    touch_switch_xy = true,
    touch_mirrored_x = true,
    -- ...
}
local KoboTrilogy = Kobo:new{
    model = "Kobo_trilogy",
    -- touch_switch_xy = false,
    hasKeys = yes,
}
```
That helped, and File Manager became responsible in the proper points.

But what should I do now? I clicked on the 'kbmenupngs/' item, and got the popup window with five (ok four, because 'Paste' is disabled) 'Copy', 'Paste', 'Cut', 'Delete', and 'Set as HOME directory'. I definitely don't want to edit anything, so the only options that may be of interest is 'Set as HOME directory'. But I didn't touch it because I don't know what does it (home directory) mean.

Markismus, would you tell me, what is the expected behavior? Should I drop to file manager on calling koreader, or it should be fired on KSM item clicking immediately?

Thanks!

**Comment by Markismus** [comment]
In filemanager you're able to browse the entire filestructure. Normally you select a directory name to enter  subdirectory and '..' for the parent directory. You open a file the same way by selecting it.
Normally koreader starts in '/mnt/onboard'. This is the directory you also see when plugging the USB cable into your PC using Kobo's Nickel.

**Comment by chrox** [comment]
Seems @indexless's problem is that tap gesture is interpreted to a hold gesture in Kobo touch.

**Comment by astro63jp** [comment]
Hi koreader users and developers,
I have exactly the same problem as indexless on my Kobo Touch. When I click on a folder in filemanager I have a window that opens with 4 choices 'Copy', 'Paste', 'Cut', 'Delete', and 'Set as HOME directory' and everything is blocked.I have to reboot the Kobo Touch to come back to Nickel.
Thank you for any assistance!
and excuse me for my english.I am french.

**Comment by houqp** [comment]
Yeah, definitely looks like a gesture recognition issue. @astro63jp @indexleoptions, if you have ssh access to your touch, can you run the reader with debug mode as `./reader.lua -d ./` then do a single tap and paste the output here?

**Comment by sriak** [comment]
Hello, I have the same issue with my kobo touch.
Here is the output of ./reader.lua -d ./ and a single tap : 
```
# initializing for device Kobo_trilogy
# framebuffer resolution: {
        ["h"] = 800,
        ["w"] = 600
}
# show home page
# INFO: invalid widget for setDirty() stack traceback:
        frontend/ui/uimanager.lua:205: in function 'setDirty'
        frontend/apps/filemanager/filemanager.lua:235: in function 'restoreScreenMode'
        frontend/apps/filemanager/filemanager.lua:242: in function 'showFiles'
        ./reader.lua:146: in main chunk
        [C]: at 0x0000bea5
# cache image|resources/icons/appbar.chevron.left.png||
# cache image|resources/icons/appbar.chevron.right.png||
# cache image|resources/icons/appbar.chevron.first.png||
# cache image|resources/icons/appbar.chevron.last.png||
# cache image|resources/icons/appbar.arrow.left.up.png||
# show widget
# triggering refresh {
        ["mode"] = "full",
        ["region"] = {
                ["y"] = 0,
                ["x"] = 0,
                ["h"] = 800,
                ["w"] = 600
        }
}
# refresh: full -1 -1 602 802
# assigned marker 1 to update: {
        ["refreshtype"] = 1,
        ["time"] = 1446994889986.4,
        ["rect"] = {
                ["y"] = 0,
                ["x"] = 0,
                ["h"] = 800,
                ["w"] = 600
        },
        ["waveform_mode"] = 2
}
# key ev {
        ["type"] = 1,
        ["time"] = {
                ["usec"] = 113350,
                ["sec"] = 321
        },
        ["code"] = 330,
        ["value"] = 1
}
# in tap state...
# set up hold timer
# hold gesture detected in slot 0
# in hold state...
# triggering refresh {
        ["mode"] = "ui",
        ["region"] = {
                ["y"] = 322,
                ["x"] = 0,
                ["h"] = 49,
                ["w"] = 600
        }
}
# refresh: ui-mode -1 321 602 51
# update area conflicts with active update 1
# waiting for completion of update 1
# duration: 0
# key ev {
        ["type"] = 1,
        ["time"] = {
                ["usec"] = 169624,
                ["sec"] = 321
        },
        ["code"] = 330,
        ["value"] = 0
}
# in hold state...
# hold_release detected in slot 0
# show widget
# triggering refresh {
        ["mode"] = "ui",
        ["region"] = {
                ["y"] = 322,
                ["x"] = 0,
                ["h"] = 132,
                ["w"] = 600
        }
}
# refresh: ui-mode -1 321 602 134
```

So single tap is indeed detected as a hold.

**Comment by astro63jp** [comment]
Line 360 in .kobo\koreader\frontend\device\gesturedetector.lua
if you change  return self:switchState("holdState", tev, true) TO return self:switchState("tapState", tev, true) it works... except that you don't have holds anymore and can't highlight text.

**Comment by astro63jp** [comment]
I found the solution there:
https://github.com/koreader/koreader/issues/630

**Comment by chrox** [comment]
Koreader has changed a lot since the OP raised this issue, so the problem might already be fixed. Please reopen this if you still have this problem with the latest nightly release.
