### ISSUE TITLE
Question - Is there a way to integrate with Nickel?

### ISSUE THREAD

**Issue by paladini** [koreader/koreader#1548]
Hi, guys!

I'm very new in the e-readers world (bought my Kobo Aura about a week ago) but I've friends that use Kobo for more time and they tell me about KOReader. Now I installed it to my Kobo and I was amazed with your PDF Reflow technology. 

Sorry if this question was already made by someone in a remote time, but there's no way to integrate KOReader with Nickel? I mean, using the Nickel software for everything, but when you open a PDF file ~ tanãaaannn ~ KOReader opens it, not Nickel. This will merge the best of both worlds:

* Only one application. Without needs to change between KSM, Nickel and KOReader.
* Allows high-end users use KOReader
* Solves the Kobo's problem for rendering PDF with your amazing PDF Reflow tool.
* Possibly become an official part of Kobo software later 

There's a way to do that? 
Btw: I only use KOReader for PDF files, I didn't found it GUI much intuitive.

**Comment by frostschutz** [comment]
Barring tricks using inotify (fmon) you'd have to reverse-engineer part of the adobehost.

When you open PDF (or EPUB) in nickel, it starts (if not already running) adobehost-reader. nickel and adobehost reader share a socket and nickel tells adobehost the file location, and adobehost opens it.

You could do a man-in-the-middle and start KoReader when nickel asks adobehost reader to open a file.

Or just fmon/inotify, see if it's adobehost reader that has the file handle (so not to trigger when data base update or search), kill nickel adobehost start koreader with pdf open.

**Comment by chrox** [comment]
Seems no progress, closing it now.
