### ISSUE TITLE
ePub encoding issue

### ISSUE THREAD

**Issue by wxcafe** [koreader/koreader#1549]
All non-ascii characters in ePub ebooks are not displayed, and instead a `?` is shown.
Pretty problematic when reading french books

**Comment by chrox** [comment]
Could you try choosing another font after you turn off the embedded style option? The css in your epub document may specify a font koreader did not find. Or you can send us a link to your document and we will look into this.

**Comment by wxcafe** [comment]
The document won't let me change the font, and when I try to turn off the embedded style, Koreader crashes. I'll upload the document somewhere later today and give you a link if you want

**Comment by wxcafe** [comment]
Okay putting the epub in calibre and then back on the kindle fixed it, I guess it was a problem with the file itself (probably with the stylesheet).
Thanks for the help though!
