### ISSUE TITLE
Kobo Aura H2O crash while suspending after editing (read-only problem)

### ISSUE THREAD

**Issue by cenobitic** [koreader/koreader#1550]
I am using KSM7 Update 3 and Koreader v2014.11-255-ga30fe26 with my Kobo Aura H2O. After selecting some text in a PDF file, I press 'Highlight' in the popup menu. Text gets highlighted. Then I press the physical turn on/off button in order to suspend the device. This causes the reader to go to KSM. Is that a known issue?

The 'crash.log' was empty, so I had to do the steps described [here](https://github.com/koreader/koreader/issues/1485#issuecomment-92264805). What I got in the log file is this:

```
# save default dictionary
# Suspending...
# show screensaver
# writing document to /mnt/sd/test/test.pdf
error: cannot open output file '/mnt/sd/test/test.pdf'
./luajit: ./ffi/mupdf.lua:61: could not write document: cannot open output file '/mnt/sd/test/test.pdf' (1)
stack traceback:
	[C]: in function 'error'
	./ffi/mupdf.lua:61: in function 'merror'
	./ffi/mupdf.lua:232: in function 'writeDocument'
	frontend/document/pdfdocument.lua:152: in function 'writeDocument'
	frontend/document/pdfdocument.lua:157: in function 'close'
	frontend/ui/screensaver.lua:23: in function 'getCoverImage'
	frontend/ui/screensaver.lua:104: in function 'show'
	frontend/device/generic/device.lua:107: in function 'onPowerEvent'
	frontend/ui/uimanager.lua:38: in function 'handler'
	frontend/ui/uimanager.lua:503: in function 'handleInput'
	frontend/ui/uimanager.lua:544: in function 'run'
	./reader.lua:144: in main chunk
	[C]: at 0x0000bea5
```

**Comment by Markismus** [comment]
The relevant line from your logs seems to be `error: cannot open output file '/mnt/sd/test/test.pdf'`. Koreader apparently changes the pdf-file and saves the highlights into the file.

The reason for that is that your sd-card is mounted read-only. A quick workaround is given on [mobilereads by Maltby](http://www.mobileread.com/forums/showthread.php?p=3095655#post3095655):
>To be able to write to and delete from your external drive, including using the File Manager's long press options for deleting files, the mnt/sd must be remounted as read/write. To do so I add this to the koreader.sh file, just before "reader.lua" is called:

>```sh
#remount SD card as read/write
mount -o remount,rw /mnt/sd
```

**Comment by Markismus** [comment]
Maybe it would be nice to have a toggle between `save highlights to pdf` and `save highlights to separate file`. I for one don't want my pdf-files changed and I wonder what would happen with pdf/a-files. Aren't they protected against change or do they just lose their archive status?

**Comment by cenobitic** [comment]
[That](https://github.com/koreader/koreader/issues/1550#issuecomment-111498007) did the trick. Thank you. I for my part would appreciate some kind of feedback that the PDF is in read-only mode. So user would actually know what is happening.

Regarding the toggling mode - I for my part need to save highlights in the actual PDF file, as I am editing it on separate devices. E.g. I add a lot of handwriting with a digitizer. I want the highlights to appear on such devices as well. Keeping them separate would require a merging step prefer viewing them on a separate device. That would be quite annoying on a long term.

**Comment by chrox** [comment]
And increment update of the original PDF file only appends several KB at the end of file instead of rewrite the whole file. It will save a lot of time especially when the file is huge. And it's the recommended way of saving annotation according to the PDF document reference.

**Comment by cenobitic** [comment]
> The relevant line from your logs seems to be error: cannot open output file '/mnt/sd/test/test.pdf'. Koreader apparently changes the pdf-file and saves the highlights into the file.

Sorry, I was mistaken. Currently highlights are saved to /filename.sdr/filename.pdf.lua. So I do not know what koreader is actually trying to save in the PDF. The highlighted parts are not visible in Acrobat Reader on my pc either.

> And increment update of the original PDF file only appends several KB at the end of file instead of rewrite the whole file. It will save a lot of time especially when the file is huge. And it's the recommended way of saving annotation according to the PDF document reference.

That does sound fine with me as long as the highlights are visible in Acrobat Reader and Drawboard. That does not seem to be the case. Is there a possibility to tell koreader to do so?
