### ISSUE TITLE
Help! Koreader cant't be used in andriod 5.0!

### ISSUE THREAD

**Issue by llb1979** [koreader/koreader#1551]
Hi,thank to the writer for koreader.I always use it in my mobile.But andriod upgrade to 5.0，I can't use it again,it is black screen.
Please upgrade this program to fit andrion 5.0,thanks again!

**Comment by hwhw** [comment]
Maybe we need READ_EXTERNAL_STORAGE permissions now? http://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE
