### ISSUE TITLE
Chinese characters in epub not correctly displayed in android version of koreader

### ISSUE THREAD

**Issue by SpikerTest** [koreader/koreader#1563]
Just downloaded koreader-nightly-20150616, installed on my Nexus 4, but when I open an epub file which is in Chinese, I got "???????" everywhere. An interesting thing is that selecting some "??" to lookup in dicts seems work well, i.e. "??" is correctly displayed as Chinese in the pop-up window. 

I have tried to change the language of the interface to Chinese, and also add some fonts that support Chinese, but with no help. 

Hope it can be fixed and koreader can replace other reader on Android!

**Comment by hwhw** [comment]
Koreader does not have a heuristic to chose a fitting font, so you probably need to manually set the font to use. Also, try disabling embedded styles, which may override things.

**Comment by SpikerTest** [comment]
I tried to clear all external styles under the "set render style" menu, and tried several other styles, also change the font under "Change font". Nothing happens. I noted the same file displayed correctly on my kindle paperwhite.

**Comment by chrox** [comment]
Yes, I can confirm this bug. Previously if request font is not found it will fallback to DroidSans Fallback and never show a question mark.

**Comment by chrox** [comment]
Fixed in #1616. Close this now.
