### ISSUE TITLE
Rendering question marks bug, font freezes(PW 2)

### ISSUE THREAD

**Issue by lightevilaster** [koreader/koreader#1566]
Hello!
I would like to report a couple of bugs that I have encountered. Have not yet tried to replicate them with English text, find them in Russian cyrillic.
The first one: When question marks appear at the end of the line are only partly visible. The bug is there with several fonts (appeared in rtf and fb2 files). Here is an example with FreeSerif font: https://dl.dropboxusercontent.com/u/12182892/Screenshot_2015-Jun-21_210552.png Changing margins does not help. Changing the size of the font moves the quesion mark and it does appear, however the problem persists with other similar cases.

The second bug happens when I try to change the font style to some fonts (again tested only for cyrillic).  The device just freezes. Happens for example with HYGothic font.

Thank you very much and I hope the issues will be resolved in further builds
P.S. Is there a way to make screenshots in KOreader?:)

**Comment by Frenzie** [comment]
To make a screenshot you can:
* Tap on diagonally opposed corners of the screen with two fingers at the same time
* Or swipe from any corner to the diagonally opposed corner of the screen on devices without multi-touch support

See https://github.com/koreader/koreader/wiki/KOReader-Gestures

**Comment by lightevilaster** [comment]
Thank you! Reaploaded the file!

**Comment by Frenzie** [comment]
Btw, you can drag pictures directly into the Github reply area. ;)

**Comment by lightevilaster** [comment]
Cool:) Will keep that in mind. Yeah,there is even a tip at the bottom. Need to pay better attention^)

**Comment by chrox** [comment]
This bug is confirmed. Still don't know if it's introduced recently or has been there all the time.

**Comment by lightevilaster** [comment]
Personally I started to notice the bug with the question mark only recently. Have read books before did not see it..

**Comment by frankyifei** [comment]
try this, works for me

```
--- /tmp/n1sejj_lvtextfm.cpp
+++ /home/frank/docs/git/crengine/crengine/src/lvtextfm.cpp
@@ -818,7 +818,7 @@
                             FONT_GUARD
                             int w = font->getCharWidth(lastc);
                             TR("floating: %c w=%d", lastc, w);
-                            word->width -= w;
+                            if (frmline->width + w + wAlign + x >= maxWidth) word->width-=w;
                         } else if (lastc==L'。' || lastc==L'，' || lastc==L'！' || lastc==L'：' || lastc==L'；' ||
                     		    lastc==L'”'  || lastc==L'’' || lastc==L'」' || lastc==L'』' || lastc==L'、') {
                             FONT_GUARD

```

**Comment by lightevilaster** [comment]
I hate to admit I am a noobie here, but I am eager to learn. . I suppose I should add (or rather replace?) this code to the file n1sejj_lvtextfm.cpp and compile it with, em...with something like Eclipse?Unfortunately was not able to find the folder crengine in the nightly builds folder..But anyways, if it is too timely to describe I suppose if it works for you should work for me:)

**Comment by lightevilaster** [comment]
The bug is still there in the new release. Was the pull request created?

**Comment by chrox** [comment]
@lightevilaster Did you try it with the latest nightly build? Does this problem persist?

**Comment by lightevilaster** [comment]
@chrox No, I do not think so, everything seems to be fixed.
