### ISSUE TITLE
How to do more than 1 refresh per page ?

### ISSUE THREAD

**Issue by Fishkilleur** [koreader/koreader#1567]
Hi, i use koreader to read manga in pdf on pocketbook inkpad, it work pretty well except that sometimes, due to the eink screen, some persistant "ghost" of previous page stay on the next page, especially on black area.
If I open a menu to refresh the page the "ghost" effect disapear, so where in the lua code i can add a line to do a full refresh every time a page is swipe ? ( 1 or 2 more than the actual refresh)
Also what is the exact fonction to call to do this ?

Thanks.

**Comment by chrox** [comment]
You probably need to tweak with the `DRCOUNTMAX` variable [here](https://github.com/koreader/koreader/blob/master/defaults.lua#L4-L6) as suggested in the [wiki page](https://github.com/koreader/koreader/wiki/Change-defaults#basic-configuration).

**Comment by Fishkilleur** [comment]
Yes, but this method allow only 1 max refresh per pages , what i want to do is at least 2 refresh per pages.

**Comment by banbanchs** [comment]
Goto setting - screen - E-link full refresh rate, **long press** `Custom X: X page`, enter the number you like

**Comment by Fishkilleur** [comment]
Long press do nothing, and i dont want to do 1 refresh per X page, i want to do X refresh per 1 page.

**Comment by chrox** [comment]
Did you try "refresh on every page" in the menu entry mentioned above? That should be what you want. Note that this page doesn't necessarily correspond to the page number of your PDF document. It's actually the "page/screen turns" you take.

**Comment by Fishkilleur** [comment]
Yep, still not good, i don't think the actual default refresh of 1 per page is good to read manga, like i tell before some "ghost" of the previous image appear on the next, the problem disaper if i tape on the corner top-left, because it does a refresh on the same page. 

Thats why i think i must add a call to a refresh function in the code, but i dont know where and which function.

**Comment by chrox** [comment]
There is shortcut gesture to manually refresh the screen by swiping from top-left corner to the center of the screen. So one gesture to remove the screen ghost.

**Comment by chrox** [comment]
Close this now.
