### ISSUE TITLE
Kindle DXG not loading Koreader

### ISSUE THREAD

**Issue by fabeuw** [koreader/koreader#1568]
I have installed MKK and KUAL, latest versions, I open KUAL, and then Koreader and choose file manager, I tried all three (ASAP, no framework, and regular), then it goes back to the home and I see "starting koreader" but nothing happens. When I choose no framework the kindle reboots but still nothing happens.
Am I missing something?

**Comment by NiLuJe** [comment]
Yep, the KoReader codebase *might* support non-Touch devices, but the public builds certainly aren't targeting those earlier device.

Use KOReader's acenstor, kpdfviewer instead.

**Comment by fabeuw** [comment]
thanks.
