### ISSUE TITLE
PDF text reflow and screensaver

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1569]
This is just a little papercut bug:

When you read a PDF with text reflow the formatting can look quite ugly, but at least you are able to read it comfortable on eink with a decent font size.

Now when you put the device to sleep while you are in the reader the screensaver will display the horrible mangled cover of the PDF. 

But if you put the device to sleep while in the file manager you can the cover page as the PDF god intended. 

So the output of the screensaver changes depending on the context. 

Could you change the screensaver so it always displays the cover of a PDF **without** text reflow?  

This would add visual persistence and the edevice won't lock as bad when in sleep. :)

**Comment by chrox** [comment]
Thanks for the report. This is actually a bug. It should not display the reflowed cover as screensaver.
