### ISSUE TITLE
"Swipe to go back" breaks workflow

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1570]
Some dev-releases back the new "go back" gesture was introduced:

When you read a document on page 25 and press a link that brings you to page 40, you can swipe from left to right and it brings you back to page 25. 

This breaks the workflow of people that use swiping as a primary action for page turns. 

I know it is optional, but imho a core gesture should not conflict with another core gesture that is always activated. Maybe the go back gesture could be changed into an edge gesture.

E.g. if you swipe on the bottom edge.

**Comment by Frenzie** [comment]
+1

I didn't realize it was new though.

**Comment by chrox** [comment]
Yes, I think it's time to remove the swipe-to-go-back gesture. :+1:

**Comment by KenMaltby** [comment]
The "Follow Links" menu items, seem to be working, can't the OP just uncheck "Swipe to go back", now.

**Comment by lightonflux** [comment]
No the problem is the default. It has to be off. Because you have the same gesture that turning a page has. Which is a huge UX oversight.

We have these options:

 * make the feature opt in
 * change the gesture to something isn't used by another function
 * remove the feature

My preference is the second option if we find a good gesture that is easy to remember but hard to trigger accidentally.

Maybe a 180° turn. Like left to right and turning back to left. Like a U turned at -90°.

Am 18. September 2015 15:32:18 MESZ, schrieb Ken Maltby <notifications@github.com>:
>The "Follow Links" menu items, seem to be working, can't the OP just
>uncheck "Swipe to go back", now. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/koreader/issues/1570#issuecomment-141452348

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Frenzie** [comment]
@lightonflux Also see #1008.

**Comment by KenMaltby** [comment]
"Swipe to go back" seems natural, when following links.  If it is removed, it would make the quick check of a reference link, require a menu lookup to return to the flow of the book/document.  The tap the left side AND swipe left to right both go to the previous page, while reading.  For those who Tap, the Swipe is the natural alternative way to go back.  

Not sure there is any set rule, that means anything, as much as a matter of style enshrined in certain web design texts.
