### ISSUE TITLE
Highlights displaced in reflowed PDF

### ISSUE THREAD

**Issue by jedick** [koreader/koreader#1573]
This may be related to koreader#1283 but seems different enough that I started a new issue.

Sample PDF from http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0039743. At the top of page 2, with PDF reflow on, I selected the sentence "In this study ... healthy controls." The highlight appears fine when the highlight dialog comes up:
![pic1](https://cloud.githubusercontent.com/assets/12667794/8511524/84634d62-2345-11e5-891f-b18aa77446a3.png)

After hitting Highlight (Subrayar) the highlight is not placed correctly. It has moved up by a couple of lines:
![pic2](https://cloud.githubusercontent.com/assets/12667794/8511528/d2c12fa6-2345-11e5-8940-f733333a1ba8.png)

The highlight itself is stored at the right location, as shown in the full-page page-flipping mode:
![pic3](https://cloud.githubusercontent.com/assets/12667794/8511531/0a5ffef6-2346-11e5-9945-e1c0a45610e1.png)

A highlight made at a lower position in the page has a greater offset between the real and displayed selection. This picture is a composite image from the second column of page 2 (inverted text - selection active when the highlight dialog appears; lightened text - as displayed after making the highlight; the top of the rendered highlight, not visible here, extends all the way into the first column of the page):
![pic4](https://cloud.githubusercontent.com/assets/12667794/8511542/60f9da70-2346-11e5-83fa-b32c8df587f6.png)

Of possible relevance for debugging: the highlight always moves UP; the offset is often greater for highlights lower in the page. I have experienced this problem only in PDF reflow, for many, but not all, documents including both single- and double-column, and scanned and software-produced documents.

Tested with koreader v2014.11-267-g0b45394.

**Comment by utkb** [comment]
I can repeat this issue on Kobo Glo. Especially when working on academic papers this issue is annoying.

**Comment by jedick** [comment]
A correction to my first post: In nearly every case I find that the displaced highlight moves up, but occasionally I have encountered a PDF where the highlight sometimes moves down. In the PDFs I've been reading this downward movement is quite uncommon.

**Comment by chrox** [comment]
This is not a device-specific problem, the reflow-to-nonreflow coordinates mapping is not 100% precise, especially for two-column layout. I suggest highlighting in the non-reflowing mode in this case.

**Comment by houqp** [comment]
Thanks @jedick for fixing your own issue ;)
