### ISSUE TITLE
FR: Marked as read

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1576]
Hi
It can be very beneficial if one could mark a book (and its sub formats) as read so that we are aware of out progress in the storage library. When the user marks a book as read, KR shows a small icon next to the book or shows it in italics in the file list so that the reader is aware of the status of the bhok. I have hundreds of books on my sd card so this is very beneficial for people like me.
thanks

**Comment by lenisko** [comment]
Good idea ++

**Comment by chrox** [comment]
:+1:  Will add reading progress info in history view.

**Comment by chrox** [comment]
Implemented in #1730, close this now.
