### ISSUE TITLE
FR: Amount of hours spent on a book

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1581]
So that we can have an idea how time time we spend on a book or so.

**Comment by apletnev** [comment]
Added documentation https://github.com/koreader/koreader/wiki/Statistics-plugin

**Comment by gerroon** [comment]
@apletnev 

that looks good but how do I enable it? I downloaded the latest version and I cant figure it out.

**Comment by apletnev** [comment]
By default the plugin is enabled. You can find it in plugins menu section 
![plugins](https://cloud.githubusercontent.com/assets/220872/9965401/bbcd7230-5e3e-11e5-98bb-30b58c08d9b4.png)

**Comment by chrox** [comment]
Close this now since it's already implemented.

**Comment by gerroon** [comment]
Except that pdf is not supported ;(

**Comment by apletnev** [comment]
@gerroon 
Could you please provide example of your PDF? I'll try to implement for PDF's too.

**Comment by gerroon** [comment]
@apletnev 
Any pdf would do it. However you can try this I think
https://archive.org/download/TheCompleteWorksOfHPLovecraft_201412/The%20Complete%20Works%20of%20H.P.%20Lovecraft.pdf
