### ISSUE TITLE
Deinstall

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#1583]
Please add a Wiki item on how to deinstall it

**Comment by hwhw** [comment]
We probably should do that, yes. For starters, it's basically by deleting the koreader folder. All other deinstallation is not koreader-specific but rather specific for the launcher.

**Comment by houqp** [comment]
Yep, as hwhw mentioned, koreader is a "green software" in the sense that it makes no change to the native system.

**Comment by chrox** [comment]
Close this now.
