### ISSUE TITLE
Feature : For user with impaired vision: Variable font-size for progress bar /or/ display progress in menu

### ISSUE THREAD

**Issue by Tormen** [koreader/koreader#1589]
Hi,

I am using koreader on Pocketbook 840 Inkpad E-Reader PB840-X-WW.

My parents can't see well on short distances. So small fonts are a problem. The progress bar is too small and I did not find a way to increase it's font-size in the settings.
Nor did I see a possibility to display the progress information (actual page / total pages, percentage, ...) in another fashion than via the progress bar.

A possible workaround could either be a larger font-size for the progress bar
or the option to display the progress info in the (main) menu 
and ideally the option to change the font-size of this progress info and/or all menu content.

But even by just displaying the progress info in the (by default larger font size of the) menu of koreader it would already be much better !

The built-in ebook-reader had this feature : By default it displays the progress (page and I think percent) in the larger menu font-size.

I know this is not a mass problem, but still an important feature for ebook readers IMHO (we will all get old at some point ;)).

Maybe I missed an existing feature ?

Any hint / help would be greatly appreciated.

Thanks a lot in advance,

Tormen

**Comment by Frenzie** [comment]
I was going to say Gear (third from the left) > Screen > Screen DPI, but it seems like it's always automated even when a specific option is selected. I reckon that's a bug.

Increasing the DPI setting there would make all text larger, but presumably that shouldn't be too much of a problem.

**Comment by Tormen** [comment]
Thanks for your rapid feedback !!

Ah... "DPI setting", yes, I have to check that out!

Otherwise I really liked the feature to display the progress in the menu as well. Like this you would hide the (small) progress bar (at the bottom (and top)) and just use the menu if you need to know your progress info...
