### ISSUE TITLE
Status bar setting should be around the bottom somewhere

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#1590]
See #1219. Putting something that's presumably used only once all the way at the top goes against the menu's usability rationale. A quick peek at the code suggest that's slightly easier said than done.

**Comment by chrox** [comment]
Almost all options in the bottom config panel are related to document rendering (except the "progress bar" option for EPUB document). So I don't think it really make sense to place "Status bar settings" there.

**Comment by Frenzie** [comment]
Not that bottom. :)

Frontlight, Night mode and Network — those are the settings one would use relatively frequently. At the bottom is stuff like Language and Advanced Options that you'd almost never use.

**Comment by chrox** [comment]
I see, currently the menu items are sorted by registration order. We need to add some "index-hint" property to reorder them.

**Comment by chrox** [comment]
I still have no idea why frequently used items should stay at the bottom of the menu. Intuitively I think they should be at the top. Is there any psychological experiment/research of this kind?

**Comment by Frenzie** [comment]
But that's exactly what I said? Frequently used settings at the top, infrequently used at the bottom.

Frequently used:
* Frontlight
* Night mode
* Network

Infrequently used:
* Screen
* Language
* **Status bar**
* Show advanced options

**Comment by chrox** [comment]
Actually I use the status bar settings very frequently since it's not document specific once I read another book I may like to adjust certain display fields to exactly what I want, no more no less. Current items order is pretty nice in my taste.

**Comment by KenMaltby** [comment]
I could see another reason to have the frontlight at the top.  It would be a predictable place to turn on the light, in the dark, for those without a working light switch. Any other placement would be a guess as to the proper place to poke in the dark.

**Comment by Frenzie** [comment]
Fixed in #2601.
