### ISSUE TITLE
Dictionaries not work on PocketBook firmware 4.x

### ISSUE THREAD

**Issue by zlo2107** [koreader/koreader#1591]
For all new releases for pocketbook since v2014.11-173 dictionaries don't work. 

Crashlog:

Atached mqueue: id 8001
./sdcv: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./sdcv)
./sdcv: /lib/libc.so.6: version `GLIBC_2.9' not found (required by ./sdcv)
./sdcv: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./sdcv)
./sdcv: /lib/libc.so.6: version `GLIBC_2.9' not found (required by ./sdcv)

**Comment by Markismus** [comment]
I don't know what it is with my Kobo Aura H2O, but somedays koreader doesn't find any words. After plugging it into the PC, enabling USBnet, starting koreader, voilà, it's working again. Can't find relevant lines in the terminal log though.

**Comment by chrox** [comment]
Koreader on Pocketbook 5.x firmware should have no such problem if you are willing to upgrade your device firmware.

**Comment by Markismus** [comment]
After putting the device in standby for the night, sdcv couldn't find any entries matching my queried words. Returning to KSM and restarting Koreader, fixed this.

Any thoughts on how to debug this?

**Comment by zlo2107** [comment]
Unfortunately there is no 5.x firmware for my (Basic Touch 624) Pocketbook.

**Comment by chrox** [comment]
@Markismus Does `sdcv` be able to find any definition in command line by `./sdcv --utf8-input --utf8-output -nj test --data-dir data/dicts` when it does not work in koreader?

**Comment by Markismus** [comment]
@chrox Thanks for your response. To make that work, I would have to enable USBnet in KSM, wait for it to happen, connect to the PC and check it. 
Nowadays I just quit koreader to KSM, restart koreader and get the dictionary back. Haven't run into this trouble yet with the German epub I created myself, so I'll wait and see.
