### ISSUE TITLE
wonky behaviour of double tap

### ISSUE THREAD

**Issue by quillkiragimmy** [koreader/koreader#1594]
Sometimes when I flip the pages rapidly, the double tap (which is supposed to be disabled by default) seems to be triggered and makes the page zoomed out into center of the screen, the zooming option is unticked. After that, the page will be non-responsive to any page flipping and double taps won't bring it back to the previous state until a zooming option is manually selected again.

It happened with pdf and djvu. Not tested on other formats yet.
My device is Kobo H2O, it is nightly-20150808 release that I'm using.

**Comment by chrox** [comment]
Could you elaborate how to reproduce this? I cannot reproduce it on my Kindle Voyage.

**Comment by jidekene** [comment]
I have a Kobo H2O and I am experiencing the same issue.

**Comment by Frenzie** [comment]
I can't confirm this on my H2O either.
