### ISSUE TITLE
two finger scoll for backlight to sensitive (Kobo Aura)

### ISSUE THREAD

**Issue by lightonflux** [koreader/koreader#1595]
Just started nickel after a long time and realised that the two finger scroll gesture that changes screen brightness is toooo sensitive  in koreader and it is really hard to change the value easily. 

If you move your fingers 3cm in koreader you can change the brightness from 0% to 100%. This makes it really hard to change the brightness -/+5%.

In nickel it is just easier, because your finger need to travel a longer distance to make big changes.

**Comment by Frenzie** [comment]
Is this still an issue?

**Comment by lightonflux** [comment]
Will test again with newest dev.

**Comment by Frenzie** [comment]
Also note #2284.

**Comment by lightonflux** [comment]
Much better. 
Only issue that is left: You can only initiate one change. E.g. when going up from 50 to 90 you can't move down to get back to 70 in one motion. You need to lift your fingers. In nickel you can move up and down without lifting your fingers. Not sure if this is a feature request for another issue. :)

**Comment by lightonflux** [comment]
#2284 works too. But both moving gesture could use some fine tuning.

**Comment by lightonflux** [comment]
Just made sure that i have the latest dev again. Now there was an update (has some wifi issues before).

Now de- and increasing brightness in one motion works. But it flickers very much. And the delay is a but too much. Will open a new issue for this.
