### ISSUE TITLE
Pocketbook Inkpad 840 - Blank screen after 5 minutes

### ISSUE THREAD

**Issue by patrikmusic** [koreader/koreader#1596]
Hello,

I would like you to ask you for help with koeader.
I have encountered an issue with my Inkpad 840. There seems to be a screen refresh of sorts around 4 minutes after whatever my last action was, then another about 5 minutes later and so on. This also seems to cause koreader to turn the screen white. I read a lots of scientific pdfs and demand of reading time for each page is much bigger. All power saving features are turned off, the "Complete Page Refresh" setting has no effect. Default pdf software and Coolreader can handle this with no white screen.

I have written to PB support and they said, that this refreshing issue will be repaired on next firmware, but to be honest, there will never be. Thanks.

**Comment by YudiShun** [comment]
Hello,
The issue is solved with the new upcoming firmware. I have tried with the beta and works fine.

Thanks

**Comment by patrikmusic** [comment]
Hello,

great message. I am looking forward to it and hope, there will be
possibility to choose a reading app, like in older fw.
Thank you for info and have a nice day.

Patrick
Dne 3. 11. 2015 11:29 napsal uživatel "YudiShun" <notifications@github.com>:

**Comment by patrikmusic** [comment]
Hello,

do you know when the new fw for PB Inkpad will be available? Or can you
please share beta version with me?

Thanks
Patrick
Dne 3. 11. 2015 11:38 napsal uživatel "Patrik Havlán" <
havlanpatrik@gmail.com>:
