### ISSUE TITLE
Set koreader to never use external stylesheets by default

### ISSUE THREAD

**Issue by baudtack** [koreader/koreader#1601]
Is there a way to force koreader to not use external stylesheets by default? I can remove them when in reading an epub but they keep returning.

**Comment by Frenzie** [comment]
Is there an easy way to test this? It looks like there's no global setting for this, which should be easy enough to add, but I need to make sure I do it right. :)

**Comment by Frenzie** [comment]
The above is not a complete fix. It only enables saving this setting on a per-document basis, but I noticed a rather disturbing issue that the style choice isn't necessarily saved at all. I might implement a global setting first because it's easier to do.

**Comment by baudtack** [comment]
Cool. For me the real issue is mostly the justification. I guess I could just change a stylesheet, but I'm kind of in the habit of setting what I want when I strip the drm off books.

**Comment by Frenzie** [comment]
I added global settings to the PR in the meantime. 

On August 25, 2015 6:18:52 PM GMT+02:00, David Kerschner <notifications@github.com> wrote:
>Cool. For me the real issue is mostly the justification. I guess I
>could just change a stylesheet, but I'm kind of in the habit of setting
>what I want when I strip the drm off books.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/koreader/koreader/issues/1601#issuecomment-134657343

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
