### ISSUE TITLE
Default zoom and contrast

### ISSUE THREAD

**Issue by woky** [koreader/koreader#1603]
Hi.

It'd be nice if I could configure default zoom and contrast in defaults.lua.

I want the zoom to be "Fit Content Width" and contrast to be "Darker" for 99% of documents. Now the settings apply to current document only. It's kinda tiresome to do it for every document, especially if the book chapters are split into separate PDF files

I'm sorry for wasting time if this is already possible, but I couldn't find anything relevant in defaults.lua nor in Google.

**Comment by Frenzie** [comment]
Long press to default. ;)

**Comment by woky** [comment]
@Frenzie Very nice. Now it feels so natural. Thank you!
