### ISSUE TITLE
Screensavers

### ISSUE THREAD

**Issue by baudtack** [koreader/koreader#1605]
It would be nice if I could just pick a screensaver image or several images instead of using the book covers.

**Comment by thebombsauce** [comment]
I agree this would be a great feature.

**Comment by KenMaltby** [comment]
Indeed, it is, in the Kobo version of Koreader.  It is even included in the "Advanced options" and is turned on buy unchecking the "Use this book's cover as screensaver"  option of the Reader menu's "Screensaver" option.  The Advanced option that you use to point to the image file you want to use is: KOBO_SCREEN_SAVER = ""  (poking the uppercase option name will bring up a message window & keyboard to enter the address of your image file,  you start at /mnt )

The logic for this function seems to be that with the  "Use this book's cover as screensaver"  option checked for a book, the cover of the book will be used, if there is one.  If there is no cover available, then your defined image file will be used.  If neither a book cover or a defined image is available, then the Message window with "Suspended..." is displayed.  If the "Use this book's cover as screensaver"  option is unchecked, then your defined image file will be used.  If there is no defined image then the Message box is used.  

Luck;
Ken

**Comment by Frenzie** [comment]
And notice it can be either an individual image or a directory (see [here](https://github.com/koreader/koreader/blob/63fb8af937c7b011c01e090f91e78954bd341e0e/defaults.lua#L177)). But perhaps it might make sense to stick a couple of pictures in e.g. /data/screensavers and enable it by default? Not that I mind the "suspended" message or anything.

**Comment by KenMaltby** [comment]
If you used a directory of pictures, how are they used?  Is it a random selection, is it always the first one?

**Comment by baudtack** [comment]
It's random.

**Comment by chrox** [comment]
Seems already implemented for kobo devices. Closing this now.
