### ISSUE TITLE
Bad detection of kobo touch touchscreen

### ISSUE THREAD

**Issue by boul51** [koreader/koreader#1608]
Hi, my kobo is a kobo touch. Apparently there is an issue with touchscreen detection on it. I had to manually set manually touch_switch_xy to true in file frontend/device/kobo/device.lua :
-- Kobo Touch:
local KoboTrilogy = Kobo:new{
    model = "Kobo_trilogy",
    -- nboul modif: set to true
    touch_switch_xy = true,
    hasKeys = yes,
}
It's no big issue for me, but if I can help giving you some information about my device, please let me know. Thanks for this nice piece of software anyway !

**Comment by Frenzie** [comment]
Pinging @gontofe @ottischwenk from #1374

**Comment by Frenzie** [comment]
I'm reopening this on account of this message in the forum: http://www.mobileread.com/forums/showpost.php?p=3212986&postcount=2499

> I just tried [the new stable] on my Touch C. After installing the most recent nightly build, I followed the instruction and pressed the top right corner. Still, the touch coordinates do not match.
>
> Edit: I am not sure what exactly the reasoning behind the test is. I just report what I am observing. When I am asked to touch upper right corner, and I touch somewhere on the lower half of the screen, nothing is happening. If I touch anywhere on the upper half the touch is registered and ["kobo_touch_switch_xy"] = false gets written to settings.reader.lua.

**Comment by Earnestly** [comment]
I had to make the same changes to `frontend/device/kobo/device.lua` for the touch coordinates to match the location I was physically pressing.

**Comment by houqp** [comment]
@Earnestly , can you elaborate why changes you made in device.lua for kobo?

**Comment by Earnestly** [comment]
@houqp I made the changes to `device.lua` because, as I said previously, the coordinates koreader responded to were misaligned to where I had actually touched the screen.  This issue being one of the few reports about it with a solution, I tried it.

So yeah, I changed `touch_switch_xy` to `true` in the `local KoboTrilogy = Kobo:new {}` block as @boul51 did which fixed the situation.  It's been working fine since then.

**Comment by houqp** [comment]
@Earnestly can you do us a favor by testing with the following steps?
* temporarily remove your patch in `device.lua`
* remove `kobo_touch_switch_xy` in `settings.reader.lua`
* start your reader and touch the probing porint
* check the value of `kobo_touch_switch_xy` in `settings.reader.lua`

It everything goes correctly, you should be able to see the value of that config set to `true` and you won't need to apply your `device.lua` patch anymore. If not, that's a bug.

Theoretically, to map from one 2D coordination to another, we need at least three probes. But looking at our kobo porting code, there are only two cases: switchXY and mirrorX. This means we will still need at least two probes to get the correct mapping. That said, it doesn't seem like what's causing the issue in your case. For you, setting `kobo_touch_switch_xy` to `true` in `settings.reader.lua` should really do the trick even if there is a bug in the screen probing code.

**Comment by Earnestly** [comment]
As in the forum post @Frenzie added, my situation seems to be identical. Setting `kobo_touch_switch_xy` to `true` in `settings.reader.lua` has no effect, even recreating the entire koreader installation from scratch and touching the probe point results in that `kobo_touch_switch_xz` key being set to `false` and again changing it to `true` has no effect.

Unfortunately the only setting which worked was editting `kobo/device.lua`

**Comment by houqp** [comment]
Thanks @Earnestly for the info, looks like the code is broken in two places (both probing and initialization), I will take a look tonight.

**Comment by houqp** [comment]
Ha, I know what's wrong in the probing logic now. I will send out a patch tomorrow. It's bad time here now ;)

**Comment by Earnestly** [comment]
Um sorry, I updated to a version with this committed fix and removed `kobo_touch_switch_xy` from `settings.reader.lua` to trigger the prompt.

Now I get prompted to "Tap the lower right corner" when starting koreader but tapping that location does nothing, the prompt remains.  Tapping the lower left does nothing, the upper right and left gets incorrect behaviour again.

However at least now setting `kobo_touch_switch_xy` to `true` explicitly in `settings.reader.lua` is enough to correct this without having to touch the `device.lua` file.

**Comment by houqp** [comment]
Looks like the touch probe script just ignores all touches from the bottom half of the screen :(

Can you try removing the range key from the TapProbe event?
https://github.com/koreader/koreader/blob/master/utils/kobo_touch_probe.lua#L48

I think the raw touch input is outside of that registered range area (because of switched x & y).

**Comment by Earnestly** [comment]
Removing `range = Geom:new { ... }` seems to have solved it, I can now touch the lower right corner and the touch locations match up. \o/

**Comment by houqp** [comment]
Thanks @Earnestly and @boul51 for helping us debugging the issue :)

**Comment by Earnestly** [comment]
Thanks for the quick fixes too o/
