### ISSUE TITLE
Fail to go back or go forward to next page

### ISSUE THREAD

**Issue by qdwang** [koreader/koreader#1610]
The kindle original software works all right. Using koreader to open other pdfs works all right. Its just fail the page turning in my current reading book. Any explanation here?

**Comment by chrox** [comment]
It sounds like a rare bug that I encountered before just trying to swipe left or right to turn over that page then it will turn normally by tap. I suspect the bug has something to do with page dimension calc. Needs further investigation.

**Comment by chrox** [comment]
I found this issue is duplicated to #1315. Closing this issue in favor of the first raised one.
