### ISSUE TITLE
settings.reader.lua is reset when I restore an old one

### ISSUE THREAD

**Issue by boriar** [koreader/koreader#1612]
It's bored to select all settings again and again when I do clean install of koreader so I try to config everything and make a copy to restore it every new install. But when I start koreader always delete the restored file and create a new one.
Is it posible to implement a setting.reader.persistent.lua or something similar that I can copy from an install to other?

**Comment by Frenzie** [comment]
On what platform is this?

**Comment by boriar** [comment]
Sorry! My fault.
I use a Kobo Aura H2O

**Comment by Frenzie** [comment]
I have an H2O as well. So you're saying that if I deleted my KOReader folder (or renamed it to koreader.whatever), stuck on the latest stable or nightly, and copied in my old settings.reader.lua, it'd be overwritten? 'cause I don't seem to have any issues swapping that file in and out in the emulator.

**Comment by boriar** [comment]
Sorry. Seems that the problem was the program that I used for automatized the update. For an unknow reason (by now) the file always was corrupted in the process.

Thanks for your quick answer.

**Comment by Frenzie** [comment]
I'll close this then. Btw, what's the program you used for the automated update? You mean like a cron job or something?

**Comment by boriar** [comment]
Don't worry about the program. It's a simple homemade to simplified my mixture of some programs to make an update file for my kobo. Nothing special at all.
BTW Thanks to try and pointed me about the problem. All correct now
