### ISSUE TITLE
Android: unable to enable "E-ink full refresh rate" option

### ISSUE THREAD

**Issue by fxshpac** [koreader/koreader#1613]
Hi All,

My device is an Android based e-ink tablet model number i86ml made by Onyx. I have been running the latest beta release in great success thanks to all your great work with exception of one issue. The stock reader that comes with the device does full screen refresh on each page turn and I want to enable the same in koreader. So I go to "Screen" menu, tap on "E-ink full refresh rate" and on "Every page". After backing out of the menu, I make a few page turns to test out, there is no full screen refresh happening. So I go back to "Screen" menu, sure enough, "E-ink full refresh rate" is not checked, instead, "E-ink optimization" is checked. So it appears to me koreader is unable to enable "E-ink full refresh rate" at all.

So my question is how to enable this option my device in koreader to allow full screen refresh on each page turn. My wild guess is that koreader may think the device is not allowing such function therefore not allowing the option to be checked in the menu.

Feel free to let me know if you need any further data to help investigation.

Thanks

**Comment by KenMaltby** [comment]
"E-ink full refresh rate"  doesn't get a check mark, it takes you to a page where you can select how many pages between full page refreshes.  I think you will find that if you select it  and then select "Every page", the every page selection will remain checked.  If you want you can set a Custom page refresh by Long Pressing on one of the three Custom # settings. (You will get a message box & keyboard to make your custom setting.)  

Luck;
Ken

**Comment by fxshpac** [comment]
Thanks for your explanation Ken. I checked the menu again and saw that "Every page" was already checked. So the menu is set correctly but still there is no full screen refresh on page turns. Anything else you can help me to make it work? Thanks in advance.

**Comment by KenMaltby** [comment]
There is a setting in the advanced settings/defaults:  "DFULL_SCREEN = 1"  But if the setting is checked in the menu, it should already be set.  You set it by longpressing on the upper case name of the setting. When you are done and you use the "Home" icon to exit Koreader, you should see a message box giving you the option to save your settings.

**Comment by fxshpac** [comment]
Yes "DFULL_SCREEN" is already set to 1 in Advanced Settings/Defaults. And I did restart the app multiple times and still there is no full screen refresh. Do you think it's possible that the app is not using the right API to trigger that? I can help debugging it to find out more on that.

**Comment by KenMaltby** [comment]
OOps, that is the wrong setting, I should have used "DRCOUNTMAX = 1"  (It is even the first one in the defaults.lua.)  If you open defaults.lua in Notepad++, you will see the advanced/default settings and very helpful descriptions of the settings.   You should also have a "defaults.persistent.lua" file that you should copy the defaults.lua into, so those settings won't be overwritten when you update the koreader folder.

**Comment by fxshpac** [comment]
I went ahead and changed DRCOUNTMAX from 6 to 1 and confirmed the value change by restarting the app and check the value again. Unfortunately the new setting still doesn't help. Let me know if there is anything else that I can try. Thx.

**Comment by chrox** [comment]
Currently we cannot set screen refresh mode on Android, the "E-ink full refresh" option is only for kindle, kobo and pocketbook devices.

**Comment by KenMaltby** [comment]
Since e-Ink devices that run Android are still rare birds, and that the screen refresh might be expected to be addressed in the OS adaptation to the hardware requirements, you might find that "Onyx" support should provide some answer, to this issue.  Or whoever supplies firmware for the device.

**Comment by fxshpac** [comment]
@chrox @KenMaltby Thx both for the inputs. If I can find out the API to control the screen refresh on Android would you like to consider supporting it in koreader?

**Comment by KenMaltby** [comment]
Perhaps the title should be changed to "Android: Unable to enable "E-ink full refresh rate" option"
