### ISSUE TITLE
Change progress sync server URL

### ISSUE THREAD

**Issue by vaemendis** [koreader/koreader#1619]
Hello,
is there a way to change the progress sync server URL in Koreader ?
I'd like to use my own instance of [koreader-sync-server
](https://github.com/koreader/koreader-sync-server).

**Comment by KenMaltby** [comment]
It looks to be at:  \.adds\koreader\plugins\kosync.koplugin\api.json .  ( might be good to know as I am currently finding "bjmu.edu.cn" unreachable.)
Luck;
Ken

**Comment by vaemendis** [comment]
Well, I meant without having to rebuild or repackage the application.

**Comment by chrox** [comment]
Yes, just editing the json file will do the work and there is no need to rebuild or repackage. But the changed file will be overriden by the next upgrade, so it's better to have a persistent config file for it.

**Comment by vaemendis** [comment]
Thank you both for your answers.

**Comment by vaemendis** [comment]
I tried to modify it in the apk, but it won't install anymore after I replaced the address.
I'm not familiar with apk packaging, but I guess a checksum somewhere might not match anymore after my modification.

**Comment by chrox** [comment]
If your Android device is rooted you can edit the file "/data/data/org.koreader.launcher/files/plugins/kosync.koplugin/api.json" directly. Otherwise, you have to build the apk yourself before there is a special option to set custom url for progress sync.

**Comment by KenMaltby** [comment]
So, you are talking about the Android version of Koreader?  You need a tool like "EasyApkDisassembler" to sign the .apk, after you make changes.  

I find it in the disassembled "assets>module>koreader-g??????.7z>plugins>kosync.koplugin of a downloaded nightly apk.

**Comment by vaemendis** [comment]
It worked. Thanks !
