### ISSUE TITLE
How well are we supposed to behave on non-Touch devices?

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#1623]
I've been playing around with my build machine to semi-automate KOReader builds with my TCs, and I decided to go the extra mile and try out the good old K3 TC...

After a few tweaks to the buildsystem, I finally got something that didn't pull anything newer than GLIBC 2.5, and as such ran properly on a random K3.

Which leads me to my question: how well is that kind of setup supported? Right now the FM works properly (I just couldn't find a way to make the menu pop up), but as soon as you open a PDF or ePub, you lose any kind of input method.

Nothing's crashed, the first page is rendered correctly, you just can't do anything with it. Sending a SIGTERM to luajit is the only way to quit KOReader.

So... yeah. Did I break something, or is this the expected behavior?
If it is, what would it entail to make this work, and finally retire KPV?

**Comment by NiLuJe** [comment]
Okay, it tends to work way better when we listen to the right input devices ;p.

**Comment by houqp** [comment]
Yeah, koreader should be able to run on K3/DXG without issues. I had it running on my DXG too. It's just reeeeeeaaaaly slow :(

**Comment by NiLuJe** [comment]
It's working pretty well on my K3, FWIW :).

[Here's the package](http://files.ak-team.com/niluje/kopub/koreader-kindle-arm-kindle-linux-gnueabi-v2014.11-309-gf674c82.tar.gz) for those adventurous enough to try at home ;).

I'll check on a K2 too. I guess the issue on the DX/DXG might be the larger resolution putting more strain on the CPu?

**Comment by NiLuJe** [comment]
Indeed, it's not particularly snappy on a K2 ;).

It's far from unusable, though, but on the larger screen of the DXs, who knows...

**Comment by NiLuJe** [comment]
There's a few unusable UI elemtns though.

One of them is the confirmbox (no key mappings). Not familiar enough with it to fix that ;'(;

**Comment by Googlerez** [comment]
Ok, on DXG, runs a bit on the slow side but that doesn't mean it's not usable. It indeed opened a huge PDF file just fine. So, I'm going to say it is usable in a production system too.

"Menu > Settings > Show advanced options" doesn't do anything?!

I haven't faced SIGTERM issue, NiLuJe!!! ?

**Comment by NiLuJe** [comment]
@Googlerez:

Yep, the advanced options menu is one of those UI lement that's currently not wotking ;à.

1. I meant that you need to SIGTERM luajit when you hit some broken UI widget with no key mapping.
2. git master
3. lol ^^. See 0. ;).

**Comment by Googlerez** [comment]
@NiLuJe Oh I see.

It's a good sign, that even on my DXG v2.5.8, when I open a Persian mobi/epub, the characters are actually shown in KOReader (though disjointed and LTR).

And great, accidentally hit an AZW book and nice, to my surprise, it opened! :)

**Comment by houqp** [comment]
The document rendering speed should be the same since we are using the same rendering backend for both projects. It's just the new koreader UI is slow, the user interaction is going to be slow, i.e. time between menu show up after key presses.

Confimbox one should be easy to fix. Just need to register key press events to buttontable. I don't have my dev laptop with me right now. If no one beats me, I can work on it after I get back home in 3 days.

**Comment by Googlerez** [comment]
I'm reviewing the project to get a handle of it. Would watch closely and hope to contribute a thong or two in future.

UI slowness doesn't really annoy me though, all in all it's good. Appreciated.

**Comment by Googlerez** [comment]
@NiLuJe "If it is, what would it entail to make this work, and finally retire KPV?"
We have to make sure this is a merger, meaning if there are any feature in KPV that are not yet part of KOReader for non-touch devices, we should stuff them as much as possible before saying goodbye.

**Comment by houqp** [comment]
OK, I will be working on this today, should be able to get it by the night ;)

**Comment by houqp** [comment]
Advanced menu should have been fixed for keyboard devices now. Feel free to give the latest master a try :)

**Comment by Googlerez** [comment]
Sorry for getting back to you late!
I just tried the latest nightly of master branch on my K3 and it gives segmentation fault (because of luajit): https://github.com/koreader/koreader/releases/download/v2015.10.24-nightly/koreader-kindle-arm-linux-gnueabi-v2014.11-415-g5dc899f.zip

I replaced it with the Luajit that is supposed to work on K3 but still it doesn't work. It stops and resumes cvm and exits the shell.

**Comment by NiLuJe** [comment]
@Googlerez: That's to be expected, none of the official nightlies target legacy Kindles.

[These do](http://www.mobileread.com/forums/showpost.php?p=2658945&postcount=2) on the other hand ;).

**Comment by Googlerez** [comment]
Oh yes yes yes! You're the man.

**Comment by mergen3107** [comment]
Are you planning to update the build for Kindle 4?
I can see that the last update was in July 2016, which is good!

**Comment by houqp** [comment]
Try the koreader-kindle-legacy-arm-kindle build. I believe they should work for k4.

**Comment by mergen3107** [comment]
@houqp 
Can you please tell me, can I remap buttons for Kindle 4 NT? For example, if I want to assign 'Page reflow' to the left turn page back. Similar tweak I can see [here](https://github.com/koreader/koreader/issues/1898), but for adding menu items.

Can I do highlights on Kindle 4 NT?

Thank you! I appreciate your support!

**Comment by houqp** [comment]
Remapping reflow to another key is probably not a good idea given you don't have that many keys on K4. How can turn backwards? But if you really want to do that, you can insert the reflow code in `function ReaderPaging:onPagingRel(diff)`. in `reader/modules/readerpaging.lua` file.

I don't think pocketbook build will work on kindle. K4 is only compatible with softwares built for K3 and DXG.

**Comment by mergen3107** [comment]
@houqp 
I think about the Next/Prev keys as about key with 4 different keycodes (as on Nook Simple Touch).
I have to check, will try very soon (after my finals). Since I usually use only right-hand side buttons, the two on the left are staying without a function.

Thank you for suggestion of code!

**Comment by houqp** [comment]
@mwoz123 I would recommend you make that feature accessible from the menu though. It's not a frequent action to perform, only once per book. By adding it to the menu, other devices like K3 and DXG will be able to use it too.

**Comment by mergen3107** [comment]
@houqp 
OK, I'll try soon!
Thank you for your support!

**Comment by Frenzie** [comment]
With #3796 merged much functionality is now accessible, so I'll close this and #1898. This has now become the territory of targeted specific bugs instead of a generic notion that it's not working.
