### ISSUE TITLE
andriod force stop

### ISSUE THREAD

**Issue by goodboy2men** [koreader/koreader#1629]
can not open any pdf books file floder.  always force stop！ samsung note3 ，andriod 4.3

**Comment by gerroon** [comment]
goodluck with koreader on android. Koreader on Android sucks to death.

**Comment by KenMaltby** [comment]
@gerroon 
That is quite a change from your post on the older Koreader Android version.  The Android version has almost always worked great on my Asus EEE Transformer TF-101 running 4.0.3.  The Android implementations and hardware/firmware differences make it unlikely that any team, without access to a large sample of devices, could get a complex program working on "all" Android devices, in a short time.

If you can describe the shortcomings you see they could be looked at, and possibly addressed.  Just saying that it sucks, gives no one anything to work on. Remember though that the developers work on things that interest them, there is no money back guarantee that it well work on your device, in the manner you wish it to.

Luck;
Ken

**Comment by gerroon** [comment]
KenMaltby

Yes that is the only version that works on my Boyue. Any other versions crash or never start on none of my tablets (I have 4 Android tablets and 1 Einks Anroid device). 

I tried that old version on normal Android tablet and it is as crashy however I am still happy that that aprticular version works on my Eink Android device reasonably.

**Comment by chrox** [comment]
Since there is no additional info about this crash I will redirect this to #1643 for better discussions.
