### ISSUE TITLE
how to open pdf document with koreader default

### ISSUE THREAD

**Issue by analysisky** [koreader/koreader#1631]
when I open a pdf document,system always open it with native system. I want to change it to koreader,what should I do？

**Comment by Frenzie** [comment]
Is that on Android?

**Comment by analysisky** [comment]
On my kpw2

**Comment by chrox** [comment]
Please refer to this wiki page https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#installation. You need to install kpvbooklet if you want to open pdf with koreader directly in kindle's home screen.
