### ISSUE TITLE
Pocketbook Inkpad 840 - Blank screen after 5 minutes

### ISSUE THREAD

**Issue by YudiShun** [koreader/koreader#1632]
Hello, I am having the follwing issue

***Environment tested
a. Using Koreader upto the lastest version "koreader-nightly-20150911", under Inkpad 840 (Firmware 4.4 and 5.4 as well)
b. Power management ("Lock Device After" / "Power off After") either on or with some values

***Bugs encontered when reading pdf/epub.. with koreader: the screen goes blank after 5 mns. The power management hasn't taken over as this happens even when the power management is off. Besides, when touching the screen, koreader reads the input and triggers the action that is associated with the touch (menu area if touching menu area, turn page if turn page area..).

***If the bug can not be corrected, is there a way to turn the timer to 60mns(so the powermanagement can take it over when setting them shorter)? 5 mns is too short when using a page as reference page while doing other things :-)

Thanks.

**Comment by chrox** [comment]
This seems duplicated to #1596 though the issue title is more informative. Close this now and redirect to #1596.
