### ISSUE TITLE
Planned features, any suggestions?

### ISSUE THREAD

**Issue by chrox** [koreader/koreader#1634]
* Grid layout history view with book cover in file manager

* Zooming mode to support multi-columns page layout

* OPDS authentication (implemented in #1637)

* [Wallabag](https://github.com/wallabag/wallabag) integration as a read-it-later plugin

* Ubuntu touch support (implemented in #1660)

These features are planned, any suggestions?

**Comment by thebombsauce** [comment]
Column zoom for pdfs?

**Comment by chrox** [comment]
Yes, of course.

**Comment by KenMaltby** [comment]
How about simple password authentication for the Local calibre catalog OPDS?

**Comment by lenisko** [comment]
https://github.com/koreader/koreader/issues/1541 Deeper search in dictionary window
https://github.com/koreader/koreader/issues/1547 Passworded ZIP support
https://github.com/koreader/koreader/issues/1575 Enable adding notes between pages

**Comment by Markismus** [comment]
#1095 Notes
#1420 Create dictionary/font resources 

(P.S. "planned" instead of planed: (of a boat) to rise partly out of the water when moving at high speed? Or did you mean to really overdrive koreader development?)

**Comment by Frenzie** [comment]
Wallabag can [create an RSS feed of its contents](http://doc.wallabag.org/en/User/rss_feed.html), but it doesn't include a feedreader.

#1524 NEWS (RSS/Atom) plugin to Koreader ?

PS Password authentication in OPDS is #1001.

**Comment by gerroon** [comment]
Wallabag integration would be great!

**Comment by houqp** [comment]
The UI framework is probably also due for some refactor. We need to get rid of the `widget:_init()` and `show_parent` hack. Would be nice if we can also make the API more user friendly so it's easier for people to contribute.

Improve the setting/history flushing process so we can have the confident that the reader can always restore to previous state after a crash. Currently, user can only tweak AUTO_SAVE_PAGING_COUNT, which only saves settings on page turns and flushing the whole setting every time is an expensive process. This should not be a configurable option, it should be a default that every single user action is saved to filesystem.

**Comment by houqp** [comment]
Also this one: https://github.com/koreader/koreader/issues/1356

**Comment by Markismus** [comment]
Ah, forgot about #1356! 
I agree with houqp _make the API more user friendly_. I would like to extend it to a friendlier description of the organization of the frontend and in particular 'readerui.lua.' 

I've been trying to hack notes into koreader, but I usually find myself without time before I got any programming done: all is usually lost in analyzing how the highlights are implemented. Two small girls and not enough sleep wreaks havoc on my memory, so usually I have to start all over again, when I get to it after a few weeks.

If someone would like to give me a few pointers where to start hacking notes into koreader, it would be much appreciated.

**Comment by gerroon** [comment]
How about giving some love to Android compability? It seems like KR is stable on a margin of the Android devices. I mean I personally prefer slower but non crashing KR on Android. KR was not as unstable as this. Somewhere along end of last year something has changed.

**Comment by houqp** [comment]
@Markismus , You don't really need to understand how the highlight works. The hardest part will creating the UI component to compose notes. Then you only need to hook that UI up with "Add Note" button.

@gerroon If you have the device to reproduce the crashes, can you help us find out which release introduces the unstability?

**Comment by Markismus** [comment]
@houqp Yes, I know, especially the hard part! :)  
I was thinking that some of the programming would be analogue to the highlighting. Understanding how that works, would allow me to expand it to introduce the UI component.

**Comment by utkb** [comment]
#1573 True highligting on PDF's

**Comment by gerroon** [comment]
@houqp 

Sure I can try to help. I have like 6 Android devices and all are different configuration brands. And KR crashes on all of them. The common thing is that alla re using Cyanogenmod except the Eink one.

**Comment by Frenzie** [comment]
Made me curious. KOReader works like a charm on my phone ([LX](http://legacyxperia.github.io/) cm-12). Nothing like #1642 either. I wonder what the difference is.

**Comment by utkb** [comment]
#1008

**Comment by fxshpac** [comment]
#1613 please

**Comment by YudiShun** [comment]
Feature Request : Bookmark Folders and fast access to them

What about implementing bookmarking forders, like "history" for read ebook.
In some cases, we have a lot of folder and sub folders and in most cases in SDCARD, as of now it may take a lot of click and clicks to reach the wanted forder; having a bookmarked folder list will help a lot to fast access the wanted folder.

Thanks!

**Comment by andrego** [comment]
The only reasons I ever find myself booting out of koreader (into nickel) is to use the file manager.  For actual reading, I find koreader superior in every way.

The current file manager certainly works well for basic use.  Here are a few ideas for some "luxuries" that could add some utility and to the ease of use.

- in addition to the current folder view, add the ability to create & display collections of books on the device (or via editing a file, calibre plugin, etc) so books could be organized and located in multiple ways.  This would make locating books in larger libraries much easier.
- option to choose between the current (folder) view or metadata (collections) view "on the fly".  This would satisfy those who might prefer one view over the other.
- option to show book covers in file manager.
- include series metadata info (book #, series name) in a smaller font below the file name
- option to sort within a folder or collection by file name or series number & name so it is easy to identify and open the next book in a series

**Comment by BasedMan** [comment]
Please consider supporting digest authentication, which is the method that the calibre content server utilizes.

**Comment by chrox** [comment]
I find it not good for issue tracking and moved unimplemented features to separate issues. I'm closing this now.

**Comment by anarcat** [comment]
@chrox if you want to see how i implemented wallabag sync in the kobo reader, you may want to review my code in [wallabako](https://gitlab.com/anarcat/wallabako/).

cheers!
