### ISSUE TITLE
Some Hungarian characters not rendered in epub file

### ISSUE THREAD

**Issue by zolix7508** [koreader/koreader#1638]
Koreader - v2014.11-267-g0b45394 on Kobo Aura HD - some of Hungarian characters not rendered from certain epub file, just question marks are shown for them. Same file is displayed correctly however, on Calibre on Windows 7.

**Comment by zolix7508** [comment]
Just updated to Koreader v2014.11-324-gd952c49, text is displayed correctly now. Not sure if the improvement happened because of the update or power on/off.

**Comment by zolix7508** [comment]
Sometimes the issue re-appears: e.g. when I opened the file after doing a search for file names in the File Manager.

**Comment by thebombsauce** [comment]
I've had this problem with formatting in a few books, turning on and off the "use embedded formatting" option fixes this

**Comment by chrox** [comment]
It's better to provide a sample file for the developers to investigate into.

**Comment by zolix7508** [comment]
Unfortunately I can't upload epub file here :/ Also, can't provide exact steps to repro the problem. Will come back if I will found a pattern in the occurrence of the issue.

**Comment by Frenzie** [comment]
I'll close this for now. Feel free to reopen if you the issue reoccurs.

**Comment by KenMaltby** [comment]
You might also want to check out setting a "fallback" font, that contains the missing characters.
