### ISSUE TITLE
Wikipedia not working in onyx android device 

### ISSUE THREAD

**Issue by sapindus** [koreader/koreader#1642]
when I click on the "wikipedia" button ,it says"Do you want to turn on wifi", but my wifi have been turned on already.Finally no wikipedia pages invoked.

**Comment by Frenzie** [comment]
If this is on the stable version that's to be expected since Wikipedia switched to HTTPS. See #1598. But I'm not really familiar with the Android version.

**Comment by Frenzie** [comment]
On second thought the presence of the wifi prompt indicates something more seriously wrong with KOReader's connectivity.

**Comment by sapindus** [comment]
I'm using the newest nightly build, there may be some connectivity problem, but how to solve this ?

**Comment by gerroon** [comment]
I get this with my CM Kitkat tablet as well

**Comment by Frenzie** [comment]
All I can say is that it shouldn't be a permission issue: https://github.com/koreader/android-luajit-launcher/blob/ac0fd8bf7eef3fa8d7a5c2682d4361ebcaf7a310/AndroidManifest.xml#L10

**Comment by KenMaltby** [comment]
Can't you start Wifi before selecting Koreader?  With my tablet the Android OS user control icons remain on a bar at the bottom of the screen, even while Koreader runs, and a popup gives me the controls.
This is an Android OS function on my tablet.

**Comment by gerroon** [comment]
KR brings up the wifi window even when the wifi is enabled.

**Comment by KenMaltby** [comment]
Humm... Does the Network menu item show "Wifi connection" greyed out?  Does it have a check mark?
With my tablet the menu item "Wifi connection" is always greyed out, and non-functional.  When I turn-on Wifi using the Android controls, it gets a checkmark, and works in koreader.

**Comment by chrox** [comment]
The wikipedia function will first use google translate to detect the source language of the word then it selects corresponding wiki page. In China the Google translate page is blocked again recently so connection to google host is lost thus a "Network unavailable" error [here](https://github.com/koreader/koreader/blob/master/frontend/ui/translator.lua#L61-L63).
