### ISSUE TITLE
feature request : filtering some diacritical marks before dictionary lookup 

### ISSUE THREAD

**Issue by harmonicholas** [koreader/koreader#1649]
Hello. Some languages do not use diacritical marks (e.g. russian). Nevertheless, it is useful to indicate the stress mark with a combining acute accent. However, adding such a diacritical mark confuses the stardict lookup, which isn't always finding the appropriate word with such stress marks. So I think it would be nice for languages without diacritical marks (as english, russian...) to not only filter punctuation (as is done with util.stripePunctuations), but diacritical marks as well before calling sdcv in readerDictionary:stardictLookup(word, box)
thank you

**Comment by chrox** [comment]
It sounds pretty straightforward. Could you give some direct examples on the diacritical marks that you wat to strip.

**Comment by harmonicholas** [comment]
thank you so much for answering, I had in mind COMBINING ACUTE ACCENT (U+0301). but I guess COMBINING ACUTE TONE MARK (U+0341) could be a candidate as well.
exemple of word in russian : УРАГА́Н

once again, I am not suggesting this for me, as I simply added :gsub("\204\129",'') at the end of util.stripePunctuations, but that a generic solution might be interesting for international readers.
thank you

**Comment by Frenzie** [comment]
@poire-z Any interest? ;-P

**Comment by poire-z** [comment]
I'll have to do some cleaning around https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerdictionary.lua#L69 , cause most of that is no more needed.
So, I could add that instead of removing this function.
Any interest in finding us a definitive list of such characters ? :)
I hope we can discard them with no regard to the language used (I think we've already talked about dictionnary stuff not having languages associated, and there's no language variable in this source file).

**Comment by Frenzie** [comment]
https://en.wikipedia.org/wiki/Combining_character#Unicode_ranges

**Comment by poire-z** [comment]
OK, a few ranges should be easy to add.
But are we sure we want to remove them before feeding sdcv ? I know nothing about diacritical stuff. Are `ўoўo` and `yoyo` the same words for the dictionary ?

**Comment by Frenzie** [comment]
They're not the same word, but both should match. I just tested and `déjà` comes up when you input `deja`, but I'm not sure about how it sorts the results. In principle déjà should be listed earlier than deja if you entered it all properly, regardless whether it currently does so or not.

Edit: oh wait, the behavior I described is in 0.5.x whereas the currently shipped 0.4.2 is inferior. That reminds me that I should look into updating the whole shebang. I've got this branch prepped for the purpose: https://github.com/Frenzie/sdcv/tree/v0.5.4_beta4_koreader_changes

So actually this probably doesn't need to involve crengine at all.

**Comment by poire-z** [comment]
(I didn't aim at diving into crengine again :) the cleaning of selected word to be fed to sdcv happens in readerdictionnary.lua)
OK, so we should wait to see how this updated sdcv behave ?
But accentuated chars in déjà (1 unicode char each) are different from the diacritical (2 unicode char to make up one strange letter), so may be sdcv bugs with 2 chars and is fine with 1 char, and we should remove the diacritical char ?

**Comment by Frenzie** [comment]
I'd need a dictionary and a word to test specific behavior. In newer sdcv "deja" also gives "déjà" as a result, whereas in older sdcv it does not. Things are different and better in any case. However, I have zero motivation to check if this stuff works for Android, but I guess I'll try if I can compile it for Android one of these days.

**Comment by Frenzie** [comment]
I've updated sdcv in #3071, so this is likely fixed. Please object if it's not. :-)
