### ISSUE TITLE
Onyx C67ML missing light control

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1651]
Hi

This is  an Android 4.2.2 device. It has night setting but no light intensity control.

Thanks

**Comment by KenMaltby** [comment]
You might want to see if you can access any controls outside of the Koreader App. On my tablet a tap on where the system icons are (they are in the bottom right corner like on a PC) brings up a popup with a number of settings available including those for the light.  This is where I expect to find them when running other apps as well.

**Comment by gerroon** [comment]
Well, KR has light control in other ereaders (Kobo). It would be nice if this is supported with Android version too.

**Comment by chrox** [comment]
Duplicated to #1415. Closing this now.
