### ISSUE TITLE
FR: Background color and paper support

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1653]
Hi

It would be nice if we could change bg color (or darken it) and also be able to add some bg texture/image support.

This could be a much nicer option for Android devices but being able to darken and add some texture in Eink devices can be nice as well, obviously depends on the book and page.

thanks

**Comment by chrox** [comment]
Yes, since we support ubuntu-touch now, more non-eink devices will run koreader and the ability to change background color is nice.

**Comment by gerroon** [comment]
Slight perturbations in the background looks nice on Eink devices. I use FBreader and Coolreader on my Android Eink device and when bg choice done properly, it is not distracting.

**Comment by NiLuJe** [comment]
c.f., #3871
