### ISSUE TITLE
trying to build it on arm linux fails

### ISSUE THREAD

**Issue by irregularisnotrandom** [koreader/koreader#1654]
Hi

I am not sure why it fails on arm debian linux.

1]: Entering directory '/media/temp/koreader/base'
make -C lua-serialize CC="gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC" \
	 \
	 \
	OUTPUT_DIR=/media/temp/koreader/base/build/arm-linux-gnueabihf/common
make[2]: Entering directory '/media/temp/koreader/base/lua-serialize'
[ ! -f lua-5.1.5.tar.gz ] && wget http://www.lua.org/ftp/lua-5.1.5.tar.gz || true
[ `md5sum lua-5.1.5.tar.gz|cut -d\  -f1` != 2e115fe26e435e33b0d5c022e4490567 ] \
	&& rm lua-5.1.5.tar.gz \
	&& wget http://www.lua.org/ftp/lua-5.1.5.tar.gz || true
tar zxf lua-5.1.5.tar.gz
make[2]: Leaving directory '/media/temp/koreader/base/lua-serialize'
cd tar-1.28 && patch -N -p1 < ../tar-0001-fix-build-failure.patch
patching file doc/tar.1
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file doc/tar.1.rej
patching file src/tar.c
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file src/tar.c.rej
Makefile:403: recipe for target 'build/arm-linux-gnueabihf/tar' failed
cd tar-1.28 && ./configure -q LIBS=-lrt \
	 \
	
Makefile:403: recipe for target 'build/arm-linux-gnueabihf/tar' failed
make[1]: Leaving directory '/media/temp/koreader/base'
Makefile:43: recipe for target 'all' failed

**Comment by chrox** [comment]
You can try deleting the tar source directory and rerun make fetchthirdparty.

**Comment by gerroon** [comment]
That did not help. I removed "tar" third party and redid the steps with similar error. 

Has anyone succeeded this under normal arm linux?

**Comment by chrox** [comment]
Could you remove the "-q" flag when configuring `tar` in 
```
cd $(TAR_DIR) && ./configure -q LIBS=$(if $(WIN32),,-lrt) \
```
and see what does it say?

**Comment by houqp** [comment]
@irregularisnotrandom , can you try out the new build system? There were a lot of changes introduced so maybe this issue is already fixed. Please feel free to reopen this issue if you are still seeing the same error.
