### ISSUE TITLE
PDF text reflowing

### ISSUE THREAD

**Issue by JW01** [koreader/koreader#1655]
I'm new to KOReader and I have one question and one problem.
1 Is it possible to reflow a PDF and have control over the font or does it just use the input font? If the former is possible, how do I do it?
2 I have a PDF of a 100 year old boys' magazine. It is printed in two columns but occasionally there is an advert which covers both columns. What I am finding is that reflowed text is interspersed with two column text.
(I just tried to attach the file but it said it doesn't support that filetype - PDF!)
Thanks for your help.

**Comment by chrox** [comment]
1. No. Koreader feeds the reflowing engine with images of the pages, thus no concept of font at all.
2. Could you just upload a screenshot of that page? It should support png attachments.

**Comment by JW01** [comment]
I attach screenshots of the PDF, 1-3 on the Kindle, 4-5 the original file.
1 shows a bit of reflowed text, the advert (which covers one column, not two as I said before) and the unreflowed text.
2 shows more unreflowed text followed by the heading of the next page (which does cover two columns).
3 shows the heading followed by reflowed text.
4 shows the first original page.
5 shows the second original page.
I can send you the whole 20 page PDF if you give me an address to send it to.

Incidentally as a newcomer to KOReader, I cannot find explanations for some functions in the wiki: Forced OCR, Embedded Style, Floating punctuation, Set render style.
Also, 
How do I add, for instance Arial, to the list of fonts?
What is the advantage of choosing a specific rendering style over Auto?
Is there any way to change the font and/or font size of the menus?
Many thanks for your help. It’s a great program.

![1](https://cloud.githubusercontent.com/assets/12519813/10264009/fc742174-69f8-11e5-96ba-51e83e46509c.JPG)
![2](https://cloud.githubusercontent.com/assets/12519813/10264012/0bea317a-69f9-11e5-8208-fde3a04e73b4.JPG)
![3](https://cloud.githubusercontent.com/assets/12519813/10264014/186829ac-69f9-11e5-9244-b6a5845957fb.JPG)
![4](https://cloud.githubusercontent.com/assets/12519813/10264016/239a60ec-69f9-11e5-8950-37adfc6e86d1.JPG)
![5](https://cloud.githubusercontent.com/assets/12519813/10264018/2ef24d24-69f9-11e5-9d34-3b42fac3c280.JPG)

**Comment by chrox** [comment]
From your screenshots koreader behaves expected at large. It's not "clever" enough to make decision according to contextual information and display the ad at the bottom of your second page altogether. All it does is checking if there is a big gap between the left and right part, if there is, it divides them apart.

And "Forced OCR" is an experimental feature and is hidden by default unless you turn on the "advanced settings" at the top menu. And the other three options "Embedded Style, Floating punctuation, Set render style" are only for EPUB documents.

**Comment by JW01** [comment]
Thanks for your reply.
Just to clarify, my supplementary questions were not confined to PDF but to KOReader in general.
Can you please explain them or point me to an explanation of them?
Many thanks.

**Comment by chrox** [comment]
>How do I add, for instance Arial, to the list of fonts?
You can put your ttf font file in the `fonts` directory, then you will find it in the choose font menu.

>What is the advantage of choosing a specific rendering style over Auto?

By auto it will choose an style according to the file extension, for example, it will choose epub.css for epub documents. But you can still choose other styles for epub documents or even add new styles in the "koreader/data" directory.

>Is there any way to change the font and/or font size of the menus?
You cannot change the font of the GUI, but font size should be adjustable in a while, I'm working on it. See #1345 and #1589.

**Comment by chrox** [comment]
And the wiki pages only cover a small portion of koreader's functionality, feel free to ask anything related to koreader here.

**Comment by KenMaltby** [comment]
This is the real home of Koreader and official info about it will be presented here, but you can also find some answers over at MobileRead Forums http://www.mobileread.com/forums/
The Kobo and Kindle forums are probably the most Koreader active.

**Comment by JW01** [comment]
Many thanks for the very helpful replies.
You say that the wiki pages only cover a small portion of KOReader's functionality. This is a pity as it is a great program and I would like to understand all its features. Is there a plan to provide more comprehensive documentation?  
(I would still like to know what is the effect of having Forced OCR, Embedded Style and Floating punctuation switched on or off).
Finally, is there a way of being notified automatically when a new release/nightly is available or do I have to check every few days?
Once again, many thanks for the replies and for developing a Kindle (and Kobo) game changer.

**Comment by chrox** [comment]
I agree that the wiki page is the best place to document Koreader features, but Koreader development is quite active recently thus the wiki page is a little out-of-date. I really wish more users not only the developers could contribute to the wiki pages, they are open to everyone.

For example, we can create a "terminology" page in the wiki to explain some unfamiliar concepts of Koreader to users like:

>"Forced OCR": an option that forces to use the built-in OCR(Optical Character Recognition) engine to recognize words in PDF pages even if the pages have text layers, currently the OCR process only takes place when highlighting a word for dictionary look up.

>"Embedded Style": when this option is turned on, Koreader will use the embedded style sheet file in the EPUB document. This option may change the typesetting of the rendered result of that document.

>"Floating punctuation": with this option on, punctuation marks at the end of a line may be hung into page margin. This is also called "[Hanging punctuation](https://en.wikipedia.org/wiki/Hanging_punctuation)".

I don't know if you will get an email notification of a new release if you watch this project, but you will get notifications of issue discussions.

**Comment by chrox** [comment]
I really would like to ask @KenMaltby for helping us build the wiki pages. And I appreciate your patient guidance for beginners of Koreader users at the mobileread forum. I wish we could have a comprehensive repository of all Koreader knowledge including but not limited to guides, manuals, tips and technical explanations. So we can lead users to this wiki and they will find anything they want to know about Koreader.

**Comment by KenMaltby** [comment]
I would want to provide any help I can to support this great project.  I guess I need to find and study a WiKi tutorial guide.  I think the current WiKi structure is pretty good and will have to think of how to fit in with what is already there. I will be glad to try.
