### ISSUE TITLE
Battery status update

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#1656]
Charging or discharging, the battery value changes only very rarely and randomly, I also can't force it by certain actions, at least I didn't find any.
(Kobo Aura HD)

**Comment by KenMaltby** [comment]
While it may appear random, Li-Ion batteries are charged in a controlled way.  You would not see a steady predictable change in the % charge, in any case.  As I understand it the power status is polled after every 6 page turns, while reading.  When you call the menus it gets polled as well, I think.  It shouldn't show a new number until the battery charge has actually changed.  It now will show a "+" when it is charging.

**Comment by chrox** [comment]
As @Ken said you can force a refresh of battery status by showing the menu.

**Comment by hurzl** [comment]
But it doesn't seem to work as now after about 18 hours on it still shows 100%

**Comment by KenMaltby** [comment]
If you are launching Koreader using the Kobo Start Menu (KSM), you can try the KSM "Tools" battery monitoring scripts.  You also should see a complete relook at the battery status if you restart Koreader.

**Comment by hurzl** [comment]
Ok I restartet koreader and immediately I see 98%. Right before it was 100%. So it's not updated by opening the menu

**Comment by KenMaltby** [comment]
Opening the menu checks on the battery status, almost all the time the status will not have changed enough to change the % shown.  For instance: going from 100% to 99% would not necessarily be always a detectable amount of change.

**Comment by hurzl** [comment]
Now I had the menu open while loading, it stayed at 76%. I closed and opened it and it still was at 76%. Then I turned the page and/or switched the status bar to the battery value which then showed 100%. Then after opening the menu it was at 100%. Probably one has to turn the page for an update?

**Comment by Frenzie** [comment]
Yes, that's correct.

**Comment by hurzl** [comment]
Now after a few hours still 100%. I close the menu and reopen it, still 100%. I go a page forth and back, still 100%. Then I cycle the bottom status bar which shows 100% until I get back to battery and it shows  94%.

**Comment by NiLuJe** [comment]
Don't pay attention to battery status report > 92%, they're wonky as hell (especially on Kobos). That's just how the HW reports stuff, not KOReader.

**Comment by NiLuJe** [comment]
As for KOReader, the report is updated every 10 polls, no matter what (the menu doesn't short-circuit that, that was me misremembering stuff. Possibly it *should*, but, meh...).

**Comment by NiLuJe** [comment]
[This should do the trick](/NiLuJe/koreader/commit/bfb2ee703aebc0b8c4a4332bd8a8326609b2c05a)
