### ISSUE TITLE
All italics

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#1657]
Just installed 346, and suddenly my current epub is all italics text. It wasn't with 324. I can select whatever Typeface I want in the settings, it stays the same.

... And why does it stay like this when I reinstall -324?

**Comment by KenMaltby** [comment]
You could try the bottom menu gear icon and set "Embedded Style"  to "off".

**Comment by hurzl** [comment]
Ok yes, why does 346 switch it on?

**Comment by KenMaltby** [comment]
The default is on.  You can set the default to off by long pressing the off selection.
