### ISSUE TITLE
FR: Save PDF

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1661]
Hi

I love reflowing and other pdf features of KR. I wonder if KR can save the pdf file as seen on the screen after the user sets everything as intended. That way one can either read the saved version without further reflowing per page. The user can also transfer the nice looking readable pdf to other devices as well.

**Comment by chrox** [comment]
You can try the k2pdfopt http://willus.com/k2pdfopt/. It runs on desktop OS and does exactly what you ask for.

**Comment by gerroon** [comment]
I already use it but it is nicer and easier to do inside KR ;)

**Comment by brookhong** [comment]
k2pdfopt generates out file with bitmap when reflowing(http://www.willus.com/k2pdfopt/help/native.shtml), which causes its output file with large file size and lower quality.

I'm still looking forward this feature from koreader, as reflowed output from koreader looks good on my mobile.

**Comment by Frenzie** [comment]
KOReader depends on k2pdfopt for reflow, and actually the currently slightly older v2.34 plus some patches at that, so I don't think it should generally look much better or worse. Perhaps more to the point, I think a saved PDF should therefore have the same (large?) file size.

As an aside, your link seems to contradict what you're saying? Also bitmaps would certainly be sized larger, but I can only assume you mean subsequent (re)compression with low-quality JPEG. :-)

> **As of v1.60** [note: that means ~2013], k2pdfopt has an option so that *rather than* rendering the output file as a sequence of bitmaps, each output page is **rendered directly using the source PDF file instructions**, but with translation, scaling, and cropping directives to place the source regions at the appropriate places on the output pages. This is especially beneficial if the source file is a native text PDF file (rather than a scan of a document).

PS @gerroon 

> Also K2PdfOpt is much slower on the desktop.

On your desktop it processes the entire file all at once. In KOReader it's per page. Unless you're running KOReader on a top model Android device (or k2pdfopt on a 20-year-old computer) it's extremely unlikely that processing the entire file would even be in the same order of magnitude of total time. ;-)

**Comment by brookhong** [comment]
> On the other hand, native PDF output is not compatible with text wrapping, contrast adjustment, gamma adjustment, or sharpening.

I have a pdf doc, with original size 4.7M, k2pdfopt generates an output file of 192M with below command.

    ./k2pdfopt -n input.pdf -wrap+ -hy -ws 0.01 -o output.pdf

`-wrap+` here seems suppress `-n`. The layout is good for me on my kindle device, but the output file is too large, and the quality of text is bad.


## Original Doc
![image](https://user-images.githubusercontent.com/288207/36071115-2fa6fac4-0f44-11e8-9c83-2f8dcb343053.png)

## Converted Doc
![image](https://user-images.githubusercontent.com/288207/36071098-f4601f40-0f43-11e8-98ef-0a8b62863ccf.png)

**Comment by brookhong** [comment]
I looked into more about result from koreader, it looks similar. Maybe it looks better just because I used it on an Android phone, which has a higher resolution of screen than Kindle.

**Comment by Frenzie** [comment]
True, though at least for Western text I find the result of `-wrap+` thoroughly displeasing regardless of the horrific size/quality ratio.

```
-wrap[-|+]        Enable [disable] text wrapping.  Default = enabled.  If
                  -wrap+, regions of text with lines shorter than the mobile
                  device screen are re-flowed to fit the screen width.  If
                  you use -wrap+, you may want to also specify -fc- so that
                  narrow columns of text are not magnified to fit your device.
                  Text wrapping disables native PDF output (see -n option).
                  See also -ws, -j, -fc, -n.
```

![screenshot_2018-02-11_09-18-20](https://user-images.githubusercontent.com/202757/36071298-8e62645a-0f0c-11e8-90b3-fc2e2821a524.png)

**Comment by Frenzie** [comment]
Oh wait, in my example it's just cutting the margins. Sorry, I don't use reflow. :-P
