### ISSUE TITLE
Suspend not working properly on Kobo Glo HD

### ISSUE THREAD

**Issue by nickjwhite** [koreader/koreader#1663]
I'm using a Kobo Glo HD with the 3.18.0 firmware and the newest Kobo Start Menu, and the latest nightly build of koreader, gf85da28.

Suspend doesn't seem to work properly from koreader. It appears to work; the screen is locked and the cover is shown, however it drains the battery way faster than it should on suspend (~2-3% per hour).

I looked in the crash.log and found several entries "sh: write error: Operation not permitted" (though this may be a red herring, as it doesn't add a line every time I suspend try to suspend). That took me to issue 310. I found when applying a workaround there, to add "sleep 2" between the last 2 lines of suspend.sh, the issue _seems_ to be fixed; suspend no longer seems to be draining the battery. This probably isn't a clean / proper solution, though.

Any suggestions on how to debug this further? I don't know how to test actual suspend status or anything like that, but would be happy to be guided on it if it helps.

**Comment by Frenzie** [comment]
> though this may be a red herring, as it doesn't add a line every time I suspend try to suspend

That means it's suspending properly when that line isn't there.

> This probably isn't a clean / proper solution, though.

It's not, but it's the only one I could come up with: https://github.com/koreader/koreader/blob/master/frontend/device/generic/device.lua#L113

Those 10 seconds are based on my Kobo Aura H2O, which always suspended properly with 8 seconds, plus 2 seconds for safety. Your story suggests increasing it to 12.

You can get more info about specifics using dmesg.

**Comment by Frenzie** [comment]
I'll close this now but feel free to reopen or add to one of the various suspend issue tickets.
