### ISSUE TITLE
FR: Saving the last page position on every page flip on Android 

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1668]
Hi

We have a lua setting on Kobo where one could set it so KR saves the last page on every page flip but I cant find a way to do that on Android.

Right now I get frequent crashes and that means that I always start from the same page or whereever the page num was saved properly.

thanks

**Comment by chrox** [comment]
It actually has the same setting, look at [this](https://github.com/koreader/koreader/blob/master/defaults.lua#L142-L143).

And in Android each time you put the koreader application to the background it will flush reader setting to external storage, refer to [this](https://github.com/koreader/koreader/search?utf8=%E2%9C%93&q=SaveState).

**Comment by gerroon** [comment]
@chrox 

Which file do I put this in then?

**Comment by gerroon** [comment]
Ok I see that this is part of /data/data however this is not user friendly because not everyone`s devices are rooted.
