### ISSUE TITLE
Do I have to have a book open to get Zsync to work?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1669]
Can I be in the file browse mode as well for Zsync? Does it do it in the background regardless where the user is? The reason I am asking si that there is no progress indication so it is hard to know if it is done or not.

Naturally one has to have a book open to publish it however my question is more about the subscriber. 

Also do I have to subscribe constantly if the other device publishes a new book?

**Comment by chrox** [comment]
Currently you have to open a document in order to subscribe another document. That's the limitation of the plugin architecture which is loaded in `ReaderUI`, so after you close a document all plugins won't get events any more. This can be improved in the future when we have filemanager plugins.

**Comment by gerroon** [comment]
Thanks for the explanation
