### ISSUE TITLE
Android tablet devices instabilities and crashes

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1670]
[Samsung Tab]

Hi

My intention is to help out the devs about the crashes and freezes we get with the Android tablet installations of KR in this bug.

Please bear in mind that KR on my Android devices is very crashy but sometimes once in a while it decides to act like it is abit more stable. For instance, 2 times out of 10 runs I might might be able to use it to check out couple pages of a book. Although it is super crasy and freezey, it pretends that it can run ok which is just a fluke compared  to number of times it crashes in my view. The thing is that I can get these nicer sessions after many crashes so it is not something I decide or I do. 

I am kicking off the discussion with the  luajit log from my Samsung CM 11 Android Kitkat 4.4.4

Here I started KR waited 5 min almost with no visible screen, I only get blank screen in this time frame. Sometimes waiting long enough brings KR emnu however that is just a fluke because it would crash later when clicked on a menu item.

https://paste.debian.net/315041/

**Comment by gerroon** [comment]
I waited long enough (maybe like 7 min?) and it brought the file browser, then as I mentioned clicking on freezes KR further and soon it crashes.

Here is the addition to the first log which displays the status after the long delayed black screen and furthering the crash

https://paste.debian.net/315042/

**Comment by gerroon** [comment]
And here is the much anticipated memory map

https://paste.debian.net/315045/

**Comment by gerroon** [comment]
And this is the memory map from a black screen start up

https://paste.debian.net/315048/

**Comment by gerroon** [comment]
[Nook HD+]

The file browser is not opening files. The fb responds, I can select a file but it does not open the file. It stays in the fb.

I/luajit-launcher(22066): 		["h"] = 369,
I/luajit-launcher(22066): 		["w"] = 941.33333333333
I/luajit-launcher(22066): 	}
I/luajit-launcher(22066): }
I/luajit-launcher(22066): # creating coroutine for showing reader
I/luajit-launcher(22066): # opening file /storage/emulated/legacy/xxxx.pdf
E/libmupdf(22066): error: cannot find startxref
E/libmupdf(22066): warning: trying to repair broken xref
E/libmupdf(22066): warning: object missing 'endobj' token
I/luajit-launcher(22066): # Loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
I/luajit-launcher(22066): # Loaded plugin evernote at plugins/evernote.koplugin
I/luajit-launcher(22066): # Loaded plugin kosync at plugins/kosync.koplugin
I/luajit-launcher(22066): # Loaded plugin statistics at plugins/statistics.koplugin
I/luajit-launcher(22066): # Loaded plugin zsync at plugins/zsync.koplugin
I/luajit-launcher(22066): # INFO: invalid widget for setDirty() stack traceback:
I/luajit-launcher(22066): 	frontend/ui/uimanager.lua:205: in function 'setDirty'
I/luajit-launcher(22066): 	frontend/apps/reader/modules/readerview.lua:570: in function 'onSetScreenMode'
I/luajit-launcher(22066): 	frontend/apps/reader/modules/readerview.lua:614: in function 'handleEvent'
I/luajit-launcher(22066): 	frontend/ui/widget/container/widgetcontainer.lua:67: in function 'propagateEvent'
I/luajit-launcher(22066): 	frontend/ui/widget/container/widgetcontainer.lua:79: in function 'handleEvent'
I/luajit-launcher(22066): 	frontend/apps/reader/readerui.lua:306: in function 'init'
I/luajit-launcher(22066): 	frontend/ui/widget/widget.lua:39: in function 'new'
I/luajit-launcher(22066): 	frontend/apps/reader/readerui.lua:361: in function 'doShowReader'
I/luajit-launcher(22066): 	frontend/apps/reader/readerui.lua:328: in function <frontend/apps/reader/readerui.lua:327>
I/luajit-launcher(22066): # INFO: invalid widget for setDirty() stack traceback:
I/luajit-launcher(22066): 	frontend/ui/uimanager.lua:205: in function 'setDirty'
I/luajit-launcher(22066): 	frontend/apps/reader/modules/readerview.lua:520: in function 'recalculate'
I/luajit-launcher(22066): 	frontend/apps/reader/modules/readerview.lua:582: in function 'handleEvent'
I/luajit-launcher(22066): 	frontend/ui/widget/container/widgetcontainer.lua:67: in function 'propagateEvent'
I/luajit-launcher(22066): 	frontend/ui/widget/container/widgetcontainer.lua:79: in function 'handleEvent'
I/luajit-launcher(22066): 	frontend/apps/reader/modules/readerview.lua:571: in function 'onSetScreenMode'
I/luajit-launcher(22066): 	frontend/apps/reader/modules/readerview.lua:614: in function 'handleEvent'
I/luajit-launcher(22066): 	frontend/ui/widget/container/widgetcontainer.lua:67: in function 'propagateEvent'
I/luajit-launcher(22066): 	frontend/ui/widget/container/widgetcontainer.lua:79: in function 'handleEvent'
I/luajit-launcher(22066): 	frontend/apps/reader/readerui.lua:306: in function 'init'
I/luajit-launcher(22066): 	frontend/ui/widget/widget.lua:39: in function 'new'
I/luajit-launcher(22066): 	frontend/apps/reader/readerui.lua:361: in function 'doShowReader'
I/luajit-launcher(22066): 	frontend/apps/reader/readerui.lua:328: in function <frontend/apps/reader/readerui.lua:327>
E/libmupdf(22066): error: cannot find page tree
I/luajit-launcher(22066): # close widget
I/luajit-launcher(22066): # triggering refresh {
I/luajit-launcher(22066): 	["mode"] = "full",
I/luajit-launcher(22066): 	["region"] = {
I/luajit-launcher(22066): 		["y"] = 0,
I/luajit-launcher(22066): 		["x"] = 0,
I/luajit-launcher(22066): 		["h"] = 1848,
I/luajit-launcher(22066): 		["w"] = 1280
I/luajit-launcher(22066): 	}
I/luajit-launcher(22066): }

**Comment by gerroon** [comment]
[Nook HD+]

Freezes during opening a book

https://paste.debian.net/315666/

**Comment by gerroon** [comment]
Any word on this bug? Do the devs need more info from me regarding android devices?

**Comment by chrox** [comment]
Sorry about this, but I won't have spare time until this weekend when I would like to do some experiments with the LuaJIT source and see if we can have some workarounds to handle this for Android.

**Comment by gerroon** [comment]
@chrox 

Thanks for the follow up. Please let me know if you need further testing. I so want KR to be stable on Android, I would do anything pretty much to get it going ;)

This is the reader everyone in the world needs. KR will save the future of humanity ;)

**Comment by gerroon** [comment]
[Boyue T62]

KR freezes during menu operations, and sometimes when page turning
luajit
http://www.pasteall.org/61751/text

rest of the android log
http://www.pasteall.org/61752/text

memory map
http://www.pasteall.org/61753

This device does not have any kind of xposed/xprivacy stuff. It is the vanilla Boyue kernel

**Comment by gerroon** [comment]
Any progress here ;) Not push you, I know you guys are busy ;)

**Comment by chrox** [comment]
Koreader for Android has changed a lot since this issue was reported so the provided logs might be out of date. Please retry with the latest nightly build and report back if you still have this problem.
