### ISSUE TITLE
Kobo Aura HD v2014.11-375 Status bar change limited

### ISSUE THREAD

**Issue by Ebrehem** [koreader/koreader#1673]
I have updated to this version, and at the first quit of the application, it remained stuck. After restart I read without a problem, but later realised, that in spite of the status bar set to display battery %, chapter pages and total pages, it only displays total pages. I can turn on - off the status bar, but nothing else. changes (i tried both turning on-off chapter pages and battery). Is it a matter of settings or a bug?

(persistent settings also contain to display the above).

**Comment by KenMaltby** [comment]
Did you tap the bottom right corner, with the display item that you do see?  Tapping what is displayed there should cycle through the checked selections in the "Status bar" menu.

**Comment by Ebrehem** [comment]
Thank you Ken, yes, Show all at once was turned off, I enabled it so long time ago I forgot it :). I close the issue and thank you for the hint!
