### ISSUE TITLE
Resizing KR window on Linux?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1681]
Hi

I cant find a way to resize KR window on Linux. Is this a compile time option if so how do I do it?

The current default is pretty small for a desktop.

thanks

**Comment by chrox** [comment]
You can set several env variables to change the window size for the emulator, look at [this](https://github.com/koreader/koreader-base#device-emulation).

**Comment by gerroon** [comment]
That is great, maybe this should be in the wiki for desktop portion.
