### ISSUE TITLE
FR: Splitting double pages without reflowing

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1683]
Hi

I cant seem to find a way to do this so I am putting it as a FR. Basically I would like to be able to split double pages into properly ordered individual pages without reflowing (since reflowing can break formatting quite a bit on certain books). This can even be more evident to KR if the book is in landscape format which is generaly an indication of double pages. 

The user can define a middle spline along with general  cropping guides to assist the split.

k

**Comment by chrox** [comment]
Duplicated to #501.

**Comment by gerroon** [comment]
thanks for the follow up.
