### ISSUE TITLE
FR: Would you like to read the downloaded book for OPDS

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1688]
Hi,

It would be nice if we could get a confirmation window that asks the reader if she would like to read the downloaded book right after finishing the download. The user can either says yes or no. If she says yes KR opens the downloaded book. If she says no it stays in the current OPDS folder. 

thanks

**Comment by robert00s** [comment]
Done in #2370
@houqp Please close the task.

**Comment by houqp** [comment]
Thanks @robert00s !
