### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x00000037 crash on Onyx C67ML

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1689]
Hi

We fixed most of the issues with another bug somehow KR started acting up with another type of crash, I believe. This crash mostly happens when I clikc on the top menu to change some stuff.

https://github.com/koreader/koreader/issues/1643

I am using the version with all those manual fixed implemented in mupdf.lua and util.lua as described in the previous bug.

Android log
http://www.pasteall.org/61846

luajit
http://www.pasteall.org/61847

mem map
http://www.pasteall.org/61848

**Comment by chrox** [comment]
Duplicated to #643.
