### ISSUE TITLE
FR: Craziest FR ever, 2 devices to read a single book at the same time, DIY 2 page ereader ;)

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1690]
So I have this idea which is a bit fantasy but I feel like KR can actually do this because we already have something like Zsync in place.

Basically I am thinking to buy 2 ereaders of the same model same size etc. I am going to attach them together from a shared edge, lets say I tape them so in the end it looks like a 2 page ereader. Now that by itself can be useful. However the magic migth come in place if KR can sync sequential pages of the same book  left to right etc. I can do this at the moment manually. I can publish the book from the left ereader and subscribe to it on the the right one and from that on I can manually click on the pages to simulate a traditional 2 page book reading experience. However I feel like KR can do this in an automated way. It can stay synced if that special model is selected. Kr would flip pages of the both devices at the same time when page turning is asked on one of the devices.

Anyway it is maybe too fancy since not many people would spend money on multiple readers to get this going but worth thinking about it.

**Comment by chrox** [comment]
Guess what? It's not crazy and is right on my development roadmap. We will have not only dual view of a single book but also we can drag a window like a dict window or TOC or input box onto another screen and the two device could act like one device with two screen. It will be a promising exploration of new possibility of user interaction with ereader devices and is full of imagination.

**Comment by KenMaltby** [comment]
With the addition of Notetaking, this could make for an interesting study/research tool.

**Comment by gerroon** [comment]
@chrox 

That is a great news. 
I also wonder if this can be done via usb connections(like some kind of usb net) insted of wireless. However I am not sure which one would be more energy efficient. In any case I will be more than happy to start with whatever is easiest to implement.

I guess in this respect the user can have differently sized eraders as well. as @KenMaltby mentioned it could be mor euseful as research tool. For instance users can have use 8inc and a 6inc reader together etc.

**Comment by chrox** [comment]
Bingo, totally agreed. It's an open question. But we can try to solve it.

**Comment by ersi-dnd** [comment]
Any progress on having two pages side by side in a single view?

**Comment by KenMaltby** [comment]
You might also consider "Near Field Communications".

**Comment by pazos** [comment]
Closing old tickets. Feel free to reopen if something is going on :)

**Comment by Frenzie** [comment]
As a quick note one might be able to hack something together fairly quickly using #10223. (Of course I mean quickly only in the dumbest way possible, i.e. next page here says next page to the other one.)
