### ISSUE TITLE
Clicking on menu crashes KR on C67ML with koreader-nightly-20151008 F/libc ( 7489): Fatal signal 11 (SIGSEGV) at 0x00000040 (code=1),

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1691]
I installed the latest release to see if I get any stability improvements, I guess I did not get much. Maybe it fixes the libc issues but I have menu clicking crashes steadily.

http://www.pasteall.org/61856

the memory map should be same as the previous bug since it is the same device
http://www.pasteall.org/61848

Please feel free to merge the bugs, however I feel like I should provide as much information as possible to the devs.

Prev bug with crash issues on the same device. Not sure if they are the same issue
https://github.com/koreader/koreader/issues/1689

thanks

**Comment by gerroon** [comment]
This and the previous bug is very curious. I wonder Luajit is having issues with the Android system. Because it seems like luajit just crashes.

I/luajit-launcher( 7489): # in tap state...
I/luajit-launcher( 7489): # set up hold timer
D/PowerManagerService(  344): cancelAlarms:
D/PowerManagerService(  344): resetIdle:true
D/PowerManagerService(  344): cancel alarm:idle_wake_action
D/PowerManagerService(  344): cancel alarm:user_timeout_action
D/PowerManagerService(  344): set alarm:user_timeout_action, now:1445617091411, wake:1445617390410
F/libc    ( 7489): Fatal signal 11 (SIGSEGV) at 0x00000040 (code=1), thread 7502 (reader.launcher)
I/DEBUG   (   91): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (   91): Build fingerprint: 'Onyx/C67ML_Carta/C67ML_Carta:4.2.2/JDQ_1506261720/610:user/release-keys'
I/DEBUG   (   91): Revision: '0'
I/DEBUG   (   91): pid: 7489, tid: 7502, name: reader.launcher  >>> org.koreader.launcher <<<
I/DEBUG   (   91): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000040
I/DEBUG   (   91):     r0 00000000  r1 58eb21e7  r2 5cdfbc38  r3 00000000
I/DEBUG   (   91):     r4 00000000  r5 5956503c  r6 58eb21e7  r7 58eb21e7
I/DEBUG   (   91):     r8 00000000  r9 5cdfbc38  sl 00000001  fp 000015ce
I/DEBUG   (   91):     ip 00000000  sp 5cdfbbe8  lr 40200ea9  pc 401fe3b8  cpsr 20000030

**Comment by gerroon** [comment]
Just to offer some insight after digging around the bug database

This patch.lua addition fixes menu crashes for now. So it is a memory issue then?
"require("jit.opt").start("sizemcode=64","maxmcode=512", "recunroll=8", "callunroll=12", "loopunroll=60", "instunroll=16", "tryside=16", "hotexit=160", "hotloop=1792", "maxsnap=160000", "maxside=32000", "maxirconst=160000", "maxrecord=1280000", "maxtrace=320000")
for i=1,1000 do end  -- Force allocation of one large segment"


My patch.lua for C67ML
local screen = require("android").screen                                        
screen.height = screen.height + 80 

require("jit.opt").start("sizemcode=64","maxmcode=512", "recunroll=8", "callunroll=12", "loopunroll=60", "instunroll=16", "tryside=16", "hotexit=160", "hotloop=1792", "maxsnap=160000", "maxside=32000", "maxirconst=160000", "maxrecord=1280000", "maxtrace=320000")
for i=1,1000 do end  -- Force allocation of one large segment

**Comment by wjchen** [comment]
My patch.lua for T62D
It seems just incress hotloop, crash will be less.
```
--  for boyue t61/t62
local results_str = require("android").stdout("getprop", "persist.boeye.statusbar")
if results_str == "0\n" then
    local screen = require("android").screen
    screen.height = screen.height + 80 
end

require("jit.opt").start("hotloop=57344")
for i=1,100 do end  -- Force allocation of one large segment
```

**Comment by Germanc** [comment]
Hi! Just adding that I have been using that same patch on both my rebranded CM67 (Boris 611L reader, android 4.2) and my Moto G (android 5.0.2 using xposed) for the last three months. It won't work without it so I can test if needed.

**Comment by pasteur90** [comment]
I have the same issue with @gerroon.
One different thing from @gerroon:
   It crashes just after turning a few pages of any book.
my log:
I/luajit-launcher(  905): # in tap state...

I/luajit-launcher(  905): # set up hold timer

I/luajit-launcher(  905): # in tap state...

I/luajit-launcher(  905): # set up tap timer

I/luajit-launcher(  905): # in tap timer true

I/luajit-launcher(  905): # single tap detected in slot 0

I/luajit-launcher(  905): # goto relative page: 1

I/luajit-launcher(  905): # going to page number 9

I/luajit-launcher(  905): # init scroll page states

I/luajit-launcher(  905): # set page position 0

I/luajit-launcher(  905): # painting {

I/luajit-launcher(  905): 	["y"] = 0,

I/luajit-launcher(  905): 	["x"] = 0,

I/luajit-launcher(  905): 	["h"] = 1448,

I/luajit-launcher(  905): 	["w"] = 1072

I/luajit-launcher(  905): } to 0 0

I/luajit-launcher(  905): # triggering refresh {

I/luajit-launcher(  905): 	["mode"] = "partial",

I/luajit-launcher(  905): 	["region"] = {

I/luajit-launcher(  905): 		["y"] = 0,

I/luajit-launcher(  905): 		["x"] = 0,

I/luajit-launcher(  905): 		["h"] = 1448,

I/luajit-launcher(  905): 		["w"] = 1072

I/luajit-launcher(  905): 	}

I/luajit-launcher(  905): }

I/luajit-launcher(  905): # hinting page 10 in background

I/luajit-launcher(  905): ffi.load libc.so

E/PowerManagerService-JNI(  343): jeffy, do set wake

E/libsuspend(  343): autosuspend_earlysuspend_wake

I/luajit-launcher(  905): # in tap state...

I/luajit-launcher(  905): # set up hold timer

F/libc    (  905): Fatal signal 11 (SIGSEGV) at 0x00000040 (code=1), thread 918 (reader.launcher)

I/DEBUG   (   89): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

I/DEBUG   (   89): Build fingerprint: 'rk30sdk/rk30sdk/rk30sdk:4.2.2/JDQ39/ridi.20151030.112911:user/release-keys'

I/DEBUG   (   89): Revision: '0'

I/DEBUG   (   89): pid: 905, tid: 918, name: reader.launcher  >>> org.koreader.launcher <<<

I/DEBUG   (   89): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000040

I/DEBUG   (   89):     r0 00000000  r1 40b9dfcf  r2 689b5c38  r3 00000000

I/DEBUG   (   89):     r4 00000000  r5 40ba2cec  r6 40b9dfcf  r7 40b9dfcf

I/DEBUG   (   89):     r8 00000000  r9 689b5c38  sl 00000001  fp 00000000

I/DEBUG   (   89):     ip 00000000  sp 689b5be8  lr 40160ea9  pc 4015e3b8  cpsr 20000030

I/DEBUG   (   89):     d0  fffffff200000064  d1  fffffff2000003e8

I/DEBUG   (   89):     d2  64656c6961662074  d3  756f656d6974203a

I/DEBUG   (   89):     d4  ffffffff51eb851f  d5  bff0000000000000

I/DEBUG   (   89):     d6  000003e800000000  d7  408f400000000000

I/DEBUG   (   89):     d8  0000000000000000  d9  0000000000000000

I/DEBUG   (   89):     d10 0000000000000000  d11 4082c00000000000

I/DEBUG   (   89):     d12 3f90000000000000  d13 3fe0000000000000

I/DEBUG   (   89):     d14 4069000000000000  d15 4040000000000000

I/DEBUG   (   89):     d16 7fffffffffffffff  d17 7fffffffffffffff

I/DEBUG   (   89):     d18 0000000000000000  d19 3fe0000000000000

I/DEBUG   (   89):     d20 3fe1c15d9a29c1d4  d21 0000000000000000

I/DEBUG   (   89):     d22 00ff00ff00ff00ff  d23 00fe00ff00ff00ff

I/DEBUG   (   89):     d24 00ff00ff00ff00ff  d25 00fe00ff00ff00ff

I/DEBUG   (   89):     d26 0000000000000000  d27 0000000000000000

I/DEBUG   (   89):     d28 00ff00ff00ff00ff  d29 00fe00ff00ff00ff

I/DEBUG   (   89):     d30 0000000000000000  d31 0000000000000000

I/DEBUG   (   89):     scr 8800001f

I/DEBUG   (   89): 

I/DEBUG   (   89): backtrace:

I/DEBUG   (   89):     #00  pc 000123b8  /system/lib/libutils.so (android::SortedVectorImpl::_indexOrderOf(void const*, unsigned int*) const+35)

I/DEBUG   (   89):     #01  pc 00014ea5  /system/lib/libutils.so (android::Looper::addFd(int, int, int, android::sp<android::LooperCallback> const&, void*)+136)

I/DEBUG   (   89):     #02  pc 00014fd5  /system/lib/libutils.so (android::Looper::addFd(int, int, int, int (*)(int, int, void*), void*)+76)

I/DEBUG   (   89): 

I/DEBUG   (   89): stack:

I/DEBUG   (   89):          689b5ba8  62d5f370  

I/DEBUG   (   89):          689b5bac  689b5bf8  

I/DEBUG   (   89):          689b5bb0  0000000b  

I/DEBUG   (   89):          689b5bb4  00000200  

I/DEBUG   (   89):          689b5bb8  40135228  

I/DEBUG   (   89):          689b5bbc  00000000  

I/DEBUG   (   89):          689b5bc0  62e0a23c  

I/DEBUG   (   89):          689b5bc4  62dc7083  /data/app-lib/org.koreader.launcher-1/libluajit-launcher.so

I/DEBUG   (   89):          689b5bc8  62d5f370  

I/DEBUG   (   89):          689b5bcc  62d5f370  

I/DEBUG   (   89):          689b5bd0  689b5bf8  

I/DEBUG   (   89):          689b5bd4  633100b0  

I/DEBUG   (   89):          689b5bd8  00000001  

I/DEBUG   (   89):          689b5bdc  62d641c8  

I/DEBUG   (   89):          689b5be0  df0027ad  

I/DEBUG   (   89):          689b5be4  00000000  

I/DEBUG   (   89):     #00  689b5be8  00000000  

I/DEBUG   (   89):          689b5bec  00000000  

I/DEBUG   (   89):          689b5bf0  40ba2cb8  

I/DEBUG   (   89):          689b5bf4  00000000  

I/DEBUG   (   89):          689b5bf8  40ba2cec  

I/DEBUG   (   89):          689b5bfc  40ba2ccc  

I/DEBUG   (   89):          689b5c00  689b5c30  

I/DEBUG   (   89):          689b5c04  689b5c8c  

I/DEBUG   (   89):          689b5c08  65173e48  

I/DEBUG   (   89):          689b5c0c  40160ea9  /system/lib/libutils.so (android::Looper::addFd(int, int, int, android::sp<android::LooperCallback> const&, void*)+140)

I/DEBUG   (   89):     #01  689b5c10  00000002  

I/DEBUG   (   89):          689b5c14  00000000  

I/DEBUG   (   89):          689b5c18  00000004  

I/DEBUG   (   89):          689b5c1c  00000000  

I/DEBUG   (   89):          689b5c20  00000000  

I/DEBUG   (   89):          689b5c24  00000000  

I/DEBUG   (   89):          689b5c28  00000000  

I/DEBUG   (   89):          689b5c2c  fffffffe  

I/DEBUG   (   89):          689b5c30  647acc68  

I/DEBUG   (   89):          689b5c34  65173e50  

I/DEBUG   (   89):          689b5c38  00000000  

I/DEBUG   (   89):          689b5c3c  40ba2cb8  

I/DEBUG   (   89):          689b5c40  00000002  

I/DEBUG   (   89):          689b5c44  00000000  

I/DEBUG   (   89):          689b5c48  647acc68  

I/DEBUG   (   89):          689b5c4c  62d77670  

I/DEBUG   (   89):          ........  ........

I/DEBUG   (   89):     #02  689b5c80  689b5c8c  

I/DEBUG   (   89):          689b5c84  65173e50  

I/DEBUG   (   89):          689b5c88  00000ef4  

I/DEBUG   (   89):          689b5c8c  647acc68  

I/DEBUG   (   89):          689b5c90  401633a5  /system/lib/libutils.so

I/DEBUG   (   89):          689b5c94  65173e30  

I/DEBUG   (   89):          689b5c98  65173e28  

I/DEBUG   (   89):          689b5c9c  00000001  

I/DEBUG   (   89):          689b5ca0  62e167c0  

I/DEBUG   (   89):          689b5ca4  62e167c0  

I/DEBUG   (   89):          689b5ca8  64d6ed98  

I/DEBUG   (   89):          689b5cac  00000000  

I/DEBUG   (   89):          689b5cb0  00000002  

I/DEBUG   (   89):          689b5cb4  65173e50  

I/DEBUG   (   89):          689b5cb8  00000000  

I/DEBUG   (   89):          689b5cbc  61bc1067  /system/lib/libandroid.so (android::sp<android::Looper>::~sp()+14)

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near r1:

I/DEBUG   (   89):     40b9dfac 404afcc4 40b9dfb8 0000001b 00000001  

I/DEBUG   (   89):     40b9dfbc 00000001 40b9dfac 00000001 ffffffff  

I/DEBUG   (   89):     40b9dfcc 0000001b 402aba80 40b9dfe8 63a8fbd8  

I/DEBUG   (   89):     40b9dfdc 00000032 006e0061 0000001b 00000002  

I/DEBUG   (   89):     40b9dfec 00000002 40b9dfd0 00000000 0049002e  

I/DEBUG   (   89):     40b9dffc 00000043 401d2e9c 00000011 00000000  

I/DEBUG   (   89):     40b9e00c 00000001 00000000 00000000 401d2d50  

I/DEBUG   (   89):     40b9e01c 00000000 00000000 00000000 00000010  

I/DEBUG   (   89):     40b9e02c 00690057 40025048 401d2f04 40054c40  

I/DEBUG   (   89):     40b9e03c 000003ab 00000000 00000000 aa682400  

I/DEBUG   (   89):     40b9e04c fbf5e1cd 74add5ef 00000026 00000000  

I/DEBUG   (   89):     40b9e05c 00000000 00000000 ffc64300 ffffffff  

I/DEBUG   (   89):     40b9e06c ffffffff c3ffffff 00000045 00000000  

I/DEBUG   (   89):     40b9e07c 00000000 ffb81100 ffffffff ffffffff  

I/DEBUG   (   89):     40b9e08c ffffffff a7ffffff 0000000d 00000000  

I/DEBUG   (   89):     40b9e09c d9230000 ffffffff 89a9ebff a4867174  

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near r2:

I/DEBUG   (   89):     689b5c18 00000004 00000000 00000000 00000000  

I/DEBUG   (   89):     689b5c28 00000000 fffffffe 647acc68 65173e50  

I/DEBUG   (   89):     689b5c38 00000000 40ba2cb8 00000002 00000000  

I/DEBUG   (   89):     689b5c48 647acc68 62d77670 65173e48 400f6f01  

I/DEBUG   (   89):     689b5c58 00000002 401498ef 689b5c8c 00000000  

I/DEBUG   (   89):     689b5c68 40ba2cb8 00000002 00000001 647acc68  

I/DEBUG   (   89):     689b5c78 62d77670 40160fd9 689b5c8c 65173e50  

I/DEBUG   (   89):     689b5c88 00000ef4 647acc68 401633a5 65173e30  

I/DEBUG   (   89):     689b5c98 65173e28 00000001 62e167c0 62e167c0  

I/DEBUG   (   89):     689b5ca8 64d6ed98 00000000 00000002 65173e50  

I/DEBUG   (   89):     689b5cb8 00000000 61bc1067 00000002 61bc10dd  

I/DEBUG   (   89):     689b5cc8 65173e40 65173e38 62d68150 62e5b878  

I/DEBUG   (   89):     689b5cd8 62d5f1c0 65173e38 65173e28 62e167c0  

I/DEBUG   (   89):     689b5ce8 62d5fd20 62ec2e5c 64d6ed98 62d93508  

I/DEBUG   (   89):     689b5cf8 65173e30 61bd1428 6333e060 62d5f1c0  

I/DEBUG   (   89):     689b5d08 689b5d80 00000000 6f6c4320 62d5f1c0  

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near r5:

I/DEBUG   (   89):     40ba2ccc 00000001 00000007 00000004 402ab398  

I/DEBUG   (   89):     40ba2cdc 63a9dd28 00000001 00000007 00000004  

I/DEBUG   (   89):     40ba2cec 00000000 00000001 40b9dfd0 00000002  

I/DEBUG   (   89):     40ba2cfc 00000000 0000002b 00000000 126fdac8  

I/DEBUG   (   89):     40ba2d0c 00000049 00000001 00001002 00000000  

I/DEBUG   (   89):     40ba2d1c 00000000 00000000 00000000 00000000  

I/DEBUG   (   89):     40ba2d2c 00000000 126fdac8 00000049 00000000  

I/DEBUG   (   89):     40ba2d3c 00000000 3f74c6b0 3f063017 00000001  

I/DEBUG   (   89):     40ba2d4c 00000000 00000000 00000001 000001ff  

I/DEBUG   (   89):     40ba2d5c 00000000 446dee84 445d4d3d 3f800000  

I/DEBUG   (   89):     40ba2d6c 3d989899 41e079c5 41e079c5 41e079c5  

I/DEBUG   (   89):     40ba2d7c 41e079c5 3fc90fda 00000000 00000000  

I/DEBUG   (   89):     40ba2d8c 00000000 00000000 00000000 00000000  

I/DEBUG   (   89):     40ba2d9c 00000000 00000000 00000000 00000000  

I/DEBUG   (   89):     40ba2dac 00000000 00000000 00000000 00000000  

I/DEBUG   (   89):     40ba2dbc 00000000 00000000 00000000 00000000  

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near r6:

I/DEBUG   (   89):     40b9dfac 404afcc4 40b9dfb8 0000001b 00000001  

I/DEBUG   (   89):     40b9dfbc 00000001 40b9dfac 00000001 ffffffff  

I/DEBUG   (   89):     40b9dfcc 0000001b 402aba80 40b9dfe8 63a8fbd8  

I/DEBUG   (   89):     40b9dfdc 00000032 006e0061 0000001b 00000002  

I/DEBUG   (   89):     40b9dfec 00000002 40b9dfd0 00000000 0049002e  

I/DEBUG   (   89):     40b9dffc 00000043 401d2e9c 00000011 00000000  

I/DEBUG   (   89):     40b9e00c 00000001 00000000 00000000 401d2d50  

I/DEBUG   (   89):     40b9e01c 00000000 00000000 00000000 00000010  

I/DEBUG   (   89):     40b9e02c 00690057 40025048 401d2f04 40054c40  

I/DEBUG   (   89):     40b9e03c 000003ab 00000000 00000000 aa682400  

I/DEBUG   (   89):     40b9e04c fbf5e1cd 74add5ef 00000026 00000000  

I/DEBUG   (   89):     40b9e05c 00000000 00000000 ffc64300 ffffffff  

I/DEBUG   (   89):     40b9e06c ffffffff c3ffffff 00000045 00000000  

I/DEBUG   (   89):     40b9e07c 00000000 ffb81100 ffffffff ffffffff  

I/DEBUG   (   89):     40b9e08c ffffffff a7ffffff 0000000d 00000000  

I/DEBUG   (   89):     40b9e09c d9230000 ffffffff 89a9ebff a4867174  

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near r7:

I/DEBUG   (   89):     40b9dfac 404afcc4 40b9dfb8 0000001b 00000001  

I/DEBUG   (   89):     40b9dfbc 00000001 40b9dfac 00000001 ffffffff  

I/DEBUG   (   89):     40b9dfcc 0000001b 402aba80 40b9dfe8 63a8fbd8  

I/DEBUG   (   89):     40b9dfdc 00000032 006e0061 0000001b 00000002  

I/DEBUG   (   89):     40b9dfec 00000002 40b9dfd0 00000000 0049002e  

I/DEBUG   (   89):     40b9dffc 00000043 401d2e9c 00000011 00000000  

I/DEBUG   (   89):     40b9e00c 00000001 00000000 00000000 401d2d50  

I/DEBUG   (   89):     40b9e01c 00000000 00000000 00000000 00000010  

I/DEBUG   (   89):     40b9e02c 00690057 40025048 401d2f04 40054c40  

I/DEBUG   (   89):     40b9e03c 000003ab 00000000 00000000 aa682400  

I/DEBUG   (   89):     40b9e04c fbf5e1cd 74add5ef 00000026 00000000  

I/DEBUG   (   89):     40b9e05c 00000000 00000000 ffc64300 ffffffff  

I/DEBUG   (   89):     40b9e06c ffffffff c3ffffff 00000045 00000000  

I/DEBUG   (   89):     40b9e07c 00000000 ffb81100 ffffffff ffffffff  

I/DEBUG   (   89):     40b9e08c ffffffff a7ffffff 0000000d 00000000  

I/DEBUG   (   89):     40b9e09c d9230000 ffffffff 89a9ebff a4867174  

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near r9:

I/DEBUG   (   89):     689b5c18 00000004 00000000 00000000 00000000  

I/DEBUG   (   89):     689b5c28 00000000 fffffffe 647acc68 65173e50  

I/DEBUG   (   89):     689b5c38 00000000 40ba2cb8 00000002 00000000  

I/DEBUG   (   89):     689b5c48 647acc68 62d77670 65173e48 400f6f01  

I/DEBUG   (   89):     689b5c58 00000002 401498ef 689b5c8c 00000000  

I/DEBUG   (   89):     689b5c68 40ba2cb8 00000002 00000001 647acc68  

I/DEBUG   (   89):     689b5c78 62d77670 40160fd9 689b5c8c 65173e50  

I/DEBUG   (   89):     689b5c88 00000ef4 647acc68 401633a5 65173e30  

I/DEBUG   (   89):     689b5c98 65173e28 00000001 62e167c0 62e167c0  

I/DEBUG   (   89):     689b5ca8 64d6ed98 00000000 00000002 65173e50  

I/DEBUG   (   89):     689b5cb8 00000000 61bc1067 00000002 61bc10dd  

I/DEBUG   (   89):     689b5cc8 65173e40 65173e38 62d68150 62e5b878  

I/DEBUG   (   89):     689b5cd8 62d5f1c0 65173e38 65173e28 62e167c0  

I/DEBUG   (   89):     689b5ce8 62d5fd20 62ec2e5c 64d6ed98 62d93508  

I/DEBUG   (   89):     689b5cf8 65173e30 61bd1428 6333e060 62d5f1c0  

I/DEBUG   (   89):     689b5d08 689b5d80 00000000 6f6c4320 62d5f1c0  

I/DEBUG   (   89): 

I/DEBUG   (   89): memory near sp:

I/DEBUG   (   89):     689b5bc8 62d5f370 62d5f370 689b5bf8 633100b0  

I/DEBUG   (   89):     689b5bd8 00000001 62d641c8 df0027ad 00000000  

I/DEBUG   (   89):     689b5be8 00000000 00000000 40ba2cb8 00000000  

I/DEBUG   (   89):     689b5bf8 40ba2cec 40ba2ccc 689b5c30 689b5c8c  

I/DEBUG   (   89):     689b5c08 65173e48 40160ea9 00000002 00000000  

I/DEBUG   (   89):     689b5c18 00000004 00000000 00000000 00000000  

I/DEBUG   (   89):     689b5c28 00000000 fffffffe 647acc68 65173e50  

I/DEBUG   (   89):     689b5c38 00000000 40ba2cb8 00000002 00000000  

I/DEBUG   (   89):     689b5c48 647acc68 62d77670 65173e48 400f6f01  

I/DEBUG   (   89):     689b5c58 00000002 401498ef 689b5c8c 00000000  

I/DEBUG   (   89):     689b5c68 40ba2cb8 00000002 00000001 647acc68  

I/DEBUG   (   89):     689b5c78 62d77670 40160fd9 689b5c8c 65173e50  

I/DEBUG   (   89):     689b5c88 00000ef4 647acc68 401633a5 65173e30  

I/DEBUG   (   89):     689b5c98 65173e28 00000001 62e167c0 62e167c0  

I/DEBUG   (   89):     689b5ca8 64d6ed98 00000000 00000002 65173e50  

I/DEBUG   (   89):     689b5cb8 00000000 61bc1067 00000002 61bc10dd  

I/DEBUG   (   89): 

I/DEBUG   (   89): code around pc:

I/DEBUG   (   89):     4015e398 68874605 46904689 a004f8d0 f8d03f01  

I/DEBUG   (   89):     4015e3a8 2400b010 1b39e011 464a6828 76d1eb01  

I/DEBUG   (   89):     4015e3b8 46286c03 0666eb04 a106fb0b 28004798  

I/DEBUG   (   89):     4015e3c8 da01d008 e0001c74 42bc1e77 f06fddeb  

I/DEBUG   (   89):     4015e3d8 e0010001 46304634 0f00f1b8 f8c8d001  

I/DEBUG   (   89):     4015e3e8 e8bd4000 b5078ff8 f7ffaa01 9801ffcf  

I/DEBUG   (   89):     4015e3f8 2200bd0e bfcaf7ff aa01b537 460c4605  

I/DEBUG   (   89):     4015e408 ffc4f7ff 46024621 46282a00 9a01da04  

I/DEBUG   (   89):     4015e418 f7ff2301 e001fec3 fda6f7ff e92dbd3e  

I/DEBUG   (   89):     4015e428 460741f0 b184688c 8010f8d0 684e2500  

I/DEBUG   (   89):     4015e438 46384631 ffe0f7ff 28004446 3501db06  

I/DEBUG   (   89):     4015e448 d1f542a5 e8bd2000 462081f0 81f0e8bd  

I/DEBUG   (   89):     4015e458 4604b538 460d6888 d0292800 46281e41  

I/DEBUG   (   89):     4015e468 fcbef7ff 46016862 6c036820 47984620  

I/DEBUG   (   89):     4015e478 dc062800 46294620 e8bd2200 f7ff4038  

I/DEBUG   (   89):     4015e488 68a2bee6 1e514620 fcaaf7ff 6c0b6821  

I/DEBUG   (   89): 

I/DEBUG   (   89): code around lr:

I/DEBUG   (   89):     40160e88 46312210 9309a802 ec6cf7f7 f1059702  

I/DEBUG   (   89):     40160e98 a90a0734 4638960d 940a9404 faa9f7fd  

I/DEBUG   (   89):     40160ea8 a80b4606 fbe6f7ff 6b282e00 2101da1e  

I/DEBUG   (   89):     40160eb8 ab024622 ecc2f7f7 da072800 eb08f7f7  

I/DEBUG   (   89):     40160ec8 4a2c492b 447a4479 e01d6803 a906ad14  

I/DEBUG   (   89):     40160ed8 4d14f845 46201d2c ff86f7ff 46294638  

I/DEBUG   (   89):     40160ee8 fa8af7fd f7ff4620 e02cfbc5 46222103  

I/DEBUG   (   89):     40160ef8 f7f7ab02 2800eca4 f7f7da12 491eeaea  

I/DEBUG   (   89):     40160f08 44794a1e 6803447a 20069300 f7f74623  

I/DEBUG   (   89):     40160f18 a806ea5c fbaef7ff f7f74640 e01aea68  

I/DEBUG   (   89):     40160f28 428e6be9 4631d20f f7fd4638 9b06f80c  

I/DEBUG   (   89):     40160f38 60434649 98074604 f10460a0 f7ff000c  

I/DEBUG   (   89):     40160f48 9a09fd79 a8066122 fb94f7ff f7f74640  

I/DEBUG   (   89):     40160f58 2001ea4e f04fe001 b01430ff 87f0e8bd  

I/DEBUG   (   89):     40160f68 000023b8 00002672 000023a8 000026a8  

I/DEBUG   (   89):     40160f78 00002326 0000265b 000022e8 0000264b  

I/BootReceiver(  343): Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)

I/ActivityManager(  343): Process org.koreader.launcher (pid 905) has died.

**Comment by chrox** [comment]
Duplicated to #643.
