### ISSUE TITLE
Freezes and instabilities on Android Samsung Tab CM11 (logs, trace included)

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1692]
Basically KR either never starts or starts after taking 10 mins of black  screen. After it starts I can never open a book successfully, it seems to crash at some point during file browsing.

require("jit.v").start("/sdcard/my_dump.txt")
http://www.pasteall.org/61861

mixed luajit log
http://www.pasteall.org/61862

I tried the code below which did not help much
'''
require("jit.opt").start("sizemcode=256","maxmcode=256") for i=1,100 do end -- Force allocation of one large segment 
'''

memory map
http://www.pasteall.org/61863

**Comment by Frenzie** [comment]
Thanks for the trace! I'll close this now because blitbuffer.c should've theoretically made all this better on Android.
