### ISSUE TITLE
FR: Edge darkening

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1694]
Hi

Given that most displays have extra brightness around the edges, it would be very beneficial to have a way to darken the edges. This could be three sliders or three multipler that lets user the control the darkness of the overlay, the spread of the overlay and the placement/shifting of the darkening(left to right)

This post processing or overlay can make the page look more uniform or even give a sense of a book page.
 

thanks

**Comment by chrox** [comment]
Never notice this phenomenon on my Kindle. Isn't this a hardware design problem?

**Comment by gerroon** [comment]
Well all my tablets and ereaders have some brightness issues around the edges. Some has it more than the others. Some are unnoticiable but darkening can help in general I think. 

I will make a mock up to show what I am talking about.

**Comment by Frenzie** [comment]
@chrox I assume this is talking about backlight bleeding? In any case this kind of goes along with #1653. For example, you can already use [linear-gradients](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) in CSS backgrounds.

**Comment by gerroon** [comment]
Frenzie is on it. I personally also would like to see this in pdf files too not just epubs

**Comment by chrox** [comment]
Close this in favor of #1653.
