### ISSUE TITLE
The screen becomes white while opening some epub files

### ISSUE THREAD

**Issue by thegreatgod** [koreader/koreader#1697]
My device is PB840. Sometimes the screen becomes full white when I try to open a epub file even if the file was opened successfully before.
Strangely, if the device is plugged into electricity, this issue never appears and the fact may speed up the progress of opening the file.
Nothing works but quit koreader by force with both pageup and pagedown button pushed when the White Screen Issue happens.
Someone told me that it may be caused by the increased frequency of arm CPU when charging.

**Comment by thegreatgod** [comment]
Nothing works except quitting koreader by force when the White Screen Issue happens.
Someone told me that it may be caused by the increased frequency of arm CPU when charging.

**Comment by chrox** [comment]
Duplicated to #1596, closing this now.
