### ISSUE TITLE
What could cause koreader to become sluggish and non-responsive?

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1698]
I got a Glo that sometimes freezes in Nickel. So I read in koreader.
However, yesterday evening koreader froze, too. First it became sluggish, a great delay between taps and actions, resulting in turning pages backwards for a few minutes. After that it became utterly unresponsive. In the morning I was able to change the menu and a few pages, before it became unresponsive again. After rebooting it runs beautifully, again. The crash.log reports: `Nothing similar to on, sorry :(`. No idea what that means.

Anyone an idea what could cause koreader to become sluggish and non-responsive? 

Is there read-write action going on in the background? IO could typically freeze a system like that. 
Any suggestions would be nice! Since I can't think of anything else besides switching out the SD-card, it would be nice if it was IO, but I don't see what file action would be necessary while changing pages or menu's.

**Comment by NiLuJe** [comment]
If/Next time it happens, check the state of the system's resources (CPU/MEM) over SSH, that should hopefully point somewhere.

**Comment by NiLuJe** [comment]
As for that message in the crash log, that's just from sdcv ;).

**Comment by Markismus** [comment]
Thanks. 
Hadn't recognized it as an sdcv output. Still odd that it ends up in the crash.log

**Comment by NiLuJe** [comment]
IIRC, we eat stderr, so anything we spawn that spouts stuff to stderr will end up in there ;).
