### ISSUE TITLE
building glib for Kindle fails due to missing gettext library

### ISSUE THREAD

**Issue by mixaz** [koreader/koreader#1699]
I'm building KOReader for Amazon Kindle, host OS is Ubuntu 14.04 LTS. I followed instructions in README.md, but build fails for glib with following message:

    make TARGET=kindle clean update
    ...
    checking for msgfmt... no
    configure: error: 
    *** You must have either have gettext support in your C library, or use the
    *** GNU gettext library. (http://www.gnu.org/software/gettext/gettext.html

More detailed log is here: http://pastebin.com/9DC4An1R

I see in logs some gettext related messages:

    configure: WARNING: unrecognized options: --without-included-gettext, --with-gettext

I tried to use an older glib version but it fails the same. I wonder what could cause the issue.

Could somebody confirm that building for Kindle works OK? I guess that the Kindle build might become broken because it is rarely used.

Info about my setup:

    $uname -a
    Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015 i686 i686 i686 GNU/Linux

gcc-arm-linux-gnueabi 4:4.7.2-1
g++-arm-linux-gnueabi 4:4.7.2-1

**Comment by NiLuJe** [comment]
Worksforme.

The build *does* need something else in your sysroot that we don't build (because it's in most TC's base sysroot), but I can't for the life of me remember what. I've mentioned here here on GH somewhere, but good luck with that ;p.

But that's not even relevant here, since I'm pretty sure you need gettext on your *host* platform, not for the target's. And gettext should *definitely* be a part of any basic development environment.

**Comment by mixaz** [comment]
Indeed, installing gettext package on host solved the issue. May be it's worth adding it to README.md to the list of packages required on host?

I didn't realize that the issue was about missing gettext on host, I thought `configure` checks target platform. How did you understand that the issue is on host side?

I think that it's OK to close the ticket, the build now works for me. Thanks!

**Comment by Markismus** [comment]
That could be a leftover, since we abandoned the gettext package in favour of a lua-implementation. 
Is the gettext package required by third-party software?

**Comment by Frenzie** [comment]
> Indeed, installing gettext package on host solved the issue. May be it's worth adding it to README.md to the list of packages required on host?

Hm, perhaps. I see that [autoconf](http://packages.ubuntu.com/trusty/autoconf) only suggests gettext, so I'd say it's part an implicit "it's at your own risk if you don't install suggested packages". Basically you're very consciously doing something different than the instructions.

**Comment by NiLuJe** [comment]
Gettext is nearly an integral part of the autotools suite, it's used at build-time in nearly everything with NLS/I18N support to compile the binary translation files at build-time.

(In Gentoo speak, it's part of the system set of packages. It's also part of the basic packages needed to build anything).

**Comment by mixaz** [comment]
I see, thanks for clarifications
