### ISSUE TITLE
Deleting highlights doesn't really work

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#1702]
Everytime I tap on a highlight the Unhighlight option is greyed out. Highlights also keep getting rendered after I delete them in Bookmarks menu though the program starts behaving like they actually are deleted when I tap them.
I use the latest build on Kindle Touch.

**Comment by chrox** [comment]
Is this for PDF documents?

**Comment by GeneralFailer** [comment]
No, I've tested FB2 and EPUB files.

**Comment by chrox** [comment]
I still cannot reproduce this issue. Could you post a screenshot of your problem?

**Comment by GeneralFailer** [comment]
I've installed the latest build and the greyed-out Unhighlight button now appears only for highlights consisting of one word, the highlights with spaces can be highlighted several times which makes the highlight darker. I think it was different in the build I used before.
The first one here was highlighted three times and the second one was deleted via the Bookmarks menu.
![reader_2016-mar-06_060436](https://cloud.githubusercontent.com/assets/9321788/13554295/2fa53ad4-e3b5-11e5-9f9f-d6ca6f3de5f0.png)
![reader_2016-mar-06_060453](https://cloud.githubusercontent.com/assets/9321788/13554296/2fb70016-e3b5-11e5-8efe-90913d9bbabd.png)
![reader_2016-mar-06_060527](https://cloud.githubusercontent.com/assets/9321788/13554297/2fbbc1fa-e3b5-11e5-9bde-01d88242ebbc.png)

**Comment by chrox** [comment]
You can delete a highlight by tapping on the highlight and selecting the delete option in the popup dialog. Removing bookmarks of highlights doesn't remove highlighs themselves.

**Comment by GeneralFailer** [comment]
Ah, that one works. I think this is very unintuitive when coming from Kindle's default reader app, especially considering this is not mentioned in the wiki. The greyed-out Unhighlight button contributes to the confusion.

**Comment by houqp** [comment]
@GeneralFailer , could you help improve that section of the wiki from a user's point of view? I am sure other people will run into this in the future ;)

**Comment by GeneralFailer** [comment]
English isn't my native language, but here you go.
https://github.com/koreader/koreader/wiki/KOReader-Gestures

**Comment by houqp** [comment]
Looks great to me. Thank you so much @GeneralFailer  :)
