### ISSUE TITLE
Android: KR does not show up in the app list if the filename has an extra period in it.

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1704]
For a long time I was trying to figure out why KR was not showing in the applist with some pdf files. It would show up fine for most pdfs but not so for others. I think that I figured out the cause. 

If the file name has an extra period in the file name KR wont show up in the open with app list on Android. For instance if the filename is like this  "Joe W. Writer-Love in Somewhere.pdf". That period after W confuses KR. That does not seem to be an issue with other apps.

**Comment by Frenzie** [comment]
I guess there's something strange about those Android filename patterns; in principle it looks to me like they should match anything (.*) that ends in .pdf, but e.g. the Document VIewer app has [this ridiculous looking workaround](https://github.com/SufficientlySecure/document-viewer/blob/b93d66b11af89ee9b3916427f079af7032a2c007/document-viewer/src/main/AndroidManifest.xml#L92-L120).

```xml
                <!-- Workaround to match files in pathes with dots in them, like /cdcard/my.folder/test.pdf -->
                <data android:pathPattern=".*\\.pdf" />
                <data android:pathPattern=".*\\..*\\.pdf" />
                <data android:pathPattern=".*\\..*\\..*\\.pdf" />
                <data android:pathPattern=".*\\.djvu" />
                <data android:pathPattern=".*\\..*\\.djvu" />
                <data android:pathPattern=".*\\..*\\..*\\.djvu" />
                <data android:pathPattern=".*\\.djv" />
                <data android:pathPattern=".*\\..*\\.djv" />
                <data android:pathPattern=".*\\..*\\..*\\.djv" />
                <data android:pathPattern=".*\\.xps" />
                <data android:pathPattern=".*\\..*\\.xps" />
                <data android:pathPattern=".*\\..*\\..*\\.xps" />
                <data android:pathPattern=".*\\.oxps" />
                <data android:pathPattern=".*\\..*\\.oxps" />
                <data android:pathPattern=".*\\..*\\..*\\.oxps" />
                <data android:pathPattern=".*\\.cbz" />
                <data android:pathPattern=".*\\..*\\.cbz" />
                <data android:pathPattern=".*\\..*\\..*\\.cbz" />
                <!-- <data android:pathPattern=".*\\.cbr" /> -->
                <data android:pathPattern=".*\\.epub" />
                <data android:pathPattern=".*\\..*\\.epub" />
                <data android:pathPattern=".*\\..*\\..*\\.epub" />
                <data android:pathPattern=".*\\.fb2" />
                <data android:pathPattern=".*\\..*\\.fb2" />
                <data android:pathPattern=".*\\..*\\..*\\.fb2" />
                <data android:pathPattern=".*\\.fb2\\.zip" />
                <data android:pathPattern=".*\\..*\\.fb2\\.zip" />
                <data android:pathPattern=".*\\..*\\..*\\.fb2\\.zip" />
```

Also see [this question on SO](http://stackoverflow.com/questions/3400072/pathpattern-to-match-file-extension-does-not-work-if-a-period-exists-elsewhere-i).

**Comment by chrox** [comment]
@Frenzie Nice workaround. :P Could you send a pull request to koreader/android-luajit-launcher?

**Comment by Frenzie** [comment]
Sure, probably not until tomorrow though.
