### ISSUE TITLE
lookup ancient greek words in the dictionary window.

### ISSUE THREAD

**Issue by didina44** [koreader/koreader#1705]
This is my first use of github, so apologies for any awkwardness. Basically, when looking up ancient greek words in the dictionary window, in order to use the newly implemented feature of koreader, I can only select a letter upon pressing a word, but not the word itself. This happens with all ancient greek dictionaries I have, for instance with those posted by Rosen on Mobilereads , namely Greek Analyses and Middle Liddle, here
 http://www.mobileread.com/forums/showthread.php?t=256360

This problem with just selecting a letter when pressing a word was present with kobo reader, that is why I switched to Koreader, because it could select a word in the greek text. But then, as I said, when looking inside the dictionary window, this selection problem shows up. 

I don't know if this can be solved, but just to say I think what you do with this reader is really great, and you have helped me a lot in my work.

**Comment by Markismus** [comment]
I remembered initially having [the same problem in the reader in issue #279.](https://github.com/koreader/koreader/issues/279#issuecomment-26517278) 
[In issue #327](https://github.com/koreader/koreader/issues/327#issuecomment-27073272), I mention [a commit of chrox](https://github.com/koreader/koreader/commit/2590cc7ca5e943910f2430f2516cf1f21d74c7f4) that fixed it.

Could it be that an analogue fix is needed?

**Comment by chrox** [comment]
It's a bug in the text segmentation. The text is segmented to characters for non-ascii encoded text [here](https://github.com/koreader/koreader/blob/master/frontend/ui/widget/textboxwidget.lua#L86). It's OK for Chinese and Japanese, but apparently unacceptable for non-ascii Western languages. I'll try to fix this.

**Comment by Markismus** [comment]
` for words in line:gmatch("[\32-\127\192-\255]+[\128-\191]*") do`

Are \32-\127 etc. the patterns for decimal utf-8 values?

**Comment by didina44** [comment]
Hello,

I was just wondering if by any chance you thought of some way to fix this
problem. It would be really great for users of ancient greek dictionary.
Sorry to bother you with this, you have enabled great features to Koreader,
I dare to ask about this thinking it might just have escaped your notice.

Thank you very much.

**Comment by houqp** [comment]
I added this to next release milestone. @chrox are you still working on this? If not I can take a look.

**Comment by didina44** [comment]
Thank you!

**Comment by chrox** [comment]
Sorry, I'm afraid I forgot this. You can take this of course.

**Comment by didina44** [comment]
THANK YOU!!
