### ISSUE TITLE
Render reflowed PDF with upper and lower margin

### ISSUE THREAD

**Issue by jbaumann** [koreader/koreader#1714]
Currently reflowed PDFs are rendered with the full vertical height, leaving no upper and lower margin (right and left margin work).

Instead it would be nice if the behaviour would be configurable.

**Comment by chrox** [comment]
Sounds reasonable. I will implement it later. Thanks.

**Comment by turkeyphant** [comment]
Doesn't seem to be fixed. Still no top/bottom margins at all in reflowed documents.

* KOReader version: v2018.12
* Device: Kobo_nova (Kobo Clara HD)

#### Issue
No matter which of the three margin settings are chosen when reflowing PDFs, there is no margin whatsoever at the top and bottom of the screen. In fact, text is frequently cut off.

![reader_2018-dec-07_160749](https://user-images.githubusercontent.com/8129583/49659028-3db3ad00-fa3b-11e8-95ad-675ff18ea531.png)

#### Steps to reproduce
Open text PDF, enable reflow, disable scroll.

In addition, changing margin settings in defaults.lua doesn't seem to help.
