### ISSUE TITLE
pillow interrogatePillow cann't work

### ISSUE THREAD

**Issue by DreamLiMu** [koreader/koreader#1716]
Have any method to make "lipc-set-prop com.lab126.pillow interrogatePillow ${MESSAGE}" work?

**Comment by NiLuJe** [comment]
Since FW 5.6.5, no idea. Never was my area of expertise, so I couldn't tell you what changed. I see no reason why it couldn't be done though, so, hey, good luck ;p.

**Comment by DreamLiMu** [comment]
Ok ,thanks!

**Comment by NiLuJe** [comment]
We can probably close this, since it barely has anything to do with us ;).
