### ISSUE TITLE
/usr/include/bits/mathinline.h:790:3: error: impossible constraint in 'asm'

### ISSUE THREAD

**Issue by hy0kl** [koreader/koreader#1717]
`Linux ubuntu 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

$ arm-linux-androideabi-gcc -v
Using built-in specs.
COLLECT_GCC=arm-linux-androideabi-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-androideabi/4.7.3/lto-wrapper
Target: arm-linux-androideabi
Configured with: ../src/configure --prefix=/usr --libexecdir=/usr/lib --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=arm-linux-androideabi --with-build-sysroot=/build/buildd/gcc-arm-linux-androideabi-0.20130705.1/sys-root --disable-multilib --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --disable-ppl-version-check --disable-cloog-version-check --enable-cloog-backend=isl --disable-libssp --disable-nls --disable-libmudflap --disable-shared --disable-sjlj-exceptions --disable-libquadmath --disable-libitm --disable-libatomic --with-float=soft --with-fpu=vfp --with-arch=armv5te --enable-target-optspace --disable-docs --disable-nls --enable-threads --enable-tls --enable-libgomp --disable-libitm --disable-libatomic --disable-libstdc__-v3
Thread model: posix
gcc version 4.7.3 (Linaro GCC 4.7-2014.01) 

$ make TARGET=android
...
make all "LJCORE_O=ljamalg.o"
make[4]: Entering directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
CC        ljamalg.o
In file included from lj_obj.h:14:0,
                 from lj_gc.c:12,
                 from ljamalg.c:31:
lj_arch.h:496:0: warning: "LUAJIT_NO_LOG2" redefined
 #define LUAJIT_NO_LOG2
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/math.h:426:0,
                 from lj_vmmath.c:10,
                 from ljamalg.c:46:
lj_strscan.c: In function 'strscan_double':
/usr/include/bits/mathinline.h:790:3: error: impossible constraint in 'asm'
   __ldexp_code;
   ^
make[4]: *** [ljamalg.o] Error 1
make[4]: Leaving directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
make[3]: *** [amalg] Error 2
make[3]: Leaving directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
make[2]: *** [amalg] Error 2
make[2]: Leaving directory `/home/parallels/dev/koreader/base/luajit-2.0'
make[1]: *** [build/arm-linux-androideabi/libs/libluajit.so] Error 2
make[1]: Leaving directory `/home/parallels/dev/koreader/base'
make: *** [all] Error 2
```

**Comment by NiLuJe** [comment]
Is that a standard NDK toolchain?

**Comment by hy0kl** [comment]
$ make android-toolchain 
make -C base android-toolchain
make[1]: Entering directory `/home/parallels/dev/koreader/base'
mkdir -p toolchain/android-toolchain
/home/parallels/src/ndk/android-ndk-r10e/build/tools/make-standalone-toolchain.sh --platform=android-9 \
		--install-dir=toolchain/android-toolchain
Copying prebuilt binaries...
Copying sysroot headers and libraries...
Copying c++ runtime headers and libraries...
Copying files to: toolchain/android-toolchain
Cleaning up...
Done.
make[1]: Leaving directory `/home/parallels/dev/koreader/base'

**Comment by NiLuJe** [comment]
It shouldn't be pulling includes from /usr, make sure you don't have stray SYSROOT set in your env...

**Comment by NiLuJe** [comment]
Alternatively, try patching koreader-base's Makefile.defs @ L44 from
```
export SYSROOT=$(NDK)/platforms/android-9/arch-arm
```
to
```
export SYSROOT=$(CURDIR)/$(ANDROID_TOOLCHAIN)/sysroot
```

**Comment by NiLuJe** [comment]
Alternatively, that might just be your host's toolchain that's borked, I forgot that LuaJIT builds some stuff on the host first.

**Comment by hy0kl** [comment]
I use `export SYSROOT=$(CURDIR)/$(ANDROID_TOOLCHAIN)/sysroot`,and no SYSROOT in env.

then:
$ make TARGET=android clean androidupdate
rm -rf koreader-android-arm-linux-androideabi
MAKE -C base clean
make -C base
make[1]: Entering directory `/home/parallels/dev/koreader/base'
mkdir -p build/arm-linux-androideabi/libs
# To recap: build its TARGET_CC from CROSS+CC, so we need HOSTCC in CC.
# Build its HOST/TARGET_CFLAGS based on CFLAGS, so we need
# a neutral CFLAGS without arch
make -j2 -C luajit-2.0 \
		CC="gcc" HOST_CC="gcc -m32" \
		CFLAGS="-O2 -ffast-math -pipe -fomit-frame-pointer" HOST_CFLAGS="-march=native -O2 -ffast-math -pipe -fomit-frame-pointer " \
		 \
		 \
		TARGET_SONAME=libluajit.so \
		TARGET_CFLAGS="-O2 -ffast-math -pipe -fomit-frame-pointer  --sysroot /home/parallels/dev/koreader/base/toolchain/android-toolchain/sysroot -march=armv7-a -mfpu=vfpv3-d16 -mthumb -ffunction-sections -funwind-tables -fstack-protector -no-canonical-prefixes -mfloat-abi=softfp  -fPIC" \
		TARGET_FLAGS="-DLUAJIT_NO_LOG2 -DLUAJIT_NO_EXP2" \
		CROSS="arm-linux-androideabi-" amalg
make[2]: Entering directory `/home/parallels/dev/koreader/base/luajit-2.0'
Building LuaJIT 2.1.0-beta1
make -C src amalg
make[3]: Entering directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
+--------------------------------------------------------------------------+
| WARNING: Compiling the amalgamation needs a lot of virtual memory        |
| (around 300 MB with GCC 4.x)! If you don't have enough physical memory   |
| your machine will start swapping to disk and the compile will not finish |
| within a reasonable amount of time.                                      |
| So either compile on a bigger machine or use the non-amalgamated build.  |
+--------------------------------------------------------------------------+
make all "LJCORE_O=ljamalg.o"
make[4]: Entering directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
CC        luajit.o
In file included from luajit.c:20:0:
lj_arch.h:496:0: warning: "LUAJIT_NO_LOG2" redefined
 #define LUAJIT_NO_LOG2
 ^
<command-line>:0:0: note: this is the location of the previous definition
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
BUILDVM   lj_ffdef.h
BUILDVM   lj_folddef.h
BUILDVM   lj_bcdef.h
BUILDVM   lj_recdef.h
BUILDVM   lj_libdef.h
BUILDVM   jit/vmdef.lua
ASM       lj_vm.o
CC        ljamalg.o
In file included from lj_obj.h:14:0,
                 from lj_gc.c:12,
                 from ljamalg.c:31:
lj_arch.h:496:0: warning: "LUAJIT_NO_LOG2" redefined
 #define LUAJIT_NO_LOG2
 ^
<command-line>:0:0: note: this is the location of the previous definition
In file included from /usr/include/math.h:426:0,
                 from lj_vmmath.c:10,
                 from ljamalg.c:46:
lj_strscan.c: In function 'strscan_double':
/usr/include/bits/mathinline.h:790:3: error: impossible constraint in 'asm'
   __ldexp_code;
   ^
make[4]: *** [ljamalg.o] Error 1
make[4]: Leaving directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
make[3]: *** [amalg] Error 2
make[3]: Leaving directory `/home/parallels/dev/koreader/base/luajit-2.0/src'
make[2]: *** [amalg] Error 2
make[2]: Leaving directory `/home/parallels/dev/koreader/base/luajit-2.0'
make[1]: *** [build/arm-linux-androideabi/libs/libluajit.so] Error 2
make[1]: Leaving directory `/home/parallels/dev/koreader/base'
make: *** [all] Error 2

Where is log do you mean?

**Comment by hy0kl** [comment]
It is my mistake.

if has `/usr/include/bits/mathinline.h error: impossible constraint in 'asm'` error, try it:

```
$ export LIBRARY_PATH=""
$ export C_INCLUDE_PATH=""
$ export CPLUS_INCLUDE_PATH=""
```
