### ISSUE TITLE
Save the statistics data into the history file

### ISSUE THREAD

**Issue by apletnev** [koreader/koreader#1718]
Instead of using additional folder with stat files, regarding #1712 we decided to move the data in to the history file of book. Also to reduce size of history file, change format of statistics data like this:

	["stats"] = {
		["total_time"] = 18,
		["authors"] = "William Shakespeare",
		["title"] = "Romeo and Juliet",
		["notes"] = 0,
		["highlights"] = 0,
		["pages"] = 202,
		["details"] = {
			[1448142254] = 1,
			[1447682801] = 2,
			[1448142299] = 3,
			[1448142263] = 2,
			[1448142306] = 5,
			[1448142302] = 4
		},
		["series"] = "",
		["language"] = "en"
	}

Details contains in key - timestamp, in value - page

**Comment by chrox** [comment]
Just some random thoughts about the naming of the variables. `total_time` could be `total_time_in_sec` or `total_time_in_min` and there may be a better name for `details` like `pages_read_in_(minute?)`.
