### ISSUE TITLE
[Feature request] Limited word editor

### ISSUE THREAD

**Issue by boriar** [koreader/koreader#1719]
May be it posible to include a word editor? I don't say a complete epub editor but a only word editor, because so many times I read epub with mistakes inexactitudes or something like that, and it's a pain to take note of all of they to fix later.

**Comment by KenMaltby** [comment]
I take it you mean something where you would be able to highlight a word or some characters and use the existing keyboard to type in replacement text?  It might be a step toward the note taking function. Perhaps as an insert.  Perhaps, if inside brackets, it could also be treated as a note, instead of as a correction.

**Comment by boriar** [comment]
That's exactly what I said. I would to correct ocr's epubs or badly wording directly while I'm reading and not wait to do it later. Well, I can take a snapshot or a note (on ereader or in a notebook), but always after read the book and in a PC (that I don't like).

**Comment by AlanSP1** [comment]
Speaking about editing files, if it would be possible that we can open config files (defaults.lua) and edit them from koreader (it needs reboot to take effect anyway), it would really be great. Or some other file accessible through file manager (at the moment it shows only ebook files).

This would enable us to avoid using computer for some small and easy changes.

It just looks like interesting idea.

**Comment by boriar** [comment]
Please.
Can someone put the label: Feature request for this open issue?
I don't how and even I know if I can do it.
Thanks

**Comment by Frenzie** [comment]
@AlanSP1 Note that there's a little text editor in vlasovsoftlauncher.

**Comment by AlanSP1** [comment]
Didn't know about that, I have his package installed, but I never use it. I have it just to have it. I exclusively use koreader and KSM as launcher (plus some other things, like USB control, setting time...).

**Comment by boriar** [comment]
Thanks for the label.
About text editor in vlasovsoftlauncher, it's only for notes and what I want is a book editor. Not a full book editor like Calibre but a simple word editor to let correct text or spaces within a ebook.

**Comment by AlanSP1** [comment]
I thought along lines of simple text editor ( .txt file format), without special formatting capabilities. I'm not sure, but editing epub files can be too complex? Or are there already available libraries with many things already solved?

**Comment by boriar** [comment]
Well, I don't know if any exist but I suppose that you need a zip library with support for zip/unzip, and may be a html editor? By the way, the idea isn't modify toc, css or something like that.

**Comment by Frenzie** [comment]
The vlasovsoftlauncher remark was a parenthetical about editing KOReader
config files.
