### ISSUE TITLE
Paperwhite 3; menu; changelog

### ISSUE THREAD

**Issue by JW01** [koreader/koreader#1720]
1 Does KOReader support Paperwhite 3?
2 I believe work is in progress to make menu font configurable. Any progress on that? I would like a smaller font so that the menus take up less of the screen.
3 I cannot find a KOReader changelog later than March 2015.
Many thanks.

**Comment by NiLuJe** [comment]
1. Provided you JB your device (over serial right now), yes.

**Comment by chrox** [comment]
2. Yes, no you can set custom screen DPI to change the font size in all reader menus.
3. This changelog page is deprecated. Please checkout the release note for each release for the change.
