### ISSUE TITLE
Feature request: Status bar can have two lines of text and/or graphics

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#1724]
I must admit that I like to have all info in status bar on. And now that we soon will have two new infos (#1723), maybe it would be good idea that we can have more than one line for status bar, of course, as an option.

In case of using two lines, one could be graphic progress bar (with chapter), other line could be used for other status bar infos.

This certainly would open space for adding additional infos which are possible in future.

Setting to use additional line for graphic progress bar in separate line could be just one more setting stating just that: Progress bar in additional line. If checked, status bar would be two lines, one for graphic progress bar, one for all other additional infos.

This additional line doesn't need to be as high (in pixels) as the textual one, so we can save a bit of vertical space.

**Comment by Yaretzki** [comment]
That's very good idea. I'm using and testing now "time to read book" and 'Time to read chapter". That would be great to have additional line in status bar as you described: one for graphic progress and other for rest of information.

**Comment by apletnev** [comment]
Guys, i think it is not so good idea to introduce two strings. I think It will look ugly and requires additional space. In my opinion will be better way to add some button in the left bottom corner. When you click you can see additional information something like this: https://mir-s3-cdn-cf.behance.net/project_modules/disp/633ad615882719.5629843a4ecfd.png

But we need some UX designer which can provide some mockups for it.

**Comment by Yaretzki** [comment]
I think with option described above: 
- If checked, progress bar would be two lines, one for graphic progress bar, one for all other additional infos
Or
- Unchecked, progress bar and all other (selected) infos in one line
still you could decide to have more infos in 2 lines or like it is now in 1 line. So decision is up to user.

**Comment by AlanSP1** [comment]
@apletnev, thing is that in my opinion I don't want to do anything to see additional info, I want to see everything right away. Having to touch some button, it is like not seeing all options instantly (which is one setting we already have).

Also, we already have something similar what I suggest. In defaults.lua we have option to see full progress bar:

>-- crereader progress bar
>-- 0 for top "full" progress bar
>-- 1 for bottom "mini" progress bar
>DCREREADER_PROGRESS_BAR = 1 

If we choose to see top full progress bar, graphic part is second row. And one line thick. So, I suggests something very similar, graphic part in it's own line, but that we have control what goes in lower line and that we can see it all at the same time.

Also, graphic part should be a bit thicker, maybe 10 pixels or we maybe can set it up in defaults.lua, as now we can set other things:

>-- configure "mini" progress bar
>DMINIBAR_TOC_MARKER_WIDTH = 2   -- Looses usefulness > 3
>DMINIBAR_HEIGHT = 7             -- Should be smaller than DMINIBAR_CONTAINER_HEIGHT
>DMINIBAR_CONTAINER_HEIGHT = 14  -- Larger means more padding at the bottom, at the risk of eating into the last line
>DMINIBAR_FONT_SIZE = 14 

For example, we could have:
DMINIBAR_GRAPHIC_HEGHT = 10

In that case we wouldn't need to have full progress bar, or if someone wants to use it, why not.

**Comment by Yaretzki** [comment]
Unfortunately still I have problems with feature "Time to Read Book" (TB). When I start the book everything is OK until the moment koreader crashes. In such situation I see my statistics ("Read Pages") reset to "0" even if I'm already in the middle of the book. And both: "Read Pages" and "Time to read book" show  incorrect information. The same situation I have if I start reading book in the middle, e.g. from page 400 of 800 in total. In statistics I have Read pages/Total pages 1/800 and Time to read book shows incorrect information because I assume it is related to "Pages Read", not to "Current Page".

Now I'm not sure if I should open new issue or #1723 should be re-opened?

**Comment by Yaretzki** [comment]
Is there any possibility to configure top full progress bar? I mean e.g. more visible chapters markers, book title on/off, different information than pages/total pages?
Y.

**Comment by chrox** [comment]
@Yaretzki The bottom status bar is designed as a minibar that takes as little space as possible to make more room for reading area. You can find the file `koreader/data/cr3.ini` in your koreader distribution and config the top full status bar instead. Currently it provides these options to config:
```
window.status.battery=1
window.status.battery.percent=0
window.status.clock=0
window.status.line=0
window.status.pos.page.count=1
window.status.pos.page.number=1
window.status.pos.percent=0
window.status.title=1
```
