### ISSUE TITLE
Jump to page\chapter pop-up window while highlithing the word in last stroke of a text issue

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#1728]
Hello,

This time I have not made any video on the issue, sorry.

Anyway, it is very easy to explain.

Try to open any text with KoReader and select\highlight words in last stroke... It is impossible, cause this annoying "Jump to page\chapter pop-up window" appears and there is no any option to turn off it.

Thanks for your attention. :D

**Comment by KenMaltby** [comment]
For me on my Kobo, I can toggle through the things I have selected to appear on the mini progress bar, by poking the bottom right of the screen.  One more poke and the mini progress bar is dismissed, and words on the last line of text can then be selected.

**Comment by Frenzie** [comment]
See discussion on this in #1350. The behavior @KenMaltby refers to was introduced in #1471. It's a bit annoying to have to toggle the status bar to select words on the lowest line, but it's workable. In the mythical future when someone will write a gesture manager, I think that particular area should by default have an undefined long-press behavior.
