### ISSUE TITLE
Unable to open djvu file with russian name

### ISSUE THREAD

**Issue by plusInfinity** [koreader/koreader#1729]
Hi, 
A little bit annoying issue. When I'm trying to open djvu file with russian letters in name I get message
"No reader engine for this file". Renaming file with latin letters solves the problem.
pdf files are OK though. I'm using the last stable release.

**Comment by Frenzie** [comment]
Duplicate of #542. I guess your Cyrillic characters must somehow contain invalid UTF-8.

**Comment by chrox** [comment]
Closing because of duplication.
