### ISSUE TITLE
Create status book feature

### ISSUE THREAD

**Issue by apletnev** [koreader/koreader#1730]
After finish the book a user can mark the book as complete (read). 
The UI should provide next fields before close the book:
* Rate - stars from 1 to 5
* Review
* Stats - show performance
* Move to folder (need further investigation)
* Mark as Read

Need integration into filemanager app relating to #1576

**Comment by AlanSP1** [comment]
This with moving books to folder would be really great. In a way that would make much easier to know which books are still unread, which should be read from time to time, and which books can be "safely" deleted from device.
