### ISSUE TITLE
[Pocketbook] Installation "Pocketbook package" is it still required (to run Koreader)?

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#1732]
In https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices#installation
there's a sentence:
"You need to obtain a recent PocketBook package from [this page] " 
where "[this page]' is a clear text (not a URL link). 

Is it still required to obtain "PocketBook package"?
I did find only:
https://github.com/bevry/pocketbook
but it doesn't contain "system" and "application".

Can someone (who already has Pocketbook) check it?

**Comment by Frenzie** [comment]
I assume that should've pointed to https://github.com/koreader/koreader/releases, so hereby.
