### ISSUE TITLE
Feature request: Option to use magnetic cover for turning device on/off, or not, like in nickel

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#1733]
I have cover with magnet and it puts device to standby, or turn on, but I would like to turn it off, like I can in nickel, which I don't use at all.

I read about workaround for this, but it may be better to have it as an option

**Comment by chrox** [comment]
A reader application cannot turn on your device neither could/should it turn off your device. This feature request is invalid and will be closed.

**Comment by AlanSP1** [comment]
@chrox 
request wasn't to turn device on/off, but to choose if magnetic cover turns device on/off.

If magnetic cover is disabled, magnetic cover wouldn't influence device status (you could close magnetic cover, device still would be on).

**Comment by AlanSP1** [comment]
I see that my description was pretty unclear, hope I cleared what I meant now.

**Comment by chrox** [comment]
Sorry I miss-understood what you mean on & off, it could be more precise to describe it as screen on/off or suspend/resume. Anyway, this is now duplicated to #1382.

**Comment by AlanSP1** [comment]
Sorry, didn't see that request before.
