### ISSUE TITLE
Feature request: Ability to set the default hyphenation setting using long tap on the menu option

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#1735]
Even not being an English native speaker I find it strange that KOReader defaults to hyphenating in English considering that it has originally been developed to work on a 6″ screen. Currently AFAICS it's only settable with an option in cr3.ini file.
Optionally it'd be neat to have this setting for each individual language.

**Comment by KenMaltby** [comment]
It might be good for UI consistency.  This setting selection remains until or unless another selection is made.  The selection is made with a simple tap, not a long tap, as most defaults are set.

**Comment by GeneralFailer** [comment]
Is this how it works now, or are you describing an alternative solution?

**Comment by KenMaltby** [comment]
Right, if you open the Hyphenation menu item you should see a listing of those hyphenation dictionaries that you have added to your device.  A simple tap on the one you want to use, will bring up a message box with "Changed hyphenation to ... " There will be a short wait while the change is made.

**Comment by GeneralFailer** [comment]
Is this supposed to change the default setting and I just have some kind of file write problem? The new documents I open keep using the setting I typed into cr3.ini, therefore the file wasn't affected by me selecting the option using GUI.

**Comment by KenMaltby** [comment]
Perhaps the cr3.ini settings are applied after the menu option settings, and take precedence?  I just know that it works as described on my Kobo Aura HD.  The selection with the check  remains in effect for later documents.

**Comment by GeneralFailer** [comment]
Maybe this is also connected to my issue #1701 then.

**Comment by GeneralFailer** [comment]
Damn it, wrong button.

**Comment by chrox** [comment]
Yes, that the hyphenation language defaults to English seems unfair to books of other languages. And this issue is solved by #1775 which implements auto detection of book language and select hyphenation language accordingly.
