### ISSUE TITLE
Japanese vertical writing not working on epub

### ISSUE THREAD

**Issue by tumugin** [koreader/koreader#1736]
My epub files should be rendered like the image shown below
![2015-12-05 01 33 18](http://i.imgur.com/myMsLNT.jpg)
but on koreader, vertical writing isn't working as the image shown below.
![2015-12-05 01 38 13](http://i.imgur.com/4g48IJa.jpg)

**Comment by KenMaltby** [comment]
What does changing it to landscape display?  Its menu item is on the bottom reading menu.

**Comment by chrox** [comment]
Currently koreader does not support vertical writing direction for EPUB format.

**Comment by frankyifei** [comment]
maybe simply rotate the glyph could work. but that requires more work with gui.

**Comment by Frenzie** [comment]
I'll close this for now, as it's unlikely to be implemented within the near future unless a motivated developer stands up.

Also, let's call it superseded by #4353.
