### ISSUE TITLE
What about upload it to Fdroid? Fdroid repo with latest versions?

### ISSUE THREAD

**Issue by timofonic** [koreader/koreader#1737]
Hello.

I found your app interesting, but I don't use Google services on my Android devices. And I have a few of them. I'm not a big fan of Android but it's the somewhat more open platform out there. I hate centralized services and try to avoid them more each time, removing Google dependence is one of them.

I'm also an idealist and consider Free Open Source Software (FOSS, FLOSS, Libre Software or whatever) and Hardware (the now tainted OSHW term by the shady OSHWA organization, so I prefer to call it Libre Hardware or FOSHW but who cares when what matters is to make substance to fight against parasites) to be better in both technical and idealistic aspects. This is a wide topic, so I'll write about it personally by request if someone is interested about it.

Are there plans to add Koreader to Fdroid? It would be greatly appreciated! I'll be able to update my FOSS Android packages easier.

Kind regards.

**Comment by chrox** [comment]
Sounds a good idea. But I think Koreader on Android is not stable enough to be released in public application stores.

**Comment by houqp** [comment]
Agree with chrox, we should revisit after the android version considered stable.

**Comment by timofonic** [comment]
When that will happen? Are there an issues list? A planning? Betatesting
phase?

I want KOreader to be used and updated easily :D

**Comment by houqp** [comment]
I would say when we clear up most of the android issues in this issue tracker and have an active developer maintaining the android port.

**Comment by chrox** [comment]
This will be discussed in #2040.
