### ISSUE TITLE
What's happening to this issue tracker? 116 and growing. Does the project manager need help?

### ISSUE THREAD

**Issue by timofonic** [koreader/koreader#1738]
Hello.

I see there's a giant list of issues here and it seems most of them aren't looked and solved.

Are there plans to clean it properly? It's not wise and good to clean them in dirty way as many projects do because of marketing reasons. Your code and users will suffer from it!

What's happening? Maybe this project needs more people.

Kind regards.

**Comment by chrox** [comment]
Cleaning now... ;)
