### ISSUE TITLE
What about merging efforts with Document Viewer?

### ISSUE THREAD

**Issue by timofonic** [koreader/koreader#1739]
Hello.

I think this project looks quite promising, I consider the Lua approach a lot better than using Java. Anyway, there are other FOSS projects with similar goals about having a viewer of documents in a wide variety of formats.

Java portability is a lie and adds lots of overhead. LuaJIT seems a lot more lightweight approach, a lot more portable too.

I cross-posted about this on the other repo...

https://github.com/SufficientlySecure/document-viewer/issues/158

Kind regards.

**Comment by Frenzie** [comment]
I'm not sure it's similar goals exactly. KOReader is geared toward eInk, while Document Viewer is aimed at Android.

**Comment by timofonic** [comment]
@Frenzie 

Why not target both?

**Comment by chrox** [comment]
I don't think it's possible to merge the efforts from both sides technically. The two projects have quite different development paradigms. Merging either side into the other side will inevitably rewrite a good part of the code base which is not valuable enough to justify the purpose.
