### ISSUE TITLE
Making Koreader even multiplatform and support non-touch? Linux, Windows, MacOS...

### ISSUE THREAD

**Issue by timofonic** [koreader/koreader#1740]
Hello.

I always wanted a program like this: A Document reader with wide file format support. But there's the issue of not having the same app on all platforms.

Sumatra PDF is somewhat okay on Windows.

I yet have to find a really good one on Linux, only a mix of them does a somewhat decent job: Some of them have awful form support, bad print support or lack certain formats.

But what about making Koreader also usable on desktop platforms too?

Kind regards.

**Comment by AlanSP1** [comment]
You can make koreader for different platforms (emulate how it works), see wiki: https://github.com/koreader/koreader#prerequisites

**Comment by timofonic** [comment]
@AlanSP1 

I knew that, thanks a lot anyway ;)

I meant to be natively ported to other platforms instead doing that emulation.

This way it could replace SumatraPDF on Windows and... Zathura and a zillion others? on Linux ;)

**Comment by houqp** [comment]
The rendering engine (koreader-base) can be run on different desktops without any issue. But the UI layer is designed specifically for mobile devices. To get cross platform desktop support, someone need to basically rewrite the UI layer with cross platform framework :( Atom-shell can be a good candidate. But it's a non-trivia effort.

**Comment by KenMaltby** [comment]
Might be of some help? http://gntheprogrammer.blogspot.com/2015/11/iup-lightweight-and-cross-platform-user.html
Luck;
Ken

**Comment by chrox** [comment]
And `TekUI` is also promising. See http://tekui.neoscientists.org/index.html.

**Comment by chrox** [comment]
Koreader basically is not targeting on desktop environment so I'm closing this now. But I will try to make the emulator run on Mac OS so that this project can attract more developers.
