### ISSUE TITLE
Official KOreader forum?

### ISSUE THREAD

**Issue by timofonic** [koreader/koreader#1741]
Hello.

I think KOreader project needs to create a community and have more visibility. An official forum section could be a good start.

I proposed a KOreader section in Mobileread, and collected a few posts mentioning KOreader that could be moved there.  I would love to know the opinion of the KOreader Team and  Vadim Lopatin (aka buggins,  aka vlasovsoft aka sergeyvl12 on mobileread), the original Cool Reader developer, likes this concept to go further.

http://www.mobileread.com/forums/showthread.php?p=3219769#post3219769

I'm afraid KOreader might become another OpenInkpot, you know what I mean...

Kind regards.

**Comment by tigran123** [comment]
Sergey Vlasov is not the same person as Vadim Lopatin :)

**Comment by timofonic** [comment]
@tigran123

I got confused! 

So who's interested in the unfork?

**Comment by timofonic** [comment]
Any news?

**Comment by tigran123** [comment]
What would be the benefit of doing what you propose?

**Comment by houqp** [comment]
I think the main benefit would creating a place for users to help each other. Github is probably not that user friendly anyway. The main issue is we need someone to help maintain the forum since it's a none trivia effort. If no one volunteers the work, I would rather have no forum than a "dead one" :P

**Comment by KenMaltby** [comment]
As it is now, Mobileread Forums provides an entry level user support with referrals to Github for more involved issue treatment.  There is still some effort to find a way for KOReader to have its own forum at MR, but the structure of the site is more device oriented.  It might not be intuitive for the average new MR member to find KOReader, except as it is mentioned in the forum for their device.

**Comment by timofonic** [comment]
@KenMaltby 

Calibre and other projects already have forums there. I think there's no problem at making a custom structure for KOreader, they are flexible about it.

On the other hand, KOreader needs more visibility and support. I found it accidentally, because I'm a crazy guy that looks things from Internet :)

An official website would be nice too, but I understand you probably don't have enough resources for it.

**Comment by KenMaltby** [comment]
I have just been notified that a "KOReader" forum has been started at MR in the "E-Book Software" section.  I requested that the first post moved there be the @timofonic MR post with his list of links.

**Comment by timofonic** [comment]
Hello.

That's nice! I'm very happy about this!

I have an Onyx Boox M96Plus, so I'm an Android user. I'm going to try KOreader a lot these days and provide feedback, but I don't have other devices (I have a Kindle DXG with a broken screen...).

**Comment by houqp** [comment]
Thank you guys so much for setting up the forum, especially @KenMaltby  and @timofonic ! I am sure @hwhw will be very happy to see how one of his MR posts turned into a sub forum :)  I just checked the original post, it's almost 3 years now.

I will try to check on the forum for unanswered questions as frequent as I can. Please feel free to escalate questions to github as you see fit.
