### ISSUE TITLE
Is it possible to compile kindlepdfviewer for 2-bit screens?

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#1742]
Greetings my brothers,

Here is the problem. One of my Kindle's (old Kindle Keyboard 3) screen broke and I bought a replacement on eBay. When the replacement arrived it turned out to be 2-bit rather than the 4-bit screen, but the contacts were all compatible and I fitted it into the device correctly. Obviously, when I saw that the screen is 2-bit (i.e. not as advertised 4-bit) I opened a case against the seller and got a full refund. However, it seems a shame to throw away an otherwise perfectly working Kindle (3G+WiFi model). Amazon's built-in mobi viewer sort of works (when typeface is set to "regular") but even dictionary lookups are awful because they require more than 2 bits of data. And kindlepdfviewer is even worse (much worse) because PDF rendering (or even just filemanager) uses all 4 bits all the time, so the output is horrible.

So, my question is: is it possible to tweak something in the sources to compile it (kindlepdfviewer, not koreader as this is for Kindle 3) for 2-bit screen or is this hopeless?

Here is the picture of comparison of 4-bit vs 2-bit Kindle screens, to show the problem:

![Image of 2-bit Kindle screen](http://www.bibles.org.uk/screenshots/defect1-small.jpg)

**Comment by tigran123** [comment]
Hmmm, I see that at least those bit shifts in `bitblip.c` and `djvu.c` will need adjusting (and probably some other places?), so it is not a single `#define` in some header file as I hoped....

**Comment by houqp** [comment]
That's a crazy screen :)

The easiest way I can think of is to create a 2 bit blitbuffer (BlitBuffer2) in blitbuffer.lua. That way, you don't have to change any other code. Just need to write the code that converts any type of BB to BB2.

**Comment by NiLuJe** [comment]
Isn't that also what happens when there's a waveform mismatch? (i.e., the screen itself might be okay). there are a number of threads on that subject on MR, IIRC.

**Comment by tigran123** [comment]
@NiLuJe Yes, you are exactly right. Are you saying that there may be a cure, i.e. a way to apply the correct waveform somehow? Ok, I'll study what is known about this on mobileread, thank you!

**Comment by tigran123** [comment]
I sold that particular Kindle, so the issue can be closed :)
