### ISSUE TITLE
koreader stable 2015.11 crash on kobo aura

### ISSUE THREAD

**Issue by rghe** [koreader/koreader#1743]
After installing v2015.11 stable koreader crashes when trying to open the menu (ie touching top of screen).  It happens with one epub I was reading before installing stable. Other epubs doesn't have the problem.  No crashes if statistics plugin is removed.
crash.log contains:

./luajit: plugins/statistics.koplugin/main.lua:237: attempt to perform arithmetic on field 'page' (a nil value)
stack traceback:
	plugins/statistics.koplugin/main.lua:237: in function 'updateCurrentStat'
	plugins/statistics.koplugin/main.lua:160: in function 'getStatisticForCurrentBookMenuTable'
	plugins/statistics.koplugin/main.lua:73: in function 'addToMainMenu'
	frontend/apps/reader/modules/readermenu.lua:94: in function 'setUpdateItemTable'
	frontend/apps/reader/modules/readermenu.lua:150: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:67: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:79: in function 'handleEvent'
	frontend/apps/reader/modules/readermenu.lua:211: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:67: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:79: in function 'handleEvent'
	frontend/ui/uimanager.lua:271: in function 'sendEvent'
	frontend/ui/uimanager.lua:59: in function '__default__'
	frontend/ui/uimanager.lua:505: in function 'handleInput'
	frontend/ui/uimanager.lua:544: in function 'run'
	./reader.lua:148: in main chunk
	[C]: at 0x0000bea5

**Comment by apletnev** [comment]
Unfortunately I've made a lot of changes in the statistics plugin regarding to #1718 so i can't make hotfix.
I can suggest to remove the file with name of the book from Statistics folder, instead to disable the plugin.
Thanks

**Comment by rghe** [comment]
ok, thanks

**Comment by houqp** [comment]
@rghe feel free to reopen the issue if you have further question. I am going to close this issue for now. In the future, we should make sure plugins are backwards compatible.
