### ISSUE TITLE
Filemanager should have close icon

### ISSUE THREAD

**Issue by tbm** [koreader/koreader#1744]
It would be nice if the filemanager had a close/exit "x" icon on the right, upper side.

Sometimes I enter filemanager by accident and afaict there's no way to close the filemanager.  The only way to exit is to choose the book I'm reading again.

**Comment by AlanSP1** [comment]
As a workaround, you can choose any book, after that go to history and choose original book you were reading. It's useful if you need some time to find book that you were reading in first place.

**Comment by KenMaltby** [comment]
I am not sure how someone would "enter filemanager by accident", but the File Manager and the readers are separate.  In fact going from the reading programming to the File Manager, is a way to insure that highlights and reading position are saved to a file, from memory.  It is easy enough to select History and poke the top entry listed, to return to where you were while reading.  The **Home** button, while in the file manager, is a "close/exit "x" icon on the right, upper side".  Selecting that will close and exit KOReader.  If you use KSM to launch KOReader, it will return you to KSM.  If you are using an Android version of KOReader, you will return to Android.

**Comment by tbm** [comment]
Ken, I should have explained how I entered filemanager by accident.  When I installed KOReader, the icons weren't immediately obvious to me.  I cannot remember for sure but I think I thought the filemanager icon was a table of contents icon, so that's why I clicked on in by accident several times.

**Comment by houqp** [comment]
Looks like you got sorted out :)
