### ISSUE TITLE
Footnote hard to hit - increase sensitivity

### ISSUE THREAD

**Issue by tbm** [koreader/koreader#1745]
I find it really hard to press a footnote when you have a footnote that only consists of a single number. When I press the footnote, I usually end up on the next page instead of the footnote.

It would be nice if KOreader would be less strict about where you touch... i.e. it should be good enough to press near the footnote, as long as it's not too far away.

FWIW, this is on a Kobo Glo HD.

**Comment by Frenzie** [comment]
Should probably be relatively easy to change with some extra padding in the
styles.

**Comment by chrox** [comment]
This issue will be fixed along with #2066 which specified a generic issue of hitting hyperlinks in Koreader.
