### ISSUE TITLE
Show "next article" for magazines

### ISSUE THREAD

**Issue by tbm** [koreader/koreader#1746]
The Kindler shows "next article: title" on the progress bar when reading magazines and clicking that is an easy way to skip the current article and go to the next one.  It would be nice if KOreader would offer the same.

I've no idea how the Kindle knows whether something is a magazine/newspaper as opposed a book (where it doesn't do this).  But this feature works with The Economist, which I created using Calibre's download from the web function.  I guess the metadata indicates the type.

**Comment by Frenzie** [comment]
We have a next file functionality now, see #3943.
