### ISSUE TITLE
Open a window for footnotes

### ISSUE THREAD

**Issue by tbm** [koreader/koreader#1747]
It would be nice if KOreader would show footnotes in a window (as with the dictionary) instead of going to the footnote.  This is the behaviour of the Kindle.

This should probably be an option since not everyone wants this.

**Comment by Frenzie** [comment]
Sounds like a good idea to me, but I imagine it's largely down to the cr
API.

**Comment by frankyifei** [comment]
I think CR only jump to a position when you press on the footnote link, it does not know what the footnote is. So it's not so easy to implement this.

**Comment by KenMaltby** [comment]
If going in that direction perhaps the Message Window widget could allow for moving the window about the screen, so that pertinent text is not covered by the window.  Maybe a drag handle?

**Comment by chrox** [comment]
A footnote link has an `xpointer` from which we can get the corresponding DOM node and extract the footnote text.

**Comment by Frenzie** [comment]
Closing as a duplicate of #3054.
