### ISSUE TITLE
Where to download *.idx, *.ifo, *.dict stardict files to add a dictionary to Koreader

### ISSUE THREAD

**Issue by Mixal400** [koreader/koreader#1748]
I want to add a dictionary to my Koreader, to do it I have read this thread:
https://github.com/koreader/koreader/wiki/Dictionary-support
where it is said to copy *.idx, *.ifo, *.dict files to koreader/data/dict directory, but where to get these files when I google for "stardict dictionary download" I either find some .exe files that I have to install or some tar.bb2 files that I can't even opened on my Windows 7, I can't find *.idx, *.ifo, *.dict files.
Can anyone tell me please where to find these files or send me the link where I can download them?
I want to have eng to eng (with explanation of each word) or eng to rus dictionary.

**Comment by KenMaltby** [comment]
If you open the "tarball" file in WinRAR, (or similar) you should find the files or a folder that contains the files.  You can just put the folder in koreader/data/dict directory, or the files, if there is no folder.

**Comment by Frenzie** [comment]
7-zip is a free alternative to WinRAR.

**Comment by Mixal400** [comment]
thank you guys it helped a lot!

**Comment by chrox** [comment]
Closing this as the OP already found the answer.
