### ISSUE TITLE
Auto power off

### ISSUE THREAD

**Issue by CyberAndrew** [koreader/koreader#1749]
Koreader needs auto power off (or auto exit to main menu) function after some time of inactivity. Now, when device is inactive, it drains full battery for a week. That's why I always need to exit koreader to keep the battery, and this is very annoying. Koreader should automatically shut down device after few hours of inactivity, or (if previous option impossible to code) exit to main menu, where the original firmware will shut down it after some time.

**Comment by Frenzie** [comment]
What device is this on? I think this should be closed in favor of #1356, but I'm holding off because you didn't mention suspend at all.

**Comment by CyberAndrew** [comment]
The device is Kobo Aura HD.

**Comment by AlanSP1** [comment]
It may be problem with suspend script which for some unknown reason (unknown at least to me) doesn't suspend device properly and battery can be spent sooner than expected.

For example, suspending device with koreader suspend script first day of testing brought battery from 100% to 82% (of course, this isn't always so).

So now I'm testing CoolReader's suspend script. For 5 days I had battery at 100%. I started testing 5.12 and still battery is going just fine. I'll report when I need to charge battery for the first time with CR's suspend script.

Before I was turning device off, but at the moment it seems that using CR's suspend script solves the problem of fast battery drain when suspending device.

**Comment by farvardin** [comment]
I don't have this problem on the pocketbook Lux 3. The device suspend itseft after the time limit. But then KoReader won't keep my bookmarks for this session nor keep the current reading progression. It will only save them when I go to the home screen first.

**Comment by CyberAndrew** [comment]
Interesting thing, that after weak of inactivity, koreader wakes up instantly after opening magnetic case. Isn't suspend should be so fast?

**Comment by Frenzie** [comment]
Waking up in less than a second is pretty much the point of suspend. ;-)

**Comment by mwozny123** [comment]
Wow around Month ago I had the same feeling, as author  on Pocketbook lux 3 (koreader nightly) 
4-5days after suspend the battery was empty. 
 this was a just bought new eReader, so I thought Pocketbook (is not as good as kindle in battery saving ) and it cannot be suspended(without power off) because it drains battery. 
Since the I use battery saving  power off option:/

**Comment by chrox** [comment]
Power off the device automatically is not and should not be an option for a reader application.  It seems the OP's real problem is duplicated to #1663.

**Comment by joestrach** [comment]
For anyone coming here from a Google. This is implemented despite being closed.

Gear -> Device -> Autoshutdown Timeout

![20231016_203221](https://github.com/koreader/koreader/assets/5495465/391895e4-7fde-4d83-a4f8-c26c656c7a4b)

![20231016_203235](https://github.com/koreader/koreader/assets/5495465/8527449a-cfab-4af8-9d2e-9748232c7c8d)
