### ISSUE TITLE
TB feature/statistics and Nightly 20151213

### ISSUE THREAD

**Issue by Yaretzki** [koreader/koreader#1750]
Unfortunately still I have problems with feature "Time to Read Book" (TB). When I start the book everything is OK until the moment koreader crashes. In such situation I see my statistics (e.g. "Read Pages") reset to "0" even if I'm already in the middle of the book. And both:  "Time to read book" shows incorrect information. The same situation I have if I start reading book in the middle, e.g. from page 400 of 800 in total. In statistics I have Read pages/Total pages 1/800 and "Time to read book" shows incorrect information because I assume it is related to "Pages Read", not to "Current Page".

In file main.lua I added my own line calculating "time to read book" which is linked to "current page". So under Statistics menu => Current, I have correct information and I can always go there to check it. But it could be great to have correct one on status bar (TB).
The idea for TB (Time left to read book) was:
(Total pages - current page) * average time per page = Time left to read book (TB)

Feature TC works fine.

Now I'm not sure if I should open new issue or #1723 should be re-opened?

Another issue ans some comments on koreader last nightly version 20151213.
1. When I was reading last book everything was OK (except above). When I finished I went to another book and koreader couldn't open it. So I went to next and result the same: koreader tried to open but (there was opening window but after that still list of books was on screen. The next book and koreader crashed. I re-open it and checked the last "working" book and koreader opend it with no problems. So I tried to open other books with no success.
2. I checked what is the difference betwenn "working book and rest of them which koreader couldn't open. I found this:
- for working book there is folder Booktitle - Author.epub.sdr with Booktitle - Author.epud.lua file inside
- for working book there is in koreader=>history folder [#mnt#onboard#] Booktitle - Stephen King.epub.lua file inside

- for non working books there is folder Booktitle - Author.epub.sdr BUT EMPTY
- for non working books THERE IS NO in koreader=>history folder [#mnt#onboard#] Booktitle - Author.epub.lua file inside corresponding to such book

3. I created manually (based on already existing file for different book) for non-working books file in koreader=>history folder, changed name of file corresponding to title and author and edited information inside file corresponding to book I want to make working
4. I launch koreader and tried to open prevoiusly non working book but this time koreader opened it!

So I assume problem is linked to file(s) in .sdr folder and .lua in history folder. It looks like koreader cannot create these files by itself and thus cannot open book. 
J.

**Comment by apletnev** [comment]
Hi @Yaretzki, thank you for your feedback. 
I've changed formula for TB to: ((total_read_time / read_pages) * (all_pages - current_page))

About the second issue, i think better if you will create separate issue for this. 
Thanks.

**Comment by Yaretzki** [comment]
Thank you for new TB formula!
So, for this second problem I'm opening new issue.
