### ISSUE TITLE
last nightly version 20151213 cannot open books

### ISSUE THREAD

**Issue by Yaretzki** [koreader/koreader#1752]
Another issue and some comments on koreader last nightly version 20151213.
1. When I was reading last book everything was OK, in meantime I upgraded from stable to last nightly version. When I finished I went to another book and koreader couldn't open it. So I went to next and result the same: koreader tried to open but (there was opening window) but after that still list of books was on screen. The next book and koreader crashed. I re-open it and checked the last "working" book I was reading and koreader opened it with no problems. So I tried to open once again other books with no success.
2. I checked what is the difference betwenn "working" book and rest of them which koreader couldn't open. I found this:
- for working book there is folder Booktitle - Author.epub.sdr with Booktitle - Author.epub.lua file inside
- for working book there is in koreader=>history folder [#mnt#onboard#] Booktitle - Author.epub.lua file inside

- for non-working books there is folder Booktitle - Author.epub.sdr BUT EMPTY
- for non-working books THERE IS NO in koreader=>history folder [#mnt#onboard#] Booktitle - Author.epub.lua file inside corresponding to such book

    I created such file manually for non-working books file in koreader=>history folder, changed name of file corresponding to title and author and edited information inside file corresponding to book I want to make working
    I launched koreader and tried to open prevoiusly non working book but this time koreader opened it! Probably thanks to created manually file in history folder.

So I assume problem is linked to file(s) in .sdr folder and .lua in history folder. It looks like koreader cannot create these files by itself and thus cannot open book.
J.

**Comment by KenMaltby** [comment]
Which device?

**Comment by Yaretzki** [comment]
Kobo Glo HD and with last stable version everything is OK, all books are working.

**Comment by houqp** [comment]
@Yaretzki , when the reader crash, you should be able to find a crash.log inside the reader directory, could you paste the content here?

**Comment by Yaretzki** [comment]
I tried to open one of the book koreader failed to open before. Once again koreader crashed. There was empty .sdr folder created and no .lua file in "history" folder corresponding to this book. Here is crash log content:
./luajit: frontend/apps/reader/modules/readerrolling.lua:482: bad argument #1 to 'getPageFromXPointer' (string expected, got nil)
stack traceback:
	[C]: in function 'getPageFromXPointer'
	frontend/apps/reader/modules/readerrolling.lua:482: in function 'gotoXPointer'
	frontend/apps/reader/modules/readerrolling.lua:399: in function 'updatePos'
	frontend/apps/reader/modules/readerrolling.lua:388: in function 'action'
	frontend/ui/uimanager.lua:302: in function '_checkTasks'
	frontend/ui/uimanager.lua:453: in function 'handleInput'
	frontend/ui/uimanager.lua:544: in function 'run'
	./reader.lua:148: in main chunk
	[C]: at 0x0000bea5

Y.

**Comment by frankyifei** [comment]
try delete files in cache folder

**Comment by houqp** [comment]
That's weird, i manually deleted all files from .sdr and history directories, but still cannot reproduce the crash. What happen if you delete the whole .sdr directory? Koreader should work fine without those history files, it will just treat the book as a new book.

Also please try deleting the cache folder as @frankyifei suggested.

Could you also help verify that deleting those history files makes working books crash?

**Comment by Yaretzki** [comment]
Here is what I did:
1.
- cache folder files deleted,
- I tried to open previously non-working book. 
Result: koreader couldn't open it and crashed
2.
- cache folder files deleted,
- all .sdr folders for all books deleted
- I tried to open previously non-working book. 
Result: koreader couldn't open it and crashed

For all non-working books I tried to open there are .sdr folders created once again, but empty. And no .lua files created in history folder
3. 
- cache folder files deleted,
- all .sdr folders for all books deleted
- manually created .lua file in history folder by copy/paste existing one and changing file name to corresponding to title and author of book I want to open in next step
- I tried to open previously non-working book, the one for which I created manually file in above step
Result: koreader opened it and worked OK, folder .sdr for this book created with .lua file inside

crash.log content is exactly the same as in above post

Y.

**Comment by Yaretzki** [comment]
Update:
I think I found reason.
There is a file settings.reader.lua. When I removed it and tried to open books they all works and mentioned file is recreated but content of it is different in comparison to the one I removed.
I will continue on tests.

**Comment by houqp** [comment]
@Yaretzki , could you paste the content of the old settings.reader.lua here?

**Comment by Yaretzki** [comment]
Here it is, content of settings.reader.lua I removed:
> return {
	["copt_line_spacing"] = 100,
	["night_mode"] = false,
	["copt_font_weight"] = 0,
	["copt_status_line"] = 1,
	["copt_css"] = "./data/epub-kopia.css",
	["filemanagermenu_tab_index"] = 3,
	["footer"] = {
		["progress_bar"] = false,
		["disabled"] = false,
		["book_time_to_read"] = true,
		["toc_markers"] = true,
		["battery"] = true,
		["pages_left"] = true,
		["all_at_once"] = true,
		["page_progress"] = false,
		["time"] = true,
		["percentage"] = true,
		["chapter_time_to_read"] = true
	},
	["fm_screen_mode"] = "portrait",
	["frontlight_intensity"] = 10,
	["lastfile"] = "/mnt/onboard/Dallas `63 - Stephen King.kepub.epub",
	["reader_footer_mode"] = 2,
	["kosync"] = {
		["auto_sync"] = true
	},
	["cre_font"] = "Charis SIL Modified",
	["statistics"] = {
		["is_enabled"] = true,
		["min_sec"] = 10,
		["max_sec"] = 150
	},
	["copt_page_margins"] = {
		[1] = 5,
		[2] = 10,
		[3] = 5,
		[4] = 10
	},
	["ota_server"] = "http://hal9k.ifsc.usp.br:80/koreader/",
	["show_advanced"] = true,
	["collate"] = "strcoll",
	["lastdir"] = "/mnt/onboard",
	["open_last"] = false,
	["evernote"] = {
		["username"] = "",
		["html_export"] = false
	},
	["ota_channel"] = "nightly",
	["language"] = "pl"
}
<

Y.

**Comment by KenMaltby** [comment]
What if you turn ["is_enabled"] = true, to false?  Another new feature that might be effecting this could be ["book_time_to_read"] = true, you might try with that false.

**Comment by apletnev** [comment]
@Yaretzki 
Maybe problem in the file name? ``` mnt/onboard/Dallas `63 - Stephen King.kepub.epub ```
try to remove quote from name: ```Dallas `63 ```

**Comment by houqp** [comment]
I am able to reproduce the crash now. The cause is the "all_at_once" footer option. You can remove that line for now to workaround it. I will look into it further for a proper fix. Thanks for all the information.

**Comment by houqp** [comment]
Root cause is `ReaderFooter:getDataFromStatistics` returning nil when there is no stats history for the book, which causes `table.concat(info, " | ")` to fail. I am investigating why this causes a stack trace from readerrolling.lua instead.

**Comment by houqp** [comment]
OK, it's because of the coroutine. My PR should force it to dump a stack trace now. We should have better visibility in the future for reader crashes.
