### ISSUE TITLE
Screenshots in File Manager?

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1756]
I could use screenshots of the menus to help explain KOReader's functions, both here in the wiki and at MR forums.  It looks like I can in the cr3 Reader menus (haven't tried it in the PDF reader yet), but I can't get it to work in the File Manager.

**Comment by houqp** [comment]
screenshot should be enabled for all formats. it should be easy to add it to filemanager. I can take a look at it later tomorrow.

**Comment by KenMaltby** [comment]
Ah... I can now get a screenshot in File Manager (v2015.11-38) but not with a menu showing.  I do get the menus in the Reader screenshots.

**Comment by houqp** [comment]
good catch, I just submitted a new PR to fix this.

**Comment by KenMaltby** [comment]
It is working in v2015.11-40, thanks; it should make things easier.
