### ISSUE TITLE
andriod, full screen

### ISSUE THREAD

**Issue by Lewis-Liu** [koreader/koreader#1759]
koreader for andriod ，can not read in full screen.   My device is  Boox M96C(android 4.0.4).
if koreader has a full screen option ,it will be better.thanks!

**Comment by KenMaltby** [comment]
Is there perhaps an OS/android setting to have the app use the whole screen?  Could it be effected by the portrait/landscape setting?

**Comment by Lewis-Liu** [comment]
In most andriod device，the full screen option is in  specific app, not in android system. if koreader has the full  screen option,we can choose to open it or close it.

**Comment by timofonic** [comment]
I have an Onyx Boox M96 Plus (1GB RAM, 8GB Flash, inductive screen with "Big Pen") and I'm concerned about this.

Any news?

**Comment by chrox** [comment]
Could you post a screenshot (a real shot by a camera, I mean) of your device running koreader?
