### ISSUE TITLE
Bluetooth does not work.

### ISSUE THREAD

**Issue by irregularisnotrandom** [koreader/koreader#1760]
Hi

Bt controls do not work when Koreader is open. basically i can hear the music through bt but the play butttons do not work when koreader is in focus. When i get back to android desktop, bt controls start working again.

I am using lollipop 5.1

**Comment by chrox** [comment]
Sounds like koreader traps some Bluetooth input events. Will investigate further into this later.

**Comment by irregularisnotrandom** [comment]
I think that it also blocks other regular media controls, like the ones on headsets

**Comment by pazos** [comment]
media controls are in fact blocked by KOReader when it has focus and used as page turn buttons.

But bluetooth handset controls shouldn't be used in any non-broken device. I cannot reproduce on my phone.
