### ISSUE TITLE
Selected text from right-to-left language content comes out wrong

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1767]
Hi

I have been reading a Persian book in KOreader.I believe it is a standard pdf with text, because the underlying text seems proper. For instance when I reflow the text, the word separation seems correct. I did not check every single page for testing, it seems correct.

The issue is this. When I select some text (and selecting is pretty hard and incosistent btw) ,given that if I successfully select it, the text shown in the bubble window is garbage like, meaningless. It shows some persian characters but it has nothing to do with selected text. So I assume there is some conversion there and it fails to do the right right.  Normally some persian characters should connect to left or right ot from both sides. The text shown there all show as separated with their various connecting states. So the characters are not given in their original unconnected state(which arabic alphabets derivations do have) which is good but the representing characters have nothing to the with the selected text. 

Anyway I hope it makes sense.

cheers

**Comment by chrox** [comment]
Sorry, but could you make a screenshot to help to explain this problem?

**Comment by gerroon** [comment]
@chrox 

You can try this book

http://www.irantarikh.com/adab/bufkur.pdf

**Comment by Frenzie** [comment]
The text seems to come out okay now:

![Screenshot_20190830_171716](https://user-images.githubusercontent.com/202757/64032159-2a58ec80-cb4a-11e9-80a3-68a435a089ec.png)

For bidi in general see <https://github.com/koreader/koreader/issues/1426#issuecomment-486388762>.

**Comment by poire-z** [comment]
Fixed by #5598 and #5667.
