### ISSUE TITLE
Feature Request: For Kobo devices, make clock live, changing time automatically in status bar

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#1769]
If it is possible, it would be great if time would change automatically in real time, not only on page changes (or when turning off status bar and then turning it on again).

As it happens only every minute, and affects relatively small screen area, it probably wouldn't affect too much battery.

It would look really great, having accurate clock readings all the time.

**Comment by chrox** [comment]
I would like to make it an option but disabled by default.

**Comment by AlanSP1** [comment]
Great!
