### ISSUE TITLE
koreader display content differently between Kobo Aura h2o and kpw1

### ISSUE THREAD

**Issue by qdwang** [koreader/koreader#1770]
1. The koreader version are the same.
2. The books are the same pdf file.
3. The books' setting in two devices are the same.

![koreader](https://cloud.githubusercontent.com/assets/403616/12220193/658c221a-b7a1-11e5-875f-5c390fda4102.png)

**Comment by chrox** [comment]
It seems you turned on text reflow on both devices. Since the h2o has a larger screen dimension the refow algorithm may produce slightly different results. You can try fine turnning the font size to a smaller one on h2o and it may have a better result.

**Comment by qdwang** [comment]
I have to increase the font size to very big to make the diagram to be rendered like the kindle does.
But the font has to be too big for me to do normal reading.

So is it possible to fix this by add some special corner case to code when detected a 6.8 devices?

**Comment by chrox** [comment]
You may also change the screen DPI which is also a parameter passed into k2pdfopt, otherwise I cannot think up a solution. And this is not an item for the next stable release.
