### ISSUE TITLE
FR: Move Book

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1777]
Hi

It would be so nice if we can move a book from a directory to another directory while in the reading mode. 

This is different than "copy" or "cut" function we have. By moving I mean also moving the .sdr folder along with the book. So when the user select move item it will present a browser. The user selects a new folder and koreader moves the currently open book to the new folder along with the associated .sdr folder and reopens the book from that newly opened folder.

Some might say, why do not you just use a file browser or use cut paste thing. The thing is that it is a bit tedious to do this stuff on Einks devices as you know. Such menu item will make it a snap to move a book around.

**Comment by KenMaltby** [comment]
I don't see why you would want to move the book while you are reading it?  In any case, shouldn't we leave file management in the File Manager.  Perhaps adding a "Move" function to File Manager's long press functions, one that moves the .sdr as well as the book file, could be possible.  I don't see why it would be an urgent need though.  For now it is very easy to do such things with the device attached to your PC.

**Comment by gerroon** [comment]
@KenMaltby 

The issue is convenience. Sure I do not even need an erader in the first place I can just do it on my computer.

Why would you need to move the book while you are reading? You open a book and you realize that like it and you just want to put it in your "currently reading" folder maybe or your "favorites" folder while maintaining its koreader file settings is not a crazy idea.

**Comment by KenMaltby** [comment]
While it may seem less convenient to have to poke the File Manager Icon, and do it there, you might consider that going to the File Manager would be needed to update the files you want to move, with the current data.  Rearranging files, selecting destination folders, ect... would interrupt my reading, no matter what menu I started from.

**Comment by Frenzie** [comment]
> This is different than "copy" or "cut" function we have. By moving I mean also moving the .sdr folder along with the book.

That's a bug in the cut/copy/paste functionality. One that's probably fixed easily enough around [here](https://github.com/koreader/koreader/blob/a97d06e527c17ff25cdb184e2649709e3687da08/frontend/apps/filemanager/filemanager.lua#L266-L278). In fact the same bug was fixed for the delete functionality [less than two weeks ago](https://github.com/houqp/koreader/commit/d1ca8bc4940542547c33da48767916149c7d3128).

Besides that, I'm not convinced that saving the step of selecting "cut" in the file manager warrants polluting the reader interface with functionality that doesn't really have a place there.

**Comment by Frenzie** [comment]
Cut has been fixed, copy doesn't yet copy the .sdr.

**Comment by gerroon** [comment]
@Frenzie thanks
