### ISSUE TITLE
after "make clean", it will delete all thirdparty zips

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#1779]
Then next time I “make" it will download everything again and it costs very long time on my computer.

**Comment by houqp** [comment]
`make clean` should not remove the zip files. you should able find those zip files under `thirdparty/LIBFOO/build/downloads` dir. Were you running the command with an invalid `TARGET`?

**Comment by frankyifei** [comment]
maybe I used wrong TARGET.

**Comment by houqp** [comment]
I have been wanted to make the build system to bail out on invalid TARGET so things like this won't happen. It actually happened to me couple times and it's not fun to download everything again.

**Comment by houqp** [comment]
@frankyifei https://github.com/koreader/koreader-base/pull/370 should fix this issue.
