### ISSUE TITLE
KR works on Lollipop with Xposed without any problems 

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1780]
Hi

I just wanted to give some heads up on KR Android platform. I upgraded my tablet to Lollipop 5.1 and KR works without any issues even though it has Xposed frame work installed on it as well. KR never worked on this device when it had Kitkat. 

The reason I brought it up because there was some kind of consensus amoing devs that KR is failing on some Android devices because those devices had Xposed framework installed. Well I do not know if this new finding deflects that idea but it is definetely a new evidence of issues around KR crashes on Android devices could be related to other matters not just Xposed type of frameworks.

**Comment by chrox** [comment]
Thanks for the information. I'm interested to the memory map file of the koreader process running within the Xposed framework. Could you post that file here?

**Comment by chrox** [comment]
Closing this now as it did not raise any bug or issue.
