### ISSUE TITLE
Displays blackscreen on startup(Android)

### ISSUE THREAD

**Issue by pdo-smith** [koreader/koreader#1782]
On starting up Koreader it displays a black screen and is unresponsive.
This is true for 2015.11-stable and for koreader-nightly-20151213

My environment is Android 5.1 on a Meizu M2 Note.

It worked correctly after the first install but then failed after trying to read a .pdf file. Thereafter it displays a black screen on startup. I have deleted(including the file structure) and reinstalled but it always gives a black screen on startup.

**Comment by gerroon** [comment]
KR on Android is pretty sketchy unfortunately.

**Comment by houqp** [comment]
potentially related to https://github.com/koreader/koreader/issues/1771. Do you have logcat access to help get the error log?

**Comment by houqp** [comment]
> KR on Android is pretty sketchy unfortunately. 

Yeah, I consider android support till in early alpha stage right now. The eco system is very fragmented thus not easy to debug without the actual hardware.

**Comment by pdo-smith** [comment]
My system information is:
AArch64 Processor, rev 4, 8 cores
Instruction set arm64-v8a

I will get the logcat info later.

**Comment by pdo-smith** [comment]
_"Yeah, I consider android support till in early alpha stage right now"_

Koreader works well on my tablet:
ARMv7 Processor rev4, 4 core
Instruction set armeabi-v7a

so things are not so bad!

**Comment by Frenzie** [comment]
I also have a black screen issue on my Zenfone 2, although I suppose that could be an architecture issue as it's an x86 device (cf. #1815). Note that Intel says ARM stuff should [Just Work™](http://regmedia.co.uk/2014/04/30/intel_binary_translator_slide.jpg) with a slight performance penalty.

```
D/LauncherLog( 2051): Launcher:: startActivity: pkg: org.koreader.launcher clz: android.app.NativeActivity
I/art     (18987): Late-enabling -Xcheck:jni
D/houdini (18987): [18987] Initialize library(version: 5.0.7a_y.48167 RELEASE)... successfully.
I/ActivityManager(  635): Start proc org.koreader.launcher for activity org.koreader.launcher/android.app.NativeActivity: pid=18987 uid=10055 gids={50055, 9997, 1028, 1015, 3003} abi=armeabi-v7a
V/Launcher( 2051): [onWindowFocusChanged]: false, takes: 0ms
I/art     (  315): Explicit concurrent mark sweep GC freed 712(30KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 15MB/25MB, paused 217us total 16.061ms
D/WindowManager(  635): adjustConfigurationLw, config:{0 0.85 ?mcc?mnc ?locale ?layoutDir sw360dp w360dp h615dp 480dpi nrml long port ?uimode ?night finger -keyb/v/h -nav/v} mLidState:1 mHasDockFeature:false mHasKeyboardFeature:false mHasHallSensorFeature:true config.hardKeyboardHidden:2
I/art     (  315): Explicit concurrent mark sweep GC freed 6(208B) AllocSpace objects, 0(0B) LOS objects, 40% free, 15MB/25MB, paused 210us total 13.770ms
I/art     (  315): Explicit concurrent mark sweep GC freed 5(160B) AllocSpace objects, 0(0B) LOS objects, 40% free, 15MB/25MB, paused 122us total 9.080ms
D/ForegroundUtils( 2179): Foreground changed, PID: 18987 UID: 10055 foreground: true
D/ForegroundUtils( 2179): Foreground UID/PID combinations:
D/ForegroundUtils( 2179): UID: 10013 PID: 2051
D/ForegroundUtils( 2179): UID: 10055 PID: 18987
D/hwcomposer(  245): void android::intel::UeventObserver::onUevent(): received Uevent: REPEATED_FRAME
D/hwcomposer(  245): virtual void android::intel::Hwcomposer::invalidate(): invalidating screen...
V/PhoneStatusBar( 1477): setLightsOn(true)
V/Monotype(18987): SetAppTypeFace- try to flip, app = org.koreader.launcher
V/Monotype(18987):     Typeface getFontPathFlipFont - systemFont = default#default
D/hwcomposer(  245): void android::intel::DisplayAnalyzer::handleIdleEntryEvent(int): handling idle entry event, count 0
D/hwcomposer(  245): void android::intel::DisplayAnalyzer::handleIdleExitEvent(): handling idle exit event
D/houdini (18987): [18987] Added shared library /data/app/org.koreader.launcher-1/lib/arm/libluajit-launcher.so for ClassLoader by Native Bridge.
V/threaded_app(18987): Creating: 0x12024020
V/threaded_app(18987): Config: mcc=206 mnc=20 lang=en cnt=US orien=1 touch=3 dens=480 keys=1 nav=1 keysHid=3 navHid=0 sdk=21 size=2 long=2 modetype=1 modenight=1
V/Monotype(18987): SetAppTypeFace- try to flip, app = org.koreader.launcher
V/Monotype(18987):     Typeface getFontPathFlipFont - systemFont = default#default
V/threaded_app(18987): Start: 0x12024020
I/dispmgr (  309): waiting for message from kernel.
I/dispmgr (  309): message from kernel received.
I/dispmgr (  309): DpstAlgorithm_DPST4_5 
I/dispmgr (  309): DpstAlgorithm_DPST4_5 level is 3
I/dispmgr (  309): waiting for message from kernel.
I/dispmgr (  309): message from kernel received.
I/dispmgr (  309): DpstAlgorithm_DPST4_5 
I/dispmgr (  309): DpstAlgorithm_DPST4_5 level is 3
I/luajit-launcher(18987): Application data directory /data/data/org.koreader.launcher/files
I/luajit-launcher(18987): Application library directory /data/app/org.koreader.launcher-1/lib/arm
I/luajit-launcher(18987): Screen size 1080x1920
I/luajit-launcher(18987): Screen brightness 12
I/luajit-launcher(18987): Check file in asset module: koreader-gcf9dc26.7z
I/luajit-launcher(18987): Skip installation for revision gcf9dc26
I/luajit-launcher(18987): Change directory to /data/data/org.koreader.launcher/files
I/luajit-launcher(18987): intent file path 
I/luajit-launcher(18987): run command chmod 755 ./sdcv
I/dispmgr (  309): waiting for message from kernel.
I/dispmgr (  309): message from kernel received.
I/dispmgr (  309): DpstAlgorithm_DPST4_5 
I/dispmgr (  309): DpstAlgorithm_DPST4_5 level is 3
I/luajit-launcher(18987): command stdout:
I/luajit-launcher(18987): command stderr:
I/luajit-launcher(18987): command res:0
I/luajit-launcher(18987): run command chmod 755 ./tar
I/luajit-launcher(18987): command stdout:
I/luajit-launcher(18987): command stderr:
I/luajit-launcher(18987): command res:0
I/luajit-launcher(18987): run command chmod 755 ./zsync
V/ImageWallpaper( 1477): onVisibilityChanged: mVisible, visible=true, false
V/ImageWallpaper( 1477): Visibility changed to visible=false
I/luajit-launcher(18987): command stdout:
I/luajit-launcher(18987): command stderr:
I/luajit-launcher(18987): command res:0
I/luajit-launcher(18987): try to load module libs/libkoreader-lfs.so
W/ActivityManager(  635): getRunningAppProcesses: caller 10013 is using old GET_TASKS but privileged; allowing
V/AppLockBridge( 2051): isAllowToActiveAppLock = true
```

**Comment by houqp** [comment]
Looks like it's loading fine. I have been experiencing the black screen issue with one of my old phone too. KOReader used to run fine on that phone. I noticed the black screen is caused by the fact that KOReader is running really slow. It takes minutes for it to update the screen and response to user input. That's why it started out as a blackscreen, if you wait for enough time, it will eventually draw and update the screen. I am not sure why this is happening yet.

**Comment by NiLuJe** [comment]
Wasn't the usual diagnostic for those kind of issues a JIT failure causing a fallback to interpreted code?

**Comment by houqp** [comment]
Good point, that's very likely the cause.

**Comment by Frenzie** [comment]
I don't know anything about Android debugging; is there any further info I
could provide?

**Comment by houqp** [comment]
We can check the JIT status using `DEBUG(jit.status())` call.

**Comment by houqp** [comment]
Hmm... jit.status returns true in my phone: `true ARMv7 VFPv3 fold cse dce fwd dse narrow loop abc sink fuse`. So looks like JIT is enabled. @Frenzie , can you help verify that you are having the same issue as mine? i.e. try wait for longer after the blank screen shows up, like 10 minutes, to see if there any change. You can also use `kodev log android` to monitor the log progress.

**Comment by houqp** [comment]
My initial test shows that it blocks on `bb:blitFrom(self.bb)` (`ffi/framebuffer_android.lua`) for a very long time. Not sure why this is happening yet.

**Comment by Frenzie** [comment]
I haven't been able to see anything drawing on the screen after waiting for like ten minutes, but I can confirm that KOReader uses up all of one of my cores. However, using `kodev log android` shows something that might be relevant:

```
$ sudo ./kodev log android
--------- beginning of crash
--------- beginning of system
--------- beginning of main
I/luajit-launcher(31787): Application data directory /data/data/org.koreader.launcher/files
I/luajit-launcher(31787): Application library directory /data/app/org.koreader.launcher-1/lib/arm
I/luajit-launcher(31787): Screen size 1080x1920
I/luajit-launcher(31787): Screen brightness 15
I/luajit-launcher(31787): Check file in asset module: koreader-gcf9dc26.7z
I/luajit-launcher(31787): Skip installation for revision gcf9dc26
I/luajit-launcher(31787): Change directory to /data/data/org.koreader.launcher/files
I/luajit-launcher(31787): intent file path 
I/luajit-launcher(31787): run command chmod 755 ./sdcv
I/luajit-launcher(31787): command stdout:
I/luajit-launcher(31787): command stderr:
I/luajit-launcher(31787): command res:0
I/luajit-launcher(31787): run command chmod 755 ./tar
I/luajit-launcher(31787): command stdout:
I/luajit-launcher(31787): command stderr:
I/luajit-launcher(31787): command res:0
I/luajit-launcher(31787): run command chmod 755 ./zsync
I/luajit-launcher(31787): command stdout:
I/luajit-launcher(31787): command stderr:
I/luajit-launcher(31787): command res:0
I/luajit-launcher(31787): try to load module libs/libkoreader-lfs.so
I/luajit-launcher(31787): ffi.load SDL2
I/luajit-launcher(31787): ffi.load SDL
W/luajit-launcher(31787): cannot blit: no window
I/luajit-launcher(31787): # initializing for device Android
I/luajit-launcher(31787): # framebuffer resolution: {
I/luajit-launcher(31787): 	["h"] = 1920,
I/luajit-launcher(31787): 	["w"] = 1080
I/luajit-launcher(31787): }
I/luajit-launcher(31787): ffi.load libs/libfreetype.so.6
I/luajit-launcher(31787): ffi.load libs/libmupdf.so
I/luajit-launcher(31787): ffi.load libs/libwrap-mupdf.so
I/luajit-launcher(31787): try to load module common/serialize.so
I/luajit-launcher(31787): # cache image|resources/icons/appbar.chevron.left.png||
I/luajit-launcher(31787): # cache image|resources/icons/appbar.chevron.right.png||
I/luajit-launcher(31787): # cache image|resources/icons/appbar.chevron.first.png||
I/luajit-launcher(31787): # cache image|resources/icons/appbar.chevron.last.png||
I/luajit-launcher(31787): # cache image|resources/icons/appbar.arrow.left.up.png||
I/luajit-launcher(31787): # show widget
```

Note the `W/luajit-launcher(31787): cannot blit: no window`. How do I get it to run this DEBUG status call? Would I have to build the whole Android toolchain myself? I'd rather avoid that, you see. :P

**Comment by houqp** [comment]
`cannot blit` error should go away with the latest android build. If you don't want to install the android TC, you can hack around by unzip the apk, change the files inside and zip it back.

Looking at your log, I am pretty sure you are running into the same issue as mine. On My phone, it works totally fine before. Now it's just really really slow on loops. I suspect it's related to this: http://www.freelists.org/post/luajit/Extremely-slow-JIT-on-ARM,5

I tried tuning off jit, but still does not help. I will dig further tonight to see if it's actually a mem allocation issue in JIT compiler :(

**Comment by Frenzie** [comment]
Oh, I thought those APKs were signed and stuff. I'll check up on the JIT status tomorrow.

**Comment by KenMaltby** [comment]
They are but you can modify scripts or resources in them then sign your modified .apk with EasyAPKDisasembler https://code.google.com/archive/p/easy-apk-dissassembler/downloads and they will install.  (I replace the KOreader Icon with my egocentric one, as well as test script changes that way.)

**Comment by gerroon** [comment]
@houqp 
It must be memory allocation because I have bunch of devices with various rams and os combinations and Kr is so inconsitent with performance and speed and crashes among these devices. Sometimes it works in low end android ereaders (C67ML) but not on highend latest android devices of mine (like Lenovo A10-70f).

**Comment by chrox** [comment]
Maybe we can debug the issue like this https://github.com/koreader/koreader/issues/1456#issuecomment-82028581 in #1456. It looks like a JIT failure issue.

**Comment by houqp** [comment]
Unfortunately, the phone that's having this issue is not rooted :( I will see if it's possible to get root access tomorrow.

Assuming it's mcode allocation that's failing, shouldn't it be taken care by https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L20?

**Comment by chrox** [comment]
Not necessarily. On some devices there is not a single free slot for mcode in the short jump range, for example some devices that install xposed framework.

**Comment by gerroon** [comment]
@chrox 

Kr did not work on my Galaxy when it had Xprivacy+Android Kitkat but when I upgraded the same device to Android Lollipop along with Xposed/Xprivacy Kr started working fine (although a biut laggy sometimes)

**Comment by houqp** [comment]
Confirmed that in my case, it's the mcode allocator that's failing to find a large enough mcode area for JIT compiler:

```
I/luajit-launcher(14483): SELF MAP:::::: 505f8000-505f9000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 505f9000-506f8000 rw-p 00000000 00:00 0          [stack:14490]
I/luajit-launcher(14483): SELF MAP:::::: 506f8000-50721000 r--s 005b1000 b3:21 73768      /system/framework/com.htc.resources.apk
I/luajit-launcher(14483): SELF MAP:::::: 50721000-5094c000 r--s 0036c000 b3:21 73768      /system/framework/com.htc.resources.apk
I/luajit-launcher(14483): SELF MAP:::::: 5094c000-50989000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5098b000-509d3000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 509d6000-509e0000 r--s 0019e000 b3:21 73788      /system/framework/framework-htc-res.apk
I/luajit-launcher(14483): SELF MAP:::::: 509e0000-50a28000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50a2b000-50a63000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50a68000-50b06000 r--s 000fb000 b3:21 73788      /system/framework/framework-htc-res.apk
I/luajit-launcher(14483): SELF MAP:::::: 50b06000-50b2b000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50b2b000-50bec000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50bec000-50c46000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50c49000-50d00000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50d02000-50d0c000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50d0d000-50d21000 r--s 00000000 b3:21 65575      /system/fonts/Roboto-Regular.ttf
I/luajit-launcher(14483): SELF MAP:::::: 50d21000-50d33000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50d3a000-50da6000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50da7000-50db0000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50db3000-50de5000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50de8000-50e25000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50e2b000-50e92000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50e93000-50fe0000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 50fe0000-5100d000 r-xp 00000000 b3:21 82188      /system/lib/libmedia_jni.so
I/luajit-launcher(14483): SELF MAP:::::: 5100d000-5100e000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5100e000-5100f000 r--p 0002d000 b3:21 82188      /system/lib/libmedia_jni.so
I/luajit-launcher(14483): SELF MAP:::::: 5100f000-51010000 rw-p 0002e000 b3:21 82188      /system/lib/libmedia_jni.so
I/luajit-launcher(14483): SELF MAP:::::: 51014000-51021000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51021000-5102d000 r-xp 00000000 b3:21 82285      /system/lib/libstagefright_amrnb_common.so
I/luajit-launcher(14483): SELF MAP:::::: 5102d000-5102e000 r--p 0000b000 b3:21 82285      /system/lib/libstagefright_amrnb_common.so
I/luajit-launcher(14483): SELF MAP:::::: 5102e000-51047000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51047000-51054000 r-xp 00000000 b3:21 81993      /system/lib/libandroid.so
I/luajit-launcher(14483): SELF MAP:::::: 51054000-51055000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51055000-51057000 r--p 0000d000 b3:21 81993      /system/lib/libandroid.so
I/luajit-launcher(14483): SELF MAP:::::: 51057000-51058000 rw-p 0000f000 b3:21 81993      /system/lib/libandroid.so
I/luajit-launcher(14483): SELF MAP:::::: 51059000-51066000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51066000-510dd000 r--s 00000000 b3:21 49313      /system/usr/share/zoneinfo/zoneinfo.dat
I/luajit-launcher(14483): SELF MAP:::::: 510dd000-510fe000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 510fe000-51127000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51138000-51141000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51141000-511a4000 r-xp 00000000 b3:23 90127      /data/data/org.koreader.launcher/lib/libluajit-launcher.so
I/luajit-launcher(14483): SELF MAP:::::: 511a4000-511a5000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 511a5000-511a6000 r--p 00063000 b3:23 90127      /data/data/org.koreader.launcher/lib/libluajit-launcher.so
I/luajit-launcher(14483): SELF MAP:::::: 511a6000-511a7000 rw-p 00064000 b3:23 90127      /data/data/org.koreader.launcher/lib/libluajit-launcher.so
I/luajit-launcher(14483): SELF MAP:::::: 511b1000-511bb000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 511bb000-511db000 rw-p 00000000 00:00 0                                                                                                                                                      [8/48130]
I/luajit-launcher(14483): SELF MAP:::::: 511e2000-5120a000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5120a000-5122a000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51236000-5124d000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51251000-5126b000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5126b000-5128b000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5129d000-512a6000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 512d1000-512f7000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 512f7000-5137b000 r-xp 00000000 b3:21 81982      /system/lib/libRS.so
I/luajit-launcher(14483): SELF MAP:::::: 5137b000-5137c000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5137c000-5137e000 r--p 00084000 b3:21 81982      /system/lib/libRS.so
I/luajit-launcher(14483): SELF MAP:::::: 5137e000-5137f000 rw-p 00086000 b3:21 81982      /system/lib/libRS.so
I/luajit-launcher(14483): SELF MAP:::::: 513ad000-51604000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51604000-51dd9000 r--s 00000000 b3:21 49281      /system/usr/icu/icudt48l.dat
I/luajit-launcher(14483): SELF MAP:::::: 51dd9000-51f47000 r-xp 00000000 b3:21 82284      /system/lib/libstagefright.so
I/luajit-launcher(14483): SELF MAP:::::: 51f47000-51f50000 r--p 0016d000 b3:21 82284      /system/lib/libstagefright.so
I/luajit-launcher(14483): SELF MAP:::::: 51f50000-51f51000 rw-p 00176000 b3:21 82284      /system/lib/libstagefright.so
I/luajit-launcher(14483): SELF MAP:::::: 51f51000-51f53000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 51f53000-52185000 r-xp 00000000 b3:21 82008      /system/lib/libchromium_net.so
I/luajit-launcher(14483): SELF MAP:::::: 52185000-52186000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 52186000-52194000 r--p 00232000 b3:21 82008      /system/lib/libchromium_net.so
I/luajit-launcher(14483): SELF MAP:::::: 52194000-52195000 rw-p 00240000 b3:21 82008      /system/lib/libchromium_net.so
I/luajit-launcher(14483): SELF MAP:::::: 52195000-521a7000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 521a7000-525fa000 r-xp 00000000 b3:21 82007      /system/lib/libbcc.so
I/luajit-launcher(14483): SELF MAP:::::: 525fa000-52623000 r--p 00452000 b3:21 82007      /system/lib/libbcc.so
I/luajit-launcher(14483): SELF MAP:::::: 52623000-52625000 rw-p 0047b000 b3:21 82007      /system/lib/libbcc.so
I/luajit-launcher(14483): SELF MAP:::::: 52625000-52648000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 52648000-52758000 r-xp 00000000 b3:21 82006      /system/lib/libbcinfo.so
I/luajit-launcher(14483): SELF MAP:::::: 52758000-5275c000 r--p 0010f000 b3:21 82006      /system/lib/libbcinfo.so
I/luajit-launcher(14483): SELF MAP:::::: 5275c000-5275d000 rw-p 00113000 b3:21 82006      /system/lib/libbcinfo.so
I/luajit-launcher(14483): SELF MAP:::::: 52794000-52cd9000 r-xp 00000000 b3:21 82338      /system/lib/libwebcore.so
I/luajit-launcher(14483): SELF MAP:::::: 52cd9000-52d4c000 r--p 00544000 b3:21 82338      /system/lib/libwebcore.so
I/luajit-launcher(14483): SELF MAP:::::: 52d4c000-52d57000 rw-p 005b7000 b3:21 82338      /system/lib/libwebcore.so
I/luajit-launcher(14483): SELF MAP:::::: 52d57000-52d5c000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 52d5c000-52d96000 r-xp 00000000 b3:21 82177      /system/lib/libkikin.so
I/luajit-launcher(14483): SELF MAP:::::: 52d96000-52d97000 r--p 00039000 b3:21 82177      /system/lib/libkikin.so
I/luajit-launcher(14483): SELF MAP:::::: 52d97000-52d98000 rw-p 0003a000 b3:21 82177      /system/lib/libkikin.so
I/luajit-launcher(14483): SELF MAP:::::: 52d98000-53023000 r-xp 00000000 b3:21 82328      /system/lib/libv8.so
I/luajit-launcher(14483): SELF MAP:::::: 53023000-53024000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 53024000-53035000 r--p 0028b000 b3:21 82328      /system/lib/libv8.so
I/luajit-launcher(14483): SELF MAP:::::: 53035000-53038000 rw-p 0029c000 b3:21 82328      /system/lib/libv8.so
I/luajit-launcher(14483): SELF MAP:::::: 53038000-53039000 rw-p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 53039000-5303a000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5303a000-53139000 rw-p 00000000 00:00 0          [stack:14491]
I/luajit-launcher(14483): SELF MAP:::::: 53139000-5313a000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5313a000-53239000 rw-p 00000000 00:00 0          [stack:14492]
I/luajit-launcher(14483): SELF MAP:::::: 53239000-5323a000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 5323a000-53339000 rw-p 00000000 00:00 0          [stack:14493]
I/luajit-launcher(14483): SELF MAP:::::: 53339000-53537000 r--p 00000000 00:0a 4932       /dev/binder
I/luajit-launcher(14483): SELF MAP:::::: 53537000-53538000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 53538000-53637000 rw-p 00000000 00:00 0          [stack:14494]
I/luajit-launcher(14483): SELF MAP:::::: 53637000-53638000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 53638000-53737000 rw-p 00000000 00:00 0          [stack:14495]
I/luajit-launcher(14483): SELF MAP:::::: 53737000-53738000 ---p 00000000 00:00 0 
I/luajit-launcher(14483): SELF MAP:::::: 53738000-53837000 rw-p 00000000 00:00 0          [stack:14497]
I/luajit-launcher(14483): SELF MAP:::::: 53837000-53937000 r-xp 00000000 00:04 414606     /dev/ashmem/dalvik-jit-code-cache (deleted)
I/luajit-launcher(14483): SELF MAP:::::: bed29000-bed4a000 rw-p 00000000 00:00 0          [stack]
I/luajit-launcher(14483): SELF MAP:::::: ffff0000-ffff1000 r-xp 00000000 00:00 0          [vectors]
```

Setting `sizemcode` to 128 makes the JIT compiler happy again. Since the memory address around luajit.so is completely out of our control, I am thinking of dynamically adjust `sizemcode` on start based on `/proc/self/maps`. And if there no enough space, just turn off JIT completely to avoid the random memory probe that mcode allocator does everytime it tries to allocate a memory for traces.

Another thing I thing we should do is to at least rewrite the bliting code path in blitbuffer mode in C for android. This will at least makes KOReader usable when JIT is turned off (assuming we don't have many tight loops in other places). It will also make KOReader faster with JIT turned on.

**Comment by gerroon** [comment]
@houqp 

Thanks for digging into this issue. We need stable Kr on Android very badly.

**Comment by chrox** [comment]
The maps file is only accessible with root permission so it's not an option. A more viable way is extending luajit to have explicit annotations for JIT code block, which could save precious mcode memory space on some platforms. Compared to the rewriting in C approach, this could be a good to have feature of luajit and may be useful to other projects that may have the same problem with koreader.

**Comment by houqp** [comment]
`/proc/self/maps` does not require root access, that's how I read mine. My phone is still not rooted yet :P Windows VM is not working properly for me.

The problem here is luajit mcode allocator only does random probing. Which means there could be enough way more space than needed around the jump target, but it can still fail after trying the random probe for 32 times as shown in my previous comment. Because of this, we can't adjust the mcode on start based on the memory map as I suggested before. My nexus5x has way less available memory in the jump range compared to my HTC one X, yet the blank screen happens only on HTC.

Another easy workaround can be trying different mcode size on start, i.e. start with `512`, if it failed, then try `256`, `128` and finally `64`.

As for rewriting the bliting loop in C, I think it's a thing that we need to do in the future anyway. It will yield better performance in either case. Currently we are doing pixel by pixel read/set, which is very low efficient. And the bliting C code should be very simple and easy to maintain.

**Comment by houqp** [comment]
After playing around with the mcode setting more, I am lost again. LuaJIT was able to create trace for our dummy loop no matter how large I set the `sizemcode` to, for example `640000`. It will only start giving out `failed allocate mcode memory` error in blitbuffer module. The size I given is already larger than the jump range, so shouldn't I get a trace abort event from the beginning?

The error goes away after I set the `sizemcode` to lower than `132`, which makes sense as it's more likely to find a small region with random probing.

**Comment by houqp** [comment]
@chrox , how hard is it to implement explicit annotation? And how much memory can we save from doing that?

**Comment by chrox** [comment]
Yes, allocating a large mcode memory is just a workaround and it may not work on every circumstance. It seems we cannot implement that feature with existing luajit APIs. And we need to patch luajit to jit-compiling only the code blocks that are specified in the code for example between two api calls. I guess in this way the four blitbuffer loops won't take more than 8KB of memory that needs to be allocated around luajit base address.

**Comment by chrox** [comment]
And from my observation the bionic implementation of mmap returns monotonically increasing address without regarding the hint address given in the mmap call which is not taken care of in luajit's allocation probe function. That's a big reason why after several probes it will never return an allocation in proper address range. So increasing probing times won't help at all. And the less execution memory we need the more opportunity we get successful allocation.

**Comment by houqp** [comment]
Ha, I see what you meant by explicit annotation now. It would be nice to have priority based tracing so we can guarantee annotated code are JIT compiled while JIT compile other code too if there is extra space.

Another thing we can possibly do to is to statically pre-allocate a large noop code region at compile time. Then patch the mcode allocator to only use this memory region instead of mmap at run time.

I still don't understand why setting `sizemcode` to a number that's larger than jump range won't cause trace abort from the beginning though.

**Comment by gerroon** [comment]
This is all I get with some pdf books on Lollipop. I waited like 5 mins without any change.

I/luajit-launcher(29557): Waiting for app ready...
I/luajit-launcher(29557): App window ready.
I/luajit-launcher(29557): App gained focus.
I/luajit-launcher(29557): Launching LuaJIT assets...
I/luajit-launcher(29557): Application data directory /data/data/org.koreader.launcher/files
I/luajit-launcher(29557): Application library directory /data/app/org.koreader.launcher-1/lib/arm
I/luajit-launcher(29557): Screen size 800x1280
I/luajit-launcher(29557): Screen brightness 94
I/luajit-launcher(29557): Check file in asset module: koreader-g9a3e262.7z
I/luajit-launcher(29557): Skip installation for revision g9a3e262
I/luajit-launcher(29557): Change directory to /data/data/org.koreader.launcher/files

**Comment by houqp** [comment]
Yeah, at this point, I would say android port is very broken until we fix the mcode allocation issue.

**Comment by chrox** [comment]
Koreader for Android has changed a lot since this issue was reported so the provided logs might be out of date. Please retry with the latest nightly build and report back if you still have this problem.

**Comment by sunnsi** [comment]
I have installed the latest version released on 6.24. The app always crashes when it opens any pdf file on SD card. My device is LG gpad 8.3. It works fine when pdf files on internal storage are opened.

**Comment by chrox** [comment]
What's your Android version?

**Comment by sunnsi** [comment]
Android 5.0.2. The path for SD card is /storage/external_SD/.  The path of internal storage is  /storage/sdcard0 or /storage/emulated/0/ or /storage/emulated/legacy or /sdcard/ ,  I have no idea which ones are symbol links.

**Comment by chrox** [comment]
Do you have a logcat of koreader when you open a PDF file on SD card? Maybe we can get more information from it.

**Comment by sunnsi** [comment]
Thanks for your quickly reply. Would you like to give me a hand on how to produce a log file?
