### ISSUE TITLE
Grid layout history view with book cover in file manager

### ISSUE THREAD

**Issue by chrox** [koreader/koreader#1790]

**Comment by robert00s** [comment]
I think that is done by @poire-z Cover Browser plugin.

**Comment by Frenzie** [comment]
Adding #2940 for cross-reference and closing.

**Comment by venken** [comment]
When the book screen stops running, how to return to the desktop? At present, my operation room is restarted

**Comment by Frenzie** [comment]
If you open the top menu, there's exit in the top right under the hamburger menu.
