### ISSUE TITLE
Where can I download the latest nightly?

### ISSUE THREAD

**Issue by thebombsauce** [koreader/koreader#1792]
The ota sources seem to be using a very old version and the current nightly on the wiki is pretty out of date too. How can I get my hands on the latest version of koreader?

**Comment by AlanSP1** [comment]
Strange, like you read my mind (or I yours :D). I just opened this thread: http://www.mobileread.com/forums/showthread.php?t=270548

Newer OTA I found is here: http://vislab.bjmu.edu.cn/apps/koreader/ota/ (it's not latest, but it's not that very old).

And, I too would like to see some newer nightlies.
