### ISSUE TITLE
Overlap is greyed out when reflow is enabled.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1794]
After I am switch to reflow, I cannot enable the overlap feature. My work-around is to disable reflow, enable overlap, enable reflow and voilà: greyed out area of the text that was already on the previous screen.

Why is overlap greyed out when I enable reflow?

**Comment by chrox** [comment]
This is by design. Because page overlay is unnecessary in scroll mode which is automatically turned on in reflow mode. You can re-enable page overlay after scroll mode is disabled.

**Comment by Markismus** [comment]
Ah, will try. Thanks!
