### ISSUE TITLE
Crash when selecting book from history on my Aura HD

### ISSUE THREAD

**Issue by hombretranquilo** [koreader/koreader#1796]
Koreader crashes after select a book from history. Koreader version is 2015.11-82 (fresh  installation), and device is Aura HD.
Crash log says:
./luajit: frontend/apps/reader/modules/readerhinting.lua:10: attempt to index field 'document' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerhinting.lua:10: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:67: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:79: in function 'handleEvent'
	frontend/apps/reader/modules/readerview.lua:351: in function 'action'
	frontend/ui/uimanager.lua:353: in function '_checkTasks'
	frontend/ui/uimanager.lua:497: in function 'handleInput'
	frontend/ui/uimanager.lua:587: in function 'run'
	./reader.lua:147: in main chunk
	[C]: at 0x0000bed5

**Comment by houqp** [comment]
Is this always reproducible? Were you reading the book in scroll mode?

**Comment by chrox** [comment]
I cannot reproduce this and I suspect the file in that  history entry is already deleted.

**Comment by hombretranquilo** [comment]
Yes, crash happens with all the books in history menu, and there is no difference if the book is in scroll mode or not. 
Now, for testing behaviour, I reistalled koreader-v2015.11-stable, koreader-v2015.11-11, koreader-v2015.11-40, and koreader-v2015.11-82.Tests are made with the same five books on different formats (epub, pdf, etc.), on different locations (both external and internal sd card). The tests results show that there is no crash on versions 2015.11-stable, and 2015.11-11, but on versions 2015.11-40 and 2015.11-82, if  history menu is used, koreader crashes.

**Comment by KenMaltby** [comment]
Works fine with koreader-v2015.11-82, in my Aura HD.  Books in History have been opened successfully, so they should not have anything obvious wrong with them, to cause a crash.  If there is something in the install of the newer builds that makes changes to the history/sdr files it has not effected those I had/have.

**Comment by houqp** [comment]
I suspect the history files somehow got corrupted. Can you upload some sample files under history directory here?

Also anyone what's the commit hash for 2015.11-11 and 2015.11-40 respectively? Looks like the crash is caused by commits added between these two version. But I don't know what's a good way to trace back the commit hash by our release version. @hombretranquilo , can you post the full filename for those two releases?

**Comment by hombretranquilo** [comment]
I tested some more versions. Last working fine (for me) version is v2015.11-11-g16509e2, and first version that crashes is v2015.11-25-gf3dba98. A zip with some sample files under history directory is attached. These files cause a crash in v2015.11-25, but in v2015.11-11 work well (I copy & pasted them).
[history.zip](https://github.com/koreader/koreader/files/126157/history.zip)

**Comment by houqp** [comment]
Thanks a lot for the detailed report. I will take a deeper look at it tomorrow.

**Comment by hombretranquilo** [comment]
Today I have noticed that if History menu is launched from Filemanager you can select a book from history and there is no crash (all versions work well), but if History menu is launched when reading a book, the selection of a book from history causes a crash (since v2015.11-25-gf3dba98). 
Thanks for your time!

**Comment by houqp** [comment]
Aha, everything makes sense now if it's only crashing from the reader ui. I will submit a fix in an hour :)

**Comment by hombretranquilo** [comment]
I added  manually the changes from fix #1796. The issue is solved.
Thanks a lot @houqp @chrox @KenMaltby for your time.

**Comment by houqp** [comment]
@hombretranquilo also thank you for collecting all the bug information. It makes debugging a lot easier for us.
