### ISSUE TITLE
Kobo Aura sleep buttons poweroff koreader

### ISSUE THREAD

**Issue by TheGodgod** [koreader/koreader#1799]
Running the lastest stable build and the sleep button, sometimes poweroff the device

**Comment by houqp** [comment]
This is weird. There is no device power off logic in KOReader. Do you see any crash.log when you restart the device from the shutdown?

**Comment by KenMaltby** [comment]
How is it you established that your device was powered off?  Did a "Power Off" image appear?  Were you returned to your launcher?  Did it return to Nickel?

**Comment by chrox** [comment]
The OP didn't provide enough information to reproduce this issue. So please feel free to reopen this if you still have this problem, I'm closing this now.
