### ISSUE TITLE
kindle voyage blank screen when waked up from screen saver 

### ISSUE THREAD

**Issue by dracodoc** [koreader/koreader#1800]
koreader version

    koreader-kindle-arm-linux-gnueabi-v2015.11-11-g16509e2.zip

In kindle voyage, 5.6.5 jb, screen saver hack with customized images. 
1. put kindle to sleep with power button, screen saver on.
2. wake up kindle, there is a white blank screen. Click screen will turn page and refresh screen to show contents.

It seemed that there should be a screen refresh after wake up.

**Comment by chrox** [comment]
I can reproduce this occasionally on my Kindle Voyage. And it seems to occur much more often in winter time when the temperature is lower.

**Comment by NiLuJe** [comment]
That vaguely rings a bell too...

**Comment by dracodoc** [comment]
Is this related?
[no need to do full screen refresh when outof screensaver](https://github.com/chrox/koreader/commit/4920426148def93ba75928cac4220e508591c321)

**Comment by dracodoc** [comment]
It may indeed relate to the temperature. This morning it occurs every time when I tested, and now it is normal. 

I guess normally there is a full screen refresh by kindle system, so the above fix removed the additional refresh, but the full screen refresh by system didn't happen in some cases, which caused the problem.

I'd want the additional full screen fresh even it is redundant sometimes. It sure is better than wake up kindle and get a blank screen! Somebody may think his kindle is broken...

**Comment by chrox** [comment]
Sounds reasonable. I will fix it later.
