### ISSUE TITLE
kindle voyage hard page turn key messed up

### ISSUE THREAD

**Issue by dracodoc** [koreader/koreader#1801]
koreader version

    koreader-kindle-arm-linux-gnueabi-v2015.11-11-g16509e2.zip

In kindle voyage, 5.6.5 jb, open an epub book.

The problem is pretty random, I didn't find a reproducible action sequence yet. 
If I mix the screen tap page turn and the hard key page turn, back and forth, there will be several possible problems:

1. page down by hard key actually page down then page up.
2. page up by hard key turn 2 pages back.

My guess is the the "page" definition in epub have different meanings in two page turn method. Maybe the hard key page turn started from the page number, not the current view location.

**Comment by chrox** [comment]
If you launch Koreader via KUAL, you may end up with non-functional hardware page up button. And when launching Koreader via KPVBooklet the hardware buttons should work fine (at least on my Kindle Voyage 5.6.5). The "whisper touch" on KPVBooklet is supported by https://github.com/koreader/kpvbooklet/commit/584cb757cd1eb60c421a862202273b8355bc5670

**Comment by dracodoc** [comment]
I'm launching Koreader through KPVBooklet. The button is working but have random problems. I can just use touch instead of the button till I find a repeatable action sequence to report.

**Comment by TheNeedForRead** [comment]
Hi, thanks for your excellent work!

I concur that Page Press/haptic support does not work in KUAL, but works through KPVBooklet.
I believe I can shed some light on this issue, which I would love to see fixed.

**Technically, all four Voyage buttons are working perfectly. The 'double-press' issue is caused by the thumb touching the screen after a Voyage button is pressed.**

Whatever code exists in the default reader, which temporarily de-activates the touch-screen while a button is pressed, is currently not present/activated in KOReader.

I am running 5.7.4fw Serial JB KV

**Comment by houqp** [comment]
I don't have a voyager, are those buttons very close to the screen? If this is really the case, we can add the code. @TheNeedForRead how long does the native reader disable touch after the button is pressed?

**Comment by TheNeedForRead** [comment]
Hi, sorry Houp I updated my message a moment ago, I have performed a few more tests and realised was incorrect in my first assumption!  It's a touchscreen deadzone issue, not a touchscreen deactivation issue.

**Comment by houqp** [comment]
Interesting, so the dead zone feature remains active if KOReader is launched through KPVBooklet?

**Comment by TheNeedForRead** [comment]
To clarify:

- Kindle reader program has a permanent 7-8mm deadzone around the touchscreen
- KOReader (KPVBooklet or KUAL-launched) has no deadzone
- Voyage buttons (and haptic feedback) do not work in KUAL-launched KOReader
- Voyage buttons (and haptic feedback) work perfectly in KPVBooklet-launched KOReader, but the presses are adversely affected by the lack of deadzone.

**Comment by houqp** [comment]
Thanks for the clarification. If the dead zone is permanent, then it's trivia to implement from our side :)

The only information we need is how much 8mm maps to screen coordinate. Do you have ssh access to the device? If so, you can run koreader in debug mode with `./reader.lua -d`. Then you will be able to get coordinates for the touch events. It will show up in the log as something like: 

```
# single tap detected in slot 0 {
        ["y"] = 552,
        ["x"] = 468,
        ["h"] = 0,
        ["w"] = 0
}
```

A rough estimate should be enough.

**Comment by dracodoc** [comment]
@TheNeedForRead , thanks for the discovery, now the mystery is solved!

If KOreader was to implement a similar deadzone feature, will the bookmark action be interfered? I found the current active zone for bookmark too small anyway. You have to click the exact corner to add the bookmark.

**Comment by houqp** [comment]
We might have to tweak that too. We will see after the dead zone is implemented :)

**Comment by TheNeedForRead** [comment]
Hi guys, sorry to disappear but as of this afternoon I'm going to be unavailable for up to a couple of weeks. However, I've posted a shout-out regarding this bug to Voyage users on [mobileread](http://www.mobileread.com/forums/showthread.php?p=3326755#post3326755) asking for a volunteer for this bug specifically. (Although it only just occurred to me that dracodoc might be able to do it :D )

Have a great start to June and I'll drop in when I return.

**Comment by chrox** [comment]
I also encountered this problem occasionally and it was annoying sometimes. So I can help to implement this touch deadzone for Kindle Voyage.

**Comment by AuTa** [comment]
When I use AD screensaver, then return read, Voyage buttons can not use.
Maybe this is a other problem.
