### ISSUE TITLE
load the additional CJK fonts that downloaded in updates

### ISSUE THREAD

**Issue by dracodoc** [koreader/koreader#1802]
`koreader` can load the host fonts from the kindle system, but there are some CJK fonts that were not part of the firmware. If you set the system language as Chinese and read some Chinese books with wifi on, kindle will download additional font pack later, mainly the Kaiti font.

This font must located in different location so `koreader` didn't load it. Can koreader find this font and load it into font list too?

**Comment by frankyifei** [comment]
it's easy to add your own fonts just put them in /koreader/fonts

**Comment by dracodoc** [comment]
But I can't extract the font I mentioned. Actually I was asking how to extract that font in mobileread forum first, @NiLuJe suggested me to open a ticket here. 

I think it is a good idea because user don't need to do anything, and it can handle any new fonts updates in future.

**Comment by NiLuJe** [comment]
Yep, trivial to do. I just need a look an actual device to confirm the path, can't remember it OTOH ^^

**Comment by NiLuJe** [comment]
Said path *should* be: /var/local/font/mnt

**Comment by KenMaltby** [comment]
Wasn't there something related to "fall back fonts" with this?

**Comment by NiLuJe** [comment]
Hmm, no, I think Amazon just uses this to avoid shipping heavy CJK fonts on models where they're not needed?

We always have code2000 as a fallback, that hasn't changed.

**Comment by dracodoc** [comment]
Did anybody test it working? I tried the latest nightly build and it should include this fix, but the fonts are not in list.
I saw there is a cspfonts/zh-Hans_font folder created, but nothing inside it.

**Comment by NiLuJe** [comment]
Bleh, which means everything probably gets mounted in a subdirectory, not fun.

D you happen to have shell access to your device?

**Comment by dracodoc** [comment]
I don't have it now. I can install usbnetwork to voyage, but it seemed that I need to connect from a linux machine while I'm using windows. 

I can try usbnetwork if nobody in developers is using Chinese as default language
