### ISSUE TITLE
New build?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1803]
HI

Can we please get a new Android build ? Most recent one is from November.

Thanks

**Comment by KenMaltby** [comment]
There are newer builds, except for the Android version, at the OTA sites.

**Comment by gerroon** [comment]
Yeah that does not help me. I want to try it on my Android devices.

**Comment by KenMaltby** [comment]
There might be others who see the question and look to the answer.

**Comment by houqp** [comment]
@chrox, what's the status of android nightly build? IIRC, it's handled the same as builds for other platforms?

**Comment by gerroon** [comment]
Any update on this?


thanks

**Comment by chrox** [comment]
Sorry for the late release. Latest nightly builds are already uploaded to the release page. Since Koreader on Android and Ubuntu-touch doesn't support OTA yet, the OTA server only has update packages for Kindle, Kobo and Pocketbook.
