### ISSUE TITLE
Howto uninstall Koreader on Pocketbook (go back to default reader)?

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#1805]
Does anybody know how to go back to the default reader on Pocketbook?

Since Koreader installation (or rather opening first epub and pdf file with it) files are automatically associated with Koreader, and I can't find a way back to default reader.
Can someone help?

I need to give it back for warranty, so help appreciated.
Marcin

**Comment by Frenzie** [comment]
Isn't that Android? If so go into Settings > Apps to uninstall. There might
also be some kind of factory reset in the settings.

**Comment by chrox** [comment]
Pocketbook uses a custom built linux firmware just like Kindle and Kobo. 

A factory reset should wipe out the koreader installation.

**Comment by mwozny123** [comment]
Ok. I didn't think about it, but ain't there a better way to uninstall koreader without wiping out everything?

**Comment by houqp** [comment]
koreader is self-contained should not change anything in the system. you should be able to just remove the whole folder together with those book settings files.

**Comment by mwozny123** [comment]
I think the problem here is that Pocketbook UI is using the same policy as Gnome, Unity. 
Once you open a file type with application it remembers it and always use this application for particular file type. 

I don't know how I did it(there's no "open with" option) but after first run koreader (and opening epubs and pdf) I wasn't able to go back to default system reader. 
It must happened automatically (association). 
And in my Pocketbook (Touch Lux 3) in menu there's only a file browser which starts Koreader on epubs and pdfs. There isn't a entry where I can start "system reader"

**Comment by chrox** [comment]
According to [the wiki](https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices):
```
2. Associate PDF/DJVU/EPUB/FB2 documents to Koreader (optional)
copy and merge the system directory in the unzipped archive into your PocketBook's USB root directory
```
You may need to revert the `system/config/extensions.cfg` file to clear the association of PDF/EPUB files with koreader.

**Comment by mwozny123** [comment]
@chrox thanks it works :)
