### ISSUE TITLE
FR: adding Status page as a screensaver option.

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1809]
Now that there is an interesting "Status" function page with reader notes and all, it might make a nice screensaver.  As an option to using the current book cover.

**Comment by Frenzie** [comment]
Interesting idea!

**Comment by houqp** [comment]
I like this idea! However, since the status page also has editing features, we should create an other interface that only pulls in the read only info from status page.

**Comment by KenMaltby** [comment]
I was thinking that, with the screensaver option set to use the status page, when the screensaver event occurs, the page would be written to a buffer as an image (nothing functional).

**Comment by AlanSP1** [comment]
It's good idea.

**Comment by apletnev** [comment]
Hi there, anyone can help me with this? Where i can read about the file system's structures (for kobo, kindle, etc) and events like "power off"? As i understand we have to make a screenshot of the status page, save it like a picture and put to some folder.

**Comment by KenMaltby** [comment]
Actually, I was hoping that it could be done with just additional framebuffers.  We wouldn't need or want the touchscreen functional, while it is displayed, as a "screensaver".  An actual image file shouldn't be needed, but if one were used it should be deleted on return from the suspend.  Of course anyone who actually does it, would be doing it in whatever way they can or wish it to work. 
Luck;
Ken
