### ISSUE TITLE
Add feature : adding notes and annotations on scanned PDF

### ISSUE THREAD

**Issue by yasteora** [koreader/koreader#1810]
Hi guys, I found I cant make annotations and notes for PDF that Scanned. also  I cant make notes for epub files.
 wether the feartrues can be achieved ?

**Comment by yasteora** [comment]
我发现我可以在扫描版PDF上直接做“一点”标记，但是选中的内容无法控制，实际上只能选中几个文字。
而且做完标记后，似乎没有任何办法取消掉，我只能通过删除koreader文件目录后，将原来的koreader文件目录复制回去。

**Comment by frankyifei** [comment]
the changes may have already saved to pdf file. try should open it on pc

**Comment by houqp** [comment]
To delete highlights, just tap on the highlighted text, then you should be able to see a pop up with option to delete the highlight.

**Comment by yasteora** [comment]
@houqp @frankyifei I had tried that method for my scanned PDF,but that does not work. So I delete the file.lua file on the /history/  and the .lua file on /document/ *.sdr/,the highlights would be Disappeared

**Comment by Frenzie** [comment]
Presumably fixed by #4773? :-)
