### ISSUE TITLE
Koreader vs Kindle passcode protection

### ISSUE THREAD

**Issue by ecc29** [koreader/koreader#1811]
I'm not sure if this is a problem or it's what koreader intended to be. Currently I'm running koreader-kindle-arm-linux-gnueabi-v2015.11-11-g16509e2.zip on my jailbroken PW3 with the passcode turned on. Usually if I leave the pw3 for a while, the screensaver will kick in, then if I turn on the pw3 again, a window will pop up asking for the passcode. 

But with koreader is running things are different. The screensaver will work, but when you turn on the kindle again, the passcode window will not pop up, it will go directly to the last page you read in koreader, and the koreader menu is working. If you quit the koreader, the passcode window will show up. It looks like koreader is running above the kindle passcode protection mechanism.

**Comment by NiLuJe** [comment]
@ecc29: That's because it is ;).

Not sure we have any way of plugging into it?

**Comment by ecc29** [comment]
@NiLuJe You mean the passcode will not work with Koreader running? That sucks. You know, it was like passcode protection was fighting with koreader for the control. In worst case, when I turned on the pw3, the passcode input window popped up, but it didn't respond to any input. It looked like the pw3 was frozen. I guess the touch screen controller actually sent the signal to koreader. If koreader responded to the input, it won't display properly, the whole screen was messed up.

**Comment by Vijay-Beeshmacharri** [comment]
@ecc29 
@NiLuJe 

I have a PW2 and the same happens to mine too. I have a magnetic case which auto sleeps/wakes when closed/opened. If I close (lock) the case with a book open in KOReader, and then open it later, the passcode prompt do comes up, but when i try to type passcode, the next to last read page opens in KOReader (I am guessing depending on the position when i try to type it either goes forward a page or back a page.) I thought I was the only one having this issue. 

Once the book opens in KOReader when unlocking, I can do everything with page turns and menu options. But when I hit "Home" menu, it stops responding as @ecc29 said. The passcode prompt is actually on the screen but needs screen refresh. At this point, either I can type my code guessing its position (only those positions get refreshed) or I can lock again and unlock the PW2.

Just thought I'll add the behavior sequence, so it may help if it is taken up in the next fix.


VJ

**Comment by houqp** [comment]
Yep, KOReader will take over everything so it won't play along with any kindle native feature. Since amazon won't open the api, it's a pain in the ass to integrate with the native system.

**Comment by NiLuJe** [comment]
Note that on FW >= 5.7.2.1, since we now sigstop awesome while running, and restore a mix of an old fb dump to the screen on exit, it may be even more weird.

**Comment by ecc29** [comment]
@houqp Actually I have no problem if Koreader really has total control over everything. The problem is Koreader only has part of the control and that's why things are messed up. Koreader has the input signal, but it cannot display its UI correctly. It's even worse when koreader is launched in no framework mode. After the screensaver picture is displayed, if you push the power button, the screen will not change, and the pw3 will not respond to any input. Just looks like it's bricked. In this case the only choice is to push the power button long enough to force restart.

**Comment by houqp** [comment]
Hmm... looks like we failed to sigstop the passcode protector program? I am surprised that you get a screen freeze with kill framework start. Looks like this start mode is broken then.

**Comment by NiLuJe** [comment]
Hmm, you're not supposed to be able to put the device to sleep at all right now in "no framework" mode with FW 5.x, so I'm not quite sure what you're doing since you mentioned having seen a screensaver...

**Comment by NiLuJe** [comment]
Works for me w/ the framework running.

Although I just remembered why I tried to avoid sigstopping awesome in the past: it inhibits native screensavers...

**Comment by NiLuJe** [comment]
See the PR that just popped up for the gory details.

The only 'good' solution I could think of was simply disabling the passcode while KOReader is running.

**Comment by Vijay-Beeshmacharri** [comment]
Thanks for the fix/workaround. This certainly works. Disabling the PassCode when KOReader is running enables the screen to open the last open page when Kindle PW2 resumes. Before this fix, when I swipe or touch somewhere on the screen to open the KOReader, the action will lead to a new page appearing depending on the position of the touch (like any link clicked, or progressed to prev page or next page,  or sometimes even 2 pages).
