### ISSUE TITLE
Formatting - instead of centering justified left

### ISSUE THREAD

**Issue by Ebrehem** [koreader/koreader#1812]
I have a book with the following formatting, where both the author and the first line of the title is justified left in koreader, while in the kepub reader it is centered, and also in calibre viewer. The book is converted from the odt I prepared, where title and author styles are centered.

So the following lines are left justified:
Mág Bertalan
Nyomon

and only this one is centered:
a Mág-csoport

The (I hope) relevant part of the HTML:
```
<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Nyomon a Mág-csoport</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="stylesheet.css" rel="stylesheet" type="text/css"/>
<link href="page_styles.css" rel="stylesheet" type="text/css"/>
</head>
  <body class="calibre">
<h2 class="p-author" id="calibre_pb_0"><span id="anchor1" class="calibre1"></span>Mág Bertalan<a id="anchor2" class="calibre1"></a><a id="anchor3" class="calibre1"></a></h2>
<p class="p-title"><span id="anchor4" class="calibre1"></span>Nyomon </p>
<p class="p-title">a Mág-csoport</p>
```
Can it be caused by the internal links (actually unused as I removed the references from the TOC).
Style.css of the styles mention above:
```
.calibre {
    display: block;
    font-size: 1em;
    line-height: 1.2;
    margin: 0 5pt;
    padding: 0
    }
.calibre1 {
    line-height: 1.2;
    margin: 0;
    padding: 0
    }

```.p-title {
    display: block;
    font-family: Liberation Sans, sans-serif;
    font-size: 1.5em;
    font-weight: bold;
    line-height: 1.2;
    text-align: center;
    text-indent: 0.499cm;
    margin: 0.423cm 0 0.212cm;
    padding: 0
    }

Is there sg. koreader doesn't support?

**Comment by frankyifei** [comment]
can you uploade your epub?

**Comment by Ebrehem** [comment]
The original book is under copyright, though I converted it from a doc I found somewhere. Now I had some time to create a book with the same formatting (strange thing is the outcome is a bit different).

The book: 
[Title - Author.zip](https://github.com/koreader/koreader/files/139532/Title.-.Author.zip)

Please find below the pages in calibre viewer (close to the view in kobo stock reader):
![page1calibre](https://cloud.githubusercontent.com/assets/8835359/13201895/e786e4ea-d884-11e5-8799-7cdf43285684.jpg)
![page2calibre](https://cloud.githubusercontent.com/assets/8835359/13201894/e786c33e-d884-11e5-80bd-e1e49661020e.jpg)
![page3calibre](https://cloud.githubusercontent.com/assets/8835359/13201896/e7877266-d884-11e5-982a-dffdf199456f.jpg)

And the same pages in koreader (page 2 is identical, so I skipped it):
![page1koreader](https://cloud.githubusercontent.com/assets/8835359/13201902/06c6e918-d885-11e5-9ed4-8fab96ffe48c.png)
![page3koreader](https://cloud.githubusercontent.com/assets/8835359/13201903/06df1dee-d885-11e5-88e8-14ae7b2f3d6a.png)

And the above mentioned different outcome in the first page of the original book, also Author is justified left.
![page1origbookkoreader](https://cloud.githubusercontent.com/assets/8835359/13201906/3b848c8c-d885-11e5-9757-b6f5b7c6816a.png)

**Comment by frankyifei** [comment]
There is a bug in Cre, if you put a blank <span></span> or <span> </span> in front of another <span> , then the line will be left justified.

**Comment by Ebrehem** [comment]
Thank you, it can be easily corrected in the book. Is it responsible also for the spacing issues in the normal text? (See in the third pages above, first line of paragraphs should be indented, and below the chapter title ("heading 1") there should be blank space of 1-2 lines).

**Comment by frankyifei** [comment]
Also CRE does not support length as cm. it only support px, em, %
I think the reason is that it can not determine the actual size of the device

**Comment by Ebrehem** [comment]
Thank you, I assumed calibre converts them to em by default and omitted to check it.

**Comment by frankyifei** [comment]
I just worked out a fix for the blank`<span>` bug. But I don't know if this will change the formatting of something else.
