### ISSUE TITLE
Intel Android build?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1815]
Hi

It would be great if we  can get x86 builds for Android. It does not work on my intel tablet, so I assume it is an arch issue.

**Comment by houqp** [comment]
Yeah, it's the current android build is only for ARM cpus.

**Comment by fikr4n** [comment]
Is there a way to make an intel version?

**Comment by houqp** [comment]
I don't anyone is active working on it. Patch welcome :)

**Comment by Eduardomb22** [comment]
Still doesn´t have an intel build...right?

**Comment by houqp** [comment]
Yes, I don't anyone is actively working on this one.

**Comment by Frenzie** [comment]
Here's the first x86 Android build of KOReader (afaik). It works fine in the x86 Android emulator, which should make @mwoz123 very happy. It tells me it's good, because the emulator would complain about incompatible ARM stuff if if weren't.

[koreader-android-i686-linux-android-v2015.11-1335-gefd0d4f0.apk.zip](https://github.com/koreader/koreader/files/1383239/koreader-android-i686-linux-android-v2015.11-1335-gefd0d4f0.apk.zip)

There's a downer though: on my Zenfone 2 I'm getting a pretty funny error message.
```
10-13 17:42:00.300  9477  9492 I KOReader: try to load module libs/libkoreader-lfs.so
10-13 17:42:00.320  9477  9492 I KOReader: error: [string "dl.lua"]:38: error opening /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so: dlopen failed: can't find ARM symbol
10-13 17:42:00.320  9477  9492 I KOReader: try to load module /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
10-13 17:42:00.320  9477  9492 I KOReader: error: [string "dl.lua"]:92: could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
10-13 17:42:00.330  9477  9492 E luajit-launcher: Failed to run script: error loading module 'libs/libkoreader-lfs' from file 'libs/libkoreader-lfs.so':
10-13 17:42:00.330  9477  9492 E luajit-launcher: 	dlopen failed: library "libs/libkoreader-lfs.so" not found
10-13 17:42:00.330  9477  9492 V threaded_app: android_app_destroy!
```

Can't find ARM symbol? No kidding! I'd be interested to hear if it works on your tablet, @gerroon @latepaul.

Anyway, so it's not 100% there yet but it's pretty close.

**Comment by gerroon** [comment]
@Frenzie 

Thanks for it man, you guys rock. I am going to try it on my x86 device tonight.

**Comment by gerroon** [comment]
It works!  

For now main issue I seemed to have that it was not doing the full screen thing fully, I still had that bottom android buttons.

**Comment by Frenzie** [comment]
Thanks for testing! :)

I don't really know the deal with all that fullscreen stuff. There are values to play around with here.

https://github.com/koreader/android-luajit-launcher/commit/ca591eb9cfbf689792d4d545a5a18910d4202a4b claims to hide the navigation bar.

But clearly it's there:
https://github.com/koreader/koreader/pull/3353#issuecomment-336542601

I'm not really a fan of hiding such an important thing by default, but I just noticed the statusbar hides itself if you perform an action like going to the task switcher and then going back. So I'm guessing all that's needed is to call it a touch later or some such. Unless related to how they keep changing these freaking things around over at Google.

But if we want fullscreen to be the default then it should probably be fixed up by someone and @mwoz123 's fullscreen toggle in the Screen settings menu should do undo it instead.

**Comment by Frenzie** [comment]
@gerroon Fixed by @chrox in #3357.

**Comment by chrox** [comment]
> I'm not really a fan of hiding such an important thing by default, but I just noticed the statusbar hides ...

On real devices the system will provide a convenient way to show/dismiss the nav bar thus showing koreader in full screen mode by default is fine considering almost all reading app use this "immersive full-screen" mode.

**Comment by Frenzie** [comment]
Yeah, it looks like you can swipe up at the bottom and of course you can also swipe down at the top.

Btw do you know why my Zenfone 2 incorrectly seems to think my x86 build has arm libs in it? Something to do with where the 7z file gets extracted to perhaps?

**Comment by chrox** [comment]
Is there any log? The path for the 7z extraction is arch-neutral and the so libraries in the extraction are all loaded by our own dl, so if all libraries are built with x86 arch it should work fine. Did you mean the 7z utility library cannot be loaded so that it failed in the extraction process?

**Comment by Frenzie** [comment]
No, that part is perfectly fine. See https://github.com/koreader/koreader/issues/1815#issuecomment-336499485

> 10-13 17:42:00.320  9477  9492 I KOReader: error: [string "dl.lua"]:38: error opening /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so: dlopen failed: can't find ARM symbol

When I checked it in Native Libs Monitor it also incorrectly claimed that all the libs are arm. (After uninstalling, reloading, etc.)

But today it seems to think it's x86. Maybe it was some weird Android cache issue, although it's still failing in weird ways:
```
10-14 18:22:46.588  5377  5391 I KOReader: try to load module common/serialize.so
10-14 18:22:46.588  5377  5391 I KOReader: error: [string "dl.lua"]:38: error opening /data/user/0/org.koreader.launcher/files/common/serialize.so: dlopen failed: library "libluacompat52.so" not found
10-14 18:22:46.588  5377  5391 E luajit-launcher: Failed to run script: error loading module 'serialize' from file 'common/serialize.so':
10-14 18:22:46.588  5377  5391 E luajit-launcher: 	dlopen failed: library "libluacompat52.so" not found
10-14 18:22:46.588  5377  5391 V threaded_app: android_app_destroy!
```

Anyway, I was just hoping you might already know something about it. I'll just investigate it myself. I have the device, after all. It's just that I figured with everything working perfectly fine in the x86 emulator it'd also work on my phone, but due to its ARM compatibility layer it's somehow still refusing to.

**Comment by Frenzie** [comment]
I've attached a new x86 build with the fullscreen fix and DjVu support included.

[koreader-android-i686-linux-android-v2015.11-1343-g74242025.apk.zip](https://github.com/koreader/koreader/files/1384948/koreader-android-i686-linux-android-v2015.11-1343-g74242025.apk.zip)

**Comment by latepaul** [comment]
Sorry not to have replied earlier. I tried the first build and it worked OK. Will try the latest one when I get a chance. Cheers

**Comment by Frenzie** [comment]
With #3384 as the final piece we'll now have Android x86 nightlies.

First successful build log here: https://gitlab.com/koreader/nightly-builds/-/jobs/37044757

Build itself also attached here for convenience.
[koreader-android-i686-linux-android-v2015.11-1358-ge0bc0a1.apk.zip](https://github.com/koreader/koreader/files/1403250/koreader-android-i686-linux-android-v2015.11-1358-ge0bc0a1.apk.zip)

**Comment by Frenzie** [comment]
Apologies, there's actually some stuff I'd overlooked in the nightly builds process, such as `arm` here: https://github.com/koreader/koreader-misc/blob/9291b7925e8e96003039d1c8520ac49db54302fe/nightswatcher/nightswatcher.py#L45

It should suffice to change it to `(arm|i686)` but it means I'll have to update the Docker image.

The signing is also important to distinguish official nightlies from other builds: https://github.com/koreader/koreader-misc/blob/9291b7925e8e96003039d1c8520ac49db54302fe/nightswatcher/nightswatcher.py#L166 That one should be changed to something more inclusive as well, like `if build['name'].startswith('build_android'):`

So I'm afraid there'll probably be at least a few more days, although I'm not entirely sure from my two-minute check why they haven't simply shown up improperly signed. But in the meantime you can grab the nightlies by downloading the artifacts from https://gitlab.com/koreader/nightly-builds/-/jobs/
