### ISSUE TITLE
koreader-nightly-20160214 fails to start on Arm Android 

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#1816]
koreader-nightly-20160214 fails on Android
koreader-nightly-20151213 works fine

I/luajit-launcher(18561): Application data directory /data/data/org.koreader.launcher/files
I/luajit-launcher(18561): Application library directory /data/app/org.koreader.launcher-2/lib/arm
I/luajit-launcher(18561): Screen size 1600x2560
I/luajit-launcher(18561): Screen brightness 42
I/luajit-launcher(18561): Check file in asset module: koreader-gd9b55af.7z
I/luajit-launcher(18561): Skip installation for revision gd9b55af
I/luajit-launcher(18561): Change directory to /data/data/org.koreader.launcher/files
I/luajit-launcher(18561): intent file path
I/luajit-launcher(18561): run command chmod 755 ./sdcv
I/luajit-launcher(18561): try to load module libs/libkoreader-lfs.so
I/luajit-launcher(18561): ffi.load SDL2
I/luajit-launcher(18561): ffi.load SDL
W/luajit-launcher(18561): cannot blit: no window
I/luajit-launcher(18561): # initializing for device Android
I/luajit-launcher(18561): # framebuffer resolution: {
I/luajit-launcher(18561):       ["h"] = 2560,
I/luajit-launcher(18561):       ["w"] = 1600
I/luajit-launcher(18561): }
I/luajit-launcher(18561): ffi.load libs/libfreetype.so.6
I/luajit-launcher(18561): try to load module common/serialize.so
W/linker  (18561): libluacompat52.so: unused DT entry: type 0xf arg 0x455
I/luajit-launcher(18561): ffi.load libs/libmupdf.so
E/luajit-launcher(18561): Failed to run script: ffi/mupdf.lua:21: dlopen failed: cannot locate symbol "fcrypt_decrypt" referenced by "libmupdf.so"...

**Comment by houqp** [comment]
hmm.... probably due to my recent refactors in koreader-base. I will dig into it since I am working on another android related issue.

**Comment by gerroon** [comment]
Thanks for the fix. Is it possible to get a new Android build with the fix?
