### ISSUE TITLE
Can the corner X tap area be increased in persistent.defaults.lua?

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1818]
[Today a mobileread user using the Kobo Mini asked how to close the status window, since the X doesn't work for him.](http://www.mobileread.com/forums/showthread.php?p=3261366#post3261366) I basically ignore the X for the dictionary, because I fail to tap it correctly quite consistently and tap somewhere outside the dictionary window to close it. 

Since the tap area's for the upper and lower menu's can be scaled, I wondered how this could be hacked into the X area as well. Could anybody point me to the relevant code?

**Comment by houqp** [comment]
The widget for close button is `frontend/ui/widget/closebutton.lua`. You can try increase the font size there to see if it helps. Current value is `32`.

**Comment by Markismus** [comment]
Thanks. Will try.

**Comment by KenMaltby** [comment]
I tried 52 and the **X** looks much the same, it does seem a little easier to activate.

**Comment by houqp** [comment]
@Markismus can you try the latest build to see if the close button is more responsive now? I increased the tapping area in the recent commit.

**Comment by KenMaltby** [comment]
I am using 42 there now and at line 92, in menu.lua

**Comment by houqp** [comment]
With the changes I made, the default font size `32` should hopefully be good enough. I am trying to get it to a work out of box state so there is no need for users to tweak the setting.

**Comment by KenMaltby** [comment]
Well gee..., if you are going to go and do a real, proper fix....

**Comment by Markismus** [comment]
Ah it's closed, so that why I couldn't find this issue anymore. Anyway, it seems a tad more responsive. After trying a bunch of times with words on different parts of the page, ---See log [here](https://gist.github.com/a1bd943004b308a2c60d)--- I found that in these three responses are as likely to happen: 
[1]  I get it to close at the first time, 
[2] I get it to close after tapping a bunch of times (up to 5),
[3] I don't get it to close, so I tap outside of the dictionary window, to close it in one tap.

**Comment by Markismus** [comment]
Previous post was for @houqp.

**Comment by houqp** [comment]
@Markismus that's a very old version, my change is introduced in https://github.com/koreader/koreader/commit/a99ab5a976b2c0549c2c40742f9b12f85ba356e2, can you give the latest build a try?

**Comment by Markismus** [comment]
Huh, odd. Since I downloaded that from the release page yesterday. Will try again.

**Comment by Markismus** [comment]
I can't download via OTA and the [releases](https://github.com/koreader/koreader/releases) still only have version 175 as the latest.

**Comment by Markismus** [comment]
Still the same bug with building a kobo release, too.

**Comment by KenMaltby** [comment]
I just download the appropriate .targz file directly from the OTA site, using myPC (usually: http://vislab.bjmu.edu.cn/apps/koreader/ota/)  I use "Save As" to shorten the file name and remove the "tar" from the extension, like this "koreader-kobo-v2015.11-251.gz".  Both WinRAR and 7-Zip can open .gz files.  (7-Zip also can save back to that [for making changes])

**Comment by Markismus** [comment]
That should have been a tar.gz-file, shouldn't it? It think you might have found the typo that killed OTA!

**Comment by Markismus** [comment]
Another oddness:
![screenshot from 2016-03-13 20-06-23](https://cloud.githubusercontent.com/assets/5269101/13730715/1e987092-e957-11e5-8e08-83456dc1406c.png)
My extraction app fileroller generates an error stating that it cannot make a hard link in this directory.

**Comment by KenMaltby** [comment]
Not really a typo, it was a work around, as I recall.

**Comment by Markismus** [comment]
On version 251-g511147a the x finally marks the spot! Seven direct closings out of seven tries!

**Comment by houqp** [comment]
Good to know my change worked :)

targz is introduced to workaround CDN caching issue, it's not a bug.
