### ISSUE TITLE
Bug: cannot OTA on kindle paperwhite 3

### ISSUE THREAD

**Issue by yasteora** [koreader/koreader#1821]
i set it from stable mode to develop mode. After download the 118 edition, that told me failed ,and deleted the temp file.

**Comment by chrox** [comment]
It works as expected on my Kindle Voyage and I just OTA updated it to v2015.11-129. Could you check your network connection and try it again?

**Comment by yasteora** [comment]
I have checked the network is connectioned.   I have removed the old folds, /koreader and /extensions/koreader  ,then mov the new edition folds to /.

**Comment by houqp** [comment]
I suggest we retry download on other servers automatically if we can't reach the default one.

**Comment by chrox** [comment]
Yes, a retry mechanism is always better for a network action.
