### ISSUE TITLE
Koreader consistently crashes when toggling the frontlight off

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1827]
Koreader version 2015.11-106-gd9b55af on Kobo Aura H2O.
Crash log:
```
./luajit: frontend/apps/reader/modules/readerfrontlight.lua:96: attempt to call method 'setText' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerfrontlight.lua:96: in function 'callback'
	frontend/ui/widget/button.lua:173: in function 'action'
	frontend/ui/uimanager.lua:353: in function '_checkTasks'
	frontend/ui/uimanager.lua:497: in function 'handleInput'
	frontend/ui/uimanager.lua:587: in function 'run'
	./reader.lua:147: in main chunk
	[C]: at 0x0000bed5
```

Oddly enough that line in the code hasn't changed for quite some time.

**Comment by houqp** [comment]
Likely an old bug exposed due to recent bug fixes in the scheduler like (https://github.com/koreader/koreader/issues/1796) :( I will take a look today.

**Comment by houqp** [comment]
My bad, it's actually caused by a recent refactor I did for InputDialog widget...

**Comment by Markismus** [comment]
@houqp How could I pull from your repo to test?
