### ISSUE TITLE
reader should only display status page after user finishes reading the last page

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#1831]
Right now, the status page will show up when a user turn to the last page. This prevents the user from reading the last page. Ideally, it should show up after the user hits a page turn on the last page.

To achieve this, we can emit a "end of book" event from readerpaging module and catch it in readerstatus module and display the status page accordingly.

**Comment by Markismus** [comment]
Yes. Indeed. With the problematic escape X from the status page, this bug prevented me from reading the last 7 lines of a novel for 20 seconds. Rather wonderfully annoying.
