### ISSUE TITLE
"Fulltext search" dialog does not appear in nightly-20160216

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1834]
Device: Kobo Glo HD.
"Fulltext search" and "Dictionary lookup" dialogs don't appear when using nightly-20160216 and 2015-11-144-gd4256e1 (2016-02-18 18:01 snapshot)
Regards.

**Comment by houqp** [comment]
My bad, I will fix it tonight

**Comment by djalma2k** [comment]
Nice, Thanks for your hard work! :)
