### ISSUE TITLE
[New Feature Proposal] Plan to add a 'Rename' function in FileManager

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1838]
* KOReader version: git commit 180b82315728af97cbd8f420a70928824623eb02 or higher
* Device: *

#### Issue
I plan to add a 'Rename' function in FileManager, to rename a file or folder with linux mv binary.

#### Steps to reproduce
To achieve this goal, I will need to,
1. Add a basename function in koreader-base/ffi/util.lua, which also impacts koreader-base/ffi-cdecl/posix_decl.c and koreader-base/posix_h.lua.
2. Change koreader/frontend/apps/filemanager/filemanager.lua to add one more button (Rename) in file_chooser:onFileHold(file) function, and implement its function by using InputDialog with OK and Cancel buttons.

I have partially finished @ https://github.com/hzj-jie/koreader-base and https://github.com/hzj-jie/koreader. But instead of pulling two requests directly, any suggestion is welcome.

**Comment by houqp** [comment]
@Hzj-jie thanks a lot for the help! Your patch looks good to me :+1:  Feel free to send us PRs. One thing I want to point out is you should check to see if the file is a document, if it is, we should also migrate the history files too. There are two types of history files you need to migrate, one is the `.sdr` directory (the new config), the other one is the file in `history` directory (the legacy config). I want kill the legacy config at some point in the feature.

You can also always send PRs for review even though it's still work in progress, just tag `[WIP]` in the title so we know not to merge it until it's ready.

**Comment by Hzj-jie** [comment]
Ah, yes, I forgot.
If we enable rename and move for a folder, but the history files are legacy, we will lost them. Is it acceptable?

**Comment by houqp** [comment]
Unfortunately, we haven't got rid of the legacy document setting yet. In `docsettings.lua`, we still do a dual write to the new and legacy format in the `flush` method. So unless you want to lead the effort to clean up the legacy config files, we will need to keep the legacy format too.

**Comment by Hzj-jie** [comment]
Just a draft idea, how about executing a merging logic to merge and delete legacy history files to new format when we start koreader? Then we won't need to take care of legacy files in the following logic.

**Comment by houqp** [comment]
sounds good to me. If the merging logic turns out to be too complicated, we can just check the last modified time and discard the older one.
