### ISSUE TITLE
[New Feature Proposal] Pinch to zoom images in epub files

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1839]
- KOReader version: v2015.11-150-g180b823 and previous versions.
- Device: Kobo Glo HD
#### Issue

It would be nice to implement this feature for epub images because sometimes you find images in the epub files like maps and you find that you need a feature like this for the map to be useful. 
Old Sony Prs-T3 has something like this:
http://postimg.org/image/ea4qcjhvn/

Regards.

[O/T]: In zoom mode the sony device doesn't seems to use "dithering" with the images...

**Comment by KenMaltby** [comment]
An ability to free zoom would be a great feature for images and nontext features including scanned documents, pdfs as well, but until that becomes available, here is something I sometimes do to have a reference image available while reading.  I pull a copy of the map/chart image file and size/scale it for my device, using Gimp2, then if I open it in KOReader it will be available in "History", where I can call it up quickly and then return to where I was in the book.

**Comment by djalma2k** [comment]
Yes, It could be a temporary solution, maybe with the correct script magnifying the images could be a good solution. But I wrote my previous post thinking that the "pinch 2 zoom" gesture is already implemented for pdf files (real zoom isn't currently and really implemented). And maybe could be easy (I really don't know :) ) implement a simple zoom feature.
The problem of doing what you do in a manual way is that some of the maps or images really "spoils" the future book contents and if you previously saw that images... bad business ( 4 example if you saw a victim killed by the killer at the beginning of the book, probably the book's atmosphere fall off a little bit... :/ )
On the other hand isn't the optimum solution for a novice in IT stuff ( 4 example, thinking in my mother :P who has koreader installed in her device).
Anyway, Kent Thanks for your help and ideas.
Regards.

**Comment by poire-z** [comment]
I think this could be closed thanks to ImageViewer with zoom implemented some months ago (#2519, #2522): hold on an image to display it in a Viewer, and there one can pan & zoom.
(Doing it inline in crengine is probably impossible, and not really needed.)

**Comment by Frenzie** [comment]
Good point. Closing now.
