### ISSUE TITLE
Change Wikipedia Language

### ISSUE THREAD

**Issue by nachox77** [koreader/koreader#1844]
* Device: Kindle PW3

#### Issue
Hello.

I was wondering if is possible to change the lenguage of the wikipedia search. Instead of searching in wikipedia in English I want to search in Spanish.

Thanks in advance

**Comment by KenMaltby** [comment]
The MR thread: http://www.mobileread.com/forums/showthread.php?t=271101

**Comment by Frenzie** [comment]
Similar to #1775 this could potentially be automated, presumably based on something like `self.ui.document:getProps().language` but I only glanced at it.

**Comment by Immick** [comment]
Guys, I'm sorry is there a ready patch that solver the problem?

Thank you!

**Comment by Frenzie** [comment]
Not as far as I know.

**Comment by Immick** [comment]
**Frenzie**, too bad :( I thought it's not so hard to get the idea from #1775 of determining document language...
