### ISSUE TITLE
Keyboard visible on file explorer screen, unable to properly navigate

### ISSUE THREAD

**Issue by zenterprises** [koreader/koreader#1846]
* KOReader version: v2015.11-118-ge71863a
* Device: kobo aura h2o

#### Issue

Navigation freezes, unable to return to normal operation

Keyboard is responsive, but unable to navigate anywhere else.

#### Steps to reproduce

Navigate to advanced settings,

attempt to edit default text size or default text size options

Exit, keyboard will be visible on the file explorer screen

Unable to navigate from this point.

Reset by removing sd card or plugging usb cable into PC.

**Comment by chrox** [comment]
Fixed in #1841. Please try the latest nightly build on OTA server.
