### ISSUE TITLE
[Kindle] Difficult to hide menu

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1850]
* KOReader version: v2015.11.118-ge71863a
* Device: Kindle Paperwhite 3

#### Issue
I found it difficult to hide the menu by tapping the displayed book area right below.

#### Steps to reproduce
1. Open an pdf
2. Tap top area to open menu
3. At any setting page, tap **right** below the menu, expect menu to be hidden, and observe that it is not.
4. tap a bit more below, observe that the menu is hidden

**Comment by houqp** [comment]
Confirmed, looks like a bug in the UI framework.
