### ISSUE TITLE
[Feature request] Show current page at "go to" input

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1851]
The title pretty says it all. 

Often I open "Go to" only to realize that I need to know what page I am currently on. :)

Moreover, some keys of the keyboard on KPW3 have parts of their border "covered" by the images (I'm guessing they are images..). i.e. shift key, backspace key, newline key, and the global like thing key.

**Comment by houqp** [comment]
Hi @SsnL , can you do a screenshot for the keyboard issue? A screenshot can be created with diagonal swipe from top left of the corner to the bottom right.
