### ISSUE TITLE
Crash, when opening fb2 (probably other formats) with a lot of text on Kindle PW2

### ISSUE THREAD

**Issue by pavlukivan** [koreader/koreader#1852]
* KOReader version: 2015.11 and newer
* Device: Kindle PW2

#### Issue
Crash, when opening files with a lot of text.
(Segmentation fault)

All is fine on some old version (It started, when I upgraded to 20160216, I tried downgrading to 2015.11 but nothing works)
#### Steps to reproduce
For example, try to open that fb2 file: [crash.zip](https://github.com/koreader/koreader/files/147704/crash.zip)

**Comment by houqp** [comment]
I am not able to reproduce this with emulator and my kobo. Are you getting this segmentation fault for most of the big fb2 books or just this one? I wonder if it also has something to do with your book settings.

**Comment by pavlukivan** [comment]
I have only one really big book, crash is only on books with much text. That book is containing all the books of The Elder Scrolls III-V...

**Comment by pavlukivan** [comment]
Also I can run strace

**Comment by houqp** [comment]
A strace wouldn't hurt ;) Also does the crash only happen on a specific page or any page?

**Comment by frankyifei** [comment]
I dont know how to debug on real device

**Comment by frankyifei** [comment]
fixed

**Comment by pavlukivan** [comment]
The crash is when opening that document

**Comment by houqp** [comment]
@pavlukivan , have you tried the latest release? @frankyifei fixed a bug in one of our rendering engine that might be related to your crash.

**Comment by burunduk** [comment]
I have same bug on kindle touch.
Size of fb2 files >  1.5~2 MB.

**Comment by houqp** [comment]
@burunduk , what version are you using?

**Comment by burunduk** [comment]
2015.11-219, -175 and -118

**Comment by frankyifei** [comment]
@burunduk,can you upload your fb2 file? 
Actually I do not quite understand fb2 file format. The last fix is based on test of pavlukivan's file. That file will crash at lvtextfm.cpp in function processParagraph().  In that case, the file size does not matter. I have several epubs >10mb on my kpw and Koreader can still open them.

**Comment by burunduk** [comment]
[book fb2](http://www.e-reading.club/download.php?book=27568)
ebup - opening.

**Comment by frankyifei** [comment]
@burunduk , I can open your book on my kpw. so it's the end line of this book caused your problem?

**Comment by burunduk** [comment]
Yes.

**Comment by frankyifei** [comment]
@burunduk ,I can't reproduce this bug. your book works on emulator and my kindle.

**Comment by burunduk** [comment]
I can create on my kindle any debug log with crash infotmation?

**Comment by houqp** [comment]
@burunduk, when koreader crashes, it will generate a crash.log under `koreader` folder. Can you paste the content of that file here? Also it wouldn't hurt if you paste the book settings too :)

**Comment by GeneralFailer** [comment]
The crash.log is empty for me.

**Comment by GeneralFailer** [comment]
Dunno if it can help, but it seems like the last version to produce a non-empty crash.log for me is koreader-nightly-20160216.

`./luajit: frontend/ui/uimanager.lua:291: attempt to index local 'self' (a nil value)
stack traceback:
	frontend/ui/uimanager.lua:291: in function 'quit'
	frontend/apps/reader/readerui.lua:353: in function 'action'
	frontend/ui/uimanager.lua:353: in function '_checkTasks'
	frontend/ui/uimanager.lua:497: in function 'handleInput'
	frontend/ui/uimanager.lua:587: in function 'run'
	./reader.lua:151: in main chunk
	[C]: at 0x0000becd`

**Comment by houqp** [comment]
@GeneralFailer I noticed a bug that prevents some of the reader error log from writing into `crash.log`. Either one of the commit in https://github.com/koreader/koreader/pull/1900 should fix the issue. Could you give it a try?

**Comment by GeneralFailer** [comment]
@houqp Generated logs are still empty for me.

**Comment by burunduk** [comment]
@houqp, on v2015.11-267 i have some log:
`FATAL ERROR #111: restoreFromCache() failed for chunk`
I try clean cach folder. May be I have other bug. Not for this issue.

**Comment by pavlukivan** [comment]
Everything works on new version

**Comment by GeneralFailer** [comment]
The new nightly build finally started generating logs.

> [!] doShowReader coroutine crashed:
./ffi/mupdf.lua:61: cannot open page #1:  (0)
stack traceback:
	./ffi/mupdf.lua:61: in function 'merror'
	./ffi/mupdf.lua:191: in function 'openPage'
	frontend/document/document.lua:139: in function 'getNativePageDimensions'
	frontend/apps/reader/modules/readerzooming.lua:213: in function 'getZoom'
	frontend/apps/reader/modules/readerzooming.lua:279: in function 'setZoom'
	frontend/apps/reader/modules/readerzooming.lua:162: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:71: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'handleEvent'
	frontend/apps/reader/modules/readerview.lua:569: in function 'onSetScreenMode'
	frontend/apps/reader/modules/readerview.lua:612: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:71: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'handleEvent'
	frontend/apps/reader/readerui.lua:318: in function 'init'
	frontend/ui/widget/widget.lua:39: in function 'new'
	frontend/apps/reader/readerui.lua:383: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:345: in function <frontend/apps/reader/readerui.lua:344>

**Comment by GeneralFailer** [comment]
Is anybody planning to look into this?

**Comment by houqp** [comment]
You need to reopen the issue so it's back in the milestone queue ;) I will try again to see if I can reproduce with the latest code.

**Comment by houqp** [comment]
@GeneralFailer I am still not able to reproduce the crash. Is the crash from `crash.zip`? If so, can you upload the book settings here?

**Comment by GeneralFailer** [comment]
I don't think I have the necessary privileges.

Yes it is. The generated `crash.sdr` is empty.

**Comment by houqp** [comment]
@GeneralFailer what device are you using? Do you have ssh access?

**Comment by GeneralFailer** [comment]
@houqp Kindle Touch. No, do I need to?

**Comment by houqp** [comment]
It will be easier for you to collect debug information. Can you add a `print('!!!!!!!!!!!', number)` statement at `ffi/mupdf.lua` https://github.com/koreader/koreader-base/blob/master/ffi/mupdf.lua#L184 right before the `local mupdf_page = {` statement?  After that, you should be able to see the print output in the crash.log.

I wonder if it's feeding a valid page number.

**Comment by GeneralFailer** [comment]
@houqp
> [!] doShowReader coroutine crashed:
./ffi/mupdf.lua:61: cannot open page #1:  (0)
stack traceback:
	./ffi/mupdf.lua:61: in function 'merror'
	./ffi/mupdf.lua:192: in function 'openPage'
	frontend/document/document.lua:139: in function 'getNativePageDimensions'
	frontend/apps/reader/modules/readerzooming.lua:213: in function 'getZoom'
	frontend/apps/reader/modules/readerzooming.lua:279: in function 'setZoom'
	frontend/apps/reader/modules/readerzooming.lua:162: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:71: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'handleEvent'
	frontend/apps/reader/modules/readerview.lua:599: in function 'onSetScreenMode'
	frontend/apps/reader/modules/readerview.lua:642: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:71: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:83: in function 'handleEvent'
	frontend/apps/reader/readerui.lua:318: in function 'init'
	frontend/ui/widget/widget.lua:39: in function 'new'
	frontend/apps/reader/readerui.lua:383: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:345: in function <frontend/apps/reader/readerui.lua:344>!!!!!!!!!!!	1

**Comment by houqp** [comment]
I can't reproduce the crash, but the first page in my emulator is displayed as a blank page. So the JPEG is not rendered probably. This might be related to the crash you are seeing.

**Comment by houqp** [comment]
@GeneralFailer oh, wait, it's a fb2 file, it should not be using mupdf to render it. Can you rename the file to `crash.fb2.zip` or unzip it to extract `crash.fb2` and try again?

**Comment by GeneralFailer** [comment]
@houqp Right, I thought something along those lines. It works fine with the full extension.

**Comment by GeneralFailer** [comment]
Also in case this could be somehow related, I've been having an issue of the screen only refreshing in the titlebar's space when exiting KOReader similarly to #1924 for a while now.

**Comment by houqp** [comment]
@GeneralFailer that's an issue with native framework "integration". Have you tried the workaround @NiLuJe mentioned over that issue? Let's move the discussion to that issue instead since I am pretty it's not related to this one ;)
