### ISSUE TITLE
[Kindle] can't go back from a link in pdf

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1858]
* KOReader version: latest nightly, koreader-kindle-arm-linux-gnueabi-v2015.11-175-g7b11491
* Device: Kindle PW3

#### Issue
In pdf, go back from a link is not working.

#### Steps to reproduce
1. open a pdf
2. click a link that is not on the first page
3. menu->follow link->go back
4. expect to go back to previous page, actually end up at first page

The "swipe to go back" option is not working. After clicking a link, swiping backward now flips pages back, and swiping forward now redirects to first page.

**Comment by houqp** [comment]
Hmm... I don't have a pdf with links. Tired to reproduce it with epub, but failed. Could you provide a sample pdf? Looks like it's should be something easy to fix.

**Comment by SsnL** [comment]
Sure. Here's the one where I encountered bugs:
[Adaptively Scaling The Metropolis Algorithm Using Expected Squared Jumped Distance.pdf](https://github.com/koreader/koreader/files/159251/Adaptively.Scaling.The.Metropolis.Algorithm.Using.Expected.Squared.Jumped.Distance.pdf)

Try the link in section 1.1's first line with text "Metropolis, Rosenbluth, Rosenbluth and Teller (1953)".

It seems that this bug doesn't occur for all links. But it definitely does for this one.

**Comment by houqp** [comment]
@SsnL , I cannot reproduce the issue. Both the `go back` item and swipe back works as expected for me. The link `Metropolis, Rosenbluth, Rosenbluth and Teller (1953)` in section 1.1 is located in the first page, so when you swipe back, it will jump back to the first page, which is expected. I tried some links in other pages and was able to swipe back to the correct page. Do you have a better example to reproduce the bug?

**Comment by SsnL** [comment]
Uhh, it occurs for me in reflow mode, if that's helpful at all. Sorry I don't have a better example at hand. But I will report back if I see one.

**Comment by houqp** [comment]
Ha i see. It makes sense now. The jump back feature does not work every well with reflow mode right now. Mainly because when page 1 is reflowed into multiple pages, those pages are still considered page 1. So when you jump page, it goes straight back to top of page 1.

This is indeed a bug. We should restore all context during a jump back operation.
