### ISSUE TITLE
FR: File Manager item list with smaller text and more lines

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1865]
* KOReader version: <= v2015.11-194
* Device: Kobo AuraHD

#### Issue
When I reduce cfont to 16 in the "menu.lua" widget, I get more of the book file name showing, good, but I don't see how to get the spacing of the lines tighter and have more lines per menu page.
#### Steps to reproduce
Make change to frontend/ui/widget/menu.lua

With ereaders evolving to higher resolutions, smaller text is more readable.  If you include all the information, to make browsing effective, in the file name, they can get quite long.  Using a smaller text lets me see most or all of the file name.  While I wouldn't want the lines too close together, there looks to be room for more lines, on the page.

(I would post a screenshot but what used to work, crashes me to KSM.)

**Comment by NiLuJe** [comment]
FWIW, can't reproduce the crashing issue on screenshot on an H2O (with a diagonal swipe).

**Comment by KenMaltby** [comment]
I shouldn't have mentioned it, I am sure the screenshot issue is due to something I did, while updating.

**Comment by houqp** [comment]
The cfont stuff in `menu.lua` is an internal state that's not supposed to be a user configurable variable. So simply changing it won't work very well ;)

What do you want to achieve here? Maybe we can instead convert your use case into a feature request. If I understand it correctly, you want more lines and each line to display more characters? If so, maybe we can introduce a compact view or something.

**Comment by AlanSP1** [comment]
I also have some books with very long titles (some over 256 chars). So, having more (or all) of the title can help know what book I'm looking at.

And @KenMaltby would like (me also) more books per file manager page.

If we could somehow control number of books per page in file manager and font size of book title would be great addition.

**Comment by KenMaltby** [comment]
So far, having the item cfont set to 16 has been working well, 
![cfont_16](https://cloud.githubusercontent.com/assets/14007369/13497601/e479cd18-e11b-11e5-8fc8-005ecf36d523.JPG) 
(Sorry about the flash)

As you can see there is a lot of space between lines.  I was thinking that maybe half the space might still leave the lines pokeable.

**Comment by houqp** [comment]
Yeah, agree. @chrox is working on the redesign of filemanger, a.k.a. "koreader home". That should make this problem go away. 

For now, you can try also manually adjust the hardcoded item height in menu.lua. Around line 374, there is a ` h = Screen:scaleBySize(46), -- hardcoded for now ` :)

**Comment by KenMaltby** [comment]
Ah... thanks, I would never have found it.  I don't see it as a problem, just an opportunity to take advantage of the HD screen.  Let me give that a few tries and then I can close this, to keep the number of open issues down. Thanks All.

**Comment by KenMaltby** [comment]
I changed line 373 to (28) and it looks great with the (cfont) at 16 , looks and works the same in the History menu. (That Fantasy submenu went from 35 to 21 pages) (24 items per page) Would I be out of line if I offered this approach to "tshering" over at MR as something for his "Modifications for bad eyes" thread?  Bigger should work just like smaller does, now that the placement of the lines can be adjusted.

**Comment by houqp** [comment]
@KenMaltby sure! Feel free to share the hack :)

**Comment by Markismus** [comment]
Wouldn't it be nice to have a menu or defaults.lua entry to tweak this?

**Comment by AlanSP1** [comment]
Yes, that would be very helpful if we could control this two variables in defualts.lua, it would make things much easier to use than editing hardcoded ones.

**Comment by KenMaltby** [comment]
The way it impacts me is, as something I need to remember to apply when updating KOReader.  Having then added to defaults/persistent defaults would be a boon.

**Comment by houqp** [comment]
If we are going to make it configurable, I would want it to be in reader setting. defaults.lua is already a mess right now  and it's better to avoid adding more stuff to it. We need to clean that up in the future.

**Comment by AlanSP1** [comment]
Actually, having it in reader settings is even better, because you don't need editor, you can do that from koreader's own interface, which is easier.

**Comment by KenMaltby** [comment]
While I am somewhat uncomfortable suggesting how things should be done, to those who would be the ones actually doing them. ( Perhaps I am channeling my old Plt Sgt days?)  I think it would a good part of the cleanup to have the File Management settings accessible from the File Manager Menus and the Reader settings from the menu you get when reading.  For instance it seems more intuitive, to me, if the OTA and Calibre wireless connection functions were in the File Manager, instead of the Reader menus.  

Perhaps; there could be separate "Advanced Settings" with only those settings listed that apply to the functional area.  An Advanced Settings for the File manager, an Advanced Settings for the cr3 Reader and an Advanced Settings for the PDF reader.  Called from their respective menus. That might sort them out better, as well. 

Luck;
Ken

**Comment by chrox** [comment]
@KenMaltby Yes, all the suggestions are great enhancements for user experience. Could you open new issues for these enhancements so that we can add them in the todo list of the next stable release.

**Comment by KenMaltby** [comment]
Of course.
