### ISSUE TITLE
koreader crashes on Kindle DXG

### ISSUE THREAD

**Issue by elektronaut0815** [koreader/koreader#1868]
- KOReader version:  v2015.11-214-g58e7103 (upload date 2016-Mar-03 02:18:36)
- Device: Kindle DXG
#### Issue

KOReader won't start, it immediately crashes.

```
./luajit: frontend/ui/uimanager.lua:312: attempt to index local 'self' (a nil value)
stack traceback:
    frontend/ui/uimanager.lua:312: in function 'quit'
    frontend/apps/reader/readerui.lua:353: in function 'action'
    frontend/ui/uimanager.lua:374: in function '_checkTasks'
    frontend/ui/uimanager.lua:518: in function 'handleInput'
    frontend/ui/uimanager.lua:608: in function 'run'
    ./reader.lua:164: in main chunk
    [C]: at 0x0001459c
```
#### Steps to reproduce

Simply start KOReader from KUAL.

**Comment by NiLuJe** [comment]
Is that when opening a book directly or the File Manager?

Opening a CRe-handled book currently most likely crashes in fun and interesting ways in my builds, for reasons beyond my comprehension (and that I couldn't manage to debug).

**Comment by houqp** [comment]
Looks like it crashed in readerui, so it's trying to open a book. @elektronaut0815 , did you get the release directly from our release page on github? Our official kindle release only works on touch based kindle devices right now. For k3/dxg/k4/k2, you will need to compile your own version with kindle-legacy as the target.

If you don't know how to setup cross compile environment, you can take https://github.com/koreader/virdevenv/tree/master/vm/ubuntu a try. Feel free to ping us if you got stuck at any step ;)

**Comment by elektronaut0815** [comment]
Correct, it crashed directly after trying to open a book. 
Concerning compatibility with DXG: [The first build here](http://www.mobileread.com/forums/showpost.php?p=2658945) should work with DXG according to NiLuJe.

**Comment by houqp** [comment]
Oh, I see. NiLuJe's build should work then. I thought you downloaded it from github instead. Does the crash happen to any book?

**Comment by elektronaut0815** [comment]
Yes, any book.

**Comment by NiLuJe** [comment]
For curiosity's sake, does it happen with books handled by another engine than CRe (pdf or djvu for instance)?

**Comment by elektronaut0815** [comment]
Those books were all Epub's, I just tried a PDF now, which is displayed without crash.

**Comment by frankyifei** [comment]
@NiLuJe , I tested your build on my kpw1, it crashes on epubs and only works for pdf.

**Comment by NiLuJe** [comment]
Yeah, that's why I was asking, that might just be a side-effect of the CRe
crash... Guess I'll see how the next stable linaro release behave, and/or
try a gcc 4.9 build...

**Comment by NiLuJe** [comment]
Okay, the just-release snapshots *should* now have a properly working CRe...

(Stupid ABI mismatch, I had some crap in my env...)

**Comment by elektronaut0815** [comment]
Still not working with current snapshot.

**Comment by NiLuJe** [comment]
Okay, so there's a definite issue somewhere in the codebase, and not only a silly mistake on my part, thanks :).

**Comment by houqp** [comment]
@elektronaut0815 are you still getting the same error? Fun fact, I tried a new kindle-legacy build with the latest master, EPUB is working fine for me, but now it says no engine found for PDFs... I will probably take a closer look at weekend to see what's actually happening.

**Comment by NiLuJe** [comment]
Okay on PDF & ePubs on a K4 over here.

**Comment by NiLuJe** [comment]
Okay also on a K3.

**Comment by NiLuJe** [comment]
... And okay also on a K2.

:?

**Comment by NiLuJe** [comment]
Even checked on a clean install to make sure, and, yep, works fine on my end... :?

**Comment by houqp** [comment]
After updated https://github.com/koreader/koxtoolchain to use @NiLuJe 's ct-ng kindle branch, everything is working again on my K3 now. @elektronaut0815 can you give @NiLuJe 's latest build a try?

PS: @NiLuJe, the kernel version you specified in the sample file does not exist in ct-ng. Did you do anything special to make ct-ng fetch your version? I ended up using 2_6_32 for kindle-legacy TC.

**Comment by NiLuJe** [comment]
That kernel version is in my kindle, branch, make sure you don't have an
older ct-ng version installed somewhere in your path ?
On Apr 18, 2016 10:43 AM, "Qingping Hou" <notifications@github.com> wrote:

After updated https://github.com/koreader/koxtoolchain to use @NiLuJe
<https://github.com/NiLuJe> 's ct-ng kindle branch, everything is working
again on my K3 now. @elektronaut0815 <https://github.com/elektronaut0815>
can you give @NiLuJe <https://github.com/NiLuJe> 's latest build a try?

PS: @NiLuJe <https://github.com/NiLuJe>, the kernel version you specified
in the sample file does not exist in ct-ng. Did you do anything special to
make ct-ng fetch your version? I ended up using 2_6_32 for kindle-legacy TC.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/koreader/koreader/issues/1868#issuecomment-211273977>

**Comment by NiLuJe** [comment]
... On the tip of the branch, that is, whereas your script is checking out
the latest tag ;).

**Comment by houqp** [comment]
haha, I am an idiot. Thanks for catching that, I forgot to change the commit hash ;)

**Comment by houqp** [comment]
@NiLuJe btw, which version of binutils should we use? linaro-2.24.0-2014.11-2?

**Comment by NiLuJe** [comment]
The latest when using gold, but with bfd we don't really care. That said,
it doesn't hurt to go with something up to date, so 2.26 (mainline) right
now ;).

**Comment by NiLuJe** [comment]
@houqp: Any particular reason for sticking w/ GCC 4.8? (If the idea is to avoid GCC 5, which is not such a crazy idea, GCC 4.9 is also a solid choice ;)).

Same question for glibc 2.11 in the Kobo TC?

**Comment by houqp** [comment]
I haven't finished up the kindle tc clean up yet. GCC 5 for some reason does not work for me. I need to dig further into it.

As for Kobo TC, I haven't started rebuilding it based on your sample yet ;)

**Comment by NiLuJe** [comment]
This should definitely be fixed by now :).
