### ISSUE TITLE
A reorganization of the "Advanced Settings/Defaults"  

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1870]
- KOReader version: All?
- Device:
#### Issue

The setting of "Advanced settings" could be less cluttered and more intuitive.

I think it would a good part of a cleanup to have the File Management settings accessible from the File Manager Menus and the Reader settings from the menu you get when reading.

Perhaps; there could be separate "Advanced Settings" with only those settings listed that apply to 
the functional area. An Advanced Settings for the File manager, an Advanced Settings for the cr3 
Reader and an Advanced Settings for the PDF reader. Called from their respective menus. That might 
sort them out better, as well.

**Comment by poire-z** [comment]
Most useful advanced settings have been moved to proper settings and menus over the years. So, closing.
Also related: #2589 .
