### ISSUE TITLE
Move the menu item for the Calibre wireless connection, from Reader menu to File Manager menu.

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1871]
- KOReader version: All?
- Device:

It seems more intuitive, to me, if the Calibre wireless connection function were in the File Manager, instead of the Reader menus.  If  moved, it should be easier for the average user to find and use.

**Comment by KenMaltby** [comment]
Just noticed that the OTA function also is in the File Manager menus.

**Comment by Frenzie** [comment]
I don't know about Calibre, but I think OTA update makes sense in both
locations (as it is).

**Comment by KenMaltby** [comment]
That is why I changed the title.

**Comment by houqp** [comment]
I think for now, it actually makes more sense to have them in both menus given that many people use koreader without filemanager? Especially for kindle users, they probably just run koreader from kpvbooklet.

**Comment by robert00s** [comment]
In the newest versions "Calibre wireless connection" is also available in File Manager menu.

**Comment by houqp** [comment]
Thanks @robert00s for catching this issue :)
