### ISSUE TITLE
keyboard should support cursor navigation

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#1872]
- KOReader version: ALL
- Device: ALL

A followup for https://github.com/koreader/koreader/pull/1840#issuecomment-193398231.

**Comment by robert00s** [comment]
Do you mean a virtual or physical keyboard?

**Comment by Frenzie** [comment]
I think it's about virtual. Maybe another layer?

**Comment by robert00s** [comment]
I think we have two possibility:
+ Add left and right arrow to the symbol layer like that
![screenshot 2017-09-30 17-05-43](https://user-images.githubusercontent.com/22982594/31046937-f53cf47a-a601-11e7-81a8-87bad68cf7b6.jpg)
but we don't have space to another button (up, down, home, end etc)
+ Add another layer with arrow and "move buttons" like home, end pageup ...
But how to enable/disable this new layer (long press space? long press Sym?)

**Comment by KenMaltby** [comment]
The right and left arrows would be all you need, combined with Frenzie's poke where you want the cursor.

**Comment by robert00s** [comment]
Pinging @Frenzie @Hzj-jie @Eduardomb22 @poire-z 
Any objection to use method 1?

**Comment by Frenzie** [comment]
I note that it would remove the @? But the duplication of `,` does seem kind of odd.

![screenshot_2017-10-01_14-43-27](https://user-images.githubusercontent.com/202757/31054631-f13d0ff8-a6b6-11e7-8e25-b3e7dbbcc943.png)

I haven't looked at the code for this, but visually I think the present keyboard is pretty decent and consistent with regular QWERTY. I'd strip out that redundant comma at the bottom, shrink the spacebar and put the left and right arrows in that spot. They could even double as up/down with some long-press action.

![screenshot_2017-10-01_14-43-27](https://user-images.githubusercontent.com/202757/31054654-d866d026-a6b7-11e7-9319-2801e4cd61bc.png)

**Comment by Eduardomb22** [comment]
I liked everything about @Frenzie suggestion. The arrow´s position, if possible, will be better at the spot he posted.

**Comment by robert00s** [comment]
Good idea.
But in this case we have shrink the spacebar and one more button in all modes.

**Comment by Frenzie** [comment]
Fine by me. Alternatively we could make the spacebar more dynamic.

Btw, Japanese keyboards have a smaller spacebar.

https://en.wikipedia.org/wiki/File:Physical_keyboard_layouts_comparison_ANSI_ISO_KS_ABNT_JIS.png
![1600px-physical_keyboard_layouts_comparison_ansi_iso_ks_abnt_jis](https://user-images.githubusercontent.com/202757/31055033-ac23bb94-a6be-11e7-9d30-be6a93cb0947.png)
