### ISSUE TITLE
Up-right side may miss after resume

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1874]
* KOReader version: Nightly 2015.11-233 (built myself)
* Device: Kobo Aura HD with firmware 3.19.5761

#### Issue
Up-right side of the screen turns to blank after resume.

#### Steps to reproduce
Suspend, then resume.
I cannot consistently reproduce this issue, but keep the device in suspending state for a long time may help to reproduce.

Below are two images when the issue reproduced,
https://raw.githubusercontent.com/Hzj-jie/files/master/IMG_20160308_161430.jpg
https://raw.githubusercontent.com/Hzj-jie/files/master/IMG_20160308_161551.jpg

**Comment by houqp** [comment]
Could you test to see if the bug is introduced in this commit? https://github.com/koreader/koreader/commit/ada373e247020c484053a09d76ffbd675b00a7e1

**Comment by Hzj-jie** [comment]
Should be partially, I found (at least on my device) this issue almost the first day I used koreader (should be early Feb). But, yes, commit ada373e does make this issue worse. i.e. both the trigger rate and impacted area size have increased.

**Comment by houqp** [comment]
Hm... it's weird the shape is so irregular. I also don't get a screen refresh at all after resume without that commit. I will see if I can reproduce this issue tonight.

**Comment by Hzj-jie** [comment]
It's always a right trapezoid AFAIK. It may be a Kobo specific issue, on my device, the screen is always refreshed after resume.

**Comment by houqp** [comment]
I am also using kobo Aura HD. It's probably because I have a much older firmware. But I can confirm that it's a recent change that makes the refresh go away.

**Comment by houqp** [comment]
@Hzj-jie , could you test whether adding a sleep in `Kobo:resume` helps alleviate the issue?

**Comment by Hzj-jie** [comment]
I will try, will get you back later.

**Comment by Hzj-jie** [comment]
I have not seen the issue reproduces anymore, after added a os.execute("sleep 0.1") after os.execute("echo 0 > /sys/power/state-extended").
I found the screen fully refresh after resuming, is it because of the screensaver?

**Comment by Hzj-jie** [comment]
Tried several times, with various suspending duration, I have not seen the issue reproduced anymore. But still cannot quite understand the root cause.

**Comment by NiLuJe** [comment]
Kernel being stupid.

**Comment by houqp** [comment]
Yeah, this is usually the sign of race condition in kernel drivers where we tells it to update the screen while it is still in the process of waking up.

**Comment by Hzj-jie** [comment]
Do you prefer me to send the PR for this change?

**Comment by houqp** [comment]
Yes please ;)
