### ISSUE TITLE
Opening file '...' message box won't show until koreader has fully started

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1876]
* KOReader version: Nightly 2015.11-233 (built myself)
* Device: Kobo Aura HD with firmware 3.19.5761

#### Issue
Opening file '...' message box won't show until koreader has fully started.
i.e. When starts koreader from KSM, with 'Start with last opened book' settings on, the screen will remain unchanged for a long time (depends on file size).

#### Steps to reproduce
Described above.

Commit 5e8c5243c433a73a7ee4cdc93409db54fd2d1ae5 should be the trigger. i.e. if UIManager:handleInput won't be called immediately after ReaderUI:showReader. Or in another word, UIManager won't start before ReaderUI:showReader (https://github.com/koreader/koreader/blob/master/reader.lua#L144), the message won't show when KoReader starts.

A potential fix is to schedule any procedures in reader.lua line 144 - 171 into UIManager:nextTick.

**Comment by houqp** [comment]
Good catch! My bad for not testing last opened book option.

**Comment by KenMaltby** [comment]
And I thought you guys had sped up the starting of reader so much that my last page was displayed ahead of the mesagebox.  I thought it was starting faster.
