### ISSUE TITLE
Certain book files cause a crash-to-home-screen

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#1880]
* KOReader version: Latest dev build
* Device: Kindle Touch

#### Issue
I've [mentioned](https://github.com/koreader/koreader/issues/1701#issuecomment-153466898) this a while ago, but it seems to have slipped under the radar. Basically, both EPUB and Mobi files from [this page](https://www.gutenberg.org/ebooks/4300) consistently cause KOReader to crash to the home screen.

**Comment by frankyifei** [comment]
I tried epub-with images. it is ok on my kpw

**Comment by houqp** [comment]
@GeneralFailer , do you have crash.log that you can upload?

**Comment by GeneralFailer** [comment]
It just says "Segmentation fault" there. I use the official nightly releases.

**Comment by frankyifei** [comment]
this is identical to #1852 , i reproduce this bug with older version. it has been fixed but not released yet

**Comment by houqp** [comment]
@GeneralFailer can you try the latest version as @frankyifei said? He fixed a bug in CREngine a while ago. I also cannot reproduce the crash on my side.

**Comment by GeneralFailer** [comment]
I'm having trouble installing gcc-arm-linux-gnueabi on Arch Linux. There's only arm-none-eabi-gcc in repos and nothing in AUR.

**Comment by frankyifei** [comment]
that should be the same one. I tried older build of crengine, and it did crash like #1852 . Also I found a better way to fix this, the bug is when len==64, TexHyph::hyphenate() will crash. The last fix will work because when len>64, it will reduce it to WORD_LENGTH-2=62.

**Comment by houqp** [comment]
@GeneralFailer setting up build environment in Arch is not easy right now.  I am also having issue with setting it up in a arch vm. You can use https://github.com/koreader/virdevenv/tree/master/vm/ubuntu to do the build for now, which should work out of the box.

**Comment by GeneralFailer** [comment]
The building failed apparently. Here's the console output.
[log.txt](https://github.com/koreader/koreader/files/174288/log.txt)

**Comment by GeneralFailer** [comment]
The new official build fixes opening Ulysses, but doesn't fix opening FB2 from #1852.

**Comment by houqp** [comment]
@GeneralFailer thanks for reporting. I am not able to reproduce the bug on my side, but based on the error log, it's very likely caused by a bug in the build script. See: https://github.com/koreader/koreader-base/pull/394.

**Comment by GeneralFailer** [comment]
@houqp I tried building with only the first fix and it didn't report any errors, but the build still weighs over 1.8 GB.
[log.txt](https://github.com/koreader/koreader/files/176685/log.txt)

**Comment by houqp** [comment]
@GeneralFailer , the size of the build is expected to be that large. KOReader is not a trivia reader project ;)
