### ISSUE TITLE
bug: OTA always show the lastst is 2015110219 and OTA failed too.

### ISSUE THREAD

**Issue by yasteora** [koreader/koreader#1883]
* KOReader version:koreader-nightly-20160227

* Device:kpw3 kobo glo 

#### Issue 
Hello,After I downloaded koreader-nightly-20160227,I upgraded by OTA, but it always show me download the 2015110219 edition, althought I found the lastst  edition is 240 from  http://koreader.ak-team.com/ . And I cant OTA to the new edition too.
Is this is a bug?

**Comment by houqp** [comment]
I assume you already chose the nightly channel in the OTA setting?

**Comment by yasteora** [comment]
@houqp Hi,houqp,I had set the OTA channel to develop,I do not find the nightly channel.

**Comment by houqp** [comment]
Sorry, i meant develop channel ;P

Hmm.. I won't have time to dig into this until weekend. @chrox , any thoughts?

**Comment by NiLuJe** [comment]
In a slightly related note, we've had a report of failed updates on Kindles over on MR.

Haven't had time to look into it yet either.

**Comment by KenMaltby** [comment]
The "http://vislab.bjmu.edu.cn/apps/koreader/ota/koreader-kobo-latest-nightly.zsync" only has:
Filename: koreader-kobo-arm-linux-gnueabihf-v2015.11-219-g2fda2d0.targz MTime: Sun, 06 Mar 2016 10:02:16 +0000 Blocksize: 2048 Length: 41605120 Hash-Lengths: 2,2,5 Z-URL: koreader-kobo-arm-linux-gnueabihf-v2015.11-219-g2fda2d0.targz in the start of it.

**Comment by Markismus** [comment]
I am also not able to download via OTA since a few days.

**Comment by KenMaltby** [comment]
It looks like whatever was supposed to create new .zsync files, stopped working some time ago. At leased for the Kobo releases.

**Comment by Goligoski** [comment]
The same for the kindle. Cannot update.

**Comment by KenMaltby** [comment]
Try again it looks like the .zsync files have been updated: For Kindle:
Filename: koreader-kindle-arm-linux-gnueabi-v2015.11-251-g511147a.targz MTime: Sun, 13 Mar 2016 15:12:33

**Comment by Markismus** [comment]
Looking at [this line](https://github.com/koreader/koreader/blob/cf9dc260339b5cb3d004f4877a51d5dc653c0999/Makefile#L162) in the makefile targz is the intended extension. 

Could the double appearance of package.index on koreader/ota (see [this post](https://github.com/koreader/koreader/issues/1818#issuecomment-196022054)) be the cause for the malfunction?

**Comment by KenMaltby** [comment]
I would guess that the OTA plugin checks the .zsync file for the file to be downloaded.  If the file is not newer than what is running on the device, the update would be aborted.

**Comment by houqp** [comment]
OTA looks for the version in .zsync file and compare it with the current version of KOReader, which is saved in `git-rev` file.

@yasteora and @Markismus , can you confirm that OTA is working now?

**Comment by yasteora** [comment]
@houqp  Hi, I tested on KOBO and  Kinlde ,they are both working now thanks!
