### ISSUE TITLE
Android: No reader engine for this file

### ISSUE THREAD

**Issue by medwatt** [koreader/koreader#1884]
* KOReader version: koreader-nightly-20160227
* Device: Onyx i86 Plus (Android 4.0.4)

#### Issue
Cannot load ePub or djvu documents. I get the message "No reader engine for this file".

#### Steps to reproduce
Just try to open any ePub or djvu file.

**Comment by houqp** [comment]
I just tried it out with verstion 254 and was able to open epub files. Can you give that version a try when it's out? Also do you have access to `adb log`?

**Comment by medwatt** [comment]
@houqp, I have access to the log file. What do you want me to run or what do you want to see ?

**Comment by houqp** [comment]
Thanks for the log, it already points out the issue:

```
I/luajit-launcher( 9678): try to load module libs/libkoreader-cre.so
I/luajit-launcher( 9678): error: [string "dl.lua"]:80: could not find library libpng16.so.16
I/luajit-launcher( 9678): try to load module /data/data/org.koreader.launcher/files/libs/libkoreader-cre.so
```

I wonder why  libpng16.so.16 is missing from the build. Where did you download the apk file?

**Comment by medwatt** [comment]
@houqp, I downloaded it from https://github.com/koreader/koreader/releases. This file that I downloaded has the name "koreader-android-arm-linux-androideabi-v2015.11-175-g7b11491.apk".

**Comment by houqp** [comment]
@chrox the build in release page is quite old. How do we upload the nightly build right now? Is it still done from your build server? We can also use travis to generate and upload the build if it's easier for you. I can help with that if needed.

**Comment by houqp** [comment]
In case you want to give the latest version a try, you can download the release I attached in this comment.

[koreader-android-arm-linux-androideabi-v2015.11-254-g959bf73.zip](https://github.com/koreader/koreader/files/173383/koreader-android-arm-linux-androideabi-v2015.11-254-g959bf73.zip)

**Comment by chrox** [comment]
The build server is already fixed now.

**Comment by KenMaltby** [comment]
I don't understand how the .zsync file there now, with "zsync: 0.6.2 Filename: koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-219-g2fda2d0.targz MTime: Sun, 06 Mar 2016 10:02:58"  
Or how the: koreader-android-arm-linux-androideabi-v2015.11-253-gcf9dc26.targz ends up an .apk?

I can see that  houqp's .zip could be changed to .apk ( would it need to be signed to install?)

**Comment by chrox** [comment]
It now refers to koreader-android-arm-linux-androideabi-v2015.11-253-gcf9dc26.targz which will be unpacked by koreader program and the main part of koreader will be updated. Previously the pocketbook file on Android's zsync file is just a test case.

**Comment by KenMaltby** [comment]
Ah, makes sense now, thanks for setting me straight. (I broke my tablet, so I can't try it out, till I get a new one.)

**Comment by chrox** [comment]
Should be fixed in the latest release. Close this now.
