### ISSUE TITLE
Building emulator fails at build step for lua-spore

### ISSUE THREAD

**Issue by m4kh** [koreader/koreader#1887]
* KOReader version: Build from source (Sun Mar 13 09:00:25 2016, master branch, commit 511147ae29ce443e12cb775cca1505d60810beb6)
* System: Ubuntu 15.10, 32 bit

I followed the building instructions described in the readme. However, building the emulator both for linux (./kodev build) as well as for win32 (./kodev build win32) fails at the _lua-spore_ build step. I successfully build for kobo (./kodev release kobo) and ubuntu-touch (./kodev release ubuntu-touch). Both seem to perform the same build step but without errors. Any suggestions? The errors are as follows:
```
Performing build step for 'lua-Spore'

Missing dependencies for lua-spore:
luajson >= 1.3

Using https://rocks.moonscript.org/luajson-1.3.3-1.src.rock... switching to 'build' mode

Missing dependencies for luajson:
lpeg >= 0.8.1

Using https://rocks.moonscript.org/lpeg-1.0.0-1.src.rock... switching to 'build' mode
/usr/bin/ccache gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/home/koreader/base/thirdparty/luajit/build/i686-linux-gnu/luajit-prefix/src/luajit/src -I/usr/include/lua5.1 -c lpcap.c -o lpcap.o
/usr/bin/ccache gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/home/koreader/base/thirdparty/luajit/build/i686-linux-gnu/luajit-prefix/src/luajit/src -I/usr/include/lua5.1 -c lpcode.c -o lpcode.o
/usr/bin/ccache gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/home/koreader/base/thirdparty/luajit/build/i686-linux-gnu/luajit-prefix/src/luajit/src -I/usr/include/lua5.1 -c lpprint.c -o lpprint.o
/usr/bin/ccache gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/home/koreader/base/thirdparty/luajit/build/i686-linux-gnu/luajit-prefix/src/luajit/src -I/usr/include/lua5.1 -c lptree.c -o lptree.o
/usr/bin/ccache gcc -O2 -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/home/koreader/base/thirdparty/luajit/build/i686-linux-gnu/luajit-prefix/src/luajit/src -I/usr/include/lua5.1 -c lpvm.c -o lpvm.o
ld -shared -o lpeg.so -L/usr/local/lib lpcap.o lpcode.o lpprint.o lptree.o lpvm.o
lpcap.o: In function `stringcap':
lpcap.c:(.text+0x41e): undefined reference to `__stack_chk_fail_local'
lpcap.o: In function `.L132':
lpcap.c:(.text+0xb20): undefined reference to `__stack_chk_fail_local'
lpcap.o: In function `getcaptures':
lpcap.c:(.text+0xe81): undefined reference to `__stack_chk_fail_local'
lpcode.o: In function `.L117':
lpcode.c:(.text+0x56e): undefined reference to `__stack_chk_fail_local'
lpcode.o: In function `realloccode':
lpcode.c:(.text+0x763): undefined reference to `__stack_chk_fail_local'
lpcode.o:lpcode.c:(.text+0x97b): more undefined references to `__stack_chk_fail_local' follow

Error: Failed installing dependency: https://rocks.moonscript.org/luajson-1.3.3-1.src.rock - Failed installing dependency: https://rocks.moonscript.org/lpeg-1.0.0-1.src.rock - Build error: Failed compiling module lpeg.so
CMakeFiles/lua-Spore.dir/build.make:108: recipe for target 'lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-build' failed
make[4]: *** [lua-Spore-prefix/src/lua-Spore-stamp/lua-Spore-build] Error 1
make[4]: Leaving directory '/home/koreader/base/thirdparty/lua-Spore/build/i686-linux-gnu'
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/lua-Spore.dir/all' failed
make[3]: *** [CMakeFiles/lua-Spore.dir/all] Error 2
make[3]: Leaving directory '/home/koreader/base/thirdparty/lua-Spore/build/i686-linux-gnu'
Makefile:75: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/koreader/base/thirdparty/lua-Spore/build/i686-linux-gnu'
Makefile.third:452: recipe for target 'build/i686-linux-gnu/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec' failed
make[1]: *** [build/i686-linux-gnu/rocks/lib/luarocks/rocks/lua-spore/0.3.1-1/lua-spore-0.3.1-1.rockspec] Error 2
make[1]: Leaving directory '/home/koreader/base'
Makefile:52: recipe for target 'all' failed
make: *** [all] Error 2
./kodev: line 7: [: too many arguments
 ```

**Comment by Markismus** [comment]
It seems that `Failed installing dependency: https://rocks.moonscript.org/luajson-1.3.3-1.src.rock - Failed installing dependency: https://rocks.moonscript.org/lpeg-1.0.0-1.src.rock ` is the breaking error.

You can check whether you have lpeg and luajson installed with `$ luarocks list`
If they are absent, tou could try installing them manually before compiling:
```sh
$ sudo luarocks luajson 
$ sudo luarocks lpeg
```

**Comment by m4kh** [comment]
Thanks for the help. I tried installing the dependencies manually by calling `sudo luarocks install luajson` and `sudo luarocks install lpeg`. However, they got installed in `/usr/local` and subsequently calling `./kodev build` resulted in the same errors as listed above. I checked the build log of my successful build for kobo `./kodev release kobo` and it seems they need to be installed in `koreader/base/build/<PLATFORM>/rocks`. So for the emulator I installed them using:

```
cd ~/koreader/base/build/i686-linux-gnu/rocks
sudo luarocks install lpeg --tree=./
sudo luarocks install luajson --tree=./
```

Now `./kodev build` works and I can run the emulator. I think I read in another issue that recently some changes to the build scripts were introduced. Maybe the scripts for the emulators are not up-to-date?

**Comment by houqp** [comment]
Interesting, I have never seen that error before. But I have also never tried compiling in 15.10, so maybe something in the system toolchain is different. I will see if I can reproduce this with a 15.10 VM.

By just looking at the link error, looks like we should be able to workaround it by replacing `ld` with `gcc`.

**Comment by houqp** [comment]
@m4kh , just in case you are bored and want to test my theory ;) You can edit this line: https://github.com/koreader/koreader-base/blob/master/thirdparty/lua-Spore/CMakeLists.txt#L24 and replace `LD=\"${LD}\"` with `LD=\"${CC}\" to see if the error is still there.

**Comment by NiLuJe** [comment]
Or could it be ccache being stoopid?

(Never used ccache, so, wild guess ;p).

**Comment by houqp** [comment]
@NiLuJe are you not using ccache with gentoo? ;)

**Comment by NiLuJe** [comment]
I so rarely rebuild non-trivial stuff that I never bothered, no ;).

I do build everything in a tmpfs to nullify IO impact (and avoid usless cell writes on the SSD), though.

That, and I did upgrade my 5 year old box this winter...

```
cat /proc/cpuinfo | grep -e name -e 
model name      : Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
cpu MHz         : 4400.000
```

It does the job... *grin*

(I've had to switch to a pasta-heavy diet, but that's a minor detail... :D)

**Comment by houqp** [comment]
Damn... as a comparison, here comes my main laptop:

```
 $ cat /proc/cpuinfo | grep -e name -e MHz                                                                                                                                                                             git:houqp-master8cdf526
model name      : Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
cpu MHz         : 1600.000
```

This is why I decided not to use gentoo on my mac air ;)

I remember on my old sony laptop, KDE update would take a whole night. Fun time...

**Comment by NiLuJe** [comment]
Yep, I have a recent-ish entry-level 11" Air too, and, yuuuup, that one stayed on OS X for pretty much the exact same reason ;p.

**Comment by m4kh** [comment]
I tested @houqp's theory by replacing `LD=\"${LD}\"` with `LD=\"${CC}\"` on line 24 of `~/koreader/base/thirdparty/lua-Spore/CMakeLists.txt`. Now the build hangs at:

```
Performing build step for 'lua-Spore'
Missing dependencies for lua-spore:
luajson >= 1.3
Using https://rocks.moonscript.org/luajson-1.3.3-1.src.rock... switching to 'build' mode
```

I also tried to disable ccache by inserting `export USE_NO_CCACHE=1` into `kodev` (without @houqp's mod). But this results in the same error as reported in the first post. Any other ideas?

**Comment by NiLuJe** [comment]
Which luarocks/lua version is your system using?

**Comment by m4kh** [comment]
My system uses `LuaRocks 2.2.0` and `Lua 5.1`.

**Comment by m4kh** [comment]
If it helps, here are the complete logs for my successful [kobo build](https://www.dropbox.com/s/4af4aoulsnt59y8/kobo_out.txt?dl=0) and the failed [emulator build](https://www.dropbox.com/s/merc6pr3alexohd/emulator_out.txt?dl=0). I briefly checked them but couldn't find any issues.

**Comment by houqp** [comment]
In your build log, I found following error:
```
Failed installing dependency: https://rocks.moonscript.org/lpeg-1.0.0-1.src.rock - Permission denied
```
So looks like it's trying to install it to global tree, which requires root access. Looking at `thirdparty/lua-Spore/CMakeLists.txt`, we are using `luarocks make --to=DIR` option to specify the output directory. This is weird, because I can't find any reference to that option in luarocks's documentation. I am trying with `--tree` on my dev machine right now to see if it build correctly. If so, we should use `--tree` instead.

**Comment by houqp** [comment]
@m4kh so `--tree` worked for me. Can you give it a try by modifying the `CMakeLIsts.txt` file? If it fixes your issue, feel free to submit a pull request :)

**Comment by m4kh** [comment]
It's strange that `Permission denied` didn't show up in the first build log above. I will try using the `--tree` option, and report back later today.

**Comment by m4kh** [comment]
I tried the `--tree` option but got the same error as reported in the first post. I also tried building in a clean VM running Ubuntu 14.04.4 LTS. The build failed at the same location while trying to install `lpeg` in the `lua-spore` step. This time I got `cp: cannot stat ‘lpeg.so’: No such file or directory` (line 4433). Please see the [build log](https://www.dropbox.com/s/6tpnx03t4jhlwkk/ubuntu14_emulator_out.txt?dl=0) for details.

**Comment by houqp** [comment]
This is weird. Did you apply the `LD=\"${CC}\"` workaround in your VM? How different is your vm setup compared to https://github.com/koreader/virdevenv/tree/master/vm/ubuntu? What's the GCC version?

**Comment by m4kh** [comment]
I finally get successful builds by applying both `LD=\"${CC}\"` and `--tree`. Somehow i didn't try this combination before. It works in both VMs running Ubuntu 15.10 and 14.04.4 LTS. GCC version is 4.8.4. Thanks @houqp for the hint.

**Comment by houqp** [comment]
Thanks @m4kh for confirming the fix. I have included the patch in https://github.com/koreader/koreader-base/pull/394
