### ISSUE TITLE
koreader.sh does not be called by KSM 08 anymore

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1889]
* KOReader version: latest nightly build (built myself)
* Device: Kobo Aura HD

#### Issue

I am using KSM 08 (2015.10.27) to start koreader, and almost suddenly, koreader.sh does not be called by KSM anymore. KSM uses some magic way to start koreader. Is it an expected change, or anything wrong with my device or configuration?

#### Steps to reproduce

I recently found remount sd card function did not work anymore. After some debugging work, I found koreader.sh does not been called by KSM 08. While I am pretty sure the folder I am using is correct. Since if I delete koreader folder, start nickel and start koreader won't show in KSM, also the legacy history files are written in the correct folder. I can even start koreader from KSM after I delete koreader.sh. But unfortunately koreader.sh contains logic to mount sd card as writable, so it won't work. I tried to add a koreader startup script in KSM user scripts folder to start koreader.sh, and everything works fine if I start koreader from this startup script.

It's pretty strange, have you ever got similar issues before?

Thank you.

**Comment by KenMaltby** [comment]
You might get more results at the KSM8 thread on MR in the Kobo Developer's Corner subforum.

**Comment by houqp** [comment]
@Hzj-jie do you have the link for the new KSM download? I can take a look to see what's going on. We might need to coordinate with KSM project on this.

**Comment by Hzj-jie** [comment]
I believe I have downloaded KSM8 @ http://www.mobileread.com/forums/showthread.php?t=266821
It used to work well, but, yes, things suddenly changed around last week.
@KenMaltby I did not see a clear description, how KSM find koreader or other applications for kobo and start it on mobileread, KSM is not an open source project AFAIK.

**Comment by Frenzie** [comment]
It may not be free software, but the source is open enough. It's in a util
folder or something like that.

**Comment by KenMaltby** [comment]
Tshering's scripting has been given freely to the Kobo Community at MR, to great benefit for KOReader users as well as those using the stock software.  
While some parts have been moved to the System partition, tshering has had the starting of KOReader use the koreader.sh in the koreader folder and I doubt that, that has changed.  Where the koreader folder has been, was changed to /mnt/onboard/.adds when KSM7 was introduced.

**Comment by Frenzie** [comment]
Having had a chance to take a quick peek now (I was on my phone before), the script I was referring to is /adds/kbmenu/onstart/start_koreader.sh

Specifically, it checks whether koreader.sh contains `from_nickel`
```
if [ $(grep -c 'from_nickel' "$koreadersh") -gt 0 ]; then
```

A quick look shows you to be responsible for [changing from_nickel to FROM_NICKEL](https://github.com/koreader/koreader/blob/770625d756868c713c897575da6750726761315b/platform/kobo/koreader.sh#L90) a couple of weeks ago. So just revert that particular change and we're good. ;)

**Comment by Frenzie** [comment]
Wait, I'll just do that myself. I'm on a proper computer after all. =P

PS My previous comment has seen some editing.

**Comment by Hzj-jie** [comment]
What's an interesting hack in KSM. Why doesn't KSM just try to execute a start.sh in each folder?

Anyway, thank you everyone to digdug the issue.

**Comment by Frenzie** [comment]
> Why doesn't KSM just try to execute a start.sh in each folder?

Because the KOReader startup script saw some great improvements since the earlier versions of KSM, and there's really no good reason for it to force newer versions on people who aren't interested. Kind of the same reason I've made sure newer versions of KOReader [work with older versions of KSM](https://github.com/koreader/koreader/commit/475ee2817370015c61f3e23a8a4f901ebed19154). =)
