### ISSUE TITLE
Flipping mode doesn't work

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#1894]
#* KOReader version:
v2015.11-3-g9e0be45
* Device:
Kindle 7th generation, firmware 5.7.2.1

#### Issue
Flipping mode does not work with PDF file

#### Steps to reproduce
I tap top left corner, book ion appears, but swiping finger only makes screen update, without page changing

**Comment by chrox** [comment]
In order to flip pages in flipping mode, we must first set the zoom mode to "Zoom to fit page". Note that the zoom mode set in flipping mode does not affect zoom mode in regular reading. I'll clarify this in the wiki page and close this issue.

**Comment by ilyats** [comment]
But why? Or if it is necessary, shouldn't zoom mode be set automatically? Also, even if I set 'zoom to fit page', swiping finger in horizontal direction produces strange results, with page changing, but then immediately returning back to the original one.

**Comment by ilyats** [comment]
Flipping mode still does not work with Koreader v2011.15-877-ga2f2ac0 and firmware 5.8.7.0.1

**Comment by ilyats** [comment]
Also, sometimes pressing top left corner of the screen opens dictionary instead of turning on flip mode (at other times it works correctly).
