### ISSUE TITLE
Checklist for next stable release

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#1897]
Feel free to add things here as you see fit.
## todo
- [ ] close all issues in `next stable release` milestone: https://github.com/koreader/koreader/milestones/next%20stable%20release
### breaking change
- KOBO_SCREEN_SAVER and KOBO_SCREEN_SAVER_LAST_BOOK removed in favor of `use_lastfile_as_screensaver` and `screensaver_folder` in reader.settings.lua. See: https://github.com/koreader/koreader/pull/1969
## changelog
- CREngine speed up: https://github.com/koreader/koreader/pull/1896
- backgroud image support for epub: https://github.com/koreader/crengine/pull/32
- (kindle) k3/dxg/k4 support
- (kobo) auto suspend support for kobo
- (kobo) fix touch screen probe for kobo touch
- fix highlight in reflow mode (@jedick): https://github.com/koreader/koreader/issues/1573

**Comment by gerroon** [comment]
Image browsing mode?
It would be nice if Kr could browse next/prev image (when tapped to next previous) in the folder if it is used for opening an image.

Ironing out Android stability issue

**Comment by houqp** [comment]
Image browsing mode would be something nice to have, but probably not in the next release. Feel free to file a FR issue for it though.

I have included most of the outstanding android issues in the milestone.

**Comment by Frenzie** [comment]
Closing as outdated.
