### ISSUE TITLE
text-align property doesn't always seem to work

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#1899]
* KOReader version: Last nightly build
* Device: Kindle Touch

#### Issue
I've noticed that in one book I'm reading text doesn't get centered in KOReader. [Here's](https://github.com/koreader/koreader/files/178469/test.zip) a small example file that suffers from this.

**Comment by KenMaltby** [comment]
It works fine (what little is there), if you have "Embedded Style" turned on.  It is under the bottom reader menu Gear Icon.

**Comment by GeneralFailer** [comment]
Ah, right, I haven't thought of that. I think it would be very helpful if there was an embedded font option that wouldn't affect this kind of sometimes-important stuff. Though from what I can now see it would be a poor trade-off in the case of that specific book file.
I wonder if any reader app developers have created a sensible easy solution for these kinds of weird ugly cases that doesn't involve creating your own personal css or whatever.

**Comment by houqp** [comment]
@GeneralFailer we can possible just abstract these typesetting out into book config/menu options. Then convert the configs into css overrides on the fly and apply to the documents.

**Comment by GeneralFailer** [comment]
They'd still have to be pretty much set on basis of HTML tags, right?
Anyways, is Embedded Style off supposed to make styles to be completely ignored as opposed to low-priority? I've commented .div out of epub.css completely, but it still gets aligned to the left. If so, is there a priority-based kind of option?

**Comment by houqp** [comment]
> They'd still have to be pretty much set on basis of HTML tags, right?

There are some common HTML tags. Like we can assume content are wrapped in `<p>` etc.

> Anyways, is Embedded Style off supposed to make styles to be completely ignored as opposed to low-> priority? I've commented .div out of epub.css completely, but it still gets aligned to the left. If so, is there > a priority-based kind of option?

I believe when Embedded Style is on, all other css will be skipped.
