### ISSUE TITLE
Koreader startup ignores light OFF (intensity 0) when synchronized with nickel

### ISSUE THREAD

**Issue by m4kh** [koreader/koreader#1902]
* KOReader version: v2015.11-253-gcf9dc26
* Device: Kobo Glo HD

#### Issue
Koreader always starts with light on (intensity set to 1) if light has been disabled in nickel. For light levels between `0 -100` the synchronization works fine.

#### Steps to reproduce
Turn the light off in nickel and exit to KSM. `Kobo eReader.conf` shows `FrontLightLevel=0`. Start koreader. On startup the light is turned on automatically (intensity set to 1). Exit koreader. `Kobo eReader.conf` shows `FrontLightLevel=1`. This also happens if the light is toggled off in koreader before exiting. Koreader advanced settings are `KOBO_LIGHT_ON_START = -2` and `KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true`.

**Comment by houqp** [comment]
@Hzj-jie , the normalize function will convert 0 to 1, we need to handle 0 as special case here.
@m4kh , could you also check the `FrontLightState` config in `Kobo eReader.conf` after you exit nickel with frontlight turned off? I suspect your nickel also does not write out this config entry, which is used by KOReader to turn on/off frontlight on start.

**Comment by m4kh** [comment]
I don't see a `FrontLightState` entry in my `Kobo eReader.conf`. I have firmware `3.19.5761 (0e028f3185, 12/29/15)` installed via KSM.

**Comment by djalma2k** [comment]
Same that @m4kh (Kobo Glo HD with 3.19.5761 upgraded via "nickel") and don't appears any "FrontLightState" parameter in my Kobo eReader.conf. Exists a parameter called "FrontLightLevel"...
Regards.

**Comment by houqp** [comment]
@m4kh @djalma2k next build should work without the workaround ;)
