### ISSUE TITLE
FR: Use gestures for controlling light intensity to turn light off

### ISSUE THREAD

**Issue by m4kh** [koreader/koreader#1903]
- KOReader version: v2015.11-253-gcf9dc26
- Device: Kobo Glo HD

Enhance swipe gestures for turning light off (intensity 0). Currently the minimum intensity that can be set via gestures is 1. It would be nice if continuing to swipe down would turn the light off completely. Currently this is only possible through the toggle button in the frontlight menu.

**Comment by houqp** [comment]
I would consider this a bug. Related to https://github.com/koreader/koreader/issues/1902.
