### ISSUE TITLE
Koreader does not work on Samsung Galaxy SIII Neo

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#1904]
- KOReader version:
  koreader-stable-v2015.11
- Device:
  Samsung Galaxy SIII Neo GT-I9301I Android 4.4.2 firmware I9301IXXUAOD2
#### Issue

black screen on start
#### Steps to reproduce

Download and install stable .apk, then start koreader. Black screen appears, no reaction to touches or buttons.

**Comment by houqp** [comment]
Likely a duplicate of https://github.com/koreader/koreader/issues/1782#issuecomment-198535990.

**Comment by Frenzie** [comment]
@ilyats Is this still an issue?

**Comment by ilyats** [comment]
@Frenzie I don't know, I don't have that phone anymore

**Comment by Frenzie** [comment]
I'll close this then. :-)
