### ISSUE TITLE
Status bar don't show the chapter structure

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1905]
* KOReader version: v2015-11 261 and 264
* Device: Kobo Glo HD

#### Issue
Status bar don't show the epub file chapter structure. It doesn't happen with v2015-11-214

![statusbar_1](https://cloud.githubusercontent.com/assets/17313916/13894353/25f7ff6a-ed67-11e5-8d95-ff64000bfb9b.png)

![statusbar_2](https://cloud.githubusercontent.com/assets/17313916/13894361/2a861f76-ed67-11e5-8b81-5f039d082959.png)

**Comment by KenMaltby** [comment]
I lost the chapter tick marks with 261 also.

**Comment by houqp** [comment]
Thanks for the report. My bad for breaking this.

**Comment by djalma2k** [comment]
Well, the chapter tick marks seemed to work well until now I just try the following [book](http://m.zbigz.com/myfiles?url=magnet:?xt=urn:btih:7CBFF2D42C37713C6BB7835BADFA9A1389B3FEB4&dn=EPL_Sueno_en_el_pabellon_rojo&tr=http://tracker.tfile.me/announce&tr=http://91.121.54.8:6969/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://open.demonii.com:1337/announce)
Regards.
