### ISSUE TITLE
OTA update gets downloaded but not installed after restart

### ISSUE THREAD

**Issue by m4kh** [koreader/koreader#1907]
* KOReader version: koreader-nightly-20160315
* Device: Kobo Glo HD

#### Issue
OTA updates are downloaded but not installed after restart.

A partially related issue:
1) The check for updates is not performed automatically, after the prompt for turning on wifi (in case wifi was off previously). After wifi is turned on, the prompt closes and I have to go back into the menu and hit `check for updates` again.

#### Steps to reproduce
If I hit `check for updates`, the prompt says `installed version: 2015110253` and `available version: 2015110270`. I agree to update, the update gets downloaded, and a prompt appears with `KOReader will be updated on next restart`. After I restart koreader and hit `check for updates` again, I get the same prompt with the same versions. Checking the folder `koreader/ota/` it seems that indeed some update files have been downloaded. My OTA channel is set to `develop`.

**Comment by NiLuJe** [comment]
What's the exact file listing of your ota directory?

**Comment by m4kh** [comment]
My ota directory shows the following files:

- koreader.installed.tar
- koreader.updated.tar
- koreader-kobo-latest-nightly.zsync
- package.index

**Comment by NiLuJe** [comment]
How do you launch KOReader?

**Comment by m4kh** [comment]
I launch KOReader via KSM 8 or via the nickel-koreader switch (after enabling it in KSM).

**Comment by houqp** [comment]
Looks like `koreader.sh` failed at ` cd "${KOREADER_DIR%/*}" && tar xf "${NEWUPDATE}" && mv "${NEWUPDATE}" "${INSTALLED}"   `? Or does KSM 8 launches koreader with its own script?

**Comment by Frenzie** [comment]
This is #1889. Applying the update manually will fix it.

**Comment by m4kh** [comment]
I will try to apply the fix of #1889, as suggested by @Frenzie. However, I thought my current version of KOReader `koreader-nightly-20160315` already is the latest build. So, why does `Check for update` show a newer version in the first place? I downloaded the current version from github and manually installed it by copying/merging the koreader folder in the zip to my device.

**Comment by Frenzie** [comment]
Ah, sorry. I didn't take a close enough look at the version. Serves me
right for using my phone.

**Comment by chrox** [comment]
The OTA nightly builds are updated twice a day automatically while the release packages in the release page from which you can download are updated every one or two weeks because those packages need manual uploading. So most of the time there is newer version in the ota server if you check it.

**Comment by m4kh** [comment]
OK, thanks for the info. I followed @Frenzie's suggestion and manually applied the fix of #1889 (commit b8b0684) in KOReader version `2015110253`. I can confirm that this fixes the issue and the OTA updates are now getting installed after restarting KOReader. Thanks everybody for the help!
