### ISSUE TITLE
Option to turn off Wi-Fi

### ISSUE THREAD

**Issue by m4kh** [koreader/koreader#1908]
* KOReader version: koreader-nightly-20160315
* Device: Kobo Glo HD

#### Issue
There is no option to turn Wi-Fi off after it has been enabled in KOReader. A Wi-Fi menu to turn it on/off might be helpful, maybe even with a Wi-Fi status indicator.

#### Steps to reproduce
I Wi-Fi is off, hit `Check for updates` in the `OTA update` menu. A prompt allows to enable Wi-Fi. Afterwards there is no way to turn it off.

**Comment by KenMaltby** [comment]
There should be a "Network" menu item (under the gear tab/icon of the top menus) It will have a "Wi-Fi connection" that will have a check in front of it, if the Wi-Fi is on.  selecting that will pop up a message box to turn it on or off.

**Comment by m4kh** [comment]
Ah sorry, I somehow didn't see that menu before. Thanks for the hint!
