### ISSUE TITLE
Crash when searching NULL (reproducible)

### ISSUE THREAD

**Issue by pavlukivan** [koreader/koreader#1910]
* KOReader version: 20160315
* Device: Kindle PW2

#### Issue
Crash when searching NULL (log: something like "expected string, found NULL) 

#### Steps to reproduce

Tap at the VERY left (or maybe very right too) of the screen and hold, then drag the finger anywhere else. Then tap search.

**Comment by Frenzie** [comment]
Confirmed. I figure the best fix is probably to prevent the popup from
showing up at all if NULL is selected?

**Comment by pavlukivan** [comment]
or maybe creating search function with NULL, that does nothing

**Comment by houqp** [comment]
Thanks for the report, It's actually a bug in crengine wrapper where it should return `nil`, but instead returns `{}`.
