### ISSUE TITLE
FR: Ability to change dictionary priority

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#1913]
As far as I can see, KOReader now just displays dictionaries in alphabetic order. I think it'd be useful to be able to customize their order, at least set a bilingual/monolingual preference or the default one.

**Comment by chrox** [comment]
You can tap the title bar of the dictionary window to set current dictionary the default one.

**Comment by GeneralFailer** [comment]
Ah, right, this is mentioned in the wiki.
Still, I think it would be very useful to set the dictionary to be the default one for the language with a long tap on the title bar. I doubt that setting on by-document basis would be useful for most people using the dictionary feature. Of course, it can still stay and have a higher priority.

**Comment by houqp** [comment]
Yup, I agree having default setting per language makes sense.
