### ISSUE TITLE
FR: Long press on image provide option to use image as the screensaver image.

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#1914]
- KOReader version: All
- Device:All
#### Issue

Being able to dynamically set an image within a book/document as the screensaver image would come in handy, in several ways.  
1.  I have a number of epubs that are compilations of individual novels merged in caliber. Each novel is treated as a chapter.  Each novel has a cover image.  It would be nice to have the current novel's cover as the suspend image.  
2.  There are often maps or charts it would be good to have a ready reference to.

If there were a long press option, on images, to have the image be the current screensaver image, it would be easy to make such things work.

**Comment by robert00s** [comment]
What about add context button (`<<` and `>>`) with more options?
Normal:
![romeo and juliet - koreader_133](https://user-images.githubusercontent.com/22982594/43047229-79f1769a-8dd4-11e8-8283-66f43452bf33.png)


Extend (after tap on `<<`):
![romeo and juliet - koreader_134](https://user-images.githubusercontent.com/22982594/43047237-89b94972-8dd4-11e8-8df3-3ff7442f27c0.png)

**Comment by poire-z** [comment]
Well, that could do (except we lose the buttons balance/symmetry).

But i'm not that keen on the idea of having "Use as screensaver", that feels like a toy thing like in Windows.
"Extracting the image", because somehow you'd want to have it on the side would feel more serious (one could then use it as screensaver with your new option).
But that's only my opinion :) so, if people really want to play with suspend image, well, ok :)

(An other option would be to override in ImageViewer the long diagonal swipe usually used for taking a screenshot, so it saves the original image instead)

About @KenMaltby original use cases:
The first feel a bit like a rare use case, and would need a manual action on each met cover ("oups, forgot to do that for the past cover, let's go back to it...").
The second is more interesting:

> There are often maps or charts it would be good to have a ready reference to.

Being able to bookmark an image would be nice: it would appear in the bookmarks (and be candidate for `Swipe to latest bookmark`), and when taping/holding on it, would directly launch ImageViewer (?)
(Found you an idea for a 2nd button if you go with `<<` `>>` :)
`>> Bookmark | Screensaver | Close` or `>> Bookmark | Save | Close`

**Comment by KenMaltby** [comment]
I agree that the first example might be rare.  For most cases I was looking at it as having a reference image that was a flick of the power button away and that could be returned to over and over again while going through the book.  Perhaps a bookmark that goes directly to the image displayed and an easy way back to where I was reading, would accomplish the same thing.  Except for my first example I wasn't thinking of book covers, at all.  For most fiction we would be mostly talking about maps, but non-fiction books often include reference type images for many non-text material (charts, graphs, tables, ect...) Being able to designate and enable a quick reference method for selected such image data would come in handy.

**Comment by poire-z** [comment]
I wrote in https://github.com/koreader/koreader/issues/3637#issuecomment-362107711 :
> Long press is currently assigned to refreshing screen (like small diagonal swipe in readers does), all the other gestures are taken for zooming/panning the image.

Except one little known gesture, that is also available in the regular ScreenShoter: two fingers tap in diagonal corners.
I'll look at adding it to ImageViewer: two finger tap > Save image (or if currently panned and zoomed, the current view without the title & buttons) > ConfirmBox("Do you want to set it as screensaver).

**Comment by noembryo** [comment]
>two fingers tap in diagonal corners

Is this something that only the multi-touch enabled readers can do?
Because I think my Glo (original) is single touch only..

**Comment by Frenzie** [comment]
Yup, it'd be a bit hard to do otherwise. ;-D

**Comment by poire-z** [comment]
> Is this something that only the multi-touch enabled readers can do?

Yep :/

> Because I think my Glo (original) is single touch only..

May be we can degenerate this to a single tap in a little area in (some or all?) corner(s) when `not Device:hasMultiTouch() ?` Currently:
Tap outside closes a non-full screen ImageViewer, that I don't remember we use.
Tap on title toggles optional caption.
Tap anywhere toggles bottom button visibility.

**Comment by noembryo** [comment]
What about double tap?
Is there a detection for this?

**Comment by Frenzie** [comment]
You can enable it, but I find it a really annoying delay (because each single tap will have to wait for a little while to determine if maybe it's a double tap).

**Comment by noembryo** [comment]
A, OK, I know this problem..
If it will make the UI less snappy, forget it.

**Comment by noembryo** [comment]
What if the long press opened a popup with options (Refresh, Screenshot, ...)?

**Comment by Frenzie** [comment]
I mean you can enable it right now in taps & gestures to play around with, not as a theoretical code thing. ;-)

![Screenshot_2020-10-02_22-59-40](https://user-images.githubusercontent.com/202757/94969445-0ad98380-0503-11eb-95d0-bf785ef76995.png)

**Comment by noembryo** [comment]
Oups, OK, I did..
But I can't find a "Take a Screenshot" action to assign :o(

**Comment by poire-z** [comment]
> What if the long press opened a popup with options (Refresh, Screenshot, ...)?

I use long press to Refresh, often, I don't want to see a popup (for a Screenshot option I - and I guess most people - will never care about), that I'd have to dismiss (which would need a full refresh after close anyway :)
So, 2 fingers tap + degenerate single tap in a rare corner is the less intrusive _to me_.

Yes, I saw there was no action in dispatcher to take a screenshot.
(And the actions we set in Gesture Manager only work in Reader or FileManager where Reader or FileManager is the top level widget - not when there is another widget on top of them (like a ConfirmBox or ImageViewer).

**Comment by noembryo** [comment]
I agree about the popup, I was just brainstorming :wink: 

The best option for me would be an option to assign what happens when long press.
I can then change it, only in the rare occasions that I need it.

But any other solution will be fine. :smile:

**Comment by NiLuJe** [comment]
My solution is firing up an SSH shell and running fbrab form there.

Oops. :D.

**Comment by noembryo** [comment]
>My solution is firing up an SSH shell and running fbrab from there.

Well, its not that easy to do when you're on a hammock in the middle of nowhere.. :-p

**Comment by poire-z** [comment]
Done in #6745.
@noembryo : if you want to have a try, you can just get https://raw.githubusercontent.com/koreader/koreader/ace14e08e8892a43aafedecbd6a73573527ce335/frontend/ui/widget/imageviewer.lua and replace it on your device.

**Comment by noembryo** [comment]
Check and it works great! :tada: Thanks!
The only thing that remains to be seen is if I will remember it next year when I will need it again.. :thinking:
