### ISSUE TITLE
Koreader don't open an epub file

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1915]
* KOReader version: v2015.11-270-g3f8f759
* Device: Kobo Glo HD

#### Issue
Koreader don't open an epub file from KSM (with the koreader's option: auto-loading the last file opened -> enabled).
Crash.log:
```
./luajit: ./reader.lua:115: attempt to index field 'Screen' (a nil value)
stack traceback:
	./reader.lua:115: in main chunk
	[C]: at 0x0000bea5
```

#### Steps to reproduce
It was working well since this version was released but now when I'm using KSM menu and I try to "load" koreader, it don't open and it crash.

**Comment by djalma2k** [comment]
Ok, I already tried a manual upgrade to v2015.11-275 with same results (same crash.log).
On the other hand, I also tried to change:
settings.reader.lua:
from
`["open_last"] = true,`
to
`["open_last"] = false,`
(cr by vlasovsoft and "nickel" are working with the same epub)

Regards.

**Comment by houqp** [comment]
My bad, i broke it in the last couple commit. You can fix it by changing that line to `Deivce.screen`.

**Comment by houqp** [comment]
You are using night mode right?

**Comment by djalma2k** [comment]
mmm related with night mode


-- night mode
if G_reader_settings:readSetting("night_mode") then
    Device.Screen:toggleNightMode()
end

**Comment by djalma2k** [comment]
yes, im gonna try changing it

**Comment by houqp** [comment]
This should be fixed by https://github.com/koreader/koreader/commit/9a3e262bb3611bf95c6619f143ec3688a5394786.

And yes, I mistakenly committed to master directly again with the stupid github web editor. I promise I won't use that thing again...
