### ISSUE TITLE
Wrong SEARCH_LIBRARY_PATH

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1916]
- KOReader version: koreader-stable-v2015.11
- Device: Kobo Glo HD
#### Issue

With this device I need to force the default search library path to:

defaults.persistent.lua:

```
SEARCH_LIBRARY_PATH = "/mnt/onboard/"
SEARCH_LIBRARY_PATH2 = "/mnt/onboard/"
```

(I don't know if I only need one of them or both.  Although, anyway, all it is working well right now).
#### Steps to reproduce

When I try to search a specific book using calibre's db and koreader shows the results, and then I try to load this book, koreader doesn't find it (wrong path).

PS: I don't know if this is still present in "nightly" versions (I keep the same defaults.persistent.lua file with them).

**Comment by KenMaltby** [comment]
The "metadata.calibre" file is created by calibre and placed in the root of the drive/folder that caliber is directed to.  For instance the "Main" device for Kobo devices is at /mnt/onboard  The drive A (external drive) is at /mnt/sd/.  The search of the calibre installed books on your device makes use of that or those files.

**Comment by djalma2k** [comment]
Yes, ok then I only need 1 of them, but when I only set the 2nd one (SEARCH_LIBRARY_PATH2 = "/mnt/onboard/"), it just doesn't works. 
Anyway, by default calibre and "nickel" copy all the books folders and files in /mnt/onboard (Kobo Glo HD haven't a "external drive"). I'm just saying that koreader should know this and when dectects a Kobo Glo HD set the default path to /mnt/onboard because mostly people have this one by default. 
But this not happens rightnow: Koreader detect the calibre's db, show the results but not open the real files because the default path is /mnt/sd or something like that (I don't remember well because it's a bug that happened to me in Dec-2015).
Regards.
