### ISSUE TITLE
Android: No reader engine for Djvu file

### ISSUE THREAD

**Issue by medwatt** [koreader/koreader#1919]
* KOReader version: koreader-nightly-20160315
* Device: Onyx i86+

#### Issue
I created a similar thread like this the last time mentioning the fact that epubs don't load and I get the error message  "No reader engine for this file". The last update solved this issue. However, DJVU files still don't load and give the same error message.

**Comment by houqp** [comment]
Is Onyx running android? Could you post the crash.log?

**Comment by medwatt** [comment]
@houqp,

I/luajit-launcher(15691): # opening file /mnt/sdcard/Books/DJVU/Ordinary Differential Equations - Tenenbaum, Pollard.djvu

I/luajit-launcher(15691): # cannot open document /mnt/sdcard/Books/DJVU/Ordinary Differential Equations - Tenenbaum, Pollard.djvu frontend/document/djvudocument.lua:26: module 'libs/libkoreader-djvu' not found:

I/luajit-launcher(15691): 	no field package.preload['libs/libkoreader-djvu']

I/luajit-launcher(15691): 	no file 'libs/libkoreader-djvu.lua' (checked with asset loader)

I/luajit-launcher(15691): 	no file 'common/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'rocks/share/lua/5.1/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'frontend/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file '/data/data/org.koreader.launcher/files/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'plugins/evernote.koplugin/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'plugins/zsync.koplugin/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'plugins/statistics.koplugin/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'plugins/calibrecompanion.koplugin/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'plugins/kosync.koplugin/libs/libkoreader-djvu.lua'

I/luajit-launcher(15691): 	no file 'common/libs/libkoreader-djvu.so'

I/luajit-launcher(15691): 	no file 'common/libs/libkoreader-djvu.dll'

I/luajit-launcher(15691): 	no file '/usr/lib/lua/libs/libkoreader-djvu.so'

**Comment by mergen3107** [comment]
People from [4pda](http://4pda.ru/forum/index.php?showtopic=734837) report that djvu's with Russian filenames have this issue of 'no engine' on Android.
Example file is [attached](https://yadi.sk/d/sFrorXNSrxQdX).

On my Kinde Touch however such files are opened correctly.

**Comment by chrox** [comment]
@houqp Is this a "next stable release" work? It's totally new feature as we don't build djvulibre for Android now. I will close this in favor of #1543.

**Comment by houqp** [comment]
Yeah, my bad, I forgot we are not building libdjvu in android.
