### ISSUE TITLE
2-colour cover

### ISSUE THREAD

**Issue by pavlukivan** [koreader/koreader#1920]
* KOReader version: any
* Device: Kindle PW2 (And maybe other e-books, or even all devices)

#### Issue
Cover is only 2 colours - very black and very white, no gray colour. Even if that's not a bug, that's weird.

**Comment by Frenzie** [comment]
Do you perhaps have a picture of how a specific cover looks on your device coupled with its regular color look?

**Comment by houqp** [comment]
Same question. Or it would even better if you can provide us the book. There is no code path in KOReader that does 2 color rendering.

**Comment by chrox** [comment]
Maybe it's related to #1438.

**Comment by pavlukivan** [comment]
Yes, it's copy of #1438 , I didn't noticed it.
