### ISSUE TITLE
Updated russian translation

### ISSUE THREAD

**Issue by pavlukivan** [koreader/koreader#1921]
I don't know how to join KOReader translators' team, but I translated all the remaining strings (it's actually .po file, github doesn't support it):
[ru.txt](https://github.com/koreader/koreader/files/189128/ru.txt)

**Comment by Frenzie** [comment]
Cool, thanks! You can join the KOReader project on Transifex with your GitHub account, but I see you already noticed. I accepted you there. I fear the best way to actually get the translations into KOReader is probably to redo them in the web interface.

**Comment by houqp** [comment]
Thanks @pavlukivan for the help! I have entered the translation from your file to Transifex. Please help review the russian translation there when you have time ;)
