### ISSUE TITLE
[Kindle] cropping in pdf reflow

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1922]
* KOReader version: v2015.11-276-g9a3e262
* Device: Kindle PW3

#### Issue
I'm reading a Chinese pdf book with reflow on. There are places where the text gets cut in reflow mode, but not in non-reflow with auto-cropping/manual cropping/semi-auto-cropping.

#### Screenshots
Reflow
![reader_2016-mar-24_112459](https://cloud.githubusercontent.com/assets/5674597/14051146/fc9e0e36-f27d-11e5-9d03-5ce1b653926f.png)
Non-reflow + auto-cropping
![reader_2016-mar-24_112530](https://cloud.githubusercontent.com/assets/5674597/14051157/0101e27c-f27e-11e5-80f3-14b150b0e6ec.png)
Non-reflow + no-cropping
![reader_2016-mar-24_112508](https://cloud.githubusercontent.com/assets/5674597/14051165/0ec05254-f27e-11e5-84dd-477c9132c41f.png)

I feel that reflow should happen after cropping....

**Comment by chrox** [comment]
Yes, the reflowing is done always after cropping so could make sure you didn't crop too much in the reflow mode? Did you still have this problem with autocrop + reflowing?

**Comment by SsnL** [comment]
Yes, I went back to that page and the problem is still there.

One funny thing though: Starting from reflow and auto-cropping, I turned off reflow, KOReader shows full uncropped page, rather than auto-cropped page. I had to tap on the already selected "auto" in cropping setting to make the cropping happen.

**Comment by SsnL** [comment]
Oh yes, and when I turned off reflow, characters aren't cut. (They are when reflow is on)

**Comment by chrox** [comment]
I still cannot reproduce this. Could you send a copy of that document with the corresponding history file (the lua file in the sdr directory of the document)?

**Comment by chrox** [comment]
No progress, closing this now.
