### ISSUE TITLE
Suggestion: "None" as a cropping option

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1923]
Can we have "None" as a cropping option? 

It was confusing when I opened a pdf for the first time, noticed that cropping was shown in UI as "auto", but the pdf wasn't cropped at all. Sure, tapping on "auto" again activates cropping. But what if I want to disable cropping and don't want to read in scroll mode?

Thanks.

**Comment by Hzj-jie** [comment]
Thank you SsnL, it's a known issue, at least I know it. I will fix it.

**Comment by Frenzie** [comment]
@Hzj-jie I do think it would be better to have more of those options (or all if reasonably possible) in the footer menu because this split is unintuitive.

**Comment by Frenzie** [comment]
Waiting to look into this to prevent conflict with #4580.

**Comment by Frenzie** [comment]
Oh darn, I overlooked #1998. Why is this still open?
