### ISSUE TITLE
[Kindle] No refreshing when exiting KOReader from file manager

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#1924]
* KOReader version: v2015.11-276-g9a3e262
* Device: Kindle PW3

#### Issue
No refreshing when exiting KOReader from file manager

#### Steps to reproduce
1. Open KUAL
2. Start KOReader by "KOReader" -> "Start file manager"
3. Exit KOReader using the menu bar button
4. Noticing that KOReader already exits but screen is not refreshed. i.e. it should show kindle main menu, but actually showing KOReader file manager and behaving like kindle main menu.

**Comment by NiLuJe** [comment]
On which FW version?

**Comment by SsnL** [comment]
5.7.3.1

**Comment by NiLuJe** [comment]
Do you have shell access to your device?

What does
```
printf "%.3s" $(grep '^Kindle 5' /etc/prettyversion.txt 2>&1 | sed -n -r 's/^(Kindle)([[:blank:]]*)([[:digit:].]*)(.*?)$/\3/p' | tr -d '.')
```

returns?

**Comment by SsnL** [comment]
Just realized that this is not just file manager. 
Adding a step "2.5. Open a document" still reproduces this bug. 
Maybe the KUAL extension script?

**Comment by SsnL** [comment]
573

**Comment by NiLuJe** [comment]
Huh.

Will double-check again, but last I checked, I fixed that, and it worked (PW2/5.7.3, not that it should change anything...)

**Comment by NiLuJe** [comment]
Does uncommenting [this line](https://github.com/koreader/koreader/blob/master/platform/kindle/koreader.sh#L311) in koreader/koreader.sh help?

**Comment by SsnL** [comment]
Umm weird enough, I restarted kindle and the problem was gone. Will report back if it appears again.

**Comment by houqp** [comment]
Please reopen this issue if you found a way to reproduce it.

**Comment by GeneralFailer** [comment]
@houqp No, this doesn't work for me. It's also independent from whether a document is opened or not.

**Comment by NiLuJe** [comment]
@GeneralFailer: Same questions as my original queries to @SsnL , please ;).

**Comment by GeneralFailer** [comment]
5.3.7.3 on Kindle Touch. I can't connect to the shell:  `ip addr add 192.168.15.201 dev _interface_ && ssh root@192.168.15.244` returns `ssh: connect to host 192.168.15.244 port 22: Network is unreachable`.

By the way, `authorized_keys2` seems to have been deprecated long time ago, so maybe readme should be edited?

**Comment by NiLuJe** [comment]
@GeneralFailer: Make sure NetworkManager is not crapping on your party and assigning broken IPs to the USB IF. (i.e., mark it as unmanaged in NM; or something).

Thanks for mentioning the readme thing, I have no idea where that originally came from... :?.

FWIW, I can't reproduce this on a PW2.

Random idea: Do you happen have a crazy amount of books and/or collections on your device (on the native system's side, not KOReader's)?

**Comment by NiLuJe** [comment]
Holy crap, I just realized I've been reading @GeneralFailer's report wrong (given the context of the original report). And the fact that 5.3.7 looks very much like 5.7.3 at 5 AM xD.

Sooo, yeah, IIRC, shouldn't happen, so, my previous questions still stand.

In the meantime, I'll charge my K5 and see if I can reproduce...

**Comment by NiLuJe** [comment]
Yup, reproduced. Will fix :).
