### ISSUE TITLE
Koreader does not work on Kobo Touch

### ISSUE THREAD

**Issue by enigma90** [koreader/koreader#1926]
* KOReader version:nightly-20160315 and nightly-20160323
* Device:Kobo Touch 
firmware 3.16 

#### Issue

can't enter koreader. just quits. koreader-nightly-20160227 and earlier versions work just fine.

**Comment by houqp** [comment]
Can you paste the crash log here?

**Comment by enigma90** [comment]
./luajit: ./reader.lua:135: attempt to index field 'fl' (a nil value)
stack traceback:
	./reader.lua:135: in main chunk
	[C]: at 0x0000bea5

**Comment by enigma90** [comment]
btw, that's crash log of nightly-20160323

**Comment by Hzj-jie** [comment]
It should be a defect by commit 08b08d6, a Kobo without front light will be impacted.

**Comment by Frenzie** [comment]
The frontend/device/kobo/device.lua file already has hasFrontlight
definitions, so it should be simple to put in a check of some sort.

**Comment by Hzj-jie** [comment]
Emmm, I think we do not need to change the front light state, if the setting we have got is off, i.e. user may turn on the front light in other system (not nickel, we are syncing configuration with nickel) because the environment is dim.

But anyway, let me fix this crash first.

**Comment by Frenzie** [comment]
You're right, there's no need to mess with anything in that case. Good
point.

**Comment by houqp** [comment]
My bad for not taking this into account :( Thanks @Hzj-jie for fixing it :+1:

**Comment by Frenzie** [comment]
This should be fixed in #1928.
