### ISSUE TITLE
Koreader crashes opening ePub file

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#1931]
* KOReader version: v2015.11-stable
* Device: Kobo Aura H2O

#### Issue
Koreader crashes when opening an epub file with `Floating point exception` in `crash.log`. The epub file is: Quantum Mechanics by Albert Messiah, Dover Pubs, 2014 (2 vols in 1) in epub format. (downloadable from LG). Note that CoolReader opens and reads this file absolutely fine, no problems at all.

#### Steps to reproduce

Open the above-mentioned epub file and observe that Koreader crashes.

**Comment by frankyifei** [comment]
cant find this book

**Comment by houqp** [comment]
Not able to find the book neither. What is LG?

**Comment by tigran123** [comment]
Oh, come on, guys... Which planet are you from? :)
LG stands for Library Genesis, libgen.io

**Comment by tigran123** [comment]
http://libgen.io/book/index.php?md5=F5A01F7C7518D2104774DBE7337B9D7C

**Comment by KenMaltby** [comment]
It doesn't open in Sergey's Coolreader port either.  It takes ~28 seconds to crash in KOReader.  After the attempts, it took longer than normal to reload my current read, as well.

**Comment by tigran123** [comment]
@KenMaltby It opens and reads perfectly here. Which version of CoolReader are you using? I am using 2016.03:

``
$ l pbchess-2016.03_kobo.zip 
-rw-r----- 1 tigran tigran 21145340 Mar 22 06:44 pbchess-2016.03_kobo.zip
$ md5sum pbchess-2016.03_kobo.zip 
ceebb773b643a6946ca8732f1e79271f  pbchess-2016.03_kobo.zip
``

**Comment by frankyifei** [comment]
can you guys share this book

**Comment by houqp** [comment]
http://libgen.io/book/index.php?md5=F5A01F7C7518D2104774DBE7337B9D7C。

Not able to reproduce in emulator, might be an ARM specific bug.

**Comment by tigran123** [comment]
@houqp Yes, probably, as the error suggests as well (unless it is something trivial like `1/0` the way FPU raises exception may be arch-specific)

**Comment by frankyifei** [comment]
I can open it on my kindle pw1. so it should be a kobo thing. or maybe it has been fixed after last stable version.

**Comment by houqp** [comment]
Might be a hard-float related issue then. My dev laptop died two days ago. I am waiting for system76 to ship my new laptop ATM :-/

**Comment by NiLuJe** [comment]
I'd say "try my builds" to chekc if it's a TC issue, but CRe is broken in them right now, so... :D.

**Comment by tigran123** [comment]
Re-tested with v2015.11-549 and it works absolutely fine, so I am closing the issue. I now have a doubt as to whether I should switch to Koreader even for ebooks as well, not just PDF and DjVu. Normally I use CoolReader for ebooks (fb2 and epub), but since Koreader now handles files of this complexity, perhaps it is worth switching to it for ebooks.

The other area where CoolReader felt superior was suspend and wakeup. I never had problems with it, but in Koreader I had a couple of crashes when the device was left in suspended state inside Koreader for too long (1-2 days). And in other cases, the battery seems to have been draining much faster than when sleeping in CoolReader or vlasovsoft launcher. Also, there were problems with wakeup, i.e. it was very slow and looked like "hang", but in CoolReader it is always instant.

**Comment by tigran123** [comment]
Actually, I said "it works absolutely fine", but there are still a few problems with it:

1. It opens the epub file for the first time slower than CoolReader (92 seconds vs 80 seconds).

2. The second open (and all subsequent ones) are also slower than in CoolReader (90 seconds vs 35 seconds).

3. Switching to the book from History is also much slower than in CoolReader (80 seconds vs 25 seconds).

It is quite annoying to have to wait one and a half minute to switch to this book. Even CoolReader's 20-30 seconds I considered quite slow...

**Comment by chrox** [comment]
That is a severe problem and needs to be fixed in the next stable release. I also encountered this issue, sounds like the cache is invalidated every time the same document is opened. It's probably because we try to re-render the document even after the document is rendered from cache, for example by applying additional settings like hyphenation or floating punctuation. Any way this issue needs to be addressed. Could you open a new issue for it?

**Comment by tigran123** [comment]
Ok, I will do that,
