### ISSUE TITLE
FR - two lines progress bar

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#1933]
- KOReader version: ALL
- Device: ALL

I already asked if we could get two lines for lower status bar, but in a way it is OK if it doesn't happen.

The reason I asked for this is that we have more and more text options to add in status bar, and being statistics freak (is there a word for it?), I like to have them all turned all at the same time. With having all of them turned on, graphic progress bar becomes shorter and shorter.

And I found progress bar very useful to easily see where in the book we are, including information about chapters. So I need to decide, should I use all textual statistics, or have much smaller (shorter) progress bar.

Anyway, either having lower progress bar in second line along whole screen length or using upper one would be just fine with me.

But, upper progress bar now isn't same as lower. It's just one very thin line, or a bit thicker, without information about chapters (or I'm not able to discern them).

So, please, could you make upper graphic progress bar similar to lower one? Coding wise, you already have all the code you need, you just need to implement it. It would be great help. Or, even more preferably would be adding second line in lower position just for progress bar.

**Comment by KenMaltby** [comment]
Perhaps it would be less impact on the normal reading experience, if there were a pop-up info box of maybe four lines size. It might drop back down after a certain amount of time after the finger is lifted.

**Comment by AlanSP1** [comment]
Well, if you ask me, I prefer to see that info all the time, without any special action from my side, like pointing on same screen position.

I'd like to see it all the time, if it is possible.

**Comment by houqp** [comment]
Sounds like a simple task. Now only if someone can tell me how to enable the upper progress bar... When I read, I usually disable everything so I can focus on the text. I don't even know we have a upper progress bar support...

**Comment by KenMaltby** [comment]
It's the bottom reader menu gear icon "Full" progress bar.

**Comment by houqp** [comment]
Oh, i see. That's the one rendered by crengine, which is completely out of
our control. If we want to change its styling, we will need to change
crengine's code instead...

**Comment by AlanSP1** [comment]
If it is a problem, maybe you could put lower progress bar in separate line from textual statistics info, so it is wide as screen. I would even prefer it this way.

**Comment by AlanSP1** [comment]
I already opened similar issue, just to remind: https://github.com/koreader/koreader/issues/1724

It was closed with reason that lower status bar should be as small as possible, but if it is possible to make it into two lines (one for graphic progress bar, one for textual statistics), with option to choose if it is one or two lines, this would be really great for people like myself who like to have statistics all the time. And now we have a lot of statistics available, which is really, really great, but we are starting to lack space in one line of lower status bar.

Well, @Yaretzki also liked that idea.

**Comment by houqp** [comment]
I am with chrox with on this matter. I would prefer the two lines status bar to be implemented as a plugin that's not on by default.

**Comment by AlanSP1** [comment]
Of course, I don't think it need to be on by default, that's the reason why I suggested option (in status bar menu), to have second line. And if we choose to have second line, it becomes graphic progress bar, living text in first line (I would like to put progress bar in upper line, textual info in lower line, where it already is).

Some people like to cycle through selected statistics, but some prefer to have them at the same time. And, having all of them on makes status bar pretty full. I personally like that, having all that info at the same time, but also I'd like graphic status bar a bit larger.

With time there can be even some additional textual data added, not that at the moment I could think of, but it can happen. With putting graphic progress bar in second line we can have all that info comfortably shown at the same time.

I really would love that feature. As an option, of course, not forcing anyone to that arrangement as not all of us like same things.

**Comment by robert00s** [comment]
Maybe something like that:

![1](https://user-images.githubusercontent.com/22982594/41307965-ede32dce-6e7a-11e8-8bd7-2eac8256518c.png)
![2](https://user-images.githubusercontent.com/22982594/41307971-f06450dc-6e7a-11e8-8cdd-c6a6a33ce1de.png)

**Comment by AlanSP1** [comment]
Oh, you're using upper and lower "lines" (well, not sure how to call it, maybe spaces is better term?).

In my original idea I thought it would be all in same area, i.e. in lower space, as two lines, with reading progress bar with chapters in one and other statistical data in other. I thought about it in this way as it would be more logical to look only in one way, i.e. down.

But, as I'm not sure how it can be programmed, and how complex it could be, this solution with using upper and lower space is also much better.

Would be able to define what goes in which space? In my original idea, only graphical progress bar would be in one space, all other used info would go in other space, so it would need some special coding, just selecting which info we would like to use, but I see you placed some data in one space and rest in other.

Anyway, thanks for taking interest in this idea! 👍

**Comment by poire-z** [comment]
The full status bar (at top) is indeed drawn by crengine (I guess that's the only status bar in CoolReader, and we kept it as an option as it was already there).
If you want to make a top status bar drawn by KOReader (whether we keep or not the crengine _full_ status bar), I think you're in for a lot of work (a new readerheader.lua?), with many other things to take care of (readerview, deciding what height to give to the engines for their drawing, the overlap stuff...), and that would scare me :) Not talking about how to configure all that, what to put on top, what on bottom.

May be it would be easier and safer to make optionally the footer multi-lines: the progress bar on top, that would act as a kind of separator, and the other textual items below?
(I personally don't like having something at top, and I hacked my readerfooter.lua to order things to my liking - I don't mind the smaller progress bar.)

**Comment by AlanSP1** [comment]
And @poire-z suggestions look great for me, progress bar in one line, all other data below, especially if it is easier task to achieve. And of course, setting for those that don't want to use it (by default, it can be left as one line, to be compatible with older versions).
