### ISSUE TITLE
Screen not redrawn at exit

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#1934]
- KOReader version:
  v2015.11-stable
- Device:
  Kindle 7th Generation, firmware 5.7.3
  #### Issue
  After exiting koreader screen is not redrawn. 
  #### Steps to reproduce
  Open a PDF file in koreader, then select home icon from menu. The document text remains on the screen. After turning screensaver on and off with the power button kindle home screen is displayed.

**Comment by chrox** [comment]
How did you launch Koreader, via KPVBooklet or KUAL?

**Comment by ilyats** [comment]
Now I am using KPVBooklet and the problem exists. I tried now KUAL ("Open the last document") and the problem occurs with it as well.

**Comment by ilyats** [comment]
Problem does not seem to happen with Koreader v2015.11-877-ga2fac0 and firmware 5.8.2. Still happened with v2015.11-876

**Comment by ilyats** [comment]
I was to early to close this the problem still exists.

**Comment by ilyats** [comment]
@robert00s with Special Offers

**Comment by robert00s** [comment]
@ilyats 
I have prepared patch for it. It should fix it. See #3168.
Please check it out and let me know if it helped.

**Comment by ilyats** [comment]
@robert00s now it does redraw, albeit sometimes with a a small (<1s) delay.
