### ISSUE TITLE
Screensaver does not wait for swiping finger.

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#1935]
* KOReader version:
v2015.11-stable
* Device:
Kindle 7th Generation, firmware 5.7.3 (with ads displayed on screensaver) 
#### Issue
When screensaver is displayed over koreader, pushing power button makes it disappear
 #### Steps to reproduce
Open a PDF file in koreader, wait until screensaver is displayed, push power button. Writing appears inviting to swipe finger to end screensaver, then screensaver disappears. When screensaver is displayed over Kindle interface screen or its native bookreader app, it does wait for swiping finger.

**Comment by chrox** [comment]
This behavior is expected. We don't need to do exactly the same way as the native system does. Isn't it better to save a swiping to get out of the screensaver?
