### ISSUE TITLE
FR: An option to force margins and line spacing (epub):

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#1936]
- KOReader version: All
- Device: All
#### Issue

I think that an option, (a checkbox or a mark for example), to force margins and/or line spacing to selected/default ones in epub files with embedded styles would be very useful.

Some books come with predefined margins that are not interesting for a particular device. 
And totally disabling the embedded styles (or directly modifying the epub file), it seems to me an extreme solution when you could try to easily set the reader with a new parameter...

Regards.

**Comment by djalma2k** [comment]
A picture is worth a thousand words:

- **Embedded styles (on)** --> bad margins, good "styles" ;) :
![styles_on_1](https://cloud.githubusercontent.com/assets/17313916/14184712/ca425cbe-f776-11e5-97d8-525ff2eb1177.png)
![styles_on_2](https://cloud.githubusercontent.com/assets/17313916/14184723/cf7338d4-f776-11e5-88b2-885438fc3d5b.png)

- **Embedded styles (off)** --> good margins, poor "styles" :P :

 ![styles_off](https://cloud.githubusercontent.com/assets/17313916/14184750/09838a24-f777-11e5-8647-38d53a4291ca.png)


A simple intermediate solution would be desirable.

Regards.

**Comment by KenMaltby** [comment]
With embedded styles off, the styles that KOReader has for your selection or one you add or modify, might provide what you want.

**Comment by djalma2k** [comment]
@KenMaltby I don't totally understand what you are trying to say to me: With embedded styles off, the koreader ones has all the embedded typography off also ( and I don't want it :) ); and add or modify book by book... in this case I prefer to do it with a properly configured calibre output plugin... 
Anyway, I'm gonna try to explain myself a little bit better:
All I want is bypass some parameters locked in some epub files in an easy way, for example in the previous book, in the **style.css** you could find the following lines:
> body { font-family: "Times New Roman", Times, serif; **margin:1em**; }
>         h1, h2, h3, h4, h5, h6 { text-align:center; margin-top:35%; }
>                 h1 { font-size:2em; }
>                 h2 { font-size:1.8em; }
>                 h3 { font-size:1.6em; }
>                 h4 { font-size:1.4em; }
>                 h5 { font-size:1.3em; }
>                 h6 { font-size:1.2em; }
>         p { text-align:justify; margin:0; text-indent:1.5em; line-height:1.3em; }
> 
I could modify the epub file directly or with sigil, calibre (with an output plugin), etc...but "nickel" for example, let me choose a more adjusted margin than koreader with "styles" on.
Regards.

**Comment by KenMaltby** [comment]
I am referring to the .css files in the "Set render style" menu option.  They are located in the koreader/data/ directory. Since you would be applying it last, in the cascade, it should override earlier css.  (The ebook maker can prevent a change for some settings, in which case you may need to use the "clear all external styles" before selecting yours.)

**Comment by poire-z** [comment]
Unlocking margin, line-height, fonts is now possible with Style tweaks, see #3944.
