### ISSUE TITLE
Bug: The first highlight won't disappear after page turns.

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1944]
* KOReader version: koreader-kobo-arm-linux-gnueabihf-v2015.11-304-g3884266
* Device: Kobo Aura HD

#### Issue
The first highlight of the book does not disappear even after page tunes. The highlight is also clickable.
This issue happens on some certain formats of files, as far as I can tell, text file is impacted. And it's device independent.

#### Steps to reproduce
Open a book, choose several words or characters, click highlight, then turn to next page.

Expected behavior is, the highlight disappears on the next or previous page.
Real behavior is, the highlight is always there. It would disappear after reopening the file.

Screenshots,
The first highlight, https://raw.githubusercontent.com/Hzj-jie/files/master/koreader/b1944/first.png
It impacts the second page, https://raw.githubusercontent.com/Hzj-jie/files/master/koreader/b1944/second.png

**Comment by Hzj-jie** [comment]
With some initial investigation, ReaderView:drawXPointerSavedHighlight may have some issue. I am continually working on it.

**Comment by houqp** [comment]
Thanks for looking into it :) It looks like a bug in CREngine or cre.cpp, which causes `getWordBoxesFromPositions` in cre.cpp to return invalid data. If the highlighted xpointers are not visible in current page, `getWordBoxesFromPositions` should return something that's outside of the current screen.

Also I feel like the way we are checking for highlight is inefficient and should be better optimized. I am still  waiting for my new laptop to arrive ;P I will join the bug hunting next week with you if you get stuck somewhere.

**Comment by Hzj-jie** [comment]
Yes, some code in CREngine are suspicious. But how do we cooperate with CREngine? It's even not hosted on github. Should we just make change in https://github.com/koreader/crengine/, and push back later?

**Comment by houqp** [comment]
We tried sending our patches to upstream: https://sourceforge.net/p/crengine/crengine/merge-requests. But looks like buggins does not have time reviewing them.

For now, let's put our own changes into koreader/crengine. We are basically forking crengine now. I hope one day we can merge back to upstream, but that will take a lot of effort.

**Comment by Hzj-jie** [comment]
I believe this bug has been fixed. I have not reproduced it in recent versions.
