### ISSUE TITLE
FR: The keyboard is too small on Kobo Aura HD

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1945]
* KOReader version: koreader-kobo-arm-linux-gnueabihf-v2015.11-304-g3884266
* Device: Kobo Aura HD

#### Issue
The keyboard covers only one fifth of the entire screen, and it's pretty hard to click keys.
I have not tried koreader on other devices, but at least we can tune it a little bit larger on Kobo Aura HD.

#### Steps to reproduce
Use any feature that triggers a keyboard input.

**Comment by houqp** [comment]
This is due to `ui/widget/virtualkeyboard.lua` is using raw pixel unit instead of calling `scaleBySize`. Can you try running all size variables through `scaleBySize` to see if it helps? For example, `width` and `height` should definitely be adapted by `scaleBySize`.

**Comment by Frenzie** [comment]
I think it's good on the similarly sized H2O, unless it changed recently.

**Comment by KenMaltby** [comment]
It seems very functional, to me, on my AuraHD.  It could be larger, for those uses I checked, there was room.  It is not too small for me, but that could be subjective, functionally I have no problem poking in text.  No matter how big you were to make it I couldn't actually type on such a keyboard.
