### ISSUE TITLE
Kindle toggle frontlight does not reenable frontlight

### ISSUE THREAD

**Issue by hcs64** [koreader/koreader#1960]
* KOReader version: v2015.11-318-g8c4c274
* Device: Kindle Paperwhite 2

#### Issue
On the Frontlight level dialog, pressing "Toggle" will turn off the frontlight if it is on, but pressing it again does not turn the frontlight back on. It is possible to turn it on again only by entering a new brightness level (if it is the same as the previous level nothing happens, even if nothing is currently shown in the text box) and pressing "Apply".

#### Steps to reproduce
- Open frontlight level dialog when frontlight was already on
- Press "Toggle", frontllight turns off
- Press "Toggle" again, frontlight remains off

**Comment by hcs64** [comment]
This behavior appears to be due to 8b7658b8cd9a9754ba66d959274190daddebb25f which [added](https://github.com/koreader/koreader/commit/8b7658b8cd9a9754ba66d959274190daddebb25f#diff-d832f4212dd6340f5a670645c54da2daR60)
```if intensity == self.fl_intensity then return end```
to the beginning of `BasePowerD:setIntensity`. Commenting out this early exit fixes the issue for me.

Since `KindlePowerD:toggleFrontlight` reenables the frontlight with `self:setIntensity(self.fl_intensity)` (see [device/kindle/powerd.lua](https://github.com/koreader/koreader/blob/8c4c274e7bac0059def197073b4ff3bc5cfd1ec9/frontend/device/kindle/powerd.lua#L30)), the addition of this check makes the reenable do nothing.

I don't want to insist that the "don't re-set intensity" check should be removed, as I don't understand why it was added. Instead for the toggle we could save intensity to a temp, set intensity to 0, then set it back to the temp, but I don't know if this could be problematic.

**Comment by NiLuJe** [comment]
AFAICT your hunch sounds solid, I don't *think* killing that check would hurt...

@houqp?

**Comment by houqp** [comment]
Good catch, I forgot to check other models during the refactoring. @NiLuJe , I commented in your PR.
