### ISSUE TITLE
Kobo Mini doesn't start after update v2015.11-253.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#1961]
* KOReader version: 11-253 and next ones.
* Device: Kobo Mini

#### Issue: KOReader doesn't start after update OTA or manual update. Last version that works is v2015.11-175.
Tried with fmon and KSM8

crash.log:
**./luajit: ./reader.lua:136: attempt to index field 'fl' (a nil value)
stack traceback:
./reader.lua:136: in main chunk
[C]: at 0x0000bea5**

**Comment by NiLuJe** [comment]
One more instance of OO breaking my brain, and Lua syntax not helping, my bad ;).

**Comment by houqp** [comment]
Ha, nice. As a side note, I tried to keep the naming consistent across the code base, i.e. lower_case for variable and camelCase for functions :)

**Comment by NiLuJe** [comment]
Good to know, thanks :).
