### ISSUE TITLE
FR: Enable Kobo screen saver and auto stretch

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1968]
* KOReader version: Up to v2015.11-320-gccd72a8
* Device: Kobo Aura HD

#### Issue
Kobo (and also pocketbook) does not have a default screen saver, so screensaver.lua will be involved, but there is no default setting for screensaver folders. So we can use only book cover image or 'suspend' message.
Also, after enabling screensaver folder, if the image has a different width / height ratio than the screen, it would be stretched badly.

#### Steps to reproduce

So I plan to enable screensaver images first, and update stretching logic to support both book cover image and screensaver images.

**Comment by KenMaltby** [comment]
There is a "screensaver"/suspend image that the user can supply and specify.  If a folder is specified the suspend will randomly select from image files in the folder.

If you mean that there is no default image(s) provided, at a default location, that is true.  The "Suspend" message box only comes into play if none of the other options are available.

**Comment by Hzj-jie** [comment]
Yes, I mean the feature is not turned on by default.

**Comment by Hzj-jie** [comment]
Done.
