### ISSUE TITLE
 kingu (Allan Nordhøy) made a norwegian translation of koreader

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#1971]
This morning my inbox was flooded by emails from Transifex. Apparently Kingu has made a Norwegian translation. I have send him a thank you note, but I can do little about these issues as I cannot speak or write Norwegian. 

He has already collected a flood of manager roles on Transifex, so I don't know how he will maintain them in the future when he has a paid job. Could someone with more access (@houqp) help him further along?

**Comment by houqp** [comment]
I have added him as a maintainer :)
