### ISSUE TITLE
"Rate Book" mistakenly popup

### ISSUE THREAD

**Issue by N46AN** [koreader/koreader#1975]
* KOReader version: kindle-arm-linux-gnueabi-v2015.11-318-g8c4c274
* Device: Kindle PW3

#### Issue
When reading this file: http://www.tldp.org/HOWTO/text/TkRat
The "Rate and Comment" page mistakenly popup multiple times as I tap for next page.

#### Steps to reproduce
- Download http://www.tldp.org/HOWTO/text/TkRat as tkrat.txt
- Open tkrat.txt in koreader
- Tap for next page several times, the "Rate and Comment" page will appear several times

**Comment by KenMaltby** [comment]
I wonder if it is being seen as a single page document, and the next page goes to the page presented at the end of reading the "book"?

**Comment by NiLuJe** [comment]
I've seen that happen too (that was on a chapter break, for my part).

**Comment by houqp** [comment]
Looks like edge cases that got missed in https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerrolling.lua#L380. I will take a look.

**Comment by frankyifei** [comment]
I'm also going to make complain about this. It looks like it can not determine the end of the book.  I noticed this usually happens at end of each html inside Epub files.
Sometimes it even caused crash Like this. When it crashes, I have to clear the .sdr folder and delete history file to open the book.
`./luajit: frontend/ui/widget/progresswidget.lua:74: attempt to perform arithmetic on field 'last' (a nil value)`
here is a book which has many html files.
[Zai Jian Zhu Zhong Fa Xian Meng - An Teng Zhong Xiong.zip](https://github.com/koreader/koreader/files/225201/Zai.Jian.Zhu.Zhong.Fa.Xian.Meng.-.An.Teng.Zhong.Xiong.zip)

Could you add an option to disable the rate book function? It is not so useful in my opinion.

**Comment by houqp** [comment]
I did suggest we keep the reader core small and implement status page as a plugin. But it was not a triva task so it is merged as part of the core. Turning it into a pluggable module will be a bigger project. Let's first focus on fixing the current bugs first. Now that our master branch is back to a healthy state, I will have time to look into it tomorrow.

**Comment by N46AN** [comment]
Thanks for taking time to look into this issue! The core+plugin model seems like a good choice.
