### ISSUE TITLE
FR: add more options in Line Spacing & Margin

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#1978]
add more options in Line Spaceing & Margin,or maybe can using decreaser & increase options.
this will be great!

**Comment by N46AN** [comment]
For a temporary wordaround, use a custom css file.

**Comment by houqp** [comment]
+1 on what @N46AN said. We are mostly working on bug fixes so we can get the next stable release as soon as possible. Therefore, this issue will not have a high priority unless someone volunteers to work on it. Pull requests welcome ;)

**Comment by gerroon** [comment]
Css wont do much for reflowed Pdfs, so it would be nice if we have adjustable settings.

**Comment by seacatwu** [comment]
Expecting :)

**Comment by robert00s** [comment]
I think, is done in #4785 and #4691 so should be available in 2019.04.

**Comment by Frenzie** [comment]
Thanks for the reminder, closing this now.
