### ISSUE TITLE
progress window shows very large book cover

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#1979]
* KOReader version: latest version
* Device: emulator

#### Issue
![reader_2016-apr-19_235803](https://cloud.githubusercontent.com/assets/8104251/14642772/e74734ec-068a-11e6-8dc0-895e662a17f8.png)

#### Steps to reproduce
open any book

**Comment by KenMaltby** [comment]
"Book status" normal on my Kobo AuraHD with v2015.11-330.

**Comment by frankyifei** [comment]
a recent change in imagewidget.lua caused this.
