### ISSUE TITLE
Kobo Aura HD affected by magnet

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#1981]
* KOReader version: Up to v2015.11-351-gafeefe8
* Device: Kobo Aura HD

#### Issue
This is not a KOReader issue, but Kobo Aura HD has magnetic cover detector. The detector seems too sensitive, so moving the ereader around some speakers or digital devices can trigger the suspend and resume.

#### Steps to reproduce
A video @ https://raw.githubusercontent.com/Hzj-jie/files/master/koreader/b1981/VID_20160419_143144.mp4

So I plan to add an advanced configuration to disable magnetic cover detector, i.e. ignore Power_SleepCover key code if we actively set the setting.

**Comment by NiLuJe** [comment]
Remind me to look into it on the Kindle side of things when you're done, because this has come up before, but it had completely slipped my mind ;).

**Comment by KenMaltby** [comment]
This might jog a memory; http://www.mobileread.com/forums/showpost.php?p=3205282&postcount=2480

**Comment by Hzj-jie** [comment]
Done
