### ISSUE TITLE
Current directory value is lost when switching books via History

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#1985]
* KOReader version: 2015-stable
* Device: Kobo Aura H2O

#### Issue
When selecting a book via History the File Manager should switch the current directory to the one corresponding to the book being opened. In the old versions of Koreader this worked fine, but now the current directory is some random useless value (presumably the last directory visited by File Manager). This feature was very useful because while switching, for example, from reading a book on Quantum Field Theory to a book on Philosophy I would like the File Manager to point to the vicinity of the philosophy book rather than the physics one. Otherwise, if one wants to open another related book, one has to manually walk the rather long paths from `/mnt/sd/.Books/Science/Physics/Theoretical-Physics/Modern/Quantum-Field-Theory/` to `/mnt/sd/.Books/Philosophy/Mystics/Rosicrucian/Max-Hendel/`

#### Steps to reproduce
Open a book in Koreader, then open a book in a different directory. Now go to File Manager and notices that the current directory is not the one corresponding to the book opened last.

**Comment by NiLuJe** [comment]
Does this still happen with current OTAs?

**Comment by KenMaltby** [comment]
It looks that way with v2015.11-358.  For me the first switch returned to that book's File Manager page/directory bur subsequent switching settled on one File Manager location irrespective of the current book.

**Comment by tigran123** [comment]
Btw, I should add that the behaviour I expect as correct is also the behaviour of CoolReader. That is in CoolReader, when you go to "Recent books" and select the icon on the left which invokes the "Open File" dialog, the current directory is positioned to the book currently selected in the "Recent books" list (you don't have to open it, just selecting it in the "Recent books" list is enough).
