### ISSUE TITLE
Cannot turn FrontLight back on after 'toggle FL'

### ISSUE THREAD

**Issue by N46AN** [koreader/koreader#1989]
* KOReader version: kindle-arm-linux-gnueabi-v2015.11-318-g8c4c274
* Device: Kindle PW3 5.6.5

#### Issue
Cannot turn front light back on by entering a value after 'toggle frontlight'.

#### Steps to reproduce
- Open koreader with FL on;
- "Toggle FL", FL will go off;
- Enter FL value >0, "Apply" or "OK", FL does not turn back on.

- Expected Behaviour: FL should turn on at given value.

**Comment by NiLuJe** [comment]
Should already be fixed in more recent OTAs.

**Comment by N46AN** [comment]
@NiLuJe Sorry for the duplicate issue! I've updated to the lastest dev branch and I can confirm this issue is fixed, along with #1975 .
Thank you all!
