### ISSUE TITLE
FL turn back on upon wakeup after "Toggle FL"

### ISSUE THREAD

**Issue by N46AN** [koreader/koreader#1991]
* KOReader version: v2015.11-371-g24a30cb
* Device: Kindle PW3 5.6.5

#### Issue
After turning off FL by "Toggle FL" and then suspend the device, FL will turn back on upon wakeup

#### Steps to reproduce
- Open koreader with FL on
- "Toggle FL", FL will go off
- Press power button, the device goes into suspend
- Press power button again, the device wakes up, FL turns back on.

Expected Behaviour: FL should remain off.

**Comment by houqp** [comment]
Good catch... We need to do the same thing we did in kobo powerd, using  is_fl_on to keep track of the on/off state..

**Comment by houqp** [comment]
Oh wait, actually frontlight toggle in suspend/resume should be managed by the kindle system, not us. @N46AN did this work for the old version you have tried before?

**Comment by chrox** [comment]
I'm afraid it's not controlled by us. And I suggest that we don't interfere too much with the underlying hardware and power management on Kindle, after all Kindle does a good job on this for third party applications.

**Comment by N46AN** [comment]
@chrox @houqp Sorry for the late response on this. But I don't quite understand the logic in this: if I execute 'lipc-set-prop -i com.lab126.powerd flIntensity 0' as user 'framework', the front light off status will survive a suspend/resume. 
And from a users point of view, how can I expect the light to turn back on after I've explicitly told it to be off?

Thanks for your attention!

**Comment by N46AN** [comment]
Update: 
I looked through the code at fronend/device/kindle/powerd.lua, changed the function KindlePowerD:toggleFrontlight() to:
```
function KindlePowerD:toggleFrontlight()
    local sysint = self:read_int_file(self.fl_intensity_file)
    if sysint == 1 then
        self:setIntensityHW()
    else
        os.execute("/usr/bin/lipc-set-prop -i com.lab126.powerd flIntensity 0")
    end
```
Then the front light off status will survive a suspend/resume.
So echoing values is different from setting it via lipc?

**Comment by houqp** [comment]
I think it's because writing directly to a file bypassed the kindle system, so system thought the light is still on and therefore turned it back on after resume. But I am surprised that using lipc-set-prod works for you because the comment said it will instead set it to 1. @NiLuJe perhaps the behavior is different for different models?

**Comment by NiLuJe** [comment]
Actually seeing the difference between 1/0 requires a pitch black room, so, maybe that?

Because that behaviors seems to have been confirmed multiples times on multiples devices on MR: ```lipc-set-prop -i com.lab126.powerd flIntensity 0```, then cat the actual sysfs entry (whichever it is on the specific device), and, blam, it's actually set to 1, not 0 ;).

**Comment by N46AN** [comment]
@houqp @NiLuJe 

I've verified this problem has nothing to do with koreader. But changing the method in controlling the FL could indeed remedy this.

What I've done:
Initial status : FL level = 11
1. Exec echo -n 0 > /sys/class/backlight/max77696-bl/brightness, FL level = 0
2. Press power button, device sleeps.
3. Press power button, device resumes. FL level = 11

4. Exec /usr/bin/lipc-set-prop -i com.lab126.powerd flIntensity 0, FL level = 1
5. Press power button, device sleeps.
6. Press power button, device resumes. FL level remains 1.

Hence:
Consider that FL level 1 and 0 has no practical difference, should we consider changing function KindlePowerD:toggleFrontlight() as descibed above?

**Comment by NiLuJe** [comment]
Except there is a practical difference between level 1 and 0. It's *very, very, very, very, very* slightly still on (as can be seen in a pitch black room).

**Comment by NiLuJe** [comment]
Crappy idea: do both?

i.e., lipc first, then ninja it via sysfs.

**Comment by N46AN** [comment]
@NiLuJe 
```
i.e., lipc first, then ninja it via sysfs.
```
IMHO this is a pretty good idea.
Although after resuming FL would be back at level 1, it still saves a little bit more energy. :-)

```
My only real concern would be to make sure it's always really 0 when asleep.
```
I've yet to find a situation in which FL is not turned off while sleeping.  :-D

**Comment by houqp** [comment]
probably also need to make sure when it resumes, the level is at 0 instead of 1.

**Comment by N46AN** [comment]
@houqp 
When it resumes, the level is always the previous level set by lipc.
Hence:
1. /usr/bin/lipc-set-prop -i com.lab126.powerd flIntensity 0 (NOTE: asking lipc to set it to 0 would in fact set it to 1)
2. echo -n 0 > /sys/class/backlight/max77696-bl/brightness
3. suspend
4. resume, level will be 1.
