### ISSUE TITLE
Physical buttons(prev, next) don't work for "page crop" 

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#2003]
- KOReader version: 2015.11-175
- Device:pocketbook touch lux 
#### Issue

This is similar to the https://github.com/koreader/koreader/issues/1999 
So maybe also just additional  "event listener"  is needed? 

When using "page crop" set to "manual" or "semi-manual" can't change to next or previous page to see if current  selected crop area  is also valid for next /prev page. 
(sometimes the odd and even pages have different margins) and page crop set for one page can cut words on next page.  
#### Steps to reproduce

Open book, select koreader menu, choose "page crop", select "manual" or "semi-manual", press next or prev button on device - nothing happens.

**Comment by houqp** [comment]
Yep, you will have to manually flip to next page and do the corp action again for now. I will mark this as a feature request.

**Comment by robert00s** [comment]
@mwozny123 
Please look at #6091 . Is it that you wanted? :)

**Comment by mwoz123** [comment]
Thanks a lot :) pozdrawiam :)
