### ISSUE TITLE
Cannot launch Koreader on kobo Touch 2.0

### ISSUE THREAD

**Issue by GuyDeLaCombe** [koreader/koreader#2005]
* KOReader version: (1) koreader-nightly-20160427 and (2) koreader-stable-v2015.11 
* Device: kobo touch 2.0

#### Issue

I tried the two methods listed [here](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices) 

With KSM 8 with version (1) and (2) (with factory reset in-between) : 
The star menu launch correctly but when I select Koreader, it just selects the line and come back to the start menu home page. Other things work correctly, I can launch the usual Kobo soft and configure stuff into start menu. I tried to add pbchess but it freeze when ask to choose the language. 

With Filemonitor 
It tried with factory reset first and when clicking on the icon, it just goes back to the main menu of the Kobo soft and the same bug comes with pbchess.

**Comment by houqp** [comment]
Hi @GuyDeLaCombe ,

You should be able to find a file named crash.log in koreader folder in this case. Can you paste its content here?

**Comment by GuyDeLaCombe** [comment]
Hi @houqp 

Yes, there is one in Koreader folder : 

> ./luajit: frontend/device/kobo/device.lua:211: unrecognized Kobo model pika
> stack traceback:
> 	[C]: in function 'error'
> 	frontend/device/kobo/device.lua:211: in main chunk
> 	[C]: in function 'probeDevice'
> 	frontend/device.lua:38: in main chunk
> 	[C]: in function 'require'
> 	frontend/ui/uimanager.lua:1: in main chunk
> 	[C]: in function 'require'
> 	./reader.lua:96: in main chunk
> 	[C]: at 0x0000bea5
 
and no crash.log in the vlasovsoft folder.
Thanks.

**Comment by NiLuJe** [comment]
Huh. Yup, we completely forgot to support a 6 months-old device :D. Oops.

Do you happen to have shell access to it (this might make things easier in case the "just wing it" approach fails)?

**Comment by NiLuJe** [comment]
@GuyDeLaCombe: See if bdda4e5eef4134de1fa97d3e8448afcf5cbcdf24 helps?

The touch protocol might need some tweaks, though... I know we have some logging capabilities to test that, but I'm not familiar with those, so I'm sure someone else will chime in with some help if touch is wonky with this patch ;).

**Comment by Frenzie** [comment]
Pika, Pika! lol, finally the Pokeball icon makes sense.

@NiLuJe PR? =P

**Comment by GuyDeLaCombe** [comment]
Hi,

@NiLuJe I reedit the file (using TextEdit on mac) device.lua in .kobo/Koreader/frontend. And after reboot, when clicking on the koreader pic, it loads for 2 sec and come back to main menu of the usual kobo soft. The crash.log says:

> ./luajit: error loading module 'device' from file 'frontend/device.lua':
> 	frontend/device.lua:223: 'end' expected (to close 'if' at line 206) near 'else'
> stack traceback:
> 	[C]: at 0x00044201
> 	[C]: in function 'require'
> 	frontend/ui/uimanager.lua:1: in main chunk
> 	[C]: in function 'require'
> 	./reader.lua:96: in main chunk
> 	[C]: at 0x0000bea5

By the way, there are others device.lua in .kobo/Koreader/frontend/device/kobo
 
@NiLuJe What do you mean by shell acess to the kobo ?

**Comment by NiLuJe** [comment]
@GuyDeLaCombe: The crash is because I made a stupid mistake (there's an extra 'else' in there).

@Frenzie: Will do, as soon as we're sure it (mostly) works ;).

**Comment by NiLuJe** [comment]
@GuyDeLaCombe: 8205177db6bcebb75b1282ca36b164904c06edc0 should be saner, sorry about that ;).

**Comment by GuyDeLaCombe** [comment]
OK, still the same, the crash.log says:

> ./luajit: frontend/ui/widget/buttontable.lua:13: attempt to index local 'Screen' (a nil value)
> stack traceback:
> 	frontend/ui/widget/buttontable.lua:13: in main chunk
> 	[C]: in function 'require'
> 	frontend/ui/widget/buttondialog.lua:1: in main chunk
> 	[C]: in function 'require'
> 	frontend/apps/filemanager/filemanagerhistory.lua:3: in main chunk
> 	[C]: in function 'require'
> 	frontend/apps/filemanager/filemanager.lua:1: in main chunk
> 	[C]: in function 'require'
> 	./reader.lua:163: in main chunk
> 	[C]: at 0x0000bea5
>

**Comment by houqp** [comment]
This doesn't make much sense to me :( Screen should never be nil. Can you add a print statement after this line? https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua#L84. Add something like `print('!! Device.screen', self.screen)`

**Comment by NiLuJe** [comment]
Ah, right, forgot the bits in koreader-base

**Comment by NiLuJe** [comment]
@houqp : The waveform selection code in ffi/framebuffer_mxcfb.lua ;)

**Comment by NiLuJe** [comment]
... Which is fact doesn't support the Glo HD either, nice :D.

**Comment by NiLuJe** [comment]
... Wait, there are defaults value, that shouldn't completely fail.

**Comment by GuyDeLaCombe** [comment]
Hi everyone ! @NiLuJe 
I was not at home from last week :)

So I started again with a factory reset and install with KSM 8 that time. In fact, the error concerning the nil screen was coming from a modification that I made in the wrong device.lua file. So this time I modified like described [here](https://github.com/koreader/koreader/commit/8205177db6bcebb75b1282ca36b164904c06edc0) and it worked ! 
But when I launch Koreader it seems that it doesn't recognize a short press and all press are like long ones. This guy has the same [issue](http://www.mobileread.com/forums/showthread.php?t=272487). So when I want to enter in a folder, it give me choice to delete, rename, etc... and in a PDF I cannot turn a page and it impossible to shut down, because I cannot select "ok" button :)

Thanks a lot !

**Comment by NiLuJe** [comment]
@GuyDeLaCombe: Ah! That makes sense, thanks.

So, let's try to apply the GloHD tweaks, too... Gimme a minute ;).

**Comment by NiLuJe** [comment]
Does 8ba0cb4 fix the issue?

**Comment by GuyDeLaCombe** [comment]
HI @NiLuJe 

Yes, [that](https://github.com/koreader/koreader/commit/103e4eaeb8e504cf96f3a3b8699ec6c4747885c5) works nicely ! 

It is really nice to see people helping each other, working without knowing anyone personally, in an unselfish wholesome way and for no money. It's a good hope for a better society and one liberated from the slavery of subordinated labor. Long life to the free labor ! Thanks a lot to everyone !

**Comment by NiLuJe** [comment]
Fantastic ;).

Then the very latest OTA should currently work out of the box, as will the next nightly!
