### ISSUE TITLE
Cover image is black (fb2)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2010]
* KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-371-g24a30cb
* Device: Kindle Touch

#### Issue
A cover images is solid black.

#### Steps to reproduce
The book format is .fb2.zip.
http://flibusta.is/b/313434

**Comment by itspec-ru** [comment]
I am already described this bug
https://github.com/koreader/koreader/issues/1438

**Comment by mergen3107** [comment]
OK, thank you!
Let's wait together :)

**Comment by Frenzie** [comment]
Note to others who didn't know: fb2 is simply an XML file, and images are BASE64 encoded.

Closing in favor of #1438
