### ISSUE TITLE
Kindle Touch - Password BYPASS

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2011]
* KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-371-g24a30cb
* Device: Kindle Touch

#### Issue
KOreader bypasses Kindle Touch's password.

#### Steps to reproduce
Open a book in KOreader. Lock Kindle Touch (a password previously set).
Try to unlock - Kindle will unlock without asking the password.
This also applies to USB connection - normally, Kindle asks to enter the password in order to open Kindle storage drive on a PC. With KOreader it connects without prompt.
This also does not matter in what screen on KOreader the user is - a book, file manager, settings

However, if Kindle is locked somewhere outside of KOreader, password is asked normally.

**Comment by NiLuJe** [comment]
By design. We can't interact with the native password prompt, so it only gets in our way.

**Comment by mergen3107** [comment]
OK, thank you NiLuJe!
Then, thinking about a workaround, will the following set up work?
1) From KOreader press a new button that says 'Lock'
2) KOreader will jump to Home and invoke Kindle's default lock to screensaver.
3) Whenever the Kindle is unlocked (either by password or not) only after steps 1 and 2 are completed (in order to return KOreader only after Kindle was locked from KOreader), the script will return KOreader.

I know that's quite complicated, however I think such an automated tweak is worth considering.
Thank you!

**Comment by NiLuJe** [comment]
1/ Exit KOReader.
2/ Press power button.

...

3/ Start KOReader.

:?

**Comment by mergen3107** [comment]
Ah, OK.
I replaced the Store button with KOreader like [there](http://www.mobileread.com/forums/showthread.php?t=178752), now it is even easier to restart it.

(On Kindle Touch we need const t = 'app://com.github.koreader.kpvbooklet';)
