### ISSUE TITLE
File manager - Folder name on top

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2012]
* KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-371-g24a30cb
* Device: all devices

#### Suggestion
It would be great if current folder's name is shown on top of the File Manager screen.

#### Steps to reproduce
First, I open a book from Kindle's Home menu in KOreader (thanks to KPV Booklet and Collections manager that makes collections out of folders!)
Then, I open file manager - it show the current folder of that book.
Here, it will be great to see what folder (and optionally location) is that.

**Comment by chrox** [comment]
Implemented in #2129.
