### ISSUE TITLE
Wrap names and font size in File Manager

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2013]
- KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-371-g24a30cb
- Device: all devices
#### Suggestion

A great idea is to allow filenames to wrap so that we can see the full name.
Also, font size could made smaller in order to allow more names to fit in a single screen.
#### Steps to reproduce

Currently I use Rename dialog to see the full name of a file. However, it would much more convenient if we could see the full name right a way on the screen.

**Comment by KenMaltby** [comment]
I make the following adjustments 
For me, with my Kobo AuraHD, it is in .adds\koreader\frontend\ui\widget\menu.lua
 The "cfont", at line 122 and 325, using Notepad++
 I changed mine to 18. It looks fine but The Aura HD, has a higher res than some, which means that the fine print is clear and readable. The text is smaller, so more of the titles are visible. 

To adjust number of lines per page, change:
 Around Line 374: Screen:scaleBySize(46), -- hardcoded for now. I changed to (28), for my AuraHD)

\koreader\frontend\apps\reader\modules\readerfooter.lua Line 215  return os.date ("%I:%M")
(This is just to change the time format in the reader's mini-progress bar.)

This works for me with my eyes, on the larger HD display of my AuraHD, might not be so good on a Kobo Mini.

**Comment by mergen3107** [comment]
Great news! Thank you!
Previously I tweaked all my margins and other default settings by copying defaults.lua to defaults.persistent.lua. Tried to find something for UI tweaks in many lua files also available in koreader folders, however the abovementioned tweaks aren't quite obvious :D
Thank you! At least with changed font size and number of items it would be more convenient even without wrapping.

**Comment by mergen3107** [comment]
Let me leave the question about list names wrapping still open in the same thread.

**Comment by KenMaltby** [comment]
Sure, it still would be useful.

**Comment by houqp** [comment]
@chrox is working on the new KOReader home which will solve this issue :)

**Comment by mergen3107** [comment]
Wonderful! :)

**Comment by robert00s** [comment]
Full filename is added in #2414. 
@houqp Please close this issue.

**Comment by KenMaltby** [comment]
While I have no objection, to closing this item, there is quite some difference between the results of #2414 and what we discussed here.  In fact the approach in #2414 isn't much different from the OP's "Currently I use Rename dialog to see the full name of a file."

**Comment by robert00s** [comment]
I prepared something like that

![koreader_042](https://user-images.githubusercontent.com/22982594/34457244-4f6e5704-edab-11e7-8d31-187a9023be6e.png)
![koreader_043](https://user-images.githubusercontent.com/22982594/34457245-5441ee3a-edab-11e7-9382-d3d0624faac7.png)

**Comment by lostwonders** [comment]
How did you change the icons and page text at the header and footer

**Comment by Frenzie** [comment]
That's just what the program looked like in 2018, but coincidentally see https://github.com/koreader/koreader/issues/13174.
