### ISSUE TITLE
Problem with cover (kepub file):

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#2017]
* KOReader version: Since 2015-11-31x
* Device: Kobo Glo HD || (1448 x 1072)px

#### Issue
**The cover is the 2nd page of the book when it should not be this way.**
On the other hand, **IMHO** when the cover page consist only by a single image. It always should be showed as a full scaled image... It seems better to me... ;P 

Cover with version 276 (in landscape mode; exists a bug that don't allow me to make the ss in vertical mode):
![276_1](https://cloud.githubusercontent.com/assets/17313916/15125372/c6ddb8e6-162c-11e6-8594-48ede0e1f8ff.png)
vs Cover with version 38x (It happens since 31x versions if I don't remember bad :P ):
![38x_1](https://cloud.githubusercontent.com/assets/17313916/15125403/e67c35a6-162c-11e6-9524-10566be74a01.png)
Cover image (jpg: 900x600)px
Cover.xhtml:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <link href="../Styles/style.css" rel="stylesheet" type="text/css" />
</head>

<body class="sinmargen">
  <h1 class="cubierta" title="Cubierta"><img alt="" src="../Images/cover.jpg" /></h1>
</body>
</html>

```
Style.css:
```
/* -------- CUBIERTA -------- */
.cubierta { margin:0; padding:0; border:0; font-size:0; text-align:center; text-indent:0; }
	.cubierta img { height:100%; max-height:100%; }
/* bloques */
.sinmargen { margin:0; }
```
Regards.

**Comment by frankyifei** [comment]
try use a image with higher resolution

**Comment by djalma2k** [comment]
The cover problem is a consecuence of this:
Book rendered with 276:
![276_2](https://cloud.githubusercontent.com/assets/17313916/15132821/7e1ed0a0-165d-11e6-8f2e-ce34a9acb46c.png)
![276_3](https://cloud.githubusercontent.com/assets/17313916/15132830/8aba008c-165d-11e6-91cd-fdc6284fbfdf.png)
Book rendered with >31X:
![38x_2](https://cloud.githubusercontent.com/assets/17313916/15132844/b02f84f4-165d-11e6-9759-4741c7830357.png)
![38x_3](https://cloud.githubusercontent.com/assets/17313916/15132847/b9eb75a2-165d-11e6-9da4-efb747f1c5de.png)

But this new method that it's rendering in a proper way the images that previously was incorrectly magnified, introduce a bug (in my opinion) that is what I'm talking about here.
Regards.
If anyone want to check an epub with a lot of image at the begining:
http://m.zbigz.com/myfiles?url=magnet:?xt=urn:btih:46D8C007D3FEE13D1ED3EA62BB0CE924BC31F4A5&dn=EPL_How_to_Make_Love_Like_a_Porn_Star&tr=http://tracker.tfile.me/announce&tr=http://91.121.54.8:6969/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://open.demonii.com:1337/announce

but any epub file with images should do the trick...

**Comment by frankyifei** [comment]
it disabled zoom in of low resolution image from that versio. So try to use a higher resolution image for cover

**Comment by djalma2k** [comment]
@frankyifei I should have explained better... The bug is that right now all the books have a 1st blank page instead the cover image.
With 276:
1st page-----> cover image
With >31X:
1st page----> a blank page
2nd page----> cover image
And I suspect that its not only happens with the cover images... I have to check it right now...
Regards.

**Comment by frankyifei** [comment]
can not download from http://m.zbigz.com/myfiles?url=magnet:?xt=urn:btih:46D8C007D3FEE13D1ED3EA62BB0CE924BC31F4A5&dn=EPL_How_to_Make_Love_Like_a_Porn_Star&tr=http://tracker.tfile.me/announce&tr=http://91.121.54.8:6969/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.publicbt.com:80&tr=udp://open.demonii.com:1337/announce

you can upload it here by change the filename to zip

**Comment by djalma2k** [comment]
> you can upload it here by change the filename to zip

You should'nt be problems rightnow, anyway If you still can't download it, i will upload it here:
https://dropfile.to/zkOaxHG

PS: If I will upload any file here, can I be able to erase it from here?
Regards.

**Comment by frankyifei** [comment]
I think this has been fixed in recent commit. I can not find any blank page for this epub using my build.

**Comment by djalma2k** [comment]
Using 2015-11-392 (commit: cc72fcafd19b81f7c4744924845f2d7790ec5998)(May 6, 2016), I count 6 different blank pages (2 of them contigous) until the "Prologue" and between the "Prologue" and the "Chapter one" other 3 blank pages...
Well, I'll try it when a newer version will be released via OTA. (Right now It's only 1 commit "below master branch")
Regards and Thanks for checking this.

**Comment by djalma2k** [comment]
@frankyifei I just check the last commit (7816c3373306849323ab8b3875f95be8f9081404)(2015-11-394 in OTA) and it is still happening the same :/

**Comment by frankyifei** [comment]
did you check out the master branch of crengine , base is not updated for some days. 
I don't have a kobo. The book looks ok on my kindle and on pc emulator.

**Comment by djalma2k** [comment]
@frankyifei I just know where is the problem. I'm using kepub files generated by calibre. If I use the raw/original epub files, (the same as you download), I don't have this problem. Anyway with the previous versions (<2015-11-31X) I don't have any problem related to this issue...
Regards.
PS: Sorry if I make you waste time checking this... I didn't realize the calibre conversion.

**Comment by houqp** [comment]
I don't think kepub is supported by KOReader right now. Feel free to create a new issue for kepub support if you want.
