### ISSUE TITLE
CONTRIBUTION: Russian localization

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2023]
* KOReader version: Should work on every KOReader
* Device: on all devices

#### Thank you KOReader Team!
I am so excited about your diligent and persistent efforts toward making KOReader greater and greater that I couldn't resist to try to help you!

#### Russian Localization
Russian is my second native language after Kazakh since I live in a post-Soviet country, the Republic of Kazakhstan. Also the last three years before my High School graduation I was keeping winning olympiads on Russian language and literature. Hope that proves my credibility :D

I edited and tested (in a fb2.zip, pdf files and in File manager) the file koreader\l10n\koreader.po by several iterations and asked my friend to proof read it on my Kindle Touch in order to find some uncertain translations. Also I was taking care about how the text will look like on actual screen. Now I can assure you that it looks greatly and very understandable. Hope this could make KOReader more user-friendly to your only-Russian audience.
Respecting all other contributors of ru-locale, I just added myself in that file too, if you don't mind :D

The file is here: [New Russian Localization](https://yadi.sk/d/fy_yrVsUrhJc5). **Could you please update the Russian localization with the next release?**
Thank you!

**P.S.** I don't understand why only for Russian there are two folders, ru and ru_RU. Maybe we should remove the latter? As far as I understand, it does not affect anything.

**P.S.S.** While I was translating, I noticed a few strange things.
1) Why the option of 'View Mode' is in different categories for pdf and books? For pdf it is under the tab with columns icon, for books it is under the tab with gear icon. Isn't it logical to place both, let's say, under the tab with columns?
2) There is the menu "Highlight" that appears both in dictionary look up widget and among settings items. In the dictionary widget there is very short space to place a word, so I decided to put just translation of "Highlight". However, I'd like to make the settings menu of "Highlight" more meaningful, so instead of just "Highlight" I'd like to put translation of "Highlight options". There are linked to the same translation and both change together. Can we separate them please? I tried to put addition strings with msgid and msdstr after the lines (with no success):
#: frontend/apps/reader/modules/readerhighlight.lua:69
#: frontend/apps/reader/modules/readerhighlight.lua:320

**Comment by chrox** [comment]
Thanks for your contribution. Koreader wouldn't be what it is now without continuous efforts from the Koreader community.

This repo now don't manage translated strings (the po files). When we release a package we fetch the po files for all languages from https://www.transifex.com/houqp/koreader/. And translators should submit the translations to Transifex. See a short instruction [here](https://github.com/koreader/koreader#translation).

I agree that the `View Mode` for EPUBs and the `Scroll Mode` for PDFs are the same concept of paging option and should be placed in the same category. And `Highlight options` is a better name for the settings menu item. I will send a pull request to reflect these changes. Thanks.

**Comment by mergen3107** [comment]
What a unified and organized way of keeping all translations ordered! I am impressed!
I uploaded .po file for Russian through the web interface
Thanks for your feedback to my feedback :)

**Comment by mergen3107** [comment]
Found another strange feature.
1) Select a word in a book. 
2) Highlight it. In the widget box that is still open it says "Unhighlight" grayed out. I don't know why I can't remove the highlight right after I did it. Probably it is still on early stage, the same as feature of adding notes yet. Anyway, strange things are the following.
3) When I tap this highlight, it says "Delete", not "Unhighlight". I think it does make sense if these options are the same.

This "Delete" comes from around line 380 in the translation:
```
#: frontend/apps/filemanager/filemanager.lua:133
#: frontend/apps/reader/modules/readerhighlight.lua:203
#: frontend/ui/widget/opdsbrowser.lua:650
msgid "Delete"
msgstr "Удалить"
```
So, I guess for File Manager and OPDS Browser it is good to have common "Delete" button. As for highlighting, I think we should move this readerhighlight to "Unhighlight" msgid.

To here (around line 1340):
```
#: frontend/ui/widget/dictquicklookup.lua:304
msgid "Unhighlight"
msgstr "Убрать цитату"
```

**Comment by mergen3107** [comment]
Great! New [changes](https://github.com/koreader/koreader/commit/c6d68e381fdd723245ebccad7ff5b77ed4e0b991) work :)
I applied them on my KOReader, looks great.

Interestingly, when I tried to copy small portions to the codes first, KOReader did not open.
Then I just opened Raw versions of these two files and replaced the whole codes with them - succeeded!

Thank you!

**Comment by mergen3107** [comment]
@Frenzie, @chrox 
Will we consider replacing KOReader's virtual keyboard with [this](https://github.com/koreader/koreader/issues/2014) one I created in the next releases?
I changed there Russian layout to more convenient QWERTY-like layout, also added Kazakh letters (however replaced Ukrainian). Changed numbers so that there are like a dialpad now (like on my [BlackBerry Q10](http://s3.amazonaws.com/digitaltrends-uploads-prod/2013/01/BlackBerry-Q10-review-bottom-keyboard.jpg)).

**Comment by Frenzie** [comment]
Unless the current layout is deficient I'd think it should be available in addition somehow, rather than instead of.

**Comment by mergen3107** [comment]
@Frenzie 
yes, current versions is unusable. There should be 33 letters in Russian, in this version there are only 30. Two of three (ь, ъ) are critical! The third one (ё) is an optional replacement for Russian "e" letter.
So I did thorough redesign of 26 letters using conventional qwerty-like layout, and put all other (7) "out-of-26" characters on the second keyboard at their usual places on hardware keyboards (laptop, PC) at the right.

Russian-speaking guys (maybe, @erosennin, @evgsh, @houqp since I noticed you among Russian localization translators) could you please kindly test it and give feedback on usability and overall look of the new layout? The file is here - [KOReader Improved Russian keyboard (with Kazakh)](https://yadi.sk/d/S28EaW1VraPi5)

I know that I am quite insisting on applying this new keyboard, however, no offense, guys, I just really would like to help you to improve KOReader, and I really think that keyboard layout is a very important aspect that could dramatically affect your audience :)

Regarding changeable keyboards, yes, I very much agree that there must be an option to choose layouts in future. However, for now I still think the keyboard I suggest is very convenient :D

Thank you for your patience!
Hope for your understanding and looking forward to our future collaboration!

**Comment by houqp** [comment]
Ha, I don't speak russian at all, i just happened to ended up in that group because i created it :P @mergen3107 the file you uploaded is not downloadable anymore, can you put it into a github gist? Or even better, send us a pull request so we can discuss it further there.

**Comment by mergen3107** [comment]
@houqp 
strange! I can download that file from the above link. OK, let me upload on another source..
