### ISSUE TITLE
Crashes on some epubs when I turn Embedded styles off.

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2026]
- KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-394-g7816c33
- Device: Kindle Touch
#### Issue

On some epubs, when I try to turn off Embedded Styles off (Bottom options, Gear tab), KOReader crashes to the main Kindle menu. When I come back, the styles are again on.
#### Steps to reproduce

Example epub that has that issue is [here](https://yadi.sk/i/pfECeygqrho7Z).

**Update!**
I manually deleted the cache of this file from cache/cre3engine and now it works!
This book was the first time opened fine (however I didn't play with Embedded styles) with 2015-11 stable version, then with Nightly 371 (previous) and crashed on my current Nightly (394).
Probably, KOReader should notice that something bad happens with the cache, then I think it should delete the cache and try to open the book again.

Thanks!

**Comment by houqp** [comment]
Do you sill have backup for the old cache files? It would be nice if we can use it to reproduce it on our side to fix the root of the issue.

**Comment by mergen3107** [comment]
@houqp 
Unfortunately, the old cache was just wiped. If this happens again with another book I'll let you know

**Comment by poire-z** [comment]
Must have been fixed, like #2386, last summer in https://github.com/koreader/crengine/pull/73 and followups.
