### ISSUE TITLE
KOReader and BlackBerry Q10 - not working

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2027]
- KOReader version: Android version (the latest nightly 394)
- Device: BlackBerry Q10 10.3.2.2836
#### Issue

KOReader installs, but does not work on BlackBerry Q10's Android Runtime.
A black screen appears for about 5 seconds, then KOReader gets minimized.
A patch from [here](http://www.mobileread.com/forums/showthread.php?t=271505) doesn't work too.
#### Steps to reproduce

I think there are two main reasons why KOReader is not working properly:
1) BlackBerry's Android Runtime is working all the Android apps from mnt/sdcard. /sdcard is also linked to mnt/sdcard. Probably, KOReader looks for /sdcard and get confused with the link.
2) There is not access, for example, from Total Commander to /data. As I guess, KOReader installs there, right? So instead I suggest to use mnt/sdcard/Android - that is /data equivalent for /data, since I noticed that many apps store their temporary files there.

I suppose that Android (and especially BlackBerry) is  low in priorities in your project plan, so I don't expect this issue to be resolved. I just want to try to help you develop KOReader with all devices that I have :D These are Kindle Touch, Nook Simpe Touch (its 2.1, so KOReader doesn't work, OK), and BlackBerry Q10.

**Comment by houqp** [comment]
Thanks @mergen3107 for the report. We are working hard on getting the next stable release out right now. Hopefully, we can take a look at this after the release. Or if someone wants to take a stab at it, feel free to send a PR :)

If you have android build env setup, you can try modifying the path in https://github.com/koreader/koreader/blob/master/datastorage.lua#L10 to see if it fixes the issue.

**Comment by mergen3107** [comment]
Should I then rebuild my own KOReader package for Android?

**Comment by houqp** [comment]
If you want to test custom changes in android, you will need to build your own koreader apk.

**Comment by KenMaltby** [comment]
It is possible to modify an existing .apk, I use "EasyApkDisassembler"  to sign the .apk, after applying whatever changes.  There is seldom any need to actually Disassemble the .apk, I just use Notepad++ to make changes to the scripts, then sign the .apk, so it will install.

**Comment by mergen3107** [comment]
I disassembled the nightly-394 build with ApkTool, but I couldn't file a file where I could change the install directory. Total Commander does not find anything with 'sdcard' or something looking like it is installation path.
So where should I find the above mentioned datastorage.lua?

**Comment by KenMaltby** [comment]
There is no need to disassemble the .apk. You can just use 7-zip or WinRAR to open the .apk then go to: assets> module then open the koreader- xxxxxx.7z (which has the program in it) the datastorage.lua is there.

**Comment by mergen3107** [comment]
OK, got this! Thank you!
So I changed the file (directory is now /mnt/sdcard/koreader/), then re-signed the apk, it didn't blame for anything while installing.
However still no success even with the patch. First time it just minimizes. Then, if I open the window of KOReader again, it goes all black and holds still for eternity. I only noticed something happening on this black screen, like it tries to draw something (very dark brownish color appears for a second) and then comes back to all-black-state. Menu button is not working either.
Also there is nothing created under its path.
Think further what can we do.

**Comment by houqp** [comment]
@mergen3107 , do you have adb logcat access? It would very helpful to paste the log here.

**Comment by mergen3107** [comment]
@houqp 
yes, I think with some workarounds, like from [here](http://devblog.blackberry.com/2013/11/pull-android-logs-from-your-blackberry/), it is possible to approach BlackBerry 10's Android Runtime logs. I'll that a bit later with an ample free time available

**Comment by mergen3107** [comment]
@houqp 
yes, I think with some workarounds, like from [here](http://devblog.blackberry.com/2013/11/pull-android-logs-from-your-blackberry/), it is possible to approach BlackBerry 10's Android Runtime logs. I'll that a bit later with an ample free time available

**Comment by Frenzie** [comment]
@mergen3107 Is this still an issue? I imagine Blackberry's runtime has been improved since.

**Comment by mergen3107** [comment]
@Frenzie, I believe yes, since BlackBerry dropped support for BlackBerry OS 10 at all, so there are no more improvement to their Android runtime adoptation neither.

**Comment by Frenzie** [comment]
There have also been Android improvements in KOReader that might have helped, btw. I meant if you could test the latest beta or nightly if you don't mind. :-) For example, @houqp 's suggestion has been part of the program since #2254.

**Comment by Frenzie** [comment]
Since Blackberry dropped support I'll close this. Sorry for the inconvenience.
