### ISSUE TITLE
Nook Glowlight Plus full screen refresh not working.

### ISSUE THREAD

**Issue by verge-36** [koreader/koreader#2034]
* Device:Nook glowlight plus

#### Issue

E ink optimization is problematic. Refresh screen after 6/12/x pages doesn't work. 

#### Steps to reproduce

After starting to read a book scroll pages. Full screen refresh never happens.

#### Proposition:

I dont know if screen refresh for nook glowlight plus is hard do implement.
But there's an app for nook:Nook clear screen It basically just refreshes the screen. 
Maybe as a temporary workaround we could launch it every x pages?

**Comment by houqp** [comment]
@verge-36 is Nook glowlight running with android? The full refresh support can be reverse engineered if you can run strace on the device.

**Comment by chrox** [comment]
Duplicated to #1613. Closing this now.

**Comment by verge-36** [comment]
Yes it's android 4.4 . Mentioned app exists in play store.

**Comment by verge-36** [comment]
@ houqp I ran strace on the device for both stock B&N Reader and Nook Clearscreen apps.
I may have missed a few lines with this script but i couldn't find a way to run strace any other way since the Clearscreen app closes instantly after starting it..
[NOOK.tar.gz](https://github.com/koreader/koreader/files/349551/NOOK.tar.gz)
