### ISSUE TITLE
Unable to launch on Kindle PW2

### ISSUE THREAD

**Issue by pavlukivan** [koreader/koreader#2035]
* KOReader version: nightly-20160620
* Device: Kindle PW2

#### Issue
Error in reader.lua at lines 144-146

#### Steps to reproduce
try to launch KOReader

I fixed it by removing lines 144-146, but probably it isn't good workaround.

**Comment by NiLuJe** [comment]
Can't reproduce on 2015.11-404 (on a PW2).

Try with a fresh install of the latest OTA?

**Comment by pavlukivan** [comment]
I have 5.7.2, if that matters... It doesn't work after fresh install.

**Comment by houqp** [comment]
@pavlukivan can you paste the `crash.log` here? This does not make much sense to me since the code path should only be triggered for kobo devices.

**Comment by NiLuJe** [comment]
Wasn't this reported a while ago? I vaguely remember testing this on my end
and not being able to reproduce it... I'll double check this week end.

**Comment by chrox** [comment]
It seems that we cannot reproduce this. Please reopen this if you still have this problem with the latest nightly build.
