### ISSUE TITLE
How to set the "screensaver_folder"?

### ISSUE THREAD

**Issue by ycrichard** [koreader/koreader#2037]
* KOReader version: Latest Nighty
* Device: Kobo Aura H2O

#### Issue
I normally set screensaver directory in `KOBO_SCREEN_SAVER`, and get random images inside to show as screensaver.
But in the lastest nighty, `KOBO_SCREEN_SAVER` option has been removed from `defaults.lua`.
And in `screensaver.lua`, that part has been replace by `readSetting("screensaver_folder")`.

Can someone tell me, how to set the screensaver folder now or what is the default path?

**Comment by Hzj-jie** [comment]
You may want to edit reader.settings.lua, add
["screensaver_folder"] = "..."
but kobo internal storage (i.e. /mnt/onboard/screensaver) should be able to work.

**Comment by houqp** [comment]
@ycrichard , like @Hzj-jie said, you can set it by setting the ` screensaver_folder` key in settings.reader.lua. I am working on adding this as an option to the menu. Currently stuck at refactoring the code that handles defaults.lua. Those are very hacky code that's not easy to clean up unfortunately :(

**Comment by ycrichard** [comment]
Thanks for the instruction, it works well now.
I also added `["use_lastfile_as_screensaver"] = false` into settings.reader.lua.

Looking forward to the option in menu! Cheers

**Comment by houqp** [comment]
New menu item is added in https://github.com/koreader/koreader/pull/2045
