### ISSUE TITLE
File manager won't be able to start without several font settings

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2038]
* KOReader version: v2015.11-411-gf649acd
* Device: Kobo Aura HD

#### Issue
If three fonts are not set scfont, hpkfont, infont, in reader.settings.lua / fontmap, file manager won't be able to start. If 'open last file' has been enabled, koreader will open last file when clicking on file manager icon in reader ui.

#### Steps to reproduce
1. Set fontmap in reader.settings.lua, but do not include scfont, hpkfont, infont.
2. Start Koreader.

**Comment by houqp** [comment]
Yep, this is a bug. We should have those set to the fallback front if not set.
