### ISSUE TITLE
Android build won't work with NDK 11c

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2043]
- KOReader version: Up to 2015.11-411-gf649acd
- Device:
#### Issue

Android build won't work with NDK 11c

```
Linux 64-bit (x86)  android-ndk-r11c-linux-x86_64.zip   794135138   de5ce9bddeee16fb6af2b9117e9566352aa7e279
with download link http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip
```

After digging out a little bit, following issues found.
1. libk2pdfopt/Makefile, when it builds libtesseract, it should define -DANDROID, as far as I can tell, the latest android g++ compiler won't define it anymore. Append

```
$(if $(ANDROID), CPPFLAGS='-DANDROID',) \
```

around line 107 (After

```
$(if $(WIN32), CPPFLAGS='-D_tagBLOB_DEFINED',) \
```

should fix it. Or tesseract should respect ANDROID environment variable.
1. tesseract/configure.ac, ADD_RT should be false for android, around line 112.
2. gettext expects _LIBC defined. Changing gettext/CMakeLists.txt line 20 from

```
    set(CFG_CMD "${CFG_CMD} && ${ISED} \"s|#define HAVE_PWD_H 1||\" gettext-tools/config.h")
```

to

```
    set(CFG_CMD "${CFG_CMD} && ${ISED} \"s|#define HAVE_PWD_H 1|#define ANDROID 1|\" gettext-tools/config.h")
```

and edit spawn_faction_addclose.c spawn_faction_adddup2.c spawn_faction_addopen.c to replace __sysconf with sysconf

```
#if !_LIBC
#if ANDROID
# define __sysconf(open_max) sysconf(open_max)
#else
# define __sysconf(open_max) getdtablesize ()
#endif
```

can resolve it.
1. tar/gnu/fcntl.c, similar as the one above, replace getdtablesize to sysconf can resolve it.

```
#ifndef HAVE_GETDTABLESIZE
#define getdtablesize() sysconf(_SC_OPEN_MAX)
#endif
```
1. p7zip-full is required to build android. This can be covered by README.md.
2. android/luajit-launcher/mk-luajit.sh hardcoded arm-linux-androideabi-4.6.
3. ANDROID_HOME is expected to be reported if using NDK without make-standalone-toolchain.
4. Android SDK API19 is required.

Finally I have got a build. And good news is, it works. But the entire process is too complex, should we fix these issues to make android build fluently?

**Comment by houqp** [comment]
Definitely. I did not run into these issues with my old android toolchain setup. We should make sure the build system works flawless with the new toolchain too. Feel free to submit PRs for those fixes.

**Comment by chrox** [comment]
Fixed in koreader/koreader-base#427.

**Comment by Hzj-jie** [comment]
Sorry, Huang, my PR is one of the changes.

**Comment by Frenzie** [comment]
Can this be closed?

**Comment by houqp** [comment]
Yes, there is a already 11c entry in the build matrix for koreader-base CI: https://github.com/koreader/koreader-base/blob/master/.travis.yml.
