### ISSUE TITLE
hanging/negative indent

### ISSUE THREAD

**Issue by bbgordon** [koreader/koreader#2046]
* KOReader version: f5b0f0dcd728327d41ab412c004a3df24ba36da4
* Device: Kindle Voyage

In the HTML below the "hanging" class creates a paragraph whose first line is flush with the left edge and subsequent lines moved 2em inward. However, crengine implements negative text-indent by indenting all but a paragraph's first line by its absolute value. If the paragraph has any padding or margin the first line is indented by that padding amount (instead of zero) and other lines are indented by padding + indent (instead of just the padding).

This looks fine in isolation but  doesn't line up as intended with other paragraphs or with the opposite margin.

Experimentally, I changed crengine to treat x position as signed rather than unsigned and pass the negative indent through when rendering. I expected this hack to cause lots of problems but to my surprise it seems to work okay! Text is positioned properly even if the negative indent cuts it off by pushing it off the screen edge.

HTML example:

```
<style>
p {
    margin: 0;
}
.hanging {
    text-indent: -2em;
    padding-left: 2em;
}
</style>
<p class="hanging">hanging</p>
<p>no indent</p>
```

Hack hack hack:

```
diff --git a/crengine/include/lvtextfm.h b/crengine/include/lvtextfm.h
index 9740b27..c06e3e2 100755
--- a/crengine/include/lvtextfm.h
+++ b/crengine/include/lvtextfm.h
@@ -135,7 +135,7 @@ typedef struct
    formatted_word_t * words;       /**< array of words */
    lInt32             word_count;  /**< number of words */
    lUInt32            y;           /**< start y position of line */
-   lUInt16            x;           /**< start x position */
+   lInt32            x;           /**< start x position */
    lUInt16            width;       /**< width */
    lUInt16            height;      /**< height */
    lUInt16            baseline;    /**< baseline y offset */
diff --git a/crengine/src/lvtextfm.cpp b/crengine/src/lvtextfm.cpp
index 50e319b..67c1246 100755
--- a/crengine/src/lvtextfm.cpp
+++ b/crengine/src/lvtextfm.cpp
@@ -1068,7 +1068,7 @@ public:
         }
 
         for (;pos<m_length;) {
-            int x = indent >=0 ? (pos==0 ? indent : 0) : (pos==0 ? 0 : -indent);
+            int x = pos==0 ? indent : 0;
             int w0 = pos>0 ? m_widths[pos-1] : 0;
             int i;
             int lastNormalWrap = -1;
```

There's an upstream bug for this https://sourceforge.net/p/crengine/bugs/324/ but I'm reporting it here, too, because upstream seems inactive.

**Comment by houqp** [comment]
Sounds reasonable to me. According to http://www.w3schools.com/cssref/pr_text_text-indent.asp, text-indent should  only indent the first line of a paragraph. @bbgordon , feel free to send a pull request.

My only concern is we should also change y to be signed if x is changed to be signed.
