### ISSUE TITLE
Disable embedded fonts

### ISSUE THREAD

**Issue by depeesz** [koreader/koreader#2048]
It would be useful if koreader would have an option not only to disable entire embedded style, but also to switch the font to default one. It would remain, for example, text alignment or declared font sizes.

Thanks a lot.

**Comment by frankyifei** [comment]
This will be useful for some bad formatted epubs

**Comment by slow-mo** [comment]
#830

**Comment by Frenzie** [comment]
Some progress in #2048.

**Comment by robert00s** [comment]
@Frenzie I think that's another issue :)
#2048 is the same issue.

**Comment by Frenzie** [comment]
I probably meant to refer to #3141 but of course that's the same thing. :-P

**Comment by Frenzie** [comment]
Alright, should be fixed in #3149.
