### ISSUE TITLE
non-stop gettimeofday system call when reader is idle

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2050]
* KOReader version: g66754e3
* Device: Kobo

#### Issue

Just notice this while trouble shooting an issue. The reader is in idle state without user inputs. However, strace shows that it's constantly calling gettimeofday syscall during the background every second. We need to get to the bottom of this to see if it's expected behavior.

**Comment by NiLuJe** [comment]
Just for clarity's sake, which process is that coming from?

**Comment by houqp** [comment]
I don't remember, I will do a strace again and paste the result here.

**Comment by houqp** [comment]
Likely related to https://github.com/koreader/koreader/issues/1974

**Comment by KenMaltby** [comment]
#1769?

**Comment by houqp** [comment]
IIRC, this happens even if that feature is disabled. And the frequency of auto refresh timer should not be once per second. It's likely a bug in the UIManager.

**Comment by KenMaltby** [comment]
The only other places where I would expect a call for the time of day would be the display in the main menu or in the statistics/status functions.  ( Perhaps the updating/calculation of time to read.)  Just logical places to look, not much help, I guess.

Luck;
Ken

**Comment by houqp** [comment]
So this only happens in KOBO, not in the emulator. A quick check reveals that length of UIManager._task_queue is always 1 in idle state, which causes UIManager._checkTasks to run every second and subsequently calls gettimeofday every second.
