### ISSUE TITLE
Cant edit the file name Pocketbook

### ISSUE THREAD

**Issue by andruha30** [koreader/koreader#2058]
* KOReader version:koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-394-g7816c33
* Device:Pocketbook 626+

**Comment by andruha30** [comment]
When open to edit the file name (Edit) no possibility to place cursor for editing nevertheless once or twice tapping. I had to delete the whole name  and then to write a new name

**Comment by chrox** [comment]
With the latest nightly it should be able to do that work thanks to @union2find's patch from #2028.
