### ISSUE TITLE
Should we use Font:getFont in CreDocument?

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2059]
- KOReader version: Up to 751e46c
- Device: Independent
#### Issue

CreDocument.default_font / header_font / fallback_font are still read from specific G_reader_settings, but not Font.lua. Should we use Font.lua in CreDocument?

**Comment by houqp** [comment]
So `Font.lua` is for typesetting KOReader's user interface, while those 3 fonts are used by CREngine. They have different use cases. They also go through different code path. The font settings in `Font.lua` goes straight to Freetype2 lib through our FFI shim, while those 3 fonts go through CREngine's fontmanager, which is a more complex Freetype2 wrapper.

Whether we still want to keep them separate is probably something we can discuss here. Some people might want different font face for UI and the book content.

My thoughts:
The name for those settings, especially `header_font` and `fallback_font` are confusing and they sound like a setting for system (UI) fonts. It's probably better to rename and prefix them with cre.

**Comment by Frenzie** [comment]
Also see https://github.com/koreader/koreader/commit/587758939eb7696d680ed27032343d585c041e4d

**Comment by Frenzie** [comment]
@houqp Is this still an issue? You did some separation.

**Comment by houqp** [comment]
We can close this now. G_reader_settings should have been nuked in all the backend code path :)
