### ISSUE TITLE
Crash in koptinterface.lua.all_matches.match

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2060]
* KOReader version: Up to 751e46c
* Device: Independent

#### Issue

A crash in koptinterface.lua.all_matches.match function.
The callstack is pretty long, but simply speaking, in all_matches.match function, we need to check whether #plist is zero at the very beginning.

#### Steps to reproduce

I reproduced this issue when I tried to do a 'search' in a pdf file, but tesseract failed to OCR the text.

**Comment by houqp** [comment]
Agreed. @chrox thoughts?
