### ISSUE TITLE
Last two characters of highlight portion are not greyed out

### ISSUE THREAD

**Issue by martinrotter** [koreader/koreader#2067]
May be related to #2021, #1722.
#### Steps to reproduce
1. Go to page (like) 10, not first page.
2. Highlight whole paragraph, click on "Highlight".
#### Result

Not whole paragraph is greyed out after clicking on "Highlight". Sometimes (like in 60% of cases) last two characters of initially highlighted text are NOT greyed out.

**Comment by frankyifei** [comment]
a screen shot will be helpful

**Comment by Frenzie** [comment]
Might be related to https://github.com/koreader/crengine/pull/107 but also closing now due to lack of info. Please reopen if more information comes up.

**Comment by frankyifei** [comment]
There could be a space in the start of the paragraph, for some reason this will cause a mismatch of the actual layout and getXrange().

**Comment by Frenzie** [comment]
@frankyifei You mean like this?

```html
<p>  Text.</p>

**Comment by frankyifei** [comment]
yes, the spaces wont be displayed but it does count one position at the start.

**Comment by poire-z** [comment]
Should be fixed by https://github.com/koreader/crengine/pull/204 , available in current nightly.
