### ISSUE TITLE
"Show advanced options" doesn't work.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2069]
* KOReader version: 2015.11.434 and next ones. But I don't know which version introduced the bug.
* Device: Kobo Mini

#### Issue
The "Show advanced options" menu entry that is available both from inside and outside a book doesn't work. It shows exactly the same options with it ticked and unticked.

**Comment by chrox** [comment]
For PDFs some advanced options will appear in the bottom config panel after the "Show advanced options" is ticked.
