### ISSUE TITLE
Inconsistent behavior for <h1><a></a>Center this</h1>

### ISSUE THREAD

**Issue by bbgordon** [koreader/koreader#2070]
* KOReader version: f5b0f0dcd728327d41ab412c004a3df24ba36da4
* Device: Kindle Voyage

#### Issue

`<h1><a>Center</a> this</h1>` gets centered but `<h1><a></a>Center this</h1>` doesn't.

#### Steps to reproduce

Consider an EPUB with one HTML file:

```
<html>
<head>
<style>
h1 { text-align: center; }
</style>
</head>
<body>
<h1><a id="chapter"></a>Foo</h1>
</body>
</html>
```

crengine doesn't center the text "Foo". If I add text like "bar", a
zero-width space inside my `<a>`, "Foo" (or "barFoo") gets centered:

`<h1><a id="chapter">&nbsp;</a>Foo</h1>`

I don't understand why yet, but it seems to happen in lvtextfm.cpp
when renderFinalBlock gets called recursively for each DOM node.

```
void renderFinalBlock( ldomNode * enode, LFormattedText * txform, RenderRectAccessor * fmt, int & baseflags, int ident, int line_h )
...
        int flags = styleToTextFmtFlags( enode->getStyle(), baseflags );
            for (int i=0; i<cnt; i++)
            {
                ldomNode * child = enode->getChildNode( i );
                renderFinalBlock( child, txform, fmt, flags, ident, line_h );
            }
```

1. Enter renderFinalBlock(h1). baseflags indicates center alignment (3).
2. Enter renderFinalBlock(a). caller's flags passed by reference = this call's baseflags = 3.
3. Exit renderFinalBlock(a). In the caller, baseflags = 3 but flags is now = 0.
4. Enter renderFinalBlock(Foo). flags = 0 so baseflags inside this call = 0 and Foo isn't centered.

Saving and restoring flags around the renderFinalBlock call fixes this, of course, but I'm not sure if alignment (are there any other flags?) ever must be intentionally affected by a sibling node.

Or is the only bug that `<a></a>` and `<a>&nbsp;</a>` get flags computed differently? I can dig into that if saving and restoring flags is the wrong design.

**Comment by frankyifei** [comment]
I think there is a similar case #1812 .

**Comment by bbgordon** [comment]
Thanks for the background!

I understand the interaction between LTEXT_ALIGN and NEWLINE a little better now. Restoring flags is definitely wrong! It would fix this but cause spurious newlines `<p><span>between</span> these</p>` words.

If the first child element doesn't have children of its own, however, the alignment gets cleared before taking effect. Maybe the below is a better approach? I haven't done much testing, nor have I investigated the other places that clear the newline flag for similar problems. I also wonder if it's correct to do this when there are no child nodes at all or if it should only be concerned with text children.

```
diff --git a/crengine/src/lvrend.cpp b/crengine/src/lvrend.cpp
index 3d55356..af5ddcd 100755
--- a/crengine/src/lvrend.cpp
+++ b/crengine/src/lvrend.cpp
@@ -1268,7 +1268,7 @@ void renderFinalBlock( ldomNode * enode, LFormattedText * txform, RenderRectAcce
 //            LVFont * font = enode->getFont().get();
 //            txform->AddSourceLine( L"\n", 1, 0, 0, font, baseflags | LTEXT_FLAG_OWNTEXT,
 //                line_h, 0, enode, 0, 0 );
-        } else {
+        } else if (enode->getChildCount()) {
             baseflags &= ~LTEXT_FLAG_NEWLINE; // clear newline flag
         }
         //baseflags &= ~LTEXT_RUNIN_FLAG;
```

**Comment by frankyifei** [comment]
If my memory is correct, I found a way to fix this. The original code will remove space in the beginning of a paragraph, it will cause this bug. But I really forget where to find it.

**Comment by frankyifei** [comment]
try comment line 1335 to 1344 in lvrend.cpp, it will fix this but the first spaces of a paragraph will not be cleared.

**Comment by frankyifei** [comment]
the flags changes in renderFinalBlock(). this function calls it self recursively and if the Element is empty or contains only spaces at the beginning of a paragraph, it should not clear the new line flag.

**Comment by bbgordon** [comment]
Thanks!
