### ISSUE TITLE
Cannot highlight across pages

### ISSUE THREAD

**Issue by martinrotter** [koreader/koreader#2071]
* KOReader version: Latest stable
* Device: PW2

#### Issue
When I try to highlight portion of texts spanning two pages, It is not possible.

#### Steps to reproduce
Start highlighting some texts almost at the end of the page and move your finger to very bottom/right corner (indicating you want to turn to next page and finish your highlight there). Nothing happens, page is not turned.

**Comment by martinrotter** [comment]
This (along with other bugs) became a blocker for me. Reverted to stock PW2 browser. :(

**Comment by lenisko** [comment]
Duplicate https://github.com/koreader/koreader/issues/1575

**Comment by houqp** [comment]
@martinrotter could you also help open issues for the other bugs that you are experiencing?

**Comment by martinrotter** [comment]
@houqp I already switched to stock browser, so no, but as far as I remember, one of really main problems were those issues with highlights because they are killer feature for me.

Follow-up problems was KOreader inability to expert bookmarks/highlights to one single easily readable file. JSON format is not good enough. Same format as the one used by stock Kindle book browser would be nice. :)

**Comment by houqp** [comment]
> Follow-up problems was KOreader inability to expert bookmarks/highlights to one single easily readable file. JSON format is not good enough. Same format as the one used by stock Kindle book browser would be nice. :)

I see. This is actually a very simple feature that can be implemented in couple lines of Lua. The good thing of open-source software is you can make it do whatever you want. The bad thing is of course you will have to do it yourself if it's not done already :P

**Comment by Nick1412** [comment]
I see that in version 2018.12 under Android 6.0.1 highlighting across pages still doesn't seem to be possible. Any hope that this could be fixed or added? Thank you.
