### ISSUE TITLE
Page footer should be counted when zooming PDF files

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2072]
* KOReader version: up to 463-gdabc705
* Device: Kobo Aura HD and Android, device independent

#### Issue

When zooming PDF files to fit the content height, bottom of the page will be covered by page footer.

#### Steps to reproduce

https://github.com/koreader/koreader/blob/641d741ec4b1c92959bb86605e8eaf5641d95d60/frontend/apps/reader/modules/readerzooming.lua#L231 may be the root cause. Instead of self.demin, which includes also page footer, we should use demin - footer.demin.h.

**Comment by chrox** [comment]
Fixed in #2079.
