### ISSUE TITLE
One tap won't close both menu and config widgets

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2073]
* KOReader version: up to 462
* Device: Kobo aura HD, should be device independent

#### Issue

One tap cannot close menu and config widgets together.

#### Steps to reproduce

https://github.com/koreader/koreader/commit/a92a88e063ef20bf35249dc3665edadb020d4297 is a little bit suspicious.

**Comment by houqp** [comment]
Yup, you are correct, a92a88e is indeed what causes it.
