### ISSUE TITLE
Backspace will delete the character before the one on the left of the cursor 

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2074]
- KOReader version: up to 462
- Device: Kobo aura HD, should be device independent
#### Issue

Clicking backspace deletes the character before the one on the left of the cursor. But the expected behavior is to delete the one on the left of the cursor.
#### Steps to reproduce

https://github.com/koreader/koreader/blob/fd39016c87aaa8ee99b5ae236bd439798750ca62/frontend/ui/widget/inputtext.lua#L172, this line should be swap with the one above.

**Comment by houqp** [comment]
Yup, are you going to submit the PR?

**Comment by Hzj-jie** [comment]
Sure.

**Comment by Hzj-jie** [comment]
The bug looks complex than my expectation, I cannot reproduce it on Android or emulator. Root cause is still unknown.

**Comment by Frenzie** [comment]
I can't reproduce this on my H2O on the current 1b700c0 (however, I've never noticed such a thing happening).

**Comment by Frenzie** [comment]
@Hzj-jie Can you still reproduce this on your Aura HD?
