### ISSUE TITLE
Black bar under screen

### ISSUE THREAD

**Issue by pavlukivan** [koreader/koreader#2077]
- KOReader version: 2016.05.29
- Device:Оnyx boox C67ML Darwin, android 4.2.2
#### Issue

Black bar under screen in koreader app only
![8190987](https://cloud.githubusercontent.com/assets/9590981/15997570/71b3a8c6-3157-11e6-9ef1-746b2e276b07.jpg)
![8190990](https://cloud.githubusercontent.com/assets/9590981/15997571/71b3cd7e-3157-11e6-9cda-791e0c0adcbb.jpg)
#### Steps to reproduce

download, install and launch koreader

**Comment by chrox** [comment]
Will be fixed by #2102.

**Comment by pavlukivan** [comment]
The black bar is still there...

**Comment by Frenzie** [comment]
Is this still an issue after koreader/android-luajit-launcher#63?

**Comment by Frenzie** [comment]
Closing due to lack of response. Feel free to reopen if it's still an issue.
