### ISSUE TITLE
KOReader on Onyx Boox Darwin

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2090]
* KOReader version: Latest Nightly and Stable by June 5, 2016 (probably, 431)
* Device: Onyx Boox Darwin (C67ML, E-ink Carta display)
* Issue Origin: [4pda](http://4pda.ru/forum/index.php?showtopic=734837&view=findpost&p=50168619)

#### Issue
Black strip on screen when KOreader is open:
![dsc02836](https://cloud.githubusercontent.com/assets/6279855/16188647/61e2fafe-36f8-11e6-8649-6354b04c2712.jpg)

![dsc02839](https://cloud.githubusercontent.com/assets/6279855/16188651/64081058-36f8-11e6-8c2c-70842e77f562.jpg)

#### Additional Suggestion for Android
The author also asks, how about allowing KOReader to install on sd card?

**Comment by chrox** [comment]
Duplicated to #2077, closing this now.
