### ISSUE TITLE
Info line not updated after standy

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#2091]
- KOReader version: koreader-kobo-arm-linux-gnueabihf-v2015.11-431-gc0846ee.zip
- Device: Kobo
#### Issue

Neither the battery status nor time are updated when switching on after standby. I have to turn the page first.

**Comment by djalma2k** [comment]
I found that the current behaviour is useful in case as for example you want to check, (in an easy way), the battery drop between "the uses". ( I know that it isn't an exact measurement... :P )

Regards.

**Comment by hurzl** [comment]
I would prefer the status being the actual status and not some values of the past.

**Comment by houqp** [comment]
Should be a simple fix, tagged for next stable release.
