### ISSUE TITLE
[Bug] Crash using the frontlight toggle button

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#2092]
* KOReader version: 2b35e40 (2015-11-477)
* Device: Kobo Glo HD

#### Issue
A crash occurs when a number/value is written in the fl box and the toggle button is pressed. ( If you wrote a value in the box, set the fl, erase the value and finally press the toggle button then NO crashes occurs ) 

```
/luajit: frontend/ui/widget/textboxwidget.lua:177: attempt to index a nil value
stack traceback:
	frontend/ui/widget/textboxwidget.lua:177: in function '_findCharPos'
	frontend/ui/widget/textboxwidget.lua:58: in function 'init'
	frontend/ui/widget/widget.lua:39: in function 'new'
	frontend/ui/widget/inputtext.lua:100: in function 'initTextBox'
	frontend/ui/widget/inputtext.lua:188: in function 'setText'
	frontend/ui/widget/inputdialog.lua:180: in function 'setInputText'
	frontend/apps/reader/modules/readerfrontlight.lua:96: in function 'callback'
	frontend/ui/widget/button.lua:172: in function 'action'
	frontend/ui/uimanager.lua:455: in function '_checkTasks'
	frontend/ui/uimanager.lua:602: in function 'handleInput'
	frontend/ui/uimanager.lua:693: in function 'run'
	./reader.lua:172: in main chunk
	[C]: at 0x0000bea5
```
#### Steps to reproduce
1) Write any value in the FL box
2) Press the toggle button

Regards.

**Comment by houqp** [comment]
This is a regression caused by a new feature added in textboxwidget. I will take a look at it tomorrow.

**Comment by djalma2k** [comment]
I don't know if it's related to #2028 but a bug related with the inputbox is still present in this version #2106 :
1) Write anything in any inputbox ("light control", dictionary...)
2) Long press the "backspace" key.
*****
And a 2nd one I need to recheck is using any type of characters (unexpected ones) in the light control box. I had a problem with it since my last reported issue but I haven't the ereader right now... If I don't remember bad the crash.log is exactly the same as the "backspace" issue... then I need to recheck it with the new pr #2016.
Regards.

**Comment by chrox** [comment]
Thanks for your report. I'll fix it later.
