### ISSUE TITLE
FR: Ability to edit the IP:PORT of Wireless device

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2094]
Hi

It looks like Koreader does some auto discovery to find the Calibre wireless connection which means that this can only work in a local network. I forward ports so that I can connect as a wireless device even when I am not around. That is why it would be nice if the user can edit the ip:port combo so that the user can access as aCalibre device from non local networks.

thanks

**Comment by chrox** [comment]
Duplicated to #1475.
