### ISSUE TITLE
Changing the gesture to adjust Frontlight

### ISSUE THREAD

**Issue by Immick** [koreader/koreader#2096]
- KOReader version: all
- Device: Kobo Glo HD
#### Issue

As known to adjust Frontlight on Kobo devices you have to use _two fingers_.  In nickel you need to use only _one finger_ on the left side of the screen. I guess the second way (like in Nickel) is more comfortable. 
So maybe someone knows how to implement adjusting Frontlight by swiping up and down with **one finger on the left (right) side of the screen**?

On mobilread there is already the [solution](http://www.mobileread.com/forums/showpost.php?p=3337353&postcount=20) but here the sliding up or down dose not behave exactly the same as nickel. It will not refresh the frontlight level as you slide, but only after finishing the gesture.

So the good idea is create the same behaviour as in nickel.

Thank you!

**Comment by houqp** [comment]
I think it's better to make it configurable, preferably with a plugin. Someone else will prefer two finger scroll ;P

**Comment by Brnoch** [comment]
This post made me discover this useful functionality... 
For me the fact that you need to use two fingers is not a big deal.
But I'd like to use it to disable / enable the front light: could it set the light to 0 ? Presently it can't go under 1.

**Comment by chrox** [comment]
On kobo it does not decrease to 0 because of [this](https://github.com/koreader/koreader/blob/master/frontend/device/kobo/powerd.lua#L8-L10):
```
local KoboPowerD = BasePowerD:new{
    -- Do not actively set front light to 0, it may confuse users -- pressing
    -- hardware button won't take any effect.
    fl_min = 1, fl_max = 100,
    fl_intensity = 20,
    restore_settings = true,
    fl = nil,
```
So this is by design, but it could be optimized for example only for devices that have hardware light toggler button.

**Comment by Brnoch** [comment]
Could be great if you could allow to decrease the light to 0 on devices like the Kobo Glo HD!

**Comment by robert00s** [comment]
I think its done in kobolight plugin
https://github.com/koreader/koreader/blob/master/plugins/kobolight.koplugin/main.lua

**Comment by Brnoch** [comment]
Yes, it works!
