### ISSUE TITLE
use epub test suits in unit and regression tests

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2100]
@frankyifei mentioned a good epub2 test suite at: https://code.google.com/archive/p/epub-conform.
I noticed they also had one for epub3 at: https://github.com/IDPF/epub-testsuite

We should leverage these testsuite for our own unit test and regression test.

**Comment by frankyifei** [comment]
+1

**Comment by poire-z** [comment]
Not planning on this - and done without for many years - and updating tests for each new fix/improvements in crengine would be nightmarish.

**Comment by Frenzie** [comment]
I disagree, at least about the nightmarish part.

Basically you'd write tests like:

```html
<style>
p::first-letter {font-weight:bold}
</style>
<p>bla</p>
```
should render the same as:
```html
<p><b>b</b>bla</p>
```

That has its limitations, but that's how those tests (like for CSS2) already work.

(But the issue definitely doesn't need to remain open. Either someone will do it or they won't.)
