### ISSUE TITLE
One default font for all books

### ISSUE THREAD

**Issue by Immick** [koreader/koreader#2103]
- KOReader version: all
- Device: all
#### Issue

I'm wondering is there a way to setup one default font for all books? There must be an option for it.
And secondly - sometimes KOReader cannot override font in EPUB. SO there must be also optin that will allow to turn off internal font (like it madein CoolReader).

Thank you!

**Comment by KenMaltby** [comment]
Have you tried the "Set render style" option "clear all external styles"?

You can set the default font as on of the options for a "Long Press" on the font listing.

**Comment by Immick** [comment]
> Have you tried the "Set render style" option "clear all external styles"?
Yes, I've tried it. I set "clear all external styles" and then tried to change the font (in epub) an nothing was changed.

> You can set the default font as one of the options for a "Long Press" on the font listing.
After Long press I set the chosen font as the default. But htne when I open other books (expecting to see the default font) I get another font.

**Comment by KenMaltby** [comment]
I guess I should have asked if you had turned off the "Embedded Style" option, under the bottom reader menu's Gear Tab/Icon.  I usually try that first.  

Some epubs make it harder than others, to change the font.  It  may come down to having to change the epub itself.  Publishers of prose and poetry can be the most aggressive about maintaining control over how the text is presented.

**Comment by yarulan** [comment]
Same thing. Setting default font doesn't work. I use fb2's.

**Comment by poire-z** [comment]
Some enhancements for default font to be even more default were made in #3149.
Also see https://github.com/koreader/koreader/pull/3149#issuecomment-326819972 if you want even more defaultness.
Setting the default font for all books can be done by holding on the font name in the Change fonts submenu (it will propose you to set it as default or fallback font.

**Comment by poire-z** [comment]
This is no more an issue: we can set a default font, and have style tweaks to disable publisher's font.
