### ISSUE TITLE
Feature for pdfreflow

### ISSUE THREAD

**Issue by selohamon** [koreader/koreader#2104]
When I am reading a PDF and click on next, sometimes I need to read the text again to know which part was, you could not show some kind of marking? So it was only read on.

**Comment by chrox** [comment]
Sorry, I don't understand what do you want. Could you explain it in more details such as what's your problem right now and what do you expect the Koreader could behave?

**Comment by selohamon** [comment]
@chrox See this picture, the last word is "adiante" 
![reader_2016-jun-26_011220](https://cloud.githubusercontent.com/assets/20133471/16360468/e5297d4c-3b3b-11e6-8ada-286a4ae314fa.png)

when I tap to go next
![2](https://cloud.githubusercontent.com/assets/20133471/16360469/ee9da86c-3b3b-11e6-9be4-008f596730f5.png)
See I made a mark after the word "adiante", this will serve to not be looking for in the text which was the last word in the middle of text.

The feature I want is that he had an appointment when there is such a case.

**Comment by houqp** [comment]
we used to gray out the previous read portion of the page after a page turn. Now sure why it was removed. I now only read books in scroll mode, which in my opinion, is the much better than the default mode and does not have this problem. I highly recommend it if you haven't tried it yet. You can enable it at the bottom configuration panel.

**Comment by chrox** [comment]
In addition to @houqp's scroll view mode, you can also show page overlap by enable it in the top menu "Page overlap" entry which is disabled by default.

**Comment by houqp** [comment]
@chrox why is the overlap disabled by default? Also thoughts on making scrollview the default behavior?
