### ISSUE TITLE
Backlight control does not work properly on C67ML

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2105]
- KOReader version:
  koreader-nightly-20160624
- Device:
  C67ML
#### Issue

The backlight control works half baked
#### Steps to reproduce

Open the light settings and put a number. Wait for the light to change (which does not happen)

Changing the light level works after enabling and disabling the light. Basically KR changes the light setting but the setting is not applied right away. I have to disable and reenable (using the hardware button) to see the new screen light setting.

It seems to work better on my other android devices although the degree of the light setting is different on different models ( like amoled vs ips). The same number can mean different intensities on different devices.

thanks

**Comment by gerroon** [comment]
Hmmm

Something  is wonky on my other android devices. It seems like when I set it the first time my screen goes black (on Amoled)

**Comment by chrox** [comment]
Could you adjust the light intensity with two-finger vertical swiping?

**Comment by gerroon** [comment]
@chrox 

Swiping works but it is like the original post. I have to disable and enable the light via the hardware ey to see the actual change. When I do swiping, I see the numbers changing at the top with no real affect. I have to do hardware way of toggling to get the real light intensity to be shown on the device.

**Comment by gerroon** [comment]
I wonder if this is related to the refresh issues I reported earlier.
https://github.com/koreader/koreader/issues/1955

**Comment by gerroon** [comment]
This controls brightness fine 
echo 100 >/sys/class/backlight/rk28_bl/brightness

Anyother method is not refreshing the brightness. I tried couple "lcd" brightness apps, they modify the brightness but the result is not visible right away, until I enable or disable the light or click on the tray bar

**Comment by houqp** [comment]
We control brightness through the standard android API. I think the other apps go with the same approach too. Are you saying writing to `/sys/class/backlight/rk28_bl/brightness` works without needing to toggle to refresh?

**Comment by gerroon** [comment]
@houqp 

Yes that does not require a refresh. My gut feeling is that the Android brightness settings for the einks are different that the brightness settings for the tablets with the lcds naturally. 

The apps that I tried for changing brightness for Android(including Koreader) fails to change the brightness or the frontlight right away, some sort of manual refreshing is needed. The only app that was able to do was rootdim or using the method I described above.

**Comment by houqp** [comment]
Judging from the name `rootdim`, I bet it also write to the file directly like you did ;P

Looks like we need to make a special case for C67ML in the code. Are all ONYX BOOX readers based on android?

**Comment by gerroon** [comment]
@houqp 

I am guessing that this might be an issue with all the EInk Android devices.

As far as I know Onyx makes Android devices though one of its models might be just a Linux based

**Comment by verge-36** [comment]
Hello. I have a rooted NOOK Glowlight Plus, which is also an Android based E-Ink(Carta?) device. I don't think it is an issue with all eink android devices.
Two finger vertical scrolling isn't working for me(Usually crashes). But using Menu-Frontlight to apply screen brightness works fine.Screen usually goes black when i first set it, I tap once then it is fixed.I can change it with no black screen issue, no problems until i exit the app. Can normally change it after first black screen.
My device doesn't support full screen refresh with koreader. Maybe it is in some way related? I uploaded strace and logcat to a closed issue i opened(#2034) about this btw. Hope it can be easily implemented soon :D 
--Sorry for bad english--

**Comment by gerroon** [comment]
I get the initial blackness with  my all android devices (lcd and eink)

**Comment by Frenzie** [comment]
@gerroon Is this affected by #3319?

**Comment by gerroon** [comment]
The device was sold sometime ago ;)

**Comment by Frenzie** [comment]
I'll close it as lacking information then. ;-) (It just distracts otherwise.)
