### ISSUE TITLE
Cannot use the dictionary for words placed at the bottom of the page

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2117]
* KOReader version: v2015.11-501-gb82fdc8
* Device: Kobo Glo HD

When you perform a long press on a word located in the bottom line of the page, the "Go to" fuction" is fired instead of the dictionary, even if the margin is configured to "big".

Wouldn't it be possible to disable the bottom status bar toggle switch when making a quick press, and to use the quick press for the "Go to" function ? From my point of view, this toggle switch is not really useful and can be even annoying: I often made the status bar disappear accidentaly.

**Comment by chrox** [comment]
This is by design. You need to tap the status bar until it disappears and then hold to loop up words.
Please refer to discussions on #1350.

**Comment by Brnoch** [comment]
OK. I'll do this.
