### ISSUE TITLE
C67ML the lowest brighness is not the lowest brightness

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2123]
- KOReader version: koreader-nightly-20160702
- Device: C67ML
#### Issue

Setting the light to the lowest using the finger gesture or the menu setting does not put it to the lowest possible value. I do not know what the exact range is but, I see that it is set to 3 when I quit KR and look at the light menu. The lowest light on this is 1 not 3.

I am feeling that this must be an Android sdk issue

**Comment by houqp** [comment]
Feels like a framework issue to me too. IIRC, we don't cap the minimal level in android.

**Comment by Frenzie** [comment]
@gerroon Is this still an issue?

**Comment by gerroon** [comment]
I do not have the device anymore ;)
