### ISSUE TITLE
FR: Speed up the experience on Android

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2124]
Hi

The android builds has gotten much better as far as the stability goes, there are still rough cases though.

The other issue I have with the Android builds on my tablets is that the scroll speed or the general interaction speed does not seem to increase with the process speed or the memory increasements. For instance it feels as laggy as on my octa core cpu as it does on my eink devices or eink android devices. 

It would be nice if KR improvess the interaction speed for the modern cpus especially those on lcd screen tablets. The speed is not as bad on einks because, well the screens are slow too.

**Comment by houqp** [comment]
refresh rate is hardcoded because KOReader was developed to only run on eink readers. This is something we should revisit after the next stable release.

**Comment by poire-z** [comment]
Some recent issue about that: #4470 (even if PDF/CBZ, I guess the technical details would apply too with EPUBs).

**Comment by Frenzie** [comment]
This is actually the issue I was thinking of but couldn't find. Closing in favor of #4470 which has more discussion on the topic now.

**Comment by ZZZXXX0110** [comment]
I do not think it is the same issue, as the performance issue mentioned here refers not only to panning CBZ/PDF files, but also refer to general menu performances. All the menu buttons on the Android version takes a whole second to respond after being taped, regardless what format of document is being viewed, even in the file explore view. This is again not the case when running Koreader on Ubuntu on a tablet PC.

**Comment by poire-z** [comment]
About the menu, I can see some delay if double tap is enabled.
`Top menu > Gear > Screen > Disable double tap` may help.

**Comment by ZZZXXX0110** [comment]
Double tab is already disabled, as that is the default option.

**Comment by Frenzie** [comment]
@ZZZXXX0110 That would be a Galaxy S7-specific issue then. I certainly haven't seen anything like that on my Android devices. On the Sony Xperia Ray as well as the Sony Xperia XA2 it's speedy and responsive.

> This is again not the case when running Koreader on Ubuntu on a tablet PC.

Calling one of the best tablet PCs currently available "a tablet PC" is ever so slightly unfair toward a phone, even those that are € 1 000. ;-) But yes, it isn't the case on my 2010 netbook either.

**Comment by Frenzie** [comment]
I only said one of, haha. I don't know if they updated the keyboard they try to sell with it, but I tried the one they had in the store one or two years ago and it felt atrocious. Based on previous experience I'd probably get an ASUS Flip thingy or a Lenovo something or other if I wanted something in that general direction.

> Were you using the precomplied apk fill from the release page? Or did you compile apk youself from the source?

All and more. ;-) On the XA2 it was a quick test with 2018.12 (the one I uploaded on releases because it's the easiest to get to), before I replaced Android with Sailfish.

**Comment by Frenzie** [comment]
> I replaced 23 times before I got myself a Surface Pro 4 that doesn't have any screen defect.

I'm surprised you decided to get another one! :-D

> Where do I look for the compiler error output?

Somewhere earlier, where you see the actual compiler output.

**Comment by ZZZXXX0110** [comment]
Well it did look like their quality control got better at least.

So my compile problem is like this: 
-compile:
    [javac] Compiling 5 source files to /mnt/Programs/koreader/platform/android/luajit-launcher/bin/classes
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.

BUILD FAILED
/mnt/Programs/koreader/base/toolchain/android-sdk-linux/tools/ant/build.xml:716: The following error occurred while executing this line:
/mnt/Programs/koreader/base/toolchain/android-sdk-linux/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 0 seconds
make[2]: *** [apk] Error 1
make[2]: Leaving directory `/mnt/Programs/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/mnt/Programs/koreader'
make: *** [Makefile:445: update] Error 2

I made a new issue report too, in case this is not an isolated case.

**Comment by ZZZXXX0110** [comment]
> > I replaced 23 times before I got myself a Surface Pro 4 that doesn't have any screen defect.
> 
> I'm surprised you decided to get another one! :-D
> 
> > Where do I look for the compiler error output?
> 
> Somewhere earlier, where you see the actual compiler output.

Okay now I managed to compile it for Android, but it is still just as slow as the precompiled apk :/
