### ISSUE TITLE
Android 2.2.1

### ISSUE THREAD

**Issue by medwatt** [koreader/koreader#2125]
Is there anyway I can force KOReader to install on my old Sony PRS-T1 which runs on android 2.2.1. I know its supposed to run on android 2.3 and above but is there some hack that I can try ? It will make the device super cool. Thanks.

**Comment by houqp** [comment]
We might be relying on couple APIs that's only available in 2.3+. But technically it's possible to port it to 2.1. So if you are a developer, feel free to give it a try ;P I haven't heard anyone working on it.

**Comment by medwatt** [comment]
@houqp 
I'm not a developer at all; just a guy who uses KOReader on the Onyx Boox i86 which runs android 3.0. I also have a Sony PRS-T1 (android 2.2) and thought it would be wonderful to use KOReader on it, particularly for PDF reading.

**Comment by houqp** [comment]
I think it won't even be able to start on 2.2 without patches. Is it possible to upgrade the android version on the sony reader at all?

**Comment by medwatt** [comment]
@houqp 
The last update for the PRS-T1 was about 3 years ago and the android version was 2.2.1. I wonder if it'll be possible to patch the system partition in such a way that the required dependencies will be added ? Anyway, do you see a way I can use KOReader on the PRS-T1 ?

**Comment by pavlukivan** [comment]
@medwatt, I think it's possible to upgrade your device to 2.3...
http://www.mobileread.com/forums/showthread.php?t=165938

**Comment by medwatt** [comment]
@pavlukivan 
I don't think that's a finished project. It was merely a speculation.

**Comment by Frenzie** [comment]
We'd love to do this, but unfortunately I rather doubt that anyone has the time. Android itself is already a sore point.
