### ISSUE TITLE
nested dictionary lookup doesn't work for second page of definition text

### ISSUE THREAD

**Issue by taosxx** [koreader/koreader#2126]
- KOReader version: koreader-kobo-arm-linux-gnueabihf-v2015.11-507-gef260f0.zip
- Device: Kobo Glo HD
#### Issue

It seems impossible to look up a word that's used on the second page of a dictionary definition, instead the word at the same position of the first page is searched for.
#### Steps to reproduce

From an open book (pdf, epub, etc) look up a word which will have a long definition (e.g. "in"). In the definition pop-up scroll/page down to the second page and press on a word to open its definition. The pop-up won't show the definition of the word you are looking for, but of the word that is at the same position on the first page of the initial definition (for "in").
Example: In the definition of "in" in the Collaborative International Dictionary, go to the second page, click on "sometimes" and a pop-up for "respect" will be opened. On the first page of the definition for "in" "respect" appears at the same position as "sometimes" on the second page.

**Comment by houqp** [comment]
Likely a bug introduced during recent refactoring in textboxwidget. We will make sure this is addressed before the next stable release.
