### ISSUE TITLE
problems with line breaks after umlaut characters in dictionary definitions and nested look-ups

### ISSUE THREAD

**Issue by taosxx** [koreader/koreader#2127]
- KOReader version: koreader-kobo-arm-linux-gnueabihf-v2015.11-507-gef260f0.zip
- Device: Kobo Glo HD
#### Issue

If a dictionary definition contains a word with an umlaut character and this word is located at the end of a line and exceeds it, instead of being completely pushed to the next line, a line break is introduced after the umlaut. This not only looks strange, it also negatively affects nested dictionary look-ups because you can only look-up the two parts of the word separately.
#### Steps to reproduce

Look up a word from an opened book (pdf, epub, etc). The definition must contain a word with an umlaut (or maybe other special characters) at the end of the line. If it exceeds the length of the line
the word is separated after the umlaut and you can no longer look-up the complete word.

Example (two lines from Duden dictionary defining "fröhlich"):
...
leuchtenden, heiteren) Farben der Wände; b) vergnü
gt, lustig, ausgelassen: -es Treiben; in -er Runde
...
"vergnügt" is one word and should not be broken up in two parts. Of course, neither a nested look-up for "vergnü" nor for "gt" will give you any meaningful definition.

This two lines should be actually rendered as:
...
leuchtenden, heiteren) Farben der Wände; b) 
vergnügt, lustig, ausgelassen: -es Treiben; in -er
...
For "vergnügt" a definition can be found (thanks to the recent update of sdcv).

**Comment by houqp** [comment]
Good catch, looks like a bug in our line breaking code. I have added this to the next stable release mile stone.

**Comment by taosxx** [comment]
As far as I can tell, both issues were solved a few weeks ago by PR #2356 and #2381.

**Comment by houqp** [comment]
Thanks for confirming :)
