### ISSUE TITLE
Latest nightly builds much slower than v2015.11-stable on Kobo Aura H2O (and possibly others)

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2130]
* KOReader version: v2015.11-507-gef260f0
* Device: Kobo Aura H2O

#### Issue
Koreader became much slower than v2015.11-stable. Specifically, open a DjVu file, e.g. this one:

http://libgen.io/book/index.php?md5=723C8ED0D904E5A1DF1197730515D22A

Notice that even opening the file takes 3 times longer. But this is not a main problem --- the real problem is that turning the pages is also much slower than in v2015.11-stable. So much slower that I had to go back to v2015.11-stable on Kobo Aura H2O. I only kept the latest version on Kobo Touch because it is needed there for fixing the touch screen on such devices (no, manual editing of device.lua as described in #1608 didn't work and removing the range in TouchProbe also didn't help, but upgrading the whole koreader did fix the issue on Kobo Touch).

#### Steps to reproduce

Open the above-mentioned djvu file, select Crop to "Auto" and start turning the pages. Actually, even selecting menu items feels slower and also navigating in the File Manager as well. Also, turning pages in a PDF file seems slower as well (e.g. try this one http://www.bibles.org.uk/Revelation-Text-7in.pdf.zip and compare with v2015.11-stable).

**Comment by tigran123** [comment]
Just to add that on Kobo Touch it seems to be very fast and responsive, even though the actual hardware is slower than Aura H2O. I suspect it is something to do with H2O's higher resolution...

**Comment by chrox** [comment]
No noticeable performance degeneration here on Kindle Voyage. And a snip of detailed log may be helpful to debug this issue. I suspect that double tap detection is enabled on your Kobo H2O (which should be disabled by default), so that single tap takes 0.3 sec to be detected. The rendering work won't start until the gesture is detected. If this is true, you will see "# double tap detected in slot 0" in log after two successive taps.

Note that in page flipping mode (an opened book icon on the top left corner) the "double tap detection" is turned on which is new introduced feature added after v2015.11-stable.

**Comment by tigran123** [comment]
Yes, I think you are correct --- I too have found this new option "Disable double tap" and I think it is connected to it. I mean the jerky behaviour. But the loading of djvu file being twice as slow cannot be connected to it, surely.

**Comment by tigran123** [comment]
Ah, I see what is happening: the option "Disable double tap" is IGNORED! Yes, even after the restart of koreader it still reacts to double tap by zooming in some strange location on the next page (probably being confused by autoscroll set to ON) and then one has to reset the page to normal (Crop: Auto) manually.

So, the bug is --- we still have 0.3s delay even with "Disable double tap" option turned ON. At least on the DjVu files. But on PDF files it seems to work fine. So, this is specific to DjVu.

**Comment by tigran123** [comment]
On Kobo Mini turning pages in DjVu is slower as well, compared with v2015.11-stable.

**Comment by houqp** [comment]
This is very strange, did you compare the stable version with koreader-kobo-arm-linux-gnueabihf-v2015.11-11-g16509e2.zip?

**Comment by tigran123** [comment]
Thank you, I'll test the next nightly build.

**Comment by tigran123** [comment]
Unfortunately, the problem is still there and it is so severe that I had to revert to v2015.11-stable for now. The problem is that turning the pages in DjVu files in the latest builds (I tested v2015.11-536) is about five times slower than in v2015.11-stable.

Note that you cannot see it if you just open a djvu file and start turning the pages. In fact, if you do that then the latest build appears to be just as fast as v2015.11-stable (i.e. I couldn't tap fast enough to break it). But this is irrelevant because nobody reads books just by "open a file and turn pages" --- one always _prepares_ the book for reading first, namely performs the following essential steps:

1. Enable Scroll mode On.

2. Set Crop mode to Auto.

3. Switch to Landscape mode.

4. Change eInk screen refresh to Every page (actually the problem is seen even with the default setting of "every 6 pages" but I always use "every page" setting to make the content of the page sane).

Then you can see that Koreader cannot keep up with your finger tapping the screen. It can just about turn one page per second, or even slower sometimes. But in the old version (v2015.11-stable) it was able to turn the pages as fast as a human can tap the screen (about 3-4 times a second).

For browsing scientific books it is very important to be able to turn pages quickly in both forward and backward directions.

**Comment by tigran123** [comment]
Ok, I'll close it now, because I did not provide specific numbers. The issue is elusive because for some books the latest build (549) performs as good (even feels better!) than v2015.11-stable, but for others it is slower.

But now I see that the advantages of recent new features in Koreader outweigh some possible performance degradation, so I am convinced it is better to use the latest version.

**Comment by tigran123** [comment]
Wonderful news --- I have found the cause of this slowdown. This is very interesting! :)

**Comment by tigran123** [comment]
Now, first let me re-state the problem --- djvu page rendering is very slow, but it is not "uniformly" slow, but rather every 3-4 pages Koreader process starts taking 100% of cpu and you can't turn the pages.

Specifically, you can only turn one page in 2 seconds. If you don't try to turn pages faster than that, then everything is OK. If you do, then on every second or third page it will halt and by glancing at the terminal with htop running you will know when you can safely turn the page.

So, these symptoms would suggest that this is normal behaviour, i.e. Koreader pre-decodes the following page (according to DHINTCOUNT=1 in the settings) and as it does not do this in the background (btw, this is strange --- djvulibre is linked with pthreads correctly, so why not?) the user has to wait.

So, I have been experimenting with various parameters --- djvu page cache values, Koreader's internal cache settings, DHINTCOUNT values etc etc --- many many things, but NOTHING helped.

And then I suddenly remembered that this is _only_ manifested when crop setting is set to Auto. So, as this particular book had perfectly nice consistent margins I just set the crop to Manual and --- voila! It works! I.e. I can turn about 10 pages per second with NO SLOWDOWN WHATSOEVER and htop says Koreader never uses more than 15% CPU!

So, the problem lies in the auto-crop algorithm --- something is causing it to "hickup" every 2 or 3 pages and cause Koreader to use enormous amount of CPU.

What exactly is the reason I still don't know, but at least we know two things:

1. A workaround for slow DjVu page turning --- if your book has reasonable (i.e. constant across pages) margins just set crop mode to Manual and you can turn 10 pages per second!

2. The problem is connected to crop mode: Auto, so we need to look closer at this.

**Comment by tigran123** [comment]
Reproduced on the emulator as well: if you set the crop mode to Manual and start turning the pages as fast as you can click still luajit process never goes above 10% cpu (on my reasonably fast desktop machine), but if you set it to Auto you can easily cause it to use 100% cpu and the behaviour becomes noticeably "jerky". No wonder on Kobo machine it becomes unbearable as it is about 30 times slower than a desktop...

So, we need to go into the depths of auto-crop to see what is going on...

**Comment by tigran123** [comment]
It is a call to `k2pdfopt.k2pdfopt_crop_bmp(self)` from `base/ffi/koptcontext.lua:KOPTContext_mt.__index:getAutoBBox()` that is taking all the CPU. If I comment it out then the CPU hogging problem is gone, but then (obviously) the auto-cropping feature is gone too. So, we need to figure out why is `base/thirdparty/libk2pdfopt/build/git_checkout/libk2pdfopt/koptcrop.c:k2pdfopt_crop_bmp()` so horrendously CPU resource-intensive.

More precisely, we need to figure out why this function has become so CPU-hungry recently, as in the November 2015 it was not the case.

**Comment by tigran123** [comment]
The culprit is the call to `masterinfo_new_source_page_init()` function: it takes 9 times longer than the actual job of trimming the margins, see the timings below:

```
bmp_init(): 0.000000 seconds
k2pdfopt_settings_new_source_document_init(): 0.000005 seconds
masterinfo_init(): 0.000004 seconds
bmpregion_init(): 0.000001 seconds
masterinfo_new_source_page_init(): 0.084874 seconds
bmpregion_trim_margins(): 0.010648 seconds
bmp_free(src): 0.000002 seconds
bmp_free(srcgrey): 0.000001 seconds
bmpregion_free(): 0.000001 seconds
masterinfo_free(): 0.000001 seconds
```

This is for the desktop. I suppose I should recompile and run this instrumented version on Kobo as well.

**Comment by houqp** [comment]
wow, nice catch and awesome deep dive! I don't see any computational intensive code in that function, looks like the performance hit is coming from the functions that are called by it.

**Comment by tigran123** [comment]
Actually, opening DjVu files is also made 50 times (yes, FIFTY TIMES!) slower by enabling Auto-crop. With crop set to manual the above djvu file opens in 0.3 seconds, with crop set to Auto in 16 seconds!

**Comment by tigran123** [comment]
Btw, when I said "every 3-4 pages" --- that was red herring, namely because I was using Scroll mode ON, and a page was split across 2 or 3 screen fulls, so it seemed like "every 2-3 pages", but actually the slowdown occurred every time a new physical page was cropped.

**Comment by tigran123** [comment]
@houqp Yes, you are right, it is the functions called by `masterinfo_new_source_page_init()` that are a problem. Namely, these two functions make the most of those 0.08 seconds (or 2.5 seconds on Kobo):

1. `bmp_adjust_contrast()` --- 0.03 seconds
2. `bmp_convert_to_greyscale(src)` --- 0.05 seconds

So, we need to understand if we really need "adjusting contrast" and "converting to greyscale" whatever that means in the language of kpdfopt module...

**Comment by tigran123** [comment]
Ok, this patch fixes a major part of the problem, namely the opening of DjVu file now takes not 16 seconds, but 2 seconds which is much better, but still 7 times slower than 0.3 seconds with Crop set to Manual. And Auto-crop works fine, that is about 3 page turns per second without slowing down, which is much better than one page in 3 seconds, but not as good as 10 page turns per second with Crop set to Manual:

```
diff --git a/k2pdfoptlib/k2master.c b/k2pdfoptlib/k2master.c
index fdb3136..b826ea8 100644
--- a/k2pdfoptlib/k2master.c
+++ b/k2pdfoptlib/k2master.c
@@ -231,8 +231,10 @@ printf("11\n");
 printf("22\n");
 #endif
     /* Convert source back to gray scale if not using color output */
+#if 0^M
     if (!k2settings_need_color_permanently(k2settings))
         bmp_convert_to_greyscale(src);
+#endif^M
     region->dpi = k2settings->src_dpi;
     region->r1 = 0;
     region->r2 = srcgrey->height-1;
```

Now, the above is just a hack that I used to test, of course. A proper way is to set k2settings in such a way that the above test returns 0 and `bmp_convert_to_greyscale()` is not called. I'll try to figure out what we need to set in order to achieve this.

I have tested the above on Kobo Touch, but of course will also test on all other devices I have (Kobo Aura H2O, Kobo Aura HD, Kobo Mini).

**Comment by tigran123** [comment]
No, setting dst_color = 1 is not really a solution. But commenting out the call as I did in the above hack seems to work absolutely fine. (ok, it may break some platforms which use color screens like Android tablets, so if someone considers Koreader useful on non-eInk devices, then an alternative solution should be found).

**Comment by tigran123** [comment]
Ok, I have tested my `#if 0...` hack very thoroughly and for my purposes this is sufficient --- i.e. DjVu files now open many times faster (even with Crop set to Auto) and page turning is tolerably fast (about 2-3 pages per second, i.e. 8-9 times faster than without it).

But if @chrox (or someone else) suggests a better solution that not only respects colour screens but also perhaps gets rid of (or reduces) the overhead of adjusting the contrast, that would be fantastic. That would make the Autocrop work even faster than with my hack above.

**Comment by tigran123** [comment]
Hmmm, maybe I should create a separate issue with more descriptive name as this one contains a lot of extra information, part of which may be misleading.

**Comment by tigran123** [comment]
Closing this issue as duplicate of #2205
