### ISSUE TITLE
[FR]More Contrast Settings

### ISSUE THREAD

**Issue by verge-36** [koreader/koreader#2133]
- Device:E ink device
  Would it be possible to add more contrast options? With some pdf files even the darkest option is hardly readable.

**Comment by robert00s** [comment]
Now (4 options):
![zaznaczenie_016](https://user-images.githubusercontent.com/22982594/32242588-7b40d71a-be73-11e7-982d-3581fb2da258.png)
My proposition (6 options):
![zaznaczenie_017](https://user-images.githubusercontent.com/22982594/32242653-a29953be-be73-11e7-9c47-739c5de86965.png)
or
![zaznaczenie_018](https://user-images.githubusercontent.com/22982594/32242783-f3dca88e-be73-11e7-9ecb-18fad09cdc89.png)

Any suggestions?

**Comment by Frenzie** [comment]
@robert00s The basic principle behind your frontlight widget seems more appropriate to me. Possibly in the shape of these nice little circles.

But since that would presumably take a lot more work, the second solution doesn't look half-bad.

**Comment by robert00s** [comment]
Progress bar/frontlight widget is a good idea.

**Comment by robert00s** [comment]
I think that looks better and gives more options:

![zaznaczenie_019](https://user-images.githubusercontent.com/22982594/32281270-a755d638-bf1e-11e7-85ef-a29bc36dba43.png)

**Comment by Frenzie** [comment]
Looks good to me. But was "darkest" not actually the darkest or do we simply have more options in between? (That would be good too, of course, but not quite what the OP requested. ;-) )

**Comment by robert00s** [comment]
Now:
args = {0.8, 1.0, 2.0, 4.0} 
lighter, default, darker, darkest

My proposition:
args = {0.8, 1.0, 2.0, 4.0, 6.0, 9.0, 12.0, 15.0},

**Comment by Frenzie** [comment]
It's useful to go that much higher? On my quick tests with the current options "darkest" pretty much seems to equal "black," especially on E Ink. I'd be more inclined to add more fine-grained control, such as:

```
args = {0.8, 1.0, 1.5, 2.0, 3.0, 4.0, 6.0, 9.0},
```

**Comment by seacatwu** [comment]
Can we change the args{} in the defaults.persistent.lua ？
