### ISSUE TITLE
pdf and djvu files could not be opened. Ubuntu touch

### ISSUE THREAD

**Issue by Easthy** [koreader/koreader#2135]
- KOReader version: 0.0.1 (latest on 1 July 2016, possibly v2015.11-505-g30a9f73)
- Device: BQ Acquaris E5 HD Ubuntu Edition
#### Issue

.pdf and .djvu files could not be opened, koreader closes
#### Steps to reproduce

Try to open .djvu or .pdf files

Here logs after trying to open pdf file and djvu file:
https://yadi.sk/d/Sx5VYgctt383a

**Comment by chrox** [comment]
The log file shows a segmentation fault problem. Could you find the `core` file it dumps?

**Comment by houqp** [comment]
Perhaps toolchain issue? It's weird that canonical does not provide official cli toolchain...

**Comment by Easthy** [comment]
Files from /var/crash are here:
https://yadi.sk/d/Sx5VYgctt383a

**Comment by Frenzie** [comment]
Is this still an issue?

**Comment by Frenzie** [comment]
Closing due to lack of response.
