### ISSUE TITLE
highlighting and one-letter words issue in epub

### ISSUE THREAD

**Issue by supercoil** [koreader/koreader#2136]
- KOReader version: koreader-stable-v2015.11
- Device: Kobo Glo HD

I've had a look at other highlighting issues; don't know whether this one's related to any of them. It occurs in epubs, but not pdfs. When I highlight a word and there is a one-letter word to the left of it, this gets highlighted as well. (And vice versa: trying to highlight a one-letter word highlights the word to the right too.) This doesn't happen when I highlight a word with a one-letter word to the right of it. Perhaps not a big problem for highlighting as such, but the dictionary (obviously) doesn't recognise these random word pairs.

**Comment by Frenzie** [comment]
Could you test this with the upcoming nightly to see what happens? (So not v2015.11-935-g1b700c0.)

**Comment by supercoil** [comment]
I tried nightly v2015.11-947-ga6ca0f9: problem fixed, thanks.

**Comment by Frenzie** [comment]
Thanks @poire-z!
