### ISSUE TITLE
missing characters with diacritics in on-screen keyboard

### ISSUE THREAD

**Issue by supercoil** [koreader/koreader#2137]
- KOReader version: koreader-stable-v2015.11
- Device: Kobo Glo HD

I'm using a Polish dictionary, but I'm having trouble looking up words: as far as I can tell a few letters from the Polish alphabet with diacritics are missing from the on-screen keyboard. They are:
a and e with ogonek: ą ę
l with stroke: ł
z with acute and with dot: ź ż

Edit: added z's

**Comment by houqp** [comment]
I am not an expert in keyboard layout. Which keys do you think we should assign those letters to? You can tweak and test the layout by editing this file: https://github.com/koreader/koreader/blob/master/frontend/ui/data/keyboardlayouts/yazhert.lua.

**Comment by supercoil** [comment]
OK, I've had another look at the layout. I see there are basically three categories/groups of keys you can switch between with the three keys at the bottom left: "latin", "cyrillic", "diacritic" (which also includes ligatures etc.). All three include numbers. That's useful for "latin" and "cyrillic" – so you don't have to switch all the time – but I think you could do away with them in the third group: afaik no language has exclusively letters with diacritics, so you're going to have to switch between "latin" and "diacritic" anyway. That would free up ten keys for something else. Of course this would require some rearrangement to get upper case and lower case on the same key for the new letters. I'll have a look at the layout file later to see if I can come up with something.

BTW, I noticed the ç (c cedilla) appears on the keyboard twice in the "diacritic" group, once on the top row and once on the bottom row. That's one key you could replace withot rearrangement.

**Comment by supercoil** [comment]
OK, I played around with the keyboard layout a bit, but I wasn't sure what the best layout would be. Then I decided to have a closer look at how complete the set of latin letters with diacritics is in the first place in the current layout; so far I've found 25+ from different languages that are still missing, so I don't think it's really worth trying to rearrange the current layout, because you're never going to fit all of them in. I think the best solution would probably be to have language specific layouts. You could then also have alphabets other than latin and cyrillic, of course.

**Comment by houqp** [comment]
Thanks for looking into it. Yes, if there are too many to cover, we should create language specific layouts and let users switch between them. Perhaps you can help create the polish layout? I have no idea how the standard polish layout looks like ;P

**Comment by hurzl** [comment]
The numbers are hidden behind the symbols, I think it should be the other way around?

**Comment by houqp** [comment]
Problem being there is no enough space to put the numbers in the non-symbol tab. What's your suggestion?

**Comment by hurzl** [comment]
Show symbols on shift, numbers without shift

**Comment by chrox** [comment]
Perhaps we can have dynamic keyboard layout candidates that will change with the recently used interface languages. Presumably, one would use the same input language with the display language.

**Comment by houqp** [comment]
> Show symbols on shift, numbers without shift

Shift maps to capital letters though

> Perhaps we can have dynamic keyboard layout candidates that will change with the recently used interface languages. Presumably, one would use the same input language with the display language.

+1

**Comment by hurzl** [comment]
> Shift maps to capital letters though

I mean on the symbols page. Like in Android where you switch from letters to numbers+symbols

**Comment by houqp** [comment]
Still not quite following. When you click the sym button, we currently does switch to numbers+symbols laytout.

**Comment by hurzl** [comment]
I only see symbols and no hint that I can get numbers with shift.
