### ISSUE TITLE
Disable double tap option has no effect for DjVu files

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2141]
* KOReader version: v2015.11-507-gef260f0
* Device: Kobo Aura H2O

#### Issue
For djvu files double-tap seems to be always active, regardless of the option "Disable double tap" in the "Screen" section of menu. I did remember to restart Koreader after setting the option --- still, if I double-tap the area is zoomed in (but not the area I double-tap on --- rather, some strangely picked area from some other (usually next) page --- but this is a separate bug, I guess).

#### Steps to reproduce
Open a djvu file, but first make sure that "Disable double tap" option is ticked. Now double tap on some area. Nothing apparently happens, but now turn to the next page and you will see that some chunk of it got zoomed in to enormous scale. Before doing all this don't forget to set "Crop" to "Auto" and "Scroll" to "ON" (this is the first thing one normally does when reading djvu files anyway).

**Comment by tigran123** [comment]
I forgot to add in the description that if this implies that we always have a delay of 0.3s when turning a page in djvu files then this is a serious "show-stopper" bug, because for scientific literature you often need to browse through the pages quickly (e.g. to go back to some formula referred to later).

**Comment by tigran123** [comment]
Oh, actually, I was about to comment that the double tap which happens with "Disable double tap" turned on is of a completely different nature. Namely, instead of zooming in to a small rectangle around the area tapped it chops the margins off. Namely, this is what happens in a PDF file. But in a DjVu file it (presumably) attempts to do the same, but miscalculates and ends up zooming in some strange rectangle on some other page (e.g. next page, with scroll set to On).

**Comment by tigran123** [comment]
Excellent work, I am using build v2015.11-536 on all my Kobo devices (Aura HD, Aura H2O, Touch and Mini) without any problems. The last annoying thing that remains in Koreader is that it is impossible to distinguish between files with long filenames in the File Manager, so, if you have two books, say, called "Principialnye-voprosy-kvantovoj-mexaniki-1966.djvu" and "Principialnye-voprosy-kvantovoj-mexaniki-1988.djvu" you just have to remember that the 1988's edition is 2.1MB in size, whereas the 1966 edition is only 2MB.

It would be very nice to have "long touch" on a filename popup a window displaying the full filename (if necessary line-wrapped).

**Comment by KenMaltby** [comment]
What is working for my more casual reading, is to change the "c-font" settings in menu.lua widget.  I am now using (18) but (16) was quite readable, on my AuraHD.  I also set "Line 374: Screen:scaleBySize(46)," to (28), to adjust number of lines per page.  This, of course affects some other menus, but it has not been a problem.
