### ISSUE TITLE
Book status not available for djvu files.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2142]
* KOReader version: v2015.11-507-gef260f0
* Device: Kobo Aura H2O.

#### Issue
Why is the "Book status" option in the menu restricted to PDF files? It should work just as well with DjVu files as there is nothing PDF-specific there.

#### Steps to reproduce
Open a djvu file and notice that "Book status" option (place where you can rate the book and leave comments) is not available.

**Comment by houqp** [comment]
Yeah, this is expected. Someone just need to add djvu support.
