### ISSUE TITLE
Koreader crashes often with new Android builds

### ISSUE THREAD

**Issue by verge-36** [koreader/koreader#2150]
* KOReader version:v2015.11-507-gef260f0(crashes frequently)
* Previous version:v2015.11-371-g24a30cb(crashes 1,2 times a day)
* Device:Nook Glowlight Plus

#### Issue
Koreader crashes frequently.Here is logcat attached. Couldn't find any logs in koreader directory.
[NOOK.tar.gz](https://github.com/koreader/koreader/files/356167/NOOK.tar.gz)
#### Steps to reproduce
Open the app. Start Reading a book. In a few minutes Koreader crashes.Reading PDF files and tapping a lot(5-6) and swiping also make crashes more frequent.

**Comment by houqp** [comment]
Hm.. I have never seen this before. looks like luajit issue. Can you try version 483 to help narrow down the commits?

**Comment by verge-36** [comment]
Here:
[Crashlog_483.tar.gz](https://github.com/koreader/koreader/files/356495/Crashlog_483.tar.gz)
This survived a little longer than the newer version.

**Comment by houqp** [comment]
Same issue as the last one. Still looks like a LuaJIT issue to me:

```
I/DEBUG   ( 2032): memory map around fault addr 704d8a40:
I/DEBUG   ( 2032):     6e5e0000-6e5e1000 rw- /data/data/org.koreader.launcher/files/libs/libk2pdfopt.so.2
I/DEBUG   ( 2032):     6e5e1000-704f4000 rw- 
```

Perhaps it's trying to execute a JITed machine code on a rw memory region.

Does KOReader ever work for you before?

**Comment by verge-36** [comment]
At first There were some problems with UI not showing up , but after using the patch here:[http://www.mobileread.com/forums/showthread.php?t=271505] it kinda worked.
I think after a while this patch was merged or the issue was fixed because i didn't need this patch anymore. 
Sometimes refused to show UI but killing it and starting again almost always fixed it. Didn't see any Crashes except once or twice. In fact I've been trying to get koreader-android-arm-linux-androideabi-v2015.11-371-g24a30cb version to crash but haven't succeeded so far.

**Comment by verge-36** [comment]
Closing this issue since latest versions do not have this problem.
