### ISSUE TITLE
Add a "save button" for PDF

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2152]
* KOReader version: All
* Device: All

#### Issue
Dunno if I can post a suggestion here. But you can only save the pdf files if u exit koreader. To make it more praticte and avoid losing the highlights, I think a "save button" for PDF would be nice. Thanks
#### Steps to reproduce
PDF only saves if u leave koreader

**Comment by houqp** [comment]
I think the right approach is to persist every change immediately so users don't have to worry about this anymore. Then the `save button` will become redundant.

As a temporary workaround, we actually have a setting that you can use to force koreader to flush settings to disk on every page turn. You can enable this behavior by setting `DAUTO_SAVE_PAGING_COUNT` to `0` in `defaults.persistent.lua` file.

**Comment by Eduardomb22** [comment]
Thanks for the reply. It worked and solved my problem with some PDFs files

**Comment by houqp** [comment]
You should be able to set it to 0 without crashing with the next release.
