### ISSUE TITLE
Settings in defaults.persistent.lua

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#2154]
* KOReader version: newest
* Device: kobo aura

#### Issue
I have set DSCROLL_MODE = 1 in defaults.persistent.lua but it doesn't work. I have to set it for every single PDF I open.
And is there a setting to get auto scale by default for PDFs?

**Comment by houqp** [comment]
The setting is working for me. Note that it only applies to new books that you have never opened before. Do you have other settings in `defaults.persistent.lua`?

**Comment by hurzl** [comment]
Of course it's about new PDFs. I copied the whole defaults.lua.
Btw. the scale setting shows "auto" by default, but scales to whole pages. Only when I set it manually to auto again it actually scales.

**Comment by chrox** [comment]
In the bottom menu you can long-press on the scroll option to make it the default mode for new PDFs. I don't think the `DSCROLL_MODE ` global variable is valid for PDF.

**Comment by hurzl** [comment]
Ok I did this but it opens new PDF full-page

**Comment by chrox** [comment]
So could you make it clear that you want to auto "crop" the page margins other than make the pages "scroll"? If that's true, you need to long-press on the "auto crop" option.

**Comment by hurzl** [comment]
I want both. Scroll works now by long-click, but not the file. Auto crop doesn't work by default.

**Comment by chrox** [comment]
Then you can go to the "set zoom mode" options in the upper menu and long press on the "zoom to content width" option which will do what you want.

**Comment by hurzl** [comment]
I don't see a "zoom mode" setting in the upper menu

**Comment by chrox** [comment]
It would be "Switch zoom mode" the third item in the second tab.

**Comment by hurzl** [comment]
Now it works, thanks. But why not by the defaults.persistent.lua?

**Comment by chrox** [comment]
There is no "zoom mode" settings in defaults.persistent.lua and eventually we will remove all settings in defaults.persistent.lua and settings will only be accessible in the GUI.
