### ISSUE TITLE
KOReader does not open files from Home Search (Kindle)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2159]
* KOReader version: nightly 431 and probably earlier ones 
* Device: Kindle Touch

#### Issue
KOReader does not open a book found from Kindle Search

#### Steps to reproduce
1) Go to Kindle Home
2) Start searching a book from the top bar
3) Kindle finds all suggestions
4) Hit the book of your interest
5) Something different opens, not KOReader

Example book: 
[Zhutko Джонатан Фоер - Жутко Громко и Запредельно Близко.fb2.zip](https://github.com/koreader/koreader/files/367386/Zhutko.-.fb2.zip)
It is in Russian, so I added a word 'Zhutko' for search purposes.

**Comment by houqp** [comment]
Are you using kpvbooklet?

**Comment by chrox** [comment]
What is your kpvbooklet version? In my Kindle Voyage 5.8.1 when hitting the search results in Kindle Home just like you described above it launches Koreader to open that document. I'm using kpvbooklet 0.6.3. You can try updating your kpvbooklet to the latest version and see if it still have this problem.

**Comment by mergen3107** [comment]
@houqp @chrox 
Thanks for your quick replies!
Yes, I use KPV Booklet 0.6.3, and it launches books as usual from home menu, the problem is only with found items. I don't remember if I tried that after I installed KPVB, but I didn't do anything with Kindle that might break it somehow.
Should I try to reinstall KPVB?

**Comment by NiLuJe** [comment]
@mergen3107: Which FW version is your Touch running on?

**Comment by mergen3107** [comment]
@NiLuJe 
It's 5.3.7.3, the latest Kindle Touch can have

**Comment by mergen3107** [comment]
@houqp @chrox @NiLuJe 
I am sorry guys! What a stupid mistake of me!
I totally forgot that Linux-based file systems DO pay attention to cAsE in filenames.

The reason I got so confused about KOReader not opening the book is Cool Reader 3 on Android :D
On my Nook I've read that book with many highlights. I extracted them to a .txt file. Then, in order to keep everything synced, I copied that .txt file to my Kindle too, which has a book library replica.
Now I searched for a 'word' from book's name, when I had to look for a 'Word'. However Kindle search engine found matches, not in names, but only inside file .txt file and not in the book itself. When I tried to open that .txt something strange with Kindle reader app happened - the content is way different from what it should be, but that's a different story.

**So kpvbooklet and KOReader are still the greatest on Kindle!**
Sorry for interrupting you ._.

P.S. @NiLuJe congrats on Kindle JB success! I just have seen Kindle Developers corner on MobileRead. I am really happy for you and all the JB team! Now we should expect many more reports from Kindle users :) [I hope]

**Comment by NiLuJe** [comment]
@mergen3107 : Am currently cursing Amazon and trying to make KUAL behave on new devices...

I've got my hate on.

**Comment by chrox** [comment]
Closing this now, as the OP has already figured it out.

**Comment by mergen3107** [comment]
@NiLuJe 
I wish I could help you somehow, but I don't own a new Kindle
