### ISSUE TITLE
Wrong history items deleted.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2162]
* KOReader version: v2015.11-536
* Device: Kobo Aura H2O

#### Issue
If the history list contains many items (at least two pages worth) and you delete something other than the first or the last items (especially after turning the page) it sometimes deletes a different item.

#### Steps to reproduce
With many items in the History I noticed that sometimes the wrong item is removed when you long touch and then touch "Remove this item from history". I think the text "Remove this item from history" should be replaced with "Remove 'book name...' from history" i.e. at least the beginning of the book's filename should be shown so the user knows exactly what is being removed.

**Comment by tigran123** [comment]
Just to add that to avoid "chasing red herring" --- wait until I provide detailed steps (e.g. exactly how many items in history, which item to delete, etc.) to reproduce it. I just opened this issue so I don't forget about this, as the problem really did occur.

**Comment by Hzj-jie** [comment]
I can surely add the 'Remove 'book name ...' from history' first. But I have not seen your issue before. Maybe I seldom remove item from history list.

**Comment by houqp** [comment]
I can reproduce with only one page of history. Looks like this feature is very broken right now. I actually don't even know it exists until you brought it up ;P

**Comment by Hzj-jie** [comment]
@HouQP, are you sure you can reproduce it? I have tried on emulator, and seems it works fine.

**Comment by houqp** [comment]
Yes, steps to reproduce with 3 items:

1. delete the 2nd item
2. now try delete the last item, and it won't work

If you have more than 3 items, it will start deleting the wrong item in the list.

**Comment by Hzj-jie** [comment]
Emm, interesting. Reproduced. I am working on it.

**Comment by Hzj-jie** [comment]
Found the root cause. I will fix it in PR #2164.
