### ISSUE TITLE
Disabling chapter mark indicators has no effect until restart.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2163]
- KOReader version: v2015.11-536
- Device: Kobo Aura H2O
#### Issue

If you choose not to show chapter mark indicators in the status bar then there is no warning that this setting only becomes effective after the restart of Koreader.
#### Steps to reproduce

Disable the setting "Show chapter marks" in the status bar and observe that they are still shown even after you turn a few pages.

Btw, on the subject of chapter marks --- these correspond to the lowest level of outline items, but in the old version of Koreader, if their number was too great (e.g. on some books I read there are 20,000+ of them) then the marks for the _top_ level outline items are shown instead (which are usually few). But now you either get nothing or all of them...

**Comment by Frenzie** [comment]
I can't confirm this on my H2O on 1b700c0. Flipping the switch adds/removes the TOC markers within a second or so.

**Comment by houqp** [comment]
This should have already been fixed in the last readerfooter refactoring.

We are also doing the automatic chapter level detection to find the right level to draw the markers.
