### ISSUE TITLE
cloud storage service integration

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2165]
- KOReader version:
- Device:

First of all, I dunno know how to programe, so forgive if my suggestion is very hard to do. Probably it is. 
Is it possible to add a plugin or funcition to koreader so we can access a cloud storage (onedrive, googledrive, box ) and download a book if we wanna?
Thanks for this great software.

**Comment by houqp** [comment]
KOReader is open-source, so there is no limitation on what you can add to it :) Someone just need to implement this feature.

Currently, there is a calibre companion plugin that you can use to send book to the device from your computer through wifi.

**Comment by KenMaltby** [comment]
KOReader already has OPDS support.  You might find COPS interesting, http://www.mobileread.com/forums/showthread.php?t=170903

Luck;
Ken

**Comment by Frenzie** [comment]
Closing because this is now available thanks to @robert00s in #2424.
