### ISSUE TITLE
Add a review at Book status crashs Koreader @ PW3

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2166]
* KOReader version: Lastest nightly
* Device: Kindle PW3

#### Issue
I can´t add a review at the book status menu. When I click the box, the app crash.
I´m pretty sure this worked @ some older version of Koreader.

#### Steps to reproduce

Open a PDF or EPub and go to book status menu and I try to add the review. The app crashs.

**Comment by NiLuJe** [comment]
A copy of the relevant KOReader crash.log might be helpful ;).

**Comment by Eduardomb22** [comment]
Failed loading language 'eng'
Tesseract couldn't load any languages!
Failed loading language 'eng'
Tesseract couldn't load any languages!
Failed loading language 'eng'
Tesseract couldn't load any languages!
./luajit: frontend/ui/widget/inputtext.lua:57: attempt to call method 'moveCursor' (a nil value)
stack traceback:
	frontend/ui/widget/inputtext.lua:57: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
	frontend/ui/uimanager.lua:389: in function 'sendEvent'
	frontend/ui/uimanager.lua:36: in function '__default__'
	frontend/ui/uimanager.lua:655: in function 'handleInput'
	frontend/ui/uimanager.lua:694: in function 'run'
	./reader.lua:172: in main chunk
	[C]: at 0x0000be9d
source page (0,0) - (419,595)
source page bgcolor 192
source page (0,0) - (419,595)
source page bgcolor 192
[0m[34m¨Å
[0m[0m[31mCould not find Tesseract data[0m (env var TESSDATA_PREFIX = data).
Using GOCR v0.49.

source page (0,0) - (419,595)
source page bgcolor 192


Is it something that I changed?
Another question...this tessdata, OCR? Do I have to install it? ( think off topic but I saw it into the log)
Thanks for the reply

**Comment by houqp** [comment]
broken due to recent refactoring in inputtext module. I will take a look.
