### ISSUE TITLE
language support 

### ISSUE THREAD

**Issue by thezawad** [koreader/koreader#2169]
Just a basic question.
Does it support Bengali language?
and scanned pdf?
Can I install it in Doukan?

**Comment by houqp** [comment]
We don't have volunteer working on Bengali translation right now. You are welcome to help by submitting translations to https://www.transifex.com/houqp/koreader/dashboard/.

I don't think Doukan let's you install stuff into their system. KOReader should work fine with most of the native reader systems.

**Comment by thezawad** [comment]
Thanks.
Will try to contribute to Bengali translation :-)

**Comment by Frenzie** [comment]
Good luck! :)
