### ISSUE TITLE
Statistics / All Books shows only currently opened book.

### ISSUE THREAD

**Issue by WolfBackGR** [koreader/koreader#2170]
* KOReader version:  v2015.11-485-gbfa4bcd and LATEST nighty
* Device: Kobo Aura H2O, Kobo Aura 6''

#### Issue

Is something wrong with the statistics plugin of the latest nighty builds?
I read and complete some books, but the **Statistics / All Books** always shows the stats of the currently opened book.
After some days of searching I came up with this: On latest nighties the selected option and stats of every book is stored in the current book folder as: **xxxxxxx.epub.lua** and thats all... If I want to check the stats on a specific book it must to be opened and then select **Statistics / All Books.**
On the stable Koreader version the stats info stored in the statistics folder as: **xxxxxxx.stat** file and always shows the stats info of all books at **statistics / Total**.
My first thought is to use the statistics plugin of the stable version to the latest nighty. But, in that case I loose all my tracks and stats of my reading books. Except if I'll be able to convert the **epub.lua** file to **.stat**. (I don't know how to do that, of course...)
There's anybody have a solution for that matter?

**Comment by houqp** [comment]
Confirm that it is broken by a recent refactoring. We will fix it.

**Comment by WolfBackGR** [comment]
Thanks, houqp!

**Comment by seacatwu** [comment]
kpw3 has same problem.

**Comment by robert00s** [comment]
Fixed in https://github.com/koreader/koreader/pull/2300

**Comment by WolfBackGR** [comment]
I added this on all of my devices and working just fine!!!!
Many thanks!
