### ISSUE TITLE
pressure-sensitive buttons stop working after waking up

### ISSUE THREAD

**Issue by lilchow** [koreader/koreader#2171]
- KOReader version:koreader-nightly-20160714
- Device: Kindle Voyage
#### Issue

Whenever my KV goes to sleep (either after a certain period of inactivity or after I press the power button), the pressure sensitive buttons on the bezels stops working once I wake the device up. To restore the functions, I have to exit Koreader completely by pressing on the HOME icon and select the book in Amazon's native launcher to re-enter Koreader. This issue happens consistently with no exceptions.

**Comment by chrox** [comment]
What's your Kindle Voyage firmware version and KPVBooklet version? I cannot reproduce this on my Kindle Voyage 5.8.1 with KPVBooklet 0.6.4. I usually don't exit koreader and always suspend within koreader and physical buttons (Amazon calls them whisper touch) work great after going out of suspend.

**Comment by lilchow** [comment]
My KV has the same firmware version and KPVBooklet version. I have updated my koreader since the original post twice and the issue just refuses to go away. Note that I never encounter this issue when reading .mobi files.

**Comment by Hzj-jie** [comment]
I have exactly the same issue, I doubt the root cause is 'swipe to unlock' feature, i.e. 'Special Offers'.
@chrox Does your voyage have special offers?

**Comment by houqp** [comment]
I vaguely remember you can enable/disable whisper touch by interacting with the native framework?

**Comment by NiLuJe** [comment]
Probably not much we can do, AFAICT.
