### ISSUE TITLE
OPDS: downloading with koreader results in unreadable files

### ISSUE THREAD

**Issue by Horla** [koreader/koreader#2174]
* KOReader version: v2015.11-533-g1d2150c
* Device: Android, Samsung Galaxy A3 (also tested on the kobo touch n905)

#### Issue
Downloading an ebook from the software COPS with the OPDS feed results in an unreadable file.
It seems that koreader only downloads the cover of the ebook.

The default OPDS providers from koreader work fine.

Reference: https://github.com/seblucas/cops/issues/287

#### Steps to reproduce
Downloading an ebook (epub, pdf) from the software COPS with the OPDS feed

**Comment by Eduardomb22** [comment]
Hello. 
I´ve tested with eg from COPS and worked fine here http://cops-demo.slucas.fr/feed.php

I´ve download some sherlock holmes books and can read fine at koreader.
I´m using Kindle PW3

**Comment by Horla** [comment]
I confirm that it works great with the demo feed. It seems like something is wrong with my installation.

**Comment by chrox** [comment]
Looks like that. Please feel free to reopen this if you still have this problem.
