### ISSUE TITLE
Re-opening an epub file (or switching from History) is very slow.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2175]
- KOReader version: v2015.11-549
- Device: Kobo Aura H2O
#### Issue

For some epub files (see below) the first open is quite slow, but this is expected and takes almost the same time on CoolReader (maybe 10% faster than Koreader). But all subsequent opens are quite slow as well and jumping to the file from History is also very slow, whereas on CoolReader it is several times faster.
#### Steps to reproduce

Try opening this file:

http://libgen.io/book/index.php?md5=F5A01F7C7518D2104774DBE7337B9D7C

And then quit Koreader and re-open it again. Then, open some other file and switch to this one via History.

**Comment by tigran123** [comment]
Interesting, there are multiple cache files created by crengine, look:

```
[/mnt/onboard/.kobo/koreader]# l cache/cr3cache/
total 8592
-rwxr-xr-x    1 root     root       4377600 Jul 22 10:47 Quantum-Mech-cs-2014.epub.41a0d7d6.0.cr3
-rwxr-xr-x    1 root     root       4377600 Jul 22 10:49 Quantum-Mech-cs-2014.epub.669a6827.0.cr3
-rwxr-xr-x    1 root     root           149 Jul 22 10:48 cr3cache.inx
```

**Comment by frankyifei** [comment]
I tested on emulator, 8 seconds for first open and 6 seconds for following open. This book is quite large and includes 7987 images and 8 embedded fonts. Maybe this is the reason it is so slow.

**Comment by tigran123** [comment]
Yes, of course this is the reason it is so slow, but my point was that in CoolReader subsequent opens (or switches from History) are considerably faster.

Ok, to make this more specific I must provide more information: namely, the actual timings of the first and subsequent opens on CoolReader and Koreader on the specific hardware, say Aura H2O. I will do that as soon as possible.

**Comment by frankyifei** [comment]
on my pc ,there is little difference between the two. I'll do more test

**Comment by frankyifei** [comment]
![test](https://cloud.githubusercontent.com/assets/8104251/17277109/538db258-577a-11e6-80bf-c16616c010fd.jpg)
open this book on my kindle, first time and second time

**Comment by frankyifei** [comment]
>https://github.com/koreader/crengine/blob/b49ffd4ce5b3b8dcaf933393291e90fc0d51fec3/crengine/src/epubfmt.cpp#L881

**Comment by cytown** [comment]
Why not check cache first as default behavior?  Because the file should be modified?  Then just put the file size and modify time in cache will fix.

Just as frankyifei mentioned:
I have a 14mb pure text epub, it takes 2 minutes 15 seconds to open 1st time, second time 1 minutes 15 seconds.

I wonder why it takes such long time to open with cache...

**Comment by poire-z** [comment]
Fixed in https://github.com/koreader/koreader/pull/3700 and followups.
