### ISSUE TITLE
Default sync server is down?

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2178]
- KOReader version: up to 06bd4d7
- Device: independent, but I have tried on Kobo, Kindle voyage and Android
#### Issue

Devices cannot connect to default sync server. Unknown error reported.
#### Steps to reproduce

If it's expected, I happen to setup a sync server at hzj-jie-ubuntu.westus.cloudapp.azure.com:7200. Feel free to try it and update the default setting.

**Comment by houqp** [comment]
I can't ping vislab.bjmu.edu.cn either. I think at some point we should maintain one sync server for the community together to share the operational work load. We are already a globally distributed team so someone is always online to help fix issues.

**Comment by Hzj-jie** [comment]
Is it a temporary issue?

**Comment by houqp** [comment]
I don't know, but the server is still unreachable for me.

**Comment by Hzj-jie** [comment]
-_-
I can provide a dedicated machine on Windows azure with 0.5 core and 784MB memory or share one machine with 1 core and 1.75GB memory. Both should have ~200GB harddisk. Is it OK for a permanent server?

**Comment by houqp** [comment]
I also have a linode instance to share, but the spec is not as good as your shared azure machine. How does azure charge for the bandwidth?

@chrox do you mind migrating the service to a shared server so we can manage it together?

**Comment by Hzj-jie** [comment]
First 5 GB /Month 1	Free	Free	Free
5 GB - 10 TB 2 /Month	$0.087 per GB	$0.138 per GB	$0.181 per GB
Next 40 TB 
(10 - 50 TB) /Month	$0.083 per GB	$0.135 per GB	$0.175 per GB

It's pretty cheap.

**Comment by houqp** [comment]
Let's wait for confirmation from chrox. He probably also has the stats for the current bandwith usage. I am pretty sure it's less than 5G/month :P In case it's not, we can use my linode instance, it has 2TB per month cap, so should be enough.

**Comment by houqp** [comment]
Also, depends on how it goes, we might need to setup POP for countries like China to reduce latency or even circumvent GFW >_<

**Comment by Eduardomb22** [comment]
@Hzj-jie Sorry for enter the conversation. But can u give the website of this webhost you posted? I wanna host something and seems nice. Thanks

**Comment by chrox** [comment]
Yes, the campus network infrastructure was in upgrading in recent days. And the network is back now. Go ahead with a new default sync server. It won't use more than 100MB of bandwidth per month, as the current default sync server has less than 1 thousand users.

**Comment by houqp** [comment]
@Hzj-jie let's use your azure server then? I can chip in too if the sync service is causing you extra money. I also have the koreader.rocks domain, so let's put it under `sync.koreader.rocks` subdomain?

**Comment by Hzj-jie** [comment]
Sure, no problem. I will give your access soon.

**Comment by Frenzie** [comment]
See my comment https://github.com/koreader/koreader/issues/2889#issuecomment-324294852

The sync.koreader.rocks server results in an `sslv3 alert handshake failure`.
