### ISSUE TITLE
[FR] Whispered sync without user confirmation

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2179]
- KOReader version: up to 06bd4d7
- Device: independent
#### Issue

Several suggestions to kosync.koplugin/main.lua.
1. Around line 302, tostring(body.progress) ~= tostring(body.progress) seems strange to me. Considering the data sent to sync server are always string, they may not really useful. And around line 310, the elseif does not use exactly same condition.
2. If users actively clicked 'Sync now', i.e. manual == true in KOSync:getProgress function, do we really need to show the confirmation box? It's doubtable, so I would like to know your opinions.
3. Should we ignore a very small progress difference? (If it's really progress instead of pages.) Screen resolutions / font size settings may be various across different devices. And I believe this is the very common scenario -- I cannot really imagine a regular user would have two exactly same devices with exactly same configuration. A very small progress difference may not be able to avoid, even two devices are showing almost exactly the same page. One may just be several lines in advanced. I would suggest to round the percent.
4. Also sync backward. It's useful if users read one book for more than once.
5. Do we need to sync progress to the same device? I have got 'Sync to furthest location ... from device ...' several times, even I am reading only on the same device. It may also relate to the 4th issue, I cannot tell the root cause for now. But instead of device model, a device mode + a random string should be able to represent a unique device.
6. As title, whispered sync without user confirmation.
7. Most important, progress won't sync until file close. i.e. If I forgot to close a doc on one device, it won't sync to another. A simple solution is to respect DAUTO_SAVE_PAGING_COUNT, i.e. sync after several page turning. A complex but comprehensive solution is to use both a sync interval and page turning event. Personally I prefer the first solution. As it's simple, and I always set DAUTO_SAVE_PAGING_COUNT to 5 to avoid a crash to lost my recent comments / highlights / progress, since I am always using dev version.
#### Steps to reproduce

To address the above issues, I have changed kosync.koplugin/main.lua a little bit in my clone. Feel free to have a look at master http://github.com/hzj-jie/koreader/. I will double confirm everything works well, and push PR later.

**Comment by houqp** [comment]
> 1. Around line 302, tostring(body.progress) ~= tostring(body.progress) seems strange to me. Considering the data sent to sync server are always string, they may not really useful. And around line 310, the elseif does not use exactly same condition.

Agreed.

> 2. If users actively clicked 'Sync now', i.e. manual == true in KOSync:getProgress function, do we really need to show the confirmation box? It's doubtable, so I would like to know your opinions.

I don't have a strong opinion on this. Ideally the sync functionality should be smart enough to always sync from the correct device, then this is redundant. On the other hand, user might want to know exactly which device is the source so koreader won't get the wrong progress.

> 3. Should we ignore a very small progress difference? (If it's really progress instead of pages.) Screen resolutions / font size settings may be various across different devices. And I believe this is the very common scenario -- I cannot really imagine a regular user would have two exactly same devices with exactly same configuration. A very small progress difference may not be able to avoid, even two devices are showing almost exactly the same page. One may just be several lines in advanced. I 
would suggest to round the percent.

Agreed. Ideally though, the sync should also handle progress within a page, meaning the progress should be made up of (pageno, coordinations within the physical page).

> 4. Also sync backward. It's useful if users read one book for more than once.

Perhaps it's better to sync against progress with the latest timestamp.

> 5. Do we need to sync progress to the same device? I have got 'Sync to furthest location ... from device ...' several times, even I am reading only on the same device. It may also relate to the 4th issue, I cannot tell the root cause for now. But instead of device model, a device mode + a random string should be able to represent a unique device.

That sounds like a bug to me. We should totally generate a random UUID for each device.

> 6. As title, whispered sync without user confirmation.

looks cool :)

> 7. Most important, progress won't sync until file close. i.e. If I forgot to close a doc on one device, it won't sync to another. A simple solution is to respect DAUTO_SAVE_PAGING_COUNT, i.e. sync after several page turning. A complex but comprehensive solution is to use both a sync interval and page turning event. Personally I prefer the first solution. As it's simple, and I always set DAUTO_SAVE_PAGING_COUNT to 5 to avoid a crash to lost my recent comments / highlights / progress, since I am always using dev version.

Both solutions sound good to me.

**Comment by Hzj-jie** [comment]
One more issue, progress sync feature is conflict with document saving feature. i.e. MD5 hash value will also change if a document has been changed by saving feature. I would also suggest to create MD5 hash at the very first time a new file has been opened, then store it in the metadata. So further change to the document won't impact its progress record in the sync server.

**Comment by houqp** [comment]
> One more issue, progress sync feature is conflict with document saving feature. i.e. MD5 hash value will also change if a document has been changed by saving feature. I would also suggest to create MD5 hash at the very first time a new file has been opened, then store it in the metadata. So further change to the document won't impact its progress record in the sync server.

Makes sense. A little optimization, the md5 is only needed the first time user changes a document. So we can delay the hash creation til that time.

> And syncing against the latest timestamp is conflict with 'Sync now' feature, as we always push progress of this device to the sync server. A potential solution would be using a pull progress and a push progress instead of one sync now function.

To reduce the RPC calls to the server, we can attach the last update from server timestamp with the push request. On the server side, if the timestamp is older than the latest timestamp, reject the push and send back the new progress.

**Comment by Hzj-jie** [comment]
1. If the user recently enabled sync feature, but has not disabled save-document feature before. This behavior will be confusing. Progress of two same files (PDF files in current scenario) won't be able to synchronized. Since one or two files may be changed. That's the reason I suggested to create MD5 hash value once we open a new file.
2. Do we really need to make it complex? I would suggest to remove old_percentage check between around line 100 of syncs_controller.lua (Reduce one redis read). And add one more menu item in kosync.koplugin/main.lua. 'Sync now' is a little bit confusing, especially it implies to push current progress to the server. Then we will have two menu items 'push current progress from this device' and 'pull progress from other devices'. Both of them would have very clear meaning and operations.

**Comment by houqp** [comment]
> If the user recently enabled sync feature, but has not disabled save-document feature before. This behavior will be confusing. Progress of two same files (PDF files in current scenario) won't be able to synchronized. Since one or two files may be changed. That's the reason I suggested to create MD5 hash value once we open a new file.

The sync code path will still need to check to see if there is a md5 in the metadata. If not generate one before sync. Perhaps this is too much pre-optimization. Adding an extra if branch in the open call is probably fine since it's not a hot code path.

> Do we really need to make it complex? I would suggest to remove old_percentage check between around line 100 of syncs_controller.lua (Reduce one redis read). And add one more menu item in kosync.koplugin/main.lua. 'Sync now' is a little bit confusing, especially it implies to push current progress to the server. Then we will have two menu items 'push current progress from this device' and 'pull progress from other devices'. Both of them would have very clear meaning and operations.

If we combine the push and pull actions into one request like I mentioned in the previous comment, then the "Sync now" item will make more sense.

We can create two more endpoints specifically for "push only" and "pull only" actions, and add those to the menu as fallbacks for manual control. I think in the long term, this sync feature should really be smart enough work out of the box without user interaction. It's a tradeoff between engineering effort and user experience.

**Comment by Hzj-jie** [comment]
Emmm, I think the smart way to sync is to use whisper sync as I suggested. :) But for a manual control, separating push and pull should be more clear.

**Comment by houqp** [comment]
Oh yeah, the push/pull in one request design is proposed mostly for whisper sync.

**Comment by Hzj-jie** [comment]
Then I would argue the requirement of a combined request with both push and pull.
The sync always happens in three times, - Opening a book, - Closing a book, - Page turning (If AUTO_SAVING_AFTER_PAGE_TURNS enabled.) We properly can add a forth time point, resuming the device, but it should be the same as opening a book.
- Opening a book. It seems pushing a progress during opening is not correct. The progress should be pushed already during last closing. The only possibility is Koreader crashed / device ran out of power, before the file has been actively closed. Since user is continually working on this book in this device, we can always push the progress later. So during opening stage, only pulling progress is required.
- Closing a book. We are closing the book, so there is no reason to pull the progress again. Only pushing the progress is required.
- Page turning. User is continually working on this book, we should only push the progress instead of pulling the progress.

So it seems like, we do not really need a combined request to push / pull together. What do you think?

**Comment by Hzj-jie** [comment]
Kindly ping ...

**Comment by houqp** [comment]
Sorry, I was too busy with work this week. Basically getting home at 12 every night :(

You bring up the good point. My previous assumption is wrong. I think it's better to rephrase my proposal as adding staleness check into push and pull requests. i.e. always send the request with last known state from server. Now that I think about it, the state is probably better to be represented as a unique incremental id instead of server timestamp.

> - Opening a book. It seems pushing a progress during opening is not correct. The progress should be pushed already during last closing. The only possibility is Koreader crashed / device ran out of power, before the file has been actively closed. Since user is continually working on this book in this device, we can always push the progress later. So during opening stage, only pulling progress is required.

Hmm.. Perhaps I missed something. But I feel like this is going to cause the user to lose progress during a crash:
1. start the book at page 50, progress pushed to server (state: 1)
2. turn off wifi to save power
3. read to page 150, because wifi is off, progress is only saved locally
4. close the book or reader crashed
5. turn on wifi
6. open the book. now if we always pull from the server without staleness check, the progress will be reverted to page 50.

> - Closing a book. We are closing the book, so there is no reason to pull the progress again. Only pushing the progress is required.

I agree with this one but only on the assumption that progress has been synced before the close operation. Otherwise, the following might happen:

1. on device 1, read to page 50, progress pushed to server (state: 1)
2. suspend device
3. on device 2, sync to page 50 (state: 1)
4. on device 2, read to page 150, progress pushed to server (state: 2)
5. now resume device 1 and close the book. if we don't check the staleness and just push blindly, progress of the book will be reverted to page 50.

> - Page turning. User is continually working on this book, we should only push the progress instead of pulling the progress.

Again, the following senario could happen:

1. on device 1, read to page 50, progress pushed to server (state: 1)
2. suspend device
3. on device 2, sync to page 50 (state: 1)
4. on device 2, read to page 150, progress pushed to server (state: 2)
5. now resume device 1 and turn a page. if we don't check the staleness and just push blindly, progress of the book will be overwritten to page 51.

Of course, the staleness check only makes sense if we want to support sync backwards. If we always only sycn forward, then there is no need to check the staleness. The conflict resolving strategy will be as simple as always pick the furthest progress.

**Comment by Hzj-jie** [comment]
Great points.

For scenario 1,
This won't be resolved with staleness check. i.e. The server has not idea where the 150 is coming from. But this can be resolved by my original propose. (I thought it was useless before) We should send a device id with device model. So client won't sync if the device id + model is consistent with current device. i.e. We should never sync with ourselves.

For scenario 2 and 3 are the same right?
It's more likely we need to implement pull function when suspend, and push function when resume.

**Comment by houqp** [comment]
> For scenario 1,
> This won't be resolved with staleness check. i.e. The server has not idea where the 150 is coming from. But this can be resolved by my original propose. (I thought it was useless before) We should send a device id with device model. So client won't sync if the device id + model is consistent with current device. i.e. We should never sync with ourselves.

In this case, the server will not get the 150 when we reopen the book. Let's say we keep the state id (1) from last server sync. Now when we open the book at step 6, a pull progress is sent to the server. The server will send back 50 with latest state id (1). The reader will check the latest server state with the local one. If the server state is not greater than the local one, then we can be sure that the local progress is newer than what's in the server. As a result, the reader should discard the pull result and does a push instead to push the update.

Checking against device id is also a good safe guard :+1:  And I think we should use uniq device id regardless whether this id is used to prevent one device from syncing against itself.

> For scenario 2 and 3 are the same right?
It's more likely we need to implement pull function when suspend or wifi off, and push function when resume and wifi on.

We definitely should do state sync on resume/suspend. But again, there is no guarantee that internet access is enabled during these operations. So we probably still need extra checks to handle those edge cases.

**Comment by Hzj-jie** [comment]
> In this case, the server will not get the 150 when we reopen the book. Let's say we keep the state id (1) from last server sync. Now when we open the book at step 6, a pull progress is sent to the server. The server will send back 50 with latest state id (1). The reader will check the latest server state with the local one. If the server state is not greater than the local one, then we can be sure that the local progress is newer than what's in the server. As a result, the reader should discard the pull result and does a push instead to push the update.

I cannot quite get the point, how local koreader knows the state id (1) is older than local state. Do you mean local percentage is larger than remote percentage? I think using percentage here is not a quite good choice. As users may read a book again later. If we do need a state, using UTC timestamp is a good choice. I would suggest to calculate the UTC timestamp in server layer, to avoid any misbehavior client to overwrite it unexpectedly.

> We definitely should do state sync on resume/suspend. But again, there is no guarantee that internet access is enabled during these operations. So we probably still need extra checks to handle those edge cases.

I totally agree handle those edge cases are needed. (Pulling / pushing when wifi on / off is just one of many ways we can try.) But I really do not think a combined pull / push request is a must-have. We are using three redis commands in one request, there is no atomic guarantee. So we can also pull then push in client side. Then we can keep the server simple. We may add several fields, such as timestamp, device-id, etc, in sync server. But the sync server accepts only push / pull / register / authorize requests. And we can try different solutions in client side.

**Comment by houqp** [comment]
> I cannot quite get the point, how local koreader knows the state id (1) is older than local state. Do you mean local percentage is larger than remote percentage? I think using percentage here is not a quite good choice. As users may read a book again later. If we do need a state, using UTC timestamp is a good choice. I would suggest to calculate the UTC timestamp in server layer, to avoid any misbehavior client to overwrite it unexpectedly.

Everytime KOReader communicates with the server, it record the latest document state locally. So it can use it to compare against the next server response. Essentially, this is just optimistic locking using check and set operation, where the check phrase always check against the latest state of the document. Optimistic locking usually works very well then there is little contention.

Problem with timestamp is it's physical time, meaning it will be difficult to synchronize the time between multiple servers. This will cause issues when we migrate servers or scale the sync server to multiple hosts. Using a logically ID will eliminate this issue. Of course, at the expense of implementing our own logic to increment this ID.

> I totally agree handle those edge cases are needed. (Pulling / pushing when wifi on / off is just one of many ways we can try.) But I really do not think a combined pull / push request is a must-have. We are using three redis commands in one request, there is no atomic guarantee. So we can also pull then push in client side. Then we can keep the server simple. We may add several fields, such as timestamp, device-id, etc, in sync server. But the sync server accepts only push / pull / register / authorize requests. And we can try different solutions in client side.

Oh yeah, like I mentioned in the previous comment. I think we should have separate endpoints for push/pull. I just suggest we should implement check and set logic to serialize the push/pull requests form the clients.

**Comment by houqp** [comment]
Nice, looks like redis has builtin CAS support: http://redis.io/topics/transactions#cas

**Comment by houqp** [comment]
> Emmm, get your point. You would prefer to use the way a source control system uses. Correct me if my understanding is not correct. Server will only accept a push request, if the transaction id provided by client is same as the one recorded in server. Otherwise, the client needs to pull before push.

Correct, except we can avoid the second pull action by sending the latest state in the rejection response.

> This seems too complex for our scenario. As we can always do this in client side. Before pushing a progress, we can always pull from server, compare the timestamp with local last operation timestamp, and make a smart choice. (If local last operation is early than the server timestamp, we ask users whether overwriting a newer progress is expected.)

You can still do the same optimization with timestamp. On the server, check the timestamp with the most uptodate one. If it's out of date, reject the push and send back the latest state. Then on the client side you can prompt the user for manual override. This actually requires even less code to implement than the pull before push design.

And if we are going to use timestamp as state id, we should only use timestamps from the servers. I would not trust the local client's timestamp at all.

> I do not think we really need to care too much about the time inconsistency between different servers. As the pull / push requests should not happen too frequently.

This is also a good point. But we need to make sure the client requests are properly rate limited. Because time drifts in seconds between servers is not uncommon.

**Comment by robert00s** [comment]
Whispered sync is now available. I think we can close this issue.

**Comment by Frenzie** [comment]
Alright, closing then.
