### ISSUE TITLE
Unresponsive screen on Oasis.

### ISSUE THREAD

**Issue by vincent-inspectionapps** [koreader/koreader#2181]
* KOReader version:koreader-kindle-arm-linux-gnueabi-v2015.11-533-g1d2150c
* Device:Oasis 3g, 5.7.4 and 5.8.1.0.1

#### Issue
Screen is not responsive to touches.

#### Steps to reproduce
I follow this instruction to install, http://lifehacker.com/how-to-jailbreak-your-kindle-1783864074

Tried both KPV and KUAL, same problem.

**Comment by NiLuJe** [comment]
For reference, here's the [thread on MR](http://www.mobileread.com/forums/showthread.php?t=276556).

@Hzj-jie: Do you happen to have a 3G Oasis, or a WiFi only?

My current working theory is that the 3G ones have input devices ordered differently (or an extra input device).

**Comment by vincent-inspectionapps** [comment]
@NiLuJe  I've got this myself.

[root@kindle root]# cat /proc/bus/input/devices
I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="max77696-onkey"
P: Phys=max77696-onkey/input0
S: Sysfs=/devices/platform/imx-i2c.0/i2c-0/0-003c/max77696-onkey.0/input/input0
U: Uniq=
H: Handlers=kbd event0 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0018 Vendor=0000 Product=0000 Version=0000
N: Name="SX9500 Cap Touch"
P: Phys=
S: Sysfs=/devices/virtual/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=81c

I: Bus=0018 Vendor=0000 Product=0000 Version=0000
N: Name="bma2x2"
P: Phys=
S: Sysfs=/devices/virtual/input/input2
U: Uniq=
H: Handlers=event2 
B: PROP=0
B: EV=9
B: ABS=100 7

I: Bus=0018 Vendor=0000 Product=0000 Version=0000
N: Name="bma_interrupt"
P: Phys=
S: Sysfs=/devices/virtual/input/input3
U: Uniq=
H: Handlers=event3 
B: PROP=0
B: EV=d
B: REL=3c6
B: ABS=3000000

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="cyttsp4_mt"
P: Phys=cyttsp4_mt.main_ttsp_core
S: Sysfs=/devices/platform/imx-i2c.1/i2c-1/1-0024/main_ttsp_core.cyttsp4_i2c_adapter/cyttsp4_mt.main_ttsp_core/input/input4
U: Uniq=
H: Handlers=event4 
B: PROP=0
B: EV=f
B: KEY=6420 0 0 0 0 0 0 0 0 0 0
B: REL=0
B: ABS=2608000 0

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="gpiokey"
P: Phys=
S: Sysfs=/devices/platform/gpiokey.0/input/input5
U: Uniq=
H: Handlers=kbd event5 
B: PROP=0
B: EV=3
B: KEY=2100 0 0 0

**Comment by vincent-inspectionapps** [comment]
For a testing purpose, I modified the event3 to event1, i also noticed that i need to modify two spots in the device.lua, but it is still not working.

**Comment by NiLuJe** [comment]
@vincent-inspectionapps : Perfectly normal, the touchscreen is cyttsp ;).

But thanks for that output, that's definitely helpful, and I think I have something that should work without making a mess of the code :).

**Comment by vincent-inspectionapps** [comment]
Fantastic! Thanks a lot!

I should probably learn a bit of linux and lua to help a bit with the development. :)

**Comment by NiLuJe** [comment]
@vincent-inspectionapps: Could you check if that commit does the trick for you? Thanks!

**Comment by vincent-inspectionapps** [comment]
@NiLuJe Yes, it works like a charm!

**Comment by NiLuJe** [comment]
Fantastic, thanks! :).
