### ISSUE TITLE
[FR] Show WIFI connection info somewhere

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2184]
* KOReader version: up to 0d708405
* Device: independent

#### Issue

As I recently moved from USB to dropbear, I found there is no simple way to show the device IP. Static IP is not always achievable. I have to use ifconfig in KSM terminal or ;711 page in Kindle voyage to get the info. Considering we are using Linux in for both systems, outputing a ifconfig info is not a quite big deal.

#### Steps to reproduce
I am implemented the logic in http://github.com/hzj-jie/koreader master2. But I have not found a good UI element to output the data. It seems like InfoMessage is not a quite good choice.

**Comment by houqp** [comment]
I suggest using `KeyValuePage`.

**Comment by houqp** [comment]
But of course, you need to parse the output into key value pairs :)

**Comment by tigran123** [comment]
Oh, I needed to see both IPs (wifi and usb) as well, so I just knocked up a two-liner script in vlasovsoft launcher which uses QT's `message` to show it :)

```
[/mnt/onboard/.kobo/vlasovsoft]# cat my_ip.sh 
#!/bin/sh

ethip=$(ifconfig eth0 | sed -ne 's/^.*inet addr:\(.*\) Bcast.*$/\1/p')
usbip=$(ifconfig usb0 | sed -ne 's/^.*inet addr:\(.*\) Bcast.*$/\1/p')
msgbox/msgbox -stylesheet eink.qss "IP address" "eth0: $ethip usb0: $usbip"
```

**Comment by Hzj-jie** [comment]
This should have been fixed already.
