### ISSUE TITLE
Frontlight setting ON/OFF not saved after exit.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2185]
* KOReader version: v2015.11-549
* Device: Kobo Aura H2O

#### Issue

If you start Koreader after a fresh install everything is fine --- the front light is OFF, as it should be. However, if you try setting frontlight ON (with some value, say, 23 and then click "Apply" and "OK") and then turn it OFF again (click on "Toggle", then "Apply", then "OK") the light turns ON again after Koreader is restarted. This means now there is no way to turn it OFF permanently --- every time Koreader is started, the frontlight is turned ON, i.e. one has to turn it OFF manually every time, by going to the menu, clicking on Frontlight, then click on "Toggle", then "Apply", then "OK". Very annoying...

**Comment by Hzj-jie** [comment]
The configuration of Kobo Aura highlight is synchronized with Nickel, Kobo's original system. But it requires a certain version of Nickel, which has this setting. You may want to start Nickel to confirm whether it has been updated, and turn the frontlight on and off in Nickel to make sure it creates required settings.

If it still doesn't work, you can manually create or change Nickel configuration file at '/mnt/onboard/.kobo/Kobo/Kobo eReader.conf', inserting

[PowerOptions]
FrontLightLevel=23
FrontLightState=true

in the file.

Instead of synchronizing with Nickel settings, you can also set the value to 0, and apply. It will permanently close the frontlight.

Personally I prefer the first solution, it also respects frontlight hardware button.

**Comment by tigran123** [comment]
First of all, I don't use Nickel and I am not going to boot into it because it is potentially risky --- an upgrade would wreak my whole system. So, that is not a solution.

Second, Kobo Aura H2O has no hardware button for light.

Thirdly and most importantly, your real suggestion to set the value to 0 and then apply did NOT work. That was the very first thing that occurred to me, but right now I have re-tested it just to make sure that I did everything correctly. So, I did this:

1. I enter Koreader, the front light is ON at the setting of 23.

2. I enter the setting 0, click on Apply and then on OK. The light is NOT turned OFF. Instead, it is dimmed to the lowest setting but it is still ON.

3. Exit Koreader and start it again. The light is still ON at a very annoying level of "0" --- which means you have to put the device under the table to see that the light is actually ON. So it is damaging the eyes "silently" and if you don't know that the light is ON you may not even notice it (especially at bright sunlight). At least at the setting of 23 it was quite obvious and one immediately turned it OFF by going to frontlight and clicks on Toggle to get rid of this stupid useless feature that was added to damage the quality of eInk screens (without this feature H2O's eInk screen would have been much better as it would not require the special extra coating).

So, there is still a serious bug --- there is simply no way to turn the frontlight OFF without having to reboot into Nickel.

Now, I'll try editing the file you mentioned (fortunatel,y vlasovsoft launcher includes Notepad, so this can be done without connecting to a computer) and will report if this suggestion of yours works or not (presumably one would need to set `FrontLightState=false` to turn it OFF). Even if it works, it is still a very bad solution because it should be possible to turn the light OFF completely from within Koreader.

**Comment by tigran123** [comment]
UPDATE: Yes, editing the file `/mnt/onboard/.kobo/Kobo/Kobo eReader.conf` with vlasovsoft's built-in Notepad revealed that the setting of value `0` in Koreader gets converted into `1` in that file. This is also a bug --- a setting of `0` should mean OFF.

Now, if I manually add the following line to this config file:

`FrontLightState=false`

then all is well, i.e. the front light is really turned OFF. So, to summarise, the bug is this:

Setting of `0` means OFF, not "the lowest non-zero setting", i.e. `1`. So, if the user sets the value to `0` the line `FrontLightState=false` should be written.

**Comment by tigran123** [comment]
Ok, I've read the code in `reader.lua` and see that if I set `KOBO_LIGHT_ON_START=-1` in `defaults.lua` then Koreader will behave the way I expect it. I'll test it now and if it works, I'll close this issue.
