### ISSUE TITLE
PDF crashes after opening

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#2190]
- KOReader version: v2015.11-533-g1d2150c
- Device: Kobo Aura H2O
#### Issue

crash.log:

```
error: cannot find startxref
warning: trying to repair broken xref
warning: object missing 'endobj' token
error: Malformed pages tree
[!] doShowReader coroutine crashed:
./ffi/mupdf.lua:63: cannot open page #1: Malformed pages tree (1)
stack traceback:
    ./ffi/mupdf.lua:63: in function 'merror'
    ./ffi/mupdf.lua:193: in function 'openPage'
    frontend/document/document.lua:139: in function 'getNativePageDimensions'
    frontend/apps/reader/modules/readerzooming.lua:226: in function 'getZoom'
    frontend/apps/reader/modules/readerzooming.lua:296: in function 'setZoom'
    frontend/apps/reader/modules/readerzooming.lua:161: in function 'handleEvent'
    frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
    frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
    frontend/apps/reader/modules/readerview.lua:599: in function 'onSetScreenMode'
    frontend/apps/reader/modules/readerview.lua:642: in function 'handleEvent'
    frontend/ui/widget/container/widgetcontainer.lua:75: in function 'propagateEvent'
    frontend/ui/widget/container/widgetcontainer.lua:87: in function 'handleEvent'
    frontend/apps/reader/readerui.lua:319: in function 'init'
    frontend/ui/widget/widget.lua:39: in function 'new'
    frontend/apps/reader/readerui.lua:387: in function 'doShowReader'
    frontend/apps/reader/readerui.lua:349: in function <frontend/apps/reader/readerui.lua:348>
```
#### Steps to reproduce

Open pdf-file: 
[The Real Book Vol 2.part3.zip](https://github.com/koreader/koreader/files/384525/The.Real.Book.Vol.2.part3.zip)
[The Real Book Vol 2.part4.zip](https://github.com/koreader/koreader/files/384523/The.Real.Book.Vol.2.part4.zip)
[The Real Book Vol 2.part5.zip](https://github.com/koreader/koreader/files/384521/The.Real.Book.Vol.2.part5.zip)
[The Real Book Vol 2.part1.zip](https://github.com/koreader/koreader/files/384522/The.Real.Book.Vol.2.part1.zip)
[The Real Book Vol 2.part2.zip](https://github.com/koreader/koreader/files/384524/The.Real.Book.Vol.2.part2.zip)

**Comment by tigran123** [comment]
Usually, the message about xref means PDF is corrupted, i.e. it is missing startxref. Have you manually verified (opening PDF in vi) that this is not the case?

**Comment by Markismus** [comment]
Yes, tigran. I did.

**Comment by tigran123** [comment]
@Markismus I didn't mean opening it with a PDF reader (like Acrobat Reader etc). Of course Adobe would open it because it would try to fix the xref table on the fly (btw in my almost 20 years of working with PDF files I never encountered a situation when Adobe Reader actually successfully repaired the file --- it just printed the message "Repairing" and then failed anyway :)

Of course I agree with you that Koreader shouldn't crash, but at least if you verify (by running `pdfinfo file.pdf` command) that your PDF file is not corrupted, it would rule out that possibility.

**Comment by tigran123** [comment]
I tried to download your PDF file, but it is split into multiple pieces and the first piece is corrupted (unzip complains). So, please upload it as a single piece, so I can download it properly. Also, don't forget to specify MD5 checksum of the file, so I can verify if I downloaded the file correctly. Thank you.

**Comment by chrox** [comment]
Sorry I also failed to reconstruct the multi-part zip, could you show us how to do it?

**Comment by Markismus** [comment]
First of all, my apologies for responding so late. It's vacation time and that actually implies a lot more work with 2 daughters and a mom away giving lectures.

I tried to open it with vi, but it fails due to a too large temp file. (The pdf-file is 47MB.)

The file is [here at Dropbox](https://www.dropbox.com/s/t9pdd7tv06qgs6j/The%20Real%20Book%20Vol%202.pdf?dl=0).

**Comment by tigran123** [comment]
I downloaded the file and the xref looks fine, the file opens in evince and Adobe Reader with no problems. Haven't tried it in Koreader though... MD5 checksum is `d4ba42b65df5100e889104658b2d20a1`

**Comment by Frenzie** [comment]
The file works for me in emulator and on H2O. Closing now.
