### ISSUE TITLE
Settings in defaults.persistent.lua not working?

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#2192]
* KOReader version: koreader-nightly-20160702 - Couldn't find any relevant code change since then.
* Device: kobo aura hd

#### Issue
`defaults.persistent.lua` is not obeyed. I set `DAUTO_SAVE_PAGING_COUNT = 6` but now koreader crashed and the state of the pdf is about 100 pages back, where I was the last time I switched files.

Maybe it is a page saving problem, but I have the same problem with other settings, see #2154

#### Steps to reproduce
Copy `koreader/defaults.lua` to `defaults.persistent.lua` and change any setting there.
Is there any other way to test this?

**Comment by Hzj-jie** [comment]
I am almost 100% sure defaults.persistent.lua is still working. As the code is at https://github.com/koreader/koreader/blob/6a7f55f81273176e2cccd36f77197d4740494c58/frontend/apps/filemanager/filemanagersetdefaults.lua#L17.
But your description is a little bit strange, just double confirm, your defaults.persistent.lua and defaults.lua are in the same folder, right?

**Comment by hurzl** [comment]
> your defaults.persistent.lua and defaults.lua are in the same folder, right?

yes

**Comment by houqp** [comment]
I cannot reproduce this in emulator. Perhaps there is a synx error in the file? You can try print the changed variable after this line: https://github.com/koreader/koreader/blob/master/reader.lua#L6. Also try change that line to `require "defaults.persistent"` to see if you get any crash log at start up. Does changing the value in `defaults.lua` work for you?

**Comment by hurzl** [comment]
> Does changing the value in defaults.lua work for you?
How do I test that? Where is the crash log? Where is the page state saved?

**Comment by Hzj-jie** [comment]
Would you mind to share your defaults.persistent.lua here? Please kindly attach your file directly, instead of the text in the file.

**Comment by hurzl** [comment]
[defaults.persistent.lua.txt](https://github.com/koreader/koreader/files/391738/defaults.persistent.lua.txt)

**Comment by Hzj-jie** [comment]
Are you sure you have .txt as file suffix? If so, remove it, and you should be all set. (In Windows, you may not be able to see the suffix without enabling display suffix feature. Please refer to https://goo.gl/PZRbK2)

**Comment by hurzl** [comment]
I could only attach it here by adding ".txt"

**Comment by Hzj-jie** [comment]
That's extremely weird. I am always using defaults.presistent.lua for DAUTO_SAVE_PAGING_COUNT. Are you able to reproduce this issue consistently?

**Comment by houqp** [comment]
> Does changing the value in defaults.lua work for you?
> How do I test that? Where is the crash log? Where is the page state saved?

crash log is a file named `crash.log` in `koreader` folder.

> I added require "defaults.persistent" and it doesn't crash

Can  you also add the following line after the require statement?

```lua
print("defaults:::", DAUTO_SAVE_PAGING_COUNT`)
```

After this, open and exit the reader. Then see if you can find the `defaults:::` line in the crash log. If so, check to see whether the value matched with the value you have in persist.defaults.lua.

**Comment by hurzl** [comment]
> crash log is a file named crash.log in koreader folder.

I have no such file

**Comment by houqp** [comment]
This is very weird then... Are you using KSM as the launcher?

**Comment by hurzl** [comment]
Is that KBStartMenu_08?

**Comment by houqp** [comment]
Yes, i wonder whether your KSM is using a custom startup script that does not write out crash.log files. Do you have ssh access to your device?

**Comment by hurzl** [comment]
no network is off

**Comment by houqp** [comment]
Could you try enable usbnetwork for you device? This feature should come with KSM. Without crash.log or ssh access, it's almost impossible for us to debug this issue.

**Comment by hurzl** [comment]
how do I setup the usbnetwork?

**Comment by KenMaltby** [comment]
http://www.mobileread.com/forums/showthread.php?t=266821 under the •enable USBNet "Show" button.

**Comment by hurzl** [comment]
sorry this is on FreeBSD
```
ue0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        ether xx:xx:xx:xx:xx
        inet 192.168.2.100 netmask 0xffffff00 broadcast 192.168.2.255 
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>

# route get 192.168.2.101
   route to: 192.168.2.101
destination: 192.168.2.0
       mask: 255.255.255.0
        fib: 0
  interface: ue0
      flags: <UP,DONE,PINNED>
 recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
       0         0         0         0      1500         1         0 
# ping 192.168.2.101
PING 192.168.2.101 (192.168.2.101): 56 data bytes
ping: sendto: Host is down
```

**Comment by hurzl** [comment]
on linux it works :(

**Comment by houqp** [comment]
interesting, perhaps freebsd requires special driver for the usbnet thing? you should be able to ssh to the device with user `root` and password `banana`.

once you get ssh access, you will be able to run koreader from command line and output of the print state should show up in the console: `cd /mnt/onboard/.kobo/koreader && ./luajit reader.lua -d .`

**Comment by hurzl** [comment]
```
 # ping kobo
PING kobo (192.168.2.101) 56(84) bytes of data.
64 bytes from kobo (192.168.2.101): icmp_seq=1 ttl=64 time=0.489 ms

# ssh root@kobo
ssh: connect to host kobo port 22: Connection refused
```

**Comment by houqp** [comment]
Hmm... perhaps the usbnet from KSM is broken. Based on https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L114. All output from koreader (including the pirnt) should be redirected crash.log. It's mostly likely KSM executed its own koreader.sh script.

Another workaround is to change the print statement to io.write:

```lua
f = io.open("/mnt/onboard/.kobo/koreader/test_write", "w")                                                                                                                                           
f:write("defaults:::")
f:write(DAUTO_SAVE_PAGING_COUNT)                                                                                                                                                              
f:close()
```

**Comment by hurzl** [comment]
The error is found: I had a /koreader/ and a /.kobo/koreader/ directory, because I unzipped to the root directory. All changes I made there and that couldn't work. Very funmy, hahaha. Sorry. But I must say the installation procedure can be confusing.

**Comment by hurzl** [comment]
But now I lost my history when I correctly installed into .apps, why?

**Comment by Hzj-jie** [comment]
usbnet from KSM can magically work with vlasovsoft package. You do not need to do anything, just copy its package into .adds folder of KSM, and enable usbnet in KSM.

history is maintained by history.lua and legacy history folder in koreader folder. If you have not used koreader for a long time, you properly do not have anything in history folder. If so, you can ignore this folder. Copying both into your new installation, and your history will be back.

**Comment by hurzl** [comment]
I don't really have to have sshd (I hope).
I have many lua files in the history folder, one for each file, but the history in koreader is empty.
Has the history format changed and the new version can't read these files?

**Comment by Hzj-jie** [comment]
No, we always be able to read history folder. You mean your history.lua file is empty? It may have the similar issue as your defaults.presistent.lua, i.e. KSM started a koreader in an unexpected location.

**Comment by hurzl** [comment]
I have no history.lua file.

**Comment by hurzl** [comment]
Does it now start in the .adds directory? I thought that is for installation only?

**Comment by Hzj-jie** [comment]
I believe KSM 08 only accept .adds folder for koreader. And koreader assumes this is the root folder, and most of the settings are placed here.

**Comment by hurzl** [comment]
@houqp  wrote
> f = io.open("/mnt/onboard/.kobo/koreader/test_write", "w") 

and I have koreader in .kobo. why?

**Comment by hurzl** [comment]
history in .adds/koreader works.

**Comment by KenMaltby** [comment]
If going from no KSM (or KSM prior to KSM7.4) to KSM8 (or KSM7.4), then you move the entire "/mnt/onboard/.kobo/koreader", koreader folder to  "/mnt/onboard/.adds/koreader".  That should have moved the history folder as well.

**Comment by houqp** [comment]
Right.. sorry i forgot i am still using a very old version of KSM. @KenMaltby is correct, you should delete the old `.kobo/koreader` directory.
