### ISSUE TITLE
UI has been blocked if kosync server is not reachable

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2194]
- KOReader version: up to commit 37d3975
- Device: independent
#### Issue

UI has been blocked if kosync server is not reachable, and auto sync has been enabled.
#### Steps to reproduce

Set an incorrect kosync server address.
Turn on auto sync function.
Open a book or close a book.
The UI will freeze for a long time (30 seconds as timeout setting).

I believe this is because of the implementation of kosync plugin, it blocks current UI thread.

**Comment by houqp** [comment]
try put that IO code into a coroutine?

**Comment by chrox** [comment]
Coroutine itself won't make the HTTP request async. But if we enable the Turbo support in the defaults.lua the kosync APIs will be async.

**Comment by chrox** [comment]
Anyway we should fix this problem in the sync mode by setting a shorter timeout peroid or failing the request early.

**Comment by NiLuJe** [comment]
What was the issue with the Turbo codepath, I can't remmeber :s.

**Comment by Hzj-jie** [comment]
It has been disabled by chrox at https://github.com/koreader/koreader/pull/1543, to fix several random crashes, https://github.com/koreader/koreader/issues/1535 and https://github.com/koreader/koreader/issues/1498.

**Comment by chrox** [comment]
Yes, it's an unstable feature in koreader and I'm pretty sure the random crashes were caused by the Turbo library. Maybe we can try the latest version of Turbo. And even it's not muture enough we can disable it in the stable release.

I'm still in vacation thus probably cannot help with this.

**Comment by houqp** [comment]
IIRC, the root cause has something to do with large memory usage, at least in android. The product is not under active development anymore so we should switch to something more stable in the long run.

I don't mind we give the latest version another shot. But we should also setup a proper timeout in the client request. Something less then 400ms should be good enough IMO.

**Comment by Frenzie** [comment]
Sync timeout reduced to 1s in #2268.
