### ISSUE TITLE
Kindle Basic 2 crash on startup from KUAL

### ISSUE THREAD

**Issue by prajnak** [koreader/koreader#2195]
* KOReader version: koreader-nightly-20160714 kindle
* Device: Kindle Basic 2 (Black)

#### Issue
koreader does not launch from KUAL. I unpacked koreader into the root and verified that the extensions folder and koreader folder were populated in the kindle root directory. I ran all variants(normal + no framework) of "Start filemanager" and "Open last document" to no avail. 
Selecting any of these options takes me back to the homescreen and it stays there. I checked the logs (_crash.log_) for KO reader and found the following error:

```
./luajit: frontend/device/input.lua:147: error opening input device </dev/input/event1>: 2
stack traceback:
	[C]: in function 'open'
	frontend/device/input.lua:147: in function 'open'
	frontend/device/kindle/device.lua:354: in function 'init'
	frontend/device.lua:39: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:96: in main chunk
	[C]: at 0x0000be9d
```

#### Steps to reproduce

Install Koreader on a Kindle Basic 2 and open via KUAL.

**Comment by prajnak** [comment]
I'm running FIRMWARE version 5.8.0

**Comment by houqp** [comment]
Is basic 2 the same as kindle2? Do you have ssh access? Can you check if `/dev/input/event1` file exists on the device?

**Comment by NiLuJe** [comment]
It's a KT3, and that path was a wild guess, so I'm not terribly surprised ;).

So, a couple of possibilities:

If you have SSH access:

```ls -lash /dev/input/by-path```

If you don't:

After a reboot, enter '';dm'' in the Homescreen's searchbar, and show us the *system* logfile that'll dump in the documents folder ;).

**Comment by prajnak** [comment]
@NiLuJe here you go. 
[all_system_logs_as_of_Fri_Jul_29_06.58.10_AST_2016.txt](https://github.com/koreader/koreader/files/390390/all_system_logs_as_of_Fri_Jul_29_06.58.10_AST_2016.txt)

**Comment by prajnak** [comment]
Oh, your suspicion doesn't sound like good news for me ;). I can try to get ssh access today and i'll report back with what i find in input devices

**Comment by NiLuJe** [comment]
Well, what do you know... It's using a good old IR grid...

I might be misremembering things, but didn't the KT2 switch to a capacitive touchscreen?

**Comment by NiLuJe** [comment]
See if that commit does the trick ;).
Most notably, I'd like to confirm that the battery status reporting works ;).

**Comment by prajnak** [comment]
WORKS FINE NOW THANK YOU BASED GOD
