### ISSUE TITLE
Screensaver option is missing from menu

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2198]
* KOReader version: v2015.11-558 but the bug is at least 2 months older
* Device: Kobo Mini

#### Issue
In some moment the option "Screensaver" disappeared from the menu. It was an entry that appeared right after "Highlight options" in the same menu where "Change font" and "Hyphenation" are when you have opened a book.
This entry let you choose if you wanted to use the cover of the book as screensaver. Now, it seems that cover as screensaver is activated by default and that it is not possible to deactivate it. If you cannot deactivate this option, the option "Screen saver folder" to use your own images as screensavers become useless.

More info:
I commented this problem in Mobileread two months ago.
Ken Maltby said: 
> The option to use the book cover should have been moved to "settings.reader.lua" from the "defaults.lua". It appears to be gone from defaults, but I don't yet see it in settings.reader.lua. (I have "KOBO_SCREEN_SAVER_LAST_BOOK = true" in my "defaults.persistent.lua". You could try adding it to yours, with it set to false.)
> I don't know why your KOBO is not having the menu option though.

I replied: 

> I added the option with notepad++ to defaults.persistent.lua. It ignores it though. It still shows the cover of the last book in sleep mode.
> The option KOBO_SCREEN_SAVER_LAST_BOOK doesn't appear in the default.lua.

And NiLuJe replied: 

> I'd open a GH issue right now .
> KOBO_SCREEN_SAVER_LAST_BOOK appears to be gone, yet it's still checked to devise whether or not to show the "Screensaver" settings menu entry.

I thought that NiLuJe would open an issue right after but I guess he meant that I should open it ^^;

**Comment by NiLuJe** [comment]
Yeah, I did mean that you should be the one to it, but I still completely forgot to bring the subject back up, so, thank you ;).

**Comment by houqp** [comment]
Sorry for the confusion. Looks like we missed that entry when migrating the setting from defaults.lua to settings.reader.lua. We will add this menu entry back (although I don't recall we explicitly removed the entry).

For now, if you want to set a screensaver folder, you will have to manually set the `screensaver_folder` key in settings.reader.lua.

**Comment by houqp** [comment]
@retrue, my fix in #2202 should bring this feature back. FYI, I also moved the menu item to the gear menu tab to keep it consistent with the menu in filemanager.
