### ISSUE TITLE
Disabling AutoSuspend doesn't work.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#2207]
* KOReader version: v2015.11-549
* Device: Kobo Touch

#### Issue

According to the source code in `frontend/ui/uimanager.lua:UIManager:_initAutoSuspend()` the setting `auto_suspend_timeout_seconds` controls this feature and, if negative, should disable AutoSuspend. However, this is not the case --- I have put this line in `defaults.lua` and restarted Koreader:

```
auto_suspend_timeout_seconds = -1
```

and the AutoSuspend still kicks in. So, how do I disable this feature?

**Comment by tigran123** [comment]
Ok, I see that the proper way to disable it is to add this line to `settings.reader.lua`:

```
["auto_suspend_timeout_seconds"] = -1
```

and add a comma to the previous line.

I have documented this on Wiki here:

https://github.com/koreader/koreader/wiki/Tips-and-Tricks

so the issue can be safely closed. I replaced the tip about "long press at the bottom for quick Goto" because this feature no longer exists.

**Comment by houqp** [comment]
Thanks for updating the wiki! We should add an menu option to control that behavior in GUI too.

> so the issue can be safely closed. I replaced the tip about "long press at the bottom for quick Goto" because this feature no longer exists.

This actually still exist, but the proper description should be something like "long press progress bar for quick Goto".

**Comment by tigran123** [comment]
@houqp Thank you for correcting me concerning the long press on the status bar for Goto. I didn't know this and added this info to the wiki Tips.

**Comment by tigran123** [comment]
Btw, yes, I agree that it would be nice to have a menu option to disable AutoSuspend and that would also provide the functionality which is discussed in #2204 .
