### ISSUE TITLE
EPUB don't show up in Kindle OS + PDF don't be opened automatically (just with Kindle OS...)

### ISSUE THREAD

**Issue by loralo** [koreader/koreader#2210]
* KOReader version:  v2015.11-533-g1d2150c
* Device: Paperwhite 3

Hi! I've tried to put some EPUB books in my Kidle with Calibre and directly copy/paste in the device, but nothing seems to work. I only can see the PDF ebooks, but Koreader can't open them from the Kindle OS directly, just from Koreader explorer. What I am doing wrong? :S 

Thank you so much!

**Comment by Eduardomb22** [comment]
Do you have kpvbooklet installed? https://github.com/koreader/kpvbooklet/wiki

**Comment by loralo** [comment]
Hi Eduardomb22! I have KUAL, do I need kpvbooklet installed too? I'm a little confused, sorry!
Thanks for your quickly answer!

**Comment by loralo** [comment]
I've installed kpvbooket and everything goes awesome! Thank you! I'm new in these kindle/jailbreak world and I have a lot to learn :)

**Comment by houqp** [comment]
Yup kpvbooklet is for integration between koreader and the native system. KUAL is for launching koreader alongside the native system.
