### ISSUE TITLE
Problem with starting Wi-Fi with Kobo Touch N905

### ISSUE THREAD

**Issue by Stoyan-T** [koreader/koreader#2211]
- KOReader version: koreader-stable-v2015.11
- Device: Kobo Touch N905
#### Issue

Can not start wi-fi from menu "Settings->Network->Wifi connection".

After some research i was finally able to start wi-fi after changing the function " koboEnableWifi" in /frontend/ui/networkmgr.lua as follows:

``` Lua
local function koboEnableWifi(toggle)
    if toggle == 1 then
        os.execute("insmod /drivers/freescale/wifi/ar6000.ko")
        os.execute("sleep 1")
        os.execute("ifconfig wlan0 up")
        os.execute("wlarm_le -i wlan0 up")
        os.execute("wpa_supplicant -s -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf -C /var/run/wpa_supplicant -B")
        os.execute("udhcpc -S -i wlan0 -s /etc/udhcpc.d/default.script -t15 -T10 -A3 -b -q >/dev/null 2>&1")
    else
        os.execute("killall udhcpc wpa_supplicant 2>/dev/null")
        os.execute("wlarm_le -i wlan0 down")
        os.execute("ifconfig wlan0 down")
        os.execute("rmmod -r ar6000")
    end
end
```

**Comment by houqp** [comment]
@Stoyan-T do you know if all the touch models are loading the same kernel module (ar6000)?

**Comment by NiLuJe** [comment]
We might be able to reuse the "detection" code used in nickel.sh, I think there's something related to that in there....

xref #2215, which would be a fine time to do just that ;).

**Comment by KenMaltby** [comment]
There must be a huge difference between a 30,Oct 2015 release and the current nightlys, still I had to reauthorize my AuraHD's access to my wireless router, to get the Wifi working yesterday. ( That is on "2015.11-566")  I had to tap "disconnect" > "edit" > "Connect", before it would show me as Connected. ( I just tried again and I had to do it all over again today.)  Life was easier before we had "Network info".

**Comment by Stoyan-T** [comment]
@houqp, i honestly don't know. I remember that i had problems also with kobo start menu and had to change code there too.

**Comment by houqp** [comment]
> We might be able to reuse the "detection" code used in nickel.sh, I think there's something related to that in there....

Good point, I am traveling right now so can't verify this with my kobo. @NiLuJe so is it safe to assume `WIFI_MODULE_PATH` is set by `/etc/init.d/rcS` for all modules except `ar6000`?

> There must be a huge difference between a 30,Oct 2015 release and the current nightlys, still I had to reauthorize my AuraHD's access to my wireless router, to get the Wifi working yesterday. ( That is on "2015.11-566") I had to tap "disconnect" > "edit" > "Connect", before it would show me as Connected. ( I just tried again and I had to do it all over again today.) Life was easier before we had "Network info".

Once the network is saved, you can just tap on the network name to connect. No need to tap edit again. However, the fact that you have to alway disconnect first sounds like a bug to me. Does this happen on a fresh start or only after a suspend?

**Comment by KenMaltby** [comment]
On starting after "Power off"; "Network"> "Wi-Fi connection"> "OK"(to "Do you want to turn on Wi-Fi?"), gives me "Scanning...". Then the listing of available access points, with my normal one at the top and there is "disconnect" offered for that item.  Tapping that item does nothing, ( I'm guessing because it thinks it is already connected).  Tapping the "disconnect", gives me a "disconnecting..." message box, then "edit" appears for that item.  Now - tapping the item name gets it connected, and a checkmark appears in front of the "Wi-Fi connection" menu option.  

I haven't tried after suspend; So: tried it, it is the same.  It comes up with "disconnect" but it is not really connected.

**Comment by NiLuJe** [comment]
The original issue should be fixed for... quite a while now ;).
