### ISSUE TITLE
page overlap in epub is zero

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#2214]
* KOReader version: koreader-nightly-20160714
* Device: aura hd

#### Issue
No page overlap in epubs. I have set OVERLAP_PIXELS to 60 and see it in pdfs.
It is there, but only about the height of the status bar.

**Comment by KenMaltby** [comment]
Not sure you should have "overlapping" pages in an EPUB, this is for scanned pages where a larger fixed page is being displayed on more than one display page of a device.

**Comment by hurzl** [comment]
Then it would make sense to forbid "scroll mode" for epubs.

**Comment by KenMaltby** [comment]
Scroll mode doesn't make much sense for a normal epub, as they are primarily lines of text and images that can be fitted to different sized display screens, to be pages.  I am curious as to how you find scroll mode to be useful for epubs?

**Comment by hurzl** [comment]
I don't,  but I had it set to scroll mode and expected behaviour like pdf scrollmode

**Comment by chrox** [comment]
EPUB documents actually have no concept of regular page thus no page overlap. Please regard this as EPUB engine limitation.

**Comment by chrox** [comment]
I'm closing this now.
