### ISSUE TITLE
Screen is unresponsive to touch

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2219]
* KOReader version: 2015.11-577
* Device: Kobo Mini

#### Issue
The screen is totally unresponsive to touch. The device starts correctly though. I know the device or koreader are not frozen because the power button works. I mean, with a slight push I go to see the screensaver and I go back to the File Manager screen with another touch. With a 3 seconds push I go to see the Power off?  dialogue but then I cannot turn it off because the screen doesn't respond to touch.

**Comment by hombretranquilo** [comment]
Same behaviour on Kobo Aura HD. KOReader version: 2015.11-566 worked fine.

**Comment by retrue** [comment]
I have installed version 2015.11-568 and it doesn't work either. So it seems the bug was introduced between versions 566 and 568.

**Comment by chrox** [comment]
Thanks for the report, it will be fixed in #2220.
