### ISSUE TITLE
Physical buttons not working in KOReader on Kindle Oasis [Wifi, 8.5.2]

### ISSUE THREAD

**Issue by allegd** [koreader/koreader#2221]
* KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-533-g1d2150c [nightly]
* Device: Kindle Oasis, firmware 8.5.2

#### Issue

Physical buttons on kindle oasis version 8.5.2 do not work on any document

#### Steps to reproduce

Open KUAL, launch KOreader, open any document whether its .epub or .pdf, the buttons do not work. 

#### What I tried so far: 

On this other [thread](https://github.com/koreader/koreader/issues/2173), I tried [bingo619's code](https://github.com/bingo619/koreader/blob/master/frontend/device/kindle/device.lua#L112). I updated device.lua with the appropriate additions to add keys and events, but it didnt work. The same happens when using KPVBooklet. 
I verified that the buttons work normally with kindle store epubs and imported pdfs. 

If theres anything else I can provide please let me know.

**Comment by chrox** [comment]
Could you test the latest release `koreader-kindle-arm-linux-gnueabi-v2015.11-583-g7e4dc7a.zip` and report back?

**Comment by allegd** [comment]
Just tested it, the buttons work fine now, thank you so much!

**Comment by chrox** [comment]
I'm glad it works now. Thank you for your report though. Closing this now,
