### ISSUE TITLE
Paragraph and div problem

### ISSUE THREAD

**Issue by jpalaciosdev** [koreader/koreader#2228]
* KOReader version: v2015.11-587
* Device: Kobo Aura HD

#### Issue
I have some books that have the divs styled with margings (and optionally italics), tipically used for quotes.
This is what Calibre and other software renders:
![calibre-test-rendering](https://cloud.githubusercontent.com/assets/10498177/17817733/3c8945a2-6640-11e6-86cc-85aff7475ce2.png)
And this is what Koreader renders:
![koreader-test-rendering](https://cloud.githubusercontent.com/assets/10498177/17817734/3c903f4c-6640-11e6-8234-8e9f868c9516.png)
The subsequent paragraphs of each div block inherits the margin of the previous div block.
Looks like that the closing div element is being ignored (for the marging style, but not for the italics style).

#### Steps to reproduce
Open [this test file](https://www.dropbox.com/s/p0ittez3yh1cko6/test.epub?dl=0).

**Comment by frankyifei** [comment]
this bug is really interesting, why only margin gets inherited?
