### ISSUE TITLE
Cannot Exit KOReader

### ISSUE THREAD

**Issue by TheDauthi** [koreader/koreader#2229]
* KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-583-g7e4dc7a
* Device: PaperWhite 2

#### Issue
Cannot exit KOReader.  Home button does not exit.  Menus partially work, do not refresh properly.

#### Steps to reproduce
( I am working to reproduce consistently, the following are one set of conditions I was able to reproduce it under (several times), but not consistently.  If I am able to consistently reproduce, I will update this ticket with those steps )

- Open book (KPV)
- Read for a very long time, including multiple sleep cycles
- Open menu
- Press Home button.
- Nothing happens.  Other menu items will work, but no longer close or refresh correctly.

(This result was with KPV; I believe it has happened with KUAL, but unsure.  Will attempt next)

**Comment by Eduardomb22** [comment]
Got the same problem with ppw3

**Comment by chrox** [comment]
It should be fixed in [koreader-nightly-20160823](https://github.com/koreader/koreader/releases/tag/v2016.08.23-nightly). 

@TheDauthi @Eduardomb22 Could you try it and report back here? Thanks.

**Comment by Eduardomb22** [comment]
@chrox It is working fine now. thanks

**Comment by chrox** [comment]
Thank you for the report. Closing this now.
