### ISSUE TITLE
No covers in fb2 books

### ISSUE THREAD

**Issue by andruha30** [koreader/koreader#2230]
- KOReader version:
- Device:

**Comment by andruha30** [comment]
When open fb2 files no covers of books....Just black screen(1st page)  Is it normal?
PB626 VERSION FROM 14/08/16

**Comment by apletnev** [comment]
It depends on fb2 file. Sometimes it works as expected, but sometimes it does not work correctly. Looks like fb2 format can contains different types of images, but creengine support only one of them

**Comment by andruha30** [comment]
Today I opened about 10 files fb2 and no one shows the cover...

**Comment by apletnev** [comment]
You are right. I've checked too, and it does not working. But earlier it worked for some kind of fb2 files.

**Comment by andruha30** [comment]
По русски понимаете? В какой то версии все работало,но в последних 2-х точно не работает,неприятно открывать файл без обложки..

**Comment by apletnev** [comment]
Работало год назад. Из-за того, что не всегда отображало как нужно, я не заморачивался и не обращал внимание на обложки. Кстати если все таки хочется посмотреть на обложку можно использовать статус.

**Comment by itspec-ru** [comment]
Я про этот баг в феврале 2015-го здесь писал
incorrect cover in FictionBook (FB2) in Kindle PW
https://github.com/koreader/koreader/issues/1438
К следующему релизу вроде как должны поправить (Milestone: next stable release)

**Comment by andruha30** [comment]
Спасибо!!! ...Есть еще пару мелких пожеланий, как нибудь соберусь и отпишусь по ним...

**Comment by apletnev** [comment]
Боюсь не стоит ожидать в ближайшее время каких-то сдвигов ( тут народ больше на рефакторинг кода заточен, фичи практически не имплементятся. ((

**Comment by andruha30** [comment]
Ничего нового не буду предлагать..Только то что уже есть,но не до конца корректно работает:)

**Comment by apletnev** [comment]
Если есть фичи, ты предлагай если что, вдруг я соберусь ;) А то мне не интересно баги, на работе хватает багов. %) хочется фичи

**Comment by andruha30** [comment]
Добро..Если что, дам знать :)

**Comment by tigran123** [comment]
@apletnev воистину, на вкус и цвет товарища нет --- мне как раз, наоборот, интересно только баги (и на работе когда-то только баги в SCO UnixWare фиксировал) , а фичи хочется 99% вообще выкинуть как ненужные. Кстати, поддержку fb2 в koreader-е я считаю ненужной (ибо CoolReader в варианте Сергея Власова лучше). Давным давно (когда koreader-a не было, а был kindlepdfviewer) я даже не поленился и смастерил версию "только для pdf и djvu" и она была намного быстрее и легче нормальной. И никаких багов, ибо весь код видишь "как на ладони". Но следить за всеми изменениям было неохота и я это дело оставил.

**Comment by andruha30** [comment]
смастерил версию "только для pdf и djvu" 
Пришлите мне,потестю у себя на PB....

**Comment by tigran123** [comment]
@andruha30 PB? Это было во времена Kindle Keyboard 3 и KindleDXG (оба с клавиатурой).

Между прочим, на KindleDXG я до сих пор использую kindlepdfviewer и очень даже неплохо. Хотя большинство книг можно вполне комфортабельно читать и на Kobo Aura H2O, иногда хочется видеть всю страницу (речь идёт о DjVu или PDF) и тогда я достаю KindleDXG. Версия kindlepdfview на нём `v2013.1-10-g73c2d18` --- последняя стабильная хорошая версия. Могу послать, если нужно. А вот она есть и здесь:

[https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/kindlepdfviewer-package/kindlepdfviewer-v2013.1-10-g73c2d18.zip](url)

Kobo Aura H2O удобна тем, что допускает до 512GB хранилища, т.е. можно таскать "почти всю" свою библиотеку всегда с собой. "почти всю" это значит только то, что когда-нибудь (может быть) собираюсь прочесть. А архив это 25ТБ который никак не положишь в карман сегодня (и вряд ли когда-нибудь, ибо прежде чем технологии дойдут до того, чтобы можно было положить 25ТБ в карман, человечество само-уничтожится).

**Comment by apletnev** [comment]
@tigran123 спасибо за наводку о CoolReader, посмотрю на досуге

**Comment by frankyifei** [comment]
use the same code to build a coolreader, then it shows cover correctly.

**Comment by frankyifei** [comment]
can you guys upload more fb2 with covers for me to test, I found some suspicious code in lvdrawbuf.cpp which may caused black cover when it is doing color conversion.

**Comment by tigran123** [comment]
Yes, sure here is the FB2 version of my British Study Edition of the Urantia Papers (one of the few books in English in FB2 format :)

[http://www.bibles.org.uk/The-British-Study-Edition-of-the-Urantia-Papers.fb2.zip](url)

**Comment by andruha30** [comment]
Here is a fb2 file in Russian

http://rgho.st/6728QDtln

**Comment by frankyifei** [comment]
![reader_2016-sep-05_120706](https://cloud.githubusercontent.com/assets/8104251/18236053/7e614bc2-7361-11e6-875a-a436e736e5fa.png)
looks like it is working on emulator

**Comment by andruha30** [comment]
Okey,waiting for a new build......

**Comment by frankyifei** [comment]
this issue should be closed

**Comment by andruha30** [comment]
new build ?

**Comment by apletnev** [comment]
HI @frankyifei 
Could you please describe steps to update crengine?

**Comment by frankyifei** [comment]
I have already submitted the changes and gets merged by maintainer. so if you do a "git pull" you will see the changes.

**Comment by andruha30** [comment]
I am a simple user so dont hope I will manage it sorry

**Comment by itspec-ru** [comment]
Собрал koreader с обновленным crengine на своём linux'е. Обложки FB2 отображаются корректно.
Ждём новых релизов koreader'а с обновлённым crengine.
frankyifei, большое спасибо!

I'm built koreader with updated crengine on linux. Covers on FB2 looks perfect.
Waiting for koreader's releases with updated crengine.
frankyifei, thank you very much!

**Comment by andruha30** [comment]
Спасибо Вам большое за обложки......

**Comment by itspec-ru** [comment]
Не стал дожидаться релиза с исправленным багом, собрал из исходников сам (исходники от 26 октября).
Работает. **Собрал только для kindle**. Обложки в FB2 отображаются. Каких-либо проблем замечено не было.
Кому нужно, качайте архив koreader-kindle-arm-linux-gnueabi-v2015.11-658-g683b038.zip здесь
https://yadi.sk/d/RtKszxtsxoGZA

**Comment by andruha30** [comment]
Жаль только для киндла,мне нужен покетбук 626

**Comment by apletnev** [comment]
@itspec-ru @andruha30 парни, вы чего?
Есть ж ведь nightly builds http://build.koreader.rocks/download/nightly/

**Comment by itspec-ru** [comment]
На сборку под kindle потратил около двух часов. Пока не располагаю временем на сборку под другие платформы. Возможно позже

**Comment by itspec-ru** [comment]
@apletnev спасибо за ссылку, не знал. Значит время на сборку потрачено зря.
Я всегда ориентировался по ссылке https://github.com/koreader/koreader/releases
а там стоит дата последнего билда 20160823

**Comment by andruha30** [comment]
Спасибо,скачал посмотрим что нового....

**Comment by andruha30** [comment]
Тоже ориентировался на дату последнего билда 20160823

**Comment by andruha30** [comment]
Есть небольщое пожелание - в файлах пдф и джвю  Режим прокрутки по умолчанию поставить ВЫКЛЮЧЕНО,кому нужно включит вручную.

**Comment by tigran123** [comment]
@andruha30 Эта опция (называется Scroll) уже давно стоит по умолчанию On. Это приводит к небольшим проблемам ибо включение Crop=Auto ломает Koreader (примерно в 70% случаях) и приходится делать это "акκуратно", т.е. сначала выключить Scroll, а потом уже ставить Crop=Auto, тогда работает.

**Comment by andruha30** [comment]
*  Can now set picture or text when turning off the device
Где именно внастройках находится эта фича?

**Comment by apletnev** [comment]
@andruha30 
Насколько я понимаю, это относится только к kobo устройствам. Увы, другие девайсы не поддерживаются.

**Comment by andruha30** [comment]
Блин,перелопатил все настройки,предупреждать надо :(
А может для Покета 626 сделаете?

**Comment by apletnev** [comment]
Я для киндла сделать не могу ((, а для покета тем более. Надо создавать фича реквесты.

**Comment by Frenzie** [comment]
As far as I can tell this has been fixed. Feel free to reopen if I'm mistaken on account of all the Russian.
