### ISSUE TITLE
Koreader crashes when login to Evernote

### ISSUE THREAD

**Issue by boplennon** [koreader/koreader#2231]
- KOReader version: 20160823
- Device: KPW3
#### Issue

Koreader crashes when login to Evernote
#### Steps to reproduce

Login to evernote.

**Comment by vetmode** [comment]
This is still happening.

- KOReader version: v2015.11-1689g5db7baba_2018-04-22
- Device: Kobo Aura One

**Comment by Frenzie** [comment]
Presumably that would be the open issue #3600 rather than this fixed issue.

**Comment by vetmode** [comment]
Correct, sorry. :)
