### ISSUE TITLE
Nothing happens when clicking on Start Koreader

### ISSUE THREAD

**Issue by kylescousin** [koreader/koreader#2232]
* KOReader version: https://github.com/koreader/koreader/releases/tag/v2015.11-stable
* Device: Kobo aura

Installed the menu and then koreader. When I startup there's the new start menu where I can select nickel or koreader. When touching koreader, it turns the line dark, but nothing opens. When selecting nickel it does open the standard kobo interface. What could be wrong here?

**Comment by KenMaltby** [comment]
All that is needed is for the "koreader" folder to be in the .adds directory.

**Comment by kylescousin** [comment]
That's where it is.

**Comment by KenMaltby** [comment]
The vast majority of times when I select something (like Start KOReader) on the KSM menu it just goes to that program, but every once in a while the line just seems to be selected and the line is darkened.  Another poke on the line gets it to do what it normally does on the first poke.

**Comment by houqp** [comment]
Can you give the latest build a try? https://github.com/koreader/koreader/releases/tag/v2016.08.23-nightly

**Comment by kylescousin** [comment]
Nevermind, got it working. 
Really loving it!
