### ISSUE TITLE
Traditional Chinese to Simplified Chinese

### ISSUE THREAD

**Issue by bingo619** [koreader/koreader#2234]
It would be great if Koreader can convert Tradional Chinese to Simplified Chinese internally, or the other way around.

Anyone got any ideas?

**Comment by thotypous** [comment]
Maybe [libopencc](https://github.com/BYVoid/OpenCC) could be integrated? It doesn't appear to have any external dependencies.

UI-wise, I believe it could work like the dictionary (select some text and ask to convert). Direction (zhs -> zht, zht -> zhs, etc.) could be selected from a menu.

I'm a little out-of-the-date with the codebase though, so I don't know how easy would it be to implement this as an optional plugin.

The size of the conversion databases is as follows:
```
8,6M	/usr/lib/x86_64-linux-gnu/opencc
```

**Comment by bingo619** [comment]
@thotypous That is awesome. 

Don't think we need to do it as a optional plugin though.

**Comment by houqp** [comment]
opencc is probably the best choice for this task. i would prefer this to be implemented as a plugin because the size of the databases is already one third of the current KOReader release :(
