### ISSUE TITLE
dictionary don't work

### ISSUE THREAD

**Issue by Ocarinalover** [koreader/koreader#2236]
- KOReader version:v2015.11-587-ga55a987
- Device:kindlepaperwhite2(with android 4.4.2 installed)
#### Steps to reproduce 1.kindlepaperwhite with both andriod and orginal system installed

 2.switch to android and install the version
3.open any book,pick up a word ,and you will find no explaination come out with or without dict placed in the file

**Comment by Ocarinalover** [comment]
i just figure out that if the dictionary contain any chinese character and be placed in the file ,it will cause the situation i desctibed above ,which make the whole other dictionary unbrowsible.
so if we only have english-english dictionary in the file the word-search function worked properly 
.

**Comment by Ocarinalover** [comment]
so i wondered that this problem can be reproduced in any android divices since i have another ebook --onyx t68plus,and the same problem can be recreated

**Comment by Markismus** [comment]
Could you upload the non-working dictionary? Just zip it and drag it in your comment.

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
okay

**Comment by Ocarinalover** [comment]
i don't know whether or not  the file is uploaded successfully ,if failed please sent email with you email address attached

**Comment by Ocarinalover** [comment]
the file is too big to fix into this upload system(100M),

**Comment by Markismus** [comment]
Than you could either use a storage server like Dropbox or make a multi-part zip-file (10 parts of 9MB +1 of 1MB wil upload just fine)

**Comment by Ocarinalover** [comment]
https://yunpan.cn/cMTuu9yqFfyxq  password 55e8

**Comment by Ocarinalover** [comment]
https://yunpan.cn/cMTuu9yqFfyxq  password 55e8

**Comment by Markismus** [comment]
Downloaded them, installed a lot of symbol fonts and tested them with version 0.5.0-beta4 of sdcv. I can't see a difference between those you said that worked and that don't. (Even before the fonts were installed, I got results, albeit unreadable.) Could you rerun your tests with dog or 警犬? (Just to make sure your lack of results wasn't due to a unlucky choice of lemma.)

**Not-working**
```
ancient chinese dictionary]$ sdcv -c --data-dir=. -l && sdcv -c --data-dir=.  警犬
Dictionary's name   Word count
古汉语常用字字典    3933
Found 1 items, similar to 警犬.
-->古汉语常用字字典
-->警

jǐng①<动>告诫；警告。《狱中杂记》：“是立法以～其余。”②<动>警戒；戒备。《左传·宣公十二年》：“军卫不彻，～也。”③<名>危险紧急的情况或消息。《左忠毅公逸事》：“每有～，辄数月不就寝。”④<形>敏捷；敏锐。《三国志·魏书·武帝纪》：“太祖少机～，有权数。”";

```
```
advanced chinese learner's dictionary]$ sdcv -c --data-dir=. -l && sdcv -c --data-dir=.  警犬
Dictionary's name   Word count
高级汉语大词典    51675
Found 10 items, similar to 警犬.
0)高级汉语大词典-->小犬
1)高级汉语大词典-->牧犬
2)高级汉语大词典-->狐犬
3)高级汉语大词典-->猎犬
4)高级汉语大词典-->蜀犬吠日
5)高级汉语大词典-->警
6)高级汉语大词典-->警区
7)高级汉语大词典-->警卫
8)高级汉语大词典-->警句
9)高级汉语大词典-->警号
Your choice[-1 to abort]: 0
-->高级汉语大词典
-->小犬

xiǎoquǎn
(1)
[small dog]∶小狗
(2)
[my son]∶谦辞,对人称自己的儿子
待服满后,亲带小犬到府叩谢。――《红楼梦》
```
```
英文相关词典]$ sdcv -c --data-dir=. -l && sdcv -c --data-dir=. dog
Dictionary's name   Word count
英文相关词典    7209
Found 10 items, similar to dog.
0)英文相关词典-->dig
1)英文相关词典-->do
2)英文相关词典-->dock
3)英文相关词典-->doff
4)英文相关词典-->dole
5)英文相关词典-->dolt
6)英文相关词典-->don
7)英文相关词典-->done
8)英文相关词典-->doom
9)英文相关词典-->dose
Your choice[-1 to abort]: 5
-->英文相关词典
-->dolt
<单词解释块>
<基本词义>
<单词项>
<单词原型><![CDATA[dolt]]></单词原型>
<相关词><![CDATA[&L{blockhead}&L{dunce}&L{numskull}]]></相关词>
</单词项>
</基本词义>
</单词解释块>
```

**Working**
```
21century chinese-english and english-chinese dictionary]$ sdcv -c --data-dir=. -l && sdcv -c --data-dir=.  警犬
Dictionary's name   Word count
21世纪英汉汉英双向词典    213723
Found 10 items, similar to 警犬.
0)21世纪英汉汉英双向词典-->上犬牙
1)21世纪英汉汉英双向词典-->吠犬不咬
2)21世纪英汉汉英双向词典-->大犬座
3)21世纪英汉汉英双向词典-->小犬座
4)21世纪英汉汉英双向词典-->山犬
5)21世纪英汉汉英双向词典-->恶犬
6)21世纪英汉汉英双向词典-->桀犬吠尧
7)21世纪英汉汉英双向词典-->牧犬
8)21世纪英汉汉英双向词典-->犬
9)21世纪英汉汉英双向词典-->狂犬病
Your choice[-1 to abort]: 0
-->21世纪英汉汉英双向词典
-->上犬牙

1.an eye tooth
```

**Comment by Ocarinalover** [comment]
when ancien

**Comment by Ocarinalover** [comment]
when the ancient chinese dictionary was not in the dict folder , http://pan.baidu.com/s/1jIFbkyE      
password 3p0x

**Comment by Ocarinalover** [comment]
after adding the acient chinese dictionary to the dict folder   
http://pan.baidu.com/s/1pK85hGJ
password   557l

**Comment by Ocarinalover** [comment]
i used the latest android koreader version (nightly build)

**Comment by Markismus** [comment]
So without ancient chinese dictionary:
![1](https://cloud.githubusercontent.com/assets/5269101/18420006/a14917b2-7868-11e6-861d-59d3892596b6.jpg)

after adding the acient chinese dictionary to the dict folder:
![2](https://cloud.githubusercontent.com/assets/5269101/18420012/bf1150ac-7868-11e6-990c-69bf824ae157.jpg)

Alright, I try it on my device and get back to you.

**Comment by Markismus** [comment]
So, I've done a lot of work that seems to boil down to: If I have to input a chinese character I am lost.

**On my system:** 
Running `stardict-verify` gives zero errors on _ancient chinese dictionary_. Running _21century chinese-english and english-chinese dictionary_ through `stardict-verify` gives pages of errors. So the problem is not that it is a bad dictionary.

**On my Kobo Glo:** 

So when I use the non-functioning dictionary _lazyworm-ec_ that uses english lemmas as input:
```
# ./sdcv --utf8-input --utf8-output -l && ./sdcv --utf8-input --utf8-output dog
Dictionary's name   Word count
\u61d2\u866b\u7b80\u660e\u82f1\u6c49\u8bcd\u5178    452185
Found 1 items, similar to dog.
-->懒虫简明英汉词典
-->dog

[dɔg]
n.
狗, 犬, 类似犬的动物, 卑鄙的人, 小人, 坏蛋
vt.
跟踪, 尾随
```

When I use the _advanced chinese learner's dictionary_ (Also not working), I get when copy-pasting 跟踪 (represented in the terminal by ??):
```
# ./sdcv --utf8-input --utf8-output -l && ./sdcv --utf8-input --utf8-output ??
Dictionary's name   Word count
\u61d2\u866b\u7b80\u660e\u82f1\u6c49\u8bcd\u5178    452185
\u9ad8\u7ea7\u6c49\u8bed\u5927\u8bcd\u5178    51675
Found 1 items, similar to 跟踪.
-->高级汉语大词典
-->跟踪

gēnzōng
(1)
[shadow sb.;follow the tracks of sb.]
(2)
紧紧跟随在后面
牛元峰待援无望,趁黑夜率领残部突围向西逃跑,我七十五师的战士,随即跟踪追击。――《奠基礼》
跟踪查明古围墙的路线
(3)
有意地、偷偷地跟随
有时…被陆军、海军或联邦调查局的小汽车跟踪
```

When I add the _ancient chinese dictionary_ and remove _advanced chinese learner's dictionary_, I get an segmentation fault:
```
# ./sdcv --utf8-input --utf8-output -l && ./sdcv --utf8-input --utf8-output ??
Dictionary's name   Word count
\u61d2\u866b\u7b80\u660e\u82f1\u6c49\u8bcd\u5178    452185
\u53e4\u6c49\u8bed\u5e38\u7528\u5b57\u5b57\u5178    3933
Found 1 items, similar to 跟踪.
-->古汉语常用字字典
-->踪

zōng①<名>脚印；踪迹；踪影。柳宗元《江雪》：“千山鸟飞绝，万径人～灭。”《促织》：“而心目耳力俱穷，绝无～响。”②<动>追随；追寻。《新唐书·桓彦范传》：“安足继～前烈。”【】。《》：“～。”";

Segmentation fault
```
When I also include the _advanced chinese learner's dictionary_ the Segmentation fault doesn't happen:
```
# ./sdcv --utf8-input --utf8-output -l && ./sdcv --utf8-input --utf8-output ??
Dictionary's name   Word count
\u61d2\u866b\u7b80\u660e\u82f1\u6c49\u8bcd\u5178    452185
\u9ad8\u7ea7\u6c49\u8bed\u5927\u8bcd\u5178    51675
\u53e4\u6c49\u8bed\u5e38\u7528\u5b57\u5b57\u5178    3933
Found 1 items, similar to 跟踪.
-->高级汉语大词典
-->跟踪

gēnzōng
(1)
[shadow sb.;follow the tracks of sb.]
(2)
紧紧跟随在后面
牛元峰待援无望,趁黑夜率领残部突围向西逃跑,我七十五师的战士,随即跟踪追击。――《奠基礼》
跟踪查明古围墙的路线
(3)
有意地、偷偷地跟随
有时…被陆军、海军或联邦调查局的小汽车跟踪
```

Conclusion is that the _ancient chinese dictionary_ generates a memory error. This causes `sdcv` to crash before it returns a value to koreader. The other non-functioning dictionaries that I tested, work. I can look up a english lemma, get a chinese entry and look those symbols up again.

**Comment by Markismus** [comment]
You can convert the binary files with `stardict-bin2text`  into a xml-file. For the _ancient chinese dictionary_ an article looks like this:
```
<article>
<key>一</key>

<definition type="m">
<![CDATA[yī①<数>。《狼》：“～屠晚归。”②<连>一边；一面。《兰亭集序》：“～觞～咏，亦足以畅叙幽情。”③<形>同一；一样。《察今》：“古今～也。”④<动>看作一样。《兰亭集序》：“固知～死生为虚诞，齐彭殇为妄作。”⑤<动>统一。《阿房宫赋》：“六王毕，四海～。”⑥<动>专一。《劝学》：“用心～也。”⑦<副>全；一概。《岳阳楼记》：“而或长烟～空，皓月千里。”⑧<副>一旦。《信陵君窃符救赵》：“公子诚～开口请如姬，如姬必许诺。”⑨<副>才；刚刚。《赤壁之战》：“初～交战，操军不利。”⑩<副>初次。《曹刿论战》：“～鼓作气。”【一旦】⒈有一天。⒉一时；忽然。⒊形容时间很短。【一何】多么。【一力】⒈协力。⒉竭力。【一体】关系密切，如同一个整体。一样，相同。【一昨】前些日子。";]]>
</definition>
</article>
```

For the _advanced chinese learner's dictionary_ it looks like this:
```
<article>
<key>一</key>

<definition type="m">
<![CDATA[yī
(1)
都,一概 [all]
一匡天下。――《史记·货殖列传》
(2)
又如:一划(一律);一回(一概);一弄(一切;全体);一抹光(全都包括在内);一往(一概;一律);一括(犹言总括);一是(一概)
(3)
很;甚 [very]。如:一无性天(非常虚伪);一力价(极力地);一撮儿(极其;百般)
(4)
始终 [straight;always;all along]。如:一象(一像。一向;从来);一起(一向;向来);一行(一向;一直);一了(一直;从来);一往(犹一向)
(5)
一经 [once;in case]
诚一开口。――《史记·魏公子列传》
俗之一改。――《史记·屈原贾生列传》
黄鹤一去不复返,――唐·崔颢《黄鹤楼》
禄山一出。――宋·苏轼《教战守》
一出门。――《聊斋志异·促织》
(6)
又如:一膺新命(一旦接受朝廷的任命);一觉(一旦);一头(一旦);一投(方言。一等到;一旦)
(7)
犹一一 [one by one;one affer another]。如:一略数(谓一一略举);一听(一一倾听)

yī
初次,第一次;开始 [first;begin]。如:一箭上垛(比喻旗开得胜,首次就达到目的);一生人(初次卖做奴婢的女子);一头里(原来;起先);一成(初次制成的);一回生(初见陌生);一见如旧(一见如故。初次相见意气相投,有如故交);一初(开始;起初);一征(初次征战);一听(初听)

yī
(1)
全;满 [whole;full]
一肌一容(一:全部。指宫女的整个肌肤容貌)。――唐·杜牧《阿房宫赋》
传一乡。――宋·王安石《伤仲永》
洞庭一湖。――宋·范仲淹《岳阳楼记》
长烟一空。
欢动一城。――明·高启《书博鸡者事》
通订一舟。――明·魏学《核舟记》
(2)
又如:一罟(全部;一点不留);一是(全赁);一凭(任凭;完全凭仗);一抹(全部);一听(听任);一划(一派);一床(全部[乐器]);一力(竭力);一创(整个);一到处(到处;四处);一条提(全部;统统);一抹光(一律免除或不予追究);一到处(遍地里);一肩儿(所承担的全部责任)
(3)
相同;一样 [same]。如:一个稿子(一模一样);一便价(一式的;一律的);一似(好像;似同);一同(相同;一样);一理(同一准则)
(4)
齐一;联合 [joint;combined]。如:一缴过儿(一起);一搭儿(一答里。一起;一块儿);一合儿(一同;一起);一就(一并;一起);一心(同心;齐心);一堆(一起;一块);一淘(一道;一路);一派(一齐);一体(一起;一块)
(5)
统一 [unified;unitary]
以一中外之心,以色觊觎之望。――《子谦全传》
六王毕,四海一。――杜牧《阿房宫赋》
(6)
又如:一正(统一法度政令);一匡(使得到匡正);一法(统一的法令);一是(犹言统一的标准);一量(统一度量);一统天下(统一全国)
(7)
专一 [single-minded;concentrated]
用心一世。――《荀子·劝学》
(8)
又如:一德无暇(一心一意,没有一点虚情假意);一心一计(一心一意)
(9)
纯一不杂 [pure]。如:一青(犹纯青);一抹黑(形容一团漆黑);一纯(心地纯一)
(10)
独 [single;alone]。如:一目(独眼);一取(独取);一眼(一只眼睛。特指独存一眼);一尊(独尊)]]>
</definition>
</article>
```

**Comment by Markismus** [comment]
When I convert the _ancient chinese dictionary_ back with `stardict-text2bin` it gives the same result on _my PC_:
```
$ sdcv -c --data-dir=. -l && sdcv -c --data-dir=.  警犬
Dictionary's name   Word count
古汉语常用字字典    3933
Found 1 items, similar to 警犬.
-->古汉语常用字字典
-->警

jǐng1<动>告诫;警告。《狱中杂记》:“是立法以~其余。”2<动>警戒;戒备。《左传·宣公十二年》:“军卫不彻,~也。”3<名>危险紧急的情况或消息。《左忠毅公逸事》:“每有~,辄数月不就寝。”4<形>敏捷;敏锐。《三国志·魏书·武帝纪》:“太祖少机~,有权数。”";
```
However, the on _my Glo_ `sdcv` won't acknowledge anything about it:
```
# ./sdcv --utf8-input --utf8-output -l && ./sdcv --utf8-input --utf8-output ??
Dictionary's name   Word count
Nothing similar to 跟踪, sorry :(
```

**Comment by Markismus** [comment]
I played around a bit and found out that if I only install _ancient chinese dictionary_ it works without `sdcv` crashing: 
```
# ./sdcv --utf8-input --utf8-output -l && ./sdcv --utf8-input --utf8-output ??
Dictionary's name   Word count
\u53e4\u6c49\u8bed\u5e38\u7528\u5b57\u5b57\u5178    3933
Found 1 items, similar to 跟踪.
-->古汉语常用字字典
-->踪

zōng①<名>脚印；踪迹；踪影。柳宗元《江雪》：“千山鸟飞绝，万径人～灭。”《促织》：“而心目耳力俱穷，绝无～响。”②<动>追随；追寻。《新唐书·桓彦范传》：“安足继～前烈。”【】。《》：“～。”";
```

However, as soon as I install another dictionary, I get the segmentation fault again. It's kind of a mind boggle: there are only 4k words in the dictionary, while the other has 450k. 

The only thing I can think of is that the very long single line definition (see the xml snippet above) sets the memory size for each line of definition. For the small dictionary or our large PC's it doesn't matter. But as soon as `sdcv` has to load 450k entries with multiple lines at that size, it just doesn't fit in my Glo's memory.

@chrox Do you have a speculation or an idea where we could look to make sdcv more crash-proof? 

I don't think you'll fix this on the user end. Someone actually has to go on and debug `sdcv`. I remember running into these problems

**Comment by Frenzie** [comment]
I didn't see this at the time, but note that upstream has received a variety of fixes: https://github.com/Dushistov/sdcv

I also created a separate branch that combines upstream from about half a year ago (because that's when I created it) with our patches on top. Those will hopefully be integrated soon, see https://github.com/Dushistov/sdcv/issues/6

Anyway, it could be interesting to compile my branch or current upstream to see how it fares.

**Comment by Frenzie** [comment]
I'll close this under the hopeful assumption that #3071 fixed it (combined with the lack of activity). Feel free to reopen if it didn't.
