### ISSUE TITLE
KOReader crash/freeze on book status page

### ISSUE THREAD

**Issue by edwintorok** [koreader/koreader#2240]
- KOReader version: koreader-android-arm-linux-androideabi-v2015.11-587-ga55a987.apk
- Device: Samsung Galaxy Tab 3 7" WiFi (SM-T210, Android 4.4.2)

freeze also reproduces on Tolino Vision 3 HD (Android 4.0.4)
#### Issue

Crash on 'Book status' page
#### Steps to reproduce

Download and open this PDF in KOReader (don't know if the actual PDF matters): https://people.eecs.berkeley.edu/~wkahan/UnumSORN.pdf
Tap middle right to advance to next page until you get the book status screen where you can enter notes.
Try entering a note.

Expected behaviour:
- be able to enter notes

Actual behaviour:
- sometimes KOReader crashes while opening the book status screen
- sometimes KOReader crashes while typing in the notes section (I was typing the string: 'testing')
- sometimes KOReader just freezes on the 'book status' screen (i.e. I get a popup after a while saying its not responding)
- sometimes typing a note just works

The crash/freeze doesnt' reproduce all the time, however I captured two traces with 'adb logcat' where the crashes did occur:
https://gist.github.com/edwintorok/bcacd7a38253e66186e0da9f69dab365#file-crash1-L2741 
https://gist.github.com/edwintorok/bcacd7a38253e66186e0da9f69dab365#file-crash1-L5391
https://gist.githubusercontent.com/edwintorok/bcacd7a38253e66186e0da9f69dab365/raw/3388ad6208e532310b323b57830266870c8e9955/gistfile1.txt

Looks like some sort of NULL dereference/jump to NULL address?

To reproduce the crash I force stop KOreader, then delete the .sdr folder and repeat the above steps until I get either a crash or a freeze.

When KOreader froze I found this in the .sdr directory:
/sdcard/Download/UnumSORN(2).sdr/metadata.pdf.lua

```
-- we can read Lua syntax here!
return {
    ["summary"] = {
        ["status"] = "",
        ["modified"] = ""
    },
    ["stats"] = {
        ["performance_in_pages"] = {
            [1473176357] = 25,
            [1473176370] = 25
        },
        ["authors"] = "Prof. W. Kahan",
        ["notes"] = 0,
        ["total_time_in_sec"] = 18,
        ["title"] = "UnumSORN",
        ["highlights"] = 0,
        ["pages"] = 26,
        ["series"] = "",
        ["language"] = ""
    }
}
```

**Comment by houqp** [comment]
Thanks for the detailed bug report! Unfortunately, we are running into limitation in LuaJIT on android platform right now so android version is very unstable at this point. I will take a look into this once the LuaJIT issue is resolved.

**Comment by mirh** [comment]
If by "book status" we mean the page with "Review", then I cannot reproduce on Vision HD 4.

**Comment by Frenzie** [comment]
Can you still reproduce it @edwintorok ?

**Comment by Frenzie** [comment]
I'll close this due to a lack of activity and because I can't reproduce it on a couple of devices and the emulator, but please reopen or start a new issue should it occur again.
