### ISSUE TITLE
TOC page #'s show zeros for djvu files

### ISSUE THREAD

**Issue by okobo** [koreader/koreader#2242]
* KOReader version: kobo-arm-linux-v2015.11-587
* Device: kobo glo HD

#### Issue
Table of content items show all zeros for page numbers for djvu files; a click on any of which would lead to the first page. These same files work fine with djvulibre programs on both PC and linux system for their TOC items.
#### Steps to reproduce
Just try a djvu ebook with a TOC. If you cannot reproduce the error, I can email a djvu file with the said problem to you (file size 2.6 mb).

**Comment by houqp** [comment]
Can you send us the file? I am not able to reproduce it with the limited DJVU collection I have.

**Comment by okobo** [comment]
Thank you very much for the response.
Per your request, I have attached a djvu file with a TOC. I have created the djvu file by (1) scanning a book into separate tiff files, (2) binging the tiff pages into a single djvu book with djvubind program on Ubuntu linux computer, and (3) creating a TOC for the book using djvusmooth program in linux. The TOC works fine with the djvulibre suite on linux, but with Koreader on my Kobo Glo HD, the TOC items show all zero's for pages and tapping of any of the TOC items would lead to the first page.
One correction to my previous statement: I just found out that the TOC of the attached djvu file doesn't work on djvulibre on Windows 7 on a PC with the same set of problems. Maybe it is the inconsistency between linux and window systems.
I appreciate your help on this very much.
 

    On Sunday, September 11, 2016 2:11 AM, Qingping Hou <notifications@github.com> wrote:
 

 Can you send us the file? I am not able to reproduce it with the limited DJVU collection I have.—

**Comment by houqp** [comment]
@okobo did you forget to attach the file? It's probably easier for you to just send me the file through email. You can find it on my github profile ;)
