### ISSUE TITLE
Kobo Aura HD - frontlight is on after sleep, but only in theory

### ISSUE THREAD

**Issue by Ebrehem** [koreader/koreader#2247]
- KOReader version: since June up to all recent versions, including 2015.11.594
- Device: Kobo Aura HD

When device is awaken from sleep frontlight is not enabled, I can enable it by selecting frontlight from menu, and pressing toggle twice, so it is turned on in theory, not visible in reality. It seems to be regardless of frontlight setting (sync with nickel or +10).

Steps to reproduce: sleep then wake. (It is OK when koreader is started.)

**Comment by dagrim1** [comment]
I noticed this this morning as well, frontlight was not on when the device woke up while it was on when I put it in suspend last night (in koreader)... Not sure how the sync with nickel works though (it is set to true).

I toggled it and it went on, after which it works as expected. I think it's some combination of Nickel/Koreader and maybe even KSM as well setting but have to put some more research into it to properly reproduce...

The following parameters are set:

KOBO_LIGHT_ON_START = -2 
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true

I the sync both ways? So is the level set in koreader also pushed to nickel and vice versa?

**Comment by Hzj-jie** [comment]
Yes, the sync is bidirectional, indeed we read and write a nickel setting if KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true, and KOBO_LIGHT_ON_START = -2.
@Ebrehem, would you mind to confirm whether these two settings in your defaults.lua and defaults.persistent.lua are set properly?

**Comment by Ebrehem** [comment]
Under Nickel it is on with 10 level. I have changed persistent.lua to 10, and falsa synch. Now I opened advanced settings, where I see -2 and true. Strange. But anyway, the setting is in line with the above.

**Comment by houqp** [comment]
I just fixed a bug couple days ago, which causes advanced setting to display values from `defaults.lua` instead of `persistent.lua`. The next release should fix the display issue. Can you try change it to -2 in persistent.lua?

**Comment by Ebrehem** [comment]
FALSE and 10 not work if both set in persistent.lua.

-2 and true works.

For me it is fine, though it means the only working functionality is sync with Nickel.

Does the setting eg. 10 and false (or true) work for anyone? I mean if it works only on setting -2 and true, probably the settings should be removed.

**Comment by pazos** [comment]
@Ebrehem: I can't reproduce on my devices. Everything works as expected with:

```
(sync)
KOBO_LIGHT_ON_START = -2
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = true

(don't sync, leave as is)
KOBO_LIGHT_ON_START = -1
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = false

(don't sync, set value)
KOBO_LIGHT_ON_START = [0-100]
KOBO_SYNC_BRIGHTNESS_WITH_NICKEL = false
```
AFAIK other combos aren't used.

I didn't find any light behaviour bug returning from suspend

**Comment by NiLuJe** [comment]
Can't reproduce either.

Re-open if need be.
