### ISSUE TITLE
Android build won't update lua scripts after upgrade

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2253]
* KOReader version: up to 76cef07
* Device: Android

#### Issue

After upgrade the app, one needs to manually clear data to trigger the update to the lua scripts.

#### Steps to reproduce

install app
update some lua scripts
rebuild app and reinstall
lua scripts won't take effect until manually clearing app data

**Comment by KenMaltby** [comment]
When I was doing that, I always uninstalled the existing KOReader before installing the new KOReader.apk.

**Comment by Hzj-jie** [comment]
This seems pretty user-unfriendly. We cannot tell users to do the same thing each time we upgrade the app.

**Comment by KenMaltby** [comment]
I modified the downloaded .apk, including modifying some of the .lua scripts and changing out the Icon used (I replaced it with my ego centric one).  Then just signed the modified .apk and it installed and runs with my changes.

**Comment by Hzj-jie** [comment]
Confirmed in android-luajit-launcher, https://github.com/koreader/android-luajit-launcher/blob/565a792157b7fef4fd7f5a278f41729059064e17/assets/install.lua#L15, the package installation depends on git reversion. So it should be fine when performing upgrade.

**Comment by houqp** [comment]
Yeah, but it's still a little bit annoying when you are testing a temporary change without a new commit.
