### ISSUE TITLE
Footer hides text

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2257]
- KOReader version: 2015.11-587
- Device: Kobo Glo
#### Issue

Sometimes, depending on an epub style, some text is hidden by the progress bar (the mini one at the bottom).
With normal style everything looks OK.
![reader_ok](https://cloud.githubusercontent.com/assets/8684739/18640792/559359aa-7ea2-11e6-8f22-883597d7983c.png)
But if there is a header in the page, something is about to cut off.
![reader_problem](https://cloud.githubusercontent.com/assets/8684739/18640793/5596bf28-7ea2-11e6-8f24-4e6038644063.png)
Shouldn't the size of the progress bar be taken into account and force the line to the next page?

edit: re-checked with 2015.11-587, no change.

**Comment by Hzj-jie** [comment]
This issue should be fixed by change https://github.com/koreader/koreader/commit/ac6ccc003878e569c29f12821b40c844d4da9723, you may want to try a later version.

**Comment by houqp** [comment]
@Hzj-jie readerzoom is only used for pdf/djvus. So we still need to fix this for crengine unfortunately :(

**Comment by Hzj-jie** [comment]
Oh, yes, I recall the detail, it was a bug for pdf.

**Comment by frankyifei** [comment]
But the footer is not always there, if the footer is hidden, should we render the document again?
It is easy to hide the footer by users.

**Comment by robert00s** [comment]
Does this problem still occur? In my reader, this problem is not present for few months.

**Comment by embryo10** [comment]
Yes.. (with 2015.11-1054)
