### ISSUE TITLE
Dialog when reopening book at start

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2259]
- KOReader version: 2015.11-587
- Device: Kobo Glo
#### Issue

This is something that concerns the readers with an external SD card.
It takes some time to mount the card's partition.
When I have koreader to open with the last book and that book is on the external SD, koreader starts in file browser.
If I wait a little, it opens with the book.
The problem is I don't know how little...
It would be nice if there was a dialog saying the book is not available and give the option to retry or cancel to the file browser.

edit: re-checked with 2015.11-587, no change.

**Comment by Hzj-jie** [comment]
This is because the Kobo OS won't mount the SD card before it finished startup. When you are using KSM to replace the default stock software, the mount may take up to some thirty seconds after KSM showing up.

**Comment by KenMaltby** [comment]
I find that about 7 seconds after the KSM menu appears, works for me. 

 From koreader.sh:
# Remount the SD card RW if it's inserted and currently RO
if awk '$4~/(^|,)ro($|,)/' /proc/mounts | grep ' /mnt/sd ' ; then
	mount -o remount,rw /mnt/sd
fi

./reader.lua "${args}" > crash.log 2>&1

As you can see the external SD card is accessed before reader.lua is called.
 
We could ask Tshering to consider adding a delay before calling koreader.sh. 

Luck;
Ken

**Comment by robert00s** [comment]
I propose the following dialog box saying the book is not available and give the option to retry or cancel.
We can click OK until book is available or Cancel to go filemanager.
What do you think?
![screen1](https://cloud.githubusercontent.com/assets/22982594/23333564/a70f16da-fb8d-11e6-9385-f6be80c39c65.jpg)

**Comment by Frenzie** [comment]
I'm slightly confused about what the OP is asking. Isn't there already a "file not found/available" dialog with automatic drop-back to the file manager? 

@robert00s Not objecting or anything; it's just a little unclear to me what the present behavior and/or the problem is.

**Comment by embryo10** [comment]
Yeap, that was exactly what I was thinking..
It wasn't available when I asked and I don't use a more recent version, so I don't know if its implemented..

**Comment by embryo10** [comment]
Yeap, that was exactly what I was thinking..

**Comment by embryo10** [comment]
@Frenzie The original behavior that I remember was that if the card was not mounted, you ended up at the file manager.
Then you had to find the history entry in the menus, and then select the last file again.
The point of the dialog was to wait there a little, and retry your luck... until the card was mounted.
Just lazier (if that's a word ;o)

**Comment by KenMaltby** [comment]
I think that the delay needs to be before the check for if the "last file option" is applied, in other words before ./reader.lua, for sloppy user scripting.

**Comment by robert00s** [comment]
So what are we doing with this issue? :)
Maybe only infomessage that the last file is not available? But I prefer dialog box with retry info...

**Comment by houqp** [comment]
I don't mind adding a dialog with retry.
