### ISSUE TITLE
Where are the history files?

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2261]
* KOReader version: 2015.11-587
* Device: Kobo Glo

#### Issue
I'm not really sure where the book's metadata.epub.lua is saved.
I don't remember well, but I think it used to be in a folder by the book, with the book's name + '.sdr' but with some newer koreader versions is in the /Koreader/History folder as "[#mnt#sd#.Books#Banks, Iain M_#] Iain M. Banks - Feersum Endjinn.epub.lua", and now with some even newer versions its again in the ".sdr" folders.
There are differences if it's on the internal or external maybe??
Is there a foolproof way to find these files?
I'm interested because I have written an [app to get the highlights](https://github.com/noonkey/KoHighlights) from these files and I wanted to add a semi-auto way to retrieve them.

edit: re-checked with 2015.11-587, no change.

**Comment by Hzj-jie** [comment]
The history folder is an old way, which is deprecated. Unless the "filename".sdr folder is not writable - this may happen on SD card of Kobo - KOReader won't write "[#mnt ... ] filename".lua file anymore.
And the file in .sdr folder is named as "metadata.file_suffix.lua", "file_suffix" is the suffix of the book, i.e. metadata of a.pdf is in a.sdr/metadata.pdf.lua, a.epub is in a.sdr/metadata.epub.lua.
History file / recent books is written in /koreader/history.lua, though KOReader still reads koreader/history folder.

**Comment by houqp** [comment]
@Hzj-jie summarized it well. In short, the latest setup is to store all book settings in `NAME.sdr/metadata.SUFFIX.lua` (except read-only SD card) and store all history info in `history.lua`.

**Comment by KenMaltby** [comment]
Isn't the SD card remounted to RW, if found to be RO, just before reader.lua is called?

**Comment by Hzj-jie** [comment]
The remount is for Kobo only, I cannot tell whether other devices support SD card.

**Comment by houqp** [comment]
and there are users who prefer to mount the SD card as RO
