### ISSUE TITLE
Chapter marks don't show in mini progress bar

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2262]
* KOReader version: 2015.11-587
* Device: Kobo Glo

#### Issue
When I first open a book although there are some chapters in it, the progress bar is empty.
I have to close and reopen the book to see the bar marks.
A known bug?

**Comment by AlanSP1** [comment]
I also have this problem, but I thought it is because I'm with old version and that it may be solved by now. But, it obviously isn't.

I have Kobo H2O.

Solution I use, if I want to see chapters in graphical progress bar is to exit koreader (into KSM) and return back. After that, chapters are visible.

**Comment by houqp** [comment]
Weird, I cannot reproduce this issue on my side. is it happening to all your books? Can you reproduce with this book? https://github.com/koreader/test-data/blob/master/djvu3spec.djvu

**Comment by embryo10** [comment]
@houqp 
With the djvu3spec.djvu the chapter marks are OK.
But all my books are epubs.
Try this one...
[The Kivy NUI Framework.epub.zip](https://github.com/koreader/koreader/files/486024/The.Kivy.NUI.Framework.epub.zip)

**Comment by AlanSP1** [comment]
One thing that comes to my mind is thing when live clock messed with opening books. This bug was solved, but maybe it is some option that we use, and you maybe don't.

I have all thing in status bar enabled and shown on together.

**Comment by houqp** [comment]
OK, I can reproduce with this epub now. It's weird that this does not happen to my other epubs.

**Comment by AlanSP1** [comment]
It happens for almost all my epubs (but I'm on older version, that also can be a factor). Or it is just my luck?

**Comment by AlanSP1** [comment]
I just saw linked FR - full progress bar (upper) adjustments thread and checked. It looks that bug mentioned here doesn't affect only lower, but also upper progress bar. When there are chapter marks in lower, then there are chapter marks in upper progress bar and vice versa.

So, this isn't related only to lower progress bar.

**Comment by houqp** [comment]
I submitted a PR to fix this issue. Note that this will only happen for new epub books. Once you exited the book once to create the book setting file, the issue will disappear.
