### ISSUE TITLE
Light level after suspend

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2263]
* KOReader version: 2015.11-587
* Device: Kobo Glo

#### Issue
When the KOBO_LIGHT_ON_START is some value (I used 5, 10, 20) the light does not open after waking from suspend.
It works OK with -2

**Comment by Hzj-jie** [comment]
Yes, KOBO_LIGHT_ON_START is a deprecated setting, which should always be -2. And KOReader synchronizes the front light setting with nickel, the stock software of Kobo, which has both on/off and level settings.

**Comment by houqp** [comment]
This is expected, although confusing, behavior. You should be able to find the comment in https://github.com/koreader/koreader/blob/master/defaults.lua#L173.

Hopefully, we will get rid of this setting in the future and have everything set in a user friendly UI.
