### ISSUE TITLE
Changing advanced settings and saving them in defaults.persistent.lua from within Koreader causes it to crash

### ISSUE THREAD

**Issue by anton79ru** [koreader/koreader#2264]
* KOReader version: v2016.08.23-nightly
* Device: Kobo Aura H2O

After creation of defaults.persistent.lua by changing the advanced settings from within koreader menu, it is no longer possible to activate menu by tapping upper area: koreader crashes. Deletion of defaults.persistent.lua fixes it.

Steps to reproduce: from file manager, go to advanced settings, change page margin size, save settings, exit koreader, start again, open a book, try to open menu.

**Comment by houqp** [comment]
I am not able to reproduce this on my side. Could you upload the crash.log here for analysis?

**Comment by anton79ru** [comment]
That's weird, but now I can't make it happen either.

**Comment by anton79ru** [comment]
Here, it happened again. Koreader crashed several times in a row, on three different books - two of them failed to open and one crashed when trying to activate the top menu. Once defaults.persistent.lua is deleted, everything works fine. For some reason, making changes to defaults.lua directly doesn't cause any trouble. I'm attaching three logs with three book files that crashed respectively.

[crashes.zip](https://github.com/koreader/koreader/files/511356/crashes.zip)

**Comment by anton79ru** [comment]
For some reason, defaults.persistent.lua created as a result of changing settings in the Koreader menu has different syntax than defaults.lua that's originally in the program forder. No idea as to whether that could contribute to the bug, just an observation.

**Comment by houqp** [comment]
This is expected. Sorry, I am having a bad headache right now after traveling. So probably won't be able to work on koreader until weekend :(

**Comment by houqp** [comment]
Hi @anton79ru looks like it's caused by a invalid config entry that's missing a key.

However, I am not able to reproduce on my side. What did you change in the advanced settings? Do you still have the defaults.persistent.lua that causes the crash to share with me?

**Comment by anton79ru** [comment]
I changed font gamma, line spacing, and page margins. Here's the file.
[defaults.persistent.zip](https://github.com/koreader/koreader/files/530249/defaults.persistent.zip)

**Comment by houqp** [comment]
Ha, I think I found the root cause. I fucked it up while refactoring that module. Will fix it soon. Sorry for the trouble :(

**Comment by houqp** [comment]
@anton79ru , could you try the patch in https://github.com/koreader/koreader/pull/2286/files?
