### ISSUE TITLE
FR - Ability to setup clock within koreader

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2265]
It would be useful if we can setup clock within koreader, similar like we can do within nickel.

At the moment I use KSM and its terminal to setup clock with linux date command, but some people probably don't use KSM and in general it is useful feature.

**Comment by KenMaltby** [comment]
I would guess that this could be another wifi related function to get the time off the net.  There was a discussion along that line , but I don't remember where.

**Comment by AlanSP1** [comment]
Of course that getting time from net is also good option, but I would like to have option for manually setting time.

I'm often in area where I can't have my or free wifi (there are still areas like this) and if I would have ability to setup time only through wifi, it wouldn't mean anything to me. I'll still need to use KSM's terminal (which I do at the moment to manually setup time).

**Comment by houqp** [comment]
Note for implementation detail, need to synchronize hardware clock with system one:

```
date 18:44:25
hwclock -w -u
```

ref: http://www.mobileread.com/forums/showpost.php?p=3401695&postcount=248

**Comment by hurzl** [comment]
I would like a manual setting, too.  Every time the battery goes low the time is reset.
And 1. there is not wifi everywhere, and 2. I have wifi off anyway.

**Comment by AlanSP1** [comment]
Yes, I agree.

Automatic syncing over internet is great, but sometime we need manual way to input correct time.
