### ISSUE TITLE
FR - Quick top menu commands (icons) for shutting off of reader and toggling light

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2266]
At the moment I use this small change in top menu commands made by xor_, you can find it here: http://www.mobileread.com/forums/showpost.php?p=3151522&postcount=2322 (Actually, this version needs adjusting to work with KSM 8, which is easily done and there is KSM version).

It adds ability to turn off ebook reader completely and ability to toggle light quickly and easily.

It would be useful if these two additions become koreader native. Now I need to change file to achieve this. It is very useful, especially light toggle, but powering off of reader also can be useful.

I think that xor_ wouldn't mind if his code is used (it only needs some power off script to be created, that can be called from menu), as well as graphic images. Of course, xor_ needs to be asked about this if his code would be used.

I use this options frequently and think that others will also found them very useful.

**Comment by WolfBackGR** [comment]
I don't know about this mod.... till today.
It was so painful changing the frontlight on/off within the menu's toggle function and as the shutdown feature, is simply awesome! This option its a deal breaker for me. 
Thanks Alan for the mod's link. (I really don't know how I miss this all this time...)
I hope that someone adds this feature in future releases of Koreader! (Please ???)

**Comment by AlanSP1** [comment]
I hope you found version that works with KSM 8 as well, as it needs a bit of fixing (correct path to shutdown script).

And yes, this is something really useful and also something that can fairly easily could be added to already great koreader.

**Comment by AlanSP1** [comment]
Here's is latest version from xor_ supporting KSM8: http://www.mobileread.com/forums/showpost.php?p=3264641&postcount=4

**Comment by xorrox** [comment]
For the record, of course you can use my code if it seems helpful. It's just a minimal hack anyway. I never made it official because I wasn't sure there was a lot of interest.

**Comment by KenMaltby** [comment]
It should be possible to check in both places and make it usable for both versions of KSM.  (If you grep what I mean.)

**Comment by AlanSP1** [comment]
@KenMaltby I guess that if it would be supported within koreader, then there could be also poweroff script included in koreader installation, making it working for people that don't use KSM.

**Comment by houqp** [comment]
Sorry I have missed this discussion. Currently, in koreader you can power off the device by long pressing the power button, does this handle your use case?

**Comment by AlanSP1** [comment]
I didn't know about long press, powering off with icon seems more intuitive for me.

All coding is done ( xorrox agreed), it could be simple implementation, as there is already power off script called by long press.

Having more than one way to do some things isn't always bad UI, it may be even better.

Anyway, it is up to you to decide if you think this change is worth to be implemented.

**Comment by houqp** [comment]
I have no objection for including a power off option in the menu as long as we don't overload the menu. Probably worth packing it into the same submenu with the exit koreader option.

**Comment by AlanSP1** [comment]
On my H2O this two additional options (light toggle and power off) work just fine.

Maybe on devices with smaller screen that could be a problem, but I can't tell. Maybe if someone with smaller screen device can show us how this looks like?

**Comment by houqp** [comment]
I think it's not just about screen size, but rather putting two less used options into the top level menu. I have no objection adding them to a sub menu though, which is just two taps away.

Regarding to light toggle feature, with the newly added light gesture support in kobo, you should be able to toggle it by tapping left bottom of the screen now. Have you tried this feature yet?

**Comment by KenMaltby** [comment]
I think what this is being looked for is a quick/one step way to "power off" the device, not just exit KOReader.  You can currently "two poke" to power off, if using KSM, by exiting KOReader (poking the Home icon) and then poking the "Power Off" option on the KSM menu.  What the mod provided was essentially that, with one poke. 

This was seen as a power saving avoidance of suspend issues.

Luck;
Ken

**Comment by AlanSP1** [comment]
@houqp I still didn't tried latest koreader with light toggle, but I guess that this will be something I'll use on daily bases. So this leaves light toggle button a bit redundant, but also this isn't necessarily bad UI, being able to do something in more than one way. But, it can be dropped out from koreader.

As @KenMaltby said, power off with one press is nice feature to have, not only for now mostly solved power problems, but also as having that option. On the other hand, it depends if you think it is useful or not.

For me personally it is, I used it regularly, but also I understand that everyone has own preferences. Anyway, I still can manually copy file when upgrading if I'd like to keep these features, so you can close this if you think that is best course for koreader.

**Comment by houqp** [comment]
If it's for general power consumption issues in suspend mode, then we should focus on fixing the broken suspension mode instead (which is what's actually happening right now).

I can see that if you care every bit of the power consumption, then having a quick way to power off device makes sense. But I don't see a convincing argument that this is indeed a common use-case for majority of the users. For me, I don't even want to tap anything, I just want to close and open my sleep cover ;)

Luckily, KOReader, as an open-source project, can be tweaked by anyone to suite his/her own needs. 

I would also accept the patch for an extra power off icon if it's made into a configurable setting or plugin that's off by default.

**Comment by AlanSP1** [comment]
It seems fine to me that it is an option, to have visible power off button or not. So, if you can make it so, it is something I'd like to use.

**Comment by xorrox** [comment]
@houqp
> Regarding to light toggle feature, with the newly added light gesture support in kobo,  > you should be able to toggle it by tapping left bottom of the screen now.

I have a hard time finding that spot to toggle. While the gesture for changing the frontlight level works on my H2O (thanks for that), I can't get it to toggle. Tapping the very bottom left, it toggles the status bar, and above that it triggers the page back option. Could it be that it interferes with the status bar, or am I just not finding the right spot?

That said, this light toggle option, in addition to the recent improvements in suspend mode, take care of my initial reasons for making this additional icons.

**Comment by houqp** [comment]
I agree, I had a hard time finding the toggle spot too. I also just use the hardware button directly so I did not take a look into it. I should definitely fix it though.

I am still working on the last issue for suspend mode, after that hopefully we should have a perfect suspend support.

With regards to power off button, @baskerville recently changed the long press power off behavior so that you can power off the device by just long pressing the button, no confirmation modal will popup. So now it's only 1 press now v.s. two taps for an icon in the menu.

**Comment by AlanSP1** [comment]
@xorrox I had the same problem as you and @houqp have, but I found solution that works really great by @ycrichard help. You can found it here: https://github.com/koreader/koreader/pull/2284#issuecomment-261707439 and comments afterwards.

You need to do at least one thing, control status bar zone. Or, also, make a bit bigger light toggle zone. Now it works excellent, without any problems, after you modify zones that trigger those two functions. It's pretty easy. I also made thinner zone for status bar, not to interfere with lowest rows of text and not to toggle it by accident.

Anyway, as it is now by default, those two zones needs changes. So I suggest that we change them in defaults.lua. At least status bar one, not to interfere in the future for new users, because it really messes with light toggling function. Small PR will do this easily.

I did for myself these changes:

For light toggling zone:

local DTAP_ZONE_KOBOLIGHTTOGGLE = {x = 0, y = 0.92, w = 0.1, h = 0.08 }

For status bar zone:

DTAP_ZONE_MINIBAR = {x = 0.1, y = 0.98, w = 0.9, h = 0.02}

For me it works great, you can adjust settings to your liking. But status bar zone should be changed not to overlap with lighttogoggle zone.

@houqp Now that I'm on 694 and have all these new options, I think that maybe we don't need this FR at all, as all can be used great. Only we need to make small changes for light toggling in status bar. Powering off with long button press also works great, so it is also solved.

I you think it OK, you can close this FR.

**Comment by ycrichard** [comment]
I don't understand when 2 zones overlap which one will function in priority. Can someone enlighten me as well :p
Changing the default DTAP_ZONE_MINIBAR should be a good idea, I am just aware of non-kobo users. In those case, lower-left corner will be a dead zone by default.

**Comment by houqp** [comment]
Whichever widget got registered later overrides the tap zone. If I recall correctly, migrating the code to a plugin will make it register after the footer widget so it will take higher priority to footer's event listener.

**Comment by AlanSP1** [comment]
I think that system we now have solves need to have additional icons. Only problem I see is, how new users would know that they can toggle light with one tap, as well as turn off device by pressing power button for 2 seconds.

Maybe if we put some information in wiki about this info?

Also, there's problem of light toggle zones, as I described it here: https://github.com/koreader/koreader/issues/2266#issuecomment-261928796

**Comment by houqp** [comment]
> I think that system we now have solves need to have additional icons. Only problem I see is, how new users would know that they can toggle light with one tap, as well as turn off device by pressing power button for 2 seconds.

Yes, putting these information in wiki will be very helpful. In the long term, we should document this features within the code and have toolings to automatically generate user manuals based on the code comments.

> Also, there's problem of light toggle zones, as I described it here: #2266 (comment)

Like I said in my previous comment, migrating it to a plugin will likely fix the issue

**Comment by houqp** [comment]
OK, I lied in my previous comment. My journey of fixing this resulted in a rather large refactoring in the touch event handling code... See: https://github.com/koreader/koreader/pull/2408

**Comment by AlanSP1** [comment]
Thank you, this probably means also new way of defining touch zones?

**Comment by houqp** [comment]
Yes, probably not much impact for the end users, it's mostly an optimization and simplification for the code.

**Comment by houqp** [comment]
The light toggle tap zone issue should have been fixed in the latest build.
