### ISSUE TITLE
FR - full progress bar (upper) adjustments

### ISSUE THREAD

**Issue by Yaretzki** [koreader/koreader#2269]
hello,
When we turn on full progress bar:
DCREREADER_PROGRESS_BAR = 1
 we can see on top of the screen progress bar and some additional information.
This additional information can be modified in file koreader/data/cr3.ini by changing values:
window.status.battery=1
window.status.battery.percent=0
window.status.clock=0
window.status.line=0
window.status.pos.page.count=1
window.status.pos.page.number=1
window.status.pos.percent=0
window.status.title=1

But how to change full (upper) progress bar and chapters markers thickness?
Yaretzki

**Comment by AlanSP1** [comment]
At the moment we can't do this. It needs to be done.

But, I just checked and saw that this bug affects also full progress bar. https://github.com/koreader/koreader/issues/2262

**Comment by protist** [comment]
On my Kobo H2O, some of the chapter markers are almost invisible. Oddly enough, it seems to be slightly inconsistent between marks. I'm happy to provide a photo if useful.

Even the more obvious marks are hard to see, so it would be great to be able to increase the vertical width of all marks.

**Comment by Frenzie** [comment]
I'll close this because it's not something that can currently be done and it's a fairly old issue. But improvements continue being made to the statusbar. ;-)
