### ISSUE TITLE
FR - controlling light similar to nickel (swiping on the left to adjust level, tapping lower left to toggle...)

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2270]
There's this mod made by yc_richard (nick on MobileRead) that allows koreader to emulate nickel way of controlling light plus more features.

To copy original text from yc_richard:

_________________
 I have made a mod to the latest koreader nightly v2015.11-431. Tested on my Kobo aura H2O.

Additional Functions are:
1. Frontlight can be toggled on and off by taping the bottom left corner. And frontlight level can be adjusted by sliding up or down on the left edge of the screen (add file: readerkobolight.lua; change file: readerview.lua.lua)
2. Frontlight level is shown in the footer (change file: readerfooter.lua)

Hope someone find it useful.
__________________

You can find mod here: http://www.mobileread.com/forums/showpost.php?p=3337353&postcount=20

Hope this could be also integrated within koreader. Only feature request from me would be option to control is swiping active, as well as toggle to show light level in status bar or not.

**Comment by oldhasbeen** [comment]
@AlanSP1 
I fully support this request. I use this mod and it works perfect.

**Comment by jscris** [comment]
Yes, please!

**Comment by trekk2810** [comment]
This functionality is surely an improvement and should be integrated. Works on my KA1.

**Comment by andruha30** [comment]
Support the idea!!!!!

**Comment by Hzj-jie** [comment]
The toggle is useful for Kindle, because of leaking a physical button.

**Comment by AlanSP1** [comment]
Some Kobos also miss hardware button (my H2O for sure, but also KA1, and probably some more models).

**Comment by houqp** [comment]
I would love to merge this patch into official KOReader. If anyone of you has contact with yc_richard, please ask him if he can send the patch to github ;)

**Comment by AlanSP1** [comment]
I just sent him PM on MobileRead forum. Hopefully he will read it and answer. Sadly, his last activity was 27.7.2016.

But, maybe he requested receiving emails when receiving PMs. Will see.

Is there a way that you include it yourself? From what he wrote, I think he wouldn't mind (but, I surely would like to check this with him anyway, fair is fair and this is his code). I asked him to join koreader dev team here: http://www.mobileread.com/forums/showpost.php?p=3338257&postcount=26

This is his answer quoted here:

> Sadly, I have never learned or coded in LUA before. I know Linux and bash that can help explore and read its source code.

Joining team sounds really appealing but only when after I feel comfortable with LUA and get more free time, lol. Lots of staff to learn first.

**Comment by ycrichard** [comment]
Hey guys, 
I'm "yc_richard" from MobileRead. I am glad to merge this patch if possible!

I could upload the files for build 587 here, or do you prefer that I submit a pull request based on the current master branch? I'm totally flexible about this. 

BTW, anyone knows where to find the latest nightly build for aura one? Sorry to be off the topic.

**Comment by houqp** [comment]
Hi @ycrichard ! Glad to see you here :) It would be great (and save us a lot of time) if you can submit a PR against the latest master. I can help review your patch there.

I am still setting up the new nightly build service. For now, you can download it from: https://gitlab.com/koreader/nightly-builds/builds/5055439/artifacts/browse/koreader/

**Comment by AlanSP1** [comment]
@houqp 

We can close this now.
