### ISSUE TITLE
Cannot use custom css with android version.

### ISSUE THREAD

**Issue by N46AN** [koreader/koreader#2272]
- KOReader version: v2015.11-587-ga55a987
- Device: ShiaoMi MI Note LTE
#### Issue

Custom css file placed in /mnt/sdcard/koreader/data do not show up in koreader.
#### Steps to reproduce
1. Download and install https://github.com/koreader/koreader/releases/download/v2016.08.23-nightly/koreader-android-arm-linux-androideabi-v2015.11-587-ga55a987.apk
2. Start KOReader so as to initialize /mnt/sdcard/koreader/data (not sure if this is necessary)
3. Place some custom css files in /mnt/sdcard/koreader/data
4. Close and start KOReader again
5. custom css files do not show up in "Set render style"

**Comment by pazos** [comment]
out of date, new path to store custom css is sdcard/koreader/styletweaks, working fine here.

@N46AN please reopen tif you find this issue again!
