### ISSUE TITLE
Koreader crashes when I attempt to enable wi-fi network

### ISSUE THREAD

**Issue by pdo-smith** [koreader/koreader#2273]
- KOReader version: a55a987 - koreader-nightly-20160823
- Device: Kobo Glo, KSM 08
#### Issue

 Koreader crashes when I attempt to enable the wi-fi network and the KSM screen is shown

Contents of crash log:

./luajit: frontend/ui/network/wpa_supplicant.lua:11: attempt to index local 'wcli' (a nil value)
stack traceback:
    frontend/ui/network/wpa_supplicant.lua:11: in function 'getNetworkList'
    frontend/ui/network/manager.lua:142: in function 'action'
    frontend/ui/uimanager.lua:472: in function '_checkTasks'
    frontend/ui/uimanager.lua:618: in function 'handleInput'
    frontend/ui/uimanager.lua:712: in function 'run'
    ./reader.lua:175: in main chunk
    [C]: at 0x0000bea5
#### Steps to reproduce
1. Network
2. Wi-Fi connection
   Do you want to turn on Wi-Fi?
3. OK
   Koreader closes and KSM message is displayed:
   Info: Wifi is enabled
4. Close KSM text window and KSM main menu is displayed.

**Comment by houqp** [comment]
The wi-fi feature is only implemented for aura hd since that's the only kobo device I have. We will need to do a little bit of tweaking to make it work for Glo. Do you know what's the command to turn wifi on in Glo? Or do you know is there any wifi management script that I can use as a reference?

**Comment by Hzj-jie** [comment]
Good news is, the wifi also works for Aura HD.

**Comment by Frenzie** [comment]
Is this still an issue? The wifi was changed about a fair bit.

**Comment by houqp** [comment]
@pdo-smith can you give the latest build a try? The recent change in enable-wifi script might have fixed this issue. If not, please reopen this issue.
