### ISSUE TITLE
A screen size adjustment bug on e-ink Onyx Boox i86ml

### ISSUE THREAD

**Issue by ossovskiy** [koreader/koreader#2275]
- KOReader version: koreader-android-arm-linux-androideabi-v2015.11-587-ga55a987
- Device: Onyx Boox i86ML
#### Issue

When the deviceis switched into the full-screen mode (system bar removed), the koreader doesn't adjust to the new free space. The whole thing moves up and a thick black strip appears at the bottom of the screen.
#### Steps to reproduce

Start koreader, then start any full screen app (QuickFullScreen for instance).

**Comment by Frenzie** [comment]
Fixed by koreader/android-luajit-launcher#63. You might have to remove a patch.lua if you have any.
