### ISSUE TITLE
koreader-nightly freezes on kobo h2o

### ISSUE THREAD

**Issue by Wonko7** [koreader/koreader#2278]
* KOReader version: koreader-nightly-20160823 / koreader-kobo-arm-linux-gnueabihf-v2015.11-587-ga55a987.zip
* Device: kobo h2o

#### Issue
Koreader ends up freezing after ~5 to 10 minutes of usage. Either while I'm reading, or if I put it to sleep and later turn it back on, the book does appear on the screen, but the touchscreen stops responding, I can't change pages/bookmark the page/open the menu. 
The power button responds and I can put it back to sleep, but it's still in the same state when I bring it back up.
I have to press the power button for 20 secs to get the device to reboot. 

At one point it also forgot all the data on one book (bookmarks, current page etc) and wouldn't show chapter ticks on the status bar, though navigating the table of contents was still possible. Now it's working again. 

I'm using the nightly build because stable would (less frequently) freeze but require a hard factory reboot using a toothpick. 

crash.log is always empty, but after changing koreader.sh to capture stdout with:
``/reader.lua -d /mnt/onboard > koreader.log.`date +%s` 2>&1``
I reproduced the freeze three times and got these logs:
https://paste.pound-python.org/show/V0lAAsLH91B3lYDTh4Hk/
https://paste.pound-python.org/show/W0GvFFW66qbTnv3HWQbu/
https://paste.pound-python.org/show/CbqbKavz2gZFpWJUB8Gp/

Anything else I can do to help with debugging this?

#### Steps to reproduce
Use koreader for more than 5 minutes.

**Comment by Wonko7** [comment]
It doesn't seem to happen while the kobo is plugged in, or I'm just lucky right now. 
I don't *think* it's a battery issue though, if I recall correctly I was at ~60% when I created those logs.

**Comment by Wonko7** [comment]
The frontlight is off too when it's frozen, if that helps.
I have DUSE_TURBO_LIB = false.

**Comment by WolfBackGR** [comment]
That's strange.
I have no such issues on my H2O and 587 rel.
I use a sleep cover to put my device on suspend mode, but I never came up with a frozen screen on weak up. Not after a few hours of reading.
Re-installing Koreader may resolve this problem, though.

**Comment by Wonko7** [comment]
>  Re-installing Koreader may resolve this problem, though. 
I rm'd .adds/koreader and unzipped the nightly there, I only kept my defaults.persistent.lua, and dictionaries. This was maybe two days ago. Anything else I should have done?

**Comment by WolfBackGR** [comment]
In your case, maybe I follow this procedure:

1. Keep a back-up of your dicts and defaults.persistent.lua.
2. Delete Koreader folder.
3. Download and extract the **583** nightly release.
4. Start Koreader and force it to make a OTA update to **587** release.
5. Add your dicts **ONLY**. (keep the back-up of your defaults.persistent.lua for later use)
6. Take your time and read some.
7. If everything's going fine, then you can modify/add the defaults.persistent.lua file.

I hope those steps would resolve your troubles.

**Comment by Wonko7** [comment]
I didn't even know that koreader could do OTA updates, I'll try that tomorrow and let you know, thanks.

**Comment by KenMaltby** [comment]
The current OTA nightly is 619.  Do you get 587 with the "OTA channel" set to "stable" ?

**Comment by WolfBackGR** [comment]
Ken. I think he's never update the KOR via OTA.
He's just download and extract the latest nightly from GitHub site.
I hope that 619 will works fine with him.

**Comment by Wonko7** [comment]
> Ken, I think he's never update the KOR via OTA.

Yeah, I never bothered with wifi, I'd just update by cp'ing the extracted zip file.

> The current OTA nightly is 619. 

I don't see that one on this page: https://github.com/koreader/koreader/releases is there another place to get it?
Anyway I'll check tomorrow if the OTA updates to 619.

**Comment by WolfBackGR** [comment]
Yes, the 619 is only available on OTA update.

**Comment by KenMaltby** [comment]
The server addresses are listed in the menu item.

http://vislab.bjmu.edu.cn/apps/koreader/ota/  is the one I use to download the latest version, to my PC and sideload the koreader folder to the .adds folder on my AruaHD.  I make some modifications to the download before using it to do the update, therefor I seldom use the OTA.  

To do the download I use the "Save As" function to remove everything except: "koreader-kobo-v2015.11-xxx.gz" (WinRAR and 7-zip, can read .gz, and 7-zip can save using that compression.)  Windows7 Explorer lets you merge the new koreader folder over the old so things like a "defaults.persistent.lua " remain.  

Luck;
Ken

**Comment by Wonko7** [comment]
Wifi was annoying so I gave up, but a manual update to 619 seems to have fixed everything, thanks guys.

**Comment by houqp** [comment]
Sorry for the delay. Automated nitghtly build has been broken for awhile. I have been working on the new build system for the last two weeks. I am almost there, the OTA and nightly build should be back in a week.

@Wonko7 what's the issue with WIFI? Could you let us know so we can fix it?

**Comment by Wonko7** [comment]
Sorry about that, since I closed this I didn't think there'd be interest in this.

> what's the issue with WIFI? Could you let us know so we can fix it?

So I did "scan ap", found my wifi, but the keyboard was too dumbed down (no space bar, no non-alphanum characters) so I let it drop for that night, thinking I'd find a way to configure that later. I tried several times the day after, no APs at all would show with scan ap. 
But I'm guessing this is more a KSM issue than koreader?

Anyway, koreader was never the issue with the freezes, my battery seems to be dead...

**Comment by houqp** [comment]
> So I did "scan ap", found my wifi, but the keyboard was too dumbed down (no space bar, no non-alphanum characters) so I let it drop for that night, thinking I'd find a way to configure that later. I tried several times the day after, no APs at all would show with scan ap. 
But I'm guessing this is more a KSM issue than koreader?

Looks like you are using the WIFI feature from KSM. Give the builtin network management feature in KOReader a try :) It's under the network menu.

**Comment by houqp** [comment]
> Edit: or not a battery issue, but I'm getting the same freezes using nickel after a factory reset. I open a book, it freezes, after a few hours long pressing the power button finally reboots it. And ten minutes after that it freezes again. If anyone knows what the problem could be if it's not the battery, I'm all ears.

You should be able to force a reboot by poking the reset hole on the device. I have never seen this kind of behavior before unfortunately :( Are you using the latest firmware?
