### ISSUE TITLE
Unhighlight is not clickable in dictionary view

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2283]
- KOReader version: up to 74eeffb129241ca9d6b270ae29f953051a0efd8b
- Device: Independent
#### Issue

The 'unhighlight' button is not clickable in dictionary view
#### Steps to reproduce

Long press a word to trigger dictionary view.
Click 'highlight' button to highlight the word.
The 'highlight' text becomes 'unhighlight', but not clickable anymore. i.e. I cannot remove the highlight.

**Comment by houqp** [comment]
Good catch, looks like the only way to remove a highlight is to exit the popup, click the highlighted text and select delete. Given that the delete functionality is already there, it should be a simple fix ;)
