### ISSUE TITLE
FR: Support for natural light on KA1

### ISSUE THREAD

**Issue by agaAdams** [koreader/koreader#2285]
- KOReader version:
- Device: Kobo Aura One

KA1 has a natural light feature which makes reading during nighttime much better on the eyes. I'd very much like to see this feature with KOReader.

Many thanks for coding!

Aga

**Comment by houqp** [comment]
Yay, definitely on my todo list since I just got a aura one :)

**Comment by sopincariu** [comment]
the frontlight KA1 seems dimmer than the same level of brightness in nickel. is there a way to calibrate the front light?

**Comment by houqp** [comment]
should be, but I still haven't had time to play with my aura one yet ;(

**Comment by wvhulle** [comment]
I don't think it's a bad thing that the backlight is lower. It was too high in Nickel (or de slider too sensitive).

Nickel has the following functionalities (besides controlling the white led's)

- The amount of red light follows a sinus with maximum 4 or 5 hours after bedtime.
- Bedtime is set to determine this maxium
- The amount of red light can be manually adjusted as well, this can be seen as changing the amplitude of the sinus. 

Too add it, i think would be necessery to update this amount according to the current time (or 15 min), a bedtime and amplitude user setting. This settings shouln't be accessed too much by user and could be hidden somewhere near the frontlight setting in the koreader menu.

**Comment by houqp** [comment]
Interesting, I have a quick question:

> The amount of red light follows a sinus with a maximum around 4 or 5 hours after bedtime.

Did kobo publicly said they are doing this kind of stuff? Is there any documentation I can refer too?

**Comment by wvhulle** [comment]
Well, it's my experience that the red backlight behaves like this. They call it something like Comfort Light. Maybe I was wrong about the way it behaves.

The theoretical maximum amount of red light is around 4 hours after bedtime, but the sinus is flattened such that the amount of red light is on its maximum before the actual maximum of the sinus. The same goes for the minimum amount of red light that is constantly zero during most of the day. It looks like you could fix the upper and lower bound, such that the maximum amplitude of the sinus results in around 9 hours of maximum amount of red light.

The maximum amount of red light is scaled down as well, such that it's slightly above the current amount of white backlight, which can already be accessed and tuned from within KOreader.

So now we just need to find the setting for the amount of red light and implement the above algorithm with parameters Bedtime and Amount.

**Comment by raimaj** [comment]
Hi guys, I own an Aura One and I'dlove to have this feature on koreader.
Can I help in any way (testing/donation/developing) ?

Thanks

**Comment by houqp** [comment]
We still don't know how to properly control the natural light. @baskerville found the kernel interface, but we are still trying to figure out the value mapping. See previous discussion in https://github.com/koreader/koreader/issues/2321. It would be nice if you can help take a look to see if you can find out the pattern ;)

**Comment by helmus** [comment]
Would love to see this feature as well !
Here is a bounty source: 
https://www.bountysource.com/issues/38378853-fr-support-for-natural-light-on-ka1

**Comment by helmus** [comment]
There are two bounties on this issue right now : 

<a href="https://www.bountysource.com/issues/38378853-fr-support-for-natural-light-on-ka1?utm_source=38378853&utm_medium=shield&utm_campaign=ISSUE_BADGE"><img src="https://api.bountysource.com/badge/issue?issue_id=38378853" /></a>

https://www.bountysource.com/issues/38378853-fr-support-for-natural-light-on-ka1

**Comment by Frenzie** [comment]
At a glance it looks to me like @baskerville may have already figured out all that's necessary in https://github.com/koreader/koreader/issues/2321#issuecomment-315522478 (pinging as a slight nudge ;-) )

**Comment by baskerville** [comment]
I'll suggest the following approach: provide red / green / white sliders and let the user save and load presets.

**Comment by wvhulle** [comment]
Good job, but I don't think it's a good idea to do this with sliders. It should just be an option to let it shift with the time of the day. How's the work going @baskerville?

**Comment by Wonko7** [comment]
I like the sliders, I would like to have direct control over the colors/lighting. You could add the option to have it move with the time of the day, but I wouldn't use it.

**Comment by helmus** [comment]
I think the sliders is also not a bad idea. I would add a 4th preset slider to, to lock in combinations of the other 3 sliders.

**Comment by wvhulle** [comment]
Sliders is a good start. But the whole point of that lights is to shift
during the day. I hope the person doing the backend could figure it out.

Op 7 nov. 2017 5:33 p.m. schreef "helmus" <notifications@github.com>:

**Comment by Gauff** [comment]
I'm looking forward too to enjoy the night shift color :-)

**Comment by AwUnic** [comment]
I would actually prefer sliders over a day shift approach.
Having both options would be the most ideal solution.
Also looking forward to that feature

**Comment by bendtherules** [comment]
Would really like to see this feature being completed. Added a little more bounty.

**Comment by Frenzie** [comment]
@dengste 

A couple of comments from the forum. :-)
https://www.mobileread.com/forums/showthread.php?p=3659530#post3659530

> The warm light works perfectly on my KA1, but the lowest setting for brightness seems to be much brighter now. 

> Trekk, I noticed that too last night. Even at 2% it is very bright.

**Comment by dengste** [comment]
Thanks for letting me know, I've answered in the forum.

**Comment by cramoisi** [comment]
On KA1, when comfort light is more than 50% you can notice the last led (and perhaps the first, or more) stays blue (it doesn't do that with nickel). I'll do a picture at night.

**Comment by dengste** [comment]
@cramoisi: I think I know what you mean, but I can see the same thing on Nickel.

**Comment by cramoisi** [comment]
@dengste yes it's not visible if the light intensity is more than 20% but at 1% (as I always use it) and warmth at more than 50 % its visible on nickel too. (I didn't see it at first because light was on automatic and so never stays at 1%

**Comment by dengste** [comment]
There's now a new widget to configure the parameters for the natural light progression. This should turn up in the next nightly.

**Comment by Frenzie** [comment]
The last piece of this was implemented by @dengste in #3820.
