### ISSUE TITLE
FR - Light level info in lower (mini) status bar

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2288]
@ycrichard 

Now that we have your mod included in koreader, can you also include light level info in lower status bar?

I think this would be also great addition and it would complete your light controlling mod nicely.

Also, in daylight having light on sometimes isn't visible, at least on my device I can't know if light is on or off. With light info in status bar we all can know light status and level.

**Comment by ycrichard** [comment]
I just dropped a PR. Let's hope we can get it through.

**Comment by AlanSP1** [comment]
Well, that's an example of synchronicity. :+1:

**Comment by houqp** [comment]
thanks @ycrichard for the patch, merged :)
