### ISSUE TITLE
Wi-Fi doesn't connect most of the time

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2293]
- KOReader version: 2015.11-654
- Device: Kobo Mini
#### Issue

Problems to connect to the Internet. It happens with the last development version but it has been happening for months, since it was introduced the option to connect to other available Wi-Fi networks.
It doesn't matter if I try to activate the connection through the gear menu / Network / Wi-Fi connection, or throught the pokeball menu / OTA update / Check for update / Do you want to turn on Wi - Fi.
The menu with the available Wi-Fi networks appears with the option "disconnect" besides to my Wi-Fi connection. When I get out of that menu, after waiting some seconds, in some occasions, I get connection, but most of the times I don't get it.
However there is a way to activate Wi-Fi for sure inside KOReader: when the menu to choose Wi-Fi network appears, choose disconnect from my Wi-Fi network, choose it again and introduce my Wi-Fi password (it is 20 characters). Then I get Wi-Fi.
However, if I activate Wi-Fi in Nickel and after that I launch KOReader, Wi-Fi will work in KOReader too.

**Comment by KenMaltby** [comment]
That change had a similar effect on my AuraHD.  What I do now is poke the disconnect, and watch it disconnect.  Then poke the listing for my router again and watch it search and do the authenticating again.  Then the WiFi is connected and available.  (I don't have to enter anything for the authentication, it should be getting it from the WPA supplicant File.)

**Comment by retrue** [comment]
If I try to do that, it prompts me to introduce the password.

**Comment by KenMaltby** [comment]
That makes sense, it is sounding like the "password" isn't being kept/recorded properly.

**Comment by houqp** [comment]
@retrue the wifi issue only happens after you suspend with wifi on right?

The fact that you can't save wifi password is weird. The network information is saved in file `koreader/settings/network.lua`. Could you check to see if that file exists?

**Comment by retrue** [comment]
The Wi-Fi issue happens always. It is not related with suspend.
I use fmon to launch KOReader. If Wi-Fi was activated on Nickel, I have Wi-Fi on KOReader. If it was not and I have to activate Wi-Fi from KOReader, then I need to type the password.
As I told above, I get a list of available connections, with the option to disconnect from my network. But to work, I need to disconnect and type the password.

This is my network.lua file (The password is correct in my file, I have changed it to not post it here the real one).

-- we can read Lua syntax here!
return {
    ["THE_DOC"] = {
        ["password"] = "X123456789XXXXXXXXXX",
        ["ssid"] = "THE_DOC",
        ["flags"] = "[WPA-PSK-TKIP+CCMP][WPS][ESS]"
    }
}

**Comment by houqp** [comment]
You only have one network named THE_DOC right? For testing purpose, could you try change this line https://github.com/koreader/koreader/blob/master/frontend/ui/network/wpa_supplicant.lua#L27?

Change it from

```
if saved_nw and saved_nw.flags == network.flags then
```

to:

```
if saved_nw then
```

**Comment by retrue** [comment]
I know zero about programation and I have never compiled KOReader before. I'll try this weekend to compile it under Linux Mint.

**Comment by houqp** [comment]
@retrue there is no need for compilation. It's just a text file, you can just edit it with a text editor.

I have uploaded a modified version for you. You need to rename the file from `wpa_supplicant.lua.txt` to `wpa_supplicant.lua` before copying into your device. Make sure it's placed under `koreader/frontend/ui/network` directory so it overwrites the original one.

download link:
[wpa_supplicant.lua.txt](https://github.com/koreader/koreader/files/543803/wpa_supplicant.lua.txt)

I added a debug print in my uploaded version, so if it's still not working, it would be very helpful if you can also attach the crash.log file :)

**Comment by retrue** [comment]
Thanks.
Now I think it behaves the way KenMaltby described several posts above. It is not as it should, but it works.
When I connect I get an image like in screenshot 1. I touch outside of that window to close it and Wi-Fi doesn't work. It asks me again if I want to activate Wi-Fi and I get the same image like in screenshot 1 again.
![screenshot 1](https://cloud.githubusercontent.com/assets/18194241/19593748/616d1bf0-9782-11e6-8dc7-7f6bfb66035a.png)
Now, and this is new, if I touch on Disconnect in that window I get screenshot 2, with the option edit. (Before this change in wpa-supplicant.lua I was just prompted to enter my password with the space for password completely blank).
![screenshot 2](https://cloud.githubusercontent.com/assets/18194241/19593667/042d7af2-9782-11e6-9284-ade0c1565491.png)
In screenshot 2, if I touch over THE_DOC it connects and I get screenshot 3 and Wi-Fi works.
![screenshot 3](https://cloud.githubusercontent.com/assets/18194241/19593679/11e0ea80-9782-11e6-88cc-ce6323adb626.png)
And if, in screenshot 2, I touch over edit, I get screenshot 4, touch over connect and I get again screenshot 3 and Wi-Fi works.
![screenshot 4](https://cloud.githubusercontent.com/assets/18194241/19593690/1c4e4ba2-9782-11e6-81d7-045a0942d033.png)

I include the crash.log too
[crash.log.txt](https://github.com/koreader/koreader/files/543947/crash.log.txt)

**Comment by houqp** [comment]
> Now I think it behaves the way KenMaltby described several posts above. It is not as it should, but it works.

Thanks for confirming, I will submit the patch soon.

> When I connect I get an image like in screenshot 1.

Can you elaborate how did you get to screenshot 1? Did you enable wifi in kobo before going into koreader? Did you get to that network list through the Network menu tab?

**Comment by retrue** [comment]
About screenshot 1.
If Wi-Fi is enabled in Nickel when I launch KOReader through fmon, I have Wi-Fi in KOReader without doing anything else. I don't need to activate Wi-Fi because I am already connected.
If Wi-Fi is not enabled in Nickel before launching KOReader and I have to activate Wi-Fi, I always get the image in Screenshot 1. It doesn't matter if I try to activate Wi-Fi through 
- gear menu / Network / Wi-Fi connection / Do you want to turn on Wi - Fi?,
or throught 
- pokeball menu / OTA update / Check for update / Do you want to turn on Wi - Fi?

Instead of getting a behaviour like in Screenshot 3, I always get Screenshot 1.

**Comment by houqp** [comment]
If this is the case, then nickel did not disconnect the reader from the wireless router properly. it must be in a half disconnected state, i.e. it only released the IP address.

However, once the auto reconnect feature is fully implemented, koreader will be smart enough to regrab the IP.

**Comment by retrue** [comment]
But it is weird because I have always Wi-Fi disconnected on Nickel.
I don't disconnect Wi-Fi on Nickel and then I launch KOReader. Wi-Fi is disconnected on Nickel all the time. I start Nickel with Wi-Fi disconnected and I launch KOReader without connecting Nickel, so I don't understand how can be the e-reader in a half disconnected state when it hadn't been in a connected state.
Wi-Fi connected properly on KOReader months ago, before this menu with the networks available was implemented.

**Comment by houqp** [comment]
Now that I think about it, the half connected state is probably caused by KOReader's auto wifi resume feature. Can you try disable it by tapping the `Automatically restore Wi-Fi connection after resume` menu item?

KOReader automatically disables wifi after exit because that's a safety measure required by KSM, which is the preferred way to launch KOReader. I guess for fmon users, we can add another option to disable this behavior.

**Comment by retrue** [comment]
I already did before taking those screenshots. It behaves the same way being enabled or disabled when you are trying to get that first Wi-Fi connection.

**Comment by houqp** [comment]
This is very strange. Exiting KOReader turns of wifi. And if you relaunch koreader without turning on the wifi in nickel, the wifi should remain off assuming you have the auto restore feature turned off. Do you have ssh access to the device to help debug this problem?

**Comment by retrue** [comment]
No, no idea about ssh and how it works.
I can install KSM 8 and see if the problem continues.

**Comment by houqp** [comment]
@retrue, thanks for testing! I think I know what's going on. It's because you saved the wifi setting in nickel before. When koreader tries to enable wifi, it first launches wpa_supplicant, which is the wireless authentication tool for Linux. The tool itself automatically connects to the wifi using the kobo setting (since kobo write the setting to system global). That's why koreader thinks it's already connected to the network, which is indeed the case.

However, connecting/authenticating to the router is only the first step. We also need to obtain an IP address through DHCP protocol. The current logic in the new WIFI manager is to obtain an IP address only after the connection has been established through KOReader's UI. We need to make it smarter so if the device is already authenticated, go straight to obtain an IP.

I will submit a fix for it this weekend.

**Comment by retrue** [comment]
I just checked version 674 and it works as it should.
Thanks  :)
