### ISSUE TITLE
FR - Set Highlight Options -> Disable as a default

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#2294]
Hey.
Highlighting text is nice, but for my use case it is useless, and often gets in the way if I accidentally rest my finger on the screen..

"Highlight Options -> Disable" disables highlighting, which is good. However, unlike many other settings, you cannot set it as default by tapping-and-holding on it. 

Please make it possible to set it as default. Thank you

**Comment by houqp** [comment]
Good catch.

**Comment by houqp** [comment]
Feature implemented in the lastest master. Should be available in the next nightly build.
