### ISSUE TITLE
Android KR crashing

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2295]
- KOReader version: v2015.11-650-gc9ffd44/ 
- Device: Android Marshmallow

It looks like the recent builds of KR for android is trying  to create folders in /data/user/0/org.koreader.launcher and it cant create those folders therefor it crashes during startup.

Going back to the latest file on the github (koreader-nightly-20160823) repo works again. That version creates files in /data/data which is where things are generally on Android.

Btw I do not see an android apk under /download/nightly/v2015.11-654-gb7392f7/

thanks

**Comment by houqp** [comment]
Trying to retrigger the android build right now, but gitlab is down :( Guess we will have to wait until it comes back online.

Do you know what file it's trying to create under `/data/user/0/org.koreader.launcher`? I am not able to reproduce this on my android N phone.

**Comment by houqp** [comment]
weird, according to http://stackoverflow.com/questions/18464495/user-data-directory-in-android-4-3, `/data/user/0` should be a symlink to `/data/data`?

**Comment by gerroon** [comment]
@houqp 

I think it does however KR is having hard time with it as far as I can tell. And that just happens as the first thing that log prints almost, so definetely it is an access issue.

**Comment by houqp** [comment]
That's weird, the permission should be enabled since we did not change that setting for a long time. In android M, you should be able to get a list of permissions enabled for a specific app in the system setting. Could you let me know what's in there?

**Comment by Frenzie** [comment]
@gerroon Are you still experiencing this?

**Comment by gerroon** [comment]
Nope
