### ISSUE TITLE
FR: Statistics - Add reading statistics

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2299]
I made a patch that extend statistics plugin. I added reading statistics.
- Add reading statistics in statistics menu

![reader_2016-oct-22_134414](https://cloud.githubusercontent.com/assets/22982594/19619251/803d6aa2-985a-11e6-9e52-1a3c6601c976.png)

- Add submenu with category:

1. Last week
2. Last month
3. Last year
4. Weekly
5. Monthly

![reader_2016-oct-22_134432](https://cloud.githubusercontent.com/assets/22982594/19619257/c3549770-985a-11e6-953f-e125ebfeab76.png)

When I select last week:

![reader_2016-oct-22_134448](https://cloud.githubusercontent.com/assets/22982594/19619260/df82392a-985a-11e6-88c4-2ee1502e4462.png)

last month:
![reader_2016-oct-22_134502](https://cloud.githubusercontent.com/assets/22982594/19619264/ec2eded0-985a-11e6-9830-48e10f0c1b7a.png)

last year:
![reader_2016-oct-22_134513](https://cloud.githubusercontent.com/assets/22982594/19619266/f61b6c88-985a-11e6-91c4-8e2b00c813e8.png)

weekly:
![reader_2016-oct-22_134533](https://cloud.githubusercontent.com/assets/22982594/19619268/02f21f9c-985b-11e6-94c6-8647febb6216.png)

monthly:
![reader_2016-oct-22_134543](https://cloud.githubusercontent.com/assets/22982594/19619276/3c10e1f0-985b-11e6-91f3-8e2b57cde035.png)

I share patch soon.

**Comment by robert00s** [comment]
fixed in: https://github.com/koreader/koreader/pull/2300

**Comment by AlanSP1** [comment]
Thanks, looks very nice. :+1:

**Comment by seacatwu** [comment]
Great work
Wish it can be a line chart.

**Comment by houqp** [comment]
Yup, the ultimate interface is a page with pretty graphs ;)

**Comment by robert00s** [comment]
Maybe something similar to this :)
![pocketbook_touch lux_3_legimi](https://cloud.githubusercontent.com/assets/22982594/19643625/7ef1667a-99eb-11e6-96a3-81be72913dd7.png)

**Comment by apletnev** [comment]
Looks really nice, but unfortunately we haven't in koreader charts library.

**Comment by houqp** [comment]
Yup, but keep in mind that it's also not that hard to create a simple graphing library within koreader. It's just couple progress bar drawn vertically ;) It's actually easier than drawing a simple circle :)
