### ISSUE TITLE
Status Bar progress bar can no longer be hidden

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#2303]
- KOReader version: v2015.11-654-gb7392f7
- Device: Kobo Aura One
#### Issue

Under [Cog Icon]->Status bar it is possible to change what appears in the status bar. 

However, the Progress bar is enabled by default and toggling it has no effect, it is always shown. This is a regression, as I remember being able to hide it a few months ago.

**Comment by AlanSP1** [comment]
Maybe related with chapter marks? https://github.com/koreader/koreader/issues/2262

Just thinking aloud...

**Comment by houqp** [comment]
@pickx I can't reproduce this on my Aura HD and emulator. I am able to hide the bottom progress bar by tapping on it.

@AlanSP1 do you also have this issue?

**Comment by AlanSP1** [comment]
Yes, I can.

I'm on 622 from your build (you shared on suspend issue topic) if it is a problem. I'm using all options visible at the same time if that is important.

If I tap on status bar and check mark isn't visible, status bar still stays on. But, other things (tested just with battery) react immediately, i.e. appear or disappear per selected status.

It may be solved on latest build if you don't see it.

**Comment by Frenzie** [comment]
Could just be a menu issue? Can't test atm.

**Comment by oldhasbeen** [comment]
with my Aura H2O I need to first untick the progress bar option and then exit and restart koreader. The progress bar is then gone.

**Comment by houqp** [comment]
Now that I reread the reader footer code, it's so bad that I think I am going to rewrite it from scratch >_< This module just went out of control after people kept adding features to it.

**Comment by KenMaltby** [comment]
Since the "Status Bar" menu has grown to two pages perhaps a "Setting may require a restart of KOReader, to show effect" warning could be added to the first page.

**Comment by houqp** [comment]
I am going to make it reload on the fly so no restart is needed ;)
