### ISSUE TITLE
FR - Custom suspended message

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2306]
There is a way to change hard coded suspended message (and I think that it is just that, "suspended") by editing certain file, but it would be great if there would be a way that we can edit it so it stays through updates. I think that some people also might like having some other text than suspended.

Now I need to change some things every time I update koreader. One of them is changing this message, other is asked for here: https://github.com/koreader/koreader/issues/2266

It would be just fine if it is set in defaults.lua file, or within options menu.

**Comment by houqp** [comment]
Have you thought about using an image as screensaver? This is already a supported feature.

**Comment by AlanSP1** [comment]
I tried using ebook covers, this for some reason looked ugly to me and it takes more time in my opinion (didn't do exact timings). Anyway, now I always disable image as screen saver and go for textual message over ebook page. I don't know why, it just seems more logical and informative to me having it that way.

**Comment by KenMaltby** [comment]
![cracked](https://cloud.githubusercontent.com/assets/14007369/19746936/52399b20-9b9e-11e6-885f-81e55e04d705.png)

This is the one I use and have it pointed to in KOReader's settings/defaults.

**Comment by AlanSP1** [comment]
Nice one. :+1: 

A bit scary though. :)

**Comment by houqp** [comment]
@KenMaltby LOL. Someone should submit a patch to show this screen saver during April fool :P

@AlanSP1 I was about to mention using image as custom screen saver. You can disable gook cover and have KOReader always show the image. This way you can be more creative about the screen saver. Does this fit your need better?

**Comment by AlanSP1** [comment]
I'm not sure if rendering of image would be faster than rendering book cover, but it looks a bit slow. And I still would prefer simple text overlay over page text.

If it isn't that a big of a problem, of course.

**Comment by houqp** [comment]
If you are concerned with the speed, then text overlay is the only choice. I am marking this as a low hanging fruit task so other people can help implement it.

**Comment by AlanSP1** [comment]
OK, thank you.

**Comment by AlanSP1** [comment]
@KenMaltby just used your image for powered off screensaver. Looks great and scary. Thank you for image. :+1:

**Comment by KenMaltby** [comment]
I think I origionally  got it from Markismus.
