### ISSUE TITLE
Smalls .mobi images, and not working footnotes

### ISSUE THREAD

**Issue by lordninjamelon** [koreader/koreader#2308]
- KOReader version: v2015.11-622-gfca6176
- Device: Kobo Aura One
#### Issue

I am reading a .mobi book that has images embedded, as well as footnote links. Pressing on footnote link, does nothing, or opens gestures menu.

Also, when viewing .mobi on my computer, I can see tables and images, but when viewing them on KOReader I see a tiny math formula, or a tiny image
#### Steps to reproduce

Just open an .mobi file with images, or linked footnotes

**Comment by houqp** [comment]
Marking this as a bug.

**Comment by Hzj-jie** [comment]
AFAICT, mobi supporting is really weak, have you tried to convert the doc into epub?

**Comment by Frenzie** [comment]
Mobi support is unfortunately pretty terrible and that's unlikely to change anytime soon, so closing for now. As suggested, converting might be the best option.
