### ISSUE TITLE
Question about zoming and Rss status, plus a feature 

### ISSUE THREAD

**Issue by Wacek** [koreader/koreader#2309]
[Question] 
1 I would like to ask about the status of pinch to zoom and RSS features. Do you still plan to implement any of them or maybe you decided to abandon them totally? 
2 What dou you think about implementing "font menu" that Kobo has, (font face, size, weigh slider, margin slider, justification etc plus a live "lorem ipsum" preview that allows to see the combined effect of all of the above). Most of this features are already in so its not much of a priority, but i still think it would be nice to have this menu.

**Comment by houqp** [comment]
> 1 I would like to ask about the status of pinch to zoom and RSS features. Do you still plan to implement any of them or maybe you decided to abandon them totally?

We never abandoned these two ideas. Right now we are mostly focusing on stability issues like memory leak that crashes the reader and battery consumption in suspend mode. I am trying to cut a new stable release. Once that's done, I should I have more time to work on new features. I have many cool ideas in my head, but there is only 24 hours in a day ;) I am also willing to accept patches that implement those features from other people.

> 2 What dou you think about implementing "font menu" that Kobo has, (font face, size, weigh slider, margin slider, justification etc plus a live "lorem ipsum" preview that allows to see the combined effect of all of the above). Most of this features are already in so its not much of a priority, but i still think it would be nice to have this menu.

I think it's a good idea to get quick feedback on setting changes. Again, we are short on resources so I don't when this feature will be worked on :(
