### ISSUE TITLE
Make the scroll mode's page gap height configurable

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2315]
I haven't found a setting in `defaults.lua` that would allow me to configure the height of the horizontal gray band that appear between pages in scroll mode.

I would like to set it to *0*.

(I'm using build *666*.)

**Comment by houqp** [comment]
That setting would be `DOVERLAPPIXELS`, see: https://github.com/koreader/koreader/blob/8813f0f32dfda3042cd05f03a402b077956c3ae7/frontend/apps/reader/modules/readerpaging.lua#L20

Sorry we don't have much resources dedicated to documentation right now :(

I am also planning to get rid of all these global variables and move these settings into the reader.settings.lua file.

**Comment by baskerville** [comment]
Thanks but this is not what I'm looking for: I'm talking about the thin solid gray band that appear (only in scroll mode) between pages.

**Comment by baskerville** [comment]
I found the relevant variable in `readerview.lua`:
```lua
    page_gap = {
        width = Screen:scaleBySize(8),
        height = Screen:scaleBySize(8),
        color = Blitbuffer.COLOR_GREY,
    },
```

**Comment by houqp** [comment]
Oh, LOL. You already found it ;) Feel free to turn that into a configurable option with a patch. I should be able to take a look at it this weekend too.
