### ISSUE TITLE
Side effect of DLANDSCAPE_CLOCKWISE_ROTATION=false

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2316]
If I set `DLANDSCAPE_CLOCKWISE_ROTATION` to `false` (in `defaults.lua`) then the file manager starts (and stays) in landscape mode.

I'm using build *666*.

**Comment by houqp** [comment]
Hmm... I am not able to reproduce this bug. Have you rotated the screen at some point? I also tried rotating the screen in a book and filemanager was restored to portrait mode as expected. Do you the `fm_screen_mode` set in your `reader.settings.lua`?

**Comment by baskerville** [comment]
I can't reproduce neither.

I probably rotated the screen unintentionally.

Although I can't seem to be able to do it on purpose…

I've read this in the wiki:

> Set screen rotation (portrait/landscape):
> Rotate on screen with an angle larger than 15 degrees

But I must have an incorrect conception of the rotate gesture is.
