### ISSUE TITLE
KA1 frontlight not working

### ISSUE THREAD

**Issue by sopincariu** [koreader/koreader#2321]
* KOReader version:
* Device: Kobo Aura One

#### Issue
The frontlight  KA1 is dimmer than Nickel frontlight at the same percentage level

**Comment by baskerville** [comment]
@houqp I have this device, so I might provide useful information if needed.

**Comment by houqp** [comment]
I bought a KA1 couple weeks ago too, but haven't had time to play with it :( I think this should be a simple fix once we have the strace log for when the native reader sets the frontlight level. KA1 probably has a different kernel interface. We just need to figure out what value needs to be written to which file. I probably won't be working on KA1 until I fixed the suspend corruption issue in Kobo. So feel free to give it a shot ;)

**Comment by baskerville** [comment]
I found the frontlight interface: `/sys/class/backlight/lm3630a_led1b`.

**Comment by baskerville** [comment]
And `/sys/class/backlight/lm3630a_led1a` is the interface for the *natural light*.

**Comment by houqp** [comment]
Did you strace the stock reader to figure out what values are passed in to the kernel interface from userspace?

For frontlight level setting, we are using the ioctl interface, which is more portable because it's sysfs path agnostic. See: https://github.com/koreader/koreader-base/blob/master/ffi/kobolight.lua#L28

Here is the kernel source for the ioctl interface: https://github.com/pazos/linux-2.6.35.3-kobo/blob/master/arch/arm/mach-mx5/mx50_ntx_io.c#L1130. However, this source might not be the latest one. @pazos does the kernel source include support for Aura one?

**Comment by baskerville** [comment]
I've used `strace` on the `nickel` process, but unfortunately, `/dev/ntx_io` doesn't appear in the output.

**Comment by baskerville** [comment]
The aforementioned sysfs interfaces appear directly in `libnickel.so` (and strangely there seems to be some embedded C++ code near those occurrences).

That wasn't the case with firmware `3.19.5761`.

I also compared the output of `lsof` on the *Glo HD* and the *Aura ONE*. The main difference is that the `nickel` process opens the following files on the *Aura ONE*:
```
/sys/devices/platform/imx-i2c.1/i2c-1/1-0038/backlight/lm3630a_led1b/brightness
/sys/devices/platform/imx-i2c.1/i2c-1/1-0038/backlight/lm3630a_led1b/bl_power
/sys/devices/platform/imx-i2c.1/i2c-1/1-0038/backlight/lm3630a_led1a/brightness
/sys/devices/platform/imx-i2c.1/i2c-1/1-0038/backlight/lm3630a_led1a/bl_power
/sys/devices/platform/imx-i2c.1/i2c-1/1-0036/backlight/lm3630a_ledb/brightness
/sys/devices/platform/imx-i2c.1/i2c-1/1-0036/backlight/lm3630a_ledb/bl_power
/sys/devices/platform/imx-i2c.1/i2c-1/1-0036/backlight/lm3630a_leda/brightness
/sys/devices/platform/imx-i2c.1/i2c-1/1-0036/backlight/lm3630a_leda/bl_power
```

**Comment by houqp** [comment]
Interesting, I wonder why nickel chooses the sysfs interface over ioctl. I guess this is why percentage from koreader is dimmer. Does the natural light also takes a numerical value?

**Comment by baskerville** [comment]
I can confirm my hypothesis, I've done another `strace` but this time, I've recorded the output of `ls -al /proc/$(pgrep nickel)/fd` beforehand, so I known what the FDs for the brightness and temperature are. And I was able to extract the relevant `write` calls.

Setting the brightness to *100%* is equivalent to writing *205* on `led1b/brightness` and setting the temperature (*natural light*) to *100%* is equivalent to writing *228* on `led1a/brightness`.

Regarding `Kobo eReader.conf`, the mapping between the brightness percentage and `FrontLightLevel` is straighforward, but the mapping between the temperature and `ColorSetting` is slightly less conventional: *0%* maps to *6400* and *100%* maps to *1500* (the scale is linear though: *50%* maps to *4000*).

**Comment by baskerville** [comment]
The mapping between percentages and brightness values is non-linear:
```
  0    0
  1   50
  2   71
  3   85
  4   95
  5  102
 10  125
 13  134
 15  136
 18  144
 20  148
 21  150
 23  153
 25  156
 28  160
 30  162
 33  166
 35  168
 38  171
 40  172
 43  174
 45  176
 48  178
 50  180
 53  182
 55  184
 58  186
 60  187
 63  189
 65  189
 68  191
 70  192
 73  194
 75  194
 78  196
 80  197
 83  198
 85  199
 88  201
 90  201
 93  203
 95  203
 98  204
100  205
```

**Comment by houqp** [comment]
Ha, based on your hypothesis, I found couple percentage mapping table in the kernel:
https://github.com/pazos/linux-2.6.35.3-kobo/blob/master/arch/arm/mach-mx5/mx50_ntx_io.c#L1147

Does nickel do the percentage mapping in the userspace? i.e. does it write 205 instead of 100 directly to sysfs?

**Comment by baskerville** [comment]
Yes it does.

**Comment by baskerville** [comment]
I can't provide a similar mapping for the temperatures: there's no percentage indication on the slider.

But the slider tick marks seem to be spaced out evenly.

In addition, the values depend on the current brightness!

Here's the temperature values for a brightness of about *50%*:
```
0
103
125
138
148
155
161
166
171
174
176
180
185
189
191
194
199
201
```
And for a brightness of *100%*:
```
  0
125
148
162
171
177
184
189
194
198
202
206
211
215
218
221
226
228
```

**Comment by houqp** [comment]
Hmm... If they are doing the mapping in user space, then we either have to reverse engineer nickel or brute force all the possible mappings.

I noticed Kobo also released the GPL source for their aura1 kernel modules: https://github.com/kobolabs/Kobo-Reader/blob/b95297487179ed64c155090ebaa631e76be6ada5/hw/imx6sl-auraonetwo/kernel.tar.bz2

Reading through arch/arm/mach-mx6/mx6sl_ntx_io.c, looks like the `CM_FL_LM3630_TABLE` might be the ioctl command for frontlight color.

I also found a percentage mapping table in drivers/video/backlight/lm3630a_bl.c called `lm3630a_fl_table`. Although I haven't spent much time to verify that this matches with what you found. It will likely not be the same mapping used by nickel.

**Comment by pazos** [comment]
@houqp, @baskerville: What a mess. I bought the KA1 two days ago. The whole lighting thing in koreader is crazy. On lower levels of "normal" light the "natural" light shines in amber.

Can we just write 0 to the natural light until we find a way to write a sane value for it?

**Comment by houqp** [comment]
@pazos sure, feel free to submit a PR

**Comment by pazos** [comment]
> Regarding Kobo eReader.conf, the mapping between the brightness percentage and FrontLightLevel is straighforward, but the mapping between the temperature and ColorSetting is slightly less conventional: 0% maps to 6400 and 100% maps to 1500 (the scale is linear though: 50% maps to 4000).

@baskerville: this makes sense. Is the temperature of the colour (in Kelvin) https://en.wikipedia.org/wiki/Color_temperature. So 0% indeed is leaving the light temperature without colour modification (ie: natural light turned off) and 100% is the maximum amount of red spectrum added to the image. Red is used to neutralize blue, so more frontlight more nature light, as in your tests.

> Hmm... If they are doing the mapping in user space, then we either have to reverse engineer nickel or brute force all the possible mappings.

Need to strace it myself. Unfortunately I had to return my Aura One, it came with magnetic sensor broken. I'm waiting for amazon :⁽

I expect a signed int passed to ntx_io (the one who speaks with netronix coproccesor, via GPIO kernel interface.) 

natural light value seems between 0 and 228. Lower values of natural light seems not perceptible by the eye with the frontlight enabled (the first "step" in baskerville's reads is from 0 to 100 (in both 50% and 100% of "blue light"). So the map is non linear (6400/1500 to 0/228). Lower values of natural light seems only needed when setting the frontlight between 0 and 20..30) because there isn't any blue light to neutralize.

The whole concept of natural light depends on perception, and YMMV

**Comment by baskerville** [comment]
Maybe we could plug directly into *libnickel*:

```
$ objdump -T libnickel.so.1.0.0 | grep -i 'light.*temp'
00777718 g    DF .text	00000010  Base        _ZNK10FrontLight18bedtimeTemperatureEv
00777762 g    DF .text	00000012  Base        _ZN10FrontLight25cancelTemperatureChangingEv
007776f8 g    DF .text	00000010  Base        _ZNK10FrontLight14maxTemperatureEv
00777708 g    DF .text	00000010  Base        _ZNK10FrontLight14minTemperatureEv
007776e8 g    DF .text	00000010  Base        _ZNK10FrontLight11temperatureEv
007776c0 g    DF .text	00000028  Base        _ZN10FrontLight14setTemperatureEibbi
008d5f88 g    DF .text	00000024  Base        _ZN10FrontLight27temperatureChangingFinishedEv
00777c28 g    DF .text	00000008  Base        _ZN25FrontLightPopupController20onTemperatureChangedEi
00777d28 g    DF .text	00000058  Base        _ZN25FrontLightPopupController29onAutoTemperatureStateChangedEb
```
?

Disassembly of `ZN10FrontLight14setTemperatureEibbi`:
```
007776c0 <_ZN10FrontLight14setTemperatureEibbi@@Base>:
  7776c0:	e92d 41f0 	stmdb	sp!, {r4, r5, r6, r7, r8, lr}
  7776c4:	b082      	sub	sp, #8
  7776c6:	af02      	add	r7, sp, #8
  7776c8:	461d      	mov	r5, r3
  7776ca:	4688      	mov	r8, r1
  7776cc:	4616      	mov	r6, r2
  7776ce:	f57c efb0 	blx	4f4630 <_ZN12ChannelMixer14sharedInstanceEv@plt>
  7776d2:	69bc      	ldr	r4, [r7, #24]
  7776d4:	4641      	mov	r1, r8
  7776d6:	6803      	ldr	r3, [r0, #0]
  7776d8:	4632      	mov	r2, r6
  7776da:	9400      	str	r4, [sp, #0]
  7776dc:	6b9c      	ldr	r4, [r3, #56]	; 0x38
  7776de:	462b      	mov	r3, r5
  7776e0:	47a0      	blx	r4
  7776e2:	46bd      	mov	sp, r7
  7776e4:	e8bd 81f0 	ldmia.w	sp!, {r4, r5, r6, r7, r8, pc}
```

And `ZN12ChannelMixer14sharedInstanceEv`:
```
00776210 <_ZN12ChannelMixer14sharedInstanceEv@@Base>:
  776210:	e92d 41f0 	stmdb	sp!, {r4, r5, r6, r7, r8, lr}
  776214:	b082      	sub	sp, #8
  776216:	4c35      	ldr	r4, [pc, #212]	; (7762ec <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xdc>)
  776218:	af00      	add	r7, sp, #0
  77621a:	f57c ea84 	blx	4f2724 <_ZN6Device16getCurrentDeviceEv@plt>
  77621e:	4b34      	ldr	r3, [pc, #208]	; (7762f0 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xe0>)
  776220:	447c      	add	r4, pc
  776222:	6840      	ldr	r0, [r0, #4]
  776224:	58e3      	ldr	r3, [r4, r3]
  776226:	6078      	str	r0, [r7, #4]
  776228:	3308      	adds	r3, #8
  77622a:	603b      	str	r3, [r7, #0]
  77622c:	b108      	cbz	r0, 776232 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x22>
  77622e:	f54d ed98 	blx	4c3d60 <_ZN15QBasicAtomicOpsILi4EE3refIiEEbRT_@plt>
  776232:	4638      	mov	r0, r7
  776234:	f557 e8ec 	blx	4cd410 <_ZNK6Device10isDaylightEv@plt+0x4>
  776238:	b1e0      	cbz	r0, 776274 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x64>
  77623a:	4e2e      	ldr	r6, [pc, #184]	; (7762f4 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xe4>)
  77623c:	447e      	add	r6, pc
  77623e:	6ab3      	ldr	r3, [r6, #40]	; 0x28
  776240:	07dd      	lsls	r5, r3, #31
  776242:	d502      	bpl.n	77624a <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x3a>
  776244:	4c2c      	ldr	r4, [pc, #176]	; (7762f8 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xe8>)
  776246:	447c      	add	r4, pc
  776248:	e048      	b.n	7762dc <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xcc>
  77624a:	f106 0028 	add.w	r0, r6, #40	; 0x28
  77624e:	f574 ec44 	blx	4eaad8 <__cxa_guard_acquire@plt>
  776252:	2800      	cmp	r0, #0
  776254:	d0f6      	beq.n	776244 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x34>
  776256:	4630      	mov	r0, r6
  776258:	f577 ee5e 	blx	4edf18 <_ZN16RGBWChannelMixerC1Ev@plt>
  77625c:	4e27      	ldr	r6, [pc, #156]	; (7762fc <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xec>)
  77625e:	447e      	add	r6, pc
  776260:	f106 0028 	add.w	r0, r6, #40	; 0x28
  776264:	f57a ea12 	blx	4f068c <__cxa_guard_release@plt>
  776268:	4b25      	ldr	r3, [pc, #148]	; (776300 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xf0>)
  77626a:	4630      	mov	r0, r6
  77626c:	4a25      	ldr	r2, [pc, #148]	; (776304 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xf4>)
  77626e:	58e1      	ldr	r1, [r4, r3]
  776270:	447a      	add	r2, pc
  776272:	e020      	b.n	7762b6 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xa6>
  776274:	4e24      	ldr	r6, [pc, #144]	; (776308 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xf8>)
  776276:	447e      	add	r6, pc
  776278:	6af1      	ldr	r1, [r6, #44]	; 0x2c
  77627a:	f011 0801 	ands.w	r8, r1, #1
  77627e:	d003      	beq.n	776288 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x78>
  776280:	4c22      	ldr	r4, [pc, #136]	; (77630c <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xfc>)
  776282:	447c      	add	r4, pc
  776284:	3414      	adds	r4, #20
  776286:	e029      	b.n	7762dc <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xcc>
  776288:	f106 002c 	add.w	r0, r6, #44	; 0x2c
  77628c:	f574 ec24 	blx	4eaad8 <__cxa_guard_acquire@plt>
  776290:	2800      	cmp	r0, #0
  776292:	d0f5      	beq.n	776280 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x70>
  776294:	f106 0014 	add.w	r0, r6, #20
  776298:	4641      	mov	r1, r8
  77629a:	f576 ef52 	blx	4ed140 <_ZN12ChannelMixerC1EP7QObject@plt>
  77629e:	4e1c      	ldr	r6, [pc, #112]	; (776310 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x100>)
  7762a0:	447e      	add	r6, pc
  7762a2:	f106 002c 	add.w	r0, r6, #44	; 0x2c
  7762a6:	3614      	adds	r6, #20
  7762a8:	f57a e9f0 	blx	4f068c <__cxa_guard_release@plt>
  7762ac:	4b19      	ldr	r3, [pc, #100]	; (776314 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x104>)
  7762ae:	4630      	mov	r0, r6
  7762b0:	4a19      	ldr	r2, [pc, #100]	; (776318 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x108>)
  7762b2:	58e1      	ldr	r1, [r4, r3]
  7762b4:	447a      	add	r2, pc
  7762b6:	f580 eb22 	blx	4f68fc <__aeabi_atexit@plt+0x4>
  7762ba:	4634      	mov	r4, r6
  7762bc:	e00e      	b.n	7762dc <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xcc>
  7762be:	4817      	ldr	r0, [pc, #92]	; (77631c <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x10c>)
  7762c0:	4478      	add	r0, pc
  7762c2:	3028      	adds	r0, #40	; 0x28
  7762c4:	e002      	b.n	7762cc <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xbc>
  7762c6:	4816      	ldr	r0, [pc, #88]	; (776320 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0x110>)
  7762c8:	4478      	add	r0, pc
  7762ca:	302c      	adds	r0, #44	; 0x2c
  7762cc:	f555 eeb6 	blx	4cc03c <__cxa_guard_abort@plt>
  7762d0:	e7ff      	b.n	7762d2 <_ZN12ChannelMixer14sharedInstanceEv@@Base+0xc2>
  7762d2:	4638      	mov	r0, r7
  7762d4:	f56f ef36 	blx	4e6144 <_ZN6DeviceD1Ev@plt>
  7762d8:	f565 eca2 	blx	4dbc20 <__cxa_end_cleanup@plt>
  7762dc:	4638      	mov	r0, r7
  7762de:	f56f ef32 	blx	4e6144 <_ZN6DeviceD1Ev@plt>
  7762e2:	4620      	mov	r0, r4
  7762e4:	3708      	adds	r7, #8
  7762e6:	46bd      	mov	sp, r7
  7762e8:	e8bd 81f0 	ldmia.w	sp!, {r4, r5, r6, r7, r8, pc}
  7762ec:	9e1c      	ldr	r6, [sp, #112]	; 0x70
  7762ee:	0044      	lsls	r4, r0, #1
  7762f0:	9450      	str	r4, [sp, #320]	; 0x140
  7762f2:	0001      	movs	r1, r0
  7762f4:	ad0c      	add	r5, sp, #48	; 0x30
  7762f6:	0048      	lsls	r0, r1, #1
  7762f8:	ad02      	add	r5, sp, #8
  7762fa:	0048      	lsls	r0, r1, #1
  7762fc:	acea      	add	r4, sp, #936	; 0x3a8
  7762fe:	0048      	lsls	r0, r1, #1
  776300:	db64      	blt.n	7763cc <_ZN12ChannelMixer24makeTemperatureAnimationEii@@Base+0x4c>
  776302:	0001      	movs	r1, r0
  776304:	b4a8      	push	{r3, r5, r7}
  776306:	0046      	lsls	r6, r0, #1
  776308:	acd2      	add	r4, sp, #840	; 0x348
  77630a:	0048      	lsls	r0, r1, #1
  77630c:	acc6      	add	r4, sp, #792	; 0x318
  77630e:	0048      	lsls	r0, r1, #1
  776310:	aca8      	add	r4, sp, #672	; 0x2a0
  776312:	0048      	lsls	r0, r1, #1
  776314:	096c      	lsrs	r4, r5, #5
  776316:	0002      	movs	r2, r0
  776318:	b464      	push	{r2, r5, r6}
  77631a:	0046      	lsls	r6, r0, #1
  77631c:	ac88      	add	r4, sp, #544	; 0x220
  77631e:	0048      	lsls	r0, r1, #1
  776320:	ac80      	add	r4, sp, #512	; 0x200
  776322:	0048      	lsls	r0, r1, #1
```

 I can't cross compile *ltrace*: is that expected?

**Comment by pazos** [comment]
@baskerville: http://stackoverflow.com/questions/4597205/omap-building-and-installing-ltrace

I didn't try it myself :)

I have a new KA1 to test!. First thing I'm going to do is to upgrade the kernel sources for the device to github. The sources that @houqp links doesn't contain any mark6 support (nor mark5/mark3)

I'm reading the kernel sources now. It seems that the natural/confort light are, in fact, RGB leds

**Comment by pazos** [comment]
and [here](https://github.com/pazos/linux-3.0.35-kobo/blob/master/arch/arm/mach-mx6/mx6sl_ntx_io.c#L233:L572) is the devil.

**Comment by ebrahimpak** [comment]
Hi everybody. Had you any success with developing the Natural Light?

**Comment by pazos** [comment]
@ebrahimpak: not yet :(

All the magic seems to happen in userspace, so having the kernel sources doesn't help here.

Differences between how nickel store light values and what values are really passed to the kernel can be displayed with this script

```
#!/bin/sh                                                                                                                         
fl=`cat /mnt/onboard/.kobo/Kobo/Kobo\ eReader.conf | grep FrontLightLevel | cut -f2 -d "="`                                       
nl=`cat /mnt/onboard/.kobo/Kobo/Kobo\ eReader.conf | grep ColorSetting | cut -f2 -d "="`                                          
fl_sysfs=`cat /sys/devices/platform/imx-i2c.1/i2c-1/1-0038/backlight/lm3630a_led1b/brightness`                                    
nl_sysfs=`cat /sys/devices/platform/imx-i2c.1/i2c-1/1-0038/backlight/lm3630a_led1a/brightness`                                    
echo "nickel-> light: ${fl}, color: ${nl}"                                                                                        
echo "sysfs->  light: ${fl_sysfs}, color: ${nl_sysfs}"
```

**Comment by baskerville** [comment]
The `bl_power` files are also important.
Here's the output of `lsof | grep backlight | cut -f 3- | xargs cat` with a brightness of 57 % and a yellowness of about 66 %:
```
141
31
189
31
143
31
0
0
```
If the `brightness` file contains `0`, then `bl_power` contains `0`, otherwise `31`.

It appears that the yellow light is produced by combining the right amount of purple (`led1a`) and green (`ledb`).

**Comment by baskerville** [comment]
Here's a few tables constructed using the output of `lsof | grep backlight | cut -f 3- | sed -n 'p;n' | head -n 3 | xargs cat`. The brightness slider is fixed and the temperature slider moves from 0 to 100 % by steps of about 4.54 %. The values given are for the white, red and green lights.
For each table, the brightness is from left to right, 25, 50, 75 %.

```
 W   R   G	 W   R   G	 W   R   G
-----------	-----------	-----------
156   0   0	180   0   0	194   0   0
154  84  28	177 104  53	192 117  66
152  99  47	176 120  70	190 133  85
150 109  58	174 131  81	189 144  96
149 117  66	173 139  91	188 152 105
146 125  75	170 148 101	185 162 115
144 131  81	168 153 107	182 167 121
142 135  87	166 158 111	180 171 126
140 139  91	164 162 115	178 174 131
136 144  96	161 167 121	174 178 136
134 146 100	158 170 125	172 182 139
132 150 103	155 173 127	169 185 143
128 152 105	152 174 131	166 188 146
123 155 108	147 177 135	161 191 150
120 158 111	143 179 137	157 194 152
116 160 112	136 182 138	153 197 153
111 164 111	134 186 136	148 201 152
103 167 112	125 189 138	136 204 153
 95 169 114	118 191 140	132 206 155
 86 170 115	108 193 142	121 208 157
 72 172 117	 95 194 144	108 210 159
 31 174 113	 51 199 139	 63 215 155
  0 176 111	  0 201 137	  0 217 152
```

**Comment by baskerville** [comment]
I finally came up with [a formula](https://github.com/baskerville/plato/blob/master/src/frontlight/natural.rs#L87)!

**Comment by Frenzie** [comment]
Hooray! Btw, if you press <kbd>y</kbd> in the source view then you get a link with a commit hash [like this](https://github.com/baskerville/plato/blob/c025cebad65bbb4fa2bca88b9085e68da2dbb689/src/frontlight/natural.rs#L87) that'll always point to the right line even in the future. ;-)

Would you mind explaining the specifics? Is this related to hardware differences with different LEDs having different intensities?

**Comment by baskerville** [comment]
### White

```rust
let white = 80.0 * i * (1.0 - w).sqrt();
```
The maximum value (80 % of the hardware maximum value) comes from *Nickel*.

*Nickel*'s implementation jumps more quickly to the high white values: this is a personal choice not to do so, I like to have more choice in the lower registers.

We need to decrease the white light when the warmth increases (the white light makes the colored lights fade away). *Nickel* might not do this properly, because almost two thirds of its warmth slider doesn't yield any warmth.

Ideally, increasing the warmth shouldn't have any effect on the perceived illumination level.

### Green

```rust
let green = 64.0 * (w * i).sqrt();
```
The green light jumps quickly, because the white light initially prevents it from shining through.

### Red

```rust
let red = green + 20.0 + 7.0 * (1.0 - green / 64.0) + w * 4.0;
```

The green light is stronger than the red light in the lower values. We counterbalance the effect with `+ 7.0 * (1.0 - green / 64.0)`. Removing `+ w * 4.0`, would result in a constant yellow hue.

**Comment by dengste** [comment]
Just bought a Aura One, and if no one is currently working on this (especially @baskerville) I'd give it a shot, but I don't want to steal anyone's thunder here. I've played around with the sysfs interface and the values @baskerville figured out and this seems to be working nicely so far.

**Comment by baskerville** [comment]
@dengste Go ahead.

**Comment by dengste** [comment]
OK, I've extended the Kobolight plugin so that you can swipe on the right border to inc/decrease the warmth value. This is working nicely so far, I just need to clean this stuff a bit more before submitting it, but that hopefully shouldn't take long.

**Comment by edluedlu** [comment]
Hey dengste, 
will it be like Nickel has, Ambient light sensor? or you have to operate it manually

**Comment by dengste** [comment]
BTW, I'm using a different formula now. The white/red/green levels are roughly linearly dependent on the 4th root of the brightness and warmth value (both in [0,100]). I've fitted the following:

    local white = whiteGain * math.pow(brightness, 0.25) * math.pow(100 - warmth, 0.25) + whiteOffset
    local red = redGain * math.pow(brightness, 0.25) * math.pow(warmth, 0.25) + redOffset
    local green = greenGain * math.pow(brightness, 0.25) * math.pow(warmth, 0.25) + greenOffset

(The results must still be limited to [0,255], of course).

Currently I'm using whiteGain=redGain=greenGain=25, whiteOffset=-25,redOffset=0 and greenOffset=-65. For me, this is close enough to Nickel's behavior, and IMO those Gain/Offset parameters are easier to understand and hence easier to tune to one's liking.

**Comment by Frenzie** [comment]
Sounds good to me (he said not owning a One).

**Comment by baskerville** [comment]
@dengste I'm eager to try this formula!

Don't forget that, since `brightness >= 0 && warmth >= 0`, `math.pow(brightness, 0.25) * math.pow(warmth, 0.25)` can be written as `math.pow(brightness * warmth, 0.25)`.

**Comment by dengste** [comment]
I think this can be closed. Frontlight should have now similar brightness as Nickels' by default (but can be configured to be even brighter or less bright).

**Comment by Frenzie** [comment]
Thanks @dengste!
