### ISSUE TITLE
clock displays without prompting when reading pdf files in top right corner

### ISSUE THREAD

**Issue by thebeesshoulders** [koreader/koreader#2323]
* KOReader version: latest
* Device: PW3

#### Issue
when reading any pdf file, the time will show up in the top right corner of the screen after about a minute. I can't find an option to disable it
#### Steps to reproduce
read a pdf file through koreader

**Comment by houqp** [comment]
I just tested http://build.koreader.rocks/download/nightly/v2015.11-674-g75f96c5/koreader-kindle-legacy-arm-kindle-linux-gnueabi-v2015.11-674-g75f96c5.zip on my kindle3 and I don't have this issue. Could you take a photo to demonstrate it?

**Comment by houqp** [comment]
Also what's your kindle firmware version? I am using a really old version right because I never updates the native system.

**Comment by Eduardomb22** [comment]
It is fine here. No clock boring me. Kindle pw3 with 5.6.5

**Comment by thebeesshoulders** [comment]
hey folks, sorry for the reply. here is a picture. firmware is 5.7.4
![img_1545](https://cloud.githubusercontent.com/assets/23328673/20204008/f1d2097c-a799-11e6-837c-383430d91825.jpg)

**Comment by houqp** [comment]
I am pretty sure this is the clock from the native system. Are you using KUAL? There should be an option to kill the native system before launching koreader. Can you verify my theory with that?

**Comment by aconicq** [comment]
Can confirm that it is the clock (and wifi symbol on my setup) from the native system. Opening Koreader with framework disabled does stop this from happening (I opened an epub).

Is there a way to fix this without closing the native framework?

**Comment by houqp** [comment]
It does pause the native framework for older k3 firmwares. Looks like you probably have a new firmware that no one has tested before. Do you have ssh access?

**Comment by aconicq** [comment]
yep to ssh. What to do to test?

**Comment by houqp** [comment]
I am interested in what native system is running when koreader is started. Can you open koreader then paste the result of `ps aux` here?

**Comment by houqp** [comment]
You can try manually send stop signal to those running processes to find out which one is drawing the clock using `killall -stop PROCESS_NAME`, like what we do with `cvm`: https://github.com/koreader/koreader/blob/master/platform/kindle/koreader.sh#L237

**Comment by aconicq** [comment]
As requested, here is the ps aux for when the symbols had appeared in koreader.

[root@kindle root]# ps aux
Unknown HZ value! (4) Assume 100.
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.6   3228  1712 ?        Ss   Nov10   0:02 /sbin/init.exe
root         2  0.0  0.0      0     0 ?        S    Nov10   0:00 [kthreadd]
root         3  0.0  0.0      0     0 ?        S    Nov10   0:00 [ksoftirqd/0]
root         6  0.0  0.0      0     0 ?        S    Nov10   0:02 [watchdog/0]
root         7  0.0  0.0      0     0 ?        S<   Nov10   0:00 [khelper]
root       168  0.0  0.0      0     0 ?        S    Nov10   0:03 [sync_supers]
root       170  0.0  0.0      0     0 ?        S    Nov10   0:00 [bdi-default]
root       172  0.0  0.0      0     0 ?        S<   Nov10   0:00 [kblockd]
root       201  0.0  0.0      0     0 ?        S<   Nov10   0:00 [imx6q-ecspi.0]
root       208  0.0  0.0      0     0 ?        S    Nov10   0:00 [khubd]
root       219  0.0  0.0      0     0 ?        S    Nov10   0:00 [irq/372-max7769]
root       288  0.0  0.0      0     0 ?        S    Nov10   0:00 [irq/301-max7769]
root       401  0.0  0.0      0     0 ?        S<   Nov10   0:00 [rpciod]
root       418  0.0  0.0      0     0 ?        S    Nov10   0:01 [khungtaskd]
root       423  0.0  0.0      0     0 ?        S    Nov10   0:02 [kswapd0]
root       424  0.0  0.0      0     0 ?        SN   Nov10   0:00 [ksmd]
root       483  0.0  0.0      0     0 ?        S    Nov10   0:00 [fsnotify_mark]
root       493  0.0  0.0      0     0 ?        S<   Nov10   0:00 [nfsiod]
root       496  0.0  0.0      0     0 ?        S<   Nov10   0:00 [crypto]
root       632  0.0  0.0      0     0 ?        S    Nov10   0:24 [mmcqd/0]
root       633  0.0  0.0      0     0 ?        S    Nov10   0:00 [mmcqd/0boot0]
root       634  0.0  0.0      0     0 ?        S    Nov10   0:00 [mmcqd/0boot1]
root       638  0.0  0.0      0     0 ?        S<   Nov10   0:00 [EPDC Submit]
root       639  0.0  0.0      0     0 ?        S    Nov10   0:18 [irq/129-fb_dma]
root       645  0.0  0.0      0     0 ?        S    Nov10   0:00 [kjournald]
root       783  0.0  0.2   2252   656 ?        S<s  Nov10   0:11 udevd --daemon
root       875  0.0  0.2   2812   752 ?        Ss   Nov10   0:03 crond -f -c /etc/crontab
root       888  0.0  0.2   2816   636 ttymxc0  Ss+  Nov10   0:00 getty -L 115200 /dev/ttymxc0
root       908  0.0  0.8   3668  2208 ?        Ss   Nov10   1:40 syslog-ng
root       924  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop2]
root       933  0.0  0.0      0     0 ?        S<   Nov10   0:01 [loop3]
root       942  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop4]
root       951  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop5]
root       960  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop6]
root       969  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop7]
root       987  0.0  0.0      0     0 ?        S<   Nov10   0:00 [otg_switch]
root      1028  0.0  0.0      0     0 ?        S    Nov10   0:01 [kjournald]
root      1202  0.0  0.0      0     0 ?        S<   Nov10   0:00 [Cyttsp4 startup]
root      1203  0.0  0.0      0     0 ?        S    Nov10   0:20 [irq/355-main_tt]
root      1981  0.0  0.0      0     0 ?        S<   Nov10   0:05 [loop0]
root      1999  0.0  0.6 104100  1664 ?        Ssl  Nov10   1:23 fsp /mnt/base-us /mnt/us -o rw,nosuid,nodev,noatime,allow_other,umask=0,uid=0,gid=0,max_write=65536,max_readahead=65536,nonempty
root      2396  0.0  0.0      0     0 ?        S    Nov10   0:07 [file-storage-ga]
92        2548  0.0  0.6   3536  1712 ?        Ss   Nov10   0:36 dbus-daemon --system --nofork
root      2592  0.0  1.2  49896  3240 ?        Ssl  Nov10   0:26 cmd -f
root      2596  0.0  0.6   8792  1692 ?        SNsl Nov10   0:00 dynconfig
root      2600  0.0  1.3  27200  3324 ?        SNsl Nov10   0:00 archive
root      2603  0.0  0.9  24808  2296 ?        Ssl  Nov10   0:00 volumd -f -d /dev/mmcblk0p4
root      2604  0.0  1.1  24860  2948 ?        Ssl  Nov10   0:11 rcm
root      2606  0.0  1.3  25444  3504 ?        SNsl Nov10   0:00 /usr/bin/otav3
root      2609  0.0  0.2   1844   580 ?        Ss   Nov10   0:00 stackdumpd
root      2611  0.0  1.3  33804  3416 ?        Ssl  Nov10   1:12 powerd -f
root      2614  0.0  1.0  26348  2760 ?        Ssl  Nov10   0:09 dpmd
root      2616  0.0  1.1  27212  2884 ?        S<sl Nov10   0:25 appmgrd
root      2620  0.0  0.7   9312  1816 ?        SNsl Nov10   0:00 /usr/bin/otaupd
root      2625  0.0  2.2  51336  5784 ?        Ssl  Nov10   0:07 tmd -f
root      2628  0.0  0.8  40904  2216 ?        Ssl  Nov10   0:00 deviced -f
root      2654  0.0  0.9   9476  2500 ?        Ssl  Nov10   0:00 lipc-daemon -f -p /etc/lipc-daemon-props.conf -e /etc/lipc-daemon-events.conf
root      2676  0.0  1.3  60676  3412 ?        Ssl  Nov10   0:12 wifid -f
9000      2685  0.0  0.2   2812   588 ?        Ss   Nov10   0:00 sh -c phd -f 2>> /tmp/phd.err
9000      2706  0.0  1.1  35656  2868 ?        Sl   Nov10   0:04 phd -f
root      3514  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop8]
root      3560  0.0  0.0      0     0 ?        S<   Nov10   0:00 [loop9]
root      4241  0.0  0.2   2248   700 ?        S<   Nov17   0:00 udevd --daemon
root      4949  0.0  0.6   7548  1564 ?        Ssl  Nov17   0:00 lxinit blanket -t splash screensaver langpicker blankwindow
root      4959  0.0  2.9  14172  7508 ?        S<l  Nov17   0:07 Xorg -nolisten tcp +bs -ardelay 0 -arinterval 0
root      4965  0.0  2.9  36820  7484 ?        Sl   Nov17   0:02 awesome
root      4966  0.0  1.9  34920  4912 ?        Sl   Nov17   0:03 blanket -t splash screensaver langpicker blankwindow
root      5108  0.0  3.2  40260  8344 ?        Ssl  Nov17   0:00 kb
root      5109  0.0  0.8  25908  2228 ?        Ssl  Nov17   0:00 contentpackd -f
root      5298  0.0  2.0  30380  5148 ?        Ssl  Nov10   0:17 todo
9000      5466  0.0  4.5  82140 11492 ?        S<sl Nov17   0:00 webreader
root     21817  0.0  0.3   2816   808 ?        Ss   Nov23   0:00 /bin/sh /etc/upstart/framework
9000     22232  0.0 30.2 192280 76984 ?        Sl   Nov23   2:11 /usr/java/bin/cvm -minimal -Xmx23m -XX:MaxNewSize=3m -XX:SurvivorRatio=2 -XX:TargetSurvivorRatio=80 -Xss100k -XX:ReservedCodeCacheSize=2m -XX:CompileThreshold=8000 -XX:Code
9000     22233  0.0  0.5   4580  1368 ?        S    Nov23   0:00 logger -p local2.debug
root     22544  0.0  1.2  26552  3116 ?        Ssl  Nov23   0:00 dmld
root     22547  0.0  1.0  33112  2616 ?        Ssl  Nov23   0:10 pmond -f
root     22549  0.0  0.3   2816   784 ?        Ss   Nov23   0:00 /bin/sh -e /proc/self/fd/11
9000     22552  0.0  2.7  49204  7128 ?        S<sl Nov23   0:00 kfxreader -l
root     22554  0.0  0.2   2812   624 ?        Ss   Nov23   0:00 /bin/sh -e /proc/self/fd/11
9000     22586  0.0  1.3   9924  3320 ?        Sl   Nov23   0:24 scanner
9000     22676  0.0  5.1  84100 13220 ?        Sl   Nov23   0:00 /usr/bin/mesquite -d com.lab126.stored
root     22922  0.0  0.2   2812   652 ?        Ss   Nov23   0:00 /bin/sh -e /proc/self/fd/10
9000     22930  0.0  3.2  77620  8304 ?        Sl   Nov23   0:00 pillowd -f
root     26124  0.0  0.0      0     0 ?        S    02:48   0:00 [kworker/0:1]
root     26135  0.0  0.0      0     0 ?        S    02:59   0:00 [kworker/0:2]
root     26136  0.0  0.0      0     0 ?        S    02:59   0:00 [flush-7:0]
root     26137  0.0  0.0      0     0 ?        S    02:59   0:00 [flush-179:0]
root     27022  0.0  0.0      0     0 ?        S    03:01   0:00 [kworker/u:5]
root     27023  0.0  0.0      0     0 ?        S    03:01   0:00 [kworker/u:6]
root     27024  0.0  0.0      0     0 ?        S    03:01   0:00 [kworker/u:7]
root     27026  0.0  0.0      0     0 ?        S    12:50   0:00 [ksdioirqd/mmc1]
root     27063  0.0  0.1   2812   264 ?        Ss   12:50   0:00 udhcpc -R -n -S 908 -p /var/run/udhcpc.wlan0.pid -i wlan0
root     27088  0.1  0.0      0     0 ?        S    12:50   0:00 [kworker/0:3]
root     27147  0.1  0.9   8040  2304 ?        SNs  12:52   0:00 sshd: root@pts/0
root     27151  0.0  0.2   2816   744 pts/0    SNs  12:52   0:00 -sh
root     27196  0.0  0.2   2816   744 ?        SN   12:57   0:00 /bin/sh /mnt/us/koreader/koreader.sh
root     27222 13.7  7.8  83536 19924 ?        SNl  12:57   0:04 ./luajit ./reader.lua
root     27225  0.0  0.3  15724   820 ?        SN   12:57   0:00 ./luajit ./reader.lua
root     27226  0.0  0.5   6208  1296 ?        SNl  12:57   0:00 lipc-wait-event -m -s 0 com.lab126.powerd goingToScreenSaver outOfScreenSaver charging notCharging
root     27235  0.0  0.4   4816  1164 pts/0    RN+  12:57   0:00 ps aux
root     27308  0.0  0.0      0     0 ?        S<   Nov16   0:00 [cfg80211]
root     27315  0.0  0.0      0     0 ?        S<   Nov16   0:00 [ath6kl]
root     27316  0.0  0.0      0     0 ?        S<   Nov16   0:00 [htc_rx]
root     27328  0.0  0.2   2248   700 ?        S<   Nov16   0:05 udevd --daemon
root     27341  0.0  0.7   4920  1972 ?        Ss   Nov16   0:05 wpa_supplicant -t -c /etc/wpa_supplicant.conf -i wlan0 -d -s -D nl80211
root     30741  0.0  0.3   5480   832 ?        SNs  Nov16   0:00 /usr/sbin/sshd

**Comment by aconicq** [comment]
I'm finding it hard to replicate the issue now. Opening the KUAL menu for koreader and starting without the framework stops the issue. But it doesn't always happen when the framework is not stopped.

What hasn't been mentioned is that the symbols show by themselves without a screen refresh being activated. i.e. without touching the kindle, the symbols can just appear after a certain amount of time.

**Comment by houqp** [comment]
Looks like all the native system components are not stopped, which is weird because it should be handled by the kroeader.sh script. The native system will automatically refresh the clock widget in the background even if you are not issuing a screen refresh command. Can you try running the following two commands and see if it stops the clock refresh?

```
killall -stop cvm
killall -stop awesome
```

**Comment by NiLuJe** [comment]
Should be fixed since #3955
