### ISSUE TITLE
Make the "powered off" state customizable

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2327]
I'm using the `screensaver_folder` setting to display a custom image for the *suspended* state.

Could there be something similar the *powered off* state?

And could there be a setting for disabling the confirmation dialog?

(I've never unintentionally pressed the power button for 3 seconds, so I'm wondering if the confirmation dialog really makes sense…)

**Comment by KenMaltby** [comment]
For what device?  For Kobo devices, where KSM is used, you can make your own Power Off html page/image, for its power off option.

**Comment by baskerville** [comment]
I have a Kobo device, but I'm launching *koreader* via *kfmon*.

**Comment by houqp** [comment]
This one should be easy, just do the same thing as what's done for screen saver around https://github.com/koreader/koreader/blob/master/frontend/ui/uimanager.lua#L70
