### ISSUE TITLE
Wikipedia button

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2328]
* KOReader version: ALL
* Device: ALL

#### Issue
Wikipedia button is always active even after search in Wikipedia.

![1](https://cloud.githubusercontent.com/assets/22982594/20173173/7b0c4214-a738-11e6-97f7-c706bdcce096.png)
 

#### Steps to reproduce
Long press to any word -> Press Wikipedia button in search widget -> Wikipedia button is still active.
I think it should be disabled to prevent opening next window with the same content.
Like that:

![3](https://cloud.githubusercontent.com/assets/22982594/20173315/096132b8-a739-11e6-94f8-b42fa7d1c1d3.png)

**Comment by houqp** [comment]
I agree, marking it as a bug.
