### ISSUE TITLE
Add multitouch gesture for going up in the directory tree

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2329]
I think it should be possible, when using the file manager, to directly go to the parent directory, whatever the page.

Potential solutions:
- Wire a two-finger-swipe-upward touch gesture to the relevant action.
- Create an icon area under *FileManager* that would provide the required functionality.

**Comment by KenMaltby** [comment]
The "../" goes to the parent directory, of the one you are in.  You find that at the top of page one of the directory that you are in.  You can go to the first page of the directory that you are in by poking the "<<" at the bottom of any page.

**Comment by Hzj-jie** [comment]
I think most of the e-ink devices are single-touch. Am I wrong?

**Comment by baskerville** [comment]
@KenMaltby Thanks, but, as I said in my original message, I don't want to have to go to page 1 to be able to go to the parent directory: it seems like an unnecessary indirection to me.

@Hzj-jie You might be right, but *koreader* already provides multi-touch gestures for showing the *bookmarks* and *table of contents* windows.

**Comment by houqp** [comment]
Most of the newer generation ereaders should have multi-touch support in the hardware level. And KOReader does leverage multi-touch support in those devcies, see: https://github.com/koreader/koreader/blob/master/frontend/device/gesturedetector.lua

**Comment by robert00s** [comment]
This is done in #4240. You can use Gesture manager to going up in the directory tree
