### ISSUE TITLE
Error while logging in to Evernote

### ISSUE THREAD

**Issue by agaAdams** [koreader/koreader#2332]
* KOReader version:
* Device: KA1

#### Issue
Logging in to Evernote, I get the following error:
```
An error occurred while logging in:
plugins/evernote.koplugin/EvernoteOAuth.lua:210: closed
```

I have a basic Evernote account. No devices are associated with this account yet.

#### Steps to reproduce

**Comment by houqp** [comment]
Did the evernote plugin ever work for you before?

**Comment by agaAdams** [comment]
I just tried it out the first time.
