### ISSUE TITLE
Add search engines other than Wikipedia

### ISSUE THREAD

**Issue by checcousero** [koreader/koreader#2345]
Kobo GLO HD user here. In my opinion, a very useful function that KOReader lacks is the possibility to search a word in search engines other than Wikipedia (for example WordReference, Google, etc.).
The ideal would be to be able to specify a prefix URL, for example: http://www.wordreference.com/enit/
and to see a new corresponding entry in the menu that appears when you select a word.
Is this possible?

**Comment by Frenzie** [comment]
The easiest way would probably be to use APIs such as
http://www.wordreference.com/docs/api.aspx

**Comment by checcousero** [comment]
From the API URL: 
"Due to abuse of the API, it is no longer available. Current users can continue to use it, but no new users are being accepted. Sorry for the inconvenience."
:'(

A most difficult but powerful approach would be to use some lightweight webpage rendered (a little browser, similar to that used by the default Kobo reader to search in Google and Wikipedia).

**Comment by Frenzie** [comment]
I wouldn't call QtWebKit lightweight, exactly. =P

Something like that would be cool for those of us with more memory (say
512MB+), and possibly also necessary for #2333. But like I said there,
nothing I've got time for. =)

**Comment by checcousero** [comment]
Whaaaaaaaaat? 512MB???? :O 
Forget I said anything... :|

**Comment by Frenzie** [comment]
I just mean that 200MB+ can be easily taken up by (some) documents.
Nevertheless QtWebkit takes like a 100 times as long to compile as KOReader
so I think that's probably out of the question. ;)

**Comment by checcousero** [comment]
I understand. Hope in the future there will be an affordable way (in terms of resources and time) to implement this really cool feature...
Anyway, thanks to all the KOReader developers for the work!

**Comment by houqp** [comment]
We can just hit the web page, parse and extract needed information in Lua and present that to the user.

**Comment by Frenzie** [comment]
Sure, but unlike an API that's quite prone to changes.

**Comment by nathanmp** [comment]
I think that [owlbot](https://owlbot.info/api/v1/dictionary/test) might be a good search engine to add. I doubt it'd be too terribly challenging - I might be able to do it.

**Comment by didierm** [comment]
To extend battery life, 95% of my e-reader usage excludes WiFi connectivity.
This prevents on-line Wikipedia lookups.

Aard2 (http://aarddict.org/) :
* for Android has been made available on F-Droid (https://f-droid.org/packages/itkach.aard2/) ;
* offers fast off-line lookups (foreign language dictionaries, Wikipedia, Wiktionary, ...) in the slob format (https://github.com/koreader/koreader/issues/2333#issuecomment-260051030) ;
* caters for diacritics (e.g. 'Déjà vu' resolves to 'deja vu', and vice versa) ;
* provides an API (https://github.com/itkach/aard2-android#launching-from-other-applications).

Would it be an eligible option to provide Aard2 search lookups in KOReaders dictionary lookup ?

**Comment by pazos** [comment]
Too generic issue. Closing it :p
