### ISSUE TITLE
add two finger touch gesture to refresh eink

### ISSUE THREAD

**Issue by aconicq** [koreader/koreader#2348]
* KOReader version: 
* Device: Kindle PW2

I would like to add a command to refresh the display when I do a two finger touch/other gesture. This would be combined with 99 pages between refreshes, so when the ghosting becomes too annoying a gesture can be used to refresh it. 

I was wondering where I can find the touch control scripts to implement this? Thanks

**Comment by bel3atar** [comment]
It's already implemented: https://github.com/koreader/koreader/wiki/KOReader-Gestures

**Comment by houqp** [comment]
Sorry, I missed this thread earlier. As @bel3atar mentioned, we already support this gesture. You can find an example at: https://github.com/koreader/koreader/blob/master/frontend/ui/widget/screenshoter.lua#L25.

All supported gestures are documented at: https://github.com/koreader/koreader/blob/master/frontend/device/gesturedetector.lua#L6

It's best if you can implement this as a plugin.

**Comment by houqp** [comment]
Oh, LOL, now I know why you implemented it as a plugin @robert00s , it's all my fault for pointing you at the wrong direction :(

**Comment by robert00s** [comment]
@houqp I think we can close it now.
