### ISSUE TITLE
Red LED backlights cannot be shifted from within Koreader

### ISSUE THREAD

**Issue by wvhulle** [koreader/koreader#2350]
* KOReader version: v2015.11-675-g09f2db3
* Device: Kobo Aura One

#### Issue

Kobo Aura One has red LED backlights that are gradually turned up and off (in Nickel) according to a preset day and night cycle.

Nickel has the following functionalities (besides controlling the white led's)

- The amount of red light follows a sinus with maximum 4 or 5 hours after bedtime.
- Bedtime is set to determine this maxium
- The amount of red light can be manually adjusted as well, this can be seen as changing the amplitude of the sinus. 

After installing KSM and Koreader, it was not possible to use this function anymore without starting Nickel and exiting to Koreader. It would be nice to have the same functionality in Koreader. 

Too add it, i think would be necessery to update this amount according to the current time (or 15 min), a bedtime and amplitude user setting. This settings shouln't be accessed too much by user and could be hidden somewhere near the frontlight setting in the koreader menu.

Thanks in advance!

**Comment by wvhulle** [comment]
Apparently someone already talked about this in #2285 , but the developer did not have time yet to experiment with this. I will add my suggestions to that issue.

**Comment by houqp** [comment]
Thanks for help organizing the discussions. I am closing this one as a duplicate for now.
