### ISSUE TITLE
[Project]: Boot to KOreader [test device: Aura HD]

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#2352]
* KOReader version: any of them [+2015]
* Device: Kobo Aura HD

#### I'm running a kobo aura hd from the external sdcard using a modified version of uboot. It runs koreader just fine from a minimal root filesystem.

With all the new features of koreader, like the great wifi UI, I barely need any hackish scripts running on the background to have an open-source ereader (except from kernel blobs, the netronix coproccesor, the wifi drivers...)

Here is my - last, I hope - issue (handling USB mass storage)

I run koreader from /opt/koreader. Something like this:
 `while true; do /opt/koreader/koreader.sh /mnt/; sleep 5`

In those 5 seconds the reader isn't running koreader. If udev detects an usb_host then it will trigger the usb mass storage mode -and graphical feedback-. 

During koreader execution usb is in usbnet mode, mainly for testing purposes.

the reader works as expected but the solution is NOT very elegant. So it would be awesome if koreader could catch those events and show us a UI to choose like kobo software does

Do you like the Boot to Koreader project [B2K] ?

**Comment by houqp** [comment]
Yes, this a goal @chrox and I want to achieve in the future. We even dreamed about designing open-hardware reader devices to go full stack :)

Not sure if you have heard it before, @lgeek already made a huge progress on building a Debian based distribution for KOReader: https://github.com/lgeek/okreader. However, the installation process can be a little bit daunting right now ;p

With regard to usb hotplug event, koreader already reads them in kobo platform: https://github.com/koreader/koreader-base/blob/master/input/input-kobo.h#L48. We are only using the hotplug event to prevent charging from interrupting the sleep state. But surely, we can hook them up to any functionalities we want ;)

**Comment by pazos** [comment]
@houqp: I didn't know. Debian for this device seems to much for me. I am happy with buildroot.

The installation method can be improved, of course. Right now my uboot can be installed with the koboroot method and the rootfs can be created with a simple dd command (I choose to have two partitions on sd, the first one for compatibility with original software: fat32, the second one: ext2). We can have some simple steps like: 1) create a big partition in vfat. 2) create a little partition (about 200-400MB) 3) write the changes to the sd 4) use dd if=/path/to/image.disk of=/dev/mmcblk0p2 

I have working repos for both uboot and kernel for the kobo aura hd.

[u-boot sources](https://github.com/pazos/u-boot-2009.08-kobo)
[kernel sources](https://github.com/pazos/linux-2.6.35.3-kobo)

Right know booting from external SD requires pressing FL button while powering on. I'm working on a more elegant solution using uboot scripting

**Comment by lgeek** [comment]
@pazos Why cross-compile when you can just install the packages maintained by a mature distribution? And you get all the development and debugging tools you might want, right on the device, one apt-get away. Plus, my eventual aim is to support updating the device, including the distribution and koreader using the existing package management infrastructure. Sadly, I've been busy with other things so progress is very slow.

Anyway, we can agree to disagree on the base system and collaborate on other more important bits like missing functionality for koreader.

**Comment by pazos** [comment]
@lgeek: No shortcomings at all. I just needed to copy some files from kobo firmware (like the files you rewrote) plus the Kobo eReader.config that has the frontlight setting. I just want to have usb storage integrated in koreader UI.

Looking at your readme, best installation option for me is to boot from the external SD - in that case the internal sd card stays almost untouched - just u-boot is replaced. The easiest method is the dual-booting 

I'm happy to help you with uboot and kernel patches. I need to find some time to test a few things myself first.

**Comment by houqp** [comment]
I think the biggest win for collaboration here is to have a well maintained uboot and kernel for developers and an dead easy installation/uninstallation process for end users.

I am personally interested in the kernel part because the code that handles sleep mode in the current kobo kernel looks weird. It will be a win win if we can help them improve it. It's possible that they did not released the latest source code.

**Comment by Frenzie** [comment]
@houqp 
> We even dreamed about designing open-hardware reader devices to go full stack :)

Hah, talk about ambitious! =P Btw, I don't know how open the hardware on this thing is, but it sounds more open than most: https://www.indiegogo.com/projects/13-3-inch-android-e-reader#/

**Comment by houqp** [comment]
Yep, I have seen that one before. I think they are only open firmware, the hardware design is closed.

**Comment by AlanSP1** [comment]
@lgeek 

> What shortcomings have you noticed when using it without nickel?

Only thing that is missing from koreader in my opinion is setting date and time within koreader. Nickel allows that if I'm not mistaken. I'm using it with KSM8, and it has small terminal program that allows using date command. Also tshering made small script that quickly synchronizes hardware clock.

**Comment by Frenzie** [comment]
I gave him that idea. http://www.mobileread.com/forums/showpost.php?p=3212807&postcount=49 #hurtpride ;-)

**Comment by houqp** [comment]
The UI for setting date and time should be pretty trivia to implement in KOReader.

**Comment by AlanSP1** [comment]
I was referring to this script: http://www.mobileread.com/forums/showpost.php?p=3403084&postcount=256 It needs to be run from terminal if you want manually set time, or available WiFi network (I don't have it all the time).

And, there's a matter of hardware clock, it needs to be synchronized with system clock, which I learned hard way. Now tshering included automatic synchronizing with hardware clock, if you use linked script. If you don't synchronize hardware clock at some point before reboot, you'll be back to whatever time hardware clock thinks it is. At least on Kobo devices.

**Comment by lgeek** [comment]
@houqp What do you envision as a 'dead easy installation/uninstallation process for end users'? I'm weary of giving people a tool with which to shoot themselves in the foot. However, if the community would be willing to provide support to users, then that might change things.

What are the issues with sleep in the kernel?

I would also like a UI for setting the time and date. What about timezone? If I recall correctly, the Kobo firmware sets the timezone, so the RTC is probably set to GMT rather than the local time.

**Comment by pazos** [comment]
@lgeek:

>What do you envision as a 'dead easy installation/uninstallation process for end users'?

An installation/uninstallation procedure using kobo upgrade routines, mainly koboroot.tgz and upgrade folder in /mnt/onboard/.kobo

Installation should be compatible with booting stock firmware. I suggest upgrading [u-boot](https://github.com/pazos/u-boot-2009.08-kobo/commit/c55b88f92cba07ea559a9bc250e4a17853a5a499) and repurpose the recovery method to boot from external sd.

I changed the environment a little bit and place it in a different offset. In the first boot it will find a broken environment and load the the modified one - hardcoded in u-boot binary -.

By default uboot will run 'bootcmd'. If the frontlight button is pressed during early boot it will run 'bootcmd_recovery'. bootcmd_recovery procedure takes some more time to boot (I don't know why, but it is noticeable [10-15s]. bootcmd procedure uses, by default, 'bootcmd_internal', but it can be changed to use 'bootcmd_external' instead.

Flashing stock u-boot worked in the same way (invalid environment -> default environment -> boot) but you'll recover the ability to use the recovery/factory reset combo

**Comment by houqp** [comment]
> What do you envision as a 'dead easy installation/uninstallation process for end users'?
>> An installation/uninstallation procedure using kobo upgrade routines, mainly koboroot.tgz and upgrade folder in /mnt/onboard/.kobo

Basically this, I am hoping any user can get this installed with a single file drop followed by a restart.

> What are the issues with the sleep implementation in the kernel?

While @NiLuJe and I were looking at the suspend issue, there are times when writing to `/sys` files will result fail with syscall errors which prevented the device from going into sleep. We also noticed that the native system is writing to a file that sets a global variable in the kernel module, but we were not able to find where that global variable is used based on the source they released. So we suspect they did not release the latest source code.

Recently (#2239), we noticed sleeping longer before requesting the kernel to put device into sleep mode results in a much higher success rate. So I feel like there might be a race condition in the sleep handling code. From the limited strace log we have, looks like the native system just keeps reissuing the sleep request in a busy loop :-/

Occasionally, we also noticed the device will run into a corrupted state where the sleep request will always fail until reader is exited and restarted. I still can't think of a type of bug that can cause this kind of issue to happen.

> I would also like a UI for setting the time and date. What about timezone? If I recall correctly, the Kobo firmware sets the timezone, so the RTC is probably set to GMT rather than the local time.

Yeah, good point, the time setting UI should support timezone too.

> By default uboot will run 'bootcmd'. If the frontlight button is pressed during early boot it will run 'bootcmd_recovery'. bootcmd_recovery procedure takes some more time to boot (I don't know why, but it is noticeable [10-15s]. bootcmd procedure uses, by default, 'bootcmd_internal', but it can be changed to use 'bootcmd_external' instead.

This means we will have to go through bootcmd_recovery every time if we want to boot to koreader?

**Comment by KenMaltby** [comment]
Since KOReader already makes so much use of a WiFi connection to the internet, perhaps a time check could be added to the WiFi startup? You might even add a menu item to "Network" such as "Check Time".

**Comment by pazos** [comment]
@houqp: by default, yes. The device will boot from Stock OS. Anyways this can be changed if the user wants, booting koreader from external SD card by default and using the key combo to boot stock OS. Running koreader by default is a lot faster than running it using the key combo. AFAIK frontlight button + power button modifies the environment *once* and, at some point, introduces some delay *before* linux execution. This is also true on the case of booting stock OS using the bootcmd_recovery method - it will take some more time to boot (8-10s)

Anyways, having access to the Stock OS is a must to be able to "uninstall" u-boot using the installation method (koboroot.tgz) and we can change u-boot environment from userspace if we want to.

@lgeek: 

I was thinking about a better way of handle usb storage on debian. What about an udev rule to run mass storage  on demand?

I also suggest to move koreader to /opt (rootfs partition). Koreader could run during usb storage but we need a way put koreader in a waiting state to avoid crashes trying to access to /mnt to prevent filesystem corruption.

**Comment by pazos** [comment]
> While @NiLuJe and I were looking at the suspend issue, there are times when writing to /sys files will result fail with syscall errors which prevented the device from going into sleep. We also noticed that the native system is writing to a file that sets a global variable in the kernel module, but we were not able to find where that global variable is used based on the source they released. So we suspect they did not release the latest source code.

Everything under arch/arm/mach-mx5/ seems almost like a vanilla kernel, but with a lot of weird netronix(ntx) stuff: mainly [mx50_ntx_io.c](https://github.com/pazos/linux-2.6.35.3-kobo/blob/master/arch/arm/mach-mx5/mx50_ntx_io.c) and [ntx_hwconfig.c](https://github.com/pazos/linux-2.6.35.3-kobo/blob/master/arch/arm/mach-mx5/ntx_hwconfig.c).

Most of the hardware is handled by the ntx proccesor (like hardware buttons, hardware watchdog, frontlight...). Within linux we use ioctl system calls to communicate with the ntx core for doing almost everything.

**Comment by lgeek** [comment]
@pazos Yes, koreader on okreader is installed in /opt. We need a way to get koreader to close all file descriptors, otherwise I don't think it would be possible to umount the SD card. On my own device I keep USB mass storage enabled all the time and I didn't have any issues, but that's not actually safe for the data partition.

Generally I don't like the idea of messing with the internal partition for installation. Firstly, it would be quite difficult to recover if something goes wrong on the hardware using soldered eMMC rather than removable uSDs. Secondly, I'm not sure that even kobo's recovery software can recover the device if the HWCONFIG block is damaged. Similarly, I'm not sure if the kobo firmware would work on a device with a damaged serial number block.

**Comment by KenMaltby** [comment]
"exec n<&-" comes to mind.

**Comment by houqp** [comment]
> Anyways, having access to the Stock OS is a must to be able to "uninstall" u-boot using the installation method (koboroot.tgz) and we can change u-boot environment from userspace if we want to.

Yes and we should make sure booting into stock os is as easy as booting into koreader so users can freely choose whatever system they want. I am curious how does the recovery boot approach work for models without frontlight buttons. How hard is it to implement a boot loader screen where people can choose which OS to boot into?

> Most of the hardware is handled by the ntx proccesor (like hardware buttons, hardware watchdog, frontlight...). Within linux we use ioctl system calls to communicate with the ntx core for doing almost everything.
>
> @houqp: which kernel module?

I found the old discussion here: https://github.com/koreader/koreader/issues/1862#issuecomment-190506640

Now that I looked at the source code again, looks like that global variable(gSleep_Mode_Suspend) is used in `mx50_ntx_io.c` to handle touch screens? 

Currently we are not using iocl to interface with the kernel, just sysfs.

I am still trying to figure out how does the reader get into the sleep corruption state.

> @pazos Yes, koreader on okreader is installed in /opt. We need a way to get koreader to close all (ebook / file manager) file descriptors, otherwise I don't think it would be possible to umount the SD card. On my own device I keep USB mass storage enabled all the time and I didn't have any issues, but that's not actually safe for the data partition.

Can we just exit koreader and restart it after the transfer is done? The speed would the basically the same as closing and reopening the current book.

> "exec n<&-" comes to mind. exec 3<&- , has been handy in the past.

This will probably only work for shell scripts where you know exactly what are the file descriptor numbers.

> Generally I don't like the idea of messing with the internal SD for installation. Firstly, it would be quite difficult to recover if something goes wrong on the hardware using soldered eMMC rather than removable uSDs. Secondly, I'm not sure that even kobo's recovery software can recover the device if the HWCONFIG block is damaged. Similarly, I'm not sure if the kobo firmware would work on a device with a damaged serial number block.

I agree. In my opinion, the ability to cleanly revert all mods is the most important factor. How does booting from external SD installation work for okreader?

**Comment by pazos** [comment]
@houqp @lgeek: it isn't possible to boot from external sources without modifying internal SD card. We have two options here:

modify uboot binary (at the beggining of the disk /dev/mmcblk0) and keep the system as is
modify rootfs on /dev/mmcblk0p1 and implement the boot logic from userspace.

About the menu in uboot: fiddling with uboot in kobos is difficult. There is a watchdog, running from stage1 bootloader, which resets the board after a few seconds if linux isn't loaded yet.

**Comment by houqp** [comment]
> modify uboot binary (at the beggining of the disk /dev/mmcblk0) and keep the system as is

What's the recovery process if the installation process corrupted this partition?

> modify rootfs on /dev/mmcblk0p1 and implement the boot logic from userspace.

How does the userspace boot logic work? I would love learn more about this :)

> About the menu in uboot: fiddling with uboot in kobos is difficult. There is a watchdog, running from stage1 bootloader, which resets the board after a few seconds if linux isn't loaded yet.

Yeah, now that I think about it, it would also require us implementing screen and touch driver in uboot, which is too much work.

> kobos without fl button use other key combos: power+home(kobo touch), power+reset(kobo mini) to boot from recovery.

Good to know, thanks :)

**Comment by houqp** [comment]
Also, I lied in my previous comment, we did use ioctl in kobo to control the frontlight ;)

**Comment by pazos** [comment]
@houqp: sorry for the delay

>What's the recovery process if the installation process corrupted this partition?

there isn't any partition. the first 10 MB are raw data. dd is used to write at the offset of 1MB. If you write a fault bootloader (ie: a kobo touch bootloader in a kobo aura hd) the only way to recover the brick is to open the device, extract the internal sd and flash a working one (stock bootloader are provided on every kobo firmware images avaliable online) So, this method is safe to try on: Kobo Touch -some models-, Kobo mini, Kobo Glo, Kobo Glo HD, Kobo Aura HD, Kobo Aura H2O.

This uboot enviroment is safe for all thosedevices:
```"cmd_common=setenv bootargs console=ttymxc0,115200 rootwait quiet no_console_suspend " \
"cmd_internal=run cmd_common; setenv bootargs $(bootargs) root=/dev/mmcblk0p1 rootfstype=ext2 rw\0"
"cmd_external=run cmd_common; setenv bootargs $(bootargs) root=/dev/mmcblk1p2 rootfstype=ext2 rw\0" \
"bootcmd_default=setenv bootcmd run bootcmd_internal\0" \
"bootcmd_first_time=run bootcmd_default; saveenv; reset\0" \
"bootcmd_internal=run cmd_internal; load_ntxkernel; bootm\0" \
"bootcmd_external=run cmd_external; load_ntxkernel; bootm\0" \
"bootcmd_recovery=run bootcmd_external\0" \
"bootcmd=run bootcmd_first_time\0" \
"verify=no"

```

> How does the userspace boot logic work? I would love learn more about this :)

Sorry, It sounds awesome, but it isn't. I mean modify inittab to run a script on sysinit. The script will check for a working ext2 partition on /dev/mmcblk1p2 (sd, second partition).

> Yeah, now that I think about it, it would also require us implementing screen and touch driver in uboot, which is too much work

It is already implemented on stock sources and compiled by default. I really hate the watchdog thing :-1:

**Comment by houqp** [comment]
I feel like if we are going to modify internal SD card anyway, might as well boot from internal SD directly.

> there isn't any partition. the first 10 MB are raw data. dd is used to write at the offset of 1MB. If you write a fault bootloader (ie: a kobo touch bootloader in a kobo aura hd) the only way to recover the brick is to open the device, extract the internal sd and flash a working one (stock bootloader are provided on every kobo firmware images avaliable online) So, this method is safe to try on: Kobo Touch -some models-, Kobo Glo, Kobo Glo HD, Kobo Aura HD, Kobo Aura H2O.

We should be able to safe guard mismatch model bootloader flash by reading the current firmware first right?

**Comment by pazos** [comment]
> We should be able to safe guard mismatch model bootloader flash by reading the current firmware first right?

@houqp: yes, of course. This is already implemented in stock firmware. Each uboot/kernel binary is prefixed with a different board ID.

I'm closing this issue since my Aura HD has a broken touchscreen as was repurposed as a (nice?) weather clock. On the other side I got a better device for a Boot to KOReader project, the Cervantes4 :smile:
