### ISSUE TITLE
Problem: same configuration for sleep and turned-off screensaver.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2359]
* KOReader version: 2015.11-694
* Device: Kobo Mini

#### Issue
If I am not wrong, the new turn-off screensaver uses the same configuration than the sleep screensaver. That is, is not possible to choose different screensaver images for sleep mode and turned-off mode.
In my Kobo, as screensaver for sleep mode, I have been using a folder to the images that I use as sleep screensavers. When I turn off the device one of those images appear now. It should be possible to define a path to a folder with images for sleep mode and a different path for aother folder for turn-off mode. Or even to define completely different behaviours, like the book cover as sleep screensaver and a different image as turned-off screensaver.
The problem is that, at a glance, looking at the device, the user cannot know if the device is in sleep mode or turned-off at least that he tries to wake up the reader. In the nickel firmware there is not that problem because a text appears on the screensaver (the cover of the book) saying if it is sleeping or turned off.

**Comment by houqp** [comment]
@baskerville added different section for each mode, see: https://github.com/koreader/koreader/pull/2349#issuecomment-261726070

**Comment by AlanSP1** [comment]
I just played a bit with this, as you can see from my comments. You only need to be very careful about syntax, save before settings.reader.lua file (in case you mess your file, it gets erased along with your settings).

Now it is really great. And I tested with custom text message, it worked great. Didn't tested with images, but I guess it would work just fine.

**Comment by houqp** [comment]
Always make a copy before any manual editing of the setting file ;) In the future, we will have a web page for setting editing and validation so you can do everything from the browser and just download the new setting as a file.

**Comment by AlanSP1** [comment]
That would be really great.

Also, maybe if there is wiki page or something with all possible and correct settings we can manually add in settings.reader.file for now? It would make things much easier, as not all settings are in file by default, only when they are triggered in some way.

**Comment by houqp** [comment]
The setting documentation part should be automated too. I am thinking of something like a tool that parses comment in the code and automatically generates a section for all available settings in a user manual.

**Comment by AlanSP1** [comment]
This would be really great! :+1:
