### ISSUE TITLE
FR: Setting for folder and files blacklist in file browser.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2360]
* KOReader version: 2015.11-692
* Device: Kobo Mini

#### Issue
The folder "System Volume Information" is visible in the file browser. It should be hidden (even if the option show hidden files is ticked).

**Comment by houqp** [comment]
What's in this folder? I haven never seen it before. It's created by the native system?

**Comment by Frenzie** [comment]
It's something Windows creates, but I think normally only on its system
drive?

**Comment by retrue** [comment]
It is created by Windows in each partition, but it is not normally accesible from Windows even with the option of showing hidden files. It contains system info. The folder is visible if you access that partition from Linux.
But that folder is shown too by the file browser in KOReader. It should be possible to hide it. Maybe add a text file where you could blacklist filetypes and folders so they are not shown?

**Comment by houqp** [comment]
Yes, I think a setting for file blacklist would be ideal.

**Comment by Frenzie** [comment]
There already is an exclude_dirs in the FileChooser widget.

https://github.com/koreader/koreader/blob/1b700c00443da111bdd3eb0bad6a42a9a8f2a370/frontend/ui/widget/filechooser.lua#L31

The simplest way would be to change the line like this, but given that (however unlikely) users might name their folders that it's probably not the right way.

```lua
exclude_dirs = {"%.sdr$", "/System Volume Information$"},
```

**Comment by houqp** [comment]
I think that should be fine. User can manually name a `foo.sdr` directory too ;)

**Comment by Frenzie** [comment]
That seems significantly less likely though. ;-)

**Comment by houqp** [comment]
True, but I can't think of a better way to handle this :) Perhaps make this a configurable option and let users manually opt-in via editing the reader setting.

**Comment by retrue** [comment]
For me, a good solution would to implement this through a text file.
The user could create/edit a text file where he could enter specific directories, specific files and file types in the easiest possible way: one line by each item, possibility to unblock a specific item using # or semicolon.
Example: blacklist.cfg
/mnt/onboard/.adobe-digital-editions
;/mnt/onboard/.kobo
"/mnt/onboard/System Volume Information"
/mnt/onboard/koreader.png
/mnt/onboard/launcher.png
;"/mnt/onboard/My books/*.mobi"

**Comment by houqp** [comment]
good idea, i suggest we name it as filemanager.ignore. The `"` is redundant if we read the config entry line by line.

**Comment by Frenzie** [comment]
What about the syntax? Lua patterns, [shell globbing](http://www.cs.tufts.edu/~nr/drop/lua/posixutil.lua)? ([via](http://stackoverflow.com/a/326660/2470572))

**Comment by retrue** [comment]
I don't know what is the correct syntax but imho it should be something easy and obvious for the user.
As name for the blacklist file, if blacklist.cfg is not god, I would propose then filemanager.ignore.cfg
The name and extension must be obvious too so the user can be able to easily locate and open the file to edit it.

**Comment by protist** [comment]
If the plan is for there to be default files in the blacklist, another one that always annoys me is the `kbmenupngs` directory (along with `koreader.png`).

**Comment by retrue** [comment]
I opened this issue four years ago and I always see it in the open milestones.
Which is the problem to implement this?

**Comment by NiLuJe** [comment]
Someone actually willing to spend the time to work on it ;).

**Comment by NiLuJe** [comment]
Did a thing in #7371 (not configurable, because that's a can of worms I won't care to open).
