### ISSUE TITLE
hindi unicode font is not supported

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#2368]
* KOReader version:v2015.11-587 and latest stable version
* Device:Kindle paperwhite 2

#### Issue
Hindi unicode font is not supported in ko reader.Any e pub book which is formatted in hindi unicode font is not displaying in ko reader properly even after installing hindi unicode font in ko reader font directory.There occurs a lot of gramatical mistakes although words are showing in hindi.However after converting the book to .mobi or .azw3 via calibre there occurs no problem when i read it through native kindle operating system.Please help to resolve this issue as there are large number of people who read hindi books on kindle.Thanks in advance

**Comment by houqp** [comment]
@tarungupta2001 can you provide an example book for us to test with?

**Comment by tarungupta2001** [comment]
Yes of course i am attaching the Mahatama Gandhi's book Satya ke prayog in epub format as well as in .mobi  format.Just read the .epub book  in ko reader and .mobi format through the native kindle paperwhite operating system.you will notice the difference.There occurs no spelling mistakes in .mobi when i read it through native kindle operating system.But when the same .mobi format book is read through ko reader then the same gramatical mistakes occur.One more thing i will point out to you that this book contains the embedded mangal hindi unicode font.But to read it through ko reader i have to install mangal unicode hindi font in ko reader font directory.Where as .mobi format requires no font installation.

**Comment by tarungupta2001** [comment]
I am mailing you the desired files as they are not uploading here due to server problem.

**Comment by tarungupta2001** [comment]
Here are the desired books

**Comment by NiLuJe** [comment]
Should be slightly better since #3942
