### ISSUE TITLE
The Viewport of the Kobo Aura ONE is wrong

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2372]
A test image can be created with:
```
convert -size 1404x1872 canvas:black black.png
```

You'll notice the white borders present around the image within *koreader*.

**Comment by houqp** [comment]
I am pretty sure the view port for aura one is not properly calibrated. You can either manually tweak the image or use the method I mentioned at https://github.com/koreader/koreader/issues/2235#issuecomment-246163292 to find out the exact viewport setting.

Then you can change the viewport at https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua#L62

**Comment by baskerville** [comment]
`Geom:new{x=0, y=0, w=1404, h=1872}` seems to work fine.

I've used this test image:
![grid](https://cloud.githubusercontent.com/assets/159419/20651651/5e344d1c-b4e9-11e6-8450-6fb165c792db.png)

**Comment by houqp** [comment]
feel free to submit a PR to update the viewport.
