### ISSUE TITLE
statistics plugin v2 design

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2378]
This is a discussion ticket for the new statistics plugin design.

@robert00s , new sqlite3 api documentation is ready at: http://koreader.rocks/doc/topics/DataStore.md.html.

Feel free to come up with whatever design that you think makes the most sense. I think it's best to keep it the old way, i.e. having one sqlite3 database for each book. A simple table can be created to just store 3 columns: page_num, start_time, end_time. With this, we can use SQL queries to apply all kinds of aggregations to the raw data to mine interesting stats.

**Comment by apletnev** [comment]
I think the best way to create only one DB file for the statistics plugin. Make and maintain schema only in one place. Because current implementation has overall ("total") statistics for all books. I think it is not a good idea to work with book's DB, especially in case when we will show "total".

**Comment by houqp** [comment]
Good point. A centralized db will make it easier to calculate global stats. Then we need at least two tables, `book` for book metadata and `page_stat` for time spent on each page for all the books.

**Comment by robert00s** [comment]
@houqp 
I have a question.
Where is the function in KO that creates writes in file metadata with "performance_in_pages"? After implement sqlite3 pages and time should be insert into DB.

**Comment by KenMaltby** [comment]
As long as I can continue to totally ignore all the data gathering and it doesn't mess with my reading in any way, I won't be bothered.

**Comment by houqp** [comment]
@robert00s see plugins/statistics.koplugin/main.lua around line 614.

@KenMaltby I only expect the new plugin to be faster and more stable than the current one. So if the current version is not bothering you, you should be fine :)

**Comment by robert00s** [comment]
Unfortunatelly sqlite INSERT are very slow :(


```
local stmt = conn:prepare("INSERT OR IGNORE INTO page_stat VALUES(?, ?, ?)")
for k, v in pairs(self.data.performance_in_pages) do
      stmt:reset():bind(res3, v, k):step()
end

```

INSERT 1000 pages take on my emulator about 7 second.
Convert (insert) 100 books x 500 pages take ~ 6 minutes.
Bigger issue is update pages on current reading book. We should update on every 1-5 pages. 
Update more pages in at the same time or on exit book may take more than 0,5 sec and slower ereader:(

I don't know how it looks on real readers... It may be even slower.

**Comment by houqp** [comment]
140 inserts per second seems unreasonably slow for sqlite. Probably an issue with the sqlite client that i need to further perf test and investigate into. BTW, is `res3` the row id for books?

**Comment by robert00s** [comment]
@houqp 
Yes `res3` is calculated id for book.
I found that: http://www.sqlite.org/faq.html#q19

**Comment by robert00s** [comment]
When I add:

`    conn:exec("PRAGMA synchronous = OFF;")`

inserts are very fast. Over 6000 in less then 0,5 sec. But if you lose power in the middle of a transaction, your database file might go corrupt.
 If the application running SQLite crashes, the data will be safe, but the database might become corrupted if the operating system crashes or the computer loses power before that data has been written to the disk surface.
http://www.sqlite.org/pragma.html#pragma_synchronous

**Comment by poire-z** [comment]
Should we worry about SD card wearing (like SSD disks do) if there's some sqlite disk write at each page turn ?
Could there be some tunable like "save  only after 10 page turns", so there's an insert/update/commit only then. But of course a full flush when exiting a book, or the reader, or when the statistics plugin is invoked ?

**Comment by Frenzie** [comment]
Unlike for SSDs, for SD cards that's more of an actual concern. SD cards don't come with controllers sporting complicated wear leveling algorithms.

**Comment by AlanSP1** [comment]
Is it possible that statistic info is written in memory and flushed to SD card only at suspending or powering off? Very rarely device would crash and if it crash, loosing a bit of reading statistic isn't that big of a problem, as constantly writing to SD card. Or at least that seems so to me.

**Comment by robert00s** [comment]
@AlanSP1 
Yes it it possible to write statistics only at suspending or powering off. Possible that there will be needed to write when we go to statistics menu (to prepare statistics).

**Comment by houqp** [comment]
Yes, we can keep them in memory for awhile just like what we are doing right now. @robert00s do we really need to turn off sync? Is batching inserts with one transaction fast enough?

**Comment by robert00s** [comment]
@houqp Thanks :)
With one transaction inserts are very fast:
```
                conn:exec('begin')
                for i, j in pairs(book_stats.performance_in_pages) do
                    conn:exec('INSERT OR IGNORE INTO page_stat VALUES('..id_book..', '..j..', '..i..');')
                end
                conn:exec('commit')
```

**Comment by houqp** [comment]
Cool :) I think you should be able to get more performance out of it by avoid doing multiple string concatenations since they are expensive in LUA/LUAJIT. Try the prepare, reset, bind combo. 

Or you can also do:

```lua
string.format('INSERT OR IGNORE INTO page_stat VALUES(%d, %d, %d);', id_book, j, i))
```

Although it's generally a bad practice to do manual raw string generation for SQL queries. Using builtin methods like `bind` should always be the preferred solution.

**Comment by robert00s** [comment]
Ok, I will use "prepare, reset, bind combo" :)

**Comment by robert00s** [comment]
Is it possible to catch from statistics plugin (in plugins/statistics.koplugin/main.lua) menu open (activate) and close events? Somethink like ReaderStatistics:onMenuOpen() and ReaderStatistics:onMenuClose()
We have now ReaderStatistics:onResume() in https://github.com/koreader/koreader/blob/master/plugins/statistics.koplugin/main.lua#L648 that is run when device is resume from sleep or from screensaver.
I need that to better calculate reading time.
Any ideas? :)

**Comment by Frenzie** [comment]
There are `ShowReaderMenu` and `CloseReaderMenu` events. It might suffice to write `ReaderStatistics:onShowReaderMenu()` and `ReaderStatistics:onCloseReaderMenu()`. Worth a quick try. ;-)

**Comment by robert00s** [comment]
Yes, I mean that you won't be reading while menu is up.
But `ReaderStatistics:onShowReaderMenu()` won't work. I don't know why :(

**Comment by poire-z** [comment]
Technically, you could add your own methods `ReaderStatistics:onReadingPaused()` and `ReaderStatistics:onReadingResumed()`, and add **everywhere** focus is lost and regained `self:broadcastEvent(Event:new("ReadingPaused"))` and `self:broadcastEvent(Event:new("ReadingResumed"))` 
But I was told these calls are costly, and i'm not sure such accurate statistics are really needed.
Also, you would really need to not forget a `ReadingResumed`, and as they are many way to get out of something, you would quickly see your statistics not getting updated, and it could quickly becore a nightmare to track them.

**Comment by Frenzie** [comment]
I assume propagation is stopped somewhere, or maybe it just stays within the widget and would have to be broadcast instead to reach the plugin (I haven't checked the code here nor do I have the time to debug it to figure it out if it's not immediately obvious). But like @poire-z said I don't know if it's worth the effort regardless.

**Comment by robert00s** [comment]
Thanks for explanations.
I will not use such accurate statistic. I leave it as it is.

**Comment by houqp** [comment]
`ReaderMenu:onShowReaderMenu` returns `true`, which will stop the event propagation. Let's get the basic stuff working before considering adding fancy features. Like @poire-z said, it can get complicated real quick ;) I think it's a reasonable tradeoff between accuracy and correctness.

**Comment by robert00s** [comment]
Next small problem :)
The new version of the statistics will use the database. But ReaderFooter module uses sdr files to calculate average_time_per_page (see: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerfooter.lua#L489). Question is how to now transfer average_time_per_page from the statistics plugin (I can calulate it from database) to the ReaderFooter without sdr files?

**Comment by houqp** [comment]
The way it's currently implemented is not a good practice. It's polluting the core code path with plugin specific logic. I would suggest we make the footer module fully pluggable so plugins can also register extra footer info. Then, we can let the new statistics plugin handle the calculation and info text generation. Footer will just blindly take whatever output a plugin gives and draw it on the screen without knowing what those output is.

**Comment by robert00s** [comment]
Done in #2893. We can close it.

**Comment by Frenzie** [comment]
You have the power. ;-)
