### ISSUE TITLE
Turn off wifi on exit

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2379]
* KOReader version:  koreader-nightly-20161120
* Device: Kindle PW3

#### Issue
When I exit from KO to Kindle native system wifi is always switched off.
#### Steps to reproduce
Turn on wifi -> Exit from KO to Kindle native system -> wifi is off

This line should be removed?
https://github.com/koreader/koreader/blob/master/reader.lua#L192

**Comment by retrue** [comment]
I think it should be an option.
For people who prefer to have wifi on all the time it is a problem, but for people who almost always have wifi off the actual behaviour is handy.

**Comment by Frenzie** [comment]
This is a very recent addition.

https://github.com/koreader/koreader/commit/db5a872ec6c772778ab36984e3fb8dc73140e9eb

@houqp What was the reason for adding it?

**Comment by Hzj-jie** [comment]
This change also impacts Kobo.

**Comment by houqp** [comment]
I will think about it, this change was added for kobo ksm users. You will freeze the device if you exit koreader and launch nickel when wifi is on. It's a workaround for a bug in nickel.

**Comment by asampal** [comment]
@houqp is this still a problem. I just tried launching nickel from KSM on my KA1, with wifi on and the device didn't freeze. I was presented with an option to turn off wifi as nickel was launched, but I chose to keep it on.

**Comment by houqp** [comment]
@asampal KSM has its own prompt for disabling wifi before starting nickel now? Right now, KSM will show a warning to you if KOReader exits without disabling wifi.

**Comment by asampal** [comment]
@houqp is the first part of your comment meant to be a question? Also, do you know if it's still a problem when launching nickel with wifi on? That was my question.

**Comment by houqp** [comment]
First part of my comment is a question. I am not familiar with the nickel system actually since I have never used it myself. This is a better question for KSM author. I suggest you ask him on mobileread forum.
