### ISSUE TITLE
Crash on start on Ubuntu Touch

### ISSUE THREAD

**Issue by TronFortyTwo** [koreader/koreader#2382]
* KOReader version: nightly 20161120 and nightly 20160823. I haven't tried previous nightly
* Device: bq acquaris E5 ubuntu edition on the release candidate channel (dev OTA 14)

#### Issue
Crash when try to open.

#### Steps to reproduce
Download the click package, install it then click on the icon. After half second of loading the app crashes. If you want I can attach some log, but I don't know where to find them.

Thanks for all your work!

**Comment by houqp** [comment]
I don't know how ubuntu touch works either ;P Just did some googling and found this: http://askubuntu.com/questions/548504/ubuntu-sdk-how-can-i-see-error-logs-for-my-ubuntu-touch-app

**Comment by Frenzie** [comment]
Does it still crash?

**Comment by TronFourtyTwo** [comment]
Yes. Now I tested latest nightly 20170308

**Comment by Frenzie** [comment]
Any luck on getting logs?

**Comment by TronFourtyTwo** [comment]
No, there is no log in the default .cache/upstart/ folder where ubuntu touch logs are stored.

**Comment by Frenzie** [comment]
Please refer to #4960 instead.
