### ISSUE TITLE
File Manager additions for tidy people

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#2391]
(Thank you for your welcome on my first pull request!)

I made quite a few adds/mods to koreader to fit my needs over the last weeks, and felt like some of them may be of general interest.
houqp suggested i open an issue and write a brain dump of my local changes.  As this brain dump got big, i decided to split it over a few issues.

I browsed thru my big patch, and wrote a complete list of the changes I made. So what's coming looks more like a bunch of commit messages than a real presentation. Hope that's ok, and well, i'll have these commit messages ready if you want them.

frontend/apps/filemanager/filemanager.lua
Allow doing some stuff that would otherwise require to plug to a computer :
- added to file hold context menu a button "Purge .sdr" (so now it's 2 rows of 3 buttons) to remove .sdr directory (and also item from history), so one can start from a fresh one (or to just clean things when i open a book to see or test, or mess with settings and want to revert to default settings). We may find a better name than "Purge .sdr"... ("Prune" ?)
- when moving (cut/paste) a file, also moves its .sdr directory
- new entry in File Manager's Tools : "Clear readers' caches", that does purgeDir(cache) and recreates it (it happened to me, after changing styles, and a crash, that it crashed again when opening the file : only clearing the cache allowed the book to be opened again)

frontend/ui/widget/filechooser.lua
Display filename in bold if file has an associated .sdr directory, so I can see books i've opened, and purge their .sdr if too much bold :

![filemanager_stripped](https://cloud.githubusercontent.com/assets/24273478/20814568/85e1fa88-b81a-11e6-883f-7c00f88c5e08.png)

**Comment by houqp** [comment]
Looks great! I am happy to merge all these changes. Feel free to submit a PR.'

With regards to `Clear readers' caches`, do you remember what's the in crash log? Ideally, a corrupted cache should never crash the reader. So I would like to fix the actual bug if possible. I suggest we create a `developer options` item under tools menu tab and put this feature into `developer options`.

**Comment by poire-z** [comment]
Thanks, i'll submit PRs over the weekend.

I don't remember how i triggered that.
Managed to trigger SegmentationFault this morning while playing on a specific epub with `Embedded styles` on/off and `Clear all external styles` and `Auto`, but it hasn't prevented me from reopening the book.
Actually, this item would not have helped in the situation that happened once : with the option `open_last=true`, koreader would keep opening the corrupted file and crashes, and would not let me access this menu :| The cleaning would need to be done from KSM.
What should be done to not be locked out of koreader would be for it (may be `readerui.lua`) to flag the opening of any book with a file `.opening_in_progress`, and unflag/delete it when book opened and rendered (= has not crashed). On startup, it (`reader.lua`) should check if this file exists, and if it does, just consider open_last=false, and go to file manager.

About `developer options`, i wouldn't know in what part of the code to do that right (obviously, it should be done elsewhere, for other modules to register their stuff to it - and only in filemanager's tools menu or reader's one too ? - cache cleaning should only be done from filemanager when no reader has that cache open). But i'm good at cut & pasting, so if you tell me "do like it's done for this in that.lua", i'll do it :)
Also, cache cleaning is not just for developers, cache directory is accumulating caches of long time deleted books.

**Comment by AlanSP1** [comment]
All these changes look really great. :+1:  Thanks.

**Comment by houqp** [comment]
> I don't remember how i triggered that.
> Managed to trigger SegmentationFault this morning while playing on a specific epub with Embedded styles on/off and Clear all external styles and Auto, but it hasn't prevented me from reopening the book.
Actually, this item would not have helped in the situation that happened once : with the option open_last=true, koreader would keep opening the corrupted file and crashes, and would not let me access this menu :| The cleaning would need to be done from KSM.
> What should be done to not be locked out of koreader would be for it (may be readerui.lua) to flag the opening of any book with a file .opening_in_progress, and unflag/delete it when book opened and rendered (= has not crashed). On startup, it (reader.lua) should check if this file exists, and if it does, just consider open_last=false, and go to file manager.

This can be added as a temporary workaround for the crash problem. In the long term, we need to run the document rendering engine in a separate process so this kind of crashes can be isolated from the main reader process.

> About developer options, i wouldn't know in what part of the code to do that right (obviously, it should be done elsewhere, for other modules to register their stuff to it - and only in filemanager's tools menu or reader's one too ? - cache cleaning should only be done from filemanager when no reader has that cache open). But i'm good at cut & pasting, so if you tell me "do like it's done for this in that.lua", i'll do it :)

We can just add it to filemanagermenu.lua for now. This can be made more flexible if needed in the future. You should be able to find enough examples in that file :)

> Also, cache cleaning is not just for developers, cache directory is accumulating caches of long time deleted books.

We need to make sure cache cleaning is handled automatically by the reader too. Cache is a technical concept that should be hidden from most users. We can purge the old caches when a document is deleted and on reader exit.
