### ISSUE TITLE
Swipe to follow page's first link

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#2392]
(follow up of #2391, see intro there)

frontend/apps/reader/modules/readerlink.lua
In "Follow links" menu, added option "Swipe to follow page's first link" and boolean setting "swipe_to_follow_first_link".
There is already "swipe east to go back", so let's allow to swipe west to jump to current page's first link (easier than clicking on small links).  Other links of current page are probably there too, or one page away.
That allows quick reading of footnotes with a single move and back, mostly like when reading a book and keeping a finger on the footnotes page, and moving the pack of pages in between left then back.

**Comment by houqp** [comment]
sounds good to me, feel free to submit a PR for this.
