### ISSUE TITLE
icons on bottom are too small

### ISSUE THREAD

**Issue by wvhulle** [koreader/koreader#2401]
* KOReader version: v2015.11-696-g2bc7b01
* Device: Kobo Aura One

#### Issue

Icons on the bottom for changing text size, colums etc are to small. I often miss them. If the size would be doubled it would be much more comfortable.

**Comment by AlanSP1** [comment]
There's this commit: https://github.com/koreader/koreader/pull/2390

It allows changing DPI, which would make every element bigger (or smaller, depending on your settings), so it also would include interface.

Just download latest version and try to change DPI.

**Comment by wvhulle** [comment]
Thank you, It wasn't clear to me that you have to press long on DPI
