### ISSUE TITLE
koreader wont start in KSM08 Start Menu

### ISSUE THREAD

**Issue by mystycs** [koreader/koreader#2404]
* KOReader version: 4.1.7729
* Device: Aura One

#### Issue

I installed KSM08 following this guide http://www.mobileread.com/forums/showthread.php?t=266821

And a stable build of koreader using this link https://github.com/koreader/koreader/releases/download/v2015.11-stable/koreader-kobo-arm-linux-gnueabihf-v2015.11-stable.zip

And when i install it, i see koreader in the KSM08 Start menu, but when i press on koreader, nothing happens. It just flashes. I am able to go in nickel though.

**Comment by houqp** [comment]
Aura one is not supported by the last stable release, which is more than a year ago ;)

Try the latest nightly build: http://build.koreader.rocks/download/nightly/v2015.11-731-g922cd0f/

**Comment by Frenzie** [comment]
The Kobo Aura One only came out a few months ago, so the old stable has no support. It should work with the latest builds from http://build.koreader.rocks/download/nightly/

**Comment by Frenzie** [comment]
Synchronized reply achievement unlocked!

**Comment by houqp** [comment]
LOL, such an coincident, I was just checking emails before going to shower ;)

**Comment by mystycs** [comment]
Awesome. It worked!

Thanks guys!
