### ISSUE TITLE
Nickel does not start from KSM or KOReader

### ISSUE THREAD

**Issue by FranMarelli** [koreader/koreader#2407]
* KOReader version: koreader-nightly-20161120
* Device: Kobo Aura One

#### Issue
When booting on KSM, it is impossible to launch Nickel : it starts loading and then gets back to KSM.
Same problem from KOReader with nickel switch on : it gets nickel launching and then back to KSM.
The problem did not occur at first, it appeared after the second time shutting down and launching KOReader.
Nickel works properly if booted directly (without KSM), but then it is impossible to open KOReader.

#### Steps to reproduce
Install KSM and KOReader following the standard steps given here : [Install on Kobo device](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices)
Launch KOReader from KSM several times and then try to open Nickel from KSM.

**Comment by AlanSP1** [comment]
It looks more of a problem with KSM, not koreader. That just looks like that to me. Like nickel for some reason crashed.

Did you apply KSM patch to work with KA1? Latest version of KSM patch to work with KA1 is here: http://www.mobileread.com/forums/showthread.php?p=3389190#post3389190

**Comment by FranMarelli** [comment]
Thank you for your answer.

I used the latest patch of KSM indeed. Although, I have rebooted the Aura some more times since then and it seems to work again. Strange.
I suppose I cannot fix it until it reappears, so I'll close this issue.

**Comment by houqp** [comment]
@FranMarelli could you add some notes for KA1 installation in the [wiki page](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices) to document the issues you ran into to help future KA1 users?
