### ISSUE TITLE
Menu is very difficult to open in some cases

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2410]
* KOReader version: Last nightly version
* Device: Kobo Mini

#### Issue
It is very difficult to access the menu in those cases where the page of the book is the beginning of a chapter. More difficult in my case because I have a Kobo Mini which has a smaller screen.
Whenever I tap the upper part of the screen, KOReader sends me to the TOC following the link of chapter. If I tap a bit to left of right it goes to the previous or next page or appears a dictionary search. Some times I need to tap 10 or more times to be able to open the menu.
I would like that it was possible to add some new gesture to open the menu: a double tap in the middle of the screen (or the top or bottom middle), a new swipe or any other gesture that guarantees that the menu will always open.
The screenshots are an example of when this problem happens.
Thanks.

![reader_2016-dec-06_220008](https://cloud.githubusercontent.com/assets/18194241/20943702/efbc7e9e-bc00-11e6-8278-f73f510751e9.png)
![reader_2016-dec-06_220015](https://cloud.githubusercontent.com/assets/18194241/20943706/f14555c4-bc00-11e6-8c1d-53f89ac4d4d2.png)

**Comment by KenMaltby** [comment]
Have you tried rolling your thumb off the top bezel onto the screen?  Or just going to the next page, to access the menu?

**Comment by retrue** [comment]
Rolling my thumb off the top bezel onto the screen is like a swipe down begining from the bezel, isn't it? Well, it doesn't work to open the menu.
And yes, I can go to the next page to get the menu, but that is not the point, Mr Maltby.
Thanks anyway  :)

**Comment by houqp** [comment]
Yeah, in retrospective, we should have made double tap the default action to trigger menu. Now it's tricky because it will break the default behavior. I will be more comfortable making this change if we have a new changes walk through demo mode in koreader.

**Comment by retrue** [comment]
My suggestion is not replacing the current configuration to open the menu, but to add a double tap (top middle and, or top bottom), the same way that there are several swipes to pass pages in adition to the single tap.
Another idea would be to add a new entry in the menu called _controls_ that opened a controls window where all the gestures were described. Something like:
Next page: tap on right side, swipe down, swipe right.
Dictionary: long press on word.
etc

**Comment by poire-z** [comment]
From you screenshot, you may be victim of what i described in #2412 (your links at top look single, and make the full width clickable, and that has priority over the menu).

The problem with double tap is that it will slow down reaction of other single taps (you can enable double tap in the Screen menu to see).

A solution may be to change the tap zone for menu, which you can do in `defaults.persistent.lua`.
The defaults (in `default.lua`) are:
```
DTAP_ZONE_MENU = {x = 1/8, y = 0, w = 3/4, h = 1/4}
DTAP_ZONE_FORWARD = {x = 1/4, y = 0, w = 3/4, h = 1}
DTAP_ZONE_BACKWARD = {x = 0, y = 0, w = 1/4, h = 1}
```
If you're fine with taping only in the 1/3 sides of the screen to change pages, you can increase the menu zone height so u can tap in the middle 1/3 (below the "14" in your screenshot). I have:
```
DTAP_ZONE_MENU = {x = 1/3, y = 0, w = 1/3, h = 3/4}
DTAP_ZONE_FORWARD = {x = 2/3, y = 1/8, w = 1/3, h = 13/16}
DTAP_ZONE_BACKWARD = {x = 0, y = 1/8, w = 1/3, h = 13/16}
```

**Comment by houqp** [comment]
> The problem with double tap is that it will slow down reaction of other single taps (you can enable double tap in the Screen menu to see).

This is a bug in the double tap detection code (gesturedetector.lua). I suspect it's problem of finding the right value for `DOUBLE_TAP_INTERVAL`. If it's too high, wait time for single tap detection will increase, if it's too low, it would be too hard for user to perform a double tap.

Problem with changing tap zone is it will still run into issue if most of the menu tap zone also happened to be a link in the document. The core of this issue is we can't bind any book manipulation gesture to the menu trigger, otherwise, you will always run into this ambiguous scenario.

**Comment by retrue** [comment]
I always use double tap because if offers me the option to go to the next/previous chapter, and I have never perceived single taps as slow.
So, in my case, adding a double tap to trigger the menu solves the problem without negative consequences. I would really like that it was implemented.
Another gesture that I would like to see implemented in KOReader is the option to advance or go back 10 pages. It makes browsing pages inside a book nimbler. It is an option that I miss and was included in Coolreader in my first e-reader, a Jinke Hanlin v3+. And I think a double tap would be the best gesture in this case.

**Comment by houqp** [comment]
> Another gesture that I would like to see implemented in KOReader is the option to advance or go back 10 pages. It makes browsing pages inside a book nimbler. It is an option that I miss and was included in Coolreader in my first e-reader, a Jinke Hanlin v3+. And I think a double tap would be the best gesture in this case.

This can be easily implemented as a plugin

**Comment by Frenzie** [comment]
I'm closing this in favor of #2608. In my test branch I think activating the menu on a swipe south works quite elegantly, but I'll have to combine it with a quick start guide.
