### ISSUE TITLE
footnotes : link alone in a div is clickable on the full width

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#2412]
* KOReader version: latest nightly
* Device: kobo glo HD

#### Issue
In .epub (or .html), a short 'a' link alone in a 'div' is clickable on the full page width.
`    <div><a href="#somewhere">123</a></div>`
It's a bit annoying when in the footnote pages, where every other line is a footnote number, clickable to jump to the origin of the footnote. Screenshot from my test file:

![footnotes](https://cloud.githubusercontent.com/assets/24273478/20965404/c879781c-bc75-11e6-98e0-823917e3ee59.png)

If there's some text after the 'a', the clickable area gets right and short.
May be it's the right thing to do (after all, a 'div' should take the whole width), but browsers dont have that behaviour.
It's probably deep in crengine code,
Could that be workaround'ed with stuff in .css (tried a few things with no success) ?

#### Steps to reproduce
I made a html file so you can see for yourself (remove the .txt from filename):
[test_links.html.txt](https://github.com/koreader/koreader/files/636435/test_links.html.txt)

**Comment by poire-z** [comment]
I've been working around this annoying bug by modifying html files and wrapping `<a>...</a>` with a [Zero-width space](https://en.wikipedia.org/wiki/Zero-width_space). For exemple, while saving a wikipedia page as epub, i do:
```
    -- avoid link being clickable before <a> (if it starts a line) or
    -- after </a> (if it ends a line or a block) by
    -- wrapping it with U+200B ZERO WIDTH SPACE which will make the
    -- dom tree walking to find a link stop at it.
    html = html:gsub("(<[aA])", "\xE2\x80\x8B%1")
    html = html:gsub("(</[aA]>)", "%1\xE2\x80\x8B")
```
This hidden character makes the search code stops at it when looking for the element we taped on, so it finds it and not the link behind, and my tap on a blank area is no more considered a tap on a link.

No problem with display, these zero-width-space are known to crengine, and (not) displayed properly. There's even some code in crengine to use a "non breaking zero width space" if this zero width space is not available in the current font.

Later, I thought: why not let crengine do that when parsing any HTML.
I came up with 4 additions to lvtinydom.cpp like these ones:
```
 ldomNode * ldomDocumentWriter::OnTagOpen( const lChar16 * nsname, const lChar16 * tagname )
 {
+    // ldomDocumentWriter is used for epub files
+    if (tagname[0] == 'a' && tagname[1] == 0 && _currNode) {
+        // printf("fixing <a>\n");
+        lString16 ZEROWIDTHSPACE("\xE2\x80\x8B");
+        _currNode->onText(ZEROWIDTHSPACE.c_str(), ZEROWIDTHSPACE.length(), 0);
+    }
[...]
 void ldomDocumentWriter::OnTagClose( const lChar16 *, const lChar16 * tagname )
     [...]
     _currNode = pop( _currNode, id ); // pop parent, _currNode is now the link parent

+    if (tagname[0] == 'a' && tagname[1] == 0 && _currNode) {
+        // printf("fixing </a>\n");
+        lString16 ZEROWIDTHSPACE("\xE2\x80\x8B");
+        _currNode->onText(ZEROWIDTHSPACE.c_str(), ZEROWIDTHSPACE.length(), 0);
+    }
+

```
(same for ldomDocumentWriterFilter used for plain html files).

cr3cache has to be clean for files to be reparsed and DOM cache rebuilt. Haven't seen any problem yet, but I have no idea if there may be some side effect (like mappings from DOM to original file offsets that this may screw...)

It's ugly, as it's hacking the DOM so that later render/UI problems don't happen, instead of fixing the render/UI problem (but I tried doing this, checking the tap position was in the rect area of the link, which may not be a rect... with no success - and the fix at this level may be less simple than this hack).
Would that ugly hack be accepted ? (no problem if not!).

**Comment by houqp** [comment]
Yeah, this seems a little bit too hacky ;) I recall seeing similar issue reported before where a list of footnotes make it really hard to do page turning. I would expect the clickable area to be restricted to the link text too.

Looking at crengine's source code, it's only comparing Y in ldomNode::elementFromPoint in the lookup code path. Perhaps we can change it to compare X too at the end?

**Comment by poire-z** [comment]
I checked, but no, elementFromPoint is just used to find the full-width block of lines (p, div or li) where the tap is in.
But it lead me to the processing that is done after that in ldomDocument::createXPointer( lvPoint pt), and I think i found a quite simple solution.
I'm going to open a PR on crengine, so we can discuss it there.
