### ISSUE TITLE
Problem with em dash and dictionary —

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2413]
* KOReader version: last nightly version
* Device: Kobo Mini

#### Issue

If the word you press to open the dictionary is beside an em dash **—** both words will be selected. In addition to that, the dictionary will see it like a single word, without dash.
For example, when pressing in _could_ it will select _could_—_and_ and the word that the dictionary will try to look for will be _couldand_.
Or when pressing the word _into_, _mothers_—_into_ will be selected and the word that the dictionary will try to look for will be _mothersinto_.

![reader_2016-dec-07_130021](https://cloud.githubusercontent.com/assets/18194241/20968436/d5d63f4a-bc84-11e6-93f8-5f8c687f304a.png)

**Comment by Frenzie** [comment]
Actually #2411 happens to include some improvements in this area, cf. https://github.com/koreader/koreader/pull/2411/files#diff-cad628d67db4dba7c2bf2ed81f582816R83

**Comment by poire-z** [comment]
#2411 won't help in this case.
In frontend code, we just get what crengine or pdf engine decided what was the word at hold position, so we will get "mothers-into". My cleanSelection would may be remove that dash, so it's the same as before. And we wouldn't know there, if we had to decide to split, what side of the dash to keep (or we would have to do some calculation with x/y, original selection coordinates and length... vs hold position comparisons ...)
I think it would need to be solved into crengine and/or pdf engine.

**Comment by houqp** [comment]
How do you logically decide whether to split the dashed word or not? For example, you won't want to to split `open-source` right? I think the solution to this is not as easy as always split word lookup by dashes.

**Comment by poire-z** [comment]
For these rare cases, there's always the solution, once the lookup is done (and failed), to hold the word on the dict window : this will popup a widget where you can edit it, remove the wrong word, and launched a new lookup with that.

About splitting on dashes, may be there are some rules for epub editors on using different kind of dashes for these different situations. And even if there are, we'll probably get lots of books that don't respect them.
(http://epubsecrets.com/avoiding-bad-punctuation-breaks-in-ebooks.php)

**Comment by Frenzie** [comment]
@houqp Open-source is a hyphen, not a dash—this is an em-dash–and this is an en-dash.

Hyphens incorrectly used as dashes you don't know (unless they're doubled or tripled--like so), but at least for Western European languages you can and should split on em-dashes and en-dashes.

**Comment by houqp** [comment]
Interesting, I don't even know how to type em-dash and en-dash with my keyboard ;P

Like @poire-z said, it's a bug in crengine. I like the idea of making lookup word editable too.

**Comment by Frenzie** [comment]
The `--` and `---` I referred to are the traditional (pre-Unicode) LaTeX ways (Ligatures = TeX). You could also use `\textendash` and `\textendash`. I prefer to just type the character. =P

If you use the compose key ([I recommend Caps Lock](http://fransdejonge.com/2013/02/compose-key-on-xfce/#comment-44743)) then it's <kbd>Compose</kbd>, <kbd>-</kbd>, <kbd>-</kbd>, <kbd>-</kbd> for em-dash and <kbd>Compose</kbd>, <kbd>-</kbd>, <kbd>-</kbd>, <kbd>.</kbd> for en-dash.

For a more handicapped OS there's the [wincompose](https://github.com/SamHocevar/wincompose) crutch. Those of us who grew up with Windows 3 and 9x still remember many of the codes like <kbd>Alt</kbd> + <kbd>0150</kbd> for en-dash and <kbd>Alt</kbd> + <kbd>0151</kbd> for em-dash. (I particularly knew the range 022x range for ë, ï, etc by head.) I think those combos probably still work, but they seem to have been largely forgotten. And there's always the character map.

On Mac I think there's a bunch of rather useful stuff under <kbd>Shift</kbd> + <kbd>Option</kbd> (cf. [Wikipedia](https://en.wikipedia.org/wiki/Option_key#Alternative_keyboard_input)), but I haven't used one of those in forever.

**Comment by poire-z** [comment]
> I like the idea of making lookup word editable too.

It's already there :) https://github.com/koreader/koreader/commit/d34a7fb355e73814669a6c373664c31bc178c449#diff-d62cc01ac3a92ec2624c563aa3e16596R108

**Comment by poire-z** [comment]
Mentionning here (in koreader/koreader issues) a PR i made to koreader/crengine, that would solve this issue (and a few others):
https://github.com/koreader/crengine/pull/69
