### ISSUE TITLE
Back to last book from file manager

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2415]
I think it would be very usefull additional icon in file manger menu to go back to last reading book.
https://github.com/koreader/koreader/issues/1761#issuecomment-184693438.
It's one of FR: "When you are in file manager you can not go back to the book you have been reading - there should be back to read arrow next to home icon. I know there is History, but you need to make two taps to go there and another one to choose the book."

In my test environment, it works pretty well :)

![1](https://cloud.githubusercontent.com/assets/22982594/21016935/d08e2064-bd67-11e6-864b-c67d4da5fa82.png)

Any suggestions?

**Comment by KenMaltby** [comment]
It may be just me but I can't see using up valuable menu space, to save three logical taps on a touch screen.  Maybe it is a generational thing, I don't expect everything to be dead easy.

**Comment by Frenzie** [comment]
Could you explain your use case a bit? I can definitely understand quickly switching between a couple of documents from the reader, but I don't understand going to the file manager just to open the same book right back up again.

**Comment by AlanSP1** [comment]
You can change your mind, for whatever reason. Also, you may went in file manager by mistake (wrong tap, something like that).

In MS Windows each window has close option.

Just thinking aloud...

**Comment by houqp** [comment]
why not just put another menu entry`open last opened file`  into the default menu tab? It's also just two taps away and it does not clutter the menu tabs.

**Comment by Frenzie** [comment]
@houqp That's basically what I had in mind when with "quickly switching between a couple of documents from the reader", which would pretty much have the side effect of adding that to the file manager pokeball menu anyway. ;)

**Comment by houqp** [comment]
Yeah, adding it to pokeball tab sounds better :)
