### ISSUE TITLE
Kobo Aura 2nd edition not recognised

### ISSUE THREAD

**Issue by gorlan** [koreader/koreader#2418]
* KOReader version:   koreader-nightly-20161120
* Device:    kobo aura 2nd edition

my kobo aura 2nd edition is not recognized by koreader. I modified in file "/koreader/frontend/device/kobo/device.lua" the existing entries for kobo aura (lines 89-97 and 344-5):

  -- Kobo Aura:
       local Kobo**Star** = Kobo:new{
       model = "Kobo_**Star**",
       hasFrontlight = yes,
       **touch_alyssum_protocol = true**,
      display_dpi = 212,
       -- the bezel covers 12 pixels at the bottom:
       viewport = Geom:new{x=0, y=0, w=758, h=1012},
  }

elseif codename == "**star**" then
return Kobo**Star**

I'm no expert at all, I'm no programmer, I don't know if other parameters needs to be changed but at first look it seems working.

**Comment by Frenzie** [comment]
Sounds good, except you'd need to add rather than modify. Could you send a pull request or would you rather I do it?

**Comment by houqp** [comment]
Nice, if you are not a programmer, then it really speaks something about how much flexibility Lua brings to the table :) I am impressed.

**Comment by gorlan** [comment]
I'm not able to write it in the correct way, especially following programmer's and project's rules, so I leave it to experts. As I said I don't know if there are other parameters to correct (viewport,...) and maybe if there's someone else with an Aura 2nd edition and better knowledge then mine could help.
I thank you again for your great job in developing Koreader.

**Comment by gorlan** [comment]
Hi guys,
after some more testing I've found that highlighting doesn't work properly with settings I've suggested.

       touch_alyssum_protocol = true

Instead using same touch settings as kobo aura one 

        touch_probe_ev_epoch_time = true,
	touch_phoenix_protocol = true,

highlighting works correctly. Maybe it's because Aura 2nd edition and Aura One should share some firmware family (Mark6). As I already said I'm no expert, I only share my experience, sorry for creating confusion.

**Comment by djalma2k** [comment]
@Frenzie I'm currently testing a kobo aura 2 with:
Firmware  4.6.9995
KSM 08 with patch KSM08_ext_aura_one (v5b)
KOreader v2015.11-1419 ( 2697a30 )

And Imho this should be changed to:
```
local KoboStar = Kobo:new{
     model = "Kobo_star",
     hasFrontlight = yes,
     touch_probe_ev_epoch_time = true,
     touch_phoenix_protocol = true,
     display_dpi = 212,
}
```
The bezel do not cover any of the bottom part of the screen... other thing could be the consideration that the bezel somehow hinder the finger recognition in this part of the screen but in this case the same happens with the upper part.

O/T: @Frenzie About your "petition" here (https://www.mobileread.com/forums/showpost.php?p=3610669&postcount=26) I'm unable to make dropbear get recognize by KSM in this model...

**Comment by Frenzie** [comment]
@djalma2k There's no bezel? Fine by me. :-P

https://github.com/koreader/koreader/blob/3e19ff81ce4ca7c7c56a47bc5012048388942259/frontend/device/kobo/device.lua#L111-L119

I think KSM automatically uses the dropbear from vlasovsoftlauncher, btw.

**Comment by djalma2k** [comment]
About the O/T: Yep, I know it. The glo hd works with a current and an "oldie" version of the vlasoft's software but something happens with aura 2 that it don't want work :(

**Comment by djalma2k** [comment]
@Frenzie Well after rechecking using a glo hd I'm sure my suggestion is correct (about the lowest border of the screen) but I find out that maybe the screen (aura 2) "could being eated" in the left and right sides by 2-3 pixels each side. If the crash.log is correct: 758 X 1024 is the true resolution?¿?
In this case the right value could be:
` viewport = Geom:new{x=2, y=0, w=756, h=1024},`
isn't it?, but the the thing is that the following image seems displaced to the right when I aplyied the zoom adjusting it to fit the page width
( I did a trial-error probe using this image:
https://s18.postimg.org/atpbfv7nt/testaura.jpg )
@poire-z iIf my testing probe is correct, then the glo hd upper border seems (to me :P ) that could be corrected by at least 1-2 pixels. 
` viewport = Geom:new{x=0, y=2, w=w, h=h},`

Anyway this last post is fine tuning, the solution without the viewport "limitation" seems fine to me.

**Comment by Frenzie** [comment]
> in the left and right sides by 2-3 pixels each side. If the crash.log is correct: 758 X 1024 is the true resolution?¿?
In this case the right value could be:
viewport = Geom:new{x=2, y=0, w=756, h=1024},

Actually if it's 2 pixels on *each* side then that should be x=2, w=754 (as in 758-2-2).

> If the crash.log is correct: 758 X 1024 is the true resolution?¿?

You didn't attach the file, but that would be the "true" resolution reported by the hardware, yes. Whether the hardware is just spinning a tale for some reason or whether the bezel covers it is something you can only find out by splitting open the device, which I wouldn't recommend. :-P

The picture looks to me like it scales along nicely and should be centrally aligned.
![screenshot_2017-11-22_19-52-12](https://user-images.githubusercontent.com/202757/33144840-afa1d35e-cfbe-11e7-9c64-aa72e13a1113.png)

**Comment by poire-z** [comment]
> the glo hd upper border seems (to me :P ) that could be corrected by at least 1-2 pixels.

I did some tests, with [testresolutionwidget.lua.txt](https://github.com/koreader/koreader/files/1497393/testresolutionwidget.lua.txt) put as frontend/ui/widget/testresolutionwidget.lua and in frontend/apps/filemanager/filemanagermenu.lua added in Developer options:
```
            {
                text = _("Test screen resolution"),
                callback = function()
                    local TestResolutionWidget = require("ui/widget/testresolutionwidget")
                    UIManager:show(TestResolutionWidget:new{})
                end,
            },
```
And indeed, looking straight vertically at the screen, the 2 top first pixels are hidden by the bezel.
But if you tilt the device 20°, you can see them.
(the left side is fine - I was too lazy to add right and bottom in this test)

The thing is that if you paint all the screen black, and in an ideal world where black would really mask the frontlight, you would still see some white and light from the 2 top lines.
So I don't know how it is for other devices with bezel, and if this should really be fixed (it has never bothered me - except may be when i was making both top and bottom menu look alike, and I believe I was a bit surprised to not see the top menu's top border - but I didn't bother about it).

**Comment by djalma2k** [comment]
Ok, I tested them following your suggestion and it confirms my previous test. My final conclusion/"subjective opinion" is for Aura 2:
```
11/22/17-22:42:20 INFO  initializing for device Kobo_star
11/22/17-22:42:20 INFO  framebuffer resolution: {
    ["h"] = 1024,
    ["w"] = 758
}
```
`viewport = Geom:new{x=1, y=0, w=756, h=1024},`
Maybe someone could object this and think that he needs to tilt the device a little bit...and he maybe prefer something like:
`viewport = Geom:new{x=2, y=0, w=754, h=1024},`

And for Glo HD:
```
11/22/17-22:24:54 INFO  initializing for device Kobo_alyssum
11/22/17-22:24:54 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072

```
`viewport = Geom:new{x=0, y=2, w=1072, h=1446},`
If you really want to see the upper line of the GUI without any tilt (90º) ---> |_ , or the clear point of intersection (Upper horizontal line vs ~-5º line) generated by your test):
`viewport = Geom:new{x=0, y=3, w=1072, h=1445}`
but I prefer the 1st option.

> Actually if it's 2 pixels on each side then that should be x=2, w=754 (as in 758-2-2).

:((... I was thinking about this format (x1,y1, x2,y2) .... :/ :P somehow it made sense in my mind xD I ignored the "W" and the "H".... ://

**Comment by djalma2k** [comment]
> The thing is that if you paint all the screen black, and in an ideal world where black would really mask the frontlight, you would still see some white and light from the 2 top lines.
> So I don't know how it is for other devices with bezel, and if this should really be fixed

When you are using the aura 2, and you are using the night mode, you still can see a white line at the edge of all sides and below the bezel when you tilt your device to the right direction. I think that it is the light reflected against "the cristal layer" at the end of the screen and with a width that seems proportional to the thickness of the crystal. In the glo hd this don't happens. On other hand in the glo hd, you only realize that it is happening when you are using the night mode or with dark images...

**Comment by poire-z** [comment]
> On other hand in the glo hd, you only realize that it is happening when you are using the night mode or with dark images. in the glo hd it could [harm]. It's basically a preferences matter...

I tested it with `viewport = Geom:new{x=0, y=2, w=1072, h=1446},`. No real visual differences in general use (except you notice the top menu top border - because there is some white above it). But when you set a black image screensaver, you see the 2-pixel white line at top, and you see it only on top when tilting the device in every direction.
(Or it would need the off-viewport area to be painted black on startup - so it feels like black material).
So my preference would go to not change it for Glo HD.

I wonder how it is on the H2O with its 11 pixels y-offset: is the bezel material nearest to the screen (than on the glo HD) so that you don't see any of the white (on the y=0->11 area) at all when tilting the device?

**Comment by Frenzie** [comment]
The official bezel is 10 pixels, but in reality it's something more fractional like 10.6. I originally put it at 10 because I preferred it that way, but someone else later decided to change it to 11. I imagine that physical tolerances in manufacturing might also cause slight variations.

You only notice it if you examine it under an angle, so 11 isn't objectionable as a default.

**Comment by poire-z** [comment]
So, if there were no viewport defined, and you would display a black picture starting at 10, and let 0-9 white, you wouldn't see at all the 0-9 white no matter how you tilt your device ?

**Comment by Frenzie** [comment]
Not on my device, anyway. If you can actually look under the bezel on other devices maybe it has something to do with the H2O being watertight?

**Comment by poire-z** [comment]
OK, so it's really 10 invisible/dead pixel lines, unlike these 2 pixel lines on Glo HD one can see when tiltling only 20°.

**Comment by Frenzie** [comment]
Yes, it's 10 completely invisible pixels, which for all I know are just a lie, plus a half-obscured 11th pixel which you only see when you put the device in front of you on a desk or if you purposefully examine it.
