### ISSUE TITLE
Incorrect ASCII art display in text files

### ISSUE THREAD

**Issue by GeneralFailer** [koreader/koreader#2422]
* KOReader version: koreader-nightly-20161120
* Device: Kindle Touch

#### Issue
ASCII art in [this file](https://github.com/koreader/koreader/files/652897/ASCII.bug.txt) is displayed completely broken, I think the app even detects a page break in it somehow. It seems to look fine in a HTML file.

**Comment by houqp** [comment]
CREngine tries to be smart and detect document structure within a txt file using heuristics. So it definitely will not play nice with ascii arts. In HTML mode, it just use HTML tags for document structure, so it will not try to interpret ascii art.

**Comment by GeneralFailer** [comment]
OK then, I guess.

**Comment by Frenzie** [comment]
Iirc you might be able to disable this behavior in `data/cr3.ini`, although atm I can't find what settings there are or anything.

**Comment by houqp** [comment]
If there is such a setting, I prefer we turn it off by default, most of the time the heuristic is wrong anyway...

**Comment by Frenzie** [comment]
Ah, I was kept from working on #1607 and forgot all about it later (plus I wasn't entirely sure it should be in the GUI), but that's what I'm talking about.

**Comment by houqp** [comment]
Nice, so all we have to do is setting `crengine.file.txt.preformatted` to false?

**Comment by Frenzie** [comment]
False is the default. Sorry, I should've linked to https://github.com/koreader/koreader/issues/1607#issuecomment-135968260 but I was on my phone. It's not perfect either way but it disables most of the cleverness.
