### ISSUE TITLE
Light control mod and swipe up/down

### ISSUE THREAD

**Issue by Yaretzki** [koreader/koreader#2425]
I'm using this great light control mod prepared by ycrichard on my kobo glo HD since it is native in koreader builds (adjusting light level by swiping along left edge).
After last update I found that swiping up change light setting as usual but also I go to next page. When I swipe down, light control works great but at the same time I go to previous page. That never happened before and adjusting light worked perfectly.
After update (last build or the one before last) I found new gestures: up - to go to next page and swipe down - to go to previous page. Mentioned 1 finger swipes work on all screen area and interfere with light adjustment swiping along the left edge.
I'm not sure if up/down single finger swipe gestures were implemented before, I found them when I started to have problem adjusting light.
To clarify, now 1 finger swipes working to change pages are:
- Swipe up or left for next page
- Swipe down or right for previous page
Changing tap zone doesn't solve problem.

**Comment by AlanSP1** [comment]
@houqp  maybe there's problem with this PR: https://github.com/koreader/koreader/commit/0c49b915de69b259a7f40eb04affd8e3a12e3eb7

**Comment by seacatwu** [comment]
kobo aura h2o also have this bug

**Comment by houqp** [comment]
Is this also happening to PDFs?

**Comment by Yaretzki** [comment]
After last nightly build everything works fine. There is no more interference with light control gestures and swipe up/down.
