### ISSUE TITLE
FR: Bookmark browsing mode in EPUBs

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2429]
* KOReader version: v2015.11-762
* Device: Kindle PPW3

Does the Bookmark browsing mode works with pubs? I can get it working with pdfs files, but it isn´t working with epub.

**Comment by houqp** [comment]
Yes, it should work with epubs. Are you getting an empty bookmark menu?

**Comment by Eduardomb22** [comment]
I mean the bookmark browing mode. I can get into this mode by long press the right corner of the screen. It is working fine with pdf but I can´t get it working with epubs
The bookmark menu is fine with epub and pdfs, but this mode isn´t working
Did I made myself clear?

**Comment by houqp** [comment]
Ha, that's the flipping mode. Yeah, it's only implemented for pdf and djvu right now.

**Comment by Frenzie** [comment]
Effectively implemented in #3389 through a different dialog.
