### ISSUE TITLE
Allow transitioning from *sleep* to *power off*

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2431]
Some users might put the device to sleep by mistake and then try to power it off directly.

This will currently fail.

**Comment by robert00s** [comment]
I think this is done by @poire-z in #3572. You can set deferent settings for sleep and power off.

**Comment by poire-z** [comment]
Not sure this issue is about screensaver.
I guess it's about, after having put the device to sleep with a short press on the power button, to be able to power it off with a 3-seconds press.
Currently, one have to short press again to wake it up, and the long-press it to power it off (which does not sounds too complicated to me :)

**Comment by robert00s** [comment]
@poire-z  But can it be handled by KOReader?
@baskerville What did you mean exactly?

**Comment by poire-z** [comment]
On Kobo, it is handled by KOreader:
https://github.com/koreader/koreader/blob/0d66ea7555accfd0c231f04d7754d85d84fed6e2/frontend/ui/uimanager.lua#L87-L107
https://github.com/koreader/koreader/blob/0d66ea7555accfd0c231f04d7754d85d84fed6e2/frontend/ui/uimanager.lua#L55-L65

So, solving this issue would need some trickery around these (but I won't try it :)

**Comment by robert00s** [comment]
Ok :) I don't have Kobo so I can't help.

**Comment by avsej** [comment]
@Frenzie @poire-z @pazos This patch breaks power button on Cervantes! Is it possible to keep kobo-specific fixes separately?

**Comment by Frenzie** [comment]
@avsej Could you be a bit more specific? This is Kobo-specific code.

**Comment by NiLuJe** [comment]
@Frenzie : From a very quick glance, I *think* the Cervantes/Sony blocks in uimanager rely on the "Resume" event, which went poof with this ;).

**Comment by Frenzie** [comment]
Indeed. We've got a case of confusing design or just a quick hack from years ago spreading out like an oil spill here. :-P

**Comment by pazos** [comment]
> We've got a case of confusing design or just a quick hack from years ago spreading out like an oil spill here. :-P

Indeed. I might be still confused now as I don't understand why this code path should be reachable only for kobos.

**Comment by Frenzie** [comment]
The split in Press/Release is fine and generic enough in theory, but deciding that "Resume" is the correct action to take based on that input event is UIManager logic infiltrating in the Input module.

Back a few years ago this lack of separation was "Kobo only" and I just hadn't quite caught up to that fact. ;-)

**Comment by avsej** [comment]
> Could you be a bit more specific?

My Cervantes 4, unable to resume after suspend with this patch. I had to reboot it. But even after reboot it does not wake up after suspend. While the change is kobo-specific, the fix goes into common code path, and affect other devices.

**Comment by Frenzie** [comment]
The change isn't Kobo-specific exactly. The common code path should definitely look the other way architecturally speaking. ;-)

Anyway, thanks for reporting!

**Comment by pazos** [comment]
Uh-oh. I think that I understand now: instead of returning "Resume" from input.lua return "PowerPress | PowerRelease" and let UiManager handle that?

**Comment by Frenzie** [comment]
Right, `Input` incorporates a couple of hacks related to converting keyboard combos to events but in principle it should just make sure input is turned into something that's digestible by other parts of the program. `UIManager` handles suspend/resume/shutdown with the aid of `Device`-specific implementations.

The original hack from 3066c86e38c8297c4c534a31c9631bb8bd6535cf made a lot more sense than the spaghetti monster we ended up with in subsequent rewrites:

```lua
if ev.value == EVENT_VALUE_KEY_RELEASE then
        if keycode == "Light" then
            return keycode
        elseif keycode == "Power" then
            -- Kobo generates Power keycode only, we need to decide whether it's
            -- power-on or power-off ourselves.
            if self.device.screen_saver_mode then
                return "Resume"
            else
                return "Suspend"
            end
        end
    end
```

It's still breaking the abstraction in a way I'd prefer to avoid in `Input`, but it does so sensibly.
