### ISSUE TITLE
Tap zones regression

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2432]
I use the following tap zone definitions in `defaults.lua`:
```
DTAP_ZONE_MENU = {x = 1/3, y = 0, w = 1/3, h = 1}
DTAP_ZONE_FORWARD = {x = 2/3, y = 0, w = 1/3, h = 1}
DTAP_ZONE_BACKWARD = {x = 0, y = 0, w = 1/3, h = 1}
DTAP_ZONE_CONFIG = {x = 0, y = 0, w = 0, h = 0}
DTAP_ZONE_MINIBAR = {x = 1/3, y = 7/8, w = 1/3, h = 1/8}
DTAP_ZONE_BOOKMARK = {x = 7/8, y = 0, w = 1/8, h = 1/8}
DTAP_ZONE_FLIPPING = {x = 0, y = 0, w = 1/8, h = 1/8}
DDOUBLE_TAP_ZONE_NEXT_CHAPTER = DTAP_ZONE_FORWARD
DDOUBLE_TAP_ZONE_PREV_CHAPTER = DTAP_ZONE_BACKWARD
```
And after having upgraded from c71b176 to a8dd8c6, I can no longer toggle the mini bar.

**Comment by Frenzie** [comment]
All commits in between (no time to look at it but this should help): https://github.com/koreader/koreader/compare/c71b176...a8dd8c6

**Comment by houqp** [comment]
I will take a look

**Comment by asampal** [comment]
I'm seeing the problem as well.

**Comment by houqp** [comment]
Can anyone confirm that this is also happening to PDFs?

**Comment by houqp** [comment]
@baskerville can you give the latest master a try?

**Comment by baskerville** [comment]
I've tried and I'm still experiencing the same issue.

**Comment by houqp** [comment]
Weird, I cannot reproduce this on emulator and kobo at all. @baskerville @asampal , this is also happening to PDFs right? Does it happen with the default tap zone setting too?

**Comment by baskerville** [comment]
It works if I use the default tap zone settings…

**Comment by baskerville** [comment]
The problem comes from the fact that, in my settings, `DTAP_ZONE_MENU` and `DTAP_ZONE_MINIBAR` overlap and the menu takes precedence (previously it wasn't the case).

I can *fix* it by making the two zones non-overlapping.

**Comment by houqp** [comment]
Good catch, i only copied your DTAP_ZONE_MINIBAR setting. For now, it's easier for you to update your local defaults. The order between menu and minibar tap zone is kind of arbitrary. I will submit a patch to change it to the old behavior.
