### ISSUE TITLE
FR Configurable option to bold / unbold books with sdr in file manager

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2439]
* KOReader version: Last nightly builds
* Device: Kobo Mini

#### Issue
One the last changes in the code marks in bold in the file manager all the new books or images that have not been open. That is good and I like it. Little problem here is that almost all my books are in bold, so right now I wouldn't be able to identify newer books just because of the bold, because almost everything is in bold.
Is there any way to mark all the books as open? So only the new books that I copy to the reader since today appear in bold until I open them?

**Comment by retrue** [comment]
I have just discovered that the new feature that use bold to mark all the new books just check if the document has a sdr directory associated. 
No sdr - bold typeface
Sdr - regular typeface
If you purge/delete the sdr, the document name goes back to bold.
I wonder if this feature is so useful as it should.

**Comment by houqp** [comment]
KOReader stores everything it knows about the book in sdr folder, so if you delete the directory, you are purging KOReader's memory about the book. The answer to your question is to create sdr directories for books that you don't want to be shown with bold font.

**Comment by retrue** [comment]
In that case I would prefer the other way around: That only books with sdr folder were shown in bold.

**Comment by KenMaltby** [comment]
I carry over 7000 ebooks on my device.  While I have a number that have SDR, the larger number haven't yet been read on that device.  So, if we must do this I would also prefer that it be those that have SDR, be emboldened, not those without.

**Comment by houqp** [comment]
@poire-z originally implemented it as bold for books with sdr. I later changed it to the current behavior. Looks like we have a very different setup ;) I don't put all my collection to the device, instead, i only put my current to-read list. That's why I prefer the current behavior. I think it's better to make this a configurable option for now.

**Comment by KenMaltby** [comment]
So, maybe options to:  "Make unopened files bold"  and "Make opened files bold"  with checkmarks when selected.  Without one of them checked, they would display as they do now.  Just an idea.

**Comment by retrue** [comment]
@houqp Could you reopen this issue, please, so the feature request is not lost among the closed issues?

**Comment by retrue** [comment]
Where is the new setting to show opened book name in bold?
It is not in the menus, not in Tools --> Advanced settings and not in the lua file with the preferences settings.
I guess that, if I am not wrong, the foundation to the code to possibilite the new setting is there but the new setting is not yet.
Imho, ideally, there should be three options: bold typefont for new books, bold for already opened books and regular typefont for everything.

**Comment by houqp** [comment]
You can change the behavior by setting `show_file_in_bold` to either `"opened"`, `false`. By default, it shows new files in bold. See https://github.com/koreader/koreader/pull/2457

**Comment by KenMaltby** [comment]
How do you set it to not show any in bold?

**Comment by retrue** [comment]
+    -- set to false to show all files in regular font
+    -- set to "opened" to show opened files in bold
+    -- otherwise, show new files in bold
+    local show_file_in_bold = G_reader_settings:readSetting("show_file_in_bold")

**Comment by houqp** [comment]
You need to add the setting to `reader.settings.lua`. If you don't want the bold highlight, just set the value of `show_file_in_bold` to `false`.

**Comment by retrue** [comment]
Thanks  =)
