### ISSUE TITLE
Crash when selecting Book information on images.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2440]
* KOReader version: Last nightly versions
* Device: Kobo Mini

#### Issue
KOReader crashes when quering for Book information on an image.

#### Steps to reproduce
Select an image on the file manager (I have tried with png and jpg). Long press on the image file. In the menu that appears, taps on Book information.

#### Attached files.
[crash.log.txt](https://github.com/koreader/koreader/files/663060/crash.log.txt)
![filemanager_2016-dec-20_083233](https://cloud.githubusercontent.com/assets/18194241/21342047/0f83b582-c690-11e6-90bd-f8aaaf60f061.png)

**Comment by robert00s** [comment]
Book information should be disabled when selecting images after fix.
