### ISSUE TITLE
Can't find books with "Find a book in calibre catalog"

### ISSUE THREAD

**Issue by asampal** [koreader/koreader#2442]
* KOReader version: g1a83eb5
* Device: Kobo Aura One FW 4.2.8110

#### Issue
Can't find a book in Calibre OPDS catalog

#### Steps to reproduce
- Start content server on Calibre 2.74
- In KOReader's File Manager, with wifi on, choose "Find a book in calibre catalog"
- Search for book which was verified to be there by browsing the local OPDS Calibre catalog
- In the resulting search dialog, enter the book name, or part or it and choose "Find Book"
- Popup results with "No match for <search text"

**Comment by asampal** [comment]
After poking around, it seems this isn't an action that functions through OPDS, as was my initial assumption, but rather through a file. Could someone clue me in as to what file is involved here and how is it generated by Calibre? It's not clear to me if what I see failing on my KA1 is due to a bug or a user error.

**Comment by KenMaltby** [comment]
Calibre generates a "metadata.calibre" when it is used to send files to a device.  It updates the file as later files are sent to that device.  (This is not the case when you use the content server and the OPDS function.) It only works if you allow calibre to create its own file structure on your device.  

The Calibre OPDS catalog provides the catalog listing that it generates with no search function, as far as I know.  (Such a search function was a feature request, not too long ago, but I don't remember anything coming of it.)

**Comment by Frenzie** [comment]
I'll close this now. I find the various calibre-related processes confusing too, but they all work. I think the particular one relevant here may be [this](https://github.com/koreader/koreader/wiki/Calibre-wireless-connection) one.
