### ISSUE TITLE
New Go to page/location widget 

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2444]
What do you think about new goto page/location widget?
After tap on progress bar we change the page/location immediatly.
![1](https://cloud.githubusercontent.com/assets/22982594/21364364/cd037042-c6f0-11e6-9c6a-3d2bfb7b8bc4.png)
![2](https://cloud.githubusercontent.com/assets/22982594/21364367/cf3f8468-c6f0-11e6-92e2-0b98fcb28860.png)

**Comment by AlanSP1** [comment]
Looks great, much better than before.

**Comment by Eduardomb22** [comment]
much better

**Comment by Frenzie** [comment]
I think adding -10 and +10 to the existing dialog could be interesting (I
see no point in +1 and -1), but I think the primary purpose of the dialog
is to enter a number. Like in a scanned document that didn't have ToC
metadata added.

**Comment by Eduardomb22** [comment]
I like the +1 -1 button, but this is my opinion

**Comment by KenMaltby** [comment]
It would make it possible to have the quick, but imprecise, tap on the "progress bar" be easily refined to the page wanted.

**Comment by houqp** [comment]
This looks like a useful feature for quickly flipping through a book. However, I think we should still keep the page number input box. For me, 90% of the time I know exactly which page I am jumping to. We can just keep the old input box at the bottom.

**Comment by AlanSP1** [comment]
Yes, that is exactly what I'm thinking (referring @houqp).

If page number is also in box, symbolizing that we can tap on it and enter exact number, it would be the best.

**Comment by Eduardomb22** [comment]
Agree with @AlanSP1 and @houqp

**Comment by Frenzie** [comment]
I think tapping on it would be adding a rather unnecessary extra step and a
regression. At the bottom like @houqp said would be much better.

On Dec 22, 2016 2:34 AM, "Eduardomb22" <notifications@github.com> wrote:

Agree with @AlanSP1 <https://github.com/AlanSP1> and @houqp
<https://github.com/houqp>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/koreader/koreader/issues/2444#issuecomment-268695317>,
or mute the thread

**Comment by robert00s** [comment]
I would like to left widget as small as possible. Adding old input in the bottom will hide almost all page.
First solution:
Tap on page number enable  old input when we need to go to exact page.
Secound solution:
Add new menu item somethink like that:

![1](https://cloud.githubusercontent.com/assets/22982594/21458333/fc74184e-c935-11e6-9ff0-540f892c2bcc.png)

**Comment by Frenzie** [comment]
Btw, one of LibreOffice 5.3's big new features is a Go to page dialog where
you can just enter a number
https://wiki.documentfoundation.org/ReleaseNotes/5.3#Go_to_Page_Dialog

How about just sticking something like -50/-10/+10/+50 underneath the
existing dialog?

**Comment by retrue** [comment]
-25/-10/+10/+25
=P

**Comment by houqp** [comment]
> Btw, one of LibreOffice 5.3's big new features is a Go to page dialog where
you can just enter a number

Welp, looks like we are converging ;)

> First solution:
> Tap on page number enable old input when we need to go to exact page.

This still requires an extra tap to get to the page input box

> Secound solution:
> Add new menu item somethink like that:

I think this is a good solution too :+1: 

In the future, we can add a tiny preview window when user is doing pan gesture on the progress bar too :) page flipping is already taken by another feature in KOReader, how about naming this feature something like `skim document`?

**Comment by AlanSP1** [comment]
We also can have redundant UI, i.e. that we have some mesh of first solution (from new interface tapping on page number opens old dialog for direct page number input) and second, having option for dedicated direct page number entering. Which could, of course, also have button for opening this new method.

Also, if we go this way, we could have setting in options, which dialog is default if we tap and hold on progress bar.

This would ask a bit more programming, but is more universal and people can decide what is more suited to their liking.

From my point of view, I think that we still should have method to input direct page number, however this is implemented.

**Comment by Eduardomb22** [comment]
> From my point of view, I think that we still should have method to input direct page number, however this is implemented.

I agree

**Comment by robert00s** [comment]
Third solution: 
Adding additional button in input dialog e.g. "Skim".
![1](https://cloud.githubusercontent.com/assets/22982594/21462286/78f86dba-c95a-11e6-8783-e8d1edc49362.png)
After select button "Skim" we get widget with progress. 
![2](https://cloud.githubusercontent.com/assets/22982594/21462288/7c3b618a-c95a-11e6-8274-51f190703989.png)

**Comment by houqp** [comment]
I like the third option too :+1:

**Comment by Frenzie** [comment]
The "third" option doesn't contradict the "second' one.

Two menu entries:

* Go to
* Skim mode

And then the individual dialogs would allow switching in between.

**Comment by houqp** [comment]
If we are going to add a menu entry for skim mode, I would suggest naming it as `Skim to` to keep it consistent with `Go to`. `Skim mode` is a better name for the button in the input box :)

**Comment by Hzj-jie** [comment]
Sorry, I have not got the point. Why cannot we add an input box in "Skim mode"?

**Comment by houqp** [comment]
@robert00s did add the switch for precise page number control. If you tap on the page number, it will bring you to the input box for page number.
