### ISSUE TITLE
can not login evernote: plugins/evernote.koplugin/EvernoteOAuth.lua:210:closed

### ISSUE THREAD

**Issue by DrSkyeagle** [koreader/koreader#2452]
* KOReader version: koreader-nightly-20161120
* Device:kindle paperwhite3

#### Issue
can not login evernote: plugins/evernote.koplugin/EvernoteOAuth.lua:210:closed
#### Steps to reproduce
when you login evernote ,it will show code like plugins/evernote.koplugin/EvernoteOAuth.lua:210:closed

**Comment by houqp** [comment]
Likely a duplicate to https://github.com/koreader/koreader/issues/2387
