### ISSUE TITLE
OPDS catalog containing URL with many params in query string are not correctly handled

### ISSUE THREAD

**Issue by seblucas** [koreader/koreader#2458]
* KOReader version: koreader-nightly-20160823
* Device: Android Nexus 5

#### Issue

OPDS catalog containing URL with query string are not correctly handled.

#### Steps to reproduce

With KOReader

 * Add a new OPDS catalog with this url http://cops-demo.slucas.fr/feed.php
 * In this OPDS catalog click on Authors
 * Click on C
 * You'll see a list of 5 authors (not normal)

If you use any other OPDS client (FBReader for example), instead of 5 authors, you'll only see one (.

#### Problem / How to fix

I'm not fluent in lua but the problem should be easy to solve. If you check the source of this page http://cops-demo.slucas.fr/feed.php?page=1, you'll see this kind of link `<link href="feed.php?page=2&amp;id=D" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>`.

To produce a valid XML file, all `&` were replaced by `&amp;`, the problem is KOReader use this URL directly without decoding it (replacing `&amp;` by `&`). That is the cause of the bug.

Note that the `&amp;` are mandatory in the feed, if I use `&` directly, the feed is not valid anymore (you can check with http://opds-validator.appspot.com/)

Note that this was reported by one of my users : https://github.com/seblucas/cops/issues/315

**Comment by houqp** [comment]
Thanks @seblucas for the detailed report! I have submitted a PR to fix this issue :)

**Comment by seblucas** [comment]
Thanks a lot.
