### ISSUE TITLE
Change PDF font

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#2462]
* KOReader version: koreader-nightly-20161120
* Device: Pocketbook touch lux 3

#### Issue

Although reflow works fine (even on scanned) PDFs (can increase, decrease font size), fonts quality are rather very bad.

Here's an example:
https://cloud.githubusercontent.com/assets/12519813/10264009/fc742174-69f8-11e5-96ba-51e83e46509c.JPG 

Possibility to change font in PDFs would be appreciated.

#### Steps to reproduce
Open scanned PDF in Koreader.

**Comment by houqp** [comment]
This is a non-trivia feature. Your example looks bad because the original scanned image has bad quality. To support arbitrary zooming, we might need to do OCR on the full image to recover the actual characters.

**Comment by mwozny123** [comment]
Please don't look at the page structure. 
This was just internet example to show how poor quality fonts they're for scanned documents.
My document is less complicated - just 1 column, the same font (and I think most of the scanned PDFs also have less complicated structure).

Current font quality reminds me look of XIX century newspaper:/

I thought as we have a reflow on scanned PDFs we would be able also to change (/improve) font  quality..

**Comment by houqp** [comment]
It's not related to the page structure. What the reflow engine does is basically split the image into pieces by characters, then scale and reorder those pieces to form a new structure. So the quality of the font is determined by the quality of original scanned images.

**Comment by Frenzie** [comment]
I think this is a really cool idea, but I'll close it because I don't think it's realistically achievable. Or at least not without using a dedicated application like Adobe Acrobat.
