### ISSUE TITLE
The menu entry "Keep Alive" should be ticked when the plugin is active

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2466]
* KOReader version: Last nightly builds
* Device: All of them

#### Issue

The current implementation of the Keep Alive plugin will maintain the keep alive mode when the user close the pop up after pushing the button "Stay Alive". 
The Keep Alive menu entry should be ticked after pushing "Stay Alive" to remind the user that the plugin is active to avoid unnecesary battery drain.
As a side note, the menu entries "Keep Alive" and "Stay Alive" should be renamed as "Keep alive" and "Stay alive" for stylistic coherence.

**Comment by Eduardomb22** [comment]
That would be nice.

**Comment by Hzj-jie** [comment]
Good suggestion, I will make the change.

**Comment by retrue** [comment]
I tested the checked tag for the keepalive plugin and it works well. Closing the issue.
