### ISSUE TITLE
History not working

### ISSUE THREAD

**Issue by hurzl** [koreader/koreader#2468]
* KOReader version: koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-696-g2bc7b01.zip
* Device: 

#### Issue
Files I open don't appear in the history since I installed above version. What went wrong?

**Comment by houqp** [comment]
Not able to reproduce this on my side. I don't recall any change on the history menu. Did you get a blank menu? Have you tried restarting the device?

**Comment by hurzl** [comment]
The date was reset to 2012 and I can't set it, see #2265, so the files appear at the end of the history list.

**Comment by Hzj-jie** [comment]
I have exactly the same issue on my Kobo. You may want https://github.com/koreader/koreader/pull/2459.
