### ISSUE TITLE
Latest release has issues with certificates

### ISSUE THREAD

**Issue by IzzySoft** [koreader/koreader#2469]
* KOReader version: koreader-nightly-20161120
* Device: unrelated

#### Issue

    ERROR: Found multiple signing certificates on koreader-android-arm-linux-androideabi-v2015.11-696-g2bc7b01.apk
    CRITICAL: Failed to get apk signature

#### Steps to reproduce
Try adding the `.apk` to an F-Droid repository. Index won't be compiled, throwing above error message.

**Comment by KenMaltby** [comment]
You could try the latest, or other, from here. http://build.koreader.rocks/download/nightly/

**Comment by IzzySoft** [comment]
The latest one (`koreader-android-arm-linux-androideabi-v2015.11-789-g86e924a.apk`) still has the same issue. Not sure when this started; I can just say the last "official 1.2" (from the `releases/` page) did not have it.

**Comment by KenMaltby** [comment]
It would not be an answer to this issue but it would be interesting if the .apk can install after sigining it with: https://code.google.com/archive/p/easy-apk-dissassembler/ .  There is no need to actually disassemble it, just use the #4 option to sign it.  (I don't know how the program handles signing an apk that is already signed, (it may correct any conflicts), but it didn't throw an error when I just did it.  {I don't have an android device anymore, so I didn't try installing it.}

**Comment by houqp** [comment]
There is a known apk signing issue with the latest release. I am taking a look at it. I would suggest not submitting koreader to fdroid until it's considered ready for broader testing. Right now we are having LuaJIT issues on android platform so it's very unstable (it probably only runs on 50% of the android devices out there).

**Comment by IzzySoft** [comment]
Thanks for the pointers, @houqp – and good to know you're already on it! Waiting for your update then.

Background: I'm not submitting it to F-Droid, I run [my own little repo](https://android.izzysoft.de/repo) – which is intended a.o. to help people without playstore access with apps not in the regular F-Droid repo. You can [find koreader there](https://apt.izzysoft.de/fdroid/index/apk/org.koreader.launcher).

**Comment by gerroon** [comment]
I assume this is the same as https://github.com/koreader/koreader/issues/2437

**Comment by houqp** [comment]
Might be related. The current android builds are signed with both debug and release keys. I made some changes in the build script to strip out debug key before signing. Let's see how it goes.

**Comment by IzzySoft** [comment]
> The current android builds are signed with both debug and release keys.
>> `ERROR: Found multiple signing certificates`

Matches. And indeed might be related. Just let me know when there's a "fixed up" version in ' releases/'  I should give another try.

**Comment by gerroon** [comment]
Is this resolved? Can we get some recent versions of the android builds?

thanks

**Comment by gerroon** [comment]
Any word on this issuie? We have not had an android build for a while.

**Comment by IzzySoft** [comment]
Guess this one can be closed now – or does anyone here still encounter the issue?

**Comment by houqp** [comment]
I believe the build system is still not fully fixed yet :( If someone knows how to resign an APK with a new key, please let me know.

**Comment by KenMaltby** [comment]
When I was making changes to the .apk, probably 20+ times, (before I broke my tablet), I had to sign the modified .apk using EasyApkDisassembler.V1.3.2.  I did nothing to try and deal with the existing signature, and it let me install KOReader with my modifications, (including using my avatar for the KOReader Icon).

**Comment by Frenzie** [comment]
Closing this because I haven't seen any problems anymore.
