### ISSUE TITLE
android version not work

### ISSUE THREAD

**Issue by csJd** [koreader/koreader#2471]
* KOReader version:
* Device:Android 6.0

#### Issue
the last android version installed on android 6.0 can't be launched

#### Steps to reproduce

**Comment by houqp** [comment]
Can you tell us the exact version you tried that's not working and the last working version?

**Comment by ddwust** [comment]
Sorry, I don't konw Koreader android version is not for android phones. It just not work properly on phones.

**Comment by houqp** [comment]
It's still alpha software and only works for 50% of the phones out there, so it's very likely that it won't work for yours.

**Comment by Hzj-jie** [comment]
Do you happen to know your device model?

**Comment by Frenzie** [comment]
Closing now because Android is pretty broken. Refer to #673.
