### ISSUE TITLE
The two finger swipe gesture doesn't work in landscape mode

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2473]
I can bring the *Table of Contents* window with a two finger swipe left gesture in portrait mode but not in landscape mode.

I'm on 2bc1be9.

**Comment by baskerville** [comment]
Unfortunately, this is a hardware problem, specific to the *Aura ONE*. While trying multitouch gestures within *Sketch Pad*, I noticed that the *Aura ONE* had a different behavior than the *Glo HD*: a two-finger swipe along the major axis is seen a single finger swipe (the fake touch point is the average of the two real touch points) on this device. I hoped it was a bug in *Sketch Pad*: unfortunately it isn't (I've checked by analyzing the *evdev* events). This can't be fixed by *KOReader*.

**Comment by houqp** [comment]
It's odd that the driver does it :(
