### ISSUE TITLE
FR: Set the language of a book

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2476]
* KOReader version: any
* Device: any

#### Issue
Some ebooks don't have a language defined in its metadata. In some cases, they have the wrong language defined, e. g. the book is defined as English but it is in German.
I ask for an option in the menu to define the language of a book. This information would be stored in the sdr folder. The book's new language would override the language defined in the metadata of the book if there was one.
Right now, it would be useful when using the Wikipedia. If the metadata doesn't containe a language, the wikipedia tries to search in UND (undefined language). 
But this defining language feature would be useful too for other stuff, for example, a future translator plugin.

**Comment by poire-z** [comment]
The metadata language (document:getProps().language) seems to be used only for 2 things:
- building the list of available wikipedia languages (if setting `wikipedia_languages` has not been manually set in settings.reader.lua) - and there's always a "en" fallback added (see #2393 : _can be read from custom setting "wikipedia_languages", and if not present, it is build with previous logic (document language + ui language (or translator) + "en")_ )
- to find the default hyphenation algorithm (which one can change with the menus by setting another hyph algo that will be stored in the sdr directory and reused later for this book).

So it may be a bit overkill to add this feature.
Also, most of my pdf don't have any language in metadata, and neither do .txt files.
I think it's better to have options to set default or fallback values for individual things that to relies on a possible absent or wrong "language" and the need to set/change one (I have my UI in english, my hyph dict in french that i prefer even for english text, wikipedia_languages with ["fr", "en"] and i prefer the french even if i read english text...)
I'll make a PR with some code I have to set a fallback hyph_alg (useful for me to have my french hyph dict when i'm reading a .txt).
It would be nice to have a way to set wikipedia_languages from the UI, but it looks like quite a bit of work.

**Comment by Frenzie** [comment]
Do StarDict dictionaries define their language? (Regardless whether this can currently be queried through sdcv.)

**Comment by poire-z** [comment]
I don't think they do, at least not in the .ifo file describing themselves, for example:
```
StarDict's dict ifo file
version=2.4.2
wordcount=174222
idxfilesize=3316950
bookname=dictd_www.dict.org_gcide
date=2003.05.13
sametypesequence=m
```
And there's no notion of language in KOReader's dict code, neither in sdcv binary helper:
```
Usage: ./sdcv [OPTIONS] words
-h, --help               display this help and exit
-v, --version            display version information and exit
-l, --list-dicts         display list of available dictionaries and exit
-u, --use-dict bookname  for search use only dictionary with this bookname
-n, --non-interactive    for use in scripts
-j, --json-output        for use in scripts
--utf8-output            output must be in utf8
--utf8-input             input of sdcv in utf8
--data-dir path/to/dir   use this directory as path to stardict data directory
```

**Comment by Frenzie** [comment]
Pity about the ifo specification. I'm aware that sdcv offers no such functionality; I suppose I phrased that badly.

**Comment by retrue** [comment]
What about a plugin that shows the dictionaries installed in the device with the possibility of ticking items in the list to activate or deactivate specific ones?
But that is a different subject and I don't know how difficult would it be.

**Comment by Frenzie** [comment]
Alongside enabling and disabling you could also set the language for the dictionary. Anyway, just trying to figure out if there are other areas where something like book language could be useful. :-)

**Comment by Frenzie** [comment]
@poire-z 

> I'll make a PR with some code I have to set a fallback hyph_alg (useful for me to have my french hyph dict when i'm reading a .txt).

Not just fallback imo. Wouldn't it make the most sense for long-pressing on a hyphenation pattern to set a default?

**Comment by retrue** [comment]
> Not just fallback imo. Wouldn't it make the most sense for long-pressing on a hyphenation pattern to set a default?

The current behaviour to select hyphenation dictionaries I think it is to choose first the language of the book and if there is none defined to choose then the language of the interface.
For most people, me included, who read mostly in a single language, the possibility to set as default a hyphenation dictionary with a long-press is handy and welcomed. However, for people who switches often between languages, the current behaviour is the best one.
In my opinion, if long-press is configured to set as default a hyphenation language, some mechanism/option should be added to preserve the current behaviour. For example, in addition to None, Algorithm, French, English, Spanish, Italian, etc, an option called "Book language" or similar could be added in a way that with a long press could set the current behaviour as default.

**Comment by Frenzie** [comment]
> However, for people who switches often between languages, the current behaviour is the best one.

I switch between four languages on a regular basis, but the language specified by EPUB files only vaguely correlated to the actual language of the book (cf., my strong opposition to #2614). All books from DBNL are "Dutch", for example, which indeed happens to be true for the majority of them. My preferred hyphenation algorithm, which I'd like to set as default, is "none at all, get your filthy paws away from the text you stupid computer algorithm". :-)

Actually I don't care particularly much (in other words, I'm fairly unlikely to implement this myself, at least in the short term) and naturally I completely agree with your remark about "automatic" having to be an available option. My post was prompted by https://www.mobileread.com/forums/showthread.php?t=285878

**Comment by poire-z** [comment]
It may be easy to have both, just like holding on a font name launch a MultiConfirmBox with Cancel/Default/Fallback.
We just need, when setting hyph_alg_fallback, to delete hyph_alg_default (similar the other way around), and to add before https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerhyphenation.lua#L104
```lua
    if not hyph_alg then
        hyph_alg = G_reader_settings:readSetting("hyph_alg_default")
    end
```
No need to reset (remove both settings), choosing any fallback should be enough to have the usual behaviour. Choosing English as fallback is similar as if nothing have been chosen.

**Comment by Frenzie** [comment]
Doing it like the fonts sounds good to me.

**Comment by poire-z** [comment]
Ways to set wikipedia languages and hyphenation directories has been added since, so I think this can be closed.
