### ISSUE TITLE
feature request: PDF "read"-flow

### ISSUE THREAD

**Issue by Tobster85** [koreader/koreader#2478]
* KOReader version: latest
* Device: any

#### Issue
I am thinking of enhancing the PDF reading experience. Reading very individually designed PDFs  is quite hard at the moment because of the need to constantly zoom in and out and move the already enlarged view.

![1 page](https://cloud.githubusercontent.com/assets/22470848/21678198/11f47c88-d33e-11e6-8d29-14ffd09bdfa3.png)

A possible solution could be to select the flow of reading as path **before** actually reading the PDF page. Please see the attached image:

![2 first frame](https://cloud.githubusercontent.com/assets/22470848/21678209/180a7c58-d33e-11e6-80ba-8365af532319.png)
![3 second frame](https://cloud.githubusercontent.com/assets/22470848/21678213/1a95ac04-d33e-11e6-830a-a49692055ba7.png)
![5 final](https://cloud.githubusercontent.com/assets/22470848/21678460/16c82b5a-d33f-11e6-9f6c-6ad96fd92598.png)

Frame 1 and 4 are supposed to be shown in portrait mode.

And then enjoying the read flow:
![6 read flow](https://cloud.githubusercontent.com/assets/22470848/21678243/44fc83c8-d33e-11e6-968b-1a9032501fc8.png)

**Comment by Frenzie** [comment]
Self-evident to a person, but I have no idea how this could be automated (at least without gobs of data and processing power in a machine learning context).

**Comment by Tobster85** [comment]
Hi Frenzie,
this feature does not need to be automated, as the read"flow" is generated by user input before reading the "flow".

**Comment by Frenzie** [comment]
Still not trivial but theoretically that's definitely doable. :+1:

**Comment by KenMaltby** [comment]
So you want to have the user able to "map" a sequence of areas (user defined, for each page of the PDF) that a "next page" gesture would have display full screen, in the order specified.

**Comment by Tobster85** [comment]
Exactly! This could be a solution for reading complex layouted and large formated PDF files (like magazines) on our small screen e-readers.
If I can support you with more details of the idea, please let me know.

**Comment by Frenzie** [comment]
I think the bigger problem is finding something with both the time and the will to specifically implement something like this. :-)

**Comment by houqp** [comment]
@Tobster85 do you expect the user to manually tag the flow for each page?

One thing would be nice though is to upload all these manually labeled flows to our server so we can train an machine learned model ;)

**Comment by Tobster85** [comment]
Yep, I think it would be suitable to map the flow for every page before actually reading it. If you get used to it, it could be a matter of seconds.
The alternative is to scroll and zoom WHILE reading PDFs (like it is now) and this option is even more uncomfortable to use ;)

**Comment by Frenzie** [comment]
While not quite the same, https://github.com/koreader/koreader/releases/tag/v2020.12 should have taken care of most of it.
