### ISSUE TITLE
Long press status bar can't open "go to" menu

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2479]
* Device:KOBO aura h2o

latest version!
Long press status bar can't open "go to" menu.

**Comment by retrue** [comment]
It happens too with Kobo Mini since some nightly versions ago.

**Comment by AlanSP1** [comment]
Maybe related with this: https://github.com/koreader/koreader/pull/2460 It was implemented 29.12.2016.

**Comment by seacatwu** [comment]
@AlanSP1  Maybe before this version.

**Comment by robert00s** [comment]
After this commit long press status bar can't work: 0c49b915de69b259a7f40eb04affd8e3a12e3eb7
On Kindle PW3 also don't work.
@houqp Can you check it?

**Comment by houqp** [comment]
@robert00s good catch, it's because the hold event is eaten by readerhighlight widget before passing to readerfooter. I will migrate readerhighlight to tap zone, that should fix this issue.
