### ISSUE TITLE
Housekeeping: some language things

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2482]
This is basically just a note to self but I probably won't have time until the 12th.

```
Line thick. Current value: %1
```

> Line thickness?
> by kingu, 4 hours ago 

> @kingu Could also be that line height is meant; I'll investigate in a few days.
> by Frenzie, a few seconds ago

**Comment by Frenzie** [comment]
@apletnev I assume it's meant to be line thickness, but note that line width is also common (e.g., in SVG and canvas elements). Or is it something else?

**Comment by apletnev** [comment]
@Frenzie i think line width is to complicated because it is like programmer's language.

**Comment by Frenzie** [comment]
@apletnev Dutch *lijndikte* (line thickness) and German *Strichbreite* (literally line breadth, but properly translated it would be line width) are often translated into English as *line width*. This predates any kind of programming by a long time, cf. [this random book from 1933](https://books.google.be/books?id=eConAQAAIAAJ&q=%22%22+line+width+%22%22&dq=%22%22+line+width+%22%22&hl=en&sa=X&ved=0ahUKEwjttdLK_sPRAhWTHsAKHZJiDCIQ6AEILjAD). If anything it's programmers who'd get confused about line width often being 80 characters. ;-)

But anyway, the point was to ascertain whether it's meant to be line *thickness*, because line thick isn't proper English. Shall I fix it or will you?

**Comment by apletnev** [comment]
@Frenzie go ahead
