### ISSUE TITLE
StorageStat plugin needs improvement.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2486]
* KOReader version: Last nightly builds.
* Device: All of them.

#### Issue
The way the information is showed by the Storage Stat plugin is not intuitive so many users won't be able to understand it. More so if the user doesn't speak English.
Here we see:

**/mount/onboard U1.0G F279.4M
P79%**

It should be something like:

**Internal storage**
Used 1.0 GB, Free 279.4 MB, Percentage 79%.
(And a similar entry for **External storage**)

And, ideally, "Internal storage", "Used", "Free", "Percentage" and "External storage" should be translatable.

As a side note, the menu entry "Storage Statistics" should be "Storage statistics" for stylistic coherence.

![filemanager_2017-jan-12_085213](https://cloud.githubusercontent.com/assets/18194241/21885448/0713b64c-d8b8-11e6-9b2b-b1e768444291.png)

**Comment by retrue** [comment]
It is much clearer now, thank you very much.
However, I don't close the issue because there are still two problems. Quoting @houqp in #2491:

> We could have at least done the space split in Lua and construct the message with _() to make the string translatable. This feature also needs to be extended to support external storage in the future.

**Comment by Hzj-jie** [comment]
I believe this bug should have been fixed already.
