### ISSUE TITLE
Small typo in the Spanish translation

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2488]
* KOReader version: v2015.11-800 (last one as of today)
* Device: All of them.

#### Issue

I found a small typo in the Spanish translation. I would correct it myself but I don't know how the translation system works or what is the correct place to report typos in the translations.

I the entry menu, inside of "Set render style", "Clear all external styles" is translated as "Eli**o**minar todos los estilos externos" but it should be "Eliminar todos los estilos externos".

**Comment by Frenzie** [comment]
I'll do it and #2482 later today. :)

**Comment by Frenzie** [comment]
Alright, fixed. The fix should be in a nightly near you soon.
