### ISSUE TITLE
Is it possible to retrieve Kindle Voyage / Oasis light sensor value?

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2494]
The default behavior of auto-brightness of kindle voyage is less optimized, i.e. the frontlight becomes brighter when the environment is brighter, which, I believe, is wrong for e-ink display. Well, anyway, I am trying to support the light sensor in KOReader.
I have googled around, especially in mobileread, and searched in voyage system, but I have not found anything interesting. Do you happen to have any thoughts?

**Comment by houqp** [comment]
Nothing interesting in /dev/input? On kobo, reading from the Orientation/Motion sensor can be found there.

**Comment by Hzj-jie** [comment]
Unfortunately, no. I have found the change to detect oasis rotation (https://github.com/koreader/koreader/pull/2209/files), which looks like a pretty complex change, with lots of magic strings.

I suppose it can be retrieved by lipc-get-property. I am trying.

**Comment by Hzj-jie** [comment]
`lipc-get-prop com.lab126.powerd alsLux` looks like the right value.
The value can be up to 65K, may be 65535. But typically 100 should be bright enough to read.
Several samples,
Placing on the table in my room, 60 - 65
Facing the sensor to the screen of my laptop, 85 - 90
Facing the sensor to a 60W bulb, up to 65K.
A comfortable brightness for reading, 256.

**Comment by NiLuJe** [comment]
Re #2941, right?
