### ISSUE TITLE
Kindle oasis crash startup

### ISSUE THREAD

**Issue by sylvainblot** [koreader/koreader#2496]
* KOReader version: latest
* Device: kindle oasis

#### Issue
launch with KUAL
crash at startup, here is the crash.log file, seems to be gesture related.

```
./luajit: frontend/device/kindle/device.lua:363: unknown Kindle model B0
stack traceback:
	[C]: in function 'error'
	frontend/device/kindle/device.lua:363: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:37: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:92: in main chunk
	[C]: at 0x0000be8d
```

**Comment by sylvainblot** [comment]
my bad wrong version

**Comment by aaditya99983** [comment]
please tell how you resolved it steps??

**Comment by Frenzie** [comment]
The "wrong version" comment indicates what i already pointed out in https://github.com/koreader/koreader/issues/3387#issuecomment-338410562

Please make sure you've tried https://github.com/koreader/koreader/releases/tag/v2017.10.04-nightly and we'll take it from there.
