### ISSUE TITLE
missing some letters from portuguese languague

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2497]
I don´t know how to do it,..but Is it possible to add some letters from portuguese to koreader keyboard?
It is missing these two: ã , õ 

Thanks for keeping this good software alive.

**Comment by houqp** [comment]
Keyboard layouts are defined in frontend/ui/data/keyboardlayouts. You  can edit those files with a text editor to add characters you need.

**Comment by Eduardomb22** [comment]
Thanks

**Comment by robert00s** [comment]
Similar to #2319 I propose that layout:

![1](https://cloud.githubusercontent.com/assets/22982594/22306258/d8a48cfa-e33e-11e6-876f-ee5161bf1339.png)

![2](https://cloud.githubusercontent.com/assets/22982594/22306259/d8aa7408-e33e-11e6-9a25-afd605bc4b0a.png)

Is this correct?

**Comment by Eduardomb22** [comment]
Yes! Thanks for fixing it!
