### ISSUE TITLE
Scrolling bars in new image viewer

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2505]
* KOReader version: Any
* Device:

#### Issue

I love the new image viewer feature. It is something that I have wished for ages, but would it be possible to add scrolling bars to view images at scale 1:1 or zoomed that are bigger than the resolution of the screen?
I have a Kobo Mini, and even with this new feature, looking at maps in fantasy books is all but impossible.

**Comment by poire-z** [comment]
Could be some fun with onPan and some blitbuffer cropping.
Are scroll bars really necessary ? That seems more complicated.

It would be sad to lose image space with a second row of buttons (zoom+/zoom-/???).
Are the "pinch" and "spead" gestures available on all devices (I guess not on the emulator, but we could add key bindings for the + and - keys) ?
Can you link to some free epub with a few real big images to play with ?

**Comment by retrue** [comment]
Really scroll bars are not necessary if you can scroll the image with your fingers. I mean, tap on the image and while tapped, moved it to one side or other.
I think there are two types of situations here. 
Situation 1: Images that are big, for example a 1600x1200 image to be seen at scale 1:1 in a 800x600 screen. Here, there should be a button beside "rotate", "close", "scaled" that say something like 1:1 or original size, and then move the image with your fingers instead of a scrolling bar.
Situation 2: Images that are smaller than the screen resolution at 1:1. If you want to zoom in to see them bigger, you would need new buttons called "zoom +", "zoom -" or similar; or define a couple of gestures to zoom in and out, for example pinching with two fingers. But I don't know if it is pinches are supported by all the devices. And once the image is zoomed in and bigger than the screen, then you would need to be able to move the image with your fingers like in situation 1.
I would be already happy if situation 1 was implemented.
I'll look for a free epub with a big image. If I don't find anything, I will  create a epub with a big image.

**Comment by KenMaltby** [comment]
Sounds great for maps, especially those embedded in the text, as opposed to those on a map page.

**Comment by retrue** [comment]
I tested it. Pinch and spread (for zoom in and out) don't work on my Kobo Mini. I don't know if it is a bug or a hardware limitation in Kobos Mini. I mean, I don't know if pinches can be added to Kobo gestures.
But the rest of the PR works great and I am more than happy with it.
Thanks.

**Comment by poire-z** [comment]
Could be some hardware or kernel limitation.
But just to be sure: try to be quick when pinching/spreading. I noticed that if you're too slow, and hold too long at start or end, the gesture may be considered a hold-like event, and not be sent as pinch or spread.

**Comment by retrue** [comment]
Checked again. Pinch or spread don't work on my Kobo Mini. If somebody else can confirm that it works in other devices, then it must be a hardware or kernel limitation.

**Comment by poire-z** [comment]
It works on my Glo HD.
We could add an other single touch gesture for zooming, like vertical swipe in a 1/16 wide zone on the side (left side ? right side ? there's already the kobolight plugin that uses this on the left side, dunno how they would conflict).

**Comment by retrue** [comment]
Is there space beside "Original size", "Rotate" and "Close" to add two more buttons, "Zoom -" "Zoom +"? Or would it be too cluttered?

**Comment by KenMaltby** [comment]
This issue has an interesting history.  The capacitance based original Aura (non-HD) has multi-touch built-in, it is the only Kobo E-reader that multi touch should work on.  All the others use an IR touchscreen that has only half its multi-touch implemented.  But - there are several reports where the Glo HD is able to use multi-touch functions.

**Comment by retrue** [comment]
In my case vertical swipe on both sides will work great because Kobo Mini doesn't have light.

**Comment by poire-z** [comment]
It was easy to add zoom with vertical swipes on both sides of screen, so here it is.
@retrue: you may want to download the raw imageviewer.lua from my PR and drop it in place of the current one, and say if 1/16 width is enough on your small screen.
No conflict with existing gestures as i was already masking them while allowing panning with zoom on the full scrren.

**Comment by retrue** [comment]
Which ones are exactly the gestures? And which one zoom in and wich one zoom out?

down to up, left side?
up to down, left side?
down to up, right side?
up to down, right side?

Because right now I have a very zoomed in image and I cannot zoom it out.

**Comment by poire-z** [comment]
Both sides works (but small width, so you may need to touch the border) :
down to up (swipe north) on left or right side will increase zoom (zoom in)
up to down (swipe south) on left or right side will decrease zoom (zoom out)

**Comment by retrue** [comment]
Thanks. Now it works. I have to be a bit patient so the screen has time to react.
