### ISSUE TITLE
[Kindle pw3] airplane mode automatically on exiting koreader

### ISSUE THREAD

**Issue by SsnL** [koreader/koreader#2511]
* KOReader version: v2015.11-817-g8f6a38d
* Device: Kindle pw3

#### Issue
When exiting koreader, airplane mode gets automatically switched on, no matter koreader was opened from kpvbooklet or kual. 

The issue occurred when I updated from an old nightly build (~ 2016.9 I think) to the latest version in GitHub release. It is still happening when I updated to latest nightly I can find.

**Comment by robert00s** [comment]
Similar issue here: #2379

**Comment by SsnL** [comment]
Can we at least disable that workaround for non-kobo-ksm devices?

**Comment by houqp** [comment]
Yes, will get this fixed asap. It's holiday season here unfortunately :(
