### ISSUE TITLE
dictionary disassemble for Persian (Farsi) language 

### ISSUE THREAD

**Issue by Ulterimate** [koreader/koreader#2512]
* KOReader version:koreader-stable-v2015.11
* Device:pw3

#### Issue
dictionary disassemble for Persian (Farsi) language 
#### Steps to reproduce
i have installed a English/Persian dictionary the way been told in  instruction, and it worked but it was disassembled
it should show "stun" word like this : 
![1](https://cloud.githubusercontent.com/assets/25292473/22193785/1f35f214-e153-11e6-8236-fe15d590e8df.JPG)
but it works this way : 
![photo_2017-01-23_10-08-59](https://cloud.githubusercontent.com/assets/25292473/22193895/fcdde89c-e153-11e6-8875-5e2248c7d2d4.jpg)
and this is the stardict file : 
[Hfarsi.zip](https://github.com/koreader/koreader/files/722913/Hfarsi.zip)
i took this file from a froum that they teseted it on koreader in kubo and seems worked for them
then i tryed to install the famous persian font that named "B nazanin" that may correct dictionary by doing this:
![2](https://cloud.githubusercontent.com/assets/25292473/22194081/4b58920a-e155-11e6-87f0-1130698011d6.JPG)

and then this:

![3](https://cloud.githubusercontent.com/assets/25292473/22194146/c3380404-e155-11e6-9a1f-ec2b3dc712f9.JPG)
but it didn't worked
I also tryed another dic :
[English to Farsi hfarsi.zip](https://github.com/koreader/koreader/files/722892/English.to.Farsi.hfarsi.zip)
still not working :d
I don't know if I did right or wrong but this was what i did and still it's disassembleld  
any body? any idea?

**Comment by poire-z** [comment]
Not sure about what your problem is, as i don't read persian and am not sure about what you mean by disassemble.
But if you'd mean the persian characters you see are not the ones you expect to see from your B Nazanin font, you may try to change the order of the .ttf in the font.lua you were editing, and make it the first:
```
    fallbacks = {
        [1] = "B Nazanin/B Nazanin.ttf",
        [2] = "noto/NotoSansCJK-Regular.ttf",
        [3] = "noto/NotoSans-Regular.ttf",
        [4] = "freefont/FreeSans.ttf",
    },
```
If that does not solve it (the dictionary uses the noto/NotoSans-Regular.ttf font, which may have persian characters, so no fallback would be needed), and if you mostly read persian, you may make the dictionary use your persian font (and use the above fallbacks for latin characters) by editing:

frontend/ui/widget/dictquicklookup.lua at line 40:
```
    -- content_face = Font:getFace("cfont", DDICT_FONT_SIZE),
    content_face = Font:getFace("B Nazanin/B Nazanin.ttf", DDICT_FONT_SIZE),
```

**Comment by Ulterimate** [comment]
Great thanks for your help, but Unfortunately it's not working
but i tryed an other trick and it worked:
the persian language has two difference with english that makes us problems
1- it's right-to-left and in dictionary it like we write "hello" and it shows "olleh"!
2-when you write persian letters near each other without any Space between them, they will join each other unlike english
so meaning of a word like hello in perion should be shown:   "سلام"
 that is created from joining of:   "س ل ا م"  letters
so when koreader is not Compatible whit right-to-left and joining letters it don't join them and show them in revers like this :  "م ا ل س"
i think it will be needed to add complete support of persian for normall use but until that day there is an special dictionary that it's words are been reversed and joints are tricked some how I don't know!
and could be usefull : 

[persian.zip](https://github.com/koreader/koreader/files/736779/persian.zip)

it also need's a persian Unicode font not "B nazanin" (seems it's not unicode)
that  I suggest using of "Yas" font:

[Yas.zip](https://github.com/koreader/koreader/files/736780/Yas.zip)

I hope one day persian is supported by every device and software. until that, it will remain a real problem

**Comment by NiLuJe** [comment]
We should have taken of the more egregious cases in #3942 

Complex script shaping is still not on the table, because we're not using a shaper.

**Comment by xmha97** [comment]
@NiLuJe This bug is still not solved and this issue should be opened.

**Comment by poire-z** [comment]
Look at the .ifo in this dict directory, what's the value of `sametypesequence=` ? "h" or other ? If it is "h" (rendered by MuPDF, that we can't tweak), you can try changeing it to "t" so it is rendered by our UI text stack, which should properly do RTL Arabic/Farsi text shaping.

Hard for us westerner to notice what's wrong: it does not look all bad with all letters separated, it seems some stuff is properly joined.
We have Arabic and Urdu working :https://github.com/koreader/koreader/issues?q=sort%3Aupdated-desc+sametypesequence+arabic
Also be sure that in File browser > Tools > More tools > Developper options > , you DO NOT have this checked: ![image](https://user-images.githubusercontent.com/24273478/208295152-a50e07cf-8069-4f30-ba38-8f3063f77aeb.png)

**Comment by xmha97** [comment]
Ok, thanks.

**Comment by poire-z** [comment]
Tell us what it was if any of these ideas did solve your issue.

**Comment by Mirsalar** [comment]
I have the same problem and I have tested four types of sametypesequence so far: h, m, x, t. Any other suggestions to solve the problem? Thanks a lot!

**Comment by mortezadadgar** [comment]
For those that are interested in English to Persian dictionary, just take "English to Farsi hfarsi.zip" and change "sametypesequence" to "t" in .ifo file
