### ISSUE TITLE
Suggestion：Let the comic gamma definable

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2513]
I found change these values can fit the comic gamma.
how can I let these values definable in the defaults.persistent.lua?
![image](https://cloud.githubusercontent.com/assets/9783549/22207741/41c506b8-e1bb-11e6-8e70-fbf39da25cbd.png)

**Comment by houqp** [comment]
We are deprecating defaults.persistent.lua now, so no new settings can be added to it. What other values do you need? Maybe we can just add those new values to it.

**Comment by houqp** [comment]
If we need to go down the "make it configurable" route, then it needs to be set in `settings.reader.lua`.

**Comment by seacatwu** [comment]
![image](https://cloud.githubusercontent.com/assets/9783549/22320937/955292f2-e3cb-11e6-9fe7-46743c1a4675.png)
Maybe we can let margin-top or margin_bottom configurable.

**Comment by seacatwu** [comment]
still waiting

**Comment by robert00s** [comment]
@seacatwu 
After this commit #3463 (#2133) we have more contrast/gamma options. Is that enough?

**Comment by seacatwu** [comment]
@robert00s  That's great!

**Comment by Frenzie** [comment]
I'll close this then. :-)
