### ISSUE TITLE
koreader+fmon failed to start since firmware 4.2.8283 on kobo aura one

### ISSUE THREAD

**Issue by chenxingqun** [koreader/koreader#2515]
* KOReader version: v2015.11-818-g81bc115
* Device: Kobo aura one

#### Issue 
koreader failed to start. after press koreader.png, it returns to nickel

#### Steps to reproduce
update to firmware 4.2.8283
install fmon and koreader, and then open koreader as usual

**Comment by liyiecho** [comment]
Me too, so I use KSM8 now.

**Comment by houqp** [comment]
This is no something we can help since we don't manage fmon. Do you who maintains fmon?

**Comment by pazos** [comment]
same in #2542, it affects koreader via fmon kfmon and shell script. KSM8 was patched to work with this FW

**Comment by Frenzie** [comment]
Closed in favor of #2502.
