### ISSUE TITLE
Some zoom fit margin & status bar problem

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2517]
* KOReader version:latest
* Device:H2o
#### Issue
1.Zoom fit content width and use status bar, the status bar covered the content. 
![image](https://cloud.githubusercontent.com/assets/9783549/22273596/961e065c-e2dc-11e6-8cd9-ee9c33762e5c.png)
2.Zoom fit content height and use status bar, the top margin can't be 0.
![image](https://cloud.githubusercontent.com/assets/9783549/22273671/e232ca50-e2dc-11e6-8d62-c3a00efb6330.png)
If not use status bar, the top margin and bottom margin can be 0.
![image](https://cloud.githubusercontent.com/assets/9783549/22273695/07f920ae-e2dd-11e6-9ef0-11986153fec2.png)

**Comment by yparitcher** [comment]
should be fixed by  #5620 or #5657
please close

**Comment by NiLuJe** [comment]
Indeed, thanks ;).
