### ISSUE TITLE
Problem with Kobo Suspend: Kobo Aura One wakes up by itself

### ISSUE THREAD

**Issue by trekk2810** [koreader/koreader#2520]
* KOReader version: v2015.11-793-gf95ad00
* Device: Kobo Aura One

Short version:
My KA1 mysteriously woke up from suspend (with it's screensaver still showing). In the time between 7:49 and 14:52 the battery life went down from 91% to 43%.

Here is what happened in detail:
As you can see in the excerpt of the KoReader log, the device was suspended on 01/29/17 - 22:59:36. That was the time I  pushed the power button to suspend the reader and went to sleep.

At 01/30/17 - 07:49:19 the device woke up by itself. That was about the time I took the device out of my bag and placed it onto my desktop at work. I didn't touch the device with my hands (it was still in his sleeve). I also didn't accidently push the power button.

At 01/30/17 - 14:52:28 I took the device out of it's felt-sleeve (no magnetic parts). The device still showed the screensaver, allthough according to the log file, the device already woke up at 07:49:19. 
I pushed the power button to start the reader and after flippig the first page I noticed the massive loss of battery life.

As I went to sleep the battery was at 91 %. At the time I started the device the battery was at only 43 %.

This happened to me multiple times before. I started KoReader from a rebooted device, using KSM.
```
01/29/17-22:59:34 INFO  Kobo Suspend: Going to sleep . . .
01/29/17-22:59:34 INFO  Write syscall returned:  true
01/29/17-22:59:34 INFO  Kobo Suspend: Asked the kernel to put subsystems to sleep
01/29/17-22:59:36 INFO  Kobo Suspend: Waited for 2s because of reasons...
01/29/17-22:59:36 INFO  Kobo Suspend: Synced FS
01/29/17-22:59:36 INFO  Kobo Suspend: Asking for a suspend to RAM . . .
01/29/17-22:59:36 INFO  Kobo Suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
01/30/17-07:49:19 INFO  Kobo Suspend: Woke up!
01/30/17-14:52:28 INFO  Kobo Suspend: Unflagged kernel subsystems for suspend
01/30/17-14:52:28 WARN  no refresh got enqueued. Will do a partial full screen refresh, which might be inefficient
01/30/17-14:52:48 WARN  sizeUtf8Text called without text
01/30/17-14:52:50 INFO  no dialog left to show
01/30/17-14:52:50 INFO  quiting uimanager
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device
---------------------------------------------
                launching...
```

**Comment by taosxx** [comment]
I've seen the same on a Kobo Glo HD with a fresh install of v2015.11-822-g399190c: goes to sleep, wakes up mysteriously a few minutes later - but still shows book cover as screen saver - drains battery from 96% to 43% over night.
Koreader was started from KSM8 after exiting nickel, suspend was entered after closing sleepcover, device was not moved.

**Comment by houqp** [comment]
This is a known issue, although I don't expect it to happen at the frequency that @taosxx is experiencing. Can any of you run koreader in debug mode to help collect more logs? I am curious what event wakes up the device.

At the mean time, I will submit a patch to put device back to sleep during unexpected wake up actions.

**Comment by houqp** [comment]
@taosxx can you confirm that all activities from your log are generated while the device is not operated at all? It doesn't make sense that it keeps suspend and resume by itself because there is no such logic in the code. Only things that can trigger this is closing/opening sleep cover and toggling power button. Have you tried placing the device in a different location?

**Comment by taosxx** [comment]
First time was over night. It was on a table next to my bed. Second day, I forgot to take it with me and left it on the counter during the day (no pets or humans at home).
I've enabled debug mode and have it lying on a table in its sleep cover at the moment, I'll let you know if I find something strange in the log file again.

**Comment by houqp** [comment]
@taosxx please give the next nightly build a try, it should include a patch that addresses this issue.
