### ISSUE TITLE
Install on Kobo Glo HD

### ISSUE THREAD

**Issue by sbll885** [koreader/koreader#2529]
* KOReader version: koreader-stable-v2015.11
* Device: Kobo Glo HD, firmware 3.19.5761

####  Install based on [Start Menu](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices).  
Start menu was installed , after reboot device started in Start Menu.
**koreader** folder was copied to _.adds_ directory
After  additional restart I can see **start kooreader** in the start menu. On an attempt to launch reader application, files manager is opened instead of reader. What to do from this point ?

Thanks

**Comment by KenMaltby** [comment]
I am surprised at the number of people who find it odd that the reader opens in the "File Manager".  That they don't seem to see it as part of the reader.  Perhaps there should be a one time (or dismissible)  information message box with instructions on how to navigate the file manager and select books to read.  It might also explain how to set a "Home" directory for the File Manager. (That would also expose the new user to the "Long Press" to set defaults concept.)

**Comment by AlanSP1** [comment]
In file manager there's option to open last used file. I always select that option to enter book I read at the moment.

And yes, some instructions are needed for new users (and for older ones like myself, there's so much options, functions...)

**Comment by retrue** [comment]
There are too many options that are only available through editing setting.reader.lua with zero information on the web or wiki. They can be found only through reading the issues and pull requests found here in Github.

**Comment by houqp** [comment]
We are very resource constrained on documentation unfortunately. I see two ways to scale this:

1. have volunteers with technical backgrounds to help maintain the manual
2. automate the document generation with tooling. This way, developer can put the document in the code as comment and have the manual generated automatically

Option 2 would be ideal and is something on my long todo list. If anyone wants to take a stab on it, please let me know.

**Comment by Frenzie** [comment]
How about simply renaming it slightly to, e.g., "KOReader File Browser" for the moment? That way you'd know you did in fact open KOReader and not some random file manager.

![screenshot_2017-02-23_16-19-28](https://cloud.githubusercontent.com/assets/202757/23265076/e3db339c-f9e3-11e6-8e1f-f9d9ccce5c9f.png)

**Comment by KenMaltby** [comment]
One part of the problem is that a new user may not have any ebooks in the directory that KOReader defaults to.  He would need to navigate to where he has ebooks, if he has any on his device.  The use of "../" and "/mnt" would not be what windows users are familiar with.

**Comment by Frenzie** [comment]
This Windows user is familiar with it. *grins*

![filemanager31](https://cloud.githubusercontent.com/assets/202757/23268392/e0e9a7f4-f9ed-11e6-8b25-95460e77c845.gif)

But true, that was removed in Windows 95. I'd say that ideally you could navigate by breadcrumps, i.e., something like

<kbd>home</kbd> / <kbd>frans</kbd> / <kbd>etc</kbd>

but in lieu of that it oughtn't be too hard to add a little upwards arrow of some sort like Windows 3 did.

`⬑ ..`

That's U+2B11 but it's apparently not in our GUI font.

Here's an illustration with a regular upwards arrow, but that doesn't seem quite clear enough. You can do your own experiments here: https://github.com/koreader/koreader/blob/ee54e127b14609a7b4d247cbe7a1c90405403240/frontend/ui/widget/filechooser.lua#L157

![screenshot_2017-02-23_17-51-29](https://cloud.githubusercontent.com/assets/202757/23269400/c2448636-f9f0-11e6-802e-115d5581b10c.png)

**Comment by Frenzie** [comment]
This one's pretty decent.

⬆ 
2B06
UPWARDS BLACK ARROW

![screenshot_2017-02-23_18-20-53](https://cloud.githubusercontent.com/assets/202757/23270644/d4556652-f9f4-11e6-94ca-da8e1e2c48bf.png)
