### ISSUE TITLE
Feature Request: Debug mode and crash.log stuff in Developper options

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2530]
#### Issue

I would like to see in Developper options a menu entry to enable Debug mode. When enabled it should appear ticked. And below Debug mode add too several menu entries related to crash.log. They could be:
Delete crash.log
Rename crash.log
Open crash.log (to look at it as a text file)

For me, as an user who reports bugs it is useful because I avoid connections to the computer to activate/deactivate debug mode. The idea of having the option to rename crash.log is to separate different crash.log files depending of options chosen or debug mode enabled or not.
For you, developpers, it would be handier than to me.

**Comment by KenMaltby** [comment]
The File Manager already has the ability to delete and rename .txt files, it can't be hard to add ".log" to cre's registered file types.  Setting debug mode, with a tick mark to indicate when it is enabled, sounds great.

**Comment by Frenzie** [comment]
A little extra line here should do for opening log files: https://github.com/koreader/koreader/blob/97d34c5bb0de21a8c2ad2cb47ead64b2d3de89ff/frontend/document/credocument.lua#L454

**Comment by houqp** [comment]
I like this feature, seems like a quick win for us. In the long run, we should automate the process and make the crash log collecting and bug report experience a "one click" action.

**Comment by KenMaltby** [comment]
At some point it also might, be a good idea to add a log.css, to make the crash logs more presentable.

**Comment by Hzj-jie** [comment]
It looks like I have added the log file support in the PR of batterystats plugin. Though I have not set a specific CSS for it.

**Comment by Frenzie** [comment]
Implemented by @NiLuJe recently so closing now, but I can't quite pinpoint the issue/PR atm.

![Screenshot_2019-06-11_16-25-46](https://user-images.githubusercontent.com/202757/59280312-a9363b80-8c65-11e9-9f7b-f36c6bd35a7f.png)
![Screenshot_2019-06-11_16-25-54](https://user-images.githubusercontent.com/202757/59280313-a9ced200-8c65-11e9-8d2b-d26bf952b5da.png)

**Comment by NiLuJe** [comment]
It might have been snuck in with another unrelated PR during the various Forma & BB tweaks ;p.
