### ISSUE TITLE
Android build?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2531]
Hi

Can we please get some recent buildfor Android? It has been a while since we had one and hopefuly we have the android key signing fixed.

**Comment by houqp** [comment]
I introduced another bug while fixing the double signing issue:
https://github.com/koreader/koreader-misc/blob/master/nightswatcher/nightswatcher.py#L79

The `*` got expanded before passing to the `zip` command, which broke the android build. Unfortunately I am in travel mode again and won't be back until mid Feb :(

**Comment by Frenzie** [comment]
I'll look at it tonight.

**Comment by houqp** [comment]
Thanks! It should be a fairly straight forward fix, just need to figure out how to pass `*` to the zip command from python. The `*` is probably also not required for the zip command to remove a whole folder.

**Comment by gerroon** [comment]
thanks for looking into it guys. 
If I remember right Python uses Popen subprocess but my Python knowledge is a bit rusty.

**Comment by houqp** [comment]
I am using the subprocess module from gevent, but the API is probably very similar :)

**Comment by Frenzie** [comment]
If I did this Docker thing right then it should be spitting out a proper Android build in some 8 hours, but I'm not entirely sure how to trigger it manually. Or if I did do it right, then there's another error in there:

```
cp: cannot stat '/builds/koreader/nightly-builds/koreader/base/thirdparty/libzmq/build/arm-linux-androideabi/libzmq-prefix/src/libzmq-build/lib/libzmq.so.4': No such file or directory
make[1]: *** [build/arm-linux-androideabi/libs/libzmq.so.4] Error 1
make[1]: Leaving directory `/builds/koreader/nightly-builds/koreader/base'
make: *** [all] Error 2
```

**Comment by Frenzie** [comment]
I'll just drop this here for now as I'm not sure what's up with the OTA server exactly.

http://apkshared.net/2BKl

I don't know if it actually works because KOReader doesn't work on my phone regardless.

**Comment by gerroon** [comment]
@Frenzie 

thanks , I will test it out, however the original issue was that there were multiple apk signatures so we should only get one apk that use the same signtatures across otherwise we need to constantly uninstall and install, not sure what the method is for when multiple devs are releasing the same apk builds

**Comment by Frenzie** [comment]
This is (or should be) the proper build with the proper key. It's not me just running `./kodev release` on my regular machine. ;-)

**Comment by gerroon** [comment]
Couple issues

-crashes during start up

-mising icon

-wrong app package name 

:)

02-09 11:02:35.015  3186  5915 I ActivityManager: Start proc 1328:org.koreader.launcher/u0a298 for activity org.koreader.launcher/.MainActivity
02-09 11:02:35.100  1328  1328 W System  : ClassLoader referenced unknown path: /data/app/org.koreader.launcher-1/base.apk
02-09 11:02:35.135  1328  1328 W XPrivacy: Hooking package=org.koreader.launcher
02-09 11:02:35.160  1328  1328 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:35.160  1328  1328 W ContextImpl: Unable to create files subdir /data/user/0/org.koreader.launcher/cache
02-09 11:02:35.160  1328  1328 W ContextImpl: Unable to create files subdir /data/user/0/org.koreader.launcher/code_cache
02-09 11:02:35.170  1328  1328 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:35.170  1328  1328 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:35.175  1328  1328 E AndroidRuntime: Process: org.koreader.launcher, PID: 1328
02-09 11:02:35.175  3186  7009 W ActivityManager:   Force finishing activity org.koreader.launcher/.MainActivity
02-09 11:02:35.685  3186  3232 W ActivityManager: Activity pause timeout for ActivityRecord{1f444c9 u0 org.koreader.launcher/.MainActivity t7215 f}
02-09 11:02:36.385  3186  6718 I ActivityManager: Process org.koreader.launcher (pid 1328) has died
02-09 11:02:37.725 18675 18675 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:37.725 18675 18675 W PackageManager: Failure retrieving resources for org.koreader.launcher
02-09 11:02:38.610  3186  3208 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity} from uid 10225 on display 0
02-09 11:02:38.615  3186  3252 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:38.625  3186  3252 W WindowManager: Token{dbc1463 ActivityRecord{3ed9292 u0 org.koreader.launcher/.MainActivity t7217}} failed creating starting window
02-09 11:02:38.795  3186 24510 I ActivityManager: Start proc 1346:org.koreader.launcher/u0a298 for activity org.koreader.launcher/.MainActivity
02-09 11:02:38.890  1346  1346 W System  : ClassLoader referenced unknown path: /data/app/org.koreader.launcher-1/base.apk
02-09 11:02:38.925  1346  1346 W XPrivacy: Hooking package=org.koreader.launcher
02-09 11:02:38.955  1346  1346 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:38.955  1346  1346 W ContextImpl: Unable to create files subdir /data/user/0/org.koreader.launcher/cache
02-09 11:02:38.955  1346  1346 W ContextImpl: Unable to create files subdir /data/user/0/org.koreader.launcher/code_cache
02-09 11:02:38.960  1346  1346 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:38.965  1346  1346 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:38.970  1346  1346 E AndroidRuntime: Process: org.koreader.launcher, PID: 1346
02-09 11:02:38.975  3186  3209 W ActivityManager:   Force finishing activity org.koreader.launcher/.MainActivity
02-09 11:02:39.480  3186  3232 W ActivityManager: Activity pause timeout for ActivityRecord{3ed9292 u0 org.koreader.launcher/.MainActivity t7217 f}
02-09 11:02:40.540  5870  5870 W asset   : Asset path /data/app/org.koreader.launcher-1/base.apk is neither a directory nor file (type=1).
02-09 11:02:40.540  5870  5870 W PackageManager: Failure retrieving resources for org.koreader.launcher
02-09 11:02:41.615  3186  5932 I ActivityManager: Process org.koreader.launcher (pid 1346) has died

**Comment by Frenzie** [comment]
Freezes and crashes are normal on Android so I can't comment on that. The program has never once worked on my phone.

I'm not sure what you mean about app package name. Looking at the previous releases they're all the same.

* koreader-android-arm-linux-androideabi-v2015.11-845-g6b5b426.apk
* koreader-android-arm-linux-androideabi-v2015.11-696-g2bc7b01.apk
* koreader-android-arm-linux-androideabi-v2015.11-587-ga55a987.apk

The icon's definitely there for me?

Anyway, I guess we'll just have to wait until @houqp has some time to look at it. I fixed a minor typo/oversight so the program builds successfully and I wash my hands of anything else. :P

**Comment by Frenzie** [comment]
Ah, perhaps I see the problem. There's a missing META-INF/KOREADER.RSA and META-INF/KOREADER.SF which would explain this resources stuff. (Meaning deleting everything in META-INF was a bit overzealous.) I imagine it should stick to `CERT.RSA`, `CERT.SF` and `MANIFEST.MF` because those are what's generated by jarsigner. The others probably stem from building the launcher or something. I'll give it a whirl tomorrow.

**Comment by gerroon** [comment]
@Frenzie 

Yeah android builds were never great, but the builds from last 6 months did work ok for me. I use it on multiple devices.

**Comment by houqp** [comment]
@Frenzie good catch. Deleting the whole META-INF directory is just a tip I found from the internet so it might not work for us. I haven't tested it myself. The problem we need to solve here is how to resign a debug APK with a release key. I choose to do it this way so that we can keep the release key in our own koreader server instead of gitlab's CI servers.

**Comment by Frenzie** [comment]
Closing now.
