### ISSUE TITLE
TimeAPI.org is dead

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2533]
* KOReader version: timesync.koplugin
* Device: independent

#### Steps to reproduce

Unfortunately, timeapi.org is dead. http://www.timeapi.org/utc/now is not accessible anymore.
Should we add our own time server in kosync server?

**Comment by Frenzie** [comment]
Could it just be temporary?

**Comment by Hzj-jie** [comment]
I hope so. But it has already died for a while.

**Comment by Frenzie** [comment]
This has something to do with time synchronization, right?

Are there any objections to my suggestion from https://github.com/koreader/koreader/issues/1712#issuecomment-155100070 ?

Made slightly more explicit earlier here: https://www.mobileread.com/forums/showthread.php?p=3212807&highlight=ntpd#post3212807

```
ntpd -q -p pool.ntp.org
```

Those pools have a track record of decades.

**Comment by houqp** [comment]
I suggest we switch to use NTP too. There are plenty of reliable NTP servers out there, for example: https://developers.google.com/time/

**Comment by Hzj-jie** [comment]
Emmm, I should learn more linux commands. I do not even know there are ntp command-line tools.
I will confirm ntpdate (I assume we should use this command to update the time.) is available on both Kindle and Kobo, and update this plugin.
