### ISSUE TITLE
Wikipedia not working on Android since latest nightly 20170209

### ISSUE THREAD

**Issue by Germanc** [koreader/koreader#2537]
* KOReader version: koreader-nightly-20170209
* Device: Onyx C67ML Android 4.2

#### Issue
Wikipedia does not work since latest update. When I look up a word from a book it says "Do you want to turn on wifi?". Neither Cancel or Ok open up a wikipedia search. If I try to do a wikipedia search from the file manager, it does not ask to turn on wifi but still won't show the search.
The ereader is connected to wifi and loads web pages from other apps. Wikipedia search was working on previous nightly
#### Steps to reproduce
Press on a word and select Wikipedia.

**Comment by Frenzie** [comment]
The Android build may still be slightly broken. I'll remove it for now.

**Comment by Germanc** [comment]
Brute changing in manager.lua:
`return socket.dns.toip("www.example.com") ~= nil`
to
`socket.dns.toip("www.example.com") == nil`
makes wikipedia work again on android. So for some reason the dns lookup is not working even when the network is up. I'm using latest nightly build.

**Comment by houqp** [comment]
I don't recall any recent change in this code path. Can you confirm the previous version is still working on your device?

**Comment by Germanc** [comment]
On november nightly it never asks to turn on wifi but wikipedia is not working either. Not sure why, I used to use it.```

I/KOReader( 8494): }
W/SocketClient(   92): write error (Broken pipe)
I/KOReader( 8494): # error: frontend/ui/wikipedia.lua:60: Network is unreachable
```
KOReader says "No wiki page found"
Wikipedia is working in current version changing that line. I have network on other apps.

**Comment by houqp** [comment]
The network connectivity detection prompt is added recently, so it explains it why the older version doesn't display the prompt.

Can you try changing `www.example.com` to `www.google.com` or `www.wikipedia.org` in the latest version to see if it helps with connectivity detection?

**Comment by Frenzie** [comment]
example.com is a real website with DNS and everything, so I don't think it should make a difference.

**Comment by houqp** [comment]
yes, just trying to rule out the possibility of local DNS issue with example.com since I don't know what provider they use and what kind of availability they guarantee.

**Comment by Germanc** [comment]
Actually, I changed example.com by google.com and it works now as expected, so I might be having dns issues. I will check that later but this is resolved for me!

**Comment by robert00s** [comment]
It's works on koreader-nightly-20170612 (Android 6). I think we can close it.
