### ISSUE TITLE
Forced to use clippings instead of Evernote.

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#2539]
* KOReader version: v2015.1-847-g726b15a
* Device: PW3

#### Issue
Trying to export to Evernote plugin does not work anymore. Instead, when presing the green underlined item (see screenshot) it exports highlights to the new clippings.txt file. 

This clippings has been marked (see red underline), probably after an OTA update, and I cannot change it. The usual long press fails to do it. 

BTW the new clippings feature works very well. 

#### Steps to reproduce
Try to export to Evernote plugin
![highlight](https://cloud.githubusercontent.com/assets/1344670/22978967/a86acd28-f3cf-11e6-8358-3ac9949f996c.png)

**Comment by KenMaltby** [comment]
Perhaps OT, but after checking it out I couldn't dismiss the highlight from the text.

**Comment by Hzj-jie** [comment]
Do you mean you cannot click the 'Export to local clipping text file' again to uncheck it?

**Comment by KenMaltby** [comment]
What I couldn't dismiss was the highlight on the selected text in the epub.  ( I only used the highlight function to test out the poster's problem and perhaps there is a procedure to remove the highlight, that I am not aware of.)  Since the submenu is no longer just for "Evernote", you might want to change it to "Highlight options" or something.

**Comment by roger64** [comment]
Thank you for taking care of this. The clippings feature looks a little unstable because, for me,  nothing is working anymore. 

To comment further: I managed to take out the tick bar after pressing some time, but I can't select any of the items. I cannot export to Evernote like I was used to and even the export to clippings text works no more.

**Comment by Hzj-jie** [comment]
Evernote export failure may relate to issue #2452.
But you should always be able to enable or disable text export by short press the menu item. I do have a plan to update evernote menu items, but before that, would you mind to tell me your operations, so we can fix the issue on your device first.

**Comment by roger64** [comment]
Well I think there was a big misunderstanding of mine about how to use this new feature. Indeed everything works well with short presses and a little brain.

1. The short press on "Export to local clipping text file" just toggles (**on/off**) the tick mark on this line and do not do anything else (except provide a useless "confirmation" flash.
2. The line  "Exporter toutes les notes contenues dans ce livre"  is the important one.
With a short press on it, It either exports:
- to _Evernote web_ (if wifi is on...) and if  1 is **off** (unmarked)
- to _clippings.txt_ if 1 is **on** (marked)

Maybe the "purge history records" should totally delete the "clippings.txt file without asking the user to chack if there is still another file.

So, please accept my apologies. This is indeed working but maybe needs to be made clearer for very average users of my kind.
Regards

As I totally misunderstood its use,

**Comment by Hzj-jie** [comment]
Glad to know it works for you indeed.
Yes, we have already realized the menu items are pretty confusion. I plan to update it soon or later.
Regarding to the existing clipping.txt file, a principle at least I followed is, do not delete anything without users confirmation. But, yes, maybe we can change the information message into a two-button option window. I.e.
Do you also want to purge clipping.txt? Existing clippings in it won't be deleted automatically during next export.

What do you think?

**Comment by roger64** [comment]
Hi
I think that purge just means purge, so it should really do it (delete clippings.txt). But a two step implementation seems right (I mean with a confirmation dialog box).

**Comment by Hzj-jie** [comment]
I will make a change.

**Comment by roger64** [comment]
Thank you for making Koreader more user-friendly

**Comment by Hzj-jie** [comment]
Should we close this issue?

**Comment by houqp** [comment]
Looks like it's safe to close now. @roger64 feel free to reopen it if you still have questions.
