### ISSUE TITLE
kobolight.koplugin: frontlight toggle with tap on bottom left corner is not working

### ISSUE THREAD

**Issue by mblq** [koreader/koreader#2543]
* KOReader version: koreader-nightly-20170209
* Device: Kobo Glo HD

#### Issue
Tap on bottom left corner toggles status bar but does not toggle frontlight.
One finger swipe on left margin to change the frontlight works.

#### Steps to reproduce
Just try it.

**Comment by houqp** [comment]
Welp, you fixed it yourself :)
