### ISSUE TITLE
Scrolling behavior

### ISSUE THREAD

**Issue by baskerville** [koreader/koreader#2548]
During a scroll interaction, *koreader* tries to re-render the page for each touch event: it doesn't seem like the best possible approach for an e-ink screen.

Here's my suggestion:
- Don't refresh the page until the end of the scroll gesture.
- Only record the first and last touch points.
- When the gesture is over, let `P_s = (x_s, y_s)` be the first touch point and `P_e = (x_e, y_e)` be the last. Scroll by `y_e - y_s` vertically or by `x_e - x_s` horizontally.

**Comment by Frenzie** [comment]
Scrolling is definitely somewhat suboptimal, but I don't think going entirely feedback-less is the right approach either. Nickel scrolls reasonably well in PDFs and the browser.

Also, don't blame E Ink for what I assume are mostly Kobo implementation details and partially KOReader ones :-P

* ScummVM (2011) https://www.youtube.com/watch?v=8iFoMhJCCbo
* Nook Simple Touch emulating PlayStation 1 games (2012) https://www.youtube.com/watch?v=mXiiaprv3do

**Comment by poire-z** [comment]
This has also bugged me since the start on kobo.
As i don't know about other devices behaviour, i'm just patching my readerpaging.lua with this:
```
 function ReaderPaging:onPan(_, ges)
     if self.bookmark_flipping_mode then
         return true
     elseif self.page_flipping_mode then
         if self.view.zoom_mode == "page" then
             self:pageFlipping(self.flipping_page, ges)
         else
             self.view:PanningStart(-ges.relative.x, -ges.relative.y)
         end
     elseif ges.direction == "north" or ges.direction == "south" then
-        self:onPanningRel(self.last_pan_relative_y - ges.relative.y)
+        -- panning in real time is ugly on eInk screen... we'll do
+        -- that in onPanRelease, we just remember the latest relative.y here
+        -- self:onPanningRel(self.last_pan_relative_y - ges.relative.y)
         self.last_pan_relative_y = ges.relative.y
     end
     return true
 end

 function ReaderPaging:onPanRelease(_, ges)
     if self.page_flipping_mode then
         if self.view.zoom_mode == "page" then
             self:updateFlippingPage(self.current_page)
         else
             self.view:PanningStop()
         end
     else
+        -- we do the panning only at release time here
+        if self.last_pan_relative_y then
+            self:onPanningRel(0 - self.last_pan_relative_y)
+        end
         self.last_pan_relative_y = 0
         -- trigger full refresh to clear ghosting generated by previous fast refresh
         UIManager:setDirty(nil, "full")
     end
 end
```

**Comment by baskerville** [comment]
Thanks @poire-z, unfortunately your patch doesn't work for me: I only get a screen refresh but no scrolling.

In debug mode, I get this kind of messages though:
```
02/22/17-11:17:32 DEBUG in pan state...
02/22/17-11:17:32 DEBUG swipe south 523.83967012818 detected in slot 0
```

I'd like to add, regarding the current scrolling behavior:
- Scrolling sometimes continues for a few seconds after the end of the gesture.
- Making a scroll gesture in one direction can sometimes make the page scroll in the opposite direction.

**Comment by poire-z** [comment]
Dunno if that what happened, as you seem to know how to pan :) but as I read "swipe south", i remember what i wrote in some comments in imageviewer.lua:
```
-- Hold happens if we hold at start
-- Pan happens if we don't hold at start, but hold at end
-- Swipe happens if we don't hold at any moment
```
So, for onPanRelease to be called (and do the actual panning), you need to hold (waht 1-2 seconds before removing your finger) at the end of the gesture.
With continuous panning, it was indeed not needed, and the onPanRelease was a no-op.
So, yes, i got used to holding at end, and it may be strange to other people used to this continuous panning.

**Comment by baskerville** [comment]
Thanks, I wasn't aware of the distinction, my e-reader is the only touch device I use.

**Comment by houqp** [comment]
I constantly got annoyed by this behavior too to be honest ;) I have an intuition that this can be solved by adding debouncing in the gesture detector or event handler to reduce screen refresh rate. But I haven't been able to find time to experiment with it.
