### ISSUE TITLE
Unable to enable wifi on Kobo Glo HD 4.2.8432 

### ISSUE THREAD

**Issue by dset0x** [koreader/koreader#2554]
* KOReader version: koreader-nightly-20170209
* Device: Kobo Glo HD

#### Preface
The 4.2.8432 update introduces `/drivers/mx6sl-ntx/wifi/8189fs.ko`

#### Issue
Enabling wifi from koreader results in a message about being unable to connect to `/var/run/wpa_supplicant` 

#### Steps to reproduce
(As per `wifi-enable.sh`. Not I have removed `-s` for testing.)
```
# wpa_supplicant -ieth0 -O /var/run/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant.conf -B
Successfully initialized wpa_supplicant
nl80211: 'nl80211' generic netlink not found
Failed to initialize driver 'nl80211'
```

Adding `-Dwext` to the above command solves the issue.

Which devices require this change (or if this is the optimal solution) needs to be investigated.

**Comment by Frenzie** [comment]
Pinging @houqp in #2553

**Comment by dset0x** [comment]
Woops, I missed that one. At any rate my understanding is that `wext` is to-be-deprecated in general, so better keep that in mind.

Could we merge these issues?

**Comment by Frenzie** [comment]
The solution there is already more robust. :-)

You probably missed it because it's in a PR; I'm not sure if there's another issue.

**Comment by dset0x** [comment]
Indeed, I missed the PR @Frenzie. Thanks!
