### ISSUE TITLE
Statistic is not accurate

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2561]
* KOReader version: up to ee54e1
* Device: independent

#### Issue

Statistic is not accurate

#### Steps to reproduce

It's easy to reproduce the issue by starting a new book. After finishing some 50 pages in several days, you may find the statistic plugin reports inaccurate numbers, say pages, time read, etc.

I have had a look at the statistic plugin, but have not found a obvious reason. Maybe the plugin itself is too large. But something must be wrong in it. Indeed, I have not seen a correct number for any of my books. When I finish a book, the count of total pages I have read is always less than the count of pages of the book.

**Comment by Frenzie** [comment]
Wouldn't the min & max seconds be an obvious reason?

**Comment by AlanSP1** [comment]
I also think that min and max time to account page into statistics has a big influence into statistics readings.

For example, at the beginning of the book I usually fast forward for few pages. So, min time needs to be a bit high (15, or even more seconds), not to account for these pages. But, this causes that pages not to be entered into statistics.

Anyway, probably we need to take a hard look how we actually turn pages and how this reflects on statistics.

With time, as I close end of book I have more accurate statistics.

**Comment by Hzj-jie** [comment]
I do find some page updates will be ignored if time spent on the page is smaller than min or larger than max. I can imagine the reason of min seconds, but what's the purpose of the max seconds?

**Comment by apletnev** [comment]
Hi,
Min value, example if you skip pages, you did not read them, add it to total time is not correct.
Max value, an example you forgot to turn off your device and counter still add to the total time.

**Comment by Frenzie** [comment]
There's no forgetting. I do that on purpose.

**Comment by Hzj-jie** [comment]
I usually use a very tiny font to ensure I can read as much as possible in one page, which usually make me take longer time on one page. I have not measured the accurate time, but 90 seconds is not enough.

Should we enlarge the default value of page_max_read_sec?

**Comment by Frenzie** [comment]
Oh btw, does it pause while you're looking things up in the dictionary/Wikipedia?

Reading speed is something like ~250-300 words per minute in your native language. (My reading speed in French is significantly slower even when it doesn't feel like it.) A page could have anywhere from ~200-500 words on it, although usually probably closer to that same ~250-300 range. So yeah, I figure it should be something more like 120s or 150s.

Of course this is also device-dependent. On my H2O word density approximates a real book[1] but a device with a smaller screen (i.e., most of 'em) 90s is already a very reasonable margin.

[1] I primarily use it for DjVus (from archive.org) and PDFs (e.g., stuff from OAPEN Library), usually at a slightly smaller size than they'd be on real paper.

**Comment by apletnev** [comment]
Guys, the main idea of min and max that calculate actual reading time, I understand that some of the people writing notes, thinking about reading, surfing the net about some facts. But for me, is interesting to know the actual reading time, without thinking, surfing, etc. 
I think we can add an additional variable which would show how much time the book is open.

**Comment by Frenzie** [comment]
The implicit idea behind my first sentence, which is unrelated to the rest of what I wrote, is that ideally it should *pause* while you're in the dictionary. :-) Anyway, that's just an off-handed remark, probably very hard to implement, so ignore it. ;-D

My actual argument was that if you take, say, a 250 wpm reading speed at 500 wpp then you're already at 120s to read a page. [One of the books I'm reading right now](http://www.oapen.org/search?identifier=341439;keyword=yankees) has ~510-540 words on a few random but sufficiently representative full-text pages (i.e., those without illustrations). I imagine my reading speed will be on the higher end of the spectrum as it's in Dutch and I'm a reasonably fast reader, but it's possibly tampered slightly by the fact that it's a semi-academic volume. In any case, the ~400 wpp on [a French book I read recently](http://gallica.bnf.fr/ark:/12148/bpt6k5682013w/f3.image) (albeit on paper) would likely consistently push me over the edge.

Anyway, obviously I can up the max time if I want more accurate statistics, but on devices with sufficiently large screens coupled with sufficiently high PPI my and @Hzj-jie's situation is probably not atypical.

**Comment by AlanSP1** [comment]
For max time I use 900 seconds, just to be on the safe side.

In my opinion lower value (5 seconds) can be a problem when accuracy is in question. I rise that to 15 seconds.

But, thing is, is statistics module accurate, or not?

**Comment by Hzj-jie** [comment]
Sorry, it seems like I have misunderstood the component. But it looks inaccurate for me before I understand its implementation, which, I think, is not reasonable to regular users -- We should not expect them to understand the source code before using it.

It looks like we should also consider font size, or in another word, character count of a page to decide the maximum seconds.

But I am thinking about a simpler solution, we can ignore the time between last page turning and device suspension.

**Comment by apletnev** [comment]
Of course, you can't read a page in five seconds (usually). Min and max values it is only a range. Min in case if you skip the page, max in case if you don't read it. 

The idea with character count is nice.

**Comment by Hzj-jie** [comment]
Well, considering this is not a bug. I will close this issue. If we do want to change it soon or later, we may have another discussion thread.
