### ISSUE TITLE
Typefont too small in file manager for Kobo Mini

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2563]
* KOReader version: Since commit  #2558 two days ago
* Device: Kobo Mini

#### Issue
The size of the font for the file manager was changed a couple of days ago. The new size, smaller, is too small for Kobo Mini. I include two screenshots. The difference doesn't seem big but it is noticeable in a screen so small.
Imho, the new font size should be device dependent or configurable through settings.reader.lua

Old font size (please ignore the popup window. It is an old screenshot and the problem was solved)
![587ec8c2-ad85-11e6-807e-93dc6a671417](https://cloud.githubusercontent.com/assets/18194241/23212318/683271e8-f906-11e6-8e7b-863a1017ea97.png)
New smaller font size
![filemanager_2017-feb-22_134245](https://cloud.githubusercontent.com/assets/18194241/23212323/6cdbf980-f906-11e6-8c63-6ee8b8dabaf4.png)

**Comment by Frenzie** [comment]
It didn't seem like a big deal at the time. I suppose we should revert it then.

**Comment by retrue** [comment]
The smaller font is only a problem with the Kobo Mini. It is a good change for all the other devices.

**Comment by KenMaltby** [comment]
I have been using this for quite a while now with no problems:
For me, with my Kobo AuraHD, it is in .adds\koreader\frontend\ui\widget\menu.lua

 The "cfont", at line 122 and 325, using Notepad++
 I changed mine to 18. It looks fine but The Aura HD, has a higher res than some, which means that the fine print is clear and readable. The text is smaller, so more of the titles are visible. 

To adjust number of lines per page, change:
 Around Line 374: Screen:scaleBySize(46), -- hardcoded for now. I changed to (28), for my AuraHD)

**Comment by Frenzie** [comment]
This is now dynamic with the items per page setting from #3589. It can be easily customized at will.

## Settings → Items per page
![screenshot_2018-03-06_21-54-45](https://user-images.githubusercontent.com/202757/37057875-12f4ba5e-2189-11e8-89d1-8df37aaebff5.png)

## The items per page widget
![screenshot_2018-03-06_21-54-37](https://user-images.githubusercontent.com/202757/37057874-12d789e8-2189-11e8-81ec-65c2c36f3d91.png)
