### ISSUE TITLE
File Manager orientation should follow that of reader

### ISSUE THREAD

**Issue by asampal** [koreader/koreader#2565]
* KOReader version: 856-gee54e12
* Device: Kobo Aura One

#### Issue
I have KOReader set to read my PDFs in landscape format. When I switch to the file manager, it's shown in portrait mode forcing me to reorient the KA1.

#### Steps to reproduce
Open KOReader,  set orientation to landscape. Switch to file manager. Notice that the latter is shown in portrait mode.

**Comment by Frenzie** [comment]
See #2347. My first two comments there refer to some history regarding this issue.

The way that makes the most sense to me is that the filemanager follows the default orientation, or possibly to have a distinct filemanager orientation, but others think it makes the most sense to follow the last-read document. Some people care sufficiently much for there to be the occasional back and forth in the code itself. :-P

**Comment by asampal** [comment]
Yeah this issue needs more thinking. The goal is to not be unnecessarily bothered by an orientation switch, but, IMO, the aggravation is dependent on the state switching involving the file manager. 

e.g. if my "session" at a given time consists mostly of browsing around in the file manager with short intervals of loading a book to take a quick look, I would probably have different expectations than if I was primarily reading and just once in a while wanted to take a quick look in the file manager. For the latter, I would expect the reader's and file manager's orientation to match, while for the former state switch I wouldn't care if a particular book's orientation was different than the file manager's (and would expect the reader to use the orientation that I had set for a particular book).
