### ISSUE TITLE
How to save the dictionary's word when I searched.

### ISSUE THREAD

**Issue by yefeiyu** [koreader/koreader#2566]
* KOReader version: kobo
* Device: kobo hd

#### Issue
How to save the dictionary's word when I searched.
(When I use Stardict on other OS, it had a tag of "save" for me to save the word with the explain to "dic.txt" .)

**Comment by Frenzie** [comment]
An interesting idea, but I'm a little unsure how it would be implemented without overloading the GUI.

Okay, so in principle we seem to have an empty button spot available:
![screenshot_2017-02-23_11-10-57](https://cloud.githubusercontent.com/assets/202757/23254622/f26c2522-f9b8-11e6-87bf-6cb6e0429747.png)

Saving would presumably save as .html or .txt in the same directory as the file you're reading.

**Comment by yefeiyu** [comment]
yes!!! that is what I wanted!
I hope it be ture tomorrow.

**Comment by yefeiyu** [comment]
Up up up

**Comment by poire-z** [comment]
Implemented by #3161 or #9132.
