### ISSUE TITLE
About the Kobo Aura One

### ISSUE THREAD

**Issue by moshpirit** [koreader/koreader#2574]
* Device: Kobo Aura One

#### Issue

I'm considering buying a Kobo Aura One but PDFs reading is highly important for me since I need to read lots of scientific PDFs for my career. So I saw [this 2015 video](https://www.youtube.com/watch?v=rsJizVAMpDQ) about it and wanted to know if there's any improvement about PDF reading and crops (specially for documents made on LaTeX). The thing is that I searched on Reddit if there's anyone in my situation and found [this post](https://www.reddit.com/r/kobo/comments/5ttm2s/koreader_on_aura_one/) where a co-founder of Koreader said:

>One of the maintainers of KOReader here. Kobo aura one port is almost there, but not fully compatible yet. I will be working on it in the following weeks. At the mean time, I recommend you file an issue on our github project so we can notify you when it's ready.

So since I can't see his issue, I'm creating this one and using it also to know if there has been any improvement to consider about PDFs reading (seeing how great the support is here, I'm expecting really good news).

Thank you so much!!

**Comment by Frenzie** [comment]
It's my understanding that the program should already work fine for basic reading but that wifi is currently non-functional. See #2553.

**Comment by moshpirit** [comment]
Thank you! hmm looks like the WiFi issue is already solved, isn't it? so I expect it to be implemented in the next release (maybe in a month?) I think I can wait till then for using it.

BTW, I've just [re-checked the video](https://youtu.be/rsJizVAMpDQ?t=21m30s) (I saw it a couple of months ago) and I mixed the official PDF reader and the Kodeader one and I think it works perfectly :) thanks a lot for this!!

**Comment by AlanSP1** [comment]
Download latest nightly from here: http://build.koreader.rocks/download/nightly/

KA1 is completely supported. You only need to use latest KSM8 (with last patch for KA1). You don't need to wait for anything.

**Comment by Frenzie** [comment]
I'll close this now.

**Comment by houqp** [comment]
FWIW, the only remaining issue right now is koreader doesn't support tunning color of the frontlight
