### ISSUE TITLE
FR: Display images of books in file manager

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2576]
* KOReader version: up to c1318827
* Device: independent

#### Issue

Comparing to all other implementations, current file manager looks simple. We may consider to provide more fancy information. Say, images of books, progress, etc.

**Comment by Frenzie** [comment]
I'm not entirely sure how helpful that would be. For icons it works great:

![screenshot_2017-02-25_08-48-31](https://cloud.githubusercontent.com/assets/202757/23329365/351d367a-fb37-11e6-9f90-289ae00251a7.png)

But for actual books — those aren't designed to be viewed as icons:

![screenshot_2017-02-25_08-49-13](https://cloud.githubusercontent.com/assets/202757/23329371/5ce9f3c8-fb37-11e6-9683-f6c8db9ac944.png)

Still, if you're going to generate such thumbnails for a two or three line detailed view then I suppose you might as well display them on the smaller view.

Here's a (bad) quick exploration of what a two or three line entry could look like.

![untitled](https://cloud.githubusercontent.com/assets/202757/23329460/1b2b5254-fb39-11e6-9a64-f0c88415bae9.png)

**Comment by KenMaltby** [comment]
This sounds like a bad idea, to this Kobo owner, it would make having a large library more problematic.

**Comment by Frenzie** [comment]
Oh, I'm also against this, but it's clearly a popular display mode and the default in, e.g., Windows. The way I see it pretty much all graphical file managers offer a choice between one or more of the following:

1. (detailed) list 
2. (large) icons or tiles.

![virtualbox_ie10 - win8_25_02_2017_15_57_50](https://cloud.githubusercontent.com/assets/202757/23332090/2f5fe124-fb73-11e6-8d12-ceb6cb1826c6.png)

**Comment by Hzj-jie** [comment]
To me, I prefer to have progress displayed in file list. I am not a big fan of thumbnails also, but I just compare koreader with other implementations.
We can definitely have two modes.

**Comment by KenMaltby** [comment]
The progress displayed graphically sounds good for the History list (I guess the cover could work there too) but don't think it would make much sense for books that haven't been opened yet.

**Comment by houqp** [comment]
This was one of the goal for the original koreader home app, to have multiple view modes that users can switch between.

**Comment by Frenzie** [comment]
Fixed by #2940.
