### ISSUE TITLE
FR: nicer keyvaluepage

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2578]
Copied from https://github.com/koreader/koreader/issues/2562#issuecomment-282469008

I'd like this:

![screenshot_2017-02-25_09-16-33](https://cloud.githubusercontent.com/assets/202757/23329547/26ac1922-fb3b-11e6-98ae-b392fe596b8b.png)

To go more in this direction (Evince properties dialog):

![screenshot_2017-02-25_09-16-17](https://cloud.githubusercontent.com/assets/202757/23329548/2e0d5d84-fb3b-11e6-9992-8a3a4d26eb55.png)

**Comment by retrue** [comment]
It is true that the current Book Information screen is scarce and needs improvement but, in my opinion, your proposal includes too technical information .
My idea is diferent. Book Information should include other information from the metadata of the ebook, in addition to the current one, like tags and summary.
It would be nice a button inside Book Information that linked to Book Status (if book status is available, that is, the file has already been opened. If it has not, that button should appear grayed). And a similar button inside Book Statuts that linked to Book Information.

**Comment by Frenzie** [comment]
I'm talking about the layout, not about the actual content.

**Comment by retrue** [comment]
Book Information is accessed from the File Manager and you already have there Location and size. But it would be handy to have location and size if you accessed Book Information from that future button in Book Status  =P

**Comment by KenMaltby** [comment]
I can see a logical difference between "Book Information"  and "File Properties".  Each would have their place, (although it looks like the "File Manager" is being replaced with a "KOReader" (Book) "Browser")
