### ISSUE TITLE
The color of fonts in koreader is not black as Kindle

### ISSUE THREAD

**Issue by strategist922** [koreader/koreader#2585]
* KOReader version: koreader-nightly 20170209
* Device: Kindle PaperWhite PW3

#### Issue
The color of fonts in koreader is not as black as Kindle
#### Steps to reproduce
open any pdf has the same issue

**Comment by Frenzie** [comment]
You say PDF. Does that mean the issue doesn't occur with EPUBS?

**Comment by houqp** [comment]
Have you tried tuning the font darkness from the bottom control panel?

**Comment by Hzj-jie** [comment]
I doubt whether this issue also triggers #2606 .

**Comment by Frenzie** [comment]
Fixed by #3634.
