### ISSUE TITLE
FR: Adding exit and restart options to hamburger menu

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#2588]
With reorganizing menus, we can also add exit and restart options to hamburger menu, as suggested here: https://github.com/koreader/koreader/pull/2577#issuecomment-282494170

**Comment by Frenzie** [comment]
On which platforms do one or both of these make sense?

Makes sense:
* Kobo - that's where we already have a [poweroff](https://github.com/koreader/koreader/blob/f402ee5f6ff2769fee1f0bca747f5b0b2eafce1b/frontend/device/kobo/device.lua#L476) function
* Kindle???

Doesn't:
* Android
* Ubuntu Touch
* (Desktop emulator)

**Comment by AlanSP1** [comment]
I have Kobo Aura H2O and I know that I can turn it off with long power button press. Also restart could be useful because memory leaks.

For other platforms, I don't know if it will be useful, or even viable.

**Comment by Frenzie** [comment]
Right, I just meant that as an implementation note. On Kobo it's easy to add and it makes sense. It's other platforms like Kindle where i don't know if it makes sense or if it's viable.

**Comment by pazos** [comment]
>  It's other platforms like Kindle where i don't know if it makes sense or if it's viable.

It makes sense. But reboots (and cold boots) are sloooow.

About viability @NiLuJe knows :dancer:

**Comment by houqp** [comment]
we can only include these menu items for supported devices

**Comment by Frenzie** [comment]
That's the question, not the answer. :-p

**Comment by pazos** [comment]
@houqp: supported = tested ?

But, of course, it should be only viewable with show avanced settings enabled ;)

**Comment by NiLuJe** [comment]
By "restart" you mean a reboot of the device, right?

FWIW, it should be perfectly safe on a Kindle with a simple ```shutdown -r now```. But as @pazos mentioned, reboots are horrendously slow on Kindles, and of dubious usefulness, to add, so, meh?

**Comment by houqp** [comment]
yes, supported == tested :) I think restart is mostly only useful for kobo

**Comment by pazos** [comment]
we don't want to close the ui before the reboot, because reader.lua will end and koreader.sh will invoke nickel or back to KSM.

**Comment by houqp** [comment]
Yup, just flush all settings and invoke the shutdown command without exiting koreader.

**Comment by houqp** [comment]
Actually, that's how we are doing poweroff, see: https://github.com/koreader/koreader/blob/master/frontend/ui/uimanager.lua#L53

**Comment by Frenzie** [comment]
Implemented by #2888.
