### ISSUE TITLE
After wake-up the screen of Kobo Aura H2O stays freesed. 

### ISSUE THREAD

**Issue by chunosoff** [koreader/koreader#2590]
* KOReader version: koreader-nightly 20170209
* Device: Kobo Aura H2O

#### Put the Aura H2O sleep wake it up.

**Comment by pazos** [comment]
@chunosoff  more info, please:  
way of boot koreader? Ksm, fmon..
Is nickel working fine?
FW version of your device

**Comment by houqp** [comment]
@chunosoff also can you trigger this bug with a fresh koreader start?

**Comment by chunosoff** [comment]
Sorry, I've maked full reset and fresch Nickel without any books has the same problem. Now I think it is a Hardware problem. Sorry for disturbing you

**Comment by Frenzie** [comment]
No problem. I hope you can still claim warranty!
