### ISSUE TITLE
Status bar disappears while a reading PDF book.

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2598]
* KOReader version: v2015.11-877-ga2f2ac0. Interface language set to Russian.
* Device: Kindle (7th generation) firmware Kindle 5.8.7.0.1 (3115940037)

#### Issue
Status bar sometimes not shown when reading PDF.
#### Steps to reproduce
Read PDF book with status bar enabled. Status bar disappears and appears for no apparent reason.

**Comment by Frenzie** [comment]
You mean without tapping on or near the status bar?

**Comment by ilyats** [comment]
yes, i saw no pattern when it happens.

**Comment by Frenzie** [comment]
Is the PDF publicly available by any chance?

**Comment by ilyats** [comment]
[Band 2.pdf](https://github.com/koreader/koreader/files/889354/Band.2.pdf)

**Comment by ilyats** [comment]
[Band 2.sdr.zip](https://github.com/koreader/koreader/files/889377/Band.2.sdr.zip)

**Comment by Frenzie** [comment]
Unfortunately I haven't been able to produce such an effect by simply going back and forward a whole bunch. But if there's something slightly off about the input on Kindle (cf. #2599) could that also be a possible explanation?

**Comment by ilyats** [comment]
Do you mean the touchscreen on my device may have some quircks? It could be an explanation. (I was not aware that one can hide and unhide statusbar by tapping it.)

**Comment by Frenzie** [comment]
Not unless you have comparable issues in the stock software as well. I meant that KOReader might be misinterpreting or perhaps missing some event or other. We'd need someone who knows more about Kindle. @NiLuJe maybe?

**Comment by NiLuJe** [comment]
Stupid question: which "status bar" are we talking about?

**Comment by NiLuJe** [comment]
If you meant the bottom status bar: can't reproduce on a PW2. Taps are registered just fine there, too.
