### ISSUE TITLE
flipping mode does not work #1894

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2599]
* KOReader version: v2015.11-877-ga2f2ac0
* Device: Kindle 7th generation, firmware 5.8.7.0.1

#### Issue
flipping mode does not work while reading PDF
#### Steps to reproduce
Reopening #1894  (can I reopen it?)
Open PDF file, push top left corner to start flipping mode. Book icon appears, screen resolution changes to fit the whole page, but sweeping finger makes screen redraw but has no other effect.

**Comment by Frenzie** [comment]
You can flip with taps or by using the status bar (cf., #2707). I don't think swipes are supposed to do anything.

**Comment by ilyats** [comment]
Flipping mode is described here https://github.com/koreader/koreader/wiki/Tips-and-Tricks Panning as described there makes page change to another one, but then KOReader returns to the original page. Probably it falsely detects sweep to right.

**Comment by Frenzie** [comment]
Oh, it works as described for me, except that it says "In page flipping mode panning (moving your finger tip on the screen slowly) *horizontally* will flip page with steps 1, 2, 5, 10, 20, 50 and 100 according to the panning distance" which should be *vertically*.

**Comment by ilyats** [comment]
It says panning (moving finger slowly) horizontally should flip buy one of the fixed amount of pages, while panning vertically should flip by amount determined by number of pages in document and distance of swiping. Swiping fast to right should bring back the initial page. What seems to happen for me is false positive for the latter gesture.

**Comment by ilyats** [comment]
I got it from a torrent, I can send it to you.

**Comment by Frenzie** [comment]
Oh yes, this actually works reasonably well for me on Kobo. Unfortunately I can't do anything about Kindle.

**Comment by NiLuJe** [comment]
Works for me on a PW2.

Once in flipping mode, tapping switches pages, and a swipe goes back to my original location.

If that's not the desired behavior, we have a bigger problem, because my H2O behaves the exact same way ;).

**Comment by ilyats** [comment]
According to the docs
<https://github.com/koreader/koreader/wiki/Tips-and-Tricks>, swipes should
flip certain amount of pages forwards or backwards.

вс, 8 июл. 2018 г., 2:19 NiLuJe <notifications@github.com>:

**Comment by NiLuJe** [comment]
Panning != swiping.

And it indeed does roughly that, both on my PW2 & H2O.

The panning gesture detection is moderately unreliable on both, though ;).
