### ISSUE TITLE
Question, can something be done about case sensitivity inside Epub files?

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2600]
* KOReader version: N/A
* Device: Kobo, probably others

#### Issue
Weeks ago, I found an epub file that looked well using Calibre viewer but had missing images on KOReader. Unzipping the epub I discovered that the problem was that the epub code looked for an image_name.JPG and the image included was image_name.jpg. File extension was case-sensitive for KOReader but it was not for Calibre viewer.
Doing some texts today, renaming file extensions inside of an epub, I discovered that all file extensions that I tried were case-sensitive for KOReader, PBChess-Coolreader and Nickel. However, Calibre viewer and SumatraPDF (I tried ony under Windows) showed the epub perfectly.
Can be something about it done from KOReader? Maybe indicating that it should ignore case-sensitivity in file extensions? Or it is a problem affecting cre or the whole Linux filesystem?
It could serve to show well some epubs files that were not perfectly created. I don't know if mobi files have the same problem.

#### Steps to reproduce

Just unzip an epub file and rename the file extensions of some files (for example, from jpg to JPG, htm to HTM).

**Comment by Frenzie** [comment]
Is the EPUB publicly available? I'd be curious to see what my Calibre in Linux does.

**Comment by retrue** [comment]
Just take any epub you have. Unzip it, rename some file extensions, from png to PNG, jpg to JPG, htm to HTM, zip it again and rename to epub.
I'll restart my computer to switch to Linux and see myself what Calibre viewer does.

**Comment by Frenzie** [comment]
I'm not sure if there's a good solution here. Trying to write a workaround might potentially cause more trouble than it solves.

**Comment by Frenzie** [comment]
I'll close this since calibre behaves the same.
