### ISSUE TITLE
Background of some icons is not transparent on Kindle

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2606]
* KOReader version: Up to f47d257
* Device: Independent, but it seems more obvious on Kindle

#### Issue

The background of hamburger menu item is not transparent, which is more obvious on Kindle voyage.

#### Steps to reproduce

You can see a very light gray rectangle behind the hamburger icon.

**Comment by Frenzie** [comment]
The background of none of the icons is transparent. They show up as black otherwise. The background of the hamburger icon is, however, completely white.

**Comment by Hzj-jie** [comment]
That's weird. Indeed I can only see the rectangle of hamburger on Kindle. So the background color should not be the same as other icons. I will double confirm tomorrow.

**Comment by Hzj-jie** [comment]
![image](https://cloud.githubusercontent.com/assets/1188462/23560242/9704fe02-ffee-11e6-9d99-680491b1bfb3.png)

Do you see the gray background of hamburger icon?
I use paint tool to detect the color of the background of the icons, they are all 0xffffffff, which is really weird.

**Comment by retrue** [comment]
Could it be a visual illusion?
The brain sees a gray area around the menu that really doesn't exist?

**Comment by Frenzie** [comment]
> Do you see the gray background of hamburger icon?

Yes, loud and clear. Could it have something to do with the PNG palette? I just saved it from Inkscape without paying any attention, but maybe the other PNGs are custom-tailored to be black & white or something.

**Comment by Hzj-jie** [comment]
@retrue, it's not likely. You will see the rectangle after zooming in.
@Frenzie, you remind me. Maybe the black is not so black, instead of the white.

**Comment by Frenzie** [comment]
GIMP says the existing icons are grayscale and the one I made is RGB. pngquant compresses it down to 9 indexed colors which is effectively the same thing as grayscale but I'm not really sure how to make a grayscale PNG file. You can test the pngquant one attached below if you want. It all looks the same in the emulator.

![menu-icon-fs8](https://cloud.githubusercontent.com/assets/202757/23568640/b72618e8-005b-11e7-9f64-965c940b49a2.png)

**Comment by houqp** [comment]
Weird, is this a voyage specific thing? It looks fine on my Kobo A1. Do you get this background consistently even with a fresh start? I wonder if it has something to do with the background highlight triggered by taps.

If the wifi icon doesn't have this issue for you, you can give the build command I used for those svgs a try: https://github.com/koreader/koreader-icons/blob/master/Makefile#L8.

**Comment by Hzj-jie** [comment]
The last one is awesome.

**Comment by Hzj-jie** [comment]
Sorry, I missed your last comment. Yes, other icons work well. It should relate to the gray scale, though I have almost no idea about the root cause.

**Comment by Hzj-jie** [comment]
Same issue happens on the shift key and enter key in soft keyboard.

**Comment by robert00s** [comment]
@Hzj-jie 
Can you check icons after lastest update? This should be fixed in #3634.

**Comment by Frenzie** [comment]
I've heard some reports on the grapevine that it's fixed and it should be fixed, so closing now. :-)
