### ISSUE TITLE
Deleting highlights in bookmarks does not take effect

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2609]
* KOReader version: Up to f47d257
* Device: independent

#### Issue

It only deletes the entity in bookmarks, but the highlight still shows up in the page.
I remember I have reported this issue before. I cannot recall whether it has been fixed, and this is a regression, or we have never fixed this issue.

**Comment by houqp** [comment]
I don't recall seeing report for this issue before, so likely it was never fixed ;)

**Comment by KenMaltby** [comment]
I also mentioned not being able to dismiss the highlight from the page, but I figured there was some trick to it that I didn't know.

**Comment by Hzj-jie** [comment]
Emmm, maybe I found this issue for a while, but I have not reported it. Or, indeed I come from… a different time line. :)
Anyway, deleting highlights from the page always works well for me. Though as @KenMaltby said, it's a little bit tricky.

**Comment by chrox** [comment]
This is by design, at least when it was implemented. The only way to delete an highlight is tapping the highlight you intent to delete and select the 'delete' option in the pop-up dialog. But deleting highlights from the bookmarks window is also nice and convenient.
