### ISSUE TITLE
Black rectangle in menu

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2611]
* KOReader version: last nightly
* Device: Kobo Mini, possibly others

#### Issue
When selecting hambuger icon or magnifier icon, a black rectangle appears in menu bar.

![filemanager_2017-mar-04_080228](https://cloud.githubusercontent.com/assets/18194241/23577272/07619e22-00bb-11e7-925a-55e69babdce1.png)

**Comment by Frenzie** [comment]
Sorry about that.
