### ISSUE TITLE
kodev script should probably include something like eval "$(luarocks path --bin)"

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2613]
* KOReader version: ce8f568
* Device: desktop

#### Issue
Even after installing busted properly (cf. [here](https://github.com/koreader/koreader/blob/ce8f568486c57fcfca1baf7741eb8e6268d2b59b/.ci/install.sh)) it still wasn't a part of my path.

**Comment by Frenzie** [comment]
Oh yes, here it is in the ci code (possibly originally added by me now that I think of it)

https://github.com/koreader/koreader/blob/ce8f568486c57fcfca1baf7741eb8e6268d2b59b/.ci/common.sh#L62-L65

Except for kodev it should be phrased a little bit more like this
```bash
if [ -f /usr/local/bin/luarocks ] || [ -f "${HOME}/.luarocks/bin" ]; then
    # add local rocks to $PATH
    eval "$(luarocks path --bin)"
fi
```

**Comment by houqp** [comment]
There is an activate command in kodev that I use regularly ;) We can add a detection for busted in the beginning of kodev and prompt user to run the activate command if those required bin scripts are missing in the path.

**Comment by Frenzie** [comment]
Hm, so maybe just change https://github.com/koreader/koreader/blob/40e19dbc37b8b873d8c6ce69a1440755e6878399/kodev#L366 to `--bin`. I suspect that what was intended in the first place, because there's no difference between the output of `luarocks path` and `luarocks path bin` on my system.

However, I do think that just like `run` automagically does `fetch-thirdparty` and `build`, `test` should also pretty much Just Work™.[1] A prompt to run `activate` would do the trick if there are concerns about auto-running `activate`.

[1] Actually this would also include setting up busted.

**Comment by houqp** [comment]
> However, I do think that just like run automagically does fetch-thirdparty and build, test should also pretty much Just Work™.[1] A prompt to run activate would do the trick if there are concerns about auto-running activate. Maybe something based around which busted and which luarocks. If luarocks but no busted, run/prompt for luarocks path --bin. If still no busted, prompt for… I don't know, install-busted. :-P

Agreed. @chrox and I also talked about building self-contained luarocks from source for dev environemnt so we can have full control over the lua dependency and make sure everything is setup correctly.

**Comment by Frenzie** [comment]
Closing now since the original issue was resolved.
