### ISSUE TITLE
dictionary shows only one definition

### ISSUE THREAD

**Issue by enigma90** [koreader/koreader#2622]
![2017-03-09_113550](https://cloud.githubusercontent.com/assets/18080825/23734845/a92231f4-04bc-11e7-99f6-e6c627b6b9b2.jpg)

* KOReader version: koreader-nightly-20170308
* Device: KOBO Touch

#### Issue
When I check up a biographical last name that has more than 2 definitions,  the dictionary only shows the last one. I've converted a part of the dictionary into text and stardict formats for you to test. (In the sample, only the definition of Wilson7 shows up.)

ops. can't upload zip file....

**Comment by Frenzie** [comment]
I'll close this as a duplicate for #2951 (although this one's older).
