### ISSUE TITLE
Pre-reflowed pdf file format

### ISSUE THREAD

**Issue by sirwul** [koreader/koreader#2623]
koreader can reflow scanned PDF with built-in K2pdfopt now. 

> K2pdfopt works by **converting** each page of the PDF/DJVU file to a bitmap and then **scanning** the bitmap for viewable areas (rectangular regions) and **cutting** and **cropping** these regions and assembling them into multiple smaller pages without excess margins so that the viewing region is maximized. Making use of this method, k2pdfopt can re-flow text lines, even on scanned documents (see the Winnie the Pooh example below). You can see another example of how k2pdfopt works on this help page. [http://www.willus.com/k2pdfopt/](url)
however,these converting, scanning, cutting and cropping operations need a lot of computation which is limited in e-readers by battery and embedded CPU. So PDF reflowing in e-reader works bugy and reduce the battery time.
I wander if possible to do these heavy operation (converting, scanning, cutting and cropping ...) on PC to build a pre-compiled file and then  koreader rendering it in e-reader.
I don't exactly know how K2pdfopt work in koreader.  I just want to make it better.

**Comment by Frenzie** [comment]
Did you visit the link? I think it pretty much answers your question.

**Comment by sirwul** [comment]
I hope to change font size as I read a book instead a pdf with fixed font size.

**Comment by houqp** [comment]
If you enable reflow mode for pdf, you will be able to change the font size.
