### ISSUE TITLE
OPDS Catalog's Internet Archive doesn't work

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2625]
* KOReader version: last development version
* Device: Kobo Mini

#### Issue

Internet Archive doesn't work. 

#### Steps to reproduce

When you select it, it appears three options:
- Alphabetical By Title: Select it and you will get a list "Titles: A, Titles : B, ..., Titles: Z." But it doesn't do anything when you select a letter.
- Most Downloaded Books: It doesn't do anything when you select it.
- Recent Scans: Again, it doesn't do anything when selected.

**Comment by robert00s** [comment]
e.g: http://bookserver.archive.org/catalog/alpha/a/0
"internal server error"
I think problem is with archive.org servers.

**Comment by retrue** [comment]
https://archive.org/details/texts works though.
Maybe the servers are not down but the Internet address for the catalog has changed?
No idea.

**Comment by robert00s** [comment]
On OPDS Browser on my Android also doesn't work.

**Comment by houqp** [comment]
This is a server problem from archive.org.

**Comment by Frenzie** [comment]
Servers are working and so is the OPDS catalog. Closing now.

**Comment by retrue** [comment]
This is a doubt not related to KOReader.
I just checked Internet archive and it works, but it works differently.
 http://bookserver.archive.org/catalog allows you to download books alphabetically by title, by most downloads and recent scans. _Most downloads_ and _Recent scans_ work just like before. But the webmaster at archive.org has changed the behaviour of alphabetically by title. And now, it only shows books depending on your location. I am in Spain, so it shows only Spanish books.
How could I access to the English books from KOReader?
Any idea?

**Comment by Frenzie** [comment]
I think it's just that the `¡` character isn't used in languages other than Spanish and it's sorted first. The page number count is somewhat deceptive and it'll load more pages if you keep pressing right. It does however make it rather hard to get beyond the first few books from the KOReader GUI. I'd say there's definitely some kind of UX issue here but I don't see a quick fix. You can bring up a dialog by long-pressing on the page numbers but entering a number like 30 doesn't help you one bit.

**Comment by retrue** [comment]
Yup, you are right. It was the Spanish character **¡**. So right now it is a pain in the @$$ to browse the internet archive looking for a specific title. But if you are interested in the most downloaded books, it will work well.
Thanks for replying.
