### ISSUE TITLE
OPDS: Crash when downloading books with unknown characters in title

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2627]
* KOReader version: last development version
* Device: Kobo Mini

#### Issue
Downloading books from ManyBooks work if you don't get #2626 bug. But here we have a crash if the title of the book to download has an unknown character. You will be able to select the book, and begin the download, but before it finishes, KOReader will crash and close itself, exiting to KSM or Nickel.

#### Steps to reproduce
Any title with the unknown character � will crash the device. You can see one going to
OPDS Catalog->ManyBooks->Genres->Classic and you will see there Be�wulf. Select it, begin the download and after some seconds, KOReader will crash and close.

[crash.log.txt](https://github.com/koreader/koreader/files/834188/crash.log.txt)

**Comment by robert00s** [comment]
We can close this issue.

**Comment by retrue** [comment]
We cannot close this issue yet. See https://github.com/koreader/koreader/pull/2628#issuecomment-286983197
