### ISSUE TITLE
Can not support Markdown

### ISSUE THREAD

**Issue by PentiumRabbit** [koreader/koreader#2632]
* KOReader version: v2015.11-894
* Device:kobo aura one
#### Issue
if this can support markdown ,it is very useful

**Comment by Frenzie** [comment]
I think "Markdown" means too many things besides the basics. But why not just generate an EPUB or PDF from the Markdown file?

**Comment by Frenzie** [comment]
As a random thought, Markdown to HTML could potentially also be done since I came across https://github.com/bakpakin/luamd

However, I'm not sure what a sensible GUI for that would be exactly.
