### ISSUE TITLE
Missing last_xpointer in booktitle.sdr/metadata.epub.lua crashes KOReader

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2635]
* KOReader version: v2015.11-896-g4316284
* Device: Kobo Glo HD

#### Issue

KOReader crashes when attempting to open book with missing last_xpointer in sdr metadata.epub.lua.
(Deleted too much when deciding to remove statistics records after turning off the statistics plugin)
The only way to be able to open the book again is to purge sdr record.
If KOReader is set to automatically open last file, the record needs to be deleted from a computer.

Relevant crash.log entries:
```
[!] doShowReader coroutine crashed:
frontend/apps/reader/modules/readerrolling.lua:524: bad argument #1 to 'getPageFromXPointer' (string expected, got nil)
stack traceback:
	frontend/apps/reader/modules/readerrolling.lua:524: in function '_gotoXPointer'
	frontend/apps/reader/modules/readerrolling.lua:465: in function 'v'
	frontend/apps/reader/readerui.lua:325: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/readerui.lua:390: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:352: in function <frontend/apps/reader/readerui.lua:351>03/12/17-21:55:35 INFO  quiting uimanager
03/12/17-21:55:35 INFO  no dialog left to show
03/12/17-21:55:35 INFO  quiting uimanager
```

#### Steps to reproduce
1. Delete line starting with `["last_xpointer"]` in `booktitle.sdr/metadata.epub.lua` of previously opened book
2. Open book with koreader

**Comment by houqp** [comment]
I will look into this, looks like it only happens when you have `copt_view_mode` in the config while missing the `last_xpointer` key.
