### ISSUE TITLE
Can't long-press lookup word inside bookmark tap zone

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2636]
* KOReader version: v2015.11-896-g4316284
* Device: Kobo Glo HD

#### Issue
Can't long-press lookup word inside bookmark tap zone.
This happens with short words, small fonts and very narrow margins.

#### Steps to reproduce
Try these settings in a books `booktitle.sdr/metadata.epub.lua`,
then try long-pressing a short word inside the bookmark tap zone
(default 1/8 width and height, upper right corner)
```
["copt_page_margins"] = {
    [1] = 8,
    [2] = 4,
    [3] = 8,
    [4] = 4
},
["copt_line_spacing"] = 90,
["floating_punctuation"] = 0,
["font_size"] = 18,
```

**Comment by a-kohout** [comment]
Did some more testing to better illustrate the problem.

Example: 
Words inside the red area do not respond to long-press. Words fully inside that area thus cannot be looked up.
![epub-example](https://cloud.githubusercontent.com/assets/26367956/23951154/a1b6afc8-098d-11e7-99d8-3f8f6aa04a6d.png)

There's a twist to this bug with PDFs though. Long-pressing a word inside the red area sets a bookmark and toggles page flip mode on.
Another long-press toggles flip mode back off.
Words inside this area still can't be looked up though. 
![pdf-example](https://cloud.githubusercontent.com/assets/26367956/23951296/fb8ec706-098d-11e7-836b-5ba6f051c433.png)

**Comment by a-kohout** [comment]
I just tested with a clean koreader installation (v2015.11-971-gf1c0b4b) to rule out anything configuration-related.
Btw device is Kobo Glo HD, so it's not just Android.

**Comment by Frenzie** [comment]
I must've accidentally labeled this while I was going through issues last week. I probably meant to click bug which is right underneath Android. :-)

> There's a twist to this bug with PDFs though. Long-pressing a word inside the red area sets a bookmark and toggles page flip mode on.

Actually this isn't normal page flip mode. It's bookmark flip mode. https://github.com/koreader/koreader/wiki/Tips-and-Tricks#2-bookmark-browsing-mode-only-for-pdf-and-djvu

**Comment by protist** [comment]
FWIW I also get this bug on a Kobo H2O running v2015.11-1023-g773e24f.
