### ISSUE TITLE
Can't delete Folder containing epub or pdf

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2637]
* KOReader version: v2015.11-896-g4316284
* Device: Kobo Glo HD

#### Issue
Trying to delete a Folder containing an epub or pdf (with or without sdr record) yields the message
`An error occured while trying to delete /mnt/onboard/...`
Deleting the epub, then the empty folder works.
The logfile doesn't show anything relevant

#### Steps to reproduce
Long press a folder containing an epub in the file manager, then select delete

**Comment by Hzj-jie** [comment]
Indeed we do not have a deleting folder function, but only deleting file. Since we are running on Linux, it happens to be able to delete a folder by using same command as deleting a file.

**Comment by a-kohout** [comment]
Since rm -r happily deletes single files, couldn't that function be updated to handle folders as well?

**Comment by Hzj-jie** [comment]
I won't have objections to add a removing folder functionality. I will work on it soon or later.

**Comment by houqp** [comment]
why not use purgeDir function? https://github.com/koreader/koreader-base/blob/master/ffi/util.lua#L172

**Comment by cramoisi** [comment]
thinking about this, it could be great to be able to create a folder at the place the file manager is without using the tedious terminal emulation (and thus, typing all the path)

**Comment by tomatosoupcan** [comment]
Would also like to see this, seems it worked on older builds but no longer works on the newer ones.

**Comment by KenMaltby** [comment]
Why not simply connect to your PC, and use the file management tools and processing power you have there?

**Comment by tomatosoupcan** [comment]
Because I use my e-reader on the go and don't carry a pc around with me to supplement deleting folders.

**Comment by Frenzie** [comment]
@Hzj-jie Btw, I generally don't go to base but I just noticed it has a purgeDir function ready for use:

https://github.com/koreader/koreader-base/blob/8c6551aa615a79ed5d3892f993806056997d3009/ffi/util.lua#L172-L194
