### ISSUE TITLE
Unhighlight grayed out in dictionary menu

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2640]
* KOReader version: v2015.11-896-g4316284
* Device: Kobo Glo HD

#### Issue
"Unhighlight" is greyed out in the (long-press) dictionary menu.
The highlight becomes unremovable if located inside the menu tap zone as the single tap menu doesn't work there.

#### Steps to reproduce
1. Long press word.
2. Click "highlight".
3. "highlight" changes to "unhighlight", but changes to a greyed-out state.

**Comment by Hzj-jie** [comment]
Same as #2283, but it does not like a low-hanging fruit.

**Comment by Frenzie** [comment]
Closing now because it's a duplicate and swipe for menu makes it so you can tap on it.
