### ISSUE TITLE
Screenshot gesture doesn't work while the dictionary is open

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2641]
* KOReader version: v2015.11-896-g4316284
* Device: Kobo Glo HD

#### Issue
Screenshot gesture doesn't work while the dictionary is open, either in dictionary or wikipedia modes.
Screen flashes after sliding diagonally, but "saving screenshot" message doesn't appear/screenshot doesn't get created.
Screenshots do work in search mode or while "Do you want to turn on wifi" is being displayed after touching wikipedia whilst offline.

#### Steps to reproduce
1. Long-press word to look up
2. Slide diagonally

**Comment by retrue** [comment]
Duplicated. See #2248
