### ISSUE TITLE
Nightmode inverts sleep and poweroff images as well

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2642]
KOReader version: v2015.11-896-g4316284
Device: Kobo Glo HD

#### Issue
Nightmode inverts sleep and poweroff images as well.
Is this intentional?

#### Steps to reproduce
1. Turn on nightmode
2. Sleep the device

**Comment by Frenzie** [comment]
Also see #2571, except that this would probably be quite easy to implement.

**Comment by robert00s** [comment]
This is done in #4853 so I'm closing.
