### ISSUE TITLE
Can't insert ["auto_suspend_timeout_seconds"] in settings.reader.lua

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#2644]
* KOReader version:v2015.11-896
* Device:Kobo aura H2O

#### Issue
Can't insert ["auto_suspend_timeout_seconds"] in settings.reader.lua.
I insert this in settings.reader.lua, and then this file will become to default.

**Comment by AlanSP1** [comment]
This is not used at the moment AFAIK.

You can find instructions here: https://github.com/koreader/koreader/pull/2349#issuecomment-261240696 (or read whole discussion there, to found out all info).

You need to use something like this:

["suspend_screensaver"] = {
["message"] = "eBookReader is suspended",
["timeout_sec"] = 900

And you need to respect syntax, so first thing to do is save on your computer working settings.reader.lua file. In case it returns to defaults, you messed syntax somewhere. I learned this hard way...

**Comment by KenMaltby** [comment]
When I update KOReader, I modify the koreader  folder from the download .zip with this:
For me, with my Kobo AuraHD, it is in .adds\koreader\frontend\ui\widget\menu.lua

 The "cfont", at line 122 and 325, using Notepad++

 I changed mine to 18. It looks fine but The Aura HD, has a higher res than some, which means that the fine print is clear and readable. The text is smaller, so more of the titles are visible. 

To adjust number of lines per page, change:
 Around Line 374: Screen:scaleBySize(46), -- hardcoded for now. I changed to (28), for my AuraHD)

\koreader\frontend\apps\reader\modules\readerfooter.lua Line 57 return os.date ("%I:%M")

----------------------------------
In /koreader/frontend/ui/uimanager.lua
By default, the timeout is set to 60*60 (1 hour). You can change it by tweaking the reader setting  auto_suspend_timeout_seconds .  To 480 for 8 min. Around line 720.

------------------------------------

Add line:

PeriodicAutoSync=false

in the .kobo\Kobo\Kobo eReader.conf file under [ApplicationPreferences]


----------------------------------------

Then after using that modified koreader  folder to apply the update, and the "settings.reader.lua" is updated/created it shows:      ["auto_suspend_timeout_seconds"] = 480,

Luck;
Ken

**Comment by seacatwu** [comment]
@KenMaltby 
I set 10*60  In /koreader/frontend/ui/uimanager.lua, and it's working.

**Comment by Hzj-jie** [comment]
settings.reader.lua is preferred, otherwise you will lost the setting after an OTA upgrade.
But anyway, good to know you suceeded.
