### ISSUE TITLE
Swedish language missing

### ISSUE THREAD

**Issue by jony0008** [koreader/koreader#2645]
* KOReader version: nightly v2015.11-897-gd206abc
* Device: Kobo Aura

#### Issue
Swedish language missing from latest nightly build. Please add it in next nightly release.

**Comment by Hzj-jie** [comment]
It looks like we do not have Swedish support. We need to translate strings first.

**Comment by jony0008** [comment]
@Hzj-jie I have translated them on Transifex already.

**Comment by jony0008** [comment]
Please merge them.

**Comment by Frenzie** [comment]
I checked http://ota.koreader.rocks/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-898-gdccbf4c.targz and Swedish is in /i10n/sv

Do you mean it's not showing in the GUI?

**Comment by houqp** [comment]
Ha, I forgot this is still a manual process, see: https://github.com/koreader/koreader/blob/master/frontend/ui/language.lua#L36.

We need to add it to the table. In the long term, this table should be generated at runtime by looking at the i10n directory ;)

**Comment by Frenzie** [comment]
Ah, I thought it was all automated. We should check if there are any others
missing then (although I suppose the translators would mention it).

**Comment by jony0008** [comment]
I think it would be a good idea to check it, sometimes the translators doesn't check if it has been added.

**Comment by robert00s** [comment]
Please remove `pl_PL` language from transferix: https://www.transifex.com/houqp/koreader/language/pl_PL/
For Polish is used `pl` https://www.transifex.com/houqp/koreader/language/pl/
