### ISSUE TITLE
'./kodev release android' build failed 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2647]
* KOReader version: current git
* Device: android build:
./kodev release android @ ubuntu 16.04 lts

#### Issue
build failed for reasons:
> [100%] Built target libpng
make[3]: Leaving directory `/home/marcin/koreader/base/thirdparty/libpng/build/arm-linux-androideabi'
make[2]: Leaving directory `/home/marcin/koreader/base/thirdparty/libpng/build/arm-linux-androideabi'
cp -fL /home/marcin/koreader/base/thirdparty/libpng/build/arm-linux-androideabi/libpng-prefix/src/libpng-build/.libs/libpng16.so.16 build/arm-linux-androideabi/libs/libpng16.so.16
cp: cannot stat '/home/marcin/koreader/base/thirdparty/libpng/build/arm-linux-androideabi/libpng-prefix/src/libpng-build/.libs/libpng16.so.16': No such file or directory
make[1]: *** [build/arm-linux-androideabi/libs/libpng16.so.16] Error 1
make[1]: Leaving directory `/home/marcin/koreader/base'
Makefile:52: recipe for target 'all' failed
make: *** [all] Error 2

libpng16.so.16 doesn't exist but exist libpng16.so (without '.16') under that path:
> ~/koreader/base/thirdparty/libpng/build/arm-linux-androideabi/libpng-prefix/src/libpng-build/.libs$ ls libpng16.*
libpng16.la  libpng16.lai  libpng16.so

#### Steps to reproduce
git clone https://github.com/koreader/koreader.git
cd koreader && ./kodev fetch-thirdparty && ./kodev release android 

the same for:
libfreetype.so.6
libjpeg.so.8
(.. and many more).

#### workaround - paste one by one after each error:
>export koreader=[your koreader dir]
>ln -s $koreader/base/thirdparty/libpng/build/arm-linux-androideabi/libpng-prefix/src/libpng-build/.libs/libpng16.so $koreader/base/thirdparty/libpng/build/arm-linux-androideabi/libpng-prefix/src/libpng-build/.libs/libpng16.so.16 
>ln -s $koreader/base/thirdparty/freetype2/build/arm-linux-androideabi/freetype2-prefix/src/freetype2-build/lib/libfreetype.so $koreader/base/thirdparty/freetype2/build/arm-linux-androideabi/freetype2-prefix/src/freetype2-build/lib/libfreetype.so.6
>ln -s $koreader/base/thirdparty/libjpeg-turbo/build/arm-linux-androideabi/libjpeg-turbo-prefix/src/libjpeg-turbo-build/.libs/libjpeg.so $koreader/base/thirdparty/libjpeg-turbo/build/arm-linux-androideabi/libjpeg-turbo-prefix/src/libjpeg-turbo-build/.libs/libjpeg.so.8
>ln -s $koreader/base/thirdparty/giflib/build/arm-linux-androideabi/giflib-prefix/src/giflib-build/lib/libgif.so $koreader/base/thirdparty/giflib/build/arm-linux-androideabi/giflib-prefix/src/giflib-build/lib/libgif.so.7
>ln -s $koreader/base/thirdparty/libzmq/build/arm-linux-androideabi/libzmq-prefix/src/libzmq-build/lib/libzmq.so $koreader/base/thirdparty/libzmq/build/arm-linux-androideabi/libzmq-prefix/src/libzmq-build/lib/libzmq.so.4
>ln -s $koreader/base/thirdparty/czmq/build/arm-linux-androideabi/czmq-prefix/src/czmq-build/lib/libczmq.so $koreader/base/thirdparty/czmq/build/arm-linux-androideabi/czmq-prefix/src/czmq-build/lib/libczmq.so.1
>ln -s $koreader/base/thirdparty/filemq/build/arm-linux-androideabi/filemq-prefix/src/filemq-build/lib/libfmq.so $koreader/base/thirdparty/filemq/build/arm-linux-androideabi/filemq-prefix/src/filemq-build/lib/libfmq.so.1
>ln -s $koreader/base/thirdparty/zyre/build/arm-linux-androideabi/zyre-prefix/src/zyre-build/lib/libzyre.so $koreader/base/thirdparty/zyre/build/arm-linux-androideabi/zyre-prefix/src/zyre-build/lib/libzyre.so.1

**Comment by Frenzie** [comment]
Apparently Android broke the normal way libraries work or something. http://www.opengis.ch/2011/11/23/creating-non-versioned-shared-libraries-for-android/

It sounds like a bunch of `$(if $(ANDROID),.so` in Makefile.defs should do the trick. I'll probably make a quick PR out of it after testing and I'll leave it to @houqp to point out if it's proper or not. :-P

**Comment by Frenzie** [comment]
@mwoz123 You didn't run into this?

```
android update project --path . -t android-19
Error: Target id 'android-19' is not valid. Use 'android list targets' to get the target ids.
```

**Comment by houqp** [comment]
Interesting, i haven't run into this before with ndk version 9c, 11c and 12b. @mwoz123 , are you using 14b? The official KOReader apk build uses 12b: https://github.com/koreader/koreader-base/blob/master/toolchain/Makefile#L19.

@Frenzie looks like you are missing the sdk, have you tried https://github.com/koreader/virdevenv/blob/master/docker/ubuntu/koandroid/build_android_tc.sh#L20?

**Comment by Frenzie** [comment]
@houqp In that case there might be a bug in kodev. I'm pretty sure it automatically downloaded and setup both the NDK and the SDK though.

**Comment by houqp** [comment]
Correct, it will automatically download 12b if no NDK installation is detected, see: https://github.com/koreader/koreader/blob/master/kodev#L97.

I will try reproduce this tomorrow, i have done a local android build for a while.

**Comment by houqp** [comment]
Weird, I am having the same issue with my local build now even though I haven't changed my toolchain :(
