### ISSUE TITLE
Floating image with caption does not respect width/float

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2652]
* KOReader version: v2015.11-898-gdccbf4c
* Device: Kobo Glo HD

#### Issue
I've got an epub where I need to float images together with a caption, sized in percent.
Koreader renders the size correct when sizing the image directly (no caption) but ignores the float.
If a floating div wrapper is used for sizing with the enclosed image sized 100% then koreader renders the image at 100%, ignoring the size of the surrounding wrapper.

Koreader seems to use the size of the image based on the body, disregarding the size of the parent wrapper.

Is there any way to at least get the image to be rendered at the proper size (without the float)?

Thanks!

This is how it looks in Nickel/Calibre/ADE/iBooks:
![screen_001](https://cloud.githubusercontent.com/assets/26367956/24023030/fc9c3b0c-0aa9-11e7-962d-8984283f6cee.png)

This is how Koreader renders it:
![reader_2017-mar-16_232618](https://cloud.githubusercontent.com/assets/26367956/24023042/0e8e7b2c-0aaa-11e7-8396-1e4c47d9eed6.png)

#### Steps to reproduce

See example epub
[test.epub.zip](https://github.com/koreader/koreader/files/849269/test.epub.zip)

**Comment by frankyifei** [comment]
crengine does not support float. I spend some time trying to figure out how to do it and gave up. it's a huge task.
