### ISSUE TITLE
Screensaver renders underneath InfoMessage

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2653]
* KOReader version: v2015.11-898-gdccbf4c
* Device: Kobo Glo HD

#### Issue
Screensaver renders underneath InfoMessages such as
* Connected to network …
* Your KOReader is up to date
* KOReader will be updated on next restart

I'm using a custom screensaver

settings.reader.lua:
```
    ["suspend_screensaver"] = {
        ["path"] = "/mnt/onboard/.adds/img/sleeping.png"
    },
```

![2017-03-17 17 11 16](https://cloud.githubusercontent.com/assets/26367956/24053053/e9e6fac2-0b37-11e7-8af6-1f3ffac9edae.jpg)

#### Steps to reproduce
1. Touch Hamburger menu -> Version
2. Push power button to suspend device or wait for the device to fall asleep

**Comment by KenMaltby** [comment]
What happens if you dismiss the message, by tapping the screen, prior to suspending?

**Comment by a-kohout** [comment]
Then only the screensaver is displayed.

**Comment by Frenzie** [comment]
Oh yeah, I've been aware of this for years but I guess it's never bothered me. :-)

**Comment by a-kohout** [comment]
IMHO the screensaver should hide everything.
If you're not aware of this glitch you might think that the device isn't sleeping properly.
Is it complicated to have the screensaver render on top of everything else?

**Comment by Frenzie** [comment]
Probably not, but I've never looked at this part of the code.

A quick peek says there's an exception for modal windows.
https://github.com/koreader/koreader/blob/dccbf4cf96bed24bceadf99baa492967d094237b/frontend/ui/uimanager.lua#L147-L154
I guess that means the screensaver needs an exception of some sort, such as an extra `above_all` boolean argument, because you wouldn't want it to skip modal windows.

**Comment by Hzj-jie** [comment]
+1, I have found this issue since day 1 I used KOReader. :)

**Comment by KenMaltby** [comment]
So you do something, or something causes a message box to be displayed, and you read it, then why not dismiss it, before suspending?  If you were not able to read the information before the auto-suspend, you might want to have it stay until you do dismiss it.  There is usually a good reason for the messages.

**Comment by a-kohout** [comment]
I discovered this bug after the device auto-suspended with the message "KOReader will be updated after next restart" shown.
I usually do dismiss messages before suspending manually.
Since the message is still there after waking up there is no harm in rendering the screensaver on the topmost layer. Also, from a usability perspective rendering a message on top of a screensaver doesn't make sense.

**Comment by Frenzie** [comment]
As a corollary, the same issue exists without an image. That is, the version notification (or whatever) wouldn't be replaced by the "Sleeping" message.
