### ISSUE TITLE
Koreader Android log?

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2654]
* KOReader version: Android
* Device: Android

#### Issue
Where koreader log is stored on android?
How to obtain/enable such log?

**Comment by Hzj-jie** [comment]
adb logcat

**Comment by mwoz123** [comment]
$ adb logcat
* daemon not running. starting it now on port 5038 *
* daemon started successfully *
- waiting for device -

It seems to be stuck on "waiting for device". 
Do I need to provide any additional parameters? 
I tried "adb logcat *:V" and "-d" but the output was the same :(

**Comment by Frenzie** [comment]
Besides running adb (btw, I think it might need sudo?) you also need to enable USB debugging on your Android device. This is part of "Developer options" which is hidden by default. You can activate that menu by tapping half a dozen times or so on the build number in "About phone".

**Comment by mwoz123** [comment]
I don't have root, and it seems it's necessary :(

I found workaround :
http://android.stackexchange.com/questions/157/does-access-to-logcat-need-root

Point is to  use "report bug" (in "developer options") and then all logs can be and send to specified email. 
I tried this but unfortunately it crashes:(

**Comment by Frenzie** [comment]
You don't need root to enable developer options or access logcat. Go to **Settings** > **About phone** and press **Build number** seven times. Then you can enable USB debugging in **Settings** > **Developer options**.

**Comment by mwoz123** [comment]
@Frenzie - "no root is necessary to get logging output" - is it "adb logcat" or debugging from pc? 

"report bug" might crashed because missing email client on deceive, but I discovered 3mb log file exist under directory:
/mnt/sdcard/bugreports

**Comment by Frenzie** [comment]
I'm not really sure what you're asking since there's no "or". adb stands
for Android *Debug* Bridge and logcat is one of the tools in the debugging
arsenal. To use adb you need to enable USB debugging.

**Comment by mwoz123** [comment]
Ok. Now I get it :) 
I thought it can be either log output to console on Android (when typed "adb logcat" in command prompt) or remotely with pc when enabled "usb debugging". 
Good to know I was wrong. 

@Frenzie thanks :)

**Comment by Frenzie** [comment]
The log above is from a terminal emulator on your phone? Besides not
needing root debugging over USB or wifi from your PC is a whole lot
simpler. You can install adb with your package manager in Linux or from
https://developer.android.com/studio/index.html#downloads (just tools
should do).

**Comment by houqp** [comment]
FWIW, we also have a helper command in kodev to help filter output from logcat, try `./kodev log android`.

**Comment by Frenzie** [comment]
Closing this now.
