### ISSUE TITLE
KOReader dies after clicking AEB four times on keyboard

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2657]
* KOReader version: up to 897
* Device: Kindle only, cannot reproduce on Kobo Aura HD

#### Issue

KOReader dies after clicking AEB four times on keyboard.

#### Steps to reproduce

Trigger virtual keyboard by opening an input box, say, dictionary lookup.
Click AEB (it should be alpha ?? beta I believe.) four times.
KOReader dies, no response on any action, include touch, power button or magnetic cover.
Clicking AEB for three times, and international key once can also trigger this issue.

This does not happen on Kobo Aura HD, but the screen usually flickers and partially refreshes after the action.

**Comment by Frenzie** [comment]
As expected I can't confirm this in the emulator or on my H2O. Btw, I'm pretty sure it's an ß (eszett, a German ligature for ss) and not a lowercase β. ;-)

**Comment by KenMaltby** [comment]
"Doctor it hurts when I do this ..."
