### ISSUE TITLE
WiFi switch doesn't work on Android

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2660]
* KOReader version: koreader-nightly-20170308
* Device: Android (e.g. Inkbook Prime, Myphone L-line)

#### Issue
WiFi switch on Android is grayed out and so cannot be selected.
 BTW indicator is always "ticked", even when Wifi is off.

This would be very useful feature for all plugins that use internet connnection.

#### Steps to reproduce
On Android device run koreader , open top menu -> Network  try to enable/disable Wifi with "Wifi connection"

**Comment by houqp** [comment]
There is no easy way to implement a network manager in android, so please use the builtin network manager.

The status indicator issue is a valid bug that we should fix.

**Comment by mwoz123** [comment]
done in koreader/android-luajit-launcher#65 & #3386
