### ISSUE TITLE
Can't download files from ftp

### ISSUE THREAD

**Issue by swearofwind** [koreader/koreader#2667]
* KOReader version: v2015.11-901-g112e6a4 and before  (eink version)
* Device: Kobo Touch N905C

#### Issue  

When I use the ftp function to download files form my phone(through the wifi hot spot, my phone and eink device connects to the same wifi), KOReader shows that "could not save file to .........."

And the screen of the  new version(v2015.11-901-g112e6a4) have a bug that the size of the "Cloud Storage" is incorrect, it show the landscape UI size on screen, which results I can't close the "Cloud Storage", and the right part of the UI can't show and the below still show the previous UI.

**Comment by houqp** [comment]
@robert00s probably worth adding the actual error message into that info prompt to help troubleshoot issues like this.

**Comment by robert00s** [comment]
@swearofwind 
Can you see list of files and folders in KO from your ftp server on phone?
Can you download another files?

**Comment by swearofwind** [comment]
@robert00s 
No, I can't download any file from my phone server in the kobo device using koreader.
I can see the file list in KO.

**Comment by robert00s** [comment]
Thanks for screenshot.
I cannot reproduce it on my emulator. I don't have Kobo unfortunately.
Two requests:
1. Try to change one arbitrary pdf file name to e.g: abc.pdf on your phone and try to download to your Koreader.
2. Can you write name of one file from screenshot? I don't know this language. I want to try to download file with this name in my environment.

**Comment by houqp** [comment]
`表彰大会策划书(1).doc` for the first item.

**Comment by slow-mo** [comment]
I've got the same (?) problem on my Kindle PW2, ftp server log may help:

`07/05/2017 13:28:25.406 [8196] Client connected from 192.168.0.3.
07/05/2017 13:28:25.410 [8196] 220 Welcome to Quick 'n Easy FTP Server
07/05/2017 13:28:25.417 [8196] USER slow-mo
07/05/2017 13:28:25.419 [8196] 331 Password required for slow-mo
07/05/2017 13:28:25.419 [8196] PASS ******
07/05/2017 13:28:25.419 [8196] 230 User successfully logged in.
07/05/2017 13:28:25.419 [8196] PASV
07/05/2017 13:28:25.419 [8196] 227 Entering Passive Mode (192,168,0,2,4,0)
07/05/2017 13:28:25.422 [8196] NLST /Vari
07/05/2017 13:28:25.461 [8196] 150 Opening ASCII mode data connection for directory list.
07/05/2017 13:28:25.461 [8196] 226 Transfer complete
07/05/2017 13:28:25.504 [8196] QUIT
07/05/2017 13:28:25.505 [8196] Client disconnected from 192.168.0.3.
07/05/2017 13:28:25.507 [8196] 221 Bye
07/05/2017 13:28:41.705 [7416] Client connected from 192.168.0.3.
07/05/2017 13:28:41.707 [7416] 220 Welcome to Quick 'n Easy FTP Server
07/05/2017 13:28:41.709 [7416] USER slow-mo
07/05/2017 13:28:41.711 [7416] 331 Password required for slow-mo
07/05/2017 13:28:41.712 [7416] PASS ******
07/05/2017 13:28:41.712 [7416] 230 User successfully logged in.
07/05/2017 13:28:41.714 [7416] TYPE i
07/05/2017 13:28:41.714 [7416] 200 Type set to BINARY
07/05/2017 13:28:41.716 [7416] PASV
07/05/2017 13:28:41.716 [7416] 227 Entering Passive Mode (192,168,0,2,4,0)
07/05/2017 13:28:41.720 [7416] RETR /La storia del cinema.epub
07/05/2017 13:28:41.721 [7416] 550 File not found.
07/05/2017 13:28:41.723 [7416] 426 Connection closed. Transfer aborted.
07/05/2017 13:28:41.725 [7416] Client disconnected from 192.168.0.3.`

Maybe I didn't set the server properly (tips are welcome) but it seems that koreader is disconnecting after every transfer and it isn't keeping track of the directory tree. So if you browse to a folder and then try to download a file within, koreader issues a RETR command asking for the file in the root dir, which causes a "File not found" error from the server. Koreader then gives the "Could not save file" msgbox.

Here's the log of a working download session with chrome:

`07/05/2017 13:37:33.111 [10180] Client connected from 192.168.0.2.
07/05/2017 13:37:33.114 [10180] 220 Welcome to Quick 'n Easy FTP Server
07/05/2017 13:37:33.114 [10180] USER slow-mo
07/05/2017 13:37:33.115 [10180] 331 Password required for slow-mo
07/05/2017 13:37:33.115 [10180] PASS ******
07/05/2017 13:37:33.115 [10180] 230 User successfully logged in.
07/05/2017 13:37:33.115 [10180] SYST
07/05/2017 13:37:33.116 [10180] 215 UNIX emulated by Quick 'n Easy FTP Server.
07/05/2017 13:37:33.116 [10180] PWD
07/05/2017 13:37:33.117 [10180] 257 "/" is current directory.
07/05/2017 13:37:33.117 [10180] TYPE I
07/05/2017 13:37:33.117 [10180] 200 Type set to BINARY
07/05/2017 13:37:33.117 [10180] SIZE /Vari/La storia del cinema.epub
07/05/2017 13:37:33.128 [10180] 213 125963
07/05/2017 13:37:33.129 [10180] CWD /Vari/La storia del cinema.epub
07/05/2017 13:37:33.134 [10180] 550 "/Vari/La storia del cinema.epub": Directory not found.
07/05/2017 13:37:33.134 [10180] PASV
07/05/2017 13:37:33.135 [10180] 227 Entering Passive Mode (192,168,0,2,4,0)
07/05/2017 13:37:33.135 [10180] RETR /Vari/La storia del cinema.epub
07/05/2017 13:37:33.140 [10180] 150 Opening BINARY mode data connection for file transfer.
07/05/2017 13:37:33.207 [10180] 226 Transfer complete
07/05/2017 13:37:33.273 [10180] QUIT
07/05/2017 13:37:33.273 [10180] 221 Bye
07/05/2017 13:37:33.274 [10180] Client disconnected from 192.168.0.2.`

**Comment by houqp** [comment]
@slow-mo I think you are right. You are able to download that file if it's put under the root directory right?

**Comment by slow-mo** [comment]
Yes, everything in the root directory can be downloaded/accessed. Anything placed inside a first level folder cannot, so you can't access subfolders too.

**Comment by allexmasu** [comment]
Change  file name from chinese to english can solve this problem

**Comment by robert00s** [comment]
With VSFTPd there is no problem but with Quick 'n Easy FTP Server I have the same problems.
I will try to debug that.

**Comment by slow-mo** [comment]
Works great, thanks a lot!

**Comment by goodBoy11** [comment]
The bug still exist!

    KOReader version:v2015.11-1054-g6870bc2
    Device: Kindle PaperWhite 1

**Comment by slow-mo** [comment]
The patch is working fine for me.

**Comment by keenreader** [comment]
I have the same problem. I m using koreader v2020.08.01 and kobo aura h2o
Btw i could not find the fix #2667 nor #2910

**Comment by keenreader** [comment]
I find the fix #2667 and #2910 were already in koreader v2020.08.01 but i cannot save any file to kobo device. I can see the ftp list but cannot download it.
![931269CF-8FED-4238-883A-5E3D57B69AD9](https://user-images.githubusercontent.com/71136051/92936553-cbc48f00-f47c-11ea-96a5-8d9924e0991b.jpeg

**Comment by keenreader** [comment]
I tried IE and chrome to download files in ftp, they works fine but not in koreader. Please help us to refine it🙏

**Comment by NiLuJe** [comment]
Can't help you without logs. (Also, an English UI might help for screenshots).

**Comment by pihokkerr** [comment]
Hi! I have the same problem with WebDAV, I can connect to my NAS, see all of my files but I cant download it I get an error that cant save the file (I tried: .epub, .mobi, .pdf). 

Kindle PaperWhite 3 (PW3)
Firmware version of 5.9.6.1.
KOReader version: v2021.02

log:
--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 96.729/96.729/96.729 ms
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot tell in file
02/26/21-06:32:19 WARN  cannot open document /mnt/us/koreader/documents/abc..pdf frontend/document/pdfdocument.lua:35: ./ffi/mupdf.lua:70: libs/libwrap-mupdf.so: undefined symbol: mupdf_error_message
02/26/21-06:32:19 WARN  got error waiting for events: Waiting for input failed: 4

What could be the problem?
Thanks for your help!

**Comment by codeninja-ru** [comment]
I have the same issue. 

I tried to figure it out myself and found this:

ftp server response is "553 User not allow"
It might be a problem specific to the ftp server (pure-ftp on WD My Cloud) but curl and wget download files without fail. I can't change the ftp configuation since it's the part of WD My Cloud

So I tried next lua code:
```lua -- load the ftp support
local ftp = require("socket.ftp")
local ltn12 = require("ltn12")
local url = require("socket.url")

-- a function that returns a directory listing
function nlst(u)
    local t = {}
    local p = url.parse(u)
    p.command = "nlst"
    p.sink = ltn12.sink.table(t)
    local r, e = ftp.get(p)
    return r and table.concat(t), e
end

print(nlst("ftp://192.168.1.137/books/"))

-- Log as user "anonymous" on server "ftp.tecgraf.puc-rio.br",
-- and get file "lua.tar.gz" from directory "pub/lua" as binary.
f, e = ftp.get("ftp://192.168.1.137/books/test.txt;type=i")
print(f)
print(e)
```

and got the response:
```
books/.
books/..
books/.DS_Store
books/Lo-Guanchzhun_Troecarstvie.KGLQxA.224268.fb2
books/Oruell_1984.epub
books/test.txt
	nil
nil
553 User not allow
```

the first is the list of the files on my ftp. As you see listing is working.
but downloading returns ```553 User not allow```

Any ideas?

P. S.

If you get here like me by googling you need to know that the issue might be in luasocket (socket.ftp). Maybe you can solve it by tweaking your ftp, but this is not my case.

The issue in koreader is that they do not show the response of the server properly in case of error.

**Comment by Frenzie** [comment]
> The issue in koreader is that they do not show the response of the server properly in case of error.

PR welcome.

**Comment by codeninja-ru** [comment]
Ha ha, it's pure magic. I added extra '/' in the url after the host and it worked. 
```lua
f, e = ftp.get("ftp://192.168.1.137//books/test.txt;type=i")
```

so to make it work you have to put double '//' in the path field. I put '//books' in my case

**Comment by Frenzie** [comment]
That sounds like a bug in the server, though the fact that it works with cURL sure is mysterious.

**Comment by codeninja-ru** [comment]
Checked `ftp.lua` from `luasocket`. It seems they remove leading '/' in the path for some reason. 

Submitted an issue to them https://github.com/lunarmodules/luasocket/issues/456

**Comment by arthur-mts** [comment]
i was receiving this errors when downloading files from the server and it was because of the file name size.
the file name was "The Lightning Thief -- Rick Riordan -- 2010 -- Disney Hyperion; Hyperion Book CH -- 9780307245311 -- e2ea953d51e82129a89590ff46e6f423 -- Anna’s Archive.epub" and renaming it to "The Lightning Thief -- Rick Riordan -- 2010.epub"  made it work perfectly.
