### ISSUE TITLE
EPUB doesn't support SVG images

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2668]
* KOReader version: lastest 
* Device: ppw3

#### Issue

Some images in few epubs doens´t open...I ´ve attached screens with a mobi and the epub into pc, I can see the image in both files, but if I open the epub in koreader I only see a blank image

this one is on PC (" 11.1.5 PECULATO")
![epub-pc](https://cloud.githubusercontent.com/assets/20425689/24161928/91cfdf1a-0e44-11e7-8931-dbc4af56859e.jpg)

Mobi at kindle (" 11.1.5 PECULATO")
![p_20170321_143717](https://cloud.githubusercontent.com/assets/20425689/24162118/40287130-0e45-11e7-903d-c3fc8aee77d1.jpg)

Epub with koreader (" 11.1.5 PECULATO")

![p_20170321_144355](https://cloud.githubusercontent.com/assets/20425689/24162060/0595f5e2-0e45-11e7-9fed-9c085c488b34.jpg)

#### Steps to reproduce
Download the epub and try at ppw3
https://www.dropbox.com/s/dtc5vdw4him9cek/DIREITO%20PENAL%20-%20PARTE%20ESPECIAL%20-%20ESQUEMATIZADO%20-%202016.epub?dl=0

**Comment by retrue** [comment]
I have checked, the images in this book are in svg format.

**Comment by Eduardomb22** [comment]
Do u know if there is a way to "fix" it?

**Comment by retrue** [comment]
Nope. Probably the format is not supported, but I don't know for sure. You could edit the epub file so it used png instead.

**Comment by Eduardomb22** [comment]
thanks

**Comment by Frenzie** [comment]
Also note #1813.

The [EPUB 2 spec](http://idpf.org/epub/20/spec/OPS_2.0.1_draft.htm#Section2.5) states that SVG *must* be supported.

**Comment by houqp** [comment]
Looks like https://github.com/memononen/nanosvg has a pretty simple API for rendering SVG.

**Comment by Frenzie** [comment]
Incidentally, MuPDF 1.10 ships with a "Simple SVG parser (a small subset of SVG only)" ([source](http://mupdf.com/news)). I think it's part of their work toward EPUB3 support. Now I'm not entirely sure what kind of magic would need to happen for either this or nanosvg, but I'm just pointing it out 'cause MuPDF is already there.

**Comment by houqp** [comment]
Oh yeah, good point. We should definitely also consider using mupdf.

**Comment by poire-z** [comment]
I had a go at making crengine uses nanosvg, and it was in the end quite simple (except it took me hours with my limited experience with C).
Some screenshots with Eduardomb22's epub:

![reader_2017-apr-28_212647](https://cloud.githubusercontent.com/assets/24273478/25544914/f01a1960-2c5c-11e7-8e8e-01845f73933f.png)
![reader_2017-apr-28_212617](https://cloud.githubusercontent.com/assets/24273478/25544916/f288dc36-2c5c-11e7-8003-be2e2ac1be83.png)

It only works with image files (not with svg tag inside the html, haven't yet checked if it's possible), and there's some strange micro problems (like the bottom and right border being thiner than the left and top borders...), and I haven't yet checked how these 360 pixels wide svg images look on the device. Also, some with text/tspan/fonts (unsupported by nanosvg) are displayed blank.

I had a hard time finding some other epubs with svg (as image files inside the epub). I would welcome a few more, with various kind/size of svg graphics, so if some of you have free ones, please post them here.

Also, @houqp & @Frenzie : what would need to be done to have the build process pull nanosvg and how to have the crenegine build uses them ? I would be happy if you could deal with that :)
Or should I just put the 2 nanosvg.h and nanosvgrast.h into crengine/src ? (Although the nanosvg looks quite alive, so it would be fine to use always the latest, without the need for bumps ?)

**Comment by Frenzie** [comment]
I'd be inclined to just stick the headers in there but of course we do have this quite nice version management system in place already. Taking a quick glance it would probably suffice to pull it in and add the include dir to crengine: https://github.com/koreader/koreader-base/blob/3e9b63f5cafc12335e18ea8ed313aa01c004b745/thirdparty/kpvcrlib/CMakeLists.txt#L30-L37

Just eye-balling it real quickly I guess the include dir would be something like:

```bash
$(THIRDPARTY_DIR)/nanosvg/src
```

I probably wouldn't go without manual bumps. It's just too annoying to have something fail randomly because of some temporary upstream mistake.

**Comment by Eduardomb22** [comment]
Thanks for looking into this! I have more epubs with svg images, but they are from the same press. So, I think will not help you a lot, but I will post it anyway

https://www.dropbox.com/s/6nvw02fr0c6ib0e/Direito_Processual_Civil_Esquematizado_-_Marcus_Vinicius_-_2017.zip?dl=0

https://www.dropbox.com/s/2u2a5t9xb2wrhy8/DIREITO%20CONSTITUCIONAL%20ESQUEMAT%20-%20PEDRO%20LENZA.zip?dl=0

**Comment by Frenzie** [comment]
If there's an easy way to convert a webpage to EPUB with the inclusion of SVG you could try one of my silly drawings: http://fransdejonge.com/2016/08/le-champignon-qui-sest-retire-du-monde/

**Comment by poire-z** [comment]
Thanks.
Indeed, the brazilian books have quite similar svgs (and hard to find among 4000 pages :)
For converting web pages to epub, I use https://github.com/alexadam/save-as-ebook .
Output from your page (quite fast, rasterizing image 837 x 2524) :
![reader_2017-apr-28_231442](https://cloud.githubusercontent.com/assets/24273478/25547682/dba419ca-2c68-11e7-8beb-18f07754c4f1.png)
Would like to find something like this one https://www.hindawi.com/journals/bmri/2013/962369/ (but its svg are embedded in the html). But I suspect the photo-like won't be supported by nanosvg.

**Comment by Frenzie** [comment]
Btw, in case you're interested that's actually a follow-up to http://fransdejonge.com/2016/04/trois-champignons/

In the hindawi thing, are you talking about [the logo](https://images.hindawi.com/logo/hindawi.svg)? It doesn't look like it's using anything complicated.

**Comment by poire-z** [comment]
No, not the logo, but the scientific images included in the paper.
As shown by Firefox epub-catalog extension:
![capture](https://cloud.githubusercontent.com/assets/24273478/25554436/e2cc02ca-2ccd-11e7-8099-2567d2e4d97d.png)
I just extracted it to replace one in some other epub. As shown by koreader/nanosvg :
![reader_2017-apr-29_111533](https://cloud.githubusercontent.com/assets/24273478/25554437/f891e0a2-2ccd-11e7-8ca2-ac0c184616fe.png)
The photos (png included in the svg) are not shown (nanosvg would need to use external libs like libpng/libjpeg), and there's some kind of multiple way to specify width and height of svg images (the original svg had some width=43em, that nanosvg rendered as 43px , had to remove them...)

Also, I had a look at how we could handle inlinded svg tag in the html with crengine, but it looks there's nothing already there to make image streams out of xml tags hierachy... so a lot of code to add to deal with that...

So, we may get a lot of bug reports with this rudimentory implementation.
Should I still go on with what I have ?

**Comment by poire-z** [comment]
MuPDF does not seem to support more tags than nanosvg:
http://git.ghostscript.com/?p=mupdf.git;a=blob;f=source/svg/svg-run.c;h=d113fd13d63a722794f891ef870da405d889d9c5;hb=HEAD#l1097
Anyway, if crengine uses nanosvg (looks twisted to make it use mupdf), we may later have the ImageViewer widget pull the svg data from crengine, and feed it to mupdf to have an alternate svg rendering.

**Comment by Frenzie** [comment]
I can't find these SVGs you're referring to. All I see on that page is JPEGs. Incidentally, on my blog I've also got some inline SVGs ([here](http://fransdejonge.com/2013/07/feed-pick-my-new-feed-icon/)) as well as SVGs with images ([here](http://fransdejonge.com/2010/06/pancake-visions/)). The latter are animated, but should in principle display in merged form in user agents that don't support animation.

> MuPDF does not seem to support more tags than nanosvg:

But I see image in there, the one that would presumably be the most important one for the issue you pointed out above?

> (looks twisted to make it use mupdf)

I see nothing particularly twisted in using MuPDF, unless you mean it'd make more sense to replace crengine competely by MuPDF. :-P (On the longer term I certainly think it could make sense to implement it as an alternative EPUB renderer.) What i said above still applies in any case: MuPDF's SVG support is also under active development and it doesn't pull in an extra dependency.

Btw, I'm on Gitter atm if you'd like to talk a little faster. https://gitter.im/koreader/koreader

**Comment by poire-z** [comment]
> I can't find these SVGs you're referring to

Oh, there's a link at the top right "Full-Text ePUB": the downloadable epub includes these images are embedded svg tags.

> But I see image in there

Yes, but enclosed in `#if 0 ... endif` :) So they may be supported later, but not yet.
Dunno about having crengine uses mupdf (an engine using another engine!), but I guess everything is possible. Anyway, nanosvg integration was simple enough that I could do it :)

**Comment by Frenzie** [comment]
Without highlighting I completely missed that. :-)

**Comment by poire-z** [comment]
> Taking a quick glance it would probably suffice to pull it 

"suffice" is an easy word :) I can't get it pulled !

I modified base Makefile.third
```
@@ -108,7 +108,7 @@ $(DJVULIBRE_LIB): $(JPEG_LIB) $(THIRDPARTY_DIR)/djvulibre/CMakeLists.txt
        cp -fL $(DJVULIBRE_LIB_DIR)/$(notdir $(DJVULIBRE_LIB)) $(DJVULIBRE_LIB)

 # crengine, fetched via GIT as a submodule
-$(CRENGINE_LIB): $(ZLIB) $(PNG_LIB) $(FREETYPE_LIB) $(JPEG_LIB) \
+$(CRENGINE_LIB): $(ZLIB) $(PNG_LIB) $(FREETYPE_LIB) $(JPEG_LIB) $(NANOSVG_HEADERS) \
                $(THIRDPARTY_DIR)/kpvcrlib/crengine $(THIRDPARTY_DIR)/kpvcrlib/CMakeLists.txt
        install -d $(CRENGINE_BUILD_DIR)
        cd $(CRENGINE_BUILD_DIR) && \
@@ -534,6 +534,8 @@ $(LUA_LJ_SQLITE) $(OUTPUT_DIR)/common/xsys.lua: $(LUA_LJ_SQLITE_DIR)/init.lua $(
        cp $(LUA_LJ_SQLITE_DIR)/{init.lua,LICENSE} $(LUA_LJ_SQLITE_INSTALL_DIR)
        cp $(LUA_LJ_SQLITE_DIR)/xsys.lua $(OUTPUT_DIR)/common

+$(NANOSVG_HEADERS): $(THIRDPARTY_DIR)/nanosvg/CMakeLists.txt
+
 comma:=,
 empty:=
 space:=$(empty) $(empty)

```
Created a thirdparty/nanosvg/CMakeLists.txt based on the djvulibre one with nanosvg and it's github info.
Even after make clean and kodev build, nanosvg is not pulled, that thirdparty/nanosvg stays with a single CMakeLists.txt
Any idea what else I should do ?

**Comment by Frenzie** [comment]
Could you commit it to a branch on GitHub so we can get a better overview of it?

**Comment by poire-z** [comment]
Here: https://github.com/poire-z/koreader-base/tree/nanosvg
(Incomplete for crengine and cre.cpp to use them, nanosvg/CMakeLists.txt too, but I'd just like a pull for now)

**Comment by Frenzie** [comment]
Yeah, this stuff is kind of frustrating. I'm not sure why that's not pulling anything.

**Comment by poire-z** [comment]
Ok, understood why it wasn't pulled:
`$(NANOSVG_HEADERS): $(THIRDPARTY_DIR)/nanosvg/CMakeLists.txt`
The first part needs to point to missing file(s), so that `make` can think about dealing with it.
The second part was just a requirement for this `CMakeLists.txt` to exist.
And after that, indented, we have to actually do the work and call `cmake` and `make`, and copy the files so that these are not missing anymore and it is considered _made_.
