### ISSUE TITLE
Changing fonts should overwrite bundled EPUB-bundled CSS

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#2670]
* KOReader version: v2015.11-431 or later (not sure for now, sorry for that)
* Device: Kindle Touch (ver. 5.3.7.3)

Hi guys! I've been out of the discussion for a while, since I gave my Kindle to my friend. There were a few 'complaints' about it regarding the usability and friendliness of KOReader's interface to users. So here are some suggestions for improvement:

#### Issues
1) When the publisher's default setting for an e-book were set (as we investigated lately), we tried to change fonts. Of course, the fonts didn't change. So the suggestion is to make KOReader say in this case that "Publisher default fonts are set, in order to change the font please turn it off";

2) When we, during this investigation, tried to open another book (fb2), the page position of the first book (epub) was lost after returning to it from the second book. I am not sure if it happens constantly, we had only a conversation over the phone when it happened.

**UPDATE**: sorry for missing it (did search before posting, somehow skipped that post). Found a work around here - https://github.com/koreader/koreader/issues/2015 , it seems like it is a tough issue right?  

I am sorry beforehand, if these issues where solved already in newer versions. I will ask my friend whether he updated the KOReader from here or not later.

I wish I could help you guys better!

**Comment by Hzj-jie** [comment]
I have not had the second issue. But the first looks like a bug to me. The default font should always be overwritten by users' choice.

**Comment by Frenzie** [comment]
@Hzj-jie Since #2015 is still open I suppose that bug probably still exists. I couldn't find any PRs in base that seem to adress the issue at a quick glance.

**Comment by poire-z** [comment]
> When the publisher's default setting for an e-book were set (as we investigated lately), we tried to change fonts. Of course, the fonts didn't change. So the suggestion is to make KOReader say in this case that "Publisher default fonts are set, in order to change the font please turn it off";

koreader doesn't know, when Embedded Styles is On, if there are fonts in the epub, so it doesnt know what the effect changing fonts will have.
But a new toggle is available since #3149 : Embedded fonts On/Off

**Comment by poire-z** [comment]
Since https://github.com/koreader/koreader/pull/3944, there's now the option to `Ignore publisher font families` or `Ignore publisher font sizes` that should help address the 1st issue..
https://github.com/koreader/crengine/pull/195 may have helped on the 2nd issue.
