### ISSUE TITLE
Android APK is not upgradable

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2682]
* KOReader version: 894, but this issue happens for a while.
* Device: Android. My device is Huawei Honor 6 Plus with Android 6.0. Similar issue happens on several other devices, include Nexus.

#### Issue

Upgrading an existing KOReader installation on Android always fails. I need to uninstall existing installation before installing a new version.

#### Steps to reproduce

Install an older version.
Upgrade to a newer version.
Expectation, upgrading succeeded.
Actual, the app failed to be upgraded.

Though we do not use Android mechanism to store settings, thus settings won't lose after an uninstallation. It's still a little bit inconvenient for a regular user.

**Comment by Frenzie** [comment]
Also see #2531 although I was under the apparently mistaken impression that that particular problem had been resolved.

**Comment by gerroon** [comment]
I think that most recent builds actually work but release to most recents probably would not work

**Comment by Frenzie** [comment]
I just tested this. Updating worked between these two.

http://build.koreader.rocks/download/nightly/v2015.11-898-gdccbf4c/
http://build.koreader.rocks/download/nightly/v2015.11-935-g1b700c0/

However, there's something different about the nightly uploaded by @chrox available from https://github.com/koreader/koreader/releases/tag/v2017.03.08-nightly

So it's probably more of a ghost bug.

**Comment by Frenzie** [comment]
Closing for #2469.
