### ISSUE TITLE
A system status plugin

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2683]
* KOReader version: independent
* Device: independent

#### Issue

I would include memory usage, processor usage, awake time & percentage (for current process), up time.

**Comment by Hzj-jie** [comment]
Forgot to mention that this plugin can help to detect the unexpected restart, unexpected wakeup, memory and processor usage issues, etc.

**Comment by oldhasbeen** [comment]
@Hzj-jie 
yes please, would help with diagnostics!

**Comment by Hzj-jie** [comment]
This issue can be closed.
