### ISSUE TITLE
Go to page problem

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2687]
* KOReader version: v2015.11-930-g0318a04
* Device: ppw3

#### Issue
If I click go to page (dunno if this the correct english transation, but is the function that enable the user to write a page number and go to the select one) the koreader crash.

#### Steps to reproduce
Just click the go to page  at v2015.11-930-g0318a04

here is the crash log, it happens with pdf and epub files.
[crash.txt](https://github.com/koreader/koreader/files/876001/crash.txt)

**Comment by Frenzie** [comment]
@Hzj-jie This has something to do with the description in your #2672.

**Comment by Frenzie** [comment]
Fixed by #2690.
