### ISSUE TITLE
More assertions?

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2700]
* KOReader version:
* Device:

#### Issue

I spent hours today to debug the ScrollTextWidget, and finally found I missed dialog parameter.
I think this can be simply achieved by adding an assertion once self.dialog is referred.

So I would suggest to use more assertions + error messages at the unexpected situations, which would impact the behavior.

What do you think?

**Comment by Frenzie** [comment]
Better messages is always good, right? ;)

**Comment by Hzj-jie** [comment]
I think in the scenario I have mentioned, ScrollTextWidget definitely won't work without dialog parameter, which deserves an assertion.

**Comment by Frenzie** [comment]
*nods enthusiastically*

**Comment by Hzj-jie** [comment]
Coding style has been updated to add an assertions section.

**Comment by houqp** [comment]
I prefer we make those assertions only take effect in debug mode like what I did in the uimanager with `dbg:guard`.
