### ISSUE TITLE
FR: pinch gesture for changing fontsize

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2701]
Platform: probably only Kindle and Android

> Pinch gesture like in Kindle - changing font size - it's not so important for me, but good to have.
https://github.com/koreader/koreader/issues/1761#issuecomment-184693438

**Comment by Frenzie** [comment]
This is similar to and perhaps slightly conflicts with #1839.

**Comment by robert00s** [comment]
I think we can close it now.
