### ISSUE TITLE
WiFi and network manager states

### ISSUE THREAD

**Issue by lgeek** [koreader/koreader#2706]
Hi,

I think what the UI shows doesn't quite match the state of the actual interface, and the internal state of the network manager gets similarly confused. At the moment, there are two states shown for the WiFi connection: on (connected) and off. However, the WiFi adapter has 3 main states: on (up, disconnected), connected, and off (down). 

For example, we can now enable the Wi-Fi adapter via Gear -> Network -> Wi-Fi connection. However, if we don't connect to a network, when we return to the menu, the 'WiFi connection' checkmark will appear as off. In fact, the WiFi adapter is left up in the disconnected state. If we select the 'Wi-Fi connection' button again, then we'll once again be asked whether to turn on Wi-Fi, even though it is already enabled. Similarly, we can only turn off the WiFi adapter after we have connected to a network, there's no way to go from the disconnected state to the off state. With the 'automatically restore Wi-Fi connection after resume' option enabled, this can persist for the uptime of the device.

The way I would propose to fix this is exposing the three states in the UI. The following transitions should be allowed:

* off -> on
* on -> connected
* on -> off
* connected -> off
* connected -> on (via the disconnect button in the network list)

In terms of actual changes to the UI, I would suggest the following:

* renaming the 'Wi-Fi connection' menu entry to 'Wi-Fi' and mapping the check mark to (on || connected)
* changing the actions of the WiFi menu entry to the following: from off, ask whether to enable WiFi, then show the network list if answering yes; from on and connected, show the network list immediately
* from the on and connected states, is must be allowed to turn off Wi-Fi. I'm not sure how to implement that in terms of UI. I'd be tempted to use a long press on the Wi-Fi connection menu, followed by the confirmation dialog currently used. However, I'm not sure if that is consistent with the rest of the UI. In particular, I'm concerned that it might not be intuitive to discover this action. Maybe it would make more sense to add a turn off button to the network list UI.

Any thoughts?

**Comment by Frenzie** [comment]
My preferred way of disabling wifi is by suspending quickly because it's not really any slower than going through the GUI anyway. I don't use restore on resume. Probably a case of https://xkcd.com/1172/

Another possible solution (and probably the easiest short-term) would be to change the network info popup into a dialog with a "Turn off Wi-Fi" button.

**Comment by houqp** [comment]
> renaming the 'Wi-Fi connection' menu entry to 'Wi-Fi' and mapping the check mark to (on || connected)

Agree. We can dynamically set the menu text based on current state: `Wi-Fi (on)` and `Wi-Fi(connected)`. We can even do `Wi-Fi(ESSID)`.

> changing the actions of the WiFi menu entry to the following: from off, ask whether to enable WiFi, then show the network list if answering yes; from on and connected, show the network list immediately
> from the on and connected states, is must be allowed to turn off Wi-Fi. I'm not sure how to implement that in terms of UI. I'd be tempted to use a long press on the Wi-Fi connection menu, followed by the confirmation dialog currently used. However, I'm not sure if that is consistent with the rest of the UI. In particular, I'm concerned that it might not be intuitive to discover this action. Maybe it would make more sense to add a turn off button to the network list UI.

We can add buttons to the network list UI. One button for turn off wifi and another one for rescan network. Then we can support all the workflows:

* off -> on (click menu to prompt for turn on when wifi is off)
* on -> connected (click menu to show network list when wifi is on)
* on -> off (turn off wifi button)
* connected -> off (turn off wifi button)
* connected -> on (via the disconnect button in the network list)

**Comment by lgeek** [comment]
@houqp That sounds good to me. I'll start implementing it.

**Comment by a-kohout** [comment]
I'd suggest to not show the network list automatically after turning wifi on.
Instead, the device should connect automatically to the strongest known network.
In order to access the network list another menu entry should be added.
In case there are no known networks nearby, there could be an option to automatically show the network list.
This behavior would be similar to what people are already used to from iPhone/Android.

**Comment by lgeek** [comment]
@a-kohout That would be best, but it looks like it would involve more complex changes to how the network manager works, as opposed to only changing its UI. At the moment, my preference is to treat them as two separate sets of changes. For now, I'm only committing to do the first one.

**Comment by houqp** [comment]
Agree, the automatic connect step is not trivia to implement due to the limitation in the current UI framework :( It will need proper background task support in order to pull status update from wpa_supplicant without blocking the UI.

Let's get thee one step at a time :)

**Comment by poire-z** [comment]
Closing as probably obsolete after #6424 and other previous Wi-Fi related PRs.
