### ISSUE TITLE
Indentation bugs

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2715]
* KOReader version: v2015.11-942-g339e166
* Device: Kobo Glo HD

#### Issue
I've encountered the following indentation bugs in KOReader:
1. Manually `<br/>`'d line is indented as well in `<p>` tag with `text-indent` css property set.
2. Indentation on nested lists is completely broken, all sub-levels are rendered with the same margins as the first level.
    * Definition lists (which render correctly outside a list) lose their margins inside a list as well.
    * `<p>` tag inside `<li>` with a `margin-left` of 2em looks like it has been rendered with a margin of 1em

KOReader's rendering behavior:
![reader_2017-apr-03_191008](https://cloud.githubusercontent.com/assets/26367956/24626752/9eb1879c-18b2-11e7-8f32-97315c4743e4.png)

Expected rendering behavior:
![screen shot 2017-04-03 at 21 09 07](https://cloud.githubusercontent.com/assets/26367956/24626733/89007d4a-18b2-11e7-8019-31ac8e28ddb5.png)

#### Steps to reproduce
Attached: epub used to create screenshots
[nested-lists.epub.zip](https://github.com/koreader/koreader/files/891119/nested-lists.epub.zip)

**Comment by poire-z** [comment]
> Manually `<br/>`'d line is indented as well in `<p>` tag with text-indent css property set.

This should have happened only with .html (not with epub) and has been solved by https://github.com/koreader/crengine/pull/172

**Comment by Frenzie** [comment]
Which has been merged in #3928 so closing. ;-)

**Comment by poire-z** [comment]
OK, so this can be closed now :)
Fixed on new documents after https://github.com/koreader/crengine/pull/188, https://github.com/koreader/crengine/pull/192, https://github.com/koreader/koreader/pull/3976, so in a next nightly.
