### ISSUE TITLE
"Cannot open last file" warning triggered with "Start with last opened file" option turned off

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2716]
* KOReader version: v2015.11-942-g339e166
* Device: Kobo Glo HD

#### Issue
"Cannot open last file" warning is triggered after removing previously read book even with "Start with last opened file" option turned off.

#### Steps to reproduce
1. Make sure "Start with last opened file" is turned off.
2. Open a book.
3. Quit KOReader.
4. Delete file from computer.
5. Start KOReader.
    * It will show the message
      ```
      Cannot open last file.
      This could be because it was
      deleted or because external
      storage is still being mounted. 
      Do you want to retry?
      ```
   * This message should not be triggered unless the book is opened for reading, either by the user or automatically with "Start with last opened file" option turned on.

**Comment by Frenzie** [comment]
@robert00s In the changes that were added in your #2603 you should also check for `open_last`. I think it would probably suffice to do something like this but that's just based on a quick skim. NB open_last is currently located a few lines lower: 

```lua
-- load last opened file
local open_last = G_reader_settings:readSetting("open_last")
local last_file = G_reader_settings:readSetting("lastfile")
if open_last and last_file and lfs.attributes(last_file, "mode") ~= "file" then
```

**Comment by Biep** [comment]
Yesterday I updated - development channel: 2022.10-137.
Then I deleted the book I had been reading and the directory it was in, and quit KOReader.
When returning, it tried to open the last book, and failed, giving me the options to Cancel or Try again.  Both options repeatedly led to KOReader exiting (and nickel starting - KFMon)- and upon restart the same thing would happen.
I had to connect to my computer and change "start_with" to "none" to get the thing working again.  (I got one crash then, but after that things seem to work well.)
(And then I could not find where to set this value from the menu.  Editing the settings file with the built-in editor did not work, so I had to connect to the computer again to set the value back to "last".

I am in the airport now leaving for Burkina Faso, where I am unlikely to have Internet, so don't expect me to reply soon.
That is also why I don't include a crash report.

**Comment by Frenzie** [comment]
That setting can be found in the file browser menu, but a deleted file shouldn't be able to cause any trouble.

![Screenshot_20221130_105039](https://user-images.githubusercontent.com/202757/204764002-056ee0b5-e379-4fe5-899c-7b2929cb9e9e.png)
