### ISSUE TITLE
FR: double tap to go back or forward 10 pages

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2721]
Split out from https://github.com/koreader/koreader/issues/2410#issuecomment-267044394

@retrue wrote:
> Another gesture that I would like to see implemented in KOReader is the option to advance or go back 10 pages. It makes browsing pages inside a book nimbler. It is an option that I miss and was included in Coolreader in my first e-reader, a Jinke Hanlin v3+. And I think a double tap would be the best gesture in this case.

**Comment by poire-z** [comment]
Let's not forget the following comments:

From me:
> The problem with double tap is that it will slow down reaction of other single taps (you can enable double tap in the Screen menu to see).

To which houqp replied:
> This is a bug in the double tap detection code (gesturedetector.lua). I suspect it's problem of finding the right value for DOUBLE_TAP_INTERVAL. If it's too high, wait time for single tap detection will increase, if it's too low, it would be too hard for user to perform a double tap.

I'm just not sure it's a bug, just a matter of "finding the right value", which will slow down single tap reaction anyway, no ?
But may be this existing setting ["disable_double_tap"] = true is enough to disallow double tap waiting in the gesture detector, and any double_tap feature would be disabled for those who prefer quick reactions, and those who want double tap, but slower reaction to single tap, can let it to false ?

**Comment by Frenzie** [comment]
Right, good point. I'd like to add that I consider the implementation details secondary to the request. I'd probably assign a new action to swiping east and west at the bottom of the screen. This largely comes down to #1008. It'd also be cool to do something like `left, down` for previous chapter and `right, down` for next chapter. But just like how my new menu implementation enables changing these things sensibly, something similar is really required for registering gestures. And of course GestureDetector doesn't currently have support for chaining gestures like that in the first place, which would hardly be trivial either.

The 300ms used to be pretty standard (and horribly annoying) in mobile browsers for zoom: http://www.telerik.com/blogs/what-exactly-is.....-the-300ms-click-delay

I think that 100ms feels *a lot* better, although it depends on the document in question. A borderline slow document suddenly becomes slow that way. But while I think 300ms is an insensibly long default, the fact that I'd personally go for something closer to 50ms or less (I'd have to test) would similarly not work. I'd say that double-tap timeout is definitely the kind of thing that is served by a setting.

**Comment by retrue** [comment]
About double tapping. Currently can be enabled or disabled through the menu and it is disabled by default. But people like me have it enabled because we like the possibility of jumping back to previous chapter or forward to next one. In our case, we welcome more gestures added to double tap and we don't see any problem at all with that.
But I don't see any problem either with removing double tap completely if the possibility of jumping back and forth between chapters is kept by substituting double taps with new gestures.
