### ISSUE TITLE
NEW: Synchronize time

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2722]
* KOReader version: last nightly build.
* Device: Kobo Mini

#### Issue
The menu item "Synchronixe time" is called "NEW: Synchronize time"
I include screenshot.

![filemanager_2017-apr-04_135117](https://cloud.githubusercontent.com/assets/18194241/24655412/7d85f51c-193e-11e7-8bec-c340a5d77610.png)

**Comment by Frenzie** [comment]
I must've forgotten to add it to the filemanager menu.

**Comment by lgeek** [comment]
I've noticed this but thought it was a feature

**Comment by Frenzie** [comment]
The "NEW:" prefix is a feature intended to make sure users with customized menus are aware of new menu items so they can either integrate them into their menu or explicitly disable them. But in this case it's indicating that I forgot to add it to the default menu. :-)
