### ISSUE TITLE
Russian localization

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2732]
* KOReader version: v2015.11-957-g1749ab7
* Device: Kindle 7th generation

#### Issue
Russian translation of some UI strings is bad.
#### Steps to reproduce
Is it done with Google translate? I could improve it. I couldn't find in the github tree where the messages are.

**Comment by houqp** [comment]
See https://github.com/koreader/koreader#translation. You can request to join the russian translation team if you haven done so.
