### ISSUE TITLE
Read progress sync server is down

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2738]
* KOReader version: independent
* Device: independent

#### Issue

I am using https://hzj-jie-ubuntu.westus.cloudapp.azure.com:7200. But it does not respond.

**Comment by houqp** [comment]
Nothing is listening on port 7200 on the server. Do you remember how the server was setup initially?

**Comment by Hzj-jie** [comment]
Oh, I thought you have changed some configuration. If not, I will try to execute it again.

**Comment by houqp** [comment]
Yup, I haven't migrated the sync service to docker yet, so I haven't touched it ;)
