### ISSUE TITLE
Sentence in ebook gets truncated 

### ISSUE THREAD

**Issue by tobiasKaminsky** [koreader/koreader#2739]
* KOReader version: v2015.11-894-gd168db9
* Device: Kindle Paperwhite 2012

#### Issue
Sentence in ebook gets truncated in middle of word and rest of paragraph is skipped. This happens every 5-7 kindle pages.
It happened on the current book that I read, as I am new to koreader. I therefore do not know if other books are also affected.
The ebook itself is fine as it can be displayed without problems in the regular reading system of the same kindle

#### Steps to reproduce
If needed, I can provide the ebook.

**Comment by Frenzie** [comment]
What's the file format?

**Comment by tobiasKaminsky** [comment]
Mobi, I can send you the file, if you want.
Meanwhile I also tried it on android and it the same error occurs.
As I am experienced I also can to debug this in android, if you think this helps (and if you give me a hint where I should look)

**Comment by Frenzie** [comment]
From what I've heard Mobi support isn't very good in crengine and converting to EPUB or PDF (e.g., with calibre) would yield better results (see https://github.com/koreader/koreader/issues/2191#issuecomment-236374377). That being said, I haven't heard of things being truncated. I'm not really the right person to ask in this case as I know nothing about the Mobi format. :-)

**Comment by houqp** [comment]
yup, we don't officially support mobi since it's a proprietary format.

**Comment by tobiasKaminsky** [comment]
I converted it with calibre to epub and now it is working fine 👍 
So, it is fine for me :-)
But if you want, we can try to debug this together or feel free to close it.

Thank you for the cool software!

**Comment by Frenzie** [comment]
If you really want to, the easiest way would be to set up an emulator build. 

https://github.com/koreader/koreader#building-prerequisites

Then I think (but I've only taken a really quick peek so I might be wrong) that around here would be the place to start: https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/crengine/src/pdbfmt.cpp

Personally I'd rather focus my attention elsewhere, but patches are always welcome. :)

**Comment by Frenzie** [comment]
I'll close now this since mobi is low priority and you know a good workaround. :-)
