### ISSUE TITLE
Kobo Aura HD display is upside down

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2740]
* KOReader version: 963
* Device: Kobo Aura Hd

#### Issue

The display suddenly becomes upside down. Restarting the device won't help. Indeed the device is in a strange state: each refreshing in Kobo Start Menu 08 rotates the screen.
I have also upgraded the stock software, still no luck.

#### Steps to reproduce

No idea, happened suddenly.

**Comment by houqp** [comment]
have you tried a factory reset? does it behave the same way in stock firmware?

**Comment by Hzj-jie** [comment]
No, stock software works well.

**Comment by houqp** [comment]
refresh in koreader also refreshes the screen?

**Comment by Hzj-jie** [comment]
No, in KOReader, the screen is always upside down.

**Comment by Hzj-jie** [comment]
The behavior seems consistent with the one described in https://github.com/koreader/koreader/issues/937

**Comment by Hzj-jie** [comment]
If my memory is reliable, this issue happens immediately after I upgraded to 963. I found this change https://github.com/koreader/koreader/pull/2731/files is suspicious.

**Comment by Frenzie** [comment]
I already included a fix in #2712

**Comment by Hzj-jie** [comment]
Yes, just FYI, reverting to an old koreader.sh resolves the issue. I.e. cat "/sys/class/graphics/fb0/rotate" > "/sys/class/graphics/fb0/rotate" is suspicious.

I believe the change in https://github.com/koreader/koreader/pull/2712 should resolve it.
