### ISSUE TITLE
Rename Statistics to Reading statistics

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2744]
* KOReader version: Last nightlies
* Device: N/A

#### Issue
We have System statistics, Storage statistics, Battery statistics and Statistics. This last one should be renamed to Reading statistics to avoid confusion.

#### Steps to reproduce
N/A

**Comment by Frenzie** [comment]
Agreed, but I believe @Hzj-jie intends to merge the battery & storage stuff into system stats.

**Comment by Hzj-jie** [comment]
I think battery stats deserves a standalone component. But storage will be merged into system - indeed I have already composited the change.
