### ISSUE TITLE
Regression: Wifi manager doesn't open on first attempt to connect Wi-Fi

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2750]
* KOReader version: v2015.11-971-gf1c0b4b
* Device: Kobo Glo HD

#### Issue
Wifi manager doesn't open on first attempt to connect Wi-Fi.
The system says "connecting", then draws two horizontal lines close to each other in the center of the screen. The second connection attempt works (brings up the "Do you want to connect" dialog again). The crash log does not show any dhcp-related messages on the first failed attempt.
I noticed this bug a few days ago, probably not before 957.

#### Steps to reproduce
1. Start KOReader with Wi-Fi off.
2. "OTA update" --> "Check for update"
3. Click "Turn on"
4. GUI says "Scanning..." then draws lines (see screenshot)"
5. Repeat steps 2 and 3, this time it'll work

![filemanager_2017-apr-10_134252](https://cloud.githubusercontent.com/assets/26367956/24864929/fd4985c2-1e05-11e7-9db8-778e270c32d2.png)

**Comment by Frenzie** [comment]
I can't confirm on H2O with the same version. Let's see, 957 is 1749ab7, so that makes for 1749ab7...f1c0b4b. My own #2712 is the only thing that really looks suspicious but if you've already seen this for a few days that wouldn't be it. (Plus I've been testing that for the past week on my own device.)

**Comment by a-kohout** [comment]
Unfortunately my guess was wrong. It appears that this bug has been introduced between 942 and 947.

**Comment by Frenzie** [comment]
339e166...a6ca0f9

In that case the only possible cause I can spot is that lj-wpaclient was bumped as part of #2553 https://github.com/koreader/koreader-base/compare/26bfa43e1d7580a63b4fe4021c23334f9cf2ca62...8396c9e9139dff2b190a3e328317d5c49a861a4a#diff-142a18f9b3a45ea8313a8170bbfd9b67

@houqp You know all about this (hopefully). :-)

**Comment by houqp** [comment]
Good catch, the change is https://github.com/koreader/lj-wpaclient/commit/bdb128071b9bf43304885cc40219ca8ada465a44, which is introduced to fix a bug in okreader reported by @lgeek .

@a-kohout can you help confirm this by reverting this change in common/lj-wpaclient/wpaclient.lua? It would be helpful if you can also add one extra debug print around that the code:
```lua
print("debug wpa_supplicant", ev.lvl, ev.msg)
```

If you don't have time to get into this, that's fine, I will take a look myself this weekend.

I suspect wpa_supplicant is sending a `CTRL-EVENT-SCAN-RESULTS` event initially when no network has been found yet.

**Comment by a-kohout** [comment]
Reverting the change fixes this bug, though because since 'CTRL-EVENT-SCAN-RESULTS' is not an 'INFO' message, the loop never breaks and the while loop iterates 20 times (wait_cnt).
Debug line is above if statement.
Log (reverted):
```
04/12/17-18:20:50 INFO  FM loaded plugin zsync at plugins/zsync.koplugin
debug wpa_supplicant	WARNING	CTRL-EVENT-NETWORK-NOT-FOUND
debug wpa_supplicant	WARNING	CTRL-EVENT-SCAN-RESULTS
debug wpa_supplicant	WARNING	CTRL-EVENT-CONNECTED - Connection to 34:31:c4:42:79:8b completed [id=0 id_str=]
debug wpa_supplicant	WARNING	WPA: Key negotiation completed with 34:31:c4:42:79:8b [PTK=CCMP GTK=CCMP]
debug wpa_supplicant	WARNING	Associated with 34:31:c4:42:79:8b
debug wpa_supplicant	WARNING	Trying to associate with 34:31:c4:42:79:8b (SSID='Aloha' freq=2437 MHz)
debug wpa_supplicant	WARNING	CTRL-EVENT-SCAN-RESULTS
debug wpa_supplicant	WARNING	CTRL-EVENT-BSS-ADDED 4 40:3c:fc:05:31:09
debug wpa_supplicant	WARNING	CTRL-EVENT-BSS-ADDED 3 c0:3f:0e:bd:f5:40
debug wpa_supplicant	WARNING	CTRL-EVENT-BSS-ADDED 2 4a:d2:24:38:0a:cd
debug wpa_supplicant	WARNING	CTRL-EVENT-BSS-ADDED 1 00:23:df:f8:c9:31
debug wpa_supplicant	WARNING	CTRL-EVENT-BSS-ADDED 0 34:31:c4:42:79:8b
udhcpc (v1.22.0.kobo) started
Sending discover...
Sending select for 10.0.0.71...
Lease of 10.0.0.71 obtained, lease time 864000
adding dns 10.0.0.1
```

Log (not reverted): 
```
04/12/17-18:26:16 INFO  FM loaded plugin zsync at plugins/zsync.koplugin
debug wpa_supplicant	WARNING	CTRL-EVENT-NETWORK-NOT-FOUND
debug wpa_supplicant	WARNING	CTRL-EVENT-SCAN-RESULTS
04/12/17-18:26:37 WARN  no refresh got enqueued. Will do a partial full screen refresh, which might be inefficient
```

This works on my Glo HD, breaks on the second occurrence of 'CTRL-EVENT-SCAN-RESULTS':
Btw wait_cnt decrements to 6 before results are found.
'Scanning...' (on several 4.x firmwares) takes ages compared to Firmware 3.19.5761.
Should this be increased for newer firmwares?

```
    i = 0
    while wait_cnt > 0 do
        -- print("debug wait_cnt", wait_cnt)
        for _,ev in ipairs(self:readAllEvents()) do
            -- print("debug wpa_supplicant", ev.lvl, ev.msg)
            if ev.msg == 'CTRL-EVENT-SCAN-RESULTS' then
                if i > 0 then
                    found_result = true
                    break
                end
                i = i + 1
            end
        end
        if found_result then break end

        wait_cnt = wait_cnt - 1
        -- sleep for 1 second
        ffi.C.poll(nil, 0, 1000)
    end
```

**Comment by houqp** [comment]
Looks like it got an empty scan result from the first `CTRL-EVENT-SCAN-RESULTS` event. Do you also have your wifi network saved in nickel?

Forcing it to do a second scan with a loop counter is a quick workaround. I think a proper fix here would be adding a refresh button so the second scan can be triggered manually. In the long, when we have proper background task support, we can just keep scanning in the background and update the UI for newly found networks.

**Comment by lgeek** [comment]
Hmm, now that I think about it, I think I've sometimes seen fewer results than expected, but never completely empty and my own AP was always on there. That's with brcmfmac and not bcmdhd.

Adding a refresh button is in the works, as part of #2706. It mostly works, but I need to debug a screen update issue and I've been busy with other things.

**Comment by houqp** [comment]
@lgeek it's expected to see fewer results. The way it works is wap_supplicant will constantly stream updates for new APs it found and the application is suppose to listen to the update and update the UI accordingly. This part unfortunately requires background task support.

If you can push your current work in progress code to a branch, I can help with the update and send you PRs.

**Comment by a-kohout** [comment]
Yes, wifi network was entered in nickel.

**Comment by houqp** [comment]
That might be why it's returning an empty list on the first scan. Wpa_supplicant was probably busy auto connecting to the network saved in nickel based on the `CTRL-EVENT-CONNECTED` event shown in your log.

**Comment by lgeek** [comment]
@houqp I've tested the scanning behaviour using wpa_cli on my computer and that's not how it works by default (that is, with no configuration file): all networks are available immediately after it sends `CTRL-EVENT-SCAN-RESULTS` and unless I issue a new `scan on` command no new networks are discovered, while the previous results are removed after a time without scanning. I see that there are a number of scanning options available in `wpa_supplicant.conf`. Are any of those set on Kobo's firmware? I don't have any devices on hand.

**Comment by houqp** [comment]
@lgeek which scan option are you interested in specifically? I can help check on my kobo.

**Comment by houqp** [comment]
Another thing we can do is to remove all the network loaded from `wpa_supplicant.conf` in koreader when wifi manager is first enabled since we are not using it anyway.

Off topic: @lgeek I noticed you removed the line to kill wpa_supplicant on suspend, did you notice any issue with it interrupting the suspend? If not, I am considering port that patch to koreader too.

**Comment by a-kohout** [comment]
Deleting the network in Nickel and entering the password again in KOReader did not make a difference. The list still comes up empty the first time. One thing did change, though. With the network saved in Nickel the device auto-connects. With the network saved in KOReader, this doesn't happen. Instead WPA supplicant status is being shown as InfoMessages after touching the network to connect. IMHO behavior should be consistent regardless where the password is being read from

**Comment by cramoisi** [comment]
Hello.
Got a problem somehow related on my kobo Glo HD
Version tested :
- koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-995-gd6c81f5
- koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1006-g6f037ce

When turning wifi on : 

cog > network > wifi connection
"do you want to turn on wifi" > Turn on 
(at this point, I wait 15 seconds)
Then I got this error each time :

Failed to initialize network control client : Failed to connect to wpa_supplicant control socket : /var/run/wpa_supplicant/eth0.

The wifi is ok in Nickel side.

Searching crash.log gave me this : 
-- first try
insmod: can't read '/drivers/ntx508/wifi/sdio_wifi_pwr.ko': No such file or directory
insmod: can't insert '/drivers/mx6sl-ntx/wifi/dhd.ko': invalid parameter
ifconfig: SIOCGIFFLAGS: No such device
wlarm_le: wl driver adapter not found
-- second try
ifconfig: SIOCSIFADDR: No such device
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device

**Comment by spelufo** [comment]
I don't run nickel, only koreader. Wifi didn't work and I got the "Failed to connect to wpa_supplicant control socket" error. Overwriting `/etc/wpa_supplicant/wpa_supplicant.conf` with `/etc/wpa_supplicant/wpa_supplicant.conf.template` fixed it for me.
I don't know how related my problem was to the problems described here, though.

**Comment by cramoisi** [comment]
Do you run it with ksm8 or advboot ? I only get this issue with advboot.

**Comment by spelufo** [comment]
Neither. I launch koreader from the `/etc/init.d/rcS` boot script. The same script had the following lines:
```sh
if [ ! -e /etc/wpa_supplicant/wpa_supplicant.conf ]; then
    cp /etc/wpa_supplicant/wpa_supplicant.conf.template /etc/wpa_supplicant/wpa_supplicant.conf
fi
```
Here is my `wpa_supplicant.conf.template`:
```
 # cat /etc/wpa_supplicant/wpa_supplicant.conf.template 
ctrl_interface=/var/run/wpa_supplicant
update_config=1
```
I don't know what koreader/advboot/ksm expect, or how this is supposed to work, I just saw that line on the boot script and thought maybe there was some stale config in my wpa_supplicant.conf so I replaced it with the .template one that was there. I'm not saying this will fix your problems, only sharing the information in case it helps.

**Comment by cramoisi** [comment]
Sorry for the delay : doesn't work for me ...
/etc/wpa_supplicant/wpa_supplicant.conf contains the same two lines than /etc/wpa_supplicant/wpa_supplicant.conf.conf and informations for connecting my home network. I overwrite it with the .template one but still got the "Failed to initialize network control client : Failed to connect to wpa_supplicant control socket : /var/run/wpa_supplicant/eth0."

**Comment by orangemango** [comment]
**Context**

- KOReader version: v2015.11-1523-g78284e1
- Device: Kobo Touch (v1)
- Kobo Start Menu v9
- WiFi works perfecly with Nickel

**Issue**

`Failed to initialize network control client : Failed to connect to wpa_supplicant control socket: /var/run/wpa_supplicant/eth0.`

**Steps to reproduce**

Try to activate WiFi.

`Tools -> Network -> Wi-Fi Connection [_]` click "Turn on"

**Already tried**

- Using KSM "xdel wpa supplicant.conf.sh" doesn't helps
- Having WiFi turn on or turn off in Nickel makes no change
- I can't try with _v2015.11-stable_ because I will be stuck in File explorer with a popup "copy/paste/set home folder"
