### ISSUE TITLE
Feature proposal: support dictionaries in Kindle native format

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2751]
* KOReader version: v2015.11
* Device: Kindle

#### Issue
Amazon provides Kindle purchasers with some 30 dictionaries which may not be available in StarDict format, e.g. Oxford English Dictionary or Duden German. It would be nice to be able to use them with KOReader. I used to be a reasonably competent software developer and could try to implement it, but I am new to development for Kindle, or any gadget, and have no idea how difficult it would be. Does Kindle environment provide application developer with means to embed its stock book reader in the applications?

**Comment by Frenzie** [comment]
Would that be legal?

**Comment by ilyats** [comment]
Hm, [Kindle Store Terms of Use](https://www.amazon.com/gp/help/customer/display.html?nodeId=201014950) says content may be viewed _solely through a Kindle Application or as otherwise permitted as part of the Service_. If one can display Kindle reader in a window of KOReader, would that count as reading through a Kindle Application? I am not a lawyer.

**Comment by Hzj-jie** [comment]
I do not even think KOReader is a Kindle application :)

**Comment by KenMaltby** [comment]
A "Duden" stardict dictionary is one of the commoner german dictionaries that work in KOReader.  Would like an oxford English one though.

**Comment by ilyats** [comment]
@KenMaltby thanks, I didn't know Duden was available as StarDict.

**Comment by houqp** [comment]
Yup, KOReader is not a kindle application. IIRC, amazon never opened up their API for 3rdparty app developers.

**Comment by Frenzie** [comment]
I'll close this then. :-)
