### ISSUE TITLE
OTA update installs update in wrong koreader installation directory

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2752]
* KOReader version: v2015.11-963-g3a75b6d
* Device: Kobo Glo HD
* Launcher: KSM 08 Patch 04e (as recommended for Kobo Firmware 4.3.8966)

#### Issue
Updates are applied to .adds/koreader directory even if running from a different directory, e.g. .adds/koreader963

#### Steps to reproduce
1. Install two different versions of koreader, for example any older version in
    * .adds/koreader
and v2015.11-963-g3a75b6d in
    * .adds/koreader963
2. Use KSM functionality "select koreader version" to start the installation in .adds/koreader963
3. Perform OTA update
4. The installation in .adds/koreader will be up-to-date, while the installation in .adds/koreader963 will remain unchanged.
    The update process downloads the ota file correctly to .adds/koreader963/ota but extracts it to .adds/koreader

**Comment by houqp** [comment]
I am not familiar with how the version switches is implemented in KSM. In fact, I don't even know this awesome feature existed! Based on what we have in the koreader.sh script, it should be extracting the update to the current working directory: https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L12.

Do you see a `/ota/koreader.installed.tar` or `/ota/koreader.updated.tar` file in `koreader963`?

**Comment by a-kohout** [comment]
I found that feature by accident.
There has to be one koreader installation in a folder named 'koreader'.
Additional koreader versions in folders which names start with 'koreader' show up in the version select menu.

`/ota/koreader.installed.tar` does end up in `koreader963`

```
Andreas-MBA:.adds Andreas$ ls -lsa koreader/ota/
total 96
 8 drwxrwxrwx  1 Andreas  staff   4096 Apr 11 22:21 .
16 drwxrwxrwx  1 Andreas  staff   8192 Apr 11 22:20 ..
72 -rwxrwxrwx  1 Andreas  staff  33693 Apr 10 06:33 package.index
Andreas-MBA:.adds Andreas$ ls -lsa koreader963/ota/
total 88040
    8 drwxrwxrwx  1 Andreas  staff      4096 Apr 11 22:21 .
   16 drwxrwxrwx  1 Andreas  staff      8192 Apr 11 22:21 ..
  472 -rwxrwxrwx  1 Andreas  staff    240856 Apr 11 20:16 koreader-kobo-latest-nightly.zsync
    8 -rwxrwxrwx  1 Andreas  staff       162 Apr 11 20:15 koreader-kobo-latest-stable.zsync
87464 -rwxrwxrwx  1 Andreas  staff  44779520 Apr 10 06:33 koreader.installed.tar
   72 -rwxrwxrwx  1 Andreas  staff     33693 Apr  8 08:32 package.index
```

**Comment by KenMaltby** [comment]
I doubt that tshering had the KOReader OTA function in mind when he implemented that feature.  If you can find the KOReader folder that was updated, you should be able to have it "show up in the version select menu" as you want it.  You may just overwrite the folder you want updated.

**Comment by a-kohout** [comment]
That was just a short description how that feature works. Koreader does show up in the version select menu just fine. The problem is Koreader's OTA process which updates the wrong folder (the main one, even if it is running from a different one started via the version select menu).
KSM is not at fault here.
The culprit is here https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L12.

`KOREADER_DIR` expands to the folder in which koreader.sh is located, in this case `/mnt/onboard/.adds/koreader963`
```
# working directory of koreader
KOREADER_DIR="${0%/*}"
```

`cd "${KOREADER_DIR%/*}"` changes the current directory to `/mnt/onboard/.adds`

since the tar file contains one folder called `koreader`and no destination is specified, this folder extracts to `/mnt/onboard/.adds/koreader` overwriting the existing installation

Fix:
Change line 1-16 of `koreader.sh`:
```
#!/bin/sh
export LC_ALL="en_US.UTF-8"

# working directory of koreader
KOREADER_DIR="${0%/*}"

# we're always starting from our working directory
cd "${KOREADER_DIR}"

# update to new version from OTA directory
NEWUPDATE="${KOREADER_DIR}/ota/koreader.updated.tar"
INSTALLED="${KOREADER_DIR}/ota/koreader.installed.tar"
if [ -f "${NEWUPDATE}" ] ; then
	# TODO: any graphic indication for the updating progress?
	./tar xf "${NEWUPDATE}" --strip-components=1 -C "${KOREADER_DIR}" && mv "${NEWUPDATE}" "${INSTALLED}"
fi
```
Change to koreader working dir needs to be done before OTA logic in order to use bundled tar binary which supports --strip-components

**Comment by Frenzie** [comment]
Nice work! I made a PR because you've got a copy of the "old" code there from 3+ days ago and it would've errored out on the new code quality and coding style checks. For future reference, you don't need to figure out Git for such simple changes. You can just click the little edit button in the top right. :-)

PS To link to a specific version of a file you can press <kbd>y</kbd>. For example, kodev changed a bit due to coding style enforcement. Three days ago: [L406-L419](https://github.com/koreader/koreader/blob/e5bcdee85e78424b844386d2fcf4d719ee8762c9/kodev#L406-L419). Now: [L490-L503](https://github.com/koreader/koreader/blob/e8c01274f4d1ef81ebc431ad50a4af9de3000148/kodev#L490-L503). The code is almost entirely the same. The line numbers have changed.

**Comment by a-kohout** [comment]
Thanks for merging.
@Frenzie Since you added `|| exit` to `cd "${KOREADER_DIR}"`, `-C "${KOREADER_DIR}"` isn't needed. I added that to make sure that tar would unpack to the right location. Since `cd "${KOREADER_DIR}" || exit` quits the script if `cd` fails, `-C "${KOREADER_DIR}"` can be safely removed.
