### ISSUE TITLE
Frontlight level in Status bar in Kobos without light

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2760]
* KOReader version: Last nightly
* Device: Kobo Mini, possibly other devices without light

#### Issue
Small problem.
In gear, in the _Status bar_ menu entry, one of the options is _Frontlight level_, in my Kobo Mini and possibly all the other devices without light. In other parts of the menu, there is already code to no show frontlight options in devices without light, so I guess it would be easy to implement here too.

![reader_2017-apr-13_090213](https://cloud.githubusercontent.com/assets/18194241/24993853/72dc9526-2028-11e7-9edd-47adca6f1bfd.png)

**Comment by houqp** [comment]
Yes, it's an easy change. Anyone interested in doing this please let me know, I can help point to the right direction.

Files to change: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerfooter.lua#L445

Reference:
https://github.com/koreader/koreader/blob/master/frontend/ui/elements/common_settings_menu_table.lua#L10
