### ISSUE TITLE
Manage .otf fonts

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2769]
* KOReader version: v2015.11-988-g6542382
* Device: Kobo Glo HD

#### Issue 
In a book with included .ttf and .otf files, the text using .otf font isn't displayed properly. I don't know if Koreader doesn't manage .otf files in general, or if it is related to the specific font file. I can provide all required information if needed (log file, screencapture...)

**Comment by Frenzie** [comment]
Looks like several different kinds of fonts should be supported

https://github.com/koreader/crengine/blob/a09aac18672f5f9c57d87457afbac205001ed793/crengine/src/lvfntman.cpp#L2012

**Comment by frankyifei** [comment]
if you can provide the book to test

**Comment by Brnoch** [comment]
I just sent it to you privately. Hope this will help!

**Comment by poire-z** [comment]
I've seen no problem lately with books with embedded ttf or otf files.
So, this may have been fixed by the various crengine changes over the last year.
Re-open if it is not.
