### ISSUE TITLE
FR: better line spacing/margin/etc. small/med/large UI

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2771]
* KOReader version: 76c7747
* Device: all

#### Issue
Large (PDF) margin is somewhat small and could be bigger: https://www.mobileread.com/forums/showthread.php?p=3506579#post3506579

Some brainstorm:

1. Make large more like medium and large something bigger (0.4?). This could be more of a DPI-related bug than a FR but I haven't investigated.
2. Add <kbd>-</kbd>/<kbd>+</kbd> buttons for fine-tuning.

It could look like
<kbd>-</kbd><kbd>S</kbd><kbd>M</kbd><kbd>L</kbd><kbd>+</kbd>

**Comment by KenMaltby** [comment]
I wonder how adjusting "DKOPTREADER_CONFIG_PAGE_MARGIN = 0.10 -- range from 0.0 to 1.0" 
affects the PDF margins?

**Comment by seacatwu** [comment]
Great!Can you make the setps configurable?

**Comment by houqp** [comment]
DKOPTREADER_CONFIG_PAGE_MARGIN sets the default value for margin.

**Comment by seacatwu** [comment]
#1978

**Comment by Frenzie** [comment]
My bad. Closing this one in favor of your issue.
