### ISSUE TITLE
support history as the default view for filemanager

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2774]
see discussion in https://github.com/koreader/koreader/issues/2614

This should be a configurable thing.

**Comment by Frenzie** [comment]
Also note what @KenMaltby said:

> Perhaps replacing the "Start with last opened file" With; "Start with>" then "Last opened file", "History list", or "My file".

https://github.com/koreader/koreader/issues/2614#issuecomment-294352627

**Comment by ersi-dnd** [comment]
And I think the history list view would be best when it's fully integrated with the file browser. Meaning: no bubble around the history list. Just the list of files like in file browser, except that at the top it should read *History (List)* instead of *KOReader File Browser*
