### ISSUE TITLE
FR: automatically exit to file browser after finishing reading quick start guide

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2776]

**Comment by KenMaltby** [comment]
Is it still "File Manager" or is it "File Browser", now?

**Comment by houqp** [comment]
updated the title, thanks

**Comment by Frenzie** [comment]
You mean instead of showing the book status at the end?

**Comment by KenMaltby** [comment]
After showing the book status at the end, makes more sense that returning to the last page of the book, but this appears to be for the "quick start guide.  Does that get a book status page, if so why?

**Comment by Frenzie** [comment]
As far as displaying goes it's just a regular HTML file. The only special thing is that it's generated and opened on first run.

**Comment by houqp** [comment]
Yes, skip the book status and go straight back to file browser.

**Comment by KenMaltby** [comment]
After finishing a document/book, (and seeing a "Status page" if required) it would be a normal workflow to go looking for my next read.  So would be good for all documents/books, IMHO.  Some who opened the book from the History list, might prefer returning there, though.

**Comment by houqp** [comment]
That's a good point, maybe we can just add a button in book status page for quick navigation. For those who have book status page disabled, we can go back to the browser directly.

**Comment by Frenzie** [comment]
I'm not sure if those who disabled automatic book status would appreciate auto-closing (myself included), but a couple of convenience shortcuts in the status window sounds good.

Incidentally, should the quick start guide still exhibit special behavior when it's opened as a regular document as opposed to automatic display on first run? (Regardless whether it's through Help > Quickstart, the file browser or history.)

**Comment by houqp** [comment]
> I'm not sure if those who disabled automatic book status would appreciate auto-closing (myself included), but a couple of convenience shortcuts in the status window sounds good.

A confirm box for exit perhaps in that case.

> Incidentally, should the quick start guide still exhibit special behavior when it's opened as a regular document as opposed to automatic display on first run? (Regardless whether it's through Help > Quickstart, the file browser or history.)

If we make it easy to exit for all documents, then there is not special behavior ;)

If we want to keep it to only quick start guide, then i would expect it to behavior the same even launched from help menu since in those cases, it's not opened like a regular book.

**Comment by a-kohout** [comment]
+1 for going back straight to the file browser.
Also, it shouldn't be recorded in history IMO and "open last book" should open the last book read by the user, not the quickstart guide.

**Comment by a-kohout** [comment]
Also, the file manager should open in the library location when exiting the quickstart guide, not inside the koreader installation folder where the quickstart guide is located.
