### ISSUE TITLE
make quick start guide easier to translate

### ISSUE THREAD

**Issue by houqp** [koreader/koreader#2777]
Right now it's a blob of markdown mixed with html tags, which is not friendly for translation for the following reasons:

* the whole text needs to be retranslated on one byte change
* markup syntax should not be part of the translatable string

The guide itself should probably be a separate project on transifex. Then we can extract each content line into a translatable string. This is how gentoo manages their wiki translations.

**Comment by Frenzie** [comment]
> the whole text needs to be retranslated on one byte change

It would be convenient if Transifex highlighted the differences between the suggestion source string and the current source string, but you just use the most relevant suggestion and adjust it slightly. I thought those suggestions based on previous translations and the concordance were pretty much the whole point of using Transifex. ;-)

> markup syntax should not be part of the translatable string

The anchors are certainly ugly (and wouldn't be that much better if luamd supported `{#whatever}`), but surely emphasis and such should be?

**Comment by houqp** [comment]
Looks like we can just use the txt format support in transifex. They will automatically split the content into lines for us :)

see: https://docs.transifex.com/formats/txt

> The anchors are certainly ugly (and wouldn't be that much better if luamd supported {#whatever}), but surely emphasis and such should be?

Good point, I was mostly thinking about html tags.

**Comment by Frenzie** [comment]
I'll close this because translation of the string in question has not shown itself to be problematic in practice. The move to Weblate (cf. #3754) made it even less so.
