### ISSUE TITLE
Update menu items of evernote plugin

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2778]
* KOReader version: Up to #2775
* Device: Independent

#### Issue

The menu items of evernote plugin are confusing; we would be better to update it.

A potential solution is,
```
Login
Export nodes from all books
Export nodes from this book (Unclickable in FileManager)
Export to --- (Unclickable)
  >> Evernote
  >> HTML
  >> Text
```

**Comment by houqp** [comment]
I think this would be better served with a pop up dialog. Then you can have the following UI setup:

```
From:
[x] export notes from all books
[ ] export ntoes from this book (hide or uncheckable in file browser)

To:
[button: Evernote] [button: HTML] [button: Text]
```

**Comment by Frenzie** [comment]
I'm not sure if this is still relevant, pinging @Galunid.

**Comment by Galunid** [comment]
Sure, I can do that, although is there a point? And if so, which one should be implemented, the OP's one, or houqp's one? Personally I like it how it is, but it shouldn't be a big deal to change it.

**Comment by Frenzie** [comment]
There's one thing that hadn't been implemented in 2017, the separator. I'll stick some in.
<img src=https://user-images.githubusercontent.com/202757/85256496-9d7a7900-b464-11ea-8237-19169c29f1d6.png width=50%>

I understand what's being called confusing here. You can't click export until you select one of those checkmarks.

I think houqp's suggestion is better but personally I have no interest in implementing/testing it.
