### ISSUE TITLE
txt.css always overwrites font setting

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2779]
* KOReader version: Up to #2775
* Device: Independent

#### Issue

When txt.css is selected, font setting does not take effect.
The suspicious css is https://github.com/koreader/crengine/blob/727a0d2f8ca8eb7d08b7e926252155edbbe53ebc/cr3gui/data/txt.css#L140.
But we may find a better solution to apply font face in crengine.

**Comment by Frenzie** [comment]
Might be intentional as part of #2702?

I had a `self._document:setStringProperty("styles.pre.font-face", "font-family: \"" .. self.default_font .. "\"")` in there at first. Might be worth investigating and reintroducing.

**Comment by Frenzie** [comment]
Closing because txt.css is considered obsolete since <https://github.com/koreader/koreader/pull/3996>.
