### ISSUE TITLE
Use find {DATA} -name metadata.*.lua for ReadHistory

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2780]
* KOReader version: Up to #2775
* Device: Independent

#### Issue

Currently the read history maintains its own record file.
The advantages are,
1. Cheap, reading one file is enough.
2. Covering files out of home folder.

The disadvantages are also obvious,
1. Synchronizing the record file with file system is painful. Lots of operations need to be covered: copy / move / rename / delete. Indeed, we do not cover most of them.
2. Easy to be clear. Once my reading history was cleared because of an unexpected restart.
3. Cannot cover other file system changes out of KOReader.

So a potential solution is to use find command to build the ReadHistory during the start, and append newly opened files into the generated list. So we do not need to have a single record file.

The disadvantages are the advantages of current solution, but I doubt the performance should be on-par, and placing files out of home folder is not a regular behavior.

**Comment by Frenzie** [comment]
Reference to #2789.

**Comment by Frenzie** [comment]
> Synchronizing the record file with file system is painful. Lots of operations need to be covered: copy / move / rename / delete. Indeed, we do not cover most of them.

Not covering delete is a definite feature in my book, not a disadvantage at all.

> Easy to be clear. Once my reading history was cleared because of an unexpected restart.

If there's no atomic swap in place that's a bug but it doesn't really seem like a disadvantage.

**Comment by poire-z** [comment]
> Once my reading history was cleared because of an unexpected restart.

And it has been made more solid with using `ffiutil.fsyncOpenedFile(f) -- force flush to the storage device`.

Closing as I don't think any of us would like to use "find" for that.
