### ISSUE TITLE
Prompt to restart once free memory is less than 5% (TBD)

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2782]
* KOReader version: Up to #2775
* Device: Independent

#### Issue

In SystemStat plugin, there are enough information to help the users make the decision automatically: whether KOReader needs to be restarted to avoid performance decrements. So we can add another plugin, it uses SystemStat to retrieve memory usage information, and notice the user once free memory is less than 5% (TBD).

**Comment by houqp** [comment]
We will need to find the proper threshold here. I believe `os.execute` should already stop working at %5 free memory because it won't be able to fork anymore, which will cause suspend to fail.

**Comment by NiLuJe** [comment]
That'd imply polling the system's health at regular intervals, though, wouldn't it?

**Comment by Frenzie** [comment]
I'll close this one, but please feel free to play around with a plugin if you want. ^_^

**Comment by NiLuJe** [comment]
c.f.,

https://github.com/koreader/koreader/blob/e955a28796340594d6898e76140a4993402d33e0/frontend/cache.lua#L299-L319
