### ISSUE TITLE
crash on opening advanced settings

### ISSUE THREAD

**Issue by luckyfatpig** [koreader/koreader#2785]
example:open a document on page 55, then force stop on page 100. reopen it the page will back to page 55, not 100 nor 99

**Comment by Hzj-jie** [comment]
Unfortunately, yes, this is expected.
In file manager, swipe down to activate menu, in screwdriver and wrench, advanced settings, change DAUTO_SAVE_PAGING_COUNT to 1 to save setting after each page turning. Note, this is very efficient, and will decrease the performance of KOReader. You may set it to a fairly larger value, say 10 or 20 to balance the performance and reliability.

**Comment by Frenzie** [comment]
Should we change it to a default other than nil? I don't mean 1, but something like 5 or 10 (similar to full screen refresh rate).

**Comment by luckyfatpig** [comment]
unfortunately, when i open the advanced settings, the software just stopped and can not reopen it

**Comment by Frenzie** [comment]
Just from opening advanced settings? Do you have a crash log?

**Comment by luckyfatpig** [comment]
maybe it's the android version problem

Frans de Jonge <notifications@github.com>于2017年4月26日星期三 04:10写道：

**Comment by Hzj-jie** [comment]
Yes, on Android advanced configuration page crashes KOReader.

**Comment by robert00s** [comment]
Advanced configuration crashes on Android was fixed in https://github.com/koreader/koreader/pull/3066
