### ISSUE TITLE
an option to activate menu by tapping

### ISSUE THREAD

**Issue by chenxingqun** [koreader/koreader#2786]
* KOReader version: newer than v2015.11-988-g6542382
* Device: all

#### Issue
It would be nicer for users to choose tapping or swiping to activate menu. Please add an option to activate menu by tapping. Thanks.

**Comment by Eduardomb22** [comment]
how do I open the menu now?

**Comment by mwoz123** [comment]
+1 for tap to menu

**Comment by baskerville** [comment]
I find it slightly strange that the menu tap zone I've defined in `defaults.lua` suddenly no longer works.

Shouldn't the links tap zones take precedence over the existing tap zones?

**Comment by robert00s** [comment]
Done in #2932 so we can close this issue. Now we can tap and swipe to activate menu.

**Comment by robert00s** [comment]
@Frenzie 
I think we can close it now. 
Done in #2932 and https://github.com/koreader/koreader/pull/3060
