### ISSUE TITLE
Commented entities won't show up in Advanced Settings

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2787]
* KOReader version: 971
* Device: independent

#### Issue

I used to edit defaults.persistent.lua manually, so I have a commented DAUTO_SAVE_PAGING_COUNT. I tried to use the advanced settings function, but this field does not show up.

#### Steps to reproduce

Open Advanced Settings.

Expected: DAUTO_SAVE_PAGING_COUNT is showing up correctly in the list.
Actual: This field is missing.

I have read the source code of the set defaults component, maybe it's because of the default value of this field. In Lua, nil should equal to "undefined".

Also, we can move SetDefaults to the plugin: it does not likely belong to file manager.

**Comment by KenMaltby** [comment]
Which plugin?  Do you mean to the reader settings?  This being to have the page progress saved, I presume.

**Comment by Hzj-jie** [comment]
The "Advanced settings", we can move it into a plugin to separate it from FileManager, and also make it usable in reader.

**Comment by KenMaltby** [comment]
There were some very involved discussion on this subject and the "settings.reader.lua" got created as a step away from the one "defaults.lua" with both global and reader default settings.  In that discussion I argued for having separate files for each menu structure: for the file manager, for the cr3 reader, and for the PDF reader.  Where each would have a file and an "Advanced settings" feature/widget? for making the settings.

**Comment by Frenzie** [comment]
I'll close this since there's a slow but steady migration away from defaults(.persistent).lua. PRs welcome.
