### ISSUE TITLE
Startup crash after dead battery

### ISSUE THREAD

**Issue by matejdro** [koreader/koreader#2788]
* KOReader version: v2015.11-587-ga55a987
* Device: Kobo Glo HD

#### Issue

My Kobo ran out of battery. I tried to turn it on, but the battery was dead (maybe it tried to start, but then battery gave up midway and some files got corrupted). After charging it, starting KoReader would just flash the frontlight and nothing else would happen. Crash.log contained this:

```
./luajit: frontend/readhistory.lua:79: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	frontend/readhistory.lua:79: in function '_read'
	frontend/readhistory.lua:106: in function '_init'
	frontend/readhistory.lua:130: in main chunk
	[C]: in function 'require'
	frontend/apps/reader/readerui.lua:336: in function 'showReader'
	./reader.lua:163: in function 'action'
	frontend/ui/uimanager.lua:472: in function '_checkTasks'
	frontend/ui/uimanager.lua:618: in function 'handleInput'
	frontend/ui/uimanager.lua:712: in function 'run'
	./reader.lua:175: in main chunk
	[C]: at 0x0000bea5
```

I tried to fix it by deleting Cache direcotry and settings file. That got me into the menu, but opening any book would crash the reader again (re-opening it would throw me back into the menu. Crash.log was empty this time). At that point I just gave up, purged whole KoReader folder and downloaded new version.

Just wanted to report this crashlog, maybe there is bug lurking in there that can be fixed.

**Comment by Hzj-jie** [comment]
I believe this bug has been fixed already, you may update to latest version to resolve the issue.

**Comment by matejdro** [comment]
That is great to hear! Thanks for the answer.
