### ISSUE TITLE
Ancient Greek dictionary support

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#279]
To make koreader the dreamreader for philosophers and philologists support for the ancient languages is a necessity. 
After adding a Latin dictionary successfully, I am thinking of trying to build in support for ancient Greek. 

TesseractOCR claims to support it as one of the only OCR programs around. Any idea whether this would be possible for sdcv?
Would the extra character set cause problems for sdcv? Most of those diacritical marks could be ignored as the greeks don't use them anyway, but the iota subscript (http://en.wikipedia.org/wiki/Iota_subscript) is important.

How would the ancient Greek dictionary entries have to be formatted for sdcv to work?

**Comment by marmistrz** [comment]
Markismus: the dictionary works ok if all diacritic marks are in. Would it be possible to make searching without diacritic marks possible? (iota subscripts, accents, etc.)

**Comment by Markismus** [comment]
Yes, you can decompile both the dictionary and the tesseract traineddata files and alter to them to your needs.

The Stardict dictionary decompiles to a textfile. You can import that in for instance Excel and replace all diacritical characters with normal ones.

In the Tesseract traineddata files, about 12 if I remember correctly, see [issue #327](https://github.com/koreader/koreader/issues/327#issuecomment-31373105). You can modify the file grc.unicharsambigs to replace all diacritical characters with normal ones---this will probably greatly reduce the filesize and hence the speed of the lookup!

I though about doing this for the reason that Greeks don't use diacriticals either and hence they are superfluous for determining the correct dictionary entry. I forgot about it, because I though it would be more efficient to just train Tesseract to recognize diacriticals as normal characters. Clearly, never got around to that one.

**Comment by marmistrz** [comment]
Thanks. Should the script be helpful to anyone, here it is
```
#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage: remove-diacritics.sh [FILE]"
	exit 1
fi

while read line
do
	word=`echo -e "$line" | cut -f 1`
	definition=`echo -e "$line" | cut -f 2`
	clean_word=`echo -e $word | perl -CS -MUnicode::Normalize -pne '$_=NFKD($_);s/\p{InDiacriticals}//g'`
	echo -e "$clean_word\t<h3>$word</h3><br>$definition"
done < $1
```

Thanks to the folks here [1] and here [2]

[1] stackoverflow.com/questions/30393681/removing-diacritical-marks-from-a-greek-text-in-an-automatic-way/
[2] http://stackoverflow.com/questions/30461142/using-cut-on-stdout-with-tabs/

**Comment by Markismus** [comment]
Nice. This should work with the dictionary in txt-format. 
What will you do with grc.unicharsambigs? I think the creator of the traineddata-set for grc put all his data online [here](http://ancientgreekocr.org/) and [here](https://gitorious.org/ancient-greek-training-for-tesseract/pages/Home). So you could manipulate the input data and train Tesseract to disregard the diacritics.

**Comment by marmistrz** [comment]
Well, nothing :) I'm only working on the decompiled dictionary.

**Comment by marmistrz** [comment]
Uploaded the script here. [1] Any further development will take place here.

[1] https://github.com/marmistrz/stardict-tools-ancient-greek

**Comment by marmistrz** [comment]
@Markismus: is there any guide for making a stardict dictionary from pdf with ocr? I'm thinking about converting one dictionary.

**Comment by Markismus** [comment]
I didn't go that route. I searched the internet rather thorough and found an unseeded torrent--after two weeks it mysteriously completed.

You could use ABBYY Finereader for it, because it can output to Excel. There you arrange things in two nice columns and save as cvs-file or create the entire line and copy-paste to a txt-file. No need for programming skills. 

If it's just too much work in Excel, I would program it using Perl on the plain text-file generated by Finereader. More versatile and powerful than fiddling around in Excel.
