### ISSUE TITLE
ERROR cannot open translation file: l10n/en_US/koreader.po

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2792]
* KOReader version: last nightly
* Device: Kobo Mini.

#### Issue

The first line in crash.log is that line, _ERROR cannot open translation file: l10n/en_US/koreader.po_
There must be a small error somewhere.

**Comment by Frenzie** [comment]
It's harmless but should be fixed in #2775

**Comment by houqp** [comment]
This, this is harmless, we have disabled it in #2775
