### ISSUE TITLE
Cannot open pdf or epub files in kindle with koreader

### ISSUE THREAD

**Issue by ccirjan** [koreader/koreader#2797]
* KOReader version: koreader-kindle-arm-linux-gnueabi-v2015.11-stable 
* Device: Kindle 8th generation white, with firmware 5.8.7

#### Issue
I cannot open pdf or epub files on my kindle, either through koreader or from the main menu. I can open pdf's in the main menu only by holding the item and hitting the 'go to' option, and then selecting a section. Otherwise the screen turns blank for a second, then takes me back to the main menu. The same thing happens when I click any option within koreader, except for the (no framework) options, which restarts the device before taking me to the main menu. Does anyone know what's happened? 

#### Steps to reproduce
I did all of this in one sitting: 
1. jailbroke the device using the following instructions https://www.mobileread.com/forums/showthread.php?t=275877
2. installed kvpbooklet by downloading the bin file, uploaded into mrpackages, and triggered MRPI with ;log mrpi
3. Downloaded koreader file above. Placed main koreader file in root directory of kindle and koreader file within extensions file into the extensions file on kindle root. That's it. 

I provided the crash log. Can anyone help me? I would genuinely appreciate it.

./luajit: frontend/device/kindle/device.lua:363: unknown Kindle model 00
stack traceback:
	[C]: in function 'error'
	frontend/device/kindle/device.lua:363: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:37: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:92: in main chunk
	[C]: at 0x0000be8d

**Comment by ccirjan** [comment]
I have solved the problem. Follow the same procedure as I did except use the nightly version of KOreader instead of the stable version. The stable version may have some problem this kindle (8th gen) or this firmware version (5.8.7).

**Comment by aaditya99983** [comment]
please mention the steps

**Comment by Frenzie** [comment]
@aaditya99983 The common thread seems to be what I pointed out in https://github.com/koreader/koreader/issues/3387#issuecomment-338410562
