### ISSUE TITLE
crengine: unwelcomed wrapping on no-break-space

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#2806]
Regarding the issue raised at https://www.mobileread.com/forums/showthread.php?t=285622, and how line wrapping can happen sometimes on no-break-space (NBSP) character:

It's indeed more noticable with french, although i don't see them as much as the original poster (probably because I use a small font).
I made a sample html file with the same sentence:

_L’autre ajouta : « On en a au moins cinquante, des bicoques comme celle-là, sur la voie, entre ici et Roskilde. Vous vous imaginez combien de personnes on pourrait loger là-dedans ? »_ ,

shortened by removing some letters to see how wrap happens around quotations marks, exclamation mark and colon : [test_nbsp_wrap.html.txt](https://github.com/koreader/koreader/files/949909/test_nbsp_wrap.html.txt) . One can check with various font sizes (most noticeable with bigger fonts).

Related code where the decision is made (and that we could tweak):
https://github.com/koreader/crengine/blob/master/crengine/src/lvfntman.cpp#L703-L710
https://github.com/koreader/crengine/blob/master/crengine/src/lvtextfm.cpp#L1093-L1096
https://github.com/koreader/crengine/blob/master/crengine/src/lvtextfm.cpp#L1108-L1114

From what I get:
- hyphens and NBSP are considered "deprecated wrapable" (_line break after this char is possible but deprecated_)
- when processing lines, 2 widths are calculated : a normalWrapWidth one (using only space, and may be hyphenation dictionaries) - and a deprecatedWrapWidth (using spaces, and hyphens and NBSP).
- a decision is made about which one to use:
`if ( deprecatedWrapWidth>normalWrapWidth && unusedPercent>3 ) {lastNormalWrap = lastDeprecatedWrap;}`
If the normal width < 97% of line width (too much space to add to spaces to fill 100% width I guess), the deprecatedWrapWdith will be used.

We have a few options:

a) remove the LCHAR_DEPRECATED_WRAP_AFTER in:  `(ch==UNICODE_NO_BREAK_SPACE?LCHAR_DEPRECATED_WRAP_AFTER|LCHAR_IS_SPACE`
(the LCHAR_IS_SPACE is not used in this part of the code, so no worry, NBSP is not considered a space).
With that, NBSP is never considered for wrap, and we get really nice french typography.
(Should non-breakable spaces really be breakable in case of emergency ? :)
But it's a bit messy for lines with no space at all (1st line in my test file), dunno if we can ignore this extreme case, of if that can happen in real documents.

b) keep LCHAR_DEPRECATED_WRAP_AFTER for NBSP, but increase the condition for using deprecatedWrapWidth from 3% to 50% : less chance for deprecatedWrapWidth to be used with casual text, and it would still be used for no-space-at-all lines (so my 1st test line looks fine and justified).
Side effect: existing hyphens are less easily used for wrapping, and it may feel less clean (see the ending `là-dedans` in my test file: we would get a wrap before or after, or a wrap at `là-de↵dans` (from hyphenation dict) - but never the natural `là-↵dedans`).

c) like a), but calculate a third width: nbspWidth, and use it at last resort (more complex coding, not sure I could code that right).

Any thoughts ?

**Comment by Frenzie** [comment]
I think the most sensible emergency-wrap procedure is to just break at the end of the line. In principle non-breaking spaces are probably a touch more breakable, but I doubt it's worth the effort.

**Comment by poire-z** [comment]
What do you mean with _a+_ ? (But good if you go with a), it's the easiest).

With a), NBSP becomes like all other chars (including the other non-breaking spaces you mention, and including all the punctuation characters from the global punctuation range): only space (and hyphens) will be used for wrapping. So nothing special to add or do about these other non-breaking space characters.

About _just break at the end of the line_ , not sure what you mean: end of the html line ? or end of the displayed line, which have to be computed and decided. With a), my long no-space-at-all line is splitted and wrapped (not sure how, looking at the code), but there's no text justification at all (no space added to spaces so text is not justified, which is a bit ugly - but ok, not worth the effort).

**Comment by Frenzie** [comment]
I mean that the displayed line probably shouldn't overflow, but breaking on nbsp cannot be a solution to that. It could be a slightly more elegant solution in what I can only imagine would be fairly rare circumstances.

> but there's no text justification at all 

Doesn't sound that horrible. :P

**Comment by houqp** [comment]
I think going with a) makes the most sense in that we are respecting the document producer's intent. They put NBSP there to tell the rendering engine not the wrap a line.

We can think about the force line wrap heuristics later when we run into a real world extreme case like you demonstrated in the test file. Mostly likely, the document owner should fix the document instead.

**Comment by poire-z** [comment]
Done in https://github.com/koreader/crengine/issues/70.
Ready for bumps !

**Comment by poire-z** [comment]
Thanks.
Not sure I should bump base in koreader, we're 3 commit behinds. That would include:
_framebuffer_linux(fix): compare pointer properly in mmap assert_
and _add documentation for framebuffer_linux.lua_
Should I ?

**Comment by Frenzie** [comment]
Of course! :-) But it's probably helpful to also mention it in the PR commit message.
