### ISSUE TITLE
No new builds in OTA servers for the last 4 days.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2813]
* KOReader version: N/A
* Device: N/A

#### Issue
There have not been a new nightly build since 4 days ago. And the last build available through OTA had serious bugs.
Any special reason for this? We are missing the last 14 merged commits.

**Comment by Frenzie** [comment]
There's a minor issue of sorts, but I'd say it's not quit what you think. ;-)

![screenshot_2017-04-25_17-04-21](https://cloud.githubusercontent.com/assets/202757/25392675/915a751c-29d9-11e7-897f-780e0d752be5.png)

The sorting is just a bit different than I imagine you would expect.

**Comment by retrue** [comment]
I'll close this.
It is too embarrasing to leave it open  ^^;
