### ISSUE TITLE
dictionary doesn't work

### ISSUE THREAD

**Issue by helmus** [koreader/koreader#2816]
* KOReader version: v2017.03.08-nightly
* Device: Kobo Aura one

#### Issue 

Dictionary isn't showing any definitions for english words in pdf document, wikipedia searches do work.

#### Steps to reproduce
image: 

![dict](https://cloud.githubusercontent.com/assets/1042463/25416366/46302050-29f2-11e7-9e40-12f2ac8e4653.jpg)

**Comment by KenMaltby** [comment]
Which dictionaries have you added to the /data/dict folder?  

OT; I wish there were a standard way to identify the version, ( I would vote for v2015.11-123, not a release date.)

Another OT; for Kobos, at least, we should ask for the Kobo firmware version.

**Comment by Frenzie** [comment]
Dictionary support is explained in the wiki: https://github.com/koreader/koreader/wiki/Dictionary-support

> OT; I wish there were a standard way to identify the version, ( I would vote for v2015.11-123, not a release date.)

But there is? If you ask for the version you get "v2015.11-894-gd168db9".

Actually the part behind that (d168db9) is the easiest for us to work with, the v2015.11-894 just helping to identify at a glance what it's talking about.

When you know full version strings like v2015.11-894-gd168db9 and v2015.11-1006-g6f037ce you can easily dissect changes like so: d168db9...6f037ce

**Comment by helmus** [comment]
That fixed it, sorry should have read the wike first !
