### ISSUE TITLE
Scroll mode: Scroll half screen length of pdf/djvu

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#2818]
* KOReader version:
* Device:

#### Issue
This is an enhancement suggestion

When reading, I usually refer to a few sentences backwards too. For this style of reading, it's very good to scroll by half screen length instead of full. I realise this cannot work on epub and other text files, but those are always easier browsable anyway.

So the suggestion is: When doing Next/Previous in Scroll mode, the page should scroll half screen width. 
A toggleable option of course.

**Comment by Frenzie** [comment]
You could try setting `DOVERLAPPIXELS` in defaults.persistent.lua:

https://github.com/koreader/koreader/blob/8813f0f32dfda3042cd05f03a402b077956c3ae7/defaults.lua#L59

The default of `30` is actually scaled by DPI and tends to come to about one to two lines of text. It sounds like you're looking for something in between `100` and `300`.

**Comment by ersi-dnd** [comment]
> It sounds like you're looking for something in between 100 and 300.

For a Pocketbook Inkpad with 8" screen, it's rather 450. But yes, that's the setting. Solved. Thanks :)
