### ISSUE TITLE
Koreader can't work with fmon after the first time

### ISSUE THREAD

**Issue by liyiecho** [koreader/koreader#2823]
* KOReader version: v2015.11-1013-g495accf
* Device: kobo aura one

#### Issue

I use OTA update to v2015.11-1013-g495accf, koreader can't work after the first time. I found that after I open the koreader.png, koreader didn't get respond. 
Restart or manually install, this problem still exists.

**Comment by Frenzie** [comment]
What exactly do you mean by didn't respond?

**Comment by liyiecho** [comment]
@Frenzie  open the picture didn't call koreader.sh in the folder of koreader.

**Comment by liyiecho** [comment]
@Frenzie I use koreader.sh from v2015.11-1006-g6f037ce to replace it,  now koreader can work well.

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/compare/6f037ce...495accf

Do you have a crash.log?

**Comment by liyiecho** [comment]
@Frenzie open the picture didn't call koreader.sh, so it didn't generate a crash.log.

**Comment by Frenzie** [comment]
The only thing potentially relevant I see is 1850ebca0d81a6c0475c6759fd4ad83da9fcc843 and that shouldn't affect koreader.sh being called. Weird. :/

**Comment by liyiecho** [comment]
Update to v2015.11-1023-g773e24f, it works well. It is so weird. :)

**Comment by Frenzie** [comment]
I'll close it then. :-)
