### ISSUE TITLE
I cannot update via OTA 

### ISSUE THREAD

**Issue by oldhasbeen** [koreader/koreader#2829]
* KOReader version:
* Device: 

#### Issue
I cannot update via Wi-Fi (connection is there and new updates are indicated)
Cannot see newer updates on the rocks nightly download site. Last is 21/04/2016
Is the problem on my side?

**Comment by Frenzie** [comment]
Could you indicate the device and version?

https://github.com/koreader/koreader/issues/2813#issuecomment-297060758

**Comment by oldhasbeen** [comment]
Device is 
Kobo Aura H2O

Koreader version is
 v2015.11-994-ga1ec64b

website is 
http://build.koreader.rocks/download/nightly/ 

with last entry
v2015.11-995-gd6c81f5/                             21-Apr-2017 07:02

**Comment by Frenzie** [comment]
The OTA update was slightly broken for a few versions, although I thought it only resulted in a slow start. https://github.com/koreader/koreader/commit/870c4d38591046f79401620356ab22eb243954d5

If the existing update file doesn't get overwritten in those versions then you could either delete the update file in the OTA directory and try again from the GUI or overwrite your KOReader with a more recent nightly.

**Comment by oldhasbeen** [comment]
Thanks, I normally never update via OTA to avoid any potential conflicts. I always copy the entire koreader nightly and make my personal mods (settings, icons etc) afterwards.
Issue can be closed from my side.

**Comment by Frenzie** [comment]
Alright. :)
