### ISSUE TITLE
messy code in CHM

### ISSUE THREAD

**Issue by stevenzhgl** [koreader/koreader#2834]
* KOReader version: lasted verison
* Device:Kobo Aura One

#### Issue

Read CHM for Chinese e-book display messy code.

**Comment by houqp** [comment]
yeah, don't read in chm format, better convert to epub or even pdf and use the reflow feature. chm format support is not well maintained.

**Comment by Frenzie** [comment]
I'll close this. Sorry for the inconvenience. You could convert it using, e.g., calibre. :-)
