### ISSUE TITLE
onPageUpdate methods run twice on book open

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#2836]
* KOReader version:all
* Device:all

#### Issue
`onPageUpdate()` methods runs twice on book open. It should run only one.

#### Steps to reproduce
Open new document in format epub or doc. For new and previously opened books.
I think that that line https://github.com/koreader/koreader/blame/master/frontend/apps/reader/modules/readerrolling.lua#L450 may be redundant for new books.
That line https://github.com/koreader/koreader/blame/master/frontend/apps/reader/modules/readerrolling.lua#L467 may be redundant for previously opened books.

I think that `self:_gotoXPointer(self.xpointer)` shouldn't be run when opening documents.

**Comment by z3t0** [comment]
@robert00s hey I am new to the koreader ecosystem and trying to learn how to get into the development. Just for my learning, how did you know that onPageUpdate() was run twice? Was there a debugger/ log somewhere or are you just inspecting the source code.

Thanks!

**Comment by robert00s** [comment]
@z3t0 
I develop #2378 (statistics plugin v2 design) and I notice that `ReaderStatistics:onPageUpdate(pageno)` https://github.com/koreader/koreader/blob/master/plugins/statistics.koplugin/main.lua#L568 method is run twice on document startup.
The simplest way is to add to the function:
`DEBUG("*******onPageUpdate method**********")`
or 
`logger.dbg("*******onPageUpdate method**********")` 
run KOReader emulator:
`./kodev run` 
test KOReader and review console for `*******onPageUpdate method**********` string 

Helpful links:
[link1](http://koreader.rocks/doc/modules/logger.html)
[link2](https://github.com/koreader/koreader/wiki#hackers)

**Comment by houqp** [comment]
Yeah, I have noticed similar stuff too. Feel free to submit a patch to fix this behavior. `self:_gotoXPointer(self.xpointer)` should only be called once after the document is fully loaded by crengine.
