### ISSUE TITLE
LDoc Generation

### ISSUE THREAD

**Issue by z3t0** [koreader/koreader#2839]
Would it be valuable to add a document generator? I am new to the project and although the overview documentation is really good it might be useful to have more documentation for the code itself?

Let me know if I sound crazy or anything. If there is interest I would be able to integrate LDocs and lead the task to write the documentation

**Comment by Frenzie** [comment]
Ahem ;-) http://koreader.rocks/doc/

Feel free to submit PRs with improvements, of course!

**Comment by z3t0** [comment]
@Frenzie didn't see that! I was looking at the docs folder and thought that was it...

**Comment by houqp** [comment]
Thanks @z3t0 ! The doc we have right now is actually far from what I want it to be :P So still a lot of work to be done on improving it.
