### ISSUE TITLE
CSS percentage based width for <hr/> is ignored

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2842]
* KOReader version: v2015.11-1024-g3b813c7
* Device: Emulator

#### Issue

`<hr/>` gets rendered at 100%, percent based width is ignored

CSS:
```
hr {
  border-top: 0.15em solid;
  margin-bottom: 0.5em;
  margin-left: 0;
  margin-top: 0.5em;
  width: 30%;
}
```
ADE/iBooks/Calibre/Sigil behave as expected.

#### Steps to reproduce
[untitled.epub.zip](https://github.com/koreader/koreader/files/971903/untitled.epub.zip)

**Comment by a-kohout** [comment]
This works in ADE/iBooks/Calibre/Sigil **_and_** koreader:
```
hr {
  border-top: 0.15em solid;
  margin-bottom: 0.5em;
  margin-left: 33%;
  margin-right: 33%;
  margin-top: 0.5em;
}
```

**Comment by Frenzie** [comment]
I can reproduce the issue, but it's not quite that width is not supported or some such. If I just stick it in an HTML file:

```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <style>hr {
  border-top: 0.15em solid;
  margin-bottom: 0.5em;
  margin-left: 0;
  margin-top: 0.5em;
  width: 30%;
}</style>
</head>

<body>
<hr style="width:10%"/>
<hr style="width:20%"/>
<hr/>
<hr style="width:40%"/>
<hr style="width:50%"/>
<hr style="width:60%"/>
<hr style="width:70%"/>
<hr style="width:80%"/>
<hr style="width:90%"/>
<hr style="width:100%"/>
</body>
</html>
```

![screenshot_2018-03-24_16-05-08](https://user-images.githubusercontent.com/202757/37865465-2601d724-2f7d-11e8-83ea-f15c9296b175.png)

But the EPUB does behave that way, even without external styles.

**Comment by poire-z** [comment]
Mhhh, if I just stick your HTML in a **.html** file, I only get 100% width'ed lines...
(I thought that with that, and the other segfault you can't reproduce, we were not really working on the same koreader project :)

But if you open this `.html` with MuPDF engine, or name it **.xhtml** (like your screenshot may indicate you did), they are displayed as on your screenshot :)

**Comment by Frenzie** [comment]
Ahem, I bound *X*HTML to MuPDF by default myself. /whistles The program didn't open this self-evident extension previously at all.

Yes, by an HTML file I implicitly meant .xhtml, particularly in this case where I simply extracted the file from the EPUB for easier testing and thought nothing of it.

I'm not sure if that's a clever easter egg or just annoyingly confusing.

**Comment by poire-z** [comment]
I personally don't mind the current behaviour. I always use/see files with `.html`  (and I would probably nearly inconsciously rename a `.xhtml` to `.html` :) - knowing that if I rename it .xhtml, it will open with MuPDF is kind of a feature. But _who knows_ :)
Dunno what's the right thing to do.
