### ISSUE TITLE
Adjacent sibling CSS selectors are not supported

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2845]
* KOReader version: v2015.11-1024-g3b813c7
* Device: Emulator

#### Issue

Adjacent sibling CSS selectors are not supported, e.g. `p+ol` (`<ol>` immediately after `<p>`), `p~ol` (`<ol>` immediately before `<p>`)

ADE doesn't support them either.
iBooks/Calibre/Sigil behave as expected.

**Comment by poire-z** [comment]
Should have been fixed in https://github.com/koreader/crengine/pull/178, available in current nightlys.
