### ISSUE TITLE
CSS: table: border-width: 0 is ignored

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2847]
* KOReader version: v2015.11-1024-g3b813c7
* Device: Emulator

#### Issue
border-width: 0 is ignored, a border with default width gets drawn.
Specifying border-style: none works

Koreader:
![screen shot 2017-05-03 at 01 24 33](https://cloud.githubusercontent.com/assets/26367956/25643403/e49bc958-2f9f-11e7-949e-2013c108284c.png)

Expected:
![screen shot 2017-05-03 at 01 24 39](https://cloud.githubusercontent.com/assets/26367956/25643407/e8e7f4aa-2f9f-11e7-892e-458e0068fc06.png)

CSS:
```
table {
  border-spacing: .25em;
  margin-bottom: 1em;
  margin-top: 1em;
  page-break-inside: avoid;
  width: 100%;
}

td.line {
  border-style: dashed;
  border-width: 1px 0 0 0;
}
```

Workaround:
CSS:
```
  border-style: dashed none none;
  border-width: 1px;
```

HTML:
```
  <table>
    <tbody>
      <tr>
        <td>
          B
        </td>
      </tr>

      <tr>
        <td class="line">
          B
        </td>
      </tr>
    </tbody>
  </table>
```
ADE/iBooks/Calibre/Sigil behave as expected

#### Steps to reproduce
[untitled.epub.zip](https://github.com/koreader/koreader/files/972201/untitled.epub.zip)

**Comment by Frenzie** [comment]
From a quick peek, I assume a little something called DrawBorder bears at least some responsibility.

https://github.com/koreader/crengine/blob/052637f1f4ca831fd03aafab89df8358d8ca0f49/crengine/src/lvrend.cpp#L1865-L1871

**Comment by poire-z** [comment]
Should be fixed by https://github.com/koreader/crengine/pull/198, available in current nightly.
