### ISSUE TITLE
Discussion: Calibre companion does not needs its own set of "menus"

### ISSUE THREAD

**Issue by z3t0** [koreader/koreader#2850]
* KOReader version:
* Device:

#### Issue

![](https://i.imgur.com/JQrhDID.png)
![](https://i.imgur.com/A68oAAx.png)

Calibre does not need its own "menu" layout? Unless other features are planned for Calibre we might as well make it one button that is "Connect to calibre" or "Disconnect from Calibre"

Thoughts?

**Comment by houqp** [comment]
I totally agree with you. Feel free to submit a patch for it.

**Comment by z3t0** [comment]
This is obsolete because #2851 does have more menu options
