### ISSUE TITLE
Not able to load dynamic library: libs/libmupdf.so

### ISSUE THREAD

**Issue by skygragon** [koreader/koreader#2853]
* KOReader version: koreader-android-arm-linux-androideabi-v2015.11-1023-g773e24f.apk
* Device: android 4.0 boox i86HD

#### Issue

crash on start

log:

I/KOReader( 2895): ffi.load libs/libmupdf.so
E/luajit-launcher( 2895): Failed to run script: setupkoenv.lua:27: Not able to load dynamic library: libs/libmupdf.so

**Comment by Germanc** [comment]
I have the same issue on a Onyx C67ML, running android 4.2.

**Comment by ersi-dnd** [comment]
The current nightly does not work on Samsung Galaxy Note 4 either (black screen on startup, does not react to anything), while the latest stable worked fine.

**Comment by skygragon** [comment]
any update yet? ......

**Comment by chrox** [comment]
Might be related to koreader/koreader-base#482.

**Comment by skygragon** [comment]
Any plan on this? The latest release seems not fix it...

**Comment by Frenzie** [comment]
By latest release do you mean v2015.11-1054-g6870bc2 (https://github.com/koreader/koreader/releases/tag/v2017.06.12-nightly)? Because actually I merely forgot to close this issue after merging #2946 and #2948 (as there were a bunch of duplicates).

**Comment by Frenzie** [comment]
Closing this now. :)

**Comment by skygragon** [comment]
Just tried koreader-nightly-20170612 build, but the same error still occurred... Anything I need to provide to help investigation?

```
I/KOReader( 3506): command stdout:
I/KOReader( 3506): command stderr:
I/KOReader( 3506): command res:0
I/KOReader( 3506): run command chmod 755 ./tar
I/KOReader( 3506): command stdout:
I/KOReader( 3506): command stderr:
I/KOReader( 3506): command res:0
I/KOReader( 3506): run command chmod 755 ./zsync
I/KOReader( 3506): command stdout:
I/KOReader( 3506): command stderr:
I/KOReader( 3506): command res:0
I/KOReader( 3506): try to load module libs/libkoreader-lfs.so
I/KOReader( 3506): external storage /mnt/sdcard
I/KOReader( 3506): ffi.load SDL2
I/KOReader( 3506): ffi.load SDL
I/imx6.gralloc( 1987): Display Request: 696 (0, 0) - (1600, 1200)  mode = 0x5 flags = 0x0
I/imx6.gralloc( 1987): Display Request: 697 (0, 0) - (1600, 1200)  mode = 0x5 flags = 0x0
I/KOReader( 3506): INFO  initializing for device Android
I/KOReader( 3506): INFO  framebuffer resolution: {
I/KOReader( 3506):     ["h"] = 1525,
I/KOReader( 3506):     ["w"] = 1200
I/KOReader( 3506): }
I/KOReader( 3506): ffi.load libs/libmupdf.so
E/luajit-launcher( 3506): Failed to run script: setupkoenv.lua:27: Not able to load dynamic library: libs/libmupdf.so
I/SurfaceFlinger( 1987): CAPTURE_SCREEN invoked 7
V/threaded_app( 3506): Pause: 0x19b3898
V/threaded_app( 3506): android_app_destroy!
W/WindowManager( 2109): Failure taking screenshot for (359x456) to layer 21020
```
