### ISSUE TITLE
FR: Show time on bar

### ISSUE THREAD

**Issue by z3t0** [koreader/koreader#2862]
It would be a good feature to show the time. 

I will implement this once I get a chance.

Posting here for any ideas or suggestions.

**Comment by KenMaltby** [comment]
You are aware that the time can be one of the "Mini-bar" items?  Also that the time is in the lower right corner of the main dropdown menu.

**Comment by Frenzie** [comment]
Closing now because what @KenMaltby wrote is correct.

**Comment by z3t0** [comment]
>  Also that the time is in the lower right corner of the main dropdown menu.
I saw this but found it less helpful as you would have to pull down the menu.

> You are aware that the time can be one of the "Mini-bar" items? 

Sorry had no idea about that, I'll check thank
