### ISSUE TITLE
FR: KeyValuePage navigation buttons

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#2863]
* KOReader version: up to  394be8a  
* Device: all

#### Issue
You can only swipe left and right, which is inconsistent with other similar widgets that have arrows at the bottom for turning pages (e.g., filemanager, history, OPDS).

Also see https://www.mobileread.com/forums/showpost.php?p=3516659&postcount=1

**Comment by Hzj-jie** [comment]
+1
