### ISSUE TITLE
Kobo wifi: An error occurred while setting password

### ISSUE THREAD

**Issue by protist** [koreader/koreader#2864]
* KOReader version: koreader-nightly-20170430
* Device: Kobo H2O

#### Issue
I attempted to connect to my Wi-Fi network. I selected my network, entered the password, then was presented with: `An error occurred while setting password.`
(I could find any recently-modified files, where a log might have been made.)

After this failed, I exited the screen, then tried to connect again with "gear icon" > `Wi-Fi connection`. I was presented with `Do you want to turn on Wi-Fi?`, to which I said yes. I re-selected my network and got the same error `An error occurred while setting password.`.

There was no obvious way to turn off Wi-Fi from koreader. Since I was asked if I wanted to `turn on` Wi-Fi as above, I presumed that meant it was off already. However, when I quit koreader, Kobo Start Menu said `Info: Wifi is enabled!`.

#### Steps to reproduce
Attempt to connect to the Wifi.

**Comment by houqp** [comment]
When this failed, the wifi is indeed still on but no connected to any network. We should fix this.

Are you running the latest kobo firmware? Do you have usbnet access to your device to help debug this issue?

**Comment by protist** [comment]
What do you mean by Kobo firmware? The Kobo Start Menu? If so, yes, I'm running the latest 08. Or do I misunderstand. Are you talking about the official Kobo firmware? Does that only apply to Nickel?

I'm not 100% what you mean by USBNet either, but in Kobo Start Menu, I can go `usb` > `usbnet toggle.sh` and the display says `USBNet support: enabled`. I'm not sure what to do on the connected computer, as the Kobo Start Menu [thread](https://www.mobileread.com/forums/showthread.php?t=266821) only talks about Windows, and I'm on Linux.

**Comment by houqp** [comment]
By kobo firmware, i mean the official kobo firmware, you can update it in nickel. They updated wpa_supplicant in the latest version of the firmware and we updated the wifi manager to adjust for that. Although I am under the impression that the current wifi manager will still work for the old firmware, it's worth giving the new kobo firmware a try.

If you are under linux, after enabling the usbnet, you can do `ifconfig usb0 192.168.2.100`, then `ssh root@192.168.2.101` to login to the device assuming you have dropbear installed from https://www.mobileread.com/forums/showthread.php?t=201632. Password is `banana`.

**Comment by protist** [comment]
Phew, that was more complicated than it should have been! I opened nickel and updated. Presumably I should have selected "partial update" instead of "full update", which appeared to wipe my Kobo Start Menu. I then had issues with Nickel crashing, which I'm not really interested in fixing because I use koreader! 😁 Anyway, I then re-installed Kobo Start Menu fine.

I then installed vlasovsoftlauncher as you mention. I can now open usbnet from within this (is that what you meant, as opposed to usbnet from kobo start menu?). On Arch Linux, the command is `sudo ifconfig enp0s29u1u2 192.168.2.100`, but that worked fine. I can ssh in fine, but I'm not sure what to do next now. Is there some kind of log file that I'm looking for?

**Comment by houqp** [comment]
> Presumably I should have selected "partial update" instead of "full update"

Full update is the correct choice here actually :D Every time you do a kobo firmware upgrade, you will need to reinstall KSM.

Cool now that you have ssh access, let's test out the wpa_supplicant there. Try run the following command in you ssh shell:

```bash
wap_cli   # this will drop you into a shell for wpa_supplicant
add_network  # this will return a network ID, likely 1
set_network NETWORK_ID ssid YOUR_WIFI_SSID
# the following step is the one that caused the error you are seeing
# it would be helpful if you paste the output of this step here
set_network NETWORK_ID psk YOUR_WIFI_PASSWORD
```

For the last step, you can try raw password, and if it's not working that means you have the newer version of the firmware, then you will have to use an encoded version of your password. You can obtained the encoded version by running the following command:

```bash
wap_passphrase YOUR_WIFI_SSID YOUR_WIFI_PASSWORD
```

KOReader right now always use the encoded version of the password for the last step. The function that does the above operations can be found at: https://github.com/koreader/koreader/blob/master/frontend/ui/network/wpa_supplicant.lua#L54. You can edit it to play around with it ;)

**Comment by protist** [comment]
> Full update is the correct choice here actually :D Every time you do a kobo firmware upgrade, you will need to reinstall KSM.

Ah thanks. So I then installed vlasovsoftlauncher with partial update. Presumably that's okay, since it works?

So I'm using UsbNet from vlasovsoftlauncher. (And FWIW it's `wpa_cli`, not `wap_cli` 😬).

```
[root@(none) ~]# wpa_cli 
wpa_cli v2.6-devel-hostap_2_5-1514-g49f6231+
Copyright (c) 2004-2016, Jouni Malinen <j@w1.fi> and contributors

This software may be distributed under the terms of the BSD license.
See README for more details.



Interactive mode

Could not connect to wpa_supplicant: (nil) - re-trying
```
So I restarted, went into koreader, turned on wifi, then opened vlasovsoftlauncher then USBNet.
```
[root@(none) ~]# wpa_cli
wpa_cli v2.6-devel-hostap_2_5-1514-g49f6231+
Copyright (c) 2004-2016, Jouni Malinen <j@w1.fi> and contributors

This software may be distributed under the terms of the BSD license.
See README for more details.


Selected interface 'eth0'

Interactive mode

> add_network
0
> set_network 0 ssid <MY_SSID_HERE>
FAIL
```

**Comment by houqp** [comment]
My bad, the command should be:

```bash
wap_cli   # this will drop you into a shell for wpa_supplicant
add_network  # this will return a network ID, likely 1
set_network NETWORK_ID ssid "YOUR_WIFI_SSID"  # notice the quote here
# the following step is the one that caused the error you are seeing
# it would be helpful if you paste the output of this step here
set_network NETWORK_ID psk "YOUR_WIFI_PASSWORD"
```

If you are using raw password, the quote is also needed for the set psk command. If you are using the encoded version, then you don't need to quote the encoded password.

**Comment by protist** [comment]
No worries, that worked now.
```
> add_network
2
> set_network 2 ssid "<MY_SSID_HERE>"
OK
> set_network NETWORK_ID psk "<MY_PASSWORD_HERE>"
OK
```
So does that mean that I'm using the older version of the firmware? I definitely updated to nickel 4.something.

**Comment by houqp** [comment]
> To clarify, <MY_PASSWORD_HERE> was just the raw password.

Yes, this is the expected input.

At least your wpa_supplicant is different from the one in my latest kobo firmware :P

Can you help me do a quick test by using the encoded password approach and see what you get? When I update the wifi manager, I was under the assumption that encoded password will work for all firmware versions. Make sure you don't have the quotes when using encoded password:

```bash
set_network NETWORK_ID psk ENCODED_PASSWORD
```

**Comment by protist** [comment]
> At least your wpa_supplicant is different from the one in my latest kobo firmware :P

But I've updated to the latest nickel, so shouldn't we be on the same firmware?

> Can you help me do a quick test by using the encoded password approach and see what you get?

I'm not 100% that I'm doing it right, so I'll write out the full commands and output.
* Reboot Kobo
* Turn on Wi-Fi through koreader
* Exit and launch `vlasovsoftlauncher` > `UsbNet`
* From the connected computer:
```
$ sudo ifconfig enp0s29u1u2 192.168.2.100
$ ssh root@192.168.2.101
root@192.168.2.101's password: 
[4400] May 09 10:07:34 lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
[4400] May 09 10:07:34 lastlog_openseek: /var/log/lastlog is not a file or directory!
[root@(none) ~]# wpa_cli
wpa_cli v2.6-devel-hostap_2_5-1514-g49f6231+
Copyright (c) 2004-2016, Jouni Malinen <j@w1.fi> and contributors

This software may be distributed under the terms of the BSD license.
See README for more details.


Selected interface 'eth0'

Interactive mode

> add_network
0
> set_network 0 ssid "<MY_SSID>"
OK
> set_network 0 psk "<MY_PASSWORD>"
OK
> quit
[root@(none) ~]# wpa_passphrase "<MY_SSID>" "<MY_PASSWORD>"
network={
	ssid="<MY_SSID>"
	#psk="<MY_PASSWORD>"
	psk=<LONG_HEX_NUMBER>
}
[root@(none) ~]# wpa_cli
wpa_cli v2.6-devel-hostap_2_5-1514-g49f6231+
Copyright (c) 2004-2016, Jouni Malinen <j@w1.fi> and contributors

This software may be distributed under the terms of the BSD license.
See README for more details.


Selected interface 'eth0'

Interactive mode

> add_network
1
> set_network 1 ssid "<MY_SSID>"
OK
> set_network 1 psk <LONG_HEX_NUMBER>
OK
```

**Comment by houqp** [comment]
Ha, I think I know why, try change this line https://github.com/koreader/koreader/blob/master/frontend/ui/network/wpa_supplicant.lua#L48 to:

```lua
local fp = io.popen(string.format("wpa_passphrase \"%s\" \"%s\"", ssid, pwd))
```

**Comment by protist** [comment]
Damn escapes! 😬 Yes! That works perfectly! Thank you!

As an aside, it'd be great to have a "show password" option too, especially as the keyboard isn't the easiest to navigate. I'm happy to open up a new issue if you like?

**Comment by houqp** [comment]
Yes, please file that as a separate feature request. I have submitted a PR for the fix: https://github.com/koreader/koreader/pull/2880.

**Comment by protist** [comment]
Thank you. Just to check, that PR didn't include the problem with turning Wi-Fi off, right?

> When this failed, the wifi is indeed still on but no connected to any network. We should fix this.

**Comment by houqp** [comment]
Oh yeah, that's not fixed.

**Comment by Frenzie** [comment]
@houqp Your comment about KSM full vs partial generated some response.

https://www.mobileread.com/forums/showthread.php?p=3518685#post3518685
> So let me repeat here that the recommended way is to choose "partial update." For this will preserve the installed KSM. Preserving KSM when upgrading the firmware is the main reason for having the "partial update" option

**Comment by houqp** [comment]
Oops, my bad, I will update my comment. Thanks for relaying the message :D

**Comment by mergen3107** [comment]
Is this issue not outdated?

**Comment by Frenzie** [comment]
The main issue (about setting a password) should be fixed, but I'm not completely sure about the secondary issue regarding turning off wifi.

I'll close it, but please feel free to reopen or post a new issue with more info.
