### ISSUE TITLE
Kindle password ignored

### ISSUE THREAD

**Issue by z3t0** [koreader/koreader#2865]
* KOReader version: latest nightly
* Device: kt3

#### Issue

This is a very serious issue for me at least as I like to be able to restrict access to my devices. Koreader prevents kindles lock screen password from working 
#### Steps to reproduce
1. Go to settings and add a pin 
2. Lock the screen and enter pin to unlock 
3. Open koreader 
4. The pin is not needed to unlock

**Comment by Frenzie** [comment]
Partial duplicate of #1606. 

@robert00s Would you happen to know if there is any way in which KOReader could cooperate with this Kindle lock screen functionality?

**Comment by robert00s** [comment]
@Frenzie I'll check it in a few days. Now I working on "statistics plugin v2".

**Comment by NiLuJe** [comment]
AFAICT, no, there's no easy way to do that. It inhibits events we need, the specific events we'd need to react to if we wanted to temporarily re-enable passcodes.

It's a mess, and the best we could do was disabling passcodes *while KOReader is up*. It should be silently resotred when we exit.

**Comment by melyux** [comment]
Any news on this bad boy?

**Comment by Frenzie** [comment]
It's kind of the same thing as #5970, which was closed as out of scope.

**Comment by NiLuJe** [comment]
Except it's even gnarlier on Kindle, so, way not going to happen.

**Comment by Frenzie** [comment]
I'll close it as wontfix then, because I don't know who else would even look at it. ;-)
