### ISSUE TITLE
No batterystat.log

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2867]
* KOReader version: v2015.11-1023-g773e24f
* Device: Kobo Glo

#### Issue
Just a question.
Where is the batterystat.log saved (if it exists at all) that's mentioned at the end of the Battery Statistics plugin?
Is there a way to enable it?

#### Steps to reproduce
Search in the koreader directory (where is supposed to be)

**Comment by Frenzie** [comment]
The file exists for me in /mnt/onboard/.adds/koreader/batterystat.log but it's possible that the one on my device hasn't been updated for a while.

**Comment by embryo10** [comment]
Can you check if it will be created if its not there?

**Comment by Hzj-jie** [comment]
Some known issues cause the battery stat plugin not able to receive some signals. They should be fixed by change https://github.com/koreader/koreader/pull/2772.

**Comment by Frenzie** [comment]
Closing now due to @Hzj-jie 's comment above.
