### ISSUE TITLE
"Power off" function

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2868]
* KOReader version: v2015.11-1023-g773e24f
* Device: Kobo Glo

#### Issue
From all the observations [of this post](https://www.mobileread.com/forums/showthread.php?p=3516659#post3516659), this is the only one that I can't find a workaround for.

Now that I can not use my "Turn off" button, I have to press the last menu icon>>>then the "Exit" entry>>>wait for koreader to exit>>>and press the "Shut Down" button of KSM to close the reader.
The reason that I don't use Koreader's shut down method is, as I wrote there:
"First is the faster wear of the power button.
 Second is that its really difficult because of the sliding nature of this button at the old Glo model. Its almost impossible to use it with gloves, and even without them, most of the time I miss it the first time.
 Another problem is that when the reader is closed or is sleeping, you see the same cover, with nothing to indicate the different states. You have to guess if you slide it for the right amount of time for it to go to the state that you intended."

So the proposition is to add a "Turn off" entry after the "Exit" one or even better have a way to add a top level button with that functionality.
The reason that I have to shut the reader down and not put it to sleep, is that it still drains the battery in suspend mode.

**Comment by AlanSP1** [comment]
I also think that ability to power off directly from koreader would be very useful. I already suggested it here: https://github.com/koreader/koreader/issues/2588

**Comment by a-kohout** [comment]
@embryo10 You can create a poweroff image and define that in settings.reader.lua (if powering off using long-press) and in ksm (if powering off using ksm).

edit `settings.reader.lua`
```
    ["poweroff_screensaver"] = {
        ["path"] = "/mnt/onboard/.adds/img/powered_off.png"
    },
```

edit `kbmenu_user/txt/poweroff_info.html`:
```
<!DOCTYPE html>
<html>
<head>
<title></title>
<style type="text/css">
body { margin: 0; padding: 0; overflow: hidden; }
</style>
</head>
<body>
<img src="/mnt/onboard/.adds/img/powered_off.png" alt="" width="1072" height="1448"/>
</body>
</html>
```

**Comment by embryo10** [comment]
This is good to know..
I tried to set it up but did not work.
I added this to the |settings.reader.lua|:
     ["poweroff_screensaver"] = {
         ["path"] = "/mnt/onboard/.adds/kbmenu/txt/PowerOff.png"
     },
but nothing changed.
It persisted the restarts but it didn't work.
I already use this image in the KSM7 poweroff_info.html and it's working OK.
Did I misspelled something?

**Comment by a-kohout** [comment]
No, looks good.
Mind that filenames are case sensitive

**Comment by embryo10** [comment]
Well, then is just not working...:-(

**Comment by embryo10** [comment]
... and another weird behavior is that if I suspend the reader and toggle the light button it opens/closes the light as it should, without waking.
Is this normal behavior?

**Comment by a-kohout** [comment]
Weird, works on mine. Although I have `suspend_screensaver` set as well.
Mine doesn't have a light button...
I noticed you are using KSM7. My Glo HD runs KSM08 and update v04e, as well as Kobo Firmware 4.3.9084.

**Comment by embryo10** [comment]
Xmmm..
So, is Koreader tied with Nickel or KSM versions?
I will not update any of them just for that (everything else is working 
OK), but I would like to now who is the culprit...

**Comment by Frenzie** [comment]
If something changed at the kernel level (like it must've for 32-bit) then the "Nickel" version can affect how some things function. However, in this case that would be something like *if* the device suspends. If the screensaver is drawn when suspending it should also be shown when shutting down.

**Comment by embryo10** [comment]
There is a screensaver drawn when shutting down, but its the book cover 
and not the custom one.
The device does Power off.
