### ISSUE TITLE
nightly build 1030 for Kindle

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#2874]
* KOReader version:
* Device:

#### Issue
I can´t find the kindle build of 1030. Is only the Kobo available?

http://build.koreader.rocks/download/nightly/v2015.11-1030-g3541320/

**Comment by AlanSP1** [comment]
It looks strange, if you check time stamps:

v2015.11-1028-g0b47c81/                            08-May-2017 09:09                   -
v2015.11-1030-g3541320/                            08-May-2017 10:06                   -

b1030 is done an hour later. Maybe it changed only something for kobos?

Usually there's only one build per day from what I see and only if there were new PRs.

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/pull/2832#issuecomment-299807538
