### ISSUE TITLE
Bug: Blank(black), unused area at screen bottom in Inkbook Prime; missing launcher(?) top menu

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2876]
* KOReader version: koreader-nightly-20170209
* Device: Inkbook Prime

#### Issue
Blank(black), unused area at screen bottom in Inkbook Prime.

Appears only in Koreader (both file manager and while reading a book).
Doesn't happen in other android Applications e.g. ES File Explorer.

Defect screenshots:
- koreader sample book https://ibb.co/eVXkLk
- Koreader file manager https://ibb.co/k00GRQ

In the same time Launcher (?) top menu  (with buttons "home", "back", "settings", "refresh" etc) is missing. I bet the blank, black area is missing Launcher menu.

Top menu working in other applications:
- web browser https://ibb.co/diauD5
- apps menu https://ibb.co/cRSKfk

**This is a major bug on Inkboonk Prime, as frontlight, wifi on/off etc settings cannot be changed, when koreader is working**

#### Steps to reproduce
Open Koreader on Inkbook Prime.

**Comment by mwoz123** [comment]
Can someone help? Will system log be useful here?

**Comment by gerroon** [comment]
search the issues, there is a fix for that missing spaace. I just do not remember how it was but I used it on my device before.

**Comment by Frenzie** [comment]
Please do. Hopefully we could incorporate it! :)

**Comment by mwoz123** [comment]
@gerroon are you taking about #2077?
Change #2102 should be already in master branch but error still exist :(

I also found #2275 which seems to be the same problem

**Comment by gerroon** [comment]
@mwoz123 yes but there is a koreader setting that you can put in your settings folder that fixes it.

put this in patch.lua in your settings folder, it worked for me back then.

```

local screen = require("android").screen
screen.height = screen.height + 80


```

**Comment by mwoz123** [comment]
@gerroon should it be placed before building APK file in settings folder?  Or can be on android koreader writable directory (of course in settings folder)? 

I created file:
/sdcard/koreader/settings/patch.lua

With context:
`local screen = require("android").screen`
'`screen.height = screen.height + 80`

But I see no changes in koreader :(

**Comment by gerroon** [comment]
I think it is /sdcard/koreader, or whatever the root of Koreader is using for settings

**Comment by mwoz123** [comment]
The `settings` folder was already there, that's why I used it. 

But right `/sdcard/koreader` was better choice. 

Now the black area is gone, but koreader looks like in full-screen mode (there is no system bar). 

@gerroon do you know Is there a way to disable koreader "full-screen" mode? To have both system bar (with i.a. Light control) with koreader visible at once? 
Or this patch just let you use koreader full-screen?

**Comment by mwoz123** [comment]
Maybe something like :
Screen. ofset. top = a value
Could help (if there only was something like that) ?

**Comment by Frenzie** [comment]
I don't know what effect it would have exactly, but you could try something like screen.viewport or self.viewport = `Geom:new{x=0, y=[pixels from top], w=[relevant value], h=[total-pixels from top]},`

**Comment by gerroon** [comment]
@mwoz123 

By settings folder I meant the root of koreader,_ I did not know that there was a settings folder.


I never thought that Koreader worked in non fulscreen mode. I always used it in that fullscreen mode.

**Comment by mwoz123** [comment]
Ok. I can see on my phone that KOReader runs by default in fullscreen mode.
So I created a task #2902 to have option to disable fullscreen mode.

Here let's focus on removing blank area on Inkbooks & Onyx Books (both got software developed by ArtaTech).

WORKAROUND:
create file `/sdcard/koreader/patch.lua` 
with contents:
```local screen = require("android").screen```
```screen.height = screen.height + 80```

Let focus here on changing this workaround to implementation.

Is there a way to discover this device requires such patching?
I currently don't have idea. Any one else?

**Comment by Frenzie** [comment]
In Kobo and Kindle you can see the Lua side of things, but you'd also have to acquire something like [`Build.MODEL`](https://developer.android.com/reference/android/os/Build.html) in some way. You'd have to check the code to see if there's already a simple method there or if it'd require writing some C.

**Comment by mwoz123** [comment]
[Here seems to be a C/C++ pseudo code](https://stackoverflow.com/questions/7183627/retrieve-android-os-build-system-properties-via-purely-native-android-app) for obtaining [android.os.Build.DEVICE](https://developer.android.com/reference/android/os/Build.html#DEVICE) with Android NDK.

Code above should have _interface_ created in `lua-jit-launcher/assets/android.lua` 
similar to already existing:
> int32_t AConfiguration_getDensity(AConfiguration* config);

and probably also in `koreader/frontend/device/android/device.lua` ?

But as I don't know C/C++ (at all) if I'm afraid I won't be able to change this pseudo code to real implementation:(

Could someone help me with that?

**Comment by pazos** [comment]
@mwoz123, @Frenzie, I'm lost here: Do you want to modify /sdcard/koreader/patch.lua to check if the device needs a hacked resolution?. In any case the best option to read android default properties is with `getprop ro.product.name`

**Comment by mwoz123** [comment]
@pazos The goal here is to have in lua code (probably somewhere where android screen size is set) , check if android device is inkbook or onyx boox and if yes then apply logic from gerroon's patch.lua 
So users wouldn't have to do manually apply it.

**Comment by Frenzie** [comment]
@pazos Something along the lines of frontend/device/android/device.lua would be more appropriate. I'm just stating the obvious that you'd need to detect this in some way to take it out of the realm of personalized mods. If there's a more generic method than the product name so much the better; if it needs device detection then so be it.

**Comment by gerroon** [comment]
@mwoz123

Sorry to hijack this thread. Does KOreader work fine on Inkbook prime? DO you get crashes, freezes alot? I am needing a new ereader nowadays.

**Comment by mwoz123** [comment]
@gerroon I think it works quite well (as for Android). It freezes from time to time, but for me it wasn't too often/too much annoying..
I think majority of those freezes were when I wanted to do something very fast (double/clicked on page turn etc), but it's only my teory;)
Normal reading mostly ok.

Page turn buttons - you have to be at least some precise to use it.

I love turn on/off button located at the device revers it's very comfortable (especially if you don't have small fingers to use 2mm2 button located at the bottom of other devices).

Battery could be better I'd played while with previous Inkbook Obsidian and I think it was better there.

**Comment by gerroon** [comment]
@mwoz123

Thanks for your reply, that is good to hear. It seems like a good canditate for Kr. Also did you root it? Is root possible for this device?

**Comment by mwoz123** [comment]
No, I wasn't interested in rooting device. I haven't tied it.

**Comment by Frenzie** [comment]
Is this still an issue after <https://github.com/koreader/android-luajit-launcher/pull/63>?

**Comment by mwoz123** [comment]
Latest nightly version( 1287) works fine without patching,out of the box ;) 

For those who have patch : it should be remove before upgrading to this (or newer) version.
Otherwise bottom bar will be visible only partially.
