### ISSUE TITLE
Progress Sync not working

### ISSUE THREAD

**Issue by dowiew** [koreader/koreader#2877]
* KOReader version: 20170430
* Device: Android, Kindle

#### Issue
The reading progress sync feature/plugin stopped working a few weeks ago.
Apparently the built-in sync server at https://vislab.bjmu.edu.cn:7200 does not respond (no browser/telnet connection as well, at least from Poland).
Will it be fixed? Is there another public custom server I can configure?

#### Steps to reproduce
Progress push/pull request: error msg, that something went wrong.
Logout and then Login or Register attempt: 'Unknown server error'.

**Comment by dowiew** [comment]
The sync server is back online...

**Comment by Frenzie** [comment]
I'll mention #2738 here for potential cross-reference.

**Comment by samidolo** [comment]
Bonjour sauf erreur de ma part il est impossible de s'inscrire

**Comment by Frenzie** [comment]
Are you using a recent version?

**Comment by samidolo** [comment]
Merci pour votre temps.
Oui c'est une version récente 2018/12 de koreader sur une liseuse Kobo
forma installer avec kfmon.
Ceci dit j'ai renouvelé l'opération sûr mon smartphone Android ça n'a pas
mieux marcher.

Le mar. 4 déc. 2018 à 18:05, Frans de Jonge <notifications@github.com> a
écrit :

**Comment by samidolo** [comment]
Bonjour je reviens pour faire une petite à mise à jour j'ai réussi à me
connecter au serveur je pense avoir fait une mauvaise manipulation je vous
remercie de l'attention prêté à mon petit problème.

Le mer. 5 déc. 2018 à 00:40, samuel thivillier <samidolo@gmail.com> a
écrit :

**Comment by Frenzie** [comment]
Pas de problème. Merci pour votre message.
