### ISSUE TITLE
Long pressing inc/decrease displays illogical set default message

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2879]
* KOReader version: v2015.11-1024-g3b813c7
* Device: Emulator

#### Issue
Long pressing on "increase" or "decrease" (Text size fine tuning) pops up message
"Set default Fine Tuning to increase" or "Set default Fine Tuning to decrease".
KOReader does set the current text size to default in `settings.reader.lua`

![screen shot 2017-05-06 at 16 44 37](https://cloud.githubusercontent.com/assets/26367956/25829906/a12b02f6-3459-11e7-9a02-f4f832ce4e76.png)

#### Steps to reproduce
Long press "increase" or "decrease"

**Comment by Frenzie** [comment]
> KOReader does set the current text size to default in settings.reader.lua

So if you press set default it'll go for whatever value the font size is? That does sound like useful functionality, albeit presented in a rather odd manner.

**Comment by a-kohout** [comment]
Yeah, it would have been better to change the text to 'Set default to current font size' instead of getting rid of it.
You can still long-press any of the 'Aa' font size representations and it will ask 'Set default to XX'.
Though you can't set the default to be in between two sizes that way.

**Comment by Frenzie** [comment]
Reopen then?

**Comment by a-kohout** [comment]
I have been mistaken.
It does actually set `increase` as the default size in `settings.reader.lua`.
