### ISSUE TITLE
Option to make password visible when entering

### ISSUE THREAD

**Issue by protist** [koreader/koreader#2882]
* KOReader version: koreader-nightly-20170430
* Device: Kobo H2O

#### Issue
I attempted to connect to a Wi-Fi network. When entering the password, it would be useful to have a "Show Password" option, i.e. one where it's no obfuscated. The keyboard is quite fiddly, so it'd be useful to be able to check passwords before submitting. (Is it just me or does everyone have passwords like this: `Osy2*YF|!'/yi'@sll^86l[$8`?) Many other UIs allow this, e.g. nickel, Android.

#### Steps to reproduce
Attempt to connect to the Wifi. Type in a password. See stars.

**Comment by robert00s** [comment]
@Frenzie:
I think we can close it now.
