### ISSUE TITLE
Wikipedia doesn't work when launched from dictionary lookup in file manager.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2883]
* KOReader version: n/a
* Device: n/a

#### Issue
By itself or together with the option to save wikipedia articles as an epub, it would turn the ereader in an interesting study tool.
When the external dictionary plugin was added there were some comments about adding an external plugin for the Wikipedia too but nothing has been done about that yet.
If it were to be added, it would search by default in the same language of the interface of the device, but an option should be added to search too in other languages, or at least it should use that entry in settings.reader.lua that allow you to define the different languages to use when searching the Wikipedia.

**Comment by houqp** [comment]
@poire-z already implemented all of these features I think :) You can go to the wikipedia tap on the dictionary lookup, the click full article, then you will be able to see the save as epub option.

**Comment by retrue** [comment]
@houqp I have just seen it, thanks.
But it doesn't work. And it even crashes the device. See #2884.
The button in the dictionary lookup window doesn't work.
In any case, after fixing this bug, I would prefer that "Wikipedia search" was an independent option outside dictionary look-up.

**Comment by Frenzie** [comment]
It is though?

Search (looking glass) → Wikipedia lookup

For me it prompts for wifi when I click "Wikipedia" on the dictionary window. I suspect the issue is rather something network-related. Could you check what happens when you do something else that requires the network, such as OTA update? Or **Network info** under **Network settings**?

**Comment by poire-z** [comment]
I can replicate the crash, and a few others (self.view = nil at various places when no ReaderView while in filemanager). No wikipedia lookup from filemanager cause no ReaderWikipedia was imported (so no onLookupWikipedia to catch the event).
I'll fix this in a few hours.

**Comment by Frenzie** [comment]
Ok, thanks!
