### ISSUE TITLE
Crash in Kobo when taking screenshot, it's wikipedia related.

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#2884]
* KOReader version:  v2015.11-1034-gbde2139  and v2015.11-1035-gb33c926  
* Device: Kobo Mini

#### Issue
Crash in this specific situation. Follow steps to reproduce.
I include crash.log with the last crashes.
[crash.log.txt](https://github.com/koreader/koreader/files/996809/crash.log.txt)

#### Steps to reproduce
From KOReader File Browser go to Magnifier > Dictionary lookup
Type a word and tap Search dictionary.
Tap Wikipedia. Nothing will happen. If WiFi was off it won't ask for a connection. If WiFi was on, it will do nothing. That is the first bug.
Try to take a screenshot with a diagonal swipe.
KOReader will crash. That is the second bug.
Note that if you take the screenshot in the dictionary window without pushing the wikipedia button, the screenshot will work and there won't be crash.

**Comment by Frenzie** [comment]
I get this crash even without pressing the Wikipedia button. Just searching for something in the dictionary from the file manager will do.
