### ISSUE TITLE
Is there any detailed doc about build android?

### ISSUE THREAD

**Issue by amendgit** [koreader/koreader#2891]
* KOReader version: master
* Device: -

#### Issue
I want to build koreader from scrach. And I follow the README.md to build koreader for android. I tried to get around it by myself, but trun into failed.

I tried what I can do to complied it for android but failed in last two days. 

1
```
on mac
1 brew install android-ndk
2 set ANDROID_NDK_HOME in .bash_profile
3 set NDK in .bash_profile
4 it failed when build luajit for some compiled errors.
```
2
```
on mac
1 clone the master code 
2 run './kodev build --verbose android'
3 it downalod ndk it self
4 but failed on build
It seems kodev download the linux version android-ndk.
```
3
```
on ubuntu
1 clone the master code
2 run  './kodev build --verbose android'
3 ndk self-setup
4 failed on build luajit for ld errors
it seems luajit used the wrong CC and LD
```
4
```
on ubuntu
0 ln -s toolchain from xxx_gcc to gcc
1 clone the master code
2 run  './kodev build --verbose android'
3 ndk self-setup
4 failed on build luajit for ld errors
it is reporting cannot find crt1.0
```
...

I am aware that I cannot `build android` without extra document. Would anyone mind to provide one? thank you very much. 

#### Steps to reproduce
1 on ubuntu
2 clone the master
3 run './kodev build --verbose android'

**Comment by Frenzie** [comment]
Which version of Ubuntu? Following the README I have no extraordinary trouble building for Android in Ubuntu 16.04, 17.04 or Debian Stretch.

Could it be that you're trying to make things too complicated for yourself? All you need is `sudo apt-get install ant openjdk-8-jdk` and the kodev script will take care of the rest by itself.

**Comment by amendgit** [comment]
Thank you for response and for building koreader.
I am using a DeepinOS 15.04 which is redistribution of Ubuntu 15.04, and with open-8-jdk ant installed,  I just run a fresh building without any extra settings.
here is my .bash_profile
```
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"

alias pc4="proxychains4 -q"
alias px4="ALL_PROXY=http://127.0.0.1:1087"
alias p4="px4 pc4"
```
here is my error log last few lines:
```
make all "LJCORE_O=ljamalg.o"
make[7]: Entering directory `/home/jash/Src/koreader/base/thirdparty/luajit/build/arm-linux-androideabi/luajit-prefix/src/luajit/src'
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_peobj.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
CC        luajit.o
In file included from luajit.c:20:0:
lj_arch.h:515:0: warning: "LUAJIT_NO_LOG2" redefined
 #define LUAJIT_NO_LOG2
 ^
<command-line>:0:0: note: this is the location of the previous definition
HOSTLINK  host/minilua
/usr/bin/ld: cannot find crt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
//usr/lib32/libm.so: error adding symbols: File format not recognized
```
and some usefull info from log
```
Using NDK: /home/jash/Src/koreader/base/toolchain/android-ndk-r12b...
install -d build/arm-linux-androideabi/libs
install -d thirdparty/luajit/build/arm-linux-androideabi
-- Check for working C compiler: /home/jash/.linuxbrew/bin/cc
-- Check for working C compiler: /home/jash/.linuxbrew/bin/cc
-- Check for working CXX compiler: /home/jash/.linuxbrew/bin/c++
-- Check for working CXX compiler: /home/jash/.linuxbrew/bin/c++ -- works
Cloning into 'luajit'...
Note: checking out 'v2.1.0-beta2'.
```
I am not familiar with cross-complier, but should building using the `android_toolchain/bin/arm-linux-androideabi-gcc` and `arm-linux-androideabi-g++`.

**Comment by houqp** [comment]
1. Except for the initial host LUAJIT vm building (HOSTCC) in your posted build log), cross compiling for android should always use the toolchain from your NDK installation: /home/jash/Src/koreader/base/toolchain/android-ndk-r12b. You probably also need to make sure NDK is in your path, see: https://github.com/koreader/virdevenv/blob/master/docker/ubuntu/koandroid/build_android_tc.sh.

2. When you are building the initial host LUAJIT vm (HOSTCC), you are supposed to be using the host build tool chain instead of cross compile toolchain. Are you able to build the emulator at all? Have you tried this: http://stackoverflow.com/questions/6329887/compiling-problems-cannot-find-crt1-o?

If you only want to get a working build environment, give https://github.com/koreader/virdevenv a try, either the vm or docker setup should work out of the box.

If you want to dig into this, we will be here to help answer your questions.

**Comment by amendgit** [comment]
thanks, I fellow your advice and using the virdevenv. just build the android successfully. Thank you very much.
