### ISSUE TITLE
Difficult to add bookmark

### ISSUE THREAD

**Issue by dracodoc** [koreader/koreader#2892]
* KOReader version: `koreader-kindle-arm-linux-gnueabi-v2015.11-894-gd168db9`
* Device: `kindle voyage`

#### Issue
I found it's very difficult for me to add bookmark in epub.

#### Steps to reproduce

I'm not sure if I'm missing some tricks, when I pressed the right top corner to add a bookmark, I can only succeed once in about 8 attempts. Sometimes it seemed to need longer press, sometimes it seemed that I need to press precisely the 3 pixels in corner.

How big is the region that will respond to this action? Did anybody else have difficulty adding bookmarks?

**Comment by Hzj-jie** [comment]
It's a tap gesture.
The area is not that small: it's at least as large as my thumb tip. But the performance on voyage is slightly less than on Kobo, the screen may be refreshed or frozen for a while (0.5 sec AFAICT). So you may not double-tap.

**Comment by dracodoc** [comment]
Interestingly, I now found it's much easier to tap with other epub books. Maybe it's something temporary or book specific. Thanks!
