### ISSUE TITLE
hindi support

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#2895]
* KOReader version:all versions designed for kindle

* Device:kindle voyage kindle paperwhite

#### Issue KO Reader does not suppport epubs in hindi language even the hindi font is embeded in corresponding epub.
However,after converting the same epub to mobi format via calibre the book is perfectly legible

**Comment by Frenzie** [comment]
More information can be found here: https://www.mobileread.com/forums/showthread.php?p=3522768#post3522768

**Comment by poire-z** [comment]
Is it better since we got harfbuzz (summer 2018): bottom menu, Font Kerning > "best" ?
Or may be with current nightly and some additional harbuzz tweaks?

**Comment by poire-z** [comment]
Looks like it's highly dependant on the font features.

With FreeSerif:
<kbd>![image](https://user-images.githubusercontent.com/24273478/65379714-ed0cf800-dccc-11e9-8b41-333e4cf52f98.png)</kbd>

With Code2000:
<kbd>![image](https://user-images.githubusercontent.com/24273478/65379733-42490980-dccd-11e9-8840-96f3b90fcaf7.png)</kbd>

We see less of the "virāma" with Code2000, but I dunno if it's a feature or a bug :)
Is one of these ok?
