### ISSUE TITLE
Improve version string usability

### ISSUE THREAD

**Issue by xpirad** [koreader/koreader#2896]
Why there is only nightlies on http://build.koreader.rocks/download/
but no stable version?

When will a stable one be released? And how often?

**Comment by Frenzie** [comment]
The stable release is here: https://github.com/koreader/koreader/releases/tag/v2015.11-stable

How often? Preferably one to two times a year but clearly it's slightly behind schedule. However, I like think of the current nightlies as generally beta to RC quality. ;-)

**Comment by pazos** [comment]
about version tagging:  Why are we stucked on v2015.xx.yy? It does makes sense to date nightlies with `date +%Y-%m-%d` at building time

**Comment by Frenzie** [comment]
I suppose you mean that from a user's perspective? The relevant info is exactly tag v2015.11-stable and commit xxxxxx.

I don't think `date` would make much sense. I'd say the "correct" version of what you're proposing would be something like this. ;-)

```bash
$ git describe HEAD | xargs git show -s --format=format:"%cd" --date=short
2017-05-11
```

Or in full, along these lines:
```bash
$ echo "$(git describe HEAD) ($(git describe HEAD | xargs git show -s --format=format:"%cd" --date=short))"
v2015.11-1035-gb33c9268 (2017-05-11)
```

That wouldn't change depending on system configuration or if it happened to be built a day later of whatever.

What's the exact rationale behind adding this?

**Comment by gerroon** [comment]
It would be nice to name and version releases on Android as well. All apks say they are 1.3.3

**Comment by pazos** [comment]
@Frenzie: from user POV, of course. That includes me :)

On releases I see koreader-nightly-20170430 as the last one. Which makes sense to me. But in both the zip files and inside koreader i see v2015.11-1023-g773e24f.  My suggestion is to get rid of the tag "v2015.11" to name our version. AFAIK having this tag doesn't provide any help to document issues.

**Comment by KenMaltby** [comment]
On the contrary, if  I see koreader-nightly-20170430, in an issue description I have no immediate idea what release that is.  Where as if I see v2015.11-1023-g773e24f I know exactly which release it is.  I also know where it stands in the sequence of releases.

**Comment by gerroon** [comment]
Please provide the proper versioning (like git version whatever) for the apk installers. It is hard to know what version I am installing in the apk.

**Comment by Frenzie** [comment]
@pazos It's more precise than a date, which is quite helpful when bisecting. You can always derive what the 1023rd commit since tag v2015.11 is even without the hash. Just the date could be dozens of distinct commits.

@gerroon I might take a look next month but it is in the filename. :-)

**Comment by Frenzie** [comment]
Dropping this link here 'cause I came across it more or less randomly http://orip.org/2013/10/versioning-android-apps-with-git-tags.html
