### ISSUE TITLE
FR: Add confirmation to Power off/Reboot the device

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#2898]
* KOReader version: v2015.11-1038-g474c011
* Device: Kobo Glo HD

#### Issue
Consider adding a confirmation dialog to the newly added "Power off" and "Reboot the device"
actions. Accidentally invoking either one is super annoying. 
An option to disable these entries altogether would be great as well.

**Comment by Frenzie** [comment]
Disabling is already present through the menu customization option, although that's currently still potentially a bit user-unfriendly. You'd have to create `settings/filemanager_menu_order.lua` and `settings/reader_menu_order.lua`.

```lua
return {
    ["main"] = {
        "history",
        "book_status",
        "----------------------------",
        "ota_update", --[[ if Device:isKindle() or Device:isKobo() or
                           Device:isPocketBook() or Device:isAndroid() ]]--
        "version",
        "help",
        "system_statistics",
        --"----------------------------",
        --"poweroff", -- if Device:isKobo()
        --"reboot",   -- if Device:isKobo()
        --"----------------------------",
        "exit",
        -- I commented out the undesired menu entries for demonstration purposes
    },
    ["KOMenu:disabled"] = {
        "poweroff",
        "reboot",
    }
}
```

I already brought up confirmation in #2873, so I agree on that one.

**Comment by a-kohout** [comment]
Great, thanks!

**Comment by AlanSP1** [comment]
I had used for long time power off from xor_'s modification and even though it was top menu icon, I never powered my device off unintentionally. Now you need three more actions to power off or restart koreader, so this is even more safe in my opinion.

And, even if you trigger either action, it is not something "fatal".

Just mention this, it looks pretty safe from my point to have these options.

**Comment by a-kohout** [comment]
It might be the touchscreen on my device.
It's next to "Exit" which is needed to go back to KSM when wanting to establish a USB connection, so not safer at all.
Sure it's not fatal but it takes time to wait for the device to reboot.
Powering off is worse as you need to wait about 5 seconds before the device can be turned on again.

**Comment by AlanSP1** [comment]
Of course, if there's some problem with touch screen, there might be a problem, but this would cause problem with everything. I have H20, just to mention.

Anyway, just wanted to say, so far I didn't have problems, even when it was icon in top menu, which is much more exposed to accidents.

**Comment by Frenzie** [comment]
It's not that I've had any issues accidentally touching a particular menu item (H2O here as well) but this is simply about our UX. As it says in the UX guidelines for [ui.widget.inputdialog](http://koreader.rocks/doc/modules/ui.widget.inputdialog.html), which can be considered to apply to any action:

> If it would take the user more than half a minute to recover from a mistake, a "Cancel" button *must* be added to the dialog. The cancellation button should be kept on the left and the button executing the action on the right.

Disclaimer: I wrote that. The goal is to create and maintain a hopefully fairly intuitive, but at the very least *consistent* GUI. These menu items are either in violation of that rule (especially if you have KSM set to boot into Nickel every other time) or teetering right on the brink of it. On Kindle they'd go way overboard, and treating them separately in the backend would be inelegant. That shouldn't be done unless there were a very good reason, and that on faster systems it might take "only" 20 seconds to restart in optimal conditions can hardly count as a good reason.
