### ISSUE TITLE
Advance setting crashes

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2899]
Hi

When I use advance settings I mean when I try to open advance settings Koreader pretty much crashes with this log. I cant get any more details about it. It happens right after I click advance settings

```
KR version v2015.11-1036-g9e346f5 on Lollipop 5.1 Samsung Note 4

I/KOReader( 1921): DEBUG input event => type: 3, code: 54(Z), value: 1497, time: 1494908278.53356
I/KOReader( 1921): DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1494908278.53361
I/KOReader( 1921): DEBUG in tap state...
I/KOReader( 1921): DEBUG input event => type: 3, code: 47(S), value: 0, time: 1494908278.53426
I/KOReader( 1921): DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1494908278.53432
I/KOReader( 1921): DEBUG input event => type: 3, code: 53(Y), value: 1012, time: 1494908278.53442
I/KOReader( 1921): DEBUG input event => type: 3, code: 54(Z), value: 1497, time: 1494908278.53461
I/KOReader( 1921): DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1494908278.53465
I/KOReader( 1921): DEBUG in tap state...
I/KOReader( 1921): DEBUG set up tap timer
I/KOReader( 1921): DEBUG in tap timer true
I/KOReader( 1921): DEBUG single tap detected in slot 0 {
I/KOReader( 1921):     ["y"] = 1497,
I/KOReader( 1921):     ["x"] = 1012,
I/KOReader( 1921):     ["h"] = 0,
I/KOReader( 1921):     ["w"] = 0
I/KOReader( 1921): }
I/KOReader( 1921): DEBUG blitFrom 205 1207 0 0 60 60
I/KOReader( 1921): WARN  got error waiting for events: ffi/input_android.lua:143: Waiting for input failed: timeout
V/ApplicationPolicy( 3428): isApplicationStateBlocked userId 0 pkgname org.koreader.launcher
I/ActivityManager( 3428): Skip updateThumbnail for r=ActivityRecord{13ede34e u0 org.koreader.launcher/.MainActivity t20198 f}
W/ActivityManager( 3428): Activity pause timeout for ActivityRecord{13ede34e u0 org.koreader.launcher/.MainActivity t20198 f}
W/PackageManager(24701): Failure retrieving resources for org.koreader.launcher: Resource ID #0x0
W/PackageManager(24701): Failure retrieving resources for org.koreader.launcher: Resource ID #0x0
W/PackageManager( 4221): Failure retrieving resources for org.koreader.launcher: Resource ID #0x0
D/WifiWatchdogStateMachine( 3428): isPackageRunning - top:org.koreader.launcher.MainActivity
W/ActivityManager( 3428): Activity destroy timeout for ActivityRecord{13ede34e u0 org.koreader.launcher/.MainActivity t20198 f}
```

**Comment by Hzj-jie** [comment]
+1 Reproduce on Android only.

**Comment by gapmeister11** [comment]
Having the same problem on Android 7, Samsung Galaxy Tab Pro 10.1. Any idea which release introduced this?

**Comment by robert00s** [comment]
`
08-08 20:04:42.896 10561 10579 E luajit-launcher: Failed to run script: frontend/apps/filemanager/filemanagersetdefaults.lua:50: bad argument #1 to 'setfenv' (number expected, got nil)
08-08 20:04:42.896 10561 10579 V threaded_app: android_app_destroy!
![screenshot 2017-08-08 20-11-45](https://user-images.githubusercontent.com/22982594/29087458-555eca14-7c76-11e7-8357-3cf25940ff49.jpg)
`

This is because koreader cannot find file defaults.lua. When I manually copy file to /mnt/sdcard/koreader Koreder doesn't crash.
Unfortunately I don't know how to fix it :( 

![screenshot 2017-08-08 20-11-45](https://user-images.githubusercontent.com/22982594/29087646-e1fbb162-7c76-11e7-9e45-441c0ee688ff.jpg)

**Comment by Frenzie** [comment]
Based on your description my guess is probably something in https://github.com/koreader/koreader/blob/e3c17aa6d0f03ad9af56d5eb2d4ac899a3acda70/datastorage.lua

For example, note https://github.com/koreader/koreader/blob/e3c17aa6d0f03ad9af56d5eb2d4ac899a3acda70/datastorage.lua#L36-L47

**Comment by robert00s** [comment]
I think that here:
https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanagersetdefaults.lua#L16
we should use:
```
local defaults_path = DataStorage:getDataDir() .. "/defaults.lua"
if isAndroid then
    defaults_path = android.get_application_directory() .. "/defaults.lua"
end
```
but `android.get_application_directory()` return nil
https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L1187

**Comment by robert00s** [comment]
I think that `android.dir` is what I need.
https://github.com/koreader/android-luajit-launcher/blob/master/assets/android.lua#L1196

**Comment by Frenzie** [comment]
Thanks for looking into it. H-)
