### ISSUE TITLE
C67ML page refresh/rendering issues, empty page after start

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2900]
* KOReader version:
v2015.11-988-g6542382

* Device:
C67ML

#### Issue
When I open Koreader on my device Koreader's initial page (whatever that is, generally it opens a book that I have been reading ) is always blank, and it stays blank until I force refresh the screen, which is generally holding down the power button and pressign "cancel" or just tapping anywhere on the screen, which causes a force refresh of the page then Koreader renders the page fully. Until then it is always blank.

#### Steps to reproduce

Open Koreader on C67ML

**Comment by Frenzie** [comment]
Should be fixed by #3319.
