### ISSUE TITLE
Disable "full-screen" mode for android (make visible top bar)

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2902]
* KOReader version: v2015.11-894-gd168db9.apk
* Device: Android (phone), Inkbook Prime

#### Issue
By default KOReader run in fullscreen mode, with hidden to android menu bar (the one with clock, battery, wifi, notifications).

Because KOReader can't control (too?) many parts of android devices (frontlight, wifi on/off etc.) it can be useful to have this top bar visible (so it can be controller there). 
E.g. turning wifi on or off to Calibre, changing front light.

Please add such feature to disable full-screen mode.
I think fullscreen should be default, but with option to disable it.

#### Steps to reproduce
Run Koreader on Android.

**Comment by mwoz123** [comment]
This is how it should be done in android:
http://stackoverflow.com/questions/7692789/toggle-fullscreen-mode

Probably also [this AndroidManifest line](https://github.com/koreader/android-luajit-launcher/blob/master/AndroidManifest.xml#L18) should be removed

The only problem is how to pass boolean value (_fullscreen_) from lua code to java code (android code).
Does anyone know - is it possible to do it with [android-luajit-launcher](https://github.com/koreader/android-luajit-launcher)?

**Comment by Frenzie** [comment]
Sure, that's what FFI is for. That's probably for koreader-base though, not the launcher.

**Comment by mwoz123** [comment]
You're talking about : 
https://github.com/koreader/koreader-base/tree/master/ffi
or project:
https://github.com/koreader/ffi-cdecl
?
Could you give some examples integration with Java? Cause I was not able to find it.

**Comment by Frenzie** [comment]
There's some stuff in koreader/frontend/device/android/device.lua

I just mean that if you need to add more FFI stuff the launcher may not necessarily be the appropriate place.

**Comment by mwoz123** [comment]
Is there a doc where I can read howto use it?

From the methods in `koreader/frontend/device/android/device.lua` 
I was searching for references & found them only in `lua-jit-launcher/assets/android.lua` (searched all koreader files) e.g.:
> int32_t AConfiguration_getDensity(AConfiguration* config);
> int32_t AConfiguration_getKeyboard(AConfiguration* config);
> int32_t AConfiguration_getTouchscreen(AConfiguration* config);
> int32_t AConfiguration_getScreenSize(AConfiguration* config);
> void AConfiguration_getLanguage(AConfiguration* config, char* outLanguage);
> void AConfiguration_getCountry(AConfiguration* config, char* outCountry);

but for me they look as if they were only interface declaration, not real implementation.
Am I right?

I'm I getting it right that the letter C
_ffi.**C**.AConfiguration_getDensity(android.app.config)_
inform it's a C language implementation? Which file contains implementation?
Can I use Java?

Help appreciated.

**Comment by Frenzie** [comment]
My bad, looks like that would be the place to expand then.

I would assume the Android NDK docs are the relevant ones here. But I guess I misunderstood. I don't really know anything about Android as such. But all the relevant info seems to have been collected now?

**Comment by mwoz123** [comment]
The only thing I found about "Android NDK fullscreen" was this [link](https://stackoverflow.com/questions/38459798/what-is-the-best-way-for-creating-a-fullscreen-app-in-android-ndk-which-renders).

[Here's](https://www.gamedev.net/topic/674511-auto-hide-nav-bar-on-android-app-ndk/) something similiar but he tried to hide nav (bottom buttons) bar instead of top (menu) bar.

But it looks too low level programming for me as I don't know C/C++ at all:(

Isn't there  a way to call normal (Java) Android SDK instead of NDK?

**Comment by pazos** [comment]
@mwoz123, @Frenzie: We actually use java code in koreader since this commit: https://github.com/koreader/android-luajit-launcher/pull/41

**Comment by mwoz123** [comment]
@pazos Thanks. Good to know.

Inital commit created:
https://github.com/koreader/android-luajit-launcher/pull/50

Looking forward for help and feedback.

**Comment by Frenzie** [comment]
Implemented by #2938.
