### ISSUE TITLE
FR: disconnect wifi automatically timeout

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2903]
* KOReader version:
* Device: Kobo Glo HD

Would it be possible to integrate an option in the "OTA update" menu, so that the wifi is automatically disconnected after the update of the program?
This would be nice on my ereader as I'm eager to receive the new versions :-)

**Comment by Frenzie** [comment]
I personally just toggle suspend to quickly disable wifi. :-P

I think it'd make more sense to implement something more generic. E.g., disable wifi after x minutes of inactivity (default, 10, 15 or whatever, plus custom value).

**Comment by Brnoch** [comment]
Yes, I realized that there was this possibility. This is totally OK for me.
The option you suggest could be usefull if we want to use online services
for a period of time of if we forget to disable the wifi.

**Comment by poire-z** [comment]
Implemented in #6424
