### ISSUE TITLE
Screensaver: option to set the Auto strech option for all books?

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2904]
* KOReader version:
* Device: Kobo Glo HD

I'd like to set the option "Auto stretch this book's cover image in screensaver" for all the books, as I don't like the images to be distorted. This would be a nice addition.
But maybe the option needs to be set individually on each book for a specific reason?

**Comment by KenMaltby** [comment]
This could be an example of how "Defaults" can work with the specific book setting to provide the option to be used, until you open a book where you need to use something else.  The selectable options would be in the reader menu as would be the long press default setting.

**Comment by Brnoch** [comment]
That would be nice! And I think that it would match the needs of the majority of the koreader users?

**Comment by ersi-dnd** [comment]
A blank screensaver option would also be most welcome.

**Comment by robert00s** [comment]
Done in #3535
