### ISSUE TITLE
File manager: how to read the book description?

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2905]
* KOReader version:
* Device: Kobo Glo HD

#### Issue
Is there a way to read the book description in the file manager? I don't know how to proceed.

**Comment by Frenzie** [comment]
If it's not under long-press then no.

**Comment by Brnoch** [comment]
I made a test with several books in my library: the book description (I don't know the exact name for it, but it appears on the bottom right of Calibre) is never in the page displayed after a long-press on an item of the file manager.

**Comment by ersi-dnd** [comment]
Wouldn't it make sense to have the Book Status in the menu there in the file manager along with Purge .sdr and Delete etc.?

**Comment by ersi-dnd** [comment]
I have a reverse question: When you are inside a book, how to read the filename? Book Status sounds like File Properties to me, but it apparently is not meant to be like this. I'd expect to see the filename (and perhaps file size and other such data) there, but it's are not there. 

Is there such a thing as File Properties accessible when you are in a book so the user can take a look at the current filename without leaving the book?

**Comment by Frenzie** [comment]
> Book Status sounds like File Properties to me, but it apparently is not meant to be like this.

That's a minor difference of opinion around here iirc. I think it should definitely include that. ;-)

**Comment by KenMaltby** [comment]
I don't know why this keeps being missed, but there is a setting, in the bottom menu, under the gear icon, to select between the "Full" or the "Mini" "Progress Bar".   With the Full progress bar you get the file name, page #/# you are on, and a little battery graphic.  This will appear at the top of the page. You can set it as default by long pressing on the "Full" button.

**Comment by Frenzie** [comment]
That's only for epub, isn't it?

**Comment by KenMaltby** [comment]
Right, it is in the cr3 engine reader menu.  With the PDF reader there is a "Status bar" to configure the footer.  But no full/mini option.

**Comment by ersi-dnd** [comment]
@KenMaltby 
The "full" progress bar is not really full. It applies only to epub/doc files. It changes away from the bottom position (the position should be configurable - surely somebody already suggested this). It removes much-needed information, such as battery, reading progress indicators, clock, etc. It's a whole different thing than the usual status bar.

**Comment by robert00s** [comment]
It was added by @poire-z in https://github.com/koreader/koreader/pull/2993
@Brnoch Check newest version.
I think we can close it now.

**Comment by Frenzie** [comment]
Indeed. Closing now.
