### ISSUE TITLE
Crashes while opening an ebook (Floating point exception)

### ISSUE THREAD

**Issue by protist** [koreader/koreader#2908]
* KOReader version: koreader-nightly-20170430
  * koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1023-g773e24f
* Device: Kobo H2O

#### Issue
Koreader crashes when opening a specific book.

#### Steps to reproduce
1. Attempt to open a specific ebook.
2. Immediately crash to Kobo Start Menu 08, with `koreader exited irregularly`.

From `.adds/koreader/crash.log`.
```
05/20/17-09:24:59 INFO  Kobo suspend: woke up!
05/20/17-09:24:59 INFO  Kobo resume: clean up after wakeup
05/20/17-09:24:59 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
05/20/17-09:25:00 WARN  no refresh got enqueued. Will do a partial full screen refresh, which might be inefficient
ifconfig: SIOCSIFADDR: No such device
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device
05/20/17-09:31:03 INFO  Kobo suspend: going to sleep . . .
05/20/17-09:31:03 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
05/20/17-09:31:05 INFO  Kobo suspend: waited for 2s because of reasons...
05/20/17-09:31:05 INFO  Kobo suspend: synced FS
05/20/17-09:31:05 INFO  Kobo suspend: asking for a suspend to RAM . . .
05/20/17-09:31:05 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
05/20/17-09:32:57 INFO  Kobo suspend: woke up!
05/20/17-09:32:57 INFO  Kobo resume: clean up after wakeup
05/20/17-09:32:57 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
05/20/17-09:32:57 WARN  no refresh got enqueued. Will do a partial full screen refresh, which might be inefficient
05/20/17-09:33:00 INFO  opening file /mnt/onboard/<Author Name>/<Book Title>.epub
05/20/17-09:33:00 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
05/20/17-09:33:00 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
Floating point exception
```
Maybe related to #1931, but this was apparently fixed in my version.

I'm happy to email the book to individuals, but I'd rather not post it publicly. I purchased the book, and I'm unsure about the legality of posting it publicly.

**Comment by protist** [comment]
I can open the book if I manually create `<Author Name>/<Book Title>.sdr/metadata.epub.lua` with the following content.
```
-- we can read Lua syntax here!
return {
    ["embedded_css"] = false
}
```
If I then attempt to turn on embedded style within the GUI, koreader crashes again.

**Comment by AlanSP1** [comment]
Just to mention, it maybe totally unrelated, but I have one book that crashes koreader and coolreader if I attempt to open it. And it crashes it in a bad way (needed to reset it by using reset button, don't remember if long holding power button helped, but I think not because I used reset button). Didn't try with nickel.

If there could be a way to prevent such bad crashes would be great. And just to mention, on PC using SumatraPDF I could open book without problems.

**Comment by Frenzie** [comment]
> I'm happy to email the book to individuals, but I'd rather not post it publicly. I purchased the book, and I'm unsure about the legality of posting it publicly.

That shouldn't preclude sharing the name of the ebook. ;-) If it's something from a Humble Bundle book bundle, for example, there's a decent change that I might own it already. (In fact those DRM-free ebooks are just about the only ebooks I consider worthy of payment, all of my other electronic reading being based on the likes of DBNL, OAPEN, Gallica, and Archive.org.)

**Comment by protist** [comment]
In a general case, I can think of a few theoretical reasons against sharing the name of an ebook. I can imagine that a theoretical user might purchase an ebook from a commercial site, and then strip the DRM from it in order to read it in koreader. It's very unlikely that this would apply to me, of course!

**Comment by frankyifei** [comment]
Try comment out these line in the crengine source, in lvtinydom.cpp,
```
3818        ldomNode * abox = insertChildElement( firstNonEmpty, LXML_NS_NONE, el_autoBoxing );
3819        abox->initNodeStyle();
3820        abox->setRendMethod( erm_final );
3821        moveItemsTo( abox, firstNonEmpty+1, lastNonEmpty+1 );
```
or you can try to replace all the </br> in your book, it should work as well. i'm still investigating the reason so I am not sure this is the correct fix for this bug.

**Comment by protist** [comment]
I'm not exactly sure what file you are referring to. I couldn't find any file called `crengine` nor `lvtinydom.cpp` on my Kobo (or in the koreader download).

I grepped for `</br>`, but that string does not exist in my book.

**Comment by frankyifei** [comment]
Maybe I was wrong. can you send me the book

**Comment by protist** [comment]
Thanks. I just emailed you @frankyifei .

**Comment by frankyifei** [comment]
got it. but I can only test it on kindle

**Comment by frankyifei** [comment]
It is not like I expected. Crash happens during formating process.
After line by line test of stylesheet.css, I found out that if you delete 
`.calibre3 {
    height: auto;
    width: 100%
    }`
the file can be opened in emulator.

**Comment by protist** [comment]
Ah, nice find @frankyifei! Thank you for checking that out and fixing it.

**Comment by poire-z** [comment]
Fixed last summer in https://github.com/koreader/crengine/pull/73
