### ISSUE TITLE
Wireless connection defaults to /data/data...

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#2909]
Hi

WHen I try to connect to Calibre as wireless device, Koreader opens in /data/data/org.koreader/files which is a system folder. And when I try to go up in folders,. it does not go beyond koreaders installation folder as it is not allowed to pass its own installation folder.

This should normally default to the sdcard not the instal folder because if the files are donwloaded there, no otherapp except Koreader can read those book files.

I use v2015.11-1039-g3492b8b on C67ML

thanks

**Comment by Frenzie** [comment]
@gerroon I can't confirm this. I can browse my whole SD card.

**Comment by gerroon** [comment]
I will test with my new device. I do not have c67 anymore.

**Comment by Frenzie** [comment]
@gerroon Any news? :-)

**Comment by gerroon** [comment]
which setting do I have to put into settings.reader.lua to define the calibre server so I can connect to it? I do not get settings in koreader

**Comment by KenMaltby** [comment]
If you long press on the "Local calibre catalog" selection it will give an "edit" option, and you can enter the IP and port  that should be shown in calibre "Connect and share" content server setting.

**Comment by gerroon** [comment]
Is this the same thing? I am tryig to connect to Calibre wireless not calibre server

**Comment by KenMaltby** [comment]
No, not the same, but on mine they share the same IP and Port #  I don't use the connection that it appears you are having trouble with.  When I have used it, it was not reliable and it doesn't appear to be working for me now, either.

**Comment by gerroon** [comment]
How can a wireless device and the opds catalog can use the same port?

Yeah I want to try koreader  as a wireless device which this bug was about. 

I will try it as a catalog though  for sure, good idea.

**Comment by Frenzie** [comment]
> which setting do I have to put into settings.reader.lua to define the calibre server so I can connect to it? I do not get settings in koreader

I don't use calibre so I wouldn't know anything about settings, but when I clicked Connect/share and whichever one of the two options is relevant ("Start wireless device connection"?) it auto-connected for me last week.

**Comment by KenMaltby** [comment]
calibre has two wireless connection functions that are implemented using the Connect/share menu, one is the (Content server) which provides both HTML and OPDS type "catalogs" - the other, your ("Start wireless device connection"?) option allows for a "calibre companion" type connection to a wireless device.  The calibre "Content server" is accessible via the KOReader OPDS support, and is normally quite reliable (I use it all the time.)  The "wireless device connection" makes use of a caliber companion/wireless connection plug-in on KOReader to make the connection.   

The Content server uses an IP address, not a URL, so it most likely  must be used with devices that have IP addresses on the same network.

**Comment by Frenzie** [comment]
Anyway, that's what I thought this was referring to. However, the OPDS catalog also works just fine for me. I use it all the time on Android. (To quickly grab a couple of test documents.)

**Comment by robert00s** [comment]
@gerroon 
Try install newest version and set manual server address in `calibre wireless connection -> Server address`
Let me know if it helped
