### ISSUE TITLE
Landscape mode menu close button located in awkward position

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#2913]
* KOReader version: v2015.11-1039-g3492b8b
* Device: Kobo Aura One

The new menu with exit/reboot/power off is nice, but the "close menu" arrow button is poorly located. In general this button in landscape is not great UX, but here it's especially bad because I often trigger Exit instead.

![menuclosearrow](https://cloud.githubusercontent.com/assets/4918121/26283983/3f4f1b90-3e3a-11e7-950c-92aa95351424.jpg)

For now I use the the swipe up gesture to close the menu.

**Comment by Frenzie** [comment]
For submenus the idea is to change it to something like

```
← Name of menu
```

(at the top)

I'd be more inclined to consider swiping up and clicking outside the main methods though, not workarounds. Even after improving that button it'll still be a specific area (just less prone to misses) whereas swiping can take place on the entirety of the menu. It's just much easier to execute.

But yes, it's well known that the little up arrow is awkward. ;-)

**Comment by pickx** [comment]
Thanks, the left arrow is a good idea. Another idea is, since "clicking outside" is an intuitive way to dismiss the menu, to make the maximum menu height shorter in landscape (by splitting it into 2 pages, with less common options like System Statistics and Version moved to page 2).

Since this is a top-level menu, I'm not sure that button should be there at all (since there's nothing to "return" to).

**Comment by Frenzie** [comment]
Main issue fixed in #3167.
