### ISSUE TITLE
pinc zooming

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#2914]
* KOReader version:latest version designed for kindle e readers
* Device:paerwhite,voyage

 On pinch zooming font size increases to only 1 at a time.I would like suggest that it should increase or decrease by more than 1 at a time like in native kindle operating system.

**Comment by Frenzie** [comment]
Pinging @robert00s who implemented this feature.

**Comment by robert00s** [comment]
Done in #2989.
I think we can close it now.
