### ISSUE TITLE
How to set "Arrow" in "Page overlap" settings as default, instead of "Gray out"? 

### ISSUE THREAD

**Issue by ruizhaogit** [koreader/koreader#2915]
* KOReader version: koreader-nightly-20170209
* Device: Android (onyx n96)

#### Issue
How to set "Arrow" in "Page overlap" settings as default, in stead of "Gray out"? 
#### Steps to reproduce
Use koreader to open a pdf file and tap the settings -> page overlap -> arrow. It works.
But for a new pdf file, how to make the koreader remember the arrow in page overlap setting as default?

Thank you!

**Comment by Frenzie** [comment]
Long press should do the trick.

**Comment by ruizhaogit** [comment]
Long press does not work.

**Comment by Frenzie** [comment]
I see. That's something I would consider a bug. Fix coming up.

**Comment by ruizhaogit** [comment]
Hi, do you know in which file I can change this "config:readSetting("page_overlap_style")" page_overlap_style = "arrow"? like settings.reader.lua for the G_reader_settings.

**Comment by houqp** [comment]
You don't need to edit the settings file, just long press on the menu item to set it to the default.

**Comment by ruizhaogit** [comment]
But the new version of koreader is not release yet. I want to give a try ASAP:) Can you tell me which file?

**Comment by houqp** [comment]
It's in frontend/apps/reader/modules/readerview.lua. The new release should be out in couple hours.

**Comment by ruizhaogit** [comment]
Thank you! Looking forward to try the new release!

**Comment by ruizhaogit** [comment]
Hi guys, when will be the next release including this change? Thanks!

**Comment by Frenzie** [comment]
It's in the latest nightly build (v2015.11-1047-ged36ab3).

**Comment by ruizhaogit** [comment]
Is there also a android version?

**Comment by Frenzie** [comment]
Looks that way? :-)

**Comment by ruizhaogit** [comment]
I didn't find .apk file, only found the targz file. Can you give me a link to the android version? Thx

**Comment by Frenzie** [comment]
http://build.koreader.rocks/download/nightly/v2015.11-1047-ged36ab3/

I would assume the top is apk and the bottom targz but I'm on my phone.

**Comment by ruizhaogit** [comment]
Thanks for the link! But it seems this nightly build along with the release koreader-android-arm-linux-androideabi-v2015.11-1023-g773e24f.apk doesn't work on my device. However, koreader-android-arm-linux-androideabi-v2015.11-894-gd168db9.apk works.
