### ISSUE TITLE
Delete Russian (Russia) translation

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2918]
* KOReader version:
* Device: all

#### Issue
There are currently two translations to Russian on Transifex: "Russian" and "Russian (Russia)"
"Russian" is up to date, "Russian (Russia)" is in backwards state. There must be only one project, "Russian (Russia)" should be deleted
#### Steps to reproduce
[open](https://www.transifex.com/houqp/koreader/languages/)

**Comment by houqp** [comment]
Thanks, I have deleted the language in transifex.
