### ISSUE TITLE
How to reset reading stats

### ISSUE THREAD

**Issue by cmoig** [koreader/koreader#2920]
So this isn't an issue ,i just wonder how to reset the reading stats ,i have been exploring koreader since i got my hands on my kindle yesterday : ) , it seems really great comparing to the basic reader.

**Comment by Frenzie** [comment]
Individual books currently have their statistics stored in the metadata file in their *.sdr directories, but I'm not sure how the total is calculated off the top of my head. #2893 will change it to an SQLite db.

**Comment by robert00s** [comment]
We will return to this issue after merging and testing statistics plugin v2 (#2893).

**Comment by robert00s** [comment]
Done in #2893. We can close it.
