### ISSUE TITLE
"Storage statistics" menu entry not translatable

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2921]
* KOReader version: current
* Device: all

#### Issue
"Storage statistics" menu entry not translatable.
#### Steps to reproduce
"Storage statistics" menu entry appears in English when UI language set to Russian. Search for that string in the transifex translation project yields no results.

**Comment by Frenzie** [comment]
It looks like #2764 forgot to remove `storage_stat` from the menu order, meaning it'll still show up. It's not supposed to be translatable anymore because it's now part of System Statistics.
