### ISSUE TITLE
PagePress doesn't work 

### ISSUE THREAD

**Issue by cmoig** [koreader/koreader#2923]
Hi , I own a kindle voyage  ,
normally the page press works ,but i have found that it doesn't work on one condition: 

So i opened a kindle book (with kindle reader) ,in landscape mode .
Then i tryed to open pdf file with koreader in portrait mode , but my pagepress buttons doesn't work.

The only way to fix it was to go back to kindle reader and set it in portrait mode in order for the pagepress buttons to work on koreader.
This isn't such a big issue so it is fine by me ,i am guessing ,the oasis has the same issues.
And also... thank you for the amazing work you have done!! ,i love koreader !!!
Hope i can take notes soon

**Comment by Hzj-jie** [comment]
Unfortunately PagePress is not a reliable feature on Voyage because of the limitation from the OS.

**Comment by NiLuJe** [comment]
Possibly nothing we can do, AFAICT.
