### ISSUE TITLE
android update project --path . -t android-19

### ISSUE THREAD

**Issue by ruizhaogit** [koreader/koreader#2924]
* KOReader version: master
* Device: android

#### Issue
Try to build master, but run into error:

make -C platform/android/luajit-launcher apk
make[2]: Entering directory `/home/rui/workspace/koreader/platform/android/luajit-launcher'
android update project --path . -t android-19
Error: Target id 'android-19' is not valid. Use 'android list targets' to get the target ids.
make[2]: *** [local.properties] Error 1
make[2]: Leaving directory `/home/rui/workspace/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/home/rui/workspace/koreader'
make: *** [update] Error 2

#### Steps to reproduce
Follow the instruction on the koreader github.

**Comment by Frenzie** [comment]
Compare #2647 but you didn't mention your OS. Also it would be useful to mention the exact command you used (`./kodev release android`?) both in case the README is updated and to make absolutely sure we're talking about the same thing.

**Comment by houqp** [comment]
See https://github.com/koreader/virdevenv/blob/master/docker/ubuntu/koandroid/build_android_tc.sh#L20. You need to install android-19 SDK.

Feel free to add this to the readme.

**Comment by ruizhaogit** [comment]
OS is ubuntu 14.04. Yes, the command is  "./kodev release android". You are right! I need to install android-19 SDK.

**Comment by mwoz123** [comment]
> You need to install android-19 SDK.

My fight with :
```
android update project --path . -t android-19
Error: Target id 'android-19' is not valid. Use 'android list targets' to get the target ids.
```
- (if no sdkmanager/android command in path) add to path android variables 
`$ export PATH=$PATH:~/Android/Sdk/tools:~/Android/Sdk/tools/bin`
- according to [this](https://developer.android.com/studio/command-line/sdkmanager#install_packages) install platform 19 should be 
`sdkmanager "android-19"` or `sdkmanager "platforms;android-19"`
but it quit with warings:
```
$ sdkmanager "android-19"
Warning: File /home/marcin/.android/repositories.cfg could not be loaded.       
Warning: Failed to find package android-19                                      
$
```
- [googling around](https://askubuntu.com/questions/885658/android-sdk-repositories-cfg-could-not-be-loaded) says to create new 
`touch ~/.android/repositories.cfg`
- then  
`$ sdkmanager --update`
- and finally
` $ sdkmanager "platforms;android-19"

but reruninig `./kodev release android` end up with (unsolved yet) :
```
make[2]: Entering directory `/media/marcin/Dane1/koreader/platform/android/luajit-launcher'
android update project --path . -t android-19
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update project --path . -t android-19"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
make[2]: *** [local.properties] Error 2
make[2]: Leaving directory `/media/marcin/Dane1/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/media/marcin/Dane1/koreader'
Makefile:379: recipe for target 'update' failed
make: *** [update] Error 2
```
