### ISSUE TITLE
"Storage statistic" menu not removed

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2926]
* KOReader version: current
* Device: all

#### Issue
"Storage statistics" menu item wasn't removed, it appears now in leftmost menu and marked as "new"
#### Steps to reproduce
Open menubar, choose leftmost menu icon (the one with drawing of a bookmark).

**Comment by Frenzie** [comment]
Ah yes, that is how it's supposed to work when a plugin (or anything) provides menu entries that aren't sorted unless they're explicitly disabled. This comes down to updates never deleting stuff. It could very easily be added to the disabled menu entries, but hiding the fact that such a plugin has been loaded seems suboptimal.

@houqp Any thoughts on what we should do?

**Comment by houqp** [comment]
This is tricky, we can't just delete files that's missing from the new version because people might have their custom plugins installed there. I think it's better to add an extra upgrade process when koreader starts so we can do cleanup config migration between version updates.
