### ISSUE TITLE
Feature request: Dual cropping

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#2931]
This is a feature that no other app I know has, but maybe is not doable since it has to do with the MuPdf engine (I think...)
The option to have different crop rect for left and right sides of a book!
Usually the paper books have different margins for the left/right side.
That makes me crop with a rect that contains both text blocks, but that produces bigger left/right margins.
Thanks for your time anyway :o)

**Comment by Frenzie** [comment]
Iirc https://sites.google.com/site/pdfscissors/ can do that.

**Comment by embryo10** [comment]
Yes, but I was thinking of doing it in the reader, like the normal cropping option.
There is not always a computer and an internet connection available...

**Comment by poire-z** [comment]
From my experience, it already does exactly what you wish.
When you set-up some crop box, it saves it for the page you are on, and also in a generic crop for "odd" and "even":
https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readercropping.lua#L138
Then, on a later page with no crop box for it yet defined, it get and uses the one from odd/even:
https://github.com/koreader/koreader/blob/master/frontend/document/document.lua#L183

(As saved in the .sdr/metadata.lua:
```
    ["bbox"] = {
        [3] = {
            ["y1"] = 683,
            ["x0"] = 158,
            ["y0"] = 87,
            ["x1"] = 534
        },
        [4] = {
            ["y1"] = 810,
            ["x0"] = 23,
            ["y0"] = 265,
            ["x1"] = 490
        },
        ["odd"] = {
            ["y1"] = 683,
            ["x0"] = 158,
            ["y0"] = 87,
            ["x1"] = 534
        },
        ["even"] = {
            ["y1"] = 810,
            ["x0"] = 23,
            ["y0"] = 265,
            ["x1"] = 490
        }
    },

```
)

**Comment by embryo10** [comment]
Well, then, I stand corrected! :o)
You are right! Just checked. 
So, I will close this with more thanks for this great reader!!

**Comment by houqp** [comment]
This is one of the very early features implemented by @dpavlin if I recall correctly :) Back then the project is still named KPV.
