### ISSUE TITLE
ota.koreader.rocks malfunction

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2935]
* KOReader version: current
* Device: kindle

#### Issue
I keep receiving error message while attempting to perform OTA update with ota.koreader.rocks after downloading updates. Previously I could update with other servers, now they claim my version is up to date. When I am trying to open the server link in browser, I get an SSL error.
#### Steps to reproduce
Set OTA update server to https://ota.koreader.rocks:80/ ,update channel to development, and try to perform OTA update.

**Comment by Frenzie** [comment]
There's a secure connection issue. Pinging @houqp

**Comment by houqp** [comment]
@ilyats don't use `https://ota.koreader.rocks:80/`. It should be `http://ota.koreader.rocks:80/` or `https://ota.koreader.rocks:443/`.

**Comment by ilyats** [comment]
@houqp how to change it? The menu has only a list of predefined addresses, without possibility to enter an address not in the list.

**Comment by Frenzie** [comment]
What are the error messages?

**Comment by ilyats** [comment]
@Frenzie I think it is the error at frontend/ui/otamanager.lua:154 (Error updating KOReader. Would you like to delete temporary files?)

**Comment by ilyats** [comment]
After I did a clean install of v.2015.11-1051 by hand, trying to update to 1052 via OTA gives the same error.

**Comment by ilyats** [comment]
Statistics shows 2.6G free on the storage, so OTA update should not fail due to lack of free space.

**Comment by ilyats** [comment]
BTW, other OTA servers still have version 1049

**Comment by ilyats** [comment]
Could it be that the server does not close the connection properly? Other server may fail to update because of this.

**Comment by ilyats** [comment]
It did update to v.2015.11-1052 now. I'm closing this issue.

**Comment by houqp** [comment]
I turned off cloudflare caching yesterday. @ilyats the ota update is working for you now right?

**Comment by ilyats** [comment]
@houqp Yes, it updated to v.1052 yesterday
