### ISSUE TITLE
No support for font variants in UI based on language

### ISSUE THREAD

**Issue by alexandrahurst** [koreader/koreader#2936]
* KOReader version: current
* Device: all

#### Issue

There is currently no way to specify different UI fonts, both default and fallback, based on the user's selected language.  This isn't a major issue, but for languages such as Chinese, Japanese, and Korean, the appearance of the same unicode characters can vary noticeably based solely on which language a given font is designed for (see example below).

![](http://www.growingwiththeweb.com/images/2014/03/09/cjk-characters.png)

Although I am less familiar with the details, apparently this is an issue between different variations of Western-language fonts as well.  For example, the English (top) and Romanian (bottom) versions of Veranda render the same glyphs differently:

![](https://upload.wikimedia.org/wikipedia/commons/f/f3/Pango_locl_demo.png)

Ideally, the correct fonts would be automatically selected based on the user's chosen language.

#### Steps to reproduce

Set KOReader language to Japanese and restart.  The UI language is now Japanese, but the rendered glyphs are the Chinese variants.

#### Proposed solution

Make all the fonts in `frontend/ui/font.lua` translatable so that custom fonts can be selected on a per-language basis.  Then, for example, the Japanese "translation" of the fallback font "`noto/NotoSansCJK-Regular.ttf`" could be an alternate font such as "`noto/NotoSansCJKjp-Regular.otf`" which has the appropriate Japanese versions of the necessary glyphs.  Of course, the appropriate font would also need to be added to the repository.

**Comment by NiLuJe** [comment]
There's a genuine concern about the amount of font needed to cover all this, which we kind of went over in #3942 ;).

**Comment by poire-z** [comment]
OK, this issue mentions "UI" in its title, but also _There is currently no way to specify different UI fonts, both default and fallback_, which seem to indicate it was more about having that for crengine.

So, #5667 should have fixed that for the UI text (menus, dicts, wikipedia...) - if someone is able to confirm we pick Japanese glyphs correctly if the UI is japanese.

For crengine, it's another issue, tracked somehow at https://github.com/koreader/crengine/issues/307#issuecomment-531739317.
