### ISSUE TITLE
Battery statistics: "sleeping" time is not identified correctly

### ISSUE THREAD

**Issue by protist** [koreader/koreader#2937]
* KOReader version: koreader-nightly-20170430
  * koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1023-g773e24f
* Device: Kobo H2O

#### Issue
"Battery statistics" presents incorrect information.

#### Steps to reproduce
1. Open up "Battery statistics".
2. Observe incorrect data.

Currently the statistics say
```
Awake since last charge
  Total minutes     39703.47
Sleeping since last charge
  Total minutes     0.15
```
My kobo has been sleeping for most of this time, and only on for less than ~1 hour per day.

**Comment by Frenzie** [comment]
Same here, also see https://www.mobileread.com/forums/showthread.php?t=286933

Pinging @Hzj-jie

**Comment by protist** [comment]
Hmmm… I presumed that the Kobo really *was* sleeping, and that the battery statistics just got it wrong. After the last koreader update, my battery life included phenomenally, which I presumed was due to fixes relating to issue #2239. That's made me think that it really *was* suspending properly now. However, the first post of that linked thread hypothesises otherwise, although it might just be pure speculation.

**Comment by Frenzie** [comment]
Mine definitely sleeps or it would've died many weeks ago.

**Comment by protist** [comment]
That makes sense. As I implied above, my battery life is ridiculously good now. However, I have no idea how much drain occurs when awake, and how much when asleep. If only there were a way to inspect those statistics… 😁

**Comment by cramoisi** [comment]
yup, it was sleeping. But I was experiencing  the kobo drain bug at the same time and tried to use battery stat to find the issue...
So, since I remove the magnet, it's ok regarding suspending and it's just the battery statistics which is wrong.

**Comment by Hzj-jie** [comment]
Several changes are related,

https://github.com/koreader/koreader/commit/30378eb2a82ac1b2f686b0db638b194b642af4ab
  - This ensures the battery statistics can receive callbacks in filemanager

https://github.com/koreader/koreader/commit/d4756d777fd40e73bbea70307d9c16af76f9c82f
  - Fix a typo which causes the state to be not reset.

So you may try the latest version.

**Comment by cramoisi** [comment]
Great ! I will test it as soon as it synch from the ota server.

**Comment by protist** [comment]
I just updated to the latest `v2017.06.12-nightly` aka `koreader-nightly-20170612` aka `koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1054-g6870bc2.zip`, which includes these commits.

It's still broken for me in this version. FWIW the sleeping time has increased a little, but it's still incorrect. I slept it for 5–10 minutes and I see the following.

```
Awake since last charge
  Total minutes     25.55
Sleeping since last charge
  Total minutes     0.40
```
(Contrast to the original post where koreader reported a total sleep of `0.15`.)

**Comment by cramoisi** [comment]
Perhaps i'm wrong, but the latest is `http://koreader.ak-team.com/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1071-g970f2e7.targz` ; the `koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1054-g6870bc2.zip` is from 13 days ago.

**Comment by Frenzie** [comment]
@cramoisi 
The specific commits mentioned by @Hzj-jie were from last month, so provided that's all that changed in this regard it doesn't necessarily matter as long as you're using v2015.11-1045-gd4756d7 or higher.

**Comment by cramoisi** [comment]
@Frenzie. good to know , thanks!

**Comment by protist** [comment]
@cramoisi Huh, I didn't even know about that site. I always download from the GitHub [tagged releases](https://github.com/koreader/koreader/releases). But yeah, as @Frenzie says, this tag included the commits. If you follow the commit links in [this comment](https://github.com/koreader/koreader/issues/2937#issuecomment-310804445), you can see the tags near the top `v2017.06.12-nightly`.

**Comment by cramoisi** [comment]
@protist : it's the server koreader update when you choose an ota synch from koreader itself. for the rest, sorry, i quite mixed all the issues i'm following (as the one related to the light).

**Comment by robert00s** [comment]
Done in #5626
