### ISSUE TITLE
Screen not updating after leaving screensaver

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2939]
* KOReader version: v2015.11-1052
* Device: Kindle 7th Generation

#### Issue
Sometimes after leaving screensaver the screen does not update. Sometimes only status bar appears. The screen updates after several touches, sometimes by parts.
#### Steps to reproduce
Open PDF file, wait till screensaver appears, push the power button to leave it.

**Comment by robert00s** [comment]
I have the same issue in my KPW3. I'll try to analyze it in my free time.
For now you can diagonal swipe that refresh full screen.
https://github.com/koreader/koreader/pull/2655#issuecomment-287579534

**Comment by ilyats** [comment]
@robert00s do you also have refresh problem at leaving screensaver? #1934

**Comment by Hzj-jie** [comment]
I am using voyage, and I have both issues: won't refresh after resuming and won't refresh after exiting.
The later one is not a real issue, I never use the stock reader anyway.

**Comment by Hzj-jie** [comment]
This should be fixed by the change @robert00s referred.
