### ISSUE TITLE
Text direction is wrong for some languages such as persian or arabic.

### ISSUE THREAD

**Issue by hamzehnasajpour** [koreader/koreader#2944]
* KOReader version: latest version
* Device: android

#### Issue
Why when i open an epub that written with arabic language, text direction is wrong and not RTL.
For example the content of file is:
Word1 Word2 Word3.
But if lanugauge was arabic or persian this conent show as the following line:
Word3 Word2 Word1.

Please guide me.

**Comment by Frenzie** [comment]
Unfortunately I don't think RTL is currently supported in EPUBs though I'm not completely sure.

Pinging @gerroon @Ulterimate @serdar0020 as I think they might use RTL languages.

**Comment by gerroon** [comment]
My issue was with reflowed Pdfs.

**Comment by poire-z** [comment]
Fixed for EPUBs with #5390 and #5436, available since release 2019-10.
(Thanks @pazos for finding these old issues :)
