### ISSUE TITLE
Duden stardict dictionary issues

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#2951]
* KOReader version: v2015.11-1053
* Device: Kindle 7th Generation

#### Issue
Duden stardict dictionary sometimes contains more then one entry for the same spelling. In such cases KORearer dictionary lookup displays only one entry. Also, it contains html sequences &lt; and &gt; which bracket specification of a verb's declination type and the auxiliary verb used to form a verb's perfect. These sequences are displayed as they are, without converting to < and >.  Both issues can probably be fixed by changing the file's formatting, does somebody have suitable file? 
#### Steps to reproduce
Install Duden stardict dictionary, then look up e.g. "Geschick". Only the entry corresponding to the meaning "agility" is displayed, not the one corresponding to "fate". The HTML sequences can be seen e.g. in the entry "geben".

**Comment by Frenzie** [comment]
Shouldn't KOReader allow you to swipe left and right to look at other entries?

**Comment by ilyats** [comment]
@Frenzie I only see entries in other dictionaries that way, not other entries in the same dictionary.

**Comment by KenMaltby** [comment]
The recent operation of sdvc makes multiple, (numbered #/#) pages of entries that return more than one definition, within a dictionary.  I don't know what triggers that, but I suspect it is in part something within the dictionary file itself.  In other words it might take more a modification of the dictionary file, than KOReader or even sdvc.

**Comment by ilyats** [comment]
Cannot multiple entries be displayed by Koreader?

**Comment by KenMaltby** [comment]
I got that wrong, within the dictionary, it just numbers the returned definitions.  The page is scrollable to see all returned definitions in that dictionary.  The #/# shows which of the number of dictionaries with returns, you are on.

**Comment by alex125** [comment]
sdcv does not list multiple entries (and does not display inflections from the .syn file).
To fix both issues you can use penelope 
https://github.com/pettarin/penelope/releases (version 2.02)
to flatten synonyms and merge definitions.
If the dictionary is in files
dictionary.dict.dz, dictionary.idx, dictionary.ifo and dictionary.syn (optional):
python penelope.py -p "dictionary" -f de -t de --title "Title" --merge-definitions --merge-separator "<BR><BR>" --output-csv -i
creates the tabfile dictionary.csv that can be converted back to stardict with
/usr/lib/stardict-tools/tabfile dictionary.csv (under Linux if stardict-tools are installed in /usr/lib or use stardict-editor)

**Comment by Frenzie** [comment]
Upstream sdcv now has a new PR for exactly this: https://github.com/Dushistov/sdcv/pull/20

Unfortunately we cannot yet use upstream sdcv due to https://github.com/Dushistov/sdcv/issues/6

**Comment by ecraven** [comment]
It is a very simple patch, you can just import it, if you want. The main reason I wrote is to use it in koreader, so I'd be very happy if this was included in some way :D

**Comment by Frenzie** [comment]
The current KOReader sdcv is based on 0.4.x. It took me some time to port those patches over to the then current sdcv. That is, although obviously still simple, backporting might still take some effort. Of course if you're willing to do so (after review upstream) then I'll be glad to merge it. ;-)

**Comment by ecraven** [comment]
I'll look at it after it is merged upstream :-) Would be good to merge the two projects :-/

**Comment by ecraven** [comment]
Hm.. from looking at the code, it might be easier to unfork than to port the changes.
Is there an easy way to cross-compile upstream sdcv for the kobo? Then I could try porting the relevant commits from this to upstream (if I can test them on the actual kobo, to see whether things work correctly).

**Comment by Frenzie** [comment]
Thanks for your effort in getting the patches merged. On my phone but this might be helpful https://github.com/Frenzie/sdcv/tree/v0.5.4_beta4_koreader_changes

**Comment by Frenzie** [comment]
They work fine on Kobo. Android is the (potentially) problematic one.

**Comment by ecraven** [comment]
json support has been merged into upstream sdcv, what else is missing? if you can point me to specific commits, I'll try to get them into upstream too.

**Comment by Frenzie** [comment]
The last four commits in https://github.com/Frenzie/sdcv/commits/v0.5.4_beta4_koreader_changes and https://github.com/koreader/sdcv/commit/4455cf31bb4a424370e29d858dc07cf8d8f5de04

**Comment by ecraven** [comment]
https://github.com/Frenzie/sdcv/commit/4900907003c1d2aa0ac6c847c1f6c1db435ea6f1 is done, both of these are not printed if -j is passed.

**Comment by Frenzie** [comment]
Thanks! Almost there. :-)

**Comment by ecraven** [comment]
https://github.com/Dushistov/sdcv/pull/25
Is the non-fuzzy stuff actually used in koreader?
Are there additional patches necessary to make things run on various ARMs?

**Comment by Frenzie** [comment]
What additional patches? If I understand you correctly there's only https://github.com/Frenzie/sdcv/commit/b1f5bf15f3219c7b9a8dcccc1f31c763487b4bf5 and non-fuzzy

See https://github.com/koreader/koreader/pull/2934#issuecomment-306556276

**Comment by Frenzie** [comment]
Sorry, misread. I wouldn't know for current upstream sdcv but it seemed ok last year.

**Comment by ecraven** [comment]
can someone build it and try? or tell me how to invoke cmake to cross-compile current upstream sdcv for a kobo (where I can test it)?

**Comment by Frenzie** [comment]
I probably won't have time till Sunday and my laptop isn't set up for it
(not home).

There's
https://github.com/koreader/koreader-base/blob/master/thirdparty/sdcv/CMakeLists.txt
but you'd have to change it a bit (simplify)

if you mean stand-alone probably just setting the compiler should work?

**Comment by ecraven** [comment]
ok, only the non-fuzzy thing missing, I'll give that a go tomorrow ;)

**Comment by ecraven** [comment]
non-fuzzy search has been merged (-e for exact instead of -f): https://github.com/Dushistov/sdcv/pull/26
How do we proceed from here? Everything you guys mentioned has been merged into upstream, I think. Can we now use upstream instead of the fork?

**Comment by Frenzie** [comment]
Should be able to, yes. Updating base and then bumping here would do the
trick. :-)

**Comment by ecraven** [comment]
Any way I can help with updating base?

**Comment by Frenzie** [comment]
You'd have to update https://github.com/koreader/koreader-base/blob/c6c1bd512dfaf22bdf10c9f8a1a74665b27b78e0/thirdparty/sdcv/CMakeLists.txt and https://github.com/koreader/koreader-base/blob/4cecbeffc5089972fb7410d952bd8035c1b6007d/Makefile.third#L287-L309

It shouldn't be too difficult, but because sdcv changed to CMake itself it'll a bit more involved than just changing the URL and the commit hash.

**Comment by Frenzie** [comment]
My bad, I closed this prematurely. (And I don't mean because the updating sdcv part isn't quite a simple switch and go.) This issue is tracked upstream in https://github.com/Dushistov/sdcv/issues/30.

**Comment by Frenzie** [comment]
Closing in favor of https://github.com/koreader/koreader/issues/5168 which has a clearer title, and less confusing historical comments to wade through.

**Comment by ilyats** [comment]
As unbelievable as it may sound, the second issue is fixed as of v.2021.12.1-32

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/issues/5168 for more details. :-)
