### ISSUE TITLE
[inkBOOK] The window height is not correctly detected

### ISSUE THREAD

**Issue by marmistrz** [koreader/koreader#2952]
* KOReader version: koreader-nightly-20170308 (could not test on 20170430 due to #2947)
* Device: inkBOOK Classic 2

#### Issue 
There is blank space left at the bottom of the screen. If the screen is rotated to landscape, the content from previous portrait can be seen (stays there).

The space is roughly of the size of a top status bar on the inkBOOK device. Probably the height returned excludes this status bar, which is not displayed (covered?) by the koreader window.

#### Steps to reproduce
Open any book.

**Comment by Frenzie** [comment]
I'll close this in favor of #2876 (also see #2902). @mwoz123 is currently working on this in #2938.

**Comment by mwoz123** [comment]
@frenzie currently development is on hold. I don't have time, and Koreader doesn't create valid build  (working app) on my machine.

Hopefully I'll find time to finish #2938...

So if anyone wants to take over feel free to do it.

**Comment by mwoz123** [comment]
@marmistrz BTW, for now,  in #2876 there is workaround :

WORKAROUND:
create file /sdcard/koreader/patch.lua
with contents:
local screen = require("android").screen
screen.height = screen.height + 80
