### ISSUE TITLE
FR: add search in home folder to file search

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#2957]
* KOReader version: v2015.11-1057
* Device: Kobo Glo HD

#### Issue
I have a library containing 4000 books. They are placed in subfolders : Genre/Country/Author
The file name is the name of the book.
File search works only on a few books. Most of the time, the search results are empty.

**Comment by KenMaltby** [comment]
The "Find file" search in the File Browser of v2015.11-1052, seems to be working normally.

**Comment by Brnoch** [comment]
I changed the original SD card to a 64GB one. Could this explain the
problem?

2017-06-14 14:16 GMT+02:00 Ken Maltby <notifications@github.com>:

**Comment by KenMaltby** [comment]
Not likely, but if nothing else suggests itself, you might try an earlier KOReader version, in case something went wrong doing the update.  You want to get it working with some version to rule out any complication from the internal SD card upgrade.

**Comment by Frenzie** [comment]
Note that iirc it searches only in the current folder and subfolders of it,
not everything.

**Comment by Brnoch** [comment]
Thanks for the information. Problem solved! Sorry for this...

2017-06-14 15:38 GMT+02:00 Frans de Jonge <notifications@github.com>:

> Note that iirc it searches only in the current folder and subfolders of it,
> not everything.
>

**Comment by Frenzie** [comment]
That was the issue? Hm, it could be an idea to turn this into a PR to add a "search home folder" button or some such.

**Comment by Brnoch** [comment]
Yes, that was indeed the issue. Maybe the search button could be more
explicit : "Search a file in the present folder" or something like that ?
And it would be useful to have such a "search from home folder"
functionality : each time I go to the file browser, I have to go back to
the home folder, and that can be long as I have many subfolders.

2017-06-14 19:33 GMT+02:00 Frans de Jonge <notifications@github.com>:

**Comment by Frenzie** [comment]
Wait, there's set as home directory but not go to home directory? That's kind of its own issue.

**Comment by KenMaltby** [comment]
Perhaps a "Search from Home folder" button under the "Cancel" and "Find books" buttons, of the search box?  Maybe a Home icon on the left bottom, next to the << of the browser pages?

**Comment by robert00s** [comment]
Something like that?
![test - koreader_001](https://user-images.githubusercontent.com/22982594/42946357-f455e69e-8b6a-11e8-9db5-d4f309d498fb.png)

**Comment by KenMaltby** [comment]
Perhaps a divider line under the entry box.  Then the text "Starting from:" , then the bottom buttons as shown.

**Comment by robert00s** [comment]
That needs changes in InputDialog widget. I want to avoid it. But this is simple:

![test - koreader_002](https://user-images.githubusercontent.com/22982594/42958300-855ecaf6-8b85-11e8-8848-0e3e9f7c22e5.png)

**Comment by NiLuJe** [comment]
I'd hope that was obvious enough without needed to repeat the thing three times? :D.

**Comment by KenMaltby** [comment]
![folder_search](https://user-images.githubusercontent.com/14007369/42960370-21a4c09c-8b7b-11e8-9ec5-c1d1c47723fe.png)

**Comment by NiLuJe** [comment]
I still prefer the first version ;).

If you really, really, really want to tweak something I'd tweak the title: "Search for books by filename IN:"

But even then, that still feels a bit awkward with the "Cancel" button ;p.
