### ISSUE TITLE
[EPUB]/META-INF/calibre_bookmarks.txt content is displayed instead of book text

### ISSUE THREAD

**Issue by allati** [koreader/koreader#2959]
* KOReader version: v2015.11-1054-g6870bc2
* Device: Kobo Aura H2O

#### Issue
Instead of actual EPUB content Koreader displays [EPUB]/META-INF/calibre_bookmarks.txt content if this file is present and isn't empty. Book information is displayed with title "calibre_bookmarks", 1 page and all other fields with "N/A".

#### Steps to reproduce
1. View EPUB in Calibre (Calibre will add META-INF/calibre_bookmarks.txt to the EPUB)
2. Send it to the reader
3. Open this EPUB in Koreader. Something like `calibre_current_page_bookmark*|!|?|*4*|!|?|*/2/4[x978549601166]/2/74/1:47` is displayed (META-INF/calibre_bookmarks.txt content) instead of the actual book text.

I stumbled upon this behavior while trying to find out why Koreader segfaults when opening certain set of EPUBs. It segfaulted even if I tried to open book information using context menu command of the file manager).

These files were send to device by Calibre half a year ago. When I reuploaded them yesteday with recent Calibre version - Koreader crashed no more, but started to display bookmark files.

**Comment by gerhaher** [comment]
Same thing happened to me with a book.

Here are the book in question:
[Libertarianism_ What Everyone N - Jason Brennan.zip](https://github.com/koreader/koreader/files/1818661/Libertarianism_.What.Everyone.N.-.Jason.Brennan.zip)

**Comment by poire-z** [comment]
It's a problem in the epub detection by crengine. It can find the "mimetype" file entry in the zip file, but when it requests its size, it gets 0, and then fail reading the mimetype file, so it can't check if it is `application/epub+zip` as it should be for an epub.
https://github.com/koreader/crengine/blob/900d56dfc094c2a19a3a9b55a1502ecf36e248ca/crengine/src/epubfmt.cpp#L73

If you unzip your epub, and re-zip it, it works.
So, I guess it's a something with how the initial zip was made, and there's something that the zip reading code in crengine doesn't like (bug, newer zip features... dunno).

**Comment by gerhaher** [comment]
Thanks.
