### ISSUE TITLE
Crash on EPub Opening

### ISSUE THREAD

**Issue by Burrone** [koreader/koreader#2960]
* KOReader version: koreader-android-arm-linux-androideabi-v2015.11-1054-g6870bc2.apk
* Device: NOOK GlowLight Plus (version: 47.0.29 - Android 4.4.2)

#### Issue
When open any EPub file, KOreader crashes and the error pops up "Unfortunately, KOreader has stopoed." Other file like pdf, chm has no problem.

#### Steps to reproduce
v2015.11-1054 also fails on smart phone Android 5.1.1;

Try following nightly releases on NGP, crashes like the same;
v2015.11-1053
v2015.11-1055
v2015.11-1057
v2015.11-1058

1 case could work for now:
Install v2015.11-988 first, then upgrade it to v2015.11-1052.

**Comment by silberzwiebel** [comment]
I'm having the same isse (although without an error message) with an inkbook prime, android 4.2.2. Opening epub files crashes KOreader, PDF files are no problem. However, I can confirm that epubs work with the latest stable version (2015.11).

**Comment by zhliu0124** [comment]
Same here. It also crashes while opening mobi file.
v2015.11-894 is fine.
