### ISSUE TITLE
Footer M:# meaning? 

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#2964]
* KOReader version: all recent 
* Device: All that have this feature

#### Issue
What does the footer M:# mean?  I assume it is an indication of an amount of memory.  Is it the amount used or the amount left?  Is it a percentage used/left?  Is it from total installed memory.  Is it system or user memory, or both?  If is an amount, what measure is it, megabytes?

**Comment by Hzj-jie** [comment]
I believe it's the memory used by KOReader in Megabytes. I prefer to remove this indicator when system statistics plugin was added by change #2764, but @HouQP prefer to keep it as long as the memory leak has not been resolved.

**Comment by KenMaltby** [comment]
Seeing the memory usage can be a good look at the health of the running program.  
I guess I should close this.
