### ISSUE TITLE
[Android] Black rectangles instead of images in pdfs on Inkbook

### ISSUE THREAD

**Issue by ooree** [koreader/koreader#2967]
* KOReader version: v2015.11-1054-g6870bc2
* Device: Inkbook Obsidian e-ink reader (Boyue T63, more or less)

#### Issue
In pdf files, cover images, as well as some other images inside, are rendered as black rectangles.  The problem did not occur in version #894.

#### Steps to reproduce
Sample pdf file: https://accu.org/var/uploads/journals/Overload135.pdf
See pdf pages: 1 (cover), 12 (bottom left frame "Figure 1"), 18 (big upper right frame "Figure 1").

**Comment by Frenzie** [comment]
Fixed by #3262.
