### ISSUE TITLE
Swipe for menu moves page

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#2968]
* KOReader version: v2015-11-1054-..
* Device: Inkbook Prime (Android)

#### Issue
Swipe down for menu often move/scroll page (up or down - I don't remember).
It happens probably when "swipe" starts not precisely at the screen top edge of device, but rather few pixes below.
Menu is opened (as expected that's good), but before that you can see that page is scrolled.

#### Steps to reproduce
Open PDF file, swipe down (a little below top screen egde) to open Koreader menu.

**Comment by mwoz123** [comment]
Haven't seen that problem from couple releases. 

...Maybe because "tap for menu" is back and I'm using it;)
Closing.

**Comment by Frenzie** [comment]
Yes, the setting is a good thing.
