### ISSUE TITLE
Crashes on Nook GlowLight Plus ( Android 4.4)

### ISSUE THREAD

**Issue by bahusoid** [koreader/koreader#2976]
* KOReader version: koreader-nightly-20170612
* Device: Nook GlowLight Plus, Android 4.4, Firmware: 4.7

#### Issue
Frequent crashes. No particular action is needed. Sometime can't even open any book. See log:
[KOReaderCrashLog.txt](https://github.com/koreader/koreader/files/1089107/KOReaderCrashLog.txt)

**Comment by seacatwu** [comment]
I don't use Koreader in my android device(Ireader plus) for the same reason:)

**Comment by WinterL** [comment]
Same issue, randomly crashed on my ireader light which is an android 4.4.2 based ereader.
It seems easy crashed on epub, mobi, fb2, pdb. txt is only format which is not crash after I read 100 pages.
KOReader is very stable on my Kobo glo HD, but android version is not, I'm very appreciate developer and hope it will smoothly work on android device in the future.

**Comment by bahusoid** [comment]
It seems the problem is fixed with the following [test build](https://github.com/koreader/koreader/issues/3214#issuecomment-332106575). At least for me it's not crashing any more.
