### ISSUE TITLE
Duplicate wiki page?

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2980]
https://github.com/koreader/koreader/wiki/%E8%BF%9B%E6%AD%A5%E5%90%8C%E6%AD%A5
and
https://github.com/koreader/koreader/wiki/%E8%BF%9B%E5%BA%A6%E5%90%8C%E6%AD%A5
look exactly the same.

Except for the title, the former one looks strange: it means "improving synchronization". The later one is correct: "progress synchronization".

**Comment by Frenzie** [comment]
I kept both pages because as someone who doesn't speak or read the language all I can tell is that they're not precise duplicates. If you can merge them and delete one of them, please do.

**Comment by Hzj-jie** [comment]
If I have not made a mistake, there is only one different character. I opened this issue to ensure it's not an expected behavior, since I have zero background. E.g. if it is for tranditional Chinese. Though based on my very limited tranditional Chinese knowledge it's not.

**Comment by Frenzie** [comment]
I thought the content also contained differences. Anyway, don't forget to also remove it from the menu on the right. :)
