### ISSUE TITLE
ota.koreader.rocks does not update for several days

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#2982]
gitlab (evilly) updates the build lab download URL by (again evilly) using an HTML redirection. So we can only download a 193 bytes html file.

2017-06-24 06:55:09,099 root INFO     Running command: curl --retry 3 -C - https://gitlab.com/koreader/nightly-builds/builds/19652132/artifacts/download -o /data/19652132_artifacts.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   143  100   143    0     0    195      0 --:--:-- --:--:-- --:--:--   195
2017-06-24 06:55:09,930 root ERROR    Got invalid zip file: /data/19652132_artifacts.zip

The new URL looks like https://gitlab.com/koreader/nightly-builds/-/jobs/19652144/artifacts/download.

I am updating the nightswatcher.py to use the latest URL.

**Comment by Frenzie** [comment]
I imagine using an HTML redirect instead of HTTP is more lazily than evilly. :-P

**Comment by Hzj-jie** [comment]
Fixed.
