### ISSUE TITLE
Tapping in overlapping menu zone also turns page

### ISSUE THREAD

**Issue by protist** [koreader/koreader#2984]
* KOReader version: v2017.06.12-nightly
* Device: Kobo H2O

#### Issue
Perhaps related to PR #2932. Again, we can tap on `DTAP_ZONE_MENU` to open the menu, as opposed to having to swipe on it. However, if this zone overlaps with `DTAP_ZONE_FORWARD`, the menu is opened *and* the page is turned simultaneously. In the past (before the swiping menu was implemented), if these zones overlapped, the menu would open, but the page would *not* be turned.

#### Steps to reproduce
Tap on the region where both `DTAP_ZONE_MENU` and `DTAP_ZONE_FORWARD` are defined.

#### Expected behaviour
Menu should open.

#### Observed behaviour
Menu opens *and* page moves forward.

**Comment by robert00s** [comment]
Done in #2934 so we can close this issue.
