### ISSUE TITLE
Where to download the latest updates?

### ISSUE THREAD

**Issue by enigma90** [koreader/koreader#2988]
Are the latest updates no longer available for downloading? Can't find them at http://koreader.ak-team.com/

**Comment by Frenzie** [comment]
Try http://build.koreader.rocks/download/nightly/ :-) (although I don't now what's up with that other server; I think it's managed by @chrox)

**Comment by houqp** [comment]
ak-team is managed by @NiLuJe :)

**Comment by NiLuJe** [comment]
Yeah, I really, really need to update my mirroring script, sorry ;).
