### ISSUE TITLE
ko reader becomes unresponsive after opening a complex pdf

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#2994]
* KOReader version:latest nightly
* Device:kindle voyage

#### Issue
On opening a complex pdf , ko reader sometimes become slow and unresponsive.I am attaching the corresponding pdf file.
[lehs3ps.pdf](https://github.com/koreader/koreader/files/1117761/lehs3ps.pdf)

**Comment by Frenzie** [comment]
I'm not sure to what extent we can call that a bug. It's a very heavy PDF; even my desktop takes a couple of seconds to load it at first. But after initial loading cache kicks in.

I'll close this for now, but there is something about sticking UI in a different thread on someone's mind in any case. :-)

**Comment by Frenzie** [comment]
Let's call it a duplicate of #2929.
