### ISSUE TITLE
Screensaver displays inverted when Night Mode is enabled

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#2995]
* KOReader version: v2015.11-1073-ge67ff21
* Device: Kobo Aura One

#### Issue
When KOReader's Night Mode (inverting) is enabled, screensaver that is displayed when sleeping is also effected. It is expected that these are two separate components (and full screen pictures generally look bad when they are inverted)

#### Steps to reproduce
Open KOReader, set a non-empty screensaver folder, disable using book cover as sleep picture, enable Night Mode, press power button to sleep device.

**Comment by a-kohout** [comment]
Duplicate #2642 
See also #2571

**Comment by Frenzie** [comment]
Indeed, closing now.
