### ISSUE TITLE
Request ( Vocabulary Builder )

### ISSUE THREAD

**Issue by cmoig** [koreader/koreader#2997]
* KOReader version:
* Device: Kindle Voyage

Hi , so this isn't an issue ,it is a request , i would love to know if it is possible to add a feature like Kindle's Vocabulary builder to koreader , because that's the only reason why i have chosen Kindle over Kobo .

Keep the good work : )

**Comment by Frenzie** [comment]
What does it do exactly?

**Comment by cmoig** [comment]
Vocabulary Builder is a feature in Kindle E-reader ,which lets the user ,look back at the words he already looked up before in a book . It is a very important feature for language learners , i do hope it can be impleted in Koreader .


[Kindle's Vocabulary Builder](http://www.dummies.com/consumer-electronics/tablets/kindle/how-to-use-vocabulary-builder-on-your-kindle-paperwhite/)

**Comment by Frenzie** [comment]
So it's basically a less clear way to describe #2998? :-p

**Comment by cmoig** [comment]
Oh yes :D

**Comment by Frenzie** [comment]
I'll close this one then even though technically the other one is the duplicate. :-)

**Comment by cmoig** [comment]
yes , thank you for taking it under consideration :)
and also thank you for the amazing work you have done!!
