### ISSUE TITLE
FR: open document with compatible reader engine of user's choice

### ISSUE THREAD

**Issue by RailiQwan** [koreader/koreader#2999]
* KOReader version: koreader-kindle
* Device:kindle

Add to file: *:\koreader\frontend\document\**credocument.lua**
String: registry:addProvider("zip", "application/zip", self)

In order for the program to be able to open not only * book * .fb2.zip files, but also book files * book * .zip

Tnx!

**Comment by Frenzie** [comment]
Note that this would conflict with MuPDF, also see 507b989747119888073ed7d24548b345babfceba.

https://github.com/koreader/koreader/blob/dffa2f25637555749d942245e7561cb32e4baa29/frontend/document/pdfdocument.lua#L225

Perhaps ideally you should get a choice when you try to open a file that is compatible with multiple engines.

**Comment by Frenzie** [comment]
Whoops, I forgot all about this. I'll close it in favor of https://github.com/koreader/koreader/issues/3345
