### ISSUE TITLE
Gestures on Kobo Aura HD

### ISSUE THREAD

**Issue by emacsomancer** [koreader/koreader#3000]
* KOReader version: latest stable
* Device: Kobo Aura HD

#### Issue
Gestures do not work. For instance, the panning gestures or the zoom gestures.
#### Steps to reproduce
Try to use gestures. Nothing happens. (Or else the page turns rather than the zoom changing.)

**Comment by Frenzie** [comment]
What do you mean by gestures? I don't think the Aura HD has multitouch.

**Comment by KenMaltby** [comment]
I am assuming that this is in reference to PDFs, as panning and zooming on the fixed size scanned image on a document page, is how PDFs are handled in a number of PDF readers.  KOReader seems to be using a slightly different approach, that most are not used to.  The AuraHD is not multitouch, as I remember it, the Kobo implementation of the e-Ink IR touchscreen display only had about half of the ability to do multitouch.  @Giorgio130 looked into it once, as I remember it.

Luck;
Ken

**Comment by emacsomancer** [comment]
So is this just a limitation of the device then?  (Yes, I meant things like page-flipping mode gestures: https://github.com/koreader/koreader/wiki/Tips-and-Tricks )

**Comment by KenMaltby** [comment]
The "flipping mode" doesn't appear to require multitouch, given the Wiki description.   It works as described, on my AuraHD, in a first aid PDF.  Do you have the "zoom mode" set to "Zoom to fit page", after you have the open book icon in the top left corner?

**Comment by Frenzie** [comment]
Also works fine on my H2O. No multitouch (two fingers) required for that.

**Comment by emacsomancer** [comment]
>  In page flipping mode panning (moving your finger tip on the screen slowly) horizontally will flip pages with steps 1, 2, 5, 10, 20, 50 and 100 according to the panning distance, and panning vertically will flip pages proportionally (proportion to the whole page number according to the panning distance proportion to the whole screen height).

I can't get this to work ("panning").

[Also, is it really about multitouch per se?  I got screenshots to work which seems to require two finger detection, unless I'm misunderstanding.]

**Comment by Frenzie** [comment]
Screenshots are just diagonal, aren't they?

**Comment by KenMaltby** [comment]
Right Screenshots work with a single finger diagonal swipe.   (You could look into why the Glo seems to work some of the multitouch that is written for the capacitance screen Aura.  The light control for instance.) 
"Panning", as described in the Wiki for the Flip Mode, seems to be working fine with my AuraHD.  It is not however the same "Panning" that you may have used with other programs, it doesn't follow along as your finger moves.

**Comment by emacsomancer** [comment]
Somehow panning doesn't seem to be working for me on mine. Or, rather, given that you have it working, it must be that I'm doing it wrong.

I can take screen shots with the single finger diagonal swipe. However touching diagonally-opposing corners at the same time (i.e. with two fingers) ALSO seems to work for me on the AuraHD.

None of the zoom gestures work, but I suppose that's expected?

**Comment by Frenzie** [comment]
If by zoom gestures you mean pinching with two fingers, that's multitouch.

Touching two corners diagonally is probably just misinterpreted as a swipe from one edge to the other.
