### ISSUE TITLE
Setting default orientation to landscape ignores DLANDSCAPE_CLOCKWISE_ROTATION

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#3002]
* KOReader version: v2015.11-1073-ge67ff2a
* Device: Kobo Aura One

#### Issue
DLANDSCAPE_CLOCKWISE_ROTATION dictates which side landscape should rotate to, and which side is "reverse landscape". By default it's set to "true", however I prefer it on "false" (makes much more sense with Aura One).
However, this setting is ignored when setting the default document orientation to "landscape".
#### Steps to reproduce
1) Go to "Advanced settings" and set DLANDSCAPE_CLOCKWISE_ROTATION = false, restart KOReader and choose to save change
2) Open any document 
3) Go to orientation settings, long press "landscape", choose to set as default
4) Open a new document, it will appear in landscape but in clockwise rotation (which is the opposite of what you set in advanced settings)

**Comment by Frenzie** [comment]
Also see https://www.mobileread.com/forums/showthread.php?p=3571233#post3571233

Possibly relevant: https://github.com/koreader/koreader-base/blob/c89500f15eef751ede4942e67673bc89624c0fdc/ffi/framebuffer.lua#L287-L289

**Comment by RedRNG** [comment]
I encountered this bug too and it is kinda annoying, so here is a temporary solution for those who do not use the "switch from one landscape mode to another" functionnality:

Remove lines 290-292 (included) from the file /ffi/framebuffer.lua

**Comment by robert00s** [comment]
@pickx @RedRNG 
I think I have solution. 
In /ffi/framebuffer.lua try replace function **setScreenMode** to that (lines 306-323):

```
function fb:setScreenMode(mode)
    if mode == "portrait" then
        if self.cur_rotation_mode ~= 0 then
            self:setRotationMode(self.ORIENTATION_PORTRAIT)
        end
    elseif mode == "landscape" then
        if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
        or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED then
            self:setRotationMode(
                DLANDSCAPE_CLOCKWISE_ROTATION
                    and self.ORIENTATION_LANDSCAPE_ROTATED
                    or self.ORIENTATION_LANDSCAPE)
        elseif self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE
        or self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE_ROTATED then
            self:setRotationMode(self.cur_rotation_mode % 4)
        end
    end
end
```
Can you test it?

**Comment by RedRNG** [comment]
I tried your solution and it works, but I changed some lines so that it becomes more "clear". By that I mean you can remove the last elseif since "self.cur_rotation_mode % 4" = "self.cur_rotation_mode".

Here is the new code:

```
function fb:setScreenMode(mode)
    if mode == "portrait" then
        if self.cur_rotation_mode ~= 0 then
            self:setRotationMode(self.ORIENTATION_PORTRAIT)
        end
    elseif mode == "landscape" then
		if self.cur_rotation_mode ~= self.ORIENTATION_LANDSCAPE_ROTATED
		and self.cur_rotation_mode ~= self.ORIENTATION_LANDSCAPE then
			if DLANDSCAPE_CLOCKWISE_ROTATION then
				self:setRotationMode(self.ORIENTATION_LANDSCAPE_ROTATED)
			else
				self:setRotationMode(self.ORIENTATION_LANDSCAPE)
			end
		end
    end
end
```
The only problem is that we still lose the switch from landscape to landscape_rotated feature (when you tap twice on the "landscape" button in the menu).
However I doubt anyone is using this feature, so we need to discuss this with the others.

**Comment by robert00s** [comment]
Oh, I didn't know about switch from landscape to landscape_rotated feature

**Comment by robert00s** [comment]
Try this:

```
function fb:setScreenMode(mode)
    if mode == "portrait" then
        if self.cur_rotation_mode ~= 0 then
            self:setRotationMode(self.ORIENTATION_PORTRAIT)
        end
    elseif mode == "landscape" then
        if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
            or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED then
            self:setRotationMode(
                 not DLANDSCAPE_CLOCKWISE_ROTATION
                    and self.ORIENTATION_LANDSCAPE
                    or self.ORIENTATION_LANDSCAPE_ROTATED)
        elseif self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE
            or self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE_ROTATED then
            self:setRotationMode((self.cur_rotation_mode + 2) % 4)
        end
    end
end
```

Only add **NOT** before **DLANDSCAPE_CLOCKWISE_ROTATION**

**Comment by NiLuJe** [comment]
Could you post those as diffs against master (in those code-blocks, I mean), so it takes less effort to grok what changed at a glance?

(This stuff is mind-bending enough as it is... :D).

**Comment by robert00s** [comment]
This should work:

```
diff --git a/ffi/framebuffer.lua b/ffi/framebuffer.lua
index 9def2ca..528e083 100644
--- a/ffi/framebuffer.lua
+++ b/ffi/framebuffer.lua
@@ -310,13 +310,12 @@ function fb:setScreenMode(mode)
         end
     elseif mode == "landscape" then
         if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
-        or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED then
-            self:setRotationMode(
-                DLANDSCAPE_CLOCKWISE_ROTATION
-                and self.ORIENTATION_LANDSCAPE
-                or self.ORIENTATION_LANDSCAPE_ROTATED)
+                or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED then
+            self:setRotationMode(DLANDSCAPE_CLOCKWISE_ROTATION
+                    and self.ORIENTATION_LANDSCAPE_ROTATED
+                    or self.ORIENTATION_LANDSCAPE)
         elseif self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE
-        or self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE_ROTATED then
+                or self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE_ROTATED then
             self:setRotationMode((self.cur_rotation_mode + 2) % 4)
         end
     end

```

```
diff --git a/frontend/apps/reader/modules/readerview.lua b/frontend/apps/reader/modules/readerview.lua
index 8ad724d..fc313ea 100644
--- a/frontend/apps/reader/modules/readerview.lua
+++ b/frontend/apps/reader/modules/readerview.lua
@@ -699,7 +699,6 @@ function ReaderView:onReadSettings(config)
         screen_mode = config:readSetting("screen_mode") or G_reader_settings:readSetting("copt_screen_mode") or "portrait"
     end
     if screen_mode then
-        Screen:setScreenMode(screen_mode)
         self:onSetScreenMode(screen_mode, config:readSetting("rotation_mode"))
     end
     self.state.gamma = config:readSetting("gamma") or DGLOBALGAMMA
```

**Comment by sonix-github** [comment]
I tried the modification but this did not fix the issue. It is functional only if there are previous book screen orientation settings stored in .sdr folder. After purge.sdr the orientation depends on DLANDSCAPE_CLOCKWISE_ROTATION in advanced settings.

Now is my readerview.lua modified according above code and framebuffer.lua changed to this code:

elseif mode == "landscape" then
    if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
    or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED then
            self:setRotationMode(
						DLANDSCAPE_CLOCKWISE_ROTATION
            and self.ORIENTATION_LANDSCAPE_ROTATED
            or self.ORIENTATION_LANDSCAPE)
        elseif self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE
        or self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE_ROTATED then
            self:setRotationMode((self.cur_rotation_mode + 2) % 4)
        end
    end
