### ISSUE TITLE
Opening KOReader in Android auto sets screen to lowest brightness - can't see screen :(

### ISSUE THREAD

**Issue by justinkelly** [koreader/koreader#3004]
* KOReader version: v2015.11-1064-gbd92d68
* Device: Nexus 5X

#### Issue

When I opening KOReader in Android, it auto sets the screen to lowest brightness
- in sunlight I can't see screen :(
- in lighted room I can find the menu option to adjust the screen brightness to make it readable
- the screen brightness does not save- so next time I open KOreader it resets the brightness again to th e lowest possible :(

Please on Android can you leave screen brightness to the Android system, or make it optional, or something similar - but the current situation is not working well

Thanks!!!!!!

Jusitn

**Comment by Frenzie** [comment]
Do you know if this is new? Could be related to #2941.

**Comment by Hzj-jie** [comment]
Yes. I will fix it.

**Comment by justinkelly** [comment]
thanks @Hzj-jie

**Comment by Frenzie** [comment]
Fixed by #3319.
