### ISSUE TITLE
unicode font is not supported 

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#3005]
* KOReader version: kindle-arm-linux-gnueabi-v2015.11-1054-g6870bc2
* Device: kindle voyage and paperwhite

#### Issue Eventhough the epub file contains embedded unicode font , ko reader shows ? marks after opening the epub file in koreader. 

[satya-ke-prayog.zip](https://github.com/koreader/koreader/files/1138020/satya-ke-prayog.zip).

#### Steps to reproduce
just extrtact and copy  the attached file in document folder of kindle and text will be displayed as ???????? marks.

**Comment by frankyifei** [comment]
I check the source file, the epub does not have the font embedded. so I assume you need a right font to display characters. try turn off embedded style and use freesans, other fonts do not have your language according to my test.

**Comment by tarungupta2001** [comment]
You are right  but when i choose custom  hindi font or free sans there occurs a lot of grammitical mistakes.But the same book after converting to .mobi format is absolulely legible without any mstakes.also the book is intended to be used on variety of android device. and it is legible on any android device .the book contains mangal unicode font and even after copying the font in font folder of ko reader it is displayed as it was displaying with free sans.Thanks in advance.

**Comment by frankyifei** [comment]
you have to manually set the font you want to use in the font menu. clear the cache and try again

**Comment by NiLuJe** [comment]
We should have taken care of our unicode coverage for the majority of use-cases back in #3942
