### ISSUE TITLE
KOreader only sometimes appears as choice to open file (inkbook prime, android 4.2.2)

### ISSUE THREAD

**Issue by silberzwiebel** [koreader/koreader#3006]
* KOReader version: 201511-1054 aka 20170612 (also tried with 2015.11 stable, both times the .apk from github release page)
* Device: inkbook prime, android 4.2.2

Hi there,

I recently bought an inkbook prime (https://www.inkbook.eu/inkbook-primee) mainly for reading scientific papers (i.e., PDF files) and succeeded in installing KOreader which has great PDF(-reflow) support (although, by the way, inkbook's own reader does reflow PDFs astonishingly well. it just is too minimalistic with regard to nearly everything else ...).

Now I'm struggling with opening PDF files. Using KOreaders internal file browser works well; it opened any supported file I tried.
However, I have a large library of PDF files (almost 700 files). On the computer, I'm using the literature management software docear (https://www.docear.org) which helps me to organize these files into a meaningful structure using mindmaps.
On android devices, I'm using the app DroidPlane (http://benediktkoeppel.ch/technology/private-projects/droidplane/) with which I can browse my mindmap and open the PDF files (that are linked to each node on the mindmap).

Here comes the problem: Opening a PDF file via the DroidPlane app does not give me the option to open this file with KOreader. Only inkbook's own reader and Moon+-Reader (installed by me) appear in the selection. Interestingly, I can choose KOreader for the very same file when I use inkbook's file browser. After recognizing that the stable version of KOreader does not appear as a choice if the file name (or the path?) contains "strange"  character like "-" or "_", I suspected that KOreader has some bug that sometimes (for my use-case: always) prevents it from showing up at the app-choice.

You find example files (open the .mm file with DroidPlane) under https://kartoffelsalat.ddns.net:8001/f/73f778602f/?dl=1

I'm also in contact with DroidPlane's developer and the inkbook support, because it is not that easy to figure out where exactly something is going wrong. However, the app Moon+Reader is always showing up as a choice to open the PDF file -- so, KOreader must do something different (and I suppose: wrong) here.

Happy to provide any further information.

Thanks,
silberzwiebel

**Comment by silberzwiebel** [comment]
I was able to fix this problem. It turned out that the `AndroidManifest.xml` file from koreader seems to not cover all use cases. So, I looked for the `AndroidManifest.xml` from Moon+ Reader to see how they have done it. Given that I'm not 100% sure if this is legally okay (Moon+reader is not open source; however, I'm pretty sure that a proper google search or some android experience would result in a very similar manifest file), I'm only posting how I've done it but I'm not proposing a pull request (sorry, but I want to be on the safe side).
I suggest that someone with more android experience is able to change koreader's manifest file pretty quick.

So, here is the workaround if someone else has this problem in the meantime:

1. download the free moon+ reader apk from http://moondownload.com/download.html (or from google play using for instance the yalp store app)
2. use [apktool](https://ibotpeaches.github.io/Apktool/) to extract (and decode) the AndroidManifest.xml file
3. extract and decode the koreader apk file as well (recent nightly from github)
4. add to koreader's AndroidManifest.xml file all `<intent-filter>` nodes from moon+ reader's AndroidManifest.xml that have the string `pdf`inside at a proper place (where the other intent-filter is). I also copied the mimetype specifications.
5. recreate the koreader apk with `apktool -b`
6. sign the apk using steps 2 and 3 from [here](https://developer.android.com/studio/publish/app-signing.html#signing-manually) (unfortunately, you need to install the android sdk and build-tools as well creating a certificate to sign the apk; feel free to ask how I've done this)
7. uninstall koreader and install it again using the newly created apk. it now should properly appear as a choice to open PDF files from anywhere

**Comment by Frenzie** [comment]
Instead of bothering with that, does it work right with Document Viewer? https://f-droid.org/packages/org.sufficientlysecure.viewer/

**Comment by Frenzie** [comment]
For looking at the source I mean. ;)

**Comment by silberzwiebel** [comment]
yes, document viewer always appears in the "app choice" dialog. should I create a pull request with the additional intent-filter lines in the manifest? Or, since I don't have experience in android coding, you might be quicker in doing this and actually know more than me what you are doing ;) 
either way ...

**Comment by Frenzie** [comment]
Sure, go ahead. I'll comment on the PR. My only experience is that Android is stupid, see https://github.com/koreader/android-luajit-launcher/commit/2995500c418aa624476ad0f36315b2ac7d069662. I'd imagine this requires a similarly stupid workaround. :-P

**Comment by pazos** [comment]
Hi, just commenting here because the pathPatterns was removed entirely. It shouldn't be needed at all as long as the app that handles the intent fills the mimetype correctly. Anyways @silberzwiebel feel free to check your app and inform if I did break your workflow. Thanks!

**Comment by silberzwiebel** [comment]
Done with my PhD and so with this workflow ;) With koreader 2019.11 it still works, though. Thanks for thinking of me :)

**Comment by Frenzie** [comment]
Congratulations! :-)
