### ISSUE TITLE
Android: Toggling nightmode freezes it

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3007]
* KOReader version:
v2015.11-1078-g20ec1cd

* Device:
Android Inkbook Prime

#### Issue
Toggling the night mode back after some hours of device sleep always freezes it.

#### Steps to reproduce
toggle to night mode
press power to put the device to sleep
wait some time maybe half an hour to an hour
wake the device
toggle night mode back to normal mode (no night mode)
It is frozen

This is a regular issue for me. I read at night then in the morning when I try to toggle night mode back to dayligh use, it always freezes such that android needs to kill the process.

I am not sure if the logs here gives you any insight. Line 97-98 is when I pressed the "night mode" to toggle back. It does not seem to generate any real error not sure.

https://paste.debian.net/hidden/ca219799/

**Comment by Frenzie** [comment]
So toggling night mode on and off works fine as long as there's no sleeping in between?

**Comment by gerroon** [comment]
@Frenzie

I think it has something to do with sleeping. You are right if there is no sleeping in between togling does not crash it. And maybe I am facing the issue this way because that is my usual usage pattern. So looking into sleep might be good way to go with this.

**Comment by Frenzie** [comment]
```
I/KOReader(28094): WARN  got error waiting for events: ffi/input_android.lua:143: Waiting for input failed: timeout
```
This might be the key.

**Comment by pazos** [comment]
@gerroon I'm closing this issue, please feel free to re-open if you still have this problem on recent builds.
