### ISSUE TITLE
KOReader rocks server not updating

### ISSUE THREAD

**Issue by KenMaltby** [koreader/koreader#3009]
* KOReader version: All new versions
* Device: All

#### Issue
http://build.koreader.rocks/download/nightly/ isn't being updated, last nightly is from July 4th.

**Comment by poire-z** [comment]
There's been no new commit since July 3rd, so it's normal no nightly was build since then. But there should be one tomorrow :)

**Comment by Frenzie** [comment]
It's true. I've been too busy to do any computery stuff and apparently so has everybody else. Closing this now. :-)

**Comment by poire-z** [comment]
Seems no build today.
May be because of some outage on Gitlab side ("GitLab is currently experiencing storage issues", https://twitter.com/gitlabstatus ), as I remember houqp told us nightly builds depend on gitlab.

**Comment by Frenzie** [comment]
That's correct. You're probably able to check the status there even when
not logged in.

**Comment by houqp** [comment]
Sorry, I was also busy with work recently. Still trying to catch up on all the new issues and PRs. Is this still an issue?

**Comment by poire-z** [comment]
It's no more an issue: a nightly was built the next day (v2015.11-1082-gdffa2f2) and it is working fine.
(Glad to see you back :)

**Comment by robert00s** [comment]
There are no new versions for a few days. Is there any problem?

**Comment by Frenzie** [comment]
The builds are fine but clearly they haven't been uploaded onto the server. Unfortunately only my desktop's SSH key allows me to access it atm so I can't check up on it right now.

**Comment by robert00s** [comment]
@Frenzie 
Any news? :)

**Comment by Frenzie** [comment]
It's a disk space issue. Do you know any utilities like [Baobab](http://www.marzocca.net/linux/baobab/) for the command line?
