### ISSUE TITLE
setting PDF reflow to default gives broken layout

### ISSUE THREAD

**Issue by silberzwiebel** [koreader/koreader#3015]
* KOReader version:
* Device: inkbook prime (android 4.2)

#### Issue
Having PDF reflow enabled as default results in a broken view of a newly opened PDF (the text seems to be shifted to the left side and is cropped, there is blank space on the right side of the screen). Manually disabling and enabling PDF reflow again gives the correctly reflowed PDF.

#### Steps to reproduce
set reflow to default, close koreader, open pdf
I also played around with setting the scroll option default to off (because I do not want to have the same text on two different pages; not sure, if I got this option right, though). Potentially, this is related but I tried with scroll on/off as default and got this error always.

**Comment by Frenzie** [comment]
Isn't scroll off the default anyway?

I wasn't able to reproduce your findings with reflow on by default. I tried it on our test suite PDFs as well as  http://www.tldp.org/LDP/lkmpg/2.6/lkmpg.pdf from https://github.com/koreader/koreader/issues/2954#issuecomment-307833771 and this PDF document I like for testing things: http://www.oapen.org/search?identifier=626372;keyword=orthographies

**Comment by silberzwiebel** [comment]
hmm, I tried both of your PDFs and still have the same issue (do you need a picture?). I've clicked through several settings and turned them on/off so I can't remember whats the default. maybe I somehow made a strange setting so this bug appears? if so, where do I find log files that could help to debug?
Is it safe to remove the `settings.reader.lua`file to get everything default again?

**Comment by Frenzie** [comment]
> Is it safe to remove the settings.reader.luafile to get everything default again?

It should do exactly that, but that's also why I'd rename it rather than delete it so you can put it back right away if it doesn't help. ;-)

I'm not sure if Android saves log files anywhere or if you'd have to use logcat.

It'd look something like this:

```
07/20/17-14:29:18 DEBUG init scroll page states
07/20/17-14:29:18 INFO  setting zoom mode to page
07/20/17-14:29:18 DEBUG reflowing page 8 in foreground
07/20/17-14:29:18 DEBUG reflowed page 8 fullwidth: 540 fullheight: 1497
07/20/17-14:29:18 DEBUG init scroll page states
07/20/17-14:29:18 DEBUG get page position 0.77020708082832
07/20/17-14:29:18 DEBUG reflowing page 9 in foreground
07/20/17-14:29:18 DEBUG reflowed page 9 fullwidth: 540 fullheight: 1658
07/20/17-14:29:18 DEBUG init scroll page states
07/20/17-14:29:18 DEBUG get page position 0.77020708082832
07/20/17-14:29:18 DEBUG show widget ReaderUI
07/20/17-14:29:18 DEBUG refresh on physical rectangle 0 0 540 720
```

It might be useful to know if it mentions some really weird values.

**Comment by silberzwiebel** [comment]
ok, restoring the default setting brings back proper behavior (i.e., reflow is default ON, PDFs look default good). it might be that I've set also a different default on "zoom page to ...". I do not intend to investigate this more closely, because it works now for me. but I could look for the critical problematic setting(s), if you are interested.

however, toggling the scroll option does not give the desired effect. having scroll OFF still shows often the same sentence at the bottom of page p and at the top of page p+1. how could I disable this? should I open another issue, because it's not related to my first post here, I guess.

**Comment by KenMaltby** [comment]
In the Page Mode (not scroll mode, or with scroll mode off) "p+1" will most often still be part of "p", there is an overlap when "p" will not fit on one displayed screen.  Then "p+1" will display the bottom of "p" and enough of the top of "p" to complete the screen display.  That can include more than the one sentence you mention.

**Comment by Frenzie** [comment]
What @KenMaltby said. I'll close this now.
