### ISSUE TITLE
WebP images support on CBZ files

### ISSUE THREAD

**Issue by richmont** [koreader/koreader#3016]
* KOReader version: v2015.11-3-g9e0be45  
* Device: Kindle Paperwhite 3  

#### Issue  
When I try to open a CBZ with WebP files inside, file manager return to list of files.    

#### Steps to reproduce  
Put some of WebP files numbered in a zip, rename the file to "cbz" extension, put in Kindle storage, launch KOreader, open file manager, navigate to folder with the cbz file, try to open.  
  
Note: some of scanlators now is making the mangas with WebP format for fast and low bandwidth reading in browser, I have to convert every manga to jpg and repack in a zip for reading in KOreader.

**Comment by Frenzie** [comment]
Bubbles seems to do [something with WebP](https://github.com/nkanaev/bubble/blob/9f1e06cfa7a3827526d6945b626369b62f55c094/app/src/main/java/com/nkanaev/comics/managers/Utils.java#L69).

I've attached two files for testing (remove the .zip at the end) for those who are interested in implementing something like this.

[tmp-png.cbz.zip](https://github.com/koreader/koreader/files/1161148/tmp-png.cbz.zip)
[tmp-webp.cbz.zip](https://github.com/koreader/koreader/files/1161149/tmp-webp.cbz.zip)

**Comment by Frenzie** [comment]
Upstream issue: https://bugs.ghostscript.com/show_bug.cgi?id=697749

**Comment by Frenzie** [comment]
Upstream won't implement this, so I'm afraid we won't be seeing this.

https://bugs.ghostscript.com/show_bug.cgi?id=697749#c1
> WebP is not common enough to warrant adding yet another third party library dependency and code size.

PS JPEG2000 and JPEG XR are supported, presumably also in CBZ.

**Comment by k-aito** [comment]
Hello, I post here because I notice that https://bugs.ghostscript.com/show_bug.cgi?id=697749 got an update recently.

I don't know enough how to build it from scratch and implement it in KOReader. Would it be possible to have something like a beta branch where it is maybe enabled?

Cheers

**Comment by Frenzie** [comment]
I wouldn't count on the patch cleanly applying to our current version, cf. https://github.com/koreader/koreader-base/pull/1203

But we're probably not opposed to a PR that would build libwebp and apply/backport this patch, depending a bit on the weight of libwebp.

**Comment by winstonma** [comment]
@Frenzie I have many books that uses webp images. I converted all my epub images to epub because it is [supported in epub v3.3](https://www.w3.org/TR/epub-33/#sec-core-media-types).

I recently downloaded KOReader and the epubs are not compactible with KOReader. I would like to see if there are any way I could get that work.

May I ask one more question. Is it possible that KOReader uses the native system image decoder (e.g. WebP on Android)?

Thanks a lot

**Comment by NiLuJe** [comment]
> May I ask one more question. Is it possible that KOReader uses the native system image decoder (e.g. [WebP on Android](https://developer.android.com/studio/write/convert-webp))?

No.

**Comment by winstonma** [comment]
@NiLuJe Thanks

So can I say that KOReader have no short term plan to support epub v3.3. Thanks

**Comment by poire-z** [comment]
Cross ref to the issue with WebP images in EPUB : https://github.com/koreader/koreader/issues/9240#issuecomment-1162314957

It's not that we aim to support any version of EPUB. We support some features, we add some new support for stuff when we met books that has that stuff and it's either important (for me) or easy enough to implement.
I'm sure that there are some stuff in EPUB v1 and v2 that we don't support - so we can't even claim we support these old versions :)
But we support enough stuff to look like we do :)

**Comment by winstonma** [comment]
Thanks for the reply.

I converted all my books images to WebP so I guess I need to wait til the day KOReader support WebP. Thanks a lot

**Comment by Frenzie** [comment]
> depending a bit on the weight of libwebp.

A quick check suggests it shouldn't be much more than a few 100 kB. Not too bad.

**Comment by poire-z** [comment]
@Frenzie : if you can take care of the libwebp koreader-base addition and build (which are usually not my cup of tea), I could later see at integrating its support into crengine (lvimg is also not my cup of tea, but I'll drink that one :).

**Comment by Frenzie** [comment]
I'll think about it. I'm not particularly motivated to do so (and clearly neither is anybody else ;-) ) but I can probably simply copy, say, FriBidi and swap it for libwebp and it must Just Work™.

**Comment by poire-z** [comment]
> if you can take care of the libwebp koreader-base addition 

Well, I'm on it :)

**Comment by Frenzie** [comment]
Heh, just when my time became more available tonight and tomorrow. ;-)

**Comment by poire-z** [comment]
Oh, good ! That should be enough to finally bump MuPDF :)

**Comment by poire-z** [comment]
@NiLuJe : is there something specific about ffi-cdecl to handle inline functions defined in the .h ?
I have this in webp/demux.h:
```c
// Internal, version-checked, entry point.
WEBP_EXTERN int WebPAnimDecoderOptionsInitInternal(
    WebPAnimDecoderOptions*, int);

// Should always be called, to initialize a fresh WebPAnimDecoderOptions
// structure before modification. Returns false in case of version mismatch.
// WebPAnimDecoderOptionsInit() must have succeeded before using the
// 'dec_options' object.
static WEBP_INLINE int WebPAnimDecoderOptionsInit(
    WebPAnimDecoderOptions* dec_options) {
  return WebPAnimDecoderOptionsInitInternal(dec_options,
                                            WEBP_DEMUX_ABI_VERSION);
}
```

Adding `cdecl_func(WebPAnimDecoderOptionsInit)` in `ffi-cdecl/libwebp_decl.c` results in:
`int WebPAnimDecoderOptionsInit(WebPAnimDecoderOptions *);` in `ffi/libwebp_h.lua`,
and using `libwebpdemux.WebPAnimDecoderOptionsInit(dec_options)` in my `ffi/webp.lua ` fails as it isn't tound in libwebpdemux.so.2. There is only `WebPAnimDecoderOptionsInitInternal` in it.
Should I use `WebPAnimDecoderOptionsInitInternal()` and such (there are quite a few such inline wrappers) ? Or is there a way for ffi-cdecl to make these inlines wrappers available ?

**Comment by NiLuJe** [comment]
Yeah, that's a clunky ass API for ffi. Those aren't actual symbols, so, yeah, if they're not in the dynamic function table, you can't use 'em, so you'll need to reimplement them.

**Comment by poire-z** [comment]
Should be supported in tomorrow's nightly.

**Comment by winstonma** [comment]
Downloaded the nightly and it seems to me that WebP is working. Will try to read the WebP comics later.

I know it's off topic but I'd like to know which image format is supported in KOReader.

**Comment by poire-z** [comment]
In EPUB (and similar) books: JPG, GIF, PNG, WEBP (and very limited support for SVG).

As a single file image viewer: the same, plus:
https://github.com/koreader/koreader/blob/55c0fc6190d1be330b4efb9a8447982b6c52daee/frontend/document/pdfdocument.lua#L376-L394

**Comment by winstonma** [comment]
@poire-z Thanks

I guess it would be too soon for me to convert my comic/epub image into WebPv2/JPEGXL/AVIF
