### ISSUE TITLE
How to use this library for android?

### ISSUE THREAD

**Issue by zhjunliu** [koreader/koreader#3017]
* KOReader version:
* Device:

**Comment by Frenzie** [comment]
You can download builds from https://github.com/koreader/koreader/releases (assuming that by "library" you mean "program").

**Comment by zhjunliu** [comment]
I want to use this project in android like I use other Android Libraries (such as compile 'com.orhanobut:logger:1.15' in android studio),

**Comment by Frenzie** [comment]
You could build your own reader on top of https://github.com/koreader/koreader-base but I'm not entirely sure what it is you're asking. I wouldn't really know what you meant if you said you wanted to use, say, [AntennaPod](https://github.com/antennapod/AntennaPod) as a library either. :-)

**Comment by Dnkhatri** [comment]
The latest nightly crashes in my T63 Boyue android based reader Android ver 4.2.2 when I try to open an epub. Same version of Koreader work and is able to open the same file  on Nvidia shield android ver 7.0

**Comment by Frenzie** [comment]
I hope I managed to clear things up a little? If not, feel free to reopen. :-)
