### ISSUE TITLE
Short tap on mini progress bar doesn't do anything, Kobo Aura One

### ISSUE THREAD

**Issue by rjbergerud** [koreader/koreader#3020]
KOReader version: v2015.11-1023-g773e24f
Device: Kobo Aura One

#### Issue
The instructions here for changing the progress bar on the Kobo Aura One do not have any effect. 
 
https://github.com/koreader/koreader/wiki/Tips-and-Tricks#5-switching-progress-bar-states

#### Steps to reproduce
> Single tap on the mini progress bar will switch between various modes thereof. You can also use "Status bar" menu to show all this info at once. Long touch on the progress bar will invoke the "Goto page" dialog.

**Comment by Frenzie** [comment]
Note that it depends on **Settings** → **Status bar**. If you have "Show all at once" enabled, for example, it'll only turn on and off. I use Show all at once but I've disabled a few things that hold no value for me like "book time to read" and "chapter time to read".

Could you have any other custom settings relating to this?

**Comment by rjbergerud** [comment]
Hm, I haven't "Show All at once" enabled.  I actually got it to turn on and off now that I have "Show all at once" enabled, but most of the time the taps aren't working still most of the time.  It could be unrelated to this functionality, maybe my kobo is having trouble registering the taps at the edges for some reason.

**Comment by rjbergerud** [comment]
Hey, I just realized, I can get it working by taping just above the progress bar.

**Comment by rjbergerud** [comment]
I've added a small edit to the Wiki Tips and Tricks section to include this information.

**Comment by Frenzie** [comment]
I seem to recall there being a sensitivity testing program of some sorts (or maybe just an abused drawing program) people used to test sensitivity on their devices.

**Comment by Frenzie** [comment]
Closing now. :-)
