### ISSUE TITLE
Valid OPDS catalog not working

### ISSUE THREAD

**Issue by rjbergerud** [koreader/koreader#3023]
KOReader version: v2015.11-1023-g773e24f
Device: Kobo Aura One

#### Issue
"Cannot get catalog info from" is the error shown whenever I try to download an article from the arXiv OPDS catalog.  I can however still browse through categories and see what articles are available.  This is regardless of the fact that this is a valid OPDS catalog (see http://opds-validator.appspot.com/?uri=http://arxiv.maplepop.com/catalog/)

#### Steps to reproduce
1. Add the arXiv opds catalogue with url http://arxiv.maplepop.com/catalog/
2. Navigate to an article through the categories (e.g. Computer Science > Information Theory > [some article])
3. Tap on that article.  You will see an info box pop up with the error.

**Comment by KenMaltby** [comment]
Given where it happens I would guess that some sort of authentication/password might be required.

**Comment by Frenzie** [comment]
Some, like `Computer Science` > `Informational Complexity` are even more fun. They seem to load (cf., debug output) but don't update the displayed list. At least `Information Theory` has the decency to fail completely.

You can also get a nice crash by trying to Trying to go up after loading a category like  `Informational Complexity` twice.

I don't really have the time to debug this atm unfortunately, so if anyone feels the calling… ;-)

@KenMaltby I don't think Arxiv requires any kind of authentication?
