### ISSUE TITLE
[question] about the frontlight

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3026]
* KOReader version: 1082
* Device: kobo glohd

I was asking myself if it's possible to turn on / off the frontlight by touching the bottom left of the screen but without activating the swipe on the left part for the intensity.

This because I never change the intensity but I hold my reader with one hand , left, or right , it depends the situation. And it's easier to turn pages by swiping up / down (on the left or on the right side) with the thumb than swiping right/left.

Regards,
S

**Comment by cramoisi** [comment]
@Hzj-jie @Frenzie I made my own version of the plugin by disabling all swap related code (for warmth and intensity) inside it. It's not very friendly but it does the trick : only tap on left bottom corner is enabled and all other things (like intensity, warmth, etc) must be changed with the general frontlight menu.

**Comment by Frenzie** [comment]
Implemented by #4240.
