### ISSUE TITLE
Search calibre catalog from inside a book

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#3028]
* KOReader version: 2015.11-1054
* Device: Kobo Glo

I wonder what is the reason for not having the "Find book in calibre catalog" entry in the, otherwise very similar, Find menu while reading a book.

**Comment by KenMaltby** [comment]
You are not trying to find something within a book that you are reading.  You are making use of the calibre created and maintained catalog to find a file/book, using the indexed metadata and tags provided by calibre, from within the file structure calibre uses on your device.  It is another way to find a book/file to read, as is the file browser.

**Comment by embryo10** [comment]
But it is similar with  a Goodreads book search.
I don't use it myself, but it seems like this.
The Find menu is not just for "Find in the book" options, and that is how it is used in the file browser.
Even the "Find file" could be in the same menu.
I don't see a reason for the Find menu to be different in these two modes.
Anyway, I think it's convenient when searching for the next book to read, to save some clicks.
