### ISSUE TITLE
GoTo letter in file browser

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#3029]
* KOReader version: 2015.11-1054
* Device: Kobo Glo

In File browser, when I look in my books' directory, I have 84 pages of folders with author names.
It's difficult to calculate in what page the "M" letter will be so I can goto that page by number.
It will be very helpful if there was a way to goto page using that letter as input instead.

**Comment by KenMaltby** [comment]
Good idea.  Not sure how it will fit in with the ongoing "Cover Browser" file manager improvements. #2940

**Comment by robert00s** [comment]
My proposition:
In `plus button menu`

![koreader_071](https://user-images.githubusercontent.com/22982594/35196910-c1d99388-fed8-11e7-9290-60e69959899c.png)

![koreader_072](https://user-images.githubusercontent.com/22982594/35196912-c9ecde04-fed8-11e7-9e47-d5c935fd9e59.png)

**Comment by KenMaltby** [comment]
Go to filename starting with:

**Comment by embryo10** [comment]
Looks OK but it will be more useful to check for folders in the UI too.
I never had that many files in a single directory (usually books of the same author)
If it has to be only one of them, I would prefer folders ;o)

**Comment by Frenzie** [comment]
What @KenMaltby said. In any case the actual part of programming the go to letter part is surely harder than one interface or another. ;-)

Btw, maybe the long-press dialog could support both number and letter?

**Comment by embryo10** [comment]
@Frenzie That would be an even simpler interface..

**Comment by robert00s** [comment]
Better? (after long-press on bottom file manager page :)

![koreader_073](https://user-images.githubusercontent.com/22982594/35197321-c844cee0-fedd-11e7-9718-d6fef44f68b2.png)

**Comment by KenMaltby** [comment]
Might add a greyed out (a-z) to the prompt.

**Comment by Frenzie** [comment]
I don't think it's necessary to force the user to think about it, even if it's hardly a big mental strain.

```lua
-- quick sanity check of some sort
-- better yet keep the button grayed out until there's input?
if not input then return end

-- easy number check
local the_number_man = tonumber(input)
if the_number_man then
  -- it's a number man, cap'ain
else
  -- not a number man; do the to letter jam
end
```

**Comment by embryo10** [comment]
Getting better and better...

**Comment by robert00s** [comment]
@Frenzie What about when we want to search files or directories begin from number (eg. `2_part_of_my_book.pdf` or `2018_01_22.epub`)?

**Comment by Frenzie** [comment]
@robert00s That's an interesting point. Personally I'm more concerned about the folders @embryo10 already mentioned but I can certainly imagine someone naming their files or directories by date. (Although then you'd presumably want to go to where the entire date starts with `2018-01-21`.)

What do you think @embryo10 ?

**Comment by embryo10** [comment]
Hmm, thats true. Not very common, but it could happen..
If that has also to be addressed, it will take us back to the @robert00s last screenshot with the selection of "Go to page" - "Go to letter", which was OK already.

**Comment by KenMaltby** [comment]
I would see the "go to john" as moving the focus to the page that has the first file with john as the start of the file name.  You would still be in the File Browser pages.  A "search" would return a page listing all the files that start with john.   I would think we would want to stay in a "go to" mode, for this.

**Comment by robert00s** [comment]
Yes, we still be in the Filemanager and we return page listing all the files that start with `john`.

**Comment by embryo10** [comment]
So, is it search/filter or navigation?

**Comment by KenMaltby** [comment]
Would a search/goto for folders start from anyplace other than the File Browser "Home"?   Might that add/change something?

**Comment by robert00s** [comment]
@embryo10 only navigation
