### ISSUE TITLE
"Searching for..." dialog for dictionary lookup is redundant

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#3030]
* KOReader version: 2015.11-1054
* Device: Kobo Glo

Whenever I long-press a word to search in the dictionary I first get a blurring fast drawing of a dialog that says that it searching for the "whatever" word I long pressed, and after that the dictionary is opened.
Since I can't even read this properly (and I have an old Kobo Glo) and the extra drawing and re-drawing of the dialog square costs energy, could we just skip it?

**Comment by Frenzie** [comment]
I rather like the notification but iirc we compromised in changing it so
that the dialog would only show after 200-500 ms. That still has to be
implemented though.

**Comment by poire-z** [comment]
See https://github.com/koreader/koreader/pull/2934 : that "Searching for..." popup can be disabled by setting "Disable fuzzy search", now in the Dictionary settings menu.

**Comment by Frenzie** [comment]
I'm inclined to think that disabling fuzzy search is a highly undesirable side effect just to get rid of a little popup. Of course your mileage may vary. Obviously chrox thinks there's something to it. :-)

**Comment by embryo10** [comment]
Is fuzzy search the searching of the word with different endings?
If its that, I wouldn't like to disable it.
Maybe a configurable (even only in lua scripts) time threshold for the dialog to appear could be more handy.

**Comment by Frenzie** [comment]
Fuzzy search is the thing that matches `epuisante`, `épuisante` and `épuisantes` to `épuisant`even if only the latter has an entry in the dictionary. (Or sometimes, fuzzy search is the thing that matches `épuisant` to `lulz this word doesn't resemble the one you looked up in the slightest`.)

**Comment by embryo10** [comment]
Then we sure do need this most of the time (even if it gives some false positives).
About this delay... ;o)
