### ISSUE TITLE
Read timer entry with normal time format

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#3032]
* KOReader version: 2015.11-1054
* Device: Kobo Glo

I think it would be very useful if there was a way to input the time, for the Read timer to notify you, in actual HH:MM format also.
I prefer it from having to calculate how many minutes remain before 16:00.

**Comment by Frenzie** [comment]
I like it.

**Comment by robert00s** [comment]
I have prepared changes.
New sub menu
![screenshot 2017-09-20 17-35-29](https://user-images.githubusercontent.com/22982594/30653176-b0af9aee-9e2a-11e7-84e5-1417316cee80.jpg)
After select `time` we have choose time when KO should notify you.

![screenshot 2017-09-20 17-36-21](https://user-images.githubusercontent.com/22982594/30653217-cb6c6f6a-9e2a-11e7-848d-a64a919dd379.jpg)

After select `Minutes from now` we have "old" window

![screenshot 2017-09-20 17-37-01](https://user-images.githubusercontent.com/22982594/30653438-5d8ffcd6-9e2b-11e7-96b2-4695de7ce48e.jpg)

We can change it to timewidget or leave as it is.
![screenshot 2017-09-20 17-37-55](https://user-images.githubusercontent.com/22982594/30653507-8a9599fc-9e2b-11e7-946d-a24d54a6cfb8.jpg)

Stop timer in now available from sub menu.

**Comment by embryo10** [comment]
Looks very nice!
About the number entries, I think its faster to type 2 numbers (for 30) than press 30 times the arrow.
Is it possible to have the arrows (for fine tunning) but if we click on the number also get a keyboard to type?

**Comment by robert00s** [comment]
Thanks for the advice.
I changed `Minutes from now` to new timewidget... 

![screenshot 2017-09-21 20-12-27](https://user-images.githubusercontent.com/22982594/30711714-ea531dc2-9f09-11e7-8107-b8c493898cb8.jpg)
but you can click on number to get a keyboard to type.
![screenshot 2017-09-21 20-13-19](https://user-images.githubusercontent.com/22982594/30711713-ea29c0b2-9f09-11e7-8564-d9ddfbb3feb2.jpg)

**Comment by Frenzie** [comment]
Isn't it also the case that a long-press changes the numerical value by 10 or 15 or something? (Not disputing that you should be able to tap on the number, just pointing out an alternative means of interacting with the widget.)

**Comment by robert00s** [comment]
Long-press is still working :)
hours +/- 4
minutes +/- 10

**Comment by embryo10** [comment]
I didn't know about the long press action.
Nice to have it too!
Well, no more complaints ;o)
