### ISSUE TITLE
[Question] Refresh KeyValuePage window

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3035]
Is there any way to refresh the KeyValuePage window after launching a callback function, for example, after removing one field from the list? I want to add reset reading stats and need to remove selected book from KeyValuePage after reset (remove) book (#2920). Any ideas?
Thanks for help.

**Comment by Frenzie** [comment]
Just call `_populateItems()` like the previous page and next page functions?

**Comment by robert00s** [comment]
Unfortunately, it doesn't work.
When I run:
`KeyValuePage:_populateItems()` from main.lua (statistics.koplugin) I get error:
```

./luajit: frontend/ui/widget/keyvaluepage.lua:282: attempt to index field 'main_content' (a nil value)
stack traceback:
	frontend/ui/widget/keyvaluepage.lua:282: in function '_populateItems'
	plugins/statistics.koplugin/main.lua:1101: in function 'ok_callback'
	frontend/ui/widget/confirmbox.lua:97: in function 'callback'
	frontend/ui/widget/button.lua:180: in function 'action'
	frontend/ui/uimanager.lua:517: in function '_checkTasks'
	frontend/ui/uimanager.lua:668: in function 'handleInput'
	frontend/ui/uimanager.lua:762: in function 'run'
	./reader.lua:192: in main chunk
	[C]: at 0x00404750

```

**Comment by Frenzie** [comment]
Oh I should add that if you're calling it from outside you should probably make a refresh function 'cause _ is intended for internal use (although that shouldn't affect functionality).

You could always try destroying and calling it from scratch I suppose.

**Comment by poire-z** [comment]
Got the same error when I actually just put [KeyValuePage:_populateItems()](url) in some code.
And it's normal, like that, we're just actually calling a function, not the method of a specific instance, which has no self, and no self.main_content.
I see in stats plugin there are lots of [UIManager:show(KeyValuePage:new{ ...](url)
so your KeyValuePage instances are just instantiated and passed to UiManager:show(), and you have then lost reference to them.
You may need to instantiate them, keep the object, and call _populateItems on an existing object, like:
```lua
local my_kv_pairs = somestuff()
local zzz = KeyValuePage:new{ kv_pairs=my_kv_pairs... )
UIManager:show(zzz)
[... manipulate my_kv_pairs ...]
zzz:_populateItems()
```

**Comment by robert00s** [comment]
Thanks a lot guys :)
That's what I needed.

**Comment by Frenzie** [comment]
> so your KeyValuePage instances are just instantiated and passed to UiManager:show(), and you have then lost reference to them.
You may need to […] keep the object

My bad, I thought that was already the case. That's the same in every language and nothing Lua-specific. :-)
