### ISSUE TITLE
Android builds?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3038]
Hi

It seems like the build machine is not bulding Android apks for a while. Can we get newer Android builds please?

**Comment by Frenzie** [comment]
There seems to be some kind of XML error, but I don't know where it stems from (since nothing was actually changed since a week before it started failing…)

https://gitlab.com/koreader/nightly-builds/-/jobs/26511771

**Comment by mwozny123** [comment]
Actually [this one was first build that failed](https://gitlab.com/koreader/nightly-builds/-/jobs/23130595). It was 2 weeks ago (Jul 19 06:28).


[previous one (Jul 18 06:17)](https://gitlab.com/koreader/nightly-builds/-/jobs/22958481) was good   


was there any update around SaxParser ?

BTW why all those builds (at least last month) show the same commit version 9cc1fec7?

From [Koreader git history](https://github.com/koreader/koreader/commits/master) might be one of these:
Commits on Jul 18, 2017 f95c52f680940c70f125b90ef8e893d6442c0729
Commits on Jul 19, 2017 d6845d94b1486632096f64f42a42a6fa02c5340c

**Comment by Frenzie** [comment]
Well, in that case the problem's obvious. ;-)
