### ISSUE TITLE
[feature request] support https urls in news (RSS / Atom) downloader

### ISSUE THREAD

**Issue by silberzwiebel** [koreader/koreader#3041]
* KOReader version: latest nightly release
* Device: inkbook prime (android based)

#### Issue
https feed urls do not work in the news downloader. This is a known limitation as its written in the file that it's currently unsupported.
I couldn't find an issue for that and therefore open this one.
Would be grateful if someone implements this.

**Comment by mwoz123** [comment]
As I mainly gave the idea + some basic lua programming (I nearly don't know lua at all) so @houqp had to correct /fix/improve the code, and I'm not the right person to ask for implementation. Sorry :/

**Comment by Frenzie** [comment]
@silberzwiebel Any sample HTTPS feeds?

**Comment by silberzwiebel** [comment]
https://www.proasyl.de/news/feed/

**Comment by Frenzie** [comment]
Alright, I'll give it a look.

**Comment by Frenzie** [comment]
I realized there was one right at hand: https://github.com/koreader/koreader/commits/master.atom

Anyway, I've got the HTTPS working (like I thought, that was simple) but I ran into a problem where it's not recognizing the feeds as valid.
