### ISSUE TITLE
Build Koreader for Android x86 architecture? 

### ISSUE THREAD

**Issue by mwozny123** [koreader/koreader#3046]
Is there a way to build Koreader for _x86_ android architecture(instead of _arm_)?

Android **x86 emulator is "10 times faster than arm".** (Android Studio says so, and I can confirm that;)

Currently for fresh Ubuntu 16.04.2 LTS + latest Android studio (android-studio-ide-162.4069837-linux.zip) I'm not able to see logs ( #2654):

```
$ adb logcat
Unable to open log device '/dev/log/main': No such file or directory
```

Workarounds: [Dialing](https://stackoverflow.com/questions/6941710/unable-to-open-log-device-dev-log-main-no-such-file-or-directory) `*#*#2846579#*#*` shows nothing, also there's also no such dir as /system/etc/init.d

For x86 android emulator I was able to see logs.

**Comment by Dnkhatri** [comment]
The nightly for koreader android any architecture is not working if you could fix that maybe could get it to build for x86 architecture as well
https://gitlab.com/koreader/nightly-builds/-/jobs

**Comment by Frenzie** [comment]
The build failing (well, more the putting together the package than the *build* as such) is issue #3038.

**Comment by mwoz123** [comment]
@Dnkhatri "not working" is not the problem here as I'm on my branch (probably behind master)  that is working. 

Any one knows if there's an option to build x86 android app? 

It should make development for android much faster, easier etc.

**Comment by Frenzie** [comment]
I'll close this in favor of #1815.

I suspect you'd need to do a little more than merely change these two lines but that's the kind of thing you'd need to work on if you want to add Android x86 builds: https://github.com/koreader/koreader-base/blob/c6c1bd512dfaf22bdf10c9f8a1a74665b27b78e0/Makefile.defs#L53-L54
