### ISSUE TITLE
Feature Request - "pop up footnote"

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#3054]
The Kindle shows a pop up if you click at a footnote
If someone can create some similar system with epubs @ koreader I will be pleased.
Thanks

![p_20170806_175116](https://user-images.githubusercontent.com/20425689/29006968-62442c76-7ad0-11e7-8345-aac2b3991d3e.jpg)
![p_20170806_175148](https://user-images.githubusercontent.com/20425689/29006969-62460e6a-7ad0-11e7-83d7-5165d4aa9d00.jpg)
![p_20170806_175137](https://user-images.githubusercontent.com/20425689/29006970-624bfaaa-7ad0-11e7-91b7-8927fedcaa35.jpg)

 "Nota de rodapé" means footnote

**Comment by Frenzie** [comment]
Huh, apparently GH's thumbnails don't take rotation into account. Weird. Anyway, here's what i learned after a quick search.

Link to spec: http://www.idpf.org/epub/30/spec/epub30-contentdocs.html#sec-contentdocs-vocab-association

Link to document for regular readers: http://www.pigsgourdsandwikis.com/2012/05/creating-pop-up-footnotes-in-epub-3-and.html

**Comment by Frenzie** [comment]
@poire-z Since you're really active on crengine atm, I wonder if you know how difficult something like this would be? The first part, getting the content of the linked footnote, may not be too hard:

```html
<aside epub:type="footnote" id="n1">
<p>These have been corrected in this EPUB3 edition.</p>
</aside>
```

If we had that, we could pop up an MuPDF RichTextWidget… just brainstorming.

**Comment by poire-z** [comment]
It's easy to get to the node with such id, and to navigate children, but at this point, these nodes are all crengine objects. I don't think I've seen anything in crengine code to serialize these objects (or anything) back to HTML.
Also, when thinking about that in the past, i've look at some epub of mine, and some of them did not have such a note container: they were more like that:
```html
<aside id="n1"/>1.</aside>
<p>These are crappy notes, but well, these are notes nevertheless.</p>
```
So, even if you get the node with that ID, you're not sure you'll always get the note content (and you don't know how many siblings, that you could grab, are about this note)... and with that kind of book, you'd be displaying just "1.".

I don't think I'd like these footnotes in a popup window (displayed by MuPDF I guess, so probably with different fonts and layout that main document).
Could probably be easier to get the slice of the document (rendered by crengine, think scroll mode) for this note, and display it as an overlay over current page (like in screenshots on first post here). But what to do when the slice is big and longer?

There is support for displayed-at-bottom-of-each-page notes in crengine (see lvpagesplitter.cpp), but I think there's support for them only with fb2 (even with sample fb2 found on the web, I never managed to witness how it looks).
But although these look pretty, I'm not a fan: sometimes, you're reading a footnote that span multiple page, and you have to find your way back.

Personally, I'm very happy with the swipe to follow nearest link / swipe to go back, and the little markers (and I think this combination, with our touch devices, is a far better solution that the previous options).

**Comment by Frenzie** [comment]
I agree that it's very unproblematic, particularly after I moved "back to previous location" to the top level menu. But it seems to be very popular and it sounded potentially simple.

This fb2 thing is intriguing though. I had no idea something like this was already in crengine. Pity I have no idea where to get relevant demo documents. Any idea what these things are? https://github.com/gribuser/fb2

**Comment by poire-z** [comment]
There's lot of parsing code for such `<FictionBook>` tags in crengine, I guess fb2 (Fiction Book 2 ?) is just XML, and these are the schema specs :)

**Comment by poire-z** [comment]
> I don't think I've seen anything in crengine code to serialize these objects (or anything) back to HTML.

Actually, I did see something (there is commented debug code to save DOM tree to /tmp/ files) to serialize a node (and its children) back to HTML:
https://github.com/koreader/crengine/blob/052637f1f4ca831fd03aafab89df8358d8ca0f49/crengine/src/lvtinydom.cpp#L3009-L3102

So, it shouldn't be too hard to add a `getHtmlContentFromXPointer(xp)` in cre.cpp if you'd like to play with it.

**Comment by Frenzie** [comment]
Not badly, but it just sounds so simple in principle to do something not unlike the HTML dictionary popup. Pinging @TnS-hun to spark interest. ;-)

There are quite a few `#if 0`s in that file to comment out code. https://stackoverflow.com/questions/2852913/what-exactly-does-an-if-0-endif-block-do

**Comment by poire-z** [comment]
I'm having a go at this.
Not sure I'll personally be using it, but as I'm adding a `View HTML`  to the selection menu so we can [inspect the HTML and styles ](https://github.com/koreader/koreader/pull/3944#issuecomment-421562673), I have added to crengine a way to fetch a node's (or a range between nodes') HTML.

So, we can fetch some HTML from the node that a link is pointing to, and feed it to MuPDF like it's done for HTML dictionaries. It won't be the same formatting/font/contrast as the main book text (but we may be able to use the same font size). Also, links and backlinks won't work.

I noticed while testing what [I mentionned above](https://github.com/koreader/koreader/issues/3054#issuecomment-370925507) : we may not always fetch the whole footnote content with some (possibly bad) books - but it seems to work in 80% of my tested books.
So, it could be made an option for people who prefer popups.

So far, I have it in a centered popup:
<kbd>![image](https://user-images.githubusercontent.com/24273478/45900791-0725a900-bde1-11e8-812a-cb18b1c42e1c.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/45900722-d0e82980-bde0-11e8-977c-d1594941d55b.png)</kbd>

I'm wondering where to go from there, what people prefer, if some option has more caveats than the other:

I see 2 options:
1) having it in a small popup that would adjust its height to the content height (so a small footnote like `ibid. p57` is 2x1cm) and try to display it just below (or above if the link is too down in the page) the link.
2) having it displayed at the bottom like the screenshots in the first post of this issue, with probably its height adjusted to the footnote height to avoid that big blank area.
3) any other?

For both options, enforce a max height of 1/3 of screen, put scrollbark if overflow.
What about width?
I think we won't need any title mentionning `Footnote` or `Nota de rodapé` and no close button (just tap outside should do).
But I think we need a button/text, possibly an overlay over the MuPDF HTML, to follow the link the classic way and jump to the page where the link is, so we can see the whole footnore with the full crengine rendering and the ability to use dict lookup, follow other links, etc...

If 1), should the footnote be movable (if we want to see again what it hides)? If yes, we need a bit of room around or on some sides as a handle for the move (as swiping from inside is eaten by the scrolling)

We still have to distinguish a footnore from a link to a chapter (eg: links in the in-page TOC in a Wikipedia EPUBs are not distinguishable from a link to a footnore), to decice if we should use that popup or follow the link the classic way (or we would be displaying a full chapter in a small popup :).

Kobo describes what they do in https://github.com/kobolabs/epub-spec#footnotesendnotes-are-fully-supported-across-kobo-platforms
Of interest:
- The content in the node is nine characters or more once stripped of the HTML tags. Ex.
`<p id="uniqueID">123456789</p>` (*)
- The node being linked to is less than or equal to 5000 characters.
- The location being linked to comes after the location being linked from. Ex. A reference in Chapter 2 links to a location at the end of the file titled Endnotes or a reference at the beginning of Chapter 2 links to a location at the end of Chapter 2.

(*) Not sure about the 1st one, may be it's to catch _wrong_ links to a node that contain just the backlink with only a number as its text - so, we would get a small string like `17` and we won't get the real footnote text that is in an inline node after that. So it's for avoiding that?
I have made that case work a little bit better (that just getting the xpointed node HTML content) by trying to find a parent node that is rendered final (the first parent that is `display: block`) - that is, that make a paragraph, a slice of a crengine page. We could optmimize it even a bit more by trying to find a parent node that is a `<aside>` tag for the EPUB3 that would do that correctly.

Any thoughts, advices, experience with other reading software or devices...?

**Comment by Frenzie** [comment]
> as I'm adding a View HTML to the selection menu

Wow! :-)

> Any thoughts, advices, experience with other reading software or devices...?

Not really, besides the hovering thingy on Wikipedia I don't encounter this kind of thing too much.

![screenshot_2018-09-21_22-00-01](https://user-images.githubusercontent.com/202757/45903377-cbdba800-bde9-11e8-94b3-d8ab62299a2b.png)

**Comment by NiLuJe** [comment]
I kinda like the foonote approach of the Kindle's UI (so, full-width pane on the bottom), and found it quite usable, without disrupting the UI like a popup in the middle of the screen tends to feel.

Then again, there may be an argument to be made for that behavior to match the dictionary/wikipedia popup?

**Comment by Frenzie** [comment]
What happens on the Kindle if your footnote text is at the bottom of the page?

**Comment by NiLuJe** [comment]
I don't think it reflows the underlying page (so it's a "dumb" overlay). i'll double-chekc, though.

**Comment by NiLuJe** [comment]
Yep, as I remembered ;).

Page: 
![page](https://user-images.githubusercontent.com/111974/45904016-ee6ec080-bdeb-11e8-9a7b-80488c4c5045.png)

With Overlay:
![foot](https://user-images.githubusercontent.com/111974/45904023-f3cc0b00-bdeb-11e8-85a8-9ed30498a63f.png)

With a scrollbar if overflow:
![scroll](https://user-images.githubusercontent.com/111974/45904031-fcbcdc80-bdeb-11e8-82ca-2ba00921e2e1.png)

**Comment by NiLuJe** [comment]
And apparently, we wouldn't be the only ones throwing the "match that w/ the dictionary behavior" concern out the window:

![dict](https://user-images.githubusercontent.com/111974/45904720-237c1280-bdee-11e8-9a7b-11f4c3380c13.png)

;).

**Comment by NiLuJe** [comment]
Note that *that* one is context-aware: it'll jump to the top or the bottom depending on where the highlighted word is, so the word, the contextual menu strip, and the popups are all visible.

**Comment by poire-z** [comment]
> Note that that one is context-aware

Our Dictionary does that, a bit weirdly at times: when the word is near the top or near the bottom: it goes nearer to it. But it does nothing when the word is in the middle: it just displays over and hides it. How does Kindle (I assume it's Kindle) do in that case ? Is the dict window height always < 1/2 so it can be displayed above, and leave room below for the menu?

> I kinda like the foonote approach of the Kindle's UI (so, full-width pane on the bottom)

And probably easier to code :)
(Probably more convenient for the way I usually use the reader, one handed from bottom right, so taping the bottom area to change page: I could then just tap in the same area to scroll the footnote, and just extend my taping finger over it to close it - instead of having to possibly over-extend or use the other hand to reach a highly positionned popup to scroll the popup.)

> What happens on the Kindle if your footnote referencing text is at the bottom of the page?

How should we deal with that? Just be dumb and hide it, or slide the pane up till the original link is visible?

**Comment by Frenzie** [comment]
> How should we deal with that? Just be dumb and hide it, or slide the pane up till the original link is visible?

Intuitively I should moving it up sounds like it would be the "should" scenario, but at the same time then you'd have a popup that always goes at the bottom except when it potentially seemingly randomly doesn't. And it is of course easier not to do any special case detection...

**Comment by NiLuJe** [comment]
@poire-z: Yep, it's always small enough to be placed properly (you basically have a single line with the highlighted word sandwiched between the menu and the popup).

----

I don't think potentially overwriting the context is an issue: after all, the current solution is a full jump to a complete different section of the book ;).

**Comment by Frenzie** [comment]
After a night's sleep I'm envisioning all these complex things, like how in Evince (and derivatives) you can press <kbd>Ctrl</kbd>+<kbd>N </kbd> to open another copy of the document on the side to keep the footnotes in.

I normally do that with bookmarks, or if I'm at home I might even just grab my computer/laptop on the side.

But never mind that for now. :-D

**Comment by poire-z** [comment]
A little update on this: it should be coming well, but I've been sidetracked by a few other things to fix and features to implement, that there will be quite a few PRs, with possible new bugs :)
So, @Frenzie , if you feel like releasing a beta soon, please do before I push that new stuff.

The state of it:
<kbd>![image](https://user-images.githubusercontent.com/24273478/46559345-61019500-c8f0-11e8-900f-58cb3bcdfbc5.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/46559410-9312f700-c8f0-11e8-8378-9c390c74f1f7.png)</kbd>

With larger margins and a smaller font size:
<kbd>![image](https://user-images.githubusercontent.com/24273478/46560325-9360c180-c8f3-11e8-93ad-a2a163131326.png)</kbd>

And no button, just swipe to the left to follow this footnote in the book, swipe south or tap oustide to close it.

Other features coming:
As my tap success rate on such small footnote links was very low, I added a few menu items:
<kbd>![image](https://user-images.githubusercontent.com/24273478/46560436-0b2eec00-c8f4-11e8-9097-3e9356ae3154.png)</kbd>

For the now non-precise tap to work, I needed to re-use `ReaderLink:onGotoPageLink()` (already used by `Swipe to follow links`) to find the nearest link. I then noticed that the distance calculation was wrong as it just calculate the distance to the start and end points (so, if you tap on the middle of a long link, you're too far from its start or end and it would no work...). We were also missing the first link on the page if it started on previous one.
For that, I needed to add stuff to get a segment for each line the link spans, and calculate distance to each segment - and I realized we could use that for a cleaner highlighting of text, without losing puncutations on page edges.
Then, testing with CJK, I discovered that the CJK highlight is (and was already previously) not highlighting the last char on the right... so fixed that (and fixed the segfaults it introduced...)
Then, back to the footnote, and if the UI stuff was fun, detecting if a link is to a foonote was less, and got quite long (got inspited by how calibre does that). And many infinite loops to fix in the various DOM inspection stuff...
And the `View html` in the selection menu.
<kbd>![image](https://user-images.githubusercontent.com/24273478/46560545-75479100-c8f4-11e8-9254-6aa1ae162f1d.png)</kbd>

So, much stuff...

**Comment by Frenzie** [comment]
I bumped base myself for the Pocketbook Lux just a few days ago, so that should be good. ;-)

In any case I just wrote the release note, so I'll just wait to attach tomorrow's nightly binaries and then it should be good to go.
