### ISSUE TITLE
large nested epub file table of contents entries disappear and re-appear

### ISSUE THREAD

**Issue by ottawadeveloper2** [koreader/koreader#3062]
* KOReader version: koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1087-gba96506
* Device: kobo aura(original)

It is awesome to find that multi-level table of contents are supported in koreader. I plan to make good use of that.

I have an epub document i have created with a lot of small files inside. Something like 1400 files. 
I have created a .ncx file with 3 levels of nesting. Documents are listed more than once, organizing them in different way.

What i find is when i expand some of the later sections in the table of contents, the items appear correctly. However when i collapse the same section, then some following sections disappear on the table of contents screen. I can re-open the .epub file and missing entries re-appear. If there is a higher level section containing the problematic portion of the table of contents, if i contract and then expand this, then also the lower level stuff gets fixed.

I did try the sample file i found here, juliet.epub. This has a similar structure in the table of contents, and it works fine on the kobo. 

I wonder if there is some limit i am hitting here about number of sections? 

I also have viewed this same epub with other tools and it works fine there too.

**Comment by Frenzie** [comment]
I think (though I'm not 100% sure) that I've used EPUBs with 3 levels of nesting before.

**Comment by ottawadeveloper2** [comment]
thanks. Problem exists with just 2 levels, like the juliet sample. adding a 3rd level provides a partial workaround as it sometimes can restore missing entries. My thought is that it might relate to the total number of entries being large, not so much about how many levels.

**Comment by ottawadeveloper2** [comment]
I have made a workaround. TOC looks like below. Sometimes if i open an close sections like 'A', sections like B disappear. The workaround is to close then open 'Groups' and then all is well again. The table of contents is otherwise working most excellently and better than most ebook readers for supporting multi-levels with expand/contract.

This leaves me to suspect that the table of contents is fine and can be displayed fine, but that when a section is closed like A, the remainder of the screen is not fully drawn correctly.

Groups
      ByTitle
             A first letter
                      aItem1
             B first letter
                      bItem1

**Comment by Frenzie** [comment]
You could try changing this line to `partial` or something to see what happens.

https://github.com/koreader/koreader/blob/06d7eea507785b909e6491e179d783c051e4fa23/frontend/ui/widget/menu.lua#L695

See [here](http://koreader.rocks/doc/modules/ui.uimanager.html#UIManager:setDirty) for more information.

**Comment by ottawadeveloper2** [comment]
thanks for the hint, i tried "partial" and "full". Full slows it down. Both continue to have the same issue.

My previous post lost the indents, should have looked like this to show the levels.
Groups
.....ByTitle
..........A first letter
................aItem1
..........B first letter
...............bItem1

**Comment by ottawadeveloper2** [comment]
Here is a better explanation...
See the menu shown below.
If you expand B in group 3, then contract it, items like C, D are missing, so after B is E. 
Screen looks good, so fully refreshed, just a few items have been removed.
group1 seems fine, no issues at all. in group 3 and 4 i can see the issue, not sure about 2. 

Groups
.....ByTitle-Group1
..........A first letter
................aItem1
..........B first letter
...............bItem1
.....ByOther-Group2
.....ByKey-Group3
..........A
................aItem1
..........B
...............bItem1
..........C
...............bItem1
..........D
...............bItem1
..........E
...............bItem1
..........F
...............bItem1
.....ByAuth-Group4
..........A first letter
................aItem1
..........B first letter
...............bItem1

**Comment by Frenzie** [comment]
You can use ``` (on a line before and a line after) to keep all indentation.

I can't seem to reproduce this on my H2O though (but maybe it just refreshes faster). Is there a sample document where it occurs reliably?

**Comment by ottawadeveloper2** [comment]
Thanks for your attempts. I did a reduced size .epub and could not see the issue. I will investigate a bit more here - in case maybe there is some bad data somewhere. I will see if i can get you such a sample. It may take a while as i will be away a bit in the next while.

**Comment by ottawadeveloper2** [comment]
Well i am puzzled, the problem seems too inconsistent. With the top level folder i have a good 
workaround when there are issues, so it is working well for me. There is a chance that somewhere there 
is some bad data that is causing issue in my .epub. If i figure it out i will attempt to get a sample to you.

One very minor thing that does seem consistent, in the example i displayed above,
if you expand some sub-section, for example group3, then you contract the top level 'groups', 
then expand it again. All lower sections will be closed but thee little arrow indicators beside
will point incorrectly, indicating them as expanded, but they are no longer expanded. 
Easy to resolve, press the arrows that are wrong twice, to contract then expand again.

One other thing i did note(unrelated), cloudstorage.lua - line 29. This screen appears too wide on my screen. The title is over to the right, and the X to close is beyond the screen. I made a change to put a border on this menu and set the width at about 400, so it looks pretty good and works. Without the X to close, i was doing a Power off to get out of the menu.

**Comment by Frenzie** [comment]
I don't think I've ever looked at the CloudStorage code, but line 29?

https://github.com/koreader/koreader/blob/3492b8b117e6401f145acf346f6e4be4db2752ad/frontend/apps/cloudstorage/cloudstorage.lua#L29

PS You can create a stable link by pressing <kbd>y</kbd> before or after clicking on the line number. Hold shift to link to multiple lines.

**Comment by ottawadeveloper2** [comment]
I changed 2 lines near there for my copy
width=400
is_borderless = false
That said i see now someone has created a nicely written issue for this one. https://github.com/koreader/koreader/issues/3074

**Comment by poire-z** [comment]
I noticed something similar with China.EN.epub (https://en.wikipedia.org/wiki/China saved as EPUB).
Expanding and collpasing the 2nd top-level TOC item "History" makes all the next ones disappear.

This happens because in this article, there are 2 times that same HTML id that is referenced bt the TOC entry:
The good one:
`<h2><span class="mw-headline" id="History">History</span></h2>`
and at the end a bogus one:
`<div id="History" style="font-size:114%;margin:0 4em"><a href="/wiki/History_of_China" title="History of China">History</a></div>`

crengine updates its references with the latest one, so the TOC entry `2 History` points to a page nearly at the end of the book.
Our readertoc lua part assumes that TOC entries and the page they point to are ordered correctly. When they are not (entries are encountered like page 1, 3, 124, 7, 9, 12...) some break happens on page 124 and others are ignored in some situations, thus not displayed.

No real idea how to fix that.

**Comment by poire-z** [comment]
Another effect of this duplicated ID is that it would stop the TOC from being updated to the current page, once you're past the problematic ID.

For example, on this China.EN?epub:

<kbd>![image](https://user-images.githubusercontent.com/24273478/63029946-bebc2180-beb1-11e9-8fdc-438074ee64ef.png)</kbd>

The previous valid `1 Names` would stay highglited because the next one is too far, so as long as I'm between page 11 and page 172, it would consider I'm before `2 History`, even if I'm actually in `4 Politics`.
