### ISSUE TITLE
Occasionally device restart

### ISSUE THREAD

**Issue by asdfeeshy** [koreader/koreader#3067]
* KOReader version:v2015.11-1083-gf95c52f
* Device: Kindle paperwhite 1st gen

#### Issue
Occasionally device restart

#### Steps to reproduce
Open a large PDF -> reflow -> go to a page far from the page you are reading (for instance, if you are at page 1, go to page 300) -> device restart (occasionally)
This problem has been in nightly versions for a long time.

**Comment by Frenzie** [comment]
Is there a crash.log available?

**Comment by Frenzie** [comment]
Closing due to lack of response.

**Comment by NiLuJe** [comment]
Most likely cause: OOM.

There's an option to start KOReader without the Kindle framework running in the background, which may alleviate the issue, but it'll probably crash sooner or later, those devices are basically missing 256MB of RAM ;).
