### ISSUE TITLE
Cloud Storage not working on Kobo Aura ONE

### ISSUE THREAD

**Issue by ghiastas** [koreader/koreader#3074]
* KOReader version: v2015.11-1109-g06d7eea
* Device: Kobo Aura ONE

#### Issue:
Three issues: 
1. Cloud storage opens in landscape mode when display is in portrait mode. 
2. Dropbox storages can be pressed but nothing happens.
3. If return is pressed when in root, koreader crashes.

If the cloud storage is opened when file is in portrait mode then issue 1 does not happen but issues 2 and 3 do. 

#### Steps to reproduce
1. Open file in KOReader
2. Put the display in landscape mode
3. Open file browser that open is portrait mode
4. Open cloud storage (Creates issue 1.)
5. Try to open dropbox and nothing happens (Creates issue 2.)
6. After some time return key is blackened and can be pressed (Creates issue 3.)
7. KOReader crashes 

Return key grey:
![step1](https://user-images.githubusercontent.com/30848140/29231704-2d1ea9e2-7eb6-11e7-8afc-98a5fdd39f40.JPG)
Return key black:
![step2](https://user-images.githubusercontent.com/30848140/29231703-2d1a7aa2-7eb6-11e7-8ffe-84790fbcf3d6.JPG)
KOReader crashes after return key:
![step3](https://user-images.githubusercontent.com/30848140/29231702-2d19c472-7eb6-11e7-8773-b997d38ea22b.JPG)

(Sorry for the neck exercise with the pictures. I don't know why they rotated.)

**Comment by robert00s** [comment]
Could you send us the crash.log from your koreader folder for more info.

**Comment by ghiastas** [comment]
Sure. See below. When I added a dropbox account, it worked the first time but never after as can be seen from the log.

I added only the relevant part.

[crash.txt](https://github.com/koreader/koreader/files/1219199/crash.txt)

**Comment by ottawadeveloper2** [comment]
I was trying to get this going and had noticed both issue 1 and 2 as reported here on my Aura(original version). I have not yet been able to get this to work, was not sure if i did not understand the usage correctly. I also tried dropbox and ftp but got no luck. I have not seen issue 3 as yet.
Locally i made some changes that help but do not fix anything.
I put these changes in the code near here:
width=400
is_borderless = false
https://github.com/koreader/koreader/blob/3492b8b117e6401f145acf346f6e4be4db2752ad/frontend/apps/cloudstorage/cloudstorage.lua#L29

**Comment by Frenzie** [comment]
width=400 is a genuinely bad idea (except for a local hack for a specific device) but I'll leave all that to @robert00s. ;-)

**Comment by ottawadeveloper2** [comment]
agreed, it was a temporary hack to see if i could get the cloud functions to work. Didn't spend more time on it since i was unable to get anything to work.

**Comment by robert00s** [comment]
@ghiastas 
Please add this two lines after this line:
https://github.com/koreader/koreader/blob/3492b8b117e6401f145acf346f6e4be4db2752ad/frontend/apps/cloudstorage/dropboxapi.lua#L97
```
    local logger = require("logger")
    logger.info("Start debug dropbox")
    logger.info(ls_dropbox.entries)
```

function `DropBoxApi:listFolder` should look like that:

```
function DropBoxApi:listFolder(path, token)
    local dropbox_list = {}
    local dropbox_file = {}
    local tag, text
    local ls_dropbox = self:fetchListFolders(path, token)
    local logger = require("logger")
    logger.info("Start debug dropbox")
    logger.info(ls_dropbox.entries)
    if ls_dropbox == nil then return false end
    for _, files in ipairs(ls_dropbox.entries) do
        text = files.name
        tag = files[".tag"]
        if tag == "folder" then
            text = text .. "/"
            table.insert(dropbox_list, {
                text = text,
                url = files.path_display,
                type = tag
            })
        --show only file with supported formats
        elseif tag == "file" and DocumentRegistry:getProvider(text) then
            table.insert(dropbox_file, {
                text = text,
                url = files.path_display,
                type = tag
            })
        end
    end
    --sort
    table.sort(dropbox_list, function(v1,v2)
        return v1.text < v2.text
    end)
    table.sort(dropbox_file, function(v1,v2)
        return v1.text < v2.text
    end)
    for _, files in ipairs(dropbox_file) do
        table.insert(dropbox_list, {
            text = files.text,
            url = files.url,
            type = files.type
        })
    end
    return dropbox_list
end
```

Try again and send me crash log again.

**Comment by ghiastas** [comment]
Attached. I also found out that the blackening of the return key happens after editing an existing dropbox account and pressing apply. 
[crashv2.txt](https://github.com/koreader/koreader/files/1219966/crashv2.txt)
