### ISSUE TITLE
Android missing images from Pdfs

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3087]
* KOReader version:
http://build.koreader.rocks/download/nightly/v2015.11-1115-g74f3d6e/koreader-android-arm-linux-androideabi-v2015.11-1115-g74f3d6e.apk

* Device:
Samsung Note Lollipop 5.1

#### Issue
Suddenly all my pdfs missing images in the pages on this device. Basically if the pdf has embedded images all the image locations have empty rectangles.

I wiped the cache, removed the /sdcard/koreader etc witout any luck. This started recently maybe like in last couple weeks but I cant pintpoint the version.

This device was my most stable Koreader device, so I am not sure.  

#### Steps to reproduce

Open pdf with images

**Comment by Frenzie** [comment]
Fixed by #3262.
