### ISSUE TITLE
Android:  It crashes during startup

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3091]
* KOReader version:
http://build.koreader.rocks/download/nightly/v2015.11-1116-g27c4e28/koreader-android-arm-linux-androideabi-v2015.11-1116-g27c4e28.apk

* Device:
Note 2014 Lollipop 5.1

#### Issue
Koreader crashes rightaway after it is launched

Log:
https://paste.debian.net/hidden/1097bfa2/

It is interesting that I can open .cbz files no problem on another device (LineageOS Android 7.1)

**Comment by gerroon** [comment]
Is this fixed in the current nightly?

**Comment by Frenzie** [comment]
It's one of those weird Android memory allocation issues, meaning it's probably a duplicate. Unfortunately a combination of being hard to reproduce and no one sufficiently knowledgeable about Android working on it doesn't help. 

I bumped LuaJIT to the latest 2.1 beta 3 which potentially has some Android fixes, but if it's only on cbz files… :-/

**Comment by gerroon** [comment]
Well thanks for the fixes but we did not have these crashes before. It started popping up so something must have changed and caused thesr crashes in last month or so.
