### ISSUE TITLE
Android: Crash during startup II

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3095]
I believe this is a totally different crash than the one I reported because this just started happening with the nightly. It flashes for couple ms then crashes during startup. Really fast 

* KOReader version:
http://build.koreader.rocks/download/nightly/v2015.11-1131-g3b5cd4c/koreader-android-arm-linux-androideabi-v2015.11-1131-g3b5cd4c.apk

* Device:

LineageOS 7.1

#### Issue

08-17 23:28:32.281  2900  2468 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity bnds=[534,1711][800,2051] (has extras)} from uid 10026 on display 0
08-17 23:28:32.304  2900 26634 I ActivityManager: Start proc 3767:org.koreader.launcher/u0a69 for activity org.koreader.launcher/.MainActivity
08-17 23:28:32.543  2900  2950 I ActivityManager: Displayed org.koreader.launcher/.MainActivity: +251ms
08-17 23:28:32.547  3767  3784 I luajit-launcher: Application data directory /data/user/0/org.koreader.launcher/files
08-17 23:28:32.547  3767  3784 I luajit-launcher: Application library directory /data/app/org.koreader.launcher-1/lib/arm
08-17 23:28:32.557  3767  3784 I luajit-launcher: Check file in asset module: koreader-g3b5cd4c.7z
08-17 23:28:32.558  3767  3784 I luajit-launcher: Change directory to /data/data/org.koreader.launcher/files
08-17 23:28:32.559  3767  3784 I KOReader: intent file path
08-17 23:28:32.559  3767  3784 I KOReader: run command chmod 755 ./sdcv
08-17 23:28:32.591  3767  3784 I KOReader: command stdout:
08-17 23:28:32.591  3767  3784 I KOReader: command stderr:
08-17 23:28:32.591  3767  3784 I KOReader: command res:0
08-17 23:28:32.591  3767  3784 I KOReader: run command chmod 755 ./tar
08-17 23:28:32.618  3767  3784 I KOReader: command stdout:
08-17 23:28:32.618  3767  3784 I KOReader: command stderr:
08-17 23:28:32.618  3767  3784 I KOReader: command res:0
08-17 23:28:32.618  3767  3784 I KOReader: run command chmod 755 ./zsync
08-17 23:28:32.644  3767  3784 I KOReader: command stdout:
08-17 23:28:32.645  3767  3784 I KOReader: command stderr:
08-17 23:28:32.645  3767  3784 I KOReader: command res:0
08-17 23:28:32.648  3767  3784 I KOReader: try to load module libs/libkoreader-lfs.so
08-17 23:28:32.664  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so: unused DT entry: type 0xf arg 0x334
08-17 23:28:32.664  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so: is missing DT_SONAME will use basename as a replacement: "libkoreader-lfs.so"
08-17 23:28:32.668  3767  3784 I KOReader: external storage /storage/emulated/0
08-17 23:28:32.673  3767  3784 I KOReader: ERROR cannot open translation file: l10n/en_US/koreader.po
08-17 23:28:32.684  3767  3784 I KOReader: ffi.load SDL2
08-17 23:28:32.685  3767  3784 I KOReader: ffi.load SDL
08-17 23:28:32.904  3767  3784 I KOReader: set screen brightness 275
08-17 23:28:32.913  3767  3784 I KOReader: INFO  initializing for device Android
08-17 23:28:32.913  3767  3784 I KOReader: INFO  framebuffer resolution: {
08-17 23:28:32.913  3767  3784 I KOReader:     ["h"] = 2560,
08-17 23:28:32.913  3767  3784 I KOReader:     ["w"] = 1600
08-17 23:28:32.913  3767  3784 I KOReader: }
08-17 23:28:32.928  3767  3784 I KOReader: ffi.load libs/libmupdf.so
08-17 23:28:32.958  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libmupdf.so: unused DT entry: type 0xf arg 0x835e
08-17 23:28:32.960  3767  3784 I KOReader: ffi.load libs/libwrap-mupdf.so
08-17 23:28:32.991  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so: unused DT entry: type 0xf arg 0x8d8
08-17 23:28:32.991  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libwrap-mupdf.so: is missing DT_SONAME will use basename as a replacement: "libwrap-mupdf.so"
08-17 23:28:32.999  3767  3784 I KOReader: ffi.load libs/libfreetype.so.6
08-17 23:28:33.015  3767  3784 I KOReader: try to load module common/serialize.so
08-17 23:28:33.027  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libluacompat52.so: unused DT entry: type 0xf arg 0x4bd
08-17 23:28:33.027  3767  3784 W linker  : /data/data/org.koreader.launcher/files/libs/libluacompat52.so: is missing DT_SONAME will use basename as a replacement: "libluacompat52.so"
08-17 23:28:33.038  3767  3784 W linker  : /data/data/org.koreader.launcher/files/common/serialize.so: unused DT entry: type 0xf arg 0x2ca
08-17 23:28:33.038  3767  3784 W linker  : /data/data/org.koreader.launcher/files/common/serialize.so: is missing DT_SONAME will use basename as a replacement: "serialize.so"
08-17 23:28:33.062  3767  3784 I KOReader: try to load module rocks/lib/lua/5.1/lpeg.so
08-17 23:28:33.073  3767  3784 W linker  : /data/data/org.koreader.launcher/files/rocks/lib/lua/5.1/lpeg.so: unused DT entry: type 0xf arg 0x4a0
08-17 23:28:33.073  3767  3784 W linker  : /data/data/org.koreader.launcher/files/rocks/lib/lua/5.1/lpeg.so: is missing DT_SONAME will use basename as a replacement: "lpeg.so"
08-17 23:28:33.083  2469  2469 W auditd  : type=1302 audit(0.0:958): item=0 name="/data/data/org.koreader.launcher/files/libs/libmupdf.so" inode=656239 dev=103:0d mode=0100600 ouid=10069 ogid=10069 rdev=00:00 obj=u:object_r:app_data_file:s0:c512,c768
08-17 23:28:33.083  3800  3800 I debuggerd: type=1400 audit(0.0:959): avc: denied { getattr } for path="/data/data/org.koreader.launcher/files/libs/libmupdf.so" dev="mmcblk0p21" ino=656239 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=file permissive=1
08-17 23:28:33.112  2900  3648 I WindowManager: WIN DEATH: Window{49f680b u0 org.koreader.launcher/org.koreader.launcher.MainActivity}
08-17 23:28:33.112  2900  4207 I ActivityManager: Process org.koreader.launcher (pid 3767) has died
08-17 23:28:33.113  2900  4207 W ActivityManager: Force removing ActivityRecord{ed6d4ff u0 org.koreader.launcher/.MainActivity t2224}: app died, no saved state

**Comment by Frenzie** [comment]
@gerroon Could you check if this is still an issue after the next nightly? That will be v2015.11-1254-g62754538 or higher.

**Comment by gerroon** [comment]
@Frenzie 

Those git commit names are confusing to me can you please tell me a link to download if you can?

**Comment by Frenzie** [comment]
@gerroon The next nightly won't be out until tomorrow but you could already try the build from https://github.com/koreader/koreader/issues/3214#issuecomment-332146316 in the meantime.

**Comment by gerroon** [comment]
Is this a legit version to try?  v2015.11-1252-g35be7c0 (from today) it crashes with epub and cbz.

**Comment by gerroon** [comment]
okI tried the version you mentioned, it does not crash. I will wait for the real release to try it on my inkbook. I just doi not want to uninstall reinstall since the signatures seems to be different in that version.

**Comment by Frenzie** [comment]
@gerroon The way the tag is constructed works like this:

* **v2015.11** ← the Git tag
* **1254** ← what number commit since the tag this is; for computers this is useless or at least redundant but for people it's useful to quickly see that 1254 is higher than 1252.
* *g***62754538** ← the specific commit; the `g` is just some useless fluff, this time useful for computers to disambiguate in regular expressions that it's indeed the abbreviated commit hash.

**Comment by gerroon** [comment]
@Frenzie 

Thanks for the info

Is this a good one then ? It has 1254 in it for sure, http://build.koreader.rocks/download/nightly/v2015.11-1254-g6275453/

**Comment by Frenzie** [comment]
Yes, that's today's nightly build.

**Comment by gerroon** [comment]
cool

**Comment by gerroon** [comment]
Initial impressions, it works (no crashes with epub/cbz, pdf has images, frontlight light seem to be ok) ;)

**Comment by Frenzie** [comment]
The frontlight? Weird, that wouldn't be any different than, say, two days ago. Anyway, closing this then. :-)

Incidentally, do you need patch.lua on any of your devices? (See https://github.com/koreader/koreader/issues/3214#issuecomment-332225790) I'd like to upload a new release on GH but I'm waiting until I know more about that particular issue.
