### ISSUE TITLE
Kobo: frontlight settings cleanup

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3103]
Regarding:
https://github.com/koreader/koreader/blob/c3778bdb2ad8c3b1b3e7a435e1ba0b673f53d356/frontend/device/kobo/powerd.lua#L17
https://github.com/koreader/koreader/blob/c3778bdb2ad8c3b1b3e7a435e1ba0b673f53d356/defaults.lua#L172-L177
I may wish (@Hzj-jie: if you don't have yet more work ongoing on kobo/powerd and this topic) to work on removing them.

To me, we may need only one boolean setting: `frontlight_sync_with_nickel` (to be stored in settings.reader.lua, with a new togglable menu item):
**false**: current light level and state are saved in settings.reader.lua, and restored on startup
**true**: current light level and state are saved in settings.reader.lua **and in Kobo Ereader.conf**, and **restored from Kobo Ereader.conf** on startup.

I see the use case for true (the current default), and false (my preference: don't touch Kobo Ereader.conf, different levels for nickel vs koreader, but mostly to not bother updating Kobo Ereader.conf everytime i change level).
I can't see a real use case to have a fixed 0-100 value defined (as it is allowed with KOBO_LIGHT_ON_START ): mostly, we'd like to have back the level we had before.
Also, i dont think we can fetch the current level (KOBO_LIGHT_ON_START = -1), and it does not matter much: we're coming either from KOReader or Nickel (or KSM, but it's more a transitional state - i have a very low frontlight level for KSM, so it does not illumate the room while plugged in with usb enabled).

Thoughts ?

**Comment by Frenzie** [comment]
I don't care about the frontlight at all as long as it doesn't bother me by turning on incessantly. My preferred setting is off, although I have had some minor use for it at values <10.

As for the correct behavior I'm not sure. People seem to like Nickel sync.

**Comment by KenMaltby** [comment]
I also practically never use the frontlight, or Nickel, for that matter.  Storing the light status at any time other than when finished reading or going into sleep mode, should be avoided.  Matching Nickel would not be something to use as a criteria for KOReader.  As long as it is about setting a default level when the user turns on the frontlight, **not** having the frontlight turn on automatically when KOReader is started, it makes sense to me.

**Comment by oldhasbeen** [comment]
The frontlight is most important for me - I use it daily at the 1% intensity level. It is very dark where I live and 2% is often already a bit on the too bright side for me. I cannot toggle between frontlight off and 1%. Only from 2% up is functional. (H2O first edition). It used to be ok some longer time ago - I lost track when the regression occurred.

**Comment by poire-z** [comment]
(I'm usually at 50% frontlight level...)

About this 1% level acting as Off:

https://github.com/koreader/koreader/blob/1f75bc645ca6640f951ce4d0103be251a590bb00/frontend/device/kobo/powerd.lua#L8-L10

I changed `fl_min = 1` to `fl_min = 0`, and it seems to fix that, without any side effect seen so far.

@Hzj-jie : you (I assume it was an old account of yours) introduced this fl_min = 1 in february 2016 in https://github.com/koreader/koreader/commit/e84093c41 , and it hasn't changed since then.
As I haven't yet a full grasp on your frontlight logic refactoring from some weeks ago, could you check if this `fl_min = 1` is still needed after these changes, or if we can put it back to `fl_min = 0` ?

**Comment by Frenzie** [comment]
I the idea is that "toggle" (either in the GUI with the toggle on/off button or with a physical button) puts it to 0 while 1 is the minimum light level. The side effect, at least as given by the code comment, is that if you set the level to 0 there's nothing to toggle to.

That being said, I preferred being able to just set it to 0. It might make more sense if toggle just said something like "if toggling (from 0) to 0, toggle to 20 or user-set preference instead."

**Comment by oldhasbeen** [comment]
poire-z: I changed  fl_min = 1  to  fl_min = 0 , and it seems to fix that, without any side effect seen so far.

I have done that now too and it appears to work. My the frontlight can now be toggled on/off at the 1%  level again. Thank you!

**Comment by Frenzie** [comment]
Fixed by #3143.

**Comment by poire-z** [comment]
#3143 probably closes many other issues (i'll check for them later), but not this one :) I mentionned this one just because it was the first place I wrote about fl_min=0.
Although i've seen on mobiread that some people uses KOBO_LIGHT_ON_START=49, so I'm not sure about going on with the original topic (getting rid of these KOBO_*).

**Comment by Frenzie** [comment]
My bad, I was no better than GitHub's automated algorithm. I knew it closed some issues, did a quick visual scan and saw "fix (#3103 #2970 (comment))."

**Comment by poire-z** [comment]
Closing as no longer interested :)
