### ISSUE TITLE
Suggestion: Standby splash like in Coolreader

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#3109]
Nothing essential, but nice to have: (some version of) Coolreader has a thing called standby splash that can be timeset to anything. A splash screen appears at the appointed time and any user action on the device (touch of the screen or some button) removes it.

It's nice to have it for example to notify the user that the device has been idle too long and will switch off soon. It's much easier to do something to get rid of the standby splash and thus postpone the switch-off time than to switch on the device.

**Comment by poire-z** [comment]
Seems most of that can be done with the "Read timer" plugin.
