### ISSUE TITLE
Unhighlight doesn't return PDF to original state

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3113]
* KOReader version: c8ab918 (current master)
* Device: all

#### Issue
Reported on https://www.mobileread.com/forums/showthread.php?p=3570604
> Looks like I discovered a disastrous thing in Koreader: When you highlight some text in a pdf and then save it, the file gets irreversibly altered. There seems to be no way to unhighlight. Some tap on the altered place seems to occasionally give you the "delete" option, but it has no lasting effect the way highlight does.
>
> I know that the file is permanently altered because when it opens up in the default reading app, the same place looks the same as in Koreader. 

In this screenshot the light-gray highlights are leftovers, while the darker gray highlights are "real", deletable highlights. But they can only be removed if you didn't save the document.

![screenshot_2017-08-21_09-24-47](https://user-images.githubusercontent.com/202757/29507962-d29e856a-8652-11e7-96db-568e03bb6dc3.png)

#### Steps to reproduce
1. Highlight something in a PDF document.
2. Exit the document (to filemanager or system)
3. Choose to save the document when prompted
4. Reopen document
5. Delete highlight
6. A thin gray highlight still exists

**Comment by ersi-dnd** [comment]
I'd say the desirable solution is to keep highlights and unhighlights in .sdr with no need to overwrite the original document.

**Comment by ersi-dnd** [comment]
And it would be nice if a list of highlighted (bookmarked, annotated, ...) files could be generated by a plugin like this https://www.mobileread.com/forums/showthread.php?t=265433

**Comment by adnion** [comment]
I'd like to report another use case which breaks the desired functionality.
1. In koreader highlight something and delete the highlight again
2. Choose to save the document when prompted
3. The !deleted! highlight is written in the PDF document

**Comment by poire-z** [comment]
Possibly fixed since #7988 and https://github.com/koreader/koreader-base/pull/1388.
