### ISSUE TITLE
KT3

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#3115]
* KOReader version:koreader-stable-v2015.11
* Device:KT3

#### Issue
Doesn't work

**Comment by Frenzie** [comment]
The model number itself already exists in the code, so presumably it's a simple matter of adding your model number to the mix like [here](https://github.com/koreader/koreader/pull/3070/commits/2bd4e9403a43fb841c82838b8e7f49f661c8fc91).

Would it be possible to look at the crash.log in koreader's folder? There should be something like this in it:

```
              launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|
[*] Current time: 08/10/17-15:50:01

./luajit: frontend/device/kindle/device.lua:608: unknown Kindle model 90 (0LL)
```

It's that model number, `0LL` in the example, that we need.

**Comment by zaoqi** [comment]
```
./luajit: frontend/device/kindle/device.lua:363: unknown Kindle model 00
stack traceback:
	[C]: in function 'error'
	frontend/device/kindle/device.lua:363: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:37: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:92: in main chunk
	[C]: at 0x0000be8d
```

**Comment by Frenzie** [comment]
Thanks! Unfortunately I'm not really sure what that means, but model number 00 definitely doesn't sound very plausible.

Is there an easy way for you to read `/proc/usid`? If not, try changing this line

https://github.com/Frenzie/koreader/blob/2bd4e9403a43fb841c82838b8e7f49f661c8fc91/frontend/device/kindle/device.lua#L564

to

```lua
local kindle_devcode = kindle_sn
```

The full `kindle_sn` content should probably be added to that error.

**Comment by zaoqi** [comment]
`G000KA...`

**Comment by Frenzie** [comment]
Based on that string you would get kindle_devcode == `00` and kindle_devcode_v2 == `0KA`. So far so good. Now the question is why you would get an error message of `unknown Kindle model 00` instead of `unknown Kindle model 00 (0KA)`. Or in the latter case, no error at all because `0KA` is known.

```lua
> lala = "G000KA..."
> kindle_devcode = string.sub(lala,3,4)
> print(kindle_devcode)
00
> kindle_devcode_v2 = string.sub(lala,4,6)
> print(kindle_devcode_v2)
0KA
> print(lala) -- just making 110% sure the original string remained intact
G000KA...
> function Set(list)
    local set = {}
    for _, l in ipairs(list) do set[l] = true end
    return set
end>> >> >> >>
> kt3_set = Set { "0DT", "0K9", "0KA" }
> if kt3_set[kindle_devcode_v2] then print("bla") end
bla
-- yeah, so that's working
```

**Comment by Frenzie** [comment]
Oh drat! I didn't sufficiently look at your version: koreader-stable-v2015.11. /smacks forehead Sorry for wasting your time, but I don't really know about the Kindle side of things.

Just grab a newer nightly. Support for your device wasn't added until after that.

https://github.com/koreader/koreader/releases/tag/v2017.06.12-nightly
