### ISSUE TITLE
Android crashes III  koreader-nightly-20170821 woes

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3123]
Things seem to be little better with pdfs with this version but cbz and epubs still crashes. When I roll back to a version from june 10, cbz works although I have not tried every version in June, it is the version I have.

However the pdfs still are missing images if there are embbed images.

https://paste.debian.net/hidden/8295fa20/

**Comment by Frenzie** [comment]
Should also be fixed by #3262.
