### ISSUE TITLE
Crash when highlight a word

### ISSUE THREAD

**Issue by holyblade** [koreader/koreader#3127]
* KOReader version: abaa699
* Device:kobo

#### Issue
When I highlight a word, it just crashed.  I have to go turn back to version d6845d9.
#### Steps to reproduce

**Comment by Frenzie** [comment]
I haven't experienced this issue on my H2O. Is it a specific kind of document?

**Comment by robert00s** [comment]
Kindle PW3 the same issue (version 1113)

```
./sdcv: line 3: can't create : Invalid argument
./sdcv: line 3: ELF: not found
./sdcv: line 4: syntax error: unexpected word (expecting ")")
08/24/17-08:48:48 WARN  JSON data cannot be decoded
./sdcv: line 3: can't create : Invalid argument
./sdcv: line 3: ELF: not found
./sdcv: line 4: syntax error: unexpected word (expecting ")")
08/24/17-08:48:59 WARN  JSON data cannot be decoded
./luajit: frontend/apps/reader/modules/readerhighlight.lua:422: attempt to get length of a nil value
stack traceback:
	frontend/apps/reader/modules/readerhighlight.lua:422: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/ui/widget/dictquicklookup.lua:337: in function 'callback'
	frontend/ui/widget/button.lua:180: in function 'action'
	frontend/ui/uimanager.lua:516: in function '_checkTasks'
	frontend/ui/uimanager.lua:667: in function 'handleInput'
	frontend/ui/uimanager.lua:763: in function 'run'
	./reader.lua:169: in main chunk
	[C]: at 0x0000bef1
lipc-wait-event exited normally with status: 0
```

I don't have time now. I'll try look at it later.

**Comment by Frenzie** [comment]
@robert00s I broke the specific version you're using (and only that one), see 74f3d6e8202c9cd86a61133aad77f085a731fdb6.

**Comment by robert00s** [comment]
@Frenzie 
Thanks, I upgraded to v2015.11-1152-gabaa699 and I haven't experienced this issue on my Kindle. So we have to know more detail about document that highlight crash.

**Comment by holyblade** [comment]
The version after d6845d9 all encounter crash problems. It's not a specific file, but all files. I upgraded from very old version, I'm not sure if that matters. And here is the crash log. The device I use is kobo glo.

> 08/26/17-12:40:54 ERROR cannot open translation file: l10n/en_US/koreader.po
08/26/17-12:40:54 INFO  initializing for device Kobo_kraken
08/26/17-12:40:54 INFO  framebuffer resolution: {
    ["h"] = 1024,
    ["w"] = 758
}
[ko-input] Forked off fake event generator(pid:3350).
08/26/17-12:40:55 INFO  Loading plugins from directory: plugins
08/26/17-12:40:55 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
08/26/17-12:40:55 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
08/26/17-12:40:56 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
08/26/17-12:40:56 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
08/26/17-12:40:58 INFO  opening file /mnt/onboard/.adds/koreader/help/quickstart-en-v2015.11-1054-g6870bc2.html
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/droid/._DroidSansMono.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/freefont/._FreeSans.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/freefont/._FreeSerif.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSans-Bold.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSans-BoldItalic.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSans-Italic.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSans-Regular.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSansCJK-Regular.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSerif-Bold.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSerif-BoldItalic.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSerif-Italic.ttf>
08/26/17-12:40:58 ERROR failed to register crengine font cannot register font <./fonts/noto/._NotoSerif-Regular.ttf>
08/26/17-12:40:59 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/._PingFang Bold.ttf>
08/26/17-12:40:59 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/._STHeitiMedium.ttf>
08/26/17-12:40:59 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
08/26/17-12:40:59 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
./luajit: frontend/apps/reader/modules/readerhighlight.lua:422: attempt to get length of a nil value
stack traceback:
	frontend/apps/reader/modules/readerhighlight.lua:422: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/ui/widget/dictquicklookup.lua:338: in function 'callback'
	frontend/ui/widget/button.lua:182: in function 'action'
	frontend/ui/uimanager.lua:516: in function '_checkTasks'
	frontend/ui/uimanager.lua:667: in function 'handleInput'
	frontend/ui/uimanager.lua:763: in function 'run'
	./reader.lua:178: in main chunk
	[C]: at 0x00013fc5

**Comment by holyblade** [comment]
I guess I found the reason. Because I use Chinese as my koreader language.

**Comment by Frenzie** [comment]
Which Chinese specifically, zh_CN? I'll give it a go but your traceback doesn't seem to relate to localization. I can't confirm any crashes either on my H2O or in the emulator. :-/

![screenshot_2017-08-31_16-28-43](https://user-images.githubusercontent.com/202757/29928499-78b76336-8e69-11e7-8007-17f76a051a02.png)

![screenshot_2017-08-31_16-30-55](https://user-images.githubusercontent.com/202757/29928675-c8691ffa-8e69-11e7-8f15-6c425e68a195.png)

**Comment by holyblade** [comment]
@Frenzie 
Did you used the highlight function? 
And I took a video to prove that it indeed crashed. (https://youtu.be/kpd0igXTd0M)

**Comment by Frenzie** [comment]
Sorry, my bad! I didn't realize you meant more than just selecting a word.

It looks like this might be reproducible with any language other than the default. I forgot to post this bisection previously: https://github.com/koreader/koreader/compare/d6845d9...abaa699

@robert00s The main change I see in dictquicklookup.lua is your #3034. It looks like you made the behavior dependent on matching against the English-language "Highlight" string.
