### ISSUE TITLE
kosync call to Document:fastDigest() and partial_md5_checksum useful ?

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3132]
Just thought I would add this as a note to https://github.com/koreader/koreader/pull/3131 , but it seems like a bug:
The metadata.lua is also backuped when the document is opened, by the kosync plugin's `KOSync:onReaderReady()`, at:
https://github.com/koreader/koreader/blob/17014f9281b0aab04d6c0e8f64e4d0ff4e2d0bae/plugins/kosync.koplugin/main.lua#L67
which is calling `Document:fastDigest()` at:
https://github.com/koreader/koreader/blob/17014f9281b0aab04d6c0e8f64e4d0ff4e2d0bae/frontend/document/document.lua#L114

But this `Document:fastDigest()` does its own opening and saving of the docsettings (to save a `partial_md5_checksum` properties) in that function.
This docsettings has already been read by Reader, and when it will be saved, it's what was read at opening that will be saved, so it will never include this `partial_md5_checksum`.
So, next time the document is opened, this `partial_md5_checksum` is absent, and the whole process is done again.
Moreover, it seems nothing in the code requests that saved `partial_md5_checksum` settings...

As I don't know much about what kosync and fastDigest do/mean, I won't touch that, but there's something strange, may be it's a leftover from some past times ?

**Comment by Frenzie** [comment]
If you press <kbd>y</kbd> then GH changes the link to include the commit hash so the discussion can be easily read a year from now. :-)

Anyway, @Hzj-jie added it in https://github.com/koreader/koreader/commit/820a39c8f73e109314f33f63e384302dd72dcabb so if it's not actually being saved to prevent recalculating that sounds like a bug.

**Comment by poire-z** [comment]
(OK, didnt know that `y`, and wondered why sometimes it's just a link, sometime a snippet of the code.)
Also, it's not only recalculated, it also seem not to be used.

**Comment by Frenzie** [comment]
The snippet thing is brand-new.

But fastDigest is used? Aside from the issue you mentioned that the setting is apparently never properly saved and therefore always recalculated it seems okay?

https://github.com/koreader/koreader/blob/a8513c95b602be616528b8073de765e724cdbeae/plugins/kosync.koplugin/main.lua#L419

**Comment by poire-z** [comment]
Oh, I see. I guess that this `partial_md5_checksum` saving was made so the calls you just linked to could be replaced by it to avoid the costly (and possibly changing) `:fastDigest()` each time. And this optimisation may have been abandonned half-way?

**Comment by Frenzie** [comment]
I assume it was probably working at the time. But it might still be useful for avoiding recalculating on page changes or something like that? (I don't know when or how sync is triggered.)

https://github.com/koreader/koreader/blob/17014f9281b0aab04d6c0e8f64e4d0ff4e2d0bae/frontend/document/document.lua#L119-L120

**Comment by Frenzie** [comment]
Fixed by #3352.
