### ISSUE TITLE
How to display two pages in landscape mode when reading pdf files?

### ISSUE THREAD

**Issue by chenxingqun** [koreader/koreader#3138]
* KOReader version: All
* Device: Max Carta

#### Issue
Would you add a function that enables viewing pdf in two pages in landscape mode? I have an 13.3" onyx boox carta with resolution 2200x1650.
It would be very convinient to read in this mode.
Thank you very much!

**Comment by ersi-dnd** [comment]
Has nobody has asked for this before? It would be a great boost when looking at music sheets. Or comics :) on any screen bigger than 6".

**Comment by Frenzie** [comment]
I'll close this as a duplicate of #5799 (which has a more memorable/findable issue title).
