### ISSUE TITLE
WiFi can't be connected

### ISSUE THREAD

**Issue by liyiecho** [koreader/koreader#3142]
* KOReader version: koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1163-gefac272
* Device: kobo aura one (firmware 4.5.9587)

#### Issue

I connected WiFi then open koreader to OTA update, it always ask me to turn on the WiFi.  
Here is the video link [https://youtu.be/83tjAGO7kI0](url).
And some white triangle zone at top left of screen when I open koreader.

**Comment by Frenzie** [comment]
What kind of network is it?

**Comment by liyiecho** [comment]
home network,  and the WiFi is 2.4 Ghz

**Comment by Frenzie** [comment]
Sorry for not being more clear. I think KOReader might only support WPA and/or WPA2 at present.

**Comment by liyiecho** [comment]
Please look the picture.
<img width="444" alt="screen shot 2017-08-29 at 15 43 19" src="https://user-images.githubusercontent.com/5213722/29810012-d9ed2bee-8cd0-11e7-9d39-639e05227c03.png">

**Comment by Frenzie** [comment]
Looks like it should be okay. Pinging @houqp who I hope might have some time available to look at this.

**Comment by liyiecho** [comment]
Most likely the problem was caused by my WiFi. When I use portable hotspot , koreader can OTA update. Whether koreader check something to make a decision to connect the WiFi or not?

**Comment by Frenzie** [comment]
It's also possible that it's connected but doesn't have connectivity for some reason. By default it pings `www.example.com` to test. Does that domain work for you?

https://github.com/koreader/koreader/blob/773e24fc79c8cbf6dcf48e3678237861149aabef/frontend/ui/network/manager.lua#L64

**Comment by liyiecho** [comment]
It cannot resolve the domain. I need to change the domain by myself. Thank you so much.
<img width="725" alt="screen shot 2017-08-30 at 14 46 19" src="https://user-images.githubusercontent.com/5213722/29858865-090c7a44-8d92-11e7-875d-2f55d9fcfd9f.png">

**Comment by Frenzie** [comment]
I don't really understand though. Is your DNS server not working right? Is your ISP's traffic overloading?

```
$ dig www.example.com

; <<>> DiG 9.10.3-P4-Debian <<>> www.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34218
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.example.com.		IN	A

;; ANSWER SECTION:
www.example.com.	65596	IN	A	93.184.216.34

;; AUTHORITY SECTION:
example.com.		47800	IN	NS	a.iana-servers.net.
example.com.		47800	IN	NS	b.iana-servers.net.

;; Query time: 11 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Aug 30 09:12:54 CEST 2017
;; MSG SIZE  rcvd: 108
```

Could you also test `dns.msftncsi.com`? It's what Microsoft uses for Windows (see [here](https://technet.microsoft.com/en-us/library/ee126135#BKMK_How)). They also check whether `http://www.msftncsi.com/ncsi.txt` returns `Microsoft NCSI`.

```
$ dig dns.msftncsi.com

; <<>> DiG 9.10.3-P4-Debian <<>> dns.msftncsi.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36629
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dns.msftncsi.com.		IN	A

;; ANSWER SECTION:
dns.msftncsi.com.	24	IN	A	131.107.255.255

;; Query time: 10 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Aug 30 09:14:07 CEST 2017
;; MSG SIZE  rcvd: 61
```

It might be better to use that in the sense that it's meant for it.

**Comment by liyiecho** [comment]
`dns.msftncsi.com` works well.

```
 dig dns.msftncsi.com

; <<>> DiG 9.8.3-P1 <<>> dns.msftncsi.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51592
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;dns.msftncsi.com.		IN	A

;; ANSWER SECTION:
dns.msftncsi.com.	12	IN	A	131.107.255.255

;; Query time: 93 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Aug 30 15:26:39 2017
;; MSG SIZE  rcvd: 50
```
