### ISSUE TITLE
[bug] Android screen (viewport) offset/margin doesn't work

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3148]
* KOReader version: nightly git
* Device: android

#### Issue
This is a blocker for Pull Request #2938.

Can change Android viewport resolution (**h**eight & **w**idth) with:
```
local Geom = require("ui/geometry")
local android = require("device/android/device")
(...)
local viewport = Geom:new{x=50, y=100, w=900, h=1600}
android.screen:setViewport(viewport)
```
but chaning x & y doesn't affect screen/viewport position.

Issue confirmed by @Frenzie (https://github.com/koreader/koreader/pull/2938#issuecomment-325478013)

#### Steps to reproduce

Comparision :
`local viewport = Geom:new{x=50, y=100, w=900, h=1600}` 
below:
![x 50 y 100 w 900 h 1600](https://user-images.githubusercontent.com/4487025/29753507-507fa3fe-8b73-11e7-8761-7b399931ad68.png)
with
`local viewport = Geom:new{x=0, y=0, w=900, h=1600}` 
below:
![x 0 y 0 w 900 h 1600](https://user-images.githubusercontent.com/4487025/29753540-e26292c2-8b73-11e7-8f85-7c69d652ab2e.png)

Can anyone help?

**Comment by Frenzie** [comment]
Could you share a bit about the Android emulator setup? It might make for some slightly easier experimentation.

Pinging @pazos

**Comment by mwoz123** [comment]
Plain Google Android 24 API.

Emulator name `arm` 

Configs stored in `~/.android/avd `:
[arm.ini.txt](https://github.com/koreader/koreader/files/1267575/arm.ini.txt)
`~/.android/avd/arm.avd`:
[config.ini.txt](https://github.com/koreader/koreader/files/1267577/config.ini.txt)
[emulator-user.ini.txt](https://github.com/koreader/koreader/files/1267578/emulator-user.ini.txt)
[hardware-qemu.ini.txt](https://github.com/koreader/koreader/files/1267579/hardware-qemu.ini.txt)

I should be possible to create new Google Android 24 api with `arm` name and replace ini files with uploaded above (maybe with minor changes(homedir)).

**Comment by mwoz123** [comment]
Anyone knows why moving viewport (Koreader visible area) on Android screen doesn't work?

**Comment by mwoz123** [comment]
Once resolved those lines should be uncommented:
https://github.com/koreader/koreader/pull/2938/commits/5a08e11620c7658c6895040c11e33c52a34487bf#diff-155e4ade9f83bbd97640fe9bd601584bR27

**Comment by mwoz123** [comment]
Anyone could help here? 


Once this bug is resolved, it would be good to add those lines:
>         local Geom = require("ui/geometry")
>         logger.dbg("screen_fullscreen_menu_table.lua: Setting viewport to {x=".. status_bar_height .. ", y=0, w="
>                 .. screen_width .. ", h=" .. screen_height - status_bar_height) .. "}")
>        local viewport = Geom:new{x=status_bar_height, y=0, w=screen_width, h=screen_height - status_bar_height}
>         android.screen:setViewport(viewport)
>        android.input:registerEventAdjustHook(
>                 android.input.adjustTouchTranslate, {x = 0 + status_bar_height, y = 0})

to: 
https://github.com/koreader/koreader/blob/5a08e11620c7658c6895040c11e33c52a34487bf/frontend/ui/elements/screen_fullscreen_menu_table.lua#L27

it should resize the screen/vieport.

**Comment by Frenzie** [comment]
> It should be enought to run on Google Android 24 Api.

Be that as it may, how do you set it up? Rather than trying to do something in Qemu I imagine Google has made it so that it's practically impossible anyway unless you download some 2+ GB Android Studio/Emulator/whatever behemoth.

**Comment by mwoz123** [comment]
Right, I run Android Studio -> Tools_> Android -> AVD manager -> create Virtual Device.

Details:
>Name: arm
CPU/ABI: Google APIs ARM (arm64-v8a)
Path: /home/marcin/.android/avd/arm.avd
Target: google_apis [Google APIs] (API level 24)
Skin: 1080x1920
SD Card: 100M
hw.dPad: no
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: New Device
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: User
hw.gps: yes
hw.initialOrientation: Portrait
skin.path.backup: _no_skin
image.androidVersion.api: 24
hw.audioInput: yes
image.sysdir.1: system-images/android-24/google_apis/arm64-v8a/
tag.id: google_apis
showDeviceFrame: no
hw.camera.back: emulated
hw.mainKeys: no
AvdId: arm
hw.camera.front: emulated
hw.lcd.density: 480
avd.ini.displayname: arm
hw.gpu.mode: auto
hw.device.hash2: MD5:2fa0e16c8cceb7d385183284107c0c88
hw.ramSize: 1536
hw.trackBall: no
PlayStore.enabled: false
hw.battery: yes
hw.cpu.ncore: 2
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
hw.keyboard: yes
hw.sensors.proximity: yes
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**Comment by Frenzie** [comment]
I'll give it a go one of these days, thanks!

**Comment by Frenzie** [comment]
Okay, so you I've done this:

1. Install Android Studio.
2. Create a virtual device.
3. Open KOReader apk.

Now it just says "waiting for target device to come online" and nothings happening. (CPU's not doing a thing.)

![screenshot_2017-09-17_20-39-39](https://user-images.githubusercontent.com/202757/30523812-620af97c-9be8-11e7-8a69-76df9d6ea75a.png)

I tried it with two different images. The one I want (Android 2.3) and the one I figured should work no matter what.
![screenshot_2017-09-17_20-48-43](https://user-images.githubusercontent.com/202757/30523872-a0475edc-9be9-11e7-8e31-f732f95d94bb.png)

And it's not like it's loading or whatever. My CPU is lounging around at 1-2%.

**Comment by mwoz123** [comment]
I just used Android Studio to create AVD. It can also be used to start emulator.
Maybe it can be integrated but I used consoles.

I'm using 4 linux terminals: 
- for starting emulator (below points 1,2)
- for building apk (3,4)
- for installing (3,5,6)
- for logs (7)

My setup:
1. add `emulator` path to your paths (to start AVD without Android Studio):
> export PATH=$PATH:'~/Android/Sdk/tools' ; 

`~/Android/Sdk/tools` that's default path to `emulator` (from Android Studio)

2. to start emulator in comand line :
> emulator -avd {your_avd_name}

I used `arm` here
(you can previously display created/setup AVDs with `emulator -list-avds`)

3. Other terminal I go to koreader directory:
> cd {your koreader dir}

4. to build package: 
> ./kodev release android

5. to display build apk packages: 
> ls koreader*.apk

use the recent one 

6. to install it :
> adb install koreader-android-arm-linux-androideabi-{your version}.apk

You need to have adb in system path. in ubuntu `sudo apt install android-tools-adb`.
Emulator has to be ARM (not x86) otherwise you will get error here complaining about inconsistent architecture.

7. to see the logs :
> adb logcat

8. Start Koreader app on Emulator - test your changes/solution
9. check logs (if something's wrong)
10. make changes in code
11. build Koreader package -> see point 4.
12. uninstall Koreader from Emulator
13. install koreader again -> see point 6.
14. keep repeating steps 8-13 until you get a working solution.

Maybe we should extract that to HowTo story or to Wiki?

**Comment by Frenzie** [comment]
> to start emulator in comand line :

Now we're talking. :grin:

> Maybe we should extract that to HowTo story or to Wiki?

We could also add something like that to the docs, see http://koreader.rocks/doc/topics/Collaborating.html

**Comment by Frenzie** [comment]
> ~/Android/Sdk/tools that's default path to emulator (from Android Studio)

Is that always the case? I installed it to `~/programs/android-sdk` because I don't want Google littering their trash in my home root, but it's directly in the `~/programs/android-sdk/tools` subdirectory. In any case, just adding that to path doesn't work because it depends on a relative path:

```
$ emulator @Nexus_5X_API_23
[140523434030912]:ERROR:./android/qt/qt_setup.cpp:28:Qt library not found at ../emulator/lib64/qt/lib
Could not launch '../emulator/qemu/linux-x86_64/qemu-system-armel': No such file or directory
```

If you want it in $PATH, on my system you'd have to add the /emulator subdirectory there.

Executing it directly from the dir does:
```
$ ./emulator -avd Nexus_5X_API_23
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  156 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  55
  Current serial number in output stream:  54
emulator: WARNING: encryption is off
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  156 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
```

Now that we have a proper error message, *that*'s easy to work around:

```bash
LD_PRELOAD='/usr/$LIB/libstdc++.so.6' ./emulator -avd Nexus_5X_API_23
```

Unfortunately that's pretty pointless as it's just a slower version of what I've already got on my real devices. Btw, it looks like you can also install packages by dragging them onto the emulator.

What I want still doesn't work:
```
$ LD_PRELOAD='/usr/$LIB/libstdc++.so.6' ./emulator Nexus_4_API_9
PANIC: Missing emulator engine program for 'arm' CPU.
```

Apparently there's only a 64-bit arm emulator yet… but maybe that can be installed somehow outside of the stupid GUI.

Anyway, thanks, that really helped.

**Comment by mwoz123** [comment]
> Is that always the case? I installed it to ~/programs/android-sdk

I wrote "~/Android/Sdk/tools that's default path" which mean you can always change it and paste here yours;)

>Apparently there's only a 64-bit arm emulator yet...

That might be a big problem if you're using i686:/ 

Maybe you could try virtual box develop on 64bits linux? But it might be painful.. 
If there no such thing as 32bit emulator for ARM yet, I bet they don't have plan to create it:(

**Comment by Frenzie** [comment]
My system's qemu is perfectly happy emulating 32-bit ARM afaik. I wouldn't be surprised if I had to install something extra with the `sdkmanager` command. Anyway, I'm just hoping it might offer a way to reproduce #3214.

**Comment by Frenzie** [comment]
I don't know if I'll look into this thing at all but I'll just dump how to use gdb in combination with Android here: https://source.android.com/devices/tech/debug/gdb

**Comment by Frenzie** [comment]
I was giving this a quick look today and you can replicate the effect on Android by reversing these lines https://github.com/koreader/koreader-base/blob/ccb3ce19444fbab0eeda631834fcfd643b61379b/ffi/framebuffer.lua#L143-L146

Of course we already knew that, but I hadn't had time to track down where it (more or less) goes wrong, besides that it had to be in one of those files.

**Comment by poire-z** [comment]
Mentionning that here, although I don't know if it's related to this fix.
Previous version I had was v2015.11-1284-gb55265b or v2015.11-1276-g92e0067 (not sure) and I did not notice what I notice today with v2015.11-1293-g34ad91c :
When opening a PDF, I get that black screen people talk about. I need to tap somewhere to get a redraw and see the white background with text. The "Opening ..." infomessage is not seen.
When opening a EPUB, because of the double refresh (that #3300 not yet merged fixes), I get the white page with text (after a 1 second black screen, and still no "Opening ..." infomessage).
(Can't check intermerdiate 1284 or v2015.11-1287-g5a2c8e4 till this evening).
But it looks like it's either this framebuffer fix, or the frontlight fix. Like the first bitmap is not drawn.
I hadn't noticed that since I tried koreader on android last week.

**Comment by Frenzie** [comment]
That's the light.

**Comment by mwoz123** [comment]
I had blank (white) screen after startup since around 23 September nightly-build. Have to click somewhere to see the menu. 
So if we're talking about the same thing it should be related to this change.

**Comment by poire-z** [comment]
Noticed something on android only, that was not happening on 1287-g5a2c8e4, but is since 1293-g34ad91c (https://github.com/koreader/koreader/compare/5a2c8e4...34ad91c), that may be related to this viewport fix:
Open PDF in portrait mode, switch to landscape: the half left side is ok, the right left side if either blank, or some part of what was on portrait mode.

**Comment by Frenzie** [comment]
Yes, if that wasn't occurring before then that's because of https://github.com/koreader/koreader-base/commit/a11aacf71f69792c3a7a089ca8356d7c5427f554. I forgot to test that. :blush:

**Comment by mwoz123** [comment]
Viewport changes was moved out of this code. Implementation in #3392
