### ISSUE TITLE
Help with epub

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#3153]
I messed up with my koreader and now I cannot open epub
I´m getting this error

---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 08/30/17-08:52:18

08/30/17-08:52:18 INFO  initializing for device KindlePaperWhite3
08/30/17-08:52:18 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:21869).
08/30/17-08:52:19 INFO  opening file /mnt/us/documents/A Fazenda Pública em Juízo - Leonardo Carneiro da Cunha - 2017.epub
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/Amazon-Ember-Bold.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/Amazon-Ember-BoldItalic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/Amazon-Ember-Regular.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/Amazon-Ember-RegularItalic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Bookerly-Bold.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Bookerly-BoldItalic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Bookerly-Italic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Bookerly-Regular.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_66_Medium_Italic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_67_Cond_Medium.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_68_Cond_Medium_Italic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_75_Bold.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_76_Bold_Italic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_77_Cond_Bold.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Caecilia_LT_78_Cond_Bold_Italic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/KindleBlackboxBoldItalic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/KindleBlackboxItalic.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/KindleBlackboxRegular.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Kindle_MonospacedSymbol.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/Kindle_Symbol.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/MTChineseSurrogates.ttf>
08/30/17-08:52:20 ERROR failed to register crengine font cannot register font <./fonts/host/STHeitiMedium.ttf>
[!] doShowReader coroutine crashed:
frontend/apps/reader/modules/readerhyphenation.lua:20: r
stack traceback:
	frontend/apps/reader/modules/readerhyphenation.lua:20: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/readerui.lua:290: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/readerui.lua:442: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:402: in function <frontend/apps/reader/readerui.lua:401>08/30/17-08:52:20 INFO  quitting uimanager
08/30/17-08:52:20 INFO  no dialog left to show
lipc-wait-event exited normally with status: 0

Anyone knows how to fix it?

**Comment by Frenzie** [comment]
There should be a `/mnt/us/documents/A Fazenda Pública em Juízo - Leonardo Carneiro da Cunha - 2017` which you could try deleting, but what did you do exactly?

**Comment by Eduardomb22** [comment]
Nevermind...U can close/delete this.
