### ISSUE TITLE
no synch server update since aug, 12 ?

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3159]
OTA doesn't update... It already happened and easily missed, so I guess it's worth mentioning.

cf http://koreader.ak-team.com, etc.

**Comment by Frenzie** [comment]
Unless you mean specifically within the past half hour or so, as I was restarting some stuff on the koreader.rocks server, that one should be fine.

**Comment by cramoisi** [comment]
there is no update after aug, 12 2017 on all the OTA mentioned in the code. (otamanager.lua)

        "http://ota.koreader.rocks:80/",
        "http://vislab.bjmu.edu.cn:80/apps/koreader/ota/",
        "http://koreader-eu.ak-team.com:80/",
        "http://koreader-af.ak-team.com:80/",
        "http://koreader-na.ak-team.com:80/",
        "http://koreader.ak-team.com:80/",
        "http://hal9k.ifsc.usp.br:80/koreader/",

**Comment by Frenzie** [comment]
Not sure what is happening for you but there definitely is on the first one.

**Comment by cramoisi** [comment]
erf, i didn't try the first one :p

**Comment by Frenzie** [comment]
@cramoisi Is the sync server okay too?
