### ISSUE TITLE
Crashed when login 印象笔记 (Chinese version Evernote)

### ISSUE THREAD

**Issue by holyblade** [koreader/koreader#3174]
* KOReader version:1182-gdbaea8c
* Device:Kobo Glo

#### Issue
It's fine when login International Evernote, but koreader will crash when login 印象笔记(Chinese version Evernote).

**Comment by Frenzie** [comment]
Are these accounts free or are there any testing accounts available? Random user/pass just gives me "Incorrect username or password" on both, no crashes.

**Comment by holyblade** [comment]
@Frenzie 
account: tonyembers@yeah.net
password: qwertyui

**Comment by Frenzie** [comment]
I didn't get any crashes on either the emulator or my H2O (but it took quite a while to login, presumably because it's in China). Do you have a crash.log?

**Comment by holyblade** [comment]
@Frenzie 
I found that the test account did not crash, but when log in my account, it crashed. Maybe too many notes?

Crash.log shows below.

./luajit: plugins/evernote.koplugin/main.lua:257: attempt to call method 'find' (a nil value)
stack traceback:
	plugins/evernote.koplugin/main.lua:257: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:204: in function 'action'
	frontend/ui/uimanager.lua:518: in function '_checkTasks'
	frontend/ui/uimanager.lua:669: in function 'handleInput'
	frontend/ui/uimanager.lua:765: in function 'run'
	./reader.lua:190: in main chunk
	[C]: at 0x00013fc5

**Comment by Frenzie** [comment]
Okay, so it kind of happens in these lines.

https://github.com/koreader/koreader/blob/db6c35c14476c4f28fdc838ae5f97bccec47ccba/plugins/evernote.koplugin/main.lua#L294-L297

https://github.com/koreader/koreader/blob/db6c35c14476c4f28fdc838ae5f97bccec47ccba/plugins/evernote.koplugin/main.lua#L257-L259

I didn't write this and I don't use Evernote so unfortunately I don't really know what's going on. It looks like `guid` is supposed to be a string but apparently it's something else.

Could you change these lines (256)
```lua
    ok, guid = pcall(self.getExportNotebook, self, client)
    if not ok and guid and guid:find("Transport not open") then
```

to this?
```lua
    ok, guid = pcall(self.getExportNotebook, self, client)
require("logger").dbg("guid", guid)
    if not ok and guid and guid:find("Transport not open") then
```
and then give me the crash.log output again. Don't forget to obscure any personal info you might not want public. ;-)


PS You could also try changing line 257 to something like this in which case you might get a proper info message.
```lua
 if not ok and type(guid == "string") and guid:find("Transport not open") then 
```

**Comment by holyblade** [comment]
Wow, great, it works!! Thank you so much!

**Comment by Frenzie** [comment]
I beg your pardon? What worked? This is only supposed to give me something that I might be able to work with. :-P

**Comment by holyblade** [comment]
I thought these code fix the crash bug. But after I changed code, I login my Yinxiang(Evernote) account successfully, it indeed doesn't crash any more

**Comment by Frenzie** [comment]
I'll close this then, seeing how it needs more info but there's no way to collect it. :-)
