### ISSUE TITLE
Koreader Dutch Hyphenation support? / No dictionaries installed

### ISSUE THREAD

**Issue by ankiko** [koreader/koreader#3178]
* KOReader version: 2015,11*1182-gdbaea8c
* Device: Kobo Glo HD

#### Issue
I need Dutch hyphenation for Koreader but it don't work.

discussed also on https://www.mobileread.com/forums/showthread.php?t=261705&page=7

Can somebody please help me about that?

#### Steps to reproduce

- koreader/data/hyph/Dutch.pattern is already present. (also all of the dictionaries are present on the folder)
- When i look to koreader there it says "installed dictionaries (0)"
- Also switched interface language to english but no dictionaries.
- I did also make hard reset of my Kobo and then reinstalled KSM8, Koreader.

I need to use the hyphenation function, not the dictionary lookup.

**Comment by a-kohout** [comment]
You are confusing hyphenation rules with dictionaries for looking up words.
Koreader comes preloaded with hyphenation rules for several languages.
Dictionaries need to be installed manually

Hyphenation is here:
![screen shot 2017-09-06 at 00 38 23](https://user-images.githubusercontent.com/26367956/30086561-f10a40d4-929b-11e7-83c2-71e07d0d778f.png)

Then select "Dutch"
![screen shot 2017-09-06 at 00 38 32](https://user-images.githubusercontent.com/26367956/30086566-fbff381e-929b-11e7-8b5a-d5fbbc6a3c6c.png)

**Comment by ankiko** [comment]
[hyph.zip](https://github.com/koreader/koreader/files/1280971/hyph.zip)

When i chose dutch from the Hyphenation menu and chose a word on the book it found nothing. I have added zip file of the Hyphenanation. Can you please check the Dutch.pattern ?

**Comment by a-kohout** [comment]
It's not supposed to find anything. The hyphenation is there and working.
Hyphenation rules tells the reader where to break a word at the end of a line by adding a hyphen.
This causes a more evenly justified text.

This is a dutch ebook with Dutch hyphenation enabled. Note the dashes at the end of the line:
![screen shot 2017-09-06 at 14 29 32](https://user-images.githubusercontent.com/26367956/30112071-5256918e-9310-11e7-9085-69428e08238d.png)

This is with hyphenation turned off.
![screen shot 2017-09-06 at 14 30 53](https://user-images.githubusercontent.com/26367956/30112102-6f483d1a-9310-11e7-91db-4e2a797d2958.png)

**Comment by Frenzie** [comment]
…Tom Sawyer? 🤣 

@ankiko Waar ben je precies naar op zoek?

**Comment by ankiko** [comment]
![dutch woordenboek Koreader](https://user-images.githubusercontent.com/31673173/30112901-34c16d9e-9313-11e7-9db1-e3c369931703.jpg)

I have added a screenshot. When i click on a word i want to see information about that word in dutch language like on Nickel. 

See the screenshot of nickel. I need exactly that on koreader.

![dutch woordenboek nickel](https://user-images.githubusercontent.com/31673173/30113097-d899ea7c-9313-11e7-9c01-b196894f34d9.jpg)

**Comment by a-kohout** [comment]
Well since I don't speak dutch I thought to better pick something well-known instead of at random where I could have gotten hold of something weird 😀

**Comment by a-kohout** [comment]
Well then you're in the market for a dutch thesaurus.
I've found one here, not sure if it is any good though.
http://downloads.sourceforge.net/xdxf/stardict-comn_dictd04_muiswerk-2.4.2.tar.bz2

**Comment by ankiko** [comment]
Thank ou a-kohout. It works now on the Koreader. I am very happy with that. But...

Stardict dutch dictionary is very limited on words. It don't find most of the the words. Is it possible to use another dictionary file such as "Van Dale" as the nickel use and then convert it to Koreader format?

**Comment by a-kohout** [comment]
Stardict is the format supported by koreader, there might be more dutch dictionaries in this format somewhere on the internet...
Unfortunately Kobo obfuscates their dictionaries so they can't be converted.
Kobo dictionaries created by other people can be converted.
If you find a dictionary in another format like abby lingvo, babylon, etc. you can probably convert it with either penelope or pyglossary.
https://github.com/ilius/pyglossary
https://github.com/pettarin/penelope

**Comment by Frenzie** [comment]
I think doing something with Dutch Wiktionary might be the most promising
free option.

**Comment by Frenzie** [comment]
I'll close this since the misunderstanding was resolved. :-)
