### ISSUE TITLE
Which files can be deleted?

### ISSUE THREAD

**Issue by zhanggang807** [koreader/koreader#3180]
* KOReader version:
* Device:

#### Issue
After jailbreak succeed, which files can be deleted? Space almost run out.

**Comment by Frenzie** [comment]
Is this question related to Kindle? Either way, I'm surprised to hear that any jailbreak could make space run out unless you had very little to start with. :-)

**Comment by zhanggang807** [comment]
Yes, an old kindle , available space only has 1 GB, I have some big files in it which I do not want to delete. So I want to delete files useless.

**Comment by Frenzie** [comment]
I just glanced at the [wiki instructions for Kindle](https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices) and it doesn't really look like there's anything that can be removed. The jailbreak file is <100 kB, KUAL is pretty small too, KOReader itself seems to be the biggest of the bunch. In KOReader one of the few files that can be safely deleted that actually packs a percentual punch at 11.4 MB is probably NotoSansCJK-Regular.ttf, but judging by your username I assume that's not an option.

Maybe @NiLuJe has some tips?

**Comment by a-kohout** [comment]
`koreader/ota/koreader.installed.tar` wastes about 50MB if you've done an OTA update and can be safely deleted.

**Comment by Frenzie** [comment]
True, but without anything to compare to you'll download the full package rather than a differential.

**Comment by zhanggang807** [comment]
Thanks. I will check it.

**Comment by Frenzie** [comment]
I'll close this now. Let us know if you have any more questions. :-)
