### ISSUE TITLE
Does the bookmark browsing mode still works? 

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#3184]
* KOReader version: last nighty
* Device: ppw3

#### Issue
Bookmark browsing mode (only for PDF and DjVu)

Long press at the top right corner of the screen will bring you into bookmark browsing mode in which swipe left and right will show last and next bookmarked pages respectively. Another long press at the top right corner will exit back to normal reading mode
#### Steps to reproduce
I cant get it working. Anyone with the same problem.

**Comment by Frenzie** [comment]
It was changed last month in #3048. There's always been the choice between top left tap and top right hold, but top right hold was interfering with word selection. The wiki doesn't seem to have been changed, but it could without affecting older versions: https://github.com/koreader/koreader/wiki/Tips-and-Tricks#2-bookmark-browsing-mode-only-for-pdf-and-djvu

That being said, I think there are a few candidate places where this could be added to make it less easter-eggy.

![screenshot_2017-09-07_08-06-59-fs8](https://user-images.githubusercontent.com/202757/30148459-ce6acb30-93a3-11e7-9793-0299cdeee455.png)
![screenshot_2017-09-07_08-07-06-fs8](https://user-images.githubusercontent.com/202757/30148460-ce6b3408-93a3-11e7-953f-a4e8c587c765.png)
![screenshot_2017-09-07_08-11-08-fs8](https://user-images.githubusercontent.com/202757/30148542-3056649e-93a4-11e7-8eb3-bff7f41ae5a0.png)

**Comment by Frenzie** [comment]
Actually, there's also regular page flipping mode.

@robert00s Could it be that we're currently left with no way to toggle bookmark flipping mode, only page flipping mode?

**Comment by robert00s** [comment]
Flipping mode (only in pdf/djvu) doesn't work on Kindle see: https://github.com/koreader/koreader/issues/2599 It's a bug.
We can toggle flipping mode when we tap on top left corner.

**Comment by Frenzie** [comment]
@robert00s In page flipping mode you can click on the progressbar to quickly do to a specific location in the book (just like skim mode) or perform some gestures to go through a multiple of pages.

In bookmarks mode you can swipe left and right to go the next/previous bookmark. You can also still tap regularly to go to the next/previous page and use the progressbar to quickly go to a specific location in the book.

Imo bookmark browsing mode is significantly more useful, although truth be told I don't really use either so I failed to realize the implications of your change.

**Comment by robert00s** [comment]
I didn't know about it. We definitely need to upgrade the wiki :)
