### ISSUE TITLE
CSS: Issue with pt value

### ISSUE THREAD

**Issue by webstatic** [koreader/koreader#3189]
* KOReader version: : v2017.08.21-nightly
* Device: kobo mini , kindle pw , and other I think.

#### Issue
Every pt value in css recognize as 0.

I think easiest way is to convert every pt to px with this.
px = (pt*dpi)/72

**Comment by robert00s** [comment]
Similar to: #1010

**Comment by Frenzie** [comment]
Also see https://github.com/koreader/crengine/pull/46#issuecomment-216431151

**Comment by poire-z** [comment]
Fixed by #4040.
