### ISSUE TITLE
CSS rendering regression

### ISSUE THREAD

**Issue by a-kohout** [koreader/koreader#3192]
* KOReader version: v2015.11-1191-g75b7c4b
* Device: Kobo Glo HD, Emulator

#### Issue
A recent update has introduced a rendering bug in the following scenario:
Centered heading is followed by justified text not contained in `<p>` tags.
This is is how it looks on current master:
![reader_2017-sep-08_221237](https://user-images.githubusercontent.com/26367956/30233286-cee426ea-94f4-11e7-9755-ee00b2cc8cd1.png)

It used to render correctly on v2015.11-1050-g0a02b52:
![reader_2017-sep-08_221207](https://user-images.githubusercontent.com/26367956/30233316-11e0dcd6-94f5-11e7-9acd-d3280a4ac849.png)

#### Steps to reproduce
[untitled.epub.zip](https://github.com/koreader/koreader/files/1289253/untitled.epub.zip)

**Comment by poire-z** [comment]
Confirmed, and like #3187, seems ok when reverting the lvtinydom autoboxChildren stuff from https://github.com/koreader/crengine/commit/090059e18346f6851e2836cd117be2021c795a58 / https://github.com/koreader/crengine/pull/73 .

**Comment by frankyifei** [comment]
it mixed the first paragraph with the title, not good. I did not test last patch with this circumstances. reverting the patch will give us random crash problem, so it is better to keep it until we find another way.
