### ISSUE TITLE
Statistics at the end of book isn't synched with new statistics thus empty

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#3196]
* KOReader version: b1190
* Device: Kobo H2O

When you finish a book and turn last page, there's a screen with some statistics info, book cover, etc.

Statistics in that screen doesn't reflect actual statistics we can see in new statistics plugin. Maybe this screen needs to be synched with new statistics plugin?

For me all statistics where empty (read for 0 days, read 0 pages, for zero time).

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by robert00s** [comment]
Oh, I need to reorganize Book status.
