### ISSUE TITLE
Search in Google Images

### ISSUE THREAD

**Issue by checcousero** [koreader/koreader#3205]
* KOReader version: 2015.11-1054-g6870bc2
* Device: Kobo Glo HD
I'm a Kobo user and I use very often the dictionary.  
When I'm on Android I use a reader that can search on Google Images: it's a bless!
Search on Google Images would be a very useful and quick way to comprehend the meaning of a word. 
I hope this feature is not too difficult to implement and that we will get it.

**Comment by Frenzie** [comment]
Just out of curiosity, which program is "a reader"? ;-)

**Comment by Frenzie** [comment]
I'll close this for the moment but if anyone's interested in implementing something like this please let us know.
