### ISSUE TITLE
Default Spanish Hyphenation:

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#3212]
```
{
        "name": "Spanish",
        "filename": "Spanish_hyphen_(Alan).pdb",
        "language": "es",
        "aliases": ["spa"]
    },
```
should be

```
{
        "name": "Spanish",
        "filename": "Spanish.pattern",
        "language": "es",
        "aliases": ["spa"]
    },

```
because it's avaliable rightnow and in my opinion as native in this language it works better. 
Probably the "Spanish.pattern or Spanish*.pdb" could be improved but this is other subject...

Regards.

**Comment by Frenzie** [comment]
Ah, that's definitely a bug. (The file in question is https://github.com/koreader/crengine/blob/e2dc17c4721f52077932b1948a44022e403ed759/cr3gui/data/hyph/languages.json)

The superior pattern was added in https://github.com/robert00s/crengine/commit/156c5bcb4944397ea5b70c45a2e57c1bfa14a40e#diff-8458e05c8b3448366c96aa850d4e7ddd and recently updated in https://github.com/robert00s/crengine/commit/aad1eeee4c66a36c8229bbe411d2453f406f8f2a#diff-8458e05c8b3448366c96aa850d4e7ddd and yet no one was able to profit from it for the past three years. 🤦‍♂️ (not sure why there's such a thing as a man facepalming smiley, but it fits).

**Comment by Frenzie** [comment]
@djalma2k Would you like to submit a PR to fix the issue? :-)

**Comment by Frenzie** [comment]
My apologies. I decided to protect against this ever happening again so I included the fix as part of that in https://github.com/koreader/crengine/pull/85 😊

**Comment by djalma2k** [comment]
Np, much better this way. Thanks.
> The superior pattern was added in koreader/crengine@156c5bc#diff-8458e05c8b3448366c96aa850d4e7ddd and recently updated in koreader/crengine@34d73f4 **and yet no one was able to profit from it for the past three years.**

Well, really I have a minor script for sort out this type of things when I update the program every now and then...but yes probably I must had reported it sooner... In this case, I was thinking that you let it there (*.pattern file) as a legacy file or as an option (it don't harm anyone :P ) and yeah the latest update https://github.com/koreader/crengine/commit/34d73f4a2c4a4a1c632d3d22e7034a7e7999f824 shock me a little bit xD... 

Anyway, it's good to see it solved :)

**Comment by Frenzie** [comment]
I see. So it's https://github.com/koreader/crengine/commit/920f5a3f6b0d0c3a0f3d137d8ebf524422cba2cb

> Well, really I have a minor script for sort out this type of things when I update the program every now and then...

Do tell! :-)

**Comment by djalma2k** [comment]
> Do tell! :-)

Hahaha you know...  curiosity killed the cat ...xD I'm guessing that I'm going to disappoint you but it's no big deal...minor means exactly this ...literally xD And yes I had to do it since 2015 for several reasons: change values in cr3.ini and other files I didn't remember (not using this currently), change languages.json and adding custom hyphen files to try them all, change some menu items in the gui that bother me a little bit... [reader_menuorder.lua] (fixed currently), etc,... small "fixes" or "try outs" that "come and go"...

**Comment by Frenzie** [comment]
Still sounds neat. :-)

**Comment by djalma2k** [comment]
Please, could you update/"bump" crengine version? It would be the only thing left to close the matter, isn't it? ;) "~~_God_~~ Prs _willing_..."

**Comment by Frenzie** [comment]
Oh yeah, I can do that now. I had to resolve https://github.com/koreader/koreader-base/pull/508 in some way first (whether by reverting or fixing). :-)
