### ISSUE TITLE
Follow link wrong footnote number

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#3216]
* KOReader version: v2015.11-1208-gb617efa
* Device: ppw3

When I click on a footnote it goes to the wrong number. At the example below I clicked at "13" and it goes to the footnote number "18". I´m getting this bug with all epubs and it was working fine with 1195 or 1200

Video https://youtu.be/wt4ZLJLsiGI

**Comment by Frenzie** [comment]
v2015.11-1195-gc948472 and v2015.11-1200-g9dee6c0

Makes for these commits (1195):
https://github.com/koreader/koreader/compare/c948472...b617efa

Or these (1200):
https://github.com/koreader/koreader/compare/9dee6c0...b617efa

Would it be possible for you to test whether 1200 still works? I think #3207 looks the most suspicious as it actually goes into the link following logic but it'd help in narrowing it down.

[koreader-kindle-arm-linux-gnueabi-v2015.11-1200-g9dee6c0.zip](https://github.com/koreader/koreader/files/1300831/koreader-kindle-arm-linux-gnueabi-v2015.11-1200-g9dee6c0.zip)

**Comment by Eduardomb22** [comment]
If I use swipe to follow nearest link, it works fine. Only the tap to follow links is bugged. I will test with 1200

**Comment by Eduardomb22** [comment]
It isn´t working with 1200. So I think it worked fine with 1195

**Comment by Frenzie** [comment]
Could you check that too please? I'm not sureif I can reproduce this atm.

[koreader-kindle-arm-linux-gnueabi-v2015.11-1195-gc948472.zip](https://github.com/koreader/koreader/files/1300881/koreader-kindle-arm-linux-gnueabi-v2015.11-1195-gc948472.zip)

**Comment by Eduardomb22** [comment]
Isn´t working with 1195 neither.

**Comment by Eduardomb22** [comment]
Thanks for the fast reply @Frenzie

**Comment by poire-z** [comment]
There must be a +1 or -1 missing somewhere. When you tap on a link, you get to one page before the good page, and you have the new vertical marker at the right position where the link is in the next page. Strange :)

**Comment by Frenzie** [comment]
v2015.11-1190-g2b3b310

https://github.com/koreader/koreader/compare/2b3b310...c948472

Logically that must mean I introduced it in #3190, except I didn't actually touch the *go to* link part. :confused:

**Comment by poire-z** [comment]
Looks like onTap and onSwipe (around the same link) **do** get the same xpointer and go to the same page:

```
09/13/17-23:05:45 DEBUG swipe west 94.191294714533 detected in slot 0
09/13/17-23:05:45 DEBUG AutoSuspend: onInputEvent
09/13/17-23:05:45 DEBUG clear selection
09/13/17-23:05:45 DEBUG onGotoLink: #_doc_fragment_0_ cite_note-Imber2002244-45
09/13/17-23:05:45 DEBUG Internal link: #_doc_fragment_0_ cite_note-Imber2002244-45
09/13/17-23:05:45 DEBUG CreDocument: goto page 53

09/13/17-23:07:04 DEBUG single tap detected in slot 0 {
    ["y"] = 192,
    ["x"] = 566,
    ["h"] = 0,
    ["w"] = 0
}
09/13/17-23:07:04 DEBUG AutoSuspend: onInputEvent
09/13/17-23:07:04 DEBUG onGotoLink: #_doc_fragment_0_ cite_note-Imber2002244-45
09/13/17-23:07:04 DEBUG Internal link: #_doc_fragment_0_ cite_note-Imber2002244-45
09/13/17-23:07:04 DEBUG CreDocument: goto page 53
09/13/17-23:07:04 DEBUG CreDocument: check xpointer in current page /body/DocFragment/body/h2[2]/text().0
```
But just after that, with Tap, this happens:
```
09/13/17-23:07:04 DEBUG update battery state
09/13/17-23:07:04 DEBUG CreDocument: set battery state 0
09/13/17-23:07:04 DEBUG clear selection
09/13/17-23:07:04 DEBUG document has no pages at {
    ["page"] = 53,
    ["x"] = 566,
    ["w"] = 0,
    ["y"] = 192,
    ["h"] = 0
}
09/13/17-23:07:04 DEBUG goto relative screen: 1 , in mode:  page
09/13/17-23:07:04 DEBUG CreDocument: goto page 54
09/13/17-23:07:04 DEBUG CreDocument: check xpointer in current page /body/DocFragment/body/h2[2]/text().0
```

Feels like a missing "return true", and tap being processed by another onTap as a next/prev page.

**Comment by Frenzie** [comment]
Ah, there you have it. In normalizing between PDF and EPUB I inadvertently got rid of that. It was never there for PDFs.

**Comment by poire-z** [comment]
Confirming prepending just this `return` to that line solves the problem.
Are you making a PR or should I ? (is editing the file via github ok for such a small changes ? does that creates a commit ?)

**Comment by Frenzie** [comment]
Sure, go ahead. The GH editor is fine. It lets you choose whether to commit straight to master or to make a PR. Generally a PR is preferred for obvious reasons, but feel free to try it for this simple change. ;-)
