### ISSUE TITLE
KOReader exited irregularly

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#3219]
* KOReader version: Last nightly
* Device: Kobo Mini

#### Issue
I hadn't updated KOReader in several days. After updating it yesterday, whenever I exit KOReader with the menu options Exit> Exit,  I find a message in Kobo Start Menu that says:
KOReader exited irregularly. Turn off or Continue.
I have updated again KOReader with the nightly build available this morning and the problem continues.

**Comment by Frenzie** [comment]
Btw, you can also hold on exit if you prefer.

I haven't come across this problem. The most suspicious thing that happened would be #3206.

Could you try this frontend/apps/reader/modules/readermenu.lua without that change to see if that's responsible?
[readermenu.lua.zip](https://github.com/koreader/koreader/files/1305568/readermenu.lua.zip)

**Comment by retrue** [comment]
Hi
I did just that and the problem continues. It thinks the problem is elsewhere-
It could have been any change in the last 7 ~ 10 days. I usually update KOReader almost every day, but I had not done that lately.

**Comment by Frenzie** [comment]
I think the only other change directly dealing with exit was #3171.

Could you share the crash.log?

**Comment by retrue** [comment]
There you go:

`---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 09/15/17-16:21:28

09/15/17-16:21:28 ERROR cannot open translation file: l10n/en_US/koreader.po
09/15/17-16:21:29 INFO  initializing for device Kobo_pixie
09/15/17-16:21:29 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
[ko-input] Forked off fake event generator(pid:797).
09/15/17-16:21:31 INFO  Loading plugins from directory: plugins
09/15/17-16:21:31 INFO  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
09/15/17-16:21:31 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
09/15/17-16:21:32 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
09/15/17-16:21:32 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin storagestat at plugins/storagestat.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
09/15/17-16:21:32 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
09/15/17-16:21:33 INFO  opening file /mnt/onboard/My books/Ben Aaronovitch/Ben Aaronovitch - Rivers 06 - The Hanging Tree.epub
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Amasis-Bold.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Amasis-BoldItalic.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Amasis-Italic.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Amasis.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Avenir-Bold.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Avenir-BoldItalic.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Avenir-Italic.ttf>
09/15/17-16:21:33 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Avenir.ttf>
09/15/17-16:21:34 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Caecilia-Bold.ttf>
09/15/17-16:21:34 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Caecilia-BoldItalic.ttf>
09/15/17-16:21:34 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Caecilia-Italic.ttf>
09/15/17-16:21:34 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Caecilia.ttf>
09/15/17-16:21:35 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/FreeSans.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/FreeSerif.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/GillSans-Bold.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/GillSans-BoldItalic.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/GillSans-Italic.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/GillSans.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Gothic MB101.otf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/KoboNickel-Bold.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/KoboNickel-BoldItalic.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/KoboNickel-Italic.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/KoboNickel.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Malabar-Bold.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Malabar-BoldItalic.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Malabar-Italic.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Malabar.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSans-Bold.ttf>
09/15/17-16:21:36 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSans-BoldItalic.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSans-Italic.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSans.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSerif-Bold.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSerif-BoldItalic.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSerif-Italic.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/NotoSerif.ttf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/OpenDyslexic-Bold.otf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/OpenDyslexic-BoldItalic.otf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/OpenDyslexic-Italic.otf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/OpenDyslexic-Regular.otf>
09/15/17-16:21:37 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/Ryumin.otf>
09/15/17-16:21:38 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/georgia.ttf>
09/15/17-16:21:38 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/georgiab.ttf>
09/15/17-16:21:38 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/georgiai.ttf>
09/15/17-16:21:38 ERROR failed to register crengine font cannot register font </mnt/onboard/fonts/georgiaz.ttf>
09/15/17-16:21:38 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin storagestat at plugins/storagestat.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
09/15/17-16:21:38 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
09/15/17-16:21:43 WARN  sizeUtf8Text called without text
09/15/17-16:21:43 ERROR failed to register widget readerstoragestat plugins/storagestat.koplugin/main.lua:53: bad argument #1 to 'insert' (table expected, got nil)
09/15/17-16:21:49 INFO  no dialog left to show
09/15/17-16:21:49 INFO  quitting uimanager
./luajit: frontend/device/kobo/nickel_conf.lua:129: attempt to compare number with nil
stack traceback:
	frontend/device/kobo/nickel_conf.lua:129: in function 'set'
	frontend/device/kobo/powerd.lua:110: in function 'saveSettings'
	frontend/device/kobo/device.lua:496: in function 'saveSettings'
	./reader.lua:194: in function 'exitReader'
	./reader.lua:213: in main chunk
	[C]: at 0x00013fc5
`

**Comment by Frenzie** [comment]
It's three backticks for a code block. :-)

My best guess is that it would be related to #3163.

[koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1182-gdbaea8c.zip](https://github.com/koreader/koreader/files/1306661/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1182-gdbaea8c.zip) (before)
[koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1187-g2a0e424.zip](https://github.com/koreader/koreader/files/1306663/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1187-g2a0e424.zip) (after)

**Comment by poire-z** [comment]
Is there a frontlight on Kobo Touch ?
If not, may be just a forgotten `if self.device.hasFrontlight()` somewhere (probably in `KoboPowerD:saveSettings()`), that would be easy to add, as we should not update nickel conf if there is no FrontLightLevel in Kobo ereader.conf, or we have no value to update it with.

**Comment by retrue** [comment]
I have a Kobo Mini and they don't have light.
There was a bug last year where the newer versions of KOReader didn't start in my Kobo Mini because of the lack of frontlight.

**Comment by poire-z** [comment]
Please confirm when you next install a nightly that it is fixed (seems an obvious fix, but as I can't test, who knows...)

**Comment by retrue** [comment]
Patch works  👍 
Thanks!

**Comment by Frenzie** [comment]
@poire-z Is there a simple unit test imaginable to guard against this in frontlight_spec? (You'd have to set Device.isKobo and some other fakery.)

**Comment by poire-z** [comment]
Probably, but my imagination suddenly gets blank when I hear _unit tests_ :|
I know it's nice to have, but the whole unit test infrastructure (mock/stub/spy...) is a bit over my head, and I know it would take me hours to comprehend, and I'm not ready for that :)
Anyway, probably not in frontlight_spec (which is just doing some stuff with powerd directly), but probably in device_spec.lua, where there is already a test for kobo dahlia: could have a test with kobo mini, that should init() and exit device, or just :saveSettings() not failing.
(I don't have the test environment on my linux, so I would have to validate tests on travis, which would again take hours...)

**Comment by Frenzie** [comment]
Yeah, you *definitely* shouldn't be writing unit tests without the ability to run them in seconds. :-)

**Comment by Frenzie** [comment]
Anyway, a slightly more involved unit test is basically a detailed specification of how the function is supposed to work (see [the first one](https://github.com/koreader/koreader-base/blob/999741af6df4dbd0cfc81fa787ba960edf2313a7/spec/unit/util_spec.lua#L15-L98) I wrote for KOReader). But even a [lame little stub](https://github.com/koreader/koreader/blob/5ea7c703e0047c8394c90c99763ccf159eb15dec/spec/unit/wikipedia_spec.lua) is a good starting point imo. ;-)

**Comment by poire-z** [comment]
I did a few (util, some string stuff) when it was as easy as copy/pasting existing ones and changing input and expected output. But when it involves hardware or higher level stuff, and the need to fake some real environment, I'm just clueless and walking away :|

**Comment by Frenzie** [comment]
Well, I'm not suggesting a "proper" test. Just the most basic combination of isKobo and hasFrontlight == false. Anyway, just something to think about. ;-)
