### ISSUE TITLE
Koreader stuck on cover screensaver after usb safe removal

### ISSUE THREAD

**Issue by slow-mo** [koreader/koreader#3220]
* KOReader version: v.2015.11-1190-g2b3b310
* Device: kindle PW2

#### Issue
It seems that koreader gets stuck on your last book cover if you connect your device to a pc via usb while the cover screensaver is active.
(it may be some faulty interaction with the screensaver hack by NiLuJe?)

#### Steps to reproduce
1. In koreader, select last book's cover as screensaver
2. Put the device in standby
3. Connect the device to a pc with the usb cable
4. Safe remove and unplug the device
5. Koreader is stuck on cover screensaver

**Comment by Frenzie** [comment]
If the USB connection unsuspends the device, you might be able to suspend/unsuspend again to get rid of it.

There is some handling of USB plugging/unplugging with an explicit exception for screensaver mode:

https://github.com/koreader/koreader/blob/7c88bad18921ec60ccdd6fa4b8a261b5d4161048/frontend/device/kindle/device.lua#L121-L133

**Comment by slow-mo** [comment]
No, I tried to suspend/unsuspned, but the only way to exit the scrensaver is to reboot the device with a long press on the power button.

**Comment by Frenzie** [comment]
Pinging @NiLuJe @robert00s as I don't own or really know much of anything about Kindle. :-)

**Comment by NiLuJe** [comment]
The screensaver hack should at most vie you the wrong "screensaver", but that's it.

I kind of lost track of which one is currently supposed to "win" on current FWs (KOReader's, or my hack's), but that shouldn't be relevant for this issue.

So, yeah, I suppose something is going awry and the WM is never sent a SIGCONT?

Assigning myself so I know to try to take a look at this when I have some time...

**Comment by NiLuJe** [comment]
On FW >= 5.7.2, there's no interaction with the default screensavers possible, because we SIGSTOP the WM.

I probably never tested this in any other mode than USBNet, so there's a possibility that things go wonky w/ USBMs, where we probably need to SIGCONT something but we don't?

**Comment by NiLuJe** [comment]
Wait. You just can't put a Kindle in USBMS mode while KOReader is up (well, you *can*, but you really shouldn't).

You can if you start with the framework still up, because volumd is still up. But you shouldn't, because we live in the userstore, if you unmount that from under us, kablooey.

Hell, even without the framework, I'm not sure if shit still won't happen.

**Comment by NiLuJe** [comment]
And I'm fairly sure stopping/starting volumd ourselves during startup/shutdown would likely wreak havoc on the native system.

So it's pretty much a case of don't plug anything to that device unless you're in USBNet mode.

**Comment by NiLuJe** [comment]
And starting without the framework is a terrible idea, because it generally doesn't work all that well on modern FWs (no power button to no buttons).

**Comment by NiLuJe** [comment]
Flagging this wontfix, even if this is more of a cantfix ;).
