### ISSUE TITLE
Can't turn on Wifi on Kindle Paperwhite 3

### ISSUE THREAD

**Issue by dantopa** [koreader/koreader#3225]
* KOReader version: 2015.11-1152-gabaa699
* Device: Kindle Paperwhite 3 firmware 5.8.10

#### Issue
I can't turn the wifi on, when I try to connect, always prompt me if I want to turn the wifi on, if I select yes nothing happens.
#### Steps to reproduce
Go to settings, network, wifi connection. Then appears a windows asking if I want to turn the wifi on. I choose "Turn on", and nothing happens. I can repeat this process again and again and never connects to wifi.

**Comment by robert00s** [comment]
Settings -> Network -> Wifi connection, then when window assking if you want to enable wifi tap on enable. Then exit from menu and again go to Settings -> Network you should see wifi enabled. Check connection for example search some word in Wikipedia.
Of course we should add info that wifi is on or off and refresh info in menu (or close menu).

**Comment by dantopa** [comment]
Nope, not working for me. For example, if I try to look for updates, the same window appears, asking to turn on the wifi. Of course I push enable, but when I try to find updates again, the same cycle happens.

**Comment by robert00s** [comment]
Do you have configure wifi network on Kindle native system?
I have configured the network in kindle and then I can turn on / off the network in KO.

**Comment by dantopa** [comment]
Yes of course, wifi on native system is working great. Also, I'm running koreader via kual. Do you have wifi working on kindle pw3 with latest firmware? Seriously I don't know what are the issue, I also tried with the stable version and is the same. Maybe there is a way to log the errors or something.

**Comment by robert00s** [comment]
I have 5.8.2 firmware. I don't want to upgrade to newer version because I worried about my jailbreak :)
Maybe it's problem with 5.8.10 firmware.
You can additionally check run this command from terminal plugin
`lipc-set-prop com.lab126.cmd wirelessEnable 1`

**Comment by dantopa** [comment]
This bug is fixed on latest developing versions, closing.
