### ISSUE TITLE
REAGL on Kobo (and question for Kindle users)

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3230]
Been playing with REAGL/REGAL waveform (see #550 and others), that seems supported on my Kobo Glo HD, and probably is on other recent Kobo.
It's a bit different from the usual partial refresh (a bit faster, a bit ugly as letters morph into the next ones:), so I'm not sure it's really interesting (and may be it just feels faster because the morphing is happening quickly).
Anyway, it's the default mode on Kindles.

There are some occasions where it is really worse, which could be solved by using a "ui" refresh instead of the default "partial" refresh.
I wonder if it's the same on kindle, so could Kindle users check and tell me how the following behave on their device:

Dict lookup, multiple result: when using `>>` to see next result:
1a) only the title and definition texts are updated, the dict window stays and is not redrawn
1b) it feels like the dict windows is closed and a new one redrawn (because borders are refreshed, and morph into white)

Wikipedia Save as epub, when downloading images:
2a) Only the numbers 4 / 19 feels updated in a single InfoMessage
2b) It looks like the InfoMessage is closed and a new one shown for earch Fetching Image 4 / 19...

I get 1a) and 2a) on my Kobo with default refresh, but 1b) and 2b) when I use REGAL waveform.
What do you get on Kindle ?

(If you get 1b or 2b, there are some work to be done - otherwise, I won't bother "fixing" REGAL on Kobo).

Oh, and:
3) do you get a double full refresh when opeining a book ?

**Comment by poire-z** [comment]
@robert00s , as I know you have a kindle :) could you please tell me how that do on your kindle ?

**Comment by robert00s** [comment]
I have v2015.11-1190 version of KO.
I don't know how to enable/disable REAGAL :)


> Dict lookup, multiple result: when using >> to see next result:

1b)

> Wikipedia Save as epub, when downloading images:

2b)

> 3) do you get a double full refresh when opeining a book ?

Yes and it is a little annoying :)

**Comment by poire-z** [comment]
Thanks!
And you don't enable/disable this mode, it's decided according to device type in base/ffi/framebuffer_mxcfb.lua , and most Kindle have it be used for `partial` refreshes.
It's supposed to give less ghosting when refreshing pages (partial refresh, not the full flashing refresh).
And, by default, when closing a widget, koreader uses `partial` refresh, so this REAGL mode on Kindle, which may be not the best one for our UI stuff.
This could be changed (I think, haven't tested yet) by using more stuff of that kind in some onCloseWidget() methods:
```
    UIManager:setDirty(self, function()
        return "ui", self.dimen
    end)
```
which all Kindle could benefit from.

**Comment by Frenzie** [comment]
I think Nickel uses REAGL to display the menu (which is nice and fast) but then does a full screen refresh when closing it. Basically like you said.

**Comment by robert00s** [comment]
@poire-z Do you thnik that 

> 3) do you get a double full refresh when opeining a book ?

may be related to this issue #1955?
Do you have idea how to remove double full refresh no start?

**Comment by poire-z** [comment]
Not yet. Last time I had a look, I thought it may be the multiple `self.ui:handleEvent(Event:new("UpdatePos"))` in:

frontend/apps/reader/modules/readertypeset.lua
frontend/apps/reader/modules/readerfont.lua
 (and may be the delayed one marked as "Dirty hack" there).

In each of these file, in their onReadSettings, they are calls to other methods that send this UpdatePos event. And some onUpdatePos marks the screen with setDirty, so to be refreshed next time UIManager gets control back.

It may be a timing problem, for it to happen only when using REAGL refresh, cause it does not happen on kobo (who don't have it enabled).
I haven't had time to experiment more about that.

**Comment by poire-z** [comment]
@robert00s : double refresh on opening should be fixed by #3300.

For items 1b) and 2b), could you check how it does it you replace in:
https://github.com/koreader/koreader/blob/ceb7cf9771a5da8e23bf35a7e57f144d34b81fb2/frontend/ui/widget/dictquicklookup.lua#L469-L475
and
https://github.com/koreader/koreader/blob/ceb7cf9771a5da8e23bf35a7e57f144d34b81fb2/frontend/ui/widget/infomessage.lua#L144-L147

the 2 + 1 `"partial"` with `"ui"`

I think it should give you 1a) and 2a) like we have on Kobo.
But I'm interested in the quality of the refresh / redrawing of the text or images that were below these widgets when these widgets are closed. Is the quality the same or worse with `"ui"` ?

**Comment by robert00s** [comment]
No I have 1a) and 2b) but quality is a little worst.
I see ghosting that two lines
![screenshot 2017-10-05 17-30-05](https://user-images.githubusercontent.com/22982594/31236090-67988850-a9f3-11e7-9438-4eeece153dde.jpg)

Others looks OK.

**Comment by poire-z** [comment]
Could be the "ui" refresh mode is not good with grey lines (and texts like "Follow link") :| so anything with buttontables shoud still use `partial`...

**Comment by poire-z** [comment]
Oh, and if you change only the first `"partial"` to `"ui"` , and let the onCloseWidget one to `"partial"` ?
https://github.com/koreader/koreader/blob/ceb7cf9771a5da8e23bf35a7e57f144d34b81fb2/frontend/ui/widget/dictquicklookup.lua#L469-L475

**Comment by robert00s** [comment]
Now It works really nice. No ghosting and I have 1a) and 2a) :+1:

**Comment by poire-z** [comment]
Good :) So, it's worth commiting for kindle users? No one would regret the flashy behaviour?

**Comment by robert00s** [comment]
Of course :)
Btw. I also notice that when I change upper menu (eg. Setting to Tools) all screen flash (menu and reader) like UIManager:setDirty("all", "full"). Bottom menu hasn't got that problem. Any ideas?

**Comment by Frenzie** [comment]
As an aside (since you guys are looking at this), I noticed that the terminal emulator showed its output rather… fuzzily on my H2O. Not sure why since it just looks like a `TextViewer`.

**Comment by poire-z** [comment]
> Btw. I also notice that when I change upper menu ...all screen flash 

I didn't notice that with my REAGL Kobo. But I just managed to reproduce it. For me:
Open book > use top menu : no full screen flash. Open bottom menu, tap anywhere to close it. Use top menu: full screen flash now...
Is it the same for you ?

**Comment by poire-z** [comment]
> the terminal emulator showed its output rather… fuzzily 

I don't see anything strange with "./sdcv --help". And it's not a `TextViewer`, just an `InfoMessage `with no icon. May be just upgrading it to TextViewer would solve the fuzzyness you see then ?

**Comment by Frenzie** [comment]
InfoMessages can scroll? Huh.

**Comment by Frenzie** [comment]
This actually looks better than it did previously but you get the idea:

![2017-10-06 22 15 03](https://user-images.githubusercontent.com/202757/31296793-e55ea5bc-aae3-11e7-8bf6-78c64f56926c.jpg)

**Comment by poire-z** [comment]
Never seen anything as hideous as that :)
Try upgrading it to TextViewer, just to see.

**Comment by Frenzie** [comment]
Maybe tomorrow. :-P

**Comment by robert00s** [comment]
> I didn't notice that with my REAGL Kobo. But I just managed to reproduce it. For me:
Open book > use top menu : no full screen flash. Open bottom menu, tap anywhere to close it. Use top menu: full screen flash now...
Is it the same for you ?

First open top menu - no flash.
Change top menu position (tap on any icon) - flash (full refresh).
Go to submenu (eg. typeset -> font) - flash (full refresh)

**Comment by poire-z** [comment]
> Btw. I also notice that when I change upper menu ...all screen flash

This should solve it:
```lua
--- a/frontend/apps/reader/modules/readerconfig.lua
+++ b/frontend/apps/reader/modules/readerconfig.lua
@@ -105,6 +105,7 @@ end

 function ReaderConfig:onCloseCallback()
     self.last_panel_index = self.config_dialog.panel_index
+    self.config_dialog = nil
     self.ui:handleEvent(Event:new("RestoreHinting"))
 end

```
When both menu are open, the refreshes of each don't overlap, so they can't be combined, and it fallbacks to a full refresh. It should happen again when both menu are displayed and one is getting closed.
But previously, the bottom menu, thus no more shown, was still existing, and was setting the bottom area dirty, so full refresh as explained just above kept happening.

**Comment by robert00s** [comment]
Cool. Now full refresh is only when top menu is opened and bottom menu is closing.
