### ISSUE TITLE
FR: Add "Back" button to statistics plugin

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#3235]
Statistics plugin is really great, I started to look in my reading statistics now much more, but all the time I can go only in one way. And I need to exit at lowest level of info. It would be great if I can use statistics plugin like part of menu, to go up and down within statistics data and exit at my wish, not when I have to.

Adding "Back" button next to exit (X) button would be great improvement of great plugin in my opinion.

**Comment by robert00s** [comment]
Done in #3267.
