### ISSUE TITLE
FR: Enable access to book information within all statistics info, even for already read books

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#3236]
Now we can see book info only when we read that book (current book statistics). It would be really great if we can access this info even for already read books. I don't know if it is possible, don't know how statistics is actually organized, but it would be great.

For example, if we go to all books, we see all books and reading time for them. It would be great if we could tap on a book and see book info for that particular book, like it is current book info.

Also, when looking in days, we see info how many hours we read. It would be great if we could tap a day, it opens info on book(s) we read that day with info pertaining to that day, and if we tap on book, we receive book info for that book.

And it works in all menus, that we can access particular book info.

Hope it could be done without too much changes in plugin...

**Comment by robert00s** [comment]
> Now we can see book info only when we read that book (current book statistics). It would be really great if we can access this info even for already read books. I don't know if it is possible, don't know how statistics is actually organized, but it would be great.


Something like that _Reading statistics -> All Book -> selected book_:

![screenshot 2017-09-23 14-51-26](https://user-images.githubusercontent.com/22982594/30773352-0149c9b6-a06f-11e7-87e2-f7070f3ae8f3.jpg)

and after tap to show days:

![screenshot 2017-09-23 14-52-08](https://user-images.githubusercontent.com/22982594/30773355-0b5447e2-a06f-11e7-88a1-b5f058d8a528.jpg)

**Comment by AlanSP1** [comment]
This looks really great! 👍

**Comment by Frenzie** [comment]
This is closed by #3250?

**Comment by robert00s** [comment]
Not yet. I need to think about it:

> Also, when looking in days, we see info how many hours we read. It would be great if we could tap a day, it opens info on book(s) we read that day with info pertaining to that day, and if we tap on book, we receive book info for that book.
