### ISSUE TITLE
Backlight on PocketBock Inkpad 2

### ISSUE THREAD

**Issue by mk-f** [koreader/koreader#3240]
* KOReader version: v2015.11-1152
* Device: PocketBook Inkpad 2

Is this not implemented, or am i just unable to find the option?

**Comment by Frenzie** [comment]
If there isn't a "frontlight" option in the settings menu (gear), then it's probably not implemented on that device or platform.

![screenshot_2017-09-21_11-26-41](https://user-images.githubusercontent.com/202757/30688933-c1daac1a-9ebf-11e7-8445-19e9346f7c4b.png)

**Comment by mk-f** [comment]
See #3294

**Comment by Frenzie** [comment]
Implemented in #3294. Thanks!
