### ISSUE TITLE
 DSL dictionaries within KOReader? 

### ISSUE THREAD

**Issue by jcn363** [koreader/koreader#3242]
#### Issue
I'd wish to use my own DSL -ABBYY- (and/or GLS -babylon-) dictionaries within KOReader. Is there any way, chance, option, how-to, guide, advice, clue...?
Thanks in advance.

**Comment by Frenzie** [comment]
The wiki pretty much says it all. :-)

https://github.com/koreader/koreader/wiki/Dictionary-support

**Comment by jcn363** [comment]
Thanks, but I want to add this "hability". I'd wish any kind of info.

**Comment by Frenzie** [comment]
The dictionary-related code is mostly in https://github.com/koreader/koreader/blob/941d77f6bcc11b5d5899b11df258b0853c3f379d/frontend/apps/reader/modules/readerdictionary.lua (using sdcv on the backend) but what is it you want to do exactly?

**Comment by jcn363** [comment]
Thanks.
I'd wish to use my DSL's from my books. Therefor, I must implement a feature to do it.

**Comment by Frenzie** [comment]
Can they be converted to stardict format?

**Comment by jcn363** [comment]
Yes, of course. No problem. Is plain text.

**Comment by jcn363** [comment]
[https://letconex.blogspot.com.es/2017/04/babylon-gls-file-sample.html](url)
for reference.

**Comment by jcn363** [comment]
[https://github.com/goldendict/goldendict](url)
Goldendict can read the two formats (DSL and GLS)

**Comment by jcn363** [comment]
I think that'd will be a great idea to use Goldendict instead of only Stardict. A must study question... I think.
