### ISSUE TITLE
Feature Request - footnote display in the bottom of the current page

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#3246]
When I using small fonts, the footnote's link is very hard to click. 
I think the footnote display in the bottom of the current page will be very nice.
![image](https://user-images.githubusercontent.com/9783549/30727245-b77cccc6-9f82-11e7-80d8-63e51fccaab6.png)

**Comment by Frenzie** [comment]
Closing as a duplicate of #3054.
