### ISSUE TITLE
[UX] some small visual observations

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3265]
(KOReader version: 1251-ga2b0fb2 on Glo HD)

Following #3203, I may have been paying too much attention to smal visual details and alignments, and I noticed the following things. They are probably not a direct effect of these scaleBySize, most were probably there and I didn't noticed, or they are now more noticable because of the increased margins and paddings.

Posting these here as they are on my tofix list, but I'm quite busy these days, and I'd like to know if you feel the same about them or even notice them, or if I'm just too nitpicking:
- TOC, Bookmark, History (menu.lua): the close button (the `x`) at top right corner feels misaligned: it's not 45° diagonaly aligned with the top right screen corner (it's below this 45° line), and it is not horizontaly aligned with the title either
- TOC, Bookmark, History (menu.lua): horizontal alignements of items feels a bit uneven (the code abuses some horizontal spans default/small, where it should just use padding.fullscreen, and not add a space to mandatory for right margin- I had started working on this, but don't have yet time to finish it)
- Text in buttons looks not really verticaly centered and shifted towards up; I don't think it's some padding/margin, just that the rendering position of text in its box is a bit off (or may be it feels so because all our buttons have some uppercase letter that make it feels nearer the top border). It can be tweaked by changing the 0.7 (0.75 gives me a better feeling of centering) in:
https://github.com/koreader/koreader/blob/94c0e01b7f9916978962571c4f8dc359d9917048/frontend/ui/widget/textwidget.lua#L73
- Text in buttons, and height of buttons, seems different on the last row of a buttontable, and between widgets:
    - dictquicklookup/inputdialog: last row seems smaller (and the vertical separator touch the bottom border - it does not touch the other grey horizontal separator)
    - unlike confirmbox, where the buttons seem fine and large, (and the vertical separator does not touch the bottom border)
- Not enough room between input text and bottom buttons in InputDialog (look at any of the 2 Wikipedia settings): just adding some VerticalSpan before buttons seems to help: `VerticalSpan:new{ width = self.title_margin + self.title_padding },`. That may be needed in some other widgets.
- ButtonDialogTitle (and others) may need some vertical padding (or a verticalspan in their title, below the title) for the title to not look like a button.
- TouchMenu (top menu) has some borders on the left & right sides, unlike ConfigDialog (bottom menu) which does not have them
- TouchMenu (top menu): the horizontal lines (separator, but also the thicker line under menuicons) does not have the same margin on both sides (larger gap on the right)
- Finally, my last attempt at evoking this :) are we still letting the border.window being scaleBySize(2) (4px on GloHD) - where we feel 1.5 (3px on GloHD) have our preferences (it was 2px before) ? (I can still fix that in my personal mods - but I'm still bothered by the toyish look it gives to the whole thing).

**Comment by Frenzie** [comment]
> does they need fixing?

Yes. ;-)

> Finally, my last attempt at evoking this :) are we still letting the border.window being scaleBySize(2) 

Well, I don't understand your fixation on the window border specifically. It should be something like this.

```lua
    border = {
        default = Screen:scaleBySize(1.5), -- or maybe closer to 1
        thin = Screen:scaleBySize(1), -- should probably be 0.5 just like line.thin
        button = Screen:scaleBySize(1.5),
        window = Screen:scaleBySize(1.5),
    },
```

**Comment by poire-z** [comment]
> It should be something like this

So, why is it not yet? :)
(that's exactly my own mods - didn't feel like PR'ing this to force it on you, as the Size stuff was your domain)

**Comment by Frenzie** [comment]
Because that's my opinion and the other thing was a bug fix. :-p

**Comment by poire-z** [comment]
Isn't there a rule that states that a shared opinion, and no one posting here "I like the big borders" in the next 24 hours, make for a decision ? :)

**Comment by poire-z** [comment]
About this textwidget centering in its box, most noticable in buttontables:
Could you check if 0.75 looks fine for you with your various resolutions/dpi ? Or if there's another number that feels better? May be you'll find 0.7 is finally the best that fits all.
And it may even depend on the font family, so we should find one that work for our default font. I think it does matter only when text is in a bordered box, so it shouldn't hurt in unboxed text (menus, info text in widgets...)
I know nothing about fonts, typefaces & typography, but may be there are some rules about that? Couldn't find anything on the web.
The current textwidget/rendertext works like this:
if font size = X, make the text box 1.5*X. And draw the baseline of text at 0.7*1.5*X from top of text box.

(0.75 moves the text in footer 1 or 2 pixel down, so bottom feels a bit congested - I'm not so sure then).

**Comment by Frenzie** [comment]
One good free resource is https://practicaltypography.com/

**Comment by Kwuik** [comment]
I don't know if its related, but on my KA1 I got the 'problem' that the edge if I make a bookmark on the top right is ridiculously small. Is there a way to make it bigger?

**Comment by Frenzie** [comment]
That is indeed the same issue. In pixels these are the same (unscaled) size. However, I'm inclined to think that the intended size is a touch large. I think it's just about right on my H2O, where it's small and unobtrusive but not too small. On a KA1 it'd be a smidge smaller still. Basically this will apply to any as of yet unscaled image.

<img src=https://user-images.githubusercontent.com/202757/31317234-8c7a3f6e-ac3d-11e7-83b1-6eea5cc253a8.png width=30%>
<img src=https://user-images.githubusercontent.com/202757/31317235-8c7a5e18-ac3d-11e7-86ed-c9dcfbe7a3f0.png width=30%>

Perhaps `Size` will need some kind of standard icon sizes after all, because the proper way to do DPI scaling of images is to have a few different sizes and to scale down from the nearest larger one. Or to use a dynamic SVG as the source image.

So:

1. We want size X (`scaleBySize(X)`)
2. Image requested at size X, find nearest image size (above if possible)
3. Scale (and cache, but that should be taken care of already).

But anyway, we can leave step 2 to sometime in the future. It's the lack of scaling that should be tackled in the shorter term.
