### ISSUE TITLE
Home button issues

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3270]
* KOReader version: latest

#### Issue
New home button in filemanager has 2 problems:

+ hold home button doesn't work
https://github.com/koreader/koreader/blob/ac02d1551b6cb62427f9f975c47ccd8220685da4/frontend/apps/filemanager/filemanager.lua#L65
IconButton widget hasn't got hold_callback method

+ tap on home button creates new instances of filemanger. 
https://github.com/koreader/koreader/blob/ac02d1551b6cb62427f9f975c47ccd8220685da4/frontend/apps/filemanager/filemanager.lua#L366
showFiles() make new instance of filemanger.

**Comment by Frenzie** [comment]
Oh, I overlooked that when switching from Button to IconButton. Probably best to add hold_callback to IconButton?
