### ISSUE TITLE
Wrong colors when using the built-in koreader emulator

### ISSUE THREAD

**Issue by djalma2k** [koreader/koreader#3274]
* KOReader version: 7da2998322e2d515698bb1f252c2c21e7d80fb49
* Device: Emulator @ generic linux system

#### Issue
Images are in RGB mode with wrong converted colors when using the image viewer.
Example:
<a href="http://postimg.org/image/6x3x5dbit/" target="_blank"><img src="https://s26.postimg.org/6x3x5dbit/koreader_a.jpg" alt="koreader_a"/></a> <a href="http://postimg.org/image/v24mn2vth/" target="_blank"><img src="https://s26.postimg.org/v24mn2vth/koreader_b.jpg" alt="koreader_b"/></a> <a href="http://postimg.org/image/fuon2q3yt/" target="_blank"><img src="https://s26.postimg.org/fuon2q3yt/koreader_c.jpg" alt="koreader_c"/></a><br/><br/>

#### Steps to reproduce
Zoom an image when you are using the image viewer or follow the previous example.
Regards

O/T: Maybe related with this in somehow, when you are using a kobo glo hd device with the lastest nightly installed, the cover images ( and I guess that it probably happens with all the images in an epub ), are never "refreshed". They looks dirty with text of the contiguous pages...

**Comment by Frenzie** [comment]
Cover images are unrelated to inside an EPUB. They're not reloaded every time.

Btw, https://github.com/koreader/koreader/pull/3264#issuecomment-333097305

**Comment by Frenzie** [comment]
> O/T: Maybe related with this in somehow, when you are using a kobo glo hd device with the lastest nightly installed, the cover images ( and I guess that it probably happens with all the images in an epub ), are never "refreshed". They looks dirty with text of the contiguous pages...

Could you clarify this, e.g. by posting a screenshot?

Btw, could you try to be as specific as possible about the version? By "latest nightly" do you mean v2015.11-1265-g994606e?

**Comment by djalma2k** [comment]
> Btw, #3264 (comment)

Opps, I didn't see it, sorry... :/ Ok I'm gonna close this rightnow.

> Cover images are unrelated to inside an EPUB. They're not reloaded every time.

Yeah, I know what you mean and I aware of this but I also got an experience using koreader previously and I don't get the same feeling with previous releases: I perceive something weird related to this when I view the cover of an epub file and when I play with it: zoom it... anyway I wrote the O/T because I need a time to check it with and epub file with images.... it was just a comment for your info xD

**Comment by djalma2k** [comment]
Lastest rightnow is 994606e70ef8a529276a2af71d776c2a1959e1b3 .
Anyway dont loose time with this, I'm gonna check it well when I'll have a little more time and I'll write an "issue" if I can confirm it..

**Comment by poire-z** [comment]
> Images are in RGB mode with wrong converted colors when using the image viewer

I notice that too on android today: the tone of greys on the crengine small image rendering is sometime different from the ones we get in imageviewer :| Any hint of the type or name of the wrong conversion (or the action you need to apply to the image to get it displayed with correct colors) ?

> the cover images ( and I guess that it probably happens with all the images in an epub ), are never "refreshed". They looks dirty with text of the contiguous pages

Yes, we could probably do a full refresh onShow and onClose (I'd say I didn't so that display is faster: no full refresh by default, do it manually if you need it :)
Anyway, for now, you can refresh with:
- in ImageViewer: just hold ur finger on screen
- in Reader: small diagonal swipe

**Comment by poire-z** [comment]
Well, checked with some images, it appears that at some point, in our final RGB blitbuffers, red and blue are swapped, while green is displayed correctly...

**Comment by Frenzie** [comment]
Probably as simple as an accidentally switched reference somewhere in Blitbuffer then?

**Comment by poire-z** [comment]
Could be, but the blitbuffer code is full of shifts and other binary operations that I don't want to start digging into that. After all, there's no problem being color blind in our greyscale world :)
I'd like to make sure first it's not just Mupdf with our image > pixmap > blitbuffer conversion that is missing something, but I don't know from where else to get a colored blitbuffer :| May be from picdocument and ffi/pic.lua

**Comment by poire-z** [comment]
Ok, seems to be inverted even when mupdf not involved (GifDocument > BlitBuffer RGB24 > ImageViewer with no scaling), so it may be a blitbuffer.lua thing - or that SDL expect BGR and not RGB...

**Comment by poire-z** [comment]
Turns out it was on the SDL interfacing side, and that out blitbuffer stuff should be fine.
Now, there's still this tones of grey differences on android, that I don't see on my Kobo.
So, there may be something similar to this on the android side.
