### ISSUE TITLE
EPUB: Scroll mode page numbers broken

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3282]
* KOReader version: 180f575 but likely going back much further
* Device: all

#### Issue
Enabling scroll mode in EPUB causes crashes related to page numbers and TOC markers.

#### Steps to reproduce
Almost any random EPUB with more than one page should do. For example, notice how 10_2-BF-01.epub from `Html401/` in the EPUB test suite, a 3 page document, claims to have a thousand.

![screenshot_2017-10-01_09-28-18](https://user-images.githubusercontent.com/202757/31052650-19ce4ed6-a68b-11e7-93eb-86d27b739df0.png)
![screenshot_2017-10-01_09-28-23](https://user-images.githubusercontent.com/202757/31052651-19d0d8f4-a68b-11e7-9ee4-8e221ef5749a.png)
![screenshot_2017-10-01_09-28-27](https://user-images.githubusercontent.com/202757/31052652-19d6ff9a-a68b-11e7-8ece-49b6057526bf.png)

Doing something that requires interaction with page numbers will trigger an error like this:

```
./luajit: frontend/ui/widget/bookstatuswidget.lua:259: attempt to perform arithmetic on field 'page' (a nil value)
stack traceback:
	frontend/ui/widget/bookstatuswidget.lua:259: in function 'genBookInfoGroup'
	frontend/ui/widget/bookstatuswidget.lua:125: in function 'getStatusContent'
	frontend/ui/widget/bookstatuswidget.lua:86: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/modules/readerstatus.lua:45: in function 'showStatus'
	frontend/apps/reader/modules/readerstatus.lua:29: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/apps/reader/modules/readerrolling.lua:440: in function 'onGotoViewRel'
	frontend/apps/reader/modules/readerrolling.lua:296: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:197: in function 'handleEvent'
	frontend/ui/uimanager.lua:442: in function 'sendEvent'
	frontend/ui/uimanager.lua:43: in function '__default__'
	frontend/ui/uimanager.lua:720: in function 'handleInput'
	frontend/ui/uimanager.lua:765: in function 'run'
	./reader.lua:178: in main chunk
	[C]: at 0x55cc9d7590b0
~/src/kobo/koreader
```

**Comment by Frenzie** [comment]
This problem seems to be relatively new. It does not yet exist in abaa699.

**Comment by Frenzie** [comment]
@robert00s What is the use case for this exactly? I'm pondering how useful this mode is and whether the best "fix" would be to simply remove it. It doesn't seem very useful to me.

**Comment by robert00s** [comment]
@Frenzie I don't use scroll mode in EPUBs at all.
I also notice some time ago that's problem with page number in scroll mode.
I try to look at it soon.

**Comment by KenMaltby** [comment]
I would think that English language based EPUBs appear to show some commitment to a paged formatting.  The same might not be the case for some other languages.

**Comment by Frenzie** [comment]
I'm not sure I understand what you're getting at. I'd say it's just a continuous flow of text with automatically inserted page breaks where appropriate. That's different from PDF and DjVu which are page-based.

**Comment by KenMaltby** [comment]
Wasn't there a recent issue that concerned Japanese vertical formatting, perhaps others?  I never use the scrolling mode, with EPUBs, but I would be reluctant to advise the removal of an existing feature without raising a potential issue.

**Comment by Frenzie** [comment]
If you mean #1736 then in principle that isn't really any different, but I suppose you mean there's more of a use case for dragging EPUBs up and down if that were to work.

I wanted to check whether `v2015.11-stable` suffered from the same problem, but unfortunately due to changed URLs and such quick tests are pretty much impossible for older versions. I forget how to run multiple versions of KOReader from KSM but that would be required for some quick basic tests.

I'm pretty sure scroll mode in EPUB has been broken for quite a while. It may not have crashed, but you'd get stuck on page 1 after reopening.

**Comment by KenMaltby** [comment]
This may be an issue that we won't know until it is tried and if there is any who are affected, I am sure we would hear about it either here or at MR.  I think losing EPUB scrolling may not affect anyone, enough to cause complaint.

**Comment by poire-z** [comment]
Well, I don't use it either, but I see people used to scrolling web page using it.
And readerrolling.lua is built with as much code for both modes (notion of page in page mode, notion of percent in scroll mode), so if removed, there would be a lot to clean.
There may be just a few things (footer, bookstatus) to adapt so they work when document does not have a page, and do some alternate display (like footer, if document does not have pages, don't display pages, or use 'n/a' as an alternate, or use the % instead).

**Comment by Frenzie** [comment]
Of course it has and needs pages or you wouldn't be able to get anywhere. Scroll mode in EPUB functions very similarly to how it does in PDF when it's working. It's unclear to me why in some documents it's completely broken, but it's hopeful that in some documents it might not be (completely) broken until you exit and reopen.

(Incidentally, one of the more interesting recent Opera experiments is http://www.wiumlie.no/2011/reader/)

**Comment by frankyifei** [comment]
test 10_2-BF-01.epub on emulator, no problem with page number, can not reproduce

**Comment by Frenzie** [comment]
@frankyifei In scroll mode?

Anyway, it's something we can or maybe even should fix on the frontend. I haven't looked into it really.

**Comment by frankyifei** [comment]
in my test, scroll mode is working and page number is correct. I had this problem before. I remember it was related to residual files in .sdr folder in my case, showing thousands of pages but did not crash.

**Comment by Frenzie** [comment]
Ah! There's an element I might've missed. Because I would've noticed if I'd been getting documents claiming to have 100000 pages. No, the EPUB I was reading was perfectly normal and perhaps I've even read another EPUB or two without ever noticing anything because I simply never closed and reopened the document.

Okay, so the step I neglected to explicitly identify for what I didn't realize may be a separate problem:

1. Open the file in paged mode.
2. Switch to scroll mode.

**Comment by Frenzie** [comment]
@frankyifei Okay, updated way to reproduce:

1. Open document. Scroll mode, page mode, doesn't matter.
2. Switch to scroll mode if in page mode.
3. Exit to file browser.
4. Reopen document.

With #3183 that causes the ludicrous page numbers. I think this is what causes crashes.

Without #3183 the page indicator gets stuck on the same page but otherwise things seem to be fine.

So the key is that we simply need a slightly better version of #3183. @robert00s since you wrote it do you have any pointers?

**Comment by poire-z** [comment]
Had a quick look at readerrolling history, and I noticed that I reintroduced in #3292 a line that was removed by @robert00s in #2855.
I tried reverting #2855 and #3183 , and scroll mode does not crash anymore (and start position seems ~accurate (+/-1 page, but that may be the xpointer/percent rounded/misaligned) - and of course, the page indicator in readerfooter is not udpated (but was updated to start page, and so stays on it).
@robert00s : what was the original problem with onPageUpdate being called twice in #2855 ? StatisticsPlugin getting that info twice?
Looks like #2855 had quite a few side effects (TOC reset and rebuild, this crash), and there may be another solution to find to the 2 onPageUpdate (if that's still needed avec statPluginV2?)

**Comment by robert00s** [comment]
If I remember correctly it was a problem with onPageUpdate being called twice.
Of course we can revert this changes. I may prepare patch to prevent run `ReaderStatistics:onPageUpdate(pageno)` twice on the same page

**Comment by poire-z** [comment]
Ok, but was it just for your ReaderStatistics that you felt the need to fix this ? or was there other modules sensitive to two onPageUpdate that needed the fix?

readerrolling emit/call onPageUpdate when in page mode, and onPosUpdate when in scroll mode (and even in scroll mode, it is in "page" mode for a short time while opening).

Receivers of onPageUpdate:

```
frontend/apps/reader/modules/readertoc.lua:function ReaderToc:onPageUpdate(pageno)
frontend/apps/reader/modules/readerfooter.lua:function ReaderFooter:onPageUpdate(pageno)
frontend/apps/reader/modules/readerzooming.lua:function ReaderZooming:onPageUpdate(new_page_no)
frontend/apps/reader/modules/readerbookmark.lua:function ReaderBookmark:onPageUpdate(pageno)
frontend/apps/reader/modules/readerpaging.lua:function ReaderPaging:onPageUpdate(new_page_no, orig_mode)
frontend/apps/reader/modules/readerview.lua:function ReaderView:onPageUpdate(new_page_no)
plugins/statistics.koplugin/main.lua:function ReaderStatistics:onPageUpdate(pageno)
plugins/kosync.koplugin/main.lua:function KOSync:_onPageUpdate(page)
plugins/kosync.koplugin/main.lua:        self.onPageUpdate = self._onPageUpdate
plugins/perceptionexpander.koplugin/main.lua:function PerceptionExpander:onPageUpdate(pageno)
```
Receivers of onPosUpdate:
```
frontend/apps/reader/modules/readerfooter.lua:function ReaderFooter:onPosUpdate(pos)
frontend/apps/reader/modules/readerbookmark.lua:function ReaderBookmark:onPosUpdate(pos)
frontend/apps/reader/modules/readerview.lua:function ReaderView:onPosUpdate(new_pos)
```

I wonder if it could not calculate page / nb page even in scroll mode, and either call only onPageUpdate, or give it/them as additional parameters to onPosUpdate, so we could upgrade these onPosUpdate (and you could add one to ReaderStatistics), so we would get page info in footer, and statistics even in scroll mode.

So, if I should look at that (and the 2 onPageUpdate problem), should I start from the current readerrolling with your #2855 (+ the 2 following commits fixing side effects of it) ? Or from the readerrollin with your 3 commits reverted? (I would go with 2nd option, but I want to be sure I don't miss other things you had a go at fixing).

**Comment by robert00s** [comment]
> Ok, but was it just for your ReaderStatistics that you felt the need to fix this ? or was there other modules sensitive to two onPageUpdate that needed the fix?

On May I worked on statistics v2 so this "fix" was only to prevent run `ReaderStatistics:onPageUpdate(pageno)` twice.

> I wonder if it could not calculate page / nb page even in scroll mode, and either call only onPageUpdate, or give it/them as additional parameters to onPosUpdate, so we could upgrade these onPosUpdate (and you could add one to ReaderStatistics), so we would get page info in footer, and statistics even in scroll mode.

Good idea.

> So, if I should look at that (and the 2 onPageUpdate problem), should I start from the current readerrolling with your #2855 (+ the 2 following commits fixing side effects of it) ?

I think that #2855 and #3183 may be remove safety but it's only my opinion :)

**Comment by Frenzie** [comment]
Btw, that'll be:
```
git revert --strategy resolve 2b3b310
git revert --strategy resolve 394be8a
```

**Comment by poire-z** [comment]
Well, I just reverted them, and putting some print here and there, I see only one onPageUpdate on startup.

And... it turns out that the line I added (before the line reverted) yesterday in https://github.com/koreader/koreader/commit/26def92983afae54fb6a8cc064706825d5e71c62 is the reason onPageUpdate gets called only once... :)

https://github.com/koreader/koreader/blob/bf61e6f0932761b413c7451932e2e9af7441481b/frontend/apps/reader/modules/readerrolling.lua#L97-L98
Comment line 97, and it gets called twice :|
(Calling `_readMetadata()` was to get an accurate `self.ui.document.info.number_of_pages` , without it, `self.old_page` stayed 0 or nil)

Thought I would have to do much more, so... 2 problems solved may be :)
If you can check your other scenarii above no more crash (and may be the page number is no more excessive ?)

**Comment by Frenzie** [comment]
Seems fine to me. The page number isn't updated without closing and reopening (so that shouldn't be too hard to fix?) but as far as I can tell this solves all regressions.

**Comment by poire-z** [comment]
> so that shouldn't be too hard to fix?

Dunno yet, it's all the business about onUpdatePos vs onUpdatePage described above. I may look at it in the coming days, but don't make that a stopper if you want to do a release.

**Comment by Frenzie** [comment]
I'll wait for the build server to generate the nightlies and then I'll upload those on GH tomorrow. It's time. :-) 

Plus you may have noticed I just committed bf61e6f0932761b413c7451932e2e9af7441481b which fixed that thing that's been bugging me. It was messing things up by duplicating https://github.com/koreader/koreader/blob/5a2c8e4b5e4f964eebde66004af9522c13659b80/frontend/device/generic/powerd.lua#L128)

I tried that days ago, but I finally realized that Android kept parts of the app in memory when I added in debug statements. Even though I quit from KOReader and force closed from the Android task manager. 😠 

Besides trying some Android 8 things on the side I hope to be able to avoid it completely for the foreseeable future. :-P
