### ISSUE TITLE
Crashed when highlight 2 words using dictionary 

### ISSUE THREAD

**Issue by holyblade** [koreader/koreader#3305]
* KOReader version: Newest
* Device:Kobo Glo

#### Issue
Crashed when highlight 2 words using dictionary 
#### Steps to reproduce
1. Select 2 words and press dictionary.
2.Press highlight.
3.Crashed.
##### `crash.log` (if applicable)
stack traceback:
	frontend/apps/reader/modules/readerhighlight.lua:505: in function 'saveHighlight'
	frontend/apps/reader/modules/readerhighlight.lua:452: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
	frontend/ui/widget/dictquicklookup.lua:340: in function 'callback'
	frontend/ui/widget/button.lua:198: in function 'action'
	frontend/ui/uimanager.lua:518: in function '_checkTasks'
	frontend/ui/uimanager.lua:669: in function 'handleInput'
	frontend/ui/uimanager.lua:765: in function 'run'
	./reader.lua:190: in main chunk
	[C]: at 0x00013fc5

**Comment by Frenzie** [comment]
@poire-z Haven't had a chance to test if it is indeed at fault, but #3241 immediately came to mind.

**Comment by poire-z** [comment]
Reproducible. It's not exactly the situation of #3241, but it's always the same crash related to hold_pos being nil after the highlight has been cleared (here, by closing the highlight menu, where `ReaderHighlight:onClose()` does a `self:clear()`), and later trying to use `self.hold_pos.page` when `self.hold_pos` is now nil).

1) Simplest fix would just be to remove the 2 `self:onClose()` in:
https://github.com/koreader/koreader/blob/b483c54be8c727160d829c8a385f60b5b2a9097c/frontend/apps/reader/modules/readerhighlight.lua#L401-L414
so the highlight menu is not closed (and the hightlight not cleared), with the side effect than when closing the quickdictlookup windows, you get back to the highlight menu, with the selected text still highlighted (which, depending on how you look at that, could be a feature/fix: you can just dismiss that highlight menu, or do Search, Highlight, Wikipedia from there without having to re-select the text).

2) Or just add a no_clear param to `onClose(noclear)` and pass `no_clear=true` in these 2 onClose(), and further down, pass `self` (the highlight itself) in:
https://github.com/koreader/koreader/blob/b483c54be8c727160d829c8a385f60b5b2a9097c/frontend/apps/reader/modules/readerhighlight.lua#L583-L589
ie: `self.ui:handleEvent(Event:new("LookupWord", self.selected_text.text, false, self))`
which would make it similar (without word_box) to:
https://github.com/koreader/koreader/blob/b483c54be8c727160d829c8a385f60b5b2a9097c/frontend/apps/reader/modules/readerhighlight.lua#L324-L328

Well, 2) is easy for Dictionary, less easy for direct Wikipedia which does not yet support being given a highlight and clearing it.

So, solution 2) for Dictionary, and 1) for Wikipedia?
Or just 1) for both (probably the most secure one with less side effects to expect).

**Comment by Frenzie** [comment]
1 is fine by me.
