### ISSUE TITLE
[footer] TB and TC have 'na' after open book

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3309]
* KOReader version: latest
* Device: all

#### Issue
After open book TB and TC statistics show na

![screenshot 2017-10-06 20-41-57](https://user-images.githubusercontent.com/22982594/31293338-252a0c7a-aad7-11e7-8cd4-612014bbfd39.jpg)
After change or refresh page statistics in footer are shown property.

#### Steps to reproduce
Open book that you read already.

Pinging @poire-z for help :)
I can add refresh footer after statistics init but maybe is better solution.

**Comment by poire-z** [comment]
Not sure it's a problem needed a fix.
https://github.com/koreader/koreader/blob/b7785753c6b55f7337934f08e6b764df287709b5/frontend/apps/reader/modules/readerfooter.lua#L506-L512
When you're showing first page, you have no past info to compute any of them (how would you compute time to next chapter if you don't have yet a time to next page ?) :)
Or you could just have it display something else than `na` which would look like it's not broken :)
`na` (or `'n/a'`) means `not available` in english (in case you didn't know) - may be it needs some translation?

(Or did I misunderstand your worry ?)

**Comment by robert00s** [comment]
yes :) I thinking about reopen book :)

**Comment by poire-z** [comment]
In your ReaderStatistics:init() , you override the empty one in readerfooter and plug this one intead:
```lua
    ReaderFooter.getAvgTimePerPage = function()
        if self.is_enabled then
            print("zzz", self.avg_time) -- my way of debuging
            return self.avg_time
        end
    end
```
First times it is called, `ReaderStatistics.avg_time` is `nil`, so the na.
You would need to compute some value to start with if you can around there in `ReaderStatistics:init()`.
(and for that, I wouldn't be of much help, I hate statistics maths :)

**Comment by Frenzie** [comment]
Or this depending on what you're looking for :-P
```lua
require "logger".dbg("we can print whole tables, w00t", self)
```

**Comment by poire-z** [comment]
Yup, but print sticks out of timestamped lines when you don't need the detail :)

**Comment by robert00s** [comment]
I cannot calculate `ReaderStatistics.avg_time` in ReaderStatistics.init() because book isn't fully opened yet :( 
I can only calculate in `ReaderStatistics:onReaderReady()` but than it's too late. ReaderFooter is faster :(

**Comment by poire-z** [comment]
You could try, in ur `ReaderStatistics:onReaderReady()`, to force an update of the footer, by calling:
`ReaderFoot:updateFooter()`
If it doesnt work straight, you can try delaying it a bit: `UIManager:scheduleIn(0.1, function() ReaderFoot:updateFooter() end)`

**Comment by Frenzie** [comment]
Yeah, I see nothing wrong with updating the footer once the document's loaded.

**Comment by robert00s** [comment]
Thanks.
`self.view.footer:updateFooter()` works :)
