### ISSUE TITLE
FR: fulltext search history

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3317]
* KOReader version: d23d01643edec990e2494ff0c029bd6d3d9e55c7
* Device: all

#### Issue
Quoting @Eduardomb22 in https://github.com/koreader/koreader/pull/3161#issuecomment-329481037
> Is it possible to add a history for "full text search"too?

Easy to add based on the same principle. But design-wise, also global or per-document?

**Comment by Eduardomb22** [comment]
I prefer global. Because you may be looking for the same word at other books.

**Comment by Frenzie** [comment]
Although this is implemented then it really should be more generalized. Dictionary lookup, Wikipedia lookup, fulltext search… there's nothing fundamentally different about any of them.

Then there's the follow-up question: should it be generalized only in the code and presented it as separate lookup histories or should it all just be one and the same "lookup history"?

**Comment by Eduardomb22** [comment]
Maybe it is better to make a unique "lookup history" so the menu doesn´t be pollute with lots of search history.

**Comment by KenMaltby** [comment]
I probably am guessing wrong, but you are talking about just a list of the search terms used, - not - the results or the books searched, right?  No date/time of search?  What would any of this be used for?

**Comment by Frenzie** [comment]
I've used my lookup history in Kiwix, though not much. Anyway, it currently looks like this:

![screenshot_2017-10-09_23-33-29](https://user-images.githubusercontent.com/202757/31359449-57b2c716-ad4a-11e7-9457-8727e8c750c3.png)

**Comment by KenMaltby** [comment]
I guess I must be lacking in imagination but I can't see what value there would be in knowing that I had looked up the definition of "choice" (or any word) in a paper at 23:33:00 on 2017-10-09.  The only thing that I can think of is while learning a language, it could be a list of words I night need to check that I had retained the definition correctly.

**Comment by Frenzie** [comment]
I don't know if that's the only thing, but yes, I primarily use the dictionary while reading in French. I only write down that which somehow seems important or grabs my attention and sometimes a few days later I might be like "gosh, what was that word?" Kiwix has my back, and now I suppose so does KOReader. :-P

But there's a setting to disable it if you don't like it.

**Comment by Frenzie** [comment]
I'm not interested in pursuing this (but that's not a statement against contributions).
