### ISSUE TITLE
After Koreader startup screen is blank - missing screen refresh/repaint.

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3325]
KOReader version: nightly 1287
Device: Inkbook Prime (Android)

#### Issue
After Koreader startup screen is blank - missing screen refresh/repaint.

I have Koreader startup with history and so tap on top of this blank screen starts usually first (or second or third, depending how height I tappped;) history item. So it seems we just need to repaint screen

#### Steps to reproduce
Turn on koreader. See blank screen.

**Comment by Frenzie** [comment]
I didn't quite register this in your earlier issue but v2015.11-1287-g5a2c8e4 is from four days ago. I fixed what you describe here by getting rid of some stuff in https://github.com/koreader/android-luajit-launcher/pull/64

That should be available in v2015.11-1296-gb483c54 and up.

**Comment by mwoz123** [comment]
Great. Thanks:)

**Comment by Frenzie** [comment]
Alright, closing this then. :-)
