### ISSUE TITLE
The screen is black when KOReader starts on my android device

### ISSUE THREAD

**Issue by Leoongithub** [koreader/koreader#3328]
My device is Meizu M2 Note and it occurs on every build of koreader(at least the latest 5 builds).
This only happens when I install the new version of koreader. The screen is black and nothing happens even if you press anywhere. Usually after I tried reinstall the app, clear data or remove the directory /sdcard/koreader, koreader works properly. Once I solved the problem, it will not happen until I update koreader.
There is a little difference in the build 1152. I need to press something to refresh screen otherwise the screen is still black(this problem only occurs in this version).
I read the discussion under #3118 and I'm not sure if it is the same problem.

update:
One thing I forgot to mention is that I can't solve this problem on build 1287. I tried everything but the screen is still black. Then I unistalled it and installed the older version. This time every build appears same. Now I can't use any version of koreader.

Please excuse my poor English.

**Comment by gerroon** [comment]
I still get the black screen (I just press the screen to force a refresh) with 1254 I am waiting for a new build, supposedly it will fix that along with light issues.

**Comment by gerroon** [comment]
Did you try 1303 build? Also remove or rename patch.lua in settings folder if you have it

**Comment by Leoongithub** [comment]
@gerroon I can't find 1303 build. Can I download it from somewhere? Or I need to build it by myself?

**Comment by Frenzie** [comment]
@Leoongithub You can always get the latest builds from http://build.koreader.rocks/download/nightly/

I've also attached the latest nightly for convenience. You'd have to remove the .zip from the name; that's just to upload it on GitHub here.

[koreader-android-arm-linux-androideabi-v2015.11-1312-ga710d2c.apk.zip](https://github.com/koreader/koreader/files/1367691/koreader-android-arm-linux-androideabi-v2015.11-1312-ga710d2c.apk.zip)

**Comment by Leoongithub** [comment]
@Frenzie This build didn't help. The same problem exists on my device.

**Comment by Frenzie** [comment]
While testing Android builds I've noticed some caching behavior that unfortunately I couldn't seem to get around without uninstalling and reinstalling.

What version of Android is this Flyme 6? Android 6?

**Comment by Leoongithub** [comment]
@Frenzie It differs form different device. For me (Meizu M2 Note) it is Android 5.1.

**Comment by Leoongithub** [comment]
@Frenzie To my surprise, the 1312 build unexpectedly can work properly now. I'm not sure which behavior solved the problem. Maybe the reason is that I reboot my device. But this usually didn't help in the older versions.

**Comment by Frenzie** [comment]
In this case that would be quite expected. Usually nothing changes. Good to know that restarting also works, but for me uninstall/reinstall is a lot faster (and now fully automated through adb) than minutes rebooting. :-)

Anyway, I can now close all these issues then

**Comment by Frenzie** [comment]
Fixed by #3319.
