### ISSUE TITLE
Maximum sdk 9?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3346]
Hi

Suddenly I cant install the latest builds on my Android 7.1 device. They can be installed on Lollipop ad below. I am not sure but my installer shows that the maximum sdk is 9, maybe that is the issue? 

Basically when I open the apk, the "install" button is grayed out, it is not like apk signature issue. I get the same with a fresh install.

**Comment by Frenzie** [comment]
What do you mean by your installer? The minimum is 9, not the maximum.

**Comment by Frenzie** [comment]
See https://github.com/koreader/android-luajit-launcher/blob/a25e156f2d203e4d138347ecd3a2f901970c6f7b/AndroidManifest.xml#L6

**Comment by gerroon** [comment]
I have no idea. Like I said , "suddenly" I cant install koreader on my LineageOS device, the "install" button on the initial install window (of koreader) is grayed out.

**Comment by KenMaltby** [comment]
For what it's worth 1326 is installed and working on my Galaxy S7 Active on 7.0.

**Comment by gerroon** [comment]
It was my frigging OS update broke the installer. I did the  the Os update and Koreader update the same day and I assumed the latter was broken ;( Reverting back to early OS fixed the issue.

I am sorry that I wasted your time guyz.

**Comment by Frenzie** [comment]
The earlier version is also 7.1?

**Comment by gerroon** [comment]
Yeah but this is Lineage OS nightly builds

**Comment by Frenzie** [comment]
Alright. :-)
