### ISSUE TITLE
Series metadata: '&' and decimal aren't displayed correctly

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3347]
* KOReader version: v2015.11-1287-g5a2c8e4
* Device: Kobo Aura One

#### Issue

&:
For example series name 'Zigic & Ferreira' becomes 'Zigic `&amp;` Ferreira'

decimal: 
For example series number 2.5 becomes 2

#### Steps to reproduce

1. Transfer a book to your e-reader with series name 'X & Y' and series number '1.5'

2. Choose "List with image and metadata" and "Append Series metadata to Title"

3. Look at the result in file manager

**Comment by Frenzie** [comment]
@poire-z Didn't you do something with HTML entities?

**Comment by poire-z** [comment]
We indeed have `util.htmlToPlainTextIfHtml(text)` and `util.htmlEntitiesToUtf8(text)`, but they are used for now only for `description` (which is usually bigger text, with html, paragraphs...)
Should be easy to add them wherever we need to display title, authors, series, keywords (in filemanagerbookinfo.lua and in the various coverbrowser modules).
But currently, `util.htmlToPlainTextIfHtml()` does not detect `this &amp; that` as being HTML (it only looks for < html tags >.
Simple would be to add in detection `if util.htmlEntitiesToUtf8(text) ~= text then is_html = true end` too.

About the series number, it is crengine that does the conversion to integer (if tag contains "2.5", if gives 2, if tag contains "aaa", it gives 0). Thought I could say epub specs enforce it to be an integer, but it's a calibre tag :) so no spec. We could just deal with it as just a string, like the series name... For epub:
https://github.com/koreader/crengine/blob/8eefe54e40e4c3f56392e7d8ee2fe43848d53256/crengine/src/epubfmt.cpp#L816-L819 , but there are the other formats too.

**Comment by poire-z** [comment]
Pffff; with just getting series number as string, we now get displayed `Serie #3.0` , `Serie #4.0` ...
I have this in the few epub with series metadata i have: `<meta name="calibre:series_index" content="4.0"/>`

**Comment by Frenzie** [comment]
Sorry, what's the problem? :-)

**Comment by poire-z** [comment]
A bit uglier than before when we had `The serie #3`, `The serie #4`.
Should we just let them be displayed `The serie #3.0` , `The serie #4.0` as calibre decided these numbers should be decimal or whatever it decides them tomorrow to be?
Or just store them as is in doc_props and bookinfo.db, and do some simple `string.gsub(series, "(#%d)%.0", "%1")` at display time?

**Comment by Frenzie** [comment]
That would explain the needless int conversion. Imo the calibre numbering is wrong in any case. It should be something like `3.1` or `3.a` (although not unless there actually is a `3.2` or `3.b`). `3.0` would be a prequel. Prequel to the prequel? `-1`?

Anyway, it does seem better to abstract such nonsense away somewhere, although not necessarily in crengine. Unless calibre metadata is the only place we can conceivably get this info from in the nearby future? Then just add it with a comment I'd say.
