### ISSUE TITLE
device passcode doesnt work

### ISSUE THREAD

**Issue by tarungupta2001** [koreader/koreader#3359]
* KOReader version:
* Device: kindle voyage

#### Issue 
Device passcode doesnt work

#### Steps to reproduce
After setting device passcode in kindle in voyage when i open ko reader to read epub books and press the power the button without exit from ko reader ,device locks,but when i again press power button to open it again,it doesnt ask for a passcode.However,after exit from the ko reader and pressing the power button , it asks for a passcode on  unlocking  the device again.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by tarungupta2001** [comment]
Ko reader doesnt crash.I try to explain my problem in simple steps:
1.Set the device passcode in native kindle operating system.
2. Open  a epub file,
3.Without exit from the ko reder just lock the device simply by pressing the power button on kindle voyage.
4.Unlock the device by pressing power button again.Now it should prompt to enter the device passcode/password.But it doesnt prompt for a passcode/password.
However,locking the device after exit from ko reader,device prompts to enter a passcode to unlock the device.

**Comment by chrox** [comment]
It's a known issue on Kindle. Koreader does not provide a screen lock mechanism yet. And it cannot simply reuse the native system's lock.

**Comment by NiLuJe** [comment]
#2865
