### ISSUE TITLE
How to disable refreshing after wake up

### ISSUE THREAD

**Issue by zhliu0124** [koreader/koreader#3363]
* KOReader version: koreader-nightly-20171004
* Device: kpw3

#### Issue
1. The screen flashes once after wake up, either from opening the magnetic cover or from pressing the power button.
2. The flash happens in about 6s after wake up.
3. In most of the cases, the screen turned to blank (white screen) after flashing.
4. The blank screen was still responsible, so it seems the problem is that KOreader cannot render the text properly after flashing.
5. The screen doesn't flash after wake up if I exit KOreader and put the device to sleep.

Is there a way to disable the auto-flashing function after wake up?

**Comment by robert00s** [comment]
Try upgrade to newest version and check again.

**Comment by zhliu0124** [comment]
Still happens after upgrading to the latest nightly version.
v2015.11-1343-g7424202

**Comment by Frenzie** [comment]
@Goligoski Thanks for the report. I'll close this then. There seems to be something about some missing files in https://github.com/koreader/kpvbooklet/issues/29#issuecomment-336954704 which might also be related.

**Comment by zhliu0124** [comment]
@Goligoski Thank you very much! Problem solved!
