### ISSUE TITLE
Reading external stored files will still crash

### ISSUE THREAD

**Issue by toiiggww** [koreader/koreader#3365]
* KOReader version:koreader-nightly-20171004 koreader-android-arm-linux-androideabi-v2015.11-1287-g5a2c8e4.apk
* Device: Sony z5p android 7.1.1

#### Issue
一。显示时获取的显示区域没排除软键区域，导致底部菜单显示不全
二。软件启动时会自动黑屏
三。读取外部存储的文件仍会崩溃
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
>Feedback on start and display incomplete
>
>one. The display area obtained when the display is displayed does not exclude the softkey area, resulting in the bottom menu display incomplete
two. The software will automatically black screen
three. Reading external stored files will still crash

1 and 2 shouldn't occur in the latest nightlies. You can try downloading yesterday's from [here](http://build.koreader.rocks/download/nightly/v2015.11-1343-g7424202/).

For 3 we'll need a little more info.

**Comment by poire-z** [comment]
I think the 3rd issue is the one mentionned in #2532.
From what I recall when I looked at it last year, with android 6+, apps can't write files the natural way (so koreader can't create the sidecard dir) on the _second_ sdcard without some other kind of permissions (WRITE_MEDIA_STORAGE) *or* using some kind of specific API when you grant some other kind of permissions.
On my phone, the internal memory is named "sdcard", and needs permissions WRITE_EXTERNAL_STORARE - the additional physical SDcard that I insert in the SD slot is named BE34-17AA or something else, and needs WRITE_MEDIA_STORAGE, which can't be granted with the usual android permissions...

1st solution needs root to edit packages.xml (some details at https://forum.xda-developers.com/galaxy-s3/help/official-cm13-external-sd-write-fix-apps-t3275394/post66571825#post66571825 )
2nd solution needs the use of a stupid API, that koreader will probably won't be able to use without some specific android klugde to lua side.
Some more details at: https://stackoverflow.com/questions/12853752/eaccess-permission-denied-in-android

**Comment by Frenzie** [comment]
From your link:

> Thanks! In my opinion, the SD card write restriction is one of the worst changes Google made in Android yet. And I see no reason to deny write access to SD cards, despite of supporting the sales of expensive phones with large internal storages.

Google hates SD cards. Consider this: I'm partially responsible for enabling any filesystem on SD cards in CyanogenMod by *removing* some stupid artificial restrictions to FAT filesystems. The underlying Linux supports almost everything. Unfortunately Cyanogen continuously forgets to reapply the patch on new versions of Android. But I understand CyanogenMod is basically dead in favor of LineageOS these days. For the past two years I've kept my distance from messing with my phone's OS on my Zenfone 2 though, because Android isn't any fun to play with. It's a purposefully lobotomized Linux, which is absurdly frustrating.

What you linked once again defies belief. Google only allows FAT and then permissions don't work because… you need a different filesystem for that! Head, meet wall.

**Comment by toiiggww** [comment]
the 1st issue will when enter to full screen fail, the menu still visible. after lock done and unlock , the full screen mode success.

**Comment by toiiggww** [comment]
I've installed resent last version yet, when read external storage file still crash.
