### ISSUE TITLE
I am Android and I thank you

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3368]
Hi people

Thank you so much for the hard push for all the Android fixes recenty. I would like to thank everyone involved, both the devs and the testers. It is feeling more and more solid everyday.

Great work, now I feel like I did not waste my money on buying Android devices to read with koreader.

Cheers

**Comment by Frenzie** [comment]
You're welcome. I've only been able to fill in a few remaining missing pieces on top of the groundwork laid a few years ago. I mainly hope to have made it more viable for people who actually know and use Android to contribute. ;-)

**Comment by gerroon** [comment]
@Frenzie 
You totally made koreader useful on Android. Thanks again. Plus you guys implemented cover view in Android too.

**Comment by Frenzie** [comment]
That was @poire-z really. I did DjVu the other day though. ;-)

**Comment by gerroon** [comment]
Bring it all man, it is awesome. You have no idea how much koreader means to me. I am nobody without it. I have been using it steadily since my Kobo Glo days. It was a rough path with koreader on Android for a long time but it was ok I still liked it. 

Koreader is the only reader I use for reading. Other pdf viewers are just for browsing things like magazines etc. 

I mostly read pdfs, and there is no other app that can flow and crop like koreader for these 6 inch devices.

thanks

**Comment by Frenzie** [comment]
I'll close this now, but thanks!
