### ISSUE TITLE
Table of Contents does not work in the "scroll view mode"

### ISSUE THREAD

**Issue by lui247** [koreader/koreader#3370]
* KOReader version: v2015.11-1287-g5a2c8e4
* Device: Android Phone

#### Issue
When your have an epub file open and you select "scroll view mode" the Table of Contents does not work.  When you select a chapter or section it just stays in the same page you are on.  In order to use the Table of Contents you have to switch over to "page view mode" then it will work again.

#### Steps to reproduce
First open an epub formatted ebook with a table of contents.  Then make sure you are in "scroll view mode" then try using the Table of Contents.  It won't work.

**Comment by Frenzie** [comment]
This was fixed in #3333. Please try a recent nightly like http://build.koreader.rocks/download/nightly/v2015.11-1348-g3c99600/ :-)
