### ISSUE TITLE
FR: Use Android bluetooth volume control for page turn

### ISSUE THREAD

**Issue by jscris** [koreader/koreader#3374]
Would love to be able to use a bluetooth volume control remote for page turns with Android koreader.

**Comment by Frenzie** [comment]
Just to be sure, did you try and ascertain it doesn't work already?

**Comment by jscris** [comment]
Has not worked for me with an Icarus Illumina XL HD, the only Android device I have to check. Usbotg page turns with volume control have not worked either but same device does work with Moon+.

**Comment by Frenzie** [comment]
Do the regular volume controls work?

**Comment by Frenzie** [comment]
To be clear, USB OTG headset volume controls work for me.

**Comment by jscris** [comment]
Slider shows movement, so I've say yes.

**Comment by KenMaltby** [comment]
The MR thread starting here: https://www.mobileread.com/forums/showthread.php?p=3596367#post3596367

**Comment by Frenzie** [comment]
@jscris 
> Slider shows movement, so I've say yes.

I mean if they turn pages for you. But since you just said *slider* rather than button that might be relevant.

@KenMaltby I see, thank you. Anyway, while I have no Bluetooth volume control available to test with there is no reason to suppose it would function any differently than regular volume buttons or USB OTG volume buttons. They're just buttons that trigger the volume button up/down events.

**Comment by jscris** [comment]
All I know is that neither usbotg or bluetooth remotes turn pages in koreader but they do it moon+, which  has a setting for what the volume controls do, and that is set to page up and page down.

**Comment by Frenzie** [comment]
Do you know how to get an `adb logcat` out of your device? When pressing the buttons you'd get something like this:

```
10-19 17:29:37.133 25232 25270 I KOReader: DEBUG blitFrom 369 799 0 0 53 53
10-19 17:29:37.219  1836  1836 D EmojiAltPhysicalKeyDetector: onKeyUp() : KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_DOWN, scanCode=114, metaState=0, flags=0x8, repeatCount=0, eventTime=264315048, downTime=264314919, deviceId=0, source=0x101 }
10-19 17:29:37.219  1836  1836 D EmojiAltPhysicalKeyDetector: onKeyUp() : Not Mapped: 25
10-19 17:29:37.224 25232 25270 I KOReader: DEBUG key event => type: 1, code: 25(LPgFwd), value: 0, time: 1508426977.223589
10-19 17:29:37.298 25232 25270 I KOReader: DEBUG BackgroundRunner: _execute() @  1508426977
10-19 17:29:37.792  1089  1259 D WifiStateMachine: Disconnected CMD_START_SCAN source -2 2436, 2440 -> obsolete
10-19 17:29:38.472  1289  1289 V PhoneStatusBar: setLightsOn(true)
10-19 17:29:39.127 25232 25270 I KOReader: DEBUG key event => type: 1, code: 24(LPgBack), value: 1, time: 1508426979.127245
10-19 17:29:39.192 25232 25270 I KOReader: DEBUG ImageWidget: _render'ing
10-19 17:29:39.199 25232 25270 I KOReader: DEBUG ImageWidget: _render'ing
10-19 17:29:39.206 25232 25270 I KOReader: DEBUG ImageWidget: _render'ing
10-19 17:29:39.212 25232 25270 I KOReader: DEBUG ImageWidget: _render'ing
10-19 17:29:39.223 25232 25270 I KOReader: DEBUG blitFrom 2 2 0 0 28 28
10-19 17:29:39.254 25232 25270 I KOReader: DEBUG blitFrom 323 341 0 0 147 178
10-19 17:29:39.262 25232 25270 I KOReader: DEBUG blitFrom 451 500 0 0 20 20
10-19 17:29:39.262 25232 25270 I KOReader: DEBUG blitFrom 9 577 0 0 147 187
10-19 17:29:39.267 25232 25270 I KOReader: DEBUG blitFrom 137 746 0 0 20 20
10-19 17:29:39.268 25232 25270 I KOReader: DEBUG blitFrom 166 560 0 0 147 222
10-19 17:29:39.276 25232 25270 I KOReader: DEBUG blitFrom 294 763 0 0 20 20
10-19 17:29:39.277 25232 25270 I KOReader: DEBUG blitFrom 323 565 0 0 147 211
10-19 17:29:39.283 25232 25270 I KOReader: DEBUG blitFrom 451 758 0 0 20 20
10-19 17:29:39.284 25232 25270 I KOReader: DEBUG blitFrom 58 799 0 0 53 53
10-19 17:29:39.284 25232 25270 I KOReader: DEBUG blitFrom 141 799 0 0 53 53
10-19 17:29:39.299 25232 25270 I KOReader: DEBUG blitFrom 286 799 0 0 53 53
10-19 17:29:39.300 25232 25270 I KOReader: DEBUG blitFrom 369 799 0 0 53 53
10-19 17:29:39.387  1836  1836 D EmojiAltPhysicalKeyDetector: onKeyUp() : KeyEvent { action=ACTION_UP, keyCode=KEYCODE_VOLUME_UP, scanCode=115, metaState=0, flags=0x8, repeatCount=0, eventTime=264317325, downTime=264317162, deviceId=0, source=0x101 }
10-19 17:29:39.387  1836  1836 D EmojiAltPhysicalKeyDetector: onKeyUp() : Not Mapped: 24
10-19 17:29:39.388 25232 25270 I KOReader: DEBUG key event => type: 1, code: 24(LPgBack), value: 0, time: 1508426979.388476
```

**Comment by jscris** [comment]
No, and would need to investigate that. I'm just a little old lady. ;)  I've assumed since there was no setting for the function of the volume control up/down as in Moon+, that koreader needed a way to do that.  Will check back later as I need to go out for a while now. Thanks for the comments and interest!

**Comment by Frenzie** [comment]
Adding a cross-ref to #1760 although that sounds like it might be the exact opposite problem. (I.e., if KOReader is using the volume buttons for page turns then they can't control the volume.)

**Comment by jscris** [comment]
Haven't had time to do more testing, but there could choices for what the buttons do and volume up/down could be either volume or page turns.  When I said the slider shows movement with bluetooth, I meant that outside koreader, it did appear that bluetooth was active and changing the volume because a slider came up and showed movement. I don't use the audio on this reader, however.  I can't see any action within koreader from the use of bluetooth volume up/down.
