### ISSUE TITLE
statistics bug

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#3375]
* KOReader version:V2015.11-1312-ga710d2c
* Device: kobo h2o

#### Issue Time range statistics-> All books -> Total hours read only 25mins...
every book read time only around 1min

**Comment by robert00s** [comment]
Please do the following:

- upgrade KO to the latest version 
- run KO and than close it (menu -> exit)
- when KO is off go to folder koreader/settings and delete file statistics.sqlite3 or book.sqlite3
- open file koreader/settings.reader.lua find and remove line:
`["convert_to_db"] = true,`
save file
- run KO and check statistics - it should be ok.

**Comment by seacatwu** [comment]
thank you! @robert00s

**Comment by robert00s** [comment]
@seacatwu 
Is that helped you? Can I close it?

**Comment by Frenzie** [comment]
@robert00s What does your workaround do exactly btw? Work around a bug in the earliest versions of the statistics v2?

**Comment by robert00s** [comment]
Yes, its bug in the earlierst versions of statistics v2. 
Exactly this line: https://github.com/koreader/koreader/commit/a003b375c2a7d30a9382964922c04d7bb526b124#diff-b4081a1b3c6533bc4ce4ef105507d73fL223
It was fixed in: #3157

**Comment by seacatwu** [comment]
@robert00s  Yes，it works.
