### ISSUE TITLE
Some CBZ can't fit content width correctly

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#3376]
* KOReader version:V2015.11-1312-ga710d2c
* Device: Kobo aura h2o

#### Issue
I have used kindle comic converter to convert comics. 
 KO can't fit the content width correctly of these comics.
 It works well in another device which use Orion Viewer.
Is the KCC's output not suit for the KO?

**Comment by Frenzie** [comment]
What does this KCC program output? In principle a CBZ is just a zip file with a list of sequential images, so any issues should be relatively easily reproducible.

**Comment by Frenzie** [comment]
PS You might want to ensure settings like autocrop aren't getting in the way.

**Comment by seacatwu** [comment]
cbz = zip
and in this zip is jpgs.
Autocrop is not matter with fitting the content width.

**Comment by KenMaltby** [comment]
When the "Kindle" Comic Converter author brought his program to MR for user testing, I gave it a try and provided info on how it worked, in the AuraHD.  We worked out the image parameters and it was working well back then.  That was in KOReader of course.  As I remember it, you would have no need to use the "Fit to content" or any of the zoom settings, when the .cbz is properly prepared in KCC.

Luck;
Ken

**Comment by seacatwu** [comment]
the same cbz can fit to content width on the Orion Viewer(android).

**Comment by Frenzie** [comment]
It's unclear to me what the problem is. What have you tried and what do you expect to happen?

Through a combination of zoom mode and (auto)crop you should be able to get pretty much anything you want. It's working for me just as it always has on a few random CBZs I tried.

![screenshot_2017-10-20_15-48-05](https://user-images.githubusercontent.com/202757/31824038-2f197040-b5ae-11e7-87f1-48146df4b0b7.png)
![screenshot_2017-10-20_15-47-52](https://user-images.githubusercontent.com/202757/31824037-2ef45d5a-b5ae-11e7-89a4-eba1860c32b4.png)
![screenshot_2017-10-20_15-48-46](https://user-images.githubusercontent.com/202757/31824039-2f3a5738-b5ae-11e7-8edd-a470f179c158.png)

**Comment by seacatwu** [comment]
![img_20171020_225556](https://user-images.githubusercontent.com/9783549/31827798-124e4854-b5eb-11e7-8158-e6f989dff9e3.jpg)

**Comment by seacatwu** [comment]
The right one is kobo aura h2o,
The left one is Ireader Plus using orion viewer.
the same cbz converted by kcc.

**Comment by KenMaltby** [comment]
Your first image has the H2O on the left not right.  I see your point now, but when I have seen that in PDFs it appears that there is some color or other element that the zoom function sees as a part of the content.  KCC should have not provided that.

**Comment by Frenzie** [comment]
> Page corp is auto.

Did you also try tapping auto again? I think it misleadingly highlights it default but I don't it actually applies it by default.

@KenMaltby Yes, it looks to me like there is some kind of gray border surrounding the entire picture.

**Comment by seacatwu** [comment]
@KenMaltby I have made a mistake.....
@Frenzie I have tapped auto again.

**Comment by seacatwu** [comment]
@KenMaltby  I put the jpg in the photoshop, and found nothing around.

**Comment by KenMaltby** [comment]
Looking closely at your first H2O image above, I notice what appears like a lighter rectangle on the left edge, I would guess that the zoom is calculating the width of the content and including that as part of the content.

**Comment by poire-z** [comment]
You could try the `Dewatermark` option: it is good at removing gray background for reading scanned text (making it black & white maybe), but I don't know how that would do on pics with greyscale images. But, just for testing, it would help the auto-crop process.

**Comment by seacatwu** [comment]
@KenMaltby  that's shadow.

**Comment by seacatwu** [comment]
![image](https://user-images.githubusercontent.com/9783549/31845584-d1a7114c-b634-11e7-9c07-93222188e73a.png)
That's the one pic in the cbz.

**Comment by seacatwu** [comment]
I have zipped this pic and tested again. 
Cant't fit by content width.

**Comment by poire-z** [comment]
Indeed, there's some margin...
`Dewatermark` does not help, but `Reflow on` does!

**Comment by seacatwu** [comment]
@poire-z  Yes, it does! But it is slow.

**Comment by Frenzie** [comment]
The margin does appear bigger than I would expect. Perhaps MuPDF (or at least our version of it; upstream may have changed in this manner) is inclined to see a whole bitmap as content?

**Comment by Frenzie** [comment]
This will need to be rechecked once MuPDF 1.14 lands, cf. https://github.com/koreader/koreader-base/pull/762

**Comment by Frenzie** [comment]
It seems to work for me now.

![Screenshot_20240813_211149](https://github.com/user-attachments/assets/8c1ed99e-11ed-4df5-9ea8-1ca3542f22e0)
