### ISSUE TITLE
koreader crashing when started from kual in KT3(kindle)

### ISSUE THREAD

**Issue by aaditya99983** [koreader/koreader#3387]
@NiLuJe * KOReader version:
* Device:

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by aaditya99983** [comment]
crash log ::
./luajit: frontend/device/kindle/device.lua:363: unknown Kindle model 00
stack traceback:
	[C]: in function 'error'
	frontend/device/kindle/device.lua:363: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:37: in main chunk
	[C]: in function 'require'
	frontend/ui/uimanager.lua:1: in main chunk
	[C]: in function 'require'
	./reader.lua:92: in main chunk
	[C]: at 0x0000be8d

**Comment by Frenzie** [comment]
Please try to include version info. Does the problem occur in a recent build like this one?

https://github.com/koreader/koreader/releases/tag/v2017.10.04-nightly

**Comment by aaditya99983** [comment]
thanks @Frenzie it rocked!!

**Comment by Frenzie** [comment]
Cheers. 👍
