### ISSUE TITLE
Two page view

### ISSUE THREAD

**Issue by tejasvi8874** [koreader/koreader#3390]
* KOReader version: Nightly
* Device:Kindle reader

#### Issue
It would be helpful for books with extremely narrow contents like long lists.

**Comment by Frenzie** [comment]
This is actually already an option.

https://github.com/koreader/koreader/blob/ea284bbc3b2398d92cee8f9802ccca1f2fee5a0e/frontend/document/credocument.lua#L139-L143

https://github.com/koreader/koreader/blob/d0130ae9da92be38b573d1975d26c7485f033cfb/defaults.lua#L55-L56

Set it to something lover than the default of 7.

![screenshot_2018-03-06_21-07-42](https://user-images.githubusercontent.com/202757/37055625-77c216b8-2182-11e8-95b1-0d0c407a4aa3.png)
