### ISSUE TITLE
[i18n] Use separate strings for singular and plural

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3397]
* KOReader version: 23ab33c
* Device: all

#### Issue
Reported on Transifex by @jony08.
> Please use different strings for plural and singular because otherwise it doesn't look good in Swedish
by jony08, an hour ago 

It's a good idea in English too but apparently in Swedish it's worse.

> Timer är inställd på %1 timm(e/ar) och %2 minut(er)

> Timer är inställd på: %1:%2
> Det är %3 timm(e/ar) and %4 minut(er) från nu

plugins/readtimer.koplugin/main.lua:82
plugins/readtimer.koplugin/main.lua:115

Pinging @robert00s

**Comment by robert00s** [comment]
In Polish is better :)
0 godzin (0 hour)
1 godzin`a` (1 hour)
2 godzin`y` (2 hours)
3 godzin`y`
4 godzin`y`
5 godzin

:)
