### ISSUE TITLE
KOreader doesn't save immediately read position and options

### ISSUE THREAD

**Issue by ploum** [koreader/koreader#3398]
* KOReader version: october 16th
* Device: PB361

#### Issue
KOReader seems to only save options (like reading mode or police) and reading position on quitting. It means that if KOReader quits unexpectedly, nothing is saved.

#### Steps to reproduce
1. Read some text in a new book
2. Change some option (status bar, night mode, size) until it crashes.
3. Observe that on reopening, everything is back to the old status. Even the book itself might not be marked as opened.

**Comment by ploum** [comment]
Well, it seems that even exiting KOreader through the exit menu doesn't save anything. I've no idea when KOreader decide to save anything.

**Comment by Frenzie** [comment]
My take on a solution to the problem is currently undergoing some live testing as part of #3161.

However, it should save both when leaving a document for the file browser and when exiting. Does it crash on exit?

**Comment by ploum** [comment]
I don't understand the relationship between this bug and #3161 which seems to be about dictionnaries. Did i miss something? Is there something I could test?

**Comment by poire-z** [comment]
The real question is : how do you make it crash, and can we fix that ? :)
Saving settings is delayed till exiting book or koreader, to save on SDCard writes and wear (#3161 is a solution to limit the amount of writes).
We could force a save when an option is changed, but still, that amounts for some writes when trying things.

But you can change this behaviour by creating `defaults.persistent.lua` in koreader root dir, and adding in it:
```
-- change this to any numerical value if you want to automatically save settings when turning pages
DAUTO_SAVE_PAGING_COUNT = nil
```
(see `defaults.lua` for the list of other available settings).

**Comment by ploum** [comment]
Indeed but crashes will always be there. I believe that it should write at least in the following cases:

- Opening a new book
- Changing an option
- Adding a bookmark or highlighting a note.  (else information may be lost)

Those events are rare enough and are the most annoying to loose.

**Comment by Frenzie** [comment]
@ploum #3161 introduces a new append-mostly data format. Bookmarks are to be migrated to it at some point in the future. See #2789.

> Opening a new book

Doesn't that already happen? I think with `Start with last file` enabled you can already get caught in a crash loop.

> Changing an option

Currently unattractive due to bookmarks, but we can change this to an atomic swap of the current settings once bookmarks and highlights have left.

**Comment by ploum** [comment]
Thanks, I understand better.

But, currently, opening a book is not saved. I know it because, currently, koreader has only saved book and position only once. So each time koreader crashes (which is quite frequent), I'm back to the very first book I've read with koreader on a very specific page. The sleep cover is also the one of that book.

What is strange is that other opened book are shown in koreader history. But they are marked as never opened.

**Comment by Frenzie** [comment]
Right, open last book and history are separate from DocSettings. The bolded documents technically aren't "never opened" or some such but without DocSettings.

**Comment by ploum** [comment]
I believe that, at least, position should be saved each time the device is in "pause". 

As KOReadear crashes less (wich is nice), it is sometimes ridiculous: it consider that a 800 pages book is unread even though I was at page 700 and reading that book for days.

**Comment by robert00s** [comment]
Done in #5687.
