### ISSUE TITLE
Images and covers should not follow the nightmode

### ISSUE THREAD

**Issue by ploum** [koreader/koreader#3399]
* KOReader version: october 16th
* Device: PB361

#### Issue

When nightmode is enabled, every image is displayed as negative. Even the cover when the device sleep. This should not be the case, images should always be displayed normally.

**Comment by Frenzie** [comment]
It's a known issue. #2571 I'll close this as a duplicate. :-)

**Comment by ploum** [comment]
Sorry for the duplicate ;-)
