### ISSUE TITLE
Shake to wake

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#3400]
Somehow, I got the impression that there now was a feature to wake up the device by shaking it. I thought I scanned something like that on mobileread and my Aura H2O sometimes wakes up without me pressing the power button. 

However, I can't reproduce it nor can I find a pull request or issue mentioning it.

_So is this implemented already or not?_

The reason that I am interested is, that we have a Kobo Glo which somehow survived falling 10m down from a tower with only the power button smashed. We now use a sleep cover to wake it. However, I rather not use a cover as it adds weight. So either I add the frontlight to the wakeup keys in koreader or linux, or I use the accelerator dev input to wake it.

**Comment by Frenzie** [comment]
The H2O has an accelerometer? O_o

**Comment by Markismus** [comment]
Doesn't it? I thought I remembered there to be a listing of it in /dev. Still having a hard time waking up this Sunday, it seems...
