### ISSUE TITLE
Close the book when finished.

### ISSUE THREAD

**Issue by ploum** [koreader/koreader#3405]
* KOReader version: october 2017
* Device: PB 361

#### Issue
When I finish a book, a prompted with a nice popup asking me to rate it. Nice (is that uploaded somewhere?). But when I close the popup, I'm back to the last page of the book.

It should close the book and bring me back to the home page instead.

**Comment by Frenzie** [comment]
I think there was a big discussion about these things at the time. Since you can go to the status window at any time and you (or at least I) may want to return to a previous location in the book, it's definitely not as simple as doing just that.

> Nice (is that uploaded somewhere?).

Not to my knowledge. You might be able to export it or something. https://www.mobileread.com/forums/showthread.php?t=265433

**Comment by ploum** [comment]
What's the intended workflow for a normal user that finish a book with koreader?

**Comment by Frenzie** [comment]
I'm not sure really, but I'm personally more in the #2363 camp. :-P

**Comment by ploum** [comment]
That could be a way. Not having that window automatically at the end might be a solution. What is important, IMHO, is to be able to "close" a book and to easily switch to the next one.

**Comment by poire-z** [comment]
When you finish the book, I just go to File Browser (that closes literally the book, closing the reader engine) to select another one (and, for my use case, often to delete the one finished before that).

**Comment by Frenzie** [comment]
Oh, perhaps I misunderstood the question. Yes, I go to the file browser or history.

**Comment by ploum** [comment]
Can you describe me exactly your actions (where you click and every step) for when you finish a book?

**Comment by Frenzie** [comment]
I'm referring to these two actions:

![screenshot_2017-10-23_09-55-51](https://user-images.githubusercontent.com/202757/31878522-b74b6bf2-b7da-11e7-847b-5ce922bfdf12.png)

**Comment by ploum** [comment]
I think it's not really user friendly to force the user to go to the menu and make a choice when he realises that, hey, there's no next page. That's why I believe it's important to "close" a book once it is finished.

Some users may never go to the menu at all (if Koreader was installed on their device)

**Comment by Frenzie** [comment]
It would be trivial to add some text buttons or icon buttons at the top somewhere if that's not visually overcrowding.

<img src=https://user-images.githubusercontent.com/202757/31884396-355a014a-b7ed-11e7-8cf8-3b5086d931a5.png width=30%>

**Comment by ploum** [comment]
Or marking it as "complete" in the update status could close the book and return to the home page. (that's what I tried). It is not perfect but it allows to close a book even in the middle if you don't like it.

**Comment by KenMaltby** [comment]
You could add "Remove from history list" to the "Complete" button's functions.

**Comment by ploum** [comment]
The "remove from history" would be misleading and not really correct. If you read it, you want to know that it's in your history (with potentially the date of starting and completion)

**Comment by KenMaltby** [comment]
Why?  Should I expect an audit of my reading habits?  I could see an indicator on the books general file listing, that it has been read, but the History function is too useful to clutter it up with such "historical" data.

**Comment by poire-z** [comment]
I'd like our History to stay the way it is, a simple list with a single view.
What ploum would like would need 2 kind of views (full/only not completed), a way to store and retrieve the completed status, a way to toggle between views.
Having it full with historical records would also make it slower (1000 items to retrieve paths, check for sidecar, possibly parse the sidecar to retrieve percent).

It would be simpler to have another feature, "Reading log", similar to how "Dictionary lookup history" is made, that would be filled with bookname, start time, completed/abandonned time and status, when you decide that on the Book status widget. That way, it would not clutter history, and have no performance impact. And could be disabled/erased like Dict lookup history can be.

**Comment by robert00s** [comment]
Done in # #3943.
