### ISSUE TITLE
Displaying opened but unfinished books

### ISSUE THREAD

**Issue by ploum** [koreader/koreader#3406]
* KOReader version: october 2017
* Device: PB361

My use case is that I usually have a list of books to read. Sometimes, I read multiple books from this list at the same time.

On most device, I open, even for only one page, every book I need/want to read in the short term future. That way, the "currently reading" screen is my "to read" list.

Problem: there's no such screen with Koreader. The history screen works fine until you have a lot of finished books.

There should be a "currently reading" screen. Or a way to filter out finished books from the history screen.

Bonus: seeing the percentage read of each book in that list.

**Comment by Frenzie** [comment]
Try Settings → Display mode → History display mode

![screenshot_2017-10-22_18-21-02](https://user-images.githubusercontent.com/202757/31863956-d7b06878-b755-11e7-8549-e049c8e45b59.png)
![screenshot_2017-10-22_18-21-15](https://user-images.githubusercontent.com/202757/31863957-d7d28980-b755-11e7-86e4-de2fa4ad797c.png)

**Comment by ploum** [comment]
mmm, for whatever reason, it seems I don't have a menu in the history view. I thought it was on purpose.

**Comment by Frenzie** [comment]
Sorry, I suppose I was misleading. You can only access these settings from the file browser. ;-)

**Comment by ploum** [comment]
I managed to play the options. I found how to have the percentage (it was not displayed because I was using the mosaic view, I forgot it was not the default).

But I didn't find a way to hide finished books. In fact, I'm not even sure the concept exists: those books are displayed as being 100% read.

**Comment by poire-z** [comment]
Hold on a book in FileBrowser or History, you get then a menu allowing you to "Purge .sdr" (removing the docsettings = reseting book status = marking it as new), "Delete", and in History "Delete from history". Should allow everyone to have it his own way.

**Comment by ploum** [comment]
Well, that's not really correct. Finished books are part of the history and should stay in history. There simply should be a way to hide them. (which makes a lot of sense because a lot of the time, you want to browse unread books on your device)

**Comment by poire-z** [comment]
Ah, ok, we don't have that.
What would be the analogy with physical books ? :)

**Comment by Frenzie** [comment]
My wife maintains a to-read bookcase and the rest is the ordered stuff.

**Comment by ploum** [comment]
I don't have an analogy. That's one of the thing which makes virtual books superior to physical books ;-)

**Comment by KenMaltby** [comment]
The History feature is one of the most useful parts of KOReader, and can be used in a number of ways.  Taking the name literally as some chronicling of everything you have read, would be an extreme view of its purpose.  It is quite legitimate to remove books you have read from the "History" menu.  Your use of the feature as a "currently reading"/to be read list is a common way to use it, and would make removing read books, from the listing, a needed feature.  As it is, there is just that feature in the long press menu, for the listed books.  I don't see where a "Hide" option would add anything to what there is now.

Luck;
Ken

**Comment by ploum** [comment]
Currently, it is called "History" and acts like an history.

Using it as a reading list by manually removing the books you have read is a hack. Besides, it is not compatible with keeping an history (if you are interested in both feature).

A "currently reading" list seems something quite useful and relatively easy to implement (there's no new concept to create in the database, let's just take the book opened).

**Comment by KenMaltby** [comment]
There are those who read a number of books on the same subject and use the History to be able to jump from book to book without loosing place in any of them.  There are those of us who read books/documents with maps, diagrams, and tables that are worth having a full screen version readily available, in the History, where they can be quickly referenced and return to the page you are on. 

The point being that keeping a "History" listing of books read is not a practical use of the feature for many.

**Comment by cramoisi** [comment]
I'm thinking about how they do it on kobo-nickel : they use categories "Reading" / "Read". Perhaps there is some way to use the "completed", "unfinished", "opened" data from koreader and ask the file-browser to display only these ?
For my case, I only load what I want to read on the reader, got a "bestof" folder for emergency cases but I think maintaining loads of books on the reader is useless. Calibre does that well enough.

**Comment by shapirus** [comment]
New user of koreader here. I am surprised that this issue is forgotten (is it really?), given the rich set of features that koreader has.
From my point of view, hiding the finished books may not be always wanted (for example one may want to reopen a finished book to see something there). The problem can be solved by adding a checkbox like "show finished books last" to both file browser and history mode settings, so that they are still visible, but do not interfere with unread and being currently read books.

**Comment by NiLuJe** [comment]
xref to #7902

**Comment by shapirus** [comment]
time for me to learn a little lua? possibly, as it may also come in handy some day :).

some hints at what source files contain the sorting functions for history view and file browser, and where new options should be added, would be very welcome. i might look into submitting a PR indeed.

**Comment by NiLuJe** [comment]
I was specifically speaking of #7902 ;p. The one we're in touches slightly more stuff in general, and slightly older and gnarlier stuff in particular ;p.

Usually, ripgrep and the name of a setting will get you a good starting point of where to look ;).

**Comment by melyux** [comment]
The #8820 changes is good, but the option is not remembered, reset every time you open History. It should remember your filter choice permanently to really befit this issue (which it otherwise fixes quite well).
