### ISSUE TITLE
setWifiEnabled(true) not working with android 7.0

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3410]
* KOReader version: todays git
* Device: arm pc (android 7.0 with GApps)

#### Issue
setWifiEnabled(true) not working 
(lua-jit function)

#### Steps to reproduce
Turn off Wifi and cell network, start newsDownloader, when popup "no wifi" click on "turn on"

##### `crash.log` (if applicable)

Log:
>10-23 20:42:40.923  4015  4032 I KOReader: DEBUG single tap detected in slot 0 {
10-23 20:42:40.923  4015  4032 I KOReader:     ["y"] = 1054.51171875,
10-23 20:42:40.923  4015  4032 I KOReader:     ["x"] = 672.59399414063,
10-23 20:42:40.923  4015  4032 I KOReader:     ["h"] = 0,
10-23 20:42:40.923  4015  4032 I KOReader:     ["w"] = 0
10-23 20:42:40.923  4015  4032 I KOReader: }
10-23 20:42:40.933  4015  4032 I KOReader: DEBUG blitFrom 101 851 0 0 140 140
10-23 20:42:41.232  4015  4032 I KOReader: setting wifi to: 
10-23 20:42:41.261  1034  1053 D WifiService: setWifiEnabled: true pid=4015, uid=10080
10-23 20:42:41.299  4015  4032 I KOReader: DEBUG close widget
10-23 20:42:41.310   908  1206 D SoftapController: Softap fwReload - Ok
10-23 20:42:41.406   908  1206 D CommandListener: Setting iface cfg
10-23 20:42:41.407   908  1206 D CommandListener: Trying to bring down wlan0
10-23 20:42:41.424   908  1206 D CommandListener: Clearing all IP addresses on wlan0
10-23 20:42:41.472  1034  1211 E WifiMonitor: killSupplicant p2pfalse init.svc.wpa_supplicant=unknown init.svc.p2p_supplicant=unknown
10-23 20:42:41.476  1034  1211 E wifi    : Can not initialize the vendor function pointer table
10-23 20:42:41.476  1034  1211 E WifiNative-HAL: Could not start hal
10-23 20:42:41.476  1034  1211 E WifiStateMachine: Failed to start HAL
10-23 20:42:41.594  1983  1983 V PhoneStatusBar: setLightsOn(true)
10-23 20:42:41.629  1983  1983 V PhoneStatusBar: setLightsOn(true)
10-23 20:42:41.654  1034  1211 D WifiMonitor: startMonitoring(wlan0) with mConnected = false
10-23 20:42:41.669  4015  4032 I KOReader: DEBUG blitFrom 4 4 0 0 63 63
10-23 20:42:42.234  4050  4050 I wpa_supplicant: Successfully initialized wpa_supplicant
10-23 20:42:42.289  4050  4050 I wpa_supplicant: rfkill: Cannot open RFKILL control device
10-23 20:42:42.328  4050  4050 I wpa_supplicant: nl80211: Could not re-add multicast membership for vendor events: -2 (No such file or directory)
10-23 20:42:42.428  4050  4050 E wpa_supplicant: global ctrl interface @android:wpa_wlan0 matches ctrl interface wlan0 - do not open per-interface ctrl interface
10-23 20:42:42.487  1034  1211 I WifiConnectivityManager: User band preference: 0
10-23 20:42:42.492  1034  1211 D WifiConfigManager: Loading config and enabling all networks 
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory: readNetworkHistory: No config file, revert to default, java.io.FileNotFoundException: /data/misc/wifi/networkHistory.txt (No such file or directory)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory: java.io.FileNotFoundException: /data/misc/wifi/networkHistory.txt (No such file or directory)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at java.io.FileInputStream.open(Native Method)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at java.io.FileInputStream.<init>(FileInputStream.java:146)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at java.io.FileInputStream.<init>(FileInputStream.java:99)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.server.wifi.WifiNetworkHistory.readNetworkHistory(WifiNetworkHistory.java:331)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.server.wifi.WifiConfigManager.readNetworkHistory(WifiConfigManager.java:1828)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.server.wifi.WifiConfigManager.loadConfiguredNetworks(WifiConfigManager.java:1658)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.server.wifi.WifiConfigManager.loadAndEnableAllNetworks(WifiConfigManager.java:429)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.server.wifi.WifiStateMachine$SupplicantStartingState.processMessage(WifiStateMachine.java:4365)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:980)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:799)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at android.os.Looper.loop(Looper.java:154)
10-23 20:42:42.541  1034  1211 E WifiNetworkHistory:    at android.os.HandlerThread.run(HandlerThread.java:61)
10-23 20:42:42.541  1034  1211 D WifiConfigManager: loaded 0 passpoint configs
10-23 20:42:42.547  1034  1211 E IpConfigStore: Error parsing configuration: java.io.FileNotFoundException: /data/misc/wifi/ipconfig.txt (No such file or directory)
10-23 20:42:42.597  1034  1211 D WifiNative-HAL: Setting external_sim to 1
10-23 20:42:42.602  1034  1211 D WifiStateMachine: Setting OUI to DA-A1-19
10-23 20:42:42.609  1034  1211 D WifiCountryCode: Succeeded to set country code to: US
10-23 20:42:42.610  1034  1211 E WifiLogger: no ring buffers found
10-23 20:42:42.611  1034  1211 E WifiLogger: Failed to start packet fate monitoring
10-23 20:42:42.652  1034  1034 D RttService: SCAN_AVAILABLE : 3
10-23 20:42:42.653  1034  1213 I WifiScanningService: wifi driver loaded with scan capabilities: max buckets=16
10-23 20:42:42.657  1034  1214 D RttService: DefaultState got{ when=-4ms what=160512 target=com.android.internal.util.StateMachine$SmHandler }
10-23 20:42:42.658  1034  1211 I WifiConnectivityManager: Set WiFi enabled
10-23 20:42:42.659  1034  1211 I WifiConnectivityManager: scheduleWatchdogTimer
10-23 20:42:42.664  1034  1211 W AlarmManager: Unrecognized alarm listener com.android.server.wifi.WifiConnectivityManager$3@e31fe67
10-23 20:42:42.664  1034  1211 E WifiScanner: listener cannot be found
10-23 20:42:42.693  1034  1211 D WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
10-23 20:42:42.695  1034  1061 E BatteryStatsService: no controller energy info supplied
10-23 20:42:42.698  1034  1061 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
10-23 20:42:42.700  1034  1061 E KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
10-23 20:42:42.739  1034  1211 D WifiNative-HAL: Failing getSupportedFeatureset because HAL isn't started
10-23 20:42:42.741  1034  1061 E BatteryStatsService: no controller energy info supplied
10-23 20:42:42.742  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784162
10-23 20:42:42.745  1034  1061 E KernelCpuSpeedReader: Failed to read cpu-freq: /sys/devices/system/cpu/cpu0/cpufreq/stats/time_in_state (No such file or directory)
10-23 20:42:42.746  1034  1061 E KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
10-23 20:42:44.754  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784164
10-23 20:42:46.763  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784166
10-23 20:42:48.772  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784168
10-23 20:42:50.782  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784170
10-23 20:42:52.793  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784172
10-23 20:42:54.802  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784174
10-23 20:42:56.813  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784176
10-23 20:42:58.822  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784178
10-23 20:43:00.048  1034  1034 I ActivityManager: Killing 3403:com.android.mtp/u0a11 (adj 906): empty #17
10-23 20:43:00.477  1034  1528 D ActivityManager: cleanUpApplicationRecord -- 3403
10-23 20:43:00.506  1034  1156 D VoldConnector: SND -> {13 appfuse unmount 10011 3403 MtpDocumentsProvider}
10-23 20:43:00.516   861   886 E vold    : Failed to open /proc/3403: No such file or directory
10-23 20:43:00.518  1034  1157 D VoldConnector: RCV <- {400 13 Command failed}
10-23 20:43:00.525  1034  1156 E MountService: Failed to unmount appfuse.
10-23 20:43:00.832  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784180
10-23 20:43:02.842  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784182
10-23 20:43:03.596  1621  1636 I art     : Background partial concurrent mark sweep GC freed 50879(3MB) AllocSpace objects, 1(20KB) LOS objects, 26% free, 11MB/15MB, paused 1.692ms total 104.394ms
10-23 20:43:04.852  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784184
10-23 20:43:06.863  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784186
10-23 20:43:08.872  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784188
10-23 20:43:10.882  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784190
10-23 20:43:12.892  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784192
10-23 20:43:14.902  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784194
10-23 20:43:16.912  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784196
10-23 20:43:18.922  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784198
10-23 20:43:20.932  4015  4032 I KOReader: DEBUG BackgroundRunner: _execute() @  1508784200

**Comment by mwoz123** [comment]
Works fine on Inbook Prime (android 4.4) .
Might be an issue with my emulator .

Any one else was able to reproduce the problem?
Maybe it's not worth to spend time on it..

**Comment by Frenzie** [comment]
Yes, this looks like an emulator issue. Not a KOReader issue.
