### ISSUE TITLE
Inadequate scaling of images in fb2 and epub files

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#3416]
* KOReader version: v2015.11-1270-g180f575
* Device: Kobo Aura One

#### Issue

The images in ebooks (fb2 and epub files) should be scaled to "page width". Otherwise, on high resolution screens like Kobo Aura One they are so small that they are unreadable.

#### Steps to reproduce

Open the book "Lightning" by Martin Uman (epub format, 2013 edition) and try to look at the first Figure and Table that occur in the book. The table is unreadable. And this goes for every image in this book. Because of this I had to revert to using CoolReader for reading ebooks. Recently I commented that Koreader's rendering is practically as good as CoolReader and this is true for the text, but inline images are handled by CoolReader more correctly, i.e. stretched to "page width", making them readable always.

**Comment by Frenzie** [comment]
Note that you can always hold on an image.

**Comment by tigran123** [comment]
Oh, that's nice, I didn't know about this very useful feature. Ok, but still some images have a long caption which explains what is displayed on them and using this "hold to zoom in picture" feature one would have to keep switching between the two views. I see no reason why all images cannot be always displayed in "fit to page width" mode.

**Comment by poire-z** [comment]
I like small images on the wikipedia saved as epub.
On docs with many images, fit-to-width images may clutter the reading, you would have on a page 75% images, 25% text. Plus the fact that crengine would display a big image that would not fit on the available height remaining on a page, on the next page: so lots of blank space...
So, it depends on how important the images are to the reader :) And there's Hold to view them with imageviewer when one wants to see more.

Anyway, I think it depends on what the producer has put in its css, and crengine, I think, do respect that.
Image with no style: display it as its real pixels size
image with `style='width: 100%'` is displayed full width.

If you really want images full width, I think you could have a custom css (copy epub.css to MY_epub.css), and add/replace :
`img { text-indent: 0px; display: block; width: 100%; }`

If that works, the question would be: should that be put in the default epub.css? And I'm definitely against :)

**Comment by Frenzie** [comment]
I suspect the key here isn't necessarily fit to page width (which should be max-width really — I suspect our img width secretly works that way regardless) but rather scale by DPI.

It certainly cannot be the default to 100% 'em all up, because plenty of images aren't those kinds of images.

**Comment by tigran123** [comment]
Scaling by dpi would mean calculating (or sometimes guessing) and it is not flexible enough, i.e. cannot be controlled by the user. I think at least as an option there should be a way for the user to say to Koreader "I want inline images to occupy maximum amount of space on the screen" (and it should work for both portrait and landscape aspect ratio images).

However, @Frenzie 's suggestion to hold on the image to view it fullscreen is actually sufficient for my needs, so I don't mind even if nothing happens at all on this issue :)

**Comment by Frenzie** [comment]
@poire-z 

> Anyway, I think it depends on what the producer has put in its css, and crengine, I think, do respect that.

Incomplete at best. If you look at our own test suite, the juliet.epub file starts with a cover image, `style="height:100%; max-width:100%"`. Tell me if this looks anything like that. :-P

<img src=https://user-images.githubusercontent.com/202757/31947874-a78b0cc6-b8d5-11e7-891e-5c1770ad1c2b.png width=30%>

Oddly enough calibre seems to have a (hard-coded?) clientHeight limit of 800. But since that still means some 1600 real pixels on my monitor (and hopefully more on higher DPI screens) it's less egregiously wrong. And in any case, that's not our problem.

There are a couple of width/height tests in the css test suite that crengine fails.

s10.2
s10.5

(For some reason our copy of the test suite is very incomplete.)

**Comment by poire-z** [comment]
Yes, it's incomplete: it does not handle standalone height: percentage, it insists of needing a width, and apply some factor to width:
https://github.com/koreader/crengine/blob/a3eeb1bf2663506fa84c38470aca6fa66d9636df/crengine/src/lvtextfm.cpp#L271-L274
It also indeed doesn't handle max-width, but it takes care to not overflowing screen width I think. Overall, it's quite OK on the book I read.

But the one time I had to read a epub with only images, I needed to use a custom made koreader/data/MY_img_full_width.css
```
img {
    text-align: center;
    text-indent: 0px;
    display: block;
    width: 100%;
}
```
and that worked pretty well.

**Comment by tigran123** [comment]
Thank you, @poire-z --- your idea with setting `width: 100%;` works absolutely fine!

**Comment by poire-z** [comment]
Except for the lack of support for heights in %, I think we should be fine now with the sizing of images with:
https://github.com/koreader/crengine/pull/409
https://github.com/koreader/crengine/pull/413
https://github.com/koreader/crengine/pull/416
