### ISSUE TITLE
FR: InfoMessage log

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3418]
* KOReader version: 3639c3e
* Device: all

#### Issue
InfoMessages come and go. I don't think they should be kept indefinitely but it'd be nice to be able to look back at them. Also see https://simon.shimmerproject.org/2017/10/17/new-hotness-xfce4-notifyd-0-4-0/

Should be trivial to add something, e.g. here:
https://github.com/koreader/koreader/blob/3639c3e7c6060990a945e4a2113343dc0f46aa3f/frontend/ui/widget/infomessage.lua#L151-L160

**Comment by poire-z** [comment]
Let's say issues associated to a milestone that get postponed more than 12 months deserve to get buried down in the issues list :)

**Comment by Frenzie** [comment]
Let's forget about this one then.
