### ISSUE TITLE
PB: Page not always redrawn after opening a file

### ISSUE THREAD

**Issue by mk-f** [koreader/koreader#3419]
* KOReader version: git
* Device: PocketBook Inkpad 2

#### Issue

Opening a file will sometimes stall at the "Opening File"-Dialoge forever.  Tapping somewhere on the Screen multiple times seems to force a refresh, afterwards the reader can be used as usual. 

This occurs mostly after a fresh start (but also not always). Until now I had no luck to reproduce the Bug either under strace or with gdbserver (race condition of some sort)? I'll investigate further.

**Comment by Frenzie** [comment]
Also see https://github.com/koreader/koreader/issues/1955#issuecomment-338912609 for some logs. (Although I didn't really see anything in them at a glance.)

**Comment by mk-f** [comment]
Okay here are some strace-logs, the following may be interesting:

```
15:17:51 [4025ca38] mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x4009e000
15:17:51 [402534fc] read(12, "local ffi = require(\"ffi\")\n\nffi."..., 8192) = 1088
15:23:01 [402534fc] read(12, "", 4096)  = 0
15:23:01 [4020be10] close(12)           = 0
```
and
```
15:17:51 [402356bc] nanosleep({0, 50000000}, NULL) = 0
15:17:51 [40260f74] msgrcv(32769, 0xa9002, 19933640, 0x14 /* MSG_??? */) = -1 ENOMSG (No message of desired type)
15:17:51 [402356bc] nanosleep({0, 50000000}, NULL) = ? ERESTART_RESTARTBLOCK (To be restarted)
15:23:01 [402356bc] restart_syscall(<... resuming interrupted call ...>) = 0
15:23:01 [40260f74] msgrcv(32769, 0xa9002, 19933640, 0x14 /* MSG_??? */) = -1 ENOMSG (No message of desired type)
15:23:01 [402356bc] nanosleep({0, 50000000}, NULL) = 0
15:23:01 [40260f74] msgrcv(32769, 0xa9002, 19933640, 0x14 /* MSG_??? */) = 20
```
(note the six minutes delay)

If I open the same book after a full power-cycle, the bug is reproducible, **but only if the reader is not charging**.  Attaching a cable while the execution seems to be stalled has the same effect as tapping the display multiple times. This is unfortunate, because it makes it impossible to debug via cable under gdb.

On a sitenode @Frenzie: Apparently I did not manage to build a debug-build after all - luajit is always stripped, regardless of whether i use ``KODEBUG=1 ./kodev build pocketbook`` or `` ./kodev release --debug pocketbook``


[strace.log.165.txt](https://github.com/koreader/koreader/files/1415163/strace.log.165.txt)
[strace.log.169.txt](https://github.com/koreader/koreader/files/1415164/strace.log.169.txt)
[crash.log](https://github.com/koreader/koreader/files/1415160/crash.log)

**Comment by Frenzie** [comment]
@mk-f Looks like this line is getting in the way: https://github.com/koreader/koreader-base/blob/f39650dedf221fd801bc6cb472f1f8643a0788e8/Makefile.third#L142

There's a variety of relatively hard-coded stuff (Android ARM arch, the compiler flags) that I've been trying to make more easily changeable on demand, but it's an ongoing process. Clearly I should also search the Makefiles for `strip` and make sure it doesn't happen for a `KODEBUG` build.

These logs should be at least somewhat helpful, although I'm afraid I can't say much of use about the ffi thing you pointed out. Have you been able to try the memory allocation thing I suggested? (Stick it at the top of reader.lua or some such.)

Another avenue perhaps worth exploring as a workaround is putting something in https://github.com/koreader/koreader/blob/e8aeb3cfa503017701f2659086d09dc9fededa28/platform/pocketbook/koreader.app (Generating some fake events of some sort?)

**Comment by mk-f** [comment]
An other observation: It seems like the whole device freezes. I wrote a script which continuously echos the time to a file and started it before ``reader.lua``. The delay is exactly the same as in ``crash.log``.

@Frenzie it tried the memory-hack - no luck.

**Comment by Frenzie** [comment]
The whole device huh? I'm not sure if that's better or worse. :-P

**Comment by mk-f** [comment]
Okay, this was painful. The device is actually going to sleep while the book is loaded if not connected to usb or wlan. Fortunately there is a ``libinkview``-function (of course without additional documentation, apart from [this](http://www.the-ebook.org/forum/viewtopic.php?p=802598#802598) forum-post) which  can be used to control the PBs desire for sleep: ``void iv_sleepmode(int on);``

I put ``inkview.iv_sleepmode(0)`` in ``PocketBookPowerD:init()`` as a workaround and everything is fine. @Frenzie: Where would be the best point to disable and reenable the sleepmode code-wise?

**Comment by Frenzie** [comment]
@mk-f If we want to do this only on suspend then I'd suggest something like this:

https://github.com/koreader/koreader/blob/0e5293f1eb31e7af4108a79fd6f87ca7dc89ced9/frontend/device/kobo/device.lua#L343

**Comment by Frenzie** [comment]
I think that's coupled with this (been a while since I looked at it)

https://github.com/koreader/koreader/blob/71553a5190197d80c069895daa34c238bcf9c4f3/frontend/ui/uimanager.lua#L74-L94

**Comment by mk-f** [comment]
I think we talk at cross-purposes: The PB itself initiates a ''system-wide'' suspend while the process still loads the book **without koreader noticing** (No _DEBUG Suspending..._ in log). The prevent this, one has to disable this kind of auto suspend as soon as the application launches and re-enable it after the book is loaded.  So i think the question is: where is ``as soon as the application launches`` and ``after the book is loaded`` ;).

Or do you mean to re-enable it only on Suspend (by Button)?

**Comment by Frenzie** [comment]
Sorry, I thought this was the other topic. (Serves me right from shooting off a quick reply I suppose. :-P)

Ideally it would probably go in the device-specific init method, wouldn't it?

https://github.com/koreader/koreader/blob/0e5293f1eb31e7af4108a79fd6f87ca7dc89ced9/frontend/device/pocketbook/device.lua#L58

I'm on Windows atm so I'm not sure if there's a document loaded event.

But like you said, aren't we at danger of this happening again while in the middle of reading?

**Comment by mk-f** [comment]
> But like you said, aren't we at danger of this happening again while in the middle of reading?

Actually this is already happening, i attached three logs doing ``dmesg | grep PM`` on the device after reading ~two minutes each time, one with koreader w/o the ``inkview.iv_sleepmode(0)``, one with it, and one after running the original PB reader-software. 

As one can see, the PB suspends roughly every two seconds - **also while the original reader-software is running**. I don't think this is a problem _after the book is loaded_, as the wakeup is fast enough for page-turning.

On the other hand, after using ``iv_sleepmode(0)`` no suspends occur at all.

I have to admit, that the overall speed is increased when disabling sleeping, but this may impair battery-life quite a bit. For now, i would  enable it again after the book-loading-process is finished (where would that be?). Later it might be possible to add an option which disables sleeping entirely at the cost of faster battery-drain.

[dmesg_koreader_fix.txt](https://github.com/koreader/koreader/files/1464895/dmesg_koreader_fix.txt)
[dmesg_koreader_nofix.txt](https://github.com/koreader/koreader/files/1464896/dmesg_koreader_nofix.txt)
[dmesg_pocketbook_orig.txt](https://github.com/koreader/koreader/files/1464897/dmesg_pocketbook_orig.txt)

**Comment by Frenzie** [comment]
Probably `registerPostInitCallback` (like I said, on Windows, sorry =)).

**Comment by Frenzie** [comment]
@mk-f Back on Linux. There's the `PreRenderDocument` and `ReaderReady` events (see ReaderUI). You probably want the latter.

**Comment by mk-f** [comment]
I'm not quite sure yet how events work. In my understanding i can not register an event-handler directly in ``device.lua``. I tried to add ``self.event_handlers["ReaderReady"]`` to ``uimanager.lua`` but i doubt that is the correct way of doing it. Or should i directly modify ``readerui.lua``?

**Comment by Frenzie** [comment]
The way to use it (which cascades to widgets and plugins, maybe not into Device) is `Module:onEventName`.

So that would be `Device:onReaderReady` if that works.

But judging by these lines it should be fine to add some device-specific stuff in UIManager. Maybe @houqp has some plans to improve on it in the future? Modifying ReaderUI sounds like a worse choice to me because that'd make it less device-independent.

https://github.com/koreader/koreader/blob/06dfe4fb78ed48f655c2beef902a77696e77205a/frontend/ui/uimanager.lua#L74-L166

**Comment by mk-f** [comment]
Its not populated into Device. I tried the following in the Simulator, but it seems like the event never fires:
```
self.event_handlers["ReaderReady"] = function()
    logger.info("READER READY fired")
end
```
I'll retry on real hardware later.

**Comment by Frenzie** [comment]
I see, so ReaderReady is only propagated down to the widgets. Make sense.

We could probably just stick something like this in `ReaderUI:init()`. (Tested and working.)

```lua
if Device:isPocketBook() then
    self:registerPostReadyCallback(function()
        --stuff
    end)
end
```

It doesn't feel entirely clean though.

**Comment by mk-f** [comment]
Okay, here is the problem: while ``iv_sleepmode(0)`` works and disables suspending, ``iv_sleepmode(1)`` has no effect *as long as not called inside ``pb_event_handler()`` and therefore in the InkViewMain()-fork*. 

Seems like ``iv_sleepmode()`` depends on some state which is just reachable in ``InkViewMain()``. This is a problem, because at the moment there is no way to communicate with the fork running ``pb_event_handler()``. 

My temporary hack in ``input-pocketbook.h`` looks like the following, but there has to be a more elegant solution.

```c
    } else if (type == EVT_KEYPRESS) {
 	if (par1 == KEY_NEXT)
 		iv_sleepmode(1);
        genEmuEvent(inputfds[0], type, par1, par2);
```

Generally dis- and enabling suspending does not seem the way to go. Looking at pocketbook-coolreader one normally uses ``SetHardTimer()`` which will wake the PB at a given time and execute a callback without suspending. While callbacks into luacode seems to be [supported](http://luajit.org/ext_ffi_semantics.html) by luajit i don't think its a good idea to use them extensively: 

> Callbacks take up resources — you can only have a limited number of them at the same time (500 - 1000, depending on the architecture). The associated Lua functions are anchored to prevent garbage collection, too.
> Callbacks due to implicit conversions are permanent! There is no way to guess their lifetime, since the C side might store the function pointer for later use (typical for GUI toolkits). 

...and i would need to callback everything before ``onReaderReady()``.

**Comment by Frenzie** [comment]
Thank you for investigating. I'm afraid I don't have anything worthwhile to contribute. Could this be of any use? https://code.google.com/archive/p/libinkviewdoc/source/default/source

**Comment by mk-f** [comment]
I am afraid  that this needs changes to ``koreader-base/input`` as i need a way to inject (custom) events into the libinkview-handler. This is because many of the ``libinkview-iv*`` functions will just work if called from within this handler. What do you think of something like [this](https://github.com/koreader/koreader-base/compare/koreader:b462060...mk-f:2f5b54e)?

**Comment by Frenzie** [comment]
No objections; also pinging @chrox and @houqp

**Comment by mk-f** [comment]
At the moment, i experimentally use it like [this](https://github.com/mk-f/koreader/blob/3192e482ec1e6cb57ed142e1aa9a7c3862656a53/plugins/00-pbinsomnia.koplugin/main.lua). For some reason the ``onShow*``-events never fire for now, put this will be another story.
