### ISSUE TITLE
Remove news downloader files from Koreader history?

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3422]
* KOReader version: git
* Device: all

#### Issue
Remove news downloader files from Koreader history.

As News Downloader download mostly single, small html file which is read in  (at most) couple minutes and most of the cases (if not all) there's no sense of adding it to the reading history.

Is there a way to avoid adding it to read books history?
Any ideas?

#### Steps to reproduce
Use News Downloader, download, open news, close it. Open history, it's there.

**Comment by mwoz123** [comment]
I mean - can it be don in N.D. plugin code without affecting main Koreader code?

**Comment by Frenzie** [comment]
Probably. I assume some combination of a `NewsDownloader:onCloseDocument()` (i.e., a handler for the `CloseDocument` event) and `ReadHistory:removeItemByPath(path)` should do the trick.

https://github.com/koreader/koreader/blob/4d18ac11009f774eb059a5e489e7b76cf9d23abc/frontend/readhistory.lua#L148

https://github.com/koreader/koreader/blob/4d18ac11009f774eb059a5e489e7b76cf9d23abc/frontend/readhistory.lua#L158

I think I might like this to be configurable. Manually selected articles in a wallabag newsfeed would be long-form articles. But we can give it a go without configuration and see how it feels.

**Comment by mwoz123** [comment]
But news downloader itself doesn't open the book/file. Just creates file. Is it still possible? 

How about creating some kind of directory "blacklist" that will not be included in history. 
This might be useful is someone would plan to do reading in "private" mode (similar to web browser private mode), without storing history. 
News downloader directory will be then first element. 
If someone's not using N. D. then it will not have any influence on his history. 

IFAIR news downloader download folder is stored using lua settings which mean it should be accessible from rest of the application.

Small disadvantage is that we 'll have n.d directory on this blacklist.

**Comment by Frenzie** [comment]
Just make the function and find out. It takes two seconds. :-P

(The answer is yes, of course. That's the purpose of events.)

**Comment by Frenzie** [comment]
```lua
function NewsDownloader:onCloseDocument()
    -- another few seconds to find out
    local path = self.ui.document._document.filename
    -- do some NewsDownloader if path == whatever stuff here
    ReadHistory:removeItemByPath(path)
end
```
