### ISSUE TITLE
hyphenation in french

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3423]
* KOReader version: all
* Device: gloHD

#### Issue
as in the closed case #3212 about hyphenation in spanish, I also think from reading in french since 5 months that the .pattern I made from the TeX hyph file is way better than the default one. Sometime, I forget to enable it (so the old french pdb is active) and there is no french books I didn't had to switch since I made it work.

Also, the .pattern file is easier to edit than an .pdb file which i never manage to find how to do it cause it's only text and xml tags

[French.pattern.txt](https://github.com/koreader/koreader/files/1414691/French.pattern.txt)
[languages.json.txt](https://github.com/koreader/koreader/files/1414710/languages.json.txt)

**Comment by Frenzie** [comment]
You don't want to make a PR out of it? :-)

You can even do it without using Git purely on the GitHub web interface, though Git is awesome and I recommend getting to know it.

**Comment by poire-z** [comment]
Dunno if you used the same tex source, but it's been done some months ago: https://github.com/koreader/crengine/pull/78

**Comment by Frenzie** [comment]
Whoops, I forgot all about that. I only remembered several language had been updated and I assumed French wasn't one of them. I'll close this then. :-)

**Comment by cramoisi** [comment]
erf, sorry, i took the habit to update everything but this file so i didn't check it before !
Happy it's there !
