### ISSUE TITLE
Integrate koreader with calbre Content server

### ISSUE THREAD

**Issue by jony0008** [koreader/koreader#3427]
Could it be possible to integrate the calibre Content server with koreader and make it possible to browse, search, edit books and read them with the reader in koreader?

**Comment by KenMaltby** [comment]
calibre's Content server provides a local calibre catalog that KOReader's OPDS support lets you browse the calibre library on the machine that calibre is running on.  The catalog provides a number of sorts of the book listing.  By Newest, By Title, By Authors, By Languages, By Publisher, By Rating, By Series, and By Tags.
When you select a book you get a Download box with download options.  Once you have a download directory established and selected the format to download, the book will be added to that directory.  Then you will be offered the option to read it now or later.

I use it all the time.

Luck;
Ken

**Comment by jony0008** [comment]
Thanks for your comment, that is good to know. I am asking for better integration with calibre, how about SSL support, restrictions, metadata editing for the KOReader's OPDS?

**Comment by Frenzie** [comment]
What do you mean by SSL support? luasec has been part of the OPDS browser from its inception in 21dcf787da36a9fb68db9309233020a944b954ae

**Comment by KenMaltby** [comment]
KOReader has several features that work with calibre, in fact it is a little hard to imagine how it could be more "integrated" with calibre.  Or is it calibre's integration with ereaders?  In addition to being able to properly access calibre's "Content server", KOReader has a "calibre companion" type plugin that allows for connecting KOReader equipped devices to be seen in calibre as an attached wireless device.  calibre will see your Kobo device, if connected via USB or wireless and the caliber Kobo "Device interface plugin" is enabled, in calibre Preferences.   Then there has been the KOReader search function for the caliber supplied and maintained "metadata.calibre" file on your device.  calibre itself has the tools to edit the metadata and such editing is normally done prior to sending the file to your device.

**Comment by jony0008** [comment]
I see. I will close this issue now.

**Comment by trungng2006** [comment]
> 
> 
> KOReader has several features that work with calibre, in fact it is a little hard to imagine how it could be more "integrated" with calibre. Or is it calibre's integration with ereaders? In addition to being able to properly access calibre's "Content server", KOReader has a "calibre companion" type plugin that allows for connecting KOReader equipped devices to be seen in calibre as an attached wireless device. calibre will see your Kobo device, if connected via USB or wireless and the caliber Kobo "Device interface plugin" is enabled, in calibre Preferences. Then there has been the KOReader search function for the caliber supplied and maintained "metadata.calibre" file on your device. calibre itself has the tools to edit the metadata and such editing is normally done prior to sending the file to your device.

May I ask does this mean there is a way for user to use content server to highlight sync with calibre?

I am using a jailbreak PW2. And i want my highlight in kindle to be sync with calibre.
If i use a web browser to read book via content server, then i can use calibre highlight. But i am not sure if this is possible with Koreader? (or how to implement?).

**Comment by NiLuJe** [comment]
There are no standard for storing highlights, so, no, not without a significant amount of new code dedicated to this.

**Comment by trungng2006** [comment]
Thank you for your quick response,
I am sorry that my question is not clear, please let me clarify a bit:

When i use my web browser on my phone to read the book via calibre content server, the browser is actually acting as a calibre reader i think.
It have all the calibre reader function. And the highlight is automatically show up in calibre on my computer
![89346](https://user-images.githubusercontent.com/71961905/126688020-b6892fb8-62b0-4f75-9f3c-70d8aae3ba2f.jpg)

May I ask if Koreader have this functionality?
