### ISSUE TITLE
When i updated to  v2015.11-1376-ge8aeb3c,the dictionary not work to search word

### ISSUE THREAD

**Issue by WeihuaGu** [koreader/koreader#3429]
* KOReader version:v2015.11-1376-ge8aeb3c
* Device:kobo touch n905c

#### Issue
When i updated to  v2015.11-1376-ge8aeb3c by ota,the dictionary not work to search word and only to say "no definition found.(query:hello)"
#### Steps to reproduce

![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/koreader1.jpg)
![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/koreader2.jpg)
![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/koreader3.jpg)
![](https://raw.githubusercontent.com/WeihuaGu/asserversource/master/koreader4.jpg)

**Comment by Frenzie** [comment]
This must be a side-effect of https://github.com/koreader/koreader-base/pull/561

Pinging @poire-z.

I'd try that `#ifdef __ANDROID__` I suggested. ;-)

**Comment by poire-z** [comment]
Could be.
1370 & 1373 worked ok?
Does it work if you don't disable one dict (when you have it display `Installed dictionaries (3/3)` instead of `(2/3)` ) ?
Could you tell us the content of the `LANG` and `LC_*` variables when you run in `More plugins / Terminal Emulator` this simple command: `env` ?
And your kobo firmware version?

> I'd try that #ifdef __ANDROID__ I suggested

Feel free to try it (I'm off in a few hours and won't be able to PR and contribute to the investigation till end of next week).

**Comment by WeihuaGu** [comment]
@poire-z Tick all dict item also not work and if remove all dict file,`the installed dictionaries show (-1/0)`.
the env command log that "LANG=en_US.UTF-8 and LC_ALL=en_US.UTF-8" 
Have a good rest ：）

**Comment by Frenzie** [comment]
I've attached all the files in question for convenience. (Though it's only the sdcv executable that matters.)

[koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1370-g5ee6c01.zip](https://github.com/koreader/koreader/files/1417449/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1370-g5ee6c01.zip)
[koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1373-g3639c3e.zip](https://github.com/koreader/koreader/files/1417450/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1373-g3639c3e.zip)
[koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1376-ge8aeb3c.zip](https://github.com/koreader/koreader/files/1417451/koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1376-ge8aeb3c.zip)

**Comment by alex125** [comment]
For me on Kobo v2015.11-1376, dictionary lookup works but only if 'Disable dictionary fuzzy search' is not ticked. Same problem with 1370 on Android. Earlier versions (1276 was the last one I used before upgrading to 1376) worked ok with fuzzy search disabled.

**Comment by Frenzie** [comment]
@alex125 My bad. @chrox added `-f, --non-fuzzy-fallback disable fuzzy fallback in simple query` and I hadn't noticed that the upstream patch was the (probably more logically named) `"\-e \-\-exact\-search" ` in https://github.com/Dushistov/sdcv/pull/26

@WeihuaGu I'll make sure that particular issue will be fixed in tomorrow's nightly. Could you test again then? The nightly is normally generated around 12 hours from now if I'm not mistaken.

**Comment by WeihuaGu** [comment]
@Frenzie Thank you for your work. I will test again and give a feedback.

**Comment by davy39** [comment]
Hi,  I've just installed KSM08, KSM08_ext_aura_one_05b patch and Koreader on my new Kobo Aura One.
However, I had no success with dictionaries : I tried Koreader v1351, 1376 and 1379, tried to restart koreder, reboot... and I still get a "no definition found" message, although my dictionary is detected.
Can I do something specific to help debugging ?

**Comment by Frenzie** [comment]
@davy39 That's presumably #3302. I'm not entirely sure why the nightly build server is creating builds that don't work on Kobo 4.6.9960 and above. Any of the several sdcv binaries I posted [here](https://github.com/koreader/koreader/issues/3302#issuecomment-337700307) should work.

**Comment by davy39** [comment]
It's working now, thanks !
Sorry that I didn't notice #3302 tread.
Many thanks for your good work.

**Comment by WeihuaGu** [comment]
@Frenzie I also didn't notice #3302 tread and my kobo firmware is 4.6.9960……
I updated to version 1379 and replace the sdcv file. Then It works . the dictionary lookup works whatever 'Disable dictionary fuzzy search' is ticked or not. Many thanks to you.

**Comment by Frenzie** [comment]
I hope a Kobo firmware update might resolve the issue in the future. I understand 4.6.9960 has been pulled due to performance reasons or some such? In any case I'll close this issue. :-)
