### ISSUE TITLE
Some CSS weaknesses

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#3432]
* KOReader version: all
* Device:

#### Issue
Using Koreader for quite a long time, I can see that some CSS properties are just ignored and this causes some surprising display glitches. I  am unable to provide a comprehensive study but this is what I regularly find and it would be a good beginning:
 
_text-transform_ property (uppercase, lowercase) not applied
_vertical-align_ property (specially text-top value) not applied
_margin_ property (-top, -bottom, etc.) negative values not supported
_float_ property not appplied

thanks for your attention and for a wonderful reading tool

Roger

**Comment by poire-z** [comment]
Yeah, "simple" as in "crengine" :|

I thought too it would be an easy trip, but once happy with rendering, and trying highlights ("extraordinary", "uppercase") and full text search (for "case"):
<kbd>![image](https://user-images.githubusercontent.com/24273478/42955465-f550436a-8b7d-11e8-854e-779665879b27.png)</kbd>

So more work to do (the DOM is not transformed, and char widths may change when upper/lowercased, so things get shifted).
But no more "simple" :)

**Comment by poire-z** [comment]
> vertical-align property (specially text-top value) not applied

Fixed in https://github.com/koreader/crengine/pull/240.

What's left unsupported are:
> _margin_ property (-top, -bottom, etc.) negative values not supported
> _float_ property not appplied

**Comment by Frenzie** [comment]
I'm surprised to hear that negative margins are used a lot in EPUBs btw.
