### ISSUE TITLE
Is possible to sync the reading progress and highlights between mac and kpw

### ISSUE THREAD

**Issue by zhliu0124** [koreader/koreader#3435]
The reading experience on Kindle with KOReader is almost perfect now. But I'm also reading books, particularly difficult books, on my mac because it allows me to take notes and do background research easily.

I'm not sure if it's technically difficult, but it would be great to be able to sync the reading progress and highlights between these two devices.

**Comment by pazos** [comment]
You can use KO on the mac too (will be available soon)
