### ISSUE TITLE
Crash when try to open Wi-Fi every time (Kobo Aura ONE)

### ISSUE THREAD

**Issue by civalin** [koreader/koreader#3436]
* KOReader version: 3639c3e
* Device: Kobo Aura ONE with KSM 8

#### Issue

Crash when I try to open Wi-Fi connection every time.

#### Steps to reproduce

1. (in main menu) select `network`
2. select `Wi-Fi connection`
3. select `Turn on`
4. display: `scanning ...`
5. show `KOReader exited irregularly` in KSM's UI.

##### `crash.log` (if applicable)

```
wlarm_le: wl driver adapter not found
./luajit: common/lj-wpaclient/wpaclient.lua:118: attempt to compare number with nil
stack traceback:
	common/lj-wpaclient/wpaclient.lua:118: in function 'scanThenGetResults'
	frontend/ui/network/wpa_supplicant.lua:18: in function 'getNetworkList'
	frontend/ui/network/manager.lua:189: in function 'action'
	frontend/ui/uimanager.lua:518: in function '_checkTasks'
	frontend/ui/uimanager.lua:669: in function 'handleInput'
	frontend/ui/uimanager.lua:765: in function 'run'
	./reader.lua:190: in main chunk
	[C]: at 0x00013fc5
```

#### Other Info

1. Wi-Fi work nicely within nickel.
2. I also try to upgrade my firmware to `4.6.9995` but no matter before and after upgrade, the problem still the same.

Any idea? Thanks.

**Comment by civalin** [comment]
More info:

Also reinstall the recent updated file (`KSM08_ext_aura_one_05b.zip`) in this post:
<https://www.mobileread.com/forums/showpost.php?p=3389190&postcount=221>

but nothing changed.

**Comment by Frenzie** [comment]
> I also try to upgrade my firmware to 4.6.9995 but no matter before and after upgrade, the problem still the same.

With third-party mods as a general rule a downgrade is more likely to be effective. ;-)

But does it work in KOReader? KSM is a separate thing. Its support is, well, in its topic.

https://www.mobileread.com/forums/showthread.php?t=266821

**Comment by civalin** [comment]
Thanks your nice info about third-party mods! It's look like some common sense in this domain I never consider before. Great!

By the way, after a short test, I'm sure my aura one can also connect to wifi in KSM correctly. But still not in KOReader.

**Comment by Frenzie** [comment]
Your error message seems to suggest the driver wasn't loaded properly into the kernel but if it works in KSM I have no idea what could be wrong.

Someone might have to investigate with relevant `insmod` commands and such (`insmod /drivers/mmc/card/sdio_wifi_pwr.ko`?) I can't really say without a real device, unfortunately.

I believe @houqp owns a Kobo Aura One.

**Comment by civalin** [comment]
More info coming. Use `More Plugins` -> `Terminal emulator`.

First time run `lsmod` in KOReader:

```
lsmod
8189fs 1158112 0 - Live 0x7f008000
lowmem 905 0 - Live 0x7f000000 (P)
```

Open Wi-Fi in KSM and get into KOReader, make sure I can touch the OTA server (so I'm really online), then run `lsmod` again.

```
lsmod
8189fs 1158112 0 - Live 0x7f194000
sdio_wifi_pwr 486 0 - Live 0x7f190000
lowmem 905 0 - Live 0x7f000000 (P)
```

`modinfo sdio_wifi_pwr` return nothing. I think I should use the `root` to run this command? but not sure how to grant it.

Try to close Wi-Fi -- successful (at least KOReader say it's closed, but not sure really be closed or not).

Try to reopen Wi-Fi -- crash again.

---

I'm not familiar with driver programming. Have anything I missing?

**Comment by Frenzie** [comment]
All that you write suggests it should be working.

https://github.com/koreader/koreader/blob/e8c01274f4d1ef81ebc431ad50a4af9de3000148/platform/kobo/enable-wifi.sh#L5-L7

Btw, you should be able to redirect stderr to stdout by sticking  `2>&1` after the command.

However, I'd say the easiest method to play around with this stuff is USBNet (in the KSM USB menu).

https://github.com/koreader/koreader/pull/3167#issuecomment-326803784

On the downside, the USB connection can result in the device keeping some stuff alive it otherwise wouldn't.

**Comment by civalin** [comment]
## new info update

Use `2>&1` mentioned by @Frenzie, I got some info here. (sadly, USBNet not work due to ssh-server not started. But it's off topic. so just ignore it now...)

```sh
modinfo sdio_wifi_pwr 2>&1
modinfo: can't open '/lib/modules/3.0.35+/modules.dep': No such file or directory
```

```sh
ls -A /lib/modules/3.0.35+
modules.dep.bb           # size of file is 0
```

Not sure above results normal or not.

In the other hand, I'm try to find which files be used (reference: `koreader/platform/kobo/enable-wifi.sh`). So print some env variables:

```sh
echo $PLATFORM
mx6sl-ntx
```

```sh
echo $WIFI_MODULE
8189fs
```

```sh
echo $WIFI_MODULE_PATH
/drivers/mx6sl-ntx/wifi/8189fs.ko
```

Check files exists:

```sh
ls -A /drivers/$PLATFORM
misc
usb
wifi
```

```sh
ls -A /drivers/$PLATFORM/wifi
8189fs.ko
dhd.ko
sdio_wifi_pwr.ko
```

Try `insmod` manually:

```sh
lsmod  # print nothing
```

```sh
insmod /drivers/$PLATFORM/wifi/sdio_wifi_pwr.ko # print nothing
insmod $WIFI_MODULE_PATH # print nothing
```

```sh
lsmod
8189fs 1158112 0 - Live 0x7f004000
sdio_wifi_pwr 486 0 - Live 0x7f000000
```

As expected! next try `ifconfig`

```sh
ifconfig  # print nothing
ifconfig 2>&1  # print nothing
```

```sh
ifconfig eth0 up  # print nothing
```

```sh
ifconfig
eth0      Link encap:Ethernet  HWaddr 58:B0:D4:30:3F:62  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

Try ifconfig

```sh
wlarm_le -i eth0 up 2>&1
wlarm_le: wl driver adapter not found
```

I don't know what the `wlarm_le` is it and how to test it.

Any suggestions?

**Comment by Frenzie** [comment]
Have you tried increasing sleep? KSM does `sleep 2`.

```bash
lsmod | grep -q sdio_wifi_pwr || insmod /drivers/$PLATFORM/wifi/sdio_wifi_pwr.ko
lsmod | grep -q ${WIFI_MODULE} || insmod /drivers/$PLATFORM/wifi/${WIFI_MODULE}.ko

sleep 2
ifconfig eth0 up
wlarm_le -i eth0 up
```

In contrast to our `sleep 1`.

https://github.com/koreader/koreader/blob/e8c01274f4d1ef81ebc431ad50a4af9de3000148/platform/kobo/enable-wifi.sh#L5-L11

**Comment by civalin** [comment]
OK, I think I almost figure out what's happen.

Check this file:

https://github.com/koreader/lj-wpaclient/blob/9c031ec4e685d4c9b18ad36cdb1dd8f398f0c13d/wpaclient.lua#L99-L125

KOReader crash when the `re_str` in line `101` are look like this:

```
OK
bssid / frequency / signal level / flags / ssid
c6:e9:84:64:28:b7	2437	100	[WPA2-PSK-CCMP][ESS]	bgap
c4:e9:84:66:28:b7	2437	100	[WPA2-PSK-CCMP][WPS][ESS]	bigap
c4:e9:84:46:34:c4	2437	60	[WPA-PSK-CCMP][WPA2-PSK-CCMP][ESS]	smallap
```

But connect to network peacefully when it look like this:

(it's usually happen when I already crash then do do not `remod` wifi related module and maybe `wpa_supplicant` also keep working in KSM, and re-enter the KOReader again)

```
bssid / frequency / signal level / flags / ssid
c4:e9:84:66:28:b7	2437	100	[WPA2-PSK-CCMP][WPS][ESS]	bigap
c6:e9:84:64:28:b7	2437	100	[WPA2-PSK-CCMP][ESS]	bgap
c4:e9:84:46:34:c4	2437	56	[WPA-PSK-CCMP][WPA2-PSK-CCMP][ESS]	smallap
```

And `wpaclient.lua` not prune the line contain `OK`.

So I rewrite it as follow:

```lua
function WpaClient.__index:getScanResults()
    local results = {}
    local re_str, err = self:sendCmd('SCAN_RESULTS', true)
    if err then return nil, err end

    local lst = str_split(re_str, '\n')
    for _,v in ipairs(lst) do
        local splits = str_split(v, '\t')

        if splits[5] then  -- remove lines which cannot split into 5 parts
            local network = {
                bssid = splits[1],
                frequency = tonumber(splits[2]),
                signal_level = tonumber(splits[3]),
                flags = splits[4],
                ssid = splits[5],
            }
            -- Old version of wpa_supplicant reports signal level in dBm, we
            -- need to restrict it to range of [-192, 63] to keep it consistent
            -- with new version.
            -- ref: http://readlist.com/lists/shmoo.com/hostap/1/6589.html
            if network.signal_level > 63 then
                network.signal_level = network.signal_level - 0x100
            end
            setmetatable(network, network_mt)
            table.insert(results, network)
        end
    end
    return results
end
```

Now it working.

I don't known where the `OK` come from. Maybe it generated by `wpa_supplicant` start event?

**Comment by civalin** [comment]
Pull Request is ready in here, hope somebody can help to merge it:

https://github.com/koreader/lj-wpaclient/pull/3

**Comment by Frenzie** [comment]
Thanks! I'll merge it. :-)

**Comment by civalin** [comment]
Great thanks for all your help :D
