### ISSUE TITLE
dictionary lookup without fuzzy search

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#3440]
* KOReader version: v2015..11-1379
* Device: Kobo

#### Issue
If fuzzy search is disabled, words starting with capital letter at the beginning of a sentence are not found. This behavior used to be different in version 1256: with fuzzy search disabled words with capital first letter (and words with plural s) were still found. (Fuzzy search is a bit slower and sometimes finds a lot of similar but totally unrelated words so I prefer to switch it off).

**Comment by Frenzie** [comment]
Pinging @ecraven.

**Comment by alex125** [comment]
found a workaround:
replace `.adds/koreader/sdcv` with the one from version 1256
in `.adds/koreader/frontend/apps/reader/modules/readerdictionary.lua ` change
    local common_options = self.disable_fuzzy_search and "-nje" or "-nj"
    local common_options = self.disable_fuzzy_search and "-njf" or "-nj"

**Comment by alex125** [comment]
`.adds/koreader/frontend/apps/reader/modules/readerdictionary.lua `
has been re-organized with the latest update (the one that enables href links in html dictionaries).
Can't find the `-nje` that needs to be changed to `-njf` in order to work with the old sdcv from version 1256.
Could anyone point me to the file and line where I need to make the change?
Thanks.

**Comment by poire-z** [comment]
It was changed to use individual options in a list, and it uses the long option for fuzzy search:
https://github.com/koreader/koreader/blob/a66d657195b1ed284d89df65cd4c1fe6b35ce47e/frontend/apps/reader/modules/readerdictionary.lua#L530-L532
```
Application Options:
  -e, --exact-search             do not fuzzy-search
```

**Comment by alex125** [comment]
Thanks, changed it to "-f" and everything works again the way I prefer it

**Comment by NiLuJe** [comment]
Upstream issue, AFAICT?
