### ISSUE TITLE
Android: copy selected word to clipboard

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#3441]
* KOReader version:
* Device:

#### Issue
Any chance we could have an option (at the bottom of the dictionary lookup window) to copy the word to the clipboard or directly call an external dictionary app (ColorDict interface seems the one most used by Android ereader apps, the ColorDict interface also works with GoldenDict, Fora Dictionary and BlueDict). This way, dictionaries with nice formatting could be used with koreader. Another useful feature on Android would be an option for the existing Wikipedia button to call the app Aard2 (for offline wikipedia).

**Comment by mwoz123** [comment]
I would also add here ability to copy/paste from clipboard to our text area (e.g. comments area in book review).
Then I could use it in news downloader.

**Comment by gerroon** [comment]
It would be nice if the selected word can be shared to other apps (like in usual android way of doing it)

thanks

**Comment by mwoz123** [comment]
I could implement the android interface part if anyone else had implemented the lua part?

Android example for different versions :
https://stackoverflow.com/a/11012443

Would be good if we had that also for other koreader devices.. 
Then we don't have to check if it's handled by current device/write code only for particular device. 

BTW @Frenzie is there a way create to kind of util to check if device has required property /function e.g:
`device.hasProperty('clipboard')` or `device.canHandle('wifiOn')` or something similar instead ugly listing all devices that are handled ( `if Device.isAndroid() or Device.isKobo() or ...`) 
Is it possible in lua? 

This way we could implement main code and I won't require changes in that code when another device would get the same interface in some time. (without this) The most problematic for me seems to be that in some time the Developer might overlook some places where he needs to add check for this new device. (I already had such situation)

**Comment by Frenzie** [comment]
@mwoz123 I don't understand the question. There is no conceptual difference between `Device:isAndroid()` and `Device:whateverYouWant()`. If something specific is needed, implement it or ask for it.

In generic device, stick `hasClipboard = no` and a couple of methods named something like `getClipBoardText` and `setClipBoardText`. In Android, put `hasClipboard = yes` and do something useful with it.

**Comment by Frenzie** [comment]
@mwoz123 That being said, my main concern is presentation.

**Comment by Frenzie** [comment]
@mwoz123 
How about auto-copy selection to clipboard for starters? It'd be a lot easier to add. I can add a stub backend + SDL implementation, you'd add the Android implementation.

**Comment by mwoz123** [comment]
>There is no conceptual difference between Device:isAndroid() and Device:whateverYouWant()

Example: let's say we're writting a new feature that currently works for Android, Kobo & Pocketbook.
Let's say this `if Device:isAndroid() or Device:isKobo() or Device:isPocketbook (..)` has to be checked couple times in code in different lua files. 

In some time we want to add it code for Kindle.
We'll have to change it all over the places, so here this `Device:whateverYouWant()` is much better.
Even if it was just one device (`if Device:isKobo`) and used couple times is much better. 
It seems ok as long we have only few `Device:whateverYouWant()` ...
If we had more `Device:hasFeature('frontlight')` might be better..


> @mwoz123
How about auto-copy selection to clipboard for starters? It'd be a lot easier to add. I can add a stub backend + SDL implementation, you'd add the Android implementation.

Ok.

**Comment by Frenzie** [comment]
I'm not saying you should write `isAndroid or isKobo or isKindle`. That's obviously stupid. :-P

But you were asking if there's a way when there obviously is, so I wasn't really sure what you were asking. I don't immediately see a reason to think that `Device:hasFeature("frontlight")` is any better or worse than `Device:hasFrontlight()`, `Device:has("frontlight")` or `Device.has.frontlight` or something else of equal functionality. It's just that one of them happens to be the current method. I'll ping @houqp for a second opinion.

PS Of course it's not actually `whateverYouWant()`, but `hasFeatureName()` for this particular use case.

Regarding copying, do you have any comments on <https://github.com/koreader/koreader/pull/3465>? I intend for `hasClipboardText`, `getClipboardText` and `setClipboardText` to be the methods used in the Lua frontend.

**Comment by Frenzie** [comment]
This will automatically start working in tomorrow's nightly. Presently the only related feature available is the one I added a few months ago in https://github.com/koreader/koreader/pull/3465. After selecting a few words, you can choose to copy it.

![screenshot_2018-02-16_21-45-46](https://user-images.githubusercontent.com/202757/36328560-d64b3e86-1362-11e8-9f26-38210616d3b7.png)

**Comment by mwoz123** [comment]
Is there also a paste feature? or it will be added next time?

**Comment by Frenzie** [comment]
That was all I added back in November. Almost just a little API demo. I don't immediately see an easy way to introduce paste but it would be a nice to have. I don't think @robert00s can be coaxed into it until I write a little Lua clipboard for Kobo platforms without a native clipboard. :-P
