### ISSUE TITLE
dictionary 'no definition found'

### ISSUE THREAD

**Issue by seanexplode** [koreader/koreader#3446]
* KOReader version: koreader-nightly-20171004
* Device: kobo aura one

#### Issue
The dictionary doesn't work. 

It used to work. 

However, after partial update, whenever I highlight a word in pdf files 'no definition found' is shown.

My kobo software version is 4.6.9995

And I use three dictionaries.

Two of them are 'oxford advanced learner's Dictionary' and 'Longman Dictionary of Contemporary English' from [here](http://stardict.rrr.rs/dict.org/index.html)

The other is 'GNU Collaborative International Dictionary of English' from [here](https://tuxor1337.github.io/firedict/dictionaries.html)

Thanks in advance!

**Comment by Frenzie** [comment]
Duplicate of #3302.
