### ISSUE TITLE
Enable hyphenate when publisher block it

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3448]
* KOReader version: all
* Device: All

#### Issue
Is there any way to enable hyphenate when a publisher uses something like that:

```
body{
	adobe-hyphenate: none;
	-epub-hyphens: none;
	font-family: LiberationSerif, serif;
	hyphens: none;
	line-height: inherit;
	margin: 8px 10px 8px 10px;
	text-align: justify;
	-webkit-hyphens: none;
}

```
I don't want disable embedded style.

Add in ./data/epub.css somethink like that doesn't work :(

```
body { 
	text-indent: 0px; 
	margin: 0; 
	text-align: justify;
	adobe-hyphenate: auto;
	-epub-hyphens: auto;
	hyphens: auto;
	line-height: inherit;
	-webkit-hyphens: auto;
} 

```

**Comment by Frenzie** [comment]
Amazing, that proprietary adobe property is actually in the source: https://github.com/koreader/crengine/blob/64893eb835b986654e1ac82a299f5475f3d88818/crengine/src/lvstsheet.cpp#L104

Right, sorry. Have you tried `!important`? `hyphens: auto !important;` etc.

**Comment by robert00s** [comment]
Yes, I tired `!important` and no change. I'm pretty sure that crengine doesn't support `!important` :(

**Comment by Frenzie** [comment]
Does it support higher specificity?

```css
html body {props}
html > body {props}

**Comment by robert00s** [comment]
Something like that works:
```
* { 
	margin: 0; 
	text-align: justify;
	adobe-hyphenate: auto;
	-epub-hyphens: auto;
	hyphens: auto;
	-webkit-hyphens: auto;
} 
```
but it applies for all styles.

I'll try later

```
body * { 
	margin: 0; 
	text-align: justify;
	adobe-hyphenate: auto;
	-epub-hyphens: auto;
	hyphens: auto;
	-webkit-hyphens: auto;
}
```

**Comment by robert00s** [comment]
Unfortunately `body * {}` doesn't work.

**Comment by a-kohout** [comment]
Unfortunately crengine's CSS support is badly broken; it neither supports specificity #2841 nor !important #1430.
The book CSS gets applied after epub.css, hence what you've tried is not working.
Even super basic specificity is broken, e.g.:
```
p.text {
  font-size: 4em;
}

p {
  font-size: 1em;
}
```
`<p class="text">Test</p>`
This should render a small text. In KOReader this renders big.

**Comment by robert00s** [comment]
Thanks @a-kohout 
Unfortunately, we have a lot of css bugs. I can help, but I'm not an expert of crengine and c++.

**Comment by robert00s** [comment]
@poire-z 
Now it's work perfect. 
Many thanks. Great work :)
