### ISSUE TITLE
Book info cache management: question about cleanup of removed files

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3451]
* KOReader version: v2015.11-1373-g3639c3e
* Device: KA1

Hi!
Just wanna know if I've understood this correctly.

Are two steps needed to delete cached information of removed books?: 

1. First "Prune cache of removed books"
2. And then "Compact cache database"

If so: what are "Prune" and "Compact" actually doing, why not just one step (or even better, automatically when you delete the book)?

**Comment by Frenzie** [comment]
These are two different actions relating to the CoverBrowser plugin.

1. Prune deletes them.
2. Compact recreates the database. Through normal additions, deletions, etc. the database file can become fragmented with empty spaces and (much?) larger than it needs to be. No deletion takes place. I don't think the size should normally matter too much, but fragmentation can start to affect performance after a while.

> or even better, automatically when you delete the book

That might need a couple core changes if we keep the CoverBrowser as plugin model. But something like an `onDeleteFile` event might not be a bad idea regardless.

**Comment by gerhaher** [comment]
Ok, thanks for your answer.

The reason I asked is that I've noticed that "Current cache size" doesn't change its value when you just "Prune".

**Comment by Frenzie** [comment]
Right, I don't know about the SQLite internals but I imagine it's not unlike a filesystem, where "deleting" a file just means you delete the reference to it. The actual data is still there until it's overwritten by something else.

**Comment by poire-z** [comment]
(Sorry for the delay in answering.)
Detailed technical answer, for reference:

SQLite manages a single binary file, that is grown as entries are added.
When you delete a book (from KOreader or thru USB mounted device), nothing is done on the coverbrowser side: its entry stays in the database.
When you rename a book or directory, the old entries (referencing no more existing files) are kept, and new ones are created as you browse the renamed books.

So, there are indeed 2 actions related to db management:

- **Prune cache of removed books**: this will check, for each entry in the database, if the file still exists. If not, the entry is deleted (sql's DELETE) from the database: this make the space (in the binary file) used previously by this entry, available for future new entries (sql's INSERT).
I don't know what strategy SQLite uses to search for and re-use these holes (as it may be costly to scan all of them to see if a new entry would fit in the available space), so these holes may or may not be re-used. This binary file could eventually be quite fragmented, with lots of un-reusable small holes. Also, if you delete a bunch of books and are not adding some new ones anytime soon, you'll stay with a big file with some unused big holes.
So, this does never reduce file size: it just marks some space in the file as re-usable.

- **Compact cache database**: this uses SQLite's VACUUM command. What it does is that it create a new temporary empty binary file, and writes to it all (existing) entries - and at the end, it replaces the original database file with this temporary one. You then get a totally unfragmented database binary file, that is most of the time smaller than the original one. This operation is costly (in time and memory usage, as the temporary file is stored in memory), so it's a second optional step: not really worth for occasional delete, but useful when you decide to rename/reorganize your library hierarchy.

**Comment by poire-z** [comment]
Question answered
