### ISSUE TITLE
Doesnt work on Pocketbook 626 Lux 3

### ISSUE THREAD

**Issue by andruha40** [koreader/koreader#3452]
* KOReader version:v2015.11-1390-g456e31a/ 
* Device:Pocketbook 626 Lux 3

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Could you please try to find the crash.log if possible?

Pinging @mk-f.

**Comment by NicolasPetton** [comment]
Here you go:

```
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 10/31/17-14:11:05

10/31/17-14:11:05 INFO  SoftwareVersion:  T626.5.14.828
./luajit: frontend/device/pocketbook/device.lua:176: unrecognized PocketBook model PocketBook 626
stack traceback:
	[C]: in function 'error'
	frontend/device/pocketbook/device.lua:176: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:38: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/centercontainer.lua:5: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:2: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/confirmbox.lua:21: in main chunk
	[C]: in function 'require'
	./reader.lua:91: in main chunk
	[C]: at 0x0000c051
---------------------------------------------
```

**Comment by mk-f** [comment]
I am busy this week, I'll look into it at the weekend. Until then you can try and modify ``frontend/device/pocketbook/device.lua`` by yourself: Add 
```
 elseif codename == "PocketBook 626" then
    return PocketBook631
```
beneath [Line 172](https://github.com/koreader/koreader/blob/178555180f437715c4fb0f5b356a6ed3c1d45a2b/frontend/device/pocketbook/device.lua#L172)

**Comment by andruha40** [comment]
No changes after your advice^(



1 листопада 2017, 21:58:41, від "Fabian Müller-Knapp" <notifications@github.com>:


I am busy this week, I'll look into it at the weekend. Until then you can try and modify frontend/device/pocketbook/device.lua by yourself: Add
elseif codename == "PocketBook 626" then
    return PocketBook631
beneath Line 172

**Comment by Frenzie** [comment]
No changes? it should at least do something other than `unrecognized PocketBook model PocketBook 626`.

**Comment by andruha40** [comment]
Nothing like this....crashes when starting



1 листопада 2017, 22:53:06, від "Frans de Jonge" <notifications@github.com>:


No changes? it should at least do something other than unrecognized PocketBook model PocketBook 626.

**Comment by Frenzie** [comment]
So what's in the crash.log? :-)

**Comment by andruha40** [comment]
2 листопада 2017, 09:44:59, від "Frans de Jonge" <notifications@github.com>:


So what's in the crash.log? :-)

**Comment by andruha40** [comment]
https://mail.ukr.net/attach/get/15096114423355161523/1/crash.log

**Comment by Frenzie** [comment]
Unfortunately that link gives me "authorization failed, you will be redirected." But you can upload it straight to the reply box here! ;-)

**Comment by andruha40** [comment]
2 листопада 2017, 16:59:30, від "Frans de Jonge" <notifications@github.com>:


Unfortunately that link gives me "authorization failed, you will be redirected." But you can upload it straight to the reply box here! ;-)

**Comment by andruha40** [comment]
[crash.log](https://github.com/koreader/koreader/files/1439137/crash.log)

**Comment by Frenzie** [comment]
It looks like you performed an OTA update? The potentially relevant stuff seems to start at line 181 and stop at 342.

**Comment by andruha40** [comment]
I tried to update through wifi but no sucess so I updated it manually to the last version

**Comment by andruha40** [comment]
v2015.11-1358-ge0bc0a1/ works perfect no crashes look please the changes you have done in there!!!

**Comment by Frenzie** [comment]
That would be this: e0bc0a1...456e31a (or in other words, #3402 and #3403)

But since you were able to OTA update with the suggested edit, what action is it that causes the crash exactly?

**Comment by andruha40** [comment]
But since you were able to OTA update with the suggested edit, what action is it that causes the crash exactly?
What do you mean by this?


3 листопада 2017, 22:01:56, від "Frans de Jonge" <notifications@github.com>:


That would be this: e0bc0a1...456e31a (or in other words, #3402 and #3403)
But since you were able to OTA update with the suggested edit, what action is it that causes the crash exactly?

**Comment by Frenzie** [comment]
It looks like you didn't get crashes with the suggested edit in place?

**Comment by andruha40** [comment]
No it was crashed it just bleams turns black and go out to the main menu

Ill try to send a new log later, now I use version 58 that works perfect


4 листопада 2017, 10:49:32, від "Frans de Jonge" <notifications@github.com>:


It looks like you didn't get crashes with the suggested edit in place?

**Comment by farvardin** [comment]
Same for me, the latest Released version which works on my PocketBook 626 is koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1287-g5a2c8e4 (and the latest DailyBuild doesn't work either)

Other later versions just do nothing when launching them.
