### ISSUE TITLE
PocketBook 631 (Touch HD) - WiFi won't auto connect.

### ISSUE THREAD

**Issue by iamjustaguest** [koreader/koreader#3458]
* KOReader version: v2015.11-1393-gdbd9348
* Device: PocketBook 631 (Touch HD)

#### Issue
WiFi won't auto connect.

Tested on OTA update.
Info dialog comes up to turn on wifi.
Confirming turn on, but wifi don't connect.

It seems the Touch HD needs other arguments to enable wifi.
I found a owncloud script for the Touch HD [this](https://www.e-reader-forum.de/ebook-reader/pocketbook/27169-own-cloud-webdav-synchronisation-fuer-pb-touch-hd/) forum that contains other arguments.

[owncloud.app.txt](https://github.com/koreader/koreader/files/1434107/owncloud.app.txt)

I tried on terminal and tested the new arguments in device.lua, line 49.

os.execute("/ebrmain/bin/netagent " .. (toggle == 1 and "net on" or "net off"))

This works so far, wifi comes up. This might not work with other pocketbooks.

However, OTA Update doesn't continue, no info comes up if updates or not.
This works with manually enabled wifi.

**Comment by andruha40** [comment]
The same problem on PocketBook 626 Lux 3

**Comment by aceofknaves** [comment]
Same problem exists on PocketBook 632 Touch HD3. Running the latest version: v2019.04 with the latest  fw: U632.5.19.832.

Is there a known workaround for this? I'm currently not able to use wifi from the app.

**Comment by Frenzie** [comment]
Is this related to #4747?

**Comment by Termuellinator** [comment]
I can confirm that this still happens on Touch HD3 with Firmware U632.6.4.466 and KOreader 2021.08-81.
I also can confirm that it doesn't happen when switching the device on, but only after sleep mode (through softcover) - so to me it sounds like it indeed is the same issue as in https://github.com/koreader/koreader/issues/4747

**Comment by rjd22** [comment]
This should be fixed this latest release. Can someone check if this is still an issue for this device?

**Comment by Termuellinator** [comment]
It seems with 2022.02, wifi can be successfully activated through koreader, even after softcover-sleep. At least from what i can tell from my short test that is.
Thank you! :+1:

**Comment by rjd22** [comment]
Thank you for testing 👍
