### ISSUE TITLE
Can't open ebook from html file

### ISSUE THREAD

**Issue by ProgramMaster** [koreader/koreader#3461]
* KOReader version: v2015.11-1287-g5a2c8e4
* Device: Kobo Reader Touch

#### Issue
Can't open ebook (any format) and images by link from HTML file.

#### Steps to reproduce
I want to make a catalog of Books.
I created HTML file where there are descriptions, images and links to other eBooks (epub,pdf), docs (txt, html), images (png, jpg).

When I try to open any links I see the message:
"Invalid or external link ..."

When or how i will have open external links (books, images) from html file.

Do you plan to make the ability to open external links (books, images) from a HTML file?

**Comment by Frenzie** [comment]
Could you provide a minimal test case? Some kind of basic local link following is probably relatively simple to add.

https://github.com/koreader/koreader/blob/f5a6e32887e3312d56ef6aea98a5a6a761e991d3/frontend/apps/reader/modules/readerlink.lua#L216-L231

**Comment by ProgramMaster** [comment]
How correctly open an external ebook file?
