### ISSUE TITLE
Build Koreader on MacOS failed

### ISSUE THREAD

**Issue by zhliu0124** [koreader/koreader#3464]
I would like to build the read on my mac but I encountered this error. Sorry I don't have any experience on it. Could you please tell me what kind of things I can try? Thanks!

OS X El Capitan

```
make[4]: *** [openssl-prefix/src/openssl-stamp/openssl-build] Error 2
make[3]: *** [CMakeFiles/openssl.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [/Users/User/koreader/base/thirdparty/openssl/build/x86_64-apple-darwin15.6.0/openssl-prefix/src/openssl/libssl.so] Error 2
make: *** [all] Error 2
Failed to build emulator! Try run with -v for more information.
```

**Comment by a-kohout** [comment]
The build process currently does not work on macOS.
See #2651

**Comment by Frenzie** [comment]
@zhliu0124 Looks like your base doesn't include https://github.com/koreader/koreader-base/pull/545

Assuming your koreader repo is up to date, update your submodules using `git submodule --recursive`.

@a-kohout 
https://github.com/koreader/koreader-base/pull/571#discussion_r148962070
> Btw, this PR is developed solely on my Mac. Koreader is stable enough on Mac OSX now for development purpose. :)

**Comment by zhliu0124** [comment]
@chrox @Frenzie 
Thank you so much, guys! 
I successfully built KOReader on my mac, but I got these errors while I was trying to run it:

```
users-MacBook-Pro:koreader user$ ./kodev run

[*] Building KOReader…
************ Building for MACHINE: "x86_64-apple-darwin15.6.0-debug" **********
************ PATH: "/opt/local/bin:/Users/user/anaconda/bin:/usr/local/opt/qt/bin:/Users/user/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" **********
************ CHOST: "" **********
/Library/Developer/CommandLineTools/usr/bin/make -C base
************ Building for MACHINE: "x86_64-apple-darwin15.6.0-debug" **********
************ PATH: "/opt/local/bin:/Users/user/anaconda/bin:/usr/local/opt/qt/bin:/Users/user/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" **********
************ CHOST: "" **********
gcc -L/Users/user/koreader/base/build/x86_64-apple-darwin15.6.0-debug/libs -Og -g -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC -I/Users/user/koreader/base/thirdparty/luajit/build/x86_64-apple-darwin15.6.0-debug/luajit-prefix/src/luajit/src -shared -dynamiclib -undefined dynamic_lookup -o build/x86_64-apple-darwin15.6.0-debug/libs/libblitbuffer.so blitbuffer.c
error: invalid integral value 'g' in '-Og'
error: invalid integral value 'g' in '-Og'
make[1]: *** [build/x86_64-apple-darwin15.6.0-debug/libs/libblitbuffer.so] Error 1
make: *** [all] Error 2
Failed to build emulator! Try run with -v for more information.
```

**Comment by Frenzie** [comment]
Could you show me the output of `gcc --version`? Like the README says, "Your GCC should be at least version 4.8."

That being said, you should be able to get a working build by removing that flag from [here](https://github.com/koreader/koreader-base/blob/9347a6523bce1d233dee84e70bf5282f17af901a/Makefile.defs#L154) provided you have at least GCC 4.7.

**Comment by zhliu0124** [comment]
@Frenzie 
I really appreciate your help and I'm sorry that I'm keeping bugging you. I have not much experience about these thing...

I had the default gcc 4.2.1 on my mac. I replaced it with gcc 7.2 and it went through, but I got some new errors: 

```
user@users-mbp:~/koreader$ ./kodev run
[*] Building KOReader…
************ Building for MACHINE: "x86_64-apple-darwin15.6.0-debug" **********
************ PATH: "/usr/local/bin:/opt/local/bin:/Users/user/anaconda/bin:/usr/local/opt/qt/bin:/Users/user/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" **********
************ CHOST: "" **********
/Library/Developer/CommandLineTools/usr/bin/make -C base
************ Building for MACHINE: "x86_64-apple-darwin15.6.0-debug" **********
************ PATH: "/usr/local/bin:/opt/local/bin:/Users/user/anaconda/bin:/usr/local/opt/qt/bin:/Users/user/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" **********
************ CHOST: "" **********
install -d thirdparty/djvulibre/build/x86_64-apple-darwin15.6.0-debug
cd thirdparty/djvulibre/build/x86_64-apple-darwin15.6.0-debug && \
		cmake -DCC="gcc" -DCXX="g++" -DCFLAGS="-Og -g -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC" \
		-DCXXFLAGS="-Og -g -ffast-math -pipe -fomit-frame-pointer  -march=native -fPIC" -DLDFLAGS="" \
		-DLIBS="" \
		-DCHOST="" \
		/Users/user/koreader/base/thirdparty/djvulibre && \
		/Library/Developer/CommandLineTools/usr/bin/make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/user/koreader/base/thirdparty/djvulibre/build/x86_64-apple-darwin15.6.0-debug
[ 12%] Performing build step for 'djvulibre'
Making all in libdjvu
Making all in tools
  CXXLD    c44
  CXXLD    bzz
  CXXLD    cjb2
  CXXLD    cpaldjvu
  CXXLD    csepdjvu
clang: error: no such file or directory: '../libdjvu/.libs/libdjvulibre.dylib'
make[7]: *** [c44] Error 1
make[7]: *** Waiting for unfinished jobs....
clang: error: no such file or directory: '../libdjvu/.libs/libdjvulibre.dylib'
make[7]: *** [bzz] Error 1
clang: error: no such file or directory: '../libdjvu/.libs/libdjvulibre.dylib'
clang: error: no such file or directory: '../libdjvu/.libs/libdjvulibre.dylib'
make[7]: *** [cpaldjvu] Error 1
make[7]: *** [cjb2] Error 1
clang: error: no such file or directory: '../libdjvu/.libs/libdjvulibre.dylib'
make[7]: *** [csepdjvu] Error 1
make[6]: *** [all-recursive] Error 1
make[5]: *** [all] Error 2
make[4]: *** [djvulibre-prefix/src/djvulibre-stamp/djvulibre-build] Error 2
make[3]: *** [CMakeFiles/djvulibre.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build/x86_64-apple-darwin15.6.0-debug/libs/libdjvulibre.21.dylib] Error 2
make: *** [all] Error 2
Failed to build emulator! Try run with -v for more information.
```

**Comment by Frenzie** [comment]
> I had the default gcc 4.2.1 on my mac.

The default is ten years old? Odd.

It's unclear to me what the problem could be there. Did you clean before rebuilding? What files do exist?

**Comment by a-kohout** [comment]
Apple hasn’t shipped gcc since 2012 or so.
The `gcc` command actually invokes clang, the version string 4.2.1 are the header files it uses.
Since Apple won’t ship anything GPLv3 licensed, these are the newest they can use.

@zhliu0124
Since your output shows clang you’re not actually using gcc 7.2.
Homebrew won’t touch the existing gcc binary and installs it as `gcc-7`
You’d probably have to edit makefile stuff for the build process to use gcc.
But with the recent changes the emulator builds just fine with clang. I’m on 10.13 though.

@frenzie
This is the output of `gcc —version` on macOS 10.13
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
10.12 uses the same version.
10.11 uses `clang-800.0.42.1`

**Comment by chrox** [comment]
How about the xcode command line tool installed by `xcode-select --install`? It's theright way to setup a building env on Mac.

**Comment by a-kohout** [comment]
The command line tools were installed that way

**Comment by Frenzie** [comment]
@a-kohout 

> The gcc command actually invokes clang

In what way is it different from `CC=clang CXX=clang++`, if any?

> Since your output shows clang you’re not actually using gcc 7.2.

Yes, but that doesn't explain anything. `libdjvulibre.dylib` should be a symlink to `libdjvulibre.21.dylib` I imagine, and clang vs gcc doesn't change that.

> But with the recent changes the emulator builds just fine with clang.

It has built just fine with clang for years, actually. :-)

**Comment by a-kohout** [comment]
> In what way is it different from CC=clang CXX=clang++, if any?

Not sure

> Yes, but that doesn't explain anything. libdjvulibre.dylib should be a symlink to libdjvulibre.21.dylib I imagine, and clang vs gcc doesn't change that.

True, I merely wanted to point out that OP wasn't using the compiler they thought they were

> It has built just fine with clang for years, actually. :-)

I wouldn't have known as the build process was broken on 10.12 and 10.13

**Comment by Frenzie** [comment]
I didn't say it built on Mac OS. :-P But, and please don't quote me on this, I'm reasonably sure I've test-built it using Clang 3.0, 3.5 and 3.8. On Linux of course.

**Comment by zhliu0124** [comment]
I changed the `gcc` and `g++` lines in koreader/base/Makefile.defs
```
# unknown device
ifdef SBOX_UNAME_MACHINE
    CC:=gcc-7
    CXX:=g++-7
endif
```
```
    HOSTCC:=gcc-7
    HOSTCXX:=g++-7
```
and now I went further and got these errors:
```
[*] Running KOReader with arguments: ...
~/koreader/koreader-emulator-x86_64-apple-darwin15.6.0-debug/koreader ~/koreader
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 [*] Current time: 11/13/17-22:39:24

PANIC: unprotected error in call to Lua API (cannot open ./defaults.persistent.lua: No such file or directory)
~/koreader
```
It seems all because that the env has not been set correctly on my mac...
