### ISSUE TITLE
[Question] Close widget after tap

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3466]
Is there any way to close widget only after tap on screen?

I want to close screensaver only after tap on screen (as option of course)

https://github.com/koreader/koreader/blob/0def54716218730c4a8dbdab4da088cd70afd9de/frontend/ui/screensaver.lua#L145-L149

Any tip?

**Comment by Frenzie** [comment]
Well sure, just look at InfoMessage (also the fallback for the screensaver) which defaults to that behavior.

https://github.com/koreader/koreader/blob/0def54716218730c4a8dbdab4da088cd70afd9de/frontend/ui/widget/infomessage.lua#L63-L80

But this seems like a bit of an odd option.

**Comment by robert00s** [comment]
`self.ges_events` is `nil` in `Screensaver:close()`

**Comment by Frenzie** [comment]
Do you mean `self.left_msg.ges_events`?

**Comment by robert00s** [comment]
@Frenzie 
Yes, I mean `self.left_msg.ges_events`

**Comment by robert00s** [comment]
I think I need to create separate widget eg sswidget and put in it ges_events.
