### ISSUE TITLE
 dictionary not working under nightly-20171023 

### ISSUE THREAD

**Issue by xiaotaiqbc** [koreader/koreader#3469]
* KOReader version: nightly-20171023 
* Device:KOBO GLO

#### stardict works well under stable version KOREADER.  but it doesn't work under nightly-20171023. when I long press a word in EPUB, a window pops out ,but it shows"no definition found"
it seems the dictionary is unabled.....

help please. thank you.

**Comment by xiaotaiqbc** [comment]
please ignore my previous post. the problem solved. I changed the SDCV file according to this post https://github.com/koreader/koreader/issues/3302   thank you again!

**Comment by Frenzie** [comment]
No problem. Closing this now.
