### ISSUE TITLE
Can't find the Screensaver option

### ISSUE THREAD

**Issue by hpdung99** [koreader/koreader#3470]
* KOReader version: v2015.11-1370g5ee6c01
* Device: Kobo Aura One

#### Issue
Screensaver isn't available to modify after switching to the 3rd option of it (sorry i don't remember it actually), now the screensaver is always the current read + a "Sleeping" note.

Sorry if this problem has already been pointed out elswhere, but I've been finding solutions for almost a week now but no help at all.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by hpdung99** [comment]
Thanks for replying.

And sorry for my bad English, I think that my limited grammar and English knowledge has lead you to misunderstanding. My problem is that I could not find the "Screensaver" option, which I believe will appear when I hit the Configure tab (include options like Frontlight, Network, Screen etc.), and I cannot customize my screensaver without it (is there an alternative way to do it?). I wish that I could bring that option back, but I cannot find out what lead to it, also what can I do to fix that problem.

**Comment by Frenzie** [comment]
Oh, I see the problem.

If you disable the first option (use last book's cover as screensaver) then the menu isn't displayed in the reader:
https://github.com/koreader/koreader/blob/9ea2b3dbad50a86df96c2e5c4cdeac029b22f588/frontend/apps/reader/modules/readermenu.lua#L129

You can then only reactivate it from the filemanager.

This behavior doesn't make a whole lot of sense to me, but for the moment you can go into the filemanager → settings → screensaver → use last book's cover as screensaver.

**Comment by hpdung99** [comment]
Thanks, the second solution worked. If I get into the file manager and successfully checked the "use last book's cover as screensaver" tick box, the Screenshot option is available again in my documents.
