### ISSUE TITLE
djvu reader problems

### ISSUE THREAD

**Issue by konos93** [koreader/koreader#3475]
* KOReader version: kobo start menu 08 (2015.10.27)  v2015.11-6-g9e0be45
* Device: Kobo aura 

#### Issue 
i read books in djvu format with images because is lighter than pdf in same quality and run much faster.  i highlight part of text-images and take bookmarks  like pdf. but when i transfer back to my windows pc the djvu and pdfs i read ,i can find the changes only in pdfs .so even if i can find highlights in kobo i cant find them on windows for djvu files. 

i tried to install koreader-android-arm-linux-androideabi-v2015.11-1370-g5ee6c01.apk in my pc with 2 emulator koplayer and bluestacks. it  begun and stuck. 

any suggestions on what to do?

**Comment by Frenzie** [comment]
Stuck where? What does logcat say? You can also grab an x86 build from https://gitlab.com/koreader/nightly-builds/commit/dbc5ddc383879944b517ffc3bb5de4e07210895d/pipelines 

Btw, @embryo10 has a nice program called https://github.com/noembryo/KoHighlights

**Comment by konos93** [comment]
the app begin and stop immediately in emulators . 

how to use the build u send ?

![2017-11-12 02_07_08-exampleoocr pdf - adobe acrobat reader dc](https://user-images.githubusercontent.com/18540037/32694653-4543b748-c74e-11e7-9c4a-d067d8712373.png)
[examples.zip](https://github.com/koreader/koreader/files/1464248/examples.zip)
![2017-11-12 02_11_54-bluestacks](https://user-images.githubusercontent.com/18540037/32694678-ed3ec0fa-c74e-11e7-8fc4-2a70cee0eeeb.png)

About Kohighlights its my first time i used it thanks a lot for your suggestion.
i will highlight and bookmark the page i read .

 but Koreader  cant recognize the text from the highlited part which have or the ocr text back from the image for the djvu.

**Comment by Frenzie** [comment]
Both the ARM and x86 builds work in the Android emulators provided by Google for me.

The DjVu highlights probably aren't written into the file itself. As such this is probably a kind of reverse #3113.

**Comment by konos93** [comment]
https://www.youtube.com/watch?v=WgvTgV5EoGY 1.36 and after . dude that exactly how i feel .

can u please make a how to beginner guide for unexpired user?
what android emulator do u use ? can u suggest me on for windows 10?

**Comment by Frenzie** [comment]
Android Studio comes with an "AVD Manager" for Android development. What version of Android do these emulators pretend to be?

**Comment by konos93** [comment]
![2017-11-12 21_00_19-koreader-android-arm-linux-androideabi-v2015 11-1370-g5ee6c01 1 1 - c__users_ko](https://user-images.githubusercontent.com/18540037/32702242-961daf04-c7ec-11e7-9574-013b57c6dca9.png)

**Comment by Frenzie** [comment]
I'm not entirely sure what you're trying to say? :-)

**Comment by konos93** [comment]
![2017-11-13 10_52_46-bluestacks](https://user-images.githubusercontent.com/18540037/32717029-e0d5ba68-c860-11e7-8b12-456666e1fe30.png)

that from libjuatit.so is from android studio

**Comment by konos93** [comment]
hello again sir 
i didn't achieve to install on a simulator koreader i install koredear on huwaei y300 android 4.1.1

.the file that i install is koreader-android-arm-linux-androideabi-v2015.11-1370-g5ee6c01.apk
i use kobo aura with koreader version v2015.11-3-g9e0be45.
in kobo i can read ebook in djvu format that i make  but when i use the same files in my smartphone i cant use them.  it shows me "No reader engine for this file or invalid file" how can this happen?

**Comment by Frenzie** [comment]
That's odd; DjVu should work in that version (but not in any earlier version).

**Comment by konos93** [comment]
what enigne does koreader use to read djvu?
DjVuLibre?

**Comment by Frenzie** [comment]
That's correct. But until https://github.com/koreader/koreader-base/pull/546 it wasn't built on Android.

**Comment by konos93** [comment]
and how boomarks and highlights work the are on a .sdr file?
like example.djvu has boomarks and highlights on example.sdr or does koreader edit djvu like pdf?

**Comment by Frenzie** [comment]
I believe that's right but I'd have to check. Incidentally, in PDF highlights should be limited to .sdr if you opt not to save the document.

(If the last modified date doesn't change that'll tell you how it is.)

**Comment by konos93** [comment]
well pdf is edited in koreader . djvu Hasn't been edited. date in djvu isn't changed. 

djvu files and bookmarks isn't work in WinDjview . and if i highlight a djvu file  in WinDjvu . i cant see the highlighted part in ebook. i use djvu rather pdf because it need for the same quality 3 times almost less space  and run much better in koreader. pdf after many pages shows only blank pages and koreader change pages in much more time in pdf rather that djvu.

in lua file is highlighted only the image part like a  rectangular with four points .

personally i want to make 2 changes in koreader . 
1 edit djvu which means it keep bookmarks and highlights without the need of .sdr part and keep the changes viewable in any other program .
2 if djvu/pdf has already ocr part .the koreader can  keep the text part inside the .sdr  

"if something isn't permitted admin please delete this part http://libgen.io/ads.php?md5=C0F45222E9C59F1292B4EF4D3FA8DD7A " rename it to a.djvu to run in koreader

and make a.djvu.lua with this one 

-- we can read Lua syntax here!
return {
	["kopt_word_spacing"] = -0.2,
	["kopt_contrast"] = 1,
	["flipping_zoom_mode"] = "page",
	["render_mode"] = 0,
	["highlight_drawer"] = "invert",
	["bookmarks"] = {
		[1] = {
			["page"] = 9,
			["highlighted"] = true,
			["notes"] = "",
			["datetime"] = "2017-12-18 12:09:53",
			["pos1"] = {
				["page"] = 9,
				["x"] = 998.47529644269,
				["y"] = 1622.1077075099,
				["rotation"] = 0,
				["zoom"] = 0.30145963658028
			},
			["pos0"] = {
				["page"] = 9,
				["x"] = 391.42885375494,
				["y"] = 739.73418972332,
				["rotation"] = 0,
				["zoom"] = 0.30145963658028
			}
		}
	},
	["gamma"] = 1,
	["kopt_page_margin"] = 0.1,
	["screen_mode"] = "portrait",
	["kopt_font_fine_tune"] = 0.05,
	["show_overlap_enable"] = false,
	["kopt_defect_size"] = 1,
	["kopt_auto_straighten"] = 0,
	["config_panel_index"] = 1,
	["kopt_font_size"] = 1,
	["kopt_page_scroll"] = 0,
	["kopt_forced_ocr"] = 0,
	["kopt_writing_direction"] = 0,
	["bookmarks_sorted"] = true,
	["readermenu_tab_index"] = 1,
	["percent_finished"] = 0.044052863436123,
	["kopt_quality"] = 1,
	["bbox"] = {},
	["kopt_page_opt"] = 0,
	["rotation_mode"] = 0,
	["kopt_screen_mode"] = "portrait",
	["highlight_disabled"] = false,
	["kopt_trim_page"] = 1,
	["last_page"] = 10,
	["highlights_imported"] = true,
	["kopt_max_columns"] = 2,
	["kopt_text_wrap"] = 0,
	["kopt_justification"] = 3,
	["kopt_full_screen"] = 1,
	["kopt_detect_indent"] = 1,
	["page_overlap_style"] = "dim",
	["kopt_line_spacing"] = 1.2,
	["normal_zoom_mode"] = "page",
	["zoom_mode"] = "page",
	["kopt_doc_language"] = "eng",
	["flipping_scroll_mode"] = false,
	["highlight"] = {
		[9] = {
			[1] = {
				["text"] = "",
				["pos0"] = {
					["page"] = 9,
					["x"] = 391.42885375494,
					["y"] = 739.73418972332,
					["rotation"] = 0,
					["zoom"] = 0.30145963658028
				},
				["pos1"] = {
					["page"] = 9,
					["x"] = 998.47529644269,
					["y"] = 1622.1077075099,
					["rotation"] = 0,
					["zoom"] = 0.30145963658028
				},
				["datetime"] = "2017-12-18 12:09:53",
				["drawer"] = "invert",
				["pboxes"] = {
					[14] = {
						["y"] = 1161,
						["x"] = 304,
						["h"] = 12,
						["w"] = 1651
					},
					[2] = {
						["y"] = 798,
						["x"] = 190,
						["h"] = 27,
						["w"] = 1515
					},
					[12] = {
						["y"] = 1069,
						["x"] = 456,
						["h"] = 66,
						["w"] = 1597
					},
					[11] = {
						["y"] = 1069,
						["x"] = 763,
						["h"] = 63,
						["w"] = 1181
					},
					[10] = {
						["y"] = 1071,
						["x"] = 1897,
						["h"] = 12,
						["w"] = 14
					},
					[9] = {
						["y"] = 979,
						["x"] = 115,
						["h"] = 66,
						["w"] = 1938
					},
					[23] = {
						["y"] = 1522,
						["x"] = 582,
						["h"] = 52,
						["w"] = 1318
					},
					[8] = {
						["y"] = 981,
						["x"] = 2044,
						["h"] = 12,
						["w"] = 14
					},
					[19] = {
						["y"] = 1341,
						["x"] = 618,
						["h"] = 14,
						["w"] = 1186
					},
					[7] = {
						["y"] = 979,
						["x"] = 502,
						["h"] = 65,
						["w"] = 1442
					},
					[1] = {
						["y"] = 710,
						["x"] = 362,
						["h"] = 64,
						["w"] = 813
					},
					[6] = {
						["y"] = 890,
						["x"] = 1722,
						["h"] = 50,
						["w"] = 212
					},
					[5] = {
						["y"] = 888,
						["x"] = 167,
						["h"] = 64,
						["w"] = 1340
					},
					[26] = {
						["y"] = 1613,
						["x"] = 976,
						["h"] = 14,
						["w"] = 14
					},
					[25] = {
						["y"] = 1539,
						["x"] = 111,
						["h"] = 49,
						["w"] = 940
					},
					[4] = {
						["y"] = 888,
						["x"] = 114,
						["h"] = 67,
						["w"] = 1942
					},
					[21] = {
						["y"] = 1432,
						["x"] = 156,
						["h"] = 14,
						["w"] = 1902
					},
					[24] = {
						["y"] = 1523,
						["x"] = 186,
						["h"] = 64,
						["w"] = 1868
					},
					[22] = {
						["y"] = 1435,
						["x"] = 111,
						["h"] = 63,
						["w"] = 1945
					},
					[18] = {
						["y"] = 1252,
						["x"] = 113,
						["h"] = 64,
						["w"] = 1807
					},
					[20] = {
						["y"] = 1344,
						["x"] = 205,
						["h"] = 63,
						["w"] = 1825
					},
					[3] = {
						["y"] = 800,
						["x"] = 115,
						["h"] = 65,
						["w"] = 1937
					},
					[17] = {
						["y"] = 1250,
						["x"] = 1942,
						["h"] = 26,
						["w"] = 55
					},
					[16] = {
						["y"] = 1250,
						["x"] = 308,
						["h"] = 53,
						["w"] = 1650
					},
					[15] = {
						["y"] = 1162,
						["x"] = 112,
						["h"] = 65,
						["w"] = 1942
					},
					[13] = {
						["y"] = 1072,
						["x"] = 114,
						["h"] = 64,
						["w"] = 831
					}
				}
			}
		}
	},
	["page_positions"] = {
		[2] = 0,
		[3] = 0,
		[4] = 0,
		[5] = 0,
		[6] = 0,
		[7] = 0,
		[8] = 0,
		[9] = 0,
		[10] = 0,
		[11] = 0,
		[12] = 0,
		[13] = 0,
		[14] = 0
	}
}






this one is a djvu file i did capturing pages with a diybookscannner i made and use programs like scantailor, djvusmall and abbyyfinereader for more information check this https://www.youtube.com/watch?v=Rkf49KPIPf0 i will add subs when i can.

**Comment by Frenzie** [comment]
> 1 edit djvu which means it keep bookmarks and highlights without the need of .sdr part and keep the changes viewable in any other program .

Like in PDF that should be optional. Some of us think don't think modifying the file is desirable. :-) (PRs welcome akin to PDF.)

> 2 if djvu/pdf has already ocr part .the koreader can keep the text part inside the .sdr

It doesn't like in EPUB? I'd consider that a bug. PRs very welcome! :-D

> i use djvu rather pdf because it need for the same quality 3 times almost less space and run much better in koreader.

Btw, I also prefer DjVu for that reason but note that by using PDF with JBIG2 you can get reasonably close to DjVu. I uploaded a demo document [here](https://www.mobileread.com/forums/showpost.php?p=2950080&postcount=3).

**Comment by konos93** [comment]
well i use 2 cannon a3300 camera to capture pages or a 5 mp smartphone https://www.youtube.com/watch?v=n1ZKAbBjeJ0, https://www.youtube.com/watch?v=euJSyIALWYE . for results check this https://forum.diybookscanner.org/viewtopic.php?f=14&t=3364&start=30 

so i have to compress large images much bigger that flatscanners . with jbig2 compress in pdf for a book 800 pages i had 45 mb and 13 mb in djvu .

> 2 if djvu/pdf has already ocr part .the koreader can keep the text part inside the .sdr

sorry i was meaning that in my kobo the koreader i read djvu files that they have text behind images .
.only the image will get highlighted .the highlighted text isn't saved somewhere .

anyway while the highlighted pages  is saved in *.djvu.lua and i can find that with ["page"] =* i will edit an ordinary djvu file with WinDjvu while i trying to find the part with "go to" pages command in koreader. 

in any case koreader is a great tool for me and ebook users. thanks a lot for your time and your help.

**Comment by Frenzie** [comment]
Interesting hobby project though the thought of using a smartphone instead of a P&S (second video) is horrifying. :-)

**Comment by konos93** [comment]
yeah cost for the 2 camera scanner is almost 200 euro and for smartphone almost 20 .
the first one is 1500 pages per hour and with the second one 700

**Comment by Frenzie** [comment]
Just a quick note: the AppImage actually runs in the Windows Subsystem for Linux in combination with an X server.

https://docs.microsoft.com/en-us/windows/wsl/install-win10

https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/

It's a little tricky but it works.

Anyway, closing for now. Feel free to open up a new issue should further questions arise. :-)
