### ISSUE TITLE
Segmentation fault during any action on PocketBook 631

### ISSUE THREAD

**Issue by Loriowar** [koreader/koreader#3480]
* KOReader version: koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1370-g5ee6c01
* Device: PocketBook 631; OS version: U631.5.17.821; Releace date: 20171025_153227

#### Issue

Segmentation fault dirung any menu item access.

#### Steps to reproduce

Push on button with three stripe. In appeared menu select any item. Application will be crashed.

##### `crash.log`

https://pastebin.com/F7JZcsmB

**Comment by mk-f** [comment]
This will be hard to debug without any additional information. If you have [shell access](https://www.mobileread.com/forums/showthread.php?t=159636) to the device you could run koreader under strace, or better via gdb, which should show the cause of the segfault. For what its worth you could enable debug-logging to ``crash.log`` by inserting ``["debug"] = true,`` in  ``applications/koreader/settings.reader.lua``

**Comment by Loriowar** [comment]
Thanks for debug description. I install a night build from Now 11. It works for me. No segmentation fault.
