### ISSUE TITLE
Unable to open files on external SD card on Android

### ISSUE THREAD

**Issue by mmjoshi** [koreader/koreader#3483]
* KOReader version: 2015.11-1405 and many other versions
* Device: Redmi Note 3, MIUI 9

**Comment by jperon** [comment]
I can confirm this problem on my Android phone too (Blackview BV6000).

**Comment by Frenzie** [comment]
@poire-z posted a relevant reply about permissions here: https://github.com/koreader/koreader/issues/3365#issuecomment-336860772

**Comment by jperon** [comment]
That's what I thought; even "force external storage availability" in developper options doesn't fix it.
Wouldn't it be a possibility to have some sort of "read-only" mode to open such external files, even without having bookmarks and so on ?

**Comment by Frenzie** [comment]
PRs welcome. :-) A true read-only mode would be a lot of work; a minimal effort read-only mode might be as simple as playing around a little with DocSettings.
