### ISSUE TITLE
Add most/last used or favorites menu

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3485]
* KOReader version:
* Device:

#### Issue
IMHO our top menu don't have the best UX. 

I think it would be good to add new menu which will add most used functions (as it was(is?) in MS Windows "Start menu") with 5 most used entries. 
If that's too hard to do then it could be e.g.7 last used entries.
That would be the default opened menu.

If it's implemented the first way (most used) than in fueture we could send to our server analytis info what users mostly use, and would be good basis to reorganize menu. But that's separate topic

**Comment by mwoz123** [comment]
Favorites menu might be also a good solution..

**Comment by AlanSP1** [comment]
You also could edit menu entries (not sure exactly how to do that, but info is here somewhere), which would enable that you have your best menu spread.

**Comment by Frenzie** [comment]
Let's agree to disagree on the OP. I don't like such unpredictability. It's like having to relearn the program every day.

A favorites menu on the other hand definitely sounds interesting. You can already easily do that of course; there's just no GUI for it.

XP already had a decent compromise solution. You could pin programs for stability and it auto-populated some suggestions underneath.

**Comment by Frenzie** [comment]
Favorites were added in #4165 and #5527.
