### ISSUE TITLE
Android. Scroll speed slowed down

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3486]
Hi

I felt like the scroll speed had improved quite a bit on Android in recent months but I see a big speed drop in v2015.11-1405-g0e5293f

The scroll speed of v2015.11-1400-g6d1e185 if fine on my LineageOS 7.1

thanks

**Comment by gerroon** [comment]
I forgot to mention I was using it with Pdf with auto crop.

**Comment by Frenzie** [comment]
We did have a pretty big change under the hood last week in https://github.com/koreader/koreader/pull/3468 (just after the 6d1e185 you mentioned) but in theory that should be something in between barely faster to a lot faster, not slower.

**Comment by gerroon** [comment]
@Frenzie

The speed of scroll is very choppy in 1405, it is like back in the days, more like pre improved state. This is how it was on Android but like I said the scroll speed got a nice improvement in recent months , it was feeling more like a naaive app scrollng, I mean almost.

**Comment by gerroon** [comment]
Github redit script is broken( I block all js pretty much) so editing here

naaive=native

**Comment by chrox** [comment]
@gerroon Did you by any chance check the "Eink optimize" option in the "Screen" config section? That option will throttle the screen refresh rate to [at most 2 per second](https://github.com/koreader/koreader/blob/29707bd664133da45783d6bbef37db8b71563dbc/frontend/apps/reader/readerui.lua#L91).

**Comment by gerroon** [comment]
@chrox 

E-ink optimization is not checked.

Do you see a clear improvement between 1400 and 1405?

**Comment by gerroon** [comment]
Btw I was wrong about the format. I was testing it with Djvu
