### ISSUE TITLE
Wrap long files and directories names in file browser to new line

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3488]
* KOReader version: current git
* Device: all

#### Issue
Currently file browser display only ~40 first characters from filenames and directories.
Sometimes file names are much longer, and it's not enough.

Idea is to wrap such long file names to new lines. 
I assume max chars limit (can be variable in `defaults.lua`) can be set to e.g 128 (0 for no limit).

#### Steps to reproduce
Open KOReader file browser, go to directories with long filenames.

Unfortunately this is above my abilities in Lua, and I won't be able to implement it on my own:(

**Comment by Frenzie** [comment]
You can always hold or just choose a different view.

![screenshot_2017-11-14_21-38-51](https://user-images.githubusercontent.com/202757/32803624-655e5384-c984-11e7-97a6-042eeb74fe38.png)

**Comment by mwoz123** [comment]
Ooo didn't know we had it already in different view.
Thanks .

But anyway I think it would be good to add wrapping to standard files view

**Comment by Frenzie** [comment]
I would propose replacing the default view with one of the detailed list options from @poire-z 's CoverBrowser and to just make that part of the core. Then again, the current plugin solution also has a certain je ne sais quoi. :-P

**Comment by poire-z** [comment]
I'm honestly not so keen on reworking on it to move it into core (and I have no real clue how that would be done). So, if anyone wants to do it, feel free :)
Also, enabling a cover view takes one step, disabling it and cleaning takes 2 steps (choosing classic + delete cache db).
Enabling one cover view as default on first koreader startup would need a trick (ala quickstart book), as the current display mode is stored in the cache db itself.
But I somehow like the idea of rewarding the curious people that actually look at all menu items :)

**Comment by mwoz123** [comment]
done in #3589
