### ISSUE TITLE
Djvu not working on Android 4.2, cannot locate symbol "pow"

### ISSUE THREAD

**Issue by Germanc** [koreader/koreader#3493]
* KOReader version:
koreader-nightly-20171023 

* Device:
Onyx Boox C67ML, Android 4.2

#### Issue
Can't open djvu files.

Relevant logcat:
I/KOReader(16865): dl.lua - sys_dlopen - loading library /data/data/org.koreader.launcher/files/libs/libkoreader-djvu.so
I/KOReader(16865): error: [string "dl.lua"]:40: error opening /data/data/org.koreader.launcher/files/libs/libkoreader-djvu.so: Cannot load library: soinfo_relocate(linker.cpp:975): cannot locate symbol "pow" referenced by "libkoreader-djvu.so"...
I/KOReader(16865): try to load module /data/data/org.koreader.launcher/files/libs/libkoreader-djvu.so
I/KOReader(16865): error: [string "dl.lua"]:98: could not find library /data/data/org.koreader.launcher/files/libs/libkoreader-djvu.so

**Comment by Frenzie** [comment]
Some searching seems to suggest it's an issue that might occur on some Android 4.x devices: https://lists.freedesktop.org/archives/gstreamer-android/2015-June/000998.html

**Comment by Frenzie** [comment]
@Germanc Is this still an issue? We do link with `-lm` [here](https://github.com/koreader/android-luajit-launcher/blob/132b24664a545e524039de193466b2c15d2a4a5b/jni/Android.mk#L49) (but of course we always have).

**Comment by Frenzie** [comment]
Confirmed as still an issue in 4.2.

**Comment by NiLuJe** [comment]
Might be able to paper over it by seeing if we can make do purely with [GCC builtins](https://github.com/NiLuJe/FBInk/blob/618725c1b5c1bfe401b41b8681ca2aa69670a612/fbink_internal.h#L52-L113)?

**Comment by Frenzie** [comment]
Android 4.2 is so buggy it's hard to test.

Naively putting those in just like this doesn't seem to fix things much. There's no "cannot locate pow" error, but it still won't load.

```c
#			define iceilf(x) __builtin_iceilf(x)
#			define iroundf(x) __builtin_iroundf(x)
#			define ifloorf(x) __builtin_ifloorf(x)
#			define STBTT_floorf(x) __builtin_floorf(x)
#			define STBTT_ifloor(x) __builtin_ifloorf(x)
#			define STBTT_iceil(x) __builtin_iceilf(x)
#			define STBTT_sqrt(x) __builtin_sqrtf(x)
#			define STBTT_pow(x, y) __builtin_powf(x, y)
#			define STBTT_fmod(x, y) __builtin_fmodf(x, y)
// Need to keep double precision for cos, because GCC sneakily replaces a PI approximation in stbtt ;)
#			define STBTT_cos(x) __builtin_cos(x)
#			define STBTT_acos(x) __builtin_acosf(x)
# define STBTT_fabs(x) __builtin_fabsf(x)
```

**Comment by NiLuJe** [comment]
Well, my example just that, an example: it's targeting stb, which uses custom define especially for those kind of shenanigans ;).

Here, something like `define pow(x) __builtin_pow(x)` might be enough (provided it's also not calling pow through a custom define).

**Comment by Frenzie** [comment]
The pow error specifically comes from our own djvu wrapper, but with Android 4.2 being even more broken than most Android versions (quite an accomplishment) I'm surprised anything works anyway.

https://github.com/koreader/koreader-base/blob/15becff11c1b23edbd3f8c74cd949fc0e219d115/djvu.c#L710

I'll give it another look later.

**Comment by pazos** [comment]
`readelf -sW base/build/i686-linux-android-debug/libs/libkoreader-djvu.so` returns

`98: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND pow`

**Comment by Frenzie** [comment]
@pazos Perhaps you were already using the Android emulator images with Play services. In any case, on present-day Debubuntu the regular Android 4.x images are horribly broken for me, but those with Play services mostly seem to work.

**Comment by Frenzie** [comment]
As to the original issue, it's listed on https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#cannot-locate-symbol which eventually ends up at https://issuetracker.google.com/issues/37000040 and https://stackoverflow.com/questions/27091001/how-to-use-mkfifo-using-androids-ndk/27093163#27093163

But that claims it's due to using API 21 headers while we use 19, so something about the analysis can't be quite right.
