### ISSUE TITLE
Purge .sdr in "History" for a book that is open in the Reader

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3494]
* KOReader version: v2015.11-1373-g3639c3e
* Device: KA1

#### Issue

If you have a book open in the Reader and then open "History" and try to purge .sdr for the same book, the purge isn't executed.

If the book is opened for the first time you can't purge in this way ("Purge .sdr" is greyish). I have no problem with this. I guess this is how it is meant to be. 

But if the book has been opened before it may seem like you can perform a purge: for example, the book will disappear from "History" if you have choosen "Auto-remove purged items from history". But in reality the book is still "unpurged".

May I suggest following modification:
Either 
make example 1 standard, i.e always impossible to purge .sdr for a book that is open in the Reader
or
if allowing a purge in this situation, when you exit "History" after such a purge, you should end up in file manager (and not back to (and inside) the book you just purged).

#### Steps to reproduce
1. Open a book from your "History" page.
2. Open "History" page.
3. Longpress the book you just opened and perform a purge.
4. Leave "History" and go to file manager and check out the book you purged

**Comment by Frenzie** [comment]
Pinging @poire-z

**Comment by poire-z** [comment]
Actually, the sidecar file is created when one closes a book.
So, when you open a new book, there is indeed no sidecar file yet, so it's greyish.
For a previously opened book, there is one, and when you purge it from history, it is actually removed. But later, when you close the book or exit koreader, the sidecar is re-created, so it looks like a no-op.
As you see now, the behaviour you describe was not really planned :)

I think the simplest solution is to prevent/forbid Purge.sdr and Delete for files opened by any background ReaderUI instance.
So, should we just have these button grey when the book is opened (I have this patch ready) ?
Or should they be still enabled, but just popup an InfoMessage in the case this file is opened inviting the user to close it first ?

**Comment by gerhaher** [comment]
I vote for this alternative:

> So, should we just have these button grey when the book is opened (I have this patch ready) ?
