### ISSUE TITLE
page crop with "fit to page"

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#3501]
#### Issue
I would like to crop the pages in a pdf the same amount for each page (relative to the page size displayed with "fit to page"). That means reduce any unnecessary margin in the document's default page size but in such a way that all pages in a book display with the same zoom factor. With the existing manual crop option, I could not manage to do this. Maybe it's possible and I just don't understand how cropping works in koreader (difference between auto, semi-auto and manual crop and how "content" for the zoom options is defined in each case). Is it described somewhere?

**Comment by Frenzie** [comment]
Please see https://github.com/koreader/koreader/issues/2931#issuecomment-305556655.
