### ISSUE TITLE
kodev wbuilder fails to start

### ISSUE THREAD

**Issue by TnS-hun** [koreader/koreader#3504]
`./kodev: line 371: pushd: $'./koreader-emulator-x86_64-linux-gnu-debug/koreader\n./koreader-emulator-x86_64-linux-gnu/koreader': No such file or directory`

I don't speak Bash but it looks like EMU_DIR contains multiple lines after the setup_env function finishes.

Starting it with `KODEBUG_SUFFIX=debug ./kodev wbuilder` works.

**Comment by TnS-hun** [comment]
Thank you!

**Comment by Frenzie** [comment]
NP. Besides, I introduced the issue. :-P
