### ISSUE TITLE
Dictionary look up doesn't work.

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#3505]
* KOReader version: koreader-nightly-20171023 (koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1370-g5ee6c01)
* Device: Kobo Aura H2O

#### Issue

Dictionary look up doesn't work for me. When I select a character (looking up for Chinese word) pop-up with "No defenition found" appears. 

I can see dictionaries in "Installed dictionaries" section ( .dict, .idx and .ifo are all present on the device).

Dictionaries I use:
https://yadi.sk/d/L4IP8hHy3PmHbA

(password in case you won't be able to unrar it: "bkrs.info")

Book I read in the attach.

[Chai Jing  - Kan Jian  - Chai Jing.kepub.zip](https://github.com/koreader/koreader/files/1487254/Chai.Jing.-.Kan.Jian.-.Chai.Jing.kepub.zip)

**Comment by Sopheus** [comment]
Just checked with old-old stable version:

https://github.com/koreader/koreader/releases/tag/v2015.11-stable

Everything works fine.

What is the problem and how to fix it. Thanks

**Comment by Sopheus** [comment]
I found this post:

https://github.com/koreader/koreader/issues/3302

Seems like the issue is like the one I have. But I do not understand how to apply the fix. 

Some guidance would be much appreciated.

**Comment by Frenzie** [comment]
Inside the .adds/koreader directory there's an executable file called `sdcv` which is responsible for dictionary lookups. You can replace it with another one (whether from the old release or one of the builds I posted).

The real fix will have to come from the nightly build toolchain, unfortunately.

**Comment by Sopheus** [comment]
Great! Thanks Frenzie! It worked.

To anybody who have issue like me:

1. Connect your Kobo to PC;
2. Navigate to ".adds/koreader";
3. Find executable "sdcv";
4. Unzip and replace it with the one in the attach.
[sdcv-arm-linux-gnuabihf.zip](https://github.com/koreader/koreader/files/1489711/sdcv-arm-linux-gnuabihf.zip)


Issue can be closed
