### ISSUE TITLE
Create "new directory", new option in Koreader File Manager

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3509]
* KOReader version: git
* Device: all

#### Issue
There's no way to create a new folder in File Manager.

#### Steps to reproduce
Open File manager, cut a book, try to paste it to new folder - can't theres no such option. 

Workaround for that is to copy existing folder (recommended without any files inside) and paste it somewhere else, rename, move to correct place, but that's a little bit annoying.

**Comment by robert00s** [comment]
What about something like that:
before:
![koreader_030](https://user-images.githubusercontent.com/22982594/34126962-ab86cfe0-e43b-11e7-8c2e-1f375a75ab43.png)


after:

![koreader_031](https://user-images.githubusercontent.com/22982594/34126972-b0d7efe2-e43b-11e7-91fb-90c8247ddbfa.png)

**Comment by Frenzie** [comment]
My Android filemanager has a <kbd>+</kbd> in the bottom right. Could something like that be an idea?

**Comment by poire-z** [comment]
> after

I don't like it much: all the existing buttons in that context menu are for doing an action on the file whose filename is in the title.
`New folder...` would be the only one that does not apply to the filename.

Ideally, it should be in the context menu you get when you hold on a directory. But there's no item for the _current_ directory :| (there are only the sub-directories, or the parent directory `../`).
Or may be in the context menu of a subdirectory, named `Create a directory alongside the one you were holding on` :)

(Not fond of <kbd>+</kbd> always there, for such a rarely needed action)

**Comment by Frenzie** [comment]
> (Not fond of + always there, for such a rarely needed action)

Not really a fan either, but similarly for the proposal in the screenshot.

But when I say something *like* that it could also be something to trigger a current folder menu or something. ;-) Just brainstorming.

**Comment by robert00s** [comment]
I like <kbd>+</kbd> to trigger a current folder menu options (plus add that option to filemanger menu).

**Comment by poire-z** [comment]
(If <kbd>+</kbd>, it could be in the top right corner then, for symetry with the home button and less chance to be hit by accident - but please not bottom right, that's where my thumb like to wander :)

**Comment by KenMaltby** [comment]
That could work, and the space is open, because the browser doesn't have (or need?) a bookmark icon.  Also, it would be right next to where the current folder is indicated, so you should know which directory will be getting the new folder.

**Comment by Frenzie** [comment]
I don't know if + is necessarily the right icon for "generic folder interaction" but sure, that should work.

**Comment by robert00s** [comment]
![obraz](https://user-images.githubusercontent.com/22982594/34172094-19553da8-e4f1-11e7-9b0c-e850e9888a60.png)

But I used Button widget instead of IconButton. We should use IconButton but I need nice icon with <kbd>+</kbd> :)

**Comment by KenMaltby** [comment]
Maybe a regular yellow folder icon? When selected an interactive box would appear labeled "Add new folder"  and offering a place to enter the wanted folder name.  I guess a cancel button would also be in order.

**Comment by robert00s** [comment]
I found the icon here https://useiconic.com/open and changed it a bit.
Now FM look that:
![koreader_035](https://user-images.githubusercontent.com/22982594/34226947-b174f134-e5cb-11e7-83e3-e51892202ed0.png)

and menu: 
![koreader_036](https://user-images.githubusercontent.com/22982594/34228249-661a6c96-e5d0-11e7-8e9c-27292437a64b.png)

**Comment by KenMaltby** [comment]
The existing "Home" icon seems to work ok, for the "Go to Home" and long press for the "Set as Home" (which is very much like setting a default anyway).  The "Paste" idea could be useful for moving things around depending on your file structure, the current long press on an item in the File Browser gives both a "cut" and a "copy" option.  (It also has a "paste", but I don't see how that would work when you have selected an item.  Would it replace the selected item? or be inserted after the item selected? {would be my choice}). There might also be an effect on the sorting.

**Comment by robert00s** [comment]
It works the same as the long press option (insert file in current folder).
