### ISSUE TITLE
KEPUB rendering support.

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#3510]
* KOReader version: Doesn't matter
* Device: Kobo Aura H2O

#### Question

As everyone knows, .kepub is a .epub book format that was designed specially for Kobo e-readers.

Does KoReader have full support of this format?

Format comparison:

Positive: KePub (sideloaded):

    Quicker to respond to page turn gestures (especially tap gesture)
    Faster text selection (e.g. when highlighting large areas of text)
    Support for footnote previews
    Can double-tap to zoom images
    Shows number of minutes of reading left until end of chapter
    Shows title of ebook in the header (negative for some people)
    support for ePub 3. 

Positives for standard ePub on a Kobo device:

    Better hyphenation (kepub reader can hyphenate words in the wrong place if they have trailing punctuation)
    Full justification works properly (kepub reader doesn't properly justify some lines that contain certain common characters such as ellipsis and emdash)
    Better support for embedded fonts
    Full-screen mode works without fonts being cut off
    Better word spacing when using full justification

**Comment by Frenzie** [comment]
I don't think so. You'd probably need to use something like calibre to convert to EPUB. Note that stuff like time to read doesn't depend on one format or the other. ;-)

**Comment by cramoisi** [comment]
Kepubs are just epubs with span tags inside which are only used by the kobo stock reader. You could as well put epubs inside your calibre library and use the kobo touch extended driver to sideload them in the kepub format without convert them. I tend to think that there is no point to maintain a database with a non standard format like this.

As Frenzie said kepubs have only a positive aspect within the nickel (the app used by kobo to display epub) and this positive aspect is only because of bugs and flaws in their epub reader. From my experience, you could have all the avantage of kepub in nickel by reader epub in Koreader :)

**Comment by Frenzie** [comment]
I don't know; that footnote preview thing sounds interesting. ;-) But that's #3054 or #3246. (Those can probably be considered duplicates, but that aside.)

What kind of extra span tags does it use?

**Comment by cramoisi** [comment]
mostly wrapping < span > 

[https://github.com/jgoguen/calibre-kobo-driver/blob/master/container.py](https://github.com/jgoguen/calibre-kobo-driver/blob/master/container.py)

**Comment by AlanSP1** [comment]
@Sopheus I read what you placed as advantages of kepubs. Thing is, it is probably (I really don't know, as I don't use nickel at all) advantage within nickel, not advantage per se that would be advantage everywhere.

Many things you mention as advantage in both cases already exists in koreader, so from my perspective there is only one advantage, if kepub gets support in koreader: That koreader can open one more file format.

For me, as I don't have kepubs at all (as I mentioned, I don't use nickel and "kobo book world" at all), there's no advantage, but I guess there are people that have DRM free kepubs (I don't know if it is possible, to have DRM free kepub).

**Comment by Sopheus** [comment]
Ow, did not know that. In that case it is really no reason for kepub support. Thanks for clarification guys )))
