### ISSUE TITLE
Right align time in "Reading statistics"

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3515]
It probably looks better if the time in "Reset book statistics" and "All books" (in "Time Range") are right aligned.

**Comment by Frenzie** [comment]
Pinging @robert00s (wasn't something like this just done?)

**Comment by gerhaher** [comment]
I have the latest version (22 nov). They are not right aligned:
![filemanager_2017-nov-23_184427](https://user-images.githubusercontent.com/32645430/33184760-981c9988-d07e-11e7-8734-fb93d83a7205.png)
![filemanager_2017-nov-23_184446](https://user-images.githubusercontent.com/32645430/33184775-a851af14-d07e-11e7-8354-7f2920f553cb.png)
