### ISSUE TITLE
KOReader crashes (library path issue)

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#3523]
* KOReader version: development
* Device: Kindle 7th generation

#### Issue
After update KOReader crashes at start
#### Steps to reproduce
Start KOReader (either to open last document or to start file manager)
##### `crash.log` (if applicable)
Crash log shows the library libmupdf.so cannot be loaded. 'ldd libmupdf.so' shows it cannot find library '/builds/koreader/nightly-builds/koreader/base/build/arm-linux-gnueabi/libs/libz.so.1' (I guess such path exists only in the building environment)

**Comment by Frenzie** [comment]
Could you please provide a few more details? Development would most likely mean a44b39fda6a59eb71011b60b7ed80cc294b1ae82 but for the moment that's unclear and in a couple of weeks much harder to find out.

https://github.com/koreader/koreader/pull/3520 itself is a prime suspect for accidentally breaking something like that, so would you happen to remember from roughly when your previously working version was?

**Comment by ilyats** [comment]
It started after update today. Can I find out version without starting
KOReader?

28 нояб. 2017 г. 8:44 PM пользователь "Frans de Jonge" <
notifications@github.com> написал:

**Comment by ilyats** [comment]
Couldn't it be connected to #3519? I usually check for updates dayly, there were none for some days, then an update come today and broke it.

**Comment by Frenzie** [comment]
If it's the update today it's the version I mentioned. The version is always in a file called git-rev.

#3519 is not a thing. It's just a question. :-) #3520 is an actual change in the build process. However, I don't think libmupdf or libz should even be affected by it…

Pinging @chrox

**Comment by ilyats** [comment]
I created the path and put a symlink to /mnt/us/koreader/libs/libz.so.1 in it. Now KOReader starts. The version is ga44b39f
