### ISSUE TITLE
[Pocketbook] Crash on start

### ISSUE THREAD

**Issue by Matt-Soft** [koreader/koreader#3525]
* KOReader version: koreader-nightly-20171023
* Device: Pocketbook 624  SoftwareVersion:  W624.4.4.1739

#### Issue
After OTA update koreader won't start.

#### Steps to reproduce
Update koreader to latest version?

##### `crash.log` (if applicable)
11/29/17-23:07:30 INFO  SoftwareVersion:  W624.4.4.1739
./luajit: frontend/device/pocketbook/device.lua:176: unrecognized PocketBook model PocketBook 624
stack traceback:
	[C]: in function 'error'
	frontend/device/pocketbook/device.lua:176: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:38: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/centercontainer.lua:5: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:2: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/confirmbox.lua:21: in main chunk
	[C]: in function 'require'
	./reader.lua:91: in main chunk
	[C]: at 0x0000c051

**Comment by Frenzie** [comment]
Odd, this should already be fixed by https://github.com/koreader/koreader/pull/3472

**Comment by mk-f** [comment]
No,  PocketBook 62**4**, not PocketBook 62**6**. I'll see to it tomorrow.

**Comment by Frenzie** [comment]
D'oh! That's what I get for leaving some quick comments from my phone. :-)

**Comment by mk-f** [comment]
@Matt-Soft: Can you try with [this](https://github.com/mk-f/koreader/blob/c05a17ef864ca107ce85d9692da5dbf30112294b/frontend/device/pocketbook/device.lua) ``device.lua``? Replace the one under ``applications/koreader/frontend/device/pocketbook/device.lua`` on you reader.

**Comment by Matt-Soft** [comment]
@mk-f It work's now :) Thank you.
