### ISSUE TITLE
Update wiki page about the frontlight gesture

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#3527]
* KOReader version: koreader-nightly-20171023
* Device: eink screen

Sliding two fingers up/down the screen seem to interact with frontlight (somewhat). I discovered this accidentally. Could you please document the intended behaviour in the wiki page?

**Comment by Frenzie** [comment]
You know more than me. :-P

**Comment by ersi-dnd** [comment]
@Frenzie 
> You know more than me. :-P

This one does not count. It's fool's luck.

**Comment by Frenzie** [comment]
It's a partial duplicate of https://github.com/koreader/koreader/issues/3484 btw.

**Comment by Frenzie** [comment]
Closing since @chrox added this to the wiki.

https://github.com/koreader/koreader/wiki/KOReader-Gestures
