### ISSUE TITLE
Night mode crashes Kr when selected

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3529]
Hi

I am using Kr -1416- on Inkbook Prime.

I have been reading the current book(flowed pdf) for a while with night mode and daytime mode without any issues, I read almost %75 of the book without issues.. However last night Kr started crashing as soon as I click on night mode (daytime to night mode). 

I got the adb log  and I do not see much there but might be helpful. This is just when I click on night mode

```
I/KOReader( 2531): DEBUG in tap timer true
I/KOReader( 2531): DEBUG single tap detected in slot 0 {
I/KOReader( 2531):     ["y"] = 227.77755737305,
I/KOReader( 2531):     ["x"] = 171.77339172363,
I/KOReader( 2531):     ["h"] = 0,
I/KOReader( 2531):     ["w"] = 0
I/KOReader( 2531): }
I/KOReader( 2531): DEBUG blitFrom 21 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 117 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 213 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 309 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 405 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 501 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 686 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 10 589 0 0 60 60
I/KOReader( 2531): DEBUG close widget
I/KOReader( 2531): DEBUG blitFrom 21 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 117 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 213 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 309 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 405 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 501 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 686 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 10 589 0 0 60 60
I/KOReader( 2531): is charging?
I/KOReader( 2531): is charging 1
I/KOReader( 2531): DEBUG blitFrom 21 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 117 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 213 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 309 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 405 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 501 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 686 12 0 0 51 51
I/KOReader( 2531): DEBUG blitFrom 10 589 0 0 60 60
I/WindowState(  385): WIN DEATH: Window{41144d40 u0 org.koreader.launcher/org.koreader.launcher.MainActivity}
I/ActivityManager(  385): Process org.koreader.launcher (pid 2531) has died.
E/SurfaceFlinger(  104): remove dialog --- org.koreader.launcher/org.koreader.launcher.MainActivity
E/SurfaceFlinger(  104): remove dialog --- org.koreader.launcher/org.koreader.launcher.MainActivity
E/SurfaceFlinger(  104): remove dialog --- org.koreader.launcher/org.koreader.launcher.MainActivity
W/ActivityManager(  385): Force removing ActivityRecord{41281768 u0 org.koreader.launcher/.MainActivity}: app died, no saved state




```

**Comment by gerroon** [comment]
I went ahead and added the night mode in the koreader settings file. Well guess what, koreader crashes as oon sa it starts. So I have no idea why it would start acting this way. The result was the same with another pdf file  without reflow.

**Comment by poire-z** [comment]
Confirming this happens with latest version too: no crash, but tap behaviour is all screwed up - you can tap anywhere on the screen, it just somehow keep toggling nightmode for each tap - and when killed and relaunched, no page is displayed, but taping anywhere still continue toggling black <-> white screen...
Was not happening with early october builds.
Tracked it down to changes between v2015.11-1400-g6d1e185 (working) and v2015.11-1401-g5faddfd (not working), so https://github.com/koreader/koreader-base/pull/571 .

**Comment by gerroon** [comment]
@poire-z 

My issue is pure crash nothing like ui glitches but after your post I went back to -1348- from october and it does not seem to crash when I turn the night mode on. So you might be on to something there.

**Comment by chrox** [comment]
It seems the cblitbuffer is not working on the Inkbook. Could you post the whole crash log without greping koreader?

**Comment by poire-z** [comment]
@chrox: I'm not using an Inkbook, but a sony phone with android 6.0.1.
But here [logcat_sonyandroid601.zip](https://github.com/koreader/koreader/files/1524592/logcat_sonyandroid601.zip), with nothing much interesting I guess (except that I don't see any mention of libblitbuffer.so):

`logcat_w_patchlua_nocrash_but_stuck_toggling.txt` : logs when 1) enabling night mode, and getting stuck into toggling it - then killed and 2) launching with night mode enabled in settings
I had patch.lua enabled, containing:
```
-- Avoid koreader stuck and crashes
require("jit.opt").start("sizemcode=64","maxmcode=512", "recunroll=8", "callunroll=12", "loopunroll=60", "instunroll=16", "tryside=16", "hotexit=160", "hotloop=1792", "maxsnap=160000", "maxside=32000", "maxirconst=160000", "maxrecord=1280000", "maxtrace=320000")
for i=1,1000 do end  -- Force allocation of one large segment
```

`logcat_wo_patchlua_crash_when_enabling_nightmode.txt` : I removed this patch.lua, and I get now, like @gerroon , an immediate crash.

**Comment by chrox** [comment]
@poire-z Does it help if you delete the file `/data/user/0/org.koreader.launcher/files/libs/libblitbuffer.so`? If `libblitbuffer.so` cannot be loaded koreader will just fallback to the original lua blitbuffer as in the pre-1401 versions.

**Comment by poire-z** [comment]
I did remove libblitbuffer.so , and rebooted after that, and the behaviour described above is still there :|

**Comment by poire-z** [comment]
I just installed 1400, copied blitbuffer.lua someplace else, installed 1425, replaced blitbuffer.lua with the 1400 one, thinking it could work, but when i toggle night mode, it crashes:
`luajit-launcher: Failed to run script: ffi/framebuffer_android.lua:50: 'struct BlitBufferRGB16' has no member named 'invertblitFrom'`

**Comment by chrox** [comment]
```diff
diff --git a/ffi/framebuffer_android.lua b/ffi/framebuffer_android.lua
index ab29fb9..b4731ae 100644
--- a/ffi/framebuffer_android.lua
+++ b/ffi/framebuffer_android.lua
@@ -46,7 +46,11 @@ function framebuffer:refreshFullImp()
         -- adapt to possible rotation changes
         bb:setRotation(ext_bb:getRotation())

-        bb:blitFrom(ext_bb)
+        if ext_bb:getInverse() == 1 then
+            bb:invertblitFrom(ext_bb)
+        else
+            bb:blitFrom(ext_bb)
+        end
     end

     android.lib.ANativeWindow_unlockAndPost(android.app.window);
```
Could you try also reverting this patch? Btw, the blitbuffer of you phone is BlitBufferRGB16 not BlitBufferRGB32?

**Comment by poire-z** [comment]
> Btw, the blitbuffer of you phone is BlitBufferRGB16 not BlitBufferRGB32?

I guess it was the document blitbuffer, credocument uses RGB16 (in color mode). I tried toggling night mode with a PDF opened (uses RGB32): still same behaviour. I previously tried with color mode enabled or disabled: same behaviour.

> Could you try also reverting this patch? 

Yep, this solves the problem ! And nightmode works, and can be toggled. With both a pdf or an epub. With color mode enabled or disabled.
(with libblitbuffer.so present, it was reinstalled when i installed 1401 and 1425).

**Comment by gerroon** [comment]
I just tested it crashes on Lineageos Nougat as well. So it is not inkbook only I guess.

**Comment by gerroon** [comment]
Is the patch in ? Shall I try with the latest nightly?

**Comment by poire-z** [comment]
Not yet. Dunno if the above patch reverting is the solution, or was just a step in the understanding of the problem.

**Comment by gerroon** [comment]
Any word on this?

**Comment by chrox** [comment]
I probably will have time to look into this issue this weekend.

**Comment by gerroon** [comment]
Thanks

**Comment by gerroon** [comment]
I tried the latest nightly on LineageOS 7.1 tablet and Lollipop 5.1 Phone. It crashes on the tablet but not the phone, weird.

**Comment by gerroon** [comment]
HI

I tested 1438. It does not crash on Nougat and Lollipop but it still crashes on my Inkbook.

**Comment by gerroon** [comment]
Hi

I tested 1451 and it still crashes Inkbook. However regular android devices are not crashing with night mode. It must be something about android 4 vs newer ones.

**Comment by poire-z** [comment]
@chrox : there is another solution than your test patch above, which may be the right one if you want to keep using your cblitbluffer's `invertblitFrom()`:
In https://github.com/koreader/koreader-base/blob/65856a78437abed39f38c733c1ad03b2b2d90d70/ffi/framebuffer_android.lua#L42-L54 , just remove line 45 `bb:setInverse(ext_bb:getInverse())`, which may be cancelling (or worse) what you're doing now a few lines after
(line 45 is from your 2014's https://github.com/koreader/koreader-base/commit/edca43c5f175baf8f8ac853b83e9eee614489aa2)

**Comment by gerroon** [comment]
@chrox yeah please do what @poire-z says :) We need a fix

**Comment by poire-z** [comment]
@Frenzie : any comment about the above suggestion for fixing this nightmode problem some of us have? (Don't you have any problem with nightmode on your android emulator or devices?)

**Comment by Frenzie** [comment]
@poire-z I can confirm the crash. I'll check up on your fix shortly.

**Comment by Frenzie** [comment]
@poire-z From a quick check it looks like getting rid of L45 still crashes, while @chrox' test patch effectively kills night mode. That's on the API 23 (Android 6) emulator.

**Comment by poire-z** [comment]
Strange.
I had a quick re-check on my android 6.0.1 phone with nightly 1503 from earlier this week:
- Toggling night mode did not messed up like it used to do, and it did not crash: it just did nothing :) May be a side effect of the cblitbuffer fixes from some weeks ago...
- Then, commenting out line 45 made night mode work (no crash for me).

How does your emulator do with current master and no patch at all?

**Comment by Frenzie** [comment]
I described current master.

**Comment by gerroon** [comment]
The crash happens only on my Inkbook (kitkat). It used to crash all my android devices (lollipop and up)

**Comment by Frenzie** [comment]
It's probably a relatively simple typo or logic error somewhere but nothing jumps out at me. (Especially because it doesn't seem to occur in the emulator.)

**Comment by gerroon** [comment]
It seems to be isolated to Inkbook now, in the past it was crashing all of my android devices but lollipop and nougat devices do not have the issue for a while.

**Comment by gerroon** [comment]
HI any ideas about the crash :) Just checking. thnx

**Comment by gerroon** [comment]
This crash still exists in the release koreader-beta-20180314

**Comment by gerroon** [comment]
Do we have any hope for this issue?

**Comment by Frenzie** [comment]
Um, I fixed it last week. :-p

**Comment by gerroon** [comment]
Ok let me try it then. Thanks for the update.

**Comment by gerroon** [comment]
Ok I just tested, it seemed to be fixed. I wil test it more later,

thanks
