### ISSUE TITLE
[Feature Request] cbt support

### ISSUE THREAD

**Issue by Q3CPMA** [koreader/koreader#3533]
Hello,
I'm becoming really interested in this because the official OS/reader is really missing navigation by folders and cbt (tar) support. Looks like the better navigation is already here, so I wondered if cbt support might be possible. To give an idea of the reason to choose cbt over cbz:
- Test file: 332MB archive with 145 images. The `store` method is forced for the cbz here.
- A "modern" amd64 machine (AMD FX8350 and 1600MHz DDR3 RAM)
```
unzip *v05*.cbz -d /tmp/test  1.75s user 0.20s system 99% cpu 1.948 total
tar -xf *v05*.cbt -C /tmp/test  0.00s user 0.20s system 99% cpu 0.209 total
```

On a weak device like most ereaders, the difference is really here (even if I resize, grayscale and reduce depth).

**Comment by TnS-hun** [comment]
I think the latest version of MuPDF supports cbt. Updating MuPDF in KOReader is in progress, see #3519.

After that it will be a [single line](https://github.com/koreader/koreader/blob/master/frontend/document/pdfdocument.lua#L239) addition to enable cbts in KOReader.

**Comment by Q3CPMA** [comment]
I see, thanks for the fast answer.

**Comment by Frenzie** [comment]
Regardless whether we're dealing with JPEG, PNG or GIF, trying to add extra compression on those formats is just plain stupid. They *are* the compression. As such an uncompressed TAR archive makes an awful lot of sense, but I suspect you wouldn't get such a major difference with plain 0% compression ZIP?

**Comment by Q3CPMA** [comment]
Yeah, store is no compression at all. I don't understand the difference myself, but it's here.
