### ISSUE TITLE
PB 626: Unable to launch - unrecognized PocketBook model

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#3536]
* KOReader version: v2015.11-1370-g5ee6c01
* Device: PocketBook 626 with software E626.5.14.1227

#### Issue
Koreader did not start due to unrecognized PocketBook model. I have revert it back to previous version (v2015.11-1287-g5a2c8e4) and everything is OK.

#### Steps to reproduce
Simply copy extracted files from archive file koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1370-g5ee6c01.zip to PB and try to start Koreader

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/1532389/crash.log)

`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Fixed by #3472. Please try a newer nightly from http://build.koreader.rocks/download/nightly/ :-)
