### ISSUE TITLE
The dictionary can not look up words

### ISSUE THREAD

**Issue by terry0001** [koreader/koreader#3538]
* KOReader version:V2015.11-1370-g5ee6c01
* Device: Kobo aura one 

#### Issue
The dictionary can not look up words. it shows " No definition found".
I have installed Stardict format dictionary in data/dict, but it doesn't work.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Unfortunately that's a known issue on too new Kobo firmware.

https://github.com/koreader/koreader/issues/3302

**Comment by terry0001** [comment]
thanks,
will it be improve in next update?

**Comment by Frenzie** [comment]
Not easily as it's unclear what the problem is (except something in the toolchain). But you can easily replace the sdcv executable yourself. :-)
