### ISSUE TITLE
Open random book

### ISSUE THREAD

**Issue by hugomilan** [koreader/koreader#3543]
* KOReader version: v2015.11-1428-g8886e16
* Device: Kobo Aura HD

#### Suggestion

I have been using koreader for about 2 years to read research papers in PDF. Turns out I have a lot of papers on my device and, sometimes, I'm not sure of what paper to read. That would be great if koreader had the option to open a random paper from the folder you are in (or even from any location in the device).

**Comment by robert00s** [comment]
Question. Only unread books or all books should be open from current folder?

**Comment by hugomilan** [comment]
I'm sorry I missed your first question but I think that only unread books should be selected.

Your implementation looks nice 👍
