### ISSUE TITLE
KOReader neither opening books from PocketBook default file browser nor appearing in the "Open With" dialogue

### ISSUE THREAD

**Issue by KitezhGrad** [koreader/koreader#3544]
* KOReader version: koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1370-g5ee6c01.zip
* Device: PocketBook 623

**Issue**

KOReader works fine if I launch it from the Applications menu, then select a book from KOReader's internal browser. 

However, KOReader doesn't open books from the PocketBook Library interface (instead, they are opened with AdobeViewer or fbreader, the pre-installed reader programs on PB 623).
Also, KOReader doesn't appear in the "Open with" dialogue along with AdobeViewer and fbreader.

**Steps to reproduce**

1. Go into your PocketBook Library
2. Long press on a book -> Open with ->
3. _**KOReader doesn't appear in the "Open with" dialogue along with AdobeViewer and fbreader.**_
4. Close the "Open with" dialogue and return to the PocketBook Libary.
5. Click on any book
6. **_It opens with AdobeViewer or fbreader._**

**crash.log**
[crash.log](https://github.com/koreader/koreader/files/1547264/crash.log)

**Comment by mk-f** [comment]
These issues are both related to the PB-Firmware and not KOReader directly:

PB decides which file-types are opened by which app via [system/config/extensions.cfg](https://github.com/koreader/koreader/blob/15ec47d7e019c40013c5440c62862a751e6f8733/platform/pocketbook/extensions.cfg): When installing KOReader, it will set itself as default-App for most extensions.

In the past ``extensions.cfg`` was parsed somehow by the PB-firmware and the "Open With..."-Dialog was updated accordingly. **This is not the case for newer Firmware-Versions, leaving you only with AdobeViewer and fbreader when using "Open With..."**. KOReader is not able to modify this behavior.

To make matters worse, if you open a book via the "Open With..."-Dialog, (e.g for comparing how fbreader renders a certain book in contrast to KOReader) another file ``system/config/handlers.cfg`` is created, which tracks which book was opened by which app last _and makes this the default for the book in question_. As KOReader is missing from the "Open With..."-Dialog in newer firmware-versions there is no way via the GUI to make it the default again. As an workaround you can delete or modify ``system/config/handlers.cfg`` by hand.

In the future KOReader may modify ``handlers.cfg`` by its self when opening a book via its internal library.

**Comment by KitezhGrad** [comment]
> In the future KOReader may modify `handlers.cfg` itself when opening a book via its internal library.

Or better yet, KOReader should load the list of filenames from the KOReader home directory (all subfolders included) and make a respective entry for each of the files in `handlers.cfg`. 
Also, KOReader should detect the new files put into the home directory and create an entry in  `handlers.cfg` for each of them.

**Comment by mk-f** [comment]
Can you explain why you think that this would be a good idea? There should be no entries in ``handlers.cfg`` if one never used "Open With..." on a book, and if one did the chances are high that he/she  actually wants to use another reader-app. Files with no ``handlers.cfg``-entry will just default to KOReader if ``extensions.cfg`` was not changed.

**Comment by KitezhGrad** [comment]
> Files with no handlers.cfg-entry will just default to KOReader if `extensions.cfg` was not changed.

In my case, the books I had never opened default to AdobeViewer, not KOReader.

**Comment by mk-f** [comment]
Okay, that should not happen. Did you modify the ``extensions.cfg`` in any way? And does a ``handlers.cfg`` actually exist?

I see from the ``crash.log`` that your firmware, albeit being the newest for your device, is rather old compared to newer PockeBook-devices. It might be that this never worked as expected on devices with a firmware-level < 5.  I just own a Inkpad 2 and can't reproduce this behavior.

Maybe @chrox knows something on this issue.

**Comment by KitezhGrad** [comment]
> Did you modify the `extensions.cfg` in any way? 
No.

> And does a `handlers.cfg` actually exist?
Yes.

**Comment by mk-f** [comment]
... And it works correctly if you insert a entry for the book in question to ``handlers.cfg``?

**Comment by KitezhGrad** [comment]
I deleted `handlers.cfg` and after deleting it the books still default to AdobeViewer.

**Comment by KitezhGrad** [comment]
@mk-f Does KOReader work perfectly on Inkpad 2?

**Comment by mk-f** [comment]
Good enough that i actually use it for reading. There are some minor annoyances like .sdr-directories showing up in the native library. And than is there the issue that PB deep-sleeps while you don't press anything (https://github.com/koreader/koreader/issues/3561), leading to somewhat sluggish performance (especially in menus or when rotating the view). This would be theoretically fixable, but i don't have time for it at the moment.

**Comment by KitezhGrad** [comment]
@mk-f What about highlighting and Evernote sync? Do these work well?

**Comment by Frenzie** [comment]
@KitezhGrad In what sense? I doubt it's any better or worse on PocketBook specifically. Highlighting works well; don't really know about Evernote.

**Comment by svatas** [comment]
So I found working solution. There is special script. You can find it here - https://github.com/Lighting/Setup-openwith

The ocumentation is completely in russian but with help of Google Translator I found, how to use it. When the script is installed, the menu is in english, no fear of russian. Also it is integrated to menu and the language is the languag you have setup in your pocketbook - mine is in Czech language.

And it is working! I can associate PDF files with KOreader and everything is working as expected. Maybe this is again good tip what to implement to KOreader itself..

**Comment by pazos** [comment]
Fixed in #6617

**Comment by TimaSv-Uk** [comment]
PocketBook Touch Lux 4 

At first KOReader did not apear as an option "Open with" on my PocketBook.

How how i made KOReader open books by default: on launch of reader, from main menu, and apear in "Open with" after long press on book.

Open KOReader on your device ->
Open top menu ->
Click "gear" looking icon ->
Tap "Devises" option -> 
Tap "Associate file extentions" ->
Chose formats you want koreader to open and check the boxes ->
Return to pocketbook main screan and KOReader will apear in "Open with" after long press on book (given that books in previosly selected format)
