### ISSUE TITLE
Add option to automatically open the next file after reaching the last page of a book

### ISSUE THREAD

**Issue by onaka-itai** [koreader/koreader#3545]
Most releases in the comic book/manga category are packed by chapter, which range from four to fifty pages. Usually the naming scheme is something like this:

- Comic Book v01 c01.cbz
- Comic Book v01 c02.cbz
- Comic Book v01 c03.cbz
- Comic Book v02 c04.cbz
- and so on and so forth

It would be really convenient to add an option to automatically open the next file in the directory if the user does a "next page" swipe in the last page of the current file. PerfectViewer (Android) has something like this and makes reading across separate chapters very fluid.

**Comment by Frenzie** [comment]
I'm pretty sure this is a duplicate, though I can't quickly find it atm.

**Comment by onaka-itai** [comment]
Are you perhaps referring to #2007? It's possible to unzip and recompress chapters into a single zip/cbz but it would be rather tedious for large collections.

**Comment by Frenzie** [comment]
No, I forgot about that entirely, although it is technically also a duplicate. :-)

While looking for it I found [this](https://github.com/ad1217/koreader/commit/e6c965a459bb34c85e79d2fdde8323b8c3c6655a) somewhat hackish implementation ([via](https://github.com/koreader/koreader/issues/1235#issuecomment-67760113)) but that's not what I was referring to either. So I'll remove the duplicate label for now.

**Comment by tomatosoupcan** [comment]
I'd also be interested in functionality along these lines. Bit of a pain currently to keep hitting close on the end card, swipe down from top, return to browser, and then go into the next file every 15 pages or so.

**Comment by KenMaltby** [comment]
Might be something that could work for series, as well.  If it were working from data within the file title, the user would have control over the results.  User templating?

**Comment by robert00s** [comment]
Done in #3943
