### ISSUE TITLE
Progress Sync push error

### ISSUE THREAD

**Issue by dowiew** [koreader/koreader#3548]
* KOReader version: v2015.11-1428
* Device: Kindle and Android

#### Issue
Progress sync / Push from this device - returns "Something went wrong...".
Logout+Login to the server works ok.
Pull progress seems to work as well but pulls an old position.

Everything worked fine a week ago.

**Comment by Frenzie** [comment]
I assume it should be solved now. All disk space was taken by the nightly builds. We need a better auto-cleanup I'm afraid.

**Comment by dowiew** [comment]
Yes, it works again. Thank you.

**Comment by dowiew** [comment]
Progress sync not working again... @Frenzie any help?

**Comment by Frenzie** [comment]
I'm afraid I don't see any issues. Incidentally, the particular issue that caused a problem last time can't occur again because I set up a cleaning cron job.

**Comment by dowiew** [comment]
Indeed, resetting my Android phone helped... All the other networked apps worked fine so I have not suspected that kind of an issue.
Sorry for troubling you and thank you so much for your great work.
