### ISSUE TITLE
Expand selection for dictionary lookup

### ISSUE THREAD

**Issue by rtega** [koreader/koreader#3557]
* KOReader version: v2015.11 stable
* Device: kobo glo HD

#### Issue
I can't expand a selection for the dictionary lookup. This is particularly a problem with Japanese texts where one or two characters get selected.

#### Steps to reproduce
- Open up any Japanese text with any Japanese stardict dictionary.
- Try to select a full Japanese word

**Comment by rtega** [comment]
Found out how to do it by myself. Could someone add that to the tips and tricks section or somewhere in the wiki?

**Comment by Frenzie** [comment]
You could add it yourself if you'd like as well. :-) You mean hold & drag? That's fairly standard afaik.

**Comment by Frenzie** [comment]
I added the following phrase to https://github.com/koreader/koreader/wiki/Dictionary-support

> All you need to do is hold on a word, or hold and drag to select a phrase.

Do you think that's clear?

**Comment by KenMaltby** [comment]
to select a phrase or multiple words

**Comment by rtega** [comment]
I would also add Ken's suggestion. Thanks!

**Comment by Frenzie** [comment]
Alright, added. I'll close this now then. :-)

**Comment by rtega** [comment]
Thanks!

2018-01-08 12:25 GMT+01:00 Frans de Jonge <notifications@github.com>:
