### ISSUE TITLE
Support Kobo Aura H20 Edition 2

### ISSUE THREAD

**Issue by gramster** [koreader/koreader#3559]
* KOReader version:
* Device: Kobo Aura H20 Edition 2

#### Issue

Progress on getting koReader to work on these devices seems to have stalled (forum thread: https://www.mobileread.com/forums/showthread.php?t=291940). pbChess and KSM are both working so they are not holding up progress.

#### Steps to reproduce

Install KSM and koReader. Launch koReader from KSM. Note that there is no response to touch events.

**Comment by cas--** [comment]
Latest nightlies now work with H2O Ed2, tested this version: http://build.koreader.rocks/download/nightly/v2015.11-1546-gd0130ae/

**Comment by Frenzie** [comment]
Right, I can close this.
