### ISSUE TITLE
PocketBook: suspension and timer-behaviour

### ISSUE THREAD

**Issue by mk-f** [koreader/koreader#3561]
While dealing with https://github.com/koreader/koreader/issues/3419 I noticed that at least the Inkpad 2 does a real suspend approx. two seconds after the last key- or touch-event if certain conditions are met*. That means no [BackgroundRunner-Tasks](https://github.com/koreader/koreader/tree/a16c500ac745ed956f4afa6122ddd3b656e22829/plugins/backgroundrunner.koplugin), no [UIManager:scheduleIn()-Timers](https://github.com/koreader/koreader/blob/a16c500ac745ed956f4afa6122ddd3b656e22829/frontend/ui/uimanager.lua#L292) etc, leading to various issues like 

- https://github.com/koreader/koreader/issues/3419 (suspend while loading a book)
- Display glitches:  
  - reader suspends while in a page-redraw
  - display elements not updated (e.g. statusbar-time)
  - screensaver sometimes does not show the title-page because the redraw comes too late
- unresponsiveness in menus as wake-up, albeit being fast, is noticeable
- "unexpected" keypresses, as multiple touches while in suspend are not executed momentarily but seconds later in succession when the reader woke up.
- possible malbehaviour with plugins which depend on timed tasks.

*If the reader is connected to Wifi or USB the issues do not occur because auto-suspend does for some reason not kick in.

Most of the issues are just annoying and may be overlooked as bad performance (and are 'fixed' on the next key-/touch-event). Nevertheless i am a bit surprised that this has never come up before, leaving me wondering if it is a model- or firmware-specific issue.

So I am interested if other PB-users experience the same (**please post you Firmware-Version**). Regarding possible solutions i am tempted to disable the suspension completely, but this will affect battery-time quite a bit. An other way would be to wrap time-critical sections in ``setSuspendState()``-blocks disabling and re-enabling the suspension if needed.

**Comment by Frenzie** [comment]
Pinging @ersi @KitezhGrad @NicolasPetton @iamjustaguest @Maradar @Taranchul @mwozny123 @patrikmusic @marmistrz @druss67

**Comment by mwozny123** [comment]
From > year I don't own Pb. Don't remember major problems in this area, in touch lux 3

**Comment by marmistrz** [comment]
I don't have a PB anymore. I do have problems with power management ob my inkbook, I'll report them after xmas

**Comment by patrikmusic** [comment]
Hi, I do have PB Inkpad, however it is the first model :( On mine everything works fine except the highlighting. Koreader stops working after while and all my highlights are gone. I resolved the problem in a way, that I don´t do any higlights anymore :)

**Comment by mk-f** [comment]
@patrikmusic may i ask which firmware you are running?

**Comment by patrikmusic** [comment]
I think that's the latestest one. It says U840.5.15.172

**Comment by mk-f** [comment]
@patrikmusic so does mine. As the Inkpad 1 and Inkpad 2 are nearly identical i would be happy if you could try the following:

1.  Disconnect the PB from USB and Wifi if connected via the PB-menu, disable sync, **disable Standby (Settings -> Saving Power -> Power off after set to Off)**
2.  Power off the PB completely and restart it again
3.  Open a Book with KOReader
4.  In the KOReader Top-Menu set: 
    - Statusbar -> Current time
    - Statusbar -> Auto refresh time
5.  In the KOReader Bottom-Menu set:
    - Progress Bar full
6.  Exit and open KOReader once again.

You should now see the time at the bottom of each page, it should update automatically. Notice the time, and than let it just sit there for more than 10 Minutes without touching it. Notice the time again. 

In my case the time updates successfully in the first minute, than four minutes later, and than stops updating all together. This is reproducible on my end, and the logs reflect the the PB wakes up this two times for some reason and than stays in suspend till the next Button-/Touch-Event. 

The powerbutton of the Inkpad 2 glows if the Reader is active, i don't know if this is the case for the Inkpad 1. If so, you should be able to see when the Reader suspends (when the button stops glowing).

**Comment by patrikmusic** [comment]
I don't have auto refresh time in the status bar. My time stays the same. It refreshes with page turning. There also isn't glowing powerbutton. PB 1 is without diods.

**Comment by mk-f** [comment]
Thanks for checking.

> I don't have auto refresh time in the status bar

But you enabled 'Auto refresh time'?

**Comment by patrikmusic** [comment]
That's what I am speaking, I can't find it in the menu...

**Comment by iamjustaguest** [comment]
- Pocketbook Touch HD, FW 631_U_5.16_579
- Koreader Version: v2015.11-1436

My observations so far:

Time in the status bar don't update, it refreshes with page turning or other menu actions.
Yes, auto refresh time is enabled.

Also i have a completely white page after resuming from sleep (i use a sleep cover).

Touch HD have a LED powerbutton, it goes off after approx one second after last actions.

**Comment by mk-f** [comment]
@iamjustaguest: Thanks for testing this. The LED going off after ~1sec sounds a lot like the suspend-issue i am experiencing.

I also have a blank page after suspending since https://github.com/koreader/koreader/pull/3535. PR https://github.com/koreader/koreader/pull/3568 will fix this by side effect.
