### ISSUE TITLE
tried MuPdf for epub, no CJK fonts

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#3564]
* KOReader version: after Mupdf update
* Device: emulator

#### Issue
Played with updated mupdf engine, turns out it can not show CJK characters in Epubs. No error message and I can select the empty character and dictionary will show the correct character.
Since there is a patch to mupdf, maybe something is missing there.

**Comment by TnS-hun** [comment]
I could reproduce this issue with these files:
https://ghostscript.com/~tor/epub-tests/ManyLang.epub
https://ghostscript.com/~tor/epub-tests/unitest.epub
