### ISSUE TITLE
Dictionary lookup not working even with old SDCV file

### ISSUE THREAD

**Issue by ko2017** [koreader/koreader#3566]
* KOReader version: nightly v2015.11-1439-g1d1b005 (28/12/17)
* Device: Kobo Aura H20 (1st edition)

#### Issue

I know already that this issue exists and have seen the workaround on other issue threads: make sure to use an old version of the SDCV file, which now seems to have stopped working for me as of the last couple of days.

Is this a new problem and does anyone else have it? I have tried a couple of times with both new and old SDCV, older KoReader nightly by a few days etc. but I can't get my dictionary to work anymore (it was working fine, my dictionaries are currently installed and everything seems normal on the surface of it.)  

All I have is "No definition found" when I try to use the dictionary function.

Many thanks to the developers of KoReader for their software!

**Comment by ko2017** [comment]
Hello,
Beg your pardon, I revisited this today and after a full refresh of KoReader the dictionary now works. But the old bug still stands - I have to use the old SDCV file in order to make it work.
Many thanks, but this can be closed

**Comment by Frenzie** [comment]
The OTA update will overwrite sdcv. Maybe that happened?
