### ISSUE TITLE
Does not refresh in Boox Note

### ISSUE THREAD

**Issue by chenxingqun** [koreader/koreader#3567]
* KOReader version: All
* Device: Boox Note eink reader, Android 6

#### Issue
Does not refresh. 
I'm a beta tester of the forthcoming eink reader Onyx Boox Note, which has android 6. When I open koreader, it just shows the first screen. 
Though the app is running in fact, but the display never refreshes.
One engineer from Onyx Boox said it was because "Koreader uses native activity but not normal framewok". 
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Would you happen to know what normal framework means in this context?

**Comment by chenxingqun** [comment]
No I don't. But I notice that there is same issue in #3517.
https://github.com/koreader/koreader/issues/3517
If I force the screen to refresh, then koreader does display rightly.

**Comment by chenxingqun** [comment]
I see that KOreader refreshes in A2 display mode, with very bad display quality.

**Comment by civalin** [comment]
The same problem on Boox Max 2 (Android 6)

Koreader can work, not crash, just would not update the screen at "normal" display mode. (but, I can see correct screen after use hardware button to force refresh)

"A2" display mode are OK too. It's really strange...

**Comment by Frenzie** [comment]
Btw, I found https://github.com/onyx-intl/OnyxAndroidSample/blob/8b166ac604b48fb67c124957cd5432240c7050fd/doc/EPD-Screen-Update.md

**Comment by pazos** [comment]
@chenxingqun @civalin, could you please try https://github.com/koreader/koreader/issues/4430#issuecomment-450594508.

Closing this issue as a duplicate #4430

**Comment by pazos** [comment]
@chenxingqun @visig9: please try the einktest.apk from the releases page. I think that your device is based on the freescale platform (like tolinos) but I'm not sure.

**Comment by visig9** [comment]
@pazos Thanks for notice. But I already refund the MAX 2 so cannot test now, sorry for that and so happy to see those nice progress.

**Comment by pazos** [comment]
closing this issue, you can track progress in #3517
