### ISSUE TITLE
Not possible to scroll the Review text box 

### ISSUE THREAD

**Issue by alexconst** [koreader/koreader#3574]
* KOReader version: [nightly-20171023](https://github.com/koreader/koreader/releases/tag/v2017-10-23-nightly)
* Device: Kobo Aura H2O

#### Issue

Not possible to scroll the "review" text box when editing it.
For all purposes this makes it impossible to add new text to it.

#### Steps to reproduce

- Write a review for a book. It should be long enough (300 characters or more should do the trick). Save it. Close it.
- From the main menu tap "Book Status"
- Tap the review text box to edit it.
- Try to append new text to the review.

**Comment by robert00s** [comment]
Fixed by @poire-z  in #4084
