### ISSUE TITLE
http://build.koreader.rocks/ is down

### ISSUE THREAD

**Issue by enigma90** [koreader/koreader#3577]
It has been down for at least 3 days. Any alternative site for downloading latest updates? Thanks.

**Comment by Frenzie** [comment]
Please report, don't look for alternatives. :-)

(You can always get nightly builds straight from GitLab, but generally I would advise sticking with tagged GitHub releases for regular use.)

**Comment by Frenzie** [comment]
Forgot to say, I restarted the server.
