### ISSUE TITLE
File manager - add option to view non-ebooks files

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#3578]
* KOReader version:
* Device:

#### Issue

Koreader file manager seems to be enought mature file browser to be able to handle operations also on non-ebooks files. 

I'd love to see  feature to disable only ebooks filter in koreader file browser.
Which means to add option to view also non - ebooks format e.g. Zips, rars, images etc.

**Comment by Frenzie** [comment]
Agreed, it makes sense. The biggest question is where to put it. In principle it's the same kind of thing as "Show hidden files" but just sticking it there might contribute to overflowing the settings menu.

![screenshot_2018-01-06_13-02-24](https://user-images.githubusercontent.com/202757/34639529-db3b990a-f2e1-11e7-82dd-3816c2f0deb1.png)

Technically there are a few more concerns since it's currently presumed that displayed files can be opened.

**Comment by KenMaltby** [comment]
Some images are listed and can be selected and will display (.png, for instance) as do the compressed .cbz files.  The other files that an advanced user or developer might wish to see or manipulate would be better handled by some sort of tiny Notepad++ plugin. 

If just viewing is the objective, what's on the device could mostly be viewed once they are added to the reader engine's supported list.  (as txt files for the script files, of course)

**Comment by robert00s** [comment]
What do you think about something like this?
`Show files` instead of `Show hidden files` and submenu

![koreader_066](https://user-images.githubusercontent.com/22982594/35167759-edbf713a-fd56-11e7-91f8-28bd92246c2d.png)
![koreader_067](https://user-images.githubusercontent.com/22982594/35167768-f3c94d12-fd56-11e7-9b00-aab714b942dc.png)

**Comment by Frenzie** [comment]
It does make sense, but at least on Kobo the show hidden files toggle is quite useful where it is. As such I might be more inclined to stick the all files vs documents under `Display mode` and to keep `Show hidden files` where it is. I'm not quite sure if that's the best generic option though.

**Comment by robert00s** [comment]
Or maybe we should split the filemanager settings into two parts:

![koreader_068](https://user-images.githubusercontent.com/22982594/35169331-74d4d46c-fd5c-11e7-880a-e334658e75ef.png)

![koreader_069](https://user-images.githubusercontent.com/22982594/35169332-7762d6ca-fd5c-11e7-9714-e7853d918f43.png)

**Comment by KenMaltby** [comment]
There is something to be said for having more space below the menu.  Then there is the "which tab was that under again" situation.  As KOReader keeps getting more sophisticated and user customizable, there will come a time when some attempt to shield the casual user from menu complexity will be needed.  Programs like calibre and Gimp2 can still be quite intimidating for new users, despite efforts to make them user friendly.  Closely related functions, in smaller hierarchal menus can be less overwhelming, as long as they are reached in a logical progression.  2 cents worth.

**Comment by KenMaltby** [comment]
The "Show documents and images"  might better be: "Show only documents and images"

That along with the division line, would suggest the logic that allows the "Show hidden files" to be something not included in "Show all files".

**Comment by mwoz123** [comment]
> Agreed, it makes sense. The biggest question is where to put it.

Maybe then setting screen #3602 should be upper in priority?  ;) I see one more vote here ;)

**Comment by Frenzie** [comment]
I'm afraid I don't see how that is supposed to make a difference as to the question of where to put it. The `Display` submenu and a "stand-alone setting screen" with a display tab or something along those lines are conceptually extremely similar. In this context a window is the same thing as a submenu with slightly different styling. The question remains exactly the same, and so too does the answer. Whatever it is you might want to change about the menu, it can be done in minutes without any talk of separate windows to obscure the point.

The question is about typology, meaning that `Show hidden files` and `Show all files` clearly belong together, versus relative importance. In other words, how frequently you're going to be toggling the setting. A possible way out of the dilemma is duplicating the setting in question. Once for frequency, and then again for logic. But a separate window is a presentational detail that doesn't affect how we answer the question.

Thunar decides to exclusively use (presumed) frequency:
<img src=https://user-images.githubusercontent.com/202757/35684846-652bd734-0768-11e8-8d73-2370c84cba15.png width=40%>
<img src=https://user-images.githubusercontent.com/202757/35684845-650ab928-0768-11e8-94b1-ee629add3d80.png width=50%>
Sort folders before files is a sorting option, but is presented separately from the other sorting options. Text besides icons is clearly the same principle as Icons/Detailed List/Compact List but is presented separately.

Windows Explorer takes an alternative approach with frequency plus duplication:
<img src=https://user-images.githubusercontent.com/202757/35684873-7a02a200-0768-11e8-9e45-69072f12b23d.png width=90%>
<img src=https://user-images.githubusercontent.com/202757/35684874-7a1e978a-0768-11e8-985a-280cccdd6bc7.png width=50%>

I've been thinking about adding a view menu to the file browser for a while now, but I would oppose hiding `Show hidden files` in a `Settings` window or submenu. The question is whether `Show all files` should be "hidden" or receive top billing. I'm inclined to think it should receive top billing.
