### ISSUE TITLE
No results on dictionary lookup

### ISSUE THREAD

**Issue by Mr5quid** [koreader/koreader#3579]
* KOReader version: v2015.11-1370-g5ee6c01
* Device: Kobo Glo HD (4.7.10413 [12/12/2017])

#### Issue

I installed three StartDict dictionaries from the link given on the Dictionary Support section : 
- Dictionnaires de l'Académie française : 8ème édition (acadfran)
- GNU Collaboratice International Dictionary of English (gcide)
- Online Etymology Dictionary (etymonline)

I have their respective folders (gcide, acadfran and etymonline) at /.adds/koreader/data/dict/. They have reading permissions (644 by default, did not change that) and all three are recognized from the Koreader Dictionary Settings menu (and of course enabled). Yet it is impossible for me to get any result : Selecting a word from a book never gives any results (it says 'No definition found') nor does performing a manual dictionary lookup. I tried disabling all dictionaries but one with no success. I tried really simple words too in both french and english to make sure I wasn't just being unlucky but with no success.

I found a similar issue but even though I didn't open them up (don't know how to open a .dict.dz in a readable manner) I'm fairly confident they do not contain chinese characters.

#### Steps to reproduce

For me it started from the first dict I tried to install which was the GNU Collaborative International Dictionary of English. I then installed the two others but none of them work for me. So I've never been able to get a dictionary result from KoReader.

Any insight would be appreciated :)

**Comment by KenMaltby** [comment]
I have the "stardict-dictd_www.dict.org_gcide-2.4.2" working on my AuraHD, (among 5 others).  The folder named as shown, is in the data/dict/ directory.  That folder has four files, an .ifo, a .dz, an .idx, and an idx.otf

**Comment by Frenzie** [comment]
Likely a duplicate of #3302 I'm afraid. Kobo made something incompatible with our toolchain in their newer firmware and someone has to update it.

/me bats eyes at @houqp

**Comment by Mr5quid** [comment]
I'm sorry I did not find all the related issues. My searches only brought me to the old issue about chinese characters.
I did some reading on the other issues and replaced my sdcv binary from /.adds/koreader/ with the one given by https://github.com/koreader/koreader/issues/3505 and my dictionaries are now working fine.

**Comment by gmadjara** [comment]
Mr5quid Can you please explain me step by step how to replace sdcv. Thanks.

**Comment by Frenzie** [comment]
It's the file sdcv in .adds/koreader
