### ISSUE TITLE
Screensaver request

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#3591]
* KOReader version: koreader-nightly-20180110
* Device: All

#### Issue
This is not an issue, more of a feature request

There are some new options for the screensaver which are very nice, but I could not find a way to achieve what I really want.
I 'm trying to have the book's cover as screensaver when the reader is suspended and also when the reader is powered off.
Ideally, it would be very nice to also have a message overlaid stating its state.
As the things are now (I think) I can have options for the suspended state but nothing for the powered off state, where I get a message only.
With the previous release I had the cover as screensaver also when I powered off.
There is also not an option for the cover with a message overlay.
Any thoughts?

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by poire-z** [comment]
See #3572 : you can manually set it to have cover when poweredoff.
Previously, you had manually set some options. The format/names have changed, but it's still a manual process.
(What you can't have now is cover + an overlay message)

**Comment by embryo10** [comment]
Yes, thank you for the heads up.
Was there a setting for that in the previous release?
I don't remember it..

**Comment by poire-z** [comment]
It used to be something like (you may still have it in your settings.reader.lua):
```lua
    ["poweroff_screensaver"] = {
        ["path"] = "/mnt/onboard/.adds/screensaver_off"
-- or ["message"] = "I'm powered off!",
    },

```

**Comment by embryo10** [comment]
It must be the latter, because looking at the older `settings.reader.lua`, can not find the `["poweroff_screensaver"]` key, not even the `["screensaver"]` one...
