### ISSUE TITLE
A problem with folder path in filemanager

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3594]
* KOReader version: v2015.11-1457-g7feea40
* Device: KA1

#### Issue
In the first picture the path is correct: '/mnt/onboard/.Bibliotek/Skönlitteratur'

But in the second picture something happened. The correct path is '/mnt/onboard/.Bibliotek/Skönlitteratur/Skönlitteratur (svenska)'.
![filemanager_2018-jan-11_213429](https://user-images.githubusercontent.com/32645430/34846779-947995d0-f719-11e7-96a0-ea63e9ed65b4.png)
![filemanager_2018-jan-11_213417](https://user-images.githubusercontent.com/32645430/34846797-9ecfd3fa-f719-11e7-9fff-9967efebb8ab.png)

**Comment by Frenzie** [comment]
Ah, very nice. :-P

Would you happen to know if this is new with https://github.com/koreader/koreader/pull/3565 ?

**Comment by gerhaher** [comment]
> Would you happen to know if this is new with #3565 ?

Yes, I believe it is. I downloaded your latest release today. I haven't seen it before.

**Comment by robert00s** [comment]
I think that is problem with string.reverse function and UTF8 encoding
https://github.com/koreader/koreader/blob/e3895102578ddb932d3eb44ff155a97cb325a5ec/frontend/apps/filemanager/filemanager.lua#L57

**Comment by poire-z** [comment]
We also have (so you could reverse the list and table.concat it back to a string):
https://github.com/koreader/koreader/blob/e3895102578ddb932d3eb44ff155a97cb325a5ec/frontend/util.lua#L133-L136
