### ISSUE TITLE
Does the KOReader support the vertical read for Chinese word?

### ISSUE THREAD

**Issue by ayeteng** [koreader/koreader#3597]
Hi designer,

Does KOReader support the vertical read for Chinese word?
Usually we will add the setting in the CSS file in the EPUB:
  writing-mode: vertical-rl;
  -epub-writing-mode: vertical-rl;
  -webkit-writing-mode: vertical-rl;
But I seems like KOReader doesn't support such setting? Can it be added?

Thanks.

**Comment by Frenzie** [comment]
@TnS-hun Would you happen to know if MuPDF does this? Long-term I'd like to look into engine selection (see https://github.com/koreader/koreader/issues/3345) but if there's a concrete advantage like this there'd be an extra incentive. ;-)

**Comment by TnS-hun** [comment]
I don't think MuPDF supports that. Those string can't be found in the latest version (except for some svg [generation](https://github.com/ArtifexSoftware/mupdf/blob/3df11d8c8cc3e6d638d0864d994219ac89f734ad/source/fitz/svg-device.c#L356) dev. feature).

And here is a comment from a related [bug](https://bugs.ghostscript.com/show_bug.cgi?id=695924#c16):

> We are not likely to ever support vertical writing in the EPUB viewer.

**Comment by Frenzie** [comment]
Sort of similar for crengine I'd say, unfortunately for the OP.

**Comment by NiLuJe** [comment]
Upstream "iisue", nothing we can do :).
