### ISSUE TITLE
Crashed when export note to Evernote

### ISSUE THREAD

**Issue by holyblade** [koreader/koreader#3600]
* KOReader version:v2015.11-1459-ge389510/  
* Device:Kobo H2O

#### Issue
Crashed when export note to Evernote
#### Steps to reproduce
Crashed when export note to Evernote
##### `crash.log` (if applicable)
```
./luajit: error loading module 'libluabpack' from file 'plugins/evernote.koplugin/lib/libluabpack.so':
	liblualongnumber.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0x0004d2e1
	[C]: in function 'require'
	plugins/evernote.koplugin/thrift/TBinaryProtocol.lua:21: in main chunk
	[C]: in function 'require'
	plugins/evernote.koplugin/EvernoteClient.lua:2: in main chunk
	[C]: in function 'require'
	plugins/evernote.koplugin/main.lua:361: in function 'exportClippings'
	plugins/evernote.koplugin/main.lua:301: in function 'exportCurrentNotes'
	plugins/evernote.koplugin/main.lua:120: in function 'action'
	frontend/ui/uimanager.lua:531: in function '_checkTasks'
	frontend/ui/uimanager.lua:703: in function 'handleInput'
	frontend/ui/uimanager.lua:789: in function 'run'
	./reader.lua:190: in main chunk
	[C]: at 0x00013fc5

**Comment by tulse215** [comment]
Having the same issue.
Is it possible to put a symlink to liblualongnumber.so file somewhere to fix the issue?

**Comment by gilali** [comment]
Having the same issue on my h2o2.
Here's my dirty patch 

`cp /mnt/onboard/.adds/koreader/plugins/evernote.koplugin/lib/liblualongnumber.so /mnt/onboard/.adds/koreader/. `

**Comment by tulse215** [comment]
Worked! Thanks a lot! =)

**Comment by NiLuJe** [comment]
Possibly an rpath issue, since lualongnumber is a DT_NEEDED of luabpack, but it's not in our LD_LIBRARY_PATH, and luabpack's rpath is empty.

**Comment by kobohobo** [comment]
Awesome, Im crossing my fingers as this would be one of my favorite features!

**Comment by NiLuJe** [comment]
Fixed it. Fix will land folded into a bunch of other crap later.
