### ISSUE TITLE
html dictionaries: every entry starts with 'm'

### ISSUE THREAD

**Issue by taosxx** [koreader/koreader#3606]
By adding the line ```sametypesequence=h``` in the corresponding ifo file I've enabled the html rendering for a few of my stardict dictionaries which looks really nice (I had the line removed a couple of years ago when koreader would still display all the html tags). Unfortunately, now every entry starts with 'm' which, as far as I remember, is the "start code" for meaning in stardict dictionary files. If I remove the line (or only the 'h') again, the 'm' disappears (together with the html formatting).
Edit: Just read in another article that 'm' implicitly means 'plain text'. So, just another case of an incorrectly formatted stardict dictionary?

**Comment by Frenzie** [comment]
> So, just another case of an incorrectly formatted stardict dictionary?

Sounds like it to me. There are a couple of simple heuristics I can think of that might be relatively safe. E.g., if there is a combination of something like `<i></i>` or `<b></b>`, which is fairly unlikely to occur naturally (except perhaps under a few select entries like _tag_ or _HTML_, or in some kind of technical dictionary), try stripping the `m` and treat it as HTML. Still, I strongly question if that would be KOReader's place — at least by default.

Note that @TnS-hun added a fix_html_func option, so in the same directory as your dictionary-name.ifo file you can create a dictionary-name.lua file to fix it up.

https://github.com/koreader/koreader/blob/e3895102578ddb932d3eb44ff155a97cb325a5ec/frontend/apps/reader/modules/readerdictionary.lua#L127

I'll ping @poire-z to provide a sample function file.

**Comment by poire-z** [comment]
I'm not sure I understand the question correctly, so I'll provide multiple answers :)

If you don't remember which dict that you have changed the `sametypesequence=h` to `sametypesequence=m`, you can just talk a look at the .dict file:
```
$ zcat PetitRobert2007_1.1.dict.dz | xxd | head
00000000: 3c64 6976 3e3c 6469 763e 3c44 4956 2073  <div><div><DIV s
00000010: 7479 6c65 3d22 6d61 7267 696e 2d74 6f70  tyle="margin-top
00000020: 3a20 3570 743b 206d 6172 6769 6e2d 6c65  : 5pt; margin-le
$ zcat dictd_www.dict.org_gcide.dict.dz | xxd | head
00000000: 6578 6368 616e 6765 205c 6578 2a63 6861  exchange \ex*cha
00000010: 6e67 6522 5c20 285b 655e 5d6b 732a 6368  nge"\ ([e^]ks*ch
00000020: 5b3d 615d 6e6a 2229 2c20 6e2e 205b 4f45  [=a]nj"), n. [OE
```
(I just realized I have more HTML dicts, XMLLittre for example, which has `sametypesequence=g`. It's a bit ugly if I changed it to `h`, as line feeds are lost)

If you have such an HTML dict and the display is bad and looks like text, it's probably that the HTML is not proper XHTML and MuPDF (used for rendering) does not like it.

In that case, if you really want it, know lua, have time... you can use the fix_html_func stuff mentionned above by @Frenzie , details and sample in #3585 (also see https://github.com/koreader/koreader/pull/3573#issuecomment-356908798 on how to... debug the dict html)

**Comment by taosxx** [comment]
The problem with the aforementioned dictionaries is not that they are using invalid or ugly (x)html. The problem is that:

1. they don't advertise that they're actually html dictionaries - they include perfectly fine (x)html (that looks great rendered with mupdf) but declare with a 'm' (instead of 'h' or 'g') preceding every definition entry in the .dict.dz that they contain plain text.
2. using 'sametypesequence=h' in the ifo file to enable html rendering is in conflict with the leading m/h/g/x/... in each definition entry because now the first character is treated as part of the definition so that koreader dictionary lookup also renders it in the first line.

So, that means for me either using the dictionary-name.lua to strip the superfluous (and in addition incorrect) leading 'm' or to find out which program/script was used to convert/create the stardict dictionary in the first place without including "sametypesequence=h" (or at least properly declaring 'h' instead of 'm') and fix its code.

**Comment by poire-z** [comment]
> the leading m/h/g/x/... in each definition entry because now the first character is treated as part of the definition

You mean that in some of your dicts, each definition starts with `m\n` or `h\n`, indicating what type of format the rest of the definition is ? And that there may be different kind in the same dict ?
That's not part of the spec https://github.com/huzheng001/stardict-3/blob/master/dict/doc/StarDictFileFormat, is it?
And in any case, with the tag cleanup for non `sametypesequence=h` dict, you should have seen this character at the start of your definition anyway.

**Comment by TnS-hun** [comment]
> Note that @TnS-hun added a fix_html_func option

That was  poire-z! :)

@taosxx: unfortunately sdcv doesn't report the type of the entries in its JSON output, so the sametypesequence=h line is used by KOReader to detect the type.

> using 'sametypesequence=h' in the ifo file to enable html rendering is in conflict with the leading m/h/g/x/... in each definition entry because now the first character is treated as part of the definition so that koreader dictionary lookup also renders it in the first line.

You can't add sametypesequence to an .ifo if it wasn't there originally.

The easiest solution is to use [Penelope](https://github.com/pettarin/penelope/) to convert your dictionaries from StarDict to StarDict (or StarDict to XML to StarDict if SD to SD doesn't work).

> And that there may be different kind in the same dict ?

That can happen, I've not seen such dictionary yet, but it's according to spec.

> If the sametypesequence option is set, it tells StarDict that each word's data in the .dict file will have the same sequence of datatypes.

**Comment by poire-z** [comment]
Oh, I see: https://github.com/huzheng001/stardict-3/blob/6a5b1d46c482bdf0dc0a262e298a9fd1c220dc07/dict/doc/StarDictFileFormat#L323-L326
So, sdcv strips this first character ? concatenate the multiple data ? gives back only the first?

**Comment by TnS-hun** [comment]
It looks like sdcv [concatenates](https://github.com/Dushistov/sdcv/blob/51db56f7e502ccf28a10cb412bc07123fbe6c372/src/libwrapper.cpp#L151-L153) all textual data into the result string and returns with the concatenated string.

**Comment by cramoisi** [comment]
@poire-z  where did you get this PetitRobert2007_1.1.dict ? i need it soooo much :)

**Comment by poire-z** [comment]
At the url mentionned in https://github.com/koreader/koreader/pull/3573#issuecomment-354959514 , where you can find other less interesting french dicts

**Comment by cramoisi** [comment]
Once i tried to convert the robert-dixel for amazon reader to kobo but it was too much time consuming for a not so great result

**Comment by taosxx** [comment]
> The easiest solution is to use Penelope to convert your dictionaries from StarDict to StarDict (or StarDict to XML to StarDict if SD to SD doesn't work).

I decided to use [pyglossary](https://github.com/ilius/pyglossary/tree/next) and manipulated its stardict plugin to correctly recognize the format type (html/text) of the input file and to actually write the compact stardict format without leading 'h' or 'm'. Not sure if the result is completely correct according to stardict spec, but it works (and as an unplanned by-product I now have a rough input plugin for mobi-styled xml that recognizes synonyms).

**Comment by cramoisi** [comment]
@poire-z : did you make something to your dict file to shows linefeed when a word is search and displayed within a book ? mine is without line break (it breaks at the border of the box but it's not nice).the sametypesequence is h .

**Comment by poire-z** [comment]
The HTML in this dict is really bad, and MuPDF fails rendering it, so KOReader feeds to it some nearly plain text version. But one can add some specific code to tweak the HTML and make it better before giving it to MuPDF.
See the ones I made for 3 french dicts at https://github.com/koreader/koreader/pull/3585#issuecomment-361203757

**Comment by cramoisi** [comment]
@poire-z  thanks !
I'm looking into it and it's very bad (and on one line). It needs a script to remove all < > " ' when they are in unknown html tags.

**Comment by Frenzie** [comment]
Closing since this information is now linked from the Wiki thanks to @AlanSP1.

https://github.com/koreader/koreader/wiki/Dictionary-support#html-encoding-within-stardict-dictionaries-supported
