### ISSUE TITLE
Sreensaver when I power off doesn't work anymore

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3610]
* KOReader version: v2015.11-1465-gd201c04
* Device: KA1

#### Issue
I use last book's cover as screensaver. 
It works fine when I put the device to sleep.

But when I power off the device, instead it looks like I get the "Leave screen as it is"-alternative with the "Powered off"-popup window.

**Comment by Frenzie** [comment]
Pinging @robert00s @poire-z since I don't really know the insides of the screensaver stuff.

**Comment by poire-z** [comment]
It was changed recently in #3572 (there's new manual settings to get the bookcover back).
Seems there are a few users bothered by the loss of the probable old default (cover + msg) (#3591, mobiread).
Dunno if we should make a specific case with a hybrid default for poweroff.

**Comment by gerhaher** [comment]
I tried this manual setting and it worked fine.

Thanks!

**Comment by AlanSP1** [comment]
Maybe default for power off should be same as for sleep. Probably for most people this would work. In instructions there could be description how to set up manually power off (and reboot) settings.

**Comment by poire-z** [comment]
> Maybe default for power off should be same as for sleep.

Yes, we could do that.
```lua
--- a/frontend/ui/screensaver.lua
+++ b/frontend/ui/screensaver.lua
@@ -148,6 +148,12 @@ function Screensaver:show(event, fallback_message)
     end
     local prefix = event and event.."_" or "" -- "", "poweroff_" or "reboot_"
     local screensaver_type = G_reader_settings:readSetting(prefix.."screensaver_type")
+    if prefix and not screensaver_type then
+        -- No manually added setting for poweroff/reboot, fallback to using the
+        -- same settings as for suspend that could be set via menus
+        screensaver_type = G_reader_settings:readSetting("screensaver_type")
+        prefix = ""
+    end
     if screensaver_type == nil then
         screensaver_type = "message"
     end
```
Should I PR that?

**Comment by Frenzie** [comment]
Sounds logical; go for it. ;-)
