### ISSUE TITLE
font-family in html dictionary .css

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#3611]
I have a couple dictionaries converted from mdict files that use .css.
That works fine for most .css commands with the new html dictionary option.
But I couldn't get something like `font-family: 'Open Sans'` to work (put font files in .adds/koreader/fonts/opensans on Kobo ereader).
Dictionaries look ok with the default font, just curious whether it is possible somehow to use font-family (maybe I need to change some other file to make koreader find the font?)

**Comment by poire-z** [comment]
KOReader does not tell MuPDF (the renderer for these HTML dict) which fonts are available (except for the main font and the fallback font).
But you could try what @baskerville suggested in https://www.mobileread.com/forums/showpost.php?p=3639997&postcount=63 , defining in your css a font name and giving the fullpath to the font file.

**Comment by alex125** [comment]
This works, except that some characters aren't displayed correctly. In particular the character `ˌ` used to indicate stress in pronunciation of the words is displayed as `>`. The character does exist in the Open Sans font (also tried DejaVu Sans Condensed, same issue) at the right position but is displayed correctly only for NotoSans.

**Comment by cramoisi** [comment]
@poire-z : according to @baskerville suggestion, could we strip a dictionary from all inline css and put them in the user.css ? If yes, It could be great. (do you know where to put user.css in koreader directories ?)

**Comment by poire-z** [comment]
You could strip (or more simply make them not interpreted by MuPDF) the inline css with something like that in the `<dictfilename>.lua`:
```lua
return function(html)
    -- html = html:gsub(' style=', ' zzztyle=')
    html = html:gsub(' [Ss][Tt][Yy][Ll][Ee]=', ' zzztyle=')
    return html
end
```
And your user.css should be alongside the `<dictfilename>.ifo` and `<dictfilename>.lua` and named `<dictfilename>.css`

**Comment by cramoisi** [comment]
@poire-z thanks a lot ! PM me on me mobileread if you're interested in a wip upgrade

**Comment by Frenzie** [comment]
Added the knowledge from https://github.com/koreader/koreader/issues/3611#issuecomment-361557060 to the wiki, closing now.
