### ISSUE TITLE
issue with <span> tag ?

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3613]
* KOReader version: 1459
* Device: gloHD

#### Issue
when a span tag is present in a text and the definition in the stylesheet regarding this span is correct, koreader display it with blank line before and after. It's often the case with footnotes.

first screen, it's correctly done and it's displayed like it should in calibre 
<img width="1269" alt="capture d ecran 2018-01-17 07 57 16" src="https://user-images.githubusercontent.com/28014131/35029838-0fad908e-fb5d-11e7-9ed2-de3bf9135947.png">

second screen  (sorry for the crappy shot)  there is line feeds before and after the span 
<img width="592" alt="capture d ecran 2018-01-17 08 00 28" src="https://user-images.githubusercontent.com/28014131/35029830-0af9cf9e-fb5d-11e7-8f1e-591458b28338.png">

**Comment by poire-z** [comment]
`<span>` works fine, I'm sure you have a lot more in your book that are displayed correctly inlined.
I'd be curious to see the css definitions of the css classes involved: `pcalibre pcalibre1 pcalibre2 pcalibre3 msonormalcxspmiddle msnoendnotereferenec`. It could be there are some combinations of styles that crengine does not support well and would consider some as adding a block element.
You could also try the toggle in the bottom menu "Embedded styles", which should get rid of the above styles and I'm quite sure that it would display as expected then (ok, you lose the other book formating, but that's just to prove the cause is the embedded classes above or not).

**Comment by cramoisi** [comment]
@poire-z  : yep, i looked through the css without seing anything obviously wrong but these calibre s***t are pretty annoying and I didn't take the time to test it toroughly. I asked this because I have the sensation this is not the first time that happens (but not based on evidence). When I disable the embeded style, all I got is a line feed, an indent like for a new paragraph (which is wrong too).

<img width="574" alt="capture d ecran 2018-01-17 13 41 21" src="https://user-images.githubusercontent.com/28014131/35043232-20ccee44-fb8c-11e7-9280-403ebc4e1dd7.png">

I will strip the css to the barbone to check this issue

**Comment by poire-z** [comment]
Any end word on this ?
> So, now, why the "disable embeded style" doesn't work is another question :)

and on why this didn't have any effect ? (it should ignore links to css files in the epub, and `style=` attributes in tags)

**Comment by cramoisi** [comment]
not really ;/ when I regex-remove all "calibre" stuff from the book, the display was ok. But disabling the embeded style has not the effect it should perhaps because some css inside epub.css in koreader (sometimes they conflict with the internal css, I had the case with the last modiano (which is a theatre play). Each name before text was between H2 tag so even with embeded styles enabled the epub.css make a page break before each line of dialogue. I took one hour to figure that yesterday. So I made a css.css empty to really test it. And then I notice since my last update i cannot connect to wifi anymore... (so i'm a bit fed up with this)

**Comment by poire-z** [comment]
Dunno, could be.
Your `page-break-before` observation is discussed in #2394.
As there was no consensus, I just added for myself, alongside the original koreader `epub.css` a `MY_epub.css`, a copy of it with just a line commented out:
```
h1, h2, h3, .title, .title1, .title2, .title3 {
        /* page-break-before: always; : commented out to avoid blank page at chapter page */
        page-break-inside: avoid;
        page-break-after: avoid;
}
```
so I can switch to it when I meet a book where this problem happens.
