### ISSUE TITLE
Fulltext search

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3616]
* KOReader version: v2015.11-1465-gd201c04
* Device: KA1

#### Issue
1. I miss an easy way to get back to the start position after a fulltext search. In nickel (if I remember correctly) you can do that by just a tap. Something like that would be a good enhancement. Today you need to check on which page you are, before you perform your search and then use "Go to".

EDIT: I just found "Go back to previous location". Well, I guess that was exactly what I just asked for. :-)

2. Sometimes the word you search for is hidden behind the little "search-window". If you want to read what's hidden you have to remove the search-window. But that means that you have to write down the word again if you want to continue the search. Annoying.
Nickel doesn't have this problem.

3. Finally some issues when you **step backwards (=when using this: '<')** during a search. 
If the search word appears several times on a page only one of them is greyish. (When you step forward all of them are greyish.)
If the search word is the first word on the page (in the upper left corner) you get stuck on the page. You have to use "|<" to go backwards.

**Comment by gerhaher** [comment]
> EDIT: I just found "Go back to previous location". Well, I guess that was exactly what I just asked for. :-)

No, it wasn't. :-)

If during a search you have looked at 20 pages, to get back to your start position you have to use "Go back to..." 20 times (if you don't remember where you were). 

Therefore it would be a great thing to have a "Go back to start position"-alternative alongside the stepping backward/forward buttons in the popup search window.

**Comment by Frenzie** [comment]
The main use of "Go back to previous location" is to follow a link to a footnote or endnote and then go back to where you came from.

**Comment by Eduardomb22** [comment]
> Sometimes the word you search for is hidden behind the little "search-window". If you want to read what's hidden you have to remove the search-window. But that means that you have to write down the word again if you want to continue the search. Annoying.

I agree

**Comment by poire-z** [comment]
> 2) Sometimes the word you search for is hidden behind the little "search-window". If you want to read what's hidden you have to remove the search-window. But that means that you have to write down the word again if you want to continue the search. Annoying.

This should be solved by #3636 .

> 1) I miss an easy way to get back to the start position after a fulltext search

And this by #3648 .
