### ISSUE TITLE
Problem with chart/table at Kindle

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#3623]
* KOReader version: v2015.11-1479-gdd00417
* Device: Kindle ppw3

#### Issue
This table/chart isn't showing properly in koreader. It does works fine in the reader I have at PC
PC
![table](https://user-images.githubusercontent.com/20425689/35183515-fc6fd652-fdce-11e7-846c-82560ab118d5.png)

KOreader

![reader_2018-jan-20_103340](https://user-images.githubusercontent.com/20425689/35183522-0b379332-fdcf-11e7-8852-3631c442b2b7.png)

I can provide the ebook if it is necessary.

**Comment by Eduardomb22** [comment]
I'm pretty sure that some older version of koreader was working fine, cause this isn't the first time I read this book.

**Comment by poire-z** [comment]
I assume it is epub & crengine related.
No change when toggling Embedded styles on/off ? Or top menu Styles > clear all, or chose another one (epub/htm).

Also, there's a bug in crengine (couldn't find my way around it) with tables and cache: most Wikipedia articles usually have a table at beginning (main dates, location, country, ancestors...). First time opening: this table is displayed fine. Next opening, when the cr3cache made on the first opening is used: the table is messed up, sometimes incomplete, sometimes invisible. It displays correctly after "Developer's options > Clear readers' caches".
So you may try this Clear readers's caches to see if it is that bug.

**Comment by Eduardomb22** [comment]
I've tried all the options you said and the problem persists. I have other ebooks with table and they work fine, maybe it is a problem with this one.

It is an epub book.

https://drive.google.com/open?id=1Yep3AriEWcMq4liw3xX_qAZyEVZt6Gkx

If you wanna take a look. I will appreciate. Thanks for the reply

**Comment by poire-z** [comment]
I had a look, and I guess it's really a cache problem. May be because the document is big, the cache is really used even on the first run.
If you make koreader use no crecache (with some caveats: it will use a lot of memory, which may crash on our small devices, see https://github.com/koreader/koreader/issues/3261#issuecomment-333065785), with:
```lua
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -52,7 +52,7 @@ function CreDocument:engineInit()
     if not engine_initialized then
         require "libs/libkoreader-cre"
         -- initialize cache
-        self:cacheInit()
+--        self:cacheInit()

         -- initialize hyph dictionaries
         cre.initHyphDict("./data/hyph/")
```
you get this correct display:

<kbd>![table_fine_when_no_crecache](https://user-images.githubusercontent.com/24273478/35184013-ca445b50-fdef-11e7-8ed3-fb01a069da48.png)</kbd>

May be you can check if that works on your device (with the risk of a crash, backup your settings), and use that as a temporary workaround for this book (dunno how we could deal with that in a generic way).

**Comment by poire-z** [comment]
@frankyifei : any idea about this crengine bug with tables and cache?
Here's a sample epub [francois.zip](https://github.com/koreader/koreader/files/1649264/francois.zip) (from https://fr.wikipedia.org/wiki/Fran%C3%A7ois_Ier_(roi_de_France)).
The file needs to be large enought for cache to be used. First opening: the table on the first pages is correct and displayed. Quit and re-open: cache is used, and this same table is messed up.

**Comment by Eduardomb22** [comment]
@poire-z I was pretty sure that this book worked fine in some other version of koreader and tested a few that I found at Wiki, the table is working fine at the version 1152
Do you if any change could bugged the table?

![reader_2018-jan-21_074039](https://user-images.githubusercontent.com/20425689/35192736-b8113964-fe7e-11e7-937d-5b2884d56f95.png)

**Comment by Eduardomb22** [comment]
And it isn't working @ 1287. Those are the ones I could test. Thanks for looking into the problem.

**Comment by Frenzie** [comment]
Thanks, I think that means this should be the changelog: https://github.com/koreader/koreader/compare/v2017.08.21-nightly...v2017.10.04-nightly

**Comment by poire-z** [comment]
I had a try with https://github.com/koreader/crengine/pull/86 (which solved crashes and other rendering problems) reverted:
With an empty cache, the table in your book display fine on first opening.
On next openings (with cache previously made), the table is still there, but a bit messed up (some cells are missing).
(For my wikipedia book, with or wihout this reverted, it is still messed up, but in subtile different ways).

**Comment by Eduardomb22** [comment]
Sometimes this happens (" On next openings (with cache previously made), the table is still there, but a bit messed up (some cells are missing.") , but reducing the size of the font fixs the problem. ;After that, I change the font back to the size I wanna and it is fine.

**Comment by Eduardomb22** [comment]
Is it possible to automatic clean up the cache after koreader exits?

**Comment by frankyifei** [comment]
I did not test this because the files in test suite are quite small, so no cache are generated. Some of my books with tables seems to be ok after first open.

**Comment by poire-z** [comment]
@Eduardomb22 : if you want that, you can just add a line in `frontend/document/credocument.lua`, so cache is cleaned on startup, and crengine then just recreate it:
```lua
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -45,6 +45,7 @@ function CreDocument:cacheInit()
     if lfs.attributes("./cr3cache", "mode") == "directory" then
         os.execute("rm -r ./cr3cache")
     end
+    require("ffi/util").purgeDir(DataStorage:getDataDir() .. "/cache/cr3cache")
     cre.initCache(DataStorage:getDataDir() .. "/cache/cr3cache", 1024*1024*32)
 end

```

The cache would still persists if you're just switching books while not exiting koreader.
You additionally can change the `1024*1024*32` to `0`: when a different book is opened, previous book cache is deleted to make room for the new one.

Doing such stuff genarally for all users will make opening large books slower.

**Comment by frankyifei** [comment]
https://github.com/koreader/crengine/pull/86 is not a good fix I should admit, it goes around the code that will crash the program but never really solve the problem from its root.

**Comment by Eduardomb22** [comment]
@poire-z, thanks for the help. It helped a lot

**Comment by poire-z** [comment]
Fixed by recent crengine commits.
