### ISSUE TITLE
linefeed with comma

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3629]
* KOReader version: 1483
* Device: gloHD

#### Issue
Got a wrong linefeed in a french translated novel, between a endash and a comma. First time I notice that but it's clearly wrong as a comma mustn't begin a new line.
I checked the book and there is no space between the en-dash and the comma in the source code.

<img width="334" alt="capture d ecran 2018-01-26 09 36 47" src="https://user-images.githubusercontent.com/28014131/35431364-770a386a-027c-11e8-9305-a56095a9a184.png">

It happens "only" (as far as I could check) when floating punctuation is enabled, as in the screenshot above :

<img width="549" alt="capture d ecran 2018-01-26 09 32 47" src="https://user-images.githubusercontent.com/28014131/35431234-f62038b2-027b-11e8-8621-b617dd6fee8c.png">

**Comment by cramoisi** [comment]
For the record, when I disable floating punctuation, there is clearly too much hyphenation in the text, like 4 ou 5 in a row when the rule says 3 max in a row. But I don't think there is a way to set that in the .pattern files.

**Comment by cramoisi** [comment]
and also, when floating punctuation is enabled and a en-dash is the last char on a line, the next line begins with a space (because there is one in the source) which must be ignored in this case.

**Comment by poire-z** [comment]
I guess the comma at start of line is no more since https://github.com/koreader/crengine/pull/237.
Not sure about the space before a e*dash :|
<kbd>![image](https://user-images.githubusercontent.com/24273478/47044426-739d8900-d190-11e8-854c-79decdd9a240.png)</kbd>

**Comment by cramoisi** [comment]
@poire-z i didn't notice it in my recent reading. Will look at that and give you feedback.
