### ISSUE TITLE
Screensaver Image Format?

### ISSUE THREAD

**Issue by tomatosoupcan** [koreader/koreader#3637]
* KOReader version: koreader-nightly-20180110
* Device: Kobo Aura One

**Comment by Frenzie** [comment]
There was/is a specific format? I'd expect any supported fileformat to work, including JPEG, PNG, GIF, and anything else I'm missing.

Pinging @robert00s @poire-z

**Comment by poire-z** [comment]
The usual formats are supported.
May be you are just surprised that the _file browser/directory chooser_ does not show image files - indeed, it just shows directories. And the nb of items are just the number of sub-directories in each directory.
So, if you have usual images in a directory, just chose it by holding on it, even if it says _0 items_.

**Comment by KenMaltby** [comment]
?? I have .png files showing in the File Browser.

**Comment by poire-z** [comment]
It's not our main File Browser, but it's little restricted brother:
https://github.com/koreader/koreader/blob/e7377cd20e352bf762cbf5d0cee09505c6df7b6a/frontend/ui/widget/pathchooser.lua#L7-L14

**Comment by tomatosoupcan** [comment]
You are correct, looks like it does work despite not listing out any files. For some reason that wasn't working on my old Kobo, but it working fine on my Aura One. Thanks.

**Comment by Frenzie** [comment]
@poire-z Does it also support `getCoverPageImage()` on any supported document? I don't really customize the screensaver feature but it seems like it'd make sense. :-P

**Comment by poire-z** [comment]
That's what it does when `screensaver_type == "cover"` :
https://github.com/koreader/koreader/blob/d714bd3aea94db062fad6324b117dbe026fce007/frontend/ui/screensaver.lua#L173-L179

**Comment by Frenzie** [comment]
Well sure, but I mean that one might always want a cover from document X without having to make a PNG or JPEG out of it.

**Comment by poire-z** [comment]
To be used when viewing document Y ?!
I don't personnally know any such lazy _one_ s :)
(And why only for cover? why not for any image in an epub, or any page in a pdf? So it could be a feature of ImageViewer - save that image in `screensaver_dir` - but then I'd be sad to waste one button space for such a rarely useful feature ala Windows - where for every image viewing, you have a button "use at desktop background" or similar).

**Comment by Frenzie** [comment]
Long press on image for more options. :-P

Anyway, it's not something I care about. Just an off-hand thought.

**Comment by KenMaltby** [comment]
I seem to remember suggesting that a long press on an image might also offer "Use as screensaver", but now that we have an option to "Leave screen as it is".  Not sure you can long-press the image to get it full page and then screensave that?

**Comment by poire-z** [comment]
Long press is currently assigned to refreshing screen (like small diagonal swipe in readers does), all the other gestures are taken for zooming/panning the image.
This zooming/panning is done with a "ui" refresh to be fast, but may cause remanence/dirty picture. Being able to refresh with a long Hold is nice to get your image (or zoomed part of image) clean again.

**Comment by KenMaltby** [comment]
If you flick the Power slider, with the screensaver option "Leave screen as it is" set, and while viewing the full page image - would not that give you pretty close to what was wanted?

**Comment by NiLuJe** [comment]
Closing this. Re-open if need be if someone wants to make this less puzzling (i.e;, making it count files instead of folders?).
