### ISSUE TITLE
Disable End Card Screen

### ISSUE THREAD

**Issue by tomatosoupcan** [koreader/koreader#3638]
* KOReader version: koreader-nightly-20180110
* Device: Kobo Aura One

**Comment by Frenzie** [comment]
Yes, see https://github.com/koreader/koreader/pull/2366. :-)

**Comment by poire-z** [comment]
I would have like to put the toggling of this setting in a menu item, but I didn't find a place where it would fit...

**Comment by Frenzie** [comment]
What if we rename `Save document` to `Document` and stick it in a submenu there?

![screenshot_2018-01-29_21-03-34](https://user-images.githubusercontent.com/202757/35531674-f563f698-0537-11e8-8e97-a036384b3ca4.png)

**Comment by poire-z** [comment]
Yes, could work.
Dunno really what Save document is for (saving highlights into a pdf?), and if some people use that often.

**Comment by Frenzie** [comment]
Yes, it's for altering PDFs: https://github.com/koreader/koreader/issues/3113 The Document menu would contain those two items: `Save document` and `Show status when finished` (or whatever).

**Comment by Frenzie** [comment]
And in tomorrow's nightly you'll be able to reach it through the menu. ;-)
