### ISSUE TITLE
"Table of contents" and "Go back to previous location"/"Swipe to go back"

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3645]
"Go back to previous location"/"Swipe to go back" are for links. 
Would it be possible to broaden their scope so as to include when you have tapped on a chapter in "Table of contents"?

**Comment by Frenzie** [comment]
And bookmarks would make sense too.

**Comment by poire-z** [comment]
Seems to work with:
```lua
--- a/frontend/apps/reader/modules/readerbookmark.lua
+++ b/frontend/apps/reader/modules/readerbookmark.lua
@@ -241,7 +241,7 @@ function ReaderBookmark:onShowBookmark()
     -- buid up menu widget method as closure
     local bookmark = self
     function bm_menu:onMenuChoice(item)
-        bookmark:gotoBookmark(item.page)
+        bookmark.ui.link:onGotoLink(bookmark.ui.document.info.has_pages and item or item.page)
     end

     function bm_menu:onMenuHold(item)
diff --git a/frontend/apps/reader/modules/readertoc.lua b/frontend/apps/reader/modules/readertoc.lua
index dc6c6baf..a33944cf 100644
--- a/frontend/apps/reader/modules/readertoc.lua
+++ b/frontend/apps/reader/modules/readertoc.lua
@@ -345,7 +345,7 @@ function ReaderToc:onShowToc()
             item.state.callback()
         else
             toc_menu:close_callback()
-            self.ui:handleEvent(Event:new("GotoPage", item.page))
+            self.ui.link:onGotoLink(self.ui.document.info.has_pages and item or item.xpointer)
         end
     end

```
But may be it's cleaner to just add a `ReaderLink:addCurrentPageToStack()` and call it before the original code above.

**Comment by Frenzie** [comment]
> But may be it's cleaner to just add a ReaderLink:addCurrentPageToStack() and call it before the original code above.

+1

**Comment by poire-z** [comment]
Some thoughts for discussion:
I use "Swipe to go back", and often, after following multiple links and going back, comes a point when the location_stack is empty and you go to previous page(s).
It's a bit confusing to know when you swiped back too much and needs to go forward (what was the text I was on? did I pass it or does it need a swipe back again?), at each swipe back you need to think if this page may be your original page.
For those who use the menu "Go back to previous location", it's obvious: when it's greyed out, it's that you're back to your original page.

Some ideas:
A Notification (at top of screen) when the location is empty?
Some "resistance" from swipe back: when after swiping back, the location stack becomes empty: the next swipe back would just not respond: that's the sign you are back. The next swipe after this would then really go to previous page.

Another thing: there's the fact that if you used TOC to go to some point, read a lot, and then followed links, you will get back to the original page.
At some point, when you consider a page your real current reading page, you should be able to reset the location stack (dunno if that could be guessed from some algorithm). The only way to do that for now is to re-open the document (or easier: Restart koreader).

**Comment by Frenzie** [comment]
I don't follow the last remark. All links you follow are (afaik) and should be added to the stack. I thought that now so were bookmarks and TOC?

**Comment by poire-z** [comment]
You thought right.
I meant the following use case:
- I open a new book, I'm on page 1
- I open TOC and jump to chapter 23 (which is from where I want to read) that leads me to page 199
- I read for 30mn from 199 to 217, then I follow a link, and then a few more
- I use "swipe back" (or the menu item) multiple times, wanting to get back to page 217
- If I use it one-time-too-much, I get back to page 1 (the newly added TOC-jump-remember-current-page, page 1 was added to location_stack). No easy way to get to page 217, if I remember it was page 217...

**Comment by Frenzie** [comment]
I see. Even though we have the stack (or is it removed? didn't check code) there's no `forward` to go along with `backward` while there probably should be.
