### ISSUE TITLE
Kobo Touch stuck at TS calibration (easy fix included)

### ISSUE THREAD

**Issue by tHubig** [koreader/koreader#3649]
* KOReader version:  1483+
* Device: Kobo Touch N905

#### Issue
Stuck at touchscreen calibration. It does not need calibration, it just has XY flipped. 

Here's how to fix:
open  **koreader/frontend/device/kobo/device.lua**

Find  section
`-- Kobo Touch:`

Change:
```
needsTouchScreenProbe = yes,
    touch_switch_xy = false,
```

To:
```
needsTouchScreenProbe = no,
    touch_switch_xy = true,
```
#### Steps to reproduce
Just start koreader

**Comment by Frenzie** [comment]
Actually that's exactly what the probe is supposed to detect; it's not for calibration.

https://github.com/koreader/koreader/blob/021e3db0029d71c29753c1ad405df362d63c69e1/frontend/device/kobo/device.lua#L178-L193
