### ISSUE TITLE
A new bookmark feature?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3654]
Hi everybody!

I have a two cents idea of a new feature. Maybe someone finds it interesting and want to work with it, I dunno.

**The problem.**
AFAIK it's not possible to bookmark pictures. 
But sometimes books have maps (or other pictures) that you want to return to many times during reading. It could be a fantasy novel or a WWII history book. 
Today you have to remember that page and use "Go to Location". And then to return you have to remember the page where you were currently reading and use "Go to Location" again.

**The solution.**
A new feature where you can save these kind of pages when they appear. Maybe it could be placed in the "Go to Location" window.
You would then be able to reach these pages with just a single tap and then "swipe to go back" to return where you were currently reading.

**An example how it could work.**
You open a new book. On page 6 you find a map. You long tap at the bottom of the screen and the "Go to Location" window opens. Below "Cancel", "Skim mode" and "Location" there is now another 3, 4 or maybe 5 boxes. You long tap Box1 and page 6 is now saved there.
Then you continue reading and when you are on page 32 you decide to check out the map. So you long tap at the bottom of the screen and the "Go to Location" window opens again. You single tap Box1 which transports you to page 6. Then you just swipe and get back to page 32 again. 
On page 37 there is another map and you decide to save that in Box2. And so on...

**Comment by Frenzie** [comment]
But you can bookmark the page/location of the picture, can't you?

**Comment by gerhaher** [comment]
How do I do that?

**Comment by poire-z** [comment]
To bookmark a page: tap at top right of screen (really at the top right, it's a small area).

And you can activate (in the Links submenu): Swipe to jump to latest bookmark - kind of like Swipe forward to follow links : if there is no link to follow in the page, it jumps to the latest bookmark you made - so you can easily go back to the latest map you bookmarked - and back with Swipe to go back.

**Comment by gerhaher** [comment]
Didn't knew that. Thanks!

KOReader is full of surprises. :-)

And if you want you can delete this thread (if it's possible).

**Comment by Frenzie** [comment]
We can only close. :-)
