### ISSUE TITLE
slow bookmarks?

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#3655]
* KOReader version: lastest version
* Device: ppw3

#### Issue

Is the bookmark menu kind slow? It is taking some time to enter here, PDF or EPUB files.

**Comment by poire-z** [comment]
If your bookmarks are highlights with long text, yes, it may have become slow since a few nightlys, see https://github.com/koreader/koreader/pull/3589#issuecomment-360986821. Hopefully it will be fixed soon.

**Comment by Eduardomb22** [comment]
Thanks. It is probably this.

**Comment by Frenzie** [comment]
Yep, some semi-random comments in a closed issue/PR are a bit hard to find. ;-)

**Comment by robert00s** [comment]
@Eduardomb22 
Can you check your bookmark menu after my patch #3657?

**Comment by Eduardomb22** [comment]
@robert00s, I'm not a programmer so I've tried to copy the menu.lua (or add and remove the lines from the file) to mine menu.lua. But I'm getting this error when I open a book and click in the bookmarks menu (It doesn't crash if the book doesn't have any bookmark saved)

02/02/18-14:43:23 WARN  sizeUtf8Text called without text
02/02/18-14:43:23 WARN  sizeUtf8Text called without text
02/02/18-14:43:23 WARN  sizeUtf8Text called without text
02/02/18-14:43:23 WARN  sizeUtf8Text called without text
lipc-wait-event exited normally with status: 0
Segmentation fault

I don't know if I'm doing right, so I think it is better to wait someone that could test it.

**Comment by robert00s** [comment]
Strange. 
Unzip this file and replace menu.lua in frontend/ui/widget
[menu.lua.zip](https://github.com/koreader/koreader/files/1690199/menu.lua.zip)

**Comment by robert00s** [comment]
Problem is with this line:
`self.text = table.concat(table.move(item_name.charlist, 1, offset - 4, 1, {})) .. "…"`

**Comment by Eduardomb22** [comment]
Can u ping me if you fix it? Thanks for looking into the problem.

**Comment by poire-z** [comment]
Fixed by #3657.
