### ISSUE TITLE
De-activating one dictionary prevents searching in any dictionary

### ISSUE THREAD

**Issue by taosxx** [koreader/koreader#3660]
* KOReader version: v2015.11-1492-g827ca20 (older sdcv to workaround #3302 )
* Device: Kobo Glo HD (Firmware 4.7.10413)

#### Issue

For testing purposes, I have several dictionaries installed. To speed up the dictionary lookup for normal reading I wanted to de-activate a couple of them. Unfortunately, as soon as I de-activate only one, dictionary lookup does no longer yield any results, I always get: "No definition found."

#### Steps to reproduce

- De-activate one dictionary in top menu -> search -> "Dictionary settings" -> "Installed dictionaries"
- Afterwards, search for a definition (either from a book or via "Dictionary lookup")

**Comment by poire-z** [comment]
The options names have changed between the old sdcv 0.4 and new sdcv 0.5.
And the koreader's code that sets the options have changed too some weeks ago, see https://github.com/koreader/koreader/issues/3440.

You would now need to change `"--exact-search"` to `"--non-fuzzy-fallback"`.

I use this in my own koreader mods:
```lua
--- orig_koreader/frontend/apps/reader/modules/readerdictionary.lua
+++ koreader/frontend/apps/reader/modules/readerdictionary.lua
@@ -530,6 +583,15 @@
         if not fuzzy_search then
             table.insert(args, "--exact-search")
         end
+        if G_reader_settings:isTrue("use_old_sdcv") then -- or use: if true then
+            -- old koreader patched sdcv 0.4.2 is faster than new upstream sdcv 0.5
+            table.remove(args, 1)
+            table.insert(args, 1, "../sdcv04") -- path to where your old sdcv is
+            if not fuzzy_search then
+                table.remove(args)
+                table.insert(args, "--non-fuzzy-fallback")
+            end
+        end
         if dict_names then
             for _, opt in pairs(dict_names) do
                 table.insert(args, "-u")
```
No change related to the `"-u"` options (that set the dict names to filter results from) was needed for me. You may try that and see if that's enough to make the -u options work again.

**Comment by Frenzie** [comment]
Also note that I posted two builds that don't require any source code changes:

https://github.com/koreader/koreader/issues/3302#issuecomment-336899689

https://github.com/koreader/koreader/issues/3302#issuecomment-337700307

**Comment by taosxx** [comment]
Unfortunately, poire-z's workaround doesn't work for me. If the checkboxes of all installed dictionaries are checked, dictionary lookup works. If only one check mark is missing, no definitions are found.

I think I'm already using one of Frenzie's builds.

**Comment by poire-z** [comment]
Nothing in crash.log ?

As soon as you disable one dict, **all the others** (their names) are passed to the sdcv command with -u <dictname>. When none is disabled, no need to pass any name as sdcv will check all the dicts it find.
So you may try to disable all dicts, except one with a very english ascii name (so only a simple `-u englishname` is used) and check again if it works (may be it's the name of one dict that is causing problem on the command line parsing).

**Comment by taosxx** [comment]
> may be it's the name of one dict that is causing problem on the command line parsing

That's it! One of the dictionaries had "français" in its name.

**Comment by poire-z** [comment]
It should work, if the _français_ is utf8 encoded (like all of them should be) in the .ifo.
May be it is there in latin1 encoding ? (but it should then display badly in koreader dict list in menu...)
(It works for me with some other french dicts like _Académie_, and I checked it worked with chinese dict titles)

**Comment by taosxx** [comment]
As far as I can tell, the .ifo is encoded as utf-8, unix style line endings, no byte order mark. In the menu, the dictionary name is rendered exactly as it is written in the .ifo file in the bookname line. BTW, for me, names including some chinese or japanese characters in dict titles don't work either - but all are displayed correctly in the menu.

**Comment by taosxx** [comment]
After updating the toolchain for kobo to solve #3302, I think this issue can be closed, too.
