### ISSUE TITLE
Pdf reading: going from portrait to landscape increases font size

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3662]
* KOReader version: v2015.11-1499-g016c17e
* Device: KA1

#### Issue
Well, I guess the above title says it all.

Is that intentional? Or is it bug?

**Comment by Frenzie** [comment]
In principle that doesn't sound like a bug to me, but it depends a bit on which zoom mode you're using of course. The same should happen in any random PDF viewer on your desktop computer if you have it set to something like "window width" as opposed to a specific percentage.

<img src=https://user-images.githubusercontent.com/202757/35810386-dd3544b0-0a8b-11e8-8a2a-7ac8907bb13e.png width=30%>

<img src=https://user-images.githubusercontent.com/202757/35810396-e1632bb0-0a8b-11e8-97e5-f19028c93f5f.png width=30%>

A PDF page has a certain width and a screen has a certain width. Assuming the page is taller than it is wide, combined with fit content width or fit page width, the page should therefore indeed increase in size in landscape mode.

<img src=https://user-images.githubusercontent.com/202757/35810559-69bc02c0-0a8c-11e8-9f4d-22e8b45c825f.png width=30%>
<img src=https://user-images.githubusercontent.com/202757/35810560-69e1f80e-0a8c-11e8-931e-1bbd4501ce85.png width=30%>

I'd probably go a step further and say that this is the primary use case for landscape mode, at least on PDF or DjVu files: some of them are made for larger paper sizes (e.g., magazine size) and will therefore be too small to comfortably read in portrait.

**Comment by gerhaher** [comment]
OK, thanks.
However in my case it doesn't make sense. I read my pdf:s in reflow mode. Mostly books with one column text. 
The font size I have chosen in portrait mode should therefore work perfectly fine also in landscape. (Which it does, after I have decreased the font size in the menu.)

**Comment by Frenzie** [comment]
In that case it could arguably be called a bug, although since I see the primary purpose of landscape as increasing the zoom level I'm intuitively inclined to argue against it. Reflow can be seen a special case where it'd make more sense to increase the document width to keep the zoom level equal, but note that EPUBs, which are effectively always in reflow mode, seem to behave the same way as well. So whether intentionally or by accident, the program does at least behave consistently.

**Comment by Frenzie** [comment]
I'll close this now. :-)
