### ISSUE TITLE
koreader can't open pdf file from the home page

### ISSUE THREAD

**Issue by laobojiang** [koreader/koreader#3668]
When I open the pdf file by clicking on the file in the home page, there is an error message:  "无法启用选定的应用程序，请重试。" , which means "can't start selected application, please retry". Similar problem as Issue#131.
However, the same file can be opened by koreader through "KUAL-Koreader-start the filemanager". 
What is the problem?

* Device: kindle paperwhite
* Firmware version: 5.6.1.1 (jailbreak in 5.4.4.2, then update to 5.6.1.1)
* KOReader version: v2015.11-stable
                                  (same problem found in "nightly-20180110")
* KPVboolet version: kindle-kpvbooklet-0.6.6
* KUAL version: KUAL-v2.7.2-gea85a19-20171125
* KUAL mrinstaller version: kual-mrinstaller-1.6.N-r14394

**Comment by laobojiang** [comment]
Problem solved by downgrade the KPVbooklet version to 0.6.2.

**Comment by Frenzie** [comment]
They'd probably appreciate it if you could open an issue to track it in https://github.com/koreader/kpvbooklet/issues
