### ISSUE TITLE
HTML Dictionary: messy format 

### ISSUE THREAD

**Issue by enigma90** [koreader/koreader#3673]
* KOReader version: v2015.11-1514-g501df2e
* Device: Kobo Touch

Glad to see HTML dictionary support on KOReader. But it needs some tune-ups, I think. The same dictionary looks like this on Goldendict:

![rebellion](https://user-images.githubusercontent.com/18080825/36061727-5dd03ede-0e99-11e8-8262-b3daa75f5607.jpg)

When it comes to KOReader, it looks like:

![reader_2012-nov-02_144050](https://user-images.githubusercontent.com/18080825/36061742-9732f5a4-0e99-11e8-985c-a599fe4ddb79.png)

![reader_2012-nov-02_144105](https://user-images.githubusercontent.com/18080825/36061744-a1af7fac-0e99-11e8-83d2-64d169e56deb.png)

![reader_2012-nov-02_144202](https://user-images.githubusercontent.com/18080825/36061746-a8d3755e-0e99-11e8-8ed4-eb5505f329f9.png)

![reader_2012-nov-02_144210](https://user-images.githubusercontent.com/18080825/36061748-b2e4c520-0e99-11e8-8c1c-35cbbf0a91e9.png)

Kinda messy, don't you think? Hope to see some improvements soon.

THKs.

**Comment by Frenzie** [comment]
It's probably the regular text fallback (i.e., no different than before) that occurs with invalid HTML. Pinging @poire-z because I forget where he posted some interesting information about workarounds.

**Comment by poire-z** [comment]
We use MuPDF to render the HTML dictionary results. Unfortunatly, MuPDF expects its input to be XHTML, that is totally correct XML, balanced, all tags and attributes in lowercase... HTML.
When it is not, KOReader noticed MuPDF didnt like it, and fallback to stripping tags, keeping line feeds, like it used to do before, and give it back to MuPDF (well, may be it is not as good as it was before when we just stripped tags and render with TextBoxWidget...)
We can't easily fix and convert any HTML to XHTML, but one can add a .lua file in the dict directory with code to tweak the output before feeding it to MuPDF.
You need to be at ease with lua, or just hack the [samples](https://github.com/koreader/koreader/pull/3585#issuecomment-361203757) I did for some french dicts. More details in #3585 (and  #3606, #3611).

**Comment by enigma90** [comment]
I use one of your samples (PetitRobert2007_1.1.lua.txt) and it does make some differences. The first page looks great, but the COLLOCATIONS and Thesaurus sections are missing. 

![reader_2018-feb-11_083309](https://user-images.githubusercontent.com/18080825/36068085-b926ee68-0f07-11e8-8d31-32a28bd79425.png)

![reader_2018-feb-11_083324](https://user-images.githubusercontent.com/18080825/36068089-ddaea0d2-0f07-11e8-91f0-ab347f56b35c.png)
 
The other two samples don't work. 

If you would like to improve the HTML support, here is the part of the dictionary that I use to test. 
Sorry, I'm illiterate in coding. :-(

[rebellion.txt](https://github.com/koreader/koreader/files/1713917/rebellion.txt)

**Comment by Frenzie** [comment]
There's a devastating syntax error there (for an XML parser), right before the `COLLOCATIONS`:

```html
<span style="color: #FFFFFF; background-color: #1c3e94"; font-size: 120%>
```

If this is a global issue you can simply replace it with:

```html
<span style="color: #FFFFFF; background-color: #1c3e94; font-size: 120%">
```

**Comment by enigma90** [comment]
Did as you instructed. Most bold and italic font settings are gone, but the dictionary itself has become much more usable. Thank you so much!
![reader_2018-feb-11_161517](https://user-images.githubusercontent.com/18080825/36071869-874518ea-0f50-11e8-9593-04f7f9ea86ef.png)

**Comment by Frenzie** [comment]
Presumably because you retargeted @poire-z 's lua file aimed at another dictionary you've lost some formatting in the process. I think in your sample file all I did was to change `<BR>` to `<br/>` combined with a manual fix of that syntax error.

![screenshot_2018-02-11_10-59-05](https://user-images.githubusercontent.com/202757/36072131-b2d159b4-0f1a-11e8-981f-ba9135a2b067.png)

The easiest way to test quickly (imo) is to just create a .html file and then to open it with MuPDF. For that purpose you'll have to surround it with a root element of some sort. Generally you can just stick in something like `<html>` or `<body>`, but as a healthy habit I use something like:

```html
<!DOCTYPE html>
<html>
<body>
<!-- content goes here -->
</body>
</html>
```

Oddly enough, the white foreground color of the text is applied, but the background color is not. It's not quite clear to me why that is, because MuPDF does support background colors. The question doesn't sufficiently interest me to find out the specifics. :-P

**Comment by cramoisi** [comment]
It seems faster to use pyglossary to convert this in csv, clean it with a text editor and some regexp, make a css file to work with, and convert it back into a stardict file. In my case, it was faster to do that with the robert than working out all the error inside in a lua file). The result is lighter too.

**Comment by Frenzie** [comment]
I think that altering things on your computer is easier and faster goes without saying. :-) That holds true regardless whether we're talking about [Scan Tailor](https://fransdejonge.com/2014/10/fixing-up-scanned-pdfs-with-scan-tailor/) or dictionaries.

**Comment by Frenzie** [comment]
Closing since the wiki has been updated by @AlanSP1.

https://github.com/koreader/koreader/wiki/Dictionary-support#html-encoding-within-stardict-dictionaries-supported
