### ISSUE TITLE
A bug on Kindle 3 Keyboard Wifi

### ISSUE THREAD

**Issue by SakuraNico** [koreader/koreader#3684]
* KOReader version:v2015.11-1523-g78284e1
* Device:Kindle 3 Keyboard Wifi

#### Issue
I try to open the *GoTo* Function from menu, Cannot input number 1, When I press Q, It shows 9, The screen displayed that under both number 1 and 9 are all letter *Q*.
#### Steps to reproduce
Open an TXT with KOReader on Kindle 3 wifi, Press *Menu*, Choose the *Goto*, then you'll find that you cannot type number 1

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by robert00s** [comment]
@SakuraNico 
Try to remove (or comment) this line:
https://github.com/koreader/koreader/blob/ca6a4868069c2ddb58bedf8497690440d1440d1f/frontend/ui/widget/menu.lua#L621

Line 621 in file frontend/ui/widget/menu.lua:
`type_goto = "string"`

**Comment by SakuraNico** [comment]
@rebert00s
Feel grateful for your enthusiastic help!

**Comment by SakuraNico** [comment]
robert00s 
Feel grateful for your enthusiastic help!

**Comment by robert00s** [comment]
@SakuraNico 
Does that help?

**Comment by Commodore64user** [comment]
another ticket that could be closed. you certainly can type all numbers now.
