### ISSUE TITLE
cannot open Epub&PDF files on kindle homepage

### ISSUE THREAD

**Issue by Profitter** [koreader/koreader#3686]
* KOReader version:
* Device:

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Would that be related to https://github.com/koreader/kpvbooklet/issues/34 ?

**Comment by NiLuJe** [comment]
Yep, this belongs in KPVBooklet, closing ;).
