### ISSUE TITLE
How to export highlights as plain text

### ISSUE THREAD

**Issue by agaAdams** [koreader/koreader#3690]
* KOReader version: nightly v2015.11-1525-gca6a486
* Device: KA1

#### Issue
I'm not sure how to export highlights from my documents to a plain text format 
#### Steps to reproduce
Menu > Tools Icon > Evernote
- export to local HTML files
- export to local clipping text file

If I check the option to export to text file, only ONE menu option to export becomes available: "Export all notes in your library"
Activating this option creates a "KOReaderClipping.txt" file with ONLY the titles of books with highlights. No highlights are included.

If I choose export to HTML, BOTH menu options to export become available and produce the intended html-files.

Is exporting to plain text somehow broken or am I doing this the wrong way?

**Comment by Frenzie** [comment]
I just gave it a quick try and both options seem to work for me.
```
quickstart
　
　　-- Page: 1, added on Thu Feb 22 16:55:39 2018
the
-=-=-=-=-=-

quickstart
　
　　-- Page: 2, added on Thu Feb 22 16:56:48 2018
language and other settings through the gear icon.
File
-=-=-=-=-=-
　　-- Page: 3, added on Thu Feb 22 16:56:53 2018
folders
-=-=-=-=-=-

[clipboard.zip](https://github.com/koreader/koreader/files/1748574/clipboard.zip)

**Comment by agaAdams** [comment]
This is how my menu looks in koreader:
![01 koreader_menu](https://user-images.githubusercontent.com/22838606/36618001-bd78fb32-18e9-11e8-85ed-1f22e40a3c34.jpg)

The message I get after exporting all notes:
![02 koreader_message](https://user-images.githubusercontent.com/22838606/36618005-c1142f5a-18e9-11e8-9443-c1d676a9fff1.jpg)

The plain text file I end up with after exporting:
![03 koreader_txt_file](https://user-images.githubusercontent.com/22838606/36618007-c360d06a-18e9-11e8-9a19-1d43909ecf09.png)

One of the html files generate for one of the books:
![04 koreader_html_file](https://user-images.githubusercontent.com/22838606/36618009-c4da2edc-18e9-11e8-9e84-a650bf9306c1.png)

What I don't understand is why I get all the highlights exported per html but only the one from the first book per plain text.

**Comment by Frenzie** [comment]
Did you try the Suble Art book independently? In the list it looks like that's where things go wrong, because the Paleo Approach did apparently work out.

As an aside, those are some nice encoding issues in your screenshot of the HTML export.

**Comment by agaAdams** [comment]
I now removed all highlights from the first two books in the list and made a new file export. The problem stays the same: Only the first highlight of the first book gets exported. Beyond that it's only titles:
![plain_text_export_2](https://user-images.githubusercontent.com/22838606/36627989-704ae25a-194b-11e8-87f2-2457434dabf9.png)

**Comment by Frenzie** [comment]
The problem was introduced in #2573, specifically this line:

https://github.com/koreader/koreader/blob/40ff96761548f3a713519e97a023cecb4f107578/plugins/evernote.koplugin/main.lua#L489

Instead what we need is a timestamp for last exported. The clippings settings file looks like this:

```lua
            ["exported"] = {
                ["txt"] = true
            },
```

Maybe something like `txt_time = 1519466736`.

Then the check could change to something like:

```lua
local last_exported = booknotes.exported and booknotes.exported.txt_time or0

if clipping.time >= last_exported then
```

Pinging @Hzj-jie
