### ISSUE TITLE
WiFi handling is still broken in Koreader (can't connect to WiFi hotspot)

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#3691]
* KOReader version: v2015.11-1523-g78284e1
* Device: Kobo Aura One (most likely all Kobos)

#### Issue
Unable to connect to WiFi hotspot

#### Steps to reproduce
Create a WiFi hotspot on the mobile phone, turn it on and run FTP server on it. Now try to connect to this FTP server from within Koreader --- it will hang for a while and then will timeout. This is probably because Koreader is trying to connect to some node on the "Internet" which is wrong, it should NOT ever try to do such a thing as there is no point in it.

I have fixed this issue a year or so ago locally (on my own device) but I recall that a few weeks ago the corresponding issue was closed by a fix, so I assumed that it was fixed and so I upgraded, forgetting about my own fix. Now I'll have to dig out my fix and restore it in the new version...

Here is a proof that it works from the shell on the Kobo device:

```
root@one:~ # ifconfig
eth0      Link encap:Ethernet  HWaddr 58:B0:D4:35:4E:79  
          inet addr:192.168.43.105  Bcast:192.168.43.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6 errors:0 dropped:3 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1838 (1.7 KiB)  TX bytes:1306 (1.2 KiB)

usb0      Link encap:Ethernet  HWaddr 46:0D:9E:67:69:EC  
          inet addr:192.168.2.101  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:184 errors:0 dropped:0 overruns:0 frame:0
          TX packets:127 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:15938 (15.5 KiB)  TX bytes:16334 (15.9 KiB)

root@one:~ # telnet 192.168.43.1 2221
220 Service ready for new user.
quit
221 Goodbye.
Connection closed by foreign host
```

As you see, the interface is up and you can connect to the ftp server, but not from within Koreader --- you get "Cannot fetch the list, check with your network administrator". And, indeed, going to "Network" menu option in Koreader shows "WiFi connection" unchecked, which is wrong. I didn't try to click on it, because it would be conceptually wrong --- WiFi is managed by KSM and not by Koreader, so any such attempt to "turn on WiFi" from within Koreader would be a mistake.

**Comment by tigran123** [comment]
Here is my fix which was working in version 1270:

```
$ diff -u cloudstorage.lua.orig cloudstorage.lua
--- cloudstorage.lua.orig	2018-02-22 16:43:16.850008913 +0000
+++ cloudstorage.lua	2018-02-22 16:46:16.580000640 +0000
@@ -102,10 +102,10 @@
 function CloudStorage:openCloudServer(url)
     local tbl
     local NetworkMgr = require("ui/network/manager")
-    if not NetworkMgr:isOnline() then
-        NetworkMgr:promptWifiOn()
-        return
-    end
+    -- if not NetworkMgr:isOnline() then
+    --     NetworkMgr:promptWifiOn()
+    --     return
+    -- end
```

However, when ported to the current version it doesn't work, i.e. like this:

```
root@one:cloudstorage # diff -u cloudstorage.lua.orig cloudstorage.lua
--- cloudstorage.lua.orig
+++ cloudstorage.lua
@@ -109,10 +109,6 @@
         end
         tbl = DropBox:run(url, self.password)
     elseif self.type == "ftp" then
-        if not NetworkMgr:isConnected() then
-            NetworkMgr:promptWifiOn()
-            return
-        end
         tbl = Ftp:run(self.address, self.username, self.password, url)
     end
     if tbl and #tbl > 0 then
```

So, we need to figure out what else has changed that may be causing that unnecessary check for "Internet connection" if indeed that is the cause of the problem.

**Comment by tigran123** [comment]
Some more info: even if I disable WiFi from within KSM and, against my better judgement, enable WiFi from within Koreader, then I get a message "Connected to BTLM7G" (which is my WiFi hotspot), but the WiFi menu option is still unticked AND I am still unable to login via Cloud storage to the ftp server.

**Comment by Frenzie** [comment]
> This is probably because Koreader is trying to connect to some node on the "Internet"

It doesn't. It runs this command (see #3593):

```
ping -c1 -w2 $(/sbin/route -n | awk '$4 == "UG" {print $2}')
```

> And, indeed, going to "Network" menu option in Koreader shows "WiFi connection" unchecked, which is wrong.

That can be considered a bug or a lack of finesse, but it's otherwise unrelated since it currently uses `isOnline()`.

https://github.com/koreader/koreader/blob/1d0a5b4aa3dac665c1118436a0c2ad313e926835/frontend/ui/network/manager.lua#L125

> So, we need to figure out what else has changed that may be causing that unnecessary check for "Internet connection" if indeed that is the cause of the problem.

Did you test if the type==dropbox code path is hit? It's conspicuously there acting on `not isOnline()` with a prompt. ;-)

**Comment by tigran123** [comment]
@Frenzie  my dear friend and my brother --- my SINCEREST APOLOGIES!

You are absolutely right and I was absolutely wrong.
It works now.

How come it didn't 5 minutes ago? I forgot to add ":2221" to the end of the ftp url! :)

I am so happy and gladly admit my mistake. Thank you again for your excellent work!

**Comment by tigran123** [comment]
Btw, yes, that absence of tick against WiFi connection in the menu is a slight cosmetic issue, but certainly not the kind of "big deal" that I was making in claiming that cloud storage to mobile WiFi hotspot not working.

**Comment by tigran123** [comment]
Closing the issue as it was user's error --- I forgot to add the custom ftp port number to the URL. But Koreader is functioning correctly.

**Comment by Frenzie** [comment]
Great! :+1: 

I think perhaps ideally it'd look a bit like on Android or iOS (picture grabbed from [here](https://www.amsys.co.uk/2016/10/ios-10-wi-fi-tips/)), with the exclamation mark through the wifi icon.

![wi-fi2](https://user-images.githubusercontent.com/202757/36553127-d74c63da-17fb-11e8-8e40-0aa6849b4842.jpg)

But it should be beyond simple to stick in a text_func that returns either `Wi-Fi` or `Wi-Fi (no internet connection)`. Perhaps three states (such as `not connected`, `no internet`, and `online`). Do you have any suggestions on the wording and other specifics?

My suggestion:

1. Simplify "Wi-Fi connection" to just "Wi-Fi"
2. Three states, probably better like this (as simple as possible)
      * [ ] Wi-Fi
      * [x] Wi-Fi (no internet connection)
      * [x] Wi-Fi
3. Or more verbose:
      * [ ] Wi-Fi (disconnected)
      * [x] Wi-Fi (no internet connection)
      * [x] Wi-Fi (connected)

**Comment by tigran123** [comment]
Well, let's think...

There can be two concepts of "no internet connection":

1. It is not known whether sending a packet to the default gateway destined to a node outside of our subnet will succeed or time out. E.g. in the above scenario with my mobile WiFi hotspot I could have enabled mobile networking and (assuming my provider allows tethering) but Koreader wouldn't know about this, without sending any external packets.

2. We have sent such a packet and it timed out.

The meaning of the menu item we are discussing certainly corresponds to the semantics of 2, not 1. But this means that we must send a packet and wait for a timeout. And this is what I really don't like. Is it not better to just leave things as they are, i.e. cosmetically slightly wrong, but without unnecessary delays for sending packets out?

However, if by "No internet connection" we mean the above choice 1, then by all means add such a textual description against the menu option. But wouldn't this be somewhat misleading, as in the example with turning on mobile networking?

What I am basically saying is that purely for the purposes of making WiFi menu status accurate it is not worth sending packets outside and waiting for timeout.

**Comment by Frenzie** [comment]
Oh right, that's why I didn't do anything about it, I forgot. It's on my mental to-<del>do</del><ins>forget</ins> list for after #3078, preferably in the form of making @Hzj-jie do it. :-P

**Comment by tigran123** [comment]
Btw, looking at the source code line 125 which you have shown above it seems that it would be trivial to change that function to use `isConnected()` method instead of `isOnline()` and then the WiFi tick in the menu would be accurate. By "accurate" I really mean "accurate" and not the idea that some end-users may have in their heads. Namely, those users who think "WiFi" and "Internet connection" is the same thing. Maybe we shouldn't encourage such wrong thinking and calling `isOnline()` is doing exactly that.

I didn't mention this because I thought it would be more involved than just changing one line of code :)
