### ISSUE TITLE
Page indicator displays "=>"

### ISSUE THREAD

**Issue by Svahnen** [koreader/koreader#3692]
* KOReader version: V2015.11-1525-gca6a486
* Device: Kobo aura 2nd edition

#### Issue
The page number have stoped showing how many pages the book have totally, the page indicator looks as following: "=> 608" so it shows "=>" instead of the total number, the current page still looks like normal, this happens in all books i open

#### Steps to reproduce
I dont know what happened, i was playing with the zoom settings (and a couple more, dont rly remember) and suddenly this happened.

**Comment by Svahnen** [comment]
Is there anyway of resetting Koreader back to default? So i can try to see if the problem persists then.

**Comment by Svahnen** [comment]
I was being dumb, this is a setting u can change in the lower left corner

**Comment by Frenzie** [comment]
I'm not entirely sure what you mean you did, but in settings → status bar you can also choose "show all at once" and then tick which info you want to display. On larger sized screens like the H2O and the Aura One that makes perfect sense, but it defaults to a setting more appropriate for smaller lower res screens.
