### ISSUE TITLE
weird crash

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3693]
* KOReader version: 1483
* Device: gloHD

#### Issue
Yesterday evening, I was fiddling with koreader and I chose "Display mode" > "Detailed list with cover images and metadata". Got a crash information from KSM8 saying koreader had a issue "continue or shutdown". First I chose continue, but got the same screen, so I chose shutdown. When booting back, I got my KSM8 menu without the option to run koreader. I plugged my reader on my computer to check it : no more .adds/koreader directory and no more .hidden/library directory ; so no more reader app (and options, etc) and no more books.

How could this issue even happened ?

#### Steps to reproduce
don't do it ?

##### `crash.log` (if applicable)
`crash.log` was deleted with the rest...

**Comment by Frenzie** [comment]
> First I chose continue, but got the same screen, so I chose shutdown.

You mean?

* Continue
* Restart KOReader
* Same screen

I don't know what this could be. O-o

**Comment by cramoisi** [comment]
ksm8 present me a screen saying more or less (from memory) : koreader has crashed : continue - shutdown. On this screen, the first time, i chose continue, believing it will restart koreader but all I got was the same screen so the second time I chose shutdown (and the reader shut down with the screen provided by ksm)

**Comment by Frenzie** [comment]
As far as I know continue is supposed to just go back to KSM. I'm not really sure what the shutdown option is there for. :-P

The Dropbox thing worked when I last tried it, but that was a while ago. Pinging @robert00s

**Comment by cramoisi** [comment]
The dropbox thing worked last week , if my token was bad, i should have a "can't connect message" am i wrong ?

**Comment by Frenzie** [comment]
Looks like a generic error message

https://github.com/koreader/koreader/blob/25a67a2e17d9410d2f3df33d2b452d7da19b621d/frontend/apps/cloudstorage/cloudstorage.lua#L121-L125

The function behind the scenes should probably be able to spit out more specific error messages in theory but it doesn't. 

https://github.com/koreader/koreader/blob/25a67a2e17d9410d2f3df33d2b452d7da19b621d/frontend/apps/cloudstorage/dropboxapi.lua#L41-L73

**Comment by cramoisi** [comment]
ok, it was this font use on the dropbox website which give a token were "I" and "l" are the same. I'm giving in each time like the noob i am.

**Comment by Frenzie** [comment]
I think it might (deceptively) give that message every time if there's no database yet.

**Comment by Frenzie** [comment]
You sure? I mean, it makes no sense (at no point should any kind of "delete everything" be called O_o) but whatever it is, it's pretty serious. :-P

**Comment by cramoisi** [comment]
Yeah but, as you said, it makes no sense and and I doesn't have the smallest clue from where to start searching since everything koreader related was deleted (except the screensaver directory). The only thing I can do with this is to try to reproduce the bug on my reader but I tend towards reading with it more then trying to crash it.
But but but, I will try to reproduce it when on my next good old paper book and if I'm successful, I'll reopen...

**Comment by Frenzie** [comment]
In particular the fact that you say *two* distinct directories were gone does sound more like a filesystem error of some sort to me.

**Comment by cramoisi** [comment]
Ok, the gloHD sd card crashed yesterday. I can't understand how it could sustained a f3 test after the crash last month but anyway, like you said, it was obviously the card.

**Comment by Frenzie** [comment]
Hopefully you'll be able to claim warranty of some sort.
