### ISSUE TITLE
Dictionary lookup by clicking word not working

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#3704]
* KOReader version:2015.11-1525
* Device: Kindle 7th Generation, firmware 5.9.4

#### Issue
Dictionary lookup by pressing and holding a word doesn't work. Such problem occured before, then it was fixed.
#### Steps to reproduce
Open a PDF document, press a word and hold. Previously it started dictionary lookup of the word, now
it starts text selection.

**Comment by Frenzie** [comment]
Pinging @TnS-hun Likely an issue with #3704.

**Comment by TnS-hun** [comment]
I couldn't reproduce the problem with the emulator.

#3704 is this issue. Which one do you mean, @Frenzie?

**Comment by Frenzie** [comment]
Oh, oops. :-P I meant the HTML dictionary widget, but I see that on my phone I misread and this has nothing to do with that.

@ilyats Could it be that you're holding extra long? See #3697

**Comment by ilyats** [comment]
@Frenzie How long am I supposed to hold it? Previously after holding for a second o so the dictionary window popped up.

**Comment by Frenzie** [comment]
Extra long would be three seconds. So less than 3 seconds.

You say the same problem occurred before. Do you know the issue #?

**Comment by ilyats** [comment]
It seems that 1 sec is enough to start selection. Sometimes when I hold for la little (<1sec) and then release, selection appears to start aftee release. When this problem appeared before, I did not create an issue and I do not know if somebody else did.

**Comment by Frenzie** [comment]
If you only hold it for about a second it's normal that the highlight happens more or less simultaneously with your finger's release. That doesn't really sound like an issue to me (except in E Ink response time).

While playing around I did notice an issue where in the test/2col.pdf document the dictionary widget is never drawn for some reason.

## Bug (never drawn)
![screenshot_2018-03-04_13-01-44](https://user-images.githubusercontent.com/202757/36945308-3aef4026-1fac-11e8-9ee8-68775ebf31ba.png)

## Text selection menu (seems to work as expected, either move around a little or hold more than there seconds)
![screenshot_2018-03-04_13-01-52](https://user-images.githubusercontent.com/202757/36945309-3b0be636-1fac-11e8-8003-80c733b9e243.png)

**Comment by ilyats** [comment]
I am unable to get either dictionary or the menu you posted

**Comment by ilyats** [comment]
Actually, if I press a word, hold it for a while, then release, KOreader crashes. 
[crash.log](https://github.com/koreader/koreader/files/1778484/crash.log)

**Comment by ilyats** [comment]
I upgraded to 1537, now the menu does appear, but clicking any item in it has no result. (It wouldn't probably be of much help anyway, as the selection is usually not the whole word.)

**Comment by Frenzie** [comment]
The issue with 2col.pdf is a lack of OCR data.

**Comment by ilyats** [comment]
The problem was caused by "Forced OCR" option turned on for that document. Sorry for being nuisance.

**Comment by Frenzie** [comment]
There is something a bit off about the OCR thing though. It should probably pop up a little info popup about the problem so that you'd know why things look selected but aren't.

**Comment by ilyats** [comment]
The text is in German. Does thw OCR algorithm presuppose English text?

**Comment by Frenzie** [comment]
It doesn't presume anything:
https://github.com/koreader/koreader/wiki/Dictionary-support#dictionary-lookups-in-scanned-pages

It's the same basic problem of discovery I fixed for the dictionary in https://github.com/koreader/koreader/pull/2817 and (someday soon :-P) in https://github.com/koreader/koreader/pull/3176

**Comment by ilyats** [comment]
That's dictionary support, not OCR

**Comment by ilyats** [comment]
In fact, there is an option to select the document language, but the only available choices are English and Chinese.

**Comment by Frenzie** [comment]
> That's dictionary support, not OCR

Think about it. Without OCR, no dictionary support in scanned pages. ;-)

This is what it says at the link:

> ### Dictionary lookups in scanned pages
>
>KOReader has a build-in OCR engine for recognizing words in scanned PDF/DJVU pages. In order to use OCR in scanned page, you need to install tesseract trained data for your document language.
>
>* install [Tesseract language data](https://sourceforge.net/projects/tesseract-ocr-alt/files/)
>    * copy language data files for Tesseract 3.02 (e.g. `eng.*` in `tesseract-ocr-3.02.eng.tar.gz` for English and `spa.*` in `tesseract-ocr-3.02.spa.tar.gz` for Spanish) into `koreader/data/tessdata`
