### ISSUE TITLE
Crash on EPUB file

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#3705]
* KOReader version: 2015.11-1525
* Device: Kindle 7th Generation, firmware 7.9.4

#### Issue
An ePub file crashes Koreader
#### Steps to reproduce
Try opening the attached file
[Антонин Марк Аврелий. Размышления - royallib.com.epub.zip](https://github.com/koreader/koreader/files/1773628/-.royallib.com.epub.zip)
[crash.log](https://github.com/koreader/koreader/files/1773629/crash.log)

**Comment by cramoisi** [comment]
It looks like you tried to open it with muPDF, could you tried to long press and choose crengine and see if you still experience a crash ? (it looks like the mupdf has a problem with the pdf you open just before the this epub).

Also, just a question : why is your epub zipped ? (it makes no sense to me since epubs are kinda zip files themselves, the size gain is very slim)

**Comment by Frenzie** [comment]
@cramoisi GitHub doesn't take .epubs. I think it makes more sense to just stick .zip at the end but either way you need a workaround.

On the emulator I have no trouble opening that file in either crengine or MuPDF, but something about the Cyrillic encoding is royally (ahem, bad joke) messed up for me.

![screenshot_2018-03-02_10-01-25](https://user-images.githubusercontent.com/202757/36891125-c076dc5c-1e00-11e8-8bd8-f844dcbfd164.png)

On a real device it's not unthinkable that something stupid like that would cause issues. @ilyats Besides trying crengine, could you also try naming it something like `blabla.epub` to see if that could be the problem?

**Comment by cramoisi** [comment]
@Frenzie I know, but in the crash.log, you could see it :
 
03/02/18-05:40:25 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
03/02/18-05:40:47 INFO  opening file /mnt/us/documents/Антонин Марк Аврелий. Размышления - royallib.com.epub.zip

So he opened a zipped epub and posted the file as it.

**Comment by Frenzie** [comment]
Oh, I see what you mean. If I find the time today I might take a quick peek to see if I can make the error handling a touch more robust but we definitely wouldn't expect to be able to just open the zip file posted as is.

crengine crashes a touch nicer in that case than MuPDF (the default handler for zip files):
![screenshot_2018-03-02_12-04-52](https://user-images.githubusercontent.com/202757/36896230-1db79ac6-1e12-11e8-8b35-62923f427d89.png)

Zip files that do open are collections of pictures and text files. If you rename an EPUB to .zip, for example, you'll likely just see the images.

**Comment by cramoisi** [comment]
So, a OS with "showing extensions" disabled, a downloaded zipped-epub and a human error on the top ?

**Comment by Frenzie** [comment]
The exit is definitely on purpose:

https://github.com/koreader/koreader/blob/f6ca1c7c0a06f159ebaa6b5460bf7273fb98e2ae/frontend/apps/reader/readerui.lua#L432-L437

This doesn't strike me as very nice behavior (except in debug mode) but it's probably the easiest way to avoid a segfault and other issues.

Now what's really weird is that there is already code present to avoid the crash in question. I was going to give something like the following commented out a quick try when I noticed it was already there. Uncommenting it seems to work perfectly fine.

https://github.com/koreader/koreader/blob/5cfe9992adf2169f07ee0f26813859dbe892375f/frontend/document/pdfdocument.lua#L41-L44

Perhaps I unwittingly implemented the todo in #2956.

@cramoisi 

> So, a OS with "showing extensions" disabled, a downloaded zipped-epub and a human error on the top ?

Probably something like that.

**Comment by Frenzie** [comment]
@poire-z For a quick second opinion: the workaround is the same as uncommenting those lines but I think logically it probably fits better in base/ffi/mupdf.lua Why should the frontend worry about this kind of thing after all. It's just a kind of document loading failure.

```diff
diff --git a/ffi/mupdf.lua b/ffi/mupdf.lua
index 7fbe2e2..6d92510 100644
--- a/ffi/mupdf.lua
+++ b/ffi/mupdf.lua
@@ -96,6 +96,10 @@ function mupdf.openDocument(filename, cache_size)
 
     setmetatable(mupdf_doc, document_mt)
 
+    if not (mupdf_doc:getPages() > 0) then
+        merror("MuPDF found no pages in file.")
+    end
+
     return mupdf_doc
 end

**Comment by poire-z** [comment]
Doing this in ffi/mupdf.lua looks fine to me, as there is already a `merror("cannot open PDF file")` just above the `setmetatable`. (May be you could do it too above that `setmetatable`, just so to not bother with lua metatable in case of errors).

**Comment by Frenzie** [comment]
Not the biggest issue admittedly, but I think that looks ugly: `if not (document_mt.__index.getPages(mupdf_doc) > 0) then`

**Comment by poire-z** [comment]
Oh, right, you need setmetatable to get that method. So ok, keep it not ugly :)
