### ISSUE TITLE
weird issue with sleep, wake up and battery

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3706]
* KOReader version: 1525 (there is no complete nightly since feb, 21 on http://build.koreader.rocks/download/nightly/, so it's the last one)
* Device: gloHD

#### Issue
Since reinstallation, I experience a massive battery drain by hour and a weird battery stat on sleeping during night. Battery is consumed by 50% over six hours and there is more usage when sleeping than when using...
As usual, I disabled the magnet of the sleepcover in the reader setting file and I don't have a magnetic cover. The frontlight was off. Usually, disabling the magnet remove the old battery issue for me ( #2854  ) so I assume it's kind of a new one ?

##### `crash.log` (if applicable)

Oddly, my kobo was sleeping when I wake it up this morning, but the sleeping action, performed at 23:45 on march, 1 is not registered : 

03/01/18-21:41:06 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
ifconfig: SIOCSIFADDR: No such device
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device
03/01/18-21:58:55 INFO  Kobo suspend: going to sleep . . .
03/01/18-21:58:55 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
03/01/18-21:58:57 INFO  Kobo suspend: waited for 2s because of reasons...
03/01/18-21:58:57 INFO  Kobo suspend: synced FS
03/01/18-21:58:57 INFO  Kobo suspend: asking for a suspend to RAM . . .
03/01/18-21:58:57 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
03/01/18-22:28:55 INFO  Kobo suspend: woke up!
03/01/18-22:28:55 INFO  Kobo resume: clean up after wakeup
03/01/18-22:28:55 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
ifconfig: SIOCSIFADDR: No such device
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device
03/02/18-07:02:12 INFO  Kobo resume: clean up after wakeup
03/02/18-07:02:12 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true

Here are screenshots of my battery.log and my system_stat
![filemanager_2018-mar-02_070440](https://user-images.githubusercontent.com/28014131/36886545-51f0489e-1ded-11e8-8e2e-feabf5bd4833.png)
![filemanager_2018-mar-02_070504](https://user-images.githubusercontent.com/28014131/36886546-520b2d1c-1ded-11e8-8610-6fd850e1f498.png)

**Comment by Frenzie** [comment]
300,000 sleeps and 8 wakeups?! O_o

For me (on H2Ov1) it looks like how I assume it's supposed to look:

* Started at Feb 26
* up hours 96 (!= active hours)
* wake-ups: **6**
* sleeps: **14** (not quite sure why that's twice as high as wake-ups; maybe from me canceling the truly going to sleep 10 second timeout)

Battery usage: negligible.

**Comment by cramoisi** [comment]
Yup, I got this three days ago, the first night of my reinstallation, then I commented on the #2854 and disabled the magnet (like I did 18 months ago). The second night, I charge the reader but from 7 am when I unplugged it to 8:45 am when I woke it up, it dropped to 75%. Because I used it plugged to my computer for adding book, the third night, I was at 97% when I put it to sleep and 50% 7 hours later...

**Comment by Frenzie** [comment]
I use non-real suspend as a quick wifi off toggle. I'm just not sure if I did it more than once or twice. Probably just a minor bug in the stats or something. But I imagine 300,000 is indicative of something a little bit more… nefarious. >_>

**Comment by cramoisi** [comment]
Looked like I missed a 0 in my #2854 comment. It was 340,000+ and from 95 to 15.

Did a test during the last 1.5 hour : 8 sleeps for 2 wake-ups

**Comment by Frenzie** [comment]
Have you checked if Nickel has the same issue?

**Comment by cramoisi** [comment]
nope I haven't run nickel since I'm using koreader, but this morning, I anticipated to do it this night

**Comment by cramoisi** [comment]
@Frenzie : not a problem with nickel

**Comment by Frenzie** [comment]
@poire-z You also have a Glo HD, don't you?

**Comment by poire-z** [comment]
Yes. But I don't have any such problem, my "`sleeps`" stays at the number of suspend I did (1, last night).
Note that I have many plugins disabled, and quite a few stuff patched, but nothing related to suspend that I can see. I also have KSM 0.7 and an old Kobo firwmare (3.16.0).

No real idea about why this happens. The `sleeps` field is not even a linux system number, it's just the number this onSuspend was called:
https://github.com/koreader/koreader/blob/68e63df442a414f851a639f630b80ad00d65db69/plugins/systemstat.koplugin/main.lua#L209-L212

May be you could add `"debug" = true,` to your `settings.reader.lua` for the next night, may be you'll see more of what happens.

**Comment by cramoisi** [comment]
@poire-z 
Ok, i'll do that !
For the kobo : KSM 8 with 3.14 but nothing is disabled, and except a custom kobolight plugin (to only enable the tap, disabling the swap)

**Comment by poire-z** [comment]
And you could stick in the above function:
``` lua
 function SystemStat:onSuspend() 
     self.suspend_sec = os.time()
     log.info("SystemStat:onSuspend() called") -- this
     self.sleep_count = self.sleep_count + 1 
end
```
and no need to let it run and generate logs for the whole night, I guess if you suspend it for an hour, you may already get the `sleeps` count increase at an anormal rate.
(Unless you have magnetic neighbours that come home only at night that would trigger the sleepcover magnet stuff :)

**Comment by cramoisi** [comment]
@poire-z @Frenzie : the issue seems limited to post-january stable (before my crash, I used a nightly from end of january without problem); I will set up the reader for debug and let it sleep on 1425 the day. And I'll do 1423 this night.

**Comment by Frenzie** [comment]
These are the only things I see that could affect suspend:
https://github.com/koreader/koreader/pull/3608
https://github.com/koreader/koreader/pull/3619

**Comment by cramoisi** [comment]
@poire-z @Frenzie with 1525 : something is off : 5.55 hours sleeping and 3 wake-ups but 0 sleeps. Something due to the code I added ? (even if I don't know how it could be). And eating 5% of battery for 6 hours of sleeping seems to me a lot. The sleeping are no more registered (I just test it now)

**Comment by poire-z** [comment]
my bad, No `log` object in this plugin. So the call to this SystemStat:onSuspend() failed before increasing the counter.
Try this instead:
``` lua
 function SystemStat:onSuspend() 
     self.suspend_sec = os.time()
     require("logger").info("SystemStat:onSuspend() called") -- this
     self.sleep_count = self.sleep_count + 1 
end
```

**Comment by cramoisi** [comment]
Ok, will let sleep again until 8pm

**Comment by cramoisi** [comment]
Don't know. The cover touching the screen ? I will leave sleeping open for the next hours and we'll see the result.

**Comment by Frenzie** [comment]
> What that's tap event around the bottom right corner ?! Looks like it happens every 400ms and may be preventing suspend...

It shouldn't. Taps are ignored after suspend has been initiated.

**Comment by cramoisi** [comment]
@Frenzie @poire-z  ok, I let the cover open and more or less the same thing but not at the same coordinates. (the log is lighter this time)

https://www.dropbox.com/s/pyvvsxgm3uar1wu/crash_log_2.txt?dl=0

[crash_log_2.txt](https://github.com/koreader/koreader/files/1778745/crash_log_2.txt)

**Comment by poire-z** [comment]
Not really the same thing, it seemed to have sleep without any event between 16:14 and 18:27:

```
03/04/18-16:14:52 DEBUG BackgroundRunnerWidget:onSuspend() @  1520176492
03/04/18-16:14:52 ERROR failed to call event handler onSuspend plugins/systemstat.koplugin/main.lua:211: attempt to index global 'log' (a nil value)
03/04/18-16:14:52 DEBUG Suspending...
03/04/18-16:14:52 DEBUG show widget unknown
03/04/18-16:14:52 DEBUG refresh: full
03/04/18-16:14:52 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 17323.861100
ifconfig: SIOCSIFADDR: No such device
wlarm_le: wl driver adapter not found
ifconfig: SIOCGIFFLAGS: No such device
03/04/18-16:14:53 DEBUG BackgroundRunner: _execute() @  1520176493
03/04/18-16:14:53 DEBUG BackgroundRunnerWidget: stop running @  1520176493
03/04/18-16:15:08 INFO  Kobo suspend: going to sleep . . .
03/04/18-16:15:08 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
03/04/18-16:15:10 INFO  Kobo suspend: waited for 2s because of reasons...
03/04/18-16:15:10 INFO  Kobo suspend: synced FS
03/04/18-16:15:10 INFO  Kobo suspend: asking for a suspend to RAM . . .
03/04/18-16:15:10 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
<slept here>
03/04/18-18:27:35 INFO  Kobo suspend: woke up!
03/04/18-18:27:35 DEBUG Kobo suspend: scheduing unexpected wakeup guard
03/04/18-18:27:35 DEBUG key event => type: 1, code: 116(Power), value: 1, time: 17342.500041
03/04/18-18:27:35 DEBUG save default dictionary
03/04/18-18:27:35 DEBUG Already in screen saver mode, suspending...
03/04/18-18:27:35 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 17342.500044
03/04/18-18:27:35 DEBUG key event => type: 1, code: 116(Power), value: 0, time: 17342.600017
03/04/18-18:27:35 DEBUG Resuming...
03/04/18-18:27:35 INFO  Kobo resume: clean up after wakeup
03/04/18-18:27:35 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
03/04/18-18:27:35 DEBUG close screensaver
03/04/18-18:27:35 DEBUG close widget
03/04/18-18:27:35 DEBUG BackgroundRunnerWidget:onResume() @  1520184455
03/04/18-18:27:35 DEBUG BackgroundRunnerWidget: start running @  1520184455
03/04/18-18:27:35 DEBUG blitFrom 1052 0 0 0 20 20
03/04/18-18:27:35 DEBUG refresh: partial -1 -1 1074 1450
03/04/18-18:27:35 DEBUG update area conflicts with active update 1
03/04/18-18:27:35 DEBUG waiting for completion of update 1
03/04/18-18:27:35 DEBUG duration: 0
```
I guess at this point, it's you using the device :)

**Comment by cramoisi** [comment]
Yup, your, right. 16h14 would be the time I open the cover (after reading your comment). I put it to sleep at 16.00 but open it after that... So what, is the screen receiving inputs during sleeping ?

[ev.log](https://github.com/koreader/koreader/files/1778759/ev.log)

got this too

**Comment by poire-z** [comment]
Btw, the setting is named `ignore_power_sleepcover` (not `ignore_sleepcover_magnet` as you wrote above, but may be you just mistyped it here).
I guess that even with or without this setting, any such `SleepCoverClosed` or `SleepCoverOpened` event would still wake up the device, and it would just go back to sleep (but still making the `sleeps` counter increase):
https://github.com/koreader/koreader/blob/f74f19bd9fe4d864f028b8bf715ad4bbb2c28d95/frontend/ui/uimanager.lua#L108-L126

So, you may have a problem with your cover, or the internal counterpart of it in the device :|
(I don't have any cover, don't know much about how that work.)

**Comment by cramoisi** [comment]
I just mistyped it there, it's correct in the settings. But the point is I don't have a sleepconver (there is a cover, but there is no magnet in it, so it's a cover but not a sleepcover :)

**Comment by poire-z** [comment]
Dunno, may be something with the static electricity in the air with the cold dry days we had made it become magnetic :)
Anyway, do your futur tests with your _non-sleep-cover_ opened :) just to be sure.

**Comment by cramoisi** [comment]
My aura also register them : 334 sleeps and 2 wake-ups for the two last hours  (but it has a magnetic cover)

**Comment by cramoisi** [comment]
For the **gloHD**, leaving without anything touching the screen, no problems  when nothing touch the screen :

![reader_2018-mar-05_065022](https://user-images.githubusercontent.com/28014131/36959344-d36c4c6e-2041-11e8-8dc6-508e01e36b98.png)
![reader_2018-mar-05_065058](https://user-images.githubusercontent.com/28014131/36959345-d3865ae6-2041-11e8-8a21-ea1f47240826.png)

03/04/18-20:59:05 DEBUG BackgroundRunner: _execute() @  1520193545
03/04/18-20:59:05 DEBUG BackgroundRunnerWidget: stop running @  1520193545
03/04/18-20:59:20 INFO  Kobo suspend: going to sleep . . .
03/04/18-20:59:20 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
03/04/18-20:59:22 INFO  Kobo suspend: waited for 2s because of reasons...
03/04/18-20:59:23 INFO  Kobo suspend: synced FS
03/04/18-20:59:23 INFO  Kobo suspend: asking for a suspend to RAM . . .
03/04/18-20:59:23 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
03/05/18-06:50:06 INFO  Kobo suspend: woke up!
03/05/18-06:50:06 DEBUG Kobo suspend: scheduing unexpected wakeup guard
03/05/18-06:50:06 DEBUG AutoSuspend:_schedule registered settings_id  1  does not equal to current one  2
03/05/18-06:50:06 DEBUG key event => type: 1, code: 116(Power), value: 1, time: 114.160042
03/05/18-06:50:06 DEBUG AutoSuspend: onInputEvent
03/05/18-06:50:06 DEBUG save default dictionary
03/05/18-06:50:06 DEBUG Rename  /mnt/onboard/.hidden/library/Pratchett, Terry - 16_Accros du roc.sdr/metadata.epub.lua  to  /mnt/onboard/.hidden/library/Pratchett, Terry - 16_Accros du roc.sdr/metadata.epub.lua.old
03/05/18-06:50:06 DEBUG Write to  /mnt/onboard/.hidden/library/Pratchett, Terry - 16_Accros du roc.sdr/metadata.epub.lua
03/05/18-06:50:06 DEBUG AutoSuspend: onSuspend
03/05/18-06:50:06 DEBUG AutoSuspend: deprecateLastTask  3

**Comment by cramoisi** [comment]
for the **KA1** : 

03/04/18-22:39:39 DEBUG BackgroundRunner: _execute() @  1520199579
03/04/18-22:39:39 DEBUG BackgroundRunnerWidget: stop running @  1520199579
03/04/18-22:39:54 INFO  Kobo suspend: going to sleep . . .
03/04/18-22:39:54 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
03/04/18-22:39:56 INFO  Kobo suspend: waited for 2s because of reasons...
03/04/18-22:39:56 INFO  Kobo suspend: synced FS
03/04/18-22:39:56 INFO  Kobo suspend: asking for a suspend to RAM . . .
03/04/18-22:39:56 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
03/05/18-06:06:21 INFO  Kobo suspend: woke up!
03/05/18-06:06:21 DEBUG Kobo suspend: scheduing unexpected wakeup guard
03/05/18-06:06:21 DEBUG AutoSuspend:_schedule registered settings_id  5  does not equal to current one  6
03/05/18-06:06:21 DEBUG key event => type: 1, code: 116(Power), value: 1, time: 14096.230044
03/05/18-06:06:21 DEBUG AutoSuspend: onInputEvent
03/05/18-06:06:21 DEBUG save default dictionary
03/05/18-06:06:21 DEBUG Rename  /mnt/onboard/.hidden/library/Edogawa, Ranpo - La chambre rouge.sdr/metadata.epub.lua  to  /mnt/onboard/.hidden/library/Edogawa, Ranpo - La chambre rouge.sdr/metadata.epub.lua.old
03/05/18-06:06:21 DEBUG Write to  /mnt/onboard/.hidden/library/Edogawa, Ranpo - La chambre rouge.sdr/metadata.epub.lua
03/05/18-06:06:21 DEBUG AutoSuspend: onSuspend
03/05/18-06:06:21 DEBUG AutoSuspend: deprecateLastTask  7
03/05/18-06:06:21 DEBUG BackgroundRunnerWidget:onSuspend() @  1520226381
03/05/18-06:06:21 INFO  SystemStat:onSuspend() called
03/05/18-06:06:21 DEBUG Already in screen saver mode, suspending...
03/05/18-06:06:21 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 14096.230047
03/05/18-06:06:21 DEBUG key event => type: 1, code: 116(Power), value: 0, time: 14096.370017
03/05/18-06:06:21 DEBUG AutoSuspend: onInputEvent
03/05/18-06:06:21 DEBUG Resuming...
03/05/18-06:06:21 INFO  Kobo resume: clean up after wakeup
03/05/18-06:06:21 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
03/05/18-06:06:21 DEBUG tap to exit from screensaver
03/05/18-06:06:21 DEBUG AutoSuspend: onResume
03/05/18-06:06:21 DEBUG AutoSuspend: start at  1520226381
03/05/18-06:06:21 DEBUG AutoSuspend: schedule at  1520229981
03/05/18-06:06:21 DEBUG BackgroundRunnerWidget:onResume() @  1520226381
03/05/18-06:06:21 DEBUG BackgroundRunnerWidget: start running @  1520226381
03/05/18-06:06:21 DEBUG blitFrom 0 0 -9.5 0 1404 1872

**Comment by cramoisi** [comment]
@Frenzie @poire-z to summarize : nothing wrong when nothing touches the screen right after the sleeping. But if something does, it loops (on the KA1 and on the gloHD) between sleep and tap mode :

[crash_log, 14,5 Mb in 5 minutes](https://www.dropbox.com/s/75hql4zwp30dekw/crash_log_3.txt?dl=0)

**Comment by Frenzie** [comment]
Here's a quick breakfast hypothesis. Because the screen keeps emitting touch events, the device might end up trying to suspend over and over. That is, perhaps my failure to reproduce is because I only touched it a few times manually as opposed to continuously. (Although I *do* use a cover myself.)

https://github.com/koreader/koreader/blob/775b7a364f4b0a1b82fc236d4aaa6513922f9904/frontend/ui/uimanager.lua#L143-L152

Maybe related:
https://github.com/koreader/koreader/blob/8a5b88878995e23b8869e4da14543145b182cd7f/frontend/device/generic/device.lua#L94-L98

Originally it did exactly what I would propose you test (remove that line):

https://github.com/koreader/koreader/commit/45f3294f8d2d17ea6144cbae94e5b71dac491b0e

Which would mean it was broken ten months ago in https://github.com/koreader/koreader/pull/2772 However, it must've been added for a reason. :-/

Also of potential interest: https://github.com/koreader/koreader/pull/2245

And finally, a picture of my cover:
![2018-03-05 07 52 52](https://user-images.githubusercontent.com/202757/36961166-58724c1c-204a-11e8-935a-9bb35b894b69.jpg)

**Comment by cramoisi** [comment]
ka1 : Run it and directly sleeping (with closing sleepcover) at 8:25 - 8:30. Spent nearly 1 minute for effectively sleeping.

[crash.log](https://github.com/koreader/koreader/files/1779882/crash.log)

[ev.log](https://github.com/koreader/koreader/files/1779888/ev.log)

**Comment by Frenzie** [comment]
Sorry, I think I was a bit unclear but just to be sure you mean edited uimanager like this?

```lua
 self.event_handlers["__default__"] = function(input_event) 
     if Device.screen_saver_mode then 
         -- Suspension in Kobo can be interrupted by screen updates. We 
         -- ignore user touch input here so screen udpate won't be 
         -- triggered in suspend mode 
         --self:suspend() -- none of this, return instead
        return
     else 
         self:sendEvent(input_event) 
     end 
end 
```

**Comment by cramoisi** [comment]
will do it now !

**Comment by Frenzie** [comment]
I can confirm btw that tapping at the screen at random even for just a few seconds results in a massive amount of "sleeps". Haven't been able to try my suggested patch yet.

**Comment by cramoisi** [comment]
what did you kill to make your cover ? :-)

**Comment by Frenzie** [comment]
When I was little that Sullivan guy showed up in my bedroom and I was _not_ amused. #fivenightsatfrenzies

**Comment by cramoisi** [comment]
yup, the number of sleeps keeps close to normal

**Comment by cramoisi** [comment]
[crash.log](https://github.com/koreader/koreader/files/1788002/crash.log)

from KA1 (with the cover and without the cover) : you can see the multi calling when something touch the screen and even without cover, you can see (like this morning around 6) multi calling too (but lesser)

**Comment by ice-blaze** [comment]
With the new nightlybuild  https://github.com/koreader/koreader/releases/tag/v2018.03.14-beta and no `backlight` and no `wifi` activated, the problem seems to not appear on a `Kobo aura one`.

Can others confirm this ?

**Comment by cramoisi** [comment]
yep, i think it's because of the capacitive screen which doesn't get input from other thing than fingers

**Comment by melote** [comment]
@cramoisi nope, but i do have a magnet cover(it's normal for last nightly version), i will test that case which removes the cover.

**Comment by melote** [comment]
@cramoisi i tested last night, the battery has 91% after a  night(i think it's abnormal) and the device became dead, i just reboot it. so sad.

**Comment by ice-blaze** [comment]
@melote Have you tried to disable the WiFi ?

**Comment by cramoisi** [comment]
\o/

**Comment by RobinFrcd** [comment]
Hi,
I'm on koreader-beta-20180412 release, the #3706 fix should be included in this release, right ? I still have the battery drain issue, from 80% to 9% in a night (sleeping mode with a pdf in background)

**Comment by Frenzie** [comment]
Yes, this would be included.

**Comment by Iey4iej3** [comment]
It looks like that sleep with a PDF open still drains battery much higher than without opening anything (around 0.1% per hour or so). I will try to keep sleep for a while to catch a `crash.log` to diagnose (just checked logs for a sleep for 10 minutes, and nothing happened, so I will catch one longer).
