### ISSUE TITLE
Problem with nightly build for other devices.

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#3711]
I just saw this comment: https://github.com/koreader/koreader/issues/3706#issue-301668927

And, after I checked, I see that last complete is 1525 build, 1529 and 1530 have only ubuntu version.

Is it normal? http://build.koreader.rocks/download/nightly/

**Comment by Frenzie** [comment]
Not normal, but I'm not really sure what's up since there's no obvious error message that I see and there's plenty of space available. Note that you can grab all the nightly builds (including Android x86 which isn't properly signed) from https://gitlab.com/koreader/nightly-builds/-/jobs

**Comment by Frenzie** [comment]
Alright, I fixed it with a little help from @poire-z 's watchful eye. I also took the opportunity to add the Android x86 build to the mix.

Relevant commits: https://github.com/koreader/koreader-misc/compare/290c537414a3c028cfd33a898d8ae3c8561c3616...2967296a64f7414a8c0f375be5c55ab39b2c82c4

**Comment by Eduardomb22** [comment]
It seems that the bug is happening again

**Comment by Frenzie** [comment]
Usually GitLab changes something. This time around it's my fault. ;-) https://github.com/koreader/koreader/pull/3723#issuecomment-371742301

**Comment by Frenzie** [comment]
@Eduardomb22 
Okay, the nightlies are up. See https://github.com/koreader/koreader-misc/pull/15

**Comment by Eduardomb22** [comment]
@Frenzie Sorry for pinging you at a closed issue, but can you look if there is a problem with the nightly releases?

**Comment by Frenzie** [comment]
GitLab is having some issues mirroring the repo so it thinks nothing's changed.
