### ISSUE TITLE
crash when trying to open configure dialog 

### ISSUE THREAD

**Issue by frankyifei** [koreader/koreader#3728]
* KOReader version: pulled from git 
* Device: kindle pw1

#### Issue
only happens to this Epub
I can still read normally but crash when I tried to open configure dialog by tapping in the top middle or 
##### `crash.log` (if applicable)
```
03/07/18-10:25:51 INFO  opening file /mnt/us/documents/西游记.epub
03/07/18-10:25:51 DEBUG data is read from  /mnt/us/documents/西游记.sdr/metadata                                                                                                                                                             .epub.lua
03/07/18-10:25:51 DEBUG ImageWidget: _render'ing resources/icons/dogear.png
03/07/18-10:25:51 DEBUG ImageWidget: _render'ing resources/icons/appbar.book.ope                                                                                                                                                             n.png
03/07/18-10:25:51 INFO  RD loaded plugin backgroundrunner at plugins/backgroundr                                                                                                                                                             unner.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin batterystat at plugins/batterystat.kopl                                                                                                                                                             ugin
03/07/18-10:25:51 INFO  RD loaded plugin calibrecompanion at plugins/calibrecomp                                                                                                                                                             anion.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.ko                                                                                                                                                             plugin
03/07/18-10:25:51 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin newsdownloader at plugins/newsdownloade                                                                                                                                                             r.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin percepton_expander at plugins/perceptio                                                                                                                                                             nexpander.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplug                                                                                                                                                             in
03/07/18-10:25:51 INFO  RD loaded plugin statistics at plugins/statistics.koplug                                                                                                                                                             in
03/07/18-10:25:51 INFO  RD loaded plugin systemstat at plugins/systemstat.koplug                                                                                                                                                             in
03/07/18-10:25:51 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
03/07/18-10:25:51 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
03/07/18-10:25:51 DEBUG CreDocument: set view dimen {
    ["h"] = 1024,
    ["w"] = 758
}
03/07/18-10:25:51 DEBUG CreDocument: set status line property 1
03/07/18-10:25:51 DEBUG CreDocument: set style sheet ./data/epub.css
03/07/18-10:25:51 DEBUG CreDocument: set embedded style sheet 1
03/07/18-10:25:51 DEBUG CreDocument: set page margins 13 19 13 28
03/07/18-10:25:51 DEBUG CreDocument: set floating punctuation 1
03/07/18-10:25:51 DEBUG CreDocument: set txt preformatted 1
03/07/18-10:25:51 DEBUG CreDocument: set font face STBShusong
03/07/18-10:25:51 DEBUG CreDocument: set header font Noto Sans
03/07/18-10:25:51 DEBUG CreDocument: set font size 28
03/07/18-10:25:51 DEBUG CreDocument: toggle font bolder 0
03/07/18-10:25:51 DEBUG CreDocument: set font hinting mode 2
03/07/18-10:25:51 DEBUG CreDocument: set interline space 100
03/07/18-10:25:51 DEBUG CreDocument: set gamma index 15
03/07/18-10:25:52 DEBUG CreDocument: set hyphenation dictionary English_US_hyphe                                                                                                                                                             n_(Alan).pdb
03/07/18-10:25:52 DEBUG CreDocument: set visible page count 1
03/07/18-10:25:53 DEBUG CreDocument: goto page 64
03/07/18-10:25:53 DEBUG CreDocument: goto xpointer /body/DocFragment[8]/body/p[2                                                                                                                                                             8]/text().134
03/07/18-10:25:53 DEBUG show widget ReaderUI
03/07/18-10:25:53 DEBUG refresh: full -1 -1 760 1026
03/07/18-10:25:53 DEBUG assigned marker 1 to update: {
    ["refreshtype"] = 1,
    ["time"] = 1520384153644.8,
    ["rect"] = {
        ["y"] = 0,
        ["x"] = 0,
        ["h"] = 1024,
        ["w"] = 758
    },
    ["waveform_mode"] = 2
}
03/07/18-10:25:53 DEBUG refresh: wait for submission

./luajit: frontend/ui/widget/configdialog.lua:473: attempt to index a nil value
stack traceback:
        frontend/ui/widget/configdialog.lua:473: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/ui/widget/configdialog.lua:668: in function 'update'
        frontend/ui/widget/configdialog.lua:695: in function 'onShowConfigPanel'
        frontend/apps/reader/modules/readerconfig.lua:75: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
        frontend/apps/reader/modules/readermenu.lua:312: in function 'handler'
        frontend/ui/widget/container/inputcontainer.lua:197: in function 'handleEvent'
        frontend/ui/uimanager.lua:455: in function 'sendEvent'
        frontend/ui/uimanager.lua:46: in function '__default__'
        frontend/ui/uimanager.lua:684: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:745: in function 'handleInput'
        frontend/ui/uimanager.lua:789: in function 'run'
        ./reader.lua:201: in main chunk
        [C]: at 0x000139fd
```

[西游记.zip](https://github.com/koreader/koreader/files/1787335/default.zip)

**Comment by Frenzie** [comment]
Odd, it doesn't seem to crash for me. Did you change anything previously? (Maybe you could also share the 西游记.sdr/metadata.epub.lua?)

https://github.com/koreader/koreader/blob/5aa40fc6f176e5a61c8cc4bc8e20c925e84228b0/frontend/ui/widget/configdialog.lua#L467-L478

**Comment by frankyifei** [comment]
`-- we can read Lua syntax here!
return {
    ["kopt_word_spacing"] = 0.05,
    ["render_mode"] = 0,
    ["highlight_drawer"] = "lighten",
    ["kopt_screen_mode"] = "portrait",
    ["gamma"] = 1,
    ["kopt_page_margin"] = 0.1,
    ["show_overlap_enable"] = false,
    ["kopt_defect_size"] = 1,
    ["doc_props"] = {
        ["creationDate"] = "",
        ["keywords"] = "",
        ["producer"] = "",
        ["authors"] = "吴承恩",
        ["description"] = "",
        ["subject"] = "",
        ["title"] = "西游记",
        ["language"] = "",
        ["modDate"] = "",
        ["creator"] = "",
        ["series"] = "",
        ["author"] = "吴承恩"
    },
    ["kopt_auto_straighten"] = 0,
    ["gamma_index"] = 15,
    ["highlights_imported"] = true,
    ["kopt_page_scroll"] = 0,
    ["copt_screen_mode"] = "portrait",
    ["kopt_writing_direction"] = 0,
    ["copt_embedded_css"] = 1,
    ["partial_md5_checksum"] = "42dd4cc9e4a8bebd9fc15a2407cb7f0b",
    ["kopt_page_opt"] = 0,
    ["highlight"] = {},
    ["embedded_css"] = true,
    ["highlight_disabled"] = false,
    ["copt_view_mode"] = 0,
    ["css"] = "./data/epub.css",
    ["doc_pages"] = 717,
    ["font_embolden"] = 0,
    ["copt_line_spacing"] = 100,
    ["kopt_contrast"] = 1,
    ["kopt_text_wrap"] = 1,
    ["copt_page_margins"] = {
        [1] = 10,
        [2] = 15,
        [3] = 10,
        [4] = 15
    },
    ["bookmarks"] = {},
    ["font_size"] = 22,
    ["screen_mode"] = "portrait",
    ["kopt_font_fine_tune"] = 0.05,
    ["inverse_reading_order"] = false,
    ["last_xpointer"] = "/body/DocFragment[8]/body/p[28]/text().134",
    ["stats"] = {
        ["performance_in_pages"] = {
            [1471662070] = 21,
            [1471662729] = 44,
            [1469361553] = 1,
            [1471662756] = 46,
            [1471663030] = 59,
            [1471662089] = 22,
            [1471662368] = 28,
            [1471662890] = 55,
            [1471661976] = 15,
            [1471662906] = 54,
            [1471662864] = 51,
            [1471662414] = 30,
            [1471662511] = 33,
            [1471662800] = 48,
            [1471662715] = 43,
            [1471662375] = 29,
            [1471662526] = 34,
            [1471662227] = 26,
            [1471662535] = 35,
            [1471662815] = 49,
            [1471662953] = 57,
            [1471662012] = 20,
            [1471663074] = 64,
            [1475882616] = 74,
            [1475882578] = 69,
            [1471663036] = 60,
            [1471662673] = 41,
            [1471662659] = 39,
            [1471662607] = 37,
            [1471662194] = 25,
            [1471662461] = 31,
            [1475882515] = 65,
            [1471661933] = 13,
            [1471662567] = 36,
            [1471662166] = 24,
            [1471662687] = 42,
            [1475882563] = 66,
            [1471662936] = 56,
            [1471663052] = 63,
            [1475882610] = 73,
            [1471661956] = 14,
            [1471662742] = 45,
            [1475882594] = 72,
            [1471662318] = 28,
            [1471662491] = 32,
            [1471662356] = 29,
            [1471662783] = 47,
            [1475882509] = 64,
            [1471662644] = 38,
            [1471662829] = 50,
            [1475479068] = 64,
            [1471662876] = 54,
            [1471662138] = 23,
            [1475882571] = 68,
            [1471662270] = 27,
            [1471663025] = 58
        },
        ["md5"] = "42dd4cc9e4a8bebd9fc15a2407cb7f0b",
        ["authors"] = "吴承恩",
        ["total_time_in_sec"] = 1227,
        ["notes"] = 0,
        ["title"] = "西游记",
        ["highlights"] = 0,
        ["pages"] = 717,
        ["series"] = "",
        ["language"] = ""
    },
    ["config_panel_index"] = 6,
    ["line_space_percent"] = 100,
    ["kopt_forced_ocr"] = 0,
    ["header_font_face"] = "Noto Sans",
    ["floating_punctuation"] = 1,
    ["hyph_alg"] = "English_US_hyphen_(Alan).pdb",
    ["copt_font_weight"] = 0,
    ["copt_status_line"] = 1,
    ["font_face"] = "STBShusong",
    ["readermenu_tab_index"] = 7,
    ["percent_finished"] = 0.0139470013947,
    ["zoom_mode"] = "page",
    ["bbox"] = {},
    ["flipping_scroll_mode"] = false,
    ["disable_fuzzy_search"] = false,
    ["flipping_zoom_mode"] = "page",
    ["kopt_full_screen"] = 1,
    ["page_positions"] = {
        [1] = 0,
        [2] = 0,
        [3] = 0,
        [4] = 0,
        [5] = 0,
        [6] = 0,
        [7] = 0,
        [8] = 0,
        [9] = 0,
        [10] = 0
    },
    ["last_page"] = 10,
    ["kopt_detect_indent"] = 1,
    ["kopt_max_columns"] = 2,
    ["copt_font_size"] = 22,
    ["kopt_font_size"] = 1,
    ["kopt_justification"] = 3,
    ["kopt_quality"] = 1,
    ["page_overlap_style"] = "dim",
    ["kopt_line_spacing"] = 1.2,
    ["normal_zoom_mode"] = "page",
    ["kopt_trim_page"] = 1,
    ["rotation_mode"] = 0,
    ["kopt_doc_language"] = "chi_sim",
    ["copt_font_gamma"] = 15,
    ["bookmarks_sorted"] = true
}
`

**Comment by frankyifei** [comment]
seems works after clean .sdr folder, maybe the old metadata is the problem
