### ISSUE TITLE
please change the wiki

### ISSUE THREAD

**Issue by konos93** [koreader/koreader#3730]
https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#supported-devices

"Supported Devices

Koreader can be installed on all Kindle devices; however, certain features are currently unavailable on non-touch devices such as the Kindle4 (NT) and earlier. "

please because i bought a white pw3 2018 with 5.9.2.0.1 firmware i need serial jailbreak .(which is very hard because you have to reassembly pw3 and use 1.8 volts to transfer data and not to burn anything or break something) .

so i change this with a friends one pw3 2017 with 5.8.1 firmware. i downgraded, jaibreak and install koreader after figuring out what i need to do.

**Comment by Frenzie** [comment]
Change the wiki in what sense? "on all jailbroken Kindle devices"?

Pinging @NiLuJe

**Comment by Frenzie** [comment]
I edited the text as follows:

> KOReader can be installed on all Kindle devices. Note, firmware 5.6.x and newer might require physically modding the device. More on that [here](https://www.mobileread.com/forums/showthread.php?t=267541). 
Certain features are currently unavailable on non-touch devices such as the Kindle4 (NT) and earlier. See [Issue 1898](https://github.com/koreader/koreader/issues/1898).

You should be able to update the wiki yourself if you have any other concerns. :-)
