### ISSUE TITLE
Battery drain with pdf files in sleep mode Kobo aura one

### ISSUE THREAD

**Issue by ice-blaze** [koreader/koreader#3734]
* KOReader version:
  * koreader-nightly-20180212
  * koreader-nightly-20180110
  *  koreader-nightly-20171023
  * koreader-nightly-20171004
* Device: Kobo Aura One

#### Issue
The battery drain quickly (even in sleep mode) and with PDF files (epub doesn't drain battery). (PDF on nickel doesn't drain battery neither)

#### Steps to reproduce
Open a PDF with koreader and put into sleep mode. Wait 1 hour and your battery will be drained by at least 10%.

I didn't used the magnetic cover for the tests

I don't have the battery logs...

**Comment by Frenzie** [comment]
Pinging @cramoisi

Might be related to #3706.

(Though I hasten to add that I almost exclusively read PDF, DjVu when I can because it's smaller and faster, with the occasional EPUB only.)

**Comment by cramoisi** [comment]
@Frenzie Perhaps, I my case, I'm epub and cbz only

@ice-blaze could edit your Koreader files as mentions here
[here](https://github.com/koreader/koreader/issues/3706#issuecomment-370138053) and post a crash.log after letting your reader sleeping with a open pdf file ?

**Comment by ice-blaze** [comment]
Ho sorry, yesterday I waited 4 hours in sleep mode with an epub and the battery level was the same (I double checked). But this morning (after 8 hours) the battry was drained by 40% :/

So I guess we can close this issue because it must be the same problem than on #3706. I'm just surprise my epub format some times behave differently.
