### ISSUE TITLE
[question] double koreader.sh and reader.lua process in ps -ef

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3741]
* KOReader version: 1557 with KSM9
* Device: Ka1
#### Issue
Was wondering if it's normal to get double line about koreader to in a ps -ef output (from terminal emulator in koreader) after launching it with ksm9. Reading start_koreader.sh it's more or less the same file than koreader.sh so i was exptecting it was use in the place of koreader.sh

 1042 root       0:00 {start_koreader.} /bin/sh /adds/kbmenu/onstart/start_koreader.sh
 1047 root       0:00 {koreader.sh} /bin/sh /mnt/onboard/.adds/koreader/koreader.sh
 1053 root       0:56 {reader.lua} ./luajit ./reader.lua /mnt/onboard
 1057 root       0:00 {reader.lua} ./luajit ./reader.lua /mnt/onboard
 1063 root       0:00 sh -c ps -ef
 1064 root       0:00 ps -ef

#### Steps to reproduce
launch koreader with ksm, choose terminal in koreader's menu and type ps -ef ; get the result.
##### `crash.log` (if applicable)
[terminal_output.txt](https://github.com/koreader/koreader/files/1802901/terminal_output.txt)

**Comment by Frenzie** [comment]
Do you use the CoverBrowser? The double luajit could be process forking to render covers.

**Comment by cramoisi** [comment]
mmh, i'm in classic mode since this morning

**Comment by cramoisi** [comment]
wow the new process of metatada extraction-thing is wonderful !

**Comment by Frenzie** [comment]
What did you do with advboot exactly?

And of course thanks @poire-z for CoverBrowser! ;-)

**Comment by poire-z** [comment]
The 2nd instance of luajit you see on Kobo (and probably others) is probably a little subprocess forked (so, it keeps the same name, just like extractor forks from coverbrowser do) from the main process to deal with some kind of events (usb plug/unplug on kobo I guess).
You should see at startup in your crash.log something like:
`[ko-input] Forked off fake event generator(pid:NNN)`

https://github.com/koreader/koreader-base/blob/master/input/input.c
https://github.com/koreader/koreader-base/blob/master/input/input-kobo.h

**Comment by poire-z** [comment]
> the filemanager is sometimes in portrait mode, and sometimes in landscape mode

I've witness that too, the rare times I tested thing in landscape mode. I haven't bothered looking at it. But it's definitely an issue.

**Comment by Frenzie** [comment]
There's an issue about that, #2565 (and #2342 which I forgot about).
