### ISSUE TITLE
koreader crashes when I type one cyrillic letter inside "search wikipedia" input field

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#3742]
* KOReader version: v2015.11-1540-g8a5b888
* Device: Kobo_alyssum (kobo GLO hd, "model N437" next to reset hole)

#### Issue
koreader crashes when I type one cyrillic letter inside "search wikipedia" input field

#### Steps to reproduce

1) My koreader's language is Russian;
2) I open "Search in Wiki" (menu item named in Russian);
3) I get the "Do you want to turn on Wifi?" dialog 3 times (instead of 1 time, but this is manageable);
4) I get connected to my tethered cellphone wifi hotspot;
5) the dialog where I can enter my keywords - shows up;
6) i can type in english and with "symbols" keyboard;
7) I click the globe icon next to "space", the keyboard gets switched to cyrillic keyboard;
8) i click any cyrillic letter and then immediately the app crashes;
9) then immediately I see "Wifi is connected!" kbmenu message, I click "CLOSE" at the bottom;
10) I can start koreader again from kbmenu and I can read / scroll as usual until I search wiki in russian;

guys (multiple koreader developers) I know you are working;
besides being volunteers of open source software, I'm using it and I'm willing to pay for your work;
please whoever fixes this bug, please point me to the commit where it was fixed;
after I try the fixed version on kobo and confirm it's not crashing and allows me to search wiki, I'll pay you $20;
I think "by donation" is a correct business model for the open source software;
don't hesitate to put "ORDER THE FEATURE YOU NEED AND DONATE TO CONTRIBUTORS" everywhere ;)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

03/12/18-13:18:34 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
03/12/18-13:18:34 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
03/12/18-13:22:11 INFO  Kobo suspend: going to sleep . . .
03/12/18-13:22:11 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
03/12/18-13:22:13 INFO  Kobo suspend: waited for 2s because of reasons...
03/12/18-13:22:13 INFO  Kobo suspend: synced FS
03/12/18-13:22:13 INFO  Kobo suspend: asking for a suspend to RAM . . .
03/12/18-13:22:13 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
03/12/18-14:32:04 INFO  Kobo suspend: woke up!
03/12/18-14:32:04 INFO  Kobo resume: clean up after wakeup
03/12/18-14:32:04 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
03/12/18-14:32:06 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin percepton_expander at plugins/perceptionexpander.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
03/12/18-14:32:06 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
03/12/18-14:36:59 INFO  no dialog left to show
03/12/18-14:36:59 INFO  quitting uimanager

**Comment by Frenzie** [comment]
Looks like the nightly you're using is from 5 March. It should be fixed with #3729 (probably made it into the 8 March nightly), but I also introduced the issue a little while prior, so… ;-P

I'm afraid we currently don't have anything in place to take donations. There are some suggestions in https://github.com/FreshRSS/FreshRSS/issues/1694 @marienfressinaud seems to have looked into it the most seriously. I'm open to suggestions. :-)

**Comment by cramoisi** [comment]
@Frenzie at least, the log shows what seems to be a typo (wonder how i didn't see it before though) :

[loaded plugin percep**ton**_expander at plugins/perceptionexpander.koplugin](https://github.com/koreader/koreader/search?utf8=✓&q=percepton_expander&type=)

**Comment by worldexplorer** [comment]
the last version available on OTA did it;
i installed an update, now I run v2015.11-1556-gc5b547f_2018-03-11
tried it again
it works
no crash anymore

suggestion is to have an email for the peer-to-peer transfers
consciousness and sense of fair exchange will do the rest (payment to the developer who created and who fixed the bug haha)
I can send the paypal transfer and that's it :)
what is the email?

**Comment by Frenzie** [comment]
@cramoisi Stick it in a PR. ;-)

@worldexplorer My e-mail (which is also coupled to Paypal) is listed on [my blog](https://fransdejonge.com/about/) but I don't really know how to distribute it fairly. Pinging @Hzj-jie if the server costs anything in particular since that would probably make the most sense to pay for.

**Comment by Frenzie** [comment]
@worldexplorer It worked, thanks for the donation!

> Pavel Chuchkalov sent you 15,53 EUR.

> for the hosting of nightly builds koreader issues 3742

**Comment by Hzj-jie** [comment]
Technically speaking, the server definitely costs. But I do not pay it myself. Thanks to my company to cover the cost :)

**Comment by Frenzie** [comment]
Very well. In that case we have €15,53 of KOReader funds for yet to be determined purposes. Thanks to your company indeed. :-)

**Comment by Frenzie** [comment]
Closing this since it was fixed. Thanks again for the donation! Pity we don't really have a use for it right now, but perhaps that's a good thing. :-)
