### ISSUE TITLE
too many clicks when connecting to wifi

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#3743]
* KOReader version: v2015.11-1556-gc5b547f_2018-03-11
* Device: kobo GLO HD

#### Issue

first wifi dialog is empty (unnecessary), second dialog could function smarter (I hate clicking when user's choice is obvious)

#### Steps to reproduce

I love wikipedia, studying health-related articles
I download the articles via wifi that kobo establishes to my cellphone
1) when connecting to a wifi, I'm getting the wifi connect dialog three times
2) first definitely looks like a bug and shows up as a window with no content at all;
3) second time I click "yes connect to wifi" the new dialog lists the wifi networks;
4) I have to click on the network I connected previously (please make that setting "yes" by default that says "connect to the known network automatically" or smth like that) 
5) If there are multiple known networks then I want to switch between them, so clicking on the other recently used network with a password saved should not ask "you are connected right now, do you want to disconnect?" - of course I want to disconnect because I want to connect to the other one
6) after I'm connected, I need to click somewhere again to continue ("okay" or outside of the window to make it disappear); why? it should disappear by itself with a status somewhere (new icon next to the battery) that I'm connected;
7) after I'm connected, I need to click again "please download the wikipedia article"

all I wanted is to download wikipedia article;
but in total there are 4-8 clicks which might have been avoided.
please make the wifi connecting interface just like you'd like it yourself :)

in the next issues I would explain what I find clumsy in koreader (despite that's my favourite reader);
each next ebook I click all the same buttons over and over again (and let my settings survive the OTA update):
1) I would like to choose the font for all epubs - once and forever;
2) I would like to have the full progress bar - once and forever;
3) I would like to disable internal CSS of all epubs that I will be opening - once and forever;
4) I would like to have font tinting / contrast in a larger scale, not "light"=5 "normal"=10 "dark"=25 but a selector between 5...40 just like with frontlight 0..100, with the default I set for all the future epubs;

5) when saving an article from wiki, I don't need a preview (let me uncheck "I need a preview" on a single dialogue that follows), just show one dialog if I need pictures (I fill it once and forever "yes I need pictures", "highest resolution"), what is the path that I want to save the new article to, with autocreation of the directory and probably file chooser.... etc etc, I can create a UI flow and will add into the ticket

**Comment by Frenzie** [comment]
For a lot of those, try long-pressing. ;-)

> I would like to have font tinting / contrast in a larger scale, not "light"=5 "normal"=10 "dark"=25 but a selector between 5...40 just like with frontlight 0..100, with the default I set for all the future epubs;

Isn't that more or less what @poire-z added just a couple of days ago in #3737?

**Comment by poire-z** [comment]
Auto-enable/disable WiFi is now possible since #6424.
