### ISSUE TITLE
Translate Goodreads login info

### ISSUE THREAD

**Issue by theojesed** [koreader/koreader#3748]
* KOReader version: All
* Device: All

#### Issue

I can not locate the Goodreads login information box on Transifex so I can translate. I think it's an important part of understanding the login system.

#### Screenshot
![Image](https://i.imgur.com/C1tlxjX.png)

**Comment by Frenzie** [comment]
Indeed, looks like it's not currently translated. 

https://github.com/koreader/koreader/blob/9f50ef696f8e63196ced4675908f03dd73294628/plugins/goodreads.koplugin/main.lua#L79-L83

I'll fix it up to something like this:

```lua
_([[
How to generate a key and a secret key:
1. Go to https://www.goodreads.com/user/sign_up and create an account
2. Register for a development key on the following page: https://www.goodreads.com/user/sign_in?rd=true
3. Your key and secret key will now be available on https://www.goodreads.com/api/key
4. Enter your generated key and your secret key in the settings dialog (Login to Goodreads window)
]])

Btw, is that API page on GR available in languages other than English? (If so, props to them.)

**Comment by theojesed** [comment]
As you do not need to understand much of English to access the site, the number of users and friends of my country has grown anyway. I hope they will soon implant more languages.
