### ISSUE TITLE
Supported translations need updating

### ISSUE THREAD

**Issue by JSabio** [koreader/koreader#3749]
Hello guys,

Sorry for bad posting, but can someone check the ttransifex translations?
I applied for the basque one and I want to finish it this month.

Thank you.

**Comment by Frenzie** [comment]
Odd, I thought I approved you two days ago. 

Note to self or someone, support from the KOReader menu needs to be manually added at the moment, so I'll label this a bug as a reminder.

https://github.com/koreader/koreader/blob/ed36ab3f9b46693cf69d9f19ddc6e2b8f2bf7d11/frontend/ui/language.lua#L36-L70

**Comment by JSabio** [comment]
I check it again and now it's correct, could be a cache or smth...

Thanks for reply frenzie
