### ISSUE TITLE
Menu button crashes on Inkbook

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3758]
* KOReader version: koreader-beta-20180314
* Device: Inkbook 

Kr crashes (disappears) as soon as I press the menu (android menu) hardare button on Inkbook. Kr does not crash if I try to access the top menu with a tap at the top of the screen. So something about accessing with a hardware button/

I believe this is the relevant part of the log 

I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0                                                                                                       [111/1902]
I/KOReader(17104): DEBUG ImageWidget: _render'ing resources/icons/appbar.settings.large.png 51 51
I/KOReader(17104): DEBUG cache image|resources/icons/appbar.settings.large.png|51|51
I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0
I/KOReader(17104): DEBUG ImageWidget: _render'ing resources/icons/appbar.transform.rotate.right.large.png 51 51
I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0
I/KOReader(17104): DEBUG ImageWidget: _render'ing resources/icons/appbar.column.two.large.png 51 51
I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0
I/KOReader(17104): DEBUG ImageWidget: _render'ing resources/icons/appbar.text.size.large.png 51 51
I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0
I/KOReader(17104): DEBUG ImageWidget: _render'ing resources/icons/appbar.grade.b.large.png 51 51
I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0
I/KOReader(17104): DEBUG ImageWidget: _render'ing resources/icons/appbar.settings.large.png 51 51
I/KOReader(17104): DEBUG ImageWidget: initial offsets 0 0
I/KOReader(17104): DEBUG show widget unknown
I/KOReader(17104): DEBUG NewsDownloader: obtaining news folder
I/KOReader(17104): DEBUG Send2Ebook: obtaining download folder
I/KOReader(17104): DEBUG Send2Ebook: obtaining download folder
E/luajit-launcher(17104): Failed to run script: frontend/apps/reader/modules/readermenu.lua:298: attempt to index local 'ges' (a nil value)
V/threaded_app(17104): android_app_destroy!
D/dalvikvm(15619): GC_CONCURRENT freed 399K, 26% free 2793K/3736K, paused 2ms+6ms, total 24ms
D/dalvikvm(  386): GC_EXPLICIT freed 396K, 23% free 7202K/9328K, paused 3ms+6ms, total 76ms
V/threaded_app(17104): Pause: 0x5cf1dfa0
D/dalvikvm(15748): GC_CONCURRENT freed 372K, 27% free 2673K/3660K, paused 3ms+1ms, total 16ms
W/EventHub(  386): --dela--getEvents()--EventHub.cpp--key == 114--
W/EventHub(  386): --dela--getEvents()--EventHub.cpp--key == 0--
I/InputReader(  386): -----dela-------processKey()------inputReader.cpp-------keyCode == 82 -----
D/dalvikvm(15619): GC_CONCURRENT freed 400K, 25% free 2803K/3736K, paused 2ms+3ms, total 22ms
D/dalvikvm(15619): GC_CONCURRENT freed 404K, 26% free 2797K/3736K, paused 2ms+4ms, total 19ms
W/ActivityManager(  386): Activity pause timeout for ActivityRecord{419da1b0 u0 org.koreader.launcher/.MainActivity}
E/DimSurface(  386): hide: no Surface
D/MainActivity(  613): onRestart()
I/BookLoader(  613): onStartLoading()
I/BookLoader(  613): onStartLoading()
I/BookLoader(  613): loadInBackground() id=1
D/MainActivity(  613): onResume()
D/MainActivity(  613): loadGridView
I/BookLoader(  613): loadInBackground() id=0

**Comment by poire-z** [comment]
This crash must have been just fixed by @onde2rock in https://github.com/koreader/koreader/commit/e8aab49ee91dda8830de8023066d5cdd3c63ccc5#diff-e8b34a49b71f8c346796bc6840a95e9bR296 , so in tomorrow's nightly.

**Comment by Frenzie** [comment]
@gerroon Confirmed fixed?

**Comment by gerroon** [comment]
Is the build up?

**Comment by gerroon** [comment]
This did not fix it 2015.11-1570-ge8aab49_2018-03-14
