### ISSUE TITLE
merge library patches upstream

### ISSUE THREAD

**Issue by anarcat** [koreader/koreader#3777]
In #2621 (wallabako support), the discussion drifted towards how the "emulator" is built, and how it has a *lot* of dependencies. Part of that problem is that we might want to create a "desktop app" instead of an "emulator" (#1417) and we want to package for Debian (#3108). But before that is actually done, we need to be able to build against system libraries for OpenSSL, libpng, mupdf and so on. There are about 40 different libraries in base/thirdparty that would need to be basically dropped before koreader enters Debian. If those libraries are like upstream as-is, that won't be too much of a problem: just add some glue to the build process to link against system libraries instead of the vendored copies and you're done.

but the problem is that there are many of those libraries that are patched, and the patches haven't been submitted upstream.

@TnS-hun commented that, in the case of MuPDF, it might not be possible to merge all patches back up:

> The encrypted zip and a better version of the external font support patches could be upstreamed, but for example the patch that changes the ICC profile error to warning is KOReader specific, so you won't be able to use MuPDF provided by the system.

I would argue, on the contrary, that such changes *could* be submitted back upstream: a discussion could be had about whether such a default would be an acceptable change, and if not, it could be made configurable somehow, from consumers of the libraries. Having those changes merged back upstream will make it easier to maintain thirdparty libraries in koreader, because they can be updated just by pulling the new version upstream, without figuring out what the patches are and how to backport them.

Here are the steps I can see to go forward from here

- [x] document which libraries are patched and which are "vanilla"
- [x] extract a meaningful patchset out of each library in a standard location (say patches/)
- [ ] submit patches upstream
- [ ] merge new upstream tree once patches are merged

Does that make sense?

Thanks!

**Comment by Frenzie** [comment]
> document which libraries are patched and which are "vanilla"

Almost everything is patched in some sense because libtool was purposefully broken by Google. See https://github.com/koreader/koreader-base/pull/521

Conversely, besides MuPDF there isn't much going on. Just search for *.patch. My dirty djvulibre patch is for Android, as are the patches for zsync and Leptonica. czmq seems to be something more generic about the build process, not Android-specific. Anyway, point being that none of those matter if you were to link them to system libraries regardless to which extent something can or cannot be submitted upstream.

Insofar as there's a problem with these patches breaking it's seldom related to porting the patch itself, but rather to upstream not keeping Android in mind. (And frankly I wouldn't either.)

> Having those changes merged back upstream will make it easier to maintain thirdparty libraries in koreader, because they can be updated just by pulling the new version upstream, without figuring out what the patches are and how to backport them.

(Look [here](https://github.com/bakpakin/luamd/commits?author=Frenzie) and [here](https://sourceforge.net/p/sdcv/patches/16/) for some of my efforts. ;-))

Unfortunately our fork of crengine has become *the* fork because upstream suffered from years of inactivity and unmerged patches. A bit like sdcv in a way, but thanks to @ecraven that was resolved last year.

**Comment by anarcat** [comment]
congrats on the efforts. :)

i would say that if one of the third-party libraries has become the upstream, you might want to split it out in its own github repo and make that official. then it's just a pinned submodule you have to deal with and things are clearer for everyone.

i guess that's the final objective here: just have those be submodules instead of code copies, that way it's clear everything is upstreamm...

**Comment by Frenzie** [comment]
I'm afraid I don't quite follow your argument. Our build system deals with at least one git submodule (our own), various git "submodules" as well as non-Git.

```
ko_write_gitclone_script(
    GIT_CLONE_SCRIPT_FILENAME
    https://gitlab.com/koreader/freetype2.git
    83c877f11c6cbd99cb203447d248748ad45624c3
    ${SOURCE_DIR}
)
```

```
ExternalProject_Add(
    ${PROJECT_NAME}
    DOWNLOAD_DIR ${KO_DOWNLOAD_DIR}
    URL ftp://sourceware.org/pub/libffi/libffi-${LIBFFI_VER}.tar.gz
    URL_MD5 83b89587607e3eb65c70d361f13bab43
    CONFIGURE_COMMAND ${CFG_CMD}
    # skip the rest, we only need the header for glib
    BUILD_COMMAND $(MAKE) -j${PARALLEL_JOBS}
    INSTALL_COMMAND $(MAKE) -j${PARALLEL_JOBS} uninstall install
)
```

Patching is quite optional.

Submodules were switched to this system in https://github.com/koreader/koreader-base/pull/353

Now I'm not saying I'm 100% happy with it but practically speaking there's no particular difference between thirdparty/kpvcrlib/crengine (submodule) and thirdparty/djvulibre/git_checkout/djvulibre (regular git repo). Their downsides are mostly shared by the way @houqp constructed the CMake system. To play around with branches or something you also need to modify the CMakeLists.txt file (`touch -a` suffices), except in the non-submodule you may also need to change the commit hash or tag. A touch (harhar) more annoying, but the main annoyance is having to modify CMakeLists.txt in the first place.

**Comment by TnS-hun** [comment]
I just wanted to note that my experience [submitting a patch](https://github.com/ArtifexSoftware/mupdf/pull/5) to MuPDF wasn't stellar, so I'm not that interested in upstreaming the remaining patches.

**Comment by poire-z** [comment]
> the discussion drifted towards how the "emulator" is built, and how it has a lot of dependencies. Part of that problem is that we might want to create a "desktop app" instead of an "emulator" (#1417) and we want to package for Debian (#3108). But before that is actually done, we need to be able to build against system libraries for OpenSSL, libpng, mupdf and so on. There are about 40 different libraries in base/thirdparty that would need to be basically dropped before koreader enters Debian.

Remember we are targeting devices, mainly dumb devices without any much system libraries (and for the few we don't build and expect to find as system libraries, it can break things, like sdcv on new kobo firmware).
So we (well, not me, I wasn't there yet:) had to build them ourselves, and the huge build process is there so it can build the world from scratch (and it does it so well, every day, for one hour, on multiple architectures). And we won't drop it for a desktop app ! :)

We don't want to build a "desktop app" _instead of_ an "emulator" : the emulator should be as near as a device, if we want to develop and fix bugs on something convenient that behave **exactly** as on a device.
Your argument in the other thread about _why should I build a full emulator when I just want to develop a plugin_ is just for that reason wrong (and, it's a quite radical reaction to being confused for a few hours with SDL and translation :)

If you want it as a desktop app, what you want is _another_ build process (a non-build process :)
Merging patches upstream is just a minor thing in that case. As @Frenzie said, we don't have much patches.

If on debian, you have all the dependancies (I think we may, luajit, lua-sockets...), well, it's just a matter of installing them all, and having luajit run our pure lua code, and it should (with our few C modules or libraries entry points).
As we use ffi to wrap libraries, it's just a matter of not building our own, and changing some paths here and there so it goes find the system libraries.
That's where the big (may be not so big) work has to be done. After that, there may be a few things with our patched libraries that won't work with system libraries, and we may need to submit upstream, or find hooks or monkey patch stuff.

But frankly, as much as I love koreader (and the emulator, to develop), on a desktop where there are alternatives, I would probably not use it as an app...

**Comment by anarcat** [comment]
On 2018-03-19 22:08:31, poire-z wrote:
> So we (well, not me, I wasn't there yet:) had to build them ourselves, and the huge build process is there so it can build the world from scratch (and it does it so well, every day, for one hour, on multiple architectures). And we won't drop it for a desktop app ! :)

Yeah, I understand, that makes sense. I'm not suggesting you drop those
libraries completely.

> We don't want to build a "desktop app" _instead of_ an "emulator" : the emulator should be as near as a device, if we want to develop and fix bugs on something convenient that behave **exactly** as on a device.

Agreed. but that discussion belongs in the desktop app issue, i think. :)

[...]

> Merging patches upstream is just a minor thing in that case. As @Frenzie said, we don't have much patches.

Maybe I overestimated this. I just thought I would open an issue so that
this is followed up on (and out of the wallabako discussion ;).

**Comment by bahusoid** [comment]
>but for example the patch that changes the ICC profile error to warning is KOReader specific, so you won't be able to use MuPDF provided by the system.

It seems it's already committed:
https://github.com/ArtifexSoftware/mupdf/commit/80b59185030368fecf38d9abe13ffb0302a60c2a

And some others ICC related commits:
https://github.com/ArtifexSoftware/mupdf/commit/2bc74c6683f4e45c4d7f60c652f906f2bc97db34
https://github.com/ArtifexSoftware/mupdf/commit/4ccc9cdc72346175fd22aafbce03847f1e287d26

**Comment by Frenzie** [comment]
@bahusoid Great!

**Comment by Frenzie** [comment]
@anarcat Good news: the djvulibre patch I added two weeks ago is now obsolete. ;-) See https://github.com/koreader/koreader-base/pull/639 and https://github.com/koreader/koreader-base/pull/655  Luckily, it goes like that more often than not.

(But like I said in my first reply, a patch like that would be irrelevant within a Debian context. If you imagine a Kobo with proper Debian you wouldn't have weird locale-related bugs in the first place because Debian is Debian.)

**Comment by Frenzie** [comment]
Since this is something we did and do I'll be closing this issue now.
