### ISSUE TITLE
building emulator on os x

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3783]
* Device: emulator

I followed the steps to build the thing on os x but it keeps erroring at this file. Had no prob to do it on ubuntu though.

brew install nasm binutils libtool autoconf automake cmake makedepend sdl2 lua51 gettext
echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

git clone https://github.com/koreader/koreader.git
cd koreader && ./kodev fetch-thirdparty

./kodev build

.... (compilation going on until : mupdf and then : )

```
AR build/release/libmupdf.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: build/release/libmupdf.a(color-lcms.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: build/release/libmupdf.a(jmemcust.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: build/release/libmupdf.a(track-usage.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: build/release/libmupdf.a(gprf-doc.o) has no symbols
    RM build/release/libmupdfthird.a
    AR build/release/libmupdfthird.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: build/release/libmupdfthird.a(hb-warning.o) has no symbols
clang: error: no such file or directory: 'build/release/libjbig2dec.a'
make[4]: *** [mupdf-prefix/src/mupdf-stamp/mupdf-build] Error 1
make[3]: *** [CMakeFiles/mupdf.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build/x86_64-apple-darwin17.4.0-debug/libs/libmupdf.dylib] Error 2
make: *** [base/build/x86_64-apple-darwin17.4.0-debug/luajit] Error 2
```

any leads ?

**Comment by Frenzie** [comment]
It could be that the build is simply broken on Mac OS. To quickly test that, try:

```
# one commit before MuPDF update in https://github.com/koreader/koreader/pull/3547
git checkout fe4d52c
git submodule --recursive
```

**Comment by Frenzie** [comment]
Oh yes, my hypothesis looks correct. For regular builds, this happened:

```diff
-    set(LINK_OPTS "${LINK_OPTS} build/release/libopenjpeg.a build/release/libmujs.a build/release/libjbig2dec.a")
+    set(LINK_OPTS "${LINK_OPTS} build/release/libmupdfthird.a")
```

The equivalent Mac OS change wasn't consistently made.

It should hopefully be an easy fix in `thirdparty/mupdf/CMakeLists.txt`. Just change this line to `set(LINK_OPTS "${LINK_OPTS} build/release/libmupdfthird.a")`

https://github.com/koreader/koreader-base/blob/9e001e18f13cd233ce4ddf8505c3472928668297/thirdparty/mupdf/CMakeLists.txt#L40

**Comment by Frenzie** [comment]
PS I'll be on Gitter: https://gitter.im/koreader/koreader

**Comment by cramoisi** [comment]
to resume : 

1/ I commented out [mupdf CMakeLists.txt#L40](https://github.com/koreader/koreader-base/blob/9e001e18f13cd233ce4ddf8505c3472928668297/thirdparty/mupdf/CMakeLists.txt#L40) to get past mupdf compilation (it worked, still, we need to have a working emulator to know the side-effects)

2/ glib failed to config as the options : `--without-included-gettext --with-gettext=no` are not recognized.

```
[ 62%] Performing configure step for 'glib'
configure: WARNING: unrecognized options: --without-included-gettext, --with-gettext
checking for a BSD-compatible install... /usr/bin/install -c
```

**Comment by Frenzie** [comment]
Guide I followed: https://www.pcsteps.com/2157-mac-os-x-virtual-machine-vmware-player/#Create_the_MacOS_High_Sierra_virtual_machine_onVirtualBox

To set the resolution:
```
VBoxManage setextradata "macOS" VBoxInternal2/EfiGraphicsResolution 1280x1024
```

(Don't know if there's a way to combine a UHD resolution with Mac scaling so I'm just using a scaling factor of 200% on that. It looks a bit fuzzy.)
