### ISSUE TITLE
Books changing size after calibre transfer

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#3791]
* KOReader version: v2015.11-1573-g0a4fb89_2018-03-15/ 
* Device: KA1

#### Issue
When I transfer the following books using calibre with USB-connection the sizes change rather dramatically.

The attached pdf (13 MB) becomes 68.9 MB.
The attached epub (5.7 MB) becomes 2.8 MB.

Otherwise, both seem to work fine.

If I instead just copy & paste using File Explorer the sizes are unchanged.

[The Allure of Battle_ A History - Cathal J. Nolan.pdf](https://github.com/koreader/koreader/files/1837524/The.Allure.of.Battle_.A.History.-.Cathal.J.Nolan.pdf)
[Portratt av en dam 1 - Henry James.zip](https://github.com/koreader/koreader/files/1837530/Portratt.av.en.dam.1.-.Henry.James.zip)

**Comment by Frenzie** [comment]
Seems more likely to be something calibre does?

**Comment by cramoisi** [comment]
@gerhaher : just put some books in your koreader's library folder with you PC only then open KOReader and look at them (you put your device in Display > Classic (filename only) before doing this : 

1. your books have the correct size and KOReader tells you they have this size --> Not a KOReader bug (but perhaps Calibre)
2. Look at the books with KORreader filemanager : if they have different sizes and KOReader tells so, then exit KOReader, plug your device and check the size of the book on your support.
---> If it's really different sizes, not a KOReader bug (but Windows or OS ?)
---> If it's not a different sizes and KOReader told you the size is different, then maybe it's a KOReader bug ;)

**Comment by gerhaher** [comment]
It's a Calibre bug. You can bury this thread if you want.

I tested to not involve KOReader and instead transfered the books (with Calibre: "Connect to folder" + "Send to device") to another folder on my PC and got the same result (incorrect sizes).

**Comment by Frenzie** [comment]
Alright, closing.
