### ISSUE TITLE
Calibre Wireless connection not working since v2018.02.12-nightly

### ISSUE THREAD

**Issue by max-cw** [koreader/koreader#3794]
* KOReader version: v2018.02.12-nightly
* Device: Kobo Auro H2Ov1

Calibre wireless connection no longer works in v2018.02.12-nightly and v2018.03.14-beta. It is working in v2018.01.10-nightly after the #3558. Seems to be a different issue.

#### Steps to reproduce
Connect to calibre server from the menu. It will immediately show the "cannot connect" error. I should also point out that there is no message box asking if I want to turn on the wifi if it's off, unlike v2018.01.10-nightly where the connector still works.

**Comment by max-cw** [comment]
Hi. It may be a naive thinking on my part, but I change the one line according to #3795. Now koreader asks me if I want to turn on the wifi, but the calibre wireless connection plugin still cannot connect after the wifi is connected.

**Comment by Frenzie** [comment]
Slightly breaking the wifi dialog was the only change that's been made there: https://github.com/koreader/koreader/commits/master/plugins/calibrecompanion.koplugin/main.lua

I don't really see anything else that could affect it… https://github.com/koreader/koreader/compare/v2018.01.10-nightly...v2018.02.12-nightly

Except for https://github.com/koreader/koreader-base/pull/593

Apparently with `udp:setoption("broadcast", true)` we get this error:

```
nil	setsockopt failed
```

Presumably that leads to `permission denied`.

We're using socket in many more places though.

@poire-z Do you have any clue?

**Comment by poire-z** [comment]
Not really (I don't use calibre, never looked at its code, and I have the wifi code quite patched on my side).
May be other calibre users could report if they notice any such problem, just to be sure it's not something local to the OP.

**Comment by max-cw** [comment]
Hi again. Just a quick comment: I have two H2Ov1, and the other one with a different setup have the same issue, so I don't think any particular setting. I could be wrong of course.

**Comment by poire-z** [comment]
And if you reinstall a koreader version from 201801, they both work (or it's just that they worked at the time you had 201801?)

**Comment by max-cw** [comment]
That is correct. 201801 works for both.

**Comment by Frenzie** [comment]
@poire-z I don't really know how calibre works either. It's luasocket giving these `getsockopt failed` and `permission denied` failures before it even does anything. I guess I'll look over https://github.com/diegonehab/luasocket/compare/321c0c9b1f7b6b83cd83b58e7e259f53eca69373...652959890943c34d7180cae372339b91e62f0d7b later to see if anything changed. (Annoyingly, I thought updating it was just a simple bugfix… argh, side effects. :-P)

**Comment by Frenzie** [comment]
Oh, got it. A few commits after our original one they added udp4() and udp6() options.

https://github.com/diegonehab/luasocket/commit/96965b179c7311f850f72a8629b9ba6d3a31d117

Changing it to udp4() works.

**Comment by poire-z** [comment]
@max-cw : you could try taking the `common` directory from a 201801 release, and drop it over the one from a 201803, just to confirm it's really related to luasocket.

**Comment by max-cw** [comment]
Confirm working after changing to udp4(). Cheers!
