### ISSUE TITLE
FR : add an SSH server

### ISSUE THREAD

**Issue by onde2rock** [koreader/koreader#3810]
A ssh server would be a very good addition to koreader : 

- Being able to easily conect to ssh, for debugging
- For scp or SFTP to easily transfer file

I was thinking of [dropbear](https://github.com/mkj/dropbear). It advertise : 
>Dropbear can compile to a 110kB statically linked binary

Maybe we can do something like [tar](https://github.com/koreader/koreader-base/tree/3e9b63f5cafc12335e18ea8ed313aa01c004b745/thirdparty/tar), and just put it in the main directory. The fronted work sould be relatively easy, maybe just a button or something.

**Comment by NiLuJe** [comment]
Yeah, USBNet and stuff ;). FWIW, I ported all of that crap in a single package for Kobo here, for people, like me, who don't use KSM: https://www.mobileread.com/forums/showthread.php?t=254214

**Comment by onde2rock** [comment]
Yes me too, I'm already using dropbear, I just made a script that launch it at startup. But I just thought that a menu item would have been neat. And since Koreader is already cross-compiling lots of stuff, would have been simple to add it.

But if no one is interested, I can live without :-)

**Comment by poire-z** [comment]
For what it's worth, I add this to my `frontend/ui/network/manager.lua`  for a quick shell (unencrypted) without the need for ssh:
```lua
-- listen and start a shell (with better tty control)
--    https://www.preining.info/blog/2013/07/ssh-or-telnet-on-the-kobo-glo/
--    https://stackoverflow.com/questions/29317933/vi-over-netcat-session
--    http://www.real-world-systems.com/docs/stty.1.html
function NetworkMgr:getStartAShellMenuTable()
    return {
        text = _("Listen on 7777 and start a shell"),
        callback = function(menu)
            local info = InfoMessage:new{
                text = "Waiting for 20 seconds on port 7777, launching a shell",
                timeout = 20,
                }
            UIManager:show(info)
            -- Better than 'nc -e /bin/sh' (with which we have no echo on stdin nor stderr) :
            -- os.execute("rm -f /tmp/mykoshell ; mkfifo /tmp/mykoshell ; cat /tmp/mykoshell | /bin/sh -i 2>&1 | nc -w 20 -l -p 7777 >/tmp/mykoshell &")
            -- Even better than previous one, with support for Ctrl-C, Ctrl-D... and ESC with vi
            os.execute("mkdir -p /dev/pts; mount -t devpts devpts /dev/pts 2>/dev/null; rm -f /tmp/mykobettershell ; mkfifo /tmp/mykobettershell ; script -q /dev/null < /tmp/mykobettershell | nc -w 20 -l -p 7777 > /tmp/mykobettershell &")
            -- Connect to it from linux or cygwin with:
            -- alias kobo7777='stty -icanon -isig -echo ; nc KOBO_IP 7777 ; stty sane'
        end
    }
end
```
