### ISSUE TITLE
FR: Keep one line when paging

### ISSUE THREAD

**Issue by zelmon64** [koreader/koreader#3813]
Moon+ Reader has the option "Keep one line when paging" (stored in it's miscellaneous section). This feature repeats the last line of the previous page at the top of the next page. This is similar to "Page overlap" but for content that doesn't have predefined pages such as EPUBs.

This is useful for a couple of reasons. The first is that it gives an easy way to verify that the new page is in fact the page following the last one and not some other subsequent page (which could happen accidentally by a double-tap of a "next page" button). The second reason is that it helps the flow of text because the page can be turned while reading the bottom line instead of at the end of the bottom line. It especially helps the flow if the bottom line ends with a hyphenated word.

EDIT: I first asked on the [MobileRead KOReader Forum](https://www.mobileread.com/forums/showthread.php?p=3676352#post3676352) whether this was already possible and was directed to raise it as a feature request.

**Comment by poire-z** [comment]
`Page overlap` works (not wonderfully thus) with EPUBs. But only in `Scroll` mode.
If you switch to Scroll mode, the menu is no more grayed out, and you can enable it and select how you want it.
It uses a hardcoded overlap value of pixels here:
https://github.com/koreader/koreader/blob/38a0519062cdbd40527cb2c2d12e1c79c4b1c749/frontend/apps/reader/modules/readerrolling.lua#L44
that you may try increasing (20 didn't show much of previous page - 50 shows 4 lines).
May be it should use the same value readerpaging uses:
https://github.com/koreader/koreader/blob/38a0519062cdbd40527cb2c2d12e1c79c4b1c749/frontend/apps/reader/modules/readerpaging.lua#L34

I don't use or like that feature, so I don't know what good values are and if a good one would work in all cases, different font size, layouts...

(There is no support for that in crengine page splitter, that splits the whole rendered height into pages).

**Comment by zelmon64** [comment]
@poire-z thanks for the help but it hasn't worked for me. 

I switched to `Scroll` mode (with `DCREREADER_VIEW_MODE = "scroll"`) but `Page overlap` is still greyed out. I saved it in `defaults.persistent.lua` to make certain the setting stuck. I also tried with `DSCROLL_MODE = 1` and `DSHOWOVERLAP = true`.

 I'm using v2018.03.14-beta on an InkBook Obsidian running Android 4.2.2.

**Comment by poire-z** [comment]
Oh, you didn't need to touch all these :)
You can switch to scroll mode from the bottom menu:
<kbd>![image](https://user-images.githubusercontent.com/24273478/38524608-81a7e936-3c4f-11e8-82b1-9c0e627aa05b.png)</kbd>
(and remove what you added, dunno what precedences these can have over that one).

**Comment by zelmon64** [comment]
@poire-z thanks, that's enabled `Page overlap` for me. I've tried editing `readerrolling.lua` but when I run KOReader my changes are overwritten. The file I've been trying to edit is at `/data/data/org.koreader.launcher/files/frontend/apps/reader/modules/`, is that the correct directory?

**Comment by Frenzie** [comment]
> I've tried editing readerrolling.lua but when I run KOReader my changes are overwritten.

OTA updates overwrite your changes. Just running KOReader should not. Unfortunately last month's release has a bug on Android where it always extracts the resource package. Updating will fix that problem so you can experiment.

**Comment by zelmon64** [comment]
@Frenzie thanks, my changes are no longer overwritten after the update. KOReader also seems to be starting quicker now.

Do you know how to make Scroll mode end the page at the last whole line and how to make it respect the top and bottom margins? At the moment the overlap uses the bottom visible line even if it is only a thin sliver which is also obscured by the Status bar.

**Comment by Frenzie** [comment]
I'm not sure if that's possible, sorry. :-)

**Comment by poire-z** [comment]
Looks like we can make scroll mode a little better just in readerrolling.lua, with more accurate calculation of delta y, taking footer height into account, and current font height for the dim area, without touching crengine. I'll have a try at it.
About aligning on the whole line, that's a bit harder (only crengine could do it), but may be with a more correct dim area, that won't be really needed if you can read the truncated bottom line (even if grayed out a bit) fully at top of next page.
