### ISSUE TITLE
[UX] Access context menu in non-touch menu

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3818]
* KOReader version: f893b01 

#### Issue
@onde2rock 
It looks like only the file browser supports long press yet (by right arrow). If that behavior makes sense it should also be replicated in the touchmenu, although I was thinking the menu button would make the most sense there. Unfortunately that could be regarded as some slight inconsistency and it couldn't work in the file browser, but given that one is a file browser and the other a menu it just might make sense.

Also, the bottom menu does too much stuff with left and right in the first place, so an alternative long press action (like menu button) would be necessary. 

For my own reference, it looks like the Kindle 4NT has a button layout like this ([via](https://rowi.standardleitweg.de/archives/2100-elektrische-Buecher-Tipps-fuer-den-Kindle4.html)):

1. Back button
2. Pop up keyboard (?)
3. Arrow navigation with press/enter in the middle
4. Menu button
5. Home (exit?) button

**Comment by onde2rock** [comment]
> Back button
> Pop up keyboard, not used, no idea what to do with it.
> Arrow navigation with press/enter in the middle
> Menu button
> Home button

**Comment by onde2rock** [comment]
That's very nice ! 

But I don't think pressing `menu` while in a menu to set default is intuitive. In fact, I'm more expecting `menu` to close the menu.
The first thing I tried to do is implement the hold behavior with hold the `press` key. This would be the best solution, but the hardest to do.

**Comment by onde2rock** [comment]
> This is slightly confounded by the fact that by necessity "menu" and "context menu/action" are conflated into one button.

Actually, there is no `context menu` button in Koreader, I quickly hack `Right` to access the context menu  but that's because I'm starting to run out of key on Kindle4NT

**Comment by Frenzie** [comment]
Conflate = merge, as in there's no distinction between the two. I never said there was a context menu action, quite the opposite. ;-)

Conceptually I don't see that as a big issue. The menu is in effect the context menu of the document. The difference is just that on a desktop app you have the app menu and the context menu as separate entities under different buttons, so you have the context menu/action of the menu rather than the context menu/action of the context menu.

(And in any case, it's surely no weirder than "press/enter" for bottom menu. :-P)

**Comment by onde2rock** [comment]
Yes, I agree, there seem to be definitly the need for a dedicated `context menu` key in koreader.

> (And in any case, it's surely no weirder than "press/enter" for bottom menu. :-P)

I'm really starting to run out of keys on my device, but Koreader can keep evolving, I don't expect a lot on my old device.

**Comment by poire-z** [comment]
Probably solved by #8859 or followups PRs.

**Comment by Commodore64user** [comment]
> Probably solved by #8859 or followups PRs.

Not the case, at all.

**Comment by Frenzie** [comment]
Not at all doesn't sound accurate. ;-) Scroll down to "Key Binding." I think it'd be better to open a new issue with specific challenges because it does implement something that addresses this issue.
