### ISSUE TITLE
crash when touching touching left-bottom area

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3832]
* KOReader version: 1607
* Device: KA1

#### Issue
Got this crash when touching around the left-bottom corner (I was trying to pick up a speck of dust). The frontlight gesture controller was enabled:

4/01/18-17:19:48 INFO  opening file /mnt/onboard/.hidden/library/1. BESTOF/Nabokov, Vladimir - Ada ou l'ardeur.epub
04/01/18-17:19:48 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/01/18-17:19:48 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/01/18-17:19:48 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/01/18-17:19:48 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
04/01/18-17:19:48 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
04/01/18-17:19:48 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/01/18-17:20:09 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/01/18-17:20:09 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/01/18-17:20:09 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/01/18-17:20:09 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
04/01/18-17:20:09 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
04/01/18-17:20:09 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
./luajit: frontend/ui/widget/menu.lua:676: attempt to call method 'onReturn' (a nil value)
stack traceback:
	frontend/ui/widget/menu.lua:676: in function 'callback'
	frontend/ui/widget/button.lua:201: in function 'action'
	frontend/ui/uimanager.lua:532: in function '_checkTasks'
	frontend/ui/uimanager.lua:719: in function 'handleInput'
	frontend/ui/uimanager.lua:805: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x00013fc5

**Comment by Frenzie** [comment]
Not sure how to trigger that. Could you try if you can reproduce it and also if updating fixes it? @onde2rock made a few changes to the menu last week.

**Comment by onde2rock** [comment]
Maybe related to this code ?
No idea how you triggered the button without the menu open. See if you can reproduce.

https://github.com/koreader/koreader/blob/38a0519062cdbd40527cb2c2d12e1c79c4b1c749/frontend/ui/widget/menu.lua#L661-L666

**Comment by cramoisi** [comment]
I'm trying to reproduce (same book, etc) but with no success...

**Comment by Frenzie** [comment]
@cramoisi Or a paged tab of the top reader menu.

**Comment by cramoisi** [comment]
My KA1 shines like aladin's lamp and still no genius. I really can't reproduce...
What about managing the nil value in the case above-mentionned in the log ?

**Comment by Frenzie** [comment]
Well yes, something like this. :-P

https://github.com/koreader/koreader/blob/f893b01f04055112908074532fb22d9056423492/frontend/ui/widget/menu.lua#L885

**Comment by cramoisi** [comment]
at least it would do no harm

**Comment by poire-z** [comment]
(re-open when/if you can still reproduce it :)
