### ISSUE TITLE
Cache of PDF/DJVU tiles: some observations

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3846]
This is called whenever we leave _any_ document and go to file manager:

https://github.com/koreader/koreader/blob/d7a7a78731a13debaa47b63de81f47a904f1c709/frontend/cache.lua#L152-L181

It saves the most recently made cache item (blitbuffer of last displayed page, for PDF/DJVU...) into koreader/cache/ 
```
04/08/18-08:59:47 DEBUG self.cache_order {
    [1] = "renderpg|test/626372.pdf|1493017580|27|0.90184049079755|0|1|0|color",
    [2] = "pgdim|test/626372.pdf|27",
    [3] = "renderpg|test/626372.pdf|1493017580|26|0.90184049079755|0|1|0|color",
    [4] = "renderpg|test/626372.pdf|1493017580|25|0.90184049079755|0|1|0|color",
    [5] = "pgdim|test/626372.pdf|26",
    [6] = "renderpg|test/626372.pdf|1493017580|24|0.90184049079755|0|1|0|color",
    [7] = "pgdim|test/626372.pdf|25",
    [8] = "pgdim|test/626372.pdf|24",
    [9] = "renderpg|test/626372.pdf|1493017580|23|0.90184049079755|0|1|0|color",
    [10] = "pgdim|test/626372.pdf|23",
    [11] = "renderpg|test/626372.pdf|1493017580|22|0.90184049079755|0|1|0|color",
    [12] = "pgdim|test/626372.pdf|22",
    [13] = "pgdim|test/626372.pdf|1"
}
04/08/18-08:59:47 DEBUG dump cache item renderpg|test/626372.pdf|1493017580|27|0.90184049079755|0|1|0|color
04/08/18-08:59:47 DEBUG dumping tile cache to ./cache/7dc14b39df5e361b616091473a22e9f1 {
    ["y"] = 0,
    ["x"] = 0,
    ["h"] = 588,
    ["w"] = 397
}
```
and we end up (after several leaving of document/exiting koreader) with:
```
-rw-r--r-- 1 933789 Apr  8 00:01 b5dc399f1c71a8e9e677deac1b1c54a3
-rw-r--r-- 1 933789 Apr  8 00:01 8493f7c6b868236c771cd288acf9f673
-rw-r--r-- 1 933789 Apr  8 00:01 0c51459072db2987cbb44731fd210965
-rw-r--r-- 1 933789 Apr  8 00:01 c534b0da88c2b3b7bcb475b7cdb834f4
-rw-r--r-- 1 933789 Apr  8 00:01 623b8fab3e3b6737ff97961b960fed74
-rw-r--r-- 1 933789 Apr  8 08:15 8e7179ddb2a2df8d077b3bb650df8a19
-rw-r--r-- 1 933789 Apr  8 08:17 17a823b0521e7d1e37d2df70bf692d36
-rw-r--r-- 1 933789 Apr  8 08:19 3143b9ff041bcaae578ab45872c8232c
-rw-r--r-- 1 933789 Apr  8 08:21 fdd25703d26dd9241db0d7795926141f
-rw-r--r-- 1 933789 Apr  8 08:59 7dc14b39df5e361b616091473a22e9f1
```
So, on disk, we have many _most recently used cache items at the time we leave the document_ , which have no real use now that we are many pages away - and have less value that the _last to most recently used cache item_ of the current session (so, the previous page) that is not saved to disk, as we just save one tile.
I guess we can't do much about that, these md5 names can't help us guess it's an old tile from the same book.

But there's another thing:
If you open once a PDF, and so have some tiles in cache, and then go read many EPUB: each time you close an EPUB, this old cached tile from the PDF will be rewritten to the same `koreader/cache/7dc14b39df5e361b616091473a22e9f1` because it's still the most recently used cache item in the global `Cache` single instance (EPUBs/crengine does not use this glocal Cache object).

I wonder if we should just call this at the end of `Cache:serialize()`:
https://github.com/koreader/koreader/blob/d7a7a78731a13debaa47b63de81f47a904f1c709/frontend/cache.lua#L183-L191
so it's cleared when we leave a document - so nothing will have to be re-written to disk - with the overhead that if you go to that doc again, you lose all the other memory cached tiles, and can just load the most recently used from disk.
(Marking each CacheItem with a `already_saved=true` seems not an option, as you would just zap it and go to write the next one to disk).

Or just not call `Cache:serialize()` if document was a credocument?

**Comment by Frenzie** [comment]
Btw, DjVu also [this](https://gitlab.com/koreader/djvulibre/blob/55e6a76d7876e2483a2adbc36873d7f00eb806bd/libdjvu/ddjvuapi.h#L229-251) internally.

Anyway, why not simply prevent unnecessary rewrites? It'd do the trick regardless if we're reclosing a PDF or closing an EPUB.
```diff
diff --git a/frontend/cache.lua b/frontend/cache.lua
index 001df5e8..c4a870da 100644
--- a/frontend/cache.lua
+++ b/frontend/cache.lua
@@ -162,8 +162,10 @@ function Cache:serialize()
     local cache_size = 0
     for _, key in ipairs(self.cache_order) do
         local cache_item = self.cache[key]
+        local cache_file_exists = lfs.attributes(cache_path..md5.sum(key))
         -- only dump cache item that requests serialization explicitly
-        if cache_item.persistent and cache_item.dump then
+        if cache_item.persistent and cache_item.dump
+        and not cache_file_exists then
             logger.dbg("dump cache item", key)
             cache_size = cache_item:dump(cache_path..md5.sum(key)) or 0
             if cache_size > 0 then break end
```

> I wonder if we should just call this at the end of Cache:serialize():

Meh, I like my memory cache. I want more of it, not less. :-P

**Comment by poire-z** [comment]
> you're going to write each of them to disk:

or we could just get out of this loop once we found a `cache_file_exists`.
This will avoid rewritting this same cache file when you re-open a PDF/DJVU and quit it without changing page.

**Comment by Frenzie** [comment]
You mean something like this?

```diff
diff --git a/frontend/cache.lua b/frontend/cache.lua
index 001df5e8..ab8cd446 100644
--- a/frontend/cache.lua
+++ b/frontend/cache.lua
@@ -162,11 +162,18 @@ function Cache:serialize()
     local cache_size = 0
     for _, key in ipairs(self.cache_order) do
         local cache_item = self.cache[key]
+        local cache_full_path = cache_path..md5.sum(key)
+        local cache_file_exists = lfs.attributes(cache_full_path)
+
         -- only dump cache item that requests serialization explicitly
         if cache_item.persistent and cache_item.dump then
-            logger.dbg("dump cache item", key)
-            cache_size = cache_item:dump(cache_path..md5.sum(key)) or 0
-            if cache_size > 0 then break end
+            if cache_file_exists then
+                break
+            else
+                logger.dbg("dump cache item", key)
+                local cache_size = cache_item:dump(cache_full_path) or 0
+                if cache_size > 0 then break end
+            end
         end
     end
     -- set disk cache the same limit as memory cache
```

(or `if not break else blabla`)

**Comment by poire-z** [comment]
Yes, exactly.
(I first thought the `if cache_file_exists then break end` should be inside the `if cache_item.persistent and cache_item.dump then` - but why bother: if we found it, it's because it was persistent and dumped. - unless the md5 and lfs.attribute are costly and there are other non persistent stuff in cache - although it seems there's none on quick tests)

**Comment by Frenzie** [comment]
Neither is costly. We do an md5sum of this little identifying string after all, not the full cache item. It's not an integrity check. But you're right that it'd be better inside the if.

> 04/08/18-13:00:32 DEBUG dump cache item renderpg|/home/frans/Desktop/books/sedandawk.pdf|1480518409|42|1.4596099752372|0|1|0|color

Given what you mentioned about clarity, should we call it something like `sedandawk.pdf-p42-94b415bfbff7444a82c59a471ddbab8b`?

**Comment by poire-z** [comment]
I think we can't do that (without complicating CacheItem and subclasses): at this point, in Cache, we don't know how `key` is made (it could be anything) and which part is the original filename that we could put in the cache filename.

**Comment by Frenzie** [comment]
True, the beauty of the (md5) hash system is that you can pretty much toss whatever you want at it.

But I don't think it'd complicate much, at least not in this slightly more realistic form:

```lua
 local cache_full_path = cache_path..util.replaceInvalidChars(key)
```

Of course it'd have to look more like:

```lua
local function legibleHash(key)
  local hash = util.replaceAllTheEvil(key)
  if hash and hash.len > 255 then
    -- trim to fit on FAT32
  end
  return hash
end
```

Resulting cache filename:

> renderpg__home_frans_Desktop_books_prohtml5games.pdf_1520867153_3_0.99630996309963_0_1_0_color

Anyway, I'll go ahead and submit a PR for the actual problem.

**Comment by hius07** [comment]
> So, on disk, we have many _most recently used cache items at the time we leave the document_ , which have no real use now that we are many pages away - and have less value that the _last to most recently used cache item_ of the current session (so, the previous page) that is not saved to disk, as we just save one tile.
> I guess we can't do much about that, these md5 names can't help us guess it's an old tile from the same book.

A user who reads mostly pdfs has **a lot** of useless cache items.
Menu item "Clear caches" is not widely advertised and known, at least it is not mentioned in the User Guide (@offset-torque).
The average size of a pdf cache item is about 200 KB, so the koreader/cache folder can take much space.

**Comment by Frenzie** [comment]
Being able to quickly switch back and forth between documents is a feature ftr.

**Comment by hius07** [comment]
Maybe delete a cache item after the pdf document has been opened and the item has been used?

**Comment by offset-torque** [comment]
I didn't even know we have a tile cache and I had to use **Menu Search** to find where it is. So yes it is well-hidden.

If this cache can grow big enough to cause problems, I think solution should be automatic pruning/limiting.
Sending users to **File explorer>Tools>More Tools>Developer options>Clear caches** is not very user friendly.
Especially when there is no indicator that their cache has grown big.

You are the programmers of course but:
- Cache can have a hard limit (%5 of partition)
- Dynamic limit (%5 of partition free space)
- Age limit (files older than 1 week get pruned at startup)

etc.

So a user never needs to deal with this manually (which is the optimal situation IMHO).

**Comment by Frenzie** [comment]
That simply describes the situation since time immemorial. `¯\_(ツ)_/¯`

**Comment by Frenzie** [comment]
> Maybe delete a cache item after the pdf document has been opened and the item has been used?

I don't know what that means but it sounds like something I profoundly disagree with. :-)

**Comment by offset-torque** [comment]
Forgot to say, yes I will add this to the guide. We have **Book Info Cache** cleanup in the guide. This will go next to that with a short explanation about the cache folder.

**QUESTION:** I checked my reader and my oldest cache file was created around the same time I installed KOReader. So it seems this cache files are not deleted automatically. Is this correct?

**Comment by NiLuJe** [comment]
I haven't checked but that doesn't ring a bell.
