### ISSUE TITLE
Wifi cannot be started on Kindle Voyage

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#3849]
* KOReader version: 1640
* Device: kindle voyage

#### Issue

After upgrading my kindle voyage to 1640, the wifi cannot be started.

Last known good version is 1597.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
dfd8744...d7a7a78

Well, the first commit on the list is pretty obviously wifi-related. :-P

https://github.com/koreader/koreader/pull/3795

Could you describe the problem (that is, the steps) in a little bit more detail?

**Comment by Hzj-jie** [comment]
Sorry for the late response. Nothing interesting indeed. After started koreader, the wifi will be shutdown automatically. Clicking the "Wi-Fi connection" menu does not have any impact.

**Comment by NiLuJe** [comment]
Can you check over SSH if

```
ping -c1 -w2 $(/sbin/route -n | awk '$4 == "UG" {print $2}')
echo $?
```

Actually works (and returns as expected)?

I can't really do that on my end (won't enable WiFi, for obvious reasons ^^) (that, and the most up to date Kindle I have is still a PW2).

**Comment by Hzj-jie** [comment]
Sorry for the late response (again). I cannot test over SSH, since the wifi will be disabled immediately after koreader started. :)

**Comment by NiLuJe** [comment]
I meant over SSH in general, not necessarily while KOReader is running ;)

**Comment by Hzj-jie** [comment]
Oh, then I believe it works fine.

**Comment by Hzj-jie** [comment]
Bravely update to 1750, this issue won't reproduce anymore. Close for now.
