### ISSUE TITLE
FR: PocketBook frontlight warmth

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#3856]
* KOReader version: 305e75c5ea13b63de55df1294ce0caeaee547f20
* Device: PocketBook, not sure which ones

#### Issue

From [the forum](https://www.mobileread.com/forums/showthread.php?p=3680824#post3680824).

The presumably simple part, add a little interface to the backend mirroring these lines:

https://github.com/koreader/koreader/blob/305e75c5ea13b63de55df1294ce0caeaee547f20/frontend/device/pocketbook/powerd.lua#L24-L35

All we should need there is inkview.GetFrontlightColor() and inkview.SetFrontlightColor(intensity) plus a little check to see if they exist at all. Could it be as simple as `hasFrontLight = (inkview.GetFrontlightColor and inkview.SetFrontlightColor) and yes or no`?

The hard(er) part, adapt the settings widget. Judging by [this commit](https://github.com/blchinezu/pocketbook-coolreader/commit/b20336437a7c17cda8627bf75800f798eda0cb83) it looks like it goes from 0 to 100 but perhaps that's just an assumption.

More info [here](https://www.mobileread.com/forums/showthread.php?p=3654153#post3654153).

Pinging @dengste regarding what issues there might be with the frontlight widget as it exists right now and @mk-f as our resident PocketBook expert.

**Comment by dengste** [comment]
Frontlightwidget should work if  powerd has 'setWarmth' and uses a warmth value in [0 100]. The 'automatic warmth' feature has a bit more things needed in 'powerd', but I think it should be possible to move most of that stuff into BasePowerD.

**Comment by dengste** [comment]
>  and uses a warmth value in [0 100]

Not quite correct: it currently needs to have the same limits as the brightness value, meaning [fl_min fl_max].

**Comment by Frenzie** [comment]
@dengste
Looking at this (remove isKobo):
https://github.com/koreader/koreader/blob/305e75c5ea13b63de55df1294ce0caeaee547f20/frontend/ui/widget/frontlightwidget.lua#L55

I'm guessing the configure_button would need to be hidden behind an isKobo()? (Also, double space there, grmbl. :-P)

https://github.com/koreader/koreader/blob/305e75c5ea13b63de55df1294ce0caeaee547f20/frontend/ui/widget/frontlightwidget.lua#L251-L266

**Comment by pazos** [comment]
Closing this one as a "duplicate" of #5116. https://github.com/koreader/koreader/issues/5116#issuecomment-511223831 contains api calls
