### ISSUE TITLE
Proposal of logo and icon for the application

### ISSUE THREAD

**Issue by richardbmx** [koreader/koreader#3858]
Hello I would like to contribute with a new icon and logo for your application I leave you the proposal if you want to use it I can send you all the files

![presentacion para github](https://user-images.githubusercontent.com/35604837/38628675-f81e7068-3d7f-11e8-873e-6389fd99cdb3.png)

**Comment by richardbmx** [comment]
he has perfect I thought that they did not have a defined logo, the proposal that they did to you is very well too, if you want to make the change I am ordering with my proposal :-)

**Comment by KenMaltby** [comment]
I like the current "Main Logo", it looks nice on MobileRead as well, but I think the proposed icon might be a good replacement for the android one.  (No offence @chrox ) The Logotype version would be best for Android, IMHO.

Luck;
Ken

**Comment by Frenzie** [comment]
@KenMaltby I think the DPI is already quite high. You just need to crop it. Something like this, but I don't know if it's quite what you're looking for.

![crop](https://user-images.githubusercontent.com/202757/38643014-20495218-3ddc-11e8-89b4-94edfb167a21.png)

There is one small problem with the icon version of this: it doesn't scale down to a tiny icon as well as the other proposal. I think for a desktop icon it'd need to be a reduced version with just the book.

![screenshot_2018-04-11_23-05-04](https://user-images.githubusercontent.com/202757/38643240-cbb3298a-3ddc-11e8-9d4c-19ccbe3f4311.png)

Btw, here's that other crop for whatever it is you want to try. ;-)

![other](https://user-images.githubusercontent.com/202757/38643269-e3d077e8-3ddc-11e8-836e-d3fdc370cec1.png)

**Comment by KenMaltby** [comment]
I'll just make it in Inkscape as an svg then scale it to the same as those in the "res" folder of the current download .apk - saving as a .png for each of the six.  Starting from an Scalable Vector Graphic should make it a little easier.

**Comment by richardbmx** [comment]
Here is a version of just the book

![logo582](https://user-images.githubusercontent.com/35604837/38648590-03c4a47e-3dc0-11e8-90bd-eb7a90549a80.png)

**Comment by KenMaltby** [comment]
![koreaderandroidicon svg](https://user-images.githubusercontent.com/14007369/38653715-989d03bc-3dfb-11e8-854d-3fb63db4db68.png)

But scaled:
![image18](https://user-images.githubusercontent.com/14007369/38653756-b92c4bc4-3dfb-11e8-86ad-f341eb028aa8.png)

**Comment by bahusoid** [comment]
I think current icons are better (both android and main icon logo looks better to me than suggested)

**Comment by Frenzie** [comment]
@bahusoid I like all of the logos, but I have some practical problems with the two older ones.

* They don't scale down very well. I'd like the logo to be as widely applicable as possible without much effort.
* The blackletter logo is oddly pixelated. As someone who mainly uses their Kobo for reading books written before 1900, which I'm hardly going to read in their entirety in the study hall of a heritage or national library, I like what blackletter says to me, but not pixelated. ;-) (Also I've never understood why some people think blackletter is hard to read, besides maybe the s/f stuff to some degree but that's also a problem in old Roman letters.)

Veering outside of the realm of practical considerations, I think this book proposal is cuter and more attractive, with more personality and individuality than the harsher, almost brutalist "Adobe Creative Suite" `KO` (see [here](https://en.wikipedia.org/wiki/File:Adobe_Photoshop_CS6_icon.svg)).

@richardbmx Are you okay with us mixing and matching? For example, combining this quickly bitmap-traced vector version of the blackletter logo with the reading guy (just a quick copy/paste hackjob to communicate the direction I'm thinking):

![bitmap](https://user-images.githubusercontent.com/202757/38771884-47e58304-402b-11e8-8533-3fa678e4c1e3.png)
![bitmap2](https://user-images.githubusercontent.com/202757/38771885-48273c18-402b-11e8-84fd-97cdd2e8e998.png)

If that's fine by you then I'd like to start by implementing the book as the new desktop icon (see https://github.com/koreader/koreader-base/pull/647) while finalizing larger versions of the logo to unify the visual language.

PS Here's the vectorized blackletter logo: [koreader-logo-blackletter-traced.svg.zip](https://github.com/koreader/koreader/files/1910932/koreader-logo-blackletter-traced.svg.zip)

**Comment by Frenzie** [comment]
I found the origin of the blackletter:

Quoting @giorgio130 in https://github.com/koreader/koreader/pull/201#issuecomment-22237816
> Yes, it's more a placeholder, it's used by the launcher on kobos!

**Comment by giorgio130** [comment]
Hi guys! I remember making that logo very quickly in inkscape. It really was just a placeholder and I was really surprised some weeks ago when I saw it was still in use!
I really like the final proposal of #2000. @richardbmx I think the book in your logo has a strange curve, almost if it's facing away from the reader or if the book is too open (angle between pages is >180°), I don't know if I was clear, and maybe it's just the way I look at it. :)

**Comment by poire-z** [comment]
I personally won't ever really see the logo, so I won't mind any choice (I'm not really fond of the current one, but I hardly ever see it).
But I find the proposal of this issue a bit too generic: it's a man, reading a purple real paper book.
It expresses not much about KOReader, except it's about reading a book.

I prefer all those from https://github.com/koreader/koreader/issues/2000#issuecomment-292975919: they look like an e-reader device, they have rounded corners and are smooth - but also like a book, with pages on the right side, and that could evoke an e-reader cover too - and we see the KO, which says it's KOReader - and the left side of the K looks like a bookmark. It expresses quite a bit much more, while still being simple and clean.

**Comment by Frenzie** [comment]
Oh yeah, I found this sitting around on my hard drive. I guess I never shared my experiments insofar as I bothered to save them.

![koreader pdf](https://user-images.githubusercontent.com/202757/38782665-5b7b7078-40f7-11e8-8eeb-d7040fb341c3.png)
