### ISSUE TITLE
AppImage crashes on second load (coverbrowser)

### ISSUE THREAD

**Issue by captn3m0** [koreader/koreader#3861]
* KOReader version: ` v2015.11-1644-ge39ed90_2018-04-09`
* Device: ArchLinux 

#### Issue

The first run of KOReader works as expected. See [first load log](https://paste.ubuntu.com/p/5VqBXK73CJ/).

However, the second load crashes somewhere in the coverbrowser plugin:

```
./luajit: frontend/util.lua:176: attempt to index local 'text' (a nil value)
stack traceback:
	frontend/util.lua:176: in function 'utf8Reverse'
	frontend/apps/filemanager/filemanager.lua:52: in function 'truncatePath'
	frontend/apps/filemanager/filemanager.lua:162: in function 'onPathChanged'
	frontend/ui/widget/filechooser.lua:288: in function 'changeToPath'
	plugins/coverbrowser.koplugin/main.lua:414: in function 'refreshFileManagerInstance'
	plugins/coverbrowser.koplugin/main.lua:504: in function 'action'
	frontend/ui/uimanager.lua:530: in function '_checkTasks'
	frontend/ui/uimanager.lua:717: in function 'handleInput'
	frontend/ui/uimanager.lua:803: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x00404fe0
```

Complete log: https://paste.ubuntu.com/p/y6dzHfnTmz/

#### Steps to reproduce

- Run koreader once
- Exit normally
- Run the AppImage file again

Aside: Thanks for making KOReader (and the regular updates). It makes the Kindle worth having (if solely because of the OPDS support). I just pushed a [AUR Package](https://aur.archlinux.org/packages/koreader-appimage/) that might be helpful for Arch Linux users.

**Comment by Frenzie** [comment]
This might be my fault. I used (or rather unthinkingly copied) `~/Documents` instead of `$XDG_DOCUMENTS_DIR` in the AppRun script when I adapted it from the Ubuntu Touch Click koreader.sh script. Does it work if you supply a folder or filename argument?

**Comment by captn3m0** [comment]
Passing another directory does work! I'll keep an empty ~/Documents directory for now as a workaround, thanks :+1:

**Comment by Frenzie** [comment]
@poire-z This is however a bug in CoverBrowser. You can easily reproduce it with something like `./reader.lua /crashfest2018`. The classic view stupidly displays the fake location you start with as if it existed (with 0 files), but CoverBrowser crashes. Perhaps `FileManager:showFiles()` would be a better place to tackle it, though it's unclear to me what the right behavior would be.

It looks like starting in classic view with a fake location always takes you "up" to the directory luajit is located in.

**Comment by gerroon** [comment]
```
 [*] Current time: 04/12/18-19:01:05
 [*] Version: v2015.11-1654-g666c9f1_2018-04-12

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
./luajit: ./ffi/SDL2_0.lua:70: Cannot initialize SDL.
stack traceback:
        [C]: in function 'error'
        ./ffi/SDL2_0.lua:70: in function 'open'
        ./ffi/framebuffer_SDL2_0.lua:13: in function 'init'
        ./ffi/framebuffer.lua:63: in function 'new'
        frontend/device/sdl/device.lua:39: in function 'init'
        frontend/device.lua:39: in main chunk
        [C]: in function 'require'
        frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
        [C]: in function 'require'
        frontend/ui/widget/container/centercontainer.lua:5: in main chunk
        [C]: in function 'require'
        frontend/ui/widget/button.lua:19: in main chunk
        [C]: in function 'require'
        frontend/ui/widget/buttontable.lua:2: in main chunk
        [C]: in function 'require'
        frontend/ui/widget/confirmbox.lua:21: in main chunk
        [C]: in function 'require'
        ./reader.lua:96: in main chunk
        [C]: at 0x00404fe0

```

**Comment by gerroon** [comment]
Never mind, I was starting it in a Nomachine session, I think it must be an X issue
