### ISSUE TITLE
Do KOReader still support Kindle 1,2,3,DXG ?

### ISSUE THREAD

**Issue by onde2rock** [koreader/koreader#3878]
It's already kinda slow on my kindle 5, so I can't imagine on these older device.

Pro : 

-  We can remove the kindle-legacy target
- They are the last real<sup>1</sup> devices that use `hasKeyboard`, so code cleanup possible.

Cons : 

-  ?
<br><br>

<sup>1</sup>except maybe android ? https://github.com/koreader/koreader/blob/aadb81eb4831c968daf14e1c20845c9810bb5f6e/frontend/device/android/device.lua#L48-L53

**Comment by NiLuJe** [comment]
It technically does, I guess, so it's a question of whether it actually still has users on these devices, and whether we want to carry that legacy baggage or not.

OTOH, I'm not terribly convinced we'd lose much code by dropping it, and I'm somewhat against it until we somehow roll a stable release which does support it ;).

**Comment by Frenzie** [comment]
All the less limited devices at the very least have bluetooth keyboards. It's a great feature on desktop too.

https://en.m.wikipedia.org/wiki/Vimperator
https://github.com/Frenzie/nimbler

So I don't know about old Kindle, but I wouldn't want to throw it away just for the sake of cleaning up a tiny bit.

**Comment by onde2rock** [comment]
> until we somehow roll a stable release which does support it ;).

Fair enough

>  but I wouldn't want to throw it away just for the sake of cleaning up a tiny bit.

Yes, of course, maybe I will try to fix it then, because I think it's broken for now.

@NiLuJe While you here, do you happen to know the difference between the currently used TC for kindle` arm-linux-gnueabi` which [seem](https://github.com/koreader/virdevenv/blob/c3481c22f56d7b66151d5120b3755f261a2c5a3f/docker/ubuntu/baseimage/bootstrap.sh#L8) to be coming from [ubuntu](https://packages.ubuntu.com/fr/xenial/gcc-arm-linux-gnueabi), and for example, the TC `arm-kindle5-linux-gnueabi ` build using the neat crosstool fork ?

It work all the same but they are differences, does it matter ?
```
#objdump -s --section .comment base/thirdparty/zsync/build/arm-kindle5-linux-gnueabi/zsync-prefix/src/zsync-build/zsync 

Contenu de la section .comment :
 0000 4743433a 20286372 6f737374 6f6f6c2d  GCC: (crosstool-
 0010 4e472063 726f7373 746f6f6c 2d6e672d  NG crosstool-ng-
 0020 312e3232 2e302d31 39352d67 31373635  1.22.0-195-g1765
 0030 38663429 20342e38 2e3500             8f4) 4.8.5.     
```
#objdump -s --section .comment base/thirdparty/zsync/build/arm-linux-gnueabi/zsync-prefix/src/zsync-build/zsync

Contenu de la section .comment :
 0000 4743433a 20285562 756e7475 2f4c696e  GCC: (Ubuntu/Lin
 0010 61726f20 342e372e 332d3132 7562756e  aro 4.7.3-12ubun
 0020 74753129 20342e37 2e330047 43433a20  tu1) 4.7.3.GCC: 
 0030 28556275 6e74752f 4c696e61 726f2034  (Ubuntu/Linaro 4
 0040 2e382e32 2d313675 62756e74 75332920  .8.2-16ubuntu3) 
 0050 342e382e 3200                        4.8.2.         
```

**Comment by Frenzie** [comment]
> Yes, of course, maybe I will try to fix it then, because I think it's broken for now.

What is? The quick access keys to open a file (in filechooser and history, for example) are working fine.

**Comment by onde2rock** [comment]
> What is? The quick access keys to open a file (in filechooser and history, for example) are working fine.
Oh I didn't even think about that, I was talking about typing in inputdialog.

**Comment by Frenzie** [comment]
There's support for that? But yes, I'd say we definitely want that. Besides physical keyboards, Android/Ubuntu Touch/Sailfish/iOS/desktop also have a variety of onscreen keyboards and input methods that ideally we'd be able to harness. But anyway, that's far beyond the scope of "please don't strip it out if it's there". :-P

**Comment by NiLuJe** [comment]
@onde2rock: The only weird thing I see here is why are we not also using the kindle TC built w/ koxtoolchain, since we do build it? :D

But to answer your question, it currently works because it's historically what the old nightly build system used, and at one point I had to install the same Ubuntu version in a VM to implement a bunch of workarounds to make sure nothing untoward was happening because of the fact that it wasn't really targeting the Kindle ;).

**Comment by NiLuJe** [comment]
Okay, looking at the current Makefile.defs, a couple of comments:

'kindle' should really be using the kindle5 TC (c.f., the other discussion on whether we should actually rename it to kindle4).
'kindle-legacy' should be using the kindle TC (the one built w/ koxtoolchain).

Meaning we should really always use custom TCs, never the Ubuntu one.

And if we want to go the extra-mile, ship a kindlepw2 build, but that's icing on the cake, and the performance gains may not be that significant.

**Comment by Frenzie** [comment]
@NiLuJe We never use the Ubuntu/system TC (well, except for the AppImage and Ubuntu Touch build, but I mean for Kindle):

https://gitlab.com/koreader/nightly-builds/blob/bda312e7a5cfe233c82c845446c45de7b681087a/.gitlab-ci.yml#L28

https://github.com/koreader/virdevenv/blob/c3481c22f56d7b66151d5120b3755f261a2c5a3f/docker/ubuntu/kokindle/build_kindle_tc.sh

Adding a kindlepw2 build would be child's play. (Select the kindle lines in .gitlab-ci.yml, press Ctrl+D, change kindle to kindlepw2)

**Comment by onde2rock** [comment]
> 'kindle-legacy' should be using the kindle TC (the one built w/ koxtoolchain).

Already the case :` arm-kindle-linux-gnueabi ` is coming from [here](https://github.com/koreader/virdevenv/blob/c3481c22f56d7b66151d5120b3755f261a2c5a3f/docker/ubuntu/kokindle/build_kindle_tc.sh#L8), which is the legacy TC, maybe a name change is needed.

> 'kindle' should really be using the kindle5 TC (c.f., the other discussion on whether we should actually rename it to kindle4).

Yes, that what seemed weird to me and lead to all this.

>Meaning we should really always use custom TCs, never the Ubuntu one.

That's funny because that's exactly the opposite of the current setup :-)

**Comment by Frenzie** [comment]
The Docker image for the nightly builds has everything available. Whatever else happens is up to base. :-(

So please fix it. ;-)

**Comment by Frenzie** [comment]
@NiLuJe Btw let me know if you have a GitLab account so I can add you.

**Comment by NiLuJe** [comment]
Hmm, Atlassian, yeah, GitLab, I don't think so. That can be arranged ;).

**Comment by NiLuJe** [comment]
Yup:

```
readelf -p .comment kindle/koreader/luajit                                                                                                                                                                                           
String dump of section '.comment':
  [     0]  GCC: (Ubuntu/Linaro 4.7.3-12ubuntu1) 4.7.3
  [    2b]  DynASM 1.4.0
  [    38]  GCC: (Ubuntu/Linaro 4.8.2-16ubuntu3) 4.8.2
```

With the added bonus that it appears to bundle some static parts compiled with another version of the TC ^^.

At least with our CFLAGS it appears to more or less be targeting the right CPU:

```
readelf -A kindle/koreader/luajit
                                                                                                                                                                         
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_CPU_unaligned_access: v6
```

**Comment by NiLuJe** [comment]
kindle-legacy is okay:
```
String dump of section '.comment':
  [     0]  GCC: (crosstool-NG crosstool-ng-1.22.0-195-g17658f4) 4.8.5
  [    3b]  DynASM 1.4.0
```

```
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "ARM1136JF-S"
  Tag_CPU_arch: v6
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-1
  Tag_FP_arch: VFPv2
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_CPU_unaligned_access: v6
```

**Comment by NiLuJe** [comment]
As is kobo:

```
String dump of section '.comment':
  [     0]  GCC: (crosstool-NG crosstool-ng-1.22.0-195-g17658f4) 4.8.5
  [    3b]  DynASM 1.4.0
```

```
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "Cortex-A8"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_HardFP_use: Deprecated
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_Virtualization_use: TrustZone
```

**Comment by Frenzie** [comment]
@NiLuJe Might as well check the brand new pw2 build while you're at it. (Should be good.)

**Comment by NiLuJe** [comment]
@Frenzie : Where does the binary end up? I'm not seeing it on http://ota.koreader.rocks/ (which is what I assumed to be the master OTA server? Did I get that wrong?).

OT: Registered on GitLab, same username ;).

**Comment by Frenzie** [comment]
In the link I gave (with the build log), on the right there's a "get artifacts."

There are more builds executed every night/early morning than are automatically pushed to the koreader.rocks server. Part caution (at least the first few weeks after adding something new), part lack of time, part laziness.

The artifacts are downloaded from GitLab by https://github.com/koreader/koreader-misc/tree/cb50c7e6607c7b8d35d07d2785514734a68b696f/nightswatcher (which does a few more things besides that, such as signing the Android builds)

I'll also have to look into doing signed AppImages, for example. And AppImages also have a zsync OTA update system but since it can't tap into our existing infrastructure I'd have to write that from scratch. Plenty of stuff to do everywhere. ;-)

**Comment by NiLuJe** [comment]
@onde2rock: Hit the nail on the head! The [update](https://github.com/koreader/koreader/blob/master/Makefile#L362) make target doesn't handle the pw2 TARGET.

**Comment by Frenzie** [comment]
Expanding on what I wrote above. It was five months ago that I added Android x86 to GitLab (around [here](https://gitlab.com/koreader/nightly-builds/commit/dbc5ddc383879944b517ffc3bb5de4e07210895d)) and only last month that I added it to koreader.rocks, properly signed and all (around [here](https://github.com/koreader/koreader-misc/commit/0d6b09e1f78e2aeb32aaccecbbac1d77bb928db4#diff-e1876ee6d08465af3547d2bc258f6c79)).

And yeah, missing target in front. Makes sense since we don't really use it, I suppose. :-P

**Comment by Frenzie** [comment]
@NiLuJe With the fix in https://gitlab.com/koreader/nightly-builds/-/jobs/63073025 should generate a proper build

**Comment by NiLuJe** [comment]
@Frenzie :+1: 

```
String dump of section '.comment':
  [     0]  GCC: (crosstool-NG crosstool-ng-1.22.0-195-g17658f4) 4.8.5
  [    3b]  DynASM 1.4.0
```

```
File Attributes
  Tag_CPU_name: "Cortex-A9"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_CPU_unaligned_access: v6
  Tag_MPextension_use: Allowed
  Tag_Virtualization_use: TrustZone
```

A9 ;).

**Comment by NiLuJe** [comment]
We should have clarified the situation enough by now ;).
