### ISSUE TITLE
crash with zsynch

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3880]
* KOReader version: 1658
* Device: KA1 & kobo aura (first edition)

#### Issue

I was testing zsynch between my KA1 and my wife's aura yesterday. Sent one book form Aura to KA1 with no problem, then when selected one book from KA1 to send to the aura, koreader crashed on the two kobos at the same time (Yup, I noticed the time on the device is not synched)

crash.log on KA1 : 
-------------------
udhcpc (v1.22.0.kobo) started
Sending discover...
Sending select for 192.168.0.11...
Lease of 192.168.0.11 obtained, lease time 3600
adding dns 62.197.111.140
adding dns 109.88.203.3
ffi.load: libs/libczmq.so.1
ffi.load: libs/libczmq.so.1
ffi.load: libs/libzyre.so.1
D: 18-04-14 18:57:05 (zsys): zsys_set_interface (wlan0)
ffi.load: libs/libczmq.so.1
ffi.load: libs/libfmq.so.1
ffi.load: libs/libfmq.so.1
ffi.load: libs/libfmq.so.1
04/14/18-18:57:37 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
04/14/18-18:57:37 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/14/18-18:57:37 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/14/18-18:57:37 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
04/14/18-18:57:37 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
E: 18-04-14 18:57:43 dangling socket created at /builds/koreader/nightly-builds/koreader/base/thirdparty/zyre/build/arm-kobo-linux-gnueabihf/zyre-prefix/src/zyre/src/zyre.c:87
E: 18-04-14 18:57:43 dangling socket created at /builds/koreader/nightly-builds/koreader/base/thirdparty/zyre/build/arm-kobo-linux-gnueabihf/zyre-prefix/src/zyre/src/zyre.c:97
E: 18-04-14 18:57:43 dangling socket created at /builds/koreader/nightly-builds/koreader/base/thirdparty/czmq/build/arm-kobo-linux-gnueabihf/czmq-prefix/src/czmq/src/zactor.c:109
E: 18-04-14 18:57:43 dangling socket created at /builds/koreader/nightly-builds/koreader/base/thirdparty/czmq/build/arm-kobo-linux-gnueabihf/czmq-prefix/src/czmq/src/zactor.c:118
E: 18-04-14 18:57:43 dangling socket created at /builds/koreader/nightly-builds/koreader/base/thirdparty/zyre/build/arm-kobo-linux-gnueabihf/zyre-prefix/src/zyre/src/zyre_node.c:80
E: 18-04-14 18:57:43 dangling socket created at /builds/koreader/nightly-builds/koreader/base/thirdparty/zyre/build/arm-kobo-linux-gnueabihf/zyre-prefix/src/zyre/src/zyre_peer.c:113
E: 18-04-14 18:57:43 dangling sockets: cannot terminate ZMQ safely
04/14/18-18:58:23 INFO  opening file /mnt/onboard/.hidden/library/Egolf, Tristan - Le seigneur des porcheries.epub
04/14/18-18:58:23 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
04/14/18-18:58:23 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/14/18-18:58:23 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/14/18-18:58:23 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
04/14/18-18:58:23 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/14/18-18:58:23 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
ffi.load: libs/libfmq.so.1
18-04-14 18:58:34 I: server accepts anonymous access
D: 18-04-14 18:58:34 (zsys): zsys_set_interface (wlan0)
ffi.load: libs/libfmq.so.1
**luajit: /builds/koreader/nightly-builds/koreader/base/thirdparty/filemq/build/arm-kobo-linux-gnueabihf/filemq-prefix/src/filemq/src/fmq_client.c:170: fmq_client_set_resync: Assertion `self' failed.**
Aborted

crash.log on Kobo Aura
---------------------------

04/14/18-18:54:54 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
04/14/18-18:54:58 WARN  menu id not found: plus_menu
04/14/18-18:55:31 INFO  opening file /mnt/onboard/.livres/Les boulevards de ceinture - Modiano, Patrick.epub
04/14/18-18:55:32 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
04/14/18-18:55:32 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/14/18-18:55:32 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/14/18-18:55:32 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
04/14/18-18:55:32 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/14/18-18:55:32 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
udhcpc (v1.22.0.kobo) started
Sending discover...
Sending select for 192.168.0.14...
Lease of 192.168.0.14 obtained, lease time 3600
adding dns 62.197.111.140
adding dns 109.88.203.3
ffi.load: libs/libczmq.so.1
ffi.load: libs/libczmq.so.1
ffi.load: libs/libfmq.so.1
ffi.load: libs/libfmq.so.1
18-04-14 18:56:43 I: server accepts anonymous access
ffi.load: libs/libczmq.so.1
ffi.load: libs/libzyre.so.1
D: 18-04-14 18:56:43 (zsys): zsys_set_interface (wlan0)
ffi.load: libs/libfmq.so.1
ffi.load: libs/libfmq.so.1
**luajit: /builds/koreader/nightly-builds/koreader/base/thirdparty/filemq/build/arm-kobo-linux-gnueabihf/filemq-prefix/src/filemq/src/fmq_client.c:170: fmq_client_set_resync: Assertion `self' failed.**
Aborted

**Comment by cramoisi** [comment]
to reproduce (somehow) - between KA1 and GloHD: 

open a book on each reader
connect each reader on LAN
on the first reader (KA1) : share the book
on the second reader (GloHD) : subscribe to share
the book is push on the second reader, KOReader crashed when the book was opened

**Comment by Frenzie** [comment]
Closing on account of https://github.com/koreader/koreader/commit/a665901c51ffb70003db0b64a54a65f038adc90a.
