### ISSUE TITLE
FR : Add SDL/linux build to nightly

### ISSUE THREAD

**Issue by onde2rock** [koreader/koreader#3886]
So people wanting to quickly mess around with the frontend don't have to build base.

**Comment by NiLuJe** [comment]
Isn't that the niche AppImage is supposed to fill ?

**Comment by Frenzie** [comment]
It does. Run it with `--appimage-extract`.

**Comment by hwhw** [comment]
FWIW: It also works fine in the Windows Subsystem for Linux :-) (You need an X-Server, of course)
