### ISSUE TITLE
crash when waking up ? 

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3899]
* KOReader version: 1674
* Device: KA1

#### Issue

Put my reader to sleep (closing the cover) for eating. Was off when came back (KSM auto-shutdowned it after the crash)

04/19/18-18:55:44 WARN  menu id not found: plus_menu
04/19/18-18:55:50 INFO  opening file /mnt/onboard/.hidden/library/Barde-Cabucon, Olivier - Commissaire aux morts etranges - 01 -Casanova et la femme sans visage.epub
04/19/18-18:55:50 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
04/19/18-18:55:50 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
CRE WARNING: cached rendering is invalid (style hash mismatch): doing full rendering
04/19/18-18:56:44 INFO  Kobo suspend: going to sleep . . .
04/19/18-18:56:44 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
04/19/18-18:56:46 INFO  Kobo suspend: waited for 2s because of reasons...
04/19/18-18:56:46 INFO  Kobo suspend: synced FS
04/19/18-18:56:46 INFO  Kobo suspend: asking for a suspend to RAM . . .
04/19/18-18:56:46 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
04/19/18-19:08:23 INFO  Kobo suspend: woke up!
04/19/18-19:08:23 INFO  Kobo resume: clean up after wakeup
04/19/18-19:08:23 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
./luajit: frontend/ui/widget/dictquicklookup.lua:555: attempt to index field 'dimen' (a nil value)
stack traceback:
	frontend/ui/widget/dictquicklookup.lua:555: in function 'refreshfunc'
	frontend/ui/uimanager.lua:655: in function '_repaint'
	frontend/ui/uimanager.lua:731: in function 'handleInput'
	frontend/ui/uimanager.lua:803: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x000139b9

**Comment by cramoisi** [comment]
And I didn't even lookup a word

**Comment by Frenzie** [comment]
I'll close this for now, but please reopen with more info (if possible) should it occur again.
