### ISSUE TITLE
[UI] Weird box in the covermenu

### ISSUE THREAD

**Issue by onde2rock** [koreader/koreader#3906]
* KOReader version: git
* Device: SDL

#### Issue
Weird box behind covermenu.

![image](https://user-images.githubusercontent.com/3342132/39089303-552ecf04-45c4-11e8-9cbc-6d280ddce511.png)

@poire-z I think you are the specialist of the coverbrowser ?

**Comment by cramoisi** [comment]
@onde2rock : you mean the little thing which pop out at the right the coverimage ? it's to signal that there is a summary available

files >Display mode >other settings > show hint for books with description / Show hint for opened books in history

**Comment by poire-z** [comment]
Right (that was supposed to look like some _insert_ in the book, or some post-it with review sometimes put on a book by bookshop employees).
It's for letting you know there was a description/subject/summary in the book metadata, that you can read directly thru the menu you get when Holding on the book.
