### ISSUE TITLE
extra space in resource files ("% 1" is shown in wiki dialogs instead of integers / file name)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#3913]
* KOReader version: v2015.11-1689-g5db7bab_2018-04-22
*Device: Kobo glo hd

#### Issue
lots of dialogues in Russian language contain "% 1" and "% 2" instead of "%1" and "%2" for wikipedia downloads

#### Steps to reproduce
1) go click and remember the sequence to download a wiki article
2) set the language to Russian
3) restart koreader to apply new language everywhere
4) go to wikipedia download ( that's why we did item#1 )
5) go through the hassle of turning on the WiFi with some empty dialogs
6) type "china"
7) download first available article found (anything) - as EPUB
8) you will see dialogs will be asking do "you want download % 1 pictures embedded into the article?" (in russian)
9) after download finished, you'll see "the article downloaded is stored as % 2, do you want to open it now?" (in russian)

so it's just an extra space that has to be removed;
it's that printf ("%1", bookname) C-like format that gets a wrong string;
I assume all the messages are stored in separate files for multitude of languages that koreader supports;
I clicked through source tree and tried to search for "% 2" to remove the space;
but I couldn't find... i10n contains something else but not the strings;
I'd assume other languages might have the same bug, not only Russian

##### `crash.log` (NOT applicable)

**Comment by Frenzie** [comment]
The translations are on Transifex. I'm not sure what the best way to mass fix this if it was mistakenly done on all strings.

https://www.transifex.com/houqp/koreader/dashboard/

**Comment by cramoisi** [comment]
Looks like we find a new translator for russian : @worldexplorer  😄

**Comment by worldexplorer** [comment]
so how this Transifex works? I registered and requested RU language for koreader;

Im just curious:
how the translation is integrated into the koreader build?
what folder the resource files are deployed into? where in the final nightly zip / tgz the translation is located?


guys I'm really ready to contribute. do any of the koreader developers need my Kobo Glo HD for testing? I got a new one, I can ship my old N437 model

**Comment by cramoisi** [comment]
@worldexplorer : all the "translatable" strings are on transiflex. On the right you got english version ; on the left, the translation you choose for your langage. Easy enough. Each string is describe with a little context (from what file, etc - that could be better, but it's good enough for the purpose i think).

<img width="714" alt="capture d ecran 2018-04-26 07 54 34" src="https://user-images.githubusercontent.com/28014131/39288137-240de25a-4927-11e8-9075-b9e583518a96.png">

After that, you can download a .po file and put it on your reader ; you can also download a .po file and use it to translate and reupload it. It's easier to tweak them from an emulator though (cause some strings will have to not be translate from word to word as they won't stick in their right place on the screen (some language need more place than other). The .po file are to be placed in /.adds/koreader/l10n/code-langage (here it's ru for you)/koreader.po.

I think they are automatically update on build (@Frenzie, correct me if it's wrong)

Go on , give a shot : https://www.transifex.com/houqp/koreader/language/ru/  ;)

**Comment by worldexplorer** [comment]
Merci Sebastien, j'ai demande la langue (RU) sur Transifex, j'attends quand on m'approve :)
Pardon my French :) without accents :))

Yes the emulator is my next step... so far it was easier to have koreader installed on an android phone and fix files on the phone, restarting the android koreader. I'm going over the steps mentioned in "Building Prerequisites" on a debian box

**Comment by worldexplorer** [comment]
yes, it's worldexplorer, authenticated via github auth

**Comment by cramoisi** [comment]
@worldexplorer : not related to this thread but as you are a russian reader ; would you mind testing a hyphenation dot pattern file to replace the old pdb actual file ?

**Comment by worldexplorer** [comment]
yes I will check the hyphenation next week (or two from now). I'll have to figure how it works and PDB has nothing to do with windows DLL debugging :)

**Comment by cramoisi** [comment]
@worldexplorer : thanks ! ping me when you'll have the time for I need to make / send you the file (you'll got a .pattern file which I want to use in place of the pdb file). There is really nothing to do but reading. If errors there are, they pop up in the eyes by themselves (but there will be none).

**Comment by Frenzie** [comment]
@worldexplorer Is there a particular reason you want to create a Russian (Russia) in addition to "generic" Russian?

**Comment by Frenzie** [comment]
I fixed up the remaining broken strings.
