### ISSUE TITLE
UI ideas (my own notes)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#3915]
I'll put these notes here somewhere (mostly for myself, may be one day... I'll figure them out)

1) file browser: path would better look (to me) aligned to the left, and each folder of breadcrumbs have a dropdown with subfolders; this way it will be easier to jump from
/Wikipedia/politics/crises/Carribean1945
to
/Wikipedia/economics/
a dropdown on politics, showing neighbours, will save me 5 clicks going back to Wikipedia and one choosing economics
I may have picked up this idea from some linux file browsers;
a widget needs to be implemented, a panel drawn as overlay on top with just lines of conttent

2) file search results: add "open folder" in addition to default action "open the EPUB found" (single click)

3) add another widget / panel so that a menu item could contain its content by expanding (instead of click - choose submenu - get a dialog window)
Time And Date
- Set Time
-- Dialog
- Set Date
-- Dialog

could have been #1
Time And Date
-- dialog immediately with both time and date

could have been #2
(with an improved widget, where all controls can be inside a panel of a vertically-extended menu item):
Time And Date
- in-place dialog just like the combined one, with no frame, not in the middle of the screen but below the parent item and idented; collapseable; not clearing the parent menu completely but keeping the way I reached this in-place dialog;

4) wifi state icon, current time, frontlight level - in top status bar (or into the bottom, but somewhere together and toggle-able for icons I want / dont want)

5) while showing submenus - show also the parent menu item (looking at ""Reverse sorting" I already forgot what root menu item led me here - sorting WHAT?...)

6) what "disable double tap" means?? if I enable - what will be affected? may be question mark aligned to the right with a popup window?...

7) third icon from left contains more plugins than anything else - may be a puzzle shape of the icon would better remind something pluggable than a allen key and a screw driver... (which to me sound more like "setup")

8) probably after a Items per page dialog with increase / decrease button closes, it may make sense to open the menu where from this dialog was invoked?... in-place dialogs (when the menu panel that invoked it stays under the dialog) might help me figure how did I reach this thing here? this builds more association and it's easier to remember where control stuff is located across the menu

9) same idea (like for files) with breadcrubms can be applied to menu items - after I dive 3 menu levels deep, the path could stay on top with each level having drop downs

10) after I saved a wiki article from file browser, I need to get out of folder and click back so that I will see the fresh epub; the page could be auto changed so that the file list is sorted and I see the page where the newcomer takes its place, and is highlighted (of course it is bold already)

11) still wiki fetch dialog should be one instead of 3 (and 4 clicks on the original link if WiFi is turned off), with multiple checkboxes / fields / settings... clicking 8-10 times for just having a hard copy of a web page by clicking a link is too much; in chrome / firefox it takes 1 click

12) history helps to find the read-and-forgotten, but I'd be happier if I could click one button "prev epub" and I will go to the prev book where I left if (like "back" button in internet browser) and "next epub" to return; probably "prev" and "next" might have an overlay (closing the rendered book and painted on top of the book content) dropdown with the previous half of the history (and same for "next" that will grow as I'm going back one book)

13) auto shut down / auto sleep - I noticed the book falls asleep in ~60 minutes if kept on... ehm I wish this was configurable

I understand that all the above requires big efforts of "invention" the widgets with their own windows-like Paint() method and events and all this ... but may be one day I will do it myself?..... those were just notes, not a task to complete.

BIG THANK YOU TO THE TEAM FOR (v1689):
1) I can cut a file, walk away, open menu (open a epub) and paste the file after
2) wiki plugin can now open a wiki article from file browser (previously it couldn't save a epub "in the same folder as an article" because "no article was currently open / displayed" 
3) file search is amazing;
4) I don't know how but the keyboard remembered the russian language I once chose - after OTA I'm back to English UI but the keyboard is bilingual without the UI being russian
5) clicking on a link of a wiki article, you now check for a local file with the expected name and no need to download again

**Comment by Frenzie** [comment]
Having the name of the menu on top like in Firefox (except in Firefox it's stupid and awful 'cause it's desktop) is something I definitely want, as are breadcrumbs. They're also on my personal "if I have too much time" (so probably never) list. :-P

> what "disable double tap" means?? if I enable - what will be affected? may be question mark aligned to the right with a popup window?...

Double tapping means taps take longer to respond. I forget what if anything responds to it. Perhaps it's a slightly vestigial option in a GUI sense.

> third icon from left contains more plugins than anything else - may be a puzzle shape of the icon would better remind something pluggable than a allen key and a screw driver... (which to me sound more like "setup")

I'd say it's "tools." The plugins part is more a technical detail.

**Comment by KenMaltby** [comment]
13.  Can be set in "settings.reader.lua"  I am using:  ["auto_suspend_timeout_seconds"] = 480, that is 480 seconds or 8 min.  You can also use 60*8 or whatever min. you want.

**Comment by ersi-dnd** [comment]
I have another suggestion to make the UI more consistent.

To me, History and File Browser always felt like the same function/view, but different "folders". I often hit the top edge of History, expecting the menus show up, but nothing happens because lo and behold it's not File Browser. Instead I have to target the upper-right corner to get out of History, something I never need to do with File Browser.

I'd very much like if History looked like File Browser and I could open the menus by tapping the top edge of History.

**Comment by ersi-dnd** [comment]
@KenMaltby 
Since to me History and File Browser feel like the same thing, I expect a tap on the upper edge to open the very same menus. Largely the same menus open up also when you are in a book.

Then there is a big fat + at the upper-right corner in File Browser that does something. I guess there could be a big fat + at the upper-right corner in History too that would bring up a few strictly history-related options. 

But I mainly care about the upper-center tap that should always bring up (largely) the same menus whether in File Browser, History, or in a book.

**Comment by KenMaltby** [comment]
Not the same to me, at all.  History is more like a "collection" of reads I want to keep handy.  Something like search results, not like the file browser.

**Comment by ersi-dnd** [comment]
But the search results come up in the File Browser, don't they? 

For me, History is just another way to sort the files. It's a list of files - just like in the file browser.

Anyway, the main point of my suggestion is to make the UI consistent. All those menus open up when you are in a book. All those menus also open up when you are in the File Browser. Why don't all those menus open up also when we are in History?

**Comment by Panoptis** [comment]
Please excuse the necropost. 
Just installed koreader on Kindle 4 and discovered this issue while searching if it's a known problem. Do not know if this warrants it's own issue so I mention it here:  
Items 3. and 8. (the dialogues with small up/down Buttons) seem not to work on non-touch devices. Would be nice if up/down HW Keys were connected.

**Comment by NiLuJe** [comment]
No active contributors are using non-touch devices, so it's probably going to be a "PRs welcome" affair ;).

**Comment by pazos** [comment]
For UI ideas and elaborated feedback the forum is a better place for a discussion. Please use GH tickets to report single bugs or request single features. This makes easier to keep track of each one.
