### ISSUE TITLE
Inconsistencies in file paths and database between calibre wired and wireless connection

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#3918]
* KOReader version: v2015.11-1689-g5db7bab_2018-04-22
* Device: Kobo Aura H2O2
* Calibre: 3.22.1

#### Issue
Not sure if to pin this as a calibre or koreader's fault, I'm opening here because I suspect the latter.
When connected to calibre as wireless device, calibre doesn't list the available ebooks on the device, ignoring the database built using the wired transfer. Worse, when attempting to re-transfer them, it partially ignores the path set in the the config.

My config has '{author_sort}/{title} - {authors}', to have a consistent path with the wired connection, but the destination path on the device appears to be '{authors}/{title} - {authors}'. A file saved with the wired connection would end up as 'lastname, firstname/title - firstname lastname', a file sent from the wireless connection instead ends up as 'firstname lastname/title - firstname lastname'.

#### Steps to reproduce

- Enable usb transfer and open calibre.
- Transfer any file to the device.
Default path is set to '{author_sort}/{title} - {authors}', which is respected ( can be confirmed in the builtin browser ).
- Unmount and unplug.

- Launch koreader, connect to calibre as wireless device.
- Set as path '/mnt/onboard', to match the wired connection.

First thing to notice: the previously transferred books are absent from the list, which means the database file is ignored.
Second thing to notice: confusingly, the wireless connection has a different file pattern, something along the lines of '{title} - {author} ({id})', so change it to '{author_sort}/{title} - {authors}' to match the wired connection.

- Restart calibre with the new setting.
- Reconnect the wireless device to calibre.

Third thing to notice: even with the fixed path in the setting the files on the device are still ignored.

- Attempt to transfer files to the device ( even those that are already present ).

Fourth thing to notice: the destination paths are wrong, they don't respect the configuration, approximating author_sort with author.

- Disconnect the wireless device from calibre
- Reconnect the wireless device to calibre

Fifth thing to notice: the list of files on the device empty again, it does not recognize the file that just got uploaded to the wrong path.

This results in a giant mess, making the wireless connection functionality extremely irksome to use.

**Comment by cramoisi** [comment]
I think calibre considers one device to be different devices when connected differently. The metadata plugboard list "content_server" and "folder_server" and when connected, you have to configure the device as they are different. I did that and I got no problem using calibre with koreader (dropbox, server content or folder). If I'm not totally wrong, all the problems you mentioned above are calibre's configuration related. all you have to do is made the same configuration for the " 2 devices" and be sure the metadata plugboard are the same for the two of them.

**Comment by BrainDamage** [comment]
Thanks, creating a plugboard  entry does indeed fix the '{authors}' <-> '{author_sort}' mis-mapping, however, it does not fix the device's book list being empty at every re-connection ( even after re-uploading the books trough the wireless connection ).

**Comment by cramoisi** [comment]
@BrainDamage 
I finally could check it and your right, but it's inherent to calibre, and the fact that there is two different calibre plugins involved to connect (folder_device and wireless_device) which leads calibre to thinks the devices are different. Calibre use the file `.driveinfo.calibre` to recognize them which will be different according to the plugin use to connect  as it contains it.  **"device_name": "Folder Device"**

**Comment by cramoisi** [comment]
the "wireless device" doesn't seem update or create the driveinfo file so it uses another way to recognize the device, which lead to another way to know the books present on it, so the inconsistency.

I only see one long term solution : create a specific koreader calibre plugin to manage the connection with calibre.

**Comment by cramoisi** [comment]
@Frenzie , do you think it will work if I change the device name sent to calibre with "Folder Device" and change the variables with the one used in .driveinfo.calibre ?

https://github.com/koreader/koreader/blob/68c1246575f0d95a75c3cd6d57a0aa7f5a2be81e/plugins/calibrecompanion.koplugin/main.lua#L262-L273

**Comment by cramoisi** [comment]
and mostly the device store uuid ?

**Comment by Frenzie** [comment]
@cramoisi I know very little about calibre. If it's just a small change you're proposing I'd say give it a go and test it out. :-)

**Comment by cramoisi** [comment]
@Frenzie : I did, and it doesn't seem to do anything. So voilà, I guess it's a calibre "issue" more than a koreader issue anyway since calibre is doing as expected.

**Comment by BrainDamage** [comment]
I wouldn't be so fast to pin it on calibre that the file list is empty on every connection, for one, I do use calibre companion on android and it manages to report the list of books on device fine and it does't have specific code on calibre side other than the generic wireless connection.

If I understand correctly in wired mode the device is mounted as a generic drive and it's calibre's responsibility to check for book existance by inspecting the path directly. In wireless mode instead it's up to the client ( koreader ) to push its list of books stored on device, and inspecting the code:
https://github.com/koreader/koreader/blob/68c1246575f0d95a75c3cd6d57a0aa7f5a2be81e/plugins/calibrecompanion.koplugin/main.lua#L315
the implementation is empty

**Comment by cramoisi** [comment]
not exactly : 
https://github.com/koreader/koreader/blob/68c1246575f0d95a75c3cd6d57a0aa7f5a2be81e/plugins/calibrecompanion.koplugin/main.lua#L12-L23

**Comment by cramoisi** [comment]
@BrainDamage I'm ok with you to say the thing is quite useless atm.

I test a set of modifications without success and I guess you're right : the cc plugin should be at least able to send books. Even the "update metadata" on calibre side doesn't work (it should populate the list even if it's empty). This being said, I don't know if this part of the close source of the thing or not and without somebody wants to dive in it ; i guess it will stay like that :-|

**Comment by cramoisi** [comment]
Also I noticed that smartdevice send the file with a uncommon name , like long ID 12344-5443-4354-898765.epub and this must conflict with the way folder device recognize files (by filename only)

**Comment by pazos** [comment]
Closing this issue as **can't fix**. From calibre POV each device driver has its own settings. You need to configure both to use the same pattern if you want to avoid mismatches.

Other comments from this ticket will be addressed in #6177
