### ISSUE TITLE
CSS snippets: brainstorming

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3923]
Follow up to https://github.com/koreader/koreader/issues/1430#issuecomment-385056402
> What I wish we could do is just to not have to look at the publisher stylesheet inside the epub.
I'd like if we had another menu list with "css snippets", multiple checkboxes, that would generate some rules with !important that would be appended (dynamically) to the content of epub.css and fed to crengine.
I see for my use such snippets as:
> -    change link colors from gray to black (always on for me)
`a { color: inherit !important; }` or `a { color: black !important; }`
> -    avoid page breaks before (needed for some books to avoid blank page at chapter page)
`h1, h2, h3, .title, .title1, .title2, .title3 { page-break-before: avoid !important}`
> -    ignore publisher margins (that's the one I wonder if we can do it)
`body { margin: 0 0 0 0 !important; }`
> -    ignore publisher line-height
`* { line-height: inherit !important ;}`
> -    ignore publisher font-family (different from disable embedded fonts)

With the recent improvements to crengine stylesheets handling, it looks like we can do that.
With a small patch to cre.cpp and CreDocument:setStyleSheet() to allow providing a file path and/or some css content:
```lua
-function CreDocument:setStyleSheet(new_css)
-    logger.dbg("CreDocument: set style sheet", new_css)
-    self._document:setStyleSheet(new_css)
+function CreDocument:setStyleSheet(new_css_file, appended_css_content )
+    logger.dbg("CreDocument: set style sheet:",
+        new_css_file and new_css_file or "no file",
+        appended_css_content and " and appended content ("..#appended_css_content.."b)" or "(no appended content)")
+    self._document:setStyleSheet(new_css_file, appended_css_content)
 end
```

So, how should we present/implement that?

It should be under a new menu item: same level as the current `Style >` or under it?

How should that feature be named (and its menu item string): `Styles fixes >`, `Stylets >`, `User styles >` (but they are not full stylesheets)  `Style snippets >`? Other suggestions?

Should we just allow the user to put some of his own in `data/userstyles/` , and just show the filename in the menu? Or should we provide a collection of ready to use such snippets (to which we would add the user own ones found in that directory) ?

These would be checkboxes and would be checked/unchecked applied/unapplied on tap.
The list of applied snippets would be saved in the metadata.epub.lua, and re-applied on book opening.

Should we allow with Hold to select some default ones that would be applied once a book is first opened (I guess, once it's been opened and the list saved, it would be hard to re-apply defaults one, to distinguish between defaults that are no more in this book metadata.lua because they have been disabled cause the user dont want it for this book).
Or can user changes to our shipped epub.css continue to be done manually by editing epub.css, or by having another complete style file set as default?

How to implement that collection?
- multiple CSS files, with name/description on first line, to be parsed to build the collection menu list
- 1 JSON file, ala `data/hyph/languages.json`, pointing to additional css files alongside? But could Description in it be translatable?
- 1 LUA single file, ala `frontend/ui/language.lua`, that would include css code in lua strings `[[ body { margin: 0 0 0 0 !important; } ]]` (I'd prefer that - but we'd lose the syntax highlighting an editor would provide when editing individual css files), 
Would something like that do?
```lua
return {
    _("Page fixes") = {
        _("Ignore publisher page margins") = {
            priority = 1,
            css = [[body { margin: 0 0 0 0 !important; }]],
        },
        _("Ignore all publisher margins") = {
            priority = 2,
            css = [[* { margin: 0 0 0 0 !important; }]],
        },
        _("Ignore publisher line heights") = {
            priority = 1,
            css = [[* { line-height: inherit !important ;}]],
        },
    },
    _("Text fixes") = {
        _("Links always black") = {
            priority = 1,
            css = [[a { color: black !important; }]],
        },
        _("Prevent sub- and superscript from affecting line-height") = {
            -- https://friendsofepub.github.io/eBookTricks/
            priority = 1,
            css = [[
sub {
  font-size: 0.675em;
  line-height: 1.2;
  vertical-align: sub;
  vertical-align: -20%;
}

sup {
  font-size: 0.675em;
  line-height: 1.2;
  vertical-align: super;
  vertical-align: 35%;
}
            ]],
        },
    },
    _("Publishers fixes") = {
        _("Jack & John Ed.") = {
            _("Remove their ugly italic font, use their nice font instead") = {
                priority = 1,
                css = [[...]],
            },
            _("Scale down their ridiculously big separator images") = {
                priority = 1,
                css = [[...]],
            },
        },
        _("Mark & Luke Publishing") = { },
    },
}
```

Any other thoughts?

**Comment by Frenzie** [comment]
I like the menu idea. Here's a screenshot of classic Opera's built-in custom styles.

![screenshot_2018-05-02_16-58-37](https://user-images.githubusercontent.com/202757/39530843-18c80922-4e2a-11e8-984d-a905dc2683b9.png)

> Should we just allow the user to put some of his own in data/userstyles/ , and just show the filename in the menu? Or should we provide a collection of ready to use such snippets (to which we would add the user own ones found in that directory) ?

As a user that would definitely be my preference.

Anyway, I'll give you more detailed feedback tomorrow afternoon/night if you want. No time today. :-)

**Comment by cramoisi** [comment]
@poire-z : what will be the reaction of KOReader options with the margins snippet active ? ie : will the margins options be functional with 0 0 0 0 active ?

sup and sub snippet are totally a good idea, did you test them on an actual stylesheet ? I had trouble time to find one functional combo (and I had put them on the same level than text).

LUA files seems nice enough, even if I had the same reserve than you for the syntax highlight.

**Comment by poire-z** [comment]
> I'll give you more detailed feedback tomorrow afternoon/night if you want

Of course :)

> what will be the reaction of KOReader options with the margins snippet active ? ie : will the margins options be functional with 0 0 0 0 active ?

Configured margins are managed outside of styles: they just increase/decrease the rect that is given to crengine so it can draw content on it (so, with very-zero magins, it tells crengine to draw on `Screen.width x Screen.height` - with 20px margins, it tells crengine to draw on `(Screen.width - 40) x (Screen.height - 40)`)

> sup and sub snippet are totally a good idea, did you test them on an actual stylesheet ? I had trouble time to find one functional combo (and I had put them on the same level than text).

Yes, I tested that on wikipedia epub full of footnotes, and it was better, but still not perfect. I was actually hoping you and @Frenzie would play with it and find a better one :)

**Comment by Frenzie** [comment]
> Should we allow with Hold to select some default ones that would be applied once a book is first opened (I guess, once it's been opened and the list saved, it would be hard to re-apply defaults one, to distinguish between defaults that are no more in this book metadata.lua because they have been disabled cause the user dont want it for this book).

How is that hard? False = do not want, nil = whatever, do the default. ;-) 

I would also try to keep MuPDF in mind while writing the feature if reasonably possible. Most of the code, except applying it to the engine should be engine agnostic. (Should is not must in spec language. It's more like a very strong suggestion. Only must is fully binding.)

**Comment by cramoisi** [comment]
@poire-z not a problem. The only difficulty is to find a way which use styles supported by KOReader

**Comment by cramoisi** [comment]
@poire-z  are you sure vertical-align is supported ?

**Comment by poire-z** [comment]
Indeed, `vertical_align` is parsed, not as a _length_, but as expecting a `named value` from the following list:
```
    "baseline",              ***
    "sub",                   *** 
    "super",                 ***
    "top",
    "text-top",
    "middle",                ***
    "bottom",
    "text-bottom",
```
and only those I marked with `***` are actually managed around [here](https://github.com/koreader/crengine/blob/feba497dd3ffb739b7feec7e3be7fb171bd12e4a/crengine/src/lvtextfm.cpp#L781-L794).

To know what's supported (and even if listed there, it may not be fully used in the other code):
https://github.com/koreader/crengine/blob/master/crengine/include/cssdef.h
https://github.com/koreader/crengine/blob/master/crengine/src/lvstsheet.cpp

**Comment by cramoisi** [comment]
@poire-z : thanks, that will be easier :)

**Comment by cramoisi** [comment]
ok, for sup, with our limitations, `sup {  font-size: 50%;  vertical-align: super;}` does the trick. percentage or size in vertical-align are ignored, and modifying the line-height doesn't seem to do anything. All other trick involving baseline and top or a relative position are out anyway. `text-top` on vertical-height should do it in one command thought

<img width="524" alt="capture d ecran 2018-05-03 22 05 32" src="https://user-images.githubusercontent.com/28014131/39600138-2e0ce042-4f1e-11e8-8966-d4e8dbba26a5.png">

<img width="365" alt="capture d ecran 2018-05-03 22 05 13" src="https://user-images.githubusercontent.com/28014131/39600147-3368a36e-4f1e-11e8-929f-f708d3452747.png">

**Comment by poire-z** [comment]
The code I linked too above was for vertical alignment of images. The code for text is [there](https://github.com/koreader/crengine/blob/feba497dd3ffb739b7feec7e3be7fb171bd12e4a/crengine/src/lvtextfm.cpp#L806-L825).
The space for bit flags LTEXT_VALIGN_SUB / LTEXT_VALIGN_SUPER  / LTEXT_VALIGN_MIDDLE  is a bit tight for us to add more of them and implement the other `vertical-align` named values...
But may be we can tweak the C code for these if someone can think of a good alternative method to compute a better `wy` (= `word->y`).

**Comment by cramoisi** [comment]
@poire-z : ok. anyway, in this state, the middle value doesn't do it and I'm pretty satisfied with the result of `sup { font-size: 50%; vertical-align: super;}`

A bit odd, but the middle value is great for sub : `sub { vertical-align: middle; font-size: 50%;}`

<img width="266" alt="capture d ecran 2018-05-04 07 35 21" src="https://user-images.githubusercontent.com/28014131/39614157-e435c042-4f6d-11e8-9fd8-bc8912e44a57.png">
<img width="242" alt="capture d ecran 2018-05-04 07 39 33" src="https://user-images.githubusercontent.com/28014131/39614200-507dac42-4f6e-11e8-9d10-52a5cef6556f.png">

with `.apnb {  font-size: 60%;  vertical-align: sub;}` : 

<img width="427" alt="capture d ecran 2018-05-04 07 41 02" src="https://user-images.githubusercontent.com/28014131/39614220-8a321ad6-4f6e-11e8-9c74-09613c559704.png">

with `.apnb {  font-size: 50%; vertical-align: middle;}`:

<img width="520" alt="capture d ecran 2018-05-04 07 44 08" src="https://user-images.githubusercontent.com/28014131/39614274-f2c066ca-4f6e-11e8-877f-b4d02783d2a2.png">

**Comment by poire-z** [comment]
Implemented by #3944

**Comment by poire-z** [comment]
@cramoisi : do you think your sub & sup tweaks should have `!important` ? For both properties?

I have a book with which I use:
```
* { font-size: inherit !important; }
* { line-height: inherit !important; }
sup { font-size: 50%; vertical-align: super; }
sub { font-size: 50%; vertical-align: middle; }
sup { font-size: 50%; vertical-align: super; }
sub { font-size: 50%; vertical-align: middle; }
```
The `Ignore publisher font-heights` tweak prevent the sup&sub tweak to fully do its job.

(Just noticed a bug above: if you set one as default, disable and re-enable, the tweak css appears twice...)

**Comment by cramoisi** [comment]
@poire-z : after thought, I would use sub in place of middle ; and yes, I would add the !important (I did in a custom, in fact)
Another thing a saw is a lot of publishers don't use the sub and sub tag but a span with a class so the snippet stays ineffective....

**Comment by roger64** [comment]
I arrive late on this one. 

I have been using for years this code for superscript.  It respects line-heights and adapts to any font-size (while a fixed percentage value can fit one paragraph but not the other...)
```
sup { 
 vertical-align: text-top;
 font-size: smaller;
}
```

**Comment by cramoisi** [comment]
hi @roger64 , you mean you use it within koreader ? (I test `vertical-align: text-top;` without sucess and I didn't use it for @poire-z [mentioned ](https://github.com/koreader/koreader/issues/3923#issuecomment-386298207) it isn't implemented. as for smaller I don't remember how I try it.
