### ISSUE TITLE
Action after finishing reading book

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#3937]
Similar and discussion in #2776, #3545, #3405

I have two proposal what to do after finishing book (user does a "next page" swipe in the last page of the current file).
**Proposal no 1:**
Action is defined in menu option-> document
![test - koreader_079](https://user-images.githubusercontent.com/22982594/39767791-ddde8b5c-52e7-11e8-9e67-f491c3157681.png)

![test - koreader_080](https://user-images.githubusercontent.com/22982594/39767806-e3eb9986-52e7-11e8-9b87-6e9c454de3db.png)
![test - koreader_081](https://user-images.githubusercontent.com/22982594/39767818-e8e95446-52e7-11e8-9c96-822e86a86fc7.png)

**Proposal no 2:**
Without configuration. One dialog with options to choose

![romeo and juliet - koreader_082](https://user-images.githubusercontent.com/22982594/39767823-eeb55b04-52e7-11e8-97cc-b5bf6b33b2df.png)

What do you think. Which option will be better?

**Comment by Frenzie** [comment]
Maybe both?

Configuration in menu for default action (without any prompts):

* Ask (=default, this is the popup dialog from proposal 2)
* Do nothing
* Book status
* Next file
* Return to file browser

**Comment by KenMaltby** [comment]
Not sure how "Next file" would work, next alphanumerically from current sort of the file browser, or maybe next in a series?

**Comment by robert00s** [comment]
@Frenzie: Nice idea.
@KenMaltby: Next file means "next document from current sort of the file browser (eg title, size, type etc).

**Comment by robert00s** [comment]
![romeo and juliet - koreader_085](https://user-images.githubusercontent.com/22982594/39775486-5097be82-52fe-11e8-949f-c8c0e6fa0ee9.png)
![romeo and juliet - koreader_086](https://user-images.githubusercontent.com/22982594/39775492-54235df4-52fe-11e8-9373-bdcd811aa3d2.png)
![romeo and juliet - koreader_087](https://user-images.githubusercontent.com/22982594/39775498-56977d18-52fe-11e8-8b19-c0d7f6e6d59c.png)

**Comment by Frenzie** [comment]
Looks pretty good to me!

I'd try to use something shorter, like "Document finished action" or "End of document action". Any suggestions @KenMaltby ?

I'm not sure if the full "Ask with popup dialog" line is really necessary? But I suppose it can't hurt.

For the title text, maybe something like… "You've reached the end of the document. What would you like to do?" Or less jovially, "End of document reached."

Do nothing might not have been my best suggestion. Maybe something like "Keep reading" or "Return to book"?

Similarly, just "File browser" should suffice, just as it does for "Book status".

**Comment by KenMaltby** [comment]
I guess if the "Do nothing" option was set, when you were on the final page, (205/205, in the example) and you try to go to the next page, there would be no change.  Whatever was on page 205 would remain.  With the "Ask" option set, trying to go to 206 would bring up the message box over what is on page 205.  (This should not be a problem now that the message boxes can be moved around the page)  Just "File Browser" should work in the Message box.  "Do nothing" in the message box might be just "Cancel", to be consistent with similar actions.

**Comment by gerhaher** [comment]
For those who have Reading statistics activated it would be a nice thing if it also calculated the number of finished books. 

Therefore when finishing a book a pop up window could say something about this calculation. Something like this: "Now you have finished 7 books last month. 25 books last year,...." and so on.

My 2 cents.
