### ISSUE TITLE
error when running emulator on vm lubuntu 64 bits on windows 10 host

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3938]
* KOReader version: last
* Device: emulator

#### Issue
After a successful compile, I got this error when `./kodev run`
It is inside a Lubuntu VM on VirtualBox PC (w10). The same virtualdisk runs on VirtualBox mac without error (the emulator launch alright).
I got this error in all cases (creating the VM on mac (HSierra), compiling on mac(ok), running emu on mac (ok) and running emu on pc (ko) ; creating the VM on pc, compiling on pc (ok), running emu on pc (ko), running emu on mac (ok)).

the virtualdisk is on a usb stick, the whole idea is to take it with me between computers.

---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/09/18-12:12:15
 [*] Version: v2015.11-1703-g62630706_2018-05-07

ffi.load: blitbuffer
ffi.load (assisted searchpath): ./libs/libblitbuffer.so
ffi.load: SDL2
ffi.load: SDL2
SDL: no gamecontrollers connected
05/09/18-12:12:16 DEBUG refresh on physical rectangle 0 0 540 720
ffi.load: libs/liblodepng.so
ffi.load: gtk-3
ffi.load (warning): libgtk-3.so: cannot open shared object file: No such file or directory
ffi.load: gtk-3.so.0
ffi.load: gtk-3
ffi.load (warning): libgtk-3.so: cannot open shared object file: No such file or directory
ffi.load: gtk-3.so.0
05/09/18-12:12:16 INFO  initializing for device SDL
05/09/18-12:12:16 INFO  framebuffer resolution: {
    ["h"] = 720,
    ["w"] = 540
}
ffi.load: libs/libfreetype.so.6
05/09/18-12:12:16 DEBUG show widget unknown
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
Illegal instruction (core dumped)

#### Steps to reproduce
installing virtualbox pc windows 10, installing lubuntu 64 bits, compiling koreader's emulator inside lubuntu vm, running the emu from it ; crash.

**Comment by Frenzie** [comment]
Sounds like an architecture mismatch between different CPU models. See https://github.com/koreader/koreader-base/pull/644

@NiLuJe Do you think we should just do generic (that is, not pass any march flags) for the emulator by default? It is conceivably annoying that I can't just copy over a compiled copy to my old netbook.

**Comment by NiLuJe** [comment]
Yeah, that sounds like a sound reasoning ;).

I'd maybe leave/add the possibility of honoring the env's CFLAGS, if for some reason someone absolutely wants to do an optimized, local emulator build?

**Comment by cramoisi** [comment]
it's more that the build doesn't work inside a lubuntu vm on w10 hosts when built on it and it exit successfully. I only incidentally after that I saw it was working when running the .vdi on my mac. So I didn't drop anything from a vm to another vm.

**Comment by Frenzie** [comment]
It'd probably also fix some of these issues on Travis as a side effect, which I know must run on servers which aren't guaranteed to have the same arch (or it wouldn't happen).

@cramoisi You're saying you did a *completely* clean build in VirtualBox on Windows and you still got that core dump? Sounds more like a VirtualBox issue then. But compiling it without -march=native might still help against the problem.

**Comment by cramoisi** [comment]
@Frenzie : Yes, I said that (tried to said it). I that this install (not just the build on of koreader emu, the whole virtual disk of the vm, so the lubuntu install with the emu inside of it), when run from a vm on virtualbox mac do it right.

**Comment by cramoisi** [comment]
@Frenzie :  no. Everything was done on pc w10 and doesn't work. After that launching a vm with the same config and with this very non-working virtualdisk that was magically working.
So, it must be a VB on w10 bug only because the VB VM's have the same config on the two sides. I will try with a 32 bit guest and if it doesn't work, i'll be done with this.

**Comment by cramoisi** [comment]
virtualbox issue ; it works with no problem using vmware, so let's close this.
