### ISSUE TITLE
Fixing crengine and breaking past highlights, or not?

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#3940]
I just realized that fixing even a simple thing in crengine may break past highlights and bookmarks (I'm not sure I have not yet already done that with the fixes I did these last weeks...).

I personally don't use highlights at all, but many users do. So, I'm asking users and developers how they see things: should we fix, enhance, _and_ break - or just not touch anything?

For example, the HTML `<cite>` tag, that should be inline and italic, is currently considered to be a block element by crengine (may be because it has/had some other meaning in the old pdb or fb2 formats), so it is rendered like a `<P>` or a `<DIV>` (and this can make things awful and unreadable in documents that have lots of them).

So, this HTML snippet (put inside an EPUB):
```html
<html>
<head>
</head>
<body>
<p>
This is some text that I wrote, but not this: <cite>this is a citation</cite> and now I'm back writting my own text.
</p>
</body>
</html>
```
displays currently as this:
<kbd>![image](https://user-images.githubusercontent.com/24273478/39825360-e867d914-53b1-11e8-8886-cb68417a12f3.png)</kbd>
I added 2 highlights to simulate past highlights.

This problem could easily be solved by adding to `html.css` and `epub.css` (so, not affecting other book formats - but it would be the same if hardcoded as an inline element in crengine code)
`cite { display: inline; font-style: italic; }`

It would then correctly display as:

<kbd>![image](https://user-images.githubusercontent.com/24273478/39825325-cc5ca024-53b1-11e8-9ee6-e924d721a5e9.png)</kbd>

but the highlights are gone :( because the DOM structure changes when you switch the nature of elements between inline and block.
(In that simple case, only highlights made in a `<p>` or `<div>` containing a single `<cite>` would be lost, all other would still be valid - but losing even a few may be dramatic for some people.)

Because internally, some autoBoxing nodes are added for rendering purpose, so, the highlights xpath/xpointers that were previously:
```lua
        [1] = {
            ["page"] = "/body/DocFragment/body/p/autoBoxing[1]/text().26",
            ["highlighted"] = true,
            ["notes"] = "wrote",
            ["datetime"] = "2018-05-09 17:44:41",
            ["pos1"] = "/body/DocFragment/body/p/autoBoxing[1]/text().31",
            ["pos0"] = "/body/DocFragment/body/p/autoBoxing[1]/text().26"
        },
        [2] = {
            ["page"] = "/body/DocFragment/body/p/autoBoxing[2]/text().13",
            ["highlighted"] = true,
            ["notes"] = "back writting",
            ["datetime"] = "2018-05-09 17:44:47",
            ["pos1"] = "/body/DocFragment/body/p/autoBoxing[2]/text().26",
            ["pos0"] = "/body/DocFragment/body/p/autoBoxing[2]/text().13"
        },
```
would not be found in the new DOM.
If I highlight again these words on the new DOM, they become:
```lua
        [3] = {
            ["page"] = "/body/DocFragment/body/p/text()[1].26",
            ["highlighted"] = true,
            ["notes"] = "wrote",
            ["datetime"] = "2018-05-09 18:00:48",
            ["pos1"] = "/body/DocFragment/body/p/text()[1].31",
            ["pos0"] = "/body/DocFragment/body/p/text()[1].26"
        },
        [4] = {
            ["page"] = "/body/DocFragment/body/p/text()[2].13",
            ["highlighted"] = true,
            ["notes"] = "back writting",
            ["datetime"] = "2018-05-09 18:00:53",
            ["pos1"] = "/body/DocFragment/body/p/text()[2].26",
            ["pos0"] = "/body/DocFragment/body/p/text()[2].13"
        }
```
(even if it looks like we could translate back the old ones into the new ones by removing the `autoBoxing[2]`, that's just an optical illusion :) say we fix an inline element that should be a block element, and that won't work. For more serious stuff like fixing list items, that would be impossible.)

So, highlights can be broken by simple css changes (and obviously by more complex code changes), and there's no way to keep xpointers valid or translate them accurately in the process.
We could think of a way to have surviving xpaths (I see no obvious solution for that, dunno if that's possible), but that won't help with past xpointers.
I tried to address a way to keep old code for already opened book in #3928 , but even these ugly checks won't help with the above simple CSS change.

So, any thoughts?

(Note that people can already break their own highlights by changing style in the `Style >` menu, or by toggling `Embedded styles` - but they would find them again by reverting these changes.)

**Comment by Frenzie** [comment]
> For example, the HTML <cite> tag, that should be inline and italic

Technically, unless the HTML5 spec changed something, the italic part is only a styling suggestion. One that it'd be stupid to ignore, of course. ;-)

> because the DOM structure changes when you switch the nature of elements between inline and block.

It's really a pity that it's basically a "proper" part of the DOM instead of some kind of shadow DOM to perform special tricks but not get in the way.

Since we know the highlighted text, I can't help but wonder if there's something we could do in front to rematch the text to a node?

**Comment by cramoisi** [comment]
the fact that nightlies could break things seems to me quite a common feature :-)
The stable releases could have a role to play here. What would happen if the highlight are exported before an update and imported after (if they could be imported/exported, never tried). I don't know if it's very kind to think that but I would only bother about that only between two stables :-)

**Comment by poire-z** [comment]
> I would only bother about that between two stables

That's exactly my concern.
I'm not talking about temporary breakage (like I may have done from saturday to tuesday), i'm talking about permanent: we fix rendering, some highlights are broken, we keep the rendering fix, the breakge stays :)
So, people with many highlights would have to stick to some old stable - and it would mean we could never trust highlights (unless we find a way to make them more solid). (Knowing a bit how they are made and stored, I already don't trust them, I would not use them for serious stuff).

pinging @frankyifei (who had met autoBox and tweaked the getRect & co used for highlights in the past) for his opinion

**Comment by Frenzie** [comment]
> Knowing a bit how they are made and stored, I already don't trust them, I would not use them for serious stuff

Yeah, I had no idea that these nodes were these highly variable things. When I first saw them I thought it was a fairly clever reference method that would always work as long as the markup of the document in question doesn't change.

**Comment by cramoisi** [comment]
(just random thoughts) What about using some process to convert highlight between when KOReader updates ? highlight is just a text string. What about strip it raw with some context (like some words before, some words after to make it a string of words as unique as possible and regex it after at the right place ?

**Comment by Eduardomb22** [comment]
I think it is more important to fix crengine, so I don´t care if I lose my highlights. (I think this is a unpopular opinion)
Btw, probably a stupid question, but I´m not a programmer, will we lose all highlights, even from PDF? If I´m not wrong, crengine is not used for PDF, right?

**Comment by Frenzie** [comment]
PDF and DjVu are fixed page layouts. They never change. :-)

Those highlights are defined as coordinates on the page:

```lua
    ["bookmarks"] = {
        [1] = {
            ["page"] = 1,
            ["highlighted"] = true,
            ["notes"] = "also more faithful to the original document",
            ["datetime"] = "2018-05-11 10:33:31",
            ["pos1"] = {
                ["page"] = 1,
                ["x"] = 1349.4658119658,
                ["y"] = 1305.8760683761,
                ["rotation"] = 0,
                ["zoom"] = 0.55058823529412
            },
            ["pos0"] = {
                ["page"] = 1,
                ["x"] = 666.55982905983,
                ["y"] = 1309.5085470085,
                ["rotation"] = 0,
                ["zoom"] = 0.55058823529412
            }
        }
    },
```

(Or in case of PDF, optionally made part of the document itself.)

> I think it is more important to fix crengine, so I don´t care if I lose my highlights. (I think this is a unpopular opinion)

It might not be much consolation to those who disagree with the both of us, but technically you don't lose the text of the highlight, only the position. If you highlighted an entire paragraph the loss might not even really matter.

**Comment by cramoisi** [comment]
I only use highlights for read-proofing and I remove them as I correct the typo ; but even if I used them in a more serious way I would still think it's better to fix than to keep a "broken" crengine just for the sake of some highlights.

**Comment by poire-z** [comment]
Thanks for the feedback, and somehow allowing for the possibility to break highlights :)
I'll have a look anyway (before any other breaking fix) if there's a chance to make them solid.

> even if it looks like we could translate back the old ones into the new ones by removing the autoBoxing[2], that's just an optical illusion :) 

Somehow, a quick test shows that it may not be an optical illusion, and that it may work (in some cases? always? dunno yet).

**Comment by poire-z** [comment]
Following up here on https://github.com/koreader/koreader/pull/3968#issuecomment-390473504 and how to enable new features while keeping compatiblity with old highlights/bookmarks/last_xpointer.

This new list items rendering looks better to me on many books, and so does the `<cite>` change from `block` to `inline`, and I think they are the _right_ way to do things.
For now, they are disabled by default, and we can enable them with Style tweaks.

May be we can enable them by default (= updating the crengine .css files and code with them), and just provde via Style tweaks a way to get back the old _broken_ behaviour?
Instead of `Enhancements > Better rendering of list items`, we'd have `Legacy behaviour > Old rendering of list items`, so users for which the new stuff do break things could go there to reactivate the old stuff?

Then, should we really have to deal with previously opened books (like it was done [here](https://github.com/koreader/koreader/pull/3928/files#diff-951479c7ba6627645890ee6616d8ad50)) to automatically enable this legacy stuff on them? Or just expect the users to know about this and let them do that when they feel they are missing highlights?

(That would work for enhancements/fixes that can be toggled with CSS, may be not for more hardcore changes, but it would mean we should always try to implement possibly-breaking-past enhancements via CSS)

**Comment by cramoisi** [comment]
I vote for fixing, updating and informing. People don't update a lot (except those who linger here) and they just need to be informed of the potential issue of an update. (I'm more into "let's keep styletweak" for user side before it becomes a collection of thing difficult to sort).

**Comment by Frenzie** [comment]
@poire-z Yes, I like that better. I think ideally it should be done automatically, perhaps combined with some unit tests to ensure it won't break. In fact it might not be a bad idea to add some highlighting unit tests to be alerted of accidental breakage on top of what we know will break.

**Comment by poire-z** [comment]
I think I should be able to manage the `<cite>` and `<li>` changes via the `cre_dom_version` [method](https://github.com/koreader/koreader/pull/3928/files#diff-951479c7ba6627645890ee6616d8ad50).
So, we won't need to have any reference to them in Style tweaks.
Books previously opened (that have a metadata.lua, whether with highlights or not, but because they all have a last_xpointer that points to the current page, that can be broken too by the changes) will continue to have the old wrong behaviour, so they won't be impacted by the breaking changes.
Purge .sdr on them and they will get the new behaviour. Newly opened book will get the new behaviour.

@KenMaltby : Style tweaks address both kind of users you described, see screenshots in #3944 (power users with User style tweaks, others with the ready made available tweaks, with descriptions of what they do on Hold).

**Comment by poire-z** [comment]
Closing for now, as we found a method to not break past highlights for these few fixes and enhancements.
(Will re-open when this method won't work with some other fix :)
