### ISSUE TITLE
Empty space in landscape mode

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#3945]
* KOReader version:
koreader-beta-20180412 (also everyth other version since that version has the exact issue)
* Device:
Inkbook

I am getting empty space on the right side of the screen in landscape mode when I enable the night mode. I do not have this issue with regular daylight mode (non night mode) in landspace orientation. 

I also do not have this issue with portrait mode when it is in night mode.  

I am not sure if it is a empty space or not but it is a portion of the space that is not updated and it is almost cut off , it takes about %25 of the screen space.

thanks

**Comment by cramoisi** [comment]
@gerroon could you update with a picture of the thing ?

**Comment by Frenzie** [comment]
There was no issue previously? Which filetype is this?

**Comment by Frenzie** [comment]
@poire-z Possibly, but in that case it should be a problem on all versions ever rather than just those from ~April onward.

**Comment by gerroon** [comment]
@cramoisi 

I am using Pdf

Here is the image

https://filebin.net/km6ps6g3zrp76k1a/koreader.jpg?t=m4cdnozb

**Comment by Frenzie** [comment]
@gerroon You can add images directly on GH. :-)

(See the "selecting them" just under the textbox)

![koreader](https://user-images.githubusercontent.com/202757/40065066-22dcc736-5861-11e8-87ed-35094408d294.jpg)

But am I understanding you correctly that this didn't used to be an issue or has it always been one?

**Comment by gerroon** [comment]
@Frenzie, 

My script blocker blocks unnecessary scripts.

I am thinking that this issue was not there before like last year, but to be honest I d onot use the landscape mode that often so I might be mistaken.

**Comment by Frenzie** [comment]
Not autocrop. it looks like what @poire-z says except my Android device doesn't have any issues like that.

**Comment by poire-z** [comment]
I can reproduce this on my phone (only happens when both nightmode & landscape, no matter the order they were toggled).
Happens too with the oldest nightly I still had downloaded on my phone: 1627 38a0519 2018-04-05.

The strange thing is that the part of the screen on the right (that is not refreshed, and does not have the right side of the book), looks like it oscillates between 2 old nightmode buffers (while reading a book in nightmode landscape, I can either see: an old nighmode portrait Screen menu - or and old nightmode portrait file browser.. :)

**Comment by Frenzie** [comment]
Nightmode and landscape, in whichever order:

![2018-05-15 18 51 10](https://user-images.githubusercontent.com/202757/40071482-3024ffd4-5871-11e8-863a-b08612ee14cb.jpg)

**Comment by Frenzie** [comment]
But nobody with issues mentioned any Android versions.

**Comment by poire-z** [comment]
6.0.1 for me.
(and we already had different behaviours with nightmode some months ago: @Frenzie not getting any problem, @gerroon crashing, @poire-z not crashing but not getting nightmode at all :)

**Comment by Frenzie** [comment]
That phone is also on 6.0.1. Grmbl.

I suspect the Inkbook is probably on something like 4.ancient though.

**Comment by gerroon** [comment]
@Frenzie 
Most android ebooks are kitkat. I have not seen any that uses anything above that.

**Comment by gerroon** [comment]
Bug no? Any ideas if this will be fixed?

**Comment by Frenzie** [comment]
Did you try if it also occurs when you don't turn the device itself to ensure there's no built-in auto-rotation at work?

**Comment by gerroon** [comment]
This is inkbook, there is no auto rotation. I rotate in Koreader.

**Comment by gerroon** [comment]
hey I tested this with my phone (Samsung, Lollipop 5.1, Amoled) and I have the exact same issue on my phone. So this is not just an eink issue.

**Comment by gerroon** [comment]
just tested the nightly, still there :)

**Comment by gerroon** [comment]
v2015.11-1777-g8c9fe9b_2018-07-11/   still there on all of my devices like Inkbook, Samsung  Lollipop phone etc.
