### ISSUE TITLE
Web Browser

### ISSUE THREAD

**Issue by isayk1988** [koreader/koreader#3948]
* KOReader version:
* Device:Kobo Aura One

Hello 
Where can i find web browser on koreader?

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Nowhere, I think? :-p Is that implied somewhere?

**Comment by cramoisi** [comment]
@isayk1988 : There is no web browser within KOReader.

But, if you want to use it for wikipedia, there is a wikipedia plugin that let you search and read it. If you want to use it for calibre opds, there is a plugin for it too ; but aside of that, you're out of luck.

**Comment by Frenzie** [comment]
As an aside, NetSurf and Qt already support framebuffer output, so with any luck someone dedicated might be able to hack together a working Kobo browser in mere hours if they knew what they were doing.

**Comment by isayk1988** [comment]
That is very bad actually 
Thanks to answer my question because i search anywhere to find it!

Unfortunatly i dont know about writing or hacking but i hope one day make a good browser like koreader for reading because browsers of kobo or kindle very annoying me!(why they didnt make like chrome old chrome just!)

 About wiki ya yes but i read on mobileread sute that can load kiwiki (offline wiki) or you downliad data then open with zip and copy html in one folder ir seperate by subject ir alphabetic and use it 

Thanks for your helping

**Comment by KenMaltby** [comment]
The last thing I would want on my e-reading device is a "Net Browser".  KOReader has a few plugins to do things on the net that relate to using the device as a reader, great, that fits in fine.  

Why would anyone want to browse the full color, video enhanced, high refresh rate web using an eink device, anyway?

**Comment by Frenzie** [comment]
I didn't mean related to KOReader. I'll close this now. :)

**Comment by isayk1988** [comment]
Excusme write after closed!

I have to say i want browser not like ipad 
I think ebook reader must have ebook reader browser 
Browser that i can save site to book format can download book and can connect to storage and reflow site like Koreader do and my other feature 
Wiki is one of many site that give open source data and many people use other site 
This excuse let we see android ebook reader that actually not professional ebook reader!

**Comment by robert00s** [comment]
You can write your own plug-in with web browser.

**Comment by isayk1988** [comment]
How? 
Can you help me?

**Comment by Frenzie** [comment]
Wouldn't it make more sense to use that browser that comes with Nickel? Except for a few minor tweaks (like pg up/down buttons on the screen instead of dragging) I doubt one could do much better.
