### ISSUE TITLE
Weird  & sneaky behavior w/ 32bpp fb

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#3949]
On my H2O running FW 4.8 (i.e., post 32bpp switch), I inadvertently realized that some stuff appears to be a bit wonky...

While looking into the fonts thing w/ Wikipedia lookups, when looking at fbgrab captures, it looked like, on some text elements of the UI, the alpha channel appeared to be filled with garbage instead of being set to 0xFF...

![ko_alpha_wiki_b](https://user-images.githubusercontent.com/111974/40015572-16aa45b8-57b4-11e8-984b-f7d27fa98e63.png)

It only happens for *some* UI elements, and, funnily enough, only happens in wikipedia popups when there's an image to render...

![ko_alpha_wiki](https://user-images.githubusercontent.com/111974/40015595-2d31f7e0-57b4-11e8-9592-3b58739b650f.png)

FWIW, it doesn't happen in CRe (except for the page numbers in the footer).

Possibly related, I'm guessing we're processing thumbnails in the wrong order (RGB instead of BGR?), because the color channels are all fucked up, too ;).

(f.g., American Gods' cover is supposed to be deep blue, not brown ^^).

![ko_alpha](https://user-images.githubusercontent.com/111974/40015602-30b5ed5e-57b4-11e8-82df-24277611aafb.png)

----

I *think* FBGrab's end of things is sane (after all, the 32bpp codepath is the most simple of all), and things definitely look okay in Nickel.

Granted, it's mostly invisible when looking at the actual screen of the device, but I'm mainly concerned with the fact that we may be skipping fast codepaths in some blitting cases because of the fucked up alpha...

**Comment by poire-z** [comment]
> I tried looking into it, but most of the bb & blitting stuff goes way over my head... ;'(

Same for me, but that did not prevent me to make some changes, often by luck :)

I added this for the images embedded in textboxwidget:
https://github.com/koreader/koreader/blob/c0e80461ff5bf5ab200fe346793839ca77286773/frontend/ui/widget/textboxwidget.lua#L343-L355

I was just going to suggest trying to use RGB32A, but there's no such thing as RGB32A :)

So, when there is no image in wikipedia result, we use the default BB8: so, you don't get any such _délavé_ effect at all when there is not image?

**Comment by poire-z** [comment]
And it looks like it's only the text ?
So, may be it's when freetype > RGB32 that there is a problem:
https://github.com/koreader/koreader/blob/fcc24fc7b1dcd1dcf05b09ee132d86065c6ec82a/frontend/ui/rendertext.lua#L225-L235
when dest_bb is RGB32

**Comment by NiLuJe** [comment]
@poire-z : Yeah, that's basically where my grepping led me, too ;).

**Comment by NiLuJe** [comment]
Yep, it helps for that very specific case.

![ko_alpha_nobb](https://user-images.githubusercontent.com/111974/40019974-199502c4-57c1-11e8-9cc9-872381062ecb.png)

Which probably points to renderUtf8Text doing weird crap w/ BB >24bpp...

**Comment by poire-z** [comment]
What did you change?

**Comment by poire-z** [comment]
Strange, cause after that, it's a BB8, just like everything else :|

**Comment by NiLuJe** [comment]
And that indeed fixes the text. Which means that 'everything else' may not always be BB8 ;).

**Comment by poire-z** [comment]
Mhhhh.
So, in the wikipedia textbox, we blit the freetype glyphs (BB8 It seems) to the BB8 we made. And then, this BB8 panel is blitted to your RGB32 framebuffer.
The other texts may have the freetype glyphs directly blitted to your RGB32 framebuffer.
It's the only difference I can think of :|

And the coverbrowser list texts & images seem to be ok on your screenshots (except for the size on the right)...
Just to be sure: you get the same thing with the old Noto fonts ? :)

**Comment by NiLuJe** [comment]
Yup.

**Comment by NiLuJe** [comment]
I got the alpha thing under control via https://github.com/koreader/koreader-base/pull/676/commits/dcdcf4ae43cb7e512eb9002d2e857a6e830ed55d

I'm a bit mystified as to why that previously didn't work... My best guess is that the struct behaves like a pointer, and as such, we were updating it and not a locally scoped copy?
If that's true, I'm not sure if we *can* avoid either a cast or a copy in setPixelWhatever...

**Comment by poire-z** [comment]
Nice find :)
I guess it's indeed a reference to a single struct that gets its alpha updated here.
Looks like a bug in the original code:
```lua
function BB_mt.__index:setPixelColorize(x, y, mask, color)
    -- use 8bit grayscale pixel value as alpha for blitting
    local alpha = mask:getColor8().a
    -- fast path:
    if alpha == 0 then return end
    local px, py = self:getPhysicalCoordinates(x, y)
    if alpha == 0xFF then
        -- here, the unique color struct would still have the alpha set in one
        -- of the previous calls where in the else below
        -- so, I guess one should have done here too (or above, before the if):
        -- color.alpha = alpha
        self:getPixelP(px, py)[0]:set(color)
    else
        color.alpha = alpha
        self:getPixelP(px, py)[0]:blend(color)
    end
end
```

**Comment by NiLuJe** [comment]
Yep, it's been here since @hwhw wrote it, at a time were we didn't really commonly use devices w/ color fbs ;).

And it's only ever had a single caller all these years, and the issue is actually pretty sneaky to detect ;).

**Comment by poire-z** [comment]
>  I'm not sure if we can avoid either a cast or a copy in setPixelWhatever

May be reseting `color.alpha = alpha` is a tad more efficient (thus uglier) than allocating and freeing a `local fgcolor = color:getColorRGB32()` for each pixel?
Although there is one already done for each pixel with `local alpha = mask:getColor8().a`

**Comment by NiLuJe** [comment]
@poire-z : Yup, [that](https://github.com/koreader/koreader-base/pull/676/commits/77132e3593b30ef2987a12f832ed61bf4019f37c) works. Stores & set an u8 inside a struct instead of creating a full struct.

This looks slightly less stupid, if uglier, but I don't actually know if it's really faster ;).

**Comment by poire-z** [comment]
Oh, didn't notice your cover images were also wrong.
Any reason why we don't notice any problem with android or the emulator, which must also have a rgb32 framebuffer? Or .. what is BGR, or when is BGR involved?

**Comment by poire-z** [comment]
I remember I met https://github.com/koreader/koreader/issues/3274#issuecomment-333225593 with some BGR keyword involved. https://github.com/koreader/koreader-base/pull/523
