### ISSUE TITLE
Testers needed for new English UK and US hyph patterns

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3958]
* KOReader version: all
* Device: all

If one of you is about to read something in English (uk, us), here are two new hyph pattern files to replace the old pdb files. They were converted from Libreoffice. No need to adjust crengine to use them. Just unzipping the pack and dropping the three files (2 hyph and a custom json) in your .adds/koreader/data/hyph will do the trick. Don't forget to select in koreader's menu afterward as otherwise it should fallback to whatever file you defined to be the fallback.

Left and right min values are bot set to 2 ; these values could be override with koreader hyph menu. 

Feedbacks are welcome. It's ok If you don't see any change =) I use them for one month but as you may have noticed, errors in English don't pop at my eyes the way french do.

[hyph_en_uk_us.tar.gz](https://github.com/koreader/koreader/files/2030760/hyph_en_uk_us.tar.gz)

(corrected)

**Comment by dengste** [comment]
I'd like to try this, but I don't see any difference between your JSON file and the one from koreader. Are you sure this is correct? Also, it'd be nice to still have entries for the old pdb files so that one can still switch to them for comparison.

**Comment by cramoisi** [comment]
erf , will be corrected in 10 minutes

**Comment by cramoisi** [comment]
@dengste : I really need to clean my folders ! 

[hyph_en_uk_us.zip](https://github.com/koreader/koreader/files/2019237/hyph_en_uk_us.zip)

for the record, the new values are : 


```
    {
        "name": "English (UK)",
        "filename": "English_GB.pattern",
        "left_hyphen_min": 2,
        "right_hyphen_min": 2,
        "language": "en-GB",
        "aliases": ["en", "eng"]
    },
    {
        "name": "English (US)",
        "filename": "English_US.pattern",
        "left_hyphen_min": 2,
        "right_hyphen_min": 2,
        "language": "en-US",
        "aliases": ["en", "eng"]
    }
```

**Comment by cramoisi** [comment]
@dengste any feeback before I PR them ?
