### ISSUE TITLE
wikipedia save as epub inbox is shared with calibre wireless connection inbox

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3960]
* KOReader version: all (it seems)
* Device: all (it seems to)

Setting inbox for wikipedia save as epub file change the inbox for wireless calibre plugin. It should be a problem for people who separate them in different directories and there is no obvious way to change the inbox for wireless calibre plugin after setting it except to change the wikipedia option. More : if the wikipedia option has been set before, the wireless doesn't ask for a default inbox the first time it's used

**Comment by Frenzie** [comment]
Pinging @poire-z

**Comment by poire-z** [comment]
I don't know calibre, and I don't really understand the issue. By "inbox", you mean "folder" ?
Under which (possibly multiple?) settings in settings.reader.lua does that directory appear after you set it?
It should be saved under `wikipedia_save_dir`,  and I don't get how calibre could use that.

https://github.com/koreader/koreader/blob/68c1246575f0d95a75c3cd6d57a0aa7f5a2be81e/frontend/apps/reader/modules/readerwikipedia.lua#L194-L236

(these first comment lines seems a bit obsolete :| )

**Comment by cramoisi** [comment]
@poire-z : I don't know how, but when you have a "wikipedia_save_dir" set then after that  you connect for the first time with calibre wireless plugin, the "inbox_dir" is set to "/mnt/onboard/.hidden/Wikipedia (they are my own path, and this one I didn't do it myself)

**Comment by poire-z** [comment]
and if you restart koreader between these steps? (just in case it's some global variable or some pathchooser/downloadmgr attribute not re-initialized and re-used)

**Comment by KenMaltby** [comment]
I really appreciate having the option, on a per book/download basis, to set the download folder when using the OPDS feature.  When downloading books, that I may want in different folders based on their subjects, that ability is very handy.  If all Wiki articles/generated ebooks are to be kept in the same folder,  then such a feature would not be needed.  The option for selecting an other than the "current download folder" (the last one you used) needs to be in the message box to do the download.  For these Wiki articles you could have a Wiki folder as the default "Current folder".

**Comment by cramoisi** [comment]
When coming back from the office at 1PM, "I took a 15 minutes nap".. until now (it's 6.15 PM), so I guess I'll test it tomorrow  :-|
