### ISSUE TITLE
wikizero or VPN for Turkey

### ISSUE THREAD

**Issue by codex-hex** [koreader/koreader#3964]
* KOReader version:v2015.11.-1713-g32cb1a8_2018-05-15
* Device:Kobo Aura Edition 2

#### Issue
First, sorry for my bad english, I am from Turkey.Do you know Wikipedia is prohibited from my country?
We cannot access(dns queries and https traffic both).I need a vpn application(or ssh tunneling) for my Koreader to access wiki or a Wikizero soulution.
Turkish people use wikizero without any problem on their client devices (android or x86).İf you could support wikizeo on my Kobo device, it would be awesome and easy solution.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by codex-hex** [comment]
Adding only 0 to wikipedia link gives us to access from forbidden countries.
for example: 
https://en.wikipedia.org/wiki/Nvidia -> Can’t connect securely to this page
This might be because the site uses outdated or unsafe TLS security settings. If this keeps happening, try contacting the website’s owner.
when we add a zero, we are redirected wiki-zero
https://en.0wikipedia.org/wiki/Nvidia ->http://www.wiki-zero.net/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvTnZpZGlh

**Comment by cramoisi** [comment]
Isn't changing this line enough to do the trick ?

https://github.com/koreader/koreader/blob/113aefba2efc6167691477a27e016b85196aa267/frontend/ui/wikipedia.lua#L22

**Comment by Frenzie** [comment]
The way we retreive the info is using the API, e.g. like this:

```
https://en.wikipedia.org/w/api.php?action=query&titles=Main%20Page&prop=revisions&rvprop=content&format=json&formatversion=2
```

This isn't implemented in the 0wikipedia service. Instead of returning the expected API result it thinks you're asking for `https://en.wikipedia.org/wiki/Application_programming_interface` (or more specifically [here](http://www.wiki-zero.net/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvQXBpLnBocA)).

**Comment by codex-hex** [comment]
I understand the wiki-zero solution tha is not possible right now.
Could you support ssh connection interface to access standart wiki server over sock5 ssh tunnel?
By the way ,very thanks for your interest

**Comment by Frenzie** [comment]
I'm not sure if there's something like that in our current libraries that could be easily utilized.

**Comment by poire-z** [comment]
You may find many stuff (including ssh) build for Kobo devices by @NiLuJe at https://www.mobileread.com/forums/showthread.php?t=254214

btw, https://blog.wikimedia.org/2018/02/16/partnerships-new-approach/ says _The Wikipedia Zero program will end in 2018_ , dunno how that would affect your 0 url...

**Comment by NiLuJe** [comment]
Yeah, I have the full OpenSSH and dropbear suite in there.

It's in the process of being updated, here's a [prerelease build](http://files.ak-team.com/niluje/mrpub/Kobo/kobo-stuff-1.4.N-r14918.tar.xz) so you get stuff that isn't two years old ;).

**Comment by cramoisi** [comment]
>btw, https://blog.wikimedia.org/2018/02/16/partnerships-new-approach/ says The Wikipedia Zero program will end in 2018 , dunno how that would affect your 0 url...

@poire-z I read that too yesterday but I concluded (perhaps I'm wrong) it was not the same thing.

**Comment by cramoisi** [comment]
https://www.actualitte.com/article/monde-edition/wikimedia-appelle-la-turquie-a-lever-sa-censure/89018

**Comment by codex-hex** [comment]
does dropbear support ssh tunneling, ı couldnt find any information on the web?
ı am considering to access Wiki servers over tunnel.

**Comment by jzlcdh** [comment]
Everipedia has a very old copy of the English Wikipedia. If you change the above line to 

wiki_server = "https://everipedia.org/",

does it work and if not why not?

**Comment by Frenzie** [comment]
That site doesn't seem to offer the API either. See https://github.com/koreader/koreader/issues/3964#issuecomment-390467274

**Comment by Frenzie** [comment]
Since this unfortunately can't be solved unless one of the mirrors implements the API, I'm closing this now.
