### ISSUE TITLE
Cannot add extra button in file manager context menu

### ISSUE THREAD

**Issue by hfpop** [koreader/koreader#3969]
* KOReader version: last nightly
* Device: kobo aura one le

#### Issue

I am modifying the frontend/apps/filemanager/filemanager.lua file to add an extra button in the long-press-context-menu for files or folders in file manager.

If I add the button as the first one-line button, the whole thing crashes. If I add the button at the end, after the set-as-home-directory button, all is OK. 

This does not happen in KOReader for Kindle. 

##### `crash.log`

./luajit: plugins/coverbrowser.koplugin/covermenu.lua:213: attempt to index a nil value
stack traceback:
plugins/coverbrowser.koplugin/covermenu.lua:213: in function 'onFileHold'
frontend/ui/widget/filechooser.lua:331: in function 'onMenuHold'
plugins/coverbrowser.koplugin/listmenu.lua:675: in function 'handleEvent'
frontend/ui/widget/container/inputcontainer.lua:205: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
...
frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
frontend/ui/widget/container/widgetcontainer.lua:87: in function 'propagateEvent'
frontend/ui/widget/container/widgetcontainer.lua:105: in function 'handleEvent'
frontend/ui/uimanager.lua:454: in function 'sendEvent'
frontend/ui/uimanager.lua:149: in function '__default__'
frontend/ui/uimanager.lua:698: in function 'handleInputEvent'
frontend/ui/uimanager.lua:759: in function 'handleInput'
frontend/ui/uimanager.lua:803: in function 'run'
./reader.lua:195: in main chunk
[C]: at 0x00013fc5

**Comment by poire-z** [comment]
It should happen when you have the Mosaic or List display mode. May be you have one of these enabled on your kobo but not on your kindle?
These display modes are handled by a plugin, which hacks the thing you added a button to:
https://github.com/koreader/koreader/blob/07713be4299e15a1e52c091d25581cf52fd6ef38/plugins/coverbrowser.koplugin/covermenu.lua#L209-L213
If you added a button before the 4th row (a separator counts for a line) and the 3rd column, this `[4][3]` may not be correct and points to some other thing or nothing and causes a crash.
You may need to adjust that too. Try: `orig_buttons[5][3]`

**Comment by hfpop** [comment]
@poire-z Thank you very much indeed. This was my problem.

**Comment by hfpop** [comment]
@cramoisi I am using KOReader alternatively with the Kindle / Kobo reader programs. 

One option that I do miss on KOReader is playing with weight of the font. I mean, if the font is too bold (or not bold enough), I would like it weakened (or boldened) in degrees.

**Comment by cramoisi** [comment]
@hfpop indeed. I never use it because I've long time choose a font of my choice and edited it in fontforge to my liking (and since then I'm using it for every books I read)
