### ISSUE TITLE
KoReader Dont Start on Kobo Aura 2

### ISSUE THREAD

**Issue by laksenuoy** [koreader/koreader#3971]
* KOReader version: koreader-kobo-arm-linux-gnueabihf-v2015.11-stable
* Device: Kobo Aura 2

#### Problem
KoReader does not open then return to KSM 09

##### `crash.log`
./luajit: frontend / device / kobo / device.lua: 177: unrecognized Kobo model star
stack traceback:
[C]: in the function 'error'
frontend / device / kobo / device.lua: 177: in the main song
[C]: in the 'probeDevice' function
frontend / device.lua: in the main song
[C]: in the 'require' function
frontend / ui / uimanager.lua: 1: in the main song
[C]: in the 'require' function
./reader.lua:92: in the main track
[C]: 0x0000bea5

**Comment by NiLuJe** [comment]
Perfectly normal given the age of the release you're using.

Use a current nightly/beta (c.f., the [wiki](https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices) recommendations).
