### ISSUE TITLE
Can't inline <code>

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#3974]
* KOReader version: v2015.11-1708-gc0e8046_2018-05-13
* Device: Kobo Glo HD

#### Issue
By default, in epubs, crengine displays text wrapped in `<code></code>` tags as a separate block with line breaks before and after it (See similar issue with `cite`: [#3940](https://github.com/koreader/koreader/issues/3940).
I attempted to fix this by creating a user styletweak with the following css:
```css
code { display: inline !important; }
```
When turned on, this tweak causes it to render the code element without a line break before it. However, it still puts  a line break after the code element.

**Comment by cramoisi** [comment]
@Thra11 : if the epub css contains some other styles for `code`, they will be used, could you check or send over the book ?

**Comment by poire-z** [comment]
> if the epub css contains some other styles for code, they will be used

Indeed. Check with toggling `Embedded styles` off/on.
And nowhere in the code or the shipped styles `<code>` is defined as other than inline. And it's defined with an additional property: `white-space: pre;` (which I guess that if you have a `\n</code>`, it could behave as you describe.
Check with this sample epub: [test-code.epub.zip](https://github.com/koreader/koreader/files/2033965/test-code.epub.zip)

There is an issue thus: it's ok (as you expect it) if you select `Style > htm.css` (displayed inline with monospace font), but not with `Style > epub.css` (displayed inline with the normal font).

**Comment by poire-z** [comment]
It's strange, but all other .css except epub.css have this declaration:
```css
code, pre {
   white-space: pre;
   text-align: left;
   font-family: "Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono", monospace;
   }
```
the display and white-space are hardcoded elsewhere, but the `font-family` is not, and I guess it's that which says it should use Droid Sans Mono to render it with a monospace font.
It was removed in this big shuffling https://github.com/koreader/crengine/commit/3c14c01485a0dfa5c7404bf1df51fe70247e10c8#diff-dee5d3310391925b25b367ee77ea695c
I guess we should add it back to epub.css, unless I miss something.

**Comment by cramoisi** [comment]
@poire-z : yup, this make no sense to not have it there. (but why "Liberation mono" and "dejavu sans mono" since only droid is included in koreader/fonts ?)

**Comment by poire-z** [comment]
Because we inherited all that from cool reader (and its history of changes): https://github.com/koreader/crengine/commits/master/cr3gui/data/epub.css
And we made only small updates. Sometimes, I think it would need a whole cleanup, but there's some specific stuff that may be apply to some particular books from some specific source that are useful to some poeple.

**Comment by Frenzie** [comment]
> I guess we should add it back to epub.css, unless I miss something.

Monospace is probably clearer, I agree.

**Comment by cramoisi** [comment]
@poire-z, @Frenzie  I vaguely remember something about the courier font but can't pin it ; the font is used in a lot of css declaration in c3qt/data so shouldn't be included in the fonts directory ?

**Comment by cramoisi** [comment]
in fact it looks like the epub.css in c3gui/data is the epub.css in c3qt/data, where are all css are courier, monospace

**Comment by poire-z** [comment]
We don't use any stuff from cr3qt/data (guess that's for cool reader QT port).
We only use stuff from the library code in crengine/crengine (or I mostly just look at that part), and the css in cr3gui/data/ (which are different from those from cr3qt/data).
The only trace of Courier in the code we use is in the initial stylesheet (that is overriden by the other style):
https://github.com/koreader/crengine/blob/d429de2b1d8468127839228f2d46e2230b65e96d/crengine/src/lvdocview.cpp#L85

On cr3gui/data/, all except epub.css have:
font-family: "Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono", monospace;

**Comment by cramoisi** [comment]
added (I needed some training with git / github cli)

**Comment by Thra11** [comment]
Turning embedded styles on or off has no effect on the issue. The only relevant bit of embedded css I can see is this:
```css
.code {
    font-family: monospace;
    font-size: 1em
}
```

However, I don't see the same issue with @poire-z 's test-code.epub, which inlines the code correctly, with the paragraph continuing on the same line.

I will experiment with the original epub and the test epub and see if I can work out what's causing the inlining issue.

I am also able to reproduce the separate issue where the epub css doesn't use a monospace font for the code, but it sounds like that's now well understood and being fixed.

**Comment by poire-z** [comment]
OK, that's the class named `.code` that is the problem, and we just discussed it earlier at https://github.com/koreader/crengine/pull/191#issuecomment-391632167
The fact that you have bits of HTML with a class="code" make it be handled by https://github.com/koreader/crengine/blob/d429de2b1d8468127839228f2d46e2230b65e96d/cr3gui/data/epub.css#L102-L110 , so just like a PRE.
So, your case is an encouragement to go remove all the class names in that epub.css.

In the meantime, in your user tweak, use:
```css
code { display: inline !important; font-family: "Droid Sans Mono"; }
.code { display: inline !important; font-family: "Droid Sans Mono"; }
```

**Comment by Thra11** [comment]
Ah, that fixes it! Thanks for your help!
