### ISSUE TITLE
Pocketbook 626+ not connect to wi-fi

### ISSUE THREAD

**Issue by dorianleven** [koreader/koreader#3975]
* KOReader version:v2015.11-1724-g07713be_2018-05-21
* Device: Pocketbook 626+

#### Issue
Koreader not coneting to wi-fi.

#### Steps to reproduce
Using Dictationary or network settings.

**Comment by ersi-dnd** [comment]
I have owned a few Pocketbooks. Koreader never manages to create a connection to wifi on Pocketbook. 

On Pocketbook, Koreader is situated in the Pocketbook environment, as distinguished from Kobo where Koreader is placed in KSM, an environment separate from Kobo. Koreader is evidently not built to override Pocketbook's environment when it comes to wifi.

**Comment by Frenzie** [comment]
Closing in favor of #4747.
