### ISSUE TITLE
feature request: temporarily disable/enable touch with hardware button

### ISSUE THREAD

**Issue by silberzwiebel** [koreader/koreader#3978]
* KOReader version: koreader-beta-20180412
* Device: inkbook prime (android 4.2)

#### Feature Request

In its own reader app, the inkbook prime has a wonderful option: Pressing a (configurable) hardware button (the device has four), disables the whole touch screen. This allows to hold the device anywhere without having the fear of turning pages. Pressing the key again enables the touch again.

Since I personally think that touch screens are one of the worst invention ever (mouse & keyboard are *much* superior), I like to disable touch as often as I can.

I thought of implementing this disable-touch-key into koreader but I'm lacking lua skills and, possibly more relevant, time. This is why I open this feature request. Possibly someone wants to implement this useful feature (as a plugin?)?

**Comment by Frenzie** [comment]
It could potentially be as simple as registering a touch event adjust hook that discards everything.

**Comment by gerroon** [comment]
Please do not disable this by default on Inkbook.

**Comment by Frenzie** [comment]
KOReader is for touch devices; that'd make little sense. ;)

**Comment by gerroon** [comment]
I personally would like to disable the touch sometimes, but not all times :)

**Comment by silberzwiebel** [comment]
> I personally would like to disable the touch sometimes, but not all times :)
> 

That's exactly the use case. :) I updated the issue title.

**Comment by Frenzie** [comment]
Btw @silberzwiebel you never said anything about the keycodes involved here by default.

**Comment by silberzwiebel** [comment]
That's true, thanks for reminding. Some time ago, I implemented this feature in [wallabag's android app over here](https://github.com/wallabag/android-app/pull/635) (flavored by @di72nn with the [ability to change the keycode](https://github.com/wallabag/android-app/commit/8e8313b0bc74b0dc815f75a66152f2e2e46e2055)) and the inkbook's default keycode for blocking touch input is the `KEYCODE_CAMERA` (but it can be changed to another keycode, I think the inkbook provides at least `PAGE_UP, PAGE_DOWN` and maybe `VOLUME_UP, VOLUME_DOWN`).

**Comment by pazos** [comment]
@silberzwiebel: If you're still interested we can make a first version hardcoding the behaviour to KEYCODE_CAMERA (and providing a menu to enable/disable this feature).

If we want to make the keycode switchable we need to look a bit which is the best option, since we cannot map key events directly, but with a middle layer of indirection, see https://github.com/koreader/koreader/blob/master/frontend/device/android/event_map.lua

**Comment by silberzwiebel** [comment]
That sounds great! Actually, I finished reading PDF articles in the last week for the foreseeable future, so I probably won't use koreader much in the months to come. I'd love to see this feature anyway ;)

`KEYCODE_CAMERA` should be fine for the first implementation. For making this switchable: Maybe a text config file is good enough and relatively easy to implement?

Happy to test!

**Comment by pazos** [comment]
In the same vein of #5158 we can make a little change to make this work:

### base diff

```diff
diff --git a/ffi/input_android.lua b/ffi/input_android.lua
index 8a15c17..8cc596c 100644
--- a/ffi/input_android.lua
+++ b/ffi/input_android.lua
@@ -58,6 +58,9 @@ end
 
 local is_in_touch = false
 local function motionEventHandler(motion_event)
+    if android.getTouchscreenIgnored() then
+        return
+    end
     local action = android.lib.AMotionEvent_getAction(motion_event)
     local pointer_count = android.lib.AMotionEvent_getPointerCount(motion_event)
     local pointer_index = bit.rshift(
@@ -102,6 +105,10 @@ local function keyEventHandler(key_event)
     or code == C.AKEYCODE_MEDIA_REWIND
     or code == C.AKEYCODE_MEDIA_FAST_FORWARD then
         return 0 -- event not consumed
+    elseif code == C.AKEYCODE_CAMERA
+    and action == C.AKEY_EVENT_ACTION_UP then
+        android.setTouchscreenIgnored()
+        return 1 -- event consumed
     end
     if action == C.AKEY_EVENT_ACTION_DOWN then
         genEmuEvent(C.EV_KEY, code, 1)
```
### luajit-launcher diff

```diff
diff --git a/assets/android.lua b/assets/android.lua
index 2fe6935..dcb0783 100644
--- a/assets/android.lua
+++ b/assets/android.lua
@@ -1429,6 +1429,26 @@ local function run(android_app_state)
         end)
     end
 
+    android.getTouchscreenIgnored = function()
+        return JNI:context(android.app.activity.vm, function(JNI)
+            return JNI:callIntMethod(
+                android.app.activity.clazz,
+                "getTouchscreenIgnored",
+                "()I"
+            ) == 1
+        end)
+    end
+
+    android.setTouchscreenIgnored = function()
+        JNI:context(android.app.activity.vm, function(JNI)
+            JNI:callVoidMethod(
+                android.app.activity.clazz,
+                "setTouchscreenIgnored",
+                "()V"
+            )
+        end)
+    end
+
     -- properties that don't change during the execution of the program.
     android.prop = {}
 
diff --git a/launcher/src/org/koreader/launcher/MainActivity.java b/launcher/src/org/koreader/launcher/MainActivity.java
index 7d193ef..7ff10bb 100644
--- a/launcher/src/org/koreader/launcher/MainActivity.java
+++ b/launcher/src/org/koreader/launcher/MainActivity.java
@@ -48,6 +48,7 @@ public class MainActivity extends android.app.NativeActivity implements SurfaceH
     // size in pixels of the top notch, if any
     private int notch_height = 0;
 
+    private boolean touchscreen_ignored = false;
     private boolean volume_keys_ignored = false;
 
     /* Called when the activity is first created. */
@@ -269,10 +270,19 @@ public class MainActivity extends android.app.NativeActivity implements SurfaceH
     }
 
     /* input */
+    public int getTouchscreenIgnored() {
+        return touchscreen_ignored ? 1 : 0;
+    }
+
     public int getVolumeKeysIgnored() {
         return volume_keys_ignored ? 1 : 0;
     }
 
+    public void setTouchscreenIgnored() {
+        touchscreen_ignored = !touchscreen_ignored;
+        showToast("Touchscreen: " + Boolean.toString(!touchscreen_ignored));
+    }
+
     public void setVolumeKeysIgnored(boolean ignored) {
         volume_keys_ignored = ignored;
     }
```

The only downside I got is that the toast text is hardcoded to english. I'm not entirely sure if koreader-base supports translation or what is the proper approach to have the text translated.

**Comment by Frenzie** [comment]
base doesn't really. You'd probably best pass along the string with a get/setTouchscreenIgnoredMessage or something? Slightly convoluted but I'm not really sure how else to maintain the architectural separation.

**Comment by pazos** [comment]
> You'd probably best pass along the string with a get/setTouchscreenIgnoredMessage or something?

@Frenzie The problem is that android-luajit-launcher isn't localized. The only solution I found is to propagate the event to the frontend and react there with:

```diff
diff --git a/frontend/device/android/event_map.lua b/frontend/device/android/event_map.lua
index f15164a0..4cdf34a3 100644
--- a/frontend/device/android/event_map.lua
+++ b/frontend/device/android/event_map.lua
@@ -14,6 +14,7 @@ return {
     [23] = "Press", -- DPAD_CENTER
     [24] = "LPgBack", -- VOLUME_UP
     [25] = "LPgFwd",  -- VOLUME_DOWN
+    [27] = "Camera",  -- CAMERA
     [56] = ".",     -- PERIOD
     [59] = "Shift", -- SHIFT_LEFT
     [60] = "Shift", -- SHIFT_RIGHT
diff --git a/frontend/device/input.lua b/frontend/device/input.lua
index 089293b0..119deaec 100755
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -322,6 +322,23 @@ function Input:handleKeyBoardEv(ev)
         return keycode
     end
 
+    -- The hardware camera button is used in Android to toggle the touchscreen
+    if keycode == "Camera" and ev.value == EVENT_VALUE_KEY_RELEASE then
+        local isAndroid, android = pcall(require, "android")
+        if isAndroid then
+            local notification = nil
+            local new_state = not android.getTouchscreenIgnored()
+            if new_state then
+                notification = _("Touchscreen disabled")
+            else
+                notification = _("Touchscreen enabled")
+            end
+            android.setTouchscreenIgnored()
+            android.notification(notification)
+        end
+        return
+    end
+
     if keycode == "Power" then
         -- Kobo generates Power keycode only, we need to decide whether it's
         -- power-on or power-off ourselves.
```

For me it looks a bit hacky but works the same way.

**Comment by Frenzie** [comment]
Sure, but I meant setting/overriding the text of the relevant string, akin to https://github.com/koreader/koreader/blob/e2961097e7b054d97928b6d188353335372b0db6/frontend/ui/data/strings.lua

That would be done in device init.

I'm not really sure to what extent the ignoring business belongs in base though (which I see more as facilitating such functionality) so that's more of a clarification, not an objection.

**Comment by pazos** [comment]
> Sure, but I meant setting/overriding the text of the relevant string, akin to https://github.com/koreader/koreader/blob/e2961097e7b054d97928b6d188353335372b0db6/frontend/ui/data/strings.lua

> That would be done in device init.

Sorry but I still don't get it :cry: 

> I'm not really sure to what extent the ignoring business belongs in base though (which I see more as facilitating such functionality) so that's more of a clarification, not an objection.

I tried moving the `if android.getTouchscreenIgnored() then return end` to the `Input:handleTouchEv(ev)` function and still works but looks even hackier.

I tried to add a new hook for android devices: it works nice but requires a restart and somewhat goes against the spirit of the thing (touchscreen should be enabled by default and turned of temporarily when the user wants, we shouldn't store touchscreen state as a permanent setting and restore it on device init).

I think I will submit PRs and we can move the conversation there. I'm sure there are better ways of doing this but I cannot figure out which ones.

**Comment by Frenzie** [comment]
In this diff it's hard-coded.
```diff 
+    public void setTouchscreenIgnored() {
+        touchscreen_ignored = !touchscreen_ignored;
+        showToast("Touchscreen: " + Boolean.toString(!touchscreen_ignored));
+    }
```

That's easily avoided with a simple var of some sort (obviously ;-) ):

```diff 
+    public void setTouchscreenIgnored() {
+        touchscreen_ignored = !touchscreen_ignored;
+        showToast(String.format(translated_string_loaded_by_front_on_init, Boolean.toString(!touchscreen_ignored));
+    }
```

I think there should be no need to do any translation with luajit-launcher, which would just complicate matters. It just needs to facilitate setting a few strings through a class or something.

So then we use something along these lines:

```java
List<AwesomeStrings> stringies = new ArrayList<AwesomeStrings>();
// load 'em up
// and then use 'em
stringies.get(0).touchscreen_disabled;
```

Only in my first message I proposed doing that for one or two highly specific strings and this would be the more generic way. Unless I'm overlooking something here.

**Comment by pazos** [comment]
@silberzwiebel: done, please inform if something doesn't work as expected!

**Comment by silberzwiebel** [comment]
Fantastic, thanks very much! I'll wait until the next release and report back then!

**Comment by silberzwiebel** [comment]
It works great, thanks! One possible improvement would be to document that feature somewhere for users. I knew it's there but couldn't find any information about it (and then I just pressed the button and it worked). Maybe this documentation could go together with a possibility to change the keycode that triggers the deactivation of the touchscreen?

**Comment by pazos** [comment]
> One possible improvement would be to document that feature somewhere for users.[...] Maybe this documentation could go together with a possibility to change the keycode that triggers the deactivation of the touchscreen?

Sure, please document or improve as you like.

Some things to keep in mind:

1. Any event that reaches KOReader [mapped as a "Camera" event](https://github.com/koreader/koreader/blob/master/frontend/device/android/event_map.lua#L17) will do the same job.
2. Some key events never reach KOReader as [they are forwarded to the media server](https://github.com/koreader/koreader-base/blob/master/ffi/input_android.lua#L101-L107)
3. There is no easy way to detect which device has a specific set of keys.
4. Most devices don't have any hardware key available.
5. Back key shouldn't be mapped as "Camera".

So the hw keys available to behave as touchscreen toggle are: Page Up/Down, Volume Up/Down and Camera. Volume up/down will work as long as the user ticks the "turn pages with volume keys" under settings->navigation. The others will work always.

You probably need to make the event map dynamic based on user preferences. Please ping me if you have some specific question about the implementation :+1:

**Comment by silberzwiebel** [comment]
Thanks for the detailed advice! Just to let you and other interested people know: I won't be able to implement this in the foreseeable future.

**Comment by xahon** [comment]
And how to do that?

**Comment by pazos** [comment]
> And how to do that?

WIth an android device that has a physical "camera" button. Or remapping any key as a "camera" button. See https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys
