### ISSUE TITLE
Instalacion without usb connection (Solved)

### ISSUE THREAD

**Issue by Nanco300** [koreader/koreader#3982]
It is possible upgrade Koreader v2015.11-stable to v2018.04.12-beta without usb connection?

**Comment by Frenzie** [comment]
Probably, but on what device?

**Comment by Nanco300** [comment]
Kobo Glo 3.18.0 and I have a memory styck.

**Comment by cramoisi** [comment]
hi @Nanco300  : you don't have a usb connection because your usb is broken ?
If it's the case (and you still have a computer to plug a microsd card to, you can follow the directions given recently on mobileread : 

 https://www.mobileread.com/forums/showpost.php?p=3694364&postcount=250

**Comment by KenMaltby** [comment]
How do you recharge the battery?  Can you use OTA, does the WiFi work?

**Comment by KenMaltby** [comment]
You can move things between the internal user partition and the external SD card using the File Manager utility that comes with the Pbchess Launcher.

**Comment by cramoisi** [comment]
@Nanco300 : check your usb/micro usb cable, and if you didn't, try a "kobo" usb cable. I got a lot of usb/mirco-usb cables from various manufacturers and (I don't know why) a lot of them don't do well with the glo/aura I got at house when still they perform correctly with other devices.

**Comment by Nanco300** [comment]
@cramoisi I tested many cables, but none works

I did like to know if is possible upgrade Kobo Start Menu without uninstall the previous version? What if the current version of the Kobo Start Menu works with the firmware Kobo 3.18.0?

**Comment by Nanco300** [comment]
I did get install the Koreader, but I broken the  power button, however  I am using a magnet for control the suspension.

Thank you all.

**Comment by cramoisi** [comment]
@Nanco300 :-(  : in the article I linked did you read that : 
> Several people have broken the power button when opening/closing the Glo. So be careful.

(because now I feel quite guilty that I haven't saying it again here)

**Comment by Nanco300** [comment]
@cramoisi The fault was my. But I suggest that you include this information on top the article.
