### ISSUE TITLE
Sort by last read doesn't work

### ISSUE THREAD

**Issue by alethiophile** [koreader/koreader#3988]
* KOReader version: v2015.11-1654-g666c9f1_2018-04-12
* Device: Kobo Aura

#### Issue
When "sort by last read date" is selected in the file manager, items are instead sorted in a seemingly arbitrary order that doesn't change as you open books.

This may be related to the fact that the file atimes aren't updated properly; the displayed order seems to be consistent with the atimes, but these seem to be rounded to the nearest midnight UTC, or something.

The device does know reading order; when the History view is opened, files are correctly displayed in reverse order of last reading.

#### Steps to reproduce
1. Put more than one ebook in a directory
2. Select last read order
3. Open various ebook files, watch the order not reflect it

**Comment by NiLuJe** [comment]
Random question: is the date / time sane on said device?

**Comment by alethiophile** [comment]
The date and time displayed are correct. I have no idea what the situation with time zone settings is (I haven't been able to get SSH access).

**Comment by alethiophile** [comment]
Looking at the situation, it appears the last-read sort mode sorts by access time, but the `/dev/onboard` mount on the Kobo is mounted with `noatime` and `nodiratime`. Thus, it can't be expected to work.

That sort mode should probably be changed to use whatever the history view uses.

**Comment by alethiophile** [comment]
Another option would be to make the reader do an explicit `touch -a filename` (or equivalent) at the same time that it updates the history; this might be a smaller change.

**Comment by cramoisi** [comment]
@alethiophile so you said your file are on an microsd inside the external slot ?

**Comment by alethiophile** [comment]
I've got whatever kind of Kobo Aura it is that doesn't have an
external slot. The files are on /mnt/onboard, which is a separate
filesystem from / and seems to be an internal flash device.

**Comment by alethiophile** [comment]
It looks like "date added" sorts by inode change time (ctime), "date
modified" sorts by file modification time (mtime), and "last read"
sorts by atime as discussed. These are kind of weird decisions; ctime
is basically equivalent to mtime here, so "date added" is just
incorrect (maybe stemming from the common misreading of "ctime" as
"creation time" rather than "change time"), and atime is of course
meaningless (or at least doesn't mean what you think) on a
noatime-mounted partition.

If you really wanted to sort by date added, you'd need to keep records
separately; that information isn't tracked by (and can't reliably be
tracked by) the inode metadata. Meanwhile, the only operations that
count as "modifications" are basically writing over the ebook file
with another, and I'm not sure how you'd make a principled distinction
between that and adding it new.
