### ISSUE TITLE
Issue On Kobo N905c Touch Crash On When Login Evernote

### ISSUE THREAD

**Issue by Jerry-Chow** [koreader/koreader#3991]
* KOReader version: v2015.11-1564-gbfd55c7_2018-03-13
* Device: Kobo_trylogy

#### Steps to reproduce
 Crash On When Login Evernote

##### `crash.log` (if applicable)
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/31/18-17:08:38
 [*] Version: v2015.11-1564-gbfd55c7_2018-03-13

05/31/18-17:08:39 INFO  initializing for device Kobo_trilogy
05/31/18-17:08:39 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 600
}
[ko-input] Forked off fake event generator(pid:1012).
05/31/18-17:08:41 INFO  Loading plugins from directory: plugins
05/31/18-17:08:41 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
05/31/18-17:08:41 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
05/31/18-17:08:41 INFO  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
05/31/18-17:08:41 INFO  FM loaded plugin AutoSuspend at plugins/autosuspend.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin perception_expander at plugins/perceptionexpander.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
05/31/18-17:08:41 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
05/31/18-17:08:49 INFO  opening file /mnt/onboard/Books/C#高级编程（中文第七版）_文字版.pdf
05/31/18-17:08:49 INFO  RD loaded plugin AutoSuspend at plugins/autosuspend.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin perception_expander at plugins/perceptionexpander.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
05/31/18-17:08:49 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
05/31/18-17:08:49 INFO  setting zoom mode to contentwidth
source page (0,0) - (412,667)
source page bgcolor 192
warning: non-embedded font using identity encoding: FZDHTJW--GB1-0
source page (0,0) - (435,667)
source page bgcolor 192
source page (0,0) - (438,667)
source page bgcolor 192
udhcpc (v1.22.0.kobo) started
Sending discover...
Sending select for 172.20.10.7...
Lease of 172.20.10.7 obtained, lease time 85536
adding dns 172.20.10.2
./luajit: error loading module 'libluabpack' from file 'plugins/evernote.koplugin/lib/libluabpack.so':
	liblualongnumber.so: cannot open shared object file: No such file or directory
stack traceback:
	[C]: at 0x0004d2e1
	[C]: in function 'require'
	plugins/evernote.koplugin/thrift/TBinaryProtocol.lua:21: in main chunk
	[C]: in function 'require'
	plugins/evernote.koplugin/EvernoteClient.lua:2: in main chunk
	[C]: in function 'require'
	plugins/evernote.koplugin/main.lua:234: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:204: in function 'action'
	frontend/ui/uimanager.lua:531: in function '_checkTasks'
	frontend/ui/uimanager.lua:703: in function 'handleInput'
	frontend/ui/uimanager.lua:789: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x00013fc5

**Comment by cramoisi** [comment]
hi @Jerry-Chow : just to be sure : are the files mentioned in your log present your koreader/plugins/evernote.koplugin/lib folder device ?
`libluapack.so`
`liblualongnumber.so`

**Comment by Jerry-Chow** [comment]
@Frenzie Thank U Very much,it works.
And BTW,if I want to customize some feature by my self ,how should i start .

**Comment by NiLuJe** [comment]
@Frenzie : I only have an H2O, so I'd imagine I'd reproduce the exact same thing as #3600 ;).

It might not be seen on Kindles because the Kindle FW ships a copy of Lua? (wild guess, how Lua handles searching for stuff breaks my brain :D).
