### ISSUE TITLE
[question] about title in the full status bar

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#3994]
* KOReader version: all
* Device: all

(from mobileread)

Do you know if there is a possibility to change the size of the font when using a full status bar (where the title dwelt). 

I spot a `crengine.page.header.font.size=22 ` in cr3.ini but changing the value doesn't do anything on the emu even if it seems to deal with it.

https://github.com/koreader/crengine/blob/ac7470a3bc230e6e934125d1f5681f51d8961729/crengine/src/lvdocview.cpp#L3156-L3163

**Comment by poire-z** [comment]
That setting in cr3.ini seems indeed not to be used, and I don't really know how that cr3.ini works, or why it works for some and not for others.
A quick and easy way to have it applied is to do it from koreader, for example with:
```lua
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -124,6 +124,10 @@ function CreDocument:init()
     -- adjust font sizes according to screen dpi
     self._document:adjustFontSizes(Screen:getDPI())

+    if G_reader_settings:readSetting("cre_status_font_size") then
+        self._document:setIntProperty("crengine.page.header.font.size", G_reader_settings:readSetting("cre_status_font_size"))
+    end
+
     -- set fallback font face
     self._document:setStringProperty("crengine.font.fallback.face",
         G_reader_settings:readSetting("fallback_font") or self.fallback_font)
```
so one could add to its `settings.reader.lua`:  `["cre_status_font_size"] = 40,`

(But who still wants that ugly top bar when we have a super configurable super nice bottom minibar? :)

**Comment by cramoisi** [comment]
@poire-z not me ; I was just passing through a question from mobileread : https://www.mobileread.com/forums/showthread.php?t=297545

But now you speak of it ; it would be a delight to have "title : chapter" display option in the minibar (but probably wouldn't use it anyway)

**Comment by cramoisi** [comment]
it's closed then. @poire-z https://www.mobileread.com/forums/showthread.php?t=297932 (as I know you like robert dict)

**Comment by poire-z** [comment]
I'll probably stick the above setting in a futur PR, so it's just there for people who'd like that.
I spent enough time tweaking the Robert 2003 and 2010 that I don't feel like doing that again on some new dict :)
But if you post a screenshot of what you get for, let's say the word `lecteur`,  I can compare and see if the adventure is worth it :)

**Comment by cramoisi** [comment]
for now it's quite nothing I have yet to make some css functional =-) But as it's intended for nickel the thing is quite "simple" bot much more than ol , li, b and i

**Comment by KenMaltby** [comment]
"cre_status_font_size" doesn't sound like it would be for the "Full" Progress bar setting resulting display at the top of each page.  Is it a cre3 thing?

**Comment by cramoisi** [comment]
@KenMaltby : yup, this bar is a cr3 thing.

**Comment by cramoisi** [comment]
@poire-z : just to say : tested and working.

**Comment by poire-z** [comment]
So, any better name for this hidden setting?
```
cre_status_font_size
cre_header_font_size
cre_header_status_font_size
full_status_bar_font_size
```
It's just to set the internal crengine setting name `crengine.page.header.font.size`

**Comment by cramoisi** [comment]
one of these two ? (mostly because they are the most explicit ) : 

```
cre_header_status_font_size
full_status_bar_font_size
```

**Comment by cramoisi** [comment]
![reader_2018-jun-05_112449](https://user-images.githubusercontent.com/28014131/40967724-15b04138-68b4-11e8-89d4-aeb00ddcd670.png)

@poire-z

**Comment by poire-z** [comment]
A bit stripped down from those I have:
![image](https://user-images.githubusercontent.com/24273478/40971585-6c539c24-68be-11e8-99a4-83d47204503d.png)
![image](https://user-images.githubusercontent.com/24273478/40971810-17e1a036-68bf-11e8-8584-28f9f18f3bd0.png)
(See https://github.com/koreader/koreader/pull/3585 for the lua function trick to parse & tweak a HTML dict output with lua code.)

**Comment by cramoisi** [comment]
Yup, I compared too. Hence the "micro" in the title :)

**Comment by cramoisi** [comment]
This is what if got from my converted amazon robert-dixel to stardict : 

![reader_2018-jun-05_130802](https://user-images.githubusercontent.com/28014131/40972757-0d486666-68c2-11e8-9ec6-7a3c6c8ecf91.png)

**Comment by poire-z** [comment]
I remember I used penelope 3.1.3, with some modifications of mine, to ignore duplicates and deal with title words like "Travail, -aux", and may be some stuff with synonyms (it's quite old, and I don't want to put back my nose in it :) Sharing these modifications in case it may help you: [penelope-3.1.3my.patch.txt](https://github.com/koreader/koreader/files/2072167/penelope-3.1.3my.patch.txt)

**Comment by cramoisi** [comment]
great ! till now I used a serie of regexp for making a new line with the feminine form (or the synonym) and the definition (the same as the principal form). It does the trick but it's quite redundant.

**Comment by KenMaltby** [comment]
I guess cre3's use of the "Status" line term, could be a nod to the Android page design, where there is an info/menu bar at the top of every page.  That could be looked at as a "Status" line.  For within KOReader's UI, I like the "page header" term better.

**Comment by poire-z** [comment]
Can now be changed by manually adding to settings.reader.lua something like:
`["cre_header_status_font_size"] = 60,`
