### ISSUE TITLE
characters of the title of the books

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#3995]
* KOReader version: all versions
* Device: kobo aura one

#### Issue
Hello,
In the upper mini bar, which contains the title of the book, the state of the battery ... the size of the characters is very small (1mm on aura one) .I did not find the corresponding line in the file defaults.lua
Is there a way to increase the font of this top bar?
Regards,

**Comment by cramoisi** [comment]
@davicraquette I already asked and had a response there  : 

https://github.com/koreader/koreader/issues/3994

**Comment by poire-z** [comment]
@davicraquette 
This will work with a koreader named with something equal or higher than `v2015.11-1736` (so, starting from tomorrow's nightly build).
You should be able, to change the font size by manually adding to `koredar/settings.reader.lua` something like:
`["cre_header_status_font_size"] = 60,`
(make a backup of that file, dont'd add that line at the end, add it just under a similar simple setting, don't forget the virgule at the end)
