### ISSUE TITLE
Enhancement suggestions to Table of Contents 

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#3997]
I tried a search. Hopefully this is not a duplicate.

**Idea no. 1:** TOC is just a waste of time when it shows up empty. Is there a way for the TOC to recognise that it has nothing to show and then just not show up even though the user happens to hit it in the menu? (Pocketbook's TOC actually functions this way: If nothing to show, do nothing.)

**Idea no. 2:** When the file offers no TOC, perhaps Koreader can generate a TOC? For epubs, the generation could occur based on heading elements. For pdfs, perhaps simply list all pages, providing yet another way to navigate.

Koreader could generate a TOC from the file when the user triggers or requests a TOC to be generated. For example, right now we are often enough presented with an empty TOC. Instead of being empty, it could show options: 
- Generate an auto-TOC from the file
- Never show empty TOC's again

Edit: And hi to Microsoft at the top edge.

**Comment by poire-z** [comment]
> Idea no. 2: When the file offers no TOC, perhaps Koreader can generate a TOC? For epubs, the generation could occur based on heading elements

Nice idea! I've been living with empty or nearly empty TOC for so long, and I never ever had the thought we could build a TOC from headings :) crengine will be able to do that for EPUBs with https://github.com/koreader/crengine/pull/205

This shouldn't be only available when the TOC is empty. Sometimes, the TOC has only 1 or 2 items, and on some books the TOC has a only a subset of the top level headings, so this alternative TOC can be useful in other cases.
I'm going with having it toggable with long-press on the Table of content menu.

About your other ideas and requests about TOC, Bookmarks and History, there's the thing that all these are some kind of simple overlay over the book or the filemanager: they use some simple code to show a list of things, with no additional button and no top menu (the top menu infrastructure is huge, and only set up for the 2 main "applications": reader and file manager) with the benefit of not having to close the thing under: book or filemanager. Adding what you wish for would be a huge work and involve some big refactoring.

**Comment by ersi-dnd** [comment]
Good that at least one little point of mine hit the mark.

An additional idea I got meanwhile: It should be possible to erase/ hide an undesirable TOC, regardless if generated by Koreader or pre-existing. Some pdf files in particular tend to offer every page as a TOC item and it would be nice to remove it to cleanse the progress bar.

**Comment by robert00s** [comment]
This is done in #4011 by @poire-z

**Comment by poire-z** [comment]
Idea 1 discussed in https://github.com/koreader/koreader/issues/3526#issuecomment-421552322 , but closing TOC has been made easier with #4237.
Idea 2 implemented in #4011.
So, closing.
