### ISSUE TITLE
Enhancement to keyboard layout system

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#3998]
Ability to keep adding layouts indefinitely is a must for users who read in many languages. Looks like the current keyboard layout system cannot do it. Correct me if I am wrong.

When reading in many languages, the user may require several dictionaries and keep adding them as needed to no upper limit. Similarly to search inside books of any arbitrary language or to perform searches in the file browser for filenames/metadata in any arbitrary language (think different alphabets like Cyrillic, Greek, Armenian, Hebrew, Arabic, Ethiopian, Chinese...). 

The keyboard layout cannot be tied to the app interface language. These things are completely unrelated. There should be no limit to the number of possible layouts. Start with a few, yes, but the user should be able to keep adding them as needed without losing the first ones.

**Comment by Biep** [comment]
Another thing I'd like a lot is keyboard gestures.  Starting on a vowel and moving NW would give it an acute accent, and moving NE a grave accent.  Long pressing a key would surround it with the eight symbols associated with the eight main directions - and those symbols should be clickable.  The idea is that in the beginning a long press will bring up these options, but soon one will learn to use the gestures instead.
(Multigestures would be possible, but I can't think of a nice way to show those when long-pressing.)
@Frenzie  @poire-z

**Comment by Frenzie** [comment]
Display would take a fair bit of effort (I mean, it's not a novel idea ;-) ), but just adding some swipes might be somewhat easier.

**Comment by Biep** [comment]
OK, consider it two separate proposals.. :-)
Not all gestures would be obvious, but some, such as the acute and grave accents, or a down swipe for cedilla, could be.  If you want to go wild, multiswipes could indicate other alphabets (as in e.g. swipe left to indicate alphabet change, and then up for Cyrillic, down for Hebrew, right for Greek).  With some reasonable mapping that could become fairly mnemonic too.

**Comment by Frenzie** [comment]
Implemented by #4884, #4886 and #4887.
