### ISSUE TITLE
Evernote can't login

### ISSUE THREAD

**Issue by Nanco300** [koreader/koreader#4000]
* KOReader version: v2015.11-1735-g14e7730_2018-06-02
* Device: Kobo Glo

    Koreader menu --> Evernote --> Login
    Type login and password (or email and password)
    Login button.

When I try to connect to the Evernot the  Koreader closes, but I did recieve a mail after the attempt.

[evernote.log](https://github.com/koreader/koreader/files/2078180/evernote.log)

**Comment by NiLuJe** [comment]
Duplicate of #3600
