### ISSUE TITLE
tweak ota update

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#4002]
* KOReader version: all
* Device: all (I guess) but specifically kobo as I got one

I like my koreader and kor's menu without all the things I don't use so I removed lots of plugins on my first install (I only keep 7 of them which I use or are needed by the system). The fact is when I want to OTA update, the update can't process because the koreader tree on my device is not as intended by the updater (missing this directory, and this directory).

for now , I run a script before updating to add again the files I deleted ; after that I run the ota, it updates, and after that another script for removing the above-mentioned plugins.

So, I there a way to customize otamanager.lua to process the files and skip the files which were obviously removed ?

**Comment by cramoisi** [comment]
I guess it's related to this ?

```
function OTAManager:_buildLocalPackage()
    -- TODO: validate the installed package?
    local installed_package = self.installed_package
    if lfs.attributes(installed_package, "mode") == "file" then
        return 0
    end
    if lfs.attributes(self.package_indexfile, "mode") ~= "file" then
        logger.err("Missing ota metadata:", self.package_indexfile)
        return nil
    end
    if Device:isAndroid() then
        return os.execute(string.format(
            "./tar cvf %s -T %s --no-recursion",
            self.installed_package, self.package_indexfile))
    else
        return os.execute(string.format(
            "./tar cvf %s -C .. -T %s --no-recursion",
            self.installed_package, self.package_indexfile))
    end
end
```

**Comment by NiLuJe** [comment]
zsync works by diffing a tarball of your tree, and I've never managed to get it to actually finish some of those steps properly (either building said tarball of diffing it or downloading the relevant needed pits or patching it) with an even slightly custom tree.

I've never bothered looking into it more, but I've more tha once let it chomp on the CPU for >30min before it just gives up ;).

**Comment by cramoisi** [comment]
@NiLuJe : ok, so let's my solution with scripts is good (backup all my mess, restore a pristine version of koreader, update, restore the mess) after all :) I'll go with it !
