### ISSUE TITLE
chapter title option in status bar

### ISSUE THREAD

**Issue by kokoreader** [koreader/koreader#4010]
* KOReader version: all
* Device: KA1

Good day.

I was wondering if the option to display the chapter title in the status bar at the bottom of the screen could be implemented. Thank you.

**Comment by cramoisi** [comment]
my two cent : title and chapter name would be great !

**Comment by AlanSP1** [comment]
Well, title of book and of chapter, it may better be placed in upper part, but if it goes down, it maybe "asks" for third line in status bar. I already asked for two lines status bar here: https://github.com/koreader/koreader/issues/1933

As we now have many options to see, having book and chapter title can take one line more, as it can get pretty big.

**Comment by cramoisi** [comment]
you don't need to enable everything.... I could be just an option to enable or not for people who want it. For myself, I enable page i am / total and number of page left int the chapter. Plenty of place left.

**Comment by cramoisi** [comment]
@AlanSP1 : I just do the opposite : I activate the less option. Everything which is not immediately relative to reading I have disabled :-P

**Comment by KenMaltby** [comment]
With the "Full" progress bar (with the cr3 "Status" bar that has the book title, at the top of the page) you can still have the "Mini" progress bar also (although you may have to tap the bottom right corner, to bring it back up), so you do have two lines.  One at the top and one at the bottom.  Maybe, with the page numbering removed from the top, there could be room for a short chapter title.  Would be some trick though messing with the cr3 code and grabbing the chapter title some how.

**Comment by cramoisi** [comment]
to note : all the options to remove things in the full-header-status-c3-bar are somehow functional from cr3.ini : displaying or not : page you are / total page, battery icon, battery status (disabled by default), time.

But really, this full-header-status-c3-bar is ugly :) and it's far better to use the little mini-bar which can be hidden and displayed so easily.

**Comment by AlanSP1** [comment]
@cramoisi Yes, I agree that we all have our own different customs and no one is same.

For me, I don't look at all information that is offered all the time, but from time to time I want to know some of info that is there. As getting some info that isn't included at the moment would require going to setting and enabling, for me, it is easier to already include all info, e.g. info on memory usage (to know when to restart koreader, just in case).

Anyway, that's why I think that all that info should be optional, that we all can set what we prefer.

**Comment by LucyOne** [comment]
I would also like to see the chapter title in the status bar. A rotation with author name - book title - chapter title would be great.
