### ISSUE TITLE
Auto-merge PR?

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4017]
Something interesting I saw today: https://julien.danjou.info/stop-merging-your-pull-request-manually/

It could auto-merge after, say, three devs approve a PR.

**Comment by cramoisi** [comment]
> It could auto-merge after, say, three devs approve a PR.

Am I wrong if I say : I've yet to see a PR approved by more that 1 dev ? (you) :-)

**Comment by Frenzie** [comment]
Yes, although generally speaking probably not. ;-)

But for a stupid automated system like that I'd say two separate opinions is the bare minimum if it were used.

**Comment by Frenzie** [comment]
I'll close this. It'll be findable in the archive for reference.
