### ISSUE TITLE
Evernote and local clipping text file issues

### ISSUE THREAD

**Issue by rudin17** [koreader/koreader#4019]
* KOReader version: koreader-android-arm-linux-androideabi-v2015.11-1744-g18db509_2018-06-16.apk
* Device: Onyx M96

#### Issue
Evernote feature apparently not syncing to Evernote web.

I am able to log on to evernote from my device.

Evernote acknowledges the logon. At first attempt, a special folder named "KOReader notes" appeared along with my other evernote online notes -- but this new "KOReader notes' remains empty.

The html local text export feature seems to be working.

The local clipping text file is not working, however, whereas it worked on a the previous build.

The "export all notes in this book" is greyed-out when "export to local clipping text file" is checked.

When attempting to "export all notes" from an open pdf,  export process starts, but after several seconds says that nothing was exported.

**Comment by rudin17** [comment]
I've also just noticed that the highlights are no longer embedded in the .pdf file.

The previous build (4.12) seemed to embed highlights quite well; these were visible when transferring the pdf over to my mac computer -- but are now no longer there -- although they are still readable by KOReader.

So there seems to be a bigger problem related to highlighting.

**Comment by NiLuJe** [comment]
Which previous build would that be? I'm not quite groking the version scheme you're using, do you mean a build from the 12th of March?

**Comment by poire-z** [comment]
There's been a few Evernote/clipping fixes over the last year:
https://github.com/koreader/koreader/pulls?q=is%3Apr+author%3Amustafa-001
So, may be this is solved. Re-open if not.
