### ISSUE TITLE
Which target for various Kindles?

### ISSUE THREAD

**Issue by hfpop** [koreader/koreader#4021]
The page at http://build.koreader.rocks/download/nightly shows three downloads for Kindle:

koreader-kindle-arm-kindle5...
koreader-kindle-legacy-arm-kindle...
koreader-kindlepw2-arm-kindlepw2...

Which is the version to be used on Kindle Voyage? 
I used kindle5 and kindlepw2. (KV with the last firmware) Both of them work, but show various errors in the crash.log file:

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
...
06/24/18-20:43:06 ERROR failed to register crengine font cannot register font …
(a lot of these)

**Comment by NiLuJe** [comment]
I forgot to add that bit of info to the Wiki, I'll do that ;).

For ref:.

Kindle Legacy: K2, DX, K3
Kindle: K4, K5, PW1
Kindle PW2: Everything else ;). (PW2, KV, KT2, Oasis, KT3, KOA2).

As for the content of `crash.log`, even when not in debug mode, it's moderately verbose (i.e., don't expect an empty file).
Those particular ffi.load warnings are harmless, and perfectly normal (libblitbuffer is used on Android, and SDL on the emulator). The path of least resistance was simply not to ship those libraries on targets where they're not needed, and live with the warnings ;).

**Comment by NiLuJe** [comment]
FWIW, I'm seeing the CRe warnings on a bunch of Amazon fonts... but I can still select them from the menu :?

**Comment by hfpop** [comment]
Not quite true:
- I can select Amazon Ember, but looks bolded, i.e. defective processing.
- I can select Amazon Ember Bold, but looks bolded exactly the same way, i.e. defective processing.
- I do not see Caecilia at all.
- I do not see DiwanMuna, SakkalKitab, NotoSansBengali and others at all.
- I do not know how to read the other fonts, looks like they are not for latin languages.

**Comment by NiLuJe** [comment]
Forgot to mention that that was on FW 5.8.1, it's quite probable things got worse in newer FW.

I do see the bold thing on a few of them, too, though ;).

I vaguely looked at what CRe was doing, it looks like very basic assumptions are made about what the header should look like, and if it doesn't, well, too bad ;p.

**Comment by NiLuJe** [comment]
#4039 magically got rid of the bold issue (on Ember, too, I think) on my end.

I'm guessing some of those have funky family names and/or styles that are only properly mangled and/or coalesced via fontconfig in the native system.

CRe definitely needs to handle things better, but in the meantime, this should avoid the most egregious issues.

**Comment by hfpop** [comment]
On KV 5.9.6.1 JB, the log for koreader 1755 shows the following:

ERROR failed to register crengine font: cannot register font 
</usr/java/lib/fonts/Amazon-Ember-Medium.ttf>
</usr/java/lib/fonts/Amazon-Ember-MediumItalic.ttf>
</usr/java/lib/fonts/Amazon-Ember-Regular.ttf>
</usr/java/lib/fonts/Amazon-Ember-RegularItalic.ttf>
</usr/java/lib/fonts/Caecilia_LT_66_Medium_Italic.ttf>
</usr/java/lib/fonts/Caecilia_LT_75_Bold.ttf>
</usr/java/lib/fonts/Caecilia_LT_76_Bold_Italic.ttf>

All the other fonts have been sorted out. But Amazon Ember and Amazon Ember Bold are still bolded. And Caecilia and Caecilia Condensed are not visible in the list. There is an entry PMN Caecilia LT however.

Thank you.

**Comment by NiLuJe** [comment]
Caecilia condensed is now blacklisted, because we genuinely can't use it (it requires lab126's own freetype patch to render as expected (namely, condensed). Without it, it's just a hobbled Caecilia clone.

I'm not quite sure what happened to Ember, because it loads fine on my PW2 on 5.8.1, but you're not the only one, I've seen similar stuff in other logs.

One day we'll fix CRe instead and this'll be history, this was just a minor workaround in the meantime ;).

**Comment by NiLuJe** [comment]
I'll close this, since the original issue has been taken care of ;).

The fonts issue is already tracked in #2925 ;).
