### ISSUE TITLE
Auto-show bottom menu not working in Pocketbook

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#4028]
* KOReader version: v2015.11-1748-g6877ade_2018-06-25
* Device: Pocketbook Inkpad 2

I'm presupposing that `Screen > Activate menu > Auto-show bottom menu` is meant to toggle whether a tap on statusbar vanishes the statusbar or brings up the bottom menu.

The menu item has the described effect on my Kobo H2O, but not on Pocketbook Inkpad 2. On Pocketbook Inkpad 2, the statusbar vanishes on tap regardless what is selected in the menu item.

**Comment by Frenzie** [comment]
Same version?

**Comment by ersi-dnd** [comment]
Yes, the same version of Koreader. And I just discovered that I described the issue wrong, because the taps between Inkpad 2 and H2O give a different impression, but are not really different.

I wrongly perceived that the tap on statusbar on H2O brings up the bottom menu and does not vanish the statusbar, because I was not tapping close enough to the edge/statusbar. Now I find that the tap on H2O also always vanishes the statusbar, I just have to aim very close to the edge. 

As to Pocketbook Inkpad 2, the bottom menu shows up on tap, I just have to aim somewhat **away** from the edge.

To conclude, the named setting is evidently not meant to affect whether the statusbar vanishes or not. I assumed that part wrong.

**Comment by poire-z** [comment]
> I'm presupposing that Screen > Activate menu > Auto-show bottom menu is meant to toggle whether a tap on statusbar vanishes the statusbar or brings up the bottom menu.

Indeed wrong presupposition :)
This menu item controls just whether, when tap in middle top or swipe down from the top to bring the Top menu, well, the bottom menu should be shown too.

> Now I find that the tap on H2O also always vanishes the statusbar, I just have to aim very close to the edge.

And this area has been even more reduced 1 or 2 months ago, so I need to really touch the bezel to have it work (which is good, because previously, I was hitting it too reasily).

**Comment by ersi-dnd** [comment]
@poire-z 
> And this area has been even more reduced 1 or 2 months ago, so I need to really touch the bezel to have it work (which is good, because previously, I was hitting it too reasily).

Thanks for the explanation. Is there a way to make this into a user-tweakable option somewhere in Advanced settings?

**Comment by poire-z** [comment]
No option in the UI, but it's one of the thing that is in `default.lua`, that you could already override in a `default.persistent.lua`. 
https://github.com/koreader/koreader/blob/0dc809942586cc115f1adcff820ebff47542cf0a/defaults.lua#L73

Just revert or increase the values that were changed in: https://github.com/koreader/koreader/commit/0dc80994
