### ISSUE TITLE
Problem with some stardict dictionaries (v2.4.2)

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#4030]
* KOReader version: b1749 28.6.2018
* Device: Kobo Aura One

#### Issue

Tried some dictionaries found here: http://download.huzheng.org/bigdict/

I downloaded these three dictionaries:

Oxford English Dictionary 2nd Ed. P1
Oxford English Dictionary 2nd Ed. P2
Oxford Advanced Learner's Dictionary 8th Ed.

Also, I unzipped them (appropriate file with .dict.dz extension, living only extenstion .dict) and placed where they should be. Koreader sees them when going to dictionaries menu in options, but when selecting words, there's none found.

I have some working dictionaries (same stardict version 2.4.2), they work, but I'd like to use these dictionaries also, as they are much bigger and I hope more comprehensive.

From what I see, it looks that they much more html markups then those that work for me at the moment.

Also, if you can suggest some dictionaries (with links to download them) for koreader, I'm looking for en-en ones.

**Comment by gerhaher** [comment]
I use all those three you mention. And they work fine for me.

**Comment by cramoisi** [comment]
Do you have the possibility to try them with sdcv (on mac, on a linux vm ?) ?

**Comment by cramoisi** [comment]
@AlanSP1 

>Also, I unzipped them (appropriate file with .dict.dz extension, living only extenstion .dict) and placed where they should be. Koreader sees them when going to dictionaries menu in options, but when selecting words, there's none found.

I'm not sure I understand this : did you remove the .dz ext ? if it's the case, it's the reason they don't work. The directory has to be as poire-z shows just above.

**Comment by AlanSP1** [comment]
It looks that my unzipping messed things up, so now when I copied zipped files, everything works.

Only thing I noticed is that now first search takes a pretty long time, exiting koreader also resets this initial opening time. I guess it is because files are zipped, before I used dictionaries that were unzipped and it worked faster.

Anyway, thanks, you helped me a lot.

**Comment by poire-z** [comment]
Your new dicts are really huge.
You could gunzip de *.dict.dz if you really wanted (rename them to dict.gz for correct gunzip'ing), but you would get even huger files. You could try if its faster and tell us.
(the initial time to read the whole file content from SDCard to RAM would be even higher, but I think dict.dz allows to get directly to the position in the gzipped file, so it would not be needed to read the whole file - what's read may be fully are the index files, .idx & .idx.oft - these can be huge too, and can't be compressed).

Also, the initial long opening time should happen only after a reboot. For each lookup, an sdcv execution is done, so if it's faster, it's just using dict content that has been read and is still in memory. Restarting koreader (without rebooting the device) should still benefit from this stuff that should still be in RAM.

**Comment by AlanSP1** [comment]
Yes, I guess that my previous dictionaries also are smaller, so everything worked faster. I don't want to test unzipping, now that everything works, I will use it, but just was a bit surprised how long it took for first search. As it is only first search, it is fine for normal daily usage. I don't go in and out of koreader that much when normally using it, only now when I'm installing and testing it for the first time.
