### ISSUE TITLE
FR: Different options for screensaver (i.e. suspending device) and power off

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#4031]
* KOReader version: last build
* Device: Kobo Aura One

At some moment we had suspend and power off settings through settings.reader.lua, but it was changed through @robert00s commit here: https://github.com/koreader/koreader/pull/3535

I just installed on my new Aura ONE latest build (on my H2O I still have older build without this PR) and I see that I can't have different screensaver for power off and suspend, as before.

So, I don't know if device is just suspended, or powered off.

It would be nice to again have different settings for power off, probably with whole menu doubled (i.e. with all options we now have for suspending and powering off), only with changes so we can differentiate what are we setting, suspend or power off.

And per this comment: https://github.com/koreader/koreader/pull/3535#issuecomment-350487424

Anyway, hope it wouldn't be too difficult to have separate settings

**Comment by poire-z** [comment]
You have some references to followups PR at the bottom of the PR you linked to: #3572, #3619.
Available manual settings summarized in https://github.com/koreader/koreader/issues/2589#issuecomment-323927682
(I didn't re-read them, and I don't really remember what I changed :) I hope my writtings at the time explains things right :)

**Comment by cramoisi** [comment]
Quite right I'm using the options since then : 

```
poweroff_screensaver_type = "random_image" or "message", "cover", "bookstatus", "readingprogress", "disable",
poweroff_screensaver_dir = "path to same as screensaver_dir or alternate dir for poweroff image(s)",
poweroff_screensaver_message = "message to use instead of Powered off",
reboot_screensaver_type = "random_image" or "message", "cover", "bookstatus", "readingprogress", "disable",
reboot_screensaver_dir = "path to same as screensaver_dir or alternate dir for reboot image(s)",
reboot_screensaver_message = "message to use instead of Rebooting...",
```

**Comment by AlanSP1** [comment]
Thanks, I'll check this settings and see how it works.
