### ISSUE TITLE
Idea: menu entry "open last book: <last_read_book_name>" 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4032]
* KOReader version: all
* Device: all

#### Idea

Idea is to add information about last open book name, in "open last book" menu entry. 

So this menu will be dynamic. Examples :
"open last book : Hamlet" 
"open last book : War and peace" 
"open last book : a rss news downloader single page article" 

The last situation annoys me the most (when I recently read "rss downloader news" (or send2ebook) , then after some time I start ebook reader again and what to open last read book and it turns out to be read single page news article. 

But it can also be useful for person reading 2 books at the same time. 

#### Steps to reproduce
Open top menu, see entry for "open last book"

**Comment by robert00s** [comment]
You should use history :)

**Comment by cramoisi** [comment]
@mwoz123 you should configure KOReader to open the history at startup, so you would get exactly what you are describing.

In the filemanager, menu, files manager  > start with > history (your install is on "last file)

**Comment by mwoz123** [comment]
implemented in #4042 . To enable go to 
`Display mode > Other settings -> Show filename in Open last menu item`
