### ISSUE TITLE
Trying to Enable WiFi just before Logging to Evernote Freezes Device

### ISSUE THREAD

**Issue by t5k6** [koreader/koreader#4034]
* KOReader version: v2015.11-1735-g14e7730_2018-06-02
* Device: Kobo Aura - Mark 5

#### Issue

If WiFi is not enabled beforehand and I try to login to Evernote, it brings me the menu to turn the WiFi on. However, once the cursor is in the username textbox, I cannot click any option about WiFi. All I can do is power off the device to get rid of the menu items.

![6_27_18 10_57 pm office lens](https://user-images.githubusercontent.com/12563212/42112839-e8647310-7bf1-11e8-9fae-27122ab5cf53.jpg)

This does not happen when I am already logged in to Evernote.

**Comment by NiLuJe** [comment]
Only slightly related: I have somewhat of a minor issue with the whole WiFi UI:

* When it successfully connects, none of the popups get autodiscarded (neither the list of SSIDS, nor the infobox). I can understand why we'd want to keep the infobox, but the SSID list is fairly useless at that point (and, if you're in an urban area, chances are it'll be nearly full-screen, which makes the "discard it" tap areas somewhat small).

* When a feature requires WiFi and the "ask if offline" option is on, you do get steered towards enabling WiFi, but the previous action is not resumed once connected.

**Comment by Frenzie** [comment]
All true.

**Comment by poire-z** [comment]
Closing as probably obsolete after #6424 and other previous Wi-Fi related PRs.
