### ISSUE TITLE
Segfaults on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [koreader/koreader#4044]
* KOReader version: v2015.11-1735-g14e7730_2018-06-02
* Device: Ubuntu 14.04

#### Issue

Application crashes (segfault)

#### Steps to reproduce

Run https://github.com/koreader/koreader/releases/download/v2018.06.02-beta/koreader-appimage-x86_64-linux-gnu-v2015.11-1735-g14e7730_2018-06-02.AppImage on Ubuntu 14.04

##### `crash.log` (if applicable)

```
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|
 It's a scroll... It's a codex... It's KOReader!
 [*] Current time: 07/03/18-06:27:40
 [*] Version: v2015.11-1735-g14e7730_2018-06-02
Segmentation fault (core dumped)
Parent pid 9822, child pid 9825
```

References:
* https://github.com/AppImage/appimage.github.io/pull/510
* https://travis-ci.org/AppImage/appimage.github.io/builds/399441769#L633

**Comment by cramoisi** [comment]
got it too when running the emu inside a ubuntu VM on a win10 Host (virtualbox)

**Comment by NiLuJe** [comment]
Is it the first release that fails? Does the latest OTA still do?

**Comment by NiLuJe** [comment]
If one of you can get a stacktrace, that'd be helpful ;).

Also, which glibc version is Ubuntu 14 using?

**Comment by cramoisi** [comment]
@NiLuJe : for the emu on ubuntu guest + w10 host with virutalbox, it fails since I tried it for the first time, in january and all release since then. (but now my ubuntu VM is at the latest and it continue to fail). 

The same config on mac (ubuntu guest + high sierra host with virtualbox) works without problem so I just switched. (won't be able to do anything with this before Thursday)

**Comment by cramoisi** [comment]
@probonopd can you run the emulator ?

**Comment by probonopd** [comment]
> If one of you can get a stacktrace, that'd be helpful ;).

How do you do this?

> @probonopd can you run the emulator?

Which emulator are you talking about? Sorry for asking this, I literally just tried to run the latest AppImage from the GitHub Releases page on Ubuntu 14.04 in an [automated test](https://github.com/AppImage/appimage.github.io/blob/master/code/worker.sh).

**Comment by NiLuJe** [comment]
Given the early crash, my guess is an SDL2 ABI mismatch?

I have no clue how AppImage thigies work, but, basically, running it through gdb would help ;).

**Comment by NiLuJe** [comment]
Also, I have no idea how the AppImages are built, since they're not part of the OTA roation, so, forget my comment about trying somethign newer ;).

**Comment by probonopd** [comment]
> I have no clue how AppImage thigies work, but, basically, running it through gdb would help ;).

An AppImage is really just a self-mounting filesystem image that runs whatever the application developer has put into it. That's all it is. You could also distribute the same ingredients in a zip or other archive file, but then the user would have to extract the archive before being able to run the application.

Are you sure that you are bundling all SDL related libraries inside the AppImage? If the application uses the bundled SDL, then there should be no version mismatch with the host SDL (since it is not used), right?

**Comment by NiLuJe** [comment]
We don't build SDL (at least, usually), which is why that seems like a good point of failures for ABI mismatches if that also holds ture for the AppImage ;).

**Comment by NiLuJe** [comment]
Okay, there's an SDL2 lib in the AppImage. It's the .so and not the proper sover (.so.0), but we're patching ffi.load to handle that, so it should get picked up...

We're still not building it, so I'm not quite sure where it comes from, so ABI mismatches are still not out ;).

**Comment by Frenzie** [comment]
It's from Ubuntu 14.04. It's on GitLab same as the others on the same Docker base image. Didn't I make it auto-download to koreader.rocks yet?

**Comment by Frenzie** [comment]
@probonopd At what time did you try? That's rather common on Travis when Americans are awake. European morning is generally more reliable in my experience.

**Comment by probonopd** [comment]
The test was downloading https://github.com/koreader/koreader/releases/download/v2018.06.02-beta/koreader-appimage-x86_64-linux-gnu-v2015.11-1735-g14e7730_2018-06-02.AppImage

**Comment by Frenzie** [comment]
Sure. I don't think anything should've changed since then as far as the AppImage goes anyway. But I know the AppImage worked on bare metal Ubuntu 14.04 when I tested it a few months ago.

**Comment by NiLuJe** [comment]
@Frenzie : Yeah, it doesn't end up on koreader.rocks ;).

**Comment by Frenzie** [comment]
I probably wanted to wait until the auto-purging was sorted out. It can now be added to https://github.com/koreader/koreader-misc/blob/3de3dc0a113ca374a853d9199c687c7993fc3767/nightswatcher/nightswatcher.py

**Comment by Frenzie** [comment]
It works fine on my Ubuntu 14.04, so I don't know what could be causing this.
