### ISSUE TITLE
size of the page brand

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#4046]
* KOReader version:
* Device: kobo aura one

hello, what settings need to be changed so that the bookmark at the top left of the screen is larger. A bit like nickel

**Comment by KenMaltby** [comment]
If you are just talking about the image itself, the "dogear.png" is in: /.adds/KOReader/resources/icons/

**Comment by davicraquette** [comment]
That's it, thank you

**Comment by cramoisi** [comment]
@davicraquette : if you want to change the file, be aware the file is also used for the coverbrowser (@poire-z ) ; I don't know if you can upscale it in the code (i didn't find anything related to that)

**Comment by poire-z** [comment]
That dogear icon is indeed used by coverbrowser to hint opened books.
But there's still an issue mentionned by @Frenzie after https://github.com/koreader/koreader/issues/3265#issuecomment-335006567 , that this icon is not scaleByDpi'ed in reader.
(I never insisted on fixing that, cause I like it small as it is on my 300dpi gloHD).

**Comment by davicraquette** [comment]
![20180705_075029 1](https://user-images.githubusercontent.com/39924188/42304961-179bab2c-8029-11e8-884a-f554692e17ee.jpg)
I replaced the dogear png icon with this one.
Except that the original icon comes back after each koreader update. How to save my icon?

**Comment by cramoisi** [comment]
do you use KSM to launch KOReader ?

**Comment by davicraquette** [comment]
yes

**Comment by cramoisi** [comment]
you could add a little script in your KSM install user script directory to copy a backup of your dogear.png when you need it

something like that : 

```
cd /.adds/koreader/resources/icons/
mv dogear.png dogear_ori.png
cp /.adds/misc/dogear.png dogear.png
```
you will need to check the path and add a copy of the dogear.png of yours in .adds/misc

**Comment by Eduardomb22** [comment]
@davicraquette , can you post the icon here? I wanna try it too

**Comment by KenMaltby** [comment]
It does look like a nicer one.  You can just remove, or rename, the dogear.png in the downloaded package, prior to merging the koreader folder from the download to your device.  Then your new dogear.png will remain the one used.

**Comment by davicraquette** [comment]
here is the file  
![dogear](https://user-images.githubusercontent.com/39924188/42721751-6bca1968-8740-11e8-81d6-4f206667666e.png)

**Comment by davicraquette** [comment]
hello, is it possible to automatically center the title of the book?
Not being English speaking, I can not find the file to modify.
![20180716_095459](https://user-images.githubusercontent.com/39924188/42748140-50cd26f0-88df-11e8-81e9-517a3d52e913.jpg)

**Comment by davicraquette** [comment]
I would like this. Is it possible?
![titre](https://user-images.githubusercontent.com/39924188/42758441-d362346a-8903-11e8-81a5-c351610e104f.jpg)

**Comment by KenMaltby** [comment]
I don't know if it will work but you could try adding:
window.status.title.align=text-align: center
to ".adds/koreader/data/cr3.ini"
