### ISSUE TITLE
Idea: multi-seat (one device, multiple users w/ different reading progress, bookmarks etc)

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4066]
* KOReader version: all
* Device: all

#### Issue
I'm usually the only user of my ebook reader. 
But sometimes I'd like read the same book on same reader with someone else.
Usually one person has to wait until other one finish book. 

E.g. book has 300 pages. 
- I started reading, read 30 pages. Finished 
- Someone else start reading from first page. Read 50 page,
- I'd like to continue reading from 30 page, I read 40 pages so finished at page 70,
- someone else wants to continue reading from 50 page ..

Dealing with bookmarks on writing where each of us finished is annoying.

**Comment by mwoz123** [comment]
Workaround: create a copy of book for other person.

**Comment by pazos** [comment]
Closing this one as nobody cares :). Feel free to comment here if you're willing to implement or suggest ideas

**Comment by utmost-premise** [comment]
Might be useful for people searching for this issue: https://github.com/artemartemenko/KOReader_MultiUser.koplugin
