### ISSUE TITLE
Sort folders and files together?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4068]
Today, if you have two folders named A and C, and a file named B, they will be sorted with the folders first, like this: A, C, B.

Would it be difficult (or impossible) to make folders and files equal (so to speak), so that the sorting instead results in A, B, C?

**Comment by poire-z** [comment]
The code process directories and filenames differently, so it first process directories, sort them, and add them to the list, then the filenames, sort them, add them to the list. Re-ordering them correctly after that may be tricky.
(I personally like the current ordering, directories first - so what you'd like would have to be an option :)

**Comment by AlanSP1** [comment]
I think that it is more logical to have directories sorted first, and files after them. They are quite different things.

But, if there's need for sorting files and directories as same entries, this certainly should be option.

**Comment by Frenzie** [comment]
Some programs do it. 

https://fransdejonge.com/2018/05/sort-folders-before-files-in-the-gtk3-filechooser/

**Comment by NiLuJe** [comment]
Yeah, not a huge fan of mixed sorting either, the very exception being for a frecency sort.

**Comment by alethiophile** [comment]
Under many sort options, it doesn't even make sense. A directory has an atime, an mtime and a name, but not ebook metadata titles, or a percent read. If those options were selected, it's really unclear how directories should be ordered relative to files.

**Comment by Frenzie** [comment]
/shivers :-p

But more to the point, what about the size of that menu?

**Comment by robert00s** [comment]
I have no idea how to reorganize it. We can of course not share this option and close this issue :)

**Comment by NiLuJe** [comment]
Random thought : do the two "sort by percent" options make sense with a "revert sort" toggle in the previous menu?

**Comment by robert00s** [comment]
`Sort by percent` go to submenu. 

![aaa - koreader_154](https://user-images.githubusercontent.com/22982594/43549031-d52fcc9c-95df-11e8-83d5-83afc6acb9e6.png)
![aaa - koreader_153](https://user-images.githubusercontent.com/22982594/43549037-d85b8424-95df-11e8-8135-5b29bb779d68.png)
