### ISSUE TITLE
koreader/kepub

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#4071]
* KOReader version:
* Device: kobo aura one

hello, when inserts a kepub file into the folder containing all my books, koreader do not see this file.
Conversely, he sees the epub 
kepub works best in kobo via nickel. Why not with koreader?

**Comment by NiLuJe** [comment]
It should (kePubs are usually named filename.kepub.epub, so KOReader sees that as an ePub, and opens it as an ePub, and it works).

You'll have better rendering performance with a proper ePub than a kePub on KOReader, but they should open without any issue. (I can vouch for that, I mainly have kePubs on my device).

**Comment by davicraquette** [comment]
I had, indeed, found that koreader sees kepub / epub files as epub. But if I paste the file kepub (produced by calibre) koreader does not see this file.

**Comment by NiLuJe** [comment]
You mean if you strip the .epub and just name it blah.kepub? Yes, we don't. (Nickel might not, either).

**Comment by cramoisi** [comment]
the kepub must be named `something.kepub.epub` that's the correct way to use with calibre / nickel / koreader (but if you have a correct epub, I don't know why you bother to plague it with the kepub trash code)
