### ISSUE TITLE
Mini progress bar disappears and occasionally reappears at random

### ISSUE THREAD

**Issue by JW01** [koreader/koreader#4072]
* KOReader version: V2015.11-1523-g78284e1
* Device: Kindle

#### Issue
Mini progress bar disappears and occasionally reappears at random
#### Steps to reproduce
Cannot, it's random
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Try again with a more recent nightly.

**Comment by NiLuJe** [comment]
Possible dup of #2598 ;).

**Comment by Frenzie** [comment]
Please reopen with more info if necessary.
