### ISSUE TITLE
Multiline text is not translated

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#4085]
* KOReader version: newest
* Device: all

#### Issue
Multiline text is not translated. 
Polish:
![test - koreader_125](https://user-images.githubusercontent.com/22982594/42895321-cd8ee03a-8ab9-11e8-8286-9ffeb06aec82.png)

French:
![test - koreader_126](https://user-images.githubusercontent.com/22982594/42895315-c98a641e-8ab9-11e8-8f6c-fdcebfde54c7.png)

This applies only to the texts they use double square brackets [[...]] 
e.g.
https://github.com/koreader/koreader/blob/464672108e2d7b444dc1eced68c04d9735fb0e33/frontend/apps/reader/modules/readerwikipedia.lua#L254-L259

**Comment by Frenzie** [comment]
Most are. I'm not sure I have time to look at the Python regex atm, see misc.

**Comment by poire-z** [comment]
Are the creoptions ones (when long press on title) transated?
Because there is a different, the creoptions ones don't have a leading newline:
`help_text = _([[Font hinting is the process...`

**Comment by Frenzie** [comment]
Indeed, the problem isn't in Python like I thought just reading the messages on my phone. Lua patterns are more annoying, but I'll have a quick look after all this new stuff compiles.

**Comment by Frenzie** [comment]
I think there are basically three approaches:

1. Don't write newlines in the code. This is potentially less legible, and needs some script to police.
2. Strip starting newline at `gettext.translation()` time.
3. Add translations twice. In its simplest form something like this, more sensibly with some kind of check.
```diff
diff --git a/frontend/gettext.lua b/frontend/gettext.lua
index 42e4c297..854aef2d 100644
--- a/frontend/gettext.lua
+++ b/frontend/gettext.lua
@@ -69,7 +69,9 @@ function GetText_mt.__index.changeLang(new_lang)
             what = nil
         else
             -- comment
             if not line:match("^#") then
                 -- new data item (msgid, msgstr, ...
                 local w, s = line:match("^%s*(%a+)%s+\"(.*)\"%s*$")
                 if w then
@@ -86,6 +88,9 @@ function GetText_mt.__index.changeLang(new_lang)
                     data[what] = (data[what] or "") .. s
                 end
             end
+            if what then
+                data[string.sub(what, 3)] = data[what]
+            end
         end
     end
     GetText.current_lang = new_lang
```

**Comment by poire-z** [comment]
No real opinion on these options.
Shall I quickly fix the few listed above? Or keep them if you feel like implementing one of these option soon?

**Comment by Frenzie** [comment]
Fixing them quickly for now is fine by me. The only problem is the problem is likely to crop up again. :-)
