### ISSUE TITLE
default reading direction

### ISSUE THREAD

**Issue by Gil-boy** [koreader/koreader#4089]
* KOReader version: latest nightly v2015.11-1782-g4646721_2018-07-16
* Device: kobo aura one

#### Issue
 can you add a dfeature to change default reading direction  in the menu  when you long press from  on reading direction # right to left#

**Comment by NiLuJe** [comment]
IIRC, a lot of stuff barely supports RTL (Us, CRe, I think only MuPDF does a bit).

**Comment by NiLuJe** [comment]
Fold w/ #4088
