### ISSUE TITLE
"Go to Location" and dictionary lookup interfere with each other at the bottom of the page

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4094]
When you hold on a word at the bottom of the page to perform a dictionary lookup, you instead open the "Go to Location"-window.

To perform your dictionary lookup, you have to first remove the status bar (by a tap) and then long press the word. And when the lookup is finished, another tap to make the status bar appear again.

Any brilliant solution to this?

**Comment by robert00s** [comment]
Yes, you should go to Advanced Settings and change DTAP_ZONE_MINIBAR. Try that:

![zaznaczenie_128](https://user-images.githubusercontent.com/22982594/43039841-24af45c0-8d36-11e8-9342-0b35ce0cd27c.png)

I think that by default we should smaller this parameter or calculate it based on the size of the status bar

**Comment by gerhaher** [comment]
Yes, that was brilliant.
Works like a charm!

Thanks!
