### ISSUE TITLE
Enable ''Add Note'' option when highlighting

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#4115]
This is a feature request.

A standard use of my reader (except of reading ;o) is to fix typos and other book related errors.
The way I do it is to first highlight the part of the text with the error, then press the highlighted block and select edit and then add the description of the fix or the correct word.
I was thinking if I could somehow save some clicks there (some books have tens of errors) when I noticed the disabled "Add Note" option to the highlight dialog.

In the ["Bookmark titles or comments?"](https://github.com/koreader/koreader/issues/3415) I think that we concluded that no new comment/note field is going to get added to KoReader anytime soon.
So, how about using this "Add Note" option to highlight and open the edit dialog in one go?

It might also need some thinking of the naming scheme (bookmark name, comment, note..)

**Comment by Frenzie** [comment]
I think that button is actually a placeholder for PDF comments. See eb4c76bd159363315141822d709ce3661a7d25ef.

**Comment by embryo10** [comment]
Sorry, never got any notifications from GitHub for the replies..

Are they any different than the "text" key of the epub highlight?
If not, it would be nice to enable it for epubs to do that editing.

**Comment by Frenzie** [comment]
PDF comments can either just be applied to a random part of the page or to a highlight. So I guess they can be the same to some degree. Depends a bit on the MuPDF API for them too.

Btw where was this conclusion thing you mentioned? :-)

**Comment by embryo10** [comment]
It wasn't a conclusion per se.
It just left me with the impression that apart from an `"edited" = true` key, nothing more was scheduled for the near future...

**Comment by embryo10** [comment]
Added from v2019.04 onward... Great!
