### ISSUE TITLE
Show hidden folders when selecting Screensaver folder

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#4117]
Well, the title says it all.
My screensaver images are located in the .Adds directory but I can not select it...

**Comment by robert00s** [comment]
You have to enable `Show hidden files` in file browser.

**Comment by embryo10** [comment]
But I already have (in the book browser).
I think that this is a different browser...

**Comment by robert00s** [comment]
Check once again. I can see hidden files (on my emulator):

![koreader - koreader_150](https://user-images.githubusercontent.com/22982594/43344716-0309ae9c-91eb-11e8-923d-e719257b292c.png)

**Comment by embryo10** [comment]
Well, I don't...
I re-checked!

**This is the Screensaver folder selector:**
![reader](https://user-images.githubusercontent.com/8684739/43349887-cb9965bc-920b-11e8-877e-ac458ccb82cd.png)

**and this is the book file manager:**
![filemanager](https://user-images.githubusercontent.com/8684739/43349909-f2739f04-920b-11e8-98a5-547375abfa40.png)

They are at the root of the onboard storage.
What am I missing here?

**Comment by NiLuJe** [comment]
You mentioned in the other issue running a tremendously old nightly, is that still the case? That might be a factor here, too ;).

**Comment by cramoisi** [comment]
I have my screensaver png in a hidden dot folder and to get to it I enabled the option as @robert00s said without problem since my day#1 of koreader (of all I remember). So @NiLuJe advice to update should be of great help to you.

**Comment by embryo10** [comment]
Sorry, never got any notifications from GitHub for the replies..

I'll install the latest release (2015.11-1800) and I'll report back..

**Comment by embryo10** [comment]
Installed v.1800 and nothing changed.
Still no hidden folders in Screenshot folder selection.
Then, I got an inspiration.
I went to the File manager and unchecked the show hidden files option, and re-check it.
After this, the Screenshot folder selection showed the hidden folders.

**Comment by poire-z** [comment]
And if you restart koreader, you get the same behaviour as before and you still have to do that trick to get it to show hidden folders? Or is it permanently fine?

**Comment by poire-z** [comment]
There may still be a small similar issue with the new `Choose screensaver image`.

It looks only FileManager and DownloadMgr uses the show_hidden setting.
The plain FileChooser starts with a show_hidden=nil.
@robert00s 
`Choose screensaver directory` uses DownloadMgr, and so shows hidden files.
`Choose screensaver image` uses FileChooser without any show_hidden setting, and so won't show hidden files. You may want to make it uses that, for consistency (and so that when choosing screensaver image, if you go up too much outside .adds/, you can go back down into it).
