### ISSUE TITLE
Hold backspace (virtual keyboard) clears all text from InputDialog

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4129]
* KOReader version: git master
* Device: emulator

#### Issue
Long press (2 seconds?) backspace key (virtual keyboard) clears all InputDialog text. 
IMHO this is unexpected in multilines texts e.g. news downloader config editor (https://github.com/koreader/koreader/pull/4126 )

Where config is over 1kb (>1000 chars) and hold backspace clears all.
Expected behavior would be to delete char one by one.

#### Steps to reproduce
Open multiline InputDialog eg.#4126 hold backspace to delete line - it clears all configuration.

**Comment by Frenzie** [comment]
Over here I imagine:

https://github.com/koreader/koreader/blob/e37c34531ad3327f5602ae8efdaab23928ae1cac/frontend/ui/widget/virtualkeyboard.lua#L53-L56

Introduced in c83f35a0d07dfde280712c387a14cd0525bae111

**Comment by poire-z** [comment]
It's a feature, quite useful on short input texts (say, a highlight, that you want to clear the text to replace it with your words).
Surprising at first, but once this full clearing happened to you 2 or 3 times, you remember that it does that :) So, you will soon tap tap tap tap tap... to clear all.

Dunno how well we could do on eInk with the refreshes and the time it takes to-rerender the whole text if we were to implement Hold on key = repeat key press. And how would this delay and queued events do with visual feedback on when to stop pressing key...

**Comment by Frenzie** [comment]
I think the problem isn't so much the clearing as a lack of undo.

**Comment by NiLuJe** [comment]
I don't know how feasible it might be to make it clear the current *line* instead of everything on multiline inputs? (Or if that even helps...).

**Comment by mwoz123** [comment]
Ideal option for me would be slowly increasing speed of deleting chars (for multlines).

**Comment by poire-z** [comment]
^ implemented in #4124's https://github.com/koreader/koreader/pull/4124/commits/3b9f786ba887208c689300776691fd4f95b29030 . And it's quite usable !

**Comment by poire-z** [comment]
Closing, as the new alternative behaviour feels better and is less destructive.
