### ISSUE TITLE
CSS question

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#4131]
Hi, is there a way to make footnote looking like the second photo? I've tried:

a {
  vertical-align: text-top;
  font-size: 0.75em !important;
  line-height : 0.1;
}

And it works at Calibre, but it doesn't work at koreader. Anyone knows what am I doing wrong?  

Normal epub
![normal](https://user-images.githubusercontent.com/20425689/43522428-b89ad394-956f-11e8-8364-4d637f6185fd.png)

Edited CSS at calibre

![up](https://user-images.githubusercontent.com/20425689/43522439-c18de23e-956f-11e8-8aed-2ddc6eb38c3a.png)

**Comment by poire-z** [comment]
crengine does not support `text-top` for `vertical-align`. Only the values marked *** in https://github.com/koreader/koreader/issues/3923#issuecomment-386298207
So, you'll have to see how it looks with either `sup` or `middle`.
(and indeed play with font-size and/or line-height if you don't want them to affect the space between lines)

(And make it a User style tweak once you're happy, so you can apply it to other books, see https://github.com/koreader/koreader/pull/3944#issuecomment-389069259)

**Comment by Eduardomb22** [comment]
Thanks! It worked with "super"
