### ISSUE TITLE
Highlighting doesn't include final punctuation mark

### ISSUE THREAD

**Issue by protist** [koreader/koreader#4134]
* KOReader version: `v2015.11-1803-ge37c345_2018-07-29`, but also in previous versions for as long as I remember
* Device: Kobo H2O

#### Issue
Highlighting doesn't include final punctuation mark

#### Steps to reproduce
Attempt to highlight a selection that ends with a full stop (period) or question mark.

#### Expected behaviour
The highlight should include the final punctuation mark.

#### Observed behaviour
The highlight stops short of the final mark, only encompassing the final word. To include the punctuation mark, you have to include the first word of the following sentence in the highlight. (This behaviour was also observed by someone else [here](https://www.mobileread.com/forums/showpost.php?s=28ac23836b9e09f8a54fc89af57585d1&p=3689677&postcount=12).)

**Comment by poire-z** [comment]
Noticed that too. And they don't include the puncutations at the left or right of a line, even when it's not yet the end of paragraph. Not obvious to fix the way boxes are decided.
For reference:
https://github.com/koreader/crengine/pull/222
https://github.com/koreader/crengine/pull/107#issuecomment-386222250
https://github.com/koreader/crengine/pull/69
https://github.com/koreader/koreader/issues/1252#issuecomment-403270465

**Comment by willricemusic** [comment]
I'm also seeing this behaviour and find it troublesome. (KOReader version: v2015.11-1800-g0924b57_2018-07-29
Device: Kobo Aura One)

**Comment by poire-z** [comment]
Looks like I found a simple solution to this issue.
Now that with [ldomXRange::getSegmentRects()](https://github.com/koreader/crengine/pull/236), we are not required to have a range that starts and ends on real word boundaries, we could start and end the selection on non-word chars, and get:

<kbd>![image](https://user-images.githubusercontent.com/24273478/46744667-e1871380-ccab-11e8-9225-35659870088f.png)</kbd>

With this simple change to base/cre.cpp:
```c
--- a/cre.cpp
+++ b/cre.cpp
@@ -1129,9 +1129,9 @@ static int getTextFromPositions(lua_State *L) {
                        return 0;
                r.sort();

-               if (!r.getStart().isVisibleWordStart())
+               if (r.getStart().isVisibleWordChar() && !r.getStart().isVisibleWordStart())
                        r.getStart().prevVisibleWordStart();
-               if (!r.getEnd().isVisibleWordEnd())
+               if (r.getEnd().isVisibleWordChar() && !r.getEnd().isVisibleWordEnd())
                        r.getEnd().nextVisibleWordEnd();
                if (r.isNull())
                        return 0;
```
When we start or end selection with our finger on a word, it would behave as before and grab the whole word.
If we happen to start it or end it on a space or punctuation, these will be included (needs to be a little on the left side of a char to grab it).
It may be tedious with small fonts, and may need a few tries going back and extending it again to catch the additional punctuations and not the space after, etc... but it's workable.
I'll see how usable it is on my Kobo.

**Comment by quowarranto** [comment]
Why was this closed? The issue still persists. Highlighting doesn't capture the trailing punctuation. Editing only allows you to capture the word after the trailing punctuation, but not the trailing punctuation itself.

**Comment by mergen3107** [comment]
If you press and hold the button to select one more word, it will select only one character

**Comment by poire-z** [comment]
Question asked again at https://github.com/koreader/koreader/pull/4267#issuecomment-851220618 and answered there.

**Comment by hius07** [comment]
Additionally, the wiki says:
"Long press of the arrow buttons moves the selection boundaries by characters."
https://github.com/koreader/koreader/wiki/Clipboard

**Comment by quowarranto** [comment]
Thanks, all. I think the multiple comments on other tickets, including someone going through the source code to implement a solution, suggests that the solution is not sufficiently well implemented. There's nothing in the UI to suggest that a long-press does anything, and the requirement to edit every highlight to capture trailing punctuation isn't a good experience.
