### ISSUE TITLE
PocketBook 615 Plus doesn't start

### ISSUE THREAD

**Issue by Arilas** [koreader/koreader#4141]
* KOReader version: any
* Device: PocketBook 615 Plus

#### Issue

Copied and merged `applications` folder. Tried to start it from "Applications" but it's just refreshing System UI without starting.
Tried to find `crash.log` file, but it doesn't created at all.

In "Applications" menu I see icon "@Koreader".

I also tried to add this model to `device.lua`

```lua
-- PocketBook 615 Plus
local PocketBook615 = PocketBook:new{
    isTouchDevice = no,
    hasKeys = yes,
    hasFrontlight = yes,
    display_dpi = 212,
    emu_events_dev = "/var/dev/shm/emu_events",
}
```

And on end tried all possible variants of model definition:
```lua
if codename == "PB615" then
    return PocketBook615
elseif codename == "PocketBook 615" then
    return PocketBook615
elseif codename == "PocketBook 615 Plus" then
    return PocketBook615
-- ...
```

But it doesn't work also

**Comment by chelobaka** [comment]
You need to use PB615W codename to launch KOReader on this device. I wasn't able to use it because joystick keys didn't respond.

**Comment by poire-z** [comment]
A few "615" stuff were added recently with #6481.
Re-open if still not OK.
