### ISSUE TITLE
WIFI list of available always shown on 2nd try, Kobo Glo HD

### ISSUE THREAD

**Issue by luftek** [koreader/koreader#4153]
* KOReader version: v2015.11-1818-g7e68027-2018-08-10 (latest development) 
* Device: Kobo GLO HD N437

#### Issue
List of available wifi hotspots is always shown on 2nd try

#### Steps to reproduce
0. WiFi disconnected/disabled
1. Network -> press on Wi-Fi connection (unchecked at moment) -> press Turn On (prompt message) - (Scanning...) -> only thin grey line is shown (photo)
2. Network -> press on Wi-Fi connection (unchecked at moment) -> press Turn On (prompt message) - (Scanning...) -> shows available wifi hostspots and connect to recognized one

Uncheck Wi-Fi connection and situation repeates

<a href="url"><img src="https://user-images.githubusercontent.com/1379063/43992970-de2a000c-9d86-11e8-9abe-f7e62de9d252.jpg" align="left" height="500"></a>

**Comment by NiLuJe** [comment]
I assume you've never had a WiFI AP stored by Nickel?

Does it still happen if you uncheck "Dismiss Wi-Fi scan popup after connection"?

**Comment by luftek** [comment]
> I assume you've never had a WiFI AP stored by Nickel?

Nickel has same AP stored.

> Does it still happen if you uncheck "Dismiss Wi-Fi scan popup after connection"?
This does not seem to have an effect.

Seems like 1st try enables "HW" and 2nd actually gets to search and list APs.
Seems that when no AP is succesfully selected WIFI  "HW" stays turned on.
Seems that when AP is connected and you disconnect, WIFI "HW" acctually turns off

**Steps to reproduce issue:**
- no AP stored in Nickel, no AP stored in Koreader
- Kobo Start Menu 09 (2018.01.05)
- Wifi is off
- Start Koreader
- try to turn wifi ON
- scanning and not succesful (shows wifi turned off)
- grey line
- try again shows AP list

**Steps when issue** NOT  **present:**
- no AP stored in Nickel, no AP stored in Koreader
- Kobo Start Menu 09 (2018.01.05)
- Wifi is on, but not connected to AP (wifi -> wifi ap scan.sh)
- Start Koreader
- list shows on first try

**Some other thing:**
- Kobo Start Menu 09 (2018.01.05)
- Wifi is off
- start koreader
- try to turn on wifi
- scanning and not succesful (shows wifi turned off)
- exit koreader
- asks me to turn off wifi

When I exit Koreader it asks me to turn it off
Wifi should already be off? I did not select AP because list of AP was not available

**Comment by luftek** [comment]
Probabaly something in https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua

Will check if I can find something timeout related.

**Comment by NiLuJe** [comment]
You're not even supposed to see the AP list if you have an AP stored in Nickel (with the option I mentioned in its default state, i.e., checked).

And I'm confused, because you mention having that AP stored in Nickel, and then explicitly state not having it stored anywhere in your step-by-step recap :?

**Comment by NiLuJe** [comment]
As for step 3, err, what? What's asking you to turn WiFi off?

AFAIK, that's not KOReader, we don't care about the WiFi state on exit (and when we do, we silently kill it).

**Comment by luftek** [comment]
> What Kobo FW are you on? 

4.8.11073 which suits your desc. of 4.7+

> Does KSM9>wifi>"wifi ap scan.sh" show APs ?

No, not even on 2nd try. It just changes WIFI state to enabled.

Ok, thank you explanation! Closing for now.
I managed to connect over USBNet and SSH so I can try some things.

**Comment by poire-z** [comment]
I spent a few hours trying to understand why it didn't work... without any luck.
So let us know if you find out :)

@cramoisi : no problem with wifi with your GloHD (which FW version?)
Really no problem with wifi in ksm or koreader on other Kobo devives like KA1 with FW > 4.8?

**Comment by NiLuJe** [comment]
@poire-z : Huh, yeah, strange, I definitely have a populated AP scan popup on 4.8/4.9 with a Mk5 here...

**Comment by cramoisi** [comment]
yup, I reproduced it on my gloHD with KFmon FW 4.8.10956. I don't have my KA1 on my right now.

**Comment by luftek** [comment]
I used ssh and sshfs with USBnet for few hours. It is all new (linux, bash and lua syntax) to me. Do have a slight overview how things work, but don't have the skill, knowledge do degub low level https://github.com/koreader/lj-wpaclient for now.

Downgraded FW to one which shows available networks on first try.

I don't like there is no differentiation between: wifi enabled, connected to ap, "internet" accessible.
But, it is an ereader
Thank you for all hard work! Due to Koreader and KSM I use it more and bought it in the first place

**Comment by cramoisi** [comment]
after the first try, a grey bar displayed onscreen : 

![filemanager_2018-aug-12_193314](https://user-images.githubusercontent.com/28014131/44006274-f0698944-9e81-11e8-94f7-d0fd320cd1aa.png)

**Comment by luftek** [comment]
Jup on first try. Return from function WpaClient.__index:getScanResults()  is only 
**bssid / frequency / signal level / flags / ssid**
which is a header, however wpa_cli repors that (if AP previously saved) connection to saved AP was established

**Comment by worldexplorer** [comment]
I'm using kobo glo hd (N437); no issues whatsoever with wifi inside of koreader v2018.12-31-gf6743a4_2018-12-28 (mentioned as "Installed: 201812000031" in OTA update popup). Upgraded everything 2 weeks ago (probably the sequence of updates matter, in your case):
1) nickel (from a 1.5 years old version of firmware) to "4.12.12111 (13a6961059, 12/11/18)";
2) kobo start menu 08 to 09;
3) installed plato for the first time (and it connects okay to the same home wifi as koreader and nickel), although I have no idea how can I use wifi under plato;
4) koreader from one nightly / dev build to another (I didn't catch which to which , but no issues with browsing wiki / downloading wiki pages to EPUB)

**Comment by cramoisi** [comment]
@worldexplorer : could you try to go to nickel, register your wifi there, and try again in koreader after a reboot ? (it solves the issue for me)

**Comment by worldexplorer** [comment]
> @worldexplorer : could you try to go to nickel, register your wifi there, and try again in koreader after a reboot ? (it solves the issue for me - but I won't have access to my gloHD before 2 weeks)

I created a new network named "0xff2" on my cellphone, connected in nickel, checked the updates from nickel top menu, got "Sync complete" (so that the new wifi works in nickel); turned off, 10 seconds, turned on, ksm09, got "usbnet ip: 192.168.2.101, wifi ip: was not available" on the top, "start koreader" quickly (otherwize nickel will boot again - default boot into nickel by timeout is smth new in ksm09), top menu > gear icon > Network info > "IP: 192.168.43.172, SSID: 0xff2, Gateway ping successfull". Wifi connection is ticked, Automatically restore wifi connection after resume is ticked, Action when wifi is off: turn on, Dismiss wifi scan popup after connection is ticked

**Comment by cramoisi** [comment]
@worldexplorer : I don't know your use of KSM09, but this very problem doesn't happen with @NiLuJe 's KFMon so perhaps you could switch to it ?

**Comment by worldexplorer** [comment]
> @worldexplorer : I don't know your use of KSM09, but this very problem doesn't happen with @NiLuJe 's KFMon so perhaps you could switch to it ?

I didn't complain that I have a problem :) I said I have no problems at all with wifi, just as another opinion  and side comment on how wifi looks fine on my device, inside nickel and inside koreader. I just tested what you asked me to test :) did you mean something else? we were not solving my issue - I don't have any with wifi :) I just found this random issue in the search and decided to add my 2 cents if you lack of devices to test on...

my use of KSM 09 is: I installed it to be able to launch koreader as it was intended to :) the "kobo start menu" on boot offers me to "continue" to nickel, or koreader, or plato - nothing else

**Comment by cramoisi** [comment]
I should not reading thread when i'm sick :)
