### ISSUE TITLE
Serve code over HTTPS

### ISSUE THREAD

**Issue by alethiophile** [koreader/koreader#4158]
* KOReader version: n/a
* Device: n/a

#### Issue

As it stands, both the nightly builds from the build.koreader.rocks server and the OTA updates from ota.koreader.rocks are served over plain HTTP.

Nowadays, serving runnable code over unencrypted connections is highly contraindicated; it's now easy to get an intercepting proxy server from as little as a host on the same LAN, and software to transparently intercept and substitute files served over HTTP is readily available. For code that will be run on a client's device, using a protocol with integrity verification, such as HTTPS, is a basic security measure. It's also now easy to set up HTTPS on normal servers, given the wide availability of free certificates from e.g. LetsEncrypt.

This is obviously not something I can submit code for, but it's quickly approaching the baseline of security for any code-distribution channel; distributing builds over unencrypted HTTP puts the current servers notably in the lower end of the distribution with respect to security precautions, and this will only get worse as time goes on.

**Comment by NiLuJe** [comment]
`zsync` doesn't support HTTPS.
