### ISSUE TITLE
TOC clicks lead to wrong pages for some djvu files (1 such file uploaded)

### ISSUE THREAD

**Issue by okobo** [koreader/koreader#4161]
* KOReader version: koreader-beta-20180729
* Device: Kobo Aura one and Kobo Glow HD

#### Issue
For some djvu files, a click to a table-of-content (TOC) entry leads to an incorrect page, while the same file works perfectly with 4 other djvu viewing programs (both windows and linux). I have reported the same problem before and it was reported to have been fixed. But problems remain as far as I can tell.
#### Steps to reproduce
Open the uploaded djvu file and click an TOC entry.
[Barford-Experimental.measurements-precision,error.and.truth.2e.Wiley.1985.168.djvu.zip](https://github.com/koreader/koreader/files/2287648/Barford-Experimental.measurements-precision.error.and.truth.2e.Wiley.1985.168.djvu.zip)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Issues in question: 
https://github.com/koreader/koreader/issues/2242
https://github.com/koreader/koreader-base/pull/456

**Comment by Frenzie** [comment]
Alright, closing then. :)
