### ISSUE TITLE
Lua-http installation (as dependency), luarocks +cross compile +arm

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#4163]
Topic extracted from #3516
As this is a bigger topic than expected,so extracting. 

Dry - run trying to cross compile for arm with lua rocks, check how to do it (if possible?) before it get committed. 

First command I tried on my Ubuntu 18.04 was
`$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" CFLAGS="-I/usr/include/x86_64-linux-gnu -I/usr/include/lua5.3" --local`

But it was incorrect. 

based on [liblua5.1-0-dev: lua-deb-multiarch.h not found when compiling source including lua.h](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=682183) I did:
```
sudo ln -s /usr/include/x86_64-linux-gnu/lua5.1-deb-multiarch.h /usr/include/lua5.1/
pkg-config --cflags lua5.1
``` 

(last one may not be needed)
and again (with less option command):
`$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" --local`

it worked, some libs were generated, but it brings another errors that I tried to workaround:
```
sudo mkdir -p /usr/include/lua5.1/openssl
sudo ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/lua5.1/openssl/opensslconf.h
```
it was unsuccessfull yet, but some files where compiled:
```
$  find ~/.luarocks -iname *.so | xargs file
/home/marcin/.luarocks/lib/lua/5.1/bit32.so:           ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=c6418084a59a68ac2b684f203ebb35c106f13b8e, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/utf8.so:   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=0863d4d3088523bb8047003d2f2f4c58f03a0f3d, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/string.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=6382f67fef06427d20e537e9f6a6334f86dc71e3, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/table.so:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=e676ed490000941311053c3b6c828f628b13af0b, not stripped
```
_Do those files look good?_ Am I on the right way? 

tring to run (e.g bit32.so) on my amd64 PC gives error `Can't run binnary file: Uncorrect executable format` (my quick translation to english)

next workaround was
`sudo ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/`

Error `/usr/lib/x86_64-linux-gnu/libssl.so: file not recognized: File format not recognized` [arm-linux-gnueabi-gcc_with-ln-workarounds.txt](https://github.com/koreader/koreader/files/2290574/arm-linux-gnueabi-gcc_with-ln-workarounds.txt)

```
$ file /usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so: symbolic link to libssl.so.1.1
marcin@ubuntu:~$ file /usr/lib/x86_64-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so.1.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9787ff1fffe8d82268d89f6bfa3af07b3e9d140f, stripped
```
this file should be from ARM to make compile, right?

I also did some quick checks for https://github.com/dockcross/dockcross but at glance I saw no benefits over what I'm doing now

**Comment by mwoz123** [comment]
Move one step futher:

- downloaded [debian libssl ARM](https://packages.debian.org/jessie-backports/armhf/libssl1.0.0/download) and extracted  
- renamed `ibcrypto.so.* -> `libcrypto.so` and libssl.so.* -> `libssl.so`
- copy to `libcrypto.so` and `libssl.so` to `/usr/arm-linux-gnueabi/lib`
- succesfully build `cqueues` with command:
`luarocks build cqueues CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" LUA_LIBDIR="/usr/arm-linux-gnueabi/lib" --local` 
result:
```
$ find ~/.luarocks -iname *cque*.so | xargs file
/home/marcin/.luarocks/lib/lua/5.1/_cqueues.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=bd5a79668b914732857c14f1b8447225e2ea92cc, with debug_info, not stripped
```
- after that I rebuild `lua-http` with command:
`$ luarocks build http CC="arm-linux-gnueabi-gcc" LD="arm-linux-gnueabi-gcc" LUA_LIBDIR="/usr/arm-linux-gnueabi/lib" --local`

results:
```
$ find ~/.luarocks -iname *.so | xargs file/home/marcin/.luarocks/lib/lua/5.1/bit32.so:           ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=c6418084a59a68ac2b684f203ebb35c106f13b8e, not stripped
/home/marcin/.luarocks/lib/lua/5.1/_openssl.so:        ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=e5f02bedebd6c9c11a768b7f18abd5dedb6e839f, not stripped
/home/marcin/.luarocks/lib/lua/5.1/_cqueues.so:        ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=bd5a79668b914732857c14f1b8447225e2ea92cc, with debug_info, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/utf8.so:   ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=0863d4d3088523bb8047003d2f2f4c58f03a0f3d, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/string.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=6382f67fef06427d20e537e9f6a6334f86dc71e3, not stripped
/home/marcin/.luarocks/lib/lua/5.1/compat53/table.so:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=e676ed490000941311053c3b6c828f628b13af0b, not stripped
/home/marcin/.luarocks/lib/lua/5.1/lpeg.so:            ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=12d27790fd5c40362291ea739f854dea0a3cbb3a, not stripped
```

Should they be ok to work with Koreader lua???

(build using lua 5.1 - which lua version Koreader has?)  ?

If yes I'll try to work on automation the build process so it could be commited to koreader.

**Comment by NiLuJe** [comment]
LuaJIT, which is roughly 5.1 + a few 5.2 features, but I don't know how LuaRocks prefixes it.

**Comment by Frenzie** [comment]
> Should they be ok to work with Koreader lua???

For testing, yes. Anything real should of course be more like this: https://github.com/koreader/virdevenv/blob/13c37dcc21d6e8acffe53e0d88e2a6e3562bd169/docker/ubuntu/baseimage/install_luarocks.sh

**Comment by Frenzie** [comment]
That's a given, but I mean not some random luarocks from Ubuntu.

**Comment by Frenzie** [comment]
Closing this now, cross-ref to https://github.com/koreader/koreader-base/issues/594
