### ISSUE TITLE
Koreader thinks "儿" is two characters

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#4164]
* KOReader version: koreader-beta-20180729
* Device: Android/BOOX NoteS

#### Issue
Koreader thinks "儿" is two characters

**Comment by zaoqi** [comment]
@Frenzie It is in some pdf.

**Comment by Frenzie** [comment]
I can't confirm. I created this `text.xhtml` document (rendered by MuPDF) and it's treated as one character:

```xml
<html>
  <p>Koreader thinks &quot; 儿 &quot; is two characters · Issue #4164 · koreader/koreader</p>
</html>
```

Please provide more information if this is still an issue.

**Comment by zaoqi** [comment]
@Frenzie It was a scanned version of pdf

**Comment by zaoqi** [comment]
@Frenzie It was a scanned version of pdf.
Converting a png to a pdf may be possible to reproduce it

**Comment by zaoqi** [comment]
@Frenzie It was a scanned version of pdf.
Converting a png to a pdf and enable `Reflow` may be possible to reproduce it

**Comment by Frenzie** [comment]
That means it's either a mistake in the text layer or an "OCR is very hard" problem. Could you please try to include such vital information in the future?

**Comment by zaoqi** [comment]
How to reopen this issue?

**Comment by Frenzie** [comment]
If it's an OCR issue that means there's nothing that can be done, except to make sure you're using the 3.04 data files from https://github.com/tesseract-ocr/tesseract/wiki/Data-Files#data-files-for-version-304305 OCR results can be improved by preprocessing the document on your computer to reduce scanning noise but of course in that case you should also perform the OCR on your computer. 

I notice [the wiki](https://github.com/koreader/koreader/wiki/Dictionary-support#dictionary-lookups-in-scanned-pages) is pointing to slightly older data files. I'll update that now.
