### ISSUE TITLE
Q: touchmenu.lua, closeMenu()

### ISSUE THREAD

**Issue by luftek** [koreader/koreader#4170]
* KOReader version: v2015.11-1828-g6f2368e_2018-08-17
* Device: Kobo Glo HD

#### Question
Is all that closing of menu really necessary?

Rant:
Did not check "git blame", to know when was it added and why, but in functions onMenuHold and onMenuSelect I find it very annoying.

**Comment by Frenzie** [comment]
I agree. What do you guys think?

**Comment by poire-z** [comment]
(Bit generic comments ^ :) some examples may be?)

I remember I had occasionally been bothered by menu closing when taping/holding, and having to get again to where I was. But looking around now, I can't really find something bothering :) What did you find?

It usually behaves well: closing when taping on an action thing, NOT closing when taping on a checkboxed item. Would you like the menu to stay open when you tap on Dict lookup, Full text search, Skim To, Table of content, Book status ?

There are more chances for that being bothering with Hold.
I added something to prevent the closing in https://github.com/koreader/koreader/commit/a9905c51294cd83893e2acfdf8d510c4df35977b#diff-200e39a7a76e64783d1d2c16a6d7c01e (used when hold in `Fonts>`, `Hyphenation>`, `Style tweaks>` - I guess where I found the closing bothering :)

**Comment by Frenzie** [comment]
> Would you like the menu to stay open when you tap on Dict lookup, Full text search, Skim To, Table of content, Book status ?

Nah, not on those, but I don't think I've ever thought that it'd be nice if the menu closed more than it does.

**Comment by KenMaltby** [comment]
I am not seeing where there is a noticeable problem.  A better example might help.  To me it seems the menus are usually staying up while I was deciding to use them and mostly only closing when I tell them to.  The Wi-Fi interactions might be an exception, but much of those are simple notifications.  (A notification duration setting might help those wanting more time to read them. )

**Comment by NiLuJe** [comment]
Yeah, nothing really ever struck me as annoying on that front either?

**Comment by luftek** [comment]
I am checking what to do with WIFI on latest Nickel FW I find it annoying that top menu closes on me when:
- try to check for new FW version and wifi is not turned on at the time
- ssh (which is a plugin) turn on, turn off
- network info, network proxy, 
- few plugins where settings must be done before use
and you must then return to the same menu 

Will check how to add this to advances settings, as user option. I rather tap one more time than lose context which led to InfoMessage or SelectionMenu

Maybe I should check and present all situations (statistics)

**Comment by poire-z** [comment]
OK, I would agree with you about the cases you mentionned. I think most others are fine with menu closing, except the one you mentionned, network, settings...
So, rather than a user option that you will hate for the other cases, I guess it'd be just better to add an option to menu items `keep_menu_open=true` where it makes sense, and just have onMenuSelect and onMenuHold test for this to not do the close if this option is true.
