### ISSUE TITLE
Q: letter 'Å'?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4171]
I can't find the letter 'Å' ('å') in the keyboards. (https://en.wikipedia.org/wiki/%C3%85)

When I tap the 'Äéß'-button I can find 'Ä' and 'Ö' but not 'Å'. (The swedish alphabet ends with Å, Ä, Ö)

If I want to add the letter myself, how can I do that? I have found this folder: koreader/frontend/ui/data/keyboardlayouts/

Thanks!

**Comment by Frenzie** [comment]
It probably makes the most sense to copy the standard layout and adjust it into a Swedish one. Pinging @robert00s

**Comment by Frenzie** [comment]
If you mean lowercase and uppercase then yes, that's necessary… and otherwise I don't know what you're talking about. :-)

**Comment by poire-z** [comment]
![image](https://user-images.githubusercontent.com/24273478/44308679-5e87c200-a3ba-11e8-9adc-68b3681cf90b.png)

**Comment by Frenzie** [comment]
Oh, I didn't notice those in the top right, haha. Yes, that's pretty weird.

**Comment by NiLuJe** [comment]
(Also applies to their lowercase variants, though ;)).

**Comment by poire-z** [comment]
Indeed, didn't even notice :)
So, @gerhaher , you found yourself 2 slots for new letters. You got to decide which should be the newcomers. (And make your first PR by fixing all the files in /keyboardlayout/ that have these duplicates? :)

**Comment by gerhaher** [comment]
> So, @gerhaher , you found yourself 2 slots for new letters. You got to decide which should be the newcomers. (And make your first PR by fixing all the files in /keyboardlayout/ that have these duplicates? :) (edit: std.lua is the default/fallback keyboard one that you are probably using)

Thanks for giving me the honour. But changing the file is probably all I am capable to do.  :)

First I added Å (å).
And then I moved Ø (ø) from another place. In its place I put Ã (ã). 

I also found Ë (ë) in 3 places. I hope you don't mind that I changed two of them to Ũ (ũ) and Ĩ (ĩ), so that anyone who wants can write "Ngũgĩ wa Thiong'o" :-). 

Here it is: [std.zip](https://github.com/koreader/koreader/files/2300573/std.zip)
