### ISSUE TITLE
standby time of the device

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#4179]
* KOReader version:
* Device:kobo aura one

hello, is it possible to set the standby time of the device?
I want to set this sleep timer to 15 minutes.

**Comment by poire-z** [comment]
The default is 60 minutes, but you can can change it by adding into your `settings.reader.lua`:
```lua
    ["auto_suspend_timeout_seconds"] = 900,
```
(make a backup of the file, beware the , at the end, put that line after a similar simple one, and not at the end of the file, etc...)

I guess this should be in the menu, may be in the new `Device>` submenu (it's dealt with by the autosuspend plugin, kobo & sdl only).

**Comment by pazos** [comment]
>  it would be interesting to have a setting option in a menu to choose the time to sleep and how to reactivate the reader (touch, slide etc ...)

I like the idea of making the autosuspend time settable from gui :+1:. 

Sadly once suspended the only way to reactivate the reader is pressing the power button.
