### ISSUE TITLE
Epub-file created from html with ebook-convert shows only two pages

### ISSUE THREAD

**Issue by rtega** [koreader/koreader#4180]
* KOReader version: v2015.11-1800-g0924b57_2018-07-29
* Device: kobo glo hd

#### Issue
When I open up an epub-file converted from an html-file with ebook-convert it shows only two pages.

#### Steps to reproduce
See attached files
[musashi.zip](https://github.com/koreader/koreader/files/2305614/musashi.zip)

I can read this file in all other epub-readers that I know of. If I open up the file in sigil and save it it opens ok in koreader and I can read all content.

**Comment by poire-z** [comment]
There are double spaces in the filenames of the indivual HTML files in the epub, and crengine decides, while parsing the content.opf XML that describes the EPUB structure, to trim the double spaces, so in the end, the referenced filenames (trimmed) are not found in the ZIP file, so it displays only the title page (which is the only one named simply titlepage.xhtml).

Commenting out the `attrvalue.trimDoubleSpaces(false,false,false);` at https://github.com/koreader/crengine/blob/c02f59701128cef0cbc34fefeed126ce36260e37/crengine/src/lvxml.cpp#L3112-L3113:
```c
                attrvalue.trimDoubleSpaces(false,false,false);
                m_callback->OnAttribute(attrns.c_str(), attrname.c_str(), attrvalue.c_str());
```
makes your book display fine.

String functions signatures:
```c
    /// trims spaces at beginning and end of string
    lString16 & trim();
    /// trims duplicate space characters inside string and (optionally) at end and beginning of string
    lString16 & trimDoubleSpaces( bool allowStartSpace, bool allowEndSpace, bool removeEolHyphens=false );
```
Dunno if attribute values read from the XML text should really have their double spaces trimmed, and/or if they should go thru trim() only to remove only spaces at start & end, of if even not :) Or if there should be specific handling depending on the attribute name (`href` vs others, like `class` where we may want to trim double spaces if we don't want to go see other specific attribute parsing codes to be sure they would work with double spaces kept.....)?
@Frenzie ?

**Comment by rtega** [comment]
Are you sure this is the only reason? I see the same filenames in both files of which only the one converted with sigil works. I'll upload a working example saved in sigil and a not working example: [both.zip](https://github.com/koreader/koreader/files/2306107/both.zip)

**Comment by poire-z** [comment]
In the one that works, the double spaces are propertly url-encoded (so, preserved) in the content.opf XML:
```xml
  <manifest>
    <item href="Images/cover_image.jpg" id="cover" media-type="image/jpeg" />
    <item href="Text/Ji%20Chuan%20%20Ying%20Zhi%20%20-%20Gong%20Ben%20Wu%20Zang%20%20-%2002%20Di%20noJuan%20_split_000.html" id="html17" media-type="application/xhtml+xml" />
    <item href="Text/Ji%20Chuan%20%20Ying%20Zhi%20%20-%20Gong%20Ben%20Wu%20Zang%20%20-%2002%20Di%20noJuan%20_split_001.html" id="html16" media-type="application/xhtml+xml" />
```
In the one that does not work:
```xml
  <manifest>
    <item href="cover_image.jpg" id="cover" media-type="image/jpeg"/>
    <item href="Ji Chuan  Ying Zhi  - Gong Ben Wu Zang  - 02 Di noJuan _split_000.html" id="html17" media-type="application/xhtml+xml"/>
    <item href="Ji Chuan  Ying Zhi  - Gong Ben Wu Zang  - 02 Di noJuan _split_001.html" id="html16" media-type="application/xhtml+xml"/>
```

So, I guess Sigil did the right thing ? and we don't have to support tools that don't do the right thing ? :)

**Comment by poire-z** [comment]
Well, crengine seems to do the right thing according to the specs https://www.w3.org/TR/xml11/#AVNormalize :

_For a white space character (#x20, #xD, #xA, #x9), append a space character (#x20) to the normalized value.
[...]
If the attribute type is not CDATA, then the XML processor MUST further process the normalized attribute value by discarding any leading and trailing space (#x20) characters, and by replacing sequences of space (#x20) characters by a single space (#x20) character._

I didn't try to understand the sentence that follows that :):
_Note that if the unnormalized attribute value contains a character reference to a white space character other than space (#x20), the normalized value contains the referenced character itself (#xD, #xA or #x9). This contrasts with the case where the unnormalized value contains a white space character (not a reference), which is replaced with a space character (#x20) in the normalized value and also contrasts with the case where the unnormalized value contains an entity reference whose replacement text contains a white space character; being recursively processed, the white space character is replaced with a space character (#x20) in the normalized value._

**Comment by rtega** [comment]
Hmmm, I see, better poke the people at calibre for this?

**Comment by rtega** [comment]
I filed a bug against calibre.

**Comment by poire-z** [comment]
> I can read this file in all other epub-readers that I know of.

Really? Can't you find at least one that does not like that book either :) so we're not alone in the _tight-ass-adhering-to-specs-by-using-a-XML-parser-for-reading-opf_ camp ?

(I don't really say a simple way to be more relaxed when parsing href in the opf file... we're just using everywhere the XML Parser that does its thing)

**Comment by rtega** [comment]
Ok, a list:

- fbreader: no problem whatsoever
- calibre: no problem whatsoever
- okular: shows all text but the links to the chapters don't work. Links don't work with the sigil-corrected epub either
- lucidor: no problem whatsoever

didn't try any others.

**Comment by rtega** [comment]
https://bugs.launchpad.net/calibre/+bug/1788187

**Comment by Frenzie** [comment]
While technically incorrect as per XML, I'd say we should also check the EPUB spec for this manifest thing.

**Comment by poire-z** [comment]
Nothing special said about manifest.
But http://www.idpf.org/epub/31/spec/epub-spec.html says:
```
4.3 XML Conformance
Any Publication Resource that is an XML-Based Media Type must meet the following constraints:
       It must be a conformant XML 1.0 Document as defined in Conformance of Documents
```
So, closing as I see no easy way to be more relaxed.

**Comment by rtega** [comment]
I can confirm that the new calibre released today solves this problem. Thanks for looking into this.
