### ISSUE TITLE
Hardware buttons

### ISSUE THREAD

**Issue by serarck** [koreader/koreader#4182]
* KOReader version: 1832
* Device: Kindle Voyage (FW 5.9.7)

Hello, is it possible to implement the support of hardware buttons (page turning) in the Voyage?

**Comment by NiLuJe** [comment]
We're already doing as much as we can, the underlying OS has a quirky way of inhibiting hardware events for the buttons in some obscure circumstances.

**Comment by NiLuJe** [comment]
AFAICT, this behavior is specific to the Voyage, things got better on the Oasis.

**Comment by NiLuJe** [comment]
(Untagging as wontfix because , who knows, someone with the actual device might figure it out one day).
