### ISSUE TITLE
KOReader does not take full advantage of the frontlight on kobo devices by default

### ISSUE THREAD

**Issue by AndreasTPC** [koreader/koreader#4186]
I thought the brightness of my Kobo Aura One when reading in complete darkness was too bright, to the point where it was uncomfortable. I was curious if this was a hardware limitation or just a software one, so I started to mess around with the files in /sys/class/backlight on the device, and found that I was able to get the output of the frontlight much lower than KOReader will do by default.

With the default koreader settings the lowest you can go, at 1% brightness in the ui with warmth off, is the brightness parameter (that accepts values from 0 to 255) set to 54. When in daylight 54 looks about the same as if the backlight is off, but when you're in a dark room setting it lower than that makes a big difference. You can mess around with the amplification and offset settings in koreader, but that isn't very user friendly, you pretty much have to read the source code to understand what the effect will be from changing those settings.

I think the default koreader settings should be such that 1% brightness in the UI maps to the lowest the hardware can do, and 100% brightness in the UI maps to the highest the hardware will go, so the user can easily take advantage of the full capabilities of the hardware. The formula for translating the 0-100 brightness in koreader's ui to the hardware parameters will probably need to be changed to accomplish this.

Another thing to note is that KOReader will set the bl_power parameter of the frontlight to either 31 for on or 0 for off. My testing showed that setting it to values in between does have an effect. For white light setting it to something lower than 31 lowers the brightness, meaning that the hardware actually has 8192 brightness steps rather than the 255 it initially appears to have. Not that we need more brightness steps, but we might want to evaluate if just leaving this setting at the highest value possible is the best option, maybe we should scale it with brightness as well.

I also tested changing the bl_power parameter with the red frontlight, and found that I was able to get hues of red that looked nicer and was more comfortable to read with than the harsh red you get by leaving it at 31, so the natural light setting could possibly be vastly improved by messing with this value.

**Comment by cramoisi** [comment]
@AndreasTPC : while waiting for the enhancement, do you have some offset settings to share with us ? :-)

**Comment by AndreasTPC** [comment]
@cramoisi Sure, try these settings for white light: amplification 0.0255, offset 0, exponent 1. That makes 0-100 brightness in the koreader UI map linearly to 0-255 brightness on the hardware. I've only tested it with warmth set to 0, it might do funky things if you try to use the warmth feature, I'm not sure.

It's still not quite the lowest the hardware can go since this won't change the bl_power setting, but it's a lot lower than you can go with the default settings. I think I'm gonna see about making a patch that changes the formula to something that is more like how I'd like it, I'll post it here maybe tonight or tomorrow.

**Comment by laurentbe** [comment]
FYI: I only use the light when reading in the total darkness. 
Here are my night reading settings to get the low light and rather pink color:
White: 1 offset: 0
Red: 40  offset: 5
Green: 12.9 offset: -49.8
Exponent: 0.17
Natural light: 99 (100 would be red)
General Light set to 1%
