### ISSUE TITLE
Crash using calibre wireless connection on 64-bit linux 

### ISSUE THREAD

**Issue by shermp** [koreader/koreader#4187]
* Koreader v2015.11-1837-g8f865796_2018-08-23 (self-compiled)
* Koreader v2015.11-1800-g0924b57_2018-07-29 (AppImage)

* Device: Ubuntu MATE 18.04 x86_64 (Virtualbox VM)

#### Issue
The emulator crashes when attempting connect to Calibre using the "calibre wireless connection" functionality.

Crash does not occur in Ubuntu MATE 18.04 i386.

#### Steps to reproduce
Run a 64-bit version of linux.
Start the "calibre wireless connection" from the koreader menu. Select the inbox. Emulator then crashes.

##### Traceback
```
...
ffi.load: libs/libczmq.so.1
ffi.load: libs/libzmq.so.4
ffi.load: libs/libczmq.so.1
08/29/18-16:23:47 WARN  connect to endpoint tcp://192.168.1.20:9090
./luajit: frontend/ui/message/streammessagequeue.lua:28: bad argument #4 to 'zmq_getsockopt' (cannot convert 'uint64_t [1]' to 'unsigned int *')
stack traceback:
	[C]: in function 'zmq_getsockopt'
	frontend/ui/message/streammessagequeue.lua:28: in function 'start'
	plugins/calibrecompanion.koplugin/main.lua:115: in function 'initCalibreMQ'
	plugins/calibrecompanion.koplugin/main.lua:133: in function 'onConfirm'
	frontend/ui/downloadmgr.lua:52: in function 'onConfirm'
	frontend/ui/widget/pathchooser.lua:131: in function 'callback'
	frontend/ui/widget/button.lua:201: in function 'action'
	frontend/ui/uimanager.lua:597: in function '_checkTasks'
	frontend/ui/uimanager.lua:818: in function 'handleInput'
	frontend/ui/uimanager.lua:904: in function 'run'
	./reader.lua:195: in main chunk
	[C]: at 0x5636682dc050
```

**Comment by Frenzie** [comment]
Pinging @niluje who played around with some of this recently.

**Comment by NiLuJe** [comment]
Yeah, we're 3 or 4 API levels behind øMQ mainline, so all of this needs a good dusting off.

**Comment by NiLuJe** [comment]
But in this case, that's a data-type mismatch, will band-aid it.
