### ISSUE TITLE
Q: Koreader for Pocketbook as standalone app

### ISSUE THREAD

**Issue by spanceac** [koreader/koreader#4191]
* KOReader version: v2015.11-1803-ge37c345_2018-07-29
* Device: Pocketbook Basic 3

Hi,

I have this PB Basic 3 which had its card corrupted after I copied ~100 books on it. Now it fails to start the native reader application.
I investigated the main application called "pocketbook" with strace and it's blocked waiting to read from a pipe where no one writes.

I want to run Koreader on it as the main application. Is this possible if the main application doesn't run anymore?

I copied the koreader release for PB from here https://github.com/koreader/koreader/releases.

Since my PB doesn't seem to be recognized I also added the device type in "_koreader/frontend/device/pocketbook/device.lua_" with this diff:

```
--- a/frontend/device/pocketbook/device.lua
+++ b/frontend/device/pocketbook/device.lua
@@ -203,6 +203,16 @@ local PocketBook740 = PocketBook:new{
     emu_events_dev = "/var/dev/shm/emu_events",
 }
 
+-- PocketBook Basic 3
+local PocketBook614 = PocketBook:new{
+    isTouchDevice = no,
+    hasKeys = yes,
+    hasFrontlight = no,
+    isAlwaysPortrait = yes,
+    display_dpi = 166,
+    emu_events_dev = "/var/dev/shm/emu_events",
+}
+
 logger.info('SoftwareVersion: ', PocketBook:getSoftwareVersion())
 
 local codename = PocketBook:getDeviceModel()
@@ -219,6 +229,8 @@ elseif codename == "PocketBook 623" then
     return PocketBook623
 elseif codename == "PB740" then
     return PocketBook740
+elseif codename == "PocketBook 614W" then
+    return PocketBook614
 else
     error("unrecognized PocketBook model " .. codename)
 end
```

When I run the application, it seems to start but nothing appears on the screen.

The crashlog reports the following:
```
/mnt/secure/koreader # cat koreader/crash.log 
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/07/00-20:50:31
 [*] Version: v2015.11-1803-ge37c345_2018-07-29

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
ffi.load: inkview
01/07/00-20:50:31 INFO  SoftwareVersion:  U614-2.5.17.964
Atached mp shm: id 0 addr 4202e000 size 21648
----------------> USING A2PLUS MODE <-----------------
Atached mqueue: id 8001
```

Please let me know if there's something that I can do to make it run.

Thank you!

**Comment by Frenzie** [comment]
Could you run it with the `-d` (debug) flag?

I don't know the specifics of Pocketbook but if you know where the file is located you can probably just add it to this line:

https://github.com/koreader/koreader/blob/4320359b25f88c1148575af328a33ca746ca1d2a/platform/pocketbook/koreader.app#L47

**Comment by spanceac** [comment]
I added the ```-d``` flag but with no effect. 

The crash.log looks exactly as what I pasted in the first message.

Checking with ps if the reader.lua is started with the -d flag and it is:
```
  180 root      2412 S    {koreader.app} /bin/sh ./koreader.app
  184 root     33764 S    {reader.lua} ./luajit ./reader.lua /mnt/ext1/ -d
```

**Comment by NiLuJe** [comment]
`./reader.lua -d "${args}"`

Can't remember how foolproof our argument parsing is, so, better be safe than sorry ;).

**Comment by Frenzie** [comment]
Yeah, that wouldn't work. Arguments first, then location.

**Comment by spanceac** [comment]
Hi,

So I put the ```-d``` before the location but the crash.log file contains the same info as in my first post.

This is the ```ps``` result:
```
  135 root      2412 S    {koreader.app} /bin/sh ./koreader.app
  139 root     33764 S    {reader.lua} ./luajit ./reader.lua -d /mnt/ext1/
```
