### ISSUE TITLE
width / height confusion on PocketBook Color Lux; screen is stretched and always rotated/landscape

### ISSUE THREAD

**Issue by thomasrebele** [koreader/koreader#4193]
* KOReader version: release koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1800-g0924b57_2018-07-29.zip
* Device: Pocketbook Color Lux

#### Issue

I got KOReader running on my device, however, the screen starts in landscape, upside down.
The screen has the wrong aspect ratio, i.e., x is stretched by 2, y is stretched by 0.5.
A similar issue was described in #3687. As recommended there, I tried self.screen:setRotationMode(x) after Generic.init(self) with x=0, x=1, x=2, but that doesn't affect the screen.

Setting isAlwaysPortrait = yes only turns around the screen by 180, but doesn't resolve the issue with the wrong aspect ratio.

How can I fix the aspect ratio or turn the screen by 90°?

#### Steps to reproduce

- install koreader on Pocketbook Color Lux
- extend `frontend/device/pocketbook/device.lua`
```
-- PocketBook Color Lux
local PocketBookColorLux = PocketBook:new{
    isTouchDevice = yes,
    hasKeys = yes,
    hasFrontlight = yes,
    isAlwaysPortrait = no, -- or yes?
    display_dpi = 100,
    emu_events_dev = "/var/dev/shm/emu_events",
}
...
elseif codename == "PocketBook Color Lux" then
	return PocketBookColorLux
```
- start koreader

**Comment by thomasrebele** [comment]
Some pictures to visualize the problem. I hold the reader in portrait format, so the text should be written from left to right, top to bottom in the picture.

`isAlwaysPortrait = no`

![always_portrait_no](https://user-images.githubusercontent.com/1692723/44949785-067ca100-ae39-11e8-90b7-22b9ab1812d9.jpg)

`isAlwaysPortrait = yes`

![always_portrait_yes](https://user-images.githubusercontent.com/1692723/44949791-21e7ac00-ae39-11e8-9a47-39cc692bcf1c.jpg)

**Comment by NiLuJe** [comment]
That looks like w/h are inverted, in addition to it starting in a CCW rotation.

We usually handle inverted w/h somewhat properly, which leads me to think that they're *not* inverted, and only the rotation is unexpected.

What do the log say about the reported fb width/height?

**Comment by NiLuJe** [comment]
That display_dpi is also most likely wrong, which may not be helping. It's going to be at the very least around 212 or 250, maybe even 300.

Old 600x800 devices were already over 150, to give you a frame of reference.

**Comment by thomasrebele** [comment]
Sorry, didn't think that the log was important as it didn't crash.
The relevant lines:

```
09/01/18-13:10:46 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 1800
}
```
(probably isAlwaysPortrait = no),
and
```
09/01/18-13:51:32 INFO  framebuffer resolution: {
    ["h"] = 1800,
    ["w"] = 800
}
(probably isAlwaysPortrait = yes)
```
Here the full log: [crash.log](https://github.com/koreader/koreader/files/2342782/crash.log)

Thanks for the hint with Kobo H2O²r1. Do I need to adjust my configuration with `viewport = Geom:new{x=0, y=0, w=800, h=1800}` ?

About DPI values: I had tried several, with the same result. So I thought that I'll first fix the rotation, and then find out the right DPI.

**Comment by NiLuJe** [comment]
I honestly have no idea what a viewport with inverted w/h will do, probably nothing good, but, hey, who knows ;).

**Comment by thomasrebele** [comment]
# first try
the device crashes with configuration

```
    isAlwaysPortrait = no,
    viewport = Geom:new{x=0, y=0, w=800, h=1800},
```

```
#---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/02/18-00:25:13
 [*] Version: v2015.11-1800-g0924b57_2018-07-29

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
ffi.load: inkview
09/02/18-00:25:13 INFO  SoftwareVersion:  W801.4.1.915
----------------> USING A2PLUS MODE <-----------------
ts: loading default calibration values
ffi.load: inkview
09/02/18-00:25:13 INFO  initializing for device PocketBook
09/02/18-00:25:13 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 1800
}
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
09/02/18-00:25:15 INFO  Loading plugins from directory: plugins
09/02/18-00:25:15 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
09/02/18-00:25:15 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
09/02/18-00:25:15 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
09/02/18-00:25:15 INFO  Plugin  plugins/kobolight.koplugin/main.lua  has been disabled.
09/02/18-00:25:15 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
09/02/18-00:25:15 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin perception_expander at plugins/perceptionexpander.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
09/02/18-00:25:15 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
```

# second try
koreader app crashes with configuration 
```
    isAlwaysPortrait = no,
    viewport = Geom:new{x=0, y=0, w=1800, h=800},
```

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/02/18-00:29:30
 [*] Version: v2015.11-1800-g0924b57_2018-07-29

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
ffi.load: inkview
09/02/18-00:29:30 INFO  SoftwareVersion:  W801.4.1.915
----------------> USING A2PLUS MODE <-----------------
ts: loading default calibration values
ffi.load: inkview
09/02/18-00:29:30 INFO  initializing for device PocketBook
09/02/18-00:29:30 INFO  framebuffer resolution: {
    ["h"] = 800,
    ["w"] = 1800
}
./luajit: ./ffi/framebuffer.lua:157: fb:setViewport() bad viewport
stack traceback:
	[C]: in function 'error'
	./ffi/framebuffer.lua:157: in function 'setViewport'
	frontend/device/generic/device.lua:86: in function 'init'
	frontend/device/pocketbook/device.lua:114: in function 'init'
	frontend/device.lua:39: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/centercontainer.lua:5: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:2: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/confirmbox.lua:21: in main chunk
	[C]: in function 'require'
	./reader.lua:96: in main chunk
	[C]: at 0x0000c059
```

**Comment by thomasrebele** [comment]
if I set `self.screen.native_rotation_mode = self.screen.ORIENTATION_PORTRAIT` then I get the right orientation, however, aspect ratio is still wrong:
![native_rot_portrait](https://user-images.githubusercontent.com/1692723/44953477-1e364280-ae96-11e8-86fa-368bf0154fcf.jpg)

**Comment by thomasrebele** [comment]
if it would just affect the interface, it would be ok. However, books are also stretched:

![native_rot_portrait2](https://user-images.githubusercontent.com/1692723/44955949-3751ea00-aebc-11e8-8f7d-242617399325.jpg)

original PDF: http://www-users.math.umn.edu/~olver/ln_/cv.pdf

**Comment by thomasrebele** [comment]
I just noticed: the aspect ratio of my device is 12cm / 16cm = 0.75
However, the aspect ratio of the framebuffer is 0.44

Maybe it is related to the fact that the PocketBook Color Lux can display color?

**Comment by NiLuJe** [comment]
Not familiar with Triton screens, so I can't say what it should be expecting, and short of adding a bunch of logging of the relevant fb setup info in base/ffi/framebuferr_linux.lua to see what it's *reporting* (which might actually be what it's expecting, because everything is terrible), I'm not quite sure what might be going wrong...

**Comment by thomasrebele** [comment]
These are the values: [framebuffer.txt](https://github.com/koreader/koreader/files/2343761/framebuffer.txt) (please let me know if there's an easy way to print structs with lua)

Strangely, `vinfo.bits_per_pixel = 8`. The resolution of the screen is 600x800, framebuffer size is 1800x600, so every pixel should have three bytes. I might have some time in the following days to look into the issue.

**Comment by thomasrebele** [comment]
I forced a RGB24 framebuffer with `self.bb = BB.new(vinfo.xres, vinfo.yres, BB.TYPE_BBRGB24, self.data, finfo.line_length)`. This solves the aspect ratio issue, and the top menu looks fine:

![fb24_1](https://user-images.githubusercontent.com/1692723/44961160-5b3d1c00-af0c-11e8-8a64-4ed79bf3c4aa.jpg)

However, the bottom menu is messed up (see picture above), as well as some documents (see picture below). Unfortunately no colors :/

![fb24_2](https://user-images.githubusercontent.com/1692723/44961162-6132fd00-af0c-11e8-8855-51e28959a4a4.jpg)

**Comment by poire-z** [comment]
Try adding to the device definition: `hasColorScreen = yes,` (like it's done in `sdl/device.lua` and `android/device.lua`) (and check in the `Screen` menu that `Color rendering` is enabled).

**Comment by NiLuJe** [comment]
@thomasrebele : Ah, progress :).

As @poire-z said, we won't do color unless hasColorScreen = yes is true, so, there's that.

Given the state of this thing, I expect we don't actually know how to do colors *right* for this thing, unfortunately ;D.

I don't think there's a silver bullet for printing structs short of honoring each field's data type, which can be somewhat painful... In this specific instance, you can take inspiration from [FBGrab](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/FBGrab/fbgrab.c).

I don't remember to which extent we trust smem_len & line_length in KOReader, but, clearly, that might need some tweaking here, given the horrendously broken report :D.
Because, yeah, that appears to be 24bpp, *maaaaaaybe* with a twist, or maybe we're screwing things up by trusting vinfo/finfo too much.

**Comment by NiLuJe** [comment]
Random maths brainfart: w & h might well be wrong too, since 600*3 = 1800, okay, but it's still 800 pixels high, so 1800x600 is bonkers.

Try enforcing 24bpp, portrait, and 600x800?

**Comment by NiLuJe** [comment]
Random unrelated remark, since I just saw your edit of the Wiki:

Does enabling [this block of code](https://github.com/koreader/koreader/blob/master/plugins/SSH.koplugin/main.lua#L52-L59) help with the no TTY issues?

**Comment by thomasrebele** [comment]
sorry, my fault, the framebuffer size is 1800x**800**. It seems that we're getting close. I added `hasColorScreen = yes`, and forced 24bpp and 600x800 with 
```
width = 600
height = 800
finfo.line_length = 1824
self.bb = BB.new(width, height, BB.TYPE_BBRGB24, self.data, finfo.line_length)
```

It works quite well ... for the first third of the screen. The other two thirds don't show anything, or show what the previous app showed at this area

![fb24_w600](https://user-images.githubusercontent.com/1692723/45058834-2ced4700-b09a-11e8-9576-59263937d193.jpg)

Increasing width leads to the problem of the above picture. My intuition is that the framebuffer is now correct. Any ideas why the other two thirds are not shown?

- - - 

Thanks for the hint with the TTY problem. Apparently I have not enough rights to execute the second command. The workaround with lsyncd works well enough for the moment.
```
$ mount -t devpts devpts /dev/pts
mount: permission denied (are you root?)
```

**Comment by NiLuJe** [comment]
Hmm, try with `finfo.line_length = 5472`? (Both with width 600 & back to 1800 if all else fails).

(My reasoning being that line_length is supposed to be the amount of bytes in a scaline, ideally aligned to 16 bytes, so 1824 * 3 for 24bpp).

----

True, that only works if we're running as root (which is the case on Kobo) ;).

**Comment by NiLuJe** [comment]
Err, wait, still not used to think in terms of "tony" 600x800 screens.

1824 makes sense for finfo.line_length (608 * 3), so that leaves making sure you're overriding that early enough in base/ffi/framebuffer_linux that it properly affects the mmap size...

**Comment by thomasrebele** [comment]
`finfo.line_length = 1824` seems to be the correct one. Setting it to 5472 for BB.new gives a segmentation fault, an setting it to 3648 fills only every other line on the screen.

The mmap size should be ok. If I multiply its size by 3, the app crashes.

**Comment by thomasrebele** [comment]
I added two foor loops that draw a red rectangle from (190,10) to (210,100) by setting the corresponding bytes of the framebuffer. See left picture. Other tests confirm that the last visible column is x=199. Once however, I saw the picture on the right. I think I switched between the main menu and koreader. I had to force a restart, as the device didn't react after I took the picture.

Is there a "update screen from framebuffer" command?

![drawing](https://user-images.githubusercontent.com/1692723/45079310-7ec1bb80-b0f2-11e8-98b7-83b65165da97.jpg)

**Comment by thomasrebele** [comment]
**Edit:** found the fix. Apparently the Pocketbook Color Lux doesn't  use pixels for mxc_update, but bytes. So I had to `w = w * 3` in ffi/framebuffer_mxcfb.lua:mcx_update. Where shall I put the change? If I put it in refresh_pocketbook, it is overwritten by BB.checkBounds in mxc_update.

**Comment by NiLuJe** [comment]
Yup, nice catch! ;).

(The hung device was probably from a "broken" MXCFB_SEND_UPDATE call, there's a number of weird corner-cases that just crash the driver... (Notably rectangles with one or both sides <= 1px)).

Hmm, that's a bit tricky... You could probably game the checkBounds calls by doing something like if w = 0 then w = getWidth * 3; but that leaves BB's getPhysical* stuff, which will use the "visible" width when there's rotation tweaks to apply...

**Comment by thomasrebele** [comment]
so shall I put it directly in mcx_update? Something like "if device = Pocketbook Color Lux then w = w*3". Would it be ok to add an additional parameter, or shall I try to get the device name inside the function?

There are two gray vertical lines left and right in the document, see previous picture. Is there an option to remove them?

**Comment by poire-z** [comment]
> There are two gray vertical lines left and right in the document, see previous picture. Is there an option to remove them?

Could be that you unwillingly enabled the `Speed reading module - perception expander` plugin (in the 2nd/Style top menu tab, 2nd from left).

**Comment by NiLuJe** [comment]
While I'd really like to avoid piling any more device-specific hacks in mxc_update, I don't really see any better solution OTOH...

You can probably do fb.device:isPocketBook() in there IIRC.

**Comment by poire-z** [comment]
(I don't understand much of what's involved...) but you can keep the brand/model in frontend, and just use feature-flag functions here, like `device:has3BytesWideFrameBuffer()` or something like that indicating correctly what's happening and what's needed. And have that set to `no` by default, and to `yes` only for that specific model in frontend code.

**Comment by NiLuJe** [comment]
That's a definite possibility ;). Better if other models ever need it, and it miiight be a tad faster than doing a string comparison ;).

**Comment by thomasrebele** [comment]
@poire-z  thanks, it was the perception expander.

A feature-flag is a good idea. I'll make a pull request in the near future (after cleaning up and adding the changes to the repository). Thanks to @NiLuJe  and @poire-z for all the help debugging this issue.
