### ISSUE TITLE
Problem with some tables at crengine

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#4197]
I´m having a problem with a table at this book: 

If you go to " 9 GRAFIMACETES ", the first table isn´t displaying right. 

Computer

![computer](https://user-images.githubusercontent.com/20425689/45119143-e8f95100-b130-11e8-839c-d9283a9b37bf.jpg)

Koreader

![reader_2018-sep-05_172009](https://user-images.githubusercontent.com/20425689/45119152-ef87c880-b130-11e8-9119-5b80818cd607.png)

can you take a look @poire-z ?

**Comment by poire-z** [comment]
Mhhh, the table rendering code is quite complicated, never really tried to understand it and not sure I'll dare modifying it :| (not soon anyway, quite busy these days).
But yes, it's not always working well.

With your book, I got the same that you did. But if you reduce the font size, comes a point where it displays a bit more correctly (that is no cells overlap, but still not really pretty) - but that's how I'm used to see that kind of multi column tables (that I see mostly only in your books :), :

<kbd>![image](https://user-images.githubusercontent.com/24273478/45120666-13fa9980-b15f-11e8-8536-7f470988781d.png)
![image](https://user-images.githubusercontent.com/24273478/45120673-1b21a780-b15f-11e8-854c-82933fdbefc0.png)</kbd>

I get the feeling it's always the columns on the left that are shortened excessively, but not really sure.

**Comment by Eduardomb22** [comment]
Thanks for the reply, the tip and sorry for the tables at my books :)

**Comment by poire-z** [comment]
(Your books are quite good for testing stuff :)

Btw, if you don't want to reduce the main text size, you can create a user style tweak and apply it when needed (and even multiple, with 70%, 60%, 50%... so you can go down when needed):
`koredaer/styletweaks/table_70pct_smaller.css`
```css
table { font-size: 70%; !important }
/* stop imbricated tables from getting smaller */
table table { font-size: 100%; !important }
```
(epub.css has that already at 80%)

**Comment by poire-z** [comment]
@Eduardomb22 : just curious, because this book also uses some invalid utf8 chars in its tables, for example in the same chapter a few pages further:

<kbd>![image](https://user-images.githubusercontent.com/24273478/45172193-ed8f3980-b204-11e8-9bbd-635567190e16.png)</kbd>

These `??` are actually EF82A5 and EF82A6, so not far away from EF8284 we met in https://github.com/koreader/koreader/issues/4196#issuecomment-418380798.
How do calibre and your other software that displayed EF8284 as a bullet do display these 2 new ones? A bullet too or some other real character?
If you can post screenshots of their rendering of that same table, I'd like to witness that :)

There is also a EF80B1 in:
<kbd>![image](https://user-images.githubusercontent.com/24273478/45172373-73ab8000-b205-11e8-9c88-2f45f992b79f.png)</kbd>

That makes 2 books ! Same publisher or epub maker?

**Comment by Eduardomb22** [comment]
@poire-z These books are from the same publisher (that is the reason they have the same "problem'" ) and the publisher also has their own ereader hardware/software. The book displays fine at calibre, here are the screenshots

![ss2](https://user-images.githubusercontent.com/20425689/45179253-61721780-b1ee-11e8-8e0f-af972ec58671.jpg)
![ss1](https://user-images.githubusercontent.com/20425689/45179255-620aae00-b1ee-11e8-96ac-d7f949df49b4.jpg)
![ss3](https://user-images.githubusercontent.com/20425689/45179257-620aae00-b1ee-11e8-9fd4-f57ad7b4b7d3.jpg)

**Comment by NiLuJe** [comment]
Again, Private Use Block while there's a perfectly good in-spec [block w/ Arrows](http://www.fileformat.info/info/unicode/block/arrows/list.htm) in it ;).

**Comment by poire-z** [comment]
Thanks for the screenshots.
Indeed, all different arrows, and I can not find any correlation between the utf8 bytes I saw (unless vim's zip navigator+ xxd screwed that up for me - but I just double checked in notepad++) and the normal unicode arrows various encoding (utf8, utf16)...

What I don't understand is that one publisher uses them, and 2 different EPUB readers display them correctly... and there's nothing at all about this private use block on the web being semi-publicly used in some contexts...

I tried to look at calibre code to see if they do anything special, but I didn't find my way in the monster sources...

**Comment by NiLuJe** [comment]
Does whatever font Calibre ends up using happen to have the right glyphs in this custom block, maybe?
