### ISSUE TITLE
Does it work to redirect file search to home folder when in some other folder?

### ISSUE THREAD

**Issue by ersi-dnd** [koreader/koreader#4199]
* KOReader version: v2015.11-1837-g8f86579_2018-08-23
* Device: Kobo H2O edition 1

#### Issue

For a while now the "Home folder" button in the file search box is greyed out for me. Does anybody else have this issue? Have I messed up something in the settings perhaps?

#### Steps to reproduce
![filemanager_2018-sep-06_182311](https://user-images.githubusercontent.com/6865273/45168739-b15bd900-b204-11e8-867a-8973f22b4a81.png)

**Comment by Frenzie** [comment]
The regular home button in the top left of the file browser works as it should?

**Comment by NiLuJe** [comment]
IIRC, it's grayed-out if you're currently already in your Home folder (or something of the sort).

**Comment by Frenzie** [comment]
That seems a bit confusing. Then you have to keep track of whether or not you're in the home folder, whereas I can very well see someone adopting the behavior of always pressing "search home folder".

**Comment by NiLuJe** [comment]
Okay, no, I clearly imagined that ;D.

It's [disabled when no home directory is set](https://github.com/koreader/koreader/blob/ababbd7aadc59a9cf773137186cdfc0b0778d995/frontend/apps/filemanager/filemanagerfilesearcher.lua#L107-L110) (or at least it should be).

**Comment by ersi-dnd** [comment]
> It's disabled when no home directory is set (or at least that's the intent, and that looks sane to me).

Yes, this applied to my case. Thank you very much :)

I was pretty sure I had set a home folder early on, but I have multiple devices so I must have forgotten it on this one. Sorry for the trouble.

**Comment by Frenzie** [comment]
That makes a lot more sense. But that's also why I asked about the regular home button. ;-) Closing now.
