### ISSUE TITLE
PB626: Not possible to set default orientation to landscape rotated +90 clockwise

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#4202]
* KOReader version: v2015.11-1840-gababbd7_2018-09-06
* Device: PocketBook 626 with software E626.5.14.1227

#### Issue
Not possible to set default orientation to landscape rotated for 90 degrees clockwise (only 90 degrees counterclockwise)
#### Steps to reproduce
1. Open some e-book e.g. PDF format
2. Change orientation to landscape and do long tap on landscape "button" and set it as default
3. In file browser select "purge.sdr" on previously opened file
4. Open again the same e-book

It opens with landscape orientation but rotated for 180 degrees compared to default settings made by long tap on landscape "button" in step 2.

If I change orientation again to landscape the screen rotates for 180 degrees and again try to set this as new default orientation nothing changes in comparison to previously set default orientation. So it seems that KOReader does not distinguish 2 aspects of landscape orientation.

**Comment by robert00s** [comment]
Go to `Advanced settings` and set `DLANDSCAPE_CLOCKWISE_ROTATION = false`, restart KOReader and choose to save change.

If that not help try https://github.com/koreader/koreader/issues/3002#issuecomment-403580085

**Comment by sonix-github** [comment]
@robert00s: Thanks for the hint. Changing DLANDSCAPE_CLOCKWISE_ROTATION to false seems to help with this but it makes no sense to "hide" it in advanced settings. If there is possibility to set defaults by long tap on portrait or landscape then it will be much intuitive to make the setting there :)

I also tried [#3002](https://github.com/koreader/koreader/issues/3002#issuecomment-403580085) but this did not fix the issue. It is functional only if there are previous book screen orientation settings stored in .sdr folder. After purge.sdr the orientation depends on DLANDSCAPE_CLOCKWISE_ROTATION in advanced settings.

Now is readerview.lua modified according linked issue comment and framebuffer.lua changed to this code:

elseif mode == "landscape" then
    if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
    or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED then
            self:setRotationMode(
						DLANDSCAPE_CLOCKWISE_ROTATION
            and self.ORIENTATION_LANDSCAPE_ROTATED
            or self.ORIENTATION_LANDSCAPE)
        elseif self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE
        or self.cur_rotation_mode == self.ORIENTATION_LANDSCAPE_ROTATED then
            self:setRotationMode((self.cur_rotation_mode + 2) % 4)
        end
    end

**Comment by yparitcher** [comment]
should have been fixed in koreader/koreader-base/pull/781
