### ISSUE TITLE
choose inbox directory: hidden directories not shown

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#4206]
* KOReader version: latest (updated today)
* Device: Kobo

#### Issue
Choose inbox by long-pressing in Zsync and Cloud storage:
hidden directories are not shown
many kobo koreader users have their pdf books in a hidden directory like .books (so that they don't show up with Nickel). 
Is there any possibility to select a hidden directory in choose inbox by changing something in the configuration?

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by cramoisi** [comment]
Yup, I still got this issue on the two H2O2 I installed two weeks ago (but I thought I had seen a solved case for this)

**Comment by robert00s** [comment]
After this PR: #4213 this should be possible.
Remember to enable `Show hidden files` in file browser :)
