### ISSUE TITLE
Kobo GLO HD with koreader v2015.11-stable cannot be put to sleep

### ISSUE THREAD

**Issue by user108** [koreader/koreader#4211]
* KOReader version: v2015.11-stable
* Device: Kobo GLO HD (N437)

#### Issue
I installed 'KBStartMenu_09_plus_update_001' and 'KoReader' and they both work well except when I press the top button, while KoReader is running, the device does to go to sleep, instead the screen flashes once. When I switch to the built in reader I can put the device to sleep.

#### Steps to reproduce
As above

##### `crash.log` (if applicable)
not applicable

Thank you!

**Comment by Frenzie** [comment]
> not applicable

The name is a bit misleading perhaps since it's not just for crashes. Could you please share it after performing the pressing sleep action?

**Comment by NiLuJe** [comment]
There's also a fairly good chance things are fixed in current builds ;).

**Comment by Frenzie** [comment]
Quite so! My bad, I should've paid closer attention.

**Comment by NiLuJe** [comment]
In case that wasn't clear: the "stable" release is *exceedingly* old, we heartily recommend switching at least to a recent "nightly", as available in the "[Releases](https://github.com/koreader/koreader/releases)" tab on the GitHub project page.

**Comment by user108** [comment]
Updated to current beta solved the issue. Thanks NiLuJe
