### ISSUE TITLE
Changelog Inside KOReader Application

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#4215]
Just a minor feature request.
It would be nice to have a copy of the release changelog available inside the KOReader application, somewhere near or on the version information page. This would be particularly nice when using OTA updates, to see what's changed, what's been fixed, and whether there are any exciting new features to try out.

I assume that showing some text in a popup is trivial, it's just a question of how easy it is to put the changelog text that appears on the release page somewhere where it can be built into the release.

**Comment by Frenzie** [comment]
As a workaround of sorts you can probably subscribe to the release updates in the NewsDownloader.

**Comment by Thra11** [comment]
I tried adding https://github.com/koreader/koreader/releases.atom to the newsdownloader feed_config.lua. The results include rather a lot of garbage (basically the entire top part of the github web ui), but the content is all there, so I guess it's good enough for now.

**Comment by Frenzie** [comment]
Cf. #3172.
