### ISSUE TITLE
kindle-like search (overview of search results)

### ISSUE THREAD

**Issue by timokau** [koreader/koreader#4216]
#### Feature request

When using koreader instead of the native kindle reader, there is one feature I miss in particular. The search will show a list of appearances of the search term (starting from the start of the book) with context. This makes it very easy to quickly check if a character/concept has been introduced before. That is not so easy with koreaders search feature since it starts from the current position and always only shows one results (taking up the whole screen).

Kindle also makes it possible to search in multiple books.

The kindle search feature works [similar to this](https://www.logos.com/images/pages/apps/kindlefire/features/kindlefire-search.png).

**Comment by Frenzie** [comment]
Closing in favor of #5597 which contains more screenshots.
