### ISSUE TITLE
Can't setting Contrast on Kindle 4

### ISSUE THREAD

**Issue by pbnanc** [koreader/koreader#4218]
* KOReader version: koreader-beta-20180729
* Device: Kindle 4

#### Issue

I can't setting `Contrast` option, 'coz the buttons don't move the little squares (like the picture)

![kindlee](https://user-images.githubusercontent.com/39012860/45394536-c1096200-b5f6-11e8-9a67-42ddfc4bc988.png)

**Comment by pbnanc** [comment]
So, this issue is fixed ¿? i need wait the next realese

**Comment by NiLuJe** [comment]
I'll be in the next OTA (~5AM UTC) ;).
