### ISSUE TITLE
Nexus 6P Cannot connect to Calibre Connect

### ISSUE THREAD

**Issue by LividJava** [koreader/koreader#4221]
* KOReader version: v2015.11-1800-g0924b57_2018-07-29
* Device: Nexus 6P (LineageOS: 15.1-20180910-NIGHTLY-angler)
* Calibre Version: 3.31.0

#### Issue
KOReader is unable to connect to the calibre connect service. attempts to restart and reinstall (on both ends) have failed

**Comment by NiLuJe** [comment]
Try with a current nightly, this is probably #4187, which was fixed in #4188 ;).

**Comment by LividJava** [comment]
Am noob where can i nab the nightlys or do i need to compile them on my own

**Comment by LividJava** [comment]
Seemed to work! is there any way to get OTA nightly? or is that not a thing

**Comment by NiLuJe** [comment]
Not on Android, no.
