### ISSUE TITLE
Sorting of folders not correct?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4224]
* KOReader version: 1836
* Device: KA1

#### Issue
"Sort by name - mixed files and folders" works fine. 

But the other choices: size, type, date added etc?? They don't seem to sort my folders in a correct way.
Are sorting only for files?

**Comment by Frenzie** [comment]
It looks like date modified sorts correctly, but indeed not with a mixed option.

None of the others besides size seem like they make sense "mixed," and folder size would probably be a bad idea performance-wise.

Pinging @robert00s in case there's an interest in adding mixed by date.

**Comment by gerhaher** [comment]
> It looks like date modified sorts correctly, but indeed not with a mixed option.
> 
> None of the others besides size seem like they make sense "mixed," and folder size would probably be a bad idea performance-wise.

I think you are misunderstanding the described issue. It's not about lack of  "mixed" options for size, type et cetera.

I just wanted to point out that sorting by size, type et cetera seems to give strange results for folders.

The only ones that I care about - "Sort by filename" and "Sort by name - mixed files and folders" - are both sorting folders correctly.

**Comment by Frenzie** [comment]
It seems correct to me atm, but perhaps it's something Kobo-specific, see #1189.

**Comment by NiLuJe** [comment]
locales are broke as hell on Kobo, so, if there's anything funky involved, yep, it's going to be b0rked on Kobo.

**Comment by gerhaher** [comment]
I just checked size sorting on my Android: I think it was better than on my KA1 but I found some faults there too.

**Comment by NiLuJe** [comment]
Specific examples of what's not sorted correctly would potentially be helpful ;).

**Comment by gerhaher** [comment]
> Specific examples of what's not sorted correctly would potentially be helpful ;).

Well, I imagine it would be easy to reproduce for anyone with an Android, because on closer inspection, sorting on my Android seems to be as messy as on my Kobo.

My Home folder on my Android contains 36 subfolders (all files are in the subfolders).
Size sorting results in the following. Sizes of the folders:
18.5 MB
22.2 MB
41.0 MB
1.08 GB
96.8 MB
363 MB
33.9 MB
14.0 MB
31.7 MB
8.9 MB
19.1 MB
24.8 MB
90,4 MB
49.1 MB
209 MB
274 MB
161 MB
119 MB
330 MB
268 MB
451 MB
450 MB
348 MB
409 MB
554 MB
534 MB
1.03 GB
515 MB
625 MB
134 MB
369 MB
628 MB
120 MB
831 MB
432 MB
633 MB

I opened a book and then tried "Sort by last read date". The folder which contained the book in question did end up somewhere in the middle.

I renamed a folder and then tried "Sort by date modified". It did not end up first.
I renamed a file in a folder, That folder did actually end up first.

Well, I hope that will do for now. :-)

**Comment by gerhaher** [comment]
I can add that "Sort by last read date" works on my KA1 (but thus not on Android).

**Comment by Frenzie** [comment]
The only size by which folders could reasonably be sorted is number of items inside.

**Comment by gerhaher** [comment]
Number of items (from my size sorting above):
5, 10, 20, 6, 20, 24, 10, 4, 11, 5, 18, 16, 17, 18, 28, 39, 35, 37, 23, 38, 44, 63, 53, 64, 78, 57, 101, 63, 68, 42, 72, 57, 62, 126, 102, 101

**Comment by Frenzie** [comment]
Well I said could, not is. :-P It'd actually be more deceptive than anything because only the top level number of items is known, and as soon as you start traversing directories you run into the same performance issue as tallying up file sizes.

**Comment by Frenzie** [comment]
Closing since unfortunately I don't think there's much we can do. Someone's always welcome to implement full traversal along the lines of how covers are done in CoverBrowser of course.
