### ISSUE TITLE
cloud storage: hidden directories are not shown

### ISSUE THREAD

**Issue by alex125** [koreader/koreader#4226]
* KOReader version: latest (updated today)
* Device: kobo 

#### Issue
Choose inbox by long-pressing in Zsync and Cloud storage:
hidden directories are not shown

I saw that #4206 was closed so I thought this should work now?
Tried it but it still doesn't work. I can see and select hidden directories in the file browser but not in cloud storage. When I tap 'longpress to select current directory', it takes me to /mnt/onboard  and I cannot see and select mnt/onboard/.books

**Comment by y-muller** [comment]
On Kobo Clara and Mini, I see the hidden files in ZSync and Cloud storage **if** the option to see hidden files is selected in the file manager. Makes sense and works perfectly.

**Comment by alex125** [comment]
Thanks for trying. I did have Show hidden files checked but it only worked in the File Browser for opening books. After reading your post, I unchecked Show hidden files, then checked it again and immediately exite koreader. On restart, Zsync and Cloud storage now show hidden files. Issue resolved.
