### ISSUE TITLE
No full screen redraw in night mode

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#4228]
* KOReader version: v2015.11-1800
* Device: Boyue Likebook Plus T80s

#### Issue
When night mode is on, shadow images of previous pages distort picture, even if redraw after each page is selected
#### Steps to reproduce
Open a document, turn on night mode.

**Comment by Frenzie** [comment]
Is that an Android device?

**Comment by ilyats** [comment]
Yes

**Comment by ilyats** [comment]
BTW, is there a way to have nightly builds automatically installed on Android? The OTA server doesn't have Android builds.

**Comment by Frenzie** [comment]
Not that I know of, sorry.

The E-ink full refresh rate setting doesn't actually do anything on Androida afaik. It should be taken out. Somewhat related: #3567 and #3517 (except there the device creators broke normal Android).

Anyone who knows of any documentation to tap into E Ink on any Android device (see [here](https://github.com/koreader/koreader-base/blob/a7e0ab9071f03c490f81d6ec395259ee3f94eaf8/ffi/framebuffer_mxcfb.lua) for regular E Ink), please share! :-) I couldn't really find much of anything for this device; is it in Russian?

**Comment by ilyats** [comment]
The device is manufactured by a Chinese firm called Boyue, it (or a very similar device) is also sold as Icarus Illumina XL. It is based on rk3188 SoC and rk30sdk board by RockChip and runs firmware based on Android 4.2.2 It has 7.8" 300DPI Carta HD e-ink screen with backlight.

**Comment by Frenzie** [comment]
Right, I should've specified. I mean I searched for the usual terms like Boyue SDK, Boyue API, Boyue development/developers docs/documentation and various other variations of the theme including stuff like REGAL.

I can't find anything relevant for that Icarus thing either, neither through their website nor through generic searches.

**Comment by pazos** [comment]
There are a bunch of android devices based on [rockchip RK3026](https://www.mobileread.com/forums/showthread.php?t=254042), but sadly no SDK,  kernel source or anything.

All the other devices that I know are based on freescale IMX platform (ie: kobos, kindles and the bq cervantes - Only sold in Spain AFAIK. Even some tolino ereaders shipped w/ android are based on freescale.

**Comment by Frenzie** [comment]
Sorry for the reference. I thought this was the issue I was fixing based on the title.

**Comment by pazos** [comment]
@ilyats: please download the eink test from the releases page and try if supported controllers work for you. It should work.
