### ISSUE TITLE
Crashes on Pocketbook Touch HD 2

### ISSUE THREAD

**Issue by lsahnicne** [koreader/koreader#4229]
* KOReader version: koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1849-geed3a4b_2018-09-13
* Device: Pocketbook Touch HD 2

Issue: Frequent crashes. I mostly used koreader so far to read comics in .cbz format and it would occasionally crash mid-read. Today i tried opening .zip archives containing images in .jpg format and it is crashing instantly when trying to open them. It also crashed when using file browser. I used version koreader-pocketbook-arm-obreey-linux-gnueabi-v2015.11-1800-g0924b57_2018-07-29 for that. Now today i tried updating to version mentioned in the beginning of the issue and all the aforementioned issues are still in place. Unfortunately i don't have crash log from when i was using previous version but iirc it all ended with the same "Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault".

Steps to reproduce:
1. Install Koreader
2. Open .cbz file
3. Using menu go to file reader
4. Flip page
5. Crash

1. Install Koreader
2. Open from app menu
3. Flip page
4. Crash

1. Install Koreader
2. Open .cbz file
3. Read for a while
4. Crash

Crash log: https://pastebin.com/W4XtFFzY

**Comment by pazos** [comment]
Closing in favor of #6000, because it exhibits the same error `Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}`
