### ISSUE TITLE
After select element in menu it didn't invert back to white

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#4234]
* KOReader version: newest
* Device: all

#### Issue
Hamburger menu -> Help -> report a bug -> close window -> About
![test1 - koreader_171](https://user-images.githubusercontent.com/22982594/45701665-24077580-bb70-11e8-8933-06433048a496.png)

**Comment by NiLuJe** [comment]
Yes, it's a side-effect on items that keep the menu open without switching menu pane.

I'm not annoyed enough by it to care enough (read: dig enough time to work on it) to fix it right now, to be perfectly honest ;).

**Comment by NiLuJe** [comment]
Might be as simple as making https://github.com/koreader/koreader/blob/master/frontend/ui/widget/touchmenu.lua#L155-L162 happen if keep_menu_open

**Comment by NiLuJe** [comment]
At the very least, that comment is now wrong since #4189 ;).

**Comment by NiLuJe** [comment]
And making it ui instead of fast might work around the "hey, I'm now transparent" timing issues with fast.

**Comment by poire-z** [comment]
Oups, didn't check when I made it, as I always have `Flash buttons and menu items` disabled :( sorry. (Feel free to fix it if there's an obvious fix)

**Comment by NiLuJe** [comment]
No worries, as I said, I noticed it, but it's not bothering me too much ;p.

I'll see if my napkin coding actually works when I have a bit of time ;).
