### ISSUE TITLE
Orientation/Rotation gets out of sync with actual orientation on Kindle Oasis

### ISSUE THREAD

**Issue by ghost** [koreader/koreader#4239]
* KOReader version: v2015.11-1854-gf2abdd4_2018-09-19
* Device: Kindle Oasis 5.9.7

#### Issue
After reading for a while the orientation will get out of sync with the actual rotation of the device. Frequently the rotation will be reversed from how the device is held, and when this happens, the application becomes very, very slow to respond to input, lagging by 30-60 seconds after each touch. Strangely, the device recognizes touches in the opposite orientation from what is displayed (digitizer is in correct orientation, but display is not) meaning that to exit and reboot, you must tap where the target would be if the display were correct.

I tried the latest stable and latest nightly, both have this issue.

#### Steps to reproduce
Frustratingly, I cannot repeatably reproduce with a given flow, but after reading for 30 minutes I invariably get to this state.

**Comment by jacquescousteau** [comment]
To clarify, this is on the 6 inch Kindle Oasis, not the new 7 inch.

**Comment by jacquescousteau** [comment]
Beginning to think that this is only occurring while night mode is active. I read for a while with night mode off and did not encounter the issue, but one commonality that I've observed with night mode both on and off is that the battery indicator and the clock from the Kindle framework (I think?) will show through to KOReader. This also happened when the above slowdowns occurred, but I'm not sure if it's a separate bug or somehow related to this issue. This UI would commonly be in the correct orientation when the KOReader was in the opposite/incorrect orientation.

**Comment by NiLuJe** [comment]
Unless it's a SO, I'm fairly sure the framework seeping through issues are taken care of as well as we possibly can.

Orientation is a whole 'other kettle of fish, though, and it's quite possibly slightly broken.

**Comment by jacquescousteau** [comment]
SO = Special Offers? It had them when purchased, but they've been removed by Amazon. Not sure if that matters.

I'm not super confident that I can fix it, but I'm happy to take a look through the relevant code. @NiLuJe can you give me a sense of where to look?

**Comment by poire-z** [comment]
Possibly better since #6309 and #6347. Re-open if not.
