### ISSUE TITLE
[Kobo OTA]: error upgrading 

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4242]
* KOReader version: 2015111800 - lastest beta
* Device: Kobo Aura One

#### Issue
Can't update to lastest nightly (2015111856).

I see the *error upgrading koreader, do you want to remove temp files?* message. 

##### `crash.log` (if applicable)
```
./tar: koreader/ota/koreader.installed.tar: file is the archive; not dumped
./tar: koreader/ota/koreader.installed.tar: file is the archive; not dumped
./tar: The following options were used after any non-optional arguments in archive create or update mode.  These options are positional and affect only arguments that follow them.  Please, rearrange them properly.
./tar: --no-recursion has no effect
./tar: Exiting with failure status due to previous errors
```

**Comment by NiLuJe** [comment]
Yep, that was fixed in #4150

**Comment by NiLuJe** [comment]
(Keeping this open because it affects a beta, and blocks updating, which is less than ideal ;D).

**Comment by pazos** [comment]
Closing because a new beta was released 👍
