### ISSUE TITLE
FTP "empty folder"

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#4243]
* KOReader version:V2015.11-1856
* Device:KAO，H2O

I have built a FTP sever on my router to store books. 
I use cloud storage->FTP to connet the FTP sever , and it found "empty floder".
I try this from PC and phone, and it works normally.
Does anyone have same problem?

**Comment by jacquescousteau** [comment]
Same with both WebDAV and FTP. Tried using my email provider’s offering, as well as my synology NAS. Would be great if this worked instead of just saying “Empty Folder” every time.

**Comment by seacatwu** [comment]
I use a vftpd on my openwrt router, and it works fine.
But it can't work on the other FTP severs.

**Comment by NiLuJe** [comment]
Define "other", so we can try to repro ;).

**Comment by seacatwu** [comment]
Like Serv-U, Asus N14 vftpd, some android FTP sever.

**Comment by clach04** [comment]
KOReader 2020.06 works for me with ProFTPD server (but did hit bug #6362).
