### ISSUE TITLE
About unfinished book

### ISSUE THREAD

**Issue by ZenRoi** [koreader/koreader#4247]
* KOReader version: koreader-beta-20180729
* Device: kobo touch

#### Issue

How can I continue to read the last unfinished book when I enter the system? 

It is recommended to keep the option to 'Continue reading' please! thanks.

**Comment by Frenzie** [comment]
In the file browser, you can activate "start with last opened book."

**Comment by ZenRoi** [comment]
> In the file browser, you can activate "start with last opened book."
Thank you!
I can only find the option in a list about the document is "Open random document" when I've activate the symbol "+" in the upper right corner of then file browse. 
Maybe my device is too old to get support? It may also be true that this feature is not included in this version.

**Comment by Frenzie** [comment]
It's in the settings menu (gear). You have to swipe down from the top (or tap in the top center) to bring it up.

**Comment by Frenzie** [comment]
My bad, it's in the file manager menu (top left).

![2018-09-29 09 30 24](https://user-images.githubusercontent.com/202757/46242579-d8a06300-c3ca-11e8-8874-9b9d35276bd0.jpg)
![2018-09-29 09 30 34](https://user-images.githubusercontent.com/202757/46242580-d8a06300-c3ca-11e8-9a55-74103222f1c4.jpg)

**Comment by ZenRoi** [comment]
> My bad, it's in the file manager menu (top left).
> 

Thank you for your patience!
From the pictures you've uploaded, I found that the interface is different from my device. Kobo touch's file browser option is on the right. If you click on it without a drop-down menu, jump directly to the file list interface.
 I checked it, yes, the version is beta 20180729.

**Comment by ZenRoi** [comment]
[https://lh3.googleusercontent.com/rNsJrikvq1c1gU8CwH-bSILXJM4Q-0SbYBCvS_raOS1MIFMRlC8QNZLsbjm2f2F8iAKQE05WF67-r3xSuU6aHcG6fz66bXBF-yFT8OrYCR0ZgzPQqHZZzl3Cwky_TKDgcnUob_Iyt5jyKmkqsw0XEHNhKBy6U66EUobPgNgGFciwDXvMryYlApN2VpChcWZPXV2jy9un0BAvs81VGibEGeG-Jqru882fyrIJPxq3KGDwk7Gxr__WerStDabeGF2hT-TOEDOrF3OuUyyUBzVfWYMYCU5nYbt8jSQBRIBwHl9bW_DvHy6mn0XL_fADKUrYG43X6OT4jTVujRMrOfPttGltgRVjrJwKyv9K2oFp6Tpi3j2ls9RD6RmMy9kFkr6rDGKqTMh0PFoI6YbjWSsLnQRGJZIy1TQ6XJ9a4jTn2x5xzRgFdvoRzJzXehLJ7cIBcuKVbwekbtjwGk9rmtnPJQvlq6UEufqmcLiSjuLjmHHtfVpsDh3U4e3RGqB3QyNHON3wV8ZEWIY9sO7lCTJEUjm1PuE5yaxkX1744pwtrR8ovvyuT4FEhR37N9NEQJMWjzxNlW4I7o6Ic6DD_XzuuDSh5EMny04cPPg8qeQuYjbia1lE7BmOCPtaWJC2XFg=w604-h805-no](url)

**Comment by ZenRoi** [comment]
[Kobo touch](https://lh3.googleusercontent.com/rNsJrikvq1c1gU8CwH-bSILXJM4Q-0SbYBCvS_raOS1MIFMRlC8QNZLsbjm2f2F8iAKQE05WF67-r3xSuU6aHcG6fz66bXBF-yFT8OrYCR0ZgzPQqHZZzl3Cwky_TKDgcnUob_Iyt5jyKmkqsw0XEHNhKBy6U66EUobPgNgGFciwDXvMryYlApN2VpChcWZPXV2jy9un0BAvs81VGibEGeG-Jqru882fyrIJPxq3KGDwk7Gxr__WerStDabeGF2hT-TOEDOrF3OuUyyUBzVfWYMYCU5nYbt8jSQBRIBwHl9bW_DvHy6mn0XL_fADKUrYG43X6OT4jTVujRMrOfPttGltgRVjrJwKyv9K2oFp6Tpi3j2ls9RD6RmMy9kFkr6rDGKqTMh0PFoI6YbjWSsLnQRGJZIy1TQ6XJ9a4jTn2x5xzRgFdvoRzJzXehLJ7cIBcuKVbwekbtjwGk9rmtnPJQvlq6UEufqmcLiSjuLjmHHtfVpsDh3U4e3RGqB3QyNHON3wV8ZEWIY9sO7lCTJEUjm1PuE5yaxkX1744pwtrR8ovvyuT4FEhR37N9NEQJMWjzxNlW4I7o6Ic6DD_XzuuDSh5EMny04cPPg8qeQuYjbia1lE7BmOCPtaWJC2XFg=w604-h805-no)

**Comment by ZenRoi** [comment]
![image](https://lh3.googleusercontent.com/rNsJrikvq1c1gU8CwH-bSILXJM4Q-0SbYBCvS_raOS1MIFMRlC8QNZLsbjm2f2F8iAKQE05WF67-r3xSuU6aHcG6fz66bXBF-yFT8OrYCR0ZgzPQqHZZzl3Cwky_TKDgcnUob_Iyt5jyKmkqsw0XEHNhKBy6U66EUobPgNgGFciwDXvMryYlApN2VpChcWZPXV2jy9un0BAvs81VGibEGeG-Jqru882fyrIJPxq3KGDwk7Gxr__WerStDabeGF2hT-TOEDOrF3OuUyyUBzVfWYMYCU5nYbt8jSQBRIBwHl9bW_DvHy6mn0XL_fADKUrYG43X6OT4jTVujRMrOfPttGltgRVjrJwKyv9K2oFp6Tpi3j2ls9RD6RmMy9kFkr6rDGKqTMh0PFoI6YbjWSsLnQRGJZIy1TQ6XJ9a4jTn2x5xzRgFdvoRzJzXehLJ7cIBcuKVbwekbtjwGk9rmtnPJQvlq6UEufqmcLiSjuLjmHHtfVpsDh3U4e3RGqB3QyNHON3wV8ZEWIY9sO7lCTJEUjm1PuE5yaxkX1744pwtrR8ovvyuT4FEhR37N9NEQJMWjzxNlW4I7o6Ic6DD_XzuuDSh5EMny04cPPg8qeQuYjbia1lE7BmOCPtaWJC2XFg=w604-h805-no)

**Comment by ZenRoi** [comment]
If I click on the browser icon, the drop-down menu will not appear, but instead skip directly to the file list.

**Comment by Frenzie** [comment]
Yes, and that's where you have to access the menu again. :-)

**Comment by ZenRoi** [comment]
Ok, I am sorry that I have not found this feature before.
Now I've got it, ^_^
Thank you for your enthusiasm.

**Comment by Frenzie** [comment]
Alright, closing then! ;-)
