### ISSUE TITLE
Crash on EPUB files with JPEG on Android 4.x

### ISSUE THREAD

**Issue by carmelocotonto** [koreader/koreader#4254]
* KOReader version:  the last two months. Ver. 1840 and up, for example
* Device:  onyx boox c67, android 4.2

#### Issue
When I try to open a .epub file, the application ends. With an html file everything is correct and with a mobi file is also correct.
The last functional version for me is 1807

#### Steps to reproduce
Uninstall previous versions, install the application and try to open an epub ebook from file manager or directly. I tried it from ver 1838 to 1866

##### `crash.log` (if applicable)
I can not find the `crash.log` in android

**Comment by NiLuJe** [comment]
This is similar (or possibly identical) to a report made on MR.

Likely culprit is the jpeg-turbo bump, but I've yet to see it crash on anything else...

**Comment by carmelocotonto** [comment]
And please, what do you think about it?. Is it a problem with solution in the future?, or is it a permanent problem?. Android ereaders have got android 4.0 or 4.2, I think, so the problem affects many readers. Thanks in advance

**Comment by pazos** [comment]
It crashes on a [Energy ereader pro hd](https://www.tuexperto.com/2017/07/30/energy-sistem-ereader-pro-hd-probamos-el-lector-de-ebook/) too. It seems a common (rockchip - Jelly Bean) problem.

**Comment by sgelb** [comment]
Same here, koreader-beta-20181007 crashes when opening any epub. It works with koreader-beta-20180602. Device is a Tolino Vision 4HD, Android 4.0.4.

I'll try to find some time to bisect the code to find the responsible commit this weeekend.

**Comment by NiLuJe** [comment]
Probably the jpeg turbo bump, which seems to be allergic to Android 4.x...

**Comment by Frenzie** [comment]
@NiLuJe Have you checked if with any luck it's been fixed upstream? Android 2.3 might be droppable (in fact I think @mwoz123 accidentally broke it last year and no one other than me even noticed), but Android <4.4 is used by an awful lot of ereaders.

I suppose we could consider setting up some special Android <5 stuff (e.g., older libjpeg-turbo) but it'd make downloading the right page even more confusing.

**Comment by NiLuJe** [comment]
Nothing but windows compat fixes last I checked ;/

**Comment by carmelocotonto** [comment]
> It crashes on a [Energy ereader pro hd](https://www.tuexperto.com/2017/07/30/energy-sistem-ereader-pro-hd-probamos-el-lector-de-ebook/) too. It seems a common (rockchip - Jelly Bean) problem.

Hi, I have prepared an experiment: I took the last version that worked, the 1815, and I have changed several files taken from the 1866 version, mainly from the / frontend directory . I tried several changes until I 'built' a 'frankenstein' version that works on Onyx C67 with android 4.2.x. I used APK-Multi-Tool to recreate the apk. If you want to take a look, I can send you the result. So you can see the files changed and build yourself the apk.
The modified application I only use, is not available to anyone in the network, but I can pass it to you if you want.
(Nota para Pazos: soy español y creo que tú también)

**Comment by carmelocotonto** [comment]
> From frontend? Could you please give some more details? I wouldn't expect frontend to affect stability, or at least not specifically on one platform.

Yes, 'mainly from the /frontend' directory because ver. 1866 has got different menus, dialogs, functions, etc.... I have changed some libs too. I have reviewed the changed files and this is the list (I hope they are all. They are basically more modern files than ver. 1815):

".\git-rev"
".\ota-rev"
".\reader.lua"
".\README.md"
".\common\ssl.so"
".\ffi\framebuffer_mxcfb.lua"
".\ffi\mxcfb_sony_h.lua"
".\frontend\depgraph.lua"
".\frontend\device.lua"
".\frontend\pluginloader.lua"
".\frontend\apps\cloudstorage\cloudstorage.lua"
".\frontend\apps\cloudstorage\ftp.lua"
".\frontend\apps\filemanager\filemanager.lua"
".\frontend\apps\filemanager\filemanagerconverter.lua"
".\frontend\apps\filemanager\filemanagermenu.lua"
".\frontend\apps\filemanager\filemanagershortcuts.lua"
".\frontend\apps\reader\readerui.lua"
".\frontend\apps\reader\skimtowidget.lua"
".\frontend\apps\reader\modules\readerdevicestatus.lua"
".\frontend\apps\reader\modules\readerdictionary.lua"
".\frontend\apps\reader\modules\readerfont.lua"
".\frontend\apps\reader\modules\readerfooter.lua"
".\frontend\apps\reader\modules\readergesture.lua"
".\frontend\apps\reader\modules\readergoto.lua"
".\frontend\apps\reader\modules\readerhighlight.lua"
".\frontend\apps\reader\modules\readerhyphenation.lua"
".\frontend\apps\reader\modules\readerlink.lua"
".\frontend\apps\reader\modules\readermenu.lua"
".\frontend\apps\reader\modules\readerstyletweak.lua"
".\frontend\apps\reader\modules\readertoc.lua"
".\frontend\apps\reader\modules\readertypeset.lua"
".\frontend\apps\reader\modules\readerwikipedia.lua"
".\frontend\apps\reader\modules\readerzooming.lua"
".\frontend\device\generic\device.lua"
".\frontend\device\generic\powerd.lua"
".\frontend\device\sony-prstux\device.lua"
".\frontend\device\sony-prstux\event_map.lua"
".\frontend\device\sony-prstux\powerd.lua"
".\frontend\document\credocument.lua"
".\frontend\document\documentregistry.lua"
".\frontend\ui\uimanager.lua"
".\frontend\ui\data\creoptions.lua"
".\frontend\ui\data\css_tweaks.lua"
".\frontend\ui\data\strings.lua"
".\frontend\ui\data\keyboardlayouts\el_keyboard.lua"
".\frontend\ui\data\keyboardlayouts\es_keyboard.lua"
".\frontend\ui\data\keyboardlayouts\fr_keyboard.lua"
".\frontend\ui\data\keyboardlayouts\ja_keyboard.lua"
".\frontend\ui\data\keyboardlayouts\pl_keyboard.lua"
".\frontend\ui\data\keyboardlayouts\pt_keyboard.lua"
".\frontend\ui\data\keyboardlayouts\std.lua"
".\frontend\ui\data\keyboardlayouts\yazhert.lua"
".\frontend\ui\elements\avoid_flashing_ui.lua"
".\frontend\ui\elements\common_info_menu_table.lua"
".\frontend\ui\elements\common_settings_menu_table.lua"
".\frontend\ui\elements\filemanager_menu_order.lua"
".\frontend\ui\elements\flash_keyboard.lua"
".\frontend\ui\elements\flash_ui.lua"
".\frontend\ui\elements\menu_activate.lua"
".\frontend\ui\elements\reader_menu_order.lua"
".\frontend\ui\elements\refresh_menu_table.lua"
".\frontend\ui\elements\screensaver_menu.lua"
".\frontend\ui\elements\screen_color_menu_table.lua"
".\frontend\ui\elements\screen_disable_double_tap_table.lua"
".\frontend\ui\elements\screen_dpi_menu_table.lua"
".\frontend\ui\elements\screen_eink_opt_menu_table.lua"
".\frontend\ui\elements\screen_fullscreen_menu_table.lua"
".\frontend\ui\message\streammessagequeue.lua"
".\frontend\ui\network\manager.lua"
".\frontend\ui\widget\bookstatuswidget.lua"
".\frontend\ui\widget\button.lua"
".\frontend\ui\widget\buttondialogtitle.lua"
".\frontend\ui\widget\buttonprogresswidget.lua"
".\frontend\ui\widget\filechooser.lua"
".\frontend\ui\widget\imagewidget.lua"
".\frontend\ui\widget\infomessage.lua"
".\frontend\ui\widget\inputdialog.lua"
".\frontend\ui\widget\inputtext.lua"
".\frontend\ui\widget\keyvaluepage.lua"
".\frontend\ui\widget\menu.lua"
".\frontend\ui\widget\multiinputdialog.lua"
".\frontend\ui\widget\opdsbrowser.lua"
".\frontend\ui\widget\screenshoter.lua"
".\frontend\ui\widget\scrolltextwidget.lua"
".\frontend\ui\widget\spinwidget.lua"
".\frontend\ui\widget\textboxwidget.lua"
".\frontend\ui\widget\textviewer.lua"
".\frontend\ui\widget\textwidget.lua"
".\frontend\ui\widget\toggleswitch.lua"
".\frontend\ui\widget\touchmenu.lua"
".\frontend\ui\widget\virtualkeyboard.lua"
".\frontend\ui\widget\container\inputcontainer.lua"
".\l10n\*.*"
".\libs\libcrypto.so.1.0.0"
".\libs\libfmq.so.1"
".\libs\libharfbuzz.so.0"
".\libs\libsqlite3.so"
".\libs\libssl.so.1.0.0"
".\plugins\*.*"
".\resources\ko-icon.png"

**Comment by NiLuJe** [comment]
One definitive way to confirm my jpeg turbo theory would be to take the reverse approach : Start from the latest Apk, and simply replace libs/libjpeg-turbo by the old one.

**Comment by Frenzie** [comment]
Oh, I misread. I thought you'd done what @NiLuJe suggested.

**Comment by carmelocotonto** [comment]
No, I already did it. I changed only libjpeg-turbo but there are other associated files, for example: 
turbojpeg_h.lua  is different between ver 1815 and 1866
libjpeg.so.8  (this lib is not into ver.1866). There is a lib named libjpeg.so but is different

I think that in ver. 1866   libcrengine.so, libjpeg.so and libmupf.so  call  libturbojepg.so (ver 1866), so if you replace only  libs/libjpeg-turbo by the old one, the program fails. You must replace mor libs. So I started from 1815 to 1866, not 1866 to 1815.
Sorry for my english. I do not know if you understand me.

**Comment by carmelocotonto** [comment]
Well, when I say 'change', I want to say 'replace'. Sorry. I have taken files from version 1866 and I have passed them to version 1815

**Comment by marmistrz** [comment]
For me some of the epubs crash, some don't. I've sent an affected file to @Frenzie on gitter.
I'm attaching the logs.
Device: InkBook Classic 2.
[koreader.log](https://github.com/koreader/koreader/files/2489175/koreader.log)

**Comment by NiLuJe** [comment]
@marmistrz : I'd actually be more interested in one that *doesn't* crash ;).

@Frenzie: Would we get a better backtrace with JIT disabled? Because AFAIK, all those longjmp are just jumps into the JIT code area, right?

**Comment by Frenzie** [comment]
Probably, though I wouldn't necessarily count on a better backtrace.

**Comment by carmelocotonto** [comment]
> If someone could check if a nightly >= `2018.11.1-20` does any better, that'd be helpful ;).
> 
> (And I wouldn't mind a look at a `cat /proc/cpuinfo` while we're there).

Well. I have done a clean installation of version nightly = `2018.11.1-20` and with mobi ok, html ok but epub crash.

cat /proc/cpuinfo:

Processor: ARMv7 Processor rev 1 
processor: 0
BogoMIPS: 1823.40
Features: swp half thumb fastmult vfp edsp neon vfpv3
CPU implementer: 0x41
CPU architecture: 7
CPU variant: 0x4
CPU part: 0xc09
CPU revision: 1

Hardware: RK30board
Revision: 0000
Serial: 0000000000000000

Regards

**Comment by poire-z** [comment]
Just to be sure if it's related to jpeg handling or not (as most other formats usually come without embedded images): can you check with a plain EPUB without images if it crashes too, for example the sample in the first post of #2842

**Comment by NiLuJe** [comment]
Yeah, so, definitely libjpeg-turbo. -_-".

**Comment by NiLuJe** [comment]
Okay, one final test before I take a very big hammer to the problem: does today's nightly (-24) work any better?

**Comment by sgelb** [comment]
Did you mean -14? Today's nightly `koreader-android-arm-linux-androideabi-v2018.11.1-24-gbd6c852_2018-11-14.apk` still crashed here.

**Comment by carmelocotonto** [comment]
No. This version (24)  fails when I try to open an epub book. 8(
Luck with the hammer

**Comment by Frenzie** [comment]
I don't see a file to reproduce the crash here, only files that *don't*?

**Comment by carmelocotonto** [comment]
Frenzie, please, take an epub with pictures (any book). If it has only text, koreader can open it without problem.

**Comment by Frenzie** [comment]
I cannot confirm with the juliet.epub from the test suite: https://github.com/koreader/test-data/tree/86eeb0b43d8998d402d203a1ae42d00dbed58037

![screenshot_1542656020](https://user-images.githubusercontent.com/202757/48730383-792c3a00-ec3a-11e8-95f7-2949e64ac326.png)
![screenshot_1542656040](https://user-images.githubusercontent.com/202757/48730384-792c3a00-ec3a-11e8-9450-ce82eba453d7.png)

**Comment by Frenzie** [comment]
Alright, it crashes with leaves.epub.

**Comment by poire-z** [comment]
Was about to write: only png files in juliet.epub. But there is a cover.jpeg in leaves.epub.
But I guess you guessed :)

**Comment by Frenzie** [comment]
Unfortunately figuring that out severely cut into my figuring out if I can fix it time.

**Comment by NiLuJe** [comment]
Might be arm specific ;).

**Comment by Frenzie** [comment]
Oh f*ck no they switched to CMake.

Also apparently I've got too recent Java stuff these days:

```
-compile:
    [javac] Compiling 4 source files to /home/frans/src/kobo/koreader/platform/android/luajit-launcher/bin/classes
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.
```

So… back to ancient 8. Some luck I still have it:

```
$ sudo update-alternatives --config java
[sudo] password for frans: 
There are 4 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-10-openjdk-amd64/bin/java      1101      manual mode
  2            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  3            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
  4            /usr/lib/jvm/java-9-openjdk-amd64/bin/java       1091      manual mode
```

**Comment by NiLuJe** [comment]
Well, that's... not good news? :D.

My plan is basically to say eff it and just selectively rollback to libjpeg-turbo-1.x on Android... :/.

Which is annoying, as, as you've discovered, they switched to CMake, and it could only be used on Win32 in -1.x, so I have to re-import our old CMakeFile... -_-"

**Comment by Frenzie** [comment]
Do they have any Android API-level ifdefs or something in the code? Their readme does have some instructions about API level <15 or 16 (or whatever it said).

**Comment by Frenzie** [comment]
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/BUILDING.md

> If building for Android 4.0.x (API level < 16) or earlier, remove -DCMAKE_POSITION_INDEPENDENT_CODE=1 from the CMake arguments and -pie from LDFLAGS.

I don't think we have those in LDFLAGS, but eh.

**Comment by Frenzie** [comment]
> My plan is basically to say eff it and just selectively rollback to libjpeg-turbo-1.x on Android... :/.

Sorry for the spam, but also note #4348. Selectively on Android legacy then, 'cause it works just fine in Androids more recent than 4.x.

(Where legacy = Android API < 17.)

**Comment by NiLuJe** [comment]
@Frenzie : Huh, yeah, I'd expect issues in the other direction (i.e., trying to run non-PIE code on higher API where it became mandatory), but it certainly can't hurt to try...

We don't have an android-legacy target right now, right?

**Comment by Frenzie** [comment]
No, it'll have to be added, possibly half automated for API <17.

**Comment by Frenzie** [comment]
@NiLuJe I have a fix:

```diff
diff --git a/thirdparty/kpvcrlib/crengine b/thirdparty/kpvcrlib/crengine
--- a/thirdparty/kpvcrlib/crengine
+++ b/thirdparty/kpvcrlib/crengine
@@ -1 +1 @@
-Subproject commit 89b0650e425013da81bc73c6d7676599d8b13c62
+Subproject commit 89b0650e425013da81bc73c6d7676599d8b13c62-dirty
diff --git a/thirdparty/libjpeg-turbo/CMakeLists.txt b/thirdparty/libjpeg-turbo/CMakeLists.txt
index af9d4ed..bda2540 100644
--- a/thirdparty/libjpeg-turbo/CMakeLists.txt
+++ b/thirdparty/libjpeg-turbo/CMakeLists.txt
@@ -39,7 +39,7 @@ endif((DEFINED ENV{CERVANTES}) OR (DEFINED ENV{KINDLE}) OR (DEFINED ENV{KOBO}) O
 # and   https://github.com/taka-no-me/android-cmake
 # In the meantime, I'll be sitting in the corner, crying hysterically.
 if(DEFINED ENV{ANDROID})
-       set(CFG_OPTS "${CFG_OPTS} -DCMAKE_SYSTEM_NAME='Android'")
+       set(CFG_OPTS "${CFG_OPTS} -DCMAKE_SYSTEM_NAME='Linux'")
        # Magical value that inhibits all of CMake's own NDK handling code. (Or shit goes boom.)
        set(CFG_OPTS "${CFG_OPTS} -DCMAKE_SYSTEM_VERSION=1")
```

**Comment by carmelocotonto** [comment]
Hi Frenzie,
I have tried v2018.11.1-34 and crash... but I have been 'looking' into libs and I have seen that several libs call   'libturbojpeg.so.0'   and     'libjpeg.so.8'   instead of  'libturbojpeg.so'   'libjpeg.so', so  I have added  both of them. How?, well I have duplicated  'libturbojpeg.so' and  'libjpeg.so' with the 'correct' name, and now  Koreader  has   libjpeg.so, libjpeg.so.8, libturbojpeg.so and libturbojpeg.so.0.  And all is ok: open epub books with 'jpg'. Perhaps you can do something about it over next versions  8-). Thanks.

**Comment by Frenzie** [comment]
@carmelocotonto See https://github.com/koreader/koreader-base/pull/521

Odd, it worked for me. I'll take another look later this week.

**Comment by Frenzie** [comment]
@carmelocotonto There'll be a new build within half an hour. Could you let me know if it works?

**Comment by carmelocotonto** [comment]
I have tried it and... it woks perfectly. I have not added any extra lib (like before). It's all ok. Wow, congratulations
