### ISSUE TITLE
OPDS catalogs don't display the authors of books listed

### ISSUE THREAD

**Issue by y-muller** [koreader/koreader#4258]
* KOReader version: v2015.11-1800 2018-07-29
* Device: Kobo Clara HD

#### Issue
When browsing an OPDS catalog, only the book titles are displayed, not the authors. It is not very user friendly, especially when browsing by "Most popular" or "Recent entries".
Displaying the author in smaller size under the title, in a similar way to local books, would be very helpful.

#### Steps to reproduce
Menu > OPDS Catalog > ManyBooks (for example) > New Titles
Only the book titles are displayed.

#### Comment
In opdsbrowser.lua both the title and author are known.

**Comment by Frenzie** [comment]
Didn't you do some stuff in the OPDS browser recently @robert00s ?

**Comment by KenMaltby** [comment]
Are the category lists a feature of the OPDS catalog that calibre generates, if so what elements are available for each listing, in each category, may have been determined by calibre.

**Comment by y-muller** [comment]
I'm starting to find my way in the codebase. I can do this, with the author under the title:
![opds_proposal](https://user-images.githubusercontent.com/11664668/47141325-506df900-d2b8-11e8-9f01-0be743167aff.png)

or this, with the author after the title (could be the other way around too):
![opds_proposal2](https://user-images.githubusercontent.com/11664668/47141681-1fda8f00-d2b9-11e8-9e0b-502aa5968f8b.png)

I think two separate lines look nicer. But the single line is what the file browser looks like in classic mode. Comments?

I don't see an easy way of making it look like the CoverBrowser, unfortunately.

**Comment by Frenzie** [comment]
Two lines is fine by me.

**Comment by poire-z** [comment]
> Am I correct in my assumption that the CoverBrowser is tied to the file manager and can't be used to show the data from external catalogs? 

Yes, you are correct.
I've done it in the context of browsing files, with caching metadata in a sqlite db, and background extraction of metadata, and getting back cached metadata from the sqlite db.
So, it probably can't be used as-is easily for something else .

But the code is splitted into parts that deal with displaying alternative views (mosaicmenu, listmenu, parts of covermenu), code for overriding Menu in the context of FileBrowser and History (main.lua, parts of covermenu, quite twisted to make it work to not touch the original core code) and code for caching/extraction/background jobs (bookinfomanager).

If I were to want to use it in other contexts, I would probably extend some parts to accept a `BookinfoProvider`, which would be the `BookInfoManager` by default, but could be some other kind of object (`OPDSBookinfoProvider`) that would not need to do any caching/background (so, no-op for some methods) and would just give back some similar table as the bookinfo objects that are made from the db (title, author, covers, nb of page...). The background extraction and re-update of the items could even be used to fetch the cover images only when needed, and there would just be a in-memory cache of already fetched cover in that OPDS browsing session).

So, it's a quite big project, but seems do-able if you feel adventurous.

(Dunno how twisted/hacky it could be plugged into OPDSCatalog from the plugin, so this plugin may need to be morphed into widgets into core for easier re-use - which is another adventure, see https://github.com/koreader/koreader/issues/3488#issuecomment-344746277)

**Comment by y-muller** [comment]
Thanks for the details @poire-z . I think for the moment I'll stick to easier changes; still figuring things out.
