### ISSUE TITLE
Bookmark on kindle no touch

### ISSUE THREAD

**Issue by pdanc** [koreader/koreader#4260]
* KOReader version: v2018.10.07-beta
* Device: Kindle 4

How to add a new bookmark on kindle with keyboard like kindle 4?

**Comment by Frenzie** [comment]
Pinging @onde2rock 

I'm not sure if it's currently possible, but if not it may not be too hard to add.

**Comment by onde2rock** [comment]
I don't use that function, so I have no idea but I will look, maybe it's an easy fix.

**Comment by onde2rock** [comment]
Alright, It's normally done by tapping the upper right corner.

I propose to add a menu item "Add Bookmarks" just under the already existing "Bookmarks" item if the device doesn't support touch.

Should be quick to do.

@Frenzie : No appimage release anymore ? It's quite usefull to not have to rebuild everything...

**Comment by Frenzie** [comment]
Oh, I forgot to upload it. No time atm but you can find it on Gitlab. :-)

**Comment by Frenzie** [comment]
@onde2rock I added the binary to the release.

**Comment by pdanc** [comment]
Thank you for considering this request. :smiley:
