### ISSUE TITLE
The bottom bar in the reader is controllable with the up and down arrow key

### ISSUE THREAD

**Issue by onde2rock** [koreader/koreader#4263]
* KOReader version: git
* Device: sdl

#### Issue

The bottom bar in the reader is controllable with the up and down arrow key.

~~I guess it's a side-effect of adding key support everywhere, I will look into it.~~

edit:
It only happen with coolReader engine. 
I have narrowed it down to this function https://github.com/koreader/koreader/blob/0924b57877013e9c11be8a0115b76ca498bc6073/frontend/apps/reader/modules/readerrolling.lua#L556

So it's no just a visual problem with the widget, it's actually messing with the saved position of the document.

**Comment by poire-z** [comment]
Looks like it's https://github.com/koreader/koreader/blob/master/frontend/apps/reader/modules/readerpanning.lua that register these keys and generate a `Panning` event.
(never had a look at that module before :)

Guess it's just a matter of adding a test in `ReaderRolling:onPanning()` so that it does nothing when not in pan/scroll mode (like it's done in `ReaderRolling:onPan()`)

```diff
function ReaderRolling:onPanning(args, _)
-   --@TODO disable panning in page view_mode?  22.12 2012 (houqp)
+    if self.view.view_mode ~= "scroll" then return end
    local _, dy = unpack(args)
    self:_gotoPos(self.current_pos + dy * self.panning_steps.normal)
    self.xpointer = self.ui.document:getXPointer()
    return true
end
```

**Comment by Frenzie** [comment]
Hold on, what are you suggesting? I rather like pressing up and down in scroll mode.

**Comment by poire-z** [comment]
It will still work in scroll mode.

But with `if self.view.view_mode ~= "scroll" then return end`, when in page mode, it won't try to use stuff (self.current_pos , panning_steps.normal,...) that probably don't work or are not set up correctly when in page mode.

**Comment by Frenzie** [comment]
Oh, alright. :-)
