### ISSUE TITLE
History page and book sizes

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4266]
Is there any special reason why book sizes aren't included on the History page?

Couldn't it be as it is in the file manager with size to the left of book type (for classic and detailed list)?

**Comment by poire-z** [comment]
What's displayed is not a choice of mine :)

File choser does set-up the (same for classic or cover view) menu items with:
https://github.com/koreader/koreader/blob/717184f1d65a147d90e12ab93afcad2b48d0e310/frontend/ui/widget/filechooser.lua#L237-L244

History does set up the (same for classic or cover view) menu items with:
https://github.com/koreader/koreader/blob/717184f1d65a147d90e12ab93afcad2b48d0e310/frontend/readhistory.lua#L15-L26
There's no `mandatory` for History items.

Classic Menu uses the `text` field on the left, and the `mandatory` field on the right.
Cover menu list view also uses the `mandatory` field for the size part on the right (and adds the file type and % read).

Just building and adding a `mandatory=` with the same code as in filechooser, with the caveat that a file can be in History, but no more on the file system, so with no size, should make it work. **IF** we're fine with getting ALL the sizes for ALL the files in a 500 items long history.
(getting it on the fly would need more work both in filechooser/menu and cover menu - or just intoduce an alternate `mandatory_func` called only when displayed).

**Comment by Frenzie** [comment]
> IF we're fine with getting ALL the sizes for ALL the files in a 500 items long history.

I figured something like that, but I noticed some lfs.getAttributes stuff in the code on a quick skim. But perhaps that's just about the optional deletion thing; like I said I only skimmed.
