### ISSUE TITLE
Can't read the OPDS feed from www.ebooksgratuits.com

### ISSUE THREAD

**Issue by y-muller** [koreader/koreader#4279]
* KOReader version: latest on git
* Device: simulator, Kobo Clara

#### Issue
After adding the "Ebooks libres et gratuits" OPDS catalog, nothing happens when selecting the catalog.

#### Steps to reproduce
Add an entry to the OPDS Browser with the following catalog URL and try to open the new catalog:
```
https://www.ebooksgratuits.com/opds/index.php
```
#### Other info
I have added some logs to opdsbrowser.lua to show the response to the request:
```
<?xml version="1.0" encoding="UTF-8"?>
Error connecting database: No such file or directory
```
The same URL in a web browser or with curl returns the correct feed data.

The same happens going directly to the book list with `https://www.ebooksgratuits.com/opds/feed.php`

I noticed the Autorization header was sent even when there is no password so I removed it. I also tried adding a header for `Accept: */*`. No difference.

I'm out of ideas.

**Comment by poire-z** [comment]
Looks like it works if you add `Host: www.ebooksgratuits.com`
You can extract it from the url with:
```
    local url = require('socket.url')
    local parsed = url.parse(request["url"])
    local hostname = parsed.host
```

(But it seems there are other issues after that, up to 16 slow calls like `opds/feed.php?page=1` to `opds/feed.php?page=16`, and then `INFO  cannot get catalog info from` when I click on a book. But I had never used OPDS before, so I don't really know how it's supposed to work.)

**Comment by Frenzie** [comment]
You can see how it works on Gutenberg and Archive.org, at least from a user's perspective.

**Comment by y-muller** [comment]
Adding the Host header fixed the download of the XML doc. And indeed, things go wrong after that.
- the parsing of the results is not right. I'll look into it; that shouldn't be too difficult as the XML doesn't look particularly different compared to other catalogs.
- this catalog uses linked pages to return large amount of data. For example the recently added section has 2780 books in pages of 100 books. Currently the browser fetches all (or just lots?) of those pages before parsing. So that is really slow.

I'm determined to get this catalog working. It's a massive repository of French language public domain.

**Comment by y-muller** [comment]
I have found the problem. This catalog wraps the book descriptions in a CDATA section and the parser chokes on it. The loading of multiple pages is just a side effect of the failed parsing (tries to load more pages until there enough data to fill a page).

I filtered out the CDATA in OPDSParser:parse to only keep the content with: 
```
text = text:gsub("<!%[CDATA%[(.-)%]%]>","%1")
```
The CDATA section protects against the text containing something that looks like XML and could break the parsing. Is this really something we need to worry about?

**Comment by Frenzie** [comment]
> Is this really something we need to worry about?

Well, yes. CDATA is treated as text, not markup. A `<` in CDATA like `&lt;` outside of CDATA.

https://www.w3.org/TR/REC-xml/#syntax
> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively.

So I'd say you should escape `&` and `<` inside the CDATA if you remove the CDATA.

**Comment by y-muller** [comment]
This seems to do the trick:
```
    text = text:gsub("<!%[CDATA%[(.-)%]%]>", function (s)
        return s:gsub( "%p", {["&"] = "&amp;", ["<"] = "&lt;", [">"] = "&gt;" } )
    end )
```

**Comment by Frenzie** [comment]
Should be good enough for now. :-)
