### ISSUE TITLE
evernote html has odd characters

### ISSUE THREAD

**Issue by milmike0** [koreader/koreader#4280]
* KOReader version: stable version 2015.11
* Device: kindle PW 2

#### Issue Thanks for all your hard work to make koreader so great.
Lately when I export highlights to HTML  and look at the note on the clipboard, the notes are full of statements  such as  less than sign div  greater than sign (lots of these), font size,  margin widths,and lots of others. They take up most of the page before I can see the highlight.  I know that these are format instructions but I really don't need to see all of them. It's not terrible but it is annoying. I reset the kindle, jailbroke, added KUAL and kpv and added a fresh koreader. It made no difference.If I open the HTML document on my PC the highlights look like they used to-the date and page number on one line and the highlight on the next, with spaces between each note.( I take it that's why all the notes end with three div's).  This problem appeared out of the blue-I did nothing to either Koreader or Kindle.
 Koreader works fine except for this. Does any one know what is going on?

Thanks for any response.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Or just https://github.com/koreader/koreader/releases :-)

The Evernote stuff hasn't changed much, but it has indeed received a few changed.

**Comment by milmike0** [comment]
I added an old document to Kindle, saved the notes and they  looked fine. It's just odd that programs get corrupted in such strange ways. Thanks to the responders and keep up the good work.
