### ISSUE TITLE
Does koreader support bluetooth gamepad control? Thanks

### ISSUE THREAD

**Issue by wangandi520** [koreader/koreader#4281]
* KOReader version:koreader-android-arm-linux-androideabi-v2015.11-1868-gb8d9598_2018-10-06.apk
* Device:Android

I have a mini bluetooth gamepad, it works on amazon kindle reader, left is previous page, right is next page,but it seems not work on koreader. it is really comfortable for lazy person like me.

Is there any setting about bluetooth device in koreader, if not, i hope it is a good feature for koreader. Thanks

**Comment by Frenzie** [comment]
Does this gamepad have a d-pad? In theory I think that should already work (e.g., in the menus) even if the other buttons don't perform any actions yet.

Btw, which Android version?

**Comment by wangandi520** [comment]
It is my gamepad https://images-na.ssl-images-amazon.com/images/I/51NFPcJK8yL._SY355_.jpg. My phone is android 8.0. Today i found the "select" button is working as "next page", and other buttons does not work. It is enough for me, thanks

**Comment by Frenzie** [comment]
I'll close this then, but I'll still try to keep it in mind next time I'm looking at Android. :-)
