### ISSUE TITLE
Koreader crashes when logging in Evernote

### ISSUE THREAD

**Issue by sebnapi** [koreader/koreader#4285]
* KOReader version: _koreader-kindle-arm-kindle5-linux-gnueabi-v2015.11-1868-gb8d9598_2018-10-06.zip_
* Device: PW3

#### Issue

Koreader crashes when logging in Evernote

#### Steps to reproduce

Login Evernote

##### `crash.log` (if applicable)
```
./luajit: plugins/evernote.koplugin/main.lua:257: attempt to call method 'find' (a nil value)
stack traceback:
	plugins/evernote.koplugin/main.lua:257: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:204: in function 'action'
	frontend/ui/uimanager.lua:621: in function '_checkTasks'
	frontend/ui/uimanager.lua:845: in function 'handleInput'
	frontend/ui/uimanager.lua:931: in function 'run'
	./reader.lua:216: in main chunk
	[C]: at 0x000139b1

```

**Comment by NiLuJe** [comment]
I assume that's because find gets called on a nil, which I definitely don't get because it's hidden behind an if (true) on that very string...

```
if not ok and guid and guid:find("Transport not open") then
```

```
if not ok and err and err:find("Transport not open") then
```

Unless it's failing to alias find to string.find because reasons?

(have I mentioned how much I find Lua's backtraces terribly unhelpful? :D)

**Comment by NiLuJe** [comment]
Oops, missclick ;).

**Comment by sebnapi** [comment]
> I assume that's because find gets called on a nil, which I definitely don't get because it's hidden behind an if (true) on that very string...
> 
> ```
> if not ok and guid and guid:find("Transport not open") then
> ```
> 
> ```
> if not ok and err and err:find("Transport not open") then
> ```
> 
> Unless it's failing to alias find to string.find because reasons?
> 
> (Have I mentioned how much I find Lua's backtraces terribly unhelpful? :D)

I don't know lua. But if I'm reading it correctly, it can't find the method "find" rather than `err` or `guid` beeing `nil`.

**Comment by poire-z** [comment]
You should try to add between the `ok, err = pcall(...)` and these tests:
`require("logger").warn(type(ok), type(err), ok, err)`
so we see what kind of thing ok and err are, and these values.
Could be we get a table where we expect only nil or a string (that have a :find() method, unlike tables).

**Comment by sebnapi** [comment]
> You should try to add between the `ok, err = pcall(...)` and these tests:
> `require("logger").warn(type(ok), type(err), ok, err)`
> so we see what kind of thing ok and err are, and these values.
> Could be we get a table where we expect only nil or a string (that have a :find() method, unlike tables).

The crash output is:
```
10/23/18-20:00:20 WARN  boolean nil false
./luajit: plugins/evernote.koplugin/main.lua:262: attempt to concatenate local 'guid' (a table value)
stack traceback:
	plugins/evernote.koplugin/main.lua:262: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:204: in function 'action'
	frontend/ui/uimanager.lua:621: in function '_checkTasks'
	frontend/ui/uimanager.lua:845: in function 'handleInput'
	frontend/ui/uimanager.lua:931: in function 'run'
	./reader.lua:216: in main chunk
	[C]: at 0x000139b1
lipc-wait-event exited normally with status: 0
```
(I had to rename the "crash.log" file to get this message, don't know why?!)

**Comment by Frenzie** [comment]
Indeed, something like `if not ok and err and type(err) == "string" and err:find("Transport not open") then` would avoid this, but I haven't read the code in question.

**Comment by sebnapi** [comment]
Ok, I used the Oauth-token and have put it manually inside the settings, I also used a guid for the notebook from a backup. I think the error I have got before while exporting, was due to a expired token. The export worked, I had some errors regarding some of the books, which I can show you here:


```
10/23/18-21:14:31 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:32 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:33 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:33 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:34 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:34 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:36 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:38 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:39 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:40 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:41 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:42 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:42 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:43 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:44 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:44 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:46 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:46 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:47 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:49 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:50 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:51 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:53 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:55 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:56 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:56 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:56 WARN  EvernoteExporter:exportClippings boolean string false plugins/evernote.koplugin/slt2.lua:169: [string "plugins/evernote.koplugin/note.tpl"]:6: attempt to perform arithmetic on local 'time' (a nil value)
10/23/18-21:14:57 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:14:59 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:15:00 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:15:02 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:15:04 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:15:05 WARN  EvernoteExporter:exportClippings boolean nil true
10/23/18-21:15:42 INFO  no dialog left to show
10/23/18-21:15:42 INFO  quitting uimanager
lipc-wait-event exited normally with status: 0
```

**Comment by seacatwu** [comment]
The same bug!
./luajit: plugins/evernote.koplugin/main.lua:257: attempt to call method 'find' (a nil value)
stack traceback:
	plugins/evernote.koplugin/main.lua:257: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:204: in function 'action'
	frontend/ui/uimanager.lua:669: in function '_checkTasks'
	frontend/ui/uimanager.lua:893: in function 'handleInput'
	frontend/ui/uimanager.lua:979: in function 'run'
	./reader.lua:210: in main chunk
	[C]: at 0x000139c1

version:2019.01

**Comment by Frenzie** [comment]
@Galunid Would you be interested in investigating this one?

**Comment by Galunid** [comment]
Evernote plugin got replaced with Exported plugin
