### ISSUE TITLE
[mupdf bug] Can't read POSIX tarballs, only GNU ones

### ISSUE THREAD

**Issue by q3cpma** [koreader/koreader#4287]
* KOReader version: koreader-beta-20181007 "don't read alone tonight"
* Device: Kobo Aura HD

#### Issue
Can't read cbt files (I get "No reader engine for this file"). After debugging on my desktop, the bug comes from mupdf: it can read GNU tar files, but not POSIX ones (created with pax); at least with the 1.13 version.

Guess I should report the bug upstream.

**Comment by NiLuJe** [comment]
Do you know if it behaves any better with mupdf 1.14.x?

**Comment by q3cpma** [comment]
On Thu, Oct 25, 2018 at 07:12:45PM -0700, NiLuJe wrote:
> Do you know if it behaves any better with mupdf 1.14.x?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/koreader/koreader/issues/4287#issuecomment-433263318

No, it doesn't solve it.

**Comment by Frenzie** [comment]
> Do you know if it behaves any better with mupdf 1.14.x?

There's a new MuPDF again? Darn it. :-P

And this one definitely sounds like it might affect us, too. :-)

> Quads instead of rects when highlighting and searching text.

**Comment by NiLuJe** [comment]
Has been fixed upstream, so we'll get it when it lands in a release ;).
