### ISSUE TITLE
Disable all "enhancements"

### ISSUE THREAD

**Issue by q3cpma** [koreader/koreader#4290]
I'm primarly using my kobo aura hd to read mangas, and I already do a lot of post processing in imagemagick before, so I want to disable all resizing and enhancements:
* How to disable the contrast thing? By looking at the segmented bar, I couldn't guess what was the setting equivalent to "disabled".
* Is there a way to prevent all resizing? I'm currently using zoom set to "fit page".
* Are there other things I don't know of?

**Comment by Frenzie** [comment]
* It looks like the second (1.0) is the default contrast.
* Hm, interesting question. There has to be in MuPDF, but there doesn't seem to be an option in the GUI.
* #1833 maybe? :-)

**Comment by q3cpma** [comment]
* Thanks.
* As long as "fit to page" does what it does, I don't thinks it's a problem.
* Definitely the kind of thing I don't want, since I already reduce depth and dither with Floy-Steinberg.
Another quite unrelated question: any way to disable scrolling mode for all documents? I find it pretty annoyin.

**Comment by Frenzie** [comment]
Scroll mode isn't the default, so, um, I don't quite understand the question?

And yes, there should be no cropping unless you choose cropping.

**Comment by q3cpma** [comment]
Ah thanks, the long pressing thing wasn't obvious. (it's the default here, though).

**Comment by Frenzie** [comment]
PS I'd stick to CBZ for comics (not EPUB), regardless of any potential dithering concerns related to the now closed issue I referenced before.

I'll close this one now too.
