### ISSUE TITLE
Is there any plan to release a stable version?

### ISSUE THREAD

**Issue by voq** [koreader/koreader#4292]
Is there any plan to release a stable version?

**Comment by AlanSP1** [comment]
Yes, there are plans, but also, for daily use you don't need stable version. I can use latest nightly just as well. Stable is more just a name, not that it really is most stable version.

**Comment by Frenzie** [comment]
For most intents and purposes tagged basically means stable.

But yes, I've been wanting to add a new base tag for quite a while now, but I keep procrastinating due to what work would/should come after the tagging.

**Comment by KenMaltby** [comment]
Then there might be a wait, to include the latest devices?  Maybe it would be better to establish a point with it working well for all the earlier devices, then bring the new ones on after that point?

**Comment by Frenzie** [comment]
I wouldn't say so because there's always a new device to add. The main wait is probably in translations. We've currently got 8 languages 100% translated and that number should be as high as possible.

**Comment by pazos** [comment]
I would remove the old stable release OR specify the devices that are supported.

**Comment by NiLuJe** [comment]
+1 on burning it with fire ;^p

**Comment by Frenzie** [comment]
Tell you what, I'll create a new annotated stable tag on (probably) Thursday.

Or, pinging @NiLuJe @poire-z @KenMaltby I could use annotated tags for the more or less monthly releases I do moving forward while dropping that "beta" (and "stable") thing. I already moved from calling 'em `nightly` to `beta` for the much the same reason.

The lightweight tags are what is currently used for the betas. Annotated tags will always start counting from the annotated tag (`v2018.11.01-etc`).

This suggestion has vocal support on the forums, though I suppose most people don't really care. I'd never given the versioning much thought since I basically just use the latest from git (that is, the latest automated nightly build).

**Comment by NiLuJe** [comment]
Yep, that sounds sensible to me, and I like it :).

Less potential for confusion, and if we *really* want to keep the notion of a "stable" channel, we could prooobably find a way to retro-fit those tags in there ;).

**Comment by Frenzie** [comment]
I do think we should automate the tagged (stable) and untagged (nightly/"unstable") channel. The only real problem there is that with the current setup, besides the complete lack of support, is that the stable tag is at a risk of being missed completely if a commit was added right after.

Note that I'm thinking of the stable tag in its simplest form as the lack of `-` (i.e., no adding `-stable`, only something unstable like `-beta` would get that). When a commit is the tag, `git describe` is just the tag. It's only when it's a later commit that you get the `tag-##-ghash`.

The nightswatcher container will likely need a copy of git and the basic KOReader repo to do some basic tag-based logic.

**Comment by KenMaltby** [comment]
I think that the average user needs less information than is included in the current download package naming.  The result is a longer file name than is easily handled, or even displayed, in the listing, with the file extension showing.  

For example I use the "Save as" function to turn the download package listed as:

"koreader-kobo-arm-kobo-linux-gnueabihf-v2015.11-1900-gf3ce1c2_2018-10-30.zip"

into "koreader-kobo-v2015.11-1900.zip"

Some other users find the release date to be the more useful discriminator.  

I realize you actual developers need your arcane numbers/tags to find your place in your magical codex, but they are not likely to be used by us mundane users. 

Luck;
Ken

**Comment by Frenzie** [comment]
Good suggestions. A display name would definitely make sense. But for the immediate future I'll just stick to the easy part. :-)

**Comment by Frenzie** [comment]
Fixed by https://github.com/koreader/koreader/releases/tag/v2018.11

I'll make sure it also ends up in the stable OTA channel, hopefully by automating it.

**Comment by zivilyyyn** [comment]
So which OTA channel should I take now, stable or dev?

**Comment by Frenzie** [comment]
That's a personal choice, but the stable's always safe and since we'll tag a new release every one or two months it won't be lagging behind anymore.
