### ISSUE TITLE
Friendly filename

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4297]
* KOReader version: v2018.11
* Device: all

#### Issue
Too much info in filename.

Automatically added compiler info (gnu-abi-etc) can be removed on a case by case basis for a friendly nickname. Cf. 
https://github.com/koreader/koreader/issues/4292#issuecomment-434709291

**Comment by NiLuJe** [comment]
Random thought: that'd potentially break OTA updates, no?

I don't exactly recall the details, but I think that was the gist of the issue when the legacy kindle target temporarily switched names...

**Comment by Frenzie** [comment]
The OTA update already uses "friendly" names. The problem there is more the opposite if anything:

https://github.com/koreader/koreader/blob/349485e240472a0db83e8f85c656bfd63d8c5529/frontend/ui/otamanager.lua#L48-L63

(why doesn't inline code show anymore?)

There's only one `koreader-android-latest-stable.zsync` when we should also have one with i686. Actually it now occurs to me that there might be a disaster waiting to happen there… Okay, one that's easy to fix by reinstalling the correct KOReader apk, but still.

For Kindle the zsync situation is better. We have a `koreader-kindlepw2-latest-stable.zsync`. What we lack there is Lua-side code to detect it.

I forget the specifics of the kindle-legacy thing though. Which issue was that? It's definitely pertinent here.

**Comment by poire-z** [comment]
(Sorry, I was away for a few days, and I missed the ping and discussion in #4292).
Was going to wait for tomorrow and see if what we get is `v2018.11.3` because of 2 new commits, and if I understand how things work. But well:

So, no more git hash like `g1e69fae` anywhere (not even in the `Version` menu? These were quite useful to know what commit went in or not. Without that, you're sometimes doomed to guess it from the others unambigous around, and do some arithmetic.
Or will there be now an automated github "tag", so we can still get the hash from this page?

Also, I would have naively thrown away the date as the first part (and just use "main" or "build", or just "2018") so we don't get v2018.11.17 released the 5th and v2018.11.33 released the 30th - which sound like a date error :) and don't get v2018.11.36 released on 2018/12/03.

**Comment by Frenzie** [comment]
I like the `git-rev` version just fine. ;-) Tomorrow's will (most likely) be `v2018.11.1-3-g42548939_2018-11-02`.

I'm really mainly just talking about the compiler info.

```
koreader-kobo-arm-kobo-linux-gnueabihf-v2018.11.1.zip
```

So you'd get something like this:
```
koreader-kobo-arm-v2018.11.1.zip
koreader-kobo-v2018.11.1.zip
```

Or tomorrow,

```
koreader-kobo-arm-v2018.11.1-3-g42548939_2018-11-02.zip
koreader-kobo-v2018.11.1-3-g42548939_2018-11-02.zip
```

**Comment by KenMaltby** [comment]
Perhaps the version could spear as v2018.11-(sequential number of commits, since start of v2018.11 tag) so for your example it might be v2018.11-003 (can't it be restarted before 999 commits have been added?) That would be obviously not the day field of a date reference, but quickly apparent that it is an advancing  sequential number.

**Comment by pazos** [comment]
> I'm really mainly just talking about the compiler info.

Compiler information is only useful for platforms with 2 or more targets (android & debian).

examples:

```
koreader-kindle-v2018.11.1-3-g42548939_2018-11-02.zip
koreader-cervantes-v2018.11.1-3-g42548939_2018-11-02.zip
koreader-android-armv7a-v2018.11.1-3-g42548939_2018-11-02.apk
koreader-android-x86-v2018.11.1-3-g42548939_2018-11-02.apk
koreader-debian-x86-v2018.11.1-3-g42548939_2018-11-02.deb
koreader-debian-x86_64-v2018.11.1-3-g42548939_2018-11-02.deb
koreader-appimage-v2018.11.1-3-g42548939_2018-11-02.AppImage
```  
> Perhaps the version could spear as v2018.11-(sequential number of commits, since start of v2018.11 tag) 

I like this as a short version string. I think most users won't need the full version unless they're reporting an issue, so I would use a short version in "version" and "about" popups and leave the full version from git-rev in "report bugs"

Finally, on android I would append the "flavor" at the end of version (short and full)

**Comment by KenMaltby** [comment]
The "spear" should have been appear.  Making the sequential numbering having leading zeros, like 003 or 053, means that they will sort into the proper order.

**Comment by Frenzie** [comment]
> Compiler information is only useful for platforms with 2 or more targets (android & debian).

Disagree, at least for AppImage. Being able to tell at a glance that it won't work on anything but x86_64 is definitely not a bug.

Kobo/Kindle/etc. is a different story.

**Comment by NiLuJe** [comment]
On Kobo/Kindle, the target name should be more than enough, yeah ;).

I'd go so far as to chop down the git rev to tag-commitsamountsincelasttag (i.e., drop the commit hash & date), as long as that info (commit hash & date) is still shown somewhere (ideally, the log startup).

**Comment by Frenzie** [comment]
@NiLuJe 
> I'd go so far as to chop down the git rev to tag-commitsamountsincelasttag (i.e., drop the commit hash & date), as long as that info (commit hash & build date) is still shown somewhere (ideally, the log startup).

The date is there by popular demand because people thought the number was unclear. But of course if we're only talking about the filename that's a different matter than the version. For the filename just `koreader-kobo-v2019.02-132.zip` would do the (backwards-compatible) trick.

**Comment by poire-z** [comment]
I'd like to keep the hash, for the edited reason pointed out by @NiLuJe : bissecting & co, and its easier to see what went it or not - and to know about nightly I keep backups of. I remember a time when for some reason, I was counting (ok, today is 124, this one I have is 117, so, go to github commit page, count backwards -7, ok this commit is in 117, or is it +1 or -1...).

**Comment by Frenzie** [comment]
Yes, I also think it's perfect. tl;dr I stand by https://github.com/koreader/koreader/issues/4297#issuecomment-435503285 

I was just saying that, technically speaking, `v2019.02-132` is all that's used by the OTA update.
