### ISSUE TITLE
Disable front-light tap switch

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#4300]
* KOReader version: 2018.11.1
* Device: Glo (nonHD)

When a tap at the lower left part of the screen, the front-light is turned on/off although the front-light gesture controller is disabled.
Just in case, I enabled the controller - exited - disabled it - exited and re-checked.
Still, the light is turning on/off by tapping the lower left corner...

**Comment by pazos** [comment]
@noembryo Settings (gear?)->device->gesture manager->tap left bottom corner -> Nothing

:smile:

**Comment by Frenzie** [comment]
Still shouldn't happen if that plugin is disabled though?

**Comment by noembryo** [comment]
Xm, there is no device menu entry anywhere..
I wonder if that has to do with the fact that I added an extra shutdown entry some months ago, but I don't remember how :o(
When I see the `reader_menu_order.lua` i can see the device sub-menu but not when in koreader.

**Comment by Frenzie** [comment]
Ah, @pazos is right. It looks like we made the bottom-light tap part of the core in #4240, basically obsoleting that part of the frontlight gesture controller plugin.

As an aside, the adjective order in that menu is wrong. It should be bottom left and bottom right corner.

@noembryo Custom menu orders would be in the settings subdir.

**Comment by noembryo** [comment]
Ahh, OK, found it..
I have to remember to check this with every update :o)
..but there is another problem with the left bottom corner.
I use `DTAP_ZONE_CONFIG = {x = 0, y = 7/8, w = 1/12, h = 1/8}` in the `defaults.persistent.lua` to have the bottom menu open when I press this corner.
Now this is almost gone. I can still occasionally hit a spot where it works, but overall it does not coming up anymore. Does that mean that although the "Tap left bottom corner" is disabled, it keeps the position blocked?

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by noembryo** [comment]
Also, I think that the image (with the hand sketches) that shows up when we open the "Front-light gesture controller" for helping us to understand the usage, must not include the hand that taps the bottom left corner anymore...

**Comment by pazos** [comment]
> Perhaps we could add the opening of the bottom menu to the options of the bottom corners tap?

I would like this too, but this is specific for the reader application and thus not available in the filemanager.

**Comment by cramoisi** [comment]
@Frenzie : "It looks like we made the bottom-light tap part of the core in #4240, basically obsoleting that part of the frontlight gesture controller plugin." do you plan to correct it ? I think it's a great feat (because I love to have the on/off corner but I hate to have the slider enable :) )

**Comment by Frenzie** [comment]
So just don't turn on the plugin? Not sure I follow. But try pinging the author first. ;-)

**Comment by cramoisi** [comment]
I mean : I don't like the plugin because I don't like the gesture on the side of the screen to adjust luminosity / warmth. I only like the on/off feature on the corner. I already edit the plugin to have that but I think it's better to keep the plugin as it is, disable it and use the on/off introduce by the gesture manager...

**Comment by Frenzie** [comment]
I'm afraid I'm still not following. What's the concrete problem you're having with turning off the plugin?

**Comment by cramoisi** [comment]
none :) I was asking if this override of the plugin by the gesture manager will stay or not.

**Comment by noembryo** [comment]
I think that there are looked upon as two different things.
The plugin that enables the side-gesture and the bottom corner hotspots...

**Comment by poire-z** [comment]
> I was asking if this override of the plugin by the gesture manager will stay or not.

See https://github.com/koreader/koreader/pull/4240#discussion_r220166095 by @robert00s : 
> I want to migrate all kobolight (Frontlight gesture controller) to readerfrontlight + readergesture and remove completely this plugin.

**Comment by robert00s** [comment]
This should be fixed in #5156
