### ISSUE TITLE
Kindle4NT no screensaver

### ISSUE THREAD

**Issue by iq89** [koreader/koreader#4305]
* KOReader version: v2018.11.1
* Device: Kindle4NT 4.1.3 Firmware - No ads version 

#### Issue
Upon sleep/manual lock the screen does not change from the current image, device does lock but no screensaver image
There is no option for the screensaver in the settings menus either

#### Steps to reproduce
Install latest release
Lock/Let the kindle time out to sleep
View options menu

##### `crash.log` (if applicable)j
not sure if applicable, can upload it needed

**Comment by Frenzie** [comment]
Pinging @NiLuJe @robert00s who know more about the Kindle ecosystem.

From a quick glance it looks like your Kindle would have a library loaded that's associated with ads: 
https://github.com/koreader/koreader/blob/42548939bc0e8a1e6d276f9079ad7d05d79a3b6e/frontend/device/kindle/device.lua#L22-L47

**Comment by NiLuJe** [comment]
Yep, did your device ever have special offers enabled?

**Comment by xelxebar** [comment]
By chance I ran into this issue myself yesterday. For the moment, I just patched `koreader/device.lua` so that `Kindle:supportsScreensaver` unconditionally returns true.

It seems to be working just fine at the moment, though I keep my device in airplane mode which might be revelent. However, should I anticipate problems with my patch? For that matter what is the intent/purpose behind the `ad_screensavers` check?

**Comment by NiLuJe** [comment]
Detecting SO devices because they're weirder in how they expect standby to behave.

**Comment by xelxebar** [comment]
@NiLuJe What's the "Right Way" to get screensavers working on SO devices? I'd be willing to hack around a bit if you could point me in the right direction.

**Comment by xelxebar** [comment]
@Frenzie, Oooh. It's a principled stance, not a technical barrier...

**Comment by NiLuJe** [comment]
Both, actually, since the ad module really is more finicky.

**Comment by samba2** [comment]
I also have a Kindle 4.1.3 starting KOReader via KUAL. I also have the same issue - no screensaver is displayed but the device apparently sleeps.

As suggested above I made `koreader/device.lua` `Kindle:supportsScreensaver` return "true". When I now press the sleep button the current KOReader screen freezes and an info popup "Sleeping" is displayed. When I press "sleep" again, the popup disappears and I can continue working with the device.

However, the screensaver is stil not displayed. 

Regarding the "ads" thing which was mentioned before: I am new to Kindle, jailbreaking and so on so maybe I miss one of the extensions/ plugins?

**Comment by xelxebar** [comment]
@samba2 When screensaver support is enabled, you should see a "screensaver" option in your settings. This is where you can tell it to display an image and whatnot.

**Comment by NiLuJe** [comment]
Okay, yeah, that check makes no sense on FW < 5.x, because there's no blanket there.

Will look into an alternate solution, because SO *are* supported there nonetheless...

**Comment by samba2** [comment]
> @samba2 When screensaver support is enabled, you should see a "screensaver" option in your settings. This is where you can tell it to display an image and whatnot.

You where absolutely right. I was able to change the screensaver behaviour in the settings.

**Comment by NiLuJe** [comment]
I forgot to mention that, no, I unfortunately did not find a great way to detect SO devices on FW < 5.x.

**Comment by jaboto** [comment]
I had the same issue with my Kindle Version 4.1.3 (2692310002). Never had advertisement screensavers but the screensaver option was not available in Koreader (v2019.09.3).

Modifying the _device.lua_ in _/koreader/frontend/device/kindle_ so the `Kindle:supportsScreensaver` returns always `True` fixed the issue.

Thanks @xelxebar !
