### ISSUE TITLE
Popup footnotes: chapter titles in footnote text

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4309]
* KOReader version: v2018.11.1-5-g472b9cf_2018-11-05
* Device: KA1

#### Issue
Not all books have this issue, but it's rather common. If I choose 10 random books with footnotes, maybe 3, 4 or 5 have the problem.

Issue:
The text in the last footnote in chapter contains next chapters title. See picture:

![reader_2018-nov-06_072801](https://user-images.githubusercontent.com/32645430/48050628-b3a9c780-e1a2-11e8-8b6e-88f350e0b4eb.jpg)

**Comment by poire-z** [comment]
I can witness that with your _The strange death of Europe_ book.

<kbd>![image](https://user-images.githubusercontent.com/24273478/48052868-709f2280-e1a9-11e8-8477-e3be42601ed1.png)</kbd>

```
11/06/18-09:57:29 DEBUG Checking if link is to a footnote: 57206 /body/DocFragment[8]/body/section/p[61]/sup/a.0 #_doc_fragment_24_ c04-f25
11/06/18-09:57:29 INFO  is a footnote: source has all content shifted by vertical-align
11/06/18-09:57:29 INFO    extended until: node with 'id=' attr met
11/06/18-09:57:29 INFO  /body/DocFragment[25]/body/section/p[64].0
11/06/18-09:57:29 INFO  /body/DocFragment[25]/body/section/p[65]/text().19
```

The footnote code tries to grab as many "blocks" following the block that contains the target ID, until it finds one that looks like it must be another footnote, or a new chapter, or a new page.
The red block is just a `<p class="h1">`, that does not look enough like it's not part of that footnote. So, it's included (if it had been a proper `<h1>`, it would not have been included).

On this book, all footnotes are a single paragraph: not a single one with a new line.
But I have some other books where a single footnote might be multiple paragraphs, and the target ID is **in** the first paragraph - ie: the ID is not on an element that would surround all the paragraphs. So, I had to add code to extend the selection to grab more.

So, this warning:
<kbd>![image](https://user-images.githubusercontent.com/24273478/48053277-98db5100-e1aa-11e8-96f7-c8942038bf44.png)</kbd>

Not sure how to help with that.

An option to not extend that would disable this flag:
https://github.com/koreader/koreader/blob/472b9cf32aebcec0d705eea9a20721ae6794c729/frontend/apps/reader/modules/readerlink.lua#L966-L967
(you can try commenting out that line, but you may miss parts of footnotes with other books).

A style tweak so you can set `.note1 {-cr-hint: footnote}` so it's not extended.
https://github.com/koreader/koreader/blob/472b9cf32aebcec0d705eea9a20721ae6794c729/frontend/apps/reader/modules/readerlink.lua#L924-L928

Or just live with it ? :)

**Comment by gerhaher** [comment]
Ok, thanks.
No big deal for me, so yes, I can live with it.

**Comment by Frenzie** [comment]
Closing now.
