### ISSUE TITLE
How to install new stable version?

### ISSUE THREAD

**Issue by Nanco300** [koreader/koreader#4310]
* KOReader version:2018-10-30
* Device:Kobo Glo

I desire to know how install stable version on older version.

**Comment by NiLuJe** [comment]
https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices#what-about-manual-updates

**Comment by NiLuJe** [comment]
Depending on the age of your current installation (and your launch method) there may be a `.kobo` -> `.adds` move involved.

**Comment by Nanco300** [comment]
Thank you. Solved.
