### ISSUE TITLE
OTA update broke

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#4312]
* KOReader version: 2018.11.1-5
* Device: Kobo Aura HD & Kindle Voyage

#### Issue

OTA does not work after recent changes.

#### Steps to reproduce

Install 2018.11.1-5 and try to update to -8. But it does not work with KOReader is up to date message.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Fixed in #4308.

**Comment by Hzj-jie** [comment]
Awesome, thank you.
