### ISSUE TITLE
Popup footnote when going from portrait to landscape (or vice versa)

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4315]
* KOReader version: v2018.11.1-5-g472b9cf_2018-11-05
* Device: KA1

#### Issue
Popup footnotes don't follow when going from portrait to landscape (or vice versa). 
#### Steps to reproduce
1. Start KOReader and open a popup footnote in a book in portrait mode.
2. Change to landscape. Open a popup footnote. It will look like this:
 
![reader_2018-nov-09_161240](https://user-images.githubusercontent.com/32645430/48271767-6006da80-e43d-11e8-8a2f-5e4051e187ea.jpg)

3. Restart KOReader and now open a popup footnote in a book in landscape. It will look as it should:

![reader_2018-nov-09_161915](https://user-images.githubusercontent.com/32645430/48271970-d9063200-e43d-11e8-9dc9-71fc797edeea.jpg)

4. And then open a popup footnote in a book in portrait. It will look like this:

![reader_2018-nov-09_161400](https://user-images.githubusercontent.com/32645430/48272071-11a60b80-e43e-11e8-85ac-a796f57e7597.jpg)

**Comment by poire-z** [comment]
Thanks for the report. Easily fixed in #4316.
