### ISSUE TITLE
FR: Launcher

### ISSUE THREAD

**Issue by zaoqi-unsafe** [koreader/koreader#4317]
Can it become a OS/launcher?A OS/launcher for ebook readers.

**Comment by zaoqi-unsafe** [comment]
It seems easy.There are koreader / frontend/apps and koreader / plugins without document.

**Comment by Frenzie** [comment]
Sounds like a job for a plugin. ;-)

**Comment by Frenzie** [comment]
I'll close this as likely largely attained by <https://github.com/koreader/koreader/pull/5804>.
