### ISSUE TITLE
Footnotes navigation problem

### ISSUE THREAD

**Issue by Nick1412** [koreader/koreader#4319]
* KOReader version:KOReader version: v2018.11.1 for android
* Device: Likebook Mars T80D / Android 6.0

When I click on a footnote link in an .epub book it sometimes takes me to an unrelevant page.
And it's hard to easily go back because "Back to previous location" is also not active in such cases.
Also, clicking on a footnote to go back to the original location sometimes takes me somewhere else.

**Comment by Frenzie** [comment]
Pinging @poire-z about footnotes. I think "go back to previous location" should always be available after clicking a link?

Note that on Android you can always easily go "back" with the back button of your device.

**Comment by poire-z** [comment]
By _sometimes_, you mean (multiple choices possibles :):
a) it always happens with some specific books, and never happens with others?
b) it happens and sometimes not happens on a same book, but it always happens with a same footnote link and not with some others links
c) it happens and sometimes not happen if you tap on a same link

If a) or b), sharing such book, with some indication of where to find a link where it happens would help.

The nearest thing I could think of is tapping a bit outside the link (or thinking that what looks like a footnote link is a link, when it's just text with no link - you can check by selecting text around and using the new `View HTML` to see if there's really a `<a href=>`) and getting to the previous or next page... Which in this case would not register as a link, so no back history to go back to.
So, tell the original page number, and the page number of the "unrelevant" page number you are bring to.

(I guess we're not talking about the new footnote display at bottom.)
Anything in crash.log ? like `not coherent a_xpointer: /blah/bluh/...` which could explain it a bit.
If you haven't yet, enable `Show footnotes in popup` which may log a few more lines about what's happening, which could help understanding.

Dunno if this could be something specific with Likebook/Android.

**Comment by poire-z** [comment]
> I suspect it happens because the footnote number is in the touch-screen area of next-page or previous-page.

It shouldn't, as the "is the tap on a link?" check is done before the "is tap on the next or prev page areas?" check in the code.
Might it be that the footnote link is really small, in which case you're not tapping on the link but just a bit out of it?
In that case, there's a new option added recently to help with that:
<kbd>![image](https://user-images.githubusercontent.com/24273478/48302095-0fa08300-e4f8-11e8-8771-6e2c25b3dcf7.png)</kbd>
Could you check if it helps?

**Comment by Nick1412** [comment]
Thanks. It did the trick and also helped me realize that I didn't have 
the latest version with the new menu items (including the very 
convenient "show footnotes in popup").

So, issue resolved :-)
I'm new here and must say it's very nice to receive such quick and 
detailed help from the community!


------ Message d'origine ------
De: "poire-z" <notifications@github.com>
À: "koreader/koreader" <koreader@noreply.github.com>
Cc : "Nick1412" <nebo2007@gmail.com>; "Author" 
<author@noreply.github.com>
Envoyé : 10/11/2018 14:53:02
Objet : Re: [koreader/koreader] Footnotes navigation problem (#4319)

**Comment by Frenzie** [comment]
> helped me realize that I didn't have the latest version with the new menu items 

But you said that you were using v2018.11.1? That was one of the new features in it. ;-)

See https://github.com/koreader/koreader/releases/tag/v2018.11
