### ISSUE TITLE
TOC navigation in portrait mode broken (epub)

### ISSUE THREAD

**Issue by samba2** [koreader/koreader#4328]
* KOReader version: 2018.11
* Device: Kindle 4.1.3

#### Steps to reproduce
- open a epub file
- file is by default displayed in portrait mode
- open TOC and navigate to a section -> works
- change orientation to portrait
- open the TOC again and navigate to a different section
- some page is opened which is far away from the chosen section

**Comment by Frenzie** [comment]
As a workaround, it should probably do the trick if you close the document and reopen it.

**Comment by poire-z** [comment]
Can't reproduce (even with my now usual suspects: scroll mode and/or full status bar).
But that's the kind of thing that did happen in some conditions when some kind of reset was missing, and we fixed the ones we discovered.

Are you sure you have the latest version 2018.11 (top right menu item > Version)?
Any specific configuration (status bar, scroll or page mode, others)?

Btw, just witnessed a crash when in scroll mode, opening TOC after toggling orientation...:
```
./luajit: frontend/apps/reader/modules/readertoc.lua:115: attempt to compare nil with number
stack traceback:
        frontend/apps/reader/modules/readertoc.lua:115: in function 'getTocIndexByPage'
        frontend/apps/reader/modules/readertoc.lua:386: in function 'onShowToc'
        frontend/apps/reader/modules/readertoc.lua:475: in function 'callback'
```
Probably some reset of stuff misssing again. Might be related or not to this issue.

**Comment by poire-z** [comment]
(Seen the other issue about that kindle being non-touch - might be different code paths are taken to toggle orientation and needed reset not made in the non-touch path.)

**Comment by samba2** [comment]
> As a workaround, it should probably do the trick if you close the document and reopen it.

Just tried that _without success_:
- open the epub in portrait
- changed orientation to landscape
- went back to file browser by pressing "home" button
- select epub again
- file is opened in landscape
- jump to a specific TOC section

**Comment by samba2** [comment]
> Can't reproduce (even with my now usual suspects: scroll mode and/or full status bar).
> But that's the kind of thing that did happen in some conditions when some kind of reset was missing, and we fixed the ones we discovered.
> 
> Are you sure you have the latest version 2018.11 (top right menu item > Version)?
> Any specific configuration (status bar, scroll or page mode, others)?
> 
> Btw, just witnessed a crash when in scroll mode, opening TOC after toggling orientation...:
> 
> ```
> ./luajit: frontend/apps/reader/modules/readertoc.lua:115: attempt to compare nil with number
> stack traceback:
>         frontend/apps/reader/modules/readertoc.lua:115: in function 'getTocIndexByPage'
>         frontend/apps/reader/modules/readertoc.lua:386: in function 'onShowToc'
>         frontend/apps/reader/modules/readertoc.lua:475: in function 'callback'
> ```
> Probably some reset of stuff misssing again. Might be related or not to this issue.

Version is v2018.11.1
I enabled/ disabled the status bar with no success.
I have view mode "page" (not "scroll") configured.

**Comment by Frenzie** [comment]
What do you mean by far away precisely?
