### ISSUE TITLE
Fulltext search: got stuck on a mysterious page

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4331]
* KOReader version: v2018.11.1-9-g5d68076_2018-11-09
* Device: KA1

#### Issue
When I perform a fulltext search I got stuck on one strange page (see picture below). 

Here is the book in question if someone wants to play with it: 
[Reclaiming History_ The Assassi - Vincent Bugliosi.zip](https://github.com/koreader/koreader/files/2569742/Reclaiming.History_.The.Assassi.-.Vincent.Bugliosi.zip)

When I arrive at this page 69 during fulltext search I can't jump forward (using > or >|). 
And, if the word appears on page 68 too, I can jump backwards only once (i. e. to page 68) and then I got stuck there. '|<'  seems to work from 69 but only sometimes from 68. From page 68 I can use '>|'.

If I start a new search when I am on this page 69 (and the word appears on the page) following happen:
1. The search words don't become grey.
2. When I tap '<', the words become grey - with some exception I noticed:
 If I search for "finally" (appears twice on the page) only the second becomes grey when tapping
 If I search for "just" (appears one time) I get to page 68 instead when tapping
 Same thing (get to page 68) happens when I search for "Oswald" (appears 4 times)

If I change font size or disable full progress bar, so that the text floats in another way on the pages, the stucking problems disappear completely.

![reader_2018-nov-11_184655](https://user-images.githubusercontent.com/32645430/48317152-5c668580-e5ee-11e8-8554-dc847a0eb0d7.png)

**Comment by gerhaher** [comment]
OK, I think it has to do with the fat style letter in the beginning of the page.

After changing font style I found another page with the same problem with fat letter in the beginning.

**Comment by poire-z** [comment]
Referencing a few others: https://github.com/koreader/koreader-base/pull/595 https://github.com/koreader/koreader/pull/3656 https://github.com/koreader/crengine/pull/95
(Glad I wrote a lot and put some comments in the code, but it's still hard to get familiar again with this code...)

But I can't manage to reproduce it (hard given the differences in geometry/font/... and that that text is not on page 68 or 69 for me :) even if I manage to align that fat letter to top of screen with a style tweak `.spaceBreak {page-break-before: always}`.

Just a thought while re-reading my comments: does it happen the next page and the one after next, or previous and the one before previous, are a single paragraph: to check for things on previous page, it needs to find a HTML node that starts on the page before - if that node started even before that page before, if may fail.

The only explainable thing is the first `Finally` not being matched: the code searches for the text in each individual node text. For the `Finally` with the fat `F`, it's 2 nodes:
<kbd>![image](https://user-images.githubusercontent.com/24273478/48347266-09d4aa00-e67e-11e8-88d6-59e1601379d8.png)</kbd>
So, `inally` would be matched, but not `Finally`. Quite not straightforward to implement inter/multi-nodes matching...

**Comment by gerhaher** [comment]
Some more info.

I have found several more pages with the same problem, all had this fat letter word beginning.

But compare below pictures with the same text. In the first picture there was no stucking problem (although the searching didn't recognize Hugh). In the second picture the page has a little more empty space at the top of the page (after some changes I've made with the text). Now the stucking was there.

So it seems that the problem occurs when the page begins with a fat letter word and has an empty line (or at least some empty space) at the top of page.

![reader_2018-nov-12_145104](https://user-images.githubusercontent.com/32645430/48353546-fc282000-e68f-11e8-88ed-256b6f29b6a8.jpg)
![reader_2018-nov-12_145135](https://user-images.githubusercontent.com/32645430/48353548-00543d80-e690-11e8-9d5a-9bf4c6890d1b.jpg)

**Comment by poire-z** [comment]
Got that page with **H**ugh at the top, but I'm not stuck with any 4 buttons (even after hacking th HTML to add some text to the previous page to make it go lower...)
`after some changes I've made with the text`: some changes hacking the HTML inside the EPUB, or just toying with koreader settings?

And you are stuck no matter what term you search from that page, even simple words like "he" or "to" ?
And which of the 4 `|< < > >|` are stuck?

**Comment by gerhaher** [comment]
I couldn't reproduce the issue with my other device, a Kobo Aura with KOReader version: v2015.11-1877-g76a3d20_2018-10-11. 

After updating to latest KOReader version I can reproduce it.

**Comment by poire-z** [comment]
Oh, good, so it means it's something new (although it's still possible the new stuff just cause a different layout that just triggers that behaviour by chance).
Could you try `v2018.11.1-3-g4254893_2018-11-02` vs  `v22018.11.1-4-g26aeb61_2018-11-05` ?
Between these were introduced the vertical-align and other minor commits (including ignore space at start of line, which could ring with your observation about space-only line.

Btw, that ignore space commit was tweaked in this morning nightly `v2018.11.1-21-gf92136e_2018-11-11`, but it's the _latest KOReader version_  you said you tried, so no fix by chance :)

**Comment by gerhaher** [comment]
Actually with latest version in above post I meant `v2018.11.1-9-g5d68076_2018-11-09`. 
I've missed the two latest updates as they weren't at the bottom of the download/nightly-page. :-)

After updating to the _real_ latest version the stucking problem is gone. 👍

Problem solved!

Thanks.

**Comment by poire-z** [comment]
Phew, glad it is ! and that I don't have to dig into that code :)
