### ISSUE TITLE
Status bar can't be re-enabled when "activate menu" is set to "tap"

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#4332]
The status bar can be tapped to hide it. Then, tapping the bottom of the screen shows it again.
However, once hidden, if "activate menu" is set to "only tap" or "swipe and tap", it cannot be re-enabled. Tapping the bottom of the screen shows the menu instead. 

Unfortunately, there is no way to re-enable the status bar from a menu, either. The only way to get the status bar back is to set "activate menu" to "only swipe". Then tapping the bottom of the screen makes the status bar re-appear as expected.

**Comment by poire-z** [comment]
I have activate menu set to only tap and I can show/hide the bottom status bar with tap.
But the bottom area size has been reduced some months ago by #4099.
See https://github.com/koreader/koreader/issues/4028#issuecomment-430372222 and following posts on how to increase it again if needed.
(Unless you have increased DTAP_ZONE_CONFIG or DTAP_ZONE_MENU so they take fhe full screen height and leave no room for DTAP_ZONE_MINIBAR).

**Comment by pickx** [comment]
@poire-z you're correct, I can get it to work now when aiming lower. I can't understand why I could never do it earlier.

**Comment by pickx** [comment]
Okay, I seem to have identified a problem. Tapping to activate the status bar initially works with menu set to "tap", however it then stops working.

@poire-z can you confirm this behavior please?

1.  restart KOReader, open file in portrait orientation, tap bottom, status bar hides/unhides
2. hide status bar
3. switch to landscape orientation (via menu)
4. tap bottom, can't show status bar, only open menu
5. switch back to portrait orientation
6. tap bottom, still can't show status bar
