### ISSUE TITLE
kobo aura one touch panel calibration

### ISSUE THREAD

**Issue by colorfulshark** [koreader/koreader#4345]
* KOReader version: v2018.11
* Device: kobo aura one

#### Issue
Actually this is not a bug of koreader, but kobo device itself. I got a kobo aura one and I found that the touching coordinate is a little left off to the place where the finger really touch. This is annoying when I try to select text. What's worse, the right edge of screen is untouchable at all. I have seen many aura one users meeting this problem.

I don't know if this is a hardware issue or touch panel driver issue. I wander if there is any feature in koreader which make it easy to calibrate the touch panel, or display the coordinate in screen?

#### Steps to reproduce
When koreader runs on kobo aura one.

**Comment by Frenzie** [comment]
We don't have calibration as such but we do have adjustment hooks:

https://github.com/koreader/koreader/blob/fb1c3606d7e787506d33f56e0d3de51bd468280d/frontend/device/input.lua#L177-L187

https://github.com/koreader/koreader/blob/fb1c3606d7e787506d33f56e0d3de51bd468280d/frontend/device/kobo/device.lua#L381-L417

You'd have to write your own function to shift things a few pixels to the right. But of course the right edge of the screen could never become touchable.

Sorry, this is just a short break quickie so I can't be more help. ;-)

**Comment by NiLuJe** [comment]
It supposedly got a bit better on very recent FWs, that may also be something to explore.

**Comment by NiLuJe** [comment]
@Frenzie : Nope, H2O only ;).

**Comment by AlanSP1** [comment]
From my experience touch on KA1 is relatively bad (worse than on H2O), but something like simple calibrating tool could be useful.

**Comment by colorfulshark** [comment]
@NiLuJe 
Instead, the latest firmware(4.10) is worse. I wrote a hook function in koreader to test, and the result is interesting.

I found that about 5mm width area at both left and right edge of screen is untouchable. At first I think it is a hardware broken problem, but considering the touching offset, I think that kobo may know this hardware defect, so they modified the firmware and then we can trigger the button on the edge of screen. In the left half of screen, the touching offset to right, and in the right half side, it offset to left, which makes every touch point is inaccuracy. This seems like using a 6.8-inch touch panel cover a 7.8-inch screen. And the touch area is squeezed.

Actually this problem has little influence in nickel, because the margin of operation page is large. But when we use koreader, the margin is small and we often need to touch the edge of screen, like modifying light. And when we use landscape, the offset becomes up and down, which makes it even worse.

@AlanSP1 
So, it is impossible to calibrate because the touching area is smaller then the display area.

**Comment by AlanSP1** [comment]
Well, I didn't test it, but I noticed many problems with touch accuracy on my KA1. What's going on and why, I don't know.

**Comment by athompso** [comment]
As a Kobo Aura One user, I'm not experiencing dead spots, but I am experiencing real-time calibration drift.  Which should be impossible, but hey, maybe someone saved a few pennies on the touchscreen layer.

It currently makes it nearly impossible to reliably activate the "..." menu beside each book.  In spots, like the drop-down sorting/filtering menus, I have to tap almost 1/4" to the left of my intended targe.

I would return it as bad hardware, but every firmware release changes the nature of the touch problems I have, which tells me it's not the hardware that's the problem...

Thoughts?  Suggestions?  Go bark up another tree somewhere?

**Comment by NiLuJe** [comment]
Yeah, the KA1's touch layer is crap. They may be attempting to heuristically tweak it at runtime, but the root cause is likely hardware, and not necessarily consistently crappy across every device, which would render heuristics even more wonky in practice.

**Comment by Frenzie** [comment]
You can also slide down from the top right to open that menu straight away. You could also try increasing the DPI value so everything displays larger.
