### ISSUE TITLE
Android 9 objects to apps using an API older than 17

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4348]
* KOReader version: v2018.11
* Device: Android 9 emulator

#### Issue
For now it's only an annoying but harmless message on the first run, but this might mean being blocked from running on the next version.

![screenshot_1542647896](https://user-images.githubusercontent.com/202757/48723697-a0c5d700-ec27-11e8-8924-fc091e36ff74.png)

Annoyingly, while we can drop 2.3 (API 9) instead of fixing it,[1] API 17 means Android 4.2 and supporting Android 4.0 (API 14) is quite desirable with regard to Onyx and other devices.

Some background info: https://www.digit.in/software/android-p-could-barr-running-apps-built-for-android-41-or-lower-versions-40064.html

This means the dreaded moment of switching to something like an old API build (same as now) as well as a new one (Android 5+? 6+?) might have arrived. But if we do that we should probably fix 2.3 just because.

Any thoughts @NiLuJe @poire-z?

I suppose it should be called `android-legacy` by analogy with Kindle.

#### Steps to reproduce
Run KOReader for the first time.

[1] It was accidentally broken over a year ago.

**Comment by poire-z** [comment]
> This means the dreaded moment of switching to something like an old API build (same as now) as well as a new one (Android 5+? 6+?) might have arrived

You mean having 2 builds, making 2 different apk at each nightly? (ok, saw your edit: `android-legacy` indeed).
(But don't we build multiple already in koreader-base CI ? NDKREV=11, 12, 15/14)
Well, if we have to... Not much thoughts :|

**Comment by Frenzie** [comment]
Yeah, but that's just for developers to ensure you can build it with your own TC if you want to. Since another year passed it's not entirely unreasonable anymore to drop all of those older ones, see https://github.com/koreader/koreader-base/pull/510#discussion_r139290793 That'd mean a minimum API level of 14 (4.0), which is the minimum SDK 26 supports.

Adding more cruft to the release goes a bit further than that. ;-) Also the API level isn't reflected in the current release name. It'd definitely require effort in the Makefiles besides more Docker images, etc.

And even I constantly have to look up what means what in [my notes](https://github.com/koreader/koreader/wiki/Development-and-Debugging-on-Android#api-levels).

**Comment by Frenzie** [comment]
Quick brain dump since I don't have time to experiment and I might forget otherwise:

```diff
diff --git a/Makefile.defs b/Makefile.defs
index 0fd229e..978cce8 100644
--- a/Makefile.defs
+++ b/Makefile.defs
@@ -18,6 +18,12 @@ ANDROID_TOOLCHAIN=$(TOOLCHAIN_DIR)/android-toolchain-$(ANDROID_ARCH)
 NDK?=$(TOOLCHAIN_DIR)/android-ndk-r15c
 NDKABI?=9
 
+# API level lower than 17 causes Android 9 to complain
+ifeq ($(shell test $(NDKABI) -lt 17; echo $$?),0)
+    ANDROID_LEGACY?=1
+    export ANDROID_LEGACY
+endif
+
 # set debug-related variables to cascade down
 ifdef KODEBUG
        DEBUG:=$(KODEBUG)
```

(Because I'm not sure if the existing LEGACY covers quite the same ground.)

**Comment by NiLuJe** [comment]
Yeah, IIRC, the existing LEGACY stuff is Kindle-specific (so, glibc 2.5 & astoundingly old kernels ;p).

**Comment by Frenzie** [comment]
I fixed Android 2.3 in #4356 because it was too simple not to.

**Comment by Frenzie** [comment]
Stashing this here. Nothing of interest but I want to toss it from my working tree without bothering with branches atm.
```diff
diff --git a/Makefile.defs b/Makefile.defs
index be57466..3132e47 100644
--- a/Makefile.defs
+++ b/Makefile.defs
@@ -73,6 +73,15 @@ else ifeq ($(TARGET), appimage)
        export EMULATE_READER=1
        export SDL=1
        export APPIMAGE=1
+else ifeq ($(TARGET), android-legacy)
+       export ANDROID=1
+       export PATH:=$(ANDROID_TOOLCHAIN)/bin:$(PATH)
+       export SYSROOT=$(NDK)/platforms/android-$(NDKABI)/arch-$(ANDROID_ARCH)
+       ifeq ($(ANDROID_ARCH), x86)
+               CHOST?=i686-linux-android
+       else
+               CHOST?=arm-linux-androideabi
+       endif
```

**Comment by pazos** [comment]
@Frenzie: Is this still an issue after https://github.com/koreader/koreader/pull/4491 ??. I mean we are using at least API19 for building java code, we're still using ndk version 15r but this shouldn't be an issue.

**Comment by Frenzie** [comment]
We've always used API 19, so there's no reason to suppose it wouldn't be. I'll give it a try later.

**Comment by Frenzie** [comment]
But yes, I didn't think of that when I wrote the above comment. Presumably lower than API 19 probably won't run at all.

According to this commit API level 23 should not display the warning. I'll see if I can give it a quickish try.
https://android-review.googlesource.com/c/platform/build/+/737545

**Comment by pazos** [comment]
> It looks like the message is quieted by writing android:minSdkVersion="19"

Great, it should work if we add android:targetSdkVersion="19". Since we don't have a target version targetSdkVersion get the value of minSdkVersion, which is 14. If we change the target version without modifying minSdkVersion the apk should install on <19.

**Comment by Frenzie** [comment]
Indeed, that seems to do the trick! I wasn't expecting there to be such a simple workaround, nor does a quick search on GH suggest anybody else facing the problem went with anything other than increasing minSdkVersion. :+1:
