### ISSUE TITLE
Kobo Forma Frontlight Adjustment not Working Properly

### ISSUE THREAD

**Issue by kitsek** [koreader/koreader#4354]
* KOReader version: All
* Device: Kobo Forma

#### Issue
When adjusting frontlight, unable to control warmth light, also lightness is messed up from 1 to 100.

#### Steps to reproduce
open Menu-> frontlight -> adjust all from 0 to 100, and vice versa.

**Comment by pazos** [comment]
@kitsek @sekkit:  centralized effort to support the Forma is in #4291

**Comment by NiLuJe** [comment]
Yep, closing in favor of #4291 ;)

(And, yes, as @pazos mentioned, it is a known issue).
