### ISSUE TITLE
Publish to OpenStore

### ISSUE THREAD

**Issue by gouchi** [koreader/koreader#4361]
Koreader is not available on the [OpenStore](https://open.uappexplorer.com/submit) which will ease the installation of the application.

**Comment by Frenzie** [comment]
Would you be willing to assist with that? I'd love to of course, but time is limited. :-)

**Comment by viksok** [comment]
> Would you be willing to assist with that? I'd love to of course, but time is limited. :-)

I might take care of it.

**Comment by pazos** [comment]
@viksok: I'm not sure if there is any content hub API for non qt/qml applications. Could you ask this to the administrator? How other non-qml applications are added to OpenStore?

**Comment by Frenzie** [comment]
Oh, I'd only seen the original comment without the edit. Indeed, just quickly looking at the docs I see a lot of stuff about QML and HTML5.

**Comment by viksok** [comment]
Unfortunately no constructive information was provided to me by OpenStore admins.
They claim that: `${HOME}/fonts is not a valid path`

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/blob/b2740808469801482e2d83e640e89c44aa1f1fb9/platform/ubuntu-touch/koreader.sh#L26-L27

Of course it's not a valid path unless one makes it a valid path. I'm not really sure how to respond to that. I wouldn't say the program is trying to do much of anything there, except optionally load fonts from that path, should one choose to create it and stick some fonts in there.

I do have some doubts about the path as such. Alternatives like the standard `/usr/share/fonts/` and `~/.local/share/fonts` spring to mind, as well as the deprecated `~/.fonts` and the more clearly KOReader-specific `~/.config/koreader/fonts` depending on what the goal for that line is. I.e., is it about using any fonts installed on the system or only about adding custom fonts specifically for use with KOReader.

> These are the writable paths, where the app should store its data:

Okay, but that doesn't have anything to do with the supposed problem. That's exactly what this line would seem to do:

https://github.com/koreader/koreader/blob/b2740808469801482e2d83e640e89c44aa1f1fb9/datastorage.lua#L19

**Comment by myii** [comment]
I got reminded of KOReader in the [UBports Telegram SuperGroup](https://t.me/ubports).  I saw that @viksok was discussing this back in February.  My question: has the `.click` ever worked on UBports?  That would be the first stage before this can be published to the OpenStore.  The `.click` installs but then fails to run.  The only log I get is in the `unity8.log`:

```log
ApplicationManager::onProcessStopped reports stop of appId= "koreader.koreader_koreader" which AppMan is not managing, ignoring the event
```

**Comment by Frenzie** [comment]
Seems like @gouchi or @viksok would've mentioned if it didn't?

**Comment by myii** [comment]
@Frenzie In the discussions on Telegram involving @viksok, there was no indication that it has ever worked on UBports.

**Comment by Frenzie** [comment]
@myii That doesn't make much sense to me, but alright. :-)

Is there some kind of UBports emulator like there is for Sailfish? Given that UBports is a regular Linux from what I understand (i.e. none of the horrors of Android), combined with the fact that we already have a (legacy?) Ubuntu Phone build it probably shouldn't be too hard to dust it off a little.

**Comment by myii** [comment]
@Frenzie Thanks for your responsiveness.  Let me try to get someone involved in this discussion who can explain it a little better than me.  Or if you have Telegram, please join the group I linked above and then it will be a lot easier to get to the bottom of this.

**Comment by Frenzie** [comment]
Btw, according to https://github.com/koreader/koreader/issues/2119#issuecomment-229954097 logs can be found in `/home/phablet/.cache/upstart/*`.

**Comment by Frenzie** [comment]
I'll close this issue for the moment to prevent any possible confusion. Please refer to #4960 instead.
