### ISSUE TITLE
Keep screen awake still not available

### ISSUE THREAD

**Issue by taohansen** [koreader/koreader#4364]
* KOReader version: 2018.11.1
* Device: Galaxy S7

#### Issue

I commented here https://github.com/koreader/koreader/issues/2748 that an option to keep a device screen from turning off is still not available despite a commit to to fix.

**Comment by cramoisi** [comment]
@taohansen : could you check the plugin is not disabled in your plugin manager ?

**Comment by avsej** [comment]
@cramoisi which plugin?

**Comment by taohansen** [comment]
All plugins are enabled and none of them offer to keep the screen awake.

**Comment by pazos** [comment]
@mwoz123 added support for this feature in https://github.com/koreader/android-luajit-launcher/pull/67 but it is unimplemented in the frontend.

**Comment by cramoisi** [comment]
ok, I was thinking about the "keep awake" plugin, which I use on my kobo for this purpose (keep the device for turning off / going to sleep)
