### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by chelovekPlanetaZ** [koreader/koreader#4366]
* KOReader version: v2018.11.1
* Device: PocketBook PB625

#### Issue
Hello, such a problem. New versions of the Koreader on PB625 are not running. Old ones are working. I don’t remember the latest working version. Help me please.
------
##### `crash.log`     
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/21/18-01:35:27
 [*] Version: v2018.11.1

ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
ffi.load: inkview
11/21/18-01:35:27 INFO  SoftwareVersion:  R625.4.4.1815
./luajit: frontend/device/pocketbook/device.lua:243: unrecognized PocketBook model PB625
stack traceback:
	[C]: in function 'error'
	frontend/device/pocketbook/device.lua:243: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:48: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/widgetcontainer.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/container/centercontainer.lua:5: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/button.lua:19: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/buttontable.lua:2: in main chunk
	[C]: in function 'require'
	frontend/ui/widget/confirmbox.lua:21: in main chunk
	[C]: in function 'require'
	./reader.lua:96: in main chunk
	[C]: at 0x0000c059

**Comment by Frenzie** [comment]
@chelovekPlanetaZ Probably since #3403. You can probably get it running temporarily by placing `PB625` in one of the checks, e.g. here:

https://github.com/koreader/koreader/blob/7841351a813d34669c7451a47b13167e5a5f434e/frontend/device/pocketbook/device.lua#L248-L249

So:

```
elseif codename == "PB625" then
return PocketBook627
```

The DPI might be slightly off in that case.

Pinging @wsotest

**Comment by chelovekPlanetaZ** [comment]
Thank you very much.
This option worked:
```
elseif codename == "PB625" then
return PocketBook624
```
