### ISSUE TITLE
FR: Set font size in MuPDF EPUB rendering

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4368]
* KOReader version: v2018.11.1
* Device: all

#### Issue
You can't easily adjust the font size in a MuPDF-rendered EPUB. See https://www.mobileread.com/forums/showthread.php?p=3780029#post3780029

(Tracking here so I'm less likely to forget when I have some time, and to alert potentially interested parties like @poire-z @robert00s @pazos maybe @NiLuJe ?)

It's actually very easy to tap into the backend. This works:

```diff
diff --git a/frontend/document/pdfdocument.lua b/frontend/document/pdfdocument.lua
index 34f072e9..14ae115d 100644
--- a/frontend/document/pdfdocument.lua
+++ b/frontend/document/pdfdocument.lua
@@ -42,6 +42,8 @@ function PdfDocument:init()
     if not ok then
         error(self._document)  -- will contain error message
     end
+    local Screen = Device.screen
+    self._document:layoutDocument(Screen:getWidth(), Screen:getHeight(), 50)
     self.is_open = true
     self.info.has_pages = true
     self.info.configurable = true
```

What isn't as easy, or at least what would take some time to properly implement, is to make that not a hack, to make it properly configurable and and finally to tie it into the existing font size GUI.

**Comment by poire-z** [comment]
(I'm a bit too busy with credocument these days to give much thoughts to pdfdocument :| )

But we could as a quick solution, if we can detect it's an epub-like document, call the above hack with the credocument default font size - so one can at least set it there to use it with MuPDF.

Otherwise, it indeed does not look obvious (ReaderView:onFontSizeUpdate() which gets the event when font size is changed, calls onReZoom... :| it's all quite tied to kopt...

**Comment by pazos** [comment]
What benefits does Mupdf have over crengine to render epub files?. I find crengine quite powerful for reading epubs.

**Comment by Frenzie** [comment]
A concrete advantage is RTL. A document in Hebrew etc. will look mostly or even entirely correct in MuPDF right now.

Mostly it's just something different. But MuPDF is actively developed upstream, so if they implement brilliant support for X in the future we'll get it (almost) for free.

There's also some font size shenanigans in cr I still have to track down.
