### ISSUE TITLE
Unable to refresh screen on Android eReader

### ISSUE THREAD

**Issue by nicolascolla** [koreader/koreader#4373]
* KOReader version: KOReader 2018.11 "An die Freude"
* Device: Energy Sistem eReader Max
*Operating system: Android

While I can report that the Kobo version of Koreader works perfectly, unfortunately I haven't been able to refresh the screen on my Android Energy Sistem. I have tried to change the refresh settings to a different page number, and it never works. Touching the screen two times to display and remove the menu also doesn't work. This seems to be related to the form in which the device recognizes the need to refresh the screen. Some Android apps work, some don't. It -almost- always works in apps in which you scroll. Using a web browser, for example, a scroll refreshes the screen, but no eReading application (except the one provided by default) is able to do it.

I contacted Energy Sistem asking for information about the way in which the device can be made to refresh the screen, and they have told me that they cannot tell it to me (ugh).

I understand that this can be a complex issue and my device is not very well-known. Thank you very much for your work anyway.

**Comment by Frenzie** [comment]
Also see #3517.

**Comment by pazos** [comment]
> I contacted Energy Sistem asking for information about the way in which the device can be made to refresh the screen, and they have told me that they cannot tell it to me (ugh).

They also refuse to release the kernel  and their main application sources -  FBReaderJ -  (both tied by GPLv2) 

I got a couple of their ereaders (the max and the pro hd) and returned both a few days later because they provide one of the buggiest android firmwares of e-ink readers.

Anyways, did you try the diagonal swipe to force a full refresh?
