### ISSUE TITLE
Failure to load many native fonts on Kindle PW2 (degradation from previous versions) 

### ISSUE THREAD

**Issue by vt220** [koreader/koreader#4374]
* KOReader version: v2018.11.1
* Device: Kindle Paperwhite 2 4GB International Edition (B017 or 9017), firmware version 5.4.5.1

A current version of koreader fails to load some of the native (built-in) fonts which were successfully loaded by older versions. For example, in comparison to a version v2015.11-1735-g14e7730_2018-06-02 (the old version), the following fonts are loaded by the old version but are not loaded by the current version:

Helvetica (all the 4 variants: medium, medium italic, bold, bold italic)
KindleBlackboxC
STBShusong
STBShusong-Bold
TBGothic
TBMincho

Attached are logs from both old and current versions. Logs for both versions were gathered on the same device.

[crash-v2015.11-1735.log](https://github.com/koreader/koreader/files/2639660/crash-v2015.11-1735.log)
[crash-v2018.11.1.log](https://github.com/koreader/koreader/files/2639661/crash-v2018.11.1.log)

Note: from my perspective (and probably for most of the users' as well), the most important problem is a failure to load Helvetica, which is a heavily used font.

**Comment by Frenzie** [comment]
Looks like @NiLuJe blacklisted them in #4039, although in that case I'm surprised they actually worked? Also pinging @poire-z who's the most familiar with crengine these days. ;-)

@NiLuJe is this `RegisterFont()` what you were referring to?

https://github.com/koreader/crengine/blob/89b0650e425013da81bc73c6d7676599d8b13c62/crengine/src/lvfntman.cpp#L3382-L3414

**Comment by Frenzie** [comment]
@vt220 Looks like the Helvetica fonts specifically were blacklisted for another reason than not loading though:

>  And blacklist Helvetica because it's not identified as a single family.
> (That's done via FontConfig in the native system).

https://github.com/koreader/koreader/pull/4039/commits/2b36afb4d4fbf2c58c87c9d4b59d2fd993a56fb1

**Comment by NiLuJe** [comment]
Yeah, some of them may have worked on earlier firmwares, which makes things
even more awesome to deal with...

**Comment by vt220** [comment]
Ok, then I am closing it. Thanks.

**Comment by poire-z** [comment]
I'm not very familiar with the font handling (it's all very freetype-cryptic to me :)
But from what I got, crengine should accept any font that KOReader throws at it with:
https://github.com/koreader/koreader/blob/062d9a44d1e144fd83f4b300e66935088f22c48e/frontend/document/credocument.lua#L78-L87
provided (I think):
- it is readable/supported by Freetype
- glyphs for the chars `azAZ09` are present in the font (that was why symbol fonts were discarded)

https://github.com/koreader/crengine/blob/89b0650e425013da81bc73c6d7676599d8b13c62/crengine/src/lvfntman.cpp#L2944-L2958 https://github.com/koreader/crengine/blob/89b0650e425013da81bc73c6d7676599d8b13c62/crengine/src/lvfntman.cpp#L2688

**Comment by NiLuJe** [comment]
Some variants of Noto get dropped, too, depending on which previous Noto variants were loaded (IIRC)...

**Comment by poire-z** [comment]
Oh, yes, forgout about that: it also doesn't register what it _considers_ as duplicate of fonts it already knows.
Some investigation about that detailed in https://github.com/koreader/koreader/issues/4174#issuecomment-414349293
