### ISSUE TITLE
"Page overlap" greyed out/settings can't be changed/works occasionally

### ISSUE THREAD

**Issue by turkeyphant** [koreader/koreader#4383]
* KOReader version: v2018.12
* Device: Kobo_nova (Kobo Clara HD)

#### Issue
Even with scroll turned off and reflow on, the "Page overlap" option is greyed out in all types document.

I manually edited defaults.lua to turn it on and it remains greyed out and only works on some text-based PDFs. Even journal articles from the same publisher sometimes work and sometimes don't.

This is it working on a PDF.

![reader_2018-dec-07_161027](https://user-images.githubusercontent.com/8129583/49659674-a51e2c80-fa3c-11e8-86ab-f48fb6f751fd.png)

--------------------

However the option is still greyed out and I can't see any settings.

--------------------

![reader_2018-dec-07_161041](https://user-images.githubusercontent.com/8129583/49659672-a51e2c80-fa3c-11e8-9b34-bd3f84fb49a3.png)

#### Steps to reproduce
Open document, enable reflow, disable scroll, go to menu setting for "Page overlap".

Alternatively, force page overlap with defaults.lua and open various documents and enable reflow and disable scroll.

**Comment by poire-z** [comment]
I don't read much PDFs, but I noticed in https://github.com/koreader/koreader/pull/3870#issuecomment-381247890:

> I was going to say: the same as how overlap works with PDF ... but it seems to suck even more with PDF, got some pages with half the screen grayed out, some pages not (needs **scroll mode + fit to content width** to have the Overlap menu enabled).

**Comment by Frenzie** [comment]
This is probably a duplicate, see https://github.com/koreader/koreader/issues/4382#issuecomment-445292405

**Comment by turkeyphant** [comment]
> I don't read much PDFs, but I noticed in [#3870 (comment)](https://github.com/koreader/koreader/pull/3870#issuecomment-381247890):
> 
> > I was going to say: the same as how overlap works with PDF ... but it seems to suck even more with PDF, got some pages with half the screen grayed out, some pages not (needs **scroll mode + fit to content width** to have the Overlap menu enabled).

Thanks for that. I didn't find it while searching.

I managed to get it working for one PDF that didn't work before using that trick (although I only needed fit to content width and not scroll mode as well).

Interestingly, despite working in other PDFs and being set to true in defaults.lua, the setting was disabled when I was able to ungrey out "Page overlap".

I was also able to make it persist after turning "Reflow" back on (bother having changed the fit to content width and not!).

Clearly some logic has gone wrong here because "Page overlap" should not be available in scroll mode and should be available in all reflow modes (and I guess all fit to width zooms).

**Comment by pazos** [comment]
> Even with scroll turned off and reflow on, the "Page overlap" option is greyed out in all types document.

I did notice yesterday. It seems that controls are inverted: page overlap should be disabled with reflow off and enabled with reflow on.

**Comment by Frenzie** [comment]
@pazos That's not right, in paged mode it's a very relevant setting provided pages are taller than the screen. In other words, you need to be using some kind of fit to width setting. Of course it doesn't do anything with a setting that fits to page or height.

**Comment by hius07** [comment]
Seems this can be closed.
Page overlap can be enabled for pdf, for certain combinations of the view mode parameters (reflow off required).
