### ISSUE TITLE
Wifi non functional on Kobo Glo HD

### ISSUE THREAD

**Issue by rtega** [koreader/koreader#4387]
* KOReader version: 12.0 and 11.1
* Device: Kobo glo HD

#### Issue

When enabling wifi it says "scanning..." and then just a gray bar appears. I can't select my network. On the version previous to 11.0 it worked more or less flawless.

##### `crash.log` (if applicable)
shows just:
12/08/18-08:54:18 INFO  Kobo WiFi: enabling WiFi                                                                                                               
12/08/18-08:55:44 INFO  Kobo WiFi: disabling WiFi                                                                                                              
12/08/18-08:55:48 INFO  Kobo WiFi: enabling WiFi                                                                                                               
12/08/18-08:56:26 INFO  Kobo WiFi: disabling WiFi

**Comment by NiLuJe** [comment]
Ye olde and weyrd Glo HD wpa-supplicant? Pinging @poire-z ;).

In the meantime, double-check that your usual networks are still being selected/saved in Nickel, as it may help ;).

**Comment by Frenzie** [comment]
What do you mean by the version previous to 2018.11 exactly? 2018.10? I'm afraid I don't see anything wifi-related here:

https://github.com/koreader/koreader/compare/v2018.10.07-beta...v2018.11

**Comment by rtega** [comment]
It says: v2015.11-1800-g0924b57_2018_07-29
On this version the wifi works though I get the grey bar about 1 in 4 times.

**Comment by rtega** [comment]
I'm on KSM 9 btw.

**Comment by Frenzie** [comment]
July's a bit further back; I'll have a look later.

**Comment by rtega** [comment]
Nope. I'm on 4.7.10413 (168741200a 12/12/17).

**Comment by Frenzie** [comment]
I don't see anything about wifi between July and October either.

https://github.com/koreader/koreader/compare/v2018.07.29-beta...v2018.10.07-beta

Could you perhaps give the October release a go to narrow it down further?

**Comment by poire-z** [comment]
4.7.10413 was for me among the newest problematic firmwares on GloHD.
Sure you haven't upgraded from <=4.6 to this one recently?

Does wifi ap scan in KSM show something ?
If it doesn't, OK, not koreader specific. Unless there is really a past KOReader version that did work, in which case we'd like to know which. Have you reinstalled that old version today on 4.7.10413?

**Comment by rtega** [comment]
@poire-z nope. I must have upgraded about a year ago so that definitely is not the reason. The old release works OK today (been using it all day).

Wifi ap scan in KSM shows my network as it should.

I'll try the October release. I'll be back to report on that soon.

**Comment by rtega** [comment]
Nope, october release doesn't work either. I'll have a try with a fresh install of the release I'm using.

**Comment by rtega** [comment]
Tried a fresh install of the release that works here. The difference is the following:
- When I hit "Wi-Fi connection" it asks whether I want to turn wifi on, I hit yes
- It scans and then it shows the infamous grey bar with no networks
- I hit "Wi-fi connection" again and it asks whether I want to turn wifi **on**, I hit yes
- It scans and pronto it shows the available networks which work
Sometimes I don't have to try twice enabling Wi-Fi and I get the networks on the first scan.

When I try one of the releases that don't work:
- When I hit "Wi-Fi connection" it asks whether I want to turn wifi on, I hit yes
- It scans and then it shows the infamous grey bar with no networks
- When I hit "Wi-Fi connection" again, the Wi-Fi connection square is turned on and it asks whether I want to turn wifi **off**
I can try as many times as I want, I never seem to be getting the list of available networks. If I don't opt to turn wifi off and chose network info it has IP 127.0.0.1

I hope that clarifies what could be going on.

**Comment by rtega** [comment]
The relevant code is in frontend/ui/network/manager.lua and definitely has changed.

**Comment by rtega** [comment]
I guess this line
https://github.com/koreader/koreader/blob/master/frontend/ui/network/manager.lua#L127
should read something like 
`local wifi_status = NetworkMgr:isWifiOn() and NetworkMgr:isOnline()`

**Comment by Frenzie** [comment]
It's definitely intentional move to allow connecting to the wifi without being online, though why that was tacked on like that is unclear to me. I should be more vigilant about that precisely for this reason, because something like Sony support doesn't exactly say "wifi change" when looking at commit messages.

It might, however, need to read something like isWifiOn() and isConnected().

**Comment by rtega** [comment]
I changed those lines as I suggested and lo and behold, it works again.

**Comment by rtega** [comment]
Works with isConnected() as well.

**Comment by Frenzie** [comment]
Could you submit a PR with the latter change please?

The difference between the two is that isConnected() only checks if it can reach the default gateway (the router it's supposedly connected to), while isOnline() checks if it can retrieve an IP for `dns.msftncsi.com`, which is the same method used by Microsoft Windows to check whether it has internet connectivity.

I used that specific method because I presumed it's more likely to be trustworthy than using `koreader.rocks`, though I don't really know if it is. ;-)

Anyway, we basically used to be too pedantic about having Internet connectivity, which got in the way of local transfers.

**Comment by NiLuJe** [comment]
Wasn't the change intended to avoid the delay inherent to isConnected that it added to the menu?

**Comment by Frenzie** [comment]
Good point. I repeat, that's why I like smaller commits, whether they're in small PRs or well organized rebased bigger PRs with multiple commits. Makes it clear while looking at the logs and while using git blame. ;-)

What I'm mostly confused about is how this count impact, well, anything at all other than the menu loading speed really.

**Comment by rtega** [comment]
Mmm, not on git I'm sorry.

**Comment by NiLuJe** [comment]
c.f., #4192 for the original disucssion ;).

**Comment by Frenzie** [comment]
Well, that completely slipped my mind. Thanks!

**Comment by NiLuJe** [comment]
That said, OTOH, isConnected should handle that case sanely, FWIW ;).

**Comment by rtega** [comment]
Nice, now it would be nice to have it scan twice so I don't have to hit "Wi-Fi connection" twice every time I want to go on the net.

**Comment by Frenzie** [comment]
Well yeah, I passed that -w2 very much on purpose. :-)

**Comment by rtega** [comment]
Well, that doesn't do much in this case. It looks like in the file common/lj-wpaclient/wpaclient.lua it doesn't get the list it should be getting. On second try it does. I can solve this crudely by letting it scan twice in frontend/ui/network/manager.lua in function showNetworkMenu:
Well, that doesn't do much in this case. It looks like in the file common/lj-wpaclient/wpaclient.lua it doesn't get the list it should be getting. On second try it does. I can solve this crudely by letting it scan twice in frontend/ui/network/manager.lua in function showNetwork
```
        if (table.getn(network_list) == 0) then
            --UIManager:show(InfoMessage:new{text = err})
            --return
            network_list, err = self:getNetworkList()
        end

```
