### ISSUE TITLE
Better way to handle user plugins

### ISSUE THREAD

**Issue by DezMakes** [koreader/koreader#4393]
* KOReader version: 2018.12
* Device: Kobo Aura H2O Edition 2

Disclaimer: I am new to Lua and I also just made this GitHub account.

I just made my first plugin. It's just a little MessageBox with a "Hello World" text based on the Hello and Terminal plugins.
It works flawlessly **but** in order for the plugin to appear in the menu I had to edit the files "_filemanager_menu_order.lua_" and "_reader_menu_order.lua_".

So I wanted to ask, isn't that a bad way to handle user plugins? Wouldn't it be better if the end user could just drop a "_plugin.koplugin_" they downloaded somewhere into the plugin folder and be done with it?
As I understand it, right now if I wanted to maintain my plugin, I would have to fork the whole project just to add one line in those ui files (again, I just made this GitHub account so my apologies if I misunderstand how this works).

To make this easier, there could be something like a "user plugins" folder and a corresponding "user plugins" menu section which updates programmatically based on the contents of that folder. We would just have to scan the folder once when koreader is launched.

I can try to implement something like this myself but first i just wanted to ask what you think about it and whether this would be a good idea. :)

Thank you

**Comment by Frenzie** [comment]
I apologize for running away with this, but I was thinking something more along these lines:

```diff
diff --git a/frontend/ui/menusorter.lua b/frontend/ui/menusorter.lua
index b7066d3f..4655ce54 100644
--- a/frontend/ui/menusorter.lua
+++ b/frontend/ui/menusorter.lua
@@ -18,6 +18,10 @@ local MenuSorter = {
     },
 }
 
+local function starts_with(str, start)
+    return str:sub(1, #start) == start
+end
+
 function MenuSorter:readMSSettings(config_prefix)
     if config_prefix then
         local menu_order = string.format(
@@ -156,12 +160,18 @@ function MenuSorter:sort(item_table, order)
 
     -- remove top level reference before orphan handling
     item_table["KOMenu:menu_buttons"] = nil
+
+    local more_plugins_menu = self:findById(menu_table["KOMenu:menu_buttons"], "more_plugins")
+
         --attach orphans based on menu_hint
     for k,v in pairs(item_table) do
+        -- insert plugins in more_plugins menu
+        local is_plugin = starts_with(k, "plugin_")
+
         -- normally there should be menu text but check to be sure
         if v.text and v.new ~= true then
             v.id = k
-            v.text = self.orphaned_prefix .. v.text
+            if not is_plugin then v.text = self.orphaned_prefix .. v.text end
             -- prevent text being prepended to item on menu reload, i.e., on switching between reader and filemanager
             v.new = true
             -- deal with orphaned submenus
@@ -172,7 +182,11 @@ function MenuSorter:sort(item_table, order)
                 end
             end
         end
-        table.insert(menu_table["KOMenu:menu_buttons"][1], v)
+        if is_plugin then
+            table.insert(more_plugins_menu.sub_item_table, v)
+        else
+            table.insert(menu_table["KOMenu:menu_buttons"][1], v)
+        end
     end
     return menu_table["KOMenu:menu_buttons"]
 end
@@ -193,10 +207,13 @@ function MenuSorter:findById(tbl, needle_id)
     local k, v
     k, v = next(items, nil)
     while k do
-        if v.id == needle_id then
+        local id_match = v.id == needle_id
+        local sub_table = v.sub_item_table or type(v) == "table" and v
+
+        if id_match then
             return v
-        elseif v.sub_item_table then
-            for _,item in pairs(v.sub_item_table) do
+        elseif sub_table then
+            for _,item in pairs(sub_table) do
                 if type(item) == "table" and item.id then
                     table.insert(items, item)
                 end
```

**Comment by DezMakes** [comment]
I don't fully understand the code but I can try it out tomorrow. This i probably way cleaner than I would have managed anyway :)

**Comment by Frenzie** [comment]
In this particular example you have to name a menu items `plugin_whatever` and then if it's an "orphaned" menu item it'll be sorted into `more_plugins`.

It's a quick hack as written, but back when I wrote the MenuSorter I definitely considered including a more generic version of this where you can include something like a `menusorter_hint` as a pointer for where to put it.

**Comment by DezMakes** [comment]
Thanks, I understand. I am getting a CMake error when building the compiler right now but I will try to fix that and test it tomorrow!

**Comment by DezMakes** [comment]
That's pretty much exactly what I meant. So basically I would have to have this in my plugin, right?
```lua
function Whatever:addToMainMenu(menu_items)
    menu_items.plugin_whatever = {
        text = _("Hello World"),
        callback = function()
            UIManager:show(InfoMessage:new{
                text = _("Hello, whatever..."),
            })
        end,
    }
end
```
I have tried this with your suggested changes in menusorter.lua but when I do use "plugin_whatever" I get a crash:
```bash
./luajit: frontend/ui/menusorter.lua:169: attempt to call global 'starts_with' (a nil value)
stack traceback:
	frontend/ui/menusorter.lua:169: in function 'mergeAndSort'

```

**Comment by Frenzie** [comment]
It's definitely there in my diff. ;-)

But like I said, something *like* this. It's meant as a quick demonstration of the general principle to be followed. I just threw on starts_with as a quick hack to make it work without effort.

**Comment by DezMakes** [comment]
Oh well, then that's my bad :)
I'll close the issue!
