### ISSUE TITLE
Full Refresh Settings not taking effect on Likebook Mars

### ISSUE THREAD

**Issue by mbbrinkman** [koreader/koreader#4396]
* KOReader version: 2018.12 (Android)
* Device: Likebook Mars

#### Issue
Screen does not full refresh when it is supposed to. Does not work with any choice of setting in the Screen > E ink Settings > Full Refresh rate menu. 
#### Steps to reproduce
Change setting to full refresh after n pages. Turn n pages. It doesn't full refresh.

**Comment by mbbrinkman** [comment]
This persists regardless of de

**Comment by Frenzie** [comment]
This is not a supported setting on Android unfortunately as there don't seem to be default APIs. Please see #3517.

**Comment by NiLuJe** [comment]
Closing this, as #4397 effectively hid it from view ;).
