### ISSUE TITLE
[Feature Request]input method

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#4406]
Asian characters need input methods.
There is a open source IME,rime
https://github.com/rime

**Comment by Frenzie** [comment]
Thanks for the suggestion. Unfortunately something like this would require a lot of effort and understanding,

**Comment by Frenzie** [comment]
While only implemented Korean, I'll now close this with the note for interested parties that https://github.com/koreader/koreader/pull/5053 should be an excellent guide the required basic principles.
