### ISSUE TITLE
White screen after waking up

### ISSUE THREAD

**Issue by cepfromca** [koreader/koreader#4413]
* KOReader version: KOReader 2018.12
* Device: Kindle Paperwhite 3

Device screen flashes to white screen after waking up

#### Steps to reproduce

I am using the screensaver hack to modify the image that my Kindle uses and I use the same image for the screensaver feature inside KOReader.  When the device wakes up from the screensaver (regardless if it is with the SmartCover or pressing the button on the bottom of the Kindle), the screen will flash to a whitescreen after about 10sec of use.  After the first 5sec, the screen flashes black, then white (very rapidly) and then it comes back to the last page viewed (I am assuming normal behavior).  Once the screen comes back, it will flash again within another 5sec and this time it will get stuck on a whitescreen.  The device is still responsive and any touch on the screen will return the last page viewed.

This issue seems to be related to #3287, but the behavior is slightly different.

**Comment by NiLuJe** [comment]
FW version?

KUAL or KPVBooklet?

**Comment by cepfromca** [comment]
FW version?
5.9.6.1

KUAL or KPVBooklet?  
Didn't think to test that out.  Behavior seems to only happen when opening a book from a collection using KPVBooklet.  Issue doesn't present when opening from KUAL.  

I should have mentioned whether my device has SO ... it doesn't

**Comment by NiLuJe** [comment]
Yep, then closing this in favor of #3287 ;).

This appears to be a weird quirk stemming from running via KPVBooklet, that possibly only happens on newer FW versions.
Nothing much that can be done about it, AFAICT.
