### ISSUE TITLE
Can't read the OPDS feed from Ubooquity

### ISSUE THREAD

**Issue by mithriltabby** [koreader/koreader#4415]
* KOReader version: v2018.12
* KFMon version: v1.2.9
* Device: Kobo Aura H2O Edition 2 software version 4.12.12111

#### Issue
I set up a Ubooquity server (http://vaemendis.net/ubooquity/) on my local machine to try out OPDS. Ubooquity 2.1.2 indexed my book collection and worked just fine with Aldiko. When I attempt to access it via KOReader, I tap on the entry I added (http://192.168.86.239:2202/opds) and nothing happens in the UI. Eavesdropping via Wireshark, it retrieves the URL specified the first time (subsequently it's probably caching it). I also tried specifying it as the target of the local Calibre OPDS server to see if that made a difference; it didn't.

I've enclosed the crash.log (which doesn't seem to have much of use) and "sniff.txt" containing the text of the HTTP exchange.

[sniff.txt](https://github.com/koreader/koreader/files/2705809/sniff.txt)
[crash.log](https://github.com/koreader/koreader/files/2705810/crash.log)

**Comment by robert00s** [comment]
You should use http://192.168.86.239:2202/opds-books (not /opds)
See: https://vaemendis.net/ubooquity/article10/ubooquity-1-7-0-with-opds-and-comics-metadata
I tested a minute ago and OPDS works well.

**Comment by robert00s** [comment]
I'm closing. Please reopen issue when problem still exist.
