### ISSUE TITLE
FR: different or configurable fallback for "use last book's cover as screensaver"

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4418]
* KOReader version: b21a9efa5373f05de7307d51e7f5e7c98d1cbb30
* Device: Kobo H2O

#### Issue
There's this nice screensaver in an EPUB from one of the latest fun Humble Bundles (Fun Maths from the [Games & Puzzles](https://www.humblebundle.com/books/games-and-puzzles-books?hmb_source=humble_home&hmb_medium=product_tile&hmb_campaign=mosaic_section_1_layout_index_4_layout_type_threes_tile_index_3) bundle).

It's probably something wrong with the EPUB, but I'm logging it just in case. Can't investigate now.

![2018-12-24 21 06 07](https://user-images.githubusercontent.com/202757/50406137-2bb66600-07c0-11e9-9a73-349907447b5a.jpg)

#### Steps to reproduce
Go to sleep.

**Comment by NiLuJe** [comment]
Did you have time to look into this?

I'd be happy to take a look at the ePub otherwise ;).

**Comment by Frenzie** [comment]
No, I've been busy. :-)

**Comment by Frenzie** [comment]
Still happening. I'll send you a mail.

**Comment by NiLuJe** [comment]
Got it, I'll see what I can come up with ;).

**Comment by Frenzie** [comment]
I looked into it a little today and the problem is actually a lot less nefarious. Apologies if you wasted any time on this. On books without a screensaver, for some reason instead of the former behavior of displaying a message, it now falls back to a random image instead. I find this behavior confusing.

Anyway, long story short I have a PNG export from April 23, 2017 demonstrating an old issue no doubt long since fixed.

<img src=https://user-images.githubusercontent.com/202757/53910300-cdc1bc80-4053-11e9-8c3c-992442a104cb.png width=30%>

What I thought was a variety of weird screensaver corruption and cache issues, was actually just my screenshot folder. They probably *were* weird corruption and cache issues, just not current ones. ;-)

I'll leave this open as an FR instead, because I don't want to fall back to some random image.

**Comment by Frenzie** [comment]
In fact it explicitly goes for the screenshot folder as a fallback for the random image folder:
https://github.com/koreader/koreader/blob/dc829d02236d104b43011b77b258e73739b06238/frontend/ui/screensaver.lua#L84-L87

I never noticed since I started doing more with EPUB following the introduction of proper kerning.

**Comment by NiLuJe** [comment]
:D 

Yeah, that is indeed confusing behavior, and the fact that you had a snapshot like that in your screensavers folder made the whole thing hilarious :D.

What's strange is that, AFAICT, there *is* a valid cover in that ePub. I'm not well-vezrsed (or, at all, really) in the intricacies of the spec on that front, but I manually managed to find a cover pretty quickly in there... Any ideas on how CRe does that, @poire-z ?

**Comment by Frenzie** [comment]
@NiLuJe Exactly, that's why I didn't even think of it that way until I:

a. Downloaded my first Wallabag EPUB last night
b. Put my device in standby with a Wallabag EPUB open this morning

**Comment by poire-z** [comment]
> I don't want to fall back to some random image. I'd like fallback to message, first page or book status instead.

You don't but I do :) so have it configurable indeed !
(My screensaver images are curated photos of authors I like - so I get a random one of them when the book doesn't have any cover - or when it's ugly and I have _excluded it from screensaver_ - better that than a text message or the book 1st page :)

> Any ideas on how CRe does that, @poire-z ?

It has to be specified in the .opf file.
The crengine [code involved](https://github.com/koreader/crengine/blob/e68e6b98fd5889a16d0ef57b30438424c6e7dc05/crengine/src/epubfmt.cpp#L852-L903), but also see [what we do ](https://github.com/koreader/koreader/blob/dc829d02236d104b43011b77b258e73739b06238/frontend/ui/wikipedia.lua#L840-L862)when making a Wikipedia EPUB - that `<meta name="cover" content="%s"/>` must reference a file by id in the other part of the opf that lists the files in the EPUB.
No such meta tag, or referenced file not found => no cover.

**Comment by Frenzie** [comment]
> My screensaver images are curated photos of authors I like

Well, I wouldn't be opposed to that of course. But even with more normal screens (my old screen came from modding the source to output a PNG at a point of failure) it seems a bit odd as a default.

**Comment by poire-z** [comment]
If the user has set a directory with what he wants to use as screensaver images, and then decides to use book cover, showing them when the book has no cover looks like an ok default to me.

What doesn't look like a ok default is using the screenshots/ directory as the default directory for screensaver images when the user has not defined one yet.

**Comment by Frenzie** [comment]
Then we agree. :+1:

**Comment by KenMaltby** [comment]
Wasn't there something where you could set the image file to use for the "Screensaver" and one for setting the image file to use for "Power off", as well.  I think it went into the reader settings lua.

**Comment by poire-z** [comment]
Been postponed to next milestones for almost two years :) Time to solve it, or close it !

**Comment by Frenzie** [comment]
The behavior is still weird. ;-)

**Comment by NiLuJe** [comment]
Did a thing in #7371 ;)

**Comment by Frenzie** [comment]
Looks good. :)

https://github.com/koreader/koreader/pull/7371/commits/5682987264004c1339d92989a3bc406eca3c80e4

**Comment by NiLuJe** [comment]
(Gonna refactor ScreenSaver to make the kludges less kludgey)
