### ISSUE TITLE
kobo forma with kfmon troubles

### ISSUE THREAD

**Issue by faassen** [koreader/koreader#4425]
* KOReader version:

This PR (soon to be merged) with improved kobo forma support:

https://github.com/koreader/koreader/pull/4414

* Device:

Kobo Forma

#### Issue

When I start koreader using kfmon (the start menu is documented not to be supported on the forma yet), it crashes with an unexpected exit.

#### Steps to reproduce

Install kfmon. Install koreader (recent development version, but I also got this with the december release)

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/2713530/crash.log)

**Comment by NiLuJe** [comment]
Your build is incomplete ;).

(At a glance, I'd say luarocks issue).

**Comment by faassen** [comment]
I will attempt to run the most recent proper release again first (and then your trick of copying over the lua files). If I get a crash log, you'll see that here.

**Comment by NiLuJe** [comment]
Try with a *clean* install from the latest nightly, that should at least get you a mostly-working base, yeah ;).

(It'll certainly start without crashing, at least ^^).

**Comment by faassen** [comment]
Latest nightly it will be.

**Comment by faassen** [comment]
Thanks! For future reference on my experience (in case someone digs up this issue):

I removed koreader from .adds, then added the nightly. I tried to start it again through kfmon (without an intermediate reboot, perhaps my mistake). This immediately resulted in a reboot of the reader and initially it appeared as if it forgot my login data (as happened before). A restart took care of this. 

Then koreader still crashes (exited unexpectedly), but then doesn't reset but just shows the KO logo fullscreen (but I'm still in nickel). Mysteriously when I went to look for the crash report, it's entirely missing in .adds now. I added it back again. Then *restarted* the koreader before I tried running koreader, and now it works!

The trick seems to be in restarting the ereader before trying to launch koreader.

Since the immediate issue has been resolved and your PR is about to land and it's time for bed, I will take a look at the next nightly.

Thanks for all your help!

**Comment by NiLuJe** [comment]
There's currently a new (AFAICT, FW >4.8) & fun behavior where Nickel restarts completely wreak USBMS, which may have compounded your issues.

**Comment by NiLuJe** [comment]
i.e., everything appears dandy, but onboard isn't actually unmounted on the device side, which evidently leads to massive FS shenanigans...

A full reboot puts things back in order.

**Comment by NiLuJe** [comment]
Which I managed to just fix, whee.
