### ISSUE TITLE
Scrolling PDF with Column mode, not being able to disable continuous paging

### ISSUE THREAD

**Issue by virgiliomd** [koreader/koreader#4426]
* KOReader version: 2018.12
* Device: Kobo Aura One

I am using KOreader A LOT, and many PDFs require minor vertical adjustments so I can see a full image. So I activate scroll mode to do it, but there is a problem: There is no option to have scroll mode ON, but continuous paging OFF. 

I would like to be able to scroll, but scrolling to be limited to the page im reading, and to go to next page I would have to tap the screen. Is this possible? Right now, we cant really use column zoom (I use this a lot) with scrolling mode, because it goes straight to the next page, instead of going back up to read the right side columns.

**Comment by poire-z** [comment]
Probably solved by #6885.
