### ISSUE TITLE
OTA update fails on Kobo Glo HD

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4429]
* KOReader version:
201812000031
updating to:
2018000033

* Device: Kobo Glo HD, N437

#### Issue
I can not update koreader via OTA, the process stops with an error message
"Error updating KOReader. Would you like to delete temporary files?"

#### Steps to reproduce
1) I did an OTA update 4-5 days ago to 201812000031
2) I launch OTA update today
OTA update asks:
Do you want to update?
Installed version: 201812000031
Available version: 201812000033
3) I click UPDATE button
4) "calculating local distribution";
5) "computing zsync delta";
6) "Error updating KOReader. Would you like to delete temporary files?"
7) I click YES - no update happened; next time I "check for update" I see the same versions detected/offered;
8) I changed OTA server from
http://ota.koreader.rocks:80 to
http://vislab.bjmu.edu.cn:80/apps/koreader/ota
and got the same result
9) the third OTA server responded with something "no updates found": http://koreader.ak-team.com:80

Thank you for the proper OTA update mechanism though(when zsync started to be incorporated - since then, OTA went smoother), koreader is growing fast! thank you for your efforts

**Comment by NiLuJe** [comment]
Did you tweak any default files between your last OTA end this failed one?

**Comment by worldexplorer** [comment]
hm... yes I recall doing this:
1) I went to KoReader File Browser;
2) under third icon (screwdriver) there is a "new" menu item "Advanced settings";
3) there is a warning there and "Defaults" page with settings I can change;
4) I changed DLANDSCAPE_CLOCKWISE_ROTATION=false to DLANDSCAPE_CLOCKWISE_ROTATION=true hoping the landscape mode for PDFs would allow me to hold kobo with right hand
5) it didn't work :)

but yes, this way I "tweaked default files" and the next OTA updated started to fail. this might be the root cause.

**Comment by Frenzie** [comment]
That definitely shouldn't affect OTA updates. Did you check if the cleanup proceeded correctly?

**Comment by tlhc** [comment]
ota stuck in computing zsync data  ，also modify the default settings

version  33

**Comment by Frenzie** [comment]
I was wondering about that myself. The nightwatcher script explicitly says make a copy:

https://github.com/koreader/koreader-misc/blob/14c2bf91e35099a41b32d7c01d3df34c8307b788/nightswatcher/nightswatcher.py#L175-L176

It looks to me like we should just be able to replace that by `os.symlink()` without any difference in functionality.

**Comment by NiLuJe** [comment]
@Frenzie : I'm not familiar with the paths used, but we probably indeed want one move out of tmp path, and then a symlink from the versioned nightly path to the ota dir (or vice versa).

Without double-checking, my understanding is that right now it makes a first copy from a tmp path to the version nightly dir, then a move from that tmp path to the ota dir.

**Comment by Frenzie** [comment]
Right, but I think that for space use it should be more like:

1. Move to version dir
2. Symlink to OTA dir

**Comment by NiLuJe** [comment]
Yep! (Or the reverse if zsyncmake truly has something against symlinks, which'd be weird).

**Comment by Frenzie** [comment]
Besides the fix in case of any problems, today's OTA update Just Works™.

**Comment by worldexplorer** [comment]
CONFIRMED
I updated with no problem to ....37(last digits) version
thank you!
