### ISSUE TITLE
It doesn't refresh the screen well on the hacked Sony DPT-RP1.

### ISSUE THREAD

**Issue by Zack-Q** [koreader/koreader#4430]
* KOReader version: koreader-android-arm-linux-androideabi-v2018.12.apk
* Device: Sony DPT-RP1

#### Issue
It doesn't refresh the e-ink screen in time after operations.  Most of the time the screen remains unchanged after you tap the screen.
#### Steps to reproduce
Install KOReader on the hacked Sony DPT-RP1, which runs Android. Open it and that's it.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
That's an issue with your Android, not KOReader.

Could you give some more information about the Android version?

**Comment by Zack-Q** [comment]
It is said the Android version on dpt-rp1 is 5.1, but I get this through adb:
**[ro.build.version.release]: [1.4.01.16100]**
**[ro.build.version.sdk]: [22]**

I have seen some issues about koreader on the Android devices with an e-ink screen. It seems koreader works well on the normal Android devices and has this refresh problem only on the e-ink ones. So are you guys still working on it or just thinking this is not a problem worth solving ?

And thanks for your time.

**Comment by Frenzie** [comment]
> [ro.build.version.sdk]: [22]

Yeah, that's 5.1.

> It seems koreader works well on the normal Android devices and has this refresh problem only on the e-ink ones.

KOReader has no problem on Android E Ink devices other than a slight lack of optimization in some usage scenarios. Onyx seems to implement their drivers just fine, for example. Some of these (hacked) E Ink devices apparently don't implement screen refreshes properly, perhaps because they were only intended to run the manufacturer's own software.

> So are you guys still working on it

Note that this is a volunteer effort. A niche issue down to an extra buggy (or given that it had to be hacked, perhaps purposefully made buggy) version of Android largely depends on someone who has the device and is willing to put in at least several hours. But on the flipside, no commercial project manager would ever allow their employees to waste time on something like that. ;-)

**Comment by Zack-Q** [comment]
OK, I'll try to find a way to get rid of it. Thank you again, for your effort and patience. 👍

**Comment by Frenzie** [comment]
Cross-ref to https://github.com/koreader/koreader/issues/3517#issuecomment-441762635

(We might want to close this one as a semi-duplicate.)

**Comment by Zack-Q** [comment]
Someone told me a temporary solution, install a third-party app `WakeLock`, which prevents the android screen dimming when running KOReader. It does work on my device.

I guess e-ink devices frequently "deactivate" and "activate" the screen to save power, which hinders the refresh operations. I hope this might be a clue that helps. 

Can you spread this message to see if it can help other guys? I keep trying to find a better solution.

Thanks.

**Comment by Frenzie** [comment]
In that case also see #4428, although it'll be disabled by default.

**Comment by pazos** [comment]
> Someone told me a temporary solution, install a third-party app WakeLock, which prevents the android screen dimming when running KOReader. It does work on my device.

> I guess e-ink devices frequently "deactivate" and "activate" the screen to save power, which hinders the refresh operations. I hope this might be a clue that helps.

Very interesting. 

I would go with that (set a wakelock onResume and keep it until onPause). We can avoid #4428 completely (ie: the device never dims when KOReader is active and has focus). + avoids just another option on UI. 

If somebody claims that we need a setIdleTimeout that can be implemented as the autosuspend plugin (backgroundrunner until (wakelock - current screen timeout) = 0, release wakelock and wait for suspend).

#### vs set/clear window FLAG_KEEP_ON

the good:
- no user intervention for desired usage (do not dim until requested)
- a remote possibility of fixing #3567, #3517 and this issue, which seem related.

the bad:
- use another android permission for being able to do wakelocks

the ugly:
- implement the plugin described above.

**Comment by pazos** [comment]
@Frenzie: I just did a few tests and wakelocks are a wonderful solution. It makes my Motorola flies running KOReader.

I guess I will submit a PR to luajit-launcher and adapt #4428 to use setWakeLock(false) instead of keepScreenOn(true) and we're ready to go without plugins and other stuff.

**Comment by Frenzie** [comment]
The CPU can go into ultra-low power states while the screen is on? Huh, i didn't know that.

**Comment by Frenzie** [comment]
It doesn't really sound like they want you to do that:

https://developer.android.com/training/scheduling/wakelock#screen

> The advantage of this approach is that unlike wake locks (discussed in Keep the CPU On), it doesn't require special permission, and the platform correctly manages the user moving between applications, without your app needing to worry about releasing unused resources.

**Comment by pazos** [comment]
Yup, We can release the wakelock on application resume (when other app gets focus, the power button is pressed, etc).

KOReader doesn't behave like a normal app (we're forwarding input processing and don't write to the framebuffer unless the blitbuffer was changed). So the device may decide to turn on the touchscreen, the cpu, the screen...).

If we integrate a wakelock handler on luajit-launcher we just let the hardware to stay idle without sleeping (CPU governor/freq scaling works nice even when acquiring a full wakelock)

It seems like a win/win to me.

**Comment by Frenzie** [comment]
> KOReader doesn't behave like a normal app (we're forwarding input processing and don't write to the framebuffer unless the blitbuffer was changed). So the device may decide to turn on the touchscreen, the cpu, the screen...).

I'm not really sure how that's different from any other even halfway competent app tbh?

**Comment by pazos** [comment]
> I'm not really sure how that's different from any other even halfway competent app tbh?

We are more like a game, but without updating the screen 30 times per second. So our render stays idle most of the time. A lot of games are using wakelocks instead of keeping the screen on, it lets them display cinematics without dimming the screen and at the same time they have the warranty that cpu and sensors are ready for whatever they need.

**Comment by Frenzie** [comment]
As an aside, I saw a wakelock in an early ScummVM Android port from a decade ago, but not in current ScummVM.

**Comment by pazos** [comment]
> As an aside, I saw a wakelock in an early ScummVM Android port from a decade ago, but not in current ScummVM.

ScummVM is based on regular activity, not nativeActivity. This might help.

**Comment by pazos** [comment]
@Zack-Q: the nightly with wakelocks support is [online](http://build.koreader.rocks/download/nightly/v2019.01.1-3-gab09ded_2019-01-11/). Please report if it worked for you without the need of third party applications.

**Comment by Frenzie** [comment]
@Zack-Q Have you been able to test a recent nightly?

**Comment by Zack-Q** [comment]
@Frenzie Yes, it works!

The Wakelock app has been uninstalled. With the option "**Keep screen on**" selected, my dpt-rp1 refreshes the screen well; Disable the option and the issue presents again. Thanks!

Since the screen is always on, I guess it will cost more power. Waiting for a better solution... thanks for your effort again.

**Comment by pazos** [comment]
@Zack-Q I'm closing this issue since it is fixed. We are going to disable wakelocks by default since it is the right thing to do. If you can provide your model name I will try to make an exception for devices such as yours, where without wakelocks things don't work.

You can get the model on lastest nightlies, running KOReader, go to the top-right menu->help->report a bug.
