### ISSUE TITLE
Suggestions for integration of external software into koreader

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4432]
Hi guys,
I'm very grateful for koreader that you develop and I use a lot;

My suggestions, besides bugs and reading-related experience, are here:

1) versions naming could be simpler, you don't release more than one version per day, correct? "v2018.12-31-gf6743a4_2018_12_28" contains too much of details for an average user;
2) sending files (epub/fb2) to kobo via wifi would help a lot; I don't have my own FTP server to use send-to-eBook plugin; zsync requires an IP-exposed host; calibre is a nightmare for its desktop piece; may be you could integrate some telegram api into koreader to send books to myself via Telegram's "Saved Messages"? or even the whole Telegram UI can be reproduced on simple widgets - besides P2P messaging and file transfer, I could read news on e-reader instead of a cellphone; passing-though-IP-blocking on the provider / traffic exchanges might still be an issue in Russia :)
3) is there any open source email software written in LUA?...
4) (online) chess? :))) there used to be a good chess app in nickel and I miss it now; vlasovsoft is a good suite but it requires non-voluntary license;
5) a browser? web blinks a lot by itself and while scrolling the pages; that's why internet browsing is not a very pleasant experience on eInk displays; but might still be useful;

koreader-specific (probably someone has already complained):
1) having top half of the screen as the book's text, and the bottom half as an always-on-dictionary (like in coolreader) would totally make sense; less clicks to do and the popup window with translation closes the context of the word to be looked up. I don't see what words are around the one I'm checking in the dictionary, but I need two unobstructed views simultaneously: the sentence where I met an unknown word and the dictionary with translation;
2) having two books opened simultaneously with per-paragraph sync between the EN and ES versions would be appreciated by language learners; i know "parallel text software" exists to create your own EPUBs with 2 columns; and having such functionality in the koreader might be "too much to develop"... but how much would it cost if we - the users - would pay for that?... crowdfunding campaign?...

**Comment by KenMaltby** [comment]
Personal comments, not intended to represent a reply from the current developers:

1. It is much better now, It is intended to include the info users have commented on using, while retaining the minimum useful to the developers.

2.  I could not envision an easier wireless user ebook transfer than the OPDS implementation in KOReader coupled with the "caliber content server".  

3.  Probably, you might find a few candidates and bring them back here, for consideration.

4.  Is there really a "voluntary" license?  Sergey's P-chess seems quite comprehensive, for the chess enthusiast.  

5.  An "Internet Browser" is the last thing you want on an ereader,  and certainly not as part of an ereading program.  The approach the has been used by the KOReader team is one of having support for various net connected activities, that are directly reading related, provided as "plug-ins".  

As to your interesting "koreader-specific" features, you could submit them as feature requests.  Funding is not normally the issue for this sort of thing, it is more a matter of time and interest.  

Luck;
Ken

**Comment by Frenzie** [comment]
You can send files from KOReader to KOReader on the same network btw.

**Comment by pazos** [comment]
> An "Internet Browser" is the last thing you want on an ereader, and certainly not as part of an ereading program. The approach the has been used by the KOReader team is one of having support for various net connected activities, that are directly reading related, provided as "plug-ins".

:+1: 

Here is a list of public apis:https://github.com/toddmotto/public-apis/blob/master/README.md

**Comment by pazos** [comment]
@worldexplorer: please create one issue per topic, since it is easier to track. That doesn't mean that somebody will implement the feature you want, but these kind of **all-in-one** issues are difficult to track and ended in the tail of never reached - never implemented features.

Closing this.
