### ISSUE TITLE
PDF is squeezed in half (sometimes)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4433]
* KOReader version: v2018.12.31-gf6743a4_2018_12_28 (201812000031 in OTA UPDATE, but I saw in in multiple dev versions throughout 2018)
* Device: Kobo Glo HD (model N437)

#### Issue
under certain circumstances, after a few clicks here and there, PDFs are rendered in such manner that only left half of the width of the screen is used, the right half contains no text and is not used in any way, it stays blank / clean; PDF rendering engine seems to squeeze the whole document vertically by receiving the wrong device width (twice smaller that it actually is); this happens on "Reflow: ON" from the bottom menu;

what doesn't help:
- clicking twice on the left upper corner (to go full screen, with an open book icon in the left upper corner);
- turning pages, changing portrait/landscape
- anything with font size, kerning, "contrast" (font thickness)

what helps:
toggling Reflow: to OFF and then back to ON restores the screen width that koreader sets for the PDF rendering library; after OFF/ON the re-flowed PDF takes full width of the screen;

#### Steps to reproduce
this might be a well known bug;
please leave the comment "STEPS TO REPRODUCE ARE REQUIRED" and I will describe the exact case;

**Comment by worldexplorer** [comment]
i have some large PDFs (>1Mb) or some commercial presentations in PDF - so that I can't send them :) I will catch this again and tell some small publicly available PDF file... this will take some time... :) thanks!

**Comment by gerhaher** [comment]
> I don't personally use reflow much, so I've never seen this. Curious that toggling it on/off helps. How to reproduce? :-)

I can reproduce it:

1. Reflow on
2. Change to "Zoom to fit content width" with a multiswipe. Now the page is squeezed.
3. Reflow off (or change to "Zoom to fit page" with another multiswipe). Squeezing disappears. 

Looks like this:
![Reader_2019-Jun-11_154536](https://user-images.githubusercontent.com/32645430/59278205-de408f00-8c61-11e9-9721-5b86cb27d8c5.png)

Looks like a version of #3330

**Comment by Frenzie** [comment]
That particular method might be more of a gesture manager bug since until recently those actions were inaccessible when reflow was enabled, but as detailed in #3330 similar unintended interactions might occur.
