### ISSUE TITLE
Page randomly turning blank

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4435]
* KOReader version: v2018.11.1
* Device: Kindle Paperwhite 3

#### Issue
While reading page randomly turns blank, I need to move to next page, and then go back in order to get page content back.
#### Steps to reproduce
Read a book(I'm reading EPUB, but possibly occurs with other formats?)

**Comment by NiLuJe** [comment]
Duplicate of #3287 

TL;DR: Weird side-effect of KPVBooklet + newer FW. Does not happen when launched from KUAL.
