### ISSUE TITLE
Footnotes in pages: Full progress bar issue

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4444]
* KOReader version: v2018.12-44-g41b885f_2019-01-03/
* Device: KA1

#### Issue
Full progress bar:

![reader_2019-jan-03_225430](https://user-images.githubusercontent.com/32645430/50678862-0536cd00-1001-11e9-9838-b49e393d1f88.jpg)

Mini progress bar:

![reader_2019-jan-03_225456](https://user-images.githubusercontent.com/32645430/50678866-0bc54480-1001-11e9-93fa-d0ee955e73ae.jpg)

**Comment by poire-z** [comment]
Ok, I once again forgot to take into account the top status bar height :|
Fix found, I'll include it in a crengine PR with a few other small things this weekend.
