### ISSUE TITLE
PB626: Screen distorted

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#4447]
* KOReader version: v2018.12-44-g41b885f_2019-01-03
* Device: PocketBook 626 with software W626.5.14.1225

#### Issue
After last nightly update the whole screen of KOReader is distorted. I also tried previous nightly build ( v2018.12-39-gee673b1_2019-01-02 ) and there is screen normal.
![pb626_screen_issue](https://user-images.githubusercontent.com/29783895/50724382-cd0cb880-10ec-11e9-9e23-09f74b0606a3.jpg)

#### Steps to reproduce
Just copy KOReader version v2018.12-44-g41b885f_2019-01-03 to the PB626 device and start KOReader.

##### `crash.log` 
crash.log does not contain some useful information because of the application did not crashed
[PB626_crash_screen_issue.log](https://github.com/koreader/koreader/files/2729467/PB626_crash_screen_issue.log)

**Comment by Frenzie** [comment]
Pinging @NiLuJe 

Something in https://github.com/koreader/koreader-base/pull/783

**Comment by NiLuJe** [comment]
Yay, I broke it \o/.

I'll add some logging to the PB branch, because it's going to get old real quick to ask people to run FBGrab otherwise ;).

In the mean time, @sonix-github : if you could provide me with the same kind of information as what was done [here](https://github.com/koreader/koreader/issues/4416#issuecomment-449766742) (and the following answer), that'd be great.

----

Probably related to the maybe-4bpp fb.

**Comment by NiLuJe** [comment]
@sonix-github : If, for some reason, shell access is a no-go on your end, try with [these changes](https://github.com/NiLuJe/koreader-base/commit/498041a0985c396ad48a0b9b8d1bff39cdd3159b), that'll make the crash.log useful ;).

**Comment by NiLuJe** [comment]
@sonix-github : Make that the full changes from https://github.com/koreader/koreader-base/pull/788 ;).

**Comment by sonix-github** [comment]
@NiLuJe : I am not able to get shell access via ssh to work, therefore I replaced "framebuffer_linux.lua" and started KOReader and the "crash" log with additional debug data is attached below:

[crash_framebuffer_debug.log](https://github.com/koreader/koreader/files/2733397/crash_framebuffer_debug.log)

**Comment by sonix-github** [comment]
@NiLuJe : I successfully connected to my PB626 via telnet (with "help" from utelnetd) and run fbgrab + copied console output from it also:

[fbgrab_log.txt](https://github.com/koreader/koreader/files/2733742/fbgrab_log.txt)
fbgrab_image:
![fbgrab_image](https://user-images.githubusercontent.com/29783895/50784408-d42ef480-12ad-11e9-94e6-9f34ab901805.png)

**Comment by NiLuJe** [comment]
Okay, that helps, thanks ;).

Could you check if the current nightly + https://github.com/koreader/koreader-base/pull/790 does the jop?

**Comment by sonix-github** [comment]
Now it seems to be OK on the PB626 screen :) I am going to check if there is something another "broken" by opening some ebooks.

Wow, great job !

BTW fbgrab captured almost the same image as above in my last comment

[crash_framebuffer_debug.log](https://github.com/koreader/koreader/files/2734106/crash_framebuffer_debug.log)
[fbgrab_log_3.txt](https://github.com/koreader/koreader/files/2734107/fbgrab_log_3.txt)

**Comment by NiLuJe** [comment]
Yeah, fbgrab probably won't ever handle PB devices properly, but that's out
of scope here, it was just used as a debugging tool ;).
