### ISSUE TITLE
Option to disable automatic orientation switch

### ISSUE THREAD

**Issue by alethiophile** [koreader/koreader#4451]
* KOReader version: v2018.12-44-g41b885f_2019-01-03
* Device: Kobo Forma

#### Issue
The orientation of the screen is set to automatically change based on the physical orientation of the device, via the accelerometer; this works correctly, but keeps firing when I don't want it to e.g. reading while lying down. It would be good to have an option to disable this and just set the orientation manually.

**Comment by pickx** [comment]
@NiLuJe may I suggest not to bury this option under a submenu, even if it's the logical place to put it? 3 taps to change a feature like this is too much.

(also, thanks so much for all your work on the Forma)

**Comment by pickx** [comment]
I thought about placing it at the root of the "gear" menu, like the Frontlight widget. But a gesture does makes more sense.
