### ISSUE TITLE
Best way to sync PB 626+

### ISSUE THREAD

**Issue by dorianleven** [koreader/koreader#4452]
* KOReader version: v2018.12-39-gee673b1_2019-01-02
* Device: pb 626+

#### Issue
After the reader is turned off by long pressing the power button while Koreader is running, all information and settings get lost. Synchronization with the cloud does not help and progress on the books does not load.
What method of synchronization via Wi-Fi will help to save all the necessary data, like books and progress, settings and notes, so that you can restore everything at once?

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by avsej** [comment]
How about using `Exit` menu and exit koreader before poweroff?

**Comment by dorianleven** [comment]
> How about using `Exit` menu and exit koreader before poweroff?


Yes, in a normal situation, you don’t even need to exit KoReader, everything is saved as well. But here we are talking about those cases where only one way remains - a hard reset of the device, for example, in the case of a reader hang. For normal reboot of the device, the loss of all information is too high a price. There should be a way to save information so as not to risk the work done on the book with one click.

**Comment by dorianleven** [comment]
> See [#3398 (comment)](https://github.com/koreader/koreader/issues/3398#issuecomment-338473182) on how you can have settings saved on each page turn, and why we don't do that by default.

Even if there is no pagination, the last recorded progress is sufficient. But when you turn off, all the progress disappears completely, no matter whether it was today or yesterday or a week ago. Books rarely hang and the lack of saving through each page is a reasonable compromise. The question is whether there is a convenient way to save this information, backup to the cloud, which happens for example when connecting to wi-fi? I tried to "synchronize progress", but it did not work for me the last time a similar reboot of the reader occurred.

**Comment by poire-z** [comment]
Well, it seems we have a book progress sync server, but I know nothing about that. But anyway, it would probably not save your global settings. And having to enable WIFI and sync before any reboot or power button press seems like quite a burdain :)

It would be best to try to understand and solve the issue, rather than trying to find a syncing workaround :)

I don't know much about pocketbook, but koreader should save them when done, and when starting, it should read the global and book settings, and if these are corrupted, it should fall back to use the previously saved backuped version of these (.old).

So see how these settings file look , do these file exists, are they 0 bytes or not...:
```
koreader/settings.reader.lua
koreader/settings.reader.lua.old
yourlastbook.sdr/metadata.lua
yourlastbook.sdr/metadata.lua.old
koreader/settings/statistics.sqlite3 (dunno if you're talking about these statistics progress).
```
And please provide your crash.log, where we can see what happened at reboot time (possibly nothing if it wasn't flushed to disk before power off), and what happens at start time (if the settings files are corrupted and tried).

Could be some permission problem, files not fsync() before power off, stuff unmounted before things are saved, SD card corruption, etc...

**Comment by dorianleven** [comment]
The last time I decided to look for possible backups and found just these versions of the * .old files and when viewed through text editor they were the same as the original. Perhaps the * .old backups did not work only in this case, because for the first time KoReader was just installed and the lost progress was insignificant.
I will try to make a complete copy of the internal and external memory and repeat the experience with hard turning off the reader and adding logs here.

**Comment by dorianleven** [comment]
Today there was a similar problem. The reader turned off when the book was open. Copying or using .old files did not help. crash.log attached. When trying to copy a file, an error of file system 0x80070570 was found for the file metadata.fb2.lua. After checking the file system of the flash drive, the error is gone. The latest file is metadata.fb2 (72) .lua. How to restore all selections in the text?

[crash.log](https://github.com/koreader/koreader/files/2826390/crash.log)

**Comment by Frenzie** [comment]
Make a backup of the metadata backup files, delete or rename the main one and replace it with a backup to your liking.

What do you mean by turned off? Like an empty battery?

**Comment by dorianleven** [comment]
> Make a backup of the metadata backup files, delete or rename the main one and replace it with a backup to your liking.

I deleted all files in ***.sdr** folder, and paste biggest **.lua** file without index like **metadata.fb2.lua**. It works, thanks!

> What do you mean by turned off? Like an empty battery?

Yes, either through a long press on the power button, or an independent reboot of the device for its own reason, such as a hang or some kind of error. After turning on the reader, the book that was open starts as the first open. This happened regardless of the book or the KOReader version..
