### ISSUE TITLE
footer font

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#4458]
* KOReader version:
* Device: kobo aura one
Hello,
I would like to change the font of the footers.
How to proceed?
thank you

**Comment by Frenzie** [comment]
By the footer, do you mean the status bar?

**Comment by davicraquette** [comment]
![20190107_104400 1](https://user-images.githubusercontent.com/39924188/50764563-61088c80-1273-11e9-8102-19a5963326b8.jpg)
![20190107_104400 1](https://user-images.githubusercontent.com/39924188/50764593-78e01080-1273-11e9-93ae-a42fb41edcca.jpg)

**Comment by Frenzie** [comment]
Oh, that's the footnote? Today's nightly includes #4454.

Pinging @poire-z because I don't recall otoh if the popup footnote has a custom CSS mechanism as well.

**Comment by poire-z** [comment]
No custom CSS in frontend/ui/widget/footnotewidget.lua, only a hardcoded one.
And the font size does not come from it, it's the one provided as the default font size to MuPDF.
https://github.com/koreader/koreader/blob/bba76357636d5c2a1d51924a608b88f4d01144b1/frontend/ui/widget/footnotewidget.lua#L178-L181

@davicraquette : you can try changing the `-2` here. Use -5 or -8 if you want it smaller.
As in my comment in that code, it looks like your main font is on the smaller side of fonts :) Or your book has some CSS that make that body text smaller, and we won't be able to know when deciding for the font size of footnotes popup...

We could add a manual setting if needed:
`local font_size = self.doc_font_size - 2  + (G_reader_setting.readSetting("footnote_popup_font_size_diff") or 0)`
or do some ugly font metric calculations (which may be wrong anyway given metrics quality) to find the best NotoSans font size to use... but again, this will still suck if the book has `p {font-size: 90%}`

**Comment by poire-z** [comment]
Changing font size will soon be possible with a new menu item, see#4482.

Changing the font itself (to answer https://www.mobileread.com/forums/showthread.php?t=313043 too) is more complicated:
https://github.com/koreader/koreader/blob/c327069f43d7986da33d01346a44786fe82dea83/frontend/ui/widget/footnotewidget.lua#L22-L40
