### ISSUE TITLE
Shows gibberish when opening a specific EPUB

### ISSUE THREAD

**Issue by frh** [koreader/koreader#4464]
* KOReader version: v2018.12
* Device: Kobo H2O Edition 2

#### Issue
I have an EPUB that opens just fine with Calibre, but when opening in KOReader shows only gibberish (see attached screenshot). If I use Calibre to convert it from EPUB to EPUB, it opens properly in KOReader.

#### Steps to reproduce
Open the EPUB in KOReader. This EPUB is copyrighted, so I can't attach it. I could send it privately to developers for testing if desired.

##### `crash.log` (if applicable)
N/A

![reader_2019-jan-09_113538](https://user-images.githubusercontent.com/4987254/50894672-b40d4b80-13fb-11e9-8a96-4d2be1fc35b4.png)

**Comment by Frenzie** [comment]
Looks like the publisher messed up the encoding. Did you try running `epubcheck` on it?

**Comment by Frenzie** [comment]
If the zipfile itself is corrupted, your screenshot might show binary data rendered as if it were simply a text file.

Over at calibre I noticed something interesting [here](https://github.com/kovidgoyal/calibre/blob/6b01ddeaa310b375f15bf37c1f5856acdcbdd5cc/src/calibre/utils/localunzip.py#L10-L15) ([commit](https://github.com/kovidgoyal/calibre/commit/9f570abd9b039dffe043904a7c6bbd710f398c6c)).

> Try to read invalid zip files with missing or damaged central directories.
These are apparently produced in large numbers by the fruitcakes over at B&N.
Tries to only use the local headers to extract data from the damaged zip file.

Would those, ahem, fruitcakes be the origin of your EPUB?

**Comment by frh** [comment]
Quite possibly. I'm afraid I don't know for sure the origin of this EPUB, other than that it's a retail source with the DRM stripped. If I knew nothing else about it I'd say it was rather likely to have come from OverDrive.

**Comment by frh** [comment]
It turns out that the file I had was from a corrupt download. Impressive that Calibre managed to read it anyway though. I don't know if managing to read broken files as well as Calibre is a goal, if not I'll close this issue.

**Comment by poire-z** [comment]
In unzip can't open it, well, we have a good excuse if we can't :)
But I'd like to get your corrupted file that calibre can open, just to check what happens in crengine with it, in case there's an easy solution to do it the calibre way. Although if we do that, we may get then later other errors or strange things that would be hard to understand and relate to this workaround happening...

(You can upload your book here for a few hours till I download it - then edit your post to remove the link - then _Delete revision from history_ the previous revision to really remove any trace of that link.)

**Comment by frh** [comment]
Here you go. Renamed to .zip so GitHub would accept it. Please let me know when you've downloaded it.

[Uploading bad.zip…]()

**Comment by poire-z** [comment]
Thanks. Downloaded.
(Windows compressed folders can't open it - by 7zip can, and SumatraPDF can read it correctly too.)

**Comment by poire-z** [comment]
OK, with your book, the EPUB detection failed (ZIP item name too long, so ZIP invalid), so crengine falls back to detecting other book formats, and ends with the LVTextRobustParser which is robust and won't fail, and will display the ZIP binary content as plain UTF8 text without failing. That's the gibberish :)

But it looks like our amazing crengine already has [some code to use zip local headers](https://github.com/koreader/crengine/blob/master/crengine/src/lvstream.cpp#L2595-L2639) (like the calibre commit pointed out by @Frenzie) when it detects the ZIP might be truncated.
It doesn't detect a truncation with your book, but if I force it to use the `truncated` code path (with a few other tweaks), your book opens correctly.
So, I guess we can make it try a 2nd attempt at opening the zip with the truncated code path when the 1st attempt with the regular code path fails (return 0 ZIP entries, or find names too long, or else...).
I'll push something like that over the weekend.

**Comment by poire-z** [comment]
Yes, I did test and make it work with your book.
(It's not yet merged/bumped and available into koreader nightly, but it should be in the coming days.)

**Comment by poire-z** [comment]
Mentionning them in this issue, in case people do a search for these messages.

crengine will output in koreader crash.log such messages, when meeting truncated/workarounded/corrupted ZIP files:
```
CRE WARNING: zip file truncated: going on with possibly partial content.
CRE WARNING: zip file corrupted or invalid: trying alternative processing...
CRE WARNING: zip file corrupted or invalid: processing failure.
```

So, if you get these messages, your EPUB is not a nice zip file, and we did what we could with it :)
