### ISSUE TITLE
PB626+doesnt start (crash)

### ISSUE THREAD

**Issue by andruha40** [koreader/koreader#4473]
* KOReader version:KOReader 2019.01 "Public Domain 1923"
* Device:626+

#### Issue new firmware
http://download.pocket…7_mix_br_eink_user.zip

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by andruha40** [comment]
http://download.pocket…7_mix_br_eink_user.zip

**Comment by andruha40** [comment]
https://4pda.ru/pages/go/?u=http%3A%2F%2Fdownload.pocketbook-int.com%2Ffw%2FYitoa%2F626%2Fuser%2F20181120_beta%2Fsw_20181120_U626_5.20.87_mix_br_eink_user.zip&e=79235704

**Comment by Frenzie** [comment]
Could you please also share the output of crash.log? It just might say something useful in it.

**Comment by andruha40** [comment]
[crash.log](https://github.com/koreader/koreader/files/2750886/crash.log)

**Comment by andruha40** [comment]
Exactly,it works!!!
Thanks!!!

**Comment by Frenzie** [comment]
Thanks for testing. Would you like to submit a PR or shall I?

**Comment by andruha40** [comment]
Let you
