### ISSUE TITLE
[Feature Request]KOReader, allow selecting default option when item is highlighted

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4480]
We can set default action for most of the items in KOReader, by holding on the item and confirming a dialog. I wonder whether it is possible, to add such behavior to highlighting/translating/opening wikipedia.

**Comment by Frenzie** [comment]
That might make sense, but since my Wikipedia use is more incidental I don't know all the specifics of what's already possible. Pinging @poire-z

**Comment by poire-z** [comment]
Not sure how practical that would be.

I guess that would be for multi-words selection? Or even single-word selection?

If multi words, the implementation could be as easy as calling directly the callback of the prefered button (and immediately closing the 2x4 highlight menu before it is painted on screen).

But the _how to select the default prefered action_ might be less practical: I guess it would be a hold on your prefered button in the 2x4 highlight menu, and it would show a star icon - but Hold on that menu is already managed for moving it around and making it translucent (MovableContainer). So it would need to have that killed, or tweaked.

And once you have set your prefered direct action, how to chose another, and how to cancel-it and get no prefered one? Hold on the selection for > 3s could bypass the prefered action, and would still show the 2x4 menu. Then hold on the prefered button to unprefer it, Hold on another to prefer another.

Might be not super complicated to implement, but many small tweaks and complications in quite a few places. (But more complicated for single words selection.)

Just sharing how I would go at it, but not sure I want to :)

**Comment by KenMaltby** [comment]
Perhaps a "dragging icon" in the far left top corner? Like the + in the far right corner.  The "highlight" menu box would need a "title line" added.  The single word/dictionary result/menu has no long press options for the bottom buttons (the Highlight, Search and Wiki buttons) they just look to be responding as if they were just part of the overall menu, as far as long press is concerned.
Of course making that consistent would require a number of changes, I guess.

**Comment by poire-z** [comment]
Or if we can diverge from the _Hold to make it the default_ trick we could just add a new menu (burried in `Document>`) with an item for each button... So it would just need _calling directly the callback of the prefered button, and immediately closing the 2x4 highlight menu before it is painted on screen_.

**Comment by Frenzie** [comment]
@poire-z 

> Not sure how practical that would be.

Right, when I said it could make sense I was thinking mainly from the dictionary vs. Wikipedia vs. translation perspective.

**Comment by Galunid** [comment]
Well, I pretty much use it for highlighting sentences, that I'd like to come back later. I never used translation/wikipedia. I don't think there is a need to change the single words highlights. Adding a new menu to `Document>` may also work, if it'd simplify other things. It definitely wouldn't hurt to implement this. The only question is how complicated it would be. Also it may be a good idea, to add extra menus when clicking on highlight other than Edit and Delete. It doesn't seem complicated(adding additional entries in `ReaderHighlight:onShowHighlightDialog`?). Please correct me if I'm wrong, after adding additional entries in `Document>` we would have to change `ReaderHighlight:onHoldrRelease` to check if default action is provided and execute it, otherwise just display standard menu?

**Comment by poire-z** [comment]
> Please correct me if I'm wrong, after adding additional entries in Document> we would have to change ReaderHighlight:onHoldrRelease to check if default action is provided and execute it, otherwise just display standard menu?

Right. Something like that gives the behaviour you want:
```lua
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -608,11 +608,16 @@ function ReaderHighlight:onHoldRelease()
                 },
             })
         end
+      local prefered_button_position = {1,1} -- prefer highlight
+      if prefered_button_position then -- some prefered button has been set
+        highlight_buttons[ prefered_button_position[1] ][ prefered_button_position[2] ].callback()
+      else
         self.highlight_dialog = ButtonDialog:new{
             buttons = highlight_buttons,
             tap_close_callback = function() self:handleEvent(Event:new("Tap")) end,
         }
         UIManager:show(self.highlight_dialog)
+      end
     elseif self.selected_word then
         self:lookup(self.selected_word, self.selected_link)
         self.selected_word = nil
```

To do it more properly, you could give a `id=`s to each button in the `highlight_buttons` table, and add into ButtonDialog what exists in ButtonTable as `ButtonTable:getButtonById(id)`, and just have the menu store the prefered button action (its `id`) as the setting value, so you could use something cleaner like:
```lua
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -612,7 +612,11 @@ function ReaderHighlight:onHoldRelease()
             buttons = highlight_buttons,
             tap_close_callback = function() self:handleEvent(Event:new("Tap")) end,
         }
-        UIManager:show(self.highlight_dialog)
+        if G_reader_settings.readSetting("selection_auto_action") then
+            self.highlight_dialog.getButtonById(G_reader_settings.readSetting("selection_auto_action")).callback()
+        else
+            UIManager:show(self.highlight_dialog)
+        end
     elseif self.selected_word then
         self:lookup(self.selected_word, self.selected_link)
         self.selected_word = nil
```

> Also it may be a good idea, to add extra menus when clicking on highlight other than Edit and Delete. It doesn't seem complicated(adding additional entries in ReaderHighlight:onShowHighlightDialog?)

Good idea I don't know :) It might clutter that small quick menu. But yes, it's as simple as that.
Although it could be a solution to just highlight what you want to lookup on Wikipedia when you're on the go without wifi - for quick & easy tap on each of them when at home with wifi to actually do the lookup.
