### ISSUE TITLE
EPUB: squared-off pages vs. no widow or orphan lines?

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#4484]
It looks really simple to add in crengine support for the [orphans:](https://developer.mozilla.org/en-US/docs/Web/CSS/orphans) and [widows:](https://developer.mozilla.org/en-US/docs/Web/CSS/widows) CSS properties (by just adding something similar to "page-break: avoid" between the concerned lines of a paragraph).

https://en.wikipedia.org/wiki/Widows_and_orphans
https://www.thebookdesigner.com/2010/10/pagination-styles-shall-we-kill-the-widows-orphans/
(note: this last page reverse the meaning of widows and orphans, but explains very well how it looks).

crengine currently allows the first line of a paragraph to be alone at the bottom of a page, and the last line of a paragraph to be alone at the top of a page.
Some publishers includes in their embedded CSS `{orphans: 2; widows:2;}` in the intention to stop that from happening.

But there's one thing: I don't like the result :) And we don't have a single issue mentionning widows or orphans, and the lack of support for these properties.
So, are there people around here that would like them?

(I also wonder if it really should be a publisher decision, or a global user decision (like hyphenation is now).

Personally, my biggest grip with the resulting possible blank like at the bottom of a page is that it looks like it is intended, and you could think going to the next page that you're going to read paragraphs that belong to another context.

For example, the page on the left in scroll mode would show in page mode as on the right:

<kbd><img src="https://user-images.githubusercontent.com/24273478/51266615-0500df00-19bc-11e9-8d9d-86dd49107325.png" width=300></kbd> <kbd><img src="https://user-images.githubusercontent.com/24273478/51266785-6de85700-19bc-11e9-9e91-63edb1a96a19.png" width=300></kbd>

making you think that this last paragraph is a standalone paragraph, which it is not... 

crengine currently renders it like this (1 widows, 1 orphan), which I'm quite happy with:
<kbd><img src="https://user-images.githubusercontent.com/24273478/51267855-fe279b80-19be-11e9-912f-0f778f4c2114.png" width=300></kbd>

(We can still add support for them in crengine, but the general preference will decide for the kind of Style tweaks and the presence of defaults with !important or not in our epub.css.)

**Comment by NiLuJe** [comment]
Yeah, FWIW, my personal preference is also for `div, p {widows:1; orphans:1;}` (which i'm currently enforcing in my KePubs) ;).

That said, I am seeing some weird potentially-font/setting/book-specific weirdness where CRe really really doesn't want to render the bottom line while there appears to be space for it (and there indeed is, as switching to scroll mode does print it, without much (if any) changes to the rest of the layout).

**Comment by NiLuJe** [comment]
That'd be on every page, no, so my guess would indeed be very unlucky vertical spacing/alignment ;).

I'll try to check that properly and get back to you, because that was basically just me hijacking your question for something baaarely related ;).

**Comment by poire-z** [comment]
Got that :) but I too witnessed that, never checked, just assumed it was because page was short off a few pixels...
(`#define DEBUG_PAGESPLIT` at the top of crengine/src/lvpagesplitter.cpp if you feel adventurous :)

**Comment by Frenzie** [comment]
Actually I have sometimes thought that I wouldn't mind crengine pushing one or two more lines to the next page more often, but that was a passing occasional thought — not something I thought needed mentioning.

**Comment by poire-z** [comment]
OK, added it with #4490, we will see.

So, we keep the default of allowing widows and orphans, but if a publisher has set some rules like `p {orphans: 2; widows: 2;}`, they will apply.
That will be part of the process of discovering a new book with publisher styles, and disabling the styles you don't like with Style tweaks (except that orphans and widows rules might not be noticed before a few pages turns...)

Added tweaks to allow for avoiding orphans and widows (values set to 2 - I don't think using 3 makes much sense - people who think so can use User style tweaks :).

I discovered that [some publishers and tools](https://guide.pressbooks.com/chapter/widows-orphans-and-bottom-balancing/) prefer using `{orphans: 1; widows: 2;}`:


> In most cases, Pressbooks has widow and orphan settings as follows:
>     Orphans: 1 (meaning that we tolerate a single line of a paragraph at the bottom of a page)
>     Widows: 2 (meaning there should be at least two lines of a paragraph at the top of a page)

And it indeed seems to prevent my _biggest grip_ situation described in the first post, and it keeps the last line of a page filled with text up to the right, and the top line of next page filled with text too (but still allows for blank space, but no ambiguity anymore). So, added a tweak with that.

Also, I think it may be in some case a publisher layout choice (and not just a user preference), for example with poetry: when verses are organized in strophes/stanza of 4 (quatrain), it can make sense to use `p.quatrain {orphans: 4; widows: 4;}` to avoid one to be split among 2 pages (page-break-inside would also work).

**Comment by Frenzie** [comment]
> I discovered that some publishers and tools prefer using {orphans: 1; widows: 2;}:

Right, that's actually the gist of what I meant above.

**Comment by cramoisi** [comment]
It's so cool to have it implemented !
@poire-z : do you plan a style tweak with that ?

**Comment by poire-z** [comment]
Look at your `Style tweaks > Text >` (or https://github.com/koreader/koreader/pull/4490)

**Comment by cramoisi** [comment]
I updated yesterday from an 201808 version : the menu is now quite cool ; (and I looked at paragraph, obviously o.O)

**Comment by Frenzie** [comment]
Closing since this was implemented in #4490.

**Comment by poire-z** [comment]
A note about https://www.mobileread.com/forums/showthread.php?t=354866

> The padding top/button is modified by me (Calibre), so that it fits exactly with the line. As you can see in the second photo, it does include one more line.
I have modified this padding top/button with other values and the same thing happens, there is simply more space below, but it moves me one line to the other page.

This user issue is not with widows and orphans, but with him using CSS `padding` to add some blank space between some paragraphs.
Padding is like borders, it sticks to the related line of text to which it adds padding, it is unbreakable there. If last line of text + padding-bottom does not fit, both are pushed to the next page.
Solution: don't use `padding` for that :) You can try using `margin`, which also stick generally, but 1) collapses and 2) has some special treatment on page breaks (if bottom margin on the last line of text does not fit, it is ignored and not reported on the next page).

@NiLuJe @mergen3107 : if you can link to this in the forum post, thanks :)
(Sorry, I don't want to have an account on mobileread, would be too hard for me to resist going into flame wars :) No account, no temptation !)

**Comment by mergen3107** [comment]
Thanks for your attentive eye :D
