### ISSUE TITLE
Wiki section about kindle needs a small touch up

### ISSUE THREAD

**Issue by C0rn3j** [koreader/koreader#4497]
https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#err-there-are-three-kindle-packages-to-choose-from-which-do-i-pick

There are only two packages now. 

I just opened this project, so can't know how to edit it myself.

**Comment by NiLuJe** [comment]
Nope, still three packages (kindle, kindle5, kindlepw2), what made you think otherwise?

**Comment by C0rn3j** [comment]
As poire-z said. Why isn't the PW2 version in the Releases?

**Comment by NiLuJe** [comment]
Yeah, it'll OTA to the kindle5 version, that's a stupid oversight on my part, I'll fix it later tonight ;).

All the more reason for it to be there for Releases, IMHO ;).
