### ISSUE TITLE
Allow editing of words before lookup.

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4499]
When looking up e.g. "dictionaries", the system is smart enough to remove the "s", but not to change the "ie" to "y". Obviously it cannot know all rules in all languages - which is why the user should be allowed to edit the word to look up. This would also allow the lookup of words that are not on the page, by looking up a random word that is on the page, and then replacing it by the word wanted.

**Comment by Biep** [comment]
When looking up e.g. "dictionaries", the system is smart enough to remove the "s", but not to change the "ie" to "y".  Obviously it cannot know all rules in all languages - which is why the user should be allowed to edit the word to look up.  This would also allow the lookup of words that are not on the page, by looking up a random word that _is_ on the page, and then replacing it by the word wanted.

**Comment by poire-z** [comment]
Might already be there, but not obvious nor documented:

Hold on the word in the lookup result (long-press on the yellow area):

<kbd>![image](https://user-images.githubusercontent.com/24273478/51503370-f1e67880-1dda-11e9-99ce-534e69b1e9ab.png)</kbd>

(you can before that tap on screen while look up in progress to cancel it:)

<kbd>![image](https://user-images.githubusercontent.com/24273478/51503435-51dd1f00-1ddb-11e9-8e7b-60686cb5cf52.png)</kbd>

And you'll get:

<kbd>![image](https://user-images.githubusercontent.com/24273478/51503387-062a7580-1ddb-11e9-9c3b-8fb671f56ae9.png)</kbd>

And you can do a lookup for any word not in the page from the menu:

<kbd>![image](https://user-images.githubusercontent.com/24273478/51503479-8e107f80-1ddb-11e9-86a0-3771a424c27a.png)</kbd>

**Comment by Biep** [comment]
That works - wonderful!  Thanks!

---- On di, 22 jan 2019 00:21:52 +0100 poire-z <mailto:notifications@github.com> wrote ----




Might already be there, but not obvious nor documented:

Hold on the word in the lookup result (long-press on the yellow area):

https://user-images.githubusercontent.com/24273478/51503370-f1e67880-1dda-11e9-99ce-534e69b1e9ab.png

(you can before that tap on screen while look up in progress to cancel it:)

https://user-images.githubusercontent.com/24273478/51503435-51dd1f00-1ddb-11e9-8e7b-60686cb5cf52.png

And you'll get:

https://user-images.githubusercontent.com/24273478/51503387-062a7580-1ddb-11e9-9c3b-8fb671f56ae9.png

And you can do a lookup for any word not in the page from the menu:

https://user-images.githubusercontent.com/24273478/51503479-8e107f80-1ddb-11e9-86a0-3771a424c27a.png

**Comment by Biep** [comment]
Poire just explained it to me.  Thanks!



---- On Tue, 22 Jan 2019 00:28:02 +0100 Frans de Jonge <mailto:notifications@github.com> wrote ----




It should be documented on the dictionary wiki page.

**Comment by Frenzie** [comment]
Closing the issue then. :-)
