### ISSUE TITLE
Crashes when loading large epub file

### ISSUE THREAD

**Issue by timlt** [koreader/koreader#4503]
* KOReader version:  v2019.01.1-1-g2009ffa_2019-01-10
* Device: Kobo Clara HD

#### Issue
KOReader app exits when loading large epub file.  This file is 28MB and loads fine in the Kobo reader, and in the Moon+ and Google Play readers on Android. 

#### Steps to reproduce
1. Try to load a large epub file (28MB). 
2. KoReader runs for a while, then exits without warning

##### `crash.log` (if applicable)
Attached. 

[crash.log](https://github.com/koreader/koreader/files/2785182/crash.log)

**Comment by timlt** [comment]
That would makes sense--this is a 'study bible'--a very challenging book to parse with several thousand pages, and probably 20x that in links and complex markup.  Even though the other readers seem to handle it, they are 'slow' as well.  Thanks.

**Comment by poire-z** [comment]
Looks like we can increase this 1M max nodes limit to 16M : https://github.com/koreader/crengine/pull/121#issuecomment-457244709

@timlt If you feel like it and trust my kobo build (can't test on mine for the moment), can you check on your Clara how your book does it you replace in `koreader/libs/` `libcrengine.so` (and `libkoreader-cre.so` if needed) with the ones from [libcrengine kobo max nodes 1M to 16M.zip](https://github.com/koreader/koreader/files/2792421/libcrengine.kobo.max.nodes.1M.to.16M.zip) (make a backup of these 2 original files just in case).

I'm interested in knowing:
- if it loads :) (first load may take a few minutes - cache save on quit may take a few dozens of seconds)
- the time taken on first load, and memory usage (you can enable it to be shown in the footer).
- the time taken on subsequent loads (and memory usage, should be smaller than on first load)
- if it's usable (hoping koreader should be more usable then than _other readers_ :) thanks to its cache)

**Comment by timlt** [comment]
@poire-z, that's getting better!  This is on a new Clara HD with 2GB RAM/8GB storage, and the file in question is 42MB (I reconverted in Calibre yesterday to include higher quality images). 

- First load:  3:20  (3 minutes, 20 seconds).  
- Subsequent load:  0:12 (12 seconds)
- Usability:  
   - Responsiveness very good, page turns and response on links is snappy and immediate. 
   - The Rendering/layout is roughly usable, but quite different from the Kobo reader.  This is noticeable especially in things like poetry (like the Psalms) where there are tricky layouts, indentations, etc.  KOReader seems to indent the stanzas way too much, for one thing.  Not sure if this is simply a stylesheet issue.
    - Some of the inline footnote links, which SHOULD render as in-page footnotes, instead actually navigate to a different page which contains the link content.  This in turn forces you to actually lose your place in the book, because there's no "back" type of navigation experience that takes you back to your immediately preceding location.  So, I would say that in-page footnote experience is broken, at least on this particular book.

**Comment by poire-z** [comment]
> First load: 3:20 (3 minutes, 20 seconds).
Subsequent load: 0:12 (12 seconds)
Usability: Responsiveness very good, page turns and response on links is snappy and immediate.

Thanks for the test, that's enough for me to push that change in the coming days, and to close this issue :)

For your other usability comments, you can probably solve these problems. But it will be a pain to do that on this big book where any change on styles/tweaks will take 2mn++ to render...

(OK, just saw you solved one).

For the other, some possible things to investigate:

- our KOReader epub.css default EPUB styles: you can disable it in Style>Clear all external styles, so it's not used, and only the books styles will be used. We have a [possibly large-margin blockquote style](https://github.com/koreader/crengine/pull/243#issuecomment-444217191) { margin-top: 0.5em; margin-bottom: 0.5em; margin-left: 2em; margin-right: 2em;} which might be used by your book for stanzas. If yes, you could change that with [User style tweaks](https://github.com/koreader/koreader/pull/3944#issuecomment-389069259).
- you can select text and View HTML to see the HTML and book CSS, and guess what's causing what you see. You then can override some of these with User style tweaks.
- could be some layout/rendering choices/bugs in crengine, for example: negative margins  are not supported, and there may be issues with negative indent in case your book use that kind of styles.

**Comment by poire-z** [comment]
>  I enabled the "Show more links as footnotes" setting which resolved it. Some of the inline footnote links, which SHOULD render as in-page footnotes, instead actually navigate to a different page which contains the link content. This in turn forces you to actually lose your place in the book, because there's no "back" type of navigation experience that takes you back to your immediately preceding location. So, I would say that in-page footnote experience is broken, at least on this particular book.

There may be some terminology differences between how you name things and how we (arbitrary) named them :)

"Show more links as footnotes" : this should only have an impact with _popup footnotes_ (#4261).
What we call _in-page footnotes_ is yet another thing: #4440.
And there is a "back type navigation": if hitting a link brings you to another page, you can go back to the original page with a swipe right (if you enabled `Links > Swipe to go back`)

**Comment by timlt** [comment]
@poire-z, any idea what an ETA might be for this change to be included in a FW update?  The inline fix you sent above worked great, it appears to me in the current FW I'm still getting extremely slow loads, as well as style updating, on books that have many 'text nodes' to process.

**Comment by NiLuJe** [comment]
This definitely made it into 2019.02.

There wasn't any kind of performance improvement expected, though, only avoiding the resource exhaustion crash.

**Comment by poire-z** [comment]
It is included in latest release.
If it loads (even slowly) and does not crash, you have it :)
After that, any change in style/font size/... will take time (usually 2/3 the first load time) to re-render the whole book, nothing much to do about that...
But once you're satisfied with your styles and dont tweak them anymore, it should load again from cache more quickly. If not, look at your crash.log for any CRE WARNING... message.

(If you really have a different behaviour with old FW + my zip vs new FW... tell me more about the differences.)

**Comment by timlt** [comment]
OK that makes sense.  It will definitely load the book without crashing if I wait long enough.  Before, using your fix in this thread, after the initial load it would load many, many times faster from the cache.  Now, it seems it still takes several minutes to load from the cache. 

One thing that has changed is I'm using a different device though.  I'm using a Kobo Forma rather than a Kobo Clara.  Decided to give e-ink one last try, with a nicer device. :-)

**Comment by NiLuJe** [comment]
This should be completely device-agnostic, so, I'd check the logs, as @poire-z mentioned?
