### ISSUE TITLE
ticking on dictionaries installed could define their lookup order (LIFO)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4504]
* KOReader version: v2019.01.1-29-gb629881_2019-01-22
* Device: Kobo Glo HD

#### Issue
"If you'd like to change the order, move dict files out and move them back one by on in the order you want"

#### Steps to reproduce
tap on top => MENU => Lens => Info on dictionary order

#### Suggestion
I understand having a table with arrows to define the lookup order is a whole thing to do. I'd suggest the following logic: I select the dictionaries that I'm interested in - in reverse order; so that 
1) the worst dictionary I select first by ticking checkbox in the "Installed Dictionaries";
2) so-so dictionary I select the second;
3) the dictionary I want the first to show up I select the last;
...this way whatever I select next and next and next takes higher and higher priority.

The order can be marked right in the list of dictionaries with checkboxes, in MENU > Lens icon > Installed dictionaries (3/15), like this:
[_] {00} GNU Collaborative Dictionary of English
[X] {03} English-Russian full dictionary
[X] {01} English-Russian short dictionary
[_] {00} English-Russian slang dictionary
[X] {02} New big English-Russian dictionary

where (to explain the above 5 lines):
[X] - ticked checkbox
[_] - unticked checkbox
{02} - order of the dictionary in the lookup, for {02} two taps on ">>" button will be needed to reach that dictionary in the lookup results. 

After I tick the checkbox, the order could recalculate and the menu could repaint; this way without any explanations the user understands that the priority changed; reverse order is a bit counter-intuitive but this is the price for this cheap & dirty solution (without the need to "move out all folders and drop them back one-by-one").

"last selected dictionary will be used first to bring lookup results" represents LIFO, whereas for FIFO the developer would need to provide "reset all checkboxes" and then first ticked is first in the lookup results, second selected dictionary will show up after ">>" button and the third dict goes to the next ">>" page... FIFO is too much to code...

**Comment by AlanSP1** [comment]
It would be really nice if we would have some way to control dictionaries appearance (lookup order) outside the way we install them.

Which leads me to question, where is info about installation order stored, so we may manually edit that info, it may work...

**Comment by poire-z** [comment]
> where is info about installation order stored, so we may manually edit that info

In the filesystem inode for that directory, where it stores in a list the names and references to the inodes of the things it contains :)
And the manual editing of it is just moving stuff out and back in :) so the list get them in the order of addition of in the directory.
That's just because sdcv has no notion or order, and uses the dictionary in the order the filesystem gives them to it.
If sdcv would at least sort these by alphabetical order, we could give that hint to the user, so he can at least name its dict directory names like 11-FR-PetitRobert , 12-FR-XMLLittre, 31-German - 51-US-Something, 81-LatinInflected, 91-GreekFull ...I do that, just so when I move them out and back, they are in the right order.

**Comment by worldexplorer** [comment]
> It would be really nice if we would have some way to control dictionaries appearance (lookup order) outside the way we install them.
> 
> Which leads me to question, where is info about installation order stored, so we may manually edit that info, it may work...

![image](https://user-images.githubusercontent.com/4983083/51708252-7aac2100-2034-11e9-933c-07e6060e1f83.png)

**Comment by AlanSP1** [comment]
Thanks, so it is data related to time stamp. And moving it out and then again in is the only way at the moment.

**Comment by poire-z** [comment]
It's not even related to timestamps. You can take _one_ out, and put this same one back in, it may be put it the same slot it was previously, and you won't have changed the order. You need to move them all out to get a change to fill the list in the correct order.
I think one even have to rename `data/dict` to `data/dict.OLD`, create a new `data/dict` (so it starts with a fresh empty list), and move the subdirs of `data/dict.OLD/` in data/dict/ in the correct order.

KOReader could do that, but it solves the situation only if all dictionaries dirs are in one level of subdirectories. Nothing prevents a user from having a deeper layout like french/01-Robert french/02-XMLLittre english/31-stuff ...
A bit dangerous if we assume stuff and mess the user dictionary layout...

**Comment by AlanSP1** [comment]
Thanks for additional explanation. So it is a bit more complicated procedure, but it can be done.

Added this info in wiki: https://github.com/koreader/koreader/wiki/Dictionary-support

**Comment by pbienst** [comment]
From reading the discussion above, does this mean that if I have dictionaries for multiple languages installed, it's possible that irrelevant dictionaries are searched? It would be nice if only dictionaries for relevant languages would be searched.

**Comment by poire-z** [comment]
> it's possible that irrelevant dictionaries are searched

Yes. But usually, the irrelevant dict don't have the word you're looking for :) so they'll be searched, but you'll only get results from dicts that have that word in their language.

Anyway, startdict dicts don't specifiy their language (https://github.com/koreader/koreader/issues/2476#issuecomment-270438851).
And in a book in one language, you may see words from other languages (english, greek, latin) that you want to lookup, so it would be a bit restrictive if we'd limit searches to the dicts of the language of the book.
But you can manually check/uncheck the dict you need/don't need for the book you're currently reading (their state is not saved per book thus). Human choice may work better than auto selection (that we can't do).
