### ISSUE TITLE
Is it possible to scroll by one line?

### ISSUE THREAD

**Issue by N46AN** [koreader/koreader#4506]
Is it possible to scroll by one line while reading txt/epub/mobi... ?

For example, sometimes it would be convenient to let some paragraph in one page, i.e. not splitted between pages. Currently in scroll mode (`copt_view_mode=1`), it scrolls by `ges.distance` which is quite hard to precisely control. (Line height is 10~20 pixels).

**Comment by Frenzie** [comment]
Should be fixed by https://github.com/koreader/koreader/commit/d0165f8bd1a8335ffc8f3b1aa5b12cf86ae3c98b.
