### ISSUE TITLE
Update kobo library

### ISSUE THREAD

**Issue by RobotCaleb** [koreader/koreader#4508]
* KOReader version: na
* Device: Kobo H2O 2

Is it possible to update the native Kobo library?

I haven't used koreader in ... over a year, so I might be out of date. As I recall, the two libraries were distinct and entirely separate. I felt more comfortable with some features that were missing in koreader and ended up switching back, but when I did I noticed that I didn't have the same library I had built up in koreader.

**Comment by pazos** [comment]
KOReader doesn't have a library, just a file manager/explorer. So, if your question is: **_I want to use KOReader again, can I read books from Kobo library?_** the anwser is 
- yes **for nonDRM sideloaded ebooks**
- no **for books that belong to kobo or are protected by adobe DRM**

If the question is: **_Can I access the same books from KOReader/kobo?_** the anwser is 

- yes, **except if you put your books on a hidden folder** (folders starting with a dot, like ".ebooks") In that case **KOReader will be able** but **nicke**l (kobo program) won't.

Welcome back to KOReader! I hope you enjoy more this time :smile: Questions are welcomed here, but IMO is it better to keep github issues as a bug / feature request tracker and ask general questions in [KOReader forum](https://www.mobileread.com/forums/forumdisplay.php?f=276), where the topic can reach more users!

**Comment by RobotCaleb** [comment]
Okay, great. Thanks for the clarification.

We'll see if I recall what my complaints were and whether I feel up to doing anything about them. :)
