### ISSUE TITLE
[feature request] Add support to sync progress position with moon+ reader dropbox/gdrive positions

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4510]
* KOReader version:
* Device:

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

I use moon+ reader on my phone/tablet.  it would be amazing!! if position sync could be enabled via dropbox.  that way i could read with the most up to date position across any device.  WOWSERS! :)

**Comment by ZZZXXX0110** [comment]
Second to this, Moon+ Reader is probably the best ereader available on Android, it will be great if we can sync reading progress across our different devices.

**Comment by pazos** [comment]
Moon+ is not open source, it doesn't have an API. We can do nothing, AFAIK. Maybe you can ask them to provide a way to sync progress with third party software.
