### ISSUE TITLE
Failed to compile for Android on Kubuntu 18.10

### ISSUE THREAD

**Issue by ZZZXXX0110** [koreader/koreader#4511]
* KOReader version: 2019.01.1
* Device: MSI GS65 running Kubuntu 18.10

#### Issue
Compile for Android fail with log:

-compile:
    [javac] Compiling 5 source files to /mnt/Programs/koreader/platform/android/luajit-launcher/bin/classes
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.

BUILD FAILED
/mnt/Programs/koreader/base/toolchain/android-sdk-linux/tools/ant/build.xml:716: The following error occurred while executing this line:
/mnt/Programs/koreader/base/toolchain/android-sdk-linux/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 0 seconds
make[2]: *** [apk] Error 1
make[2]: Leaving directory `/mnt/Programs/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/mnt/Programs/koreader'
make: *** [Makefile:445: update] Error 2

#### Steps to reproduce
Attempt to compile for Android with "./kodev release android".

**Comment by pazos** [comment]
Can't reproduce, are you sure you are building with JDK/openJDK **8** ¿?

**Comment by Frenzie** [comment]
Yeah, that indicates using one that's too new. See the README and https://github.com/koreader/koreader/issues/4254#issuecomment-440025378

**Comment by ZZZXXX0110** [comment]
> Yeah, that indicates using one that's too new. See the README and [#4254 (comment)](https://github.com/koreader/koreader/issues/4254#issuecomment-440025378)

Followed the directions linked by Frenzie worked! Thank you!

**Comment by Frenzie** [comment]
That being said, we might want to look into updating some of that ~2014 era stuff.

**Comment by Frenzie** [comment]
Yeah, I meant "update" more than update. If 6 and 1.6 are compatible with openJDK 8 then we might as well give it a try I suppose.
