### ISSUE TITLE
How to pull books from Dropbox? [paperwhite 4] [online storage options seem missing (except for ODPS)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4518]
* KOReader version:
* Device:

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

From https://github.com/koreader/koreader/pull/2424#issuecomment-267410178 It looks like there is an option for online storage that I don't see on the january build for my paperwhite 4.  am I missing something?  Or did it move to somewhere else?  

Would love to pull from my calibre book library (which is hosted on dropbox).  can this be done?

**Comment by pazos** [comment]
![filemanager_2019-jan-29_000645](https://user-images.githubusercontent.com/975883/51872522-09cd7780-235a-11e9-90e6-dbb29e1cd8a8.png)

cloud storage

**Comment by arooni** [comment]
right, but i dont seem to have cloud storage listed as a plugin at all.
(paperwhite 4).  and doesnt seem to be listed in plugin manager.

may today be the best day of your life,
-------
david parkinson
founder - aroonilabs.com
blog - davidparkinson.com  <https://www.davidparkinson.com/>
twitter - @followdavid <https://twitter.com/followdavid>

**Comment by pazos** [comment]
> right, but i dont seem to have cloud storage listed as a plugin at all.
(paperwhite 4).  and doesnt seem to be listed in plugin manager.

That is weird (I don't have any Kindle).

1. Go to plugin manager
2. Disable **all** the plugins
3. Restart KOReader
4. It should be the first option on plugins menu, If it isn't could you please take a screenshot/photo and share it. 

I have no idea, this kind of thing shouldn't be device dependant.

**Comment by Frenzie** [comment]
It's probably only in the file manager. (I don't have a device at hand atm.)

**Comment by arooni** [comment]
confirmed.  i can definitely select cloud storage from within the file manager.  didn't see it within a book.  thanks!

**Comment by wokawoka** [comment]
I'm experiencing the same problem here on a kindle touch.
I believe that the "online storage" option was previously in the menu before updating via OTA from an old version today (but I'm not 100% sure).
I can't find it now in the plugins tab nor in the file manager. Running the last v2019.02-8-g3f41560 version. 
Any idea?

**Comment by Frenzie** [comment]
Does it say anything about it in the crash.log?

**Comment by wokawoka** [comment]
it doesn't look so, from what I've seen it did log the correct loading of all the other plugins. I did search for "storage" or "online storage" and "dropbox" in the crash.log but I didn't find any hit. Which is the specific name of the online storage plugin I should look for?
Thanks

**Comment by Frenzie** [comment]
It's cloud storage, see the screenshot in https://github.com/koreader/koreader/issues/4518#issuecomment-458339290.

**Comment by wokawoka** [comment]
Thank you for your reply.
Then there are no recent references to the cloud storage plugin in the crash.log.
The only references I find are old koreader/frontend/apps/cloudstorage/drop-boxapi.lua  /cloud-storage.lua ftp.lua lines from 2018.
It looks like the plug-in is totally missing. I don't know if it should but it's also not listed in the plugin management menu as well. 
Differently from arooni comment here [https://github.com/koreader/koreader/issues/4518#issuecomment-458701999](url) it looks like that I can't access the cloud storage even from the file manager.
Thanks again

**Comment by Frenzie** [comment]
It's the fourth entry on the tools menu. Are you using a custom menu order?

(It's not a plugin, btw.)

**Comment by wokawoka** [comment]
there's no "cloud storage" entry on the tools meno on my kindle touch.
I'm pretty sure there was and that I correctly set it up last year or two years ago but it did disappear yesterday after an OTA update to the latest version.

![img_20190206_123602409](https://user-images.githubusercontent.com/7824587/52338921-fe3e1880-2a0b-11e9-9829-c8e10aac4f46.jpg)

**Comment by Frenzie** [comment]
That picture shows the reader, not the file browser.

![filebrowser](https://user-images.githubusercontent.com/202757/52340036-09467800-2a0f-11e9-864c-d28cd927d211.jpg)

**Comment by Frenzie** [comment]
You can reach the file browser though the file browser icon circled above.

Btw, is that weird arrow artifact something you edited onto the picture or does it look like that on your actual device? Also pinging @NiLuJe

**Comment by NiLuJe** [comment]
That's ghosting from the page 2 of the menu.

**Comment by Frenzie** [comment]
I guess the Touch must be pre-2014ish? That looks pretty bad. That square is also normal?

**Comment by NiLuJe** [comment]
Ironically, it ghosts *more* because it flashed (hence the square).

**Comment by NiLuJe** [comment]
Yeah, the Touch is using the original Pearl screen ;).

**Comment by wokawoka** [comment]
Yes, it's ghosting here and there quite often, but never to a point that is annoying, in my opinion. 

I know where the file browser is (I also did use it to inspect the crash log), but I can't find any way to access the cloud storage option from there as well.

I'm also experiencing many crashes while trying to open some books (it expecially happened while trying to open azw books on the device) that forced me to reboot the device because it froze each time. 
I don't remember koreder ever crashing on this device before, but I could be wrong.
As I believe I don't have any way to go back to the previous old version, maybe I should clear the config and reconfigure it from scratch. 
What do you think?

![img_20190206_142222252](https://user-images.githubusercontent.com/7824587/52344349-c4c0d980-2a1a-11e9-86bd-8556e347080e.jpg)

**Comment by NiLuJe** [comment]
Define "previous".

Mobi support hasn't been touched in ages (if ever? :D), so, that's strange.

**Comment by wokawoka** [comment]
I've just went through the downloads folder of my pc and I'm pretty sure that the previous version I was running on this device (the only kindle I have which ever run koreader) was koreader-kindle-arm-linux-gnueabi-v2015.11-1287-g5a2c8e4 downloaded and installed on 15/10/2017. I may have updated it via OTA maybe once after that but, if so, probably just in the close following months

**Comment by NiLuJe** [comment]
Well, dusted off my Touch to double-check: I was running `2015.11-309`. Ouch. Pre-new homescreen and everything xD.

So, after an update, nothing wrong over here.

![cstore](https://user-images.githubusercontent.com/111974/52363826-fac68380-2a43-11e9-884d-7c47d063eeb1.png)

It is indeed ghosting mightily, though :D.

**Comment by wokawoka** [comment]
interesting. Did the OTA updated it to v2019.02-8-g3f41560?

Maybe I should try to reset the settings to see if the cloud storage option reappears. What do you think? Anything else to try before doing that?
Thanks again

**Comment by NiLuJe** [comment]
No, I did a clean install, (in the most brutal manner possible: via the KUAL extension, which basically deletes the koreader folder). (Besides, I keep all my Kindles in Airplane mode).

So, yeah, that sounds like a good idea. I don't OTOH recall where every setting might be hiding (besides `settings.reader.lua`, `settings/` and the persistent `defaults.lua`), so I'd just rename your current koreader folder and do a clean install.

**Comment by wokawoka** [comment]
Alright, then I'll do a clean install as soon as I'll find some time during the weekend. For the moment I need the reader for my presleep readings.
Thank you very much for helping!

**Comment by wokawoka** [comment]
@NiLuJe, sorry for resurrecting again this issue (and for having hijacked an issue about the paperwhite 4 in the firs place) but I've just cleanly installed the last 2019.02 version of koreader downloaded from github on my kindle touch and the cloud storage menu line is still missing.
I did use the koreader-kindle-arm-kindle5-linux-gnueabi-v2019.02.zip
I don't know what to think.
Would you be so kind to tell me exactly which version you did test on your kindle [the last time you sent me the screenshot](https://github.com/koreader/koreader/issues/4518#issuecomment-461129739)?
Many thanks again

**Comment by NiLuJe** [comment]
@wokawoka : The nightly from 13 days ago ;). But the version should be fairly irrelevant as long as it's not severely outdated.

Which leads me to: define "clean install" ;).

**Comment by wokawoka** [comment]
I just did what you also suggusted [here](https://github.com/koreader/koreader/issues/4518#issuecomment-461140908) : I renamed the old koreader directory on the root folder and also the old koreader folder in the extensions subfolder.  Not clean enough?

**Comment by NiLuJe** [comment]
Lightbulb moment: you wouldn't happen to be using KPVBooklet, by chance?

**Comment by wokawoka** [comment]
I'm using KUAL to launch koreader.
I'm sure that in the past I was using the koreader cloud storage function because I still have a dedicated folder for koreader in my dropbox applications folder.
The option disappeared after the OTA update.
Would you be so kind to tell me precisely the koreader nightly version you did install so that I can try exactly with that and report back?
Many thanks again

**Comment by uphantom89** [comment]
For dropbox storage, I intend to download .azw3 file, however, the file manager did not show this file type.
Is there anyway to work around? Please kindly advise

**Comment by ttoomm** [comment]
ACCESS "CLOUD STORAGE"
1. KUAL
2. koreader
3. Tap @ top
4. Tools
5. Send2ebook
6. Tap @ top again
7. Tools again and you'll find Cloud Storage
