### ISSUE TITLE
Wallabag sync error on kindle PW 4 "Could not login to Wallabag server"

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4519]
* KOReader version: v2019.01.01
* Device: Kindle PW4 

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

Error:
Could not connect to wallabag server
Communication Failed

even though i've verified that this :

http POST https://framabag.org/oauth/v2/token     grant_type=password     client_id=clientid     client_secret=clientsecret     username=arooni     password=password

results in:

HTTP/1.1 200 OK
Cache-Control: no-store, private
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Sun, 27 Jan 2019 22:16:30 GMT
Pragma: no-cache
Server: nginx
Transfer-Encoding: chunked
Vary: Accept-Encoding

{
    "access_token": "accesstoken",
    "expires_in": 3600,
    "refresh_token": "token",
    "scope": null,
    "token_type": "bearer"
}

this is my wallabag.lua file:

-- we can read Lua syntax here!
return {
["wallabag"] = {
["is_delete_finished"] = true,
["directory"] = "/mnt/us/ebooks/downloads",
["filter_tag"] = "",
["client_secret"] = "clientsecret",
["password"] = "pass",
["client_id"] = "clientid",
["is_delete_read"] = false,
["is_sync_remote_delete"] = false,
["username"] = "arooni",
["server_url"] = "https://framabag.org/oauth/v2/token",
["is_auto_delete"] = false
}
}
~

not sure how to proceed.

**Comment by Frenzie** [comment]
Pinging @y-muller 

I assume that where you say things like `["client_secret"] = "clientsecret",` you mean that you put your client secret there?

**Comment by y-muller** [comment]
The server_url parameter is incorrect. It should be "https://framabag.org".
I have just created an account on this server and it worked.

Let me know if it still doesn't workfor you  after fixing the server URL.

**Comment by arooni** [comment]
Yes I had all the correct data there.  But  changing the url worked .  I didn't see on the wallabag app or koreader info that it just needed the top level url.  Thanks folks !!!

**Comment by Frenzie** [comment]
Alright, closing then. Where'd you get the other server URL from btw?

**Comment by arooni** [comment]
I was guessing really.  The instructions were a bit sparse on framabag.  I did try to check koreader docs too.

Question; do you know if they allow 1000 articles total or 1000 unread articles?

**Comment by Frenzie** [comment]
Probably total. I think they'd mention unread otherwise.

**Comment by arooni** [comment]
running into this now again :(

```
-- we can read Lua syntax here!
return {
    ["wallabag"] = {
        ["articles_per_sync"] = 10,
        ["client_id"] = "clientid
        ["client_secret"] = "secret
        ["directory"] = "/mnt/us/ebooks/wallabagv2/",
        ["download_queue"] = {},
        ["filter_tag"] = "",
        ["ignore_tags"] = "",
        ["is_archiving_deleted"] = false,
        ["is_auto_delete"] = true,
        ["is_delete_finished"] = true,
        ["is_delete_read"] = true,
        ["is_sync_remote_delete"] = false,
        ["password"] = "pass",
        ["remove_finished_from_history"] = true,
        ["server_url"] = "https://bag.g3l.org",
        ["username"] = "arooni",
    },
}

i can set it up find on android but not on the kindle @Frenzie 

i see no output in the log


```

**Comment by Frenzie** [comment]
@arooni 
> i can set it up find on android but not on the kindle

Are you saying you copied the file from Android and only changed the directory? Otherwise try that. ^_^

**Comment by arooni** [comment]
@Frenzie 

Was saying that I had configured wallabag successfully on the android version of that app (not koreader).  When I sent a POST request with the right data this time:

```
HTTP/1.1 302 Found
Cache-Control: no-cache, private
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
Date: Sat, 04 Sep 2021 02:01:40 GMT
Keep-Alive: timeout=5, max=100
Location: https://bag.g3l.org/login
Server: Apache/2.4.38 (Debian)
Transfer-Encoding: chunked
X-Powered-By: PHP/7.4.23

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='https://bag.g3l.org/login'" />

        <title>Redirecting to https://bag.g3l.org/login</title>
    </head>
    <body>
        Redirecting to <a href="https://bag.g3l.org/login">https://bag.g3l.org/login</a>.
    </body>
</html>
```

I was getting a 200 OK before so not sure if there's additional config that this new wallabag host requires?

**Comment by Frenzie** [comment]
It might potentially be worth pointing out that you're missing closing quotation marks, though I figured that was just because you removed it to keep it secret.

```lua
-- we can read Lua syntax here!
return {
    ["wallabag"] = {
        ["articles_per_sync"] = 10,
-- here
        ["client_id"] = "clientid
-- and here
        ["client_secret"] = "secret
        ["directory"] = "/mnt/us/ebooks/wallabagv2/",
        ["download_queue"] = {},
        ["filter_tag"] = "",
        ["ignore_tags"] = "",
        ["is_archiving_deleted"] = false,
        ["is_auto_delete"] = true,
        ["is_delete_finished"] = true,
        ["is_delete_read"] = true,
        ["is_sync_remote_delete"] = false,
        ["password"] = "pass",
        ["remove_finished_from_history"] = true,
        ["server_url"] = "https://bag.g3l.org",
        ["username"] = "arooni",
    },
}
```
