### ISSUE TITLE
Filebrowser doesn't display .cbr files

### ISSUE THREAD

**Issue by Sopheus** [koreader/koreader#4520]
* KOReader version: KOReader 2019.01 "Public Domain 1923"
* Device: Kobo Aura H2O (First edition)

#### Issue
Filebrowser doesn't display .cbr files

#### Steps to reproduce
Copy files, navigate to respective folder, observe the issue

**Comment by Sopheus** [comment]
Attach

**Comment by Sopheus** [comment]
https://drive.google.com/file/d/1H_zm5o9uHYCXszYZ8JAesJyjS0XsekxX/view?usp=sharing

**Comment by Sopheus** [comment]
After I changed the extension to .cbz, I can see the file in File Browser, but unable to open it, getting "No reader engine for this file or invalid file" error.

**Comment by Sopheus** [comment]
Wanted to add that I can open the .cbr files in Nickel

**Comment by Sopheus** [comment]
Here is the file, which I unable to open in Koreader, but able in Nickel: https://drive.google.com/file/d/1H_zm5o9uHYCXszYZ8JAesJyjS0XsekxX/view?usp=sharing

**Comment by poire-z** [comment]
Duplicate of #1517.
(There is no unrar support in KOReader - except some in crengine - but CBR would need MuPDF to be able to read RAR files.)

**Comment by KenMaltby** [comment]
The RAR compressor will let you create a RAR file that uses the ZIP compression of the data, sometimes a comic book gets made a .cbr that is, actually zip compressed.  Not the case here apparently.

**Comment by cramoisi** [comment]
@Sopheus Use nickel as it supports them. Or if you want to be koreader all along, you just have to change the extension of your cbr to rar ; then unrar the file, zip it and rename it to cbz :)

**Comment by Frenzie** [comment]
Closing since it's a duplicate.
