### ISSUE TITLE
menu translation with transiflex

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#4522]
* KOReader version:
* Device: kobo aura one

Hello,
I translate in french all the new menus as and with transiflex. However, some translated menus still appear in English on my reader. Why?

**Comment by Frenzie** [comment]
The most likely answer is that the version you're using doesn't yet include the updated translations. Without knowing which version you're using and which menus you're talking about there's not much to go on.

You can always grab the latest nightly build [here](http://build.koreader.rocks/download/nightly/) or OTA update using the nightly channel.

**Comment by davicraquette** [comment]
I am aware that we have to wait for the new translation to appear on the next version.
So I confirm that the latest translations are not always on the latest nightly build
[TRANSIFEX.pdf](https://github.com/koreader/koreader/files/2803237/TRANSIFEX.pdf)
![20190128_145827 1](https://user-images.githubusercontent.com/39924188/51840836-72dace00-230d-11e9-99f1-dfdaed434194.jpg)

**Comment by Frenzie** [comment]
I see, that's #4085.

**Comment by poire-z** [comment]
My bad... (I corrected those old bad ones, and I since added some new bad ones...)
Going to fix these recent bad ones.

**Comment by poire-z** [comment]
Is there an issue with Transiflex when the source text contains the string `<H1 to <H6>`?

The `1` and `2` in blue shown with a darker background in the pdf:

![image](https://user-images.githubusercontent.com/24273478/51845328-a4f12d80-2317-11e9-9f6b-a912a427a8b1.png)

**Comment by davicraquette** [comment]
indeed, I have the feeling that the problem comes from the chains since all the menus containing these signs do not translate

**Comment by Frenzie** [comment]
> The 1 and 2 in blue shown with a darker background in the pdf:

Are you sure? :-)

**Comment by poire-z** [comment]
> Hold up on that; we can just eat a newline after [[ in Python

Pushed the change anyway, just for coherency in the code. I'll make that error again anyway, so your python fix is welcome :) (and because it gave me a chance to push a parapgraph tweak I had lying around).

> Are you sure? :-)

About me getting confused with blue or grey ? which is quite possible. Or about me seeing some 1 and 2 that are not there ?! :)

**Comment by Frenzie** [comment]
> Pushed the change anyway, just for coherency in the code. 

I definitely prefer it with a newline, myself.

> About me getting confused with blue or grey ? which is quite possible. Or about me seeing some 1 and 2 that are not there ?! :)

The 1 and 2 look light purple to me in both English & French.

**Comment by Frenzie** [comment]
@davicraquette Transifex will now say there are 11 untranslated strings. The previous translation will be available under "suggestions." They can be left exactly as is, except for the newline at the start.
