### ISSUE TITLE
Minimum frontlight level in Kobo Clara HD

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#4523]
* KOReader version: 2019.01.1
* Device: kobo clara hd

#### Issue

When frontlight level is set to the minimum (1%) this level is still too high compared to the same minimum level set in nickel. You can only notice this when using the frontlight at 1% in a complete dark room.  In this situation 1% can be a little too bright in koreader. Nickel can go lower. (I didn't have this problem with the Glo HD, when the minimum light level in koreader was as low as in nickel.)

Is it possible to remap the frontlight levels in koreader for the Clara HD so the minimum level matches the real minimum level of the device?

#### Steps to reproduce

Compare 1% frontlight level between koreader and nickel in a complete dark room.

**Comment by NiLuJe** [comment]
Possibly sysfs vs. ioctl using slightly different tables, somehow?

Weird, but not out of the realm of possibilities...

**Comment by pazos** [comment]
using the mixer interface like in the Forma is an option. @NiLuJe Did you find differences between nickel and koreader at the same level?

**Comment by NiLuJe** [comment]
Haven't bothered to check, as the differences, if any, are small enough not
to bother me.

**Comment by pazos** [comment]
@pblasi: You can try switching to the mixer, since your device doesn't have green leds.

```diff
--- a/frontend/device/kobo/device.lua
+++ b/frontend/device/kobo/device.lua
@@ -191,8 +191,11 @@ local KoboNova = Kobo:new{
     display_dpi = 300,
     hasNaturalLight = yes,
     frontlight_settings = {
-        frontlight_white = "/sys/class/backlight/lm3630a_ledb",
-        frontlight_red = "/sys/class/backlight/lm3630a_leda",
+        frontlight_white = "/sys/class/backlight/lm3630a_ledb/brightness",
+        frontlight_mixer = "/sys/class/backlight/lm3630a_led/color",
+        nl_min = 0,
+        nl_max = 10,
+        nl_inverted = true,
```

If it works for you then we can apply this to newer devices too, if that doesn't work for you then this will be a non fixable issue :p

**Comment by pblasi** [comment]
@pazos : Sorry I'm not a developer, but I guess I need to edit the device.lua file for kobo, deleting "-" lines and adding "+" lines, right? I don't know what this numbers mean in the first row though:
`@@ -191,8 +191,11 @@ local KoboNova = Kobo:new{`
Anyway here's how the file looks now and frontlight is not working at all in koreader. Did I do something wrong? Thanks
```
-- Kobo Clara HD:
local KoboNova = Kobo:new{
    model = "Kobo_nova",
    hasFrontlight = yes,
    touch_snow_protocol = true,
    display_dpi = 300,
    hasNaturalLight = yes,
    frontlight_settings = {
        frontlight_white = "/sys/class/backlight/lm3630a_ledb/brightness",
        frontlight_mixer = "/sys/class/backlight/lm3630a_led/color",
	nl_min = 0,
	nl_max = 10,
	nl_inverted = true,
        -- NOTE: There doesn't appear to be a dedicated "green" LED, instead,
        --       there's a knob that mixes the white & red ones together (/sys/class/backlight/lm3630a_led).
        --       c.f., https://www.mobileread.com/forums/showpost.php?p=3728236&postcount=2947
    },
}
```

**Comment by Frenzie** [comment]
@pblasi The numbers are the line number. Any programmer's editor will show those. :-)

> Anyway here's how the file looks now and frontlight is not working at all in koreader. Did I do something wrong?

That looks correct, assuming you mean only part of the file. Unfortunately that means the issue probably can't really be fixed.

**Comment by pazos** [comment]
@pblasi 

> Anyway here's how the file looks now and frontlight is not working at all in koreader

On the bright side that means that brightness is not too high anymore :duck: 

Nah!, probably that particular node needs bl_power to work. After reading https://www.mobileread.com/forums/showpost.php?p=3728236&postcount=2947 it seems that you can try using mxc_msp430.0 instead of lm3630a_leb.

So your device will look like:

``` lua
-- Kobo Clara HD:
local KoboNova = Kobo:new{
    model = "Kobo_nova",
    hasFrontlight = yes,
    touch_snow_protocol = true,
    display_dpi = 300,
    hasNaturalLight = yes,
    frontlight_settings = {
        frontlight_white = "/sys/class/backlight/mxc_msp430.0/brightness",
        frontlight_mixer = "/sys/class/backlight/lm3630a_led/color",
	nl_min = 0,
	nl_max = 10,
	nl_inverted = true,        
    },
}
```

If that works then good!, if that doesn't work then we can do nothing (I mean, a person *with* the device and *bothered* enough to look at it and willing to spend some time learning how KOReader handles stuff may probably "fix" that)

**Comment by pblasi** [comment]
It works! @pazos you're the best! Now minimum brightness is as low as in nickel! Plus temperature steps are reduced to 10 like in nickel as well (in only changes at 0, 10, 20... 100). I couldn't be happier! (and my wife too, who complained about the kobo being too bright when she was trying to sleep :)
Thank you!
