### ISSUE TITLE
[question] How does exporting evernote notes work when they are *already* exported?

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4526]
1) When I attempt to export all notes from all books in EVERNOTE I see that it seems to create a new note for each book. What happens if I do an export AGAIN, will it duplicate notes? What happens if I create new notes for a book I've already exported, will it replace it? 

2) related; if you export evernote notes from a separate device that's already exported, does it just overwrite the existing note?  last one exported wins?

**Comment by pazos** [comment]
> What happens if I do an export AGAIN, will it duplicate notes? What happens if I create new notes for a book I've already exported, will it replace it?

No duplicates. New notes will be added to the documented. Deleted notes will be deleted in the document.

>  if you export evernote notes from a separate device that's already exported, does it just overwrite the existing note? last one exported wins?

Yeah, for the same document last exported wins. That's not a problem because it's a one-way sync and you can go to your other device where all your notes are and re-export them again.
