### ISSUE TITLE
Don't display network settings on devices without network capabilities.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4527]
- Devices with full wifi manager (using lj-wpasupplicant): kobo, cervantes & sony-prstux.
- Devices with wifi toggle but no manager (relying on system settings): android & kindle, pocketbook?
- Devices where we cannot toggle wifi: SDL targets: appimage, debian, ubuntu touch, etc?

It doesn't make sense to have the wifi toggle disabled on platforms like desktops.
It doesn't make sense to have options related to wireless manager on platforms that don't have one.

Common settings for all devices are: http proxy, network info/status and ssh if the plugin is enabled
++ settings for devices with wifi toggle: enable/disable wifi
++ settings for devices with wifi manager: all the rest.

So, I guess we can have two more hardware settings, hasWifi and hasWifiManager and display settings accordly.

This is the same we already do on power capabilities (suspend, reboot/poweroff), where instead of showing those options disabled we just display them on supported devices. I guess that can be abstracted too (ie: canSleep / canTogglePower).

**Comment by Frenzie** [comment]
> It doesn't make sense to have the wifi toggle disabled on platforms like desktops.

That depends, think of the emulator. ;-)

But yes, that all sounds good.
