### ISSUE TITLE
[goodreads plugin potential issue]: seems developer secret key is getting overwritten -- no searches work

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4528]
* KOReader version: 2019,01,01
* Device: paperwhite 4

#### Steps to reproduce

1) enter developer key and secret from goodreads.  
2) notice that the goodreads setting lists the key value twice (once in key and once in place of the secret).  this is the case even though editing /koreader/settings/goodreadsettings.lua is set to the correct values (edited on mac)
3) no searches seem to work with goodreads.  
4) be sad and go cry.   go to the library instead.  :P

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by robert00s** [comment]
@arooni 
Try enter only developer key.
Something like that.
![obraz](https://user-images.githubusercontent.com/22982594/60681374-4bc19300-9e8f-11e9-8b4a-4b2cf13da665.png)

**Comment by arooni** [comment]
So I did try that; using only the key (not the secret) and I still cannot get searches to return anything.  I tried searching "dickens" under author search and got "Search not found!"

**Comment by robert00s** [comment]
Can you try to reset api key?

![obraz](https://user-images.githubusercontent.com/22982594/61281503-03bd3d00-a7ba-11e9-9eb6-fa0b9f4a01fd.png)

**Comment by arooni** [comment]
Yeah that worked great!  Just using the key, not the secret with a reset api key allows me to use this.  YAY ... thanks!

**Comment by robert00s** [comment]
Great :)
