### ISSUE TITLE
Non book items (RSS downloads for instance) do not appear in history (between KOreader restarts)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4534]
* KOReader version: 2019.01.01
* Device: kindle PW4

#### Issue
Non book items like RSS downloads from sites I follow, and perhaps even wallabag articles don't appear in history.  Maybe this is intentional?  I think ideally they'd appear there.  And maybe have a filter in history for different types of content like kindle does (news, books, all, etc).

Anyway

#### Steps to reproduce
1) open a non book like a rss download
2) switch to another book.  notice that the article shows in history.  
3) restart koreader, notice that the article is no longer in the history list.

**Comment by Frenzie** [comment]
Yes, that's intentional. Categories are an interesting idea.
