### ISSUE TITLE
news downloader seems not to like various rss feeds

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4540]
* KOReader version: 2019.01.01
* Device: paperwhite v4 2018

#### Issue
set up 8-9 rss feeds, 4-5 work and the other half seem to have some error.  I do not see error messages in the crash.log.  

i checked a few rss feeds and the validator did identify some errors, so perhaps unless each feed is perfect it won't download?

also somewhat related; if i tell koreader i only want 10 articles per site, and i've read 2-3, what will happen?  does it always download the latest 10 and delete any others?  or must i run 'delete news' to get the thing to clear?

#### Steps to reproduce
run the rss update / download feature.  

see the following message:

![image](https://user-images.githubusercontent.com/556667/52138347-838f8a80-2612-11e9-9d2d-7ca59c2c8512.png)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
`https://www.starterstory.com/feed?format=rss` might be a bug, pinging @mwoz123 

`https://okdork.com/feed/` is not properly encrypted.

```
curl -I https://okdork.com/feed/
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```

It's not entirely clear to me why this thing thinks there's a 301 status involved, but I imagine that's the root of the problem.
```
02/01/19-18:24:30 DEBUG InternalDownloadBackend: url : https://okdork.com/feed/
02/01/19-18:24:31 DEBUG InternalDownloadBackend: HTTP response code <> 200. Response status:  HTTP/1.1 301 Moved Permanently
02/01/19-18:24:31 DEBUG InternalDownloadBackend: Redirecting to url:  https://okdork.com/feed/
02/01/19-18:24:31 DEBUG InternalDownloadBackend: url : https://okdork.com/feed/
02/01/19-18:24:33 DEBUG InternalDownloadBackend: HTTP response code <> 200. Response status:  HTTP/1.1 301 Moved Permanently
02/01/19-18:24:33 DEBUG InternalDownloadBackend: Redirecting to url:  https://okdork.com/feed/
02/01/19-18:24:33 DEBUG InternalDownloadBackend: url : https://okdork.com/feed/
02/01/19-18:24:35 DEBUG InternalDownloadBackend: HTTP response code <> 200. Response status:  HTTP/1.1 301 Moved Permanently
02/01/19-18:24:35 DEBUG InternalDownloadBackend: Redirecting to url:  https://okdork.com/feed/
02/01/19-18:24:35 DEBUG InternalDownloadBackend: url : https://okdork.com/feed/
02/01/19-18:24:37 DEBUG InternalDownloadBackend: HTTP response code <> 200. Response status:  HTTP/1.1 301 Moved Permanently
02/01/19-18:24:37 DEBUG InternalDownloadBackend: Redirecting to url:  https://okdork.com/feed/
02/01/19-18:24:37 DEBUG InternalDownloadBackend: url : https://okdork.com/feed/
02/01/19-18:24:38 DEBUG InternalDownloadBackend: HTTP response code <> 200. Response status:  HTTP/1.1 301 Moved Permanently
02/01/19-18:24:38 DEBUG InternalDownloadBackend: Redirecting to url:  https://okdork.com/feed/
```

`http://feeds.feedburner.com/tynan` works for me, temporary server trouble?

`https://growthlab.com/feed` works if you use `http://growthlab.com/feed` instead

`http://jamesclear.com/feed` works for me

**Comment by jfmcbrayer** [comment]
I am having this issue. I self-host tt-rss on https only, and it can generate a public feed for my starred articles like https://my-host.domain/tt-rss/public.php?op=rss&id=-1&key=at80srta8stranuyrsa8 (this is not a real URL).

Is it the case that no https-only feeds work?

**Comment by Frenzie** [comment]
https works perfectly fine, but I can't verify with certainty atm that this still applies to the NewsDownloader plugin. As I wrote above the HTTPS feed that didn't work wasn't encrypted properly.

For example, this feed worked fine last time I checked: https://github.com/koreader/koreader/releases.atom
