### ISSUE TITLE
[Android]: Error renaming a file

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4543]
* KOReader version: All of them
* Device: Android

#### Issue

Renaming a book crashes the reader, leading to a unknown state which requires killing the activity to work again.

#### Steps to reproduce

rename a file (I only tried with ebooks), it crashes with the error `E luajit-launcher: Failed to run script: ffi/util.lua:123: undefined symbol: __xpg_basename` .

Maybe the function [util.basename](https://github.com/koreader/koreader-base/blob/master/ffi/util.lua#L118) doesn't work on Android at all.

**Comment by NiLuJe** [comment]
There's a POSIX and a GNU version of basename/dirname, I'd have to check which one we're trying to use w/ ffi, and which one Android actually implements (if any).

**Comment by NiLuJe** [comment]
Okay, the XPG one from <libgen.h> is the POSIX one.

**Comment by Frenzie** [comment]
Android seems to use its own Frankenbasename. "Doesn't modify its input path" is GNU behavior afaik yet it claims to be POSIXish? But I guess as long as it uses POSIX `/` behavior it shouldn't really matter in a practical sense.

Android platform 9:
```c
__BEGIN_DECLS

/*
 * Including <string.h> will get you the GNU basename, unless <libgen.h> is
 * included, either before or after including <string.h>.
 *
 * Note that this has the wrong argument cv-qualifiers, but doesn't modify its
 * input and uses thread-local storage for the result if necessary.
 */
char* __posix_basename(const char*) __RENAME(basename);

#define basename __posix_basename

/* This has the wrong argument cv-qualifiers, but doesn't modify its input and uses thread-local storage for the result if necessary. */
char* dirname(const char*);

#if !defined(__LP64__)
/* These non-standard functions are not needed on Android; basename and dirname use thread-local storage. */
int dirname_r(const char*, char*, size_t);
int basename_r(const char*, char*, size_t);
#endif

__END_DECLS
```

Newer Android:
```c
__BEGIN_DECLS

/*
 * Including <string.h> will get you the GNU basename, unless <libgen.h> is
 * included, either before or after including <string.h>.
 *
 * Note that this has the wrong argument cv-qualifiers, but doesn't modify its
 * input and uses thread-local storage for the result if necessary.
 */
char* __posix_basename(const char*) __RENAME(basename);

#define basename __posix_basename

/* This has the wrong argument cv-qualifiers, but doesn't modify its input and uses thread-local storage for the result if necessary. */
char* dirname(const char*);

#if !defined(__LP64__)
/* These non-standard functions are not needed on Android; basename and dirname use thread-local storage. */
int dirname_r(const char*, char*, size_t);
int basename_r(const char*, char*, size_t);
#endif

__END_DECLS
```

The easy way out of this specific example would be just to replace it with a Lua patterns implementation, which we basically already have in front:

https://github.com/koreader/koreader/blob/27b6c1546a620cb651b7bbd9a8d1b242480ddec7/frontend/util.lua#L444-L453

(Except of course for basename we'd need `string.gsub(file, "(.*/)(.*)", "%2")` instead.)

But perhaps taking the easy way out would be disadvantageous in the long run.

**Comment by Frenzie** [comment]
Um, that kind of works. KOReader showed the rename dialog, i.e., it didn't crash when loading this into memory:

https://github.com/koreader/koreader/blob/ea946d52d688d77d323e5ea862f3797a0700fbbf/frontend/apps/filemanager/filemanager.lua#L241-L246

But… and this is a first for me — the Android emulator just disappeared. (Of course by this point we're using `mv`, not basename.) Let me start the thing from the command line to see what it says, because *of course* Android Studio never has any useful logs of any sort.

https://github.com/koreader/koreader/blob/ea946d52d688d77d323e5ea862f3797a0700fbbf/frontend/apps/filemanager/filemanager.lua#L60-L62

https://github.com/koreader/koreader/blob/ea946d52d688d77d323e5ea862f3797a0700fbbf/frontend/apps/filemanager/filemanager.lua#L897-L899

**Comment by Frenzie** [comment]
Well, I guess I should have expected this.
```
$ ./emulator -avd Nexus_5X_API_23
emulator: WARNING: encryption is off
Segmentation fault
```

Anyway, I'll quickly check if there are some differences between Android versions.

**Comment by Frenzie** [comment]
* Android 4.1: failed to rename popup
* Android 5, 6: KOReader shows the renamed file just before the emulator does a segmentation fault
* Android 8, 9: it renames

Obviously this was never written for Android 8 or 9, but for 2.3.

It's *probably* just an emulator flaw given that Google only pays attention to the latest emulator or two.

**Comment by NiLuJe** [comment]
Huh. What about switching `__xpg` to `__gnu` or `__posix`, in case that's a weird linker/loader shenanigan?

**Comment by Frenzie** [comment]
With `__gnu` it works the same as the other one (emulator segmentation fault). With `__posix` we get this:

```
02-03 16:50:06.916  5057  5074 E luajit-launcher: Failed to run script: ffi/util.lua:123: undefined symbol: __posix_basename
```

**Comment by NiLuJe** [comment]
Well, that's weird. :D.

**Comment by Frenzie** [comment]
Completely off topic, KOReader for Android runs like a charm on Sailfish.

![20190203180714](https://user-images.githubusercontent.com/202757/52180277-6c07fb80-27e4-11e9-9cc1-71774f21a3bb.jpg)

**Comment by pazos** [comment]
Hi, I'm not too bothered by the fact of the crash, but I'm interested in understand why the application isn't completely destroyed after the crash, which leds to the unknown state.

I will investigate that, since it could affect a bunch of other scenarios too. (ie: app crashes without error, like if focus was requested by another app, when focus is returned to app, it doesn't work, white background only). The application in this unkown state needs a force close to work again.

**Comment by pazos** [comment]
> Completely off topic, KOReader for Android runs like a charm on Sailfish.

That's nice

**Comment by Frenzie** [comment]
> The application in this unkown state needs a force close to work again.

Yes, the same issue applies with an early library loading failure in LuaJIT-land like on my Zenfone 2. It remains in some kind of weird running state. Ideally the Java would just shut down.

> That's nice

Not for #3872. :-P Of course KOReader for native Sailfish wouldn't suffer from weird issues like this basename thing, but besides that you wouldn't be able to tell the difference.

**Comment by pazos** [comment]
> i.e.,
> 
> ```diff
> diff --git a/ffi/posix_h.lua b/ffi/posix_h.lua
> index 6cdbb56..5852e69 100644
> --- a/ffi/posix_h.lua
> +++ b/ffi/posix_h.lua
> @@ -67,7 +67,7 @@ int usleep(unsigned int);
>  int statvfs(const char *restrict, struct statvfs *restrict) __attribute__((__nothrow__, __leaf__));
>  int gettimeofday(struct timeval *restrict, struct timezone *restrict) __attribute__((__nothrow__, __leaf__));
>  char *realpath(const char *restrict, char *restrict) __attribute__((__nothrow__, __leaf__));
> -char *basename(char *) __asm__("__xpg_basename") __attribute__((__nothrow__, __leaf__));
> +char *basename(char *) __attribute__((__nothrow__, __leaf__));
>  char *dirname(char *) __attribute__((__nothrow__, __leaf__));
>  void *malloc(size_t) __attribute__((malloc, leaf, nothrow));
>  void free(void *) __attribute__((leaf, nothrow));
> ```

That works fine here, thanks!

**Comment by NiLuJe** [comment]
Huh, so only the emulator gets its panties in a twist?

**Comment by Frenzie** [comment]
@NiLuJe Note that it's the emulator itself (QEMU) that suffers the segmentation fault while running Android 5 & 6. It seems unlikely that real Android would do much more than failing to rename, or possibly crashing KOReader.

**Comment by NiLuJe** [comment]
Okay, I'll PR this then ;).
