### ISSUE TITLE
Failed to update KOReader 

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4547]
* KOReader version: 2019.01.01
* Device: PW4

"Failed to update KOReader.  

You can: Cancel, keeping temporary files. Retry the update process with a full download.
Abort & cleanup al temporary files".  

Tried with the stable version of KOReader.  Across each OTA server available.  Same error message.

Have never done an update before so not exactly how this work (WIFI is enabled though)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Galunid** [comment]
I had the same error, did you try "Retry" option? That did the trick for me. It'd also be helpful, if you could include your `crash.log` file.

**Comment by Galunid** [comment]
My log:
```
02/04/19-00:26:33 INFO  opening file /mnt/us/documents/The King's Avatar 1421.epub
02/04/19-00:26:33 ERROR failed to register crengine font: cannot register font </usr/java/lib/fonts/Caecilia_LT_66_Medium_Italic.ttf>
02/04/19-00:26:33 ERROR failed to register crengine font: cannot register font </usr/java/lib/fonts/Caecilia_LT_75_Bold.ttf>
02/04/19-00:26:33 ERROR failed to register crengine font: cannot register font </usr/java/lib/fonts/Caecilia_LT_76_Bold_Italic.ttf>
02/04/19-00:26:33 INFO  Loading plugins from directory: plugins
02/04/19-00:26:33 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
02/04/19-00:26:34 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
02/04/19-00:26:34 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
02/04/19-00:26:34 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
02/04/19-00:26:34 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
failed to retrieve from http://ota.koreader.rocks:80/koreader-kindle-arm-kindle5-linux-gnueabi-v2019.02.targz
Not all of the required data could be downloaded, and the remaining data could not be retrieved from any of the download URLs. Incomplete transfer left in ./ota/koreader.updated.tar.part.
(If this is the download filename with .part appended, zsync will automatically pick this up and reuse the data it has already done if you retry in this dir.)
02/04/19-00:29:44 INFO  quitting uimanager
02/04/19-00:29:44 INFO  no dialog left to show
```

**Comment by NiLuJe** [comment]
Yep, happens when zsync gets its panties in a twist (which is becoming increasingly common, for whatever reason...).

That's precisely why Retry is there, as you've mentioned ;).

**Comment by Frenzie** [comment]
@NiLuJe Updating from an approximately two-week-old v2019.1 nightly to v2019.2, it worked on my H2O.

**Comment by NiLuJe** [comment]
No issues with tonight's nightly either on my end, FWIW.

**Comment by arooni** [comment]
I did find that restarting and then trying the update worked well.  Now I have mutli page highlight!  What more could I want?  I guess the ability to highlight and write a note in a .epub.  But honestly I could never go back to the vanilla kindle experience after KOreader.  Thanks team! :).

Closing.

**Comment by LucyOne** [comment]
Digging up this old thread, as I always get this error when updating KOReader on my two Pocketbooks. Hitting "Retry" works, but it's annoying. Any way to solve this issue?

**Comment by MrKaon** [comment]
I came here to say I had the same problem with my Kindle Paperwhite 11Gen updating from 2024.07 to 2024.11. Did manual update according to this link: https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#manual-update

**Comment by Frenzie** [comment]
That's unrelated (as is just about anything that could possibly be said about OTA — we switched to zsync2 in the meantime). Kindle stable OTA files are currently accidentally missing; they will be restored with the next release.
