### ISSUE TITLE
Battery notification still appears when already charging

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4560]
* KOReader version: 9e65ff4ac9c1110f391c1b9a1a278c517008a56a
* Device: H2O

#### Issue
The low battery notification still appears when you're already recharging. I think this check should be extended to include charging status:

https://github.com/koreader/koreader/blob/225b5d417d803fd0bb3037a4864ab977078cb824/frontend/apps/reader/modules/readerdevicestatus.lua#L19

(Unless we reason that it's a fairly minor annoyance and you might be "charging" due to transferring files without realizing the battery is low?)

#### Steps to reproduce
1. Lower the battery under the warning threshold (20 % by default).
2. Restart the program.

**Comment by NiLuJe** [comment]
Yup, adding an `and not powerd:isCharging()` in there sounds logical ;).

**Comment by KenMaltby** [comment]
I sometimes read while charging, and as of v2019.01.1-37, the only indicator that it is charging is a "+" before the battery % in the top menu or the mini-bar.  It sounds like you two are talking about something more intrusive.  I guess I haven't seen the "Low battery" notification yet, but if you are talking about a message box notification that would obscure the text I might be reading, that would not be good.

**Comment by Frenzie** [comment]
It's just a popup that can be dismissed. But like I said, it only happens at 20 % or lower by default. I'd never actually seen it until today, and it's been there for about half a year now.

**Comment by KenMaltby** [comment]
OK, I get it, sort of a temporary "Check Engine" light, nice to know it's there.
