### ISSUE TITLE
Page break before h2 and h3 headings

### ISSUE THREAD

**Issue by DanBenHa** [koreader/koreader#4565]
* KOReader version: 2019.01
* Device: Kobo Glo HD

#### Issue
Epub headings h2 and h3 cause page break before heading. In other readers I tried (Tolino Vision 4 HD, Kobo Nickel, Calibre), this is not the case.
Not sure if it's a bug or a feature, but I personally don't like it, since you have to go to the next page very often in texts with those headings.

#### Steps to reproduce
Load an epub with those headings and little text in between so that they would fit onto one page.

**Comment by Frenzie** [comment]
There's a style tweak for that already. Style tweaks → Pages → Ignore white page at beginning/end of chapter.

![screenshot_2019-02-08_21-32-30](https://user-images.githubusercontent.com/202757/52504579-2cc51a80-2be9-11e9-83f9-72f4ab315ffa.png)
![screenshot_2019-02-08_21-33-02](https://user-images.githubusercontent.com/202757/52504580-2cc51a80-2be9-11e9-9ef4-d084abc70e0e.png)

**Comment by DanBenHa** [comment]
Thanks. Kind of what I wanted, but not exactly. I don't mind the whitespace after real chapters, but only the ones after within-chapter sections.
Ah real chapter could be defined as separate html files.

**Comment by pazos** [comment]
@DanBenHa: please read https://github.com/koreader/koreader/wiki/Style-tweaks. You can create your own tweaks and apply them to the css of all your documents.

**Comment by Frenzie** [comment]
@DanBenHa Ignore at chapter start will not affect the white page at the end of a chapter, as defined by DocFragment (i.e., the HTML file). That's why there are two separate style tweaks. :-)

**Comment by poire-z** [comment]
> Not sure if it's a bug or a feature

I guess it's a feature, we've had page break on H1 H2 H3 for years in our default [epub.css](https://github.com/koreader/crengine/blob/66166c0d6b823ec870a1a68b55181a5cfeff95e7/cr3gui/data/epub.css#L25-L33).
It never really bothered me, but I had to [disable it for H3](https://github.com/koreader/koreader/blob/011370882f3d6da5c8f59b9c90c006182918cfa2/frontend/ui/wikipedia.lua#L898-L913) in Wikipedia EPUB

> , but I _personally_ don't like it

That's what Style tweaks are for :)
[Create](https://github.com/koreader/koreader/pull/3944#issuecomment-389069259) a file `koreader/styletweaks/no_pb_on_h2_h3.css` with (if you want to keep page break on H1 but not on H2 and H3):
`h2, h3 { page-break-before: auto !important; }`
and you'll have it in Style tweaks>User style tweaks, and you can apply it on the current book, on have it set as default for all of you next books.

**Comment by DanBenHa** [comment]
Thanks a lot you guys! Frenzie's solution already satisfies my needs. It's good to know that there are these style tweaks.
