### ISSUE TITLE
No screen refresh when panning on same page

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#4575]
(Device: Kobo Forma, most recent nightly)

After the recent Kobo screen refresh changes, when scrolling on the same page there is never screen refresh. Among other things, this makes reading CBZ files very hard if the entire page doesn't fit in the viewport. In my opinion the screen should refresh at the end of every panning operation.

Thanks.

**Comment by NiLuJe** [comment]
On which type of content, exactly? Because I can't reproduce on a cbz.

**Comment by NiLuJe** [comment]
Okay, I can somewhat trigger some crappy behavior, but not a missed refresh.

So, what kind of content, and which exact settings?

**Comment by NiLuJe** [comment]
I still can't pan for shit, but at least refreshes are consistent.

**Comment by NiLuJe** [comment]
Landscape, auto-crop, scroll-mode *OFF*, and page turns buttons are somewhat usable. Until...

```
./luajit: frontend/apps/reader/modules/readerview.lua:304: attempt to compare nil with number
stack traceback:
        frontend/apps/reader/modules/readerview.lua:304: in function 'drawPageSurround'
        frontend/apps/reader/modules/readerview.lua:162: in function 'paintTo'
        frontend/ui/widget/container/inputcontainer.lua:81: in function 'paintTo'
        frontend/ui/uimanager.lua:884: in function '_repaint'
        frontend/ui/uimanager.lua:994: in function 'handleInput'
        frontend/ui/uimanager.lua:1066: in function 'run'
        ./reader.lua:210: in main chunk
        [C]: at 0x000139c1
```

Wheee.

That looks familiar to anyone?

**Comment by Frenzie** [comment]
Just from switching a few painting methods?

**Comment by NiLuJe** [comment]
No I'm fairly sure that's unrelated (page overlap quirk, maybe? I was in Gray overlap mode).

**Comment by Frenzie** [comment]
Still not familiar I'm afraid.

**Comment by NiLuJe** [comment]
Not quite sure why I can't pan in a CBZ, though, I end up in `ReaderPaging:onSwipe` instead :?

**Comment by NiLuJe** [comment]
(Couldn't reproduce the above crash, though, so, there's that).

**Comment by poire-z** [comment]
(Not familiar with that either - that's the dark internals of readerpaging/readerview...)
For pan, you need to hold a bit at the end of the gesture. If you don't hold enough - you get "in pan state" early - it's a "swipe west" - hold a bit longer, it's a "pan west".

**Comment by NiLuJe** [comment]
I have no issues panning in ImageViewer, though, which is weird?

**Comment by NiLuJe** [comment]
Okay, holding a bit does get me to `ReaderPaging:onPanRelease`.

Still doesn't actually pan anywhere though :D.

**Comment by NiLuJe** [comment]
On the not so fun facts front: I also usually pretty quickly end up w/ a murdered JIT and the blitting codepath blacklisted like in #4137 :/.

**Comment by poire-z** [comment]
> I have no issues panning in ImageViewer, though, which is weird?

Because in ImageViewer, I made them all work like pan :) because there was no need for distinctive behaviours:
https://github.com/koreader/koreader/blob/e123cc5dca990c2692c2bab0a52a18140797a2a1/frontend/ui/widget/imageviewer.lua#L106-L114
In some other contexts (reader, dictionary...), swipe/hold/pan may have different behaviours.

**Comment by NiLuJe** [comment]
Ha, that explains, that, at least, thanks ;).

No why pan doesn't actually pan is another kettle of fish...

**Comment by poire-z** [comment]
Well, my phone is the only place I do actually try panning (on a colorful Asterix.pdf).
It was always a bit awkward, as most of the times i seem to get back to an early position.
I just realized some days ago while checking again that that's this swipe (when you don't hold for a bit at the end of the swipe for it to become a pan) that's causing this backward thing...
So, if you don't hold enough, while the swipe is happening, it looks like it's panning. But if you release too early, it becomes a swipe and I guess it must align to next or prev page, making it stick on the same page, or something...

I can swipe/pan like that with Zoom>Fit page (bottom), Scroll mode On, Reflow Off.

**Comment by Frenzie** [comment]
I have no trouble panning, but I've never been able to figure out if the various diagonal gestures (other than the biggest one for a screenshot) actually work.
