### ISSUE TITLE
[bug?] Dictionary crashes when looking up a word that cannot be found with fuzzy search turned off

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4579]
* KOReader version: 2019.02.01 nightly
* Device: PW4

#### Issue

koreader seems to hang/crash.  have to restart the device to recover by holding down the power button for 30 seconds.  

#### Steps to reproduce

1) use gnu dictionary and that dictionary alone (though have found issue with other dictionaries)
2) disable fuzzy search
3) long press a word that does not exist in the dictionary.

[note: when fuzzy search is turned on, if it looks like its taking awhile and the word isn't coming up, you can just click elsewhere on the screen and the lookup is canceled], allowing you to recover.

i can try to upload a crash log at some point

**Comment by arooni** [comment]
Error log as requested though I didn't see an explicit error.
https://gist.github.com/arooni/6e1778299cb2203f74a8bd5558ad2922

and attached you can see a shot of trying to look a word up.  nothing happened for 5-7 minutes, despite it being a word i'd assume was in the gnu collaborative dictionary.  i had to restart the kindle

![image](https://user-images.githubusercontent.com/556667/52749335-77aaad80-2fae-11e9-8efd-4134fb9f6583.png)

**Comment by arooni** [comment]
Update: I updated to the latest nightly and could not reproduce.  Closing this.

**Comment by Frenzie** [comment]
Quite odd. It normally shouldn't take more than a few seconds in any case.

**Comment by arooni** [comment]
Re-opening because it seems like downloading the latest nightly (02-13-2019) worked for a moment, but now exhibits the same behavior as described before.

Here are the two most recent launches crash.log (though I don't see any fatal errors): https://gist.github.com/arooni/5b5cfdd5d99bc968e5c63358f831d6eb

In addition, it may be relevant that if I have fuzzy search turned on, I cannot seem to look up any definition, it just hangs for awhile and eventually I cancel it.  I have WordNet and GNU dictionaries installed.

**Comment by poire-z** [comment]
Enable `Gear>Status bar>KOReader memory usage`, and try to see if it happens only when KOReader memory usage reaches a certain point. (Reference https://github.com/koreader/koreader/issues/2239#issuecomment-272188927)
I dont know what kind of book you read and if it grows early, nor how much memory is available on Kindle, and if Kindle has some big amount of it used by some other processes than koreader, so making less of it available. @NiLuJe ?

**Comment by Frenzie** [comment]
Memory usage is a good one to check, but I removed what I wrote due to @poire-z replying while I was writing.

Do you have SSH access? Pinging @NiLuJe because I don't know the Kindle details.

If you run something like this in KOReader's directory then you can potentially get a hint as to where the problem's coming from.
```
./sdcv --data-dir=/where/relevant --exact-search efficiency
```

That being said, dictionary lookup can normally be canceled within the GUI, so that doesn't bode well I suppose.

**Comment by arooni** [comment]
https://gist.github.com/arooni/a610f82c7961459a403dd1060a24938c

> Memory usage is a good one to check, but I removed what I wrote due to @poire-z replying while I was writing.
> 
> Do you have SSH access? Pinging @NiLuJe because I don't know the Kindle details.
> 
> If you run something like this in KOReader's directory then you can potentially get a hint as to where the problem's coming from.
> 
> ```
> ./sdcv --data-dir=/where/relevant --exact-search efficiency
> ```
> That being said, dictionary lookup can normally be canceled within the GUI, so that doesn't bode well I suppose.

https://gist.github.com/arooni/a610f82c7961459a403dd1060a24938c

**Comment by arooni** [comment]
> Enable `Gear>Status bar>KOReader memory usage`, and try to see if it happens only when KOReader memory usage reaches a certain point. (Reference [#2239 (comment)](https://github.com/koreader/koreader/issues/2239#issuecomment-272188927))
> I dont know what kind of book you read and if it grows early, nor how much memory is available on Kindle, and if Kindle has some big amount of it used by some other processes than koreader, so making less of it available. @NiLuJe ?

Memory usage is @ 29 right now.  After overwriting the dictionary I'm able to look things up.  I wish I hadn't though it'd be easier to track down the issue on an intermittant bug like thiiis.

**Comment by Frenzie** [comment]
It's less the size of the document than the number of nodes. But 36 suggests a perfectly average number, which should leave plenty of memory for pretty much anything you like.

Is that sdcv output while you're having trouble in KOReader? Otherwise it's basically just showing the program working normally. :-)

**Comment by arooni** [comment]
Is it measured between 1-100?  

That's the output when everything is working fine yeah (after I overwrote the dictionary).  I guess I should wait to see if this happens again, and then not try to 'fix' it in a way that doesn't enlighten us on the core reason behind it.

**Comment by Frenzie** [comment]
Memory? No, that's 36 MB, presumably out of 512 (minus however much Kindle system services use).

**Comment by Frenzie** [comment]
System statistics, in the hamburger menu on the top right, should also say (here 382 out of… 1648.84? must be some LuaJIT without resorting to tricks limit or something). Also see the last page of that info screen.

![screenshot_2019-02-14_20-47-05](https://user-images.githubusercontent.com/202757/52813286-bcf7d980-3099-11e9-8d4c-3a2c896f077d.png)

**Comment by poire-z** [comment]
On kobo, I start at around 20M and everything is fine up to 350M. But kobo don't use much.
Growing on EPUB should be reasonable; It may grow faster with PDF where some pages rendering are cached in memory, but there's a limit to the cache size. Switching books may also not reclaim some memory, and make it grow again.
It also grows a lot when you do many of dictionary/wikipedia lookup, not because of the lookup itself, but because the UI widget that displays the text do use a lot of memory.

Anyway, just use your kindle, look at the mem from time to time, and just see at how much it was before things went bad.

**Comment by Frenzie** [comment]
To illustrate how deceptive that "free" column is:

```
cat /proc/meminfo
MemTotal:         508740 kB
MemFree:          121040 kB
Buffers:            7444 kB
Cached:           251392 kB
SwapCached:            0 kB
Active:           195768 kB
Inactive:         124904 kB
Active(anon):      61184 kB
Inactive(anon):      680 kB
Active(file):     134584 kB
Inactive(file):   124224 kB
Unevictable:           0 kB
Mlocked:               0 kB
HighTotal:             0 kB
HighFree:              0 kB
LowTotal:         508740 kB
LowFree:          121040 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 8 kB
Writeback:             0 kB
AnonPages:         61860 kB
Mapped:             7808 kB
Shmem:                28 kB
Slab:              31528 kB
SReclaimable:      29508 kB
SUnreclaim:         2020 kB
KernelStack:         512 kB
PageTables:          680 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      254368 kB
Committed_AS:      68196 kB
VmallocTotal:    1376256 kB
VmallocUsed:        8508 kB
VmallocChunk:    1320872 kB
```

Afaik "inactive" is fully available for all intents and purposes. To a reasonable extent, so is cached (which is where previously opened files like the previous book you opened and your various dictionaries live, until they're booted out).

By contrast, the "free" column is completely unoccupied. So I guess the tl;dr there is that the "free memory" as stated doesn't mean all that much.

**Comment by NiLuJe** [comment]
Memory pressure is higher on Kindle, as the system is kept running in the background, unlike on Kobo. And that system is a mix of Java + HTML5, so it tends to need all the RAM it can get its grubby hands on ;).

Kindles also used to ship with limited RAM (compared to other similar devices). I *think* anything recent enough jumped to 512MB, though, so, all of this became less of a concern.
