### ISSUE TITLE
Full-page spreads should respect "Read from right to left"

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#4583]
When reading CBZ files on some Zoom Modes (specifically, "fit content height"), if the page is a spread (a double-sized comic page), half the page will be shown on the viewport. Then, when tapping to go to the next page, the other half of the page will be shown. Thus double-page spreads can be read without having to mess with the zoom options.

However for comics that read right-to-left, the left half is shown before the right half, rather than the other way around. 

There's a "read from right to left" per-file setting. If it could also control how full-page spreads are shown, it would be great.

Thanks!

**Comment by poire-z** [comment]
Probably fixed with #6885.
