### ISSUE TITLE
[Android]: Layout issues on Huawei P20 Pro

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4584]
* KOReader version: current
* Device: Huawei P20 Pro.

Reported by @wangkaibule on [gitter](https://gitter.im/koreader/koreader)

#### Issue

1. Screen aspect ratio is more than 2:1, and KOReader doesn't fill all the space available. (Can't reproduce on the emulator)
2. Errr, KOReader doesn't enter fullscreen until pause/resume is triggered. That is common for all devices with an action bar.

![92fffjr2_o](https://user-images.githubusercontent.com/975883/52664640-d1a56780-2f09-11e9-949e-cbe982ff475f.jpg)

**Comment by Frenzie** [comment]
[Link to report](https://gitter.im/koreader/koreader?at=5c6200f5ef98455ea41cbe17)

> @Frenzie The content of both Koreader UI and book content are incomplete on my mobile phone, sorry I cannot upload any pictures at the moment. Also I have to touch the "paper" icon to activate the menu under the "cog" icon
And I'm afraid I can not find the "scroll mode" option

> http://imgbox.com/92fFfJR2
The first picture shows the content is incomplete in landscape mode and the second picture shows the UI is incomplete in portrait mode
