### ISSUE TITLE
[FR] Do not invert background on keyboard keys on tap

### ISSUE THREAD

**Issue by avsej** [koreader/koreader#4590]
Kindles render keyboard without borders, and draw border on tap. This makes typing visually more pleasant, and reduces flickering. Here is the demonstration of what I'm talking about.

![doc_2019-02-14_16-07-38](https://user-images.githubusercontent.com/7280/52788695-a6319280-3059-11e9-8d80-8b218e517f7b.gif)

Can we have something like this instead of current keyboard UX?

**Comment by Frenzie** [comment]
PS This is an FR for showing the feedback differently, and is therefore not covered by the current "no feedback/flash" options.

**Comment by NiLuJe** [comment]
Yep, no idea if we can cobble something like that out of whatever widgets we're currently using, but I definitely like the idea.

I don't think I have any intention of specifically looking into it any time soon, but I like it ;).

**Comment by Frenzie** [comment]
Implemented in #4776.
