### ISSUE TITLE
During OTA update on Kindle PW4 "Vaugely related. When I ran the update on my Kindle it said "error Koreader failed to update and may not work properly"

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4602]
* KOReader version: 2019.02.16 nightly
* Device: PW4

some discussion in the closed issue of #4599 .

what's weird is that i got the new feature of highlighting one word at a time.

i have also noticed some weirdness (see attached images).  its like images aren't rendering well by default.  i have it set up for 6 pages before full refresh but the book covers and open/history screen/reading progress screens look all funky.  perhaps this is related?  or a known issue on latest nightly?

![image](https://user-images.githubusercontent.com/556667/52906079-bd63b200-320a-11e9-9e5e-8d53e7049378.png)

![image](https://user-images.githubusercontent.com/556667/52906075-b472e080-320a-11e9-8f06-e7b66337131f.png)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

https://gist.github.com/arooni/66f334ce8cc3e1837bc33197f1c1fd57

**Comment by NiLuJe** [comment]
Hmm, nope, definitely not supposed to look like that :D.

If you can catch the exact error message on update, that might jog my memory. I remember writing something like that somewhere, but damned if I remember where exactly...

**Comment by arooni** [comment]
Tried again today.  Update failed again. 

It looks like 

"Update failed :(
Koreader may cease to work properly"

Pretty sure if the update failed smiley face wording.  Not sure about the may cease part.  Will verify again tomorrow.

**Comment by NiLuJe** [comment]
Ah, right, got it, thanks!

That's indeed the unpacking process of an update returning an error, which definitely shouldn't happen.
Do you seven see the tiny progress bar at the bottom of the screen? If you do, does it stop before 100%?

**Comment by arooni** [comment]
I do see the progress bar and I think it goes to 💯 but I can check for sure tomorrow.

**Comment by NiLuJe** [comment]
On the off-chance it matters, on which FW version is that?

**Comment by arooni** [comment]
5.10.2

**Comment by NiLuJe** [comment]
Okay, yeah, confirmed, it's throwing a SIGBUS at the end, I'll look into it...

**Comment by NiLuJe** [comment]
Ooohkay, tar is segfaulting with a strlen on a NULL ptr. o_O.

**Comment by NiLuJe** [comment]
```
#0  gettime (ts=0xbeda3f60) at gettime.c:30
30      gettime.c: No such file or directory.
(gdb) bt full
#0  gettime (ts=0xbeda3f60) at gettime.c:30
No locals.
#1  0x0001b974 in compute_duration () at buffer.c:264
        now = {tv_sec = 0, tv_nsec = 3}
#2  0x0001e34e in close_archive () at buffer.c:1135
No locals.
#3  0x00020710 in read_and (do_something=0x1a945 <extract_archive>) at list.c:304
        status = <optimized out>
        prev_status = <optimized out>
        mtime = {tv_sec = -1, tv_nsec = 421880}
#4  0x00032466 in main (argc=9, argv=0xbeda4134) at tar.c:2761
```

I smell gnulib shenanigans...

**Comment by Frenzie** [comment]
On Kindle's side?

**Comment by NiLuJe** [comment]
Nope, it blows up because it's being truncated during the update.

Which makes sense. No idea why it does NOT blow up everywhere else, though...

**Comment by NiLuJe** [comment]
Unfortunately, the workaround is fairly gnarly: copy the tar binary somewhere else (i.e., /tmp), and run that one.

**Comment by NiLuJe** [comment]
Oh, wait, I know why it's being wonkier than on other platforms: probably a weird side-effects of /mnt/us being a proxy-fs overlaid on top of the real partition via a custom fuse module.

**Comment by NiLuJe** [comment]
And cn't do everything from the real fs, because it's mounted noexec. Yaaaay.

(Because another side-effect is that now, instead of tar blowing up, it's sh with a bogus syntax error because koreader.sh is being overwritten...)

**Comment by arooni** [comment]
So should I just be able to run an OTA update tomorrow ?  Or do I need to download a full Dev build tomorrow as perhaps previous updates weren't completing properly?

**Comment by NiLuJe** [comment]
I'd do a clean install, because I definitely can't reproduce your other image issue ;).

Unless...

**Comment by NiLuJe** [comment]
Yeah, I enabled hardware dithering on the KOA2 & PW4, and, apparently, that doesn't work :D.

I'll double-check I didn't do anything stupid, and will probably disable it as I don't have a device to check what might work better.

**Comment by arooni** [comment]
Well happy I could guinea pig it for you :p.  

So when you say clean build do you mean grab from the build server and overwrite everything that's not in /settings ?  And when are new builds available each day ?

**Comment by NiLuJe** [comment]
There's no settings folder in packages anyway, you can just overwrite the full koreader folder, it shouldn't wiper anything other than the non-persistent defaults.lua ;).

Nightlies finish cooking around ~7:30AM UTC, IIRC.
