### ISSUE TITLE
[FR] Disappearing status bar on android devices (seems system menu is overriding)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4603]
* KOReader version: 2019.02.01 stable
* Device: Fire tablet 10

#### Issue

Seems system menu overrides the app and doesn't go away, preventing users from seeing the status bar, and some parts of the UI such as previous/next page in the file browser/history etc.

see attached image for example:
![image](https://user-images.githubusercontent.com/556667/52906344-60b6c600-320f-11e9-8586-a39a43c30cbf.png)

#### Steps to reproduce

**Comment by pazos** [comment]
@arooni that is hopefully fixed in recent nightlies, try this one: http://build.koreader.rocks/download/nightly/v2019.02-32-g015fb4d_2019-02-16/

If still doesn't work for you I need logs. Please use `adb logcat luajit-launcher:V KOReader:I *:S`

**Comment by arooni** [comment]
Problem is indeed resolved!  I didn't know there were builds for nightlies!  But now I think the error preventing OTA updates on android should be solved so should be able to update via the app.

**Comment by Frenzie** [comment]
Not quite I'm afraid. This whole OTA functionality on Android business might need a rethink (meaning, it might be better to just remove it even though it allows for smaller update downloads).

The thing is, there's a regular KOReader core for all platforms and then there's the unique Android specific wrapper. The OTA update only updates the core part, so a fix in the wrapper could never be OTA-updated using that mechanism. And worse, if the core part update depends on newer functionality in the Android wrapper it will crash completely.

So in the end it's a marvelous achievement, but maybe not the best idea. Perhaps the original idea was to make the wrapper update separately as well when necessary, but I'm not particularly interested in spending my time on implementing something like that and I doubt @pazos is either. What we should be able to implement easily of course is a more traditional update check that simply hands the URL to the latest relevant APK off to the system.

**Comment by pazos** [comment]
> . This whole OTA functionality on Android business might need a rethink (meaning, it might be better to just remove it even though it allows for smaller update downloads).

It should be possible to start the installation of a new apk from KOReader just by starting a new activity with the apk intent. This opens the "default apk installer" and, if you confirm the update, the installer will first shutdown the running version. IMO this is the way to go.

**Comment by Frenzie** [comment]
Sure, same difference. :-)
