### ISSUE TITLE
[FR] For android devices allow a screen timeout for inactivity when "Keep Screen On" is enabled

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4604]
* KOReader version: 2019.02.16 nightly
* Device: fire tablet 10

#### Issue
So I love the keep screen on feature and use it when I'm eating so I can use my bluetooth mouse to advance pages.

But sometimes I forget to turn off the tablet, or the mouse gets bumped and then turns the tablet back on and if the keep screen on is enabled I'll end up draining the battery life out of the tablet.

FR would be to have a user definable timeout time either as a number entry UI (like the read timer) or a slider bar.  I think the read timer would be more flexible with say a sensible default like 10 minutes.

Would also be useful to see something like this on the kindle in case I want to change my screen turn off timeout for some reason.

**Comment by pazos** [comment]
For Android it will be implemented eventually.

The proper way of doing this is with a timeout menu with some values (use system settings/1min/5min/10min/15min/30min/never). Only "never" will setup a wakelock. Other values will modify system settings (like we do on light levels).

The sad thing of developing for android is that writte_settings permission is deprecated, is a special permission (this is a block to build with API23+) and is not guaranteed to work on every device.

The even sad thing of writting system settings on android is that those settings will override current system settings and we need to keep a previous state of system settings to restore them when the application is paused.

Right now we can override light values, the new value is then used by other apps too. This is fine as screen is not as problematic as power. Imagine that you set a timeout of 30 minutes, finish a book, do something else with your device and forget to change that value... You have now a timeout of 30 minutes for all the applications.

**Comment by Frenzie** [comment]
But on normal Androids (and what Google [wants you to do](https://developer.android.com/training/scheduling/wakelock#screen)) you can just dynamically add and clear `WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON` or something, instead of messing about with wakelocks. That's just an ugly workaround for some weirdly broken Android E Ink devices.

**Comment by pazos** [comment]
https://developer.android.com/reference/android/os/PowerManager.html#SCREEN_BRIGHT_WAKE_LOCK has in fact a big warning message which says:

> Most applications should use WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON instead of this type of wake lock, as it will be correctly managed by the platform as the user moves between applications and doesn't require a special permission.

But since we added the permission and integrate wakelocks in activity lifecycle It should behave exactly the same, please correct me if I'm wrong.

**Comment by Frenzie** [comment]
In normal circumstances it should behave the same, yes. But you started with "The proper way of doing this".

**Comment by pazos** [comment]
> In normal circumstances it should behave the same, yes. But you started with "The proper way of doing this".

My english doesn't help :duck: 

I meant: the proper way of doing timeouts is not setting a wakelock during n seconds, but modifying system settings for this activity:

onCreate-> set useSystemDefaults = true;
on frontend device init check if G_custom_timeout and set useSystemDefaults accordly

on resume if useSystemDefaults = false then store actual timeout and set new timeout based on settings
on pause if useSystemDefaults = false then restore saved timeout
on resume if useSystemDefaults and savedTimeout != currentTimeout set custom timeout again.

this way, system settings are applied while KOReader has focus and previous settings are restored when the program loses focus.

probably we want to implement the same for brightness (to restore automatic brightness if it was enabled before changing its value from KOReader)

**Comment by pazos** [comment]
Did a few tests with android settings today. Things are working fine on the emulator and on my two devices.

My idea is to set a custom timeout only applicable to KOReader. In that context I'm working with setTimeout(int) where:

if int == 0 then use system settings (aka don't touch anything).
if int == -1 then set a wakelock (aka no screen timeout)
if int > 0 then set that timeout when KO gains focus and restore the system timeout when KO loses focus.

Of course some devices needWakelocks. In those devices there won't be any menu for the user to choose custom timeouts.

I would go for standard android screen timeouts (without the little ones): 1 minute, 2 minutes, 5 minutes, 10 minutes, 15 minutes and 30 minutes. The other two options will be: use system settings and never(enable wakelocks)

Not sure if this is what @arooni was looking for or if @Frenzie has a better idea to implement this.

**Comment by Frenzie** [comment]
Seems okay, although intuitively I'd just set FLAG_KEEP_SCREEN_ON until the int > 0 time instead of messing with system settings.

Btw, also see the read timer plugin. We already have a little GUI widget for that kind of thing. ;-)

**Comment by pazos** [comment]
> Seems okay, although intuitively I'd just set FLAG_KEEP_SCREEN_ON until the int > 0 time instead of messing with system settings. 

We actually mess with system settings for changing frontlight level (but we don't restore system wide settings on KOReader exit, which can be a pain if you like to keep your fl at auto, since in KO we set the value to manual each time we change the level).

Aaand, FLAG_KEEP_SCREEN_ON *is* a wakelock. In fact I double checked that we're doing the same that FLAG_KEEP_SCREEN_ON does on the shadows.

**Comment by Frenzie** [comment]
> We actually mess with system settings for changing frontlight level

Which I'm against. I'd strip that out stante pede. If you want my (nearly) uncensored opinion, @#$@# this messing about with system settings.

**Comment by pazos** [comment]
But, why?

I mean, right now frontlight permissions work great (ie: you can disable write settings permission and you are still unable to crash KOReader trying to change fl level). The same should apply to screen timeout. If you allowed that function then good, if not you cannot change the option, but that's all.

**Comment by Frenzie** [comment]
Because I find it rather annoying as a user.

But I say this squarely from the perspective of one who might occasionally use KOReader to view a file on their phone. I know this brightness stuff is here for Android ereaders. :-)

**Comment by pazos** [comment]
@arooni: done. It will be available on a couple of days (or tomorrow?). Please use it extensively and report any miss behaviour. It should be safe enough for production.

internally we keep two different timeouts: one for the system and one for KOReader, but externally there is only one setting (you can see/change it from android settings -> display -> screen timeout), so we're toggling both internal states based on changes.

Things are expected to work. If not I know you are very good bug reporter :smile:

**Comment by arooni** [comment]
Wow!!!

That's awesome!  Great job @pazos!!  I love how koreader keeps getting better and better every day!  

I'll try to remember to download a dev version for my android tablet.  

I think I can switch back between stable/dev versions whenever I'd like right?

**Comment by Frenzie** [comment]
Usually, unless there are data format changes.
