### ISSUE TITLE
on wakeup, no full screen repaint when using "Use message as screensaver"

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4624]
* KOReader version: v2019.02-43-g1623cc_2019-09-16
* Device: Kobo Glo HD

#### Issue
After I wake up the kobo glo hd, the screen is blank. The screensaver message that I typed like "Sleeping...." disappears and only that small rectangle where this text was written, the book's text appears. the rest of the surface is still blank as while screensaver was "on". In order to see the book, I have to turn the page twice or invoke the menu from the top or bottom.

#### Steps to reproduce
1. choose "Use message as screensaver";
2. choose "White background behind messages and images";
3. choose "Delay when exiting from screensaver" = Disable;
4. type some tongue twister into Screensaver message;
5. now put the reader to sleep;
6. now wake it up;
7. you will see that the white background is still there, while under the former screensaver text & its border, the text that was behind the plate, will fade in;

#### what helps
1. choose "Delay when exiting screensaver" = 1 second, for "Use message as screensaver";
2. use any other screensaver; "reading statistics" works perfect no matter what "Delay when exiting from screensaver" was set (including "Disable");

**Comment by NiLuJe** [comment]
Should be fixed by #4622 ;).

**Comment by worldexplorer** [comment]
Thank you! this actually might fix my other Kampf with 
Short taps on wakeup are interpreted as long taps (kobo glo hd N437)
https://github.com/koreader/koreader/issues/4431
