### ISSUE TITLE
AppImage fails to start on Fedora 29

### ISSUE THREAD

**Issue by jcomesana** [koreader/koreader#4627]
* KOReader version: koreader-appimage-x86_64-linux-gnu-v2019.02.AppImage
* Device: Fedora 29 x64

I've attached the debug output.
[koreader_error.txt](https://github.com/koreader/koreader/files/2886563/koreader_error.txt)

**Comment by Frenzie** [comment]
Thanks for the report. I'll add an extra print statement so we can catch the actual error next time something like this happens. :-)

```
libXss.so.1: cannot open shared object file: No such file or directory
```

Normally the X11 screen saver extension library is installed, so its absence in Fedora uncovered a hidden dependency.

**Comment by Frenzie** [comment]
Actually since it doesn't really do anything a dummy should suffice, cf. https://github.com/AppImage/pkg2appimage/issues/127

Fedora also seems to do without `libbsd.so.0`.

I'll have to take a more extensive look later.

**Comment by Frenzie** [comment]
The libXss.so.1 dummy combined with something like this works:

```diff
diff --git a/Makefile b/Makefile
index 613b61ba..61293b1f 100644
--- a/Makefile
+++ b/Makefile
@@ -319,6 +319,9 @@ appimageupdate: all
        # required for our stock Ubuntu SDL even though we don't use sound
        # the readlink is a half-hearted attempt at being generic; the echo libsndio.so.6.1 is specific to the nightly builds
        ln -sf /usr/lib/x86_64-linux-gnu/$(shell readlink /usr/lib/x86_64-linux-gnu/libsndio.so || echo libsndio.so.6.1) $(INSTALL_DIR)/koreader/libs/
+       ln -sf /lib/x86_64-linux-gnu/libbsd.so.0 $(INSTALL_DIR)/koreader/libs/
 ifeq ("$(wildcard $(APPIMAGETOOL))","")
        # download appimagetool
        wget "$(APPIMAGETOOL_URL)"
```

![screenshot from 2019-02-21 15-20-45](https://user-images.githubusercontent.com/202757/53175478-5704d800-35ec-11e9-9b0d-305b09ac4625.png)

**Comment by Frenzie** [comment]
@jcomesana This will be fixed in tomorrow's nightly, which will show up [here](http://build.koreader.rocks/download/nightly/).

**Comment by jcomesana** [comment]
I can confirm that the nightly build starts on Fedora 29 and on Debian Testing. Thanks! :+1:
