### ISSUE TITLE
Statistics in metadata.epub.lua

### ISSUE THREAD

**Issue by embryo10** [koreader/koreader#4642]
Perhaps there's something wrong in my configuration (I still use koreader 2018.11.1), but since I also checked a test file that another user send me for debugging (for KoHighlights), it seems that there is no updating of the `"total_time_in_sec"` key in the `metadata.epub.lua` file.
Its always 0.
The book statistics in KoReader shows normal values.
I can understand that these are from a plugin that stores its data elsewhere, but is the `"total_time_in_sec"` key obsolete?

Also, is the `["summary"]["status"]` key gone too?
I must lost a lot of discussion here ;o)
I'll try to keep up...

**Comment by poire-z** [comment]
I think some of this stuff has been removed from the book docsetting metadata.lua and moved to be stored in the SQLite db of the statistics plugin v2 https://github.com/koreader/koreader/pull/2893 (september 2017).
Haven't looked at the details, but I think footer and book status widget are fed with the info they need by this statistics plugin, ex https://github.com/koreader/koreader/pull/3218

**Comment by robert00s** [comment]
@poire-z Exactly :)
Footer, book status need plugin statistics to show some elements.
https://github.com/koreader/koreader/blob/b1215812cb99a1e9e8cbb2ce99da94eca12a3324/plugins/statistics.koplugin/main.lua#L101-L126

The plugin uses a database to store data.

**Comment by robert00s** [comment]
I'm closing this issue - nothing to add.
