### ISSUE TITLE
TouchMenu doesn't have a switchItemTable() method

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4651]
* KOReader version: d090f3e
* Device: all

#### Issue
Unless I'm overlooking it, there doesn't seem to be a reasonably nice non-hackish way of adding or removing items from a TouchMenu instance.

**Comment by poire-z** [comment]
I went the hackish way in https://github.com/koreader/koreader/blob/master/plugins/texteditor.koplugin/main.lua

**Comment by poire-z** [comment]
Dunno if we added it, if we still need it - but we have done without it :) so closing.
