### ISSUE TITLE
Left button's background color is black instead of white

### ISSUE THREAD

**Issue by mirogika** [koreader/koreader#4653]
* KOReader version: koreader-android-arm-linux-androideabi-v2019.01.1.apk
* Device: Kindle Fire HD 8 (2016)

#### Issue
The background color of the left button of several windows is black.
Here are some screeenshots:
![reader_2019-feb-24_133620](https://user-images.githubusercontent.com/8546614/53299794-29b06800-3840-11e9-9dd2-41dafc2ecde0.png)

![reader_2019-feb-24_132849](https://user-images.githubusercontent.com/8546614/53299799-c6263a80-383f-11e9-9cd5-c0f755c306c7.png)

**Comment by Frenzie** [comment]
It indicates keyboard/keypad focus.

https://github.com/koreader/koreader/blob/91b83c5176ea8238bc121b98e4588d8f67c437d7/frontend/device/android/device.lua#L15

@pazos @poire-z Any thoughts?

**Comment by poire-z** [comment]
I only see in on the emulator, not on my kobo, not on my Android phone.
It's a bit ugly, I rarely use it on the emulator, but I sometimes do and I find it useful.
May be the focus could only be shown on the first key press?

**Comment by mirogika** [comment]
@Frenzie: by changing hasKeys = yes to hasKeys = no, the problem is solved. 
Thanks 👍

**Comment by NiLuJe** [comment]
I don't recall if 01.1 was affected, but I fixed something similar on e-ink recently.

**Comment by NiLuJe** [comment]
I don't recall if the emulator was affected, though.

**Comment by NiLuJe** [comment]
(to be fair, I broke it first, then I fixed it :D)

**Comment by Frenzie** [comment]
When did you break (and fix) it? The OP lists v2019.01.1.

**Comment by NiLuJe** [comment]
I don't recall exactly, but that should be around the time focus manager
was last touched ;).

**Comment by pazos** [comment]
I can't reproduce in any of my devices/emulators.

Not sure what happens on android if `hasKeys=no`. I think home/back/media keys will still work. Anyways we can blacklist certain android devices but no please...
