### ISSUE TITLE
Question/poll/opinion: double-swipe natural instinct

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#4659]
Pinging @Frenzie @NiLuJe @pazos @houqp @robert00s @AlanSP1 @KenMaltby @cramoisi @gerhaher @ptrm @ersi-dnd @Biep @Galunid @a-kohout @avsej (names i've met lately in issues, others please feel welcome!) for some little experimentation.

Please don't read anything more than this issue for now - think about it, make some gesture on your devices, and then only read the other multiswipe PR and discussions if you feel like it.

I'm trying to see what's people natural mindset related to swipes and double swipes.

Let's say: if we were to use a **single swipe** to bring the Skim widget (that we can do currently with long press on the footer), which would it be between  `↥` (finger going up on the screen) and `↧` (finger going down) ?

I guess (I hope) we would all agree it's `↥`  (finger up, swipe north), making the footer little progress bar rise up into a big one in the middle of the screen (like we do on Android to bring up the hidden bottom menu bar into view).
If you don't agree :) well, let's say you do for the next step in that experimentation :)

Now, my real question I want your naive answer (and less naive after you have drawn it a few times on your device screen):
Let's say single swipe is not available, and we have to choose **exclusively** between **these double swipes**:
`↥ ↧` or `↧ ↥` 
for that same action of bringing the Skim widget up into view.

So, people, what would you most naturally do (and if in doubt, what would a few seconds of thinking would led you to do) **on your device** ?

**A**) `↥ ↧` (finger going up, then down)
**B**) `↧ ↥` (finger going down, then up)

----
Please don't read [this](https://github.com/koreader/koreader/pull/4657#issuecomment-466810264) before having an answer to this question please - but giving the link so people can then see how I'm puzzled...

**Comment by KenMaltby** [comment]
I don't think that there is an intuitive/natural precedent for implementing these gestures.  It seems new enough and each unique enough, that a rule for this would be difficult to conceive or follow.  Perhaps keeping the Android gestures as a general reference, makes sense but I don't know how universal they would actually be.

**Comment by Frenzie** [comment]
Neither, but B.

**Comment by Frenzie** [comment]
Because your method of swiping is counterintuitive. It's like making a checkmark with a bigger first stroke. ;-)

**Comment by Galunid** [comment]
At first I was leaning towards A(probably because on Kindle single swipe up brings up something like skim widget), but after drawing the gestures a few times on my device, I preferred B. It just feels more natural.

**Comment by Biep** [comment]
Neither feels natural, but given your preface, I'd go for A: calling up the skim, and skimming itself means going forward = downward.  Pointing the way, as it were.
Now B is slightly easier to draw, but I presume there will eventually be another function that will be assigned the other gesture, so I am discounting that.

**Comment by Frenzie** [comment]
I don't think the vast majority of these gestures can be particularly intuitive. We can, however, strive for some degree of internal logic and consistency. For example, upward gestures should generally open fullscreen widgets (e.g., Bookmarks, TOC, History) while downward gestures should open a dialog (e.g. skim, frontlight, search dictionary). Or vice versa.

@Biep Eventually meaning within about a week. For customization, just go to Device → Gesture manager. (The location may change prior to release.)

**Comment by viksok** [comment]
I like the way Android expands the top bar with double swipe down.
So I'd like to choose ↑↑. But if that's not the case, then I'd prefer A.

**Comment by NiLuJe** [comment]
I'm away right now, so, to be continued on my end, as I haven't had a
chance to play with this ;).

**Comment by Frenzie** [comment]
@NiLuJe I'll merge #4660 later today so there'll be a proper set of defaults to go on. ;-)

**Comment by poire-z** [comment]
> I don't think that there is an intuitive/natural precedent

Yes, it's new (to most), but some people may have a past with these kind of forward/reverse double swipe gesture, and are able to say one is intuitive and the other not. Personally, I'm not able to :)

> Because your method of swiping is counterintuitive

I don't (yet) have a _method of swiping_. But i'm eager to adopt one and stick with it and get it as a habit :) (including yours!). Hence this post.

> But I surely hope that things like that will be adaptable to personal taste.

They will be, we're just thiking about defaults.

> We can, however, strive for some degree of internal logic and consistency

100% agreed, and that's the aim of this post. Picking defaults that would feel natural to people - and that we can explain some logic of them to the people who would not feel them natural. So their mind can take over their nature :) But nature first if we can, then logic.
So we don't have to learn what we could feel as random choices one person made - but we can learn and remember a little quick logical flow so that, with it, we can find out what's the logical gesture for the action we want to do.
And my concern here is just about actions that would naturally map to a single swipe into a well agreed direction - and that we would need to map into a 2-directions (opposite) swipe.
Following up with 2 more and similar questions.

Thanks for your answers up to now!

**Comment by poire-z** [comment]
Two more experimentations:

We can currently bring down the top menu with a single swipe south `↧` (inspired by Android too - some people prefer tap, that's ok, they can disable this swipe).
If this single swipe south `↧` was not available, and you were to choose **exclusively** between **these double swipes** for that same action of bringing the top menu into view **on your device**:

**A2**) `↧ ↥` (finger going down, then up)
**B2**) `↥ ↧` (finger going up, then down)

Now, 3rd question:
We can currently swipe left or right to change page. `↦` goes back one page, `↤` goes forward one page (when reading this line and seeing the arrows directions, it may look odd, but we're dragging the current page out - I guess it feels natural to everybody - if not, let's pretend it does :).
With the option `Links> Swipe to go back`, one can use `↦` to go back to the previous location (after having jumped and followed a link to a footnote for example). It currently may conflict with "`↦` goes back one page", and one take precedence over the other if need be (this will stay, no worry).
Let's say we want to avoid this conflict, and add a 2 swipe gesture, and you were to choose **exclusively** between **these double swipes** for that same action of going back from the footnote page after you followed a link:

**A3**) `↦ ↤` (finger going right, then left)
**B3**) `↤ ↦` (finger going left, then right)

I would hope people willing to try this would settle on a coherent set of these choices, either A+A2+A3, or B+B2+B3 :)

Note that you can experiment that with the current nightly, Gear> Device> Gesture manager).
Thanks for playing :)

**Comment by cramoisi** [comment]
@poire-z since I don't have a tablet/ipad/smartphone, I  don't swipe but on my Kobo. This said, I think I would go with down-up (for your first question)

**Comment by Biep** [comment]
Beautiful set of options for multisweep!
And we can choose from a 3-page set of actions.  Which makes me think: would there be interest in having two-column menus?  To get more lines on fewer pages?
And (old question): what does "Short diagonal sweep" mean?  NE->SW?  SE->NW?  NW->SE?  SW->NE?
Finally - on the 3-page action menu, it would be nice if we could see which swipe(s) have already been assigned to those actions.  So just as the swipe menu shows the associated actions in parentheses, likewise the actions could show the (0, 1, or more) associated sweeps.

**Comment by Frenzie** [comment]
> And (old question): what does "Short diagonal sweep" mean? NE->SW? SE->NW? NW->SE? SW->NE?

All of them.

**Comment by poire-z** [comment]
(Please @Biep , don't disrupt this issue from my original question, or the answers will be hard to find :) There are much to talk about the multiswipe gestures but can we keep that in some other existing Gesture manager issues :) Thanks.)

**Comment by Biep** [comment]
OK, I'll stay on-topic.
B2 - "go getting" the menu, then dragging it out
B3 - the same, and it also feels like an arrowhead pointing back: <

So my answers are A, B2, B3.  Sorry for the inconsistency.

**Comment by Frenzie** [comment]
Logically speaking B, B2, B3. But in reality probably B, A2, B3. `Down, up` is simply the better gesture,

1) and 2) are arbitrary (because there's no need to think of them as top/bottom menu), which doesn't apply to B3.

Anyway, the traditional gestures for rewind/fast forward are `down, left` and `right, up` respectively.

**Comment by ersi-dnd** [comment]
My regretfully denunciative two cents: It is always counterintuitive to hardcode a gesture, regardless what the gesture is, to do just one thing. It is best to make a given gesture configurable to an array of functions as wide as possible, so that the user can set up the swipes and taps so that they follow his intuition. Will this be a milestone at some point?

**Comment by AlanSP1** [comment]
B, B2, A3

But, that being said, this is maybe too soon to tell, with time I could learn to use (or learn not to use... :D) any of them, depending how much I would use them.

Also, to bit expand on subject, maybe also logical would be if we could have options to hold as some kind addition for swipes, like swiping from down (variant of A) and then holding. For menu would be swiping from up and then holding, etc.

**Comment by Frenzie** [comment]
@ersi-dnd These are not hard-coded.

**Comment by ersi-dnd** [comment]
@Frenzie Good to know. Unfortunately, this does not help me much when I do not see configuration options. I'm afraid my two cents are not worth even one.

Okay, here is something straight on the topic. My intuition tells me that when I swipe once and nothing happens, then I would swipe again to make something happen. 

If I know that a swipe should do a thing, and I do it and nothing happens, then I would execute the exact same swipe yet again.

Given the placement of the footer at the bottom edge of the screen, I would be inclined to swipe up, because I am used to swiping down on Android statusbar given its placement at the top edge. So, experimenting with swipes to make things happen at the footer, I would pretty soon end up trying a double swipe up, I guess, after a tap, double tap, and a single swipe up.

**Comment by Frenzie** [comment]
@ersi-dnd Perhaps we're talking past each other. Regular single swipes currently have a limited level of configurability. Taking more of that to the gesture manager is definitely a long-term goal. But I've added a new type of swipes that I called multiswipes, quite possibly well known to Opera users like yourself, which are bound to actions exclusively through the gesture manager. Thanks to @poire-z's testing they're ready to go.

Here are some pieces of the info graphic I'm preparing for the March release (some first draft, some more finished):
<img src=https://user-images.githubusercontent.com/202757/53368803-fbb74a80-3949-11e9-9a85-9a9a94e6040f.png width=40%><img src=https://user-images.githubusercontent.com/202757/53369108-b9dad400-394a-11e9-84f8-52fd9110a9b5.png width=40%>
<img src=https://user-images.githubusercontent.com/202757/53369734-24404400-394c-11e9-831b-3d48846a1754.png width=30%>  <img src=https://user-images.githubusercontent.com/202757/53369735-24404400-394c-11e9-8295-a2ec22c3f49f.png width=40%>

We're still working on finishing up the default set of multiswipes, both in adding more actions (e.g., the frontlight dialog is still coming; it's just a simple event I believe) and actually binding them to default gestures. 

> Given the placement of the footer at the bottom edge of the screen, I would be inclined to swipe up, because I am used to swiping down on Android statusbar given its placement at the top edge. So, experimenting with swipes to make things happen at the footer, I would pretty soon end up trying a double swipe up, I guess, after a tap, double tap, and a single swipe up.

I've disabled tap to show menu and only use swipes. But this could probably also be added as an action. Don't both swipe and tap work by default?

**Comment by pazos** [comment]
I had no idea. After thinking a bit I now have even less idea. But I'm not the target audience since I won't use multiswipes. But hey, they are pretty cool. Thanks to @Frenzie and @poire-z for their work 👍

**Comment by ersi-dnd** [comment]
@Frenzie The idea is great. Perhaps I will participate in testing, if I can make up my mind on which device I would do the testing. However, I think that there is a bit of a difference between multiswipe and a gesture. A multiswipe sounds like swipe multiple times (lifting the finger from the screen in between swipes), whereas a gesture is done by means of continuous contact just as depicted in your graphic.

I have found myself thinking occasionally that it would be nice to e.g. draw a circle on the screen and something would happen, for example previous/next file in history/folder would open up. Of course, to be truly useful, gestures should be remappable to pretty much any arbitrary action at will.

**Comment by ptrm** [comment]
I did not manage to read thriugh the discussion, but since I have been summoned, I go for *B* ;) – it's generally easier for me to start gestures downwards or sideways.

**Comment by poire-z** [comment]
OK, thanks for all your answers.
So there seems to be a majority of B), which goes with what @Frenzie has currently set as default gestures, ie:
https://github.com/koreader/koreader/blob/163853afdf5f2183f4b0cbb81a51fdc70f34c5b6/frontend/apps/reader/modules/readergesture.lua#L96-L97

And the way some of you described their mind flow fit how I thought about A and B in https://github.com/koreader/koreader/pull/4657#issuecomment-466810264. In two swipe gestures:
with **A** the first swipe is the intention, the second swipe some kind of release
with **B** the first swipe is just taking some room to make the 2nd, and the second swipe the intention
(as @Biep described B: _"go getting" the menu, then dragging it out_)

I would have been more inclined to defend another set of gestures if there would have been more of A naive/natural minds :)

Anyway, sharing how I thought about these double swipes - might appeal to some users.

I initially went with [setting up gestures in the B spirit](https://github.com/koreader/koreader/pull/4623#issuecomment-466748426), but after a few hours, I [thought A felt better,](https://github.com/koreader/koreader/pull/4623#issuecomment-466779463) may be just because it allowed for easier remembering of gestures.

From our discussions @Frenzie, I think  you are used to _drawing_ gestures, in browsers (so, with a mouse, a trackpad), so, for such minds, a gesture is mostly any drawing, abstract or not (your knob drawing), or meaning something with directions.
On KOReader, with the current swipe gestures, I never think of drawings. I don't draw. I grab, drag, drag out: I do physical things to the device/software UI elements: I grab and drag the top menu in, I drag the current page out.

I think I need to have that feeling with multiswipes too.
So, getting used to do ↦ to go _back_, and having to do first ↤ and then ↦ to go _back_ to previous localtion feels a bit awkward. And possibly ↧ and then ↦ to go _back_ 10 pages would too.
(I really _can't draw_ a gesture containing ↤ to go back just because it's a back arrow... :)

I think the A mindset allows for easier remembering or guessing, kindof "think as you draw".
All _back_ multiswipe would start with the usual ↦, and then you would decide what next:
↦ standalone: go back one page
↦ ↤ go back to previous location
↦ ↥ go back 10 pages
↦ ↧ go back to previous chapter (or go back to previous book).

↤ same reasoning with a first left swipe to do these things forward.

An initial ↧ would grab the top menu and do something to/from it, ie:
↧  bring down top menu
↧ ↥ (bring down and release) would bring History (possibly the most useful item we access from top menu).
↧ ↦ TOC (also often accessed from top menu)
↧ ↤ Bookmarks (also often accessed from top menu)

An initial ↥ would grab the footer and do something to/from it
↥ (not implemented, used for panning, can conflict with swipe)
↥ ↧ (bring up and release) bring up the Skim to widget
↥ ↤ would do something else from the footer or stuff from bottom, frontlight widget may be
↥ ↦ likewise - or may be prev/next chapter, as we see chapter marks in the footer

To be honest, I haven't really played with this set of gestures since I asked this question, so to not get too used to that. So, I don't even know if they are practical :)
Just wanted to share the reason why I asked this question.

(That thinking could be applied too with mindset B, but it feels less natural to guess/remember:
↦ standalone: go back one page
↤ ↦ go back to previous location
↥ ↦ go back 10 pages
↧ ↦ go back to previous chapter (or go back to previous book).)

**Comment by Frenzie** [comment]
> with **A** the first swipe is the intention, the second swipe some kind of release
> with **B** the first swipe is just taking some room to make the 2nd, and the second swipe the intention

This false dichotomy could be something I need to address, or do my drawings do the trick? You should generally think of a gesture as a whole, not as a single-swipe intent with baggage. Ideally the complete gesture references an established symbolic intent, but even that is limited by necessity.

Perhaps `⌝` will become symbolic for bookmarks among KOReader users (NB in this particular case the top-right corner is self-referential) but there's little if any pre-established iconic language to draw from.

**Comment by Frenzie** [comment]
@ersi-dnd I'd say a multiswipe is a swipe consisting of multiple constituent components, which isn't the same thing as multiple distinct swipes.

But it's true that "gestures" is a more straightforward name. The naming problem here refers to the distinction between simple swipes or gestures, which consist of one stroke, and complex swipes or gestures, which consist of multiple strokes.

Hence the name. Multiswipe is short for multiswipe gesture. I think it's clearer than something like `complex gesture` or `advanced gesture`.

**Comment by ersi-dnd** [comment]
@Frenzie 
> 
This false dichotomy could be something I need to address

The false dichotomy may have arisen because people are indeed under the impression of multiple swipes, something like when you are in a fullscreen app on Android and you swipe down from the upper edge (first swipe) and the statusbar becomes visible and the you swipe a second time the same way and the statusbar expands. Perhaps poire-z has the same in mind for Koreader's statusbar.

**Comment by poire-z** [comment]
> This false dichotomy could be something I need to address, or do my drawings do the trick?

I really can't answer. May be we'll get feedback, may be people will just set their own to their liking and we'll never know.

> You should generally think of a gesture as a whole, not as a single-swipe intent with baggage. 

But I don't want to :) There's no reason for "should", except the historical fact (before you brought gestures to KOReader :) - ok, they probably already existed on Android) that "gestures" were drawn on/with some peripheral, far from where the action is happening.
Or we're just different minds. You're with Plato and his theory of forms and idealistic figures, while I'm a dirty materialist :)
So, I'm ok with taking your path for default gestures - but I really can't ack or nack you symbolic suggestions.
(Been using my above suggested mappings for a few hours - and they were already too many for my real usage - I may end up keeping only 6 and disabling all others).

> Perhaps ⌝ will become symbolic for bookmarks among KOReader users (NB in this particular case the top-right corner is self-referential)

Even this one is alien for my mind. The bookmark icon is a page dog-eared at top right. The obvious gesture for me would be a diagonal south-west single swipe to actually take the page corner and bring it to the center to physically make a dog ear :) (but I don't need that, no need for diagonal multiswipes, the current tap is fine :)

> Perhaps poire-z has the same in mind for Koreader's statusbar.

I don't think so. I'm too lazy to have to get my finger up from the screen and do a 2nd touch/swipe :) I really like these continuous swipes, and they currently work very well, you can even draw quarter or half-circles, and it maps to the nearest squared one defined.

**Comment by Biep** [comment]
> Perhaps `⌝` will become symbolic for bookmarks among KOReader users (NB in this particular case the top-right corner is self-referential) but there's little if any pre-established iconic language to draw from.

You mentioned knob-turning.
In my B3 answer I mentioned it looked like a back arrow: < (of course the lines are supposed to be horizontal, and overlap, but still the gesture _feels_ like drawing an arrow pointing back).
I think that idea could be the basis for some more iconic language.
And I guess for me the most natural gesture for bookmarking would be a short SW swipe starting in the NE corner - and the inverse for unmarking, even though the one gesture could technically be a toggle.

**Comment by Frenzie** [comment]
> I think that idea could be the basis for some more iconic language

…but that *is* the language. ;-) Back to previous location is very intentionally a back arrow.

**Comment by Biep** [comment]
Are there any plans for multifinger gestures?  Swiping one way with two fingers is an easier gesture than swiping back and forth.  And more fingers would be a natural way to idicate "heavier" or "more intense" action: whereas swiping EW would return to the previous page, two-finger swiping EW would return to the origin of the last jump (and maybe three fingers would jump back to the previous book, for people reading a theory book with an associated workbook).

**Comment by Frenzie** [comment]
There are already multifinger gestures. I don't know what they are precisely, see the wiki. I think they have something to do with the frontlight.

**Comment by poire-z** [comment]
It's supported on devices that support multi touch, like my GloHD. See https://github.com/koreader/koreader/pull/4423#issuecomment-462170129 for some gestures supported and their associated hardcoded action.
I used to use 2-fingers right to open TOC and left to open Bookmarks. But I find single-finger multi-swipes a LOT easier to do than 2-fingers one (and less buggy/sensitive to timing on fingers synchronisation.)

**Comment by Frenzie** [comment]
Since support of those multifinger swipes is quite sparse, it shouldn't be much effort to integrate the existing ones into the gesture manager.

I might have a look for the 2019.04 release, although I'm much more interested in various issues that came to my attention due to multiswipe. For example, outside-document links aren't followed by the nearest link gesture, which I find disorienting. Also I'd like to have the option to add such links to Wallabag. (Pinging @y-muller for loud hinting purposes.) And of course they were never implemented for DjVu or PDF.

The effort to make two-finger multiswipes work should presumably also be fairly minimal since it's all been thought out, coded and tested already, although it might require some refactoring to do it elegantly. (NB I'm not particularly interested in spending time on that.)

> I used to use 2-fingers right to open TOC and left to open Bookmarks.

Oh, I never knew. That works quite nicely, albeit not nearly as nicely as multiswipes.

**Comment by poire-z** [comment]
> For example, outside-document links aren't followed by the nearest link gesture, which I find disorienting.

This was intentional of my part, see:
https://github.com/koreader/koreader/blob/7c2df53808e0eb23d442e98b55376adc01f2f420/frontend/apps/reader/modules/readerlink.lua#L735-L742
So, if you want to change it, make it optional/toggable.

And what is there to _follow_? :) we can only somehow follow Wikipedia article links - and in Wikipedia pages, there are so many, mixed with tiny footnotes links that somehow matters more with the idea of "following" in the book content, meaning navigating to another page of the book. That's my reasoning anyway.
If you're stuck because you disabled Tap on link (because now that you have gestures to follow link which are easier), you can still get the link with a Hold to follow it (a bit more tedious, but following Wikipedia links should be less frequent than footnotes).
Personally, I patched the bottom of ReaderHighlight:onHoldRelease() with this (we discussed it previously when you added support for having the link there):
```lua
     elseif self.selected_word then
+        -- if hold on a link, follow link rather than dict lookup
+        if self.selected_link then
+            self:clear()
+            self.ui.link:onGotoLink(self.selected_link)
+            self.selected_word = nil
+            self.selected_link = nil
+            return true
+        end
         self:lookup(self.selected_word, self.selected_link)
         self.selected_word = nil
     end
```

**Comment by Frenzie** [comment]
> And what is there to follow? :)

If you take the word "follow" literally then I suppose I don't want "follow" at all. I want the activate link action, whatever that may be.

Tapping on links is hard, although I'd actually never really noticed before. Even when you're seemingly tapping right on them, you often accidentally turn the page. Gesturing near them is easy, and starting your gesture on them in crowded environments still always works perfectly.

Anyway, for the moment it's just an observation. :-P

**Comment by Biep** [comment]
> Tapping on links is hard, although I'd actually never really noticed before. Even when you're seemingly tapping right on them, you often accidentally turn the page.

I often have the opposite problem.  Footnotes and literature references insinuate themselves just there where I happen to tap to turn the page, and then I wonder why I am where I am.  I must try out those gestures.

**Comment by Frenzie** [comment]
Btw @poire-z are you interested in looking at two-finger swipes? I wouldn't mind doing it, but testing it is a real pain since I can only do it on a mostly broken real Android device.

(Unless @pazos knows of a sufficiently simple way to do it in the Android emulator. There seems to be some combination of Ctrl/Shift/click that triggers something but I can't quite put my finger on it. Although… I suppose I could also hack our own emulator to do something like that.)

**Comment by poire-z** [comment]
> are you interested in looking at two-finger swipes? 

Not really, sorry.
1) because I wouldn't be using them
2) because even if available, I don't think people would use them given how less reliable 2-fingers swipe can be - unlike multisingleswipes
3) because @Biep asks about multifingers gestures, while saying _I must try out those gestures_ - so I'm sure he'll like them once he had tred them, and he will forget about multifingers :)

**Comment by Frenzie** [comment]
Alright, I'll put it in the I might look into it jar. (Just migrating those few to gesman, that is.)

**Comment by Frenzie** [comment]
PS For @Biep that won't really work given that PDF currently doesn't yet support follow link.

**Comment by poire-z** [comment]
> that PDF currently doesn't yet support follow link.

It does. Check with paper.pdf, which has internal links to the bibliography, so swiping near "Author (1995)" should have you jumped to near the end of the book. But I guess that's just very rarely available in most PDFs.

**Comment by Frenzie** [comment]
Perhaps I confounded it with the external links thing. Indeed it seems to be working. Of course I wasn't talking about facsimile PDFs without links. ;-)

**Comment by ersi-dnd** [comment]
Today I downloaded the new version with multiswipes&gestures manager. Good job, worthy of congratulations for starters. A few instant comments.

Commendably, the swipes seem to work not just when viewing a book, but also when in history and file browser. However, you have totally missed the opportunity for contextual functionality. E.g. a gesture takes you from a book view to the file browser, but in the file browser *the very same gesture* would take you back to the book view. 

(I personally even earlier mused like this: What if the down swipe, which gets rid of whole-page dialogs and history view and returns to the book and whose general meaning thus seems to be "take me back to the book", would also have a function in the book view, e.g. "go to file browser"?)

Among the available set of functions attributable to multiswipe gestures, you have included book status, but forgotten the much better book information. 

These multiswipe gestures seem to be the best option for Kobo devices that lack multitouch. Otherwise, such as on Pocketbooks, I guess I would much prefer configurable multitouch gestures.

**Comment by Biep** [comment]
> But I guess that's just very rarely available in most PDFs.

It is in most PDFs that are uploaded to Academia.edu.  And those tend to contain lots of references, so when tapping randomly, chances are that one hits a reference link.

**Comment by Biep** [comment]
> he will forget about multifingers :)

Difficult.  I was born with them.

**Comment by Frenzie** [comment]
There are probably links in most PDFs that aren't scanned facsimiles period.

But in between the likes of DBNL and Gallica there's a great quantity of terrific PDF facsimiles to be found, that are hard to impossible to obtain or at least read on paper, which for me is the primary use case of an ereader period.

(Not Archive.org. There you go for DjVu instead. But same principle.)

**Comment by ersi-dnd** [comment]
@Frenzie 
> Tapping on links is hard

Even longpress is hard? A tap vs longpress could easily make a sensible distinction between a regular page turn and aiming at a link.

**Comment by Frenzie** [comment]
Long-pressing is extremely hard.

> And instead of elaborating a multiswipe system, it would have been much greater to introduce a multifinger system. But not many Kobos have multitouch, I have heard..

Two-finger swipes have been supported for roughly 6 years. There's nothing to introduce…

**Comment by ersi-dnd** [comment]
I meant of course a configuration manager/remapper for multifinger swipes. This has not been introduced.

**Comment by Frenzie** [comment]
If I had, you'd be looking at a maximum of about six actions. ;-)
