### ISSUE TITLE
Panning rate default

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4667]
* KOReader version: 2019.2
* Device: Android/AppImage

#### Issue
Smaller panning rate seems to be enabled by default. Instead, it should depend on Device:hasEinkScreen(). Cf. #4470.

https://github.com/koreader/koreader/blob/5495c5d108eae003cf9d36426d59448b79758d62/frontend/device/generic/device.lua#L109-L110

@pazos Also, if hasEinkScreen then hasColorScreen should be no for some memory/performance improvement.

**Comment by pazos** [comment]
> if hasEinkScreen then hasColorScreen should be no for some memory/performance improvement.

For android & sdl targets sure. There is the pocketbook colourLux which is supported and has both EinkScreen and ColorScreen.

**Comment by Frenzie** [comment]
That's what device-specific overrides are for, but it's just a "btw" in any case.

**Comment by pazos** [comment]
Cool. For me this makes sense:

emulator has a switch to toggle panning rate.
on eink devices set low_pan_rate (on the future make the rate GUI editable)
on other devices do not provide a switch to toggle panning rate and do not set low_pan_rate.

**Comment by Frenzie** [comment]
I'm not completely sure about that not providing a switch part. Low pan rate is primarily about screen drawing performance, but there's also blitting performance to take into consideration. (Of course _2_ is a bit extremely low.)

**Comment by mergen3107** [comment]
Guys, can you please explain what does `Use smaller panning rate` mean in general, and specifically for eInk screens?

**Comment by mergen3107** [comment]
I found the answer on [MR](https://www.mobileread.com/forums/showthread.php?t=320937) :D 
Credits to @pazos:


> It sets a lower "refreshes per second" when scrolling (2 vs 30). It is enabled by default on eink devices.
> 
> Most people will want to leave it enabled. Some android users with modern Onyx/Likebook devices and A2 enabled can disable it without pain.
