### ISSUE TITLE
[FR] [Android] Support bluetooth keyboard/mouse

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4671]
**Mouse:** I can click and highlight, but it'd be nice if I could use the scroll wheel on my bluetooth mouse to go back and forth between pages. Also would be nice if the middle button/right button were supported.  The middle button could pull up bookmarks/index/ or maybe be user definable.

**Keyboard:** It would be nice to add support for the hardware keyboard where I can take notes much faster

**Comment by pazos** [comment]
We do not support any special gadget on android. Bluetooth mouse support is just something that android provides (ie: mouse as a single point&click device).

What you requested is doable on api14+ but requires effort, time and a person willing to do the job.

**Comment by arooni** [comment]
Just bumping my own feature.  For anyone who likes to take and edit extensive notes on their Android tablet support of a Bluetooth keyboard would be amazing amazing amazing

**Comment by arooni** [comment]
Would mean much faster writing as compared to using the on screen keyboard

**Comment by arooni** [comment]
A janky alternative would be supporting the paste command in editing a note. I could compose in another app and paste it into Koreader note editing view

**Comment by pazos** [comment]
> A janky alternative would be supporting the paste command in editing a note. I could compose in another app and paste it into Koreader note editing view

a long press on a note edit will paste everything that is on your clipboard :smile:

**Comment by pazos** [comment]
Closing. Bluetooth keyboards are supported as well as bluetooth mouses. Other kind of keyboards are supported too. What needs to be done is in #5902 

(Optionally users can assign key actions to mouse events using https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys)
