### ISSUE TITLE
Tiny margins on 10,3" screen

### ISSUE THREAD

**Issue by carlinux** [koreader/koreader#4684]
No matter what dpi margin or style override I use, the margins are less than 0,5cm.

In a eink 10,3 screen looks tiny. 

Is there a way to setup, by default, bigger margins? Or what piece of code i could touch to increase the margins? Looks like the margins are absolute instead of relative but I don't know.. 

Maybe it would be good to have custom margins by percentage or pixels.(or more buttons to choose).

**Comment by pazos** [comment]
I guess in our case RTFM doesn't apply, but RTFW https://github.com/koreader/koreader/wiki/Change-defaults

**Comment by Frenzie** [comment]
@pazos I disagree, the UX is pretty bad here. :-) The margins accessible through the GUI are pretty small and are aimed at 2011/2012 era Kindles. (Also, I'm not sure why the wiki claims the value should be 5-50. There's no such thing as a maximum of 50.)

@carlinux However, they the margins do change depending on scaled size, here's two examples of "large":
![screenshot_2019-03-01_12-06-24-fs8](https://user-images.githubusercontent.com/202757/53634605-d6ad2b00-3c1a-11e9-846a-935314083415.png)

**Comment by carlinux** [comment]
Thank you guys :+1
