### ISSUE TITLE
Status bar/ page number in rotated screen

### ISSUE THREAD

**Issue by carlinux** [koreader/koreader#4685]
Once rotated the screen to have dual pages the status bar and the info disappear completely. 

 it would be nice to have the page number at least.

**Comment by pazos** [comment]
A screenshot would be nice.

**Comment by carlinux** [comment]
I'm afraid the issue  it's permanent. I supposed it was related with the change of orientation but now the status bar is gone no matter what I do. I'm still investigating. (Trying to solve it to be able to reproduce it )

**Comment by carlinux** [comment]
Ok. So I solved it. Apparently, if the status bar is touched it disappears (after cycling the selectable info) . So.. closed case. I didn't know that!

**Comment by carlinux** [comment]
Actually,  it's in the Wiki https://github.com/koreader/koreader/wiki/Tips-and-Tricks
