### ISSUE TITLE
Ko reader doesnt appear in the KS start menu

### ISSUE THREAD

**Issue by Hedebo** [koreader/koreader#4697]
* KOReader version: 9
* Device: Kobo GLO

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
I would suspect something's off about your folder structure. It should be `.adds/koreader` (inside which you'll find files like `koreader.sh`).

**Comment by AlanSP1** [comment]
Also, KSM 9 have option to start with reduced menu, and that could be configured. So it is possible (not certain) that somehow koreader is removed from that reduced menu. Try to toggle to full menu, to see all options.

**Comment by Hedebo** [comment]
Thanks gentlemen. Obviously it didn't unzip in the correct file structure. Now I have the option to start KO reader but when I do it opens a screen asking to turn off wifi but then nothing happens once i select either yes or no. No browsing menu for certain.

**Comment by Hedebo** [comment]
I am attaching some photos of what I am experiencing. There must be something missing in the file structure. My pdfs are located in the main kobo file. Could that be part of the issue? I hope someone can advise me.

![kobo-3](https://user-images.githubusercontent.com/48134627/53673135-ce251680-3c53-11e9-8963-447040196e49.jpg)
![kobo-1](https://user-images.githubusercontent.com/48134627/53673214-3673f800-3c54-11e9-8004-302be04ce3fc.jpg)
![kobo-2](https://user-images.githubusercontent.com/48134627/53673218-3bd14280-3c54-11e9-93d1-96873c84015d.jpg)
![kobo-4](https://user-images.githubusercontent.com/48134627/53673229-4c81b880-3c54-11e9-918c-55446226791d.jpg)
![kobo-5](https://user-images.githubusercontent.com/48134627/53673232-53a8c680-3c54-11e9-9f50-6038746908a0.jpg)

**Comment by pazos** [comment]
I don't use KSM but looking at the pics and your issue description it seems that the vertical axis has a offset of two rows, so when you touch "start koreader" you'll end touching "wifi". 

If my guess is true by clicking "front light off" you'll end opening "koreader". Otherwise I have no idea :p.

**Comment by Hedebo** [comment]
Thanks Pazos but that wasn't the answer.

**Comment by Frenzie** [comment]
That looks like a copy of the source, not the release. You can find the release under "releases" (or "download" on koreader.rocks).

**Comment by Hedebo** [comment]
Thank you Frenzie. That was the answer. I had downloaded the wrong version for my  kobo to begin with and when the files unzip they are placed in an extra folder with the version name which the Kobo couldn't read until I removed them to the correct folder. Thank You everyone for taking the time to offer advice.
