### ISSUE TITLE
"Disable double tap" appears twice in the Taps & gestures menu, when in File Browser (but not when in Reader).

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4703]
> "Disable double tap" appears twice in the Taps & gestures menu, when in File Browser (but not when in Reader).

_Originally posted by @poire-z in https://github.com/koreader/koreader/pull/4677#issuecomment-468905516_

To reproduce, open a book and then return to the file manager.

**Comment by poire-z** [comment]
Looks like it's because of the `follow_links` item (that should be there only in reader), which, when removed, leaves a slot at the end with its old value kept and shown.

Move `follow_links` at the end, and `Disable double tap` is no more duplicated - but `Link>` is still displayed when in File browser.
```
    taps_and_gestures = {
        "gesture_manager",
        "frontlight_gesture_controller",
        "----------------------------",
        "menu_activate",
        "screen_disable_double_tab",
        "----------------------------",
        "follow_links",
    },
```
So, possibly a menu_sorter issue not clearing stuff.

**Comment by Frenzie** [comment]
MenuSorter just sorts what it's given. It's not responsible for loading or unloading anything.

In this case the problem is related to using require. It keeps the code in memory and doesn't load it again. Which is fine in principle, except MenuSorter does all of its processing on those tables.

The easiest solution is something like `package.loaded["ui/elements/common_settings_menu_table"] = nil` or `dofile("frontend/ui/elements/common_settings_menu_table.lua")`. The latter probably makes more sense for clarity.

A more difficult workaround would be to have MenuSorter act on a deep copy of the table it's given, but I'd say that just seems like more work (for us as well as for the CPU) for little gain.

**Comment by poire-z** [comment]
It's strange we didn't witness that before. There were already menus with different items in File browser vs Reader (the plugins one for example).
