### ISSUE TITLE
FR: Option to assign back button to "Go to previous location" action

### ISSUE THREAD

**Issue by bahusoid** [koreader/koreader#4706]
* KOReader version: 2019.2
* Device: Android 7

For me it's useful to have back history only for some big jumps. Like open first page to see the cover  and then back to my last page. But I don't want to keep all my next page actions in history.

**Comment by poire-z** [comment]
You can disable back history: `Gear>Navigation>` uncheck `Enable back history`.
"Big jumps" (TOC, Bookmarks, following internal link like to footnotes, Skim widget) use another kind of history: the _location stack_, which is independant of _back history_.

**Comment by bahusoid** [comment]
But what about navigation through book via "Go to/Skim to" . I still want to be able to go back to my last page with back.

**Comment by bahusoid** [comment]
My ideal behavior to skip from history exactly next/prev page actions. I mean if next page is opened via "Go To" it should  still be added to "back history".

**Comment by Frenzie** [comment]
That doesn't affect the validity of what @poire-z wrote. That's what back to previous location does.

**Comment by poire-z** [comment]
Yes, but I guess @bahusoid wants to use his Android back key for that.

**Comment by bahusoid** [comment]
> That's what back to previous location does.

But how to do it with my back button?

**Comment by Frenzie** [comment]
Oh right, disabling back history is basically a convenience setting for @poire-z and not so much for users. :-P

**Comment by bahusoid** [comment]
So correct me if I'm wrong but it seems my feature request should be renamed to:
Option to assign back button to "Go to previous location" action

**Comment by Frenzie** [comment]
If that is not possible then yes.

**Comment by poire-z** [comment]
Possibly solved by #6840.
