### ISSUE TITLE
Incorrect north east/west arrows in Noto font

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4707]
* KOReader version: master

#### Issue
North east and north west arrows are swapped in the Noto font.

Take these symbols:
```lua
    northeast = "⬈", -- U+2B08 NORTH EAST BLACK ARROW
    northwest = "⬉", -- U+2B09 NORTH WEST BLACK ARROW
    southeast = "⬊", -- U+2B0A SOUTH EAST BLACK ARROW
    southwest = "⬋", -- U+2B0B SOUTH WEST BLACK ARROW
```

Only the bottom two are displayed in the correct direction.

Pinging @NiLuJe who knows more about the font.

(For the diagonal multiswipes it doesn't really matter. I can just swap the symbols with a comment.)

**Comment by NiLuJe** [comment]
There was an update of the various Google maps fonts a while ago, I'll try
to remember to check/ship that ;).

(could you assign this to me, still on mobile ;)).

**Comment by NiLuJe** [comment]
The culprit is actually FreeSerif, Noto doesn't have those glyphs at all ;).

**Comment by Frenzie** [comment]
I didn't investigate, but I did notice they didn't seem to match up. :-P
