### ISSUE TITLE
right to left   language in file browser

### ISSUE THREAD

**Issue by Gil-boy** [koreader/koreader#4709]
* KOReader version:
* Device: kobo aura one

#### Issue

in file browser the filename are written in left  to right  even if the language in right to left .
ps  the  language i use is arabic  but i think the issue is on all right to left  language.

**Comment by Frenzie** [comment]
That's very hard to fix I'm afraid, although since we now have a HarfBuzz library readily available it might be less difficult than it used to be.

There's a HB FFI implementation [here](https://luapower.com/harfbuzz/info).

**Comment by Frenzie** [comment]
Not fixed yet, but with #5359 in active development there's little reason to keep this specific issue open.
