### ISSUE TITLE
Landscape: swiping & wrong place in book

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4724]
* KOReader version: v2019.02-155-g8ecdf9d_2019-03-04/  
* Device: KA1

#### Issue
Maybe you are already aware of this.

Since the introduction of multiswipes, swiping (including single swipes) in landscape is completely f*cked up. The biggest problem with this is that you can't even open the menus with a swipe.
Luckily it´s still possible to open the menus by tapping.

Another thing is that you end up 1 or 2 pages back (after a tap). Reproduce like this:
Go from portrait to landscape. Tap once (forward or backward).

**Comment by Frenzie** [comment]
> Maybe you are already aware of this.

If there's no issue, always assume it's unknown. Thanks for reporting!

> Since the introduction of multiswipes

Since #4640, rather.

**Comment by gerhaher** [comment]
The second thing I mentioned isn't corrected with latest nightly (v2019.02-161-gbae83ad_2019-03-04/ ).

What I meant in my first post is when you rotate screen and then page tap you end up on wrong place in text.
Portrait to landscape + page tap = 2-3 pages back
Landscape to portrait + page tap = 2-3 pages forward

**Comment by poire-z** [comment]
That's the kind of bug I hate having to look at.
But I can't reproduce it (with EPUBs, page mode, with top or with bottom status bar).

Any more info about when this happen or not happen (EPUB? PDF? mode?).
Try to stick to the first page of a chapter, so you're not disrupted by some text shift.

So, after rotation - and before taping, you're on the good and same page? And the page number in the footer is accurate (meaning that after taping and taping again to find that page again, you find the same number?)
And it's just on the first tap after rotation that you jump more than one page - and is this confirmed by the page number in the footer?

**Comment by Frenzie** [comment]
@gerhaher I don't see anything like that.

**Comment by poire-z** [comment]
(Also, just in case this is what had you confused - but I hope not :):
indeed, when I switch rotation, my page number change often a few digits - but that's because the total pages number change when rotation. So I may have been on page 400/500 in portrait - and after rotation I'm at 404/512 - but it's the same page with the same content - and then, after taping, I go to page 403 or 405.)

**Comment by poire-z** [comment]
(But I *do* experience something like that when resizing my emulator :) but I really don't care).

**Comment by Frenzie** [comment]
Do you have double taps enabled? Due to an issue fixed in #4736 a single tap might've been incorrectly detected as double tap (previous/next chapter).

**Comment by gerhaher** [comment]
No, I don't think I have made any mistake or misunderstood something. The issue is there.
I made a new, clean KOReader installation on my other device (Kobo Aura) and it appears there too.

It doesn't happen to pdf's. Only epub's AFAIK.
Full or mini progress bar doesn't matter.

This is exactly what happen. I have chosen a large book (1383 pages in my configuration (1468 in landscape)).
1. I start in portrait mode on first page in chapter 2.
2. Rotate the screen to landscape and end up on the same place (first page in chapter 2). The page numbers in the upper right corner has now changed but not the page numbers in the bottom status bar.
3. I tap 'page forward' once. I end up somewhere else in the book. And now the pages in the bottom status bar has changed too. 
4. I tap forward twice more and now I'm back on first page in chapter 2). If I had tapped backward after the rotation, I would have to tap forward 4 times to get back to chap 2.
5. When I open TOC I notice that the pages are the same as in portrait mode. Shouldn't they change when you rotate the screen?
6. I rotate again, back to portrait. End up on the same page (first page, chap 2)
7. Tap backward once. And then tap backward twice more, and now I'm back where I started.
8. I open TOC and tap on chapter 20, page 607.
9. Rotate the screen to landscape. Tap forward once. 
10. Now I have to tap forward 32 times to get back to chapter 20.
11. Rotate back to portrait. Tap backward. 31 times backward taps to get back.
12. The 'previous/next chapter' feature is of course completely wrong in landscape.

**Comment by poire-z** [comment]
> I forgot to tell you that if I disable multiswipes the problem disappears.

I'm glad to hear that (you mean that everything is right, including updated page numbers in the TOC?) - but I have a hard time to see what in multiswipes code could cause that difference in behaviour.

And how are you toggling the rotation? With the bottom config toggle or with a multiswipe? If via multiswipe, does it work ok if you use the toggle? (in which case, it might just be the multiswipe rotation that does not enough - and that would be a relief and probably easy to fix :)

**Comment by poire-z** [comment]
I guess this is it: with the bottom toggle, everything is fine. When toggling rotation with a gesture, I experience the kind of mess you describe.

**Comment by gerhaher** [comment]
Yes, everything is OK if I disable multiswipe.

I toggled with multiswipe.

You are right. I tried now the bottom config and it worked fine.

**Comment by Frenzie** [comment]
I still can't reproduce, but a bug in the gesture manager action makes a lot more sense. Multiswipes could certainly break taps in theory if they were messed up, but it'd basically be an all or nothing affair (like in your OP regarding swipes).

**Comment by poire-z** [comment]
I think it's just the wrong event we use in readergesture: `SetScreenMode`.
We should probably use the ones used in koptoptions.lua `SwapScreenMode ` , or creoptions.lua `ChangeScreenMode` depending on has_page, which do SetScreenMode + a bit more stuff.
(no time right now to test, but may be later this evening if no one beats me to it :)

**Comment by NiLuJe** [comment]
That's what I was going to suggest ;).

**Comment by Frenzie** [comment]
@poire-z @NiLuJe I think I just copied the whole thing from the existing multitouch rotation.

There's also this:
https://github.com/koreader/koreader/blob/29f52cce81bb5a077c1708f841185e3fb4534af7/frontend/apps/reader/modules/readerrotation.lua#L28-L32

**Comment by NiLuJe** [comment]
I think that's handled as-needed by the onSwapScreenMode handlers (... and children) if relevant.

**Comment by Frenzie** [comment]
You know, I read through #4414 but the addition of this onSwapScreenMode event completely slipped my mind. :-)

Anyway, I'd try to fix it, but I'll leave it to someone who can actually figure out how to reproduce the problem.

**Comment by poire-z** [comment]
OK, that seems to work. problem fixed now on EPUBs, and rotation gesture works on PDF.
(And Toggle rotation is not presented among the FM gestures, so nothing to test and no worry I guess :)
