### ISSUE TITLE
Since -155 build, the screen dpi settings are ignored

### ISSUE THREAD

**Issue by ptrm** [koreader/koreader#4726]
* KOReader version: v2019.02-155-g8ecdf9d_2019-03-04
* Device: Kobo Forma / Clara HD

#### Issue

I use a 200dpi custom screen dpi setting. After the update from `-130` to `-155`, the screen dpi is forced to 320 dpi, and even checking other checkboxes while in the menu doesn't uncheck old / check new selection.  `["screen_dpi"] = 200` was still present in the settings.reader.lua during all changes, after exiting koreader to make sure it saved.

After unzipping -130 back, the dpi settings are maintained as expected.

#### Steps to reproduce
Attempt to change screen dpi in the `Screen > Screen DPI` menu. The checkboxes remain intact and after restart the dpi is intact as well.

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/commit/dd1ab7b409d73d270c4b1477bd30ba89ec6e245f#commitcomment-32573579

**Comment by poire-z** [comment]
That one line added patch seems to work. Who's adding it so we get it in tomorrow's nightlies?

**Comment by Frenzie** [comment]
I'm not sure if it's quite the proper solution. I think there's an idea there about setting fb.dpi to the actual DPI of the screen with a custom_dpi for scaleBySize. (But of course you could stick in there as a quick fix.)

**Comment by poire-z** [comment]
Well, dunno. Looks like #4580 decouples a bit too much :) Pinging @houqp .

There is this added:
https://github.com/koreader/koreader/blob/710ab1ba1b9c2d0d40fac35691989474d56bc952/reader.lua#L37-L41

I guess calling `require("device")` does already many things including calling getDPI(), and the later setDPI() lose:
```
ffi.load (warning): libgtk-3.so.0: cannot open shared object file: No such file or directory
03/04/19-21:26:00 WARN  fb:getDPI
03/04/19-21:26:00 WARN  fb:getDPI 160
03/04/19-21:26:00 WARN  fb:getDPI 160
03/04/19-21:26:00 WARN  fb:getDPI 160
03/04/19-21:26:00 INFO  initializing for device Emulator
03/04/19-21:26:00 INFO  framebuffer resolution: {    ["h"] = 610,    ["w"] = 600}
03/04/19-21:26:00 WARN  fb:setDPI 120    -- too late
03/04/19-21:26:00 WARN  fb:getDPI 160
```

**Comment by Frenzie** [comment]
Yeah, I noticed the same thing. :-) Anyway, let's just go ahead and add that line so the next nightly and the upcoming stable work as intended even if the backend stuff might need another look.

**Comment by poire-z** [comment]
OK, please do it if you can.

**Comment by Frenzie** [comment]
Alright, on it.

**Comment by ptrm** [comment]
I'm not sure if it's a consequence of the temporary fix, so I describe it below:
Auto dpi seems to be impossible to set. The checked dpi value in the menu seems to be rounded to the closest one available in menu entries.
I had auto dpi on Clara HD set before posting this issue (I use custom value only on larger displays), and after upgrade to `-161` the checkbox checked is 320 (not sure if the actual value used in UI is 320 or 300 (real dpi), that's only what I can see on the display). When checking auto dpi menu option again, the checkbox stays on 320, unless I set a custom 300 dpi value, then after picking auto and restarting, the `custom (300)` option is checked in the menu.

That being said, it is possible to set *any* dpi value from the GUI, so that doesn't bother me personally so far ;)

**Comment by Frenzie** [comment]
I think @houqp is taking a closer look at it as we speak. :-)

**Comment by houqp** [comment]
@ptrm I double checked on the auto dpi logic, currently the check display is wrong due to the temporary fix. for some reason, it relies on `framebuffer.dpi` being `nil` to display the check. The end result is not affected though, i.e. if you set to auto dpi, you should be getting 320 as dpi, it just that the wrong box is being checked.

I am going to work on a fix later this week to address the display issue.
