### ISSUE TITLE
Gesture manager: action suggestions

### ISSUE THREAD

**Issue by mayabtlaloc** [koreader/koreader#4727]
I find it essential to navigate quickly between folders. Thanks

- [x] Folder shortcuts

**Comment by Frenzie** [comment]
And it would go nicely as the file browser equivalent default gesture for bookmarks.

Also:
- [ ] Toggle scroll/page mode

**Comment by poire-z** [comment]
There is one (that I don't want to have anything to do with :) that is strangely missing (that one you use Suspend or your power button to have it, if I remember correctly):
Set Wifi off (and/or Toggle Wifi).

**Comment by Frenzie** [comment]
I occasionally use suspend as a quick wifi turn-off, yes.

Anyway, I think we've got a decent set of actions for release. More can just trickle in. :-)

**Comment by Frenzie** [comment]
Adding a reference to #3978. Because with a multiswipe of at least three strokes, ignoring touch could work on any device.

For example, an L for lock:
<img src=https://user-images.githubusercontent.com/202757/53835532-07c88b00-3f8e-11e9-84e2-92465c68e551.png width=40%>

But definitely not for the stable. Something like that is a little too volatile to throw in last minute. ;-)

**Comment by gerhaher** [comment]
I would like to see the multiswipe gesture manager itself among the actions opened with a multiswipe.

**Comment by Frenzie** [comment]
- [ ] Book information
Also see https://github.com/koreader/koreader/issues/4659#issuecomment-471635233, but not so much forgotten as not wanting another last-minute disaster akin to #4733 (with #4764 and #4772).

> I would like to see the multiswipe gesture manager itself among the actions opened with a multiswipe.

For sanitary code organization purposes I would generalize that as opening a specific (sub)menu. Not likely to happen very soon I'm afraid but it is part of my overarching vision. :-)

**Comment by Galunid** [comment]
It'd be nice to see "Next/Prev Highlight action" gesture(`Document > Highlight action`). Not sure how many people would be interested, but I'd like it for when I'm debugging stuff on my kindle and need to quickly go from `Highlight` to `Ask`.

**Comment by Frenzie** [comment]
You should know more about that than me. :-) What is it this action would do precisely?

**Comment by Galunid** [comment]
Basically it should set `default_highlight_action` in `G_reader_settings` to one of the following
`"highlight"`, `"translate"`, `"wikipedia"`, or `nil`, and display notification which one is enabled now. I'm not familiar with gesture manager, but sth like this would probably work:
```lua
local actions = {
    "highlight": "translate",
    "translate": "wikipedia",
   "wikipedia": nil
}
local current_action = G_reader_settings:readSetting("default_highlight_action")
if not current_action then
   G_reader_settings:saveSetting("default_highlight_action", "highlight")
       UIManager:show(InfoMessage:new{
           text = _("Default highlight action is now: highlight"),
           timeout = 1,
       })
else
   local next_action = actions[current_action]
   G_reader_settings:saveSetting("default_highlight_action", next_action)
       UIManager:show(InfoMessage:new{
           text = "Highlight action is now: " + next_action,
           timeout = 1,
       })
end
```

**Comment by Frenzie** [comment]
That looks okay to me, except you should try to keep the logical separation by putting those lines in something like `ReaderHighlight:onToggleHighlightAction()`. Then you can trigger the `ToggleHighlightAction` event from the gesture manager action.

NB I haven't looked at the specific code involved so that's more of a generic statement even if it looks specific.

**Comment by gerhaher** [comment]
"View book description" would be nice to have too.

**Comment by Frenzie** [comment]
@gerhaher Is that something different than #4777?

**Comment by gerhaher** [comment]
> @gerhaher Is that something different than #4777?

With #4777 you need to do 2 things to open the description: a multigesture & a tap.

The most common reason for me to open Book information, is to view the books description. So to bypass "Book information" and directly open the "Description" with a multigesture would be nice.

Well anyway, it's not superimportant.

**Comment by Frenzie** [comment]
Oh, I see what you mean. Perhaps @poire-z (who authored book info) would be interested in that?

**Comment by poire-z** [comment]
(Come on, 2 things, a gesture and a tap! for something you'll do at most 2 or 3 times on a book :)

Anyway, using stuff from filemanagerbookinfo is a bit complicated, as it's more just the display parts that gets the bookprops dict from various callers (including CoverBrowser when the props are in the db) and set up kvpage and use the callback it provides.

It's just easier to get it from self.ui.document and launch the TextViewer directly in gesture manager.
Something like this as the action code seems to just work:
```lua
        local TextViewer = require("ui/widget/textviewer")
        UIManager:show(TextViewer:new{
            title = _("Description:"),
            text = self.document:getProps().description or _("N/A"),
        })
```
(@Frenzie : feel free to go on with that and pick a default gesture for it if it's worth one and you have an idea for it.)

**Comment by Frenzie** [comment]
It seems a bit niche to have as a default gesture, but as an action it seems fairly innocent maintenance-wise.

**Comment by poire-z** [comment]
OK, I'll add it. And its buddy "View book cover" while we're at that.

**Comment by gerhaher** [comment]
How about disable/enable Reading Statistics? Is that posssible?

**Comment by gerhaher** [comment]
> OK, I'll add it. 

There is an issue with it. 
These things are added to description text:
<div> <p> <p class="description">  <em>  <h3>

**Comment by poire-z** [comment]
Right, forgot to use what's used in bookinfo:
```
        -- Description may (often in EPUB, but not always) or may not (rarely
        -- in PDF) be HTML.
        description = util.htmlToPlainTextIfHtml(description)
```

**Comment by lengyelimrezsolt** [comment]
I would find it useful to have gestures for fine-tuning font sizes, like one gesture for font size +1 and another for -1.

**Comment by Biep** [comment]
One I really miss is "scroll here to top/bottom".
I read lots of PDFs, zoomed to content width.  Now sometimes there is an image or diagram that straddles the page, and I'd like to draw a horizontal line at the top of the image, and then vertically up to the top rim of the screen, meaning: move this position to the top.  Likewise with moving the bottom of the image to the bottom of the screen.
(And being left-handed, those horizontal parts would be right-to-left.)

**Comment by Frenzie** [comment]
Splitting out the feature request for new functionality and closing. The type of actions intended for this issue was existing functionality. I'll close this issue because we've reached quite a usable degree of gesture manager actions. Please create dedicated tickets if something should come up.
