### ISSUE TITLE
How I access to frontend folder on android devices 

### ISSUE THREAD

**Issue by rutapon** [koreader/koreader#4731]
* KOReader version:all
* Device:android 

#### Issue
How I access to frontend folder. 
or, is it possible to change location of frontend folder to somewhere that I can access? (without root)

**Comment by Frenzie** [comment]
You can set a custom folder in persistent.defaults.lua or use the default:
https://github.com/koreader/koreader/blob/89fe3e305129e537088fe9ec6e6970c85265d72e/defaults.lua#L200

**Comment by rutapon** [comment]
Sorry.
I mean frontend that content Lua code.
I want to change some little things like I do on kobo.

**Comment by pazos** [comment]
@rutapon:

you can access settings in /sdcard/koreader.

assets like libraries and lua files are stored somewhere in /data (you can figure out where with `adb logcat luajit-launcher:I *:S`) and thus they are not modificable.

Which kind of tweaks do you want to do?

**Comment by Frenzie** [comment]
Unfortunately Android doesn't work that way. (It's a pretty terrible platform.)

You can however use a patch file, to fairly limited effect.
https://github.com/koreader/koreader/blob/c5b2bad6d6e712e217525f8a8e60ed835cf1f6ea/platform/android/llapp_main.lua#L21

**Comment by rutapon** [comment]
Thank you.
I have changed many little things, but the important things (for me) are normal dictionary window size and swipe up-own for changing page.

**Comment by Frenzie** [comment]
These simply sound like settings available through the UI? On Android those are stored in /sdcard/koreader.

**Comment by rutapon** [comment]
I can't find it. 

Swipe up-down normally work on epub but not on pdf. 
Large window dict, I want to add little space left and right for easyly close windows. 

These are only my preference, not that has to be changed in main code.

**Comment by Frenzie** [comment]
Dictionary settings:
![screenshot_2019-03-04_21-54-55](https://user-images.githubusercontent.com/202757/53762355-30864d00-3ec8-11e9-89e5-50230c7d1188.png)
Large window (near the bottom)
![screenshot_2019-03-04_21-55-05](https://user-images.githubusercontent.com/202757/53762356-30864d00-3ec8-11e9-8e82-79a04ab4b946.png)

On second thought I suppose there isn't anything about changing swipe left/right to up/down atm, unless it's hidden in the advanced settings.
