### ISSUE TITLE
Gesture manager: something wrong with toggle rotation

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4738]
* KOReader version: master
* Device: all

#### Issue
Something about page numbers, not sure how to repro yet. See https://github.com/koreader/koreader/issues/4724#issuecomment-469721725

**Comment by ersi-dnd** [comment]
Still something wrong with this. I played around with the gesture manager. On my Kobo H2O first edition (with midroSD slot), I changed the default Book status gesture to File browser and made one other change (sorry, don't remember) and after reboot (that is reboot, not app restart) Koreader opened up upside down, with the touch interface still being as if the app were not upside down. With great difficulty I managed to disable multiswipes and restart to get my Koreader back as it was.

Perhaps there should be a default gesture for "disable multiswipe gestures and restart Koreader"?

**Comment by poire-z** [comment]
Not sure there should be anything to do with gestures. Might be if a restart makes it upside down, a second restart puts it back correctly :) with our without gestures enabled.

Probably more related to #4752 - and something specific to the H2O (I thought I've read something in the release notes about H2O users needing to upgrade to KSM09, but can't find that anymore). @Frenzie ?

**Comment by NiLuJe** [comment]
Yeah, KSM08 doesn't actually handle the rotation quirks of the 6.8" Kobo panels properly.

I have no idea why this only started appearing since the 8bpp move, but definitely not our bug.

**Comment by Frenzie** [comment]
Definitely not multiswipe related, nor to this issue. ;-)
