### ISSUE TITLE
Update git command in README.md

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#4743]
I couldn't build at my first try cloning using git clone https://github.com/koreader/koreader.git

(missing luafilesystem/)

Then I figure out by the base/.gitmodules that some submodules need to be fetched.

So I suggest update the doc file:

https://github.com/koreader/koreader/blob/master/README.md#getting-the-source

for include the submodules and could be changed to:

git clone --recurse-submodules https://github.com/koreader/koreader.git

**Comment by Galunid** [comment]
Actually the second command after `git clone`:
```bash
cd koreader && ./kodev fetch-thirdparty
```
does module initialization I believe.

**Comment by hugleo** [comment]
Yes, I forgot to type ./kodev fetch-thirdparty

But I'm seeing a error now:

cd koreader && ./kodev fetch-thirdparty
v2019.02-172-gb1075fba
git submodule init
Submodule 'koreader-base' (https://github.com/koreader/koreader-base.git) registered for path 'base'
Submodule 'platform/android/luajit-launcher' (https://github.com/koreader/android-luajit-launcher.git) registered for path 'platform/android/luajit-launcher'
Submodule 'platform/ubuntu-touch/ubuntu-touch-sdl' (https://github.com/Sturmflut/ubuntu-touch-sdl-template) registered for path 'platform/ubuntu-touch/ubuntu-touch-sdl'
Submodule 'resources/fonts' (https://github.com/koreader/koreader-fonts.git) registered for path 'resources/fonts'
Submodule 'test' (https://github.com/koreader/test-data.git) registered for path 'test'
git submodule sync
Synchronizing submodule url for 'base'
Synchronizing submodule url for 'platform/android/luajit-launcher'
Synchronizing submodule url for 'platform/ubuntu-touch/ubuntu-touch-sdl'
Synchronizing submodule url for 'resources/fonts'
Synchronizing submodule url for 'test'
git submodule update
Cloning into '/home/hugleo/Desktop/koreader/koreader/base'...
Cloning into '/home/hugleo/Desktop/koreader/koreader/platform/android/luajit-launcher'...
Cloning into '/home/hugleo/Desktop/koreader/koreader/platform/ubuntu-touch/ubuntu-touch-sdl'...
Cloning into '/home/hugleo/Desktop/koreader/koreader/resources/fonts'...
Cloning into '/home/hugleo/Desktop/koreader/koreader/test'...
Submodule path 'base': checked out 'f549ca8922f92a70986082a1d2023de3e7cd9a68'
Submodule path 'platform/android/luajit-launcher': checked out '734f66878703cf895fe52cf5757ffee041a4f01e'
Submodule path 'platform/ubuntu-touch/ubuntu-touch-sdl': checked out '1d0cd7583c27025a69e340ac77cab3c53cdef8ba'
error: Server does not allow request for unadvertised object c526ac0087cb7cbf00200659d9efc8189581d15c
Fetched in submodule path 'resources/fonts', but it did not contain c526ac0087cb7cbf00200659d9efc8189581d15c. Direct fetching of that commit failed.
make: *** [Makefile:146: fetchthirdparty] Error 1

**Comment by Frenzie** [comment]
As @Galunid said, there's really nothing to add.

But in fact if you run `./kodev build` or `./kodev run`, you won't need to do even that. It will do that for you automatically.

https://github.com/koreader/koreader/blob/b1075fba60110ea1834404ec848c82ef01d3d068/kodev#L38-L42

**Comment by hugleo** [comment]
Yes, doesn't worked for me because ./kodev build (kodev-fetch-thirdparty) have a bug fetching resources/fonts. The reason that git clone --recurse-submodules is working is that in this way the luafilesystem is being fetched first.  The resources/fonts error is getting further for git clone command too.

**Comment by Frenzie** [comment]
It's an annoying GitHub server bug/behavior.

In base I implemented a workaround, but that's a slightly different scenario:

https://github.com/koreader/koreader-base/commit/4b8bc32d525866096c410b1f119d9c39e049dbe3
