### ISSUE TITLE
Inkpad3 Wifi Standby 

### ISSUE THREAD

**Issue by Jarcis** [koreader/koreader#4747]
Hi@all,

as tob1az has released a fix for the sleep/resume issue for the Pocketbook Inkpad 3 koreader is now a very good replacement for the Standard Ebookviewer. 
Now there is a small issue left which I have seen, compared to the koreader on Kindle Paperwhite:
The Pocketbook OS has a function to put Wifi into sleep/standby directly after an APP is used which don't need permanent Internet Connection. 
This leads to problems in syncing the read progress because after a few seconds the Inkpad remains offline while the koreader is used - also the wifi doesn't turn back on after the reader is brought back from sleep. 
Is there a possibility to enable a request for internet from the koreader to the pocketbook os, as so the wifi wouldnt go to sleep? 

Best Regards,
Jarek

**Comment by Frenzie** [comment]
Pinging @tob1az since I don't really know much about PB. ;-)

**Comment by tob1az** [comment]
This question requires some investigation. Indeed, the OS shuts WiFi down as soon as possible. There should be a way to prevent this. At least, the built-in browser app somehow keeps the network connetion on.
I'll look into it later.

**Comment by Jarcis** [comment]
Thank you in advance for your efforts
You are our Pocketboot Savior :D

If there is something, to investigate, test or evaluate, I'll be happy to help.

**Comment by tob1az** [comment]
This issue looks similar to #3975

**Comment by pazos** [comment]
@tob1az: there is a wifi toggle in https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L49-L51

but it wasn't used AFAICT. You can test what happens if you toggle wifi. (You'll need to set `hasWifiToggle = yes` in https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L58)

**Comment by Jarcis** [comment]
In the latest release for Pocketbook from February (and curiously not in the latest nightlies) there are still controls for Wifi in the koreader settings, but they doesn't changen anything to this problem :(

**Comment by tob1az** [comment]
@pazos, thanks for your hint. I guess NetworkMgr:isWifiOn() should be implemented as well.
@Jarcis, the Wi-Fi toggling was disabled for PB in #4550. I'd also need an additional input from you:  Are you using the Progress sync plugin? It it synchronized automatically or manually?

**Comment by Jarcis** [comment]
Yes, I'm using the progress Sync plugin - it is working fine, including signing in to the server, manual and auto sync, but only in a short matter of time: only when I directly sync after a switch from a wifi connected Pocketbook Main Screen (where you can choose the books to read) to the koreader through the task manager. After this the wifi turns off and I then also can't manually push the progress sync.
There is a trick to extend this "connected" time: As you have also found out, the integrated Webbrowser turns on the Wifi directly and with it as a background task, the internet remains on. But after a little time or when you put the Pocketbook into sleep, the Wifi connection turns off again.

**Comment by pazos** [comment]
> the Wi-Fi toggling was disabled for PB in #4550.

Yup, it was visible before but disabled, see https://github.com/koreader/koreader/pull/4550/files#diff-8a665adb55900a011d1c3928d7447e61L132

>  I guess NetworkMgr:isWifiOn() should be implemented as well.

I have no idea if the pocketbook sdk provides a way to retrieve network status, but [this one](https://github.com/koreader/koreader/blob/master/frontend/device/cervantes/device.lua#L16-L22) should be generic enough if the interface name is known.

**Comment by Frenzie** [comment]
@tob1az GH does some auto-close stuff that you can get around by writing something like "references issue number" or "cf. issue number".

**Comment by pepefil** [comment]
This pocketbook SDK (https://github.com/dennwc/inkview/blob/8f626286e32bb7cc2c42fce86acfb60786e1d496/network.go#L71) talks about a KeepNetwork function that may have something to do with the issue.

Maybe it's something obvious (I'm not a developer) or maybe it has nothing to do with the issue, , but I hope this helps.

**Comment by tob1az** [comment]
@pepefil thanks, I'll check it.
@Jarcis Wi-Fi can now be turned on/off in the Koreader menu. However, the session will not last more than a couple of minutes. You could test the nightly build.

**Comment by Jarcis** [comment]
@tob1az 
Really Big thanks for your efforts  :D
After I've seen your update/commit I was just on my way to test it, but unfortunately it seems that my Inkpad3 has failed:
After connecting to my Computer it wasn't reachable and then it has has crashed; Not it only boots to the Pocketbook Logo and also any Firmware Update (through the button combination on boot) is crashing with an error :( 

So unfortunately I won't be able to test until I'll get my Inkpad back from RMA :'(

**Comment by iamjustaguest** [comment]
My tests so far on a Pocketbook PB631 aka Touch HD with actual U631.5.19.656 firmware.

Now Wi-Fi can be turned on from inside koreader nightly version, but there are still issues.

This describes what happens when checking for updates, Wi-Fi not enabled before:

The dialog from koreader comes up asking to enable Wi-Fi, then the Firmware dialog comes up asking to enable Wi-Fi.
After confirming a white page comes up showing an hourglass.
Then koreader comes back, shows the ebook text and a dialog that says 'sleeping', but that disappears in seconds.
I guess that sends Wi-Fi immediately into sleep mode?

On pocketbook home screen the icon shows an enabled, but sleeping Wi-Fi.
The koreader Network settings shows a sleeping Wi-Fi as not enabled.

Is there a way to disable sleep mode for koreader temporarily for further tests?

**Comment by tob1az** [comment]
@iamjustaguest My guess is that dialog popped up because there were no Wi-Fi connections configured on your device. Adding a connection in the Pocketbook Settings would probably help. 

I'll look into this use case though.

**Comment by iamjustaguest** [comment]
A Wi-Fi connection is configured and it works with the built-in browser.

I think the problem is the immediate sleeping.
Also when i activate Wi-Fi via Network Menu from koreader comes the sleeping dialog.
Workaround is opening the built-in browser app as already mentioned.

**Comment by pepefil** [comment]
Same behavior in my Inkpad3. Although there is a connection configured in PB, the activation of the network via Update menu, or via Network menu, results in a "sleeping" popup. After that, network is enebled, but Wi-Fi is sleeping.

**Comment by LucyOne** [comment]
Same problem on my Pocketbook Touch HD 3. I could only connect to Evernote with the Pocketbook browser running to keep Wi-Fi on.

**Comment by dekani** [comment]
Here are some tests results and details about this issue.

Wifi mode has 3 visible states :
- disabled : no Wifi icon displayed on screen,
- standby (or passive/disconnected) : All Wifi bars are empty.
- active : Wifi bars are filled depending on Wifi signal strength.

I have only seen two cases (at the moment...) where standby mode is reached on my device:
- after device standby/wakeup functionality is used. (Power button quick pressed)
- when KOReader application/process goes to background - occurs when home button is pressed for example. ('Sleeping' message is displayed, and perhaps when it is resumed)

When Wifi always works with KOReader:
- when Wifi mode is active before KOReader is started or resumed. (using Pocketbook task/process management tool - long press on home button)

Wifi state is preserved when KOReader is exited normally. (from option menu)
Wifi mode can be set to active mode running native Web browser application before KOReader is started. (as described in previous comments)

What occurs with KOReader when Wifi mode is:
- disabled : KOReader asks to turn it on. If confirmed, Pocketbook SDK mesage box asks to enable Wifi (KOReader process probably goes to background as a 'Sleeping' message is displayed) and enable it but it isn't possible to use it. (If KOReader is exited with menu option to preserve Wifi state, Wifi state is no more disabled and confirmed to be visually set to standby mode)
- standby mode: KOReader asks to enable Wifi too (but no SDK progress bar is displayed) and there is no possibility to use it. (KOReader always asks to enable it)
If KOReader is exited with menu option, Wifi state is confirmed to be active.
- active : Works without any issue.

I don't know if it can be useful (or already used with KOReader), but some Pocketbook unix scripts used this command before using Wifi:
/ebrmain/bin/netagent connect

**Comment by Frenzie** [comment]
It's now using libinkview:

https://github.com/koreader/koreader/blob/95d18fe8d9cc5f21763eaa76bd7960d0a746a309/frontend/device/pocketbook/device.lua#L169-L172

But it used to use that command:

https://github.com/koreader/koreader/commit/89c17092e8358b70ece568aa023e3cc91072063a

**Comment by BloodyStupidJohnson** [comment]
I think i have found a workaround
TurnOnWifi function misses one line:

`function PocketBook:initNetworkManager(NetworkMgr)
    function NetworkMgr:turnOnWifi(complete_callback)
   	-- this line over here actually enables wifi
   	inkview.WiFiPower(1)
   	-- yup, that's it
        if inkview.NetConnect(nil) ~= C.NET_OK then
            logger.info('NetConnect failed')
        end
        if complete_callback then
            complete_callback()
        end
    end`

I tested it on my PB627 (a.k.a Touch Lux 4) and it seems to work. It asks you to enable wifi and then if you repeat your request it works fine. It still goes idle over the time, but it works, at least

**Comment by jakubjezek001** [comment]
@BloodyStupidJohnson yes, this is working for me.

**Comment by andrewshadura** [comment]
@BloodyStupidJohnson, @jakubjezek001, thanks for this proposed change and the verification. I have created a pull request with this change.
