### ISSUE TITLE
Kobo Forma - Rotation doen't work

### ISSUE THREAD

**Issue by bearthang** [koreader/koreader#4749]
* KOReader version: 2019.02
* Device: Kobo Forma

#### Issue
Can't rotate screen

#### Steps to reproduce
Opening the application in Portrait mode.
Turn the device up-side down --> the screen doesn't rotate

**Comment by NiLuJe** [comment]
Nickel needs to have been started at least once in a power cycle for rotation events to be handled.

**Comment by bearthang** [comment]
I've already started the nickel but it doesn't work.
Here are my steps:
_ Exit KOReader then go to KSM.
_ Start Nickel.
_ Open the book "exit_nickel" to back to KSM.
_ Start KOReader.

Are they right order?

**Comment by NiLuJe** [comment]
I have no idea, as I don't use KSM. I just know @ptrm had to jump through quite a few hoops to get that to behave w/ KSM.

**Comment by ptrm** [comment]
@bearthang:

>Here are my steps:
_ Exit KOReader then go to KSM.
_ Start Nickel.
_ Open the book "exit_nickel" to back to KSM.
_ Start KOReader.
>
>Are they right order?

That's what I do and what gets me rotation working.

Maybe that's a firmware-related issue? I use the latest version on Forma (4.12 or higher AFAIR)

**Comment by bearthang** [comment]
Oh, I've found the reason!!!
I checked to "ignore accelerometer rotation event" because I don't want to switch to Landscape mode accidentally.

Is there any setting that is "enable rotation event with Portrait mode only".

**Comment by NiLuJe** [comment]
Nope. Not quite happy with the few ideas I had about how implementing that would potentially go.

**Comment by NiLuJe** [comment]
(In the meantime, I'm closing this ;)).
