### ISSUE TITLE
Kobo Aura H2O rotation issue

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4752]
* KOReader version: since #4637
* Device: Kobo Aura H2O, should also be the case on Kobo Aura HD and potentially others with the same display (H2O2?)

#### Issue
Something's off with the fbink update rotation and rotation in KSM on exit. Discussion on Gitter around https://gitter.im/koreader/koreader?at=5c815e368f294b134a04908a and higher.

The update notification looks like this:
![screenshot_2019-03-07_20-23-34](https://user-images.githubusercontent.com/202757/53983448-771db680-4117-11e9-8161-886828bbf200.png)

**Comment by Frenzie** [comment]
Video illustrating the problem:

[2019-03-07 21.03.11.mp4.zip](https://github.com/koreader/koreader/files/2943075/2019-03-07.21.03.11.mp4.zip)

On KSM8 there's also some turning upside down in the menus on exit, but KSM9 is fine so we can probably just ignore that.

**Comment by NiLuJe** [comment]
Yeah, that was an oversight on my part ;). I'd blissfully forgotten about the quirkiness of the rotation pickel sets up on those devices, because it behaves differently on the Forma.

I just need to expand the current checks for that state to 8bpp ;).

**Comment by poire-z** [comment]
Just for info: no issue at all for me with koreader 8bpp with FW 3.19 and good old KSM 07.
Btw, that may concern only users of older devices that were supported by KSM 07 - as newer devices need KSM 09 - but KSM07 has the benefit (for some) that it's all on the /mnt/onboard partition unlike newer ones. So, I'd rather like koreader to stay compatible with older KSM :)

There is just one thing, possibly related to input/gestures changes - but probably not: the issue I described at https://github.com/koreader/koreader/issues/4431#issuecomment-455847181 has happen to me 5 times over last week, when it happened previously only twice a month. But it could be just very well that I multiswipe too much now :)  and the original problem, possibly hardware related, shows itself more often with more touch events...
Still unsure what's the cause - but unlike @ptrm issue with his Clara describer on gitter, when my touch layer is unresponsive, I can still suspend with the power button - wait 20 seconds, resume, and touch is back.

**Comment by NiLuJe** [comment]
@poire-z : You're using a Glo HD, right?

Could I get an excerpt of your KOReader logs, just to double-check which rotation it's in, so that I try not to break it when I fix the H2O issue? ;).

**Comment by NiLuJe** [comment]
But yeah, as @Frenzie said, this specific quirk applies solely to the H2O, the Aura HD (for sure), and possibly the H2O² (the first version, if not both).

(Basically, the kernel sets the invert rotation of the requested one. Which leads to hilarity in some custom rotations, something we only realized quite recently when Plato started doing hardware rotations. But that extra bit of fun *shouldn't* come in play here, unless I screwed up ;)).

**Comment by NiLuJe** [comment]
@poire-z: Do you get anything relevant in the logs (in debug mode, I guess), when those touches get sent to the void?

(The only weird thing I'm seeing on the H2O is still the very *first* touch on KOReader startup that does nothing, but it does get registered. I've never bothered to look further into it ;)).

**Comment by poire-z** [comment]
Just had a (I guess) luajit cpu loop after setting `DCREREADER_TWO_PAGE_THRESHOLD = 2` and playing with toggling orientation and margins in the bottom menus... :(
```
 03/07/19  22:11:23 Battery level changed : 90 > 89
 03/07/19  22:12:28 Battery level changed : 89 > 88
 03/07/19  22:14:42 Battery level changed : 88 > 87
1329  1321 root       7:36   9:54  R     36m 133m reader.lua (7m36 cpu over 9m54)
```
No idea why. But two pages mode on a small kobo is pretty pretty :)

Logs coming up after a fresh reboot.

**Comment by NiLuJe** [comment]
Hmm, the last couple of times I managed to get the JIT to spaz out was also when playing with the bottom menu... But that was in a CBZ. >_<".

**Comment by poire-z** [comment]
Yes, GloHD.
crash.log excerpts, first start after boot, launched by KSM07, exit KOReader, restart it, exit again:
```
Variable fb info: 1448x1072 (1472x2304), 16bpp @ rotation: 0 (Upright, 0Â°) [latin1 terminal, no worry]
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes

Switching fb to 8bpp . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 0 (Upright, 0Â°)

Variable fb info: 1448x1072 (1472x2304), 8bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 1472 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/07/19-22:31:25
 [*] Version: v2019.02-173-g5992bb6_2019-03-05

SDL2 not loaded:    ./setupkoenv.lua:33: Not able to load dynamic library: SDL2
SDL not loaded: ./setupkoenv.lua:33: Not able to load dynamic library: SDL
FB: computed size: 3391488
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1472
FB: xres         : 1448
FB: xres_virtual : 1472
FB: yres         : 1072
FB: yres_virtual : 2304
FB: bpp          : 8
03/07/19-22:31:25 INFO  initializing for device Kobo_alyssum
03/07/19-22:31:25 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:1009).


03/07/19-22:31:33 INFO  quitting uimanager
Variable fb info: 1448x1072 (1472x2304), 8bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 1472 bytes

Switching fb to 16bpp . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 0 (Upright, 0Â°)

Variable fb info: 1448x1072 (1472x2304), 16bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes
Variable fb info: 1448x1072 (1472x2304), 16bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes

Switching fb to 8bpp . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 0 (Upright, 0Â°)

Variable fb info: 1448x1072 (1472x2304), 8bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 1472 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/07/19-22:31:38
 [*] Version: v2019.02-173-g5992bb6_2019-03-05

SDL2 not loaded:    ./setupkoenv.lua:33: Not able to load dynamic library: SDL2
SDL not loaded: ./setupkoenv.lua:33: Not able to load dynamic library: SDL
FB: computed size: 3391488
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1472
FB: xres         : 1448
FB: xres_virtual : 1472
FB: yres         : 1072
FB: yres_virtual : 2304
FB: bpp          : 8
03/07/19-22:31:38 INFO  initializing for device Kobo_alyssum
03/07/19-22:31:38 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:1036).

03/07/19-22:31:43 INFO  quitting uimanager
Variable fb info: 1448x1072 (1472x2304), 8bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 1472 bytes

Switching fb to 16bpp . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 0 (Upright, 0Â°)

Variable fb info: 1448x1072 (1472x2304), 16bpp @ rotation: 0 (Upright, 0Â°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes
```

> Do you get anything relevant in the logs (in debug mode, I guess), when those touches get sent to the void?

I don't put logs in debug mode - and given the time it needs to happen, debug mode logs could fill my SDCard :) (or I just don't like having it grow that fast).
But I still contemplate the input code from time to time, hoping something would jump at me. Might be a timestamp issue, or stuck in some pan or hold state... or just hardware...

**Comment by poire-z** [comment]
Another strange thing/edge case noticed (nothing relevant to the above issues):
Emulator in portrait mode: bottom menu orientation shows: portrait
Full screen window > landscape on my laptop screen (2 pages): bottom menu orientation shows: landscape.
Hit on bottom menu orientation "portrait": it 180° the previous landscape mode. bottom menu shows: landscape.
Hit on bottom menu orientation "landscape" (even if it's the one highlighted): you're switched to some rotated text (so, portrait). Bottom menu shows "portrait". Hit "portrait": you're back into landscape.

Some kind of missed state when the rotation was not caused by the toggle, but by window resize - or something else :)

**Comment by NiLuJe** [comment]
@poire-z : Yeah, the current screen mode (i.e., landscape/portrait) possibly doesn't get updated in these cases, which would desync the buttons behavior (possibly since my Forma changes, since they now always try to do something).

(Haven't actually checked anything, so that's just a random guess ;)).

**Comment by poire-z** [comment]
> Hmm, the last couple of times I managed to get the JIT to spaz out was also when playing with the bottom menu... But that was in a CBZ. And rotation was indirectly involved, because I'm usually in Landscape when testing that, although I only recall it actually dying a fair bit of time after switching back to Portrait

Got that 3-4 times today, while testing some 2-pages mode patches on my kobo - mostly changing margins and toggling rotation (and toggling a new pages: one|two). But once, it seemed fine, and began getting stuck when I put orientation back to portrait).

I checked it happens too when I put the progress bar from grey back to black - so that's probably not additional invert/diming slow path with grey.

I wonder if some jit tuning might be needed, as we lose what you set for 16bpp in #4157 when we are now in 8bpp.
I checked I can not reproduce the translucent Hold-on-file issue (#4137) in 8bpp (so, without `jit.opt.start("loopunroll=45")`.
It's less easy to reproduce than the Hold-on-file issue unfortunatly...

**Comment by NiLuJe** [comment]
I'm seriously considering just switching to the C blitbuffer... >_<".

Just have to implement nightmode at the EPDC level instead of the BB, since that doesn't work with cbb.

**Comment by NiLuJe** [comment]
@poire-z : Just to double-check: are the FBInk messages during an OTA update rotated/centered properly on your device?

**Comment by poire-z** [comment]
I don't do OTA, but executing `./fbink -q -y -7 -pmh 'Preparing local OTA package"` over SSH, after a fresh reboot and starting koreader with a book in classic portrait mode displays ... as it does for @Frenzie as on his drawing on first post and on his video :| So, not as intended I suppose.

**Comment by poire-z** [comment]
And for info, I never launch Nickel. The only thing that is *ickel that is launched in my KSM07 /etc/init.d/rcS is 
```
/usr/local/Kobo/pickel can-upgrade
CAN_UPGRADE=$?
```
(dunno why I let that in - is it worth keeping if that pickel thing does set up stuff ?)

**Comment by NiLuJe** [comment]
@poire-z: Thanks! That makes perfect sense, I'd have been mightily confused it it were actually printed properly ;).

I just have to double-check how it behaves on the Forma then, but otherwise the commit mentioned above should fix it ;).

Later tonight, as it's currently charging, because, err, it made a trip in extreme conditions.. :D
![IMG_20190302_112309](https://user-images.githubusercontent.com/111974/54075725-e7a50e80-42a2-11e9-958c-caa4ddb5efc2.jpg)

**Comment by NiLuJe** [comment]
@poire-z: I was wondering about what the upgrade check actually *does*, but I never bothered to check ;).

In any case, it's potentially irrelevant here: either it *does* also setup the fb properly, or KSM does it itself.
The end result matches on-animator, which is what we care about ;).

**Comment by NiLuJe** [comment]
Here's a fixed binary, if you want to double-check.

[fbink-1.12.0-1.tar.gz](https://github.com/koreader/koreader/files/2948734/fbink-1.12.0-1.tar.gz)

**Comment by poire-z** [comment]
That binary makes it displayed at the bottom, horizontally and readable, so as intended I guess :)
(That Forma screen is not as white as snow it seems :)

**Comment by NiLuJe** [comment]
Fantastic, thanks ;).

(Yeah, even if you forget about a "pure" contrast ratio, the screen is actually somewhat grainy, which actually works out pretty well in practice!).

**Comment by poire-z** [comment]
I played quite a lot with margins and orientation since earlier, after having set in reader.lua `jit.opt.start("loopunroll=45")` - and I haven't got stuck since. I'll continue playing while keeping it.

So, you may want to add that loopunroll even with 8bpp - as it hadn't really hurt people in the 16bpp era - if it can prevent such bad cpuloop (I got corrupted settings.reader.lua + .old once ... had to redo all my gestures :|)

**Comment by Frenzie** [comment]
@NiLuJe Also something I should test?

**Comment by NiLuJe** [comment]
@Frenzie : No need, we've got the same device ;). Thanks!

@poire-z: Good to know, might as well make it mandatory (since that was @ 32bpp on my end ;)) if it helps here, too...

**Comment by poire-z** [comment]
@Frenzie : what's your status regarding the release? Ready, waiting for some issue(s) to be fixed, or translations, or skipping it?

(I'm holding a few things, just want to know how long I should :)

**Comment by Frenzie** [comment]
@poire-z I might tag it tonight, probably tomorrow. I haven't quite finished the release notes.

**Comment by poire-z** [comment]
OK, and no hurry really. (It's just that if you'd have some blockers that would need time to be resolved, I would have slipped in a few (medium risk) things - but if it is fine, no pb waiting.)

**Comment by poire-z** [comment]
@NiLuJe @Frenzie : when you have a bit of time, can you try having a look at https://github.com/koreader/koreader/issues/4752#issuecomment-470708895 ?

I had some quick random tries at sending a SwapScreenMode event in the SDL_WINDOWEVENT_RESIZED handler, tweaking device/sdl/device.lua, base/ffi/framebuffer_SDL2.0.lua ... to only get things even messier :)

I guess it's related to #4414 and its onSetScreenMode/onSwapScreenMode tweaks (the issue is the same with PDF or EPUB), but I don't know if all that's there is just fine, and if it's not better to look at screen size and rotations modes in device/sdl/device.lua or base/ffi/framebuffer_SDL2.0.lua (I get the feeling the emulator is a special case, vs devices with a fixed screen/native rotation, so may be it's there tweaks are needed).
But I have a hard time getting into these, so maybe one of you that have played with them before will see a simple obvious fix by there :)

**Comment by NiLuJe** [comment]
AFAIK, the handlers are fine. There may be a bad interaction with whatever happens on screen resize, yeah.

**Comment by poire-z** [comment]
Nothing more clever than these stupids:

```diff
--- a/frontend/device/sdl/device.lua
+++ b/frontend/device/sdl/device.lua
@@ -186,18 +186,25 @@ function Device:init()
                 if dropped_file_path and dropped_file_path ~= "" then
                     local ReaderUI = require("apps/reader/readerui")
                     ReaderUI:doShowReader(dropped_file_path)
                 end
             elseif ev.code == SDL_WINDOWEVENT_RESIZED then
                 device_input.device.screen.screen_size.w = ev.value.data1
                 device_input.device.screen.screen_size.h = ev.value.data2
+                local prev_size = device_input.device.screen:getSize()
+                local prev_screen_mode = device_input.device.screen:getScreenMode()
                 device_input.device.screen.resize(device_input.device.screen, ev.value.data1, ev.value.data2)

                 local new_size = device_input.device.screen:getSize()
+                local new_screen_mode = device_input.device.screen:getScreenMode()
                 logger.dbg("Resizing screen to", new_size)
+                if prev_screen_mode ~= new_screen_mode then
+                    UIManager:broadcastEvent(Event:new("SwapScreenMode", prev_screen_mode, true))
+                    -- with all 2x2 combinations of prev/new_screenmode & false/true :)
+                end

                 -- try to catch as many flies as we can
                 -- this means we can't just return one ScreenResize or SetDimensons event
                 UIManager:broadcastEvent(Event:new("SetDimensions", new_size))
                 UIManager:broadcastEvent(Event:new("ScreenResize", new_size))
                 --- @todo Toggle this elsewhere based on ScreenResize?
```
And this, expecting the generic framebuffer to magically solve that by re-setting its rotation flags for the new geometry:
```diff
--- a/ffi/framebuffer_SDL2_0.lua
+++ b/ffi/framebuffer_SDL2_0.lua
 function framebuffer:resize(w, h)
     w = w or SDL.w
     h = h or SDL.h

     if not self.dummy then
         self:_newBB(w, h)
         SDL.w = w
         SDL.h = h
     else
         self.bb:free()
         self.bb = BB.new(600, 800)
     end

     if SDL.texture then SDL.destroyTexture(SDL.texture) end
     SDL.texture = SDL.createTexture(w, h)

     self.bb:fill(BB.COLOR_WHITE)
     self:refreshFull()
+    framebuffer.parent.init(self)
 end
```
(the bb gets trashed, but the fb isn't (until my not-helping my parent.init())

**Comment by NiLuJe** [comment]
Hmm. Will probably have to try on the emulator one of these days ;).

**Comment by Frenzie** [comment]
There's some fairly stupid hardcoded logic in there that assumes when the framebuffer is wider than it is high, it must be landscape. See https://github.com/koreader/koreader-base/blob/53ff64833621a1d85c04111ac7c05094f585fe0d/ffi/framebuffer.lua#L78-L90

There could be some relationship there.

If it's about the new gyrometer stuff, I haven't played around with that. (I suppose I could on Android if I really wanted to.)

**Comment by poire-z** [comment]
> assumes when the framebuffer is wider than it is high, it must be landscape

I think we still want that :) If I resize the emulator from portrait to full screen, I obviously don't want it to be rotated, and I want it to advertise itself to the higher level code as being landscape, so all the landscape features/tweaks are enabled (dual pages in the bottom config, 4x2 mosaic covers instead of 3x3...)

**Comment by ptrm** [comment]
> I think we still want that :) If I resize the emulator from portrait to full screen, I obviously don't want it to be rotated

That reminded me of [split screen and pop ups](https://developer.android.com/guide/topics/ui/multi-window) in Android, which can live resize the app changing ratio (though developer can disable them both afair, still I enforce it in developer options)

**Comment by Frenzie** [comment]
> If I resize the emulator from portrait to full screen, I obviously don't want it to be rotated

I must've expressed myself badly, but I don't consider this good.

![Uploading Screenshot_2020-01-11_12-26-53.png…]()

**Comment by Frenzie** [comment]
PS That happens because of startup assumptions, which are kept during resizing.

**Comment by poire-z** [comment]
> > If I resize the emulator from portrait to full screen, I obviously don't want it to be rotated

> I must've expressed myself badly, but I don't consider this good.

I don't know what you mean by "this" :) me not wanting it rotated, or your followup screenshot ?

Anyway, when launched in portrait, and then resized to landscape, I don't get the rotation that your screenshot shows - I get this, expected and right:
<kbd>![image](https://user-images.githubusercontent.com/24273478/72204075-524f4980-3474-11ea-86d5-ce9f98b2b90e.png)</kbd>

But ok, if I have it started with w > h, indeed, it gets into landscape - and there's then another bug: touch is not rotated (bottom menu that should activate from tap on the left, still activate from tap on bottom...)
So, ok, multiple (related or unrelated) issues :)

**Comment by Frenzie** [comment]
Rotating during resizing would be rather stupid of course.

> So, ok, multiple (related or unrelated) issues :)

Well, it's more of a feature than an issue, at least on Kobos and perhaps also older Kindles. But it's really more of a temporary patch that's been bothering me for years, just not quite badly enough to fix it up properly because it's somewhat of an edge case in real use.

That touch isn't adjusted is SDL-specific (because you basically shouldn't have to). On Kobo that's all set up correctly in the device properties.

**Comment by poire-z** [comment]
> at least on Kobos and perhaps also older Kindles

Mhhh, we must not be talking/thinking about the same things... I don't see how my observation on the emulator/SDL can even remotely affect Kobo or Kindle :)

> But it's really more of a temporary patch that's been bothering me for years, just not quite badly enough to fix it up properly because it's somewhat of an edge case in real use.

So, what are you taking about ?! :)

My observation at https://github.com/koreader/koreader/issues/4752#issuecomment-470708895 is not a feature/improvement: it's a bug with bottom toggle `portrait|landscape` not working correctly, on the resizable emulator/SDL only.
(I remember I previously said when you introduced that SDL resize or AppImage I did not care about supporting it :) but that portrait|landscape is may be the only little thing bothering me :)

**Comment by Frenzie** [comment]
> Mhhh, we must not be talking/thinking about the same things... I don't see how my observation on the emulator/SDL can even remotely affect Kobo or Kindle :)

That's why it all works how it works, with stupid assumptions about portrait and landscape.

The toggle will probably work if you replace the assumption with tracking what we actually know, along these lines:
```diff
diff --git a/ffi/framebuffer.lua b/ffi/framebuffer.lua
index b20881a..60efe15 100644
--- a/ffi/framebuffer.lua
+++ b/ffi/framebuffer.lua
@@ -305,10 +305,13 @@ function fb:getRotationMode()
 end
 
 function fb:getScreenMode()
-    if self:getWidth() > self:getHeight() then
-        return "landscape"
-    else
+
+    if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
+       or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED
+    then
         return "portrait"
+    else
+        return "landscape"
     end
 end
```

**Comment by Frenzie** [comment]
The point is rather that it *doesn't* affect Kobo and Kindle, is what I mean.

**Comment by poire-z** [comment]
> The toggle will probably work if you replace the assumption with tracking what we actually know, along these lines:

Well, with that, at least the toggle toggles :) (when you tap, it switches to the other - it didn't previously) but portrait and landscape are inverted (when you get full screen, it still shows "portrait" and tap rotate the page and "landscape" is highlighted while we are in portrait).

That stupid trick makes things messier: :)
```lua
    local landscape_like = self:getWidth() > self:getHeight()
    if self.cur_rotation_mode == self.ORIENTATION_PORTRAIT
       or self.cur_rotation_mode == self.ORIENTATION_PORTRAIT_ROTATED
    then
        -- return "portrait"
        return landscape_like and "landscape" or "portrait"
    else
        -- return "landscape"
        return landscape_like and "portrait" or "landscape"
    end
```
