### ISSUE TITLE
The space between lines in the table of contents view

### ISSUE THREAD

**Issue by mayabtlaloc** [koreader/koreader#4757]
Could be reduced, or an option to customize it The space between lines in the table of contents view?. It has too much “Line spacing”, which results in having to navigate in a large number of pages. Thanks.
![table of contents line spacing very large](https://user-images.githubusercontent.com/2880036/53999672-eab8c700-4109-11e9-900d-add9bb1e349f.jpg)

**Comment by poire-z** [comment]
Not obvious, but what you set in File browser menu > 1st tab > `Items per page` applies to all these kinds of panels (Files list, TOC, Bookmarks...). You probably have it at 8. I have it set at 20.

**Comment by mayabtlaloc** [comment]
It is a good solution but, unfortunately the size of the font is reduced too much, And in long file names it becomes even smaller, almost microscopic. This is a problem for many people who we have tired eyesight and vision problems.
Is there the possibility of increasing the font size in the lists without sacrificing the number of items per page?
It's something like the filename classic view was before. Could you include an option to have the classic old view?. In which you can have a large font with a large number of items per page, due to a more tight Space between lines. Thanks.
![very small font](https://user-images.githubusercontent.com/2880036/54047354-79762400-419c-11e9-9f6e-99d54d839811.jpg)
![classic old view](https://user-images.githubusercontent.com/2880036/54047403-9579c580-419c-11e9-8a3a-0caf5e05d357.jpg)

**Comment by mayabtlaloc** [comment]
Long names look even smaller. 
![20190309_092712](https://user-images.githubusercontent.com/2880036/54073637-68d2b600-424f-11e9-8b6a-47c7f24ffcf4.jpg)

How can you see large font keeping more items per page?

**Comment by poire-z** [comment]
Currently, you can't, there is no option to tweak the algorithm.

But if you feel like editing a file and playing, you can try adding into `frontend/ui/widget/menu.lua` these 2 lines in green around line 145  (without the `+` at the beginning), and experiment with other values than this `30`, depending on what you set for _item per page_:
```diff
 function MenuItem:init()
+    self.font_size = 30
+    self.single_line = true
     self.content_width = self.dimen.w - 2 * Size.padding.fullscreen
     local shortcut_icon_dimen = Geom:new()
     if self.shortcut then
```

**Comment by mayabtlaloc** [comment]
Perfect poire-z!!, I did not think it could be changed so much by adding two simple lines.
Thank you very much, very grateful for the great work you are doing with all your team.
