### ISSUE TITLE
Have both status bars showing simultaneously by default

### ISSUE THREAD

**Issue by protist** [koreader/koreader#4762]
* KOReader version: v2019.02
* Device: Kobo H2O

#### Issue

Is it possible to show both status bars by default? Every time I open a new book, it seems to default back to the single lower status bar. I like the lower bar for its copious information, and I like the upper bar because it shows the title of the book.

I can show both status bars by opening the "quick settings menu" down the bottom, and setting `Progress bar` to `Full`. This shows the top bar, but hides the bottom bar. I then have to re-enable the bottom bar. It's even fiddlier for me because I have `DTAP_ZONE_MINIBAR` turned off. This dual-bar setting lasts indefinitely for the current book, but needs to be redone for each new book.

#### Steps to reproduce

1. Attempt to show both status bars by default for all books.

**Comment by Frenzie** [comment]
You can set defaults by long-pressing, although there may not be a way to do both.

**Comment by KenMaltby** [comment]
There is this:

-- crereader progress bar
-- 0 for top "full" progress bar
-- 1 for bottom "mini" progress bar
DCREREADER_PROGRESS_BAR = 1
in defaults.lua, of course it might have moved.  It might not work for an existing book, but could work on the newly opened ones.

**Comment by protist** [comment]
> You can set defaults by long-pressing, although there may not be a way to do both.

@Frenzie I knew of this with "normal" top-menu items, but didn't realise it also applied to the lower menu. As per my first post, normally the first part of my procedure is setting `Progress bar` to `Full` in the lower menu, which brings up the top status bar. I now long-pressed this. Usually I need to get the lower status bar back with the "Gear" menu >`Status bar` > `Toggle mode`. I couldn't seem to set this as a default with a long press. However, for some reason, after setting only the first part as a default, both bars are showing as default in new books.

@KenMaltby After the above, it's now working. I checked `defaults.lua` after making the changes, which contained `DCREREADER_PROGRESS_BAR = 1`. I don't exactly understand; these settings seem to suggest that the full and mini bars are mutually exclusive. Anyway, it seems to work. Thanks to you both.
