### ISSUE TITLE
koreader crashes on attempt to invoke the top menu

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4763]
* KOReader version: http://build.koreader.rocks/download/nightly/v2019.02-180-g2536cc2_2019-03-08/
* Device: Kobo Glo HD

#### Issue
TONIGHT's NIGHTLY UPDATE v177>v180 IS DEFECTIVE!!!
I am not able to invoke the top menu. After I tap on top 2 cm of my screen, I see "KOReader exited irregularly", "do you want to turn wifi off? yes/no", and after 10 seconds I see Powered Off

#### Steps to reproduce
Just tap on the stripe where you expect the menu will appear

#### Manual steps to roll back the version 
- downloaded the prev version (I do an OTA update very frequently and I recall this version was printed BEFORE the new broken 180 was downloaded by the OTA updater)
- renamed the current D:\.adds\koreader to D:\.adds\koreader180-crashes
- unpacked http://build.koreader.rocks/download/nightly/v2019.02-177-g2c98c81_2019-03-07\koreader-kobo-arm-kobo-linux-gnueabihf-v2019.02-177-g2c98c81_2019-03-07.zip/koreader folder into D:\.adds\koreader
- clicked on "koreader" in KSM09
- everything went back to normal, the top menu works in the version 177
- copied from the crashy v180 to v177:
D:\.adds\koreader\data\dict\*
D:\.adds\koreader\settings\*
D:\.adds\koreader\history\*
(where all my history of the opened books is kept? so that I can copy it from my old crashy folder to the rolled back version?)

#### Switching between versions
as I see, KSM 09 has "toggle btw full and short menu" - this is very useful!
- I toggled to the full menu
- there is a new item "koreader additions" under "koreader"
- "select koreader version"
- I see my "koreader" with v177 and "koreader180-crashes" with v180
- that's cool !!
- can the OTA Upgrader ask the user if I want to have a backup before upgrade, please?

#### SUGGESTIONS
- having an "koreader (last working version № such&such)" in KSM09 would be very useful, as after a crashy OTA upgrade I have no ability to do anything. probably during the OTA update, prior to "koreader will update on next koreader restart", the OTA updater could leave a copy of the previous version by renaming the folder? I know it's additional ~65Mb of space used (+97Mb in D:\.adds\koreader\cache ?...);
- having a "roll back koreader to the previous version № such&such" would be also useful, this menu item / script can also be created by OTA updater for KSM09 to pick them up and;
- the depth of the backups = 1 would be enough (only one last version is kept); the previous backup can be deleted along with activating the new OTA-downloaded version;

##### `crash.log`
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/09/19-09:27:00
 [*] Version: v2019.02-180-g2536cc2_2019-03-08

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:30: Not able to load dynamic library: SDL2
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
SDL not loaded:	./setupkoenv.lua:30: Not able to load dynamic library: SDL
ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
FB: computed size: 3391488
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1472
FB: xres         : 1448
FB: xres_virtual : 1472
FB: yres         : 1072
FB: yres_virtual : 2304
FB: bpp          : 8
03/09/19-09:27:01 INFO  initializing for device Kobo_alyssum
03/09/19-09:27:01 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:1225).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
PING 192.168.100.1 (192.168.100.1): 56 data bytes
64 bytes from 192.168.100.1: seq=0 ttl=64 time=19.808 ms

--- 192.168.100.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 19.808/19.808/19.808 ms
[Sat Mar  9 09:27:01 EET 2019] restore-wifi-async.sh: Restarting WiFi
03/09/19-09:27:02 INFO  Loading plugins from directory: plugins
03/09/19-09:27:02 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
03/09/19-09:27:02 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
03/09/19-09:27:03 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
udhcpc (v1.22.0.kobo) started
03/09/19-09:27:03 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin kobolight at plugins/kobolight.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
03/09/19-09:27:03 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
Sending discover...
Sending select for 192.168.100.31...
Lease of 192.168.100.31 obtained, lease time 259200
adding dns 192.168.100.1
[Sat Mar  9 09:27:05 EET 2019] restore-wifi-async.sh: Restarted WiFi
03/09/19-09:27:06 INFO  opening file /mnt/onboard/_books-kobo/1984 RoadsidePicnic Sheckley/ANIMAL FARM - George Orwell.epub
03/09/19-09:27:07 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSansCJKsc-Regular.otf>
03/09/19-09:27:07 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
03/09/19-09:27:07 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
./luajit: frontend/ui/widget/menu.lua:391: attempt to index local 'dimen' (a nil value)
stack traceback:
	frontend/ui/widget/menu.lua:391: in function 'getGesPosition'
	frontend/ui/widget/menu.lua:397: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:256: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/uimanager.lua:632: in function 'sendEvent'
	frontend/ui/uimanager.lua:153: in function '__default__'
	frontend/ui/uimanager.lua:966: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1027: in function 'handleInput'
	frontend/ui/uimanager.lua:1071: in function 'run'
	./reader.lua:224: in main chunk
	[C]: at 0x00013b61
Variable fb info: 1448x1072 (1472x2304), 8bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 1472 bytes

Switching fb to 16bpp . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 0 (Upright, 0°)

Variable fb info: 1448x1072 (1472x2304), 16bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes

**Comment by Frenzie** [comment]
Unintended side effect of #4733. It might have to be reversed for the moment until the whole thing can be rewritten to be more like FileManagerHistory.
