### ISSUE TITLE
Koreader crashs if I try to open superior menu

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#4766]
* KOReader version:  started at this version v2019.02-180-g2c98c81_2019-03-07
* Device: Kindle paperwhite

#### Issue
Koreader crashs if I select the superior menu (sometimes it doesn't crash, but it does 99% of time)

##### `crash.log` (if applicable)

---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/09/19-23:21:33
 [*] Version: v2019.02-180-g2536cc2_2019-03-08

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:30: Not able to load dynamic library: SDL2
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
SDL not loaded:	./setupkoenv.lua:30: Not able to load dynamic library: SDL
ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
FB: computed size: 6684672
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1088
FB: xres         : 1072
FB: xres_virtual : 1088
FB: yres         : 1448
FB: yres_virtual : 6144
FB: bpp          : 8
03/09/19-23:21:34 INFO  initializing for device KindlePaperWhite3
03/09/19-23:21:34 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:5718).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
03/09/19-23:21:35 INFO  opening file /mnt/us/documents/Informativos Dizer o Direito/Informativos STJ 2018-2017 640-598.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
03/09/19-23:21:36 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
03/09/19-23:21:36 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
03/09/19-23:21:36 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: z
ffi.load: sqlite3
03/09/19-23:21:36 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
03/09/19-23:21:36 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
03/09/19-23:21:36 INFO  setting zoom mode to contentwidth
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
./luajit: frontend/ui/widget/menu.lua:391: attempt to index local 'dimen' (a nil value)
stack traceback:
	frontend/ui/widget/menu.lua:391: in function 'getGesPosition'
	frontend/ui/widget/menu.lua:397: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:256: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/uimanager.lua:632: in function 'sendEvent'
	frontend/ui/uimanager.lua:46: in function '__default__'
	frontend/ui/uimanager.lua:966: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1027: in function 'handleInput'
	frontend/ui/uimanager.lua:1071: in function 'run'
	./reader.lua:224: in main chunk
	[C]: at 0x000139a9
lipc-wait-event exited normally with status: 0

**Comment by NiLuJe** [comment]
c.f., #4763, will be fixed in tomorrow's nightly (i.e., in roughly 4 hours).
