### ISSUE TITLE
enhancement: Postscript support

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4767]
Many scientific papers are published as .ps files.  There exists open source PostScript rendering software (Ghostscript) - is there any specific reason why KOReader doesn't read such files?

I know one can convert - but that argument holds for all-but-one document types, and KOReader clearly has chosen not to go that minimalistic way.

Maybe modules would be the way to go?  KOReader could then have modules for many different formats, and users could decide which ones to install - maximum flexibility with minimum space usage.

**Comment by Frenzie** [comment]
It would be more accurate to say that some scientific papers are optionally available in that format, in addition to PDF.

Also see https://flameeyes.blog/2019/01/23/why-do-we-still-use-ghostscript/

> is there any specific reason why KOReader doesn't read such files?

Time and effort.

**Comment by Biep** [comment]
Aha - so I am showing my age.  My whole library of electronically collected scientific papers is in PostScript.
Calbre seems to have a conversion plug-in - but it doesn't even automatically load .ps documents.
(It doesn't load .pptx either.)
Thanks!

**Comment by hugleo** [comment]
No need to use Calibre, you can convert all your files at once in batch. Worth for ps as to .pptx. You just need to use the right tool.

**Comment by pazos** [comment]
> Many scientific papers are published as .ps files. There exists open source PostScript rendering software (Ghostscript) - is there any specific reason why KOReader doesn't read such files?

Postscript is targeted for publishers, not for end users. Its intended use is to print content. I won't dissapear as most profesional printers use that, event CUPS is using postscript as an intermediate language (and delegate the render on a software rasterizer for most consumer printers).

**Comment by Biep** [comment]
> No need to use Calibre, you can convert all your files at once in batch. Worth for ps as to .pptx. You just need to use the right tool.

Any recommendation?
(I am using Calibre anyway to maintain my library, but am interested in the best batch convert tool.)

**Comment by Frenzie** [comment]
I don't know what calibre does, but I figure ps2pdf should do the job just fine.

**Comment by hugleo** [comment]
Are sure that you is using the last calibre version?
Looks like should be fixed in 2012: https://bugs.launchpad.net/calibre/+bug/1035656

**Comment by Biep** [comment]
I regularly update Calibre (not every week, but once a month or so).  Am not in a position at the moment to check things - which is also why I waited answering you -, but once I am again I intend to report the exact version.
