### ISSUE TITLE
Screen unresponsive on start when start with folder shortcuts is enabled

### ISSUE THREAD

**Issue by KernelPainc** [koreader/koreader#4768]
* KOReader version: 2019.3
* Device: Kobo H2O2

#### Issue
After updating to the latest version, the screen becomes semi-responsive. By this I mean the low battery warning dialogue dismiss button works, but no other gestures or touching on the file manager does anything. Previously I had the reader set to open on the folder shortcuts menu, was this reworked in the latest update?

Sleeping / waking works as normal

#### Steps to reproduce

Update device to latest version.
Turn on.

##### `crash.log` (if applicable)
N/A

**Comment by Frenzie** [comment]
What version are you actually running? The thing is that the stable build actually isn't available yet. Of course the latest nightly will make virtually no discernible difference.

**Comment by KernelPainc** [comment]
I think I had it set to the development channel, but had not done an ota update for a while.

I can double check in about 18 hours

**Comment by poire-z** [comment]
No issue for me in my classic usage with the latest artifacts. But:

> Previously I had the reader set to open on the folder shortcuts menu, was this reworked in the latest update?

I just set my emulator to `Start with: folder shortcuts`, and it's indeed un-tapable after a restart :(
Had to remove `["start_with"] = "folder_shortcuts"`, from my [settings.reader.lua](url)

Probably related to #4764 refactoring.

**Comment by NiLuJe** [comment]
No issues on a Kindle PW2, an H2O and a Forma, FWIW (yes, we had fun over on gitter tonight ;p).

**Comment by codex-hex** [comment]
UI freezes sometimes but when ı open some epub touch freeze.What have you done guys?

**Comment by Frenzie** [comment]
@codex-hex Is there any more information you could share? That wouldn't be related to this highly localized issue with "start with shortcuts".

**Comment by codex-hex** [comment]
I will give you my serial output as soon as possible.But as I said UI freezes sometimes.what is certain is every trying to open an epub file make my touchscreen freeze.
Sorry for my fcking eng. guys.I love you and your efforts so much.
