### ISSUE TITLE
[Android 9.x]: Bottom of Screen being cut-off on devices with notch

### ISSUE THREAD

**Issue by nvllsvm** [koreader/koreader#4769]
* KOReader version: `v2019.02-182-g7c2df53_2019-03-10`
* Device: `OnePlus 6T (Android 9.0)`

#### Issue
The bottom of KOReader is cutoff. The phone I'm using does have a notch and seems to force fullscreen apps to show underneath it.
![screen](https://user-images.githubusercontent.com/6550543/54092294-df130d80-4360-11e9-8afe-5a11ce4ca25e.png)

#### Steps to reproduce
Open app and see that the bottom of the app is off-screen.

**Comment by pazos** [comment]
1 - enable android debug bridge
2 - quit the program, run `adb logcat luajit-launcher:V KOReader:I *:S` and open the program again.
3 - attach the log here

we probably need to blacklist models with the notch or something

**Comment by pazos** [comment]
Ok, I see a new api (28) stuff https://developer.android.com/reference/android/view/WindowInsets#getDisplayCutout().

Sadly we cannot target api 28 without:

https://github.com/koreader/android-luajit-launcher/issues/60
https://github.com/koreader/android-luajit-launcher/issues/129

So a workaround needs to be done for each device (which is awful).

**Comment by nvllsvm** [comment]
`adb logcat luajit-launcher:V KOReader:I '*:S'` - [log.txt](https://github.com/koreader/koreader/files/2950136/log.txt)

Phone is primarily camera, used low-quality webcam to capture these.
![2019-03-10-184650](https://user-images.githubusercontent.com/6550543/54092660-1edbf400-4365-11e9-8459-288fe5530023.jpg)
![2019-03-10-184703](https://user-images.githubusercontent.com/6550543/54092661-1edbf400-4365-11e9-8ae4-37bf8720fb4c.jpg)

**Comment by pazos** [comment]
@nvllsvm:

thanks for the photo, the device looks nice.

You need to create the file `patch.lua` in koreader folder (`/sdcard/koreader`) with the content:

```lua
local screen = require("android").screen
screen.height = screen.height - x
```

Were x is the number of pixels covered by the notch (which we cannot get ourselves without newer api28 methods). I would suggest starting with a high number (400px) and adjust that number yourself based on the screen feedback.

Bad news: each owner with a "notched" device needs to do the same thing again and again
Good news: the patch.lua is something that survives application updates, so it should be "set & forget".

**Comment by NiLuJe** [comment]
I do have a OnePlus 6, which probably behaves in a similar way ;).

I'm willing to break my promise not to touch Android stuff if need be ;p.

**Comment by NiLuJe** [comment]
Yes it does ;). Switching KOReader to fullscreen obviously works, with the notch eating into the top menu icons, which isn't terribly helpful ^^.

**Comment by NiLuJe** [comment]
80px appear to do the trick on a 6. No idea if they changed the notch on the 6T ;).

**Comment by NiLuJe** [comment]
@pazos: Could that be handled via a UI knob somehow? You'd still have to figure out the height in pixel yourself, true, but it might be slightly less unwieldy than the patch.lua approach?

**Comment by pazos** [comment]
> Could that be handled via a UI knob somehow?

Yep, or whilelist specific devices. But in any case I'm more interested in being able to use latest apis in the long run (say a year or so)

**Comment by nvllsvm** [comment]
Also keep in mind that, even with the correct **x-value**, the rounded corners cut off part of the progress bar. 
![2019-03-11-202139](https://user-images.githubusercontent.com/6550543/54166448-aa27b900-443b-11e9-98a2-9f36966a6b1f.jpg)

The **x-value** can be further increased to fix this, but at the cost of losing screen space. Is there a  patch to increase the margin around the progress bar?

**Comment by NiLuJe** [comment]
I personally switched to the "show everything" variant, and put something fairly useless on the right, but that's kind of a shitty workaround ;p.

**Comment by pazos** [comment]
A whilelist example could be (assuming 80px):

```diff
+local function getNotchHeight()
+    local model = android.getProduct()
+    if model == "OnePlus6TOne" or model == "OnePlus6T" then return 80 end
+    return 0
+end
+

function Device:init()
+    -- if we have a notch don't count its height as available
+    -- this is a workaround, see https://github.com/koreader/android-luajit-launcher/issues/131
+    local notch = getNotchHeight()
+    if notch ~= nil and notch > 0 then
+        local new_height = android.screen.height - notch
+        android.screen.height = new_height
+    end
+

**Comment by NiLuJe** [comment]
Is android.getProduct() logged somewhere? OnePlus have weird model names (i.e., ONEPLUS A6003).

**Comment by pazos** [comment]
yes, it is reported as the device model. So you'll find it in:

```
03-10 18:37:44.775 22435 22451 I KOReader: Android 9 - Pie (API 28) - flavor: rocks
03-10 18:37:44.823 22435 22451 I KOReader:  initializing for device OnePlus6T
03-10 18:37:44.823 22435 22451 I KOReader:  framebuffer resolution: {
03-10 18:37:44.823 22435 22451 I KOReader:     ["h"] = 2340,
03-10 18:37:44.823 22435 22451 I KOReader:     ["w"] = 1080
03-10 18:37:44.823 22435 22451 I KOReader: }
```

**Comment by goodevilgenius** [comment]
@pazos Thank you, thank you, thank you for the workaround. It worked perfectly for me on my LG G7 (100px for me, in case anyone else needs it).

I've been using KO Reader for about a month, but this has been driving me crazy.

**Comment by pazos** [comment]
Now that we can build with gradle and use aar libraries I think I fixed that (at least on Android P emulator). Could you please test that build (remove yours first because signatures don't match) -> https://www.dropbox.com/s/dd4mgtwni9iypjo/koreader-android-arm-linux-androideabi-notch.apk?dl=0

@nvllsvm @NiLuJe @goodevilgenius ?

There is no need to delete patch.lua since it will be ignored on this version. Please report if it works for you (it should work with any kind of "top" notchs from android P onwards)

**the patch on top of current master:**

```diff

diff --git a/launcher/src/org/koreader/launcher/MainActivity.java b/launcher/src/org/koreader/launcher/MainActivity.java
index ee6a9f6..72a4f99 100644
--- a/launcher/src/org/koreader/launcher/MainActivity.java
+++ b/launcher/src/org/koreader/launcher/MainActivity.java
@@ -48,6 +48,8 @@ public class MainActivity extends android.app.NativeActivity
     private ScreenHelper screen;
     private SurfaceView surface;
 
+    private int notch_height = 0;
+
     /** Called when the activity is first created. */
     @Override
     protected void onCreate(Bundle savedInstanceState) {
@@ -173,6 +175,23 @@ public class MainActivity extends android.app.NativeActivity
         super.surfaceDestroyed(holder);
     }
 
+    /** Called when the view was atached to a window */
+    @Override
+    public void onAttachedToWindow() {
+        super.onAttachedToWindow();
+        Logger.d(TAG, "view attached to a window");
+        if (SDK_INT >= Build.VERSION_CODES.P) {
+            android.view.DisplayCutout cutout;
+            cutout = getWindow().getDecorView().getRootWindowInsets().getDisplayCutout();
+            if (cutout != null) {
+                int top_pixels = cutout.getSafeInsetTop();
+                if (notch_height != top_pixels) {
+                    notch_height = top_pixels;
+                }
+            }
+        }
+    }
+
     /** Called on permission result */
     @Override
     public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
@@ -356,7 +375,11 @@ public class MainActivity extends android.app.NativeActivity
 
     @SuppressWarnings("unused")
     public int getScreenHeight() {
-        return screen.getScreenHeight();
+        if (SDK_INT >= Build.VERSION_CODES.P) {
+            return (screen.getScreenHeight() - notch_height);
+        } else {
+            return screen.getScreenHeight();
+        }
     }
```

**Comment by NiLuJe** [comment]
@pazos : Flawless victory! :tada: :heart:

**Comment by nvllsvm** [comment]
Works fine here too!

**Comment by pazos** [comment]
Will be included in https://github.com/koreader/koreader/pull/5096

the patch.lua thingy won't be removed until https://github.com/koreader/koreader/pull/5096, so the notch height will be substracted twice. This is the time to remove your patch file :+1:
