### ISSUE TITLE
Can not work in /system/

### ISSUE THREAD

**Issue by zaoqi-unsafe** [koreader/koreader#4770]
* KOReader version: 2019.02
* Device: jdread venus(T65S)

#### Issue

KOReader won't start if is installed as a system application

#### Steps to reproduce

* copy koreader.apk to /system/app
* copy lib/armv7a/* to /system/lib

**Comment by pazos** [comment]
It is a limitation for applications based on https://github.com/koreader/android-luajit-launcher. I have no idea why and I don't care 😄 

This won't affect normal users but integrators willing to add KOReader to a specific rom.

@zaoqi-unsafe if you want to take a look at it you will probably need the logs `adb logcat luajit-launcher:V AndroidRuntime:I *:F`

**Comment by Frenzie** [comment]
Part of the problem may be that lib/armv7a/* would only contain the luajit-launcher libs.

**Comment by pazos** [comment]
Keeping track of this issue on the android-luajit-launcher repo. Closing this now.
