### ISSUE TITLE
Screensaver: Last book's cover renders differently from original image

### ISSUE THREAD

**Issue by CriticalPower** [koreader/koreader#4774]
* KOReader version: 2019.03.1
* Device: Kobo Forma

#### Issue
Since installing the March stable update, whenever I enter screensaver mode and choose to display the last book cover, the image shown is a bit different from the original one. Please see images below. Nothing major, but curious to see if I'm doing anything wrong.

"White background behind message and images" is disabled, and does not seem to have any effect (likely because I chose to "Stretch covers and images to fit screen").

I believe the problem first emerged in a February nightly. I went back to the stable version and everything was fine then. Thank you for any thoughts!

#### Steps to reproduce
Enable screensaver and select last book cover.

![Original](https://user-images.githubusercontent.com/48442518/54129002-982f2180-440d-11e9-93ee-b0a6b99f7a0e.jpg)

![Screensaver](https://user-images.githubusercontent.com/48442518/54129087-ce6ca100-440d-11e9-9820-7b087d9a6ac6.jpg)

**Comment by Frenzie** [comment]
You'll have to specify the file format. For example, in PDF the "cover" simply means the first page, but in EPUB it means an image specified by the creator.

Could you download the Leaves of Grass EPUB from the test data to see what happens?

https://github.com/koreader/test-data/blob/86eeb0b43d8998d402d203a1ae42d00dbed58037/leaves.epub

Basically for book cover, what you see in Hamburger menu → Book status is the cover that will be shown in screensaver.

There has been no real change to the screensaver since #4095. Last month all we've had was #4541 and #4622.

**Comment by NiLuJe** [comment]
What happens without the "stretch" option?

**Comment by poire-z** [comment]
Hard to say if it's the same image, just converted to 2 bits, black & white (by HW dithering or MuPDF image manipulation?).
Because it's like the grey lines and circles just disappear - but the "Choosing..." text looks to be in the same grey as the lines & circles - so it should have disappeared too :|

**Comment by CriticalPower** [comment]
@Frenzie Leaves of Grass EPUB works fine on the screensaver. In relation to the issue, Hamburger menu → Book status shows the correct cover (which is also the Calibre cover).

@NiLuJe This happens on 2 out of 5 books I have on the device. The two problematic ones display the same behavior with or without the stretch option.

@poire-z You may be up to something here! To me this feels like the same image...just black and white.

Thanks!

![Book Status](https://user-images.githubusercontent.com/48442518/54134221-dc272400-4417-11e9-8072-f71bb50655d5.jpg)

**Comment by Frenzie** [comment]
Good observation by @poire-z. Now that could indeed be a side effect of one of February's changes.

**Comment by NiLuJe** [comment]
Except a cover should *never* be refreshed w/ A2.

(But, yeah, given the pattern that doe slook like what'd happen if rendered w/ FORCE_MONOCHROME).

@CriticalPower : Still haven't told us which format those books are in ;).

**Comment by NiLuJe** [comment]
Also, if you could pull the cover image from the book and send it to me, I could double-check that it's not simply a weird HW dithering quirk.

**Comment by NiLuJe** [comment]
Random lightbulb moment: that *also* looks like what a publisher might use as a *first page*, right after the cover.

Could you double-check that you're indeed using" book cover" and not "first page" as your current screensaver mode?

**Comment by CriticalPower** [comment]
Sure, all are EPUB.

Using "Last book's cover". I was not aware that there's a "First page" option...is that live?

![cover](https://user-images.githubusercontent.com/48442518/54135752-b0596d80-441a-11e9-8cbb-e58ef7ef05cf.jpg)

**Comment by Frenzie** [comment]
No, I think first page is just an FR I have (mainly as fallback when there's no cover).

**Comment by NiLuJe** [comment]
Okay, not an HW dithering quirk, that behaves sanely ;).

And I don't think that's an A1 quirk either, because it's more obvious (halftone patterns, no AA).

**Comment by Frenzie** [comment]
Btw, I figured I'd double check, but that image renders fine as a screensaver on my H2O in regular and stretched mode. Given that it's probably some logic error related to dithering no real surprise, but better safe than sorry. ;-)

**Comment by CriticalPower** [comment]
Here's another book that has a similar issue. Notice the "and" and the subtitle at the bottom fading away.

![cover](https://user-images.githubusercontent.com/48442518/54137620-3f1bb980-441e-11e9-8767-ca498e3724b5.jpg)

![IMG_20190311_163816](https://user-images.githubusercontent.com/48442518/54138194-498a8300-441f-11e9-8cde-a88c4e1ba08f.jpg)

![IMG_20190311_163837](https://user-images.githubusercontent.com/48442518/54137902-c6692d00-441e-11e9-8e73-1f04d095b112.jpg)

**Comment by gerhaher** [comment]
I also have a cover which behaves similar.

This:
![image](https://user-images.githubusercontent.com/32645430/54139559-1d243600-4422-11e9-9454-9cbbebe42a44.png)

Becomes this: 
![IMG_20190311_171819815](https://user-images.githubusercontent.com/32645430/54139597-35945080-4422-11e9-9968-445110a4524b.jpg)

**Comment by NiLuJe** [comment]
@gerhaher : On which device, as that doesn't look like a Forma ;).

**Comment by NiLuJe** [comment]
Shouldn't be dithering related (or at least not entirely), as the cover thumbnail in the Book Status widget is also dithered ;).

**Comment by NiLuJe** [comment]
Speaking of, does it also happen when you do a long tap on the book in the FM > View cover image?

**Comment by NiLuJe** [comment]
Oh, and because I've just found out something strange over on gitter: how are all of you launching KOReader? KSM or KFMon?

**Comment by gerhaher** [comment]
@NiLuJe 

> On which device, as that doesn't look like a Forma ;)

KA1

> Speaking of, does it also happen when you do a long tap on the book in the FM > View cover image?

Yes, but all the black is white instead.

> how are all of you launching KOReader? KSM or KFMon?

KSM

**Comment by NiLuJe** [comment]
Okay, so, not dithering at all, as that's not possible on the KA1 ;).

Next question: Which FW version?

**Comment by NiLuJe** [comment]
I meant the device's FW, not KOReader's version, although that is good to know ;).

**Comment by NiLuJe** [comment]
Okay, with the images as provided, the only weird thing I can reproduce is @gerhaher's PNG being grayscaled in a weird manner (the bottom banner is much fainter than it should be), but absolutely not as broken as in his own picture, though.

So, I'm thinking the next step is providing us with scarmbled versions of the original books to see if there's an extra layer of fun happening in the CRe/Kopt bits...
(There's a Calibre plugin to scramble ePubs, IIRC).

**Comment by CriticalPower** [comment]
@NiLuJe 

> Does it also happen when you do a long tap on the book in the FM - View cover image?

Yes

> How are all of you launching KOReader?

KFMon

Kobo 4.12.12111

**Comment by poire-z** [comment]
You may try (just to see) disabling the new (faster) 8bpp mode on Kobo, and get back to 16bpp or 32bpp as before. Go to file browser, 3rd tab, `Developpers options > Disable forced 8-bit color space`

**Comment by CriticalPower** [comment]
@NiLuJe Does this help?

[Test eBook - Authors.zip](https://github.com/koreader/koreader/files/2953574/Test.eBook.-.Authors.zip)

@poire-z 

> You may try (just to see) disabling the new (faster) 8bpp mode on Kobo

Tried and issue persists

**Comment by NiLuJe** [comment]
You do have to restart KOReader for the bitdepth change to take effect ;).

**Comment by NiLuJe** [comment]
@CriticalPower : It unfortunately also scraps the images, so, nope ;). (My bad, I'd never actually *tested* that pluygin).

**Comment by NiLuJe** [comment]
Good news though, Jackie's awesome, and there's a standalone version which happens to be configurable: https://www.mobileread.com/forums/showpost.php?p=3188419&postcount=2

You'll be able to leave the images alone with that version ;).

**Comment by CriticalPower** [comment]
Good deal! Disabling forced 8-bit color space seems to have solved the issue :)

**Comment by NiLuJe** [comment]
Huh. I'd still be glad to get a semi-scrambled book to repro the issue ;).

Slightly puzzled why I can't reproduce it (or reproduce it the same way) over here... There's *something* wonky somewhere, for sure, though.

@poire-z/@Frenzie: Are the cached cover thumbnails in the SQLite DB used anywhere else than the FM?

**Comment by CriticalPower** [comment]
Yep, will send in a bit!

**Comment by gerhaher** [comment]
> I meant the device's FW, not KOReader's version, although that is good to know ;).

What is "device's FW"? Where can I see that?

Here is a scramble: 
[Stalin's Scribe_ Literature, Am - Brian J. Boeck_scrambled.epub.zip](https://github.com/koreader/koreader/files/2953735/Stalin.s.Scribe_.Literature.Am.-.Brian.J.Boeck_scrambled.epub.zip)

**Comment by NiLuJe** [comment]
@gerhaher : In Nickel's Help/About menu.

As for the scramble, unfortunately, same issue as with @CriticalPower's first file, I'd forgotten to check how the plugin behaved, my bad.
You'll have to use the [standalone version](https://www.mobileread.com/forums/showpost.php?p=3188419&postcount=2), and uncheck "images" in the config.

**Comment by poire-z** [comment]
> Are the cached cover thumbnails in the SQLite DB used anywhere else than the FM?

No. They are only re-used for the FM thumbnails. We get them from document:getCoverPageImage(), and saved the possibly rescaled gzipped blitbuffer for direct re-use:
https://github.com/koreader/koreader/blob/644e0d6440fe06959b92f414aab786bae61682ca/plugins/coverbrowser.koplugin/bookinfomanager.lua#L429-L447

> Does the CRe cache include the rendered full cover?

No. Each time it is asked, crengine just send the image file content unprocessed (so, jpeg or png) to frontend. It's then rendered as a BB by MuPDF:
https://github.com/koreader/koreader/blob/644e0d6440fe06959b92f414aab786bae61682ca/frontend/document/credocument.lua#L237-L244

**Comment by NiLuJe** [comment]
@poire-z : Okay, thanks, that's what I thought I remembered ;).

That'd point towards me having broken something in there recently, because we'd have heard about it from Kindle/PB people otherwise.

**Comment by gerhaher** [comment]
So device FW=Nickel software version? If so, here it is: 4.10.11655

Another try: 
[Stalin's Scribe_ Literature, Am - Brian J. Boeck_scrambled.epub.zip](https://github.com/koreader/koreader/files/2953833/Stalin.s.Scribe_.Literature.Am.-.Brian.J.Boeck_scrambled.epub.zip)

**Comment by poire-z** [comment]
^ On my Kobo, that Stalin book's cover renders, when View full size cover, in nearly full white, unreadable text (except the 2 portraits, in light grey).
In CoverBrowser File Manager, it's more readable, black text on grey bg, but the heads have a black forehead and white hairs :|

**Comment by NiLuJe** [comment]
Haha! It's a CMYK JPEG, which is quirky enough to possibly matter ;).

**Comment by poire-z** [comment]
Mhhh. I get the exact same things after switching to some 2018-12 version. Even after a reboot and only starting that koreader-2018-12...

**Comment by NiLuJe** [comment]
I'm fairly confident turbo-jpeg *should* handle those fine (hell, I have no issues with it w/ stb in FBInk), so this might be fixable ;).

**Comment by poire-z** [comment]
But why the differences? For both full cover and thumbnail covers, we get the jpg from crengine, and scale it with MuPDF?
And what with @CriticalPower book, which seems fixed when switching to 16bpp?

**Comment by CriticalPower** [comment]
Just downloaded the EbookScramble utility. As I use Calibre Portable, I replaced the path in the .bat file with the Calibre installation path but no luck. The routine seems to break as I have a space in my path. Any thoughts, assuming the scrambled file would still be useful?

**Comment by poire-z** [comment]
Yellow circle and lines replacing cover.jpg in the Stalin book:
2019-03 ~~16bpp~~ 8bpp: thumbnail ok (grey lines a circles), full cover bad (black text on white bg)
^ Well, no matter how checked the setting is, and the setting in settings.reader.lua, fbdepth runs and sets me to 8bpp...

**Comment by poire-z** [comment]
> no matter how checked the setting is, and the setting in settings.reader.lua

Ignore that (I don't have settings.reader.lua in koreader dir, so your grep was not greping for it:)

**Comment by poire-z** [comment]
So: Yellow circle and lines.jpg replacing cover.jpg in the Stalin book:
2019-03 8bpp: thumbnail ok (grey lines a circles), full cover bad (black text on white bg)
2019-03 16bpp: thumbnail ok (grey lines a circles), full cover OK

**Comment by poire-z** [comment]
> assuming the scrambled file would still be useful?

@CriticalPower : I guess the images you posted are enough, I can reproduce what you saw with the original book.

**Comment by CriticalPower** [comment]
> @CriticalPower : I guess the images you posted are enough, I can reproduce what you saw with the original book.

Kewl. Thanks @poire-z @NiLuJe and everyone else for all the help.

**Comment by NiLuJe** [comment]
Okay, yup, putting the yellow lines cover into an ePub, I can repro.
I still can't with the very same JPG just on its own, which is mightily weird.

As for the CMYK issue, bad news, turbo-jpeg says you need a CMS to do CMYK <-> RGB (and they're mostly right).

**Comment by NiLuJe** [comment]
Oohkay,

```diff
diff --git a/frontend/ui/screensaver.lua b/frontend/ui/screensaver.lua
index 8c66d2d1..9d5440f6 100644
--- a/frontend/ui/screensaver.lua
+++ b/frontend/ui/screensaver.lua
@@ -258,7 +258,6 @@ function Screensaver:show(event, fallback_message)
                     widget = ImageWidget:new{
                         image = image,
                         image_disposable = true,
-                        alpha = true,
                         height = Screen:getHeight(),
                         width = Screen:getWidth(),
                         scale_factor = not self:stretchImages() and 0 or nil,
@@ -315,7 +314,6 @@ function Screensaver:show(event, fallback_message)
             widget = ImageWidget:new{
                 file = image_file,
                 file_do_cache = false,
-                alpha = true,
                 height = Screen:getHeight(),
                 width = Screen:getWidth(),
                 scale_factor = not self:stretchImages() and 0 or nil,
@@ -339,7 +337,6 @@ function Screensaver:show(event, fallback_message)
             widget = ImageWidget:new{
                 file = screensaver_image,
                 file_do_cache = false,
-                alpha = true,
                 height = Screen:getHeight(),
                 width = Screen:getWidth(),
                 scale_factor = not self:stretchImages() and 0 or nil,
diff --git a/frontend/ui/widget/imageviewer.lua b/frontend/ui/widget/imageviewer.lua
index ddbb23bd..ddfe4b69 100644
--- a/frontend/ui/widget/imageviewer.lua
+++ b/frontend/ui/widget/imageviewer.lua
@@ -348,7 +348,6 @@ function ImageViewer:update()
         file = self.file,
         image = self.image,
         image_disposable = false, -- we may re-use self.image
-        alpha = true,
         width = max_image_w,
         height = max_image_h,
         rotation_angle = rotation_angle,
```

Fixes it, which suggests there's a bug in alphaBlitFrom with a BB8 target.

(Note that not setting this to true ever is mostly a good thing. The only case where it might make sense to keep it is for the image/randomç_mage case, where one may play with transparency...).

I'll double-check if it works w/ the cbb, for fun.

**Comment by NiLuJe** [comment]
Might be as simple as not trying to alphaBlitFrom a BBTYPE that has no alpha component...

**Comment by Frenzie** [comment]
For reference, here's the first page FR: #2917.

**Comment by NiLuJe** [comment]
Fun fact: it's also fixed w/ my WIP [bbtype](https://github.com/NiLuJe/koreader-base/commits/bbtype) branch... -_-".

(Because I added fast-paths to alphaBlit for fully opaque/fully transparent).

**Comment by poire-z** [comment]
@NiLuJe : regarding `Switch the GREY color constants to colors that are actually in the eInk`, good point :)

There are a few frontend modules that use stuff like `Blitbuffer.gray(0.7)` that I guess could benefit from being adjusted too:
```
$ rgrep -l '\.gray' frontend plugins
frontend/apps/reader/modules/readerview.lua
frontend/ui/widget/menu.lua
frontend/ui/widget/bookstatuswidget.lua
frontend/ui/widget/progresswidget.lua
frontend/ui/widget/touchmenu.lua
frontend/ui/widget/networksetting.lua
frontend/ui/widget/configdialog.lua.TOFIX
frontend/ui/widget/configdialog.lua
plugins/coverbrowser.koplugin/listmenu.lua
plugins/coverbrowser.koplugin/mosaicmenu.lua
plugins/statistics.koplugin/readerprogress.lua
plugins/goodreads.koplugin/goodreadsbook.lua
plugins/perceptionexpander.koplugin/main.lua
```

I was sure i've seen some using `ColorN(...)`, but can't find any.

**Comment by Frenzie** [comment]
Yup, definitely should be turned into some kind of appropriate BB constant. :-)

**Comment by NiLuJe** [comment]
@poire-z : Nice catch, I'll track those down, thanks!

**Comment by NiLuJe** [comment]
Re: alpha for screensaver_image: Turns out it's nonsensical anyway, since we enforce a white or black background (via the widget's background property, which leads to a paintRect over the full-screen).

It took me an inordinate amount of time being puzzled why a test image had its transparent pixels set to black... -_-".

And we :clear the fb to white anyway ;).

**Comment by poire-z** [comment]
(For the record, any stuff related to alpha that git blame would point to me shall be considered unthought, random, or stupid cut & paste :) because I don't really get much of that alpha stuff.)

Also, some comments when I gave up on them, in case that talks to you (inline images in Wikipedia lookup results):
https://github.com/koreader/koreader/blob/ce3d181e240ea070384cdb66d1d7a1bc80f16837/frontend/ui/widget/textboxwidget.lua#L364-L377

Related: https://github.com/koreader/crengine/pull/142#issuecomment-376188864

**Comment by NiLuJe** [comment]
@poire-z : Yeah, that one was on my list of things to check ;).
