### ISSUE TITLE
"No books were found" when 'Extract and cache book information'

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4778]
* KOReader version: v2019.02-180-g2536cc2_2019-03-08/ 
* Device: KA1

#### Issue
'Extract and cache book information'-feature doesn't find your books if the following procedure is performed.
#### Steps to reproduce
1. Ensure that you have books in History page
2. Delete cache database and restart KOReader
3. Choose display mode for History page and file manager (something other than classic).
4. Open History page and then close it again.
5. Go to your Home folder (or where your library are), which should have subfolders with books
6. Start 'Extract and cache book information metadata': Continue, Here and under, Don't refresh/Refresh, Don't prune/Prune
7. This produce a "No books were found" message. So it doesn't find books in subfolders, _but_ it seems like it won't even find books that are placed in the folder you perform the 'Extract and cache...', (of course unless they are on page 1 in that folder) as long the first page in that folder contains at least one folder.
8. If you want it to find your books now you can either restart KOReader, or jump into a subfolder and back, and then start 'Extract and cache..." again. If you open History page in between (after restart or jump/jump back) the problem continues.

**Comment by poire-z** [comment]
I don't seem to be able to reproduce it - following your instructions (with differences: my home dir has files in it, and shown on page1, so going to choose display mode already have them being fetched and cached - and you don't say if we should choose Refresh or Prune). Anyway, probably really edgy casy :)

Anyway the code should get the path to work on from the filebrowser. And it should be the one displayed at the top of filebrowser, on the left of the Plus button, under "KOReader file browser". What does it say when that happens?

**Comment by gerhaher** [comment]
> you don't say if we should choose Refresh or Prune

That's because it doesn't matter what you choose here, same thing happen in either case.

> Anyway the code should get the path to work on from the filebrowser. And it should be the one displayed at the top of filebrowser, on the left of the Plus button, under "KOReader file browser". What does it say when that happens?

Well, it shows the correct folder.


What is important is that you must perform the extraction directly after you have closed the History page, i. e. you may not change folder or change page in folder before you start the extraction. 

For example my Home folder contain 5 pages of only subfolders. I'm on page 1 in that folder when I open and close History, and then I start the extraction. If I go to page 2 in that folder before the extraction it finds the books.

**Comment by poire-z** [comment]
OK, reproduced. Guess you also have/need "Start with: file browser" ?

**Comment by gerhaher** [comment]
No: "Start with: History"

**Comment by poire-z** [comment]
I solve this scenario with this simple patch (self.path is empty when History is shown, it then stayed empty until you browse pages in file manager, but indeed if you don't move pages in file browser, it stays empty and is used by Extract & cache... with what you observed):
```lua
--- a/plugins/coverbrowser.koplugin/covermenu.lua
+++ b/plugins/coverbrowser.koplugin/covermenu.lua
@@ -81,7 +81,9 @@ function CoverMenu:updateItems(select_number)
     self:_updateItemsBuildUI()

     -- Set the local variables with the things we know
-    current_path = self.path
+    if self.path then
+        current_path = self.path
+    end
     current_cover_specs = self.cover_specs

     -- As done in Menu:updateItems()
```
Can you test if that solves it for you too, and that you don't see any side effects? (you're good at that :)

**Comment by gerhaher** [comment]
> Can you test if that solves it for you too

I can. if you give a simple noncoder some direction. :) 

Should I remove this `current_path = self.path` and then add the three following lines? 
Anything else?

**Comment by poire-z** [comment]
> Should I remove this current_path = self.path and then add the three following lines? Anything else?

Nothing else, exactly just that (`-` meaning delete that line, `+` meaning add that line).
Or replace your current plugins/coverbrowser.koplugin/covermenu.lua with this one: [covermenu.lua.txt](https://github.com/koreader/koreader/files/2961437/covermenu.lua.txt)

**Comment by gerhaher** [comment]
In that case it doesn't work for me. It finds the books and the extraction process starts.
But when the extraction process is finished, it turns out that nothing has been really extracted. :(

**Comment by gerhaher** [comment]
Correction: Mosaic covers aren't extracted, but Detailed list... seems to be

**Comment by poire-z** [comment]
> Correction: Mosaic covers aren't extracted, but Detailed list... seems to be

Ok, so that's normal. It's still the file browser (that you have probably set to Detailed list) that says which thumbnail size to fetch. Only when you have History set to Mosaic, the plugin sees it only has small thumbnails and decide to fetch again higher thumbnails for better Mosaic view, but only for the ones displayed in History - to save space.
If you set your file browser to be mosaic, they should be fetched as Mosaic.
So, is it allright? (still at Indexing 400/765, waiting for completion :)

Noticing something on my emulator: the infomessage Indexing... have various sizes:
![image](https://user-images.githubusercontent.com/24273478/54281221-88444880-4599-11e9-8b15-22a3722b8ee9.png)

They should only grow, so that does not happen. Do you have also that on your device or is it ok?

**Comment by gerhaher** [comment]
No, I have Mosaic with cover images for file manager and Detailed list with cover... for History.

> If you set your file browser to be mosaic, they should be fetched as Mosaic.
Not working for me.

**Comment by poire-z** [comment]
> If you set your file browser to be mosaic, they should be fetched as Mosaic.

OK, I can somehow reproduce that too, and fix my use case. If you're willing to test again, just move the `current_cover_specs = self.cover_specs` inside the `if`:
```diff
--- a/plugins/coverbrowser.koplugin/covermenu.lua
+++ b/plugins/coverbrowser.koplugin/covermenu.lua
@@ -81,8 +81,13 @@ function CoverMenu:updateItems(select_number)
     self:_updateItemsBuildUI()

     -- Set the local variables with the things we know
-    current_path = self.path
-    current_cover_specs = self.cover_specs
+    -- These are used only by extractBooksInDirectory(), which should
+    -- use the cover_specs set for FileBrowser, and not those from History.
+    -- Hopefully, we get self.path=nil when called fro History
+    if self.path then
+        current_path = self.path
+        current_cover_specs = self.cover_specs
+    end

     -- As done in Menu:updateItems()
     self:updatePageInfo(select_number)
```
Or replace your file with [covermenu.lua.txt](https://github.com/koreader/koreader/files/2962269/covermenu.lua.txt)

**Comment by gerhaher** [comment]
Now it works for me too.
