### ISSUE TITLE
how to reflow 3 columns vertical row pdf

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#4781]
* KOReader version:2019.3
* Device:kindle

it's easy to reflow 2 column vertical row pdf,but how to reflow 3 columns vertical row pdf,example like this:
![2019-03-13_151948](https://user-images.githubusercontent.com/5170835/54260443-de1dee00-45a3-11e9-9cd2-48502a715f3e.gif)

I find that k2pdfopt lib can erase vertical/horizontal line,then the content's border line is disappeard,like this:
![2019-03-13_152508](https://user-images.githubusercontent.com/5170835/54260599-51bffb00-45a4-11e9-94c9-713c3c1906ce.gif)

i hope that koreader can reflow this content

**Comment by poire-z** [comment]
I guess that kpdfopt will probably never be able to do that much.
But for that kind of content, you'd probably be very happy with #6885.
