### ISSUE TITLE
No feedback when turning wifi on or off

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4783]
* KOReader version: 2019.03
* Device: Kindle Paperwhite 3

#### Issue
When I execute default action for enabling wifi on my kindle, it doesn't display any notification
#### Steps to reproduce
Execute default enable wifi gesture on Kindle Paperwhite 3(possibly other devices)

**Comment by Frenzie** [comment]
Are you saying it does in a different scenario?

**Comment by Frenzie** [comment]
For example, if you turn it on through the Network menu or with a wifi prompt.

**Comment by Galunid** [comment]
Actually when I toggle it off using gesture, it displays notification "Wifi disabled", I think it's a good idea, to know whether the gesture was detected successfully, or not.

**Comment by Galunid** [comment]
Also toggling it through Network menu, doesn't display any kind of notification(whether on or off)

**Comment by Frenzie** [comment]
Does the "already connected" notification work on Kindle?

**Comment by Galunid** [comment]
Yes, it does

**Comment by Frenzie** [comment]
I suppose a short little "Enabling wifi" notification shouldn't hurt.
