### ISSUE TITLE
distributing libstdc++.so.6 for better compatibility across different models?

### ISSUE THREAD

**Issue by chrox** [koreader/koreader#480]
A koreader user reported that latest koreader nightlies cannot open any DJVU document in Kobo AuraHD 2.8.1 and 3.1.1. And I also found long ago that koreader nightly build binaries cannot be launched directly in Kindle 3 3.4, and it seemed to be a problem with libstdc++.so.6 which was linked by libdjvulibre.so.21. I'm wondering if this problem can be solved by distributing libstdc++.so.6 binary with Koreader and linking libdjvulibre.so.21 with our own libstdc++.so.6 instead of that provided by firmware.

**Comment by NiLuJe** [comment]
Epic mistake in my previous message: `-static-libstdc++` should of cours ebe passed to the linker, not the compiler. Hence it should go in LDFLAGS not C*FLAGS ;).
