### ISSUE TITLE
[FR] Allow a backlight / night mode schedule (after say 8PM, auto enter night mode with a user definable brightness)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4802]
* KOReader version: 2019.03.01 stable
* Device: PW4

#### Issue

Yes I'm aware #866 exists but it was closed back in 2014 b/c of low activity.  Potentially there is more interest now.

Use case: I read my Paperwhite during the day and at night.  During the day, I tend to have the brightness cranked to 24 and in normal (white screen, black text) mode.

Then when I'm ready to read, it's usually 9-9:30PM and I keep my room dark for the benefit of my eyes and also to try address my insomnia.  I turn on my Kindle and BLAM!!! It's like a punch to my face (the brightness at 24).  I have to kind of squint and angle it away so it doesn't sear my eyes.  

It seems that this is an issue many others would face who read their Kindle or other device during the day and at night.  And making reading more comfortable and easier on the eyes seems a worthy goal.

Popular software like F.lux exists, and Apple & Ubuntu think so highly of adjusting light automatically, they both integrated the feature directly into their operating system.

Some devices have an automatic light sensor and adjust as necessary (Oasis and Voyage I think?).  But for those of who don't have that luxury it seems a system might benefit the user; where:

* User can determine what time a 'night reading' period might cover (i.e. 8pm - 7am)
* User can determine what level brightness 0-24 they'd like by default when the device is turned on during that period.  
* User can determine whether they'd like 'night mode' (inverted screen) to be enabled or not enabled during that period.  
* If the user had the default set to say 5 during this night mode period, and then turned it to say 7, then the device screensaver kicked in, it would stay at 7 until the next night period existed.
* At the conclusion of the 'night mode period' koreader would revert to the brightness/color settings that were set before the night mode period.  

If this is appealing, please comment below!  I'd like to see if it's just me who has this issue.  But it seems like it might help a lot of people!

**Comment by Frenzie** [comment]
Someone interested could write a new plugin or extend the frontlight controller to implement some kind of schedule. You can probably just copy and repurpose bits & pieces of existing code.

**Comment by NiLuJe** [comment]
Doesn't the natural light code has something like this?

**Comment by Frenzie** [comment]
Yeah, an interested party could probably just copy & repurpose bits of code to get something halfway decent pretty quickly. But I'm not that party. :-)

**Comment by NiLuJe** [comment]
What he said. ;).

**Comment by Galunid** [comment]
I may want to take a look and write a plugin, if I find some spare time and get more familiar with widgets.

**Comment by poire-z** [comment]
Implemented by #8129.
