### ISSUE TITLE
Something wrong with the combination diagonal swipes, multiswipe recorder & landscape

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4803]
* KOReader version: v2019.03.1-24-g645d41e_2019-03-15/ 
* Device: KA1

#### Issue
It's problem with both using a recorded multiswipe in landscape, and recording a multiswipe in landscape.
I give you 2 examples. 

1. 
I recorded this when I was in portrait mode and chose an action:

![Reader_2019-Mar-15_174656](https://user-images.githubusercontent.com/32645430/54450209-2843d280-4750-11e9-9548-f948a8e65239.png)

The chosen action works fine in portrait but not in landscape

2.
When I try to record this when I'm in landscape...:

![Reader_2019-Mar-15_175609](https://user-images.githubusercontent.com/32645430/54450279-575a4400-4750-11e9-91fb-47de40d162fb.png)

...I get this:

![Reader_2019-Mar-15_174947](https://user-images.githubusercontent.com/32645430/54450301-63460600-4750-11e9-9d7c-6bfcdbce9d12.png)

**Comment by Frenzie** [comment]
A KA1-specific issue seems unlikely, but I couldn't and can't reproduce this.

**Comment by gerhaher** [comment]
Further info: 

The gist of the problem might be that swipe to bottom left corner is understood as swipe to bottom right corner.

**Comment by Frenzie** [comment]
Oh, you're in reverse landscape, not landscape. Yes, I seem to have made a typo there that I failed to notice while testing:

https://github.com/koreader/koreader/blob/f817bb5e0c17c6fa0c0663ce943c1248a6439053/frontend/device/gesturedetector.lua#L706-L715

**Comment by gerhaher** [comment]
Yes, reverse landscape.
