### ISSUE TITLE
One big lump

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4806]
Just some things I find myself thinking when I use KOReader on my Kobo Aura One.
No energy to turn them all into decent issues.

KOReader:
- Keyboard (books status window, dictionary lookup, file manager jump):
- - Keyboard only has caps lock, no shift.
- - Key letters often disappear after tapping.
- - I'd like a sub-keyboard on holding a key - allowing one to choose from all the accented letters more naturally.
- - If I tap to move the cursor, and tap again and again, I probably do not want a location selected earlier - and in tapping LRL or RLR I probably want a location between the first two.
- Dictionary:
- - Slow.
- - Depletes the battery quickly.
- - When adapting the word to be looked up, the label "Lookup" from the button remains after tapping it.
- - A list of options would be better than cycling through them with << and >>.
- - Nickel dictionaries show a list of possible completions of partially-typed words.  Nice feature.
- - Allowing a page-wide list would be good.  Also for using a dictionary while reading some physical medium.
- File browser:
- - Show which folders have unread material (maybe by boldfacing them).
- PDF reader
- - Kevin Timpe: Grace and controlling what we do not cause (see attachment).  Zoom to fit content width; click on footnote 1
- - - Jumps to wrong location (may be a problem in the document).
- - - Shows last page tiled multiple times.
- - Erratically shows blank triangle at left top corner.
- - Bookmarks in "fit to content width" mode are sometimes one-off.
- - I'd like "Go to and hold"-gesture for link jumping.
- Front light:
- - When resuming from sleep, the warmth is not adapted - this happens suddenly some minutes later.
- - Front light (or menus) not accessible wen the dictionary is open.
- - Light perception is logarithmic.  In the dark 1% light is too much: less than 1%is needed, whereas the difference between 99% and 100% isn't.
[Grace and Controlling what we do not Cause.pdf](https://github.com/koreader/koreader/files/2973031/Grace.and.Controlling.what.we.do.not.Cause.pdf)

**Comment by pazos** [comment]
Thanks for reporting!!

> No energy to turn them all into decent issues.

Ufffffff, please recover a bit of energy and try it, pleeeease ¿?

Some are device specific issues, some are bugs, some are feature requests, some are .. I have no energy to finish this sentence :man_facepalming:

**Comment by Frenzie** [comment]
> Light perception is logarithmic. In the dark 1% light is too much: less than 1%is needed, whereas the difference between 99% and 100% isn't.

I don't see the point in any value over 5 or so on my H2O (and there are 95 more), but unless you want to artificially limit KOReader to the lowest values that doesn't really have anything to do with the program.

**Comment by NiLuJe** [comment]
> Keyboard only has caps lock, no shift.
  Viable FR
> Key letters often disappear after tapping.
c.f., https://github.com/koreader/koreader/pull/4776
> I'd like a sub-keyboard on holding a key - allowing one to choose from all the accented letters more naturally.
  Probably more awkward on an eInk screen than what the usually looks like on Android, but why not. Probably non-trivial, though.
> If I tap to move the cursor, and tap again and again, I probably do not want a location selected earlier - and in tapping LRL or RLR I probably want a location between the first two.
  No idea what that refers to ;).

> Dictionary:
>        Slow.
>        Depletes the battery quickly.
Nothing we can do about that, that's the backend: sdcv ;).
> When adapting the word to be looked up, the label "Lookup" from the button remains after tapping it.
  Probably ghosting?
        A list of options would be better than cycling through them with << and >>.
> Nickel dictionaries show a list of possible completions of partially-typed words. Nice feature.
Like earlier, nothing we can do about that ;).
> Allowing a page-wide list would be good. Also for using a dictionary while reading some physical medium.
  I seem to recall there being a "gigantic dictionary popup" option somewhere.

> Show which folders have unread material (maybe by boldfacing them).
Potentially viable FR, but probably more complex than it might seem and/or prohibitively expensive without an index.

I'm skipping the PDF stuff because PDF is pain and I'm not familiar with it.

> When resuming from sleep, the warmth is not adapted - this happens suddenly some minutes later.
Hmm, that's strange. You wouldn't happen to be using the dynamic natural light thingy by chance? (no issues without it over here).
> Front light (or menus) not accessible wen the dictionary is open.
Yeah, it's a popup.
> Light perception is logarithmic. In the dark 1% light is too much: less than 1%is needed, whereas the difference between 99% and 100% isn't.
That's highly device (or even unit, to some extent) specific, and we tend to match Nickel's behavior for <-> purposes.

**Comment by Biep** [comment]
> 
> 
> > Light perception is logarithmic. In the dark 1% light is too much: less than 1%is needed, whereas the difference between 99% and 100% isn't.
> 
> I don't see the point in any value over 5 or so on my H2O (and there are 95 more), but unless you want to artificially limit KOReader to the lowest values that doesn't really have anything to do with the program.

No, I'd like values starting from 0.01%, and then in - say 100 - logarithmic steps up to 100%.  No idea whether the hardware supports values smaller than 1%, though.

**Comment by Biep** [comment]
> > When resuming from sleep, the warmth is not adapted - this happens suddenly some minutes later.
> 
> Hmm, that's strange. You wouldn't happen to be using the dynamic natural light thingy by chance? (no issues without it over here).

Yes, it is with natural light - it should change by imperceptibly small steps, but after sleeping it doesn't adapt immediately to the now-required value.

**Comment by Biep** [comment]
> > If I tap to move the cursor, and tap again and again, I probably do not want a location selected earlier - and in tapping LRL or RLR I probably want a location between the first two.
> 
> No idea what that refers to ;).

The keyboard is somewhat insensitive, so while typing often a letter is missing in the resulting text.  So I want to tap the location of the missing letter and type it - but my fat fingers often tap a few characters to the right or left, resulting in a "tap dance" between one position too far to the left and one position too far to the right.  The program should understand I do not intend to do that, but want a location between those two.  This can be generalised to my proposal above.

**Comment by NiLuJe** [comment]
The easiest solution would be a simple left/right virtual key in the
keyboard to move the caret ;).

**Comment by NiLuJe** [comment]
Which I vaguely remembered we had, and we do: they're just hidden in the
Sym board.

**Comment by Biep** [comment]
> Like I said, the only thing that could be done and which I would consider highly undesirable is to artificially restrict values. There is no artificial restriction against 1.5 (on our end).

OK, so I'll just have to live with a screen that is too bright at night..  Pity.

**Comment by Biep** [comment]
> > When adapting the word to be looked up, the label "Lookup" from the button remains after tapping it.
> 
> Probably ghosting?

No - there is a clear white rectangle with rounded corners, and the word "Lookup" in it in black - both completely occluding the text "behind" it.
(I suppose by "ghosting" you mean that traces of the previous image remain on the current.)

**Comment by Biep** [comment]
> Ufffffff, please recover a bit of energy and try it, pleeeease ¿?

I started - made [a new issue](https://github.com/koreader/koreader/issues/4812) for the PDF things.

**Comment by pazos** [comment]
@Biep: please make reports for any bug / feature request you want. One at a time to help others to follow the issue in the long term (and hopefully somebody will pick and fix/implement) the ones she/he likes).

Closing this.
