### ISSUE TITLE
Some problems with the PDF reader

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4812]
* KOReader version: v2019-02-130-g93422d0-2019-03-02
* Device: Kobo Aura One

Taken from [#4806](https://github.com/koreader/koreader/issues/4806) about PDF viewing:
- Erratically show blank triangle at left top corner.
- Bookmarks in "fit to content width" mode are sometimes one-off.
- I'd like "Go to and hold"-gesture for link jumping.
- Kevin Timpe: [Grace and Controlling what we do not Cause.pdf](https://github.com/koreader/koreader/files/2975144/Grace.and.Controlling.what.we.do.not.Cause.pdf).  Zoom to fit content width; click on footnote 1
- - Jumps to wrong location (may be a problem in the document, though it happens in some other documents too).
- - Shows last page tiled multiple times.  This too happens quite a bit with other documents.

**Comment by poire-z** [comment]
Just mentionning something i did early on when I met KOReader but as I'm not a heavy pdf user I may not see all implications.

```diff
 function ReaderPaging:setPagePosition(page, pos)
     logger.dbg("set page position", pos)
+    -- only remember one page position (the latest one,
+    -- used when re-opening a book)
+    for k,v in pairs(self.page_positions) do self.page_positions[k]=nil end
     self.page_positions[page] = pos
 end
```

Because by default, KOREader remembers the "position" of each page: how much scrolled are we in it, the y of the page that should be aligned to the top of the view when we reach again that page.
Which makes sense when turning pages or getting back from links - and not in other cases like jumping to TOC entries or following bookmarks.

I'm not interested in investigating/fixing that. But the above patch has shut down any surprise I used to have with PDF.

**Comment by Frenzie** [comment]
> Erratically show blank triangle at left top corner.

Could you give a few more details please?

> Bookmarks in "fit to content width" mode are sometimes one-off.

Do you mean that it applies to the bottom page on the screen even though it's only taking up part of it or that it's actually one off? It's the difference between a bug and something that might be improved upon.

<img src=https://user-images.githubusercontent.com/202757/54492267-4ed74a00-48c5-11e9-821a-c9f0ff995952.png width=30%> 

> I'd like "Go to and hold"-gesture for link jumping.

That doesn't sound PDF-related, but also I don't know what it means.

> Shows last page tiled multiple times. This too happens quite a bit with other documents.

Huh, cool. I think this could largely be the same issue as "Jumps to wrong location". That is, normally you can't reach "below" the document, but following a link might make it try to scroll down further.

![Screenshot_2019-03-17_14-53-56](https://user-images.githubusercontent.com/202757/54492181-81cd0e00-48c4-11e9-86f8-73c8a9d0f867.png)

**Comment by Biep** [comment]
> > Erratically show blank triangle at left top corner.
> Could you give a few more details please?

Anything to the NW of an imaginary line is white.  The imaginary line crosses the top border of the screen maybe halfway, and the left border maybe 1/4 down - like a big dogear.
When I make a screenshot the page repairs itself - and the image doesn't show it.  Just going to another page and returning repairs it too.

> > Bookmarks in "fit to content width" mode are sometimes one-off.
> Do you mean that it applies to the bottom page on the screen even though it's only taking up part of it or that it's actually one off? It's the difference between a bug and something that might be improved upon.

I'll have to check.  Sometimes I set a bookmark on a page showing a certain footnote, and when I jump to that bookmark the footnote isn't there (normally I have to page back one page).

> > I'd like "Go to and hold"-gesture for link jumping.
> That doesn't sound PDF-related, but also I don't know what it means.

I guess it isn't.  I feel the natural gesture for me to select a link is to put my finger besides it, then moving onto the link, and keeping my finger there.  Just tapping is should proceed to the next page, and just holding should call up the dictionary.

**Comment by Biep** [comment]
I guess in content width mode I want bookmarks to be associated with "pages" as e-reader display units - the pagination of the original document doesn't interest me.  Maybe the bookmark is associated with the page as seen by the PDF.

**Comment by poire-z** [comment]
>  The imaginary line crosses the top border of the screen maybe halfway, and the left border maybe 1/4 down - like a big dogear

You mean like in https://github.com/koreader/koreader/issues/3130 - in which case, it's not voluntarily, but a hard to track/counteract refresh glitch.

**Comment by Biep** [comment]
> > The imaginary line crosses the top border of the screen maybe halfway, and the left border maybe 1/4 down - like a big dogear
> 
> You mean like in #3130 - in which case, it's not voluntarily, but a hard to track/counteract refresh glitch.

Yes, that's the one.
Not sure what you mean by "voluntarily" - I hadn't assumed this behaviour had been coded in on purpose.. :-)

**Comment by Frenzie** [comment]
When you said triangle I just thought of something like the bookmark. ;-)

**Comment by Biep** [comment]
I just got a new type.  While deleting letters from the dictionary lookup feature (popping up when long pressing an entry head).  When I had deleted all letters and then hit the <x button once more, a triangular slice of the screen went blank.  The two top corners were 1/4 and 1/2 along the top rim, and the bottom corner was the SW corner of the screen.

**Comment by Biep** [comment]
The problem with the tiled last page is not restricted to footnote jumps.  Simply "Go to page 23" will do the same with this file:
[Armchair Philosophy, Metaphysical Modality and Counterfactual Thinking.pdf](https://github.com/koreader/koreader/files/3145537/Armchair.Philosophy.Metaphysical.Modality.and.Counterfactual.Thinking.pdf)

**Comment by Frenzie** [comment]
I can't seem to reproduce the "go to page" issue anymore. Please reopen with more info if you can.
