### ISSUE TITLE
page turner for kindle

### ISSUE THREAD

**Issue by konos93** [koreader/koreader#4813]
question 
i saw this https://twitter.com/ESP8266/status/1080874134853304322

is it possible to connect an usb OTG on kindle with latest koreader version and with a mouse press right click like touch right part of the screen , press left click like touch left part of the screen ?

**Comment by Frenzie** [comment]
If the answer to the first part of all that is "yes" then it may not be too hard to respond to some input event.

Basically you'd need to figure out how to get the clicks from something like `/dev/input/eventX` and then the simple part would be to somehow translate it to PgFwd/PgBack events in KOreader:

https://github.com/koreader/koreader/blob/59d8a1852fcc33a482fa6c4052d871036429a8af/frontend/device/kindle/event_map_kindle4.lua#L5-L19

**Comment by pazos** [comment]
pinging @NiLuJe, I'm not sure if kindles have usb host support and related input devices (keyboard/mouse/gpio keys).

Other platforms don't and need a new kernel build to support that kind of devices.

**Comment by NiLuJe** [comment]
Someone did such a thing for some specific PaperWhite / FW versions combo (c.f., KindleLazy on MR).

**Comment by arooni** [comment]
i'd like to follow this issue if there ever is a positive results for the PW4

**Comment by konos93** [comment]
well i connect an otg-cable without start koreader and a window pop up and ask me to register the device via wifi . i don't know if it will work but this is a risk i wont take. if there will be an upgrade or something similar i will have to disassembly the device and do a serial downgrade to install again Koreader
