### ISSUE TITLE
Fr: (Android) support Bluetooth keyboard input especially for note taking 

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4814]
* KOReader version: any
* Device:

#### Issue
So I read with multiple devices including an Android tablet.  On occasion there's a great passage that id like to jot a few notes on 
..

So I hooked up my Bluetooth keyboard and tried to take notes but it looks like Koreader ignores all input unless it's provided with the on screen input.  Would be nice to see support for the hardware keyboard where I can take notes much faster

**Comment by pazos** [comment]
Hi @arooni, I edited the other issue you opened #4671 and mark this a a duplicate since it will need the same kind of improvements.
