### ISSUE TITLE
Ways of closing bottom menu: clicking active tab icon, pressing menu button

### ISSUE THREAD

**Issue by viksok** [koreader/koreader#4817]
* KOReader version: 2019.03.1
* Device: Pocketbook Aqua 2 aka. 641

#### Issue
While bottom menu (layout, fonts etc) opened clicking on an active tab should close the menu, actually does nothing. Also pressing menu button again does not close the bottom menu.

#### Steps to reproduce
Open any book, click menu button or make a swipe up, click on an active tab icon. Also clicking menu button does not closes the bottom menu.

#### Proposed behavior
Clicking active tab or pressing menu button or swipe down should hide bottom menu

**Comment by Frenzie** [comment]
> While bottom menu (layout, fonts etc) opened clicking on an active tab should close the menu, actually does nothing.

Should it? :-) That would be inconsistent with how tabs are expected to behave. Normally they can't be closed by accident.

Is there more detail you could add to the hypothetical scenario? Because it's much easier to tap outside the menu or to swipe down on it to close it, than to precisely hit the currently open tap. By contrast, if you want to switch to a tab on the left or right you might accidentally miss and hit the currently open tab.

> Also pressing menu button again does not close the bottom menu.

This is also not something that's normal for the context menu. Perhaps it would be more accurate to say that UIs are oddly inconsistent in the matter. It's complicated further by the fact that while this might make sense on your specific device, on devices with arrow keys it's would make more sense to use it for the long-press (set default) action, so unfortunately it's not a simple case of altering some behavior.

> crash.log does not apply here.

You can just remove what doesn't apply. ;-)

**Comment by viksok** [comment]
> > While bottom menu (layout, fonts etc) opened clicking on an active tab should close the menu, actually does nothing.
> 
> Should it? :-) That would be inconsistent with how tabs are expected to behave. Normally they can't be closed by accident.

If there's no dedicated close button/action raising your palm to the top of the screen to emit an action that closes the menu seems worse that tapping with your thumb finger while holding device normally.
This allows users to operate with one hand.

> Is there more detail you could add to the hypothetical scenario? Because it's much easier to tap outside the menu or to swipe down on it to close it, than to precisely hit the currently open tap. By contrast, if you want to switch to a tab on the left or right you might accidentally miss and hit the currently open tab.
> 
> > Also pressing menu button again does not close the bottom menu.
> 
> This is also not something that's normal for the context menu. Perhaps it would be more accurate to say that UIs are oddly inconsistent in the matter. It's complicated further by the fact that while this might make sense on your specific device, on devices with arrow keys it's would make more sense to use it for the long-press (set default) action, so unfortunately it's not a simple case of altering some behavior.

Well, to answer the question try to press Win/Super button in windows/gnome, you'll see that pressing the button again closes the menu.
Another example is Notification center (Windows 10), clicking once opens the panel, clicking again - closes.
And another one, while clicking on program icon on the task bar once you either minify the window, or expand it. 
That's how UI interaction should behave.

If device has no physical menu button, let the device close bottom menu by tapping outside, otherwise it worse nothing to implement it.
 
> > crash.log does not apply here.
> 
> You can just remove what doesn't apply. ;-)
removed

**Comment by Frenzie** [comment]
> If there's no dedicated close button/action

But there is: swipe down. Which is much easier to execute than an any alternative yet also practically impossible to do by accident.

> Well, to answer the question try to press Win/Super button in windows/gnome, you'll see that pressing the button again closes the menu.

The relevant example here is the context menu key, as I already said. The Windows key is something completely different.

> And another one, while clicking on program icon on the task bar once you either minify the window, or expand it.

That is unrelated to configuration tabs, although a tabbed document interface (which is not what we've got here) is the most popular variant of MDI, which distinguishes itself precisely by that behavior. Hence like I said, UIs are inconsistent, but they are nevertheless consistent about this inconsistency.

**Comment by viksok** [comment]
> > If there's no dedicated close button/action
> 
> But there is: swipe down. Which is much easier to execute than an any alternative yet also practically impossible to do by accident.

Well, as I mentioned, it doesn't work on my device.
Steps to reproduce? Open bottom menu then swipe from top to bottom or from center to bottom. None are closing bottom menu.

> > Well, to answer the question try to press Win/Super button in windows/gnome, you'll see that pressing the button again closes the menu.
> 
> The relevant example here is the context menu key, as I already said. The Windows key is something completely different.
> 
> > And another one, while clicking on program icon on the task bar once you either minify the window, or expand it.
> 
> That is unrelated to configuration tabs, although a tabbed document interface (which is not what we've got here) is the most popular variant of MDI, which distinguishes itself precisely by that behavior. Hence like I said, UIs are inconsistent, but they are nevertheless consistent about this inconsistency.

Talking about swipes, how does swipe with another palm is more convenient that pressing a button or tapping on a bottom area of the screen with the same palm finger?

**Comment by Frenzie** [comment]
> Well, as I mentioned, it doesn't work on my device.

You mean where you wrote "Clicking active tab or pressing menu button or swipe down should hide bottom menu"? I interpreted that as a full set of dismissal behaviors, not as a report about the existing one not working. ;-)

> Steps to reproduce? Open bottom menu then swipe from top to bottom or from center to bottom. None are closing bottom menu.
> […]
> Talking about swipes, how does swipe with another palm is more convenient that pressing a button or tapping on a bottom area of the screen with the same palm finger?

It might make sense to extend the swipe area I suppose, but that's a false dilemma. The entire point of swiping is that you don't have to move your finger anywhere. You just swipe down from where you are. This is precisely what makes it so much easier than tapping on a precisely defined location.

<img src=https://user-images.githubusercontent.com/202757/54608990-43655980-4a52-11e9-9b51-60578c3e8c30.png width=40%>

* Purple is the area where you tap to dismiss.
* Green is the area where you swipe down to dismiss.
* Red is the area where you propose to tap to dismiss.

**Comment by Frenzie** [comment]
I'm tagging this as wontfix, since as I laid out above I don't think requiring high precision is good UX. But as the tag says, PRs are welcome.
