### ISSUE TITLE
Handle external links on Android

### ISSUE THREAD

**Issue by minijackson** [koreader/koreader#4821]
* KOReader version: v2019.03.01
* Device: a3y17ltexc

#### Issue

As I understand, external links are currently handled only in the Wikipedia case. It would be nice to make KOReader open an external app to handle the links instead of showing an error window.

Thanks for the great work!

#### Steps to reproduce

- Have a book with non-wikipedia external links in it
- Read it
- Click on one of those links
- See error message

**Comment by Frenzie** [comment]
As an aside, on Kobo etc. I want to do something similar to Wikipedia with Wallabag on all links.
