### ISSUE TITLE
Suspend action doesn't work on Kindle PW3

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4823]
* KOReader version: v2019.03.1-24-..._2019-03-15
* Device: Kindle PW3

#### Issue
When I set gesture manager action nothing happens
#### Steps to reproduce
Set "Suspend" as a gesture on kindle

**Comment by Frenzie** [comment]
Is suspend an action that is in fact available on Kindle? By which I mean that the issue title might be misleading and it should simply be something like "suspend is displayed when it shouldn't be".

**Comment by Galunid** [comment]
Oh, I'm not sure if it's supported, it's displayed and can be ticked, so I assumed that it is supported

**Comment by Frenzie** [comment]
But is it available through the exit menu?

**Comment by pazos** [comment]
We can add (device:)canSuspend and canTogglePower instead of
https://github.com/koreader/koreader/blob/master/frontend/ui/elements/common_info_menu_table.lua#L64 and https://github.com/koreader/koreader/blob/master/frontend/ui/elements/common_info_menu_table.lua#L72

**Comment by Frenzie** [comment]
Quite so. :+1: 

Btw, if you press <kbd>y</kbd> then it adds a specific commit so that you have a link that'll always work.

NB The emulator can also "suspend" (but not reboot afaik). Please keep that in mind while refactoring.

https://github.com/koreader/koreader/blob/b1ed2838c8b838e7f1d0b3cbf1aa9ca6ee547932/frontend/apps/reader/modules/readergesture.lua#L815-L816

Anyway @Galunid so it's available in the exit menu judging by what @pazos linked. Is it also functional?

**Comment by Galunid** [comment]
In exit menu, it's called "Sleep", but it doesn't work

**Comment by Galunid** [comment]
```lua
    -- part of UIManager:init()
    elseif Device:isKindle() then
        self.event_handlers["IntoSS"] = function()
            self:_beforeSuspend()
            Device:intoScreenSaver()
        end
        self.event_handlers["OutOfSS"] = function()
            Device:outofScreenSaver()
            self:_afterResume();
        end
        self.event_handlers["Charging"] = function()
            self:_beforeCharging()
            Device:usbPlugIn()
        end
        self.event_handlers["NotCharging"] = function()
            Device:usbPlugOut()
            self:_afterNotCharging()
        end
-- next elseif
```
this is then used in:
```lua
function UIManager:suspend()
    if Device:isCervantes() or Device:isKobo() or Device:isSDL() or Device:isSonyPRSTUX() then
        self.event_handlers["Suspend"]()
    elseif Device:isKindle() then
        self.event_handlers["IntoSS"]()
    end
end
```
So it seems, there is a problem with `Device:intoScreenSaver()` for kindle

```lua
function Kindle:intoScreenSaver()
    local Screensaver = require("ui/screensaver")
    if self:supportsScreensaver() then
        -- NOTE: Meaning this is not a SO device ;)
        if self.screen_saver_mode == false then
            Screensaver:show()
        end
    else
        -- Let the native system handle screensavers on SO devices...
        if self.screen_saver_mode == false then
            if os.getenv("AWESOME_STOPPED") == "yes" then
                os.execute("killall -cont awesome")
            end
        end
    end
    self.powerd:beforeSuspend()
    self.screen_saver_mode = true
end
```
Either `self.screen_saver_mode == true`, or `Screensaver:show()` has some problem.

**Comment by Frenzie** [comment]
Okay, so a Kindle bug. It works ob Kobo. Pinging @NiLuJe

**Comment by Galunid** [comment]
Some more digging, `Exit -> Sleep` draws a widget on screen, but it neither disables frontlight nor prevents touch events(if I press screen, it moves), `Sleep gesture` -> no reaction at all. Additionally, making the device sleep from menu and tapping the screen, causes the device not to go to sleep again through `Exit -> Sleep`. After going to sleep using `Exit -> Sleep` and waking up then making the device suspend using power button, leaves me with screen disabled, but without screensaver image. Is it possible, that the suspend through `Exit -> Sleep` doesn't finish the entire process.

**Comment by Galunid** [comment]
KOReader was launched using KUAL

**Comment by NiLuJe** [comment]
There's no real software suspend event on Kindle: we rely on the system's suspend, which we don't currently have any means of triggering ourselves. Only the power button/sleep cover can and will suspend properly.

So, yeah, those sleep/suspend thingy shouldn't be accessible on Kindle.

Unless you really want them, in which case they'll have to be implemented via a lipc call, because i'm fairly sure there's one to trigger the system's suspend ;).

**Comment by NiLuJe** [comment]
(i.e., c.f., input/input-kindle.h in base, we listen for the system's `goingToScreenSaver` & `outOfScreenSaver`, which indicate, respectively, suspend and resume).

**Comment by NiLuJe** [comment]
`lipc-set-prop -i com.lab126.powerd powerButton 1` will fake a power button, effectively triggering a suspend (or resume).

I have no idea how portable that is, though. I'm fairly sure it'll work on FW 5.x, it might not on earlier devices. (It should, but I'm not sure OTOH).

**Comment by Galunid** [comment]
Would sth like this work?
```lua
function Kindle:intoScreenSaver()
    local haslipc, lipc = pcall(require, "liblipclua")
    if not (haslipc and lipc) then
        logger.warn("could not load liblibclua")
        return true
    end
    local lipc_handle = lipc.init("com.github.koreader.device")
    if not lipc_handle then
        local Screensaver = require("ui/screensaver")
        if self:supportsScreensaver() then
            -- NOTE: Meaning this is not a SO device ;)
            if self.screen_saver_mode == false then
                Screensaver:show()
            end
        else
            -- Let the native system handle screensavers on SO devices...
            if self.screen_saver_mode == false then
                if os.getenv("AWESOME_STOPPED") == "yes" then
                    os.execute("killall -cont awesome")
                end
            end
        end
        self.powerd:beforeSuspend()
        self.screen_saver_mode = true
        return true
    end
    lipc_handle:set_int_property("com.lab126.powerd", "powerButton", 1)
end
```
basic idea is that if there is lipc, we use it to trigger screensaver, which should in turn trigger the rest of necessary stuff, if there isn't, we do it like we used to

**Comment by NiLuJe** [comment]
IIRC, no, as intoScreenSaver is launched *after* we catch the goingToScreenSaver event. You'd just be waking up the device instantly ;).

I'm not sure what method the "Sleep" menu & gesture are calling, but you basically want them to call something new on Kindle, probably added to powerd, named, let's say, "toggleSuspend', that just sends that powerd event over lipc ;).

**Comment by NiLuJe** [comment]
Apparently, that's UIManager:suspend(), which helpfully already has a Kindle-specific branch.

Just stick that before calling the IntoSS event.

**Comment by NiLuJe** [comment]
KindlePowerD already has a cached lipc handle, so you don't even have to deal with its lifecycle.
