### ISSUE TITLE
Kindle Documentation Unclear

### ISSUE THREAD

**Issue by Fmstrat** [koreader/koreader#4827]
* KOReader version: n/a
* Device: Kindle Paperwhite

#### Issue
When utilizing https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices it is unclear which Kindle zip to use for which kindle.

- koreader-kindle-arm-kindle5-linux-gnueabi-v2019.03.1.zip
- koreader-kindle-legacy-arm-kindle-linux-gnueabi-v2019.03.1.zip
- koreader-kindlepw2-arm-kindlepw2-linux-gnueabi-v2019.03.1.zip

Now I have a Kindle Paperwhite (1) running 5.4.4.2 firmware. The documentation does not state the difference between "kindle-arm-kindle5" and "kindle-legacy-arm-kindle". Is the Kindle5 file for new generation Kindles? Is it for Kindles with 5.x firmware?

**Comment by pazos** [comment]
https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#err-there-are-three-kindle-packages-to-choose-from-which-do-i-pick

**Comment by Fmstrat** [comment]
Hah, hiding it down at the bottom. I'm an idiot.
