### ISSUE TITLE
[bug] Crashes when launched via installed deb on Ubuntu 18.04

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4830]
* KOReader version: 2019.03.01
* Device: ubuntu 18.04 

koreader
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/21/19-18:28:30
 [*] Version: v2019.03.1

ffi.load: SDL2
ffi.load: SDL2
ffi.load: blitbuffer
/usr/bin/koreader: line 36: 19241 Illegal instruction     ./reader.lua "${ARGS}"

**Comment by pazos** [comment]
I would need a few logs:

log of `uname -a`
log of `cat /proc/cpuinfo`
log of `koreader -d`
log of `cd /usr/lib/koreader && ./reader.lua`

**Comment by NiLuJe** [comment]
@Frenzie : That vaguely looks like two copies of libSDL2 get loaded?

Could the log be slightly more explicit as to which symlink it's trying to load?

**Comment by arooni** [comment]
> I would need a few logs:
> 
> log of `uname -a`
> log of `cat /proc/cpuinfo`
> log of `koreader -d`
> log of `cd /usr/lib/koreader && ./reader.lua`

so personal!

good thing i like you folks :)

[I]  ~  uname -a
Linux LilArooni 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[I]  ~  cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0x2e
cpu MHz         : 2865.289
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4983.90
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0x2e
cpu MHz         : 2922.123
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4983.90
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0x2e
cpu MHz         : 2961.817
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4983.90
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
stepping        : 7
microcode       : 0x2e
cpu MHz         : 2865.354
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 2
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 4983.90
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

[I]  ~  koreader -d
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/21/19-20:59:22
 [*] Version: v2019.03.1

ffi.load: SDL2
ffi.load: SDL2
ffi.load: blitbuffer
/usr/bin/koreader: line 36:  4042 Illegal instruction     ./reader.lua "${ARGS}"
[I]  ✘  ~  cd /usr/lib/koreader && ./reader.lua
fish: Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
cd /usr/lib/koreader && ./reader.lua
                      ^
[I]  ✘  ~  cd /usr/lib/koreader && ./reader.lua^C
[I]  ✘  ~  bash
Initializing new SSH agent...
succeeded
Identity added: /home/david/.ssh/id_rsa (/home/david/.ssh/id_rsa)
Identity added: /home/david/.ssh/id_dsa (/home/david/.ssh/id_dsa)
LilArooni ~: cd /usr/lib/koreader && ./reader.lua
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 03/21/19-20:59:31
 [*] Version: v2019.03.1

ffi.load: SDL2
ffi.load: SDL2
ffi.load: blitbuffer
ffi.load (assisted searchpath): ./libs/libblitbuffer.so
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
Illegal instruction
LilArooni /usr/lib/koreader:

**Comment by Frenzie** [comment]
@NiLuJe
>That vaguely looks like two copies of libSDL2 get loaded?
>
>Could the log be made slightly more explicit as to which symlink it's trying to load?

That's what it's always done. First it checks if SDL2 can be loaded in `util.haveSDL2()` ([here](https://github.com/koreader/koreader/blob/54b0e85bddda37be23013f4e4063d50738710d9b/frontend/device.lua)), then if that's true it proceeds to load `ffi/SDL2_0.lua` ([here](https://github.com/koreader/koreader/blob/54b0e85bddda37be23013f4e4063d50738710d9b/frontend/device/sdl/device.lua#L69)).

What's new is that if SDL2 isn't found, you'll also see `libSDL2-2.0.so` show up. So then it would look like this:

```
ffi.load: SDL2
ffi.load: libSDL2-2.0.so
ffi.load: SDL2
ffi.load: libSDL2-2.0.so
ffi.load: blitbuffer
```

If neither of those can be found it'll proceed to SDL next (cf. https://github.com/koreader/koreader-base/issues/828).

**Comment by NiLuJe** [comment]
Oh, never noticed that, my bad, thanks for the recap ;).

**Comment by pazos** [comment]
@arooni: your cpu lacks some instructions (like avx2). Could you please check if the appimage works for you? It should work.

On https://github.com/koreader/koreader-base/pull/785/files I used -march=native for debian on intel computers (to differenciate between 32 and 64 bits) but seems a bad idea to release that because gcc will catch the optimizations found in the build computer.

One easy way to get rid of these kind of bugs is to add a couple of generic targets for generic 32 and generic 64 and leave native for people who wants to build from source.

@NiLuJe @Frenzie: any idea of how to solve this?

@arooni again: you can build from source and the debian package you build will work in your computer.

**Comment by Frenzie** [comment]
@pazos What if you just leave out the -march=native?

**Comment by NiLuJe** [comment]
Oh, yeah, that's definitely it.

The usual recommendation for binary packages is indeed `-mtune=generic`" *on its own*.

People who build from source should have sane CFLAGS in their env, overriding those defaults.

**Comment by arooni** [comment]
the app image works fine.  I suppose there's really no reason to run anything else, especially as it seems its able to get OTA updates without having to re-build like I think I'd need to for native ubuntu builds.

Did try building for funsies ; didn't seem to finish.

```
[I]  ~/software  cd koreader
[I]  ~/s/koreader  ➦ 658f5135    ./kodev build
git submodule init
Submodule 'koreader-base' (https://github.com/koreader/koreader-base.git) registered for path 'base'
Submodule 'platform/android/luajit-launcher' (https://github.com/koreader/android-luajit-launcher.git) registered for path 'platform/android/luajit-launcher'
Submodule 'platform/ubuntu-touch/ubuntu-touch-sdl' (https://github.com/Sturmflut/ubuntu-touch-sdl-template) registered for path 'platform/ubuntu-touch/ubuntu-touch-sdl'
Submodule 'resources/fonts' (https://github.com/koreader/koreader-fonts.git) registered for path 'resources/fonts'
Submodule 'test' (https://github.com/koreader/test-data.git) registered for path 'test'
git submodule sync
Synchronizing submodule url for 'base'
Synchronizing submodule url for 'platform/android/luajit-launcher'
Synchronizing submodule url for 'platform/ubuntu-touch/ubuntu-touch-sdl'
Synchronizing submodule url for 'resources/fonts'
Synchronizing submodule url for 'test'
git submodule update
Cloning into '/home/david/software/koreader/base'...
Cloning into '/home/david/software/koreader/platform/android/luajit-launcher'...
Cloning into '/home/david/software/koreader/platform/ubuntu-touch/ubuntu-touch-sdl'...
Cloning into '/home/david/software/koreader/resources/fonts'...
Cloning into '/home/david/software/koreader/test'...
Submodule path 'base': checked out '1b146e7234c787d6c779bd8b42c0a85cb8dc9323'
Submodule path 'platform/android/luajit-launcher': checked out '734f66878703cf895fe52cf5757ffee041a4f01e'
Submodule path 'platform/ubuntu-touch/ubuntu-touch-sdl': checked out '1d0cd7583c27025a69e340ac77cab3c53cdef8ba'
error: Server does not allow request for unadvertised object a4b2154c7a26197593e786ff4c90c05b2409e05b
Fetched in submodule path 'resources/fonts', but it did not contain a4b2154c7a26197593e786ff4c90c05b2409e05b. Direct fetching of that commit failed.
Makefile:144: recipe for target 'fetchthirdparty' failed
make: *** [fetchthirdparty] Error 1
make -C base
make[1]: Entering directory '/home/david/software/koreader/base'
************ Building for MACHINE: "x86_64-linux-gnu-debug" **********
************ PATH: "/home/david/.rvm/gems/ruby-2.4.1/bin:/home/david/.rvm/gems/ruby-2.4.1@global/bin:/home/david/.rvm/rubies/ruby-2.4.1/bin:/home/david/.rvm/bin:/home/david/bin:/home/david/.local/bin:/home/david/.fzf/bin:/home/david/.tmux/plugins/tmuxifier/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/games:/usr/local/games:/snap/bin" **********
************ CHOST: "" **********
install -d build/x86_64-linux-gnu-debug/libs
install -d thirdparty/luajit/build/x86_64-linux-gnu-debug
cd thirdparty/luajit/build/x86_64-linux-gnu-debug && \
        cmake -DCC="gcc" \
        -DXCOMPILE:BOOL=off \
        -DBASE_CFLAGS="-Og -g -pipe -fno-omit-frame-pointer" -DHOST_CFLAGS="-march=native -Og -g -pipe -fno-omit-frame-pointer " \
         \
         \
        -DTARGET_SONAME=libluajit.so \
        -DTARGET_CFLAGS="-Og -g -pipe -fno-omit-frame-pointer  -march=native -fPIC" \
        -DCROSS="-" \
        /home/david/software/koreader/base/thirdparty/luajit && \
        make
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BASE_CFLAGS
    CC
    CROSS
    HOST_CFLAGS
    TARGET_CFLAGS
    TARGET_SONAME


-- Build files have been written to: /home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug
make[2]: Entering directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
make[3]: Entering directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
make[4]: Entering directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
Scanning dependencies of target luajit
make[4]: Leaving directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
make[4]: Entering directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
[ 12%] Creating directories for 'luajit'
[ 25%] Performing download step for 'luajit'
Cloning into 'luajit'...
fatal: reference is not a tree: f0e865dd4861520258299d0f2a56491bd9d602e1
From https://github.com/LuaJIT/LuaJIT
 * [new branch]      master     -> origin/master
 * [new branch]      v2.0       -> origin/v2.0
 * [new branch]      v2.1       -> origin/v2.1
 * [new tag]         v2.0.0               -> v2.0.0
 * [new tag]         v2.0.0-beta1         -> v2.0.0-beta1
 * [new tag]         v2.0.0-beta10        -> v2.0.0-beta10
 * [new tag]         v2.0.0-beta11        -> v2.0.0-beta11
 * [new tag]         v2.0.0-beta2         -> v2.0.0-beta2
 * [new tag]         v2.0.0-beta2-hotfix2 -> v2.0.0-beta2-hotfix2
 * [new tag]         v2.0.0-beta3         -> v2.0.0-beta3
 * [new tag]         v2.0.0-beta4         -> v2.0.0-beta4
 * [new tag]         v2.0.0-beta5         -> v2.0.0-beta5
 * [new tag]         v2.0.0-beta6         -> v2.0.0-beta6
 * [new tag]         v2.0.0-beta7         -> v2.0.0-beta7
 * [new tag]         v2.0.0-beta8         -> v2.0.0-beta8
 * [new tag]         v2.0.0-beta8-fixed   -> v2.0.0-beta8-fixed
 * [new tag]         v2.0.0-beta9         -> v2.0.0-beta9
 * [new tag]         v2.0.0-rc1           -> v2.0.0-rc1
 * [new tag]         v2.0.0-rc2           -> v2.0.0-rc2
 * [new tag]         v2.0.0-rc3           -> v2.0.0-rc3
 * [new tag]         v2.0.1               -> v2.0.1
 * [new tag]         v2.0.1-fixed         -> v2.0.1-fixed
 * [new tag]         v2.0.2               -> v2.0.2
 * [new tag]         v2.0.3               -> v2.0.3
 * [new tag]         v2.0.4               -> v2.0.4
 * [new tag]         v2.1.0-beta1         -> v2.1.0-beta1
 * [new tag]         v2.1.0-beta2         -> v2.1.0-beta2
 * [new tag]         v2.1.0-beta3         -> v2.1.0-beta3
Note: checking out 'f0e865dd4861520258299d0f2a56491bd9d602e1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f0e865d Improve luaL_addlstring().
[ 37%] No patch step for 'luajit'
[ 50%] No update step for 'luajit'
[ 62%] No configure step for 'luajit'
[ 75%] Performing build step for 'luajit'
make[5]: Entering directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit'
==== Building LuaJIT 2.1.0-beta3 ====
make[6]: Entering directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src'
HOSTCC    host/buildvm_asm.o
HOSTCC    host/buildvm_lib.o
HOSTCC    host/buildvm_fold.o
HOSTCC    host/minilua.o
HOSTCC    host/buildvm_peobj.o
CC        lj_gc.o
CC        lj_char.o
CC        lj_obj.o
CC        lj_buf.o
CC        lj_str.o
CC        lj_tab.o
CC        lj_func.o
CC        lj_udata.o
CC        lj_meta.o
CC        lj_debug.o
CC        lj_state.o
CC        lj_vmevent.o
CC        lj_vmmath.o
CC        lj_strscan.o
CC        lj_strfmt.o
CC        lj_strfmt_num.o
CC        lj_api.o
CC        lj_profile.o
CC        lj_lex.o
CC        lj_parse.o
CC        lj_bcread.o
CC        lj_bcwrite.o
CC        lj_load.o
CC        lj_ir.o
CC        lj_opt_mem.o
CC        lj_opt_narrow.o
CC        lj_opt_dce.o
CC        lj_opt_loop.o
CC        lj_opt_split.o
CC        lj_opt_sink.o
CC        lj_mcode.o
CC        lj_snap.o
CC        lj_asm.o
CC        lj_trace.o
CC        lj_gdbjit.o
CC        lj_ctype.o
CC        lj_cdata.o
CC        lj_cconv.o
CC        lj_ccall.o
CC        lj_ccallback.o
CC        lj_carith.o
CC        lj_clib.o
CC        lj_cparse.o
CC        lj_lib.o
CC        lj_alloc.o
CC        lib_aux.o
CC        lib_package.o
CC        lib_init.o
CC        luajit.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
HOSTCC    host/buildvm.o
HOSTLINK  host/buildvm
BUILDVM   lj_vm.S
BUILDVM   lj_ffdef.h
BUILDVM   lj_folddef.h
BUILDVM   lj_bcdef.h
BUILDVM   lj_recdef.h
BUILDVM   lj_libdef.h
BUILDVM   jit/vmdef.lua
ASM       lj_vm.o
CC        lj_err.o
CC        lj_bc.o
CC        lj_dispatch.o
CC        lj_record.o
CC        lj_crecord.o
CC        lj_ffrecord.o
CC        lib_base.o
CC        lib_math.o
CC        lib_bit.o
CC        lib_string.o
CC        lib_table.o
CC        lib_io.o
CC        lib_os.o
CC        lib_debug.o
CC        lib_jit.o
CC        lj_opt_fold.o
CC        lib_ffi.o
AR        libluajit.a
DYNLINK   libluajit.so
LINK      luajit
OK        Successfully built LuaJIT
make[6]: Leaving directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src'
==== Successfully built LuaJIT 2.1.0-beta3 ====
make[5]: Leaving directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit'
[ 87%] No install step for 'luajit'
[100%] Completed 'luajit'
make[4]: Leaving directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
[100%] Built target luajit
make[3]: Leaving directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
make[2]: Leaving directory '/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug'
cp -fL /home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src/luajit build/x86_64-linux-gnu-debug/luajit
rm -rf build/x86_64-linux-gnu-debug/jit
cp -r -fL /home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src/jit build/x86_64-linux-gnu-debug
gcc -L/home/david/software/koreader/base/build/x86_64-linux-gnu-debug/libs -Og -g -pipe -fno-omit-frame-pointer  -march=native -fPIC -I/home/david/software/koreader/base/thirdparty/luajit/build/x86_64-linux-gnu-debug/luajit-prefix/src/luajit/src -shared -Wl,-E -Wl,-rpath,'$ORIGIN' -o build/x86_64-linux-gnu-debug/libs/libblitbuffer.so blitbuffer.c
make[1]: *** No rule to make target 'luafilesystem/src/lfs.c', needed by 'build/x86_64-linux-gnu-debug/libs/libkoreader-lfs.so'.  Stop.
make[1]: Leaving directory '/home/david/software/koreader/base'
Makefile:109: recipe for target 'base/build/x86_64-linux-gnu-debug/luajit' failed
make: *** [base/build/x86_64-linux-gnu-debug/luajit] Error 2
Failed to build emulator! Try run with -v for more information.
[I]  ✘  ~/s/koreader  ➦ 658f5135  ±  bash
Initializing new SSH agent...
succeeded
Identity added: /home/david/.ssh/id_rsa (/home/david/.ssh/id_rsa)
Identity added: /home/david/.ssh/id_dsa (/home/david/.ssh/id_dsa)
LilArooni ~/software/koreader: sudo apt-get install build-essential git patch wget unzip \
> gettext autoconf automake cmake libtool nasm luarocks \
> libssl-dev libffi-dev libsdl2-dev libc6-dev-i386 xutils-dev linux-libc-dev:i386 zlib1g:i386
[sudo] password for david:
Reading package lists... Done
Building dependency tree
Reading state information... Done
autoconf is already the newest version (2.69-11).
automake is already the newest version (1:1.15.1-3ubuntu2).
build-essential is already the newest version (12.4ubuntu1).
cmake is already the newest version (3.10.2-1ubuntu2).
libc6-dev-i386 is already the newest version (2.27-3ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
libtool is already the newest version (2.4.6-2).
patch is already the newest version (2.7.6-2ubuntu1).
unzip is already the newest version (6.0-21ubuntu1).
zlib1g:i386 is already the newest version (1:1.2.11.dfsg-0ubuntu2).
luarocks is already the newest version (2.4.2+dfsg-1).
nasm is already the newest version (2.13.02-0.1).
xutils-dev is already the newest version (1:7.7+5ubuntu1).
gettext is already the newest version (0.19.8.1-6ubuntu0.1).
git is already the newest version (1:2.17.1-1ubuntu0.4).
libssl-dev is already the newest version (1.1.0g-2ubuntu4.3).
wget is already the newest version (1.19.4-1ubuntu2.1).
linux-libc-dev:i386 is already the newest version (4.15.0-46.49).
libsdl2-dev is already the newest version (2.0.8+dfsg1-1ubuntu1.18.04.3).
0 upgraded, 0 newly installed, 0 to remove and 205 not upgraded.
LilArooni ~/software/koreader: exit
[I]  ~/s/koreader  ➦ 658f5135  ±  weechat^C
[I]  ~/s/koreader  ➦ 658f5135  ±  ./kodev build -v
make -C base
make[1]: Entering directory '/home/david/software/koreader/base'
************ Building for MACHINE: "x86_64-linux-gnu-debug" **********
************ PATH: "/home/david/.rvm/gems/ruby-2.4.1/bin:/home/david/.rvm/gems/ruby-2.4.1@global/bin:/home/david/.rvm/rubies/ruby-2.4.1/bin:/home/david/.rvm/bin:/home/david/bin:/home/david/.local/bin:/home/david/.fzf/bin:/home/david/.tmux/plugins/tmuxifier/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/games:/usr/local/games:/snap/bin" **********
************ CHOST: "" **********
make[1]: *** No rule to make target 'luafilesystem/src/lfs.c', needed by 'build/x86_64-linux-gnu-debug/libs/libkoreader-lfs.so'.  Stop.
make[1]: Leaving directory '/home/david/software/koreader/base'
Makefile:67: recipe for target 'all' failed
make: *** [all] Error 2
Failed to build emulator! Try run with -v for more information.
```

**Comment by arooni** [comment]
BTW: 

I don't have a touch screen, it seems like arrow keys aren't supported?  I have to click the mouse/track pad to advance?

**Comment by Frenzie** [comment]
Page up/down.

Regarding fonts, might have to add something like this:

https://github.com/koreader/koreader/blob/54b0e85bddda37be23013f4e4063d50738710d9b/frontend/fontlist.lua#L65-L71

**Comment by minijackson** [comment]
I encountered the same build problem of "No rule to make target `luafilesystem/src/lfs.c'`". You just need to `git submodule update --init --recursive` from the top level directory to fetch the submodules that are stored inside a submodule ^^

**Comment by arooni** [comment]
update: still occurs on 2019.04 version:

[I]  ~/downloads  koreader
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/03/19-19:17:40
 [*] Version: v2019.04

ffi.load: SDL2
ffi.load: SDL2
ffi.load: blitbuffer
/usr/bin/koreader: line 36: 21008 Illegal instruction     ./reader.lua "${ARGS}"
