### ISSUE TITLE
Is there an option to not create a SDR folder for each folder opened ?

### ISSUE THREAD

**Issue by mooms06** [koreader/koreader#4831]
Hi !
I'm using KOReader on a PocketBook 740/InkPad 3.

I would rather like that KOReader will not create these folders, is it possible ?

Thank you.

**Comment by poire-z** [comment]
These .sdr directories contain some metadata.epub.lua with the settings/position/highlights for opened books.
If you opened a few to just look at them and are not willing to read them soon, you can hold on the file and choose "Purge .sdr" to remove that dir and its content and have the book unread.

Some things in the code might depend on them. It's also supposed to help if you move books around, or switch removable storage.
Previously, the book settings were saved in koreader/history/.

It seems you could get back that original behaviour by commenting one line in the code:
```diff
--- a/frontend/docsettings.lua
+++ b/frontend/docsettings.lua
@@ -85,7 +85,7 @@ end

 function DocSettings:ensureSidecar(sidecar)
     if lfs.attributes(sidecar, "mode") ~= "directory" then
-        lfs.mkdir(sidecar)
+        -- lfs.mkdir(sidecar)
     end
 end

```
Dunno what may break.

**Comment by mooms06** [comment]
Ça fonctionne, merci à toi.
It works, thank you.

**Comment by poire-z** [comment]
To have the above hack working on Android, create a `/sdcard/koreader/patch.lua` file with:
```lua
local orig_path = package.path
package.path = "frontend/?.lua;" .. package.path
local DocSettings = require("docsettings")
DocSettings.ensureSidecar = function() end
package.path = orig_path
```

Still some caveats: books won't be marked as opened in File browser.
So, more work would be needed if we'd wanted to have that as a real option.

**Comment by Iey4iej3** [comment]
I think that it is better to reopen this issue. These directory seem polluting the directory where PDFs are stored which does not seem to be satisfactory.

**Comment by Iey4iej3** [comment]
> To have the above hack working on Android, create a `/sdcard/koreader/patch.lua` file with:
> 
> ```lua
> local orig_path = package.path
> package.path = "frontend/?.lua;" .. package.path
> local DocSettings = require("docsettings")
> DocSettings.ensureSidecar = function() end
> package.path = orig_path
> ```
> 
> Still some caveats: books won't be marked as opened in File browser. So, more work would be needed if we'd wanted to have that as a real option.

This patch does not seem to work. `sdr` directories are still produced.
