### ISSUE TITLE
Color rendering cannot be disabled.

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#4832]
* KOReader version: koreader-android-arm-linux-androideabi-v2019.03.1.apk 
* Device: jdread(boyue) T65S

#### Issue
Color rendering cannot be disabled.

**Comment by poire-z** [comment]
Just for info: the color rendering toggle applies only to the rendering engines.
Book covers, images in Wikipedia lookup results... are still displayed in color.

**Comment by Frenzie** [comment]
The color rendering toggle doesn't seem to change. Something may have been slightly broken in #4580, but I don't have time to check whether it's the actual rendering or just updating the menu.
