### ISSUE TITLE
Crashes on latest android nightly

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#4833]
* KOReader version: koreader-v2019.03.1-41-g54b0e85_2019-03-21
* Device: Android

#### Issue

Crashes at launch, log shows:

```logcat
E luajit-launcher: Failed to run script: setupkoenv.lua:30: Not able to load dynamic library: libs/libmupdf.so
```

Referenced on https://github.com/koreader/koreader/issues/3517#issuecomment-475727528

**Comment by Frenzie** [comment]
Hm, I guess it must be something about https://github.com/koreader/koreader-base/pull/870 although I can't see anything wrong with it. Don't have time to debug today or tomorrow.

2f65fb9...54b0e85

**Comment by Frenzie** [comment]
If you'd included a tiny bit more of the log I could've seen it wouldn't be a time-consuming fix because the problem is pretty obvious from it. ;-)

```
03-25 09:41:31.896  3592  3605 V KOReader: ffi.load libs/libmupdf.so
03-25 09:41:31.896  3592  3605 V KOReader: dl.lua - dl.dlopen - library lname detected /data/user/0/org.koreader.launcher/files/libs/libmupdf.so
03-25 09:41:31.896  3592  3605 V KOReader:          dl.dlopen - opening needed /builds/koreader/nightly-builds/koreader/base/build/i686-linux-android/libs/libz.so.1 for /data/user/0/org.koreader.launcher/files/libs/libmupdf.so
03-25 09:41:31.896  3592  3605 E luajit-launcher: Failed to run script: setupkoenv.lua:30: Not able to load dynamic library: libs/libmupdf.so
```

I.e., that `/builds/koreader/nightly-builds/koreader/base/build/i686-linux-android/libs/libz.so.1` means the soname LDFLAG isn't being applied.
