### ISSUE TITLE
UI doesn't use the full screen on kobo aura H2O 2nd edition

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#4834]
* KOReader version: v2019.03.1-41-g54b0e85
* Device: Kobo Aura H2O 2nd Edition

#### Issue
UI does not fill the entire screen, leaving a white stripe on top, this is exacerbated when using night mode.

![IMG_20190324_174854](https://user-images.githubusercontent.com/50474/54882808-1ce25c80-4e5e-11e9-8bcd-882a8a864cad.jpg)

![IMG_20190324_174810](https://user-images.githubusercontent.com/50474/54882798-02a87e80-4e5e-11e9-8221-a2ea00eb07e6.jpg)

I'm not sure if it's some local hardware fault where my screen is misaligned. Is there a way to shift the screen coordinates?

**Comment by Frenzie** [comment]
Presuambly the H2O2v2 doesn't cover up part of the screen with the bezel and no one's mentioned it.

https://github.com/koreader/koreader/blob/54b0e85bddda37be23013f4e4063d50738710d9b/frontend/device/kobo/device.lua#L137-L151

You can simply comment out the viewport, but if part of the screen is still hidden by the bezel you'll need to adjust it instead.

**Comment by BrainDamage** [comment]
Ok, I've done a bit of experimentation:
first of all, my device is  Kobo Aura H2O2, KoboSnow ( I guess there was a miscommunication from my side about naming meant by 2nd edition )

second: the bezel does not cover the top part, but does cover partially the bottom, I have tested this by making the image much smaller, using night more and then gradually expanding towards the borders using successive trials.

the final geometry is:
viewport = Geom:new{x=0, y=0, w=1080, h=1436}
excluding the bottom 4 pixels

... which also explains why I always had issues with grabbing the ui from the bottom, the activation margins were actively much smaller than the screen due to being partially covered

**Comment by NiLuJe** [comment]
Which revision of the H2O2 is that? The initial Mk. 6 version, or the Mk. 7 revision ?

Would it be possible for you to take a screengrab over SSH, from within Nickel, with fbgrab ? That would eliminate all the guesswork ;).

**Comment by BrainDamage** [comment]
![out](https://user-images.githubusercontent.com/50474/54884451-8a4bb880-4e71-11e9-9177-0709ab08424c.png)

resolution seems to be 1080x1440

as for the revision: where am I supposed to check? I know the serial number, but I don't know how that translates to a mk. version

**Comment by NiLuJe** [comment]
If that was indeed from fbgrab and not Nickel's own screenshot function, then it doesn't appear that there's a viewport in effect at all ;).

As that device appears to be a rare beast, I have a few other things to ask, some of them related to this, others to an upcoming change I'm working on ;).

* You can identify the device by running:
`tail -c 3 /mnt/onboard/.kobo/version`

* You can double-check the lack of viewport by strace'ing nickel during a full-screen refresh (my usual test would be opening and closing the search window from the Homescreen).

`strace -fitv -e trace=ioctl -p $(pidof nickel)`

(You'll need a Kobo-specific strace build, available [here]( http://files.ak-team.com/niluje/mrpub/Other/strace-kobo.tar.gz).

It should look something like this:

```
strace: Process 572 attached with 11 threads
[pid   572] 00:03:42 [2f65d1f6] ioctl(3, MXCFB_SEND_UPDATE_V1_NTX, {update_region={top=11, left=970, width=110, height=120}, waveform_mode=WAVEFORM_MODE_AUTO, update_mode=UPDATE_MODE_PARTIAL, update_marker=642, temp=TEMP_USE_AMBIENT, flags=0, alt_buffer_data={virt_addr=(nil), phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}, 0x7efc932c) = 0
[pid   572] 00:03:43 [2f65d1f6] ioctl(3, MXCFB_SEND_UPDATE_V1_NTX, {update_region={top=11, left=0, width=1080, height=1429}, waveform_mode=WAVEFORM_MODE_AUTO, update_mode=UPDATE_MODE_FULL, update_marker=643, temp=TEMP_USE_AMBIENT, flags=0, alt_buffer_data={virt_addr=(nil), phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}, 0x7efc932c) = 0
[pid   572] 00:03:43 [2f65d1f6] ioctl(3, MXCFB_SEND_UPDATE_V1_NTX, {update_region={top=271, left=58, width=964, height=560}, waveform_mode=WAVEFORM_MODE_AUTO, update_mode=UPDATE_MODE_PARTIAL, update_marker=644, temp=TEMP_USE_AMBIENT, flags=0, alt_buffer_data={virt_addr=(nil), phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}, 0x7efc932c) = 0
[pid   572] 00:03:46 [2f65d1f6] ioctl(3, MXCFB_SEND_UPDATE_V1_NTX, {update_region={top=34, left=956, width=101, height=100}, waveform_mode=NTX_WFM_MODE_A2, update_mode=UPDATE_MODE_PARTIAL, update_marker=645, temp=TEMP_USE_AMBIENT, flags=EPDC_FLAG_FORCE_MONOCHROME, alt_buffer_data={virt_addr=(nil), phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}, 0x7efc84e4) = 0
[pid   572] 00:03:47 [2f65d1f6] ioctl(3, MXCFB_SEND_UPDATE_V1_NTX, {update_region={top=11, left=0, width=1080, height=1429}, waveform_mode=WAVEFORM_MODE_AUTO, update_mode=UPDATE_MODE_FULL, update_marker=646, temp=TEMP_USE_AMBIENT, flags=0, alt_buffer_data={virt_addr=(nil), phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}, 0x7efc932c) = 0
```

(Interrupt with Ctrl+C).

Notice the `{top=11, left=0, width=1080, height=1429}`, which is the H2O viewport (top 11 pixels behind the bezel), the same one currently wrongly applied on your device ;).

* I'd like to know a few things about the device's reaction to rotation, so I'm attaching an FBInk build to this message, I'd like to see the output from a few things (in that particular order):

`fbink -Mmp 'Hello'`

And then

`rota`

That *may* not restore the proper rotation on exit, something you'll be able to correct via fbdepth (I'm expecting the original rotation to be 3, possibly 1, so, `fbdepth -r 3` ;).
[fbink-1.12.1-34.tar.gz](https://github.com/koreader/koreader/files/3000975/fbink-1.12.1-34.tar.gz)

Thanks! :)

**Comment by NiLuJe** [comment]
(If you're doing all this over WiFi and not USBNet, I'm usually leaving the WiFi popup open for quick tests like that, just to ensure WiFi won't be shut off ;)).

**Comment by BrainDamage** [comment]
> If that was indeed from fbgrab and not Nickel's own screenshot function, then it doesn't appear that there's a viewport in effect at all ;).

yes, that was through your own tool which I've uploaded through sftp and executed through ssh remotely.

>     * You can identify the device by running:
>       `tail -c 3 /mnt/onboard/.kobo/version`
```

tail -c 3 /mnt/onboard/.kobo/version
374
```

> 
>     * You can double-check the lack of viewport by strace'ing nickel during a full-screen refresh (my usual test would be opening and closing the search window from the Homescreen).
> 
> 
> `strace -fitv -e trace=ioctl -p $(pidof nickel)`
```

[pid  5875] 06:52:33 [2f6a01f6] ioctl(3, MXCFB_SEND_UPDATE_V1_NTX, {update_region={top=0, left=0, width=1080, height=1440}, waveform_mode=WAVEFORM_MODE_AUTO, update_mode=UPDATE_MODE_FULL, update_marker=299, temp=TEMP_USE_AMBIENT, flags=0, alt_buffer_data={virt_addr=(nil), phys_addr=0, width=0, height=0, alt_update_region={top=0, left=0, width=0, height=0}}}, 0x7ee9af3c) = 0
```


>     * I'd like to know a few things about the device's reaction to rotation, so I'm attaching an FBInk build to this message, I'd like to see the terminal output from a few things (in that particular order):
> 
> 
> `fbink -Mmp 'Hello'`
```

FBInk] Detected a Kobo H2O² (374)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 265 dpi
[FBInk] Variable fb info: 1080x1440, 32bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fontsize set to 24x24 (IBM base glyph size: 8x8)
[FBInk] Line length: 45 cols, Page size: 60 rows
[FBInk] Horizontal fit is perfect!
[FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Printing string 'Hello' @ column 0 + 0px, row 0 + 0px (overlay: N, no BG: N, no FG: N, inverted: N, flashing: N, centered: Y, halfway: Y, left padded: Y, right padded: N, clear screen: N, dithered: N, skip refresh: N, font: 0, font scaling: x0)
```


> 
> And then
> 
> `rota`
> 
```

Variable fb info: 1080x1440, 32bpp @ rotation: 1 (Clockwise, 90°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes

FB_ROTATE_UR to FB_ROTATE_CCW, +1 increments
Setting rotate to 0 (Upright, 0°)
Rotate is now 0 (Upright, 0°)
Variable fb info: 1440x1080, 32bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 5760 bytes
Setting rotate to 1 (Clockwise, 90°)
Rotate is now 1 (Clockwise, 90°)
Variable fb info: 1080x1440, 32bpp @ rotation: 1 (Clockwise, 90°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes
Setting rotate to 2 (Upside Down, 180°)
Rotate is now 2 (Upside Down, 180°)
Variable fb info: 1440x1080, 32bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 5760 bytes
Setting rotate to 3 (Counter Clockwise, 270°)
Rotate is now 3 (Counter Clockwise, 270°)
Variable fb info: 1080x1440, 32bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes

FB_ROTATE_UR to FB_ROTATE_CCW, +2 increments
Setting rotate to 0 (Upright, 0°)
Rotate is now 0 (Upright, 0°)
Variable fb info: 1440x1080, 32bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 5760 bytes
Setting rotate to 2 (Upside Down, 180°)
Rotate is now 2 (Upside Down, 180°)
Variable fb info: 1440x1080, 32bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 5760 bytes

FB_ROTATE_CW to FB_ROTATE_CCW, +2 increments
Setting rotate to 1 (Clockwise, 90°)
Rotate is now 1 (Clockwise, 90°)
Variable fb info: 1080x1440, 32bpp @ rotation: 1 (Clockwise, 90°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes
Setting rotate to 3 (Counter Clockwise, 270°)
Rotate is now 3 (Counter Clockwise, 270°)
Variable fb info: 1080x1440, 32bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes

FB_ROTATE_UR to FB_ROTATE_CCW, +2 increments, intermerdiary rota if ==
Setting rotate to 0 (Upright, 0°)
Rotate is now 0 (Upright, 0°)
Variable fb info: 1440x1080, 32bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 5760 bytes
Setting rotate to 2 (Upside Down, 180°)
Rotate is now 2 (Upside Down, 180°)
Variable fb info: 1440x1080, 32bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 5760 bytes

FB_ROTATE_CW to FB_ROTATE_CCW, +2 increments, intermerdiary rota if ==
Setting rotate to 1 (Clockwise, 90°)
Rotate is now 1 (Clockwise, 90°)
Variable fb info: 1080x1440, 32bpp @ rotation: 1 (Clockwise, 90°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes
Setting rotate to 3 (Counter Clockwise, 270°)
Rotate is now 3 (Counter Clockwise, 270°)
Variable fb info: 1080x1440, 32bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 4352 bytes
```


so it seems that indeed that the viewport is equal to the entire surface

**Comment by Frenzie** [comment]
Curious, so Nickel just doesn't care that they're missing 4 pixels?

But @NiLuJe you're sure that a fullscreen refresh will only be a viewport refresh? A fullscreen refresh doesn't really seem like the kind of scenario where you'd care about those few pixels. :-)

**Comment by NiLuJe** [comment]
@BrainDamage: Fantastic, many thanks! So, the Mk. 6 one, which probably
means we can kill the viewport in the later revision, too ;).

@Frenzie: Yeah, and yet it is honored there by Nickel, c.f.; my H2O snippet
;).

You can also enable Nickel debugging and check the reader's viewport
dimensions, but that's slightly more annoying to set up and check ;).

**Comment by NiLuJe** [comment]
I'd be willing to chalk the 4px thingy to either slightly less accurate touch input near the edges, of the usual couple of pixels that are hard to see unless looked at at a shallower angle.

You can experiment by printing a 4px high line at the bottom of the screen with fbink:

`fbink -g file=4px.png,valign=BOTTOM -v`
![4px](https://user-images.githubusercontent.com/111974/54936159-26cd9380-4f22-11e9-9359-e4dcea5a0a6b.png)
