### ISSUE TITLE
FR: Make gesture intervals configurable

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#4842]
* KOReader version: v2019.03/master
* Device: all

#### Issue
They're currently hard-coded.

https://github.com/koreader/koreader/blob/cc9f58687a8a8504d9a81928c707fced51e79b6d/frontend/device/gesturedetector.lua#L53-L56

See https://www.mobileread.com/forums/showthread.php?p=3824560#post3824560

**Comment by robert00s** [comment]
Where we should put config dialog?
Option 1: `Setting -> Taps and gestures`
Option 2: `Tools -> Advanced settings`

**Comment by Frenzie** [comment]
Taps & gestures works for me. :-)

**Comment by robert00s** [comment]
I'm not sure that limit values are correct.
![obraz](https://user-images.githubusercontent.com/22982594/61459302-be8d3c80-a96c-11e9-865e-4f532ee4f04f.png)

**Comment by poire-z** [comment]
If I would play with that, I'll be scared moving away from the defaults, and not being able to reset back to them :)
So, I guess you could show the defaults - or if that would take too much space and make the titles multi-lines, you could add a 3rd button: `Use defaults` (as in `Hyphenation>Left/right minimal sizes`).

**Comment by robert00s** [comment]
Thanks for hint :)

Option 1: (use default button)
![obraz](https://user-images.githubusercontent.com/22982594/61461845-dc10d500-a971-11e9-8a3a-75b9b2e515fb.png)

Option 2: (submenu for each interval + individual widget)

![obraz](https://user-images.githubusercontent.com/22982594/61462017-39a52180-a972-11e9-9a6f-05aa89fc3133.png)


![obraz](https://user-images.githubusercontent.com/22982594/61461994-28f4ab80-a972-11e9-95bb-3ff98436b93d.png)

**Comment by Frenzie** [comment]
Do they really need individual limits? I'd just give 'em all a limit from 50-2000 or something.

**Comment by robert00s** [comment]
We can set all limits from 100 to 2000.

**Comment by poire-z** [comment]
The numberpicker is prettier and easier to use (with a default button too, and may be the current value and if it is the default shown in the menu).

But I don't know if these 5 intervals have any relations (like: one shouldn't be smaller than some other), where it would be easier to have a view of them all with option 1.

**Comment by Frenzie** [comment]
> We can set all limits from 100 to 2000.

Alright.

> But I don't know if these 5 intervals have any relations

Only in a real-world way. Hold at fewer than 50 ms makes it hard to tap because most taps become holds, a swipe at fewer than 100 ms can make it hard to swipe because swipes may take "a while", etc.

The defaults have very large safety margins roughly based on Windows/Android/Mac OS/iOS/Linux DE standards, where the hopeful assumption is that with the budgets on the Windows/Android/Mac front they've done actual user testing among different types of users, and that it wasn't just randomly made up by someone back in the '70s or '80s. Because for a focus group of just me, most of those values could be reduced to a third of what they are. (Mainly talking about values like double tap and hold. Detecting swipes for a little longer is pretty harmless.)

**Comment by LucyOne** [comment]
I find this feature interesting, but what is it actually good for?

**Comment by Frenzie** [comment]
The benefit is primarily to make the program more responsive if that works for you, and in rarer circumstances it might make it easier to use. If you set double tap to 100 ms it makes it more bearable, for example, although it's still an annoying delay and double tap best remains disabled.

Presumably the most interesting one for most users will be hold delay. 2 seconds is a fairly safe value, hard to trigger accidentally, but if you set it to 200 ms you only need to hold for a short while. Or an in-between like 1 s which is still a lot more responsive yet hard to trigger accidentally.
