### ISSUE TITLE
Kindle Legacy March 2019 build - Crashes when navigating top menu bar

### ISSUE THREAD

**Issue by Tony556** [koreader/koreader#4845]
* KOReader version: March 2019
* Device: Kindle 3 and 4

#### Issue and steps to reproduce:
![image](https://user-images.githubusercontent.com/4276171/55037350-b46cba00-4fda-11e9-9426-05c57d50fec8.png)

Clicking the center in the 5-way here crashes the app.

##### `crash.log` (if applicable)
https://gist.github.com/Tony556/02a8e9c3e577a2e094e9c969ca5f00ea
https://gist.github.com/Tony556/2bb4ece14f9255f5262726fcb24e8dba

**Comment by Tony556** [comment]
It seems to only be the gear, and the others seems to work fine

**Comment by NiLuJe** [comment]
Confirmed on the latest nightly, too.

```
./luajit: frontend/ui/widget/touchmenu.lua:90: attempt to index a nil value
stack traceback:
        frontend/ui/widget/touchmenu.lua:90: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/ui/widget/touchmenu.lua:569: in function 'updateItems'
        frontend/ui/widget/touchmenu.lua:646: in function 'switchMenuTab'
        frontend/ui/widget/touchmenu.lua:311: in function 'callback'
        frontend/ui/widget/iconbutton.lua:106: in function 'action'
        frontend/ui/uimanager.lua:708: in function '_checkTasks'
        frontend/ui/uimanager.lua:985: in function 'handleInput'
        frontend/ui/uimanager.lua:1071: in function 'run'
        ./reader.lua:216: in main chunk
        [C]: at 0x000139b1
```

**Comment by NiLuJe** [comment]
(I have been seeing a few of those `sizeUtf8Text called without text` everywhere, FWIW).

**Comment by NiLuJe** [comment]
@Frenzie: It's apparently trying to show taps_and_gestures despite it behind an ifTouchDevice() block :?

@poire-z: This avoids the crash, but leaves a blank menu entry.

```
diff --git a/frontend/ui/rendertext.lua b/frontend/ui/rendertext.lua
index 6a0ca34c..f5095652 100644
--- a/frontend/ui/rendertext.lua
+++ b/frontend/ui/rendertext.lua
@@ -157,7 +157,7 @@ end
 function RenderText:sizeUtf8Text(x, width, face, text, kerning, bold)
     if not text then
         logger.warn("sizeUtf8Text called without text");
-        return
+        return { x = 0, y_top = 0, y_bottom = 0 }
     end
 
     -- may still need more adaptive pen placement when kerning,
```

**Comment by poire-z** [comment]
> This avoids the crash, but leaves a blank menu entry. Does it make sense as a better than nothing safety?

Of course. That fix to avoid the crash lgtm :) (I thought about having callers just check for `text ~= nil` before calling, but your fix actually returns something that is true, nil text has 0 width :)

The blank menu entry is another (less major :) thing that I guess have to be fixed elsewhere.

**Comment by Frenzie** [comment]
Might be related to those submenu entries.
