### ISSUE TITLE
Now Reading Menu

### ISSUE THREAD

**Issue by ReaLx3m** [koreader/koreader#4849]
It would be grat if we could have a menu with functionality like kobos top part of home screen, with books thet user is reading currently.
Already present "History" menu is a good starting point.The new one would have to contain books/comics that are <100% read, and would get automatically removed when reached 100% or if marked finished.
Or maybe it would be easier to add user selectable option to "History", so books with 100% or marked as finished can be auto removed.

**Comment by KenMaltby** [comment]
Perhaps an additional "end of book" option?  Maybe; "Mark as finished and remove from History"?  By the way, you can long press an entry in history and select the "Remove from history".

**Comment by ReaLx3m** [comment]
I know about long press to remove. While if one uses the reader only for books it could be considered bearable, but bigger issue is with reading comic books.As they are pretty short reads, the history menu gets cluttered pretty quick, and doing it manually is a big pita.
