### ISSUE TITLE
PB Inkpad3 does not start with last nightly release

### ISSUE THREAD

**Issue by pepefil** [koreader/koreader#4851]
* KOReader version:
* Device: PB Inkpad3

It's a segmentation fault issue. Nightly v2019.03.1-47 woks well.

Crash.log says:
[*] Current time: 03/29/19-11:58:17
 [*] Version: v2019.03.1-58-g7210fb4_2019-03-27

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:30: Not able to load dynamic library: libSDL2-2.0.so
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
SDL not loaded:	./setupkoenv.lua:30: Not able to load dynamic library: SDL
ffi.load: inkview
03/29/19-11:58:17 INFO  SoftwareVersion:  U740.5.19.660
ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
PB FB: smem_len    : 2637824
PB FB: line_length : 1872
PB FB: xres        : 1872
PB FB: xres_virtual: 1872
PB FB: yres        : 1404
PB FB: yres_virtual: 1404
PB FB: bpp         : 8
PB FB: xres_virtual -> 1888
PB FB: yres_virtual -> 1408
PB FB: line_length -> 1888
PB FB: yres_virtual => 1408
PB FB: line_length <- 1872
FB: computed size: 2637824
FB: id           : 
FB: smem_len     : 2637824
FB: line_length  : 1872
FB: xres         : 1872
FB: xres_virtual : 1888
FB: yres         : 1404
FB: yres_virtual : 1408
FB: bpp          : 8
Segmentation fault

**Comment by Frenzie** [comment]
Pinging @NiLuJe. This is probably related to #4847.

**Comment by NiLuJe** [comment]
Eh, probably needs to reset xres_virtual when we reset line_length ;).

**Comment by NiLuJe** [comment]
See if that commit helps?

**Comment by pepefil** [comment]
I've modified the file framebuffer_linux.lua with changes you suggested on  commit 00ec8e4 , and now v2019.03.1-58 starts and runs well. Huge thanks, @NiLuJe.

**Comment by NiLuJe** [comment]
@pepefil: Fantastic, thanks for the quick feedback, it'll be fixed in tomorrow's nightly ;).
