### ISSUE TITLE
Likebook Mars - Refresh is happening or not?

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#4860]
How to make sure that refresh is working?
Using Koreader e-reader in Mars in a epub file I can't perceive a refresh. I can perceive a refresh using Koreader in a Kobo device so I think that I know how is the the behavior. The default Mars reader shows a refresh each 5 pages. I think I should see a refresh with Koreader in Mars too, right? However the text looks nice. I'm not seeing ghost texts even a pass 30 pages. Didn't tried hundreds pages yet.
The behavior is different If I open a cbz fil. I see that the refresh is happening each page, even the dewatermark option is working. Maybe are the images refreshes being handled direct by the Mars system?

**Comment by Frenzie** [comment]
Special case support implemented in https://github.com/koreader/koreader/pull/4818. More generally speaking, the einkTest.apk will tell you if special case support is possible.

If you're feeling adventurous you can grab a development build from http://build.koreader.rocks/download/nightly/

**Comment by hugleo** [comment]
Hi, for einkTest.apk is working.

I forget to mention that I'm using the night build file koreader-android-arm-linux-androideabi-v2019.03.1-64-g8f019b8_2019-03-30.apk

**Comment by pazos** [comment]
@hugleo: I just fixed a typo. I forgot to include these devices as part of EINK devices list so it doesn't work since the app things we have no supported driver. It will be fixed in https://github.com/koreader/koreader/pull/4862
