### ISSUE TITLE
Table of contents is not working 

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#4861]
If I test the table of contents in Kobo glo the action doesn't go direct to the the chapter title. I need back 5 pages, sometimes 10 pages.

If I test in the Likebook Mars, a android device, then each item in table of contents that I select I'm being redirect to the book cover.

**Comment by Frenzie** [comment]
What kind of document is this? Is it freely available?

**Comment by hugleo** [comment]
Epub, yes. But is not the file. I copy the file and upload the same file to another folder and the table of contents worked normally.
So I deleted the "broken file" and moved the other file to the same folder. The file is the same and the same name as before. And after that process tabled of contents is working normally.

I do know what could be happened but I remember of installed a old koreader git version before and uninstall. I removed some .sdr files, and koreader folder in some place, no sure if I remove all the cache files though.  After that I updated the boyue os since was using a very old version and install koreader again today (most recent git build night). Maybe boyue os missed something with files and caches that occasioned that unexpected behavior to Koreader. Or maybe some koreader cached files.

Since I can't reproduce the problem anymore we can close this issue.

**Comment by Eduardomb22** [comment]
I think it is a problem with the cached files, sometimes I get this too. All itens at ToC will go the book cover and have position number 1 in front of it.

**Comment by hugleo** [comment]
Happened again here after I moved a book to another folder (not used koreader for this, use my own mtp file manager). But I just manually removed the /koreader/cache folder and worked! Maybe a good thing clean the cache folder when koreader restart?

**Comment by poire-z** [comment]
The cache is useful for quicker load. And the crengine code has some checks to see if a cache is valid, and conformed to your current settings. Depending on what it noticed has changed (from what's cached in the cache), it can reload the book, or keep the DOM (the tree of HTML nodes and text) and just do a re-rendering.
Next time you witness that, can you try just changing the font size (and later back) to see if the forced re-rendering is enough to build a working TOC ?
(If you didn't move the .sdr and the previous settings, using the default settings should have made crengine noticed a change in layout, and trigger a re-rendering.)
Also check you crash.log, to see if crengine did output some messages at that moment (usually look like `CRE WARNING: blah blah)`
This happened on the same KOReader version? no KOReader update involved?

**Comment by hugleo** [comment]
yes, update KOReader too, but have been updating all week and problem just tday when I also moved the files. As for .sdr files I didn't have any because before was in a read only folder. Koreader created after that I moved. Before the cache file I removed the history folder too without success. If I get this more times I'll do the mentioned tests ;)

**Comment by Eduardomb22** [comment]
It does works if you change the font size. I can't check crash.log, because I haven't got the problem now.

**Comment by poire-z** [comment]
@hugleo @Eduardomb22 : please report if you feel this has been solved by #5017 (nightly >= v2019.05-3-geace8d2_2019-05-09) - or if it's still happening.

**Comment by hugleo** [comment]
Haven't seen the problem for long time. Now that you send me a rabbit's foot I'm deeply feeling in my heart that I'll not face that problem anymore.

**Comment by Frenzie** [comment]
I'll close this issue then. Feel free to reopen if necessary.
