### ISSUE TITLE
FR: Support <ruby> in epub files

### ISSUE THREAD

**Issue by cges30901** [koreader/koreader#4868]
* KOReader version: 2019.03.1
* Device: Android and Linux

#### Issue
I think it will be great if KOReader can support `<ruby>` in epub files.

Here is a test file: [ruby.zip](https://github.com/koreader/koreader/files/3034108/ruby.zip)

In KOReader it looks like this: 
![螢幕快照_2019-04-02_21-17-19](https://user-images.githubusercontent.com/19516286/55406110-0e96ed80-558e-11e9-96ae-ef23d89261bb.png)

In Calibre: 
![螢幕快照_2019-04-02_21-27-30](https://user-images.githubusercontent.com/19516286/55406167-253d4480-558e-11e9-9283-2ee4c96ff78c.png)

**Comment by Frenzie** [comment]
That's probably non-trivial I'm afraid. Interestingly, Opera/Presto doesn't support it either.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby

**Comment by poire-z** [comment]
Mentionning some possible hacky solution at https://github.com/koreader/koreader/issues/6223#issuecomment-638834510 (that I couldn't make it work with the OP test file though...)

**Comment by poire-z** [comment]
And some (still a bit hacky) proper implemenation in https://github.com/koreader/crengine/pull/347 which will give us:
<kbd>![image](https://user-images.githubusercontent.com/24273478/84680241-a9c97800-af32-11ea-9571-ce6db21376bb.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/84680345-d087ae80-af32-11ea-80a8-7f691531dbe2.png)</kbd>

**Comment by poire-z** [comment]
Support for ruby provided by #6305 .
