### ISSUE TITLE
the standby with the cover does not work anymore

### ISSUE THREAD

**Issue by davicraquette** [koreader/koreader#4870]
* KOReader version: 2019.3.1-72
* Device:kobo aura one
hello, since this last version the folding of the cover of the e-reader does not put in standby any more. Conversely, the opening of the cover does not activate the reader any more.This problem appeared with version 69 then corrected with version 70 but again in default with the latest version

**Comment by NiLuJe** [comment]
Worksforme on -69.

What is missing is a "This needs a restart" popup on the "Ignore sleepcover events" checkbox I added to the Device menu.
Il'l fix that.

In the meantime, @davicraquette , double-chekc that you don't have that enabled, and restart KOReader ;).

**Comment by davicraquette** [comment]
indeed, and at first, the restart has solved the problem. thank you

**Comment by NiLuJe** [comment]
Fixed via #4871
