### ISSUE TITLE
OPDS viewer shows old data

### ISSUE THREAD

**Issue by alethiophile** [koreader/koreader#4873]
* KOReader version: v2018.12-53-gd113cb9_2019-01-18
* Device: Kobo Forma

#### Issue
When browsing the calibre OPDS catalog, koreader shows old (presumably cached?) listings, despite the fact that the calibre library has been updated (and the server restarted) in the interim. I cannot find any option to refresh the listings.

#### Steps to reproduce
1. Connect to a Calibre OPDS catalog
2. View the "by newest" listing
3. Add books to the Calibre library and restart the server
4. View the OPDS listing again, note absence of new items

**Comment by KenMaltby** [comment]
I just restart KOReader.

**Comment by alethiophile** [comment]
A usable workaround, but irritating.

For what it's worth, it looks like Calibre does ship an `updated` timestamp in its OPDS listings, so it should be possible to detect changes automatically.

**Comment by Frenzie** [comment]
@alethiophile Could you give #4874 a try? All you need to do is overwrite ui/widgets/opdsbrowser.lua with [this one](https://raw.githubusercontent.com/koreader/koreader/62e0c0208c874e26d8ecbb334b82edce6c6c5b3d/frontend/ui/widget/opdsbrowser.lua).

**Comment by alethiophile** [comment]
@Frenzie It looks like now it works fine. Thanks.
