### ISSUE TITLE
Double tap lower corners

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#4877]
The shortcuts that can be assigned to the lower corner's tap are awesome!
I was trying to find other ways to access some more of these shortcuts (since top corners are already used) and thought about the Double-Tapping of the all the corners.
Is it possible?

**Comment by Frenzie** [comment]
Double tapping delays all taps by 300 ms by default, also see #4842. Of course should you already have double tap enabled, it wouldn't introduce any additional delay.

It'd probably be relatively simple to add but I wouldn't recommend enabling double tap. 50-100 ms is better for me, but still noticeably slows down regular taps.

**Comment by Frenzie** [comment]
PS There's also hold. Currently the entire bottom of the screen brings up skim to.

**Comment by noembryo** [comment]
Yes, Pressing and holding the corners!
That will be nice! :o)

**Comment by Frenzie** [comment]
@noembryo Btw, which device do you have? I always forget about it, but there's also two-finger tap.

**Comment by noembryo** [comment]
Kobo Glo (original) no multi touch here :o)
When using the Android mod though, I could use multi touch nicely...
With the kobo's kernel its disabled :o(

**Comment by Frenzie** [comment]
Yeah, same on the H2O, hence why I forget it exists.

One wonders if there's a sensible way to automate this stuff away... (I.e., we have this corner and we want it to be configurable for...)

**Comment by noembryo** [comment]
Its the old "Screen Zone Editor" enhancement, that uses a common shortcut menu for every zone..

**Comment by Frenzie** [comment]
I assume it's not KOReader related? :-p

**Comment by noembryo** [comment]
What I meant is that we need (in KOReader) a "Screen Zone Editor", but when I asked about it a *long* time ago, there wasn't any response, so I refer to it as the "old" one ;o)

**Comment by Frenzie** [comment]
My "wondering" above was just rhetorical in any case, and not about UI/UX.

The multiswipes are dynamic & basically auto-generated. These tap zones aren't. Adding more gestures would result in a lot of duplication. But I suppose I shouldn't do anything too fancy. Just some variables for the zones should probably do the trick.

https://github.com/koreader/koreader/blob/22db71c07549ffc59196f1f27cd9bb162eacd6d7/frontend/apps/reader/modules/readergesture.lua#L585-L614

The way CoolReader has the touch zone configuration is pretty cool.

**Comment by LucyOne** [comment]
I would prefer double tapping the lower corner instead of "hold corners" which interferes with highlighting and dictionary lookup.
