### ISSUE TITLE
WebDAV: wifi prompt, empty folder

### ISSUE THREAD

**Issue by Incog5** [koreader/koreader#4879]
* KOReader version: 2019.04
* Device: Kindle Paperwhite 10

1)
When using webDAV, I get a prompt to turn on Wifi when it's already on and connected.
DropBox uses isOnline, ftp and webDAV use isConnected
I changed NetworkMgr:isConnected to NetworkMgr:isOnline to eliminate this issue.
https://github.com/koreader/koreader/blob/de9d675de29c1c80e07818aa89ab4a6dc4b149be/frontend/apps/cloudstorage/cloudstorage.lua#L112-L133

2) 

Empty Folder 
related to:
https://github.com/koreader/koreader/issues/4243

Here is a test connection you can freely use, which contains a epub file in the test folder, but does NOT work in koreader and shows empty folder:

In windows explorer or any WebDAV program open a secure link (no username/password):
https://dhqidxb3g84146wjwta9xpe.webdav.drivehq.com/
which will redirect to
\\dhqidxb3g84146wjwta9xpe.webdav.drivehq.com@SSL\DavWWWRoot
contains the test file:
Metamorphosis-jackson.epub

![image](https://user-images.githubusercontent.com/14378320/55680527-cccac600-5944-11e9-8f84-c869e67d4196.png)

cloudstorage.lua

> -- we can read Lua syntax here!
> return {
>     ["cs_servers"] = {
>         [1] = {
>             ["address"] = "https://dhqidxb3g84146wjwta9xpe.webdav.drivehq.com/ssl/DavWWWRoot/",
>             ["password"] = "nopass",
>             ["url"] = "",
>             ["username"] = "nousername",
>             ["name"] = "DriveHQ",
>             ["type"] = "webdav"
>         }
>     }
> }

I've tried the ["address"] without "/ssl/DavWWWRoot/"
as well as adding /ssl/DavWWWRoot/ to  ["url"]

**Comment by Frenzie** [comment]
@Incog5 Thanks for reporting!

Could you please investigate what part of the ping command is breaking down?

```
ping -c1 -w2 $(/sbin/route -n | awk '$4 == "UG" {print $2}')
```

https://github.com/koreader/koreader/blob/22db71c07549ffc59196f1f27cd9bb162eacd6d7/frontend/ui/network/manager.lua#L100-L107

```
$ /sbin/route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    100    0        0 eth3
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     100    0        0 eth3
$ /sbin/route -n | awk '$4 == "UG" {print $2}'
192.168.1.1
$ ping -c1 -w2 $(/sbin/route -n | awk '$4 == "UG" {print $2}')
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.389 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.389/0.389/0.389/0.000 ms
```

Pinging @robert00s

**Comment by Incog5** [comment]
I just ran a test from my computer and found what the issue is, I'm connected to my guest hotspot and ping fails to the router ip. I think this is a common security feature with guests hotspots, it blocks the port 80 to the gateway to prevent guests from accessing the configuration of the router via webUI but also blocks IGMP/ping to the router.

I'm not an network expect, but I suggest the following possible fix:

A) if ping to the gateway fails, run an additional ping to 8.8.8.8 or 1.1.1.1, before declaring wifi is NOT connected

B) use traceroute instead of ping to determine connection status: tracert -h 1 8.8.8.8, shows 192.168.1.1 as the first hop on my restricted network.

C) use DNS or a captive wallgarden check
example:
https://stackoverflow.com/questions/13958614/how-to-check-for-unrestricted-internet-access-captive-portal-detection

**Comment by Incog5** [comment]
I just took a look at:

https://github.com/koreader/koreader/blob/89c17092e8358b70ece568aa023e3cc91072063a/frontend/ui/network/manager.lua#L109-L116

Looks like there is already a check for hotspot via DNS.  Although I suggest using http get "http://www.msftncsi.com/ncsi.txt", because a hotspot portal might return correct DNS entries but redirect/block http://www.msftncsi.com/ncsi.txt 


I think a possible solution would be to check is a user isOnline() first, if they are Online, that means they are connected to wifi by default (regardless if the gateway is pingable or not)

If they are not Online, you can check isConnected( for users that just use local network services)

**Comment by Frenzie** [comment]
> I think a possible solution would be to check is a user isOnline() first, if they are Online, that means they are connected to wifi by default (regardless if the gateway is pingable or not)

First is unacceptable, but as an additional check in case of failure it can be done. Just look at this best-case scenario, .5 ms vs 12 ms. And you need to allow for a whole lot more than 12 ms, at the very least 1 s.

```
$ ping -c1 -w2 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.424 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.424/0.424/0.424/0.000 ms
```
```
$ ping -c1 -w2 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=121 time=11.9 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 11.860/11.860/11.860/0.000 ms
```

> B) use traceroute instead of ping to determine connection status: tracert -h 1 8.8.8.8, shows 192.168.1.1 as the first hop on my restricted network.

That's even slower. *Much* slower. Also, that's `traceroute`. ;-)

> Although I suggest using http get "http://www.msftncsi.com/ncsi.txt", because a hotspot portal might return correct DNS entries but redirect/block http://www.msftncsi.com/ncsi.txt

Well yes, I already suggested that in the comment. :-P

**Comment by Incog5** [comment]
That would be perfect, an additional check to prevent a false negative :-)

I'm on windows, so I was using tracert.  Not so experienced in linux :-)

Yes I took the suggestion from the comments :-)

**Comment by tiandongxv** [comment]
Hi,
   I want use the WebDAV to upload or download files on Kindle koreader, but I cannot find this function, I only can find ftp plugin (Sent2Ebook), so could you tell me how to use WebDAV?
    Sorry to bother you, thanks a lot!

**Comment by Frenzie** [comment]
It's called cloud storage and it's only in the file browser. :-)

**Comment by tiandongxv** [comment]
> It's called cloud storage and it's only in the file browser. :-)

Thanks for answering me, I can’t find file browser, I’m new to koreader, could you tell where it is? Or you can upload a photo to show me, thanks a lot!

**Comment by jp8** [comment]
I've made a pull request for the second issue (empty folder):
#5171

**Comment by jrnwndr** [comment]
I'm having issues accessing my transip stack webdav server, it keeps saying "Empty Folder" for me too. I've tried loads of different ways to connect to it, but it either tells me empty folder or to check my network configuration. Help with this would be greatly appreciated.

**Comment by Frenzie** [comment]
Pinging @jp8.

**Comment by jrnwndr** [comment]
I could set up a test account for you guys on there too, just let me know what I need to provide.

**Comment by Frenzie** [comment]
I've never really looked at this code much. :-) Also pinging @robert00s

**Comment by jp8** [comment]
Could you send me the ip address of the server, and a user and password to test with?

**Comment by jrnwndr** [comment]
How do I send it directly to you? I'm not sure if I should be posting credentials in this public discussion.

**Comment by Frenzie** [comment]
As an aside, besides the obvious path of email you can also send private messages through [the Gitter chat](https://gitter.im/koreader/koreader).

**Comment by jrnwndr** [comment]
@jp8 I've emailed you the credentials.

**Comment by clach04** [comment]
@Incog5 is this still an issue with current release? I've had success with (SabreDAV) WebDAV.

**Comment by johnbeard** [comment]
I'm seeing this with Apache + DAV. I can access it with other DAV clients, but Koreader always says "empty folder".

**Comment by hius07** [comment]
I believe this has been fixed in https://github.com/koreader/koreader/pull/9061 and https://github.com/koreader/koreader/pull/9128.
