### ISSUE TITLE
Swipe up on left side error

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4880]
* KOReader version: v2019.03.1-73-g22db71c_2019-04-05/
* Device: KA1

#### Issue
The left side swipe up to increase light is very unreliable for me.

Often my swipe is interpreted as either a short diagonal swipe, or as up+right (the multiswipe gesture).

Swipe down works fine.

**Comment by NiLuJe** [comment]
Might be KA1-specific, to some extent, as it is known to have generally very poor touch input precision.

**Comment by gerhaher** [comment]
This is much better now.
I close it.
