### ISSUE TITLE
http://koreader.ak-team.com Doesn't update builds

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#4882]
Latest build on http://koreader.ak-team.com/ is from 01.04.2019, http://ota.koreader.rocks is alright

**Comment by Frenzie** [comment]
@NiLuJe was that yours?

**Comment by NiLuJe** [comment]
Yep, that's me. Will look into it later tonight ;).

**Comment by NiLuJe** [comment]
Okay, there was a two-pronged issue with me having borked something on the master's end, and the crond getting crabby on my mirror ;).

Should be back to normal, give me a shout if this happens again, it's much appreciated :).
