### ISSUE TITLE
Feature request: scheduled wifi activation

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#4883]
It'd be nice if the wifi could be scheduled for activation at regular intervals, even with the device on standby.

Use cases would be downloading koreader updates and syncronizing books through the various plugins, but for starting, executing a simple script and shutting down the wifi on completion would be nice.

**Comment by NiLuJe** [comment]
Not that when the device is in suspend, it's effectively dead to the world.

Unless you start playing with rtc wakes, which is non-trivial, quirky, and device-specific to some extent.

**Comment by Frenzie** [comment]
Doesn't work on Kobo in any case.

**Comment by Frenzie** [comment]
@BrainDamage I'll close this because it's unfortunately impossible without running a custom hacked kernel (and possibly even then, if it's impossible for a hardware reason).
