### ISSUE TITLE
Download images in news (rss) feed articles

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#4894]
* KOReader version: v2019.04

#### Issue / Suggestion
When an article in an RSS feed contains images, it would be nice to download the images and embed them in the article. Particularly with scientific articles, it can be very frustrating when you can download the text, but you can't understand it because the accompanying diagrams are missing.

 I assume the thing to do is:
1. Download the html
2. Parse the html to find img tags and extract image urls
3. Download the image urls
4. Substitute image urls to be relative as required
5. Zip everything up into a suitable container, probably epub.

It look like most of the necessary functionality should already exist in the wikipedia article "Save as EPUB" code, so hopefully we can re-use/copy some of it. (When saving as epub with images, does it get the "normal" web html for the wikipedia page? or does it get it in an easier-to-parse form?)

Might be worth adding an optional parameter to the feed specification in feed_config.lua, as downloading images might not be desirable for every feed.

I'm planning to have a go at implementing this myself if no-one else does, but I'm not particularly familiar with lua or the koreader code, so any pointers or suggestions from those who know it better would be welcome.

There are a couple of open issues which are related: #3065, #3516.

**Comment by Thra11** [comment]
Looks like the wikipedia code is parsing html, but it does take advantage of some wikipedia-specific knowledge to select or reject certain elements based on class.

**Comment by poire-z** [comment]
> It look like most of the necessary functionality should already exist in the wikipedia article "Save as EPUB" code, so hopefully we can re-use/copy some of it. (When saving as epub with images, does it get the "normal" web html for the wikipedia page? or does it get it in an easier-to-parse form?)

We don't get the normal web page html, but some HTML from Wikipedia API (the same that, I think, is used to make the web pages, where navigation and other stuff is added to it).
So, it's indeed some quite clean and "normalized" HTML, and after looking at it, we could guess what we can remove or modify with some simple regexps.

Anyway, I think wikipedia.lua is a good starting point to get what you can do with Lua and the few things we already have to help building an EPUB:
https://github.com/koreader/koreader/blob/fd50dc34a6922eed97c69e3ec928694caebe6bd0/frontend/ui/wikipedia.lua#L648-L649
https://github.com/koreader/koreader/blob/fd50dc34a6922eed97c69e3ec928694caebe6bd0/frontend/ui/wikipedia.lua#L817-L818
https://github.com/koreader/koreader/blob/fd50dc34a6922eed97c69e3ec928694caebe6bd0/frontend/ui/wikipedia.lua#L830-L833

In RSS, I get the HTML shouldn't be too complex, so you may have some chances to get things done with some regexp too.

I don't use that newsdownloader plugin, so can't say much about it. It looked odd that it saves individual HTML files, but it may have some sense: one entry, one file: easier to track/delete what's new or read.
With EPUB, you will need to decide if you still want one EPUB for each entry, or a single EPUB with the many entries in the RSS, with TOC, etc... but then, it's harder to track what's read/new/need to be updated.
(Or have it accumulate new articles in a same EPUB ? So you get a growing archive of that RSS feed and you have a book that never ends :)

**Comment by Thra11** [comment]
I now have a working prototype, based on the wikipedia.lua code, with most of the wikipedia-specific tweaks removed: https://github.com/Thra11/koreader/tree/news-epub-with-images

It's a still little untidy in places, but it does seems to produce a working epub file, provided that the image links are http, not https. For https (or possibly only https with redirects), it fails with, "tlsv1 alert protocol version". A recommended solution to this problem seems to be [use lua-http](https://github.com/brunoos/luasec/issues/72#issuecomment-205548172) in place of luasec. Looks like @Frenzie also came to the same conclusion [here](https://github.com/koreader/koreader/issues/3516#issuecomment-346649788).

> It looked odd that it saves individual HTML files, but it may have some sense
I think it does make sense to stick with 1 file == 1 article, even if you could technically stuff multiple html files into an epub as chapters. Deleting old articles is nice and simple when they are just individual files.

**Comment by Frenzie** [comment]
@Thra11 No, that just means that for some reason you're using `request['protocol'] = "tlsv1"` (on line 111) instead of `"any"`.

**Comment by Thra11** [comment]
@Frenzie  I did try `"any"` (and also not setting `'protocol'`, which I believe means it defaults to `"any"`), but it just dies silently on the call to `https.request()`

**Comment by Frenzie** [comment]
That's what I said. ;-) A supported protocol will be automatically selected, such as `tlsv1_3`, `tlsv1_2` or `tlsv1`. Your unnamed server is failing because it wants TLS v1.2.

(Mind you, we would need OpenSSL 1.1.1 for 1.3, which btw @NiLuJe does seem to be supported by luasec these days since there are various TLS v1.3 commits. ;-) )

**Comment by Thra11** [comment]
> A supported protocol will be automatically selected

That's what I thought would happen, but instead it died silently. I had `logger.info("Whatever")` on the line immediately after `local code, headers, status = socket.skip(1, httpRequest(request))`, and it never output the "Whatever" when `'protocol'` was set to `"all"`.

Explicitly setting `'protocol'` to `"tlsv1_2"` didn't work either, though I can't remember whether it died silently or output and error.

In case you wanted to try to reproduce the issue, the feed which exhibited the failure was http://tetzoo.com/podcast?format=rss . I took one of the failing image urls and downloaded it with wget to confirm that it wasn't a server-side issue.

**Comment by Frenzie** [comment]
I get the expected error with line 111 and it works fine for me when commenting out the offending line.

**Comment by Thra11** [comment]
With line 111 removed, I get the following output:
```
...
04/15/19-22:23:37 INFO  Added OEBPS/stylesheet.css
04/15/19-22:23:37 INFO  Added OEBPS/toc.ncx
04/15/19-22:23:37 INFO  Added OEBPS/content.html
04/15/19-22:23:38 INFO  Getting img  https://static1.squarespace.com/static/510be2c1e4b0b9ef3923f158/t/5cb1b051e4966b391d890328/1555148888589/phyllostomids-intro-bat-books-1000px-tiny-April-2019-Darren-Naish-Tetrapod-Zoology.jpg
04/15/19-22:23:38 INFO  getUrlContent( https://static1.squarespace.com/static/510be2c1e4b0b9ef3923f158/t/5cb1b051e4966b391d890328/1555148888589/phyllostomids-intro-bat-books-1000px-tiny-April-2019-Darren-Naish-Tetrapod-Zoology.jpg ,
04/15/19-22:23:38 INFO  timeout: 10
04/15/19-22:23:38 INFO  request: {
    ["url"] = "https://static1.squarespace.com/static/510be2c1e4b0b9ef3923f158/t/5cb1b051e4966b391d890328/1555148888589/phyllostomids-intro-bat-books-1000px-tiny-April-2019-Darren-Naish-Tetrapod-Zoology.jpg",
    ["method"] = "GET",
    ["sink"] = function: 0x7f95e7ed70
}
04/15/19-22:23:38 WARN  EpubDownloadBackend.createEpub pcall: false common/socket/http.lua:40: LuaSocket: Function tcp() not available from LuaSec
04/15/19-22:23:38 INFO  createEpubWithUI failure
```
I wasn't getting the WARN line before: I can only assume it now appears because of some changes I made after I found that it worked for http, gave up on https, and tidied some of the code.

The only search result I get if I search for the error is the line of code in luasocket which produces it. Any ideas? I've double checked that I have all the dependencies in the ReadMe installed.

**Comment by Frenzie** [comment]
What conditions are required to reach this URL? What's your config set up like?

**Comment by Thra11** [comment]
I've been testing using the emulator on an aarch64 laptop running ubuntu 18.04.

**Comment by Frenzie** [comment]
What do you have in the feed config?

**Comment by Thra11** [comment]
`feed_config.lua` config has only one feed as follows, and is otherwise unmodified from the example one:
```
{ "http://tetzoo.com/podcast?format=rss", limit = 1 },
```
I can paste the whole thing when I get home if necessary.

**Comment by Frenzie** [comment]
No, I was using 10 for testing. I was just wondering if it could be an issue unique to, e.g., entry 50+.

**Comment by Frenzie** [comment]
Btw, I suppose this remark might be more for @poire-z, but naïvely speaking it seems that it might make more sense to have a generic EPUB download/creation module with Wikipedia-specific overrides than two more or less duplicate copies.

Or at the very least to have the EPUB creation fairly agnostic based on what it's fed.

**Comment by Thra11** [comment]
I think I have worked out why it complains that tcp is not available from luasec. It would appear that this luasec [commit](https://github.com/brunoos/luasec/commit/5e2b27fa711c648a15c534235e682f9480634205) exports the `tcp` function in `https`, but `kodev fetch-thirdparty` has checked out the `luasec-0.7` tag, which predates that commit.

So the question is… how can it work for you, @Frenzie? What luasec version do you have?

**Comment by Frenzie** [comment]
0.7, but note that your specific URL is a redirect. Anyway, looks like all that nonsense is resolved then. A bump to 0.8 and OpenSSL 1.1.1 (with TLS v1.3) is already incoming.

**Comment by Thra11** [comment]
I have now confirmed that if I change `luasec-0.7` → `master` in `base/thirdparty/luasec/CMakeLists.txt`, everything starts working: it now successfully downloads images for the tetzoo articles and produces a working epub.

**Comment by NiLuJe** [comment]
That should make it to tomorrow's nightly, if I manage to hammer the final failing TC into shape...

**Comment by Thra11** [comment]
Hmmm. By testing with a the article limit set to 1, I hadn't noticed that it's processing all the articles concurrently, which means they're
a) Fighting to display their progress on the UI
b) Possibly downloading a lot of images (1 per article) concurrently

Some work still to be done... :-)

**Comment by poire-z** [comment]
> Btw, I suppose this remark might be more for @poire-z, but naïvely speaking it seems that it might make more sense to have a generic EPUB download/creation module with Wikipedia-specific overrides than two more or less duplicate copies.
Or at the very least to have the EPUB creation fairly agnostic based on what it's fed.

Yeah, we could. Have a `EPubWriter` that would just extend/subclass `ZipWriter`.
It would need a bit of thinking (like the format of the TOC datastructure to pass to build the toc.ncx file if we want to go that deep), so it would take time and won't happen soon :) (unless someone else wants to have a go at it). Same for the downloading code.
So, I'd say it shouldn't block making a PR with this, now that the complex wikipedia leftovers are removed.

**Comment by Thra11** [comment]
I'm planning to submit a PR a soon as I've fixed the issue with multiple articles downloading concurrently while all trying to show their progress on the same UI dialog. Having said that, I'm not sure what the best solution is. I figure the simple options are:
* Remove the concurrency, only process one article at a time (Not sure exactly which bit of code to change to achieve this).
* Remove the progress updates, just show the "Processing feed \<url\>", not "Retrieving image 4 / 13 …" or "Packing EPUB…"

In the long term, it might be a good idea to have some sort of plugin-agnostic "download manager" to manage a download queue properly, downloading a few at a time and informing the requesters as each download completes. That way we could keep the advantages of concurrent downloads, without the potential problems that downloading 100 images simultaneously could cause.

**Comment by Thra11** [comment]
I guess this is done. Thanks for your help everyone!
