### ISSUE TITLE
Natural light: previous session's light for half a second when starting device

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4895]
* KOReader version: v2019.04-5-g69e3830_2019-04-09/  
* Device: KA1

#### Issue
It has been like this since some days (or maybe weeks).

I use the auto warmth feature. 

When I start the device nowadays, it seems like it has the previous session's level of natural light for maybe a half second before it finds the correct light.

So for example: if I put the device to sleep in the evening when I have a high level of warmth light, and then start the device in the morning (when the warmth should be 0), it has yesterdays light for like half a second before it jumps to the correct non-warmth light.

**Comment by NiLuJe** [comment]
Does it happen without the auto warmth plugin?

**Comment by NiLuJe** [comment]
I'd be happy if you could pinpoint since exactly when this happens, as I did touch the FL behavior very recently, and I can't test the legacy natural light behavior of the KA1 on my end ;) '

**Comment by gerhaher** [comment]
> Does it happen without the auto warmth plugin?

I don't realy understand this question. If you don't use this auto feature you always start with previous session's light, do you?

> Do you have a specific nickel warmth stored in nickel's settings? Does it happen to match the warmth level being used when this happens?

I never use nickel, so that's unlikely.

> I'd be happy if you could pinpoint since exactly when this is happening, as I did touch the FL behavior very recently (as in, three days ago), and I can't test the legacy natural light behavior of the KA1 on my end ;).

OK, when looking into my update history, and if my memory doesn't fail me, my best _guess_ would be
v2019.03.1-73-g22db71c_2019-04-05/ or v2019.04-1-g8466af2_2019-04-07/

**Comment by NiLuJe** [comment]
There's no way to query the system's actual frontlight state until Mk. 7 devices, so, yeah, all kinds of arcane assumptions are made on startup, which may lead to bogus values for a short while ;).

If it happened on a March nightly, that's definitely not related to my changes, but 04-2 might be it, I'll double-check.

**Comment by NiLuJe** [comment]
Oh, right, I killed the autowarmth calculation on resume like an idiot :D.
