### ISSUE TITLE
Book status crashes

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#4899]
* KOReader version: v2019.04-9-gfd50dc3_2019-04-10
* Device: Kobo Aura One

#### Issue

Trying to open Book status (through the hamburger menu or when reaching the end of a document) has KOReader exit irregularly (as reported by KSM).

#### Steps to reproduce

Open a document (in my case pdf); open the top menu; choose "Book status".
Or go to the end of the document and choose "Book status" at the pop-up.

##### `crash.log` (if applicable)

source page (0,0) - (595,841)
source page bgcolor 192
./luajit: frontend/ui/widget/virtualkeyboard.lua:459: attempt to concatenate local 'keyboard_layout' (a nil value)
stack traceback:
	frontend/ui/widget/virtualkeyboard.lua:459: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/ui/widget/inputtext.lua:380: in function 'initKeyboard'
	frontend/ui/widget/inputtext.lua:224: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/ui/widget/bookstatuswidget.lua:443: in function 'genSummaryGroup'
	frontend/ui/widget/bookstatuswidget.lua:164: in function 'getStatusContent'
	frontend/ui/widget/bookstatuswidget.lua:112: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/modules/readerstatus.lua:145: in function 'onShowBookStatus'
	frontend/apps/reader/modules/readerstatus.lua:64: in function 'callback'
	frontend/ui/widget/button.lua:218: in function 'action'
	frontend/ui/uimanager.lua:716: in function '_checkTasks'
	frontend/ui/uimanager.lua:993: in function 'handleInput'
	frontend/ui/uimanager.lua:1079: in function 'run'
	./reader.lua:234: in main chunk
	[C]: at 0x00013b61
Restoring original fb bitdepth @ 16bpp & rotation @ 0
[FBInk] Detected a Kobo Aura One (373)
Variable fb info: 1404x1872 (1408x3840), 8bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 1408 bytes

Switching fb to 16bpp @ rotation 0 . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Setting rotate to 0 (Upright, 0°)
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 0 (Upright, 0°)

Variable fb info: 1872x1404 (1888x2816), 16bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 3776 bytes
Original fb rotation is set @ 0
Original fb bitdepth is set @ 16bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Aura One (373)
Variable fb info: 1872x1404 (1888x2816), 16bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 3776 bytes
Device's expected Portrait orientation should be: 3 (Counter Clockwise, 270°)!

Switching fb to 8bpp @ rotation 3 . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Setting rotate to 3 (Counter Clockwise, 270°)
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 3 (Counter Clockwise, 270°)

Variable fb info: 1404x1872 (1408x3840), 8bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 1408 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/11/19-12:21:30
 [*] Version: v2019.04-9-gfd50dc3_2019-04-10

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
SDL not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: SDL
ffi.load: blitbuffer
ffi.load (warning): libblitbuffer.so: cannot open shared object file: No such file or directory
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
FB: computed size: 5406720
FB: id           : mxc_epdc_fb
FB: smem_len     : 10813440
FB: line_length  : 1408
FB: xres         : 1404
FB: xres_virtual : 1408
FB: yres         : 1872
FB: yres_virtual : 3840
FB: bpp          : 8
04/11/19-12:21:31 INFO  initializing for device Kobo_daylight
04/11/19-12:21:31 INFO  framebuffer resolution: {
    ["h"] = 1872,
    ["w"] = 1404
}
[ko-input] Forked off fake event generator(pid:4160).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
04/11/19-12:21:31 INFO  opening file /mnt/onboard/D/Corradini, Antonella/Essentialism and Forms of Necessity.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
04/11/19-12:21:31 INFO  Loading plugins from directory: plugins
04/11/19-12:21:31 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/11/19-12:21:31 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
04/11/19-12:21:31 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin kobolight at plugins/kobolight.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
04/11/19-12:21:31 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
04/11/19-12:21:31 INFO  setting zoom mode to contentwidth
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
04/11/19-12:34:18 INFO  no dialog left to show
04/11/19-12:34:18 INFO  quitting uimanager
Restoring original fb bitdepth @ 16bpp & rotation @ 0
[FBInk] Detected a Kobo Aura One (373)
Variable fb info: 1404x1872 (1408x3840), 8bpp @ rotation: 3 (Counter Clockwise, 270°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 1408 bytes

Switching fb to 16bpp @ rotation 0 . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Setting rotate to 0 (Upright, 0°)
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 0 (Upright, 0°)

Variable fb info: 1872x1404 (1888x2816), 16bpp @ rotation: 0 (Upright, 0°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 3776 bytes

**Comment by Frenzie** [comment]
Steps to reproduce: select a language without a keyboard (such as Dutch).
