### ISSUE TITLE
'Go to letter' not working when opening with long tap

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#4902]
* KOReader version: v2019.04-5-g69e3830_2019-04-09/
* Device: KA1

#### Issue
'Go to letter' doesn't work for me if I open it with a long tap. When I choose a letter and tap 'Go to letter' I'm left on same page.

If I open it with a multiswipe it works fine.

'Go to page' also works fine, irrespective of opening method.

**Comment by Frenzie** [comment]
It's probably working alright, but due to an unintended side effect of #4887 you'd be inserting a space first. (Although arguably whitespace should be stripped.)

**Comment by gerhaher** [comment]
> It's probably working alright, but due to an unintended side effect of #4887 you'd be inserting a space first. (Although arguably whitespace should be stripped.)

Yeah, I see.

**Comment by NiLuJe** [comment]
I've sometimes had it not actually moving pages at all despite a sane-looking output, and that for a good long while, so, there may be something slightly wonky somewhere nonetheless ;).

**Comment by Frenzie** [comment]
It seems to work by filename, while the cover browser displays metadata title or filename.

Potential workaround concept that isn't quite satisfactory:
```diff
diff --git a/frontend/ui/widget/virtualkeyboard.lua b/frontend/ui/widget/virtualkeyboard.lua
index d170027c..ccbe52cc 100644
--- a/frontend/ui/widget/virtualkeyboard.lua
+++ b/frontend/ui/widget/virtualkeyboard.lua
@@ -232,7 +232,13 @@ function VirtualKey:onSwipeKey(arg, ges)
     return true
 end
 
-VirtualKey.onHoldReleaseKey = VirtualKey.onTapSelect
+function VirtualKey:onHoldReleaseKey()
+    if self.keyboard.just_opened then
+        self.keyboard.just_opened = false
+        return true
+    end
+    self:onTapSelect()
+end
 VirtualKey.onPanReleaseKey = VirtualKey.onTapSelect
 
 function VirtualKey:invert(invert, hold)
@@ -551,6 +557,7 @@ function VirtualKeyboard:_refresh(want_flash)
 end
 
 function VirtualKeyboard:onShow()
+    self.just_opened = true
     self:_refresh(true)
     return true
 end
```

**Comment by gerhaher** [comment]
And since we are talking about 'Go to letter' in this thread: "Äéß-keyboard"´s letters are case sensitive for this plugin. 

Is there any possibility to make them insensitive?

**Comment by Frenzie** [comment]
It's listed as a todo:

https://github.com/koreader/koreader/blob/74e14a927cc706b9c040a704b1fb1206b11b349b/frontend/ui/widget/menu.lua#L656

**Comment by poire-z** [comment]
> Potential workaround concept that isn't quite satisfactory

Looks quite satisfactory to me (I used that kind of trick quite often, and you let them be merged :)

**Comment by Frenzie** [comment]
It's not so much the propriety of the code I'm concerned about as the behavior. It breaks the first hold release in all other scenarios, where the keyboard isn't activated through holding. To work properly it'd need to know if there was an active hold state onShow or something.

It would be very simple to only respond to hold release in the popup, but I rather like the hold release behavior.

**Comment by NiLuJe** [comment]
Is there actually a hold handler on the spacebar, though?

In fact, is there actually a hold handler anywhere excpet on del?

**Comment by Frenzie** [comment]
Not Hold, but HoldRelease.

**Comment by NiLuJe** [comment]
And what does it do?

**Comment by Frenzie** [comment]
The primary purpose is so you can hold on a key, wait for the popup, and move to the expanded key of your choice.

If I haven't thought of a better solution in a week I'll just restrict it to the popup.
