### ISSUE TITLE
Fdroid Screenshots

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [koreader/koreader#4904]
Please Add some screenshots to F-Droid and your github page.

**Comment by Frenzie** [comment]
@poire-z I think we could show off some footnotes. ;-)

**Comment by poire-z** [comment]
Yeah, we could, and many other things (after a quick tour in the menu: TOC, SkimTo, highlights and extending them, some nice HTML dict output, full text search, gestures, night mode, statistics, style tweaks, texteditor, Wikipedia lookup and epubs, zoom in pdf, zoom on EPUB images, cover views, book status, our new keyboard popups...).

We have various screenshots here and there (I mentionned some of them in https://github.com/koreader/koreader/issues/4102#issuecomment-407356062, and @AlanSP1 has put them on the Wiki).

I like the animated GIFs to really show how things work (ex in #3609). We could make a comprehensive and definitive one :)
I used [LiceCap](https://www.cockos.com/licecap/) (on Windows) to make the animated GIFs - but the result is quite big, there are probably stuff to do it and get a smaller size.

(I won't have time the coming week(s) to think about it, so feel free to have a go at it :)

**Comment by AlanSP1** [comment]
I'm not sure what should be in screenshots (except when some feature is shown)?

Usually we just see some ebook text, with very little something else (status bar is only what we see from koreader).

**Comment by poire-z** [comment]
Uh, we have a screenshots page ! https://github.com/koreader/koreader/wiki/KOReader-Screenshots
It's just that... it does not look like the KOReader I know :)

**Comment by NiLuJe** [comment]
Back To The Future! :D

(Incidentally, that's one issue with stuff like that, and once thing I was itching to point out ;)).

**Comment by houqp** [comment]
a gif to show off runtime reflow for scanned pdf/djvu would be cool :)

**Comment by Frenzie** [comment]
For myself or others: https://linoxide.com/tools/make-animated-gif-linux/

Peek sounds promising.

**Comment by Frenzie** [comment]
If you want the same content with a different aspect ratio, here's the exact Wikipedia article I used (remove .zip):

[E-reader.EN.epub.zip](https://github.com/koreader/koreader/files/3461652/E-reader.EN.epub.zip)

(Not really a fan of sticking screenshots in the main repo though. We could consider an Android metadata submodule?)

**Comment by pazos** [comment]
:+1: for an android/fdroid metadata submodule and using the second option that @Rudloff mentioned -> in the app’s build metadata in an fdroiddata collection.

fastlante seems really great for android-only apps (and the changelog thingy seems nice)

I will prepare the screenshots.

**Comment by Poussinou** [comment]
Here are three examples of apps using fastlane for F-Droid perfectly : [Newpipe](https://github.com/TeamNewPipe/NewPipe/tree/dev/fastlane/metadata/android), [A Photo Manager](https://github.com/k3b/APhotoManager/tree/FDroid/fastlane/metadata/android), [GadgetBridge](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android).

Regarding gifs, I'm almost sure it won't work with fastlane and F-Droid ;)

**Comment by pazos** [comment]
@Poussinou: thanks for the hints. We would like to have the fastlane dir in another repo because this is the main one used in all the supported platforms.

If this is not possible and you guys have another means to update these few screenshots outside our repo we're good too as long as we can PR new screenshots if current ones become obsolete.

**Comment by Rudloff** [comment]
I think you can use a Git submodule, since we fetch them before scanning the repository.
However, the metadata needs to be located in one of these paths: https://gitlab.com/fdroid/fdroidserver/blob/ebb8a6bf3083b15f09eaf0dcefe9e57328f90b00/fdroidserver/update.py#L901

> If this is not possible and you guys have another means to update these few screenshots outside our repo we're good too as long as we can PR new screenshots if current ones become obsolete.

It is also possible to add screenshots directly to [fdroiddata](https://gitlab.com/fdroid/fdroiddata/) but it is not the preferred method.

**Comment by Frenzie** [comment]
@Rudloff Sounds good! :+1:

**Comment by pazos** [comment]
That doesn't solve our problem, since we need to have the new submodule in one of these paths:

```
   metadata/<locale>/
   fastlane/metadata/android/<locale>/
   src/<buildFlavor>/fastlane/metadata/android/<locale>/
```

So still in our main repo.

> It is also possible to add screenshots directly to fdroiddata but it is not the preferred method.

That's probably the (not preferred) way to go.

**Comment by Frenzie** [comment]
@pazos It's certainly not preferred but if we stick to a thin submodule (like the fonts) it negates the biggest disadvantages.

**Comment by pazos** [comment]
@Frenzie: I created https://github.com/koreader/koreader-metadata, following [gadgetbrigde example](https://github.com/Freeyourgadget/Gadgetbridge/tree/master/fastlane/metadata/android/en-US)

Just copied descriptions from the readme (skipping some things that might not be relevant for fdroid, like portable) and screenshots from this ticket.

Please review. It can be included as a submodule in /koreader/koreader/metadata as both screenshots and description are generic enough and don't justify a path like /koreader/koreader/fastlane/metadata/android

**Comment by Frenzie** [comment]
calibre people always get upset if you capitalize it. But wouldn't it make more sense to just copy that list section directly from README?

Also, typo in "Document viewer primarly aimed at e-ink readers."

Maybe "Document viewer optimized for e-ink readers" or "Document viewer with e-ink optimizations"?

**Comment by pazos** [comment]
> calibre people always get upset if you capitalize it. But wouldn't it make more sense to just copy that list section directly from README?

sure.

> Also, typo in "Document viewer primarly aimed at e-ink readers."
Maybe "Document viewer optimized for e-ink readers" or "Document viewer with e-ink optimizations"?

That was the only string I copied from the README directly. Currently fdroid has the short description: `Ebook reader supporting multiple formats like PDF, DjVu, EPUB, FB2`. Maybe something like that is enough?

**Comment by Frenzie** [comment]
I'd write it more like this:

>Ebook reader with support for many formats like PDF, DjVu, EPUB, FB2, CBZ.

I wrote that other phrase years ago when Android support was worse. These days it's my preferred document viewer on Android.

**Comment by Frenzie** [comment]
I'll close this, a touch prematurely perhaps, but https://github.com/koreader/koreader-metadata/pull/1 is ready. See https://github.com/koreader/koreader/issues/2040#issuecomment-572182960 for further discussion.
