### ISSUE TITLE
FR: Support EPUB3 navigation document

### ISSUE THREAD

**Issue by cges30901** [koreader/koreader#4915]
* KOReader version: 2019.04
* Device: Linux

#### Issue
Because Sigil does not automatically update toc.ncx when editing a EPUB3 file, many files I download online does not contain an up-to-date toc.ncx. It will be convenient if KOReader can read TOC from [navigation document](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-nav).

Here is a sample file: [nav.zip](https://github.com/koreader/koreader/files/3076330/nav.zip)

**Comment by poire-z** [comment]
Indeed not currently supported. May be some day.
In the meantime, the "alternative TOC" feature may help, see #4011 and #4440 about how to tweak it.
