### ISSUE TITLE
Suggestion - Option Hide readed files

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#4917]
If option is enabled then readed files (100%) percentage will no show in file browser

**Comment by b1n4ryj4n** [comment]
bump

Is this feature already implemented yet? I wish it is because normally i delete my readed books but now on a tablet i can not delete them anymore because they are on a sdcard now and koreader wont delete them -.- so i need a way to hide my readed books.

**Comment by Frenzie** [comment]
It won't? But on a tablet couldn't you use a file manager?

**Comment by b1n4ryj4n** [comment]
I can use any filemanager to delete the book but not the in-build koreader filemanager and that sucks thats why i look for a solution to hide readed books. All i get is the message: 'An error occurred while trying to delete /storage/3637-6263/Android/data/com.github.catfriend1.syncthingandroid/files/Books/testbook.txt'

**Comment by pazos** [comment]
Duplicate of #7158
