### ISSUE TITLE
 Brightness in Settings close Koreader

### ISSUE THREAD

**Issue by tayabuz** [koreader/koreader#4919]
Device:Kindle PW1
Koreader version:v2019.04-25-g06a73ba_2019-04-13
I can change brightness by gentures. But Brightness in Settings close Koreader. Whis is a bug or feature?

**Comment by Frenzie** [comment]
Pinging @NiLuJe

**Comment by NiLuJe** [comment]
A crash.log would be helpful ;).

**Comment by NiLuJe** [comment]
Although I think I have an idea where it's going wrong, I killed a device check around a capa check, and those capa may not actually exist on all platforms, so, nil method, kablooey.
