### ISSUE TITLE
Bottom bar cutting off

### ISSUE THREAD

**Issue by ZachAttakk** [koreader/koreader#4926]
* KOReader version: Current nightly build (v2019.04-27-g7e06db9_2019-04-14)
* Device: Huawei P20 Pro, resolution 2240x1080 (18.7:9) running Android 9

#### Issue
I don't see the icons on the bottom of the screen, only the absolute top edge. I've tried every setting I can find. 

Found related bugs posts for Pixel 2 XL, but that appears to only allow aspect up to 18.5:9. Not sure if that's related or whether my device is reporting screen size incorrectly.

![Screenshot_20190416_001754_org koreader launcher](https://user-images.githubusercontent.com/44269032/56169417-541bd780-5fde-11e9-8d86-d9a723cea7ad.jpg)
![Screenshot_20190416_001746_org koreader launcher](https://user-images.githubusercontent.com/44269032/56169418-54b46e00-5fde-11e9-9303-0df5564600b4.jpg)

**Comment by NiLuJe** [comment]
Probably related to #4769 

Funnily enough, the cutoff looks similar-ish, so you may not even have to bother computiong the offset yourself ;).

**Comment by ZachAttakk** [comment]
Ah that worked for the time being! 
The patch descriptions, combined with the fact that Huawei Dev docs provide exact notch measurements, solved the problem.

I see there is an issue for reading notch height so hopefully that would be a device agnostic solution.

**Comment by NiLuJe** [comment]
Great! Closing this to keep things tidy then ;).
