### ISSUE TITLE
consistent crash on file load

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#4928]
* KOReader version: v2019.04-14-g58d88b1
* Device: Kobo Aura H2O2

#### Issue

consistent crash on file load ( the file is possibly corrupted )

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/3085321/crash.log)

**Comment by NiLuJe** [comment]
Yep, it is.

**Comment by Frenzie** [comment]
Ah, this is the background to #4929.

I'm surprised MuPDF takes down the whole program here.

**Comment by Frenzie** [comment]
How did you manage to save the last opened document if it crashed, btw?

**Comment by BrainDamage** [comment]
I simply pressed "open next file" from a previous file in the same folder, it launched the current one, saved settings ( I guess ) and then crashed

**Comment by Frenzie** [comment]
But that's not how it works. If I open a file and crash the program, the in memory settings crash with it. Something like the last opened document will be lost. Generally speaking I consider this a bug, not a feature, but those settings will only be saved in case of a clean exit. Never in between. Settings pertaining to a specific document will be saved when exiting the document. This too is a bug, for which I've prepared a solution but I haven't wanted to tackle migration.

If you purposefully edit the last file pointer to a broken file or break the file afterward, you'll see this on startup:

![Screenshot_2019-04-16_17-27-55](https://user-images.githubusercontent.com/202757/56222883-0e5a2000-606d-11e9-9670-e5b243b1e6b2.png)

On closer inspection of your log, the program does not actually crash. It seems to quit when it should be showing you the file browser. Do you have any special settings?

```
INFO  quitting uimanager
04/16/19-16:18:44 INFO  no dialog left to show
```

**Comment by Frenzie** [comment]
Oh, never mind. There's a code path that leads to a proper exit, possibly to prevent memory corruption? That's what'll cause it to save the last opened file.

https://github.com/koreader/koreader/blob/717db55566cc1359f05c5defbdbf2b1ded1451ef/frontend/apps/reader/readerui.lua#L465-L484

It can be easily triggered by this CBZ test file. It's a random source code file renamed `.png`.

[not-a-png.cbz.zip](https://github.com/koreader/koreader/files/3085745/not-a-png.cbz.zip)

I've never encountered this code path before, in the past five years. ;-)
