### ISSUE TITLE
question : KOReader and Kobo Forma

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#4939]
Hi there,

A friend of mine is in japan for the moment and I'm quite teasing myself with the kobo forma 32go...

But : I can't live without KOReader (launch by KFMon if possible). So how are they working together on this device ?

**Comment by Frenzie** [comment]
Afaik it's fine, including auto-rotation. See #4414.

**Comment by NiLuJe** [comment]
Yep, I've got one, so it's shipshape ;).

**Comment by cramoisi** [comment]
@NiLuJe : do you like it (as a reader, with koreader) ?

**Comment by NiLuJe** [comment]
Yep, my only complaint is the decidedly less than perfect frontlight, with its strip of brightness on the button's side.

**Comment by hiworld3** [comment]
> 
> 
> Yep, my only complaint is the decidedly less than perfect frontlight, with its strip of brightness on the button's side.
> 
> That said, it's hands down the best Kobo has to offer. I've grown used to the slightly larger screens, and I love flush bezels, so, really, the only sensible choices are a Forma, or a PW4 on Amazon's 6" side of the fence ;) (The Oasis 2 is a tad too expensive to have to deal with Amazon's crap, but it is also a fantastic device).

forma is perfecter if using imx7 dual core like oasis2
