### ISSUE TITLE
semi-auto crop & reflow temporarily removes page content

### ISSUE THREAD

**Issue by silberzwiebel** [koreader/koreader#4942]
* KOReader version: v2019.04 (installed from F-Droid, issue existed for many earlier versions, too)
* Device: inkbook prime

#### Issue
The first page is not rendered correctly if one uses the semi-auto crop feature.

#### Steps to reproduce
1. Have automatic reflow as default (not sure if neccesary).
2. Download and open PDF from https://www.pnas.org/content/104/4/1436 (or similar PDFs)
3. use semi-auto crop to exclude the blue left PNAS bar from the reflow content
4. realize that although reflow works nicely now, not all content from the first page is printed

Workaround:
Scroll down to page 2 (none of page 1 should be visible anymore), then scroll back to page 1: all content is back again

**Comment by Frenzie** [comment]
This doesn't seem to be an issue anymore. Please verify on the Inkbook Prime as well.
