### ISSUE TITLE
[Help] I forgot my password for Progress Sync.

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#4952]
A few updates prior my koreader crashed and after I did a hard reset, all my settings were gone.

I know the username is the same as this one since it tells me when I try to make a new one, but is there a way to recover old passwords?

**Comment by houqp** [comment]
Sorry to hear that. As far as I can tell, the sync server doesn't have access to your password in plaintext, so there is no way to recover the old password :(

Did you have to do the hard reset due to issues with koreader upgrade?

**Comment by CalbertAmu** [comment]
It didn't crash during the upgrade, but I figured something was buggy in that version because it happened some about 3 times before I updated. It's ok now, and nothing important was lost.

I'll just register with a new username then. Thanks!

**Comment by houqp** [comment]
I see, it would be helpful if you can report the bug you saw next time so we can dig into the root cause :)
