### ISSUE TITLE
Synchronize Library

### ISSUE THREAD

**Issue by rjbergerud** [koreader/koreader#4971]
#### Issue
Feature request: would it be possible to synchronize the books on koreader with a folder in dropbox or on a ftp server?  Does this feature already exist and I just haven't found it?

Would be interested in helping with this if someone wanted to give me a few pointers.

**Comment by Frenzie** [comment]
I wrote down a Syncthing brainstorm here:

https://github.com/koreader/koreader/issues/3630#issuecomment-360988434
