### ISSUE TITLE
Feature request: per-folder settings

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#4975]
I would like to have per-folder settings; in particular there should be a .settings file that's read if present in the current directory, and overrides global defaults 
Use case:
Some comic books are written on a normal page-layout setting, while others are a long vertical strip ( especially korean ones ), and one needs to toggle between defaults when opening a lot at once.
Or a folder containing a lot of scanned documents could have forced ocr enabled.

**Comment by Frenzie** [comment]
As a funny coincidence, I just referred to something of the sort in https://github.com/koreader/koreader/issues/4951#issuecomment-486991232, albeit not as an FR. ;-)

**Comment by KenMaltby** [comment]
Hmm... sort of an SDR for folders?  Could be handy for those keeping reading material in different languages and/or other situations where some setup/defaults changes are needed for reading the particular material in a category.

**Comment by Frenzie** [comment]
Implemented in <https://github.com/koreader/koreader/pull/5428>.
