### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [koreader/koreader#4979]
* KOReader version:2019.4
* Device:samsung J2

I really like the app ,it's feature rich but the UI takes some time to learn,
Is it possible to add sepia theme or create custom theme in koreader?

**Comment by Frenzie** [comment]
Duplicate of #3871. Not exactly because the program started on ereaders, but if you redefine white as some sepia-type color  it's not completely horrible. See https://github.com/koreader/koreader/issues/3871#issuecomment-381210519.
