### ISSUE TITLE
Feature request: Auto Next Page

### ISSUE THREAD

**Issue by kobomobo** [koreader/koreader#4984]
* KOReader version: 2019.04
* Device: Kobo Clara HD

Believe or not, sometimes touch/click/swipe could be very annoying while reading non-stop. Automatically turn next page would be great. 

The interval time can be defined by typing/selecting seconds (or advanced idea : can be calculated according your mean time statistics per 1 page)

**Comment by Frenzie** [comment]
Duplicate of #3019. But I'll tag that one help-wanted to indicate that it's a good place for someone to write a first plugin.

**Comment by kobom** [comment]
I think it's not duplicate of #3019.

I have serious accessibility problems with turning pages. Is it too hard to develop a next page command that runs at certain times? I don't understand software development. Please help us with accessibility.
