### ISSUE TITLE
Feature Request: Touchscreen Zones: More touch option for next/previous page

### ISSUE THREAD

**Issue by kobomobo** [koreader/koreader#4985]
* KOReader version: 2019.04
* Device: Kobo Clara HD

It's a feature mimic Kobo

Kobo has great touchsreen controls, as The Digital Reader say:

> There's a 4th option for setting the page turn zones. Readers can now set their Kobo to advance a page when they touch the bottom half of the screen 

![image](https://user-images.githubusercontent.com/50151056/56983673-e5697d00-6b8c-11e9-92d3-07b9dd37281c.png)

**Comment by Frenzie** [comment]
This is technically already possible with a persistent.defaults.lua.

https://github.com/koreader/koreader/blob/96179670f8d1d29f343db1ab0ce20ef6bd45acb2/defaults.lua#L74-L75

There are some examples on the forum: https://www.mobileread.com/forums/showthread.php?t=316179

**Comment by AlanSP1** [comment]
For myself, I like how I set it up: Almost everything is page forward, except relatively small zone at the left side, which is page back. It allows me easy control with both hands.

**Comment by gerhaher** [comment]
Is it possible to have more than one zone for either forward or backward?

For example if you want to have one backward zone on the left side and one on the right (and the forward zone in the middle).

**Comment by AlanSP1** [comment]
At the moment no.

**Comment by Frenzie** [comment]
You can if you're willing to give up on one or more of the corners.

You can also achieve the effect with an overlap. Make one cover the whole screen, the other only the middle, and use RTL if the result is opposite from what you want.

**Comment by gerhaher** [comment]
Thanks @Frenzie!

I've tried them both now, and yes they are acceptable workaround solutions. 

But can you explain the RTL thing? 
When using the overlap method I inverted the function for the zones with this method: https://github.com/koreader/koreader/wiki/Keymapping
It seems to work. 
But I guess you were refering to something else.

**Comment by Frenzie** [comment]
See #4983. Settings → Read from right to left.

I assume one touch zone, whether left or right, is technically on top of the other.

**Comment by gerhaher** [comment]
> I assume one touch zone, whether left or right, is technically on top of the other.

Unfortunately I've found that it shifts which is at the top. It shifts seemingly randomly after exiting KOReader.

So it seems that the overlap method doesn´t work.

**Comment by Frenzie** [comment]
Not really a problem if you add a third touchzone from whichever corner you don't use though. :-)

**Comment by poire-z** [comment]
Implemented by #8475.
