### ISSUE TITLE
Add option to disable non-inverted images in night mode

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#4986]
* KOReader version: v2019.04
* Device: Kobo Aura One

#### Issue
The recent work to keep most images non-inverted in night mode (see #2571) is a massive improvement for most documents. However, some books don't have _pictures_  as such, but have lots of line-art _decorations_: Illustrated chapter numbers, squiggly symbols to separate sections and so on. These now look a bit odd in night mode, as they are rendered as black symbols on a white rectangular background (not sure if the original images have white or transparent backgrounds), whereas if inverted, they render as white symbols and the background rectangle is indistinguishable from the page background (as it is without night mode). Could we maybe have style setting (per document, but with configurable default) which disables the non-inverting?

**Comment by NiLuJe** [comment]
A sample would be nice, because the alpha or not question might be the crux of the issue.

**Comment by Thra11** [comment]
I'll sort out a minimal example this evening and experiment with white vs transparent backgrounds as well

**Comment by Thra11** [comment]
Haven't had time to create a minimal example, but I have found that the images in question have opaque white backgrounds.

**Comment by NiLuJe** [comment]
That definitely makes sense for opaque background, and I did randomly get
to see that in effect on Android, the only platform where I actually have a
vague chance of using night mode for real ;).

Still curious whether this would happen with transparent background, though
;).

**Comment by Thra11** [comment]
Right. Here we are:
Test epub containing images with both opaque and transparent backgrounds:
[InversionTest.zip](https://github.com/koreader/koreader/files/3170447/InversionTest.zip)
Result in Normal/Day mode:
![Reader_2019-May-12_195808](https://user-images.githubusercontent.com/1391883/57586682-60b62180-74f1-11e9-8ee9-cf8ad5f3fca2.png)
Result in Night mode (screenshots don't take night mode into account, but I've manually inverted it so that it looks the same as on screen)
![Reader_2019-May-12_195820](https://user-images.githubusercontent.com/1391883/57586686-657ad580-74f1-11e9-9610-bc4709d05dda.png)

**Comment by Thra11** [comment]
As you can see, neither image produces an ideal result in night mode. (Before the recent changes, I believe either of the images would result in white lineart on a black background when in night mode, which looked much nicer for this sort of decoration.)

**Comment by NiLuJe** [comment]
Huh. The alpha handling is arguably a bug, because it definitely should render as white on a transparent background (i.e., black).


Can you check with 2019.05? I don't *think* .04 had the latest nightmode tweaks in...

**Comment by NiLuJe** [comment]
Actually, no, it makes perfect sense :D. Black gets inverted to white by CRe, whichds end up drawing white on white, and then all that gets inverted by the eInk controller, but since we essentially lost the contrast because what's behind the transparency (white), now matches the inverted fg color (white), the image is essentially lost, and when the eInk controller (or us) invert that, this doesn't change that fact :).

Do check with the latest release for my peace of mind, but, nyeeah, it does make sense.

**Comment by NiLuJe** [comment]
Unless we just draw a black pixel instead of skipping that pixel when encountering a fullty transparent image pixel.

**Comment by Thra11** [comment]
FYI, the tests and screenshots were done using v2019.05

I think we have two slightly different issues here:
1. 'Decorations' look best when inverted along with the text (as they used to be before #2571 )
2. An image which is black on transparent background becomes black on a black background (invertRect inverts it to be white on transparent, it gets overlaid on a white background, then night mode makes it black on black).

Dealing with 1., I don't think we can really expect koreader to be able to distinguish between a decoration and a photograph, so the best we can do is probably to allow the user to decide whether images get inverted or not on a per-document basis.

As far as 2. is concerned, I assume the thing to do would be to do the alpha blending first (effectively converting the transparent background to a an opaque white background), then proceed as normal with the inversion. Assuming the pixel is AARRGGBB, each component one byte, I think the alpha blending will be something like:
```
// extract alpha value
const int alpha = 0xFF000000 & pixel;
const int background = 0xFF; // max for all components == white
const int result_pixel = 0;
// For each component, R, G, and B
for (auto component : { 0, 1, 2 }) {
    // Extract the component
    const int component_mask = 0xFF << component;
    const int source = component_mask & pixel;
    // multiply and add source and background, normalise, mask (possibly unnecessary), shift and put into result
    result_pixel |= (component_mask & ((source * alpha + background * (0xFF - alpha)) / 0xFF)) << component;
}
```
This is doodled from memory, so obviously it's not perfect, but I think that's the gist of what needs to be done.

**Comment by NiLuJe** [comment]
CRe only does alpha-blending as a last resort (as it should): if the pixel is fully transparent, it's skipped, and if it's fully opaque, it's plotted as-is from the image pixel.

This makes sense because, in practice, very, very, very few pixels will actually need alpha-blending. You generally have that kind of stuff, where basically only the AA on the contours will possibly need it, or, much more commonly, a PNG that happens to have an alpha channel for no good reason, because it's just always opaque.
Given this, going through alpha-blending unconditionally turns out to be much more expensive in practice, hence the shortcuts ;).

Hence the crappy "plot a white pixel instead of skipping it if alpha is 0" idea ;).

c.f., https://github.com/koreader/crengine/blob/cdd4634e9c5dac438076f7bd0eb97a234c3a5efd/crengine/src/lvdrawbuf.cpp#L545

A quick glance at that makes me think those alpha shortcuts are all kinds of broke currently...

**Comment by Thra11** [comment]
I may be misunderstanding, but wouldn't replacing fully-transparent pixels with opaque white ones give an end result something like this?
![alpha-shortcut](https://user-images.githubusercontent.com/1391883/57644440-016d1580-75b4-11e9-9fc1-87bff38115ae.png)

**Comment by Thra11** [comment]
We are getting slightly off-topic for this issue, which is about allowing the user to choose to invert images in night mode (once, not twice). Do you think such an option would be reasonable? With respect to the image with the transparent background, it is worth noting that:
a) It renders fine in day mode and old (everything inverted including images) night mode.
b) It wasn't discovered 'in the wild': it's just a test image I created.

If images like this did start showing up in actual ebooks, it's probably not the end of the world, as a long press on the image currently shows it rendered correctly, regardless of whether night mode is enabled or not.

**Comment by NiLuJe** [comment]
That's because the alpha issue is far more interesting than a boring new setting ;o).

Turns out CRe expects inverted alpha, which is why none of those alpha checks made sense to me.

Delaying inversion post blending, and faking a background when inverting transparent pixels makes it behave.

**Comment by NiLuJe** [comment]
As for the new setting, my main concern is *where* to put it, and whether it should be settable as a global default or not... @poire-z?

**Comment by poire-z** [comment]
> As for the new setting, my main concern is where to put it, and whether it should be settable as a global default or not.

Dunno if you're still thinking about that setting after this PR that may kill the need for it?
But if needed, I guess we could show it in the bottom menu (around your Image scaling one) only when night mode is enabled. Would need some small tweak to ConfigDialog to support a `show_func = function() return Device.screen.night_mode end,` parameter, where it already supports a `show = false/true`. Then, you get all the global/local benefit of the copt_ stuff.

**Comment by NiLuJe** [comment]
Oh, the PR doesn't fix it, it just ensures a transparent images gets rendered the same as one with a white background ;).

**Comment by Thra11** [comment]
I came across another type of graphic which would benefit from this: mathematical formulae are often rendered as images, and if they use particularly obscure symbols, the individual symbols are also rendered as small images when referred to in the accompanying text.
