### ISSUE TITLE
"margin size" bottom title label: disappeared for PDFs

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#4992]
* KOReader version: current nightly v2019.04-76-gaec7594_2019_05_02
and prev nightly, too: (201904000073) v2019.04-73-g4c14ef7_2019-05-01
* Device: kobo glo hd

#### Issue
THANK YOU for the pixel-precision tuning of the margins, line spacing and word spacing! the same functionality seems not applicable for PDFs, but the bottom menu stays the same (non-pixel precision, but with toggles "large" "medium" "small"). The issue is that the interface for PDFs got slightly confusing because the label for margin size disappeared, while reading a PDF.

#### Steps to reproduce
1) open a PDF
2) I applied crop = semi-automatic, with reflow = off - but this doesn't matter;
3) in the bottom menu, "margin size" label disappeared and user selection buttons took all the width

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

![Reader_2019-May-02_101303](https://user-images.githubusercontent.com/4983083/57060969-f49f1680-6cc3-11e9-8f0d-988ae5663db9.png)

**Comment by worldexplorer** [comment]
![Reader_2019-May-02_101303](https://user-images.githubusercontent.com/4983083/57061294-f4ebe180-6cc4-11e9-97ea-849a556f1e1e.png)

**Comment by Frenzie** [comment]
Pinging @NiLuJe

**Comment by NiLuJe** [comment]
Oh, right I zapped the old string like an idiot.
