### ISSUE TITLE
Android 5.x Bottom of screen cut off by navigation bar when switching away from koreader then back

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4996]
* KOReader version: 2019.04.01
* Device: kindle fire 10 tablet (android 5.6.x)

#### Issue
Note: may be considered a duplicate of #4794.  feel free to close if deemed as such.

#### Steps to reproduce
Open koreader.
Use the square button to switch to a different app.
The navigational buttons are now persistent and can't be made to go away.  Only relief is to quit the koreader app and reload it.  

See image.

![IMG_20190503_185107](https://user-images.githubusercontent.com/556667/57170902-9c583980-6dd5-11e9-98a0-f024e348a148.jpg)

**Comment by pazos** [comment]
Can confirm on the emulator w api23.It is weird because it does not affect recent android versions(api26+)

**Comment by pazos** [comment]
@arooni: if this is still an issue on latest 2019-07 release I will give it a try tomorrow.

**Comment by pazos** [comment]
@arooni: feel free to open it agin  if you can still repro on latest stable.I cannot on emulator.

**Comment by pazos** [comment]
Still an issue and @arooni interested in beta-testing.

**Comment by pazos** [comment]
Fixed in https://github.com/koreader/android-luajit-launcher/commit/7edd7d1b1bc42d4b025c61f6bcbbd61d8445064e

@arooni: feel free to test and report back! (Use 2020.07 when available)
