### ISSUE TITLE
FR: Support arrow keys for next previous/page.  And mouse wheel.

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#4997]
* KOReader version: 2019.04.01 
* Device: ubuntu laptop

#### Issue
So I have started using KOreader on ubuntu.

I am working through a guitar theory book in epub format.  As I advance pages it would be really handy to have left/right and up/down arrow all be mapped to previous/next page respectively.

Also would be handy to support a mouse scroll wheel to advance/previous page.  

This is especially true when I'm trying to advance the page one handed with a guitar in my lap and finding the page up/down button is a bit tricky.

As an aside, how am I supposed to upgrade the koreader version?  I tried update from within the app without positive results.  So I have to download the deb and install it that way?

**Comment by Frenzie** [comment]
In scroll mode you can scroll through. Perhaps it'd make more sense to map scroll to page up/down though.

**Comment by arooni** [comment]
wowowowowowwo!

amazing!  koreader keeps getting better and better!

**Comment by pazos** [comment]
> hoping the mouse wheel support will apply to android devices too :)

Using the mouse wheel as page fwd/back seems doable. [The mouse wheel event action is considered a scroll event](https://stackoverflow.com/a/28807680) and, in fact, is [available via native api -> AMOTION_EVENT_AXIS_VSCROLL](https://developer.android.com/ndk/reference/group/input#group___input_1gga4790f45dcc812c1b00184a2edccdddf5ad11be04b4b81715cad905ee9fa348e99)

That specific setup is covered in https://stackoverflow.com/a/33086042. We need to port it to the [motion event handler](https://github.com/koreader/koreader-base/blob/master/ffi/input_android.lua#L60) and emit a fake event or some unused key event.
