### ISSUE TITLE
Feature request: better system for highlighting long text fragments

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#5004]
* KOReader version: 2019.4
* Device: Kobo Forma

#### Issue

Highlights spanning more than 2 pages are impossible and very frustrating. People have reported this in other (closed) issues. I would like to suggest an alternative way to solve this:

1) when selecting more than one word, the context menu for highlights could have an item "start highlight".
2) when after this action the user selects more than one word at the end of the intended highlight, the context menu could have an item "end/finish highlight".
3) upon choosing this action, the highlight is inserted
4) the default highlight action "highlight" which KoReader has at the current moment could also be maintained, for shorter text selections, when the user wants to immediately insert a highlight which does not span multiple pages.

The page flips after selecting the lower right end of a page are very jumpy, the user has to re-orient himself where in the page he is. A system with "start highlight" and "end highlight" as proposed, would prevent this problem. It would give the user much more control over the highlighting process.

#### Steps to reproduce

I read in horizontal mode with 2 columns.
When selecting a page spanning text fragment the first flip to the next page is done correctly.
But after that KoReader refuses to flip to yet another page, making it impossible to select longer text fragments.

**Comment by hius07** [comment]
Closed in https://github.com/koreader/koreader/pull/8432.
