### ISSUE TITLE
NewsDownloader re-downloads articles

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#5005]
* KOReader version: v2019.04-73-g4c14ef7_2019-05-01
* Device: Kobo Aura One

#### Issue
The newsdownloader plugin doesn't check whether an article in a feed has already been downloaded, it just downloads it and overwrites the existing article if it exists. This is a) nice and simple and b) ensures that the most recent version of an article is downloaded if the content of a url changes. However, for feeds with many items, this can take a long time, especially if including images.

#### Steps to reproduce
Add at least one feed to feed_config.lua. Run "Download news". Run "Download news" a second time: it  re-downloads all the articles despite the fact they've already been downloaded by the first run.

I'll have a go at this if noone else does. I Think simply checking whether the target filename exists and skipping the article if it does should be OK in most cases.

**Comment by Frenzie** [comment]
Go ahead. ;-)
