### ISSUE TITLE
Feature request: cloudstorage - support view others file type

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#5006]
* KOReader version:all
* Device: kindle
Koreader is the best with 'cloud storage' function. I can upload all my documents to dropbox and get them whenever I want.
However, It's better if 'cloud storage' support viewing other file types like azw,azw3...
As sometimes we need to transfer azw3 file to kindle for reading with word wise.
Please consider to add other file type support

**Comment by robert00s** [comment]
This should be quite easy to do but I don't really have idea where to put settings (show all files / show only supported files) in cloud storage. Any ideas? @poire-z @Frenzie @NiLuJe

**Comment by Frenzie** [comment]
Also see #3578. You could start with something like "Show unsupported files" under "Show hidden files." Perhaps it's not necessary to do it separately.

![Screenshot_20190704_202831](https://user-images.githubusercontent.com/202757/60683828-4e75b580-9e9a-11e9-8df1-6cba844d22dc.png)

**Comment by poire-z** [comment]
No real idea... I don't even have any account to check how that works.
Looking at the code, may be an additional (long) button among these ones (Info|Edit|Delete):
https://github.com/koreader/koreader/blob/a3356483bac01d8e7becd8ca37d83a8df6b14603/frontend/apps/cloudstorage/cloudstorage.lua#L258-L262
Hitting would toggle the button from something like `Showing only supported files` <> `Showing all files`.

Or a top right  `+` menu :)

**Comment by uphantom89** [comment]
To make it simple, I would suggest that "Show hidden files" tick box also trigger showing all file types both in file manager and cloud storage

**Comment by Frenzie** [comment]
"Show hidden files" is fairly standard operating procedure on Kobo because we use a directory like `.books` so that it's not indexed by Nickel. There's a definite use case for it that doesn't necessarily include showing all files.

On the flip side… I image people don't tend to put in files that can't be opened, perhaps making it a moot point.

**Comment by uphantom89** [comment]
As I mentioned above "As sometimes we need to transfer azw3 file to kindle for reading with word wise"

**Comment by Frenzie** [comment]
That we want to show unsupported files in various situations is a given. The discussion is about:

1. Is it necessary to have separate settings for different contexts. I would argue that for starters it isn't. It can always be added later if desired.
2. Is it necessary to have separate settings for hidden files and unsupported files or should it just be a "show all files" toggle. I find it unintuitive to put it all in one setting, but like I said it may be a moot point.

**Comment by KenMaltby** [comment]
Perhaps expecting KOReader to list files that are to be used outside of KOReader, would be more likely to add unnecessary complexity to the file browser.  Wouldn't the other program that can use the file be the place to have the means to acquire the file to be opened?
