### ISSUE TITLE
Feature Request: gestures for navigating to the first highlight to the left or right of the current page

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#5009]
* KOReader version: 2019.4
* Device: Kobo Forma

#### Issue

It would be very nice if KoReader had the option to let a reader navigate to the first highlight to the left or right of the current page.

If it would also be possible to assign a multi swipe to these actions, the reader could navigate through the highlights in an ebook by using gestures.

This would be much more conveniant then using the skimming dialog, because this dialog covers a large part of the page, so the highlighted text may sometimes only become entirely visible after quitting this dialog.

**Comment by robert00s** [comment]
@smartscripts-nl 
I think it has been already implemented. Go to gesture manager and try:
- Next bookmark
- Previous bookmark
