### ISSUE TITLE
FR: Allow more font choices (perhaps access to locally installed fonts) on Android

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5013]
* KOReader version: 2019-04 monthly
* Device: pixel xl

#### Issue

So when I pick up my phone because I'm bored I'm trying to get in the habit of opening koreader and not twitter/hacker news/etc.  

To whit, I find that the two pages of font choices insufficient.  I particularly enjoy reading with Google's Literata and Amazon's Bookerly is also decent.  But none of those are available with koreader.  Request would be adding some additional 'baked in' fonts to the android/koreader in general.  

Not sure how licensing issues may restrict you from doing this though.

**Comment by Frenzie** [comment]
There's a related discussion on the forum: https://www.mobileread.com/forums/showthread.php?t=316565

I wouldn't mind adding Libertine and/or Tex Gyre Pagella to the shipped fonts. An extra font does add quite a bit of weight though.

For Android specifically we already utilize `/system/fonts`. On my devices that's definitely functional. Like this "Coming Soon" font.

![Screenshot_20190508-203149](https://user-images.githubusercontent.com/202757/57398918-74e7df00-71d0-11e9-93d8-0b410adfbd1c.png)

https://github.com/koreader/koreader/blob/888d3591b29259884a4d87f0386e0e31154967d3/defaults.lua#L237

https://github.com/koreader/koreader/blob/f6e561923cddcd7133ad0103e9f06c7240f254b4/frontend/fontlist.lua#L65-L71

**Comment by Frenzie** [comment]
PS

> To whit, I find that the two pages of font choices insufficient.

I glossed over this, but this is proof that your Android system fonts are being picked up. All fonts shipped with KOReader by default can be found [here](https://github.com/koreader/koreader-fonts).

![Screenshot_2019-05-08_20-41-31](https://user-images.githubusercontent.com/202757/57399534-bb8a0900-71d1-11e9-9339-c8da32cc4c24.png)

**Comment by arooni** [comment]
I looked briefly into how to install a font on Android and it seems if my device is not rooted (its not) it's not advisable to try to use third party apps which might brick the device.  

If I'm wrong, please do correct me.

**Comment by Frenzie** [comment]
You can put fonts for KOReader in `/sdcard/koreader/fonts`.

**Comment by pazos** [comment]
@arooni you can place fonts in `/sdcard/koreader/fonts`.

**Comment by arooni** [comment]
Ooof!  Much easier than trying to get them to /system/fonts !  Thanks team!

**Comment by ChenguangZhang** [comment]
Is it possible to do the same for koreader.AppImage? 
I created a fonts folder under ~/.config/koreader and put some fonts inside, the AppImage does not detect them.
