### ISSUE TITLE
Feature request: screen rotation, 4 directions

### ISSUE THREAD

**Issue by hiworld3** [koreader/koreader#5016]
* KOReader version: 2019.04
* Device: Android

Hi, it would be really convenient if we could add screen rotations in 4 directions, some devices need to ratate into landscape, but we only have one landscape, no 180 landscape and no 180 portrait, thanks.

**Comment by Frenzie** [comment]
It's currently somewhat hidden, but try tapping on the rotation again. ;-)

**Comment by hiworld3** [comment]
lol, amazing!!!!
