### ISSUE TITLE
Feature request: Option for shutdown in the Gesture Manager

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#5021]
Just a way to avoid a click or two by long pressing a corner :-p

I never put my Glo to sleep, because if I do, it spends more battery than when is open.
So I have to shutdown every time I leave my book.
And I'm lazy...

On a side-note, would it not be cleaner if there was a menu arrangement like this?
```
Gesture Manager
    Top left corner
        Tap
            menu
        Hold
            menu
    Top right corner
        Tap
            menu
        Hold
            menu
    Bottom left corner
        Tap
            menu
        Hold
            menu
    Bottom right corner
        Tap
            menu
        Hold
            menu
```
Anyway, all these are minor nitpicks.
You guys have made KOReader a super reader!

Too bad there is no windows version ;o)

**Comment by noembryo** [comment]
I meant "Hold" not "Right top" ..

**Comment by Frenzie** [comment]
> Too bad there is no windows version ;o)

I'm told the program runs fine in WSL.

**Comment by noembryo** [comment]
What is WSL (apart from that [WSL](https://www.worldsurfleague.com/))

**Comment by Frenzie** [comment]
https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/

More is on the way: https://venturebeat.com/2019/05/06/microsoft-windows-terminal-wsl-2-coming-june/

**Comment by robert00s** [comment]
Should we reorganize Gesture manager menu or leave as it is? I like arrangement as is now.

**Comment by Frenzie** [comment]
I think it's clearer to have the tap menu with locations, the hold menu, etc. (like we do). To focus on the location first rather than the action strikes me as backwards, but I'm having trouble articulating why.

**Comment by poire-z** [comment]
> I think it's clearer to have the tap menu with locations (like we do)

I agree,
Couldn't we just move the 4 `Tap y x corner` in a `Tap corner >` submenu, like all the others?
It woule make the main menu one single page.
And the `Tap y x corner` ones are the only ones not (yet) showing the associated action in parenthesis in the menu text. Adding that while they are in the main menu would make that main menu a bit ugly, but no pb if they are moved in a submenu.

**Comment by noembryo** [comment]
@Frenzie So, is the "Shut down reader" added to the gesture manager options?

**Comment by Frenzie** [comment]
It was added a few days ago in #5202.

**Comment by noembryo** [comment]
Oops, I missed it... :o)
Thanks!
