### ISSUE TITLE
Framework drawing clock & battery over KOReader

### ISSUE THREAD

**Issue by Pandentia** [koreader/koreader#5022]
* KOReader version: 2019.05, 2019.04
* Device: Kindle Paperwhite 4 (No SOs/8GB/WiFi-only) with (consumer) firmware 5.10.1.3

#### Issue

Kindle's framework (Home UI) seems to be drawing certain UI elements over KOReader spontaneously.

#### Steps to reproduce

None specifically (sorry), though I have noticed an increase in occurrence after a pop-up message appears at the top of the screen ("Frontlight is off.", etc). I've also seen it happen with the top menu open or shortly after closing, and just today I've seen it shortly after the screensaver triggered. (Just as I was writing this report, I've seen it occur while opening a book and the "Opening {filename}" message was displaying, twice.) **TL;DR:** Pretty much everywhere, mostly after touch events, randomly.

Presumably some condition combined with a framework update requiring a redraw (clock roll-over, battery percentage update, etc). Thus far I've seen it happen with battery status and clock, but not WiFi indicator. ~~I'll attach some screenshots later if I can catch it again (and find a way to scrape it off the framebuffer).~~

Edit: Upon closer inspection of related (Kindle) issues, this seems to be a known but unreported bug. I'll leave it open.

#### File browser, shortly after KOReader restart through top menu

![screenshot_2019_05_11T21_59_26+0200_blurred](https://user-images.githubusercontent.com/10685096/57574444-90a1ee00-7439-11e9-8b15-acf8e2683c71.png)

**Comment by NiLuJe** [comment]
Is the clock up to date when it seeps through?

But, yeah, there's nothing much we can do about it, there's already a giant pile of hacks in place to make it mostly behave...

**Comment by Pandentia** [comment]
It is, yes. Same applies for battery status.

**Comment by Frenzie** [comment]
I'll close this since @NiLuJe says there's nothing that can be done. I hope it's not too annoying. :-)

**Comment by Pandentia** [comment]
Okay. I'll report back if I do happen to find a fix nonetheless.

**Comment by yparitcher** [comment]
this is fixed by #5943
