### ISSUE TITLE
Question: Add characters to the en_popup.lua

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#5023]
So, I notice that the `std.lua` keyboard layout is not used anymore and instead there is the `en_popup.lua` in the `keypopup` folder.

I would like to make a greek version of it (maybe an `el_popup.lua`) for the greek GUI, but also add all the missing greek letters to the `en_popup.lua`, because that's what I'll be using (english GUI with the option to write with greek too).

Is there a template or some rules that I have to follow or should I just replace whatever charecters I want?

**Comment by Frenzie** [comment]
Depends a bit on the modifications. There's room for (some) additions to English itself of course.

Besides that you can do it like French or go more in-depth and clone the original English.

**Comment by noembryo** [comment]
@Frenzie I updated the [Greek keyboard layout](https://github.com/koreader/koreader/files/3174589/el_keyboardlayout.zip) by adding an `el_popup.lua` for popups.
Is it OK like this? If it is, can you add it to the project? (I suck at git ;-)

I'm using it as `en_keyboard.lua` to have it with the english GUI.

BTW How difficult it is to add a long press to the "Globe" key of the keyboard, so that we can select another `xx_keyboard.lua`?
Is the keyboard loaded on start, or it can be reloaded later?

**Comment by Frenzie** [comment]
> BTW How difficult it is to add a long press to the "Globe" key of the keyboard, so that we can select another xx_keyboard.lua?

Not very, but it does take time. PRs/contributions welcome. ;-) The relevant open issue is #3998 btw.

**Comment by Frenzie** [comment]
> Is it OK like this?

Yes, but could you clean it up slightly? The el_popup file contains some unused stuff imported from `en`.

**Comment by noembryo** [comment]
Removed the commented Q, W letters and the symbols: [el_popup.zip](https://github.com/koreader/koreader/files/3178203/el_popup.zip)

BTW, in the original `en_keyboard.lua` @99:43 there is a `","` instead of a `com` (or am I wrong?)

**Comment by Frenzie** [comment]
Probably a mistake, although of course in theory the comma keys can be made context-dependent.

**Comment by Frenzie** [comment]
Oh, that's the one with the numbers. That was probably on purpose. Doesn't really matter one way or the other I'd say, so I might as well make it consistent.

**Comment by noembryo** [comment]
Removed some comments from [el_keyboard.zip](https://github.com/koreader/koreader/files/3178239/el_keyboard.zip) too..
I wish I could be of more help and I started a few times to learn Lua just for KOReader, but I couldn't keep me motivated enough.
There is a lack of feedback from the code since I can not run it from my windows machine.
I'm used with python to execute the code all the time and see the results...

**Comment by Frenzie** [comment]
Oh, I just merged the code since I didn't have any issues with them. (It probably makes it clearer where keys haven't been customized) Would you still like to remove the comments?

> There is a lack of feedback from the code since I can not run it from my windows machine.
I'm used with python to execute the code all the time and see the results...

You should be able to do just that with the AppImage if you have the WSL or Docker set up, or in a VM. (Slightly off-putting, admittedly, but not necessarily much more so than installing Python on Windows.)

You can run the AppImage with `--appimage-extract` so you don't have to set up the full dev environment. Then you can just change & run the Lua.

**Comment by noembryo** [comment]
>Oh, I just merged the code since I didn't have any issues with them. (It probably makes it clearer where keys haven't been customized) Would you still like to remove the comments?

No, its OK with me.
>(Slightly off-putting, admittedly, but not necessarily much more so than installing Python on Windows.)

but Python is just a setup.exe :o)
Just show your info for the WSL at the other thread.
Its getting a lot of trouble for me, since I try to avoid win10 as much as I can ;o)
Also missing a lot of knowledge for the AppImage stuff, so I'll have to wait for another option in the future.. :-(

**Comment by NiLuJe** [comment]
FWIW, I generally just test everything on-device, I have a one-liner that'll scp "dirty" files in my tree to the device, and then it's just a matter of restarting KOReader ;).

Granted, when you mess up enough to cause crashes, it gets slightly less fun because of the overhead of restarting Nickel ;).

**Comment by noembryo** [comment]
>FWIW, I generally just test everything on-device, I have a one-liner that'll scp "dirty" files in my tree to the device, and then it's just a matter of restarting KOReader ;).

That's a nice idea, but a drawback I can see, is that long development times would really tax the reader's hardware (have it connected and open all the time).
Also there must be a way to not have to mount/unmount the USB all the time.
Do you do it with a script?
I use KSM7 to connect the reader to the PC, so I have to do it manually...

**Comment by NiLuJe** [comment]
I use scp, and my devices all have an SSH server running in the background at all times. So I can even do that over WiFi when I feel extra-lazy ;).
