### ISSUE TITLE
crash on selecting/long press when viewing cbz files

### ISSUE THREAD

**Issue by sat3ll** [koreader/koreader#5024]
* KOReader version: v2019.05
* Device: Kindle Fire HD 7" 2nd generation (2012)

#### Issue
When viewing a cbz file, if I long press (accidentally) it selects/highlights some part of the text before crashing.

#### Steps to reproduce
Open a cbz file
Long press/select/highlight somewhere on the content (could be text) (could take a few tries (usually <= 2))

##### `crash.log` (if applicable)
crash.log not found

**Comment by cramoisi** [comment]
Yup, reproduced on my KA1. here is a log

[crash_cbz.txt](https://github.com/koreader/koreader/files/3171841/crash_cbz.txt)

**Comment by Frenzie** [comment]
I'm not entirely sure how one would accidentally highlight something? :-P

**Comment by cramoisi** [comment]
@Frenzie  : falling asleep when reading ;)
