### ISSUE TITLE
High Processor usage at kindle

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#5029]
Hello, I´m getting high processador usage using kindle ppw3, I´m using the newest nightly, but I dunno when the problems appers, probably not today.
I´m getting this if I open a PDF or EPUB, the size doesn´t matter. 
The processor is around 27%. As fas as I remember, this should be around 5%, at least this is the number that flash in my memory. Is anyone getting this problem too? Maybe I need a fresh install?

**Comment by Frenzie** [comment]
Even 5 % sounds very high tbh. You mean this is when a document is opened and displayed? How do you check it?

**Comment by Eduardomb22** [comment]
I opened the document, I went to the system statistics menu.

this is after some minutes reading, but was 27% since the begging.

![Reader_2019-May-15_110943](https://user-images.githubusercontent.com/20425689/57783855-418fdd80-7705-11e9-8a96-87226a0d999a.png)

Later I will try some old versions to see if I have the problem.

**Comment by Eduardomb22** [comment]
![Reader_2019-May-15_122749](https://user-images.githubusercontent.com/20425689/57788825-24134180-770e-11e9-9fb0-f471557a401f.png)

This is with koreader-kindlepw2-arm-kindlepw2-linux-gnueabi-v2019.03.1

This very high, but not 27%

**Comment by Frenzie** [comment]
It seems unlikely that it would come from KOReader. Probably the Kindle system something or other.

**Comment by poire-z** [comment]
The value you're showing on these screenshots is in the "System information" subsection, so it indicates the global processor usage by all processes.
There's an other one before, on the first page, under "Process", between "ID" and "Threads", which should tell the processor usage of the current single KOReader process. What does it say ?
(^checked on the emulator, looks like it should be the same on our Kindle or Kobo)

If the koreader process % is low, well, probably not a koreader issue (unless it's some other Kindle process fighting against something koreader does).
Dunno if you need to reboot on Kindle to switch between system reader & koreader. If not, you may start with the Kindle stuff, wait a few minutes, and then launch koreader to see the system % (when koreader was not running). Then, reboot, launch koreader and stay idle for a few minutes, and check the system %, if it differs...
There's some `ps` (with some options I don't have at hand) that you could launch via the Terminal emulator plugin (or via ssh if you can use that) to see which process is really taking cpu time.

**Comment by Eduardomb22** [comment]
> Dunno if you need to reboot on Kindle to switch between system reader & koreader. If not, you may start with the Kindle stuff, wait a few minutes, and then launch koreader to see the system % (when koreader was not running). Then, reboot, launch koreader and stay idle for a few minutes, and check the system %, if it differs...

This helped me! Thanks!

**Comment by poire-z** [comment]
Running `ps -o pid,ppid,user,time,etime,stat,rss,vsz,comm,args` (on my Kobo at least) shows:
```
PID   PPID  USER     TIME   ELAPSED STAT RSS  VSZ  COMMAND          COMMAND
    1     0 root       0:00 5009:03 S     632 2248 init             init
    2     0 root       0:00 5009:03 SW      0    0 kthreadd         [kthreadd]
    3     2 root       0:26 5009:03 SW      0    0 ksoftirqd/0      [ksoftirqd/
[...]
 1336     2 root       0:06 4334:02 SW      0    0 kworker/u:3      [kworker/u:
 1395     2 root       0:20 4110:32 SW      0    0 kworker/u:1      [kworker/u:
[...]
 1705   648 root       0:00 2838:36 S     532 2248 start_koreader.  {start_kore
 1709  1705 root       0:00 2838:36 S     584 2248 koreader.sh      {koreader.s
 1719  1709 root       3:12 2838:36 S     95m 245m reader.lua       {reader.lua
 1720  1719 root       0:00 2838:36 S     888 6536 reader.lua       {reader.lua
[...]
```
The TIME field should show which process has actually used some CPU. My koreader has used 3m12s of CPU, and has been running for 2838 minutes (47 hours uptime, but problably only 2 hours non-sleeping/reading time).

I think on your Kindle you should see a lot more Kindle processes. If it's actually one of them that has used CPU, @NiLuJe might know what each does what.

**Comment by Eduardomb22** [comment]
@poire-z , Do you know what should be a normal number at this system processor stats? Around 10%?

**Comment by AlanSP1** [comment]
As I understood (maybe totally wrong), this is not current processor usage (in percentage), but how much koreader as process (or program so to say) used processor compared to all other processes.

If that is so, 20+% sounds normal, depending how much system has processes (i.e. programs) and how much it uses them in background, without you noticing it.

So, I wouldn't worry.

Also, high processor usage is usually only when you open documents, change pages, or do some other intensive stuff (like change font size). All other times processor is in very low usage. It was tested on Kobos.

Just to mention, on Kobos nickel was more energy efficient (nickel is shipped ebook reading software if you maybe don't know), but it is so small margin and koreader so much better software that I personally don't even think about using nickel over koreader. It all may be applied to kindles.

**Comment by Eduardomb22** [comment]
Thanks for the answer. I was afraid that my system was some problems, because yesterday I read a book and the battery went to 55%, but it dunno how much time I spend reading, probably a lot of hours, hehehe. I pretty sure it was a lot, but thanks for the all the help. I will close this now, it seems ok after I open a kindle book and wait a little, and open koreader after. Thanks all.

**Comment by poire-z** [comment]
On my 48 hours uptime, 2 hours non-sleeping Kobo:
```
System info Processor usage % : 5.74
Process Processor usage % : 2.04
```
And indeed, as mentionned by @AlanSP1 , the Process Processor usage % seems to actually be the % of this process cpu time vs all cpu time used.
So, that might say KOReader has used 2% of these 5.74 %, which seems confusingly very little :|

Again, with KSM and koreader, no Kobo process is running (no nickel stuff at all).
On Kindle, you may have many other kindle processes running, so, you should compare your numbers to some other Kindle users.
