### ISSUE TITLE
RK3368 Support

### ISSUE THREAD

**Issue by rubensa** [koreader/koreader#5033]
There are some issues (#4551 #4595 ) opened for RK3368 devices (like Likebook Mimas and Likebook Mars).

I've found [Tronsmart Orion R68 RK3368 TV Box Firmware and Android SDK](https://www.mediafire.com/folder/4ojpuo3s4m9ct/Tronsmart_Orion_R38_SDK_0713) that could be useful to add support as there seems to be no official [Rockchip Linux](http://opensource.rock-chips.com/wiki_Main_Page) support to this chip.

**Comment by pazos** [comment]
These android devices work like any other phone/tablet. If you find a new android device based on rk3368 which does not work please open a new issue reporting the bug you find.

Thanks
