### ISSUE TITLE
[feat. request] autocopy to clipboard

### ISSUE THREAD

**Issue by shiftyshady** [koreader/koreader#5039]
* KOReader version: 2019.05
* Device: Android

#### Issue:
Dictionary look-ups are very slow on my devide and worse, many times fail to find even simple words (eventhough I have 5 dictionaries all of them including it).
Autocopy word on selection could potentially solve many my dictionary look-up problems (depends on whether tasker clipboard scanner is battery efficient, which I have not yet tested). Better would be that selected words are automatically sent to dictionary apps (and a way to disable it easily so that one can highlight text).
Another improvement IMO would be that instead of showing "searching dictionary for:" (which takes ages on my device) koreader could directly display the pop-up window but with wikipedia, highlight and search buttons on top adding a "copy" button, so that the dict search results can appear below (after a few seconds).

**Comment by Frenzie** [comment]
Which Android on which device? Which words in which dictionaries?

Cf. https://github.com/koreader/koreader/issues/2333#issuecomment-486418545.

**Comment by shiftyshady** [comment]
Sorry, it's been a while. I had a bunch of japanese dictionaries but it does not matter, I think for certain languages it's better to use a dedicated dictionary app like Goldendict. Don't get me wrong, the built-in dictionary search is absolutely awesome, it's just that some languages are better dealt with with dedicated software.

So I would like to disable dictionary searching and get the usual pop-up menu (that's the menu that appears when you select a sentence), but with a 'Send to dictioanry' entry.
For Goldendict the action to execute would be something like this i guess:
`Send Intent [ Action:android.intent.action.SEND Cat:Default Mime Type:text/plain Data: Extra:android.intent.extra.TEXT: MY TEST TEXT Extra: Package:mobi.goldendict.android Class: Target:Activity ]`
