### ISSUE TITLE
fr: option to make status bar on the right or left side

### ISSUE THREAD

**Issue by hiworld3** [koreader/koreader#5044]
if we turn off the progess bar the status bar will be sitting at the middle of the bottom, could we add options to choose the status on left or right side, or even at top or at bottom, thanks...

**Comment by hiworld3** [comment]
add: I mean left corner or right corner, I fear there will be misunderstanding since there's no native speaker here. thx

**Comment by AlanSP1** [comment]
You basically mean that we can choose between left, right or center alignment for status bar, right?
