### ISSUE TITLE
FR wallbag: remove wallabags articles from Koreader history

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#5045]
* KOReader version: 2019.05
* Device: Inkbook Prime (android)

#### Issue

After reading couple articles downloaded using wallabag plugin, Koreader history is littered with all those (mostly 1-5 minutes read) walllag articles and it's hard to find/go back to "real" books within Koreader history.

#### Steps to reproduce
Use wallbag plugin to download articles from your wallabag box, read couple 7-10 articles from wallag. Display Koreader history, try to find non-wallbag book there. 

#### Idea

Remove (while closing) wallbag article from Koreader history, similar to send2ebook plugin, by default, or at least give a setting to disable wallbag articles visiblity in history

**Comment by Frenzie** [comment]
It's exclusively certain plugin-related files you wish to remove from the history and not dead documents in general?

**Comment by mwoz123** [comment]
Rarely delete wallabag article right after finish reading it 
(btw how about new option for afterFinishReadingEvent (or whatever it's called) "delete this book"? create FR for this? )
so it's not about orphans in history, rather read but not deleted yet.

There should be such code in Send2Ebook plugin or NewsDownloader plugin I don't remember.

**Comment by mwoz123** [comment]
Found it:
https://github.com/koreader/koreader/commit/424593ca7c02304e72f8e4e8f53fb43085075a8d#diff-efab783a06b27d501b2fda3af3de62faR353

function name `onCloseDocument`

**Comment by Frenzie** [comment]
Incidentally, the opposite issue can be found here: #4534.

**Comment by mwoz123** [comment]
> Incidentally, the opposite issue can be found here: #4534.

Then option in wallabag settings (and later possibly in news downloader and send2ebook) as proposed in #6046 looks as the best option

**Comment by pazos** [comment]
a bit offtopic:

@mwoz123: send2ebook app is currently broken. I'm not sure if it worked at some point but I'm not able to make it work in any device/emulator.

**Comment by mwoz123** [comment]
continueing oftopic :

@pazos could you create a story then and describe the issue? 
Last time I used it was ~1-2 months ago with cba.pl ftp, but it worked fine. 
Know limitation is it cannot download subfolders, only files.

**Comment by pazos** [comment]
Already documented in https://github.com/koreader/android-send2ebook/issues/3. Just commented there. Lets move offtopicness there too :smile:

**Comment by Frenzie** [comment]
Implemented by #6048.
