### ISSUE TITLE
FR: move current article to favourites (general/wallabag/newsdownloader/send2ebook)

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#5046]
* KOReader version: 2019.05
* Device: 

#### Issue

Often reading a article downloaded from internet (via wallbag/news downloader or send2ebook) I wish there were a function to move current reading article from this folder to a "favourites" folder (so I wont' lose it e.g. with "delete all readed" function). 

There could be a setting to choose one folder and mark it as 'favourite', and then a option "move current article to favourites" folder on current reading book .

It mostly usefull for above metioned plugins but could be an koreader menu option (or even separate plugin to move it if you don't agree to have it in main code).

**Comment by Frenzie** [comment]
The suggestion seems redundant with cut, folder shortcuts, paste.

But perhaps "paste here" could be added as an action in folder shortcuts (besides edit & delete), which would also make it directly accessible from the reader. Pinging @robert00s who implemented folder shortcuts.

**Comment by mwoz123** [comment]
> The suggestion seems redundant with cut, folder shortcuts, paste.

It's ok if you do this once (and if folders are nearby, so you don't have to change couple folder to get to "favourites" (and then way back (for another one?;))) but once you do this couple times you wish there was an option to do this automaticly;)

Most of the articles apps have a functionality to "star" of "move to favourites" don't have to search far - e.g. even  wallabag android version has it;) 

How about separate plugin then? 
2 menus :
- "move to favourites folder" (with SDR),
- "select favourites folder"
?

**Comment by Frenzie** [comment]
Like I said, just add it to folder shortcuts.

**Comment by Frenzie** [comment]
## 1. Simpler to implement here:
![Screenshot_2019-05-28_14-29-05](https://user-images.githubusercontent.com/202757/58477912-08b82580-8155-11e9-896f-4ca96134aa8d.png)

## 2. Harder to implement, easier to use here:
![Screenshot_2019-05-28_14-29-14](https://user-images.githubusercontent.com/202757/58477913-0950bc00-8155-11e9-969a-0bdee821fd32.png)
