### ISSUE TITLE
Wallabag plugin:  download failed - name with quotation mark, hash and comma

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#5049]
* KOReader version: 2019.05-10-...2019-05-22
* Device: Inkbook (android)

#### Issue
(This doesn't seem to be correctly process by wallabag server but) noticed that it has problems probably with quatation mark (as it couldn't be downloaded by wallabag plugin). 
It was named on my framabag:
`Jak koduje się pilota (scyzoryk) do #peugeot 307 po lifcie? W necie są "jakieś" instrukcje, każda jest inna, a nic nie idzie. Ktoś zna sposób? #motoryzacja #pytanie`

#### Steps to reproduce
add 
https://www.wykop.pl/wpis/13795011/jak-koduje-sie-pilota-scyzoryk-do-peugeot-307-po-l/
to your wallabag 

Try to download with Koreader's wallabag plugin

**Comment by mwoz123** [comment]
Just noticed it has even worse name:


`            Jak koduje się pilota (scyzoryk) do # <a class="showTagSummary" href="https://www.wykop.pl/tag/peugeot">peugeot</a> 307 po lifcie? W necie są "jakieś" instrukcje, każda jest inna, a nic nie idzie. Ktoś zna sposób? #<a class="showTagSummary" href="https://www.wykop.pl/tag/motoryzacja">motoryzacja</a> #<a class="showTagSummary" href="https://www.wykop.pl/tag/pytanie">pytanie</a>`

**Comment by Frenzie** [comment]
Wallabag issue, not KOReader:

```
05/30/19-18:04:07 DEBUG Wallabag: DOWNLOAD: filename:  /home/frans/src/koreader/test/[w-id_1969015] Jak koduje się pilota (scyzoryk) do #<a href="#peugeot">peugeot<_a> 307 po lifcie? W necie są &quot;jakieś&quot; instrukcje, każda jest inna, a nic nie idzie. Ktoś zna sposób? #<a href="#motoryzacja">motoryzacja<_a> #<a href="#pytanie">pytanie<_a>.epub
05/30/19-18:04:07 DEBUG Wallabag: URL      https://framabag.org/api/entries/1969015/export.epub
05/30/19-18:04:07 DEBUG Wallabag: method   GET
05/30/19-18:04:07 DEBUG Wallabag: Server error:  /home/frans/src/koreader/test/[w-id_1969015] Jak koduje się pilota (scyzoryk) do #<a href="#peugeot">peugeot<_a> 307 po lifcie? W necie są &quot;jakieś&quot; instrukcje, każda jest inna, a nic nie idzie. Ktoś zna sposób? #<a href="#motoryzacja">motoryzacja<_a> #<a href="#pytanie">pytanie<_a>.epub: File name too long
```

**Comment by Galunid** [comment]
I fixed this for myself, by leaving `[w-id_1969015]` this as a name, the book image has the proper title anyway.

**Comment by Frenzie** [comment]
@Galunid The debug statement misled me. The problem was simply that the "extension" was too long.
