### ISSUE TITLE
calibre plugin shows 'turn wifi on' when wifi is on

### ISSUE THREAD

**Issue by EmpressFiona** [koreader/koreader#5058]
* KOReader version: v2019.05
* Device: Kindle Keyboard

#### Issue

When attempting to connect to calibre using the provided plugin, most of the time it tells me to turn wifi on. Wifi is, in fact, already on (and I don't think I can toggle it one way or another without returning to the Kindle framework); however, it shows that the ping to my gateway has FAILED. I got it to show 'cannot connect to server' a couple of times instead, and managed to successfully connect _once_ and transfer a file over; I don't know what the difference is, besides 'turning it on and off again' on both the Kindle and 

I believe this issue is related to #4879 as it has similar symptoms. I tried to ping the gateway, and doing so revealed something very strange: `ping` provides _no output whatsoever_. `ls` does, so the terminal seems to be working fine overall - I don't know what the issue is! It's entirely possible something's wrong on my end of the configuration, but I don't know what it would be.

Either way, because the calibre lua files don't use the same methods of determining whether the Kindle is online or not, I can't fix it myself using the method described in #4879.

#### Steps to reproduce

I couldn't tell you what the actual steps to reproduce are. I'd suggest just testing it on a Kindle 3 of your own and seeing if any problems arise.

As an aside, though - is there any way to use the hardware keyboard? Using a touch keyboard UI with a d-pad is an absolutely atrocious way of entering text, although I suppose the Kindle 3's keyboard isn't much better.

**Comment by NiLuJe** [comment]
On which FW version is that?

**Comment by NiLuJe** [comment]
I *think* the keyboard issue isn't Kindle-specific, I have a vague memory of the emulator behaving that way. @Frenzie?

**Comment by EmpressFiona** [comment]
FW 3.4.2 with the latest jailbreak. If this commit will fix it, when will the daily be available? Thanks for the prompt response!

I seem to recall reading in some of the issues I skimmed on the keyboard to figure out if it was a bug that external keyboards weren't supported in Android or other contexts where they're available. Is a fix for this planned if it affects more than legacy Kindles?

(I had another issue where trying to change the margin settings causes the system to lock up, but I'll make another thread for that one when I have access to the crash log.)

**Comment by NiLuJe** [comment]
Roughly every morning at 7AM UTC ;).
