### ISSUE TITLE
Book status is not saved on End of Document actions

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#5060]
* KOReader version: 2019.05-18
* Device: All

#### Issue

Upon reaching the end of a book, choosing "File browser" as the end of document action will properly drop you back to the FM, but the book's progress won't have been saved: instead of showing "Finished" (or at the very least 100%), it's showing the previous status (i.e., whatever it was when you opened the book).

Going back to the FM from the menu does not exhibit this issue.

#### Steps to reproduce

Open a random book, taking note of the current progress.
Go To > Last page
PgNext until you hit the EoD action.

(I'm using the default setting of "popup", but I suspect *every* action, not just "back to FM" suffers from this).

Not familiar at all with [this piece of code](https://github.com/koreader/koreader/tree/master/frontend/apps/reader/modules/readerstatus.lua), so, open to any ideas you might have ;).

**Comment by Frenzie** [comment]
I'd expect the problem to be in the popup, not in ReaderStatus?

**Comment by Frenzie** [comment]
Incidentally, the Wallabag "go to folder" action doesn't properly close the currently open document either.
