### ISSUE TITLE
Night mode does not work in Kobo Aura H2O Edition 1 N250

### ISSUE THREAD

**Issue by adamryczkowski** [koreader/koreader#5061]
* KOReader version: `v2019.05-19-g89e002f_2019-06-05` and also current stable
* Device: Kobo Aura H2O Edition 1 N250

#### Issue

Night mode does not work. 

#### Steps to reproduce

1. Update koreader
2. Open your favorite book (tested on PDF)
3. Try to turn on night mode. Although the checkbox gets checked, the screen keeps showing black text on white background

**Comment by NiLuJe** [comment]
On which FW version is that? And ate you really absolupositively sure it's an H2O? Can you post a crash.log?

**Comment by adamryczkowski** [comment]
No crash logs - just night mode ceased to work after I upgraded from koreader dated from December 2018.
Yes, absolupositively sure it is that it is a Kobo Aura H2O, released on 2014 (i.e. edition 1), model nr N250. I know Kobo has a weird naming scheme, but you can trust me I got the version right.

**Comment by adamryczkowski** [comment]
When I press the "night mode" checkbox, the screen flashes, turning the inverse mode for an instant, just long enough to notice, and immediately returns to the white background with a black text while keeping the checkbox still checked.

**Comment by NiLuJe** [comment]
There's *always* a crash.log ;).

Which firmware version are you running? I'm guessing something tremendously
old, right?

**Comment by adamryczkowski** [comment]
Thank you a lot. Since last time I opened nickel was over a year ago, I kind-of assumed, that the koreader+KSM itself are the only firmware... Of course, you were right. My firmware was ancient, `3.19.5613`. I did upgrade, and now all the problems (including this one) solved itself. Thank you!
