### ISSUE TITLE
Frontlight support for Onyx Boox Note Pro

### ISSUE THREAD

**Issue by elc00l** [koreader/koreader#5072]
* KOReader version: 2019.06
* Device: Onyx Boox Note Pro, Android 6.0.1

Currently frontlight adjustments don't work at all on Note Pro so I have to exit KOreader every time I want to change it and use system settings.

**Comment by pazos** [comment]
We're using normal framework to change light levels (white leds only!).

Keep in mind:

1. There's no framework to modify orange levels
2. There's no framework to turn on a light to specified value if the light is currently off.

Anyways, If isn't 1 or 2 we will need logs `adb logcat KOReader:* AndroidRuntime:* *:F`

**Comment by pazos** [comment]
And even when KOReader is a fullscreen app you can "swipe down" from the top of the screen and you should see the android bar, which hopefully has a link to frontlight settings.

**Comment by elc00l** [comment]
Unfortunately it isn't 1 nor 2 from your conditions  and if trick with sweeping down to see system bar would work for me it'd be enough but it also doesn't work :( Maybe at least there could be option to toggle between full screen and window modes in gestures.
Anyway I'm not sure if it's possible to gather the logs you requested on this device, I can try, at least there's an option to enable USB debugging in system settings.

**Comment by pazos** [comment]
> Maybe at least there could be option to toggle between full screen and window modes in gestures?

We cannot change android behiavour. We're a full screen app and the system provides a way to show system controls over the application on Android 4.4+

Look how to show status bar on a mimas (the gesture around the end of the video) -> https://youtu.be/n6-2wX5F8OM, if you're in portrait the gesture is top to bottom. If you're in landscape the gesture is right to left

**Comment by pazos** [comment]
@elc00l: I saw your logs, but no trace about light changes, did you try to change fl level while logging?

Also, did you look the video and are you able to reproduce the gesture to show system bar?

Please anwser to #5073 instead, I'm closing this issue :+1:
