### ISSUE TITLE
EeWrite E-Pad ships KOReader without complying with AGPLv3 license

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5075]
Was launched at Kickstarter https://www.kickstarter.com/projects/479880611/e-pad-the-e-ink-android-tablet?lang=es

Seem to be a clone of http://www.wisky.com.cn/en/design/info_68.aspx?itemid=288

It has some form of basic/modified KOReader. See https://www.youtube.com/watch?v=MihtrS-Ix90

They need to release sources for the entire program (including the wacom overlay you see on the video) or get rid of KOReader entirely.

https://www.kickstarter.com/help/copyright

**Comment by Frenzie** [comment]
I believe the source only has to be made available to users, not to random onlookers, even if not doing so goes against the spirit of the thing. But it's definitely something to keep a close eye on. If I understand correctly it won't actually have any users till August?

**Comment by pazos** [comment]
I'm closing this issue because the whole company / product seems a scam. I will open it again if they deliver something fishy.

**Comment by Frenzie** [comment]
It's weird that they'd share news like [this](https://goodereader.com/blog/electronic-readers/wisky-is-going-back-to-the-drawing-board-with-the-eewrite-e-pad) with a news site and not their backers…

**Comment by pazos** [comment]
Awesome borked project. Here's a dump of main apps the software has: https://www.reddit.com/r/e_pad/comments/drnlgi/i_have_copies_of_the_eewriter_epads_default/

If you download com.wisky.reader and open it you'll find something very interesting and maybe familiar enough.

**Comment by Frenzie** [comment]
It seems to be based on a version from over a year ago.

**Comment by gabefair** [comment]
After many years of waiting, I have received the e_pad and have successfully rooted and imaged it. If anyone needs things from me, you can contact me here or with any of my platforms linked on my [keybase](https://keybase.io/gabefair).

**Comment by Frenzie** [comment]
@gabefair Thanks for the offer. Except possibly for whatever mostly hidden Android-specific backend stuff they tweaked, a regular user's perspective would be of bigger interest as a starting point to me. I.e., what have they implemented on top of KOReader that could potentially be interesting to backport. (Assuming it's not completely hackish.)

So that'd basically mean firing up the AppImage/Debian package/Android release (unless you have another proper ereader) side by side with the thing to see if anything sticks out.

**Comment by pazos** [comment]
I think that the only thing we can do, legally, is report copyright violations to artifex/coolreader/k2pdfopt and see if they want to do a thing. The project raised 400000$, so there's some incentive.

It is a shame that new "companies" use these methods. They go against their users mainly but against their maintainers too. That's why good android apps like Ebookdroid and FBReader went closed-source and their latest open versions are still used today by major ebook reader programs, like Boyue.

@gabefair: feel free to install yourself a legit version of KOReader and see which one works better for you. The only thing we're missing is the transparent layer used to take notes on top of the program itself. I'm more interested about the things they're stripped out (and the reason to strip out these features).

You and other buyers have rights to demand the entire source code used for build com.wisky.reader.

**Comment by pazos** [comment]
Another crappy copy of the E-pad running a crappy KO build -> https://www.youtube.com/watch?v=EZYlb6lL7Ds

We can start calling this version KrappyReader.

**Comment by pazos** [comment]
I'm going to close this issue because the following reasons:

- source is provided in lua
- the android-luajit-launcher modifications are covered by MIT
- we can't grab a single thing they did:

I reviewed both source changes and user experience.

Source changes:

- a lot of "gaolixu logs"
- implemented a crappy content resolver that seem to work - sometimes - to guess file paths from content uris.
- changed framebuffer to RGB565 to work with overlays.
- changed input to handle specific things: MT_PRESSURE and MT_TYPE? I guess they're related to wacom but I dunno.
- changed input handlers so now the input queue is filled with legacy input events, all of them will be replayed later.

Ux: a crap. 

- Writting in a keyboard is a crap and lags a lot (100-200ms per key pressed and since queue grows and every event will be forwarded to frontend you can easily generate a more than **one minute** input lag just by typing a few words)
- They removed the main intent so the app isn't listed in the launcher
- They removed the shortcut to open the file manager from the reader app. You can still access the reader app by finishing a book and press return to filemanager.
- They still use our domain for settings, so if you have both apps installed and modify one of them the other will be changed too (if both apps handle the change in question).
- Impossible to change document fonts for reflowable types (lol) @poire-z - lol
- Of course no styletweaks, no dictionary, no wikipedia, no android specific functions (toggle wifi/control lights/open intents)
- No hightlights, no nothing.

A *REAL* **CRAP**

**Comment by Frenzie** [comment]
Alright, thanks for investigating. :+1: 

> changed input to handle specific things: MT_PRESSURE and MT_TYPE? I guess they're related to wacom but I dunno.

I'm pretty sure most regular touch also does that, at least these days. Just less precise. But it's not really "pressure" so much as "contact area" in that case.

**Comment by pazos** [comment]
> I'm pretty sure most regular touch also does that, at least these days. Just less precise. But it's not really "pressure" so much as "contact area" in that case.

Cool, I didn't investigate because of the general input lag.

One image worth more than 1000 words:

E-pad "reader" app (notice the white dots showing when the input was registered by android):

![test](https://user-images.githubusercontent.com/975883/71548041-a3f1d180-29a8-11ea-8608-ef9a5dc38451.gif)

The same test on koreader:

![test2](https://user-images.githubusercontent.com/975883/71548052-bf5cdc80-29a8-11ea-853d-62cc20be89e2.gif)

**Comment by Frenzie** [comment]
Wow, that's pretty bad.
