### ISSUE TITLE
(KT4) Screen not refreshed correctly and flickering in Night mode

### ISSUE THREAD

**Issue by j-h-h** [koreader/koreader#5076]
* KOReader version: koreader-kindlepw2-arm-kindlepw2-linux-gnueabi-v2019.05-25-g5df31f2_2019-06-09
* Device: KT4

#### Issue
Screen not refreshed correctly and flickering in Night mode 

#### Steps to reproduce
1. Enter file manger or open a document.
2. Activate night mode, night mode successfully activates.
3. Now tap anywhere to trigger a change in the screen content, resulting in the new content written over (overlapping) the old content and flickering.

##### `crash.log` (if applicable)
Verbose log attached.
[crash.log](https://github.com/koreader/koreader/files/3285914/crash.log)

**Comment by NiLuJe** [comment]
A video would be nice ;).

**Comment by NiLuJe** [comment]
Or, even better, a strace of awesome when the framework itself is put in night mode ;).

```strace -fitv -e trace=ioctl -p $(pidof awesome)```

With this strace build: http://files.ak-team.com/niluje/mrpub/Other/strace-pw4.tar.gz (the one in USBNet will probably crash on a KT4).

**Comment by j-h-h** [comment]
Here's the video.
[https://gofile.io/?c=E4KRxA](url)

I'll see if I can do the USBNet and stance command, it's above my current knowledge... :)

Thank you!

**Comment by j-h-h** [comment]
Running the above command as is while koreader already running only produces this static output:


 1 /mnt/us/strace: Process 2843 attached with 8 threads
 2 [pid  3063] 20:14:56 [769c9ef8] --- stopped by SIGSTOP ---
 3 [pid  3062] 20:14:56 [769c9ef8] --- stopped by SIGSTOP ---
 4 [pid  3061] 20:14:56 [769c9ef8] --- stopped by SIGSTOP ---
 5 [pid  3060] 20:14:56 [76942574] --- stopped by SIGSTOP ---
 6 [pid  3059] 20:14:56 [769c9ef8] --- stopped by SIGSTOP ---
 7 [pid  3038] 20:14:56 [76942574] --- stopped by SIGSTOP ---
 8 [pid  3037] 20:14:56 [769c9ef8] --- stopped by SIGSTOP ---
 9 [pid  2843] 20:14:56 [76949574] --- stopped by SIGSTOP ---


I guess I'm doing something wrong. Maybe I need to specify somewhere the right process to attach to?...

**Comment by NiLuJe** [comment]
No, that's perfectly normal, I just need that when you're *outside*
KOReader, in the native system, with the built-in inverted screen setting
enabled (supposedly in the Settings, somewhere possibly labeled
accessibility or something) ;).

**Comment by j-h-h** [comment]
Err... the cheap "basic" model doesn't have this feature unfortunately... And I don't own a PW.
(Also it doesn't have touch lock BTW.)
This why we need KOReader in the first place!

**Comment by j-h-h** [comment]
I've found a workaround by setting full refresh rate to every page (Settings > Screen > E-ink settings > Full refresh rate).  After dictionary lookup I need to trigger manual refresh by swiping diagonally. This won't help for menus though.

**Comment by NiLuJe** [comment]
Could you try today's nightly? I expect it will utterly wreck your workaround, but I'd like to be sure of that before fixing this ;).

**Comment by j-h-h** [comment]
Yes, in the last nightly the screen flickered frantically in night mode regardless of screen refresh rate settings. Almost had to force reboot to reverse night mode (SSH was off...). 
I'm glad you're going to fix that.

**Comment by NiLuJe** [comment]
Yup, you can try https://github.com/koreader/koreader-base/pull/928 in the meantime, that *should* settle things ;).

**Comment by j-h-h** [comment]
Yes, that fix night mode. Thank you so much!
Setting full refresh for every page still helpful to avoid some ghosting.
#5019

**Comment by NiLuJe** [comment]
Thanks for testing ;).

Yeah, ghosting is to be expected, since, well, no fancy nightmode waveforms ;).
