### ISSUE TITLE
WebDAV Cloud storage yields an "Empty folder" response for a non-empty folder.

### ISSUE THREAD

**Issue by zfnmxt** [koreader/koreader#5077]
* KOReader version: 2019.06
* Device: Kobo Clara HD

I can't figure out why this is happening. I've looked at the httpd access logs on the host machine, and it is receiving the `PROPFIND` request from the Kobo:

```
<ip address> - <user> [14/Jun/2019:15:40:23 +0200] "PROPFIND / HTTP/1.1" 207 856
```

The root folder definitely has files in it, and I've tried accessing the WebDAV storage on other clients and it worked fine. Here's the relevant config from my `httpd.conf`:

```
   DavLockDB /var/www/davlock
       <Directory "/var/www/public/">
           Dav On
           AuthType Basic
           AuthName "dav"
           AuthUserFile /var/www/.htpasswd
           Require valid-user
       </Directory>
```

Has anyone else experienced this issue? Any idea how I can solve it?

**Comment by zfnmxt** [comment]
On another note, if I can't get WebDAV to work, does anyone have other syncing suggestions? Is something like `rsync` + `cron` viable? I'm sorta steering away from ftp due to security concerns (I'm going to switch to https for the WebDAV stuff once it works...).

**Comment by NiLuJe** [comment]
That vaaaaguely sounds familiar, try seeing if a similar issue wasn't raised in the past, either here or on MobileRead...

**Comment by NiLuJe** [comment]
cron is tricky on these devices, as they essentially spend most of their time in suspend, so, cron is out. And getting rtcwake to behave is tricky, because completely device-specific, and sometimes just plain broken.

But rsync on its own does wonder, that's mainly what I'm using if I feel the need for large transfers or proper syncs. Otherwise, simply scp/sftp.
But, again, manual interaction.

**Comment by pazos** [comment]
offtopic: did someone said a webdav server running on eink devices?. That would be great 😁

**Comment by zfnmxt** [comment]
I ended up using [Syncthing under KSM](https://www.mobileread.com/forums/showpost.php?p=3244608&postcount=82). I updated the package with the latest Syncthing binary and it works great. Probably a superior solution to the WebDAV one tbh. :)

Gonna close the issue.

**Comment by jp8** [comment]
#5171

**Comment by zmlww** [comment]
Thanks @jp8!
