### ISSUE TITLE
Visualize a little more the names of files in the file browser.

### ISSUE THREAD

**Issue by mayabtlaloc** [koreader/koreader#5090]
* KOReader version: KOReader 2019.06 "Sea Buckthorn"
* Device: kobo aura One

What part of the code should be modified so that the size of the files does not appear in the file browser and the file names can be displayed a little longer.
Thanks for your reply.
attached image:
![20190625_065447-2222](https://user-images.githubusercontent.com/2880036/60098343-eb0dba00-971a-11e9-9e99-27b8320db834.jpg)

**Comment by poire-z** [comment]
Should just be a matter of commenting one line (by adding `--` in front of `mandatory =`
```diff
--- a/frontend/ui/widget/filechooser.lua
+++ b/frontend/ui/widget/filechooser.lua
@@ -240,13 +240,13 @@ function FileChooser:genItemTableFromPath(path)
     for _, file in ipairs(files) do
         local full_path = self.path.."/"..file.name
         local file_size = lfs.attributes(full_path, "size") or 0
         local sstr = getFriendlySize(file_size)
         local file_item = {
             text = file.name,
-            mandatory = sstr,
+            -- mandatory = sstr,
             path = full_path
         }
         if show_file_in_bold ~= false then
             file_item.bold = DocSettings:hasSidecarFile(full_path)
             if show_file_in_bold ~= "opened" then
                 file_item.bold = not file_item.bold
```
(There is a similar section for directories above this one, in case you want that for them too.)

(Referencing #4757 for some past hacks to the file browser, from which I guess this is a followup tweak :)

**Comment by mayabtlaloc** [comment]
Thanks, poire-z, This works well. Of course this is a followup tweak of https://github.com/koreader/koreader/issues/4757
Just one more thing. Can be also deleted the "three points" that appear after the file names?
attached image:
![20190625_065447-333](https://user-images.githubusercontent.com/2880036/60117113-0ab6d980-973f-11e9-9d4b-86ea47932334.jpg)

**Comment by poire-z** [comment]
One line to add to override the `indicator = ellipsis` with just an empty string.
That's the 2nd part of the following patch, which includes the first part that you are already using (from https://github.com/koreader/koreader/issues/4757#issuecomment-471228409):

```diff
--- a/frontend/ui/widget/menu.lua
+++ b/frontend/ui/widget/menu.lua
@@ -142,6 +142,8 @@ local MenuItem = InputContainer:new{
 }

 function MenuItem:init()
+    self.font_size = 30
+    self.single_line = true
     self.content_width = self.dimen.w - 2 * Size.padding.fullscreen
     local shortcut_icon_dimen = Geom:new()
     if self.shortcut then
@@ -199,6 +201,7 @@ function MenuItem:init()
         local w = RenderText:sizeUtf8Text(0, self.dimen.w, self.face, my_text, true, self.bold).x
         if w + mandatory_w + state_button_width + text_mandatory_padding >= self.content_width then
             local indicator = "\226\128\166 " -- an ellipsis
+            indicator = ""
             local indicator_w = RenderText:sizeUtf8Text(0, self.dimen.w, self.face,
                 indicator, true, self.bold).x
             self.text = RenderText:getSubTextByWidth(my_text, self.face,

```

**Comment by mayabtlaloc** [comment]
Thanks for your quick response, all the changes worked very well.
