### ISSUE TITLE
OPDS Catalog Removal crash

### ISSUE THREAD

**Issue by AluminumTank** [koreader/koreader#5091]
- Version: 2019.06
- Device: Kobo Glo HD

When trying to remove default OPDS catalogs (specifically ManyBooks, Internet Archive, Flibusta (Russian), textos.info (Spanish)), there is a crash as soon as "Delete" is pressed.

**Comment by Frenzie** [comment]
Interestingly, this only happens if you already removed a few of them previously (or perhaps also if you added something). On a clean install this can't be reproduced.

**Comment by Frenzie** [comment]
PS The crash.log file is really quite useful. I could've seen the problem without having the program available then. ;-)

If there are fewer than 4 servers, this line will crash:
https://github.com/koreader/koreader/blob/a791a7df56ff47ac6fa4688ba1610576b0c6272a/frontend/ui/widget/opdsbrowser.lua#L92-L93
