### ISSUE TITLE
Add more fonts for AppImage/desktop

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#5093]
Is it possible to do the same for koreader.AppImage? 
I created a fonts folder under ~/.config/koreader and put some fonts inside, the AppImage does not detect them.

_Originally posted by @ChenguangZhang in https://github.com/koreader/koreader/issues/5013#issuecomment-505567224_

<hr>

Right now you can set the `EXT_FONT_DIR` variable, so it could also be solved through the launch script.

**Comment by ChenguangZhang** [comment]
Thanks, but doesn't seem to work (I run the AppImage after "export EXT_FONT_DIR=~/.config/koreader/fonts/", both from the same terminal window).

A search of EXT_FONT_DIR in the repository shows nothing.

**Comment by pazos** [comment]
@ChenguangZhang: 

`export EXT_FONT_DIR="${HOME}/.fonts"`

So, you need to create a folder called `.fonts` under your home path and copy your fonts to that folder. It should work.

**Comment by pazos** [comment]
If you use the debian package then the exported directory is:

`export EXT_FONT_DIR="${HOME}/.config/koreader/fonts"`

I think it doesn't make any sense to have two different paths on the same os and I would change the appImage path to behave like the debian package.

**Comment by NiLuJe** [comment]
I'm pretty sure there should be a FreeDesktop consensus about that kind of thing.

I *think* fontconfig deprecated ~/.fonts, so, something in an XDG path somewhere might make more sense.

**Comment by ChenguangZhang** [comment]
Thanks @Frenzie and @pazos 
The amd64 deb package recognizes the fonts copied into the ~/.config/koreader/fonts folder and works like a charm, and there is no need to specify the EXT_FONT_DIR environmental variable--at least on my laptop. 

I tested AppImage again without success, so a bug may be there. I will use the deb package instead.

**Comment by NiLuJe** [comment]
@ChenguangZhang : I'd suggest ditching youy current search tool, then ;p.

```
┌─(niluje@illyria:pts/11)──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(~/MPLAYER/koreader)─┐
└─(0.12:31%:23:04:%)── rg EXT_FONT_DIR                                                                                                                                                                                                                                                                                                                  ──(Tue, Jun 25)─┘
frontend/fontlist.lua
69:        return os.getenv("EXT_FONT_DIR")

platform/pocketbook/koreader.app
30:export EXT_FONT_DIR="/mnt/ext1/fonts"

platform/debian/koreader.sh
27:export EXT_FONT_DIR="${HOME}/.config/koreader/fonts"
28:[ ! -d "${EXT_FONT_DIR}" ] && mkdir -pv "${EXT_FONT_DIR}"

platform/kindle/koreader.sh
159:export EXT_FONT_DIR="/usr/java/lib/fonts;/mnt/us/fonts;/var/local/font/mnt;/mnt/us/linkfonts/fonts"

platform/cervantes/koreader.sh
65:export EXT_FONT_DIR="/usr/lib/fonts"

platform/kobo/nickel.sh
12:unset OLDPWD EXT_FONT_DIR TESSDATA_PREFIX FROM_NICKEL STARDICT_DATA_DIR LC_ALL KO_NO_CBB

platform/appimage/AppRun
14:export EXT_FONT_DIR="${HOME}/.fonts"

platform/kobo/koreader.sh
72:export EXT_FONT_DIR="/mnt/onboard/fonts"

platform/ubuntu-touch/koreader.sh
17:export EXT_FONT_DIR="${HOME}/fonts"
```

**Comment by NiLuJe** [comment]
And the consensus seems to be `${XDG_DATA_HOME}/fonts` (i.e., `~/.local/share/fonts`), c.f., https://wiki.archlinux.org/index.php/XDG_Base_Directory & https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by pazos** [comment]
@NiLuJe: yup! I used ${HOME}/.config/koreader/fonts as it is the path where the application "koreader" should store its assets based on $XDG_CONFIG_HOME/ + name of the app scheme. But storing fonts shared across applications makes sense to me.

In any case for desktop makes sense to have a menu entry "open font dir" which does `xdg-open ${EXT_FONT_DIR}` and let the user copy stuff freely.

**Comment by ChenguangZhang** [comment]
> @ChenguangZhang : I'd suggest ditching your current search tool, then ;p.
> 
> ```
> rg EXT_FONT_DIR                                                                                                                                                                                                                                                                                                                  
> 
> frontend/fontlist.lua
> 69:        return os.getenv("EXT_FONT_DIR")
> 
> platform/pocketbook/koreader.app
> 30:export EXT_FONT_DIR="/mnt/ext1/fonts"
> 
> platform/debian/koreader.sh
> 27:export EXT_FONT_DIR="${HOME}/.config/koreader/fonts"
> 28:[ ! -d "${EXT_FONT_DIR}" ] && mkdir -pv "${EXT_FONT_DIR}"
> 
> platform/kindle/koreader.sh
> 159:export EXT_FONT_DIR="/usr/java/lib/fonts;/mnt/us/fonts;/var/local/font/mnt;/mnt/us/linkfonts/fonts"
> 
> platform/cervantes/koreader.sh
> 65:export EXT_FONT_DIR="/usr/lib/fonts"
> 
> platform/kobo/nickel.sh
> 12:unset OLDPWD EXT_FONT_DIR TESSDATA_PREFIX FROM_NICKEL STARDICT_DATA_DIR LC_ALL KO_NO_CBB
> 
> platform/appimage/AppRun
> 14:export EXT_FONT_DIR="${HOME}/.fonts"
> 
> platform/kobo/koreader.sh
> 72:export EXT_FONT_DIR="/mnt/onboard/fonts"
> 
> platform/ubuntu-touch/koreader.sh
> 17:export EXT_FONT_DIR="${HOME}/fonts"
> ```

Oh, thanks for pointing out!

**Comment by NiLuJe** [comment]
Yeah, <3 ripgrep ;). (Or the_silver_searcher if rust is an issue).

**Comment by Frenzie** [comment]
@pazos 

> I think it doesn't make any sense to have two different paths on the same os and I would change the appImage path to behave like the debian package.

That one's somewhat legacy, but standard locations like `/usr/share/fonts`, `/usr/local/share/fonts`, `~/.fonts` and `~/.local/share/fonts` might make more sense than something KOReader-specific.

**Comment by pazos** [comment]
> That one's somewhat legacy, but standard locations like /usr/share/fonts, /usr/local/share/fonts, ~/.fonts and ~/.local/share/fonts might make more sense than something KOReader-specific.

Cool. In both debian and appimage makes sense to have EXT_FONT_DIR to some path writable by current user since the internal fonts used by KOReader are placed in a non-writable folder by default.

Users that don't use ~/.local/share/fonts can do a symlink to /usr/share/fonts to repurpose system fonts.

So, my idea:

`EXT_FONT_DIR=$HOME/.local/share/fonts`
on start script: `mkdir -p $EXT_FONT_DIR`

somewhere:

```
if Device:isLinuxDestop() then
    someplace.some_menu = {
        text = _("open font dir"),
        callback = function()
            os.system("xdg-open "..os.getenv("HOME").. "/.local/share/fonts")
        end
    }
end
```

Ideas?

**Comment by Frenzie** [comment]
Above the available fonts, similar to style tweaks?

![Screenshot_20190817_084402](https://user-images.githubusercontent.com/202757/63207718-3c0eae80-c0cb-11e9-8e01-30e46549f758.png)
