### ISSUE TITLE
Function: Add to favorites or collections

### ISSUE THREAD

**Issue by mayabtlaloc** [koreader/koreader#5099]
* KOReader version: KOReader 2019.06 "Sea Buckthorn"
* Device: Kobo Aura One

It can already be implemented the function Add to favorites or collections?
Thanks.

**Comment by NiLuJe** [comment]
What collections? What favorites?

**Comment by mayabtlaloc** [comment]
I mean the possibility of saving the books that you are reading or the books that you like in a list of favorites.
Something similar to the function that The kobo reader has to add to collections
attached image:
![20190626_152917-444](https://user-images.githubusercontent.com/2880036/60213516-4928c300-9829-11e9-91bf-3cfa3ae3d5a8.jpg)

In the case of the koreader it would be more or less like this:
attached image:
![20190626_155050-555](https://user-images.githubusercontent.com/2880036/60215062-79be2c00-982c-11e9-9584-0f25eab35185.jpg)

**Comment by pazos** [comment]
# huge offtopic 

@mayabtlaloc: Veo que estas con libros de psicología a vueltas. No si es puro interés personal o eres unha persona en formación o ya una profesional. En todo caso no dudes en consultar los libros de divulgación de Paul Watzlawick, como *el arte de amargarse la vida* o *cambio*

Considero que su obra magna **teoría de la comunicación humana** debería ser leída por toda persona, con independencia de su formación o sus gustos personales.

Un saludo!

**Comment by mayabtlaloc** [comment]
Gracias, Sí, me apasionan los temas sobre desarrollo humano tomaré en cuenta tus sugerencias
