### ISSUE TITLE
Gyro enhancement

### ISSUE THREAD

**Issue by sopincariu** [koreader/koreader#5106]
* KOReader version:
* Device:Kobo Forma

#### Issue
We can only turn on or off the accelerometer  events. It should be useful if we can lock in a certain certain orientation (portrait or landscape).
Thanks

**Comment by pazos** [comment]
If you disable sensor events you can get your desired orientation per document. Just use the bottom menu, rotation -> landscape/portrait (press twice for 180º rotation). 

AFAIK the file manager will always be in portrait

**Comment by NiLuJe** [comment]
c.f., comments in the relevant bits of frontend/device/input.lua

I don't have any specific interest in tweaking that, but it's there for the taking for interested parties.

**Comment by wildertux** [comment]
KOReader version 2019.10
DEVICE Acer Iconia Tab 10 (A3a50)

KoReader and inbuild File Manger starts with wrong Orientation (is upside down).
a config option for this would be nice.
and/or a Help info for 180° toggle.

**Comment by Frenzie** [comment]
Is that an Android device? Either way it's wholly unrelated to this Kobo Forma issue. ;-)

You can rotate 180° in landscape and portrait by tapping a second time on the rotation in the bottom menu.

**Comment by NiLuJe** [comment]
(Orientation lock not yet implemented, re-opening ;)).
