### ISSUE TITLE
FR: PocketBook frontlight warmth + gestures

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#5116]
Device: Pocketbook Touch HD 3
Version: v2019.06-23

The Touch HD 3 has a frontlight with adjustable light temperature. Sliding in left side up/down to increase/decrease light and sliding in right side up/down to change light temperature (for devices that support this feature) both work on the original reader software and on CoolReader (https://github.com/blchinezu/pocketbook-coolreader), but not in KOReader.

When I try sliding with two fingers it works very slowly and is often interpreted as increasing font size.

**Comment by NiLuJe** [comment]
We have no notion of how warmth should be handled on PB, so, yeah, this wo'nt wokr until a developer with the device on hand looks into it.

None of the currently active maintainers have ever even *held* a PB device, so ;).

**Comment by LucyOne** [comment]
Oh, that's too bad. KOReader has grown on me, now that it works fine on the Touch HD 3.

**Comment by tob1az** [comment]
@LucyOne I guess this could be implemented with GetFrontlightColor/SetFrontlightColor API from libinkview.so .

**Comment by NiLuJe** [comment]
Yep, that's one advantage of PB, InkView often exposes it ;).

We probably already have a few bits and bobs that access it via ffi, if someone were to look for inspiration.

**Comment by Frenzie** [comment]
It's present in both of the device abstraction files:

https://github.com/koreader/koreader/blob/bea7ca7008f113ad83ca82db71b3db80636ecbf5/frontend/device/pocketbook/device.lua
https://github.com/koreader/koreader/blob/bea7ca7008f113ad83ca82db71b3db80636ecbf5/frontend/device/pocketbook/powerd.lua

So if libinkview exposes a sensible API, it could theoretically be quite simple to implement.

**Comment by LucyOne** [comment]
At least, or rather additionally, it would be good to have the possibility to adjust the frontlight temperature via a menu, like frontlight intensity.
