### ISSUE TITLE
OPDS Search

### ISSUE THREAD

**Issue by captn3m0** [koreader/koreader#5119]
* KOReader version: 2019.07
* Device: Kindle PW4

#### Issue

OPDS Catalogs are not searchable

#### Steps to reproduce

Similar to #2442, but across all OPDS catalogs, not necessarily just Calibre.

A simple searchable public OPDS server that can be used for testing is `opds://www.feedbooks.com/catalog.atom`

**Comment by Frenzie** [comment]
#2442 isn't related to OPDS.

https://catalog.feedbooks.com/catalog/index.atom says this about search:

```xml
<link rel="search" href="https://catalog.feedbooks.com/opensearch.xml" type="application/opensearchdescription+xml" title="Search on Feedbooks"/>
```

The code seems to contain some stuff to deal with that, but presumably only if it's within an `<entry></entry>` element.

https://github.com/koreader/koreader/blob/642aed240ccb1f3aa6473c6411edd5de5fdf3189/frontend/ui/widget/opdsbrowser.lua#L42

https://github.com/koreader/koreader/blob/642aed240ccb1f3aa6473c6411edd5de5fdf3189/frontend/ui/widget/opdsbrowser.lua#L369-L377

**Comment by Dinth** [comment]
Would love to see this feature too.

**Comment by hius07** [comment]
Close the issue? https://github.com/koreader/koreader/pull/5823

**Comment by captn3m0** [comment]
The current implementation doesn't implement the OPDS search specification. I need to create 2 entries for every OPDS catalog to use this.

Should this remain open?
