### ISSUE TITLE
It is not work on deepinlinux 15.10.2

### ISSUE THREAD

**Issue by wunianyoung** [koreader/koreader#5122]
* KOReader version:
* Device:

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.
            launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 07/18/19-14:37:14
 [*] Version: v2019.07

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so
ffi.load: SDL
ffi.load (warning): libSDL.so: cannot open shared object file: No such file or directory
SDL not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: SDL
./luajit: frontend/device.lua:45: Could not find hardware abstraction for this platform. If you are trying to run the emulator, please ensure SDL is installed.
stack traceback:
	[C]: in function 'error'
	frontend/device.lua:45: in function 'probeDevice'
	frontend/device.lua:48: in main chunk
	[C]: in function 'require'
	./reader.lua:55: in main chunk
	[C]: at 0x00404f60

**Comment by Frenzie** [comment]
With which package is that?

**Comment by wunianyoung** [comment]
deb amd
| |
国光
|
|
邮箱：yangguoguang110@163.com
|
On 07/18/2019 14:46, Frans de Jonge wrote:

With which package is that?

**Comment by Frenzie** [comment]
Random note: you can actually boot this Deepin as a LiveCD. Just press <kbd>Tab</kbd> where it wants you to install and remove the installer part from the line (and probably change locale to something like `en_US` unless you speak Chinese).

Anyway, it's either a slight mistake in https://github.com/koreader/koreader-base/pull/873 or an additional name to add (`libSDL2-2.0.so.0`).

**Comment by wunianyoung** [comment]
okay




| |
国光
|
|
邮箱：yangguoguang110@163.com
|
On 07/18/2019 16:42, Frans de Jonge wrote:

Random note: you can actually boot this Deepin as a LiveCD. Just press Tab where it wants you to install and remove the installer part from the line (and probably change locale to something like en_US unless you speak Chinese).

Anyway, it's either a slight mistake in koreader/koreader-base#873 or an additional name to add (libSDL2-2.0.so.0).
