### ISSUE TITLE
Bug?  OTA updates from stable version to most stable version fails on Kindle pw 4

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5130]
I have tried updating several times.  All previous updates worked fine but this time.   What should I do differently?  Do a manual upgrade?  I don't want to overwrite the whole Koreader folder as I have different config files like wallabag etc

**Comment by NiLuJe** [comment]
Define "fail"?

**Comment by arooni** [comment]
from crash.log

```GET https://sync.koreader.rocks:443/syncs/progress/6fcd500e979b174e5759b0e25885620e
temporary failure in name resolution
failed to retrieve from http://ota.koreader.rocks:80/koreader-kindlepw2-arm-kindlepw2-linux-gnueabi-v2019.07.targz
Not all of the required data could be downloaded, and the remaining data could not be retrieved from any of the download URLs. Incomplete transfer left in ./o
ta/koreader.updated.tar.part.
(If this is the download filename with .part appended, zsync will automatically pick this up and reuse the data it has already done if you retry in this dir.)
```

**Comment by arooni** [comment]
![image](https://user-images.githubusercontent.com/556667/61598558-80e71880-abe5-11e9-99b3-62d991369449.png)

**Comment by arooni** [comment]
well hitting retry worked this time.  had tried various updates prior and ailed when i got here ; so i'm sure the moment i decide to post a bug report is the moment it fixed everything ;)

**Comment by NiLuJe** [comment]
`temporary failure in name resolution` feels like a local network issue ;). Or a Kindle going wonky ;).

Note that, even when everything's okay on your end, this *can* sometimes happen, because zsync ;p.

The "Retry" option should *always* work, though (barring actual network issues).
