### ISSUE TITLE
send2ebook problems

### ISSUE THREAD

**Issue by HoanPiTa** [koreader/koreader#5132]
* KOReader version:2019.07
* Device:kindle pp3 5.9.6.1

#### Steps to reproduce
i use some ftp server on android but i can access through send2reciver. it notice" could not get file list for server ftp:192......"

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
"Some FTP server"? :-) It might be useful to mention which one. There are no issues through a desktop client?

**Comment by Frenzie** [comment]
The plugin has been deprecated. Cf. https://github.com/koreader/koreader/pull/7967
