### ISSUE TITLE
FR: Highlighting with keyboard controls

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#5133]
* KOReader version: v2019.07
* Device: all with keyboard

#### Issue
This one's a bit niche but it used to be possible.

> In "KindlePDFViewer/Librerator", I can enter highlighting mode by pressing "n". The cursor then will occur in front of the first letter. The cursor can be moved word-by-word to other position using the five-way-controller (joystick). Highlighting will start by pressing the middle button of the five-way-controller. It also end by another pressing of this middle button. To exit highlighting mode, I press "n" again. To show all highlights, I press "shift+n". 

Requested by DeKuns, see https://www.mobileread.com/forums/showthread.php?p=3869732#post3869732

Relevant KindlePDFViewer code:

https://github.com/koreader/kindlepdfviewer/blob/c5beab2ded22d6bd480604c2bb87f3479d4b3b85/unireader.lua#L393-L912

**Comment by richo67** [comment]
@Frenzie I found this and wonder, can highlighting be done by mouse? I am running 2019.08 on ubuntu under the Windows10 with X11 Server. I can do all with mouse,  but no highlighting.

**Comment by Frenzie** [comment]
@richo67 Just hold the button pressed for a little while, same as you would with your finger. The UI was originally created for Kindle/Kobo.

**Comment by richo67** [comment]
> @richo67 Just hold the button pressed for a little while, same as you would with your finger. The UI was originally created for Kindle/Kobo.

@Frenzie thank you. And please excuse me, I should know this. Works very well!

**Comment by poire-z** [comment]
Cross-ref: #4329

**Comment by poire-z** [comment]
Fixed by #8877.
