### ISSUE TITLE
Android: current input limitations.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5136]
This is a kind of meta-issue on android related with how we handle input events.

<details>
<summary>
<b>original issue, obsolete because it was fixed</b>
</summary>
<p>

1. We set ALooper and poll all input events, generating compatible events which are dispatched by the frontend input handler based on type (motion | key events). See: https://github.com/koreader/koreader-base/blob/master/ffi/input_android.lua#L123-L137

2. In the specific case of key events we react only if the keycode is known to us. See https://github.com/koreader/koreader/blob/master/frontend/device/input.lua#L305 and https://github.com/koreader/koreader/blob/master/frontend/device/android/event_map.lua

If the keycode is not mapped then we just ignore its events. On current implementation the event is consumed and thus not forwarded to the system (ie: volume/media keys never trigger its function even if we remove them from the event map). The specific code that consume the event is in https://github.com/koreader/koreader-base/blob/master/ffi/input_android.lua#L133

1 means the event is consumed. 0 means the event is not consumed and available to the system.

And here start our potential problems:

1. While most part of the NativeActivity framework can be overloaded from java this doesn't apply to input events. They're processed by native code first and, if not consumed, they will trigger java callbacks later.
2. Unkown keycodes are consumed even when they do nothing on KOReader. This is particularly painful for playback media keys (next/previous and play/pause)
3. For most key events current behaviour works fine (ie: the back button key event won't close the activity as it is consumed before reaching onKeyUp). In some cases this can lead to unwanted scenarios:

Blocks #1760 
Blocks #3374
Makes #3978 harder to implement. (ie: instead of overriding onKeyUp for AKEYCODE.CAMERA events and toggle a boolean field "ignore_touchscreen" , and override onTouch to ignore motion events if ignore_touchscreen = true we might need to implement this logic on the frontend event handler as a input hook)

</p>
</details>

**to-do:**

Original issue  might be still applicable to #4671 for certain keys.
 #2241 is far beyond my interest (and my actual knowledge) but seems that keys are predispatched by the IME and thus consumed before reaching our motion/key event handlers.

While I won't spend too much time trying to fixing these issues since I'm not affected and they're not fun to work with, I'm more than happy to test suggestions and/or help people willing to spend time on this meta-issue.

**Comment by pazos** [comment]
Ok, I made a quick test to forward media keys to the system. It works well (if we remove volume keys from the event_map since they're mapped to page_fwd/page_back). Events finally reach the media server and volume/media controls work fine.

### luajit-launcher diff

```diff
diff --git a/assets/android.lua b/assets/android.lua
index b57bea1..6eac8cd 100644
--- a/assets/android.lua
+++ b/assets/android.lua
@@ -215,6 +215,17 @@ enum {
     AINPUT_MOTION_RANGE_ORIENTATION = 8,
 };
 
+enum {
+    AKEYCODE_VOLUME_UP = 24,
+    AKEYCODE_VOLUME_DOWN = 25,
+    AKEYCODE_MEDIA_PLAY_PAUSE = 85,
+    AKEYCODE_MEDIA_STOP = 86,
+    AKEYCODE_MEDIA_NEXT = 87,
+    AKEYCODE_MEDIA_PREVIOUS = 88,
+    AKEYCODE_MEDIA_REWIND = 89,
+    AKEYCODE_MEDIA_FAST_FORWARD = 90,
+};
+
 int32_t AInputEvent_getType(const AInputEvent* event);
 int32_t AInputEvent_getDeviceId(const AInputEvent* event);
 int32_t AInputEvent_getSource(const AInputEvent* event);
```

### base diff

```diff
diff --git a/ffi/input_android.lua b/ffi/input_android.lua
index 29b18e4..d4fcf36 100644
--- a/ffi/input_android.lua
+++ b/ffi/input_android.lua
@@ -90,11 +90,27 @@ end
 local function keyEventHandler(key_event)
     local code = android.lib.AKeyEvent_getKeyCode(key_event)
     local action = android.lib.AKeyEvent_getAction(key_event)
+    local event_consumed = 1
+
+    -- do not consume media keys
+    if code == C.AKEYCODE_VOLUME_UP
+    or code == C.AKEYCODE_VOLUME_DOWN
+    or code == C.AKEYCODE_MEDIA_PLAY_PAUSE
+    or code == C.AKEYCODE_MEDIA_STOP
+    or code == C.AKEYCODE_MEDIA_NEXT
+    or code == C.AKEYCODE_MEDIA_PREVIOUS
+    or code == C.AKEYCODE_MEDIA_REWIND
+    or code == C.AKEYCODE_MEDIA_FAST_FORWARD then
+        event_consumed = 0
+    end
+
     if action == C.AKEY_EVENT_ACTION_DOWN then
         genEmuEvent(C.EV_KEY, code, 1)
     elseif action == C.AKEY_EVENT_ACTION_UP then
         genEmuEvent(C.EV_KEY, code, 0)
     end
+
+    return event_consumed
 end
 
 local function commandHandler(code, value)
@@ -125,12 +141,13 @@ function input.waitForEvent(usecs)
                     while android.lib.AInputQueue_getEvent(android.app.inputQueue, event) >= 0 do
                         if android.lib.AInputQueue_preDispatchEvent(android.app.inputQueue, event[0]) == 0 then
                             local event_type = android.lib.AInputEvent_getType(event[0])
+                            local handled = 1
                             if event_type == C.AINPUT_EVENT_TYPE_MOTION then
                                 motionEventHandler(event[0])
                             elseif event_type == C.AINPUT_EVENT_TYPE_KEY then
-                                keyEventHandler(event[0])
+                                handled = keyEventHandler(event[0])
                             end
-                            android.lib.AInputQueue_finishEvent(android.app.inputQueue, event[0], 1)
+                            android.lib.AInputQueue_finishEvent(android.app.inputQueue, event[0], handled)
                         end
                     end
                 end
```

This example is quite hardcoded and I'm not sure how to make it dynamic based on user preferences, since the files involved are in three different repos.

**Comment by Frenzie** [comment]
I'd say it doesn't matter much for starters. Configurability is mostly non-existent anyway, and when you've got a more hardcoded example it's easier to expand on it in the future.

**Comment by pazos** [comment]
> I'd say it doesn't matter much for starters. Configurability is mostly non-existent anyway, and when you've got a more hardcoded example it's easier to expand on it in the future.

For media keys I think it is safe to ignore them on KOReader but for volume keys having a switch to use them as page turn keys seems the right thing to do. I think I can interface ffi/input_android.lua with the android FFI/JNI directly without touching the frontend. Lets see.

**Comment by pazos** [comment]
Works fine:

![untitled](https://user-images.githubusercontent.com/975883/62228998-0ffee800-b3bf-11e9-86c1-20eece75832d.gif)

**Comment by Frenzie** [comment]
Sure, makes sense. :-)

Btw, how'd you record that. An option in the emulator somewhere? (Not on my PC atm.)

**Comment by pazos** [comment]
> Btw, how'd you record that. An option in the emulator somewhere?

Yeah, the emulator has an option called "Record and Playback" on the three dots menu. You can do the same with a real 4.4+ device with `adb shell screenrecord /sdcard/video.mp4`

**Comment by Frenzie** [comment]
> You can do the same with a real 4.4+ device with adb shell screenrecord /sdcard/video.mp4

Excellent! :-)

**Comment by pazos** [comment]
External keyboard: Superseeded by #5902
Alternative virtual keyboards: See original issue #2241

The rest was fixed. Closing
