### ISSUE TITLE
manual dictionary search from dict window

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#5137]
Currently, when looking up an word in the dictionary, there is a 'search' option, but this simply searches for the same text in the book.

Wouldn't it be more useful to have that button allow a manual dictionary search, to e.g. correct a spelling mistake in the book, or to look up part of a compound word?

Alternatively, this could be a separate button.

**Comment by Frenzie** [comment]
Try holding on the window title. ;-)

**Comment by pbienst** [comment]
Good to know, but not very discoverable :-)
