### ISSUE TITLE
[question] Restart KOReader after update

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#5144]
I want to add option to restart KOReader immediately after update. Now after update we have message:
![obraz](https://user-images.githubusercontent.com/22982594/61864920-a0768d80-aed2-11e9-8f14-8b79d04ffec5.png)
and we need manualy restart (Exit menu -> Exit -> Restart KOReader).
I want to change infomessage to confirmbox with option to restart:
![obraz](https://user-images.githubusercontent.com/22982594/61864886-90f74480-aed2-11e9-9e78-db0f0ad7a4f2.png)

Is there any method to run `ReaderMenu:exitOrRestart(callback)`
here:
https://github.com/koreader/koreader/blob/1f6af80817bd9ce55201555817d4ce5e7f8f319c/frontend/ui/otamanager.lua#L254-L256 in `OTAManager:fetchAndProcessUpdate()`?

**Comment by robert00s** [comment]
Ok, I think I found solution. I'll try to use that code:

https://github.com/koreader/koreader/blob/1f6af80817bd9ce55201555817d4ce5e7f8f319c/frontend/device/input.lua#L355-L379

**Comment by NiLuJe** [comment]
Does something like what readergesture.lua does would work?

(i.e., `self.ui.menu:exitOrRestart(function() UIManager:restartKOReader() end)`)

**Comment by robert00s** [comment]
Unfortunately not.
OTAUpdate doesn't know self.ui.menu

**Comment by robert00s** [comment]
But "my" solution works great (tested on Kindle) :)
