### ISSUE TITLE
File manager - ability to change drive

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#5154]
I'm not really sure is latest version has this ability as I'm at the moment at pretty old version of koreader, but here's the story:

For some reason, when I tried to view one image within ebook, I entered "twilight zone". Everything slowed down, and, somehow, I couldn't exit image and restart koreader in normal way. I had really strange experience, where I had light on and message that device is suspended at the same time, which could be changed into no message, but no light also. And, image viewer was unresponsive.

I know, s--- can happen, so I went for restart, long press of power (I have Kobo Aura One, otherwise I would go for reset button on my H2O). And, here story begins.

After restart, all settings were deleted, probably crash was culprit. But, also, for some reason, I was on wrong side of devices memory, seeing system files, not user files (i.e. wrong partition, or disk, or however is it correctly called).

Anyway, I couldn't find way out of it to my user partition. I don't know if there's option for that, for changing partition.

I had luck, in history, somehow, info about last book was retained, so I found way out, but, it would be great if there is way (if there's not already) to change partition, in case something like this happen to unsuspecting users.

**Comment by NiLuJe** [comment]
The user partition is mounted at `/mnt/onboard` on Kobo.

Anyone can cd out of it, even in perfectly normal situations, the FM isn't sandboxed ;).

**Comment by Frenzie** [comment]
I think this is fairly thoroughly covered by the home button and folder favorites. That's no help if the settings were somehow lost, I suppose. In that case you'd be forced to navigate to `/mnt/something-or-other` manually, but it should always be reachable.

**Comment by AlanSP1** [comment]
Yes, that's something I realized later, after first shock of seeing some strange "unix" directories, with which I'm unfamiliar, as I usually see only user partition (or whatever it is).

Now I know that I should go to mount directory as @NiLuJe mentioned, but at first shock, average user can really be totally lost. Not sure if something can be done in similar case where everything is lost of settings.

Is there maybe some option to check for settings, if they are lost, to check if there's settings backup somewhere. I mean, I know that at the moment there's no that option, but if it can be programmed?

**Comment by NiLuJe** [comment]
Like @Frenzie mentioned, the Home icon will zap you back to your Home, which *should* be set to the user(s preference, as that's the gist of the Quickstart Guide shown on first boot.

**Comment by AlanSP1** [comment]
Hm, I think (not 100% sure, I was bit shocked at that moment) that when I touched home icon, it asked me to set current dir as home dir.

So, when settings are erased for some reason, it maybe don't work this way. Maybe if you test if, if you know how, to see what I experienced. It was a bit stressful, now I know there's no reason, but I was a bit panicky at the time.

**Comment by NiLuJe** [comment]
Ah, of course, if the settings are gone, then there's no home ;p.

It could probably use a platform-specific fallback, but then that makes the UX slightly trickier when it's unset, because we still have to assume someone might want to be setting a Home, rather than using the fallback value.

**Comment by AlanSP1** [comment]
I think this solves this problem and it would make life easier in case of disaster like I had. So I close this.
