### ISSUE TITLE
[UX] Up button in touch menu is too small

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#5155]
I would like to extend the touch zone for up button in touch menu. Now it is to small for me.
Red rectangle is touch zone.
![obraz](https://user-images.githubusercontent.com/22982594/62210731-2431ed80-b39d-11e9-9803-4a3934ee1f7c.png)

Three option:

1. Extend a bit + move button.
![obraz](https://user-images.githubusercontent.com/22982594/62210899-8985de80-b39d-11e9-8bc4-3c84531b5758.png)

2. Extend a lot + don't move button.
![obraz](https://user-images.githubusercontent.com/22982594/62210829-5c393080-b39d-11e9-856d-f89d3fc3957b.png)
3. We don't change that.

**Comment by Frenzie** [comment]
I suppose being slightly larger (like in 1) would be best given this particular design, but I'd like to change how it's presented. @baskerville made a nice mockup of what it should more or less look like: https://github.com/koreader/koreader/issues/2615#issuecomment-290021189

![menu](https://user-images.githubusercontent.com/202757/62215802-e5edfb80-b3a7-11e9-81f1-7724183723b5.png)

The title at the top there is the menu name (like "Style" or "Style tweaks").

**Comment by robert00s** [comment]
Maybe someday I'll try to change touch menu like in that mockup.
