### ISSUE TITLE
Strange default in paged media: fit to page + scroll mode

### ISSUE THREAD

**Issue by q3cpma** [koreader/koreader#5166]
Hello

* KOReader version: 2019.07
* Device: Kobo Aura HD

#### Issue
When reading PDFs, navigation pans the pages for no reason.
#### Steps to reproduce
1) Turn 2 pages, no problem
2) Go back 2 pages, you get panning toward to bottom each time
3) Go back 1 page more, to return to the first page with correct layout
4) Turn 2 pages, you get panning toward to top each time
The interesting point is that it only happens with PDFs (EPUBs and CBTs work fine) and that if I set the "Zoom mode" to "fit page" between 3) and 4), I go back to 1) (no problem while going forward).
Note that the "Zoom mode" was already set to "fit page", I just clicked on the ticked box.

Example faulty pdf: https://9p.io/sys/doc/9.pdf
I'll upload my koreader directory if nobody can reproduce.

By the way, an option to disable panning gestures would be extra nice.

**Comment by Frenzie** [comment]
What exactly do you mean by "you get panning toward the bottom"?

**Comment by q3cpma** [comment]
I was wrong, it's not setting the zoom mode that resets the loop, touching the top left to get the little book icon does too (but the top right folded corner does not).

**Comment by q3cpma** [comment]
Panning toward the bottom: the top of the page is cut and I see the interpage gray then the end of the previous page

**Comment by Frenzie** [comment]
Are you using zoom to fit page in combination with scroll mode?

**Comment by q3cpma** [comment]
I didn't change anything (deleted my .apps/koreader then copied the one from the zip) from the defaults. No idea what the "scroll mode" is, sorry.

**Comment by q3cpma** [comment]
Disabling scroll mode by editing defaults.lua worked but I can't find the option in the menus and https://github.com/koreader/koreader/wiki/Change-defaults is wrong, the default is 1 (I looked in the release zip). And even if this "solved" it, I wonder why the problem was there anyway.

**Comment by q3cpma** [comment]
Sorry for being daft, finally found it on the bottom menu.

**Comment by Frenzie** [comment]
Scroll mode can be toggled in the bottom menu. It was made the default in <https://github.com/koreader/koreader/pull/2160>.

Perhaps zoom to page could (prompt to) turn off scroll mode. It's just that something like zoom to content or page width in combination with scroll mode by and large makes for a better experience than zoom to page.

**Comment by q3cpma** [comment]
Don't see how it's better, but that's not the proper place to discuss that. Your prompt suggestion is a good one and should also apply to "fit to content".
But there's still a bug here, right? Scroll mode shouldn't produce this with page turning.

**Comment by Frenzie** [comment]
But it should, because it's scroll mode. There's an overlap with a value that will generally make it so that you would just ignore cut-off lines.

![Screenshot_2019-08-02_14-14-15](https://user-images.githubusercontent.com/202757/62369424-e1544f00-b52f-11e9-88b5-6262df91ea99.png)
![Screenshot_2019-08-02_14-14-22](https://user-images.githubusercontent.com/202757/62369425-e1544f00-b52f-11e9-8326-de363acd955a.png)

Perhaps the overlap could be automatically disabled in conjunction with fit to content/page but the principle is definitely by design.

The value can be adjusted to personal preference:

https://github.com/koreader/koreader/blob/e2961097e7b054d97928b6d188353335372b0db6/defaults.lua#L58-L59

**Comment by q3cpma** [comment]
Oh, I see. This is not intuitive at all, at least for me. Perhaps a configuration wizard for first install should take care of these important choices.

**Comment by Frenzie** [comment]
It's less of a choice than something that's dictated by the document in question. However, the combination of scroll mode with zoom to fit page makes for an odd default. That should probably be fit to page width, although I'd prefer content width. Alternatively it should be zoom to fit page with scroll mode off.

**Comment by q3cpma** [comment]
Well, I think not making scroll mode the default is better simply because
that's how it is on the vendor reader. It can be especially confusing when the
document ratio matches the screen ratio (and when you can't find the bottom
menu, heh; a mention in the opening readme about the diverse menus would be
nice).

**Comment by NiLuJe** [comment]
To be honest, I find the whole zoom/scroll/pan setup exceedingly confusing in the PDF reader, and some combinations do result in extremely odd behavior.

**Comment by Frenzie** [comment]
@q3cpma At the same time the default in Firefox, Chromia, Evince, Okular, MuPDF, etc. is page width + scroll mode. ;-)

The bottom menu automatically shows up together with the top menu. Back in 2014 I thought it was a pretty intuitive way of doing it.

@NiLuJe The basic problem is that while an example such as zoom to page + scroll mode doesn't make much sense for your average "just reading along" use case, the possibilities offered by scroll mode may very well still make sense. For example, to stick a full paragraph on the screen all at once without it being split up.

![Screenshot_2019-08-02_18-13-57](https://user-images.githubusercontent.com/202757/62383957-7287ed80-b551-11e9-9703-5d455b7135bc.png)

**Comment by q3cpma** [comment]
On Fri, Aug 02, 2019 at 09:46:27AM -0700, Frans de Jonge wrote:
> @q3cpma At the same time the default in Firefox, Chromia, Evince, Okular, MuPDF, etc. is page width + scroll mode. ;-)
But this on LCD, not E-ink where the lag is unbearable, especially if you want
to correct any scrolling over/undershoot.

Well, now that I solved this, it's not like I really want to continue this
crusade, but I think I won't be the only one to be confused by this silent
change.

**Comment by Frenzie** [comment]
Note that the issue I referenced was from over three years ago.

I normally never scroll. You might occasionally see the top of a line that's cut off, but that's what the overlap is for. You just ignore it and flip over to the next page.
