### ISSUE TITLE
Hold left corner in File browser not working properly

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5174]
* KOReader version: v2019.07-33-ge296109_2019-08-01
* Device: KA1

(Same problem for my Kobo Aura, v2019.04-2-g4005bf6_2019-04-08 and Android, v2019.05)

#### Issue
The 'Hold left corner' gesture in File browser is troublesome for me. I have to hold my finger a little bit to the right to make it work.

The other corner gestures are working fine (tap left corner in File browser, tap/hold left corner in Reader, tap/hold right corner in File browser/Reader).

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by Frenzie** [comment]
Sorry, never mind that (but feel free to fix it @robert00s ). I thought the issue was about #5156.

**Comment by robert00s** [comment]
I'll look at it
