### ISSUE TITLE
Blank pages on pdf (Kobo Clara HD)

### ISSUE THREAD

**Issue by pcfirebeats** [koreader/koreader#5182]
* KOReader version: 2019.07 (automatic installation)
* Device: Kobo Clara HD 

#### Issue

I cant read most of this pdf file. I open it like other pdf files, but it only shows the text of the first page, the rest of the pages are blank, It just shows the page number and author on top of the page. It happens both with reflow on and off. I can read this file normally in my PC

The file
http://www.philosophyatlisbon.org/userfiles/file/n_9/03_In%C3%AAs_Reis_2019.pdf 

Other pdfs open normally.
------------------

Thanks in advance

**Comment by Frenzie** [comment]
```
luajit: source/fitz/colorspace.c:1486: fast_rgb_to_cmyk: Assertion `"This should never happen" == NULL' failed.
Aborted
```

Upstream bug with a patch we could consider applying temporarily:

https://bugs.ghostscript.com/show_bug.cgi?id=698877

Finishing https://github.com/koreader/koreader-base/pull/762 won't make it go away; I don't think it's in upstream until 1.15.

**Comment by Frenzie** [comment]
@pcfirebeats Unfortunately updating to newer MuPDF is quite involved, but since I could backport this specific fix in a couple of minutes I decided to go ahead and do that.

**Comment by pcfirebeats** [comment]
I cant help with coding or such, but it seems it was been solved already for the next released.

That is great! Many Thanks!
