### ISSUE TITLE
Double finger up/down & horizontal left edge gestures

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5186]
* KOReader version: v2019.07-52-gaec112f_2019-08-06/
* Device: KA1

#### Issue
Double finger up/down does not work at all on my KA1 in portrait mode. However it seems to work in landscape. So I guess that is the opposite side of this problem:  #4843.

Horizontal left edge gesture gets in conflict with the other left swipe. I have 'Swipe to follow nearest link' enabled, so every time there is a link on the page my bottom/top left edge swipe follows that link instead.

**Comment by gerhaher** [comment]
And a possible rotation issue with horizontal edge gestures:

When rotating I end up 1 or 2 pages back. That's not happening when I rotate with the other gestures in Gesture manager.
 
I rotate counterclockwise (in case it's important to know).

**Comment by robert00s** [comment]
I'll try to prepare fixes. Thanks for reporting.

**Comment by robert00s** [comment]
@gerhaher 
Try the latest version v2019.07-58 (from today). All described problems should be solved.

**Comment by Frenzie** [comment]
@gerhaher Does the thumbs up mean it works? Just asking for the August release. :-)

**Comment by gerhaher** [comment]
> @gerhaher Does the thumbs up mean it works? Just asking for the August release. :-)

Yes, it seems to work.

**Comment by Frenzie** [comment]
Alright, closing then.
