### ISSUE TITLE
Show hidden files/dirs in file editor

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#5192]
I was trying to open a text file that was inside my ".Books" directory, but I could not find the folder.
Is there an option somewhere I can change? I could not find anything.
In the File Manager settings, the option to show hidden files is ON.

It faintly reminds me of a similar incident in the pass, but I can't pinpoint it..

**Comment by poire-z** [comment]
Possibly fixed by #5923 and a few previous other PRs where we made a few more things obey this setting.
