### ISSUE TITLE
ToC should show and expand current chapter

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#5194]
* KOReader version: all
* Device: all

When a book has chapters and sub-chapters, the ToC does not expand to show them all. Even when I am in a specific chapter, this is not shown and I have to expand the entry myself. It would be useful to at least know your place in the book.

I use KOReader on my Pocketbook devices.

**Comment by Frenzie** [comment]
I can't confirm. That's how it behaves?

I open a book at the beginning, the TOC is closed:
<img src=https://user-images.githubusercontent.com/202757/62821972-6fa68180-bb7d-11e9-9648-b6b7251b0766.png width=40%><img src=https://user-images.githubusercontent.com/202757/62821973-6fa68180-bb7d-11e9-8c97-12e20cc83658.png width=40%>

I go to somewhere much further in the book; the TOC is now automatically expanded:
<img src=https://user-images.githubusercontent.com/202757/62821975-6fa68180-bb7d-11e9-897b-b75b93c568c8.png width=40%><img src=https://user-images.githubusercontent.com/202757/62821976-703f1800-bb7d-11e9-9262-a0c430db5588.png width=40%>

**Comment by LucyOne** [comment]
I'm sorry, I didn't realise that it only happens in the book I'm currently reading (Blink by Malcolm Gladwell).

**Comment by Frenzie** [comment]
Likely a duplicate of #3062.

**Comment by poire-z** [comment]
@LucyOne : so, it happened really with one single book of yours?
Anything specific about that book? (Found a copy of that book somewhere that did not exhibit any problem, but it had only one TOC level - so you must have another edition.)

Anyway, a known reason for TOC to not update is when a same ID= is used multiple times, which would result in a TOC target resolving to different pages, and this messing the ordering. Or just the TOC being initially not ordered. See https://github.com/koreader/koreader/issues/3062#issuecomment-521273214.

Could you post a screenshot of what your TOC looks like (like mine there), so we see if the pages are ordered or not?

**Comment by LucyOne** [comment]
I looked at the ToC in Calibre, it seems to have unique IDs for each entry.
When opening the book in the last chapters "Notes" or "Conclusion", those were shown in bold. But when I switched to one of the other chapters, they weren't. In the screenshot I was in "2. Blink in Black and White".
![Reader_2019-Aug-14_165225](https://user-images.githubusercontent.com/15887012/63031585-7baf7d80-beb4-11e9-9836-e56cb225d55e.png)

**Comment by poire-z** [comment]
Thanks.
It's quite obvious on your screenshot that the first entry targets page 227, so you're meeting a subset of my bug. Our (buggy?) TOC code stops at the first item, because you're on a page before 227: the previous item stay highlighted, and none of the other gets expanded.

So, why does that `Cover` TOC item points to page 227? Is it really at the end of book? or some duplicated ID?
Would have to look at the EPUB spec if the NAV entries have to be ordered, or are allowed to not be.

**Comment by LucyOne** [comment]
Thanks for your help. Turns out that was the mistake in the ToC. The cover destination pointed to some random page. After I corrected it so it points to the first page, everything is shown correctly.
