### ISSUE TITLE
[Question] Work around way to launch Koreader without jailbreak

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#5196]
* KOReader version: any
* Device: kindle KW4 (shipped 5.10.3)
I've just received KW4 (shipped 5.10.3).I do know that there is no Jailbreak method for this firmware up to now.
My question is : Do we have any work around method to launch koreader on Kindle without jailbreak? 
As I like Koreader with all of its customed funtion.

**Comment by xianren78** [comment]
no

**Comment by NiLuJe** [comment]
Definitely not.
