### ISSUE TITLE
Ignore vs nothing, gesture manager confusion

### ISSUE THREAD

**Issue by kzshantonu** [koreader/koreader#5204]
What's the difference?

**Comment by NiLuJe** [comment]
My understanding is that "Nothing" will sink the touch event into oblivion, while "Ignore"  will let it propagate and do whatever the zone might already be doing (say, a page turn).

**Comment by Frenzie** [comment]
That's correct.

**Comment by Frenzie** [comment]
Terms like capture and propagate are too jargon; almost no one without the specific domain knowledge would understand what that means. Perhaps "pass through" instead of ignore?

**Comment by NiLuJe** [comment]
@Frenzie: I like it :)
