### ISSUE TITLE
Android: bug(s) in runtime permissions 

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5205]
* KOReader version: from 2019.07.
* Device: Android (api23+)

#### Issue

1. ~~If the user don't give write permission on the external storage the activity closes itself but the native thread is still on the background uncompressing assets, until it fails when it can't write to cache folder~~ **solved**

2. ~~If the user uninstalls the program but keeps /sdcard/koreader and had setup a custom timeout the next time the program is installed it will request the permission at launch (because it is stored on our own settings and restored every launch). It should request WRITE_SETTINGS just if the user does an explicit action (ie: changes screen brightness or screen timeout).~~ **solved**

3. Minor: the frontlight widget sets its new value before asking for permission.

**Comment by pazos** [comment]
Regarding:

> **Minor: the frontlight widget sets its new value before asking for permission**

I think we would want to avoid touching system-wide light settings and just modify the light of our activity. In this case we don't need to ask permissions and we don't force the user to manual light levels outside KOReader.

**Comment by Frenzie** [comment]
Fully on board with not messing with system-wide light settings. :-)

**Comment by pazos** [comment]
> Fully on board with not messing with system-wide light settings. :-)

Ok, I will implement this on top of https://github.com/koreader/android-luajit-launcher/pull/171 to avoid ugly casting.

AFAICT the in-activity brightness is [one way only](https://developer.android.com/reference/android/view/WindowManager.LayoutParams.html#screenBrightness) (set a float between 0.0 and 1.0 to use custom levels and anything lower than 0 to use system defaults), which means there isn't any way to retrieve current level of the activity (as it is expected to be equal to system brightness or managed/recorded by the activity).

**Comment by pazos** [comment]
Implemented in https://github.com/koreader/android-luajit-launcher/pull/171/commits/7fd77e930f3ee0fcd300c87eb831905346d3a03b.

I kept everything as it was. We get and set int values from MIN(0) to MAX(255). All these values are **custom** Any number below 0 will be treated as system defaults. For convenience  BRIGHTNESS_DEFAULT(-1) will be used if the user doesn't override this setting.

Note 1: we start with default level and we need set custom user level, if exists, during device initialization. Custom level will be used **only** for this app.

Note 2: once a custom level is set changing screen brightness from android settings won't change the value in KOReader.

**Comment by pazos** [comment]
And now my headache begins:

I spent a few minutes reading frontend/ui/widget/frontlightwidget.lua for the first time and I would need some help here.

I would want to add a checkbox and differenciate between system and custom settings. 
 
```lua
if android.getScreenTimeout() == -1 then
    -- use system settings, slider disabled and checkbox checked
else
    -- use custom settings, slider enabled and checkbox unchecked
end
```

**Comment by Frenzie** [comment]
@pazos I don't know, did @robert00s write it? You'd have to check git blame.

**Comment by robert00s** [comment]
@pazos 
I can help. Where do you want to put checkbox?

**Comment by pazos** [comment]
@robert00s: not sure exactly where it makes sense, but for now something like:

![Sin nombre](https://user-images.githubusercontent.com/975883/64079493-5611d900-cce8-11e9-9fec-6b1b45f3faa6.png) could be fine.

I'm not sure if add the checkbox logic only if `Device:isAndroid()` or add something new like `Device:hasLightLevelFallback()` which is only true on Android.

**Comment by robert00s** [comment]
@pazos Done in #5307
