### ISSUE TITLE
Books are not refreshed in Nickel after import via koreader

### ISSUE THREAD

**Issue by vincowl** [koreader/koreader#5212]
* KOReader version: 2019.08
* Device: Kobo Glo HD

Having added new books via an OPDS catalog using a wireless connection, books can be correctly read from koreader. But rebooting to Nickel, books library are not updated in Nickel. How can we refresh the books database without a USB connection / deconnection ?

**Comment by KenMaltby** [comment]
The "Exit" options include a option to "Reboot the device" .  If the ebook file/s in question are not in a "hidden" folder (one that starts with a dot/period) Nickel should see them.

**Comment by vincowl** [comment]
Indeed, the device reboots while exiting koreader, but nickel doesn't see my "downloaded" folder, and sadly, "downloaded" is obviously not hidden.

**Comment by pazos** [comment]
@vincowl: **https://www.mobileread.com/forums/showpost.php?p=3876016&postcount=2**

Keep in mind that github is a very bad place to ask these kind of (not so slightly) unrelated questions. The mobileread forum is way better. Now because someone asked that before and was anwsered I can avoid the effort to write the same again and I can put a link here.

Please consider asking questions there (if they're related to KOReader) or on [kobo the forum](https://www.mobileread.com/forums/forumdisplay.php?f=223) if they're entitled to your workflow with one particular device.

**Comment by NiLuJe** [comment]
The short answer is: you can't.

The long answer is: you can *fake* a USB connection (`echo "usb plug add" >| /tmp/nickel-hardware-status`), but doing that without an actual connection is slightly non-trivial, so you're pretty much back to square one.

(c.f., https://github.com/shermp/Kobo-UNCaGED for a working implementation of such a non-trivial, wireless fake USB session).

**Comment by NiLuJe** [comment]
And, to expand on @pazos's answer: I don't *think* an actual cold reboot helps (IIRC, so you might want to try it anyway).

**Comment by vincowl** [comment]
@pazos I don't think this is unrelated to a potential "bug" or a potential future feature : it lays on kfmon and the responsability of the database's update is not clearly described between kfmon and koreader. To me it should be handled by koreader since kfmon could be used to totaly different kinds of services. I don't see why it is not an actual feature since koreader is not defined as a replacement to nickel but as a product that can be easily switched to thanks to kfmon. So these two products should "communicate" easlly and share the minimum requirements which is the books database to me. It is indeed clearly explain how to avoid nickel to parse the data folder structure thanks to hidden folders. So it seems totally logical to me to assess that database is completely shared using non hidden folders. 
Thanks for the explaination on the "reboot" term meaning. I better understand the other comments.

@NiLuJe Thanks for the technical infos. I'll have a look at the link you gave

**Comment by NiLuJe** [comment]
Nickel is killed by KOReader, for good reason.

There's absolutely zero chance this could ever get handled from within KOReader.

**Comment by NiLuJe** [comment]
Do double-check that a proper restart doesn't do the job, but I seem to remember it not being the case, as that was a salient difference with a Kindle (they enforce a catalog check at boot).

**Comment by vincowl** [comment]
@NiLuJe I confirm that a proper restart doesn't do the job
