### ISSUE TITLE
[Discussion]: Simplify the README

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5213]
Please compare our readme with the [one in Calibre](https://github.com/kovidgoyal/calibre).

Both are programs where the 99'99% of the users will want to download a form of package to install in their devices.

Right now the TOC is:

Intro
===

Main features for users
-----------------------
Highlights for developers
--------------------------
Building Prerequisites
======================
Getting the source
==================
Building, Running and Testing
=============================
Translation
===========
Use ccache
==========
Footer
=====

All the information seem relevant to me (as one of the 0.01% of users that want to build from source) but makes the README very messy. I would go for moving *prerrequisites, getting the source, building/running/testing and use ccache* to a separate document and focus on final users on the front README.

Things that are important for final users: where to **download**, how to **install**, how to **contribute/support** KOReader, etc. I'm not talking about adding redundant information that is actually on the wiki but leave a lean front page with a few links that most people would find interesting.

**Comment by Frenzie** [comment]
Please! :-)

**Comment by AlanSP1** [comment]
Sounds as good idea.

**Comment by pazos** [comment]
I started updating the wiki with pages for installation on Android and Desktop linux. Just edited a few things and added links accordly.
