### ISSUE TITLE
2 lines on the screen

### ISSUE THREAD

**Issue by theNizo** [koreader/koreader#5216]
* KOReader version: 2019.08
* Device: Android 9.0

#### Issue

You can see 2 black lines (grey in night mode) on the screen, which is pretty annoying. I've tried with 4 books. Two screenshots attached below

#### Steps to reproduce

1. Install KoReader 2019.08
2. Open an epub file

##### `crash.log` (if applicable)

Not applicable

#### Screenshots

![Screenshot_KOReader_20190816-150550](https://user-images.githubusercontent.com/38207294/63170061-b5a98c80-c038-11e9-8029-39b9cd273aac.png)

![Screenshot_KOReader_20190816-150554](https://user-images.githubusercontent.com/38207294/63170106-d5d94b80-c038-11e9-9511-cc0a01609ccd.png)

**Comment by NiLuJe** [comment]
That's the speed-reading plugin, IIRC. I don't righly recall how exactly it's called, though (perception something?).

**Comment by theNizo** [comment]
Should be Perception expander?
Anyways, I disabled it and the lines were gone.
Thanks for the fast answer.
