### ISSUE TITLE
Android/Amazon Fire OS slowdown after 2019.04

### ISSUE THREAD

**Issue by JPruente** [koreader/koreader#5221]
* KOReader version: 2019.05 and higher
* Device: Amazon Fire HD 8.9" (2012, Fire OS 8.5.1, Android 4.0.3 based), Amazon Fire HD 7 (2013, Fire OS 8.5.5.3, Android 4.4 based)

#### Issue

koreader release 2019.04 is snappy and overall works quite well on these devices. koreader release 2019.05 and higher, including the current 2019.08 release, seem to be quick at starting up and loading a PDF file and turning the page. Yet, the menu interface and the file browser are slow and lag significantly responding to input. I timed repeating the same actions in 2019.04 and 2019.05 and found significant lag on the slower Amazon Fire HD 8.9".

File browser speed:
* 2019.04 - page 2 load time < 1 sec, page 1 load time < 1 sec
* 2019.05 - page 2 load time ~15 secs, page 1 load time ~24 secs.

The other Fire device was noticeably slower as well but less obviously so, presumably due to faster hardware.

#### Steps to reproduce

Download 2019.04 release and 2019.05 release for Android ARM on to an older or low-end Android device. Install one at a time and time performing menu actions and loading file browser screens, esp. where the browser has a long list of file to draw previews and spans more than one screen.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Is the same trend noticeable on the Android 4.4 device?

**Comment by JPruente** [comment]
It is noticeable now that I give it more testing. I loaded more files on to the Fire HD 7 device to be more equivalent to the older Fire HD 8. That brought the load times of the file browser way up. On koreader 2019.05 it takes 2-3 seconds for the main menu to come up when in a document. Loading various pages of the file browser take a long while. The initial load time of the file browser depends on what page it is opening, and aligns to the time to open that page when flipping through them when already in it.

Fire HD 7 with koreader:

2019.04
* Main menu load time < 1 sec
* File browser page 1 load time < 1 sec
* File browser page 2 load time < 1 sec

2019.05
* Main menu load time 2-3 secs
* File browser page 1 load time ~8 secs
* File browser page 1 load time ~22 secs

**Comment by Frenzie** [comment]
> low-end Android device

My Xperia Ray is about twice as low end as that Kindle Fire tablet spec-wise, but it's speedier than my H2O.

https://en.wikipedia.org/wiki/Sony_Ericsson_Xperia_ray
https://www.gsmarena.com/amazon_kindle_fire_hd_8_9-4995.php

**Comment by pazos** [comment]
Thanks @JPruente for the detailed bug report!.

Bug triaged to https://github.com/koreader/koreader/commit/4515a360597c987f4675dc4312fd33b5ec712ea6 as already suggested [here](https://www.mobileread.com/forums/showpost.php?p=3861871&postcount=15) and [here](https://www.mobileread.com/forums/showpost.php?p=3878738&postcount=35).

It should work fine on your device (and others that have related problems) if you remove [L49-L52](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/MainActivity.java#L49-L52) and [L132-L140](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/MainActivity.java#L132-L140) from luajit launcher MainActivity.

The problem is that we cannot reproduce on non broken devices and, nowadays, epd support relies on NativeSurfaceView. I'm fine reverting changes but I'm not sure if it will affect epd support on Tolino and other ntx boards.

**Comment by NiLuJe** [comment]
@pazos : Does anything else than the epd stuff rely on it? if not, could it be dynamically enabled only on those devices?

**Comment by pazos** [comment]
> Does anything else than the epd stuff rely on it? if not, could it be dynamically enabled only on those devices?

no, the epd stuff just requires a view. Before using a surfaceview we just got the root view using https://github.com/koreader/android-luajit-launcher/blob/a8ace0b9a1c1903c99dd9a5c45821fd583907184/src/org/koreader/launcher/MainActivity.java#L203

Do you mean enable the surfaceView only for tolinos?. That would be fine but I think it should work the same even without the surfaceview (which sits under the window and does nothing).

**Comment by NiLuJe** [comment]
Yep. We've had weirder workarounds ;).

**Comment by pazos** [comment]
> Yep. We've had weirder workarounds ;).

Lets workaround it!

**Comment by JPruente** [comment]
I've found a very similar slow down has returned in 2019.10. It reappeared on one of the two devices in this original report, as well as on a 3rd device I tested on to duplicate the behavior. Would it be best to continue this report or file a new one?

**Comment by Frenzie** [comment]
Please open a new report. The cause may be similar in principle but it's unlikely to be the same.
