### ISSUE TITLE
Installed the last night build and can't start Koreader in android

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#5228]
I' was using a nighty build from the previous month and resolved to install the last nighty build from today and Koreader for android can't start anymore.

Follow the log:

[android.log](https://github.com/koreader/koreader/files/3517973/android.log)

**Comment by NiLuJe** [comment]
Yes, it's a known issue ;).

c.f., https://github.com/koreader/koreader/pull/5207

**Comment by pazos** [comment]
@hugleo: please go to settings->apps->koreader and delete both cache and data (don't worry as /sdcard/koreader won't be affected). Start again to discard that this was a problem uncompressing assets.

**Comment by hugleo** [comment]
Oh thanks, I already solved two seconds ago following the @NiLuJe tip and added ["android_screen_timeout"] = 2, in the settings.reader.lua configuration.

**Comment by pazos** [comment]
Cool. Please do notice that `["android_screen_timeout"] = 2`, means that the screen will turn off after 2 milliseconds without user interaction. I think android won't put anything below 15000 on their settings but lets us now, how much time needs the screen to turn it off?

**Comment by hugleo** [comment]
![Screenshot_20190819-205834_Army Knife for Android](https://user-images.githubusercontent.com/4573505/63307293-4e077180-c2c4-11e9-84eb-e08aaa932698.jpg)
