### ISSUE TITLE
Links to notes at the end of the book don't work

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#5229]
* KOReader version: Last nightly as of today (August, 20th, 2019)
* Device: Kobo Mini

#### Issue
The book I am reading has hundreds of notes. In an update two days ago the notes stopped working. I guess the bug appeared in a change in the last two weeks.
When notes work well, you see in the middle of text something like this:
blahblah[15] blahblah
A single tap to the number will carry you to that note in the chapter at the end of the book with all the notes. There, a sweep on the left side will return you to the initial page. Or you can go back tapping the number of the note in that notes chapter to go back to the main text.
Another way to go to the note at the end of the book is a long press to the number of note. The dictionary will appear and below you will find a "Follow link" button that you can push to go to the note at the end of the book.

#### Steps to reproduce
Single taps on the number of note will work like there was note there. For example, if the note is on the right of the page, it will go to next page. If the note is on the left, the tap will carry you to the previous page, etc.
Long press on the note will make appear the dictionary but the "Follow link" button will be grayed.
If you go to the chapter with all the notes through the Table of contents, then the links to go back to the note work as normal.

**Comment by poire-z** [comment]
Only on that specific book you are reading? Do they work fine in other books (like Wikipedia EPUBs)?
If on all books, sure you haven't changed anything in `Gear > Tap and gestures > Links >`, and tap is enabled there?

In on this book only, could be https://github.com/koreader/crengine/commit/11af8c0124484947541570127bdaf1490205a2b5.

Could you share some extract of the HTML source of a link that is not working (preferably the original HTML source - selecting text around the link and View HTML would hide such encoding). Same for the HTML around the targeting footnote. Or your book.

**Comment by Frenzie** [comment]
So about this range of commits or back to prior to the stable?
https://github.com/koreader/koreader/compare/v2019.08...33e4c36a422d8665fd2e330f930f94446dfe4529

**Comment by poire-z** [comment]
Just to check my suspicion above, can you just get the nightly from http://build.koreader.rocks/download/nightly/v2019.08-13-g84b06d2_2019-08-15/ , extract koreader/libs/libcrengine.so from it and replace the one (from latest nightly) on your device? (hoping there are no other dependancies and that it will not crash).

**Comment by retrue** [comment]
In the Starling version worked the notes. So it must be a change introduced in the last 10 days.
I have checked two books. The book that I am currently reading and the previous book by the same author where the notes worked when I read it but don't work now.
I need to do some things now. In a couple of hours I began to try some of your suggestions.
Thanks.

**Comment by retrue** [comment]
@poire-z  I replaced libcrengine.so with the version you suggested and the problem continues.

**Comment by poire-z** [comment]
(^ have you rebooted after replacing, try it if not, I sometimes have to reboot to get a new lib to be taken into account)
Or just try to install that full nightly v2019.08-13-g84b06d2_2019-08-15 , will help discriminating anyway.

**Comment by retrue** [comment]
I have just tried two versions.

v2019.08-3-g20493ee_2019-08-12/ 
Notes work correctly.

v2019.08-9-gaae6acb_2019-08-14/ 
The behaviour is inconsistent. Most of the time the links on the notes don't work, but sometimes they work. When longpressing on the number of the note, some times in the dictionary screen appears the button "Follow link" grayed, but other times it works.

**Comment by retrue** [comment]
In the book the text with the note appears like this:

<p class="indent">At lunch hour, she walked down the hallway toward the cafeteria behind a group of five girls, who were chatting nonstop like a nest of squirrels. Laura sighed.<sup><a href="9781484799086_epub_nts_r1.xhtml#nts14" id="nts14a">14</a></sup> In California she<a id="GBS.0018.01"/> always had a friend here, a friend there.</p>

The note at the end of the book is like this:

<p class="footnote2"><a href="9781484799086_epub_c02_r1.xhtml#nts14a" id="nts14">14</a><span class="space1"/>Do I really sigh that much?</p>

**Comment by poire-z** [comment]
Thanks.
OK, nothing suspicious with these href and ids.
And if you pinpointed to between v2019.08-3-g20493ee_2019-08-12 and v2019.08-9-gaae6acb_2019-08-14, it's probably not my changes on the crengine side (phew :)
But there is nothing suspicious between these 2 commits !

> The behaviour is inconsistent

Could it depend on where on the screen the footnote link is? Like those in the top or left or right of a page would not work while some in the middle of the page would ?

**Comment by poire-z** [comment]
Oh, you get 3 behavious: correct, inconsistent, and never :)

Anyway, to discriminate whether it's a tap issue, or a link reference issue, can you try to switch from Tap to follow link to Swipe to follow link, and see how Swipe to follow works?
(and if it's different in the "inconsistent" vs "never" cases :)

An all that uniquely with a single cpecific book? Can you share that book?

**Comment by retrue** [comment]
I am a bit lost. As I said before, if through the Table of contents I go to the Endnotes chapter, there the links work correctly in all the cases. That is, tapping on a specific endnote I go to the page of the book where the footnote is.
The problems happen with two books, but both books are from the same author/series and share similar notes. I haven't tried other books.
In the case of inconsistent behaviour I don't remember where in the page was situated the note.
Book is commercial so I cannot share it. Some free book with notes that I can check?

**Comment by poire-z** [comment]
> Some free book with notes that I can check?

Do some Wikipedia lookup, find some (not ridiculously small) article, Save as EPUB, you'll get something with footnotes.

**Comment by Frenzie** [comment]
The United States article has hundreds of footnotes.

**Comment by retrue** [comment]
The inconsistent behaviour appears in version v2019.08-4-g0b8d154_2019-08-13/ 
When tapping some times the links work, other times they don't work. When longpressing to launch dictionary, some times the Follow link appears grayed, other times it works.

That is, the last one that works correctly with this book is version v2019.08-3-g20493ee_2019-08-12/

I tried a Wikipedia article downloaded and converted to epub from my Kobo and the links seem to work !!!!

I used the English article titled "Fractal".  2 notes and 111 references.
I'll try the United States article.

**Comment by poire-z** [comment]
Please try the `Swipe to follow link` first, on links that did not work with Tap.
And/or `Allow larger tap area around links`.
Your inconsistent success rate may depend on the font size used in the various book (and the size of your fingers :).

**Comment by retrue** [comment]
I have always used the same fingers when tapping on notes and I tried different versions of KOReader keeping the same font size and the behaviour was different.
I'll investigate later how to activate swipe to follow link and allow larger tap area. 
Gone to eat.

**Comment by retrue** [comment]
Allow larger tap area around links does the trick.
Links in notes work again, even with the last nightly build.
What doesn't work is the option to Follow link. When longpressing to launch the dictionary, the Follow link button appears always grayed.

**Comment by poire-z** [comment]
Well, so that confirms the links are fine.

Then, there could be a precision issue with the tap, but there's nothing in the commits of that period that looks related to that.

If your Kobo Touch has an infrared screen, could you try hitting the links with a small thin plastic thingie, with `Allow larger tap area` disabled. And see if it works if that thin thingie hits the link correctly, of if you ever need to hit a bit on the left or right or top or bottom?

The `Follow link` button being enabled in the dict window depends on what is looked up. If you see the footnote number being lookuped up (meaning you hold correctly on the footnote link), you should have the `Follow link` button enabled. If you see another word, it means you hold on some text around but not exactly on the footnote link number, and it's logical that you don't have `Follow link` enabled.

**Comment by retrue** [comment]
I only have selected the number of note on the dictionary, not other text, but the Follow link botton always appear gray now.
Mi Kobo is a Mini.
Anyway, notes in Wikipedia articles worked in any case.
I would close the issue and reopen it if the problem reappears.
Thanks.

**Comment by Frenzie** [comment]
I don't really understand what's going on, but alright. :-/
