### ISSUE TITLE
Misplaced target for top right "hold corner" gesture in file browser

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#5247]
1. Go to file browser
2. Add a gesture for "Hold corner" -> "Top right"
3. Try to long press in the top right corner
4. Action is not triggered

In fact, it does work but the target that you need to long press is slightly under the "+" icon. 
"Tap corner" for top right does work (you tap the "+" icon).

**Comment by Frenzie** [comment]
So hold on the icon doesn't work? Must be a missing override or something. Pinging @robert00s who looked at some of this stuff recently. :-)
