### ISSUE TITLE
Enlarge button elements on Android.

### ISSUE THREAD

**Issue by mahesh-hegde** [koreader/koreader#5251]
* KOReader version:
v2019.07
* Device:
Lenovo A1000 Android 5.0

#### Issue
Buttons eg in confirmation / text selection dialogues are not essily clickable. Many times some outside area will be touched and dialogue box disappears. Especially on devices with small screens. This is also irritating when trying to copy text.

#### Possible solution:
  Add option to use larger & easily clickable interface elements. (Or is there anything related to touch sensitivity?).

**Comment by pazos** [comment]
Did you check if https://github.com/koreader/koreader/wiki/DPI-control works for you?

Setting DPI to extra-extra-extra large will make dialogs bigger but wasn't intended as an accesibility feature, so YMMV.

**Comment by mahesh-hegde** [comment]
Thanks a lot, it has solved my problem..

**Comment by Frenzie** [comment]
Alright, I'll close this then. :+1:
