### ISSUE TITLE
[i18n] make two strings translatable

### ISSUE THREAD

**Issue by cges30901** [koreader/koreader#5255]
* KOReader version: 2019.08
* Device: Android

#### Issue
Two strings are not translatable: [copy in readerhighlight](https://github.com/koreader/koreader/blob/fd5fe7dfefff26aaced74868552c0b0d744ea063/frontend/apps/reader/modules/readerhighlight.lua#L803) and [day(s) in statistics](https://github.com/koreader/koreader/blob/fd5fe7dfefff26aaced74868552c0b0d744ea063/plugins/statistics.koplugin/main.lua#L1024).
#### Steps to reproduce
![highlight](https://user-images.githubusercontent.com/19516286/63636681-065a5e80-c6a5-11e9-9de7-9b1164dd8008.png)
![statistics](https://user-images.githubusercontent.com/19516286/63636686-0c503f80-c6a5-11e9-800a-35214c644fd3.png)

**Comment by Frenzie** [comment]
Thanks for reporting!
