### ISSUE TITLE
Cannot be relaunched after update on KPW3-32G

### ISSUE THREAD

**Issue by zivilyyyn** [koreader/koreader#5269]
* KOReader version: v2019.08-51-gba8099f_2019-08-25
* Device: KPW3-32G

##### `crash.log` 
[crash.log](https://github.com/koreader/koreader/files/3541245/crash.log)

**Comment by Frenzie** [comment]
Likely caused by https://github.com/koreader/koreader/pull/5257 (or at least something related).

Which language setting are you using?

**Comment by zivilyyyn** [comment]
chinese

**Comment by Frenzie** [comment]
Neither zh_CN nor zh_TW cause a crash for me, so at least it's (probably) not language specific. I wonder why you're getting a circular dependency though, and I'm not…

Working around it with some code restructuring should be easy enough.
