### ISSUE TITLE
navigate the toc - next chapter

### ISSUE THREAD

**Issue by GianniGi** [koreader/koreader#5291]
* KOReader version:
 koreader-kindle-arm-kindle5-linux-gnueabi-v2019.08.zip

* Device:
pw4

#### Issue
can't jump to next chapter

#### Steps to reproduce
the standard kindle reader is compatible with chapter and I was able to jump from a chapter to another swiping vertically. With this reader this isn't possible anymore, I can't even see the toc.

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

**Comment by Frenzie** [comment]
The default gestures are down, up, down for next chapter and the reverse for previous chapter. This can be changed in Settings → Taps & gestures → Gesture manager.

The TOC is accessible either through the menu, on Kindle also through two-finger swipe right, and using up, right.
