### ISSUE TITLE
empty Estimated reading finished in Statistics plugin

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#5293]
* KOReader version: current
* Device: all
In languages other than English when sentence `%1 (%2 days)` is not translated we get empty string:

https://github.com/koreader/koreader/blob/master/plugins/statistics.koplugin/main.lua#L1025-L1026

English:
![obraz](https://user-images.githubusercontent.com/22982594/64074711-4aee8700-ccaf-11e9-98d8-12e5cea958d1.png)

Polish:
![obraz](https://user-images.githubusercontent.com/22982594/64074696-2692aa80-ccaf-11e9-9256-5454279da371.png)

I think that there are other places when we use `T(N_)`.
After translate everything is ok.

**Comment by Frenzie** [comment]
> In languages other than English when sentence %1 (%2 days) is not translated we get empty string:

That's definitely not true. More likely it's languages with different pluralization rules than English. I should be able to fix it today. ;-)

**Comment by robert00s** [comment]
Ok. I didn't know that :)

**Comment by Frenzie** [comment]
Basically you've got this array of plurals. For Dutch (same rules as English) you've only got 0 and 1:

```
#: plugins/statistics.koplugin/main.lua:1026
msgid "%1 (1 day)"
msgid_plural "%1 (%2 days)"
msgstr[0] "%1 (1 dag)"
msgstr[1] "%1 (%2 dagen)"
```

In Polish you go up to 3 or 4. I must've neglected some scenario in my tests. Perhaps it's related to nil vs "".

https://github.com/koreader/koreader/blob/bc2412a67a25f9d1c92d3ab4f7bf0bceef041df4/frontend/gettext.lua#L292

**Comment by robert00s** [comment]
Right I have 4 rules (1, few, many other)

![obraz](https://user-images.githubusercontent.com/22982594/64075245-1af6b200-ccb6-11e9-9ae3-830d37e4b481.png)
