### ISSUE TITLE
How to turn off font smoothing? Make the font not anti-aliased

### ISSUE THREAD

**Issue by yefeiyu** [koreader/koreader#5299]
* KOReader version: android 5.0
* Device: dpt-rp1

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
Font hinting can be set in the bottom menu.

![Screenshot_20190901_154605](https://user-images.githubusercontent.com/202757/64077319-a7619e80-cccf-11e9-87a5-578421e72b4d.png)

**Comment by yefeiyu** [comment]
> Font hinting can be set in the bottom menu.
> 
> ![Screenshot_20190901_154605](https://user-images.githubusercontent.com/202757/64077319-a7619e80-cccf-11e9-87a5-578421e72b4d.png)

I did not find the anti-aliasing option turned off

**Comment by NiLuJe** [comment]
`Font Hinting` -> `Off`.

That should roughly match the system defaults on Android & iOS. (Unless Android kept hinting on the x axis at some lower dpi values?).

**Comment by NiLuJe** [comment]
You might also be confused on the terminology. What, exactly, are you trying to achieve?

**Comment by poire-z** [comment]
Possibly related: #6352 : be sure Contrast is set to its normal value and it's not it that caused the wish to disable "font smoothing".
But closing. Re-open if needed with more details.
