### ISSUE TITLE
Pali letter & dictionary

### ISSUE THREAD

**Issue by Yyatiko** [koreader/koreader#5317]
* KOReader version: v2019.08
* Device: Kobo_pika

#### Issue

I would like to use the **pali alphabet keyboard** in Koreader to be able to use the pali dictionary.

A lot of these letters are already included in the keyboard but not every one:

![paliaz](https://user-images.githubusercontent.com/54907189/64276309-9efaa500-cf15-11e9-8a4e-d48306dd53b3.gif)

Also, I used the stardict files available [here](https://github.com/indic-dict/stardict-pali). However in koreader, **the dictionary does not recognize the word with a long ā** or other letter that are already available in the koreader keyboard.

I guess the symbol used in the stardict file and the koreader keyboard are different ?

Thank you for your help.

Best wishes,
Yyatiko

[Pali Alphabet on Wikipedia](https://en.wikipedia.org/wiki/Pali#Phonology)

**Comment by Frenzie** [comment]
You could add a new keyboard adaptation, similar to Greek. :-)

https://github.com/koreader/koreader/tree/48f20b215350576133abbf85b7f0e94f99046d08/frontend/ui/data/keyboardlayouts

For the dictionary I wouldn't know unless there's a test document of some sort.

**Comment by Yyatiko** [comment]
Ok, thanks, I just add some new letters in the **en_popup.lua** file like ṁ and ḷ and it works fine. :-)

For the dictionary, I'm a bit confuse.

I install this pali-en [dict](https://github.com/indic-dict/stardict-pali/raw/master/pali-en-head/tars/pali-en-pa__2017-04-27_17-11-27__1MB.tar.gz). 

- It recognize easily word with the new letter ṁ that I add, like **aṁsa** or **abhibhū** with long u

- But it does not recognize any word with long a like **abhisāpa**. I tried to copy/paste the ā from the dict file to the lua file to be sure there are exactly the same, but still does not work.

**Comment by Frenzie** [comment]
@Yyatiko If you modified the default keyboard/popup files, be careful not to update before you've saved & shared your modifications! :-) Updates overwrite system files like that. We'll help to incorporate it properly into the program of course.

> But it does not recognize any word with long a like abhisāpa. I tried to copy/paste the ā from the dict file to the lua file to be sure there are exactly the same, but still does not work.

It might be some Unicode-related shenanigans. You can get often get the same display through a dedicated character like `LATIN SMALL LETTER A WITH MACRON` as well as a regular a followed by a combining diacritical mark. Also pinging @poire-z.

**Comment by Frenzie** [comment]
Btw, command-line results:

```
~/src/koreader/koreader-emulator-x86_64-linux-gnu-debug/koreader$ ./sdcv -01 --data-dir=./data/dict abhisāpa
Found 8 items, similar to abhisāpa.
0)pali-en-pa-->abhisapana
1)pali-en-pa-->abhisapati
2)pali-en-pa-->abhinipati
3)pali-en-pa-->abhirūpa
4)pali-en-pa-->abhisamaya
5)pali-en-pa-->abhisecana
6)pali-en-pa-->abhiseka
7)pali-en-pa-->abhitapati
Your choice[-1 to abort]: ^C
```

The dictionary definiton:
```
"(m.) abhisāpa."anathematise
```

Perhaps it's a bug in sdcv.

**Comment by Frenzie** [comment]
Actually this has something to do with the index of the dictionary itself. Goldendict shows the same result:

![Screenshot_20190905_113533](https://user-images.githubusercontent.com/202757/64330458-50124580-cfd1-11e9-911c-cf1b1c531628.png)

**Comment by poire-z** [comment]
> Actually this has something to do with the index of the dictionary itself

Indeed, just looking at pali-en-pa.idx (binary file, but the words are readable) shows that in it, we can see (in my latin1 world):
`abhibhÅ«` and `abhibhÅ«ta` = u'abhibh\u016bta' , which has `latin small letter u with macron (U+016B)` , so your `abhibhū`  is there in the index.

Looking at words containing `abhis` (the start of the word you did not find: `abhisāpa`) , I only see these:
```
abhisaddahati
5abhisaddahi
2abhisajjana
$abhisajjati
6abhisajji
:abhisamaya
+abhisambhuni
<abhisambodhi
.abhisambuddha
Cabhisambujjhati
Fabhisambujjhi
Dabhisamecca
@abhisamesi
5abhisameta
5abhisameti
6abhisamita
5abhisammati
1abhisammi
3abhisanda
!abhisandahi
<abhisandana
-abhisandati
1abhisandi
4abhisapana
$abhisapati
>abhisatta
)abhisecana
6abhiseceti
Jabhiseka
3abhisitta
```

There are a few others in the synonym file pali-en-pa.syn:
```
abhisaapa    <= might be your word
abhisaarikaa
abhisamaachaarika
abhisambhunaati
abhisametaavii
abhisamparaaya
abhisancetayita
bhisancetesi
abhisanceteti
abhisanga
}abhisaNGkhaara
|abhisaNGkharaNa
yabhisaNGkhari
zabhisaNGkharoti
{abhisaNGkhata
xabhisaTa
abhisincana
abhisincati
abhisinci
```
So, the dict maker  has not put your long word (or any other) with a real `ā` in its indexes, and must have changed them to `aa`. Dunno why, might be it's some comme usage. So, you may do your lookup again knowing that, and using `aa` in place of `ā`...

It's strange as, in the indexes, there are many words with https://graphemica.com/%C5%AB `ū` as is , but not a single one with https://graphemica.com/%C4%81 `ā`.

**Comment by Yyatiko** [comment]
Thanks for all that information and research,

And yes, the pali was first transliterate on computers using  [Velthuis scheme](https://en.wikipedia.org/wiki/Velthuis#Transliteration_scheme). see [history on Wikipedia](https://en.wikipedia.org/wiki/Pali#Writing)

From Wikipedia : [Text in ASCII](https://en.wikipedia.org/wiki/Pali#Text_in_ASCII)

> The Velthuis scheme was originally developed in 1991 by Frans Velthuis for use with his "devnag" Devanāgarī font, designed for the TeX typesetting system. This system of representing Pali diacritical marks has been used in some websites and discussion lists. However, as the Web itself and email software slowly evolve towards the Unicode encoding standard, this system has become almost unnecessary and obsolete.
> 
> The following table compares various conventional renderings and shortcut key assignments:

> 
![Screenshot from 2019-09-05 09-04-44](https://user-images.githubusercontent.com/54907189/64344318-39152880-cfbc-11e9-8b1b-d95f33631daa.png)

**Comment by Frenzie** [comment]
@Yyatiko Btw, please don't forget to submit your keyboard for consideration! :+1:

**Comment by Yyatiko** [comment]
Yes, it is pretty easy, the English one is already pretty good I just need to add some of this letters:

Vowels
a,   ā,   i,   ī,   u,   ū,   e,   o 

Consonants
k,   kh,   g,   gh,   **ṅ**;
c,   ch,   j,   jh,   ñ;
ṭ,   ṭh,   ḍ,   ḍh,   ṇ; [2]
t,   th,   d,   dh,   n; [3]
p,   ph,   b,   bh,   m;
y,   r,   l,   v,   s,   h,   **ḷ**,   **ṃ**

From https://www.bps.lk/pali_misc/palipron.html

And also, I think of removing the extra letter in the popup that are in the second level (outside the first 8 letter ring) because it doesn't work that well with the sweeping Technic (my opinion)

I might share my files next week.
Thanks for everything!

**Comment by Frenzie** [comment]
Any characters outside of the 9 directions need hold to activate. That's why they're "niche" bonus characters, at least for English.

**Comment by Yyatiko** [comment]
Ok, I thought that it depends of how long the sweep was... I was confuse ;-)

**Comment by Frenzie** [comment]
Actually that might not be a bad idea, although I'm not really a big fan of the paradigm.

We do have it right now. A short diagonal swipe refreshes the screen, while a long diagonal swipe (i.e., most of the screen) takes a screenshot.

What I'd personally probably like a lot better would be a back & forth multiswipe. And on devices that support it, a two-finger swipe.

The only problem there is that I was also considering something similar for capitalization (which would be a lot quicker than pressing shift).

**Comment by Yyatiko** [comment]
Oh yes, keep it for capital, this would be great !
I think, the outer-ring is a bit superfluous.

**Comment by Frenzie** [comment]
It is, but having those IPA characters available just makes me happy. (As does not having to switch keyboards or something.) They're still quick to reach with hold, move & release, just not as quick as the swipes.

**Comment by Yyatiko** [comment]
I would just change the **behavior of the popup** to:

1. Holding a character to display the popup.
2. Taping on a character 
3. The popup disappear automatically after the first tap. (you don't have to tap somewhere else to make the popup window disappear)

And I would do the same for **Capital Letter**.

1. Tap on Shift 
2. Tap a character
3. The capital disappear automatically after the first tap. (you don't have to tap on shift again to go back to lower case)

Could use **holding** on shift to block character to capitals.
