### ISSUE TITLE
Possibly buggy page overlap arrow

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#5322]
* KOReader version: current nightlies
* Device: Kobo Forma (but probably irrelevant)

#### Issue

The "arrow" variant of the page overlap feature appears to be a bit wonky when paging *backwards*: it's positioned where the overlap cutoff would be if we had paged *forward*.

#### Steps to reproduce

(Say, a PDF page is 125% taller than your screen, if you page forward, you get 75% of overlap, with the arrow near the bottom. If you then page backward, it should be near the top. It stays at the bottom).

Graying out behaves properly, on the other hand.

##### `crash.log` (if applicable)

N/A

**Comment by NiLuJe** [comment]
It's possibly eInk-only, in that I could imagine the arrow refresh region being broken/bogus, and as such skipped, and the issue is in fact not a bogus arrow position, but a stale arrow being kept on screen.

**Comment by poire-z** [comment]
@NiLuJe : as I read above "arrow refresh region being broken/bogus", just thought you might have fun with this :)
(may be it's fixed since we made it SVG and you did some stuff with alpha).
