### ISSUE TITLE
Custom sorting of status bar elements

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#5329]
Kind of weird arbitrary sorting by default when "show all at once" is on (battery and clock mixed between reading status elements).
Maybe putting the elements in the order you select them would be easy to implement?
Thanks!

**Comment by LucyOne** [comment]
I would like that, too.

**Comment by robert00s** [comment]
How should look widget?

**Comment by poire-z** [comment]
> How should look widget?

If you're having a go at that, may be it doesn't need any specific UI.
As it seems Holding on the menu items has yet no effect (and no help_text), one simple option would be to just Hold on one item to make it the first. A few holds and you could reorder your items once you get the trick.
For the visual feedback, either just add a number after the text item - or a little more complicated: re-order the menu items following that order (so, Hold would refresh the menu with the item you just hold on at the top).

Or, as suggested, just do that on tap when an item is selected (so uncheck then check => that item is at top).

**Comment by Frenzie** [comment]
@robert00s I would say an ideal widget would allow for some form of drag & drop or selecting an element and moving it up/down with arrow buttons on the bottom/side. But in lieu of such a widget (which I imagine would take at the very least an hour to create) I fully concur with @poire-z's suggestion.

> Or, as suggested, just do that on tap when an item is selected (so uncheck then check => that item is at top).

Preferably not. :-) I do that to enable/disable items (as would anybody else I'm sure) and then I'd end up with some completely random order.
