### ISSUE TITLE
Pdf image zoom

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#5339]
If I hold my finger in a epub image then the image will zoom through the whole screen. Can I do the same for pdf?

**Comment by Frenzie** [comment]
If you're asking if it's possible then no. ;-) Theoretically, maybe.

**Comment by poire-z** [comment]
Seems possible since #6511 and #6960.

**Comment by EastEriq** [comment]
This is with "Panel zoom (manga/comic)" and "Fall back to text selection" both tagged, btw.
