### ISSUE TITLE
[Android]: toggle frontlight causes the screen goes black

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5340]
* KOReader version: 2019.09 (any version after https://github.com/koreader/android-luajit-launcher/commit/3750551c6607aa5fa53c77a7095e1dba0b11237b was merged)
* Device: Tolino FW10 4.0.3 and probably other legacy devices with broken firmware.

#### Issue

Black screen, as reported by @Norbi24 in https://www.mobileread.com/forums/showthread.php?p=3887354#post3887354

#### Steps to reproduce

1. uncheck "use system settings"
2. press the toggle button.

##### Workaround

In settings.reader.lua replace["fl_last_level"] = 0 ' with a possitive number other than 0.

Lets see if this just affects one model or there are other devices with broken behaviour. Posible solutions are:

1. disable frontlight control on broken devices
2. workaround by using fl_min > 0.

I would go for 1 if this issue just affects this device.

**Comment by pazos** [comment]
Coolreader has a database for specific devices with minimum light levels other than 0: https://github.com/buggins/coolreader/blob/master/android/src/org/coolreader/crengine/DeviceInfo.java#L65

**Comment by Frenzie** [comment]
I can see how a brightness of 0 might do something unexpected on a backlit screen, but isn't this an E Ink device?

**Comment by pazos** [comment]
Yes, e-ink.

AFAIK this issue can't be reproduced on newer vendor firmware.

**Comment by pazos** [comment]
Closing this as part of #5364
