### ISSUE TITLE
Inverted page turns not initialized properly

### ISSUE THREAD

**Issue by hgrain86** [koreader/koreader#5346]
* KOReader version: V1-09-2019
* Device: kobo aura one

#### Issue: I cant find (right to left) option in the last update! it was very useful for me when i read arabic books :(

**Comment by poire-z** [comment]
It has been moved to another menu: `Gear > Navigation > Invert page turn taps and swipes` (#5284).

**Comment by hgrain86** [comment]
> It has been moved to another menu: `Gear > Navigation > Invert page turn taps and swipes` (#5284).

It does not work properly on kobo aura one 
I need to activate it every time i want to  read the book
then When I do this new option crashes a lot of other features
like bookmarks and select text ............
I apologize for the poor language I do not speak English and I use Google translator to communicate
thanks a lot.

**Comment by Frenzie** [comment]
I must've made a mistake if it's not loading the setting properly, but what's this about bookmarks not working and crashing?

**Comment by hgrain86** [comment]
Now after the update the problem seems to be solved but you can not bookmark the book after activating the option (invert page turn.....) until you restart the program 
thanks a lot

**Comment by Frenzie** [comment]
Confirmed, but it's an old(er) issue, not a regression in 2019.09.
