### ISSUE TITLE
Dictionary not working 

### ISSUE THREAD

**Issue by bajrabb** [koreader/koreader#5347]
* KOReader version: 2019.09.1
* Device: likebook

Issue: Dictionary lookup isn't working even though all the dictionaries are in dict folder.

**Comment by NiLuJe** [comment]
I can reproduce on Android 9, FWIW. (The popup reports no match).

I can't really pinpoint when it borke, as my phone is a backup reader, but it for sure worked in .08, and for possibly quite a bit of nightlies after that.

**Comment by NiLuJe** [comment]
Also, slightly related: the dictionary *download* feature never worked quite right on my end.

It generally downloads fine, but the unpack fails, either completely, silently or not. With .09, it actually crashes KOReader.

**Comment by Frenzie** [comment]
@NiLuJe mentioned something similar [on Gitter](https://gitter.im/koreader/koreader?at=5d756597b3e2fc57937830fc) last night.

**Comment by NiLuJe** [comment]
Okay, I'm terrible at Android stuff, but I don't see anything in the logs (short of a few failures top open DroidSansFallback, which makes sense, since I don't have it and we don't shit it anymore :p).

I can't try it manually in a shell (or check the integrity of the /data folder), as my device is not rooted, and I can't use run-as with release packages ;).

**Comment by Frenzie** [comment]
@pazos or I can probably give it a go in the Android 9 emulator later. However… I wouldn't assume this Likebook device to run anything close to 9.

**Comment by NiLuJe** [comment]
The aforementioned broken dictionary download feature means that I simply run tar in a Terminal from within the device itself, FWIW.

(The download itself is usually sane, it's only the untar that craps out).

**Comment by Frenzie** [comment]
Are there spaces in the path?

**Comment by poire-z** [comment]
Fails for me too, with Android 6 (with out nightly 08-75 g258b13d from 20190830).
I don't see anything thru a catlog app.
But I see with a file browser that in /data/data/org.koreader.launcher/files/ that sdcv (and tar, zsync...) permissions are `-rw-------`. Shouldn't they be +x ? (I may remember some discussions about preserving permissions when you switched from 7z to zip?)

**Comment by Frenzie** [comment]
Interesting, in that case it might work on my real devices because I'm running KOReader directly updated on top of old KOReader (because changing the contents of a file shouldn't change its permissions).

**Comment by Frenzie** [comment]
I can confirm @poire-z's finding on a fresh install.

> I may remember some discussions about preserving permissions when you switched from 7z to zip?

Not 100 % sure but I think you might be confused with Android runtime permissions (read/write SD card, that kind of thing).

**Comment by NiLuJe** [comment]
Ah. The good news is the exec bit is set properly in the asset zip:

```
unzip -Z assets/module/koreader-v2019.09.1.zip

-rwxr-xr-x  3.0 unx  1950180 bx defX 19-Sep-07 22:11 sdcv
```

The bad news is I have no idea why that would be dropped on unpack on a POSIXy target system :/.

**Comment by Frenzie** [comment]
Regression introduced in d2536d8b7e9474bd7748b199d1f01a53f332942a.

**Comment by Frenzie** [comment]
Since this is a pretty serious issue I say we stick those three lines back in for a 2019.09.2 and worry about the other details later:

```lua
-- set proper permission for binaries
A.execute("chmod", "755", "./sdcv")
A.execute("chmod", "755", "./tar")
A.execute("chmod", "755", "./zsync")
```

**Comment by Frenzie** [comment]
Err, maybe there's a slight side effect of dropping Noto. Guess I should revert that too. :man_facepalming: 

```
09-09 15:41:03.254  3926  3943 W KOReader:  HTML loading error: ffi/mupdf.lua:67: MuPDF cannot open document from text: cannot open ./fonts/noto/NotoSans-Regular.ttf: No such file or directory (2)
09-09 15:41:03.256  3926  3943 E libmupdf: cannot open ./fonts/noto/NotoSans-Regular.ttf: No such file or directory
09-09 15:41:03.256  3926  3943 W KOReader:  error in wrapped function: frontend/ui/widget/htmlboxwidget.lua:69: ffi/mupdf.lua:67: MuPDF cannot open document from text: cannot open ./fonts/noto/NotoSans-Regular.ttf: No such file or directory (2)
```

(However, the fact that it wants to use MuPDF shows it loaded the dictionary entry.)
