### ISSUE TITLE
Android won't upgrade cleanly

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#5355]
* KOReader version: 201909xxx
* Device: Android

There is something fishy in the upgrade procedure for Android apps: installing a more recent apk on top of an old one doesn't seem to update the software.

So, when the original 201909 came out, I manually uninstalled 201908 completely and then was able to successfully install 201909. However, after downloading the 2019.09.2 apk and installing it, I got 'install successful'. However, the dictionary bug is still present, and when I ask to check for upgrades from with the app, it complains about the latest available version being a downgrade:

Installed version: 20190900000
Available version: 20190800000

**Comment by gerhaher** [comment]
Same for me. 
It says my version is v2019.08-59 although I have upgraded several times after that.

**Comment by pazos** [comment]
@pbienst @gerhaher: Do you see the "spinning circle" the first time after you installed a new package?.

Also, could you check that the version inside KOReader matches the version of the package that is available from android application settings?.

**Comment by pbienst** [comment]
I don't think I saw the spinning circle, but I'm not 100% sure.

The Android OS does seem to think I'm on 2019.09.2, but the information from inside the app doesn't agree.

**Comment by gerhaher** [comment]
"Spinning circle": yes, if you mean the circle that is shown every time KOReader is started.

I have #5266 but not #5276 (and nothing after that I suppose)

**Comment by Frenzie** [comment]
@pbienst Good catch! Here I thought I'd been testing new changes on my Android devices but actually it looks like I haven't been for a few weeks now. That makes my analysis of why I didn't suffer from #5347 completely incorrect, even if the fixes I pushed through yesterday do solve the issue because in emulator testing I usually use wipe+install.

PS While in this case it doesn't seem to matter, "Android" isn't a device. ;-) Even without device-specific quirks, the differences between Android versions are insane.

**Comment by Frenzie** [comment]
It does say it found a new package revision and that it extracted the files, but it doesn't seem to actually overwrite anything in practice.
```
09-10 12:12:46.763  5135  5135 I KOReader: Application started
09-10 12:12:46.763  5135  5135 V KOReader: Application info {
09-10 12:12:46.763  5135  5135 V KOReader:   Flags: user
09-10 12:12:46.763  5135  5135 V KOReader:   Paths {
09-10 12:12:46.763  5135  5135 V KOReader:     Assets: /data/user/0/org.koreader.launcher/files
09-10 12:12:46.763  5135  5135 V KOReader:     Library: /data/app/org.koreader.launcher-2/lib/x86
09-10 12:12:46.763  5135  5135 V KOReader:     Storage: /storage/emulated/0
09-10 12:12:46.763  5135  5135 V KOReader:   }
09-10 12:12:46.763  5135  5135 V KOReader: }
09-10 12:12:46.763  1301  1355 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
09-10 12:12:46.772  5135  5148 V KOReader: [NativeThread]: waiting for activity
09-10 12:12:46.773  1615  1676 D WifiService: New client listening to asynchronous messages
09-10 12:12:46.798  5135  5148 V KOReader: [NativeThread]: activity window ready.
09-10 12:12:46.799  5135  5148 V KOReader: [NativeThread]: activity gained focus.
09-10 12:12:46.799  5135  5148 V KOReader: [NativeThread]: launching LuaJIT assets
09-10 12:12:46.815  1739  2225 D EGL_emulation: eglMakeCurrent: 0xae614f60: ver 2 0 (tinfo 0xae6125d0)
09-10 12:12:46.816  1301  1357 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8294400
09-10 12:12:46.822  5135  5148 I KOReader: Check file in asset module: koreader-v2019.09.2.zip
09-10 12:12:46.823  5135  5148 I KOReader: Found new package revision v2019.09.2
09-10 12:12:46.823  5135  5148 I KOReader: Installing new package to /data/user/0/org.koreader.launcher/files
09-10 12:12:47.345  5135  5148 V KOReader: update installed in 0 seconds
09-10 12:12:47.346  5135  5148 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
```

**Comment by Frenzie** [comment]
>  However, the dictionary bug is still present, and when I ask to check for upgrades from with the app, it complains about the latest available version being a downgrade:

This is a completely separate issue btw. It's a minor oversight in the server-side changes related to #5268. The program queries the server for what the latest version is. I failed to notice because I have an x86 phone.

http://ota.koreader.rocks/koreader-android-latest-stable
```
koreader-android-arm-linux-androideabi-v2019.08.apk
```
http://ota.koreader.rocks/koreader-android-x86-latest-stable
```
koreader-android-x86-v2019.09.2.apk
```

**Comment by NiLuJe** [comment]
Yup, noticed the same thing last night when going from .01 to .02, was going to mention it today ;).

**Comment by pazos** [comment]
Woooow, the whole thing is fishy.

If the git-rev file is not updated I would expect the spinning circle running each time the program is started after an exit (not resumed from the launcher/ recent app picker)

If is just the git-rev then is just a matter of explicit close the FileBuffer (which should be released when the `isSameVersion` is out of scope.

AFAICT all files shall be overriden. If this isn't the case we can delete files manually before extracting the new assets.

**Comment by NiLuJe** [comment]
It's not just that one file, upgrading from .09.01 to .09.02 left me w/ broken dictionaries until I did a clean reinstall ;).

**Comment by Frenzie** [comment]
I don't think any of the files are overwritten, but new files are added though (i.e., AutoTurn).

**Comment by pazos** [comment]
Ofc, It is just another stupid error on my logic https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/AssetsUtils.java#L117

🤦‍♂ 🤦‍♀

I will fix that tonight.

**Comment by Frenzie** [comment]
@pazos Thanks, then let's push it to master, see if it updates properly in a (triggered) nightly and push out a third (:man_facepalming:) point release within the next few days. Since uninstall/install does the trick it's slightly less urgent.

**Comment by Frenzie** [comment]
Alright, the OTA is now fixed.

http://ota.koreader.rocks/koreader-android-latest-nightly
```
koreader-android-arm-v2019.09.2-1-gdeebbfe_2019-09-10.apk
```

**Comment by Frenzie** [comment]
In roughly a half hour there'll be a new nightly. If you can, please give it a try.

**Comment by poire-z** [comment]
Confirming the manual install of `koreader-android-arm-v2019.09.2-2-g4da512c_2019-09-10.apk` worked for me (while update didn't work for me either 2 days ago).
