### ISSUE TITLE
Unable to exit KOReader onKobo Glo

### ISSUE THREAD

**Issue by calverb** [koreader/koreader#5356]
* KOReader version:
2019.09.02
* Device:
Kobo Glo
#### Issue
I have two Kobo Glos one with 2019.09 and one with 2019.09.02.   Both have the same problem. These were updated using OTA from the earlier 2019.08.

When I try to exit KOReader, I get a "Bomb" Screen and KoReader restarts.   This even happens if I try to exit using the Power Off option.   The only way I can shut down KOReader is by using a Hard reset (paperclip reset) on the device,  The Power Slider on the Glo takes me to the power off screen and then restarts KOReader

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/3594662/crash.log)

**Comment by Frenzie** [comment]
```
./luajit: frontend/device/kobo/nickel_conf.lua:162: Wrong front light state value type (expect boolean)!
stack traceback:
	[C]: in function 'assert'
	frontend/device/kobo/nickel_conf.lua:162: in function 'set'
	frontend/device/kobo/powerd.lua:187: in function 'saveSettings'
	frontend/device/kobo/device.lua:725: in function 'saveSettings'
	frontend/ui/uimanager.lua:63: in function 'action'
	frontend/ui/uimanager.lua:746: in function '_checkTasks'
	frontend/ui/uimanager.lua:1029: in function 'handleInput'
	frontend/ui/uimanager.lua:1115: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x000140c1
```

Some functions in that file seem to be using a plain assert instead of a dbg:guard. Perhaps those parts predate dbg:guard.

https://github.com/koreader/koreader/blob/6af1bc46b1e43fff06c61015ba46443a643e959d/frontend/device/kobo/nickel_conf.lua#L161-L169

https://github.com/koreader/koreader/blob/6af1bc46b1e43fff06c61015ba46443a643e959d/frontend/device/kobo/nickel_conf.lua#L183-L187

However, it doesn't seem like this would be related to 2019.09.

What's your Kobo firmware version?

**Comment by calverb** [comment]
I thought I had replied using Email; but perhaps not

Kobo is running 4.15.12920 (27/5/2019).
No problem before I updated to KoReader 2019..09

Apologies for any duplication
---------------

**Comment by NiLuJe** [comment]
How are you launching KOReader, and if you use KSM, how did you install the FW update?

What are your frontlight settings in Nickel?

**Comment by Frenzie** [comment]
Going back and forth between KOReader & Nickel still syncs the frontlight state correctly for me on the same version. I tried it in both directions with different intensities as well as on/off.

Out of curiosity, could you try to find the relevant line in `/mnt/onboard/.kobo/Kobo/Kobo eReader.conf` to see what it says? These would be the lines starting with `FrontLightLevel` and `FrontLightState`.

**Comment by NiLuJe** [comment]
Yeah, i'm just wondering if the *Nickel* state is there/sane, and whether KSM's funky update filtering may not have fucked something up.

**Comment by calverb** [comment]
I launch KoReader using KSM.   I did the Update to KoReader using the OTA update.

Checking Kobo eReader.conf I get :

[PowerOptions]
AutoSleepMinutes=5
FrontLightLevel=1
FrontLightState=false
ShowBookCover=false
----------

**Comment by Frenzie** [comment]
I changed a line in 1b17ce8ba016c8d027d0c19d589f26e576a27a8b. If the first value is false and the second value is nil then I think it would end up as nil, which is false-y but it might cause this side effect and extra `or false` might solve the problem.

What's weird though is that I usually have the frontlight turned off and I haven't seen this. @calverb Could you see if adding `or false` to that line fixes the issue?

**Comment by calverb** [comment]
I think I have found the line you mean on the Kobo ,   Is it  (line 171)
` local cur_is_fl_on = self.is_fl_on or self.fl_was_on`
and you want me to change it to:
` local cur_is_fl_on = self.is_fl_on or self.fl_was_on or false`

have I got your intention right ?
(this is very much monkey-see, monkey-do to me)

**Comment by Frenzie** [comment]
Exactly! :+1:

**Comment by Frenzie** [comment]
@calverb Btw, what frontlight settings did/do you use?

**Comment by calverb** [comment]
I normally have the front light switched off.    The only settings I'm aware of are those in my earlier reply.  If there are more then where do I find them ?

**Comment by Frenzie** [comment]
I don't think there would be any others. That should basically be the same as my own regular settings, weird.

Did the change I suggested make a difference?

(Btw, the bomb screen shouldn't show up more than… 5 times I think? No need to hard reset.)

**Comment by calverb** [comment]
Yes - the change does seem to have fixed the problem.

Thanks for walking me through it.

**Comment by NiLuJe** [comment]
> (Btw, the bomb screen shouldn't show up more than… 5 times I think? No need to hard reset.)

... Provided each subsequent crash happens less than 20s after the previous one, otherwise it's back to the beginning of the queue ;).

(The logic is mostly aimed at crash loops *on startup*, where that's pretty much always going to be the case, given that the "touch me" timeout is set at 15s).

**Comment by Frenzie** [comment]
Oh right, I made some remark about that myself.
