### ISSUE TITLE
FTP server Drivehq.com cant fetch list

### ISSUE THREAD

**Issue by HoanPiTa** [koreader/koreader#5360]
* KOReader version: 2019.09.3
* Device: kinder ppw3 

#### Steps to reproduce
my setting information
ftp name: drivehq
ftp sever: ftp://ftp.drivehq.com
ftp user and account.
ftp folder :  /
i still can connect on ES file explorer on android
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
It looks like it uses FTPS (FTP over TLS).

Looks like the cloudstorage/FTP plugin doesn't generate any debug output though? Pinging @robert00s

**Comment by robert00s** [comment]
Yep. We doesn't support FTPS. Similar to #3193.
We need to add cURL library to KOReader but I don't know how. Help is needed :)

**Comment by NiLuJe** [comment]
cURL is *extremely* unfriendly to use directly. DId you have a specific wrapper/bindings in mind?

**Comment by Frenzie** [comment]
Closing in favor of #3193.
