### ISSUE TITLE
Feature Request: access web links

### ISSUE THREAD

**Issue by angrierhorse** [koreader/koreader#5365]
Is it possible to use the newsdownloader (web page>ebook function) to pull other web pages as ebooks?  

Sometimes articles I am reading refer to other articles, if you click on the link it simply says link unhandled.  Is it possible to have koreader offer the option of fetching these external links as ebooks?

**Comment by Frenzie** [comment]
I'll close this now. With the offline queue in place (<https://github.com/koreader/koreader/pull/6170>) I consider Wallabag the go-to solution for this problem.
