### ISSUE TITLE
[Question] What does 'pass through' mean in the gesture manager?

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#5366]
Is it the same as 'nothing'?

Does enabling multi-swipe gestures use more battery? Or is it negligible?

**Comment by CalbertAmu** [comment]
Thank you for explaining. The reason I asked if it uses more energy is because I thought the multiswipes sort of 'waits'/ 'listens' for the input. Similar to how on some phones, the digitizer can be kept on low power (while screen is off) to wait for an input like swiping or double tap. It uses tiny bit of power, but the convenience outweighs the power consumed.

**Comment by Frenzie** [comment]
Unless you suspend it the device is always waiting for input, but multiswipes don't have anything to do with that. It's quite literally just multiple swipes stitched together.

Basically what it does is:

1. Swipe + direction detected
2. Still going in the same direction? Cool. This is now the new swipe length.
3. Changed direction, new swipe started.
4. Repeat the above until swipe end.

The additional logic is just about remembering the directions and limiting them to only four, either straight or diagonal.
