### ISSUE TITLE
How upgrade nickel?

### ISSUE THREAD

**Issue by Nanco300** [koreader/koreader#5370]
* KOReader version:  2019.09.3
* Device: Kobo Glo

How I do upgrade Nickel without lost installation of the Koreader?

**Comment by Nanco300** [comment]
I upgraded the fw, but lost the installation of the Koreader and reinstal don't work. I used this method for reinstall.

https://www.mobileread.com/forums/showpost.php?p=3694364&postcount=250

**Comment by NiLuJe** [comment]
Someone with actual KSM experience might be of assistance ;).

**Comment by Frenzie** [comment]
Those are extra complicated instructions for a specific scenario. It's easier to just follow the normal instructions. ;-)

Also see https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices

**Comment by Nanco300** [comment]
> Those are extra complicated instructions for a specific scenario. It's easier to just follow the normal instructions. ;-)
> 
> Also see https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices
USB broked in my Kobo.

**Comment by pazos** [comment]
> USB broked in my Kobo.

You mean the usb connector or is just that doesn't work anymore as mass storage?

**Comment by Nanco300** [comment]
> > USB broked in my Kobo.
> 
> You mean the usb connector or is just that doesn't work anymore as mass storage?

The mass storage.

**Comment by Nanco300** [comment]
Kfmon saved my life. Thank you all.
