### ISSUE TITLE
FR: Add rumble support

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#5374]
More of a brainstorm than an FR. Linkdump without commentary incoming.

Docs:
https://wiki.libsdl.org/SDL_HapticOpenFromJoystick
https://developer.android.com/reference/android/os/Vibrator

https://davidgow.net/handmadepenguin/ch6.html

Background:
https://medium.com/@sdrzn/make-your-ios-app-feel-better-a-comprehensive-guide-over-taptic-engine-and-haptic-feedback-724dec425f10

**Comment by pazos** [comment]
@Frenzie: I do like the idea but after a quick search I think the implementation on android could have some problems:

1. differences between api levels
2. overhead of the JNI calls (about 1ms)
3. Is the call blocking the program until the vibration stops? In that case vibrate on keyboard taps will become impossible.

Also I would like to finish https://github.com/koreader/android-luajit-launcher/pull/183 first and these days I'm very busy trying to find time for both my daily job and my family.

**Comment by Frenzie** [comment]
> Is the call blocking the program until the vibration stops?

Certainly not in SDL.

> Also I would like to finish koreader/android-luajit-launcher#183 first and these days I'm very busy trying to find time for both my daily job and my family.

I'm just asking for some feedback on the device abstraction logic. ;-) Job & family take precedence of course!

**Comment by pazos** [comment]
@Frenzie: I did a first implementation in https://github.com/koreader/android-luajit-launcher/pull/190.

Needs a lot of testing and tweaking because default values are far from perfect (at least in 8.0+)

I'm currently testing with this changes on the frontend:

```diff
diff --git a/frontend/device/android/device.lua b/frontend/device/android/device.lua
index 4deee2c1..b194da09 100644
--- a/frontend/device/android/device.lua
+++ b/frontend/device/android/device.lua
@@ -70,6 +70,7 @@ local Device = Generic:new{
     canRestart = no,
     firmware_rev = android.app.activity.sdkVersion,
     display_dpi = android.lib.AConfiguration_getDensity(android.app.config),
+    isHapticFeedbackEnabled = function() return android.canVibrate() end,
     hasClipboard = yes,
     hasOTAUpdates = canUpdateApk,
     canOpenLink = yes,
@@ -225,6 +226,15 @@ function Device:initNetworkManager(NetworkMgr)
     end
 end
 
+function Device:performHapticFeedback(type)
+    local short, long = 80, 160 -- milliseconds
+    if type == "CONTEXT_CLICK" or type == "LONG_PRESS" then
+        android.vibrate(long)
+    elseif type == "KEYBOARD_TAP" then
+        android.vibrate(short)
+    end
+end
+
 function Device:retrieveNetworkInfo()
     local ssid, ip, gw = android.getNetworkInfo()
     if ip == "0" or gw == "0" then
```

**Comment by poire-z** [comment]
If it comes to Android, it would be nice if it was toggable via a menu checkbox.

**Comment by pazos** [comment]
> If it comes to Android, it would be nice if it was toggable via a menu checkbox.

Sure, I'm the first that want vibration disabled. But I'm starting to change my mind about the keyboard feedback because it can be really nice.

In any case `android.prop.vibration` is a boolean referencing if the current device has vibration capabilities. We can disable it at launch just by `android.prop.vibration = false` and won't hurt anymore.

**Comment by Frenzie** [comment]
> it would be nice if it was toggable via a menu checkbox.

@poire-z @pazos That's an advantage I neglected to mention in https://github.com/koreader/android-luajit-launcher/pull/190#issuecomment-536626078

Because then it is, in system settings.

**Comment by pazos** [comment]
> Because then it is, in system settings.

That is awesome :+1:  Also the implementation is really simple.

New PR in https://github.com/koreader/android-luajit-launcher/pull/192

Works with the following change in the frontend:

```diff
diff --git a/frontend/device/android/device.lua b/frontend/device/android/device.lua
index 4deee2c1..885731c6 100644
--- a/frontend/device/android/device.lua
+++ b/frontend/device/android/device.lua
@@ -70,6 +70,7 @@ local Device = Generic:new{
     canRestart = no,
     firmware_rev = android.app.activity.sdkVersion,
     display_dpi = android.lib.AConfiguration_getDensity(android.app.config),
+    isHapticFeedbackEnabled = yes,
     hasClipboard = yes,
     hasOTAUpdates = canUpdateApk,
     canOpenLink = yes,
@@ -225,6 +226,16 @@ function Device:initNetworkManager(NetworkMgr)
     end
 end
 
+function Device:performHapticFeedback(type)
+    if type == "CONTEXT_CLICK" then
+        android.hapticFeedback(C.AHAPTIC_CONTEXT_CLICK)
+    elseif type == "LONG_PRESS" then
+        android.hapticFeedback(C.AHAPTIC_LONG_PRESS)
+    elseif type == "KEYBOARD_TAP" then
+        android.hapticFeedback(C.AHAPTIC_KEYBOARD_TAP)
+    end
+end
+
 function Device:retrieveNetworkInfo()
     local ssid, ip, gw = android.getNetworkInfo()
     if ip == "0" or gw == "0" then
```

**Comment by Frenzie** [comment]
Given that I named them after the Android constants because they seemed sensible enough, you should be able to just use C["AHAPTIC_"..type].
