### ISSUE TITLE
Device powered off when charged

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5376]
* KOReader version: v2019.09.3-7-g840d05b_2019-09-12/  
* Device: KA1

#### Issue
After updating to latest nightly this morning I noticed that my device now gets powered off when I charge it. (From sleep to powered off.)

**Comment by Frenzie** [comment]
You mean in less than 96 hours? Could you please attach the crash.log?

**Comment by gerhaher** [comment]
No, directly after. Like this:
1. Device in sleep mode
2. Charge device
3. Pull out the cable
4. After a few seconds: powered off

**Comment by Frenzie** [comment]
There does seem to be a bug related to updating the value through the GUI without a restart due to a stupid variable name (swapping between `sec` and `seconds`) semi-inherited from the plugin as it was:

https://github.com/koreader/koreader/blob/840d05b3ae1f0622f6fe98b40d4af1b5f1bf108a/plugins/autosuspend.koplugin/main.lua#L187

Did you touch the autoshutdown settings and use, say, one minute for testing purposes?

**Comment by gerhaher** [comment]
> Did you touch the autoshutdown settings and use, say, one minute for testing purposes?

Well, I just checked it out (meaning: opened "Autoshutdown timeout" and then closed it without changing anything)

**Comment by Frenzie** [comment]
Could you verify the `autoshutdown_timeout_seconds` in settings.reader.lua? If you pressed cancel it shouldn't be there at all, and if you pressed "set timeout" it should be set to the default of 72 hours.

**Comment by gerhaher** [comment]
> Could you verify the autoshutdown_timeout_seconds in settings.reader.lua? If you pressed cancel it shouldn't be there at all, and if you pressed "set timeout" it should be set to the default of 72 hours.

Checked. It's not there.

**Comment by Frenzie** [comment]
The default (no setting) works correctly for me:

```
# cat /proc/driver/rtc
rtc_time	: 10:56:31
rtc_date	: 2019-09-14
alrm_time	: 10:55:25
alrm_date	: 2019-09-17
alarm_IRQ	: yes
alrm_pending	: no
24hr		: yes
```

The suspend part of the log that was attached above:
```
ifconfig: SIOCSIFADDR: No such device
09/14/19-11:45:59 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
09/14/19-11:46:14 INFO  Kobo suspend: going to sleep . . .
09/14/19-11:46:14 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
09/14/19-11:46:16 INFO  Kobo suspend: waited for 2s because of reasons...
09/14/19-11:46:16 INFO  Kobo suspend: synced FS
09/14/19-11:46:16 INFO  Kobo suspend: asking for a suspend to RAM . . .
09/14/19-11:46:16 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
09/14/19-11:46:45 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1568450820	1568450820	1568450820
validateWakeupAlarmByProximity	nil	1568450820	1568450820	1568450820
```

The epoch from your log seems to be `Saturday, September 14, 2019 8:47:00 AM`. Assuming you're in UTC+3 that's basically a minute after suspend. But there's no logical way to end up with about a minute unless you explicitly set it. Weird.

Any ideas @NiLuJe?

**Comment by xianren78** [comment]
i met this auto powered-off on my kobo aura h2o too with KOReader version: v2019.09.3-7-g840d05b_2019-09-12 booted by KSM09. I kept Autoshutdown timeout unchanged as default 72hrs. and then set to sleep mode by pressing the powerbutton and only after a few seconds, the screen up-right showed "powered off". back to 2019.09.3 is ok.

**Comment by NiLuJe** [comment]
@Frenzie : Add some logging on the alarm setting side of things to see if something wonky happens?

**Comment by NiLuJe** [comment]
Possibly relevant: which FW versions are you all running? (@Frenzie and I are on the latest).

**Comment by Frenzie** [comment]
@xianren78 Thanks for the report.

Is that an H2Ov1 (from 2014) or v2? Could you also attach the crash.log? Which firmware versions are you guys on?

**Comment by NiLuJe** [comment]
Also, @gerhaher, does that happen with the device unplugged?

**Comment by gerhaher** [comment]
FW: 4.15.12920

> Also, @gerhaher, does that happen with the device unplugged?

Hmm, I'm not following....

It happens _after_ I charged the device, i.e. after I have unplugged the device.

**Comment by xianren78** [comment]
> @xianren78 Thanks for the report.
> 
> Is that an H2Ov1 (from 2014) or v2? Could you also attach the crash.log? Which firmware versions are you guys on?

v2 with latest  4.15 firmware. tomorrow i will upload the log.

**Comment by Frenzie** [comment]
@gerhaher So it's the unplugging that causes the wakeup?

**Comment by gerhaher** [comment]
Unplugging when device is on: nothing happens, i. e. device continue to be on

Unplugging when device is in sleep: powered off after a few seconds

**Comment by poire-z** [comment]
FWIW, on my kobo glo hd (where I use some personal tweak with that /sys/class/rtc/rtc0/wakealarm to have some kind of autostandby), I remember I got some superbogus behaviour when the battery reaches 100% (even without unplugging). At that point, my autostandby/autosuspend would keep getting triggered and rescheduled, and sleep and wakeup, resulting in a loop of wakeups. Haven't investigated (after this happened, I just remember to quit koreader and get back to KSM when charging).

**Comment by Frenzie** [comment]
@gerhaher 

> Unplugging when device is in sleep: powered off after a few seconds

The device has to wake up first before it can power down. :-)

Your log shows the suspend procedure initiated at 11:45:59, actually going to sleep at 11:46:14, and subsequently waking up a mere half minute later at 11:46:45. If we assume that 11:46:45 is the time of unplugging the power, apparently causing a wakeup, then that part would make sense. It still makes some kind of absurd sense if it's a scenario like @poire-z describes. Either way we woke up at 11:46:45.

However odd waking up at 11:46:45 may or may not be, how can a wakeup at 11:46:45 cause a scheduled shutdown at 8:47:00? That part makes no sense. I imagine it makes sense that 8:47 is the same as 11:47, assuming UTC+3, but what we're seeing is that our copy of the alarm we scheduled, the alarm as the system says it's scheduled, and the current time are all 8:47. This would all be perfectly regular if we had scheduled an alarm for 8:47 and woke up at 8:47. The only problem is that makes no sense.

Instead:

a. An alarm should've been scheduled for 72 hours from now. That's 8:45:59 in three days. Not 8:47:00 in one minute.
b. The current time at wakeup should've been 8:46:45, not 8:47:00.

Anyway, here's hoping the extra logs will provide some clarity.

**Comment by gerhaher** [comment]
Same thing happens to my Kobo Aura. 
Firmware: 4.8.11073
[crash.log](https://github.com/koreader/koreader/files/3612826/crash.log)

**Comment by Frenzie** [comment]
This is all exclusively in combination with unplugging the power cable?

**Comment by gerhaher** [comment]
> This is all exclusively in combination with unplugging the power cable?

Yeah.

**Comment by gerhaher** [comment]
> Assuming you're in UTC+3

Actually, I'm in UTC +2 according to https://time.is/sv/Gothenburg

**Comment by Frenzie** [comment]
In that case I guess your timezone isn't set up correctly. ;-) I doubt it matters on an ereader.

For example, here's my UTC+2 log from trying to trigger weird behavior with the power cord:

```
09/14/19-17:23:47 DEBUG Resuming...
09/14/19-17:23:47 INFO  Kobo resume: clean up after wakeup
09/14/19-17:23:47 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
```

The system clock is 15:25 in UTC.
```
# cat /proc/driver/rtc
rtc_time        : 15:25:14
rtc_date        : 2019-09-14
alrm_time       : 11:19:52
alrm_date       : 2019-09-16
alarm_IRQ       : yes
alrm_pending    : no
24hr            : yes
```

**Comment by gerhaher** [comment]
> In that case I guess your timezone isn't set up correctly. ;-)

In nickel it's correct: 
Time zone:  (UTC 2:00)

**Comment by Frenzie** [comment]
Out of curiosity, could you check the output of `cat /proc/driver/rtc`? Through SSH would be the easiest but the terminal emulator in KOReader would do the trick. I'm not really expecting to learn anything from it but you never know.

**Comment by gerhaher** [comment]
cat /proc/driver/rtc
rtc_time	: 15:55:15
rtc_date	: 2019-09-14
alrm_time	: 15:34:17
alrm_date	: 2019-09-17
alarm_IRQ	: yes
alrm_pending	: no
update IRQ enabled	: no
periodic IRQ enabled	: no
periodic IRQ frequency	: 1
max user IRQ frequency	: 64
24hr		: yes

**Comment by Frenzie** [comment]
Alright, so the alarm is indeed set correctly for three days from now. Maybe getWakeupAlarm and getWakeupAlarmSys are doing something wrong. If so, then 672d29fbcc3ff31b7459ef4486da7f2f42037a24 may have semi-fixed the problem by accident.

Btw, you can OTA update right now to generate slightly more verbose logs. I manually triggered a build.

**Comment by gerhaher** [comment]
Seems to be fixed now, I can't trigger it anymore.

In case you still want the crash.log:
[crash.log](https://github.com/koreader/koreader/files/3612953/crash.log)

**Comment by Frenzie** [comment]
It's mainly just broken slightly differently I'm afraid, due to the small oversight I fixed in the commit I mentioned. Right now it'll never shut down.

Anyway, thanks for testing. :-)
