### ISSUE TITLE
Chinese characters in UI not displaying

### ISSUE THREAD

**Issue by Mayonnnaise** [koreader/koreader#5381]
* KOReader version: v2019.09.3-13-g2a93e42_2019-9-15
* Device: Nova 
The Chinese characters in the UI are not showing. The device may be using another font as the default font for Chinese characters instead of Noto Sans CJK. I tried to put NotoSans-regular.ttf and NotoSansCJKsc-regular.otf under Storage/fonts but that didn't work.
![IMG_20190915_213804](https://user-images.githubusercontent.com/49610933/64922503-8d14de00-d802-11e9-8b94-b2cf7e86f388.jpg)

![IMG_20190915_214410](https://user-images.githubusercontent.com/49610933/64922467-3f987100-d802-11e9-92d4-eb093ff694a1.jpg)

**Comment by NiLuJe** [comment]
I can reproduce here, except I do have a large swath of the Noto family installed, so I'm not quite sure what's going wrong.

**Comment by cges30901** [comment]
Traditional Chinese document looks fine here, but Chinese filenames are not displayed correctly in file browser and UI.

**Comment by poire-z** [comment]
Same for me on my Android 6 phone updated this morning.
Probably because no trace of this fallback font in my phone's /system/fonts/ directory:
https://github.com/koreader/koreader/blob/6ac046c87781196d7a612d2438799da069015f0d/frontend/ui/font.lua#L81
and no font containing "CJK" in their name. There are tons of other NotoSans, and it seems they splitted that CJK font into individual fonts, as I have (as .otf, all the others are .ttf):
`NotoSansJP-Regular.otf`, `NotoSansSC-Regular.otf` `NotoSansTC-Regular.otf` `NotoSansKR-Regular.otf`.

**Comment by shincysl** [comment]
Same here for Japanese characters.

**Comment by zivilyyyn** [comment]
I think it is because the lack of system CJK font file. I tried to add a notosans font file in /system/fonts/ directory on my android tablet and the system menu could display properly.

**Comment by d3v-dev** [comment]
Same here for Korean characters.

**Comment by Frenzie** [comment]
Yes, it's CJK in general. I suppose for the short term we should just include the CJK fonts again, which is a bit unfortunate.

**Comment by poire-z** [comment]
I still do not see the chinese and japanese entries displayed correctly in the Languages menu.
If have this in logcat from time to time, and a bunch of these when I go into that Languages submenu, dunno if it gives some hint:
```
10-09 09:09:17.152  8751  8763 E KOReader:  #! Font  DroidSansFallback.ttf  ( DroidSansFallback.ttf ) not supported:  ffi/freetype.lua:96: Failed to load font './fonts/DroidSansFallback.ttf', freetype error code: 1
10-09 09:09:17.154  8751  8763 E KOReader:  #! Font  DroidSansFallback.ttf  ( DroidSansFallback.ttf ) not supported:  ffi/freetype.lua:96: Failed to load font './fonts/DroidSansFallback.ttf', freetype error code: 1
10-09 09:09:17.157  8751  8763 E KOReader:  #! Font  DroidSansFallback.ttf  ( DroidSansFallback.ttf ) not supported:  ffi/freetype.lua:96: Failed to load font './fonts/DroidSansFallback.ttf', freetype error code: 1
```
The resurrected NotoSansCJK is there, with the right size:
```
/data/data/org.koreader.launcher/files/fonts/noto # ls -la
     4377 Oct  9 08:54 LICENSE
   469180 Oct  9 08:54 NotoSans-Bold.ttf
   486980 Oct  9 08:54 NotoSans-BoldItalic.ttf
   485880 Oct  9 08:54 NotoSans-Italic.ttf
   468520 Oct  9 08:54 NotoSans-Regular.ttf
 17281332 Oct  9 08:54 NotoSansCJKsc-Regular.otf
   573576 Oct  9 08:54 NotoSerif-Bold.ttf
   614564 Oct  9 08:54 NotoSerif-BoldItalic.ttf
   599604 Oct  9 08:54 NotoSerif-Italic.ttf
   554236 Oct  9 08:54 NotoSerif-Regular.ttf
```
