### ISSUE TITLE
3 things about "Show hint for opened books in history"

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5383]
* KOReader version: v2019.09.3-12-g54568d4_2019-09-14/ 
* Device: KA1

#### Issue
1. The hint (the little triangle) is showed (for opened books) although the "Show hint..." is unticked.

2. It's always showed for (not opened) pdf's after extracting metadata. However, if you have "Detailed list...", the hint disappears when you leave the page. 
But If you have "Mosaic..." you need to purge to make it disappear. If you extract a pdf's metadata in Mosaic, and then change to classic mode, the pdf will be boldened (if you have "Show opened files in bold" enabled). 

3. It's unnecessarily showed on the History page.

**Comment by poire-z** [comment]
Mhhh, it's named "Show hint for opened books **in history**" :)

The idea is that we can always show them in file browser (because it's quite unobtrusive and useful) - and indeed, some may find them "unnecessarily showed on the History page", so this setting :) It works for me on the emulator.
So I guess that explains your 1) and 3).

While 2) might be a bug that I can reproduce, possibly a side effect of some other unrelated change, because I think that was working fine at the time.

**Comment by gerhaher** [comment]
Hehe, fair enough.  :-)
I'm OK with 1).
But I just found it puzzling with a hint for opened books.... on the history page. :-)

**Comment by poire-z** [comment]
Possibly #5100, although nothing jumps out at a quick glance, but I remember there were some tweaks to look at the docsetting for the complete/reading status. Any idea @NiLuJe ?
When purging and refresh cached book info, I indeed get a small metadata.pdf.lua created, containing just:
```
-- we can read Lua syntax here!
return {}
```

> But I just find it puzzling with a hint for opened books.... on the history page. :-)

So do I :) May be I thought that some other people would find it puzzling to not see the books fully similar in both FileBrowser and History view... or someone requested it, don't remember.

**Comment by poire-z** [comment]
Although it seems there is really no issue at all when doing the same steps with some EPUB.
So might be something pdfdocument/document related...

**Comment by poire-z** [comment]
So, possibly #5282, where it seems in `PdfDocument:init()` (which must be called by background extraction to get metadata), we call `convertKoptToReflowableFontSize()` which does:
https://github.com/koreader/koreader/blob/2a93e428a53b874e8b717be67f430aabbfafefce/frontend/document/pdfdocument.lua#L67-L69
which must create the directory and the empty metadata.pdf.lua.

Might just need to wrap like we do in a few other places (actually, only 2... thought there would be much more):
https://github.com/koreader/koreader/blob/2a93e428a53b874e8b717be67f430aabbfafefce/frontend/apps/filemanager/filemanagerbookinfo.lua#L58-L62
https://github.com/koreader/koreader/blob/2a93e428a53b874e8b717be67f430aabbfafefce/frontend/ui/screensaver.lua#L239-L245
