### ISSUE TITLE
some warning when opening a PDF (it's unnecessary)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#5385]
* KOReader version: (versions 2019 aug till now v2019.09.3)
* Device: Kobo Clara HD

#### Issue
whenever I open a PDF, there is a popup window saying 
"zoom to fit the page ... unexpected shifts while turning the page"
1) 2 seconds are not enough to read through all the warning and understand the tip;
2) it shows up every time I open (the same) PDF - why??? :) opening epubs and fb2s don't bring up any warning; the first misleading impression / idea is "what's wrong with PDF format??" :)))

This message on how to use koreader the most efficient way is very useful, so logic of this useful popup fits the best into "Hint of the day" concept, it's used in some MS Office applications. I suggest this hint should wait until user closes it and should have three buttons at the bottom of the dialogue;
1) "show again later"
2) "I understood, give me another hint tomorrow"
3) "never show me any hints, I'm happy already"

Following this concept, some other tips could be shown:
- "you can take a screenshot of any page using [your current taps setup]";
- "you can upload your e-books via sftp [set up here]";
- "you can send files from KOReader to KOReader on the same network [here is how]"
- "your default wiki language and UI lanugage are not the same; [set up here]";
- "your downloaded dictionaries 6 months ago, and 2 out of 20 were updated; [download updates]";
- "you didn't send last crash logs to the developers [do it now]";

a few versions before the same popup for PDFs told something about OCR that I also didn't have enough time to read through and grasp :)

#### Steps to reproduce
open any PDF and you will get this popup window for 2 seconds

**Comment by pazos** [comment]
> This message on how to use koreader the most efficient way is very useful [...]

Great, we are always looking for people which could help documenting KOReader functions. Are you willing to help @worldexplorer? You can start by reading [open doc issues](https://github.com/koreader/koreader/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Adocumentation) and editing the wiki adding the information you know and don't find online. 

I have the long term goal of writting a KOReader user guide. We started by making the README more user friendly and adding installation guides on (until then) undocumented platforms. Is a long term goal and even when I'm using KOReader for the last 5 years I won't be able to document the 10% of the program features as I don't use most of them.

So, please help.

**Comment by worldexplorer** [comment]
![Reader_2019-Sep-16_002037](https://user-images.githubusercontent.com/4983083/64928809-bc891200-d825-11e9-87f8-22acbb415fa4.png)

**Comment by Frenzie** [comment]
> This message on how to use koreader the most efficient way is very useful, so logic of this useful popup fits the best into "Hint of the day" concept, it's used in some MS Office applications. 

It's a specific warning in response to a specific user configuration that users were confused about. But you're definitely right that it should have some buttons. :+1: 

> a few versions before the same popup for PDFs told something about OCR that I also didn't have enough time to read through and grasp :)

The OCR popup only appears when you select some text in a document without a text layer and never disappears by itself without user interaction.

**Comment by Frenzie** [comment]
@poire-z @robert00s @NiLuJe @pazos 

I'm thinking of extending ConfirmBox to optionally include some toggles. Any objections or requirements you can think of? It looks like this (quick visual prototype only):
![Screenshot_2019-09-16_17-02-45](https://user-images.githubusercontent.com/202757/64969266-d8cb9400-d8a3-11e9-8479-e79af8108dac.png)

I was thinking of calling it using something like:

```lua
ConfirmBox:new{
            text = "Something something continuous.",
            cancel_text = _("Continuous"),
            ok_text = _("Page"),
            toggles = {
                [1] = {text = "Don't repeat", callback = function() saveSetting("dontrepeat") and check/unCheck() end}
            },
        })
```

**Comment by poire-z** [comment]
No objection (as long as we can keep the regular ones :)

For some past ideas about ConfirmBox, you can have a look at https://github.com/koreader/koreader/issues/3763#issuecomment-373689835 and at the bottom of https://github.com/koreader/koreader/issues/3757#issuecomment-374201294.
Quick reread, and it looks like it could make sense, when choosing `don't repeat` to set which of the button is to be chosen (with `Hold` on them ? like we are used to hold on stuff to make it a default) - and to find a way to unchoose `don't repeat` :)
(and/or have that don't repeat thing directly handled by ConfirmBox.lua with just a `id=` from the calling widget.

**Comment by robert00s** [comment]
No objection. Looks pretty nice.

**Comment by NiLuJe** [comment]
@poire-z : I'd KISS, with a simple option somewhere that simply makes *all* of the previously hidden popups show up again.

**Comment by Frenzie** [comment]
@poire-z Thanks, for the links.

> Quick reread, and it looks like it could make sense, when choosing don't repeat to set which of the button is to be chosen (with Hold on them ? like we are used to hold on stuff to make it a default) - and to find a way to unchoose don't repeat :)

Unless you mean an essentially hidden hold_callback (which probably isn't great for discoverability) I don't really follow why you'd want to tick a box *and* hold?

**Comment by poire-z** [comment]
> I don't really follow why you'd want to tick a box and hold?

Not both obviously :) But holding could replace the tick box.
I agree it's not great for discoverability, but it's what we use elsewhere (not great for discoverability there either) - so it makes a single great discovery to discover to be used everywhere! :)

Might also depend on what the Confirmbox is about:
With a Cancel|OK , it's kind of obvious the tick box will make it always OK when not showing.
For other where there is a real choice (Continuous|Page), there have to be a default when not showing. Which will it be? The obvious one (if there is one?), the intentional choice I made elsewhere that lead up to that ConfirmBox appearing, or the one I'm just gonna Tap after I ticked the box? Not super obvious either.

But even the Hold solution is not obvious: shoud it make it as default, and go proceed like if tap was tapped? Show an InfoMessage with a hint of what will happen from now on, and how to revert that?

**Comment by Frenzie** [comment]
> For other where there is a real choice (Continuous|Page), there have to be a default when not showing. Which will it be?

For the specific example it's probably better to use something like Cancel|Switch to page mode. I focused on displaying something that looked right on a screenshot but it's only fleshed out in the "this is what an added CheckButton would look like" sense.

> not great for discoverability there either

True, but there's an established precedent of menus supporting the context action (right click or context menu button), and there's no elegant alternative. A separate (global) settings screen could potentially come in useful.

**Comment by Frenzie** [comment]
Fixed in <https://github.com/koreader/koreader/pull/6131>. Also see <https://github.com/koreader/koreader/pull/5170#issuecomment-623963197>.
