### ISSUE TITLE
Suggestion: upload books via network

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#5386]
Hi guys,
I'm very grateful for koreader that you develop and I use a lot;

sending files (epub/fb2) to kobo via wifi would help a lot, but
- I don't have my own FTP server to use send-to-eBook plugin;
- zsync requires an IP-exposed host;
- calibre is a nightmare for its desktop piece;

My suggestions for a koreader "file delivery plugin", are:

1) sftp server setup on the kobo side + sftp client on my laptop connected to the same wifi - is probably the easiest way as SSH server just needs to be turned on in the koreader menu; this method requires a comprehensive manual and support / testing from koreader developers; I can help testing the manual, for sure;

2) may be you could integrate the Telegram api into koreader to send books to myself via Telegram's "Saved Messages"? or even the whole Telegram UI can be reproduced on simple widgets? (besides P2P messaging and file transfer, I could read news on e-reader instead of a cellphone);
> CAVEAT: Telegram was attempted to be blocked in Russia, but next Telegram update contains another hack to bypass the blocked IPs; last week on my android phone I needed to do a transparent proxy and route Telegram traffic though Orbot (called "VPN mode" in Orbot); so it's not all that great with Telegram API, but still doable;

3) may be setting up a Google Drive / Dropbox account (with typing my Google/Dropbox password every time) on kobo side with the ability to download (and upload?) files - would be an easy path? File Transfer APIs suggested by @pazoz:
https://github.com/public-apis/public-apis/blob/master/README.md#cloud-storage--file-sharing

4) using any short-term online file storage, a user might upload a book and type in kobo plugin the tiny URL of that file, ?... I used https://www.file.io/ - they have an API disclosed on their page https://www.file.io/#one
...but here are more to choose from:
https://www.geckoandfly.com/25928/anonymous-file-sharing-storage/
https://www.makeuseof.com/tag/dropbox-quickest-ways-share-file-si/
POSSIBLE IMPLEMENTATION: in the plug-in, the URL user types and the actual download button on the page should be identified and just a HTTP GET should be sent to put the downloaded file in the user-chosen folder....

5) it can be some simple own server implementation like this:
https://sourceforge.net/projects/filedrop/files/Filedrop_1.x.x/
https://github.com/joshdiaz/anfildro
... with:
- file limit 10Mb long per originating IP per day,
- auto-deletion within 24 hours
- anti-flood protection (nginx?)
- "large uploads expire sooner" algo implemented
... we can pay for the hosting $30 yearly I guess...

6) an IMAP mail checker method: when I could send a book to myself, move it into a specific IMAP folder; on a kobo, a lua-implemented email reader would check that IMAP folder and, when a ebook format (epub / fb2 / pdf) file appears in that IMAP folder, it gets that file automatically ("ask me every time") and downloads it into a specific folder of my kobo when I connect to wifi:
https://github.com/nodemcu/nodemcu-firmware/blob/master/lua_examples/email/read_email_imap.lua

Here is a list of public apis:https://github.com/toddmotto/public-apis/blob/master/README.md
_Originally posted by @pazos in https://github.com/koreader/koreader/issues/4432#issuecomment-450579686_

_Originally posted by @pazos in https://github.com/koreader/koreader/issues/4432#issuecomment-520239760_

**Comment by Frenzie** [comment]
> sftp server setup on the kobo side + sftp client on my laptop connected to the same wifi - is probably the easiest way as SSH server just needs to be turned on in the koreader menu; this method requires a comprehensive manual and support / testing from koreader developers; I can help testing the manual, for sure;

This is more of a stub but… https://github.com/koreader/koreader/wiki/SSH

**Comment by worldexplorer** [comment]
yes it IS more like a stub.

> "look like dropbear doesn't support sftp" on May 15, 2018
> https://github.com/koreader/koreader/pull/3842#issuecomment-389261216
> 
> "Cross Compiling SFTP-Server DropBear for ARM - BeyondLogic"
> https://wiki.beyondlogic.org/index.php?title=Cross_Compiling_SFTP-Server_DropBear_for_ARM
> 
> "Unable to cross-compile openSSH for arm, zlib missing"
> https://unix.stackexchange.com/questions/315605/unable-to-cross-compile-openssh-for-arm-zlib-missing

yes I tried enabling SSH but logging in failed; SFTP is too far in my dreams :)
I created this SSH login issue
https://github.com/koreader/koreader/issues/5394

PS when you exit to Koreader File Browser, in the top menu under screwdriver icon, there is "Cloud storage" popup with Dropbox / FTP / WebDAV - this looks promising...

**Comment by Frenzie** [comment]
@worldexplorer The wiki entry is just me briefly describing how I put files on my H2O all the time. It's a stub because it was copied from a quick note.

**Comment by Frenzie** [comment]
PS I've been doing it that way for years, it's just that more recently I switched to the Dropbear included in KOReader.

**Comment by Frenzie** [comment]
I'll close this now since it SSH seems to work satisfactorily (see #5394), with an added note that @dontcrash intends to add Google Drive to cloud storage.
