### ISSUE TITLE
Font size for menu items: size oscillation

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5388]
Output font sizes for menu items in filemanger in classic mode oscillate between two sizes, when you choose different font sizes that is above what is limited by filename length etc. 
Not the biggest problem in the world, but I suppose, if anyone is interested, the algorithm can be improved. :-)

Anyway, see pictures below (Items per page = 24 on my KA1).

Font size = 12
![1FileManager_2019-Sep-10_184813](https://user-images.githubusercontent.com/32645430/64765723-f2d44200-d544-11e9-873c-a31a16554583.png)
Font size = 13
![1FileManager_2019-Sep-10_184833](https://user-images.githubusercontent.com/32645430/64765728-f7005f80-d544-11e9-8f78-54358e516f5c.png)
Font size = 14
![1FileManager_2019-Sep-10_184849](https://user-images.githubusercontent.com/32645430/64765735-fbc51380-d544-11e9-95ec-c35b4a0994fc.png)
Font size = 15
![1FileManager_2019-Sep-10_184903](https://user-images.githubusercontent.com/32645430/64765747-041d4e80-d545-11e9-9f12-8a75fd4cabf7.png)
Font size = 16
![1FileManager_2019-Sep-10_184919](https://user-images.githubusercontent.com/32645430/64765778-10091080-d545-11e9-8a99-0300b57a7002.png)
Font size = 17
![1FileManager_2019-Sep-10_184931](https://user-images.githubusercontent.com/32645430/64765785-139c9780-d545-11e9-92c6-cdc5b8d5cead.png)
Font size = 18
![1FileManager_2019-Sep-10_184944](https://user-images.githubusercontent.com/32645430/64765793-17c8b500-d545-11e9-97f5-49c693fa6449.png)
Font size = 19
![1FileManager_2019-Sep-10_185000](https://user-images.githubusercontent.com/32645430/64765798-1ac3a580-d545-11e9-8f05-a66eb0ea8236.png)
Font size = 20
![1FileManager_2019-Sep-10_185015](https://user-images.githubusercontent.com/32645430/64765812-1eefc300-d545-11e9-8cd2-ddc0487f575a.png)

**Comment by Frenzie** [comment]
What I see on the picture is that it reduces the text size slightly to show as much text as possible. It's basically form vs function.

**Comment by poire-z** [comment]
The even font size seems to go lower size than the odd ones...
Might be this `-2` decrement and/or the scaleForDpi rounding?
https://github.com/koreader/koreader/blob/5bc9700c2472e39869d6ce041ed2a6683c7f2235/frontend/ui/widget/menu.lua#L308-L311
The `-2` was I think to skip an iteration and save some processing, but it may be the cause of that?
Time to check what it does with `-1` instead??

**Comment by gerhaher** [comment]
> Time to check what it does with -1 instead??

No oscillation anymore. And I see no side effects.

**Comment by Frenzie** [comment]
> The -2 was I think to skip an iteration and save some processing

Makes sense, but in that case it could maybe implement a logic similar to https://github.com/koreader/koreader/commit/ca6c7316e6fa550f511db72f9c1cdefd1775a2fe#diff-464041c4629c9eb64998fc6c752a25b2?

In pseudo-code, something like:
```lua
local iter = -2
for/while i-iter do
  if fits then
   iter = -1
   i = i+1
end
```

That way you'd still reach your goal faster by skipping a bunch of steps. Then again, given that we're talking about font size changes, how many max steps do we want to differ from the main size anyway?

**Comment by poire-z** [comment]
> how many max steps do we want to differ from the main size anyway?

I dunno, I guess as much as it is necessary to display the full filename :)
The code is even supposed to switch to 2 lines display at some point.
And there's another buggy thing on the screenshots: on the even ones, the font size for long filenames has become smaller (which is what we want), but the filename is truncated too short ("Making of Americ..." while there is enough room to display more chars).

(Anyway, was just suggesting a possible culprit, but I'm not keen on having to dig into that code :) @robert00s may be ? as you introduced this resize/wrap enhancements?)

**Comment by robert00s** [comment]
@poire-z 
Ok, I'll look at it.

**Comment by poire-z** [comment]
I'm refactoring a bit of text-related stuff, so I'm taking over your assignment @robert00s if you haven't started it :) Have you?

**Comment by robert00s** [comment]
@poire-z 
I have almost done. I will do PR today :)
So wait a few hours :)
