### ISSUE TITLE
Text Editor (copy/paste & lagging)

### ISSUE THREAD

**Issue by Yyatiko** [koreader/koreader#5392]
- KOReader version: v2019.08
- Device: Kobo_pika

**Issue**

Hi,

1. It would be nice to be able to **paste some text** in the **text editor**. I use the text editor quite a lot because I don't have a computer when I live in the forest.. ;-) Sometime, I want to copy some text from a document in the text editor.

2. Also, after typing about 10 lines of text in the text editor, the device start to **lag and eventually crash**. A bit surprising the first time when you did't save your text... ;_) 
What I found to workaround is to save after every sentence and to restart Koreader every 3 minutes. 

3. Also, after about 300 lines of typing, the text editor keep crashing and there is **no way to add any more text**. I usually then start with another empty file. 

Thanks for your help !

(4. Just an extra question unrelated to text editor: I sometime have to go on the Nikel side to go on the internet browser to download a PDF, check a website or even my email. Is their any project in Koreader to implement a **web browser** or a **email widget** ?)

**Comment by Frenzie** [comment]
> It would be nice to be able to paste some text in the text editor.

Doesn't long press work?

> Also, after typing about 10 lines of text in the text editor, the device start to lag and eventually crash.

Sounds pretty bad. :-/

> Just an extra question unrelated to text editor

A web browser is pretty much the most complicated piece of software there is. Nickel profits from the fact that QtWebKit allows you to randomly embed a reasonable web browser component more or less for free (besides disk space). It could even be pretty useful if they had added some buttons to page up/down.

Also see: https://github.com/koreader/koreader/issues/3948 https://www.mobileread.com/forums/showthread.php?t=313154&highlight=web+browser

> email widget

Almost as difficult. ;-)

**Comment by poire-z** [comment]
> It would be nice to be able to paste some text in the text editor

This works for me:
- select text in the document: hit Copy in the dialog (where you see Highlight, Wikipedia, Translate...) - the dialog does not react, but that text is copied. Close that dialog
- go into Text editor, open your file, scroll around to move the place you want to paste at into view, and just **Hold** at this place... and it should be pasted there :)

> Also, after typing about 10 lines of text in the text editor, the device start to lag and eventually crash. 
> Also, after about 300 lines of typing, the text editor keep crashing and there is no way to add any more text. 

Well, that's unfortunate, but our TextBoxWidget (that's used to display editable text) is a bit on the memory hungry side (still even after #3904)...
Can't find out how much internal memory your Kobo Touch 2.0 has. My GloHD has 512M, and it's ok, but I don't write as much as you do. If your Touch has 256M, well, you may hit that limitation quicker than us...
You might want to add Memory usage to your status/footer, so you can see how much it increases when editing and back to reading - so you can see at which point things get messy, and you can react to that and restart just before it reaches that level.

I haven't been able to make it less hungry... and our Garbage Collector does not seem to help much.

**Comment by Yyatiko** [comment]
You guys are incredibly fast !!! 
I get on the computer only once a week for 2 hours... :_)

And thanks for the trick for **holding to copy**,  it works ! How could I have known... ;-)

And I had the memory usage to the status bar (says now : M:104...) we'll see.

Thank you very much

**Comment by Frenzie** [comment]
@poire-z 
> Can't find out how much internal memory your Kobo Touch 2.0 has.

No kidding. it doesn't seem to be mentioned anywhere.

**Comment by NiLuJe** [comment]
This is going to be fun :D.

Knowing that the Touch 2.0 is codenamed Pika, we can pinpoint its PCB ID as E60Q9*.
Armed with the knowledge that it's a Mk. 6, we can look inside the latest FW update:

```
Archive:  kobo-update-4.17.13651.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 95273678  09-14-2019 00:13   KoboRoot.tgz
     1007  09-14-2019 00:13   manifest.md5sum
        0  09-14-2019 00:13   upgrade/
        0  09-14-2019 00:13   upgrade/mx6sl-ntx/
   221808  09-14-2019 00:13   upgrade/mx6sl-ntx/u-boot_lpddr2_256-E60Q90-LPDDR2.bin
   234552  09-14-2019 00:13   upgrade/mx6sl-ntx/u-boot_lpddr2_512-E70Q00-LPDDR2.bin
  2333100  09-14-2019 00:13   upgrade/mx6sl-ntx/uImage-E60Q90
     9474  09-14-2019 00:13   upgrade/mx6sl-ntx/ntxfw-E60QM0.bin
   234520  09-14-2019 00:13   upgrade/mx6sl-ntx/u-boot_lpddr2_512-E60QM0A-LPDDR2.bin
   221800  09-14-2019 00:13   upgrade/mx6sl-ntx/u-boot_lpddr2_512-E60Q90-LPDDR2.bin
  2391364  09-14-2019 00:13   upgrade/mx6sl-ntx/uImage-E70Q00
  2391364  09-14-2019 00:13   upgrade/mx6sl-ntx/uImage-E60QL0
  2401676  09-14-2019 00:13   upgrade/mx6sl-ntx/uImage-E60QM0A
      512  09-14-2019 00:13   upgrade/mx6sl-ntx/ntxfw-E60QM0.bin.header
   234552  09-14-2019 00:13   upgrade/mx6sl-ntx/u-boot_lpddr2_256-E60QL0-LPDDR2.bin
  2421172  09-14-2019 00:13   upgrade/mx6sl-ntx/uImage-E60QM0B
   238288  09-14-2019 00:13   upgrade/mx6sl-ntx/u-boot_lpddr2_512-E60QM0B-LPDDR2.bin
---------                     -------
108608867                     17 files
```

And now we're faced with a dilemma: there are two of those! One is 256M, the other 512M.

That's because the Glo HD uses the exact same board, but with a different panel...

I'm going to assume the Touch 2.0 is the 256M one, and the Glo HD is the 512M one.

**Comment by NiLuJe** [comment]
Otherwise, if you have shell access to the device:

`ntx_hwconfig -s -p /dev/mmcblk0 RamSize`

**Comment by poire-z** [comment]
Or "something memory" in Hamburger menu > System statistics :)

**Comment by poire-z** [comment]
Closing as copy/paste in TextEditor/InputDialog as improved a lot.
May be the memory usage has gotten better with the switch to xtext. Re-open if still an issue (with more info about memory usage before/near the crash).
