### ISSUE TITLE
Status bar is offset when screen orientation changes

### ISSUE THREAD

**Issue by allati** [koreader/koreader#5395]
* KOReader version: 2019.09.3
* Device: Kobo Forma

Since 2019.09.3 status bar is offset left or right when screen orientation changes.

In status bar I have enabled progress bar and "pages left in chapter". When KOReader is launched, status bar is always in correct position. If KOReader is launched in portrait orientation and then device is rotated so that orientation is changed to album, then whole status bar moves to the right for ~3 cm (so that "pages left in chapter" part is far beyond screen edge). If KOReader is launched in album orientation and then rotated into portrait, then status bar moves to the left for the same amount.

**Comment by robert00s** [comment]
Same on emulator. I'll try to fix it.
