### ISSUE TITLE
[FR] Enable/disable corner hold

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#5401]
My problem starts with my dislike for blank margins.
Because of using 0pt margin all around, it is impossible to select a word in a corner if I have assigned an action for when holding that corner.
Most of the time, I have the same problem if I try to select a word from the last line of the page (the skim dialog pops up).

The only solution I could think of, is to have a way to toggle these shortcuts.
It could be a menu entry or even better a gesture.

**Comment by NiLuJe** [comment]
Is that on a current version? IIRC, everything's neuterable in the Gesture manager.

**Comment by poire-z** [comment]
I think he wants a new gesture action: `Neuter/unneuter hold corners`.
So, when you need to highlight some words in the corners, you just draw a gesture (eg. a circle), and hop, you can hold on words. When done, draw it again and corners get their specificied gestury power back.

**Comment by noembryo** [comment]
Exactly.
I can always disable the specific corner hold, select the word and re-select the desired action again (it might be one on the 7th page!), but that's a lot of clicks.. :o)

Another way (not so fast as a gesture) is to have long pressing the `Hold corner` menu item to make the toggle...

**Comment by Frenzie** [comment]
Could be a bit confusing… perhaps more something for #5079? (Gesture/action to toggle profile x.)

**Comment by noembryo** [comment]
A profile with `Hold corner` actions and another profile with out?
Does that mean that when you change a specific action you have to update the profile too?

**Comment by Frenzie** [comment]
That depends on which direction #5079 goes in. The way it's currently written you'd just save a backup of the current action before setting the corners to pass through.

But "Disable something or other" could also just live next to "Disable double tap". Just brainstorming.

**Comment by poire-z** [comment]
Given how easily Hold corners can conflict with other regular hold actions on the book content, I think `Toggle hold corners gestures` deserves to be a gesture action (let's place it at the bottom of the 7th page of our actions if it's that confusing :).
(I personally never bothered with the hold corners gestures just because of that - and I'll probably continue not using them no matter what :)

**Comment by Frenzie** [comment]
Hold corners doesn't jive with me either. Occasionally it might get in the way but mainly it just feels a bit slow and awkward.
