### ISSUE TITLE
annotations not exported

### ISSUE THREAD

**Issue by milmike0** [koreader/koreader#5408]
* KOReader version: Starling
* Device: PW2, firmware 5.4.3.2

Hi.
 Thanks for all your work on koreader. It's great.

After I highlight  a few sentences of a PDF, I will occasionally edit it and add a (usually moronic) comment. These comments are visible in the bookmarks but not in the HTML file created by Evernote. This seems odd.

When I look at the metadata.pdf.lua I can see these comments under the section ["test"] but not under the section ["notes']. I'm not a programmer so I don't really know what this means.

I have three questions.

1. Is this behavior peculiar to Kindle devices?
2. If I wanted to copy all notes could I do it directly from the Bookmarks folder when connected to my PC? Where is  this folder and can I open it? 
3. Would it be a PITA to make Koreader copy all notes directly from the bookmarks  or from the ["test'] section to the Evernote HTML file? (Again I'm not a programmer, so have a good laugh at this one if you want).

Thanks thousands.

**Comment by Frenzie** [comment]
> Is this behavior peculiar to Kindle devices?

Unlikely.

> If I wanted to copy all notes could I do it directly from the Bookmarks folder when connected to my PC? Where is this folder and can I open it?

There'll be a `.sdr` folder with the same name as the document. That contains all the data related to the document. Also see https://github.com/noembryo/KoHighlights/

> Would it be a PITA to make Koreader copy all notes directly from the bookmarks or from the ["test'] section to the Evernote HTML file? (Again I'm not a programmer, so have a good laugh at this one if you want).

Probably not but I don't use Evernote.

**Comment by milmike0** [comment]
Thank you.

Just a note that this is really the same problem as noted by maximus83 on his kobo on 1-26-19.

**Comment by Frenzie** [comment]
Do you mean this is a duplicate with an existing issue?

**Comment by milmike0** [comment]
Yes. I had tried to research it  before starting a new thread but could not find anything. When I noticed that you added the plugin label it gave me the hint to look under "Evernote plugin" where I found the thread by maximus83.

**Comment by Frenzie** [comment]
Ah, you mean [this thread](https://www.mobileread.com/forums/showthread.php?t=314688&highlight=Evernote+plugin) on the forum. Thanks.

There's currently some movement in #5086, so perhaps @kereviz would be interested in looking at basic shared functionality after Joplin support is finished.

**Comment by milmike0** [comment]
That is the  correct thread. Since they are duplicates, I'll keep on eye on #5086, and close this thread, unless you think there's any reason to keep it open.

**Comment by Frenzie** [comment]
A duplicate with the forum doesn't matter. Depending on the specifics it is often preferred, but since this is more of a forum topic than a GH issue closing it seems appropriate enough. :-)
