### ISSUE TITLE
DMINIBAR_ advanced settings are not applied

### ISSUE THREAD

**Issue by derungs** [koreader/koreader#5411]
* KOReader version: v2019.09.3
* Device: Android, emulator

#### Issue
Advanced settings DMINIBAR_CONTAINER_HEIGHT, DMINIBAR_FONT_SIZE, and DMINIBAR_HEIGHT have no impact on status bar.

#### Steps to reproduce
Go to Advanced settings menu, set DMINIBAR_FONT_SIZE to 40 and DMINIBAR_CONTAINER_HEIGHT to 140.
Open an ebook (epub format).
**Expected**: large white space at the bottom, large font for pages.
**Actual**: font size and container size are still 14 px.

##### `crash.log` (if applicable)
n/a

**Comment by Frenzie** [comment]
Note that if you exit the emulator *as if* it were a device it'll save the settings just fine. The fact that Alt+F4 or the X doesn't necessarily save all settings is a known issue, although I can't find it right now because it probably has a deceptive issue title.

Your Android problem may be something similar, or an entirely unique Android issue.

**Comment by Frenzie** [comment]
@derungs Could you clarify precisely what issue you have in the emulator (as well as Android) and how you're triggering it? As you can see in https://github.com/koreader/koreader/pull/5412#issuecomment-533910384 it seems to work just fine. Of course you need to restart first, as prompted.

**Comment by derungs** [comment]
@Frenzie Took me a while to identify the broken behaviour, see #5418.

**Comment by derungs** [comment]
If you don't want advanced settings immediately applied, I suggest to close this issue here.

**Comment by Frenzie** [comment]
Closing then. If you're going to change one of the advanced settings to be immediately applied you should simultaneously migrate it away from advanced settings. ;-)
