### ISSUE TITLE
Can't tap on confirmbox when keyboard shown

### ISSUE THREAD

**Issue by mustafa292** [koreader/koreader#5415]
When LoginDialog:onShowKeyboard called when there is a Confirmbox on the screen, Comfirmbox stays on screen (since it has .modal = true) but events won't propagate to it. Instead all events go to keyboard or login dialog that called keyboard. To see it in effect you can look at evernote login or kosync login. When you click to login, wi-fi dialog pops up but you cant accept or dismiss it. Keyboard and login dialog at bottom still works. I tried isolate the problem as much as I can in this [wbuilder.lua](https://gist.github.com/kereviz/971261625e617f5d8128e2e40520c13f) .

 [to see in gif ](https://postimg.cc/QByXwxzw)

First I thought it was simply two modal widgets clashing but this happens even when I set VirtualKeyboard's .modal = false. So when only login dialog called after Confirmbox everything is fine, Confirmbox still on top of the window_stack and it responds. Only calling :onShowKeyboard stops Comfirmbox responding; VirtualKeyboard and LoginDialog responds as they are .is_always_active widget's. It doesn't move Confirmbox from top of the stack (i think, since it is on top of screen and keyboard responds when is_always_active widgets called in UIManager:sendEvent, not when toplevelwidget called)).  

So i'm confused, and it is possible the paragraph above doesn't make any sense :P . 

There is two workarounds to this .

1- simply call NetworkMgr:checkconnectivity after :onShowKeyboard. But this isn't how modal widgets works, they should be on screen until user responds. So this takes away advantage of ConfirmBox being modal.

2- make ConfirmBox.is_always_active true, but I don't truly understand what is exactly the aim of that flag.

Could this have any relation to VirtualKeyboard inheriting from FocusManager?

**Comment by Frenzie** [comment]
I don't quite have time to fully comprehend what you wrote atm, but I'll just drop this quick link.

http://koreader.rocks/doc/topics/Events.md.html

> When you call UIManager:show on a widget, this widget will be added to the top of the UIManager._window_stack. Events are sent to the first widget in UIManager._window_stack. If it is not consumed, then UIManager will try to send it to all active widgets (widget.is_always_active equals true) in the _window_stack.

**Comment by mustafa292** [comment]
OK, I don't know what i was thinking at that moment but reason of this problem is actually simple. And a comment on code explains it clearly.  
https://github.com/koreader/koreader/blob/27de8d9bdf088791558d44513df9d4033cb10e15/frontend/ui/uimanager.lua#L697-L700

When VirtualKeyboard is drawn, ConfirmBox gets pushed to lover level of window stack. With other widgets this doesn't happen, ConfirmBox stays on top since it is modal. But this time UIManager has two modal widgets and it sends event to only second one. 

Also it sends events that VirtualKeyboard didn't consume to LoginDialog since it sets property is_always_active to true. This creates a behaviour that you can tap on a widget that is not on screen.

Here is my understanding of how window stack looks like:
---VirtualKeyboard     -modal
---ConfirmBox            -modal
---LoginDialog            -always_active

Checking modal widgets on loop that checks always active widgets solves this,

**Comment by Frenzie** [comment]
Sorry, I completely forgot to read it in more detail at a later moment. If you found a solution to the problem you identified, please PR it! :-)

**Comment by Frenzie** [comment]
Fixed by #5452 I believe? Please let me know if I'm mistaken.
