### ISSUE TITLE
Dictionary order

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#5417]
This is just a question:
Is there a way to change the Dictionary order?

Just added some more dictionaries to KOReader.

My problem is that I can not re-arrange them the way I like.
They _do_ change positions somehow, but I think it has to do with the dict's folders creation date(?)

Now, I know that I can make one the default for the current book, but..

1. I would like to set the default for the entire program, and
2. the way it is now configured:
    - Start with the second dict (my default)
    - Go to first
    - Go to second again (can I skip this?)
    - Finally go to third

I must be missing something here, because all those years I was using just one dictionary, so I don't have much experience with them.. :o)

**Comment by poire-z** [comment]
Seriously ?! :)

![image](https://user-images.githubusercontent.com/24273478/65437411-07a5b500-de24-11e9-82e9-72d035f988e1.png)

**Comment by poire-z** [comment]
Some notes also on the Wiki: https://github.com/koreader/koreader/wiki/Dictionary-support
Technical details in https://github.com/koreader/koreader/issues/4504#issuecomment-457352313.
(So, beware that that trick may not always work - the inode ordering can sometime not follow the order you put things in it - might help to delete the original dict dir and recreate it to start from a fresh inodes chain.)

**Comment by Frenzie** [comment]
Maybe the new sorting widget by @robert00s could be used here? ;-)

**Comment by poire-z** [comment]
That new sorting widget isn't smart enough yet to code in C and patch sdcv to make it accept some ordering hints :)

**Comment by Frenzie** [comment]
Oh, sdcv doesn't care about the order of arguments or something like that? Never mind then (for now). :-)
