### ISSUE TITLE
Advanced settings are not saved on exit from opened book

### ISSUE THREAD

**Issue by derungs** [koreader/koreader#5418]
* KOReader version: 2019.09.3-30-gbcceb946_2019-09-22
* Device: emulator, tolino (android)

#### Issue
Modified advanced settings are not stored when you exit koreader from the reader, that is, from an open book. When you exit from the file manager, the save dialog pops up and the advanced settings are stored.

#### Steps to reproduce
  * Change advanced settings.
  * Open a book.
  * Exit koreader.
  * Start koreader.

**Observed**: The advanced setting has the old value.
**Expected**: The advanced setting has the new value.

**Comment by Frenzie** [comment]
Makes sense (or rather, that's what the code does). The entire workflow for saving advanced settings is pretty weird imho.

**Comment by derungs** [comment]
I could move the "save/don't save" dialog to `filemanagersetdefault`, and pass the "real" close function as a callback rather than the "save/don't save" dialog function.
That would to some degree unweird the save workflow.

**Comment by Frenzie** [comment]
Sounds good to me. :+1:

**Comment by derungs** [comment]
On it, the idea seems to work (once I fixed my rookie mistake with lambdas).

**Comment by NiLuJe** [comment]
Here's me eating humble pie for saying "every sane exit workflow is wrapped in tat check" just yesterda :D.

Hmm, pie! :cake:

**Comment by derungs** [comment]
Two questions:
* ReaderMenu seems to use lfs without explicitly setting it. Do I miss something or should I just require lfs at the top of the file?
* What does OTAManager do? It calls exitOrRestart, but I haven't discovered a way to trigger it.

**Comment by Frenzie** [comment]
> ReaderMenu seems to use lfs without explicitly setting it. Do I miss something or should I just require lfs at the top of the file?

It's not a pure Lua module but a library, so it doesn't have any functional consequences. If you think it should be enforced as a code style then you can remove the exception from `.luacheckrc`. The current situation is probably primarily a case of harmless legacy and less a case of purposeful consideration.

> What does OTAManager do? It calls exitOrRestart, but I haven't discovered a way to trigger it.

OTA updates are only for embedded devices. On Android it merely starts the download of a newer package if available.
