### ISSUE TITLE
Reflow isn´t working.

### ISSUE THREAD

**Issue by Eduardomb22** [koreader/koreader#5434]
* KOReader version:  v2019,09.3-42
* Device: ppw2

#### Issue
Reflow isn´t working again, I click and the koreader crashs, Crop is working fine for me,
Do you guys need the crash.log?

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/3665650/crash.log)

**Comment by NiLuJe** [comment]
Yes, we definitely do...

**Comment by Eduardomb22** [comment]
It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 09/28/19-12:19:09
 [*] Version: v2019.09.3-42-ga934d2d_2019-09-27

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 6684672
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 1088
FB: xres         : 1072
FB: xres_virtual : 1088
FB: yres         : 1448
FB: yres_virtual : 6144
FB: bpp          : 8
09/28/19-12:19:12 INFO  initializing for device KindlePaperWhite3
09/28/19-12:19:12 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[ko-input] Forked off fake event generator(pid:8064).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
09/28/19-12:19:16 INFO  opening file /mnt/us/documents/Informativos Dizer o Direito/Informativos STJ 2019-2017 652-598.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
09/28/19-12:19:21 INFO  Loading plugins from directory: plugins
09/28/19-12:19:21 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
09/28/19-12:19:21 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
09/28/19-12:19:22 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
09/28/19-12:19:22 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
09/28/19-12:19:22 INFO  setting zoom mode to contentwidth
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
source page (0,0) - (595,841)
source page bgcolor 192
./luajit: frontend/ui/widget/toggleswitch.lua:198: attempt to index field 'args' (a nil value)
stack traceback:
	frontend/ui/widget/toggleswitch.lua:198: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:259: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:88: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:106: in function 'handleEvent'
	frontend/ui/uimanager.lua:674: in function 'sendEvent'
	frontend/ui/uimanager.lua:46: in function '__default__'
	frontend/ui/uimanager.lua:1014: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1075: in function 'handleInput'
	frontend/ui/uimanager.lua:1119: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0

**Comment by Eduardomb22** [comment]
Ok, I uploaded it.

**Comment by NiLuJe** [comment]
Pinging @robert00s, as this seems mildly toggleswitch related ;).

**Comment by robert00s** [comment]
Yes it's my fault. I'll fix it.
