### ISSUE TITLE
[Suggestion] about bottom menu

### ISSUE THREAD

**Issue by pkpkoko** [koreader/koreader#5441]
* KOReader version: v2019.05
* Device: Kindle Paper White 3

#### Issue
Is there any way not to show the bottom menu when tap the bottom of screen?
I think it would better to design a selection/button of invoking bottom menu in the top menu.

**Comment by Frenzie** [comment]
That can be set up in Settings (gear) -> Taps & gestures -> Activate menu. I think swipe only offers a better experience, but it defaults to taps & swipes for a variety of reasons. Taps work well on all supported platforms; swipes don't necessarily do (which is a platform bug, but still). Additionally, for some users it might be difficult to execute swipes.

We probably need a quick setup wizard on first start for some things like this, or something along those lines.

**Comment by pkpkoko** [comment]
Thank you. This method works for this problem.
