### ISSUE TITLE
FR: Footnotes area gets much bigger touch zone (option to make viewing footnotes much more comfortable)

### ISSUE THREAD

**Issue by AlanSP1** [koreader/koreader#5445]
* Device: Kobo Aura One

Thing is, I just read book with pretty interesting footnotes, that are relatively small and all the same, i.e. one asterisk (*). And yes, Kobo Aura One has "really great" screen precision (sarcasm to the max).

So, now, I'm doing some sort of tap dancing and guessing where that small asterisk is on the screen, at least where my KA1 thinks it is. Which looks like I tap, miss, go back one page (or forward in cases if footnote was in back page area), then I start long tapping to see which words gets selected for dictionary (to help me judge offset from image and touch zones.

It's a hell. It really is.

On some devices where screen is more precise, this may not be necessary, but at least on KA1, it is a must, and I guess there are other devices with same problem, how to target that small elements like footnotes.

Anyway, my proposal is to make artificially target zones much bigger for certain elements, like footnotes (not sure if there are some other elements). I guess it can be done, and it can be set up as an option, to have touch zones bigger/smaller (maybe some users would prefer them smaller, I mention that just as an option) in increments like 0,25 0,5 1 (this means it stays same), 1,25 1,5 2 4.

Or we can maybe activate larger touch zones when long pressing. If we long press and there's footnote near long press (as I'm sure I'm touching pretty close where footnotes are, but just not close enough because KA1 has so lame touch screen), it gets selected like it was normal short touch and footnote is shown.

First solution is more logical and user friendly, but second will also work great. But, at the moment, I'm pulling my hair out trying to see footnotes on my KA1. It really doesn't work at all, especially in this book where they are small (and I don't want to make my font too big, I prefer to have 2-3 minutes of text per page, but for this problem I would need to go to maybe under minute).

Hope it can be done and that it is easy to solve.

**Comment by poire-z** [comment]
Don't we already have that (for EPUB only)?
<kbd>![image](https://user-images.githubusercontent.com/24273478/66081617-a0e17380-e568-11e9-85a3-1cf0eed195d9.png)</kbd>

And `Swipe to follow nearest link` (that I prefer to tap) is available for PDF too.

**Comment by AlanSP1** [comment]
My bad. :(

But, now I know (and will place info in wiki).

Larger tap area around links works great, no problem selecting footnotes.

Swipe couldn't tested as at the moment I'm reading epub, but it will be mentioned in wiki (i.e. I'll link this issue.

We really need more info what we have already, there's so much options, I found things only when I need them and, obviously, I know so little...

**Comment by pazos** [comment]
Thank you @AlanSP1 for all the work you do on the wiki. :+1:

**Comment by Frenzie** [comment]
Indeed, much appreciated!

**Comment by AlanSP1** [comment]
Thank you very much, but you guys do the really heavy work of making Koreader such a great software, so useful and full of features.
