### ISSUE TITLE
When pressing Finished on book status page, koreader exits unexpectedly

### ISSUE THREAD

**Issue by rola25** [koreader/koreader#5448]
* KOReader version: koreader-android-arm-v2019.09.3-47-g27de8d9_2019-09-30.apk
* Device: Tolino Epos

#### Issue
When book is finished and the book status page is displayed - if you press "Finished" then koreader exits

#### Steps to reproduce
Finish book -> book status page -> press finished

##### adb logcat
E/KOReader( 4206): [NativeThread]: failed to run script: frontend/ui/widget/toggleswitch.lua:220: attempt to call field 'callback' (a nil value)
E/KOReader( 4206): [NativeThread]: Stopping due to previous errors

**Comment by Frenzie** [comment]
Should be fixed by #5438 (i.e., one development build newer than the one you're using ;-) ). Duplicate of #5434.

**Comment by Frenzie** [comment]
Pardon, my bad. You are using precisely the build I was thinking of. It's likely related in any case. Pinging @robert00s.

**Comment by robert00s** [comment]
I'll look at it. I think this should be easy to fix.
