### ISSUE TITLE
how to change size of highlight text box

### ISSUE THREAD

**Issue by leela52452** [koreader/koreader#5449]
version: 2019.09.03

i dont know, what the box is called.
it appears when i highlight text of an epub.
is there any way to increase the size of the box ?

i mean the box containing options: highlight, copy, view html, etc..

![Screenshot_2019-09-29-10-44-29](https://user-images.githubusercontent.com/52065244/66127837-26ead200-e5dc-11e9-9f7e-2b3fa45d78f0.png)

**Comment by Frenzie** [comment]
You can set a custom DPI in settings (gear icon) → Screen → Screen DPI. All UI elements will automatically scale along.

**Comment by poire-z** [comment]
If it's for reading purpose, the above suggestion is the one.

If it's because it's tedious taping on the right button, because of the small height of each, and the proximity of others - I share that feeling. When I have to tap on a button in that dialog, I need to be more careful than usually...
But I don't want to increase DPI and the font size. The solution could be to increase these buttons' padding, but that make the UI a bit inconsistent, and would hide a bit more of the text below. So, I dunno :|

**Comment by leela52452** [comment]
> If it's because it's tedious taping on the right button, because of the small height of each, and the proximity of others - I share that feeling. When I have to tap on a button in that dialog, I need to be more careful than usually...

i completly agree with you.

> You can set a custom DPI in settings (gear icon) → Screen → Screen DPI. All UI elements will automatically scale along.

until a solution is found, i will adapt

**Comment by poire-z** [comment]
One might try:
```diff
--- a/frontend/ui/widget/buttontable.lua
+++ b/frontend/ui/widget/buttontable.lua
@@ -59,7 +59,7 @@ function ButtonTable:init()
                 max_width = (self.width - sizer_space)/column_cnt - 2*self.sep_width - 2*self.padding,
                 bordersize = 0,
                 margin = 0,
-                padding = 0,
+                padding = Size.padding.button, -- or Size.padding.default
                 text_font_face = self.button_font_face,
                 text_font_size = self.button_font_size,
                 show_parent = self.show_parent,
```
`Size.padding.button` gives a tad more height without looking too different - `Size.padding.default` adds too much, which could be ok in that ButtonDialog, but makes all other widgets really ugly (quickdictlookup...)

(This change would not be enough as if affects some horizontal paddings and measurements, and leaves things ugly - it would need some other tweaks here and there to counteract that.)

**Comment by poire-z** [comment]
Some suggestion with screenshots:
```diff
--- a/frontend/ui/widget/button.lua
+++ b/frontend/ui/widget/button.lua
@@ -43,2 +43,4 @@ local Button = InputContainer:new{
     padding = Size.padding.button,
+    padding_h = nil,
+    padding_v = nil,
     width = nil,
@@ -56,2 +58,9 @@ function Button:init()

+    if not self.padding_h then
+        self.padding_h = self.padding
+    end
+    if not self.padding_v then
+        self.padding_v = self.padding
+    end
+
     if self.text then
@@ -59,3 +68,3 @@ function Button:init()
             text = self.text,
-            max_width = self.max_width and self.max_width - 2*self.padding - 2*self.margin - 2*self.bordersize or nil,
+            max_width = self.max_width and self.max_width - 2*self.padding_h - 2*self.margin - 2*self.bordersize or nil,
             fgcolor = self.enabled and Blitbuffer.COLOR_BLACK or Blitbuffer.COLOR_DARK_GRAY,
@@ -81,3 +90,6 @@ function Button:init()
         radius = self.radius,
-        padding = self.padding,
+        padding_top = self.padding_v,
+        padding_bottom = self.padding_v,
+        padding_left = self.padding_h,
+        padding_right = self.padding_h,
         CenterContainer:new{
--- a/frontend/ui/widget/buttontable.lua
+++ b/frontend/ui/widget/buttontable.lua
@@ -62,2 +62,3 @@ function ButtonTable:init()
                 padding = 0,
+                padding_v = Size.padding.button, -- a bit taller buttons for easier tapping
                 text_font_face = self.button_font_face,
```

Screenshots from my Kobo, scaled by 25% for easier overall comparison.

Our current look:
<kbd>![Reader_2019-Oct-31_133101](https://user-images.githubusercontent.com/24273478/67947977-04e96d00-fbe5-11e9-8f4c-845072416ef5.png)</kbd> <kbd>![Reader_2019-Oct-31_133113](https://user-images.githubusercontent.com/24273478/67947981-06b33080-fbe5-11e9-966c-13daeb40d2d3.png)</kbd>

With `padding_v = Size.padding.button`:
<kbd>![Reader_2019-Oct-31_133234](https://user-images.githubusercontent.com/24273478/67948452-09625580-fbe6-11e9-9c97-86d5d06b4b99.png)</kbd><kbd>![Reader_2019-Oct-31_133244](https://user-images.githubusercontent.com/24273478/67948030-264a5900-fbe5-11e9-93ae-01a11a94e126.png)</kbd>

With `padding_v = Size.padding.default`:
<kbd>![Reader_2019-Oct-31_134234](https://user-images.githubusercontent.com/24273478/67948044-2e09fd80-fbe5-11e9-99ff-99f3488d42cf.png)</kbd><kbd>![Reader_2019-Oct-31_134319](https://user-images.githubusercontent.com/24273478/67948050-3104ee00-fbe5-11e9-91eb-e2dbf28ed51a.png)</kbd>
<kbd>![Reader_2019-Oct-31_134304](https://user-images.githubusercontent.com/24273478/67948046-2f3b2a80-fbe5-11e9-924b-7ada53e8d3f1.png)</kbd>
(That search buttons box is the one I really often miss my tap on... and I have to type again the word I'm searching for :)

I find our current look the prettiest, the others look a bit more toy'ish - but they are easier to tap and avoid tap errors.
Any opinion?

**Comment by Frenzie** [comment]
What does the current look use? I'd say `Size.padding.button` soundslike a good one.

**Comment by poire-z** [comment]
It uses 0, and we somehow need 0 for left and right for proper grid/lines.
```diff
@@ -62,2 +62,3 @@ function ButtonTable:init()
                 padding = 0, -- <= apply to all 4 sides
+                padding_v = Size.padding.button, -- a bit taller buttons for easier tapping
```
Standalone buttons use Size.padding.button.
So, may be in ButtonTable, just use `padding_h = 0` and remove that `padding = 0`.
