### ISSUE TITLE
(fr) add a Wikipedia lookup button to the selection expand / close ui

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5455]
Use case 

You've set default selection to highlight.  This means any multi word selection will be turned to a highlight.  But now say there's a proper noun that you'd like to lookup via Wikipedia.  Currently impossible

Idea would be to add a Wikipedia lookup button to selection expander/reducer so you could look up proper nouns

**Comment by Frenzie** [comment]
It would make sense to show the dialog instead of duplicating a highlight, but I'm less sure about partially overlapping highlights.

Anyway, a Wikipedia lookup button would be too specific, but something like a `...` might do.
