### ISSUE TITLE
Random image with no repetition as screensaver

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#5457]
Using "random image from folder as screensaver" could be better with a non-repeat rule. So, an image can not be used again as screensaver until all the other images in the folder have been used. Then we'd get max variety of images for this screensaver option.

**Comment by Frenzie** [comment]
Ah, but then it wouldn't be random. ^_^ Of course one probably wouldn't want truly random where repeating the same image(s) a few times in a row would be possible, but not repeating the same image until all other images have been shown is only semi-random once. ;-)

**Comment by pblasi** [comment]
Don't call it random then, but it would definitely be a nicer behavior.

**Comment by Frenzie** [comment]
PRs welcome. ;-)

But I do think picking a random order *once* seems a bit odd. Why not just go through in a set order?

**Comment by pblasi** [comment]
Well you don't have the surprise thing, but a set order will do the trick of course.

**Comment by NiLuJe** [comment]
On Kindle, it goes by alphabetical order, but, that's easy, because they're prefixed ssNN_<whatever>.png, with NN going from 00 top 99 ;).

**Comment by poire-z** [comment]
Looks like overengineering to me, for such a little feature, having to memorize and save a state/order, dealing with new and removed images... when a simple random of the directory current content (no state, no memory, no save) gives a good enough result.

**Comment by poire-z** [comment]
And for my use case, I have photographs of authors, so I have 5 `Tcheckhov_N.jpeg`. So, not alphabetical please, or I'll have Tcheckhov screensaver days, which won't feel random :)

**Comment by Frenzie** [comment]
> Well you don't have the surprise thing

But the logical consequence of ensuring all other files have been picked before showing a file again is quite simply a set order. A fake randomness that tried to avoid the previous pick or two wouldn't have that issue.

Perhaps you mean something like pick a random order from the onset, go through it, and pick a completely new random order once we've reached the end.

> when a simple random of the directory current content (no state, no memory, no save) gives a good enough result.

It would make sense to save the previously randomly selected image to prevent doubling.

NB Not volunteering. ;-)
