### ISSUE TITLE
After a koreader restart the frontlight warmth resets to 0

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#5465]
* KOReader version: 2019-10-08
* Device: KoboA1

Noticed since last few updates. After restarting because of an update or just manually, the warmth becomes zero. When I open the frontlight menu, warmth shows 100 but it isn't.

I just have to adjust it twice to get it back to 100 warmth.

**Comment by Frenzie** [comment]
I don't think there's been anything involving the frontlight since about #5421 two weeks ago. Does that fall within what you mean by the last few updates?

**Comment by NiLuJe** [comment]
Probably dates back to the ioctl switch, the KA1 is the only device that falls in the "has to go through sysfs, always" slot.

**Comment by NiLuJe** [comment]
Possibly just the tail end of it, i.e., https://github.com/koreader/koreader/commit/abc86323fc0e1396b6402ebb38b8a78e21c44e3e

**Comment by NiLuJe** [comment]
Otherwise, https://github.com/koreader/koreader/commit/1c2c471c5f3dda7885dec89188f632ae1945828f

**Comment by NiLuJe** [comment]
Namely, that might fix it:

```diff
diff --git a/frontend/device/kobo/powerd.lua b/frontend/device/kobo/powerd.lua
index b9adeb90..2fd0670c 100644
--- a/frontend/device/kobo/powerd.lua
+++ b/frontend/device/kobo/powerd.lua
@@ -232,7 +232,13 @@ end
 
 function KoboPowerD:setIntensityHW(intensity)
     if self.fl == nil then return end
-    self.fl:setBrightness(intensity)
+    -- Not having a mixer sucks (#5465)
+    if self.device:hasNaturalLight() and not self.device:hasNaturalLightMixer() then
+        self.fl:setNaturalBrightness(intensity, self.fl_warmth)
+    else
+        -- We either don't have NL, or we have a mixer: we don't want to always set the wamrth (c.f., #5429)
+        self.fl:setBrightness(intensity)
+    end
     self.hw_intensity = intensity
     -- Now that we have set intensity, we need to let BasePowerD
     -- know about possibly changed frontlight state (if we came
```

**Comment by NiLuJe** [comment]
Or with a slightly more logical test, with bonus points for having the most-commonly taken branch first:

```diff
diff --git a/frontend/device/kobo/powerd.lua b/frontend/device/kobo/powerd.lua
index b9adeb90..361de610 100644
--- a/frontend/device/kobo/powerd.lua
+++ b/frontend/device/kobo/powerd.lua
@@ -232,7 +232,13 @@ end
 
 function KoboPowerD:setIntensityHW(intensity)
     if self.fl == nil then return end
-    self.fl:setBrightness(intensity)
+    if self.fl_warmth == nil or self.device:hasNaturalLightMixer() then
+        -- We either don't have NL, or we have a mixer: we only want to set the intensity (c.f., #5429)
+        self.fl:setBrightness(intensity)
+    else
+        -- Not having a mixer sucks, we always have to set intensity combined w/ warmth (#5465)
+        self.fl:setNaturalBrightness(intensity, self.fl_warmth)
+    end
     self.hw_intensity = intensity
     -- Now that we have set intensity, we need to let BasePowerD
     -- know about possibly changed frontlight state (if we came
```

**Comment by CalbertAmu** [comment]
> I don't think there's been anything involving the frontlight since about #5421 two weeks ago. Does that fall within what you mean by the last few updates?

Yes, it is about two weeks.

**Comment by NiLuJe** [comment]
@poire-z : Would Cervantes need the same tweak? (i.e., is there a device w/ NL but no mixer in the lineup?)

**Comment by poire-z** [comment]
I think you meant @pazos (cause I know nothing about Cervantes :)

**Comment by NiLuJe** [comment]
Ooops. :D.

**Comment by pazos** [comment]
> is there a device w/ NL but no mixer in the lineup?

Nope, the Cervantes 4 is the only one with warmth and it is using the mixer.
