### ISSUE TITLE
Segmentation fault while browsing LAN OPDS catalog

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#5476]
* KOReader version: v2019.09.3-64g5209494_2019-10-10
* Device: Kobo Aura H2O2

#### Issue
Segmentation fault while browsing LAN OPDS catalog

#### Steps to reproduce
Just click on the OPDS entry after adding it

##### `crash.log` (if applicable)

>  [*] Current time: 10/11/19-16:18:34
>  [*] Version: v2019.09.3-64-g5209493_2019-10-10
> 
> ffi.load: SDL2
> ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
> ffi.load: libSDL2-2.0.so
> ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
> ffi.load: libSDL2-2.0.so.0
> ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
> SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
> ffi.load: blitbuffer
> FB: computed size: 3342336
> FB: id           : mxc_epdc_fb
> FB: smem_len     : 6684672
> FB: line_length  : 1088
> FB: xres         : 1080
> FB: xres_virtual : 1088
> FB: yres         : 1440
> FB: yres_virtual : 3072
> FB: bpp          : 8
> 10/11/19-16:18:34 INFO  initializing for device Kobo_snow
> 10/11/19-16:18:34 INFO  framebuffer resolution: {
>     ["h"] = 1440,
>     ["w"] = 1080
> }
> [ko-input] Forked off fake event generator(pid:2817).
> ffi.load: libs/libmupdf.so
> ffi.load: libs/libwrap-mupdf.so
> ffi.load: libs/libfreetype.so.6
> ffi.load: sqlite3
> ffi.load: z
> ffi.load: sqlite3
> 10/11/19-16:18:35 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
> 10/11/19-16:18:35 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
> 10/11/19-16:18:35 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
> 10/11/19-16:18:35 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
> 
> 
> ...
> 
> 10/11/19-20:52:53 INFO  Kobo WiFi: enabling WiFi
> udhcpc (v1.22.0.kobo) started
> Sending discover...
> Sending select for 192.168.1.11...
> Lease of 192.168.1.11 obtained, lease time 86400
> adding dns 192.168.1.1
> 10/11/19-20:53:15 INFO  request {
>     ["url"] = "http://192.168.1.6:8080",
>     ["method"] = "HEAD",
>     ["headers"] = {
>         ["Authorization"] = "Basic Og==",
>         ["Host"] = "192.168.1.6"
>     },
>     ["sink"] = function: 0x2fbb9828
> }
> 10/11/19-20:53:15 INFO  request {
>     ["url"] = "http://192.168.1.6:8080",
>     ["method"] = "GET",
>     ["headers"] = {
>         ["Authorization"] = "Basic Og==",
>         ["Host"] = "192.168.1.6"
>     },
>     ["sink"] = function: 0x33460190
> }
> Segmentation fault
> !!!!
> Uh oh, something went awry... (Crash n°1: 10/11/19 @ 20:53:21)
> Attempting to restart KOReader . . .
> !!!!

**Comment by NiLuJe** [comment]
Anything particular about that OPDS server (or your network)?

(f.g., what's serving it?)

**Comment by BrainDamage** [comment]
Nothing particular, calibre-server running on a headless arm SOC, serving epub files:

calibre's log is not particularly informative either:

> Oct 05 19:47:42 alarmnas systemd[1]: Started Calibre eBook content server.
> Oct 05 19:48:05 alarmnas python2[28774]: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-calibre'
> Oct 05 19:48:05 alarmnas calibre-server[28774]: calibre server listening on 0.0.0.0:8080
> Oct 05 19:48:08 alarmnas calibre-server[28774]: OPDS feeds advertised via BonJour at: 192.168.1.6 port: 8080

the web interface does work fine and there's no password access

**Comment by NiLuJe** [comment]
You can also enable verbose debug logging in the Tools > Developer options menu, although I'm not familiar with the verbosity of this piece of code ;).

**Comment by BrainDamage** [comment]
debug option doesn't introduce any further information
I cannot seem to get a stacktrace, but I did some progress on the issue: using http://192.168.1.6:8080/opds as the url does give me results and works as expected, so something is broken in the front page mechanism, no idea if it's a redirect or something

**Comment by Frenzie** [comment]
You could try tomorrow's nightly just in case updated luasec fixes anything (doubtful but it shouldn't take long to test).

**Comment by NiLuJe** [comment]
Is it a Calibre 4 server? If it is, can you check with Calibre 3.48? (I don't recall if there were any changes to the OPDS brower, but since the Content server was heavily revamped, it's quite likely).

**Comment by BrainDamage** [comment]
Yes, it's a calibre 4 server, I'll test an older version tomorrow as well as the new nightly

**Comment by BrainDamage** [comment]
Test results:
New nightly crashes equally.
Calibre 3.x crashes equally.
I also did further progress, I've tried to launch a calibre server on my desktop, and neither 3.x nor 4.x crash, even if I point the url to the base one, without the /opds suffix, so there's something in the library metadata that's on my NAS that is not digested well by koreader

**Comment by Frenzie** [comment]
That wouldn't cause a segmentation fault. A segmentation fault is almost certainly indicative of something much deeper down, like on the protocol level.

**Comment by robert00s** [comment]
I don't have problem in my environment. I tested on emulator and Kindle. No problem to connect to calibre 4.2.
Do you put : `http://192.168.1.6:8080/opds` ?

<img src=https://user-images.githubusercontent.com/22982594/67800074-f5541200-fa86-11e9-8945-a031bbec3aa3.png width=70%>
