### ISSUE TITLE
Extend DocumentRegistry to provide supported document info to OPDS & Wallabag 

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#5478]
* KOReader version:  v2019.09.3-64g5209494_2019-10-10
* Device: Kobo Aura H2O2

#### Issue
When selecting a cbz file on a OPDS server, the list of download formats is empty:

taking a peek at the code:
https://github.com/koreader/koreader/blob/a2dcfe9aec58f734e1285d1b6ac5a13271275b91/frontend/ui/widget/opdsbrowser.lua#L47
does not include comic book mime type, it seems to be missing djvu and few other formats as well, ideally there should be a centralized definition for supported formats rather than per-module

**Comment by Frenzie** [comment]
That's a work in progress. I believe @teroshan indicated an interest in fixing it up properly.

**Comment by Frenzie** [comment]
I should probably clarify that I wrote the DocumentRegistry module for exactly this kind of thing; it just needs an extra method or two to assist with this specific use case. @teroshan's interest is in the Wallabag plugin but the requirements are likely similar.

**Comment by jstirling** [comment]
Looks like the DocumentRegistry fix for this is still in progress. 
Any chance we can get a quickfix for CBZ for the OPDS browser in the meantime? 

Would think it'd just be adding this to the formats list
`["application/x-cbz"] = "CBZ"`

**Comment by Frenzie** [comment]
@jstirling Sure, could you put that in a PR? ;-)

**Comment by jstirling** [comment]
@Frenzie a little rusty at this but #5940. Threw in a bunch of others to cover the gap until this fix.

**Comment by Draic** [comment]
can someone explain to me why just supporting cbz from OPDS is so complicated that it has not been implemented in over a year?

**Comment by Frenzie** [comment]
Your question is mistaken. See https://github.com/koreader/koreader/pull/5940

**Comment by Draic** [comment]
it still does not work from a ubooquity server

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/issues/6585#issuecomment-752769651

**Comment by Draic** [comment]
that is not really an explanation :( All I can see is that it is an ongoing issue that is getting pushed back.

**Comment by Frenzie** [comment]
The server isn't notifying the recipient that this is a CBZ document. Emphasis on the word server. ;-)

Additionally, it's better for the health of the project to attract a wider range of contributors.
