### ISSUE TITLE
Text in non-embedded Helvetica font not rendered in PDF document

### ISSUE THREAD

**Issue by onlyra** [koreader/koreader#548]
Some pdf files have text boxes (the checkmarked ones) that are not rendered on kindle touch with koreader-nightly-20140405. I first observe this on august 2013. I attached one PDF example(disguised as png file) and its 2 screenshots. Please change the extension of the example pdf, the third attached file, back to pdf after you download it.

![screenshot_2013_08_01t10_59_13 0301](https://cloud.githubusercontent.com/assets/7191175/2623483/7201a3d6-bcf2-11e3-8491-0df144c05f35.png)
![screenshot_2013_08_01t10_59_40 0301](https://cloud.githubusercontent.com/assets/7191175/2623485/79531d22-bcf2-11e3-9b06-5ed716a16841.png)
![pages from configuring windows server 2008 network pdf](https://cloud.githubusercontent.com/assets/7191175/2623516/7265c012-bcf4-11e3-9823-cef5003cde98.png)

**Comment by robert00s** [comment]
On my Kindle PW3 and emulator looks good after latest update MuPDF (#3547).
I think we can close it now.

**Comment by Frenzie** [comment]
Neat, thanks @TnS-hun ! Closing this now. 👍
