### ISSUE TITLE
Offline book sharing across devices on same wifi

### ISSUE THREAD

**Issue by Amin-jkr** [koreader/koreader#5485]
I tried zsync with no success, nothing happened...although the wifi doesn't have access to Internet...

Is it possible to share books offline?

**Comment by Frenzie** [comment]
Tbh it's basically just there. I don't ever look at it in any case. There are a few semi-known issues like #3880 and #2223. But it's definitely meant for local network only.

You didn't specify which devices you tried it with or which version. Please do. ;-)

**Comment by pazos** [comment]
Closing as inactive, use #3880 to report future issues. Thanks!
