### ISSUE TITLE
Possible error in autosuspend plugin (or my error)

### ISSUE THREAD

**Issue by carmelocotonto** [koreader/koreader#5495]
* KOReader version:  v2019.09.3-34-ge7cfc65_2019-09-24
* Device:  kobo clara hd

#### Issue
I put 12 hours in plugin for shutdown and 5 minutes for suspend, but Clara hd shutdowns before. Today I close Clara case over 00:04:00, so I expected it to be suspend but no power off until 12:04, but at 8:00 (or before) it was power off. In the file 'settings.reader.lua' it is set: ["autoshutdown_timeout_seconds"] = 43200,
I guess with any version the same thing happens. It is the first time I use this plugin. All the night the case was closed. I hope you understand google english ;-). Thanks.

#### Steps to reproduce
Nothing special. Use the plugin

##### `crash.log` (if applicable)
10/15/19-00:04:30 INFO  Kobo suspend: going to sleep . . .
10/15/19-00:04:30 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/15/19-00:04:32 INFO  Kobo suspend: waited for 2s because of reasons...
10/15/19-00:04:32 INFO  Kobo suspend: synced FS
10/15/19-00:04:32 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/15/19-00:04:32 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/15/19-04:03:15 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1571101410	1571101410	1571101410
10/15/19-04:03:30 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1571101395	1571101395	1571101395	1571101410
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
10/15/19-04:03:31 INFO  Kobo suspend: putting device back to sleep.

**Comment by Frenzie** [comment]
Initial builds failed to update the current settings without a restart; I don't know otoh if that applies to yours but it's definitely older.

What's your timezone (on your device)?

**Comment by carmelocotonto** [comment]
No, it is not restart problem.   On my device it puts (UTC 2:00)

From web:
2019 Time Zones - Madrid
CET  UTC+1h            CEST   UTC+2h                          CET  UTC+1h
Jan Feb Mar        Apr May Jun Jul Aug Sep Oct             NovDec

**Comment by Frenzie** [comment]
Btw, doesn't the log say for when it's scheduling the wakeup prior to that "going to sleep" line?

**Comment by carmelocotonto** [comment]
Yes, six lines before

10/15/19-00:04:13 INFO  WakeupMgr: scheduling wakeup for: 43200 1571133853
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
ifconfig: SIOCSIFADDR: No such device
10/15/19-00:04:15 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/15/19-00:04:30 INFO  Kobo suspend: going to sleep . . .
10/15/19-00:04:30 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/15/19-00:04:32 INFO  Kobo suspend: waited for 2s because of reasons...
10/15/19-00:04:32 INFO  Kobo suspend: synced FS
10/15/19-00:04:32 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/15/19-00:04:32 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/15/19-04:03:15 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1571101410	1571101410	1571101410
10/15/19-04:03:30 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1571101395	1571101395	1571101395	1571101410
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
10/15/19-04:03:31 INFO  Kobo suspend: putting device back to sleep.



Now, I have tried 5 minutes for suspend and 7 minutes for poweroff (I put 420 into settings.reader.lua) and all is correct

10/15/19-12:47:56 INFO  WakeupMgr: scheduling wakeup for: 420 1571136896
ifconfig: SIOCSIFADDR: No such device
10/15/19-12:47:58 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/15/19-12:48:13 INFO  Kobo suspend: going to sleep . . .
10/15/19-12:48:13 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/15/19-12:48:15 INFO  Kobo suspend: waited for 2s because of reasons...
10/15/19-12:48:16 INFO  Kobo suspend: synced FS
10/15/19-12:48:16 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/15/19-12:48:16 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/15/19-12:54:56 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1571133311	1571133311	1571133311
10/15/19-12:55:11 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1571133296	1571133296	1571133296	1571133311
10/15/19-12:55:11 INFO  Kobo suspend: putting device back to sleep.

**Comment by carmelocotonto** [comment]
Good morning,
I have done another test with 6 hours and this has been the result:

10/16/19-00:05:40 INFO  WakeupMgr: scheduling wakeup for: 21600 1571198740
ifconfig: SIOCSIFADDR: No such device
10/16/19-00:05:42 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/16/19-00:05:57 INFO  Kobo suspend: going to sleep . . .
10/16/19-00:05:57 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/16/19-00:05:59 INFO  Kobo suspend: waited for 2s because of reasons...
10/16/19-00:05:59 INFO  Kobo suspend: synced FS
10/16/19-00:05:59 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/16/19-00:05:59 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/16/19-03:47:38 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1571186873	1571186873	1571186873
10/16/19-03:47:53 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1571186858	1571186858	1571186858	1571186873
10/16/19-03:47:53 INFO  Kobo suspend: putting device back to sleep.



Is it possible schedule function is not working correctly?

**Comment by carmelocotonto** [comment]
I keep looking at the log.........

I have found a strange case on 10/10/19. Maybe it helps to find the problem:


10/10/19-23:32:47 INFO  WakeupMgr: scheduling wakeup for: 43200 1570786367
ifconfig: SIOCSIFADDR: No such device
10/10/19-23:32:49 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/10/19-23:33:04 INFO  Kobo suspend: going to sleep . . .
10/10/19-23:33:04 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/10/19-23:33:06 INFO  Kobo suspend: waited for 2s because of reasons...
10/10/19-23:33:06 INFO  Kobo suspend: synced FS
10/10/19-23:33:06 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/10/19-23:33:06 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/10/19-23:33:08 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1570739603	1570739603	1570739603
10/10/19-23:33:23 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1570750797	1570750797	1570750797	1570739603
10/10/19-23:33:23 ERROR Kobo suspend: wakeup action failed.
10/10/19-23:33:23 INFO  Kobo suspend: putting device back to sleep.
10/10/19-23:33:53 INFO  Kobo suspend: going to sleep . . .
10/10/19-23:33:53 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/10/19-23:33:55 INFO  Kobo suspend: waited for 2s because of reasons...
10/10/19-23:33:55 INFO  Kobo suspend: synced FS
10/10/19-23:33:55 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/10/19-23:33:55 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/11/19-02:39:57 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1570750812	1570750812	1570750812
10/11/19-02:40:12 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1570750797	1570750797	1570750797	1570750812
10/11/19-02:40:12 INFO  Kobo suspend: putting device back to sleep.

**Comment by Frenzie** [comment]
Are these logs all still from the old version? I'd always recommend trying the latest version before putting in more effort testing things even if in this specific case it may not make a difference.

The scheduler takes the current time and adds your number of seconds to it:
https://github.com/koreader/koreader-base/blob/fa35ba1852395d7db8b7365ea44d9b83b11b610a/ffi/rtc.lua#L26-L38

@NiLuJe Do you know if it's possible that localtime/mktime behave differently on some devices?

**Comment by carmelocotonto** [comment]
Ok. I'll update to latest version and next tests will be done with that version. Tomorrow I'll tell you the results. Thanks again.

Yes I see  rtc.lua,  but from crash.log  we can see two things:
1.- Sum is calculated:     scheduling wakeup for: 43200 **1570786367**   and
2.-  The schedule has got a different values:  validateWakeupAlarmByProximity 1570750797 1570750797 1570750797 **1570750812**

**Comment by Frenzie** [comment]
> The schedule has got a different values

That's a 15-second difference. Nothing weird there, fully expected because the wakeup guard is scheduled 15 seconds after waking up. The problem is your 35 570 difference which wasn't visible previously due to the lacking log.

Chances are it's just your sleepcover or charger or something causing unexpected wakeups and me having insufficiently fixed that problem because my device doesn't suffer unexpected wakeups.

**Comment by carmelocotonto** [comment]
Oh, I don't say anything about 15 seconds, only about 35570 difference. Into all my logs send there are big seconds differences.  There is not always unexpected wake up (I think). You can see it in my previous messages.

This night I won't use Clara case to sleep. We will see what happens.

**Comment by carmelocotonto** [comment]
Please Frenzie, take a look to the log.
I explain to you my idea:

On 10/16/19-**14:43:47** I closed clara case. Ereader must shutdown in 5 hours
On 10/16/19-15:13:17 I arrived at home and I opened clara case
On 10/16/19-15:18:17  I closed clara case again so I thought clara will shutdown on 20:18 but....
On 10/16/19-**19:43:47**  clara powered off,  5 hours after  14:43:47, not 5 hours after 15:13 when I closed for the second time. Maybe the second wake up did not modify the schedule. Don't you think so?

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
10/16/19-14:43:47 INFO  WakeupMgr: scheduling wakeup for: 18000 1571247827
ifconfig: SIOCSIFADDR: No such device
10/16/19-14:43:48 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/16/19-14:44:03 INFO  Kobo suspend: going to sleep . . .
10/16/19-14:44:03 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/16/19-14:44:05 INFO  Kobo suspend: waited for 2s because of reasons...
10/16/19-14:44:05 INFO  Kobo suspend: synced FS
10/16/19-14:44:05 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/16/19-14:44:05 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/16/19-15:13:17 INFO  Kobo suspend: woke up!
10/16/19-15:13:17 INFO  Kobo resume: clean up after wakeup
10/16/19-15:13:17 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
10/16/19-15:18:17 INFO  WakeupMgr: scheduling wakeup for: 18000 1571249897
ifconfig: SIOCSIFADDR: No such device
10/16/19-15:18:19 INFO  Kobo WiFi: disabling WiFi
ifconfig: SIOCGIFFLAGS: No such device
10/16/19-15:18:34 INFO  Kobo suspend: going to sleep . . .
10/16/19-15:18:34 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
10/16/19-15:18:36 INFO  Kobo suspend: waited for 2s because of reasons...
10/16/19-15:18:36 INFO  Kobo suspend: synced FS
10/16/19-15:18:36 INFO  Kobo suspend: asking for a suspend to RAM . . .
10/16/19-15:18:36 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
10/16/19-19:43:47 INFO  Kobo suspend: woke up!
validateWakeupAlarmByProximity	nil	1571244242	1571244242	1571244242
10/16/19-19:44:02 INFO  Kobo suspend: scheduled wakeup.
validateWakeupAlarmByProximity	1571244227	1571244227	1571244227	1571244242
10/16/19-19:44:02 INFO  Kobo suspend: putting device back to sleep.

**Comment by Frenzie** [comment]
Your log definitely seems to suggest that. I'll have to double check if something similar doesn't happen for me following @NiLuJe's FFI tweaks but I don't recall it looking suspicious.

**Comment by NiLuJe** [comment]
@Frenzie: Unless I'm groking it wrong, `WakeUpMgr` won't replace an existing wakeup unless the new one comes *earlier* than the already scheduled one.

That confirms @carmelocotonto's analysis:

That bit of logging:

`10/16/19-15:18:17 INFO WakeupMgr: scheduling wakeup for: 18000 1571249897`

is actually lying, it's sent before the checks are done, and `WakeupMgr:addTask` will in fact not call `setWakeupAlarm` because it fails the ` not old_upcoming_task or (new_upcoming_task < old_upcoming_task)` check.

**Comment by Frenzie** [comment]
I guess I either purposefully removed or accidentally lost the removeTask call in onResume at some point.

What I don't quite understand atm is why I don't seem to be facing this issue. But anyway, too late to look into it now.
