### ISSUE TITLE
 8-) dyslexic mistake in Spanish koreader.po

### ISSUE THREAD

**Issue by carmelocotonto** [koreader/koreader#5509]
* KOReader version:  at least from  2019.xx.yy
* Device: all

#### Issue
A couple of months ago I detected this mistake but I forgot about it:

File koreader.po in spanish:

     #: frontend/apps/reader/modules/readerdictionary.lua:220
     msgid "Installed dictionaries (%1)"
     msgstr "Diccionarios instalados (1%)"

I changed my file
     msgstr "Diccionarios instalados (%1)"

**Comment by hombretranquilo** [comment]
It's my fault. The has already been modified on Transifex, and it's therefore solved.
Sorry.

**Comment by Frenzie** [comment]
@hombretranquilo Thanks!
