### ISSUE TITLE
"Charging" symbol is stuck.

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#5535]
KOReader version: v2019.09.3
Device: Kobo Aura One

Restarting KOReader after updating Nickel, I find the battery indicator is stuck: it stays on charging and 46%.  Restarting the device doesn't help, nor does plugging and unplugging the power cable (and waiting after each such change).
At some point the value changed to 47%, so I guess it is just the charging symbol that is stuck. Taking it off the cable doesn't make the lightning symbol disappear.

**Comment by NiLuJe** [comment]
Which battery meter are you talking about?

Does it still happen in current nightlies?

**Comment by Biep** [comment]
The one in the status bar.
At the moment I cannot connect my e-reader to the Wifi, but once that works again I'll check.  I suppose there is an October release of the stable version too, so I want to try that first.
The counter is at 58%, so it is only the lightning symbol that is in the way (though I haven't yet seen the counter go _down_ when off-cable).

**Comment by NiLuJe** [comment]
Which status bar would that be?

**Comment by Biep** [comment]
The KOReader one, that can be regulated through the last entry of the gear menu.

**Comment by NiLuJe** [comment]
Okay, the bottom one then, not CRe's.

Definitely check with an up to date version, then.

**Comment by Biep** [comment]
I shall, once I can access the Internet again with the device.

**Comment by NiLuJe** [comment]
Okay, double-checked, and if by "charging symbol" you meant the lightning bolt, that's by design.
For a very simple reason: that's not the "charging" symbol (at least, not here), that's simply the "this is a battery meter" symbol.
Here, in the status bar, the "charging" symbol is a "+" prefix in front of the percentage.

In the topmenu footer, on the other hand, the "charging" symbol is now a lightning bolt.

**Comment by Biep** [comment]
OK, so it is just me being confused by the new icons then.
I would be good to have the same symbols mean the same thing everywhere, though.
Sorry for the confusion, and thanks for checking!

**Comment by NiLuJe** [comment]
Yeah, I'll probably tweak the topmenu to be consistent w/ that.

**Comment by Frenzie** [comment]
Although admittedly it's a pretty "charging" type symbol.

**Comment by NiLuJe** [comment]
Yeah, it definitely looks better, but the fact that it magically changes meaning depending on where it is isn't great :/.

**Comment by Frenzie** [comment]
Right, I just mean it intuitively makes more sense to change the footer. :-)

**Comment by Biep** [comment]
Thanks!
So if there is a 'battery' symbol to indicate the meter, and the lightning symbol is used instead of the +, that would be good.  Lightning is often used to indicate charging.

**Comment by NiLuJe** [comment]
Oh, yeah, definitely ;). That finally made it through my thick skull halfway across the FreeSerif list of symbols ;p.

**Comment by NiLuJe** [comment]
Unfortunately, no u+1F50B anywhere in our fonts ;/.
