### ISSUE TITLE
Long text in style tweaks are not translated

### ISSUE THREAD

**Issue by robert00s** [koreader/koreader#5539]
May be be similar to #4085.

Some long text are not translated:
Style tweaks -> Paragraphs -> Generic web browser paragraph style

<img src=https://user-images.githubusercontent.com/22982594/67638302-4e834080-f8e3-11e9-8352-6b73f9ef2353.png width=70%>

**Comment by Frenzie** [comment]
The repo in https://github.com/koreader/koreader-translations is currently not in automated sync with Transifex while waiting for Weblate to set things up for us, so if you want the latest translations you'll have to run `make po`.

![Screenshot_2019-10-27_18-41-03](https://user-images.githubusercontent.com/202757/67638838-62ca3c00-f8e9-11e9-8084-15d536f92c32.png)

**Comment by robert00s** [comment]
Thanks. It works :)
