### ISSUE TITLE
Cloud synchronization deletes metadata file

### ISSUE THREAD

**Issue by ocra98** [koreader/koreader#5542]
KOReader version: v2019.10
Device: likebook mars t80d

#### Issue
I am using the Onesync app to automatically download and update the entire Doccument folder from the cloud. Each time it syncs, it automatically deletes the metadata.pdf.old metadata.pdf.lua files .... (of the app Koreader)

If I choose the 2-way sync function (up and down) then there will be lots of metadata files being uploaded and messing up my cloud data.

**Comment by Frenzie** [comment]
I'm not entirely sure what you expect to gain from this issue? It seems to be about this Onesync app. ;-)

**Comment by ocra98** [comment]
> I'm not entirely sure what you expect to gain from this issue? It seems to be about this Onesync app. ;-)
Every data cloud sync application works like that. It will edit or delete "strange" data (that is not on the cloud). It will retain the books and delete the metadata files created by koreader.
i think this issue is not out-of-scope.

**Comment by Frenzie** [comment]
In that case please refer to existing issues like #4951.

**Comment by poire-z** [comment]
You should see if your sync app allows for excluding files/dirs from sync by pattern, so you could tell it to ignore `*.sdr/` and `*.lua`.
(Not sure if that's the app you're using, but https://metactrl.com/userguide/ mentions that at its bottom.)

**Comment by ocra98** [comment]
> You should see if your sync app allows for excluding files/dirs from sync by pattern, so you could tell it to ignore `*.sdr/` and `*.lua`.
> (Not sure if that's the app you're using, but https://metactrl.com/userguide/ mentions that at its bottom.)
That is the app i'm using.
But "excluding files/dirs" function only work with source data from cloud, not work with data in target device. 
I will recommend this issue to this app's developer.
