### ISSUE TITLE
PDF and EPUB tearing in landscape mode

### ISSUE THREAD

**Issue by RueleuR** [koreader/koreader#5544]
* KOReader version: koreader-android-arm-v2019.10.apk

* Device: Tolino Epos (8inch reader, 1872 x 1404 pixels, Android 4.4, similar to Kobo Aura One)

#### Issue

PDF and EPUB view is corrupted in landscape mode. Only a full refresh of the screen corrects the bug. This issue doesn't exist in portrait mode.

![IMG_20191027_174919](https://user-images.githubusercontent.com/57071192/67638788-f3ece300-f8e8-11e9-82e4-6610a7368425.jpg)
![IMG_20191027_175047](https://user-images.githubusercontent.com/57071192/67638789-f4857980-f8e8-11e9-83c3-c211fae3fe60.jpg)

#### Steps to reproduce
- reflow is off
- open pdf or epub

![IMG_20191027_174836](https://user-images.githubusercontent.com/57071192/67638785-f3ece300-f8e8-11e9-86cb-7024448bf909.jpg)

- swipe bottom up

![IMG_20191027_174853](https://user-images.githubusercontent.com/57071192/67638786-f3ece300-f8e8-11e9-9d0a-23455136f0d8.jpg)

- choose landscape

![IMG_20191027_174905](https://user-images.githubusercontent.com/57071192/67638787-f3ece300-f8e8-11e9-9e6c-d74447116987.jpg)

- tap the right side of the landscape to go to next page
- left side of the landscape is not updated

![IMG_20191027_174919](https://user-images.githubusercontent.com/57071192/67638788-f3ece300-f8e8-11e9-82e4-6610a7368425.jpg)

- swipe bottom up
- only distorted orientation menu is show

![IMG_20191027_175047](https://user-images.githubusercontent.com/57071192/67638789-f4857980-f8e8-11e9-83c3-c211fae3fe60.jpg)

- full screen refresh fixes the page, but if you go to the next page the issue apperas again

![IMG_20191027_175104](https://user-images.githubusercontent.com/57071192/67638790-f4857980-f8e8-11e9-9efa-90179c655d92.jpg)

##### `crash.log` (if applicable)
Her is the file: [logcat.log](https://github.com/koreader/koreader/files/3780954/logcat.log)

I guess the width and height have wrong values for landscape mode and for the bottom menu bar, too. The interessting part seems to be:

I/KOReader( 3040):  setting zoom mode to contentwidth
V/KOReader( 3040): [MainActivity] requesting epd update, mode:34, delay:0, [x:0, y:0, w:1404, h:1872]
I/epd     ( 3040): requested eink refresh, type: 34 x:0 y:0 w:1404 h:1872
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:1552, w:1404, h:1872]
I/epd     ( 3040): requested eink refresh, type: 7 x:0 y:1552 w:1404 h:1872
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:386, y:1618, w:1369, h:1709]
I/epd     ( 3040): requested eink refresh, type: 7 x:386 y:1618 w:1369 h:1709
V/KOReader( 3040): [MainActivity] requesting epd update, mode:34, delay:0, [x:0, y:0, w:1404, h:1872]
I/epd     ( 3040): requested eink refresh, type: 34 x:0 y:0 w:1404 h:1872
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:0, **w:1404, h:1406]**
I/epd     ( 3040): requested eink refresh, type: 7 x:0 y:0 w:1404 h:1406
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:0, w:1404, h:1406]
I/epd     ( 3040): requested eink refresh, type: 7 x:0 y:0 w:1404 h:1406
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:0, w:1404, h:1406]
I/epd     ( 3040): requested eink refresh, type: 7 x:0 y:0 w:1404 h:1406
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:0, w:1404, h:1406]
I/epd     ( 3040): requested eink refresh, type: 7 x:0 y:0 w:1404 h:1406
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, **[x:0, y:1084, w:1404, h:1405]**
I/epd     ( 3040): requested eink refresh, type: 7 x:0 y:1084 w:1404 h:1405
V/KOReader( 3040): [MainActivity] requesting epd update, mode:7, delay:0, [x:503, y:1150, w:1404, h:1241]
I/epd     ( 3040): requested eink refresh, type: 7 x:503 y:1150 w:1404 h:1241
V/KOReader( 3040): [MainActivity] requesting epd update, mode:34, delay:0, [x:0, y:0, w:1404, h:1872]
I/epd     ( 3040): requested eink refresh, type: 34 x:0 y:0 w:1404 h:1872

**Comment by pazos** [comment]
@RueleuR: thanks for the report

> no crash.log applicable

Hum, no crash.log in android, but yeah, logs are already applicable here. You can fetch them with `adb logcat KOReader:* epd:* *:S`

**Comment by RueleuR** [comment]
@pazos Thank you for the command line. That made it easy for me to generate the log file. I added it to the first post.

**Comment by NiLuJe** [comment]
Okay, that one's not a surprise, but, just for completeness' sake, can't reproduce on a Kobo ;).

**Comment by hugleo** [comment]
Can't reproduce either

**Comment by pazos** [comment]
I'm not sure. height and width are the same in both portrait and landscape mode, as the screen isn't rotated. It could be what OP suggested (swapped height & width) that only affect region updates.

@NiLuJe what happens on other devices rotate their viewport?. Are x/y width/height switched?

> Can't reproduce either. Android here

Yeah, that makes sense. Rockchip devices don't support partial updates and the error doesn't happen in full updates. Thanks for reporting!!!

**Comment by NiLuJe** [comment]
@pazos: We don't do hardware rotation, so, no, the fb doesn't change, we probably rotate the region rectangle somewhere so it matches the physical orientation (i.e., still portrait).

I have no idea how that translates on Android, though.

**Comment by Frenzie** [comment]
Like @NiLuJe said there's no difference between a Kobo and the emulator as far as rotation goes.

**Comment by pazos** [comment]
> I have no idea how that translates on Android, though (where the underlying fb might actually rotate, and in turn require rotated regions).

Nope. We are using "sensorPortrait", so landscape orientation isn't triggered while KO is in the foreground. You can check this by enabling the 3rd party dict app you want and checking that, even on landscape mode, the new activity will always be in portrait mode.

Pinging @Char11, who suggested the code for tolino/ntx. I'm afraid I don't have the time &| motivation to look into this.

**Comment by elvvis** [comment]
I have the same problem on a tolino epos 2 (8 inch, 300 ppi, 1440x1920), KOReader v2019.12

**Comment by char11** [comment]
Invalidate method works in portrait mode with parameters left, top, right, bottom.
Left, top cannot be less than zero, right cannot be larger than the screen width, bottom than height.
In lanscape mode, the height and width are swapped.

In portrait mode updatePartial function is called with:

V/KOReader( 2869): !!!x - -1
V/KOReader( 2869): !!!y - -1
V/KOReader( 2869): !!!w - 1074
V/KOReader( 2869): !!!h - 1450
V/KOReader( 2869): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:0, w:1072, h:1448]
I/epd     ( 2869): requested eink refresh, type: 7 x:0 y:0 w:1072 h:1448

In landscape:

V/KOReader( 2869): !!!x - -1
V/KOReader( 2869): !!!y - -1
V/KOReader( 2869): !!!w - 1450
V/KOReader( 2869): !!!h - 1074
V/KOReader( 2869): [MainActivity] requesting epd update, mode:7, delay:0, [x:0, y:0, w:1072, h:1074]
I/epd     ( 2869): requested eink refresh, type: 7 x:0 y:0 w:1072 h:1074

How to change it?

**Comment by char11** [comment]
Patch https://pastebin.com/e1N1UBD7
Apk for tests https://ufile.io/mhl4n41u

**Comment by elvvis** [comment]
@char11 unfortunately i cannot install your version. I don't know if it's because i installed a nightly build which is newer than v2019.12. The only error message is: the app cannot be installed.

**Comment by char11** [comment]
Did you uninstall the previous version?

**Comment by hugleo** [comment]
> @char11 unfortunately i cannot install your version. I don't know if it's because i installed a nightly build which is newer than v2019.12. The only error message is: the app cannot be installed.

Apk is assigned using another key. Needs to uninstall nightly build first. Keep one eye on config/data if you need a backup ;-)

**Comment by elvvis** [comment]
I did not uninstall it, where is the config/data stored? I need a backup.

**Comment by NiLuJe** [comment]
`/sdcard/koreader` IIRC

**Comment by elvvis** [comment]
@char11 the patch works perfectly on my tolino epos 2

**Comment by pazos** [comment]
@char11: could you please submit a pull request to base? thanks!!!

**Comment by char11** [comment]
I hope I did it the right way.
https://github.com/koreader/koreader-base/pull/1029
