### ISSUE TITLE
This is how Arabic characters appear after the last update on kobo aura one :(

### ISSUE THREAD

**Issue by hgrain86** [koreader/koreader#5545]
* KOReader version: v 2019.10
* Device: kobo aura one

#### Issue
Arabic letters look mirrored
I cant find arabic language in the languages list
#### Steps to reproduce
![photo_2019-10-29_00-01-38](https://user-images.githubusercontent.com/51149380/67721490-4f010180-f9df-11e9-8eb6-de651d50ef7a.jpg)
![photo_2019-10-29_00-01-33](https://user-images.githubusercontent.com/51149380/67721491-4f999800-f9df-11e9-87fb-bf65ee462f2a.jpg)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
What do you mean by the last update? As in that part that says "KOReader version:" that you left empty? ^_^

**Comment by Frenzie** [comment]
Also pinging @WaseemAlkurdi

**Comment by NiLuJe** [comment]
As far as the UI is concerned, the symbols font may be polluting some needed PUA codepoints, inserting Noto Sans Arabic UI *above* it in the fallback should take care of that.

It shouldn't have any impact on CRe, though, as CRe shouldn't ever touch that font.

**Comment by Frenzie** [comment]
Btw, if this is in regard to the screenshots from https://github.com/koreader/koreader/issues/5359#issuecomment-544586459 then that's something @poire-z is still working on.

**Comment by Frenzie** [comment]
I've been using that as the default since you introduced it. :-)

**Comment by WaseemAlkurdi** [comment]
@hgrain86 Could you upload or give us a link to some of the files you're using as to reproduce the issue?

**Comment by WaseemAlkurdi** [comment]
@poire-z Boom! It works with FreeSerif! 
I didn't find Noto Sans Arabic UI, but that's because I'm using the latest stable release instead of the nightly. Should be rectified by next month.
As for the choice of font kerning, perhaps we can make `crengine` quickly parse a file for RTL characters. If they are found, font kerning would be enabled, otherwise, it would be kept disabled.
Failing that, we can make it a question the first time the user opens an ePub file? It can go like this:
```
Font Kerning
Font kerning can be configured to allow for faster file opening if you only read files in Western languages. 
However, this would cause characters to be incorrectly displayed in RTL languages.
Do you want to enable font kerning? (Yes, No)
```

**Comment by Frenzie** [comment]
> As for the choice of font kerning, perhaps we can make crengine quickly parse a file for RTL characters. If they are found, font kerning would be enabled, otherwise, it would be kept disabled.

EPUBs come with a language set in metadata. There's no need to be difficult about it.

<img src=https://user-images.githubusercontent.com/202757/67944014-b5eb0a00-fbdb-11e9-88fa-2e1c6128a7a6.png width=40%>

> Failing that, we can make it a question the first time the user opens an ePub file. It can be like this:

Meh, it should just be enabled by default. :-)

**Comment by poire-z** [comment]
We can't trust the EPUB language for that (and there is none with HTML files), as some english book may have large sections of arabic.
And parsing for RTL chars would trigger the slow _best_ if there's a single arabic or hebrew char in a large book - while people (like me) that don't read any of these would be fine with non-joined arabic :)

So I guess _best_ should be the default to do the right thing in all cases - and people who really want speed can set themselves an other default.

**Comment by Frenzie** [comment]
HTML should normally set lang and dir on the root element.

**Comment by poire-z** [comment]
Proposed in #5553 - with some worry about its relation to Font hinting.

**Comment by hgrain86** [comment]
> You can see that the content is actually "there", because tapping and holding on a word produces a lookup window with the actual word (albeit reversed and not connected).
> This is a screenshot from the latest KOReader (2019.10) with the test file below.
> ![image](https://user-images.githubusercontent.com/15712695/67935002-ac5ca480-fbd1-11e9-8ad0-28c91ca52399.png)

![photo_2019-11-01_02-34-21](https://user-images.githubusercontent.com/51149380/67994842-2469af80-fc50-11e9-9083-4ebe55e36af0.jpg)
Now its ok
thank u all so so so so >>>>>> much :)

**Comment by poire-z** [comment]
To get rid of the ????? at the top of that page, you should set a fallback font (by long-press on another font name), like NotoSans if these are latin characters, or NotoSansCJK if these are symbols, or FreeSerif if these are some other "foreign" scripts.

**Comment by poire-z** [comment]
The filenames in arabic should be displayed ok after #5598, so in tomorrow's nightly.
Need more work for a full RTL Arabic UI, that should be coming soon.
