### ISSUE TITLE
Android crash on startup

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#5547]
* KOReader version: 21c5d58 but it goes back earlier
* Device: Android

#### Issue
I haven't had the time to run ADB yet. Nothing immediately jumps out to me about the commits, maybe one of those base things like https://github.com/koreader/koreader-base/pull/997?

https://github.com/koreader/koreader/compare/v2019.10...21c5d58

**Comment by NiLuJe** [comment]
I had -19-g8d28164 running fine, FWIW ;).

**Comment by NiLuJe** [comment]
And the latest nightly still works on my end? (Android P).

**Comment by Frenzie** [comment]
Really? Hm, that's very odd. I noticed it a couple days ago on my x86 phone and double checked today on my arm phone with the latest build.

If it was just an x86 thing I would've just quietly fixed it but since I may not be able to look at it for another few days I figured I'd open an issue in the meantime.

**Comment by Frenzie** [comment]
Alright, I'm at my PC with debugging tools ready. Looks like it's caused by #5508.

```
10-29 17:42:36.819  3138  3155 E KOReader: [NativeThread]: failed to run script: frontend/apps/filemanager/filemanagerutil.lua:33: attempt to index local 'home_dir' (a function value)
```

**Comment by Frenzie** [comment]
So that must mean caused by #5488, exposed to me by #5508.

**Comment by NiLuJe** [comment]
`local home_dir = G_reader_settings:readSetting("home_dir") or filemanagerutil.getDefaultDir()`

->

`local home_dir = G_reader_settings:readSetting("home_dir") or self:getDefaultDir()`

Or something?

(I do have a home dir set, which explains why I'm not seeing it).

**Comment by Frenzie** [comment]
I think it should just read this:

```diff
diff --git a/frontend/apps/filemanager/filemanagerutil.lua b/frontend/apps/filemanager/filemanagerutil.lua
index a2bcf019..5691b958 100644
--- a/frontend/apps/filemanager/filemanagerutil.lua
+++ b/frontend/apps/filemanager/filemanagerutil.lua
@@ -11,7 +11,7 @@ local filemanagerutil = {}
 
 function filemanagerutil.getDefaultDir()
     if Device:isAndroid() then
-        return Device.external_storage
+        return Device.external_storage()
     elseif Device:isCervantes() then
         return "/mnt/public"
     elseif Device:isKindle() then
```

I'll test it momentarily.

**Comment by NiLuJe** [comment]
Or that, yeah :D.

**Comment by Frenzie** [comment]
Wow, things look really different on this device following some of those recent changes.

![Screenshot_1572367826](https://user-images.githubusercontent.com/202757/67789949-29263c00-fa75-11e9-9102-403a7bb8a3d9.png)

**Comment by Frenzie** [comment]
Yeah, I assume that now it's not displaying as many items per page, which is less than ideal.
