### ISSUE TITLE
Touchscreen toggle with camera button request

### ISSUE THREAD

**Issue by jscris** [koreader/koreader#5558]
* KOReader version: 2019.08 and 2019.10
* Device: Onyx Boox Nova Pro

Currently the camera button toggles the touch off/on and goes a page forward (or back (depending on settings) with each click. Would really like the ability to either toggle that function off/on or turn it off completely as it interferes with the way I use my remote. Camera button mapped to page forward only.  Thank you!

**Comment by poire-z** [comment]
See https://github.com/koreader/koreader/pull/5164#issuecomment-548596796 , may be you can solve your issue by just creating `koreader/settings/event_map.lua` with something like
```lua
return {
   [27] = "IgnoreMe", -- dummy event name, or some other name you want it to generate
   [SomeOtherKeyCode] = "Camera",
}
```

**Comment by jscris** [comment]
Since I wasn't able to get that to work (very likely did something wrong) I rolled back to 2019.07. Hopefully someone will be able to make it optional as I'd love to be able to have some of the recent changes. :) Thanks for the suggestion.

**Comment by poire-z** [comment]
Well, I just tested it, and dropping the file `event_map.lua` contained in this [event_map_lua.zip](https://github.com/koreader/koreader/files/3799754/event_map_lua.zip), in `/sdcard/koreader/settings/`, make my camera button do nothing (while it would toggle and display a popup "touchscreen disabled" previously).

Dropping the one contained in this [event_map_lua_PgFwd.zip](https://github.com/koreader/koreader/files/3799760/event_map_lua_PgFwd.zip) makes the Camera button do as the Volume up button: move one page forward.
```lua
return {
   [27] = "LPgFwd", -- just like [24] VOLUME_UP
}
```

**Comment by jscris** [comment]
Almost. I need the second one, but what it does for me is go one page back and one forward in quick succession, and end up on the same page. No popup, though. :)

**Comment by poire-z** [comment]
Well, dunno more than that. Could be your remote is sending 2 keycodes?
For reference, if you wanna try some other combinations, the keycodes and events for android that you can use or override in your `event_map.lua` are:
https://github.com/koreader/koreader/blob/6baa2af5fb87b6decb525cd58cf413ee1f647cb3/frontend/device/android/event_map.lua#L9-L33

**Comment by jscris** [comment]
Thank you.  It's always worked fine for page forward until that one change, so have no idea about sending two keycodes. I Appreciate the help! Obviously I don't  know what I'm doing. ;)

**Comment by jscris** [comment]
Woohoo! When I changed LPgFwd to LPgBack (I have the volume reversed) it was going two forward, so seemed like it must be picking the keycode up from two places, so I changed LPgFwd to "Down" (since I thought that would do nothing) and it works now, no popup!  Thank you so much!! I still don't know where that other code is coming from, but at least the popup was killed. :)

**Comment by pazos** [comment]
@jscris: from your original issue it seems that the big button generates two events. Camera + PgFwd.

@poire-z: I'm going to add this info to the wiki. Which is, in your opinion, the best way to proceed?

1. as-is: add a custom event map to disable the touchscreen toggle/notification
2. revert the ts toggle and provide specific instructions to enable it with a custom event map.

Thanks!!

**Comment by jscris** [comment]
I guess that would depend on whether more people find it useful than not. Personally, I'd rather see it an option to be enabled.  Thanks for asking. :)

**Comment by poire-z** [comment]
> Which is, in your opinion, the best way to proceed?

I dunno, I'm not really that familiar with android, and how people usually expect HW keys and gadgets to work - so I can't say which is best.
But I can imagine people may hit their camera key by error just manipulating their device, not seeing the "touchscreen disabled" popup, and being stuck with koreader not reacting to touch, not knowing why. (But ok, exiting with the bottom soft key and relaunching make it work again.)
So, may be option 2. is the safest (but more work for you :)

But may be it's just as easy to add a checkbox in `Gear > Navigation > Camera key toggles touch screen`, (if `isAndroid`) and just wrap:
https://github.com/koreader/koreader/blob/6baa2af5fb87b6decb525cd58cf413ee1f647cb3/frontend/device/input.lua#L326-L327
with `if G_reader_settings:isTrue("camera_key_toggles_touchscreen") then`.

**Comment by jscris** [comment]
That sounds perfect.

**Comment by pazos** [comment]
created https://github.com/koreader/koreader/wiki/Android-tips-and-tricks
