### ISSUE TITLE
Checkbox inverted: "Reclaim bar height from bottom margin"

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#5561]
* KOReader version: v2019.10
* Device: kobo clara hd

#### Issue
seem like the bar height is reclaimed when "Reclaim bar height from bottom margin" is OFF

#### Steps to reproduce
1) open a e-book, and find a page when a line of text goes under the bottom status bar
2) top menu > gear (3rd item) > Status Bar > Settings
3) check "Reclaim bar height from bottom margin"
4) observe the text goes under the status bar (ugly rendering)
5) uncheck "Reclaim bar height from bottom margin"
6) observe that margin was applied and the line didn't show up (nice and beautiful !!!)

I think items 4) and 6) should be swapped
and I guess the meaning of the check is reversed
so the margin is applied when the checkbox is UNchecked, while it should be the other way around;

I think this checkbox should be ON by default (for fresh installations) so that the last rendered line wasn't cut on half horizontally, it would be better to apply the margin and not render it at all

![photo_2019-11-02_10-41-52](https://user-images.githubusercontent.com/4983083/68067817-a3004300-fd5d-11e9-9c3d-2d6f40dc0022.jpg)

![photo_2019-11-02_10-41-51](https://user-images.githubusercontent.com/4983083/68067820-a98eba80-fd5d-11e9-89ce-36c183363286.jpg)

**Comment by NiLuJe** [comment]
No, it does just what it says on the tin, and is disabled by default ;).
