### ISSUE TITLE
v2019.10: after update+restart, all my settings got clear (reset / lost)

### ISSUE THREAD

**Issue by worldexplorer** [koreader/koreader#5562]
* KOReader version: v2019.10
* Device: kobo clara hd

#### Issue
I OTA-updated to v2019.10, first restart was okay; after full reboot, I had to go again everywhere and set margins, taps, font, status bar configuration, style tweaks - everything! I kept the settings for longer than 1 year and I was so used to them! now I can't even reproduce my convenient formatting :(

#### Steps to reproduce
1) upgrade via OTA to v2019.10
2) cold reboot your e-reader
3) ("koreader restart" is not enough to get your settings completely wiped out)

**Comment by worldexplorer** [comment]
probably my instance of sqlite had a broken database: when I got to clear the cache, it crashed; may be settings were stored in the same sqlite database where caches are stored, too; I wanted to create another issue on this "crash when clearing caches" but it happened just once after the upgrade to v.2019.10 (I didn't try to clear caches with other versions); sqlite crash happened on:
1) go to file explorer
2) top menu > 3rd menu item (wrench + screwdriver) > Developer options > Clear readers' caches
3) sqlite error with time bomb screen :)

**Comment by worldexplorer** [comment]
what has also changed is "show file names in OPEN LAST DOCUMENT" had disappeared at all; I wish I saw the file name of my last document straight from the menu (half of the width of the screen is available to have the file name printed) without the need to click to HISTORY and check what exactly was my last file I was reading (please bring back this feature and print the name of my previously opened file name right in the menu item next to "Open previous document <WHICH ONE RIGHT HERE>")

probably one extra line in the config file (sql table) confused the whole config settings parser, it didn't recognize its own config file, and the whole settings got reset

**Comment by Frenzie** [comment]
The settings are stored separately in settings.reader.lua. If the file were to be damaged a backup should be used (settings.reader.lua.old), unless it were somehow damaged in a way that preserved a valid syntax.

The cache folder doesn't contain any SQLite. That's in settings. It's not really clear to me how clearing cache could cause it to crash, maybe if it was working on covers/metadata while you did it?

**Comment by poire-z** [comment]
Some notes:
- the settings that you lost are not stored in any sqlite database, but in a settings.reader.lua text file (that it's always good to backup from time to time :) - and we have some kind of one back recovery by keeping the previous version as settings.reader.lua.old, and using it if the new one is unreadable - but I guess it's too later for you now and both are reset
- Developer options > Clear readers' caches only clears books cache files in koreader/cache/ - shouldn't cause any issue
- The only sqlite databases are for book reading statistics, and thumbnails/metadata cache for the various File browser and history view modes (mosaic, lists) - these can be trashed and corrupted, and should be re-created/re-populated when starting from 0 without any loss (except the time to refresh the thumbnails while browsing).

> sqlite error with time bomb screen :)

Might be good to share your full crash.log and give the data/time at which bad things happened

> please bring back this feature and print the name of my previously opened file name right in the menu 

You can enable it: `File browser > top left menu > Display mode > Other settings > Show filename in open last/previous menu items`

**Comment by worldexplorer** [comment]
> You can enable it: File browser > top left menu > Display mode > Other settings > Show filename in open last/previous menu items

yes it's there! I enabled it, thank you! I've just lost this setting

**Comment by NiLuJe** [comment]
From which version was the upgrade done?

**Comment by poire-z** [comment]
Corrupted/empty settings on crash/freeze should hopefully no more happen - and losing settings and annotations should now be limited to losing 15mn of annotations & page progress (that one can reduce to 5mn via the menu), thanks to #5678 and #5687 (January 2020).
