### ISSUE TITLE
No TOC in Mobi

### ISSUE THREAD

**Issue by GianniGi** [koreader/koreader#5566]
* KOReader version: v2019.10
* Device: kindle pw 2019

#### Issue
No toc

#### Steps to reproduce
Open a book, search for the TOC, and the TOC is empty, while calibre and any ebook reader shows that there's a TOC in the book.

I've opened many books in the koreader, but none shows sign of a TOC or even allows to jump at the next chapter using the gesture.

**Comment by pazos** [comment]
Not familiarized with the issue. Are you aware of https://github.com/koreader/koreader/wiki/Alternate-TOC ?

**Comment by NiLuJe** [comment]
More details would be nice (i.e., format, or even a repro sample, scrambled if need be).

**Comment by GianniGi** [comment]
It's a issue that I've found with each ebook that I've uploaded (I only use calibre). I know about the alternate toc but it doesn't work either. As soon as I'm home I will upload an ebook for testing. Meanwhile if you want you can upload an ebook that works, so we double check the compatibility (please tell me if I need to use calibre for the upload or if it's possible to create directly a directory on the kindle, i the documents folder). Thanks.

**Comment by Frenzie** [comment]
Pretty much any EPUB I've ever tried had a TOC. What kind of book format are you using?

Here's our test suite (including a couple of EPUBs):
https://github.com/koreader/test-data

**Comment by GianniGi** [comment]
Mmmmm. So calibre only sends mobi files to the kindle (it converts them by default before sending them), and koreader isn't compatible with the mobi toc. This is quite a crazy situation.

I've uploaded your test ebub manually and it works, but if I use calibre to send the file to the main memory, it converts it to mobi and koreader doesn't read the toc, which in fact is in the mobi file (verified with calibre and any epub reader).

I've uploaded a mobi file which has a functional toc, but isn't compatible with koreader.
[$canc.zip](https://github.com/koreader/koreader/files/3813747/canc.zip)

So can you confirm that the only way to have a toc while using koreader is to have only epubs? And how am I supposed to upload them without calibre? Do you upload them one by one???

thanks

**Comment by Frenzie** [comment]
> So can you confirm that the only way to have a toc while using koreader is to have only epubs?

Well, no. ;-) At the very least, TOCs work in EPUB, FB2, PDF and DjVu. Whether they work in Mobi I don't know, but I can confirm they don't work in the file you attached. It's possible that it's supported in Mobi but only for version x and not for Kindle File Format or some such. We'd have to check the code. In any case, EPUB is recommended.

**Comment by GianniGi** [comment]
Sorry to bother you again. Since calibre doesn't copy epubs to the kindle, how do you manage hundreds of ebooks without using calibre?

**Comment by Frenzie** [comment]
I use neither a Kindle nor calibre, so I don't know much about that. Perhaps @robert00s or @NiLuJe can share something about Kindle use.

KOReader is based around files and folders, which is the way I like it. Drop a file in a folder, plain and simple. :-) If I wanted things to be the same on my computer and my Kobo Aura H2O I'd set up Syncthing, but I'm fine just copying over some files occasionally.

Once in a blue moon I might connect using USB to copy over some files, but usually I use [SFTP](https://github.com/koreader/koreader/wiki/SSH#connecting-through-sftp---without-password). (I used to run that outside of KOReader, nowadays it's integrated. Also on Kindle if I'm not mistaken?)

**Comment by GianniGi** [comment]
I've found on the calibre forum the recommended solution:

"Right click on the kindle icon in calibre when it is connected, choose
customize this device and add epub to the list of allowed formats."

**Comment by Frenzie** [comment]
Nice, I'll close this then. :+1:
