### ISSUE TITLE
Sort Favorites: rewind button grey

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5578]
* KOReader version: v2019.10-38-g9bc1c6f_2019-11-07/  
* Device: KA1

#### Issue
Rewind button is grey for me. All the time, no matter what page number I'm on.

**Comment by robert00s** [comment]
Can you give some screenshots?
I only notice problem with second case.

It's ok (> and >> are black/active).
<img src=https://user-images.githubusercontent.com/22982594/68463303-a2105b00-020e-11ea-9c60-748a30591a69.png width=60%>

Bug (<< should be black/active):

<img src=https://user-images.githubusercontent.com/22982594/68463532-27940b00-020f-11ea-874e-60b78e54e953.png width=60%>

**Comment by gerhaher** [comment]
Yeah, that was what I meant - only this: <<

**Comment by robert00s** [comment]
Thanks. Fix will be ready soon :)
