### ISSUE TITLE
Android 5 & 10 xtext can't find symbol "_Unwind_Resume"

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#5602]
* KOReader version: 89c0bd0
* Device: Android 5 (not an issue on 6 or 9)

#### Issue
```
E/KOReader( 2460): error: [string "dl.lua"]:98: could not find library /data/data/org.koreader.launcher/files/libs/libkoreader-xtext.so
E/KOReader( 2460): [NativeThread]: failed to run script: error loading module 'libs/libkoreader-xtext' from file 'libs/libkoreader-xtext.so':
E/KOReader( 2460): 	dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "libkoreader-xtext.so"...
E/KOReader( 2460): [NativeThread]: Stopping due to previous errors
```

Pinging @poire-z @NiLuJe

**Comment by poire-z** [comment]
Well, quite a few people met that issue https://www.google.com/search?hl=en&num=25&q=%22_Unwind_Resume%22+android.
Some [possible](https://stackoverflow.com/questions/11039360/unwindresume-and-other-link-errors-cross-compiling-for-android) solutions around there - but I don't get much of that. Hope @NiLuJe will :)
You can reproduce it on an Android 5 emulator to check possible solutions?

**Comment by Frenzie** [comment]
It's not entirely clear how functional the Android 5 emulator is. It's slightly less broken than the useless 2.x/4.x series but it happily crashes all by itself. The problem doesn't occur in the Android 4.2 emulator (the only halfway functional 4.x emulator).

But assuming the Android 10 emulator is functional,[1] since Google pays some sliver of attention to the latest release, that one also reproduces the issue:

```
11-17 12:56:33.706  5013  5055 V KOReader: dl.lua - sys_dlopen - loading library /system/lib/libc.so
11-17 12:56:33.706  5013  5055 V KOReader: dl.lua - sys_dlopen - loading library /data/user/0/org.koreader.launcher/files/libs/libkoreader-xtext.so
11-17 12:56:33.706  5013  5055 E KOReader: error: [string "dl.lua"]:40: error opening /data/user/0/org.koreader.launcher/files/libs/libkoreader-xtext.so: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/data/org.koreader.launcher/files/libs/libkoreader-xtext.so"...
11-17 12:56:33.706  5013  5055 D KOReader: try to load module /data/user/0/org.koreader.launcher/files/libs/libkoreader-xtext.so
11-17 12:56:33.706  5013  5055 E KOReader: error: [string "dl.lua"]:98: could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-xtext.so
11-17 12:56:33.706  5013  5055 E KOReader: [NativeThread]: failed to run script: error loading module 'libs/libkoreader-xtext' from file 'libs/libkoreader-xtext.so':
11-17 12:56:33.706  5013  5055 E KOReader: 	dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/data/org.koreader.launcher/files/libs/libkoreader-xtext.so"...
11-17 12:56:33.706  5013  5055 E KOReader: [NativeThread]: Stopping due to previous errors
11-17 12:56:33.709  5013  5013 D KOReader: [MainActivity] onPause()
11-17 12:56:33.709  5013  5013 D KOReader: [NativeGlue]: Pause: 0xd715b100
11-17 12:56:33.786  1863  1980 E InputDispatcher: channel '2c374b org.koreader.launcher/org.koreader.launcher.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-17 12:56:35.703  1805  1805 E netmgr  : Failed to open QEMU pipe 'qemud:network': Invalid argument
11-17 12:56:35.703  1805  1805 E netmgr  : WifiForwarder unable to open QEMU pipe: Invalid argument
11-17 12:56:37.379  1863  2741 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
```

[1] Not a given, I mean what's this @#$#@$? It could also mean the way the program updates the screen is semi-borked in Android 10.

<img src=https://user-images.githubusercontent.com/202757/69007124-f23b9b80-0939-11ea-9107-5edf6418fd76.png width=30%><img src=https://user-images.githubusercontent.com/202757/69007125-f23b9b80-0939-11ea-97a3-17a189a276f7.png width=30%>

**Comment by Frenzie** [comment]
Yeah, so the Android 10 emulator doesn't take screenshots. I'm inclined to think the emulator is broken and not us…

![Screenshot_2019-11-17_13-00-47](https://user-images.githubusercontent.com/202757/69007152-52cad880-093a-11ea-8776-8ee4dcee4d4e.png)

**Comment by NiLuJe** [comment]
Is it built by CXX and properly linked against stdc++?

**Comment by Frenzie** [comment]
I don't know, I left this stuff mostly to you guys. ;-)

**Comment by poire-z** [comment]
Nope, I removed that at one point, as I didn't need any of it:
```
@@ -158,7 +158,7 @@ $(OUTPUT_DIR)/libs/libkoreader-xtext.so: xtext.cpp \
        -I$(HARFBUZZ_DIR)/include/harfbuzz \
        -I$(FRIBIDI_DIR)/include \
        -I$(LIBUNIBREAK_DIR)/include \
-       $(DYNLIB_CXXFLAGS) -static-libstdc++ -o $@ $^
+       $(DYNLIB_CXXFLAGS) -o $@ $^
```
Would it be needed? Added only for android 5?

**Comment by Frenzie** [comment]
I dunno about static-libstdc++ but that DYNLIB_CXXFLAGS might well be relevant. I'll check soon.

**Comment by Frenzie** [comment]
Oh, never mind, you meant you removed  `-static-libstdc++`. Anyway, still checking.

**Comment by Frenzie** [comment]
The line looks different for me btw?

```
	$(DYNLIB_CXXFLAGS) -Wall -o $@ $^
```

**Comment by Frenzie** [comment]
Changed it like this (and made sure it rebuilt), same error.

```diff
diff --git a/Makefile b/Makefile
index 909b15e..2ad8172 100644
--- a/Makefile
+++ b/Makefile
@@ -158,7 +158,7 @@ $(OUTPUT_DIR)/libs/libkoreader-xtext.so: xtext.cpp \
        -I$(HARFBUZZ_DIR)/include/harfbuzz \
        -I$(FRIBIDI_DIR)/include \
        -I$(LIBUNIBREAK_DIR)/include \
-       $(DYNLIB_CXXFLAGS) -Wall -o $@ $^
+       $(DYNLIB_CXXFLAGS) -static-libstdc++ -Wall -o $@ $^
 ifdef DARWIN
        install_name_tool -change \
                `otool -L "$@" | grep "libluajit" | awk '{print $$1}'` \
```

**Comment by poire-z** [comment]
( > The line looks different for me btw? - yes, I added that `-Wall` later)
What with `-lgcc_eh` (?) as suggested [there](https://stackoverflow.com/questions/11039360/unwindresume-and-other-link-errors-cross-compiling-for-android) ?

**Comment by Frenzie** [comment]
/home/frans/src/kobo/koreader/base/toolchain/android-toolchain-x86/bin/../lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: cannot find -lgcc_eh


(Also GCC anything is a hack that should be avoided if at all possible, because Clang.)

**Comment by Frenzie** [comment]
Yeah, there's no such thing as a gcc_eh.

![Screenshot_2019-11-17_16-25-12](https://user-images.githubusercontent.com/202757/69009579-e3171680-0956-11ea-842f-9ee3e8dcb9d0.png)

**Comment by NiLuJe** [comment]
@Frenzie: There should be (a static library).

```
┌─(niluje@illyria:pts/8)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(/var/tmp/niluje/koreader/koreader-emulator-x86_64-pc-linux-gnu-debug/koreader)─┐
└─(0.17:57%:17:52:%)── find ~/x-tools/arm-nickel-linux-gnueabihf -type f -name '*gcc_eh*'                                                                                                                                                                                                                                                               ──(Sun, Nov 17)─┘
/home/niluje/x-tools/arm-nickel-linux-gnueabihf/lib/gcc/arm-nickel-linux-gnueabihf/4.9.4/libgcc_eh.a
```

(That's GCC's unwinder, I can't think of any reason why Android would do away with it when not using Clang).

**Comment by NiLuJe** [comment]
That said,n Android being Android, it wouldn't surprise me all that much if they did some funky stuff with that ^^.

**Comment by Frenzie** [comment]
@NiLuJe Well, there's exactly one in my TC dir and it's not from Android. :-P

![Screenshot_2019-11-17_18-01-39](https://user-images.githubusercontent.com/202757/69010869-5a06dc00-0964-11ea-8407-61e49552ec61.png)

**Comment by NiLuJe** [comment]
`-static-libstdc++` might help here, too, in case libunwind's messing with GCC or something.

**Comment by Frenzie** [comment]
Doesn't, already tried. ;-)

**Comment by NiLuJe** [comment]
Random weird-ass flags to try: `-Wl,--exclude-libs=libgcc.a`.

libcrengine pulls in the exact symbols and dosn't blow up, so I'm assuming something loaded earliers pulls 'em in, and xtext just happens to be loaded too soon.

(Also, Android is terrible).

**Comment by pazos** [comment]
Yup, Android emulator is pretty broken for api 21. The only solution for testing in that specific platform is using one of the heavy modified emulators, like https://www.bignox.com/ or testing it on some legacy amazon tablets.

**Comment by poire-z** [comment]
Does this still happen? (no user report over the last 2 weeks)

**Comment by Frenzie** [comment]
Well of course. :-P

It's probably that Android 5 is a bit old and Android 10 is a bit new.

**Comment by poire-z** [comment]
ok :/
I still have no idea how to solve the root cause.
But for next release, would we need to check it's supported on Android (so, no nice Arabic if not supported), and use something like:
`use_xtext = G_reader_settings:nilOrTrue("use_xtext") and Device:supportsXText()`
which would be `yes` on all devices, except on Android where it would be some kind of `pcall(require("libs/libkoreader-xtext"))` if that works without crashing?

**Comment by NiLuJe** [comment]
It's possibly worth trying with a clang build, it might help...

**Comment by Frenzie** [comment]
If only we had that Clang build stuff setup yet… ;-P

**Comment by poire-z** [comment]
> there's no such thing as a libgcc_eh.a.

`-lgcc_s / libgcc_s.a` maybe ?

https://bugs.chromium.org/p/chromium/issues/detail?id=330864
> I can fix this by adding the following to libc++ link command line:
  -lgcc_s lib/libc++abi.so -lpthread -Wl,-z,defs

**Comment by poire-z** [comment]
And if we add that in xtext.h or xtext.cpp (https://stackoverflow.com/questions/10419801/undefined-reference-to-unwind-resume-and-gxx-personality-v0), does it compile, and then still crash?
`void * _Unwind_Resume =0;`

**Comment by NiLuJe** [comment]
We should already be linking against that (because g++/-lstdc++), so if it
changes anything, android TCs are gloriously broken ;) '

**Comment by Frenzie** [comment]
libgcc_s.a is for ARM. I don't know atm if it's even a problem on ARM, so if not that could also explain the lack of real life reports.

**Comment by NiLuJe** [comment]
It's for everyone, that's gcc's unwinder ;). Also what I meant by "that"
earlier.

**Comment by Frenzie** [comment]
My bad, I accidentally included the PocketBook TC in my search and misinterpreted its arm as Android ARM. So anyway, nothing split out like that exists in Android.

**Comment by poire-z** [comment]
Oh, that issue for now happens only on x86/64 android 5 & 10 emulators ?
Anyone has/can test that on a Android 5 or 10 phone? (I can't)

**Comment by NiLuJe** [comment]
Which one's 5 already? Lollipop or Marshmallow?

**Comment by Frenzie** [comment]
Lollipop is 5, Marshmallow is 6.

**Comment by NiLuJe** [comment]
Cool, I might be able to check on an old nexus then :).

**Comment by yparitcher** [comment]
latest nightly `koreader-android-arm-v2019.11-50-g3d19149_2019-11-30` works fine on 5.1.1

**Comment by pazos** [comment]
@NiLuJe: Not sure what's needed to build with clang besides

```diff
--- a/thirdparty/cmake_modules/CMakeCross.cmake
+++ b/thirdparty/cmake_modules/CMakeCross.cmake
@@ -31,8 +31,13 @@ if($ENV{CROSS_TC} MATCHES "^arm-.*")
 endif()
 
 # set compiler name
-set(CMAKE_C_COMPILER $ENV{CROSS_TC}-gcc)
-set(CMAKE_CXX_COMPILER $ENV{CROSS_TC}-g++)
+if($ENV{ANDROID})
+       set(CMAKE_C_COMPILER $ENV{CROSS_TC}-clang)
+       set(CMAKE_CXX_COMPILER $ENV{CROSS_TC}-clang++)
+else($ENV{ANDROID})
+       set(CMAKE_C_COMPILER $ENV{CROSS_TC}-gcc)
+       set(CMAKE_CXX_COMPILER $ENV{CROSS_TC}-g++)
+endif($ENV{ANDROID})
```

**Comment by NiLuJe** [comment]
Probably nothing much, except getting rid of the legacy flags crap like we
discussed in the aarch64 issue ;).

**Comment by Frenzie** [comment]
Like @NiLuJe said probably not too much in theory, but in practice you'll keep hitting GCC specific workarounds for a bit. (Also that wouldn't affect xtext anyway. ;-))

**Comment by NiLuJe** [comment]
@Frenzie: Hmm, why wouldn't it? It uses a completely different unwinder (libunwind) ;).

And which GCC-specific workarounds do you have in mind?

**Comment by Frenzie** [comment]
Because it couldn't care less about CMake. The correct location would be [here](https://github.com/koreader/koreader-base/blob/10cfb8379d6badfaa4a9599d6a659cc1983a0535/Makefile.defs#L126-L136) or somewhere equivalent.

> And which GCC-specific workarounds do you have in mind?

I don't have anything in mind (because I'm on Windows atm) but there's plenty of if android then do some workaround that includes stuff that won't work on Clang. This doesn't show on the Clang build because it's not Android.

**Comment by NiLuJe** [comment]
Oh, yeah, right, I glossed over the snippet ^^. That said, we'd need to do *both*(i.e., Makefile.defs & the CMake cross file) ;).

At a quick glance (i.e., `rg -A10 ANDROID thirdparty/*/CMake*`):

* The libtool stuff should be harmless
* sdcv has a `static-libgcc` that won't make sense anymore, but will *probably* be ignored.
* OpenSSL's gcc 4.9 patch *should* be harmless

**Comment by pazos** [comment]
@Frenzie @NiLuJe: building 3rd party libs with clang using the cmake cross file mod works fine with both r15c and r17c, while with gcc it fails miserably with r17c.

About the luajit-launcher I found a weird bug. It builds fine by itself, given the following changes:

```diff
diff --git a/jni/Application.mk b/jni/Application.mk
index 695ec7e..fef5edc 100644
--- a/jni/Application.mk
+++ b/jni/Application.mk
@@ -1 +1,3 @@
 # see https://developer.android.com/ndk/guides/application_mk
+
+NDK_TOOLCHAIN_VERSION := clang
diff --git a/jni/luajit/luajit-2.0 b/jni/luajit/luajit-2.0
--- a/jni/luajit/luajit-2.0
+++ b/jni/luajit/luajit-2.0
@@ -1 +1 @@
-Subproject commit f0e865dd4861520258299d0f2a56491bd9d602e1
+Subproject commit f0e865dd4861520258299d0f2a56491bd9d602e1-dirty
diff --git a/jni/luajit/mk-luajit.sh b/jni/luajit/mk-luajit.sh
index 49917c6..f60af06 100755
--- a/jni/luajit/mk-luajit.sh
+++ b/jni/luajit/mk-luajit.sh
@@ -51,7 +51,7 @@ case "$1" in
         NDKP=${TCVER[0]}/prebuilt/${HOST_ARCH}/bin/arm-linux-androideabi-
         NDKF="--sysroot ${NDK}/platforms/android-${NDKABI}/arch-arm"
         rm -rf "$DEST"
-        make -C luajit-2.0 install HOST_CC="gcc -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="$NDKP" TARGET_FLAGS="$NDKF" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
+        make -C luajit-2.0 install HOST_CC="clang -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="$NDKP" TARGET_FLAGS="$NDKF" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
         ;;
     armeabi-v7a)
         # Android/ARM, armeabi-v7a (ARMv7 VFP)
@@ -60,7 +60,7 @@ case "$1" in
         NDKP=${TCVER[0]}/prebuilt/${HOST_ARCH}/bin/arm-linux-androideabi-
         NDKF="--sysroot ${NDK}/platforms/android-${NDKABI}/arch-arm"
         NDKARCH="-march=armv7-a -mfloat-abi=softfp -Wl,--fix-cortex-a8"
-        make -C luajit-2.0 install HOST_CC="gcc -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="$NDKP" TARGET_FLAGS="${NDKF} ${NDKARCH}" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
+        make -C luajit-2.0 install HOST_CC="clang -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="$NDKP" TARGET_FLAGS="${NDKF} ${NDKARCH}" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
         ;;
     mips)
         # Android/MIPS, mips (MIPS32R1 hard-float)
@@ -68,7 +68,7 @@ case "$1" in
         TCVER=("${NDK}"/toolchains/mipsel-linux-android-4.*)
         NDKP=${TCVER[0]}/prebuilt/${HOST_ARCH}/bin/mipsel-linux-android-
         NDKF="--sysroot ${NDK}/platforms/android-${NDKABI}/arch-mips"
-        make -C luajit-2.0 install HOST_CC="gcc -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="${NDKP}" TARGET_FLAGS="$NDKF" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
+        make -C luajit-2.0 install HOST_CC="clang -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="${NDKP}" TARGET_FLAGS="$NDKF" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
         ;;
     x86)
         # Android/x86, x86 (i686 SSE3)
@@ -76,7 +76,7 @@ case "$1" in
         TCVER=("${NDK}"/toolchains/x86-4.*)
         NDKP=${TCVER[0]}/prebuilt/${HOST_ARCH}/bin/i686-linux-android-
         NDKF="--sysroot ${NDK}/platforms/android-${NDKABI}/arch-x86"
-        make -C luajit-2.0 install HOST_CC="gcc -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="$NDKP" TARGET_FLAGS="$NDKF" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
+        make -C luajit-2.0 install HOST_CC="clang -m32" CFLAGS="-O2 -pipe" HOST_CFLAGS="-O2 -pipe -mtune=generic" LDFLAGS="" HOST_LDFLAGS="" TARGET_CFLAGS="${CFLAGS}" TARGET_LDFLAGS="${LDFLAGS}" CROSS="$NDKP" TARGET_FLAGS="$NDKF" TARGET_SYS=Linux DESTDIR="$DEST" PREFIX=
         ;;
     *)
         echo 'specify one of "armeabi", "armeabi-v7a", "mips", "x86" or "clean" as first argument'
```

I build with `ANDROID_ARCH=x86 NDK=/home/pazos/Escritorio/koreader/base/toolchain/android-ndk-r15c/ make debug` without problem.

But when I try to build KO (with `ANDROID_ARCH=x86 ./kodev release --ignore-translation android`) I find the following error:

```make
Using NDKABI 14.
Detected NDK version 15...
make[3]: Entering directory `/home/pazos/Escritorio/koreader/platform/android/luajit-launcher/jni/luajit/luajit-2.0'
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[4]: Entering directory `/home/pazos/Escritorio/koreader/platform/android/luajit-launcher/jni/luajit/luajit-2.0/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
DYNASM    host/buildvm_arch.h
make[4]: host/minilua: Command not found
make[4]: *** [host/buildvm_arch.h] Error 127
make[4]: Leaving directory `/home/pazos/Escritorio/koreader/platform/android/luajit-launcher/jni/luajit/luajit-2.0/src'
make[3]: *** [src/luajit] Error 2
make[3]: Leaving directory `/home/pazos/Escritorio/koreader/platform/android/luajit-launcher/jni/luajit/luajit-2.0'
make[2]: *** [build-luajit] Error 2
make[2]: Leaving directory `/home/pazos/Escritorio/koreader/platform/android/luajit-launcher'
make[1]: *** [androidupdate] Error 2
make[1]: Leaving directory `/home/pazos/Escritorio/koreader'
Makefile:447: recipe for target 'update' failed
make: *** [update] Error 2
```

**Comment by pazos** [comment]
Oh, and a hint to build, in fact, 1st party code with clang is appreciated (I guess that's what needs to be modified in Makefile.defs) but I'm not familiar with the code there.

**Comment by NiLuJe** [comment]
@pazos: HOSTCC *may* be passing a --target (or something causing Clang to generate target-machine-code (i.e., ARM) instead of host-machine-code (i.e., probably x64).

Can you run file on it to check? And run the build in verbose to see what exactly HOSTCC is doing?

Something like
```export VERBOSE=1
export V=1``` should do it.

For first-party code, Makefile.defs is the place to be, tweaking that should ensure everything trickles down properly.

**Comment by NiLuJe** [comment]
I'm vaguely hoping Android's clang can actually build x86/x64 code, otherwise, a simple solution is to keep using gcc as HOSTCC ;).

**Comment by NiLuJe** [comment]
And re: Makefile.defs, I *think* I covered everything relevant in the AArch64 issue ;).

**Comment by pazos** [comment]
@NiLuJe:

with a standalone build:

```
file jni/luajit/luajit-2.0/src/host/minilua
jni/luajit/luajit-2.0/src/host/minilua: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /system/, not stripped

ldd jni/luajit/luajit-2.0/src/host/minilua
	linux-gate.so.1 (0xf7f7e000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7e4b000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7c6f000)
	/lib/ld-linux.so.2 (0xf7f7f000)
```

with a KOReader build:

```
file jni/luajit/luajit-2.0/src/host/minilua
jni/luajit/luajit-2.0/src/host/minilua: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.2.0, not stripped

ldd jni/luajit/luajit-2.0/src/host/minilua
jni/luajit/luajit-2.0/src/host/minilua: /usr/lib32/libm.so: version `LIBC' not found (required by jni/luajit/luajit-2.0/src/host/minilua)
	linux-gate.so.1 (0xf7ef5000)
	libm.so => /usr/lib32/libm.so (0xf7df9000)
	libdl.so => /usr/lib32/libdl.so (0xf7df4000)
	libc.so => not found
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7c18000)
	/system/bin/linker => /lib/ld-linux.so.2 (0xf7ef6000)
```

**Comment by NiLuJe** [comment]
Oh, multilib... What's the host distro?

**Comment by pazos** [comment]
Ubuntu 18.04

**Comment by NiLuJe** [comment]
Yeah, I have no idea what kind of monstrosity they're doing to handle multilib ;p.

If you can show me the verbose build log from both variants, that may shed some light on this...

**Comment by Frenzie** [comment]
@NiLuJe 

> sdcv has a -static-libgcc that won't make sense anymore, but will probably be ignored.

That's the kind of thing I was thinking of. I'm just saying you'll spend at least 30 minutes to an hour on the conversion as opposed to just flipping a switch, not that I expect it to be difficult per se. ;-) Still, LuaJIT isn't alone in requiring executables/code that runs on x86.

**Comment by pazos** [comment]
> Yeah, I have no idea what kind of monstrosity they're doing to handle multilib, but it doesn't look pretty ;p.
> 
> If you can show me the verbose build log from both variants, that may shed some light on this...

Attaching just the build with the changes mentioned in https://github.com/koreader/koreader/issues/5602#issuecomment-563296855. No other change in base/luajit-launcher

[build.txt](https://github.com/koreader/koreader/files/3942072/build.txt)

As you can see it is a mess of clang compiler checks and gcc. Probably this whole thing is beyond my skills and I'm a clown :smile:

**Comment by NiLuJe** [comment]
Ah. I forgot that LuaJIT is a special snowflake and needs a [patch](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/koreader-luajit-verbose-build.patch) to actually be verbose for real... -_-".

**Comment by NiLuJe** [comment]
And, as @Frenzie mentioned, the CMake cross-file doesn't affect much in practice, mostly everything gets fed the CC set in Makefile.defs, which explains why you're still seeing *a lot* of GCC in there ;).

**Comment by pazos** [comment]
Well. My interest was to have a working simulator on android 10 to experiment a bit with the scoped storage that will be enforced (android 10 if api >= 29, android 11 for all apis).

I'll wait for this issue to be fixed by someone with more knowledge than me.

**Comment by pazos** [comment]
Okay, for my intent, the following workaround does the job:

```diff
diff --git a/xtext.cpp b/xtext.cpp
index 8076ae2..d0bd3a3 100644
--- a/xtext.cpp
+++ b/xtext.cpp
@@ -37,6 +37,20 @@ extern "C"
     }
     #endif
 
+
+// workaround for android insanity
+void * _Unwind_Resume = 0;
+void * _Unwind_DeleteException = 0;
+void * _Unwind_SetGR = 0;
+void * _Unwind_GetIPInfo = 0;
+void * _Unwind_SetIP = 0;
+void * _Unwind_GetLanguageSpecificData = 0;
+void * _Unwind_GetRegionStart = 0;
+void * _Unwind_GetDataRelBase = 0;
+void * _Unwind_GetTextRelBase = 0;
+void * _Unwind_RaiseException = 0;
+void * _Unwind_Resume_or_Rethrow = 0;
+
 // luajit doesn't provide lua_set/getuservalue (unless compiled
 // with LUAJIT_ENABLE_LUA52COMPAT) but these are equivalents
 // for our purpose
```

**Comment by NiLuJe** [comment]
Yeah, that'll probably explode as soon as something throws an exception.
Which, granted, is shouldn't happen here ;).

In fact, building xtext without exceptions handling might also be worth
looking into...

**Comment by pazos** [comment]
> In fact, building xtext without exceptions handling might also be worth
looking into...

I tried with -fno-exceptions but it didn't work

**Comment by poire-z** [comment]
That was long ago and I already don't remember much , but I guess we fixed this issue with https://github.com/koreader/koreader-base/pull/1011 .
Is there still something left to fix on the xtext side ?

**Comment by pazos** [comment]
@poire-z: yup, not sure about the root issue but certainly it doesn't work in android emulators (10 and 11). Devices with android 10 work without issues, but I don't know if there's any device on android 10 based on x86.

Anyways, these new emulators are somehow broken for our purposes and the workaround in https://github.com/koreader/koreader/issues/5602#issuecomment-564158851 works fine in the case we need to test some new api thingy.

So feel free to close, it is a non-issue for me at least.

**Comment by Frenzie** [comment]
I'm not interested in downgrading my x86 Zenfone 2 to Android 5 to see if the same problem occurs on a real device, so sure, let's close it for now. The Android 10 (emulator-only?) thing is quite annoying though.

**Comment by pazos** [comment]
@Frenzie 

>  The Android 10 (emulator-only?) thing is quite annoying though.

Android 11 (Google APIs Intel x86 Atom_64 System Image, rev 8) emulator isn't affect by the xtext bug nor has the artifacts present in https://github.com/koreader/koreader/issues/5602#issuecomment-554738722.

It also supports both arm/x86 apks, so win-win.

**Comment by Frenzie** [comment]
Sweet, I'll check it out… sometime. :-)
