### ISSUE TITLE
Crash during notes export to Evernote

### ISSUE THREAD

**Issue by abdoulayeYATERA** [koreader/koreader#5609]
* KOReader version: v2019.11
* Device: Kobo Format

#### Issue
Crash during notes export to Evernote.
Need your help guys !!! (girls also ^ ^)
Thank's
#### Steps to reproduce
1 - Log with your Evernot account
2 - Export notes to Evernote 
##### `crash.log` (if applicable)
![IMG_20191117_141713](https://user-images.githubusercontent.com/9435855/69068984-00ff7c80-0a26-11ea-9db0-c7b0d5e0b1e2.jpg)

**Comment by abdoulayeYATERA** [comment]
Hmm strange Github behavior...., click on the image to see the crash log in the right orientation...

**Comment by NiLuJe** [comment]
xref: https://www.mobileread.com/forums/showthread.php?p=3913268#post3913268

Regression since https://github.com/koreader/koreader/pull/5431

**Comment by hgrain86** [comment]
also on kobo aura one koreader v2019.11

**Comment by arooni** [comment]
also on pixel xl and fire 10 tablet ; all using 2019.11

**Comment by LucenaWoods** [comment]
Also on PW2: Crashes every time I try to export all notes to local html file.

**Comment by roger64** [comment]
also on Kindle PW3. Koreader crashes and I am back to Kindle.

The crash happens exactly when I try to identify myself and to write the password.

**Comment by mustafa292** [comment]
It was introduced in https://github.com/koreader/koreader/pull/5440/files/7e7feb760dd90abef9f4600a140ad5fc46088f11#diff-d2ad3c080f3901bd500b297d33ce25b1       
https://github.com/koreader/koreader/blob/55f3575a10a07dd0c9a70154c901a1f160efba3c/plugins/evernote.koplugin/clip.lua#L290
`clippings.title` resolves to `clippings.["title"]` not `clippings[title]` as it should be. 

To my defence it was suggested at PR review and I simply clicked "commit suggestion" :)

**Comment by Frenzie** [comment]
That must've been a reflex because elsewhere that was full of clippings["title"], my bad. But don't just click commit suggestion. ;-)

**Comment by 2016201256** [comment]
> It was introduced in https://github.com/koreader/koreader/pull/5440/files/7e7feb760dd90abef9f4600a140ad5fc46088f11#diff-d2ad3c080f3901bd500b297d33ce25b1
> https://github.com/koreader/koreader/blob/55f3575a10a07dd0c9a70154c901a1f160efba3c/plugins/evernote.koplugin/clip.lua#L290
> 
> 
> `clippings.title` resolves to `clippings.["title"]` not `clippings[title]` as it should be.
> To my defence it was suggested at PR review and I simply clicked "commit suggestion" :)

Thanks for your contribution! I would like to know how to fix this bug by myself? Or I have to wait for the next updated APK?

**Comment by Frenzie** [comment]
You can check for updates on the development channel (under hamburger menu → update) and download the latest nightly that way, or manually go to http://build.koreader.rocks/download/nightly/ and grab it there.

**Comment by abdoulayeYATERA** [comment]
Got it ! Thank you guys !
Keep up the good work !
