### ISSUE TITLE
[PDF] footer cuts off bottom of page in page mode

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader#5612]
* KOReader version: v2019.11-20-g15fe0fef_2019-11-18
* Device: emulator

#### Issue

regression symptom of #3870
```diff
- return self.footer_text:getSize().h
+ return self.footer_content:getSize().h
```

by changing the effective footer height from 24 to 15

when setting the offset to half the non visible area (ie: the space subtracted because of the footer)
https://github.com/koreader/koreader/blob/15fe0fef07413b54f847fdffbc601f05d78fb3a7/frontend/apps/reader/modules/readerview.lua#L595-L598

causes the footer to actually cover the pdf by half its height ~ 7, however when the footer height was supposedly 24 of which half is 12 the extra 3 pixels were not noticed.

the underlying cause is not taking the footer into account when calculating the offset.
however if the offset is lessened when the footer is present the footer does not properly update on toggle.

screenshots from the paper.pdf in the test submodule, page 19 
the calculation is cut off
![Reader_2019-Nov-18_224532](https://user-images.githubusercontent.com/38916402/69115042-3b344280-0a55-11ea-8557-43c24dba6b7b.png)

when changing
```diff
    if self.dimen.h > self.visible_area.h then
-        self.state.offset.y = (self.dimen.h - self.visible_area.h) / 2
+        self.state.offset.y = ((self.dimen.h - self.visible_area.h)- self.ui.view.footer:getHeight()) / 2
    end
```

the calculation is visible
![Reader_2019-Nov-18_225002](https://user-images.githubusercontent.com/38916402/69115283-05438e00-0a56-11ea-8de0-a0833c7fa789.png)

and when tapping on the footer to hide it, only the sides of the footer are hidden
![Reader_2019-Nov-18_225010](https://user-images.githubusercontent.com/38916402/69115314-18eef480-0a56-11ea-99fd-bdb0a81f297e.png)

**Comment by NiLuJe** [comment]
IIRC, there's a (very, very) long-standing issue with the footer clobbering the bottom of PDF pages. There might even be an open issue about it (if there is, it's an *old* one).

**Comment by yparitcher** [comment]
> IIRC, there's a (very, very) long-standing issue with the footer clobbering the bottom of PDF pages. There might even be an open issue about it (if there is, it's an _old_ one).

that would be #2072 fixed by #2079 
however that only hid the symptoms.

this only happens when the page is bound by height for example if the zoom mode is contentheight.

i would like to fix it, however i am having a vey hard time understanding the code.

**Comment by yparitcher** [comment]
i have a partial fix in https://github.com/yparitcher/koreader/commit/ad126f49c698023e23f62767e66b954e76cb0c04

however when doing so the `onTapFooter` does not properly hide the footer like so:

if the footer was `toggled on` on the current page, it will also `toggle off`, even when panning in the middle

if the footer was `toggled on` on a different page, it will **not** `toggle off` (visibly) until the page is turned. (panning does not help)

**Comment by yparitcher** [comment]
i got to the root of the issue, PR on the way.

one question, is it better to have the margin code paint under the footer in order that when tapping on the footer (to disable it) the space is cleared. this to me is bit of a hack, this can be seen here: https://github.com/yparitcher/koreader/commit/e04b7c8f4ed3913c2f2d672e3795ffe186d11491

or should i have the whole page recalculated on footer tap, which will cause the view to reset to the top of the page, even when panned to the middle.

**Comment by Frenzie** [comment]
> view … reset to the top of the page, even when panned

/twitchtwitch

That would annoy me immensely, and probably not just me. ;-)

> this to me is bit of a hack

Depends on how you use the footer, I suppose. I'd say not painting under the overlay sounds like premature optimization with a lot of extra effort involved to make it work.
