### ISSUE TITLE
CJK characters not displaying in dictionary and footnotes

### ISSUE THREAD

**Issue by Mayonnnaise** [koreader/koreader#5617]
* KOReader version: v2019.11-12-g89c0bd0
* Device: Onyx Boox Nova

#### Issue
CJK characters are not displaying properly in dictionary and footnotes. When there is a definition found in the dictionary, all the CJK characters are shown as 'tofus'. However, when there's no definition found, the Chinese characters for 'No definition found' and 'query: ...' are shown properly.
![IMG_20191120_103757__01](https://user-images.githubusercontent.com/49610933/69205090-ed6a2800-0b83-11ea-8c2a-4bd562b170d2.jpg)
![IMG_20191120_104422__01](https://user-images.githubusercontent.com/49610933/69205091-ed6a2800-0b83-11ea-9bc1-a60f6432d1ce.jpg)
![IMG_20191120_103715](https://user-images.githubusercontent.com/49610933/69205092-ee02be80-0b83-11ea-8248-e2471f11f56b.jpg)

**Comment by Frenzie** [comment]
This wasn't the case in 2019.07 or 2019.08? I can't tell if that first screenshot is MuPDF or just the dictionary in question.

**Comment by Mayonnnaise** [comment]
No, the dictionary worked well in 2019.07 and 2019.08. The first screenshot is just the dictionary in question

**Comment by poire-z** [comment]
I guess that dictionary lookup result is from a HTML dict, so it went thru MuPDF, like the popup footnotes do.
The "No definition found" is pure KOReader text, so it's ok.

@Frenzie : looks like you forgot to revert from https://github.com/koreader/koreader-base/commit/b7dd4c16b06c22fc1d1b85544f9c767f8d4b2995 a few `#ifdef __ANDROID__`  with https://github.com/koreader/koreader-base/commit/587dd1810ba22b354d945fd91c41a305e03c82df.
`#ifdef __ANDROID__ get_font_file_android()` is still there in `fz_lookup_cjk_font_from_file()` and `fz_load_system_fallback_font_from_file()`.

**Comment by Frenzie** [comment]
@poire-z I didn't forget, I purposefully didn't revert the Roboto part. Meh, I'll just revert the whole thing then.
