### ISSUE TITLE
Adding highlights + sleep modifies PDF file even though "Save document" setting is Disabled.

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#5618]
* KOReader version: v2018.12
* Device: Kobo 

#### Issue
When you add highlights the PDF file is modified even though I made sure that the corresponding setting is disabled. This only happens if you put the device to sleep after adding the highlight.
I tolerated this bug for a year or so, but now I happen to be reading a book which is 200MB in size and you can imagine that every time rsyncing the library with a 200MB file changed takes a long time via USB 2 (and my library grows every day, sometimes more than twice a day, so rsync is a frequent event).

#### Steps to reproduce
Open a PDF file, add some highlights, but first make sure the "Save document (write highlights to PDF)" setting is set to "Disabled". Then put the device to sleep and then wakeup. Then, do (from the Linux workstation via usbnet):

```
$ rsync --delete --size-only -rvW . usbnet:/mnt/onboard/.Books/
```

And observe that the file is updated. Here is a better log:

```
root@water # md5sum Tertium-Organum-Russian-1916.pdf 
7d6c59617aa915c787f20a884d46678d  Tertium-Organum-Russian-1916.pdf
root@water # l
total 219520
-rwxr-xr-x    1 root     root       7105340 Oct 13 21:20 Tertium-Organum-English-1920-ver2.djvu
-rwxr-xr-x    1 root     root       7137690 Oct 13 21:20 Tertium-Organum-English-1920.djvu
-rwxr-xr-x    1 root     root       2678937 Oct 13 21:20 Tertium-Organum-English-typeset.pdf
-rwxr-xr-x    1 root     root     207782648 Nov 20 11:59 Tertium-Organum-Russian-1916.pdf
drwxr-xr-x    2 root     root         32768 Nov 20 12:14 Tertium-Organum-Russian-1916.sdr
```

Now, let's add a highlight, suspend and wakeup and check again:

```
root@water # l
total 219520
-rwxr-xr-x    1 root     root       7105340 Oct 13 21:20 Tertium-Organum-English-1920-ver2.djvu
-rwxr-xr-x    1 root     root       7137690 Oct 13 21:20 Tertium-Organum-English-1920.djvu
-rwxr-xr-x    1 root     root       2678937 Oct 13 21:20 Tertium-Organum-English-typeset.pdf
-rwxr-xr-x    1 root     root     207783700 Nov 20 12:15 Tertium-Organum-Russian-1916.pdf
drwxr-xr-x    2 root     root         32768 Nov 20 12:15 Tertium-Organum-Russian-1916.sdr
root@water # md5sum Tertium-Organum-Russian-1916.pdf 
dc1a05f55e113ab3c56d8b6199aed54e  Tertium-Organum-Russian-1916.pdf
```

Note that the filesize and modification time of `Tertium-Organum-Russian-1916.pdf` file has changed. And, obviously, md5sum is also changed.

Please note that after update all the highlights are NOT LOST, i.e. they are exactly as they should be, i.e. Koreader writes them BOTH to PDF and also to `.sdr/metadata.pdf.lua`).

And, btw, yes, I copied the file back from Kobo to Linux and checked that the highlight is present. Yes, it is present, but it is awful, i.e. it is a solid black block which completely hides the text. Anyway, it shouldn't be there at all.

So, I guess the code which handles suspending Kobo ignores the "don't write to PDF" setting and writes it anyway. This is a bug.

**Comment by Frenzie** [comment]
Tbh I don't much care for that write to PDF setting.

The setting itself is used to save or discard changes here.

https://github.com/koreader/koreader/blob/03fda960415c13892e04707bf82323720fd5fc5c/frontend/apps/reader/readerui.lua#L635-L643

That leads to…

https://github.com/koreader/koreader/blob/03fda960415c13892e04707bf82323720fd5fc5c/frontend/document/pdfdocument.lua#L208-L218

There are no other calls to writeDocument, and closeDocument shouldn't be called on suspend. Weird.

**Comment by tigran123** [comment]
I have now added an annotation and then suspended Kobo and then (17 seconds later) woke it up (the message about suspend gets written on wakeup, it seems?).

```
11/20/19-13:13:06 INFO  setting zoom mode to page                         
11/20/19-13:14:45 INFO  writing document to /mnt/onboard/.Books/Religions/Urantia/British-Study-Edition/Revelation-7in.pdf
11/20/19-13:15:02 INFO  Kobo suspend: going to sleep . . .                                        
11/20/19-13:15:02 INFO  Kobo suspend: asked the kernel to put subsystems to sleep, ret: true
11/20/19-13:15:04 INFO  Kobo suspend: waited for 2s because of reasons...         
11/20/19-13:15:04 INFO  Kobo suspend: synced FS                                   
11/20/19-13:15:04 INFO  Kobo suspend: asking for a suspend to RAM . . .           
11/20/19-13:15:04 INFO  Kobo suspend: ZzZ ZzZ ZzZ? Write syscall returned:  true
11/20/19-13:15:04 INFO  Kobo suspend: woke up!                                    
11/20/19-13:15:12 INFO  Kobo resume: clean up after wakeup                    
11/20/19-13:15:12 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
```

On the second attempt the log is shorter:

```
11/20/19-13:18:00 INFO  writing document to /mnt/onboard/.Books/Religions/Urantia/British-Study-Edition/Revelation-7in.pdf
11/20/19-13:18:08 INFO  Kobo resume: clean up after wakeup                    
11/20/19-13:18:08 INFO  Kobo resume: unflagged kernel subsystems for resume, ret: true
```

First I added a highlight and then (a couple of seconds later, at 13:18:00) I suspended the device.
8 seconds later I woke it up.

**Comment by Frenzie** [comment]
Hm, I can't reproduce on my H2O. With it set to ask I did:

1. Add highlight
2. Suspend
3. Resume
4. Close document

It then asked me if I wanted to save the document. The positioning seemed a bit off though, perhaps because the doc was in landscape.

As you can see only the .sdr was updated for me.
```
[root@(none) .books]# cd Early\ Printed\ Narrative\ Literature\ in\ Western\ Europe/
[root@(none) Early Printed Narrative Literature in Western Europe]# ls -l
total 10608
-rwxr-xr-x    1 root     root        157498 Nov 19 22:07 9783110563016-001.pdf
drwxr-xr-x    2 root     root          4096 Nov 19 23:08 9783110563016-001.sdr
-rwxr-xr-x    1 root     root        378233 Nov 19 22:07 9783110563016-002.pdf
drwxr-xr-x    2 root     root          4096 Nov 20 15:07 9783110563016-002.sdr
-rwxr-xr-x    1 root     root        353032 Nov 19 22:07 9783110563016-003.pdf
-rwxr-xr-x    1 root     root        573226 Nov 19 22:07 9783110563016-004.pdf
-rwxr-xr-x    1 root     root        183548 Nov 19 22:07 9783110563016-005.pdf
-rwxr-xr-x    1 root     root        981807 Nov 19 22:08 9783110563016-006.pdf
drwxr-xr-x    2 root     root          4096 Nov 19 22:10 9783110563016-006.sdr
-rwxr-xr-x    1 root     root        224451 Nov 19 22:07 9783110563016-007.pdf
-rwxr-xr-x    1 root     root        832450 Nov 19 22:08 9783110563016-008.pdf
-rwxr-xr-x    1 root     root       1611477 Nov 19 22:08 9783110563016-009.pdf
-rwxr-xr-x    1 root     root        881756 Nov 19 22:08 9783110563016-010.pdf
-rwxr-xr-x    1 root     root       2200934 Nov 19 22:08 9783110563016-011.pdf
-rwxr-xr-x    1 root     root        337319 Nov 19 22:07 9783110563016-012.pdf
-rwxr-xr-x    1 root     root       1594533 Nov 19 22:08 9783110563016-013.pdf
-rwxr-xr-x    1 root     root         56104 Nov 19 22:08 9783110563016-014.pdf
-rwxr-xr-x    1 root     root         43862 Nov 19 22:08 9783110563016-015.pdf
-rwxr-xr-x    1 root     root         93135 Nov 19 22:08 9783110563016-016.pdf
-rwxr-xr-x    1 root     root         73852 Nov 19 22:08 9783110563016-017.pdf
-rwxr-xr-x    1 root     root         64249 Nov 19 22:08 9783110563016-201.pdf
-rwxr-xr-x    1 root     root         55919 Nov 19 22:08 9783110563016-202.pdf
-rwxr-xr-x    1 root     root         53969 Nov 19 22:08 9783110563016-fm.pdf
drwxr-xr-x    2 root     root          4096 Nov 19 22:09 9783110563016-fm.sdr
-rwxr-xr-x    1 root     root         46192 Nov 19 22:08 9783110563016-toc.pdf
drwxr-xr-x    2 root     root          4096 Nov 19 22:09 9783110563016-toc.sdr
```

**Comment by tigran123** [comment]
Strange. I'll retest with v2019.11, but I am having trouble with it rotating my screen see #5619

**Comment by Frenzie** [comment]
Oh hold on, you mean 2018.12 wasn't a typo?

**Comment by tigran123** [comment]
No, I am still using 2018.12 because it is excellent and stable :)

(On Kindle DXG I am still using (sometimes, very rarely) an ancient kindlepdfviewer of God knows which version :)

But I'll try upgrading FW to 4.18 and then upgrading Koreader to 2019.11

**Comment by tigran123** [comment]
Retested with the latest Koreader 2019.11 (now that issue #5619  is fixed) and confirm that this is only a problem in 2018.12, i.e. it does NOT occur in 2019.11. So I can close the issue, all is well.

**Comment by tigran123** [comment]
Btw, I wanted to thank you guys --- the addition of Android and Linux (AppImage) versions is such a wonderful idea! I am nearly tempted to switch from the best Android app (ebookdroid of course) to Koreader. The only thing that is superior in ebookdroid is much more smooth page scrolling. In Koreader it is more "jerky" or "discrete". On an LCD screen this smoothness is important, because (especially on Super AMOLED screens) one tends to read the same small vertical range of screen's portion rather than scanning the screen from top to bottom as one does on eInk. I.e. the page's content moves but your eye's direction remains relatively fixed. Anyway, this is a very minor issue and overall I am extremely happy with the latest version of Koreader. Well done!
