### ISSUE TITLE
Exiting koreader turns the screen upside down on Kobo H2O

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#5619]
* KOReader version: v2019.11
* Device: Kobo H2O

#### Issue
I just decided to try the latest version of Koreader. Trying it under Linux revealed that some good work has been done since 2018, so I decided to upgrade it on the Kobo device as well. However, simply starting up Koreader on Kobo H2O and then exiting causes the KSM to display everything upside down. I'll edit koreader.sh and see if I can make it go away. (normally my koreader.sh is only 5-6 lines long, i.e. I always remove 99% of the "stuff" that is there, as I believe it is unnecessary).

#### Steps to reproduce
Startup Koreader and then exit, observing that the screen is upside down and you have to "blindly" estimate which part of the screen needs to be touched to reboot.

**Comment by tigran123** [comment]
Note that only the toplevel KSM menu is upside down. Any of the submenus seem to be the right way up.

**Comment by tigran123** [comment]
Oh my God, it does (or at least tries to) a LOT of fancy stuff with the fbdepth.... I'll have to figure it out if this even works on Kobo Aura H2O? I.e. can all the fbdepth setting/restoring code be just remove? My guess is that that is what is causing the screen rotation on exist.

**Comment by Frenzie** [comment]
It sounds like you forgot to update KSM? ;-)

**Comment by NiLuJe** [comment]
Yeah, @Frenzie probably remembers better than me which minimum KSM version is required.. 8? 9?

**Comment by tigran123** [comment]
Update KSM??? Oh, I am running KSM 09 (plus update_001). Is this not good enough?

I wonder if updating KSM without resetting to complete factory state is even possible.

**Comment by tigran123** [comment]
But according to KSM thread on mobileread KSM 09 update001 is the latest.

**Comment by NiLuJe** [comment]
That should definitely work on stock KSM setups, yeah ;).

**Comment by NiLuJe** [comment]
In which case, a full crash.log would be helpful.

**Comment by NiLuJe** [comment]
Also, which FW version is the device running? Early H2O kernels may be entirely too buggy for this to behave properly.

**Comment by Frenzie** [comment]
Yes, KSM 9 is good. (Btw, KSM is unfortunately discontinued although it should hopefully remain functional for a while yet.)

I run practically exactly the scenario you describe yourself, but with newer FW /older KSM (something like post FW 4.6/pre KSM 9 or possibly pre-8) the scenario you described would occur.

The reverse could also apply.

**Comment by NiLuJe** [comment]
Oh, yeah, there's a *also* specific window of FW versions around early 4.x that will royally fuck things up, possibly ^^.

**Comment by tigran123** [comment]
Here is the crash.log of just starting up Koreader and then exiting.

```
Original fb rotation is set @ 2
Original fb bitdepth is set @ 16bpp
Switching fb bitdepth to 8bpp & rotation to Portrait
[FBInk] Detected a Kobo Aura H2O (370 => Dahlia @ Mark 5)
Variable fb info: 1440x1080 (1440x2304), 16bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 2880 bytes
Device's expected Portrait orientation should be: 1 (Clockwise, 90°)!

Switching fb to 8bpp @ rotation 1 . . .
Setting bitdepth to 8bpp
Setting grayscale to 1
Setting rotate to 1 (Clockwise, 90°)
Setting rotate to 3 (Counter Clockwise, 270°) to account for kernel rotation quirks
Bitdepth is now 8bpp (grayscale: 1) @ rotate: 1 (Clockwise, 90°)

Variable fb info: 1080x1440 (1088x3072), 8bpp @ rotation: 1 (Clockwise, 90°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 1088 bytes
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/20/19-14:19:47
 [*] Version: v2019.11

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 3342336
FB: id           : mxc_epdc_fb
FB: smem_len     : 6684672
FB: line_length  : 1088
FB: xres         : 1080
FB: xres_virtual : 1088
FB: yres         : 1440
FB: yres_virtual : 3072
FB: bpp          : 8
11/20/19-14:19:47 INFO  initializing for device Kobo_dahlia
11/20/19-14:19:47 INFO  framebuffer resolution: {
    ["h"] = 1440,
    ["w"] = 1080
}
[ko-input] Forked off fake event generator(pid:2055).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
11/20/19-14:19:51 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
11/20/19-14:19:51 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
11/20/19-14:19:51 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
11/20/19-14:19:51 INFO  FM loaded plugin SSH at plugins/SSH.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin batterystat at plugins/batterystat.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin evernote at plugins/evernote.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin goodreads at plugins/goodreads.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin keepalive at plugins/keepalive.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin readtimer at plugins/readtimer.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin statistics at plugins/statistics.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin systemstat at plugins/systemstat.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin texteditor at plugins/texteditor.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin timesync at plugins/timesync.koplugin
11/20/19-14:19:51 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
11/20/19-14:19:52 ERROR failed to register crengine font: cannot register font <./fonts/nerdfonts/symbols.ttf>
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
11/20/19-14:20:06 INFO  no dialog left to show
11/20/19-14:20:06 INFO  quitting uimanager
Restoring original fb bitdepth @ 16bpp & rotation @ 2
[FBInk] Detected a Kobo Aura H2O (370 => Dahlia @ Mark 5)
Variable fb info: 1080x1440 (1088x3072), 8bpp @ rotation: 1 (Clockwise, 90°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 1088 bytes

Switching fb to 16bpp @ rotation 2 . . .
Setting bitdepth to 16bpp
Setting grayscale to 0
Setting rotate to 2 (Upside Down, 180°)
Setting rotate to 0 (Upright, 0°) to account for kernel rotation quirks
Bitdepth is now 16bpp (grayscale: 0) @ rotate: 2 (Upside Down, 180°)

Variable fb info: 1440x1080 (1440x2304), 16bpp @ rotation: 2 (Upside Down, 180°)
Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6684672 bytes & line length: 2880 bytes
```

**Comment by NiLuJe** [comment]
Yup, that's the expected behavior on KSM, everything's happening as it should on our end.

**Comment by tigran123** [comment]
Does this tell you the firmware version?

```
root@water # cat /mnt/onboard/.kobo/version
N250493001731,2.6.35.3,4.5.9587,2.6.35.3,2.6.35.3,00000000-0000-0000-0000-000000000370
```

**Comment by NiLuJe** [comment]
Yeah. 4.5, which is smack in the middle of said "fucked up" FW ranges ;).

Updating should fix it.

**Comment by Frenzie** [comment]
But beware of https://github.com/koreader/koreader/issues/5430. 4.16 is recommended.

**Comment by tigran123** [comment]
Do you mean resetting the whole thing to factory, upgrading Kobo firmware, then re-installing everything (Koreader and Vlasovsoft)?

**Comment by NiLuJe** [comment]
No, just updating the stock FW. That shouldn't have any impact on custom stuff, except laucnhers, n which cas,e refer to said launcher's doc re: FW updates.

**Comment by Frenzie** [comment]
KSM has a "handle update" menu that pops up if you (or stock Nickel) puts an update in place btw.

**Comment by tigran123** [comment]
So, you suggest I find FW 4.16 and use KSM's "handle update" function, correct?

**Comment by NiLuJe** [comment]
Yup!

**Comment by NiLuJe** [comment]
c.f., @geek1011 [firmware update](https://pgaskin.net/KoboStuff/kobofirmware.html) page for links.

**Comment by tigran123** [comment]
On that page it says 4.16 is "For Libra H2O only"

**Comment by Frenzie** [comment]
Sorry about that, I'm actually running 4.15. I knew I was running the last version before 4.17.

```
cat /mnt/onboard/.kobo/version
N250484010805,2.6.35.3,4.15.12920,2.6.35.3,2.6.35.3,00000000-0000-0000-0000-000000000370
```

**Comment by NiLuJe** [comment]
4.15, then ;).

Or 4.18 with the config tweaks mentioned in the linked issue. Which would be the recommended procedure on newer devices, BTW, but on EoL devices, if you don't use Nickel, that's not as important (there's no significant rootfs updates, and no kernel updates on EoL devices, unlike on Mk. 7, for which there were kernel updates in nearly every release).

**Comment by tigran123** [comment]
So I need the 4.15.12920 from the kobo5 column, i.e. this one:

[https://kbdownload1-a.akamaihd.net/firmwares/kobo5/May2019/kobo-update-4.15.12920.zip](https://kbdownload1-a.akamaihd.net/firmwares/kobo5/May2019/kobo-update-4.15.12920.zip)

correct?

**Comment by NiLuJe** [comment]
Yup.

**Comment by tigran123** [comment]
Thank you, I will try that. And will let you know if all is well by closing the issue.

**Comment by tigran123** [comment]
I've read that issue and see it is no big deal for me (I NEVER use nickel). So, I'll use 4.18.

**Comment by Frenzie** [comment]
The way the issue is phrased wouldn't bother me one bit, but the prospect of accidentally triggering Nickel's indexing is something I prefer to avoid.

**Comment by tigran123** [comment]
Yes, I agree, that is why I always call my books directory `.Books` and not `Books`. I'll think a bit whether I really need to go ahead and do the upgrade at all. If I don't do it in a few days I'll close this issue any way.

**Comment by geek1011** [comment]
`.Books` would trigger nickel in 4.18 just as much as `Books` unless you use the config file tweak or the [dotfile hack](https://github.com/geek1011/kobo-mods/tree/master/kobo-dotfile-hack] @NiLuJe and I worked on.

**Comment by tigran123** [comment]
Good news, no need to upgrade anything, I fixed the problem by removing most of the code in `koreader.sh`. Here is how my koreader.sh looks like:

```
#!/bin/sh
export LC_ALL="en_US.UTF-8"
KOREADER_DIR="${0%/*}"
cd "${KOREADER_DIR}" || exit

export LD_LIBRARY_PATH="${KOREADER_DIR}/libs:${LD_LIBRARY_PATH}"
export TESSDATA_PREFIX="data"
export STARDICT_DATA_DIR="/mnt/onboard/.adds/vlasovsoft/dictionary"
export EXT_FONT_DIR="/mnt/onboard/fonts"

# fast and dirty way of check if we are called from nickel
# through fmon/KFMon, or from another launcher (KSM or advboot)
# Do not delete this line because KSM detects newer versions of KOReader by the presence of the phrase 'from_nickel'.
export FROM_NICKEL="false"
if pkill -0 nickel; then
    FROM_NICKEL="true"
fi

# fallback for old fmon, KFMon and advboot users (-> if no args were passed to the script, start the FM)
if [ "$#" -eq 0 ]; then
    args="/mnt/onboard"
else
    args="$*"
fi

export PLATFORM="mx50-ntx"
export CPU="mx50"
export PRODUCT="dahlia"
export INTERFACE="eth0"

# we keep at most 500KB worth of crash log
if [ -e crash.log ]; then
    tail -c 500000 crash.log >crash.log.new
    mv -f crash.log.new crash.log
fi

./reader.lua "${args}" >>crash.log 2>&1
exit 0
```

But the bad news is that rendering of PDF files is worse compared to 2018.12 (maybe this is related to not switching to 8bpp bitdepth, although I would expect only the performance to change, not the quality of rendering) so I am considering to revert to 2018.12 as it is very stable.

**Comment by tigran123** [comment]
On the other hand, making two screenshots (with old and new) and scrutinising them very carefully (on a good quality monitor) they seem absolutely identical, i.e. maybe I am wrong in thinking that PDF rendering is worse on the new version, so I'll test it a bit more and probably will keep it, as long as I don't notice anything bad. Closing this issue as no longer relevant (i.e. fixed by removing unnecessary, imho, optimisations which switch to 8bpp for performance).

**Comment by tigran123** [comment]
Btw, on Kobo Aura One I left the fbdepth setting code as is, because exiting Koreader doesn't cause KSM to be upside down on this device and I don't notice any performance improvement because of 8bpp. But I am sure it is there theoretically (as there are less bits to blit), just not immediately perceptible :)

**Comment by NiLuJe** [comment]
Yeah, the H2O is a [special snowflake](https://github.com/NiLuJe/FBInk/blob/00af1a67f128f0b2386757f4208ccd02c949e342/fbink_device_id.c#L638-L644).

Note that, besides losing on general snappiness because RGB565 is the worst pixel format in the history of mankind, unless you have hardware compositing/blitting, ditching fbdepth prevents:

* Dithering (8bpp only)
* Blitting fast-paths (8bpp & 32bpp only)
* Running in a native rotation, which will prevent being able to use said blitting fastpaths in Portrait.

The last two are especially important for KSM users, because it will *never* run in a sane orientation and a sane bitdepth, even on FW versions that do (roughly >= 4.9, as earlier versions were a bit dicey, both because of a major rootfs update, and said move to 32bpp, which is only slightly less insane than rgb565 on a grayscale device, but unfortunately makes sense when you're familiar with the constraints imposed by Qt5).

As a random data point, the rotation alone makes blitting a CEe page jump from 3ms to 100ms.

**Comment by tigran123** [comment]
Thank you. I believe you and at some point will upgrade my H20 FW, as you suggest.
