### ISSUE TITLE
Add /sdcard/fonts to Android

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#5621]
* KOReader version: v2019.12
* Device: Computer running Ubuntu Linux 18.04.3 or any Android device

#### Issue
Even with the option "System Fonts" enabled Koreader does not see all of the system fonts (i.e. user fonts installed on the system via fontconfig mechanism), namely it seems to ignore all the fonts installed in the user's `~/.fonts` directory. But this is where the best fonts (various optical families that user actually bought) are normally installed.

Oh btw, there is another little bug, clicking on "Open font folder" results in these errors:

```
nautilus: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_glib_get_unicode_funcs

```

As for Android, a similar problem happens here: the `fonts` subdirectory of internal storage which is used for user/system fonts on other platforms (and on Android by CoolReader and, maybe, ebookdroid) is ignored. Please either use this standard location or allow the user to set it manually.

**Comment by Frenzie** [comment]
> Oh btw, there is another little bug, clicking on "Open font folder" results in these errors:

It's just xdg-open, so as it says that would be Nautilus.

**Comment by tigran123** [comment]
Thank you, I have read #5220 and understood that the workaround for this is simply to create the symlink:

```
$ cd ~/.local/share
$ rmdir fonts
$ ln -s ~/.fonts fonts
```

Then Koreader works correctly on Linux. Or, alternatively, one can just "comply" with somebody's silly caprice (the so-called "XDG Base Directory Specification") and just move the fonts from `~/.fonts` to `~/.local/share/fonts`. Either way works, so I am closing this issue. Thank you again, @Frenzie  :)

**Comment by tigran123** [comment]
Oops, I forgot about Android. The above solution works only on Linux, but on Android we still don't see user fonts, so I am re-opening it.

**Comment by pazos** [comment]
@tigran123: In the case of android we use the path `koreader/fonts` inside the primary storage partition (normally the internal storage unless the user configured an external sdcard to use it instead)

The relevant code is in https://github.com/koreader/koreader/blob/master/frontend/ui/elements/font_settings.lua#L57-L69

We can append as many paths as we want, separated with `;` but there isn't any generic path used for other apps.

**Comment by tigran123** [comment]
@pazos Thank you, Martin, it works. It seems a bit silly to have two copies (/sdcard/fonts and /sdcard/koreader/fonts) and one can't make symlinks on a vfat partition, but its ok. In my case it only wastes 25MB of 64GB internal storage, so that is negligible. Closing the issue now.

**Comment by Frenzie** [comment]
If /sdcard/fonts is a de facto standard among several other apps then @pazos might be somewhat wrong about there not being a generic path, even if it's not fully generic.

According to [this](https://andropenoffice.blogspot.com/2013/10/how-to-add-custom-fonts-to-andropen.html) Android OpenOffice (and perhaps also LibreOffice?) also use /sdcard/fonts, so it certainly seems worth considering.

**Comment by tigran123** [comment]
Well, yes, CoolReader also uses /sdcard/fonts so if Koreader used the same, then we would avoid wasting space AND, more importantly, avoid an unexpected failure to find the fonts. I think most people who use Koreader are probably familiar with CoolReader and so they put their fonts in /sdcard/fonts.

**Comment by tigran123** [comment]
Btw, on a somewhat unrelated topic --- I have switched from ebookdroid to Koreader on Android! The reason is that some PDF files (scanned books from Russia State Library dated 1913-1916) which have a lot of artefacts on the page are very hard to "clean" with ebookdroid's "image enhancements", but Koreader's "Dewatermark" function works ideally here! I.e. the page becomes beautiful high contrast and readable. So, I am EXTREMELY happy with the latest version of Koreader --- well done again, guys! :)

**Comment by Frenzie** [comment]
The initial delay should only be active in

**Comment by tigran123** [comment]
No, the delay occurs with normal swipe also. But it is just about tolerable. It would be absolutely ideal if it was as smooth as ebookdroid (try it and see the difference).

**Comment by Frenzie** [comment]
You can reduce delays in Taps & gestures. But it's no different than Androis default.

**Comment by tigran123** [comment]
I think there is a serious bug here: if you hold (with all hold-related functions disabled) and then swipe up or down then nothing happens, i.e. page content does not move. The behaviour should be exactly the same as just swiping up or down. In ebookdroid, if touch-related function (i.e. "Tools") is disabled, then hold+swipe is exactly the same as swipe. Or, instead of "hold+swipe" you can just "swipe very slowly" --- again, nothing happens in Koreader, but ebookdroid just scrolls the page very slowly, as expected.

**Comment by pazos** [comment]
Just tried with Coolreader and I can't see fonts placed under /sdcard/fonts, where /sdcard is a symbolic link to /storage/sdcard0 (internal partition) or /storage/sdcard1 (external sdcard).

I'm not sure why, but given that it might work on some FW/vendors/devices we can add /sdcard/fonts as a place to look up for fonts without removing /sdcard/koreader/fonts.

**Comment by tigran123** [comment]
Strange, on my Android tablet CoolReader 3.2.32-1 can see the fonts in /sdcard/fonts without any problems.
