### ISSUE TITLE
crash on KPW4

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#5627]
* KOReader version: 2019.11
* Device: KPW4

#### Steps to reproduce
unreproducible

##### `crash.log` (if applicable)

https://pastebin.com/RcTBFQDP

**Comment by NiLuJe** [comment]
I'm farily sure there's a similar issue already open somewhere ;).

Related to CJK + Tesseract +/- k2pdfopt/mupdf

**Comment by Frenzie** [comment]
#4481?

**Comment by NiLuJe** [comment]
That's the one I was thinking about, thanks ;).
