### ISSUE TITLE
Cannot choose chinese characters by long pressing

### ISSUE THREAD

**Issue by lyxcj** [koreader/koreader#5630]
* KOReader version: v2019.11
* Device:KindlePaperWhite

**Comment by Frenzie** [comment]
I doubt 4 would work, unless it's backward compatible. Is it a question or have you verified that it works for Latin characters?

**Comment by lyxcj** [comment]
> I doubt 4 would work, unless it's backward compatible. Is it a question or have you verified that it works for Latin characters?

It works for English and French. I wonder if there are some special settings for Chinese pdf documents. Or it just the problem of the traineddata. I also tried even older tesseracts.

**Comment by lyxcj** [comment]
> I doubt 4 would work, unless it's backward compatible. Is it a question or have you verified that it works for Latin characters?

Here are the .traineddata files:
koreader  data  tessdata  ls
chi_sim.traineddata  chi_tra.traineddata  eng.traineddata  fra.traineddata
This is the setting for the Chinese document:
![IMG_20191123_091750R](https://user-images.githubusercontent.com/57315142/69475886-0288c600-0dd3-11ea-8386-2365ced03c11.jpg)

**Comment by Frenzie** [comment]
Seems like it should be related to #4481, even if there's no crash.

**Comment by lyxcj** [comment]
> Seems like it should be related to #4481, even if there's no crash.

Yes. The OCR cannot recognize Chinese characters after the reflow.

**Comment by Frenzie** [comment]
In that case I'll close this as a duplicate.
