### ISSUE TITLE
System statistics freeze on Android

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#5631]
* KOReader version: 15fe0fe 2019-11-18
* Device: Android 6, Zenfone 2, x86

#### Issue
Opening system statistics freezes the program.

**Comment by poire-z** [comment]
No issue for me on my Android 6.0.1 **arm** phone, with today's nightly or a one from last week.

**Comment by Frenzie** [comment]
That shouldn't make a difference but it works on my other (ARM) device on 2019.11. I figured it was a generic issue and I couldn't quickly test, so I opened this so I wouldn't forget.

**Comment by Frenzie** [comment]
It works with SQLite, doesn't it? Could it be corrupted?

**Comment by Frenzie** [comment]
The same problem can be reproduced in the emulator on Android 6, but not on 4.2, 7, 8 or 9.

Android 5 & 10 can't be tested due to #5602.

**Comment by poire-z** [comment]
If you want to check other bugs, you can disable xtext by adding manually use_xtext=false to settings.reader.lua.
https://github.com/koreader/koreader/blob/4740ab1fdca2bfcf24e4d5b31a4e9062346da034/frontend/ui/widget/textwidget.lua#L45

**Comment by poire-z** [comment]
> It works with SQLite, doesn't it? Could it be corrupted?

A quick look at plugins/systemstat.koplugin/main.lua indicates it's not using sqlite.

**Comment by Frenzie** [comment]
I know (now); I wasn't at a suitable computer when I wrote that. :-)

**Comment by pazos** [comment]
Can reproduce on emulator 6.0. Reverting https://github.com/koreader/koreader/pull/5493 fix it.

Never faced this issue on a real device.

**Comment by Frenzie** [comment]
Well, it's been my daily driver for about 4 years now. ;-)

**Comment by NiLuJe** [comment]
Huh. And that call doesn't actually hang in the other, less trivial places where we actually need it?

**Comment by Frenzie** [comment]
I'll double check if I've got a home dir set, but I don't think I do. It's even less likely on the emulator.

**Comment by pazos** [comment]
> Huh. And that call doesn't actually hang in the other, less trivial places where we actually need it?

Nope. The call returns a path. It seems that processing the path to find disk usage is what breaks the whole thing. Things work fine if the path is in a sdcard as the call reports the `realpath` of the folder. In the case of internal storage it reports `/sdcard` which is a symbolic link somewhere. Most phones fail to retrive disk usage on that circunstance due to insufficient permissions.

**Comment by NiLuJe** [comment]
@pazos: Oh, okay, thanks for delving into it ;).
