### ISSUE TITLE
Crash & wake up when: Sleep/power off + empty History + Use last book's cover as screensaver

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#5633]
* KOReader version: v2019.11-27-g4740ab1_2019-11-22/  
* Device: KA1

#### Issue
When I have "Use last book's cover as screensaver" and History is empty my device crashes when power off/put to sleep.
#### Steps to reproduce
1. "Use last book's cover as screensaver", purge .sdr for all books on History page
2. Put device to sleep: device will go into sleep with a crashlog as screensaver and then wake up again after 10-15 seconds
3. Put device to sleep again. Now it won't crash.

[crash.log](https://github.com/koreader/koreader/files/3882875/crash.log)

**Comment by NiLuJe** [comment]
Could probably use a nil guard around lastfile, yeah ;).

Mildly related to #4418
