### ISSUE TITLE
No localized string for file size unit (B, KB, MB, GB)

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#5649]
* KOReader version: 2019.11
* Device: Kobo Forma

#### Issue
I'm in the process of translating the KOReader to Romanian. I found that there is no way to localize the file size units (B, KB, MB, GB) because there is no customizable string in the koreader.po files.
For example in Russian should be Б, КБ, МБ, ГБ, in Romanian and Moldavian O, KO, MO, GO.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
This is in the file manager?

**Comment by SilverGreen93** [comment]
Yes, they are displayed in the file manager/navigator.
