### ISSUE TITLE
[Enhancement] Allow multiple keyboard layouts

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#5653]
* KOReader version: 2019.11
* Device: Kobo Forma

The keyboard system is begining to take shape!
It would be great if on the settings menu, keyboard layout, you could choose more than one layout and switch between them with the "Global/Planet" key, like you do in Windows with the language switcher.

**Comment by poire-z** [comment]
It's been done these last weeks, see #5583 and #5610.
If you're using 2019.11, you don't have it, but it's available in current nightlies, and will be in 2019.12.

**Comment by SilverGreen93** [comment]
Oh, I missed that ones. Thanks!
