### ISSUE TITLE
slim status bar crops content 

### ISSUE THREAD

**Issue by BrainDamage** [koreader/koreader#5654]
* KOReader version: v2019.11.43-gb073896_2019-11-27
* Device: Kobo Aura H2O2

#### Issue
Slim status bar overlaps over the content of comic books ( cbz ) cropping off a part of the content

![1](https://user-images.githubusercontent.com/50474/69833215-b4d8e700-1232-11ea-840d-4bac0abcecc5.png)
![2](https://user-images.githubusercontent.com/50474/69833216-b60a1400-1232-11ea-9e1f-8f4457782fe3.png)

as you can see the speech bubble gets the text "I'll die" truncated by the status bar overlap.

This happens regardless of which zoom mode is selected, I would guess that status bar size is not accounted / added after the picture frame is processed and rendered

**Comment by Frenzie** [comment]
Also see #5620. Could be a regression.

**Comment by BrainDamage** [comment]
It's not a regression from that commit, I've tested both v2019.10 and v2019.6 ( the latter on my desktop ) and both exhibit the issue

**Comment by yparitcher** [comment]
#5620 fixed this issue when using **page** scrolling. page scrolling already had code to handle view size being different than screen size and just was not calculating it properly.

This issue is with **continuous** scrolling which from a quick look at the code does not yet fully support different view and screen sizes, as the content is continuous "flows straight of the screen".

if you keep on scrolling the content will be revealed (unlike on a page where only the next page is displayed), the only place this should matter is the end of the last page of the book.

this seems to fix it, but needs further testing to make sure nothing else is affected

```diff
--- a/frontend/apps/reader/modules/readerpaging.lua
+++ b/frontend/apps/reader/modules/readerpaging.lua
@@ -564,7 +564,7 @@ function ReaderPaging:onInitScrollPageStates(orig_mode)
         self.orig_page = self.current_page
         self.view.page_states = {}
         local blank_area = Geom:new{}
-        blank_area:setSizeTo(self.view.dimen)
+        blank_area:setSizeTo(self.view.visible_area)
         while blank_area.h > 0 do
             local offset = Geom:new{}
             -- caculate position in current page
@@ -740,7 +740,7 @@ function ReaderPaging:onScrollPanRel(diff)
     logger.dbg("pan relative height:", diff)
     local offset = Geom:new{x = 0, y = diff}
     local blank_area = Geom:new{}
-    blank_area:setSizeTo(self.view.dimen)
+    blank_area:setSizeTo(self.view.visible_area)
     local new_page_states
     if diff > 0 then
         -- pan to scroll down
@@ -780,7 +780,7 @@ function ReaderPaging:onScrollPageRel(page_diff)
         end
 
         local blank_area = Geom:new{}
-        blank_area:setSizeTo(self.view.dimen)
+        blank_area:setSizeTo(self.view.visible_area)
         local overlap = self.overlap
         local offset = Geom:new{
             x = 0,
@@ -790,7 +790,7 @@ function ReaderPaging:onScrollPageRel(page_diff)
     elseif page_diff < 0 then
         -- page up, first page should be moved to bottom
         local blank_area = Geom:new{}
-        blank_area:setSizeTo(self.view.dimen)
+        blank_area:setSizeTo(self.view.visible_area)
         local overlap = self.overlap
         local first_page_state = table.remove(self.view.page_states, 1)
         local offset = Geom:new{
```

**Comment by poire-z** [comment]
(I was willing to have a go at testing this, but I can't reproduce the issue before applying this PR :) I always get some overlap... Note that I'm not really familiar with our PDF/CBZ/ReaderPaging code and options...)

Anyway, should we merge this, and let users test it? :)
