### ISSUE TITLE
Romanian translation crashes (Plural forms)

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#5661]
* KOReader version: 2019.11
* Device: Kobo Forma

#### Issue
The Romanian translation has 3 plural forms, but crashes when KOReader loads the po file.
(https://www.transifex.com/houqp/koreader/language/ro_MD/)

I tested this on 2019.11, merged with the commit from #5603 in which the plurals are supposedly fixed.
Workaround: Edit po file and change pluralforms to 2.

See crashlog below.

##### `crash.log`
./luajit: frontend/gettext.lua:126: attempt to call a nil value
stack traceback:
	frontend/gettext.lua:126: in function 'getPluralFunc'
	frontend/gettext.lua:223: in function 'changeLang'
	frontend/ui/language.lua:57: in function 'changeLanguage'
	frontend/ui/language.lua:72: in function 'callback'
	frontend/ui/widget/touchmenu.lua:765: in function 'action'
	frontend/ui/uimanager.lua:750: in function '_checkTasks'
	frontend/ui/uimanager.lua:1033: in function 'handleInput'
	frontend/ui/uimanager.lua:1119: in function 'run'
	./reader.lua:260: in main chunk
	[C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash n°1: 11/26/19 @ 19:29:37)
Running FW 4.18.13737 on Linux 4.1.15-00285-ge6f1309 (#79 SMP PREEMPT Mon Jul 8 14:30:15 CST 2019)
Attempting to restart KOReader . . .
!!!!

**Comment by Frenzie** [comment]
> I tested this on 2019.11, merged with the commit from #5603 in which the plurals are supposedly fixed.

It fixes a specific edge case. This is a different extremely complex edge case.

```
"Plural-Forms: nplurals=3; plural=(n==1?0:(((n%100>19)||((n%100==0)&&(n!=0)))?2:1));\n"
```

I think it'd be easiest to just hard-code this one… once I figure out what it's even trying to do, which I don't particularly want to right now. :-)

```
gettext: plural function	return function(n) if n==1 then return0 elseif (((n%100>19)or((n%100==0)and(n~=0))) then return2 elseif 1) end end
```

**Comment by Frenzie** [comment]
There are two kinds of workarounds to consider (besides properly supporting the full syntax, which is slightly beyond the scope of spending 10 minutes in the late afternoon).

One looks like this, writing the exact same thing in a way that isn't as insane (`n==1 ? 0 : ((n%100>19) || ((n%100==0) && (n!=0))) ? 2 : 1`, or better yet `n==1 ? 0 : (n%100>19) || ((n%100==0) && (n!=0)) ? 2 : 1`), thereby not breaking my simplistic parser.
```diff
diff --git a/frontend/gettext.lua b/frontend/gettext.lua
index fcb38047..7ce12315 100644
--- a/frontend/gettext.lua
+++ b/frontend/gettext.lua
@@ -201,6 +203,11 @@ function GetText_mt.__index.changeLang(new_lang)
                     local nplurals = plural_forms:match("nplurals=([0-9]+);") or 2
                     local plurals = plural_forms:match("plural=%((.*)%);")
 
+                    -- Hardcoded workaround for Romanian.
+                    if plurals == "n==1?0:(((n%100>19)||((n%100==0)&&(n!=0)))?2:1)" then
+                        plurals = "n==1 ? 0 : (n%100>19) || ((n%100==0) && (n!=0)) ? 2 : 1"
+                    end
+
                     if not plurals then
                         -- Some languages (e.g., Arabic) may not use parentheses.
                         -- However, the following more inclusive match is more likely
```

The other is to hardcode the result instead:

```lua
function(n) if n==1  then return 0  elseif  (n%100>19) or ((n%100==0) and (n~=0))  then return 2  else return  1 end
```

The second is obviously better for performance, but it doesn't sufficiently express the weirdness factor of not using spaces for legibility as well as the overuse of parentheses. The Romanian plural logic as written expresses something fairly simple in an overly complex manner with far too many parentheses, so I don't think it "legitimately" breaks anything. It's not some new, exciting, intriguingly complex plural system. ;-)

Anyway, may not be too difficult to fix it up if you want to do it properly. It's just this simplification of the syntax that's causing issues, though I maintain that writing the logic in such a way that it breaks this assumption is hard to read at best:

https://github.com/koreader/koreader/blob/3d191490d00ccf9725e30ddaf2d95eecf23ecb15/frontend/gettext.lua#L218-L221

Some special pattern such as `%b()` could be used to assist, see [here](https://www.lua.org/pil/20.2.html). I may look into that sometime but it's likely not quite a quick 5-10 minute thing.

**Comment by SilverGreen93** [comment]
How often is this function called? GetText_mt.__index.changeLang(new_lang)
I suppose it's only when loading the UI language, right?
If so, I think the first solution should be enough for now.

**Comment by Frenzie** [comment]
They're almost equivalent. I mainly prefer the first because it implicitly says not to write illegible stuff without spaces and full of crazy unnecessary parentheses.

> How often is this function called? GetText_mt.__index.changeLang(new_lang)

That one's called only once but that's not relevant. Stuff that isn't hardcoded is currently using loadstring, which will [never be compiled](http://wiki.luajit.org/NYI). This means that the (rather few) [ngettext](http://koreader.rocks/doc/modules/gettext.html#ngettext) calls are slower, albeit not in a way you'll ever notice.

**Comment by SilverGreen93** [comment]
Hopefully I will test this today and come back with an answer. I was out of town.

**Comment by Frenzie** [comment]
Reopening because Weblate changed the rules, basically as I had hoped.

It changed it from:

```
"Plural-Forms: nplurals=3; plural=(n==1?0:(((n%100>19)||((n%100==0)&&(n!=0)))?2:1));\n"
```
to
```
"Plural-Forms: nplurals=3; plural=n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < "
"20)) ? 1 : 2;\n"
```

But although this wasn't written by a maniac, unfortunately it doesn't work out of the box.
