### ISSUE TITLE
cannot open empty txt file

### ISSUE THREAD

**Issue by zaoqi** [koreader/koreader#5669]
* KOReader version: v2019.11
* Device: KPW4

#### Issue

cannot open empty txt file

#### Steps to reproduce

1. create a empty txt file
2. open it

**Comment by Frenzie** [comment]
Cf. #1161.

**Comment by poire-z** [comment]
#1161 and https://github.com/koreader/crengine/issues/4 seem fixed: I can open txt files with only a few words on a single line, with or without a trailing \n.

Indeed, with a 0-size txt file, it opens, but it displays:
<kbd>![image](https://user-images.githubusercontent.com/24273478/70340607-5ffc2880-1851-11ea-8356-c0dd25b4c246.png)</kbd>
which might actually be a little better than opening and showing a blank page :)

So, it actually does open. It does not crash and does not show:
<kbd>![image](https://user-images.githubusercontent.com/24273478/70340697-920d8a80-1851-11ea-965c-1b5829e75ef5.png)</kbd>
But ^ this is what happens with a 0-size .pdf file:
```
12/06/19-18:00:17 INFO  opening file test_txt_small.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot tell in file
12/06/19-18:00:17 WARN  cannot open document test_txt_small.pdf frontend/document/pdfdocument.lua:35: ./ffi/mupdf.lua:67: MuPDF cannot open file.: cannot tell in file (2)
```

So, I'd say nothing to do on crengine side.
If we feel like it needs fixing (I don't :), it's in the frontend code to prevent opening any 0-size file with any engine.

**Comment by poire-z** [comment]
Although I guess a 0-bytes PDF file is an invalid PDF file, while a 0-bytes text file is still a valid text file :)

I'll fix this, as it looks simple to fix: crengine has this test before checking other formats like FB2, RTF, HTML:
```c
        if (m_stream->GetSize() < 5) {
            createDefaultDocument(cs16("ERROR: Wrong document size"),
                    cs16("Cannot open document"));
            return false;
        }
```
So, I guess if < 5, we can just go on with the plain text format parser, and display a 3 chars word, or a blank page if 0 char or one spaces and `\n`.

**Comment by Frenzie** [comment]
Yes, I'd say an empty text document should just display a white page. Bit useless, but still. ;-)

**Comment by poire-z** [comment]
Fixed with https://github.com/koreader/crengine/pull/322 via #5678.
