### ISSUE TITLE
Does koreader support arabic on kobo forma?

### ISSUE THREAD

**Issue by hgrain86** [koreader/koreader#5671]
* KOReader version:
* Device:

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by pazos** [comment]
> Does koreader support arabic on kobo forma?

see https://github.com/koreader/koreader/issues/5359, which is general support for Right-to-Left languages, like arabic. It has nothing to do with a particular device. The support, whatever it is, is for all platforms where KOReader run.

**Comment by pazos** [comment]
w

**Comment by poire-z** [comment]
Not in the 2019.11 release.
May be in the 2019.12 release.

**Comment by WaseemAlkurdi** [comment]
@hgrain86 
Arabic support is actually two different parts: KOReader's ability to show Arabic characters, and KOReader's interface displayed in Arabic.
As for the ability for KOReader to show Arabic, this is now nearly complete, huge thanks to work done by @poire-z, @Frenzie, and @NiLuJe.
I've done an Arabic keyboard, and it's nearly ready.
But as for the Arabic translations in KOReader, this isn't done yet. I'm working on that one, and you can help if you want. (But please comment here before you start so I can upload my progress)
دعم اللغة العربية في KOReader ينقسم إلى جزئين:
قدرة KOReader على عرض الأحرف العربية، وعرض واجهته باللغة العربية.
بالنسبة للجزء الأول، فقد شارف على الانتهاء، وذلك بالمجهود الجبار الذي قام به @poire-z, @Frenzie, @NiLuJe.
وقد قمتُ بصناعة لوحة مفاتيح عربية، وقد أصبحت شبه جاهزة.
ولكن بالنسبة للترجمة الفعلية للبرنامج، هذا ليس جاهزًا بعد. أنا أقوم حاليا بالترجمة، ويمكنك إن أردت المساعدة. (ولكن فضلًا علّق هنا إن رغبت بهذا قبل أن تبدأ لأرفع ما ترجمته إلى الآن على الموقع).
