### ISSUE TITLE
"Favorites" menu entry not translateable

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#5673]
* KOReader version:2019.11-55
* Device:Android

#### Issue
"Favorites" menu entry appears in English even though UI language is set to Russian
#### Steps to reproduce
I was unable to find the corresponding string in transifex and there are no untranslated strings there. (I am member of the Russian localization team)

**Comment by pazos** [comment]
The ocurrences are translated. See https://github.com/koreader/koreader/search?q=favorites&unscoped_q=favorites. Not sure if is just that transifex is being phased out. Pinging @Frenzie

**Comment by Frenzie** [comment]
Favorites is translated (and displayed) as Избранное. But indeed the problem is I haven't heard back from Weblate and I'd already prepared the nightly builds to depend on the submodule. I'll add a little Transifex pull.
