### ISSUE TITLE
[bug] editing a highlight on PW4 caused koreader to crash losing many annotations

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5676]
* KOReader version: 2019.11
* Device: PW4

#### Steps to reproduce
Highlight a passage
Click Edit
Start typing a few notes to myself... 
Koreader crashes.  
Lose a bunch of annotations that I made in the first three chapters of the book :(.  

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:
https://gist.github.com/arooni/124f2264820ba2ffe4537c6aabea22ea

seems like the ending part is the most relavent

```
12/08/19-12:14:26 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
12/08/19-12:14:26 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
12/08/19-12:23:54 WARN  got error waiting for events: Waiting for input failed: 4

error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
Killed
```

* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Huh. That's *probably* an OOM kill from the kernel.

Paired with the usual FAT32 on Kindle crap ;).

**Comment by poire-z** [comment]
Dunno if we can do anything about kindle killing koreader, but losing settings and annotations should now be limited to losing 15mn of annotations & page progress (that one can reduce to 5mn via the menu), thanks to #5678 and #5687, available in next nightly.
So, closing. Re-open if that happens again.
