### ISSUE TITLE
PB626: frontend/fontlist.lua:63: attempt to call field 'isKindle' (a nil value) > Segmentation fault

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#5688]
* KOReader version: v2019.11-75-gc6f553a_2019-12-12 
* Device: PBLux3 W626.5.14.1225 

#### Issue
Failed to start koreader.

#### Steps to reproduce
It happend after update from koreader version v2019.11. Just copy new files and replace old ones. It will crash right after koreader start.

##### `crash.log`
[crash_20191214095333.log](https://github.com/koreader/koreader/files/3963629/crash_20191214095333.log)

**Comment by Frenzie** [comment]
Possibly related to #5670, although at a glance nothing jumps out.

**Comment by poire-z** [comment]
```
./luajit: frontend/fontlist.lua:63: attempt to call field 'isKindle' (a nil value)
stack traceback:
    frontend/fontlist.lua:63: in function 'isInFontsBlacklist'
    frontend/fontlist.lua:87: in function '_readList'
    frontend/fontlist.lua:81: in function '_readList'
    frontend/fontlist.lua:98: in function 'getFontList'
    frontend/ui/font.lua:247: in function 'getFace'
    frontend/ui/widget/textboxwidget.lua:88: in main chunk
    [C]: in function 'require'
    frontend/ui/widget/scrolltextwidget.lua:14: in main chunk
    [C]: in function 'require'
    frontend/ui/widget/infomessage.lua:37: in main chunk
    [C]: in function 'require'
    frontend/docsettings.lua:15: in main chunk
    [C]: in function 'require'
    frontend/ui/data/settings_migration.lua:5: in main chunk
    [C]: in function 'require'
    ./reader.lua:145: in main chunk
    [C]: at 0x0000c4a9
Segmentation fault
```

Or my re-order of sections in reader.lua:
https://github.com/koreader/koreader/blob/7d231acad02eda2fac22ce7d1ac3bc2aed0c42d6/reader.lua#L144-L150
as it's CanvasContext:init() that's supposed to set the isKindle to it, that is nil there and cause the exception.
Possibly some early `require("docsettings")` in settings_migration.lua that could be delayed.
But I don't understand how it could jump from docsettings.lua:15 to using InfoMessage, which is way to early for using UI/widgets...
(And that segmentation fault... ?!)

@sonix-github : can you post here your file frontend/docsettings.lua ? Just to be sure it's not it that is messed up on your side for some reason ?

**Comment by Frenzie** [comment]
> as it's CanvasContext:init() that's supposed to set the isKindle to it, that is nil there and cause the exception.

While that sounds plausible enough in principle, what's really confusing to me is that logically such a thing should be an issue on all platforms (including Kindle itself). I don't see how it can be PB-specific.

**Comment by poire-z** [comment]
Unless there's setting migration that happens only when upgrading from one (old) specific version to this new one, that would trigger some specific code only then - but I don't see what :|
The stack trace is confusing - so may be it's just garbage cause by some other issue that later caused the segmentation fault :/ (and go understand that...)

> Just copy new files and replace old ones

You copied files manually? or just classic unzip other the koreader/ directory on your device?

Anyway, can you make a zip of your current crashing directory (for reference, and understanding what happened - and keeping your settings), and start from a fresh empty directory (and put back your settings) - and see if it happens again?

**Comment by sonix-github** [comment]
I copied it via total commander and during copy I have chosen option overwrite only older files as I do always. Now I have deleted whole koreader folder and copied new content and error has gone. I have copied all my previous settings and it is still ok. So maybe something went wrong with file overwriting at first attempt.

**Comment by poire-z** [comment]
Good!
Have you kept the bogus installation by chance (at least docsettings.lua) ?
Just curious, and so we'd know a bit more about what can have happened when we see such confusing stacktrace?

**Comment by sonix-github** [comment]
I have attached docsettings.lua. I have "played" how to show infomessage from lua script and left there unused line "local InfoMessage = require("ui/widget/infomessage")" that caused the error. It was my fault that I have not removed this line even there is no call for infomessage. I am sorry for the confusion.

[docsettings.lua.txt](https://github.com/koreader/koreader/files/3965274/docsettings.lua.txt)

**Comment by poire-z** [comment]
OK, good to know it's nothing with our code :)
