### ISSUE TITLE
[Request] Hyphenation + Text Alignment in pop-up footnotes

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#5699]
There isn't an option to edit the layout of footnotes. The alignment is justified by default, and hyphenation doesn't seem to reach it. 'Allow hyphenation on all text' doesn't work.

Is it possible to add an option to allow hyphenation and left-alignment ?

**Comment by NiLuJe** [comment]
Just passing thorough to mention that @poire-z is on a well deserved week off, so it might take a while for you to get a detailed answer ;).

**Comment by poire-z** [comment]
I thought I had already written a bit about this - but I can't find it.
Just https://github.com/koreader/koreader/pull/4261#issuecomment-429800143 about hacking a bit of the code to disable justification.

But the main issue is that for popup footnotes, we ask crengine for the HTML of the footnote content, and give that bit of HTML to MuPDF, and we get the rendering from MuPDF that we display in a ScrollHTMLWidget / HTMLBoxWidget, with some hardcoded CSS in https://github.com/koreader/koreader/blob/master/frontend/ui/widget/footnotewidget.lua.

MuPDF does not support any hyphenation, so we get what it can do, with what we can tweak with CSS.
(But in source/html/html-layout.c, it looks like it support soft hyphens - so, with some hard hyphenation work in Lua, we could inject some soft hyphens at the right places and may be get hyphenation from MuPDF... but not worth the effort for me.)

The alternative being to try to grab the renderered content from crengine (which may be messy, if there's a float alongside the footnote content), or grab the HTML and make a second DOM Document in crengine so it can render it with the same layout settings and fonts as the main document - which would be nicer. I never tried that, and that looks like quite some work :) Not too keen on investigating that, when we have something that's almost allright :)

Note that when the footnote popup is displayed, and if you don't like how it looks (I do that when it's some long footnote, I prefer reading it "in the book"), you can swipe to the left to jump to the footnote content in the book (displayed by crengine) - and swipe to the right to get back to your original page).

**Comment by poire-z** [comment]
> MuPDF does not support any hyphenation, so we get what it can do, with what we can tweak with CSS. (But in source/html/html-layout.c, it looks like it support soft hyphens...)

An other possibly simpler solution would be to have crengine (which has the hyphenation code and user settings) to insert these soft hyphens in the HTML snippet it returns.

@CalbertAmu : about left-alignment:
a) do you also disable justification in the book text?
b) If not, why would you prefer that in the popup footnote? Just because it looks better with the lack of hyphenation? Would you still left-align if you had text hyphenated?
c) Do you also disable justification for the dictionary lookup results (and so, in wikipedia results)?

Anyway, you can disable justification by just removing that line, or making it a typo (replace `text-align` with `DISABLEDtext-align`):
https://github.com/koreader/koreader/blob/c3a0bd4def2243b66cacf27222b62d9441ebbaff/frontend/ui/widget/footnotewidget.lua#L65

**Comment by CalbertAmu** [comment]
@poire-z 

a) Yes, I did it from style tweaks: Left alight most text
b) Yes, left-align looks better when there's no hyphenation. Most of the time I choose left-align even if there is hyphenation
c) yes I disable justification in dictionary results too

Changing that line helped what I needed. Thank you

**Comment by poire-z** [comment]
> Changing that line helped what I needed.

OK, but I was trying to think about what would be needed or if we could re-use that `dict_justify` setting, or if we should propose new options in the menu - so you don't have to change that line each time you upgrade koreader :)

But as we already have 2 options for popup footnotes, in the main `Links>` menu, we could bring them in a submenu and add 2 new ones:
```
[x] Show footnotes in popup
Footnote popup settings>
    [ ] Show more links as footnotes
        Set footnote popup font size
    [x] Justify popup footnote text    (would just add/remove "text-align: justify")
    [ ] Hyphenate popup footnote text  (if we can have crengine insert soft-hyphens)
```

**Comment by poire-z** [comment]
OK, I got the "crengine insert soft-hyphens" solution working https://github.com/koreader/crengine/pull/325#issuecomment-573335619, so we'll be able get hyphenation in the footnote popup.

So, how do we enable it?
A) Always? as it uses the hyphenation settings set for the book we read - so if the user has set some hyphenation, no reason for him to not want that in the footnote popup (and if he has chosen `Hyphenation>None`, crengine will just put no soft-hyphen, so no hyphenation either).
B) Or should it be toggable via a menu item?

And about text left/justify?
C) Menu item to allow the user chosing (we can't guess how it's displayed in the page)?
D) Re-use `dict_justify` (as what they want for dicts/wikipedia is probably what they'd want too in popups)?
E) Hidden/manual setting?
F) Or let users hack the CSS in footnotewidget.lua?
