### ISSUE TITLE
Client SSL certificate for mutual TLS authentication

### ISSUE THREAD

**Issue by dzervas** [koreader/koreader#5700]
I have to admit that this feature might be a bit far fetched, but I’m a bit security paranoid.

Is there support for a client certificate for mutual tls authentication with wallabag (and other self hosted solutions, sftp for example)?

I can’t seem to find any info on how to achieve that.

**Comment by Frenzie** [comment]
You can specify certificates in the code:

https://github.com/brunoos/luasec/wiki

You could make it auto-detect a client certificate somewhere, but you'd have to write the stuff first. Unless someone already wrote it elsewhere, which isn't unthinkable. ;-)
