### ISSUE TITLE
Page turn button not fully working in kindle voyage

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#5706]
* KOReader version: 2019.11
* Device: kindle voyage

#### Issue
There is two page turn button in kindle voyage, front with a bar sign, and back with a dot sign. Only the front button works fine. There is no response when press the back button. Both front and back work well in original kindle os. So this should not be the hardware problem. And I have not found any configuration menu to set this function.

#### Steps to reproduce
Open koreader in kindle voyage
Press the front button, it works fine
Press the back button, no response

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Yes, it's a known issue dues to some kind of weird-ass limitations on Amazon's part.

**Comment by NiLuJe** [comment]
(There are more technical details in a few matching issues in KPVBooklet, IIRC).

**Comment by NiLuJe** [comment]
re #4182

**Comment by NiLuJe** [comment]
re #2923

**Comment by NiLuJe** [comment]
re #2173 (that one has technical details)

**Comment by NiLuJe** [comment]
re #2171

**Comment by NiLuJe** [comment]
re #1801

**Comment by Hzj-jie** [comment]
Slightly more details, when the device resumed from screensaver (from Amazon), usually you need to swipe to unlock. Without this action, the buttons won't work.
