### ISSUE TITLE
Clarify how to set customised footnote markers

### ISSUE THREAD

**Issue by protist** [koreader/koreader#5707]
* KOReader version: koreader-kobo-v2019.11
* Device: Kobo H2O

#### Steps to reproduce
1) Attempt to display in-line footnotes
2) None are shown

#### Issue
With my epub document, I have enabled the setting where I can tap a footnote, and it will display in a pop-up at the bottom of the page. This works perfectly.

However, when I try to display footnotes inline, as per [this page](https://github.com/koreader/koreader/wiki/In-page-footnotes), nothing shows. I assume it's because the footnotes in my document are in an unexpected format. An image on that linked page suggests that custom classes can be set. However, KOReader's menu currently looks different to the menu on that page. How can I either:
a) determine what KOReader currently uses to recognise footnotes (hence I can edit my epub document), or
b) customise KOReader to recognise my document's custom footnotes.

(For reference, my document has `<a href="#rch1star1">*</a>`, which links to `<p class="note3"><a href="#ch1star1" id="rch1star1">*</a> ... </p>`, where the class is `note[0-9]`.)

**Comment by poire-z** [comment]
Originally (so, that Wiki page), there was only one "catch all" style tweak to enable in-page footnotes.
Since then, with #4454, it has been split into 3 style tweaks (x2=6, for normal vs smaller font size, for each of the 3) :
https://github.com/koreader/koreader/blob/c3a0bd4def2243b66cacf27222b62d9441ebbaff/frontend/ui/data/css_tweaks.lua#L525-L629

What you're after is the 3rd (so, 5th and 6th) "In-page classic classname footnotes", where there is already a `.note1`, that you can extend by either:
- hack it in that code
- hack it in that code, and PR your change if they are generic and not confusing enough
- duplicate it as a User style tweak, so you can add all the class names you may find. See https://github.com/koreader/koreader/pull/3944#issuecomment-389069259

**Comment by protist** [comment]
Thanks @poire-z. I'm happy to PR a change in general, but it's probably a bit beyond me for several reasons. Can one use regex in Lua's `[[ ]]` (whatever that is)? I'd also have to work out how to build a patched version for my Kobo to test. If it's simple enough (and if you think it's a good idea), could you possibly just add in the `note[0-9]` patterns? (I'm also not even really sure how `.note1` == `note1`.)

**Comment by Frenzie** [comment]
[[]] is a string. Look up Lua patterns fir the basics.

**Comment by poire-z** [comment]
> I'd also have to work out how to build a patched version for my Kobo to test.

Well, as all that is in Lua, no need to "build" koreader, you can just edit Lua plain text files on your Kobo. That would be the koreader/frontend/ui/data/css_tweaks.lua file I mentionned.

Also, in this file, it's just plain string that are CSS snippets, where we mention class names - and there's no regexp pattern in CSS files, so you'd have to add all the class names.
So, that would be just updating these few lines in this file:
```diff
--- a/frontend/ui/data/css_tweaks.lua
+++ b/frontend/ui/data/css_tweaks.lua
@@ -604,7 +604,8 @@ ol.references > li > .mw-cite-backlink { display: none; }
 Show footnotes with classic class names at the bottom of pages.
 This tweak can be duplicated as a user style tweak when books contain footnotes wrapped with other class names.]]),
                 css = [[
-.footnote, .note, .note1, .ntb, .ntb-txt, .ntb-txt-j
+.footnote, .note, .note1, .ntb, .ntb-txt, .ntb-txt-j,
+.note2, .note3, .note4, .note5, .note6, .note7, .note8, .note9
 {
     -cr-hint: footnote-inpage;
     margin: 0 !important;
@@ -618,7 +619,8 @@ This tweak can be duplicated as a user style tweak when books contain footnotes
 Show footnotes with classic classname at the bottom of pages.
 This tweak can be duplicated as a user style tweak when books contain footnotes wrapped with other class names.]]),
                 css = [[
-.footnote, .note, .note1, .ntb, .ntb-txt, .ntb-txt-j
+.footnote, .note, .note1, .ntb, .ntb-txt, .ntb-txt-j,
+.note2, .note3, .note4, .note5, .note6, .note7, .note8, .note9
 {
     -cr-hint: footnote-inpage;
     margin: 0 !important;
```

> I'm also not even really sure how .note1 == note1

Yes, `.note1` in a CSS file or snippet specifies class name `note1`, and matches `<p class="note1">`.

> could you possibly just add in the note[0-9] patterns?

Are you really sure they are all (.note2, .note3, .note4, .note5, .note6, .note7, .note8, .note9) really used? (The more classnames, the more checks, the more time is spent checking and applying CSS, so better to be sure and not waste time).

Anyway, for you now and to validate that works for you, here are 2 "user style tweaks" (inside the zip) with these changes that you can drop as-is on your Kobo in koreader/styletweaks/, and you'll find them at the bottom of the Style tweaks menu: [more_classic_in-pages_footnotes_2tweaks.zip](https://github.com/koreader/koreader/files/4007896/more_classic_in-pages_footnotes_2tweaks.zip).
You can uncheck the koreader ones, and check these - to see what would happen if we added those classnames.

**Comment by protist** [comment]
Thanks @poire-z for that amazingly-detailed explanation. That all makes sense and I'm glad to have learnt more.

> Are you really sure they are all (.note2, .note3, .note4, .note5, .note6, .note7, .note8, .note9) really used?

I grepped through the epub, and I can actually only see `note[1-3]`, so the list could be reduced in theory, at least for this specific document.

>  (The more classnames, the more checks, the more time is spent checking and applying CSS, so better to be sure and not waste time).

FWIW I didn't notice any obvious slowdown, but perhaps this would be more of an issue with less-powerful hardware.

> Anyway, for you now and to validate that works for you, here are 2 "user style tweaks"

I can confirm that these work perfectly. Thank you!
