### ISSUE TITLE
Unidentified characters in dictionary

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#5710]
* KOReader version:22.12.19
* Device:kobo clara hd

#### Issue
I am getting un identified characters. The language is RTL. Please help
![IMG_20191231_002115](https://user-images.githubusercontent.com/59373108/71597047-887ef600-2b63-11ea-98e6-1ab7cab5a9e6.jpg)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by poire-z** [comment]
If Urdu is written with Arabic letters, they should be provided by the `Noto Sans Arabic UI` font we ship. If not, well, we're missing a font that provides these glyphs.

BUT, if your dictionary (can't find it on the web to check myself) provides results in HTML, you may not benefit from our recent work, as it will be rendered by MuPDF that does not (yet?) use Noto Sans Arabic.

You can see if it's HTML by looking in the .ifo file, if you see `sametypesequence=h`, it is.
You can try making it seen as a NON-HTML dict by editing that .ifo file (backup that file before) and changing `sametypesequence=h` to `sametypesequence=x`.

**Comment by abdrau26** [comment]
Thank you very much. I changed "h" to "x" and the issue is resolved.

**Comment by poire-z** [comment]
Good :)
Just curious: can you post a pic of how that same page (lookup of "available") look now?

**Comment by abdrau26** [comment]
Of course..
![Uploading IMG_20191231_012058.jpg…]()

**Comment by poire-z** [comment]
^ You clicked the Comment button before your pic was fully uploaded :) So it's not there.

**Comment by abdrau26** [comment]
![IMG_20191231_012058](https://user-images.githubusercontent.com/59373108/71599407-8a00ec00-2b6c-11ea-92cd-968cecfc173d.jpg)

**Comment by abdrau26** [comment]
Sorry, i have joined today this site

**Comment by poire-z** [comment]
No worry :)

You're ok with how that looks?
The fact that the definition is on 3 short lines, is that ok, do the line break positions make sense ? Or does they feel arbitrary?
Or should all the Urdu text be on a single line?

(The fact the first line is left aligned is that it starts with a LTR/english word ("Urdu:") - the 2nd and 3rd line, being full RTL Urdu, are right aligned. I don't think we can do better than that, not knowing the main language of a dict.)

**Comment by abdrau26** [comment]
It is perfect.
