### ISSUE TITLE
Cannot be relaunched after update

### ISSUE THREAD

**Issue by zivilyyyn** [koreader/koreader#5721]
* KOReader version:v2019.11-51-ge8f91ab_2019-12-03
* Device:KPW3-32G

Cannot be relaunched after update. Just like issue #5269.
[crash.log](https://github.com/koreader/koreader/files/4014171/crash.log)

**Comment by Frenzie** [comment]
I only see clean exits. Pinging @NiLuJe for Kindle.

**Comment by Frenzie** [comment]
Btw, how do you mean after update? That version you mention is from a month ago.

**Comment by NiLuJe** [comment]
The vfat proxy strikes again (probably) ;).

Define "can"t be relaunched", though.

The usual failure after an OTA triggered by said fuse proxy is the Kindle WM not being re-awoken: KOReader exits successfully, but the wrapper script crashes and burn because it got truncated, so you're left in a state where mostly everything appears frozen, while in fact you're just need to do a `killall -CONT awesome`in a shell to get everything back up.

**Comment by Monirzadeh** [comment]
i have same problem i install koreader on kindle pw3 (7 generation) from [here](https://github.com/koreader/koreader/releases/tag/v2019.12).
if i  try to update with OTA in developer channel  every things work fine , until i try to open koreader again with kual
i get error koreader not found

**Comment by Hzj-jie** [comment]
This may be a real issue, it started from v2019.12.???. Last known good version is v2019.12.0 (last stable).

**Comment by Frenzie** [comment]
In that case it's almost certainly something in https://github.com/koreader/koreader/pull/5715

**Comment by NiLuJe** [comment]
Original report is from before both 2019.12 & #5715 

(Also, i can't reproduce ;p).

**Comment by NiLuJe** [comment]
Ah. What was missing in those reports is that the OTA update actually *fails*.

```
/bin/sh: ./fbink: Text file busy
/var/tmp/gnutar: koreader/libkohelper.sh: Cannot hard link to ‘extensions/koreader/bin/libkohelper.sh’: Operation not permitted
/var/tmp/gnutar: Exiting with failure status due to previous errors
```

So, yeah, I'll fix that ;p.

**Comment by NiLuJe** [comment]
Fun fact: couldn't reproduce because I was checking the *zip* , not the tarball, which of course bypasses (the gist) of the problem by dereferencing links by default ;).

**Comment by NiLuJe** [comment]
I also have no clue why a symlink ended up being stored as a hard link, but that's another kettle of fish... :D
