### ISSUE TITLE
Spécial characters rendering error on a particular book

### ISSUE THREAD

**Issue by abdoulayeYATERA** [koreader/koreader#5723]
* KOReader version: v2019.12.5-gd647c62_2019-12-31
* Device: Kobo Format

#### Issue
On one particular book, some special characters are not shown correctly.
![IMG_20191221_002751](https://user-images.githubusercontent.com/9435855/71645656-acfdde00-2cdb-11ea-9b2f-6c8f2bc9a6f8.jpg)

As you can see "Crécy" becomes CrAⒸy and "—" becomes âT"
I don't have the issue with other books
I don't have the issue when i open the book with Calibre
Unfortunately i can't share the book, it's not free.

#### Steps to reproduce
1. Open the book

**Comment by Frenzie** [comment]
That's likely an issue with the document, for example ISO-8859-1 when it should be UTF-8 (because EPUBs are XML).

**Comment by abdoulayeYATERA** [comment]
Hey Frenzie ! How are you. Thank's for the reply.
Well... you are absolutely right. it's exactly that. 
Don't hesitate to close the issue, i'll try to convert the book.

**Comment by Frenzie** [comment]
Alright, I'll close it then. ;-)

How'd you determine the encoding btw? Some menu in calibre?

**Comment by abdoulayeYATERA** [comment]
I try with Calibre but didn't find anything concerning the epub file encoding.
I had to check within the epub html files directly.
Used Calibre to switch to TXT, everything is alright now.
Thank's again.
Keep up the good work !
