### ISSUE TITLE
Landscape screensaver to portrait

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#5724]
* KOReader version: 2019.11
* Device: PW4
Recently, I have some pdf books. My best choice was to read in landscape mode with support of semi-auto crop. Everything was fine until I hit sleep button, the book cover was in landscape mode which was not the direction that it was designed.

May I ask or a feature to auto rotate book cover to portrait mode even we're reading in landscape mode?
Thank you.

**Comment by poire-z** [comment]
> KOReader version: all version
> Device: all device

You have ALL the devices we support, and you have tested that on all of them ?! impressive :)
Seriously, on what device do you get that? And which koreader version?

I have not tested it, but we have some code that's supposed to deal with that, at least on Kobo and Powerbook if I trust the comment:
https://github.com/koreader/koreader/blob/0f896765c371c64d2cbefb4299f6d5658bee79b7/frontend/device/generic/device.lua#L189-L233

**Comment by uphantom89** [comment]
Ah sorry, I misunderstood the meaning of "device" :).
My mean was kindle PW4, and my Kobo Touch also encoutered the same.

**Comment by pazos** [comment]
@poire-z: FYI I cannot reproduce on cervantes. Screensaver is always on portrait no matter what is the orientation of the current book.

**Comment by uphantom89** [comment]
Illustration picture:
![0102200725](https://user-images.githubusercontent.com/27908681/71648009-6d90bb00-2cf6-11ea-9c0b-51c204332eeb.jpg)

**Comment by poire-z** [comment]
> my Kobo Touch also encoutered the same.

Sure? That code should be triggered on Kobo.
Looks like there is no such rotation before screensaver show in device/kindle/device.lua. @NiLuJe : any reason, or we just forgot it?).
But let's first focus on Kobo.

Can you check if you get the same thing with an EPUB that has a cover image, when you set it to be read in landscape mode?
Might be something with PDF where the cover image is the first page, so it might be in landscape aspect ratio if the book is read in landscape (caused or not by your semi-auto-crop...)

Does it happen with any book you read in landscape mode, or only some specific one - or only with some specific crop setup?

**Comment by uphantom89** [comment]
For Kobo Touch, it happened with pdf file. Curently, I don't have it on hand as I give it away.
For PW4, it happened to all file extension (.pdf,.epub ...) , the illustration pictures was epub file.

**Comment by MariusSp** [comment]
Same experience here on PW2. When reading in Landscape mode, the (portrait) cover is in landscape as well.

**Comment by daemongloom** [comment]
Is it possible to add forcing screensaver portrait mode as a toggle or advanced setting? I'm using "reading progress as screensaver" and it looks really weird when book and screensaver are in different orientation. Previous version worked better for me - I lock the screen and there is no need to rotate device to check reading progress. Now I have to rotate device each time. Also there is no way to get device correctly before it fully wakes up (as I read both in landscape and reverse landscape depending on situation).

**Comment by NiLuJe** [comment]
@daemongloom: IIRC, that widget is not actually designed to be laid out in Landscape mode. I have no idea how it looked before, but it possibly wasn't as intended.

**Comment by daemongloom** [comment]
In fact, it was perfect in landscape. Any Screensaver except book cover was perfect.

**Comment by NiLuJe** [comment]
Huh. Indeed it does. I could have sworn that wasn't the case when the Portrait-in-screensavers switcheroo was implemented ;).

**Comment by daemongloom** [comment]
> Huh. Indeed it does. I could have sworn that wasn't the case when the Portrait-in-screensavers switcheroo was implemented ;).

Updated to latest dev version. Landscape screensaver works great now, thanks :)
