### ISSUE TITLE
Bug? With mini status bar and reclaim bottom margin enabled text is cut off 

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5728]
See image attached 
 

Latest stable release on pw4

**Comment by arooni** [comment]
![](https://i.imgur.com/Hy5NrJT.jpg)

**Comment by NiLuJe** [comment]
because that's what "Reclaim" does ;).

**Comment by NiLuJe** [comment]
Instead of adding its own height to the bottom margin to make room for itself, it squats the existing bottom margin. If said bottom margin is too small, it'll clip. That's the entire *raison d'être* of this setting ;).
