### ISSUE TITLE
Crash if no dictionary is installed

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#5730]
* KOReader version: 2019.12
* Device: Tolino Epos 2

#### Issue
Crash if a word in the book is selected an no dictionaries are installed.

#### Steps to reproduce
Select a word -> Crash

**Comment by poire-z** [comment]
Glad it's invalid and one less thing to fix :) but why is it, invalid?

**Comment by pazos** [comment]
I cannot reproduce with the steps mentioned in the ticket. (If no 3rd party app is enabled and no dict installed you'll get the "normal" please install dict widget). Hence `invalid`.

I guess OP is talking about the following steps:

- Go to dict settings
- Enable use 3rd party apps (without any dictionary app available)
- try to start a lookup

**Comment by Frenzie** [comment]
I can't reproduce any crashes as (seemingly) described in the OP, but I can reproduce a crash using the steps described by @pazos 

```
01-02 21:08:43.848  2770  2783 V KOReader:  dict lookup word: vijand {
01-02 21:08:43.848  2770  2783 V KOReader:     ["y"] = 732,
01-02 21:08:43.848  2770  2783 V KOReader:     ["x"] = 286,
01-02 21:08:43.848  2770  2783 V KOReader:     ["h"] = 47,
01-02 21:08:43.848  2770  2783 V KOReader:     ["w"] = 132
01-02 21:08:43.848  2770  2783 V KOReader: }
01-02 21:08:43.848  2770  2783 V KOReader:  dict stripped word: vijand
--------- beginning of crash
01-02 21:08:43.849  2770  2783 E AndroidRuntime: FATAL EXCEPTION: Thread-207
01-02 21:08:43.849  2770  2783 E AndroidRuntime: Process: org.koreader.launcher, PID: 2770
01-02 21:08:43.849  2770  2783 E AndroidRuntime: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter action
01-02 21:08:43.849  2770  2783 E AndroidRuntime: 	at org.koreader.launcher.BaseActivity.dictLookup(BaseActivity.kt)
01-02 21:08:43.851  2770  2770 D KOReader: [NativeGlue]: WindowFocusChanged: 0xb40fa960 -- 0
01-02 21:08:43.859  1302  1302 E EGL_emulation: tid 1302: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)
01-02 21:08:43.865  2770  2770 D KOReader: [MainActivity] onPause()
01-02 21:08:43.865  2770  2770 D KOReader: [NativeGlue]: Pause: 0xb40fa960
01-02 21:08:45.370  1653  1731 E Surface : getSlotFromBufferLocked: unknown buffer: 0x9e714500
01-02 21:08:45.439  1653  1713 E InputDispatcher: channel '11bd60 org.koreader.launcher/org.koreader.launcher.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by elvvis** [comment]
Sorry for my not so detailed description.
3rd party app is enabled and no app is installed.

**Comment by poire-z** [comment]
OK. But shouldn't we try to avoid that crash and show a message or nothing, or is that complicated because... android :) ?

**Comment by pazos** [comment]
> OK. But shouldn't we try to avoid that crash and show a message or nothing, or is that complicated because... android :) ?

Yeah, it was implicit on my response. Do nothing is really easy. Showing a message is not complicated but not sure if is needed.

**Note:** The entire JNI -> kotlin interface has no guard against null pointers. So all functions in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/JNILuaInterface.kt which require non nullable arguments will crash if they're used with nil/null values.

For example: android.notification(nil) will invoke showToast(nil) and that will crash the VM because showToast takes a non nullable String as an argument.

**Comment by Frenzie** [comment]
Btw, don't forget about scenarios like installing an app, selecting it, and then uninstalling it. :-)
