### ISSUE TITLE
Crash when trying to run an update

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#5731]
* KOReader version: 2019.11
* Device: Tolino Epos 2

#### Issue
Crash when trying to run an update

#### Steps to reproduce
Select Update -> Check for Update. If there is an update available, click Update -> Crash

**Comment by pazos** [comment]
@elvvis: logs please

**Comment by elvvis** [comment]
[C-1577728505163.txt](https://github.com/koreader/koreader/files/4017113/C-1577728505163.txt)
[C-1577727169522.txt](https://github.com/koreader/koreader/files/4017114/C-1577727169522.txt)

**Comment by pazos** [comment]
oh, I see, thanks for the logs.

Can't reproduce on the emulator or a device.  Did it work for you sometime in the past? Did you update the firmware of your device?.

The code used to download is in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/org/koreader/launcher/BaseActivity.kt#L290-L306. Is using common paths retrieved using Environment.

**Comment by elvvis** [comment]
This is my new e-reader and i tried it the first time.
Firmware of the device is the newest version: 13.2.0 .

**Comment by pazos** [comment]
It is actually very cool that the new firmware doesn't break the epd driver. About this specific issue I'm not sure if is fixable on that specific firmware. Your best bet is to download updates manually or switch to Fdroid.

**Comment by pazos** [comment]
@elvvis: will be workarounded in tomorrow's OTA.

You need to install it manually. Once installed you should be able to upgrade (or downgrade). It will detect that your device is not able to download packages and will ask you if you want to retry using the browser.

Obviously that requires a browser but it won't crash if no one is available.

**Comment by elvvis** [comment]
@pazos: great job, thank you. I will install it tomorrow.
