### ISSUE TITLE
Crash when panning image

### ISSUE THREAD

**Issue by RenaKunisaki** [koreader/koreader#5740]
* KOReader version: 2019.12
* Device: Kobo Touch model N905C

#### Issue
Panning an image crashes.

#### Steps to reproduce
1. Open a very wide image
2. Zoom to fit height
3. Pan left (hold finger on screen, then swipe left)
4. Crash

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/4021391/crash.log)

**Comment by Frenzie** [comment]
```
./luajit: frontend/apps/reader/modules/readerhighlight.lua:665: attempt to call method 'getTextFromPositions' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerhighlight.lua:665: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:251: in function 'handleEvent'
	frontend/ui/uimanager.lua:675: in function 'sendEvent'
	frontend/ui/uimanager.lua:175: in function '__default__'
	frontend/ui/uimanager.lua:1015: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1076: in function 'handleInput'
	frontend/ui/uimanager.lua:1120: in function 'run'
	./reader.lua:279: in main chunk
	[C]: at 0x000140c1
```

**Comment by poire-z** [comment]
Solved with this:
```diff
--- a/frontend/document/document.lua
+++ b/frontend/document/document.lua
@@ -277,2 +277,6 @@ end

+function Document:getTextFromPositions(pos0, pos1)
+    return nil
+end
+
 function Document:getTextBoxes(pageno)
```

That function was just defined and implement for documents with text like PDF, DJVU and EPUB.

> Pan left (hold finger on screen, then swipe left)

Note than hold + pan is for selecting text - so this won't make hold + pan actually pan, it would just prevent a crash with documents that have no text to be selected, like images :)

**Comment by RenaKunisaki** [comment]
Is it possible to freely pan images? The "turn page" model doesn't work so well with some.

**Comment by poire-z** [comment]
I managed to pan along the width with swipe left/right.
An other alternative viewer to the PicDocument is the ImaveViewer widget: if you're using Mosaic or List mode (not classic mode), just hold on the book (in History or File browser) and select "View full size cover". Then, you can swipe/pan in all directions and zoom (pinch or strecth, or by swipe up/down on left/right sides).
