### ISSUE TITLE
Tapping on Evernote password field crashes

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#5748]
* KOReader version: 2019.12
* Device: Kobo Forma

#### Issue
After clicking on Plugins -> Evernote -> Login -> Evernote and entering email, when tapping on password field, KOReader crashes with the log below.

This was working fine on 2019.11. Crash happens after upgrade to 2019.12.

##### `crash.log`
[7813] Jan 05 21:31:46 Running in background
[7831] Jan 05 21:31:50 Child connection from 192.168.1.107:65267
[7831] Jan 05 21:31:51 Pubkey auth succeeded for 'root' with key sha1!! 4e:f6:53:d7:dc:0e:be:32:07:9c:c2:78:04:f1:ca:e7:ec:95:74:ba from 192.168.1.107:65267
./luajit: frontend/ui/widget/textboxwidget.lua:946: attempt to index field '_bb' (a nil value)
stack traceback:
	frontend/ui/widget/textboxwidget.lua:946: in function 'paintTo'
	frontend/ui/widget/horizontalgroup.lua:53: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:52: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
	frontend/ui/widget/container/centercontainer.lua:24: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:52: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
	frontend/ui/widget/container/centercontainer.lua:24: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
	frontend/ui/uimanager.lua:932: in function '_repaint'
	frontend/ui/uimanager.lua:1048: in function 'handleInput'
	frontend/ui/uimanager.lua:1120: in function 'run'
	./reader.lua:276: in main chunk
	[C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash n°1: 01/05/20 @ 21:35:33)
Running FW 4.19.14123 on Linux 4.1.15-00285-ge6f1309 (#79 SMP PREEMPT Mon Jul 8 14:30:15 CST 2019)
Attempting to restart KOReader . . .
!!!!

**Comment by Frenzie** [comment]
Neither of the two commits 7b0b5d5ba703d0beabe5d30e8f48891a96f1433d or 0599c440cc934c1dceb5a2fed4aebb02bf01823e look relevant, so it seems more likely to be something in TextBoxWidget.

https://github.com/koreader/koreader/commits/master/frontend/ui/widget/textboxwidget.lua

**Comment by poire-z** [comment]
Yes, possibly all the TextWidget changes related to XText.
Or LoginDialog widget that I've never really visited, that may not be up to standards :)

Can you try if this simple patch solves the issue (it avoids the crash for me) and don't cause others (I don't use Evernote, can't check how it goes):
```diff
--- a/frontend/ui/widget/logindialog.lua
+++ b/frontend/ui/widget/logindialog.lua
@@ -102,14 +102,13 @@ function LoginDialog:onSwitchFocus(inputbox)
     -- unfocus current inputbox
     self._input_widget:unfocus()
     self._input_widget:onCloseKeyboard()
-    UIManager:close(self)

     -- focus new inputbox
     self._input_widget = inputbox
     self._input_widget:focus()
     self._input_widget:onShowKeyboard()

-    UIManager:show(self)
+    UIManager:setDirty(self, "ui")
 end

 return LoginDialog
```

I made sure UIManager:close() would free all Text*Widgets ressources - I don't think we anywhere expect something UIManager:close'ed to ever be UIManager:show'ed again.
@NiLuJe : do you think this is a right assumption?

**Comment by SilverGreen93** [comment]
Yes, this fixes the issue. No more crashes, in Evernote login dialog at least.

**Comment by NiLuJe** [comment]
At the very least, that close/show stuff looked wonky as hell, so I'd say,
yeah, sane assumption ;).
