### ISSUE TITLE
invert page turn taps and swapes not change next and previous spot in highlighte mode

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#5750]
* KOReader version:2019.12
* Device: Paperwhite 3

#### Issue
`invert page turn taps and swapes` not invert next page an previous page spot in highlighte mode

#### Steps to reproduce
open a book and active `invert page turn taps and swapes`
select a world and swap until end of the page and try to next page 
in RTL you should change page in hilightmode with bottom left corner(next page) and up right corner (previous page) 
but for now it is in LTR mode so bottom right corner(next page) and up left corner (previous page) 
and `invert page turn taps and swapes` not invert that

**Comment by poire-z** [comment]
I'll help :)
Possibly just a matter of involving `inverse_reading_order` to flip this:
https://github.com/koreader/koreader/blob/e172926af5338435d14c722d56a48c5ecdd9e837/frontend/apps/reader/modules/readerhighlight.lua#L601-L612
like in
https://github.com/koreader/koreader/blob/e172926af5338435d14c722d56a48c5ecdd9e837/frontend/apps/reader/modules/readerrolling.lua#L308-L311
