### ISSUE TITLE
NewsDownloader stop download instead of skip problematic item

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#5755]
* KOReader version: 2019.12
* Device: Kindle Paperwhite 3

#### Issue
if you use News Downloader to download item that has unsupported format, download items in rss stop instead of skip that specific item
#### Steps to reproduce
add a feed address to News downloder config (i use pocket feed  )
add some article and [this](https://thefirehoseproject.com/developer-guide/1) -i middle of your list-as an item that has unsupported format
try download the feed 
base on this issue #3598 you get `unsupported format` error and stop download instead of skip that item and report them in log
i am not check why exactly news downloader can't handle that item.
[this service](www.feedvalidator.org) say `title should not contain HTML: &#039;`
but i can't download other item until, i remove that article

**Comment by roygbyte** [comment]
Possibly fixed by https://github.com/koreader/koreader/pull/8145 ??
