### ISSUE TITLE
Can't support Pdf files which are download from CNKI

### ISSUE THREAD

**Issue by see1see** [koreader/koreader#5756]
* KOReader version:V2019.11
* Device:dasang not-ereader

#### Issue
can't support some Pdf files which are download from CNKI
#### Steps to reproduce
Open some pdf documents  it will display garbled code

[](https://pan.baidu.com/s/1yuP2i2lafcwFoi2ns6zHvg) Extraction code: waxn

**Comment by Frenzie** [comment]
Even if the documents in question are behind a paywall, without an error.log or a reference to where the file can be obtained there's nothing that can realistically be done.

Btw, what's an extraction code? Do you mean these are password-protected PDFs?

**Comment by Mayonnnaise** [comment]
It's probably the problem of CNKI itself. Some of the PDF files on it are converted from CAJ files, and the fonts are not embedded in a standard way. (See also: https://sspai.com/post/47092  "保真性的例外", https://discussionschinese.apple.com/thread/250529439?answerId=251054381322#251054381322）

**Comment by Frenzie** [comment]
I'll close this on account of the borked document hypothesis from the Chinese Apple board. Please feel free to provide an actual sample document.
