### ISSUE TITLE
Shortcut for hidden folders

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#5759]
V2019.12
Kobo clara hd
Can I create shortcuts for hidden folders?
I have checked "show hidden folders".

**Comment by Frenzie** [comment]
I didn't understand the question, but it's a bug report, not a question. :-) Pinging @robert00s who fixed a few similar ones.

**Comment by KenMaltby** [comment]
I don't see what would be meant as "a shortcut for folders", hidden or otherwise.

**Comment by abdrau26** [comment]
When you click "+" sign, you see"folder shortcuts". @KenMaltby .
Anyway the problem is resolved by just restarting the koreader.

**Comment by Frenzie** [comment]
I'll reopen it for now if you don't mind, because that's just a workaround. ;-)
