### ISSUE TITLE
Taking screenshot

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#5760]
V2019.12
Kobo clara hd
When I swipe from one corner to another corner diagonally, screen refreshes only instead of taking screenshot. Multi swipe feature is off. Please guide.

**Comment by KenMaltby** [comment]
When I have that problem, it has usually been that I didn't make the swipe long enough.

**Comment by abdrau26** [comment]
I have given many tries, but the result is same. Also there is no option for taking screenshot in short diagonal swipe.

**Comment by Frenzie** [comment]
Is this while displaying a particular feature or just in the reader?

**Comment by abdrau26** [comment]
It happens when I open a PDF file with reflow option open.

**Comment by abdrau26** [comment]
When I open EPUB file, neither screen refreshes, nor it takes screenshots.

**Comment by NiLuJe** [comment]
Can't reproduce on a H2O, FWIW (multiswipe disabled, too).

**Comment by Frenzie** [comment]
Multiswipe (or EPUB) makes no difference anyway. It probably means that you're swiping too slowly for the program so it turns into a pan instead, or something like that. (And it is somewhat difficult to swipe sufficiently quickly yet also a sufficiently long distance.)
