### ISSUE TITLE
[FR/Android]: Simulate light warmth and extra dimming on lcd screens

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5768]
I'm aware that KOReader for android is full of tricks. That's the last one I want to implement :smile: 

That's it: implement an overlay on top of KOReader window, so features like screen dimming beyond hardware levels and light warmth can be simulated.

At first tried to do that on top of KOReader itself, but given the record of bugs that using a surfaceView on top of the native view had on some devices I would go for implementing this outside the program.

There are plenty of 3rd party screen filters that can do that, but the hability to use slide gestures within KOReader would be awesome. I commented on a issue opened at [Red Moon for 3rd party integrations](https://github.com/LibreShift/red-moon/issues/202)

While I'm still thinking that integration with free apps is the way to go I played a bit with a standalone implementation for us based on a service, that needs to be installed as an extension to KOReader.

In any case the behaviour would be the same: check if a 3rd party service is enabled, bound the activity to it, promote the device as one with natural light support and forward messages to the service, which is the one that draws the overlay.

The task is feasible and has the same latency as in my ereader, but the whole idea sound hackish as hell, so I'm looking for feedback about the implementation. 

Shall I write it as part of core app or as a plugin?.

How to distribute the apk that needs to be installed? I guess it can be downloaded using the same method used for updates.

**Comment by Frenzie** [comment]
What do you mean by plugin or part of the core precisely? It sounds like the amount of Lua code would be fairly minimal so I figure that should be fine in some Android-specific device implementation. Depending on some other app sounds quite fine to me too, to reduce complexity.

**Comment by pazos** [comment]
I think I will work a bit on a example app to show you how it behaves and then ask the questions, because explain how it behaves is 100x harder for me :smile:

**Comment by pazos** [comment]
Ok, I've implemented a service, intended to run as a "server", which holds permissions to start on boot and to draw overlays on top of other activities.

It implements a simple interface for other programs:

```aidl
// IService.aidl
package org.koreader.aidl;

interface IService {
 	String status();
 	void color(int color);
 	void alpha(float alpha);
}
```

And a test application to, err, test.

![testing](https://user-images.githubusercontent.com/975883/72619384-68aa4900-393d-11ea-8ac4-a9261f522deb.gif)

As you can see this simulates warmth. Probably high values (above 5000k) and low values (below 1400k) are not interesting.
New to add a view to simulate extra dim steps, but that's easy.

The code used on the test is

```java
class ColorHelper {
    final static int NULL_COLOR = 0x00000000;
    private final HashMap<Integer, Integer> colors = new HashMap<>();

    ColorHelper() {
        init();
    }

    private void init() {
        // map between Kelvin and ARGB values,
        // following http://www.vendian.org/mncharity/dir3/blackbody

        colors.put(5400, 0xffffebdc);
        colors.put(5200, 0xffffe8d5);
        colors.put(5000, 0xffffe4ce);
        colors.put(4800, 0xffffe1c6);
        colors.put(4600, 0xffffddbe);
        colors.put(4400, 0xffffd9b6);
        colors.put(4200, 0xffffd5ad);
        colors.put(4000, 0xffffd1a3);
        colors.put(3800, 0xffffcc99);
        colors.put(3600, 0xffffc78f);
        colors.put(3400, 0xffffc184);
        colors.put(3200, 0xffffbb78);
        colors.put(3000, 0xffffb46b);
        colors.put(2800, 0xffffad5e);
        colors.put(2600, 0xffffa54f);
        colors.put(2400, 0xffff9d3f);
        colors.put(2200, 0xffff932c);
        colors.put(2000, 0xffff8912);
        colors.put(1800, 0xffff7e00);
        colors.put(1600, 0xffff7300);
        colors.put(1400, 0xffff6500);
        colors.put(1200, 0xffff5300);
        colors.put(1000, 0Xffff3800);
    }

    int getARGB(int kelvin) {
        if (colors.containsKey(kelvin)) {
            Integer value = colors.get(kelvin);
            if (value != null) {
                return value;
            } else {
                return NULL_COLOR;
            }
        } else {
            return NULL_COLOR;
        }
    }
}
```

This map can be put on the frontend so the call would be something like `android.setWarmth(0xffff5300)` or keep in the backend as a few steps and called with `android.setWarmthLevel(21)`

**Comment by Frenzie** [comment]
Yep, I think that pretty much looks like what you described above. ^_^ I think it looks small/simple enough not to go too fancy with it.

**Comment by pazos** [comment]
> Yep, I think that pretty much looks like what you described above

Good to know, my english is better than I thought :smile: 

> I think it looks small/simple enough not to go too fancy with it.

ok, will try to keep most of the stuff outside common/frontend code.

**Comment by pazos** [comment]
I've updated the sample to simulate what should look from the pov of KOReader. It looks better on the device than on this gif, which tends to overreact to step changes.

![stest](https://user-images.githubusercontent.com/975883/72909543-7b56c080-3d37-11ea-8aac-0d4bda96e933.gif)

If somebody wants to try on a device, here is a zip with both apk (the service and the test client).
[service-test.zip](https://github.com/koreader/koreader/files/4098182/service-test.zip)

In that case I would be interested in feedback about the dim/warmth steps (Did they look organic?, does the warmth color makes harder to read info?)

Note: if you installed both apks and, after testing, want to uninstall them you need to remove the service apk from android settings. It is called KO Service.

**Comment by farvardin** [comment]
@pazos I've tried your sample on my Android device (Pocophone F1), and while the service was correctly installed, the sample is not responding to the dim or warmth sliders.

**Comment by pazos** [comment]
> @pazos I've tried your sample on my Android device (Pocophone F1), and while the service was correctly installed, the sample is not responding to the dim or warmth sliders.

I don't know. Do you see "service available"?. Google Play Protect might want to disable the service as it was built against a legacy API (19).

**Comment by pazos** [comment]
Still not sure if it is a good idea to implement the overlay as a service. I did that because it is not possible to write an overlay over Native content and we're using that directly on most devices.

On a few devices we use a surfaceView on top of the window and there is possible to integrate the overlay within the app. BTW here's a good article about how surfaceviews work: https://medium.com/@zpcat/how-did-android-surfaceview-works-33afb7111b69

Probably the easiest way to implement all this is using surfaceView in all non-eink devices and put the overlay on top using `setZOrderOnTop(true)`.

**Comment by farvardin** [comment]
> 
> I don't know. Do you see "service available"?.

Yes, like on your screenshot. The sliders just don't change anything

**Comment by pazos** [comment]
@farvardin: Still no idea. Probably some "security feature" is preventing the overlay.

I will play a bit with native controls instead of the frontlight widget and ping you back if you want to test. It can help for #6332 and #5331 too. The only problem I see is that you can't preview changes on the program, just on the alert dialog.

![2020-07-01_16-05](https://user-images.githubusercontent.com/975883/86253826-52bfd600-bbb5-11ea-8e79-141c8db154f4.png)

**Comment by farvardin** [comment]
Looks perfect to me!

**Comment by Zeyadas** [comment]
Sorry about getting back to here but #8060 reminded me.
I downloaded and installed the service test file (both APKs) and worked fine, 
https://github.com/koreader/koreader/files/4098182/servicetest.zip 

![Screenshot_20210811-113642](https://user-images.githubusercontent.com/70109540/128998592-72f42dc7-f064-4847-a4ca-2a7ae4fff2aa.png)
But didn't find the warmth settings in the Koreader app, just the backlight settings. 
I'm using an android phone with the latest koreader version 7.2021 and 6.0.1 android version. And by the way Google play it totally disabled.

**Comment by pazos** [comment]
> But didn't find the warmth settings in the Koreader app, just the backlight settings.

That's because the feature **IS NOT** implemented yet. And probably I won't attempt to implement it ever. Too much edge cases in android to be worth the time :/. I would use a different app to tinker with screen emulated warmth, like RedMoon

**Comment by Zeyadas** [comment]
I'm using an app for that (twilight) it's perfect, but I thought it would be a good feature in koreader to be independent as a reading app full of features that could be used for reading ebooks.

**Comment by pazos** [comment]
> > Android solution and we would have a double warmth.
> 
> I don't know about the double warmth, but when I try to change the screen brightness in the android notification bar while koreader is running, an android massage shows that the screen brightness controlled by another app (koreader obviously) . That's on (android 11), and with Android (6.1) the screen brightness bar in the notification panel is simply not available.

Activities can override system wide brightness. That's what we do on lcd android devices. There's no api for warmth, so the issue mentioned by @zwim still stands: If we implement something within the app to manage warmth and the user has its own setting applied to all apps the mix of both will look terrible. There's no way we can know if users have a setting like that available or enabled on their devices.

If somebody decides to implement this FR I would suggest to leave it disabled by default and add a checkbox in screen  settings "lcd: simulate warmth". Then users that know what they do can enable it and have the controls in app and we don't get spammed with nasty interactions that can happen.

**Comment by strider72** [comment]
Why would you make it a system-type overlay? It's an app, just adjust the background color. Seems you're making this much too complicated.

If you want somethibg system level, I would leave it to the OS or at least a separate app that affects everything. This seems beyond the scope of KOReader

**Comment by strider72** [comment]
But overall, a good OS will handle this natively. Sadly, a lesser OS could be helped with KOReader having its own function to do this.

**Comment by pazos** [comment]
> Why would you make it a system-type overlay? It's an app, just adjust the background color. Seems you're making this much too complicated.

Lol. I guess you missed https://github.com/koreader/koreader/issues/5768#issuecomment-652341581

**Comment by strider72** [comment]
Maybe I did, but I'm not sure that answers my question.

You can specify the colors of things in an android app, correct?  So for "warm", just change the color from white to yellow/orange.  Why would you even *want* to overlay everything and turn the black orangeish as well?

**Comment by strider72** [comment]
Ah! Okay, that makes sense.  Thanks

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I believe that this unnecessarily introduces complexity into the code. Applications to add a colourative overlay to the screen have existed for many years, so most old devices that are acapable of operating KOReader are not exempt from this ability, and modern devices manage this innately anyway, so this would conflict with that.
