### ISSUE TITLE
display document metadata in the filemanager

### ISSUE THREAD

**Issue by bv217** [koreader/koreader#578]
I would like to display in filemanager instead of the filename of the information contained in the header. 
This option is present in most books, and much easier to find if the list includes several books of the same author, divided into volumes or books in the series.

**Comment by robert00s** [comment]
I prepared a patch that adds metadata information from the book file.
But now it works only with files that was before opened and have sdr catalog with metadata.
Do you know how to read metadata from a file that has not yet been opened? 
Is koreader has a method, which create sdr folder and create metadata file?

Long press on file (new File information button):
![file_information1](https://cloud.githubusercontent.com/assets/22982594/19721654/889d5a06-9b73-11e6-8c11-f6e06da412a0.png)

Select "File information"
![file_information2](https://cloud.githubusercontent.com/assets/22982594/19721662/8ecf038e-9b73-11e6-9714-ce12c1893257.png)

Long press on folder:
![file_information3](https://cloud.githubusercontent.com/assets/22982594/19721669/9306b50a-9b73-11e6-92bc-90f82d964551.png)

Long press of file without sdr folder:
![file_information4](https://cloud.githubusercontent.com/assets/22982594/19721671/96f461ee-9b73-11e6-9214-b5d75491a1ff.png)

**Comment by houqp** [comment]
@robert00s you can just open the document using `DocumentRegistry:openDocument(file)` if the document setting is not available. See: https://github.com/koreader/koreader/blob/master/frontend/apps/reader/readerui.lua#L370

Then you can access the meta data through `getProps` method.

**Comment by robert00s** [comment]
@houqp Thanks.
I also added "file information" option in the history window:

![history](https://cloud.githubusercontent.com/assets/22982594/19803360/8c52751e-9d08-11e6-8aef-9942e1523fba.png)

**Comment by AlanSP1** [comment]
Nice new options. :+1: 

We will need some form of manual, but I think this was already requested (even with me). But it is a good thing.

**Comment by houqp** [comment]
Thanks @robert00s ! I will take a look at the PR after work :)

**Comment by houqp** [comment]
Yeah, having an official manual would be nice. We can ship it with each koreader release and also host it on www.koreader.rocks.
