### ISSUE TITLE
Can not write android external SD card while downloading books from the cloud storage

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#5784]
* KOReader version: V2019.12
* Device: Hisense A5

#### Issue
Can not write android external SD card while downloading books from the cloud storage

#### Steps to reproduce
1. Try to download a book from cloud storage
2. Select any external sd card as the destination
3. It will fail with the message: Could not save to /storage/xxx/xxx.epub
4. If you choose the internal sd card as the destination, then all is ok without problem

**Comment by pazos** [comment]
Like #4872. Same unfixable underlying issue: there's **no filesystem write permission outside the primary storage**. It is mentioned at the bottom of https://www.mobileread.com/forums/showpost.php?p=3935915&postcount=1

Note that primary storage can be a sdcard if the user selected that as the main storage on android settings.

A workaround would be disable operations that require write permissions if the path is outside the sandbox. We already have `android.isPathInsideSandbox(path)` and a generic wrapper `isValidPath(path)` that can be used in these cases. It is actually used in android to [disable import on dirs outside the sandbox](https://github.com/koreader/koreader/blob/0599c440cc934c1dceb5a2fed4aebb02bf01823e/frontend/apps/filemanager/filemanager.lua#L565)

**Comment by clach04** [comment]
@kingo132 are you still seeing a message when this fails? Or does koreader exit without an error message?

**Comment by pazos** [comment]
@clach04: I'm afraid this is device/vendor dependant. The only reason for a crash here is an unhandled exception that crashes the entire java machine. Please get us a log to see what happens.

**Comment by clach04** [comment]
Thanks @pazos I got access to a machine where I could issue ADB :)

I attached an extract to #6636 (I can attach more if needed).

**Comment by pazos** [comment]
Thank you @clach04, the crash should be fixed with https://github.com/koreader/koreader/pull/6640. The underlying issue cannot be fixed. I'm closing this one.

Feel free to open other issues if you find other crashes related to RO filesystems (with logs, please :))
