### ISSUE TITLE
Please add Persian keyboard layout to koreader

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#5791]
hi
you add Arabic keyboard to Koreader in last Update.
please add Persian keyboard too if it is possible for you.
there is some different
For example Persian Keyboard has پ That is not in Arabic Keyboard
or Persian keyboard has ی instead of ي
if you need more details just say that
thank you

**Comment by Frenzie** [comment]
If the difference is small, I'd strongly recommend looking into modding the Arabic keyboard yourself! :-)

Also pinging @WaseemAlkurdi, who'd be able to understand the intricacies of the writing system better.

**Comment by WaseemAlkurdi** [comment]
@Monirzadeh 
Salaam alaykum!
Do you prefer to have a distinct keyboard for Farsi, or is simply adding the missing letters enough?
If you'd like a separate keyboard, then send me the list of the _names_ of the letters (with the letters themselves of course), as I don't speak the language.. I'd use that with a keyboard location map to create a Farsi keyboard.
The actual work (the work itself) should take about one day, hopefully.

**Comment by WaseemAlkurdi** [comment]
@Frenzie The difference isn't too significant. It's basically a re-shuffle of the keycaps, some missing ones inserted, and the variables renamed to reflect the different names of the letters.

**Comment by Monirzadeh** [comment]
@WaseemAlkurdi Thanks :heart: 
it's need a new keyboard
i work on that Chart (for now i have a list of all Unicode of them i work on add symbol too)
wheres should i send that?
i should Post that here?

**Comment by Frenzie** [comment]
I'd generally advise to post it here unless there seems to be a good reason not to. ;-)
