### ISSUE TITLE
Design improvements to KOReader?

### ISSUE THREAD

**Issue by WaseemAlkurdi** [koreader/koreader#5802]
KOReader's design is good, but it could use some subtle hints to look better on the eyes, couldn't it?
For example, the lines separating menu entries can be made a lighter shade instead of full-black, like how the stock OS for Kindle and other e-readers draws menus.
I've seen issue #2614 - and I quite frankly _hate_ the radical makeover in that mockup. (It later became _Plato_ for Kobo).
But I guess that the **harsh blacks everywhere** are annoying, _especially_ when compared to stock.
I'm going to do a mockup sometime soon.
What do you think?

**Comment by WaseemAlkurdi** [comment]
There's issue #5593 - great idea, only that it's concerned with the start page. My issue here is primarily about **"harsh blacks everywhere"**.

**Comment by poire-z** [comment]
> the lines separating menu entries can be made a lighter shade instead of full-black

But it's already gray and not black :|
You can try changing the COLOR_GRAY in:
https://github.com/koreader/koreader/blob/343eff312353b9501ad69f14f366313580f3c6fd/frontend/ui/widget/touchmenu.lua#L523-L528
for one of [the other defined grays](https://github.com/koreader/koreader-base/blob/26bb2a880350a67768da68bbc2872b185405e474/ffi/blitbuffer.lua#L1881-L1889):
```lua
-- some generic color values:
BB.COLOR_WHITE = Color8(0xFF)
BB.COLOR_GRAY_E = Color8(0xEE)
BB.COLOR_LIGHT_GRAY = Color8(0xCC)
BB.COLOR_GRAY = Color8(0xAA)
BB.COLOR_WEB_GRAY = Color8(0x99)
BB.COLOR_DARK_GRAY = Color8(0x88)
BB.COLOR_DIM_GRAY = Color8(0x55)
BB.COLOR_BLACK = Color8(0)
```

(But personally, I patch that same line from COLOR_GRAY to COLOR_BLACK - because on my GloHD, any gray stuff gets flashed when displayed or undisplayed, so there would be some disctracting animations when browsing menus, that I don't like at all - possibly some GloHD defect, as nobody except me ever talked about it :)

**Comment by Frenzie** [comment]
Are you using a Kindle of some sort given your message? On my H2O they're definitely a subtle gray and not a "harsh black." Do you use a device with low-DPI perhaps? Then the lines will be comparatively thicker and "harsher".

**Comment by Frenzie** [comment]
> possibly some GloHD defect, as nobody except me ever talked about it :)

It happens on m H2O, but I'd say it's not really noticeable unless you're paying attention to it.

**Comment by NiLuJe** [comment]
FWIW, it's definitely gray everywhere ^^.

* KOReader's entry separator in the FM: 0x88
* KOReader's button separator: 0xAA
* KOReader's menu border: 0x00

* Kindle's top menu separator: 0x99
* Kindle menu border: 0x52 (WTF, lab126, that's not in the eInk palette?)
* Kindle's menu separator: 0xAD (again, wtf).

(Reminder: 0x00 is black, 0xFF is white, stride between shades is 0x11).

**Comment by NiLuJe** [comment]
In any case, everything should be using a `COLOR_*` constant, as @poire-z explained, so it's fairly easy to try some things out ;).

**Comment by pazos** [comment]
For reference, the change was done in https://github.com/koreader/koreader/pull/2556. I 
never bothered by separators before but the thick grey line looks better than the previous versions IMO.

> KOReader's design is good, but it could use some subtle hints to look better on the eyes, couldn't it?

The user interface is like a Thinkpad: rough, robust and ready to do the job. Nothing against beautifying, but I like its current  ugliness / utility balance :smile:

**Comment by WaseemAlkurdi** [comment]
@poire-z
> But it's already gray and not black :|
> You can try changing the COLOR_GRAY

It _is_ gray, but not "gray enough" - it is definitely noticeable and _not_ subtle, at least to my (perhaps very odd) eyes.

> (But personally, I patch that same line from COLOR_GRAY to COLOR_BLACK - because on my GloHD, any gray stuff gets flashed when displayed or undisplayed, so there would be some disctracting animations when browsing menus, that I don't like at all - possibly some GloHD defect, as nobody except me ever talked about it :)

Is it an artifact of slow E Ink? The Kindle from which this picture is uploaded (my spare Kindle Touch, I've sold my present KT2 and black PW3, and bought a white PW3, which is in the mail now. But I digress). The Kindle Touch has a E Ink Pearl, and it is really slow ... that you can see menu elements sort of "fading" away.

@Frenzie
> Are you using a Kindle of some sort given your message?

Yeah, see above. I've only used Kindles with E Ink Pearl for KOReader (never had the chance to try KOReader on the black PW3, and I will try it on the white one as soon as it arrives.)

> On my H2O they're definitely a subtle gray and not a "harsh black." 

See the picture below from the Kindle Touch. The separator is definitely gray, but it isn't subtle at all, at least when compared with Kindle firmware.
And the font is _very_ thick as well. But that is should be easily fixed by replacing the font, right?
![IMG_20200131_181705](https://user-images.githubusercontent.com/15712695/73572485-9634dd80-4479-11ea-9af9-30a11ec4cec5.jpg)

> Do you use a device with low-DPI perhaps? Then the lines will be comparatively thicker and "harsher".

E Ink Pearl tops at 160 DPI. Perhaps that's it?

@NiLuJe 
I think I'll play with the values for the border color, until I find a balance.

Are the Kindle values you referred to defined by (or limited by) the sixteen shades of (gray) color of the display itself?

@pazos
> The user interface is like a Thinkpad: rough, robust and ready to do the job.

Ah, the old form vs. function debate! ;-P
ThinkPads are glorious road warrior machines, especially the older ones. Truly love them.
But not something you'd flash to make an impression on (non-techie) people ... (Not a _painful_ impression, which the ThinkPad excels at, if used "on" people! xD)
Personally, I'm a tiny bit biased towards HP's EliteBooks. They pay some attention to design. (But that's offset by a sacrifice in build quality, which is why my next convertible will be a ThinkPad. But at least EBs are _way_ better than the next disposable consumer model!)

**Comment by NiLuJe** [comment]
My Touch is flat, so more on that later, since I don't rightly recall how the stock UI looked back then ;).

That said, in order:

* You won't find slower than Pearl, yeah, so it will be markedly worse on that front.

* Your picture *sure* looks darker than the H2O sitting right next to my keyboard on your picture. More on that later when I can boot mine ;).

* As @Frenzie said, the DPI should only affect the scaling, which might yield slightly thicker elements, but that wouldn't affect the color, only how it's perceived.

* It'll also affect font rendering, to a certain extent, where you might be noticing slightly fuzzier rendering, which can masquerade as thickness ;).

* Yep, that's the eInk palette: 0x00 to 0xFF, with a stride of 0x11 yields 16 shades of gray (i.e., 0x11, 0x22, 0x33, ... you get the idea ;)).

**Comment by Frenzie** [comment]
> E Ink Pearl tops at 160 DPI. Perhaps that's it?

Yes, that should be the major difference in perceptive quality. That's basically twice as thick as "intended." Most of the "hash blacks" you speak of are intended to be about half that thickness. Although it does look oddly dark on your picture on top of that but that doesn't necessarily mean anything.

Fonts will also typically seem thicker on lower DPI.

Btw, how the stock OS for Kindle draws things means nothing to me. ;-)

**Comment by NiLuJe** [comment]
Okay, it's alive again :).

First impression: the stock UI was *much* darker than it is now ;). And not only because the top status bar is solid black ^^.

But, back to KOReader ;).

It's indeed slightly fuzzier, but the main issue is actually that it hosts like crazy, which compounds everything we've mentioned:

* Ghosting on thin gray lines makes ugly fuzzy darker lines.
* Ghosting on fuzzyish text makes ugly fuzzy darker text ^^.

But if you flash, stuff is actually rendering as expected (and the lines aren't too thick).

**Comment by NiLuJe** [comment]
You could try the following patch, but it shouldn't yield any significant changes (in fact, AUTO should be making roughly the exact same choices we do).

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index 06b161a..fecb426 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -533,6 +533,8 @@ function framebuffer:init()
         self.waveform_flashnight = self.waveform_night
         self.night_is_reagl = false
 
+        -- Older devices using a Pearl screen, don't try anything too fancy
+        local isPearl = false
         -- New devices are REAGL-aware, default to REAGL
         local isREAGL = true
 
@@ -552,8 +554,10 @@ function framebuffer:init()
         elseif self.device.model == "Kindle4" then
             isREAGL = false
         elseif self.device.model == "KindleTouch" then
+            isPearl = true
             isREAGL = false
         elseif self.device.model == "KindlePaperWhite" then
+            isPearl = true
             isREAGL = false
         end
 
@@ -583,6 +587,13 @@ function framebuffer:init()
             self.waveform_partial = C.WAVEFORM_MODE_GL16_FAST -- NOTE: Depending on FW, might instead be AUTO w/ hist_gray_waveform_mode set to GL16_FAST
         end
 
+        -- NOTE: On older Pearl screen, don't try anything too fancy. The stock UI mostly relies on AUTO doing the right thing.
+        if isPearl then
+                self.waveform_ui = C.WAVEFORM_MODE_AUTO
+                self.waveform_flashui = C.WAVEFORM_MODE_GC16_FAST
+                self.waveform_partial = C.WAVEFORM_MODE_AUTO
+        end
+
         -- NOTE: Devices on the Rex platform essentially use the same driver as the Zelda platform, they're just passing a slightly smaller mxcfb_update_data struct
         if isZelda or isRex then
             self.device.canHWDither = yes
```

**Comment by WaseemAlkurdi** [comment]
@NiLuJe 
Sorry for the delay - been busy again! :-(
I tried this. No difference at all, as far as my eyes can see.
However, I thought I might replace the font with a lighter variant (Noto itself has a light variant, or perhaps the stock Kindle font if I can find that anywhere)

**Comment by poire-z** [comment]
Closing, as the blackness of gray is really suggestive :)
May be it has improved a little with SVG icons and some thinner borders?
