### ISSUE TITLE
Wrong translations 

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#5806]
* KOReader version: v2020.01
* Device: Tolino Epos 2

#### Issue

The status bar has two new options: „Book title“ and „Current chapter“.
In the german translation, these are translated with „Buchstatus“ (book status) and „Nächstes Kapitel“ (next chapter), that‘s wrong.
When I look at the translation at Weblate, the strings are correct.
The same problem exists in another language: in French, these two options are also incorrectly translated: „État du livre“ and „Chapitre suivant“.

The assignment of the translated strings is probably incorrect.

**Comment by Frenzie** [comment]
This is in the translated string,
```
#: frontend/apps/reader/modules/readerfooter.lua:667
#, fuzzy
msgid "Book title"
msgstr "Buchstatus"
```

That was fixed a few days after the release, hence why it's correct on Weblate: https://github.com/koreader/koreader-translations/commit/a6f728f01f5c55a7f79049db79929077c6814058

**Comment by Frenzie** [comment]
But perhaps I should prevent fuzzy strings from being displayed… :thinking:
