### ISSUE TITLE
[bug?]  In page foot notes are set up but in two separate epub files foot notes are not rendered

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5812]
* KOReader version: latest stable
* Device: paperwhite 4

I am reading "The Shallows What the Internet Is" and it has a lot of footnotes, like the last book I read "Procrastination Equation" anyway even though I have in page footnotes set up all i seem to see is the number under/above the normal text.  When I click it, I go to the footnotes at the end of the book.  

I remember footnotes once worked, so I'm not sure if it's a book format specific issue or perhaps a bug.  I'd post the books in question but don't want to violate any copyright issues.

**Comment by Frenzie** [comment]
It only works if they have a class like "note". If you select the text around a footnote link and "view HTML" you could post a screenshot of that.

**Comment by NiLuJe** [comment]
We're going to need to see the book's code, which is where @jackiew1's excellent [ScrambleEbook](https://www.mobileread.com/forums/showthread.php?t=267998) plugin comes in ;).

**Comment by NiLuJe** [comment]
Oh, or, yeah, I guess @poire-z's fancy debugging options could do the trick, too ;).

**Comment by Frenzie** [comment]
That ScrambleEbook plugin would probably slightly ease things though.

**Comment by poire-z** [comment]
Just select text around the footnote link, and View HTML:
<kbd>![image](https://user-images.githubusercontent.com/24273478/73693445-88c85f00-46d6-11ea-9c1e-2828ba713937.png)</kbd>

Same around the expected target, grabbing bits from the previous and next footnotes text, and View HTML:
<kbd>![image](https://user-images.githubusercontent.com/24273478/73693524-b1e8ef80-46d6-11ea-813b-b214b67e56ad.png)</kbd>

Comparing these for a book where they work vs those for a book where they don't work, should help you see why (unless there's a bug, if they are really similar :).
Post the 4 screenshots (from a book that work and one that doesn't) here if you need help.

**Comment by arooni** [comment]
[The Shallows - Nicholas Carr_scrambled.epub.zip](https://github.com/koreader/koreader/files/4156598/The.Shallows.-.Nicholas.Carr_scrambled.epub.zip)

I think it's the issue of not having the word "Note" in the class, I see some "calibre16" as class for one example.  You can see the scrambled file.  

So is there anyway to get footnotes working in general across different epub files?  Or not so much

**Comment by poire-z** [comment]
> is there anyway to get footnotes working in general across different epub files

If the publisher has not done its work and has not set generic attributes or classnames to its footnotes, we can't do it.
But _you_ can.

Hold on the various in-page foonotes styletweaks to get more info and understand how each work.

<kbd>![image](https://user-images.githubusercontent.com/24273478/73796534-b6cca280-47ad-11ea-8020-18fa0b2de25f.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/73796415-68b79f00-47ad-11ea-94d1-8d0f4f2f786c.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/73796640-0ad78700-47ae-11ea-8291-d515bf84a622.png)</kbd>

Indeed, there is none of the "classic" classnames.
But there are others.
I had a try at calibre16, calibre28... but you need to use calibre22: the block container that contains the `id=` and the footnote text.

So, you need to create a user styletweak (see https://github.com/koreader/koreader/pull/3944#issuecomment-389069259) that contains:
```css
.calibre22 { -cr-hint: footnote-inpage; font-size: 80%; }
```
and you'll have your footnotes.
Or, if you want to get rid of the left margin:
```css
.calibre22 { -cr-hint: footnote-inpage; font-size: 80%; text-indent: 0; margin-left: 0 !important}
```

**Comment by arooni** [comment]
thanks for breaking that down @poire-z ;  just out of curiosity; is there anyway to add this setting via ssh access to my koreader folder?  i have found that typing on the kindle paperwhite is a bit _challenging_ :P

**Comment by Frenzie** [comment]
Well of course, just stick it in `koreader/styletweaks/whatever-you-want-to-call-it.css`. ;-)

**Comment by arooni** [comment]
you guys have really thought of everything haven't you?  :heart:
