### ISSUE TITLE
Enable SSH server on Android

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#5817]
* KOReader version: 2020.1
* Device: Boyue Likebook Alita

#### Issue
No SSH server on Android KOReader. This would be nice to have. Any reason it’s not supported?

#### Steps to reproduce
N/A

**Comment by pazos** [comment]
> Any reason it’s not supported?

There are a bunch of alternative apks focusing on this. They will do a better job for android devices. Dropbear just makes sense *inside* koreader if the device has no simple means to run other apps.

My favourite is Termux, but that's a lot more than a standalone ssh server. If you need just one feature you can use https://f-droid.org/en/packages/org.galexander.sshd/

 [NIH](https://en.wikipedia.org/wiki/Not_invented_here) aside, there are some specific implementation issues that can be workarounded. Sadly workarounds require new permissions (start a service on the foreground, run at boot...) that are waay out of scope of the application. 

These two are, IMO, good reasons to not implement it :smiley:

**Comment by NiLuJe** [comment]
I'm already *extremely* not a fan of having it for other platforms, because it's a giant PITA to maintain.

**Comment by Frenzie** [comment]
Agreed, on embedded platforms I have some doubts but there it solves a problem that simply doesn't exist on Android. I'll close the issue. ;-)
