### ISSUE TITLE
Cervantes (and probably others) crash on latest nightly

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5822]
Updated from 2019.12 to latest nightly. OTA update went without problems but the program is unable to start.

Log:

```
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
FB: computed size: 6782976
FB: id           : mxc_epdc_fb
FB: smem_len     : 6782976
FB: line_length  : 2944
FB: xres         : 1448
FB: xres_virtual : 1472
FB: yres         : 1072
FB: yres_virtual : 2304
FB: bpp          : 16
./luajit: ./ffi/framebuffer_mxcfb.lua:707: attempt to call method 'isRemarkable' (a nil value)
stack traceback:
	./ffi/framebuffer_mxcfb.lua:707: in function 'init'
	./ffi/framebuffer.lua:70: in function 'new'
	frontend/device/cervantes/device.lua:155: in function 'init'
	frontend/device.lua:49: in main chunk
	[C]: in function 'require'
	./reader.lua:119: in main chunk
	[C]: at 0x00013f05
```

Probably unnoticed because both Kobo, Kindle and Pocketbook went first than remarkable and just sony & cervantes go after it.

**Comment by pazos** [comment]
The workaround is to add `isRemarkable = no,` to `local Cervantes = Generic:new {` until the frontend code of the remarkable will be merged.

**Comment by NiLuJe** [comment]
Might be worth hotfixing' in the meantime wiht just adding the usual `isRemarkable = no,` to frontend/device/generic/device.lua?

**Comment by Frenzie** [comment]
@NiLuJe Is there any reason to? I haven't looked at the PR in question this past week but @pazos approved it, so it should be good enough to merge. I can take another look at it tonight, but if any of you beat me to it… ;-)

**Comment by pazos** [comment]
Yeah, hopefully this regresion won't affect too much users. The solution if someone faces it is just:

- force a poweroff
- on booting, while the dots appear in the screen, press the home button. You'll see a [usb/RJ45 image](https://github.com/pazos/cervantes-safemode/blob/master/images/usbnet.png).
- setup your host as 192.168.4.2/24 and telnet to 192.168.4.1. 
- use `vi` to edit the file /mnt/private/koreader/device/cervantes/device.lua to append the line on my last post.
- make sure it works by running koreader from telnet with `/mnt/private/koreader/koreader.sh`. If everything works just exit KO and press the home button again. This will exit telnet and resume normal booting.

But IMO we don't need a hotfix if we're going to merge the remarkable PR in a couple of days.

**Comment by NiLuJe** [comment]
@Frenzie: Oh, err, good point. I knew I'd forgotten something :D.

I'll take a look at it and push it through ;).
