### ISSUE TITLE
Can't Open with from Google file manager

### ISSUE THREAD

**Issue by ocra98** [koreader/koreader#5825]
* KOReader version: 2020.01
* Device: like book mars t80d android 6.0.1

#### Issue
Cant open file pdf from Google file manager. The KOReader app just pops up and does nothing 
Not work with Google file manager, but work with MI manager.

**Comment by pazos** [comment]
Yeah, it is expected.

See #4441 as the original issue: there's no way to open content without doing a hard copy.
And https://github.com/koreader/android-luajit-launcher/pull/208 as a workaround that seems to work for most file providers. Google FM is not one of them, it seems.

You can read https://www.mobileread.com/forums/showthread.php?t=326177 too, for more info.

**Comment by pazos** [comment]
I'm closing this issue. Patches to workaround any specific filemanager are welcome.
