### ISSUE TITLE
Redirects not supported in opds downloads

### ISSUE THREAD

**Issue by ptrm** [koreader/koreader#5831]
* KOReader version: v2020.01-20-g67627_2020-02-08
* Device: Kobo Forma

####

The redirects when downloading a book from OPDS catalog through search (#5823) might not be supported. Or are supported, but the second download is not allowed to overwrite?

As for the overwrite question popup present in the screenshots, the case when the epub file had not existed when downloading also rendered the same results.

#### Steps to reproduce

1. Search a book in Gutenberg project.
2. Try to download (tried on epubs).
3. There will be a download error message, though the document will be available with "302 Found" title and redirection message and link inside.

![20200208_120458](https://user-images.githubusercontent.com/366258/74084421-4bb1f300-4a6f-11ea-8fd4-8acdc9bb22e4.jpg)
![20200208_120449](https://user-images.githubusercontent.com/366258/74084420-49e82f80-4a6f-11ea-9f47-d43104e41703.jpg)

##### `crash.log` (if applicable)

https://gist.github.com/acd2d82c20e640de61cb5705b5bcde89 (did not filter the lots of touch/ui events)

**Comment by poire-z** [comment]
Hopefully fixed by #6334 . Re-open if not.
