### ISSUE TITLE
Register Progress Sync

### ISSUE THREAD

**Issue by niveKKumar** [koreader/koreader#5832]
* KOReader version: latest stable 2020.01
* Device: Kindle voyage

#### Issue
I am not able to register a new account for syncing the progress.

#### Steps to reproduce
Open book, open progress sync add-on and press register

##### `crash.log` (if applicable)
Unknown server error

**Comment by pazos** [comment]
Quite obvious but try a name and password without spaces and with common symbols [a-z] [A-Z] [0-9]

**Comment by NiLuJe** [comment]
Similar to https://github.com/koreader/koreader-sync-server/issues/10 maybe?

**Comment by Frenzie** [comment]
> I'll add a simple check in the KOReader frontend.

Wasn't me who said that, no sirree… >_>

**Comment by pazos** [comment]
@niveKKumar: more info, please

**Comment by niveKKumar** [comment]
Registering works, what I thought was that pressing register will open new window where you can register. Filling the textfields empty will result into unknown server issue. Adding a message like "Fill in your informations to register" would clarify that information have to be filled into current textfields. Hope I could help
