### ISSUE TITLE
[Request] Make Top Bar (Header) customizable

### ISSUE THREAD

**Issue by radzix88** [koreader/koreader#5848]
Is it a chance to implement top bar customization (which activates where "Progress Bar is set to "full") like bottom bar? I'd like to add/remove indicators (like time, battery in percent etc.) in that bar.
This is the only thing that is missing for me. Besides KOreader is perfect.

![screen](https://user-images.githubusercontent.com/47605609/74247129-e0258b00-4ce5-11ea-9e90-f546225fbe5c.png)

**Comment by poire-z** [comment]
That top status bar is not managed by KOReader, but by crengine (the engine thats renders EPUB files).
You can tweak a bit of what it will show/not show by editing `koreader/data/cr3.ini`, these bits should apply to it:
```
crengine.page.header.chapter.marks=1
crengine.page.header.font.color=0xFF000000
crengine.page.header.font.face=Noto Sans
crengine.page.header.font.size=22

window.status.battery=1
window.status.battery.percent=0
window.status.clock=0
window.status.line=0
window.status.pos.page.count=1
window.status.pos.page.number=1
window.status.pos.percent=0
window.status.title=1
```

**Comment by radzix88** [comment]
It works, thank you! One issue which I noticed is that

crengine.page.header.chapter.marks=1 

actually not marks chapters but files build in *.epub file. If it does mark chapters should be exactly the same as bottom progressbar. In my opinion this should be set to 0 as default.


![scr2](https://user-images.githubusercontent.com/47605609/74263315-d52b2480-4cfe-11ea-8d31-43560457119e.png)


![scr3](https://user-images.githubusercontent.com/47605609/74263451-2509eb80-4cff-11ea-8523-f6eac828e799.png)

**Comment by poire-z** [comment]
Indeed: https://github.com/koreader/crengine/blob/76a2f162860c2c059f946b69728931611ea73c12/crengine/src/lvdocview.cpp#L1448-L1461
So, it uses the DocFragment/EPUB files, some kind of top level TOC.
While in KOReader, we use the lower levels TOC items, https://github.com/koreader/koreader/issues/5500#issuecomment-543201699 for the bottom bar, and another one for the SkimTo widget.

You're the first one noticing that :) So, I guess top bar users have been fine with what it shows, so it would be a bit sad to remove ~~the chapter marks~~ these marks. No one promised they would be the same in the top and in the bottom :)
(May be one day, the top bar will be managed and drawn by KOReader iteself.)

**Comment by poire-z** [comment]
With #6236 and this morning nightly, the top progress bar should have the same ticks as the bottom progress bar.
