### ISSUE TITLE
Pocketbook: 2020.02 crash at startup

### ISSUE THREAD

**Issue by mikkelnl** [koreader/koreader#5866]
* KOReader version: 2020.02
* Device: Pocketbook Touch HD 3

#### Issue
.02 crashes at startup. Might be the same issue as #5861 (but 5861 mentions it uses v2020.01).

#### Steps to reproduce
Launch KOReader

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/4204382/crash.log)

**Comment by Frenzie** [comment]
I added a warning to the release, thanks for reporting.

**Comment by NiLuJe** [comment]
You're welcome to chime in to help with the tests in #5861 ;).
