### ISSUE TITLE
koreader crash when log into Yinxiang Biji/Evernote

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#5882]
* KOReader version: v2020.02
* Device: Hisense A5

#### Issue
When I try to login evernote in koreader in my hisense, it crash.

#### Steps to reproduce
1. Open koreader
2. Login evernote plugin, fill the account and passowrd
3. Click Login, then koreader crash

##### `crash.log` (if applicable)
```
02-19 11:38:35.548  1299  1347 I ActivityManager: Start proc 15339:com.automattic.simplenote/u0a147 for broadcast com.automattic.simplenote/.NoteWidget
02-19 11:38:53.134  1299  7125 D ActivityManager: kill app.info.packageName=com.moji.hmct minOomAdj=500 packageName=com.moji.hmct
02-19 11:38:53.134  1299  7125 I ActivityManager: Killing 14320:com.moji.hmct/u0a123 (adj 904): kill background
02-19 11:39:12.937 15272 15291 E KOReader: error: [string "dl.lua"]:41: error opening /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so: dlopen failed: library "liblualongnumber.so" not found
02-19 11:39:12.939 15272 15291 E KOReader: [NativeThread]: failed to run script: error loading module 'libluabpack' from file 'plugins/evernote.koplugin/lib/libluabpack.so':
02-19 11:39:12.939 15272 15291 E KOReader: 	dlopen failed: library "liblualongnumber.so" not found
02-19 11:39:12.939 15272 15291 E KOReader: [NativeThread]: Stopping due to previous errors
02-19 11:39:13.083  1299  2899 I ActivityManager: Process org.koreader.launcher (pid 15272) has died: fore TOP 
02-19 11:39:13.139  1299  1379 W ActivityManager: setHasOverlayUi called on unknown pid: 15272
```

**Comment by pazos** [comment]
@kingo132: can you reproduce on your Clara HD? Are you logging in the chinese version of evernote?. Thanks!

**Comment by kingo132** [comment]
> @kingo132: can you reproduce on your Clara HD? Are you logging in the chinese version of evernote?. Thanks!

Yes, I logged into chinese version of evernote.

**Comment by pazos** [comment]
@kingo132: And I'm assuming you have no problem to log on other (non-android) devices.

You can try with this:

```lua
local android = require("android")
android.dl.library_path = android.dl.library_path .. ":" .. android.dir .. "/plugins/evernote.koplugin/libs"
```

Copy this on Notepad++ or any other good editor and save it with the name `patch.lua`. Then copy it to your device with `adb push patch.lua /sdcard/koreader`

Exit the program and start it again. Try to log in Yinxiang Biji again. Hopefully dlopen will be able to find the shared library this time.

**Comment by kingo132** [comment]
> @kingo132: And I'm assuming you have no problem to log on other (non-android) devices.
> 
> You can try with this:
> 
> ```lua
> local android = require("android")
> android.dl.library_path = android.dl.library_path .. ":" .. android.dir .. "/plugins/evernote.koplugin/libs"
> ```
> 
> Copy this on Notepad++ or any other good editor and save it with the name `patch.lua`. Then copy it to your device with `adb push patch.lua /sdcard/koreader`
> 
> Exit the program and start it again. Try to log in Yinxiang Biji again. Hopefully dlopen will be able to find the shared library this time.

I followed your instruction. However it still crash with these log

02-22 18:08:01.175 10213 10232 E KOReader: error: [string "dl.lua"]:41: error opening /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so: dlopen failed: library "liblualongnumber.so" not found
02-22 18:08:01.177 10213 10232 E KOReader: [NativeThread]: failed to run script: error loading module 'libluabpack' from file 'plugins/evernote.koplugin/lib/libluabpack.so':
02-22 18:08:01.177 10213 10232 E KOReader: 	dlopen failed: library "liblualongnumber.so" not found
02-22 18:08:01.177 10213 10232 E KOReader: [NativeThread]: Stopping due to previous errors
02-22 18:08:01.311  1299  2026 I ActivityManager: Process org.koreader.launcher (pid 10213) has died: fore TOP 
02-22 18:08:01.379  1299  1379 W ActivityManager: setHasOverlayUi called on unknown pid: 10213

**Comment by kingo132** [comment]
I found some clues. While the crash log tell can not found file: /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so. I checked the directory /data/user/0/org.koreader.launcher/files/, it is totally empty! Maybe The koreader app is trying to find files in the wrong directory. There is no file in /data/user/0/org.koreader.launcher/files/ at all!!!

**Comment by kingo132** [comment]
Also, I tried to log in the international version of EverNote, it crashes too.

**Comment by pazos** [comment]
> I found some clues. While the crash log tell can not found file: /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so. I checked the directory /data/user/0/org.koreader.launcher/files/, it is totally empty! Maybe The koreader app is trying to find files in the wrong directory.

/data/user/0 is a symbolic link to /data/data on multiuser system (anything higher than 4.x), where 0 is the user id for the main account of the phone (called owner sometimes). This path is resolved automatically. If `/data/user/$(userId)/org.koreader.launcher/files` is empty the program wouldn't start at all. Plus `/data` is not readable unless you're root and the only way to write to internal dirs is via the AssetsManager.

> Also, I tried to log in the international version of EverNote, it crashes too.

Good to know, thanks!. Now the other thing that's still unanswered is: did both evernote and Yinxiang Biji work fine on other (non android) devices?

**Comment by pazos** [comment]
Also, my previous suggestion had a typo at the end. The dlopen library path should be

```
local android = require("android")
android.dl.library_path = android.dl.library_path .. ":" .. android.dir .. "/plugins/evernote.koplugin/lib"
```

**Comment by NiLuJe** [comment]
@pazos: There are various open issues related to the Evernote plugin, but none quite like this one, I think ;).

**Comment by kingo132** [comment]
> > I found some clues. While the crash log tell can not found file: /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so. I checked the directory /data/user/0/org.koreader.launcher/files/, it is totally empty! Maybe The koreader app is trying to find files in the wrong directory.
> 
> /data/user/0 is a symbolic link to /data/data on multiuser system (anything higher than 4.x), where 0 is the user id for the main account of the phone (called owner sometimes). This path is resolved automatically. If `/data/user/$(userId)/org.koreader.launcher/files` is empty the program wouldn't start at all. Plus `/data` is not readable unless you're root and the only way to write to internal dirs is via the AssetsManager.
> 
> > Also, I tried to log in the international version of EverNote, it crashes too.
> 
> Good to know, thanks!. Now the other thing that's still unanswered is: did both evernote and Yinxiang Biji work fine on other (non android) devices?

Yes, they both work fine on my kobo clara hd with koreader.

And sorry, I mistake the path. What I mean empty is the path /sdcard/Android/data/com.kobobooks.android/files. It didn't have the permission to show the directory /data/user/0/org.koreader.launcher/files/.

HLTE202N:/ $ ls /data/user/0/org.koreader.launcher/files/
ls: /data/user/0/org.koreader.launcher/files/: Permission denied

And after I upgrade koreader to 202003, this directory automatically added two directories.

HLTE202N:/ $ ls /sdcard/Android/data/com.kobobooks.android/files
6a4354623ca86ca81f87ec9e54cad22c packages

**Comment by kingo132** [comment]
> ```lua
> library_path
> ```

I used this script but still, it crashes.
However, I find some error messages that maybe indicate some problems of the so file liblualongnumber.so. The logcat tells the warning: unused DT entry: DT_RPATH (type 0xf arg 0x281) (ignoring)

03-11 23:47:16.794 20059 20104 V dlopen  : sys_dlopen - loading library /data/user/0/org.koreader.launcher/files/libs/liblualongnumber.so
03-11 23:47:16.795   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:16.795 20059 20104 W linker  : Warning: "/data/data/org.koreader.launcher/files/libs/liblualongnumber.so" unused DT entry: DT_RPATH (type 0xf arg 0x281) (ignoring)
03-11 23:47:16.796 20059 20104 V dlopen  :          dl.dlopen - opening needed libc.so for /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so
03-11 23:47:16.797 20059 20104 V dlopen  : dl.dlopen - library lname detected /system/lib/libc.so
03-11 23:47:16.799 20059 20104 V dlopen  : sys_dlopen - loading library /system/lib/libc.so
03-11 23:47:16.800 20059 20104 V dlopen  : sys_dlopen - loading library /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so
03-11 23:47:16.802 20059 20104 E KOReader: error: [string "dl.lua"]:41: error opening /data/user/0/org.koreader.launcher/files/plugins/evernote.koplugin/lib/libluabpack.so: dlopen failed: library "liblualongnumber.so" not found
03-11 23:47:16.804 20059 20104 E KOReader: [NativeThread]: failed to run script: error loading module 'libluabpack' from file 'plugins/evernote.koplugin/lib/libluabpack.so':
03-11 23:47:16.804 20059 20104 E KOReader: 	dlopen failed: library "liblualongnumber.so" not found
03-11 23:47:16.804 20059 20104 E KOReader: [NativeThread]: Stopping due to previous errors
03-11 23:47:16.807   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:16.810  1135 14125 D PowerManagerService: acquireWakeLockInternal: lock=163444849, flags=0x1, tag="*launch*", ws=WorkSource{10154}, uid=1000, pid=1135
03-11 23:47:16.818   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:16.901   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:16.906  2647  2647 V HmctLimitAppMonitor: limitAppMonitor: isScreenOn=true
03-11 23:47:16.913   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:16.915  2557  2586 D ThemeUtil:  checkIcon, path3 = /storage/emulated/0/.hmcttheme/com.hmct.theme/icons/org.koreader.launcher.png
03-11 23:47:16.921  2557  2586 D ThemeUtil:  getDrawableByZipFile, bitmap = true
03-11 23:47:16.924   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:16.997   551   899 E libc    : Access denied finding property "sys.sysctl.GC_New_Refresh"
03-11 23:47:17.002   551   899 I SDM     : HWCDisplay::EinkSwTconThreadHandler: frame is end, loop_num=39
03-11 23:47:17.053   551   900 I SDM     : HWCDisplay::EpdUpdateThreadHandler: queue is empty
