### ISSUE TITLE
Koreader doesn't display codepoints of the chars 139 and 155 in dictionary.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#5888]
Still checking the html-rendering of mupdf, I stumbled over another rendering problem. I think it is not a font problem nor a missing glyph problem.

![Screenshot from 2020-02-20 21-32-44](https://user-images.githubusercontent.com/5269101/74976168-88df9300-5428-11ea-9aa4-aca112f84fa5.png)
Both on Linux desktop and Kobo H2O v.2020.02

However, on Goldendict on the Linux desktop it displays well:
![Screenshot from 2020-02-20 21-35-07](https://user-images.githubusercontent.com/5269101/74976491-1b803200-5429-11ea-9f19-d8237906fe1b.png)

The output from sdcv (after prettifying) is:
```html
[{"dict": "Duden 7.Aufl. 2011","word":"ab","definition":"\n<blockquote>
    <blockquote><sup>1&#8204;</sup><b><b>a</b></b><b>b</b><b> </b>
        <blockquote>&#139;Pr&#xE4;p. mit Dativ&#155; [mhd. ab(e), ahd. ab(a), verw. mit griech. ap&#xF3; = von, ab]: </blockquote><b>1.</b> (BES. KAUFMANNSSPR., VERKEHRSW.) von ... an, von ... weg: <i>[frei] ab Werk; </i> <i>ab [unserem] Lager; </i> <i>wir fliegen ab allen deutschen Flugh&#xE4;fen. </i> <b>2.</b> &#139;bei artikellosen Substantiven mit adj. Attribut gelegtl. auch mit Akk.&#155; (ZEITLICH) von ... an: <i>ab dem 35. Lebensjahr; </i> <i>Jugendliche ab 18 Jahren/(AUCH:) Jahre; </i> <i>ab kommendem/(AUCH:) kommenden Montag; </i> <i>ab Mai; </i> <i>ab 1990; </i> <i>ab heute [Nacht]; </i> <i>ab morgen wird gefastet. </i> <b>3.</b> &#139;bei artikellosen Substantiven mit adj. Attribut gelegtl. auch mit Akk.&#155; bei einer Reihenfolge, Rangfolge o.&#xA0;&#xC4;.; von ... an: <i>die Dienstgrade ab Unteroffizier; </i> <i>ab n&#xE4;chster/(AUCH:) n&#xE4;chste Ausgabe.</i>
    </blockquote>
</blockquote>\n<blockquote>
    <blockquote><sub> </sub><sup> </sup><sup>2&#8204;</sup><b><b>a</b></b><b>b</b><b> </b>&#139;Adv.&#155; [<span><b></b></span>&#xA0;<sup><span>1</span></sup>ab]: <b>1.</b> weg, fort, entfernt: <i>gleich hinter der Kreuzung links ab; </i> <i>nicht sehr weit ab vom Weg liegen; </i> <i>die H&#xFC;tte soll weit von jeder menschlichen Behausung ab sein; </i> <i>zwei Kilometer ab [von dieser Stelle]; </i> (VERKEHRSW.:) <i>Darmstadt ab 7:30; </i> <i>Bayrischer Bahnhof ab, ab Bayrischer Bahnhof; </i> <i>(oft in Aufforderungen:) los, ab ins Bett!; </i> <i>(als B&#xFC;hnenanweisung:) ab (geht ab, soll abgehen); </i> <sup>*</sup><b>ab trim</b><u>o</u><b>/tr&#xFC;m</b><u>o</u><b> </b>(LANDSCH.; weg, ab; verschwinde!; H.&#xA0;u.) <b>2.</b> <b>a)</b> herunter, hinunter, nieder (gew&#xF6;hnlich in milit&#xE4;r. Kommandos): <i>Gewehr ab!; </i> <i>Helm ab zum Gebet!; </i> <b>b)</b> losgel&#xF6;st, abgetrennt, abgegangen: <i>der Knopf wird bald ab sein; </i> <i>die Farbe ist fast ganz ab. </i> <b>3.</b> <sup>*</sup><b>ab und zu </b>(gelegentlich; von Zeit zu Zeit. VERALTEND; [in Bezug auf eine Bewegung] weg u. wieder herbei; aus u. ein: <i>die Bedienung ging ab und zu); </i> <sup>*</sup><b>ab und an </b>(BES. NORDD.; gelegentlich; von Zeit zu Zeit: <i>er kommt ab und an mal vorbei).</i> </blockquote>
</blockquote>"}]
```

I've changed them to &#8B; and &#9B and the displays remained the same. 

However, when I substituted them with their characters they did display.
```perl
s~&#139;~‹~sg;
s~&#155;~›~sg;
```
![Screenshot from 2020-02-20 21-56-32](https://user-images.githubusercontent.com/5269101/74978078-32745380-542c-11ea-8393-b31b97107a7a.png)

**Comment by NiLuJe** [comment]
I have no idea how MuPDF handle HTML entities parsing, but since it's in the Control block, it'd be a perfectly sane decision to refuse to render those.

**Comment by NiLuJe** [comment]
i.e., why isn't this U+2039 & friends instead?

**Comment by Markismus** [comment]
Your saying that some chararcter codepoints are in the control block and although they get a glyph on the desktop, they are blocked in mupdf. They are mapped in another range, though?

**Comment by Markismus** [comment]
Yep, I stumbled right into something obscure, didn't I. :)

**Comment by poire-z** [comment]
Might depend on the page encoding.
In UTF-8, they map to the control block.
In [CP1252](https://en.wikipedia.org/wiki/Windows-1252) (Windows's latin1 extended), 139 = 0x8B is indeed that single left-pointing angle quotation mark.
So, I guess your dict expects the renderer to know its content is cp1252. Dunno if that is advertized somewhere in the .ifo, the content - or if it's assumed with sametypesequence=x (or whatever you're testing with :)

**Comment by NiLuJe** [comment]
@poire-z: Ha, nice! That indeed makes much more sense :).

**Comment by Markismus** [comment]
Ah, so what does that mean for those &#xXX;, such as &#xE4;? They seem to render fine. Are the codepoints in hex independent or less dependent on page encoding?

**Comment by Frenzie** [comment]
ä is basic ASCII, isn't it? Basic ASCII should be roughly the same in both utf-8 and cp1252.

**Comment by poire-z** [comment]
> ä is basic ASCII, isn't it?

Nope, ASCII stops at 127 and doesn't have these accentuated àéçùô.

> so what does that mean for those &#xXX;, 

Good question, and I did not find an obvious answer on the first page of Google results...
(But looking a bit more, I guess/hope we'll find it should be converted to the char with that num in the page advertized or guessed charset.)

**Comment by Markismus** [comment]
Converting a mobi-dictionary to other formats just got an extra layer of incompatibility. 
`<meta http-equiv="content-type" content="text/html; charset=windows-1252" />`

**Comment by Frenzie** [comment]
Btw, MuPDF doesn't do HTML rendering, it does XHTML rendering. XHTML = XML = UTF-8.

**Comment by Markismus** [comment]
Ah, so that's why I just ran into this problem. Until KindleUnpack of mobi to html, I never strayed from XML.

**Comment by poire-z** [comment]
> Converting a mobi-dictionary to other formats just got an extra layer of incompatibility.
`<meta http-equiv="content-type" content="text/html; charset=windows-1252" />`

You mean the converter (yours?) added that? so, it knows mobi are windows-1252, or that specific mobi advertized it?
And what if you pass that in the HML you give to MuPDF? Does MuPDF understands it and act accordingly?

**Comment by Markismus** [comment]
When I looked in the the html-file [KindUnpack](https://github.com/kevinhendricks/KindleUnpack) generated, I saw the meta-tag. I don't know whether the original mobi was cp-1252, but the generated html did advertise it.

**Comment by poire-z** [comment]
Not via CSS, nothing for encoding. Indeed, only via the head element (which is hardcoded in HtmlBoxWidget:setContent()).
But as you are the author/converted, you might as well convert everything to UTF8 and let cp1252 behind you (and KOReader :)

**Comment by Markismus** [comment]
Yes, that seems the right way to handle it. Thanks for the replies! I would never have found out what I stumbled on.
