### ISSUE TITLE
EvernoteOAuth.lua:210:wantread [Could not Login (Yinxiang Biji)evernote in China]

### ISSUE THREAD

**Issue by actg** [koreader/koreader#5895]
* KOReader version: v2020.02
* Device:KT4

#### Issue

Evernote in China(Yinxiang Biji) could't login.
![20200224133109](https://user-images.githubusercontent.com/6778447/75130593-3218d880-570a-11ea-8577-39fc60b7570c.jpg)

**Comment by seacatwu** [comment]
same Issue
KOReader version: v2020.04
device: kobo aura one

**Comment by Galunid** [comment]
@seacatwu @actg Could you please download latest nightly and confirm the issue is fixed?

**Comment by seacatwu** [comment]
KOReader version: V2020.06.19

EvernoteOAuth.lua:280:Target URL was not found in the response on login

**Comment by Galunid** [comment]
Could you try with latest nightly(Last menu -> Update -> Settings -> Update channel -> Development, Update -> Check for update)?

**Comment by seacatwu** [comment]
Yes,It's the lastest version:v2020.06.19-gf8af0a9_2020-06-24.
EvernoteOAuth.lua:280:Target URL was not found in the response on login.

**Comment by Galunid** [comment]
Evernote plugin got replaced with Exported plugin
