### ISSUE TITLE
Screensaver is blurry

### ISSUE THREAD

**Issue by daemongloom** [koreader/koreader#5900]
* KOReader version: v2020.02
* Device: Kindle PW4

#### Issue
Screensaver is blurry in both landscape and portrait. It was ok on v2020.01. Some lines are barely readable (Current and Today, for example). Daily progress bars are not completely black.
![20200226_090955](https://user-images.githubusercontent.com/3511755/75311220-e84e0080-5877-11ea-91f6-e621b40bc6f5.jpeg)

**Comment by NiLuJe** [comment]
This has been fixed in current nightlies (#5884).
