### ISSUE TITLE
Second blockquote in dictionary is handled differently

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#5901]
For example, this entry (prettified):
```html
[{"dict": "Duden 7.Aufl. 2011","word":"früh","definition":"
\n
<blockquote>
	<span>
		<span>
			<small><sup>1\n</sup></small><b>fr</b><u><b><b>ü</b></b></u><b>h</b><b> </b>
			<span>‹Adj.› [mhd. vrüe(je), ahd. fruoji, zu: fruo, </span>
			<span><b></b></span> <span><sup>2</sup><span>früh]: <b>1.</b> in der Zeit noch nicht weit fortgeschritten, am Anfang liegend, zeitig: <i>am -en Morgen; </i> <i><span>in -er, -[e]ster Kindheit; </span></i> <i>es ist noch f. am Tage; </i> <i>f. blühende Tulpen; </i> Ü <i>der -e (junge) Nietzsche; </i> Ü <i>die -esten (ältesten) Kulturen; </i> <sup>*</sup><b>von f. auf </b>(von früher Kindheit, Jugend an: <i>sie ist von f. auf an Selbstständigkeit gewöhnt). </i> <b>2.</b> früher als erwartet, als normalerweise geschehend, eintretend; frühzeitig, vorzeitig: <i>ein -er Winter; </i> <i>ein -er Tod; </i> <i>eine -e (früh reifende) Sorte Äpfel; </i> <i>wir nehmen einen -eren Zug; </i> <i>Ostern ist, fällt dieses Jahr f.; </i> <i>er kam -er als erwartet; </i> <i>sie ist zu f., noch f. genug gekommen; </i> <i>ihre f. (in jungen Jahren) verstorbene Mutter; </i> <i>ein f. vollendeter (in seiner Kunst schon in jungen Jahren zu absoluter Meisterschaft gelangter [u. jung verstorbener]) Maler; </i> <i>sie hat f. geheiratet; </i> <i>-er oder später (zwangsläufig irgendwann einmal) wird sie doch umziehen müssen.</i> 
		</span>
	</span>
</blockquote>
\n
<blockquote>
	<span>
		<span>
			<small><sup>2\n</sup></small><b>fr</b><u><b><b>ü</b></b></u><b>h</b><b> </b>‹Adv.› [mhd. vruo, ahd. fruo, eigtl. = (zeitlich) vorn, voran]: morgens, am Morgen: <i>heute f., [am] Dienstag f.; </i> <i>kommst du morgen f.?; </i> <i>er arbeitet von f. bis spät [in die Nacht] (den ganzen Tag).</i> 
		</span>
	</span>
</blockquote>
"}]
```
results in:
![Screenshot from 2020-02-26 11-23-59](https://user-images.githubusercontent.com/5269101/75336653-cf4f4a80-588b-11ea-9143-03ff17898d94.png)
The second blockquote is differently indented than the first. Why is that? Do I have to work around it?

The dictionary can be found [here](https://markismus.stackstorage.com/s/ouJXsxt4HBRPsDp).
I've tested it with an empty css-file, and a css-file with the line `blockquote { margin: 0 0 0 1em }`. 

Replacing the blockquote-blocks with span-blocks is not a work around, since multiple entries are then placed after another inline:
![Screenshot from 2020-02-26 11-30-54](https://user-images.githubusercontent.com/5269101/75337452-54872f00-588d-11ea-973e-032899f04d11.png)

Goldendict displays it as I would expect:
![Screenshot from 2020-02-26 11-46-07](https://user-images.githubusercontent.com/5269101/75337604-9e701500-588d-11ea-9e45-75d88741f572.png)

**Comment by poire-z** [comment]
Looks like the 2nd blockquote is indented as if it was still part of the first, so a blockquote inside another blockquote.
But look at how github did syntax highlighting on your HTML snippet: it stops at some point.
xmllint -format tells me:
```
parser error : Opening and ending tag mismatch: span line 3 and blockquote
parser error : Premature end of data in tag span line 2
parser error : Premature end of data in tag blockquote line 1
```
So, probably badly balanced HTML, and MuPDF does what it can with it :)

**Comment by Markismus** [comment]
Thanks. Found it: `<span><sup>2</sup><span>`!
I made a typo in the substitution.

Thanks for the pointer to xmllint!
