### ISSUE TITLE
PDF causes wrong apparent screen size.

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#5905]
* KOReader version: v2019.12-53-g2e60164_2020_01_23
* Device: Kobo Aura One

#### Issue
When reading the attached PDF file, the lower third of the screen remains blank (but for the status bar).  The next page starts where the previous one left off, so it is not merely blank on the screen.
EDIT: I cannot attach the file, because .pdf is not supported - so I put it in a zip file.
[pdf.zip](https://github.com/koreader/koreader/files/4258419/pdf.zip)

#### Steps to reproduce
Open the file in portrait, zoom to content width, and page through the document.
In landscape mode it works OK.

**Comment by Frenzie** [comment]
> v2019.12-53-g2e60164_2020_01_23

I assume that's been fixed by https://github.com/koreader/koreader/pull/5885, or in other words any nightly from this week rather than last month. ;-)

**Comment by Biep** [comment]
And indeed it is!  Now *that* is quick work: resolved in -7 days!
Thanks!

**Comment by Biep** [comment]
And it seems another bug is gone too (maybe related?): portrait-style book status in landscape mode making it impossible to click the [X] to close it.  Thanks for that too!

**Comment by NiLuJe** [comment]
@Biep: I have *no* hat you're talking about. Open a new issue with more details, please ;).

**Comment by Biep** [comment]
An issue because a bug has been solved??

**Comment by NiLuJe** [comment]
Ouch. Sorry, I misread that :D

**Comment by Biep** [comment]
A weird thing is that that bug recently *did* come back, but before I got around to reporting it, it is gone again.
(Unless it shows with some files and not with others, and it doesn't with the book I am reading now..

**Comment by NiLuJe** [comment]
Might have been https://github.com/koreader/koreader/issues/6340
