### ISSUE TITLE
MacBook 2017 (retina display): window size does not match content size

### ISSUE THREAD

**Issue by magicmirror1365** [koreader/koreader#5909]
* KOReader version: current
* Device: Emulator running on a MacBook 2017 (retina display)

#### Issue

Observed in a Koreader emulator running on a 2017 Macbook with a retina display. The window drawn is four times the size of the actual content (see attachment).

Things work fine on an external monitor, including a 4k one.

#### Steps to reproduce

Download current koreader, build on a Mac, and run. Put the window on the retina display on the Macbook. The window is 2x2 times the size of the content.

Attached are a screenshot of the issue, along with a revised SDL2_0.lua and SDL2_0_decl which fixed the issue for me.
[SDL2_0_decl.c.txt](https://github.com/koreader/koreader/files/4268953/SDL2_0_decl.c.txt)
[SDL2_0.lua.txt](https://github.com/koreader/koreader/files/4268954/SDL2_0.lua.txt)
<img width="712" alt="Screen Shot 2020-02-27 at 1 16 40 PM" src="https://user-images.githubusercontent.com/46451014/75584143-16307200-5a3d-11ea-816d-b7ba18eabf5d.png">

**Comment by Frenzie** [comment]
Forum discussion for reference: https://www.mobileread.com/forums/showthread.php?t=327700

**Comment by NiLuJe** [comment]
Random related comment that HiDPI scaling may not play very well with our current font rendering settings.

(Qt switches to unhinted rendering to avoid issues (and macOS's native rendering is already mostly unhinted), for instance. I think the main issue is with subpixel rendering, which obviously doesn't work if you scale it. We don't do that, since we live in grayscale land, so, eh, might not be too awful ;)).

**Comment by Frenzie** [comment]
Btw, I don't know when exactly it was added, but newer AMD Windows driver enable superscaling on UHD, in something 5k-ish. Previously you could only use it to render something in UHD and downscale it to a lower resolution. Obviously it's only relevant to titles from primarily prior to ~2015 but it's pretty neat. Much better at fixing jaggies than any type of AA. (Not that jaggies bother me, I just think it's cool to play something like Remember Me while it's looking absolutely stunning despite occasional 720p console textures.)

**Comment by NiLuJe** [comment]
Yeah, AMD's scaling algorithm is *much* sharper than nVidia's (which was apparently a Gauss-ish curve, which you can tweak in the driver. Meaning it's either too blurry, or too sharp :D).

**Comment by Frenzie** [comment]
Picked up in https://github.com/koreader/koreader/pull/5917
