### ISSUE TITLE
Incorrect rotation when width larger than height

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5910]
* KOReader version: 2020.02
* Device: SDL

#### Issue

Screen is rotated 90º CW when started in fullscreen, like on Android TV (#5725). Both touch and keys are not, so is pretty unusable even if the screen is in vertical position.

#### Steps to reproduce

```
export SDL_FULLSCREEN
koreader
```

![Captura de pantalla -2020-02-29 18-21-21](https://user-images.githubusercontent.com/975883/75612093-d2169d80-5b20-11ea-81ad-3e432a333e13.png)

**Comment by Frenzie** [comment]
The issue title is slightly wrong. Just try something like `kodev run -w=300 -h=200` to see why. ;-)

**Comment by pazos** [comment]
@Frenzie: same thing. What I should see?

**Comment by NiLuJe** [comment]
There's a w > h check that does stupid things somewhere (let's say, because of Kobos? :D).

**Comment by NiLuJe** [comment]
(I'm thinking of the isAlwaysPortrait crap, which possibly also applies here for some unfathomable reason).

**Comment by Frenzie** [comment]
@pazos I mean that `SDL_FULLSCREEN` doesn't affect a thing. On typical Ubuntu & Sailfish phones height is bigger than width so nothing will be "rotated." It's a generic width larger than height issue which happens to be triggered by fullscreen in your specific condition.

**Comment by Frenzie** [comment]
Put another way, we're pretty much running in fullscreen on all platforms. ;-)

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader-base/blob/5f9bc28fe7b599a30cce0272d7e44ebc435373e9/ffi/framebuffer.lua#L307-L313

**Comment by pazos** [comment]
Ok, thanks for the info. This quick and dirty diff fixes initial rotation. Things go boom on further rotations:

```diff
diff --git a/ffi/framebuffer.lua b/ffi/framebuffer.lua
index a8f1f89..8313df3 100644
--- a/ffi/framebuffer.lua
+++ b/ffi/framebuffer.lua
@@ -313,10 +313,12 @@ function fb:getScreenMode()
 end
 
 function fb:setRotationMode(mode)
+    --[[
     self.bb:rotateAbsolute(-90 * (mode - self.native_rotation_mode - self.blitbuffer_rotation_mode))
     if self.viewport then
         self.full_bb:setRotation(self.bb:getRotation())
     end
+    --]]
     self.cur_rotation_mode = mode
 end
 ```
