### ISSUE TITLE
Calibre not retaining book status

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [koreader/koreader#5911]
* KOReader version: v2020.02
* Device: KPW4

#### Issue

If I push a book to my Kindle via Calibre wireless device connection, everything works. *.calibre files are created at USB storage root, too (``/mnt/us``), and the books are shown as on the device. However, once I disconnect and reconnect to Calibre, the books are shown as not on the device, even though they are.

#### Steps to reproduce

1. Connect to Calibre via wireless device connection
2. Push some books
3. Disconnect from Calibre
4. Reconnect to Calibre

**Comment by NiLuJe** [comment]
Yep, known issue, our calibre wireless client implementation is *extremely* limited.

**Comment by NiLuJe** [comment]
I'm fairly sure there's an existing isssue about this, I just can't find it right now :D.
