### ISSUE TITLE
Custom fonts not found

### ISSUE THREAD

**Issue by yujiadeng** [koreader/koreader#5914]
* KOReader version: v2020.02
* Device: Nook GlowLight3

#### Issue
I create a `fonts` folder under `/sdcard/koreader` and put the custom fonts in yet KOreader fails to list it in font setting. I'ved tried both rebooting the app and the device but it sitll doesn't work.

**Comment by Frenzie** [comment]
It's possible that the fonts are incompatible or that the location isn't right for that device. Is that where the program stores its settings?

**Comment by yujiadeng** [comment]
turns out the .ttf file is broken... Thanks anyway!
