### ISSUE TITLE
feature request: metric of minutes/seconds per page or words per minute read viewable on status bar

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5915]
* KOReader version:
* Device:

I'm always seeking to be a better and more efficient reader.  It would be useful to see a metric of how many words per minute on the status bar so I could see page per page if my pace is improving/slowing down etc.  

I know we already have time till end of chapter (not all my ebooks have a good chapter mark) and time till end of book, which I do use, but I think this more granular metric might be of use to others and myself

At a higher level, it would be nice to know per book if my reading speed in terms of words read is increasing or decreasing.   Not sure how I can currently track this.

**Comment by pazos** [comment]
Duplicate of #4865
