### ISSUE TITLE
koreader 2020.2 crashes at launch on kobo aura one with FW 4.20.14601

### ISSUE THREAD

**Issue by jjmure** [koreader/koreader#5918]
* KOReader version: 2020.2
* Device: Kobo Aura One (fw 4.10.14601)

#### Issue
when launching koreader, il crashes with a bomb on the screen and the message "Don't Panic (Crash n°1 -> 1) Tap the screen to continue.
Then the reader reboots with the standard kobo interface 
#### Steps to reproduce
Select the koreader icon to launch the reader
[crash.log](https://github.com/koreader/koreader/files/4293673/crash.log)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
This looks to me like you might be missing at least one file in your installation.

```
03/05/20-14:57:11 INFO  could not open image file: resources/icons/appbar.home.png
./luajit: frontend/ui/widget/imagewidget.lua:172: attempt to index field 'bb' (a nil value)
stack traceback:
	frontend/ui/widget/imagewidget.lua:172: in function '_loadfile'
	frontend/ui/widget/imagewidget.lua:189: in function '_render'
	frontend/ui/widget/imagewidget.lua:294: in function 'getSize'
	frontend/ui/widget/iconbutton.lua:64: in function 'update'
	frontend/ui/widget/iconbutton.lua:53: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:92: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:1040: in function 'showFiles'
	./reader.lua:261: in function 'action'
	frontend/ui/uimanager.lua:812: in function '_checkTasks'
	frontend/ui/uimanager.lua:1095: in function 'handleInput'
	frontend/ui/uimanager.lua:1181: in function 'run'
	./reader.lua:279: in main chunk
	[C]: at 0x000140c1
!!!!
```

**Comment by jjmure** [comment]
on mac osx, in a term console : 

cd /Volumes/KOBOeReader
unzip ~/Downloads/KOReader-v2020.02.zip

on the first reboot of the reader, I had not set the option to prevent Nickel to index files in hidden directories, so the content of .add has been indexed. Then I modified the option in the kobo conf file and everything was right.

I can try to reinstall koreader, if you want

**Comment by jjmure** [comment]
I think the indexation has had an effect : 
ls -la
total 488
drwxrwxrwx@ 1 jjm  staff  12288  5 mar 13:43 .
drwxrwxrwx@ 1 jjm  staff   4096  5 mar 13:43 ..
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._README.md
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.align.auto.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.align.center.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.align.justify.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.align.left.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.align.right.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.arrow.enter.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.arrow.left.up.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.arrow.shift.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.book.open.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.cabinet.files.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.checkmark.thick.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.checkmark.thick.unchecked.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.chevron.first.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.chevron.last.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.chevron.left.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.chevron.right.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.chevron.up.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.clear.reflect.horizontal.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.column.one.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.column.three.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.column.two.large.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.column.two.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.control.collapse.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.control.expand.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.crop.large.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.globe.wire.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.grade.b.large.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.home.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.magnify.browse.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.page.corner.bookmark.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.page.text.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.plus.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.pokeball.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.settings.large.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.settings.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.spacer.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.text.size.large.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.tools.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.transform.rotate.right.large.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._appbar.wifi.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._dogear.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._eink_cmap.gif
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.open.0.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.open.100.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.open.25.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.open.50.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.open.75.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.secure.0.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.secure.100.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.secure.25.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.secure.50.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._koicon.wifi.secure.75.medium.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._menu-icon.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._stats.star.empty.png
-rwxrwxrwx  1 jjm  staff   4096  5 mar 13:43 ._stats.star.full.png
-rwxrwxrwx@ 1 jjm  staff    488  5 mar 02:54 README.md

I need to reinstall.

**Comment by jjmure** [comment]
After a new install of koreader, everything is OK.
I can close the issue. 

Thanks for your help.

**Comment by NiLuJe** [comment]
FWIW, KOReader icons were indexed *before* you applied the indexing filter, meaning once it got put in place, it proceeded to *delete* that stuff => kablooey.
