### ISSUE TITLE
Add folder shortcut no longer possible

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#5919]
* KOReader version: v2020.02-31-g72f2cef_2020-02-28
* Device: Tolino Epos 2 and Kindle PW4

Folder shortcuts: ‚Add new folder shortcut’ no longer works. No folder can be selected by clicking on it. This error occurs on both devices.

**Comment by pazos** [comment]
@elvvis: I never used that feature, but works fine for me.

You need to long press on the dir you want. See: 
![test](https://user-images.githubusercontent.com/975883/76016465-281e8300-5f1d-11ea-812d-2780215298b9.gif)

**Comment by elvvis** [comment]
It worked with the last version v2020.01, but not now. Neither on the tolino nor with the kindle.  @pazos: Have you tried the latest version?

**Comment by Frenzie** [comment]
It works fine for me afaict (on the very latest as well as 2020.02).

**Comment by elvvis** [comment]
I go to the folder shortcut with multiswipe (right and down). Now when I click on 'add new folder shortcut' nothing happens. No file browser appears in which I can select the directory.

**Comment by pazos** [comment]
> Have you tried the latest version?

Yeah, I did update just to test on my android tablet.

> I go to the folder shortcut with multiswipe (right and down). Now when I click on 'add new folder shortcut' nothing happens. No file browser appears in which I can select the directory.

Cannot reproduce. See 
![test (1)](https://user-images.githubusercontent.com/975883/76022150-d975e680-5f26-11ea-8159-e0bb390d50b6.gif)

**Comment by elvvis** [comment]
Here is an excerpt from the debug log that starts by clicking on "Add new folder link":

03/06/20-15:14:51 DEBUG single tap detected in slot 0 {
    ["y"] = 143,
    ["x"] = 72,
    ["h"] = 0,
    ["w"] = 0
}
03/06/20-15:14:51 DEBUG adjusted ges: tap
03/06/20-15:14:51 DEBUG Explicit widgetRepaint: table: 0x73f03f30 @ ( 0 , 91 )
03/06/20-15:14:51 DEBUG setDirty via a func from widget nil
03/06/20-15:14:51 DEBUG _refresh: Enqueued fast update for region 0 91 1072 92 
03/06/20-15:14:51 DEBUG refresh: fast -1 90 1074 94
03/06/20-15:14:51 DEBUG mxc_update: 1072x94 region @ (0, 90) with marker 8 (WFM: 1 & UPD: 0)
03/06/20-15:14:51 DEBUG creating coroutine for menu select
03/06/20-15:14:51 DEBUG setDirty via a func from widget ReaderUI
03/06/20-15:14:51 DEBUG painting widget: ReaderUI
03/06/20-15:14:51 DEBUG painting widget: table: 0x73f04f28
03/06/20-15:14:51 DEBUG _refresh: Enqueued ui update for region 0 91 1072 92 
03/06/20-15:14:51 DEBUG refresh: ui-mode -1 90 1074 94
03/06/20-15:14:51 DEBUG refresh: wait for submission of (previous) marker 8
03/06/20-15:14:51 DEBUG mxc_update: 1072x94 region @ (0, 90) with marker 9 (WFM: 257 & UPD: 0)
03/06/20-15:14:52 DEBUG BackgroundRunner: _execute() @  1583507692
03/06/20-15:14:52 DEBUG BackgroundRunnerWidget: start running @  1583507692
03/06/20-15:14:54 DEBUG input event => type: 3, code: 57(nil), value: 0, time: 1583507694.601087
03/06/20-15:14:54 DEBUG input event => type: 3, code: 58(nil), value: 28, time: 1583507694.601087
03/06/20-15:14:54 DEBUG input event => type: 3, code: 53(nil), value: 70, time: 1583507694.601087
03/06/20-15:14:54 DEBUG input event => type: 3, code: 54(nil), value: 147, time: 1583507694.601087
03/06/20-15:14:54 DEBUG input event => type: 3, code: 48(nil), value: 28, time: 1583507694.601087
03/06/20-15:14:54 DEBUG input event => type: 3, code: 50(nil), value: 28, time: 1583507694.601087
03/06/20-15:14:54 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1583507694.601087
03/06/20-15:14:54 DEBUG in tap state...
03/06/20-15:14:54 DEBUG set up hold timer
03/06/20-15:14:54 DEBUG adjusted ges: touch
03/06/20-15:14:54 DEBUG BackgroundRunner: _execute() @  1583507694
03/06/20-15:14:54 DEBUG BackgroundRunnerWidget: start running @  1583507694
03/06/20-15:14:55 DEBUG hold gesture detected in slot 0
03/06/20-15:14:55 DEBUG in hold state...
03/06/20-15:14:55 DEBUG adjusted ges: hold
03/06/20-15:14:55 DEBUG Explicit widgetRepaint: table: 0x73f03f30 @ ( 0 , 91 )
03/06/20-15:14:55 DEBUG setDirty via a func from widget nil
03/06/20-15:14:55 DEBUG _refresh: Enqueued fast update for region 0 91 1072 92 
03/06/20-15:14:55 DEBUG refresh: fast -1 90 1074 94
03/06/20-15:14:55 DEBUG mxc_update: 1072x94 region @ (0, 90) with marker 10 (WFM: 1 & UPD: 0)
03/06/20-15:14:55 DEBUG setDirty via a func from widget ReaderUI
03/06/20-15:14:55 DEBUG painting widget: ReaderUI
03/06/20-15:14:55 DEBUG painting widget: table: 0x73f04f28
03/06/20-15:14:55 DEBUG _refresh: Enqueued ui update for region 0 91 1072 92 
03/06/20-15:14:55 DEBUG refresh: ui-mode -1 90 1074 94
03/06/20-15:14:55 DEBUG refresh: wait for submission of (previous) marker 10
03/06/20-15:14:55 DEBUG mxc_update: 1072x94 region @ (0, 90) with marker 11 (WFM: 257 & UPD: 0)
03/06/20-15:14:56 DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1583507696.84004
03/06/20-15:14:56 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1583507696.84004
03/06/20-15:14:56 DEBUG in hold state...
03/06/20-15:14:56 DEBUG hold_release detected in slot 0
03/06/20-15:14:56 DEBUG adjusted ges: hold_release
03/06/20-15:14:56 DEBUG BackgroundRunner: _execute() @  1583507696
03/06/20-15:14:56 DEBUG BackgroundRunnerWidget: start running @  1583507696
03/06/20-15:14:57 DEBUG input event => type: 3, code: 57(nil), value: 0, time: 1583507697.284617
03/06/20-15:14:57 DEBUG input event => type: 3, code: 58(nil), value: 34, time: 1583507697.284617
03/06/20-15:14:57 DEBUG input event => type: 3, code: 53(nil), value: 1026, time: 1583507697.284617
03/06/20-15:14:57 DEBUG input event => type: 3, code: 54(nil), value: 74, time: 1583507697.284617
03/06/20-15:14:57 DEBUG input event => type: 3, code: 48(nil), value: 34, time: 1583507697.284617
03/06/20-15:14:57 DEBUG input event => type: 3, code: 50(nil), value: 34, time: 1583507697.284617
03/06/20-15:14:57 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1583507697.284617
03/06/20-15:14:57 DEBUG in tap state...
03/06/20-15:14:57 DEBUG set up hold timer
03/06/20-15:14:57 DEBUG adjusted ges: touch
03/06/20-15:14:57 DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1583507697.386086
03/06/20-15:14:57 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1583507697.386086

**Comment by poire-z** [comment]
> 03/06/20-15:14:51 DEBUG creating coroutine for menu select
03/06/20-15:14:51 DEBUG setDirty via a func from widget **ReaderUI**
03/06/20-15:14:51 DEBUG painting widget: **ReaderUI**

The strange thing is that it looks like you're in the Reader (displaying a book).
Normally, adding folder shortcuts should be done in File Browser, with no ReaderUI remaining.

So, can you describe how you reach "Add new folder shortcut" ? (in details, from the initial startup of KOReader, how do you have "Start with>", and what you do to reach that menu.
Oh, I see:

> I go to the folder shortcut with multiswipe (right and down). Now when I click on 'add new folder shortcut' nothing happens.

So, may be you reach that from the reader - and we haven't really tested how that's supposed to work :) If it's allowed, I guess we could restrict that gesture from not working from Reader :)

So, try it in File browser.

**Comment by elvvis** [comment]
Yes, I call the folder shortcut from the reader (book is open). It works in the file browser.
As I described above, this worked when the book was open in an earlier release (January or earlier).

**Comment by poire-z** [comment]
We don't see the error because it happens in some code wrapped in a coroutine (and errors are just discarded), but if we add some debugging into the coroutined func, we can see the real error:
```
03/06/20-18:06:29 DEBUG adjusted ges: tap
03/06/20-18:06:29 DEBUG creating coroutine for menu select
03/06/20-18:06:29 WARN  error in wrapped function: frontend/apps/filemanager/filemanagershortcuts.lua:70: attempt to index field 'file_chooser' (a nil value)
stack traceback:
 frontend/apps/filemanager/filemanagershortcuts.lua:70: in function 'addNewFolder'
 frontend/apps/filemanager/filemanagershortcuts.lua:21: in function 'callback'
 frontend/ui/widget/menu.lua:1176: in function 'onMenuChoice'
 frontend/ui/widget/menu.lua:1160: in function 'onMenuSelect'
 frontend/ui/widget/menu.lua:469: in function <frontend/ui/widget/menu.lua:468>
 [C]: in function 'xpcall'
 frontend/ui/widget/menu.lua:473: in function <frontend/ui/widget/menu.lua:471>
```

**Comment by poire-z** [comment]
So, caused by https://github.com/koreader/koreader/pull/5785 that didn't expect this to be called from somewhere else than the FileBrowser.
This should fix it:
```diff
--- a/frontend/apps/filemanager/filemanagershortcuts.lua
+++ b/frontend/apps/filemanager/filemanagershortcuts.lua
@@ -67,7 +67,9 @@ function FileManagerShortcuts:addNewFolder()
         select_directory = true,
         select_file = false,
         path = self.fm_bookmark.curr_path,
-        show_hidden = self.ui.file_chooser.show_hidden,
+        -- Use current file_chooser value if in file browser (if in reader,
+        -- PathChooser will pick the saved value from G_reader_settings)
+        show_hidden =  self.ui.file_chooser and self.ui.file_chooser.show_hidden,
         onConfirm = function(path)
             local add_folder_input
             local friendly_name = util.basename(path) or _("my folder")
```

**Comment by Frenzie** [comment]
Doesn't pathchooser already default to show_hidden = G_reader_settings:readSetting("show_hidden")?

**Comment by poire-z** [comment]
Yes, so that's what we will do now when in Reader - but #5785 was to made it use the current/updated (not yet saved in G_reader_settings) value when you have just toggle it in File browser (where settings are only saved in G_reader_setting on close I guess).

**Comment by Frenzie** [comment]
I see. So then it should be self.ui.file_chooser and self.ui.file_chooser.show_hidden or G_reader_etc, since otherwise you'll always set it to nil/false from the reader.

**Comment by poire-z** [comment]
But indeed, `FileManager:toggleHiddenFiles()` saves it immediately in G_reader_settings.
@robert00s : do you remember exactly why/for what #5785 was needed (ok, fixing #5759 - but then, why didn't it work?)

**Comment by poire-z** [comment]
> I see. So then it should be self.ui.file_chooser and self.ui.file_chooser.show_hidden or G_reader_etc, since otherwise you'll always set it to nil/false from the reader.

We'd set it to `nil` no ?
```
> print(nil and true)
nil
```
so, setting it to nil = not setting it, and PathChooser would use its own one:
https://github.com/koreader/koreader/blob/8da77b0fececedbde9f83c68e5562d7e0b23e27d/frontend/ui/widget/pathchooser.lua#L12-L32

But I get the problem: it's fetched from G_reader_settings in `new/extend()`, so it keeps the value it got from its first use/require. That's why @robert00s made #5785, to it get the current value.

But I guess the proper fix is to revert #5785, and just make PathChooser pick it from G_reader_settings in `PathChooser:init()`, so on each instantiation.

**Comment by Frenzie** [comment]
> so, setting it to nil = not setting it, and PathChooser would use its own one:

That can't be right, you're explicitly setting it to nil, not just leaving it undefined. So you're overwriting the defaults.

**Comment by poire-z** [comment]
In our context, we do that quite often.
```lua
    local path_chooser = PathChooser:new{
        show_hidden = nil
```
We're providing to new() a dict with no "show_hidden" key, so new() with its metaclass magic will still fetch for us (when we want to use it) the one in the base PathChooser object - that we have not overwritten.
