### ISSUE TITLE
In landscape mode frontlight level on status bar causes screen artifact on poweroff.

### ISSUE THREAD

**Issue by clarkspark** [koreader/koreader#5920]
* KOReader version: 2020.02
* Device: kobo_nova (Kobo ClaraHD)

#### Issue
In landscape mode the frontlight level on status bar causes screen artifact on poweroff.  The frontlight level status bar item being selected is what causes the artifact, the presence (or absence) of any of the other possible status bar items makes no difference.

#### Steps to reproduce
1 ensure statusbar is enabled
2 ensure the frontlight level box is checked
3 open an epub
4 set to landscape view
5 power off device

A vertical bar is then seen across the landscape text on my device.  The bar remains on the screen when the device is powered back on, and screen refresh removes it until the next power-off.  The frontlight indicator on the status bar (along the bottom) remains at the value when the device was on, and the 'anomalous' frontlight level shows the correct value.

![device off, horziontal, w_ light status bar showing issue](https://user-images.githubusercontent.com/14674610/76088389-f7266880-5f85-11ea-9dfb-67a0de8dca27.jpg)

**Comment by clarkspark** [comment]
I just verified that if the frontlight is set to 0 (which is displayed as 'Off' in the status bar) then the artifact is not triggered on suspend/poweroff.

Which would seem to indicate that it is the frontlight statusbar update from the '15%' string (in the scenario shown in the photo) to the 'Off' string which is mis-written to a perpendicular orientation.

**Comment by poire-z** [comment]
Probably due to what happens on suspend/poweroff:
- we set back the screen rotation to portrait (for screensaver images that are usually portrait).
- we turn off frontlight
- turning off frontlight requests the footer to update itself so, displaying itself in portrait mode (but then, no idea why just that FL indicator would be displayed...)
- some screen refresh here and there in that process :)

When the light is off, there's no need for these steps 2 & 3.

https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/ui/uimanager.lua#L56-L68
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/device/generic/device.lua#L193
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/device/generic/device.lua#L227-L230
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/device/kobo/powerd.lua#L391-L398
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/device/kobo/powerd.lua#L318
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/device/kobo/powerd.lua#L344-L349
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/apps/reader/modules/readerfooter.lua#L1859-L1863

As a quick hack, this might work:
```diff
 function ReaderFooter:onFrontlightStateChanged() 
+    if UIManager._entered_poweroff_stage or Device.screen_saver_mode then return end
     if self.settings.frontlight then 
         self:updateFooter(true) 
     end 
```
end

@NiLuJe probably has a better understanding of that (really ugly) big picture, there's probably a cleaner/more natural way to prevent that footer update along the way of events.

**Comment by clarkspark** [comment]
Is there a way to get the emulator (on linux) to simulate a button press/suspend to test changes?

**Comment by NiLuJe** [comment]
@poire-z: IIRC, the FL bit might be weirder in that it's not necessarily entirely async or something?

(i.e., it's terrible).

@clarkspark: No, that's deep into platform-specific innards, the emulator won't help you there.

**Comment by NiLuJe** [comment]
IIRC, the insane footer update on suspend is because of previous bugreports of users not having an up-to-date FL status in the footer for *one* page after a resume.

Have I mentioned how much I hate this bit and I wish we'd just burn that thing to the ground? :D.

**Comment by poire-z** [comment]
@clarkspark : you can try my above hack (one line to add to frontend/apps/reader/modules/readerfooter.lua , line 1860) to at least see if this flow of things is the culprit.

**Comment by clarkspark** [comment]
@poire-z: I'd like to try that change.  Is that done by cloning the repo, making the change, building, and installing it to my device?

**Comment by poire-z** [comment]
No, no need for all that! :) Our code is mostly just not-compiled text files.
Just plug your Kobo via usb to your computer, and browse its content.
Edit frontend/apps/reader/modules/readerfooter.lua with a text editor (not notepad, something that understands unix files, like notepad++), and add that line.
Save your change to the file, edit your text editor, safely unplug, and restart koreader, and test.

**Comment by clarkspark** [comment]
@poire-z: I did try your edit but there was no change.

I tried @line 58 in:
```
koreader/frontend/ui/uimanager.lua
```
changing:
```
Screen:setRotationMode(0)
```
to:
```
if Screen:screensaverType() ~= "disable" then
    Screen:setRotationMode(0)
end
```
but that also had no change.

{In the spirit that if the user has selected leave the screen as is, then maybe the screen shouldn't be rotated at all on suspend.  I'll try to find the issue which points to the fix for the incorrect FL status immediately after a resume alluded to by @NiLuJe and maybe play with that bug fix.}

**Comment by NiLuJe** [comment]
Your point about not rotating if the mode doesn't require it vaguely rings a bell, and *should* already be taken care of?

I think? If it isn't, that's definitely worth looking into ;).

**Comment by poire-z** [comment]
> not rotating if the mode doesn't require it vaguely rings a bell, and should already be taken care of?

Yep, you did that:
https://github.com/koreader/koreader/blob/8502a96a6a0e1d76b8c8d2747f540102b48b3d8b/frontend/device/generic/device.lua#L227-L242

For suspend I guess. Poweroff is done in UIManager.

> I did try your edit but there was no change.

Ok, may be my intuition is wrong then :|
Well, guess you'll have to disable bits here and there to find the one that stops that behaviour - and then we can try to understand what's happening.

**Comment by NiLuJe** [comment]
Note that i do think the OP meant suspend, not poweroff ;).

**Comment by NiLuJe** [comment]
But that check will indeed rotate if mode is `disabled`, which probably explains this?

**Comment by clarkspark** [comment]
I my experience there is no change in behavior between poweroff and suspend.  I changed the referenced line 234 in device.lua to:
```
     if (G_reader_settings:readSetting("screensaver_type") ~= "message" and G_reader_settings:readSetting("screensaver_type") ~= "disabled") then
```
and I still see the bug.

Just to verify: 'restarting' koreader just involves exiting to nickel and not a full device restart, right?

**Comment by clarkspark** [comment]
I take that back, my change immediately above seems to fix the issue.  Let me verify further though...  If it does I'll submit a PR?

**Comment by NiLuJe** [comment]
FWIW, Hamburger > Exit > Restart KOReader works just fine, and will be much quicker ;).

----

That would have been my first attempt, too, so, if it works, yep, fire up a PR.
I'd just double-check if there are other screensaver_type that I may also have missed ;).

**Comment by NiLuJe** [comment]
At a quick glance, that should indeed only be `"message"`and `"disable"`(not disabled!).

**Comment by clarkspark** [comment]
@NiLuJe: Correct.  Thanks, that was a typo.  I grep'd for 'screensaver_type' and to me that seemed to be the only place where the issue would be seen.

**Comment by Frenzie** [comment]
@clarkspark If you're quick it might make it into 2020.03. ;-)

**Comment by clarkspark** [comment]
@NiLuJe, @poire-z, and @Frenzie: Thanks for the help, the insight into the software and the chance to participate.

**Comment by Frenzie** [comment]
Btw, if you use a keyword like "fix" or "close" (instead of "address" ;-) ) in the PR then GH will auto-close the issue.

**Comment by clarkspark** [comment]
Thanks for the tip.  I did see in the PR a statement along the lines of: this PR 'might' close the issue. Next time I'll know to review some past PR to try to recognize those types of details.
