### ISSUE TITLE
Feature request : allow bookmarks view to contain more text including full highlighted portion

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#5926]
I was trying to find a portion of text I had highlighted earlier but because the bookmarks page has seemingly been changed to one line per mark I’m unable to do so.   

Request would be allowing the user to choose the length of highlights from one like to say full highlight text and perhaps a few options in between.  
![269B1278-3E0F-4B73-B97D-CDC3FF583AB4](https://user-images.githubusercontent.com/556667/76149217-d9caca80-6069-11ea-9b1d-9ff462ab6e49.jpeg)
* KOReader version:
* Device:

**Comment by poire-z** [comment]
> because the bookmarks page has seemingly been changed to one line per mark I’m unable to do so

Discussion about that in #5496.
But you can already tweak that a bit:

(OK, possibly not the most intuitive place) File browser > First Tab > Items>:
<kbd>![image](https://user-images.githubusercontent.com/24273478/76150730-d1947e80-60ad-11ea-8735-0ff02b0d3553.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/76150715-b9246400-60ad-11ea-9408-5f12ac03cc8d.png)</kbd>

(But OK, some of them also apply to TOC ... so, hope you'll find a balance.)

(And again: please clean up your issues - remove the default text at bottom if it does not apply.)

**Comment by arooni** [comment]
@poire-z Firstly I appreciate the quick response.  

I will try to do a better job of removing text that isn't applicable in issues.  

I suppose I'd still say even after enabling this setting that you pointed out that I'd like to enalbe an option to see *all* the highlighted text.  Otherwise, there doesn't seem to be a place within koreader that i can view all highlighted/notes.  I'd have to export to evernote to get that and leave reading on my kindle.

So I'd still ask for an option of "show all content highlighted/notes in notes/marks".  I think people would find this useful, for non fiction especially I think being able to browse thru all highlighted text would be handy.

**Comment by Oskar-Cint** [comment]
I second that idea. That is my favorite feature in the Kindle app, highlights are displayed perfectly there. It would be amazing to duplicate something similar in KoReader:

![IMG_20210326_222904_edit_153239087283387](https://user-images.githubusercontent.com/74194765/112694600-f0b1aa00-8e82-11eb-80d7-4be505d1725c.jpg)

**Comment by ofilipowicz** [comment]
I second that idea. That is my favorite feature in the Kindle app, highlights are displayed perfectly there. It would be amazing to duplicate something similar in KoReader:

![IMG_20210326_222904_edit_153239087283387](https://user-images.githubusercontent.com/7127243/112694699-150d8680-8e83-11eb-8330-400ee5bf6e54.jpg)

**Comment by ofilipowicz** [comment]
Also, it looks like highlights are sorted in descending order, starting from the end of the book. It would be good to add a sort-by option or swap the order.

**Comment by poire-z** [comment]
About the sorting, we have since a few months ago a setting to sort by increasing page number (that is, a setting to uncheck to not sort by largest page number :/).

**Comment by hius07** [comment]
Done in https://github.com/koreader/koreader/pull/11918.
