### ISSUE TITLE
Skim document window not opening

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#5932]
* KOReader version: 2020.02
* Device: Kobo Forma

#### Issue
The Skim document windows is not opening anymore when long-pressing on the botton status bar when reading a text PDF document in page mode. Instead it select any adjacent word and opens the dictionary.

#### Steps to reproduce
1. Open a text PDF document in page view mode
2. Press and hold on the status bar
3. The closest word on the bottom line gets selected and the dictionary window gets open instead of the Skim document window.

This was not reproducible with 2020.01 and still does reproduce in 2020.03

**Comment by poire-z** [comment]
Due to #5789. What you observe is the new expected behaviour.
Please read that PR and the linked issue before requesting the previous behaviour :)
The alternative, which is more practical I think, is a multiswipe gesture, see https://github.com/koreader/koreader/wiki/multiswipes

**Comment by SilverGreen93** [comment]
Hm... it seems that now the tap&hold on the status bar is non-deterministic, because in my case, in a epub it triggers the skim to dialog, but in pdf it does not.

**Comment by poire-z** [comment]
I guess it depends on the bottom margin, and having actually some text where you long-press to be highlighted (and may be the engines behaviours of selecting some nearest text when you long-press on some empty space... - i.e. the engine should not select text for your long press to get propagated to the footer actions).
