### ISSUE TITLE
Request: Sepeate bookmark and highlights windows

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#5933]
It would be nice to have a separate window to display the highlights and another one to display the bookmarks from the book, just to keep thinks organized.
I think this can be done easily by separating the bookmarks and highlights.

There can be 2 items under the first menu from the left:
Contents
**Bookmarks
Highlights**
\--------------
Go to
[...]

**Comment by poire-z** [comment]
Some rework of bookmarks and highlights is (slowly) ongoing, see #5794 and the linked issues (https://github.com/koreader/koreader/issues/1095#issuecomment-458918504).
We'll be able to do more interesting UI stuff once we get out of the existing mess :)

**Comment by SilverGreen93** [comment]
Great, thanks!

**Comment by Frenzie** [comment]
@poire-z Close in favor of #5794 or open as a separate thing?

**Comment by poire-z** [comment]
Dunno :) #5794 is about the cleanup, this one is about making sexy stuff later - and I guess there are a few similar enhancement issues opened.

**Comment by poire-z** [comment]
Implemented somehow in #8600.
