### ISSUE TITLE
Number pad arrows do not turn the page on Ubuntu

### ISSUE THREAD

**Issue by msf999** [koreader/koreader#5934]
* KOReader version: 2020.02
* Device: Ubuntu 18.04.4

#### Issue
Hi,

The arrow keys on the keyboard work fine for turning the page, but the arrows on the number pad (with number lock in the correct position) do not work. I tried using xbindkeys and xte to simulate the pressing of the arrow keys when their corresponding number pad keys are pressed, but this didn't' work as smoothly. 

Would love to see this implemented since using a small number pad to turn pages is more convenient than a keyboard/mouse.

Thank you.

**Comment by pazos** [comment]
Hi @msf999, you can create a custom event map for your needs.

Create `~/.config/koreader/settings/event_map.lua` with the content

```lua
return {
    [92] = "Left",
    [94] = "Right",
}
```

You can do arbitrary remaps following [this comment](https://github.com/koreader/koreader/issues/5761#issuecomment-573345775)

**Comment by msf999** [comment]
@pazos thank you so much, this worked perfectly!
