### ISSUE TITLE
Bottom margin to status bar

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#5936]
Please consider adding an option to add minimum bottom margin to status bar so some characters don't appear touching the edge.

Thanks!

**Comment by Frenzie** [comment]
Unless you're talking about crengine in paged mode, in which case there might be a bug, that's pretty much unavoidable. A margin at the bottom would mean characters cut off in mid-air instead.

K2pdfopt can do line detection, so clever tricks with a reasonable chance of success might be possible, but to me not worth the effort. PRs welcome of course. ^_^

**Comment by pblasi** [comment]
I don't know "margin" is the right word. Just check the "g". Some space would be nicer.

![IMG_20200310_114633_2](https://user-images.githubusercontent.com/4630686/76305391-5b6a6480-62c5-11ea-8fbd-3d8e23d8a764.jpg)

**Comment by Frenzie** [comment]
On which device is that?

**Comment by pblasi** [comment]
> On which device is that?

Kobo Clara HD

**Comment by pazos** [comment]
It is already possible to tweak that. You need to set `DMINIBAR_CONTAINER_HEIGHT` to a value in pixels greater than the font size you use for the statusBar.

If your statusBar font is set to 14 (default) then try to set the container height to 20 and see what happens. You can tune it to your favorite thing :smile: 

You can change that value in FileManager -> tools -> 2nd page -> advanced settings or modify settings.reader.lua directly.

**Comment by NiLuJe** [comment]
Err, what's that funky bar of black pixels on the bottom, there?

**Comment by Frenzie** [comment]
That should be the progress bar. ;-)

**Comment by NiLuJe** [comment]
Oh. :D.

**Comment by pblasi** [comment]
> Err, what's that funky bar of black pixels on the bottom, there?

Not a bar, it's outside the screen, so it's not "screen". Some building misalignment I guess and it's exagerated here by the angle of the picture.

**Comment by pblasi** [comment]
> It is already possible to tweak that. You need to set `DMINIBAR_CONTAINER_HEIGHT` to a value in pixels greater than the font size you use for the statusBar.
> 
> If your statusBar font is set to 14 (default) then try to set the container height to 20 and see what happens. You can tune it to your favorite thing 
> 
> You can change that value in FileManager -> tools -> 2nd page -> advanced settings or modify settings.reader.lua directly.

Do you mean FileManager inside Koreader? I don't find "tools" anywhere...
I tried adding "["dminibar_container_height"]" with different values inside "footer" group in settings.reader.lua, but there's no change.
What am I doing wrong?
Thanks!

**Comment by pazos** [comment]
https://github.com/koreader/koreader/blob/73a0f2f9d10fb02f95cb7cf01a7966ab78e1ea3e/defaults.lua#L196
