### ISSUE TITLE
Request: progress sync gesture

### ISSUE THREAD

**Issue by dowiew** [koreader/koreader#5938]
* KOReader version: latest
* Device: any

Hello, I frequently use the progress sync feature between Kindle at home and mobile phone in a bus to work or back. Just before I step out of the bus I have to sync, but it takes too much time: swipe to menu +tool icon +Progress sync +Push. It's hard to do with one hand (the second is busy to keep the bus handle).
I can't see any possibility to assign a gesture to push/pull the progress.
Such a feature would be very nice.

Thank you for your great work!
Wieslaw

**Comment by fazlerabbi37** [comment]
@Frenzie Hi, new user here. I just installed KOReader AppImage from the latest release and followed the OP's instruction but couldn't find Progress sync plugin. I tried the lasted release for Android from GitHub and F-Droid but the result is same. What am I doing wrong?

**Comment by Frenzie** [comment]
@fazlerabbi37 The menu differs depending on if you have a document open or not. Btw, the forum's better suited for asking user to user questions.

**Comment by fazlerabbi37** [comment]
> Btw, the forum's better suited for asking user to user questions.

I know this is not appropriate to ask those questing here instead of forum but I asked for two reason.
- I don't have an account in the forum
- Maybe we should have a clear documentation saying how to access and use it for new users like me?

Would you mind if I update the Wiki?

**Comment by Frenzie** [comment]
Absolutely, that's what the wiki's for!
