### ISSUE TITLE
After commit  of 15. Feb. 2020 PocketBook 623 build crashes with segmentation fault

### ISSUE THREAD

**Issue by cugumpac52** [koreader/koreader#5939]
* KOReader version: After commit 12e54a17b3f027872fabd4d890433d296f303667
* Device: PocketBook 623

#### Issue
After this commit, it is not possible to use Koreader in PocketBook 623. On starting the error appear that libc.so.6 version `GLIBC_2.7' was not found

#### Steps to reproduce
Just start the reader.lua from the command line in a telnet session to PocketBook 623

##### `crash.log` (if applicable)
OpenTheme: /ebrmain/themes/Contrast.pbt
ts: loading default calibration values
ffi.load: inkview
03/12/20-13:40:18 INFO  initializing for device PBTouchLux
03/12/20-13:40:18 INFO  framebuffer resolution: {
    ["h"] = 1024,
    ["w"] = 758
}
ffi.load: libs/libmupdf.so
ffi.load (warning): /lib/libc.so.6: version `GLIBC_2.7' not found (required by libs/libmupdf.so)
./luajit: ./setupkoenv.lua:27: Not able to load dynamic library: libs/libmupdf.so
stack traceback:
        [C]: in function 'error'
        ./setupkoenv.lua:27: in function 'load'
        ./ffi/mupdf.lua:25: in main chunk
        [C]: in function 'require'
        frontend/document/canvascontext.lua:14: in main chunk
        [C]: in function 'require'
        ./reader.lua:145: in main chunk
        [C]: at 0x00013f31
Segmentation fault

**Comment by NiLuJe** [comment]
Oh, joy. Something *actually* still running glibc 2.5 in 2020 :D.

**Comment by NiLuJe** [comment]
Err, wait. The old SDK was already targeting glibc 2.9. How ancient is this device, exactly?

**Comment by cugumpac52** [comment]
Last software update was from 2014. In libc.so.6 I can find the strings GLIBC_2.4 and GLIBC_2.5.
Well, it was working beautifully until last update

**Comment by Frenzie** [comment]
@cugumpac52 Could you please confirm if the fix works?

http://build.koreader.rocks/download/nightly/v2020.03.1-1-g27c3711_2020-03-12/koreader-pocketbook-v2020.03.1-1-g27c3711_2020-03-12.zip

**Comment by cugumpac52** [comment]
The binary is working, thank you guys for this great software and the unbeatable response time!

**Comment by cugumpac52** [comment]
Can I just use the toolchain generated by koxtools gen-tc pocketbook to build it or do I need to change anything?

**Comment by Frenzie** [comment]
The only change was in https://github.com/koreader/koreader-base/pull/1062 ^_^

**Comment by NiLuJe** [comment]
That means that if you want to build *other* stuff with that TC (or the old PB SDK, for that matter), you'll have to jump through the same kinds of hoops ;).
