### ISSUE TITLE
Relative filepath to local file broken in PDF

### ISSUE THREAD

**Issue by SCassidy-UK** [koreader/koreader#5941]
* KOReader version: 2020.03
* Device: Linux

#### Issue

Quite a specific use-case, but currently it seems KOreader only supports absolute file paths for links to other files on the device. If I create a pdf file with a hyperlink to another pdf file within the same folder (using LaTeX hyperref package) giving the relative filepath `./filename.pdf` then other pdf readers I have tried have the correct behaviour of opening filename.pdf if it exists in the folder. However, KOreader gives an error saying it is an invalid link. The link does work in KOreader if I replace it with an absolute file path.

This would be a useful feature/fix for me because I would like the same links to work whether I read the pdfs on my laptop or Kobo device.

**Comment by Frenzie** [comment]
Would you be able to attach a couple of test PDFs to illustrate the problem? It's a matter of when someone gets a few minutes to look at it they don't have to spend them making a test case. ;-)

**Comment by poire-z** [comment]
We're supposed to handle them correctly (at least, I checked that on local html files linking to other html files):

https://github.com/koreader/koreader/blob/f9a57a3dff123808653a0c1f864d736d07bd65a3/frontend/apps/reader/modules/readerlink.lua#L70-L72

https://github.com/koreader/koreader/blob/f9a57a3dff123808653a0c1f864d736d07bd65a3/frontend/apps/reader/modules/readerlink.lua#L458-L472

https://github.com/koreader/koreader/blob/f9a57a3dff123808653a0c1f864d736d07bd65a3/frontend/apps/reader/modules/readerlink.lua#L519-L560

So, might be worth switching to debug mode to see what kind of link string we get from the PDF.

**Comment by SCassidy-UK** [comment]
[linktest.pdf](https://github.com/koreader/koreader/files/4328413/linktest.pdf)
[linktest2.pdf](https://github.com/koreader/koreader/files/4328417/linktest2.pdf)

Here is a test. The link points to `./linktest2.pdf`. I have tested the link in the evince pdf viewer.

**Comment by Frenzie** [comment]
```
03/13/20-10:11:24 DEBUG onGotoLink: {
    ["y1"] = 143.85998535156,
    ["x1"] = 280.88299560547,
    ["y0"] = 132.16998291016,
    ["x0"] = 261.25399780273,
    ["uri"] = "file://./linktest2.pdf"
}
03/13/20-10:11:24 DEBUG External link: file://./linktest2.pdf
```

Works like this (which seems more accurate anyway… does CREngine just say `file:`?):
```diff
diff --git a/base b/base
index 0d18a9b6..60c8dc7f 160000
--- a/base
+++ b/base
@@ -1 +1 @@
-Subproject commit 0d18a9b6723dd7e6aa7b777688d5230ebf5b99ad
+Subproject commit 60c8dc7f43910ccaf0457dd560ba37dceab45246-dirty
diff --git a/frontend/apps/reader/modules/readerlink.lua b/frontend/apps/reader/modules/readerlink.lua
index 26378f3b..98a405f0 100644
--- a/frontend/apps/reader/modules/readerlink.lua
+++ b/frontend/apps/reader/modules/readerlink.lua
@@ -524,7 +524,7 @@ function ReaderLink:onGotoLink(link, neglect_current_location, allow_footnote_po
     end
 
     -- Check if it is a link to a local file
-    local linked_filename = link_url:gsub("^file:", "") -- remove local file protocol if any
+    local linked_filename = link_url:gsub("^file://", "") -- remove local file protocol if any
     local anchor
     if linked_filename:find("?") then -- remove any query string (including any following anchor)
         linked_filename, anchor = linked_filename:match("^(.-)(%?.*)$")
```

**Comment by poire-z** [comment]
> does CREngine just say file:?

I think it gives what's in the HTML file untouched.
But I think we should support both `file:somepath` and `file://somepath` - one might be more per-specs than the other, but I think I've seen both.
May be `link_url:gsub("^file:/?/?", "")` would be enough ?

That was my text file:
```html
<!DOCTYPE html>
<html>
<head>
<style>
p { color: red; text-indent: 1.2em;}
</style>
</head>
<body>

This is some text.<br/>
<a href="http://www.eazeazeaz.com">This is some text</a>.<br/>This is some text.<br/>This is some text.<br/>This is some text.<br/>
This is some text.<br/>
<a href="/">/</a>.<br/>
<a href="etc">etc</a>.<br/>
<a href="file:">file:</a>.<br/>
<a href="/etc/passwd">/etc/passwd</a>.<br/>
<a href="file:/etc/passwd">file:/etc/passwd</a>.<br/>
<a href="/etc/X11/rgb.txt">/etc/X11/rgb.txt</a>.<br/>
<a href="file:/etc/X11/rgb.txt">file://etc/X11/rgb.txt</a>.<br/>
<a href="/tmp/test.txt.txt">/tmp/test.txt.txt</a>.<br/>
<a href="file:/tmp/test.txt.txt">file:/tmp/test.txt.txt</a>.<br/>
<a href="file://tmp/test.txt.txt">file://tmp/test.txt.txt</a>.<br/>
<a href="file:///tmp/test.txt.txt">file:///tmp/test.txt.txt</a>.<br/>

<hr/>

<div class=thisisaDIV style="color: green">
This is some text.<br/>
This is <a href="Wikipedia/test-link2.html">test-link2</a> text.<br/>
This is <a href="Wikipedia/test-link2.html#toto tutu#titi tata">test-link2 with #</a> text.<br/>
This is <a href="Wikipedia/test-link2.html?q=eza&rez=eza#toto tutu#titi tata">test-link2 with ?</a> text.<br/>
This is some text.
</div>

</body>
</html>
```

**Comment by Frenzie** [comment]
```html
<a href="file:/tmp/test.txt.txt">file:/tmp/test.txt.txt</a>.<br/>
<a href="file://tmp/test.txt.txt">file://tmp/test.txt.txt</a>.<br/>
```
Note that Firefox normalizes these to the correct `file:///tmp/etc.`. That's `file://` as the protocol, and `/tmp/etc` as the path.

If Firefox does that then so should we, but for PDF the incorrect varieties should be less likely to be relevant.

The pattern you suggested should do the trick for that.

**Comment by poire-z** [comment]
Even the 2nd one `<a href="file://tmp/test.txt.txt">` which, with the per-specs `file://` scheme looks like it is a relative path `tmp/text.txt.txt`, FF normalizes it to a fullpath `/tmp/test.txt.txt` ?!

I'd may be be inclined to see `file:` and `file://` as possible supported schemes, and what's after as the path - and `file:/` as invalid/non supported , so, may be, it it works: `link_url:gsub("^file:(//)?", "") `

**Comment by Frenzie** [comment]
Ah, indeed. My bad. https://en.wikipedia.org/wiki/File_URI_scheme
