### ISSUE TITLE
Duplicate of CREngine

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5946]
* KOReader version: v2020.03.01
* Device: Kindle PW3 (5.9.7)

#### Issue
![FileManager_2020-Mar-11_044714](https://user-images.githubusercontent.com/6279855/76651712-747c4b00-653b-11ea-9fd8-a2584cdef491.png)
Duplicate of CREngine in the FM 'Open with' dialog.

#### Steps to reproduce
Open KOReader
Go to File Manager
Find a file (in this case I used a book in fb2.zip format)
Tap and hold
Select 'Open with'
'Cool Reader Engine' is shown twice. A duplicate is shown as 'selected', but it cannot be deselected or selected. If I tap on it, the previous choice remains there (e.i. if it was on MuPDF, it will still use MuPDF to open the file).

##### `crash.log` 
is not applicable. since KOReader does not crash with this dialog.

**Comment by NiLuJe** [comment]
Hmm, it's getting a DocumentRegistery from both fb2 and zip?

**Comment by Frenzie** [comment]
Btw, expected crash in debug mode:

```
03/13/20-20:53:44 DEBUG setDirty via a func from widget table: 0x7f6288943b20
./luajit: frontend/ui/widget/radiobuttontable.lua:86: RadioButtonGroup: multiple checked RadioButtons
stack traceback:
```
