### ISSUE TITLE
Some fonts render too bold

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5950]
* KOReader version: v2020.03.01
* Device: Kindle PW3 (5.9.7)

#### Issue
This is not a critical bug, but I still would like to report it. Maybe you can enhance the font rendering engine.

Fonts like Amazon Ember and Futura from stock Amazon firmware, and side-loaded such as Futura v1.001 ([Literata_v1.001.zip](https://github.com/koreader/koreader/files/4331317/Literata_v1.001.zip) are rendered too bold in KOReader. However, a [newer](https://fonts.google.com/specimen/Literata) version of Futura is fine.

Stock fonts are in /usr/java/lib/fonts/ (I don't know if I can upload them here from my Kindle due to copyright), side-loaded fonts are in /mnt/us/fonts/ folder. All fonts are given in sets of 4 ttf files (regular, bold, italic, bold-italic). 

No font settings affect this behavior (e.g. render modes, hinting, kerning, embedded styles).
A book is of fb2.zip format (if this matters).

P.S. By the way, what is the difference between render modes "book" and "web"? Also between hinting "native" and "auto"?

**Amazon Ember:**
![Reader_2020-Mar-13_152524](https://user-images.githubusercontent.com/6279855/76653584-544e8b00-653f-11ea-9059-41ad5db426d1.png)

**Futura:**
![Reader_2020-Mar-13_152553](https://user-images.githubusercontent.com/6279855/76654129-b0fe7580-6540-11ea-8c4b-162ba09d0d80.png)

**Literata v1.001:**
![Reader_2020-Mar-13_154657](https://user-images.githubusercontent.com/6279855/76654711-01c29e00-6542-11ea-8e1c-2343ca50a6a0.png)

##### `crash.log` 
[crash_fonts.log](https://github.com/koreader/koreader/files/4331925/crash_fonts.log)
It says some errors about Amazon Ember, old Literata and Caecelia fonts. Nothing about Futura though.

**Comment by NiLuJe** [comment]
That's more or less expected from the stock fonts (in fact, they should be blacklisted? Unless I missed 'em).

That's slightly more surprising with Literata, which I'm using without any issues over here. Granted, it's a manual OTF build, not whatever you're using ;).

**Comment by poire-z** [comment]
> No font settings affect this behavior (e.g. render modes, hinting, kerning, embedded styles).

Well, these are not the most obvious to affect fonts, but these ones are :):
<kbd>![image](https://user-images.githubusercontent.com/24273478/76669728-3c055d00-658d-11ea-8f2c-a1c1cefce6cc.png)</kbd>
(mentionning that just in case, I hope you have it to regular :)

> P.S. By the way, what is the difference between render modes "book" and "web"? Also between hinting "native" and "auto"?

Just long-press on "Render mode" and "Font hinting" and you'll be told:
<kbd>![image](https://user-images.githubusercontent.com/24273478/76669772-6ce59200-658d-11ea-9df0-66e2cef6e1dd.png)</kbd>

```
failed to register crengine font: </mnt/us/fonts/literata1001/literata-bold-italic.ttf>
failed to register crengine font: </mnt/us/fonts/literata1001/literata-bold.ttf>
failed to register crengine font: </mnt/us/fonts/literata1001/literata-italic.ttf>
failed to register crengine font: </mnt/us/fonts/literata1001/literata-regular.ttf>
failed to register crengine font: </usr/java/lib/fonts/Amazon-Ember-Medium.ttf>
failed to register crengine font: </usr/java/lib/fonts/Amazon-Ember-MediumItalic.ttf>
failed to register crengine font: </usr/java/lib/fonts/Amazon-Ember-Regular.ttf>
failed to register crengine font: </usr/java/lib/fonts/Amazon-Ember-RegularItalic.ttf>
failed to register crengine font: </usr/java/lib/fonts/Caecilia_LT_66_Medium_Italic.ttf>
failed to register crengine font: </usr/java/lib/fonts/Caecilia_LT_75_Bold.ttf>
failed to register crengine font: </usr/java/lib/fonts/Caecilia_LT_76_Bold_Italic.ttf>
```
Some font may not advertize their weight, so crengine can't really tell "this is 4 instances of the same font, the regular, the italic, the bold, and the italic bolc" - in which case, he would consider the 4 files as being the same font in regular (and as Bold comes before Regular in a-z, it may be seen and picked first - and the others are discarded and logged as above).
This may be what's happening with Ember and Caecilia.
Caecilia must get its Medium.ttf used, and the 3 other are considered duplicates.
For Ember, I guess you have some Amazon-Ember-Bold.ttf that gets picked up (so, it doesn't show as failed in the logs, but the others are).
(Or you have them duplicated and used from elsewhere.)

Some details in https://github.com/koreader/koreader/issues/4174#issuecomment-414349293.
So, bad font properties make them not really distinguishable/usable by crengine.

**Comment by poire-z** [comment]
And: when you see both `Amazon Ember` and `Amazon Ember Bold` in the menu, and `Futura` and `Futura Medium` in your menu, it's that their font names was different (the bold version of Amazon Ember should be named Amazon Ember...), so consider distinct fonts. So, it's may be another Amazon-Ember-something.ttf that comes first and is used... Really messy fonts.

**Comment by NiLuJe** [comment]
@poire-z: Yeah, Amazon fonts are... wonky. They're tamed into submission by fontconfig, which obviously doesn't help us ;).

@mergen3107: I've fixed Ember. Futura was beaten into submisison, but the bold with be synthetic. I haven't touched Caecilia because IIRC it may have worked properly at one point. It technically "works" now, but everything !regular is synthetic.

As @poire-z explained, your Literata build also has broken metadata. I've never had anny issues with it, personally (besides ACCESS mangling the hinting, but that's on Kobo).

**Comment by mergen3107** [comment]
Thank you very much guys for your lightning-fast replies!
I'll just stick to new Literata, it works fine and pay attention to font metadata in future :)
