### ISSUE TITLE
Contribution: Renewed Russian-Kazakh Keyboard

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5953]
* KOReader version: tested on 2020.03.01
* Device: Kindle Paperwhite 5.9.7

Dear KOReader Developers and Community,
First of all, it was such a touching moment to realize that current KOReader build for Kindle uses the Russian-Kazakh keyboard variant I [suggested](https://github.com/koreader/koreader/issues/2014) for Kindle Touch about 4 years ago.

I am happy to see so much improvement in keyboard's frontend like popups, selecting input languages and resizing the keys, that it motivated me to edit this keyboard again :D
Here is the archive with layout and its popup file: 
[koreader_new_RU_keyboard.zip](https://github.com/koreader/koreader/files/4332318/koreader_new_RU_keyboard.zip)

I will be happy if you find this keyboard useful enough to include it in the April release.
Please let me know if something should be changed.

1) Russian layout looks more natural now, with only popup keys for ё and ъ:
![Keyboard1](https://user-images.githubusercontent.com/6279855/76675817-ff892f80-6593-11ea-9b13-4f90a45498fb.png)

2) Kazakh letters moved from umlaut-layout to popups of the main layout.
![Keyboard2_Kazakh](https://user-images.githubusercontent.com/6279855/76675818-0021c600-6594-11ea-907d-a11d7cafa0d4.png)

3) Umlaut section is now a full-blown Greek alphabet + math symbols (overall I feel that 8 layers of keyboard is a little to much for a keyboard, but I decided to replace the keyboard completely now that I started).
![Keyboard4_Greek](https://user-images.githubusercontent.com/6279855/76675820-0021c600-6594-11ea-8de9-8b5c1925f3b8.png)

4) Arrow keys in Sym section are now aligned as on a PC keyboard.
![Keyboard3_Sym](https://user-images.githubusercontent.com/6279855/76675819-0021c600-6594-11ea-8942-c46612bb2e3c.png)

5) The keyboard files are edited in the most simple and clear way without any workarounds as I've seen in some other keyboard adaptations. I hope this makes it better to read and modify if needed.

Thank you! I really appreciate everything you are doing with KOReader and would like to contribute even more!

**Comment by Frenzie** [comment]
Would you like to submit a PR with the changes? Besides the tabs for indentation instead of spaces, it looks fine at a glance. ^_^

**Comment by mergen3107** [comment]
Thank you @Frenzie!
I replaced tabs with spaces and did pull request
