### ISSUE TITLE
Suggestion: compact dictionary download layout

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5955]
* KOReader version: 2020.03.01
* Device: Kindle PW3 (5.9.7)

#### Issue

I have a suggestion to make dictionary download page nicer. Let's ask KOReader to calculate and fit let's say 4 complete sets of dictionaries.
On the following screenshot you can see that there is "Entries" text. This is from previous page's last dictionary selection. And this thing happens on every page. I think this is because on the first page there is a title "Tap dictionary name to download". Without it, I think, there would be four completely fitting dictionary selections.

![FileManager_2020-Mar-14_023237](https://user-images.githubusercontent.com/6279855/76676708-9fe35200-659c-11ea-9f6c-b42eb3bb74fa.png)

Let's save some space and make it neat!

**Comment by Frenzie** [comment]
While there is something there that might bother those with OCD, the specifics differ per device.

Btw, feel free to play around with it here ;-)

https://github.com/koreader/koreader/blob/c2aac0f71eb4b3736928e3396cca063eaa63073b/frontend/apps/reader/modules/readerdictionary.lua#L833-L862
