### ISSUE TITLE
accessibility?

### ISSUE THREAD

**Issue by voipworld** [koreader/koreader#5958]
* KOReader version: V2020.03.2
* Device: Android (Redmi Note8)

#### Issue
KoReader is not accessible with android  right now, cant navigate at all. maybe the UI framework used is not native?
#### Steps to reproduce
enable TalkBack (you need google TTS at least), and run koreader

**Comment by pazos** [comment]
> KoReader is not accessible with android right now, cant navigate at all. maybe the UI framework used is not native?

It is native in the same sense of a game, but is not the common "android view hierarchy" app, so accesibility/leanback features need to be implemented from scratch.

Some things are doable (like adding a voice input handler that works like a d-pad) and others too dificult to make them feasible (like TTS output).

What are you trying to achieve?

**Comment by voipworld** [comment]
voiceInput is not reliable, the controls must be visible to the screen reader, or at least described by the ddeveloper like this:
https://developer.android.com/guide/topics/ui/accessibility/apps
regardless, according to my experiance, i dont think Koreader view can be made accessible..., only if i am out of ideas...

**Comment by pazos** [comment]
> voiceInput is not reliable, the controls must be visible to the screen reader, or at least described by the ddeveloper like this:

controls *are* visible on screen if an input device is attached (like a keyboard, a bluetooth page turner...). Probably you'll want higher contrast 
 for that graphical feedback and that needs to be implemented.

> regardless, according to my experiance, i dont think Koreader view can be made accessible.

Not easily, no. Please feel free to ask specific questions :smiley:

**Comment by Frenzie** [comment]
> others too dificult to make them feasible (like TTS output).

Although I'd add that crengine does have some support for TTS, so it might be slightly (not much ;-P) easier than expected.

**Comment by pazos** [comment]
> Although I'd add that crengine does have some support for TTS, so it might be slightly (not much ;-P) easier than expected.

Yeah, but I was talking about something like [VoiceOver](https://en.wikipedia.org/wiki/VoiceOver), where everything on the UI is translated to speech.

Anyways, I think KOReader won't be able to be used by blind people, who might want a document reader, not a document viewer. For the rest of accesibility improvements I'm more optimistic. Specially for input adaptations.

Closing this ticket as too generic. Feel free to open others asking for specific accesibility features.

**Comment by voipworld** [comment]
i think everyone here is thinking about tts output from the reader
itself, this is totaly wrong.
all i mean is that the app must be accessible to the TalkBack screen
reader, take a look at TalkBack
please try to understand.

**Comment by pazos** [comment]
@voipworld: Talkback and voiceover are just the same. One is used in Android/ChromeOS and the other for Apple products.

I have professional experience in adaptations for people with disabilities. One of the first things to consider is whether the tool is best suited to make a specific adaptation.

This program can be adapted very easily to people with mobility disabilities and some parts can be used to create a program adapted to specific cognitive impairments (but that might need heavy modifications, from simpler UI to replace text with pictograms, remove options..)

For people with visual impairments things are difficult. Most of the platforms where this program runs don't support any kind of accesibility features, and even on platforms where it is supported is not easy. Implementing a simple epub/pdf reader for android from scratch would be waaaaaaaaaay easier.

**Comment by voipworld** [comment]
yeah i understand, so i feel like i cant use the coreader at all...
