### ISSUE TITLE
Empty TOC lines

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#5961]
* KOReader version: 2020.03.02
* Device: Kindle PW3

#### Issue
Some fb2 books have empty lines after h1 headings, which get into TOC as a separate entry.
Should we suppress them?

Here is an example:
![Reader_2020-Mar-15_020442](https://user-images.githubusercontent.com/6279855/76697322-5d894600-666c-11ea-8803-9b62b5f28760.png)

The empty line here is right after the title, but inside the same section where the title is. Maybe that's why:
![Reader_2020-Mar-15_032607](https://user-images.githubusercontent.com/6279855/76697375-de484200-666c-11ea-872e-967ce5aec9e2.png)

**Comment by poire-z** [comment]
Seems this is just caused by the imbricated `<SECTION>`.
I got one too if I add these one I surrounded in red:
![image](https://user-images.githubusercontent.com/24273478/76699588-356f0680-66af-11ea-976a-d4664c3947b8.png)
<kbd>![image](https://user-images.githubusercontent.com/24273478/76699595-4881d680-66af-11ea-8f09-342d11257d36.png)</kbd>

So, dunno, might be per-specs (or per-simple-rules) to make that a TOC entry.
Or we should drop it if we don't find a `<title>` as a child.

(Goodbye BiDi hell, welcome FB2 hell ! :)

**Comment by poire-z** [comment]
Anyway, the code used to build the TOC for FB2 is:
https://github.com/koreader/crengine/blob/c1700e3798d2563123b303485f3bcb340017f66b/crengine/src/lvtinydom.cpp#L4877-L4908

`updateTocItem()` is called when exiting a `<SECTION>`, or  entering a new `<SECTION>` AND its parent is itself a `<SECTION>`.
FB2 specs: https://github.com/koreader/crengine/blob/master/fb2props/FictionBook2.2.xsd

Not delving into all this. Tell me what to do if you find out a better way to handle that :)

**Comment by hius07** [comment]
> Or we could drop it if we don't find a `<title>` as a child - but may be some books just have `<SECTION>` without any title and we would then miss valuable TOC markers.

I would drop.
The TOC of a book with sections without titles will show us just page numbers without any text. Do we need such TOC?
Personally, I haven't met such fb2 books.

One more question regarding TOC.
It seems useful to include start pages of `body[name="notes"]` and `body[name="comments"]` into the TOC.
Is it correct?

**Comment by poire-z** [comment]
> The TOC of a book with sections without titles will show us just page numbers without any text. Do we need such TOC?

Well, better some TOC with no text but page numbers, and chapter ticks, than nothing at all on books that would have only that. And having them for ticks, but not showing them in the TOC, would feel strange (and may be complicated when these no-text TOC items have children...

> It seems useful to include start pages of body[name="notes"] and body[name="comments"] into the TOC.

I guess so. At first look, it's not super clear how crengine builds the TOC for fb2 (it adds a TOC for each `<section>`, so each footnote should be in the TOC :) but that's not the case, so there must be something else...)

**Comment by hius07** [comment]
> better some TOC with no text but page numbers, and chapter ticks, than nothing at all

OK, maybe so. I've read many books with such ghost empty lines in the TOC, and had no book with sections without titles.
Not a big issue anyway.

> it's not super clear how crengine builds the TOC for fb2

I guess it scans only the first `body`.
I tried to add one more `body` (not "notes") and it didn't appear in the TOC.

**Comment by poire-z** [comment]
Right.
This seems to work:
```diff
--- a/crengine/src/lvtinydom.cpp
+++ b/crengine/src/lvtinydom.cpp
@@ -5032,6 +5032,13 @@ ldomElementWriter::ldomElementWriter(ldomDocument * document, lUInt16 nsid, lUIn
         _element = _document->getRootNode(); //->insertChildElement( (lUInt32)-1, nsid, id );
-    if ( IS_FIRST_BODY && id==el_body ) {
-        _tocItem = _document->getToc();
-        //_tocItem->clear();
-        IS_FIRST_BODY = false;
+    if ( id==el_body ) {
+        if ( IS_FIRST_BODY ) {
+            _tocItem = _document->getToc();
+            //_tocItem->clear();
+            IS_FIRST_BODY = false;
+        }
+        else {
+            // Add FB2 2nd++ BODYs' titles (footnotes and endnotes) in the TOC
+            // (but not their own children that are <section>)
+            _isSection = true; // this is just to have updateTocItem() called
+        }
     }
@@ -5114,3 +5121,3 @@ void ldomElementWriter::updateTocItem()
     // TODO: update item
-    if ( _parent && _parent->_tocItem ) {
+    if ( _parent && _parent->_tocItem ) { // <section> in the first <body>
         lString16 title = getSectionHeader( _element );
@@ -5119,2 +5126,6 @@ void ldomElementWriter::updateTocItem()
     }
+    else if ( getElement()->getNodeId() == el_body ) { // 2nd, 3rd... <body>, in FB2 documents
+        lString16 title = getSectionHeader( _element );
+        _document->getToc()->addChild(title, ldomXPointer(_element,0), getPath() );
+    }
     _isSection = false;
```
<kbd>![image](https://user-images.githubusercontent.com/24273478/91664740-6aea9d80-eaf1-11ea-9d6f-130d29eb7fc8.png)</kbd>

**Comment by hius07** [comment]
Great!

**Comment by hius07** [comment]
Oh, sorry, bold marks the current chapter. All works perfectly!

**Comment by KenMaltby** [comment]
I was hoping that this was about the empty lines you can get when using the "alternative TOC".  It would be interesting if the user could edit the lines and add a chapter title.  Just the page numbers is better than nothing, but there are times it would be worth the added effort, to add my own.

**Comment by NiLuJe** [comment]
@KenMaltby: You kinda can, as the exact level of nesting you want to use for the alt ToC is configurable.

Unless I misunderstood what you're asking? (I recall having to use it a few times recently, and I haven't noticed any issues with its behavior on my end).

**Comment by hius07** [comment]
> better some TOC with no text but page numbers, and chapter ticks, than nothing at all

The issue has been clarified and can be closed, imo; but before that may I propose to add a symbol (say, `>` or `~` or something nice) in the beginning of the empty TOC line. This will look prettier.

**Comment by poire-z** [comment]
`>` may be confusing with our similar collapse/expand icon. `~` feels a bit random.
Can't think of any nice Unicode symbol to use instead... https://en.wikibooks.org/wiki/Unicode/List_of_useful_symbols

**Comment by hius07** [comment]
Well, I thought of something simple, just to help eyes to trace the line.
Three dots (ellipsis)? Hyphen-minus?

**Comment by poire-z** [comment]
With https://www.compart.com/en/unicode/U+2E3B : 
![image](https://user-images.githubusercontent.com/24273478/104844027-09737180-58ce-11eb-9f03-94fe7a50db26.png)

Too wide ? If somebody wants to test and find a better one:

```diff
--- a/frontend/apps/reader/modules/readertoc.lua
+++ b/frontend/apps/reader/modules/readertoc.lua
@@ -44,4 +44,8 @@ end

-function ReaderToc:cleanUpTocTitle(title)
-    return (title:gsub("\13", ""))
+function ReaderToc:cleanUpTocTitle(title, replace_empty)
+    title = title:gsub("\13", "")
+    if replace_empty and title:match("^%s*$") then
+        title = "\xE2\xB8\xBB" -- U+2E3B Three-Em Dash
+    end
+    return title
 end
@@ -525,3 +529,3 @@ function ReaderToc:onShowToc()
         for _,v in ipairs(self.toc) do
-            v.text = self.toc_indent:rep(v.depth-1)..self:cleanUpTocTitle(v.title)
+            v.text = self.toc_indent:rep(v.depth-1)..self:cleanUpTocTitle(v.title, true)
             v.mandatory = v.page
```

Somehow, with EPUBs, a TOC item with an empty text is dropped by crengine and does not reach frontend.

**Comment by hius07** [comment]
> Too wide ?

Yeah, a little bit, as for me. Maybe, just a minus sign?

**Comment by Frenzie** [comment]
En-dash (–) please in that case. ;-)

**Comment by poire-z** [comment]
EM-DASH https://www.compart.com/en/unicode/U+2014
![image](https://user-images.githubusercontent.com/24273478/104844631-adaae780-58d1-11eb-924d-d0f25c4dcb48.png)

EN-DASH https://www.compart.com/en/unicode/U+2013
![image](https://user-images.githubusercontent.com/24273478/104844684-f2368300-58d1-11eb-84d0-253f6b5b334c.png)

Ascii Minus:
![image](https://user-images.githubusercontent.com/24273478/104844659-c61b0200-58d1-11eb-86be-340a181f54b4.png)

**Comment by poire-z** [comment]
> En-dash (–) please in that case. ;-)

For any semantic/logical reason ? Or just because you thought the width would be enough ?
(Any other semantic idea/symbol to express the absence of text/title ?)

**Comment by poire-z** [comment]
> Somehow, with EPUBs, a TOC item with an empty text is dropped by crengine and does not reach frontend.

That's done here: https://github.com/koreader/crengine/blob/a90c0be089b08e0b0af64289fb0fdc8ba6d5ca6b/crengine/src/epubfmt.cpp#L108-L118

Nothing in https://web.archive.org/web/20090831133730/http://www.niso.org/workrooms/daisy/Z39-86-2005.html#NCX or http://idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.4.1 seems to indicate TEXT can't be empty.
Should this be fixed, allowing empty TOC entries instead of just ignoring them ?

**Comment by Frenzie** [comment]
> For any semantic/logical reason ? Or just because you thought the width would be enough ?

Because an en or em dash would just look nicer than a minus.

**Comment by hius07** [comment]
> Because an en or em dash would just look nicer than a minus.

OK for any of them, up to you

**Comment by NiLuJe** [comment]
Well, a "semantically" correct symbol for indicating nothing would be U+2205 ∅ ;).

But, it might look fairly weird in this context ^^.
