### ISSUE TITLE
Cervantes: night mode doesn't work 

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#5963]
* KOReader version: latest
* Device: Cervantes 4

#### Issue

Night mode doesn't work, probably since https://github.com/koreader/koreader-base/pull/1047, as it used to work fine months ago.

Reported in https://www.mobileread.com/forums/showpost.php?p=3963993&postcount=11:
> when I switch to "Black Mode" in koreader, only the colors of the pictures are inverted. The text remains in black color against white screen

**Comment by NiLuJe** [comment]
Needs a `canHWInvert = yes,` flag in Device blocks ;).

**Comment by NiLuJe** [comment]
Also needs to same `if not self:canUseCBB() or not self:canHWInvert()` dance as on Kobo, in case there are devices where it is unsafe (i.e., the one based on the same board as the Kobo Aura).

**Comment by pazos** [comment]
Thanks for the patch @NiLuJe
