### ISSUE TITLE
Floating text box above screen saver of book cover possible?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#5964]
Would it be possible to have a text box overlay floating over the screen saver book cover when KOReader is suspended or shut down? Just like Nickel has? With information about the state (suspended or disabled) and about the reader's progress in the current book. It's the only feature of Nickel I really like 😄.

**Comment by KenMaltby** [comment]
The main purpose for a "Suspend" is to save battery while the device is not in use.  Having what is displayed change, uses power, as well as any work to calculate what is to be displayed.  That said,  if you wanted an unchanging text box added to what is displayed, that should be doable.  

If  "Floating" means something moving around on the screen (as is used to prevent it being "Burned In"), that is not needed with an eink screen.  

Luck;
Ken

**Comment by NiLuJe** [comment]
I absolutely abhor that Nickel feature, but it should be trivial to implement for someone interested. It's essentially image/cover + message (i.e., all the pieces are in place, they're just two separate modes right now).

**Comment by smartscripts-nl** [comment]
Bij floating I only mean "above". A moving text box would indeed be a bad idea, energy wise.

I think that the information shown in the text box doesn't have to be changed (and by doing so use power): it's only a moment of time fixed in the text box. You can look at the screen saver of Nickel, to see what I mean.

**Comment by NiLuJe** [comment]
Progress also exists, but it's the full-screen progress recap. I'm not familiar with it, so I don't know how easy it'd be to only pull *some* data out of it.

I vaguely seem to recall someone implementing keyword replacement in the message mode recently-ish, that could also be something worht looking itno.

**Comment by Frenzie** [comment]
Did they change it recently? I thought they just had an oddly small cover with a percentage underneath. Could you attach a photo?

**Comment by NiLuJe** [comment]
The option to have that on a full-screen cover might be somewhat recent, I don't rightly recall.

![fs_popup](https://user-images.githubusercontent.com/111974/76706370-3754bc00-66e7-11ea-9692-678da907d59a.png)

(We might have a patch to move the popup, IIRC?).

**Comment by Frenzie** [comment]
That's definitely nothing like how it looks for me. (I don't intend to update to any of the broken by design firmwares for now.)

Btw, that book as well as the TV show are pretty decent.

**Comment by poire-z** [comment]
Probably solved/solvable with #6238 and #5121 . Re-open if not.
