### ISSUE TITLE
Gestures for jumping to next or previous bookmark?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#5965]
Would it be possible to have menu items for jumping to the next or previous bookmark?

I know this is possible with the skimmer, but the skimmer when active covers almost a third of the visible page, so it is not really handy for jumping from bookmark to bookmark. To read the page I skimmed to I have to close the skimmer, then re-invoke it to jump to the next bookmark, close the skimmer, read the page, re-invoke the skimmer, etc. Tedious!

When gestures could be added for jumping back and forth between bookmarks (just like double tapping for jumping between chapters), this would be a real power feature!

**Comment by NiLuJe** [comment]
Random related question: on which device?

The skimmer is pretty non-intrusive in my experience (which, granted, is on a Forma ;p).

**Comment by smartscripts-nl** [comment]
I have a Forma. I experience the skimmer as very intrusive, often covering the text I want to read. I covers at about 97% of my horizontal screen space and 33% of my vertical screen space. I would not call that non-intrusive.

With the skimmer it is not possible to quickly and consecutively navigate and read the bookmarked pages/selections.

**Comment by smartscripts-nl** [comment]
Maybe I should add that I read in landscape and 2 column mode.

**Comment by mergen3107** [comment]
Do you use a mini progress bar? You can summon skimmer by tapping and holding it. This will save you extra taps to menu

**Comment by smartscripts-nl** [comment]
Yes, I use that bar. Thanks for the tip! But that doesn't take away the fact that the skimmer occupies screen space.

**Comment by poire-z** [comment]
Not killing your request for gestures, which might be really easy to add.

But just for info, you can long-press on that skimmer to make it translucide - and/or you can hold and move it, including mostly outside the screen if you hold long enough.. Hold again on it, and it will be brought back at the middle of screen.
This is useful not only when navigating bookmaks (that your request would help with), but also when navigating TOC entries, or just skimming when looking something...

**Comment by smartscripts-nl** [comment]
I didn't know that the skimmer could be made translucide. That helps a bit. But it still requires additional user actions to navigate bookmarks.

**Comment by smartscripts-nl** [comment]
Wild idea: a click at the left end of the mini progress bar navigates to the previous bookmark, while a click at the right end navigates to the next bookmark.

And maybe the user could enter in the settings whether these clicks navigate between chapters of between bookmarks.

**Comment by smartscripts-nl** [comment]
But now I remember that when clicks on the lower left corner of the reader have been assigned actions, a click on the left end of the mini bar won't work.

**Comment by mergen3107** [comment]
I use bottom swipe left/right for previous/next chapter respectively. So you need the same but for previous/next bookmark

**Comment by smartscripts-nl** [comment]
That would be handy indeed!

**Comment by smartscripts-nl** [comment]
I've copied the commits to my own installation and it works. Thanks!

However, something strange happens that I don't understand: when I consecutively navigate to 2 or more previous bookmarks, when I try to go into the opposite direction, the navigation refuses to go all the way back the original bookmark from which I started.

**Comment by NiLuJe** [comment]
Did it "break" similarly in the skimmer?

**Comment by smartscripts-nl** [comment]
Yes, there also.

**Comment by smartscripts-nl** [comment]
The farther I navigate back through the bookmarks, to the start of an ebook, the less far I can go back to previous positions.

**Comment by smartscripts-nl** [comment]
When from the Contents of the book I jump to the start and then try to cycle forward through the bookmarks, I don't get very far. I can go only 2 bookmarks forward and then the navigation stops, does nothing. Same problem, something with navigating forward through bookmarks?

**Comment by smartscripts-nl** [comment]
Navigating backwards to the start of the ebook gives no problems at all 👌.

**Comment by NiLuJe** [comment]
Just to be clear: this is new? It did not happen before applying the PR?

**Comment by smartscripts-nl** [comment]
I don't know. I will try now and then let you know.

**Comment by smartscripts-nl** [comment]
Resetting the changes in readerbookmark.lua doesn't make any difference when I use the skimmer. So it seems to be an fundamental problem. Not all bookmarks in the document "seen" when navigating forward of something like that?

**Comment by yparitcher** [comment]
@smartscripts-nl 
Cannot reproduce on master or on my branch (there are more changes btw)

did you restart koreader after editing the files?

**Comment by smartscripts-nl** [comment]
Yes, I did. To be sure I just now loaded another ebook. Same problem there, no difference. It would be nice (in a strange sort of way) if another person reports this same problem.

I don't remember having this problem in the past. But how long ago this was and with which version, I don't know.

**Comment by smartscripts-nl** [comment]
When the new version is published, I will try to install it from scratch and see if that makes a difference. I've modified some plugins (Goodreader, Evernote, perception expander) to fit my tastes, but that hardly can make a difference for navigating through bookmarks, I think?

**Comment by poire-z** [comment]
Mentionning 2nd commit of #5906, in case I messed up there (but I don't intend to scratch my head again in this binary search mess :)
