### ISSUE TITLE
[BUG] EPUB Highlight Range Adjustment Doesn't Support Punctuation

### ISSUE THREAD

**Issue by DaVinci42** [koreader/koreader#5967]
* KOReader version: V2020.03.2 and before
* Device: Sony DPT-CP1, Android 5.1

#### Issue
When clicking the highlight in epub, it will pop up a dialog to adjust the start/end of the highlight, but it doesn't take punctuation into consideration. 
For example, with the original sentence `Oh, latest koreader released`, and current highlight `Oh`. there's no way to change to `Oh,` including the `,`, instead it will change to `Oh, latest`

It doesn't happen when adjusting the end of the highlight only, but also the start.

#### Steps to reproduce
screenshots when trying to include `,` at end

![device-2020-03-16-022156](https://user-images.githubusercontent.com/4347318/76707944-2bd8b380-672e-11ea-8661-27598a51a80e.png)
![device-2020-03-16-022211](https://user-images.githubusercontent.com/4347318/76707947-3004d100-672e-11ea-8214-705bd1592389.png)

**Comment by poire-z** [comment]
Tap on the buttons moves by word.
Long-press on the buttons moves by char: that's what you want to do to include or remove any punctuation not grabbed as the words.

**Comment by DaVinci42** [comment]
@poire-z 
Thanks for your explanation. 
Yes, in this way, we can get the result with the minimum user operation.
But weird didn't find anything by Google.

Not an issue, close
