### ISSUE TITLE
Keyboard: is it possible to revert to lowercase characters after a uppercase one has been typed?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#5975]
As it stands now, when I type an uppercase character, the keyboard stays in uppercase mode and I have to explicitly click on the shift button to revert to lowercase.

Almost all virtual keyboards revert to lowercase characters after an uppercase one has been typed. Would it be possible to implement this behaviour for the KOReader keyboard also?

And maybe that a double click on the shift-key toggles capslock?

**Comment by hius07** [comment]
Nice point.

**Comment by NiLuJe** [comment]
Long-press for caps lock? (Unless lon,g-press already does something, I haven't checked).

But, yeah, I definitely agree, it's currently confusing at best ;).

**Comment by smartscripts-nl** [comment]
I didn't know that, but in the current version of KOReader a long press indeed toggles capslock. And the caps lock state is marked with a light gray color. Great!

But then it's all the more illogical that a short click on the shift key de facto also activates capslock, but doesn't show that new state with the gray color.

**Comment by yparitcher** [comment]
> But then it's all the more illogical that a short click on the shift key de facto also activates capslock, but doesn't show that new state with the gray color. 

It shows grey on my kindle

**Comment by yparitcher** [comment]
Just a warning, this will probably be difficult to implement as the keyboard is currently layer based. 
The modifier keys (shift/symbol) just change the layer.
The keyboard currently does not keep track of why a layer was changed.
To the keyboard pressing or holding shift is the same thing. They both switch from the lowercase layer to the uppercase layer or back.

To implement this would require keeping track of the shift state, when and how many keystrokes ago was shift pressed, and how that interacts with all the types of layers.

**Comment by mergen3107** [comment]
I believe this had been closed quite long time ago :D closing as complete
