### ISSUE TITLE
Time Sync does not reflect daylight savings

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [koreader/koreader#5977]
* KOReader version: 2020.03.2
* Device: KPW4

#### Issue

Time sync isnt reflecting Daylight Savings. I've manually set the time an hour ahead, but it keeps getting set back an hour, which is incorrect.

#### Steps to reproduce

1. Set time
2. Sync time
3. Observe wrong time

**Comment by Frenzie** [comment]
In principle it isn't supposed to. Normally the device clock would be in UTC, and matters like timezone and daylight saving time are based on the location you set up. I'm surprised to hear it doesn't work that way on Kindle.

**Comment by mergen3107** [comment]
There was a recent discussion on this:
https://www.mobileread.com/forums/showthread.php?t=327957

**Comment by Frenzie** [comment]
Thanks for the link! I'll regard that as the solution, although I am definitely surprised that setting up a location in Kindle settings may not have the same effect.
