### ISSUE TITLE
Terminal emulator output drawing issue

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#5979]
Kindle PW2 5.8.7, latest nightly build, pictures self explaining

Screenshot
![Reader_2020-Mar-19_084217](https://user-images.githubusercontent.com/62179190/77039646-10d0a280-69bf-11ea-92f1-382ed2b358d7.png)

Foto
![screen-foto](https://user-images.githubusercontent.com/62179190/77039666-18904700-69bf-11ea-9421-f2e69c158714.jpg)

**Comment by poire-z** [comment]
That's just a refresh issue, that can sometimes happen. Do you get that everytime?
Usually, a small diagonal swipe to cause a full refresh is enough to redraw when this happens (twice a week for me, on other things).
If that doesn't work, may be we should switch the terminal plugin to use a proper TextViewer (so, at least, output is scrollable, and maybe we can use a monospace font).

**Comment by hius07** [comment]
It happens everytime for any command, screen refresh helps, not a critical issue obviously.

**Comment by Frenzie** [comment]
It's also somewhat broken (but a lot less bad) on the H2O. Brownie points to anyone who can find the picture(s) I shared years ago. ;-)

**Comment by poire-z** [comment]
@hius07 : can you try replacing `plugins/terminal.koplugin/main.lua` with this one (to rename to main.lua): [plugin_terminal_main.lua.txt](https://github.com/koreader/koreader/files/4359059/plugin_terminal_main.lua.txt)
and tell me if the refresh issue is magically fixed?
(This also switches the output to using `TextViewer`, and it uses `Trapper:dismissablePopen()` so the execution can be cancelled - executing `cat` needed a hard reboot of the device :)

**Comment by hius07** [comment]
It is absolutely OK now, with a nice monospace font. Thank you.
