### ISSUE TITLE
Crash after having applied the "hide .nix files" 

### ISSUE THREAD

**Issue by skinkie** [koreader/koreader#5983]
* KOReader version:  Plato-0.8.4_KOReader-v2020.03.2.zip | 2020-Mar-12 15:34:45 
* Device: Kobo Aura HD

#### Issue

![4d190255-2b32-44e0-81d9-1e993358d645](https://user-images.githubusercontent.com/502394/77158556-d5f46a80-6aa3-11ea-8de6-3742193f52fd.jpeg)

#### Steps to reproduce

In .kobo/Kobo/Kobo eReader.conf I addded the section below. I did so after noticing all the images of koreader and plato were all through my book list.

```
[FeatureSettings]
ExcludeSyncFolders=\\.(?!kobo|adobe).*?
```
After starting koreader I got the crash above, plato forced a restart of the device. The images were still present. I am now going for a hard reset.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/4359179/crash.log)

**Comment by poire-z** [comment]
Nickel removed KOReader icons, so that crash. You need to reinstall koreader.
See https://github.com/koreader/koreader/issues/5918#issuecomment-595309509

**Comment by skinkie** [comment]
@poire-z thanks, I completely reinstalled the device. Everything works fine now!
