### ISSUE TITLE
Crash at launch - Bluestacks

### ISSUE THREAD

**Issue by khariche** [koreader/koreader#5987]
* KOReader version:2020.03.2
* Device:Android emulator in Windows

#### Issue
Both the arm and the x86 apks install fine bu the app crashes after asking for permissions and right after the orientation has shifted to vertical.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by mergen3107** [comment]
Can you get crash.log? 
What is the version of Windows and Bluestacks? 32/64 bit?

**Comment by khariche** [comment]
Thanks for your answer.
Windows 64, Bluestacks 4.170.10.1001
I am downloading the latest version at the moment to update the emulator, hoping it will help.
How can I get the crash log in bluestacks?

**Comment by Frenzie** [comment]
Which version of Android does this BlueStacks thing emulate? Can you choose different ones?

**Comment by khariche** [comment]
Android 7.1.2 Nougat. Don't see anyway to change the versioon.

**Comment by mergen3107** [comment]
Sorry, for Android there is crash.log, but you can extract logs with `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F` command. Not sure how to `adb` to Bluestacks though..

**Comment by mergen3107** [comment]
Try this: https://stackoverflow.com/questions/54317727/how-do-you-adb-to-bluestacks-4

**Comment by Frenzie** [comment]
7.1 isn't a version known to be problematic, but there's still an issue with 10.

**Comment by khariche** [comment]
> 7.1 isn't a version known to be problematic, but there's still an issue with 10.

I also have problems on my phone (moto g6 plus running android 9.0): crash at launch. Should I open another ticket, or can I copy the crash log here?

**Comment by Frenzie** [comment]
Putting it in here is the best way to ensure it's forgotten. ;-)

**Comment by khariche** [comment]
> Sorry, for Android there is crash.log, but you can extract logs with `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F` command. Not sure how to `adb` to Bluestacks though..

Here is the relevant bit:
03-20 22:56:14.267  1972  5417 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10204000 cmp=org.koreader.launcher/.MainActivity} from uid 1000 on display 0
03-20 22:56:14.269  1972  5417 D ActivityManager: TopActivityInfo, pkgName: org.koreader.launcher activityName: org.koreader.launcher.MainActivity callingPackage: com.bluestacks.BstCommandProcessor  bstSpecialAppKeyboardHandlingEnabled = false
03-20 22:56:14.271  1972  5417 D ActivityManager: Sending app launch intent for appName: KOReader pkgName: org.koreader.launcher
03-20 22:56:14.275  1972  7807 D ActivityManager: Sending TopActivity Info
03-20 22:56:14.307  1972  5039 D ActivityManager: TopActivityInfo, pkgName: org.koreader.launcher activityName: org.koreader.launcher/.MainActivity callingPackage:   bstSpecialAppKeyboardHandlingEnabled = false
03-20 22:56:14.310  1972  5039 D ActivityManager: Sending app launch intent for appName: KOReader pkgName: org.koreader.launcher
03-20 22:56:14.312  1972  7808 D ActivityManager: Sending TopActivity Info
03-20 22:56:14.322  1972  5039 I ActivityManager: Start proc 7809:org.koreader.launcher/u0a60 for activity org.koreader.launcher/.MainActivity
03-20 22:56:14.384  1972  5229 I ActivityManager: Start proc 7822:com.uncube.account/u0a39 for broadcast com.uncube.account/com.bluestacks.account.broadcastreceiver.MyAccountAppLaunchReceiver_
03-20 22:56:14.467  7809  7809 I KOReader: Application started
03-20 22:56:14.467  7809  7809 I KOReader: Application info {
03-20 22:56:14.467  7809  7809 I KOReader:   VM heap: 256MB (normal)
03-20 22:56:14.467  7809  7809 I KOReader:   Flags: user, legacy storage.
03-20 22:56:14.467  7809  7809 I KOReader:   Paths {
03-20 22:56:14.467  7809  7809 I KOReader:     Assets: /data/user/0/org.koreader.launcher/files
03-20 22:56:14.467  7809  7809 I KOReader:     Library: /data/app/org.koreader.launcher-1/lib/arm
03-20 22:56:14.467  7809  7809 I KOReader:     Storage: /storage/emulated/0
03-20 22:56:14.467  7809  7809 I KOReader:   }
03-20 22:56:14.467  7809  7809 I KOReader: }
03-20 22:56:14.926  1972  1996 I ActivityManager: Displayed org.koreader.launcher/.MainActivity: +617ms
03-20 22:56:15.146  1972  1986 I ActivityManager: Killing 7621:com.google.android.gms.ui/u0a2 (adj 906): empty #5
03-20 22:56:15.184  1972  2553 D ActivityManager: cleanUpApplicationRecord -- 7621
03-20 22:56:15.401  7809  7840 I KOReader: Check file in asset module: koreader-v2020.03.2.zip
03-20 22:56:15.409  7809  7840 I KOReader: Skip installation for revision v2020.03.2
03-20 22:56:15.412  7809  7840 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
03-20 22:56:15.450  1972  5192 I ActivityManager: Start proc 7870:com.android.vending:download_service/u0a0 for service com.android.vending/com.google.android.finsky.downloadservice.DownloadService
03-20 22:56:15.465  7809  7840 I KOReader: command chmod 755 ./sdcv returned 0
03-20 22:56:15.487  7809  7840 I KOReader: command chmod 755 ./tar returned 0
03-20 22:56:15.545  7809  7840 E KOReader: error: [string "dl.lua"]:41: error opening /lib/libc.so: dlopen failed: library "/lib/libc.so" needed or dlopened by "(unknown)" is not accessible for the namespace "classloader-namespace"
03-20 22:56:15.545  7809  7840 E KOReader: error: [string "dl.lua"]:99: could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-lfs.so
03-20 22:56:15.546  7809  7840 E KOReader: [NativeThread]: failed to run script: error loading module 'libs/libkoreader-lfs' from file 'libs/libkoreader-lfs.so':
03-20 22:56:15.546  7809  7840 E KOReader:      dlopen failed: library "libs/libkoreader-lfs.so" not found
03-20 22:56:15.546  7809  7840 E KOReader: [NativeThread]: Stopping due to previous errors

**Comment by khariche** [comment]
> Putting it in here is the best way to ensure it's forgotten. ;-) Please open a separate issue.

OK, I will open another ticket. Thanks :)

**Comment by Frenzie** [comment]
Looks like this might an issue with BlueStacks itself?
```
03-20 22:56:15.545 7809 7840 E KOReader: error: [string "dl.lua"]:41: error opening /lib/libc.so: dlopen failed: library "/lib/libc.so" needed or dlopened by "(unknown)" is not accessible for the namespace "classloader-namespace"
```

**Comment by khariche** [comment]
So it's not fixable? Sorry I am not a developer, just a user...

**Comment by Frenzie** [comment]
I'm sure it can be worked around, but the fact that this specific basic thing is not working seems to suggest something in the system itself is the cause.

**Comment by pazos** [comment]
Bluestacks never worked for me.

Nox works fine (it's based on a heavily modified 5.1) -> https://www.bignox.com/. 
GeanyMotion used to work fine but they discontinued the installer and now it is a web service.

**Comment by pazos** [comment]
Also the proper place to find libc is `/system/lib` instead of `/lib`.
