### ISSUE TITLE
Crash at lauch - Android 9.0

### ISSUE THREAD

**Issue by khariche** [koreader/koreader#5988]
* KOReader version: 2020.03.2
* Device: Moto g6 plus phone

#### Issue
Crash at launch, the app window doesn't even get to show.
##### `crash.log` (if applicable)
03-20 22:48:51.408  2089  3409 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity bnds=[236,1000][439,1241]} from uid 10090
03-20 22:48:51.468  2089  2200 I ActivityManager: Start proc 5461:org.koreader.launcher/u0a208 for activity org.koreader.launcher/.MainActivity
03-20 22:48:52.259  2089  4259 I ActivityManager: Process org.koreader.launcher (pid 5461) has died: vis  +99TOP
03-20 22:48:52.293  2089  2218 W ActivityManager: setHasOverlayUi called on unknown pid: 5461
03-20 22:48:54.009  2089  8788 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity bnds=[236,1000][439,1241]} from uid 10090
03-20 22:48:54.053  2089  2200 I ActivityManager: Start proc 5485:org.koreader.launcher/u0a208 for activity org.koreader.launcher/.MainActivity
03-20 22:48:54.502  2089  8788 I ActivityManager: Process org.koreader.launcher (pid 5485) has died: fore TOP

**Comment by Frenzie** [comment]
Did you deny it permissions or some such?

**Comment by khariche** [comment]
> Did you deny it permissions or some such?

No, and I just deleted cache and storage, and gave it permission again, but get a crash again.

03-20 23:12:12.456  2089  3926 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.koreader.launcher/.MainActivity bnds=[236,427][439,668]} from uid 10090
03-20 23:12:12.520  2089  2200 I ActivityManager: Start proc 8835:org.koreader.launcher/u0a208 for activity org.koreader.launcher/.MainActivity
03-20 23:12:12.591  8835  8835 I KOReader: Application started
03-20 23:12:12.591  8835  8835 I KOReader: Application info {
03-20 23:12:12.591  8835  8835 I KOReader:   VM heap: 192MB (normal)
03-20 23:12:12.591  8835  8835 I KOReader:   Flags: user, legacy storage.
03-20 23:12:12.591  8835  8835 I KOReader:   Paths {
03-20 23:12:12.591  8835  8835 I KOReader:     Assets: /data/user/0/org.koreader.launcher/files
03-20 23:12:12.591  8835  8835 I KOReader:     Library: /data/app/org.koreader.launcher-xMP5x7BrtsaP5tOEBClEzQ==/lib/arm
03-20 23:12:12.591  8835  8835 I KOReader:     Storage: /storage/emulated/0
03-20 23:12:12.591  8835  8835 I KOReader:   }
03-20 23:12:12.591  8835  8835 I KOReader: }
03-20 23:12:12.667  8835  8835 I KOReader: [MainActivity] Requesting WRITE_EXTERNAL_STORAGE permission
03-20 23:12:12.673  2089  8779 I ActivityManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10208
03-20 23:12:12.901  2089  2218 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity: +176ms (total +381ms)
03-20 23:12:14.074  8835  8848 I KOReader: Check file in asset module: koreader-v2020.03.2.zip
03-20 23:12:14.080  8835  8848 W KOReader: [AssetsUtils] java.io.FileNotFoundException: /data/user/0/org.koreader.launcher/files/git-rev (No such file or directory)
03-20 23:12:14.080  8835  8848 I KOReader: Found new package revision v2020.03.2
03-20 23:12:14.080  8835  8848 I KOReader: Installing new package to /data/user/0/org.koreader.launcher/files
03-20 23:12:17.626  8835  8848 I KOReader: Assets extracted without errors: 0 updated, 0 skipped, 839 new
03-20 23:12:17.628  8835  8848 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
03-20 23:12:17.667  8835  8848 I KOReader: command chmod 755 ./sdcv returned 0
03-20 23:12:17.697  8835  8848 I KOReader: command chmod 755 ./tar returned 0
03-20 23:12:17.721  8835  8848 I KOReader: Android 9 - Pie (API 28) - flavor: rocks
03-20 23:12:17.769  8835  8848 I KOReader:  initializing for device evert_n
03-20 23:12:17.769  8835  8848 I KOReader:  framebuffer resolution: {
03-20 23:12:17.769  8835  8848 I KOReader:     ["h"] = 2160,
03-20 23:12:17.769  8835  8848 I KOReader:     ["w"] = 1080
03-20 23:12:17.769  8835  8848 I KOReader: }
03-20 23:12:17.880  8835  8848 E KOReader: [NativeThread]: failed to run script: frontend/cache.lua:47: cannot open /storage/emulated/0/koreader/cache/: No such file or directory
03-20 23:12:17.880  8835  8848 E KOReader: [NativeThread]: Stopping due to previous errors
03-20 23:12:17.933  2089  8156 I ActivityManager: Process org.koreader.launcher (pid 8835) has died: fore TOP

**Comment by Frenzie** [comment]
@pazos Do you know what might be the problem with the emulated storage here?

**Comment by pazos** [comment]
> Do you know what might be the problem with the emulated storage here?

I have no idea. Everything looks fine. `/sdcard` should be a symbolic link to `/storage/emulated/0`, so maybe knowing the output of `adb shell ls /sdcard/koreader` could help.

**Comment by khariche** [comment]
Nevermind, it was a problem with the phone's internal storage filesystem, formatted data from twrp and everything is working smoothly now. Closing the bug.
Sorry for the inconvenience.
