### ISSUE TITLE
Kindle: top bar disappears on exit

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#5990]
PW2 5.8.7, v2020.03.2-9
Sometimes (rather often) the top status bar disappears on exit from KOReader.
Only reboot restores it. For sure it began after https://github.com/koreader/koreader/pull/5943.

![1](https://user-images.githubusercontent.com/62179190/77223224-2b438100-6b63-11ea-8a26-4cecc125e3e3.jpg)

**Comment by NiLuJe** [comment]
Does it happen after an OTA?

After a KOReader restart (I do mean a restart, not an exit/start)?

**Comment by NiLuJe** [comment]
(I did encounter it last night when testing #5989, quite possibly in conjunction with one or both of these things. But 8AM brain ;D).

**Comment by hius07** [comment]
No OTA, did several restarts before that.
I just tried to reproduce, made a couple of restarts, exits and starts - the bar is in place, doesn't disappear. I shall watch over it further to catch the reasons.

**Comment by NiLuJe** [comment]
I started testing suspend/resume at one point, too, that might factor in (not on an SO device, though).

**Comment by hius07** [comment]
v2020.03.2-16, manually updated.
No KOReader restart, but several switches to FM and back. Lost top bar on exit.

**Comment by NiLuJe** [comment]
Of course, I can't reproduce it after having added some debug logging in #5989... :D.

**Comment by hius07** [comment]
Is there a lipc command to restart ui without rebooting the device?

**Comment by NiLuJe** [comment]
Tomorrow's nightly will log the geometry string, which should allow one to fix it by hand if need be.

**Comment by NiLuJe** [comment]
That info is output to the syslog (i.e., `showlog -f`), and can be used to restore the titlebar via `${KOREADER_DIR}/wmctrl -r titleBar -e "${TITLEBAR_GEOMETRY}"`.

e.g., it's something like 0,0,0,758,41 on my PW2 (IIRC, no Kindle on hand right now).

**Comment by hius07** [comment]
PW2 5.8.7 **with SO**, v2020.03.2-17
To destroy top bar: start KOReader, enable screensaver (with ads), exit KOReader.

Trying to restore with wmctrl (0,0,0,758,41):
1) KOReader Terminal emulator: top bar appears after exit and immediately disappears
2) kterm: **top bar is restored**
3) RUNME.sh in /mnt/us
`#!/bin/sh
/mnt/us/koreader/wmctrl -r titleBar -e "0,0,0,758,41"
`
and ;log runme in the search: no effect

I would prefer roll back of https://github.com/koreader/koreader/pull/5943. Incorrect wifi symbol is less annoying than permanent loosing of the top bar.

**Comment by NiLuJe** [comment]
I kinda forgot the most important part:

I'll actually *need* those syslog excerpts when you actually trigger it :D.

**Comment by hius07** [comment]
How can I get those excerpts? ;dm as usual?

**Comment by NiLuJe** [comment]
Yep. Or via `showlog` in a shell.

**Comment by hius07** [comment]
Actions in the log beginning from 17:07
start KOReader, screensaver on, screensaver off, exit KOReader (top bar destroyed)
once more start KOReader, exit (no bar)
run KUAL extension with wmctrl (0,0,0,758,41) (top bar restored)
[syslog.zip](https://github.com/koreader/koreader/files/4397360/syslog.zip)

**Comment by NiLuJe** [comment]
Hopefully #6009 should take care of it.

Even on a non-SO devices, toggling the screensaver does affect the amount of attempts necessary to successfully restore the titlebar. Huh.
