### ISSUE TITLE
Bookmarks don't work correctly in some rare cases

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#5991]
* KOReader version: Last one (Mars 21, 2020)
* Device: Kobo Mini

#### Issue
Bookmarks don't work correctly in the book I am reading when the bookmark is in the first page of a new chapter. The book is in epub format.
If I touch the upper right corner at the beginning of a chapter, the bookmark mark will appear in that corner of the page and the bookmark will appear in the bookmarks list.
If I touch again that corner to delete the mark and the bookmark, the mark will disappear, but the bookmark will continue appearing in the bookmarks list. The only way to delete the bookmark is from the bookmarks list.
If I bookmark the book at the beginning of a chapter and turn one page or several, and then I go back to the beginning of the bookmarked chapter, the bookmark mark won't be there although the bookmark will appear in the list of bookmarks.
If I bookmark any other page of the book that is not in the beginning of a chapter, bookmarks will work correctly with this book.

#### Steps to reproduce

Try the above on the extract of the book in epub format that I include here.
(Steps I followed to create t he extract:
The book is commercial and I cannot upload it here, so I unzipped the epub, extracted 2 whole chapters in html, deleted most of the text of these two chapters and created an epub using calibre editor. I tried that extract (a minibook of 3 pages) on my e-reader and the problem continues. So it must be something in the format of the beginning or end of the chapter.)

[Bookmark problem.zip](https://github.com/koreader/koreader/files/4362997/Bookmark.problem.zip)

**Comment by poire-z** [comment]
Thanks for the mini test epub, easier to debug and fix with such a small one :)
I can reproduce the issue, I'll have a look.

**Comment by poire-z** [comment]
Probably caused by the empty div at start of page:
```html
          <div class="element-number-block">
          </div>
          <div class="title-page-contributor-primary-block">
            <h1 class="title1" id="calibre_pb_0">20</h1>
          </div>
```
If we add some height to it, the bookmark is shown:
```html
          <div class="element-number-block" style="height: 1px">
```
Possibly some issue with collapsed margins.

**Comment by poire-z** [comment]
I like it when the fix is so simple:
```c
--- a/crengine/include/lvtypes.h
+++ b/crengine/include/lvtypes.h
@@ -143,8 +143,9 @@ public:
     /// returns true if specified rectangle is fully covered by this rectangle
     bool isRectInside( lvRect rc ) const
     {
-        if ( rc.isEmpty() || isEmpty() )
-            return false;
+        // This was wrong: a 0-height or 0-width rect can be inside an other rect
+        // if ( rc.isEmpty() || isEmpty() )
+        //    return false;
         if ( rc.left < left || rc.right > right || rc.top < top || rc.bottom > bottom )
             return false;
         return true;
```
as we use it at https://github.com/koreader/koreader-base/blob/7a5c9e1110912c196e478344ec4e1edacb88c061/cre.cpp#L2943-L2954

Here some libcrengine.so and libkoreader-cre.so compiled for Kobo, that you can override the ones in your koreader/libs/ with - please confirm that works too on your full book:
[libcrengine-kobo-bookmarkfix.zip](https://github.com/koreader/koreader/files/4363232/libcrengine-kobo-bookmarkfix.zip)
(It also includes some support for EPUB3 TOC, so if your books have issues with the TOC, please tell me :)

**Comment by retrue** [comment]
Thank you very much, @poire-z 
It is fixed. I just copied these two files, loaded the book (the full one, not the extract) and it works.
