### ISSUE TITLE
Feature request: Text editor in FM

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#5996]
It would be nice to call Text editor directly from the File Manager via new button Edit in the long tap menu.

**Comment by poire-z** [comment]
What's the use case ? Editing/correcting FB2 files ?

I find it a bit dangerous to have Edit that easily available (while still possible via the Text editor menu and file chooser).
And there are a few difficulties:
- the text editor is a plugin, it can't hack the hold menu - so it would have to be set up in core, even if plugin unavalaible (might be we can check, but it's a bit ugly)
- and where to put that button on that hold menu ? that's always a delicate choice :)
- only a few book formats are editable (FB2, HTML, TXT), so it would be greyed out on many files

**Comment by hius07** [comment]
I have Show unsupported files checked in FM, so ini, lua, log etc. can be accessed (viewing, investigating...).
Can Text editor be added to the Open with... request for all file types?

**Comment by poire-z** [comment]
Yes, adding `with text editor` into `Open with...` is possibly the most discreet option :) 

Looks like there are a few ways to do that:
A) add text_editor jus like any other provider, and allow checkboxing "use this engine on all file of this type/this file only" - the file would be added in History, and re-open on next start - but that's complicated as it touches many things like ReaderUI and some fallbacks to opening Filebrowser as the app behind on start up... lots of work :/
B) add it as one of the choosable providers, but just for this time (we disable the other checkboxes when that radio is checked), and just have TextEditor open this file: we're in Filebrowser, we stay in Filebrowser, we're back to it when TextEditor is closed. Less complicated.
C) add a wide button below or above `Cancel | OK` : `Open with text editor` - so no mess with the radio/checkboxes. Easier :)
D) let things as they are: use the Text Editor menu and its file chooser

@Frenzie: any thoughts ?

**Comment by Frenzie** [comment]
B (and A) would be slightly prettier, but C should be acceptable. And personally I have no problem with D either.

**Comment by hius07** [comment]
C (saves a tap comparing to B)

**Comment by hius07** [comment]
But B might look prettier

**Comment by Frenzie** [comment]
> C (saves a tap comparing to B)

For this specific action. By prettier I implicitly mean a few more things. ^_^

**Comment by hius07** [comment]
More on the Open with... dialogue.
The window header is `Open filename with:`.
Long filenames are truncated and we have `Open longlonglongfil...`.
I propose to truncate long filenames shorter, to provide `with:` always visible: `Open longlong... with:`.

**Comment by poire-z** [comment]
Or make it a multi-lines title :) 
![image](https://user-images.githubusercontent.com/24273478/91641011-eb41cd80-ea21-11ea-8f6a-f84d1decba84.png)

Should I just use "Text editor" ? "Edit with text editor" might not be gramatically correct following the title sentence, but it makes it a bit different than the other named engine.

**Comment by Frenzie** [comment]
> Or make it a multi-lines title :)

Still needs to be limited at some point though. :-)

> Should I just use "Text editor" ? "Edit with text editor" might not be gramatically correct following the title sentence, but it makes it a bit different than the other named engine.

Text editor is the most logical I'd say.
