### ISSUE TITLE
OPDS saves .fb2.zip as .fb2

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#5997]
While loading from flibusta where all the books are stored in .fb2.zip format.
Is it correct? I would prefer to see zip extension for a zipped file.

**Comment by Frenzie** [comment]
EPUBs are also just zip files btw. But I'm inclined to agree this doesn't seem quite right.

https://github.com/koreader/koreader/blob/55d710904266ebbb8f98f44dda8bc23211e351e8/frontend/ui/widget/opdsbrowser.lua#L544

**Comment by hius07** [comment]
May I update the topic? It would be nice to have it fixed.

**Comment by Frenzie** [comment]
I downloaded some files and they saved as .fb2?

![Screenshot_2020-07-21_22-40-58](https://user-images.githubusercontent.com/202757/88104799-4242c000-cba3-11ea-97e6-75dc2fc18ac0.png)

**Comment by hius07** [comment]
Yup, and they are fb2.zip actually.

**Comment by hius07** [comment]
In my opinion, it would be better if opds module would save the downloaded book with the exact name retrieved from the server, not taken from the book's metadata.
Flibusta often has several versions of the same book, their file names differ, but metadata names coincide.
The extension should be kept original as well, not just adding the file type which we requested in the opds browser dialogue.

**Comment by Frenzie** [comment]
I already agreed with that; I just didn't realize it was a nitpick. ^_^

**Comment by Frenzie** [comment]
It's not quite that simple btw. 
```
07/22/20-12:35:08 DEBUG downloading file /home/frans/src/kobo/koreader/test/fb2 from http://www.flibusta.is/b/226848/fb2
```

```
$ curl -I http://www.flibusta.is/b/226848/fb2
HTTP/1.1 302 Moved Temporarily
Server: nginx
Content-Type: text/html; charset=utf-8
Cache-Control: public, max-age=600
Last-Modified: Wed, 22 Jul 2020 10:35:08 +0000
Expires: Sun, 11 Mar 1984 12:00:00 GMT
ETag: "1595414108"
Location: http://static.flibusta.is:443/b.fb2/Sobchak_Enciklopediya-loha.TWthOQ.226848.fb2.zip
Vary: 
Content-Length: 0
Accept-Ranges: bytes
Date: Wed, 22 Jul 2020 10:36:58 GMT
Age: 110
Connection: keep-alive
```

**Comment by hius07** [comment]
> Sobchak_Enciklopediya-loha.TWthOQ.226848.fb2.zip

It's a good name to save.
It's OK to see it in the file browser Classic mode, and we can have metadata displayed in Detailed list mode if we need.

**Comment by Frenzie** [comment]
@hius07 Yes, but it's "hard" to get, not a quick fix.

You'll get it from the headers as shown above, the third return from request.

```
07/22/20-13:36:14 DEBUG {
    ["content-length"] = "1351104",
    ["content-type"] = "application/zip",
    ["server"] = "nginx",
    ["cache-control"] = "max-age=315360000",
    ["expires"] = "Thu, 31 Dec 2037 23:55:55 GMT",
    ["accept-ranges"] = "bytes",
    ["date"] = "Wed, 22 Jul 2020 11:36:07 GMT",
    ["location"] = "http://static.flibusta.is:443/b.fb2/Igorevich_Pozhiratel.N9Tqhw.588083.fb2.zip",
    ["content-disposition"] = "attachment; filename=\"Igorevich_Pozhiratel.N9Tqhw.588083.fb2.zip\"",
    ["last-modified"] = "Wed, 22 Jul 2020 11:05:37 GMT",
    ["connection"] = "close"
}
```

The most obvious approach is probably some temp file and then to rename it afterward, or alternatively first grabbing the headers for the name and then yet another round trip for the actual saving but that would introduce annoying and unnecessary extra delay.

And I don't know otoh if content-disposition has weird exceptions, etc. ;-)

**Comment by hius07** [comment]
As I know, OPDS Catalog Entry provides full metadata including link to the book.

The feature is well implemented in vlasovsoft CoolReader: when we select a book, at first we have a table showing book information (metadata) and then we can select a format to download.

**Comment by Frenzie** [comment]
Vlasovsoft does what I sketched above.
