### ISSUE TITLE
Note Editor Tweaks

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#6008]
_Backspace too effective_
Yesterday it happened again: After writing a very nice note to an alinea of Schelling's Weltalter, I accidently erased the entire note. Well, not entirely: Just the note, not the quoted/highlighted section.

Could it be that it is actually a feature: Pressing backspace a few times to delete the entire note? It would explain why this has happened at least 3 times in the last half year.

If it is: Could this feature be disabled?

_The window size_
When I am writing a note, I would rather have a very large piece of screen, instead of a tiny window. Where can I tweak this?

**Comment by NiLuJe** [comment]
IIRC, a long-press will delete the current *line*. That might mean the whole note in this context (which I'm not familiar with ^^).

**Comment by Markismus** [comment]
So it _is_ a feature! And pressing enter will prevent it. It's a workaround. Any ideas on how to disable it?

**Comment by NiLuJe** [comment]
What I'm thinking of is tied into virtualkeyboard:

https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/virtualkeyboard.lua#L108-L111

**Comment by Markismus** [comment]
And the window size? Its length(height) is auto sized. If I press enter 10x, rename (save) and reopen, than the window is longer. The width remains smallish.

Anyone know what code defines the width and autolength of the window? Is this something that never bothered anyone before and is just the autosizing of popup windows?

**Comment by poire-z** [comment]
The rename bookmark/highlight just uses the default for InputDialog:
https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/inputdialog.lua#L132-L140
https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/inputdialog.lua#L166
So, it uses a width of 0.8*ScreenWidth:
https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/inputdialog.lua#L202-L215
You can add some of the InputDialog options that you might prefer in there:
https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/apps/reader/modules/readerbookmark.lua#L491-L497

Try with adding `fullscreen=true,`.

**Comment by Markismus** [comment]
@poire-z Brilliant! Thanks.

I've been playing around with the function `InputText:delToStartOfLine()`. Trying to make it erase whole words by changing the "\n" to " ". It leaves the spaces at the beginning of the words, though:
```[lua]
function InputText:delToStartOfWord()
    if self.readonly or not self:isTextEditable(true) then
        return
    end
    if self.charpos == 1 then return end
    -- self.charlist[self.charpos] is the char after the cursor
    if self.charlist[self.charpos-1] == " " then
        -- If at start of line, just remove the \n and join the previous line
        self.charpos = self.charpos - 1
        table.remove(self.charlist, self.charpos)
    else
        -- If not, remove chars until first found \n (but keeping it)
        while self.charpos > 1 and self.charlist[self.charpos-1] ~= " " do
            self.charpos = self.charpos - 1
            table.remove(self.charlist, self.charpos)
        end
    end
    self.is_text_edited = true
    self:initTextBox(table.concat(self.charlist))
end
```

Any idea how to make the function delete that extra space at the ending?

**Comment by poire-z** [comment]
Something along that:
```diff
        -- If not, remove chars until first found \n (but keeping it)
        while self.charpos > 1 and self.charlist[self.charpos-1] ~= " " do
            self.charpos = self.charpos - 1
            table.remove(self.charlist, self.charpos)
        end
+       if self.charpos > 1 and self.charlist[self.charpos-1] == " "  do
+          self.charpos = self.charpos - 1
+           table.remove(self.charlist, self.charpos)
+        end
```

**Comment by Markismus** [comment]
@poire-z Thanks. Works (after changing if...do to if..then.)

I am still rather confused about how `self.keyboard:delToStartOfLine()` refers to `InputText:delToStartOfLine()`. I hoped that I could put `InputText:delToStartOfWord()` next to it, but Koreader crashes rather abruptly.

_On a sidenote._ If I longpress the left mouse button in the textbox, the content of the clipboard is  pasted. Is this another feature?

**Comment by Frenzie** [comment]
Yup, that's a feature. ^_^

**Comment by poire-z** [comment]
> I am still rather confused about how self.keyboard:delToStartOfLine() refers to InputText:delToStartOfLine().

https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/virtualkeyboard.lua#L106-L111

https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/virtualkeyboard.lua#L875-L878
and to where you're at:
https://github.com/koreader/koreader/blob/026140f809cd8f441831bc71dc458f92b8774a62/frontend/ui/widget/inputtext.lua#L491-L510

**Comment by Markismus** [comment]
Thank you!
