### ISSUE TITLE
FR: Dictionary sound files icon

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#6011]
* KOReader version: 2020.03.02
* Device: Kindle PW3 (5.9.7)

#### Issue
Can you please make KOReader replace "*.wav" stings in dictionary entries by a sound icon? I use a stardict dictionary which initially had sound files.

For example here there strings are "bre_quaint.wav", "ame_quaint.wav", and "exa...wav"
![Reader_2020-Mar-25_185708](https://user-images.githubusercontent.com/6279855/77844688-9fd77a80-7176-11ea-98e8-052df10f6687.png)

**Comment by mergen3107** [comment]
Or maybe by sound Unicode character like this one if it can be rendered on all devices (https://www.fileformat.info/info/unicode/char/1f508/index.htm)

Or maybe this *.wav thingy should be completely suppressed if there is no sound support anyway.

**Comment by Frenzie** [comment]
Depends on the sdcv output. Just filtering out `*.wav` could easily have unintended side effects.

If this is an HTML dictionary, see https://github.com/koreader/koreader/wiki/Dictionary-support#html-encoding-within-stardict-dictionaries-supported

**Comment by NiLuJe** [comment]
That's possibly something best left to whatever tool used to author the dictionary?

**Comment by mergen3107** [comment]
I thought it is doable because this is how the same dictionary looks like in Dictionary Universal on iOS:
![00A337DF-BA29-4229-AA16-983C7E050513](https://user-images.githubusercontent.com/6279855/77855270-54948a80-71bd-11ea-934c-df72bf7c3fc8.png)

**Comment by NiLuJe** [comment]
Sure, anything's possible. ;).

I'm just saying I feel like in this particular instance, as @Frenzie said, this may be tricky-ish to get right, so it makes sense to leave that to the authoring tool ;).

**Comment by Frenzie** [comment]
It's possible it's an `<audio>` element in HTML, in which case perhaps we could/should do something with it. I can't say based on a screenshot. But that's close to the only scenario in which we could/should do something imo.

**Comment by Markismus** [comment]
It looks like the same references I found in the Cambridge Advanced Learner's dictionary. They referred to the wave files that are dictzipped next to the dictionary. Those files next to the dictionary are not used by sdcv. So if you want to include them, you have to encode them in base64 and put the string directly into the xml-file of the dictionary.

In my [script PocketBookDic](https://github.com/Markismus/PocketBookDic) I either removed the reference to the wave or I encoded it in base64, so that it could be put inside the dictionary.  (Can't remember whether I wrote that part of the code yet or not. I did write the encoding of images into the xml-dictionary-file.)

However, if you represent the audio with an image you run into the problem that koreader's current mu-pdf version cannot display images based on base64, yet. 

So current state of our art allows you to either use my script and strip all wav-file references or use a lua-script accompanying your dictionary with something like this in the content:
```lua
return function(html)
html = html:gsub('<h?ref[^>]+>.+%.wav</h?ref>', '') 
return html
end
```

**Comment by mergen3107** [comment]
Thank you very much for the info guys!

**Comment by mergen3107** [comment]
I tried this solution:
1) Create a file `Longman Dictionary of Contemporary English 5th Ed.lua` in the same folder, where this dictionary's .ifo file located. The name is the same as that of .ifo file.
The content is as suggested by @poire-z:
```
return function(html)
    html = html:gsub('<rref[^>]+>.+%.wav</rref>', '🔊')
    return html
end
```
2) Restart KOReader, search in dictionary.
However, I can see no visible changes.

@Frenzie, here is the output of sdvc from /mnt/us/koreader/ directory on Kindle: 
```
[root@kindle koreader]# ./sdcv -02 data/dict quaint
Found 2 items, similar to quaint.
-->Longman Dictionary of Contemporary English 5th Ed. (En-En)
-->quaint


quaint /kweɪnt/ BrE bre_quaint0205.wav AmE ame_quaint.wav adjective
[Date: 1100-1200; Language: Old French; Origin: cointe 'clever', from Latin cognitus 'known']
 unusual and attractive, especially in an old-fashioned way:
  exa_p008-000464505.wav a quaint little village in Yorkshire

-->English-Russian full dictionary
-->quaint
...
```
I don't know how to distinguish whether it is an HTML dictionary, nor how to decompose it to look for <audio> tags. How should I proceed?

**Comment by poire-z** [comment]
It does not look like it's a HTML dict.
Look inside the .ifo for `sametypesequence=L` - what's the letter L at the end? h/g/t/... ?
This .lua html function is only checked and used when `sametypesequence=h`.
You should show us some output for some entry where there are actually the .wav stuff you'd like to have removed.

**Comment by mergen3107** [comment]
It says `sametypesequence=x` in the .ifo file.

`You should show us some output for some entry where there are actually the .wav stuff you'd like to have removed.`:
it was there in my previous answer with an example output. Do you want me to show output of some other dict searches?

**Comment by poire-z** [comment]
> it was there in my previous answer with an example output

Oh, right, I was expecting some tags :)
Well, it's as text in the plain text. I guess there's nothing for KOReader to do... We can't distinguish that from any other legitimate text.
I guess that's one case where you should fix your dict content (and I guess if that `exa_p008-000464505.wav` appears like that, it's that dict was converted from some other format).

But... Try just to edit your .ifo and change `sametypesequence=x`  to `sametypesequence=h`. Might be the output is stripped by sdcv!

**Comment by mergen3107** [comment]
Thanks for the tip!
I tried `sametypesequence=h`, and it still does not allow to substitute .wav files, but at least now I can replace BrE and AmE as in the example you showed before: 
```
    html = html:gsub('BrE', '') 
    html = html:gsub('AmE', '') 
```

I tried `audio` instead of `rref`, and it still doesn't substitute. I'll try some other tags too

**Comment by poire-z** [comment]
show us the sdcv output after `sametypesequence=h`

**Comment by mergen3107** [comment]
OK, the same dict search, but with `h` : 
```
[root@kindle koreader]# ./sdcv -02 data/dict/ quaint
Found 2 items, similar to quaint.
-->Longman Dictionary of Contemporary English 5th Ed. (En-En)
-->quaint

<k>quaint</k>
<c c="blue"><b>quaint</b></c> /kweɪnt/ <abr>BrE</abr> <rref>bre_quaint0205.wav</rref> <abr>AmE</abr> <rref>ame_quaint.wav</rref><i><c> adjective</c></i>
<blockquote><blockquote>[<c c="lightcoral">Date: </c><c c="darkgray">1100-1200</c>; <c c="lightcoral">Language: </c><c c="darkgray">Old French</c>; <c c="lightcoral">Origin: </c><c c="darkgray">cointe</c><c c="darkgray"> </c><i><c c="lightseagreen">&apos;clever&apos;</c></i><c c="darkgray">, from </c><c c="darkgray">Latin</c><c c="darkgray"> </c><c c="darkgray">cognitus</c><c c="darkgray"> </c><i><c c="lightseagreen">&apos;known&apos;</c></i>]</blockquote></blockquote>
<blockquote><blockquote> unusual and attractive, especially in an old-fashioned way: </blockquote></blockquote>
<blockquote><blockquote><blockquote><blockquote>  <rref>exa_p008-000464505.wav</rref> <ex>a quaint little village in Yorkshire</ex></blockquote></blockquote></blockquote></blockquote>

-->English-Russian full dictionary
-->quaint
...
```

So the tag around the wav's _is_ `rref`, but still doesn't get substituted.

**Comment by poire-z** [comment]
OK, so now with `=h`, the lua html func gets executed.
It needs some regexp tweaks (untested):
`html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊') `

**Comment by poire-z** [comment]
and you'll want as well to match `<abr>AmE</abr>` and not just `AmE` so "Also abbrviated to AmExpress" does not get stripped to "Also abbreviated to xpress" :)
`html = html:gsub('<abr>AmE</abr>', '') `

**Comment by mergen3107** [comment]
That's wonderful! Thank you very much @poire-z ! It works like a charm now:
![Reader_2020-Mar-30_042122](https://user-images.githubusercontent.com/6279855/77891253-ae896480-723e-11ea-8308-bc1c1cd76747.png)

Moreover, because of `=h` it looks like some default css kicked in (I didn't put a css into dictionary's folder). That's the 'koreader/data/dict.css', right?

Also, I can see that the query word is spelled one extra time in the very beginning. Is that deliberate or I should fix it too? 

--
(here is final `lua` file for those curios from future:)
```
return function(html)
    html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊')
    html = html:gsub('<abr>BrE</abr>', '')
    html = html:gsub('<abr>AmE</abr>', '')
    return html
end
```

**Comment by Frenzie** [comment]
It says it twice:

```xml
<k>quaint</k>
<c c="blue"><b>quaint</b></c> /kweɪnt
```

So you could get rid of that `<k></k>`.

**Comment by mergen3107** [comment]
I see, thank you :)

**Comment by mergen3107** [comment]
I'll add this case to Wiki in the morning

**Comment by poire-z** [comment]
> That's the 'koreader/data/dict.css', right?

Nope, that dict.css is not used by anything.
It's from:
https://github.com/koreader/koreader/blob/2945a2fb79bfb73670363a1fe4ac7f0a1ee0c2c4/frontend/ui/widget/dictquicklookup.lua#L177-L210

and you can tweak that with a .css alonside the .ifo like you did a .lua.

You might want to read @Markismus recent issues, where he tweaks his own dicts, like #5859.

**Comment by Markismus** [comment]
I've looked at Longman 5th edition and the wav-files are >1GB. So that looks uninteresting for use in Koreader. However, I did reconstruct the dictionary with colors and everything:
![Screenshot from 2020-03-30 11-17-27](https://user-images.githubusercontent.com/5269101/77896395-81f23e80-7278-11ea-937a-02edce6852fe.png)
The result can be found [here](https://markismus.stackstorage.com/s/G79N93S0v5bbTSa).

**Comment by mergen3107** [comment]
Thank you for sharing!
I am OK with my minimal changes to .wav and slight css tweaks like margins.

**Comment by mergen3107** [comment]
I added this example into the [Wiki](https://github.com/koreader/koreader/wiki/Dictionary-support/_edit#an-example-of-how-to-apply-this-on-a-dictionary). Guys, could you please have a look and edit for terminology (I might be sloppy especially regarding html/css). Thank you very much for providing such beautiful tweaking opportunities to make even dictionary text look great! :)

**Comment by Markismus** [comment]
@mergen3107 Looks good! Nice to have the dictionary tweaking more accessible.
