### ISSUE TITLE
(Optimalization) news downloader create ".html" output if no images etc is downloaded 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#6012]
* KOReader version: 
* Device: all

#### Issue
Currently ".epub" file is created by news downloader even if it doesn't contain any extra media (images etc). 
Is seems to be waste of time for additional creating file, zipping epub etc. 

How about creating ".html" output file(instead epub) if we download only html?

What you think guys? 

I thought also about new engine + selection engine in settings but it will take too long.. 
Maybe in next pr.

**Comment by Frenzie** [comment]
What exactly do you mean by "seems a waste of time"? If it's anything based on the theoretical concept of performing an extra step that you otherwise wouldn't, stop right there. My CPU is faster than my I/O, which is true on my nearly 6 Gb/s desktop and it's even more true on your average slow af FAT32 interface on an ereader.

**Comment by mwoz123** [comment]
Not sure if I understood you correctly.. 

Do you mean that on ebook readers creating epub will be faster than just dumping received html string to file? (even repeated multiple times)?

I did analysis and see that in addition to images(I was unsure that) epub backed Downloads (expect images) also css and fonts. 
If we'd like to speed up generating news downloader output we could also skip fonts and I'm wondering about css (all my pages looked fine when there was only .html output) so could consider that so it could even faster on "no time to lose" exit home;)
But then this will probably require to change "never download images" to "never download media"..

**Comment by Frenzie** [comment]
> Do you mean that on ebook readers creating epub will be faster than just dumping received html string to file? (even repeated multiple times)?

It's not impossible, but no, that's not at all what I mean. Saying that performing compression and writing the result would be faster based on the theoretical concept that I/O is the bottleneck would be just as wrong.

My guess is it makes no noticeable difference whatsoever, even if one of the two methods were hundreds of times slower than the other. You'd probably need at least a few thousand iterations to reach a humanly-noticeable time span of a couple hundred milliseconds.

> If we'd like to speed up generating news downloader output we could also skip fonts and I'm wondering about css (all my pages looked fine when there was only .html output) so could consider that so it could even faster on "no time to lose" exit home;)

Well, there you have it then. It's your "etc." that's slow, namely downloading stuff, possibly by establishing completely separate connections to boot. Also see #3172.

**Comment by mwoz123** [comment]
Ok if you're sure for around 50-100 downloads (10 sources each 5-10 articles) it won't speed up then please close it
