### ISSUE TITLE
Revise commit fe1fb84: Hide "no framework" buttons on FW 5.x

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#6017]
* KOReader version: 2945a2fb79bfb73670363a1fe4ac7f0a1ee0c2c4
* Device: Kindle Voyage / PW4, may apply to other device models as well

https://github.com/koreader/koreader/commit/fe1fb840639f5086ad0b8b083f5dec27ef3bd40a

I tried it again on my voyage, the no-framework behavior still works. Recent kindle updates make memory usage of native UI be more significant and cause noticeable performance impacts.

**Comment by NiLuJe** [comment]
It's still broken in that suspend won't work, among various other things...

**Comment by Hzj-jie** [comment]
That's weird. Maybe I was using "stop framework" instead?
Do you have the adds?

**Comment by Hzj-jie** [comment]
Interesting, the behavior on PW4 is quite unstable. It may fail sometimes. But voyage works fine. Are you using voyage as well?

**Comment by NiLuJe** [comment]
My own experience was with a PW2 (and/or a PW1 and/or a Touch), FWIW ;).
