### ISSUE TITLE
Cannot turn on Wi-Fi after sleep

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#6019]
* KOReader version: 2020.03.02
* Device: Kindle PW3 (5.9.7)

#### Issue and Steps to reproduce
I am trying to catch a bug. I can't turn on Wi-Fi from KOReader after returning from a long period of sleep.
Here is how usually encounter it:
1) Read in KOReader. Wi-Fi toggling is working fine. Turn Wi-Fi off. Put Kindle to sleep (by magnet cover, or power button, or KOReader's Sleep)
2) After about 5-10 minutes, take Kindle, open the cover. Tap once on the screen to `unlock` (I have set screensavers via KOReader settings), book text appears as usual.
3) Try to turn Wi-Fi on: via gesture "Wi-Fi on", or via top menu. 
4) Wi-Fi is not showing up. Top menu's Network section has no visible changes (no tick mark, 'Network info' still grayed out)
5) Turning off and on several times doesn't help.
6) Now, when I quit KOReader, in Kindle menu's status bar I see `.....` instead of Wi-Fi icon, which usually appears if Wi-Fi is turned on, but no Network was selected yet. Airplane mode shows it is off, meaning that KOReader did properly try to switch Wi-Fi on, but couldn't select the network chosen before.
7) If I turn Airplane on and off, Wi-Fi works. And it does work and toggle properly in KOReader after that until next time I return it from a long period of sleep.

##### `crash.log` (if applicable)
If I am not mistaken about the timing of attempts in crashlog, the crashlog has something related to Wi-Fi.
If it can't connect, it says:
```
--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.728/3.728/3.728 ms
```

If it CAN connect properly, it says something like:
```
--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 68.806/68.806/68.806 ms
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=3.728 ms
```

P.S. Recently, I switched off any Amazon logging on my Kindle, so I don't have anything in /var/log/messages. But if you think I should look these logs, I can do that.

**Comment by NiLuJe** [comment]
It's entirely deferred to the system, so really can't say much without system logs ;).

That said, I doubt there's anything we can do about it.

You could try an extra set of off/on lipc calls in a shell when you trigger it, see if it helps. Not that this could be sanely automated in any shape or form anyway ;).

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/blob/2945a2fb79bfb73670363a1fe4ac7f0a1ee0c2c4/frontend/device/kindle/device.lua#L7-22

One could try going the wifid route directly instead of via cmd?

**Comment by mergen3107** [comment]
OK! Thanks :) I'll see what else I can find

**Comment by mergen3107** [comment]
A small update.
I again caught this bug after a long time sleep. Tried to turn on Wi-Fi - no reaction. Then I went to KOReader's terminal plugin and ran `lipc-set-prop -i com.lab126.wifid enable 1` from [here](https://github.com/koreader/koreader/blob/2945a2fb79bfb73670363a1fe4ac7f0a1ee0c2c4/frontend/device/kindle/device.lua#L20) and it did the trick! Since then Wi-Fi is toggling properly from KOReader, no need to exit to main Menu, and toggle Airplane back and forth. 

I'll revert my Amazon logging later to see details of why it doesn't work after sleep.

P.S. Terminal output window comes up very glitchy, like it has many random patches of pixels of text even from previous pages. It becomes normal only if I grab it and moved around a bit. Is that normal? :D

**Comment by poire-z** [comment]
> Terminal output window comes up very glitchy

Might be fixed in current nightly (#5979, #5985).

**Comment by NiLuJe** [comment]
Might be worth setting both the wirelessEnable 1 property *and* wifid enable 1, then?

(Note to self: order probably ought to be reversed when toggling off, though).

Unless there's a timing issue at play...

**Comment by NiLuJe** [comment]
i.e., does something to this effect help?

```diff
diff --git a/frontend/device/kindle/device.lua b/frontend/device/kindle/device.lua
index 95d6a71d..d76d7965 100644
--- a/frontend/device/kindle/device.lua
+++ b/frontend/device/kindle/device.lua
@@ -11,7 +11,14 @@ local function kindleEnableWifi(toggle)
         lipc_handle = lipc.init("com.github.koreader.networkmgr")
     end
     if lipc_handle then
-        lipc_handle:set_int_property("com.lab126.cmd", "wirelessEnable", toggle)
+        -- Eh. c.f., #6019
+        if toggle == 1 then
+            lipc_handle:set_int_property("com.lab126.cmd", "wirelessEnable", 1)
+            lipc_handle:set_int_property("com.lab126.wifid", "enable", 1)
+        else
+            lipc_handle:set_int_property("com.lab126.wifid", "enable", 0)
+            lipc_handle:set_int_property("com.lab126.cmd", "wirelessEnable", 0)
+        end
         lipc_handle:close()
     else
         -- No liblipclua on FW < 5.x ;)
```

**Comment by mergen3107** [comment]
@NiLuJe, thanks for the suggestion. I haven't tried it yet.
I'd like to catch the logs proper way. I reverted my logging stuff and ran `showlog -f > showlog.txt &` to save logs in background while KOReader sleep.
Then if I see that bug again, I'll apply your fixes and get logs again.

So far I see a lot of `Method has been deprecated`. For example:
```
200403:233827 lipc-set-prop[7473]: W def:lipc:method=LipcOpenEx service=(null):Method has been deprecated.
200403:233828 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.device:Method has been deprecated.
200403:233828 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.kindlepowerd:Method has been deprecated.
200403:233828 lipc-wait-event[7497]: W def:lipc:method=LipcOpenEx service=(null):Method has been deprecated.
200403:233830 luajit: W def:lipc:method=LipcOpenEx service=com.github.koreader.activityindicator:Method has been deprecated.
```
Is that normal?

**Comment by NiLuJe** [comment]
AFAIK, yeah ;).

**Comment by mergen3107** [comment]
Strange, now that I want to catch it with `showlog`, it doesn't happen :D 
So here are logs:
1) Without `device.lua` changes, turning Wi-Fi off before sleep in KOReader, sleep, wake up (from about `line 941`), turning Wi-Fi on. It worked OK and quickly as usually does in working condition.
[showlog.txt](https://github.com/koreader/koreader/files/4430869/showlog.txt)
2) With `device.lua` changes, turning Wi-Fi on and off in KOReader, no sleep though. I don't know if it makes any sense.
[showlog2.txt](https://github.com/koreader/koreader/files/4430870/showlog2.txt)

I'll try to keep catching it in sleep with `device.lua` changes. I'll report if I catch it again.

**Comment by mergen3107** [comment]
@NiLuJe, another update.
1) With the changes you suggested I haven't been able to catch this bug in any case I was catching it before. So I guess the tweak works!

2) Another thing that appeared due to this (or not?) is new things in the crash.log about libraries:
```
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
```

I didn't see such messages before. "Before" is when I haven't apply fixes yet and reverted logging stuff. Do you think it is OK?

**Comment by NiLuJe** [comment]
It definitely was there before ^^. That's the normal output (there might have been a couple less SDL attempts at one point, but the last tweak on that front was a while ago).

----

I'll let it sit for a few days, and if you haven't managed to reproduce it with the tweak, I'll commit it for real, thanks!

**Comment by mergen3107** [comment]
OK, I'll keep you posted!

**Comment by mergen3107** [comment]
@NiLuJe, I didn't catch not a single time when Wi-Fi didn't properly turn on or off from KOReader. Everything is great so far with new settings!
