### ISSUE TITLE
Feature requested

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#6020]
* Device: android
I request following feature in the koreader:
1. When I single tap a word, it just be selected i.e. dictionary dialogue box or context menu must not appear.
2. When I double tap the selected word, then it should show dictionary dialogue box.
Why I need this feature?
When word is selected I will screenshot it. After double tab I will screenshot its meaning. This will help me in learning new words. 
Caution: I know highlight option exists. It will take a lot of time. First highlight then its meaning then un-highlight.

**Comment by pazos** [comment]
There's nothing in this feature request that's specific for the android port.

Also suggested behaviour would break current behaviour for minimal gains. +

Feel free to re-open and unlabel if I missed something.
