### ISSUE TITLE
kosync plugin uses some outdated string methods

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#6022]
* KOReader version: master
* Device: all

#### Issue
It's doing padding with spaces in the string which probably isn't necessary. Reported by #6021.

https://github.com/koreader/koreader/blob/2945a2fb79bfb73670363a1fe4ac7f0a1ee0c2c4/plugins/kosync.koplugin/main.lua#L173-L194

**Comment by robert00s** [comment]
My proposal:
Menu Progress sync -> Whisper sync from:

<img src=https://user-images.githubusercontent.com/22982594/80098296-eb5e2800-856c-11ea-8fd3-b871cfd5bce2.png width=60%>

To:
<img src=https://user-images.githubusercontent.com/22982594/80098323-f4e79000-856c-11ea-8b8f-d2d08c84337f.png width=60%>
<img src=https://user-images.githubusercontent.com/22982594/80098334-fa44da80-856c-11ea-853c-3f962e35c91e.png width=60%>
Auto/Prompt/Disable without leading spaces.

**Comment by Frenzie** [comment]
Fine by me. It could potentially also be shown in the menu above (Sync to latest x: prompt)
