### ISSUE TITLE
ReMarkable: When half asleep, short press on middle button launches KOReader (should require 3 second press)

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#6029]
* KOReader version: 2020.02
* Device: ReMarkable

#### Issue
Short press on middle button when sleeping launches KOReader.

#### Steps to reproduce
1. Install KOReader on the ReMarkable, but close it/run the original device firmware.
2. Do nothing for a while: the device enters its first sleep stage, with a message on the screen telling you to press the middle button to continue.
3. Press the middle button (single press, not hold). This should wake the device and allow you to keep using the device firmware.

What actually happens is that KOReader is launched, despite the press being less than 3 seconds.

It's possible to avoid the issue by using the button on the top of the device to wake it instead of the middle button.

**Comment by pazos** [comment]
@Thra11: the helper used to launch KOReader is hosted in https://github.com/koreader/koreader-base/blob/master/button-listen.c.

Probably ev.time isn't updated during suspend and any key event will pass the threeshold.

**Comment by Thra11** [comment]
If it misses the press completely (because it's asleep) then `press_stamp` will be left at whatever value it was last time it was pressed before sleeping. Perhaps we could reset `press_stamp` to a known/invalid value in the code which handles the release, so we can tell whether we had a press+release pair rather than just the release.

**Comment by pazos** [comment]
@Thra11: feel free to play with the code. I don't have a device to tinker with.

**Comment by NiLuJe** [comment]
And since I don't recall if the system ships with a strace binary, [here's one](http://files.ak-team.com/niluje/mrpub/Other/strace-remarkable.tar.gz) ;).

**Comment by tcrs** [comment]
Turns out I had my GutHub email notifications disabled so didn't see this until now. Looked into it, should be fixed by https://github.com/koreader/koreader-base/pull/1145
