### ISSUE TITLE
Unexpected end of file in dropbear

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#6033]
* KOReader version: 04ca12b (2020-04-08)
* Device: Kobo Aura H2O

#### Issue
Trying to connect to SFTP results in an unexpected end of file error.

The weird thing is Dropbear hasn't been changed in half a year. Maybe something like https://github.com/koreader/koreader-base/commit/f8a3187667c2eb6c70541bbe63f2f21121a28e0f#diff-529fd4d7f1e0adee201bcdb404d7a528 or https://github.com/koreader/koreader-base/commit/82daab94430b5d70664dab7cdf15bb31c9550d51#diff-a514ccba8e0f2d4ff4b9ad2aeddaf80e

Can't experiment atm.

#### Steps to reproduce
Start FTP server and try to connect.

**Comment by NiLuJe** [comment]
FWIW, works on my end (with a standalone setup, same OpenSSH version, newer dropbear).

**Comment by NiLuJe** [comment]
Ah.

That's #6027 ;).

```
/mnt/onboard/.adds/koreader/sftp-server: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
