### ISSUE TITLE
Gestures for jumping to first page and to random page

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6036]
The upcoming version of KOReader will have gestures for jumping to the next or previous bookmark.

In the same vein I would like to suggest gestures for jumping to the first page or to a random page. That last functionality is for example handy for randomly selecting an inspirational text of the day.

In my local KOReader installation I've already incorporated working code for these functionalities:

in readergesture.lua:

    wallabag_download = _("Wallabag retrieval"),
    first_page = _("First page"),
    random_page = _("Random page"),

    [...]

        {"next_chapter", not self.is_docless},
        {"first_page", not self.is_docless},
        {"random_page", not self.is_docless},

    [...]

    elseif action == "first_page" then
        self.ui:handleEvent(Event:new("GotoPage", 1))

    elseif action == "random_page" then

        local last_page = self.view.document:getPageCount()
        local random_page = math.random(1,last_page)
        self.ui:handleEvent(Event:new("GotoPage", random_page))

**Comment by hius07** [comment]
I would be happy to have gestures for jumping to the first page and to the last page of the book.

**Comment by smartscripts-nl** [comment]
Jumping to last page is also easy to implement:

    elseif action == "last_page" then
        local last_page = self.view.document:getPageCount()
        self.ui:handleEvent(Event:new("GotoPage", last_page))

**Comment by smartscripts-nl** [comment]
I thought of an improvement when using these gestures: add the location from which the jump was made to the locations stack. So we can navigate back to that location.

The statement to accomplish that is: self.ui.link:addCurrentLocationToStack():

    elseif action == "prev_bookmark" then
        self.ui.link:addCurrentLocationToStack()
        self.ui:handleEvent(Event:new("GotoPreviousBookmarkFromPage", self:getCurrentPage()))
    elseif action == "next_bookmark" then
        self.ui.link:addCurrentLocationToStack()
        self.ui:handleEvent(Event:new("GotoNextBookmarkFromPage", self:getCurrentPage()))
    elseif action == "first_page" then
        self.ui.link:addCurrentLocationToStack()
        self.ui:handleEvent(Event:new("GotoPage", 1))
    elseif action == "last_page" then
        self.ui.link:addCurrentLocationToStack()
        local last_page = self.view.document:getPageCount()
        self.ui:handleEvent(Event:new("GotoPage", last_page))
    elseif action == "random_page" then
        self.ui.link:addCurrentLocationToStack()
        local random_page = self:gotoRandomPage()
        self.ui:handleEvent(Event:new("GotoPage", random_page))

**Comment by smartscripts-nl** [comment]
The function gotoRandomPage() in the previous comment I've written to ensure each page in the document is only once jumped to when jumping to a random page. Only after all pages have been visited, the random page will be chosen from all pages again, and so on.

        local pages_pool = {}

        function ReaderGesture:gotoRandomPage()

            local last_page = self.view.document:getPageCount()
            local count = 1
            local random_page_index
            local remaining_pages = {}

            -- fill the table with pages to choose from:
            if #pages_pool == 0 then

                repeat
                    pages_pool[count] = #pages_pool + 1
                    count = count + 1
                until count == last_page + 1
            end

            random_page_index = math.random(1, #pages_pool)
            local random_page = pages_pool[random_page_index]

            -- remove the random chosen page, so it will not be chosen again while the currently available pool of isn't empty yet:
            count = 1

            table.remove(pages_pool, random_page_index)

            for k, v in pairs(pages_pool) do

                remaining_pages[count] = v

                count = count + 1
            end

            pages_pool = remaining_pages

            return random_page
        end
