### ISSUE TITLE
Kindle voyage  button problem and fix

### ISSUE THREAD

**Issue by worldGM** [koreader/koreader#6038]
When use koreader in my kindle voyage everything is well except paper up button.

What i found: 
this problem root in kindle voyage system in which we can find "lab126_whisper_touch.lua". When your kindle in the first screen the whisper_touch is disable, but when the second screen of your document which is available.  
If you start koreader using kual which will back to the first screen of your document (home) meanwhile the whisper touch is disable.

**Solution: When you start koreader using kual,  continue tap next page button  when you back to the first screen of your home page. After koreader start back page button also work well.**
👇↓

update:

> here is my solution:
first: add INSERT OR IGNORE INTO "properties" VALUES('com.mobileread.ixtab.kindlelauncher','whisper-touch','supported'); into /var/local/appreg.db use sqlite3 /var/local/appreg.db < whispertouch.install.sql
second: check if kindle voyage do not exit kual menu before koreader starts.
like this :
"name": "Start the filemanager kv",
"if": "\"KindleVoyage\" -m || || || ||",
"priority": 7,
"action": "/mnt/us/koreader/koreader.sh",
"params": "--kual /mnt/us/documents",
"exitmenu": false,
"status": false,
"internal": "status Start KOReader on the File Manager"
here is what I use:
[test.zip](https://github.com/koreader/koreader/files/4466454/test.zip)

can run it using kterm under kindle, then replace koreader/menu.json.

I test many times in my Kindle voyage. Running: 5.9.7

**Comment by pazos** [comment]
duplicate  #5706

**Comment by NiLuJe** [comment]
That's a ... fun workaround :D.

To recap: After launching KOReader via KUAL, right when KUAL exit but before KOReader actually starts (there's a few seconds of stuff happening), simple page next so you're no longer on the first page of your Home/Library when KOReader finally starts.

**Comment by worldGM** [comment]
@NiLuJe But it does work ... although I don't know the complete solution.

**Comment by NiLuJe** [comment]
That's certainly good to know, and someone motivated enough might find that helpful to dig into the root of the issue ;).

**Comment by worldGM** [comment]
[log.txt](https://github.com/koreader/koreader/files/4465821/log.txt)
here is log , i still try to find what happened.

**Comment by worldGM** [comment]
@NiLuJe  problem solved...  I test if you can use back button before koreader finally starts, you can use it as well after it starts. 

here is my solution: 
first: add `INSERT OR IGNORE INTO "properties" VALUES('com.mobileread.ixtab.kindlelauncher','whisper-touch','supported');
` into  /var/local/appreg.db  use sqlite3 /var/local/appreg.db < whispertouch.install.sql

second: check if kindle voyage do not exit kual menu befare koreader starts.
like this `			"name": "Start the filemanager",
			"priority": 1,
			"action": "/mnt/us/koreader/koreader.sh",
			"params": "--kual /mnt/us/documents",
			**"if": "\"KindleVoyage\" -m || || || ||",
			"exitmenu": false,**
			"status": false,
			"internal": "status Start KOReader on the File Manager"`
here is what I use:
[test.zip](https://github.com/koreader/koreader/files/4465860/test.zip)
 
can run it using kterm under kindle, then replace menu.json.

**Comment by NiLuJe** [comment]
IIRC, that's what KPVBooklet already does, and people have reported the same issue there, too, which is why I've never bothered (also, because of potential compatibility issues ;p).

**Comment by worldGM** [comment]
@NiLuJe yeah ~ same as kpvbooklet, what different is authorized KUAL to use whisper touch and keep kual menu before koreader start.  Button of the voyage probably different than oasis which have actually button.

**Comment by NiLuJe** [comment]
Oh, right, I missed the don't exit bit.

Eh, now that most people actually use the Booklet variant, I guess it's less problematic than it used to, I'll look into it later, thanks!

**Comment by worldGM** [comment]
Thank you so much! Hope it can offer some help to the voyage user especially when KPVBooklet can't run as it used to be.
