### ISSUE TITLE
FR: Last access date in History

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6041]
history.lua contains ["time"] for each book (last_read_time).
It would be nice to see this date in the History list (maybe instead of the file size).

**Comment by poire-z** [comment]
That's feasible.
But `["time"]` stores actually the time of book opening.
I guess for the first entry if you're in reader, that's fine and what one would want to see.
But for the others, I guess time of closing (last read) is preferable ?

Note sure how to format it. A date ? A duration in days: `today` `yesterday` `125 days ago` ? a more precise duration `3 h 24 m ago`, `243 d 17 h ago` (might be complicated with translations).
<kbd>![image](https://user-images.githubusercontent.com/24273478/91500905-bcfaab80-e8c4-11ea-8382-1efd3e2ee2ee.png)</kbd>

**Comment by NiLuJe** [comment]
Do we actually store the time of closing somewhere?

(Inquiring minds wants to know, because https://github.com/koreader/koreader/issues/6399#issuecomment-681026114 ;)).

**Comment by NiLuJe** [comment]
But to answer @poire-z's query, I wouldn't necessarily go too overboard, and stick to a `strftime` representation ;).

**Comment by NiLuJe** [comment]
Namely, `%F` and the time according to the existing pref's for 24 vs. 12 format ;).

**Comment by poire-z** [comment]
> Do we actually store the time of closing somewhere?

I don't think so. But mod time of the sidecar file (if it exists) should give it.

About the screenshot, would you drop the file extension ? (it's a bit ugly, I like to see it, but may be it's not that necessary in History ?)

**Comment by NiLuJe** [comment]
No opinion, really, I like my history view in Mosaic mode ;).

But, if I had to say anything, I'd say that, since it's the History, you're supposed to have opened it once, so you're less likely to care about the format?

**Comment by NiLuJe** [comment]
> I don't think so. But mod time of the sidecar file (if it exists) should give it.

:facepalm: Duh!

**Comment by hius07** [comment]
Thank you very much.
1. Plain date-time (no "ago") format is OK.
2. Book format (extension) might be omitted.
3. I keep in history books which were deleted (and purged sdr) so history.lua is the only place keeping the date for all of them.

**Comment by hius07** [comment]
If possible, I'd like to see the date in Classic display mode as well (instead of the file size).

**Comment by poire-z** [comment]
> so history.lua is the only place keeping the date for all of them.

There's also Reading statistics and its various views, expecially the Calendar view to see what you read when.

**Comment by hius07** [comment]
Can the date from history.lua be shown for deleted items?

![Reader_2020-09-01_133820](https://user-images.githubusercontent.com/62179190/91840623-a902d100-ec59-11ea-90df-67d406b132eb.png)

**Comment by poire-z** [comment]
Done in #6618.

**Comment by hius07** [comment]
Thank you very much, I love the History screen now.
