### ISSUE TITLE
(UX) Favorites: add star indicator and availability in History menu

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#6054]
* KOReader version: 2020.03.02
* Device: Kindle PW3  (5.9.7)

#### Issue
Not an issue by itself, just a small inconvenience. 
I noticed this when I couldn't mark a book as favorite from History screen.

#### Steps to reproduce
Long-tap on a book in different file manager windows. I tested only a few variations.

1) File manager, home folder, "Classic mode": surprisingly there are very few options:
![FileManager_2020-Apr-14_222652](https://user-images.githubusercontent.com/6279855/79298548-707f7800-7eaf-11ea-960c-8eee92a13997.png)

2) File manager, home folder, "Detailed mode with metadata and covers": the most complete among other window choices.
![FileManager_2020-Apr-14_222630](https://user-images.githubusercontent.com/6279855/79298568-7bd2a380-7eaf-11ea-8cd3-9ce1395f09d4.png)

3) History, in "Cover mode" or "Detailed mode with metadata and covers": has no "Add to favorites" button. I understand that there is no need in Cut/Copy/Paste from History, but the lack of favorites is a little sad.
![FileManager_2020-Apr-14_222807](https://user-images.githubusercontent.com/6279855/79298590-8a20bf80-7eaf-11ea-96af-f62e89fb7fcb.png)

Just for the uniformity of the UI, is it possible to make the context menus the same for File Managers display modes, and add "Add to Favorites" button to History window?

**Comment by Frenzie** [comment]
> Just for the uniformity of the UI, is it possible to make the context menus the same for File Managers display modes

I think that only means mark as read & add to favorites. The cover stuff makes no sense without covers.

**Comment by mergen3107** [comment]
Yeah, I mean in the reasonable sense. `Add to favorites` is there in classical mode, but `book description` and `Add to favorites` missing. I don't know if `Refresh cached book information` should apply to classical mode. Does only include cover data and metadata? (I get it that metadata is also doesn't apply here, because only filenames are displayed)

**Comment by mergen3107** [comment]
By the way, forgot to ask: Is it possible to add an indication of items added to favorites? Like the indication that the book was opened before (a small "bookmark" icon in the end of the file name bar), but with a star sign, for example?

**Comment by poire-z** [comment]
Classic mode is a bit of a "legacy" display mode: it's the old plain file browser with filenames only, that people get when they disable the CoverBrowser plugin (#2940), that is responsible for the fancy other display modes: it uses a cache of the metadata, so it's easy for it to display covers, and make "view book description" and "view book cover" easily accessible with some buttons it adds/hacks into the classic long-press menu.

Some people don't want any sqlite DB and may have disabled that plugin and keep using that old classic view. But I consider it a bit like a "legacy" mode, and I'm fine if it doesnt get any new features.
We could add to it buttons to show book descriptions and cover, but it would have to do a little bit more expensive work to get them - and would need some work in the plugin so it does not add these buttons, but replace them.

But I guess "Add to favorites" could be available in History - I guess @robert00s didn't think about it when adding Favorites - or it didn't make sense having that in History - as there's no other button here to go access the Favorites list.
For a star sign indicator for books added to favorites, that feels like making sense. Would need to see how costly that can be (I don't use Favorites, I'd rather it to not be slower when it goes checking my empty favorites list).

**Comment by mergen3107** [comment]
@poire-z thank you for explaining! Makes perfect sense

**Comment by poire-z** [comment]
Let's re-open this, at least for the star indicator (and getting the menus coherent should not be too hard) - as it was requested in https://github.com/koreader/koreader/discussions/7185 .
(I'm not planning on doing any work on that soon, so if anybody feels like doing it :)

**Comment by ichnilatis-gr** [comment]
Following the discussion #7185, I give you an example from Poketbook. They use a heart as a mark. Personally, I would prefer another one instead, a star for example...

![scr0001](https://user-images.githubusercontent.com/76203123/105606299-32e63e80-5da1-11eb-9201-70d10f2705a4.gif)

**Comment by NiLuJe** [comment]
The positioning is interesting, although that side is already fairly crowded on our side...

Perhaps something in the spirit of the existing "curled corner" we're using for opened books?

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/master/frontend/readcollection.lua , which handles Favorites, is rather unoptimized for it to be used when file-browsing.
Displaying a little star icon could have been fun, rewritting that module is rather not :/

**Comment by ichnilatis-gr** [comment]
Now that [a progress bar has been added](#8915 ) to the mosaic view thanks to @uroybd, maybe he could have a good idea for a Favorites indicator.

**Comment by poire-z** [comment]
It's not so much about displaying something, which would be the fun/pretty part.
It's about:
> https://github.com/koreader/koreader/blob/master/frontend/readcollection.lua , which handles Favorites, is rather unoptimized for it to be used when file-browsing.
Displaying a little star icon could have been fun, rewritting that module is rather not :/

This module would load/parse the data each time you ask it if a file you're browsing is among the favorites :/ It would need to behave a bit like frontend/readhistory.lua, which keeps a cache.
(I don't think it would be some heavy work, one just have to be interested in Favorites/Collections - which I'm not :)

**Comment by ichnilatis-gr** [comment]
@uroybd thank you in advance for your efforts.

> Perhaps a star (with outline of course so that it is visible on any cover)?

It would be good if the indicator is not only in the mosaic view, but also in the other view types of the file manager.

**Comment by ichnilatis-gr** [comment]
Dear @melyux (and others too) what do you think about this issue? Do you have any idea?
I think it's an issue that has been somewhat forgotten...
Thanks!

**Comment by melyux** [comment]
I'd be cool for a star outline in the top right corner of Mosaic (and maybe doing something about the horrendous "book description" hint too). But I also don't use favorites enough to want to suffer a performance hit for every UI refresh if that's still in the books. List and Mosaic use the cache, so that would have to be used. Classic view is abandonware

**Comment by ichnilatis-gr** [comment]
Since you have added [a marker for books with highlights](#10276), you may want to reconsider adding a marker for books that have been added in Favourites list.

What do you think @hius07 ?

**Comment by ichnilatis-gr** [comment]
Let's think about it again.
Since a marker has been added for the folders in Folder Shortcuts (#11108) and other one for the books that have highlights, might it be a good idea to finally add a marker for the books in Favourites?
If only for the sake of consistency...

**Comment by hius07** [comment]
I hope to improve Collections soon, then maybe.

**Comment by mergen3107** [comment]
> I noticed this when I couldn't mark a book as favorite from History screen.

This was implemented quite some time ago.
