### ISSUE TITLE
Default thumbnail for file types which don't have a thumbnail?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6058]
In the filemanager and in the history files which don't have thumbnails of themselves (e.g. txt-files or shellscripts) are - very logical - displayed without thumbnail.

Especially in the history those files without thumbnail result in an ugly gap between the files _with_ a thumbnail.

Would it be possible to display a default thumbnail for these files? Maybe a white page with the extension as text in that page?

Or maybe the user could even be allowed to assign a thumbnail manually in the contextmenu of these files?

**Comment by poire-z** [comment]
Any strong preference between these ?
Current | With a blank fake cover | With a fake cover with symbol
<kbd>![image](https://user-images.githubusercontent.com/24273478/91480461-5022e980-e8a3-11ea-906f-40d12c41fd92.png)</kbd> - <kbd>![image](https://user-images.githubusercontent.com/24273478/91480350-1eaa1e00-e8a3-11ea-9bce-0185b4fd750b.png)</kbd> - <kbd>![image](https://user-images.githubusercontent.com/24273478/91478932-03d6aa00-e8a1-11ea-81d0-7ffd5911dd35.png)</kbd>

I don't really mind the gap, but a fake cover makes it nicer when there is a description hint (the little bookmark standing out of the top right of the cover).
The middle square is U+26F6 https://graphemica.com/%E2%9B%B6.
Tried a few other symbols that felt too busy.
Adding the file extension would also feel too busy and a distraction (and we have it on the right).
I have a few books that have a blank cover, and the dev I am would like to distinguish them from no-cover, so not fond with having just a blank cover.

**Comment by pazos** [comment]
> The middle square is U+26F6 https://graphemica.com/%E2%9B%B6.

That looks nice!

**Comment by Frenzie** [comment]
I think I prefer the fake cover with something in it; it looks a bit empty otherwise. That specific symbol seems pretty decent.

**Comment by NiLuJe** [comment]
Yep, what everyone else said ;). Go U+26F6 ;).
