### ISSUE TITLE
FR: Dropbox - download folders

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6061]
It would be great to have the possibility to download entire folders from Dropbox.
Thanks in advance.

**Comment by Net-zen** [comment]
Really needed feature. Maybe even one direction sync. Like download everything new (files, folders, subfolders) from the cloud folder into a local folder except exist copies.

**Comment by NiLuJe** [comment]
In the meantime, you can do that manually with rclone and a custom shell script.

**Comment by hius07** [comment]
I didn't mean syncing as in https://github.com/koreader/koreader/pull/5591.
I'd like to able to download from Dropbox in Cloud storage not only a file but a folder (with subfolders, if possible).

**Comment by Net-zen** [comment]
> In the meantime, you can do that manually with rclone and a custom shell script.
It's cool, but I mean this feature in koreader on kindle.

**Comment by pazos** [comment]
> I'd like to able to download from Dropbox in Cloud storage not only a file but a folder (with subfolders, if possible).

No, not possible directly. The API just provides [filesDownloadZip](https://dropbox.github.io/dropbox-sdk-js/Dropbox.html#filesDownloadZip__anchor), which will download the entire folder (=> 20GB >10000files) as a zip file.

The other option is a recursive list_folder -> download file, using the two api calls already used In [dropboxApi](https://github.com/koreader/koreader/blob/master/frontend/apps/cloudstorage/dropboxapi.lua#L14-L15). This option is several orders of magnitude slower than the other one.

Both alternatives are, IMO, bad.

**Comment by hius07** [comment]
> Both alternatives are, IMO, bad.

Thank you, I agree.

**Comment by NiLuJe** [comment]
> It's cool, but I mean this feature in koreader on kindle.

You can run shell scripts from the file manager's long press menu in KOReader. 

(same thing from the favs list, too).

**Comment by Net-zen** [comment]
> You can run shell scripts from the file manager's long press menu in KOReader.
> (same thing from the favs list, too).

wow. didn't know it. thank you, I'll try.
