### ISSUE TITLE
Can't update android package: "Application not installed"

### ISSUE THREAD

**Issue by plague-doctor** [koreader/koreader#6066]
* KOReader version: 2020.04
* Device: Boox

#### Issue

Cannot install latest (2020.04) release `koreader-android-arm-v2020.04.apk`. 
Installation is failing with "Application not installed".
Never had a single problem with earlier versions. Can you double check if the build is really for arm architecture?

**Comment by pazos** [comment]
Yeah, build works fine. It is using the same signature since the first android package

![screenshot](https://user-images.githubusercontent.com/975883/79524705-7e74fa80-8061-11ea-96c4-24b2fce0c815.png)

Please check you're not using the F-droid build in **menu -> help -> bug report** and you have 50MB of storage available

**Comment by plague-doctor** [comment]
Hmmm... I had to uninstall 2020.03 and now I could install 2020.04... Strange.
Yes, I had plenty of space. Way more than 50MB.

**Comment by Frenzie** [comment]
Android's very vague about the reason, could be that we accidentally made the version identifier a downgrade by messing with it.

**Comment by pbienst** [comment]
Similar issue here on a Samsung phone with plenty of storage...

**Comment by pazos** [comment]
> could be that we accidentally made the version identifier a downgrade by messing with it.

@Frenzie: thanks, I forgot that!

**Comment by mabier** [comment]
Yes, I have to uninstall the old version then installation can be successfully made !

**Comment by cges30901** [comment]
> could be that we accidentally made the version identifier a downgrade by messing with it.

versionCode of v2020.04 is 7401, and versionCode of v2020.03.2 is 17365. Maybe this is the reason?

**Comment by Frenzie** [comment]
That's what I was referring to, yes. If you use ADB or Android Studio/AVD then it'll tell you the actual reason. A regular user will be stuck with Android's philosophy that a vague error message is the way to go.

**Comment by tonydiep** [comment]
Still happening for 2020.05 version
