### ISSUE TITLE
One finger gestures not configurable

### ISSUE THREAD

**Issue by lschneiderbauer** [koreader/koreader#6071]
* KOReader version: 2020.04.1
* Device: Remarkable

#### Issue
I tried to deactivate the gestures for scrolling through pages (since the remarkable has buttons), while in reading mode. I set every single one of them to "Nothing" in the settings (even taps, corner swipes, etc.). However, the swipe gestures and taps still change the page.

**Comment by gbyl** [comment]
I have also searched for a way to disable taps when reading as it is too easy to accidentally change the page. [This comment](https://www.mobileread.com/forums/showpost.php?s=e7c59b15b6617cab6acd09bba02dd963&p=3657873&postcount=2) by @Frenzie is the closest I found to a solution

**Comment by hius07** [comment]
(1) Disable touch input, or
(2) Set size of backward/forward zones to 0% in the Taps & gestures menu.
