### ISSUE TITLE
Crash when highlighting scaned pdf in reflow mode

### ISSUE THREAD

**Issue by leoshone** [koreader/koreader#6073]
* KOReader version: 2019.01 ~ 2020.04
* Device: andriod

#### Issue
Crash when highlighting scaned pdf in reflow mode

#### Steps to reproduce
1. download PDF (Pls view PC website if mobile browser)
https://pan.baidu.com/s/1i3ZU7hr?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=

2. open this pdf
3. reflow: on
4. document language: Chinese
5. highlight, crash...

it only crash when set the document language as Chinese.

I tried a lot of versions, maybe this issue was introduced in v2019.01. it's just for your reference.

**Comment by NiLuJe** [comment]
Quite likely related to #4481 (and/or other PDF + CJK issues).
