### ISSUE TITLE
Include table of contents info into book field when exporting highlight to JSON

### ISSUE THREAD

**Issue by RCoeurjoly** [koreader/koreader#6074]
#### Feature request

Right now a JSON export looks like this:

{"1":[{"page":272,"time":1579730286,"sort":"highlight","text":"highlight content"}],"2":[{"page":272,"time":1579730316,"sort":"highlight","text":"highlight content"}],"file":"\/storage\/emulated\/0\/Books\/Microsoft Word - Kurzweil, Ray - The Singularity Is Near.doc - Administrator.pdf","exported":{"txt":true,"html":true},"title":"Microsoft Word","author":"Kurzweil, Ray - The Singularity Is Near.doc - Administrator"}

The desired result is:

{"1":[{"page":272,"time":1579730286,"sort":"highlight","text":"highlight content"}],"2":[{"page":272,"time":1579730316,"sort":"highlight","text":"highlight content"}],"file":"\/storage\/emulated\/0\/Books\/Microsoft Word - Kurzweil, Ray - The Singularity Is Near.doc - Administrator.pdf","exported":{"txt":true,"html":true},"title":"Microsoft Word","author":"Kurzweil, Ray - The Singularity Is Near.doc - Administrator", "toc":{ [
        "name": "Paragraph 1",
        "type": "h1",
        "children": [
            {
                "name": "Paragraph 1.1",
                "type": "h2",
                "children": []
            }
        ]
    },
    {
        "name": "Paragraph 2",
        "type": "h1",
        "children": [
            {
                "name": "Paragraph 2.1",
                "type": "h2",
                "children": []
            },
            {
                "name": "Paragraph 2.2",
                "type": "h2",
                "children": [
                    {
                        "name": "Paragraph 2.2.1",
                        "type": "h3",
                        "children": []
                    }
                ]
            }
        ]
    }
]}}

I will most probably implement this myself

**Comment by poire-z** [comment]
Looks like implemented by #6146.
