### ISSUE TITLE
koreader don't do user request if need connect to the wifi

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#6080]
* KOReader version: v2020.04.1-1-***_2020-04-19
* Device: Kindle pw3

#### Issue
if your kindle not connect to wifi and you try to do something that need internet (for example update or translate) it show a dialog box that ask you to turn on modem but after that koreader close that dialog box but don't do user requested action.
so user should repeat that step again
#### Steps to reproduce
1. wifi should be off
2. go to menu > update > check for update
3. dialog box ask for turn on wifi so press turn on
update don't start  until you repeat step 2 again
#### Expected behavior
after step 3 it should do this steps
4. show small icon in corner that show device try to connect wifi
5. if device connect to wifi ,icon update to an wifi icon with a check mark .if it not show a wifi icon with X mark on it.(program should go to step 6 but hide icon after 2 or 3 second)
6. koreader do the command that user request (translate or update or any other action that need internet)

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/issues/2706 and probably more very old Wireless manager design discussions for some more background on this.

**Comment by mergen3107** [comment]
Yeah, after you hit "Yes", it takes about 5-8 seconds before it connects correctly. Actually, this window which asks about Wi-Fi is promising only to... turn on Wi-Fi. So you should hit "Yes", wait for 10 seconds, then try to update again.

**Comment by NiLuJe** [comment]
The lack of feedback is specific to platforms where we defer wireless handling to the system. Most prominently Android/Kindle.

On a Kobo, you'd see the scanner pop up, auto-connect & everything.

You still need to re-do the action yourself, though, which is what I was getting at ;).

**Comment by Monirzadeh** [comment]
> The lack of feedback is specific to platforms where we defer wireless handling to the system. Most prominently Android/Kindle.
> 
> f.g., on a Kobo, you'd see the scanner pop up, auto-connect & everything.
> 
> You still need to re-do the action yourself, though, which is what I was getting at ;).

i agree with you lac of feedback and You still need to re-do the action yourself is so annoying
spacialy on an e-ink display.

**Comment by WaseemAlkurdi** [comment]
> The lack of feedback is specific to platforms where we defer wireless handling to the system. Most prominently Android/Kindle.

Why do we do that though? Doesn't the Kindle use a standard `wpa_supplicant`? Is there anything preventing KOReader from using command-line tools to control Wi-Fi?

**Comment by NiLuJe** [comment]
> > The lack of feedback is specific to platforms where we defer wireless handling to the system. Most prominently Android/Kindle.
> 
> Why do we do that though? Doesn't the Kindle use a standard `wpa_supplicant`? Is there anything preventing KOReader from using command-line tools to control Wi-Fi?

Kindle.

Android.

PocketBook.

**Comment by NiLuJe** [comment]
As far as the Kindle is concerned, I have no idea, because WiFi and Kindle don't mix in my world ;).

If you've got something that works there, PRs welcome ;).

**Comment by WaseemAlkurdi** [comment]
> Interoperability. OTOH, on, at least:
> 
> Kindle.
> 
> Android.
> 
> PocketBook.
> 
> You'll notice those are platforms where we don't replace the stock system, we just live off its back like a tick ;p.

Reading this, the surprise to me was that there are platforms where KOReader _does_ replace the stock OS!
> As far as the Kindle is concerned, I have no idea, because WiFi and Kindle don't mix in my world ;).

That makes me think ... if KOReader replaces the Kindle framework, won't that be hitting two birds with one rock, (almost) solving the issue of the non-free userspace and all the privacy invasion issues, while at the same time providing a Wi-Fi picker and so forth?
So far the only issue I know is that on newer firmware versions, the Kindle relies on the Amazon framework to enter sleep when hitting "the button". (Though it can enter sleep after the timeout even without the framework). If there are no issues indeed, then I will be more than happy to contribute that "isolation" from userspace! :-D

**Comment by NiLuJe** [comment]
@WaseemAlkurdi: Not viable on Kindle FW >= 5.x, all hell breaks loose without the stock UI.

**Comment by WaseemAlkurdi** [comment]
@NiLuJe Now that you said it ..
But at least a Wi-Fi picker should be possible ... I'll poke around, and if I find anything, I'll hack up something!
(I'm sure that you can at least list + connect to networks using `wpa_cli` ... but how that applies to Kindle is something I'll find out ...)

**Comment by pazos** [comment]
Err, the PR I just sent does not close this issue. Just make possible to test network state changes in the emulator.

But a proposal like https://github.com/koreader/koreader/pull/6299/commits/58d619be2bd9837c8709f04bbfa598e14a5da1d4 could work. Basically we return early from actions that need internet and set the function as a pending action. `OnNetworkConnected` we check if there is any pending actions and execute them, so the workflow is not interrupted.

**Comment by poire-z** [comment]
Auto-enable/disable WiFi without prompt is now possible since #6424.
