### ISSUE TITLE
save sentence as an example to dictionary history

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#6082]
* KOReader version: v2020.04.1-1-***_2020-04-19
* Device: Kindle pw3
please add this feature
if you translate or look up dictionary for a  word, koreader save the sentence that contain that word as example in lookup history
it is so useful for review and learn new words, something similar kindle flash card function

**Comment by NiLuJe** [comment]
Err, top menu > Search > Dictionary lookup history?

**Comment by Monirzadeh** [comment]
yes.
it can be helpful to review them on device and #6081 if it possible.

**Comment by deklanw** [comment]
@Monirzadeh This is a great idea! Getting realistic sentences for flashcards etc would be very useful.

**Comment by mingoc** [comment]
This is an important feature I am missing coming from a Kindle user.

**Comment by poire-z** [comment]
People interested in that should now use the new Vocabulary builder - and context will be added by #9195.
