### ISSUE TITLE
Writing a Plugin for KOReader

### ISSUE THREAD

**Issue by P0oOOOo0YA** [koreader/koreader#6084]
Happy to know that someone has written another reader for kindles. I was thinking about writing a DSL (Domain Specific Language) on top of highlight-note feature of kindle readers to convert several highlights into Q/A of a card (For a Spaced-repetition system). Sadly couldn't find any guide on writing plugins for KOReader. So i have to ask it here. 

## Scenario

A user press and hold on an image within a book. (Let it be in EPUB format which i think is the easiest one to start with). Some menu appears with a button named **Add metadata**. When the button is clicked another window appears with the following contents and a button named **Append to clippings**:

````yaml
img:
   path: /path/to/image/inside/epub
   # user can add more meta here 
````

After user hits **Append to clippings** button, i want the window contents to be appended to the `My clippings.txt` or its alternative in KOReader environment.

Please guide me in the right directon.

**Comment by Frenzie** [comment]
The plugin part basically just means it can be disabled. It's possible that there might need to be some adjustments in the main program code to enable the scenario you describe but it's probably not as formalized as your question seems to imply.

There's the hello world sample plugin:
https://github.com/koreader/koreader/blob/aa4bcd8c22a21d2d60a7ca0845f62fb81420d894/plugins/hello.koplugin/main.lua

And here's a semi-random more advanced one:
https://github.com/koreader/koreader/blob/aa4bcd8c22a21d2d60a7ca0845f62fb81420d894/plugins/texteditor.koplugin/main.lua

**Comment by mwoz123** [comment]
btw is the "hello" plugin disabled ?
I've never seen this one. In plugin management also can't find it.
is it again 
`  menu_items.hello_world = {` vs dir name `hello.koplugin` ?

**Comment by poire-z** [comment]
No, the names and directory names are coherent. No problem with the menu_items slot name I think, which can be different.
I guess it's just because `plugins/hello.koplugin/main.lua` contains at top:
https://github.com/koreader/koreader/blob/eaabc42ea9337b160fd15c311bdbcf9fdc121ea4/plugins/hello.koplugin/main.lua#L1-L4
