### ISSUE TITLE
Feature request : ability to save preset backlight settings and invoke them via gesture manager

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6085]
* KOReader version: April 2020
* Device:

#### Issue

I often find myself switching between my night time setting (inverted text low brightness ) with my day time setting (regular white background black text with max front light setting ) in the morning. 

While I’ve previously suggested schedules to automatically change setting based on time of day that idea didn’t attract any interest. I’m wondering if this method would.  You could attach a gesture to a saved backlight setting and then easily toggle with one command to set the settings to your preferred state.

**Comment by mzelyony** [comment]
I second this. I'd also suggest to combine this with the warmth preset on those devices that have this feature, and make this feature available in the tap/swipe actions, so that I can alternate between the two settings with 1 tap

**Comment by arooni** [comment]
Yay it's not just me lol.  Would love to see schedule support too down the line.  😛

**Comment by yparitcher** [comment]
This is now available via profiles, soon to be integrated for gestures
