### ISSUE TITLE
Can't login to Evernote

### ISSUE THREAD

**Issue by flacchini14** [koreader/koreader#6087]
* KOReader version:  2020.04.1
* Device: Pocketbook HD 3; PB632

#### Issue
Can't login to Evernote
#### Steps to reproduce
Open Epub or PDF -> Login to Evernote -> An error occurred while loggin in:
plugins/evernote.koplugin/EvernoteOAuth.lua:320: Target URL was not found in the response on login

**Comment by flacchini14** [comment]
I just got startet with Pocketbook and KOReader. 
Have also Problem with the WLAN Connection. After few seconds, WLAN disconnects. 
I will start the reader again and then wait to get the crash.logs again. Then I will post it here:

**Comment by flacchini14** [comment]
The last two attempts:

 [*] Current time: 04/24/20-14:06:31
 [*] Version: v2020.04.1

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
04/24/20-14:06:31 INFO  SoftwareVersion:  U632.6.0.926
04/24/20-14:06:31 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
PB FB: smem_len    : 1552384
PB FB: line_length : 1448
PB FB: xres        : 1448
PB FB: xres_virtual: 1448
PB FB: yres        : 1072
PB FB: yres_virtual: 1072
PB FB: bpp         : 8
PB FB: xres_virtual -> 1472
PB FB: yres_virtual -> 1152
PB FB: line_length -> 1472
PB FB: yres_virtual => 1088
PB FB: line_length <- 1448
PB FB: xres_virtual <- 1448
PB FB: yres_virtual <- 1072
FB: computed size: 1552384
FB: id           : 
FB: smem_len     : 1552384
FB: line_length  : 1448
FB: xres         : 1448
FB: xres_virtual : 1448
FB: yres         : 1072
FB: yres_virtual : 1072
FB: bpp          : 8
Atached mp shm: id 0 addr a6f42000 size 17608
epdc_default_init
attach_shm: mtfb key=251336134 size=1666724
Atached mtfb shm: id 59000b addr a4451000 size 1666724
-------------------------
The task - koreader.app fb 0xa4451000
 xres=1448 yres=1072 scanline=1456 vdepth=8 orient=1
-------------------------
attach_shm: ref key=2130378752 size=1560832
Atached ref shm: id 8001 addr a394d000 size 1560832
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 10720000 0 -10000 0 10000 0
ffi.load: inkview
04/24/20-14:06:32 INFO  initializing for device PBTouchHDPlus
04/24/20-14:06:32 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[5584 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
04/24/20-14:06:33 INFO  opening file /mnt/ext1/Books/Himmelfarb, Gertrude/the de-moralization of society from victorian virtues to modern values - Gertrude Himmelfarb.epub
04/24/20-14:06:33 INFO  Loading plugins from directory: plugins
04/24/20-14:06:33 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/24/20-14:06:33 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load (assisted searchpath): ./libs/libz.so.1
ffi.load: sqlite3
04/24/20-14:06:33 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/24/20-14:06:33 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
04/24/20-14:06:33 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
04/24/20-14:06:33 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
CRE: styles re-init needed after load, re-rendering
[5666:24/04/20 14:06:41] netagent called with parameters < disconnect >
04/24/20-14:22:20 WARN  got error waiting for events: Waiting for input failed: 4

---------

 [*] Current time: 04/24/20-14:43:13
 [*] Version: v2020.04.1

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
04/24/20-14:43:13 INFO  SoftwareVersion:  U632.6.0.926
04/24/20-14:43:13 INFO  Blacklisting the C BB on this device
Tweaking LuaJIT's max loop unroll factor (15 -> 45)
PB FB: smem_len    : 1552384
PB FB: line_length : 1448
PB FB: xres        : 1448
PB FB: xres_virtual: 1448
PB FB: yres        : 1072
PB FB: yres_virtual: 1072
PB FB: bpp         : 8
PB FB: xres_virtual -> 1472
PB FB: yres_virtual -> 1152
PB FB: line_length -> 1472
PB FB: yres_virtual => 1088
PB FB: line_length <- 1448
PB FB: xres_virtual <- 1448
PB FB: yres_virtual <- 1072
FB: computed size: 1552384
FB: id           : 
FB: smem_len     : 1552384
FB: line_length  : 1448
FB: xres         : 1448
FB: xres_virtual : 1448
FB: yres         : 1072
FB: yres_virtual : 1072
FB: bpp          : 8
Atached mp shm: id 0 addr a6f7f000 size 17608
epdc_default_init
attach_shm: mtfb key=251331716 size=1666724
Atached mtfb shm: id a800d addr a448e000 size 1666724
-------------------------
The task - koreader.app fb 0xa448e000
 xres=1448 yres=1072 scanline=1456 vdepth=8 orient=1
-------------------------
attach_shm: ref key=2130378752 size=1560832
Atached ref shm: id 8001 addr a398a000 size 1560832
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 10720000 0 -10000 0 10000 0
ffi.load: inkview
04/24/20-14:43:14 INFO  initializing for device PBTouchHDPlus
04/24/20-14:43:14 INFO  framebuffer resolution: {
    ["h"] = 1448,
    ["w"] = 1072
}
[1164 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
04/24/20-14:43:15 INFO  opening file /mnt/ext1/Books/Himmelfarb, Gertrude/the de-moralization of society from victorian virtues to modern values - Gertrude Himmelfarb.epub
04/24/20-14:43:15 INFO  Loading plugins from directory: plugins
04/24/20-14:43:15 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
04/24/20-14:43:15 INFO  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load (assisted searchpath): ./libs/libz.so.1
ffi.load: sqlite3
04/24/20-14:43:15 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
04/24/20-14:43:15 INFO  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
04/24/20-14:43:15 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin calibrecompanion at plugins/calibrecompanion.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
04/24/20-14:43:15 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
CRE: styles re-init needed after load, re-rendering
[1195:24/04/20 14:44:10] netagent called with parameters < disconnect >
04/24/20-14:44:22 WARN  got error waiting for events: Waiting for input failed: 4

**Comment by NiLuJe** [comment]
In this case, the Evernote issue is likely related to the WAN issue.

probably.

Who knows. PB + Evernote == double-whammy of in dire need of maintainers ;).

**Comment by iyner629** [comment]
I have exactly the same issue
KOReader version: 2020.04.1
Device: Kobo Aura One

**Comment by nykrphguy123** [comment]
Same issue here!
KOReader version:  2020.04.1
Device: Kobo Clara HD

**Comment by NiLuJe** [comment]
@iyner629 & @nykrphguy123 

Logs, please.

**Comment by nykrphguy123** [comment]
> @iyner629 & @nykrphguy123
> 
> Logs, please.

[crash.log](https://github.com/koreader/koreader/files/4553624/crash.log)

**Comment by NiLuJe** [comment]
@nykrphguy123: The only crash in there is a NewsDownloader one, back on the 22nd of April :?

**Comment by Galunid** [comment]
@NiLuJe I believe it to be generic issue with EvernoteOAuth, I replicated it on 3 different devices(Kindle PW3, Kobo Clara HD, Emulator), while working on #6138. I added a bit of logging to the library: https://pastebin.com/raw/DLSfbNj4
I have no idea why server responds with code 418(I'm a teapot) though. This was run on emulator, with empty login/password. Results didn't really seem to change even if I entered correct credentials.

**Comment by Galunid** [comment]
[evernote_oauth.patch.txt](https://github.com/koreader/koreader/files/4640257/evernote_oauth.patch.txt)
I include my patch(as .txt, because github doesn't seem to like .patch)

**Comment by Galunid** [comment]
It seems evernote changed its authentication workflow(https://dev.evernote.com/doc/articles/authentication.php). 
Changing `login = "/Login.action",` to `login = "/OAuth.action",` did the trick and I was able to login. I've opened pull request in sdk https://github.com/koreader/evernote-sdk-lua/pull/2/

**Comment by Tsiung** [comment]
> It seems evernote changed its authentication workflow(https://dev.evernote.com/doc/articles/authentication.php).
> Changing `login = "/Login.action",` to `login = "/OAuth.action",` did the trick and I was able to login. I've opened pull request in sdk [koreader/evernote-sdk-lua#2](https://github.com/koreader/evernote-sdk-lua/pull/2)

it work for Evernote，but it dont work for 印象笔记（yinxiang，Evernote，china）。
the error is plugins/evernote.koplugin/EvernoteOAuth.lua:280: Target URL was not found in the response on login
