### ISSUE TITLE
Android installs with generic icon

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#609]
How can the android installation make use of the koreader icon?

**Comment by pazos** [comment]
Just an idea :P

![koreader](https://cloud.githubusercontent.com/assets/975883/7420141/55d0924c-ef7a-11e4-94d3-c32aabfe84b8.png)

Don't blame me! new at inkscape

**Comment by embryo10** [comment]
Well, whats wrong with the original logo?
If you make it a little more 3D
![koreader 300 3d](https://cloud.githubusercontent.com/assets/8684739/7429580/657a82b0-f00c-11e4-8182-e7f96025cb16.png)
or put it on a book?
![koreader 300 book](https://cloud.githubusercontent.com/assets/8684739/7429582/70c74d9c-f00c-11e4-9e69-b0eb9812bbd7.png)

**Comment by Markismus** [comment]
Since koreader has dictionary support for Fraktur, I don't suppose it is suggesting anything it is not capable of.

**Comment by chrox** [comment]
And finally we have this one:
![icon](https://cloud.githubusercontent.com/assets/751535/8153851/1ee4408e-1366-11e5-8863-270caee1b90f.png).

**Comment by hwhw** [comment]
I like it! It's nice in grayscale, too.
