### ISSUE TITLE
Feature request: separate eink refresh rate for regular and night modes

### ISSUE THREAD

**Issue by kzshantonu** [koreader/koreader#6094]
Would be nice. For example, on my pocketbook touch hd 3, full refresh every 6 pages is fine in regular mode, but need to manually refresh every 2 pages in night mode, or change refresh rate every time I switch modes

**Comment by NiLuJe** [comment]
That kind of stuff would usually get chucked into https://github.com/koreader/koreader/pull/5079

I think @arooni may have opened a FR similar to this one recently, too...
