### ISSUE TITLE
Feature request: arrows to navigate to previous/next day in day view invoked from calendar view

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6104]
Would it be possible to have arrows to the right and to the left to navigate to the next/previous day in the day view as invoked from the statistics calendar view?

As it is now I have to first navigate back to the month view to be able to view the statistics for another day. That feels a little bit clumsy.

Or maybe it would even be possible to navigate to another day by swiping to the right or the left?

**Comment by poire-z** [comment]
A bit hard to do, sorry.
(the bottom arrows and horizotal swipes are managed by the KeyValuePage for the display of this day's books - which may have arrows when there were more than ~10 books read that day - so it would need some support for additional callbacks when you go before/after these internal "pages", and some ugly work in CalendarView to provide these callbacks, compute the next or prev day, etc...)
