### ISSUE TITLE
Progress bar disappears

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#6109]
* KOReader version:v2020.04.1
* Device:kobo clara hd

#### Issue
Progress bar at the bottom disappeared every time when I open the book. 
I enable it by checking "show progress bar" every time.

**Comment by Frenzie** [comment]
Could you please share a bit more about your specific statusbar settings?

**Comment by abdrau26** [comment]
Progress bar is not shown while it is checked.
![IMG_20200503_025754](https://user-images.githubusercontent.com/59373108/80893261-30f7bf00-8cea-11ea-80c4-7241e76897ef.jpg)
![IMG_20200503_025842](https://user-images.githubusercontent.com/59373108/80893272-4371f880-8cea-11ea-8fde-61112401e097.jpg)

**Comment by NiLuJe** [comment]
It might just be cycled to the "hidden" state, which the Menu won't really tell you about.

Tap it, make sure it displays one of your items (or all of 'em if in "all at once" mode), close the book, re-open it.

**Comment by abdrau26** [comment]
@NiLuJe 
It is not working

**Comment by NiLuJe** [comment]
Details, please.

**Comment by NiLuJe** [comment]
A copy of your settings file (*.adds/koreader/settings.reader.lua*) might also be helpful.

**Comment by abdrau26** [comment]
File attached herewith

**Comment by abdrau26** [comment]
Link attached herewith

**Comment by abdrau26** [comment]
https://drive.google.com/file/d/11RZxiMXi9vduASfG48OfGXlvwd-AlAc6/view?usp=drivesdk

Link of settings.reader.lua file

**Comment by NiLuJe** [comment]
```lua
["reader_footer_mode"] = 0,
```

It's indeed cycled to the hidden state.

**Comment by abdrau26** [comment]
@NiLuJe 
Solved. Thank you very much
