### ISSUE TITLE
Feature request: horizontal splash screen when starting KOReader with landscape ebook

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6110]
I like to read my ebooks in landscape, two column lay-out. However, when I start KOReader the splash screen telling me which ebook is being opened is always displayed in portrait orientation.

It would be nice if this splash screen would also be displayed in landscape orientation when the ebook that KOReader loads when it starts up will be displayed in landscape orientation.

**Comment by NiLuJe** [comment]
The FM doesn't support Landscape orientations (at all, currently).

**Comment by NiLuJe** [comment]
Wait, when you say "start up", do you *actually* mean start up? i.e., when KOReader is setup to boot on the last opened document?

**Comment by smartscripts-nl** [comment]
Indeed, that is what I meant.

**Comment by NiLuJe** [comment]
You didn't follow the issue template, so I don't know the device you're talking about, but I'm assuming it's a Kobo.

Then, no, can't fix, we require booting in Portrait for both performance reasons, and to make sure input translation is handled properly.
