### ISSUE TITLE
Expose search icons immediately on the long-press menu

### ISSUE THREAD

**Issue by protist** [koreader/koreader#6111]
* KOReader version: 2020.04.1
* Device: Kobo H2O

#### Issue
I'm currently reading a foreign book, and I find the names extremely hard to remember. Hence, I'm having to search once every few minutes, to remind myself of who is who. To search, I have to navigate the long-press menu, and then select search. It would be much more convenient to have the search buttons directly exposed on this long-press menu.

#### Current usage
1. Long press a word
2. Touch `Search`
3. Use the arrows

#### Preferred usage
1. Long press a word
2. Immediately use the `Search` arrows

#### Rationale
Currently, there are six icons exposed when long pressing a word. I don't use most of them.
* Double arrows: what do these even do? They always seem greyed out for me.
* Highlight: I _do_ use this occasionally, maybe ~3 times per book.
* Wikipedia: I never use this.
* Follow link: I never use this. Isn't this just identical to (short-) pressing a word?
* Search: In my current book, I'd use this >50 times. In a normal book, I'd probably use it ~6–10 times. Not a massive amount more than any other button, but it's definitely my most-used function.

Adding the search icons directly to the menu would add four icons, but lose one. On my device, there would be plenty of room for that.

After a search was initiated, the pop-up window could then be reduced to the minimal four-icon window, obscuring less of the page. (As an aside, I sometimes find even this small window covers important text. I'm not so sure how easy it is, but IMO a better option would be to crop the main text view, and move the popup to the top or bottom edge.)

**Comment by poire-z** [comment]
I assume that with "icon" and "menu", you mean the button table at the bottom of the dictionary lookup result window.

> Double arrows: what do these even do? They always seem greyed out for me.

They allow navigating lookup results, when the word is found in multiple dicts - I assume you only have one.

> Follow link: I never use this. Isn't this just identical to (short-) pressing a word?

Yes, when you tap on a link. But one can disable "tap on link to follow link". This allows this person to still follow the link.

> As an aside, I sometimes find even this small window (the 4 arrow buttons to navigate search occurences) covers important text

You can move it around yourself, at top, at bottom. Long-press on it makes it translucent.

> To search, I have to navigate the long-press menu, and then select search. It would be much more convenient to have the search buttons directly exposed on this long-press menu.

I'm surprised you're not even bothered by the time it takes to show up, as it must do a dict lookup before showing you the dict results with these buttons at the bottom :)

Anyway, your issue might probably be solved with adding `Search` to `Gear > Document > Highlight action >` - which currenly does not have it.
It's for highlights, meaning you should highlight multiple words, or long press 3 seconds on a single word - or, trick: long-press on one word, grab one before or after, get back on first word.

>  a better option would be to crop the main text view, and move the popup to the top or bottom edge.

Which might crop out the place where the occurences are found (or cause a full book re-rendering if you're thinking about temporarily reducing the page height). Better to let that to the users to move the 4 arrows tables where it finds it convenient.

**Comment by protist** [comment]
Thank you @poire-z for all that useful information!

> But one can disable "tap on link to follow link".

Nice. That's good to know too.

> You can move it around yourself, at top, at bottom. Long-press on it makes it translucent.

Aha! Thank you. This works for me, but on my Kobo H2O, long pressing has no visual effect. The pop-up doesn't change opacity. I can then drag my finger somewhere else, but there is still no visual feedback. Only after I release does anything change visually, with the pop-up immediately moving to the new position.

> I'm surprised you're not even bothered by the time it takes to show up, as it must do a dict lookup before showing you the dict results with these buttons at the bottom :)

Yes that's true, but is there a way to disable the dictionary lookup? I guess with the `Highlight action` action if that were implemented?

> Anyway, your issue might probably be solved with adding `Search` to `Gear > Document > Highlight action`

Hmmm, that's a reasonable solution given the current infrastructure. Ideally I'd like the longer press for the menu/dictionary, and the shorter press for the search. Or incorporating/customising search directly into the shorter-press menu/dictionary, as per my initial comment. But I understand that the `Highlight action` solution might be the easiest to implement.

> if you're thinking about temporarily reducing the page height

Yeah, that's what I was thinking, but I wasn't sure how intensive an action this might be (hence "I'm not so sure how easy it is").

Thanks again!

**Comment by poire-z** [comment]
> long pressing has no visual effect

Forgot to say that this works only to make it translucent when the button table is in its initial position (you should be careful to not move your fingers, otherwise it's considered a move).
When you have moved it, long-pressing-without-moving instead brings it back to its initial position (I thought this was more handy, after you have moved it) - and then, you can long-pressing-without-moving to make it translucent.

For what you wish, I guess some options could be added to that menu and in the following bit:
https://github.com/koreader/koreader/blob/ce3bf473da8e7b15a981f58e5a28959e1fe41ba6/frontend/apps/reader/modules/readerhighlight.lua#L965-L997
to:
- add a menu option/setting to do as if hold_duration > 3s even if not in the first bit, to skip dict lookup and go to the highlight buttons table directly
- add search to default_highlight_action possible values, to call:
https://github.com/koreader/koreader/blob/ce3bf473da8e7b15a981f58e5a28959e1fe41ba6/frontend/apps/reader/modules/readerhighlight.lua#L1219-L1226

**Comment by protist** [comment]
> Forgot to say that this works only to make it translucent…

Hmm, on my device that pop-up is *never* translucent, even in the first move.

On a related note, I thought there might be other hidden koreader settings I'd missed since the last time I looked, so I went through all of them again. I discovered I could disable the "flash" screen refresh with almost zero ghosting on my device, so I did that. Now everything feels so much snappier!

In terms of the PR, thank you so much for the quick work! However, TBH I'm finding it a bit fiddly. Firstly, holding a word for three seconds is reasonable in theory (and works well in the PR), but after I've turned off the flash/refresh, it's actually quicker to just hold a word for one second, then tap search. (Part of this might be that I don't get any obvious visual feedback after holding for three seconds, so I'm doing some guesswork. If I aim for >3 seconds, I might hold for 5 seconds sometimes, whereas if I aim for >1 second, I probably only hold for 2 seconds max.) I also can't get this working consistently either: `trick: long-press on one word, grab one before or after, get back on first word`.

So ideally I'd still prefer being able to search as the primary (quicker) action. For example, having the search buttons in the dictionary panel. (This panel actually doesn't take much time to load now with the flash/refresh off). Or alternatively, the ability to customise the shorter and longer holds, so the short hold would search, and the longer hold would bring up the dictionary and other options, including highlight, etc.

**Comment by poire-z** [comment]
> Firstly, holding a word for three seconds is reasonable in theory (and works well in the PR), 

> So ideally I'd still prefer being able to search as the primary (quicker) action

That's what the PR is about - to _not_ have to hold 3s when you check the first menu item:
<kbd>![image](https://user-images.githubusercontent.com/24273478/80921250-84631f00-8d75-11ea-86fb-8d4dc0f1a6dc.png)</kbd>

**Comment by protist** [comment]
Oops! Sorry about that. Yes, okay that makes sense now. I had the original, slightly-buggy `.zip`, and now I've installed the newer version. However, I can't seem to access my menu now to check these settings. I'm getting a crash every time with the following in the log:
```
05/04/20-19:58:43 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
05/04/20-19:58:43 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
05/04/20-19:58:43 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
./luajit: frontend/ui/elements/common_settings_menu_table.lua:1: '=' expected near 'DateWidget'
stack traceback:
	[C]: in function 'dofile'
	frontend/apps/reader/modules/readermenu.lua:146: in function 'setUpdateItemTable'
	frontend/apps/reader/modules/readermenu.lua:371: in function '_getTabIndexFromLocation'
	frontend/apps/reader/modules/readermenu.lua:392: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
	frontend/ui/uimanager.lua:736: in function 'sendEvent'
	frontend/ui/uimanager.lua:175: in function '__default__'
	frontend/ui/uimanager.lua:1076: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1137: in function 'handleInput'
	frontend/ui/uimanager.lua:1181: in function 'run'
	./reader.lua:298: in main chunk
	[C]: at 0x000140c1
!!!!
Uh oh, something went awry... (Crash n°3: 05/04/20 @ 19:58:45)
Running FW 4.3.8945 on Linux 2.6.35.3-850-gbc67621+ (#3032 PREEMPT Mon Jan 9 13:37:40 CST 2017)
Attempting to restart KOReader . . .
!!!!
```

**Comment by poire-z** [comment]
Probably some typo when you edited the file (or you didn't get the right files).
Here's [highlight_search_singleword2.zip](https://github.com/koreader/koreader/files/4573990/highlight_search_singleword2.zip) with the latest files.

**Comment by protist** [comment]
Ack, okay thank you. Sorry, I blame my mental state on the lockdown! 😅

Yes, that works now. The short hold works perfectly with the settings in your [screenshot](https://github.com/koreader/koreader/issues/6111#issuecomment-623311496). However, is there still a way to get the dictionary/highlight/etc.? Long holding or dragging a multi-word selection seems to still bring up the search menu.

**Comment by poire-z** [comment]
You can set a gesture to cycle through the 5 actions + ask with popup dialog.
But I guess that yes, we could have a long-press > 3s directly bring the popup dialog.

**Comment by protist** [comment]
Thanks again @poire-z. IMO the latter option is better, because it can leverage both of the two different inputs, and as opposed to having to tap an extra 3 times on average.
