### ISSUE TITLE
Enable rotation event with Portrait mode only

### ISSUE THREAD

**Issue by hungtaday1309** [koreader/koreader#6116]
* KOReader version: V2020.04.1
* Device: Kobo Forma

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Not yet implemented:

https://github.com/koreader/koreader/blob/eaabc42ea9337b160fd15c311bdbcf9fdc121ea4/frontend/device/input.lua#L700-L701

**Comment by poire-z** [comment]
Solved by #6347.
