### ISSUE TITLE
Kindle PW4 freeze after exit from KOReader

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#6117]
* KOReader version: 2020.04.01
* Device: Kindle PW4

#### Issue
A user from 4pda forum reports that PW4 freezes after exiting from KOReader.
Logs files from Kindle and KOReader are attached. Hang is visible AFAIK from line 18895 in `all_system_logs` (I just compared the timestamps, there are 17 minutes different)

#### Steps to reproduce
Read a book (allegedly from latest logs, a djvu book);
Exit KOReader;
Kindle freezes.

##### `crash.log` (if applicable)

[4pda KOReader logs.zip](https://github.com/koreader/koreader/files/4575880/4pda.KOReader.logs.zip)

**Comment by NiLuJe** [comment]
An actual idea of which one's supposed to be a hang (i.e., a rough timestamp) would be helpful ;).

Because the final entry is perfectly sane, since there's a ;dm dump done right after.

**Comment by NiLuJe** [comment]
Hmm, the nest to last startup is suspicious, though. It appears to have been using an older, buggy startup script.

My best guess would be the vfat proxy fucked up during an OTA.

A reboot should clear things up.

**Comment by mergen3107** [comment]
One guys says that this problem is definitely thr case on Kindle FW 5.12.5. I understand that it’s not your concern to support all FWs, but probably we should add a warning on KOReader installation instructions for Kindle to stay away from 5.12.x if possible?

**Comment by NiLuJe** [comment]
There's a giant warning about that in the JB thread already, which is linked to in the KOReader instructions :/.

I'm getting a wee bit miffed about people getting burned when clearly playing with fire they've been warned about...

**Comment by NiLuJe** [comment]
I mean, the last guy I had to repeat that to answered something along the lines of "cool. I've updated anyway". `>_<"`.

**Comment by mergen3107** [comment]
@NiLuJe 
Ah, ok! Thank you :) 
Yeah, it is really annoying sometimes

**Comment by NiLuJe** [comment]
That said, in this specific instance, the log clearly shows the startup script not running properly in one run and then properly in the other.

That's typical of the fuse proxy delaying an update because of a held lock. It's been an issue since basically forever on Kindle. The startup script takes some precautions to try to avoid that, but, apparently, shit still happens.

**Comment by NiLuJe** [comment]
(Incidentally, that's why the post-OTA on-screen message essentially reads "reboot if shit happens" on Kindle ^^).

**Comment by NiLuJe** [comment]
Well, actually, it says something slightly nonsensical, let me at least fix that ^^.

**Comment by mergen3107** [comment]
Thank you so much for your careful investigation! :)

**Comment by NiLuJe** [comment]
I still don't see any actual hang in the logs, though.

The last run is perfectly sane and leads to the ;dm, the previous one is followed by a cover close + USBMS session and stuff kicking around as usual.

**Comment by NiLuJe** [comment]
(Meaning, if hang there are, I'd still be mildly interested in actual logs of the *right* thing, ideally with a rough timestamp and history).

**Comment by mergen3107** [comment]
A little more feedback from the user. 
1) They tried to reinstall manually, no change: it sometimes freezes. 
2) If it doesn’t freeze, the Kindle menu draws out slowly (not sure how interpret this). 
3) They suppose that the major reason might be wmctrl changes from March 16-17.
4) They also suppose this might be a PW4-specific problem. 

I asked them to try to get more specific logs and timestamps when these things occur again. 

I am sorry if I am punching the dead end already, just trying to see if there is still a chance to fix this.

**Comment by mergen3107** [comment]
New logs from the same user: system froze on May 6, 2020, around 22:45 o'clock. This is line 17071 in all_system logs. I also asked them to run `showlog -f > log1.txt &` before a possible freeze, which they did as far as I see. So the `log1.txt` shows everything right before the freeze. 

What I noticed is that after reboot there are waayyy too many complaints from Whispersync. Looks suspicious as if there problems to reconnect to Wi-Fi network.
[4pda2.zip](https://github.com/koreader/koreader/files/4591850/4pda2.zip)

**Comment by NiLuJe** [comment]
Okay, that one certainly looks like a deadlock, as the logs are cut-off, I don't even see the KOReader exit.

Couple questions: is this a SO device? Is the deep sleep thingy enabled?

And, yeah, the WiFi stuff on resume looks fishy, but then we both know Kindles are very good at looping like stupid idiots when stuff goes wrong, so, eh :/.

**Comment by mergen3107** [comment]
@NiLuJe
It is non-SO device; yes, Deep Sleep is turned on

**Comment by NiLuJe** [comment]
Hmm, I'd suggest trying without deep sleep then ;).

**Comment by mergen3107** [comment]
Ok, I’ll keep you posted. Thank you!

**Comment by mergen3107** [comment]
Further feedback from the user. They turned off the deep sleep, but the issue is still here. Freeze happened around the line 19014.
[4pda3.zip](https://github.com/koreader/koreader/files/4600490/4pda3.zip)

And they still suspect that the main reason might be changes with wmctrl in March.

**Comment by mergen3107** [comment]
Forgot to mention: when it froze, Kindle drew home menu but without the status bar.

**Comment by NiLuJe** [comment]
That one is useless, I can see a reboot, and that's it.

The WhisperSync flood doesn't help ;).

And, no, this is definitely unrelated to wmctrl, if it were, it would be easy to pinpoint, like the timing quirks were in the original implementation.

**Comment by NiLuJe** [comment]
Probably requires SSH access, to confirm whether something actually crashes/deadlocks, or if it's just a dumb softlock for some reason.

**Comment by mergen3107** [comment]
So for SSH way, what is the best method to catch these logs?

**Comment by NiLuJe** [comment]
`showlog` ;).

**Comment by hius07** [comment]
We have more reports from PW4 5.12.5.
KOReader freezes while exiting and trying to redraw Kindle home screen and the top bar.
It definitely began after https://github.com/koreader/koreader/pull/6009.
We are waiting for more logs from the users.

**Comment by NiLuJe** [comment]
IIRC, wmctrl may hang if the WM is still stopped. WHich shouldn't happen, but, who knows.

Definitely need someone with shell access to figure out what's actually happening.

**Comment by NiLuJe** [comment]
The causal link with #6009 is problematic in that it was commit a month before 5.12.5 actually came out, and behaved just fine on 5.15.4, according to initial feedback ;).

(It certainly works fine on 5.9.7).

**Comment by hius07** [comment]
Yes, some devices on 5.12.4 have the same issue.
Downgrading to 5.10.1.3 solves the issue.
By now we have at 4pda.ru at least 4 reports confirming freezing. Waiting for the logs.

As one of them advised, deleting wmctrl commands from koreader.sh solved the issue.

**Comment by mergen3107** [comment]
@NiLuJe 
Can you please re-open this issue? 
I can’t find such button. 
The issue is definitely present and consistent, we are just waiting for new logs

**Comment by mergen3107** [comment]
Thank you :)

**Comment by hius07** [comment]
One more ;dm log, the device became frozen at about 200513:120500.
[Logi.zip](https://github.com/koreader/koreader/files/4622252/Logi.zip)

**Comment by NiLuJe** [comment]
Same deal, truncated logs (with a perfectly timed log rotation, to add insult to injury ;p).

i.e., I don't need any more logs, I need someone with shell access to check what's actually hung ;).

FWIW, at least the previous startup went just fine as far as wmctrl is concerned, so, there's that...

**Comment by mergen3107** [comment]
@NiLuJe 
Some side notes from the user's feedback.
They changed the line 242 in koreader.sh to:
`if [ "$(version "${FW_VERSION}")" -ge "$(version "5.7.2")" ] && [ "$(version "${FW_VERSION}")" -lt "$(version "5.12.4")" ]; then`
They say that with this change and wmctrl disabled, there are no issues on exit. I told them that this is not a solution but merely a downgrade with possible return of reappearing of the top bar items. 
Asked them to get real-real logs from ssh.

**Comment by mergen3107** [comment]
@NiLuJe 
New logs from the user using ssh. Freeze happened around 16:41 (line 176012 in `log3.txt` file) without the top bar being drawn. 

[4pda4.zip](https://github.com/koreader/koreader/files/4649986/4pda4.zip)

**Comment by NiLuJe** [comment]
Hmm, well, the good news is, wmctrl worked.

There might be an invisible focus-stealing popup pissing on the parade, though...

I don't know if we have a programmatical way of dealing with that... (I'd try a simple goto home via lipc).

**Comment by NiLuJe** [comment]
Everything related to navigation should be around `com.lab126.appmgrd`. Maybe another `lipc-set-prop com.lab126.appmgrd start app://com.lab126.booklet.home` will help, or something along the lines of `lipc-set-prop com.lab126.appmgrd backward 0`might work, too.

Or forcing a screen refresh via fbink, who knows: `fbink -fs`

**Comment by mergen3107** [comment]
OK, thank you! I told them about possible solutions. They will probably experiment

**Comment by mergen3107** [comment]
The user tried to put these three options one by one right before the line 
`if [ "${INIT_TYPE}" = "upstart" ] || [ "$(uname -r)" = "2.6.31-rt11-lab126" ]; then`

It still “hangs”, i. e. becomes unresponsive after exit. `fbink` option though draws correctly the menu and the top bar, but it is still unresponsive.

**Comment by NiLuJe** [comment]
That's... not what I had in mind ^^.

Those were basically beginning of clues to look into in a shell session to figure out what might be happening. not stuff to brute-force blindly ;).

**Comment by mergen3107** [comment]
Oops :) take two…

**Comment by NiLuJe** [comment]
Granted, it's a bit a tough ask for Joe Random.

I'm afraid it's typically the kind of Kindle crap I could only really ever debug with the actual device myself :/.

**Comment by mergen3107** [comment]
We can at least try :) 
Meanwhile, there are already around 5 people with auch issue on 4pda, so I think we have chances to gather proper logs :D

**Comment by mergen3107** [comment]
So I bombarded the 4pda forum with set of instructions on how to catch these logs. Hopefully (for PW4 owners) someone else will join too

**Comment by idirizzo** [comment]
So, I only can resolve this issue by downgrading PW4  to 5.10.1.3 solves the issue as I understand from your topic. I only today first time have installed jailbreak and KOreader, so sad :(

**Comment by idirizzo** [comment]
I have installed koreader-kindle-v2020.05 instead of koreader-kindlepw2-v2020.05 on my pw4 and the issue disappeared. I will keep an eye for the app. Thanks

**Comment by NiLuJe** [comment]
That's unlikely to make any difference.

**Comment by idirizzo** [comment]
But it finally fixed my issue :) maybe i miss some files which i have added then copied from second folder.  i have deleted the folder koreader in root and replaced files in jailbreak folder. Maybe something here helped me

**Comment by NiLuJe** [comment]
What actually has a slightly slimmer chance of having made a difference is the fact you did a clean install.

**Comment by idirizzo** [comment]
> What actually has a slightly slimmer chance of having made a difference is the fact you did a clean install.

Sad news, its again freezzing after exit. How can i help you resolve this issue?

**Comment by mergen3107** [comment]
@idirizzo there is discussion of the same issue on [4pda](http://4pda.ru/forum/index.php?s=&showtopic=541019&view=findpost&p=96807621).
Basically you need to catch logs using ssh during this event. The command to start logging is `showlog -f > log1.txt` .

Then, when it "freezes", try to send these commands, by one per each occasion to keep it separate:
`lipc-set-prop com.lab126.appmgrd start app://com.lab126.booklet.home` or
`lipc-set-prop com.lab126.appmgrd backward 0` or 
`fbink -fs`

Then attach these logs here

**Comment by mergen3107** [comment]
@NiLuJe 
The original user of this issue says that `lipc-set-prop com.lab126.appmgrd start app://com.lab126.booklet.home` didn't help to un-freeze.
Here are logs, he says it froze at around 17:53 (but I don't see a restart at that time, maybe you can see more)
[4pda5.zip](https://github.com/koreader/koreader/files/4697592/4pda5.zip)

**Comment by NiLuJe** [comment]
@mergen3107: If users hard-reboot (as opposed to, say, launching a graceful reboot in shell, (or, simply restarting the gui, `restart lab126_gui` (OTOH) should do it. Interest is minimal, as it's barely any faster than a cold reboot), then I would expect logs to get truncated (and, as such, rendered useless).

**Comment by NiLuJe** [comment]
Worth checking out in a shell is whether other random process are still SIGSTOP'ed.

The WM, `awesome`, *should* have been waken up at this point, but, who knows.

**Comment by mergen3107** [comment]
@NiLuJe 
Thank for comments! I suggested them to try these to commands to reboot i stead of hardware reboot. 

How should they check SIGSTOP things? Via a `ps -a`?

**Comment by NiLuJe** [comment]
`htop` or `top`, by the `S` field, set to `T` ;).

**Comment by Abish4i** [comment]
I **downloadgrade** KO to **v2020-02** its working fine idk where the bug is but _(temporarily fix)_
and there one other thing when running latest build of **ko** you cannot connect your device to **PC** as no device is mounted or **KINDLE drive is** greyed out

**Comment by NiLuJe** [comment]
@Abish4i: That's by design, to avoid everything blowing up in horrible ways.

**Comment by Abish4i** [comment]
Has this issue been fixed ? :- I have hardware so I can check app crashes or not + {send the link with latest commit incorporated)

**Comment by Abish4i** [comment]
> @NiLuJe
> Thanks Issue is fixed just checked it.

Is there a way to keep gestures intacted with manual update?

**Comment by Abish4i** [comment]
> I have installed koreader-kindle-v2020.05 instead of koreader-kindlepw2-v2020.05 on my pw4 and the issue disappeared. I will keep an eye for the app. Thanks

Maybe it's just was a FW code conflict 
And Still I don't understand diffrence 
b/w
Appimage linux version & KPW2

**Comment by NiLuJe** [comment]
It hasn't been "fixed. I just swept it under the rug with https://github.com/koreader/koreader/pull/6204.

**Comment by idirizzo** [comment]
Yeap, i still can reproduce this after deep sleep. But i can't configurate my kindle to download logs. Kindle still asking me about password when i trying to connect via putty. I didnt have time to investigate this issue, sorry.

**Comment by Abish4i** [comment]
I replaced my koreader.sh with the raw file & viola there is no freezing flawlessly exiting (thx for magic code)

**Comment by pazos** [comment]
closed issues are still watched. Don't hessitate to comment here!

**Comment by easyrider** [comment]
> I replaced my koreader.sh with the raw file & voila there is no freezing flawlessly exiting (thx for magic code)

@Abish4i, 
what file did you use? From the latest build?
