### ISSUE TITLE
Reorganize PDF bottom menu config panels

### ISSUE THREAD

**Issue by poire-z** [koreader/koreader#6122]
Not often reading PDF, but giving some thoughts about / asking if the bottom menu could may be be reorganized.

For CRE documents, we moved some stuff in the Font size panel (#6112)
<kbd>![image](https://user-images.githubusercontent.com/24273478/81046886-951cad80-8eb9-11ea-942d-b13d64c1050b.png)</kbd>

--

It looks to me we could do the same (and more) for PDF, and make the rightmost one smaller:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81046981-c1d0c500-8eb9-11ea-9650-395b2bef1ae7.png)</kbd>

I guess `Reflow` (which actually is the one that enables the font size widgets - correct me if I'm wrong) could be moved in there, with `Word Gap` (for consistency with the CRE changes):
<kbd>![image](https://user-images.githubusercontent.com/24273478/81047048-edec4600-8eb9-11ea-8ff8-3410126a8f47.png)</kbd>

And may be `Dewatermark` (which I use to remove grayness) (and `Render Quality`?) could be moved to this one:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81047166-2a1fa680-8eba-11ea-953c-7a35eb4d7327.png)</kbd>

Dunno if one or two from this one could find a place in one of the others:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81047483-c6e24400-8eba-11ea-8b3c-c17743bf6e17.png)</kbd>

Thoughts?

**Comment by hius07** [comment]
As we go increasing from left to right everywhere, isn't it logical for "off" to be the leftmost item?

**Comment by Frenzie** [comment]
@poire-z Yes, I've thought that basically every time I play around with reflow but forget about it before I can get around to changing it because I don't use reflow.

**Comment by poire-z** [comment]
> isn't it logical for "off" to be the leftmost item

I agree.
Dunno if we should, as people may get used to the current layout and visual patterns of what's selected :)
But if we are reorganizing them all, that might be the occasion - and shuffle these users' habits once.

That would change:
CRE `Embedded Styles: off | on`
CRE `Embedded Fonts: off | on`
PDF `Reflow: off | on`
PDF `Dewatermark: off | on`
PDF `Force OCR: off | on`

I guess we can keep
`View mode: continuous | page` (as page mode does more than continuous, browsers don't do pages) - unless continuous shows more content ?

Dunno about:
CRE `Progress bar: full | mini` ??
PDF `Page crop: manual | auto | semi-auto | none` (none should be left, dunno about the orders for others)

**Comment by hius07** [comment]
Great reorder! Seems that:
page < continuous
mini < full
none < manual < semi-auto < auto

**Comment by NiLuJe** [comment]
I don't read PDFs, but that sounds sensible ;).

**Comment by yparitcher** [comment]
`Page crop: none | auto | semi-auto | manual`

**Comment by poire-z** [comment]
> CRE Progress bar: full | mini ??

**Comment by poire-z** [comment]
> CRE Progress bar: full | mini ??

Well, full & mini are misleading... as our bottom status bar can be bigger and have more info than crengine's top status bar.
Should we rename to `top | bottom` ?

**Comment by poire-z** [comment]
Another thing which might be a question of taste, but instead of these unnumbered Aa Aa Aa:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81166552-0b8dde00-8f94-11ea-86ef-fb4744d69663.png)</kbd>

I have this in my own patch: show numbers, which makes it easier to go back to previous values, see how your sight get worse... than having to remember I was on the 4th from the right and count them:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81166053-5b1fda00-8f93-11ea-8210-5ba78a3517af.png)</kbd>
(In my defaults.persistent.lua, I have reduced the available sizes to up to 23 - so I don't see these huge ugly numbers :)

For PDF:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81166203-9fab7580-8f93-11ea-9943-c1cdf1ff8dbc.png)</kbd>

**Comment by hius07** [comment]
If I choose full, I can tap the bottom of the screen and have both top and bottom bars.
If I choose mini, I cannot have top bar.
So the actual menu action is Top status bar: off | on
Minibar is always accessible.

**Comment by Frenzie** [comment]
> Should we rename to top | bottom ?

That's misleading too in the sense that it's probably not too complicated to add a switch to put the one we draw at the top. (Not that I'm personally interested in doing so or anything.)

**Comment by Frenzie** [comment]
Agreed, numbers are clearer if slightly less pretty.

**Comment by hius07** [comment]
> instead of these unnumbered Aa Aa Aa:

Great, numbers instead of Aa's!

**Comment by poire-z** [comment]
> That's misleading too in the sense that it's probably not too complicated to add a switch to put the one we draw at the top. 

(As misleading as naming this app KOReader - as it's probably not too complicated to rename it to "BAReader" ? :)

What about @hius07 suggestion: `Top status bar: off | on` ?

**Comment by Frenzie** [comment]
Something like alt or built-in could work.

**Comment by poire-z** [comment]
Could show:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81182287-e4440a80-8fad-11ea-9798-f305b1ccfe65.png)</kbd>

**Comment by hius07** [comment]
Alt Status Bar can be customized via cr3.ini, isn't it?

**Comment by poire-z** [comment]
OK, for PDF, I had a try at understanding all the options, and reorganize them by topic.
Those of you more confortable than me with PDF handling, please correct or enlighten me :)

Those in grey are all only enabled when `Reflow` is `on`.

2nd panel (crop, margins)
<kbd>![image](https://user-images.githubusercontent.com/24273478/81182552-37b65880-8fae-11ea-967f-a3ff7f153966.png)</kbd>
- Now includes `Margin` (should it be plural?) (moved from 3rd panel) as it's after Page crop (who has cut it rough to the edges of content) that you apply some margin that makes it bearable.
- Put there `Columns` (from the 3rd panel), but I don't know, it's just for detection, not really related... but not much at home in other panels. (Also, it avoids the underlining to show which is selected to be eaten by the Alignment one on low-DPI devices/emulator.)

3rd panel (view & line layout)
<kbd>![image](https://user-images.githubusercontent.com/24273478/81182871-a8f60b80-8fae-11ea-9ca3-30a373f34ade.png)</kbd>
- Moved `Page Gap` just below `View mode`, as it is enabled only when Scroll/Continuous mode is selected
- `Line spacing` and `Alignment` (of lines) only apply to Reflow'ed text (`Line spacing` is currently always enabled, but I couldn't make it have effect when Reflow off - can some of you do? Should it be disabled when Reflow: off ?)
- Moved `Columns` out as it has really nothing to do there: it's about detection, not visual output (if you have a 2 columns PDF, you need it set to 2 columns - if set at 1 column, you'll have reflowed lines mixed with stuff from the 2 columns - you'll never get reflowed visual output in 2 columns, but always 1 full width column).

4th panel (font & words)
<kbd>![image](https://user-images.githubusercontent.com/24273478/81183445-7993ce80-8faf-11ea-9dbb-b9b8971acfec.png)</kbd>
- All other toggles are only enabled when `Reflow: on`. Many other stuff in other panels are also only enabled when `Reflow: on`, but putting `Reflow` there makes it more obvious that it is the magic toggle.

5th panel (contrast, image quality)
<kbd>![image](https://user-images.githubusercontent.com/24273478/81184250-7b11c680-8fb0-11ea-9a54-82b36d5b6360.png)</kbd>
- `Dithering` is HW dithering, only there on capable devices.
- `Render Quality` only affects Reflow'ed text, the quality of the font rendering but also the quality of word splitting and text layout. Could find its place in 4th or 6th toggle...

6th panel (OCR and stuff)
<kbd>![image](https://user-images.githubusercontent.com/24273478/81184542-ccba5100-8fb0-11ea-93b9-0426fa8aa7d7.png)</kbd>
- `Document Language` helps OCR, although I dunno what the `Forced OCR` does.
- `Writing Direction` affects Reflowed text direction layout

For the record, that 6th panel has/had 3 other not-shown options:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81185014-5cf89600-8fb1-11ea-8924-ef9693b2dfa0.png)</kbd>
- `Speckle ignore size` stuff might work, although using other than `small` may eat some words or punctuations
- Couldn't make `Auto straighten` (which would be nice! even in non-reflow mode) and `Indentation` have any kind of effect.

Might be the occasion to add `help_text = "this does that"` to all of these. Who feels like writting prose? :)

(Could be nice to have the top menu `Switch zoom mode>` stuff available at the bottom with icons, for consistency.)

**Comment by Frenzie** [comment]
@poire-z Regarding the help, see https://www.willus.com/k2pdfopt/help/options.shtml (that's the same as k2pdfopt --help)

**Comment by mergen3107** [comment]
Sorry guys for a late feedback, but doesn’t it sound natural to put everything Reflow-related to the same page with Reflow toggle? Moreover, how about moving all reflow stuff to its own separate tab?

**Comment by poire-z** [comment]
> doesn’t it sound natural to put everything Reflow-related to the same page with Reflow toggle? Moreover, how about moving all reflow stuff to its own separate tab?

Because that would make a panel with 8 items, and I mostly want them all to be around 3 or 4 items, to give more room to the page under to see the effect of each toggling.
So, yes, we could split these 8 in 2 4-items panels, but we'd have to find new tab icons :) Anyway, if you can think of some grouping like that that makes sense, I'm listening.

But keeping them organized by topic (with some disabled if reflowed off) is a less radical change I think.

**Comment by poire-z** [comment]
Done in #6131.
Those of you used to reading PDFs, please review, especially my understanding and english in the `help_text = [[This does that]]`. Thanks.
