### ISSUE TITLE
Feature request: Clean out history or book list - removing completed books

### ISSUE THREAD

**Issue by jonndoe47pp** [koreader/koreader#6124]
I have quite a few books on my device and browsing through them takes ages > 1000. One of my bad habits is starting multiple books, is there a way to tidy the history OR the book list to remove finished books and only show started or unread books. Or just to remove all books that have been read ?

**Comment by Frenzie** [comment]
You didn't say which device this is on, but if you have too many files in one folder chances are you're likely running into filesystem performance, which isn't exactly great on Kobo and even worse on Kindle.  The basic solution is to use more subfolders.

**Comment by jonndoe47pp** [comment]
Sorry, the device is a Likebook mars version is koreader-android-arm-v2020.02.apk.

The reason I want the history cleared is that I use the filebrowser and the history in different ways. The filebrowser to start a new book to read and the history browser to continue reading a book. I don't always remember to remove a book and I sometimes manually delete from the sd card a book outside of koreader, so having functionality that say shows the book name, total pages and pages read so you could manually go through to delete???? As a plugin? Just suggesting it, if it's unfeasable, fair enough. Thank you.

**Comment by pazos** [comment]
> I don't always remember to remove a book and I sometimes manually delete from the sd card a book outside of koreader.

If you remove a book from the sdcard (always outside ko as we don't have write permissions there)  it will be shown translucent on the history list. A long press on top of that book (or any other book) will show a menu with a bunch of options. The last option is called "clear history of deleted files" and will remove deleted books from history.

If you want to remove books from the primary storage you can check **delete** in "gear" -> "documents" -> "end of document action". This won't delete them in the SDcard.

**Comment by jonndoe47pp** [comment]
Thank you , I will close this you have been more than helpful in your answers. If in the future you get to choose columns for the file browser or history that would be awesome but for now it's just wishful thinking.
