### ISSUE TITLE
History entry isn't removed when there is a manual deletion

### ISSUE THREAD

**Issue by jonndoe47pp** [koreader/koreader#6125]
* KOReader version: koreader-android-arm-v2020.02
* Device: likebook mars

#### Issue

Historic entry persists when manual deletion occurs

#### Steps to reproduce

Delete book outside koreader. Launch koreader, history entry is still present though "greyed out" to indicate missing book. Could there be a way to remove historic entries of deleted books?

**Comment by poire-z** [comment]
Long-press on any book present in the History, and you'll get `Clear history of deleted files` at the bottom of the menu.

**Comment by Frenzie** [comment]
There's also an auto-remove deleted items from history setting. It's in other settings under file manager display mode.
