### ISSUE TITLE
Can't add URLs to Wallabag

### ISSUE THREAD

**Issue by fazlerabbi37** [koreader/koreader#6129]
* KOReader version: 2020.04.1
* Device: Android

#### Issue
I can't add URLs to Wallabag. Gives the following error:
```
Error adding link to Wallabag: $URL
```
Then on tap comes the seccond message:
```
Please configure the server and local settings
```

#### Steps to reproduce
1. Config Wallabag plugin by editing `settings/wallabag.lua` file
2. Open a document
3. Tap on any link
4. Tap 'Add to Wallabag`

**Comment by fazlerabbi37** [comment]
> The fact that it says $URL

Sorry for the confusion, I used it as a made up variable name to hide the URL. :disappointed: 

> I've also attached a document in which the links work for comparison.

Same result. If I click the first link of the document (online version) it shows:

```
Error adding link to Wallabag:  https://fr.wikipedia.org/wiki/Da_Vinci_Code
```
on second tap comes:

```
Please configure the server and local settings
```

**Comment by Frenzie** [comment]
In that case something's missing in the configuration, either on the server or on the device. Please see https://github.com/koreader/koreader/wiki/Wallabag for the documentation. You need all four, username, password, client ID and client secret. It's a bit weird, I know. ;-)

**Comment by fazlerabbi37** [comment]
> Please see https://github.com/koreader/koreader/wiki/Wallabag for the documentation.

I followed this one and made sure that have all 4 username, password, client ID and client secret.

---

I just created a Wallabag account with a temporary mail and here is the `wallabag.lua` file:

```
-- we can read Lua syntax here!
return {
    ["wallabag"] = {
        ["is_delete_finished"] = true,
        ["remove_finished_from_history"] = false,
        ["articles_per_sync"] = 30,
        ["filter_tag"] = "",
        ["is_sync_remote_delete"] = false,
        ["client_secret"] = "ks9b97f5tj44k8gooc40w0s8ss8gcooo8ckcsow0wswg84ss0",
        ["password"] = "nxnyyvmr@sharklasers.com",
        ["is_auto_delete"] = false,
        ["client_id"] = "10449_34fbli302b40ocgsww4kksw4g4ossc8g4ko4cs4s4ggowkc84o",
        ["is_delete_read"] = false,
        ["is_archiving_deleted"] = false,
        ["username"] = "koreaderwallabagbug6129",
        ["server_url"] = "https//app.wallabag.it",
        ["ignore_tags"] = ""
    }
}

```

I can access the API with the given call in the Wallabag doc with [HTTPie](https://httpie.org/run):

```
http POST https://app.wallabag.it/oauth/v2/token \
    grant_type=password \
    client_id=10449_34fbli302b40ocgsww4kksw4g4ossc8g4ko4cs4s4ggowkc84o \
    client_secret=ks9b97f5tj44k8gooc40w0s8ss8gcooo8ckcsow0wswg84ss0 \
    username=nxnyyvmr@sharklasers.com \
    password=koreaderwallabagbug6129
```

But I failed in the KOReader app. :disappointed:

**Comment by fazlerabbi37** [comment]
And about server side config, the `Redirect URIs` should be empty, right?

**Comment by Frenzie** [comment]
Ah, there's actually a fifth one that you need, the directory.

![Screenshot_20200612_183513](https://user-images.githubusercontent.com/202757/84525211-9375af00-acdb-11ea-8899-7578b71f5182.png)

https://github.com/koreader/koreader/blob/1384b5e97d738352ed04a130b23152d210dbfd33/plugins/wallabag.koplugin/main.lua#L295-L300

**Comment by fazlerabbi37** [comment]
> Ah, there's actually a fifth one that you need, the directory.

I have set the download directory, here is the new Lua file:

```
-- we can read Lua syntax here!
return {
    ["wallabag"] = {
        ["is_delete_finished"] = false,
        ["directory"] = "/storage/emulated/0/wallabag",
        ["remove_finished_from_history"] = false,
        ["articles_per_sync"] = 30,
        ["filter_tag"] = "",
        ["is_sync_remote_delete"] = false,
        ["client_secret"] = "ks9b97f5tj44k8gooc40w0s8ss8gcooo8ckcsow0wswg84ss0",
        ["password"] = "nxnyyvmr@sharklasers.com",
        ["is_auto_delete"] = false,
        ["client_id"] = "10449_34fbli302b40ocgsww4kksw4g4ossc8g4ko4cs4s4ggowkc84o",
        ["is_delete_read"] = false,
        ["is_archiving_deleted"] = false,
        ["username"] = "koreaderwallabagbug6129",
        ["server_url"] = "https//app.wallabag.it",
        ["ignore_tags"] = ""
    }
}
```

Error is still occurring.

**Comment by Frenzie** [comment]
Which error? It looks like you shouldn't get "Please configure the server and local settings." The server config should look like this:

![Screenshot_20200613_082714](https://user-images.githubusercontent.com/202757/84561875-45e75980-ad50-11ea-81ca-681da7e93fd8.png)

**Comment by fazlerabbi37** [comment]
> Which error? It looks like you shouldn't get "Please configure the server and local settings." 

But I am still getting the `Please configure the server and local settings` error. I am bit confused as to where I am making the mistake.

---

Server config seems to match with provided screenshot.

**Comment by Frenzie** [comment]
While your config as pasted doesn't work for me, that's not an error I can reproduce.

### Your directory isn't valid on my end, makes sense ;-)
<img src=https://user-images.githubusercontent.com/202757/84566130-1f84e680-ad6f-11ea-9a89-d2a1ceca6007.png width=45%>

### However, I can't log in. Note that this is a very different error than `Please configure the server and local settings`, which means the plugin won't even try to login due to missing information.
<img src=https://user-images.githubusercontent.com/202757/84566131-201d7d00-ad6f-11ea-9f48-d8e51023be24.png width=45%>

Did you perhaps manually edit the config file while the program was running or something to that effect?

**Comment by Frenzie** [comment]
```
06/13/20-12:16:05 DEBUG Wallabag: URL      https//app.wallabag.it/oauth/v2/token
06/13/20-12:16:05 DEBUG Wallabag: method   POST
06/13/20-12:16:05 DEBUG Wallabag: Server error:  invalid host 'nil'
```

**Comment by Frenzie** [comment]
Oh! You forgot the `:`. lol

**Comment by Frenzie** [comment]
Dunno if you changed your testing instance in the meantime? With `["server_url"] = "https://app.wallabag.it",` it won't login for me:

![Screenshot_2020-06-13_12-18-36](https://user-images.githubusercontent.com/202757/84566258-18120d00-ad70-11ea-92f7-1b8c3f8781ee.png)

**Comment by Frenzie** [comment]
I seem to be getting a 400 Bad Request from the server. Strange.

**Comment by Frenzie** [comment]
Ah no, all's well:
```
{"error":"invalid_grant","error_description":"Invalid username and password combination"}
```

**Comment by fazlerabbi37** [comment]
> Oh! You forgot the :. lol
> But anyway, that's the kind of error you should (hopefully not) be seeing. Not Please configure the server and local settings.

Huh, quite an interesting typo. I copied and pasted all the values so did not notice it. And yes Now I am getting `Could not login to Wallabag server`😐

---
> Dunno if you changed your testing instance in the meantime? With ["server_url"] = "https://app.wallabag.it", it won't login for me.

I just checked and I can log in with the credentials and I can also access the API vai HTTPie.

**Comment by Frenzie** [comment]
@fazlerabbi37 Your username and password are swapped in the Lua config you posted vs HTTPie. Swapping them allows me to log in to your instance.

**Comment by Frenzie** [comment]
I added some random stuff, you should be able to see it.
<img src=https://user-images.githubusercontent.com/202757/84566669-6379ea80-ad73-11ea-9ace-09c08e2833ac.png width=45%>

**Comment by fazlerabbi37** [comment]
> @fazlerabbi37 Your username and password are swapped in the Lua config you posted vs HTTPie. Swapping them allows me to log in to your instance.

Thank you very my for tolerating me with such patience! I am externally sorry for wasting your valuable time with my stupid mistake. :disappointed: 

> I added some random stuff, you should be able to see it.

I can see them. Thanks!

**Comment by fazlerabbi37** [comment]
Made a small change in Wiki to update and warn user from what I have learned from here.
