### ISSUE TITLE
Permanently turn backlight off?

### ISSUE THREAD

**Issue by josephernest** [koreader/koreader#6136]
* Device: Kobo Clara HD

Hello, Congrats for this great project! Is there a feature to completely turn backlight off? (No more backlight even if we increase the brightness slider). Thanks!

**Comment by pazos** [comment]
Nope. That's not a feature, it is a missconfiguration. In that case you can missconfigure your clara setting https://github.com/koreader/koreader/blob/master/frontend/device/kobo/device.lua#L203-L204 to `nil`

**Comment by josephernest** [comment]
Thanks!
