### ISSUE TITLE
[BUG] Full ProgressBar Support Fallback Font Only

### ISSUE THREAD

**Issue by DaVinci42** [koreader/koreader#6139]
* KOReader version: All
* Device: Android

#### Issue
Full progress bar support fallback font only, the selected font or default font won't work.

select a Chinese font, but don't make it the fallback font.
![bar0](https://user-images.githubusercontent.com/4347318/81563176-81e17480-93c8-11ea-98d6-18f8b4473e9f.jpg)

select any other font, even it's not a Chinese font, just make sure fallback font is Chinese
![bar1](https://user-images.githubusercontent.com/4347318/81563183-83ab3800-93c8-11ea-81cb-75f8cc9dfdc5.jpg)

what I expect: 
the progress bar should display the same font with the book content.

another trouble from this bug:
1. to make progress bar display title correctly, I need to set a Chinese font as the fallback, which works as expected, no side effect.
2. but there are some cases when the character not included in the currently selected font, like  ⋯(U+22EF). If this Unicode not included in the fallback font, will display `?` instead. I think this is exactly what fallback font should do, but the fallback font is set a Chinese to support the progress bar.

Usually, I should use something like FreeSans, or DejaVuSans, as fallback font, because they have quite good support on Unicode

**Comment by poire-z** [comment]
> KOReader version: All

Have you tested them all ?! :)

Seriously, which version are you running? Latest release or nightly ?
Not yet in the latest release, but already in current nightlies are #6090 and #6095, which (to my surprise) seem to work also with the top status bar and font (and should magically solve your other single fallback fonts issues)

Unchecking `Use additional fallback fonts`:
Chinese:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81568610-4b8eff80-939e-11ea-9af0-97e2163996b4.png)</kbd>

Arabic:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81568729-7c6f3480-939e-11ea-993a-8d926850248c.png)</kbd>

Checking it (the default):
Chinese:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81568646-5c3f7580-939e-11ea-961d-8bb592d7eb80.png)</kbd>

Arabic:
<kbd>![image](https://user-images.githubusercontent.com/24273478/81568778-88f38d00-939e-11ea-9cbb-b58a0a3dfeb4.png)</kbd>
(and no, I won't make the top status bar support BiDi/RTL !)

**Comment by DaVinci42** [comment]
@poire-z 

release version, v2020.04.1
so guess the fix will included in this month release, lol

**Comment by poire-z** [comment]
> what I expect:
the progress bar should display the same font with the book content.

Well, it is true that it does not use the font set for the book. But I'm not sure it should (the title bar might be considered some UI element, where a "Sans" font is nicer than a "Serif" font, which are better for book content.
We're using the same font used for the other UI elements:
https://github.com/koreader/koreader/blob/6e9de06fabfee79b5881ca9f4100877fc928f019/frontend/document/credocument.lua#L30
But if you really want another font, you can set it manually by adding a `header_font` setting in reader.settings.lua:
https://github.com/koreader/koreader/blob/6e9de06fabfee79b5881ca9f4100877fc928f019/frontend/apps/reader/modules/readerfont.lua#L102-L105

**Comment by DaVinci42** [comment]
@poire-z 
thank you so much :joy:

tested the latest nightly release, it works.
The title bar status should be consistent with the other UI elements, it's a reasonable feature.

issue solved, close this ticket.
