### ISSUE TITLE
[bug] open a *chunky* 55MB epub causes koreader to crash on my paperwhite 4

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6141]
* KOReader version: 2020.04.01
* Device: pW4

#### Steps to reproduce
Open up a very chunky epub in this case "ESV Study Bible  English Standard Version.epub"
Koreader will try mightily to load it for awhile, progress bar hits 75%; then it crashes each time.

log indicates it happens
Killed

Guessing the memory usage gets too much for the OS to tolerate and it gets killed.

##### `crash.log` (if applicable): 
https://gist.github.com/arooni/26d4bdfb6e9780c0efda103ea29f22da

**Comment by NiLuJe** [comment]
Yup, that's quite likely an OOM kill.
