### ISSUE TITLE
[FEATURE REQUEST] Koreader Web Client

### ISSUE THREAD

**Issue by Jbbrack03** [koreader/koreader#6145]
First off, thank everyone for their hard work! I really appreciate everything. I've got my Koreader setup alongside Ubooquity and my own self-hosted sync plugin. This is an awesome setup and I'm really enjoying it. 

It would be really nice to be able to open Koreader in the browser on my PC and continue reading my content. I know that there are other solutions to read books on the PC, but none of them are synced with my progress from Koreader. I'm not sure if this is possible, but I figured I'd ask.

**Comment by Frenzie** [comment]
There are some theoretical possibilities I can think of, but they're all quite roundabout and involved. I'll tag this as out of scope for now.

The most realistic option (as in you might actually be able to do it right now) would probably be something like https://stackoverflow.com/a/16311264/2470572 with the AppImage and something like https://github.com/novnc/noVNC to access it. But I doubt it'd be terribly convenient. ;-)

**Comment by NiLuJe** [comment]
Or just running the emulator natively? Unless I'm missing something obvious about the intended workflow?

**Comment by Frenzie** [comment]
I interpreted it more as any random PC. If we're just talking about your PC, then yes, that's what the AppImage is for. Still somewhat similar in principle if you want to run it on Windows in WSL2 though.
