### ISSUE TITLE
wish koreader support eudic

### ISSUE THREAD

**Issue by shieep** [koreader/koreader#6150]
koreader is a excellent app, but it not support eudic dictionary, I will it wll support eudic

**Comment by pazos** [comment]
For android?

Can you test it for us?

Create a file called `dictionaries.lua` inside `koreader` folder with contents

```lua
return {
    -- tested dictionary applications
    { "EudicT1", "EudicT1", false, "com.eusoft.eudic", "text" },
    { "EudicT2", "EudicT2", false, "com.eusoft.eudic", "send" },
    { "EudicT3", "EudicT3", false, "com.eusoft.eudic", "colordict" },
}
```

Restart KOReader -> exit and start it again from launcher. Test all options and report back if some option is better than the others or they are all ok.

**Comment by shieep** [comment]
> For android?
> 
> Can you test it for us?
> 
> Create a file called `dictionaries.lua` inside `koreader` folder with contents
> 
> ```lua
> return {
>     -- tested dictionary applications
>     { "EudicT1", "EudicT1", false, "com.eusoft.eudic", "text" },
>     { "EudicT2", "EudicT2", false, "com.eusoft.eudic", "send" },
>     { "EudicT3", "EudicT3", false, "com.eusoft.eudic", "colordict" },
> }
> ```
> 
> Restart KOReader -> exit and start it again from launcher. Test all options and report back if some option is better than the others or they are all ok.

thx very much, they are all ok.
koreader is better than anyother readers likes moon reader, i spend several days to find a reader like koreader and support eudic, but I failed.
I'm very happy to find that koreader is so easy to support eudic
koreader + eudic is the best combination.

**Comment by pazos** [comment]
@shieep: in your opinion what makes eudic a good dict application? It is something related to chinese glyphs? 

I tried to look some info at google but I couldn't find anything on english (or any other western language)

I'm trying to figure out if this app is something useful for most chinese users or is just a matter of preference.

**Comment by shieep** [comment]
> @shieep: in your opinion what makes eudic a good dict application? It is something related to chinese glyphs?
> 
> I tried to look some info at google but I couldn't find anything on english (or any other western language)
> 
> I'm trying to figure out if this app is something useful for most chinese users or is just a matter of preference.

stardict's dictionary has been deleted all, I try to find some EN-ZH-cn dictionaries for koreader's built-in dictionary, but there is very few stardict's dictionary to download and their quality is very low.
Eudict is support's Mdict's format, and it much better than Mdict. There are a lot EN-ZH-cn dictionaries and their quality is very high.
At first, I try to use Mdict with Koreader, but it has some bugs.
Eudict is more friendly than Mdict, maybe Eudict's users mainly are chinese.

**Comment by shieep** [comment]
> @shieep: in your opinion what makes eudic a good dict application? It is something related to chinese glyphs?
> 
> I tried to look some info at google but I couldn't find anything on english (or any other western language)
> 
> I'm trying to figure out if this app is something useful for most chinese users or is just a matter of preference.

there are also two dictionary app which chinese users mainly use:

网易有道词典
https://android.myapp.com/myapp/detail.htm?apkName=com.youdao.dict

金山词霸
https://android.myapp.com/myapp/detail.htm?apkName=com.kingsoft

**Comment by pazos** [comment]
> there are also two dictionary app which chinese users mainly use:

Thanks. Feel free to make a patch to include them. If not we can wait until some user requests them.

This should work:


```lua
return {
    { "Youdao", "网易有道词典", false, "com.youdao.dict", "send" },
    { "Kingsoft", "金山词霸", false, "com.kingsoft", "send" },
}
```
