### ISSUE TITLE
Cancelling WiFi connection dialog when attempting to update software freezes Kobo Forma

### ISSUE THREAD

**Issue by pkrakowiak** [koreader/koreader#6151]
* KOReader version: 2020.04.1
* Device: Kobo Forma

#### Issue
The device is frozen (I was seriously scared it was bricked) when you cancel the modal dialog asking to connect to WiFi when attempting to update software. The backlight turns off, the device appears to be sleeping with the last read page on and it does not react to the power button (I tried to hold it for over 30 seconds multiple times to no avail). The only way to fix it was to connect it to the computer.

#### Steps to reproduce
Open KOReader.
Go to the KOReader update option, tap it.
A modal dialog will be shown to ask you turn on WiFi. Decline.
The reader is now frozen as described above.

I did not find the crash.log file on my device.

**Comment by pkrakowiak** [comment]
This is how the device looked after it froze.

![IMG_4628](https://user-images.githubusercontent.com/736489/82018777-4542a100-9686-11ea-8b9a-aef4e218d36b.jpg)

**Comment by Frenzie** [comment]
Have you reproduced the steps above yourself as well? Given your description it sounds to me like your battery coincidentally happened to run out right after you pressed cancel.

**Comment by pkrakowiak** [comment]
@Frenzie I think you are correct. I just noticed the device was out of juice but it froze exactly at the same moment I tapped the Cancel button so I thought it was KOReader's doing. It's the first time I let it run out of battery so I am not accustomed to what happens then.

I re-tested while charging and it didn't happen. I am ashamed for posting a bug report without further testing, sorry. :(

**Comment by Frenzie** [comment]
Btw, you can adjust the low battery alarm in settings → device → low battery alarm. It defaults to 20, but on my H2O that's not a very useful value because that's roughly equivalent to dead.

**Comment by pkrakowiak** [comment]
It was set to the default 20 but I was reading in bed the day before and ignored the warning and then the next day forgot to recharge it. :) Thanks.
