### ISSUE TITLE
Is it possible to prevent displaying <br /> tags?

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#6152]
* KOReader version: 2020.04.01-34(latest nightly)
* Device: Kobo Clara HD/Kindle Paperwhite 3/Emulator

#### Issue
After enabling `Style Tweaks -> Paragraphs -> Spacing between paragraphs -> No spacing between paragraphs` spacing still remains(and on top of that I can select another option while both remain active)
#### Steps to reproduce
Enable `Style Tweaks -> Paragraphs -> Spacing between paragraphs -> No spacing between paragraphs`. I build emulator with version v2020.04.01 - It doesn't seem to work there either, but the default behavior is "no spacing between paragraphs". It seems to have been changed to spacing between paragraphs since.
##### `crash.log` (only relevant part)
https://pastebin.com/raw/H44sVWzD

**Comment by poire-z** [comment]
It still works for me on books that need it.
I guess it just does not work for you on the specific book you're testing with - but it will probably on others.

> p, li { margin-top: 0 !important; margin-bottom: 0 !important; }[END]

I guess the vertical spacing you see is made by some other margin or padding set on another parent container element. We/KOReader can't detect that for you.
First try the hyper radical ones in `Pages > Ignore margin and padding > Ignore vertical margin/padding`.
Then, if that's too radical, you need to inspect the HTML and add less radical CSS in a user style tweak.

> but the default behavior is "no spacing between paragraphs". It seems to have been changed to spacing between paragraphs since.

There is no default (and none of these style tweaks is enabled by default): the default is to be nice and ensure the publisher design choices he has set via CSS. Then, you, with style tweaks, can disable some of these choices.

> (and on top of that I can select another option while both remain active)

That's normal, there is no logic in the style tweaks menu: CSS snippers are cumulative, we just ensure sometimes some priority between them, but that does not show in the menus.
More info in the file itself: https://github.com/koreader/koreader/blob/master/frontend/ui/data/css_tweaks.lua

**Comment by mergen3107** [comment]
Double check that there are no emptyline tags between the paragraphs. Select some text in KOReader that goes from one paragraph to another, tap “View HTML” button. It will show you raw book script with tags.

**Comment by Galunid** [comment]
Yes, apparently https://github.com/koreader/crengine/commit/65d4adf843b4c85627187d4e2f685b8f42dfa1f4 introduced "displaying" <br /> tags, so it's not a problem with paragraphs/settings. I'll rename the issue accordingly. Any way to disable this behavior without compiling crengine? I tried adding custom styles
```css
br {
   display: none !important;
}
```
although they don't seem to work. Tried `content: ""` too, but it didn't work.

**Comment by Frenzie** [comment]
@Galunid Did you try something like `margin-top: -1em`?

**Comment by Galunid** [comment]
@Frenzie I tried it right now, it doesn't seem to have any effect.

**Comment by poire-z** [comment]
Well, it did not introduce displaying BR tags - it actually fixed BR tags being ignored :)
It's more a publisher content choice (to break line there) than it is a style choice. It's like asking to remove all letters `A` from the book content.

Anyway, tried a few CSS tricks, did not manage either.
Might depend on where your BR happens (inside a block text container, or between block containers.

<kbd>![image](https://user-images.githubusercontent.com/24273478/82053024-f106e380-96bc-11ea-92b2-cbb4c1b61e4c.png)</kbd>.
If they appear like that, I guess if set to `display:none`, they could be ignored and shouldn't be wrapped in that autoBoxing.
Otherwise, it's text content, and you should get an ampty line only when they are 2 consecutive BRs.

Please try to see how your book page renders in a web browser or some other EPUB reader - just to be sure our behaviour is correct. If not, I'll take the sample to look at it.

**Comment by Galunid** [comment]
![image](https://user-images.githubusercontent.com/10298730/82054188-d46bab00-96be-11ea-94f4-ec38cf2d4802.png)
Tried it with zathura/firefox/kobo's default ereader and results seem similar. Yes, the tag is between paragraphs and none of the above works.

**Comment by poire-z** [comment]
OK, thanks, that's reassuring :)
You get that between ALL paragraphs ?! Or just between some, and that would mean it's some kind of section break in the chapter, which could be considered "content".
Can you share a screenshot of selecting text from "saliva" to "Saying", and View HTML ?

**Comment by Galunid** [comment]
![Reader_2020-05-15_152948](https://user-images.githubusercontent.com/10298730/82055662-1f86bd80-96c1-11ea-8ee5-bbd6ce17c156.png)

**Comment by Galunid** [comment]
The previous screenshot was taken on firefox, sorry forgot to mention that. On koreader it looks reasonable(1 line height), although it's kind of annoying, after getting used to no line breaks.

**Comment by poire-z** [comment]
Anyway, regarding my change at the bottom of https://github.com/koreader/crengine/pull/338/files, having `BR { display: none; }` work (as I think they should) is just a matter of correctly doing:
```diff
     // <br/> can be set to "display: block" by publishers, but
     // Firefox and Calibre do not handle them like other block
     // elements: they won't ensure a "height:" set on them.
     // It's not clear how such BR should be handled, but comparing
     // with how Firefox/Calibre/Chrome render them, it looks
     // like we'll render quite as they do when forcing BR to
     // always be css_d_inline:
     // When met alongside block elements, they'll be autoboxed and
     // will ensure just their (possibly inherited) line-height.
-    if (nodeElementId == el_br) {
+    if (nodeElementId == el_br && pstyle->display != css_d_none) {
         pstyle->display = css_d_inline;
     }
```
Then, these would work:
```css
br { display: none !important;} /* all, including inside text paragraph */
br + br { display: none !important;} /* when many, keep a single one */
body > br { display: none !important;} /* only those child of BODY */
```

(I can compile for you a kobo libcrengine.so with that if you're in a hurry.)

**Comment by poire-z** [comment]
(Re-asking: You get that between ALL paragraphs ?! Or just between some, and that would mean it's some kind of section break in the chapter, which could be considered "content".)

**Comment by Galunid** [comment]
I get that between all paragraphs

**Comment by Galunid** [comment]
I already build the library, I'll see if it works

**Comment by Galunid** [comment]
It seems to work just fine.

**Comment by poire-z** [comment]
OK, I'll add that to my next PR, in a week or two.
In your case, your target should be `p + br { display: none !important; }` if you don't want to kill some other BR that may have more meaning.

**Comment by Galunid** [comment]
Great, thanks for quick response!
