### ISSUE TITLE
MD5 question

### ISSUE THREAD

**Issue by noembryo** [koreader/koreader#6153]
Just a quick question (or maybe two ;o)..

Because of an [issue](https://github.com/noembryo/KoHighlights/issues/7) in KOHighlights, I noticed that there is another `MD5` key, apart from the `partial_md5_checksum` in the `metadata.lua` file.
Is one of them going to be deprecated any time soon, because I only check the `partial_md5_checksum` to see if two books are the same file.

And since we are on the subject, is there a reason to change this number when converting the settings due to the last changes in the format?

**Comment by Frenzie** [comment]
What do you mean by another one? The one in the statistics plugin? I'm not really sure why there's a different one there with a different partial MD5 function; maybe it just slipped through accidentally a few years ago.

**Comment by Frenzie** [comment]
> And since we are on the subject, is there a reason to change this number when converting the settings due to the last changes in the format?

Could be related to https://github.com/koreader/koreader/releases/tag/v2020.04.1

MD5 was broken in nightlies for a little while.

**Comment by poire-z** [comment]
Seems `partial_md5_checksum` is only there when the kosync plugin is enabled.
And the `["stats"]["md5"]` one only when the statistics plugin is enabled (which had a bug with wrong md5, possible shared by multiple books since november 2019 https://github.com/koreader/koreader-base/pull/1077#issuecomment-613580988).

**Comment by noembryo** [comment]
> Seems `partial_md5_checksum` is only there when the kosync plugin is enabled.
That means that there is  a possibility for a book to not have one?
Is there another way to have a unique id for book?

**Comment by poire-z** [comment]
I don't see in my metadata.epub.lua any other thing that could serve as that...
You could just make a preriquisite to have this kosync plugin enabled.
(Or have KOHighlights compute itself some md5 if it has access to the book alongside the .sdr.)

**Comment by noembryo** [comment]
> I don't see in my metadata.epub.lua any other thing that could serve as that...
> You could just make a preriquisite to have this kosync plugin enabled.

Looking at the "Plugin management" of KOReader, I can't find any kosync plugin.
Maybe it goes by a different name?
> (Or have KOHighlights compute itself some md5 if it has access to the book alongside the .sdr.)

This would create problems if the metadata are copied from the reader or of there are inside a History folder (do this still exist in android?) or somehow there is no book next to the sdr.
I prefer not to do that.
OTOH if I knew the exact computation mechanism, I could use it if there was no MD5 to compare it with an existent MD5 from KOReader..

**Comment by pazos** [comment]
> Looking at the "Plugin management" of KOReader, I can't find any kosync plugin.
Maybe it goes by a different name?

It's called "Progress sync"

**Comment by noembryo** [comment]
> It's called "Progress sync"
Thank you

**Comment by noembryo** [comment]
I changed my code to use either of the `partial_md5_checksum` or `stats.MD5` as a unique id, since from what I can see, they are the same.

Can anyone point me to the lua code that does the `partial_md5_checksum` computation?
I'll try to read it if possible (although I have no lua knowledge at all :-) and have it as a third option..

**Comment by Frenzie** [comment]
It's calculated here:
https://github.com/koreader/koreader/blob/2e947e6ffe5dadbb7f3b1ef7430bf91b4f51d9fe/frontend/document/document.lua#L125-L160

**Comment by noembryo** [comment]
> It's calculated here:

Thank you

**Comment by Frenzie** [comment]
> since from what I can see, they are the same.

Then it seems the stats one should also use Document:fastDigest instead of its own implementation?

**Comment by richo67** [comment]
I had book opened by koreader 2020.03.1 and then on other device,  same book (binary same) with 2020.4 (first kindle second android) and they have different MD5. Is that possible?

When I removed metdata.lua file and upgraded koreader on kindle to 2020.04 it produce same MD5 as android.
Possible?

**Comment by poire-z** [comment]
Yes, possible since november 2019, see https://github.com/koreader/koreader-base/pull/1077#issuecomment-613353913 and followups: newly opened book may get the md5 of another previously opened book.
Fixed in 2020.04.1 by https://github.com/koreader/koreader/pull/6052.

**Comment by noembryo** [comment]
Tried to port the code but its not working.
I used this..
```python
        m = hashlib.md5()
        step, size = 1024, 1024
        with open(path, "rb") as file_:
            for i in range(11):
                file_.seek(step << (2 * i))
                sample = file_.read(size)
                if sample:
                    m.update(sample)
                else:
                    break
            result = m.hexdigest()
```
.. since using `range(-1, 11)` gives me a `ValueError: negative shift count` error.
The result is different from what KOReader calculates.
Does anybody sees what am I doing wrong here (since I know nothing about lua :o)?

**Comment by poire-z** [comment]
No idea about what our partial md5 algorithm does and why :)
Just running it, in case that helps you comparing with what you get with python range(), or finding alternatives:
```
> for i = -1, 10 do print(2*i) end
-2
0
2
4
6
8
10
12
14
16
18
20
> for i = -1, 10 do print(lshift(1, 2*i)) end
1073741824
1
4
16
64
256
1024
4096
16384
65536
262144
1048576
> for i = -1, 10 do print(lshift(1024, 2*i)) end
0
1024
4096
16384
65536
262144
1048576
4194304
16777216
67108864
268435456
1073741824
>
```
I guess strangely starting with -1 is to get 0 after the lshift.

**Comment by noembryo** [comment]
I guess the values I need are the last set, since that is what sets the `file.seek` in `file:seek("set", lshift(step, 2*i))`.
But even using these, the result is still different.
Oh, well..
Maybe its because of the different libraries, who knows :o(
I'll search it a little more..
Thank you for your help!

**Comment by poire-z** [comment]
> gives me a ValueError: negative shift count 

Just handle 0 aside then :)
```
for i in range(12): seek = i > 0 and (1024<<(2*(i-1))) or 0

for i in range(12): print i > 0 and 1024<<(2*(i-1)) or 0
...
0
1024
4096
16384
65536
262144
1048576
4194304
16777216
67108864
268435456
1073741824
```

**Comment by noembryo** [comment]
Ououppsss!!!
Well, its embarrassing..
All this time I was using the path the the `metadata.lua` file, not the path to the book!
And of course the code works.. (Yey!)
