### ISSUE TITLE
 Left-to-Right page turning option disappearing

### ISSUE THREAD

**Issue by qchenac** [koreader/koreader#6156]
* KOReader version:KOReader 2020.04.1
* Device:kindle paperwhite 4

#### Issue
**### left-to-right page turning option disappearing** 

Well I just found this feature disappeared in menu when I opened a pdf, which is extremely useful when reading some archaic texts or comics. Hope koreader could add it back. Thx in advance ;P

**Comment by Frenzie** [comment]
It's been moved into settings → navigation → invert page turn taps and swipes. See https://github.com/koreader/koreader/pull/5284 for discussion.

![Screenshot_20200517_082502](https://user-images.githubusercontent.com/202757/82137416-0c3a3600-9818-11ea-9233-9834e9026c0f.png)
