### ISSUE TITLE
Cut off rounded corners on some devices

### ISSUE THREAD

**Issue by Jbbrack03** [koreader/koreader#6157]
* KOReader version: 2020.04.1
* Device: Samsung Galaxy A50 (running Android 10.0)

#### Issue

Koreader isn't scaled properly on this device. The bottom progress bar and the bottom of the keyboard are cut off. The Galaxy A50 has a 6.4" screen with a resolution of 2340x1080 (19.5:9 aspect ratio).

![IMG_0054](https://user-images.githubusercontent.com/20332798/82134967-99a36900-97cb-11ea-9a96-5a2a6d3c9200.JPG)

#### Steps to reproduce

Open Koreader and observe screen.

**Comment by Frenzie** [comment]
Similar to https://github.com/koreader/android-luajit-launcher/pull/150 I suppose.

**Comment by pazos** [comment]
Also reported in https://github.com/koreader/koreader/issues/4769#issuecomment-471796062

> Similar to koreader/android-luajit-launcher#150 I suppose.

That would make the rounded corner black, leaving a rectangle between safe insets.In this example 
![82134967-99a36900-97cb-11ea-9a96-5a2a6d3c9200](https://user-images.githubusercontent.com/975883/82138353-0cd6ca80-9820-11ea-9578-6b89fd3f0a0e.jpeg)

Maybe a better option would be getting the width in the lowest part as the maximum size of the reader footer in https://github.com/koreader/koreader/blob/1e244d035832d3abd3cf27625d94aeae08c5e8e0/frontend/apps/reader/modules/readerfooter.lua#L572

**Comment by poire-z** [comment]
Or let that tuning to the user :)
We have a menu for the footer margins. It's a bit limited in choice (0, 10, same as book margins - last one only available with CRE books), but I believe "same as book margins" would work in this case, given the screenshot in the original post.
It's in `Gear > Status bar > Progress bar > Margins` (It's a bit misplaced I think, as it does not apply only to the Progress bar, but to the whole status bar).

We could add a Spin/NumberPicker widget for the Static margins submenu. Dunno if that was discussed in the very long #5442 (that I just didn't re-read :)

**Comment by NiLuJe** [comment]
Yep, that's more or less how I deal with it on my phone w/ rounded corners ;).

**Comment by pazos** [comment]
Yeah, user margins are the way to fix that. Just checked and android has no APIs for rounded corners :p.

But the setting should be for the entire readerfooter, not just the progress bar. Am I missing something?

**Comment by poire-z** [comment]
Not really, but yes, it feels misplaced in the `Progress bar>` submenu.
But I guess it applies to the whole status bar (at least when using 0 or static margins, because "same as book margins" is only available when you choose to have the progress bar on a 2nd line).
Also, with progress bar disabled, the status bar is really small with only the items, and centered, so no need for margins I guess :) Margins are needed when the progress bar is there to take the remaining room.

**Comment by pazos** [comment]
From https://android-developers.googleblog.com/2017/12/tuning-your-apps-and-games-for-long.html

> For full screen mode on rounded corners devices, any UI elements very close to the corners may be outside of the curved corner viewable area. Imagine if a commerce app's "Purchase" button was partially obstructed? We recommend referencing Material Design guidelines by leaving 16dp side margins in layouts.

So the following diff should work for any phone:

```diff
--- a/frontend/apps/reader/modules/readerfooter.lua
+++ b/frontend/apps/reader/modules/readerfooter.lua
@@ -689,6 +689,7 @@ end
 
 function ReaderFooter:addToMainMenu(menu_items)
     local sub_items = {}
+    local material_pixels = 16 * math.floor(Screen:getDPI() / 160)
     menu_items.status_bar = {
         text = _("Status bar"),
         sub_item_table = sub_items,
@@ -1463,6 +1464,19 @@ function ReaderFooter:addToMainMenu(menu_items)
                             self:refreshFooter(true)
                         end,
                     },
+                    {
+                        text = _("Static margins (16dp)"),
+                        checked_func = function()
+                            return self.settings.progress_margin_width == Screen:scaleBySize(material_pixels)
+                                and not self.settings.progress_margin
+                                or (self.ui.document.info.has_pages and self.settings.progress_margin)
+                        end,
+                        callback = function()
+                            self.settings.progress_margin_width = Screen:scaleBySize(material_pixels)
+                            self.settings.progress_margin = false
+                            self:refreshFooter(true)
+                        end,
+                    },
                     {
                         text_func = function()
                             if self.ui.document.info.has_pages then
```

In the emulator -> pixel 3 it looks:

![screenshot](https://user-images.githubusercontent.com/975883/82140957-e0787980-9832-11ea-8ed4-5a274c7c384b.png)

**Comment by Jbbrack03** [comment]
That looks perfect!

**Comment by Frenzie** [comment]
A quick note that Android seems to have better means of dealing with rounded corners since Android 12.
https://developer.android.com/develop/ui/views/layout/insets/rounded-corners
