### ISSUE TITLE
Is it possible to auto-apply the last configuration？

### ISSUE THREAD

**Issue by 840922704** [koreader/koreader#6159]
* KOReader version:Latest
* Device:Adroid

#### Issue
In most cases, the default display configuration is not always suitable. So I usually need to customize it.

The problem is, for example, if I read a series of books, I need to change it manually every time when I open a new book!

So when loading a new file, is it possible to apply the last configuration automatically depending on file extension(pdf, mobi, etc.)?

**Comment by mergen3107** [comment]
Long press each customization and it will become default for all new books

**Comment by 840922704** [comment]
> Long press each customization and it will become default for all new books

It works! Thank you!
