### ISSUE TITLE
Setting guide for directly opening previous document

### ISSUE THREAD

**Issue by QuestionJR** [koreader/koreader#6160]
* KOReader version: 2020.04.1
* Device: Android Pie ARM

#### Issue
Would it be possible to directly open previous document when opening Koreader APK, not entering HOME folder directory first then selecting document? If yes, appreciate if you could show me where the setting is.

**Comment by poire-z** [comment]
In File Browser top menu:
<kbd>![image](https://user-images.githubusercontent.com/24273478/82182792-22fa8e80-98e5-11ea-8a70-c2c96d75bf33.png)</kbd>
