### ISSUE TITLE
How to read books in landscape mode in Android emulator on windows?

### ISSUE THREAD

**Issue by leoshone** [koreader/koreader#6165]
* KOReader version: koreader-android-i686-linux-android-v2018.12
* Device: Windows 7 with Android emulator (Bluestacks and Mumu)

#### Issue
Cannot rotate koreader to really "landscape" mode, it is always rotated 90 degrees.

Do you guys have any idea to use koreader in windows?

**Comment by pazos** [comment]
> Device: Windows 7 with Android emulator (Bluestacks and Mumu)

Wow, very unsupported "device"

> Cannot rotate koreader to really "landscape" mode, it is always rotated 90 degrees.

Yup, always rotated on all platforms. See https://github.com/koreader/koreader/issues/5910

> Do you guys have any idea to use koreader in windows?

Nope :p. There's an open issue for win32 builds: https://github.com/koreader/koreader/issues/4512
