### ISSUE TITLE
AZW3 & KFX not as an available sending format under Calibre wireless connection

### ISSUE THREAD

**Issue by qchenac** [koreader/koreader#6166]
* KOReader version:2020.04.1
* Device: KPW4
I noticed when koreader is recognized as a wireless device in calibre, the device configuration panel in calibre is different from when kindle is connected as a USB device. There is no option to select available formats as in usb device configuration and as a result you can only send  epub,mobi,pdf,fb2,pdb these five formats to koreader from calibre wirelessly. Sending calibre books to koreader wirelessly is sweet but it's just even better if we could make azw3 kfx and maybe other formats available to send directly without conversion and read it with native reader rather than koreader which only needs to handle epub and pdf in my case.

**Comment by NiLuJe** [comment]
That's a Calibre-side setting, IIRC.

(I don't use this feature).

**Comment by qchenac** [comment]
OIC that makes sense.

**Comment by qchenac** [comment]
I just received replies from calibre team. Quote as below:

> For the wireless device the desired formats and their order is configured in the reader app. Check on the koreade forum for how to do it.
 
I have dived into the koreader setting but still no luck. Really don't know what could do on koreader side.

**Comment by Frenzie** [comment]
DjVu seems to be listed here, or is that a different one?

https://github.com/koreader/koreader/blob/5704f63bfcdcd37875875ab43926ce06b89cbdde/plugins/calibrecompanion.koplugin/main.lua#L362

**Comment by qchenac** [comment]
Sry for My mistake. DjVu is fine. The invalid one is azw3 that I'm sure of.

**Comment by Frenzie** [comment]
That's not supported, also see #5845. Could you perhaps describe the use case?

**Comment by qchenac** [comment]
Sure. I didn't intend to read azw3 on koreader at all. Just need to send some possible formats(mostly azw3 and kfx in this case) using calibre content server and read it with native reader.

**Comment by pazos** [comment]
IMO we shouldn't add formats that we don't support. But you can edit the plugin yourself:

```diff
--- a/plugins/calibrecompanion.koplugin/main.lua
+++ b/plugins/calibrecompanion.koplugin/main.lua
@@ -359,7 +359,7 @@ function CalibreCompanion:getInitInfo(arg)
     self.calibre_info = arg
     local init_info = {
         canUseCachedMetadata = true,
-        acceptedExtensions = {"epub", "mobi", "pdf", "djvu", "fb2", "pdb", "cbz"},
+        acceptedExtensions = {"epub", "mobi", "pdf", "djvu", "fb2", "pdb", "cbz", "azw3", "kfx"},
         canStreamMetadata = true,
         canAcceptLibraryInfo = true,
         extensionPathLengths = {
@@ -370,6 +370,8 @@ function CalibreCompanion:getInitInfo(arg)
             fb2 = 42,
             pdb = 42,
             cbz = 42,
+            azw3 = 42,
+            kfx = 42,
         },
         useUuidFileNames = false,
         passwordHash = "",
```

**Comment by qchenac** [comment]
I see and totally understand. I will try to build a version for my own and thx for the information.

**Comment by Frenzie** [comment]
I'll close this then. Btw, you don't need to "build" anything except for underlying libraries. Lua files can just be edited with nothing more than a text editor.

**Comment by pdf-conversion** [comment]
I've noticed the same difference in Calibre's device configuration options between KOReader wireless and Kindle USB connections. The lack of format selection for wireless transfers limits us to the pre-defined set (EPUB, MOBI, PDF, etc.).

**Comment by radeonchik** [comment]
I know its been 5 years since that comment, but you can easily send your books via "Send to kindle" from Calibre. You just send it as .epub and it appears on your kindle in mnt/us/documents/Downloads in .kfx format.
