### ISSUE TITLE
PocketBook PB616W unsupported

### ISSUE THREAD

**Issue by tosyu** [koreader/koreader#6168]
* KOReader version: v2020.04.1
* Device: PocketBook Basic Lux 2 (PB616W)

#### Issue

The application crashes

#### Steps to reproduce

Instal&run

##### `crash.log` 
 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/19/20-13:04:45
 [*] Version: v2020.04.1

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: inkview
05/19/20-13:04:45 INFO  SoftwareVersion:  U616.5.17.1775
./luajit: frontend/device/pocketbook/device.lua:391: unrecognized PocketBook model PB616W
stack traceback:
	[C]: in function 'error'
	frontend/device/pocketbook/device.lua:391: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:53: in main chunk
	[C]: in function 'require'
	./reader.lua:119: in main chunk
	[C]: at 0x00013f31

**Comment by tosyu** [comment]
Hey
I have a [PocketBook Basic Lux 2]( https://www.pocketbook-int.com/int/support/pocketbook-basic-lux-2) and I have found that PB616W is not supported. I've changed the file `device.lua` and added the "experimantal" suport by changing a condition in line `367` to
```
elseif codename == "PB626" or codename == "PB626(2)-TL3" or
    codename == "PocketBook 626" or codename == "PB616W" then
    return PocketBook626
```

That helps as Koreader starts and "seems" to work fine, athough the controls do not work. If somebody could help and guide me how to configure koreader on that device I would gladly submit a PR

**Comment by Frenzie** [comment]
What exactly do you mean by controls not working? The device codenames come with device definitions:

https://github.com/koreader/koreader/blob/5704f63bfcdcd37875875ab43926ce06b89cbdde/frontend/device/pocketbook/device.lua#L240-L247

**Comment by tosyu** [comment]
Well I mean that the big left-right buttons do work and I'm able to change file manager listings, but thats it, the mainbutton in the middle of nor the frame around it (which acts like a D-Pad) does not do anything. To exit koreader app I had to power down/up the device.

**Comment by pazos** [comment]
We don't support any PB without touchscreen. Patches welcome!

**Comment by tosyu** [comment]
Oh, ok.

I'm browsing through the source code to get a grasp of the codebase. So is this just a frontend feature or is there any work to be done in the core of the app?

**Comment by Frenzie** [comment]
It's not impossible (in that case mainly see [here](https://github.com/koreader/koreader-base/blob/989d3a92b90872b67430fd7fae88ac84e52c05bc/input/input.c)) but probably unlikely.

**Comment by pazos** [comment]
>  So is this just a frontend feature or is there any work to be done in the core of the app?

In theory you can get key ids from https://github.com/blchinezu/pocketbook-sdk/blob/master/FRSCSDK/arm-none-linux-gnueabi/sysroot/usr/include/linux/input.h#L104-L539 and add them to https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L93-L97.

You'll need to figure out event/key pairs. Start by logic ones, like KEY_RIGHT, KEY_LEFT and KEY_UP/DOWN and see if your dpad works.

**Comment by tosyu** [comment]
Ok, thank you!

I'll make a PR when I will have something working

**Comment by lenormf** [comment]
Hi,

I have a similar problem, with a 515 model:

```
./luajit: frontend/device/pocketbook/device.lua:337: unrecognized PocketBook model PocketBook 515
```

Is implementing a device definition object the only thing I should do, to add support for it?

Thanks!

**Comment by Frenzie** [comment]
@lenormf Most likely, although it's always possible for something unexpected to crop up. ;-)

**Comment by lenormf** [comment]
Thanks for the quick reply, I'm just concerned that all the devices I see listed there are fairly recent (>6xx series) and are touch-enabled! I might have a go at improving support for my device.

**Comment by Frenzie** [comment]
That means you might want an `isTouchDevice = no` in there, related options would be:

```lua
    hasKeyboard = yes,
    hasKeys = yes,
    hasDPad = yes,
```

It's possible that you'd need to add the keybinds for those as detailed a few posts up but in all likelihood it should be fairly unproblematic.

**Comment by Frenzie** [comment]
@tosyu @lenormf I added the basic definitions in #6182 and triggered a build (should be done in about a half hour); hopefully it helps. Please let us know and/or submit PRs for things that aren't working right.

**Comment by lenormf** [comment]
That's what I'd came up with on my side as well, it allows the application to start. The buttons are not supported, I'll see if I can get that to work.

**Comment by lenormf** [comment]
@Frenzie @tosyu I have tested the following mappings for the 515 model - they work:

```lua
            [KEY_UP] = "Up",
            [KEY_DOWN] = "Down",
            [KEY_LEFT] = "Left",
            [KEY_RIGHT] = "Right",
            [KEY_OK] = "Press",
```

I'm not sure how to make it so those bindings would be only set when the host system is a PocketBook515, so I've hardcoded them into the event map.

Another problem I have is when I open a file, then enter the UI menu (with the main button), I have no way of leaving it that I see! There's no "menu" or "back" button on this model, only a DPad ("OK", plus four "arrow" buttons) and two "page next/previous" buttons.

**Comment by Frenzie** [comment]
@lenormf I'm not sure if that can work without repurposing previous page as back or something. The interface can't really work with less than four arrow directions as well as ok/cancel.

Basically like this (Kindle 4):

![kindle-4](https://user-images.githubusercontent.com/202757/82756949-9288e600-9ddd-11ea-8d55-9ee42f0e719f.jpg)

**Comment by lenormf** [comment]
How about making it so holding the "OK" button equates to hitting an "exit"/"back" button that might not exist?

**Comment by lenormf** [comment]
For archiving's sake, here are the modifications I've further made to `device.lua` from #6182:

```diff
diff --git a/device.lua b/device.lua
index 0689cc2..82cf109 100644
--- a/device.lua
+++ b/device.lua
@@ -98,6 +98,12 @@ function PocketBook:init()
             [KEY_MENU] = "Menu",
             [KEY_PREV] = "LPgBack",
             [KEY_NEXT] = "LPgFwd",
+            [KEY_UP] = "Up",
+            [KEY_DOWN] = "Down",
+            [KEY_LEFT] = "Left",
+            [KEY_RIGHT] = "Right",
+            [KEY_OK] = "Press",
+
         },
         handleMiscEv = function(this, ev)
             if ev.code == EVT_BACKGROUND then
@@ -210,6 +216,8 @@ local PocketBook515 = PocketBook:new{
     model = "PB515",
     display_dpi = 200,
     isTouchDevice = no,
+    hasWifiToggle = no,
+    hasDPad = yes,
 }
 
 -- PocketBook Basic Lux 2
```

**Comment by Frenzie** [comment]
You could do that. You'd have to write a bunch of code in places like device/input or device/key. You can find sample hold and double tap code in device/gesturedetector which could be used for keypresses as well. 

Besides having to write some new behavior, we don't really want that behavior on devices without such issues. There it'd just be an unnecessary interface complication, accidentally hold a key too long and you've got unintended consequences.

For the purpose of just getting it working I wouldn't worry about the code inclusion stuff. Just make your changes and then tidy it up once it's all good and working.

**Comment by lenormf** [comment]
Thanks for the pointers, I'll try to have a look.

Couldn't we have this behaviour enabled with an option, in the device structure? I'd find it surprising if all the readers using this application all had >4 buttons, so this opt-in behaviour wouldn't be dead code.

**Comment by Frenzie** [comment]
> Couldn't we have this behaviour enabled with an option, in the device structure?

That's what I meant. I'm not sure what you think I meant. ;-)

**Comment by Frenzie** [comment]
Incidentally, actual long-press is a thing too: https://github.com/koreader/koreader/issues/3818

In that issue I proposed using the menu button as opposed to actual longpress, but the PB doesn't have that.

One could envision fairly complex interaction patterns based on just one single button, with long-press and double press, perhaps even extra long press and triple press.

For developing stuff like this that doesn't need compilation, you can run the AppImage with `--appimage-extract`.

**Comment by poire-z** [comment]
I have no idea how key are used, but looking at the existing mapping:
```
        event_map = {
            [KEY_MENU] = "Menu",
            [KEY_PREV] = "LPgBack",
            [KEY_NEXT] = "LPgFwd",
        },
```
and assuming Left and Right events are not as useful as the LPgBack and LPgFwd, you could try using:
```
+            [KEY_UP] = "Up", -- or "Menu"
+            [KEY_DOWN] = "Down", or "Press" or something else?
+            [KEY_LEFT] = "LPgBack",
+            [KEY_RIGHT] = "LPgFwd",
+            [KEY_OK] = "Press",
```

**Comment by Frenzie** [comment]
@poire-z Maybe if you just get rid of left (no room for mistakes if you accidentally press right once too many) but right is used a fair bit, for example to access all the filemanager functions.

Part of the reason I suggested getting rid of page back is because just "back" is more or less synonymous with page back in regular reading anyway. (Not entirely because you won't be adding to the location stack with it but that probably doesn't matter most of the time.

**Comment by Frenzie** [comment]
@lenormf
> I'm not sure how to make it so those bindings would be only set when the host system is a PocketBook515, so I've hardcoded them into the event map.

Restricting it to that one device doesn't sound very sensible to me anyway. Devices with roughly the same buttons will want the same actions and those without just won't emit them. Could you please put that in a PR?

**Comment by lenormf** [comment]
Created PRs for the changes I tested.

I guess I could have all files be opened with KOReader by default, to avoid having to use <kbd>up</kbd> and <kbd>down</kbd> in the file manager, and repurpose those two keys to "menu" - that would allow me to exit the onboard menu. As @poire-z suggested.

But getting a long press on <kbd>OK</kbd> to mean "Menu" would go a long way, I'll try to find time to experiment with that.

Thanks again for the quick replies and help!

**Comment by lenormf** [comment]
Looks like this topic is recurrent, #3818 #4029, but nothing has come out of it yet. It looks like the consensus is to re-organize mappings in the way described earlier when a `hasFewKeys` option is enabled? Or come up with an alternative PocketBook structure that implements those by default?

**Comment by Frenzie** [comment]
@lenormf #3818 is about something completely different. It's not saying long press should be supported *on keys*, but that the action which happens to be activated by long-press on a touch screen should be accessible. Because without that, you can only set global defaults by editing the configuration on a PC.

Anyway, let's please move any further discussion to #4029.

**Comment by lenormf** [comment]
I guess this issue could be closed, now?

**Comment by Frenzie** [comment]
Probably, I'm not quite clear on if this Basic Lux 2 is a touchscreen but I'll just close it for now and we can always reopen it if necessary.

**Comment by tosyu** [comment]
>  if this Basic Lux 2 is a touchscreen
it's not :)

**Comment by Frenzie** [comment]
@tosyu I'll add it to the title of the other issue. Is this also one with just a dpad, ok button & page up/down?

**Comment by tosyu** [comment]
yes, dpad, ok, next, prev

as in this picture

https://goodereader.com/blog/uploads/images/616BasicLux2_ObsidianBlack_03_eng.jpg
