### ISSUE TITLE
Can't login to 印象笔记（Evernote，China）

### ISSUE THREAD

**Issue by Tsiung** [koreader/koreader#6171]
* KOReader version:2020.04.1
* Device:kindle pw4

#### Issue
Can't login to 印象笔记（Evernote，China）

Open Epub or PDF -> Login to 印象笔记（Evernote，China） -> An error occurred while loggin in:
plugins/evernote.koplugin/EvernoteOAuth.lua:280: Target URL was not found in the response on login

**Comment by Galunid** [comment]
@Tsiung I assume you're using two factor authentication, currently I don't have access to 印象笔记, nor any way to understand their api. Could you try changing line 109 of `koreader/plugins/evernote.koplugin/EvernoteOAuth.lua`    from `tfa = "/OTCAuth.action",` to `tfa = "/OAuth.action",`?

**Comment by Tsiung** [comment]
I don't use two factor authentication。I had changed line 109. It work for Evernote,but not work for 印象笔记.

**Comment by Tsiung** [comment]
@Galunid I don't use two factor authentication. i have changed line 108 to OAuth.action. But the error also is error 280: Target URL was not found in the response on login

**Comment by Galunid** [comment]
@Tsiung As a temporary fix, you can try this:
change `login = "/Login.action",` to `login = "/OAuth.action",` on line 108, and `return self:handleTwoFactor()` to `return true` on line 324. Both changes in file `koreader/plugins/evernote.koplugin/EvernoteOAuth.lua`. This will make it impossible to use two factor authentication though. I made 印象笔记 account, and it works.

**Comment by Galunid** [comment]
@Frenzie The above mentioned fix, disables two factor authentication, but as far as I can tell, it was never "properly" implemented
```lua
  self.postData['tfa']['code'] = self.code or ('xxxxxx'):gsub("x", function()
          return string.char(random(97, 122)) end)
```
This looks, like we try to guess the code, `self.code` is never set. Their API changed, so that we get http code 302, and get redirected on sign in, code 302 was used to "detect" when 2fa was needed. Is it fine, to disable 2fa completely?

**Comment by Tsiung** [comment]
@Galunid  Thank you . it work. I had logined to 印象笔记.

**Comment by Frenzie** [comment]
@Galunid I don't really know anything about this plugin or the Evernote API.

**Comment by NiLuJe** [comment]
IIRC, Evernote provides auth tokens for 2FA-challenged clients, so we don't really need to if that's what the hack looks like ;).
