### ISSUE TITLE
Internal links in epub don't work

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#6175]
* KOReader version: 2020.04.1
* Device: Galaxay tab

https://www.dropbox.com/s/fmy1behnlqi3f84/links.epub?dl=0

Using the calibre ebook reader on the epub above gives no problem with the embedded links in the book (the first set of links appear around 5% in the book).

Clicking these links on koreader gives an 'invalid or external link' error

**Comment by Frenzie** [comment]
> I suppose links that target hidden elements should still be working?

I'll have to double check, but on display:none it doesn't seem like it would make sense for them to work.

**Comment by poire-z** [comment]
I think we can solve the issue with this in cre.cpp (similar in buddy `getPosFromXPointer()`) :
```diff
@@ -784,10 +793,25 @@ static int getPageFromXPointer(lua_State *L) {

        int page = 1;
        ldomXPointer xp = doc->dom_doc->createXPointer(lString16(xpointer_str));
+       if ( !xp.isNull() ) { // Found in document
+               // Ensure xp points to a visible node that has a y in the document.
+               // If it is invisible, get the next visible node
+               ldomXPointerEx xpe = xp;
+               if ( xpe.isText() )
+                       xpe.parent();
+               if ( xpe.getNode()->getRendMethod() == erm_invisible ) {
+                       xpe = xp;
+                       while ( xpe.nextElement() ) {
+                               if ( xpe.getNode()->getRendMethod() != erm_invisible ) {
+                                       xp = xpe;
+                                       break;
+                               }
+                       }
+               }
+               page = doc->text_view->getBookmarkPage(xp) + 1;
+       }

-       page = doc->text_view->getBookmarkPage(xp) + 1;
        lua_pushinteger(L, page);
-
        return 1;
 }
```
Getting the next visible element (and not the previous one) looks like the most obvious, right?

**Comment by Frenzie** [comment]
Agreed.
