### ISSUE TITLE
OPDS not seen when switched to Russian interface

### ISSUE THREAD

**Issue by alexmog123** [koreader/koreader#6176]
* KOReader version: 2020.04.1
* Device: Kobo Aura One

#### Issue
OPDS menu is not visible when I choose Russian in koreader 
#### Steps to reproduce
When in English, I see OPDS. When switched over to Russian, the menu item disappears.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by Frenzie** [comment]
I can't confirm, but perhaps the problem is that the menu differs between the file manager and the reader?

![Screenshot_2020-05-23_09-31-29](https://user-images.githubusercontent.com/202757/82724726-6f284300-9cd8-11ea-9bea-c7b8be092686.png)

**Comment by alexmog123** [comment]
[crash.log](https://github.com/koreader/koreader/files/4673083/crash.log)
Thanks for looking into the issue!

**Comment by alexmog123** [comment]
I see same munu, but "Search all text" (in Russian) after goodreads

**Comment by hius07** [comment]
> I see same munu, but "Search all text" (in Russian) after goodreads

It is "Fulltext search", and should exist in the reader menu only, not in FM menu.
What happens if you choose this item?

**Comment by Frenzie** [comment]
@alexmog123 Sorry, I left it implicit, but that should mean you need to exit the reader to go to the file manager first.

![Screenshot_2020-05-24_10-56-37](https://user-images.githubusercontent.com/202757/82749983-5c337280-9dad-11ea-98aa-129b9bfc1cc0.png)

Downloading files from OPDS is considered a type of file management; while having everything available everywhere is possible it'd all become rather cluttered.

**Comment by alexmog123** [comment]
OMG found it! Thanks a lot for your help!

**Comment by gingerbeardman** [comment]
I have the plugin enabled but I don't see this icon in the top of my reader.

Is there anything I can check?

**Comment by Frenzie** [comment]
Thanks! That screenshot is positively ancient, but it's always been a menu under the magnifying glass. :-)
