### ISSUE TITLE
Cervantes: touch problem after disabling the USB mass storage functionality

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#6189]
* KOReader version: 2020-05-3-geb92a95_2020-05-24
* Device: Cervantes 4

#### Issue
After disabling the USB mass storage functionality, the touch functionality is always interpreted as a long touch. When I make a simple touch in order to change the page or to see the menu, Koreader opens the dictionary on the word I quickly touched.
I need to switch off completely the reader in order to get back the normal behaviour.

#### Steps to reproduce
Start the USB mass storage fuctionality
Add / remove files from Calibre
Click on the physical button of the Cervantes in order to switch of the USB mass storage and go back to KoReader
Touch the screen...

**Comment by NiLuJe** [comment]
A crash.log after switching to verbose debug (Tools > Dev settings in the FM's top menu) might be helpful until someone familiar with the Cervantes platform chimes in ;).

**Comment by poire-z** [comment]
May be #6186 will have some magical effect :)
Please try again with tomorrow nightly, and tell us.

**Comment by pazos** [comment]
I can't reproduce on v2020.05-7. 

@Brnoch: the usb storage thingy runs outside KOReader and doesn't use the touchscreen at all. If you can reproduce this by entering and leaving USBMS then please try to reproduce it with "Exit" -> "Exit".
