### ISSUE TITLE
Kobo Koreader book-read-view has wired line near left and right side

### ISSUE THREAD

**Issue by superliujian** [koreader/koreader#6196]
* KOReader version: 2020.4.1 & 2020.5
* Device: Kobo Aura

#### Issue
Kobo Koreader book-read-view has wired line near left and right side (see attache image)

#### Steps to reproduce
I'm sorry I didn't have sepecified settings,the frist time (default setting) I opened the book, it had such issue, and I tried many books, changed many settings, still have the same issue.
In KSM menu, or Plato reader, everything is OK, so I think  it's not my device issue.
![image_20200527071745](https://user-images.githubusercontent.com/1275314/82959571-9ccbff80-9fea-11ea-8ba2-f5859a66b778.jpg)

##### `crash.log` (if applicable)
[settings.reader.zip](https://github.com/koreader/koreader/files/4685607/settings.reader.zip)

**Comment by NiLuJe** [comment]
That's the "Perception expander" (speed reading) plugin.

**Comment by superliujian** [comment]
I see, thanks very much.
