### ISSUE TITLE
[Question] Instruction for Joplin note plugin

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#6197]
* KOReader version: 2020.05
* Device: kindle PW4
I have difficulty with Evernote login, (in Vietnam),then I switched to Joplin. However, I did search in the Koreader Wiki and I couldn't find instruction for Joplin plugin:
- How to login?
- How to syn note/ hightlight with my Android Joplin app?

I did go to Joplin site but too much technical information over there for a non-technical guy like me.

Could you help to route me to appropriate page?

Thank you very much in advance.

**Comment by pazos** [comment]
> [...] too much technical information [...] for a non-technical guy like me

Yep. I don't think I would help with that. See my next answers.

> How to syn note/ hightlight with my Android Joplin app?

You can't. You need to sync with your Windows/Linux client. Then changes will be forwarded to all your configured clients in all platforms.

> How to login?

From the [plugin info itself](https://github.com/koreader/koreader/blob/master/plugins/evernote.koplugin/main.lua#L245-L253)

> You can enter your auth token on your computer by saving an empty token. Then quit KOReader, edit the evernote.joplin_token field in koreader/settings.reader.lua after creating a backup, and restart KOReader once you're done.
To export to Joplin, you must forward the IP and port used by this plugin to the localhost:port on which Joplin is listening. This can be done with socat or a similar program. For example:

> For Windows: `netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=41185 connectaddress=localhost connectport=41184`
> For Linux:  `socat tcp-listen:41185,reuseaddr,fork tcp:localhost:41184`
