### ISSUE TITLE
Evernote is not working on pocketbook 740

### ISSUE THREAD

**Issue by Geniusssmit** [koreader/koreader#6198]
* KOReader version: last
* Device: pocketbook 740

#### Issue
Evernote is not working on pocketbook 740
#### Steps to reproduce
try to export notes, error appears
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Providing a crash.log is *definitely* applicable here.

**Comment by Geniusssmit** [comment]
> Providing a crash.log is _definitely_ applicable here.

[crash.log](https://github.com/koreader/koreader/files/4691085/crash.log)

**Comment by Frenzie** [comment]
Where (or rather when) should I look for the relevant part of the log?

Random thing that sticks out to me:
```
g_mkdir failed: Read-only file system
```

**Comment by Geniusssmit** [comment]
![image](https://user-images.githubusercontent.com/24941285/83107241-8f844300-a0c6-11ea-8613-a89d32d65a95.png)
there is no crash, but error when logging in

**Comment by Galunid** [comment]
@Geniusssmit Could you provide exact version you're running? `Last top menu entry -> Version`

**Comment by Galunid** [comment]
As a side note, `EvernoteOAuth.lua` doesn't log anything.

**Comment by Geniusssmit** [comment]
> As a side note, `EvernoteOAuth.lua` doesn't log anything.

v2020.04.1

**Comment by Galunid** [comment]
@Geniusssmit What I thought. You aren't on the latest version, latest version is v2020.05 and it should be fixed :)

**Comment by Geniusssmit** [comment]
I see, I will try it then

**Comment by Geniusssmit** [comment]
Works as expected
