### ISSUE TITLE
how to generate direction rearranged pdf?

### ISSUE THREAD

**Issue by honahlee** [koreader/koreader#6200]
* KOReader version: new
* Device: kindle paperwhite and PC

#### Issue

I'd like to know that is there any way to split the vertical text(right to left) in the scanned pdf, 
word by word in picture, and transform them into horizontal text view(left to right)？

(no need to OCR to recognize the text, or the words...
only need to change the direction of the text, as a picture, so the original layout, font and size could be kept, and generate a new rearranged pdf.)

![image](https://user-images.githubusercontent.com/50106908/83121656-2ff95800-a105-11ea-8331-21f59b8e9c2d.png)

------------>>>>

![image](https://user-images.githubusercontent.com/50106908/83121694-3c7db080-a105-11ea-9d7d-76840ccc5495.png)

thanks a lot!

**Comment by Frenzie** [comment]
I don't think that's supported, but you could check over at https://www.willus.com/k2pdfopt/ to know for sure.
