### ISSUE TITLE
Some issues with CHM books

### ISSUE THREAD

**Issue by kingkongace** [koreader/koreader#6202]
1. CHM e-book has been disorderly, and at the same time, it can not be opened or the directory of CHM e-book can not be opened. Once the capacity of CHM e-book is a little large, it is even more difficult to open.

2. This problem exists for a long time. It may have lasted for several years, but it has not been modified. It's a pity that we hope to change it.

3. In addition, the speed of opening files and folders is very slow. Some of them need to wait a few minutes to open, or are stuck.

4. I hope to be able to make Windows version, which is suitable for PC use.

**Comment by poire-z** [comment]
Not much activity on the CHM front:
https://github.com/koreader/crengine/commits/master/crengine/src/chmfmt.cpp
and not much interest from me to dive into the CHM code:
https://github.com/koreader/crengine/blob/master/crengine/src/chmfmt.cpp
and the thirdparty library crengine uses:
https://github.com/koreader/crengine/tree/master/thirdparty/chmlib
crengine has version 0.38, while upstream is at 0.40 - but it's at 0.40 for 11 years :)
http://www.jedrea.com/chmlib/ https://github.com/jedwing/CHMLib

**Comment by kingkongace** [comment]
> CHM 方面的活动不多
> [：https://github.com/koreader/crengine/commits/master/crengine/src/chmfmt.cpp，](https://github.com/koreader/crengine/commits/master/crengine/src/chmfmt.cpp)
> 我不太有兴趣潜入 CHM 代码
> [：https://github.com/koreader/crengine/blob/master/crengine/src/chmfmt.cpp](https://github.com/koreader/crengine/blob/master/crengine/src/chmfmt.cpp)
> 和第三方库 crengine 使用
> [：https://github.com/koreader/crengine/tree/master/thirdparty/chmlib](https://github.com/koreader/crengine/tree/master/thirdparty/chmlib)
> crengine 版本为 0.38，而上游为 0.40 - 但它在 0.40 :)
> [http://www.jedrea.com/chmlib/https://github.com/jedwing/CHMLib](http://www.jedrea.com/chmlib/)

Thank you for your reply. I'm a user from China. I don't know much about software programming. Because of long-term use, I also like CHM e-book very much, because it can contain a lot of content, but it is really difficult to open in koreader, hoping to change the existing situation. Because I don't understand programming, I can't understand the reply you sent me. My English is very weak. I translate words through translation software. If there is any disrespect, please forgive me.

**Comment by poire-z** [comment]
No problem.
I was just saying that indeed, nobody has worked on it for more than 10 years (even the original authors from who we took the code 10 years ago).
And I put some links in case somebody else is interested to work on that.

But to be clear: there is very little chance that this will happen.
KOReader will probably keep being bad with CHM.
