### ISSUE TITLE
关于koreader在基于树莓派上的平板电脑移植问题

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6206]
目前我遇到的问题是这样的，就是我安装了2020年5月版本的koreader之后，发现只支持鼠标点击显示上下的菜单栏，而通过手势点击的时候只显示是否将该页面设为主目录这个选项，我想知道有什么办法让这个应用支持手势操作，在我的树莓派平板电脑上面

At present, the problem I have encountered is that after I installed the May 2020 version of koreader, I found that it only supports mouse click to display the menu bar up and down, but only displays whether to set the page as the main directory when I click through the gesture. I want to know how to make this application support gesture operation on my raspberry pie tablet
![image](https://user-images.githubusercontent.com/60098441/83208679-ddfa1600-a188-11ea-98af-7cd127bd4fab.png)

![image](https://user-images.githubusercontent.com/60098441/83208688-e18d9d00-a188-11ea-9431-5b4e07ec4623.png)

**Comment by pazos** [comment]
@kuailedeluojie-sudo: please don't open a new ticket for each new issue you find. Use #6207 for everything. Thanks!
