### ISSUE TITLE
Development a custom device based on Rasperry Pi or similar board.

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6207]
我最近怎在开发一款arm的电子阅读器平板， 想移植这个项目到我的硬件上面，但是我对这个项目不熟悉，我希望能和中国的开发者交流一下，这是我的电子邮箱:812788375@qq.com，如果有中国的开发者看到的话可以发邮件给我，然后细聊，谢谢！

How do I develop an arm e-reader tablet recently? I want to transplant this project to my hardware, but I am not familiar with this project. I hope to communicate with Chinese developers. This is my email: 812788375@qq.com , if you have Chinese developers to see it, you can email me, and then chat, thank you!

![image](https://user-images.githubusercontent.com/60098441/83208624-bacf6680-a188-11ea-916d-19ec8adfac94.png)

![image](https://user-images.githubusercontent.com/60098441/83208636-c327a180-a188-11ea-933a-d340f2371f7d.png)

**Comment by pazos** [comment]
The raspberry pi is already supported. You can run even without X11 (SDL is required)
If you want to make a custom device then you can create a new SDL device definition with the description of your board. Currently it is using https://github.com/koreader/koreader/blob/master/frontend/device/sdl/device.lua#L128-L131

We have Chinese developers but they're not very active lately.

**Comment by kuailedeluojie-sudo** [comment]
> 树莓派已受支持。您甚至可以在没有X11的情况下运行（需要SDL）。
> 如果要制作自定义设备，则可以使用板卡描述创建新的SDL设备定义。当前它正在使用https://github.com/koreader/koreader/blob/master/frontend/device/sdl/device.lua#L128-L131
> 
> 我们有中国开发商，但他们最近不太活跃。
如上面我提到的两张图片中的内容，有更好的适配版本推荐吗？我用的是 koreader-2020.05-armhf.deb 这个文件包，我想做的是支持Linux平板电脑手势操作的，而不是鼠标操作。

As I mentioned above in the two pictures, is there a better adaptation version recommended? I used koreader-2020.05- armhf.deb This package, I want to do is to support Linux tablet gesture operation, not mouse operation.

**Comment by kuailedeluojie-sudo** [comment]
> 树莓派已受支持。您甚至可以在没有X11的情况下运行（需要SDL）。
> 如果要制作自定义设备，则可以使用板卡描述创建新的SDL设备定义。当前它正在使用https://github.com/koreader/koreader/blob/master/frontend/device/sdl/device.lua#L128-L131
> 
> 我们有中国开发商，但他们最近不太活跃。



How to run koreader without running X11?
怎么在没有运行X11的情况下来运行koreader?

**Comment by pazos** [comment]
> As I mentioned above in the two pictures, is there a better adaptation version recommended?

Not yet. :smile: 

> How to run koreader without running X11?

Raspbian has an option somewhere to start in console mode. Check that option (instead of graphical mode), reboot, login into your account and type `koreader`. Do it with a keyboard attached.

> I want to do is to support Linux tablet gesture operation, not mouse operation

If your touchscreen is recognized as a linux input device (and generate common events in /dev/input/eventx) then you can use that instead of SDL input. But that's is an advanced topic. The mouse icon you see is probably provided by X11, so please check what happens if you run it without it.

Having a shell opened via serial or ssh can help you debugging. You need to edit `/usr/bin/koreader` and redirect `./reader.lua` output to a file and use `tail -f /path/to/file` to see debug messages while you are running KOReader.

For example:
`./reader.lua  "${ARGS}" > /tmp/koreader.log 2>&1`
`tail -f /tmp/koreader.log`

**Comment by kuailedeluojie-sudo** [comment]
> > 正如我在上面的两张图片中所提到的，建议使用更好的适应版本吗？
> 
> 还没。 😄
> 
> > 如何在不运行X11的情况下运行koreader？
> 
> Raspbian有一个选项可以在控制台模式下启动。检查该选项（而不是图形模式），重新启动，登录到您的帐户并输入`koreader`。使用连接的键盘进行操作。
> 
> > 我要做的就是支持Linux平板手势操作，而不是鼠标操作
> 
> 如果您的触摸屏被识别为linux输入设备（并在/ dev / input / eventx中生成常见事件），则可以使用它代替SDL输入。但这是一个高级话题。您看到的鼠标图标可能是X11所提供的，因此请检查如果不运行它会发生什么情况。
> 
> 通过串行或ssh打开外壳可以帮助您调试。您需要编辑输出`/usr/bin/koreader`并将其重定向`./reader.lua`到文件，并`tail -f /path/to/file`在运行KOReader时用于查看调试消息。
> 
> 例如：
> `./reader.lua "${ARGS}" > /tmp/koreader.log 2>&1`
> `tail -f /tmp/koreader.log`

Can we use Ubuntu-touch to implement gesture operation?
换个思路行不行，可以用ubuntu-touch这个版本来实现手势操作没有？

What's the help of viewing these debugging information for me to support gesture operation?
查看这些调试信息对于我想支持手势操作有什么帮助？

**Comment by pazos** [comment]
Ubuntu Touch uses the same backend: SDL.
Gestures work fine in SDL: not multitouch gestures but [multiswipes](https://github.com/koreader/koreader/wiki/multiswipes)

**Comment by kuailedeluojie-sudo** [comment]
> Ubuntu Touch使用相同的后端：SDL。
> 手势在SDL中可以正常工作：不是多点触摸手势，而是[多次滑动](https://github.com/koreader/koreader/wiki/multiswipes)

OK, I'll try to build it in raspberry pie. If you have any questions, please come again. Thank you!
好的，我尝试在树莓派里面构建一下，遇到问题的话再来请教，谢谢你！

**Comment by Frenzie** [comment]
Btw, while we don't currently implement multitouch, it probably shouldn't be terribly hard to do so: https://wiki.libsdl.org/SDL_MultiGestureEvent

NB By not hard I don't mean it can be done in little time; in fact I suspect it would take at least several hours. But insofar as there's anything actually difficult involved it'll already have been solved somewhere at least in principle.

**Comment by kuailedeluojie-sudo** [comment]
> 顺便说一句，虽然我们目前还没有实现多点触控，但这样做可能并不难：[https](https://wiki.libsdl.org/SDL_MultiGestureEvent) : [//wiki.libsdl.org/SDL_MultiGestureEvent](https://wiki.libsdl.org/SDL_MultiGestureEvent)
> 
> 注意：我并不意味着可以在短时间内完成。实际上，我怀疑至少要花几个小时。但是只要涉及到任何实际困难，至少在原则上已经可以解决。

In fact, it's a little difficult for me to compile Ubuntu touch on this machine. If there is a compiled koreader version of thread, it's good. So I don't need to compile again on raspberry pie to do the same thing.
实际上对于我来说，自己编译Ubuntu-touch到这个机器上的过程还是有点难度的，如果有线程的编译好的koreader版本就好了，这样我就不需要在树莓派上再次编译，做重复的事情。

**Comment by pazos** [comment]
> In fact, it's a little difficult for me to compile Ubuntu touch on this machine

You don't need Ubuntu Touch at all. Stay with plain linux. It is exactly the same for what you're trying to do.

Please record a video that showcases how the touchscreen is working to figure out what you need to do next!

**Comment by kuailedeluojie-sudo** [comment]
> > 实际上，在这台机器上编译Ubuntu touch对我来说有点困难
> 
> 您根本不需要Ubuntu Touch。呆在纯Linux上。您尝试执行的操作完全相同。
> 
> 请录制一段视频，展示触摸屏的工作原理，以弄清楚下一步需要做什么！




![5ab03efb5b1d4b56af2cbb72fa5c66c8 (1)](https://user-images.githubusercontent.com/60098441/83316039-4531cc00-a256-11ea-904c-15a160b8d00f.gif)
![5ab03efb5b1d4b56af2cbb72fa5c66c8 (2)](https://user-images.githubusercontent.com/60098441/83316054-537fe800-a256-11ea-9495-ba16e1a5ed51.gif)
![5ab03efb5b1d4b56af2cbb72fa5c66c8 (3)](https://user-images.githubusercontent.com/60098441/83316077-6db9c600-a256-11ea-8b69-a9a406fd9bb0.gif)
![5ab03efb5b1d4b56af2cbb72fa5c66c8 (4)](https://user-images.githubusercontent.com/60098441/83316172-fd5f7480-a256-11ea-83a1-02edc9f95745.gif)
As shown in the above four dynamic pictures, when clicking or sliding the touch screen by hand, koreader can't perform relevant actions, which is different from what I expected. What I want is that koreader can respond to my touch actions. Last night, I thought again, is it possible to brush the system into a Linux tablet system, and then try this version of Ubuntu touch.

如上面四张动态图片看到的那样，用手点击或者滑动触摸屏的时候，koreader不能执行相关的动作，和我预期的不一样，我想的是koreader能相应我的触摸式动作，昨天晚上我又想了一下，是不是可以把系统刷成Linux平板系统，然后用ubuntu-touch这个版本来尝试。

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/83334530-c54d4580-a2d9-11ea-8762-0e2f4b173209.png)

2020-5-13这个版本构建出来的这个版本有问题
There is a problem with the version built on May 13, 2020

**Comment by NiLuJe** [comment]
That's either a seriously broken distro, a seriously broken multilib setup, or both.

I stopped trying to understand how Debian ended up doing multilib, but I know it's... weird to begin with, but I'm extremely unfamiliar with it.

But llibm should definitely be a pat of the base system (glibc, to be exact), and that path looks like a somewhat decent multilib path?

**Comment by kuailedeluojie-sudo** [comment]
> 那要么是一个严重破坏的发行版，一个是严重破坏的multilib设置，要么两者都是。
> 
> 我不再试图了解Debian最终是怎么做multilib的，但是我知道这很...奇怪，但是我对此非常陌生，所以请多加些盐。
> 
> 但是libm绝对应该是基本系统的一部分（确切地说，是glibc），并且该路径看起来像是相当不错的multilib路径？

2020-5-10构建出来是可以正常使用的。
2020-5-10It can be used normally..

**Comment by pazos** [comment]
Are you trying to do `./kodev release debian-armhf` in the raspberry pi itself?. Debian armel/armhf releases are intended to **crosscompile** from an x86_64 host.

If you want to natively build on your raspberry pi you should do `./kodev release debian` instead. It can take you days to build.

**Comment by kuailedeluojie-sudo** [comment]
> 您是否想`./kodev release debian-armhf`在树莓派本身中做？Debian的阿梅尔/ armhf发布旨在**crosscompile**从x86_64的主机。
> 
> 如果您想在树莓派上原生构建，则应该这样做`./kodev release debian`。构建可能需要几天的时间。

Raspberry pie itself doesn't have enough memory.
树莓派本身的内存不够。

**Comment by pazos** [comment]
Closing this ticket but still watching it. Please keep us informed about your progress ;)

**Comment by kuailedeluojie-sudo** [comment]
正在做这部分的开发工作，只是没有进展，还是不支持触摸手势，如果解决支持触摸手势的问题那么就很好解决。

**Comment by kuailedeluojie-sudo** [comment]
> 关闭这张票，但仍在观看。请让我们了解您的进度；）

正在做这部分的开发工作，只是没有进展，还是不支持触摸手势，如果解决支持触摸手势的问题那么就很好解决。

**Comment by kuailedeluojie-sudo** [comment]
[*] Current time: 07/01/20-21:05:12
 [*] Version: v2020.06-16-geee54ffb_2020-06-22

ffi.load: SDL2
ffi.load: SDL2
ffi.load: blitbuffer
/usr/lib/koreader/luajit: ./ffi/SDL2_0.lua:92: Cannot initialize SDL: 
stack traceback:
        [C]: in function 'error'
        ./ffi/SDL2_0.lua:92: in function 'open'
        ./ffi/framebuffer_SDL2_0.lua:13: in function 'init'
        ./ffi/framebuffer.lua:70: in function 'new'
        frontend/device/sdl/device.lua:164: in function 'init'
        frontend/device.lua:54: in main chunk
        [C]: in function 'require'
        ./reader.lua:119: in main chunk
        [C]: at 0x004cef09
