### ISSUE TITLE
2020.05 Problems encountered in porting to arm development board

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6208]
/usr/bin/koreader: line 2: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/29/20-11:25:50
 [*] Version: v2020.05

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load: blitbuffer
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
ffi.load: gtk-3
ffi.load (warning): libgtk-3.so: cannot open shared object file: No such file or directory
ffi.load: gtk-3.so.0
ffi.load (warning): /usr/lib/arm-linux-gnueabihf/libpangoft2-1.0.so.0: undefined symbol: hb_glib_script_to_script

**Comment by pazos** [comment]
@kuailedeluojie-sudo: please don't open a new ticket for each new issue you find. Use #6207 for everything. Thanks!

**Comment by Frenzie** [comment]
You could unset it or even just leave it out entirely. Those scripts are platform-specific.

**Comment by kuailedeluojie-sudo** [comment]
> 您可以取消设置它，甚至可以完全不使用它。这些脚本是特定于平台的。

ok，thank you！

**Comment by kuailedeluojie-sudo** [comment]
> @ kuailedeluojie-sudo：请不要为发现的每个新问题打开新票证。使用[＃6207](https://github.com/koreader/koreader/issues/6207)进行所有操作。谢谢！

OK！thank you！
