### ISSUE TITLE
Debian/AppImage packages don't show all items on status bar

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#6210]
* KOReader version: 2020-05
* Device: linux emulator running on Ubuntu 20.04

#### Issue

I have the status bar set to "show all items at once". Some items selected (e.g., percentage read) do not show.

Changing things like alignment, position of progress bar, toggling the status bar items, sorting them, etc do not change the result

#### Steps to reproduce

Turn on Show all items
Turn on Progress Percentage

See attached pictures. I expect to see Current page, Current time, Pages left in Chapter, and Percentage read; but I don't see Percentage read. See attached screen shots.
![Screenshot from 2020-05-29 09-24-39](https://user-images.githubusercontent.com/46451014/83265182-2288b000-a18f-11ea-9564-9f69a824d717.png)
![Screenshot from 2020-05-29 09-29-25](https://user-images.githubusercontent.com/46451014/83265183-23214680-a18f-11ea-8cb1-65166f077692.png)

**Comment by poire-z** [comment]
Could it be only those items that don't get their symbol rendered correctly in the menu (those that get `[?]` ?
These symbols require _our_ nerdfont (hacked a bit) - dunno why your emulator is not using it.
Try to switch to using letters instead of icons to see if it changes anything: `Status bar > Settings > Prefix > [x] Letters`.

**Comment by JasonInOttawa** [comment]
Thanks for your reply. This has the same result
![Screenshot from 2020-05-29 10-17-20](https://user-images.githubusercontent.com/46451014/83269901-bf4e4c00-a195-11ea-9375-67d41c87f3dd.png)
 (see attached)

**Comment by JasonInOttawa** [comment]
Turning on Battery status (which has an icon) also doesn't work.

**Comment by poire-z** [comment]
It works for me (with nerdfont in or out), and I don't see a reason for it to not work looking at the code.
You might need to debug and see if this is called, 
https://github.com/koreader/koreader/blob/03140f505ca475f185bdc197b175ee8a59cf774f/frontend/apps/reader/modules/readerfooter.lua#L196-L207
Try replacing it with `percentage = function(footer) return "BLAH" end` , and/or insert here and there stuff like:
`require("logger").warn(string_percentage, footer.progress_bar.percentage)`

Try to just enable one, and see which items work standalone and which don't, might give us a clue if there is one or more.

**Comment by poire-z** [comment]
So, _only_ percentage doesn't work? All others work ?

That happens on all book, or only this one?
Backup your settings.reader.lua and default.persistent.lua and remove them, to start with clean settings, and see if it changes anything.

(And see why nerfont is not being used - it should have been copied in` base/build/x86_64-linux-gnu-debug/fonts/` as `nerdfonts/symbols.ttf`, may be your setup is messed up.)

**Comment by JasonInOttawa** [comment]
Thanks very much for your replies.

Some iems work, many don't. For example, Battery status doesn't work.

I'm installing the deb, not building on Linux. I did have this issue in the previous build too (2020-04.1).

I see symbols.ttf here:

/usr/lib/koreader/fonts/nerdfonts/symbols.ttf

which I think is the right spot. Permission is set to -rw-r--r--

I removed ~/.config/koreader/settings.reader.lua and restarted, with no change.. I couldn't find default.persistent.lua in my home directory or in /usr/lib/koreader.

Thanks again for all your help.

**Comment by NiLuJe** [comment]
Ah, that may be a critical point. Pinging @pazos who may have a better idea of why the Debian build might be finicky.

**Comment by poire-z** [comment]
> Some iems work, many don't.

Please list all those who don't. We need clues :)

**Comment by JasonInOttawa** [comment]
Well,  ok :)

It looks like everything after Pages left in chapter doesn't work:

![Screenshot from 2020-05-29 12-12-32](https://user-images.githubusercontent.com/46451014/83281181-b9606700-a1a5-11ea-902d-e8b56a042f33.png)
![Screenshot from 2020-05-29 12-11-34](https://user-images.githubusercontent.com/46451014/83281183-b9606700-a1a5-11ea-9601-ba9191ef389b.png)
![Screenshot from 2020-05-29 12-11-25](https://user-images.githubusercontent.com/46451014/83281184-b9606700-a1a5-11ea-9c07-f0c203f5876d.png)

**Comment by JasonInOttawa** [comment]
The first screen shot is the progress bar with no items shown over it. The other two are the ones I turned on.

Thanks again!

**Comment by Frenzie** [comment]
Sidenote, all shows well in the Debian version I have installed right now (2020.03.2).

![Screenshot_2020-05-29_18-34-19](https://user-images.githubusercontent.com/202757/83283166-0ca0dc80-a1db-11ea-80ac-dc1d7e496529.png)

**Comment by JasonInOttawa** [comment]
Thanks. I uninstalled 2020.05 and put on 2020.03.2 and it worked for me as well:

![Screenshot from 2020-05-29 12-43-05](https://user-images.githubusercontent.com/46451014/83284000-1827df80-a1aa-11ea-9e5f-2d36504f1f9f.png)

**Comment by JasonInOttawa** [comment]
That did it. I uninstalled 2020.03.2 and put 2020.05 and removed those lines:


![Screenshot from 2020-05-29 13-25-46](https://user-images.githubusercontent.com/46451014/83287669-0cd7b280-a1b0-11ea-91ff-64df453fb631.png)
![Screenshot from 2020-05-29 13-25-37](https://user-images.githubusercontent.com/46451014/83287670-0cd7b280-a1b0-11ea-9869-afd1b61f8590.png)

**Comment by NiLuJe** [comment]
@poire-z: That's another 'nil in a table', right? :D.

**Comment by poire-z** [comment]
Yep, probably :/ :)

**Comment by poire-z** [comment]
Was going to suggest @pazos: may be you could just remove this part and let the battery in the footer for Desktop - users can still not have it shown via the menu.
But my theory above (that it screws everything after it) is wrong: we remove wifi_status if not android, but we can see on the emulator Book title which is after it.
So, I guess we have to rebuild that MODE table (or use it some other way) - which might not be too complicated. I'll see to it this weekend.

**Comment by pazos** [comment]
> Was going to suggest @pazos: may be you could just remove this part and let the battery in the footer for Desktop - users can still not have it shown via the menu.
> But my theory above (that it screws everything after it) is wrong: we remove wifi_status if not android, but we can see on the emulator Book title which is after it.
> So, I guess we have to rebuild that MODE table (or use it some other way) - which might not be too complicated. I'll see to it this weekend.

As you like. I still like the battery removed from the top menu, near the hour.

Anyways to fix the isDesktop mess

```diff
--- a/readerfooter.lua  2020-05-23 11:38:10.000000000 +0200
+++ b/readerfooter.lua  2020-05-29 20:07:32.827311080 +0200
@@ -308,7 +308,7 @@
         all_at_once = false,
         reclaim_height = false,
         toc_markers = true,
-        battery = true,
+        battery = not Device:isDesktop(),
         time = true,
         page_progress = true,
         pages_left = true,
@@ -336,12 +336,12 @@
     if not Device:hasFrontlight() then
         MODE.frontlight = nil
     end
-    if Device:isDesktop() then
-        MODE.battery = nil
-    end
     for k, v in pairs(MODE) do
         mode_tbl[v] = k
     end
+    if Device:isDesktop() then
+        table.remove(mode_tbl, MODE.battery)
+    end
     for i = 0, #mode_tbl do
         mode_name = mode_tbl[i]
         if mode_name then
@@ -1519,7 +1519,9 @@
     table.insert(sub_items, getMinibarOption("page_progress"))
     table.insert(sub_items, getMinibarOption("time"))
     table.insert(sub_items, getMinibarOption("pages_left"))
-    table.insert(sub_items, getMinibarOption("battery"))
+    if not Device:isDesktop() then
+        table.insert(sub_items, getMinibarOption("battery"))
+    end
     table.insert(sub_items, getMinibarOption("percentage"))
     table.insert(sub_items, getMinibarOption("book_time_to_read"))
     table.insert(sub_items, getMinibarOption("chapter_time_to_read"))
```

**Comment by pazos** [comment]
The emulator isn't affected BTW

**Comment by pazos** [comment]
Add the missing glyphs are a mystery to me. Nerdfont is packaged and available at `/usr/lib/koreader/fonts/nerdfonts/symbols.ttf`

**Comment by JasonInOttawa** [comment]
Thanks for everyone's help. 

I thought "emulator" included the application installed on  Linux via a deb (or built from source) :)

**Comment by pazos** [comment]
> I thought "emulator" included the application installed on Linux via a deb (or built from source) :)

It is almost the same, but the emulator has some extra menus, like frontlight controls even when there's no frontlight in the device, and prints DEBUG statements on console by default.

See the [different SDL devices](https://github.com/koreader/koreader/blob/master/frontend/device/sdl/device.lua#L112-L136)

**Comment by JasonInOttawa** [comment]
Ah, ok. That's very helpful - thanks

**Comment by poire-z** [comment]
> Anyways to fix the isDesktop mess

Well, I'm not even sure MODE is the culprit - as it's a real key-value table, not an array, so setting one to nil should work.
And if that happened with `battery`, it can as well happen with `frontlight` and `wifi_status` - which are removed under some other conditions than isDesktop().

I still can't reproduce the issue, no matter what :)
But, (like in #6209, but the opposite), we might be iterating `mode_tbl` as if it were an array:
https://github.com/koreader/koreader/blob/03140f505ca475f185bdc197b175ee8a59cf774f/frontend/apps/reader/modules/readerfooter.lua#L342-L346
Line 342 is fine: we iterate a k/v table, building another k/v table: `mode_tbl`.
But line 345 is wrong: `mode_tbl` is not an array - so that's where we might lose some items.

**Comment by poire-z** [comment]
OK, I can reproduce it - I just needed to remove from settings.reader.lua `footer.order` - which, if it exists, is used instead of the shorty mode_tbl we build from MODE:
```
05/29/20-21:15:04 WARN  4 {
    [0] = "off",
    [1] = "page_progress",
    [2] = "time",
    [3] = "pages_left"
}
```

**Comment by poire-z** [comment]
So, it looks to me that for quite some time, book title & mem usage were not working - unless one had previously re-ordered them via the sort widget.

This footer code has been built by a bunch of C/Lua schizophrenic devs (I mean _us_ :): we build a Lua array (which Lua starts at 1), but we give it an item n° 0 (for "off", which could make sense), and we hope here and there that it will work fine, with all of that:
```lua
for i = 0, #self.mode_index do
for i=1, #self.mode_index do
for i, m in ipairs(self.mode_index) do
for i, m in pairs(self.mode_index) do
```
which for some reason might work...
```
require("logger").warn(self.mode_nb, self.mode_index, #self.mode_index, self.mode_index[#self.mode_index], self.mode_index[1], self.mode_index[0])
WARN  10 {
    [0] = "off",
    [1] = "page_progress",
    [2] = "time",
    [3] = "pages_left",
    [4] = "percentage",
    [5] = "book_time_to_read",
    [6] = "chapter_time_to_read",
    [7] = "mem_usage",
    [8] = "book_title",
    [9] = "book_chapter"
} 9 book_chapter page_progress off
```

**Comment by poire-z** [comment]
> And the missing glyphs are a mystery to me. Nerdfont is packaged and available 

@pazos @Frenzie : do the symbols from nerdfont work for you with the .deb ?

If yes, it must be something in @JasonInOttawa setup.
I see in frontend/ui/elements/font_settings.lua we can make use of fonts in:
/usr/share/fonts
/home/.local/share/fonts
or env variable EXT_FONT_DIR.
and there are options `Fonts> Font settings> Enable system font` that might be worth toggling to see if there's a change...

**Comment by JasonInOttawa** [comment]
The symbols did appear when I put 2020.03.2 on (see above). I have symbols.ttf here:

/usr/lib/koreader/fonts/nerdfonts$ md5sum symbols.ttf 
90b093a1d0bc5cc82218912788f74790  symbols.ttf

Let me know if there is anything you'd like to see from my setup

**Comment by pazos** [comment]
> @pazos @Frenzie : do the symbols from nerdfont work for you with the .deb ?

Nope. but the md5sum is the same as @JasonInOttawa with 2020.05
`90b093a1d0bc5cc82218912788f74790  /usr/lib/koreader/fonts/nerdfonts/symbols.ttf`

I modified the deb package rencently but didn't touch anything font-related IIRC (other than symlink against system noto & freefonts)

On the emulator all glyphs are available.

**Comment by Frenzie** [comment]
I can confirm that it broke somewhere in between 2020.04 and 2020.05. https://github.com/koreader/koreader/pull/6099 is an obvious one to check, and I think it indeed looks that way.

<img src=https://user-images.githubusercontent.com/202757/83362369-0eac9c00-a391-11ea-9954-6f2fc88e9d87.png align=right width=30%>

* 14 May build: https://gitlab.com/koreader/nightly-builds/-/jobs/551753053 (working, assuming no weird cache stuff)
* 15 May build: https://gitlab.com/koreader/nightly-builds/-/jobs/553699552 (not working, assuming no weird cache stuff)

Just in case I'm leaving some links to the builds for https://github.com/koreader/koreader-base/pull/1095

* 8 May build: https://gitlab.com/koreader/nightly-builds/-/jobs/543773498
* 9 May build: https://gitlab.com/koreader/nightly-builds/-/jobs/545159761
* 10 May build: https://gitlab.com/koreader/nightly-builds/-/jobs/545631237
