### ISSUE TITLE
./kodev release debian-armhf  difficulties

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6213]
arm-linux-gnueabihf-strip --strip-unneeded ${STRIP_FILES} ;\                        
touch -r ${STRIP_FILES}  # let all files have the same mtime                        
arm-linux-gnueabihf-strip: build/arm-linux-gnueabihf/rocks/lib/lua/5.1/*.so*：无此文
件                                                                                  
touch: 无法创建 'build/arm-linux-gnueabihf/rocks/lib/lua/5.1/*.so*': 没有那个文件或 
目录                                                                                
make[1]: *** [Makefile:41：all] 错误 1
make[1]: 离开目录“/root/share/koreader/base”
make: *** [Makefile:72：all] 错误 2

**Comment by pazos** [comment]
Cannot reproduce. Please follow the guide to setup a build environment at https://github.com/koreader/koreader/blob/master/doc/Building.md and the additional guide to build for your desired target (debian) at https://github.com/koreader/koreader/blob/master/doc/Building_targets.md.

And please keep your related questions in #6207
