### ISSUE TITLE
[question]: calibre search metadata refactor

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6219]
In #6177 I implemented a few calibre wireless fixes.

I ended up writting a way to [read and write calibre metadata directly](https://github.com/koreader/koreader/pull/6177/files#diff-040c04971ea664bab5607114ae52de35). That's nice as it makes the code easy to read and allow us to keep the metadata updated across calibre connections (wired via device drivers, wired via connect to folder or wireless via the "companion" plugin).

The implementation works well with calibre but fails to work with our current "search calibre metadata feature". Here's why:

1. with #6177 each "inbox_dir" used with the calibre wireless plugin becomes a full calibre library (it has .driveinfo.calibre and .metadata.calibre files)
2. the code in Filemanager local function [`findcalibre`](https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanagersearch.lua#L44-L74) will find all that metadata.
3. The full https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanagersearch.lua
file is intended to **manually** parse a calibre metadata file, as pretty-printed by calibre, but fails to parse the same file if we store it ourselves - without prettyprint. It is still valid JSON data, and calibre can read it without problems.

Since I'm not an user of the "search in calibre metadata" I barely know how it behaves from the user POV. Things are even harder at trying to read `filemanagersearch.lua` code. I'm full aware that most of the file is used to find calibre metadata files, save their path as global settings and write parts of their metadata in "simplified" files to be consumed by the search; but I cannot understand how the search works.

I would love a helper hand to help me figure out how to move current search functions to the new calibre db helper. Mainly, with the new helper we need to do:

1. find a calibre library of your choice
2. initializate it with `CalibreDB:init(path)`
3. all books are now stored in an indexed table `CalibreDB.books` that can be iterated direclty by a search function or used by any of the embedded functions, like `CalibreDB:searchTags(tag)`. 

Now the real question: **how to migrate the UI part of `filemanagersearch.lua` to use `CalibreDB`?**

**Comment by NiLuJe** [comment]
There's currently no UI to set a default Calibre library, there's just two different globals (because onboard + sd); and said findcalibre function that'll bruteforce iterate everywhere until it finds a Calibre db because that was useless otherwise because nobody knew how to set a Calibre library ^^.

----

Random question: how's the performance and memory usage with the JSON parsing/writing? Calibre itself has been known to implode on 32bit systems when writing chunky calibre.metadata files....

Because if it's sane, one obvious solution would be to drop the insanity in filemanagersearch.lua and just read JSON.

**Comment by NiLuJe** [comment]
I don't particularly care about that myself, as I've only got one, but one use-case of the current search was being able to search multiple (well, 2) metadata dumps at once.

Otherwise, I'd say chuck the results from findcalibre in a pane, ask the user to choose one, and that's that.

**Comment by pazos** [comment]
> Random question: how's the performance and memory usage with the JSON parsing/writing? Calibre itself has been known to implode on 32bit systems when writing chunky calibre.metadata files....

Quite good on the emulator (hundreds of test files are parsed in a few milliseconds). On a real device it is slower but it is still quite good. Here is a test case:

A cervantes 4 with 3 calibre libraries:
- `/mnt/public/calibre` (loaded with ~500 epubs for testing)
- `/mnt/sd` (loaded with ~1000 epubs)
- `/mnt/public/articles` (loaded with ~100 pdfs)

Using a findCalibre approach that returns a table with all libraries instead of returning the first match and storing that table as `all_calibre_libraries`. Now we have:

```lua
all_calibre_libraries = {
    [1] = {
        path = "/mnt/public/calibre",
    },
    [2] = {
        path = "/mnt/sd",
    },
    [3] = {
        path = "/mnt/public/articles",
    },
}
```

Then I can get the books of all of them (and all their metadata) with 

```lua
local all_books = {}
for _, path in ipairs(all_calibre_libraries) do
    CalibreDB:init(path)
    if #CalibreDB.books > 0 then
        local book = {}
        for i, metadata in ipairs(CalibreDB.books) do
            table.insert(all_books, #all_books + 1, metadata)
        end
    end
    return all_books
end
```

In all that process the slower part is the findCalibre(root) that returns the table of calibre libraries. Once calibre libraries are found getting a book list for each one and merge books in a single list is fast (<1 second). Parsing the resulting table again to discard duplicates is fast too (tens of milliseconds)

**Comment by NiLuJe** [comment]
Cool. I'm all for it ;).

Ping me if you have more questions about filemanagersearch, I have a vague memory of how some of it works ;D.

**Comment by pazos** [comment]
> Cool. I'm all for it ;).
> 
> Ping me if you have more questions about filemanagersearch, I have a vague memory of how some of it works ;D.

the function `Search:find(option)` is still a mystery to me. Will need *a lot* of time to figure out how searchs work.

**Comment by NiLuJe** [comment]
You can probably forget about the two inlined functions at the beginning because JSON now ;).

You can then also forget the part about writing the simplified variant.

Which mostly leave the bit that parses it line-by-line, looking at each searchable attribute (authors/title/path/series/tags) and storing that in a dedicated table for each if the book it was found on has a document handler in KOReader.

**Comment by pazos** [comment]
@NiLuJe: I managed to clean the file and repurpose all metadata from CalibreDB. It's all in #6177.

The new search is case insensitive (for now). I removed most parts without trying to understand what they were doing. I did barely test that basic features work as they were but a (user) review would be amazing.

**Comment by NiLuJe** [comment]
@pazos: Thanks, I'll give it a go ;).

Quick comments:

* I'd like to keep the ability to skip the findCalibre call via an user-specified table (besides the speed gain, that'd allow knowledgeable users to essentially "hide" extra dbs if need be).
* As well as the "cache the latest result" feature, which is really useful ;).

* ROOTDIR fallback debug leftover? ;).

**Comment by pazos** [comment]
> I'd like to keep the ability to skip the findCalibre call via an user-specified table (besides the speed gain, that'd allow knowledgeable users to essentially "hide" extra dbs if need be).

Yep, it is in the works

```diff

diff --git a/frontend/apps/filemanager/filemanagersearch.lua b/frontend/apps/filemanager/filemanagersearch.lua
index 47680f2c..be730153 100644
--- a/frontend/apps/filemanager/filemanagersearch.lua
+++ b/frontend/apps/filemanager/filemanagersearch.lua
@@ -1,5 +1,7 @@
 local CalibreDB = require("calibredb")
 local CenterContainer = require("ui/widget/container/centercontainer")
+local DataStorage = require("datastorage")
+local Device = require("device")
 local DocumentRegistry = require("document/documentregistry")
 local Font = require("ui/font")
 local InputDialog = require("ui/widget/inputdialog")
@@ -9,9 +11,11 @@ local Menu = require("ui/widget/menu")
 local Screen = require("device").screen
 local UIManager = require("ui/uimanager")
 local lfs = require("libs/libkoreader-lfs")
+local util = require("util")
 local _ = require("gettext")
 
-local ROOTDIR = "/mnt/calibre"
+-- name of the file that stores calibre libraries
+local user_libraries = "calibre-libraries.lua"
 
 -- get books by name
 ---@table of books
@@ -144,17 +148,45 @@ function Search:findCalibre(root)
     end
 end
 
-function Search:getMetadata(root)
+function Search:getMetadata()
     if #self.libraries == 0 then
-        self:findCalibre(root)
+        -- no libraries found. Try to load them from file instead of doing a full rescan.
+        local user_path = DataStorage:getDataDir() .. "/" .. user_libraries
+        local ok, libraries = pcall(dofile, user_path)
+
+        if ok then
+            self.libraries = libraries
+        else
+            -- no user libraries, doing a full rescan on the given root directory.
+            local rootdir = "/mnt"
+            if Device:isAndroid() then
+                rootdir = Device.external_storage
+            end
+            self:findCalibre(rootdir)
+            if #self.libraries > 0 then
+                util.dumpTable(self.libraries, user_path)
+            end
+        end
     end
     local all_books = {}
     for _, library in ipairs(self.libraries) do
         if library.enabled then
-            CalibreDB:init(library.path)
-            for __, book in ipairs(CalibreDB.books) do
-                book.rootpath = CalibreDB.path
-                table.insert(all_books, #all_books + 1, book)
+            if (CalibreDB:init(library.path)) then
+                -- to search we don't need all calibre metadata,
+                -- keep only a subset of it, to make the table slim.
+                for __, book in ipairs(CalibreDB.books) do
+                    local slim_book = {}
+                    slim_book.title = book.title
+                    slim_book.lpath = book.lpath
+                    slim_book.authors = book.authors
+                    slim_book.series = book.series
+                    slim_book.tags = book.tags
+                    slim_book.size = book.size
+                    -- also add a key with the root path of the book,
+                    -- since we're merging different libraries together
+                    slim_book.rootpath = CalibreDB.path
+                    table.insert(all_books, #all_books + 1, slim_book)
+                end
             end
         end
     end
@@ -277,7 +309,7 @@ end
 
 function Search:find(option)
     if #self.books == 0 then
-        self.books = self:getMetadata(ROOTDIR)
+        self.books = self:getMetadata()
     end
     if option == "find" then
         local books = getBooksByName(self.books, self.search_value)
```

> As well as the "cache the latest result" feature, which is really useful ;).

Not sure what it does, but seems unnecesary :p 

> ROOTDIR fallback debug leftover? ;).

yup, /mnt is a server with +3TB of data. Also removed in the diff.

**Comment by NiLuJe** [comment]
> > As well as the "cache the latest result" feature, which is really useful ;).
> 
> Not sure what it does, but seems unnecesary :p

Think of a tags search, and poking at a few different books in that same list of tags, which mean a few book/search back and forth. Not having to re-compute the search each time makes it feel pretty snappy ;).

**Comment by NiLuJe** [comment]
Okay, one fairly trivial issue first:

```
./luajit: frontend/apps/filemanager/filemanagermenu.lua:482: attempt to call method 'getCalibre' (a nil value)
stack traceback:
        frontend/apps/filemanager/filemanagermenu.lua:482: in function 'callback'
        frontend/ui/widget/touchmenu.lua:791: in function 'action'
        frontend/ui/uimanager.lua:812: in function '_checkTasks'
        frontend/ui/uimanager.lua:1095: in function 'handleInput'
        frontend/ui/uimanager.lua:1181: in function 'run'
        ./reader.lua:298: in main chunk
        [C]: at 0x000140c1
```

;).

**Comment by NiLuJe** [comment]
Okay, with https://github.com/koreader/koreader/issues/6219#issuecomment-637612207 applied, it appears to behave pretty well ;).

The findCalibre walk indeed appears to be the main bottleneck (and seems to be fairly more aggressive than the previous one, but that may just been an impression).

Subsequent searches are suitably snappy, though, so you can forget my previous comment about keeping a cache of the previous search, that's probably not necessary anymore (the textbox already remembers the previous search).

I like the automagic storage of the findCalibre result, though, so, all in all, it looks pretty good, kudos, and thank you :).

**Comment by NiLuJe** [comment]
Well, actually, the main bottleneck is the CalibreDB:init(), which makes sense ;p.

It's far from terrible though (and it's certainly faster than the old cache generation).

**Comment by NiLuJe** [comment]
Not quite sure we'd gain much by dumping that in a local cache... But then we're back to the timestamp checks to see if it's up to date :s.

**Comment by pazos** [comment]
Thanks for the feedback!!!

> The findCalibre walk indeed appears to be the main bottleneck (and seems to be fairly more aggressive than the previous one, but that may just be an impression, been a while since I actually did one).

The last one stopped on the first library. This one gets all of them.

> Well, actually, the main bottleneck is the CalibreDB:init(), which makes sense ;p. (On the upside, the prune check is not as costly as I would have thought).

I think we can make prune an option. It is useful for -not so true- calibre users, who are used to remove books by their own.

> Not quite sure we'd gain much by dumping that in a local cache

Keeping a cache of "catalogs" isn't faster than generating them from slimed books. Keeping a cache of slimed books is 10x faster than getting them via CalibreDB:init(), so it could make sense, specially when having a lot of libraries or a lot of books in them.

**Comment by NiLuJe** [comment]
> Keeping a cache of "catalogs" isn't faster than generating them from slimed books. Keeping a cache of slimed books is 10x faster than getting them via CalibreDB:init(), so it could make sense, specially when having a lot of libraries or a lot of books in them.

Yeah, I was wondering about that, thanks for clarifying (and testing ;p). I wouldn't mind that, yeah ;).
