### ISSUE TITLE
Dictionaries on android

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#622]
So I wouldn't have a clue how to install dictionaries on a non-rooted android device. I suppose a lot of people will have to do without dictionaries if we don't come-up with some way to install them. 

Couldn't we make a download/deinstall feature, so that it doesn't have to be shipped with MB's worth of dictionaries? I always feel rather rich when I download free dictionary support within Kobo Nickel.

**Comment by chrox** [comment]
Dictionary for Android is implemented in #1490. Closing this now.
