### ISSUE TITLE
remarkable pdf location

### ISSUE THREAD

**Issue by AaronDavidSchneider** [koreader/koreader#6226]
* KOReader version: v2020.05
* Device: remarkable

#### Issue
remarkable synchronizes pdfs in `/home/root/.local/share/remarkable/xochitl`.
I can't open this folder in the koreader filebrowser

#### Steps to reproduce
I installed koreader (without button-listen) and used `systemctl start koreader` to start koreader. 

#### Question
Am I overlooking something, or do I need to have two different pdf databases? (One for xochitl and one for koreader)

**Comment by Frenzie** [comment]
It's probably just a matter of hidden folders. Enable hidden files & folders and you should be able to browse to a location like .local.

**Comment by AaronDavidSchneider** [comment]
Yes thats true! Thanks. I didnt know thats possible
