### ISSUE TITLE
How to turn pages by click on the up and down half of the phone

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6227]
* KOReader version: V2020.05
* Device: Hisense A5

#### Issue
I'm using an eink phone. So I may hold the phone in the left hand or in the right hand. The default page turn method is to click the left or right half of the screen. This can not suit both the left and right holding. My left or right-hand thumb has to cross the screen to turn to the next page. So I'm trying to find how to set the turning method to up half or down half of the screen. So it will both fine when I hold the phone in the left or right hand. But I can not find this option, where can I find this option? 

#### Steps to reproduce
1. Use the default page turn method
2. Left or right thumb may cross the screen to turn pages
3. Trying to find if there's a setting that I can set to turn pages by click up or down half of the screen.
4. I can not found it.

**Comment by gerhaher** [comment]
Open 'Advanced settings'

Change DTAP_ZONE_BACKWARD to h=0.5, w=1, x=0, y=0
and DTAP_ZONE_FORWARD to h=0.5, w=1, x=0, y=0.5
(or vice versa if you prefer to tap forward with upper part of screen)

**Comment by kingo132** [comment]
> Tools menu >> 'Advanced settings'
> 
> Change DTAP_ZONE_BACKWARD to h=0.5, w=1, x=0, y=0
> and DTAP_ZONE_FORWARD to h=0.5, w=1, x=0, y=0.5
> (or vice versa if you prefer to tap forward with upper part of screen)

It works, thanks!

**Comment by edent** [comment]
I've added these instructions to the Wiki as I couldn't find them anywhere else.
https://github.com/koreader/koreader/wiki/Change-Next-Page---Previous-Page-touch-targets

**Comment by Frenzie** [comment]
Thanks!
