### ISSUE TITLE
[FR] NewsDownloader - Gazette Mode - Feed entries in one EPUB file

### ISSUE THREAD

**Issue by hngt** [koreader/koreader#6234]
* KOReader version:2020.05
* Device: PW3

In reference to the second request from #6185, I suggest a mode for NewsDownloader Plugin in which one could download feed entries and keep them in a single EPUB file, preferably with chapters. Would be very handy for feeds with lots of short entries as then opening and quitting multiple EPUB files is difficult and annoying.

**Comment by poire-z** [comment]
I mentionned some related idea in https://github.com/koreader/koreader/issues/4894#issuecomment-481879384:

> (Or have it accumulate new articles in a same EPUB ? So you get a growing archive of that RSS feed and you have a book that never ends :)

**Comment by Frenzie** [comment]
Sounds reasonable initially but I imagine you'll want to start deleting stuff after a few hundred entries or so.

As for the FR as written, I think it might be presupposing a specific solution? Compare the way the gettext manual is available both as one page or as a series of interconnected pages.

https://www.gnu.org/software/gettext/manual/html_node/index.html
https://www.gnu.org/software/gettext/manual/html_node/Aspects.html#Aspects

> Would be very handy for feeds with lots of short entries as then opening and quitting multiple EPUB files is difficult and annoying.

Shouldn't "open next file" take away the bulk of what's annoying about that btw?

**Comment by lich-tex** [comment]
This problem is quite complex, as main.lua pretty much currently defines the method around the idea of singular EPUB documents so the code change will be quite fundamental. The issue of read/non-read in my opnion would be fine with appending the newer elements on the top of the document.

Will need to learn more about EPUB specifications for that, but then it would be doable. Still, I do not think I will be able to do it as I did previous FR in less than a week :).

**Comment by lich-tex** [comment]
> Sounds reasonable initially but I imagine you'll want to start deleting stuff after a few hundred entries or so.
> 
> As for the FR as written, I think it might be presupposing a specific solution? Compare the way the gettext manual is available both as one page or as a series of interconnected pages.
> 
> https://www.gnu.org/software/gettext/manual/html_node/index.html
> https://www.gnu.org/software/gettext/manual/html_node/Aspects.html#Aspects
> 
> > Would be very handy for feeds with lots of short entries as then opening and quitting multiple EPUB files is difficult and annoying.
> 
> Shouldn't "open next file" take away the bulk of what's annoying about that btw?

Well, open next file would help a lot, still would be not as seamless.

And for the case of having few hundred entries, my Feed system on my desktop works like this, and what I basically do is just remove the files every so often if they get too bloated.

**Comment by georgew21** [comment]
i think that is usuless to accumulate newer articles in same epub. It's more easy to download your feed  news, read that you are interested on and after to delete this. 

even if, someone want to keep the older feed, when he will download again the newer feeds he will have a newer file with other date in the filename along with one feed with older news.

* also,  we can have a filter to downlaod only the articled last day

the important is every feed have a separate file in which there will be chapters with hyperlinks to go to each article you want and easy return to the contents without waiting opening-closing files..

i wonder if html could be more easy and  suitable for this, so when download the articles automatically parse the text to a html file creating the hyperlinks

**Comment by lich-tex** [comment]
> i think that is usuless to accumulate newer articles in same epub. It's more easy to download your feed news, read that you are interested on and after to delete this.
> 
> even if, someone want to keep the older feed, when he will download again the newer feeds he will have a newer file with other date in the filename along with one feed with older news.
> 
>     * also,  we can have a filter to downlaod only the articled last day
> 
> 
> the important is every feed have a separate file in which there will be chapters with hyperlinks to go to each article you want and easy return to the contents without waiting opening-closing files..

This is exactly what I meant as TOC and various content files are part of EPUB specification.

> 
> i wonder if html could be more easy and suitable for this, so when download the articles automatically parse the text to a html file creating the hyperlinks

EPUB uses XHTML so the HTML input is fully accepted and then the EPUB can be used for further extending and using links and table of contents for navigation. It is fully fitting format, and it is much easier to use with the filter patch now.

**Comment by poire-z** [comment]
Implemented in #8263.

**Comment by roygbyte** [comment]
Pinging this thread to see if folks want to contribute ideas towards Newsdownloader's rebuild. [See this thread for more info.](https://github.com/koreader/koreader/issues/9225)
