### ISSUE TITLE
Can't login "Progress sync" on Android

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#6237]
* KOReader version: 2020.05
* Device: Android - LG G6

Whenever I hit login after filled my username & password in progress sync plugin, the android - Koreader app got freeze and then force close .
I did try with version 2020.04.01, but I encountered the same.

Please kindly take a look.

Thank you

**Comment by pazos** [comment]
> Koreader app got freeze and then force close .

Yeah. Its a known android limitation. While we're doing network business we can't process input events. Android detects it and show the Aplication Not Responding dialog.

Solutions? I dunno.
Workarounds?: do not touch the screen (or buttons) while it is logging. Leave it that way until you get a response. It shouldn't take too much time. Eventually you'll get a prompt that show you you're logged or the reasons if you can't login.

**Comment by uphantom89** [comment]
I did try your instruction "do not touch" and successfully logged in. Thank you.

**Comment by pazos** [comment]
> I did try your instruction "do not touch" and successfully logged in. Thank you.

Cool!

The underlying issue isn't something easy to fix. Probably the easiest workaround for long network operations is to use a native android dialog instead of InfoMessages. This way the dialog steals the focus from the app and user input doesn't trigger an ANR. 

It is a pain to implement because it would require changing one by one all the dialogs that are shown when we're going to block. Some examples:

- Download dictionaries
- Login to evernote/calibre/kosync server
- Performing a disk scan that takes more than 5secs
...

**Comment by pazos** [comment]
@Frenzie @poire-z @NiLuJe: the easiest workaround to prevent ANRs on android would be ignoring all user input while the blocking action happens. I did play a bit with the code

```diff
 
diff --git a/frontend/device/android/device.lua b/frontend/device/android/device.lua
index 9e4ca3b4..181e9e9a 100644
--- a/frontend/device/android/device.lua
+++ b/frontend/device/android/device.lua
@@ -253,6 +253,10 @@ function Device:initNetworkManager(NetworkMgr)
     end
 end
 
+function Device:setIgnoreInput(enable)
+    android.setIgnoreInput(enable)
+end
+
 function Device:performHapticFeedback(type)
     android.hapticFeedback(C["AHAPTIC_"..type])
 end
diff --git a/frontend/device/generic/device.lua b/frontend/device/generic/device.lua
index 524f818d..5ac55f51 100644
--- a/frontend/device/generic/device.lua
+++ b/frontend/device/generic/device.lua
@@ -308,6 +308,11 @@ function Device:setDateTime(year, month, day, hour, min, sec) end
 -- Device specific method if any setting needs being saved
 function Device:saveSettings() end
 
+
+-- Device specific method for ignoring input events.
+-- It isn't used on most devices
+function Device:setIgnoreInput(enable) return true end
+
```

So, in the context of a network call, like in kosync.plugin we can ignore input on doLogin and doRegister with:

```diff
diff --git a/plugins/kosync.koplugin/main.lua b/plugins/kosync.koplugin/main.lua
index 63510b41..559c3591 100644
--- a/plugins/kosync.koplugin/main.lua
+++ b/plugins/kosync.koplugin/main.lua
@@ -5,6 +5,7 @@ local ConfirmBox = require("ui/widget/confirmbox")
 local NetworkMgr = require("ui/network/manager")
 local UIManager = require("ui/uimanager")
 local Screen = require("device").screen
+local Device = require("device")
 local DeviceModel = require("device").model
 local Event = require("ui/event")
 local Math = require("optmath")
@@ -384,6 +385,7 @@ function KOSync:doRegister(username, password)
         custom_url = self.kosync_custom_server,
         service_spec = self.path .. "/api.json"
     }
+    Device:setIgnoreInput(true)
     local userkey = md5.sum(password)
     local ok, status, body = pcall(client.register, client, username, userkey)
     if not ok then
@@ -409,7 +411,7 @@ function KOSync:doRegister(username, password)
             text = body and body.message or _("Unknown server error"),
         })
     end
-
+    Device:setIgnoreInput(false)
     self:saveSettings()
 end
 
@@ -421,6 +423,7 @@ function KOSync:doLogin(username, password)
     }
     local userkey = md5.sum(password)
     local ok, status, body = pcall(client.authorize, client, username, userkey)
+    Device:setIgnoreInput(true)
     if not ok then
         if status then
             UIManager:show(InfoMessage:new{
@@ -432,6 +435,7 @@ function KOSync:doLogin(username, password)
                 text = _("An unknown error occurred while logging in."),
             })
         end
+        Device:setIgnoreInput(false)
         return
     elseif status then
         self.kosync_username = username
@@ -445,7 +449,7 @@ function KOSync:doLogin(username, password)
             text = body and body.message or _("Unknown server error"),
         })
     end
-
+    Device:setIgnoreInput(false)
     self:saveSettings()
 end
```

That would prevent ANRs on android and does nothing on other platforms. What do you think?

**Comment by Frenzie** [comment]
Looks like a fairly elegant workaround to me.

**Comment by poire-z** [comment]
Looks fine and elegant to me too :)
