### ISSUE TITLE
status bar font size change requires "rewake"

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#6239]
* KOReader version: v2020.04.1-35-g58a6b01_2020_05_15
* Device: Kobo Aura One

#### Issue
Having changed the screen DPI, I was trying to get the status bar back to a readable size by changing its font type, but not succeeding.  In the end I found that closing the cover and reopening made the changes appear.

#### Steps to reproduce
Set the Status bar font size to various values.

This is not a real problem, but a small remark ("requires sleep&awake") in the menu would have helped.  I don't know whether this can be forced by the software upon clicking "Set size" - if so, that would be even better.
(And once one is programming in that area - having small (settable?) margins at the left and right of the status bar would be friendly too.  Currently the symbols at the right run up against the border of my screen - but that proposal would fit better with my "rearrangeable status bar items".)

**Comment by NiLuJe** [comment]
Isn't page turning enough?

IIRC, margins are already configurable?

**Comment by NiLuJe** [comment]
And items are already movable, too.

**Comment by Biep** [comment]
In my version?  Where can I find that?

**Comment by NiLuJe** [comment]
Gear > Status bar > Settings > Sort items

**Comment by Biep** [comment]
You are right - at the very top of *Settings*.  For some reason I simply missed it.  Thank you!

**Comment by NiLuJe** [comment]
That doesn't answer my question about your actual bug report, though ;p.

**Comment by NiLuJe** [comment]
Namely:

> Isn't page turning enough?

**Comment by Biep** [comment]
Yes, it is - I stand fully corrected.  I guess I must not have made a genuine change when I tried that.
But then I am stupid in more ways than one, so that isn't unlikely in itself.

**Comment by NiLuJe** [comment]
Actually, that works for me (on Kindle right now, but I do remember it behaving on Android, too), and the code looks good.

**Comment by NiLuJe** [comment]
I mean, changing the DPI requires a restart anyway, and that works, too.

And the "Use default" button in the spin widget is not supposed to actually *apply* the default, just reset the spinner's value, so, that works, too.

**Comment by Frenzie** [comment]
Closing since if I understand correctly changing the page should suffice. (Perhaps something could be improved there, but it seems like fairly minor polish.)
