### ISSUE TITLE
When exiting from a news epub to the files folder, a '/' is added to the end of the path

### ISSUE THREAD

**Issue by ericserbinenko** [koreader/koreader#6243]
* KOReader version: 2020.05 "May Storm"
* Device: Kobo Glo HD

Having never done this sort of bug reporting before, I'm not entirely sure what's the proper etiquette to contribute , but here goes nothing:

#### Issue
As of the newest version (may) of KOReader, when I stop reading a file that is inside the designated "news" folder for the downloader by tapping the back to files icon, an extra '/' (forward slash) is appended to the path, reloading the entire folder (files that previously were bold go back to not having been recognized, and subsequently go through the recognizing process again)

#### Steps to reproduce
Open any kind of file within the designated news download folder, then exit it through the "back to folder" icon. It doesn't seem to matter whether the file was actually downloaded by the news downloader or just put there through copying and pasting. Changing the folder where the news are to be downloaded fixes the problem in the old folder and causes it in the new one.

##### `crash.log` (if applicable)
Does not cause a crash.

**Comment by poire-z** [comment]
(Perfect bug report ! :)

Probably cause by #6163 https://github.com/koreader/koreader/commit/0e2b4307962df975eca1f1a7a31a390bf34104d8 .
`util.splitFilePathName()` leaves the / at the end. We were cleaning it up in `ReaderUI:showFileManager()` but not in the added stuff in `NewsDownloader:onCloseDocument()`.

https://github.com/koreader/koreader/blob/9c4e246038a30a405957b3f537c8c1c27d4a872b/plugins/newsdownloader.koplugin/main.lua#L465-L475

Can you try adding between lines 472 and 473:
```lua
        doc_dir = doc_dir:match("(.*)/")
```
and tell us if that's just enough to solve the issue (I don't use that plugin).

**Comment by poire-z** [comment]
Anyway, given the wild in plugins with what this can be provided with, better to fix it with:
```diff
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua
@@ -430,4 +430,7 @@ end

 function ReaderUI:setLastDirForFileBrowser(dir)
+    if dir and dir:sub(-1) == "/" then
+        dir = dir:sub(1, -2)
+    end
     self.last_dir_for_file_browser = dir
 end
```

**Comment by ericserbinenko** [comment]
I don't actually have a build environment set up right now, so it's a bit hard for me to test but I'll try to set it up, though it'll take a little while, probably.

**Comment by poire-z** [comment]
No need to !
You could just hack this file on your device (if Pocketbook makes available via USB the place where KOReader is installed) - or just don't bother - it's simple enough that it doesn't really need a test :)

**Comment by ericserbinenko** [comment]
I see, that's pretty easy! I put added the doc_dir = doc_dir:match("(.*)/") to the proper line and it definitely fixed it. Thanks for the help!

**Comment by poire-z** [comment]
Can you revert the one you tried, and try the other one https://github.com/koreader/koreader/issues/6243#issuecomment-640540368 please ?

**Comment by ericserbinenko** [comment]
I tried the second version and it also worked just fine. Seems to be fixed!

**Comment by poire-z** [comment]
Thanks for the tests :)
