### ISSUE TITLE
Different hyphenation variants for one language (i.e. German)

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6245]
* KOReader version: 2020.05
* Device: all

#### Issue / Feature Request
KOReader selects a hyphenation pattern depending on the language of the document.
The hyphenation-dictionary for a language is hard-coded. For every language there is only one hyphenation.pattern file in the data directory. If someone wants different hyphenation, the pattern file has to be changed manually after every update of KOReader.
It is not possible to select between different hyphenation patterns for one language on the fly.

Especially for German there exist at least five different possibilities for hyphenation:
- the traditional (old) one
- the new one, with a lot of possible positions
- the new one on word fugues (Wortfugen)
- the now one on major positions (Hauttrennstellen)
- the Libreoffice pattern file.

Depending on the line-width, either of them yields to different hyphenation, which is more or less readable.

#### Steps to reproduce
always, by design

#### Solution
It should be possible to select another pattern file. Best would be, if the file could be selected (similar to fonts) from the koreader directory on the SD-card (/sdcard/koreader/hyph). So everyone can try different patterns.

The source of the German hyphenation patterns can be found on:
```http://projekte.dante.de/Trennmuster```

I can provide pattern files or a script to generate them from the sources.
I would name the files like German-xxxxxx.pattern (i.e. German-Major.pattern). The part named with "xxxxxx" would be the variant.

Would someone be interested to add/modify  KOReader to select different hyphenation patterns? 
 The layout could be something like this (for German-Major.pattern). By tapping/clicking on "Dictionary variant:" the pattern files can be changed (round-robin, file-select ...)
![Bildschirmfoto_2020-06-08_15-08-53](https://user-images.githubusercontent.com/36999612/84034047-17592f80-a99a-11ea-970e-ce42295ab4c9.png)

**Comment by poire-z** [comment]
> Best would be, if the file could be selected (similar to fonts) from the koreader directory

That was possible, before I made #6069 and #6076. 
Now, the available hyph patterns are associated to a language, and the association rules are buried hardcoded into crengine: https://github.com/koreader/crengine/blob/master/crengine/src/textlang.cpp.

> Would someone be interested to add/modify KOReader to select different hyphenation patterns?

I'm sorry to say no :/ It would quite complexify the rendering code and the UI menu, and would make things less obvious (say I set main lang FRench, meet some `<p lang="de">german text</p>`, which "de" hyphenation should be used ? When there is only one per language, no doubt.

> I can provide pattern files or a script to generate them from the sources.
I would name the files like German-xxxxxx.pattern (i.e. German-Major.pattern). The part named with "xxxxxx" would be the variant.

May be we could just provide the best (free) one among those you mentionned. No need for german readers to have to test it and decide which is the best: _you_ decide which is the best :)
No-one yet mentionned the need for multiple or alternative hyph dict for any other language, so...

Other easier options:
- crengine: when requesting `German.pattern`, check if `German.pattern.user` exists, and use it instead. That should allow user overrides for any language he thinks there is a better or prefered alternative hyph dict.
- (Ugly) Adds languages "de-Wortfugen", "de-Hauttrennstellen" in the `Typography language>` menu, and consider them german variants :) (I think the one we provide is the one from Libreoffice).

**Comment by zwim** [comment]
@poire-z: Thank you for your hints.

I have implemented the easier option 1:

Try to open a pattern file (i.e. German.pattern) from 
   /sdcard/koreader/hyph/ (on Android)
  ~/koreader/hyph/ (on other systems).

If the appropriate pattern is not found there, try to open it on the default location (as done until now).


As I am not familiar with github and submoduls here is the patch (maybe someone could give me a short introduction to this).

```
--- /./base/thirdparty/kpvcrlib/crengine/crengine/src/hyphman.cpp 2020-06-08 19:41:29.905750875 +0200
+++ hyphman.cpp	2020-06-08 19:43:02.206207681 +0200
@@ -45,10 +45,15 @@
 
 #define _16(x) lString16(x)
 
+#define USER_HYPHENATION_DIRECTORY "/sdcard/koreader/hyph/"
+
 #else
 
 #include "../include/cri18n.h"
 
+#define USER_HYPHENATION_DIRECTORY "/~/koreader/hyph/"
+
+
 #endif
 
 int HyphMan::_LeftHyphenMin = HYPH_DEFAULT_HYPHEN_MIN;
@@ -286,10 +291,17 @@
         return method;
     }
     lString16 filename = p->getFilename();
-    LVStreamRef stream = LVOpenFileStream( filename.c_str(), LVOM_READ );
-    if ( stream.isNull() ) {
-        CRLog::error("Cannot open hyphenation dictionary %s", UnicodeToUtf8(filename).c_str() );
-        return &NO_HYPH;
+    lString16 filenameUserDir = USER_HYPHENATION_DIRECTORY + id;
+
+    LVStreamRef stream;
+    stream = LVOpenFileStream( filenameUserDir.c_str(), LVOM_READ ); // first try opening pattern in user directory
+    if ( stream.isNull() ) { // user pattern open failed
+        CRLog::info("Cannot open hyphenation user dictionary %s", UnicodeToUtf8(filenameUserDir).c_str() );
+        stream = LVOpenFileStream( filename.c_str(), LVOM_READ );
+        if ( stream.isNull() ) {  // system pattern open failed
+            CRLog::error("Cannot open hyphenation dictionary %s", UnicodeToUtf8(filename).c_str() );
+            return &NO_HYPH;
+        }
     }
     TexHyph * newmethod = new TexHyph(id, leftHyphenMin, rightHyphenMin);
     if ( !newmethod->load( stream ) ) {
```

**Comment by poire-z** [comment]
> Try to open a pattern file (i.e. German.pattern) from
/sdcard/koreader/hyph/ (on Android)
~/koreader/hyph/ (on other systems).

Not that easy :)
We don't want to hardcode paths in crengine: it's a library, it shouldn't have that.

So, if you're sure you really need an additional directory (and it looks indeed that on Android, our data/hyph/ is not accessible to the user without root), we'd have to feed it from our frontend:
koreader lua > koreader/base/cre.cpp bridge > crengine
https://github.com/koreader/koreader/blob/2b5b069863187b215a33bf8267c37af3aa015acf/frontend/document/credocument.lua#L96-L103
https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/cre.cpp#L459-L462
possibly extending `HyphMan::initDictionaries(lString16(dict_path))` to accept and store a 2nd dict_path - and then, it's probably in `HyphDictionaryList::open(hyphDirectory, hyphDirectory2)` that you would go at building a list of what's available taking precedence from your alt dir.

(Or may be cleaner, add a 2nd method HyphMan::initDictionariesFromPathList() so we can build the list in Lua and give it directly, like we do for fonts I think.)

**BUT**, if you're just looking for a quick solution (and I'm not sure the above is worth the burden), usable by the rare others that would need that, you could just copy once all our hyph dicts in some subdir of your choice on the accessible koreader data partition, and replace the ones you want, and then, we could just tweak in frontend:
https://github.com/koreader/koreader/blob/2b5b069863187b215a33bf8267c37af3aa015acf/frontend/document/credocument.lua#L102-L103
to:
- either use a setting (you could add manually to settings.reader.lua) that would specify the dir to use , and otherwise fallback to this hardcoded `"./data/hyph/"`.
- just export that as a variable into CreDocument, so you could use Android patch.lua solution to override it (just `require("frontend/document/credocument").HYPH_DICT = "/sdcard/koreader/hyph"`)

(I somehow hope you'd be fine with one these 2 last solutions :) because the first one would add some uglyness to crengine, which don't really need more of it :)

**Comment by zwim** [comment]
@poire-z: Thank you for your hints.

I have implemented the easier option 1:

Try to open a pattern file (i.e. German.pattern) from 
   /sdcard/koreader/hyph/ (on Android)
  ~/koreader/hyph/ (on other systems).

If the appropriate pattern is not found there, try to open it on the default location (as done until now).


As I am not familiar with github and submoduls here is the patch (maybe someone could give me a short introduction to this).

```
--- /./base/thirdparty/kpvcrlib/crengine/crengine/src/hyphman.cpp 2020-06-08 19:41:29.905750875 +0200
+++ hyphman.cpp	2020-06-08 19:43:02.206207681 +0200
@@ -45,10 +45,15 @@
 
 #define _16(x) lString16(x)
 
+#define USER_HYPHENATION_DIRECTORY "/sdcard/koreader/hyph/"
+
 #else
 
 #include "../include/cri18n.h"
 
+#define USER_HYPHENATION_DIRECTORY "/~/koreader/hyph/"
+
+
 #endif
 
 int HyphMan::_LeftHyphenMin = HYPH_DEFAULT_HYPHEN_MIN;
@@ -286,10 +291,17 @@
         return method;
     }
     lString16 filename = p->getFilename();
-    LVStreamRef stream = LVOpenFileStream( filename.c_str(), LVOM_READ );
-    if ( stream.isNull() ) {
-        CRLog::error("Cannot open hyphenation dictionary %s", UnicodeToUtf8(filename).c_str() );
-        return &NO_HYPH;
+    lString16 filenameUserDir = USER_HYPHENATION_DIRECTORY + id;
+
+    LVStreamRef stream;
+    stream = LVOpenFileStream( filenameUserDir.c_str(), LVOM_READ ); // first try opening pattern in user directory
+    if ( stream.isNull() ) { // user pattern open failed
+        CRLog::info("Cannot open hyphenation user dictionary %s", UnicodeToUtf8(filenameUserDir).c_str() );
+        stream = LVOpenFileStream( filename.c_str(), LVOM_READ );
+        if ( stream.isNull() ) {  // system pattern open failed
+            CRLog::error("Cannot open hyphenation dictionary %s", UnicodeToUtf8(filename).c_str() );
+            return &NO_HYPH;
+        }
     }
     TexHyph * newmethod = new TexHyph(id, leftHyphenMin, rightHyphenMin);
     if ( !newmethod->load( stream ) ) {
```

**Comment by poire-z** [comment]
> Possible it might be an easy solution to have a user-pattern-directory variable.
    If the directory does not exist, use the default location ".data/hyph/". -> Everything works as usual.

Oh, yes, good idea and super-easy. We already have `DataStorage:getDataDir()` that returns KOReader's user accessible data dir (where we create `cache/, data/, data/dict/, screenshots/`), adapted per device. So we could just check for the existence of `DataStorage:getDataDir().."/data/hyph"` and if yes, provide that, if not, provide hardcoded `./data/hyph`.

> If the directory does exist, copy all missing pattern files from "./data/hyph/" to that directory. So every user has all patterns. If someone wants different patterns, he can replace them. If someone has to save space (on the user partition) he can truncate the unwanted patterns with rm file.pattern; touch file.pattern.

That's a tiny bit ugly but a few minutes work (want to try it? :) - and you wouldn't get our updated hyph dicts if a past version has already been copied.
But we don't really update our hyph dicts, or add new ones, that often, so that might be a non-issue (or for the user to look for updates regularly - our files in packages have the build time as timestamps :/)
But in this case, the user (you) could copy them manually once, when setting up that hyph dir.

**Comment by zwim** [comment]
> > Possible it might be an easy solution to have a user-pattern-directory variable.
> > If the directory does not exist, use the default location ".data/hyph/". -> Everything works as usual.
> 
> Oh, yes, good idea and super-easy. We already have `DataStorage:getDataDir()` that returns KOReader's user accessible data dir (where we create `cache/, data/, data/dict/, screenshots/`), adapted per device. So we could just check for the existence of `DataStorage:getDataDir().."/data/hyph"` and if yes, provide that, if not, provide hardcoded `./data/hyph`.
> 

I will try that the next days. Hopefully I am firm with github until then ;-)

> > If the directory does exist, copy all missing pattern files from "./data/hyph/" to that directory. So every user has all patterns. If someone wants different patterns, he can replace them. If someone has to save space (on the user partition) he can truncate the unwanted patterns with rm file.pattern; touch file.pattern.
> 
> That's a tiny bit ugly but a few minutes work (want to try it? :) - and you wouldn't get our updated hyph dicts if a past version has already been copied.
> But we don't really update our hyph dicts, or add new ones, that often, so that might be a non-issue (or for the user to look for updates regularly - our files in packages have the build time as timestamps :/)
> But in this case, the user (you) could copy them manually once, when setting up that hyph dir.

Or we use the timestamps. If the pattern in ```./data/hyph/``` is newer than the one in the user-directory we ask the user if he wants to update it. If not we update the timestamp of the file in the user-directory.

I will send you a proposal the next days.

**Comment by poire-z** [comment]
> If the pattern in ./data/hyph/ is newer than the one in the user-directory we ask the user if he wants to update it. 

Everyday, they will be newer :) and most of the time, there would be no change.
Also, preferably no UI interaction at the time this happens. Preferably in credocument `CreDocument:engineInit()` , may be in a module local function called in there, to keep that one simple. Dunno if some other module should really be involved in that little hacky business :)

> Hopefully I am firm with github until then ;-)

We have some (possibly dated) doc at https://github.com/koreader/koreader/blob/master/doc/Collaborating_with_Git.md .
You need to clone and set up remotes, then, my workflow is may be a bit simpler from what I read there:
```
[clone on github, git clone your github locally, set remotes]
Resync
 git fetch upstream ; git merge upstream/master
 git push origin master

New work
 git checkout -b book_specific_tweak
(I copy edited files from another work tree)
 git add frontend
 git commit -v
 git push -u origin book_specific_tweak
Go to the url provided to open the PR and write some prose :)

Fix, add more commits:
 git push  origin book_specific_tweak

Fix, if rebase needed:
 git rebase -i master
 git push -f origin book_specific_tweak

Once merged in github, delete branch on github, and cleanup local tree:
 git checkout master
 git branch -D book_specific_tweak
 git fetch --prune

Resync
 git fetch upstream ; git merge upstream/master
 git push origin master
Repeat again
```

**Comment by zwim** [comment]
> > If the pattern in ./data/hyph/ is newer than the one in the user-directory we ask the user if he wants to update it.
> 
> Everyday, they will be newer :) and most of the time, there would be no change.
> Also, preferably no UI interaction at the time this happens. Preferably in credocument `CreDocument:engineInit()` , may be in a module local function called in there, to keep that one simple. Dunno if some other module should really be involved in that little hacky business :)
> 

OK you are right. Then we check some hash over the files in ```./data/hyph/``` and the files in the user-defined directories. If the hash is the same, no UI interaction, in the other case we ask the user.

Could this hash-check be done on startup?

**Comment by poire-z** [comment]
Mhhhh. You'll probably be the only user of this feature, so it feels a bit tedious to add that much code and work.

Other idea: do that the other way around :)
If some files .pattern exist in `DataStorage:getDataDir().."/data/hyph" `, and have a different size than the one with the same name in the non-writable-by-you-but-writable-by-the-app (I think, @pazos?) `./data/dict/`, copy them there.

**Comment by pazos** [comment]
It is writable using the AssetManager but I don't know if it is writable by the app itself  once it has been extracted (I don't want to know :p)

Anyways, it's easy to test. Just try to write to android.dir.."/"..somefile and see what happens.

**Comment by poire-z** [comment]
Well, excuting thru the Terminal emulator plugin:
`touch /data/data/org.koreader.launcher/files/data/zzz`
got that file created there (verified with file explorer run as root).
So I guess that's a yes :)

**Comment by poire-z** [comment]
Btw, you could already make yourself some shell script (you could run from file browser, see #5804, that you would execute manually after every update) to run:
```
#!/bin/sh
cp /sdcard/koreader/hyph/* /data/data/org.koreader.launcher/files/data/hyph/
```

**Comment by zwim** [comment]
Yes, that's a feasible solution. 
Maybe a folder for ```startup.scripts``` and ```start-once-after-update.scripts``` in the ```/sdcard/koreader/``` folder could do that?

**Comment by pazos** [comment]
@zwim:  I find the concept of copying files to the install dir a bit overengineering. You'll end with two copies and, if the files are big, it can take some time after each update.

The other idea: if files are present under user data dir use them instead of bundled ones makes more sense and it is easier to implement.

**Comment by poire-z** [comment]
> The other idea: if files are present under user data dir use them instead of bundled ones makes more sense and it is easier to implement.

I agree that for this specific use case (using an alternative German.pattern), this is probably the quicker and easier solution for you to have it working tomorrow :)
Just copy all our patterns in the user dir koreader/data/hyph, replace the one you want, and let KOReader (with 3 added lines of code) check and use that dir. And you'll update it when you think it needs it.

But Hyphenation dicts in the private android app dir are not the only stuff a user can't modify/add to. `data/styles/(epub.css,html5.css...)` too can't be modified/added to - so we might have to do that check for `data/styles` too... (and document what stuff can be redirected).

There might be some other Features Requests (like this one) that would require work and convoluted design and UI choices, that could be solved (and closed) by such scripts (or patch.lua), for the users that really needs that specific stuff.

I see 2 cases:
- on Android, some stuff is let in, and used only from, the Android private app dir, not accessible to the user: so, we can't add/replace that stuff.
- on all devices, where the above is possible, shipped-but-modified stuff would be overriden on each in-app KOReader update. User-added stuff would survive, but shipped-but-replaced stuff is reset to the shipped version.

Most people don't care and don't need more than our defaults.
But the rare people who do might ask us to implement additional hyph dir use, or Style>.css use - and I'd be happy to be able to discard these FR requests by telling the user he can use such scripts to help himself (like we did in the past with patch.lua :)

(I don't use automatic updates, and don't know much about the process :)

**Comment by zwim** [comment]
Can be closed see:
https://github.com/koreader/koreader/wiki/Android-tips-and-tricks
