### ISSUE TITLE
Dictionaries not rendering paragraphs

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#6250]
KOReader version: 2020.05.1-32
    Device: Kobo Aura 1

I've read through this link. https://github.com/koreader/koreader/wiki/Dictionary-support#html-encoding-within-stardict-dictionaries-supported
I don't follow fully, but I'll try it if there isn't another way.

Some dictionaries don't show paragraphs properly, like NOED or ConciseOED. Only occasionally it renders styles correctly, like here when searching 'deplore'. 
![Reader_2020-06-10_022322](https://user-images.githubusercontent.com/16507083/84287002-5e1b6680-ab0d-11ea-815a-954f06cb98ee.png)

![Reader_2020-06-10_005921](https://user-images.githubusercontent.com/16507083/84233435-55507380-aac0-11ea-850b-f9833f54604d.png)
![Reader_2020-06-10_005907](https://user-images.githubusercontent.com/16507083/84233438-571a3700-aac0-11ea-820b-601f41eb0bf8.png)
![Reader_2020-06-10_005847](https://user-images.githubusercontent.com/16507083/84233439-571a3700-aac0-11ea-90ab-aaf0690e6731.png)
![Reader_2020-06-10_005746](https://user-images.githubusercontent.com/16507083/84233441-57b2cd80-aac0-11ea-96fb-baa1a5b95cc2.png)

I'm wondering if there is a way to edit some files within Koreader itself so that paragraphs are rendered consistently across dictionaries. The American Heritage Dictionary shows paragraphs correctly. Gcide is ok, except the first entry isn't listed like other entries after it. The two Oxfords don't show paragraphs for the most part.

Not a huge issue though, just minor enhancement

**Comment by CalbertAmu** [comment]
That's alright. I'll try and see if I can follow that Wiki. Thank you

**Comment by poire-z** [comment]
I think I made something that's supposed to accept bad XHTML and try to make it right before feeding it to MuPDF.
It's the `PetitRobert2007_1.1.lua.txt` at https://github.com/koreader/koreader/pull/3585#issuecomment-361203757
You could try just renaming it as yourdict.lua and put it alongside yourdict.ifo, may be it will improve thing (and you can try to understand it and adapt it - and remove what you don't need)
