### ISSUE TITLE
How can I tighten the multiswipes component?

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6261]
When I migrate to an embedded device, I don't support touch gestures. How can I tighten the multiswipes component?

**Comment by Frenzie** [comment]
If you mean something like remove/disable, they're currently located in https://github.com/koreader/koreader/blob/1384b5e97d738352ed04a130b23152d210dbfd33/frontend/apps/reader/modules/readergesture.lua

Specifically:
https://github.com/koreader/koreader/blob/1384b5e97d738352ed04a130b23152d210dbfd33/frontend/apps/reader/modules/readergesture.lua#L1229-L1265

**Comment by kuailedeluojie-sudo** [comment]
> 如果您的意思是删除/禁用，则它们当前位于https://github.com/koreader/koreader/blob/1384b5e97d738352ed04a130b23152d210dbfd33/frontend/apps/reader/modules/readergesture.lua
> 
> 特别：
> https://github.com/koreader/koreader/blob/1384b5e97d738352ed04a130b23152d210dbfd33/frontend/apps/reader/modules/readergesture.lua#L1229-L1265


我是想让它支持这个组件来支持触摸手势的功能。
I want it to support this component to support the function of touch gesture.

**Comment by Frenzie** [comment]
Everything it does is touch gestures. I'm afraid I don't quite understand. Maybe have a look at https://github.com/koreader/koreader-base/tree/7b5568a3c44179fbcedafa22ee03701171539727/input ?

**Comment by kuailedeluojie-sudo** [comment]
> 它所做的只是触摸手势。恐怕我不太了解。也许看看https://github.com/koreader/koreader-base/tree/7b5568a3c44179fbcedafa22ee03701171539727/input吗？

Since the last time I was on raspberry pie, the problem of supporting touch gesture hasn't been solved. But X11 and QT support touch gesture. I think the code of SDL should be modified, but I don't know where to start.

**Comment by Frenzie** [comment]
Cross-ref to https://github.com/koreader/koreader/issues/6207#issuecomment-635940914.

What exactly isn't working? In principle SDL on X11 supports all *single* touch gestures.

![Peek 2020-06-12 11-08](https://user-images.githubusercontent.com/202757/84486083-2cd1a080-ac9d-11ea-8bb3-c1e35f42dd50.gif)

**Comment by kuailedeluojie-sudo** [comment]
> 交叉引用[＃6207（注释）](https://github.com/koreader/koreader/issues/6207#issuecomment-635940914)。
> 
> 到底什么不起作用？原则上，X11上的SDL支持所有_单_点触摸手势。
> 
> ![窥视2020-06-12 11-08](https://user-images.githubusercontent.com/202757/84486083-2cd1a080-ac9d-11ea-8bb3-c1e35f42dd50.gif)

不是鼠标不起作用，是用手指去触摸得时候不起作用
It's not a mouse that doesn't work, it's a finger that doesn't work

https://github.com/koreader/koreader/issues/6207
![image](https://user-images.githubusercontent.com/60098441/84486790-72f42780-acd0-11ea-9bdd-6e9ddc5d8e69.png)
![image](https://user-images.githubusercontent.com/60098441/84486805-77b8db80-acd0-11ea-9538-021f68f28c54.png)
![image](https://user-images.githubusercontent.com/60098441/84486817-7d162600-acd0-11ea-99ee-e6dc852a9791.png)
![image](https://user-images.githubusercontent.com/60098441/84486822-81424380-acd0-11ea-804e-56600eb445b8.png)

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84486892-9a4af480-acd0-11ea-9daa-d0315e19b33e.png)
![image](https://user-images.githubusercontent.com/60098441/84486906-9dde7b80-acd0-11ea-85df-e99a9e592650.png)
![image](https://user-images.githubusercontent.com/60098441/84486916-a0d96c00-acd0-11ea-8272-78f91bcee6d2.png)
![image](https://user-images.githubusercontent.com/60098441/84486927-a3d45c80-acd0-11ea-9b06-5cf196cfdd33.png)

**Comment by Frenzie** [comment]
According to your screenshots your finger is controlling a mouse cursor. Does it not click?

You can add some print statements [here](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L263-L386) in relevant locations to see what it's getting, if anything. See `/usr/include/SDL2/SDL_events.h` or whatever the relevant location is on your system in case it's an unknown event.

The SDL_FINGERMOTION, SDL_FINGERDOWN, and SDL_FINGERUP events in there already provide support for touch-based platforms. I don't know if they're relevant to your X11 setup.

**Comment by kuailedeluojie-sudo** [comment]
> 根据您的屏幕截图，您的手指正在控制鼠标光标。不点击吗？
> 
> 您可以[在此处](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L263-L386)的相关位置添加一些打印语句，以查看得到的内容（如果有）。查看`/usr/include/SDL2/SDL_events.h`或发现系统上任何相关位置，以防万一这是未知事件。
> 
> 其中的SDL_FINGERMOTION，SDL_FINGERDOWN和SDL_FINGERUP事件已经提供了对基于触摸的平台的支持。我不知道它们是否与您的X11设置有关。

It's actually clicked. See this link for details
https://github.com/koreader/koreader/issues/6207#issuecomment-636253723

**Comment by kuailedeluojie-sudo** [comment]
屏幕点击的时候不起作用是真的。
屏幕点击的时候不起作用是真的。
It's true that screen clicks don't work.

**Comment by kuailedeluojie-sudo** [comment]
> > 根据您的屏幕截图，您的手指正在控制鼠标光标。不点击吗？
> > 您可以[在此处](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L263-L386)的相关位置添加一些打印语句，以查看得到的内容（如果有）。查看`/usr/include/SDL2/SDL_events.h`或发现系统上的任何相关位置，以防万一这是未知事件。
> > 其中的SDL_FINGERMOTION，SDL_FINGERDOWN和SDL_FINGERUP事件已经提供了对基于触摸的平台的支持。我不知道它们是否与您的X11设置有关。
> 
> 它实际上已被单击。有关详细信息，请参见此链接。
> 
> [＃6207（评论）](https://github.com/koreader/koreader/issues/6207#issuecomment-636253723)



> 根据您的屏幕截图，您的手指正在控制鼠标光标。不点击吗？
> 
> 您可以[在此处](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L263-L386)的相关位置添加一些打印语句，以查看得到的内容（如果有）。查看`/usr/include/SDL2/SDL_events.h`或发现系统上任何相关位置，以防万一这是未知事件。
> 
> 其中的SDL_FINGERMOTION，SDL_FINGERDOWN和SDL_FINGERUP事件已经提供了对基于触摸的平台的支持。我不知道它们是否与您的X11设置有关。

i don't find `/usr/include/SDL2/SDL_events.h`.

**Comment by Frenzie** [comment]
It's part of the libsdl2-dev package (or whatever its exact name is). But it's only relevant if you get an event that isn't currently recognized, to find out what it is.

**Comment by kuailedeluojie-sudo** [comment]
> 它是libsdl2-dev软件包的一部分（或其确切名称）。但这仅与您获得当前无法识别的事件有关，以找出它是什么。



触摸手势打印
Touch gesture printing

![image](https://user-images.githubusercontent.com/60098441/84503231-6978b880-acec-11ea-8537-033d340342f6.png)


鼠标动作打印
Mouse action printing


![image](https://user-images.githubusercontent.com/60098441/84503287-87deb400-acec-11ea-97ab-db20bd50255b.png)

**Comment by Frenzie** [comment]
You can confirm here whether it's a mouse event (which seems by far the most likely) or a finger event:
https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316

Assuming you didn't tap in the very top left that's definitely curious.

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84505159-d04ba100-acef-11ea-8aab-f75818d040b3.png)

base\ffi\SDL2_0.lua

![image](https://user-images.githubusercontent.com/60098441/84505173-d93c7280-acef-11ea-8bf1-75e6eb915e7f.png)



修改base\ffi\SDL2_0.lua 的内容后提示错误
Modify base \ FFI \ sdl2_ Prompt error after 0.lua content

**Comment by kuailedeluojie-sudo** [comment]
> 您可以在此处确认是否是鼠标事件（到目前为止似乎是最有可能的）或手指事件：[https](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316) :
> [//github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316)
> 
> 假设您没有点击左上角，那肯定很好奇。

https://github.com/koreader/koreader/issues/6261#issuecomment-643258179

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84505862-0c333600-acf1-11ea-89c1-d906cc4487a9.png)


![image](https://user-images.githubusercontent.com/60098441/84505888-15bc9e00-acf1-11ea-97f4-2cf5364f0a3f.png)

你说的对
you are right

**Comment by Frenzie** [comment]
keydown and keyup are keyboard events

As to your error, it's indicated in the error itself. On line 263 you started the string `"event.type`

**Comment by kuailedeluojie-sudo** [comment]
> > 您可以在此处确认是否是鼠标事件（似乎是最有可能的）或手指事件：[https](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316)：
> > [//github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304 -L316](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316)
> > 假设您没有点击左上角，那肯定很好奇。
> 
> [第6261章（评论）](https://github.com/koreader/koreader/issues/6261#issuecomment-643258179)

https://github.com/koreader/koreader/issues/6261#issuecomment-643262258

**Comment by kuailedeluojie-sudo** [comment]
> keydown and keyup are keyboard events
> 
> As to your error, it's indicated in the error itself. On line 263 you started the string `"event.type`

https://github.com/koreader/koreader/issues/6261#issuecomment-643262258

**Comment by kuailedeluojie-sudo** [comment]
> > > 您可以在此处确认是否是鼠标事件（似乎是最有可能的）或手指事件：[https](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316)：
> > > [//github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304 -L316](https://github.com/koreader/koreader-base/blob/7b5568a3c44179fbcedafa22ee03701171539727/ffi/SDL2_0.lua#L304-L316)
> > > 假设您没有点击左上角，那肯定很好奇。
> > 
> > 
> > [第6261章（评论）](https://github.com/koreader/koreader/issues/6261#issuecomment-643258179)
> 
> [#6261 (comment)](https://github.com/koreader/koreader/issues/6261#issuecomment-643262258)


我该怎么修改这个程序让它支持触摸显示？
How can I modify this program to support touch display?

**Comment by Frenzie** [comment]
Note that the message you printed is meaningless, you would need `error(is_finger)` to determine which one it is.

**Comment by kuailedeluojie-sudo** [comment]
> 请注意，您打印的消息毫无意义，您需要`error(is_finger)`确定它是哪一条。


好的，我尝试一下
OK, I'll try

**Comment by kuailedeluojie-sudo** [comment]
> > 请注意，您打印的消息毫无意义，您需要`error(is_finger)`确定它是哪一条。
> 
> 好的，我尝试一下
> OK, I'll try

![image](https://user-images.githubusercontent.com/60098441/84506732-5cf75e80-acf2-11ea-935d-7a867f4b8c0f.png)

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84506816-7a2c2d00-acf2-11ea-8fdf-eb5c2874d295.png)
![image](https://user-images.githubusercontent.com/60098441/84506838-83b59500-acf2-11ea-9952-de8c0a1d1834.png)

添加这段后显示不正常
Abnormal display after adding this paragraph

**Comment by Frenzie** [comment]
So it's a normal mouse event, not a finger event. I'm not sure what you mean by abnormal display; you're the one opting to use `error` here. :-P

**Comment by Frenzie** [comment]
Anyway, so that means it's something about your X11 or possibly SDL2. Easy to verify with a random SDL2 app.

**Comment by kuailedeluojie-sudo** [comment]
> 无论如何，这意味着这与您的X11或SDL2有关。易于使用随机的SDL2应用程序进行验证。

![image](https://user-images.githubusercontent.com/60098441/84507432-62a17400-acf3-11ea-80a2-dccec499ae4d.png)

**Comment by kuailedeluojie-sudo** [comment]
> 因此，这是正常的鼠标事件，而不是手指事件。我不确定您所说的异常显示是什么意思；您就是选择在`error`这里使用的人。:-P


我对lua语言不熟悉，所以有些犯一些语法错误
I'm not familiar with Lua, so I made some grammatical mistakes

**Comment by kuailedeluojie-sudo** [comment]
我该如何修改这部分代码，让它支持触摸手势？
How can I modify this code to support touch gestures?

**Comment by kuailedeluojie-sudo** [comment]
> 我该如何修改这部分代码，让它支持触摸手势？
> How can I modify this code to support touch gestures?

![image](https://user-images.githubusercontent.com/60098441/84507810-f7a46d00-acf3-11ea-9ead-4dd5769c6779.png)
****

**Comment by pazos** [comment]
> 我该如何修改这部分代码，让它支持触摸手势？
> How can I modify this code to support touch gestures?

- Learn the program you're trying to port
- Learn how your hardware works (touchscreen driver, kind of events it sends, how is recognized by X11)
- Ask specific questions about your issues (documenting first how your hardware works, how do you modified the software to adapt it to your harware, expected behaviour and results)
- Do not open duplicates 

You're trying to port KOReader to a new target. Do not expect magic solutions. 😉

**Comment by kuailedeluojie-sudo** [comment]
> > 我该如何修改这部分代码，让它支持
> > 触摸手势？
> 
> * 了解您要移植的程序
> * 了解您的硬件如何工作（触摸屏驱动程序，它发送的事件类型，X11如何识别）
> * 询问有关您的问题的特定问题（首先记录您的硬件如何工作，如何修改软件以使其适应硬件，预期的行为和结果）
> * 不要打开重复项
> 
> 您正在尝试将KOReader移植到新目标。不要指望魔术解决方案。😉

I do it directly with the driver written by others, and I don't know how to implement it, so I can't start this part. Is there a better solution?

**Comment by pazos** [comment]
Drivers are always written by others!!!!

You don't need to know their inner working, just the type of output they produce. You're trying to get help but you didn't document the bare minimum info about your hardware.

> Is there a better solution?

Document your touchscreen driver (manufacturer, evtest output, X11 config) or hire someone that can do it for you.

**Comment by kuailedeluojie-sudo** [comment]
> 驱动程序总是由其他人编写！！！
> 
> 您不需要知道它们的内部工作原理，只需知道它们产生的输出类型即可。您试图获得帮助，但没有记录有关硬件的最基本信息。
> 
> > 有更好的解决方案吗？
> 
> 记录您的触摸屏驱动程序（制造商，evtest输出，X11配置）或雇用可以帮助您的人。

https://github.com/cutiepi-io/cutiepi-drivers

The changes of cutiepi include new kernel module, device tree overlay, mainly for DSI screen output, touch chip, and WiFi https://github.com/cutiepi-io/cutiepi-drivers This library

**Comment by kuailedeluojie-sudo** [comment]
> > 驱动程序总是由其他人编写！！！
> > 您不需要知道它们的内部工作原理，只需知道它们产生的输出类型即可。您试图获得帮助，但没有记录有关硬件的最基本信息。
> > > 有更好的解决方案吗？
> > 
> > 
> > 记录您的触摸屏驱动程序（制造商，evtest输出，X11配置）或雇用可以帮助您的人。
> 
> https://github.com/cutiepi-io/cutiepi-drivers
> 
> cutiepi的更改包括新的内核模块，设备树覆盖（主要用于DSI屏幕输出，触摸芯片和WiFi）https://github.com/cutiepi-io/cutiepi-drivers此库
> 
> 这是硬件的所有资料，谢谢你
> ！

提供的这些资料有帮助吗？我很想成功移植这个软件到这个硬件上面去。
Is the information provided helpful? I would like to successfully migrate this software to this hardware.

**Comment by pazos** [comment]
> Is the information provided helpful? 

No by itself, but can help you to find more relevant info, like https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver/#troubleshooting

Anyways I'm not going to do the research for you.

**Comment by kuailedeluojie-sudo** [comment]
> > 提供的信息有帮助吗？
> 
> 本身没有，但是可以帮助您找到更多相关信息，例如https://gitlab.com/AdyaAdya/goodix-touchscreen-linux-driver/#troubleshooting
> 
> 无论如何，我不会为您做研究。

thank  you!

**Comment by kuailedeluojie-sudo** [comment]
've tried to compile this driver, but I still don't support touch gestures. I wonder if it's because the SDL file hasn't been compiled.

**Comment by pazos** [comment]
This one broke my heart:
![2020-06-13_12-40](https://user-images.githubusercontent.com/975883/84566629-11d16000-ad73-11ea-997c-e293cc0f98eb.png)

I did wrote a little guide of what I would do to make an embedded device based on a Raspberry Pi and a random touchscreen before looking at your screenshot. Here is it:

1. Use `evtest` to figure out which node in /dev/input/eventX is your touchscreen.
2. Copy the output of `evtest` and [figure the touch protocol](https://www.kernel.org/doc/html/v4.17/input/multi-touch-protocol.html)(ST,MT-B). MT-A is unsupported.
3. Determine which is the default screen orientation and run `evtest` again to see if coordinates are swapped, mirrored or rotated.
4. Write an input handler (based on any of the already supported platforms like kobo, cervantes, kindle, remarkable).
5. Create a new device with SDL as output and the input handler as the input.
6. modify https://github.com/koreader/koreader-base/blob/master/ffi/input.lua to always return require("libs/libkoreader-input")

But now I think spending time here is pointless and you will still ask questions that has nothing to do with our answers.

Please keep your questions here (or on the original issue, this one is a duplicate) and do not open newer issues for the same topic. Thanks!

**Comment by kuailedeluojie-sudo** [comment]
> This one broke my heart:
> ![2020-06-13_12-40](https://user-images.githubusercontent.com/975883/84566629-11d16000-ad73-11ea-997c-e293cc0f98eb.png)
> 
> I did wrote a little guide of what I would do to make an embedded device based on a Raspberry Pi and a random touchscreen before looking at your screenshot. Here is it:
> 
> 1. Use `evtest` to figure out which node in /dev/input/eventX is your touchscreen.
> 2. Copy the output of `evtest` and [figure the touch protocol](https://www.kernel.org/doc/html/v4.17/input/multi-touch-protocol.html)(ST,MT-B). MT-A is unsupported.
> 3. Determine which is the default screen orientation and run `evtest` again to see if coordinates are swapped, mirrored or rotated.
> 4. Write an input handler (based on any of the already supported platforms like kobo, cervantes, kindle, remarkable).
> 5. Create a new device with SDL as output and the input handler as the input.
> 6. modify https://github.com/koreader/koreader-base/blob/master/ffi/input.lua to always return require("libs/libkoreader-input")
> 
> But now I think spending time here is pointless and you will still ask questions that has nothing to do with our answers.
> 
> Please keep your questions here (or on the original issue, this one is a duplicate) and do not open newer issues for the same topic. Thanks!




First contact with Lua, first contact with koreader, thank you for your support!
