### ISSUE TITLE
Back to exit settings don't work

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6263]
* KOReader version: from 2019.11 to 2020.05
* Device: Android (all of them)

#### Issue

Back button will exit KOReader ignoring current configuration on "Navigation" -> "Back to exit" -> Disable.

#### Steps to reproduce

Disable back to exit and press the back button a few times. Each time you press the back button you navigate to the previous menu, except the last one, when pressing back button will exit KOReader in spite of the settings.

#### Reported in https://www.mobileread.com/forums/showthread.php?t=330672

I also checked that it wasn't a problem with the android backend https://www.mobileread.com/forums/showpost.php?p=3999429&postcount=5

**Comment by pazos** [comment]
I'm not familiarized with the code path but seems that [`FileChooser:onBack()`](https://github.com/koreader/koreader/blob/46221985a6515bfcbb58b9f5059af47e9b858cf6/frontend/apps/filemanager/filemanager.lua#L479-L502) is never called or, at least, I couldn't find it.

**Comment by Frenzie** [comment]
Is there an implicit "in the file browser"?

**Comment by NiLuJe** [comment]
Very few things apparently generate a "Back" event (short, of, well, a Back key, one would hope?): the gesture manager, and that's it.

I vaguely seem to recall that the physical back button on Kindles is honored in the FM?

**Comment by Frenzie** [comment]
That's right, it's not available on most platforms. Anyway, in the meantime I found the relevant issue: #4705.

**Comment by pazos** [comment]
> Is there an implicit "in the file browser"?

Yeah, it happens in the browser.

> Very few things apparently generate a "Back" event (short, of, well, a Back key, one would hope?): the gesture manager, and that's it.

I can trigger a proper prompt using a gesture with the back event. Pressing the back button will skip the prompt and exit KOReader directly. That's confusing :/

**Comment by NiLuJe** [comment]
Hmm. Double-checked on a K4, the "Back in filemanager" setting (Gear > Navigation) is honored here.

If set to "go to parent folder" (the default, I assume), it does that, and if it's set to "prompt", it does that, too.

(FWIW, Back also works inside our own menus, since the "back" arrow cannot otherwise be reached).

**Comment by pazos** [comment]
> Hmm. Double-checked on a K4, the "Back in filemanager" setting (Gear > Navigation) is honored here.

It's android specific. I cannot reproduce on emulator and cannot reproduce on my cervantes if I remap the home button to back.

It is also specific of how the event "Back" is consumed on android. I replaced the logic of frontend/device/input.lua to return new "Back" events directly instead of returning "KeyPress"/"KeyRelease" and can reproduce it.

```diff
diff --git a/frontend/device/input.lua b/frontend/device/input.lua
index 0c580890..2fc2b56b 100644
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -13,6 +13,14 @@ local input = require("ffi/input")
 local logger = require("logger")
 local _ = require("gettext")
 
+local function isAndroid()
+    local ok, android = pcall(require, "android")
+    if not ok then return end
+    return android
+end
+
+local android = isAndroid
+
 -- luacheck: push
 -- luacheck: ignore
 -- constants from <linux/input.h>
@@ -323,11 +331,19 @@ function Input:handleKeyBoardEv(ev)
         return keycode
     end
 
+    -- handle android back button quirks
+    if keycode == "Back" and android then
+        if ev.value == EVENT_VALUE_KEY_PRESS then
+            return Event:new("Back")
+        end
+        -- do nothing on key release
+        return
+    end
+
     -- The hardware camera button is used in Android to toggle the touchscreen
     if keycode == "Camera" and ev.value == EVENT_VALUE_KEY_RELEASE
         and G_reader_settings:isTrue("camera_key_toggles_touchscreen") then
-        local isAndroid, android = pcall(require, "android")
-        if isAndroid then
+        if android then
             -- toggle touchscreen behaviour
             android.toggleTouchscreenIgnored()
 ```

With the same code, if I return nil on both press and release the back key obviously doesn't work.

**Comment by NiLuJe** [comment]
@pazos: You think we're eating two back events because one is sent on KeyRelease? Huh.

**Comment by poire-z** [comment]
@pazos : did your #6269 solved your/this issue?

**Comment by pazos** [comment]
Not really. It eats the back event everywhere, so certainly it doesn't trigger an exit, but the issue still stands.

The workaround is useful for broken devices that replay the event.

**Comment by poire-z** [comment]
@pazos : did #6840 solved by luck your/this issue? :)

**Comment by pazos** [comment]
> Device: Android (all of them)

@poire-z: at least that is not true anymore, I can't repro on my tablet. I will check on the emulator tomorrow.
