### ISSUE TITLE
Zoomed RTL content starts from the left side

### ISSUE THREAD

**Issue by Svahnen** [koreader/koreader#6270]
* KOReader version: 202005000046
* Device: KOBO Aura One

#### Issue
When reading Manga or other RTL content (with RTL page flipping turned on) the wrong side of the page is displayed first when the page is zoomed in.

#### Steps to reproduce
Turn on RTL, read any manga that have an image that spans two pages and turn on for example zoom to height, then when flipping pages the left side of the page is displayed first, even tho with RTL turned on the right side should be displayed first.

**Comment by NiLuJe** [comment]
Did this happen on 2020.05 (stable)?

**Comment by poire-z** [comment]
I'm assuming this issue is about the RTL toggle in the bottom menu, with PDFs.
Your #6241 only touched ReaderRolling, used with EPUBs, and should have no impact on PDFs :)

**Comment by Svahnen** [comment]
> I'm assuming this issue is about the RTL toggle in the bottom menu, with PDFs.
> Your #6241 only touched ReaderRolling, used with EPUBs, and should have no impact on PDFs :)

Yes this is about the RTL toggle in the menu, the files i have tried have been PDF and CBZ.

**Comment by poire-z** [comment]
I guess this is solved by #6885 and it's new reading direction buttons:
