### ISSUE TITLE
Google fonts plugin

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6272]
While playing with calibre metadata I discovered the [Google Fonts developer API](https://developers.google.com/fonts/docs/developer_api) and did a few tests. It is pretty easy to list fonts by category (serif, sans-serif...) and sort them by different topics (alphabetically, popularity, trending...) Downloading them is quite fast.

I don't know if an utility like this is a good idea for a plugin given that font preview is not avaiable (or requires to download the font variant first), but I was thinking in something like "editor choice" with a list of "curated" fonts that can be useful for users.

So the plugin would have the whole search 1000+ fonts that google made available but its main page would be a list of a few "preapproved" fonts, readily available to download.

**Comment by NiLuJe** [comment]
My main issue with Google Fonts is that it's generally serving outdated autohinted TTFs (possibly subsett'ed to within an inch of their lives, too), but I'm, err, a bit *picky* about fonts, so eh ^^.

**Comment by pazos** [comment]
> My main issue with Google Fonts is that it's generally serving outdated autohinted TTFs (possibly subset'ted to within an inch of their lives, too), but I'm, err, a bit _picky_ about fonts, so eh ^^.

I have no problem in ditching Google fonts and downloading curated fonts from your server instead ^^

**Comment by NiLuJe** [comment]
That'd be quick: [a mangled Literata 3](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Kobo_Hacks/Patches/REMINDER#L125) :D.

**Comment by poire-z** [comment]
> given that font preview is not avaiable (or requires to download the font variant first)

Personally, a font preview, to see the font standalone'ly, wouldn't help me much (I may like it at first sight :) - I somehow need to compare it to others to really judge it (and I then may loathe the one I loved at first sight :) So, my need for the "Generate font test document" helper.

> downloading curated fonts 

We could provide additional font packs (whether they can be downloaded via a plugin or some core code, or manually on github or koreader.rocks) - but there would be some work to check licenses, and to keep them updated (and what to do when the update makes it worse :) or when we disagree whether it makes it worse or not :)
(And/or have crengine reports unicode codepoints of missing glyphs for a book, so we can guess what coverage is missing, and propose downloading the adequate Noto Something.)

Just mentionning (discovered that yesterday) that my favorite font (love at first sight, and 4 years of living together with a few infidelities), Bitter, https://www.huertatipografica.com/en/fonts/bitter-ht, has been upgraded:
https://github.com/solmatas/BitterPro - it got many weights and some opentype features like small caps, and some bugs fixed - regular is to thin to my liking, but medium gives me what the original bitter regular was - but it also got now a really too large line height :/).
https://github.com/TypeNetwork/Bitter - these people have forked the previous one, applied some stuff to it (that I don't really understand), and gave it back its original line height, which makes it fine to me.

**Comment by NiLuJe** [comment]
gftools `fix-vertical-metrics` is very handy to "fix"/tweak line-heights ;).

(You kinda need an idea how what values to use, though, so having a look at the metrics in Fotnforge still helps ;)).

**Comment by NiLuJe** [comment]
(And, yeah, Bitter is one of the best slab serif fonts out there... with Bookerly ;p).

**Comment by pazos** [comment]
My original suggestion was meant as a low-effort counterpart of bundled fonts. Following the logic of https://github.com/koreader/koreader-fonts/issues/3#issuecomment-461833406

But a few selected fonts hosted elsewhere is better. Specially if approved by font-picky persons :smile: 

> We could provide additional font packs (whether they can be downloaded via a plugin or some core code, or manually on github or koreader.rocks) - but there would be some work to check licenses, and to keep them updated (and what to do when the update makes it worse :) or when we disagree whether it makes it worse or not :)

a font table with the structure:

```lua
local font = {
    name = "Bitter",
    category = "serif",
    license = "OFL",
    variants = {"regular", "italic", "bold"},
    lastModified = "2019-07-22",
    version = "v15",
    glyphs = { "latin", "latin-ext"},
    files = { -- path to each ttf/otf file
    },
}
```

If an update makes the font worst for everybody just skip it.
If an update makes us disagree then have both the original and the update.

And just use name .. " " .. version to differenciate them

**Comment by pazos** [comment]
> (And, yeah, Bitter is one of the best slab serif fonts out there... with Bookerly ;p. And slab serifs work great on eInk.).

All fonts made by Sol Matas are excellent. Albeit not all look nice on a ereader. One that looks pretty cool is http://www.solmatas.com/abhaya-font/. I do use it for headings in documentation, paired with a sans font for the body.

**Comment by pazos** [comment]
Not interested anymore in this one. Also my token went poof long time ago :p
