### ISSUE TITLE
Some little bugs in spanish "koreader.po"

### ISSUE THREAD

**Issue by carmelocotonto** [koreader/koreader#6276]
* KOReader version:   last version (and perhaps, previous versions)
* Device: kobo CLARA HD

#### Issue
Hi, here are several mistakes:

#: frontend/apps/reader/modules/readerfooter.lua:975
msgid "Container bottom margin (%1)"
msgstr "Margen inferior del contenedor (**% 1**)"    <----------

#: frontend/apps/reader/modules/readerrolling.lua:276
msgid ""
"Styles have changed in such a way that fully reloading the document may be "
"needed for a correct rendering.\n"
"%1Do you want to reload the document?"
msgstr ""
"Los estilos han cambiado de tal manera que puede ser necesario volver a "
"cargar por completo el documento para un renderizado correcto.\n"
"**1%**¿Quiere recargar el documento?"    <----------

#: plugins/coverbrowser.koplugin/bookinfomanager.lua:786
msgid ""
"Found %1 books.\n"
"Looking for those not already present in the cache database…"
msgstr ""
"Encontrados **1%** libros.\n"   <-------------
"Buscando los que aún no están presentes en la caché de la base de datos…"

#: plugins/readtimer.koplugin/main.lua:164
msgid "Timer set for %1%2."
msgstr "Temporizador programado a **las%1%2**."    <-------------

**Comment by elvvis** [comment]
You can correct incorrect translations here:
https://hosted.weblate.org/projects/koreader/koreader/

**Comment by Frenzie** [comment]
As @elvvis said, you can create an account on Weblate and directly submit updates and suggestions there.

For this batch I've updated the strings in question. :-)

> "Los estilos han cambiado de tal manera que puede ser necesario volver a "
"cargar por completo el documento para un renderizado correcto.\n"
"1%¿Quiere recargar el documento?" <----------

That's not a mistake. It inserts an extra line when necessary.
