### ISSUE TITLE
Configurable brightness/warmth step size for tap gesture

### ISSUE THREAD

**Issue by pblasi** [koreader/koreader#6277]
I'd like using tap gesture to control brightness and warmth since swipe gesture (and swipe on frontlight dialog bar) are not really comfortable to use, at least in kobo clara hd.  

Every tap increases/decreases a value of 1. In Clara HD, warmth changes only occur at 10, 20, 30... So, I would like changing step size to 10 for every tap to control warmth. Is it possible?
I would like trying other step sizes for brightness as well, in order to see a bigger brightness change on each tap.

Thanks!

**Comment by poire-z** [comment]
Should be do'able since #6441. Re-open if not.

**Comment by pblasi** [comment]
Great addition! However, it doesn't matter the value I set to "Increase/Decrease frontlight brightness by #". It always apply a step of 5...
