### ISSUE TITLE
Night mode in kobo 

### ISSUE THREAD

**Issue by amir2mi** [koreader/koreader#6278]
* KOReader version: last version
* Device: Kobo Aura 2

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox, or you can use one of these paste services.
Please don't forget to set a high expiration date if you do.
https://pastebin.com https://slexy.org https://paste2.org https://fpaste.org
http://ix.io https://paste.kde.org https://paste.debian.net.

**Comment by NiLuJe** [comment]
Try with an up to date firmware.

**Comment by amirmp3** [comment]
> Try with an up to date firmware.

I updated kobo today and installed Koreader with kobo start menu 9.

**Comment by NiLuJe** [comment]
Then we're going to need more details, an actual FW version, and an actually accurate device name, because there's no such thing as an "Aura 2" (there's an Aura SE, and Aura H2O, and two different revisions of an Aura H2O²).

Also, KSM is unsupported, not that it should matter much now, but, still.

**Comment by NiLuJe** [comment]
And also an accurate and detailed description of what's happening, because right now it milldy looks like you're confusing actual nightmode (i.e., persistent white on black display) with the black flash that intermittently happens on screen refreshes.

**Comment by Frenzie** [comment]
> Also, KSM is unsupported, not that it should matter much now, but, still.

I don't intend to stop using it quite yet. ;-)

**Comment by NiLuJe** [comment]
> 
> 
> > Also, KSM is unsupported, not that it should matter much now, but, still.
> 
> I don't intend to stop using it quite yet. ;-)

It might be mildly problematic if it turns out this is actually one of the Mk. 7 Aura ;).

But not on that front (usually).

**Comment by Frenzie** [comment]
> Aura SE

PS Sounds like a funny way of saying "2". xD

**Comment by amirmp3** [comment]
> And also an accurate and detailed description of what's happening, because right now it milldly looks like you're confusing actual nightmode (i.e., stable white on black display post-refresh) with the black flash that intermittently happens on screen refreshes.

It's really kobo 2 (I say) my Kobo is edition 2 of Aura series.

Product link:
https://us.kobobooks.com/products/kobo-aura

And current software version is 4.21.15015
I think it is updated because today I did it with kobo pc software.

**Comment by amirmp3** [comment]
I think this video can helps to prove this problem. 

https://www.dropbox.com/s/4ihhgtacxwezie2/VID_20200618_002848_00.mp4?dl=1

Undoubtedly Koreader is legend.
I wanted to sell my Kobo due to the bad reader but after experiencing Koreader I changed my mind.

**Comment by Frenzie** [comment]
That is indeed definitely broken. But imo it's not that great even on devices where it does work. Hopefully seeing that triggers some memory on @NiLuJe's part though.

**Comment by NiLuJe** [comment]
The Aura (first of its name) has broken nightmode support. So much so that we blacklist hardware nightmode on it.

So, no, not an Aura.

Get us a crash.log, that'll finally give me a definitive answer.

**Comment by NiLuJe** [comment]
Also, extra question: is this a PDF, and if so, is dithering enabled?

**Comment by amirmp3** [comment]
this is the crash file that I found with searching into my kobo storage.
https://www.dropbox.com/s/f84b22bh2oii10n/crash.log?dl=1

Yes, it is a pdf, I tried many pdf files. also, I tried with an Epub file and it had this problem in NightMode too.

I searched for Dithering but I did not find anything about it.
thanks again.

**Comment by NiLuJe** [comment]
Okay, so, it's an Aura SE.

I'd never heard of issues w/ HW inversion on those, but, obviously, it's hilariously broken on yours.

```diff
diff --git a/frontend/device/kobo/device.lua b/frontend/device/kobo/device.lua
index 8aa67518..808d3048 100644
--- a/frontend/device/kobo/device.lua
+++ b/frontend/device/kobo/device.lua
@@ -164,6 +164,7 @@ local KoboStar = Kobo:new{
     touch_probe_ev_epoch_time = true,
     touch_phoenix_protocol = true,
     display_dpi = 212,
+    canHWInvert = no,
 }
 
 -- Kobo Aura second edition, Rev 2:
```

Should work it around. I'm sort of wary of actually committing that, though, because I've never heard of nightmode issues on the Aura SE. Then again, I haven't seen it being used much, period, which doesn't help.

**Comment by hurzl** [comment]
On Aura HD the night mode is not kept after standby. I have to re-enable it every time.

**Comment by NiLuJe** [comment]
@hurl: That's another kernel bug. Which may or may not be fixed on current FW (IIRC, I vaguely seem to remember someone mentioning something to this effect with an H2O).

**Comment by hurzl** [comment]
Really, it seems to be fixed with firmware 4.21. Thanks

**Comment by amirmp3** [comment]
what a lucky man I am🤦‍♂️
I edited the Kobo devices file and added  ` canHWInvert = no,`  into my Kobo codes.
Fortunately, it worked but just for top menu; I still have this problem in pages and I do not think, it be from my Kobo hardware because in randomly situations night mode works well but generally, it has the problem.

**Comment by amirmp3** [comment]
> 
> 
> Okay, so, it's an Aura SE.
> 
> I'd never heard of issues w/ HW inversion on those, but, obviously, it's hilariously broken on yours.
> 
> ```diff
> diff --git a/frontend/device/kobo/device.lua b/frontend/device/kobo/device.lua
> index 8aa67518..808d3048 100644
> --- a/frontend/device/kobo/device.lua
> +++ b/frontend/device/kobo/device.lua
> @@ -164,6 +164,7 @@ local KoboStar = Kobo:new{
>      touch_probe_ev_epoch_time = true,
>      touch_phoenix_protocol = true,
>      display_dpi = 212,
> +    canHWInvert = no,
>  }
>  
>  -- Kobo Aura second edition, Rev 2:
> ```
> 
> Should work it around. I'm sort of wary of actually committing that, though, because I've never heard of nightmode issues on the Aura SE. Then again, I haven't seen it being used much, period, which doesn't help.

what a lucky man I am🤦‍♂️
I edited the Kobo devices file and added  ` canHWInvert = no,`  into my Kobo codes.
Fortunately, it worked but just for top menu; I still have this problem in pages and I do not think, it be from my Kobo hardware because in randomly situations night mode works well but generally, it has the problem.

**Comment by NiLuJe** [comment]
That.. doesn't make much sense. Double-check that you actually put it in the right place, and have restarted KOReader.

If software nightmode was broken, we'd have heard angry shouts from a mob of Android users ;).

**Comment by hurzl** [comment]
Night mode is still disabled after standby ...

**Comment by Frenzie** [comment]
Note there's a user patch now: https://gist.github.com/NiLuJe/4be737eb123cf1199590b626be131345

More information: https://github.com/koreader/koreader/wiki/User-patches
