### ISSUE TITLE
Problem Accessing OneDrive via WebDAV

### ISSUE THREAD

**Issue by mtlive** [koreader/koreader#6285]
* KOReader version: v2020.06
* Device: Kobo H2O

#### Issue
In case you didn't know, it's possible to access OneDrive via WebDAV with https://d.docs.live.net/[Your CID] where you can get your CID from address bar at your OneDrive home page. (more info: https://winscp.net/eng/docs/guide_microsoft_onedrive).

I tried to add OneDrive as WebDAV on Koreader but faced this error: Can't fetch list of folder contents...

**Comment by pazos** [comment]
> In case you didn't know, it's possible to access OneDrive via WebDAV (...). (more info: https://winscp.net/eng/docs/guide_microsoft_onedrive).

Probably, but WinSCP had to add explicit support for it, see https://github.com/winscp/winscp/commit/7550bec1ea20ba669fd1bb507c7eee8015913488

> I tried to add OneDrive as WebDAV on Koreader but faced this error: Can't fetch list of folder contents...

Somehow expected as we don't have any explicit support here.

Labeling as won't fix. PRs *very* welcome

**Comment by Teng906** [comment]
Hope to add the function of manually setting "letter-spacing"
