### ISSUE TITLE
feature request: scroll 1/3 of page in cropped mode

### ISSUE THREAD

**Issue by Hubert21** [koreader/koreader#6298]
Hello,
I am reading comics on my tablet, and the landscape mode + cropped page feature is great to split the page in 2, read first the top then the bottom, by a "one tap" on the screen.
However, often some cases are in the middle of the page, hence splited in two.
I would like to scroll with one tap not directly to the bottom, but first to the middle.
Thanks

* KOReader version: 2020.06
* Device: Clara HD

**Comment by Frenzie** [comment]
You might want to play around with DOVERLAPPIXELS. Manually create a defaults.persistent.lua and copy it over or use tools → advanced settings editor from the file manager. You'd be looking for a higher value.

https://github.com/koreader/koreader/blob/eee54ffbae305a57faa33be27f80cd28e8239b61/defaults.lua#L62-L63

**Comment by Hubert21** [comment]
Thanks that works very well :)
Maybe an option in the menus would be useful in case some other users would have the same need.

**Comment by Frenzie** [comment]
Settings are slowly migrating away from there. :-) I'll close this issue then, since I don't think we need to track that separately.

**Comment by Hubert21** [comment]
Plus when I searched around "DOVERLAPPIXELS" it appears my question had already been answered.
[https://github.com/koreader/koreader/issues/2818]
