### ISSUE TITLE
Screensaver error

### ISSUE THREAD

**Issue by Anuvadak** [koreader/koreader#6301]
Hey, guys!
Every time I'm trying to set up ANYTHING except for "Leave screen as it is" (settings->Screen->Screensaver) I see this on my kindle. 
![IMG_20200622_223747~2](https://user-images.githubusercontent.com/36309289/85359028-e04c5780-b51d-11ea-93d8-1d401f5bc3b2.jpg)
 Please fix it

**Comment by Galunid** [comment]
Without KOReader version, and which kindle it is and `crash.log` I don't think anyone can help you. Please provide those informations. Additionally do you start KOReader using KUAL or some other way?

**Comment by Frenzie** [comment]
Also if it's special offers, although in that case I think the options shouldn't show?

**Comment by Anuvadak** [comment]
> Without KOReader version, and which kindle it is and `crash.log` I don't think anyone can help you. Please provide those information. Additionally do you start KOReader using KUAL or some other way?

The version is 2020.06 Mosaic. It's the 8th generation of Kindle (2016-2018). I'll try to get the log later

**Comment by NiLuJe** [comment]
That's mildly interesting :).

Does a "show book cover" work? (long-press on a book in the FM).

Do PDF behave?

Do ePubs, for that matter?

Are you reading in a non-standard orientation?

----

Does disabling the C blitter help? (FM, top menu: Tools > Developer settings).

----

NOTE: The last time this happened, it turned out someone had the screensaver folder set to a folder with broken screenshots, so, err, just double-checking here ^^.

**Comment by NiLuJe** [comment]
If you have shell access (i.e., USBNetwork, which bundles both fbgrab & fbink), I wouldn't mind the output from a verbose fbgrab screenshot  (`fbgrab -v dump.png`) (both the console output and the actual screengrab), and, if the screengrab is sane, the same when attempting to re-display it via fbink (`fbink -f -i dump.png`).

**Comment by Frenzie** [comment]
> NOTE: The last time this happened, it turned out someone had the screensaver folder set to a folder with broken screenshots, so, err, just double-checking here ^^.

That someone was me. :-P

But that's not quite accurate. The program defaults to using the screenshots folder under specific circumstances, see https://github.com/koreader/koreader/issues/4418#issuecomment-470262554. I never told it to do that.

**Comment by Anuvadak** [comment]
> That's mildly interesting :).
> 
> Does a "show book cover" work? (long-press on a book in the FM).
> 
> Do PDF behave?
> 
> Do ePubs, for that matter?
> 
> Are you reading in a non-standard orientation?
> 
> Does disabling the C blitter help? (FM, top menu: Tools > Developer settings).
> 
> NOTE: The last time this happened, it turned out someone had the screensaver folder set to a folder with broken screenshots, so, err, just double-checking here ^^.

1) show book cove from works
2) PD, EPUB and DJVU works fine
3) Screen orientation doesn't matter (I use default ones: portrait and landscape) all the same
4) Disabling C blitter doesn't help (cleared cache)
5) The directory of pictures for screensaver and picture (if only one) choosed correctly, all JPGs.

**Comment by NiLuJe** [comment]
I'd add a request for the output of `eips -i -v`, too (or, err, whatever the actual commandline is for the fb details, I don't have a Kindle plugged in right now ^^).

**Comment by Anuvadak** [comment]
> I'd add a request for the output of `eips -i -v`, too (or, err, whatever the actual commandline is for the fb details, I don't have a Kindle plugged in right now ^^).
> 
> (The fact that xres_virtual (and as such line_length) is not a multiple of 32 is highly unusual for an i.MX EPDC, but it's still strange that only screensavers would be broken...).

May you provide a link or a program names for windows or linux (better both) to I can do this? I've never done this before

**Comment by NiLuJe** [comment]
I meant in a shell, over SSH, on the device itself.

Also, on which FW version is this?

**Comment by Anuvadak** [comment]
> I meant in a shell, over SSH, on the device itself.
> 
> Also, on which FW version is this?

Kindle 5.8.7.0.1
If I'm not mistaking it's the last rootable

**Comment by Anuvadak** [comment]
> Also if it's special offers, although in that case I think the options shouldn't show?

There're no special offers on my device, it's full price. And it's always in airplane mode.

**Comment by Anuvadak** [comment]
Well, I decided to make a hard reset and update everything, hope it'll help

**Comment by Anuvadak** [comment]
Well, I flash up the last SW after factory reset and rooting SW 5.8 and after fixing some troubles everything is working just great! The feeling's like I bought a new Kindle)
So, I think it was an cause of old SW

**Comment by Anuvadak** [comment]
May anybody close this issue? It's my first one, I dunno how to

**Comment by Frenzie** [comment]
It should normally say close issue next to where you comment. Closing now.

**Comment by NiLuJe** [comment]
Cool, thanks for confirming my hunch ;). The fact that this is an older, somewhat popular device was mildly suspicious ;).
