### ISSUE TITLE
Bug: Pocketbook Basic 3 not recognized + other

### ISSUE THREAD

**Issue by roshavagarga** [koreader/koreader#6311]
* KOReader version: 2020.06
* Device: Pocketbook Basic 3 (614W or 614-2?)
* Device firmware: [5.17.964](http://download.pocketbook-int.com/fw/Yitoa/614-2/user/20171123/sw_20171123_614-2_U_5.17.964.user.zip) (23rd November 2017, discontinued firmware support)
#### Issue
Merged both folders, opening a book does nothing, neither does opening the app.

#### Steps to reproduce
Merge folders (applications + system), disconnect, try to open the app from 'applications' menu or a book from the main menu. Screen flickers for a second and goes back to where it was.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/4836025/crash.log)

**Comment by Frenzie** [comment]
```
06/26/20-11:53:59 INFO  SoftwareVersion:  U614-2.5.17.964
./luajit: frontend/device/pocketbook/device.lua:379: unrecognized PocketBook model PocketBook 614W
```

You could replace `"PocketBook 613"` by `"PocketBook 614W"` on this line for example to see if it works. The exact device definition may be slightly different but it should suffice for basic testing.

https://github.com/koreader/koreader/blob/43693c9fe9f03e7862f268bfe4b40e1d4bed3fbf/frontend/device/pocketbook/device.lua#L344

The specs at https://productz.com/en/pocketbook-basic-3-614/p/zlYX suggest it's extremely similar to the 613.

**Comment by roshavagarga** [comment]
@Frenzie Already saw that change and I've been tinkering with my zero knowledge.

Added the following to device.lua:

1. New device at lines 233 to 242 (+ two empty lines, one before and one after)
`-- PocketBook 614W Basic
local PocketBook614W = PocketBook:new{
    model = "PB614W",
    display_dpi = 166,
    isTouchDevice = no,
    hasWifiToggle = no,
    hasFrontlight = no,
    hasDPad = yes,
    hasFewKeys = yes,
}`
2. New device model at lines 355 and 366 (codename decided based on existing model file in original system folder)
`elseif codename == "PocketBook 614W" then
    return PocketBook614W`

Now, I'm not entirely sure how the hasDPad and hasFewKeys is supposed to work, but I have noticed this so far:
1. Clicking the central d-pad button open a bottom menu. I can go right but not left in this menu and once one of the menus is selected, clicking it again with the central button does not close it, nor can I find a combination to get out of the menu.

There might be other issues, still looking through it. I have a new crashlog with data about the reader.app I think. The libSDL2 issue still seems to pop up.

**Comment by Frenzie** [comment]
> Now, I'm not entirely sure how the hasDPad and hasFewKeys is supposed to work, but I have noticed this so far:

That's intended behavior for `hasFewKeys`. It means the device is missing some vital keys like "back." It's basically the more polite way of saying "doesn't have enough keys." By using left as back that can be worked around since you can generally still select most things with some planning, but obviously it's far from ideal. There's not really any support for devices like that, see <https://github.com/koreader/koreader/issues/4029>. `hasFewKeys` is part of the device definition so that they'll be properly covered if someone were to work on improving that.

> clicking it again with the central button does not close it, nor can I find a combination to get out of the menu.

Unfortunately that probably means the bottom menu is unusable on hasFewKeys devices. PRs welcome of course. (I can quickly disable the bottom menu on hasFewKeys if you prefer.)

> The libSDL2 issue still seems to pop up.

That's not an issue, just a notification. It'd only be an issue on a platform that uses SDL. ;-)

**Comment by roshavagarga** [comment]
I think the D-pad isn't correctly supported. As far as I can feel, the d-pad has 8 directions, including diagonals, although I may be mistaken. Is there some way for me to check/log what the device sends when a button is pressed? If it turns out that it supports diagonals, those might be used in some matter, or maybe double-clicking, though I faintly remember reading in one of the other issues that it would be hard to implement.

I also updated the previous post, not sure if you saw that, thanks for the quick answers!

**Comment by Frenzie** [comment]
That's news to me. Does that apply to all the PocketBooks that are currently implemented as hasFewKeys? It'd improve things from nearly impossible to slightly awkward.

(Think top left and/or bottom left `back`, top right and/or bottom right `menu`, and you wouldn't have a problem, except perhaps for unintentionally triggering a diagonal.)

> Is there some way for me to check/log what the device sends when a button is pressed?

If you enable debug logging then you'll get output along these lines in crash.log:
```
06/26/20-12:04:41 DEBUG key event => type: 1, code: 226(Alt), value: 1, time: 1593165881.524570
06/26/20-12:04:41 DEBUG key event => type: 1, code: 226(Alt), value: 1, time: 1593165881.988721
06/26/20-12:04:41 DEBUG key event => type: 1, code: 226(Alt), value: 0, time: 1593165881.988848
```

But it might be easier to check `evtest`.

I don't really know anything about PocketBooks. Can you SSH or Telnet into them?

What I might do on Kobo is that I SSH in over wifi (or sometimes USB), and then I `tail -f` the crash.log file.

**Comment by roshavagarga** [comment]
I'm guessing it does, but again, just guessing. The d-pads look the same.

There might be a way to use SSH or Telnet, but you'd have to run me through it, I'm not a developer tbh. Also, I'm working off a Windows-based PC right now, though I should have a prehistoric lubuntu minilaptop lying around if the need arises.

First experiment:
I changed line 47 in koreader.app (applications folder) to this: `    ./reader.lua -d "${args}" >>crash.log 2>&1`

`DEBUG input event => type: 25, code: 10(Press), value: 0
DEBUG input event => type: 26, code: 10(Press), value: 0
DEBUG input event => type: 25, code: 17(Up), value: 0
DEBUG input event => type: 26, code: 17(Up), value: 0
DEBUG input event => type: 25, code: 18(Down), value: 0
DEBUG input event => type: 26, code: 18(Down), value: 0
DEBUG input event => type: 25, code: 19(Left), value: 0
DEBUG input event => type: 26, code: 19(Left), value: 0
DEBUG input event => type: 25, code: 20(Right), value: 0
DEBUG input event => type: 26, code: 20(Right), value: 0
DEBUG input event => type: 25, code: 24(LPgBack), value: 0
DEBUG input event => type: 26, code: 24(LPgBack), value: 0
DEBUG input event => type: 25, code: 25(LPgFwd), value: 0
DEBUG input event => type: 26, code: 25(LPgFwd), value: 0


DEBUG input event => type: 21, code: 0(nil), value: 0
DEBUG input event => type: 23, code: 0(nil), value: 0
DEBUG input event => type: 151, code: 549(nil), value: 0
DEBUG input event => type: 151, code: 570(nil), value: 0
DEBUG input event => type: 151, code: 591(nil), value: 0
DEBUG input event => type: 151, code: 523(nil), value: 0
DEBUG input event => type: 151, code: 612(nil), value: 0
`

**Comment by roshavagarga** [comment]
Second experiment: I opened the Koreader app from the PocketBook UI. When inside the Koreader app I confirmed that each click is registered twice - once as a type 25 and once as a type 26, the codes being the same for each click. Double-clicking is not registered in any fashion, as far as I can see.

Up = code 17
Down = code 18
Left = code 19
Right = code 20
Press = code 10
LPgBack = code 24 (left-most soft key, not d-pad)
LPgFwd = code 25 (right-most soft key, not d-pad)

The on/off key seems to be type 151 and/or type 152 and the code was 1112. The native way that button works is if that you click it once it makes the device fall asleep. If you press and hold it turns the device off. Pressing and holding was not rendered with its own code.

I did discover that while there are clicks on the diagonals, they show one of the d-pad values and not new ones, so they seem to be useless. Upper-right diagonal equals Up, Down-right diag equals down, Interestingly enough both of the left diagonals acted as if I'd clicked the left button, which acted as a 'back' button and threw me to the main menu - this might mean that the diagonals don't have their own codes, but clicking one of them maybe send the signals for both of the neighboring keys. In this case, the upper-right diagonal would send up+right commands, though I saw no evidence of that in the crash log.

The upper-left, down-left and left buttons, when used in the main koreader app menu, would register as type 25 code 19 / type 21 code 0. The first one is probably registered while in the app, the second one when in the PB UI main menu. I'm guesstimating that it is so, because 'Press' clicks (central d-pad button) are registered as type 23 code 0, instead of the appropriate type 25/26 code 10, as seen in the previous logs. Both times I used the 'Press' button to go back to Koreader app I got type 23 code 0 and then a type 151, followed by two differing codes each time - the first time 1070, the second time 1090. I used the sleep code (as mentioned before) at the very end and that was a type 151/152 code 1112, which is weird, since it seems that the code number is growing in a weird manner?

**Comment by pazos** [comment]
> When inside the Koreader app I confirmed that each click is registered twice - once as a type 25 and once as a type 26, the codes being the same for each click. Double-clicking is not registered in any fashion, as far as I can see.

That is normal. One is a key pressed event and the other one is a key released event. It happens in all platforms :-)

**Comment by Frenzie** [comment]
> Also, I'm working off a Windows-based PC right now

Sidenote, but [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/) is widely considered an amazing client. It's even been ported to Linux.

**Comment by roshavagarga** [comment]
Next up is looking at how the buttons are being used when inside a book.

![pb614w](https://user-images.githubusercontent.com/13944976/85856155-24f71d80-b7c0-11ea-8fa9-b2e2ac41536d.jpeg)
This is a reminder of which button is where and what its code is.

**Koreader**
Portrait mode:
LPgBack 24 & Up 17 & Left 19 - goes back by 1 page 
LPgFwd 25 & Down 18 - goes forward by 1 page
Press 10 - opens the bottom menu
Right 20 - opens up top menu

To note: 
In the bottom menu, you can't use LPgBack, LPgFwd or Left. This means you can't exit the menu and get back to the novel.
In the top menu, you can't use LPgBack or LPgFwd and Left can only exit the menu. This means you can't go left through the submenus. Entering things like 'Book information' leads to no option as far as leaving, since there's no 'back' function - left acts as back, but then doesn't in this menu, which only has an X in the upper corner. 

**Portrait mode can't be tested, because of menu issues.**

**Pocketbook**
Portrait mode:
LPgBack 24 & Left 19 - goes back by 1 page
LPgFwd 25 & Right 20 - goes forward by 1 page
Up 17 - Increases font size
Down 18 - Decreases font size
Press 10 - Open menu

Menu: You can leave menu by using either LPgBack 24 or LPgFwd 25.

Landscape mode:
Based on the landscape mode you're using, the d-pad buttons get changed. Up + Down + LPgBack/LPgFwd are used for changing pages, while Left + Right are used to change font size. Personally the way LPgBack/LPgFwd are used is slightly wrong for me, they did the opposite of what I was expecting as far as which one goes forward and which one goes back.

@Frenzie - since the firmware on this device is no longer being developed (and many others), I think partially mimicking some of the uses would be fine. I can give some suggestions, but as I've noted there are some weird bugs/things not being optimized for non-touch devices.

**Comment by Frenzie** [comment]
> but as I've noted there are some weird bugs/things not being optimized for non-touch devices.

`hasFewKeys`-devices. ;-) Very distinct from non-touch devices, unfortunately, or they'd work just fine. My intent with https://github.com/koreader/koreader/issues/4029 is only to send in a cross, to show what manner of things one would need to do.

**Comment by roshavagarga** [comment]
Any way I can fiddle what button is used for what on a per-device level? As I said previously, I'm not a developer and I never learned to code, but if you point me in the right direction and I don't have to write any new code but just rearrange button usage in certain instances I might be able to do it on my own :)

**Comment by Frenzie** [comment]
Sorry GH messed with the link, I meant https://github.com/koreader/koreader/pull/6195. Specifically the diff view: https://github.com/koreader/koreader/pull/6195/files

Something similar would have to be done for other widgets.

**Comment by roshavagarga** [comment]
I think I'll close this one and open a new one. Based on diff view of #6195 I am not seeing what I expected.
I thought there would be a way to tell it what button does what in the central view and in the menus and in the different portrait/landscape views. It's probably just my lack of knowledge, so I'll just open a new PR wit
