### ISSUE TITLE
Sleeping message is really annoying

### ISSUE THREAD

**Issue by xahon** [koreader/koreader#6313]
Is it really needed in the release build?
https://github.com/koreader/koreader/blob/9e9f3b419dc00176f32c5d6fb38bce8ca03fb999/frontend/ui/screensaver.lua#L407-L410

**Comment by xahon** [comment]
Opening file '...' isn't useful too as for me

**Comment by Frenzie** [comment]
You can disable it in Settings → Screen → Add message to screensaver (uncheck).

**Comment by xahon** [comment]
@Frenzie that option is already unchecked by default

**Comment by NiLuJe** [comment]
Then you're probably explicitly using the "message" screensaver mode, perhaps?
