### ISSUE TITLE
Read wallabag articles are left in koreader history. 

### ISSUE THREAD

**Issue by mwoz123** [koreader/koreader#6316]
* KOReader version: nightly 2020-06-19
* Device: android

#### Issue
Although selected in wallabag settings "remove finished from history" 100% read wallabag articles are left in koreader history. 

It seems to be working fine on nightly 2020-05-19

#### Steps to reproduce

Select in wallabag settings "remove finished from history", open wallabag article z read it all, quit to file browser. Open history. Prev article is there

**Comment by Frenzie** [comment]
I can't confirm on 43693c9 (2020-06-25) with "remove finished articles from history" checked. In fact it rather unexpectedly even seems to remove 100% read as opposed to just finished.
