### ISSUE TITLE
FR/Question: Using the kindle's built-in keyboard within KoReader

### ISSUE THREAD

**Issue by rainbowoblivion** [koreader/koreader#6319]
**Does your feature request involve difficulty completing a task? Please describe.**
I understand these devices are legacy, but it can be really difficult and time consuming, definitely when writing OPDS URLs or Searching for OPDS Books, so it would be nice to be able to type with the keyboard! (I personally have a k3gb and the keyboard goes completely to waste as it is not utilized. 

**Describe the solution you'd like**
An option to make replace the onscreen keyboard with the built-in keyboard of the k3, along with a symbol navigation pop-up.

**Describe alternatives you've considered**
An improvement, for these devices, which I feel would probably be less work would be to allow the keyboard to flow like snake, so when you reach the end on the left it appears on the right of the keyboard and vice-versa.

**Comment by Frenzie** [comment]
> An improvement, for these devices, which I feel would probably be less work would be to allow the keyboard to flow like snake, so when you reach the end on the left it appears on the right of the keyboard and vice-versa.

By sheer coincidence, that's https://github.com/koreader/koreader/pull/6315.

**Comment by xahon** [comment]
I want the same for pocketbook. Pocketbook's default keyboard doesn't miss touches when you press them quickly (Like buffering in different thread) unlike koreader's one

**Comment by pazos** [comment]
> I want the same for pocketbook. Pocketbook's default keyboard doesn't miss touches when you press keys quickly (Like buffering in different thread) unlike koreader's one

But they're not the same thing. This FR is about repurposing physical buttons and your request is using the same virtual keyboard pocketbook is using on their FW. I don't know if that is doable at all (probably not).

**Comment by NiLuJe** [comment]
That's completely not feasible on Kindle, FWIW.

**Comment by NiLuJe** [comment]
Oh, wait. You meant the *physical* keyboard :D.

That's probably doable, on the other hand, and there shouldn't be any platform-specific quirk, so it could come in handy on the emulator and Android, too ;).

(I was thinking of the stock on-screen virtual keyboiard on Touch devices, my bad).

**Comment by Frenzie** [comment]
Maybe for (very) basic functionality it would suffice to do something akin to:

https://github.com/koreader/koreader/blob/37cf106fce5964b51cf49054eb2a2f3f03ef3adb/frontend/ui/widget/menu.lua#L1102-L1114

**Comment by clach04** [comment]
This might help #6327 for the devices that have keyboards.

**Comment by clach04** [comment]
@Frenzie is your code snippet functional or an idea? Wondering if I should copy/paste this into my device and play with it :)

**Comment by Frenzie** [comment]
@clach04 Only where it's used. I just figured conveying the general principle was quicker and possibly easier with actual code than by trying to explain it in text or pseudo-code.

**Comment by Commodore64user** [comment]
this is functional now (for the most part at least), unless it isn't...?
