### ISSUE TITLE
FR: [Book cover searching]

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#6325]
Hi developer, 
I wonder if Koreader have the function to search and add book cover for a book? As some of my downloaded books don't have cover image, so the screen saver only show "Sleeping".
It's fantastic if Koreader can fetch book cover when we connect to wifi.
Thank you.

**Comment by Frenzie** [comment]
Goodreads might be able to provide for something like that but nothing like that is currently implemented.
