### ISSUE TITLE
Hyphenation is disabled, but seems is active on newly opened epubs

### ISSUE THREAD

**Issue by mikkelnl** [koreader/koreader#6326]
* KOReader version: 2020.06
* Device: Pocketbook Touch HD 3

#### Issue
Hyphenation is disabled, this used to work and still does on books I've opened before. But somehow hyphenation is happing on newly opened books it seems. Books that are opened for the first time now have Hyphenation, but the setting still is 'disabled'.

**Comment by poire-z** [comment]
This seems to work for me.

There's been a change some months ago: the hyphenation menu has been renamed Typography, and hyphenation is a sub-setting:
<kbd>![image](https://user-images.githubusercontent.com/24273478/85955241-6f71c900-b97d-11ea-968f-5b38d1e79214.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/85955247-7d274e80-b97d-11ea-8ba4-c3b96f8922ce.png)</kbd>

What you see here is that Hyphenation is disabled _for the current book_. We don't/can't really show the default value for future opened books in this menu (we use a black star in multiple options menus, like fonts, but can't when it's a toggle).
But you can see which state is the default by long-pressing` [ ] Enable hyphenation`:
<kbd>![image](https://user-images.githubusercontent.com/24273478/85955308-dc855e80-b97d-11ea-8a2d-cae5b217574b.png)</kbd>

I guess you will see on your side that your default was `enabled`. Is that right?
You can just disable it there, and you won't have hyphenation enabled when later opening never-opened books.

(It's possible I missed the migration from the old default hyphenation setting to the new one - I don't really feel like checking if I did :)

**Comment by mikkelnl** [comment]
THANKS!

I was looking in the 'Style Tweaks' menu, did not know there also is a hyphenation setting under 'Typography rules'.

**Comment by poire-z** [comment]
The `Allow hyphenation on all text` style tweak actually just makes KOReader ignore publishers styles like `h1, h2 { hyphens: none; }`, that it would otherwise respect.

**Comment by charleshan** [comment]
Thanks for the tip!

Quick feedback: Long-pressing to an option to change the default is not very intuitive.

**Comment by Frenzie** [comment]
It is and it isn't. It's somewhat intuitive in the sense that long press generally serves as right click (context menu) on touch devices, and e.g. highlights also work along those lines. But that's the meaning of intuitive where you'll talking if you'll just randomly figure it out. If you think that away what matters more is how it works once you know about it.

**Comment by NiLuJe** [comment]
It's *explicitly* pointed out in the quickstart guide ;).

**Comment by charleshan** [comment]
> It's _explicitly_ pointed out in the quickstart guide ;).

You're right. I assumed that I can just figure things out as I go.
