### ISSUE TITLE
Ability to use default keyboard on pocketbook

### ISSUE THREAD

**Issue by xahon** [koreader/koreader#6328]
* KOReader version: 2020.06
* Device: PocketBook 740 pro

#### Issue
Currently, koreader uses its own implementation of keyboard that works kinda weird. It misses taps when you type quickly, I had difficulties with adding other keyboard layouts (Technically there are checked checkboxes, but "world" button didn't change the layout). I want an ability to switch to a default probook's keyboard. It has pros: doesn't miss taps (may be buffering in another thread or efficiently use touchpad events), can switch sources, has a numeric row, ...

**Comment by NiLuJe** [comment]
Okay, on *that* one, I can say that it's probably exceedingly unlikely to ever happen, and it might not even be technicaly feasible at all. ^^.

But, we don't have a PocketBook maintainer, so, please feel free to prove me wrong, PRs welcome ;).

**Comment by NiLuJe** [comment]
Feel free to shoot out a few detailed dedicated issues if you do have genuine issues with the stock virtual keyboard, though.

**Comment by poire-z** [comment]
Something you can try to have the keyboard a bit more responsive is to disable flashing key.
Uncheck `Gear > Screen > E-ink settings > Flash keyboard`
