### ISSUE TITLE
FR: MacOS Desktop Application

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#6331]
Has any work been done, or is there any interest in, a MacOS desktop application (rather than building/running the emulator)?

**Comment by NiLuJe** [comment]
Cocoa is pain. Swift is pain. macOS is pain.

But PRs welcome ;p.

**Comment by JasonInOttawa** [comment]
So no work's been done, and there might be some interest :)

I haven't done any Mac development, but I do have a Macbook. I'll see if I can't figure something out.

**Comment by NiLuJe** [comment]
If by "interest" you mean a negative amount of, sure?

**Comment by Frenzie** [comment]
Unless someone's done that in secret, what you see is what you get. I don't know what goes into MacOS apps? If you're lucky it'd be a lot like the AppImage:

https://github.com/koreader/koreader/blob/86db43a0527e94f1ebe2a124dae92f8fd3f70e6e/Makefile#L313-L348

https://github.com/koreader/koreader-base/blob/849231bf518a6b1457459b408b9ef04e36f44b83/Makefile.defs#L441-L445

Incidentally, does the build process also randomly blow up on real Mac or is that just GitHub Actions? I added https://github.com/koreader/koreader-base/blob/849231bf518a6b1457459b408b9ef04e36f44b83/.github/workflows/build.yml to prevent accidentally breaking the Mac build and it worked great… for a few weeks. Ever since Mac clang has been segfaulting on MuPDF without us having changed anything, see [here](https://github.com/koreader/koreader-base/runs/820936534).

**Comment by pazos** [comment]
> Has any work been done, or is there any interest in, a MacOS desktop application (rather than building/running the emulator)?

See https://github.com/koreader/koreader/issues/4375#issuecomment-444717730.

**Comment by JasonInOttawa** [comment]
Thank you everyone. If the procedure for building a Mac application bundle the ugly way works, would it be acceptable to add it as a build target

**Comment by NiLuJe** [comment]
Note that that'd still be building the emulator (i.e., SDL2). I got the impression you were after a truly native backend, which is a whole other can of worms.

**Comment by JasonInOttawa** [comment]
Thank you again. I use the emulator to read on a laptop when I haven't got the Kobo. I was hoping for an easier upgrade method and tidier setup than rebuilding and running the emulator. 

Is SDL sufficient, or would only going native be acceptable?

**Comment by Frenzie** [comment]
SDL is fine.

**Comment by pazos** [comment]
> SDL is fine.

Das ist super!

**Comment by JasonInOttawa** [comment]
I managed to get a working ugly Mac application bundle, and per Pazos's comment 4375 above I had to use install_name_tool to change the following libraries so they were loading shared libraries using the @executable_path variable:

libwrap-mupdf.so loading libmupdf.dylib
libkoreader-xtext.so loading libunibreak.3.dylib
libcrengine.dylib loading libunibreak.3.dylib
serialize.so loading libluacompat52.so

Once those were updated, koreader started fine and seemed to work.

I guess the next job would be to add macOS as a valid target to the kodev build script and various makefiles. That might take a while (since I'm very, very unfamiliar with how that works :) )

Thanks to all for your help,
Jason

**Comment by JasonInOttawa** [comment]
I do have a quick question - would it be possible to add flags somewhere so that those libraries are built with the proper location of the libraries they are loading, or will this have to be something done after they are built?

**Comment by pazos** [comment]
To be rellocatable (so it works in spite of location) you need to double check that every library is using a relative path to the rest of libraries using `otool -L` except system libraries and maybe sdl.

> I do have a quick question - would it be possible to add flags somewhere so that those libraries are built with the proper location of the libraries they are loading, or will this have to be something done after they are built?

Is a very good question. I don't have a good answer. If the executable is a proper binary then otool will do the work for you. Since here the executable is a shell script there's no way for otool to magically know which libs to bundle.

So you need to do it yourself, like in https://github.com/koreader/koreader-base/blob/ccf756fcb9a16a94f83bc202ead0382b00a4afb6/Makefile#L116-L121. But I don't know if there is a better way to do that!!!

**Comment by JasonInOttawa** [comment]
Thanks. I haven't tried adding the macOS biuld target yet - I've got a script that takes a built emulator and constructs the application bundle, and runs install_name_tool on the four libraries above. I wanted something fast and easy that would show me what a proper application looks like.

I'll look at adding the target to the makefile and either building the libraries so they have relative load locations, or (at least) running install_name_tool on all the libraries that have absolute load locations.

I also noticed that the application can't see anything in the koreader file browser in the "standard" folders under my home directory. I thought this had something to do with an application sandbox, but the funny thing is that I can see folders that I added. The permissions are different on those. EG

ls -ld Desktop (can't see any files in the koreader file browser)
drwx------@ 27 jason  staff  864  7 Jul 13:55 Desktop

ls -ld Calibre\ Library  (can see files in the koreader file browser)
drwxr-xr-x  3692 jason  staff  118144  7 Jul 22:24 Calibre Library

**Comment by pazos** [comment]
@JasonInOttawa if you update your changes (ie: the script) to a local branch of yours I could help a bit

**Comment by JasonInOttawa** [comment]
I'm a newbie - would that involve opening a PR and uploading the script?

**Comment by pazos** [comment]
> would that involve opening a PR and uploading the script?

You can submit a PR, or just push to your own branch and leave a link here. Also works if you paste the script here.

Submit a PR and push to your branch are both the same except for the last step. Both involve:

```bash
git checkout -b my_feature
git add my_files
git commit -m "my commit"
git push myrepo my_feature
```

**Comment by JasonInOttawa** [comment]
I think for now I'll just paste the script here. Please don't be horrified at the quality - I didn't know what an application bundle looks like and wanted a working one before making it good.

I set up an emulator build in my Documents folder and then run the script as follows:

~/build_koreader_app.sh ~/Documents/koreader x86_64-apple-darwin19.5.0-debug

I haven't look at the proper build process yet. I'd prefer to build the libraries specifying @executable_path directly, but failing that I'll look into automating using install_name_tool to fix them all. The four fixed in the script kept koreader from running - I haven't looked at any others yet.
[build_koreader_app.sh.txt](https://github.com/koreader/koreader/files/4893032/build_koreader_app.sh.txt)

**Comment by JasonInOttawa** [comment]
Here is the icns file
[koreader.icns.zip](https://github.com/koreader/koreader/files/4893044/koreader.icns.zip)

**Comment by pazos** [comment]
@JasonInOttawa: thank you!. Sadly the app is not relocatable yet. But this is a good step forward!!!

I will use your code as a template to add a new platform but leave the fine tweaking o-tooling to you. Hopefully you'll find it easier to follow the changes. It won't take me too much time. I promise :smile:

**Comment by JasonInOttawa** [comment]
Thank you! Once the target has been added, it'll be possible to do a 

kodev build macOS 

or similar, and get a Mac application?

**Comment by JasonInOttawa** [comment]
(platform, not target)

**Comment by pazos** [comment]
Yeah, with `./kodev release macos`

Give me a few minutes!.

**Comment by pazos** [comment]
@JasonInOttawa: done in #6361. Please move your shell scripts parts to platform/mac/do_mac_bundle.sh.

You need to change things in $(INSTALL_DIR)/bundle/Contents/Resources/libs. When the script finish the bundle will be renamed to KOReader-mac-$VERSION.app on top directory.

**Comment by JasonInOttawa** [comment]
Thank you! Just so I understand, I should look into adding calls to otool -L/look for hardcoded loading paths/call install_name_tool to make them relative to @executable_path at around line 37 of do_mac_bundle.sh. Does that sound right?

**Comment by pazos** [comment]
> Does that sound right?

Exactly.

Keep in mind that the application now should work as-is even if you move the app bundle elsewhere. That's because the hardcoded libraries are pointing to base/build/x86_64-apple-darwin... The way to check if the app is relocatable is to rename that folder (the one that doesn't end with -debug, the other is the emulator) with another name and try to open the app again.

**Comment by JasonInOttawa** [comment]
This works in my build script. I think we can put this in as line 37

`pushd "${INSTALL_DIR}/bundle/Contents/Resources"

# along with the libraries in libs, serialize.so in common also needs to be fixed
for directory in common libs; do
        directoryName=`basename $directory`
        echo Checking $directory
        pushd $directory
        for libToCheck in *.so *.dylib; do
                # there may be more than one library to fix, so get all of them and iterate
                libsToChange=`otool -L $libToCheck | grep "Users.*x86_64" | tr -s " " | cut -f1 -d" "`
                if [ -z "$libsToChange" ]; then
                        echo Nothing to do; skipping $libToCheck
                else
                        for libToChange in $libsToChange; do
                                fileNameOfLibToChange=`basename $libToChange`
                                if [ $libToCheck = $fileNameOfLibToChange ]; then
                                        echo Skipping recursive $libToChange $libToCheck
                                else
                                        echo Fixing $libToCheck $libToChange
                                        install_name_tool -change $libToChange @executable_path/$directoryName/$fileNameOfLibToChange $libToCheck
                                fi
                        done
                fi
        done
        popd
done

popd`

**Comment by JasonInOttawa** [comment]
Sorry, I though that would insert it as code. Please see attached
[fix_libs.txt](https://github.com/koreader/koreader/files/4893830/fix_libs.txt)

**Comment by JasonInOttawa** [comment]
That "skipping recursive" part is there because the dylibs seem to have a reference to themselves, and running install_name_tool -change does nothing. E.G.:

% otool -L libzyre.1.dylib
**libzyre.1.dylib:**
	/Users/jason/Documents/koreader/base/thirdparty/zyre/build/x86_64-apple-darwin19.5.0-debug/zyre-prefix/src/zyre-build/lib/**libzyre.1.dylib** (compatibility version 2.0.0, current version 2.0.0)

**Comment by NiLuJe** [comment]
IIRC, I had an explanation for that the last time I played w/ otool.

I, err, don't remember what it was right now, though ;D.

It may be buried in a comment somewhere, or in the last issue/PR we discussed this.

**Comment by pazos** [comment]
>  otool -L libzyre.1.dylib
libzyre.1.dylib:
/Users/jason/Documents/koreader/base/thirdparty/zyre/build/x86_64-apple-darwin19.5.0-debug/zyre-prefix/src/zyre-build/lib/libzyre.1.dylib (compatibility version 2.0.0, current version 2.0.0)

IIRC the first is the name of the library and the rest are the rpath of the dynamic libraries on which this library depends.
