### ISSUE TITLE
 Crash when logging in to Evernote（Yinxiang）

### ISSUE THREAD

**Issue by seacatwu** [koreader/koreader#6338]
* KOReader version:koreader-kobo-v2020.06-33-g86db43a_2020-06-28
* Device:kobo aura h2o

##### `crash.log` (if applicable)
        launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 06/30/20-21:59:40
 [*] Version: v2020.06-33-g86db43a_2020-06-28

ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
ffi.load: blitbuffer
FB: computed size: 3342336
FB: id           : mxc_epdc_fb
FB: smem_len     : 6684672
FB: line_length  : 1088
FB: xres         : 1080
FB: xres_virtual : 1088
FB: yres         : 1440
FB: yres_virtual : 3072
FB: bpp          : 8
06/30/20-21:59:40 INFO  initializing for device Kobo_dahlia
06/30/20-21:59:40 INFO  framebuffer resolution: {
    ["h"] = 1440,
    ["w"] = 1080
}
[ko-input] Forked off fake event generator(pid:14599).
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
PING 192.168.2.1 (192.168.2.1): 56 data bytes
64 bytes from 192.168.2.1: seq=0 ttl=64 time=1.586 ms

--- 192.168.2.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.586/1.586/1.586 ms
06/30/20-21:59:41 INFO  opening file /mnt/sd/文档/书籍/禅修/专注力 禅修10階释放心智潜能.epub
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/NotoSansSC-Regular.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/SourceHanSerifCN/SourceHanSerifCN-ExtraLight.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/SourceHanSerifCN/SourceHanSerifCN-Heavy.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/SourceHanSerifCN/SourceHanSerifCN-Light.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/SourceHanSerifCN/SourceHanSerifCN-Medium.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/SourceHanSerifCN/SourceHanSerifCN-Regular.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/SourceHanSerifCN/SourceHanSerifCN-SemiBold.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/YouYaSong_Regular.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/droid/DroidSansMono.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/freefont/FreeSans.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/freefont/FreeSerif.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSans-Bold.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSans-BoldItalic.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSans-Italic.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSans-Regular.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSansCJK-Regular.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSansCJKsc-Regular.otf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSerif-Bold.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSerif-BoldItalic.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSerif-Italic.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/noto/NotoSerif-Regular.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/仿宋.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/幼圆.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/思源宋体 正常.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/方正兰亭宋加粗修正.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/方正兰亭特黑长.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/方正华隶.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/方正大标宋.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/楷体.ttf>
06/30/20-21:59:41 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/汉仪楷体简.ttf>
06/30/20-21:59:42 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/黑体.ttf>
06/30/20-21:59:42 INFO  Loading plugins from directory: plugins
06/30/20-21:59:42 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
ffi.load: z
ffi.load: sqlite3
06/30/20-21:59:43 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
06/30/20-21:59:43 WARN  Error when loading plugins/storagestat.koplugin/_meta.lua cannot open plugins/storagestat.koplugin/_meta.lua: No such file or directory
06/30/20-21:59:43 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin calibre at plugins/calibre.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin profiles at plugins/profiles.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
06/30/20-21:59:43 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
./luajit: plugins/evernote.koplugin/main.lua:426: attempt to call method 'find' (a nil value)
stack traceback:
	plugins/evernote.koplugin/main.lua:426: in function 'doLogin'
	plugins/evernote.koplugin/main.lua:372: in function 'action'
	frontend/ui/uimanager.lua:812: in function '_checkTasks'
	frontend/ui/uimanager.lua:1132: in function 'handleInput'
	frontend/ui/uimanager.lua:1218: in function 'run'
	./reader.lua:298: in main chunk
	[C]: at 0x000140e1
!!!!
Uh oh, something went awry... (Crash n°1: 06/30/20 @ 22:00:14)
Running FW 4.8.11073 on Linux 2.6.35.3-850-gbc67621+ (#3032 PREEMPT Mon Jan 9 13:37:40 CST 2017)
Attempting to restart KOReader . . .
!!!!

**Comment by Frenzie** [comment]
An update with more logging (when debug logging is enabled) is about to hit master but unfortunately not quite yet.

https://github.com/koreader/koreader/blob/09c654c7ec78c20eed84ba97c5ea637e7bb5218d/plugins/evernote.koplugin/main.lua#L420-L432

It looks like `guid` is *something*, but not a string. That strikes me as oddly familiar… and it is: https://github.com/koreader/koreader/issues/4285#issuecomment-432340348

Closing this one as a duplicate.
