### ISSUE TITLE
Slightly malformed TOC not showing

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#6339]
* KOReader version: 09c654c
* Device: all

#### Issue
I noticed the TOC in my newspaper doesn't show anything, while it does in calibre.

Here's a scrambled copy: [NRC Handelsblad 2020-07-01 - NRC Handelsblad_scrambled.epub.zip](https://github.com/koreader/koreader/files/4858053/NRC.Handelsblad.2020-07-01.-.NRC.Handelsblad_scrambled.epub.zip) (remove .zip from the name)

It looks like it's not quite proper, but I suppose that's how things can be "in the wild."
```
$ epubcheck nrc_20200701.epub 
Validating using EPUB version 2.0.1 rules.
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(10,12): Error while parsing file: element "doctitle" not allowed anywhere; expected element "docTitle"
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(13,10): Error while parsing file: element "doctitle" not allowed anywhere; expected element "docTitle"
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(15,10): Error while parsing file: element "navmap" not allowed anywhere; expected element "docTitle"
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(20,12): Error while parsing file: element "navmap" not allowed anywhere; expected element "docTitle"
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(23,14): Error while parsing file: element "navmap" not allowed anywhere; expected element "docTitle"
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(28,13): Error while parsing file: element "navmap" not allowed anywhere; expected element "docTitle"
ERROR(RSC-005): nrc_20200701.epub/toc.ncx(31,15): Error while parsing file: element "navmap" not allowed anywhere; expected element "docTitle"
```

[NRC Handelsblad 2020-07-01 - NRC Handelsblad_scrambled.epub.zip](https://github.com/koreader/koreader/files/4858045/NRC.Handelsblad.2020-07-01.-.NRC.Handelsblad_scrambled.epub.zip)

**Comment by poire-z** [comment]
Its toc.ncx file has lowercased tag names:
```xml
<?xml version='1.0' encoding='utf-8'?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
 <head>
  <meta content="NRC Handelsblad 2020-07-01" name="dtb:uid"/>
  <meta content="1" name="dtb:depth"/>
  <meta content="0" name="dtb:totalPageCount"/>
  <meta content="0" name="dtb:maxPageNumber"/>
 </head>
 <doctitle>
  <text>
   FQA Oxybwotajum 2020-07-01
  </text>
 </doctitle>
 <navmap>
  <navpoint id="navpoint-1" playorder="1">
   <navlabel>
    <text>
     Ljyyqjtwcj
    </text>
   </navlabel>
   <content src="content/section-1.html">
   </content>
   <navpoint id="navpoint-2" playorder="2">
    <navlabel>
     <text>
```
while the code expects these tag names with some upperCase part, like all documentions show:
https://github.com/krisztianmukli/epub-boilerplate/wiki/The-toc.ncx-File
https://wiki.mobileread.com/wiki/NCX
```xml
   <docTitle>
       <text>Document Title</text>
   </docTitle>
   <navMap>
       <navPoint id="navPoint-1" playOrder="1">
           <navLabel>
               <text>Section with no subsection</text>
           </navLabel>
           <content src="text/content001.xhtml"/>
       </navPoint>
```
`navmap` vs `navMap`
So, https://github.com/koreader/crengine/blob/master/crengine/src/epubfmt.cpp#L1486 fails.
There's no support for xpath/xpointers to work with case insensitive element names - as its XML, and we don't expect to have to do it.

An option would be to use the lowercasing XML parser used for parsing XHTML - but that's a bit ugly and would need to lowercase all these xpaths in the code which would make it less explicite, showing what's really expected.
Or duplicate the detection with lowercased element names in:
https://github.com/koreader/crengine/blob/ff3640d75a5016b2493b6fde1adb64a4826eb0ad/crengine/src/epubfmt.cpp#L93-L112

Or ask your newspaper publisher to fix that :)

**Comment by Frenzie** [comment]
> Or ask your newspaper publisher to fix that :)

And it doesn't work in Nickel either. :-) I don't really want to spend money calling to the Netherlands (plus it's a lot easier to explain in text) but apparently they also do Whatsapp… O_o

calibre is using a case insensitive regex since https://github.com/kovidgoyal/calibre/commit/c2d0a57a4187bf32de5b669e922f1efc9c6c2907 a decade ago, but it's not quite clear to me if it's purposefully working around an issue like this or if it's a mistake that effectively *caused* this issue now in the future.
