### ISSUE TITLE
Formulas are not formatted

### ISSUE THREAD

**Issue by hasufell** [koreader/koreader#6346]
* KOReader version: KOReader 2020.06 "Mosaic"
* Device: android and pocketbook IP 3 pro

#### Issue

Multiline formulas are not formatted, but squashed into one line without indentation or newlines.

![Screenshot_20200704_145418_org koreader launcher](https://user-images.githubusercontent.com/1241845/86513028-35824600-be07-11ea-9d7c-97749734c231.jpg)

And here with pocketreader:

![Screenshot_20200704_145546_com obreey reader](https://user-images.githubusercontent.com/1241845/86513042-4fbc2400-be07-11ea-9624-80d4d0ec5abd.jpg)

**Comment by poire-z** [comment]
Select text from just before to just after the formula, `View HTML`, and post screenshots.

Possibly it's some MathML that we don't support and render fully inline.
Or it's some `<PRE>` / `white-space: pre` that we should render well, but fail for some reason ? (In that case, view Stylesheet and try to figure the styles involved).

(I've looked around a few times for a C/C++ library (or just code) that could provide support for parsing and drawing MathML, but I found none.)

**Comment by hasufell** [comment]
![Screenshot_20200704_151404_org koreader launcher](https://user-images.githubusercontent.com/1241845/86513266-0c62b500-be09-11ea-9dc3-01269a412e23.jpg)

**Comment by poire-z** [comment]
OK, we may have an issue in that `<code>` reste its white-space to normal, so resetting the `white-space: pre` that comes with `<pre>`.
All elements are by default `white-space: normal`, except a few like PRE.
I guess they should default to  `white-space: inherit`, so:
```html
<pre><code>some
stuff</code></pre>
```
stays on 2 lines.
While:
```html
<pre><code style="white-space: normal">some
stuff</code></pre>
```
would be on one line.

Anywy, dunno how feasible this will be, but you might solve your issue with a style tweak (via Book-specific style tweak) and add:
`pre * {white-space: pre}`
Even just this seems to work:
`pre * {white-space: inherit}`

**Comment by Frenzie** [comment]
@poire-z 
> (I've looked around a few times for a C/C++ library (or just code) that could provide support for parsing and drawing MathML, but I found none.)

For basic MathML display there have been CSS-based approaches for at least 15 years, culminating in https://www.w3.org/TR/mathml-for-css/ about a decade ago. (Scroll to the bottom for a sample stylesheet.)

See https://golem.ph.utexas.edu/~distler/blog/archives/001588.html for a slightly older version of that. Also see some of the concerns voice there of course. Perhaps "mostly right" is worse than "not at all".

**Comment by hasufell** [comment]
> Anywy, dunno how feasible this will be, but you might solve your issue with a style tweak (via Book-specific style tweak) and add

Trying that, but the book doesn't seem to finish opening now.

**Comment by poire-z** [comment]
> For basic MathML display there have been CSS-based approaches for at least 15 years, culminating in https://www.w3.org/TR/mathml-for-css/ about a decade ago. (Scroll to the bottom for a sample stylesheet.)

Wow, it's bad, but not that bad:

Without that stylesheet :
<kbd>![image](https://user-images.githubusercontent.com/24273478/86514804-cf9cbb00-be14-11ea-99fe-21ef9d995d19.png)</kbd>

With that stylesheet as a user styletweak (Firefox on the left, KOReader on the right):
<kbd>![image](https://user-images.githubusercontent.com/24273478/86514845-230f0900-be15-11ea-9a32-f3cdffe7ed6e.png)</kbd>

**Comment by poire-z** [comment]
> OK, we may have an issue in that `<code>` reste its white-space to normal, so resetting the white-space: pre that comes with `<pre>`.
All elements are by default white-space: normal, except a few like PRE.
I guess they should default to white-space: inherit, so:

Should be fixed with https://github.com/koreader/crengine/pull/353.

Also, the added support there for `background-image: url(data:image:base64...` will allow bring the little ear to the square root symbol (still bad, but well...):
<kbd>![image](https://user-images.githubusercontent.com/24273478/86537253-ef53e200-beed-11ea-8fb6-512fd9d92c3b.png)</kbd>

**Comment by poire-z** [comment]
In https://www.w3.org/TR/mathml-for-css/, there are some bits with a CSS property I can't find anything about:
```
msubsup, msup, mmultiscripts
	{margin-top:0.4ex;
	table-baseline:2;}
```
Any idea what `table-baseline:2` might mean ?
It looks like it's responsible for positionning superscripts, which we would somehow render as subscripts.

**Comment by Frenzie** [comment]
I'd overlooked that, but indeed I don't know it, and I can't seem to find that property in https://www.w3.org/TR/css-tables-3/ or https://www.w3.org/TR/CSS2/tables.html

Still, it has to be in an old draft or on a mailing list somewhere.

**Comment by poire-z** [comment]
> Any idea what table-baseline:2 might mean ?

I guess it means: take the baseline of the 2nd row as the baseline of the table.
Otherwise, if `display:inline-table`, the renderer would use the baseline of the 1st row, and if `display:inline-block`, the baseline of the last row's last line.
