### ISSUE TITLE
MacOS Build fails on crengine

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#6351]
* KOReader version: current
* Device: emulator on MacOS

#### Issue

Build fails with "implicit instantiation of undefined template" errors while building lvmemman.cpp.o

#### Steps to reproduce

Set up build environment per instructions:
jasonbenwell@Jasons-MacBook koreader % echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/opt/gettext/bin:/usr/bin:/bin:/usr/sbin:/sbin
jasonbenwell@Jasons-MacBook koreader % echo $MACOSX_DEPLOYMENT_TARGET
10.14

then run

git clone https://github.com/koreader/koreader.git
cd koreader && ./kodev fetch-thirdparty
kodev build

Results in this error:

[ 57%] Building CXX object CMakeFiles/crengine.dir/crengine/crengine/src/lvmemman.cpp.o
/Users/jasonbenwell/Documents/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:26: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strb...
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:209:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/jasonbenwell/Documents/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:57: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strb...
                                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:209:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/jasonbenwell/Documents/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:80: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
  ...errstr = std::string("FATAL ERROR #") + std::string(strbuff) + std::stri...
                                                                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:209:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/jasonbenwell/Documents/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:100: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
  ...ERROR #") + std::string(strbuff) + std::string(": ") + std::string(error...
                                                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:209:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
/Users/jasonbenwell/Documents/koreader/base/thirdparty/kpvcrlib/crengine/crengine/src/lvmemman.cpp:77:17: error: 
      implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string errstr = std::string("FATAL ERROR #") + std::string(strb...
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:209:32: note: 
      template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
5 errors generated.
make[4]: *** [CMakeFiles/crengine.dir/crengine/crengine/src/lvmemman.cpp.o] Error 1
make[3]: *** [CMakeFiles/crengine.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build/x86_64-apple-darwin19.5.0-debug/libs/libcrengine.dylib] Error 2
make: *** [all] Error 2

**Comment by NiLuJe** [comment]
On which macOS version, with which XCode version?

**Comment by NiLuJe** [comment]
Hmm.

```diff
diff --git a/crengine/src/lvmemman.cpp b/crengine/src/lvmemman.cpp
index 32bbf74c..8eb029ff 100644
--- a/crengine/src/lvmemman.cpp
+++ b/crengine/src/lvmemman.cpp
@@ -26,6 +26,7 @@
 
 #ifdef _DEBUG
 #include <stdexcept>
+#include <string>
 #endif
 
 static char file_to_remove_on_crash[2048] = "";
```

ought to fix it.

Or, in the mean time, building a *release* build ;).

**Comment by JasonInOttawa** [comment]
I'm building on macOS 10.15.6, Xcode 11.5. Adding that include above got past that error (thank you!).

**Comment by poire-z** [comment]
I would just remove the _DEBUG part of this thingy I picked :
https://github.com/koreader/crengine/commit/0f19c4ac09b7e3de412e6430c9cf42d6643b10fe#diff-23f19cbfde8c58d572f7ef107a508a7e

Because, except for:
```
crengine/qimagescale/qimagescale.cpp:        std::cerr << "qSmoothScaleImage: out of memory, returning null!" << std::endl;
crengine/qimagescale/qimagescale.cpp:        std::cerr << "qSmoothScaleImage: out of memory, returning null!" << std::endl;
```
nothing uses std:stuff (or is that insignificant?)

**Comment by rfog** [comment]
Patch works for me as well (I applied it manually, edited the file and add the include).
