### ISSUE TITLE
[bug] 'Scratchy' looking font rendering on linux {Ubuntu 18.04 app image}

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6352]
* KOReader version: 2020 - 06 
* Device: Ubuntu 18.04 laptop

#### Issue
Here's what font rendering looks like in chrome.  Nice and crisp.
![Screenshot from 2020-07-07 12-11-17](https://user-images.githubusercontent.com/556667/86820364-8f288180-c04e-11ea-94c5-7051da59c236.png)

Here's what it looks like in koreader:  jaggedy and scratchy looking.  Ubuntu Mono is the font pictured and is the default font on Ubuntu 18.04 and looks pretty nice actually.  I have my terminal set to use it. 
![Screenshot from 2020-07-07 12-07-59](https://user-images.githubusercontent.com/556667/86820405-9c457080-c04e-11ea-8875-a77ee1ec25a0.png)

#### Steps to reproduce
Open Koreader; select system fonts.  Pick really any font, even built in ones, it looks scratchy.

**Comment by arooni** [comment]
Update:  I think high contrast values could have been causing this.  This is what it looks like at the default level of contrast.

![image](https://user-images.githubusercontent.com/556667/86820673-fe9e7100-c04e-11ea-938c-13dc61a568da.png)

**Comment by NiLuJe** [comment]
Yup, that's blow out contrast on Grayscale font rendering.

(I'm fairly sure the emulator doesn't do LCD filtering and/or subpixel rendering).

**Comment by pazos** [comment]
@NiLuJe: indeed gamma can be adapted for non-eink devices. I can't think a single reason to use a gamma > 1.0 in a lcd device.

**Comment by NiLuJe** [comment]
To expand a bit on my previous comment, I'd only bother doing it "right" on Android for non-eInk devices, but it's actually not a great idea, because phones have notoriously weird subpixel layouts (think OLED or weird fancy new-ish tech), so assuming horizontal RGB like on most monitors would probably only make it worse ;)).

**Comment by poire-z** [comment]
> I can't think a single reason to use a gamma > 1.0 in a lcd device.

I haven't changed gamma on my phone, but trying it just now, it looks ok, and might help with some thin fonts.
It might not look good when you inspect it with a magnifier - but it might just help reading the casual reader, or those with bad eyesight (I think it could even be useful on an AndroidTV where you don't notice the pixel quality from far away.)
So please, just let quality-conscious people not use Gamma - but don't kill its availability for the other people :)

**Comment by pazos** [comment]
To be fair I was talking about my desktop computer, not my android phone. On my phone higher gamma values look good, specially compared to my desktop computer. I have no idea how it will look on a 4k display.

**Comment by Frenzie** [comment]
@pazos Looks like a somewhat janky 300 DPI scan at higher values. Not great, but not bad. At a moderate value like 1.9 it looks perfectly fine.
