### ISSUE TITLE
FR: Support hardware keyboards to add/edit highlights in linux builds of Koreader (especially Ubuntu 18.04)

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#6353]
**Does your feature request involve difficulty completing a task? Please describe.**
Right now in order to add some notes I must use the software keyboard despite having a full sized keyboard that supports quick text entry.  

**Describe the solution you'd like**
Allow me to add/edit notes with my built-in keyboard.  Bonus points for bluetooth keyboard + android builds.  Separate issue though.  

**Describe alternatives you've considered**
1) Be sad and not make meaningful notes that could change the trajectory of my life.  
2) Move the mouse to use the virtual keyboard instead

**Additional context**
Nope.

**Comment by pazos** [comment]
Duplicate #5902
