### ISSUE TITLE
Emulator: link cache folder error

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader#6357]
* Device: Emulator

If i delete the cache by pressing `Developer options > Clear cache/ and cr3cache/ ?`
then try to run the emulator via `./kodev run`
I get an error
```
[*] create symlink instead of copying files in development mode
cd koreader-emulator-x86_64-pc-linux-gnu-debug/koreader && \
	ln -sf ../../base/build/x86_64-pc-linux-gnu-debug/* .
ln: ./cache: cannot overwrite directory
make: *** [Makefile:77: all] Error 1
```

caused by:
https://github.com/koreader/koreader/blob/580b38e7754ce95ef98a404d030e280b18707beb/frontend/apps/filemanager/filemanagermenu.lua#L252-L255

the code remakes the cache directory as a folder not a link so when the makefile tries to link it fails.

https://github.com/koreader/koreader/blob/580b38e7754ce95ef98a404d030e280b18707beb/Makefile#L84

**Comment by Frenzie** [comment]
Probably just remove the symlink from the Makefile. The code creates the cache directory if it's not there anyway.

**Comment by yparitcher** [comment]
> Probably just remove the symlink from the Makefile. The code creates the cache directory if it's not there anyway.

the makefile is linking all the directories in the base build for use by koreader

**Comment by Frenzie** [comment]
Tbh I've considered it a non-issue for half a decade because that which could be called a workaround (using my FM) is actually easier than bothering going all the way for that menu. ^_^

Anyhow, I think it'd be easier to exclude the cache (is something like `[!c]*` the appropriate syntax here?) but if you prefer you could also write a purgeDirContent or something, assuming it doesn't already exist.

**Comment by pazos** [comment]
purgeDIr won't be called because cachedir is a link, not a directory. But lfs.mkdir is called without checking the attributes. Maybe something like:

```lua
local type = lfs.attributes(cachedir, "mode") 
 if type == "directory" then 
     purgeDir(cachedir)
     lfs.mkdir(cachedir) 
elseif type == "link" then
    -- remove contents of cachedir recursively
end
```
