### ISSUE TITLE
Crash on favorite long press

### ISSUE THREAD

**Issue by ptrm** [koreader/koreader#6365]
* KOReader version: 2020.06-40-g580b38e_2020-07-05 (edit: the issue has been present for around a month, though)
* Device: Kobo Forma, Clara HD

#### Issue
Long pressing favorites entry results in a crash. Both on scripts and regular epubs, though crash log refers to some script check (below).

#### Steps to reproduce
Add a favorite
Long press it

##### `crash.log` (if applicable)
![20200709_053525](https://user-images.githubusercontent.com/366258/86994418-99f62a00-c1a6-11ea-910c-20a6f540fa2b.jpg)

**Comment by poire-z** [comment]
The change from `util.isAllowedScript()` to `Device:canExecuteScript()` with #6288 done for filemanager.lua has been forgotten for filemanagercollection.lua.
There are also references to util.isAllowedScript in comments in frontend/document/credocument.lua and frontend/util.lua.
