### ISSUE TITLE
PocketBook: News download and Wallabag not working since 201904

### ISSUE THREAD

**Issue by mbab** [koreader/koreader#6369]
* KOReader version: > 201904
* Device: PB630

#### Issue
Apart from issues with WIFI turn on/off etc, version 201904 is last from which I can download RSS and Wallabag articles.

#### Steps to reproduce
Turn on WIFI from PocketBook Main screen:
run Koreader News Download
after some information about processing is displayed return to PocketBook main screen occur. 

##### `crash.log` 201905
[crash.log](https://github.com/koreader/koreader/files/4906692/crash.log)

##### `crash.log` 202006
[crash.log](https://github.com/koreader/koreader/files/4906694/crash.log)

**Comment by Frenzie** [comment]
2019.04 you say? That brings up https://github.com/koreader/koreader/compare/v2019.04...v2019.05 Given the timeframe I don't really see anything that looks potentially suspicious at a glance other than a few OpenSSL updates.
```
Illegal instruction
```

**Comment by NiLuJe** [comment]
Probably InkView pulling up crap screwing things up for us once again ;).

**Comment by rjd22** [comment]
Since this seems to be working now I'm closing this. If you have any trouble please tell me.
