### ISSUE TITLE
Version of "PDF_Standard" being used in latest Release?

### ISSUE THREAD

**Issue by JagdishKumar1970** [koreader/koreader#6373]
Latest: 2.0;
Source:
https://en.m.wikipedia.org/wiki/PDF

**Comment by Frenzie** [comment]
We're currently using version 1.13 of MuPDF, see https://mupdf.com/release_history.html for more information.

**Comment by JagdishKumar1970** [comment]
> We're currently using version 1.13 of MuPDF, see https://mupdf.com/release_history.html for more information.

May I ask when will KOR updated with PDF-2.0?

Thankyou

**Comment by Frenzie** [comment]
All versions up to and including PDF 2.0 are supported. It's not quite clear to me what you're asking. I assume you're missing some concrete feature?

**Comment by JagdishKumar1970** [comment]
> All versions up to and including PDF 2.0 are supported by the MuPDF library. It's not quite clear to me what you're asking. I assume you're missing a specific feature?

Sorry for the complicated use of the English Language, but you answered my question. 
Thankyou
