### ISSUE TITLE
Question: File manager - numeric collator implementation ideas

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#6374]
Current result when sorting using "plain" string comparison:
```
AAA 1
AAA 10
AAA 2
```
Expected result when using numeric collator:
```
AAA 1
AAA 2
AAA 10
```

I'm not sure if it's a good idea, but my idea to implement would be something like this:
Strip both strings of numbers and compare them. If they are different, then fallback to "plain" string comparison(`strcoll(a, b)`), otherwise get numbers from the string and compare them.
```lua
if a.name:gsub("%d", "") == a.name:gsub("%d", "") then
    -- just draft, it would need additional checks in case there are no numbers in the text
    return tonumber(a.name:match("%d+")) < tonumber(b.name:match("%d+")
else
    return self.strcoll(a.name, b.name)
end
```
This works for my purposes, but it would fail on something like this
```
AAA 1 -- after stripping numbers we get AAA
AAA 2
AA1A 10 -- after stripping numbers we get AAA too
```
Another idea would be to iterate over both strings at the same time, until we find number/difference. Are both of this viable options? My concern is mostly about performance and supporting decimal numbers. Alternatively I was thinking of adding leading zeros to filenames when comparing them, but that's more of a hack. I'd be grateful for any input.

**Comment by Frenzie** [comment]
See http://notebook.kulchenko.com/algorithms/alphanumeric-natural-sorting-for-humans-in-lua

**Comment by NiLuJe** [comment]
See also `man 3  strverscmp` ;).
