### ISSUE TITLE
A new "Minimal-Edition" with Removal of Gesture and Plug-in System:

### ISSUE THREAD

**Issue by JagdishKumar1970** [koreader/koreader#6375]
Hello,
I'm a non-Programmer currently using:
org.koreader.launcher(v2020.05 from F-Droid.org Repository)@Android-7.1.2;

I request the respected devs to build and maintain a separate 'Minimal-Edition' for KOReader which:
1: Remove ALL the gestures except Left, Righ, Up, Down Screen Tap which trigger page-up/-down and Options;
2: Remove the Plugin System/Framework Completely;
3: Follow Standard Android System APIs for Rotation and all other functions/features except Screen-timeout(because it is embedded deep in System Settings and not as straightforward as brightness from qs panel).

Where, Points 1 and 2 would reduce Package Size and 3 will reduce unneeded use of system sensors which will save Battery, as I found there was no way to switch off the Auto Screen_Rotation which was useless for me. 

I noticed that KOR used 2% battery/hour, which impressed me deeply.

Thank you, for atleast reading till here and Please Comment the reason about: "Why not?"

**Comment by Frenzie** [comment]
> Where, Points 1 and 2 would reduce Package Size

The difference would only be a few kilobytes. Size comes from libraries and fonts. I tried to get rid of most of the fonts but unfortunately Android built-in fonts are all over the place, even though we literally depend on some of the same Noto fonts. A "you'll probably come across broken characters" edition is the only thing that would cut the size and you don't want that. ;-)

> 3 will reduce unneeded use of system sensors which will save Battery, as I found there was no way to switch off the Auto Screen_Rotation which was useless for me.

I'm not sure what you're referring to. The program doesn't waste battery listening to rotation events independently from the system. In the version you're using it can go upside down as controlled entirely by the system; in the next stable it'll be able to do that in any direction. But again, only if you enable "autorotate."

**Comment by JagdishKumar1970** [comment]
> > Where, Points 1 and 2 would reduce Package Size
> 
> The difference would only be a few kilobytes. Size comes from libraries and fonts. I tried to get rid of most of the fonts but unfortunately Android built-in fonts are all over the place, even though we literally depend on some of the same Noto fonts. A "you'll probably come across broken characters" edition is the only thing that would cut the size and you don't want that. ;-)
> 
> > 3 will reduce unneeded use of system sensors which will save Battery, as I found there was no way to switch off the Auto Screen_Rotation which was useless for me.
> 
> I'm not sure what you're referring to. The program doesn't waste battery listening to rotation events independently from the system. In the version you're using it can go upside down as controlled entirely by the system; in the next stable it'll be able to do that in any direction. But again, only if you enable "autorotate."

I understood that, but may I ask for:
1: a "Gesture On/Off" to switch ALL the gestures except Left, Righ, Up, Down Screen Tap which trigger page-up/-down and Options;

2: a single "Plug-in(s) On/Off" switch to turn_off Plugin System/Framework;

**Comment by pazos** [comment]
> I noticed that KOR used 2% battery/hour, which impressed me deeply.

It can be too much or too litle. I don't know because you gave no enough info. I would asume you're running on a LCD device, on the foreground for an entire hour and go to battery stats and find that KOReader consumes a 2% (without accounting screen on  + wifi). Is still not enough info:

What you were doing?. Some things, like pdf reflow, opening epubs for the first time or changing font size and other settings on epub are CPU intensive. Jumping between wikipedia articles is not that CPU intensive but cpu time will be accounted under KOReader, not SystemUI.
If you really want to know if KOReader wastes battery on your device you need to compare it with other apps doing the same tasks. Offline? -> it should behave almost exactly Coolreader for epubs and almost exactly MuPDF for pdfs without reflow. Online? -> it should behave like any web browser based on Chromium (or any other that implements network logic in C++)

But if you reaaaaally want an optimized app and you're the kind of person that wants to change a million times font size or margins I would suggest other programs, like MoonReader, because KOReader (or Coolreader, FBReader, AlReader?) apply changes on the entire document, and that drains a bit of current.

Also, for the sake of completeness, KOReader drawing is CPU bound, and will drains a bit more than an OpenGLES implementation (I think you won't notice under normal usage). Anyways you can compare it to ReadEra and see if it behaves properly on Readera (for offline reading!)

**Comment by pazos** [comment]
> I understood that, but may I ask for:

> 1: a "Gesture On/Off" to switch ALL the gestures except Left, Righ, Up, Down Screen Tap which trigger page-up/-down and Options;

Not possible. You can disable multigestures or disable the touchscreen completely. But you can't disable the touchscreen partially. Anyways this won't reduce battery drain.

2: a single "Plug-in(s) On/Off" switch to turn_off Plugin System/Framework;

Not really useful. If you want you can disable all of them one by one.  Anyways this won't reduce battery drain.

**Comment by pazos** [comment]
Labeled out of date:

Battery drain on the background was reduced by disabling the background runner (which prevented Android's Doze)
Screen orientation is now locked to native orientation. Surface rotations are available by user request.

**Comment by JagdishKumar1970** [comment]
> > I noticed that KOR used 2% battery/hour, which impressed me deeply.
> 
> It can be too much or too litle. I don't know because you gave no enough info. I would asume you're running on a LCD device, on the foreground for an entire hour and go to battery stats and find that KOReader consumes a 2% (without accounting screen on + wifi). Is still not enough info:
> 
> What you were doing?. Some things, like pdf reflow, opening epubs for the first time or changing font size and other settings on epub are CPU intensive. Jumping between wikipedia articles is not that CPU intensive but cpu time will be accounted under KOReader, not SystemUI.
> If you really want to know if KOReader wastes battery on your device you need to compare it with other apps doing the same tasks. Offline? -> it should behave almost exactly Coolreader for epubs and almost exactly MuPDF for pdfs without reflow. Online? -> it should behave like any web browser based on Chromium (or any other that implements network logic in C++)
> 
> But if you reaaaaally want an optimized app and you're the kind of person that wants to change a million times font size or margins I would suggest other programs, like MoonReader, because KOReader (or Coolreader, FBReader, AlReader?) apply changes on the entire document, and that drains a bit of current.
> 
> Also, for the sake of completeness, KOReader drawing is CPU bound, and will drains a bit more than an OpenGLES implementation (I think you won't notice under normal usage). Anyways you can compare it to ReadEra and see if it behaves properly on Readera (for offline reading!)

The battery stat was a Complement and not a Comment, btw I used a completely offline wifi-only Tablet with TFT-LCD Display and KOR set to:
1: All plug-ins disabled;
2: Night mode :'On';
3: Auto-Rotate: Off in the Android Settings(but KOR was still able to use it);
4: Swipe and multi gesture: Off;

**Comment by yparitcher** [comment]
> > 1: a "Gesture On/Off" to switch ALL the gestures except Left, Righ, Up, Down Screen Tap which trigger page-up/-down and Options;
> 
> Not possible. You can disable multigestures or disable the touchscreen completely. But you can't disable the touchscreen partially. Anyways this won't reduce battery drain.

when i finish my work on making the gesture manager into a separate plugin powered by `Dispatcher` this might be possible, but that wont be for a month or 2 :)
