### ISSUE TITLE
Perception expander settings periodic resets

### ISSUE THREAD

**Issue by Anuvadak** [koreader/koreader#6376]
* KOReader version: 2020.06 Mosaic
* Device: Kindle KT3
I use perception expander since the last version of KOreader is presented. I found optimal settings for me and set it up to train my speed reading skill. So, periodically, KOreader resets custom settings to default (or some else?) ones. It happens approximately every 40-60 pages, sometimes more frequent.

These are my settings:
Line thickness: 1.5
Margin from edges: 0.275
Line intensity: 10

The values after reset I'll write a bit later

**Comment by Anuvadak** [comment]
Yep, it's happened again. Why is this happening??? The settings are so close but it's breaking my mind when I slow down reading speed and only after few pages I notice WHY. Terrible bug :(

Settings after reset:
Line thickness: 1.5
Margin from edges: 0.305
Line intensity: 10

Which additional information should I provide to dear developers?

**Comment by pazos** [comment]
> Which additional information should I provide to dear developers?

contents of `koreader/settings/perception_expander.lua` and a Yes/No to the question: does the file contain the settings you like?. If the answer is No then edit the file directly and put there your settings. Save.

Now, can you reproduce the issue?.

**Comment by yparitcher** [comment]
perception expander has a "feature" that it increases the margins every X pages (100 by default) by 0.03
This can be changed in the 4th box in the settings, set it to a very high number for example 100000 and it wont change the margins on you.
![Reader_2020-07-14_213307](https://user-images.githubusercontent.com/38916402/87493467-ddbfb800-c61a-11ea-90d1-9c9bbfe70d1e.png)

**Comment by NiLuJe** [comment]
Low-hanging fruit for interested parties: disable when set to 0?
