### ISSUE TITLE
Can't access internal file system

### ISSUE THREAD

**Issue by toiiggww** [koreader/koreader#6379]
* KOReader version: 2020.06
* Device:Sony z5p

#### Issue
Can't get sub folder for internal storage .
![Screenshot_20200716-061338](https://user-images.githubusercontent.com/1251700/87608039-75afc580-c731-11ea-8b89-13d38d77a4c6.png)

**Comment by pazos** [comment]
Press the home button. It will return you to HOME.

The issue itself is not fixable but there are a few workarounds:

- validate that the path is inside the sandbox before chdir using Device.isValidPath/android.isPathInsideSandbox
- validate that the path is readable before chdir.

The first option is more restrictive and would prevent directory poping even on devices without that restriction. I remember @poire-z suggested the second option somewhere, but I cannot find the conversation.

**Comment by poire-z** [comment]
> I remember @poire-z suggested the second option somewhere, but I cannot find the conversation.

Might have been in https://github.com/koreader/koreader/issues/4885#issuecomment-494314073 : 

> when reaching an unreadable directory, and then just take an appropriate decision:
    [...]
    go down, just showing an empty list, or a fake item "directory unreadable", but still the "go up" item

**Comment by toiiggww** [comment]
This issue not exists in some previesion , maybe can review some code in history code to fix it.

**Comment by pazos** [comment]
Hi @toiiggww. We bumped the API from 14 to 28 and changed a lot of things. We aren't going to revert that!. Could you please explain what's the issue here?

**Comment by toiiggww** [comment]
My android version is 7.1.1, maybe that is the reason.

**Comment by pazos** [comment]
Yeah, on some phones there are no restrictions. But for most devices what happens is:

- You have RW permissions on the primary storage (that's `/storage/emulated/0` if you primary storage is the internal partition and `/storage/emulated/UUID` if your primary storage is an external SD card).
- If you navigate to the top dir of your primary partition you won't see any directory. You need to press the home button to go back to your home.
- You can still access files outside the primary partition but **not from KOReader**. Use your favorite FM, go to somewhere outside your primary partition and open a file with the program. It will open fine. If you press the button to go to the FM you will be at the right directory. Remember that you don't have writable permissions outside the primary partition.
- You can import files from any provider including, but not limited to, any storage providers. You can import documents only inside the primary storage by clicking the `+` button on the FM and clicking `import here`. You'll be prompted with a file picker and you can choose one or more supported files. These files will be copied to the current directory.


The workflow I would recommend would be:
- setup the primary storage as you like. If you internal partition is tiny and you store most of your documents on a sdcard it could make sense to setup the primary storage as the sdcard. (This happens on android settings, not inside KOReader).
- use an external program to open files outside the primary partition without importing them.
- use import to *ejem, import* files from other content providers, like Dropbox, Google Drive or any other cloud provider.

**Comment by toiiggww** [comment]
I've use `+` button saved a internal storage path, and can use it as a entry to explorer files.

**Comment by poire-z** [comment]
Original issue fixed by 1st commit of #6593.
