### ISSUE TITLE
Change Text and BG color based on User specified HEX Code?:

### ISSUE THREAD

**Issue by JagdishKumar1970** [koreader/koreader#6382]
SumatraPDF(2006)  Supports this:  
https://github.com/sumatrapdfreader/sumatrapdf

@pazos 
@Frenzie

**Comment by pazos** [comment]
Duplicate of #3871

Background is something that can be applied to reflowable documents or pdf without their own background. Most pdfs have a background - usually white - and seems not possible to change that. What's possible is to setup a texture overlay that tints both the background and the text/images.

**Comment by Frenzie** [comment]
There does seem to be something like https://acidwords.com/posts/2016-07-26-hacking-mupdf-custom-background-colors.html
