### ISSUE TITLE
Can't connect PC without KSM

### ISSUE THREAD

**Issue by vinhphucng25** [koreader/koreader#6384]
Dear All,

I am using Kobo Libra H2O with latest firmware so that I'm not prefer to install KSM (Kobo Start Menu) and KoReader doesn't have any option to connect USB to PC so that I have to restart to Nickel Menu to connect PC.

Can anyone add the option USB like KSM to KoReader because KoReader is the best option for my Kobo.

Thank You and Regards.

**Comment by pazos** [comment]
See https://github.com/koreader/koreader/issues/2597, in particular conclusions: https://github.com/koreader/koreader/issues/2597#issuecomment-576041788

**Comment by NiLuJe** [comment]
Just exit to Nickel? It'll take something like ~10s to boot, as it's not a cold start.
