### ISSUE TITLE
Two fingered pan gesture attempt results in frontlight changes, page change and rotate.

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#640]
With the last nightlies from at least build 202, I find on my Kobo Aura that attempts to change the frontlight setting will also result quite often in a screen rotation or a change of page.

I thought chrox got rid of this in #634. What has changed since then? Could the addition of the two-fingered swipe #638 be responsible?

Anyway, how can the two-fingered pan gesture detection be made more robust to exclude page turning and rotation?

**Comment by Markismus** [comment]
As I don't have the kobo Aura anymore, I can't check whether this is still an issue. Feel free to reopen if the issue remains on the PW1.

**Comment by arooni** [comment]
can anyone else get this working on the paperwhite 4 (2018)?  not sure how i'm supposed to make this gesture.  i can get all other gestures to work.
