### ISSUE TITLE
Status bar is gone every time I relaunch the app

### ISSUE THREAD

**Issue by laphir** [koreader/koreader#6407]
* KOReader version: v2020.06
* Device: Onyx Boox Poke Pro

Issue: 
Whenever I relaunch the app, it launches without a status bar.

Is there a way to assign a gesture for toggling the status bar?
Or could you remember previous state of status bar and apply it when the app launched again?

**Comment by BeanSlinger** [comment]
The answer your are looking for is in the wiki:
"The easiest way to set a global default setting is from within the KOReader application — long press the option you wish to make the default. KOReader will ask you to confirm the new default."
see here https://github.com/koreader/koreader/wiki/Change-defaults

**Comment by pazos** [comment]
@laphir: If you're talking about the status bar of the android apps then nope, we're a fullscreen app.
