### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by user655362020** [koreader/koreader#6414]
* KOReader version: 2020.06
* Device: Android (Touchwiz)

#### Issue
Android is locked to landscape orientation (launcher, lockscreen, etc). Upon turning off the screen and then turning it on Koreader displays black screen.

When rotation is set to portrait mode black screen does not occur. Basically it happens if I turn off the screen when the lockscreen is in landscape mode.

#### Steps to reproduce
Lock the rotation of lockscreen/launcher to landscape mode.
Open book in koreader (Koreader orientation setting does not matter)
Turn off the screen. Then turn it on. 
Black screen in koreader.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/4958290/crash.log)

**Comment by pazos** [comment]
Thank you, this is a very good bug report. 👍 

The issue happens here:

```
Config changes=480 {0 1.0 showBtnBg = 0 ?mcc?mnc [en_US] ldltr sw768dp w1024dp h744dp 160dpi xlrg land finger -keyb/v/h -nav/h s.130}
07-22 12:11:40.670 16350 16369 I KOReader: Engine thread destroy requested!
07-22 12:11:40.670 16350 16369 W KOReader:  got error waiting for events: ffi/input_android.lua:168: application forced to quit
```

As you can see there is a configuration change that we didn't handle. That would certainly crash the application. What I don't know is the specific change that happened as we cover most of relevant ones. ❓ 

Anyways, all configuration changes are in https://developer.android.com/guide/topics/manifest/activity-element#config. I think it should be safe to "handle" all of them. 

There are also listed in https://docs.microsoft.com/en-us/dotnet/api/android.content.pm.configchanges?view=xamarin-android-sdk-9, which includes one undocumented by android: colorMode.

**Comment by pazos** [comment]
@user655362020: here's a build that handles all possible configuration changes ->  https://www.dropbox.com/s/ci1mh4nqweh3mw7/koreader-arm-configChanges.apk?dl=0

Could you test it and see if that fixes your issue? Thanks

If you want to test you'll need to remove the installed application before install this one as signatures don't match.

**Comment by user655362020** [comment]
Yes. It fixes it. Thanks. 😃
