### ISSUE TITLE
Rotation blues

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6420]
* KOReader version: 2020.07.1
* Device: Kobo Forma

#### Issue

KOReader doesn't remember the default rotation I set during a reading session (I prefer 90 degrees clockwise). When I exit KOReader and then load it again, the rotation has been reset to 0 degrees.

Second problem: I cant set a rotation different from the default one for specific files. For example I like to read my poetry ebooks in "portrait" (0 degrees rotation) and my novels in "landscape" (90 degrees clockwise rotation) with 2 columns. But each time I set a rotation, this rotation is then being used for all books I load afterwards.

Third problem: I have my footer alignment set to right align, but when I manually set the rotation from 0 degrees to 90 degrees clockwise, the footer at the right side of the screen passes the right border of the screen.

#### Steps to reproduce

1) Start KOReader. The ebook is presented in 0 degrees rotation, the footer has been right aligned without problems.
2) From the bottom menu select 90 degrees clockwise rotation. Now my right aligned footer passes the right side of the screen, so de facto is truncated.
3) From the bottom menu long press on 90 degrees clockwise to make this the default setting and confirm that you want it to be the default setting.
3) From the top menu (Settings > Screen > Rotate) select "Lock auto rotation to current orientation" and "Keep current rotation across views".
4) Exit KOReader and then start it again. Rotation has been reset to 0 degrees, so default setting of 90 degrees clockwise has been ignored.

**Comment by smartscripts-nl** [comment]
I just found out that when I uncheck "Keep current rotation across views", KOReader obeys the default rotation and can use a different rotation for specific files. Also the problem with the right aligned footer doesn't occur in this configuration.

However, when I try to set the rotation in the filemanager also to 90 degrees clockwise and then try to return to the ebook I am reading, this setting will not be saved. The next time I load the filemanager during the same session, it has been reverted to 0 degrees rotation. Ergo: It appears not to be possible to save different default rotations for the ebook reader and the file manager?

**Comment by NiLuJe** [comment]
"Keep current rotation" works both ways, it's designed to never rotate on its own, no matter the saved settings. You choose a rotation, and it sticks, no matter the settings.

(Also, it *will* stomp on document settings, as in, that rotation will be remembered for that doc on exit, but *NOT* on FM settings).

Setting a default FM rotation is possible, and it involves... setting a default ;p. (i.e., long-press on the chosen rota in the Rotation menu while in the FM).

**Comment by NiLuJe** [comment]
The footer thing is another matter entirely, though.

**Comment by smartscripts-nl** [comment]
Ah, thanks for the tip of setting the default rotation for FM! I should have thought about that...

**Comment by yparitcher** [comment]
> (Also, it currently _will_ stomp on document settings, as in, that rotation will be remembered for that doc on exit, but _NOT_ on FM settings. Should I fix that, @yparitcher (as in, never stomp on settings w/ sticky_rota)? I don't particularly care myself, but it feels slightly wrong, and the discrepancy in behavior vs. the FM settings is annoying).

Please do, my original implementation honored the doc settings over "Keep current rotation" so it didn't have this issue. but we definitely should not overwrite the doc setting based on a sticky rota.

**Comment by NiLuJe** [comment]
@smartscripts-nl: I can't actually replicate the status bar thingy.

Are you sure you checked on 2020.07<b>.1</b>?

What are your status bar settings, exactly?

**Comment by smartscripts-nl** [comment]
I have modified readerfooter.lua of my KOReader installation heavily. It might be that that causes the alignment issue.

I'll install the unmodified version later this day and let you know if I still encounter this problem after that.

**Comment by smartscripts-nl** [comment]
OK, I can confirm that the original readerfooter.lua doesn't have the truncation problem for right aligned footers. So it must be caused by my modifications. But because I now have set a default orientation I don't encounter this problem: it only occurs when I go from zero to 90 degrees rotation in a document.

**Comment by yparitcher** [comment]
Fixed in #6423
