### ISSUE TITLE
can't access to internet / connect to dropbox / check update

### ISSUE THREAD

**Issue by cramoisi** [koreader/koreader#6422]
* KOReader version: 202007.1
* Device: Kobo Libra

#### Issue
With wifi off, Cloud storage, selecting dropbox account, KOReader asks me to turn on wifi : YES (everything went ok, checking the wifi status shows it ok); select the dropbox account again : the  line stays selected for ten seconds then KOReader ask me if "I want to turn on the wifi" again (the wifi was on from the start)...

Same if I do Burger > Check for update

But Network info's Gateway ping is successful.

Any idea ?

**Comment by cramoisi** [comment]
Soooo, a big reboot did the trick (but not a koreader reboot). humpf.

**Comment by Galunid** [comment]
Sidenote, it's a problem I have on Kobo Clara HD. Nickel(Kobo's default software) kept connecting and disconnecting, this isn't KOReader's fault.
