### ISSUE TITLE
can any one  point out how to develop the koreader

### ISSUE THREAD

**Issue by zhujian578423315** [koreader/koreader#6427]
Can any one  point out how to develop the koreader for me?
full documentation can be provided is so great.
which I want to get is `framework，main technology，importent tools`, etc... 
**few key words can be helpful**.
Best wishes.

**Comment by Frenzie** [comment]
What is it that you're missing in the documentation?

https://github.com/koreader/koreader/blob/master/doc/Building.md

**Comment by zhujian578423315** [comment]
> What is it that you're missing in the documentation?
> 
> 
> 
> https://github.com/koreader/koreader/blob/master/doc/Building.md

Thanks for your replay.
the build environment works fine in my macbook. 
can you tell me how to get and compile the source of the backend part

**Comment by Frenzie** [comment]
That's taken care of within those instructions, but you can look at it by itself over at https://github.com/koreader/koreader-base
