### ISSUE TITLE
FC/crash on android, with signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000068

### ISSUE THREAD

**Issue by H56** [koreader/koreader#643]
My device is an e-ink device of android 2.3.1. The problem is that the app can't run in the device, and the platform is android-9. I think it can be executed. And are there any good methods to improve?

**Comment by allenktv** [comment]
by any chance did you figure out what was happening with your native crash? I am experiencing a similar problem with my app

**Comment by hwhw** [comment]
Nope. It seems to have vanished without us really tackling it... My guess is on an API/ABI mismatch for the code we compile from external libraries, whose build systems are not easily to bring under proper control, so that they may be including (potentially incompatible) system headers. But this is just speculation.

**Comment by junelee220** [comment]
nexus 7，2012，4.4.4.
with koreader-android-arm-linux-androideabi-v2014.11-93-gac77808.apk,
it is usable first,but when i change dbackground=0 to 8 in defaults and reboot the android,
it is said:unfortunately the app has stopped.

**Comment by gerroon** [comment]
I installed release 127 and while it resolves the full screen issue, it looks like no progress on the crashes. KR not just crashes while reading Pdfs it also crashes when clicking on menus and such. It is pretty crashes, I cant have it run more than 30 sec.

**Comment by gerroon** [comment]
Btw I do not have Xposed or Xprivacy or similar apps installed on my Boyue T62.

**Comment by wjchen** [comment]
Use this patch, crash seems become less:
```
require("jit.opt").start("sizemcode=64","maxmcode=512", "recunroll=8", "callunroll=12", "loopunroll=60", "instunroll=16", "tryside=16", "hotexit=160", "hotloop=1792", "maxsnap=160000", "maxside=32000", "maxirconst=160000", "maxrecord=1280000", "maxtrace=320000")
for i=1,1000 do end  -- Force allocation of one large segment
```

**Comment by gerroon** [comment]
@wjchen 
Your patch extensions seems to help with this bug. I have not done much testing but fixed the initial crashes. If anyone suffers from the similar issues these are couple remedies to try.

https://github.com/koreader/koreader/issues/1691

**Comment by Googlerez** [comment]
Same issue with my Mega 6.3" stock Touchwiz Kitkat 4.4.2.

Meat of the logcat:
I/DEBUG   (19424): pid: 1940, tid: 1953, name: reader.launcher  >>> org.koreader.launcher <<<
I/DEBUG   (19424): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000068

**Comment by ahxxm** [comment]
Same issue, on my Sony Z3C, 5.1.1 HongKong stock rom.
Related logs:


    11-01 21:02:20.568 27549-27549/org.koreader.launcher W/ResourceType: Found multiple library tables, ignoring...
    11-01 21:02:20.571 27549-27549/org.koreader.launcher W/ActivityThread: Application org.koreader.launcher can be debugged on port 8100...
    11-01 21:02:20.575 1709-1709/? V/PhoneStatusBar: setLightsOn(true)
    11-01 21:02:20.594 27549-27549/org.koreader.launcher V/threaded_app: Creating: 0xb49cc200
    11-01 21:02:20.594 27549-27568/org.koreader.launcher V/threaded_app: Config: mcc=460 mnc=1 lang=en cnt=US orien=1 touch=3 dens=320 keys=1 nav=1 keysHid=3 navHid=0 sdk=22 size=2 long=1 modetype=1 modenight=1
    11-01 21:02:20.595 27549-27549/org.koreader.launcher V/threaded_app: Start: 0xb49cc200
    11-01 21:02:20.603 27549-27568/org.koreader.launcher I/luajit-launcher: Application data directory /data/data/org.koreader.launcher/files
    11-01 21:02:20.603 27549-27568/org.koreader.launcher I/luajit-launcher: Application library directory /data/app/org.koreader.launcher-2/lib/arm
    11-01 21:02:20.603 27549-27568/org.koreader.launcher I/luajit-launcher: Screen size 720x1184
    11-01 21:02:20.606 27549-27568/org.koreader.launcher I/luajit-launcher: Screen brightness 133
    11-01 21:02:20.661 27549-27568/org.koreader.launcher I/luajit-launcher: Check file in asset module: koreader-g6c51645.7z
    11-01 21:02:20.661 27549-27568/org.koreader.launcher I/luajit-launcher: Found new package revision g6c51645
    11-01 21:02:20.664 27549-27568/org.koreader.launcher A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x68 in tid 27568 (Thread-9073)
    11-01 21:02:20.765 589-589/? D/clmlib: Got activities:0x0000000E
    11-01 21:02:20.766 589-589/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    11-01 21:02:20.766 589-589/? I/DEBUG: UUID: ac31c3a3-ec2d-4b38-a5a1-152780a47708
    11-01 21:02:20.766 589-589/? I/DEBUG: Build fingerprint: 'Sony/D5833/D5833:5.1.1/23.4.A.1.200/3118038657:user/release-keys'
    11-01 21:02:20.766 589-589/? I/DEBUG: Revision: '0'
    11-01 21:02:20.766 589-589/? I/DEBUG: ABI: 'arm'
    11-01 21:02:20.766 589-589/? I/DEBUG: pid: 27549, tid: 27568, name: Thread-9073  >>> org.koreader.launcher <<<
    11-01 21:02:20.767 589-589/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x68
    11-01 21:02:20.772 589-589/? I/DEBUG:     r0 aec32b70  r1 af278290  r2 00001000  r3 fffffff2
    11-01 21:02:20.772 589-589/? I/DEBUG:     r4 af32c788  r5 00000090  r6 af354290  r7 fffffff5
    11-01 21:02:20.772 589-589/? I/DEBUG:     r8 00000952  r9 af32c788  sl 00000952  fp 00000967
    11-01 21:02:20.772 589-589/? I/DEBUG:     ip af457c84  sp af457cb0  lr af316fac  pc 00000068  cpsr 600d0010
    11-01 21:02:20.773 589-589/? I/DEBUG:     #00 pc 00000068  <unknown>
    11-01 21:02:20.773 589-589/? I/DEBUG:     #01 pc 0007ffa8  <unknown>
    11-01 21:02:21.067 1151-1174/? I/BootReceiver: Copying /data/tombstones/tombstone_07 to DropBox (SYSTEM_TOMBSTONE)
    11-01 21:02:21.068 1151-27584/? D/ActivityManager: New dropbox entry: org.koreader.launcher, data_app_native_crash, 4113ba5c-6b86-45df-9169-4693d64a413a
    11-01 21:02:21.074 1151-27584/? W/ActivityManager:   Force finishing activity 1 org.koreader.launcher/android.app.NativeActivity
    11-01 21:02:21.089 619-619/? I/Zygote: Process 27549 exited due to signal (11)
    11-01 21:02:21.381 1151-27584/? I/WindowManager: Screenshot max retries 4 of Token{3f9b2052 ActivityRecord{1298acdd u0 org.koreader.launcher/android.app.NativeActivity t827 f}} appWin=Window{34756a4c u0 Starting org.koreader.launcher} drawState=4
    11-01 21:02:21.382 1151-27584/? W/ActivityManager: Exception thrown during pause
    11-01 21:02:21.382 1151-27584/? W/ActivityManager: android.os.DeadObjectException
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at android.os.BinderProxy.transactNative(Native Method)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at android.os.BinderProxy.transact(Binder.java:496)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:709)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:832)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2759)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2616)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2580)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.    java:11691)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.    java:11588)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12325)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.    java:11783)
    11-01 21:02:21.382 1151-27584/? W/ActivityManager:     at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
    11-01 21:02:21.384 536-536/? E/lowmemorykiller: Error opening /proc/27549/oom_score_adj; errno=2
    11-01 21:02:21.388 1151-1916/? I/ActivityManager: Process org.koreader.launcher (pid 27549) has died
    11-01 21:02:21.388 1151-1916/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:9947 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop:8979 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLocked:8921 com.android.server.wm.WindowManagerService.executeAppTransition:4237 
    11-01 21:02:21.389 1151-1916/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.WindowState.getDisplayContent:803 com.android.server.wm.WindowStateAnimator.updateSurfaceWindowCrop:1294 com.android.server.wm.WindowStateAnimator.setSurfaceBoundariesLocked:1469 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10037 
    11-01 21:02:21.389 1151-1916/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.WindowState.getDisplayContent:803 com.android.server.wm.WindowState.isDefaultDisplay:1330 com.android.server.wm.WindowStateAnimator.updateSurfaceWindowCrop:1304 com.android.server.wm.WindowStateAnimator.setSurfaceBoundariesLocked:1469 
    11-01 21:02:21.389 1151-1916/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.WindowState.getDisplayContent:803 com.android.server.wm.WindowState.getDisplayId:808 com.android.server.wm.InputMonitor.    updateInputWindowsLw:311 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10288 
    11-01 21:02:21.391 1151-1916/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.DisplayContent.setTouchExcludeRegion:237 com.android.server.wm.WindowManagerService.setFocusedStackFrame:4080 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedInner:10364 com.android.server.wm.WindowManagerService.performLayoutAndPlaceSurfacesLockedLoop:8979 
    11-01 21:02:21.392 1151-1177/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.WindowState.getDisplayContent:803 com.android.server.wm.WindowState.getWindowList:1398 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2860 com.android.server.wm.WindowManagerService.removeWindowLocked:2761 
    11-01 21:02:21.393 1151-1177/? E/WindowState: getStack: Window{34756a4c u0 Starting org.koreader.launcher} couldn't find taskId=827 Callers=com.android.server.wm.WindowState.getDisplayContent:803 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2865 com.android.server.wm.WindowManagerService.removeWindowLocked:2761 com.android.server.wm.WindowManagerService.removeWindow:2683 
    11-01 21:02:21.424 1151-2286/? W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@2098258b attribute=null, token = android.os.BinderProxy@3ba2fcf4
    11-01 21:02:21.442 26140-27592/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1761 android.content.ContextWrapper.bindService:539 com.sonyericsson.crashmonitor.MiscTaAdapter.open:90 com.sonyericsson.crashmonitor.service.CrashMonitorService.onInit:127 com.sonyericsson.crashmonitor.service.CrashMonitorService.onHandleIntent:192 
    11-01 21:02:21.455 2151-2151/? I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1b8d5861 time:65794757
    11-01 21:02:21.457 1151-1495/? I/OpenGLRenderer: Initialized EGL, version 1.4
    11-01 21:02:21.720 1151-1177/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3a3650cb u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity t758} time:65795022
    11-01 21:02:22.235 184-184/? I/tad: MiscTA Unit 10010: 
    11-01 21:02:22.235 184-184/? I/tad: WRITTEN (Size 10)
    11-01 21:02:22.265 184-184/? I/tad: Actual erase/write to flash done (count 16, time 1446382942).
    11-01 21:02:22.265 184-184/? I/tad: MiscTA: Write of unit 10010 completed - OK
    11-01 21:02:22.269 184-184/? I/tad: MiscTA Unit 10004: 
    11-01 21:02:22.269 184-184/? I/tad: WRITTEN (Size 13696)
    11-01 21:02:22.301 184-184/? I/tad: Actual erase/write to flash done (count 17, time 1446382942).
    11-01 21:02:22.301 184-184/? I/tad: MiscTA: Write of unit 10004 completed - OK
