### ISSUE TITLE
Emulator crashes(SDL.getPowerInfo and other functions are nil values)

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#6432]
Pinging @pazos, as he'll likely have more idea what's happening.
crash.log:
```
ffi.load: SDL2
ffi.load: SDL2
./luajit: frontend/device/sdl/device.lua:55: attempt to call field 'getPowerInfo' (a nil value)
stack traceback:
        frontend/device/sdl/device.lua:55: in main chunk
        [C]: in function 'probeDevice'
        frontend/device.lua:53: in main chunk
        [C]: in function 'require'
        ./reader.lua:119: in main chunk
        [C]: at 0x0040545e
~/koreader
```
Caused by https://github.com/koreader/koreader/commit/ca21d1401a583507f5e3f7edec2eceaa0ba5b9f4
Happens with the following methods: `SDL.getBasePath()`, `SDL.getPowerInfo()`, `SDL.getPlatform()`
I used `koreader/koappimage:latest`
Run via:
`docker run -e DISPLAY=$DISPLAY --net host --volume="$HOME/.Xauthority:/home/ko/.Xauthority:rw" -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/kris/koreader:/home/ko/koreader -it koreader/koappimage:latest bash -c "source ~/.bashrc && pushd koreader && ./kodev run"`

**Comment by pazos** [comment]
Did you update base?

**Comment by Galunid** [comment]
Nope, sorry to bother, just did and all is good. :)
