### ISSUE TITLE
ReaderFooter: resize font misaligns progress bar

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader#6434]
* KOReader version: master
* Device: emulator & PW4

#### Issue

when changing the font size of a document the progress bar is not properly refreshed leading it to be out of sync until the document is reopened. This is only noticeable on short documents where there is enough space between the chapter marks

you can see in the attached screenshot I am at chapter 2 but since i changed the font size it the progress bar is in the wrong place.
![Reader_2020-07-25_232318](https://user-images.githubusercontent.com/38916402/88470715-e3948380-cecd-11ea-9977-01b39f0075dc.png)

I tried tweeking the `ReaderFooter:onUpdatePos` callback (which handles such events). Changing it to `resetLayout(true)` didn't help, trying `resetLayout(true, true)` crashed on opening a book , trying to add `setTocMarkers()` to it segfaults on opening a book.

attached is a book which shows this problem
[פרשת_אמור.zip](https://github.com/koreader/koreader/files/4977092/_.zip)

**Comment by NiLuJe** [comment]
`setTockMarkers` is *probably* not safe until `ReaderReady`, other than that, doing what the settings that touch the tick do (i.e., `self:setTocMarkers()` & `self:refreshFooter(true)` seems like a good bet).

Not *quite* sure how to make sure setTockMarkers is safe, @poire-z might have some ideas, as we probably have a number of things that have the same kind of constraints...

**Comment by yparitcher** [comment]
> `setTockMarkers` is _probably_ not safe until `ReaderReady` (and IIRC, we fire a bunch of DocSetting related events on book open before that), other than that, doing what the settings that touch the tick do (i.e., `self:setTocMarkers()` and/or `self:refreshFooter(true)` seems like a good bet).
> 
> Not _quite_ sure how to make sure setTockMarkers is safe, @poire-z might have some ideas, as we probably have a number of things that have the same kind of constraints...

I assumed so, does it make sense to redefine `onUpdatePos` in `onReaderReady`?

**Comment by yparitcher** [comment]
I got `ReaderRolling` to take care of it :)
