### ISSUE TITLE
FR: Fixed value settings of brightness and warmth in profiles

### ISSUE THREAD

**Issue by mzelyony** [koreader/koreader#6444]
I'd like to switch day and night backlight settings in 1 move. I am not talking about white on black mode. I use white on black in both cases, but at different levels of brightness and warmth. Obviously I can do it in a few keystrokes today, but it would be nice to alternate between the two settings in one tap

**Comment by NiLuJe** [comment]
Being taken care of in #6440 already ;).

**Comment by Galunid** [comment]
@mzelyony Done, should be available in the next nightly :)
