### ISSUE TITLE
How to solve this problem when running software on raspberry pie zero w?

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6451]
hi,

root@raspberrypi:/home/pi# dpkg -i koreader-2020.07-armel.deb   
dpkg: error processing archive koreader-2020.07-armel.deb (--install):
 package architecture (armel) does not match system (armhf)
Errors were encountered while processing:
 koreader-2020.07-armel.deb

After a period of time, my raspberry pie w finally worked normally, so I installed this version of the software according to the answers I got in the last question. In fact, it is not supported. As follows, but after the successful installation of HF version, this error will be prompted. I hope you can get attention and solve this problem with me.

![image](https://user-images.githubusercontent.com/60098441/88777922-66615b00-d1ba-11ea-8327-3785f6c5d9fc.png)

**Comment by pazos** [comment]
Please **stop open new issues**. Closed issues **are still watched**.
Please **stop renaming old issues** as `!!!!!!!!!!`
Use a **single issue** for all your adventures with custom software and hardware. Thanks!

Duplicate of #6401
