### ISSUE TITLE
Ability to export Reading Statistics data

### ISSUE THREAD

**Issue by rigogsilva** [koreader/koreader#6454]
**Does your feature request involve difficulty completing a task? Please describe.**
I am not sure if this is available yet, or maybe you can point me to where the data is stored. I would like to export the reading data so I can do some of device data analyses on it. But there is no button to export that data.

**Describe the solution you'd like**
In the Reading Statistics, add a button to export. Or just tell me what folder the data is and I can get it. Hopefully is in a usable format.

**Describe alternatives you've considered**
None yet.

**Additional context**
None

FYI: I just started using Koreader, so I may not know what I am talking about. Yet.

**Comment by poire-z** [comment]
There's no export button, because we would have to decide about a format, and nobody has ever cared enough to define one - and it depends on what one wants.

But the stats are in a sqlite DB with simple tables, that one can query and export what he wants (assuming he knows a bit of SQL):
```
$ sqlite3 koreader/settings/statistics.sqlite3
sqlite>
sqlite> .schema
CREATE TABLE book
            (
                id integer PRIMARY KEY autoincrement,
                title text,
                authors text,
                notes      integer,
                last_open  integer,
                highlights integer,
                pages      integer,
                series text,
                language text,
                md5 text,
                total_read_time  integer,
                total_read_pages integer
            );
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE page_stat
            (
                id_book    integer,
                page       integer NOT NULL,
                start_time integer NOT NULL,
                period     integer NOT NULL,
                UNIQUE (page, start_time),
                FOREIGN KEY(id_book) REFERENCES book(id)
             );
CREATE TABLE info
             (
                 version integer
             );
CREATE INDEX page_stat_id_book ON page_stat(id_book);
CREATE INDEX book_title_authors_md5 ON book(title, authors, md5);

sqlite> .help
.dump ?TABLE? ...        Render all database content as SQL
.headers on|off          Turn display of headers on or off
.log FILE|off            Turn logging on or off.  FILE can be stderr/stdout
.mode MODE ?TABLE?       Set output mode
.nullvalue STRING        Use STRING in place of NULL values
.output ?FILE?           Send output to FILE or stdout if FILE is omitted
.separator COL ?ROW?     Change the column and row separators
```
Here are some SQL used by the Calendar view to get what it needs to draw stuff:
https://github.com/koreader/koreader/blob/a9d0990f848ce33ebbdc67291d645c4a5296fb1c/plugins/statistics.koplugin/main.lua#L2008-L2070

**Comment by rigogsilva** [comment]
Nice. That works for me. Maybe one day I will learn Lua and put in the work. 

I did find the sql file inside the application folders and it is located here: `koboreader/settings/statistics.sqlite3` I believe. I will take a look at that. 😃 . 

Thanks for the answer. I think we can close this.

**Comment by rigogsilva** [comment]
The other idea would be to add a button to export the sqlite file.

**Comment by NiLuJe** [comment]
Err, export what? It's not hidden or obfuscated in any way, so there's not really anything to export if you're talking about the plain SQL db itself ^^.

**Comment by rigogsilva** [comment]
Yeah, export the sqlite file. Maybe to somewhere like google drive maybe or a local server.

I can export the file manually, and that is fine. Although, if I wanted to do that often, it would be nice to have a button to do it so. 

Right now to export, I go to the file with Astro file manager and export to google drive. 
Yah, there are probably other ways to do it, but not sure.

**Comment by pazos** [comment]
> Yeah, export the sqlite file. Maybe to somewhere like google drive maybe or a local server.

Keep in mind that KOReader runs on most platforms as a standalone app and implementing all these features inside the program is not trivial. A general suggestion is to use [rclone](https://rclone.org) to manage sync with cloud providers (including your own servers).

You can already [execute shell scripts](https://github.com/koreader/koreader/wiki/Shell-scripts) within KOReader. That makes a simpler way to sync things on Kobos, Kindles, Remarkable, etc. Probably for Android and Desktop OSes there are better ways of doing it.

> I am thinking about adding Koreader to a couple other devices. Does the reading statistics sync between devices?

Nope. The only thing that can be synced right now is the last position in a book.

**Comment by rigogsilva** [comment]
What are your thoughts on the best way to get the reading stats synced between devices? shell script?

Seems like this could be a good feature to add IMO. I am guessing there a cost for having the sync server...

Thoughts?

**Comment by pazos** [comment]
> What are your thoughts on the best way to get the reading stats synced between devices? shell script?

I have no idea :p. I can't speak SQL. Shell scripts + rclone is good way to backup and sync files, not really configuration/history/stats. These probably are more involved but who knows 🙈 

> Seems like this could be a good feature to add IMO.

Quite a difficult one to start with :). But of course PR are welcome

> I am guessing there a cost for having the sync server...

The server is self-hostable. There are actually a few implementations: https://github.com/search?q=koreader+sync. All of them are meant to be used with the [kosync plugin](https://github.com/koreader/koreader/tree/master/plugins/kosync.koplugin). Keep in mind that all of this is just to sync positions. I can't imagine the work involved to sync other things.

**Comment by rigogsilva** [comment]
I was able to learn a bit of the sqlite file. Got these scratch plots done. I also found a way to sync the sqlite file using FolderSync on boox nova2. Would have to do a script to make that work in kobo devices though.  

![image](https://user-images.githubusercontent.com/31558765/89107815-4370ba00-d3f9-11ea-9e58-895dce91e3e9.png)

**Comment by Frenzie** [comment]
The main programs that spring to mind are rclone/rsync on the one hand, and Syncthing on the other. I described how to run Syncthing in https://www.mobileread.com/forums/showthread.php?p=4007007#post4007007

To sync a single file in Syncthing, you'd have to ignore all the files other than the one you want to sync in an `.stignore` file.

But of course that wouldn't be a proper two-way sync for statistics.
