### ISSUE TITLE
WiFi connection problems

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#6455]
* KOReader version: v2020.07.1
* Device: Kobo Aura One

#### Issue
Often I cannot connect to a WiFi network.
Most of the time it starts making a connection and then silently fails - when I subsequently update is is quiet for a while and then asks whether it should connect to WiFi.  This (accepting and choosing to upgrade) can be repeated indefinitely.
But today it failed with a message:
*Netwerkcliënt kon niet worden gestart: Failed to connect to wpa_supplicant control socket: /var/run/wpa_supplicant/eth0.*
Also, sometimes it tells me it refuses to connect to open networks.

#### Steps to reproduce
Go to a place with Wifi and try to update.

**Comment by NiLuJe** [comment]
This should be fixed in current nightlies ;).

(c.f., #6424)
