### ISSUE TITLE
FR: [Desktop]: keep track of window size and position.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6457]
From https://github.com/koreader/koreader/pull/6448#issuecomment-665824377

**Describe the solution you'd like**

Desktop platforms keep the size and position on screen of the previous window. An aditional check that the size and position of the new window fits in the screen is also nice, as screens can change over time.

**Describe alternatives you've considered**

1. implement the change within KOReader:

    - good: SDL provides a way to check screen boundaries. environment variables could override saved window settings on all desktop platforms.

    - bad: needs major refactor of SDL backend.

2. implement the change in early initialization:

    - good: easier to implement, based on env vars already used on emulator

    - bad: no way to override, needs platform specific code for checking screen boundaries

**Additional context**

On mac, where there's only a single instance of the program running, the logic is very simple: apply saved settings if available and save new settings at exit.

On linux, where we can have multiple instances, the logic isn't so clear: shall all windows override position/size settings or just the first instance?.

For example: I started the first instance without previous saved values (800, 600, unspecified position) and resize it to (1024, 768) at position 100,100. Which is the behaviour for the rest of instances? inherit size and let the os to figure out the position?, don't inherit size if there's one running instance? I really don't know. :/

**Comment by pazos** [comment]
> implement the change in early initialization:

sample code for doing that is attached. It needs to be executed before `reader.lua`. It doesn't check screen boundaries yet, but that's not difficult:

check that window.top + window.height <= screen.height and window.left + window.width <= screen.width before setting environment  variables.

```c
#include <stdio.h>
#include <stdlib.h>

#include <lua5.1/lua.h>
#include <lua5.1/lauxlib.h>
#include <lua5.1/lualib.h>

#define TOP "KOREADER_WINDOW_POS_Y"
#define LEFT "KOREADER_WINDOW_POS_X"
#define WIDTH "EMULATED_READER_W"
#define HEIGHT "EMULATED_READER_H"

struct Window {
    int top, left, width, height;
};

int getInt(lua_State *L, const char *key) {
    int value = 0;
    if (lua_istable(L, -1)) {
        lua_pushstring(L, key);
        lua_gettable(L, -2);
        value = lua_tonumber(L, -1);
        lua_pop(L, 1);
    }
    return value;
}

struct Window loadWindow(lua_State *L, const char *file) {
    struct Window window = {0, 0, 0, 0};
    int r = luaL_dofile(L, file);
    if (!r) {
        window.top = getInt(L, "top");
        window.left = getInt(L, "left");
        window.width = getInt(L, "width");
        window.height = getInt(L, "height");
    }
    lua_pop(L, 1);
    return window;
}

void setEnv(const char *name, int n) {
    if (n > 0) {
        char value[8];
        sprintf(value, "%d", n);
        setenv(name, value, 1);
    }
}

int main()
{
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);
    struct Window window;
    window = loadWindow(L, "/path/to/sdl_window.lua");
    setEnv(TOP, window.top);
    setEnv(LEFT, window.left);
    setEnv(WIDTH, window.width);
    setEnv(HEIGHT, window.height);
    lua_close(L);
    unsetenv(TOP);
    unsetenv(LEFT);
    unsetenv(WIDTH);
    unsetenv(HEIGHT);
    return 0;
}
```

**Comment by Frenzie** [comment]
> bad: needs major refactor of SDL backend.

That sounds like a slight exaggeration?

> Which is the behaviour for the rest of instances? inherit size and let the os to figure out the position?

I think that's pretty standard, yes.

**Comment by pazos** [comment]
> That sounds like a slight exaggeration?

Indeed it is a **major** exaggeration. :smile:
