### ISSUE TITLE
App keeps crashing when opened from OneDrive

### ISSUE THREAD

**Issue by SequoiaDu** [koreader/koreader#6459]
on Android, when selecting the koreader to open a PDF from OneDrive, the koreader app immediately crashes.

**Comment by Frenzie** [comment]
Could you please provide a few more details? What version of Android,
which device, which version of KOReader?

**Comment by SequoiaDu** [comment]
Android 9, a Onyx BOOX Max3 e-ink reader, and koreader v2020.07.1

**Comment by pazos** [comment]
The expected behaviour for cloud providers is:

KOReader starts on the file manager, history or last document based on user configuration. The document isn't opened.

The fact that there's a crash suggest that google drive is copying the file in a cache or temp directory and we are actually retrieving its path, crashing because a lack of permissions. If that's true I'm afraid we can't fix it. But we can't know it without logs `adb logcat KOReader:I *:W`

You can import documents from cloud providers in KOReader file manager by clicking the "+" button and choose import here. The specific cloud providers needs to be compatible with android saf file picker, but I guess most of them actually are.

**Comment by pazos** [comment]
@SequoiaDu: If you provide logs I could look at it. If not we need to wait for somebody with a Microsoft account since I don't have one.

**Comment by SequoiaDu** [comment]
@pazos Please see below for the logs. I tested multiple valid PDF files opened from OneDrive but all lead to KOReader crashes.

08-05 18:24:38.205   552   577 E ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
08-05 18:24:38.299  6037  6037 E reader.launche: Not starting debugger since process cannot load the jdwp agent.
08-05 18:24:38.404  1004  2145 W ActivityManager: Slow operation: 86ms so far, now at attachApplicationLocked: after mServices.attachApplicationLocked
08-05 18:24:38.519  6037  6037 I KOReader: Application started
08-05 18:24:38.519  6037  6037 I KOReader: Application info {
08-05 18:24:38.519  6037  6037 I KOReader:   VM heap: 192MB (normal)
08-05 18:24:38.519  6037  6037 I KOReader:   Flags: user, legacy storage.
08-05 18:24:38.519  6037  6037 I KOReader:   Paths {
08-05 18:24:38.519  6037  6037 I KOReader:     Assets: /data/user/0/org.koreader.launcher/files
08-05 18:24:38.519  6037  6037 I KOReader:     Library: /data/app/org.koreader.launcher-i3gEh6lKZRB-8Q638pxFfg==/lib/arm
08-05 18:24:38.519  6037  6037 I KOReader:     Storage: /storage/emulated/0
08-05 18:24:38.519  6037  6037 I KOReader:   }
08-05 18:24:38.519  6037  6037 I KOReader: }
08-05 18:24:38.722  6037  6054 I KOReader: Check file in asset module: koreader-v2020.07.1.zip
08-05 18:24:38.729  6037  6054 I KOReader: Skip installation for revision v2020.07.1
08-05 18:24:38.730  6037  6054 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
08-05 18:24:38.736  6037  6054 W linker  : Warning: "/data/data/org.koreader.launcher/files/libs/libkoreader-lfs.so" unused DT entry: DT_RPATH (type 0xf arg 0x309) (ignoring)
08-05 18:24:38.819  6037  6054 E AndroidRuntime: FATAL EXCEPTION: Thread-12
08-05 18:24:38.819  6037  6054 E AndroidRuntime: Process: org.koreader.launcher, PID: 6037
08-05 18:24:38.819  6037  6054 E AndroidRuntime: java.io.FileNotFoundException: Not a whole file
08-05 18:24:38.819  6037  6054 E AndroidRuntime:        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1167)
08-05 18:24:38.819  6037  6054 E AndroidRuntime:        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1104)
08-05 18:24:38.819  6037  6054 E AndroidRuntime:        at org.koreader.launcher.utils.FileUtils.getPathFromUri(FileUtils.kt:54)
08-05 18:24:38.819  6037  6054 E AndroidRuntime:        at org.koreader.launcher.MainActivity.getFilePathFromIntent(MainActivity.kt:185)
08-05 18:24:38.831  1004  2075 W ActivityManager:   Force finishing activity org.koreader.launcher/.MainActivity
08-05 18:24:38.979  1004  1026 W Looper  : Slow dispatch took 152ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=31
08-05 18:24:39.157  3705  3715 W System  : A resource failed to call close.
08-05 18:24:39.168  1004  1026 W Looper  : Slow dispatch took 187ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=1
08-05 18:24:39.372  1004  1026 W Looper  : Slow dispatch took 165ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@14e6625 m=0
08-05 18:24:39.451  1004  1025 W ActivityManager: Activity pause timeout for ActivityRecord{ad023cf u0 org.koreader.launcher/.MainActivity t275 f}
08-05 18:24:39.857  3705  3705 W BottomSheetBehavior: BottomSheetBehavior now supports multiple callbacks. `setBottomSheetCallback()` removes all existing callbacks, including ones set internally by library authors, which may result in unintended behavior. This may change in the future. Please use `addBottomSheetCallback()` and `removeBottomSheetCallback()` instead to set your own callbacks.
08-05 18:24:39.888  3705  3705 W BottomSheetBehavior: BottomSheetBehavior now supports multiple callbacks. `setBottomSheetCallback()` removes all existing callbacks, including ones set internally by library authors, which may result in unintended behavior. This may change in the future. Please use `addBottomSheetCallback()` and `removeBottomSheetCallback()` instead to set your own callbacks.
08-05 18:24:39.908  3705  3705 W BottomSheetBehavior: BottomSheetBehavior now supports multiple callbacks. `setBottomSheetCallback()` removes all existing callbacks, including ones set internally by library authors, which may result in unintended behavior. This may change in the future. Please use `addBottomSheetCallback()` and `removeBottomSheetCallback()` instead to set your own callbacks.
08-05 18:24:39.947  3705  3705 W BottomSheetBehavior: BottomSheetBehavior now supports multiple callbacks. `setBottomSheetCallback()` removes all existing callbacks, including ones set internally by library authors, which may result in unintended behavior. This may change in the future. Please use `addBottomSheetCallback()` and `removeBottomSheetCallback()` instead to set your own callbacks.
08-05 18:24:40.485  5294  5515 E PowerManager: WakeLock tag:*gms_scheduler*:internal from [com.google.android.gms] is forbidden
08-05 18:24:40.526  5294  5515 E WakeLock: *gms_scheduler*:internal should be held!

**Comment by pazos** [comment]
Thanks for the log, that's indeed a bug. I will fix that so at least it doesn't crash.

See https://github.com/koreader/koreader/pull/5686#issue-352961087 for how to import files within KOReader for different file providers.
