### ISSUE TITLE
Reading Statistics recording long time for certain pages.

### ISSUE THREAD

**Issue by rigogsilva** [koreader/koreader#6461]
* KOReader version: v2020.07.1
* Device: Boox Nova 2

#### Issue
Looking in the statistics.sqlite3 file (table page_stat), I have found some pages to have a higher number of `period` (seconds) recorded for them. See arrows below:
![image](https://user-images.githubusercontent.com/31558765/89126604-7922ab00-d4ac-11ea-98e4-cd8473158c94.png)

Note `page` 154. I think this may be due because I am still learning how to use koreader and playing around with the settings? That is maybe being recorded as time read? 

I took a deep dive into that page to see what records exist for it and here is what I found:
![image](https://user-images.githubusercontent.com/31558765/89126630-c868db80-d4ac-11ea-8b7f-271c86399932.png)

Thoughts on what is happening?

#### Steps to reproduce
Not sure yet. Probably playing with settings while in a page? But that is just a wild guess.

**Comment by Frenzie** [comment]
There's a maximum time somewhere in the settings. I think it defaults to a minute or two but presumably you've set it to a much higher value.

**Comment by rigogsilva** [comment]
Yes, I have set that to 210. But note that it was logged multiple times for the same page, multiple days also. That is in the second screenshot.

**Comment by poire-z** [comment]
The fact that on the 2nd screenshot, everything is below 210, is somehow reasurring we don't have a bug on that period limitation front. If you stay one hour on a page, you get saved 210s. If you move to some next pages, and get back to it, and stay one hour on it, you get saved a new record with 210s.
And on your 1st screenshot, you're showing the cumulative durations, which can go above 210s.

That sounds to me like the logical (and technically simple) behaviour.

May be you expect that if you spend 30s on a page, then move around and go back to that page and look at it again, it's considered "already read" and your second visit should not be accounted ? This might be wrong in some cases, if you first skim quickly (but slowly enough so it gets acccounted), and later do a serious reading when you stay longer on the pages you previously skimmed - you would get not really relevant stats... And your cumulative time reading this book would also be wrong.

So, the real questions is: _but what was on that page 154 , that had you visiting it 19+ times and contemplating it for a cumulative 27 minutes ?!!_
(I hope you'll answer that question, I'm curious :)

**Comment by poire-z** [comment]
> I think this may be due because I am still learning how to use koreader and playing around with the settings? That is maybe being recorded as time read?

Yes, it's quite probable. I think we don't stop any timer or do anything specific when navigating menu or reading dict or wikipedia lookup.
That might indeed be considered a bug - but it might be quite a lot of work to account for the time spent in the many places that might pop up...

**Comment by rigogsilva** [comment]
That page was a simple page. Just a novel... that is the reason I think I was playing around with the settings. 

Yeah, maybe consider not counting time if the menu is open? I think I would consider looking up words in Wikipedia, or dictionary as reading and account that time.

Now, to fix this I suppose the only way is to delete these records from the SQLite file and put the file back in the settings’ folder?

**Comment by rigogsilva** [comment]
In addition. I simpler way to “handle” this without keeping track of the menu status, would be to have a setting for “max seconds per page”. 

In this case, this settings wouldn’t account for time in a page over let’s say 7 minutes. But that may be misleading as well. For example when reading text books where you spend long minutes in one page 🤷‍♂️

**Comment by NiLuJe** [comment]
There's already a per-page ceiling ;).

Ignoring menus and whatnot is not really feasible, as, AFAICT, the plugin simply diffs the date between page-turns. It doesn't actually keep a timer ticking (as that would be slightly insane).

**Comment by poire-z** [comment]
> Yeah, maybe consider not counting time if the menu is open? 

Well, we don't usually spent that much time in the menus :) (and the time we do is usually smoothed out by the time we don't.)
But _you_ do, as you're discovering the whole thing. So, may be _you_ just consider your early statistics not that accurate :)

> I think I would consider looking up words in Wikipedia, or dictionary as reading and account that time.

> In this case, this settings wouldn’t account for time in a page over let’s say 7 minutes. But that may be misleading as well. For example when reading text books where you spend long minutes in one page.

Indded. Different users, different way of seeing/expecting things :/
I personally think (but I'm on the technical side) that it sometimes best to have a simple working of the stats, so people can understand it easily - and eventually correct the results themselves when they interpret the results. Having tons of conditions will make that more complex and less easy to human interpretation/correction.

An other option if you're at ease with SQL is to cook a few queries to clean the stats from the bogus records - like we have `Reset statistics > Reset statistics for books read < N m` - you could have a:
`Reset excessive/bogus page statistics` that you could invoke from time to time.

But all that can have side effects: you might have holes in the hourly histogram in the calendar view then, if you cap the total time on a page.

**Comment by rigogsilva** [comment]
That makes sense. So basically I turned page 154 19 times in 3 different days 🤣. Yeah, not sure 🤔.

FYI: 210 is not the default. I set that for myself.

I will read for a week now that my settings are all complete and see if that happens again.

**Comment by rigogsilva** [comment]
@poire-z agree in keeping it simple. The button: ‘ Reset excessive/bogus page statistics’ seems like a great option.

**Comment by rigogsilva** [comment]
Probably worth seeing if this keeps happening or not. I will report back in a week or so after I have more days of reading in my sqlite file. 

Thanks for the input though. Appreciate it!

**Comment by poire-z** [comment]
> I can put the query together. I am not a Lua developer though... if this is something we would like to add...

We can deal with the Lua and menu stuff for you, when you get one or more SQL queries that:
- work actually, and give out something that will still be coherent with what was before in the various views (or in most of them), so users won't risk much destroying their stats
- are easily menu-item-short-title'able and explainable in some short description, so users know what they get and in which cases it's useful, and caveats, etc...
