### ISSUE TITLE
FR: [Checkboxes on Submenus]

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6474]
On the menu under Gear-> Taps and gestures -> Gesture manager  -> Hold Corner (and most of the others) -> Top left (and the others) you get the following menu:

![Unbenannt](https://user-images.githubusercontent.com/36999612/89317217-5e536080-d67d-11ea-9f23-2db15406c5e3.png)

Why do the last four submenus have a checkbox, other submenus do not have such a checkbox?

**Comment by poire-z** [comment]
It's to show there is something else checked inside this submenu.
(It's [something I requested](https://github.com/koreader/koreader/pull/6441#issuecomment-666466047), so you know where to go to see what is checked - and then uncheck it.)

**Comment by zwim** [comment]
> It's to show there is something else checked inside this submenu.

I missed that point. OK, thank you.
