### ISSUE TITLE
Please add support for Pocketbook Touch Lux 5

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#6475]
The Pocketbook Touch Lux 5 has been released.

Model number should be 628.
212 dpi
frontlight and warm smartlight
4 keys and touchscreen

Please add it to the list of supported devices.

**Comment by pazos** [comment]
@LucyOne: you'll need to test the changes first. In your koreader folder there's a crash log that you can append here.

The steps to add a new model are: 

1. edit `frontend/device/pocketbook/device.lua` with a good text editor, Like notepad, and add a definition for your device. Based on the info you gave it would be something like:

```lua
-- PocketBook Touch Lux5
local PocketBook628 = PocketBook:new{
    model = "PBTouchLux5",
    display_dpi = 212,
}
```

2. at the end of the file add (between 627 and 630)

```lua
elseif codename == "PB628" then
    return PocketBook628
```

Try to run the program again and, it if fails to run, append here the crash.log.

> frontlight and warm smartlight

I'm afraid warmth light won't be supported until an user adds it or a platform maintainer steps in, but the rest *should* work as is.

**Comment by roshavagarga** [comment]
@LucyOne: You can add two more lines, though they might be redundant.
```
-- PocketBook Touch Lux5
local PocketBook628 = PocketBook:new{
    model = "PBTouchLux5",
    display_dpi = 212,
    isTouchDevice = yes,
    hasFrontlight = yes,
}
```

Basically just install according to tutorial, change the noted file with this and the above change(s) and then try to use it and see if it works. If it does, it'll be added to koreader, if there's an issue, crash.log it :+1:

**Comment by LucyOne** [comment]
I will add the line "isAlwaysPortrait = yes". A user on a German forum described a rotation bug like in this issue: [https://github.com/koreader/koreader/issues/3687](url) On his device the screen is rotated 90° to the right.
Will test as soon as my new device arrives.

**Comment by LucyOne** [comment]
The following did the trick:

-- PocketBook Touch Lux5
local PocketBook628 = PocketBook:new{
    model = "PBTouchLux5",
    display_dpi = 212,
    isAlwaysPortrait = yes,
    isTouchDevice = yes,
    hasFrontlight = yes,
}

**Comment by roshavagarga** [comment]
Test all of Koreader's functions and your device's buttons, see what works and what doesn't and mention it here :+1:

**Comment by LucyOne** [comment]
Buttons, menus and gestures work fine. I just tested some functions, because I will send the device back. It's got a faulty pixel :(

**Comment by roshavagarga** [comment]
@LucyOne If you're getting the same model or another PB model, feel free to ping back for further testing.
