### ISSUE TITLE
Incorrect display of the first page of the book

### ISSUE THREAD

**Issue by SvyatKV** [koreader/koreader#6492]
* KOReader version: 2020.07.1
* Device:  Lenovo Tab3 7 Essential TB3-710i, Prestigio Prestigio Muze G3 LTE, TP-Link Neffos C7

Correct the first page in the book, otherwise for some reason it displays the program code
[Mocart_I_Saleri_.A.Pushkin.fb2.zip](https://github.com/koreader/koreader/files/5050406/Mocart_I_Saleri_.A.Pushkin.fb2.zip)
![Error](https://user-images.githubusercontent.com/61149954/89776232-22ebe280-db12-11ea-9f6b-df94786f4e8d.png)

**Comment by hius07** [comment]
`classsheet` is a typo by the author of this test book
https://4pda.ru/forum/index.php?s=&showtopic=945616&view=findpost&p=86021940
It should be `stylesheet`.

**Comment by poire-z** [comment]
Thank you @hius07 for helping discriminating FB2 bugs :)
