### ISSUE TITLE
FR: support for Android 6.0 e-reader devices

### ISSUE THREAD

**Issue by xl666** [koreader/koreader#6497]
Starting from version 2020.04.1 android 6.0 support was dropped, or I'm assuming it
was since I can not install newer versions on my Boyue Likebook Mars running android 6.
When launching the installer it simply displays a "X App not installed" message.

**Comment by Frenzie** [comment]
This is an issue with the Android operating itself. It doesn't say *why*. Uninstall the old version (don't worry, your settings will be kept in /sdcard/koreader) and when install the new one it should work.

**Comment by pazos** [comment]
Duplicate of #6066
