### ISSUE TITLE
Questions about interacting with Leptonica/KOPTContext/Koptinterface

### ISSUE THREAD

**Issue by Galunid** [koreader/koreader#6498]
I've found a bit of time to play around with Leptonica and managed to split comic page into multiple panels like I wanted [here](https://github.com/koreader/koreader-base/issues/1148), but without OpenCV 🙂. Now all that's left is to port my [C++ code](https://pastebin.com/MKr4aJX2) to lua, but I have no idea how to convert BlitBuffer to leptonica's pix or bitmap. Any help appreciated.

**Comment by poire-z** [comment]
I don't know what's a leptonica pix or bitmap :)
But a BlitBuffer is just an object that have some fields:
https://github.com/koreader/koreader-base/blob/9e4ae531c28ff35f43828056e88c18a3e80ff6ea/ffi/blitbuffer.lua#L60-L122
width, height, pitch (nb of pixel per line I think), and a data pointer that points to the stream of pixel bytes (raw, as-is, no compression).
This "data" pointer might just map to something that already exist in leptonica - or you'd just have to copy to tha something by picking into data.

**Comment by Frenzie** [comment]
Doesn't the code I linked there already do pretty much exactly that? You might have to add a few additional cdefs to https://github.com/koreader/koreader-base/blob/9e4ae531c28ff35f43828056e88c18a3e80ff6ea/ffi/leptonica_h.lua of course.

**Comment by Galunid** [comment]
So I assume what I need to do is[1]:
* Add my custom method to `base/ffi/koptcontext.lua` and potentially to `base/ffi/koptcontext_h.lua`
* Add wrapper for my custom method to `koptinterface.lua`
* Add wrapper, for my `koptinterface.lua` wrapper to `pdfdocument.lua`
* Add something that calls pdf's document method to `readerhighlight.lua`
* Add what's needed to cdefs

At least that's what I take based on the example @Frenzie posted in https://github.com/koreader/koreader-base/issues/1148#issuecomment-661894276.

```lua
local page = doc._document:openPage(pageno)
page:getPagePix(kc)
```
`KoptInterface` calls most of it's methods with the above code. I believe this sets attributes (probably `self.src` and likely others) in `KOPTContext` and allows it to further process using leptonica. My question is what exactly is `page`. 
https://github.com/koreader/koreader-base/blob/a96cb1c555c42d77ce88d9e97e89c87cd164d923/ffi/mupdf.lua#L937-L948
```lua
function page_mt.__index:getPagePix(kopt_context)
    local bounds = ffi.new("fz_rect[1]")
    bounds[0].x0 = kopt_context.bbox.x0
    bounds[0].y0 = kopt_context.bbox.y0
    bounds[0].x1 = kopt_context.bbox.x1
    bounds[0].y1 = kopt_context.bbox.y1

    render_for_kopt(kopt_context.src, self, kopt_context.zoom, bounds)

    kopt_context.page_width = kopt_context.src.width
    kopt_context.page_height = kopt_context.src.height
end
```
The thing that interests me the most is what's are the "page" dimensions. Are those fit to devices' screen size, or are they bigger? It would be pretty pointless to cut out panel from comic, not to be able to zoom it without loss of quality.

So far I've been playing around with [this](https://github.com/msh2050/koreader/blob/02d81e04558ed85ec22e13373d5da7cf5a43172b/frontend/document/koptinterface.lua#L294-L303), hence the BlitBuffer -> PIX question. It doesn't seem possible, at least for me, since google isn't really helpful here and I'm not familiar with the lua/c++ interaction.

**Comment by Frenzie** [comment]
> Add my custom method to base/ffi/koptcontext.lua and potentially to base/ffi/koptcontext_h.lua

The first could be an option, but the second almost certainly not? You're using some things like `pixRenderContours` from leptonica that have nothing to do with kopt.

> Add wrapper, for my koptinterface.lua wrapper to pdfdocument.lua

It seems like all the format-specific bits and pieces should already be in place? But if they're not djvu also needs whatever's missing. (Not while you're working on it of course, but for finishing it up.)

> The thing that interests me the most is what's are the "page" dimensions. Are those fit to devices' screen size, or are they bigger? It would be pretty pointless to cut out panel from comic, not to be able to zoom it without loss of quality.

The dimensions are whatever you want them to be. I'm not sure I understand the question atm but I'm still on overheating/lack of sleep brain. :-)

**Comment by Frenzie** [comment]
Oh, you mean in that function you quoted? In that of course it's optimized for display. You'd have to call a new properly zoomed part of the page after you've determined which area to zoom into.

**Comment by Galunid** [comment]
> > Add wrapper, for my koptinterface.lua wrapper to pdfdocument.lua
> 
> It seems like all the format-specific bits and pieces should already be in place? But if they're not djvu also needs whatever's missing. (Not while you're working on it of course, but for finishing it up.)

Let's say I add a method called `getPanelFromLocation(ges)` to `koptcontext`. It should take screen coordinates and return "panel" at this location. To use it in `ReaderHighlight` I'd have to first add it to `koptinterface` (since it's where all `koptcontext` methods are called). Then I need to add this function to `PdfDocument` and then call it using `self.ui.document:getPanelFromLocation(...)`.
Am I missing something/got something wrong?

**Comment by Frenzie** [comment]
Yes, adding it to DjVu. ;-)
