### ISSUE TITLE
August 2020 update

### ISSUE THREAD

**Issue by condorthe2nd** [koreader/koreader#6499]
Koreader installs but I can't find a start button

**Comment by pazos** [comment]
installs where?. In which platform?. Why don't follow the bug template?. This issue miss all the information. Feel free to add the info needed or ask questions in https://www.mobileread.com/forums/forumdisplay.php?f=276

**Comment by condorthe2nd** [comment]
Kobo clara hd i was pushed an update today an koreader still works but
does not show up in menu

**Comment by Galunid** [comment]
It's not really KOReader related. It's because you need to reinstall KFMon, and recent update broke NikelMenu I believe. Please refer to their respective threads on https://mobilereads.com

**Comment by condorthe2nd** [comment]
thank you sorry
