### ISSUE TITLE
Wi-Fi not working after Kobo 4.23.15505 update.

### ISSUE THREAD

**Issue by SilverGreen93** [koreader/koreader#6500]
* KOReader version: 2020.07.1
* Device: Kobo Forma sw ver 4.23.15505

#### Issue
After upgrading to latest sw ver for Kobo 4.23.15505, when I click on Enable Wi-Fi in KOReader I get the message:
Cannot initialize network control client. Failed to connect to wpa_supplicant control socket: /var/run/wpa_supplicant/eth0.

#### Steps to reproduce
Open KOReader. Tap on Wi-Fi connection / Enable Wi-Fi connection. After prompt asks for confirmation to enable wi-fi, the message described above appears.

**Comment by pazos** [comment]
have you tried to turn it off and on again?. Also please clean the parts of the template you don't use :)

**Comment by windirt** [comment]
confirmed on Clara HD, full reseted, updated to 4.23.15505,  fresh installed KOReader 2020.07.1, launched via Nickel Menu 0.3.2

it displaying below message 

when enabling the Wi-Fi:

    Failed to connect to wpa_supplicant contol socket:/var/run/wpa_supplicant/eth0

also tried with toggle flight mode in Nickel. neither work.

attached crash.log

[crash.log](https://github.com/koreader/koreader/files/5067502/crash.log)

**Comment by NiLuJe** [comment]
What about current nightlies?

**Comment by SilverGreen93** [comment]
> have you tried to turn it off and on again?. Also please clean the parts of the template you don't use :)

Yes, I restarted my Kobo but it's the same thing. If Wi-Fi is on before starting KOReader it can be turned off in KOReader, but then can't be turned on again.

**Comment by SilverGreen93** [comment]
> What about current nightlies?

I can't find any nightly builds. Where are they?

**Comment by Frenzie** [comment]
You can find them over at http://build.koreader.rocks/download/nightly/ but you can also upgrade within the program if you switch it to the "development" channel. (Assuming that if you connect to wifi in Nickel it remains operational without causing trouble.)

**Comment by SilverGreen93** [comment]
> You can find them over at http://build.koreader.rocks/download/nightly/ but you can also upgrade within the program if you switch it to the "development" channel. (Assuming that if you connect to wifi in Nickel it remains operational without causing trouble.)

Thanks. Installed nightly v2020.07.1-48-gd1018d2_2020-08-09 and it is the same issue. Wi-Fi can be turned off, but not on.
Couldn't install through OTA update, I manually downloaded. Wi-Fi was not working at all.

**Comment by NiLuJe** [comment]
You'll need to reboot your device after installing the nightly for all the bits and bobs related to this issue to take.

**Comment by SilverGreen93** [comment]
I rebooted, but nothing has changed.

**Comment by NiLuJe** [comment]
More on this later, then, I'm away until the 18th ;).

**Comment by embamba** [comment]
Same issues for me with wifi on a Libra H2O with the firmware update 4.23.15505. I can't turn wifi on from within KOReader, only from Nickel. I can turn it off in KOReader, but can't turn it on again. Same error message along with the other details.

**Comment by pgaskin** [comment]
I don't use KOReader, but I might take a look at the WiFi stuff later.

**Comment by oldman63** [comment]
KOReader version: 2020.07.1
Device: Kobo Aura H2O
Firmware ver: 4.23.15505

Same problem, WiFi cannot be turned on.

**Comment by pazos** [comment]
@pgaskin: thanks!

Based on the crash.log pasted above: 

```shell
08/13/20-14:33:16 INFO  Kobo WiFi: enabling WiFi
insmod: can't insert '': No such file or directory
ifconfig: SIOCGIFFLAGS: No such device
08/13/20-14:33:35 INFO  Kobo WiFi: enabling WiFi
insmod: can't insert '': No such file or directory
ifconfig: SIOCGIFFLAGS: No such device
```

it seems that something changed on the nickel environment we use to retrieve module name and network interface: https://github.com/koreader/koreader/blob/master/platform/kobo/koreader.sh#L104

**Comment by oldman63** [comment]
> KOReader version: 2020.07.1
> Device: Kobo Aura H2O
> Firmware ver: 4.23.15505
> 
> Same problem, WiFi cannot be turned on.

After updating to **Nightly/koreader-kobo-v2020.07.1-49-gd935ca6_2020-08-13** the problem is resolved.
The WiFi is working fine.

**Comment by embamba** [comment]
> > KOReader version: 2020.07.1
> > Device: Kobo Aura H2O
> > Firmware ver: 4.23.15505
> > Same problem, WiFi cannot be turned on.
> 
> After updating to **Nightly/koreader-kobo-v2020.07.1-49-gd935ca6_2020-08-13** the problem is resolved.
> The WiFi is working fine.

Not for me with a Libra H2O.

**Comment by pazos** [comment]
@embamba @oldman63: launcher/method used to launch KOReader?

**Comment by embamba** [comment]
I'm almost always launching KOReader from NickelMenu (latest version). But I've tried from the KOReader icon in My Books in Nickel, too, with the same results.

**Comment by oldman63** [comment]
After Factory Reset, installing this packages:

OCP-Plato-0.9.1_KOReader-v2020.07.1.zip
KFMon-v1.4.1.zip
at this point can't turn wifi on from within KOReader

deleted manually the koreader folder, and
installing koreader-kobo-v2020.07.1-49-gd935ca6_2020-08-13.zip package.
at this point the wifi is working normally

The KOReader is launching from NickelMenu.

**Comment by oldman63** [comment]
> After Factory Reset, installing this packages:
> 
> OCP-Plato-0.9.1_KOReader-v2020.07.1.zip
> KFMon-v1.4.1.zip
> at this point can't turn wifi on from within KOReader
> 
> deleted manually the koreader folder, and
> installing koreader-kobo-v2020.07.1-49-gd935ca6_2020-08-13.zip package.
> at this point the wifi is working normally
> 
> The KOReader is launching from NickelMenu.

Additional information after one day:

WiFi sometimes works well where it doesn’t.
This morning, for example, did not work.

Meanwhile:

The 'Settings/Network/Wi-Fi connection' is off
If Exit from KOReader, restore normal WiFi connection (from Nickel), restart KOReader,
The 'Settings/Wi-Fi connection' is ON
After Using Calibre OPDS Catalog, WiFi status is on
After Sleep mode WiFi status is OFF, the WiFi on is don't working (GOTO "Meanwille" :-) )

+1 'Restore Wi-Fi connection on resume' checkbox does not affect this error message

**Comment by NiLuJe** [comment]
Note to self on a somewhat related matter: USBMS is also broken on 4.22 on exit. Unless my Forma is strangely allergic to macOS and its stock cable.

**Comment by SilverGreen93** [comment]
I use NickelMenu to launch KOReader.

**Comment by pgaskin** [comment]
Can someone send me their dmesg after an issue?

**Comment by SilverGreen93** [comment]
Here it is from my Kobo Forma:
[dmesg_kobo_forma.txt](https://github.com/koreader/koreader/files/5079139/dmesg_kobo_forma.txt)

**Comment by pgaskin** [comment]
Can you try and get one earlier in the boot process, or at least start piping it into a file after you boot?

**Comment by oldman63** [comment]
> Can someone send me their dmesg after an issue?

Here it is from my Kobo Aura H2O_1: [Drive](https://drive.google.com/file/d/1UPOWyq41xU1gkNjeVb_EIByOnuWLGOgh/view?usp=sharing)

**Comment by NiLuJe** [comment]
Not able to look at those, but what @pazos pointed out earlier looks like a good bet.

**Comment by NiLuJe** [comment]
(i.e., double check if the rcS was updated, check the env from a stock, cold booted udev and nickel, check that the bb grep hack still behaves).

**Comment by taosxx** [comment]
> Note to self on a somewhat related matter: USBMS is also broken on 4.22 on exit. Unless my Forma is strangely allergic to macOS and its stock cable.

It's not macOS. I see the same on 4.23 with a Glo HD and Windows 10 (or Arch Linux). Rebooting (or switching off/on) usually restores USBMS.

With v2020.07.1-51-g5a7ecab_2020-08-15 I still can't turn on wifi.

BTW, rcS of 4.23 is missing the following line:
`export WIFI_MODULE_PATH=/drivers/$PLATFORM/wifi/$WIFI_MODULE.ko`
Not sure if this has to do with the problems (but koreader.sh seems to grep for `WIFI_MODULE_PATH`).

**Comment by NiLuJe** [comment]
That's indeed certainly the root cause of the issue.

**Comment by oldman63** [comment]
> > Can someone send me their dmesg after an issue?
> 
> Here it is from my Kobo Aura H2O_1: [Drive](https://drive.google.com/file/d/1UPOWyq41xU1gkNjeVb_EIByOnuWLGOgh/view?usp=sharing)

Here is my [KOReader crash.log](https://drive.google.com/file/d/1LZsmlqda38k0EH90OLx4c-CJYzvk9S7-/view?usp=sharing)
