### ISSUE TITLE
ReaderRolling: gotoPercent is broken

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader#6501]
* KOReader version: master
* Device: emulator

#### Issue

the number keys are bound to `gotoPercent`:
 1 goes to beginning, 2 11% etc. 
this is broken as currently 1 goes to page 1, 2 to 2 etc.

also `gotoPercent` currently only works in scroll mode not in page mode.

Cre.cpp has a `gotoPercent` function which i tried using instead of `gotoPos` but then nothing happens in page or scroll mode.

reported by @mendelmunkis

**Comment by poire-z** [comment]
By changing this 10000 to 100 (why was it 10000 ?! may be some other callers expect that, dunno, haven't checked), it works (but only in scroll mode):
https://github.com/koreader/koreader/blob/d935ca69373487ae985b4133c96f08e18a5c49d0/frontend/apps/reader/modules/readerrolling.lua#L898-L900

I guess go to pos/percent were only aimed at being used in scroll mode (when there is no page, the % of doc height is the only position availlable).

Might need some tweaking to make it work in page mode.
But except for these number keys, I don't think it has any use in page mode. Or make the number keys go to page number a % of total pages - or let it guess in some way on which page is that % of doc height (might need some cre.cpp help for that).

(Not much interested in digging into that...)
