### ISSUE TITLE
[Android] [OPDS] stuck in unnavigable folders

### ISSUE THREAD

**Issue by bobberb** [koreader/koreader#6508]
* KOReader version: v2020.07.01
* Device: Galaxy Tab S6 (Android 10)

#### Issue

OPDS download dialog cannot reach user folders

#### Steps to reproduce

I was able to download one file from an OPDS catalog when the application was freshly installed. However, after pressing ".." one too many times, I find myself in an unbreakable loop.

* Select any OPDS entry
* "Select another directory"
* Due to android 8/9/10 permissions scheme, "Internal Storage" is located at /storage/emulated/0. Download dialog will default to /storage if you've ascended too high with "..".  
* Clicking into /storage/emulated will result in an empty page as /storage/emulated has no read/write permissions and thus the device cannot see /storage/emulated/0 and in turn a book directory location such as /storage/emulated/0/[bookdir]

I have tried clearing app data and still I am stuck.

**Comment by pazos** [comment]
You'll need to edit `koreader/settings/news_downloader_settings.lua` and point to a valid directory.

I suggested workarounds for these kind of issues on other "android" tickets, like https://github.com/koreader/koreader/issues/6379#issuecomment-659332809. Patches welcome.

**Comment by bobberb** [comment]
This file doesn't exist. I'll try to find a skeleton.

**Comment by bobberb** [comment]
Do you have a copy of this file to share?

**Comment by bobberb** [comment]
Correct file is settings.reader.lua in main koreader dir

**Comment by pazos** [comment]
Nope. Correct file is `news_downloader_settings.lua` and the value you'll need to modify is paired to the key `custom_dl_dir`. 

Quoting you:

>  I have tried clearing app data and still I am stuck.

That means that the file is stored in settings dir inside koreader dir, on the primary storage partition on your phone.

**Comment by bobberb** [comment]
I can confirm now on 2 different Android devices that file you speak of
does not exist and settings.reader.lua in ../koreader is responsible for
successfully setting the directory for opds download dialog on the device
that was stuck.

**Comment by pazos** [comment]
Ok, whatever. I believe you. In that case your issue was not what I understood from your ticket. It was just that your last directory was set to /storage/emulated but you never setup that directory as the custom download directory for your feeds.

In the case you select one directory outside the sandbox the program will close. The next time you start the program the plugin won't load and you'll need to remove the specified file from `settings/news_downloader_settings.lua`, as I said above.

Anyways, happy to see you fixed your issue :smile:

**Comment by poire-z** [comment]
Some generic solution to be able to navigate up thru unreadable directories and back down (mostly on Android, `/storate/emulated/0/ > /storate/emulated/ > /storate/emulated/0/`):
```diff
--- a/frontend/ui/widget/filechooser.lua
+++ b/frontend/ui/widget/filechooser.lua
@@ -48,4 +48,9 @@ local FileChooser = Menu:extend{
 }

+-- Cache of content we knew of for directories that are not readable
+-- (i.e. /storage/emulated/ on Android that we can meet when coming
+-- from readable /storage/emulated/0/ - so we know it contains "0/")
+local unreadable_dir_content = {}
+
 function FileChooser:init()
     self.width = Screen:getWidth()
@@ -61,4 +66,5 @@ function FileChooser:init()
         local ok, iter, dir_obj = pcall(lfs.dir, path)
         if ok then
+            unreadable_dir_content[path] = nil
             for f in iter, dir_obj do
                 if count_only then
@@ -102,4 +108,23 @@ function FileChooser:init()
                 end
             end
+        else -- error, probably "permission denied"
+            if unreadable_dir_content[path] then
+                -- Add this dummy item that will be replaced with a message
+                -- by genItemTableFromPath()
+                table.insert(dirs, {
+                    name = "./.",
+                    fullpath = path,
+                    attr = lfs.attributes(path);
+                })
+                -- If we knew about some content (if we had come up from them
+                -- to this directory), have them shown
+                for k, v in pairs(unreadable_dir_content[path]) do
+                    if v.attr and v.attr.mode == "directory" then
+                        table.insert(dirs, v)
+                    else
+                        table.insert(files, v)
+                    end
+                end
+            end
         end
     end
@@ -237,4 +262,6 @@ function FileChooser:genItemTableFromPath(path)
         elseif dir.name == "." then -- possible with show_current_dir_for_hold
             text = _("Long-press to select current directory")
+        elseif dir.name == "./." then -- added as content of an unreadable directory
+            text = _("Current directory not readable. Some content may not be shown.")
         else
             text = dir.name.."/"
@@ -327,4 +354,17 @@ function FileChooser:changeToPath(path, focused_path)
     if focused_path then
         self.focused_path = focused_path
+        -- We know focused_path is a child of path. In case path is
+        -- not a readable directory, we can have focused_path shown,
+        -- to allow the user to go back in it
+        if not unreadable_dir_content[path] then
+            unreadable_dir_content[path] = {}
+        end
+        if not unreadable_dir_content[path][focused_path] then
+            unreadable_dir_content[path][focused_path] = {
+                name = focused_path:sub(#path+2),
+                fullpath = focused_path,
+                attr = lfs.attributes(focused_path);
+            }
+        end
     end

@@ -334,5 +374,5 @@ end

 function FileChooser:onFolderUp()
-    self:changeToPath(string.format("%s/..", self.path))
+    self:changeToPath(string.format("%s/..", self.path), self.path)
 end

```
With that:
```
d--x------  MyUnreadableDirectory/
drwxr-xr-x  MyUnreadableDirectory/MyReadableDirectory
-rw-r--r--  MyUnreadableDirectory/MyReadableDirectory/file.txt
drwxr-xr-x  MyUnreadableDirectory/MyReadableDirectory2
-rw-r--r--  MyUnreadableDirectory/MyReadableDirectory2/file2.txt
drwxr-xr-x  MyUnreadableDirectory/MyReadableDirectory3
-rw-r--r--  MyUnreadableDirectory/file4.txt
```
and if I have file.txt and file2.txt in my History and can open them, as I open them and go to file browser and navigate up the tree, I get it populated and can see:
<kbd>![image](https://user-images.githubusercontent.com/24273478/91455898-f27ea500-e882-11ea-8d70-9e0a57164ade.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/91455942-01655780-e883-11ea-9340-ed81d08726e4.png)</kbd>

So we can go back to these directories we came from.

Sounds too hacky? Does that make sense?

Ref https://github.com/koreader/koreader/issues/6379#issuecomment-659344319 https://github.com/koreader/koreader/issues/4885#issuecomment-494314073

**Comment by Frenzie** [comment]
My main concern would be getting back down again (as we currently don't have a back button or action in the FileChooser widget) rather than the slight hackiness of the code. But it sounds like a partial improvement anyway. :-)

**Comment by poire-z** [comment]
You get back down by taping on these _not-really-found-but-added-as-we-know-they-are-here_ items.
You get back up by taping on the `../` which is always added no matter readability.
As for any back button/action, it would use a "stack/history of visited paths" and would just not be impacted by any dir readability issue.

**Comment by Frenzie** [comment]
> You get back down by taping on these not-really-found-but-added-as-we-know-they-are-here items.

Oh right, I glanced over that. :+1:

**Comment by bobberb** [comment]
Thank you!!!
