### ISSUE TITLE
canot read/parse the book index of mobi format

### ISSUE THREAD

**Issue by superliujian** [koreader/koreader#6509]
I found the Koreader (both app of android and kobo) cannot read/parse the index of ALL the mobi format, it's empty in index page, is it a bug or limitation of Koreader?

**Comment by NiLuJe** [comment]
Mobi support is extremely minimal. Convert to a better format (i.e., ePub).

**Comment by poire-z** [comment]
A limitation. Nobody seems to be interested on working on mobi support, so closing as out of scope.
