### ISSUE TITLE
Switching the frontlight no longer works

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#6515]
* KOReader version: 2020.08
* Device: Tolino Epos 2

#### Issue

Frontlight can only be switched off but not switched on via the gestures.

#### Steps to reproduce
Settings -> Gesture Manager -> Tap corner -> Bottom left -> Toggle frontlight.

Start Koreader with frontlight switched on. If the corner is first pressed, the lighting is switched off. When the corner is pressed again, it is not switched on, the message „Frontlight disabled“ always appears.

**Comment by pazos** [comment]
It affects all android devices. @zwim: are you interested in this one?. I think fix that shouldn't be hard but I didn't look at it yet (and I really don't want to look :p)

**Comment by zwim** [comment]
@elvvis @pazos: I can confirm the behavior elvvis describes.
I will try to fix it tomorrow.

**Comment by zwim** [comment]
@elvvis: A fast workaround: Even if the toggle does only switch off the backlight, you can swipe on the left side to change the backlight.
The real fix will come with #6520

**Comment by pazos** [comment]
Fixed by #6520
