### ISSUE TITLE
Perception expander settings are not persistent

### ISSUE THREAD

**Issue by elvvis** [koreader/koreader#6517]
* KOReader version: 2020.08
* Device: Tolino Epos 2

#### Issue

After switching off the perception expander and quitting KOReader, previously made settings of the perception expander are gone.

#### Steps to reproduce
Enable the perception expander and change the settings (for example: Margin from edges). Switch off the perception expander and quit KOReader.
Restart KOReader and switch perception expander on again. Previously made settings are gone, the default values are used.

**Comment by Galunid** [comment]
They are saved, but if you modify one field, the rest is chosen as default (which is not desired). For now, you can enter all the settings that are of interest to you at the same time. This should make them persistent.

**Comment by elvvis** [comment]
I only modified one value: margin from edges. If you switch off the perception expander and exit KOReader this value is lost and the default value is used.

**Comment by Galunid** [comment]
I tested it with #6518, and cannot replicate, so it should be fixed.
