### ISSUE TITLE
'Toggle rotation': toggle back doesn't work

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#6524]
* KOReader version: v2020.07.1-51-g5a7ecab_2020-08-15/ 
* Device: KA1

#### Issue
I have 'Toggle rotation' in 'Tap corner' > 'Top left' > Device, and then one of the 4 rotation options.

When I toggle back I got stuck. It looks like the backrotation & the first rotation cancel out each other.

**Comment by NiLuJe** [comment]
That's... kind of the point (I think?)?

I'm confused. What were you expecting?

**Comment by gerhaher** [comment]
> What were you expecting?

Like before: when I tap my top left corner I go from portrait to landscape (that's still working), but when I tap the corner again I got stuck in landscape. I want to get back to portrait. Isn't that what 'toggle' means?

**Comment by Frenzie** [comment]
From your text it sounds like what you have set up is:

1. Toggle
2. Go to specific rotation

In which case it doesn't matter what 1 is because of 2.

**Comment by gerhaher** [comment]
Hmmm, OK, I probably have misunderstood rotation in this new gesture manager.

But, it doesn't work anyway. Neither 'Toggle rotation' or 'Rotation'.

If I have 'Toggle rotation' enabled every tap at the corner rotates the screen one step clockwise (or counterclockwise), so I have to tap 4 times to get back, i.e. no toggle. 

If I have 'Rotation' enabled I can rotate only once and then got stuck.

**Comment by NiLuJe** [comment]
Then everything's going according to plan ;). (Although I kind of agree that the "toggle" wording is misleading in this context).

What you seem to want is a toggle between *two* specific rotations. That's probably not implemented, because you can simply do it yourself with a profile with rotation 1 in it, and another with rotation 2 in it.

**Comment by gerhaher** [comment]
> That's probably not implemented

Just to be clear: the toggle rotation has worked as a true toggle before.

**Comment by NiLuJe** [comment]
Ah. Define "before" ^^.

**Comment by gerhaher** [comment]
Hmm, don't remember. I haven't used it this summer. Before this summer maybe??

It was definitely there when multi gestures were introduced. I used it a lot.

**Comment by yparitcher** [comment]
> Ah. Define "before" ^^.

before #6309 there were only 2 states: portrait and landscape, so toggle was binary, now there are 4 states
