### ISSUE TITLE
[Pocketbook]: screensaver behaviour

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6536]
* KOReader version: master
* Device: PocketBook

#### Issue

The behaviour of the suspend/screensaver on Pocketbooks is broken. Since we don't handle power functions on the platform I went and disable screensaver support, but the "sleeping" screen is still displayed on two different ocasions:

- when pressing the home button to return to the launcher
- when pressing the power button to sleep the device.

In both the event `EVT_BACKGROUND` is sent by inkview and we handle that in `onPowerEvent` in `device/generic/device.lua`.

There are a few issues that are related to this one but were masked by the "wonky" suspend behaviour.

#### Steps to reproduce

Disable screensaver support (and a few other unrelated things on the diff):

```diff
diff --git a/frontend/device/pocketbook/device.lua b/frontend/device/pocketbook/device.lua
index 10302761..2a621f3a 100644
--- a/frontend/device/pocketbook/device.lua
+++ b/frontend/device/pocketbook/device.lua
@@ -59,18 +59,20 @@ local PocketBook = Generic:new{
     model = "PocketBook",
     isPocketBook = yes,
     isInBackGround = false,
+    hasExitOptions = no,
     hasOTAUpdates = yes,
     hasWifiToggle = yes,
     isTouchDevice = yes,
     hasKeys = yes,
     hasFrontlight = yes,
+    canRestart = no,
     canSuspend = no,
     emu_events_dev = "/dev/shm/emu_events",
     home_dir = "/mnt/ext1",
 
     -- all devices that have warmth lights use inkview api
     hasNaturalLightApi = yes,
-
+    needsScreenRefreshAfterResume = no,
 }
 
 -- Make sure the C BB cannot be used on devices with a 24bpp fb
@@ -163,8 +165,6 @@ function PocketBook:init()
     Generic.init(self)
 end
 
-function PocketBook:supportsScreensaver() return true end
-
 function PocketBook:setDateTime(year, month, day, hour, min, sec)
     if hour == nil or min == nil then return true end
     local command
```

#### How it looks

![VID_20200820_141633736](https://user-images.githubusercontent.com/975883/90770626-5983e300-e2f2-11ea-948f-85ec66a55929.gif)

#### Expected behaviour

Exactly the same, without the sleeping message, as is not true when returning home and will be overriden by PB screensaver when going to sleep.

Any non orthodox workaround is fine if that makes the sleeping message disapear :)

**Comment by poire-z** [comment]
May be just have them not masquerade as Suspend/Resume in there ?
https://github.com/koreader/koreader/blob/1b904f0f0df731c3949063f54173687008e3b1a8/frontend/device/pocketbook/device.lua#L114-L124

**Comment by NiLuJe** [comment]
That would make it a behavior (somewhat) similar to what happens on Kindle w/ SO: defer suspend/screensaver to the platform.

**Comment by pazos** [comment]
@poire-z @NiLuJe: somehow the "Resume" event is needed to avoid a blank page when returning to KOReader from suspension or home.

If I understand correctly these return values trigger UIManager event handlers:

https://github.com/koreader/koreader/blob/1b904f0f0df731c3949063f54173687008e3b1a8/frontend/ui/uimanager.lua#L82-L91

Which finally use onPowerEvent.

I changed the "Suspend" return value by "SaveState" (as in android) and that work just fine, but the "Resume" event by itself still invokes the sleep infomessage. I had the impression that the message is part of the screensaver logic and shouldn't appear if the screensaver is completely disabled but it seems that I was wrong :p.

Anyways, I need to figure out which code paths are involved here, any knowledge is welcome since I'm pretty new to the screensaver logic.

**Comment by NiLuJe** [comment]
I'm pretty sure the "Sleeping" message should only show if screensaver_mode is set to message. We *may* be missing a check for the ScreenSaver cap if this we happen to have it set in the config despite that.

I know that some platforms do an explicit setDirty on resume to prevent races with the platform (again, Kindle?). I think there's a device cap for that, too (`needsScreenRefreshAfterResume`).

**Comment by roshavagarga** [comment]
Can confirm that the sleeping message has appeared on the PB614W I have on hand, my personal example being me shutting down the device while in Koreader leading to the off screen, which I've set to 'current novel information/cover' from the default firmware, having the 'sleeping' window plastered on there. It doesn't happen every time, but it did happen a few times.

**Comment by pazos** [comment]
It happens each time when the suspend problem is fixed. This issue is less annoying than the suspend issue but still annoying :p
