### ISSUE TITLE
Screen glitch on android device

### ISSUE THREAD

**Issue by fu7eL5sa** [koreader/koreader#6553]
* KOReader version: v2020.7, v2020.7.1, v2020.8
* Device: mmh55lm_f (LG K40s)
* OS: Android Pie, api 28
#### Issue
Glitch on the bottom of the screen, cropping some of view of the book when on landscape mode, when the book is closed, the start screen is also cropped.
#### Steps to reproduce
Open any book and set rotation to any horizontal degree.

![koreaderbug1](https://user-images.githubusercontent.com/70115767/90990996-294f7500-e57c-11ea-9257-20facf0c7157.png)
![koreaderbug2](https://user-images.githubusercontent.com/70115767/90990997-2bb1cf00-e57c-11ea-9fb9-cf9d2bfb873b.png)
![koreaderbug3](https://user-images.githubusercontent.com/70115767/90990998-2d7b9280-e57c-11ea-940c-b3e7095d7d5d.png)

**Comment by pazos** [comment]
nothing can be done without a log :p

**Comment by fu7eL5sa** [comment]
OK, I'm sorry.
I'm a complete newbie in regards to technology. how do I get a log? I've tried running `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F` but it seems that adb is not recognizing my device, as when I run `adb devices -l` no device is shown... what am I doing wrong here? (and yes, I have turned on the usb debugging option on the developer options of my device)

**Comment by fu7eL5sa** [comment]
Update: I got it to work! my computer recognized my device. but when I ran that command nothing actually related to KOReader happened, just a bunch of other apps and stuff. how do I get the log of what happens in this specific app? and where is the log saved? also, the app doesn't crashes, just the UI that gets messed up, like in the screenshots that I sent with this issue :)

**Comment by pazos** [comment]
@fu7eL5sa:

1. clean the log buffer: `adb logcat -c`
2. start to log KOReader messages: `adb logcat KOReader:* *:S`
3. now start the program and reproduce the issue a couple of times.
4. copy anything you logged into a text file and attach here.

**Comment by pazos** [comment]
I'm closing this issue: no feedback
