### ISSUE TITLE
Toggle rotation counter clockwise?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#6555]
The toggle rotation works again, thanks!
But toggle rotation counter clockwise doesn't. When I set DLANDSCAPE_CLOCKWISE_ROTATION = false nothing changes: it continues to rotate clockwise.

Can we perhaps get that back too?

**Comment by NiLuJe** [comment]
Nnno, it's mess my fancy logic :D. Just do Swap + Invert.

**Comment by gerhaher** [comment]
Ahaa, I haven't seen that before. Yeah it works, thanks.

**Comment by NiLuJe** [comment]
Quick question, because I hadn't actually tried (^^): does the rotation happen in one step, or do you suffer visible through the two?

**Comment by gerhaher** [comment]
looks like one step to me

**Comment by NiLuJe** [comment]
Cool, thanks :).
