### ISSUE TITLE
koreader on kpw3 can't read .doc normally

### ISSUE THREAD

**Issue by nannan-first** [koreader/koreader#6556]
vesion is 2020.07.01 kindle-legacy

document and screen photo:
[2019年河南省遴选热点：“乡土人才”是乡村振兴的生力军.zip](https://github.com/koreader/koreader/files/5116619/2019.zip)

![2116135933](https://user-images.githubusercontent.com/62452186/91021069-d3370c00-e625-11ea-9e56-7d3a6c045de0.jpg)
![310182014](https://user-images.githubusercontent.com/62452186/91021073-d5996600-e625-11ea-9ca9-fec3ed3dcbc8.jpg)
![1865610595](https://user-images.githubusercontent.com/62452186/91021088-d8945680-e625-11ea-8756-d442544b81bf.jpg)

**Comment by nannan-first** [comment]
sorry,version is 2020.07.01 kindlepw2

**Comment by Frenzie** [comment]
Formats other than EPUB and FB2 are not supported as well. But if I resave your document it seems to load reasonably well, so I'm not sure what's up with that.

![Screenshot_2020-08-24_10-49-22](https://user-images.githubusercontent.com/202757/91023944-7b81ac00-e5f7-11ea-928f-5cf8ec423b92.png)

**Comment by nannan-first** [comment]
> 

quiet right,it work well on android koreader and pc,but wrong on my kindle

**Comment by NiLuJe** [comment]
Are you sure the file isn't simply corrupt on your Kindle?

**Comment by nannan-first** [comment]
Sure. Actually the file i uploaded was just copy from my kindle.


i already upgrade my koreader to version 2020.08.01, couldn't fix the problem.maybe i should try delete all file and install again.



---Original---

**Comment by Frenzie** [comment]
@NiLuJe The attached file doesn't work. But as I said it works fine (or at least mostly fine) if I resave it.

**Comment by NiLuJe** [comment]
Oh, missed that bit, my bad ^^.

**Comment by poire-z** [comment]
Nobody seems to be interested on working on .doc support, so closing as out of scope.
