### ISSUE TITLE
Crash when tapping bottom right corner to change status bar icon

### ISSUE THREAD

**Issue by kartikynwa** [koreader/koreader#6561]
* KOReader version: 2020.08.1
* Device: Kobo Aura H2O

#### Issue

Koreader crashes when I tap on the bottom right corner. I only have "→ number of pages left in chapter" enabled. When this shows and I tap, it gors to blank like it should. But if I tap again, instead of showing this icon again, Koreader crashes. This has been happening since 2020.07.1 update.

#### Steps to reproduce

1. Settings > Status bar > Disable progress bar and all status icons.
2. Enable "pages left in chapter"
3. If it is visible, tap bottom-right to hide it
4. Tap again to show it again
5. Koreader crashes

##### `crash.log`
[crash.log](https://github.com/koreader/koreader/files/5123891/crash.log)

When I am on my computer I will try to find the relevant section. For now, here is a picture of the crash.

[IMG_20200825_184059](https://user-images.githubusercontent.com/7846060/91178281-8d03aa80-e702-11ea-97c0-14b35f04fee8.jpg)

#### Additional note

Upon further testing I discovered more odd behaviour. I enabled "battery percentage" alongside "pages left in chapter". Now the tapping bottom-right to reshow didn't crash. Then I disabled " battery percentage" again. Now upon tapping bottom-right, first the icon disappear as they should. But on tapping again, it brings back both "battery percentage" and "pages left in chapter" though the former has been disabled.

The gesture action for bottom-right tap is set to "Pass through".

**Comment by NiLuJe** [comment]
After having spent a bit of time trying to reproduce this (in vain): it's tied to having "All at once" enabled, right?

**Comment by kartikynwa** [comment]
> After having spent a bit of time trying to reproduce this (in vain): it's tied to having "All at once" enabled, right?

I am really sorry but I don't know what you mean by "All at once enabled".

**Comment by NiLuJe** [comment]
Status bar > Settings > Show all at once

**Comment by NiLuJe** [comment]
(And it was completely unrelated to the Gesture manager, that's the standard in-footer tap ;)).

**Comment by kartikynwa** [comment]
You are absolutely spot on. Turning that particular setting off fixed it. Thanks very much. I see you've referenced this in a commit so feel free to close this issue.

**Comment by NiLuJe** [comment]
(The issue will auto-close once the PR gets merged ;)).

**Comment by kartikynwa** [comment]
Also thanks very much for your work. Reading has become a hundred times better since I loaded koreader onto my Kobo.
