### ISSUE TITLE
Can't switch zoom mode while Reflow is active

### ISSUE THREAD

**Issue by MicaelJarniac** [koreader/koreader#6572]
* KOReader version: v2020.08.1
* Device: [PW4] Kindle Paperwhite 4 (10th Gen)

#### Issue
When reading a PDF, after activating **Reflow**, when trying to switch to **View Mode: continuous**, a warning message explains about the zoom mode, but switching zoom mode isn't possible while **Reflow** is active.

#### Steps to reproduce
1. Open a PDF
1. Make sure **Reflow** is **off*
1. Go to **Switch zoom mode** and select **Zoom to fit page width** (or some other)
1. Enable **Reflow**
1. Set **View Mode** to **page**, if not already
1. Set **View Mode** to **continuous**
1. Read the warning message
1. Try to go to **Switch zoom mode** and notice it's unavailable

It's mostly just an annoyance, as one would have to disable reflow, then switch zoom mode, then enable reflow again.

**Comment by Frenzie** [comment]
@NiLuJe To what extent is this still relevant with your recent changes?

**Comment by NiLuJe** [comment]
Well, I haven't touched the paged/continuous toggle, at least not on purpose, and I'm unfamiliar with the warning itself, but any and all zoom modes are meaningless/broken in Reflow mode, so they are indeed disabled now.

I guess I'll just see what the warning actually say and tweak it?

**Comment by NiLuJe** [comment]
Yep, hiding it when reflow is enabled makes sense now :).
