### ISSUE TITLE
KOReeader Android Modern Design FR: [a handful of words describing the FR]

### ISSUE THREAD

**Issue by xujun05** [koreader/koreader#6574]
Is there has a plan? the ui is tooooold.

**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by pazos** [comment]
Nope. Please use other apps

**Comment by Frenzie** [comment]
In theory the rendering backend could be used in combination with a newly written native Android frontend. In practice we're sufficiently happy with the E Ink frontend, plus we don't want to recreate it, especially considering that's still the primary use case. Effectively, if you don't like the way KOReader works you can use nice alternative Android apps such as MuPDF, Bubbles, or whatever you prefer.
