### ISSUE TITLE
Method to assign eventhandlers of user written plugins to gestures

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6575]
Since gestures have been moved to a plugin, I don't know how to make the event handlers of my custom plugins available in the multiswipe gesture manager anymore.

It would be great if the gestures plugin had a method or eventhandler with which plugins written by users could make themselves available in the dialog for assigning gestures. That way I wouldn't have to modify source files of KOReader itself or of a third party plugin anymore.

In the past I manually adapted readergesture.lua to accomplish this, but that road is closed now (readergesture doesn't exist anymore). Of course this procedure wasn't ideal, because it involved modifying source files...
   If a hook or eventhandler like above isn't possible, could you point out to me how to make custom eventhandlers available in the gestures dialog?

My device is a Kobo Forma.

**Comment by Galunid** [comment]
I assume your plugins have `onEventName` functions. In that case adding them in
https://github.com/koreader/koreader/blob/46f791c1c02e2ef1a14662879c194b6b1e72ca41/frontend/dispatcher.lua#L33-L35
https://github.com/koreader/koreader/blob/46f791c1c02e2ef1a14662879c194b6b1e72ca41/frontend/dispatcher.lua#L152-L154
will hopefully do the trick

**Comment by NiLuJe** [comment]
I don't quite recall how the plugin management works, but you might also be able to get whether the plugin is enabled or not for the Dispatcher condition, so it's not cluttered by events of disabled plugins ;).

**Comment by smartscripts-nl** [comment]
That's right, my events are named [onEventName].

But when I edit dispatcher.lua, I edit source files of KOReader itself. Then my modifications have to be re-implemented after each update. A method c.q. eventhandler to import events into dispatcher (onDispatcherReady in the calling plugin) or an additional settings-file for user defined eventhandlers would solve this problem.

**Comment by smartscripts-nl** [comment]
That's right, my events are named [onEventName].

But when I edit dispatcher.lua, I edit source files of KOReader itself. Then my modifications have to be re-implemented after each update. A method c.q. eventhandler to import events into dispatcher (onDispatcherReady in the calling plugin) or an additional settings-file for user defined eventhandlers would solve this problem.

**Comment by smartscripts-nl** [comment]
That's right, my events are named [onEventName].

But when I edit dispatcher.lua, I edit source files of KOReader itself. Then my modifications have to be re-implemented after each update. A method c.q. eventhandler to import events into dispatcher (onDispatcherReady in the calling plugin) or an additional settings-file for user defined eventhandlers would solve this problem.

**Comment by NiLuJe** [comment]
Oh, you mean out-of-tree plugins?

Yeaaaaah, I wouldn't imagine we'd want to make that kind of use-cases actually easier, would we? ;).

**Comment by smartscripts-nl** [comment]
Why not?

**Comment by NiLuJe** [comment]
Because we'd rather merge the plugins if it turns out they're useful?

Or is that just me? ;).

**Comment by Frenzie** [comment]
A few lines similar to these might suffice.

https://github.com/koreader/koreader/blob/70f89c4df113bbfe4b8ea89730e71a36dfaddedc/frontend/apps/reader/modules/readermenu.lua#L134-L139

> Because we'd rather merge the plugins if it turns out they're useful?

Ideally, but we also want to facilitate hacking some stuff together. At the same time hacked together stuff often can't be merged as is because some new hacker/contributor will take it as an example.

**Comment by poire-z** [comment]
> I wouldn't imagine we'd want to make that kind of use-case actually easier, would we? ;).

I would.

> Because we'd rather merge the plugins if it turns out they're useful?
> Or is that just me? ;).

It is :) 
See #6255 for a user plugin, that works for him, was proposed, and looked to me a bit too specific - and should look to all of us like it would _require dozens of hours of review_ and fixes before it could be merged. So, I'm grateful to @smartscripts-nl that you gave up that early :) and that you were fine with it staying a user plugin, and kept friendly with us :)

So, yes, I think we should allow user plugins to plug more easily: they can plug into the menu, I think they should be able to plug in dispatcher and so can end up easily into gestures and profiles.

**Comment by pazos** [comment]
Fixed in https://github.com/koreader/koreader/commit/433b82f1622674c7241485f3637fdeed44bb43de#diff-0b3088e1d36df073b90d27ccb02878e84cf69f7c89216489e3ea59949a43c297

**Comment by onatbas** [comment]
for those who are looking for an simpler answer in the future: The prerequisite to anchieve this is by extending event listener and prefixing the handler methods with "on"

A snippet from my plugin which is capable of handling taps and gestures from the GUI.

```
-- Import this.
local EventListener = require("ui/widget/eventlistener")

-- Extend on Event Listener
local Bluetooth = EventListener:extend{
    name = "Bluetooth"
}
 
     -- Register your action at some point during init.
     Dispatcher:registerAction("refresh_pairing_action", {category="none", event="RefreshPairing", title=_("Refresh Pairing"), general=true})


function Bluetooth:onRefreshPairing()
     -- Implement your handler
end
```

**Comment by NiLuJe** [comment]
Note also that almost every Widget class out there is a subclass of EventListener (including the base Widget class) ;).
