### ISSUE TITLE
Killed while viewing pdf

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6580]
PW2, 2020.08
In the crash.log
```
08/27/20-21:34:48 INFO  opening file /mnt/us/books/6 TMP/2 Зарубежная/usp-all.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
08/27/20-21:34:50 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
08/27/20-21:34:50 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
08/27/20-21:34:50 INFO  RD loaded plugin gestures at plugins/gestures.koplugin
08/27/20-21:34:50 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
08/27/20-21:34:50 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
08/27/20-21:34:50 INFO  setting zoom mode to contentwidth
08/27/20-21:48:55 WARN  got error waiting for events: Waiting for input failed: 4

Killed
```
Memory overflow?

**Comment by Frenzie** [comment]
Seems unlikely, unless you mean out of memory rather than memory overflow. But OOM should be fairly unlikely too, unless perhaps it's a 1200 DPI scan or something? Pinging @NiLuJe

**Comment by hius07** [comment]
Yeah, out of memory. Often after switching to FM and back to reading or Text editor many times I need to quit KOReader or even restart my Kindle as page flipping became slow.

**Comment by poire-z** [comment]
Enable Memory usage in the footer, and see if you notice the issues when it reaches some level.
cf https://github.com/koreader/koreader/issues/5998#issuecomment-602180998
Also, TextEditor is memory hungry (and cpu hungry if you edit the text).

**Comment by hius07** [comment]
> Enable Memory usage in the footer

Very good, I'll look at it.

**Comment by Frenzie** [comment]
Also I understand that on Kindle the system memory pressure will be significantly higher. You might be able to get a glance of that in System Statistics, or perhaps a better one over SSH with for example `top`.

<img src=https://user-images.githubusercontent.com/202757/91544346-e0067900-e91f-11ea-8874-bf37e4835acc.png width=45%><img src=https://user-images.githubusercontent.com/202757/91544349-e268d300-e91f-11ea-9714-47c901017100.png width=45%>

On page 1 there you see the same value as in the footer (or something close to it), in this case some 153 MB.  On page 3 (on a real device probably page 2) you see available memory is ~24 GB, even though KOReader's only using 153 MB. The rest is taken up by other programs.

On Kobo, the system doesn't use too much, some 50-100 MB. But on Kindle I understand the system's significantly more memory hungry,

**Comment by hius07** [comment]
Crashes occurred several times on pdf only, never on fb2 or in Text editor.

**Comment by NiLuJe** [comment]
Yeah, we run concurrently to the system on Kindle, and it's only going to get worse, as said system is not getting any lighter on resource usage with time ;).

**Comment by hius07** [comment]
Switched on M usage in the minibar, absolutely the same as described in https://github.com/koreader/koreader/issues/5998#issuecomment-602180998.
Reading fb2 M remains in 25-30 not increasing with page flipping.
Reading pdf M achieved 90 after 30 pages and flipping get slowed down.
Returning to fb2 didn't free the memory, so program restart required to speed it up.

**Comment by poire-z** [comment]
Might try limiting the memory used for caching:
https://github.com/koreader/koreader/blob/06bce655c527735d1b331b71889e79124dfb31b4/frontend/cache.lua#L33-L38
https://github.com/koreader/koreader/blob/06bce655c527735d1b331b71889e79124dfb31b4/defaults.lua#L29-L36

I guess setting this in default.persistent.lua might help not reaching 90:
`DGLOBAL_CACHE_SIZE_MAXIMUM = 1024*1024*30`

**Comment by Frenzie** [comment]
You can try adjusting one or both of these. 0.4 is a pretty conservative value but back in the days of 128 MB devices (which yours is not; 256 MB) it was set to 0.2 and 30. Apparently the heavy Kindle system is making it behave like a device with 128 MB or less.

https://github.com/koreader/koreader/blob/06bce655c527735d1b331b71889e79124dfb31b4/defaults.lua#L32-L36

Also see https://github.com/koreader/koreader/commit/42d139ce077a7ce77954de04790ebffe4ce973b6

**Comment by poire-z** [comment]
May be you can share your conclusion and solution ? :)

**Comment by hius07** [comment]
The issue with pdf is obviously OOM, the solution is just to watch the M value in the minibar and restart KOReader when reaching high M.
As I read pdf not very often, I didn't play with cache size.

**Comment by poire-z** [comment]
What was your value considered "high M" ?
(Just so we know if we ever do something about it, like auto restarting koreader - and I can compare with my Kobo.)

**Comment by hius07** [comment]
I tried to kill KOReader flipping pdf, reached M 100, it became very slow flipping but didn't kill.

Reading fb2 I have M about 25-30, page flipping doesn't increase it.
Every switching to FM or Text editor and back increases it by 8-10 (and I cannot decrease it just by long reading after that).
Sometimes a little slowing down of flipping can be seen at about M 60-70.

I've been looking at M for a couple of days only (after your kind advice) so not too many conclusions yet.

**Comment by hius07** [comment]
Played a little with my pdf. Opened it with M:50, flipped about 10 pages, switched to FM and back, flipped more (slower and slower) and at M:95 the device got frozen, no response to the touchscreen and even to the power button short press.
Waited for 10 min, rebooted the device with the power button long press.
The last record in the crash.log the same as before
`WARN  got error waiting for events: Waiting for input failed: 4`

**Comment by NiLuJe** [comment]
Yeah, I'd expect the stock system to eat around 128 to 150MB, and the system to wig starting at 80% mem occupied.
