### ISSUE TITLE
USBMS: no restart & when connecting immediately after start

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#6582]
* KOReader version: v2020.08.1-21-g8296bea_2020-08-28/   
* Device: KA1

#### Issue
1. It doesn't restart when it says it should. It got stuck at 'Done! KOReader will now restart...' so I have to restart my device.

2. If I connect the device immediately after having started KOReader (I use KSM 09), I have to fast double tap on 'Share' to make it work. With normal single taps the popupwindow just toggle translucent and never disappears, so I have to restart the device.

**Comment by NiLuJe** [comment]
1. You need to have done a full exit & start cycle after the update for this to actually work.

2. That's an unrelated issue with devices with a certain input event handler that mangles the first tap. Although I don't think I can reproduce that on my H2O, so it might be compounded by the terrible touch input of the KA1?

**Comment by NiLuJe** [comment]
And even if I do force a long-hold to make the popup transparent, I can still tap or dismiss it just fine over here?

**Comment by NiLuJe** [comment]
The only thing I can possibly trigger with a fast session start on plug is ending up with a busy mountpoint if I have very unlucky timing with the Wi-Fi script (which implies having restore Wi-Fi on resume enabled).

In my test, I hit the check *just* as dhcpd started, so it prevented the mount, but by the tem the process check ran, it was gone, so the list was empty ;).

**Comment by NiLuJe** [comment]
Yeah, on my H2O, the first tap just goes to the ether, it's not detected as a hold, so at worst I need to tap twice, but that's it.

And that's not anything new, either.

**Comment by gerhaher** [comment]
I tried my Kobo Aura: I could reproduce neither 1 nor 2. So everything OK with that one.

But KA1. Restart just doesn't work. The only thing that happens is that the light goes off after 90 seconds. Stuck!

**Comment by NiLuJe** [comment]
Is that after a full reboot?

If so, check the syslog over Wi-Fi `logread -F`.

**Comment by NiLuJe** [comment]
And also double-check the env from a running luajit process, check that `KOREADER_DIR` is sane.

Is your launcher setup strictly identical between the two devices?

**Comment by gerhaher** [comment]
I have no Wifi at the moment.

> Is your launcher setup strictly identical between the two devices?

I think so.

> And also double-check the env from a running luajit process, check that KOREADER_DIR is sane.

Teach me how.


I don't know if this is important or not but in any case, with my KA1, when the page with the message "USBMS IN PROGRESS. Please eject your...." appears it switches to nightmode (black background, white text) and after eject it switches back to normal again. My  Kobo Aura doesn't behave like that.

**Comment by NiLuJe** [comment]
> > And also double-check the env from a running luajit process, check that KOREADER_DIR is sane.
> 
> Teach me how.

The DIY way: `xargs -0 -n 1 /proc/$(pidof -s reader.lua)/environ`, or the easy way, if you have htop installed (i.e., https://www.mobileread.com/forums/showthread.php?t=254214): press `E` when highlighting the reader.lua process.

> 
> I don't know if this is important or not but in any case, with my KA1, when the page with the message "USBMS IN PROGRESS. Please eject your...." appears it switches to nightmode (black background, white text) and after eject it switches back to normal again. My Kobo Aura doesn't behave like that.

That's normal: it's hardware nightmode, and HW nightmode is blacklisted on the Aura because it's buggy/crashy.

**Comment by gerhaher** [comment]
I decided it was time to try NickelMenu.

So with a new clean installation, without changing any settings (and after a full reboot) I tried again, and it still doesn't work.

**Comment by gerhaher** [comment]
Another thing that doesn't work (which works fine on Kobo Aura).

If I choose 'Start USB storage' from the menu, a message says that I can press the power button to exit. Nothing happens when I do that.

**Comment by NiLuJe** [comment]
Ha, that 's interesting, I was going to ask you to try that ;).

So, yeah, do that, but with a running logread -F in a shell and it should tell us what's happening :).

**Comment by gerhaher** [comment]
> So, yeah, do that, but with a running logread -F in a shell and it should tell us what's happening :).

OK, with pleasure.

But, pleeease, give me more detailed instructions this time how to do it. Like you instructed your grandma. :)
What is a shell, for example? I'm afraid you overestimated my knowledge in these things before. :)

**Comment by NiLuJe** [comment]
1. Install [KoboStuff](https://www.mobileread.com/forums/showthread.php?t=254214).
2. Assuming Windows, install [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) (choose the right installer for your setup at the top of the page). If macOS, Terminal & ssh are installed by default.
3. Get your device's IP (Device > Networking > Network Info)
4. Connect to it in PuTTY (just enter the IP in the IP field, and hit connect).
5. Log in as user `root`, and then just hit Enter when a password is required.
6. You should now be in front of a shell prompt, just enter `logread -F`, it'll print the current backlog, and then automatically update to track the current log.
7. Run 'Start USB storage' with the device unplugged, and hit the power button to exit.
8. Post the relevant content of the output from logread (i.e., the end of it, it should be verbose enough for you to make sense of).

**Comment by gerhaher** [comment]
Thanks, but I've got no Wi-Fi at the moment ( and won't have for some time).

**Comment by Frenzie** [comment]
For most other things you could use USBNet instead of wifi but I suspect that would conflict with this very specific use case.

**Comment by Frenzie** [comment]
If you have a laptop you can also make it work by setting up the laptop as a wifi access point but that might be a bit difficult to explain.

**Comment by NiLuJe** [comment]
Yeah, the fact that this deals with USB precludes anything but Wi-Fi, really ;).

I mean, since the current test (i.e., unplugged) doesn't actually involves a real USBMS session, you could delay checking the logs until later over USBNet, but since apparently the device shuts down without giving you back control, that doesn't quite work either ;).

**Comment by NiLuJe** [comment]
> If you have a laptop you can also make it work by setting up the laptop as a wifi access point but that might be a bit difficult to explain.

A smartphone AP works, too (I, err, may have done some debugging at the library a couple of times :D).

**Comment by Frenzie** [comment]
> A smartphone AP works, too

Same thing in principle, sure, but that can't be pleasant. ;-D

**Comment by potash** [comment]
I have the same device and issue #1 (hangs at 'Done! KOReader will now restart...'). I have wifi and am happy to send a log but can you help me install KoboStuff? I did not see any installation instructions in the README. Thanks, looking forward to USBMS!

**Comment by NiLuJe** [comment]
It ships as a KoboRoot tarball, so, install it like any other KoboRoot tarball/FW update: Put the KoboRoot.tgz file in the .kobo folder and reboot the device (or, if done from within Nickel, it'll reboot on its own on eject).

**Comment by potash** [comment]
@NiLuJe thanks, it's been a while since I installed any KoboRoot tarballs. I think the error is `Oct 21 18:41:11 usbms[1409]: [main:1218] fchdir: Bad file descriptor`. Full log:

```
Oct 21 18:40:55 usbms[1409]: Initializing USBMS v0.9.10 (2020-10-06 05:26:29 +0200)
Oct 21 18:40:55 usbms[1409]: [FBInk] Detected a Kobo Aura One (373 => Daylight @ Mark 6)
Oct 21 18:40:55 usbms[1409]: [FBInk] Clock tick frequency appears to be 100 Hz
Oct 21 18:40:55 usbms[1409]: [FBInk] Screen density set to 300 dpi
Oct 21 18:40:55 usbms[1409]: [FBInk] Variable fb info: 1404x1872, 8bpp @ rotation: 3 (Counter Clockwise, 270°)
Oct 21 18:40:55 usbms[1409]: [FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 10813440 bytes & line length: 1408 bytes
Oct 21 18:40:55 usbms[1409]: [FBInk] Fontsize set to 32x32 (IBM base glyph size: 8x8)
Oct 21 18:40:55 usbms[1409]: [FBInk] Line length: 43 cols, Page size: 58 rows
Oct 21 18:40:55 usbms[1409]: [FBInk] Vertical fit isn't perfect, shifting rows down by 8 pixels
Oct 21 18:40:55 usbms[1409]: [FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Oct 21 18:40:55 usbms[1409]: Initialized FBInk v1.22.2-58-g26bc1ec for Kobo
Oct 21 18:40:55 usbms[1409]: Initialized libue v0.3.0
Oct 21 18:40:55 usbms[1409]: Initialized libevdev v1.9.901 for device 'gpio-keys'
Oct 21 18:40:55 usbms[1409]: [setup_usb_ids:118] USB product ID: 0x4225
Oct 21 18:40:55 usbms[1409]: [FBInk] Font `/mnt/usbms/resources/fonts/CaskaydiaCove_NF.ttf` loaded for style 'Regular'
Oct 21 18:40:55 usbms[1409]: Internal storage partition wasn't busy, it's been successfully marked as expired.
Oct 21 18:40:55 usbms[1409]: Starting USBMS shenanigans
Oct 21 18:40:55 usbms[1409]: Device generation is older than Mk. 7, can't check charger type!
Oct 21 18:40:55 usbms[1409]: Starting USBMS session...
Oct 21 18:40:56 usbms[1409]: USBMS session in progress
Oct 21 18:40:56 usbms[1409]: Waiting for an eject or unplug event . . .
Oct 21 18:40:56 usbms[1409]: [ue_parse_event_msg:135] line: `ACTION=add`
Oct 21 18:40:56 usbms[1409]: [ue_parse_event_msg:135] line: `DEVPATH=/module/g_file_storage`
Oct 21 18:40:56 usbms[1409]: [ue_parse_event_msg:135] line: `SUBSYSTEM=module`
Oct 21 18:40:56 usbms[1409]: [ue_parse_event_msg:135] line: `SEQNUM=1056`
Oct 21 18:40:56 usbms[1409]: [handle_uevent:349] uevent successfully parsed
Oct 21 18:40:56 usbms[1409]: [handle_uevent:352] skipped 114 bytes udev uevent: `udev-142`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `ACTION=change`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `DEVPATH=/devices/platform/imx-i2c.2/i2c-2/2-0032/ricoh619-battery/power_supply/mc13892_bat`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `SUBSYSTEM=power_supply`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_NAME=mc13892_bat`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_STATUS=Charging`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_PRESENT=1`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_VOLTAGE_NOW=4065900`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_CAPACITY=75`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_TEMP=274`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_TIME_TO_EMPTY_NOW=3932100`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_TIME_TO_FULL_NOW=1500`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_TECHNOLOGY=Li-ion`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `POWER_SUPPLY_HEALTH=Good`
Oct 21 18:40:57 usbms[1409]: [ue_parse_event_msg:135] line: `SEQNUM=1057`
Oct 21 18:40:57 usbms[1409]: [handle_uevent:349] uevent successfully parsed
Oct 21 18:40:57 usbms[1409]: Caught a charge tick
Oct 21 18:40:57 usbms[1409]: [handle_uevent:352] skipped 475 bytes udev uevent: `udev-142`
Oct 21 18:41:07 usbms[1409]: [ue_parse_event_msg:135] line: `ACTION=offline`
Oct 21 18:41:07 usbms[1409]: [ue_parse_event_msg:135] line: `DEVPATH=/devices/platform/fsl-usb2-udc`
Oct 21 18:41:07 usbms[1409]: [ue_parse_event_msg:135] line: `SUBSYSTEM=platform`
Oct 21 18:41:07 usbms[1409]: [ue_parse_event_msg:135] line: `DRIVER=fsl-usb2-udc`
Oct 21 18:41:07 usbms[1409]: [ue_parse_event_msg:135] line: `MODALIAS=platform:fsl-usb2-udc`
Oct 21 18:41:07 usbms[1409]: [ue_parse_event_msg:135] line: `SEQNUM=1058`
Oct 21 18:41:07 usbms[1409]: [handle_uevent:349] uevent successfully parsed
Oct 21 18:41:07 usbms[1409]: Caught an eject event
Oct 21 18:41:07 usbms[1409]: Ending USBMS session...
Oct 21 18:41:10 usbms[1409]: Done :)
Oct 21 18:41:11 usbms[1409]: Bye!
Oct 21 18:41:11 usbms[1409]: [main:1218] fchdir: Bad file descriptor
Oct 21 18:41:11 koreader.sh[1256]: USBMS session failed (1), shutting down in 90 sec!
```

**Comment by NiLuJe** [comment]
@potash: Yep, and that was indeed my original suspicion...

The bad news is that I don't really see how this could be happening, though...

If you're amenable to that, I may ask you to run a more verbose binary to try to figure out what's going on ;).

In the meantime, a couple questions:

* Which FW version are you running?
* How are you launching KOReader?

**Comment by NiLuJe** [comment]
Okay, apparently [reading manpages until the end](https://github.com/koreader/KoboUSBMS/commit/38304034736b1a820fe94a188c304e9d5e160463) helps...

Can you try again after putting the attached tarball in koreader's `data` folder? (replacing the same tarball that should already be there: don't unpack it yourself).

[KoboUSBMS.tar.gz](https://github.com/koreader/koreader/files/5419271/KoboUSBMS.tar.gz)

**Comment by potash** [comment]
@NiLuJe that fixed it thanks!
