### ISSUE TITLE
Same Wallabag article gets a different md5 checksum every time it's downloaded, preventing progress sync

### ISSUE THREAD

**Issue by everdred** [koreader/koreader#6588]
* KOReader version: v2020.08.1-21-g8296bea_2020-08-28 on Android and Kobo, 2020.08.1 on amd64
* Device: Kobo Libra H2O, Pixel phone, amd64 desktop

#### Issue
At one point I was able to use KOReader's progress sync feature with Wallabag articles but it no longer seems possible. I dug into the .sdr metadata that accompanies the downloaded Wallabag .epub file and it appears that a different checksum is generated each time the article is downloaded, even when the repeated attempts happen on the same device. This can be reproduced with more than one Wallabag article.

#### Steps to reproduce
Save an article to Wallabag server using Wallabag software
Download article using KOReader's Wallabag plugin
Read part of article, push progress using Progress Sync feature
Attempt to pull progress on another device and find that the "latest progress is coming from this device"

**Comment by pazos** [comment]
See https://github.com/koreader/koreader/issues/6491. (Same issue but with calibre books). 

Not sure if this one is fixable. But you can workaround using LAN sync. Download your wallabag article once in one of your devices. Then publish the article on that device and subscribe to it on the rest of your devices. Now you have the same article with the same mdsum in all your devices and progress sync should work.

**Comment by everdred** [comment]
@pazos  Thank you for the suggestion! While the Zsync UI is always a little confusing to me every time I use it, I was able to get it to work.
