### ISSUE TITLE
Pages containing images refreshed / flickering every 45 seconds. How come?

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6589]
* KOReader version: 2020.08.1
* Device: Kobo Forma

#### Issue

In this version I notice a regular flickering of the screen when a page contains one or more images. The page in this case seems to be rebuilt from top down every 45 seconds. Very noticeable! I haven't observed this behaviour in previous versions.

Is this a bug, or a setting related issue?

#### Steps to reproduce

Load a page with images and wait at least 45 seconds...

**Comment by Frenzie** [comment]
Do you mean a normal full screen refresh (which would be weird, don't get me wrong) or something else? I'm not sure how to imagine from the top down since the whole screen is supposed to flash all at once — when it flashes.

**Comment by smartscripts-nl** [comment]
It was definitely a full screen refresh.

I have applied these modifications: https://github.com/koreader/koreader/commit/0e27963ae71657bf941110e9aaaad2063d147eed

That solved the problem!

**Comment by Frenzie** [comment]
Alright, closing as fixed by #6540. Thanks!

**Comment by NiLuJe** [comment]
Err, the delay makes no sense to me, unless you maybe had the footer enabled with the clock set to refresh automatically?

**Comment by smartscripts-nl** [comment]
Hello,

Yes, that option is indeed enabled on my ereader. So that was the trigger for this problem! But solved now, luckily!

Van: NiLuJe <notifications@github.com>
Beantwoord: koreader/koreader <reply@reply.github.com>
Datum: 28 augustus 2020 at 23:38:05
Aan: koreader/koreader <koreader@noreply.github.com>
Cc: smartscripts-nl <info@smartscripts.nl>, Author <author@noreply.github.com>
Onderwerp:  Re: [koreader/koreader] Pages containing images refreshed / flickering every 45 seconds. How come? (#6589)  

Err, the delay makes no sense to me, unless you maybe had the footer enabled with the clock set to refresh automatically?
