### ISSUE TITLE
Double tap on left or right side of screen doesn't trigger anything

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6591]
* KOReader version: 2020.08.1
* Device: Kobo Forma

#### Issue

Double tap on left or right side of screen triggers no event handler. Left and right upper and lower corners do.

#### Steps to reproduce

Assign an event handler (doesn't matter which) to a double tap on right or left side of screen. Tapping there then doesn't do anything. Rotation of the e-reader also makes no difference.

**Comment by poire-z** [comment]
Seems to work for me. Re-open if you can reproduce.
(Needs `Gear > Taps and gestures > [ ] Disable double tap` unchecked, and `Tap interval` to be small enough to not consider double tap a bounce.)
