### ISSUE TITLE
Status Line on Emulator not updated after frontlight toggle

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6610]
* KOReader version: v2020.08.1-32-g85a16d00
* Device: KOReader emulator

#### Issue
status line does not reflect frontlight status after frontlight toggle.

#### Steps to reproduce
./kodev run
open book
open frontlight dialog 
set frontlight to some value (e.g. 100)
close frontlight dialog
--> here you see frontlight state 100, that's ok
toggle frontlight
--> you get a popup saying frontlight disabled, but the status line does not reflect that.

Please look at the statusline at the end of the video. (The aspect ratio of the video is wrong, on the screen is ok).
[simplescreenrecorder-2020-08-31_14.07.18.mp4.gz](https://github.com/koreader/koreader/files/5150198/simplescreenrecorder-2020-08-31_14.07.18.mp4.gz)

**Comment by pazos** [comment]
If that is an issue it can be fixed with:

```diff
--- a/frontend/device/generic/powerd.lua
+++ b/frontend/device/generic/powerd.lua
@@ -79,6 +79,7 @@ function BasePowerD:turnOffFrontlight()
     if self:isFrontlightOff() then return false end
     self:turnOffFrontlightHW()
     self.is_fl_on = false
+    self:_broadcastChanges()
     return true
 end
 
@@ -89,6 +90,7 @@ function BasePowerD:turnOnFrontlight()
     if self.fl_intensity == self.fl_min then return false end  --- @fixme what the hell?
     self:turnOnFrontlightHW()
     self.is_fl_on = true
+    self:_broadcastChanges()
     return true
 end
 
@@ -143,8 +145,11 @@ end
 
 function BasePowerD:_setIntensity(intensity)
     self:setIntensityHW(intensity)
-    -- BasePowerD is loaded before UIManager. So we cannot broadcast events before UIManager has
-    -- been loaded.
+    self:_broadcastChanges()
+end
+
+function BasePowerD:_broadcastChanges()
+    -- BasePowerD is loaded before UIManager. So we cannot broadcast events before UIManager has been loaded.
     if package.loaded["ui/uimanager"] ~= nil then
         local Event = require("ui/event")
         local UIManager = require("ui/uimanager")
```
