### ISSUE TITLE
Android: Dictionary search always returned "No definition found"

### ISSUE THREAD

**Issue by haymant** [koreader/koreader#6614]
* KOReader version: koreader-android-arm-v2020.08.1.apk
* Device: Android 8.1 on Xiaomi Moaan inkPad X eBook Cortex A7

#### Issue

After installing dictionaries, Koreader dictonary lookup can't find any word.

#### Steps to reproduce
1. Install some English dictionaries
![image](https://user-images.githubusercontent.com/700512/91779332-d20a6e00-ec27-11ea-841c-eb01e7a1048a.png)

2. Verify dictionaries are in list
![image](https://user-images.githubusercontent.com/700512/91779368-f0706980-ec27-11ea-8c7a-e70943e7d55e.png)

3. Search simple words like 'test'
![image](https://user-images.githubusercontent.com/700512/91779409-1138bf00-ec28-11ea-8498-366fd8813e33.png)

4. Koreader returned 'no definition found'

##### `crash.log` (if applicable)
During searching, the logs didn't print any new lines

**Comment by pazos** [comment]
@haymant: could you test than dictionaries are indeed uncompressed in koreader/data/dict ¿?

**Comment by haymant** [comment]
@pazos Thanks. I manually untared them, and dictionary works now.
