### ISSUE TITLE
Refreshing time shows up minibar

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6616]
Kindle PW2, 2020.08.1-44

Refreshing time shows up minibar on pages where it shouldn't be shown (History, TOC, popup footnotes)

![1](https://user-images.githubusercontent.com/62179190/91834367-a18afa00-ec50-11ea-910b-3b9b8f87a5f2.png)

**Comment by hius07** [comment]
The issue has occurred recently, maybe after https://github.com/koreader/koreader/commit/bafc52afd1da7cd19a699fbb7a5f52dcc66eb00e?

**Comment by hius07** [comment]
@poire-z, can you please look at it.

**Comment by NiLuJe** [comment]
It was never supposed *not* to do that ;).

It possibly didn't happen before #6563, but that was arguably a happy coincidence ;).

I'm not *quite* sure how it can trigger in History, though, unless the History view doesn't trigger a `CloseDocument`, for some reason?

But it's perfectly "normal" in anything that's technically still ReaderUI (i.e., ToC, Footnotes).

I don't *think* it hurts for footnotes, though?

Not quite sure how we could easily prevent that in the ToC, I'm not familiar with how this bit works.

**Comment by NiLuJe** [comment]
Can we get essentially bracket `ReaderToc:onShowToc()` between `ReaderFooter:onSuspend()` and ``ReaderFooter:onResume()`?

**Comment by hius07** [comment]
Is it OK to see the minibar over the menu?

![Reader_2020-09-12_193138](https://user-images.githubusercontent.com/62179190/93000136-04bd3c00-f52f-11ea-8b77-d574d8069229.png)

**Comment by NiLuJe** [comment]
Ah, yep, that applies to `ConfigDialog`, too :D.

**Comment by NiLuJe** [comment]
The least dodgy way to fix it is probably to whip up a new event, emit it where needed, and let `ReaderFooter` handle it?

**Comment by NiLuJe** [comment]
@hius07: Any other places where it shouldn't show up but does?

**Comment by poire-z** [comment]
Shouldn't it be UIManager job to manage the stack/covering and prevent paintTo if covered, or issue a paintTo to the covering widgets too ?
If we don't have that, that's probably because we never needed it as nothing else redraw itself in the background?

Or just add a `self.view.footer_covered` that the few things that know they are covering the footer could set and unset ?
At minima, it could check if there's something with `covers_fullscreen` in the widget stack (but it will then still show over footnotes popup, configdialog...)

> It was never supposed not to do that ;).

But why did it not do that ? :)

**Comment by hius07** [comment]
Book information, Book status, Favorites etc. When in reader and minutes changes the minibar shows up over almost any menu or information screen.
The issue has occurred recently (end of August), I have had refreshing time forever and have never seen it before.

**Comment by NiLuJe** [comment]
@poire-z: Because it's not *in* the UIManager stack to begin with: it's a subwidget of ReaderUI, and it (was) tied to ReaderUI own paintTo.

I made it request explicit subwidget repaint instead of repainting the full ReaderUI in #6540, hence the extra screwiness.

**Comment by hius07** [comment]
I got it even in the Text editor.

**Comment by NiLuJe** [comment]
I'm going to need more context on how to trigger this for stuff I'm not familiar with:

* What's the issue with footnotes, and how do i reproduce it?

* Text editor? How? When? Why? ^^.

**Comment by hius07** [comment]
![Reader_2020-09-12_201403](https://user-images.githubusercontent.com/62179190/93001048-e5291200-f534-11ea-90f5-e052ab8dee4d.png)

**Comment by poire-z** [comment]
> I'm going to need more context on how to trigger this for stuff I'm not familiar with:

I guess `Status bar > Settings > [x] Auto refresh time` - then display one of these things and just wait for one minute :)

**Comment by hius07** [comment]
> Kindle PW2, 2020.08.1-44

Reported then, now I have 2020.08.1-58.

**Comment by NiLuJe** [comment]
I meant more generally how you open said widgets ^^.

e.g., I have no idea what @hius07 just did to get there ;).

**Comment by hius07** [comment]
Reading a book, then menu Tools - Text editor

**Comment by hius07** [comment]
I have no changes to the default system files, my some User style tweaks only.

**Comment by NiLuJe** [comment]
Okay, @poire-z's idea to basically reinvent UIManager takes care of most of those, good :).

(The only loss vs. the manual event bracketing is that the date is not up-to-date when going back to ReaderUI... until the next refresh. But, oh, well. Given the amount of stuff flagged covers_fullscreen where this can happen, hahahah, nope).

**Comment by NiLuJe** [comment]
So, what's left that's *not* flagged `covers_fullscreen`?

What's the deal with footnotes, for instance?

**Comment by NiLuJe** [comment]
Okay, a quick check in a Shakespeare play, and now I get the footnotes stuff ^^.

**Comment by poire-z** [comment]
Not really following :/ 
What's to be reinveted in UIManager ? (what are you thinking about?)
ConfigDialog is not `covers_fullscreen` as it just covers the bottom. But ReaderToc and History are (when they are fullscreen, as we are actually using them).
Footnotes popup are just another widget not-fullscreen (like dictquicklookup).

**Comment by NiLuJe** [comment]
@poire-z: I meant checking for `covers_fullscreen` ourselves, too: https://github.com/NiLuJe/koreader/commit/685166b74835999d1900c40809ccb77eda7111da

**Comment by poire-z** [comment]
OK :)
Can't you here even call these widgets setDirty's region funcs to get the region they cover, and if they intersect with the footer area, either don't redraw the footer, or have these widget repainted ?

**Comment by NiLuJe** [comment]
The footer's region is unknown at that point (and... horribly tricky to compute in some cases, c.f., the meat of #6540), and I have to assume that the refresh region may also be bogus in those other widgets ;).

But, in a perfect world, yeah, that would be neat ;).

**Comment by poire-z** [comment]
> The footer's region is unknown at that point 

You could at least estimate a max height, and assume full screen width for width.

>  I have to assume that the refresh region may also be bogus in those other widgets ;)

They may be larger that what is currently displayed, but probably not smaller.
So, if these larger regions overlap with the footer estimated max height, just don't do the footer refresh (it might show the wrong time if not really covered, but that's acceptable I think).

**Comment by Frenzie** [comment]
Sorry, I hadn't seen this yet when I commented on https://github.com/koreader/koreader/pull/6648

> Shouldn't it be UIManager job to manage the stack/covering and prevent paintTo if covered, or issue a paintTo to the covering widgets too ?

^ That's my perspective too.

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/pull/6648#issuecomment-691526710

I'm not disagreeing, but it'd be a pretty specific implementation. The only gain would be that it'd be in the "right" place (especially since we access a technically private table).

(And, also, the actual footer computations would still be done, which might yield up-to-date footer data when we show it back).

**Comment by hius07** [comment]
The latest 2020.08.1-66, checked bottom menu, History, popup footnote - no minibar showing up.
Thanks a lot.

**Comment by hius07** [comment]
I haven't check https://github.com/NiLuJe/koreader/commit/e44edbf368f9279538c789e7079cbf245c2b0ae7 yet, but with the previous version minibar is back!
Under the dialogue windows which require onscreen keyboard (Go to, Find) minibar shows up over the keyboard.

**Comment by NiLuJe** [comment]
Yep, that's fixed in #6650 ;).
