### ISSUE TITLE
Feature request: Make Tap left and Tap right configurable

### ISSUE THREAD

**Issue by tastytea** [koreader/koreader#6634]
Hi, there seems to be no way to change the action for tapping on the left and right side? It would be very useful to me if I could configure the left tap to turn to the next page. 

Imagine holding the reader with the left hand and a cup of tea in the right hand. 😊

**Comment by hius07** [comment]
You can change tap zones positions and sizes
https://github.com/koreader/koreader/blob/master/defaults.lua#L78-L79

or in the filebrowser via menu Tools - More tools - Advanced settings

**Comment by tastytea** [comment]
Thanks, changing `DTAP_ZONE_FORWARD` to `{x = 0, y = 0, w = 1, h = 1}` worked. It would still be nice to have a GUI for that though.

**Comment by yparitcher** [comment]
You can invert the page turn directions (left -> forwards and right -> backwards) by `menu -> Navigation -> Invert page turn taps and swipes`
This can also be turned on/off through a gesture or profile.

**Comment by pazos** [comment]
> It would still be nice to have a GUI for that though.

Eventually everything on "advanced settings" and/or "defaults.lua" will be moved elsewhere. But keeping an issue opened for each one of these advanced settings is a bit overkill.
