### ISSUE TITLE
crash/exit when FTP to external SD card under Android 10

### ISSUE THREAD

**Issue by clach04** [koreader/koreader#6636]
* KOReader version: latest v2020.8.1
* Device: Samsung S9, android 10

#### Issue

Ftp from server to external SD card and app closes

#### Steps to reproduce

Set up from under cloud storage

Choose external SD card as destination

Download. Get "may take a while" dialog box then exits silently (possibly crashes).

Works fine with internal storage.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

**TBD I will check. Need access to adb**

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by pazos** [comment]
@clach04 Give it a look at closed android issues labeled "can't fix"

**Comment by clach04** [comment]
thanks @pazos , looking at #5784 it's definitely the same steps to reproduce. It looks like a message is displayed in #5784 whereas I'm not seeing a message and koreader exits.
