### ISSUE TITLE
FR: Trigger Importing Content

### ISSUE THREAD

**Issue by layanto** [koreader/koreader#6638]
**Does your feature request involve difficulty completing a task? Please describe.**
After adding EPUBs from OPDS, the books don't appear in Kobo's My Books section while they do appear in KOReader's File Browser. I use KOReader and Kobo's standard reader interchangeably and would like my books to be available in both readers.

**Describe the solution you'd like**
Feature in KOReader to trigger Kobo's Importing Content

**Describe alternatives you've considered**
After adding EPUBs from OPDS, I connect Kobo to computer via USB and then disconnect USB to trigger Kobo's Importing Content. But this kind of defeats the purpose of OPDS. If I need to connect via  USB, I may as well copy EPUBs via USB.

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by Frenzie** [comment]
It looks like that's covered by [NickelMenu](https://pgaskin.net/NickelMenu/#features).

https://github.com/pgaskin/NickelMenu/blob/c2d26181b9d87b2d8b8d24ec32cb19ff851366df/res/doc#L82-L86

**Comment by layanto** [comment]
Thanks. Will try this.

**Comment by NiLuJe** [comment]
A simple NM `rescan_book` should indeed do the trick ;).
