### ISSUE TITLE
Absolute font size in footnote popup

### ISSUE THREAD

**Issue by tastytea** [koreader/koreader#6642]
KOReader: **v2020.08.1**
Device: **PocketBook PB632**

The footnote popup has a different font than the book. Since the font size “30” seems to mean something different for the embedded font and the footnote font, the footnote text is huge, although it should be a little bit smaller than the ebook text (-2).

### How to reproduce

I can't reproduce this with the AppImage.

* Open [this ebook](https://theanarchistlibrary.org/library/david-graeber-debt.epub).
* Set font size to 30.
* Enable Taps and gestures → Links → Show footnotes in popup.
* Open a footnote in a popup.

### Screenshot

![Reader_2020-09-10_070456](https://user-images.githubusercontent.com/3681516/92683818-34542480-f334-11ea-8323-b851ed55ef75.png)

**Comment by hius07** [comment]
> The footnote popup has a different font than the book.

It's by design, hardcoded.
https://github.com/koreader/koreader/blob/ffa9857ff18daa3e456ec4e3b171dbe0295ba603/frontend/ui/widget/footnotewidget.lua#L39

> the footnote text is huge, although it should be a little bit smaller than the ebook text (-2)

Why can't you set it to, say, -6? Different font faces have different sizes. I see no issue here.

**Comment by tastytea** [comment]
> Why can't you set it to, say, -6? Different font faces have different sizes. I see no issue here.

I'd have to re-set it for every book. It's annoying.

**Comment by hius07** [comment]
> I'd have to re-set it for every book. It's annoying.

So strange. I have `["footnote_popup_relative_font_size"] = -5` in `koreader/settings.reader.lua` and it is applied to all books.

**Comment by tastytea** [comment]
It is applied to all books, yes. But not all books use the same font. If I set `footnote_popup_relative_font_size` to -10 it kind of works (still larger than the book text), but the next book may use a font that has the same ideas about size as “Noto Sans”, so the footnotes would be so small that they're unreadable.

Currently my font size is 30 and the footnote size is 20. In the next book, I may set the font size to 22 and the footnote size would be 12.

If the footnote font has to be hardcoded, a setting for an absolute font size would be more useful, in my opinion. And maybe the user selected default font could be used?

**Comment by hius07** [comment]
Oh, I see. Waiting for @poire-z  return to discuss further.

**Comment by NiLuJe** [comment]
I feel to see how you could get out of this one : if the font is different, the metrics may be different. Whether the size is relative or absolute won't change that?

**Comment by pazos** [comment]
> Setting the footnote font to an absolute size would ensure that the size always stays the same, regardless of the document font, right? I think that would be a better solution than the relative setting, because I would only have to set it (at most) once.

Sure, here you go: 

https://github.com/koreader/koreader/blob/master/frontend/ui/widget/footnotewidget.lua#L218

Change the value there to the absolute font size you want.

**Comment by tastytea** [comment]
Thanks, but why is it the default to use a size relative to another font's size? Even the comment of the variable admits that font sizes are not comparable.

**Comment by pazos** [comment]
No idea, other than works for me/us :tm:

It is easier to derive the font size of the foot note from the document size than to implement the following:

- a check somewhere (where it makes sense) to toggle between absolute and relative sizes
- an UI to set the absolute size if the user choses that
- change that specific code path to include user settings.

I think PR are welcome and would benefit some users, but please just add new options without changing defaults for now.

**Comment by Frenzie** [comment]
I didn't double check what's currently possible but the easiest may be to extend style tweaks to include a footnote popup style tweak? By which I mean the same general mechanism (i.e., a CSS file in a folder) but the actual implementation would have to be custom-tailored to MuPDF of course.

**Comment by poire-z** [comment]
My initial idea with this relative font size was that it would follow the user-set font size for the document, so when the user increase or decrease font size, the footnote popup font size would be just right (and he would not have to go changing that footnote popup hard font size in another menu).
I admit that people usually have a prefered reading font size that they don't change often, and we could have instead an absolute font size that would _not_ change with the user set document font size.

If really needed, we could just have a hold_callback on the `Set footnote popup font size` (or another bottom button on the normal spin widget) to set the current computed (from relative) footnote font size as an absolute font size to be used instead (for the current book only ? for all books?), with a small symbol in that menu title to show it is active.

> The footnote popup has a different font than the book

We can't know what is the document main "visual" font size, that the user is seeing. See the sample at https://github.com/koreader/crengine/pull/355#issuecomment-656760791 .
You might be reading a quote in a smaller font size: should a popup footnote from there have a smaller font size than one from another section of the book with a bigger main paragraph font size?

> But not all books use the same font

So, this is just an issue with bad books that tweak the user specified font (which is the only thing we know and are sure of, and is the reference for `1rem`).
So, if a book sets `BODY { font-size: 1.3em; }`, the books decides to screw user's choice.
I do see such books, and it's always a pain, as it screws other things (like specific top and bottom margins I have set to perfectly align bottom footnotes with my default font size). The only solution is to "Ignore publisher font size", but then, you miss bigger font size for titles and headings...

May be we should have another style tweak that resets the font size only for "main" text parts, like:
```css
body, p {
 font-size: 1rem !important;
}
```
@tastytea : can you try this and see if it helps?

**Comment by tastytea** [comment]
> [style tweak]
> can you try this and see if it helps?

The style tweak did not help. The font-size is only modified for `h1`-`h6`, `sub`, `sup`, the TOC and footnotes. The font-family in the [ebook](https://theanarchistlibrary.org/library/david-graeber-debt.epub)'s CSS is `"Linux Libertine O", serif;`; no embedded font. Turning off the embedded fonts and styles didn't help either. The used font is [Fanwood Text](https://www.theleagueofmoveabletype.com/fanwood).

The issue seems to be that "Fanwood Text" and "Noto Sans" have wildly different ideas about font sizes.

![Noto Sans – Fanwood Text](https://user-images.githubusercontent.com/3681516/92991444-1b8a7100-f4e4-11ea-80bc-08815d7f7043.png "Left: Noto Sans, right: Fanwood Text")

I think the footnote-size has to be decoupled from the document font size.

**Comment by NiLuJe** [comment]
I wouldn't mind a style tweak like that being added, @poire-z ;).

**Comment by poire-z** [comment]
> The font-family in the ebook's CSS is "Linux Libertine O", serif;; no embedded font. Turning off the embedded fonts and styles didn't help either. _The used font is Fanwood Text_.
The issue seems to be that "Fanwood Text" and "Noto Sans" have wildly different ideas about font sizes.

So, it's you that did set Fanwood Text as your user prefered/default font ? If that's the case, and NotoSans is too big, you could just set Footnote popup relative font size to be -4 or -6 instead of -2 ?

**Comment by tastytea** [comment]
>So, it's you that did set Fanwood Text as your user prefered/default font ? If that's the case, and NotoSans is too big, you could just set Footnote popup relative font size to be -4 or -6 instead of -2 ?

I did set it to -10, it's still too big. The UI doesn't allow me to set it smaller. Even if I could set it to -12 or -14 or whatever, the next book may use a font that has the same ideas about size as “Noto Sans”, so the footnotes would be so small that they're unreadable.

Currently my font size is 30 and the footnote size is 20. In the next book with a different font, I may set the font size to 22 and the footnote size would be 12.

**Comment by poire-z** [comment]
OK, it wasn't too much work to have both options:

<kbd>![image](https://user-images.githubusercontent.com/24273478/92997072-a4b79d00-f510-11ea-924f-b20cd3163edc.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/92997066-99647180-f510-11ea-9664-aba78e92df89.png)</kbd>

Wording suggestions ?

Here are the 2 files to replace, if you want to test drive that: [footnotePopupAbsFontSize1.zip](https://github.com/koreader/koreader/files/5212786/footnotePopupAbsFontSize1.zip)

**Comment by NiLuJe** [comment]
Fine by me (except for the "abs**t**olute" typo in the button ;p)) ;).

**Comment by tastytea** [comment]
Thanks! But `footnote_popup_absolute_font_size` seems to be divided by 2 somewhere? I need to set it to 40 to get a font size of 20 (the initial value was 47). Tested with 2020.08.1-63.

**Comment by poire-z** [comment]
I might have missed a `Screen:scaleBySize(font_size)`.
Try this one: [footnotePopupAbsFontSize2.zip](https://github.com/koreader/koreader/files/5212839/footnotePopupAbsFontSize2.zip) and tell if it's ok (or if I did make it divided by 4 :)

**Comment by tastytea** [comment]
It's okay now. :tada:

**Comment by poire-z** [comment]
> May be we should have another style tweak that resets the font size only for "main" text parts, like:
```css
body, p {
 font-size: 1rem !important;
}
```

For most "most..." (non-*) style tweaks, we target`body, p, li {...}`, so I guess there too.

Should `blockquote` be added to this list? Or does BLOCKQUOTE feel more like a container, like DIV ?
Various docs show samples using `<blockquote><p>text...</p></blockquote>`, some others just `<blockquote>text...</blockquote>` . Wikipedia EPUBs have `<blockquote><p>`, but my current book just `<blockquote>text`.

I guess we could/should also add `dd, dt`, but these are so rare in EPUBs that I think it might be not worth bothering with the additional checks. Or should we?

**Comment by NiLuJe** [comment]
@poire-z: I feel like blockquote blocks are often used to also tweak font family/size, so, maybe leave it alone for that?

**Comment by poire-z** [comment]
> I feel like blockquote blocks are often used to also tweak font family/size, so, maybe leave it alone for that?

You mean don't add it?
But if they are used for that, don't we want that tweak to reset them to our default font size so we can read large blocks of text more easily?

(Been checking that tweak with various books, with a rather low success rate. Some books puts titles in P with a classname and not headings, others set a font size in a wrapping span inside the P, others use absolute font sizes that we would kill in a P, but not in inner SPAN/SUP/SUB...)

**Comment by NiLuJe** [comment]
> But if they are used for that, don't we want that tweak to reset them to our default font size so we can read large blocks of text more easily?
> 

Fair point ;).

**Comment by tastytea** [comment]
> […] others set a font size in a wrapping span inside the P, others use absolute font sizes that we would kill in a P, but not in inner SPAN/SUP/SUB...)

I've made an ebook with ` <p><span style="font-size: 10pt;">` and added `p>span` to the selectors in the style tweak. Works fine.

``` css
body, p, blockquote, p>span
{
   font-size: 1rem !important;
}
```

**Comment by poire-z** [comment]
Yep, for that specific case.
But it will kill any sup/sub that would be done using : 
`<p>This is the 2<span style="vertical-align: sup; font-size: 70%">nd</span> time...</p>`
I guess the idea for that additional style tweak (we already have "Ignore all publisher font sizes") would be to still keep these kind of inline font-size changes.
Still thinking about if it's worth it, or if it's all too different and best left to user/book style tweak done after inspecting the html and styles (like this` p>span`).

**Comment by tastytea** [comment]
@poire-z Are you gonna make a pull-request for the absolute font size option?

**Comment by poire-z** [comment]
Yes, I've just been waiting for v2020.09 to be released (which looks like it will be soon) to PR that kind of changes, so we get a month to test/fix it without impacting "stable" users with a too quick change.
So, in a few days.
