### ISSUE TITLE
“Swipe to go back” sometimes freezes

### ISSUE THREAD

**Issue by tastytea** [koreader/koreader#6643]
* KOReader version:  v2020.08.1
* Device: PocketBook PB632

#### Issue

Going back to the previous location after I have followed footnote links works sometimes, sometimes the device (not just the KOReader) freezes.

#### Steps to reproduce

1. Open an ebook with footnotes.
2. Enable Taps and gestures → Links → Swipe to go back.
3. Follow a footnote link.
4. Swipe right to go back.
5. Repeat 3. and 4. until device freezes.

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/5199322/crash.log)

**Comment by Frenzie** [comment]
Most likely fixed by https://github.com/koreader/koreader/pull/6602 and friends. Could you try the latest nightly?

**Comment by tastytea** [comment]
Thanks, I updated to 2020.08.1-62 and the issue is gone.
