### ISSUE TITLE
EPUB Highlights-Export: export notes including full text

### ISSUE THREAD

**Issue by WolfgangDpunkt** [koreader/koreader#6644]
I read scientific books with Koreader and it would be really great if I could export the whole document including annotations and highlights as HTML or PDF. The goal is to read and evaluate the annotated book on the desktop (macOS or Windows). 

The possibility to export the highlights and notes within an EPUB , using the Evernote plugin, is really great. But it's a pity that only the highlighted pieces of text are exported, the surrounding context is lost. In order to be able to continue working with the annotations later on the computer, it would be practical to create a copy of the whole text including the highlights. Or the possibility to merge the highlights with the whole document, as PDF or HTML. 

Thanks for your consideration.

And thank you very much for this great piece of software!

**Comment by NiLuJe** [comment]
Enter https://www.mobileread.com/forums/showthread.php?t=265433 maybe?

**Comment by WolfgangDpunkt** [comment]
> Enter [KoHighlights](https://www.mobileread.com/forums/showthread.php?t=265433), maybe?

Thanks for the recommendation. I know the KoHighlights tool. Unfortunately, it also only offers the option to export the highlighted text pieces, but not the whole text including the highlights.

**Comment by Galunid** [comment]
> But it's a pity that only the highlighted pieces of text are exported, the surrounding context is lost.

Well, couldn't you just highlight the surrounding context? It's usually what I do. Alternatively you could convert your books to PDF ;-)

**Comment by NiLuJe** [comment]
Yeah, there's not going to be a one size fits all here: context is relative ;).

Either get the "missing" context by doing fulltext searches in another reader (e.g., foliate/Calibre/Sigil), or even with a metadata copy in the KOReader emulator.

But that's never going to be a simple workflow, that can handle every situation from within the device itself: context could be a couple sentence in one page, or much more/less in another.

Or, as @Galunid said, handle highlights in two passes: an inner highlight for your actual highlight, and another on top of that with the necessary context.

**Comment by NiLuJe** [comment]
Because exporting the whole text makes no sense: that's the book, you already have that ^^.

**Comment by WolfgangDpunkt** [comment]
Many thanks for the feedback!
You are right, there are indeed some kind of workarounds.
But especially with scientific texts, it is much more efficient to be able to pass on or further process a copy of the text in a common document format including the comments and highlights.
But since the Koreader sidecar format is proprietary and, to my knowledge, not supported by any other reader application, the only way is exporting from within Koreader, as PDF or HTML.

The workaround via the emulator is doable, but a bit cumbersome.  Unlike PDF/HTML files, the text can't be passed on to a colleague in an easy way and you can't integrate it into a literature management system or any other software. The workflow would be very cumbersome.
While the change in the Koreader-notes-export-process would actually be not that big, instead of "export only the highlighted text parts", the new feature would only have to be "export a copy of the document as PDF/HTML and include the highlights/notes".

I admit that this function is especially useful for the particular use case of working with specialist/scientific literature, but still many users would benefit from it.  But that's why I'm willing to support this feature request with a[ bounty source, as small expense allowance](https://www.bountysource.com/issues/92885640-epub-highlights-export-export-notes-including-full-text). :-)

**Comment by NiLuJe** [comment]
But... ePub *is* (X) HTML o_O.

**Comment by NiLuJe** [comment]
By which I mean I sure hope Zotero & co. recognize ePubs ;).

Otherwise, as @Galunid said, switch to PDF : highlights are baked in there
(for better and for worse...).

**Comment by NiLuJe** [comment]
Also, minor nitpick: there's a large difference between proprietary and
custom.

Notes and highlights use a custom format, not a proprietary one.

On the other hand, if you're aware of an actual standard for that kind of
thing, I'm all ears ;).

**Comment by WolfgangDpunkt** [comment]
Many thanks for your patience and your clarifications!

> But... ePub *is* (X) HTML o_O.

Yes, it is. And Zotero & co can certainly include the EPUB, but what good is that?
Because the EPUB/XHTML does than not contain any highlights than. That means I have in (e.g.) Zotero a naked EPUB and another text document with the individual stand alone text parts (the exported highlights). What I do not have is an annotated book.
Now I have to get the "missing" context by doing fulltext searches, with each individual highlighting.
EPUB does not support highlights by default, that's what I know.
So it's great that Koreader has its own and custom solution for saving notes with EPUBs, and it is almost perfect. it's just a pity that this format saves the highlighted text parts only.

The way to convert the EPUB-book right from the start to PDF is also possible, but of course a EPUB is much better than a PDF on an e-ink-reader (on the desktop it is virtually the other way round).

**Comment by NiLuJe** [comment]
So, we've subtly gone back to "the ePub spec is useless for real-world purposes", which was kiiinda my point ;p.

----

Snark aside, I get your point, really. There just isn't a perfect solution that I can see. There's not even a good one. So, open to actual feasible ideas.

**Comment by Frenzie** [comment]
Those Readium people came out with something a few years ago. I never looked into it but it rang a vague bell.

https://web.hypothes.is/blog/epub-annotation/

**Comment by NiLuJe** [comment]
That reminds me that the big feature of Calibre 5 is going to be annotations support (besides the Py 3 port), IIRC, so, that might be worth looking into, too!

**Comment by WolfgangDpunkt** [comment]
Thanks for your understanding!
Wonderful that some people seem to be working on principle solutions to the topic of EPUB-annotations, hopefully some of it will establish itself.

For me, an quick&dirty solution would make me happy at the moment (to be able to convert a PDF copy with highlights from the EPUB+Sidecar files, inside or outside of Koreader ;-) )

**Comment by Galunid** [comment]
Not sure if it's viable option for us, but wouldn't it be possible to enclose highlight in say `span` element and add a class/style that for example underlines it? It's more out of curiosity, I'm not interested in implementing that.

**Comment by poire-z** [comment]
> wouldn't it be possible to enclose highlight in say span element

I/we'd rather not like to have to edit books :) (meaning updating a XHTML file and rebuilding the EPUB/ZIP... from crengine DOM where's the initial structure is flattened to a single DOM tree.
(And there's the fact we use hash/fingerprints of EPUBs for sync, crengine DOM cache, and it would be screwed if we edit it.)

> https://web.hypothes.is/blog/epub-annotation/

There are a few others:
http://idpf.org/epub/linking/cfi/epub-cfi.html
https://www.w3.org/TR/2017/NOTE-annotation-html-20170223/
But all that is quite new and not really widely used. So, chosing one now might not be the one that will succeed in the coming years (if any succeeds :)

> A Canonical Fragment Identifier (CFI) is a similar construct to these, but expresses a location within an EPUB Publication. For example:
`book.epub#epubcfi(/6/4[chap01ref]!/4[body01]/10[para05]/3:10)`

I guess this could be rebuild/guessed back from our internal xpointers - but I don't think it would be that straightforward...

Anyway, all these assume they would be saved in the EPUB, so they are accessible by the other software that would read that EPUB. And again, we don't want to have to edit EPUBs...

**Comment by WolfgangDpunkt** [comment]
> I/we'd rather not like to have to edit books :)

Thanks for your additions.
I agree. I also don't think that modifying the EPUB files would be a good way at this time. Especially since that alone would not suffice, there would also have to be a desktop application that could read the respective technical annotation standard.

But in my opinion, this speaks all the more for creating a copy of the file (in a different format). 
With the now already available export options this happens anyway, but it results in only a partial copy.
In my opinion, a full copy/conversion of the file including the highlights would be a practical solution with the current technology (as additional alternative export method).

Please excuse me all  for insisting on this kind of idea. But as a technical unskilled person I do not yet fully understand why it is so difficult to change/enhance the current export process. To me it sounds more like replacing only one step, instead of: 
`copy the full text, delete everything that is not highlighted in the text, add some metadata, than save the result as txt/html/json`
the process should be: 
`copy the full text, delete nothing and mark visually the text parts that were highlighted, add some metadata and than save as html/pdf or similar`

**Comment by poire-z** [comment]
> replacing only one step, instead of:
`copy the full text, delete everything that is not highlighted in the text, add some metadata, than save the result as txt/html/json`

That's not how it currently works. We don't copy the full text and delete. We just get, for each highlight, the text between 2 xpaths (`/body/div/p[1]/text[45] ... /body/div/p[2]/text[13]`), and save this small text in the small `book.sdr/metadata.epub.lua`. We can update this incrementally when we add highlights.

> the process should be:
 `copy the full text, delete nothing and mark visually the text parts that were highlighted, add some metadata and than save as html/pdf or similar`

`copy the full text` might generate a 10 MB HTML file, that we'd have to re-generate for each highlight you add.
So, that won't do as a replacement for what we have.

This could only be an export option that the user would trigger when he wants it, that might take a few minutes to generate the single HTML file copy of the book. You would lose images, and possibly the whole CSS styling (as re-applying the correct styles would be some huge unrelated work).

So, that's quite a new feature that would need a bit of work, for some very edgy use case, and a quite poor result (you read your nice EPUB, export a huge HTML file that may make your web browser slow at rendering it, without much way of navigating the document, no TOC, no bookmark list - oh, you want a TOC and bookmark list, ok :) some even more work to generate an extended HTML file :/

(And you can't even easily generate wrapping/balanced containers for highlights in the resulting HTML: we can have overlapping highlights that we can draw easily - but not so easily if we want to wrap them in the resulting HTML.)

**Comment by WolfgangDpunkt** [comment]
> So, that's quite a new feature that would need a bit of work, for some very edgy use case, and a quite poor result

Thank you very much for your effort to explain the necessary complexity. Now I understand it better.
I still hope that a good solution will be found.

**Comment by poire-z** [comment]
I guess your best bet is calibre (I know nothing much about it), which is a good tool to read EPUBs on a computer.
See what kind/format of external annotations it does (or will) support, and we might save our highlight into that format (and may be transfer them via the calibre plugin?)
