### ISSUE TITLE
bad formating text with epub.css vs html5.css

### ISSUE THREAD

**Issue by tartanpion** [koreader/koreader#6654]
* KOReader version:v2020.08.1-66-ge0546d0_2020-09-12/
* Device:kobo libra

#### Issue
Misalignment of the separator (three  triangular stars) with epub.css, but not with html5.css.
[foo.zip](https://github.com/koreader/koreader/files/5214935/foo.zip)

**Comment by poire-z** [comment]
That's not really an issue: html5.css is there just for that, for books that expect a base stylesheet like web browsers have.
epub.css is there mostly for unstyled books, and might make styled books more readable (with html5.css, you wouldn't have text indentation in paragraph and neither text justification, and you would have spacing between paragraphs).
Details and discussion in https://github.com/koreader/crengine/issues/294 and https://github.com/koreader/crengine/pull/300

In that book, a `<p class=sep>*<br/>*_____*</p>` ( `_` being no-break-spaces), with `sep` specifying `text-align: center` but no `text-indent: 0`,  will have the first line text-indented by our default of `P { text-indent: 1.2em}`, so pushed to the right:
<kbd>![image](https://user-images.githubusercontent.com/24273478/93026622-a617c100-f607-11ea-9e23-e6ff8580e0a0.png)</kbd>

With html5.css, P don't get any text-indent, so it works as the publisher and you expect it to.

**Comment by poire-z** [comment]
@mergen3107 : the solution for the user at https://www.mobileread.com/forums/showthread.php?t=349549 is probably to switch `Style > HTML / EPUB` to `HTML5`.
Reason explained above and also at https://github.com/koreader/koreader/issues/9476#issuecomment-1236443852 and https://github.com/koreader/koreader/issues/8063#issuecomment-903330829.

@offset-torque : may be this deserves a paragraph in the user guide ?

**Comment by mergen3107** [comment]
@poire-z 
Thank you! I let them know

**Comment by offset-torque** [comment]
> may be this deserves a paragraph in the user guide ?

Definitely. I will have a look at the linked discussions to understand it better and add this info to the guide.

**Comment by poire-z** [comment]
@Jellby : the solution for the user at https://www.mobileread.com/forums/showthread.php?t=352080 is probably to switch `Style > HTML / EPUB` to `HTML5`.
Reason explained above and also at https://github.com/koreader/koreader/issues/9476#issuecomment-1236443852 and https://github.com/koreader/koreader/issues/8063#issuecomment-903330829.

(Copied & pasted from above :)

**Comment by offset-torque** [comment]
@poire-z 
I just noticed that this info is not in the guide. It was in my to-do list but I thought it was an unimportant note I took while browsing the issues. I forgot that it was a request, sorry for this. 

**Now I skimmed the linked discussions and...**
In some cases switching the style to HTML5 fixes problems like the Drop Caps (linked) or misaligned separators (here). What can we say about this to the users. How can I generalize this advice ?

 **"If your text doesn't look ok, try switching the style"** is very broad and probably won't be very helpful. Basically in which situations (or symptoms) they can try tthis solution ?

**Comment by poire-z** [comment]
It's mostly always text-indent'ation issues, causing miscentering, so this single sentence:

_If you get miscentered titles, headings or separators, or unexpected text indentation, try switching Style epub.css to html5.css._

Then, if you want to elaborate, you could pick bits from these parts of my previous answers (sorry, not really in the mood to do this authoring job of merging ideas in a short comprehensible paragraphs):

_html5.css is there just for that, for books that expect a base stylesheet like web browsers have.
epub.css is there mostly for unstyled books, and might make styled books more readable (with html5.css, you wouldn't have text indentation in paragraph and neither text justification, and you would have spacing between paragraphs)._

_Styles > epub.css is our book-oriented User-Agent stylesheet, with text-align: justify, text-indent on P.
Styles > html5.css is like what most browsers do, text-align: left, no text-indent on P, spacing between P. As browsers do per default, but not really pretty when publishers has done no styling (or for home made EPUBs or viewing HTML files saved-as on browsers)._

_Some publishers assume their books will only be read on web browser engines based readers, so they don't bother "resetting" the styles, and this happens._
