### ISSUE TITLE
PB626: Not able to control frontlight if Koreader is started without frontlight

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#6655]
* KOReader version: v2020.08.1-60-g051c8c0_2020-09-07 
* Device: Pocketbook 626 sw: U626.5.20.1157

#### Issue
Not able to control frontlight. It can not be switched ON if Koreader was started with frontlight OFF. If the frontlight is ON during Koreader start, everything is functional.

#### Steps to reproduce
1. switch OFF frontlight on device
2. start Koreader
3. navigate to menu settings - frontlight
4. try to change to min, max or toggle > nothing happens

##### `crash.log` 
[crash_20200915_143214_frontlight_issue.log](https://github.com/koreader/koreader/files/5224865/crash_20200915_143214_frontlight_issue.log)

**Comment by pazos** [comment]
Probably [SwitchFrontlightState](https://github.com/koreader/koreader-base/blob/248291cbab7f0363e6212b14c36ecb99363eb947/ffi/inkview_h.lua#L1443), but I didn't test and I'm fine with current behaviour. Pinging @ezdiy.

**Comment by sonix-github** [comment]
I confirm, that it is now functional. @ezdiy Thanks for the quick fix :+1:
