### ISSUE TITLE
Unable to build "kodev release macos"

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#6668]
* KOReader version: 2020.09
* Device: macos desktop, Xcode 11.7, macOS 10.15.6

#### Issue

I get the following error when running

export PATH="/usr/local/opt/gettext/bin:${PATH}"
export PATH="/usr/local/bin:/usr/local/sbin:${PATH/:\/usr\/local\/bin/}"
export MACOSX_DEPLOYMENT_TARGET=10.14
./kodev release macos"

Making all in doc
xmlto: /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/giffix.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
xmlto: /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifecho.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
xmlto: /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifclrmp.xml does not validate (status 3)
xmlto: /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gif2rgb.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
/Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifecho.xml:4: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
   "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" []>
                                                                 ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifecho.xml does not validate
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookI/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
/Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/giffix.xml:4: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
   "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" []>
                                                                 ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/giffix.xml does not validate
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
/Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gif2rgb.xml:4: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
   "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" []>
                                                                 ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gif2rgb.xml does not validate
xmlto: /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifbuild.xml does not validate (status 3)
x.dtd
/Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifclrmp.xml:4: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
   "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" []>
                                                                 ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifclrmp.xml does not validate
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
/Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifbuild.xml:6: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
]>
  ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd"
Document /Users/jasonbenwell/koreader/base/thirdparty/giflib/build/x86_64-apple-darwin19.6.0/giflib-prefix/src/giflib/doc/gifbuild.xml does not validate
make[7]: *** [giffix.1] Error 13

#### Steps to reproduce

Attempt to clone and build per instructions

Attached is a log of the entire build
[build koreadfer failed.txt](https://github.com/koreader/koreader/files/5239960/build.koreadfer.failed.txt)

**Comment by JasonInOttawa** [comment]
Please ignore the " in the kodev release macos

**Comment by NiLuJe** [comment]
That simply looks like `xmlto` is failing to access `http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd`, for some reason?

Network issues? Weird network setup?

On the other hand, we don't care about docs, so you can also probably just disable docs in the configure args.

**Comment by JasonInOttawa** [comment]
Thank you. I did try multiple times with the same result. 

I've got a laptop connecting directly to a modem and then off to the internet. Pretty simple hookup :)

How can I disable docs?
