### ISSUE TITLE
Kobo ClaraHD Crash every time I plug the usb cable and click OK to enable usb

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6670]
* KOReader version: 2020.09
* Device: Kobo ClaraHD

#### Issue
Kobo ClaraHD Crash every time I plug the usb cable and click OK to enable usb
![IMG_4886](https://user-images.githubusercontent.com/46492291/93542980-f9ce3580-f98c-11ea-9099-7bdaec24025b.jpg)

#### Steps to reproduce
1. Plug the usb cable to ClaraHD
2. A dialog prompt to ask if you want to enable usb
3. Click OK
4. Crash

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by NiLuJe** [comment]
The release notes specifically mention that you'll need to fully **exit** KOreader after the update for USBMS to behave ;).
