### ISSUE TITLE
Kobo ClaraHD crash every time when plug the usb cable and click ok to enable usb

### ISSUE THREAD

**Issue by kingo132** [koreader/koreader#6671]
* KOReader version: 2020.v09
* Device: Kobo ClaraHD

#### Issue
Kobo ClaraHD crash every time when plug the usb cable and click ok to enable usb
![IMG_4886](https://user-images.githubusercontent.com/46492291/93543554-73b2ee80-f98e-11ea-8601-9601d259bbe0.jpg)

#### Steps to reproduce
1. Plug the usb cable to ClaraHD
2. A dialog will prompt to ask if want to enable usb
3. Click OK
4. Crash

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/5242749/crash.log)

**Comment by NiLuJe** [comment]
Dupe of #6670
