### ISSUE TITLE
Unable to use the dictionary app installed from Google Play

### ISSUE THREAD

**Issue by PotoTan** [koreader/koreader#6673]
* KOReader version:v2020.09
* Device:oneplus 3
OS: Android Pie, api 28

#### Issue
Unable to use the dictionary app installed from Google Play

I have eudic installed on my phone from Google Play, which is an external dictionary supported by Koreader, but eudic is not recognized by Koreader.

I uninstalled the Google Play version of eudic and got the .apk of eudic from the official website, and it is recognized by Koreader.

eudic on Google Play Store:
https://play.google.com/store/apps/details?id=com.qianyan.eudic&hl=en_US

#### Steps to reproduce
Unable to use the dictionary app installed from Google Play

I have eudic installed on my phone from Google Play, which is an external dictionary supported by Koreader, but eudic is not recognized by Koreader.

I uninstalled the Google Play version of eudic and got the .apk of eudic from the official website, and it is recognized by Koreader.

eudic on Google Play Store:
https://play.google.com/store/apps/details?id=com.qianyan.eudic&hl=en_US

#### Screenshot
https://i.loli.net/2020/09/18/qTYVHLZO3I4vAoy.jpg
https://i.loli.net/2020/09/18/7UhVb4CpEd2AZ8m.jpg

**Comment by Frenzie** [comment]
It might suffice to duplicate this line with com.qianyan.eudic instead of com.eusoft.eudic. 
https://github.com/koreader/koreader/blob/99045b431104904d3391a3d5ed01566356f76c24/frontend/device/android/device.lua#L56
