### ISSUE TITLE
Screensaver not loading on reMarkable: Requires extra button press

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6676]
* KOReader version: 2020.09
* Device: reMarkable 1

#### Issue
Power button suspends the device – but does not show the screensaver until one of the three main buttons is pressed

#### Steps to reproduce
1. Open epub/pdf file
2. Press power button
3. Screensaver does not load
4. Press either the left, middle or right button
5. Screensaver loads

### Additional information
For some strange reason it behaves correctly with pdf files but only if you suspend the device from the file browser/main screen:
1. Open pdf file
2. Press middle button
3. Press power button
4. Screensaver loads successfully

**Comment by Eeems** [comment]
I'm not able to replicate this on my own device. That said, I do have a service running that grabs button input before anything starts and then is only passing through press events when they aren't long presses.

**Comment by gabyhk** [comment]
@Eeems Is that service included in the latest release or do you have a custom build? Are there any other benefits of running that service?

**Comment by Eeems** [comment]
@gabyhk It's not a KOReader service, and I'm not convinced it's what's keeping you from seeing the message. As for if there are any benefits, yes but it doesn't play nicely with KOReader yet: https://github.com/Eeems/oxide/issues/69

**Comment by gabyhk** [comment]
@Eeems I am out of ideas at this point then. I thought it would be an easy fix, but apparently it isn't as reproducible as I assumed. Thank you for looking into it nonetheless!

**Comment by Eeems** [comment]
@gabyhk I'll ask on the reMarkable community discord to see if anybody else can replicate.

**Comment by gabyhk** [comment]
@Eeems I just made a little discovery! If I comment out `os.execute("systemctl suspend")` from here:

https://github.com/koreader/koreader/blob/2e731dd4ddc55711734cca3759f3a72d3747787b/frontend/device/remarkable/device.lua#L113-L115

then the screensaver loads as expected every single time! Somehow that `suspend` command fails to execute and keeps it from going to the next action which triggers the screensaver. This has to be related to https://github.com/koreader/koreader/issues/6028

**Comment by Eeems** [comment]
So it might be a timing issue, I guess KOReader might draw the image after calling the suspend command? On my device that works though.

**Comment by gabyhk** [comment]
@Eeems It seems like that is the case. I really don't know why my particular device (RM102) would be the only one afflicted by this. I did a factory reset (FW 2.3.0.16) and reinstalled KOReader from zero twice and the problem never went away… until I commented out that line.

**Comment by Eeems** [comment]
What's the output of `cat /sys/devices/soc0/machine` on your device? We've noticed some strange things about what different models say they actually are in https://github.com/Eeems/oxide/issues/48#issuecomment-698103622

**Comment by gabyhk** [comment]
@Eeems It says simply `reMarkable 1.0`

**Comment by Eeems** [comment]
@LinusCDE Can you replicate @gabyhk's issue on your device since it also reports as `reMarkable 1.0`? I might be the odd one out with `reMarkable prototype 1`

**Comment by NiLuJe** [comment]
Timing might actually be key here.

On Kobo, we delay actual suspension by 15s. What you're actually reading might play a role, too, assuming you're showing the cover on suspension (e.g., getting the cover from a PDF might be faster than from an ePub).

https://github.com/koreader/koreader/blob/f0f0cfd1679800e6df8c550817a7a5c37e1e6f09/frontend/device/generic/device.lua#L26-L28

https://github.com/koreader/koreader/blob/f0f0cfd1679800e6df8c550817a7a5c37e1e6f09/frontend/device/generic/device.lua#L307

**Comment by Eeems** [comment]
> 
> 
> Timing might actually be key here.
> 
> On Kobo, we delay actual suspension by 15s. What you're actually reading might play a role, too, assuming you're showing the cover on suspension (e.g., getting the cover from a PDF might be faster than from an ePub).

Any reason the logic can't just wait for the screen to update before starting the system suspend?

**Comment by NiLuJe** [comment]
It's a full-screen, flashing update, so, assuming the kernel implements MXCFB_WAIT_FOR_UPDATE_COMPLETE properly, it already does, technically.

That hasn't stopped devices form doing weird and wonderful crap on their own later on that'd bork suspend nonetheless ;).

(Similarly, we stop reading input during the whole process).

**Comment by gabyhk** [comment]
> What you're actually reading might play a role, too, assuming you're showing the cover on suspension (e.g., getting the cover from a PDF might be faster than from an ePub).

I think I noticed that it worked once or twice when loading the cover of PDFs in the past. After commenting out that line though, it works as it should. I even added a line to disable wifi within the `Remarkable:suspend()` function and it works perfectly.

**Comment by Eeems** [comment]
> 
> 
> > What you're actually reading might play a role, too, assuming you're showing the cover on suspension (e.g., getting the cover from a PDF might be faster than from an ePub).
> 
> I think I noticed that it worked once or twice when loading the cover of PDFs in the past. After commenting out that line though, it works as it should regardless of the filetype. I even added a line to disable wifi within the `Remarkable:suspend()` function and it works perfectly.

It'll work 100% because it'll never suspend. You commented out the line that actually suspends the device, which means that power usage will be rather high due to the only thing being disabled is wifi.

**Comment by gabyhk** [comment]
I was just about to edit my comment and add that about power consumption… I guess we're back to square one

**Comment by LinusCDE** [comment]
@Eeems I was not able to replicate that. I tried it with an opened epub. Koreader is `2020.09-2` (remarkable opkg).

Remux worked fine, no launcher and oxide only had a messed up stock sleep screen (probably due to changed dpi). But it seemed to work all the time.

**Comment by LinusCDE** [comment]
My guess would be that it's some specific launcher that causes this. @gabyhk did you use any particular launcher to launch it? I guess you're using the latest koreader dist from toltec (opkg repo) as well.

Also curious that you have a `remarkable 1.0` with a `RM-102` model. For me it's a `reMarkable 1.0` with model `RM-100`. Busts the myth for me that model and `soc0/name` are not related at all. The weird numbering (was out of order for some) seemed weird to me anyway.

**Comment by LinusCDE** [comment]
Though does KOReader have an option to set an image as screensaver? If yes, I'll have to retry it since I kept my KOReader nearly stock with no changed settings.

**Comment by gabyhk** [comment]
@LinusCDE I am not using any launcher. I have a timer service that loads koreader automatically. Here is my setup https://github.com/koreader/koreader/issues/6688

> Though does KOReader have an option to set an image as screensaver? If yes, I'll have to retry it since I kept my KOReader nearly stock with no changed settings.

Yes, it does. Gear icon > screen > screensaver

**Comment by Eeems** [comment]
> 
> ...  oxide only had a messed up stock sleep screen (probably due to changed dpi). But it seemed to work all the time.

@LinusCDE There are instructions for working around the DPI issues in oxide. That said, since oxide handles the suspend screen itself, it's not really a good test case for this.

**Comment by LinusCDE** [comment]
Using the option "Use last book's cover as screensaver" on a ebook that has one, I can confirm @gabyhk's bug. I also killed all launchers and started koreader from the command line which should be similar to his setup.

As far as I can gather in this threads the devices are:

User                 | `/sys/devices/soc0/machine` | Model
--------------- | ---------------------------- | --------
Eeems              | reMarkable prototype 1        | RM102
gabyhk             | reMarkable 1.0                     | RM102
LinusCDE (me)  | reMarkable 1.0                     | RM100

Would be interesting to know what version affects what on the devices specifically. But this one seems to be dictated by beeing `reMarkable 1.0`.

**Comment by LinusCDE** [comment]
Not sure if that helps, but here is a strace -f of koreader where I:
- Get the files of `/home/root` shown.
- Go into `/home/root/plato-media/` on page 2
- Click on `Scholar of Magic` (an epub)
- Press the power button (nothing happens)
- Press the left button (cover appears)
- Press the power button again (cover disappears)
- Exit koreader using the top menu


[strace_koreader.log](https://github.com/koreader/koreader/files/5302334/strace_koreader.log)

**Comment by Eeems** [comment]
I've now tested with "Use last book's cover as screensaver" enabled, on a book that has a cover and can confirm this issue on my device as well. It looks like it's not drawing to the screen until after the resume finishes, which leads me to believe that it's not starting drawing until after calling `systemctl suspend`

**Comment by NiLuJe** [comment]
Would possibly be more helpful, and decoded MXCFB ioctrls ;)

I have [a strace build for rM](http://files.ak-team.com/niluje/mrpub/Other/strace-remarkable.tar.gz) that will.

`strace -fittv -e trace ioctl,process` should be more than enough to filter the cruft out ;).

**Comment by LinusCDE** [comment]
Nice idea @NiLuJe. I get a 404 on your file though.

**Comment by LinusCDE** [comment]
Never mind. Https seems to be a different (v)host.

**Comment by NiLuJe** [comment]
Yeah, I don't serve static content over HTTPS, only SVN ;).

**Comment by LinusCDE** [comment]
[strace_koreader2.log](https://github.com/koreader/koreader/files/5302365/strace_koreader2.log)

Same actions as above. The file is really a lot cleaner.

Seems to be as @Eeems suggested.

**Comment by NiLuJe** [comment]
Yeah, I double-checked on a Kobo, the refresh is done on the next UIManager tick at the earliest, which makes sense.

**Comment by NiLuJe** [comment]
The easiest solution is probably to switch to using the `PowerEvent` handler like on Kobo & co.

The original Kindle special-snowflake made sense because KOReader isn't the one doing the suspend there.

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/device/generic/device.lua b/frontend/device/generic/device.lua
index d0c27272..bbb324fb 100644
--- a/frontend/device/generic/device.lua
+++ b/frontend/device/generic/device.lua
@@ -217,7 +217,7 @@ function Device:rescheduleSuspend()
     UIManager:scheduleIn(self.suspend_wait_timeout, self.suspend)
 end
 
--- ONLY used for Kobo and PocketBook devices
+-- Only used on platforms where we handle suspend ourselves.
 function Device:onPowerEvent(ev)
     if self.screen_saver_mode then
         if ev == "Power" or ev == "Resume" then
@@ -228,10 +228,12 @@ function Device:onPowerEvent(ev)
                 logger.dbg("Resuming...")
                 local UIManager = require("ui/uimanager")
                 UIManager:unschedule(self.suspend)
-                local network_manager = require("ui/network/manager")
-                if network_manager.wifi_was_on and G_reader_settings:isTrue("auto_restore_wifi") then
-                    network_manager:restoreWifiAsync()
-                    network_manager:scheduleConnectivityCheck()
+                if self:hasWifiManager() and not self:isEmulator() then
+                    local network_manager = require("ui/network/manager")
+                    if network_manager.wifi_was_on and G_reader_settings:isTrue("auto_restore_wifi") then
+                        network_manager:restoreWifiAsync()
+                        network_manager:scheduleConnectivityCheck()
+                    end
                 end
                 self:resume()
                 -- Restore to previous rotation mode, if need be.
@@ -294,15 +296,18 @@ function Device:onPowerEvent(ev)
         end
         self.screen_saver_mode = true
         UIManager:scheduleIn(0.1, function()
-          local network_manager = require("ui/network/manager")
-          -- NOTE: wifi_was_on does not necessarily mean that Wi-Fi is *currently* on! It means *we* enabled it.
-          --       This is critical on Kobos (c.f., #3936), where it might still be on from KSM or Nickel,
-          --       without us being aware of it (i.e., wifi_was_on still unset or false),
-          --       because suspend will at best fail, and at worst deadlock the system if Wi-Fi is on,
-          --       regardless of who enabled it!
-          if network_manager:isWifiOn() then
-              network_manager:releaseIP()
-              network_manager:turnOffWifi()
+          -- NOTE: This side of the check needs to be laxer, some platforms can handle Wi-Fi without WifiManager ;).
+          if self:hasWifiToggle() then
+            local network_manager = require("ui/network/manager")
+            -- NOTE: wifi_was_on does not necessarily mean that Wi-Fi is *currently* on! It means *we* enabled it.
+            --       This is critical on Kobos (c.f., #3936), where it might still be on from KSM or Nickel,
+            --       without us being aware of it (i.e., wifi_was_on still unset or false),
+            --       because suspend will at best fail, and at worst deadlock the system if Wi-Fi is on,
+            --       regardless of who enabled it!
+            if network_manager:isWifiOn() then
+                network_manager:releaseIP()
+                network_manager:turnOffWifi()
+            end
           end
           UIManager:scheduleIn(self.suspend_wait_timeout, self.suspend)
         end)
diff --git a/frontend/device/remarkable/device.lua b/frontend/device/remarkable/device.lua
index 25548711..fbe7bf6c 100644
--- a/frontend/device/remarkable/device.lua
+++ b/frontend/device/remarkable/device.lua
@@ -8,6 +8,7 @@ local Remarkable = Generic:new{
     model = "reMarkable",
     isRemarkable = yes,
     hasKeys = yes,
+    needsScreenRefreshAfterResume = no,
     hasOTAUpdates = yes,
     canReboot = yes,
     canPowerOff = yes,
@@ -92,24 +93,6 @@ function Remarkable:setDateTime(year, month, day, hour, min, sec)
     return os.execute(command) == 0
 end
 
-function Remarkable:intoScreenSaver()
-    local Screensaver = require("ui/screensaver")
-    if self.screen_saver_mode == false then
-        Screensaver:show()
-    end
-    self.powerd:beforeSuspend()
-    self.screen_saver_mode = true
-end
-
-function Remarkable:outofScreenSaver()
-    if self.screen_saver_mode == true then
-        local Screensaver = require("ui/screensaver")
-        Screensaver:close()
-    end
-    self.powerd:afterResume()
-    self.screen_saver_mode = false
-end
-
 function Remarkable:suspend()
     os.execute("systemctl suspend")
 end
diff --git a/frontend/ui/uimanager.lua b/frontend/ui/uimanager.lua
index 04b8b2d1..070a3198 100644
--- a/frontend/ui/uimanager.lua
+++ b/frontend/ui/uimanager.lua
@@ -213,6 +213,14 @@ function UIManager:init()
             self:_afterNotCharging()
         end
     elseif Device:isRemarkable() then
+        self.event_handlers["Suspend"] = function()
+            self:_beforeSuspend()
+            Device:onPowerEvent("Suspend")
+        end
+        self.event_handlers["Resume"] = function()
+            Device:onPowerEvent("Resume")
+            self:_afterResume()
+        end
         self.event_handlers["PowerPress"] = function()
             UIManager:scheduleIn(2, self.poweroff_action)
         end
@@ -227,16 +235,6 @@ function UIManager:init()
                 end
             end
         end
-        self.event_handlers["Suspend"] = function()
-            self:_beforeSuspend()
-            Device:intoScreenSaver()
-            Device:suspend()
-        end
-        self.event_handlers["Resume"] = function()
-            Device:resume()
-            Device:outofScreenSaver()
-            self:_afterResume()
-        end
         self.event_handlers["__default__"] = function(input_event)
             -- Same as in Kobo: we want to ignore keys during suspension
             if not Device.screen_saver_mode then
```

Ought to do it?

**Comment by NiLuJe** [comment]
I'll PR that if you can confirm that I didn't horribly break anything ;p.

(At least it still works on Kobo ;p).

**Comment by Eeems** [comment]
I'll try to take some time to test this week.

**Comment by gbyl** [comment]
@NiLuJe I was wondering… has this been merged to the main branch already?

**Comment by pazos** [comment]
nope. nobody tested the patch here :/

**Comment by Eeems** [comment]
Sorry, work has been crazy busy for me so I haven't had a chance to test.

**Comment by gbyl** [comment]
@pazos how would one go about implementing the changes? do I have to manually go file by file replacing lines or is there a git command that I should be using?

**Comment by NiLuJe** [comment]
It's a diff, so stick the code block in a text file, put it in the root of your tree, `patch -p1 < file`, and Bob's your uncle ;). Then push the updated file to your device.

**Comment by gbyl** [comment]
@NiLuJe It works like a charm! Thank you so much! Please go ahead and submit the PR.
