### ISSUE TITLE
Wi-Fi / Network Manager not implemented on reMarkable

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6677]
* KOReader version: 2020.09
* Device: reMarkable 1

#### Issue
The following toggle does not work on the reMarkable port:
Gear Icon > Network > Wi-Fi connection

#### Workaround
Switching the Wi-Fi on and off is essential to preserve battery life. Thus, I find myself running these complementary pairs of lines often:
`ifconfig wlan0 down`
`ifconfig wlan0 up`
Or:
`iwconfig wlan0 txpower off`
`rfkill unblock wifi`

While the above lines disable/enable Wi-Fi, I am not sure they are all that is needed to preserve battery life. As a beginner, I have not been able to integrate them into a toggle script, let alone add them in any meaningful way to the interface.

**Comment by Eeems** [comment]
The built-in application (xochitl) uses wpa_supplicant to control the wifi connection. I haven't done a ton of digging into how it handles turning it off, but all I've been doing for disabling wifi has been `ifconfig wlan0 down` (https://github.com/Eeems/oxide/blob/master/applications/system-service/wlan.h#L26). I haven't done any experimentation around battery impact versus when xochitl disables wifi though.

**Comment by pazos** [comment]
@gabyhk @Eeems: Yup, wifi was left unimplemented. It should work with little changes.

Have a look at https://github.com/koreader/koreader/blob/master/frontend/device/cervantes/device.lua#L224-L255 and the helper scripts in https://github.com/koreader/koreader/tree/master/platform/cervantes.

I would suggest using the cervantes as a template if you want to split network management between xochitl and KOReader. If you want to repurpose the wpa_supplicant daemon run by xochitl you can use kobo as the template.

On kobos wifi stays alive between Nickel -> KO and killed before running Nickel again
On cervantes wifi is killed between QBookApp -> KO and killed again at exit.

**Comment by Eeems** [comment]
I've also been doing a lot of work in my own project for using the networks that xochitl has stored when dealing with wifi: https://github.com/Eeems/oxide/blob/master/applications/system-service/wifiapi.h#L560-L602

It might make sense to leverage some of that work.

**Comment by gabyhk** [comment]
@pazos @Eeems I might not be the right person to implement those changes due to a lack of expertise, but I certainly appreciate both your comments pointing me in the right direction!

**Comment by pazos** [comment]
> I've also been doing a lot of work in my own project for using the networks that xochitl has stored when dealing with wifi: https://github.com/Eeems/oxide/blob/master/applications/system-service/wifiapi.h#L560-L602
> 
> It might make sense to leverage some of that work.

Of course, feel free to improve the ReMarkable port :).

We cannot keep Qt as a dependency, so you'll need to ship a binary or a shared library as part of oxide.
Setup network manager if oxide is installed, otherwise fallback to standalone wpa_supplicant.

It is totally cool to implement stuff that require oxide to work as long as oxide is not mandatory for the program to run :+1:

**Comment by Eeems** [comment]
>
> Of course, feel free to improve the ReMarkable port :).
> 
> We cannot keep Qt as a dependency, so you'll need to ship a binary or a shared library as part of oxide.
> Setup network manager if oxide is installed
> 
> It is totally cool to implement stuff that require oxide to work as long as oxide is not mandatory for the program to run +1
> In the specific case of network I would fallback to standalone wpa_supplicant if oxide is not present.

I've already got a command line tool that could be used to interact with oxide. I'll do a little poking around tonight and potentially open a PR.

**Comment by snelg** [comment]
Discovered a quirk that might be specific to the reMarkable 2.

Short version: `systemctl suspend` breaks wifi

Solution: `rmmod brcmfmac` before suspend, and corresponding `modprobe brcmfmac` after resume.
(I'm almost certain that's what xochitl does on suspension)

Long version:
I have slightly-hacky wifi working on my rm2, using a manually-generated config file and `systemctl start wpa_supplicant@wlan0`
It was working fine, but the connection was failing any time after I first suspended and then resumed the device. And once it was broken, I had to do a full reboot to get it working again.

After realizing the failures were connected to suspension, I deactivated koreader and went back to factory-baseline xochitl. I re-created the problem via USB ssh and manually calling `systemctl suspend`. After resuming from that manual call, even xochitl couldn't connect to wifi.

I compared `dmesg` output from a manual `suspend` call versus simply pressing the physical Power button with xochitl running.
The outputs were mostly the same, but I noticed that the physical button press had a couple of lines involving `brcmfmac` at the start:

```
PHYSICAL BUTTON PRESS
[  302.132639] brcmfmac: brcmf_fil_cmd_data: bus is down. we have nothing to do.
[  302.139806] brcmfmac: brcmf_cfg80211_get_channel: chanspec failed (-5)
[  302.431275] PM: suspend entry (deep)
[  302.431286] PM: Syncing filesystems ... done.
```

```
MANUAL SUSPEND CALL
[ 370.607573] PM: suspend entry (deep)
[ 370.607584] PM: Syncing filesystems ... done.
```

After even more digging (and googling "brcmfmac suspend"), I found that running `rmmod brcmfmac` generates those same two `dmesg` lines I see in the physical button press output.
So fully removing the `brcmfmac` module on suspend, and then re-loading it on resume fixed my issues.

**Comment by Eeems** [comment]
@snelg https://github.com/Eeems/oxide/issues/113

Long story short, just call `rmmod brcmfmac` before suspending and then call `modprobe brcmfmac` on resume. Which is what you already discovered. I think I'm going to add a package to toltec that will automatically solve this issue for everyone on an rM2 instead of requiring every app to resolve it themselves.

**Comment by snelg** [comment]
Yyyyyep, finding that oxide issue would have saved me some time :)

**Comment by Eeems** [comment]
@snelg https://github.com/toltec-dev/toltec/pull/183 if you are willing to help test. I don't have a rM2 so I'm doing this all semi-blind.

**Comment by snelg** [comment]
Sure. I'll test it a bit later.

**Comment by snelg** [comment]
@Eeems Works great.

Related note: I'm not sure about the wifi chip's power consumption in its various states.
When you (re-)add the module with `modprobe brcmfmac`, it unsurprisingly always starts in the same state:
```
> iwconfig

wlan0     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
```

If you then run `ifconfig wlan0 down`, then the `iwconfig` output changes slightly to
```
wlan0     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
```
i.e. it removes the "Tx-Power=31 dBm" bit.

Like I said, I don't know how that does or doesn't affect its actual power consumption.

I also don't know if `rmmod brcmfmac` by itself powers off the chip. I don't even know if it's *normally* powered off during suspend, even without `rmmod`.

So for koreader on my own device, I copied the ideas from platform/cervantes and do a full teardown on "turnOffWifi" (and before suspend):
```
killall wpa_supplicant 2>/dev/null
ifconfig wlan0 down 2>/dev/null
rmmod brcmfmac 2>/dev/null
```
and then a corresponding full rebuild on "turnOnWifi":
```
if ! lsmod | grep -q brcmfmac; then
    modprobe brcmfmac
    sleep 1
fi

ifconfig wlan0 up
sleep 1

wpa_supplicant -i wlan0 -C /var/run/wpa_supplicant -B 2>/dev/null
```

Possibly overkill, but it works for me :)

**Comment by Eeems** [comment]
I'll have to confirm what xochitl does. My understanding is that it just removes and reinserts the module. Since I don't have a rM2 I can't validate that though.

**Comment by snelg** [comment]
Based on `dmesg` output, I'm also 99% certain that xochitl simply removes and reinserts the module.

My typically-overlong "note" above is more of a tangent :)
While trying to figure out the problem in the first place, one of the threads I skimmed was https://github.com/koreader/koreader/issues/6028 , about battery life. So it's been on my mind.
Testing something like that is inherently slow, though, since I can't watch the battery drain in realtime.

**Comment by Eeems** [comment]
Please let me know whatever you find out.

**Comment by snelg** [comment]
A few more little details about xochitl's wifi behavior on rm2:

Switching wifi off in the UI does `ifconfig wlan0 down`, or its equivalent.
After switching it off in the UI, the `wlan0` entry is gone from `ifconfig`, and `iwconfig` confirms that the `Tx-Power=31 dBm` is removed from the `wlan0` entry.

But xochitl also has the same behavior I described in my tangent.

 - turned wifi off in UI
 - verified no `wlan0` entry in `ifconfig`, and no `Tx-Power` value in `iwconfig`
 - clicked power button to suspend
 - waited at least 15 seconds (until after laptop did the "USB device removed" chime)
 - clicked power button to wake up
 - `ifconfig` now has `wlan0` entry and `iwconfig` has `Tx-Power`, even though UI still shows "wifi off"

That's further evidence that regardless of whether the wifi is off or on in the UI, whenever xochtil does a suspend/wakeup it removes and re-adds the brcmfmac module.
And re-adding the module always puts it `wlan0` in an `up` state, even if it was `down` before the module was removed. Not surprising, but good to verify.

Time to put on my QA hat and figure out the cleanest long-term tests for battery consumption in different states.

**Comment by Eeems** [comment]
Sounds like we might want to also submit an issue to reMarkable if this does increase power consumption.

**Comment by snelg** [comment]
I'm running one test overnight each day, starting at 100% battery charge each time.

Results so far:

 - **Suspended**
   - Running KOReader
   - Enabled Wifi
   - Connected to wifi network
   - Manually ran `systemctl suspend`, not allowing koreader to run any pre-suspend code
   - 8.5 hours later: 99% battery

(Good news for rm2: unlike issue https://github.com/koreader/koreader/issues/6028, it looks like `systemctl suspend` properly turns off battery drain in suspend mode.)

 - **Wifi fully active, but not connected**, i.e. same setup as xochitl's "wifi off" but after sleep/wakeup
   - Running KOReader
   - Disabled autosuspend
   - Added brcmfmac module (`modprobe brcmfmac`)
   - Did NOT do `ifconfig wlan0 down`
   - 11.5 hours later: 60% battery

Tonight's test, currently running: `modprobe brcmfmac` AND `ifconfig wlan0 down`
Next night's planned test: `rmmod brcmfmac`
Night-after-next night's planned test: wifi fully up and connected, system left awake

**Comment by snelg** [comment]
- **Module loaded, but disabled**
   - KOReader, autosuspend disabled
   - `modprobe brcmfmac`
   - `ifconfig wlan0 down`
   - 14.5 hours later: 57% battery
 
So zero statistically-significant difference in power consumption between `ifconfig wlan0 up` and `ifconfig wlan0 down`. No need for submitting an issue to reMarkable team about that.

**Comment by Eeems** [comment]
That's good to hear!

**Comment by snelg** [comment]
- **Module unloaded**
   - KOReader, autosuspend disabled
   - `rmmod brcmfmac`
   - 13 hours later: 71% battery

Looks like unloading the wifi kernel module *does* save a bit of battery power.

**Comment by NiLuJe** [comment]
As a possibly interesting reference, on NTX boards, powering the Wi-Fi chip is indeed handled via a kernel module. Kobo has chosen to make use of that fact and will in fact power the chip down when killing Wi-Fi, while, IIRC, BQ/Cervantes chose to live with the power consumption because there were timing concerns (and/or race issues)involved with the loading/unloading.

**Comment by Frenzie** [comment]
> BQ/Cervantes chose to live with the power consumption

Whoa, on my H2O that severely cuts into battery life.

**Comment by NiLuJe** [comment]
I may be misremembering that (@pazos might remember better), but it shocked me enough that I'm hoping I remember it right. (Also, the snark around the "here, we're sleeping because NTX told us to. It's terrible, we know." :D).

**Comment by pazos** [comment]
That's what I understood from https://github.com/bq/cervantes/pull/9#issuecomment-435625257

It is barely noticeable. I would recommend the C4 without any doubt if BQ were still selling and supporting them. But BQ is gone, Cervantes is gone.

**Comment by snelg** [comment]
I initially read that as "I would recommend ***[C-4](https://en.wikipedia.org/wiki/C-4_(explosive))*** without any doubt if BQ where still selling and supporting them"

"Wow, I guess pazos REALLY doesn't like BQ for some reason..."

But I did figure out what you really meant :)

**Comment by gbyl** [comment]
@snelg Thanks for implementing the wifi manager for rm2! Any thoughts as to how we could go about adapting this for the rm1?

**Comment by Eeems** [comment]
He only implemented wifi on/off I believe, not the full manager. That said you could easily take his changes and remove the rmmod/modprobe portion and it should work on the rM1 as well

**Comment by snelg** [comment]
> He only implemented wifi on/off I believe, not the full manager.

Correct. I'm not sure which parts of my code will or will not work on the rm1, since I don't have one to test with.

**Comment by snelg** [comment]
Final power consumption test result, and summary:

 - **WiFi active and connected**
   - autosuspend disabled
   - 13.5 hours later: 58% battery

**Summary**
(the "% per hour" numbers are calculated from the original time durations; in my previous updates I rounded the hours, e.g. "13.5 hours later" instead of "13 hours, 23 minutes later")

kernel module loaded | ifconfig status | connected | % per hour
----- | ----- | ----- | -----
no | n/a | n/a | 2.25
yes | down | n/a | 2.98
yes | up | no | 2.98
yes | up | yes | 3.12

**Conclusions**
In practical terms, the battery drain simply from leaving wifi on isn't much different from leaving it off.
(Actively *using* the wifi connection would obviously use more power)

On the other hand, the time it takes to unload/re-load the kernel module is negligible, So we might as well save that small bit of power by unloading it whenever we turn off wifi.
