### ISSUE TITLE
Stuck at "reMarkable is starting" screen after shutdown from KOReader (+Workaround)

### ISSUE THREAD

**Issue by gabyhk** [koreader/koreader#6683]
* KOReader version: 2020.09
* Device: reMarkable 1 (RM102)

#### Issue
Remarkable won't boot up after being shutdown using the power button while running KOReader.

#### Steps to reproduce
1. Open KOReader
2. Hold down the power button
3. KOReader displays "Powered off"
4. KOReader exits
5. Device displays "Press the power button to get started" - "reMarkable is powered off"
6. Try to turn your device back on
7. Stuck at "reMarkable is starting"

#### PSA: Workaround
If this ever happens to you. Try:
1. Connect your device through USB to a computer
2. Run `ssh root@10.11.99.1`
3. Run `systemctl restart xochitl`

Note: This approach assumes that you either know the password (whether the auto-generated one or the one on `etc/remarkable.conf` line `DeveloperPassword=yourpasswordhere` if you ever changed it) or that you set up a passwordless ssh with `ssh-keygen` and `ssh-copy-id`.

**Comment by gabyhk** [comment]
I found a fix. SSH into your device and run:
`systemctl enable xochitl`
You should see:
`Created symlink /etc/systemd/system/multi-user.target.wants/xochitl.service → /lib/systemd/system/xochitl.service.`

Presumably something removed `xochitl.service` from `/etc/systemd/system/multi-user.target.wants/` I am not sure what caused it, but chances are it was something pertaining my device only rather than a problem with KOReader. Since there is no bug, I will be closing this issue.

**Comment by Frenzie** [comment]
Thanks. :-)

**Comment by josuevalrob** [comment]
i got this when i try to log in 

ssh root@10.11.99.1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:sT0Uf8FvLQqY0CBXbZIW96Ib9EJGr7e1i/MsPoEEPp4.
Please contact your system administrator.
Add correct host key in /Users/josue.valencia/.ssh/known_hosts to get rid of this message.
Offending RSA key in /Users/josue.valencia/.ssh/known_hosts:5
RSA host key for 10.11.99.1 has changed and you have requested strict checking.
Host key verification failed.
