### ISSUE TITLE
Upload books to koreader with Http server

### ISSUE THREAD

**Issue by videni** [koreader/koreader#6690]
Even though we can upload books to kindke via Calibre wirelessly, but it is not convenient. Can we add a http servier pulgin to Koreader, then we can upload book with any browser.

**Comment by hius07** [comment]
I am happy with KOReader built-in SSH server + any sFTP client (e.g. Chrome browser + sFTP Client plugin).

**Comment by videni** [comment]
Why SSH server?   It's more difficult  to set up, Usually  We will not enable it until we need, a http server is enough. and is there any sFTP plugin for mobile browser?

**Comment by NiLuJe** [comment]
There's arguably WebDav support in the Cloud Storage plugin, I think, which is arguably the only sensible way to do this kind of things over HTTP in the first place?

**Comment by NiLuJe** [comment]
If you *really* want to, most embedded devices ship with busybox, so, with a bit of luck, the httpd applet is baked in those. Or can be coerced in via a custom bb build.

**Comment by Frenzie** [comment]
I'd recommend using the SSH server (see [here](https://github.com/koreader/koreader/wiki/SSH) for instructions), but something like Syncthing might also be of interest. See [here](https://www.mobileread.com/forums/showpost.php?p=4007007&postcount=6). (And I'm sure you should be able to find some small or not so small HTTP server and use that.)

**Comment by hius07** [comment]
> is there any sFTP plugin for mobile browser?

Yandex browser for Android supports all Chrome plugins.

**Comment by hius07** [comment]
I'd prefer not a browser but a sFTP client, say, Total Commander plugin.

**Comment by Frenzie** [comment]
There are plenty of reasonable (S)FTP clients available on all operating systems. :-)
