### ISSUE TITLE
FR: suggestion on option of turning-off antialiasing

### ISSUE THREAD

**Issue by mbrd2019** [koreader/koreader#6697]
Device: kv  
koreader ver: 202004

To echo the similar concerning as Issue #5299 and others from mobileread,  I too would love an alternative option in koreader, that is to turn off anti-aliasing, in order to attain crisp black text (epub), at few cost of being more pixellated. 

For the now built-in option of "font hinting" works extreme slightly on the output effects of sharpness, contrasted with those by turning-off antialiasing. For I've tried and proved, with anti-aliasing disabled in kindle native sys that is font hacked. You could have the same outcome.

Not a few may have interests on this coming experience if of koreader, specially on device of 300 dpi.

Here is a stone for the buliding of koreader, and for its best. 
I appreciate for your consideration. Thks.

**Comment by poire-z** [comment]
There's already something in crengine for that, that can be tweaked by manually editing a setting in `koreader/data/cr3.ini`:
`font.antialiasing.mode=2`
Changing `2` to `0` disable antialiasing completely, while setting it to `1` only disable it for small font sizes.
Looks like you can see which bit of text are affected: contrast will have no effect on non-antialiased fonts.

Dunno if/how this should/could be integrated into KOReader UI/settings.
But please try it first and tell us if the result is exactly what you expect.

**Comment by Frenzie** [comment]
crengine actually has some _drawMonochrome boolean that seems to trigger `FT_LOAD_TARGET_MONO`, but it's not immediately obvious to me under which combination of settings that might activate (and probably not from the KOReader frontend).

**Comment by mbrd2019** [comment]
Great thanks for you both, esp poire-z's. 

Following your detailed instruction, i have the sharpness outcome expected. i cannot love it more. Wow, here is a hidden stone, one hidden treasure for me, also much hoping to broadcast at your side this trick. (btw, the cr3.ini is not in the download file, rather occurs after put in the kindle.)

Thks again.  All the best.

**Comment by poire-z** [comment]
Looking again on the emulator, and the result is quite ugly. Moreover, it changes with Hinting off/native/auto. It's a bit better with "auto" (it's bolder).
Does anti-aliasing deserve to be toggable in the UI:
- with a forced value for hinting, so "no anti-aliasing" becoming the first hinting mode (-1) and just another 1st item in the Hinting mode toggle (that would make it 5 items with short space for toggle names)
- or a new independant toggle orthogonal to hinting? (that would kill the max of 4 toggles per bottom panel)

Or it's really not needed to expose that as it's ugly, and is a niche wish, that should be fine with just editing cr3.ini?

**Comment by Frenzie** [comment]
> Looking again on the emulator, and the result is quite ugly.

The higher the DPI the less it matters of course. On my H2O it looks a bit like a less nice scan. Perfectly legible but definitely not preferable. Also a bit reminiscent of an older ~160 DPI ereader perhaps.

Given how ugly the result is I'd say it doesn't need to be exposed, but if one were so inclined I suppose there might also be a space for it somewhere in the document menu rather than at the bottom? (E.g., under font settings.)

**Comment by NiLuJe** [comment]
I suspect every request we've had about this came from CJK users, where AA/hinting is another kettle of fish entirely, and I could somewhat understand the interest in no AA there ;).

**Comment by Frenzie** [comment]
300 isn't particularly high, I implicitly meant more like 600 or at least 450. (Look at a UHD 600 DPI smartphone; that's nice & sharp.)

**Comment by jonnyl2** [comment]
Besides the CRE setting mentioned by @poire-z above, is there also a way to turn off anti-aliasing for KOReader UI elements? 
Not important, just really curious how it would look like.
