### ISSUE TITLE
Rotation switches Night Mode off on Android

### ISSUE THREAD

**Issue by RueleuR** [koreader/koreader#6703]
* KOReader version: 2020.09
* Device: Tolino Epos with Android 4.4.2 and phone with Android 10 

#### Issue
Rotating the screen changes the "Night Mode" setting

#### Steps to reproduce
1. Switch off Night Mode in File Browser
2. Open PDF, Rotation at 0°
3. Set hook in "Night Mode" --> screen turns black with white letters
4. Rotate 90° --> screen turns white with black letters
5. validate night mode setting --> hook still set in the night mode settings
6. unhook "night mode" --> screen turns black with white letters
7. Roate 0° --> screen turns white with black letters

If you do not unhook in 6. and 7. Roate 0° --> --> screen stays white with black letters while there is the hook "night mode"

##### `crash.log` (if applicable)
Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.
I'll add a log if needed.

**Comment by NiLuJe** [comment]
I'd mumble something about the invert flag being lost on bb rotate, but inversion is handled by a dedicated shadow buffer on Android, so, no idea :D.

**Comment by ezdiy** [comment]
Technical FYI why it's linked from #1200 - the relationship to rotation is that cblitbuffer is not invoked when two buffers were rotated in night mode, but got invoked when the relative rotation was 0, thus producing the disco ball effects. Further complicated by that android has actual hardware rotation modes. A lot of moving parts, please someone check 09-26 snapshot (once it builds) on a real device.

**Comment by pazos** [comment]
Fixed by https://github.com/koreader/koreader-base/pull/1200
