### ISSUE TITLE
Two typo's in Dutch translation

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6706]
* KOReader version: 2020.09
* Device: Kobo Forma

#### Issue

These translations have minor typo's in Dutch:

- "Enable style tweaks (hold for info)" > "Stjilaanpassingen inschakelen (ingedrukt houden voor info)"
"Stjilaanpassingen" should be "Stijlaanpassingen"
- "Top edge right" > "Bovenrrand rechts"
"Bovenrrand" should be "Bovenrand"

**Comment by Frenzie** [comment]
You can also fix them yourself on Weblate! It shouldn't take much more time (if not less) than creating an issue here. ;-)

Anyway, fixed. Thank for reporting. Feel free to open issues if you prefer of course; it's all good.

**Comment by smartscripts-nl** [comment]
PS: a much more usual translation for "Edit" would be "Bewerk" instead of "Verander". I've never yet seen (except in KOReader) "Verander" as button text, it is almost always "Bewerk".

**Comment by Frenzie** [comment]
Perhaps there's some context-related shenanigans at play there, where something like "bewerken" and "veranderen/wijzigen" might be better depending on context. I modified it to "bewerk" for the moment.

It occurs in all of:
frontend/apps/cloudstorage/cloudstorage.lua:385 frontend/apps/filemanager/filemanagershortcuts.lua:137 frontend/apps/reader/modules/readerhighlight.lua:426 frontend/ui/widget/opdsbrowser.lua:833 plugins/texteditor.koplugin/main.lua:292

See <https://hosted.weblate.org/translate/koreader/koreader/nl/?q=verander&sort_by=-priority%2Cposition&offset=1>
