### ISSUE TITLE
Night mode not working in Samsung s10

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#6708]
* KOReader version: 2020.09-17-g5345728c_2020-09-22
* Device: Samsung s10

#### Issue
Night mode is not working
#### Steps to reproduce
Toggle night mode on/off no change
[log.txt](https://github.com/koreader/koreader/files/5278175/log.txt)

**Comment by ezdiy** [comment]
Might be related to me molesting the blitbuffer in #6696 that's present in snapshots since 09-22. Can you try with plain 2020.09/08?

**Comment by mendelct** [comment]
The downloaded 2020.09 apk works

**Comment by NiLuJe** [comment]
IIRC, inversion on Android is... weird.  There's a shadow bb that we flip to (well, not really, that we invertblitFrom, actually), and that involves twisting the neck of the invert flag in a slightly convoluted manner, so I never remember how the flag actually gets tracked...

**Comment by NiLuJe** [comment]
i.e.,

https://github.com/koreader/koreader-base/blob/de01c8a37cf6c938a57cd16fdc0796239ece0244/ffi/framebuffer_android.lua#L119-L133

**Comment by NiLuJe** [comment]
And that this happily worked it around: https://github.com/koreader/koreader-base/blob/00922774168ba8cab225d337f1bbeb15d2799d8d/ffi/blitbuffer.lua#L753-L755

**Comment by ezdiy** [comment]
Android never blacklisted cbb because it calls invertblit directly, which invoked the CBB one. The problem is that now the lua one is invoked, and the source buffer (ext_bb) has invert flag set. So you end up with double-invert, resulting in no invert at all.

**Comment by ezdiy** [comment]
Just doing this should be enough:

```diff
diff --git a/ffi/framebuffer_android.lua b/ffi/framebuffer_android.lua
index c5de1807..603e6ecf 100644
--- a/ffi/framebuffer_android.lua
+++ b/ffi/framebuffer_android.lua
@@ -117,19 +117,7 @@ function framebuffer:_updateWindow()
     end
 
     if bb then
-        local ext_bb = self.full_bb or self.bb
-
-        bb:setInverse(ext_bb:getInverse())
-        -- adapt to possible rotation changes
-        bb:setRotation(ext_bb:getRotation())
-        self.invert_bb:setRotation(ext_bb:getRotation())
-
-        if ext_bb:getInverse() == 1 then
-            self.invert_bb:invertblitFrom(ext_bb)
-            bb:blitFrom(self.invert_bb)
-        else
-            bb:blitFrom(ext_bb)
-        end
+        bb:blitFrom(self.full_bb or self.bb)
     end
 
     android.lib.ANativeWindow_unlockAndPost(android.app.window);
```

But I have no android dev env setup, whoever wrote this could should fix it.

**Comment by CalbertAmu** [comment]
Night mode is working again, but the splash screen when launching the app is white, with black dialogue box. In the stable version, with the night mode on, the splash screen is black.
