### ISSUE TITLE
Gif pictures in EPUB documents are not rendered properly

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#671]
Tested on Kobo Mini with latest nightly (but also earlier ones).
Some (or all?) gif pictures are not shown correctly in Koreader.
Here's how it looks in Sigil (and Nickel and every other ereader I own):
![bild2](https://cloud.githubusercontent.com/assets/7792441/3420463/194b7e7e-feab-11e3-9191-c1eb32ecb127.png)

This is what Koreader makes out of it:
![screenshot_2014-june-27_15h54 pam](https://cloud.githubusercontent.com/assets/7792441/3420465/242c34d2-feab-11e3-93a9-23708dee8a0c.png)

These are the pictures used:
Gif:
![theend](https://cloud.githubusercontent.com/assets/7792441/3420470/6fea525a-feab-11e3-9888-341beb258e11.gif)
Gif (no transparency):
![theend_notrans](https://cloud.githubusercontent.com/assets/7792441/3420471/6fea88b0-feab-11e3-8dfd-54dcfdc2fdb3.gif)
PNG:
![theend](https://cloud.githubusercontent.com/assets/7792441/3420469/6fe8679c-feab-11e3-9e93-662c1ba73e02.png)

PNG and JPG always work fine.
I've seen this GIF behaviour also with different pictures, but on "The End" it is shown best.

**Comment by Frenzie** [comment]
This is different on a real device? In the emulator they both seem fine (although oddly enough the transparent looks the same as the non-transparent).

Transparent:
![screenshot_2017-09-26_22-19-18](https://user-images.githubusercontent.com/202757/30882295-d038fce2-a308-11e7-9ffe-4132f7742f25.png)

Non-transparent:
![screenshot_2017-09-26_22-19-09](https://user-images.githubusercontent.com/202757/30882294-d01ca880-a308-11e7-9567-912b5c17d293.png)

**Comment by robert00s** [comment]
@Frenzie 
On my Kindle all pictures looks the same. 
I think we can close this issue :)
