### ISSUE TITLE
Koreader unusable after updating to the latest unstable version (version 2020-09-20, Cervantes 4)

### ISSUE THREAD

**Issue by Brnoch** [koreader/koreader#6711]
I just updated to the latest unstable version my Cervantes 4
After the update, the screen was automatically switched to landscape mode, but the reader behaves as if it was still in portrait mode: I need to guess where the element I want to touch should be if the display was in portrait mode.
I tried to switch to portrait in the interface, but the operation is not possible: it's like the first button of the bottom bar was ouside of the screen. And it is the same for the 3 first elements of the top bar.

**Comment by NiLuJe** [comment]
Ping @ezdiy, Cervantes is an isAlwaysPortrait perform ;).

**Comment by Brnoch** [comment]
Thanks for the quick fix! I hope that the milestone will be released soon :-)

**Comment by Frenzie** [comment]
@Brnoch You can also copy over the two files to your installation, apply the changes manually, or wait for tomorrow's nightly build. ^_^
