### ISSUE TITLE
KOReader regularly freezes after bookmarking a text spanning across pages

### ISSUE THREAD

**Issue by smartscripts-nl** [koreader/koreader#6719]
* KOReader version: 2020.09
* Device: Kobo Forma

#### Issue

KOReader regularly freezes when laying a bookmark which spans across pages. The black cursor, normally appearing for a short time to the left of the start of the highlighted text, doesn't disappear, KOReader freezes and I then have to reset my ereader.

#### Steps to reproduce

Highlight/bookmark several texts and regularly also insert highlights/bookmarks which span across pages. After some time, KOReader then freezes as described.

**Comment by poire-z** [comment]
I'm not a heavy highlighter, but when playing with that multi page selection stuff, I never witnessed a freeze.
Given that we know you have a lot of private plugins and patches, are you sure these are not interfering?
Please test with a regular unpatched KOReader if this happens again.

> KOReader freezes and I then have to reset my ereader.

In the rare cases (twice a month) I get some touch layer hicup on my GloHD, usually a power button press to cause a suspend works (and I wait 30s to press it again and get out of sleep, and touch input works again - but that might be just the IR layer of the GloHD, dunno).
Try that next time it happens: does power button press and suspend works ? (which would mean it's not a freeze but a touch input events mess (hardware or software, I'm still not sure...)

**Comment by Galunid** [comment]
My experience is similar to @poire-z, except that I'm a heavy highlighter. I never got KOReader frozen to the point I had to restart the system while highlighting (be it on Kindle Paperwhite 2/3, Kobo Clara HD, Kobo Libra H2O, Onyx Boox Nova 2). Rarely highlights bug, but it's more of an incomplete highlighting (if I go to the next page, and go back, there is no highlight), but it happens like 1/100 times I highlight.

**Comment by NiLuJe** [comment]
I have no idea what you're calling "the black cursor", FWIW ;D.

But I am currently heavily highlighting on a Forma, and it never locked up once. The multi-page thingy has sometimes been a tad jumpy to deal with, but that's it.

**Comment by NiLuJe** [comment]
As usual, get a shell, tail a log, check dmesg, see if if the epdc is actually crashed or if it's something else.

**Comment by poire-z** [comment]
> I have no idea what you're calling "the black cursor"

That's the black marker in the left margin that you see when following links. It's also shown when back from multipage/scroll mode to show where you started your text selection (even if you decide to not highlight) so you don't get lost with the jumpyness and know where you were to start reading again.

**Comment by NiLuJe** [comment]
@poire-z: Ah, thank you. It's teeny tiny with my almost-not-there margins, so I basically only notice it when it disappears ;p

**Comment by ezdiy** [comment]
Also see if the CPU spins at 100% (ie tesseract being silly).

**Comment by NiLuJe** [comment]
Can OCR be involved in CRe? (Genuine question, I don't use OCR ;)).

**Comment by poire-z** [comment]
> Can OCR even be involved in CRe? 

Nope.

> Which leads me to an interesting question, though: on what kind of douments? Because I've been talking ePub myself, hence the assumption ;).

Multi/Follow-page text selection is not implemented for the other engines than crengine. So, it must be CRe :)

**Comment by smartscripts-nl** [comment]
> I'm not a heavy highlighter, but when playing with that multi page selection stuff, I never witnessed a freeze.
> Given that we know you have a lot of private plugins and patches, are you sure these are not interfering?
> Please test with a regular unpatched KOReader if this happens again.
> 
> > KOReader freezes and I then have to reset my ereader.
> 
> In the rare cases (twice a month) I get some touch layer hicup on my GloHD, usually a power button press to cause a suspend works (and I wait 30s to press it again and get out of sleep, and touch input works again - but that might be just the IR layer of the GloHD, dunno).
> Try that next time it happens: does power button press and suspend works ? (which would mean it's not a freeze but a touch input events mess (hardware or software, I'm still not sure...)

I'll try highlighting on a "clean" installation the coming week. It's definitely a freeze: suspending is not possible anymore. Only a hard reset makes the Kobo usable again.

**Comment by smartscripts-nl** [comment]
I am a heavy highlighter, by the way...

**Comment by NiLuJe** [comment]
> I'll try highlighting on a "clean" installation the coming week. It's definitely a freeze: suspending is not possible anymore. Only a hard reset makes the Kobo usable again.

Doesn't necessarily mean much. Keep a shell session around, and check system/kernel logs.

**Comment by smartscripts-nl** [comment]
That goes a bit above my technical abilities, alas.

**Comment by NiLuJe** [comment]
This basically means:

* Enable SSH
* Enable Wi-Fi
* Log in over SSH
* wait until something goes awry, and check `dmesg` / `logread`.

**Comment by smartscripts-nl** [comment]
OK, I managed to get a connection over Wi-Fi and SSH.

Questions:
1) When something goes awry: will the SSH connection still work when my Kobo freezes?
2) I can type dmesg and then I see feedback, but when I type logread, I get to see this: "can't find syslogd buffer"

**Comment by Frenzie** [comment]
1. Chances are it will since freezing here probably just means not responding to touch. ;-)

**Comment by NiLuJe** [comment]
1. Depends on how hard it crashes ;o).

2. That's very much *not* normal. Which FW is it running? How do you launch KOReader?

**Comment by Frenzie** [comment]
In any case you won't know if you don't try. Evoking a crash would be difficult I suppose but getting an SSH session going shouldn't take too long, also see the wiki. Dunno if you're on Windows, in that case you can try PuTTY.

**Comment by smartscripts-nl** [comment]
I always start KOReader from Kobo Start Menu. I've not meddled with the startup shell scripts of KOReader.

**Comment by smartscripts-nl** [comment]
I already managed to get a SSH connection from my Mac to the Kobo Forma. So now I'll wait for a freeze and see what I can find (although I probably won't know what I should be looking for).

**Comment by NiLuJe** [comment]
> I always start KOReader from Kobo Start Menu. I've not meddled with the startup shell scripts of KOReader.

Ah. that's most definitely not going to help. ANd is probably what prevents you from actual having a working syslogd. AMong potentially a host of other crap.

KSM is broke as all hell on Mk. 7.

Also, which FW version? Because you'll want to run a current one, too. early kernels were crashier than today's. (That's a subtle hint that, yeah, there are crash bugs left in current Mk. 7 kernels ^^).

**Comment by smartscripts-nl** [comment]
I don't know what FW stands for. Same for Mk. 7.

How do you guys start KOReader?

**Comment by NiLuJe** [comment]
> I don't know what FW stands for. Same for Mk. 7.

FirmWare. Which probably answers my question: "old". [Update your device](https://pgaskin.net/KoboStuff/kobofirmware.html) ;).

Mark 7 is the current Kobo hardware generation (starting from the Clara).

> How do you guys start KOReader?

https://github.com/koreader/koreader/wiki/Installation-on-Kobo-devices

**Comment by smartscripts-nl** [comment]
When I update Nickel,  is the firmware then also updated? Or do I have to do that manually?

**Comment by smartscripts-nl** [comment]
And when you don't use KSM, what do you use instead to start up KOReader?

**Comment by NiLuJe** [comment]
> When I update Nickel, is the firmware then also updated? Or do I have to do that separately? My Nickel version is very recent.

@smartscripts-nl: Depends on what you did, exactly. KSM has weird install hooks that may prevent an update from actually updating everything.

> And when you don't use KSM, what do you use instead to start up KOReader?

The prettiest option is currently NickelMenu, either on its own or through KFMon (àla OCP).

**Comment by smartscripts-nl** [comment]
OK, I now have the latest FW, removed KSM and start KOReader from Nickelmenu. Things look hopeful, because I also experienced regular freezes in VlasosovSoft's pbchess. That app seems much more stabile now.

I'll test KOReader in this configuration the coming week and then report.

Thanks for the tips!

**Comment by smartscripts-nl** [comment]
I can now confirm that this problem disappeared after I switched from KSM to NickelMenu.
