### ISSUE TITLE
FR: Always open with Text Editor & Always execute shell scripts

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6720]
**Current Behavior**
1. Long press on a .txt file
2. Select `Text editor`
3. `Always use this engine for this file` and `Always use this engine for this filetype` are not available

&

1. Single tap `.sh` file
2. File is opened with Cool Reader Engine

**Desired Behavior**
Ability to set `Text editor` as the default app for some filetypes (e.g. `.txt`) so they can be opened with a single tap.
&
Ability to execute `.sh` shell scripts with a single tap.

**Comment by NiLuJe** [comment]
Neither of those are technically engines, so I have no idea how this would work. Then again, I'm wholly unfamiliar with this bit of code, so, what do I know ;).

**Comment by gabyhk** [comment]
@NiLuJe Fair point. Maybe I should have written "app"? I am referring to the functionality that any OS has where you can select a **default app** to choose how a file or file type is going to be openened/executed.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/issues/5996#issuecomment-683078913
Option B was less complicated, but appetite comes with eating.

**Comment by NiLuJe** [comment]
Oh, had forgotten about that, thanks @hius07 ;).

@gabyhk: My comment was alluding to the code, not the UX. But what @hius07 just reminded me of makes my point moot ;).

**Comment by gabyhk** [comment]
@hius07 oh I did not know this had been discussed before. Thanks for orginially requesting that it be put within the long press menu. It would be way too cumbersome otherwise. My use case was just editing some very simple txt, sh and css files (in the `koreader/styletweaks` directory). Nothing critical.

@NiLuJe Thank you for being so responsive. It sounds like this would be too inconvenient to implement. Feel free to mark this as duplicate or close the issue.

**Comment by poire-z** [comment]
> makes my point moot 

Still a valid point. TextEditor/Execute script are not handled by the "Reader" code (which handles docsettings/metatadata.txt.lua - the most direct consequence is that we have no metadata.txt.lua to store the fact that `Always use this engine for this file` is wished :) 
I understand the wish, but the amount of work/refactoring to have TextEditor/ExectuteScript masquerade as Reader engines enough feels a bit heavy.
(Unless it's just a matter of creating a DocSetting enough to store this preference? anyway, not much interested in investigating that.)

**Comment by Frenzie** [comment]
> (Unless it's just a matter of creating a DocSetting enough to store this preference? anyway, not much interested in investigating that.)

I should think so. You don't need the reader to play with DocSettings; it just uses it! :-D

**Comment by gbyl** [comment]
Closing this as it turned out to be more work than expected and thus is unlikely to ever be implemented
