### ISSUE TITLE
Could you add a new function?

### ISSUE THREAD

**Issue by llb1979** [koreader/koreader#6723]
当我们阅读一个扫描版的PDF时，书刊可能奇数页和偶数页的边距不等，按之前的半自动截边距会出现错误，会出现多截或少截。希望像漫画软件一样，可以选择奇数页和偶数页裁边。谢谢
When we read a scanned PDF, the margins of odd and even pages of books and periodicals may be unequal, and errors will occur according to the semi-automatic cutting margins.I wish add a new function just like comic read,cutting margins can Distinguish between odd and occasional pages.THANKS.

**Comment by poire-z** [comment]
But that's how it currently already behave.
Any manual crop on an odd page is used for future visited odd pages.
Any manual crop on an even page is used for future visited even pages.
Any manual crop made on a visited page is remembered, and re-used.
