### ISSUE TITLE
pocketbook target building failed.

### ISSUE THREAD

**Issue by fynxiu** [koreader/koreader#6724]
* KOReader version: v2020.09-23-gabfba6c7
* Device: pocketbook color 633

#### Issue
`./kodev release pocketbook` doesn't work.
`arm-pocketbook-linux-gnueabi-gcc: command not found`

#### Steps to reproduce
just run `./kodev release pocketbook`

this [building_targets](https://github.com/koreader/koreader/blob/master/doc/Building_targets.md) guide told me that `NOTE 3: The vendor toolchain will be downloaded automatically by ./kodev release pocketbook`, but it didn't work. Should I manually install the pocketbook's SDK? If so, could anybody tell me which version, is there some tutorials for pocketbook's SDK installation?

All the best

**Comment by ezdiy** [comment]
> The vendor toolchain will be downloaded automatically by ./kodev

Always remember, docs are rife with sweet little lies!

Follow instructions at https://github.com/ezdiy/arm-pocketbook-linux-gnueabi please report if you encounter any problem.

**Comment by Frenzie** [comment]
> Always remember, docs are rife with sweet little lies!

Did we remove that? Either way, if it's still in there it might be the TC that's severely outdated.

Besides the link above, also see https://github.com/koreader/virdevenv (you can use the pb Docker image to build it).

**Comment by ezdiy** [comment]
@Frenzie ah, didn't know about the docker images. https://github.com/koreader/koxtoolchain/blob/master/gen-tc.sh#L157 is a bit messy, but good enough for koreader as it has little to no dependency on host OS apart from inkview.

**Comment by NiLuJe** [comment]
Oh, yeah, I completely forgot to both update that doc, and get rid of the awful old PB TC ;p.

So, yeah, what @ezdiy said: public PB builds are done via the koxtoolchain TC. If you don't need to do anything fancy, it'll do just fine ;).

**Comment by fynxiu** [comment]
@ezdiy thanks, and thank all of you for the fancy app. I'll give it a try.

**Comment by NiLuJe** [comment]
You do know so you absolutely don't need to build it yourself, right? o_O.

**Comment by NiLuJe** [comment]
Okay, I had actually already removed it from the Makefile/kodev, so, that just left updating the docs ;).

**Comment by fynxiu** [comment]
@NiLuJe You mean I should use `koxtoolchain` instead of building the SDK manually?

**Comment by NiLuJe** [comment]
I mean that if you're not aiming to develop an actual application, you don't need to build *anything*, we ship KOReader binaries for all supported platforms.

**Comment by fynxiu** [comment]
@NiLuJe Thanks for your advice. Just want to do some study about ereader. I've solved it.
Thanks you all.
