### ISSUE TITLE
FR: Full chapter title in TOC

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#6728]
Currently, the TOC cuts off long chapter titles with "...", see image.

The rest of the chapter title should be made visible, either in a second line or a + to expand the TOC entry (like in native Kobo software).

![20200929_102623](https://user-images.githubusercontent.com/15887012/94532585-5d364e00-023e-11eb-967b-80d810a5b469.jpg)

**Comment by NiLuJe** [comment]
Possibly on a long-press, which doesn't do anything right now, AFAICT?

**Comment by Frenzie** [comment]
Long press is used for that in some places already I think.

**Comment by NiLuJe** [comment]
@Frenzie: I wouldn't mind an example, because I was kind of wondering how to go about it (InfoWidget?). So, bonus points if I can actually make that consistant ^^.

**Comment by Frenzie** [comment]
Over in system stats.

![Screenshot_20200929_150608](https://user-images.githubusercontent.com/202757/94562218-5969f200-0265-11eb-8fb5-9f5bb16306f0.png)
![Screenshot_20200929_150612](https://user-images.githubusercontent.com/202757/94562220-5a028880-0265-11eb-8451-4ba32df42c08.png)

**Comment by Frenzie** [comment]
Also bookmarks

![Uploading Screenshot_20200929_150732.png…]()
