### ISSUE TITLE
Android devices reported not working

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#673]
[Ken Maltby started a thread on mobileread](http://www.mobileread.com/forums/showthread.php?p=2861721#post2861721) that has attracted some posts about non-compatible devices. 
- [M96, android 4.0.3. ](http://www.mobileread.com/forums/showthread.php?p=2855542#post2855542) 
- [kitkat running devices: Z ultra, TF700t](http://www.mobileread.com/forums/showthread.php?p=2861614#post2861614)
- HTC Desire HD. Koreader freezes on auto-rotate and auto-screen save.

**Please post non-working devices with android version number if at all possible!!**

**Comment by irregularisnotrandom** [comment]
NookHD+ crashes right when it is starting with a black screen. I have Cyanogenmod 11. It has no security suit installed on it.

**Comment by llb1979** [comment]
my mobile (nubia z7mini 4.4)works well.But i cant't use this software in Samsung note4(4.4) and levono k3 note(andriod 5.0)，please help us! I need this program to read pdf!

**Comment by baqlias** [comment]
Let me add two Android E-Ink devices: the Boyue T62+ and the Onyx Boox C67ML Carta. Both of them run Android 4.2.2.  I tried installing koreader on each one. On the T62+, I could never get past the list of folders. Constant crashing. On the Onyx, I was actually able to select a book, open it, look at the formatting options, and turn a couple of pages before it crashed. What I saw looked very promising.

**Comment by gerroon** [comment]
@baqlias 
Are you able to use recent Koreader om Onyx Boox C67ML ? I am interested in this device but I am afraid Koreader wont run it.

thanks

**Comment by baqlias** [comment]
There has been a firmware update for the Onyx Boox C67ML since my last post. Yes, the latest nightly for Koreader works on the Onyx most of the time - but occasionally it may crash when I select an item in settings or open a book. I don't see a crash very often, but it does happen.

**Comment by KenMaltby** [comment]
This might be of interest. http://www.mobileread.com/forums/showpost.php?p=3144545&postcount=35

Luck;
Ken

**Comment by baqlias** [comment]
Thanks, Ken. I actually happen to know personally the one who made that post! Since gerroon was asking about a recent version of Koreader, I thought I'd try the latest nightly. It does work on my Onyx Boox C67ML - most of the time. But that older version referenced on that post works flawlessly all the time.

**Comment by gerroon** [comment]
Crap, it sounds nice except that I cant find the release that is mentioned in Ken`s post ;(

**Comment by KenMaltby** [comment]
It is a long ways back there : https://github.com/koreader/koreader/releases/tag/v2014.07.04-nightly
It would be lacking quite a bit, given all the development since then.

**Comment by baqlias** [comment]
Thanks. I was just about to post that link! It's possible that a more recent nightly will work fine, but this one, I know, works flawlessly.

**Comment by gerroon** [comment]
Hollllllllllyyyyy crappppppppppppppppppppppppppp. This works on my Boyue flawless. I do not know why they do not bring this stability back to Android ;( I bet it will work great on my Android tablet.

I bought this T62 to use Koreader on it and it never worked and I felt like I wasted $130 on it ;( Maybe I can use this version now.

The only issue is that the screen size patch does not work with it. https://github.com/koreader/koreader/issues/1180

**Comment by NiLuJe** [comment]
Guess it's git bisect time for those who care about Android... ;p.

**Comment by irregularisnotrandom** [comment]
@NiLuJe 

I wish that somone who knows coding  did. :)

**Comment by KenMaltby** [comment]
I wonder how much might be issues related to Android and if any is really related to CyanogenMod? Might there be two different results?

**Comment by Frenzie** [comment]
Like I said [here](https://github.com/koreader/koreader/issues/1634#issuecomment-141680362), no issues here on cm-12.1. Doesn't mean there aren't any issues with e.g. cm-11, of course.

**Comment by danielrschmidt** [comment]
Another report for today's nightly (v2014.11-346-gf85da28):

I get mixed results on the Galaxy S4 running Android 5.0.1: Koreader takes a long time to load (showing a black screen) and it gets stuck at startup from time to time. Once it displays the directory list, however, it works smoothly and seems to be stable. 

On the other hand: No issues on the Galaxy Note 8.0 (Android 4.4.2) so far. The directory list loads quickly, the black screen is there for just a second or so.

Only bug I found: If I set a home directory, it is not selected as the start directory on the next startup. Also, Koreader crashes if I click on the Home icon in the top screen toolbar. This happens on both devices.

**Comment by KenMaltby** [comment]
Does the Android version create a crash log?

**Comment by danielrschmidt** [comment]
If it does, I can't find it.Hum.

**Comment by chrox** [comment]
Koreader on Android has no error log file (probably we need one), but if have adb access to your device, you can get the log by `adb logcat | grep luajit` when koreader is running.

**Comment by danielrschmidt** [comment]
Perfect, running adb is no problem, I'm attaching a few logs below. In the meantime, I figured out that the long black screens occur if the previous session has crashed. Apart from that, the app starts quickly. 

I did the following to produce the logs:
1) This is a successful start
2) Open a book, open toolbar, tap on home -> crash.
3) This is a relaunch after a crash, the black screen occurs after line 4 and before line 5 appears (just before "Application data directory...").
4) Double tap on the back button to close the app -> crash.

Link to the logs: https://gist.github.com/00023fe97db9f9e57f35.git

**Comment by xorrox** [comment]
This is about a Sony Z1 (C6903) phone running an unofficial Android 5.1.1 ROM:

With the 2015-stable version, the screen just stays black. (logcat reports a problem about the filemanager module.) 

With the 2014.04-309-g854b941 build linked by Ken, it basically works, but after selecting a book from file manager, after loading that book in the reader, the filemanager icon is missing. And exiting with the home icon doesn't actually kill the app. I also have a really hard time hitting the icons in the reader properly, could be related.

Adding logcats for both cases.
[sony-z1-2015-stable.txt](https://github.com/koreader/koreader/files/34454/sony-z1-2015-stable.txt)
[sony-z1-2014-4.txt](https://github.com/koreader/koreader/files/34455/sony-z1-2014-4.txt)

**Comment by Frenzie** [comment]
I acquired a Zenfone 2 (ZE551ML) to replace my aging SE Xperia Ray. Because it runs on an Intel processor, it doesn't work.

All the prerequisites are in place already in https://github.com/koreader/android-luajit-launcher/ to easily build APKs that contain binaries for both x86 and ARM, so I guess the main question is whether or not it's a good idea to. There aren't too many Intel-powered Android devices, so I suppose not.

**Comment by timofonic** [comment]
I'm going to test KOReader on both my ZTE A450 and my Boox M96+!

**Comment by Markismus** [comment]
Teclast x98 plus tablet with android 5.1 doesn't work. As others do work on android 5, it probably has to do with te screen resolution of 2k times 1.5k. Will investigate the logs with adb as soon as my girls are on vacation.

**Comment by Frenzie** [comment]
I figured I'd try it again on my Zenfone 2 to see what happens.

```
04-02 14:34:29.270 20250 20266 I luajit-launcher: Waiting for app ready...
04-02 14:34:29.300 20250 20266 I luajit-launcher: App window ready.
04-02 14:34:29.300 20250 20266 I luajit-launcher: App gained focus.
04-02 14:34:29.300 20250 20266 I luajit-launcher: Launching LuaJIT assets...
04-02 14:34:29.620 20250 20266 I luajit-launcher: Application data directory /data/user/0/org.koreader.launcher/files
04-02 14:34:29.620 20250 20266 I luajit-launcher: Application library directory /data/app/org.koreader.launcher-1/lib/arm
04-02 14:34:29.620 20250 20266 I luajit-launcher: Screen size 1080x1920
04-02 14:34:29.630 20250 20266 I luajit-launcher: Screen brightness 12
04-02 14:34:29.640 20250 20266 I luajit-launcher: show progress dialog
04-02 14:34:29.660 20250 20266 I luajit-launcher: Check file in asset module: koreader-g1b700c0.7z
04-02 14:34:29.660 20250 20266 I luajit-launcher: Skip installation for revision g1b700c0
04-02 14:34:29.660 20250 20266 I luajit-launcher: dismiss progress dialog
04-02 14:34:29.660 20250 20266 I luajit-launcher: Change directory to /data/data/org.koreader.launcher/files
04-02 14:34:29.670 20250 20266 I KOReader: intent file path 
04-02 14:34:29.670 20250 20266 I KOReader: run command chmod 755 ./sdcv
04-02 14:34:29.700 20250 20266 I KOReader: command stdout:
04-02 14:34:29.700 20250 20266 I KOReader: command stderr:
04-02 14:34:29.700 20250 20266 I KOReader: command res:0
04-02 14:34:29.700 20250 20266 I KOReader: run command chmod 755 ./tar
04-02 14:34:29.720 20250 20266 I KOReader: command stdout:
04-02 14:34:29.720 20250 20266 I KOReader: command stderr:
04-02 14:34:29.720 20250 20266 I KOReader: command res:0
04-02 14:34:29.730 20250 20266 I KOReader: run command chmod 755 ./zsync
04-02 14:34:29.750 20250 20266 I KOReader: command stdout:
04-02 14:34:29.750 20250 20266 I KOReader: command stderr:
04-02 14:34:29.750 20250 20266 I KOReader: command res:0
04-02 14:34:29.780 20250 20266 I KOReader: try to load module libs/libkoreader-lfs.so
04-02 14:34:29.840 20250 20266 I KOReader: external storage /storage/emulated/0
04-02 14:34:29.870 20250 20266 I KOReader: ERROR cannot open translation file: l10n/en_US/koreader.po
04-02 14:34:29.910 20250 20266 I KOReader: ffi.load SDL2
04-02 14:34:29.910 20250 20266 I KOReader: ffi.load SDL
```
Note the three minute gap!
```
04-02 14:37:56.480 20250 20266 I KOReader: INFO  initializing for device Android
04-02 14:37:56.480 20250 20266 I KOReader: INFO  framebuffer resolution: {
04-02 14:37:56.480 20250 20266 I KOReader:     ["h"] = 1920,
04-02 14:37:56.480 20250 20266 I KOReader:     ["w"] = 1080
04-02 14:37:56.480 20250 20266 I KOReader: }
04-02 14:37:56.480 20250 20266 I KOReader: ffi.load libs/libfreetype.so.6
04-02 14:37:56.520 20250 20266 I KOReader: ffi.load libs/libmupdf.so
04-02 14:37:56.580 20250 20266 I KOReader: ffi.load libs/libwrap-mupdf.so
04-02 14:37:56.700 20250 20266 I KOReader: try to load module common/socket/score.so
04-02 14:37:56.720 20250 20266 I KOReader: try to load module common/mime/mcore.so
04-02 14:37:56.740 20250 20266 I KOReader: try to load module common/ssl.so
04-02 14:37:56.800 20250 20266 I KOReader: try to load module rocks/lib/lua/5.1/lpeg.so
04-02 14:37:56.810 20250 20266 E luajit-launcher: Failed to run script: error loading module 'lpeg' from file 'rocks/lib/lua/5.1/lpeg.so':
04-02 14:37:56.810 20250 20266 E luajit-launcher: 	dlopen failed: library "rocks/lib/lua/5.1/lpeg.so" not found
```
Then it just stays white.

I don't comprehend Android, so that's about all I can contribute. :-)

**Comment by Frenzie** [comment]
I'll close this as outdated.
