### ISSUE TITLE
FR: Support the new Calibre 5 annotations feature

### ISSUE THREAD

**Issue by WolfgangDpunkt** [koreader/koreader#6730]
Calibre 5 has now a new feature introduced: "Highlighting in the E-book viewer".
"The highlights are stored in the book file itself for easy sharing. They are also stored centrally in the calibre library" (see [New in calibre 5.0](https://calibre-ebook.com/new-in/fourteen))

It would be great if the highlights/annotations in koreader could be synchronized with Calibre in the future .
This would be incredibly valuable, especially when working with (scientific) literature (as discussed here #6644).

**Comment by NiLuJe** [comment]
They're *optionally* stored in the book itself. (Enabled by default, though).

Which means the book is updated, which means its hash changes, which, in itself, will already be a fun experience.

Then that leaves the actual format itself (I haven't looked into it *at all*).

The TL;DR being: this is probably highly NOT trivial ;).

**Comment by NiLuJe** [comment]
Okay, the three places being:

* In a JSON file in the viewer's config folder (i.e., don't care).
* In the Calibre Library DB (i.e., don't care).
* In the ePub, as `calibre-book-annotations.json`.

**Comment by WolfgangDpunkt** [comment]
Thanks for your prompt feedback. 
Apparently it is not a fruit that hangs too low after all. :-)
I hope someone will find a workable solution anyway.
The annotation feature of koreader would be catapulted to a whole new level and the workflow in reading and excerpting textbooks would be much more comfortable.

To express my gratitude for every effort in this direction, and to support the development of this great software I will post a reward of 20 US$ at bountysource.

**Comment by NiLuJe** [comment]
The fact that this doesn't make it to the metadata means that I'm not quite sure how you deal with "updating" an on-device book with new annotations made from the Viewer, among other things.

Someone that is actually familiar with the workflow might come in handy.

**Comment by poire-z** [comment]
> Okay, the three places being:
    In a JSON file in the viewer's config folder (i.e., don't care).
    In the Calibre Library DB (i.e., don't care).
    In the ePub, as calibre-book-annotations.json.

Obviously not in the EPUB, that we don't want to modify and have travelling back and forth between the device and computer.
For ther other 2 places, they are on the computer right ? So we can't access them :)

So, the question is whether they can travel thru the calibre plugin/metadata sync (we have something like that right?).
Then, the question is how they would look on this calibre plugin/metadata (xpath like?) and if we can convert to/from our xpointers format.

**Comment by NiLuJe** [comment]
@poire-z: My point exactly ;). Hence the "huh, right now, that looks like a no-go" interrogation ^^.

**Comment by WolfgangDpunkt** [comment]
Well I remain hopeful that a way will be found after all. :-)

**Comment by pazos** [comment]
https://www.mobileread.com/forums/showpost.php?p=4040454&postcount=4

There's no future :) Not sure if a xpointer <-> CFI is possible as a calibre plugin or makes sense to export KO highlights as CFI. Anyways it looks like export/import and not a sync feature.

I don't think the smart device app supports annotation syncing. It wasn't updated in a while and CC is no longer developed

**Comment by charleshan** [comment]
This would be a game changer! Syncing annotation is the main reason I'm considering switching from pw4 to an android e-reader.

**Comment by renke** [comment]
I am working on a one-way sync from KOReader to Calibre: https://github.com/renke/koreader-to-calibre-highlights

It is still WIP but since I found this issue while searching for an existing solution, I thought I maybe mention it here so other can (hopefully) profit from it.
