### ISSUE TITLE
Add back SCROLL_MODE for PDF/DJVU?

### ISSUE THREAD

**Issue by ProgramFan** [koreader/koreader#6731]
**Does your feature request involve difficulty completing a task? Please describe.**
I am using KOReader on a 10.3 inch Android Eink device for pdf documents. The reading is very smooth with an automatic page crop and no scrolling. However, there exist no ways (even in defaults.lua) to turn off the scroll mode by default. This adds a burden to manually turn off scroll mode for **every document**. After investigation, I found that older versions do support DSCROLL_MODE in defaults.lua, but it is removed intentionally and kopt_page_scroll is set to 1 by default without any chances to change it globally.

Page scrolling on Eink devices is never a good default since the screen updates so slowly. Can we add something like a global configuration for scroll mode?

**Describe the solution you'd like**
Add a global option to turn off SCROLL_MODE for PDF/DJVU alike files.

**Describe alternatives you've considered**
Add back DSCROLL_MODE in defaults.lua and default to 1. At least I can change it by recompiling the apk.

**Comment by ezdiy** [comment]
Hold-tap on the page mode button. Took me a while too to discover this. Works for a lot of settings (even in menus) etc.

**Comment by NiLuJe** [comment]
That's indeed the default-setting gesture, usable in a loooot of places ;). It's *supposedly* taught to you by the Quickstart Guide ;).

**Comment by ProgramFan** [comment]
Thank you for the information. A bad decision to skip the quickstart.
