### ISSUE TITLE
downloaded dictionary packages are not deleted after unpacking: Bug or feature?

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader#6732]
* KOReader version: http://build.koreader.rocks/download/nightly/v2020.09-29-ge169b34_2020-09-29/koreader-pocketbook-v2020.09-29-ge169b34_2020-09-29.zip
* Device: pocketbook PB631

####
I downloaded some dictionaries with the latest nightly build. I remarked that after the .tgz are downloaded and unpacked, the original .tgz remain in applications/koreader/data/dict, bloating it. Shouldn't they be erased automatically?
Is this by design, by accident, or a bug?

#### Steps to reproduce
Lookup menu/Dictionary Settings/Download dictionaries

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/5301100/crash.log)

**Comment by Frenzie** [comment]
This is in reference to https://www.mobileread.com/forums/showthread.php?p=4040878

It's by design, definitely not a bug, but it's not a design I have strong feelings about. ;-)
