### ISSUE TITLE
Screenshot takes minutes to complete

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6736]
* KOReader version: v2020.09-30-gf0f0cfd1
* Device: Tolino Epos 2

#### Issue
Screenshot does not work. It takes MINUTES until the confirmation dialog appears. After that time the screenshot is stored in the correct directory.
If you tap on the screen during the waiting time, an ANR occurs.

#### Steps to reproduce
Take a screenshot by swipe from right-bottom to left-top.

**Comment by NiLuJe** [comment]
Possibly the Lua BB code getting blacklisted by the JIT on Android, or Android being... Android.

Caz't repro on platforms with a sane JIT, FWIW.

**Comment by Frenzie** [comment]
@NiLuJe Probably more Tolino bug than Android bug. Not that Android's innocent, but… ;-)

**Comment by NiLuJe** [comment]
I don't quite recall how I checked that the last time, but I fear it requires running LuaJIT in verbose/debug mode, which is going to be extremely unfun to deal with on Android.

One could try if bumping loopunroll to 45 on Android would help?

(It's currently handled inside ffi/bb.lua, and only done when CBB is disabled).

i.e.,

https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L1906-L1907

**Comment by pazos** [comment]
This is a recent issue. It used to work a few weeks ago.

**Comment by NiLuJe** [comment]
Nothing really jumps out in the few bb cleanups, though, so I'd rather blame those very few changes upsetting the fragile JIT balance somehow ;).

**Comment by zwim** [comment]
I can tell you that the 2009.9 version does not have the bug.
The nightlies 2009.9-17 and 2009.9-33 do have the bug.

I inserted some logger.dbg calls in writePNG in blitbuffer.lua around the for loop
https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L1743-L1759 and it seems that the loop over y takes 90 seconds and more. A have also commented out line 1746 (used a differen local c) and the storage to mem[xxx] with almost no effect. The time in the loop stays at 80 seconds.

**Comment by zwim** [comment]
Is there an archive of the nightlies before 2009.09-17 so that I could check, when the bug was introduced?

**Comment by Frenzie** [comment]
You can find all the nightlies going back further than we can keep on the koreader.rocks server over on https://gitlab.com/koreader/nightly-builds/-/jobs

(but you'll have to sign them yourself since we're talking about Android here)

**Comment by zwim** [comment]
Thank you.

I have tried  koreader-android-arm-v2020.09-14-g34b3d55_2020-09-22.apk  it takes maybe 1 or 2 seconds to take the screenshot
Whereas  koreader-android-arm-v2020.09-17-g5345728_2020-09-22.apk needs minutes.

**Comment by Frenzie** [comment]
Definitely the obvious changes then… though as @NiLuJe says nothing jumps out.

**Comment by zwim** [comment]
As the 2020.9-14 was build on Sep. 22 at 6:xx 
and 2020.09-17 was build on Sep. 23 at 6:xx I would suspect the change as either #1194 or #1194 of KOreader base, but it could also be KOReader  #6696 (or unlikely 6684, 6686 or one of the other KOReader commit of 09/22).

**Comment by NiLuJe** [comment]
Do try setting loopunroll to 45 ;).

**Comment by zwim** [comment]
I have set loopunroll in https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L1905 to 45, this didn't change the time.
I have added right after https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L1736
```
       local val = 45
       jit.opt.start("loopunroll="..tostring(val))
       jit.flush()
```
didn't help either.

**Comment by NiLuJe** [comment]
No, you'll want it in the outer scope; i.e., right *below* the `BB:enableCBB(true)` call, just before the final `return BB` ;).

**Comment by zwim** [comment]
Putting 
```
       local val = 45
       jit.opt.start("loopunroll="..tostring(val))
       jit.flush()
```
before `return BB` does not help.

**Comment by NiLuJe** [comment]
Well, there goes that theory ;).

**Comment by NiLuJe** [comment]
I still suspect JIT shenanigans, but, Android being Android, this is going to be extremely unfun to look into.

**Comment by NiLuJe** [comment]
And, of course, I can't reproduce on a non-shitty Android device ;).

**Comment by NiLuJe** [comment]
Okay, I lied, it's random depending on previous usage, which pretty much confirms that it's the JIT blacklisting the BB code for some reason...

**Comment by NiLuJe** [comment]
Or the reverse? Paging around the FM a few times primes the JIT and everything gets snappier (or, actually, as snappy as before the changes ^^).

**Comment by NiLuJe** [comment]
@ezdiy: Could the `jit.flush` be screwing with this, somehow?

**Comment by NiLuJe** [comment]
I can't reliably reproduce by switching a Kobo to 32bpp either (I mean, in a dozen reboots, I managed to get two slow refresh on boot a single time :s).

**Comment by NiLuJe** [comment]
I mean, when it happens, blitting in general is slower. It just happens to be exacerbated in the screenshot function because that one's extremely dumb and shitty performance-wise ;).

**Comment by ezdiy** [comment]
Comment out lines at

https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L1906

And then add

`        jit.opt.start("loopunroll=45")`

at https://github.com/koreader/koreader-base/blob/master/ffi/blitbuffer.lua#L591

The reason for this is that jit options may get recorded on function FNEW in Lua, thus making the logic I introduced of changing options on the fly more trouble than worth (meaning, we've to set the unrolls unconditionally always now).

**Comment by NiLuJe** [comment]
@ezdiy: FWIW, we couldn't detect any obvious issues with it set to 45 back when we originally tried this unconditionally to workaround weird issues on Kobo in the dark times of RGB565...

The conservative choice to limit it to where we knew it was needed was more of a "better be safe than sorry" one ;).

**Comment by zwim** [comment]
I can confirm that https://github.com/koreader/koreader-base/pull/1205 solves this issue. A screenshot takes now approx. 3 seconds.
I know that the screenshot is not the most important function of KOReader, but would it be possible to speed things up by using a C-function instead of LUA?

Additionally I have noticed, that with 1205 opening books is also faster  and the UI is snappier.

From my side this issue can be closed.
