### ISSUE TITLE
FR: Font preview in fonts menu 

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#6739]
When choosing fonts it would be great to get a preview of what a font looks like. A solution other reading software (Kindle, Kobo, Pocketbook, Tolino) already has implemented is to display the name of the font written in the font itself.
See Pocketbook font menu as an example:
![20201001_125919](https://user-images.githubusercontent.com/15887012/94801299-2307b080-03e6-11eb-842e-23a2f6f22e1e.jpg)

**Comment by poire-z** [comment]
Would be nice to have, and would also need the A/B/C stuff I mentionned at https://github.com/koreader/koreader/issues/6107#issuecomment-672712604.
So, quite a bit of work.

**Comment by poire-z** [comment]
OK, not so much work after all (a function to add to crengine, some bits to ffi/freetype.lua and font.lua to allow specifying the face index of a font in a ttf or ttc font collection).
Just some bit ugly code in textwidget.lua to allow forcing a baseline and height (that we would never need in contexts other than this one) so we can have the menu item correctly vertically aligned.

We could have that:
<kbd>![image](https://user-images.githubusercontent.com/24273478/94996607-f601fc00-05a5-11eb-8236-c07cbe43eea2.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/94996619-03b78180-05a6-11eb-8135-14d6b98e7a88.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/94996623-0ca85300-05a6-11eb-859e-1e0fe4072d7d.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/94996635-247fd700-05a6-11eb-83e0-c0a5fdda8775.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/94996648-35304d00-05a6-11eb-8741-e362b6fe1c98.png)</kbd>

(The first font in solid black is not me hiding my prefered obscene font :) it's just the [Ahem font](https://www.google.com/search?hl=en&num=25&q=ahem+font). I don't think there's any way to distinguish a font like that to use the default font.

Fonts would be loaded when the menu is browsed, so 5 by 5, no slowdown noticable on my device.

Do we want that?
Should it be optional with a toggle in `Font settings> [ ] Show font names in their own font`, and if yes, with what default value?

(Tested on my device, and really not much value added except a feeling of how really bold or thin the font would be - but no hint about the font own line height which is what first jumps at me on a bad font :)

**Comment by pazos** [comment]
> Do we want that?

Yeah!

> Should it be optional with a toggle in Font settings> [ ] Show font names in their own font

I don't think so. But if you want I would vote for `yes`

> Tested on my device, and really not much value added except a feeling of how really bold or thin the font would be

It improves appearance. It doesn't add value if you already know your fonts but it is cool if you don't remember how a font looks like.

**Comment by Galunid** [comment]
> Do we want that?

Yes, pretty please!

> Should it be optional with a toggle in `Font settings> [ ] Show font names in their own font`, and if yes, with what default value?

I don't really see a reason, why someone wouldn't want it enabled by default, but I don't think an option to turn it off would hurt. I'm fine even if you can't turn it off.

>  (Tested on my device, and really not much value added except a feeling of how really bold or thin the font would be - but no hint about the font own line height which is what first jumps at me on a bad font :)

I don't remember how my fonts look like, so it's kind of life-saver ;)

**Comment by Frenzie** [comment]
The only question is how well the font's name shows off the font's properties, but +1 on that.

So if you want to go the extra mile, make it display the crazy fox on long press or something. :-D

**Comment by Uwe-B** [comment]
Q1: I think it is a nice and missing feature, so yes please!
Q2: Not really necessary on the first view but in case something breaks or exotic fonts are used, so it is yes please!

**Comment by LucyOne** [comment]
Yes, that looks exactly like I imagined it! The option to disable it would also be nice to have.
