### ISSUE TITLE
Night mode not working on reMarkable + Question about menu editing

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6740]
#### Issue
It appears that `Night mode` was never implemented on the reMarkable port of KOReader. The screen simply flashes when activated and nothing happens.

#### Question
What is the best way to edit the KOReader menus? I have tried commenting out sections of `filemanager_menu_order.lua` but that just make them reappear with the prefix `NEW:` under the `filemanager settings` (papers and drawer icon).

**Example:** Which part of the code would comment out to remove `Night mode` from the menu?

**Comment by ezdiy** [comment]
Edit https://github.com/koreader/koreader/blob/master/frontend/device/remarkable/device.lua#L8

(fronted/device/remarkable in your koreader folder)

And add 

```
local Remarkable = Generic:new{
    model = "reMarkable",
    canHWInvert = no, -- remarkable doesn't apparently have HW inversion
```

**Comment by gabyhk** [comment]
@ezdiy I don't know why I thought removing menus would be as easy as commenting out a line per menu. I tried adding the code you suggested and unfortunately it still does not work.

**Comment by pazos** [comment]
@gaby-lee: IIRC removing menus is a matter of assign `order["category"] = nil`, like in https://github.com/koreader/koreader/blob/master/frontend/ui/elements/filemanager_menu_order.lua#L174

Pinging @tcrs about the night mode. Not sure if never was implemented. He might know

**Comment by gabyhk** [comment]
@pazos I tried `order.night_mode = nil` and the menu item is still there. I must be doing something wrong because `order.exit_menu = nil` does work.

**Comment by NiLuJe** [comment]
I don't recall anything specific about HW inversion being broken on rM. In fact, given that it's an NXP SoC, I'd be *very* surprised if it didn't.

The inversion code is common to all NXP platforms, and it works for me over here.

And, if it were an HW inversion issue, flipping to cap off and enforcing the Lua BB like @ezdiy mentioned would *definitely* work.

**Comment by NiLuJe** [comment]
And the recent 8bpp vs. 16bpp launcher situation should be irrelevant (both for HW and SW inversion).

**Comment by NiLuJe** [comment]
That said, the cap is missing entirely, so we may not have tested this at all?

Try with a current nightly?

**Comment by ezdiy** [comment]
Even if it was missing it would be fine unless the blitter is ALSO too old (ie needs the horrible env var disable thingy thats been gotten rid of).

**Comment by gabyhk** [comment]
If I comment out these lines, then `Night mode` definitely disappears. I wish the `= nil` method worked since that's a lot more elegant

https://github.com/koreader/koreader/blob/426f7b5ddcc2029bca6f138f66182518fd5ac0f7/frontend/ui/elements/common_settings_menu_table.lua#L169-L175

**Comment by pazos** [comment]
> @pazos I tried `order.night_mode = nil` and the menu item is still there. I must be doing something wrong because `order.exit_menu = nil` does work.

If that works it would be `order.setting.night_mode = nil`

**Comment by NiLuJe** [comment]
@ezdiy: Even on stable, the cap would be enough to kill the CBB ;).

**Comment by gabyhk** [comment]
@pazos Sadly it doesn't work. This is strange considering that `order.setting = nil` does work! It gets rid of the whole menu, but specific menu items within it are apparently not affected by the `nil` instruction.

**Comment by NiLuJe** [comment]
It's a table, you'd probably have to either walk the table, and filter it (i.e., assign a "night_mode" less copy), or punch a nil through it, which might not be safe. (I don't recall how we iterate this, but nil-in-a-table is a fun recipe for disaster in Lua).

**Comment by gabyhk** [comment]
@NiLuJe I understand now why `Night mode` and  other menus that were not implemented for the remarkable are still there. It sounds like it takes quite a bit of work and knowledge to remove menus.

**Comment by NiLuJe** [comment]
@gabyhk: Night mode is *always* implemented, which is why it's always there.

Ideally, it's deferred to the hardware on NXP SoCs, but when it isn't, we handle it in software ourselves.

**Comment by NiLuJe** [comment]
You still haven't told us which version you're running, exactly ;).

**Comment by gabyhk** [comment]
I am running v2020.09

**Comment by NiLuJe** [comment]
Try a current nightly then ;).

**Comment by gabyhk** [comment]
To be honest, I don't know how to do that without a wifi connection. I'll let you know if I figure it out. I also couldn't implemente this https://github.com/koreader/koreader/issues/6676#issuecomment-701054774 given my lack of knowledge. That being said, I always appreciate your patience.

**Comment by NiLuJe** [comment]
You can install a nightly manually (the master is over [here](http://build.koreader.rocks/download/nightly/)).

**Comment by gabyhk** [comment]
@NiLuJe I am running now `v2020.09-33-g6b41880_2020-10-01` and it works! You're the best!
