### ISSUE TITLE
Downgrading KOReader, and figuring out old version from file backup

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [koreader/koreader#6747]
* KOReader version: ??? and 2020.08.1
* Device: Kindle 4

#### Backstory

I'd been using a years-old version of KOReader on my Kindle 4, which worked okay-ish. As was mentioned in another issue on here concerning non-touch devices, editing certain options and setting certain defaults does not work - they require touch input. I bypassed this by manually editing config files to set default fonts, sizes, margins, date, etc.

I'd previously made a backup of my entire Kindle directory and one day I decided to update KOReader. Sadly, the update reset the edits to the configs I'd made (and also removed the option to set a custom screenshot directory, for some reason).
  
#### Issue

I'm looking to downgrade, but I can't figure out what my old KOReader version was - I have my entire old KOReader folder, but I can't find any file which lists which version it is.
Furthermore, if I figure out the old version, what would be the best way to downgrade? Can I download the zip and use KUAL to downgrade like I used it to upgrade? 

Or is it possible to just move the old KOReader folder into my Kindle and it could start working with no issue? Hopefully that would work, it'd be a very quick and easy solution.

**Comment by Frenzie** [comment]
> I'd previously made a backup of my entire Kindle directory and one day I decided to update KOReader. Sadly, the update reset the edits to the configs I'd made (and also removed the option to set a custom screenshot directory, for some reason).

Most font size options in defaults.lua haven't been deprecated. If you overlooked the warning at the top of defaults.lua, you can just copy over your old one as persistent.defaults.lua. If that's not the case for a particular setting, you'd have to use settings.reader.lua instead.

https://github.com/koreader/koreader/blob/8b886e5922ded3c189a23acbae45ed701e9148be/defaults.lua#L1-L2

> I'm looking to downgrade, but I can't figure out what my old KOReader version was - I have my entire old KOReader folder, but I can't find any file which lists which version it is.

There should be a file named `git-rev`.

> Or is it possible to just move the old KOReader folder into my Kindle and it could start working with no issue? 

I don't know how this KUAL business works, but in all likelihood. Note that the safest way would be to delete the contents of the folder and then to copy the backup into it, rather than merging the folders.

**Comment by iFUCKINGHATEcomputers** [comment]
>I don't know how this KUAL business works, but in all likelihood. Note that the safest way would be to delete the contents of the folder and then to copy the backup into it, rather than merging the folders.

Cheers. So deleting the entire folder before copying the backup should work as well?

**Comment by Galunid** [comment]
Yes, it *should* work, instead of deleting the whole folder, I'd suggest you rename it (the one already existing on kindle, just in case it doesn't work), and copy the one you have backed up over.

**Comment by Frenzie** [comment]
Closing with reference to https://github.com/koreader/koreader/issues/6463#issuecomment-703232578 for how to figure out the settings.

As @Galunid said the smartest way to test is to rename one's koreader folder temporarily and to put another one in place.
