### ISSUE TITLE
Text in svg files created with LibreOffice does not get displayed

### ISSUE THREAD

**Issue by rexkerr** [koreader/koreader#6757]
* KOReader version: 2009.20
* Device:  Linux (Ubuntu 18.04)

#### Issue

Text on some SVG files does not show up, though drawing elements does.

I noticed that the text in some diagrams in a journal article did not show up.  I unzipped the epub file and found the offending svg -- opening the svg directly also does not render correctly.  I noticed that the svg appeared to be created in LibreOffice, so I created a new test SVG with a simple box with text and was able to reproduce the issue from scratch.  The test SVG is attached (enclosed in zip file since gitlab won't allow direct upload of svg files)

#### Steps to reproduce

Open LibreOffice Draw, create an svg with a simple shape object and text over the shape, export as svg, open with KOReader

##### `crash.log` (if applicable)
n/a

[TestSVG.svg.zip](https://github.com/koreader/koreader/files/5330499/TestSVG.svg.zip)

**Comment by poire-z** [comment]
Mentionned that a few hours ago at https://github.com/koreader/koreader/issues/6678#issuecomment-703837152.
It's a limitation of the [nanosvg](https://github.com/memononen/nanosvg) library we use to render SVG :/
I regularly look at its various forks if one of them would have implemented that - but nothing yet.

(We'd have enough already in crengine to provide glyphs to nanosvg - it just needs someone passionate enough about SVG to add the parsing of text and the needed interfacing.)

**Comment by ezdiy** [comment]
mupdf got some basic `<text>` rendering in [recent versions](https://github.com/ArtifexSoftware/mupdf/commit/a043980060a8e25dcec91c9fdd525b1a0baab7ff), so it should work in koreader once its bummped. it's still pretty basic though - no support for embedded fonts, nor for advanced styling of the sort OO does.

**Comment by Frenzie** [comment]
Another way to reproduce the issue (if we needed more ;-) ), from <https://github.com/koreader/koreader/issues/7026>.

> SVGs for math formulae in WMF exports don't show in Koreader. E.g.:
> 
> * https://wsexport.wmflabs.org/book.php?lang=en&format=epub-3&page=The_Michelson-Morley_Experiment_and_the_Dimensions_of_Moving_Bodies
> 
> Original: https://en.wikisource.org/wiki/The_Michelson-Morley_Experiment_and_the_Dimensions_of_Moving_Bodies

**Comment by poire-z** [comment]
I'm not sure this one is related to text or tspan tags - I don't see any in the few SVGs I looked at.
May be bad quality SVGs, or our support for SVGs sucks...

**Comment by Frenzie** [comment]
Indeed, the text was converted to paths. It's actually something like `https://github.com/memononen/nanosvg/issues/129`. Although as far as I'm concerned "it's nanosvg" still effectively qualifies as a duplicate. ^_^

**Comment by johnbeard** [comment]
The SVGs look fairly normal, except for the heavy use of `xlink` references (each glyph is a `<def>` and is xlink'ed for each instance).

![Save as SVG](https://user-images.githubusercontent.com/5386578/102904691-fa81d680-4469-11eb-941f-b9146f9693b0.png)

**Comment by poire-z** [comment]
There is a nanosvg fork that seems to have implemented support for text/tspan/images/def/use/styles...
https://github.com/mtyberg/nanosvg/commits/master
I can't judge the quality, but it's all in the parsing code (nanosvg.h) only - nothing in the drawing code (nanosvgrast.h).

**Comment by Frenzie** [comment]
I think some text (even if a bit meh) might be better than no text. Did you already try it?

**Comment by poire-z** [comment]
Nope, haven't tried it, and it would need much work to pick glyph and image bitmaps from crengine (but I could help on that).
I'm quite intimadated by SVG (huge spec!) and nanosvg :) Was hoping for @johnbeard to adopt it :) 

I'd like to have better SVG, supporting text and embedded images, even if meh as you say:) I think, now that MathML is done, that it's the last thing where we do NOT SHOW some valuable content (the other things we may not are most probably just cosmetics/decoration/styling).

**Comment by skinkie** [comment]
In this Plato issue I have compiled several documents with viewing issues. Hence I can confirm that text-to-path works on KOreader (and on stock). At this moment plato seems to be the only reader capable of rendering svg-text given that it is not used inline (thus: img-tag).

https://github.com/baskerville/plato/issues/191
