### ISSUE TITLE
can't take screenshot on PB631

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader#6760]
* KOReader version: 2020.09.38-ga507740
* Device: pocketbook PB631 (FW 5.20)

#### Issue
Can't take screenshots of KOReader in the usual pb way - the screen is blanked, and the resulting screenshot is a bmp file with all white content

#### Steps to reproduce
While in KR, long press the home button. This in PB brings up an Activity List dialog, which includes four buttons for supposedly useful meta actions applicable without quitting any running program, such as turning on WiFi or locking the screen. One button is for taking a screenshot of the topmost application, and to save it as .bmp in the directory /mnt/ext1/screens/. Only, the KR display blanks out before this dialog appears, and hence what is saved is a blank screenshot.

**Comment by NiLuJe** [comment]
I remember @ezdiy mentioning that InkView blanks the fb when stealing focus, which would explain this.

I'll let PB people answer it properly, but this feels like a can't fix ;).

**Comment by ezdiy** [comment]
Added as a task to https://github.com/koreader/koreader/issues/6597
This needs to be fixed to get "last screen as a boot screen" working, too.

**Comment by Uwe-B** [comment]
Just to add information to this (PB631):
Taking a screenshot within Koreader with **Koreader** gesture works but not taking a screenshot with the **pocketbook embeded utilities**.

**Comment by EastEriq** [comment]
Which gesture? I don't find any configurable as Take Screenshot in Gesture Manager

**Comment by Uwe-B** [comment]
Diagonal swipe:
https://www.mobileread.com/forums/showthread.php?t=242906

**Comment by EastEriq** [comment]
I see, thanks for the pointer. Right, diagonal swipe WFM. The effect of many other swipes is sluggish to random for me, but that is another story, possibly because of the relatively slow cpu. Most frequently I trigger Decrease font size wanting to do something else.

**Comment by EastEriq** [comment]
@ezdy many thanks for your work. It really changed KR for me from "what is this crap?" to "rocks!" during the last couple of weeks.

**Comment by Uwe-B** [comment]
Yeah, thanks from me too! I have not used Coolreader for weeks now!

**Comment by EastEriq** [comment]
I will probably erase cr3 from my reader someday to reclaim space. Coolreader doesn't support RTL, that is the deal breaker for me. KoR supports it even better than fbreader, btw. Besides, cr3 is no more maintained.

**Comment by rjd22** [comment]
@NiLuJe this will be also fixed next release. I checked and screenshots work for me with the inkview render.
