### ISSUE TITLE
Cannot access menus

### ISSUE THREAD

**Issue by maximovi** [koreader/koreader#6765]
* KOReader version: 2020.09
* Device: Kindle Paperwhite 2

#### Issue

The top menu (and bottom menu when in a book) are not opening. My gestures still work so I am able to get back to the file manager by navigating to the last page but otherwise I would be stuck in the book. The status bar still appears and disappears when touching the very bottom of the screen. This issue persists when restarting the device and opening up KOReader. 
[crash.log](https://github.com/koreader/koreader/files/5344214/crash.log)

I could read a book with KOReader in this state but I cannot configure the font size and other parameters I would want to change starting a new book.

What is the best way to reslove this?

#### Steps to reproduce

After finishing my first book since the new update, this issue arose when I started another book. Otherwise nothing out of the ordinary happened to cause this issue

**Comment by NiLuJe** [comment]
Would you maybe happen to have enabled the "Only swipe" behavior for menus?

(Gear > Taps and gestures > Activate menu >)

**Comment by maximovi** [comment]
Yes that's it.  I never knowingly enable this. I am sorry to have wasted your time in creating an issue for this. Nonetheless, thank you very much for your help.
