### ISSUE TITLE
AutoSuspend plugin should not be disabled on remarkable

### ISSUE THREAD

**Issue by soaringgaijin** [koreader/koreader#6769]
I am running KOReader on a Remarkable tablet. I noted that the device never enters standby while running KOReader. Apparently, the original system software must be running to have the device sleep automatically.

However, setting "auto_suspend_time_seconds" in settings.reader.lua never seemed to change anything. I checked the plugin itself and noted that autosuspend.koplugin/main.lua starts with

```
if not Device:isCervantes() and not Device:isKobo() and not Device:isSDL() and not Device:isSonyPRSTUX()
then
    return { disabled = true, }
end
```

Comenting out those lines makes it work as intended, putting the Remarkable to sleep after the defined number of seconds.

Is there some specific reason why the plugin is not enabled by default on Remarkable? It is immensely useful, since I constantly forget to push the hardware button for standby when interrupting my reading, only to come back to a device with empty battery a few hours later.

**Comment by pazos** [comment]
It was untested. Feel free to submit a PR if it works for you

**Comment by gbyl** [comment]
@soaringgaijin please do submit a pull request. I'm going to test this out myself. I asked a similar question and this is the reply that I got https://github.com/koreader/koreader/issues/6028#issuecomment-698566960

**Comment by gbyl** [comment]
I can confirm that this worked! With a minor caveat… it's *timeout* not "time". I commented out those lines from `/koreader/plugins/autosuspend.koplugin/main.lua` and added `["auto_suspend_timeout_seconds"] = 300,` to my `settings.reader.lua` and after 5 min it suspended automatically. Let's add it to the main branch.

**Comment by gbyl** [comment]
Not only that, but autoshutdown works too now! @Eeems This might be of interest to you too.

**Comment by Eeems** [comment]
> Not only that, but autoshutdown works too now! @Eeems This might be of interest to you too.

I already have a good idea of what has to happen for auto shutdown in Oxide. I just haven't had time to implement it.

That said, I will have to test to see if this plays nicely with oxide or not. Likely I'll have to submit a PR to make it play nice when running under Oxide.
