### ISSUE TITLE
android: bugs and differences between HW/SW rotation

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6771]
* KOReader version: 2020.7+
* Device: Android

#### background

Support for Android native rotation was added in https://github.com/koreader/koreader/commit/7094519e1bf08dbd4117fc3d969ec44cd9ed6b9c.
The main benefit is no overhead in rotated modes (specially notable with keyboard)

It didn't work fine on pre-kitkat emulators so I left them with SW rotation. Because android is usually bad implemented or very broken I also added [code to handle 4.4+ that don't play nice with surface changes](https://github.com/koreader/android-luajit-launcher/commit/516ba8c499cfb95eb984990201edc9bf0601facf)

#### Issue 1

- Notched devices w/ HW rotation **could** have a bad viewport when rotated (**confirmed**). 

#### issue 2

- 90º and 270º rotas are swapped between HW and SW devices (or at least rota is inverted between my phone and my Cervantes). (**confirmed**)

#### issue 3

- Devices w/ HW rotation that use landscape as default orientation have a bug in rotation code [ 0 -> 270, 90 -> 0, 180 -> 90, 270 -> 180] (reported by [mobileread's u/Xwang](https://www.mobileread.com/forums/showpost.php?p=4043532&postcount=307)

#### Steps to reproduce

- issue 1 requires a device with a notch. Just set a 90º/270º rota. It is the display fine or some part of the UI is out of bounds?

- issue 2 requires a device with HW rotation and one w/SW rotation. Do them rotate equal or values are swaped?

- issue 3 requires a very special snowflake device. Sadly most devices I'm aware use portrait as native orientation (even if they're emulators and are presented to you as landscape)

Anyways, all the three issues are easy to workaround. Issue 1 is **hard** to get done well as it involves messing with device viewport, but a quick workaround could be disable HW rotation. As they're all modern phones the change shouln't be that noticeable.

If you're experiencing some of these bugs and want to help debugging please post here.

**Comment by ezdiy** [comment]
Yup, when doing my linuxfb rot stuff, what android did essentially amounted to dead road. There's bunch of rotation hooks for linuxfb that android should be technically doing. I don't have the nerves of steel one needs to develop for android, but can probably sketch what needs to be done.

**Comment by NiLuJe** [comment]
As far as issue 2 is concerned, I wouldn't necessarily trust anything an NTX board has to say about HW rotation either, their kernels do... insanely weird crap ^^.

**Comment by NiLuJe** [comment]
I can definitely confirm 1. on a notched phone on P.

And also that the FM rotation is borked like on that recent issue I can't find :D.

**Comment by NiLuJe** [comment]
And that's also a yes on 2., they're indeed inverted ;).

**Comment by pazos** [comment]
@NiLuJe: cool, I guess :p 

Issue 1 can be workarounded easily by disabling HW rotation if notch_size > 0 px. A proper handle would involve using notch_size and current rota to compute the viewport and apply it with [`Device:setViewport`](https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L299-L303). Old phones use that to [toggle the legacy "action bar"](https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L309-L321) It is not fun and quite hackish but something like that should work.

Issue 2 is easier. Just Swap Landscape and reverse landscape in https://github.com/koreader/koreader-base/blob/master/ffi/framebuffer_android.lua#L95-L103

Issue 3 does involve the same function than issue 2. Just don't assume 0 is PORTRAIT and retrieve initial orientation to decide if we need to start with 0 == landscape (reversed or not)

**Comment by yparitcher** [comment]
related: https://github.com/koreader/koreader/issues/6704

I think this is due to the fact that Android HW rotation was never fixed to handle the FM when we redid rotation a few months back

**Comment by pazos** [comment]
>  I think this is due to the fact that Android HW rotation was never fixed to handle the FM when we redid rotation a few months back

Indeed. In fact android HW rotation was made possible by your rota refactor :). I did tested CRe documents and there everything worked fine, but the bug in FM is there from the very begin :P

**Comment by Galunid** [comment]
> Notched devices w/ HW rotation could have a bad viewport when rotated (needs to be confirmed).
I confirm, bottom menu is moved up by notch height and notch doesn't reduce width (phone's height in this case)

Issue 2 I can't really test, since my device refuses to do any SW rotation in KOReader (I don't see an option to toggle this in any menu, tried with today's nightly)

I can't seem to select 180 degrees rotation though, it's always set to 0

**Comment by pazos** [comment]
https://github.com/pazos/android-luajit-launcher/tree/fix_hw_rota should fix the three issues.

But I cannot test issue 3 as I don't have a device that boots in landscape and I cannot emulate one :(

**Comment by NiLuJe** [comment]
@pazos: I don't usually have an Android TC on hand, so, if you happen to have a test build... :o)

**Comment by Galunid** [comment]
I tried building using docker image, got warning, that's probably safe to ignore
```
This app only has 32-bit [armeabi-v7a] native libraries. Beginning August 1, 2019 Google Play store requires that all apps that include native libraries must provide 64-bit versions. For more information, visit https://g.co/64-bit-requirement
```

and failure with:

```
Task :app:stripArmFullStorageReleaseDebugSymbols FAILED
No toolchains found in the NDK toolchains folder for ABI with prefix: aarch64-linux-android
```

Not sure if it's something on my end, I report it just in case. I can build `master`, can't build with your commits (`pazos:hw_rota_fix`).

Alias I use to build, in case it helps.
```bash
alias koreader_build_android='docker run -v "$(pwd):/home/ko/koreader" -v /home/kris/.gradle:/home/ko/.gradle -it koreader/koandroid:0.3.1 bash -c "source ~/.bashrc && pushd koreader && ./kodev release android"; pushd platform/android/luajit-launcher && rm -rf jni/luajit/luajit-2.0/.git && git reset --hard HEAD && popd && /opt/android-sdk/build-tools/30.0.2/apksigner sign --ks my.keystore *.apk'
```

**Comment by pazos** [comment]
@Galunid: it is a problem in the docker image. It has a stripped TC.

 The problem is the new gradle distribution in: https://github.com/koreader/android-luajit-launcher/commit/f2a19bb5e52f09f706bc0beb720722ab820ccc87#diff-fd9d61e37d939c941e7a62077f38d62  required a new gradle plugin https://github.com/koreader/android-luajit-launcher/commit/f2a19bb5e52f09f706bc0beb720722ab820ccc87#diff-c197962302397baf3a4cc36463dce5ead

If you revert to gradle distribution 5.1.1 and gradle plugin 3.4.2 you can build just fine. You'll miss the new warnings too, which inform us which is the only requisite we don't match to publish on the play store :p

**Comment by pazos** [comment]
Note to @Frenzie: don't strip any ABI from the next Docker image (probably the original armeabi is it safe to remove as is isn't supported now). Anways, it looks like a fail on gradle itself as the error:

`No toolchains found in the NDK toolchains folder for ABI with prefix: aarch64-linux-android` doesn't make sense on a task named `stripArmFullStorageReleaseDebugSymbols` which is armeabi-v7a

**Comment by pazos** [comment]
@Galunid @NiLuJe: test APK in https://www.dropbox.com/s/34zjxqocc5rtkqd/koreader-2020.10%2BRota.apk?dl=0. It uses an old tag but should match current master + changes above.

**Comment by Galunid** [comment]
@pazos Just build it myself (after reverting the gradle stuff), and it works (at least issue 1) on android 10. 180 degrees rotation works too.
Issue 2 seems fixed too (my phone's rotation is the same as Kobo)

**Comment by pazos** [comment]
> Issue 2 seems fixed too (my phone's rotation is the same as Kobo)

You can't test that on a device with a notch, because issue 2 requires a HW rotation and now notched devices are using SW rotation. If you still have an onyx reader you can test there, if you wish :)

**Comment by Galunid** [comment]
@pazos Doesn't work. When you select 90 degrees counter clockwise it rotates 90 degrees clockwise, and makes 90 degrees clockwise button active. Same for the other one. Still can't select 180 degrees rotation (always stays portrait, doesn't "select" 180 degrees button)

**Comment by pazos** [comment]
@Galunid: to be sure we all speak the same language I'm going to talk based on image in https://github.com/koreader/koreader-base/blob/master/ffi/framebuffer.lua#L44-L58 :)

There's 4 rotation modes, on the UI they are `90º | 0º | 90º | 180º` and should match `3 | 0 | 1 | 2` in the image. That's what I see on the emulator in both HW and SW rotas.

About reverse portrait not working I'm afraid that's a limitation of the device. We cannot fix that if the framework doesn't admit that orientation (no other app should be able to do that). About the button "doesn't select a specific rotation", it is a side effect of the code reporting the real rotation, which would be the last one if 180º doesn't work on a device.

**Comment by NiLuJe** [comment]
@pazos: Thanks, all good on my end (notch, P) ;).

**Comment by Frenzie** [comment]
@pazos 
> Note to @Frenzie: don't strip any ABI from the next Docker image (probably the original armeabi is it safe to remove as is isn't supported now). Anways, it looks like a fail on gradle itself as the error:
> 
> No toolchains found in the NDK toolchains folder for ABI with prefix: aarch64-linux-android doesn't make sense on a task named stripArmFullStorageReleaseDebugSymbols which is armeabi-v7a

O-o

The image is already awfully close to 50 gigabyte. >_>

**Comment by Galunid** [comment]
@pazos When I select 3, it gives me 1, and makes button 1 active, when I select 1, it rotates 3 and makes button 3 active. About the 180 thingy I reported just in case, as long as you're aware it's fine by me

**Comment by pazos** [comment]
> When I select 3, it gives me 1, and makes button 1 active, when I select 1, it rotates 3 and makes button 3 active.

It doesn't make sense unless your device wasn't affected by issue 2 in the first place (ie: HW rota was ok and the same as emulators/kobos..).

Anyways, I uploaded a new version which should fix logic issues in landscape and doesn't need changes in koreader-base. Please test: https://www.dropbox.com/s/34zjxqocc5rtkqd/koreader-2020.10%2BRota.apk?dl=0

If you still have the same bug on the new version I guess we need to workaround it for that device in particular, as both my tablet, my phone and every working emulator now behave as expected :)

**Comment by Galunid** [comment]
@pazos This one works

**Comment by NiLuJe** [comment]
Still good on my end, too ;).
