### ISSUE TITLE
FR: Link to footnote page in footnote pop-up

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#6773]
When reading books with footnotes I prefer footnote pop-ups or in-page footnotes rather than following the footnote link and going back. However, sometimes I want to highlight some text in a footnote which is not possible in the pop-up or the in-page footnote. (Also, highlighting across multiple pages is not possible when in-page footnotes are activated, which is another issue.)

I would like a link in the footnote pop-up or in-page footnote that takes me to the actual page where the footnote is. (Kobo has this implemented with a "See more" button.) There I could highlight the text and then go back to my reading position.

**Comment by hius07** [comment]
Have you tried a long press on the footnote number in the main text and then "Follow Link"?

**Comment by poire-z** [comment]
> sometimes I want to highlight some text in a footnote which is not possible in the pop-up or the in-page footnote

Some technical details in https://github.com/koreader/koreader/issues/6622#issuecomment-685686730 and around.

> Also, highlighting across multiple pages is not possible when in-page footnotes are activated, which is another issue

Works for me: when selecting and reaching the bottom right corner of screen (so, go thru/over the footnote text to reach that corner, even if nothing of the footnote text is selected), it switches temporarily to scroll mode where in-page footnotes are removed.

> I would like a link in the footnote pop-up or in-page footnote that takes me to the actual page where the footnote is. (Kobo has this implemented with a "See more" button.) There I could highlight the text and then go back to my reading position.

It's already possible (and no need to add a button and lose some space):
- in popup footnotes: swipe to the left (in the popup or anywhere else when the popup is shown) to follow the link to the real footnote page - and there, swipe to the right to go back.
- with in-page footnotes: tap or swipe to the left on/around the footnote link/number in the main text - and there, swipe to the right to go back (provided you have this enabled in the Link> menu).

**Comment by LucyOne** [comment]
Thanks, I didn't know about any of these options! They do the trick. Issue closed.
