### ISSUE TITLE
Question: Best workflow to manually install nightly builds?

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6774]
- Device: Remarkable

As we do not have Wi-Fi implemented on the remarkable port, this is what I do currently:
1. scp *current_koreader* from device to computer
2. Download and unzip nightly.zip
3. locally rsync nightly to current
4. scp the result back to my device

I have tried just transfering the nightly and running unzip, but that deletes my settings, fonts, etc. Is there a better workflow that you would recommend?

**Comment by Galunid** [comment]
Not sure if remarkable supports OTA, but that's the first thing I'd look at (it's probably not supported, but just in case ;)). If not, you can probably extract zip on top of *current_koreader*. So workflow would look like that:
1. Download nightly
2. scp nightly to device
3. ssh into device and extract on top of current koreader directory
**To prevent deletion of settings, you should copy `defaults.lua` as `defaults.persistent.lua`, as per [documentation](https://github.com/koreader/koreader/wiki/Change-defaults).** Of course making a copy of the current directory won't hurt ;)
I have no idea, why fonts get deleted, unless you use something like `rsync -av --delete source dest`. The basic idea is to unzip on top of the current directory, so they get merged.

**Comment by NiLuJe** [comment]
Yep, as @Galunid said, doing it the other way around (i.e., scp nightly zip *to* the device, unzip *from* the device) is essentially what the OTA does, and it definitely won't touch your settings.

**Comment by gbyl** [comment]
@Galunid @NiLuJe I just tried it with the latest nightly and it definitely worked. My fonts are still there too. I was not aware of the `defaults.persistent.lua` trick. I suppose we can close this now. Thank you!
