### ISSUE TITLE
[translation] Arabic is missing from Weblate

### ISSUE THREAD

**Issue by WaseemAlkurdi** [koreader/koreader#6775]
Hi folks! 
I wanted to continue my unfinished Arabic translation of KOReader, only to find that for some reason, it's no longer available on Hosted Weblate. Can anyone check what would the issue possibly be?

**Comment by WaseemAlkurdi** [comment]
Alright, so I requested a new translation, it was approved within a few minutes, and I uploaded `koreader.po` straight from the koreader/koreader-translations repository ... it worked, but isn't it odd why would the translation "vanish" all of the sudden?

**Comment by Frenzie** [comment]
It hasn't, you tricked me (in a manner of speaking).

**Comment by Frenzie** [comment]
The ar_AA name is apparently the name from Transifex but Weblate just uses ar.

**Comment by Frenzie** [comment]
It's in https://github.com/koreader/koreader-translations/blob/b077a9ab66f28393d8048c5078c35dd65cc6c035/ar_AA/koreader.po

**Comment by Frenzie** [comment]
So I think I should delete the new one and rename that one for continuity, probably?

**Comment by Frenzie** [comment]
Since now it's double.

**Comment by Frenzie** [comment]
Also the old one seems to have a few more things in it?
![Screenshot_2020-10-09_19-03-36](https://user-images.githubusercontent.com/202757/95611466-26dca800-0a62-11eb-93d1-85a3b2e2e4e5.png)

**Comment by Frenzie** [comment]
@WaseemAlkurdi I resolved the duplicate as I proposed, by replacing the brand new duplicate with the old one that happened to be hidden from Weblate. :-)

In Weblate there are some automated checks to help with translation quality btw. (Of course you should ignore them if any of those are on purpose.)

https://hosted.weblate.org/projects/koreader/koreader/ar/

![Screenshot_2020-10-09_19-12-43](https://user-images.githubusercontent.com/202757/95612265-6c4da500-0a63-11eb-8ff1-125178c311ef.png)

**Comment by WaseemAlkurdi** [comment]
> The ar_AA name is apparently the name from Transifex but Weblate just uses ar.

That's probably why, though I'm certain I've translated Arabic on Weblate before 😅️



> @WaseemAlkurdi I resolved the duplicate as I proposed, by replacing the brand new duplicate with the old one that happened to be hidden from Weblate. :-)
> 
> In Weblate there are some automated checks to help with translation quality btw. (Of course you should ignore them if any of those are on purpose.)
> 
> https://hosted.weblate.org/projects/koreader/koreader/ar/
> 
> ![Screenshot_2020-10-09_19-12-43](https://user-images.githubusercontent.com/202757/95612265-6c4da500-0a63-11eb-8ff1-125178c311ef.png)

Very well .. I'll check those! Those might be back from the days where I did the translation directly in the `.po` file, using a regular text editor.

> Also the old one seems to have a few more things in it?
> ![Screenshot_2020-10-09_19-03-36](https://user-images.githubusercontent.com/202757/95611466-26dca800-0a62-11eb-93d1-85a3b2e2e4e5.png)
> ![Screenshot_2020-10-09_19-04-37](https://user-images.githubusercontent.com/202757/95611579-4d024800-0a62-11eb-887e-29162e657cbd.png)

No problem, I'll re-do those 👌️

**Comment by Frenzie** [comment]
No need, I put back the old one. ;-)

**Comment by WaseemAlkurdi** [comment]
@Frenzie Thanks a bunch! :heart_eyes: 
I think we can close this now ...
