### ISSUE TITLE
KOReader 2020.10 won't start

### ISSUE THREAD

**Issue by Matthaiks** [koreader/koreader#6780]
* KOReader version: koreader-kindle-v2020.10
* Device: Amazon Kindle 5 Classic

#### Issue
KOReader 2020.10 won't start, KOReader 2020.09 runs fine.

#### Steps to reproduce
Install KOReader 2020.10 on Kindle 5 Classic and try to run it.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/5360942/crash.log)

**Comment by Frenzie** [comment]
Probably a relatively innocent oversight, should put out a 10.1 tough. :-)
```
./luajit: frontend/device/kindle/device.lua:455: attempt to call method 'blacklistCBB' (a nil value)
stack traceback:
```

**Comment by Frenzie** [comment]
If I understand correctly in my quick skim then following https://github.com/koreader/koreader/pull/6696 the offending lines can simply be removed. Pinging @ezdiy.

**Comment by NiLuJe** [comment]
Yep, there are a couple of those left in there, not only that one, but that's the idea ;).

Will double check later this afternoon ;).

**Comment by Frenzie** [comment]
Hence line*s*, not line. ;-)

**Comment by ezdiy** [comment]
Yep. My bad.

**Comment by Frenzie** [comment]
@Matthaiks Would you mind confirming if it's all working as it should? You can find it at http://build.koreader.rocks/download/nightly/v2020.10-2-gd2f533e_2020-10-11/

**Comment by NiLuJe** [comment]
Oh, I did actually test on a K4 (that's what I meant by "double-check" ;)) ;).

**Comment by Matthaiks** [comment]
@Frenzie I've updated device.lua and it's working now. Thanks for the fix!
