### ISSUE TITLE
FR: Delete entry from Calendar (for a specific date or not)

### ISSUE THREAD

**Issue by sat3ll** [koreader/koreader#6784]
**Does your feature request involve difficulty completing a task? Please describe.**
I'd like to exclude some files or delete certain entries for a given day (or all entries for a specific file).
Useful when files are opened accidentally or aren't interesting for tracking.

**Describe the solution you'd like**
Long press on an entry to delete when viewing a date.
Option at Book info to exclude tracking/delete entries in calendar.

**Comment by NiLuJe** [comment]
Tools > Reset statistics

Includes a whole lot of ways to delete stats for stuff based on total reading time, which appears to be what you're looking for.

#6778 will also include an option for the currently open book.

**Comment by sat3ll** [comment]
Thanks! That feature does most of what I was looking for though it's still missing the ability to erase an entry for a specific day (accidental opens or uninteresting documents).

**Comment by NiLuJe** [comment]
For now, you'll have to dig those up manually via the plain listing by name, yeah.

(Or catch 'em w/ the < n min catchall, which should at least take care of accidental opens).
