### ISSUE TITLE
Version 2020.10 Crashed when I exited from reading a book

### ISSUE THREAD

**Issue by red-riptide** [koreader/koreader#6793]
1. Open a book and read
2. Exit from  reading via navigation or file list button
3. The reader will crash and show debug info about bad argument at blitbuffer.lua  987 line.

**Comment by gbyl** [comment]
This has been fixed by the latest [nightly build](http://build.koreader.rocks/download/nightly/)

**Comment by red-riptide** [comment]
Ok, thanks.

**Comment by gbyl** [comment]
No problem. This is a duplicate of: https://github.com/koreader/koreader/issues/6790 and https://github.com/koreader/koreader/issues/6787
