### ISSUE TITLE
Display mode has defaulted to "Classic (filename only)" and crashes when another view is selected

### ISSUE THREAD

**Issue by everdred** [koreader/koreader#6797]
* KOReader version: 2020.10.1
* Device: Android phone 

#### Issue
Display mode has defaulted to "Classic (filename only)" and crashes when another view is selected.

#### Steps to reproduce
My display mode has been "Detailed list with cover images and metadata" for some time, but since upgrading to 2020.10 the display mode has switched itself to Classic, and the application crashes when another view is selected.

This reproduces on Android, but not Kobo or amd64 (all on version 2020.10.1).

##### `crash.log` (if applicable)

10-15 22:38:50.565   961  1127 I ActivityManager: Start proc 16522:org.koreader.launcher/u0a192 for pre-top-activity {org.koreader.launcher/org.koreader.launcher.MainActivity}
10-15 22:38:50.883 16522 16522 I KOReader: Application started
10-15 22:38:50.883 16522 16522 I KOReader: Application info {
10-15 22:38:50.883 16522 16522 I KOReader:   VM heap: 256MB (normal)
10-15 22:38:50.883 16522 16522 I KOReader:   Flags: user.
10-15 22:38:50.883 16522 16522 I KOReader:   Paths {
10-15 22:38:50.883 16522 16522 I KOReader:     Assets: /data/user/0/org.koreader.launcher/files
10-15 22:38:50.883 16522 16522 I KOReader:     Library: /data/app/org.koreader.launcher-9LJj4RsWVd1g-zL2Xq37jg==/lib/arm
10-15 22:38:50.883 16522 16522 I KOReader:     Storage: /storage/emulated/0
10-15 22:38:50.883 16522 16522 I KOReader:   }
10-15 22:38:50.883 16522 16522 I KOReader: }
10-15 22:38:50.902 16522 16522 I KOReader: [LightsFactory]: Using Generic Lights Controller
10-15 22:38:51.091 16522 16544 I KOReader: Check file in asset module: koreader-v2020.10.1-1-gdfe3502_2020-10-15.zip
10-15 22:38:51.103 16522 16544 I KOReader: Skip installation for revision v2020.10.1-1-gdfe3502_2020-10-15
10-15 22:38:51.103 16522 16544 I KOReader: Change directory to assets dir: /data/user/0/org.koreader.launcher/files -> /data/data/org.koreader.launcher/files
10-15 22:38:51.161 16522 16544 I KOReader: command chmod 755 ./sdcv returned 0
10-15 22:38:51.181 16522 16544 I KOReader: command chmod 755 ./tar returned 0
10-15 22:38:51.271 16522 16544 I KOReader:  platform thirdparty apps
10-15 22:38:51.271 16522 16544 I KOReader: -> Aard2 (itkach.aard2), role: dict, available: true
10-15 22:38:51.271 16522 16544 I KOReader: -> Alpus (com.ngcomputing.fora.android), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> ColorDict (com.socialnmobile.colordict), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> Eudic (com.eusoft.eudic), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> EudicPlay (com.qianyan.eudic), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> Fora (com.ngc.fora), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> ForaPro (com.ngc.fora.android), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> GoldenFree (mobi.goldendict.android.free), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> GoldenPro (mobi.goldendict.android), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> Kiwix (org.kiwix.kiwixmobile), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> Mdict (cn.mdict), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: -> QuickDic (de.reimardoeffinger.quickdic), role: dict, available: false
10-15 22:38:51.271 16522 16544 I KOReader: Android 10 - Q (API 29) - flavor: rocks
10-15 22:38:51.282   961  2758 I ActivityManager: Process org.mozilla.fennec_fdroid:media (pid 15557) has died: cch+70 CEM 
10-15 22:38:51.283   961  2758 W ActivityManager: Scheduling restart of crashed service org.mozilla.fennec_fdroid/org.mozilla.gecko.media.MediaManager in 1000ms
10-15 22:38:51.319 16522 16544 I KOReader:  initializing for device sailfish
10-15 22:38:51.319 16522 16544 I KOReader:  framebuffer resolution: {
10-15 22:38:51.319 16522 16544 I KOReader:     ["w"] = 1080,
10-15 22:38:51.319 16522 16544 I KOReader:     ["h"] = 1920
10-15 22:38:51.319 16522 16544 I KOReader: }
10-15 22:38:51.387   961  1780 I ActivityManager: Process com.google.android.partnersetup (pid 15353) has died: cch+75 CEM 
10-15 22:38:51.407   961 10718 I ActivityManager: Process com.google.android.apps.wellbeing (pid 15511) has died: cch+65 CEM 
10-15 22:38:51.415   961  5618 I ActivityManager: Process com.duckduckgo.mobile.android (pid 15128) has died: cch+65 CEM 
10-15 22:38:51.462   961 10718 I ActivityManager: Process org.mozilla.fennec_fdroid (pid 7198) has died: cch+60 CAC 
10-15 22:38:51.471   961 10718 W ActivityManager: Scheduling restart of crashed service org.mozilla.fennec_fdroid/org.mozilla.gecko.gfx.SurfaceAllocatorService in 10812ms
10-15 22:38:51.485   961  1119 W ActivityManager: setHasOverlayUi called on unknown pid: 7198
10-15 22:38:51.497   961 10718 I ActivityManager: Process org.quantumbadger.redreader (pid 15480) has died: cch+65 CEM 
10-15 22:38:51.545   961  8094 I ActivityManager: Process org.mozilla.fennec_fdroid:tab0 (pid 7274) has died: fore SVC 
10-15 22:38:51.891 16522 16544 I KOReader:  Loading plugins from directory: plugins
10-15 22:38:51.893 16522 16544 I KOReader:  Plugin  plugins/keepalive.koplugin/main.lua  has been disabled.
10-15 22:38:51.904 16522 16544 I KOReader:  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
10-15 22:38:51.972 16522 16544 I KOReader:  Plugin  plugins/backgroundrunner.koplugin/main.lua  has been disabled.
10-15 22:38:52.031 16522 16544 I KOReader:  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
10-15 22:38:52.042 16522 16544 I KOReader:  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
10-15 22:38:52.048 16522 16544 I KOReader:  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
10-15 22:38:52.058 16522 16544 I KOReader:  Plugin  plugins/autosuspend.koplugin/main.lua  has been disabled.
10-15 22:38:52.068 16522 16544 I KOReader:  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
10-15 22:38:52.074 16522 16544 I KOReader:  FM loaded plugin batterystat at plugins/batterystat.koplugin
10-15 22:38:52.074 16522 16544 I KOReader:  FM loaded plugin calibre at plugins/calibre.koplugin
10-15 22:38:52.085 16522 16544 E KOReader:  Failed to initialize coverbrowser plugin:  plugins/coverbrowser.koplugin/bookinfomanager.lua:176: 'struct 4440' has no member named 'set_busy_timeout'
10-15 22:38:52.085 16522 16544 I KOReader:  FM loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
10-15 22:38:52.087 16522 16544 I KOReader:  FM loaded plugin evernote at plugins/evernote.koplugin
10-15 22:38:52.094 16522 16544 I KOReader:  FM loaded plugin gestures at plugins/gestures.koplugin
10-15 22:38:52.095 16522 16544 I KOReader:  FM loaded plugin goodreads at plugins/goodreads.koplugin
10-15 22:38:52.095 16522 16544 I KOReader:  FM loaded plugin movetoarchive at plugins/movetoarchive.koplugin
10-15 22:38:52.095 16522 16544 I KOReader:  FM loaded plugin newsdownloader at plugins/newsdownloader.koplugin
10-15 22:38:52.096 16522 16544 I KOReader:  FM loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
10-15 22:38:52.096 16522 16544 I KOReader:  FM loaded plugin profiles at plugins/profiles.koplugin
10-15 22:38:52.096 16522 16544 I KOReader:  FM loaded plugin readtimer at plugins/readtimer.koplugin
10-15 22:38:52.096 16522 16544 I KOReader:  FM loaded plugin send2ebook at plugins/send2ebook.koplugin
10-15 22:38:52.100 16522 16544 I KOReader:  FM loaded plugin statistics at plugins/statistics.koplugin
10-15 22:38:52.100 16522 16544 I KOReader:  FM loaded plugin systemstat at plugins/systemstat.koplugin
10-15 22:38:52.100 16522 16544 I KOReader:  FM loaded plugin terminal at plugins/terminal.koplugin
10-15 22:38:52.100 16522 16544 I KOReader:  FM loaded plugin texteditor at plugins/texteditor.koplugin
10-15 22:38:52.100 16522 16544 I KOReader:  FM loaded plugin wallabag at plugins/wallabag.koplugin
10-15 22:38:56.932 16522 16544 E KOReader: [NativeThread]: failed to run script: plugins/coverbrowser.koplugin/bookinfomanager.lua:291: attempt to index field 'get_stmt' (a nil value)
10-15 22:38:56.932 16522 16544 E KOReader: [NativeThread]: Stopping due to previous errors
10-15 22:38:56.982   961  2798 I ActivityManager: Process org.koreader.launcher (pid 16522) has died: fore TOP 
10-15 22:38:57.029   961  1119 W ActivityManager: setHasOverlayUi called on unknown pid: 16522
^C

**Comment by NiLuJe** [comment]
You're running 2020.10.1-1 (i.e., the nightly), not 2020.10.1 (i.e., the stable). It was broken, and has been pulled.
