### ISSUE TITLE
Bug: Calibre connect does not work on PocketBook 626

### ISSUE THREAD

**Issue by spawly** [koreader/koreader#6802]
* KOReader version: 2020.10.1
* Device: PocketBook 626 Touch
* Calibre version: 5.3.0

#### Issue
Can not connect to calibre server to upload books from calibre.

Used docs from here:
https://github.com/koreader/koreader/wiki/Calibre-wireless-connection

#### Steps to reproduce
1. Opened calibre. Started Wireless connection with default parameters
2. PocketBook and laptop are connected to the same network over wifi.
3. On Pocketbook go to Koreader > Go to plugins > Calibre > Connect

Result is the message: can not connect to calibre server.

Any changes in options did not help. Can not make it work(

**Comment by Galunid** [comment]
* Did you specify server address and port in the options, to the one calibre shows?
* Can you do other network operations?
* Please provide more logs, it'll be very hard to help you without them.
