### ISSUE TITLE
PB632: koreader crashes when loading a PDF file

### ISSUE THREAD

**Issue by mikhaeld** [koreader/koreader#6803]
* KOReader version: 2020.10
* Device: PocketBook Touch HD3 fw: U632.5.19.832

#### Issue
After upgrading to v2020.10, every time I open a PDF file after I previously opened an ePub one, koreader crashes.
This happens with any PDFs/ePubs I tested.

#### Steps to reproduce
1. Start koreader
2. Go to History
3. Open an ePub file from the history list
4. Go to History again and open a PDF from the list
5. koreader crashes showing a nice logo with a bomb that's about to explode :) 

After restarting koreader the crash does not happen if the first file I open is a PDF.
Also the crash does not happen if I open a PDF after another PDF.

##### `crash.log` (if applicable)

[crash-koreader-2020.10_PB632.log](https://github.com/koreader/koreader/files/5398079/crash-koreader-2020.10_PB632.log)

**Comment by Galunid** [comment]
Update to v2020.10.01, it should be fixed there. 
Duplicate of #6790, #6787, #6793

**Comment by mikhaeld** [comment]
Thanks, it's fixed in the new version.
Next time I'll make sure to look first for duplicates in the closed issues :D .
