### ISSUE TITLE
Crash on Tolino with #6876 applied

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6806]
* KOReader version: v2020.10.1-10-ga73bf1af_2020-10-20
* Device: Tolino Epos2

#### Issue
KOReader crashes when a73bf1afda2568724546f22f3fe3841b31660ec9 (#6786) is applied. 
See full adb logcat
[o.txt](https://github.com/koreader/koreader/files/5409948/o.txt)

On an Android mobile, there is no problem.

#### Steps to reproduce
Start KOReader and see crashlog

##### `crash.log` (if applicable)
[oo.log](https://github.com/koreader/koreader/files/5409980/oo.log)

**Comment by ezdiy** [comment]
In https://github.com/koreader/koreader-base/blob/master/ffi/harfbuzz.lua#L24

Replace the line:
```lua
hb_lang = ffi.string(hb.hb_language_to_string(hb_lang))
```
with:
```lua
require("logger").dbg(hb_lang)
hb_lang = hb.hb_language_to_string(hb_lang)
assert(hb_lang~=nil)
hb_lang = ffi.string(hb_lang)
```
This should tell us what's going wrong. My guess is that harfbuzz is unable to translate some special language attribute in there (the fault in strlen is indicative of ffi.string getting NULL argument).

**Comment by ezdiy** [comment]
Draft fix, in case this is the cause.

**Comment by NiLuJe** [comment]
(The debug logging toggles are available in Tools > More tools > developer options)
