### ISSUE TITLE
KOReader doesn't reuse instance sometimes with new PB-firmware

### ISSUE THREAD

**Issue by tastytea** [koreader/koreader#6808]
* KOReader version: 2020.10.1-12
* Device: Pocketbook Touch HD 3 (PB632)

#### Issue

After updating the firmware from 6.0.926 to 6.1.900, KOReader doesn't reuse existing instances anymore under some circumstances.

A similar issue existed before (#6321) but was fixed and it worked with the old firmware.

#### Steps to reproduce (1)

* Open book from library.
* Suspend to background.
* Start KOReader from menu or open a different book from the library.
* → A new KOReader instance is opened.

Opening the same book from the library brings the backgrounded instance of KOReader to the foreground, as expected.

#### Steps to reproduce (2)

* Open KOReader from menu.
* Open book.
* Suspend to background.
* Open a different book from the library.
* → A new KOReader instance is opened.

Opening KOReader from menu brings the backgrounded instance of KOReader to the foreground, as expected.

##### `/system/config/extensions.cfg`

```
cbz:@ZIP_file:1:koreader.app,eink-reader.app:ICON_ZIP
djvu:@DJVU_file:1:koreader.app,eink-reader.app:ICON_DJVU
epub:@EPUB_file:1:koreader.app,eink-reader_with_blink.app,eink-reader_with_epub2.app:ICON_EPUB
fb2:@FB2_file:1:koreader.app,eink-reader.app:ICON_FB2
mobi:@MOBI_file:1:koreader.app,eink-reader.app:ICON_MOBI
pdf:@PDF_file:1:koreader.app,eink-reader_with_pdfium.app,eink-reader_with_rmsdk.app:ICON_PDF
zip:@ZIP_file:1:koreader.app:ICON_ZIP
```

**Comment by ezdiy** [comment]
This is really odd, but unfortunately I have no way to investigate this (my device is fw6.0 only). Right after bringing koreadder to background, can you check that /tmp/koreader.pid still exists? Only if it were deleted somehow we'd be firing up new instance in the first place - https://github.com/koreader/koreader/blob/master/platform/pocketbook/koreader.app#L11

**Comment by tastytea** [comment]
* Open book from library: `/tmp/koreader.pid` doesn't exist.
* Open KOReader from menu: PID file exists and contains correct PID.
* Open KOReader from menu, then open book from library: 2 instances of KOReader are running, PID file contains PID from the one started from the menu.
* Open KOReader automatically at boot with last book: PID file doesn't exists.

I don't see any interesting in the logfile but I'm attaching it anyway: [crash.log](https://github.com/koreader/koreader/files/5422841/crash.log).

**Comment by ezdiy** [comment]
@tastytea This almost seems like you have two different koreader.app, one that spawns the pid, other that doesn't. Remember there's applications/koreader.app AND system/bin/koreader.app. Order of invocation of which might have changed in 6.1. Something may have gone haywire if you used OTA update, and not straight zip.

**Comment by tastytea** [comment]
Yes, that was it! I copied `applications/koreader.app` to `system/bin/koreader.app` and it works now.

Does `system/bin/koreader.app` not get updated via OTA update?

**Comment by ezdiy** [comment]
Am not all that familiar how ota works, @NiLuJe would know more.

**Comment by pazos** [comment]
@ezdiy: the OTA updates just perform changes in the koreader dir under applications.

**Comment by ezdiy** [comment]
@pazos Ah, I see. Not a fan of the two copies anyway, linking it should prevent future mishaps.
