### ISSUE TITLE
Reader inadvertently skips pages of epubs

### ISSUE THREAD

**Issue by blchk** [koreader/koreader#6818]
* KOReader version: 2020.10.1
* Device: Onyx Boox Poke 2 (Android 9.0)

Sometimes, when tapping on the screen to turn a page, KOReader unexpectedly _skips_ a single page. Example: I'm on page 235 of 552. Turning the page once, I end up on page 237/552 instead of 236/552.

I've made sure to disable any and all relevant gestures (Go # pages, Next chapter, Skim etc.), and I've disabled double tapping.

This has been occuring randomly with all epubs I've read, and ever since updating to the latest version. It never happened with v2020.09.

Seeing as there seem to be no other reports concerning the issue, it may well be somewhere on my end. Sadly, I'm at a loss.

**Comment by poire-z** [comment]
Might be the same thing reported at https://www.mobileread.com/forums/showthread.php?t=333958 , your device is mentionned in there.

> It never happened with v2020.09.

I don't see anything that could have changed input handling between 2020.9 and 2020.10.1 ... although I haven't followed what might have happened on the Android/Onyx front.

I assume the page that is skipped exists, and that you can access it by going back.
So, it might be a tap detected as two taps: a small bounce.
(So, may be you've become more shaky/feverish (which I hope not :) and KOReader is a good early Covid detector !)

Not yet in 2020.10.1, but in current nightly/dev-channel, there is #6798 , which allows ignoring 2 taps within a configurable delay. You might try it - at least to find out if it's indeed 2 near taps that are the reason.

**Comment by blchk** [comment]
> Might be the same thing reported at https://www.mobileread.com/forums/showthread.php?t=333958 , your device is mentionned in there.

Yes, that sounds exactly like what's happening on my end. Since the OP uses v2020.08.1, that should indeed rule out any potential buggishness with the latest release. That's good to know, at least.

> So, it might be a tap detected as two taps: a small bounce.

Hard to say. Normally, it takes a very deliberate movement to skip one or more pages, and I haven't developed Parkinson's (or Covid) -- yet. As the other OP states, the issue also doesn't occur with other reader apps.

> #6798

Thank you for looking into the tap interval setting, and for the tip. I'll have a look at the latest nightly release; it's absolutely worth a shot.

**Comment by Galunid** [comment]
Just in case
* You're on 2.3.1 firmware, not the beta 3.0?
* Does this happen when you go one page forward, or multiple ones (fast few consecutive taps)?

**Comment by blchk** [comment]
Yes, I'm still on 2.3.1 firmware. And yes, it happens when I go one page forward (or try to, anyway).

**Comment by blchk** [comment]
Alright. I've been testing the new tap interval feature using v2020.10.1-18-g1db07d1_2020-10-23, and it looks like that's indeed fixed the issue, whatever it was. I was on firmware v2.3.1 for about a week, then updated to 3.0. Everything ran (and runs) smoothly on both, without any more hiccups.

Closing this now. Thanks again, poire-z, for the help!
