### ISSUE TITLE
Crash on Tolino Epos 1 with latest version

### ISSUE THREAD

**Issue by rola25** [koreader/koreader#6819]
* KOReader version: v2020.10.1-18-g1db07d1_2020-10-23
* Device: Tolino Epos 1

#### Issue
KOReader crashes on startup

#### Steps to reproduce
Install latest version and try to start it

Perhaps it is because of the screensize of Tolino epos 1 and the new screenshot feature.

[logcat.txt](https://github.com/koreader/koreader/files/5431655/logcat.txt)

**Comment by ezdiy** [comment]
Might be also https://github.com/koreader/koreader-base/pull/1223 - not sure if that made it into your nightly.

**Comment by rola25** [comment]
This patch is already there, so this is not the problem
. Here a second logcat when root is allowed for koreader
[logcat.txt](https://github.com/koreader/koreader/files/5431715/logcat.txt)

**Comment by NiLuJe** [comment]
Try earlier nightlies until you find one that doesn't crash?

**Comment by rola25** [comment]
v2020.10.1-2-g5e231d7_2020-10-16 does not crash

**Comment by NiLuJe** [comment]
And anything past that does?

**Comment by rola25** [comment]
So I narrowed it down:
v2020.10.1-8-g0406be3_2020-10-18 works
v2020.10.1-10-ga73bf1a_2020-10-20 crashes

**Comment by NiLuJe** [comment]
Thanks, that's helpful ;).

So, probably #6786, since #6804 is in a plugin, so it'd kick in slightly later.

**Comment by pazos** [comment]
do `adb logcat -c`  to clean the log buffer and `adb logcat KOReader:V *:I` to get the full log. Start the program, let it crash, interrupt logcat and atach here the full log.

**Comment by rola25** [comment]
Here is the requested logcat
[logcat.txt](https://github.com/koreader/koreader/files/5431867/logcat.txt)

**Comment by NiLuJe** [comment]
@ezdiy: At a quick glance, #6786 no longer ensures that only files/links are passed, which might be an issue if there's some really weird shit in the folders?

Other than that, besides `string.dump` going haywire of something wonky in the FT/HB stuff, nothing jumps out :/.

**Comment by rola25** [comment]
ahh, yes I think thats the problem, I renamed the fonts folder to fonts.1 an created an empty fonts folder -> voila, it starts without crashing

**Comment by NiLuJe** [comment]
Was there anything odd in the "old" fonts folder?

(Otherwise, you can try to add each font family one by one, to try to isolate if only one of 'em is tripping something up).

**Comment by rola25** [comment]
yes, many different fonts ;-) some are in subfolders, some are directly in the folder, as you said: "weird shit in the folders" LOL

**Comment by NiLuJe** [comment]
I was thinking more in terms of stuff that isn't a file or a link (i.e, a pipe, a character/block device, etc) ^^.

**Comment by rola25** [comment]
I moved some fonts in and out from the fonts-Folder, I think it crashed on some of the .otf-Fonts, but it could also be a problem with the number of fonts, it cannot really narrow this down.

**Comment by pazos** [comment]
> I was thinking more in terms of stuff that isn't a file or a link

@NiLuJe: I doubt a link will work on `/sdcard/fonts`. Internally most storage partition are ext4 but they're managed with some kind of pretty invasive volume manager.

For example, this is the x86 emulator (25):

```
(...)
/dev/fuse /mnt/runtime/default/emulated fuse rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
/dev/fuse /storage/emulated fuse rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
/dev/fuse /mnt/runtime/read/emulated fuse rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
/dev/fuse /mnt/runtime/write/emulated fuse rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
```

**Comment by NiLuJe** [comment]
@pazos: It'd sure be surprising, yeah, hence my original comment ;).

@rola25: if you happen to definitely identify a *single* file that crashes, that'd be helpful to try to reproduce this on a less hellish platform than Android ;).

**Comment by ezdiy** [comment]
```
I/DEBUG   ( 2082):     #00  pc 00023168  /system/lib/libc.so (strlen+15)
I/DEBUG   ( 2082):     #01  pc 00047a0f  /data/app-lib/org.koreader.launcher-2/libluajit.so
```
This is a crash on ffi.string(nil) again, but this time it's not clear where it comes from (unless you're running version that in fact doesn't check the nil).

**Comment by ezdiy** [comment]
Possibly

```
function FTFace_mt.__index:getInfo()
    local finfo = {
        name = ffi.string(self.family_name),
```

@NiLuJe Looks like font with broken headers indeed.
@rola25 Can you upload a copy of the fonts folder somewhere?

**Comment by NiLuJe** [comment]
Yeah, I was going to say there aren't many of 'em left between HB & FT, and https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_facerec says this can be NULL, although the circumstances seem unlikely (in theory ;p).

**Comment by ezdiy** [comment]
@rola25 Replacing frontend/fontlist.lua with this one might work (is that even doable on android though?). https://raw.githubusercontent.com/koreader/koreader/b5d324a7c38a8db4b9ff591ec27624fbab63ca5e/frontend/fontlist.lua

**Comment by pazos** [comment]
> Replacing frontend/fontlist.lua with this one might work (is that even doable on android though?).

Yup, but it is a bit overcomplicated.


@rola25 

This is a zip with @ezdiy changes:

[scripts.afterupdate.zip](https://github.com/koreader/koreader/files/5432141/scripts.afterupdate.zip)

1. Uncompress it inside `/sdcard/koreader`
2. Uninstall and install the app again
3. Run the program

**Comment by rola25** [comment]
Because I rooted my Tolino, i can replace every file :-) So I replaced /data/data/org.koreader.launcher/files/frontend/fontlist.lua -> and yes, it works, no crash anymore!
