### ISSUE TITLE
FR: Should "Zoom to fit column" automatically switch to "Page" view mode?

### ISSUE THREAD

**Issue by potash** [koreader/koreader#6822]
**Does your feature request involve difficulty completing a task? Please describe.**
I use "continuous" view mode for most documents. So when I read a two column article and switch to "Zoom to fit column" I also need to switch to "page" view mode, or else I will scroll from the left column of a page to the left column of the next page. (Is there a major use case where it makes sense to zoom to fit column AND continuous view mode?)

**Describe the solution you'd like**
When switching zoom mode to "Zoom to fit column" automatically switch view mode to "page"

I think koreader is fantastic and have been wanting to help with development so If the you think this enhancement makes sense I might try a PR myself because it seems like it should be very simple and mostly a matter of getting a development environment set up.

**Comment by Frenzie** [comment]
You can also edit the Lua files directly btw (except on Android).
