### ISSUE TITLE
Auto refresh time

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#6824]
PW2
I have `Gear - Status bar - Auto refresh time` enabled.
It stopped auto refreshing after manually setting time via `Gear - Device - Time and date`.
Restarting KOReader has resolved the issue.

**Comment by poire-z** [comment]
> It stopped auto refreshing after manually setting time 

I guess you moved time back one hour, and if you had waited one more hour so the hour catch up with an internal timer (probably set before you moved hour back), it would have refreshed again :) 
I guess it's not really worth investigating how/when to reset timers, for a thing we do twice a year - may be just a "please restart KOReader".

**Comment by hius07** [comment]
Agree

**Comment by hius07** [comment]
BTW, I failed with setting winter time via KOReader. Tried twice, the next day turned wifi on and the Kindle restored summer time. Ended up with setting the time via Kindle settings menu, it is OK now.

**Comment by NiLuJe** [comment]
That's completely expected on a Kindle.

The settings are enabled as a remnant of legacy frameworkless devices, IIRC.
