### ISSUE TITLE
Non-book file transfer

### ISSUE THREAD

**Issue by Ico70** [koreader/koreader#6833]
Hi everyone,
It seems to me like it is already possible, but I can't figure it out. If it is not already implemented I believe it would become a highly sought after feature.
I have quite a bit custom fonts installed on default kindle memory, what I would like I to transfer those fonts from kindle space to Koreader, or even mirror them if possible.

What would be even better is ota font transfer from calibre Client to the device. Calibre introduced a unsupported format override feature which could send just about any format supported by it on Koreader, I was thinking I could disguise .ttf and .otf as a file format,and then do a mass rename, or something yielding the same result.

Anyone who likes to try out fonts has probably encountered a bit of a similar situation, moving all desired fonts unplugging, finding out they named fonts differently and gotten something else, or a medium, italicised version, anything basically that they did not want in the first place. 
I myself encountered that problem often and would frequently unplug and replug the device, because I picked something wrong because of the naming scheme or because I did not anticipate what the format would look on a device, until I tried it. 
Koreader Opds and companion alleviated those.problems, because it was simple to preview the document, do a quick touch up if something was not as desired and then quickly transfer the fixed file Via ota.
If implemented days of mass USB transfer of fonts, and trying them out until another batch, would end since it would be esy to try fonts via ota.
I know that there are a quite of font aficionados that would appreciate the feature.
The Fr was keeping in mind the use of fonts, but basically it could be any file if possible.
Thank You.

**Comment by NiLuJe** [comment]
The usual recommendation is the semi-DIY approach: i.E., scp/sftp/rclone/ftp & co.

**Comment by pazos** [comment]
Too specific.

See @NiLuJe answer for LAN OTA font transfer (or any file FWIW).

For downloading fonts over the internet see https://github.com/koreader/koreader/pull/6299 (it's almost ready, except for android. So you can copy the entire folder on your plugins folder any it should work just fine)

> What would be even better is ota font transfer from calibre Client to the device.

This is possible. See https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/extensions.lua. Just and "ttf", "otf", etc to the supported extensions. The fonts will be copied to your calibre inbox, not to your fonts dir. Patches for moving fonts to fontsdir welcome.

**Comment by Ico70** [comment]
> The usual recommendation is the semi-DIY approach: e.g., scp/sftp/rclone/ftp & co.

Thank You, unfortunately I don't have any experience with Ftp protocols. Do i just get a client for a specific Os and then connect via Koreader plugin?

> Too specific.
> 
> See @NiLuJe answer for LAN OTA font transfer (or any file FWIW).
> 
> For downloading fonts over the internet see #6299 (it's almost ready, except for android. So you can copy the entire folder on your plugins folder any it should work just fine)
> 
> > What would be even better is ota font transfer from calibre Client to the device.
> 
> This is possible. See https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/extensions.lua. Just and "ttf", "otf", etc to the supported extensions. The fonts will be copied to your calibre inbox, not to your fonts dir. Patches for moving fonts to fontsdir welcome.

Thank You for the response.
Just a few more questions. 
Would Your plugin support local network transfer or only preestablished services like gfonts, fontsquirrel and the like...
Also is it possible to do a calibre transfer, and then do a quick copy/paste from inbox to fontsdir, or would I need to add a lua entry to unhide that directory. Could You maybe guide me where the locations of those might be on the device, so I don't delete some of the folder structure by mistake? 
It would be also great if Koreader allowed jumping between the partitions of Kindle and Koreader, I won't bother you with the specifics, just ask is it possible for a c/p between reserved storage spaces, or would something break?

**Comment by Galunid** [comment]
> Thank You, unfortunately I don't have any experience with Ftp protocols. Do i just get a client for a specific Os and then connect 
via Koreader plugin?

I believe preferred way is to use build in ssh plugin, and connect using a sftp client, like `FileZilla/WinSCP`.

>Would Your plugin support local network transfer or only preestablished services like gfonts, fontsquirrel and the like...

As far as I know @pazos' plugin is only for downloading from a few sources, it doesn't support local file transfer. 

> Also is it possible to do a calibre transfer, and then do a quick copy/paste from inbox to fontsdir, or would I need to add a lua entry to unhide that directory.

If you want files to end up in koreader's fonts directory, you could try using something like MetadataPlugboards in calibre. I have no idea if it will work with fonts, but it's worth giving it a try. You can edit any file inside KOReader's folder, without risking your Kindle's system. The worst thing that can happen is you'll have to reinstall KOReader. IIRC, you shouldn't even be able to access files outside `/mnt/us/` (the directory that appears when you plug in your device via USB), without using serial port/usbms hack.

> Could You maybe guide me where the locations of those might be on the device, so I don't delete some of the folder structure by mistake?

`/mnt/us/koreader/plugins/calibre.koplugin/extensions.lua` - `/mnt/us` is the directory that appears when you plug your Kindle via USB

> It would be also great if Koreader allowed jumping between the partitions of Kindle and Koreader, I won't bother you with the specifics, just ask is it possible for a c/p between reserved storage spaces, or would something break?

There is no KOReader partition, it's just normal folder. If you want to modify KOReader, you change only stuff in that folder. I have no idea what you mean "jumping between partitions", since there's no need for any jumping.

**Comment by pazos** [comment]
> As far as I know @pazos' plugin is only for downloading from a few sources, it doesn't support local file transfer.

You can add your own repo somewhere in lan. It is basically a non-auth http server running on port 80 that responds with a json with a given scheme.

For example, a new LAN repo would look like (ie: called `mylanrepo.lua`)
```lua

local repo = FontRepo:new{
    id = "My lan repo",
    url = "http://192.168.1.100",
}

function repo:fontTable()
    local t = self:getFontTable()
    return t.items
end

return repo
```

But nope, that's not aimed at end users. Also I don't remember if I need to modify something to use http instead of https, but that can be changed.

**Comment by pazos** [comment]
> Also is it possible to do a calibre transfer, and then do a quick copy/paste from inbox to fontsdir

You can do that programatically. You just need to check that the filename sent by calibre is already a font and instead of adding it to our book list, showing the received file message and update the directory view, you just move it to the fonts dir.

So, after https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/wireless.lua#L537:

```lua
if isFont(filename) then
    -- move font to fontsdir
    moveFont(filename)
else
    -- add book to local database/table
    CalibreMetadata:addBook(arg.metadata)
    UIManager:show(InfoMessage:new{
        text = T(_("Received file %1/%2: %3"),
            arg.thisBook + 1, arg.totalBooks, BD.filepath(filename)),
        timeout = 2,
    })
    CalibreMetadata:saveBookList()
    updateDir(inbox_dir)
end
```

where `isFont(filename)` returns true if the file has a valid suffix ("ttf", "otf"...)
and `moveFont(filename)` will move the font to the fonts dir.

Something like that could be implemented quickly, but you'll need to test it yourself as that would require some changes in calibre that I don't want to do (ie: adding fonts as books in calibre)

**Comment by NiLuJe** [comment]
On a Kindle, absolutely prefer the USBNetwork to KOReader's built-in SSH server: the former is actually maintained, while I'm slowly waiting for the latter to horribly implode so I won't have to think about it ever again^^.

**Comment by Ico70** [comment]
> 
> There is no KOReader partition, it's just normal folder. If you want to modify KOReader, you change only stuff in that folder. I have no idea what you mean "jumping between partitions", since there's no need for any jumping.
Sorry just trying to address my concern in a formal manner without trying to sound snobbish or inapt, looks like I failed ^-^.
What I tried to say was, is file transfer ie. fonts possible between kindle and koreader. Meaning I put the fonts in kindle folder, and forgot I had them there, rather then going to the computer and plugging usb and doing a copy paste from one folder to another, can I do the same on the device itself from koreader file manager, and if yes is it safe? I must admit I don't actually understand most of the stuff, but I follow the development actively for a while now, because it is a wonderful program. On mobile read when I had to do a JB I researched extensively not to risk a brick, and then a maintainer said when doing a kindle build had to juggle quite a bit because of kindle internal software design, if I understood correctly I have a factory version, a kindle version, koreader, and a bunch of folder structure not available to the user, I took the impression it is a nigtmare to maintain

**Comment by Ico70** [comment]
> You can add your own repo somewhere in lan. It is basically a non-auth http server running on port 80 that responds with a json with a given scheme.
> 
> For example, a new LAN repo would look like (ie: called `mylanrepo.lua`)
> 
> ```lua
> local repo = FontRepo:new{
>     id = "My lan repo",
>     url = "http://192.168.1.100",
> }
> 
> function repo:fontTable()
>     local t = self:getFontTable()
>     return t.items
> end
> 
> return repo
> ```
> 
> But nope, that's not aimed at end users. Also I don't remember if I need to modify something to use http instead of https, but that can be changed.

Yes that looks like it could work, thank God Lua looks readable, so I shouldn't have to many difficulties. ^^

> > Also is it possible to do a calibre transfer, and then do a quick copy/paste from inbox to fontsdir
> 
> You can do that programatically. You just need to check that the filename sent by calibre is already a font and instead of adding it to our book list, showing the received file message and update the directory view, you just move it to the fonts dir.
> 
> So, after https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/wireless.lua#L537:
> 
> ```lua
> if isFont(filename) then
>     -- move font to fontsdir
>     moveFont(filename)
> else
>     -- add book to local database/table
>     CalibreMetadata:addBook(arg.metadata)
>     UIManager:show(InfoMessage:new{
>         text = T(_("Received file %1/%2: %3"),
>             arg.thisBook + 1, arg.totalBooks, BD.filepath(filename)),
>         timeout = 2,
>     })
>     CalibreMetadata:saveBookList()
>     updateDir(inbox_dir)
> end
> ```
> 
> where `isFont(filename)` returns true if the file has a valid suffix ("ttf", "otf"...)
> and `moveFont(filename)` will move the font to the fonts dir.
> 
> Something like that could be implemented quickly, but you'll need to test it yourself as that would require some changes in calibre that I don't want to do (ie: adding fonts as books in calibre)

This also looks interesting, if I come up short I'll ask on MobileRead, hopefully the big man sees the post, and guides me because I don't expect a commit based on my whim.

> On a Kindle, absolutely prefer the USBNetwork hack to KOReader's built-in SSH server: the former is actually maintained, while I'm slowly waiting for the latter to horribly implode so I have an excuse to scrap it so I won't have to think about it ever again^^.

Thankfully this looks like the most family-safe option, thank you very much.
Is it a drag and drop client or is it a command shell only, can I run it on windows, since my hdd is pretty much full, and for some reason my live usb is giving me problems.

Thank You all, I would just like to add that custom fonts are a slippery slope, and to all users reading heed my warning it could become an addiction, leading to trying out fonts instead of reading like at all!
That is why I'm grateful this project is written in Lua, because when I'm done with Python the transition shouldn't be that hard, both are very readable, to hopefully use the kindle underlying Linux to make a chmod or whatever needed to lock certain options for a certain period of time.
