### ISSUE TITLE
Info splash screen is shown rotated at start-up

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#6834]
* KOReader version: v2020.10.1-23-gac3c97a_2020-10-26 & v2020.10.1-19-g144fd78_2020-10-24 
* Device: Pocketbook Inkpad 3

A minor bug: 
After going from nightly version v2020.10.1-14-gdda9052_2020-10-22 to the two versions mentioned above, the info splash screen when opening a book from the Pocketbook main menu is shown rotated. G-sensor is turned off and the book opens normally with zero rotation, as it should.

![20201027_092705](https://user-images.githubusercontent.com/15887012/97287313-b8ab2a00-1844-11eb-9311-b85576983982.jpg)

[crash.log](https://github.com/koreader/koreader/files/5444427/crash.log)

**Comment by LucyOne** [comment]
The bug is related to Screen - E-ink settings - Refresh speed/fidelity: Setting it to anything other than Level 3 rotates the splash screen; setting it to Level 3 shows the splash screen normally, i.e. with zero rotation.
Tested with v2020.10.1-33 and v2020.10.1-39.

**Comment by rjd22** [comment]
This might be fixed with the new inview rendering so I'm closing it for now.
