### ISSUE TITLE
Sorting books by last reading broken

### ISSUE THREAD

**Issue by roger64** [koreader/koreader#6835]
* KOReader version: 2020.10.1-12
* Device:Kindle Paperwhite3

#### The above feature (sorting books by last reading) or in French "Trier par date de dernière lecture" works no more and provides now a random sorting (I have few books about fifty). After updating, it was still OK but I chose to implement another sorting for comparison purposes. When I resumed  sorting by last reading, it worked no more. **I do not know how to repair it.** 
Sorting by modification date seems more robust and keeps working normally.

There is no crash with Koreader.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by NiLuJe** [comment]
Double-check the date & time on the Kindle's side of things.

(e.g., DST may have screwed things up).

**Comment by roger64** [comment]
I saw nothing wrong on Kindle side (I never use it, it's a four years old version). It only offers hour setting not date.
On Koreader I updated the statistics which looks good (recent read books first).

**Comment by roger64** [comment]
Now it's working again. Maybe updating statistics did the trick?
