### ISSUE TITLE
same description for footnote-inpage_classic_classname and ..._smaller

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader#6836]
Minor documentation bug: the explanatory text for 

"footnote-inpage_classic_classnames" and "footnote-inpage_classic_classnames_smaller",
[frontend/ui/data/css_tweaks.lua:794](https://github.com/koreader/koreader/blob/master/frontend/ui/data/css_tweaks.lua#L794) and [frontend/ui/data/css_tweaks.lua:810](https://github.com/koreader/koreader/blob/master/frontend/ui/data/css_tweaks.lua#L810) is identical

Seen on Weblate
https://hosted.weblate.org/translate/koreader/koreader/en/?checksum=513b951d8ce8d199#comments

**Comment by poire-z** [comment]
I don't think they need to be different. In how these are displayed, the "smaller" difference (coming from the title) is quite apparent:

![image](https://user-images.githubusercontent.com/24273478/97431938-799bd800-191b-11eb-8f09-eee8a593c01a.png)

![image](https://user-images.githubusercontent.com/24273478/97431916-70127000-191b-11eb-99e6-d540448cb012.png)

I don't think there's any need to re-add "smaller" in the description to make them different.
(And I know pretty much nothing about our translation interface - but I guess them being identical makes people have to translate it once - so less work for everybody :)

**Comment by EastEriq** [comment]
Weblate asks to translate it twice, but whatever, it's definitely minor and you decide. Frans asked me to ticket it.

**Comment by poire-z** [comment]
OK, I guess that for the text to appear once, it should be written once in the code and assigned to a variable - and the variable used in the multiple places we want that text.
But in this file, it's a bit bothering, as it's a single big table - so, the text should be set at the top, far from where it is used - which I don't really like. (I'd rather add "smaller" in the text to make it different then :)
@Frenzie: any more thought ?

**Comment by Frenzie** [comment]
@poire-z You could do that if you want, but the reason it shows up twice is because there's a minor difference between the two.

**Comment by Frenzie** [comment]
`Show footnotes with classic class names` vs `Show footnotes with classic classname`. (I think it should probably be "with classic classnames".)

**Comment by Frenzie** [comment]
(And that minor difference shouldn't exist.)

**Comment by EastEriq** [comment]
It is so little effort in weblate just to copy-paste the first string to the second, or to accept the autosuggestion, that I would say you can skip it. Besides, if you change one occurrence you will mark it as needing a new translation for all languages.

**Comment by Frenzie** [comment]
@EastEriq I will fix it if no one else does, just not for the next week. And without an open ticket I'll forget. ;-)

**Comment by poire-z** [comment]
> the reason it shows up twice is because there's a minor difference between the two.

Oups, right, didn't see that :) 

>  (I think it should probably be "with classic classnames".)

Agreed. I'll fix it.
