### ISSUE TITLE
Koreader crashes on startup on Genymotion (Android 10 on x86)

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#6839]
* KOReader version: 10.1 on x86
* Device: Genymotion (Android 10)

#### Issue

KOReader shows the startup animation but crashes before showing the file manager

#### Steps to reproduce

Install an Android 10 VM in Genymotion
Install koreader-android-x86-v2020.10.1.apk
KOReader crashes between the boot animation and showing the file manager

Crash log attached. The relevant portion may be:

```
10-30 18:16:33.951  2497  2522 E KOReader: error: [string "dl.lua"]:41: error opening /data/user/0/org.koreader.launcher/files/libs/libkoreader-xtext.so: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/data/org.koreader.launcher/files/libs/libkoreader-xtext.so"...
10-30 18:16:33.951  2497  2522 E KOReader: error: [string "dl.lua"]:99: could not find library /data/user/0/org.koreader.launcher/files/libs/libkoreader-xtext.so
10-30 18:16:33.953  2497  2522 E KOReader: [NativeThread]: failed to run script: error loading module 'libs/libkoreader-xtext' from file 'libs/libkoreader-xtext.so':
10-30 18:16:33.953  2497  2522 E KOReader:      dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/data/org.koreader.launcher/files/libs/libkoreader-xtext.so"...
10-30 18:16:33.953  2497  2522 E KOReader: [NativeThread]: Stopping due to previous errors
```

[crash log.txt](https://github.com/koreader/koreader/files/5467942/crash.log.txt)

**Comment by NiLuJe** [comment]
c.f., #5602 

Mystical Andoird 10 on x86 issues, fixed in Android 11.

**Comment by JasonInOttawa** [comment]
Thanks very much. I searched for "Genymotion" but didn't think to check for the actual error symbol
