### ISSUE TITLE
Crash on pdf + reflow highlight

### ISSUE THREAD

**Issue by sr1920** [koreader/koreader#6843]
* KOReader version: v2020.10.1
* Device: reMarkable

#### Issue

Sometimes I observe crashes when highlighting on a PDF file.

#### Steps to reproduce

I have not identified a clear pattern for reproduction. It seems to depend on the PDF file and the specific part the user wants to highlight.

##### `crash.log` (if applicable)

```
ffi.load: pthread
ffi.load (warning): libpthread.so: cannot open shared object file: No such file or directory
ffi.load: libpthread.so.0
Error in pixWordMaskByDilation: imin = 2 is too small
Error in pixConnComp: pixs not defined
Error in boxaSelectBySize: boxas not defined
Error in boxaSelectBySize: boxas not defined
Error in pixaCreateFromBoxa: boxa not defined
Error in boxaSort2d: boxas not defined
Error in pixaSort2dByIndex: pixas not defined
Error in pixaaFlattenToPixa: paa not defined
Error in pixaGetBoxa: pixa not defined
./luajit: frontend/document/koptinterface.lua:1041: attempt to index field 'box' (a nil value)
stack traceback:
	frontend/document/koptinterface.lua:1041: in function 'getTextFromPositions'
	frontend/apps/reader/modules/readerhighlight.lua:824: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
	frontend/ui/uimanager.lua:800: in function 'sendEvent'
	frontend/ui/uimanager.lua:241: in function '__default__'
	frontend/ui/uimanager.lua:1194: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1262: in function 'handleInput'
	frontend/ui/uimanager.lua:1306: in function 'run'
	./reader.lua:300: in main chunk
	[C]: at 0x0001415d
!!!!
Uh oh, something went awry... (Crash n°1: 11/01/20 @ 20:46:42)
Running on Linux 4.9.84-zero-gravitas (#1 Fri Jun 26 08:19:19 UTC 2020)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/01/20-20:46:42
 [*] Version: v2020.10.1-28-g74c1813_2020-10-31
```

**Comment by pazos** [comment]
@sr1920: update to latest nightly and try to reproduce there. You're using a version older than the latest change in koptinterface

**Comment by sr1920** [comment]
I hadn't updated because the device does not recognize the last version as a stable version. Anyway, I updated it now (considering development versions also) and obtained the same error:

ffi.load: pthread
ffi.load (warning): libpthread.so: cannot open shared object file: No such file or directory
ffi.load: libpthread.so.0
Error in pixWordMaskByDilation: imin = 2 is too small
Error in pixConnComp: pixs not defined
Error in boxaSelectBySize: boxas not defined
Error in boxaSelectBySize: boxas not defined
Error in pixaCreateFromBoxa: boxa not defined
Error in boxaSort2d: boxas not defined
Error in pixaSort2dByIndex: pixas not defined
Error in pixaaFlattenToPixa: paa not defined
Error in pixaGetBoxa: pixa not defined
./luajit: frontend/document/koptinterface.lua:1041: attempt to index field 'box' (a nil value)
stack traceback:
	frontend/document/koptinterface.lua:1041: in function 'getTextFromPositions'
	frontend/apps/reader/modules/readerhighlight.lua:824: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
	frontend/ui/uimanager.lua:800: in function 'sendEvent'
	frontend/ui/uimanager.lua:241: in function '__default__'
	frontend/ui/uimanager.lua:1194: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1262: in function 'handleInput'
	frontend/ui/uimanager.lua:1306: in function 'run'
	./reader.lua:300: in main chunk
	[C]: at 0x0001415d
!!!!
Uh oh, something went awry... (Crash n°1: 11/01/20 @ 20:46:42)
Running on Linux 4.9.84-zero-gravitas (#1 Fri Jun 26 08:19:19 UTC 2020)
Attempting to restart KOReader . . .
!!!!
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/01/20-20:46:42
 [*] Version: v2020.10.1-28-g74c1813_2020-10-31

**Comment by pazos** [comment]
Now makes sense. Thanks

`self:getWordFromBoxes()` will return an empty table if no boxes, so it fails at https://github.com/koreader/koreader/blob/master/frontend/document/koptinterface.lua#L1041 attempting to get a field "box" from the returned empty table.
