### ISSUE TITLE
Unable to use dictionary to look up words!

### ISSUE THREAD

**Issue by Memorainer** [koreader/koreader#6846]
* KOReader version: v2020.10.1
* Device: Huawei Mate20 Pro Android 10

#### Steps to reproduce
1、Dictionary settings
2、Download the dictionary--Chinese
3、File Manager Unzip the downloaded dictionary file to the following path: /storage/emulated/0/koreader/data/dict/stardict-eng-eng-2.4.2/"including three files : chinese-eng.dict.dz, chinese-eng.ifo and chinese-eng.idx"
4、Select a word in the document and get a popup: No definition found!

![微信图片_20201104094736](https://user-images.githubusercontent.com/17745131/98060247-1dd5cf80-1e84-11eb-95e2-88d5279f0395.png)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by pazos** [comment]
that dict translates chinese to english, not otherwise.
