### ISSUE TITLE
FR: swipe to dismiss dictionary popup

### ISSUE THREAD

**Issue by doozan** [koreader/koreader#6850]
It would be nice to have the option of swiping to dismiss the dictionary popup (and probably other popups, as well).  I use the dictionary feature regularly and hitting the tiny x to close the dialog always feels like more effort than it should be.

**Comment by NiLuJe** [comment]
Tapping outside of the popup works, too,

**Comment by doozan** [comment]
I have the dictionary popup set as "large window" so there is no outside area, but that's a good workaround for other popups. Thanks!

**Comment by doozan** [comment]
I poked at this awhile and I don't see a good way to accomplish it: swiping up/down scrolls the page, swiping left/right changes dictionaries, tapping the article changes dictionaries/page, tapping the title bar sets the default dictionary. Switching to the smaller dictionary view and tapping outside of it seems to be the simplest solution.
