### ISSUE TITLE
Highlight doesn't work on PDF documents

### ISSUE THREAD

**Issue by juretto** [koreader/koreader#6860]
* KOReader version: 2020.10.1
* Device: Likebook Plus T80S - Android 4.2.2

#### Issue
Highlight doesn't work on PDF documents.
Dictionary by word doesn't work on PDF documents.
It works fine in all the previous versions.

#### Steps to reproduce
Open a PDF document, push on the word to search or to highlight.

##### `crash.log` (if applicable)
NOT AVAILABLE (KOreader does not crash).

**Comment by pazos** [comment]
please attach a pdf that showcases your issue.

**Comment by juretto** [comment]
> please attach a pdf that showcases your issue.

Please find in attachment a PDF file that showcases the issue. Thanks and Regards!
[Estratto_David Hume_Trattato sulla Natura Umana.pdf](https://github.com/koreader/koreader/files/5506914/Estratto_David.Hume_Trattato.sulla.Natura.Umana.pdf)

**Comment by Galunid** [comment]
@juretto I tested it in emulator, and it works fine. Could you confirm that in the `top menu, second tab -> Highlighting` you have `Allow highlighting` checked?

**Comment by jperon** [comment]
Also make sure Panel Zoom is disabled (2nd tab too).

**Comment by pazos** [comment]
cannot reproduce on android
