### ISSUE TITLE
FR: Contrast adjustment for image files

### ISSUE THREAD

**Issue by brunetton** [koreader/koreader#6864]
**Does your feature request involve difficulty completing a task? Please describe.**
I often use KOreader to display images, like photos. In those cases the images often appears super darks. 

**Describe the solution you'd like**
I'd love to have the ability to change that contrast, like I can do it in the bottom menu for other multi-pages documents.

**Describe alternatives you've considered**
I edited the images in an external editor; trying multiple contrast values for each photo to find finally find the correct one

**Additional context**
KOreader 2020.10.1
Kindle K4

**Comment by Frenzie** [comment]
Fixed by https://github.com/koreader/koreader/pull/6931
