### ISSUE TITLE
[non-touch devices] Skim document function is not usable 

### ISSUE THREAD

**Issue by brunetton** [koreader/koreader#6866]
* KOReader version: 2020.10.1
* Device: Kindle K4 (no touchscreen)

#### Issue
On non-touch devices (at least on this particular non-touch device), the Skim function seems unusable: I can access the tool, but it doesn't respond to arrows buttons.

#### Steps to reproduce
- open a document in KOreader
- open the main menu and open Skim tool
- try to navigate on the tool using arrows: nothing appends 

Maybe related to #6865

**Comment by rezaarifandee** [comment]
Hi, i've made some modifications that partially fixed this issue. The buttons is working now.
However, i'm still confused about how non touch device should behave with the progress bar, i'd like to map the letter Q to P for 0% to 100%, is that acceptable? Do i need to add instruction overlay for it?

**Comment by Frenzie** [comment]
That's probably a good idea, but not strictly necessary all at once.

**Comment by rezaarifandee** [comment]
Alright, i'll do a PR, thanks!
