### ISSUE TITLE
Crash on emulator startup (./kodev run) on macOS 10.15.1

### ISSUE THREAD

**Issue by Witos** [koreader/koreader#6873]
* KOReader version:
v2020.10.1-47-g1468646a_2020-11-13
* Device:
macOS 10.15.1 (Macbook)

#### Issue
./kodev run crashes on startup
#### Steps to reproduce
export PATH="/usr/local/opt/gettext/bin:${PATH}"
export MACOSX_DEPLOYMENT_TARGET=10.14
./kodev run

Attaching log from the run.
[crash.log](https://github.com/koreader/koreader/files/5535682/crash.log)

**Comment by Frenzie** [comment]
What's your system language? This doesn't look related to macOS (a welcome change :-P) but I can't quite tell what the problem might be.

Basically the output of these commands:
```sh
echo $LANGUAGE
echo $LC_ALL
echo $LC_MESSAGES
echo $LANG
```

With any luck it should be reproducible anywhere.

**Comment by Witos** [comment]
Nice. Those above where empty, setting $LANG helped.

**Comment by Frenzie** [comment]
@Witos I'd still like to figure out the root cause. ;-)

**Comment by Frenzie** [comment]
Without setting anything manually (and you might have to clear settings too), does something like this output anything?

```diff
diff --git a/frontend/gettext.lua b/frontend/gettext.lua
index 85e3f9fb..d0a4da12 100644
--- a/frontend/gettext.lua
+++ b/frontend/gettext.lua
@@ -167,6 +167,8 @@ end
 -- we only implement a sane subset for now
 
 function GetText_mt.__index.changeLang(new_lang)
+print("new_lang", new_lang)
+error()
     GetText.context = {}
     GetText.translation = {}
     GetText.current_lang = "C"

```

**Comment by Witos** [comment]
Tested:
1. Applied patch
2. Unset LANG
3 ./kodev build && ./kodev run 
4. Your print is not hit:
> ./kodev run | grep "new_lang"
./luajit: frontend/gettext.lua:386: attempt to index field 'context' (a nil value)
stack traceback:
        frontend/gettext.lua:386: in function 'C_'
        frontend/ui/data/strings.lua:81: in main chunk
        [C]: in function 'require'
        frontend/ui/data/creoptions.lua:3: in main chunk
        [C]: in function 'require'
        frontend/apps/reader/modules/readerconfig.lua:7: in main chunk
        [C]: in function 'require'
        frontend/apps/reader/readerui.lua:27: in main chunk
        [C]: in function 'require'
        frontend/apps/cloudstorage/dropbox.lua:8: in main chunk
        [C]: in function 'require'
        frontend/apps/cloudstorage/cloudstorage.lua:6: in main chunk
        [C]: in function 'require'
        frontend/apps/filemanager/filemanagermenu.lua:3: in main chunk
        [C]: in function 'require'
        frontend/apps/filemanager/filemanager.lua:18: in main chunk
        [C]: in function 'require'
        ./reader.lua:270: in main chunk
        [C]: at 0x01000ef1d0

**Comment by Frenzie** [comment]
What exactly did you set `LANG` to, btw?

**Comment by Witos** [comment]
I unset it.
> unset LANG
> env | grep "LANG"
>

**Comment by Frenzie** [comment]
But what did you set it to when you set it?

**Comment by Witos** [comment]
![image](https://user-images.githubusercontent.com/132660/99078379-95aba480-25be-11eb-8b39-97a83b0247bb.png)
Then it's fine ^

**Comment by Frenzie** [comment]
Thanks, I think I know the issue thanks to that. Could you please try this?

```diff
diff --git a/frontend/gettext.lua b/frontend/gettext.lua
index 85e3f9fb..92c7c081 100644
--- a/frontend/gettext.lua
+++ b/frontend/gettext.lua
@@ -23,6 +23,7 @@ local isAndroid, android = pcall(require, "android")
 local logger = require("logger")
 
 local GetText = {
+    context = {},
     translation = {},
     current_lang = "C",
     dirname = "l10n",
```

**Comment by Witos** [comment]
Works with LANG unset. Thanks!
