### ISSUE TITLE
FR: Add a downloadable Mac application bundle to the Releases page

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#6875]
Is it possible to add a downloadable Mac application bundle to the Releases page?

**Comment by pazos** [comment]
I tried with https://www.macstadium.com/opensource. They granted us a free mac mini server on their farms, but the register process involved giving my credit card, so nope.

I don't know if is possible to build the app/dmg using github actions. As far is I'm concerned I'm aware of the situation of opensource enthusiast who own a mac: play stupid games, win stupid prizes :smile:

**Comment by JasonInOttawa** [comment]
Thanks very much for looking into it.

**Comment by Frenzie** [comment]
@pazos See https://github.com/koreader/koreader-base/blob/ffdb9be5e626adbdc5432e1227aee7ddab1c127a/.github/workflows/build.yml which already does it (except I need to double check if I set up the cache quite right).

Also cross-ref to time-limited discussion in <https://github.com/koreader/koreader-base/pull/1198#issuecomment-706888406>. 

Relevant action:
https://github.com/marketplace/actions/upload-a-build-artifact

**Comment by pazos** [comment]
@Frenzie: thanks!

I'm very bad at deploying things, but looks like we need a similar action on the frontend that is triggered on tagged releases and just run
```
run: export MACOSX_DEPLOYMENT_TARGET=10.14 PATH="/usr/local/opt/gettext/bin:$PATH" && ./kodev release macos
```

?.

Also homebrew deps need to be tweaked a bit: sdl2 can be removed (we're building that from source) and `create-dmg` package added.

I *think* we need the dmg step, as macs out there won't like to install non-notarized apps packaged inside a container, like 7z.

Anyways, I built latest version yesterday, on Big Sur, and compressed it to see if it works: https://www.dropbox.com/s/d5doikl6fz821sf/KOReader.7z?dl=0

@JasonInOttawa, could you test if the app works?. It also has an easter egg which I'm going to submit later :)

**Comment by Frenzie** [comment]
> just run […]

Yup, unless packaging requires anything extra that should all be the same. The only thing that'd be properly different would be the artifact thing.

However, it looks like the Mac CI build has broken itself again through no fault of ours…

**Comment by JasonInOttawa** [comment]
@pazos It's been happily running for a couple hours now. Apart from the "unknown developer" warning everything is fine. I haven't seen the Easter egg yet.

**Comment by pazos** [comment]
@JasonInOttawa: I don't remember if I edited the app before upload it :p. Anyhow the easter egg is https://github.com/koreader/koreader/pull/6882

BTW, thanks for testing the app!

**Comment by JasonInOttawa** [comment]
@pazos  Is it this

<img width="607" alt="Screen Shot 2020-11-14 at 1 54 15 PM" src="https://user-images.githubusercontent.com/46451014/99154855-f3a0c080-2680-11eb-934d-f46cbde85acb.png">

**Comment by JasonInOttawa** [comment]
@pazos Is the Mac app bundle supposed to be on the 2020.12 Releases page? If so, I don't see it. If not, is there a download link somewhere?

Thanks!

**Comment by Frenzie** [comment]
That's currently not part of the workflow, but the artifact in https://github.com/koreader/koreader/actions/runs/428537870 is identical to the tagged release.

**Comment by pazos** [comment]
Not yet. artifacts are available for each new PR on this repo.

So, for example, https://github.com/koreader/koreader/pull/6992/checks?check_run_id=1569393908 has a litte icon called artifacts where you can download the app (built against that specific PR)

At some point we will change the workflow to run on tagged releases instead of on each PR, but **I have no idea how to do that**

**Comment by JasonInOttawa** [comment]
Thank you! For ongoing releases, can I just look at the most recent PR in the appropriate milestone, go to Artifacts, and download the app?

**Comment by Frenzie** [comment]
I'll tweak it a bit if it's working well now.

**Comment by JasonInOttawa** [comment]
I ran it and read a few pages - hardly exhaustive testing, but it worked fine for me.

**Comment by Frenzie** [comment]
Actually since we're using GH itself here we can probably do something simpler than I wrote here:
https://github.com/hellerbarde/stapler/commit/48d2dc7e7a683ca3c2b659c1762aa67661f7ad79

It's fairly easy to test these things in your own fork, but annoyingly time consuming.

**Comment by JasonInOttawa** [comment]
I'd be happy to pitch in if there's anything I can do

**Comment by Frenzie** [comment]
We'll want to run it (only?) on release and combine it with https://github.com/softprops/action-gh-release

Shouldn't be much to it. :-) But to test it you need to create a few releases in your own fork, which rather inconveniently takes at least 20 minutes, probably closer to 40. And you won't know if you did it quite right until the very end. Unless there's a better way to test GH Actions, anyway.

**Comment by JasonInOttawa** [comment]
Is the process to fork; clone the fork; run a release script locally to build the application; and then upload it? Or does the build happen on a Github server of some sort? (I imagine the build is what takes 20-40 minutes, where ever it happens.)

**Comment by Frenzie** [comment]
Completely on GH. But for testing purposes one can probably replace the build with a dummy to do it a lot faster.

**Comment by JasonInOttawa** [comment]
Thanks. Is it correct to say we'd need to revise koreader/.github/workflows/build.yml so that after the osx artifact is built that it copies / publishes (not sure of the right word) it so it can be added to the Releases page?

On a rather unrelated note, using the application in newer artifacts (I went back 10 hours) when I try to open an epub I get this error:

![Screen Shot 2020-12-19 at 11 30 08 AM](https://user-images.githubusercontent.com/46451014/102694221-a7035480-41ed-11eb-897f-361167e42d1f.png)

**Comment by NiLuJe** [comment]
Check the logs, there should be a trace of the specific failure when cre gets loaded.

**Comment by Frenzie** [comment]
> Thanks. Is it correct to say we'd need to revise koreader/.github/workflows/build.yml so that after the osx artifact is built that it copies / publishes (not sure of the right word) it so it can be added to the Releases page?

Yes, that's where https://github.com/softprops/action-gh-release comes in. Though just building on tag/release and later uploading it manually would also more or less work. I just don't want to spend time doing that.

**Comment by JasonInOttawa** [comment]
Thank you. The crash.log is attached. There are two stack traces - this one happens during application launch:

```
12/19/20-11:51:58 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
error in subprocess:	error loading module 'libs/libkoreader-cre' from file './libs/libkoreader-cre.so':
	dlopen(./libs/libkoreader-cre.so, 6): Library not loaded: /usr/local/lib/libzstd.1.dylib
  Referenced from: /Users/jasonbenwell/Downloads/KOReader.app/Contents/koreader/libs/libcrengine.dylib
  Reason: image not found
stack traceback:
	[C]: at 0x010262bbb0
	[C]: in function 'require'
	frontend/document/credocument.lua:104: in function 'engineInit'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:386: in function 'extractBookInfo'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:685: in function 'func'
	./ffi/util.lua:332: in function <./ffi/util.lua:313>
	[C]: in function 'xpcall'
	./ffi/util.lua:313: in function 'runInSubProcess'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:694: in function 'extractInBackground'
	plugins/coverbrowser.koplugin/covermenu.lua:142: in function 'action'
	frontend/ui/uimanager.lua:882: in function '_checkTasks'
	frontend/ui/uimanager.lua:1219: in function 'handleInput'
	frontend/ui/uimanager.lua:1312: in function 'run'
	reader.lua:305: in main chunk
```

It seems to be related to loading book covers (which doesn't happen - I only see the file name).

This one pops up when I try to open a book

```
12/19/20-11:52:51 INFO  FM loaded plugin terminal at plugins/terminal.koplugin
error in subprocess:	error loading module 'libs/libkoreader-cre' from file './libs/libkoreader-cre.so':
	dlopen(./libs/libkoreader-cre.so, 6): Library not loaded: /usr/local/lib/libzstd.1.dylib
  Referenced from: /Users/jasonbenwell/Downloads/KOReader.app/Contents/koreader/libs/libcrengine.dylib
  Reason: image not found
stack traceback:
	[C]: at 0x010262bbb0
	[C]: in function 'require'
	frontend/document/credocument.lua:104: in function 'engineInit'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:386: in function 'extractBookInfo'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:685: in function 'func'
	./ffi/util.lua:332: in function <./ffi/util.lua:313>
	[C]: in function 'xpcall'
	./ffi/util.lua:313: in function 'runInSubProcess'
	plugins/coverbrowser.koplugin/bookinfomanager.lua:694: in function 'extractInBackground'
	plugins/coverbrowser.koplugin/covermenu.lua:142: in function 'action'
	frontend/ui/uimanager.lua:882: in function '_checkTasks'
	frontend/ui/uimanager.lua:1219: in function 'handleInput'
	frontend/ui/uimanager.lua:1312: in function 'run'
	reader.lua:305: in main chunk

```
Is it possible that do_mac_bundle.sh needs revising to include calling install_name_tool to fix loading libzstd.1.dylib?

**Comment by JasonInOttawa** [comment]
Crash log actually attached
[crash.log](https://github.com/koreader/koreader/files/5719869/crash.log)

**Comment by NiLuJe** [comment]
> Is it possible that do_mac_bundle.sh needs revising to include calling install_name_tool to fix loading libzstd.1.dylib?

That's quite likely, because I don't *think* I bungled the filename itself, or the build/link would have failed ;).

**Comment by JasonInOttawa** [comment]
The library is in the application bundle: ./Contents/koreader/libs/libzstd.1.dylib

I think the issue is in this part of the do_mac_bundle script:

```
        dependencies=$(otool -L "${library}" | grep "Users.*x86_64" | tr -s " " | cut -f1 -d" ")
        if [ -n "${dependencies}" ]; then
            for dependency in ${dependencies}; do
                filename=$(basename "${dependency}")
                if [ ! "${library}" = "${filename}" ]; then
                    install_name_tool -change "${dependency}" "${path}/${filename}" "${library}"
                fi
            done
        fi


```It may need an extra check for libraries in /usr/local/lib so they are updated too.

**Comment by NiLuJe** [comment]
We should absolutely not touch /usr/local, that's not our place.

**Comment by pazos** [comment]
`"/usr/local/lib/libzstd.1.dylib"`. Do we pick that from brew?. In that case: https://github.com/koreader/koreader/blob/master/platform/mac/do_mac_bundle.sh#L146-L153

**Comment by NiLuJe** [comment]
Oh, you mean if it's installed, brew pulls *that* one in the DT_NEEDED (or whatever those are called in Mach-O) instead of ours in libs/?

But if ti's installed, shouldn't it find them at runtime, too?

**Comment by NiLuJe** [comment]
Okay, grabbed the laptop to check, yep, the DT_NEEDED entries point to /usr/local.

I'll fix it in base.

**Comment by JasonInOttawa** [comment]
I downloaded an osx-artifact that shows version 2020.12-25 and it works! The new icons look nice.
