### ISSUE TITLE
Coverimage - Some cover images are cut off due to different aspect ratio to the device.

### ISSUE THREAD

**Issue by sndwichm4n** [koreader/koreader#6876]
* KOReader version: 2020.10.1-44
* Device: Poke 2

#### Issue
Some cover images are cut off due to different aspect ratio to the device.

The device has a resolution of 1448 x 1072 ratio 1,350. If a book cover has a resolution of 1186 x 762 ratio 1,556, the image is scaled to the screen size of the device by the screensaver. So the upper and lower side is cut off a little bit.

#### Steps to reproduce
Install Koreader with "coverimage" on a Poke 2 and open a book. Put the device to sleep.

#### Solution
Set the book cover to the same aspect ratio as the device: Depending on the margins insert in black or white.

**Comment by sndwichm4n** [comment]
I love the plugin very much! :)

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/blob/6cc0ab8dc9da1549f6a6d1abdb8fe190b302faba/frontend/ui/widget/imagewidget.lua#L91-L96

**Comment by Galunid** [comment]
@sndwichm4n Does it "just" work on Poke Pro? I mean, is the cover displayed as screensaver (even if it has wrong dimensions)? If that's the case then it's pretty surprising

**Comment by sndwichm4n** [comment]
@Galunid It is a Poke 2 no Poke pro, the poke 2 is new bought. I have written something wrong out of habit.

**Comment by zwim** [comment]
@sandwichm4n: Until now, coverimage does no scaling. My Tolino is smart enough to scale the image itself.

As the Poke2 does not scale correctly, we will have to help him.

Could you please provide some informations:
1.) Which filename did you enter to store the cover image?
2.) Could you upload the created cover-image somewhere (dropbox)?
3.) Could you upload an image (photo) of the Poke2 with the cut off image?

**Comment by sndwichm4n** [comment]
No problem:

Filename: /sdcard/Pictures/cover.png
Fallback: /sdcard/Pictures/Fallback.png

https://imgur.com/a/4DeOaxG

**Comment by sndwichm4n** [comment]
> @sandwichm4n: Until now, coverimage does no scaling. My Tolino is smart enough to scale the image itself.
> 
> As the Poke2 does not scale correctly, we will have to help him.

I do not think it is about scaling. On the left and right sides 58 pixels each must be added. To get to the ratio of the Poke2 screen.

((1186/1.35)-762)/2 = 58.259

**Comment by zwim** [comment]
@sndwichm4n: Would you like to drop a short description, on how to get the screensaver work together with CoverImage on Poke 2 so that we can add it on the wiki?

**Comment by sndwichm4n** [comment]
Of course:

Sample usage on Onyx Boox Poke2

The pictures for the screensaver must be in the folder "/Pictures". The filename does not matter. It is best to create your own image as screensaver before using "Coverimage" for the first time. In this example the image should also be used as a fallback image.

Save a nice image that you like via USB on the device. Save it under the name "screensaverimage.png" in the folder "/Pictures".

Save the same picture again under the name "fallbackimage.png" in the folder "/Pictures".

1. tap on "Storage" in the main menu of Poke2 and open the folder "Storage".
2. go to the folder "Pictures" and tap long on the file "screensaverimage.png".
3. select "Set as Screensaver" in the pop-up menu 
4. now there is the option "Set as Screensaver" or "Set as shutdown image". 
5. touch "Set as Screensaver" and confirm the question if you are sure.

When the power button is pressed the beautiful image should appear on the screen.

Start Koreader and in the "coverimage" menu in "Set system screensaver image" type "/sdcard/Pictures/screensaverimage.png" and confirm. 

At "Set fallback image" enter "/sdcard/Pictures/fallbackimage.png" and confirm.

Activate the option "Save book cover" and "Turn on fallback image".
