### ISSUE TITLE
./luajit: ./reader.lua:44: attempt to call method 'enableCBB' (a nil value)

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [koreader/koreader#6879]
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/14/20-22:02:43
 [*] Version: v2020.10.1-49-g6cc0ab8d_2020-11-13

ffi.load: blitbuffer
./luajit: ./reader.lua:44: attempt to call method 'enableCBB' (a nil value)
stack traceback:
        ./reader.lua:44: in main chunk
        [C]: at 0x555f39e6ea64
~/temp/koreader

**Comment by kuailedeluojie-sudo** [comment]
After git pull and. / kodev build, kodev run prompts what is the cause of this error?

**Comment by NiLuJe** [comment]
You have a severely broken checkout, with -- at the very least --, an inconsistent base checkout.

Or broken custom code in there, who knows.

**Comment by Galunid** [comment]
It's problem with your local repository

Something like this should fix it
```
# in koreader directory
git checkout master
git pull origin master # or "upstream" remote if you changed them
cd base
git checkout master
git pull origin master # or "upstream" remote if you changed them
cd ..
./kodev fetch-thirdparty
./kodev run # this should do ./kodev build too
```

or simply start from scratch
```
git clone https://github.com/koreader/koreader new_koreader
cd new_koreader
./kodev run
```

**Comment by Frenzie** [comment]
Or possibly something like `git submodule update --recursive`, also consider `kodev clean`.

**Comment by kuailedeluojie-sudo** [comment]
> 您的结帐严重中断，至少-不一致的基本结帐。
> 
> 或那里的自定义代码已损坏，谁知道。

Thank you!

**Comment by kuailedeluojie-sudo** [comment]
> You have a severely broken checkout, with -- at the very least --, an inconsistent base checkout.
> 
> Or broken custom code in there, who knows.

Thank you!

**Comment by kuailedeluojie-sudo** [comment]
> Or possibly something like `git submodule update --recursive`, also consider `kodev clean`.

Thank you!

**Comment by kuailedeluojie-sudo** [comment]
> It's problem with your local repository
> 
> Something like this should fix it
> 
> ```
> # in koreader directory
> git checkout master
> git pull origin master # or "upstream" remote if you changed them
> cd base
> git checkout master
> git pull origin master # or "upstream" remote if you changed them
> cd ..
> ./kodev fetch-thirdparty
> ./kodev run # this should do ./kodev build too
> ```
> 
> or simply start from scratch
> 
> ```
> git clone https://github.com/koreader/koreader new_koreader
> cd new_koreader
> ./kodev run
> ```

Thank you!
