### ISSUE TITLE
"font-family: inherit" not supported

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#6886]
* KOReader version: 2020.10.1
* Device: Emulator

#### Issue

The CSS attribute `font-family: inherit` (at least) is ignored. This is useful for overriding specific font settings and use instead the parent font, whatever that is. For instance, in this sample epub ([test.zip](https://github.com/koreader/koreader/files/5542414/test.zip)) the CSS contains:

```css
h1 {
  font-family: "Lobster Two";
}

h1.plain {
  font-family: inherit;
}
```

and the text:

```xhtml
<h1>Default font</h1>

<h1 class="plain">Inherited font</h1>
```

(Maybe not a bug but a feature request)

#### Steps to reproduce

Load the attached document (see above).

Views in Firefox, calibre viewer and koreader (guess which one is wrong):
![Screenshot_20201115_142218](https://user-images.githubusercontent.com/7943459/99186304-afc8bc80-274f-11eb-8887-37b5d2d68265.png) ![Screenshot_20201115_142242](https://user-images.githubusercontent.com/7943459/99186308-b35c4380-274f-11eb-9a12-35cbc776a531.png) ![Screenshot_20201115_142309](https://user-images.githubusercontent.com/7943459/99186309-b6573400-274f-11eb-8364-05c3dd3e05b1.png)

**Comment by poire-z** [comment]
Most probably related to another issue you opened: https://github.com/koreader/crengine/issues/362 and my comment in there.
