### ISSUE TITLE
Can't hide status bar until the page is changed.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#6893]
* KOReader version: 2020.11 (regression, doesn't affect 2020.10)
* Device: all platforms

#### Issue

Can't hide status bar until the page is changed.

#### Steps to reproduce

1. enable show all at once
2. disable progress bar
3. hide the status bar
4. move to next page
5. show the status bar
6. try to hide the statusbar. It won't work until the page is switched.

Reported in https://www.mobileread.com/forums/showthread.php?p=4059187#post4059187

**Comment by NiLuJe** [comment]
Possibly related to getHeight being bogus with the progress bar disabled, haven't had time to look into it yet ;).
