### ISSUE TITLE
Should epub:type="pagebreak" be rendered?

### ISSUE THREAD

**Issue by edent** [koreader/koreader#6894]
* KOReader version: 2020.11
* Device: Linux & Android

#### Issue

I have an ePub which skips words when read in KOReader. Other ePub viewers render the words correctly. I'm trying to find out if this is a problem created by converting a book with Calibre, or with KOReader.

#### Steps to reproduce

My ePub contains the following HTML:

```
<p class="calibre7">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur efficitur tempor elementum. 
Aliquam a elit pretium, fringilla 
   <span id="pg8" epub:type="pagebreak">sapien</span>
et, ullamcorper ex. Phasellus lobortis enim in iaculis posuere.</p>
```

The word "sapien" does not appear when I try to view the file in KOReader on Linux, fresh install with no defaults changed:
![Screenshot of broken text](https://user-images.githubusercontent.com/837136/99594901-bb381400-29eb-11eb-973f-bd6e8c9c5c43.png)

Here it is rendering in Calibre's eBook Editor:
![Screenshot of the text](https://user-images.githubusercontent.com/837136/99594942-c9863000-29eb-11eb-8a88-c94db6496ea9.png)

I *suspect* that `<span id="pg8" epub:type="pagebreak">` should be an empty span. But if it isn't, should KOReader render the contents?

**Comment by poire-z** [comment]
The reason for it being not displayed, and the solution (a user style tweak to make it visible again), at https://github.com/koreader/koreader/issues/6175#issuecomment-632885620 .
(We had to decide about the default of showing or not showing the content of what should indeed be an empty span. We decided not to show it.)

**Comment by edent** [comment]
I see, thank you. Switching to the HTML5 CSS rather than epub makes it work.

I'll file a bug with Calibre.
