### ISSUE TITLE
FR: Enable CoverImage Plugin on Remarkable

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6899]
@zwim's CoverImage plugin works like a charm on the Remarkable. For example, if you want to change the poweroff screen, simply set `usr/share/remarkable/poweroff.png` as the *Screensaver image filename*

Can we have it enabled by default by adding `and not Device.IsRemarkable()` to the line below?
https://github.com/koreader/koreader/blob/2785f0d1133e023d038a76a7cec7a1aee3f3575b/plugins/coverimage.koplugin/main.lua#L5

The only minor issue I see on the Remarkable is that it leaves a ghosted image of the previous screen before turning off. If someone could add a **full screen refresh** before loading the image that would be awesome!

**Comment by NiLuJe** [comment]
If it's deferred to the system, we have no real control over *when* it's displayed, so adding a refresh becomes a potentially dicey proposition ;).

(And I'd rather not emulate the giant mess that is the Kindle codepath for that sort of things ^^).

**Comment by zwim** [comment]
@gybl: You write, that the coverimage plugin works on remarkable, that's good.

As I see on the web, the remarkable has a lot of screen images in `/usr/share/remarkable/`.
Is it right, that you have used `usr/share/remarkable/poweroff.png` to show the cover at device's poweroff and got the ghosting?

Could you please try to set the image to `usr/share/remarkable/suspended.png` and put the device to suspend? I would be interested, if there is ghosting as well.

@NiLuJe: Does KOReader do a complete screen refresh on exit? 
Just a shot in the blue: Couldn't KOReader clear the screen (white image) and do a refresh before quit (exit or SIGTERM)?

**Comment by pazos** [comment]
@gbyl @zwim: ReMarkable is described as a device that supports screensaver. See https://github.com/koreader/koreader/search?q=supportsScreensaver%28%29

That makes all the sense. It is a freescale board. Probably the "magic" used by stock to set suspend/reboot/poweroff images is in systemd units we're calling. You can replace them with their inner guts:

ie: instead of `systemctl reboot` explore what `systemctl reboot` does. It should do a simple `reboot`. Same for `poweroff`. For suspend things are a bit more complex, but indeed possible as explained in https://github.com/koreader/koreader/issues/6028#issuecomment-610411019.

IMO we shouldn't rely on tricks when full screensaver support is possible.

**Comment by gbyl** [comment]
@zwim Yes, that's correct. I used your plugin to replace the `poweroff.png` file and, except for the ghosting, it worked perfectly. Using it for `suspended.png` is also showing ghosting. Which, as @pazos said, is not a big problem as screensaver is already supported.

The reason why I prefer to use your plugin is because Remarkables have horrible battery life when suspended. It is much better to get into the habit of turning the device off. But then, I have to manually replace the `poweroff.png` file with the cover of my latest book. The CoverImage plugin makes this automatic. Thanks for creating it.

**Comment by gbyl** [comment]
@zwim I just realized that there is ghosting even when I set the image manually. So this has nothing to do with your plugin. As you suggested, a KOReader refresh on exit should solve it.

**Comment by pazos** [comment]
@gbyl: on your device remove `systemctl` from https://github.com/koreader/koreader/blob/master/frontend/device/remarkable/device.lua#L106. restart the program and try to poweroff. It should use whatever you configured as your screensaver. If the device doesn't poweroff that means that poweroff is not on your path and you'll need to find the binary with `which poweroff` and type the absolute path of the binary on `os.execute()`

**Comment by gbyl** [comment]
@pazos After removing `systemctl` the device does poweroff but the ghosting is still there. This might just be an issue with remarkables in general.

**Comment by pazos** [comment]
@gbyl: in https://github.com/koreader/koreader/blob/ac6b121c85a222f2c9e0295d3e2105a7409117a3/frontend/device/remarkable/device.lua#L11 replace `no` with `yes`.

Disable this plugin, restart the program, setup screensaver as you wish and poweroff your device. Ghosting should go away.

**Comment by gbyl** [comment]
@pazos I followed the steps, but the ghosting is still there. I just tried turning the device off from xochitl and they show the `poweroff.png` then a full refresh and then the png again. KOReader does not do that, possibly because no other device needs that.

**Comment by pazos** [comment]
> KOReader does not do that, possibly because no other device needs that.

@gbyl: It does a full refresh on cervantes, at least. I think it does that on Kobos too @NiLuJe ?

**Comment by NiLuJe** [comment]
@pazos: That's only used by our own ScreenSaver module, which you tried making use of here, but I doubt that's taken, if @gbyl is still seeing xochitl's own stuff ;).

Otherwise, on a plain exit/quit, we don't do *anything* (nor do we on startup, for that matter).

I suppose one could stick a refresh in the rM-specific suspend/reboot codepath and see what happens?

**Comment by gbyl** [comment]
@pazos Interesting, I made a wrong assumption then.

@NiLuJe To clarify, KOReader is not driving the screensaver on shutdown. It is the remarkable itself that comes with that functionality. The only difference is that when the poweroff is launched from xochitl there is a refresh and when launched from KOReader there isn't one. Hence the ghosting.

**Comment by pazos** [comment]
The whole thing doesn't make sense. @gbyl: could you share the file `frontend/device/remarkable/device.lua` with the modifications you did based on previous posts?.

That's the only way to check if your did the modifications right. Thanks!

**Comment by gbyl** [comment]
@pazos Of course, here is the [file](https://github.com/koreader/koreader/files/5580544/device.lua.txt)

**Comment by pazos** [comment]
@gbyl: thanks for the file. Does the screensaver work at all on poweroff? Does work on suspend?

From https://github.com/koreader/koreader/issues/6899#issuecomment-731757760 I understood that *the ghosting is still there* [but the choosen screensaver image is shown instead of system defaults]. Probably not true?

In any case if the screensaver doesn't work it is better to disable it so it doesn't make more noise.

**Comment by gbyl** [comment]
@gbyl Yes, it works on poweroff and suspend. On the remarkable, whichever image is in the `usr/share/remarkable/poweroff.png` directory will always load on shutdown. This is regardless of which file you use (either a custom png or the default one).

When powering off the device from KOReader, there is ghosting – regardless of the image file you use. When powering off the device from xochitl, there is no ghosting – regardless of the image file you use. The latter has a refresh before drawing the png, the former doesn't.

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/device/remarkable/device.lua b/frontend/device/remarkable/device.lua
index a562916b..ea91499a 100644
--- a/frontend/device/remarkable/device.lua
+++ b/frontend/device/remarkable/device.lua
@@ -95,7 +95,13 @@ function Remarkable:setDateTime(year, month, day, hour, min, sec)
     return os.execute(command) == 0
 end
 
+local function clearScreen()
+    self.screen:clear()
+    self.screen:refreshFull()
+end
+
 function Remarkable:suspend()
+    clearScreen()
     os.execute("systemctl suspend")
 end
 
@@ -103,10 +109,12 @@ function Remarkable:resume()
 end
 
 function Remarkable:powerOff()
+    clearScreen()
     os.execute("systemctl poweroff")
 end
 
 function Remarkable:reboot()
+    clearScreen()
     os.execute("systemctl reboot")
 end
```

**Comment by gbyl** [comment]
@NiLuJe I applied the diff but now koreader is crashing when triggering a poweroff. [crash.log](https://github.com/koreader/koreader/files/5587163/crash.log)

**Comment by NiLuJe** [comment]
I was kinda expecting that (I hate OOP ;D).

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/device/remarkable/device.lua b/frontend/device/remarkable/device.lua
index a562916b..3589258d 100644
--- a/frontend/device/remarkable/device.lua
+++ b/frontend/device/remarkable/device.lua
@@ -95,7 +95,13 @@ function Remarkable:setDateTime(year, month, day, hour, min, sec)
     return os.execute(command) == 0
 end
 
+function Remarkable:_clearScreen()
+    self.screen:clear()
+    self.screen:refreshFull()
+end
+
 function Remarkable:suspend()
+    self:_clearScreen()
     os.execute("systemctl suspend")
 end
 
@@ -103,10 +109,12 @@ function Remarkable:resume()
 end
 
 function Remarkable:powerOff()
+    self:_clearScreen()
     os.execute("systemctl poweroff")
 end
 
 function Remarkable:reboot()
+    self:_clearScreen()
     os.execute("systemctl reboot")
 end
```

**Comment by gbyl** [comment]
@NiLuJe Perfect! That worked. The second part of the diff was not being patched automatically for some reason so I added those two `self:_clearScreen()` manually.

Feel free to close this issue once merged and please consider merging the original request too if it makes sense:
> Can we have it enabled by default by adding `and not Device.IsRemarkable()` to the line below?
> https://github.com/koreader/koreader/blob/2785f0d1133e023d038a76a7cec7a1aee3f3575b/plugins/coverimage.koplugin/main.lua#L5

**Comment by gbyl** [comment]
Fixed by https://github.com/koreader/koreader/pull/6906#issue-526496048

**Comment by pheraph** [comment]
What is the current status of this feature? I have configured the plugin and on power off the cover image is displayed for about 1 second, but immediately after that it is overwritten by the default system image. Maybe a change from remarkable in OS-version 2.12 I am using?

**Comment by zwim** [comment]
The plugin saves the current cover image to a file. What the firmware of a device does with that file is not in our hand.
So if the cover is shown and gets overwritten by the default system image, we can do nothing.

Maybe you can identify the file which contains the default system image and rename it, so that the OS does not use it? But take care, **renaming system files may break things on the device**.

**Comment by pheraph** [comment]
Thanks for the clarification. I was hoping that someone in this issue might have had some experience with newer versions. It looks though like with newer versions it is no longer possible to overwrite the sleep image at runtime without a reboot:

> With 2.11.x image files are read only during startup, they are not hot loaded from the filesystem anymore, so to actually see the next image you need to restart the reMarkable. This means that even suspend image cannot be changed on the fly anymore, but you need to restart to see the new suspend image. (https://github.com/Neurone/reMarkable)
