### ISSUE TITLE
Auto shutdown timeout not working with values higher than 0.1 hours on Remarkable

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#6901]
* KOReader version: v2020.11-7-g31fe3b8_2020-11-18
* Device: Remarkable 1

#### Issue
Auto shutdown timeout works only when set to values less than `0.1`.

#### Steps to reproduce
1. Set Auto shutdown timeout to 0.1 or higher.
2. Device won't shutdown and remains awake after the time has elapsed

**Comment by NiLuJe** [comment]
That's... weirdly specific.

What do the (debug) logs have to say about it?

**Comment by gbyl** [comment]
@NiLuJe Unfortunately the crash.log file is not show anything useful

```
11/21/20-11:49:19 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
11/21/20-11:49:19 INFO  Plugin  plugins/SSH.koplugin/main.lua  has been disabled.
11/21/20-11:49:19 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
11/21/20-11:49:19 INFO  Plugin  plugins/timesync.koplugin/main.lua  has been disabled.
11/21/20-11:49:19 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
11/21/20-11:49:19 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
11/21/20-11:49:38 INFO  event times are real clock time: no adjustment needed
```

**Comment by NiLuJe** [comment]
This is why I specifically mentioned *debug* log ^^.

You'll have to enable that first, from the File Manager, in the top menu, Tools > More Tools > Developer Settings. (Then restart KOReader).

**Comment by gbyl** [comment]
@NiLuJe Ah sorry, I forgot about that. Full log is [here](https://github.com/koreader/koreader/files/5579690/crash.log)

**Comment by NiLuJe** [comment]
You appear to have Shutdown set *earlier* than Suspend, which is a strange quirk. Besides it doesn't it making much sense, I'm not sure if it's actually supposed to work (@Frenzie?).

But, more importantly: you're using your device, it's not idle. Any input resets the timers. It's not "shut it down after 1h". It's "shut it down after 1h *of being completely idle*"). Which is why Shutdown should > Suspend, because Suspend ensures it's idle ;).

**Comment by Frenzie** [comment]
> Besides it not making much sense, I'm not sure if that's actually supposed to work (@Frenzie?).

Why shouldn't it work? Of course it'll never suspend if that's what you mean but that'd be rather the point.

**Comment by NiLuJe** [comment]
> > Besides it not making much sense, I'm not sure if that's actually supposed to work (@Frenzie?).
> 
> Why shouldn't it work? Of course it'll never suspend if that's what you mean but that'd be rather the point.

Oh, yeah, right, makes sense :). I was kinda thrown by the tiny values, too ;p.

**Comment by gbyl** [comment]
@NiLuJe Yes, I set it up in that way because the remarkable has such poor battery life on suspend. I thought the shutdown would take precedence over the suspend since it would timeout first. It works precisely this way with values under `0.1`.

Also, I was not using my device for the log I posted earlier. Those input taps are a mystery to me as well. In fact, I readjusted the suspend timeout to be lower than the shutdown one and it remains unsuspended past the time set too.

**Comment by NiLuJe** [comment]
I mean, it definitely looks like *something* right before an USB plug/unplug, so, I'd turn my investigations towards *that* ;).

**Comment by Frenzie** [comment]
@gbyl 
> I thought the shutdown would take precedence over the suspend since it would timeout first. It works precisely this way with values under 0.1.

That's how it works on my Kobo. You're saying shutdown is only broken in this specific plugin and not in general?

**Comment by gbyl** [comment]
@Frenzie Yes, only for the Autosuspend plugin and, as far as I can tell, only on the remarkable

**Comment by gbyl** [comment]
Unable to fix this.
Decided to get in the habit of manually shutdown the device.
