### ISSUE TITLE
Words are not separated in epub file

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#6903]
Device: kobo clara hd
Koreader: 2020.11
![IMG_20201123_000754](https://user-images.githubusercontent.com/59373108/99914622-87643380-2cf6-11eb-82b3-b5966baf8565.jpg)
The words "though" and "the" are merged in above image. 
How can i separate them please?
It is an epub file and this error appears randomly on all pages.
Thanks

**Comment by poire-z** [comment]
> The words "though" and "the" are merged in above image.

They are probably stuck together in the HTML: select some text around and including them, then `View HTML` (possibly switch to debug view or unicode view to see spaces and all chars).

If you see `thoughthe`: well, publisher error, you can't do anything except by editing the EPUB and fixing all these errors.

If you see `though<a/>the` (which I just saw in the EPUB I'm reading), publisher error too (but I'm leaving with them, they are rare, not worth the work).
Depending on how the tags around look, you might be able to help yourself with some user style tweak.
If you would see `though<span class=zzz/>the`, this could help:
`span.zzz::after { content: ' '; white-space: pre; }`
but it might be applied in other places where you would have an additional space, so some extra space...

**Comment by abdrau26** [comment]
It is publisher error. Thanks anyway.
