### ISSUE TITLE
FR: replace leading spaces with tabs on *.lua-files, on ./kodev release xxx

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6908]
**Does your feature request involve difficulty completing a task? Please describe.**
This is just am idea, to check, if a PR would be appreciated.

**Describe the solution you'd like**
On building KOReader leading spaces could be replaced with tabs. So that the installed program/apk uses less disk space.
The code stays readable and can be edited easily. Only the editor has to be configured to use 4 spaces for a tab.
On Android this would save 300kB on disk-space on the installed apk and  10kB on the apk itself.

**Additional context**
Not seriously but:
Leading  spaces could be removed at all (but then, the code wouldn't be readable).
The code could be compressed by shortening variable names ...

**Comment by NiLuJe** [comment]
This is mildly problematic as it would make patch files unusable on deployed code.

(Yes, it's fairly arcane use-case, but, still ^^).

But other than that, I personally hate indenting with spaces with a fiery passion, so, :tear: ;).

**Comment by Frenzie** [comment]
@zwim 
> On Android this would save 300kB on disk-space on the installed apk and 10kB on the apk itself.

I assume there must be some implied ereader from circa 1990 involved? :raised_eyebrow: 

@NiLuJe 
> (Yes, it's a fairly arcane use-case, but, still ^^).

It is? >_>

> But other than that, I personally hate indenting with spaces with a fiery passion, so, cry ;).

Yeah, tabs ftw. But displayed as 2 spaces or maybe 1, certainly not 4. ;-)

**Comment by zwim** [comment]
I hate leading spaces too. Tabs were made fore indenting. 
Should we go for changing all indention to tabs? 
It would be a massive, boring work on all repos at one time, but it saves 300kB for free.

**Comment by NiLuJe** [comment]
> > (Yes, it's a fairly arcane use-case, but, still ^^).
> 
> It is? >_>
> 

<3 :)

> > But other than that, I personally hate indenting with spaces with a fiery passion, so, cry ;).
> 
> Yeah, tabs ftw. But displayed as 2 spaces or maybe 1, certainly not 4. ;-)

I'm a monster. :blush:

![8spaces](https://user-images.githubusercontent.com/111974/100139215-6aaf3380-2e8f-11eb-8e23-bd8e4e45f2eb.png)

**Comment by Frenzie** [comment]
> Should we go for changing all indention to tabs?

Please don't. git blame is worth much more than a minor personal preference. ^_^

**Comment by zwim** [comment]
> 
> > On Android this would save 300kB on disk-space on the installed apk and 10kB on the apk itself.
> 
> I assume there must be some implied ereader from circa 1990 involved? raised_eyebrow
> 

Hey, old habits.  I did my degree on a DSP56000 with 512words words of program memory and 2x256words of X-Y-data memory (Harvard architecture) in the last millennium. Every byte counts. ;-)))))

**Comment by poire-z** [comment]
I installed nighylies on my Kobo, and I sometimes do apply some patches from my work on the emulator source (apply, revert, apply new one, revert...) so I'd be quite unhappy if the nightlies code was different from the source.
(And personally, I like spaces and don't like tabs :)

**Comment by zwim** [comment]
> Please don't. git blame is worth much more than a minor personal preference. ^_^

I won't do it. But what about https://stackoverflow.com/questions/8094932/tabs-to-spaces-git especiallly the ` .git/hooks/pre-commit.`

**Comment by zwim** [comment]
@poire-z: Would it be too uncomfortable to add a `sed -i "s/^    /\t/g" *.patch` (a better one for more tabs of course),  before pushing it to the device?

**Comment by zwim** [comment]
My last update and last words ;-) : If all trailing spaces are recursively replaced by tabs, the saving of the installed program does down by 600KB for free.

**Comment by Galunid** [comment]
IMHO it's not really worth it. 600KB is ~1.5% improvement on Kobo, 300KB is 0.75% for android, while for android it may make sense, because you *shouldn't* be able to edit lua files (without root I believe), for Kobo/Kindle, where users have their patches it'd be a problem. 600KB is not really even 1 book, and for being able to apply patches on devices without any additional hassle it's really small trade-off. In the same vein it's not really a problem whether one prefers tabs or spaces, since modern editors have soft-spaces/smart-tabs, or some alternative.

**Comment by poire-z** [comment]
> Would it be too uncomfortable to add sed...

I guess I'll most often forget to do that :) 

> the saving of the installed program does down by 600KB for free

That's the size of one EPUB book :) I'd say it's not worth the bother adding willingly these differences vs the little uncoùfort they may cause.

**Comment by zwim** [comment]
OK, thank you. You have convinced me. I will drop the idea.
