### ISSUE TITLE
auto-shutdown not working kobo aura 2

### ISSUE THREAD

**Issue by PhieF** [koreader/koreader#6914]
* KOReader version:
* Device: kobo aura 2

#### Issue

Hi,

I have both an auto standby set to  7 minutes and autoshutdown to 1 hour
When I wait 1 hour, my device is just in standby, it's not off

#### Steps to reproduce

Set a timeout for auto-shutdown (1 hour in my case)
Won't shutdown

Thanks for your work !

**Comment by NiLuJe** [comment]
We'll need to see a verbose debug crash.log (enable that from Tools > More Tools > Developer Tools, then restart KOReader).

**Comment by PhieF** [comment]
Thanks for your reply

Without doing anything it seems to be working, now... Sorry for the mistake !
