### ISSUE TITLE
KOReader crashes directly when trying to sync Evernote! aThe add button is no longer responding!

### ISSUE THREAD

**Issue by hgrain86** [koreader/koreader#6915]
kobo aura one 
koreader version 2020.11
after last update koreader crashes directly when trying to sync Evernote!
Also, I cannot use the add button at the top of the screen to add a new folder!

Many thanks for all these great efforts

**Comment by NiLuJe** [comment]
There are approximately seven billion open issues about the Evernote plugin being broken (e.g., #6281).

I can't see anything wrong with the FM's add button on my end, so, if you can actually reproduce that, do open a dedicated issue that actually honors the issue template (i.e., post a log).
