### ISSUE TITLE
Question: Is it possible to open a book at a given location?

### ISSUE THREAD

**Issue by abijr** [koreader/koreader#6926]
Wondering if it's possible to pass command line arguments to open a file at a given location, something like:

```
~/Applications/koreader.Appimage ~/Ebooks/book.epub -p /body/DocFragment[2]/body/div/p[1]/text().10
```

where `-p` would be the flag for position, and the argument an xpath (example taken from a highlight in the metadata file)

**Comment by Frenzie** [comment]
Not currently; there are no hidden flags.

https://github.com/koreader/koreader/blob/c0b71d08990573349c9011dad701a9a9f28751b4/reader.lua#L61-L75
