### ISSUE TITLE
FR: disable highlighting single word if highlight action is set to dictionary lookup

### ISSUE THREAD

**Issue by doozan** [koreader/koreader#6932]
Like the title says, I'd like to entirely disable text selection if it's just a single word selection that results in a dictionary lookup.  Currently when the full screen dictionary dialog is closed, the page is drawn without the text highlight, then there's a forced refresh to highlight the text followed by another forced refresh to un-highlight the text.

I've been poking around in the code trying to do this myself, but I think I need a pointer in the right direction.  I've tried messing around in readerhighlight.lua and readerview.lua, but it seems like the code that does the actual text selection could be buried somewhere inside crengine.

**Comment by poire-z** [comment]
> the page is drawn without the text highlight, then there's a forced refresh to highlight the text followed by another forced refresh to un-highlight the text.

(The first drawing you mentionned is when the dict window was hiding where the selected word was.)
The idea behind that behaviour is to visually tell you where you were in your reading when you did the dict lookup (so you don't have to guess and look around where you were).
I don't think changing this behaviour needs to be an option.
What's bothering you with these refreshes? We refresh so much everywhere :) 

> but it seems like the code that does the actual text selection could be buried somewhere inside crengine.

Indeed, but you're lucky: looks like I did make that a parameter to the cre.cpp function involved:
https://github.com/koreader/koreader-base/blob/7f96b5dfb248f6478492cbba3b86101f5a3cb315/cre.cpp#L1776-L1791

So, from frontend code, it might be just a matter of:
```diff
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -496,7 +496,7 @@ end
 function CreDocument:getWordFromPosition(pos)
     local word_box = self._document:getWordFromPosition(pos.x, pos.y)
     logger.dbg("CreDocument: get word box", word_box)
-    local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y)
+    local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y, false)
     logger.dbg("CreDocument: get text range", text_range)
     local wordbox = {
         word = text_range.text == "" and word_box.word or text_range.text,
```

Looks like there's still technically a refresh done (in another part of frontend code, readerhighlight.lua probably), but you might not notice it if nothing changes on the screen.

**Comment by NiLuJe** [comment]
The timeline in your message looks fishy: the page is actually redrawn w/ the highlight *first*, before even showing either the InfoMessage or the Dict popup.

Dismissing the dict popup requests a flashing refresh to avoid ghosting; and then the HL is erased.

Since the HL are drawn by CRe, toggling 'em involves repainting the full page, which also means a full-page refresh. (which may or may not count towards the "pages befores a full refresh" counter).

**Comment by NiLuJe** [comment]
If you stand by your timeline, my next obvious question is: on which device?

**Comment by doozan** [comment]
@NiLuJe, you're correct: the text is highlighted, then infomessage pops up too fast to be read, then the large dictionary window covers the screen, and then there's a messy/useless refresh that briefly redisplays the highlight and the infomessage box on top of the dictionary window.
On closing the dictionary window, the page is refreshed with the text already highlighted and is then refreshed to unhighlight the page.

Taking poire-z's advice, I was able to fix the line in credocument.lua to hide the highlight entirely, however, as he noted there's a second event that's triggering a highlight that I've tracked down to DictQuickLookup::getHighligtedText() -> DictQuickLookup::getHighlightedItem() -> self.ui.highlight:getHighlightBookmarkItem() -> self:highlightFromHoldPos() -> self.ui.document:getTextFromPositions

I'm curious about where the frontend tells crengine to unhighlight the text. If I can call that before dismissing the dictionary window, I can probably achieve what I'm going for without having to untangle that mess in DictQuickLookup.

**Comment by NiLuJe** [comment]
> and then there's a messy/useless refresh that briefly redisplays the highlight and the infomessage box on top of the dictionary window.

That's the InfoMessage dismissal (because it probably has a timeout).

I'd be inclined to kill that InfoMessage with fire: it's generally useless nowadays because the lookup is fast enough, and it generally just messes things up because eInk.

**Comment by NiLuJe** [comment]
I'd stick a few `print(debug.traceback())` in strategic places, that usually helps when unwinding these sort of things ;).

**Comment by NiLuJe** [comment]
Because I remember breaking HL drawing when I messed with it, the CRe call cache might also be involved: a `getTextFromPositions` call invalidates the cache, forcing a CRe redraw.

**Comment by NiLuJe** [comment]
See also `ReaderHighlight:clear` ;).

**Comment by NiLuJe** [comment]
> > and then there's a messy/useless refresh that briefly redisplays the highlight and the infomessage box on top of the dictionary window.
> 
> That's the `Looking up: <word>` InfoMessage dismissal (because it probably has a timeout).
> 
> I'd be inclined to kill that InfoMessage with fire: it's generally useless nowadays because the lookup is fast enough, and it generally just messes things up because eInk.

Gah, I remember why I never did that: that's because of the whole "cancel lookup on tap" thingy ([xref](https://www.mobileread.com/forums/showthread.php?t=335221)). `>_<"`

**Comment by poire-z** [comment]
@doozan : you haven't answered our questions :/ : 
> What's bothering you with these refreshes? We refresh so much everywhere :)

> on which device?

but I'll answer yours anyway.

> I'm curious about where the frontend tells crengine to unhighlight the text. If I can call that before dismissing the dictionary window,

https://github.com/koreader/koreader/blob/3d8342a98ceff7b8bce6462247eb1f97b1a266a1/frontend/ui/widget/dictquicklookup.lua#L777-L794

I had a hardtime finding where that other highlighting (before this ^ unhighlight it) happens.
Looks like it's that other method in credocument, that uses the same cre.cpp method, where you could also add a `false`:
```diff
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -496,7 +496,7 @@ end
 function CreDocument:getWordFromPosition(pos)
     local word_box = self._document:getWordFromPosition(pos.x, pos.y)
     logger.dbg("CreDocument: get word box", word_box)
-    local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y)
+    local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y, false)
     logger.dbg("CreDocument: get text range", text_range)
     local wordbox = {
         word = text_range.text == "" and word_box.word or text_range.text,
@@ -524,7 +524,7 @@ function CreDocument:getWordFromPosition(pos)
 end

 function CreDocument:getTextFromPositions(pos0, pos1)
-    local text_range = self._document:getTextFromPositions(pos0.x, pos0.y, pos1.x, pos1.y)
+    local text_range = self._document:getTextFromPositions(pos0.x, pos0.y, pos1.x, pos1.y, false)
     logger.dbg("CreDocument: get text range", text_range)
     if text_range then
         -- local line_boxes = self:getScreenBoxesFromPositions(text_range.pos0, text_range.pos1)
```

**Comment by poire-z** [comment]
> I'd be inclined to kill that InfoMessage with fire: it's generally useless nowadays because the lookup is fast enough, and it generally just messes things up because eInk.

I like that InfoMessage. "fast enough" may be for you, but not with my ~10 dicts and my other dict in dict_ext/ doing a second lookup.
It might also be useful with PDF where the text selection (OCR & co) has more chance to not work or select too much or select stuff on the wrong line - and you can see what crap has been selected and given to sdcv - and you get a chance to cancel it instead of waiting for sdcv to tell you its crap.

OK, it "messes things up because eInk" one time out of 30 for me :) An other strategy would be to not setDirty anything when closing it, to avoid collisions, as it will just be covered by the dict window.

> Gah, I remember why I never did that: that's because of the whole "cancel lookup on tap" thingy

There exists an option to use an invisible TrapWidget instead of that InfoMessage:
https://github.com/koreader/koreader/blob/3d8342a98ceff7b8bce6462247eb1f97b1a266a1/frontend/ui/trapper.lua#L316-L321

> https://www.mobileread.com/forums/showthread.php?t=335221

I would say that's a tap bounce issue :) and setting a tap interval might help (@yparitcher could it have been a tap bounce?)

**Comment by NiLuJe** [comment]
> 
> OK, it "messes things up because eInk" one time out of 30 for me :) An other strategy would be to not setDirty anything when closing it, to avoid collisions, as it will just be covered by the dict window.

That's not a bad idea, actually. Should just require a new prop set in the IM, and then check it in its onCloseWidget... :).

**Comment by NiLuJe** [comment]
Seems to work out fine. Also murdered a useless `forceRepaint` in the process ;).

```diff
diff --git a/frontend/apps/reader/modules/readerdictionary.lua b/frontend/apps/reader/modules/readerdictionary.lua
index 3bad7899..382911c0 100644
--- a/frontend/apps/reader/modules/readerdictionary.lua
+++ b/frontend/apps/reader/modules/readerdictionary.lua
@@ -647,9 +647,9 @@ end
 
 function ReaderDictionary:showLookupInfo(word)
     local text = T(self.lookup_msg, word)
-    self.lookup_progress_msg = InfoMessage:new{text=text}
+    self.lookup_progress_msg = InfoMessage:new{text=text, no_refresh_on_close=true}
     UIManager:show(self.lookup_progress_msg)
-    UIManager:forceRePaint()
+    -- UIManager:forceRePaint()
 end
 
 function ReaderDictionary:dismissLookupInfo()
diff --git a/frontend/ui/widget/infomessage.lua b/frontend/ui/widget/infomessage.lua
index 4d7e62fe..6daaa1d6 100644
--- a/frontend/ui/widget/infomessage.lua
+++ b/frontend/ui/widget/infomessage.lua
@@ -185,6 +185,10 @@ function InfoMessage:init()
 end
 
 function InfoMessage:onCloseWidget()
+    if self.no_refresh_on_close then
+        return true
+    end
+
     UIManager:setDirty(nil, function()
         return "ui", self[1][1].dimen
     end)
```

**Comment by poire-z** [comment]
> Also murdered a useless forceRepaint in the process ;).

It came from one of my first PRs :/
But I guess it's no more needed since we do the sdcv in a subprocess - so, the UI now has the time to refresh while waiting for the sdcv results - while before, it was needed as the sdcv that just follows was blocking everything. Right?

> no_refresh_on_close

Please document it inside `local InfoMessage = InputContainer:new{}`, so we don't have to look at all the code to know there's something that exists already :)

**Comment by NiLuJe** [comment]
> > Also murdered a useless forceRepaint in the process ;).
> 
> It came from one of my first PRs :/
> But I guess it's no more needed since we do the sdcv in a subprocess - so, the UI now has the time to refresh while waiting for the sdcv results - while before, it was needed as the sdcv that just follows was blocking everything. Right?

The actual refresh might have been delayed to the next tick because setDirty and the repaint/refresh queue, and the tick never came because of the process. Possibly? ^^.

**Comment by doozan** [comment]
> @doozan : you haven't answered our questions :/

My apologies, here are more complete answers:

> What's bothering you with these refreshes? We refresh so much everywhere :)

I don't mind other refreshes when I'm navigating the menus, because then I'm trying to accomplish a task other than just reading. For me page turns and dictionary lookups are the only two things I do regularly when reading.  Page turns are fast and clean, even when doing a full refresh.  The dictionary popup is fast and clean.  Dismissing the dictionary is annoying, but that's another issue #6850.  However the text highlighting feels neither fast nor clean.  Watching the highlight more closely, it seems like it's doing two full refreshes instead of just one, but that may just be because it's higher contrast and more noticeable.

I'm also reading texts in a language I'm still learning so I'm doing more dictionary lookups than an average user.

> on which device?

Kobo Aura Edition 2

I'm able to suppress the initial highlight by removing the call to setDirty after the text is selected, which sidesteps the issue of DictQuickLookup selecting the text when displaying the Highlight button and avoids the side effects of patching both calls to getTextFromPositions in credocument.

Closing ReaderHighlight before displaying the dictionary popup resolves my issue with the highlight reappearing after the window is closed.

I'm sure removing the initial highlight is only interesting to me and re-highlighting the text after closing the dictionary sounds like a UX decision that poire-z wants to keep. This patch is good enough for my purposes and easy enough for me to maintain out-of-tree.

```diff
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -750,7 +750,8 @@ function ReaderHighlight:onHold(arg, ges)
             table.insert(boxes, self.selected_word.sbox)
             self.view.highlight.temp[self.hold_pos.page] = boxes
         end
-        UIManager:setDirty(self.dialog, "ui")
+        -- Don't refresh the initial highlight
+        --UIManager:setDirty(self.dialog, "ui")
         --- @todo only mark word?
         -- Unfortunately, CREngine does not return good coordinates
         -- UIManager:setDirty(self.dialog, "partial", self.selected_word.sbox)
@@ -1130,8 +1131,9 @@ function ReaderHighlight:onHoldRelease()
             self:lookupWikipedia()
             self:onClose()
         elseif default_highlight_action == "dictionary" then
-            self:onHighlightDictLookup()
+            -- Clear highlight before opening dictionary
             self:onClose()
+            self:onHighlightDictLookup()
         elseif default_highlight_action == "search" then
```

**Comment by poire-z** [comment]
> However the text highlighting feels neither fast nor clean. Watching the highlight more closely, it seems like it's doing two full refreshes instead of just one, but that may just be because it's higher contrast and more noticeable.

Could it be that it's because the highlight is gray, and your device (like my GloHD) does paint it first black, and only then fades it to gray ?
(I think one can notice this behaviour more easily in the bottom menu, with its selected toggles in gray.)

**Comment by doozan** [comment]
>Could it be that it's because the highlight is gray, and your device (like my GloHD) does paint it first black, and only then fades it to gray ?
(I think one can notice this behaviour more easily in the bottom menu, with its selected toggles in gray.

Yes, that looks like what's happening. Is there any way to alter that? I tried changing `setDirty(self.dialog, "ui")` to `setDirty(self.dialog, "fast")` but it just resulted in the highlight not appearing at all.

**Comment by NiLuJe** [comment]
Yup, it's the gray. And that's handled by CRe, AFAIK.

**Comment by poire-z** [comment]
Just in case, crengine internal text selection background color can be changed and made white (so, just not noticable) by editing data/cr3.ini:
```diff
-crengine.highlight.selection.color=#c0c0c0
+crengine.highlight.selection.color=#FFFFFF
```
(actualy, setting it to black #000000 makes the text black on black and unreaderable, no option to force a white text color on this)

> Is there any way to alter that? 

Nope, I think it's a hardware behaviour on _some_ devices.
I try to avoid using gray in my UI PRs when I can and the other dev allows it (or do not notice it :)
I also patch a few gray things to black in my own koreader patch (like the separator lines in the top menu) - as indeed, it feels like an animation...

**Comment by yparitcher** [comment]
> > https://www.mobileread.com/forums/showthread.php?t=335221
> 
> I would say that's a tap bounce issue :) and setting a tap interval might help (@yparitcher could it have been a tap bounce?)

maybe, i have not been able to reproduce this recently so #6798 may have fixed it. I am not sure what a tap bounce would have to do with this though and i have double tap disabled either way.

**Comment by doozan** [comment]
> Just in case, crengine internal text selection background color can be changed and made white (so, just not noticable) by editing data/cr3.ini:

This is a clever workaround and does what I need without having to patch anything.  Great idea!

I still think the black -> grey transition is weird. Is that a device limitation? Now that I'm looking for it, I can see it affects Nickel too when browsing any of the settings pages that have grey headers.

**Comment by NiLuJe** [comment]
To some extent, yeah: Kindles have a custom waveform mode (that we use for UI, and that AUTO picks up all on its own) that doesn't do that, for instance.

**Comment by poire-z** [comment]
Guess it was normal and expected behaviour, on a device with some twists, and a workaround was found - so closing :)

**Comment by tie-ling** [comment]
@poire-z 

> +crengine.highlight.selection.color=#FFFFFF

This workaround works for the main text rendered by the reader, but it does not apply to the dictionary pop-up dialog.  Any idea how to make text-highlighting inside dictionary pop-up dialog white-colored as well?

<img width="1072" height="1448" alt="Image" src="https://github.com/user-attachments/assets/d7af8414-bcd3-46d6-83f0-e0cd4a8d792a" />
