### ISSUE TITLE
Automatic wifi connect stuck on "Connecting to Wi-Fi..." when network is not saved in Nickel

### ISSUE THREAD

**Issue by matejdro** [koreader/koreader#6933]
* KOReader version: v2020.11
* Device: kobo_alyssum

#### Steps to reproduce

1. Have Wallabag sync setup (or any other action that require internet connection)
2. Have "Action when Wi-Fi is off" set to "turn on"
3. Turn off Wifi
4. Activate Wallabag -> Retrieve new articles from the server (or any other action that require internet connection)

Wi-Fi will turn on and list of networks will show up, but it will be stuck at connecting:

![image](https://user-images.githubusercontent.com/507922/100728350-bbf77f80-33c7-11eb-8461-e8a70ed0125d.png)

Now, interestingly, if I tap the screen to cancel auto-connect and manually select my SSID, it connects immediately. 

I've tried deleting and re-adding the SSID but it does not help.

Here are the relevant lines from crash.log:

```
12/01/20-11:33:40 INFO  Kobo Wi-Fi: enabling Wi-Fi
[enable-wifi.sh] Closed fd 7 -> 
[enable-wifi.sh] Closed fd 9 -> /dev/urandom
[obtain-ip.sh] Closed fd 7 -> 
[obtain-ip.sh] Closed fd 9 -> /dev/urandom
dhcpcd[2870]: dhcpcd not running
dhcpcd[2877]: version 6.6.6 starting
dhcpcd[2877]: eth0: using /sys hwaddr: 78:45:61:6d:49:db
dhcpcd[2877]: all: IPv6 kernel autoconf disabled
dhcpcd[2877]: eth0: IPv6 kernel autoconf disabled
dhcpcd[2877]: eth0: adding address fe80::7a45:61ff:fe6d:49db
dhcpcd[2877]: if_addaddress6: Operation not supported
dhcpcd[2877]: eth0: executing `/libexec/dhcpcd-run-hooks' PREINIT
dhcpcd[2877]: eth0: executing `/libexec/dhcpcd-run-hooks' CARRIER
dhcpcd[2877]: DUID 00:01:00:01:17:10:5c:11:78:45:61:6d:49:db
dhcpcd[2877]: eth0: IAID 61:6d:49:db
dhcpcd[2877]: eth0: delaying IPv4 for 0.5 seconds
dhcpcd[2877]: eth0: using ClientID 01:78:45:61:6d:49:db
dhcpcd[2877]: eth0: soliciting a DHCP lease
dhcpcd[2877]: eth0: sending DISCOVER (xid 0x843d45e2), next in 3.9 seconds
dhcpcd[2877]: eth0: offered 192.168.1.89 from 192.168.1.1
dhcpcd[2877]: eth0: sending REQUEST (xid 0x843d45e2), next in 4.6 seconds
dhcpcd[2877]: eth0: acknowledged 192.168.1.89 from 192.168.1.1
dhcpcd[2877]: eth0: leased 192.168.1.89 for 86400 seconds
dhcpcd[2877]: eth0: renew in 43200 seconds, rebind in 75600 seconds
dhcpcd[2877]: eth0: writing lease `/var/db/dhcpcd-eth0-drobnicm.lease'
dhcpcd[2877]: eth0: adding IP address 192.168.1.89/24
dhcpcd[2877]: eth0: adding route to 192.168.1.0/24
dhcpcd[2877]: eth0: adding default route via 192.168.1.1
dhcpcd[2877]: eth0: executing `/libexec/dhcpcd-run-hooks' BOUND
dhcpcd[2877]: forking to background
dhcpcd[2877]: forked to background, child pid 2898
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=1.305 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.305/1.305/1.305 ms
12/01/20-11:34:03 INFO  Wi-Fi successfully restored (after 8 iterations)!
```

there are no timestamps so I'm not sure when does my manual connect happen.

**Comment by NiLuJe** [comment]
Is this a mesh network? (i.e., there are multiple BSSIDs on the same ESSID?)

(Also: The syslog output would be helpful (via `logread` in a shell)).

**Comment by NiLuJe** [comment]
Also: those are *not* the relevant lines ^^.

That's the "Restore Wi-Fi connection on resume" script ;).

(And you apparently have a mess of weird fds open, so, drumroll... KSM?)

**Comment by matejdro** [comment]
> Is this a mesh network? (i.e., there are multiple BSSIDs on the same ESSID?)

Nope, just a single router

> The syslog output would be helpful (via logread in a shell)

Executing logread gives me `logread: can't find syslogd buffer: No such file or directory`. I assume I have to somehow enable logging first?

> Also: those are not the relevant lines ^^.
> That's the "Restore Wi-Fi connection on resume" script ;).

Well those are the lines that got generated when I attempted above steps (I got the log file before and after attempting to connect and then pasted extra lines here).

> drumroll... KSM?

KSM is the system menu that shows up before koreader, right? I think yes.

This is a pretty old install though, I've installed it a long time ago and then I've just been updating the koreader. Should I update it? Is there anything better than I should switch to?

Thanks for your help so far.

**Comment by NiLuJe** [comment]
I would heartily recommend burning it all with fire and starting from scratch, yes.

(In any case, KSM does mean you do'nt have a syslog, which means I can't really help you, so, yeah, you'll have to get rid of it one way or another).

**Comment by matejdro** [comment]
Okay, I updated to a new system where I can just launch KoReader from nickel (not sure what is the name of that). 

Anyway, here is the logread output of me turning off wifi, starting wallabag sync, waiting ~10 seconds on the network list screen, dismissing connecting prompt and then connecting manually:

```
Dec  2 09:37:34 dhcpcd[1782]: sending signal ARLM to pid 1718
Dec  2 09:37:34 dhcpcd[1718]: received signal ALRM from PID 1782, releasing
Dec  2 09:37:34 dhcpcd[1718]: eth0: removing interface
Dec  2 09:37:34 dhcpcd[1782]: waiting for pid 1718 to exit
Dec  2 09:37:34 dhcpcd[1718]: eth0: releasing lease of 192.168.1.89
Dec  2 09:37:34 dhcpcd[1718]: eth0: sending RELEASE with xid 0xedc4de7d
Dec  2 09:37:34 dhcpcd[1718]: eth0: deleting IP address 192.168.1.89/24
Dec  2 09:37:34 dhcpcd[1718]: eth0: deleting route to 192.168.1.0/24
Dec  2 09:37:34 dhcpcd[1718]: eth0: deleting default route via 192.168.1.1
Dec  2 09:37:34 dhcpcd[1718]: eth0: executing `/libexec/dhcpcd-run-hooks' STOP
Dec  2 09:37:34 dhcpcd[1718]: eth0: executing `/libexec/dhcpcd-run-hooks' STOPPED
Dec  2 09:37:34 dhcpcd[1718]: exited
Dec  2 09:37:34 dhcpcd[1808]: dhcpcd not running
Dec  2 09:37:34 wpa_supplicant[1634]: eth0: CTRL-EVENT-DISCONNECTED bssid=0c:9d:92:46:73:20 reason=3 locally_generated=1
Dec  2 09:37:34 wpa_supplicant[1634]: eth0: CTRL-EVENT-TERMINATING 
Dec  2 09:37:45 wpa_supplicant[1875]: Successfully initialized wpa_supplicant
Dec  2 09:37:45 wpa_supplicant[1875]: rfkill: Cannot get wiphy information
Dec  2 09:38:14 wpa_supplicant[1876]: eth0: Trying to associate with 0c:9d:92:46:73:20 (SSID='drobnicm' freq=2427 MHz)
Dec  2 09:38:14 wpa_supplicant[1876]: Failed to add supported operating classes IE
Dec  2 09:38:14 wpa_supplicant[1876]: eth0: Associated with 0c:9d:92:46:73:20
Dec  2 09:38:14 wpa_supplicant[1876]: eth0: WPA: Key negotiation completed with 0c:9d:92:46:73:20 [PTK=CCMP GTK=CCMP]
Dec  2 09:38:14 wpa_supplicant[1876]: eth0: CTRL-EVENT-CONNECTED - Connection to 0c:9d:92:46:73:20 completed [id=1 id_str=]
Dec  2 09:38:15 dhcpcd[1937]: dhcpcd not running
Dec  2 09:38:15 dhcpcd[1944]: version 6.6.6 starting
Dec  2 09:38:15 dhcpcd[1944]: eth0: using /sys hwaddr: 78:45:61:6d:49:db
Dec  2 09:38:15 dhcpcd[1944]: eth0: executing `/libexec/dhcpcd-run-hooks' PREINIT
Dec  2 09:38:15 dhcpcd[1944]: eth0: executing `/libexec/dhcpcd-run-hooks' CARRIER
Dec  2 09:38:15 dhcpcd[1944]: eth0: delaying IPv4 for 0.4 seconds
Dec  2 09:38:16 dhcpcd[1944]: eth0: using ClientID 01:78:45:61:6d:49:db
Dec  2 09:38:16 dhcpcd[1944]: eth0: soliciting a DHCP lease
Dec  2 09:38:16 dhcpcd[1944]: eth0: sending DISCOVER (xid 0xa7eeefdf), next in 3.5 seconds
Dec  2 09:38:19 dhcpcd[1944]: eth0: sending DISCOVER (xid 0xa7eeefdf), next in 8.7 seconds
Dec  2 09:38:19 dhcpcd[1944]: eth0: offered 192.168.1.89 from 192.168.1.1
Dec  2 09:38:19 dhcpcd[1944]: eth0: sending REQUEST (xid 0xa7eeefdf), next in 4.3 seconds
Dec  2 09:38:19 dhcpcd[1944]: eth0: ignoring offer of 192.168.1.89 from 192.168.1.1
Dec  2 09:38:19 dhcpcd[1944]: eth0: acknowledged 192.168.1.89 from 192.168.1.1
Dec  2 09:38:19 dhcpcd[1944]: eth0: leased 192.168.1.89 for 86400 seconds
Dec  2 09:38:19 dhcpcd[1944]: eth0: renew in 43200 seconds, rebind in 75600 seconds
Dec  2 09:38:19 dhcpcd[1944]: eth0: writing lease `/var/db/dhcpcd-eth0-drobnicm.lease'
Dec  2 09:38:19 dhcpcd[1944]: eth0: adding IP address 192.168.1.89/24
Dec  2 09:38:19 dhcpcd[1944]: eth0: adding route to 192.168.1.0/24
Dec  2 09:38:19 dhcpcd[1944]: eth0: adding default route via 192.168.1.1
Dec  2 09:38:19 dhcpcd[1944]: eth0: executing `/libexec/dhcpcd-run-hooks' BOUND
Dec  2 09:38:19 dhcpcd[1944]: forking to background
Dec  2 09:38:19 dhcpcd[1944]: forked to background, child pid 1960
```

**Comment by NiLuJe** [comment]
No, that's part of the "normal" output (*sigh*).

I'm going to need more context in the syslog, because it *feels* like it's missing key earlier bits ;).

Also, new question: is that SSID set as "saved" in Nickel, and does it auto-connect fine there?

**Comment by matejdro** [comment]
Well that is all I got from the syslog. I captured the log before reproducing the steps and after reproducing them and then pasted the new lines here,

> is that SSID set as "saved" in Nickel, and does it auto-connect fine there?

No, it was not saved (I only added the network in koreader, it was not connecting from Nickel). However, adding the network in Nickel fixes the issue!

So the issue is that network list is not synchronised between Nickel and koreader?

**Comment by NiLuJe** [comment]
I captured the log before reproducing the steps and after reproducing them and then pasted the new lines here,
> 

That's kinda what I was hinting at: I need it in full, not what you think might be relevant ;).

**Comment by NiLuJe** [comment]
> So the issue is that network list is not synchronised between Nickel and koreader?

It needs to have been saved manually *once* somewhere before.

I've never really looked into how we handle a blank slate on that front, so there's a vague chance there's a quirk in there.

**Comment by NiLuJe** [comment]
Interested parties: just try to connect to a new SSID from KOReader: it it doesn't make it to `/etc/wpa_supplicant/wpa_supplicant.conf`, we're missing something. In which case there might be older issues about this.

(wpa_supplicant is pain).

**Comment by matejdro** [comment]
Do you want me to remove wifi network from nickel and get the full logs since boot?

If you plan on looking into this, I can leave this open or I can also close it since it was sort of resolved (but I would suggest that a notice is added to Kobo entry on the wiki warning users of this).

**Comment by NiLuJe** [comment]
I have absolutely zero plan of looking into it the near future ^^.

**Comment by matejdro** [comment]
Thanks for your help anyway, you were great.

**Comment by NiLuJe** [comment]
Thinking about it, this might actually be by design (as in, not dealing with it was a shortcut to keep it platform-agnostic): that filepath is *possibly* entirely platform-specific, and the choice was made to instead store *our* preferred SSIDs entirely within KOReader's settings.

Where that doesn't quite work on Kobo is the UI-less bits of Wi-Fi machinery will look at the system's config, not KOReader's ;).

(I might be completely wrong, I barely checked ^^).
