### ISSUE TITLE
Set "history" as default home HOME directory. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#6938]
Can i set the "history" page as default to home directory or at least you make it in the "file browser" by default 

I used to read my books on bookari premium app and I loved the way I can sort my books on it, (by title, resntly added and more I'll attach a screenshot about it) but your app is better dealing with Arabic text and more functional but sometimes I think it's hard to deal with it, maybe because I never used a "real EReader". 
The history page.
![Screenshot_2020-12-02-15-43-53](https://user-images.githubusercontent.com/70109540/100875897-aeb9be00-34b7-11eb-97bc-6b51359a6cad.png)

The what I called it "file browser" page. 
![Screenshot_2020-12-02-15-43-23](https://user-images.githubusercontent.com/70109540/100875305-e5db9f80-34b6-11eb-82d6-96c0ef05744b.png)
The home page on bookari premium. 
![Screenshot_2020-12-02-14-21-19](https://user-images.githubusercontent.com/70109540/100875414-086db880-34b7-11eb-940e-705db4d9d041.png)
The ways you can sort books (the upper left corner).

**Comment by Zeyadas** [comment]
![Screenshot_2020-12-02-15-49-21](https://user-images.githubusercontent.com/70109540/100876065-efb1d280-34b7-11eb-9662-cc711abcc7f0.png)
Didn't show up in the comment..

**Comment by Frenzie** [comment]
Yes, there's a start with option in the left-most menu in the file manager.

**Comment by Zeyadas** [comment]
Yes, that's when you're in a page in the book, but I mean if you opened the file browser while you were reading how will you go back to the book you were reading. Usually I close the app and reopen it.
So I'm asking if I can add the "history" or the last book I was reading to the file browser.

**Comment by Galunid** [comment]
I don't know about such thing (doesn't mean it's not possible). You can set a gesture to "recall" history though (swipe right, up), instead of going to file manager. Alternatively there is a gesture to open last read book: swipe left, right, left. Both of them can be configured in gesture manager.

**Comment by Zeyadas** [comment]
Tried it.. Didn't work in file browser.

**Comment by poire-z** [comment]
> mean if you opened the file browser while you were reading how will you go back to the book you were reading. 

Via the top menu, right most icon - the same way you can access history (or swith to previous book) from the Reader.
In Reader:
<kbd>![image](https://user-images.githubusercontent.com/24273478/100882190-2fc08780-34af-11eb-902e-f7280160733d.png)</kbd>
In File browser:
<kbd>![image](https://user-images.githubusercontent.com/24273478/100882247-423ac100-34af-11eb-971f-924cd94580b5.png)</kbd>

Or via gestures, which is way quicker (assuming you have a touch device, and not one of the old Non-Touch Kindles)

(File browser being a file browser and showing real directories and files, we can't have it show "virtual" things like the history is. So, it's with a button/action that you switch to another view: the History.)

**Comment by Zeyadas** [comment]
Sorry I didn't mention that I'm using an android tablet.
The top menu, right most icon only shows in the reading page. It doesn't in file browser. That's what I meant first please..

**Comment by poire-z** [comment]
> It doesn't in file browser

It should show, like on my screenshots. It does on my phone.

Just in case, mentionning that: on your screenshots, to get the top menu, you must tap on `KOReader` (in yellow), not on the `+` icon on the right (which indeed bring the context menu you show on your screenshot):
![image](https://user-images.githubusercontent.com/24273478/100883853-17ea0300-34b1-11eb-9172-589f2b715fa8.png)

If not, can you post a picture of what your top menu looks like (so, without the right most icon).

**Comment by Zeyadas** [comment]
That's it. you must tap on KOReader.
Never thought about it and really it's not so obvious that you should Tab on the koreader, I always thought it's just a title or something.
Maybe you should do something about it, I'm a regular user not a programmer so excuse me if I were annoying. 
So many thanks guys, you were all helpful.

**Comment by poire-z** [comment]
I mentionned "tap on KOReader" just to be clear :)
But it's actually: tap in the top of screen zone EXCEPT on the home or the plus button (which do other things).
And even swipe from top of screen would be default show the top menu.

Like in the Reader: you tap in the middle of the top of screen, not in the corners (because top right corner toggle a bookmark). So, one should feel it will work the same in File browser.
I guess that your eyes were caught by the home and plus buttons, which made you feel that's all there was.

**Comment by Zeyadas** [comment]
That's exactly the what happened, and by the way I'm a civil engineer, maybe a dumb one..
I think adding an icon somewhere in the top of screen zone will be helpful in this case.

**Comment by pazos** [comment]
@Zeyadas: did you miss the quickstart guide? I think it explains how to invoke the top menu.

**Comment by Zeyadas** [comment]
Sorry about that but I think it's an Arabic tradition, we never read quickstart guides or user manuals..
That's why we are here.

**Comment by pazos** [comment]
> Sorry about that but I think it's an Arabic tradition, we never read quickstart guides or user manuals

It is a tradition here too :smile: Not sure if is a good one :p
