### ISSUE TITLE
Clicking the menu icon when in a sub-menu should return to the top level of that tab

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#6940]
* KOReader version: nightly
* Device: Kobo Clara HD/emulator

#### Issue

When you are in a sub-menu of the top menu bar, clicking the icon of the current menu tab does nothing. This is annoying, because you could be several level deep and want to go back to the top (but not change menu tab). And if you use the up-chevron icon, if you misremember how may taps you need, you close the menu by accident.

Example:
* Open top menu
* `Tools > Calibre > Search settings > Manage libraries`
* Now I want to go to `Tools > Evernote` - I either need to click the up-chevron 3 times (and it moves each time) or close the menu and reopen. Either is 3 taps.

What should happen (IMO) is that clicking the icon of the menu tab your are currently in takes you to the top of that tab, as if you had closed the menu and reopened it and selected that icon,

**Comment by johnbeard** [comment]
That's still three taps: tap the current one, remember that doesn't work, then tap the other and tap back ;-p

**Comment by Frenzie** [comment]
> What should happen (IMO) is that clicking the icon of the menu tab your are currently in takes you to the top of that tab, as if you had closed the menu and reopened it and selected that icon,

One could also argue that doing so should close the menu. But yes, I'm inclined to agree. :-)

**Comment by Frenzie** [comment]
Here's the check that guards against it:
```diff
diff --git a/frontend/ui/widget/touchmenu.lua b/frontend/ui/widget/touchmenu.lua
index fea07082..42d24543 100644
--- a/frontend/ui/widget/touchmenu.lua
+++ b/frontend/ui/widget/touchmenu.lua
@@ -711,7 +711,7 @@ function TouchMenu:switchMenuTab(tab_num)
     if self.tab_item_table[tab_num].callback then
         self.tab_item_table[tab_num].callback()
     end
-    if self.cur_tab ~= tab_num then
+    --~ if self.cur_tab ~= tab_num then
         -- it's like getting a new menu everytime we switch tab!
         self.page = 1
         -- clear item table stack
@@ -719,7 +719,7 @@ function TouchMenu:switchMenuTab(tab_num)
         self.cur_tab = tab_num
         self.item_table = self.tab_item_table[tab_num]
         self:updateItems()
-    end
+    --~ end
 end
```
