### ISSUE TITLE
Internet Archive OPDS downloads always fail

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#6941]
* KOReader version: git master
* Device: emulator and Kobo Clara HD

#### Issue

Downloads from the Internet Archive always fail

#### Steps to reproduce

* Open OPDS catalog
* Internet Archive > any book that doesn't need a log-in, eg. `Boston Public Library` > `A sermon..."`
* Dowload starts
* Console debug indicates URL is correct (in this case https://bookserver.archive.org/acquire/sermonfortwohund00with.pdf)
* A few moments later a dialog saying "Could not save file to: ...." appears
* The file is created, bu the content is
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.16.1 (Ubuntu)</center>
</body>
</html>
```

**Comment by Galunid** [comment]
@johnbeard It should be fixed in tomorrows nightly build.
