### ISSUE TITLE
FR: Decorative Initial Letter

### ISSUE THREAD

**Issue by StarPrince500** [koreader/koreader#6944]
I want a Decorative Initial Letter like in AlreaderX app for Android.

This letter should be the first letter in the first paragraph of every caption in a book. It should be different from the other capitals by its size (usually 2 regular rows and more), by its font and by its color. You could see such Decorative Initial Letters sometimes in some expensive books or magazines.

Decorative Initial Letters can be Dropped or Raised
[https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEMfM73wcubYrrcx5VoLKcv58_u3_Qo4cn0A&usqp=CAU](url)

P.S. Excuse me if my Eglish is not very good, it's not my native language

**Comment by pazos** [comment]
That's something you add in a ebook. Not something to add to the program.

Can you attach and epub that showcases a decorative letter?

**Comment by Frenzie** [comment]
> That's something you add in a ebook. Not something to add to the program.

If the markup is in reasonable order a style tweak could theoretically do it. We just don't support :first-letter atm. See https://github.com/koreader/crengine/issues/176#issuecomment-386794643

**Comment by NiLuJe** [comment]
Yeah, I'd wager drop cap handling isn't CRe's strong suit at the moment ;).

**Comment by Frenzie** [comment]
Nah, it's quite good, probably at least on par with IE8 if not IE9.

Of course I did my first experiments with `:first-letter` in Opera in '03, but it's only now in 2020 that I'm continually pleasantly surprised that I can Just Use Things™.

In any case, the mechanism's virtually identical.

Ye olde style:
```html
<style>
.dropcap{float:left; font-size:4em; color:crimson}
</style>
<p><span class="dropcap">H</span>i!</p>
```

Ye new-fangled '03 Opera 7 style:
```html
<style>
p:first-letter{float:left; font-size:4em; color:crimson}
</style>
<p>Hi!</p>
```

**Comment by Frenzie** [comment]
The only problem is the former can't be done as a simple style tweak unless something like that is already present. ^_^

**Comment by shermp** [comment]
BTW, there is an actual CSS property for this, called (initial-letter)[https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter].

Of course, this has only been implemented by Safari, but the property does exist if CRengine ever wanted to implement it.

(I really wish other browsers would support this property as well. The standard 'use a float' is an awful hack that never looks quite right)

**Comment by NiLuJe** [comment]
Arguably, Safari means iBooks, so, eh, that's possibly not a bad idea in that context ;).

**Comment by Frenzie** [comment]
I'm going to close this for the moment because it's extremely unlikely to happen anytime soon (as I said, see <https://github.com/koreader/crengine/issues/176#issuecomment-386794643>), but I'd very much welcome `::first-letter` and `::initial-letter`.
