### ISSUE TITLE
Landscape and Landscape rotated are reversed

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#6945]
* KOReader version: v2020.11-27-g06fb1613_2020-12-02
* Device: Emulator, Tolino

#### Issue
When setting the rotation to landscape "⤹ 90°", the screen is rotated in the wrong direction.
When setting the rotation to landscape "⤸ 90°", the screen is rotated in the wrong direction.

#### Steps to reproduce
Open an epub, go to bottom menu, leftmost entry, tap "⤹ 90°" and see the image is rotated in the wrong direction.

**Comment by NiLuJe** [comment]
That's a *device* rotation, not a framebuffer rotation.

c.f., https://github.com/koreader/koreader-base/blob/f4f90cede398de7dc409c36ba09adb767715c979/ffi/framebuffer.lua#L42-L73

(90° CCW is 3; 90° CW is 1).

**Comment by pazos** [comment]
see the (rather large) conversation in https://github.com/koreader/koreader/pull/6309

**Comment by poire-z** [comment]
You can't say it's wrong, when the world's greatest minds had put their thoughts on the topic some months ago in #6309 ! :)  
But I was like you at https://github.com/koreader/koreader/pull/6309#issuecomment-654093178 - but I ended up kinda ok at the end.
(Not re-reading this whole PR, and not even trying to see if what you describe matches what I did describe... but may you will and it does :)

**Comment by zwim** [comment]
@NiLuJe: Ahhhh its the device. Then it makes sense. :)

@pazos: Sorry I didn't connect #6309 to my problem. :(

@poire-z: Thats why I am here, to learn from the best. ;))

Anyway maybe the wording "Rotation" could be changed to make the behavior clearer: something like Device rotation or Device orientation or just Orientation.

Closing this now.

**Comment by poire-z** [comment]
> or just `Orientation`

I think this may help avoiding (or limiting) some confusion. (rotation = action - vs orientation = state, with my way of thinking in my last comment in this PR).

**Comment by NiLuJe** [comment]
We already use orientation to mean simply "Portrait" vs. "Landscape" (no matter whether inverted or not).

**Comment by NiLuJe** [comment]
(At least it comments, possibly function names. If that's not really exposed in the UI, that'd be perfectly fine by me, it's indeed potentially clearer ;)).
