### ISSUE TITLE
ReMarkable screen flashes multiple times when going to a page with an image

### ISSUE THREAD

**Issue by humCopper** [koreader/koreader#6962]
* KOReader version: 2020.10
* Device: reMarkable 1

#### Issue
The screen flashes multiple times when going to page with an image.
#### Steps to reproduce
1. Open epub that has images
1. Go to page with images
1. See it flash usually 3-5 times

**Comment by NiLuJe** [comment]
Which FW version, which device revision?

**Comment by NiLuJe** [comment]
Is nightmode enabled, by chance? (Try the latest stable, this may have already been fixed).

**Comment by humCopper** [comment]
It is RM102, and it is not on night mode.

**Comment by humCopper** [comment]
Updating to 2020.11 seems to have fixed it
