### ISSUE TITLE
add support for 64bit android ABIs

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#6963]
How do I compile 64 bit (arm64-v8a) android?

**Comment by pazos** [comment]
Is not supported yet.

See https://github.com/koreader/koreader-base/issues/993

**Comment by pazos** [comment]
@mendelct: we can leave the issue opened and close it when support is added :)

Feel free to move discussion to koreader/koreader-base#993 if you want to dig a bit into it yourself

**Comment by Frenzie** [comment]
Mostly https://github.com/koreader/koreader-base/pull/1540

Or if you mean strictly also building it every night and putting it in the releases, that'd be these:
https://gitlab.com/koreader/nightly-builds/-/commit/7749e79251dc5dd8f4bf8fcd57ad7ef2c0a5f3fe
https://github.com/koreader/koreader-misc/pull/44
