### ISSUE TITLE
Bad "refresh polygon" after opening an OPDS catalog

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#6964]
* KOReader version: 2020.11-45-g89e1c40_2020-12-08
* Device: Kobo Clara HD

#### Issue

Got the following bad refresh polygon (not sure of the right word for this):

![IMG_20201209_114513](https://user-images.githubusercontent.com/5386578/101626341-b841a980-3a14-11eb-8f9c-402f1beba9a6.jpg)

#### Steps to reproduce

* Wifi off
* Add the following OPDS catalog: `https://wsexport.wmflabs.org/opds/fr.xml`. Name doesn't matter.
* Open the OPDS catalog
* Accept "turn on wifi" prompt
* Wait for wifi + catalog load (can take a little while)
* Picture above happens - not always this exact shape, but seems to always be a right-slanted trapezoid, with a horizontal "stripe" in the centre

This doesn't happen with some other catalogs (IA, PG, etc).

**Comment by poire-z** [comment]
I named them "Papercut refresh glitches/tearing" :) https://github.com/koreader/koreader/issues?q=papercut
Can happen when multiple indendant regions are refreshed at the same moment :/ (in my own patch, I disabled a few Notifications, like when changing font or font size, to limit them).
Possibly device/hardware dependant - and it's possible your ClaraHD and my GloHD are more sensitive to that than other devices :/

**Comment by johnbeard** [comment]
Aha, missed it. So I guess this is dupe of #3130?

**Comment by NiLuJe** [comment]
Yup, it's probably a race with the stack of InfoMessage from the WiFi stuff.

**Comment by johnbeard** [comment]
Speaking of, and having made no effort to investigate yet, is it possible at all to not show the wifi station list when turning wifi on. Nearly always you're connecting to a known AP anyway. If no known AP found _then_ pop the list.

**Comment by NiLuJe** [comment]
I don't quite recall how it all works, but I'm the one who added the "auto dismiss AP list on connection" toggle, so, I'm going to assume it's either not as trivial as it looked, or I simply missed it at the time ;p.
