### ISSUE TITLE
Auto screensaver doesn't works

### ISSUE THREAD

**Issue by Risike** [koreader/koreader#6967]
* KOReader version: 2020.11 "Hive of Industry"
* Device: Kobo Nia

#### Issue

Screensaver doesn't lauch automatically when i set it to xx minutes. I must manuel activate it.

#### Steps to reproduce
Try to set it on a Kobo Nia and wait some minutes

(sorry for my bad english)

**Comment by NiLuJe** [comment]
Can't tell you much without *verbose* debug logs. (In the file manager, top menu > Tools > More Tools > Developper Tools. restart KOReader after).

**Comment by Frenzie** [comment]
Sounds suspiciously related to #6968. :-)

**Comment by Risike** [comment]
> 
> 
> Sounds suspiciously related to #6968. :-)

Hum... Maybe. But I've tried to set it ti 5 minutes and i've wait for about an hour. The clock has "advance" (sorry for the word) more than 5 minutes (but not an hour). So, maybe related, or maybe not. I will post the logs later ;)

**Comment by Frenzie** [comment]
By waited you mean you left it alone and when you came back to it the device was still on?

**Comment by Risike** [comment]
No no ! I used it for hours and hours.

**Comment by Frenzie** [comment]
In that case there might be a slight misunderstanding. It's x minutes after you stop touching it, to prevent the battery from emptying out during the night if you accidentally left it on.

**Comment by pazos** [comment]
@Risike: ping
