### ISSUE TITLE
Crazy clock

### ISSUE THREAD

**Issue by Risike** [koreader/koreader#6968]
* KOReader version: 2020.11 "Hive of Industry"
* Device: Kobo Nia

#### Issue
The clock seems to be strange when wifi is disabled. My device never had the good time.

#### Steps to reproduce
Try to set the clock on a Kobo Nia, disable wifi and wait. Time seems to pass very very slowly.

(sorry for my bad english)

**Comment by NiLuJe** [comment]
You're the first actual Nia user we've heard about, so, that stuff actually works is a surprising news ;p.

There's not much we can do about clock drift, that's entirely out of our control. Hence the manual settings, or the ntp sync.
The upcoming version of USBMS handling will also honor the manual time resync feature of the Kobo App and the upcoming Kobo Utilities Calibre plugin.

That said, it might also simply be an issue of what you're actually basing your judgment on. So, what do you mean, exactly, and what are you looking at?

**Comment by Risike** [comment]
Time resync works perfectly but after several minutes the time seems to pass slowly.  For example it advance for 5 minutes but 1 hour is passed.

**Comment by NiLuJe** [comment]
> and what are you looking at?

(and where, and in, which context).

**Comment by NiLuJe** [comment]
(Sidebar: verbose logs from your other issue will help, too, because they're timestamped ;)).

**Comment by Risike** [comment]
What am I loking at ? I don't know, it seems to be a bug, so I report it...
Where ? Everywhere, everytime in koReader. I set the clock with the online sync function in wifi, it's ok. But after... Maybe a hardware issue, and not a koreader bug.
Sorry if i look rude. My english is just... bad !

**Comment by Risike** [comment]
> 
> 
> (Sidebar: verbose logs from your other issue will help, too, because they're timestamped ;)).

Yes, laster when I'm at home ;)

**Comment by NiLuJe** [comment]
I meant specifically what bits of the UI you're basing your experience on ;).

**Comment by Risike** [comment]
I will take a picture later. I will be easier to understand ;)

**Comment by NiLuJe** [comment]
No, because it won't answer my "in which context" question ^^.

(e.g., some bits of UI don't refresh anything until user interaction, so, if you're looking at a clock on a menu that was open 10 minutes ago, it's going to be 10 minutes late).

**Comment by Risike** [comment]
Ahhh ok ! I look at the clock in the top menu when I scroll down. So this part of screen is refreshed. Moreover I have several full screen refresh when I read (every 6 pages). It's not just the clock i've set on my foot page. It seems the be a global time problem.

**Comment by Risike** [comment]
Then, I have the problem for about 3 weeks when i bought my Nia and installed koReader.

**Comment by Risike** [comment]
More technical question : how the time is get in the code ? Do you use the LUA os.time() function (I don't find in the code...) ? Maybe the Nia doesn't have an internal component that manage real time clock (like the Raspberry Pi) and the function used to get time return a bad information (for exemple : time in milliseconds avec the launch of the script).

**Comment by Frenzie** [comment]
It's a simple os.time(), yes. Not sure where you grepped. ;-)

**Comment by pazos** [comment]
@Risike: ping
