### ISSUE TITLE
12 hour time format leading zero

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#6969]
* KOReader version: 2020.11-45
* Device: Emulator, Samsung 10 (android)

#### Issue
When the time format is set to 12 Hour it displays a leading zero. e.g. 02:15 pm, I would expect to see 2:15pm. From 10 through 12 it does not have a leading zero. Screenshot attached
![Clipboard01](https://user-images.githubusercontent.com/67393493/101684042-68221180-3a2b-11eb-8dc7-174eb4b1c25b.jpg)

#### Steps to reproduce
Set the time format to 12 Hour. BTW the setting in the status bar is not controlled by the device setting. Is there a reason for having two seperate settings?

##### `crash.log` (if applicable)
N/A

**Comment by NiLuJe** [comment]
> BTW the setting in the status bar is not controlled by the device setting. Is there a reason for having two separate settings?

One might predate the other, and no-one really noticed (probably because I think none of us are in a locale using the AM/PM notation) ;).

Speaking of locales, I *think* we're doing that manually, so we might actually have a chance to fix that, but it might also just be `strftime` (aka. POSIX) thinking that's how it ought to look, and just deal with it please and thank you ;).

**Comment by NiLuJe** [comment]
And, indeed, it's `strftime`:

https://github.com/koreader/koreader/blob/89e1c406f259f705cbf2f6e0eaf934eaec98bf9e/frontend/util.lua#L224-L243

strftime(2)

says:

`%I     The hour as a decimal number using a 12-hour clock (range 01 to 12).  (Calculated from tm_hour.)`

The good news is, it also says:

`%l     The hour (12-hour clock) as a decimal number (range 1 to 12); single digits are preceded by a blank.  (See also %I.)  (Calculated from tm_hour.)  (TZ)`

If the blank is an issue, that doesn't really help you all that much, and the answer is still to post-process that in Lua ;p.

I'd rather not reinvent the wheel, and this appears to be pretty damn standard (e.g., POSIX), so I'm curious what leads you to expect a non-padded value?

**Comment by NiLuJe** [comment]
But, of course, for once in Lua, `os.date` is *NOT* a thin wrapper over `strftime` & friends, so, the canonical list of supported tokens is https://www.lua.org/pil/22.1.html, so, nope.

(Because I was going to say that on glibc, there are extended format specifier available to mess with said padding every which way to sunday, but, double nope, because not a think wrappe,r and Android is not glibc).

**Comment by NiLuJe** [comment]
Okay, LuaJIT actually is, at least, I'm just half-blind and confused %l with %i ^^.

**Comment by NiLuJe** [comment]
Meaning said glibc extensions work just fine:

```
> print(os.date("%I", os.time{year=1970, month=1, day=1, hour=1}))
01
> print(os.date("%-I", os.time{year=1970, month=1, day=1, hour=1}))
1
```

**Comment by Frenzie** [comment]
> (probably because I think none of us are in a locale using the AM/PM notation) ;).

Most Americans I know use 24h for digital clocks too. And I dunno about you guys over in France, but right now I'd say it's 11 (at night if I want to be precise, not "PM"), which is arguably the pronunciation of 23 in a text or email.

**Comment by NiLuJe** [comment]
Yeah, we generally expect 24h notation in writing, but the "pm" side of things is spoken aloud with the 1-12 numbers (and you then infer the rest by context, or explicit say "*du matin*"` (AM) or "*de l'après-midi*"/"*du soir*" (PM)).

**Comment by mendelct** [comment]
> > (probably because I think none of us are in a locale using the AM/PM notation) ;).
> 
> Most Americans I know use 24h for digital clocks too. And I dunno about you guys over in France, but right now I'd say it's 11 (at night if I want to be precise, not "PM"), which is arguably the pronunciation of 23 in a text or email.

I guess this American and those I know don't use 24h. I've seen it in some manufacturing situations where time precision was important, but not in regular use.  From a UX perspective (and I'm a "dumb user") I would not expect a leading zero, what code produces I leave to the coding gurus. At any rate it is an extremely minor issue, just thought there might be a quick fix.

**Comment by Frenzie** [comment]
Oh, I see now. A leading zero has very little to do with a 24-hour clock. A normal person writes something like 8:15/8.15/8u15/8h15. You'll generally also see that normal notation on watches (e.g., by Casio or Garmin).

It's American soldiers, some (American?) programmers and perhaps some international standards body who use a leading zero. ;-)

**Comment by NiLuJe** [comment]
Then how are your feelings about a leading *space* instead of the zero?

(I'd tend to agree with you, FWIW ;)).

My gut feeling would be to get rid of it, but, eh, who knows ;).

**Comment by NiLuJe** [comment]
By which I mean:

```
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2020 Mike Pall. https://luajit.org/
JIT: ON SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> print(os.date("%I"))
03
> print(os.date("%-I"))
3
> print(os.date("%l"))
 3
> 
```

(And the second option is not portable, so my idea would be %l wrapped in a trim).

**Comment by Frenzie** [comment]
I'd get rid of a leading space unless there's a very big layout type reason to include it. Given that it already moves around a bit with page numbers (and I don't think we should add leading zeroes there ;-) ), plus it's only once an hour that it might be an issue, it'd just be a weird white space.

**Comment by mendelct** [comment]
> I'd get rid of a leading space unless there's a very big layout type reason to include it. Given that it already moves around a bit with page numbers (and I don't think we should add leading zeroes there ;-) ), plus it's only once an hour that it might be an issue, it'd just be a weird white space.

I'm with you on getting rid of the space.

**Comment by NiLuJe** [comment]
Then we're all agreed, I'll whip up something after a snack ;).

**Comment by mendelct** [comment]
Thanks.
