### ISSUE TITLE
FR: Ability to sync page counter with an actual book's page

### ISSUE THREAD

**Issue by xahon** [koreader/koreader#6971]
My books contain a lot of additional pages which are not counted as actual pages like a title page, about author page, table of contents, expressions of gratitude - that all takes from 5 to 20 pages and then the "payload" of the book starts from the page number 1 but koreader's page counter is ~20. That makes navigation through the book much harder when you find "see page X" and you should map it in your head and find out what koreader's page do you need to see
I think koreader should have a mapping function like (page 20 -> page 1) and pages before koreader's page 20 should go from 0 to -infinity. That function is best for technical texts, so pages with number 0 to -infinity shouldn't make confusion for readers (but that is up to you)

**Comment by NiLuJe** [comment]
That's a book design issue, but the ePub standard for that will be supported in the next stable (it is in current nightlies, c.f., #6847).

**Comment by xahon** [comment]
@NiLuJe is that thing only for epub format? Most of books I have are pdf one

**Comment by NiLuJe** [comment]
That's definitely an ePub feature ;).

I have no experience with PDF myself.

**Comment by Frenzie** [comment]
Duplicate of #4245 then.
