### ISSUE TITLE
JSON Output from Evernote Plugin Incorrectly Identifies Author and Title

### ISSUE THREAD

**Issue by nsvrana** [koreader/koreader#6974]
* KOReader version: 2020.11
* Device: reMarkable 1

#### Issue

Using the Evernote menu to export my highlights from an epub with properly formatted metadata (at least it is correct when I hit book information) to JSON incorrectly identifies the book's name and the author. For example:

    "file": "\/home\/root\/Books\/Energy_ A Beginner's Guide - Vaclav Smil (86).epub",
    "author": "86",
    "title": "Energy_ A Beginner's Guide - Vaclav Smil"

I would expect, based on the book's metadata, to be:

    "file": "\/home\/root\/Books\/Energy_ A Beginner's Guide - Vaclav Smil (86).epub",
    "author": "Vaclav Smil",
    "title": "Energy: A Beginner's Guide"

#### Steps to reproduce

Export book highlights to JSON. I did not test formats other than epub, although I did test with multiple books.

**Comment by NiLuJe** [comment]
The Evernote plugin is woefully in need of a maintainer, and generally broken in fun and interesting ways.

**Comment by nsvrana** [comment]
That's unfortunate, but good to know. Maybe it is time to learn Lua.

**Comment by pazos** [comment]
> The Evernote plugin is woefully in need of a maintainer, and generally broken in fun and interesting ways.

And a new name. It is called evernote but can export to text, json, joplin ...

Maybe we can add a generic exporter that *at least* works and hook output formats to it.

**Comment by nsvrana** [comment]
That would be nice, my actual intent is to connect up with the service ReadWise.io (api [here](https://readwise.io/api_deets)). It supports highlights from a number of devices and formats, but none that KOReader currently outputs.

**Comment by pazos** [comment]
> That would be nice, my actual intent is to connect up with the service ReadWise.io (api [here](https://readwise.io/api_deets)). It supports highlights from a number of devices and formats, but none that KOReader currently outputs.

It uses json. See their python sample in the main page:

```python

import requests
requests.post(
    url="https://readwise.io/api/v2/highlights/",
    headers={"Authorization": "Token XXX"},
    json={
        "highlights": [{
            "text": "Call me Ishmael",
            "title": "Moby Dick",
            "author": "Herman Melville",
            "source_type": "book",
            "location_type": "page",
            "location": 3,
            "highlighted_at": "2020-07-14T20:11:24+00:00",
        }]
    }
)
```

**Comment by nsvrana** [comment]
> > That would be nice, my actual intent is to connect up with the service ReadWise.io (api [here](https://readwise.io/api_deets)). It supports highlights from a number of devices and formats, but none that KOReader currently outputs.
> 
> It uses json. See their python sample in the main page:
> 
> ```python
> import requests
> requests.post(
>     url="https://readwise.io/api/v2/highlights/",
>     headers={"Authorization": "Token XXX"},
>     json={
>         "highlights": [{
>             "text": "Call me Ishmael",
>             "title": "Moby Dick",
>             "author": "Herman Melville",
>             "source_type": "book",
>             "location_type": "page",
>             "location": 3,
>             "highlighted_at": "2020-07-14T20:11:24+00:00",
>         }]
>     }
> )
> ```

Sorry, I should have been more clear. It does not directly support importing any of the output files without writing code. For example you can copy a MyClippings.txt file from a (stock) Kindle, drag and drop it onto their website, and it will parse and dedupe the file. The KOReader Clippings file format does not match the Kindle one so must be converted, the JSON file requires a script, etc.

Since that is the case, my original bug request was because I plan to write a python script to send it, but the JSON isn't using the book's metadata, so I will need to correct that before sending it over.

**Comment by pazos** [comment]
@nsvrana:

You might be interested in https://github.com/koreader/koreader/issues/5794. Once we have a solid structure with enough information, implementing a minimal exporter that outputs a lua table would be easy.

Then it would be a matter of writting a textExporter, jsonExporter, etc. In that respect a readwiseExporter would work mostly as a json exporter with some filters to remove irrelevant data and some code to push the results to the server.

I don't think we want to support readWise directly but it will be nice to have an user plugin somewhere on the net :)

**Comment by nsvrana** [comment]
> @nsvrana:
> 
> You might be interested in #5794. Once we have a solid structure with enough information, implementing a minimal exporter that outputs a lua table would be easy.
> 
> Then it would be a matter of writting a textExporter, jsonExporter, etc. In that respect a readwiseExporter would work mostly as a json exporter with some filters to remove irrelevant data and some code to push the results to the server.
> 
> I don't think we want to support readWise directly but it will be nice to have an user plugin somewhere on the net :)

Exactly what I was hoping for - subscribed to #5794 and will keep an eye out. Maybe I'll learn a little Lua in the meantime!

**Comment by georgelemental** [comment]
The plugin currently tries (and generally fails) to extract author and title info from the filename. This works about as badly as one would expect. I am willing to write a PR to use metadata instead, but it could lead existing exports to no longer be recognized by the plugin.

**Comment by nsvrana** [comment]
> The plugin currently tries (and generally fails) to extract author and title info from the filename. This works about as badly as one would expect. I am willing to write a PR to use metadata instead, but it could lead existing exports to no longer be recognized by the plugin.

For me, personally, this would be very helpful and the breakage wouldn't matter to me. I'd have to rely on others for their feedback though.
