### ISSUE TITLE
FR: Show time left in chapter/book in header

### ISSUE THREAD

**Issue by Atrate** [koreader/koreader#6982]
Related: #4865, #5915

This is a feature from Nickel that I have found to be highly useful. KOReader could calculate the average WPM/PPM and basing on that calculate a rough estimate of how much reading time is left in chapter.

This information could be shown e.g. in the top/bottom header, as in Nickel.

**Comment by poire-z** [comment]
Don't we already have that ? `Gear > Status bar >`
<kbd>![image](https://user-images.githubusercontent.com/24273478/101985873-eaf4d780-3c8a-11eb-879f-53182d668130.png)</kbd>
(In the bottom footer - we don't have/want to have much control on the top header drawn by the EPUB rendering engine.)

**Comment by Atrate** [comment]
Huh, it seems that I am simply blind. Thanks much for clarifying!
