### ISSUE TITLE
battery charge status on sleep mode (KOBO Forma)

### ISSUE THREAD

**Issue by autagi** [koreader/koreader#6989]
**Does your feature request involve difficulty completing a task? Please describe.**
when in sllep mode it colud be usefull to see the status of chaging progress

**Describe the solution you'd like**
it could be suitable like in the orifinal firmware of Kobo

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by NiLuJe** [comment]
You can't, because the device is, well, asleep.

Fun fact: it even shuts off the charging LED.

**Comment by autagi** [comment]
thank you.
I thought it was possible, as happens with the original firmware that displays the charging status even in sleep

**Comment by NiLuJe** [comment]
Err, no it doesn't?

**Comment by autagi** [comment]
![WhatsApp Image 2020-12-13 at 17 10 43](https://user-images.githubusercontent.com/63999792/102017269-2fa17100-3d66-11eb-9131-6ec30da85e98.jpeg)
like in the image (sooy if I'm non clear)

**Comment by Frenzie** [comment]
Then it's lying about being asleep. ^_^ But while charging that doesn't matter, as long as it goes to sleep after you unplug it.

**Comment by NiLuJe** [comment]
Right, that's probably because you have the InfoWidget thingy enabled (I don't recall the settings name in Nickel, and I never used it myself).

In which case, @Frenzie is right, it actually prevents the device from sleeping (which means it might take that much longer to charge, although the delta should be minimal).

**Comment by autagi** [comment]
I get it.
this info should be enabled only when recharging otherwise the device is discharged in sleep.

**Comment by NiLuJe** [comment]
As far as I'm concerned, the charging LED was as far as I'm willing to mess with this. The fact that there's a giant USB lead attached to your device should already be hint enough that it's charging.

**Comment by Frenzie** [comment]
> this info should be enabled only when recharging otherwise the device is discharged in sleep.

Not necessarily. It could wake up every once in a while (think once or twice a day) to update something on the screen. But that seems like a whole lot of trouble for very little gain.

**Comment by autagi** [comment]
Thanks!
The update takes place by indicating the variations of each percentage point.
In any case it is not a problem if it is complicated to implement it.
The led should indicate when it is charged.
I take this opportunity to ask an OT thing:
When in power off it seems that the led does not work and therefore it is not clear when the device is charged: is it normal?

**Comment by NiLuJe** [comment]
As I mentioned above: when it's alseep/off: it's *really* off: the led turns off then, too.
