### ISSUE TITLE
OPDS Browser Incorrectly Handling Some Formats

### ISSUE THREAD

**Issue by mf81234** [koreader/koreader#6993]
* KOReader version: v2020.11-57-g222e752
* Device: Kindle Paperwhite 3

#### Issue
When opening some submenus on a amusewiki OPDS servers, only the first entry of each page is displayed.

#### Steps to reproduce

1. Add the following OPDS server entry to your catalog: https://staging.amusewiki.org/opds
2. Open the server.
3. Select Topics or Authors
4. Observe the entries and compare to the OPDS files from the server.

**Comment by mf81234** [comment]
Also observable on theanarchistlibrary.org/opds/, though it doesn't use pagination on Authors and Topics yet, so only the true first entry is shown

**Comment by NiLuJe** [comment]
It's actually following the `next` href, but only appending the *first* `entry` from each page.
