### ISSUE TITLE
Dictionaries not shown after downloading

### ISSUE THREAD

**Issue by leftshift** [koreader/koreader#7001]
* KOReader version: 2020.11
* Device: generic android

#### Issue
After downloading dictionaries with the `download dictionaries` feature in the app, they are not shown, it still displays `Manage dictionaries (0)`. However, the files seem to have been unpacked successfully, e.g. for the gnu english dictionary I can see the file `koreader/data/dict/gcide/stardict.idx` (and a tar.gz one directory higher).

I've also tried a bunch of other dictionaries but got none of them to show up.

I'm guessing this is not a general problem but it'd be really helpful to know where I could check next to narrow down what is happening.

#### Steps to reproduce
1. Download any dictionary via the `Download dictionaries` option
2. No dictionaries are shown

##### `crash.log` (if applicable)
I checked logcat but couldn't see anything that seemed to be related to dictionaries or any other errors.

**Comment by NiLuJe** [comment]
This was likely fixed a few days ago in #6990 ;).

**Comment by leftshift** [comment]
Thanks a lot, I tried manually downloading and unpacking the dictionary and that worked!
