### ISSUE TITLE
Two questions 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7004]
Hi, sorry for being annoying but I have two questions.
1st, How can I download and use OCR for Arabic texts? I'm trying to copy text from a pdf file (Arabic text) but it's (blank) so I think I need OCR or something.
2nd, when will be the next update (the December update)?
Thank you..

**Comment by Zeyadas** [comment]
And as I did last time, I forgot to mention that I'm using an android tablet.

**Comment by Frenzie** [comment]
You can put OCR files in /sdcard/koreader/data/tessdata.

https://github.com/koreader/koreader/wiki/Dictionary-support#dictionary-lookups-in-scanned-pages

> 2nd, when will be the next update (the December update)?

The habitual answer is WID, which might be tomorrow morning.

**Comment by Frenzie** [comment]
I'll close this now, but please feel free to add more information (preferably with a demo document) if it turns out not to be an OCR issue.
