### ISSUE TITLE
Insecure HTTPS->HTTP 302 redirects in OPDS catalogs fail but not made clear why

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#7007]
* KOReader version: 2020.11.60 (nightly)
* Device: Emulator & Clara HD

#### Issue

Some OPDS catalogs point to URLs which do a 302 Redirect. For example Project Gutenburg links to
* https://www.gutenberg.org/ebooks/46.epub.noimages
but this redirects to:
* http://www.gutenberg.org/cache/epub/46/pg46.epub
and the file that gets saved is:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://www.gutenberg.org/cache/epub/46/pg46.epub">here</a>.</p>
<hr>
<address>Apache Server at www.gutenberg.org Port 80</address>
</body></html>
```

#### Steps to reproduce

* Open Project Gutenburg OPDS catalog
* Try to download any book
* It will fail and a 302 redirect HTML file saved in its place (as above)
----
Similar for the ManyBooks catalog which is itself behind a 302: https://manybooks.net/opds/index.php → http://srv.manybooks.net/opds/index.php

And for books from the Flibuter catalog: https://www.flibusta.is/b/226848/epub → http://static.flibusta.is:443/converter/get/convert?url=http%3A%2F%2Fflibusta.is%2Fb%2F7412a0b774fdf8c0998b13e1ebeac686%2Fdownload&out=epub&md5=7412a0b774fdf8c0998b13e1ebeac686

**Comment by Frenzie** [comment]
The error handling toward the user could be improved slightly, but not allowing downgrading security is not a bug.

**Comment by Frenzie** [comment]
I.e., this describes a request that should not be allowed.
> 
    https://www.gutenberg.org/ebooks/46.epub.noimages
    but this redirects to:
    http://www.gutenberg.org/cache/epub/46/pg46.epub
    and the file that gets saved is:

**Comment by johnbeard** [comment]
Oh, so it's the HTTP -> HTTPS downgrade that's triggering this?

**Comment by johnbeard** [comment]
Annoyingly, for PG at least, HTTPS does work for the target: https://www.gutenberg.org/cache/epub/46/pg46.epub does exist and work, so their OPDS generator is busted.

**Comment by johnbeard** [comment]
C.f.: https://github.com/gbnewby/gutenbergsite/issues/10

**Comment by Galunid** [comment]
#6942 had follow redirect implemented, it was reverted because of https -> http downgrade, so once guttenberg fixes it it's pretty much ready to go (guards to prevent https -> http downgrade must be implemented though).

**Comment by Frenzie** [comment]
@Galunid What you did in there was an ugly hack to get around the restriction. Redirects will be followed completely automatically because of https://github.com/koreader/koreader/pull/6334

**Comment by johnbeard** [comment]
Project Gutenburg appears to have fixed it at their end. ManyBooks and FIlbusta still show this.

So I guess this issue is now about popping a sensible message for the user like "Insecure HTTPS->HTTP downgrade blocked: go and moan at the OPDS catalog publisher for doing it wrong"?

**Comment by Frenzie** [comment]
ManyBooks works just fine for me. Apparently someone changed it to HTTPS, but my program has retained the old URL: `http://manybooks.net/opds/index.php`.

**Comment by Frenzie** [comment]
Same for Filibusta. Just change those URLs back.

**Comment by Frenzie** [comment]
Problem introduced by https://github.com/koreader/koreader/commit/960b2ae62ae71d17cf59d22ca7ae249884de5873

**Comment by Frenzie** [comment]
Anyway, I'll have a look at the insecure downgrade thing too.
