### ISSUE TITLE
PB632: "Night mode" setting as displayed in menu, becomes inverted with actually applied setting after poweroff

### ISSUE THREAD

**Issue by JasperE84** [koreader/koreader#7017]
* KOReader version: 2020.12
* Device: Pocketbook PB632 - U632.6.1.900 / 20201001_123124 / WW

#### Issue
After powering down with night mode enabled, and then starting the device to resume a book, the "Night mode" setting will show up in menu as enabled while the applied setting is actually disabled. 
If Night Mode is subsequently disabled in the menu (checkbox empty), it will actually be enabled. 
The applied night mode setting becomes inverted from the setting state as shown in menu.

#### Screenshot
In the screenshot below, night mode is supposed to be enabled (checkbox marked) but is actually disabled (white background, black text)
![Reader_2020-12-20_170933](https://user-images.githubusercontent.com/12022716/102718297-b1097e00-42e7-11eb-88a7-a6b4e05bd096.png)

#### Steps to reproduce

1. Open ebook
2. Enable night mode
3. Wait for device to go in battery saving mode
4. Power on pocketbook 
5. KOReader will reopen book and resume with inverted night mode 

(I already reinstalled KOReader overwriting all files to see if that fixes it.)

**Comment by NiLuJe** [comment]
That's a known issue in some (old) i.MX kernels: suspend breaks EPDC flags handling.

You can either live with it, or disable HW inversion on that device.

**Comment by NiLuJe** [comment]
c.f., the [Kobo Aura](https://github.com/koreader/koreader/blob/90ad2bcf521860312c042e4a7c5067f161bc7e60/frontend/device/kobo/device.lua#L118-L128) for an example of what such an exception looks like in practice.

**Comment by JasperE84** [comment]
I have set `canHWInvert = no,` in `\applications\koreader\frontend\device\pocketbook\device.lua` in line 43 for pocketbook defaults and added the same config line in block:

```
-- PocketBook Touch HD Plus / Touch HD 3 (632)
local PocketBook632 = PocketBook:new{
  model = "PBTouchHDPlus",
  display_dpi = 300,
  isAlwaysPortrait = yes,
  usingForcedRotation = landscape_ccw,
  hasNaturalLight = yes,
  canHWInvert = no,
}
```
(PBTouchHDPlus is indeed the modelname that shows when opening the help>report a bug dialog) 
Unfortunately that doesn't fix it. 
I might add that simply exiting KOReader and restarting it also presents the issue.

**Comment by NiLuJe** [comment]
`canHWInvert` was globally set to no on PB before, hence the behavior change.

**Comment by NiLuJe** [comment]
I also forgot that *that* meant that the C BB could never be used (because it doesn't support SW inversion), which is probably why that alone doesn't fix it, as that mechanism is gone now.

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/device/pocketbook/device.lua b/frontend/device/pocketbook/device.lua
index 798bd44f..295e3339 100644
--- a/frontend/device/pocketbook/device.lua
+++ b/frontend/device/pocketbook/device.lua
@@ -455,6 +455,9 @@ local PocketBook632 = PocketBook:new{
     isAlwaysPortrait = yes,
     usingForcedRotation = landscape_ccw,
     hasNaturalLight = yes,
+    -- Buggy kernel, c.f. #7017
+    canUseCBB = no,
+    canHWInvert = no,
 }
 
 -- PocketBook Color (633)
```

Ought to do it.

**Comment by JasperE84** [comment]
Thanks again. Unfortunately that doesn't seem to fix it, anything else I can test?

(By the way, being new to koreader/lua, I'm just editing the .lua files and restarting KOReader. I assume there's no compiling to do since I checked that koreader won't start if I purposely introduce a syntax error in the lua)

**Comment by Frenzie** [comment]
That's correct, except for recompiling libraries you can do everything in
Lua by just restarting..

**Comment by NiLuJe** [comment]
That makes... zero sense, unless you're editing the wrong copy of KOReader? (Which apparently is a thing that's apparently possible on PB, so, who knows ^^).

**Comment by Frenzie** [comment]
> (Which apparently is a thing that's apparently possible on PB, so, who knows ^^).

I've done it on Kobo in the past, though I suppose you mean by means other than putting on multiple versions in different folders yourself? :-P

**Comment by JasperE84** [comment]
I don't think so. Note the TEST123


![image](https://user-images.githubusercontent.com/12022716/102725205-41aa8300-4315-11eb-8bee-8a860dc69244.png)

![image](https://user-images.githubusercontent.com/12022716/102725245-b2519f80-4315-11eb-8650-9204314cff68.png)

**Comment by JasperE84** [comment]
And a screenrecording of how it happens:

https://user-images.githubusercontent.com/12022716/102725414-dc579180-4316-11eb-8ca0-1e633b7b9b51.mp4

**Comment by NiLuJe** [comment]
Well, unless something in the PB codepath manages to bypass the CBB blacklist, somehow, no idea.

(I mean, it'd make sense for HW nightmode to be buggy. But for SW nightmode to do so, not so much: it's used on Android & the emulator, any wonkiness that obvious would have been noticed sooner).

**Comment by NiLuJe** [comment]
Hmm. it's conceivable that the fb reinits done by the HW rotation shenanigan completely forget about the inversion flag, so, let's try to disable that, too:

```diff
diff --git a/frontend/device/pocketbook/device.lua b/frontend/device/pocketbook/device.lua
index 798bd44f..26eb6bbe 100644
--- a/frontend/device/pocketbook/device.lua
+++ b/frontend/device/pocketbook/device.lua
@@ -453,8 +453,10 @@ local PocketBook632 = PocketBook:new{
     model = "PBTouchHDPlus",
     display_dpi = 300,
     isAlwaysPortrait = yes,
-    usingForcedRotation = landscape_ccw,
     hasNaturalLight = yes,
+    -- Buggy kernel, c.f. #7017
+    canUseCBB = no,
+    canHWInvert = no,
 }
 
 -- PocketBook Color (633)
```

**Comment by JasperE84** [comment]
That's excellent, it is indeed the usingForcedRotation parameter that breaks it.

Here's a config that works:

```
-- PocketBook Touch HD Plus / Touch HD 3 (632)
local PocketBook632 = PocketBook:new{
    model = "PBTouchHDPlus",
    display_dpi = 300,
    isAlwaysPortrait = yes,
    hasNaturalLight = yes,
}
```

**Comment by Frenzie** [comment]
Could you please submit a PR to fix it for everyone? ;-) I'll reopen it in the meantime so we won't forget about it.

**Comment by JasperE84** [comment]
Here you go. https://www.dropbox.com/s/umt0dilless7rr7/crash.log?dl=0

BTW, c blitter was already disabled in dev options

**Comment by torwag** [comment]
I can state that it seems to fix the night mode problem on Pockebook Inkpad 3 (PB740).
