### ISSUE TITLE
Back/up icon in OPDS catalogs doesn't work as expected from top of catalog

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#7025]
* KOReader version: nightly
* Device: Clara HD + Emulator

#### Issue

The back/up icon in the bottom left of an ODPS catalog doesn't work as expected from the top level of the catalog

#### Steps to reproduce

* Open OPDS list
* Enter, say, Project Gutenberg, then Popular
* Press back/up
* Now at the PG top level
* Press back/up again
* Should be: at the OPDS catalog
* Actually: tries to open a different catalog and fails

**Comment by NiLuJe** [comment]
I, err, can't reproduce that?

I do end up back at the OPDS catalog list.

----

Can you check what happens on your end with verbose debug enabled?

**Comment by johnbeard** [comment]
Hmm, actually it's not only going to the last OPDS catalog, it's trying to go to the last Dropbox folder I had open.
```
12/22/20-17:15:35 DEBUG Browse opds url https://gallica.bnf.fr/opds
12/22/20-17:15:35 INFO  request {
    ["method"] = "HEAD",
    ["sink"] = function: 0x7f09bebddf10,
    ["url"] = "https://gallica.bnf.fr/opds",
    ["headers"] = {
        ["Host"] = "gallica.bnf.fr",
    },
}
12/22/20-17:15:35 DEBUG Cache hit for opds|catalog|https://gallica.bnf.fr/opds
12/22/20-17:15:35 DEBUG setDirty via a func from widget table: 0x7f09c111eba0
12/22/20-17:15:35 DEBUG setDirty via a func from widget table: 0x7f09c111eba0
12/22/20-17:15:35 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:35 DEBUG painting widget: table: 0x7f09d5de3bf8
12/22/20-17:15:35 DEBUG blitFrom 7 876 0 0 36 36
12/22/20-17:15:35 DEBUG _refresh: Enqueued ui update for region 0 0 800 914 
12/22/20-17:15:35 DEBUG _refresh: Enqueued ui update for region 0 0 800 914 
12/22/20-17:15:35 DEBUG refresh on physical rectangle 0 0 800 914
12/22/20-17:15:35 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG input event => type: 3, code: 57(nil), value: 0, time: 1608657336.403091
12/22/20-17:15:36 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG input event => type: 3, code: 53(nil), value: 35, time: 1608657336.403106
12/22/20-17:15:36 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG input event => type: 3, code: 54(nil), value: 894, time: 1608657336.403111
12/22/20-17:15:36 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1608657336.403114
12/22/20-17:15:36 DEBUG in tap state...
12/22/20-17:15:36 DEBUG set up hold timer
12/22/20-17:15:36 DEBUG adjusted ges: touch
12/22/20-17:15:36 DEBUG AutoSuspend: onInputEvent
12/22/20-17:15:36 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1608657336.488463
12/22/20-17:15:36 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1608657336.488474
12/22/20-17:15:36 DEBUG in tap state...
12/22/20-17:15:36 DEBUG single tap detected in slot 0 {
    ["y"] = 894,
    ["w"] = 0,
    ["h"] = 0,
    ["x"] = 35,
}
12/22/20-17:15:36 DEBUG adjusted ges: tap
12/22/20-17:15:36 DEBUG AutoSuspend: onInputEvent
12/22/20-17:15:36 DEBUG Explicit widgetRepaint: table: 0x7f09be45f3d0 @ ( 5 , 874 )
12/22/20-17:15:36 DEBUG blitFrom 7 876 0 0 36 36
12/22/20-17:15:36 DEBUG setDirty via a func from widget nil
12/22/20-17:15:36 DEBUG not painting 1 covered widget(s)
12/22/20-17:15:36 DEBUG _refresh: Enqueued fast update for region 5 874 40 40 
12/22/20-17:15:36 DEBUG refresh on physical rectangle 5 874 40 40
12/22/20-17:15:36 INFO  request {
    ["method"] = "HEAD",
    ["sink"] = function: 0x7f09e46752d8,
    ["url"] = "/",
    ["headers"] = {},
}
12/22/20-17:15:36 INFO  cannot get catalog info from / frontend/ui/widget/opdsbrowser.lua:323: invalid host 'nil'
```
* Open Cloud Storage
* Navigate to a dropbox folder (the root of a dropbox account will do)
* Close with "×"
* Open OPDS catalog
* Enter Project Gutenburg
* Back/up
* `Error: Cannot get catalog into from /`

The same happens if you open different catalogs:
* Open OPDS list
* Open Feedbooks - options are "Most Popular", "Recently Added", "Fiction", "Non-fiction"
* Close with "×"
* Open OPDS list again, choose Project Gutenberg: options are "Popular", "Latest", "Random"
* Back/up
* Feedbooks catalog is opened, not the catalog list
* Press back/up again
* Goes to the previous catalog (or tries to go to Dropbox and fails)

**Comment by NiLuJe** [comment]
Okay, I don't have the Cloud Storage plugin enabled, but I can indeed reproduce the second example, thanks ;).

@poire-z: Could that be related to the "Back" history stack?

**Comment by Frenzie** [comment]
The file widget doesn't have one, does it?

**Comment by poire-z** [comment]
I'm only familiar with the various "back/location history stacks" in documents, when jumping pages/skimming/following links.
I guess OPDS might be about using KeyValuePage or that kind of widgets - which I'm not sure they have a proper stack handling (from what I remember, the statisctics plugin might manage itself its back/up navigation). Not familiar with all that :/

**Comment by johnbeard** [comment]
This now appears to be working for me.

**Comment by NiLuJe** [comment]
Oh, right, forgot a close/fix keyword in the PR ;).
