### ISSUE TITLE
FR: OPDS catalog name in titlebar

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#7030]
I think the OPDS catalogs should show their names at the top of the screen rather than "OPDS catalog" all the time. E.g. "Project Gutenberg".

E.g. you can't tell what catalog this is:

![2020-12-22_194627_645x290_screenshot](https://user-images.githubusercontent.com/5386578/102927212-6e35da80-448e-11eb-8ce0-f6df3152e150.png)

From a quick poke at the code, the title is set in `frontend/apps/opdacataog/opdscataog.lua`, but the widget itself `frontend/ui/widget/opdsbrowser.lua` is what knows the title. How to feed back the title to the `OPDSCatalog` object? A callback passed to the `OPDSBrowser` object?

**Comment by NiLuJe** [comment]
Turned out working on #7028 helped ;p.

**Comment by NiLuJe** [comment]
(It was slightly easier to just update every time, so the title is actually the text of the last selected entry, and not just the top-level catalog's name).
