### ISSUE TITLE
Autosuspend Not Working on Remarkable 1

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7045]
* KOReader version: koreader-remarkable-v2020.12-39-gb2b9b49_2020-12-23
* Device: RM 1

#### Issue
Autosuspend resets its timer immediately after time has elapsed.

#### Steps to reproduce
1. Set autosuspend timeout to the minimum (5 min)
2. Leave device idle for 5+ min
3. Device fails to suspend

#### Extra information
- Suspend fails even when device is left idle after a reboot
- Autoshutdown timer set to longer than Autosuspend timeout to avoid https://github.com/koreader/koreader/issues/6901
- Tested with all other plugins disabled and this made no difference

##### `crash.log`
Attached [here](https://github.com/koreader/koreader/files/5740106/crash.log)

**Comment by pazos** [comment]
@gbyl: autosuspend was never meant for the ReMarkable.It was added in https://github.com/koreader/koreader/pull/6772 because it was reported as working in https://github.com/koreader/koreader/issues/6769. It makes sense as the RM1 shares a lot of stuff in common with other NTX boards, like Kobos.

Unfortunately the ReMarkable is not a very well tested platform on our end. We believe user reports (and a couple of videos) and acknowledge that KOReader is working to some degree, but that's it. All the bugs and issues need to be ironed out by actual RM users.

**Comment by gbyl** [comment]
That makes sense. I wanted to at least document it, since Autosuspend seemed to be working fine a few releases ago.

**Comment by snelg** [comment]
Hmm, autosuspend is working fine on my RM2.
I did notice that autosuspend (intentionally) does not suspend the device if it's charging. If it's charging, then you get a crash log like the one you attached, i.e. it resets the timer each timeout cycle instead of suspending.

**Comment by gbyl** [comment]
@snelg Interesting. I have made sure that the device is not connected every time I have tried autosuspend. Does autoshutdown work for you?

**Comment by snelg** [comment]
Just tried it, and yes shutdown works too, as long as the shutdown timer is less than the suspend timer.
I haven't manually added or activated any other plugins. But I just realized that I *did* manually add this change, which happened after the 2020.12 release:
https://github.com/koreader/koreader/commit/09c1f35191a67c3c86680264951c4f8ba4c6de58

**Comment by gbyl** [comment]
Hmm I wonder if this is an RM 1 only problem. That may not make much sense though. I even did a complete factory reset and reinstall of koreader, and yet autosuspend is never triggered. We'll see if someone else can reproduce it.

**Comment by gbyl** [comment]
Got autoshutdown and autosuspend to work, but only with values of 72 seconds (0.02 hours) or less. Anything more than that and the device fails to suspend.

**Comment by NiLuJe** [comment]
As I said the first time (unless I'm mixing issues around, which is entirely possible), your "failing" logs showed weird input events, which of course will reset the timer.

I'd investigate the cause of said input events ;).

**Comment by gbyl** [comment]
@NiLuJe You did in fact mentioned that here https://github.com/koreader/koreader/issues/6901#issuecomment-731851153 I have made sure not to connect/disconnect the device as to avoid those inputs, but sadly the issue persists

**Comment by NiLuJe** [comment]
Well, they're certainly coming from *somewhere*, and that somewhere is unlikely to be KOReader itself, we're just interpreting them :).

I'd check what else is running, and double-check what's really happening with something like evtest or evemu ;).

**Comment by gbyl** [comment]
That's a good point. I'll see if can figure out how to use evtest/evemu and report back. Thanks for the suggestion!

**Comment by Galunid** [comment]
By any chance do you have one of those magnetic thingies you put in your usb port? I had one of those and it used to cause issues.

**Comment by gbyl** [comment]
@Galunid hmm not sure what you are referring to, do you mean something like a case?

**Comment by Galunid** [comment]
I meant [this](https://www.amazon.com/Magnetic-Ainoke-Charging-Braided-Android-USB/dp/B07PBBSMTN), but since you didn't understand, you probably don't have it.

**Comment by gbyl** [comment]
@Galunid Yeah that's a fair assumption. I don't have anything like that. Thanks for the suggestion though

**Comment by NiLuJe** [comment]
That raises a similar query, though, because I think the rM does have a hall sensor: are you using a "smart" magnetic cover, and/or are there strong magnets around your device?

**Comment by NiLuJe** [comment]
And, in case it's kernel uevents being misinterpreted into bogus fake input events, `uevent echo` might help, too.

**Comment by gbyl** [comment]
@NiLuJe Not really, but just to make sure I tested autosuspend in a location away from other electronics and the result was the same. I don't really understand why it works flawlessly with very low timeout values like "10 seconds" but past a certain threshold the timer just gets restarted. I'll give `uevent echo` a try.

**Comment by NiLuJe** [comment]
If your spurious events happen at a somewhat large interval, switching the suspend timeout lower than that effectively hides their interaction away, hence it working.

**Comment by gbyl** [comment]
I was unable to figure out how to run `evtest`, `evemu` or `uevent` on the remarkable. In any case, it appears that this issue is affecting my device only, so it might just be a hardware defect. I will leave the thread open for a while to see if someone else can reproduce.

**Comment by snelg** [comment]
If you have `docker` on your machine, here are instructions for compiling a version of `evtest` that can run on the reMarkable, copied from this page
https://duckpond.ch/nix/bash/2020/01/08/reMarkable.html

```
$ git clone https://github.com/freedesktop-unofficial-mirror/evtest.git
$ cd evtest
$ docker \
  run --rm \
  dockcross/linux-armv7a > dockercross
$ chmod +x dockercross
$ ./dockercross bash -c "autoreconf -iv && ./configure --host=arm-linux-gnueabi && make"
```

If you don't have docker but you trust some random dude on the internet (i.e. me), then here's the reMarkable-ready copy of `evtest` I built with those instructions, and just now tossed on an old site of mine:

https://moosebutter.com/evtest

**Comment by gbyl** [comment]
@snelg Thank you, I'll give this a try and see what I learn about the issue.

**Comment by gbyl** [comment]
@snelg I might be doing something wrong, but `evtest /dev/input/event1` is not showing anything on my end. What should be displayed as output?

**Comment by zelomel** [comment]
I have the same issue. My rM1 with KOReader 2020.12-107 never goes autosuspend or autoshutdown.

**Comment by gbyl** [comment]
@zelomel Thank you for reporting it. Did it ever work for you in the past?

**Comment by zelomel** [comment]
I was using Koreader about 1 year ago and stopped. I don't remember if it worked. I came back to Koreader few days ago only.

**Comment by snelg** [comment]
> @snelg I might be doing something wrong, but `evtest /dev/input/event1` is not showing anything on my end. What should be the expected output?

@gbyl Here's an example what I get when I ssh via a USB connection to my rm2:

```
reMarkable: ~/ ./evtest /dev/input/event2
Input driver version is 1.0.1
Input device ID: bus 0x0 vendor 0x0 product 0x0 version 0x0
Input device name: "cyttsp5_mt"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
  Event type 2 (EV_REL)
  Event type 3 (EV_ABS)
    Event code 25 (ABS_DISTANCE)
      Value      0
      Min        0
      Max      255
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max       31
    Event code 48 (ABS_MT_TOUCH_MAJOR)
      Value      0
      Min        0
      Max      255
    Event code 49 (ABS_MT_TOUCH_MINOR)
      Value      0
      Min        0
      Max      255
    Event code 52 (ABS_MT_ORIENTATION)
      Value      0
      Min     -127
      Max      127
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     1403
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     1871
    Event code 55 (ABS_MT_TOOL_TYPE)
      Value      0
      Min        0
      Max        1
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
    Event code 58 (ABS_MT_PRESSURE)
      Value      0
      Min        0
      Max      255
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
Testing ... (interrupt to exit)
```

and then it keeps running until I hit ctrl-C. While it's running, it spits out events from whichever input device it's watching, e.g.

```
Event: time 1610307058.125788, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 963
Event: time 1610307058.125788, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 876
Event: time 1610307058.125788, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 43
Event: time 1610307058.125788, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 91
Event: time 1610307058.125788, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 17
Event: time 1610307058.125788, type 3 (EV_ABS), code 49 (ABS_MT_TOUCH_MINOR), value 8
Event: time 1610307058.125788, -------------- SYN_REPORT ------------
Event: time 1610307058.125788, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 40
Event: time 1610307058.125788, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 32
```

Note that the device mapping is different between rm1 and 2.
rm1:
stylus: `/dev/input/event0`
touchscreen: `/dev/input/event1`
buttons: `/dev/input/event2`

rm2:
stylus: `/dev/input/event1`
touchscreen: `/dev/input/event2`
buttons: `/dev/input/event0`

**Comment by NiLuJe** [comment]
I can't quite recall what kind of events the spurious ones where, so it might be a good idea to listen to all three of them, *and* to the uevent feed (`uevent echo`) to cover all bases.

**Comment by gbyl** [comment]
@snelg Thank you for posting that. Yes, that's what I imagined should have been the ouput. Unfortunately, in my case, no events are recognized (regardless of the input). The log invariably stops here:

```
Properties:
  Property type 1 (INPUT_PROP_DIRECT)
Testing ... (interrupt to exit)
***********************************************
  This device is grabbed by another process.
  No events are available to evtest while the
  other grab is active.
  In most cases, this is caused by an X driver,
  try VT-switching and re-run evtest again.
  Run the following command to see processes with
  an open fd on this device
 "fuser -v /dev/input/event1"
***********************************************
```

**Comment by NiLuJe** [comment]
I don't recall all the details, but that's probably KOReader itself.

c.f., `KO_DONT_GRAB_INPUT` in koreader.sh

I have no idea why it's only enabled by default on the rM 2?

**Comment by gbyl** [comment]
@NiLuJe As usual, you are absolutely right. It should definitely be enabled by default for both rm1 and rm2. I just tweaked `koreader.sh` and now `evtest` works.

**Comment by gbyl** [comment]
@snelg @NiLuJe  I have used `evtest` to sample all three inputs for 120 seconds. All my tests show that there is no such event. Something else is resetting the timer. Any ideas?

**Comment by NiLuJe** [comment]
> _and_ to the uevent feed (`uevent echo`) to cover all bases.

**Comment by NiLuJe** [comment]
Also, define "no such event"?

**Comment by gbyl** [comment]
@NiLuJe I just meant that no spurious event is shown in that interval that would theoretically be resetting the timer past the 60-second threshold

**Comment by NiLuJe** [comment]
Compare with your actual verbose KOReader logs, then ;).

If you see something in the log, you should * definitely* see it in evdev (or uevent if it's a synthetic event).

**Comment by gbyl** [comment]
@NiLuJe
> _and_ to the uevent feed (`uevent echo`) to cover all bases.
```
root@reMarkable:~# uevent
-sh: uevent: command not found
```

```
root@reMarkable:~# busybox uevent
uevent: applet not found
```

> If you see something in the log, you should definitely see it in evtest/evemu (or uevent if it's a synthetic event).

All the log shows is that (for any timeout value higher than 60 seconds) the timer gets reset as soon as the time elapses.

**Comment by NiLuJe** [comment]
You'll need a *verbose* debug log to see input events, like the last time. The timer doesn't reset for anything else.

**Comment by NiLuJe** [comment]
And there's a fairly good chance that [this Kobo busybox build](https://svn.ak-team.com/svn/Configs/trunk/Kindle/Kobo_Hacks/USBNetwork/src/usbnet/bin/busybox) will behave on rM ;).

**Comment by gbyl** [comment]
@NiLuJe 
> Speaking of, actually _seeing_ the logs (of all the things mentioned) would be helpful :).

Well, the logs don't really show much other than confirm the reset of the timer:

```
01/15/21-08:32:07 DEBUG AutoSuspend: unschedule
01/15/21-08:32:07 DEBUG AutoSuspend: start at 1610721127
01/15/21-08:32:07 DEBUG AutoSuspend: schedule suspend in 90
01/15/21-08:32:07 DEBUG AutoSuspend: schedule shutdown in 300
01/15/21-08:32:07 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin
01/15/21-08:32:07 INFO  FM loaded plugin gestures at plugins/gestures.koplugin
01/15/21-08:33:37 DEBUG AutoSuspend: schedule suspend in 90
01/15/21-08:33:37 DEBUG AutoSuspend: schedule shutdown in 300
01/15/21-08:35:07 DEBUG AutoSuspend: schedule suspend in 90
01/15/21-08:35:07 DEBUG AutoSuspend: schedule shutdown in 300
01/15/21-08:36:37 DEBUG AutoSuspend: schedule suspend in 90
01/15/21-08:36:37 DEBUG AutoSuspend: schedule shutdown in 300
01/15/21-08:37:07 DEBUG AutoSuspend: schedule suspend in 90
01/15/21-08:37:07 DEBUG AutoSuspend: schedule shutdown in 300
```

> And there's a fairly good chance that [this Kobo busybox build](https://svn.ak-team.com/svn/Configs/trunk/Kindle/Kobo_Hacks/USBNetwork/src/usbnet/bin/busybox) will behave on rM, and it includes the `uevent` applet ;).

That does work. Running `busybox uevent echo` returns an empty output though, regarless of how long I wait.

**Comment by NiLuJe** [comment]
Does the device happen to be charging?

If it does, that's by design, it will never suspend/shutdown when charging, and simply reschedules ;).

**Comment by NiLuJe** [comment]
As for `uevent`, my bad, the magic is in the env, so: `env -i uevent env`

**Comment by gbyl** [comment]
@NiLuJe 
> As for `uevent`, my bad, the magic is in the env, so: `env -i uevent env`

What worked was: `./busybox env -i uevent env`. Though that still isn't showing anything after listening for minutes

> Does the device happen to be charging?
> If it does, that's by design, it will never suspend/shutdown when charging, and simply reschedules ;).

The device was not charging. But I suspect you are onto something. I noticed that the main menu shows the battery icon with the little lightning graphic in the middle when the device is not connected! So, it is possible that something is making the device 'think' that it is always charging. How would you troubleshoot that?

**Comment by NiLuJe** [comment]
https://github.com/koreader/koreader/blob/f52fffd4676797557e90f9f8a71327407a95d643/frontend/device/remarkable/device.lua#L44



https://github.com/koreader/koreader/blob/f52fffd4676797557e90f9f8a71327407a95d643/frontend/device/remarkable/powerd.lua#L21-L23

**Comment by gbyl** [comment]
@NiLuJe That is it! I commented out all those lines and now it works. Not quite a solution, but we are closer to finding the culprit.

**Comment by gbyl** [comment]
I think I found the problem. The condition below doesn't always work:
https://github.com/koreader/koreader/blob/f52fffd4676797557e90f9f8a71327407a95d643/frontend/device/remarkable/powerd.lua#L22

The reason being that in RM1 `/sys/class/power_supply/bq27441-0/status` can sometimes contain `Charging\nCharging\n` and not just `Charging\n`

**Comment by Frenzie** [comment]
Is there another way to get the status? Otherwise just a `:gmatch("Charging")` or something I suppose.

**Comment by gbyl** [comment]
@Frenzie If there is another way, I am not aware of it. Are you proposing `return self:read_str_file(self.status_file) == self:gmatch("Charging")`?

**Comment by Frenzie** [comment]
That'd be something closer to `self:read_str_file(self.status_file):match("Charging") == "Charging"` or alternatively `string.match(self:read_str_file(self.status_file), "Charging") == "Charging"`, but yes.

(I said gmatch as a reflex, but that shouldn't be needed here.)

**Comment by gbyl** [comment]
@Frenzie Well, I tried both of those options with different timeout values and unfortunately both of those options return `true` all the time — resetting the timer

**Comment by NiLuJe** [comment]
Sidebar: Is that sysfs file ro or rw? 

Because that *vaguely* looks like something in userspace appending in there where it really shouldn't.

Otherwise, it's a kernel bug :}.

**Comment by NiLuJe** [comment]
Sidebar n°2: Those helper functions are reinventing the wheel. [io.read supports `*line` and `*number`](https://www.lua.org/pil/21.1.html).

**Comment by Frenzie** [comment]
@gbyl What other values are possible? What I wrote definitely works:
```
> bla = "not charging"
> print(bla:match("Charging") == "Charging")
false
> print(bla:match("charging") == "charging")
true
```

**Comment by Frenzie** [comment]
I mean, if it's saying "Charging… HAHA FOOLED YOU :-D" or something. ;-)

**Comment by gbyl** [comment]
> Sidebar: Is that sysfs file ro or rw?
> 
> Because that _vaguely_ looks like something in userspace appending in there where it really shouldn't.
> 
> Otherwise, it's a kernel bug :}.

```
root@reMarkable:~# ls -l /sys/class/power_supply/bq27441-0/status
-r--r--r--    1 root     root          4096 Jan 15 17:02 /sys/class/power_supply/bq27441-0/status
```

**Comment by Frenzie** [comment]
I implicitly meant slightly more checks for the record, perhaps "^Charging\n".

**Comment by gbyl** [comment]
> What other values are possible?

As far as I can tell, it only appends "Charging\n" a second time, but it could be doing it multiple times

**Comment by Frenzie** [comment]
> As far as I can tell, it only appends "Charging\n" a second time, but it could be doing it multiple times

To be clear, what's written above will always return true as long as the word "Charging" occurs in the string. It doesn't matter how many times because it stops looking after the first occurrence. So if you say it's always returning true either the value in `/sys/class/power_supply/bq27441-0/status` is completely wrong (i.e., it's always `Charging`), or it's something like I said above. In real life I suppose that'd be closer to something like `Charging\nUnplugged\n` but that's besides the point.

```
> bla = "lalalal\nblahblah\ncharging"
> print(bla:match("charging"))
charging
```

```
> blab = "asdfasfasdfchargingasdfsfsdf"
> print(blab:match("charging"))
charging
```

**Comment by gbyl** [comment]
@Frenzie I think the value is `Charging` even when it is not connected at all. I have noticed that upon powering on the device it shows as charging. After a few taps/swipes it realizes that it is not charging. But then when idle after a certain time it goes back to thinking it is charging.

**Comment by NiLuJe** [comment]
FWIW, it read `Not charging` on NTX boards ;).

**Comment by gbyl** [comment]
> May inadvertently help w/ #7045 (or make it worse, depending on how broken the kernel is ;p).

Just documenting that https://github.com/koreader/koreader/pull/7149#issue-556043784 didn't change anything in regards to this issue. Was the `\n` in `return self:read_str_file(self.status_file) == "Charging"` never needed?.

**Comment by NiLuJe** [comment]
It was with `io.read(*all)`, it isn't with `io.read(*line)`.

This still needs someone actually answering @Frenzie's questions to fix it properly. (i.e., what are the *actually observed* contents on that file in every context imaginable).

**Comment by gbyl** [comment]
@NiLuJe On RM1 the output of `cat /sys/class/power_supply/bq27441-0/status` is either:
`Charging`
or
`Discharging`

**Comment by Frenzie** [comment]
`Charging` (uppercase C) won't match `charging` (lowercase c), so that definitely shouldn't return a truthy value.

**Comment by gbyl** [comment]
> Charging (uppercase C) won't match charging (lowercase c), so that definitely shouldn't return a truthy value.

Agreed, this line is not the problem:

https://github.com/koreader/koreader/blob/6f50d67b5d8d14b57551c0befd025e5119fc7e8c/frontend/device/remarkable/powerd.lua#L22

https://github.com/koreader/koreader/issues/7045#issuecomment-761226367 was a false flag. The output `Charging\nCharging\n` was an error of refresh from checking the file with `nano`, rather than `cat`. So we can forget about that.

**Comment by gbyl** [comment]
Now that we have wifi on RM1, I have been able to run more tests and have learned some new things.

@NiLuJe @Frenzie correct me if I am wrong. As far as KOReader is concerned, the device is ***idle*** when: no events are registered & it is not charging. Autosuspend will only be triggered when the timeout period has elapsed and those two conditions are met, right?

Here is exactly what I am doing:

1. Unplug RM1.
2. Connect RM1 to Wi-Fi
3. Make sure there are no input events.
4. SSH into RM1
5. cat /sys/class/power_supply/bq27441-0/status = `Discharging`
6. Wait roughly 60 seconds
7. cat /sys/class/power_supply/bq27441-0/status = `Charging`

Once it magically changes to `Charging` it stays with that value. However, if I tap/swipe the screen, RM1 *realizes* that it is not charging and switches to `Discharging`. Left another 60 seconds idle though and it goes back to `Charging`. And the cycle begins again.

**Comment by Frenzie** [comment]
> As far as KOReader is concerned, the device is idle when: no events are registered & it is not charging. Autosuspend will only be triggered when the timeout period has elapsed and those two conditions are met, right?

That sounds about right. If it notices it's charging it simply resets the countdown.

**Comment by NiLuJe** [comment]
Then I'm afraid we're back to: "it's a kernel bug", which means there's not really anything we can do about that.

**Comment by gbyl** [comment]
> we're back to: "it's a kernel bug"

@NiLuJe There is no doubt about that now. Feel free to mark this issue as "not our bug" and close it. Thank you all so much for the help!

**Comment by gbyl** [comment]
kernel bug
