### ISSUE TITLE
FR: Start filebrowser if the last book doesn't exist

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7049]
To start KOReader I use very nice launcher by @yparitcher
https://github.com/yparitcher/KUAL_Booklet/releases

If the last book was deleted (not by KOReader) the program cannot be started, I need to launch it by KUAL (filemanager) or edit defaults.lua.
I propose to start filebrowser if the last book doesn't exist.

**Comment by Frenzie** [comment]
> I propose to start filebrowser if the last book doesn't exist.

That's how it works already. If it's different on Kindle, presumably it's on purpose?

**Comment by hius07** [comment]
Asking @NiLuJe of the purpose?

**Comment by Frenzie** [comment]
I think it's more likely to be part of KUAL or however that works than anything related to KOReader at all. ^_^

**Comment by NiLuJe** [comment]
I can't check the code right now, but it's likely to be launching koreader.sh without arguments, hence the last doc. KUAL has an entry for both options, which obviously doesn't work here ;).

I don't recall how I handle that on Kobo, but it's likely that I default to passing the default Home folder, hence always going to the FM.

**Comment by NiLuJe** [comment]
IIRC we should be handling a deleted document fine, though, but admittedly it's not a codepath I ever test.

**Comment by hius07** [comment]
Now it shows infomessage "filename does not exist" and quits.

**Comment by yparitcher** [comment]
It runs `"/bin/sh", "-c", "{ /mnt/us/koreader/koreader.sh --kual --asap ; } 2>>/var/tmp/KOL.log &"` as I usualy want to go to the last document and the point was to be as quick as possible so koreader.sh w/o arguments.

I traced this bug down to the way reader.lua parses it args (it does deal with deleted documents but we chose not to use that path :smile:), PR coming soon.
