### ISSUE TITLE
Too slow opening large files 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7056]
Before I forget to mention, I'm using an android tablet (Samsung galaxy Tab A - T285).
When I open a (large) epub file (about 12 MB) it takes too long to open and i get a message (I don't know what do you call it as programmer) that koreader is not responding do you want to close it? Wait or close, and I have to choose wait several times till the file is opened and the progress bar in the upper left corner is going on perfectly but obviously slow.. 
Even though a larger pdf file will open smoothly.
![Screenshot_2020-12-26-10-33-40](https://user-images.githubusercontent.com/70109540/103149838-79368680-477e-11eb-95b5-3ba14d4daeaf.png)

**Comment by Frenzie** [comment]
> Wait or close, and I have to choose wait several times till the file is opened and the progress bar in the upper left corner is going on perfectly but obviously slow..

It's an unfortunate but known limitation on the Android platform right now, even if it's one you'll seldom if ever experience in practice. 

> Even though a larger pdf file will open smoothly.

EPUBs are parsed all at once, while PDFs are rendered page by page. It's not really about the size of the EPUB file, but primarily about the number of nodes. Usually there's at least a correlation between filesize and number of nodes but that's not a given.

**Comment by Zeyadas** [comment]
Now I get it. Thank you.
