### ISSUE TITLE
Synchronize statistics between devices

### ISSUE THREAD

**Issue by rigogsilva** [koreader/koreader#7058]
As far as I know there is no way to synchronize the statistics if you are using two different devices. If there is a way, please let me know.

The progress sync is one of my favorite features. It would be nice to have something similar to that for statistics.

Click a button, and it would push the statistics and merge them with the statistics from the other devices.

Thoughts?

**Comment by johnbeard** [comment]
Something that maight work here would be better Dropbox (and/or other cloud storage backend) implementation. Koreader could leave a sync file in a Koreader-specific Dropbox "app folder".

For example, Moon+ reader leaves tiny files called `<BOOK_FILENAME>.po` (not poedit files!)  in `/Apps/Books/.Moon+/Cache`.

Content is something like this (haven't checked what the meaning is, a presume a timestamp and some position data):
```
1590486119266*9:3.8%
```

**Comment by dertasiu** [comment]
Also, I think it would be pretty cool if we could also sync highlighted text and annotations

**Comment by theboomr** [comment]
I would also really love to see the capability to sync reading statistics between devices, however it might be implemented. It's like the last feature I really want to see in koreader. I mostly read on my Kobo, but once in a while I use my phone if I'm out somewhere waiting unexpectedly and I don't have my Kobo with me. In those cases, I'm always bummed at the time spent on my phone not being tracked with the statistics on my Kobo, to the point that I kinda prefer to avoid reading at all if I don't have my Kobo, despite having progress synced to my phone.

I don't really have the time or knowledge to implement it myself, despite being a software engineer, but maybe someday I'll try to look into it...

**Comment by elain** [comment]
me too

**Comment by everdred** [comment]
Stats sync is in the [2022.11 release](https://github.com/koreader/koreader/releases/tag/v2022.11)!

**Comment by poire-z** [comment]
Implemented by #9709.
