### ISSUE TITLE
Small typo in a confirmation text

### ISSUE THREAD

**Issue by timacs** [koreader/koreader#7060]
When removing a bookmark, the following confirmation appears:
![koreader-typo](https://user-images.githubusercontent.com/2982328/103156260-fcc09980-47b7-11eb-9db7-2d8c3200a075.jpg)

So, the intended text "Do you want **to** remove this bookmark?" has missed the word "to".

It seems that the following line should be changed:
https://github.com/koreader/koreader/blob/5e3c554dd780a3f062e0b1bd8002eda3e1926e20/frontend/apps/reader/modules/readerbookmark.lua#L329

And thanks for the awesome project!

**Comment by Frenzie** [comment]
If you click the little edit icon in the top right of your link, you could also submit a PR with that change to have your name immortalized in the list of contributors. ;-)

**Comment by timacs** [comment]
I will do next time! :-)
Indeed, I didn't want to deal with the command line, git, a standalone text editor for such a small contribution, but you've reminded me of possibility to do it online.
