### ISSUE TITLE
PB Inkpad 3: Autoturn not working

### ISSUE THREAD

**Issue by thomasjfox** [koreader/koreader#7061]
* KOReader version: 2020.12
* Device: Pocketbook Inkpad 3 (PB740)

Autoturn (automatic page turn) doesn't seem to refresh the screen on Pocketbook devices, at least on the PB740, tested with the latest 6.x firmware.

If one sets the page turn timer to three seconds, nothing happens when the timer expires.

Once the timer is expired and a hardware button like "context menu" is pressed, the screen is refreshed with the next page. I suspect it's a suspend / screen refresh issue.

Interestingly, if f.e. the font gamma is changed, the "Font gamma set to 2.5" notification disappears automatically after some seconds. So automatic screen refresh via timers seems to work one way or another.

**Comment by NiLuJe** [comment]
Probably a bad interaction with the "active" AutoSuspend thingy on PB.

**Comment by rjd22** [comment]
@thomasjfox can you test this with the latest release.this seems to work for me with the latest version and firmware.

**Comment by hombretranquilo** [comment]
Works fine on my InkPad 3. You can close this PR, I think.

**Comment by thomasjfox** [comment]
> @thomasjfox can you test this with the latest release? This seems to work for me with the latest version and firmware.

I gave koreader 2022.02 a good test drive on an Inkpad 3 running firmware U740.6.5.765.

Unfortunately the issue is not fixed for me: Autoturn or the "Read timer" don't work at all. If I set a one minute read timer, it will pop up several minutes after it should have. I don't see a pattern yet.

One thing is fixed though: I never power down the device, I always put it in sleep mode.
Opening the book cover used to quickly show the screen and then koreader cleared it and
just showed a white screen. A co-worker of mine, also an avid koreader user, has the same issue on his Inkpad 3. This issue is certainly fixed for me since the switch to inkview in #8727: Now the book is displayed properly after opening the cover.

@hombretranquilo can you check and report your firmware version please?

The latest official firmware for Inkpad 3 is 6.5.1379 from December 2021,
mine is from October 2021. I'll give the firmware update a try,
I'll report back within four days (the next weekend).

**Comment by rjd22** [comment]
@thomasjfox thank you for testing. I will keep this open but please test the new firmware version. Autoturn works without issues for me but I have the InkPad color with the latest firmware.

**Comment by thomasjfox** [comment]
> @thomasjfox thank you for testing. I will keep this open but please test the new firmware version. Autoturn works without issues for me but I have the InkPad color with the latest firmware.

do you have automatic suspend enable in the firmware settings on your device to shut off after XX minutes?

@NiLuJe suggested in the first reply that it might be related to AutoSuspend.

I will test the latest firmware and will test if enable / disabling automatic suspend afte xx minutes makes a difference (I doubt it, but you'll never know).

**Comment by rjd22** [comment]
I will check it. After some more testing it seems to forget to auto turn when using longer timings like 90 seconds.

This will give me a baseline so I can check it out.

**Comment by hombretranquilo** [comment]
@thomasjfox, I tested with latest nighthly and auto-standby disabled, but I only tested at time intervals of 10, 20, 30, 40, 50 and 60 seconds. But I see that @rjd22 has discovered that the problem appears after 90 seconds and auto-standby enabled. I can not do more test now, but I will try tomorrow.

**Comment by thomasjfox** [comment]
The latest firmware 6.5.1379 also doesn't make a difference for me: Background jobs don't trigger.

This time I tested with the read timer: Set it to one minute. It didn't trigger, even after a page turn. I disabled it again after two minutes. Funnily the popup _does_ trigger a few minutes later even though the read timer is disabled already.

So it looks a bit if something stops the clock while the device saves battery between page turns?

**Comment by rjd22** [comment]
@thomasjfox thank you for testing. Does the following also fix the problem for you? If so I have a place to look:

> disabling "allow auto-standby" (settings -> device -> auto-standby settings) seems to fix the issue for me also with longer times

**Comment by pazos** [comment]
Closing in favor of #9493
