### ISSUE TITLE
Question: Best way to keep a custom koreader updated?

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7069]
I have customized a few files of my koreader install to improve the UI/UX. These are rather subjective changes and do not warrant a pull request. Thus I simply re-add them after each nightly install.

What I currently do:
1. wget latest version from ota.koreader.rocks
2. scp tar file from computer to device
3. ssh into device and untar file
4. mv custom files to replace default ones
5. restart koreader

I have written a shell script that does all of the above automatically. Does anyone know a better way of keeping koreader up to date without overwriting custom changes?

**Comment by NiLuJe** [comment]
diff/patch?

**Comment by pazos** [comment]
It might depend on the files you're going to replace. Do you have a list of files?

Or even better, a diff. While most subjective changes might not apply for other users, knowing which changes are done might help to figure out if we can refactor something, to make it easier for users to override settings.

**Comment by gbyl** [comment]
@NiLuJe ah of course. Totally forgot about that! Would that fit after the untar?

@pazos Here are some of the changes. I plan on further customizing the UI if I can figure out a good update script:

"Cover image" is more appropriate as all other plugins only capitalize the first letter:
https://github.com/koreader/koreader/blob/9db4e29bb196573f444aa2a8add80e2d1688a128/plugins/coverimage.koplugin/_meta.lua#L4

The coverimage plugin runs automatically on book opening and this duplicates load times on the RM 1. I comment out the line below and that way I decide when to run it:
https://github.com/koreader/koreader/blob/9db4e29bb196573f444aa2a8add80e2d1688a128/plugins/coverimage.koplugin/main.lua#L53

When coverimage is disabled, it automatically deletes the file generated, which crashes RM 1 since it needs a `poweroff.png` file. I comment out:
https://github.com/koreader/koreader/blob/9db4e29bb196573f444aa2a8add80e2d1688a128/plugins/coverimage.koplugin/main.lua#L249

UX-wise it is very confusing to have a checkbox for a menu item that is not itself a toggle, so I comment out:
https://github.com/koreader/koreader/blob/9db4e29bb196573f444aa2a8add80e2d1688a128/plugins/coverimage.koplugin/main.lua#L162-L164

In case you are wondering "Why do this when screensaver works just fine on the RM 1?" Battery life is terrible on suspend and it much more efficient to turn off the device. Coverimage lets us customize the poweroff screen.

**Comment by pazos** [comment]
Okay. I was thinking about other kind of changes, like menu order, font faces and sizes and so on. 

For little changes in the logic the diff/patch route works well enough. Just make sure your patch applies clearly on the new version.

**Comment by gbyl** [comment]
I suppose https://github.com/koreader/koreader/pull/7051 is also a good example. That screen refresh may bring some problems in the future and it does make turning off the device a couple of seconds slower. I am ok with the tradeoff, other users might not be. Maybe that is a change that I should have kept for myself since no one else has complained about the ghosting.

**Comment by gbyl** [comment]
@pazos Sounds good. Thanks for the input!

**Comment by Frenzie** [comment]
> "Cover image" is more appropriate as all other plugins only capitalize the first letter:

I'm fairly sure I left a review comment to that effect. In any case, please submit a PR. ;-)

**Comment by gbyl** [comment]
@Frenzie right, it's a bit of nitpicking, but it is nice to stay consistent.

**Comment by Frenzie** [comment]
>  I may submit a PR if I can bundle it with more consequential changes.

That's actually kind of the opposite of what I like to see in a PR, unless it's bundled thematically (e.g., "editorial nitpickings" or "cover image plugin improvements"). ^_^
