### ISSUE TITLE
Switchtokoreader is not working in nickle

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#7073]
Device:kobo clara hd
I updated nickle software. Now start menu (which contain nickle and koreader option) is not appearing. When i power on the device, it directly goes to nickle.
Also switchtokoreader, poweroff, exit_nicle are not working. Instead image appears when i press any one of these.
Device information are attached 
![IMG_20201228_222546](https://user-images.githubusercontent.com/59373108/103232242-d9b9f500-4931-11eb-9788-a6506c62c79c.jpg)

**Comment by pazos** [comment]
You need to install/update a launcher.

Use the [forum](https://www.mobileread.com/forums/forumdisplay.php?f=276) for support. If you have questions you're welcome to ask [in discussions](https://github.com/koreader/koreader/discussions), where we can label questions as answered and can be useful for other users. You can also ask on the gitter chat.
