### ISSUE TITLE
Remove Goodreads plugin

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#7075]
Since ~~GoodReads~~ Amazon wearing the flayed skin of Goodreads like a suit has deprecated the GoodReads API (no new key issued, <30 days keys revoked, API to be terminated), this plugin is on borrowed time.

At what point should it be put out of its misery?

C.f. https://goodereader.com/blog/digital-publishing/goodreads-disables-their-api-program

**Comment by Frenzie** [comment]
A little tough to say if it's still working for some people (but not me, due to the 30 day thing). But since it can just remain behind on existing installs we can fairly safely remove it from master right now.

**Comment by Frenzie** [comment]
Pinging @robert00s

**Comment by pazos** [comment]
> But since it can just remain behind on existing installs we can fairly safely remove it from master right now.

That wouldn't work for mac bundles, debian packages, the AppImage...

Maybe just mark it deprecated on its metadata and disable it by default on new installs?

![Sin nombre](https://user-images.githubusercontent.com/975883/103251456-00e7e500-4979-11eb-8201-cdfa6bc3249a.png)

**Comment by pazos** [comment]
Deprecated instead of removed. So users with valid keys can still use it.
