### ISSUE TITLE
Remarkable 2: Stuck on startup and can't connect SSH

### ISSUE THREAD

**Issue by tealdramatic** [koreader/koreader#7076]
* KOReader version: Latest for reMarkable 2 (29/12/2020)
* Device: Remarkable 2

#### Issue
The device is frozen on "Remarkable is starting" and it is not possible to connect to the device via SSH, message "Operation timed out".

#### Steps to reproduce
1. Install Koreader on new Remarkable 2 device
2. SSH into the device and activate launch by running the following commands:
`systemctl disable xochitl`
`systemctl enable koreader`
`reboot`

Is it possible to connect to the Remarkable without SSH?

Edit:
It is possible to connect with USB:
`ssh root@10.11.99.1`

**Comment by pazos** [comment]
I'm afraid you followed bad instructions for your RM2. The instructions on the Wiki are for RM1. Instructions for RM2 weren't updated yet (as there're no instructions upstream either)

You're better reverting these changes with

```
systemctl disable koreader
systemctl enable xochitl
systemctl start xochitl
```
and wait for proper instructions/support. If you want to test I would suggest to disable xochitl manually and start KOReader manually too, and see how that works. But keep in mind that this is not the best place to ask for help as nobody of us have a ReMarkable and expected support is about 0 :)

The [automatic launch](https://github.com/koreader/koreader/wiki/Installation-on-ReMarkable/c9501585bd4f345ad722a6f16ad672994fa6e790#automatic-launch) should also have a big red warning saying **please do that if you know what you're doing** or, at least, urge people to check if the program works for them first, and state clearly that this is going to replace the program launched at boot.

Pinging @gbyl, could you please take care of updating the wiki? Thank you!

**Comment by manuelsantana** [comment]
I had the same issue and followed these steps to solve it:

1. access RM2 via USB ssh (https://remarkablewiki.com/tech/ssh), 
2. reboot it from the terminal, 
3. enable xochitl again (systemctl start xochitl)
