### ISSUE TITLE
skip pages

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7080]
There are books that have the text in one language on one page and the same text in translation on the other.
What would you say if there was the option to skip one side, if we want to read the text in one language?

There could be the possibility to choose the number of pages we want to skip.

Thanks!

**Comment by NiLuJe** [comment]
You're assumong that we can magically devise which language stuff written in ;).

(Spoiler alert: we can't, not unless it's tagged properly).

**Comment by Frenzie** [comment]
I think they're just saying they want "page forward" to be "2 x page forward".

Which is actually already possible, except not for a standard back/forward tap or swipe. In Gesture Manager, choose one of the gestures, → reflowable or fixed layout documents → Go # pages.

![Screenshot_2020-12-29_23-17-46](https://user-images.githubusercontent.com/202757/103317685-37326c80-4a2c-11eb-88e6-e8e5083b95f7.png)

**Comment by ichnilatis-gr** [comment]
You're right, Frenzie.
Forgive me for my meaningless request.

**Comment by Frenzie** [comment]
No problem. You can always ask in the forum, GitHub discussions or on Gitter first.
