### ISSUE TITLE
Forgetting rotation / Calibre metadata search

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#7081]
Hi, I have not updated Koreader for 6 years, but since the akku of my Kobo Aura is dying I bought a new reader (Kobo Nia) and installed the newest version of Koreader.
First of all, there was a lot of improvement over the last 6 years, a lot of things are better than they were before. Good job!

But I found also a few issues:

- I prefer to read in landscape mode with dual pages and have set both as default. But whenever I restart Koreader the 90° rotation is gone
- "Find a book via calibre metadata" does not to seem to work anymore (I wrote this function initially, but I am sure my source code got replaced by something new.) I have connected Koreader to my .metadata.calibre file, but whenever I try to search anything nothing happens. The reader hangs, and I have to reboot. I tried it a few times, waiting about 30 minutes before I reset the reader since nothing happened on the display. To compare this, on my old Aura I had to wait the first time (for each new .metadata.calibre) using it for about 1 minute, then the results appeared, and for each new search it took only a few seconds. I have to admit I have a huge metadata file (175MB), and I am using an old version of Calibre (3.19). But if this file is not compatible with Koreader anymore I would not expect Koreader to hang but to send a "Not compatible" warning. Actually excactly this function is why I never updated, I was afraid this function would not work anymore.
- not sure if this is really a bug, but I find it strange that I cannot add a book from the history to the favorites.

Since I have not even started reading I might find some more...

Oh, and one question, how do I stop Koreader from writing in my book directory? I prefer if everthing is written in the "history" folder. On the old Koreader I could do that, but I can't remember how to force it to do that...

**Comment by pazos** [comment]
> "Find a book via calibre metadata" does not to seem to work anymore (I wrote this function initially, but I am sure my source code got replaced by something new.) 

I rewrote your code while improving the calibre wireless client, to make both intercompatible. It is basically loading the entire JSON file once (175MB in your case) and [generating a much smaller cache that will be used on next runs](https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/search.lua#L47-L75) (until you upload the list of books in .metadata.calibre and that file is newer than the previous generated cache).

IIRC the first time is cached while you scan your device for calibre libraries, so if the scan ends fine in a relative short amount of time (less than a couple of minutes) you'll end with two files in /mnt/onboard/.adds/koreader/cache, named "calibre-libraries.lua" and "calibre-books.lua". Please check that both were generated.

> I have connected Koreader to my .metadata.calibre file, but whenever I try to search anything nothing happens.

Not sure how you do that. There's a "manage calibre libraries" menu entry on the calibre plugin. It should be called automatically if there're no previous entries in the cache. Legacy GLOBALS were removed (they were hardcoded for the Kobo anyways).

> To compare this, on my old Aura I had to wait the first time (for each new .metadata.calibre) using it for about 1 minute, then the results appeared, and for each new search it took only a few seconds

On my tests the new parsing code was about 20x faster than the old one. I'm not a heavy user of calibre, so I had to download a bunch on PD books to do the test. Even there (w/ ~5000 books) I think most of the bulk of the JSON file is other kind of crap (ie: descriptions, user columns ...) so I'm not sure if I tested with a big - to - huge JSON file. 

>  I have to admit I have a huge metadata file (175MB), and I am using an old version of Calibre (3.19). But if this file is not compatible with Koreader anymore I would not expect Koreader to hang but to send a "Not compatible" warning. 

It should be compatible with any version of calibre. The problem, if it exists, has to do with OOM while loading the JSON file.

> Actually excactly this function is why I never updated, I was afraid this function would not work anymore.

It was changed in https://github.com/koreader/koreader/pull/6177. So any version below 2020.05 has the legacy code in it.

About the rest of questions: github added [discussions](https://github.com/koreader/koreader/discussions) recently. Q&A fit better there, because they can be labeled as anwsered and could help other people, unlike issues, that end closed and people normally open a new one instead of searching for old closed questions.

> not sure if this is really a bug, but I find it strange that I cannot add a book from the history to the favorites.

Feel free to open a feature request. The lack of a feature doesn't mean a bug, not always I mean :)

**Comment by WS64** [comment]
Hi Pazos,

I checked the cache, libraries is there (but pretty empty, only _return {   ["/mnt/onboard/.hidden"] = true,}_, books is not there. So the caching did not work at all.
And the connection, I meant "manage calibre libraries"!

Maybe you can check if you can get it to work with my metadata file? I have uploaded it here: https://we.tl/t-QSq8DXDpg7 (zipped still 62MB)

Like I said on my old Aura with the legacy code this loads in about 1 minute (for caching) and in seconds after that.

I'll check "discussions" later, thanks!

**Comment by pazos** [comment]
@WS64: to test I would need the .driveinfo.calibre too. But TBH I would rather like to see your `crash.log`. If it is an OOM or any other error it will be there.

**Comment by WS64** [comment]
driveinfo:
{"date_last_connected": "2020-10-08T15:48:39.440000+00:00", "device_store_uuid": "42eb69fb-13b6-4d25-a86b-b7241e3d14ee", "device_name": "Folder Device", "prefix": "D:/epub/", "last_library_uuid": "e5d6c21d-d337-4065-9ab5-adc33c83a030", "calibre_version": "3.19.0", "location_code": "main"}

Crash log is here: https://we.tl/t-WqvntgPrEg
But I can't see anything, maybe it never crashed but 30 minutes were not enough time waiting?
(there were other crashes too which I cannot see either, e.g. it seems I cannot get back from USB storage mode and have to reboot after a few minutes)

**Comment by NiLuJe** [comment]
> 
>     * I prefer to read in landscape mode with dual pages and have set both as default. But whenever I restart Koreader the 90° rotation is gone
> 

Gone from *where*? In which context?

**Comment by NiLuJe** [comment]
> it seems I cannot get back from USB storage mode (it stays at "Ending USBMS session...") and have to reboot after a few minutes)

That's either a seriously broken FAT32 partition, or... somethign went wrong and the device was actually shut down.

You'll have to follow the syslog live for more details [c.f., this issue](https://github.com/koreader/koreader/issues/6582#issuecomment-683297132) for more details.

**Comment by NiLuJe** [comment]
>     * not sure if this is really a bug, but I find it strange that I cannot add a book from the history to the favorites.

With history displayed in which mode (in case it matters, which it might not, I barely use the favs)?

**Comment by NiLuJe** [comment]
As far as Calibre is concerned, it should basically be a matter of seconds, unless something is going awry.

In which case, debug logs might help, as would a live shell to see if something's actually running or if you're just looking at paint dry ;).

**Comment by NiLuJe** [comment]
Siebar: Nia support is a minor miracle in and of itself, we've heard of... maybe 2 people with one since it came out, either here or on MR ;).

**Comment by Frenzie** [comment]
But all 2 or 3 people say it works great. ;-)

**Comment by pazos** [comment]
> As far as Calibre is concerned, it should basically be a matter of seconds, unless something is going awry.

I'm afraid the current approach works better with fast storage and "simple" json objects. 

Rapidjson-lua was choosed because it is the fastest loading json files and decoding/encoding them.

We use `json.load()` to read the whole file, decode it and store it as a lua table. Then we iterate the whole table just to keep a few fields and finally ditch the table. Not so efficient :/

The best approach for big json files (+1/2 of the virtual memory available) would be using a library that's able to traverse and partial decode json files, like https://github.com/Egor-Skriptunoff/json4lua. That, albeit being slower, would keep memory (and cpu) usage at minimum.

We still want rapidjson for other usages (like doing OTA changes from calibre). 

Do note that calibre libraries created or managed from KOReader (ie: used as wireless client inbox dir) are stripped down to the bare minimum, using `CalibreMetadata:cleanUnused()`, so reaching the same scenario from there would be very unusual.

**Comment by NiLuJe** [comment]
True, but, FWIW, I have somewhat non-trivial metadata dumps, and it is a matter of seconds nonetheless ;p.

**Comment by WS64** [comment]
> 
> 
> > ```
> > * I prefer to read in landscape mode with dual pages and have set both as default. But whenever I restart Koreader the 90° rotation is gone
> > ```
> 
> Gone from _where_? In which context?

E.g. changing language or DPI, a popup shows up "will take effect after restart". I go to Exit/Restart Koreader, and the 90° are gone.

**Comment by WS64** [comment]
> 
> 
> > it seems I cannot get back from USB storage mode (it stays at "Ending USBMS session...") and have to reboot after a few minutes)
> 
> That's either a seriously broken FAT32 partition, or... something went wrong and the device was actually shut down (you can tell the difference because the front light will turn off).

The light is off. Windows cannot find any errors on the card either.

Have to check how to get Putty connectd to my Nia.

**Comment by WS64** [comment]
> 
> 
> > ```
> > * not sure if this is really a bug, but I find it strange that I cannot add a book from the history to the favorites.
> > ```
> 
> With history displayed in which mode (in case it matters, which it might not, I barely use the favs)?

Not sure what you mean with mode. I use only Epubs, and i know only one way to reach History (Filemanager).

**Comment by WS64** [comment]
> Rapidjson-lua was choosed because it is the fastest loading json files and decoding/encoding them.

Btw, even 6 years ago I tried to use something like this, not sure if it was Rapidjson or another module. I did not use it but implemented my own code since it always crashed my Kobo Aura because the .metadata.calibre was too big.

**Comment by NiLuJe** [comment]
> > > ```
> > > * I prefer to read in landscape mode with dual pages and have set both as default. But whenever I restart Koreader the 90° rotation is gone
> > > ```
> > 
> > 
> > Gone from _where_? In which context?
> 
> E.g. changing language or DPI, a popup shows up "will take effect after restart". I go to Exit/Restart Koreader, and the 90° are gone.

Again, gone from *where* ^^. I ask because the FM now supports rotation, which means there are a couple extra settings to set whether or not the FM rotation takes precedence over book setting,s or vice-versa ;).

**Comment by pazos** [comment]
> > Rapidjson-lua was choosed because it is the fastest loading json files and decoding/encoding them.
> 
> Btw, even 6 years ago I tried to use something like this, not sure if it was Rapidjson or another module. I did not use it but implemented my own code since it always crashed my Kobo Aura because the .metadata.calibre was too big.

A bit of context of why it was changed in https://github.com/koreader/koreader/issues/6219.

**Comment by NiLuJe** [comment]
> > > it seems I cannot get back from USB storage mode (it stays at "Ending USBMS session...") and have to reboot after a few minutes)
> > 
> > 
> > That's either a seriously broken FAT32 partition, or... something went wrong and the device was actually shut down (you can tell the difference because the front light will turn off).
> 
> The light is off. Windows cannot find any errors on the card either.
> But, on Nickel the same behaviour. Might not be related to Koreader, but what else can it be?
> 
> I have Putty working. If you tell me what and how to check I will do! (warning, I'm not really a linux guy, as I have proved a few times here in the Koreader git!)
> I seem not to be able to start SSH and USB at the same time, Koreader tell me "Filesystem is busy! Offending processes: dropbear and sh)

You won't be able to use KOReader's SSH, hence the instructions I linked to earlier ;).

**Comment by NiLuJe** [comment]
> > > ```
> > > * not sure if this is really a bug, but I find it strange that I cannot add a book from the history to the favorites.
> > > ```
> > 
> > 
> > With history displayed in which mode (in case it matters, which it might not, I barely use the favs)?
> 
> Not sure what you mean with mode. I use only Epubs, and i know only one way to reach History (Filemanager).

I meant the actual view type for History: classic vs list vs mosaic ;).

I had time to check, the button is apparently not added in the History for... reasons.

It's probably trivial (-ish, because the way that menu is frankenstein'ed together is not always sane ^^), though.

**Comment by WS64** [comment]
> 
> 
> > > > ```
> > > > * I prefer to read in landscape mode with dual pages and have set both as default. But whenever I restart Koreader the 90° rotation is gone
> > > > ```
> > > 
> > > 
> > > Gone from _where_? In which context?
> > 
> > 
> > E.g. changing language or DPI, a popup shows up "will take effect after restart". I go to Exit/Restart Koreader, and the 90° are gone.
> 
> Again, gone from _where_ ^^. I ask because the FM now supports rotation, which means there are a couple extra settings to set whether or not the FM rotation takes precedence over book settings, or vice-versa ;).

I guess I don't understand the question. From where did I come? Or where is the rotation gone?
I meant the book is not rotated anymore.
It seeme the culprit is "Rotation/Keep current rotation across views".
I am not sure what exactly this means, but when I uncheck this setting the rotation is kept even when I restart koreader. Does not sound logical to me... I checked it because I wanted the rotated view everywhere, and this setting leads to losing the rotation after a restart!

**Comment by WS64** [comment]
Ok I followed these instructions:

1.     Install KoboStuff. => done. In case "install" means to copy the three folders over the existing ones...
2.     Assuming Windows, install PuTTY (choose the right installer for your setup at the top of the page).  =>done
3.     Launch KOReader, connect to Wi-Fi. => done
4.     Get your device's IP (Device > Networking > Network Info) => done
5.     Connect to it in PuTTY (just enter the IP in the IP field, and hit connect). => doesn't work (Network error. Connection refused). I need to start the SSH server to be able to connect. Since else I can't continue I did that
6.     Log in as user root, and then just hit Enter when a password is required. => done (actually I had to start the SSH server without password.)
7.     You should now be in front of a shell prompt, just enter logread -F, it'll print the current backlog, and then automatically update to track the current log. => done
8.     Run 'Start USB storage' with the device unplugged, and hit the power button to exit. => Doesn't work. The list of offending proccesses is now one longer, "logread"
9.     Post the relevant content of the output from logread (i.e., the tail end of it, it should be verbose enough for you to make sense of the general flow of it). => can't since 8 fails

Shuting down the SSH server and closing Wifi does not help either, I cannot start USB mass storage anymore. => rebooting the device (which takes 5 minutes, does not sound right to me either. 4.5 minutes of this only a white screen is seen and the led is blinking.) After reboot I can start USB storage again.

Oh, btw, I was wrong, the led stays ON when I leave the USB storage mode.

**Comment by WS64** [comment]
One more info. 
I opened the device again and put in the original SD card. And the USB sotrage issue is gone with that one. Also the long reboot is gone. I guess I start all over again with that one...

**Comment by NiLuJe** [comment]
> It seeme the culprit is "Rotation/Keep current rotation across views".

Yep, that's what I thought ;).

It makes the current view "sticky", no matter the context (e.g., your book is landscape, you go back to the FM -> FM is landscape). Which bypasses any and all stored book rotation, unless you open on a book. (The details are explained on a long-press, IIRC).

Since you're probably booting in the FM, and the default FM rota is still upright, it makes *everything* upright ;).

**Comment by NiLuJe** [comment]
>     1. Install KoboStuff. => done. In case "install" means to copy the three folders over the existing ones...
> 

Err, no, you should ultimately end up with a `KoboRoot.tgz` (your unarchiver might have trouble unpaccking a tar.xz in one step, so first step is uncompressing, you have a tar, then unpacking that, and in there you'll find the KoboRoot ;)).

Put that in the .kobo folder like a FW update and eject/reboot ;).

This explains why the subsequent steps failed ;).

The content looks like this:

```
drwxr-xr-x niluje/niluje     0 2020-12-16 03:45 KoboStuff/
-rw-r--r-- niluje/niluje     6 2020-12-16 03:43 KoboStuff/REVISION
-rw-r--r-- niluje/niluje 29833532 2020-12-16 03:43 KoboStuff/KoboRoot.tgz
drwxr-xr-x niluje/niluje        0 2020-05-18 22:32 KoboStuff/src/
drwxr-xr-x niluje/niluje        0 2020-05-18 22:32 KoboStuff/src/usr/
drwxr-xr-x niluje/niluje        0 2018-05-30 01:56 KoboStuff/src/usr/local/
drwxr-xr-x niluje/niluje        0 2020-05-18 22:21 KoboStuff/src/usr/local/stuff/
drwxr-xr-x niluje/niluje        0 2020-12-16 03:03 KoboStuff/src/usr/local/stuff/bin/
-rwxr-xr-x niluje/niluje     2082 2020-05-13 05:11 KoboStuff/src/usr/local/stuff/bin/stuff-daemons.sh
-rwxr-xr-x niluje/niluje     5907 2020-12-16 03:03 KoboStuff/src/usr/local/stuff/bin/usbnet-toggle.sh
-rwxr-xr-x niluje/niluje      661 2020-05-13 05:11 KoboStuff/src/usr/local/stuff/bin/stuff.sh
-rwxr-xr-x niluje/niluje     9249 2020-12-16 03:03 KoboStuff/src/usr/local/stuff/bin/update-kobostuff.sh
-rwxr-xr-x niluje/niluje     5163 2020-12-16 03:03 KoboStuff/src/usr/local/stuff/bin/python-setup.sh
drwxr-xr-x niluje/niluje        0 2020-06-13 22:58 KoboStuff/src/usr/local/stuff/lib/
-rwxr-xr-x niluje/niluje     3992 2020-06-13 22:58 KoboStuff/src/usr/local/stuff/lib/libotautils
drwxr-xr-x niluje/niluje        0 2018-05-30 01:56 KoboStuff/src/usr/local/niluje/
drwxr-xr-x niluje/niluje        0 2020-05-18 22:32 KoboStuff/src/usr/local/niluje/usbnet/
drwxr-xr-x niluje/niluje        0 2020-05-18 22:32 KoboStuff/src/usr/local/niluje/usbnet/etc/
-rw-r--r-- niluje/niluje      448 2020-05-11 04:06 KoboStuff/src/usr/local/niluje/usbnet/etc/inetd.conf
drwxr-xr-x niluje/niluje        0 2018-05-30 01:56 KoboStuff/src/etc/
drwxr-xr-x niluje/niluje        0 2018-05-30 01:56 KoboStuff/src/etc/udev/
drwxr-xr-x niluje/niluje        0 2018-05-30 01:56 KoboStuff/src/etc/udev/rules.d/
-rw-r--r-- niluje/niluje      179 2018-05-30 01:56 KoboStuff/src/etc/udev/rules.d/99-stuff.rules
-rw-r--r-- niluje/niluje       38 2020-12-16 03:43 KoboStuff/VERSION
drwxr-xr-x niluje/niluje        0 2020-12-16 03:03 KoboStuff/build/
-rwxr-xr-x niluje/niluje     8883 2020-12-16 03:03 KoboStuff/build/build-updates.sh
-rw-r--r-- niluje/niluje   184320 2020-12-16 03:03 KoboStuff/build/busybox-links.tar
-rw-r--r-- niluje/niluje    35872 2020-12-16 03:03 KoboStuff/README
drwxr-xr-x niluje/niluje        0 2020-12-16 03:45 KoboStuff/uninstall/
-rw-r--r-- niluje/niluje     2192 2020-12-16 03:45 KoboStuff/uninstall/KoboRoot.tgz
drwxr-xr-x niluje/niluje        0 2018-11-18 22:01 KoboStuff/uninstall/usr/
drwxr-xr-x niluje/niluje        0 2018-11-18 22:01 KoboStuff/uninstall/usr/local/
drwxr-xr-x niluje/niluje        0 2018-11-18 22:01 KoboStuff/uninstall/usr/local/stuff/
drwxr-xr-x niluje/niluje        0 2020-12-16 03:03 KoboStuff/uninstall/usr/local/stuff/bin/
-rwxr-xr-x niluje/niluje      539 2019-10-06 22:33 KoboStuff/uninstall/usr/local/stuff/bin/stuff.sh
-rwxr-xr-x niluje/niluje     5409 2020-12-16 03:03 KoboStuff/uninstall/usr/local/stuff/bin/self-destruct.sh
-rw-r--r-- niluje/niluje    47897 2020-12-16 03:45 KoboStuff/ChangeLog
```

So `KoboStuff/KoboRoot.tgz` is what you're after ;).
>     5. Connect to it in PuTTY (just enter the IP in the IP field, and hit connect). => doesn't work (Network error. Connection refused). I need to start the SSH server to be able to connect. Since else I can't continue I did that

In particular, you won't have to start anything (and in fact, don't, because that prevents USBMS, as you noticed).

>     8. Run 'Start USB storage' with the device unplugged, and hit the power button to exit. => Doesn't work. The list of offending proccesses is now one longer, "logread"
> 

I forgot that the message I linked to was this specific, so, in your case, you'll want do a full USBMS session (e.g., plug it, start usbms, mount it, eject it), since we want to know what happens at the end ;).

> 
> Rebooting the device (which takes 5 minutes, does not sound right to me either. 4.5 minutes of this only a white screen is seen and the led is blinking.)

That's.... indeed weird, the two parts of the process should essentially last roughly as long as each other (if anything, the earlier bit with a white screen and a flew flashes should be shorter than the progress dots).

But, again, no experience with a Nia, and it is a slightly different SoC, so, who knows.

> Oh, btw, I was wrong, the led stays ON when I leave the USB storage mode.

The power LED? Or the frontlight?

**Comment by NiLuJe** [comment]
Ah, just saw your latest post ;).

Yeah, that would jive rather well with my "the FAT32 partition is hella broken" theory: both the end of an USBMS session and the early boot process do a (couple of) fscks....

I have no experience with larger than 8GB cards, though, but even a 256GB one shouldn't take *that* long, if it's sane.

**Comment by WS64** [comment]
Ok, what I tried now...
Setting up Koreader as I want it on the original card.
Adding some (but not all) books, but also added metadata.calibre and so on (but did not ue it yet).
Then I made a copy to my 64GB card.  and enhanced it so the wholecard is usable.
This copy so far runs fine, no long booting, USB storage works and ends as expected.
Next was to start the calibre metadata search.
This time it did something: it crashed:

12/30/20-16:07:28 INFO  FM loaded plugin wallabag at plugins/wallabag.koplugin
12/30/20-16:07:40 WARN  invalid cache: cannot open ./cache/calibre-books.lua: No such file or directory
./luajit: not enough memory
!!!!
Uh oh, something went awry... (Crash n°1: 12/30/20 @ 16:14:49)
Running FW 4.22.15268 on Linux 4.1.15-00437-g3064755b04b9 (#11 SMP PREEMPT Tue Jul 7 08:35:57 CST 2020)
Attempting to restart KOReader . . .
!!!!

.adds\koreader\cache contains only the calibre-libraries.lua file (return {["/mnt/onboard/.hidden"] = true,}) but not calibre-books.lua

So something was really strange on the old installation, the new one is better, but this feature does not work anymore with big files.
Is there hope of a fix, or do I have to go back to an older version which had my code, or is there an easy way how I can change it locally so it uses my code here and not the new one? (Means that I again cannot update Koreader until I get a new reader in a few years...

**Comment by NiLuJe** [comment]
Okay, yeah, that sounds sensible given what @pazos said, and is probably the "expected" behavior on a ~512MB device with a > 128MB cache.

I don't recall quite how everything fits together, but even something as simple as mmaping the input file instead of reading it in a buffer might help, although that's, admittedly not very Lua-ish, and I have no idea how feasible that is right now ^^.

**Comment by pazos** [comment]
> So something was really strange on the old installation, the new one is better, but this feature does not work anymore with big files.
Is there hope of a fix, or do I have to go back to an older version which had my code, or is there an easy way how I can change it locally so it uses my code here and not the new one? (Means that I again cannot update Koreader until I get a new reader in a few years...

There's no easy way to answer that. It really depends on the time and effort you're willing to spend on the feature:

None?

> It was changed in #6177. So any version below 2020.05 has the legacy code in it.

A few time?

Port your old code, so instead of generating another text file it generates a table of books. You can still rely on manual parsing the json file but my suggestion would be:

> The best approach for big json files (+1/2 of the virtual memory available) would be using a library that's able to traverse and partial decode json files, like https://github.com/Egor-Skriptunoff/json4lua. That, albeit being slower on most files, would keep memory (and cpu) usage at minimum.

Of course you can still return back to your old code (wrapped as a plugin) and label it with other name, like "myCalibre.koplugin" and use that instead of the calibre.koplugin bundled with the program. That would allow you to keep KOReader updated.

I'm fine helping to integrate a new json solution, returning back to old code not so much :/

**Comment by NiLuJe** [comment]
Ehn, lua-rapidjson can't take a cdata as input, so, can't really pass it a mmap of the file without actual code changes in there first :/.

**Comment by pazos** [comment]
Tried parsing chunks of 4KB of @WS64 `.metadata.calibre` on my computer.

## printing everything:

```
real	0m43,514s
user	0m10,235s
sys	0m10,872s
```

## without printing

```
real	0m5,612s
user	0m5,555s
sys	0m0,048s
```

**Comment by WS64** [comment]
Unfortunately, the issue is back again.
And it is not Koreaders fault at all.
I now added all my books (around 50000). 
Booting takes 5 minutes, and USB storage does not end properly anymore.
I removed about half of the books, booting time went down to 3 minutes. USB still not working, although I just might have not waited long enough.
I removed all but 15000 books. Booting time down to 1 minute. And about the same time it takes now after ending the USB connection from my PC that Kobo reacts and comes back to Koreader.

So it might be that USB ending worked all the time and I only have not waited long enough.

It seems that something is scanning the complete filesystem during a startup and during an ending USB connection (which might be internallly another boot).

So what can I do now?

1. Dont load all the books to the reader. Actually I don't want to do that. Only advantage here would be that the metadata search would work again...
2. Stop Nickel (I guess) doing that. Can I go back to an older Kobo version? On my Aura this does not happen, and I also have an old Kobo Mini, where I updated the internal SD card to a 32GB one and filled it completely, no problems. On the Aura the situation might be a bit different since the books there are on the external SD card, not internal.
3. Would maybe KSM help here?
4. Live with that behaviour. I don't reboot often, and I don't change the books too often. I might have to think of not using USB storage mode but remove the SD card every time or do the uploads of new books via WinSCP/Putty.
5. Any other ideas?

**Comment by Frenzie** [comment]
If you installed it with @NiLuJe's script then you can put your books in `.books` (or whatever) to hide them from Nickel as you could always do on old firmware.

**Comment by WS64** [comment]
Frenzie, I did that.
And the Kobo software does not show these books.
But still something scans the hidden folder at startup, even if it does not add the books to the Kobo software.

**Comment by NiLuJe** [comment]
It's the fsck. Nothing you can do about it (except not using FAT32, which... has been done before, but I wouldn't really recommend, as it has some downsides and requires extensive trickery).

**Comment by pazos** [comment]
Last time I checked (2 years ago) nickel ~~worked fine~~ ignored a 4th (internal) partition and a 2nd (external) partition  formatted as ext4.

That makes possible to shrink the fat32 partition (3rd on internal sdcard, 1st on external) to the bare minimum (~500MB) and allocate the rest of the space as a big linux partition. The drawback is the lack of support for USBMS there. (Nickel will still export the fat32 partition)

**Comment by Frenzie** [comment]
If I'm not mistaken that same trick also worked 5 years ago. But various old tricks were broken over the last year or so. ^_^

**Comment by WS64** [comment]
That sounds interesting...
How do I mount such a 4th partitition, and will I be able to see it on Windows when I start USB storage? The first 2 I onl see when I insert the card to my computer but not when I start USB storage..

**Comment by Frenzie** [comment]
With some difficulty:
1. https://www.omgubuntu.co.uk/how-to-install-wsl2-on-windows-10
2. https://www.bleepingcomputer.com/news/microsoft/windows-10-now-lets-you-mount-linux-ext4-filesystems-in-wsl-2/

**Comment by WS64** [comment]
Actually I thought about a 4th Fat32 partition, not ext4. I tried ext4 a few times, but it never worked flawless and always led to side effects (like sudden blue screens or reboots).

**Comment by WS64** [comment]
I prepared my SD card with a 4th Fat32 partition. and added all books to that partition.
Booting is fast and also USB storage does end properly.
But in the mnt folder I do not see the new partition, can I mount it from Koreader?

Right now of course this volume can also not seen by Windows when USB sotrage is on, will this change once it is mounted?

**Comment by pazos** [comment]
Using a 4th fat32 partition is shooting yourself in the foot very badly.

**Comment by WS64** [comment]
But ext4 will not work since I can not add data from Windows. Unless I can use NTFS or exfat it has to be Fat32.
Hinestly I don't know whichtpes I can use here, and since the main partition is also fat32 I don't think the situation here is worse than before.
Still searching for a way to usethis new partiion with USBMS...

**Comment by pazos** [comment]
> But ext4 will not work since I can not add data from Windows

You have the same issue with a fat32 partition. You can't add data there. If you manage to export that partition via USBMS you no longer have this issue with both filesystems. You can also use whatever windows program which allows you to mount sshfs partitions as local drives and still use calibre + connect to folder to manage your books.

> since the main partition is also fat32 I don't think the situation here is worse than before.

Oh yeah. Very much worse :). Your system will fsck the original fat32 but doesn't know about your extra partition. That means you'll need to check for errors yourself. So still the same issue you had originally but in a later boot place (ie: not when the system boot but when you start KOReader and want to mount the new partition)

The new fat32 partition will inherit all the fragilities of the former fat32 partition: bug prone and slow to check

> Still searching for a way to use this new partition with USBMS

The main reason for @NiLuJe USBMS package is that KOReader runs from the same partition as the data that wants to export via USB. That didn't work fine. If you still keep KOReader on the 3rd partition, but your data is on 4th you don't have this issue anymore.

Anyways, the device is yours. Feel free to explore it :) But I would suggest against messing with system partitions if you're going to end with the same issues as you originally had.

**Comment by WS64** [comment]
If I cannot use USBMS than indeed it makes no sense to stick with fat32. Is it possible to use ext4 and do the datatransfer via WinSCP? If yes, is it possible to somehow transfer this fat32 partition to ext4 without losing the context?

**Comment by NiLuJe** [comment]
If you can live with the boot fscks, a slightly less awful idea is to simply bypass the USBMS fscks.

That's a terrible idea, because FAT32, but it's feasible.

https://github.com/koreader/KoboUSBMS/blob/6063bb63e73bea0a316aa454c0e4cf5857b63935/scripts/end-usbms.sh#L45-L51

**Comment by WS64** [comment]
I think I found another solution, not perfect, but it works.
First of all, I mount the new partition readonly.
That makes sure at least Koreader does not keep writing on it and messing it up (and even solves the question I asked in Discussion a few hours ago, "history folder". When the partition is readonly Koreader does exactl what I want!)
Downside is that now I cannot use a SSH connection to write new data on it since for that it is also readonly.

But guess what, Nickel does it this time! When I launch USB storage from Nickel it shows both volumes! And yes, I need to be careful here since it is fat32, but since this partition is a synchronized copy of a master folder on my harddrive there will not be too much loss if I damage it.

So that way I have
- short boot times
- working USB storage (Koreader only for the main partition, not my books, Nickel both)
- SSH for main read/write, books readonly
Good enough for me.

What I don't like is the one line I have to add to koreader.sh, ain't there a place somewhere where I can tell Koreader to start other things before Koreader itself starts? Something like "if exists myfile.sh execute myfile.sh" at the beginning?

**Comment by Frenzie** [comment]
Not inside KOReader, but you can just start a simple wrapper script instead (much like KSM does).

**Comment by WS64** [comment]
I close this one, too much other stuff. I have opened a new one for the rotation issue.

Thanks all!

**Comment by pazos** [comment]
@WS64: could you open another ticket for the big calibre metadata files issue?. I think it won't affect much people but it is cool to have it tracked.
