### ISSUE TITLE
SDL regression: Quit doesn't work

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#7091]
* KOReader version: 2020.12-70
* Device: macOS (Big Sur)

#### Issue

Quit doesn't work

#### Steps to reproduce

Start KOReader on MacOS
Click on the close button in the window bar, or hit Cmd-Q, or right-click on the Dock icon and select Quit

Nothing happens. I need to force-quit the application to stop it.

##### `crash.log` (if applicable)

I ran the application from terminal and tried quitting. Nothing shows up at the tail of the crash log when I do so.

**Comment by NiLuJe** [comment]
Does the in-KOReader Exit work?

**Comment by JasonInOttawa** [comment]
Yes it does

**Comment by Frenzie** [comment]
Not MacOS, but can confirm. It's a regression from https://github.com/koreader/koreader/pull/7037

**Comment by Frenzie** [comment]
Already fully fixed by https://github.com/koreader/koreader-base/pull/1277.

**Comment by JasonInOttawa** [comment]
Thank you. When I look at my branch

https://github.com/JasonInOttawa/

I see that I am behind in commits in the submodules (right word?) base, etc. I've been trying to sync them up but haven't had any luck. Is there a quick 'n' easy way to do that?

(Being able to use my keyboard to type into koreader is very nice!)

Thanks!

**Comment by Frenzie** [comment]
Base hasn't been bumped yet if that's what you mean, so you'll have to `cd base && git pull origin` or something like that. After which you can `git checkout -b bump-base && commit base -m "Bump base"`. :-P

**Comment by JasonInOttawa** [comment]
Thank you. When I look at koreader master, I see this

base @ 8614f99

and in my branch 

https://github.com/JasonInOttawa/koreader/tree/add-pages-remaining

I see

base @ 783c000

I seem to be behind in "bumped bases" too, since master is ahead.

I think I had this issue because I was missing the fix in base. Should I be trying to keep up to date with those changes, and if so would the commit you suggested get me there?

(I am keeping notes on all these conversations and hopefully I won't have to ask the same question more than three or four times .... :) )

**Comment by Frenzie** [comment]
No, the commit I suggested is in order to submit a PR. ^_^ Only the git pull/checkout/whatever part from within `base` is directly relevant to your concerns.
