### ISSUE TITLE
90° rotation is lost by restarting Koreader

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#7093]
* KOReader version: 2020-12
* Device: Kobo Nia

#### Issue
When I restart Koreader the 90° rotation inside books is not there anymore, books (at least the first book) will start in portrait mode instead of landscape mode

#### Steps to reproduce
Change rotation to 90° (and make it default)
Not sure if it is important, but I also have dual pages on (default).
I can't find right now where the setting is, but I also have set up Koreader to restart with opening the last document.
I also have "Screen/Rotation/Keep current rotation across views" checked.
When I now go to th menu "Exit/Restart Koreader" Koreader will open my last document in potrait mode instead of landscape mode.
By unchecking the "keep rotation" mark it sometimes (but not always) opens in the orrect rotation but nearly all popus are turned. Since I was fighting with long boot times I am not 100% sure anymore what exactly happens here, but I think the 90° rotation should stay even with the "keep rotation" checked.

**Comment by pazos** [comment]
Each document has its own setting that can override defaults.

To make sure you're reporting a bug please do the following:

1. Change rotation to 90° (and make it default)
2. Check Screen/Rotation/Keep current rotation across views
3. Open a new book that wasn't opened before.

Books opened before have their own settings. The same applies for font size, margins and any other rule. When you setup a new rule as a default it will be the default on newer documents but won't override the settings of each particular document.

**Comment by WS64** [comment]
But the book that was reopened by restarting was set to 90° and did not open with this setting.

**Comment by pazos** [comment]
You reported a bug and I asked if you can reproduce on book that was never opened. Other observations about the bug could help but don't answer the question: can you reproduce on a new book **once** you setup rotation on the FM as you wish?

**Comment by NiLuJe** [comment]
> I also have "Screen/Rotation/Keep current rotation across views" checked.

As I've mentioned before, there's no bug, it's doing what it's supposed to ;).

**Comment by WS64** [comment]
@pazos, it is only wrong for the first book. all new (and old books) are rotated.

@Nijule, I want "if you want to use everything in Landscape, keep it enabled, but set the default FM rotation to the same Landscape, too." 
That is exactly what I do. 
I have to admit, I did not know that FM has its own defaults.
I went there, set the FM also to 90° (long press, I can see the default star).
But it does not work.
I have set both FM and the books default to 90°. And "keep rotation" checked.
Then "restart koreader", and it opens with my book not turned.

**Comment by NiLuJe** [comment]
Okay, that's a bad interaction with "Star with: last file".

It works when booting in the FM, because it does an initial rotation; the Reader doesn't. (Also, even when starting from the FM, a long-press on the "Rotation" entry show a bogus rotation. The right one is highlighted, though).
