### ISSUE TITLE
Uncloseable window

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#7100]
* KOReader version: 202012
* Device: Kobo Nia (in landscape mode)

#### Issue
I stumbled into a situation where I had to reboot the Kobo to end Koreader (at least I did not know what else to do)
Got this by going to "Send2Ebook (Receiver)/Settings":
![kor](https://user-images.githubusercontent.com/7792441/103440039-af727b00-4c42-11eb-9f54-f6057ae5d311.jpg)

I don't see any way to close or submit this window. I guess there is a cancel/submit button below the keyboard, but I cannot reach it. I also tried to click on the borders in the hope the window would close, but no. Finally had to reboot the Kobo.
I am sure this is because of the landscape mode, but still there should be a way to avoid this! Maybe a "minimize keyboard" button...

**Comment by WS64** [comment]
Found another of those, advanced settings DCREADER_CONFIG_FONT_SIZES={...}
=> reboot

**Comment by NiLuJe** [comment]
Haven't checked in practice how it works, but from my foray into playing with the VirtualKeyboard + InputDialog, it looks like anything that shows both of those widgets eats "outside" taps, so the only exit lies in the InputDialog's Cancel button.

A "get me out of here" and/or "close the VK" button/gesture might indeed be helpful. (With the caveat that a "close the VK" button means we may not have a way to open it back up ;p).

**Comment by Frenzie** [comment]
@NiLuJe No, that works fine. You can test it on your PC with Esc (or Backspace if you're @poire-z).

Fwiw, the Opera/Otter/Vivaldi close tab gesture is down, right.

I think a simple cross extension in the top right probably makes the most sense. Think BeOS. (That was on the left, I suppose.)

**Comment by NiLuJe** [comment]
Would have to be on the keyboard, though, because we might always be sure that we can see the top (or any part of) the InputDialog ;).

**Comment by NiLuJe** [comment]
Possibly fold it into a long-press on enter? Unless there's already something?

**Comment by WS64** [comment]
Btw, I noticed that some other windows are movable by long pressing on an empty space (can't remember which ones though). If that would be possible here I could scroll to the buttons to click them...

**Comment by Frenzie** [comment]
> Would have to be on the keyboard, though, because we might always not be sure that we can see the top (or any part of) the InputDialog ;).

Yes, I mean the top right of the keyboard.

> some other windows are movable

While that might work on this specific dialog, it still requires the user coincidentally knowing about it.

**Comment by WS64** [comment]
An ESC would solve the issue of not having to reboot KOreader, but it still makes it impossible to use this dialog...

**Comment by Frenzie** [comment]
With reference to #7222, here's another one that might be affected on some devices (keyboard layout selection window).

![Screenshot_2021-01-31_20-55-22](https://user-images.githubusercontent.com/202757/106396206-c7d2e280-6406-11eb-89be-23c43b495381.png)

**Comment by NiLuJe** [comment]
That one should be a MovableContainer though, so there's a vague chance of escape, at least ;)

**Comment by Frenzie** [comment]
Also this particular one should probably do some kind of scrolling.

**Comment by hius07** [comment]
The same issue is in the Add cloud storage dialog in landscape.

Meanwhile, waiting for the button to hide the keyboard, we can apply a simple temporary workaround:
add after line 154 in

https://github.com/koreader/koreader/blob/03e9fac15617e63f99dab71fd1ac0d36acf2e148/frontend/ui/widget/inputtext.lua#L146-L155

the code
`elseif ges.direction == "east" then
 self:onCloseKeyboard()`

Swipe to the right in the input field will close the keyboard and show the `Cancel` button.

**Comment by poire-z** [comment]
Feels a bit hacky, and even not obvious to a newcomer getting stuck that there is this solution (does the keyboard re-appear when you focus on another text field?)

I guess this was somehow less an issue before #4084, where I had to disable things from being a MovableContainer, because of some issues.

Dunno what we can do better:
- have some the virtualkeyboard or the other widget handle swipe up/down to show/hide the keyboard (these are more obvious gestures I think) - when the text widget are small/multiple and we don't need to have them scrollable with swipe?
- have these multi text input show/hide keyboard on focus/unfocuse these text widget, so a tap on a non-test are would hide they keyboard?
- have virtualkeyboard have a little ear :) (so we don't have to waste a key) so we can lower/raise it, this little ear being visible in bottom left/right corner when hidden ?
- remake the thing be in a MovableContainer (or may be it was just my full textwidget that couldn't be movablecontainer'ed - a big widget like these ones might still work?

**Comment by hius07** [comment]
> does the keyboard re-appear when you focus on another text field?

Yes it does.

**Comment by hius07** [comment]
> show/hide keyboard on focus/unfocuse these text widget

This is very easy to use, I like it.

**Comment by hius07** [comment]
BTW, there is a not very nice feature: if there is a hint in the input field, we can tap it and get the cursor to move within the hint (tap the position or left arrow button).

I guess this can be fixed adding `if #self.charlist == 0` condition to the
https://github.com/koreader/koreader/blob/03e9fac15617e63f99dab71fd1ac0d36acf2e148/frontend/ui/widget/inputtext.lua#L119

**Comment by hius07** [comment]
> > does the keyboard re-appear when you focus on another text field?
> 
> Yes it does, another or the same field.

Sorry, appearance is unstable, cannot catch the regularity yet.

**Comment by hius07** [comment]
We still have an issue with uncloseable windows

![1](https://user-images.githubusercontent.com/62179190/119337563-a76db300-bc97-11eb-8919-64e2b9cc54fd.png)
--
As discussed above, the best way to fix it is to hide the keyboard to see the Close button.

Another reason to hide the keyboard might be e.g. fulltext search, when we need to see more text for reference.

![2](https://user-images.githubusercontent.com/62179190/119337815-ed2a7b80-bc97-11eb-8490-630689b45393.png)
--
These are quite rare cases, and we do not need this in Text editor (we have a special button in the navigation bar).
So there is no sense to have a special button on the keyboard to hide it.

As we can see in the first screenshot, it is rather hard to find a place out of the input boxes to unfocus the input.
So this way of hiding is not so comfortable.

Summarizing, I propose to hide the keyboard with the long-press on the `arrow down` button.

![3](https://user-images.githubusercontent.com/62179190/119338969-5232a100-bc99-11eb-96a6-1e354ee97660.png)
--
![4](https://user-images.githubusercontent.com/62179190/119338983-55c62800-bc99-11eb-9db1-4572130ebbde.png)

Some additions to the InputText will allow to re-show the keyboard with just a tap in the input box.

If the above is of interest, the code is ready.

**Comment by poire-z** [comment]
> Summarizing, I propose to hide the keyboard with the long-press on the arrow down button.

Why not (not so obvious to find out, but at least, that's a solution). Fine with me.

> As we can see in the first screenshot, it is rather hard to find a place out of the input boxes to unfocus the input.
So this way of hiding is not so comfortable.

Would be nice to have that too, as a more obvious alternative to arrow key down, even if uncomfortable.
(saying that in case you managed to get it working :)

**Comment by hius07** [comment]
> in case you managed to get it working

Not yet, maybe some day.

**Comment by hius07** [comment]
It'll be good to write **Virtual Keyboard** wiki article, including [Extended keyboard swipe to get new characters](https://github.com/koreader/koreader/wiki/Extended-keyboard---swipe-to-get-new-characters) and hidden features such as holding `Backspace` and `arrows`.
