### ISSUE TITLE
Kindle 4NT:  When pressing the power button to lock, nothing changes

### ISSUE THREAD

**Issue by Qwerty-Space** [koreader/koreader#7108]
* KOReader version:  2020.12
* Device: Kindle 4NT Black

#### Issue

When pressing the power button to lock the screen, nothing changes (visually), however buttons no longer do anything.  Pressing the power button will unlock the device again, and it continues as normal.

I am running KoReader with KUAL, with the non-firmware button.  I have a screensaver plugin installed, so it should show my screensaver.

**Comment by NiLuJe** [comment]
That's what running without the framework entails, nothing we can do about it.

**Comment by Qwerty-Space** [comment]
@NiLuJe so I just run the normal version then?

The wiki didn't make that particularly clear, as I thought my device would be considered an older one

**Comment by NiLuJe** [comment]
Well, whaddaya know, confirmed.

The K4 is a special snowflake in how screensavers are (not) handled, because we can't detect SO devices properly. But, still, the native screensavers *should* kick in. They apparently don't anymore (for... a while, since I have an old-ish version on mine and I could reproduce it).

Given the device, this is way, way, way down in my TODO list.

**Comment by Qwerty-Space** [comment]
I don't actually have the native screensavers I think.  I have a custom screensaver hack.  But I don't even have screensaver options in the gear icon

**Comment by NiLuJe** [comment]
That's what I meant by "native": you won't have KOReader screensavers support on a K4.

**Comment by NiLuJe** [comment]
Well, if you can find a way to programmatically detect an SO K4, be my guest ;).

**Comment by Qwerty-Space** [comment]
SO?

I'm not very well versed in Lua, but I can do a bit.  I wouldn't really know where to start

**Comment by NiLuJe** [comment]
Special Offers (e.g., the ones with ads).

**Comment by Qwerty-Space** [comment]
Unfortunately I don't have one of those.
Wouldn't it be better to ask for forgiveness rather than permission?  Assume it's not an SO Kindle, and try the screensaver.  If it doesn't work do the other thing, whatever that is

**Comment by NiLuJe** [comment]
Nope :).

**Comment by Qwerty-Space** [comment]
So what happens if you try to enable a screensaver on an SO Kindle?

**Comment by NiLuJe** [comment]
You don't.

**Comment by Qwerty-Space** [comment]
Ohhh I see
It's a legal issue

**Comment by NiLuJe** [comment]
The fact that it's actually broken on a standard device is why I re-opened this ;).

The SO aspect solely concerns the fact that you won't ever get *KOReader's* screensavers. You should still get the native Kindle ones, though. But *that* is currently broken.

**Comment by Qwerty-Space** [comment]
Leave it up to the user?
Leave it disabled by default, with a checkbox, or a setting only accessible by changing something in the files?  Or maybe have the answer buried in some obscure issue on gh somewhere.
Idk what you're willing to do.

But yes I guess personally I'm not fussed with the koreader screensavers, I'd just like it to execute the screensavers I have on the device ie the "native" ones.  But for now I could probably just exit koreader every time

Can you believe I did all this just so that I could read two books?

**Comment by NiLuJe** [comment]
"Lave it to the native system" is and has always been the sanest choice on Kindle.

It's just currently broken ^^.

**Comment by NiLuJe** [comment]
Note to self: the sigcont bits of the sigstop/sigcont dance with cvm probably unwittingly went poof when KOReader screensavers support was enabled on non-SO devices.

Which means this is probably a super-old bug.

**Comment by Qwerty-Space** [comment]
Awesome, ty.  Got it working now
