### ISSUE TITLE
FR: "first_open" for Reading statisitcs

### ISSUE THREAD

**Issue by christian-ho** [koreader/koreader#7117]
In the "book" table of the `statistics.sqlite3` db, it would be nice to have the reading start of each book as well.
So that there is not only a `last_open` but also `first_open` column.

![image](https://user-images.githubusercontent.com/57492542/103872356-9b110100-50ce-11eb-97d0-18c9ad5f2bab.png)

**Comment by NiLuJe** [comment]
That's unnecessary, just compute the first `start_time` for the book.

**Comment by NiLuJe** [comment]
I suck at SQL, but, e.g.,

`SELECT start_time FROM page_stat_data WHERE id_book = 2 LIMIT 1;` or `SELECT start_time FROM page_stat_data WHERE id_book = 2 ORDER BY start_time ASC LIMIT 1;`

**Comment by NiLuJe** [comment]
Fun fact, if you compare: 

`SELECT start_time FROM page_stat_data WHERE id_book = 2 ORDER BY start_time DESC LIMIT 1;` to `SELECT last_open FROM book WHERE id = 2;`, you'll realize that's it's actually the last *closed* timestamp ;p.

(Well, technically, the last time the stats were dumped to DB, which they do on close ;)).

**Comment by poire-z** [comment]
`first_open` could find its place into book (I wouldn't find that illogical, if there's already last_open :) - but that would need another DB/data migration, that we'd prefer to avoid - until it's needed for some more serious reason :)

Unrelated:
Regarding statistics, the rare times I use it, I'm sometimes embarassed by the differences in information between the current book stats vs. the one we get when getting book stats via the list or the calendar view. I now most often go see the stats for the book I'm reading via the calendar view.
I think I do that to get "Show days" - but there may be 1 or 2 others that are not in the current book stats kvpage (and possibly some that are in the current book stats, but not the other one).
(I'm too frightened of the stats plugin to go fix that myself :)

**Comment by NiLuJe** [comment]
I don't actually use the KVP, FWIW ;p.

**Comment by christian-ho** [comment]
Thanks for your comments.

The actual background of the idea was that one could also enter older books (read before KOReader) with start and end date into this table.
