### ISSUE TITLE
KOReader crashes with Wikipedia plugin

### ISSUE THREAD

**Issue by retrue** [koreader/koreader#7123]
* KOReader version: Last one as of today, 2021 January 9.
* Device: Kobo Mini

#### Issue
The Wikipedia plugin crashes just after stablishing connection to the WiFi.

#### Steps to reproduce
Turn off WiFi if it is on. Open a document, select a word in the document to launch dictionary. In the window there, tap on Wikipedia button below. Accept when it asks for permission to turn on WiFi. You will see the message "Obtaining IP address". Some seconds later, KOReader will crash.

#### Aditional information
KOReader doesn't crash in other situations when using Wikipedia. For example, after the crash described above KOReader is connected to the internet, so if you open the same document and tap over the same word and then over the Wikipedia button, the Wikipedia will work.
It won't crash in any case when you have already stablished a WiFi connection.
It won't crash if you are not connected to the Internet but you access to the Wikipedia through the Menu bar in Magnifier icon/Wikipedia lookout. It will ask you to connect to the Internet and then it will proceed without problems.
By the way, I checked too the plugin of translation in the same way: No WiFi, open document, select several words, push on translate, accept turning on WiFi, and it will work too, no crashes.

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/5791364/crash.log)

**Comment by poire-z** [comment]
OK, error of mine, with the 3s timer tweaked in #7114 (that then happens to be also checked in the wikipedia subclass, that I didn't think of) - I'll fix that.
```
01/09/21-16:32:45 WARN  error in wrapped function: ./ffi/util.lua:106: attempt to perform arithmetic on local 'from_timestamp' (a nil value)
stack traceback:
    ./ffi/util.lua:106: in function 'getDuration'
    frontend/apps/reader/modules/readerdictionary.lua:917: in function 'showDict'
    frontend/apps/reader/modules/readerwikipedia.lua:523: in function 'lookupWikipedia'
    frontend/apps/reader/modules/readerwikipedia.lua:383: in function <frontend/apps/reader/modules/readerwikipedia.lua:382>
    [C]: in function 'xpcall'
    frontend/ui/trapper.lua:48: in function <frontend/ui/trapper.lua:45>
```

In the log, this happened a few times and did not crash KOReader.

The times it crashes it, it's preceeded with:
`01/09/21-16:33:35 WARN  unwrapped dismissableRunInSubprocess(), falling back to blocking in-process run`
meaning that this thin did no run thru Trapper (which otherwise, I think, could have catch the exception and prevent a crash, even if it's not its main job). 
So, it's possible the wifi turn on / enable / delay / rexecute once connected... misses a bit of stuff in the scenario described by @retrue . I'll let that to @NiLuJe :/ because I'm not familiar with (and never use) these wifi facilities.

**Comment by poire-z** [comment]
The fix should just be (just adding `and self._lookup_start_ts  `in the middle of the highlighted line):
```diff
--- a/frontend/apps/reader/modules/readerdictionary.lua
+++ b/frontend/apps/reader/modules/readerdictionary.lua
@@ -914,7 +914,7 @@ function ReaderDictionary:showDict(word, results, box, link)
     self:dismissLookupInfo()
     if results and results[1] then
         UIManager:show(self.dict_window)
-        if not results.lookup_cancelled and ffiUtil.getDuration(self._lookup_start_ts) > self.quick_dismiss_before_delay then
+        if not results.lookup_cancelled and self._lookup_start_ts and ffiUtil.getDuration(self._lookup_start_ts) > self.quick_dismiss_before_delay then
             -- If the search took more than a few seconds to be done, discard
             -- queued and coming up events to avoid a voluntary dismissal
             -- (because the user felt the result would not come) to kill the
```
@retrue: as I can't test the wifi stuff, can you see if this solves the crash?

And if this fixes the crash, can you also check in that same scenario if the Wikipedia seach is interruptible (I think you can't interrupt it in that specific scenario, while it's possible in the others, right?)

**Comment by retrue** [comment]
@poire-z Yep, it did the trick. I know nothing about programation so it took me a while to figure out what I had to do  ^^;
That fixes the bug, I think.

**Comment by poire-z** [comment]
@retrue : can you also see about (keep the fix):
> can you also check in that same scenario if the Wikipedia seach is interruptible (I think you can't interrupt it in that specific scenario, while it's possible in the others, right?)

**Comment by NiLuJe** [comment]
The WiFi stuff itself is uncancellable, so even if this were, it might not be terribly useful ;).

**Comment by retrue** [comment]
@poire-z I don't know how to interrupt the Wikipedia search and after @NiLuJe comment I am even more lost.

**Comment by poire-z** [comment]
You can just tap anywhere on the screen while the "Searching Wikipedia NN for:..." message shows.

(But OK with @NiLuJe to not fix it :)

**Comment by retrue** [comment]
Okay, if I tap outside the messange "Searching Wikipedia EN for..." I get the message _Wikipedia request canceled_.
Dunno if that solves anything. Still lost  :p

**Comment by poire-z** [comment]
> I get the message Wikipedia request canceled.

Good, that's how it should work.
But in the specific scenario where you previously got a crash (you won't get a crash anymore now that you fixed it my with my change to the code), the interruption should not work (that's my theory, that I wish you to test :)

**Comment by retrue** [comment]
Difficult to test that because without the fix, I would get the crash before the message "Searching Wikipedia EN for...". No time to cancel anything.

**Comment by poire-z** [comment]
That's why I said to keep the fix :)
Before the fix: crash - After the fix: no crash, but non-interruptible.

**Comment by retrue** [comment]
Yep, without fix, after "Obtaining IP address" message it would crash. No time to interrupt search in Wikipedia.
With fix, after "Obtaining IP address" I would get directly the Wikipedia page with the searched word. No time to interrupt. I guess it is because the 3 seconds delay is removed with the fix in this specific situation.
But if the WiFi is On then it is possible to interrupt the Wikipedia search.
So, I suppose the dilemma is to fix the crash with that little change or search for a more complicated fix that allows to interrupt the Wikipedia search after that "Obtaining IP address" message but before showing the Wikipedia page.
I don't mind either way.

**Comment by poire-z** [comment]
OK, I'll just fix the crash.
