### ISSUE TITLE
PB626: screen rotation across views is not preserved after power off or restart device option is tapped

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#7125]
* KOReader version: v2020.12-91-g1c9c40f_2021-01-07
* Device: PB626 sw:U626.5.20.1157

#### Issue
Screen rotation across views is not preserved after power off or restart device option is tapped.

#### Steps to reproduce
1. Open Koreader
2. Exit Koreader with option Power off or Reboot the device
3. Open Koreader
4. Screen rotation is set to 0° even I have 90° clockwise defaulted - star icon

If I "exit" Koreader with option Restart Koreader or Exit, the screen rotation is preserved. Before I used v2020.12-30-gb78d9c1_2020-12-23 and this issue was not there.

Could you please check / fix it?
Thanks

**Comment by NiLuJe** [comment]
Yep, makes sense, it's only saved on full, sane Exits.

----

@yparitcher: At a quick glance, can't think of a prettier solution than just duplicating the save in UIManager's reboot_action/poweroff_action?

**Comment by yparitcher** [comment]
@NiLuJe 
Probably caused by this:
https://github.com/koreader/koreader/blob/47568ae9b48271ef010e58d1deb583e6aa5821aa/frontend/ui/uimanager.lua#L60-L62

Even if it is not saved, if not for this nothing should change it.

For some reason we change to portrait on PowerOff/Reboot.
from https://github.com/koreader/koreader/pull/2888
@pazos Is there a specific reason we reset to portrait or can i just delete that line?

**Comment by NiLuJe** [comment]
It certainly made sense on Kobo for... reasons (#4098, #5920).

c.f., the extended checks in https://github.com/koreader/koreader/blob/47568ae9b48271ef010e58d1deb583e6aa5821aa/frontend/device/generic/device.lua#L264-L328

**Comment by yparitcher** [comment]
I don't have a device to test but would something like this (copied from device.lua) help? (revert the orientation after displaying the SS)
```diff
diff --git a/frontend/ui/uimanager.lua b/frontend/ui/uimanager.lua
index 8851b902..3ed47d41 100644
--- a/frontend/ui/uimanager.lua
+++ b/frontend/ui/uimanager.lua
@@ -59,11 +59,22 @@ function UIManager:init()
     }
     self.poweroff_action = function()
         self._entered_poweroff_stage = true;
-        Screen:setRotationMode(Screen.ORIENTATION_PORTRAIT)
+        local orig_rotation_mode = Screen:getRotationMode()
+        -- Leave Portrait & Inverted Portrait alone, that works just fine.
+        if bit.band(self.orig_rotation_mode, 1) == 1 then
+            -- i.e., only switch to Portrait if we're currently in *any* Landscape orientation (odd number)
+            Screen:setRotationMode(Screen.ORIENTATION_PORTRAIT)
+        else
+            orig_rotation_mode = nil
+        end
         require("ui/screensaver"):show("poweroff", _("Powered off"))
         if Device:needsScreenRefreshAfterResume() then
             Screen:refreshFull()
         end
+        -- Cleanup after ourselves (after displaying the SS)
+        if orig_rotation_mode then
+            Screen:setRotationMode(orig_rotation_mode)
+        end
         UIManager:nextTick(function()
             Device:saveSettings()
             if Device:isKobo() then
@@ -75,11 +86,22 @@ function UIManager:init()
     end
     self.reboot_action = function()
         self._entered_poweroff_stage = true;
-        Screen:setRotationMode(Screen.ORIENTATION_PORTRAIT)
+        local orig_rotation_mode = Screen:getRotationMode()
+        -- Leave Portrait & Inverted Portrait alone, that works just fine.
+        if bit.band(self.orig_rotation_mode, 1) == 1 then
+            -- i.e., only switch to Portrait if we're currently in *any* Landscape orientation (odd number)
+            Screen:setRotationMode(Screen.ORIENTATION_PORTRAIT)
+        else
+            orig_rotation_mode = nil
+        end
         require("ui/screensaver"):show("reboot", _("Rebooting…"))
         if Device:needsScreenRefreshAfterResume() then
             Screen:refreshFull()
         end
+        -- Cleanup after ourselves (after displaying the SS)
+        if orig_rotation_mode then
+            Screen:setRotationMode(orig_rotation_mode)
+        end
         UIManager:nextTick(function()
             Device:saveSettings()
             if Device:isKobo() then
```

**Comment by NiLuJe** [comment]
Not necessarily, you have no guarantee that show has actually shown anything, just that it has queued the refresh.

I'd simply store the setting before the rota and call it a day?

**Comment by yparitcher** [comment]
That should work too, Can you test?

**Comment by NiLuJe** [comment]
I'll give it a try tomorrow, yeah (3AM here ;p).

**Comment by NiLuJe** [comment]
Well, that worked much better once I actually remembered to enable the rotation lock ;p.
