### ISSUE TITLE
reMarkable 2 touch input doesn't work with fingers

### ISSUE THREAD

**Issue by alistair23** [koreader/koreader#7131]
* KOReader version: 2020.12 (installed from Toltec)
* Device: reMarkable 2

#### Issue

The touch screen doesn't work with finger input, but does work great with stylus/pen input.

It does look like finger events occur, but the location seems to be incorrect as actions only happen occasionally and don't match what I'm touching.

#### Steps to reproduce

Try to use finger touch input on the reMarkable 2.

**Comment by pazos** [comment]
You'll need to report the issue to toltec as we cannot handle bug fixes downstream. Anyways, that doesn't seem an issue in any recent [nightly](http://build.koreader.rocks/download/nightly/)
