### ISSUE TITLE
FR: [Customize the size to change to the next frame]

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#7132]
I can see comics in landscape mode.
But when I press my finger to turn the page to the next frame, the image scrolls down and I notice that half of the next frame is in the first part of the page and half goes to the next page view.
I can adjust this in continuous mode by dragging the image down, but this is a slow and boring process and I need to do this on every page.
It would be interesting to customize a smaller size to scroll the page, so that I would be able to see the brown frame perfectly  with just a finger press

![frame1](https://user-images.githubusercontent.com/4573505/104134822-c0ba3680-536a-11eb-8fe0-464c69dc4db8.png)

after scroll the page I need to manually adjust the brow frame:

![frame2](https://user-images.githubusercontent.com/4573505/104134923-78e7df00-536b-11eb-9f19-008b6c5dec4e.png)

**Comment by poire-z** [comment]
> It would be interesting to customize a smaller size to scroll the page, so that I would be able to see the brown frame perfectly with just a finger press

Assuming your books are PDF/CBX (not EPUBs), #6885 was made for you:

![image](https://user-images.githubusercontent.com/4775231/99954648-65fd5900-2d83-11eb-9acb-94a119b4fb64.png)

By chosing Zoom to fit : columns or lines (3rd and 4th items), you can choose the number of columns/lines to split the page into. With the overlap settings, you can adjust that a bit so things look nice. With the direction setting, you decide how a tap should move you into that.
Takes a little time to discover and play with, but it was made to allow these kind of reading flow.
Some discussions and strategies in the fat #6885.

**Comment by hugleo** [comment]
updating my Koread right now

**Comment by hugleo** [comment]
You were right! #6885 was made for me ;-)
