### ISSUE TITLE
Crash when Sleep is activated

### ISSUE THREAD

**Issue by zelomel** [koreader/koreader#7136]
* KOReader version: v2020.12
* Device: reMarkable 1

#### Issue

When sleep mode is activated koreader craches after ~15 seconds

#### Steps to reproduce

Push the button to Sleep or  Sleep in menu and wait about 15 seconds

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/5803971/crash.log)

**Comment by Frenzie** [comment]
I think this may have already been fixed, but I can't remember the issue title otoh.
```
./luajit: frontend/device/remarkable/device.lua:104: attempt to index local 'self' (a nil value)
stack traceback:
	frontend/device/remarkable/device.lua:104: in function 'action'
	frontend/ui/uimanager.lua:882: in function '_checkTasks'
	frontend/ui/uimanager.lua:1219: in function 'handleInput'
	frontend/ui/uimanager.lua:1312: in function 'run'
	./reader.lua:300: in main chunk
	[C]: at 0x0001415d
!!!!
Uh oh, something went awry... (Crash n°1: 01/12/21 @ 19:02:17)
Running on Linux 4.9.84-zero-gravitas (#1 Wed Nov 4 10:21:32 UTC 2020)
Attempting to restart KOReader . . .
!!!!
```

**Comment by gbyl** [comment]
@zelomel Try updating to the latest version. I believe this was fixed by https://github.com/koreader/koreader/pull/7043

**Comment by zelomel** [comment]
Is 2020.12 the latest stable version ?

**Comment by Frenzie** [comment]
Indeed it is. You grab a nightly build from http://build.koreader.rocks/download/nightly/ or update to the development version through the program itself, or you can always wait a week for the next tagged release if you prefer.

**Comment by zelomel** [comment]
In seems to work fine with v2020.12.107.
