### ISSUE TITLE
CSS: 2-styles-at-once issue

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#714]
There is one CSS issue that is bothering me.
When you have two css styles, e.g.
`center {text-align:center;}
.italic {font-style:italic;}`
You can use them like `<p class="italic">` or `<p class="center">`, but neither `<p class="italic center">` nor `<p class="center italic">` works.
In this case both styles will get ignored, I guess Koreader is searching for one style called "italic center" (which does not exit of course).
Is that something that can be fixed?

**Comment by houqp** [comment]
Someone submitted a upstream patch to crengine:
http://sourceforge.net/p/crengine/crengine/merge-requests/13/

We should sync our crengine with upstream once that merge request is merged to upstream.

**Comment by Frenzie** [comment]
Fixed in https://github.com/koreader/crengine/pull/13.
