### ISSUE TITLE
FR: Customize progress bar to display only h1 chapter markers

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7141]
**Current**
Progress bar shows all chapter markers included in the ToC. For books with a complex structure this can appear too busy.

**Request**
It would be great to have an option to customize the depth of the chapter sampling, e.g. "Show chapter markers for h1 elements only"

**Comment by NiLuJe** [comment]
Long tap on the "Table of Content" menu entry does something similar. I even think the amount of stuff it checks is configurable... somehow, but I don't recall the details OTOH ^^.

**Comment by gbyl** [comment]
@NiLuJe That's an interesting trick. It checks for all h tags though and makes the overcrowding problem even worse.

**Comment by poire-z** [comment]
Long tap on the "Table of Content" generates a new table of content from real HTML H1 H2...H5. What's considered among these H1 ... H5 can be tweaked from Style tweaks > Misc > Alternative TOC hints - but this will affect only this 2nd kind of ToC, what ends up in the ToC, and so in the footer ticks.

But I think it could make sense to filter the TOC (ReaderToc:getTocTicks() ?) to pick what ends up from the TOC in the ticks (with a list similar to what we see in the style tweak toc hints menu).
That could also work the the 2nd ToC - as we may want H1 H3 H4 in the TOC, but only see H3 among the ticks.

(This post is _not_ an advertisement for the famous chinese video sharing social network :)

**Comment by NiLuJe** [comment]
> But I think it could make sense to filter the TOC (ReaderToc:getTocTicks() ?) to pick what ends up from the TOC in the ticks (with a list similar to what we see in the style tweak toc hints menu).
> That could also work the the 2nd ToC - as we may want H1 H3 H4 in the TOC, but only see H3 among the ticks.

You kinda lost me there ;).

The use-case I see for the alt ToC feature is, essentially, when the book is broken. So, you set-it up so that alt ToC does something sensible for this book, and voilà, you have a working ToC, and the progress tick match that.

I don't *quite* see why you'd want to introduce a mismatch between the ToC and the ticks?

**Comment by poire-z** [comment]
> The use-case I see for the alt ToC feature is, essentially, when the book is broken

That, or when it has no ToC at all, or only a few ones ("Cover", and "Content, I've seen that) - and when you're lucky it uses H1...H5 inside the book.

I've seen some books with a valid ToC that points to DIV or P, without any H1...H5: alt Toc will find nothing on this one.
(And you're doomed with books with a bad ToC that uses only DIV or P.)

> I don't quite see why you'd want to introduce a mismatch between the ToC and the ticks?
> (Especially one that'd be limited to the alt ToC case).

But I don't want to limit it to the alt ToC case :) Actually, you can currently only get it with an alt ToC with Toc Hints tweaks.
As for the why, considering you have a valid ToC (whether original or alt): imagine a ToC with 1000 entries (I don't think I've seen that in my books, but I've seen that in some test books posted here, like Brazilian law books, with entries like `14.3.2.12.3 Third degree assault on a family or household member` , `14.3.2.13.7  Second degree assault on a neighbour with a lawn mower` and each a 4 lines paragraph. One would get 1000 ticks and a quite uninteresting progress bar.

One may want to have all that in the ToC, but limit the ticks to show only for chapters 14.1, 14.2, 14.3... and have ticks at start of only long enough sections.

**Comment by gbyl** [comment]
@poire-z That's exactly right! That level of customization would be excellent to control the amount of progress bar marks.

**Comment by NiLuJe** [comment]
Eh, fair enough.

**Comment by poire-z** [comment]
Proof of existence of the issue :) and proposed solution:

<kbd>![crowded_toc](https://user-images.githubusercontent.com/24273478/106393563-23e23a80-63f8-11eb-8ae8-f221ac79f281.gif)</kbd>

Not sure about the wording and where to put that menu item...
The only non-menu code would be into ReaderToc:getTocTicksFlattened():
```diff
-    for _, v in ipairs(ticks) do
-        for depth, page in ipairs(v) do
-            if not hash[page] then
-                table.insert(ticks_flattened, page)
-                hash[page] = true
+    for depth, v in ipairs(ticks) do
+        if not self.toc_ticks_ignored_levels[depth] then
+            for _, page in ipairs(v) do
+                if not hash[page] then
+                    table.insert(ticks_flattened, page)
+                    hash[page] = true
+                end
             end
         end
     end
```
It would affect what uses getTocTicksFlattened() : footer & SkimTo progress bar, getNextChapter and so footer's chapter pages left and time to read (but not the current chapter title, so this would change even if we don't cross ticks).

**Comment by NiLuJe** [comment]
I'd probably make the UI match the code (i.e., tick levels you want to *hide*)?

And possibly at least mention *depth* level in the first > menu ;)

**Comment by poire-z** [comment]
I started with "Ignore TOC level for ticks", but it felt more explicite the other way around and seeing everything checked, inviting to uncheck what one doesn't want.

> And possibly at least mention depth level in the first > menu ;)

Just using the word "depth" in the menu text? `ToC depth levels shown in progress bars` ? Just to be precise, or is there another interpretation of "level" in the context of ToC ?

**Comment by NiLuJe** [comment]
> I started with "Ignore TOC level for ticks", but it felt more explicite the other way around and seeing everything checked, inviting to uncheck what one doesn't want.
> 

:+1:

> > And possibly at least mention depth level in the first > menu ;)
> 
> Just using the word "depth" in the menu text? `ToC depth levels shown in progress bars` ? Just to be precise, or is there another interpretation of "level" in the context of ToC ?

Yeah, just to be perfectly clear, at least in the initial drillable menu entry where we can spare the width.

**Comment by poire-z** [comment]
@Frenzie @yparitcher and others: any other ideas for the wording and where to put that new menu ?

![image](https://user-images.githubusercontent.com/24273478/106482286-97924f00-64ad-11eb-85cd-90ca02801e34.png)

It feels at place in that menu, as it's about TOC items, and what is shown in the SkimTo widget (but also in the footer, and CRE top status bar).
But in that menu, there are mostly actions, and this one would be the only setting. The wording is also a bit long and make that menu a bit ugly :)
We could add a `Settings>` sub-menu, but no other idea what else to put into so it's not just with a single setting...

This could also have a better wording, or tweaked if we find a better idea for the main one above:
![image](https://user-images.githubusercontent.com/24273478/106482317-a2e57a80-64ad-11eb-9ca8-1f8b95c13a21.png)

Another idea would be to have this use a progress bar of 4 squares (in the case above), to select only a subset of the combinations allowed bt the menu: 1, or 1+2, or 1+2+3, or all 1+2+3+4. (It doesn't really make much sense to allow 1+4 or 2+3 only...). But that's more complicated.
It could be launched from another button in the SkimTo widget, or add a 2nd progress bar in the SkimTo widget, but that's really more complicated...

**Comment by NiLuJe** [comment]
Putting it there wouldn't bother me, FWIW ;).

**Comment by hius07** [comment]
> We could add a `Settings>` sub-menu, but no other idea what else to put into so it's not just with a single setting...

There is a setting `Hide non-linear fragments` in that menu.
What about `Alternative TOC hints` from Style tweaks? It's a tweak, but it's about the ToC and its submenu is very similar.

**Comment by hius07** [comment]
Submenu: isn't it expected to see the total number of entries (ticks), i.e. 9-32-65-76?

**Comment by poire-z** [comment]
I abbreviated ToC because of habits, dunno if that's allowed in the menus, but it would then be longer !
![image](https://user-images.githubusercontent.com/24273478/106491136-d547a580-64b6-11eb-901e-5bfa8fefbbdf.png)

**Comment by poire-z** [comment]
> There is a setting Hide non-linear fragments in that menu.

Yes, but this one happens only if the document has non-linear, as a way to tell the user the document has this optional feature. Putting it in a sub-menu will have this less noticable, users will never see it (althought the number of users who care about non-linear stuff must be small).

> What about Alternative TOC hints from Style tweaks? It's a tweak, but it's about the ToC and its submenu is very similar.

Yep, but it's a style tweak, the menu is dynamically generated from the style tweak file, not easy to move some of them elsewhere.

But we indeed have the undocumented thing that when you long-press `Table of contents`, you swap to the Alternative table of contents ! This could be moved in a Settings sub-menu :)
Although "settings" does not sound good... `Table of contents options` ?

> Submenu: isn't it expected to see the total number of entries (ticks), i.e. 9-32-65-76?

You don't see them ?
![image](https://user-images.githubusercontent.com/24273478/106482317-a2e57a80-64ad-11eb-9ca8-1f8b95c13a21.png)

Or do you mean something should show somewhere the total/sum of the ones enabled?

**Comment by hius07** [comment]
> the total/sum of the ones enabled?

Yes, to imagine quickly how they all fit in the bar.
I assume that selecting 'Show tick for level 2' we'll see 32 ticks, right?

**Comment by NiLuJe** [comment]
> But we indeed have the undocumented thing that when you long-press `Table of contents`, you swap to the Alternative table of contents ! This could be moved in a Settings sub-menu :)
> Although "settings" does not sound good... `Table of contents options` ?
> 

+:1:

**Comment by NiLuJe** [comment]
> > the total/sum of the ones enabled?
> 
> Yes, to imagine quickly how they all fit in the bar.
> I assume that selecting 'Show tick for level 2' we'll see 32 ticks, right?

I kinda prefer the current approach of each level showing *that level's* tick count.

I'm not against showing a total somewhere, but not necessarily there ;).

**Comment by poire-z** [comment]
> I assume that selecting 'Show tick for level 2' we'll see 32 ticks, right?

Right.
Bit crowded to add the same total to all the items - or cumulative total with only the upper ones, hard to explain :)
I guess most people who have the progress bar in the footer, will be fine as it updates in real-time when you check/uncheck.
Of course, the progress bar of the skimto widget shown as another menu item would be nice, but I'll avoid the headache of coding that :)

**Comment by Frenzie** [comment]
Progress bar ToC depth?

**Comment by hius07** [comment]
> Yes, but this one happens only if the document has non-linear, as a way to tell the user the document has this optional feature

Let me ask a general question.
What are the reasons to hide a non-applicable menu or settings item instead of just greying it?
Like this setting for non-linear docs or zoom settings in the bottom menu, for example?
Isn't it more comfortable for a user to have fixed accustomed layouts showing all the options (understanding why some of them are inaccessible in some cases)?

**Comment by poire-z** [comment]
My answer to this question (specific, but it is valid also for the `Reference pages>` submenu you might have hardly never seen, unlike Non-linear flows which is available with most FB2 books) from https://github.com/koreader/koreader/pull/6847#issuecomment-721944172 : 
> I think you need a way to show the user that this book has non-linear flows or not. No need for him to toggle it and then try to see if something has changed like total nb of pages to notice/guess that if not, there's no linear flow. So, the presence of this menu is a good indicator the document has them, and that there's a feature that may makes the reading experience better. Seeing that menu always and toggling it and seeing it has no effect won't advertize how nice that feature can be.
(Having it grey/not enabled when the book does not have non-linear stuff can be a bit confusing. Our other menu items are grey when they depend on other features/settings - so a user, seeing it grey, might want to try tweaking other stuff to make it non-grey/enabled.)

**Comment by poire-z** [comment]
> But we indeed have the undocumented thing that when you long-press Table of contents, you swap to the Alternative table of contents ! This could be moved in a Settings sub-menu :)

Except that this is only available on CRE documents, not on PDF. So, on PDF, there would be "Toc depth" as a single setting/option...
I guess that if I don't want to be saddened by this little orphan all alone in its submenu, I might have to add Font size options for TOC and Bookmarks (current, TOC, Bookmarks, FileBrowser classic view, and probably a few others, use the one set on the FileManager's `Items>` submenu...).

**Comment by NiLuJe** [comment]
> > But we indeed have the undocumented thing that when you long-press Table of contents, you swap to the Alternative table of contents ! This could be moved in a Settings sub-menu :)
> 
> Except that this is only available on CRE documents, not on PDF. So, on PDF, there would be "Toc depth" as a single setting/option...
> I guess that if I don't want to be saddened by this little orphan all alone in its submenu, I might have to add Font size options for TOC and Bookmarks (current, TOC, Bookmarks, FileBrowser classic view, and probably a few others, use the one set on the FileManager's `Items>` submenu...).

That wouldn't be a bad thing either, because he interaction is indeed slightly puzzling if you're not familiar with the code ^^.

**Comment by poire-z** [comment]
> What are the reasons to hide a non-applicable menu or settings item instead of just greying it?

Furthermore, and especially for the first panel of the top menu (and part of the reason I was a bit hesitant to add something to it): it's the main and only way to access ToC, Bookmarks, Skim. Back, on non-touch devices. So, for such devices, I'd rather not add too much noise in that menu, and keep it short for ease of action.

**Comment by hius07** [comment]
> I might have to add Font size options for TOC and Bookmarks

Nice idea

**Comment by Frenzie** [comment]
> ("Options", "ToC and bookmarks options", "Settings" ... ?)

We're generally using settings, so I'd say settings.

> ToC entries

Sounds okay to me.

**Comment by hius07** [comment]
> some languages may not have that.

There's no abbreviation for Содержание in Russian.

**Comment by hius07** [comment]
'Items' is used for Files and History, let it be unified.

**Comment by poire-z** [comment]
> There's no abbreviation for Содержание in Russian.

Out of curiosity, how (long) will you translate `Содержание entries per page` and `Show tick for ToC depth 2 (23 entries)`.

> 'Items' is used for Files and History, let it be unified.

Given that these will now only be used for file and directories, we could as well rename it to `File browser settings > Files/directories per page`.

**Comment by hius07** [comment]
`ToC entries per page`
`Пунктов содержания на странице`

`Show tick for ToC depth 2 (23 entries)`
`Показывать засечки для глубины содержания 2 (23 пункта)`

**Comment by Frenzie** [comment]
What was the context for the other two?

**Comment by hius07** [comment]
In the filebrowser menu we have both `Items per page` and `Files per page`
And `Auto-remove deleted or purged items from history`

**Comment by yparitcher** [comment]
maybe remove the separator between `Bookmarks` and options/setting` to more clearly show what they are for

**Comment by poire-z** [comment]
`Показывать метки для глубины содержания 2 (23 пункта)`

A bit long, will probaby be truncated before the valuable numbers :)
 May be we can do with:
`Progress bars ToC depth (76 ticks) > [x] 23 entries at depth 2`
even if they won't align nicely.

**Comment by poire-z** [comment]
> maybe remove the separator between Bookmarks and options/setting` to more clearly show what they are for

But I'd like to also put `Bookmark items per page` and `Bookmark item font size` in there.

**Comment by Frenzie** [comment]
Being more specific when we can, like `files per page`, is good. 

I'm not necessarily convinced that we should be consistent with entries and items in the suggested sense.

Bookmark entries → :+1: 
File entries → :-1: (those would be entries inside a file)

Put another way, `Bookmark entries` and `ToC entries` are good, but `Entries per page` potentially less so. At the same time `Bookmark items` sounds a bit programmerish to me.

But fine, let's stick with `items`.

**Comment by yparitcher** [comment]
> > maybe remove the separator between Bookmarks and options/setting` to more clearly show what they are for
> 
> But I'd like to also put `Bookmark items per page` and `Bookmark item font size` in there.
> 
> Or it would have to be
> 
> ```
> Table of contents
> Table of contents settings >
> ----
> Bookmarks
> Bookmarkrs settings >
> ```
> 
> Dunno. (Though we could also want to put `[ ] hide non-linear flows` in there - now with 2 of them, it's less obvious :)

i meant
```
Table of contents
Bookmarks
settings
---
Go To
```
toc/bookmarks/setting are one group.

**Comment by poire-z** [comment]
Updated proposal for the menu:

On a PDF | on an EPUB (which has non-linear stuff and reference pages):
<kbd>![image](https://user-images.githubusercontent.com/24273478/106894351-22ae5780-66ef-11eb-89e5-dfade35d0cad.png)</kbd> <kbd>![image](https://user-images.githubusercontent.com/24273478/106894389-33f76400-66ef-11eb-81d7-d245cf204c7a.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/106894918-de6f8700-66ef-11eb-9011-782bdc1b5dac.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/106895117-1f679b80-66f0-11eb-97c5-1f92ee76e20d.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/106894940-e6c7c200-66ef-11eb-8de9-79765adbe266.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/106895178-31493e80-66f0-11eb-91ec-8e5e993f4a59.png)</kbd>

I wonder if `[ ] Hide non-linear fragments` (which is @Jellby's baby) should be moved into this new `Settings>` sub-menu.
I personally hardly ever go into this panel so I'm not bothered. But, among my books, it happens that 90% of them don't have non-linear fragments - and that among the 10% that do, 90% of these only have the cover as a single non-linear fragment.
I guess people who are really interested in hiding them (@Jellby , @hius07 and other FB2 readers: do you use it to hide footnotes?) would have set it as enabled by default, and they can notice a book has it with the double slash `12 // 345` in the footer page/total, so may be they don't need to also see it that straight in the menu?
But I don't mind either way.
Although it has nothing to do with ToC and Bookmarks :) So may be forget that :/

**Comment by poire-z** [comment]
About the File browser's `Items>` sub-menu, we might as well rename it to:
`Classic file browser settings>` - and may be move some of the more generic settings from the Cover browser plugin's `Display mode> Other settings>` (which I just discovered are not accessible if the Coverbrowser plugins is disabled...).
(Not talking about moving Coverbrowser plugin stuff into core, which is a more complicated task I'd like to avoid :)

**Comment by hius07** [comment]
Wow, I like it very much!

The non-linear setting seems to be Okay as on the screenshots, with the default to be off.
Moving it into Settings is Okay as well :)

**Comment by NiLuJe** [comment]
> 
> ![image](https://user-images.githubusercontent.com/24273478/106895117-1f679b80-66f0-11eb-97c5-1f92ee76e20d.png)
>
 
```
The progress bar in the footer & skimmer can get very crowded when the table of contents is complex. This allows choosing exactly which depth levels will generate a tick mark.
```


>
> ![image](https://user-images.githubusercontent.com/24273478/106895178-31493e80-66f0-11eb-91ec-8e5e993f4a59.png)
> 

Nit: Inconsistency between `TOC` and `ToC` ;).

**Comment by poire-z** [comment]
> Inconsistency between TOC and ToC ;).

Yep, saw that: Which variation should we adopt globally?

> skimmer 

Is that really a word ? and one we can use there? instead of Skim widget ?

**Comment by gbyl** [comment]
We can simplify a bit to increase clarity:

`The progress bar can get too busy when the table of contents is complex. This allows you to restrict the number of tick marks generated.`

**Comment by NiLuJe** [comment]
> Is that really a word ? and one we can use there? instead of Skim widget ?

It is, but it's not necessarily the right one ^^.
The closest actually-used-in-UI-context one would probably be `scrubber`? (That's usually a glorified horizontal scroll-bar, which kinda works here?).

**Comment by NiLuJe** [comment]
> We can simplify a bit to increase clarity:
> 
> `The progress bar can get too busy when the table of contents is complex. This allows you to restrict the number of tick marks generated.`

I like the second sentence!
Not a fan of the first though (crowded > too busy).

**Comment by poire-z** [comment]
I'd still like to mention _which_ progress bars.
_The progress bars (in the footer and when skimming document) can.._ ? instead of giving it a name :)
Or _the skim dialog_ if we don't want to mention widget?

**Comment by gbyl** [comment]
Maybe something like:

`Progress bars can become overcrowded when the table of contents is complex. This allows you to restrict the number of tick marks generated.`

**Comment by NiLuJe** [comment]
> I'd still like to mention _which_ progress bars.
> _The progress bars (in the footer and when skimming document) can.._ ? instead of giving it a name :)

Works for me ;).

> Or _the skim dialog_ if we don't want to mention widget?

Yep, :+1:

**Comment by NiLuJe** [comment]
> Maybe something like:
> 
> `Progress bars can become overcrowded when the table of contents is complex. This allows you to restrict the number of tick marks generated.`

Too much ;p.

It may just be me, but using `overcrowded` for inanimate objects feels weird (unlike too crowded).

**Comment by poire-z** [comment]
About to go with:
_The progress bars in the footer and the skim dialog can get very crowded when the table of contents is complex. This allows you to restrict the number of tick marks generated._

(Grammar police : not too many _the_ ? _The_.. in _the_.. and _the_.. when _the_...? :)

**Comment by Frenzie** [comment]
I'd remove at least a couple of words.

The progress bars in the footer and the skim dialog can become cramped when the table of contents is complex. This allows you to restrict the number of tick marks.

**Comment by poire-z** [comment]
Proposed as #7238. Please continue the rewording suggestion in there.
I'm sure we can do better than _Reduce bookmark font size to show more text_ :)

**Comment by poire-z** [comment]
(Continuing a related discussion in here.)

Regarding https://github.com/koreader/koreader/issues/7141#issuecomment-773291918 : 
> About the File browser's `Items>` sub-menu, we might as well rename it to:
`Classic file browser settings>` - and may be move some of the more generic settings from the Cover browser plugin's `Display mode> Other settings>` (which I just discovered are not accessible if the Coverbrowser plugins is disabled...).
(Not talking about moving Coverbrowser plugin stuff into core, which is a more complicated task I'd like to avoid :)

If we were to do that, what should still fit in the first level menu, and what in the `Settings>` submenu:
<kbd>![image](https://user-images.githubusercontent.com/24273478/107155661-e7738900-6979-11eb-9037-c0403b2582c0.png)</kbd>

<kbd>![image](https://user-images.githubusercontent.com/24273478/107155670-f35f4b00-6979-11eb-9a32-5ba2652ccda4.png)</kbd>

Some of these settings only apply to Filemanager, some to any FileChooser/Picker, and some to everything Menu (OPDS browser, File searcher, Calibre browser and search results...)
"Items" was generic enough, but a big vague :)
Thoughts/ideas?

**Comment by hius07** [comment]
Very nice.
'File/result' seems a little bit complicated. I would accept 'Item'.
`Other settings` needs to be clarified, maybe, `Mosaic and Detailed list settings`.

**Comment by poire-z** [comment]
Or just `Cover browser settings >` ?
Should Show hidden/unsupported stay at top level, with sorting?

**Comment by hius07** [comment]
> Or just `Cover browser settings >` ?

OK



> Should Show hidden/unsupported stay at top level, with sorting?

I believe might go to `Settings` (hide from inexperienced users)

**Comment by hius07** [comment]
The numberpicker for Font size has extended heading 'Maximum font size...' which doesn't fit and is truncated. My opinion is that the heading should repeat the menu item name. The comment may be added below in the window, if required.

Generally speaking, being a maniac of unification, I'd set some standards for ui elements, e.g.for numberpickers:
- the heading is equal to the menu or setting name
- ok button is named 'Apply'
Almost all numberpickers from the bottom menu comply with that, but not so for Gear menu.

**Comment by Frenzie** [comment]
Those standards already exist. OK should seldom be used.

**Comment by Frenzie** [comment]
Partially disagree on the heading name thing.

**Comment by Frenzie** [comment]
http://koreader.rocks/doc/modules/ui.widget.confirmbox.html

**Comment by hius07** [comment]
> http://koreader.rocks/doc/modules/ui.widget.confirmbox.html

Thank you

**Comment by poire-z** [comment]
Updated screenshots in #7259 (kept "Items" instead of "Files/results", changed a bit the ordering of menu items).
