### ISSUE TITLE
Koreader for Android captures almost black screenshot when in Color Mode

### ISSUE THREAD

**Issue by Santirulo** [koreader/koreader#7146]
* KOReader version:2020.12
* Device:Xiaomi Mi 10 Lite 5G

#### Issue
The screenshots taken are completely black or they just show the status and progress bar at the bottom when in Color mode. I uploaded two images showing this behavior.

#### Steps to reproduce
Check setting in "Screen" - "Color rendering" and capture any page of the open ebook to get _black_ images. Uncheck the "Color rendering" setting and the screenshots are fine.

##### `crash.log` (if applicable)
I don't have a crash.log file.

![Reader_2021-01-14_220845](https://user-images.githubusercontent.com/47663608/104717817-34bd5b80-572a-11eb-9a7d-f7419d5b9fa3.png)
![Reader_2021-01-14_222539](https://user-images.githubusercontent.com/47663608/104717818-3555f200-572a-11eb-8666-16809231a5bd.png)

**Comment by Frenzie** [comment]
I think this is already fixed and a duplicate, but I don't have time to double check right now.

**Comment by NiLuJe** [comment]
Yep, fixed in #7042
