### ISSUE TITLE
Exporting highlights to Joplin fails

### ISSUE THREAD

**Issue by georgelemental** [koreader/koreader#7148]
* KOReader version: v2020.12
* Device: Kobo Aura H20 Edition 2 v2

#### Issue
Using the Evernote plugin to export notes to Joplin fails with `Multiple errors occurred while trying to export notes from the book: <first word of book filename>`
A KOReader notebook is created in Joplin, but it is empty.

#### Steps to reproduce
Highlight text in a book, use Evernote plugin to try to export book highlights to Joplin
##### `crash.log` (if applicable)
A verbose debug log contains this line:
`DEBUG Error while exporting book <first word of book filename> plugins/evernote.koplugin/JoplinClient.lua:69: attempt to index local 'note' (a boolean value)`

**Comment by Frenzie** [comment]
Pinging @mustafa-001

**Comment by gerroon** [comment]
I am able to export to Joplin  from Linux KOReader and my Boox device.
