### ISSUE TITLE
Remove from history (multiple selection). 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7152]
Sometimes I open several (files/books), (pdf or epub) just for browsing not for reading the whole book or maybe to choose a book to read. 
The problem is I have to remove the books from the history page separately one each time, can you add a (multiple select) function?

Using an android tablet (SM-T285) with the latest koreader version and I can't wait to see the next update ☺. 

![Screenshot_2021-01-16-13-00-38](https://user-images.githubusercontent.com/70109540/104810579-98b55200-5806-11eb-959d-c0ff5d796e25.png)

**Comment by hius07** [comment]
Yes, I would be happy to have this feature as well.

And, since the History page is concerned, one more FR: a combined option of Delete and Purge .sdr.
It might be a checkbox in the Delete confirmation dialogue.

**Comment by poire-z** [comment]
Feels really complicated to implement... (and between hours/days of dev and a few seconds of our time occasionally spent on this, I choose the latter :) 

> FR: a combined option of Delete and Purge .sdr.

"Delete" already removes the .sdr when deleting the book.
If you meant "Remove from history" should also purge the .sdr, there's an option for that, but for the reverse (which makes more sense I think): "Purge .sdr" can also remove from history when `Display mode> Other settings> Auto-remove deleted or purged items from history` is checked.

**Comment by hius07** [comment]
> "Delete" already removes the .sdr when deleting the book.

Thank you, I wasn't aware of that (I thougt it acts similar to the Kindle native system which keeps .sdr folder when deleting a book, for further usage). That closes my FR.

**Comment by Zeyadas** [comment]
I feel like I'm dumb. I'm not a programmer so I didn't understand anything of this..
