### ISSUE TITLE
Folder vs Directory

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7157]
Is there a difference beween Folder and Directory?
I see both e.g. in the + menu in the filebrowser.

**Comment by Frenzie** [comment]
Where do you see directory? But no, there's no difference.

**Comment by Frenzie** [comment]
Okay, this looks bad, yes. ;p
![Screenshot_20210117-141002](https://user-images.githubusercontent.com/202757/104843979-bb5e6e00-58cd-11eb-8cba-2439112e54da.png)

**Comment by hius07** [comment]
> Where do you see directory?

+ menu in the filebrowser: Set as HOME directory
Folder shortcuts: Add new folder shortcut: Long-press to select directory

**Comment by Frenzie** [comment]
Let's take a look at it post release sometime. For now we don't want to
invalidate existing translations.

**Comment by NiLuJe** [comment]
I have a slight conundrum with the example:

* I largely prefer "directory" for the HOME stuff.
* I slightly prefer "folder" for the "new folder" button ;p.

(All in all, I'd tend to prefer directory to folder, it probably fits better in more contexts?)

**Comment by hius07** [comment]
Not very thorough search gives two more directories only:

Gear - Device - Screenshot directory
Book information - Directory

**Comment by pazos** [comment]
> I have a slight conundrum with the example:
> 
> * I largely prefer "directory" for the HOME stuff.
> * I slightly prefer "folder" for the "new folder" button ;p.
> 
> (All in all, I'd tend to prefer directory to folder, it probably fits better in more contexts?)

As a firm believer in everything's a file and heavily desktop paradigm follower I have some issues understanding why that's an issue.

I tend to think that dir and folder is the same. The former is a way to express it in a hieararchy and the later a graphical representation of the former. Both are talking about a "place" where "stuff" is put.

Things are even meaningless in galician or spanish, where directory is never used in mainstream computer-ism. Is still used to represent an index of stuff, like "business directory" or "phone directory". But a directory of files is always called "folder".

**Comment by Frenzie** [comment]
As an aside,

https://support.apple.com/guide/mac-help/folders-that-come-with-your-mac-mchlp1143/mac
> Your home folder is named with your user name and has folders for your desktop files, downloads, pictures, documents, movies, music, and any public files. You can create folders in your home folder.

**Comment by hius07** [comment]
Deep search gives the following statistics in interface elements:
Directory - 18 entries
Folder - 17 entries
Parity)

**Comment by mergen3107** [comment]
Lets agree to “file containers” xD /s

**Comment by hius07** [comment]
![3](https://user-images.githubusercontent.com/62179190/108620292-dfb0eb80-7433-11eb-959b-dd8354d32916.jpg)

**Comment by hius07** [comment]
Two more entries
https://github.com/koreader/koreader/blob/1bd4636a037ee6c8587c706c36d7e96008ec802a/frontend/ui/widget/filechooser.lua#L227-L236
