### ISSUE TITLE
FR: [Option to hidden finished books]

### ISSUE THREAD

**Issue by hugleo** [koreader/koreader#7158]
Add an option in the menu called "Hide finished books", so the books I marked as read will not be shown in the filebrowser list

![add_finished_books_opt](https://user-images.githubusercontent.com/4573505/104846494-9d870e00-58b9-11eb-8ac2-b817701d9a29.jpg)

**Comment by NiLuJe** [comment]
Would require parsing the sidecar file (on each directory open), instead of relying on the cache. (e.g., performance hit).

(That's a "meh :/" on my book, but patches welcome nonetheless).

**Comment by pazos** [comment]
This is a duplicate of #4917. Closing the old one as this one has a better title and a better description

**Comment by hius07** [comment]
Fixed in https://github.com/koreader/koreader/pull/10895.
