### ISSUE TITLE
File open with default kindle reader

### ISSUE THREAD

**Issue by ZacharieALES** [koreader/koreader#7160]
* KOReader version: 2020.12
* Device: Kindle Paperwhite 1 (since serial number starts with B024)

#### Issue
The books are opened with the default kindle reader rather than koreader.

- More details
I just jailbreaked my kindle (everything went well and I had the message "** jailbreak **" at the end displayed on my kindle).
I then chose KPV launcher and installed it (file name: kindle-kpvbooklet-0.6.6.zip). It went well (at least it seemed to).
Then, I extracted the koreader archive (koreader-kindle-v2020.12.zip) at the root of my kindle and added a few dictionnaries in koreader/data/dict. I chose the "kindle" version of koreader rather than legacy or PW2 as I have a kindle PW1 (i.e., a serial number starting with B024). 
In the documentation it is written that koreader should automatically open when I click on a book but it does not (the book is opened with the default kindle reader instead).

Do you know where it might have gone wrong?

**Comment by NiLuJe** [comment]
KPV is unmaintained. You're welcome to ask in the right repo (e.g., https://github.com/koreader/kpvbooklet), but don't expect an answer (and/or a fix, if issue isn't actually PEBCAK).

**Comment by NiLuJe** [comment]
> I chose the "kindle" version of koreader rather than legacy or PW2 as I have a kindle PW1

[Wrong, but not ciritcial](https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#err-there-are-three-kindle-packages-to-choose-from-which-do-i-pick).
