### ISSUE TITLE
Screen refresh desirable entering KOR at poweron [PB631]

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader#7164]
* KOReader version: 2020.12-107

* Device: Pocketbook PB631 (Touch HD)

#### Issue
I've set the PB OS preference for "open last book read" at startup. If my last book was known to the OS as opened by KOR, KOR starts immediately, and that is fine. However, it seems that KOR doesn't do a screen refresh neither when pulling up the its splash dialog, nor when rendering the page, leading to much ghosting. A couple of examples: the first one if the book opens in night mode (my pb_startuplogo image has a dark bottom and a light top)
![IMG_20210118_095514](https://user-images.githubusercontent.com/16066531/104921657-4e68d800-59a2-11eb-9dda-67f122522967.jpg)
This one if the KOR starts in day mode
![IMG_20210118_131013](https://user-images.githubusercontent.com/16066531/104921694-54f74f80-59a2-11eb-9cc4-6a6d747f2da7.jpg)
And the same after flipping one page back and forth, still without a full refresh (so I set preferences), but almost without ghosting.
![IMG_20210118_131032](https://user-images.githubusercontent.com/16066531/104921719-5a549a00-59a2-11eb-9a85-acdb532f0f44.jpg)

Conversely, I see no ghosting when I open the book, if that was not automatically at startup.

I guess that in a sense this is an issue which falls in the broad category of #6597.

**Comment by NiLuJe** [comment]
Quick fix: don't disable flashing on chapter boundaries.

**Comment by EastEriq** [comment]
hmm, no, that doesn't seem to change it.

**Comment by NiLuJe** [comment]
Flashing has no noticeable impact on battery life ;).

----

In any case, that's a highly platform specific issue, unlikely to warrant a convoluted hack to work-it around.

**Comment by EastEriq** [comment]
I see... I was under the illusion that a couple of additional lines in a startup script could have done it, but never mind. Agree on the limited scope of it and on the simplicity of a refresh gesture.

**Comment by NiLuJe** [comment]
Well, it's not a bad idea, but it feels fairly convoluted to implement for very little gain, because what makes it actively annoying here is purely the fact that whatever waveform mode is used here is wonderfully terrible on your device ;).

Hence 

> You might also want to tweak your waveform preset in Screen > e-Ink, because it it ghosts that much here, it's liable to ghost that much in more common scenarios ;).

**Comment by EastEriq** [comment]
I don't think waveforms are that terrible on my device. I'm not so annoyed by ghosting in scenarios other than this, so far. I mean, in obvious cases they may be slight, but nothing really THAT bad, and nothing which still obtrudes after turning a couple of pages without refresh. Anyway, in the menu I have Level 0, high quality, slower; Level 1, low quality, faster, and "Level 2". Where stands 2, fast or slow?

**Comment by NiLuJe** [comment]
Well, it might be on par for a PB, but, trust me, it's *really* bad.

----

> Anyway, in the menu I have Level 0, high quality, slower; Level 1, low quality, faster, and "Level 2". Where stands 2, fast or slow?

That's... strange. It's my understanding that the menu should looks like this:

```
Level 0: high quality, slowest
Level 1
Level 2
Level 3: low quality, fastest
```

(i.e., 0 > 1 > 2 > 3).

Then again, it's a PB quirk, and I don't have a PB, so, someone with one might be able to get you a better answer.

**Comment by EastEriq** [comment]
Uh I see. Someone forgot the % in the localization of "Level %1: low quality, fastest" which I was using. Corrected now.

Anyway, the images I posted above are with level 0.

**Comment by NiLuJe** [comment]
Huh. 0 should essentially be what InkView does. If you forget about nightmode (because that's going to look like crap no matter what), it should *really* look *nothing* like your example (I'd expect that maybe @ level 2 on a B288, level 3 otherwise).

**Comment by EastEriq** [comment]
Almost - the splash about the file being opened is still ghosts the startup image, but that is really minor and doesn't deserve attention. No problem once the book text is displayed, like it was in the pictures I originally attached. Actually things might have improved already in a previous version, I was not aware of the problem anymore since a while (I don't have set refresh at each new page, nor always at new chapter - I might have had some high quality eink rendering setting, but can't find it at the moment).
I attach a picture of the splash ghosting, with 2022.02.
![1646069701325-1](https://user-images.githubusercontent.com/16066531/156033992-5280700b-2ccf-4f7f-9258-91a797dcefe5.jpg)

**Comment by rjd22** [comment]
Small ghosting can indeed appear when displaying images and not having full screen refresh enabled for every page. This should not be noticable when displaying text right of the bat.

Would it be okay to close this issue?

**Comment by EastEriq** [comment]
> Would it be okay to close this issue?

absolutely yes.
