### ISSUE TITLE
crash, attempting to set compact items in status bar [PB631]

### ISSUE THREAD

**Issue by EastEriq** [koreader/koreader#7168]
* KOReader version: 2020.12-107
* Device: Pocketbook PB631

#### Issue
crash attempting to set compact items in status bar

#### Steps to reproduce
 Open a book; Menu/Settings/Status bar/Settings/Prefix/ tag Compact items

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/5836427/crash.log)

(seeing that there is recent WIP in https://github.com/koreader/koreader/pull/7127, maybe this is a premature report?)

**Comment by EastEriq** [comment]
Also with 2020-12.124

**Comment by NiLuJe** [comment]
Ping @JasonInOttawa

**Comment by poire-z** [comment]
I'm looking at it (there are a few other related tweaks needed), so we get a quick fix for the coming up release.

**Comment by JasonInOttawa** [comment]
I think the issue is here

```
    book_time_to_read = function(footer)
        local symbol_type = footer.settings.item_prefix or "icons"
        local prefix = symbol_prefix[symbol_type].book_time_to_read
        local left = footer.ui.document:getTotalPagesLeft(footer.pageno)
        return footer:getDataFromStatistics(prefix .. " ", left)
    end,

```
The return line above throws an exception

`./luajit: frontend/apps/reader/modules/readerfooter.lua:279: attempt to concatenate local 'prefix' (a nil value)
`
The prefix is coming from here (around line 88):

    compact_items = {
```
        ...
        book_time_to_read = nil,
```

Things crash for me now too when I turn on "book time to read" and set compact items. It didn't on earlier builds.

**Comment by poire-z** [comment]
Found out these 3 tweaks are needed (to fix this crash, but also a few things in the menu):
```diff
--- a/frontend/apps/reader/modules/readerfooter.lua
+++ b/frontend/apps/reader/modules/readerfooter.lua
@@ -282,3 +282,3 @@ local footerTextGeneratorMap = {
         local left = footer.ui.document:getTotalPagesLeft(footer.pageno)
-        return footer:getDataFromStatistics(prefix .. " ", left)
+        return footer:getDataFromStatistics(prefix and (prefix.." ") or "", left)
     end,
@@ -822,3 +822,4 @@ function ReaderFooter:textOptionTitles(option)
             and T(_("Progress percentage (%1)"), symbol_prefix[symbol].percentage) or _("Progress percentage"),
-        book_time_to_read = T(_("Book time to read (%1)"),symbol_prefix[symbol].book_time_to_read),
+        book_time_to_read = symbol_prefix[symbol].book_time_to_read
+            and T(_("Book time to read (%1)"),symbol_prefix[symbol].book_time_to_read) or _("Book time to read"),
         chapter_time_to_read = T(_("Chapter time to read (%1)"), symbol_prefix[symbol].chapter_time_to_read),
@@ -1256,3 +1257,3 @@ function ReaderFooter:addToMainMenu(menu_items)
                         checked_func = function()
-                            return self.settings.item_prefix == "compact_items" or self.settings.item_prefix == nil
+                            return self.settings.item_prefix == "compact_items"
                         end,
```

Not sure why it would not crash before :/

**Comment by JasonInOttawa** [comment]
I'm not sure why I didn't see crashes before either. I did try turning everyone on and seeing the difference in space usage between prefix icons, letters, and compact items, but I can't find any screen shots showing time left in book.

Will you be putting in a PR with the tweaks? Or should I do that?

**Comment by poire-z** [comment]
Feel free to do it if you have the time (or I'll do it later this evening).

**Comment by JasonInOttawa** [comment]
I've got a file ready to go with the following diffs:

```
283c283
<         return footer:getDataFromStatistics(prefix .. " ", left)
---
>         return footer:getDataFromStatistics(prefix and (prefix.." ") or "", left)
823c823,824
<         book_time_to_read = T(_("Book time to read (%1)"),symbol_prefix[symbol].book_time_to_read),
---
>         book_time_to_read = symbol_prefix[symbol].book_time_to_read
>             and T(_("Book time to read (%1)"),symbol_prefix[symbol].book_time_to_read) or _("Book time to read"),
1257c1258
<                             return self.settings.item_prefix == "compact_items" or self.settings.item_prefix == nil
---
>                             return self.settings.item_prefix == "compact_items"

```

The menu items look like this

![Screen Shot 2021-01-19 at 12 09 55 PM](https://user-images.githubusercontent.com/46451014/105069000-76fadb80-5a4f-11eb-891d-866118dd1dd8.png)

![Screen Shot 2021-01-19 at 12 10 04 PM](https://user-images.githubusercontent.com/46451014/105069023-7c582600-5a4f-11eb-87d2-0a66953a4827.png)

The status bar looks like this

![Screen Shot 2021-01-19 at 12 10 10 PM](https://user-images.githubusercontent.com/46451014/105069072-85e18e00-5a4f-11eb-90f1-e8a9a66d3503.png)

I am seeing the following items on it:

Progress bar
Book title
Current time
Current Page
Pages left in book
Pages left in chapter
Battery status
Progress percentage
Time to read book
Time to read chapter
Chapter title
Bookmark count

I don't see memory usage, but I see similar behaviour on the Letters prefix. I'm running a desktop version. Should that work, or should the Memory usage option be removed from the menu on desktop?

**Comment by NiLuJe** [comment]
It never crashed before because the `prefix` used to never be `nil` by contract ;).

**Comment by JasonInOttawa** [comment]
Got it, thanks. If I fiddle any more with the status bar I will look into things more closely.

I've raised PR 7172.

**Comment by poire-z** [comment]
I can see the memory item.
Mem usage is emtpy when it can't read /proc/self/statm (a situation we thought should not happen, so empty to just avoid a crash) - may be that does not exist on Mac ? Anyway, doesn't need any fix I guess.

> I'm not sure why I didn't see crashes before either. 

May be because for a long time at the start of your PR, you had it set to `""`. Only in a late commit https://github.com/koreader/koreader/pull/7127/commits/3e34fd8a42ac2d77c583c64b49b5e2c9b32be966  you switched it to `nil` - and you didn't have it enabled after that ? :)

**Comment by JasonInOttawa** [comment]
Ah, ok. I have the "Hide empty items" option turned on.

I think you're right - I must've set it to nil and did not test it with the option turned off and on after the change. I noticed that some other options were set to nil (eg. letters.time) rather than "".
