### ISSUE TITLE
Time in alt status bar

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#7171]
* KOReader version: 2020.12-124
* Device: Samsung s10 android 10

#### Issue
The time displayed in the alt status bar is not controlled by the device setting, it is always in 24h format with a leading zero from 1am to 9am.
I'm assuming this is hardcoded in CR as the coolreader app displays it this way as well, and I'm not aware of any setting to change it.
This is basically the same issue as [https://github.com/koreader/koreader/issues/6969](6969), just with CR.
#### Steps to reproduce
Set the time to display in the alt status bar.
##### `crash.log` (if applicable)
N/A

**Comment by zwim** [comment]
Yes, the time format in toe alt status bar is hard coded in crengine.

**Comment by Frenzie** [comment]
You might have a better chance getting someone over at crengine to change that. (At least, I think most of us primary KOReader maintainers don't use that statusbar.)

**Comment by mendelct** [comment]
For myself I just patched it to use 12h clock. 
In  LVDocView::getTimeString()
`
char ampm[] = "AM";

	if (bt->tm_hour > 12) {

        	strcpy (ampm, "PM");

        	bt->tm_hour -= 12;

     	}

     	if (bt->tm_hour == 12)

        	strcpy (ampm, "PM");

     	if (bt->tm_hour == 0) 

        	bt->tm_hour = 12;

	sprintf(str, "%d:%02d %s", bt->tm_hour, bt->tm_min, ampm);`

**Comment by NiLuJe** [comment]
Random comment: Slightly mystified why this isn't using `strftime` to begin with.

**Comment by mendelct** [comment]
Thanks
