### ISSUE TITLE
Reference to /common/lj-wpaclient/* in the nightly build for reMarkable 2

### ISSUE THREAD

**Issue by wordpr3ss** [koreader/koreader#7175]
./luajit: frontend/ui/network/wpa_supplicant.lua:7: module 'lj-wpaclient/wpaclient' not found:
	no field package.preload['lj-wpaclient/wpaclient']
	no file 'common/lj-wpaclient/wpaclient.lua'
	no file 'rocks/share/lua/5.1/lj-wpaclient/wpaclient.lua'
	no file 'frontend/lj-wpaclient/wpaclient.lua'
	no file './lj-wpaclient/wpaclient.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/lj-wpaclient/wpaclient.lua'
	no file '/usr/local/share/lua/5.1/lj-wpaclient/wpaclient.lua'
	no file '/usr/local/share/lua/5.1/lj-wpaclient/wpaclient/init.lua'
	no file 'common/lj-wpaclient/wpaclient.so'
	no file 'common/lj-wpaclient/wpaclient.dll'
	no file '/usr/lib/lua/lj-wpaclient/wpaclient.so'
	no file 'rocks/lib/lua/5.1/lj-wpaclient/wpaclient.so'
	no file './lj-wpaclient/wpaclient.so'
	no file '/usr/local/lib/lua/5.1/lj-wpaclient/wpaclient.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	frontend/ui/network/wpa_supplicant.lua:7: in main chunk
	[C]: in function 'require'
	frontend/ui/network/manager.lua:646: in function 'setWirelessBackend'
	frontend/device/remarkable/device.lua:152: in function 'initNetworkManager'
	frontend/ui/network/manager.lua:655: in main chunk
	[C]: in function 'require'
	frontend/apps/reader/modules/readerdictionary.lua:14: in main chunk
	[C]: in function 'require'
	frontend/apps/reader/readerui.lua:31: in main chunk
	[C]: in function 'require'
	frontend/apps/cloudstorage/dropbox.lua:8: in main chunk
	[C]: in function 'require'
	frontend/apps/cloudstorage/cloudstorage.lua:6: in main chunk
	[C]: in function 'require'
	frontend/apps/filemanager/filemanagermenu.lua:3: in main chunk
	[C]: in function 'require'
	frontend/apps/filemanager/filemanager.lua:18: in main chunk
	[C]: in function 'require'
	./reader.lua:294: in main chunk
	[C]: at 0x0001415d
!!!!
Uh oh, something went awry... (Crash n°1: 01/19/21 @ 23:42:05)
Running on Linux 4.14.78 (#1 SMP PREEMPT Fri Nov 6 14:42:47 UTC 2020)
Attempting to restart KOReader . . .
!!!!

**Comment by Frenzie** [comment]
@pazos But with regard to #7122 I will say that this issue right here is exactly why I put a 2021.02 on it.

**Comment by pazos** [comment]
> @pazos But with regard to #7122 I will say that this issue right here is exactly why I put a 2021.02 on it.

:cricket: :cricket: 

It is something in the build server, right?.

**Comment by Frenzie** [comment]
No? It's not enabled in Makefile.defs (use_lj_wpaclient or some such) but it's clearly not used since it's using shellscripts.

**Comment by pazos** [comment]
> No? It's not enabled in Makefile.defs (use_lj_wpaclient or some such) but it's clearly not used since it's using shellscripts.

NetworkMgr uses it to drive the ctrl_interface. But know that I look again at the code the dhcp client part seems missing. So it is associating to AP but never gets a lease?. Any idea @snelg

**Comment by Frenzie** [comment]
PS So if it's actually lj-wpaclient missing, it's a simple additional line here: https://github.com/koreader/koreader-base/blob/6054e5c84fdf59c74ecd57de14f68d6786e73cb3/Makefile.defs#L157-L159 (`export USE_LJ_WPACLIENT=1`). 

It's just that the PR doesn't necessarily give me the impression that it's _missing_, but I've only taken a quick glance.

**Comment by NiLuJe** [comment]
That bit in #7122 pretty much requires `LJ_WPACLIENT` ;p.

`NetworkMgr:setWirelessBackend("wpa_supplicant", {ctrl_interface = "/var/run/wpa_supplicant/wlan0"})`

**Comment by Frenzie** [comment]
Well, then someone please toss in a `USE_LJ_WPACLIENT=1` and bump base. :-P

**Comment by NiLuJe** [comment]
I'll leave the bump to someone else and/or until @pazos's concerns in https://github.com/koreader/koreader/issues/7175#issuecomment-763601149 have been addressed ;).

**Comment by Frenzie** [comment]
Alright, I *might* tag the release tomorrow but if I do I'll revert that commit first then. Anyway, otherwise it'll be the weekend (not Friday).

**Comment by Frenzie** [comment]
^ Milestone for me, please don't change unless it goes together with reverting the commit.

**Comment by snelg** [comment]
Sorry, my mistake. When I was still trying to figure out how all this works, at some point I manually copied lj-wpaclient onto my reMarkable and then immediately forgot that I'd done that.
I should have tested a full clean install before submitting the PR.

**Comment by pazos** [comment]
@snelg: don't worry. My bad as a reviewer :p 

Could you answer https://github.com/koreader/koreader/issues/7175#issuecomment-763601149? It is some dhcp client running as a daemon and managing to obtain/release ip?.  Is there a reason to diff between that and wpa_supplicant.

As I understand you kill wpa_supplicant instead of repurposing it from stock (something that will kill running wifi when switching from xotchil). If that's a desired behaviour why don't kill the dhcp client too?

If you want to repurpose the dhcp daemon why not also repurpose wpa_supplicant and just run it if there's no actually running?

**Comment by snelg** [comment]
There's a stock dhcpd service running via systemd that I didn't touch.
I wouldn't have touched the stock wpa_supplicant service either, but it uses the DBus control interface (`wpa_supplicant -u`).

So the two main options I saw were
 1. Restarting wpa_supplicant with a standard ctrl_interface socket, and using the existing KOReader wpa_supplicant code
 2. Using the existing wpa_supplicant systemd service, and writing DBus code for KOReader

Option 1 seemed much simpler.

**Comment by pazos** [comment]
Thanks for the info, makes sense.

Maybe for users who switch between xocthil and koreader a lot is a bit of pain to have their connection closed in between. I cannot speak by myself as I don't have a kobo anymore, but if IIRC we keep the wifi enabled when we start from stock. Pinging @NiLuJe.

I guess the same could be applied here, with some modifications.

If wifi is active don't kill it unless we're going to suspend.
If we change the state of the wifi in KO at least once (manually or via suspend/resume) make sure the wifi is left in a state that stock can handle. If we don't change the wifi there's no need for reseting back before exiting.

Anyways, that can be implemented later on.

**Comment by snelg** [comment]
Good point, I haven't extensively tested the "switching back and forth" scenario.
I just ran a quick test, and both switches seemed to work fine:
 - Switched to KOReader while stock (DBus wpa_supplicant) wifi was active: KOReader did *not* touch the existing connection
 - Switched to xochitl while the ctrl_interface socket wpa_supplicant was active: xochitl killed that KOReader-initiated wpa_supplicant and cleanly restarted the DBus wpa_supplicant service

**Comment by pazos** [comment]
Great! Last question: 

> Switched to KOReader while stock (DBus wpa_supplicant) wifi was active: KOReader did not touch the existing connection

In that scenario, does KOReader report the current wifi state on settings -> network?

**Comment by snelg** [comment]
Yes, if the stock wifi is active then KOReader uses it correctly. The settings -> network "Wi-Fi connection" bo was checked, and I successfully looked up a wikipedia entry as a test.

**Comment by NiLuJe** [comment]
> Maybe for users who switch between xocthil and koreader a lot is a bit of pain to have their connection closed in between. I cannot speak by myself as I don't have a kobo anymore, but if IIRC we keep the wifi enabled when we start from stock. Pinging @NiLuJe.

Yeah, if the state is sane (e.g., drivers are loaded, AP is associated, interface is up, and it actually pings), we keep it.
We do murder the DHCP client, because Nickel now runs in in daemon mode, while we don't, so stuff would technically maybe get iffy at lease expiry, but it's never really been a problem in practice.
