### ISSUE TITLE
[Mobi]: Internal link generated from calibre not working

### ISSUE THREAD

**Issue by StillerHarpo** [koreader/koreader#7180]
* KOReader version: 2020.12
* Device: Pocket Pook Touch HD 3

#### Issue
Calibre downloads articles from a feed into one book with a table of contents at the start of the book.  The items in this table are links to the articles. In calibre I can click on this links and get to the desired location in the Book.  In koreader nothing happens if I click on this links.

#### Steps to reproduce
+ Add a feed to calibre
+ Export the generated book to the E-reader
+ Open it with koreader
+ Press on a item in the table of contents

**Comment by Frenzie** [comment]
Would it be possible to attach a file so that we can skip the calibre part of the equation?

**Comment by StillerHarpo** [comment]
Github doesn't support the file type.  Is there some standard way to upload the file?

**Comment by NiLuJe** [comment]
Archive it in a zip or tgz, that'll work.

**Comment by StillerHarpo** [comment]
Here you go [creativeCommonsBlog.zip](https://github.com/koreader/koreader/files/5858630/creativeCommonsBlog.zip)
I tried this also on android and got the same issue.

**Comment by Galunid** [comment]
@StillerHarpo It seems you used `.mobi` file. As far as I know, KOReader's support for `.mobi` is extremely limited. I'd assume it'll work as expected if it's converted to `.epub` file, using Calibre for example

**Comment by NiLuJe** [comment]
Yep, @Galunid got it in one ;).

**Comment by StillerHarpo** [comment]
@Galunid Your right. Converting it to `.epub` fixed it
