### ISSUE TITLE
Make Table of Content/Search Results better readable.

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#7188]
I mentioned already in one of the Discussions that the search results are really small, very hard to read.
Now I see the same goes for the table of content.
Here's a photo (somehow my multiswipe to do a screenshot does not work here):
![Bild1](https://user-images.githubusercontent.com/7792441/105580514-21933700-5d8d-11eb-8168-b3da96e45b79.jpg)
This looks for sure different than it does in my 6 years old version on my Kobo Aura, there the fonts were way better readable.
I don't really think the fonts here should be configurable, but thy should be better readable! The fonts at the headline "Table of Content" and "Page 1 of 2" are absolutely fine, just the content itself is not.
(I thought it might be because of landscape mode, but in portrait mode it looks similar)

**Comment by Frenzie** [comment]
It's not easy to find (from the reader), but try file browser, items, don't
size.

**Comment by NiLuJe** [comment]
That screenshot looks like it's using a custom value, FWWI, because it feels slightly larger thna that at the default (19) on my end.

But, yeah, this is affected by what @Frenzie said ;).

**Comment by Frenzie** [comment]
I'll have to disable autocorrect on my new phone. Whatever I typod, it wasn't don't size, lol

**Comment by Frenzie** [comment]
And done. I don't care for this Gboard thing anyway.

![Screenshot_2021-01-23-15-44-05-73](https://user-images.githubusercontent.com/202757/105588616-da5b7500-5d91-11eb-818c-8a4c3fa8691f.jpg)

**Comment by WS64** [comment]
Yes, way better... It was on 10. Back to 19 and everything is fine.
Same goes for the search results.

**Comment by poire-z** [comment]
Remember for what you did set it to 10 ?
This setting is used for various different things, where we might prefer things differently, but it's not yet possible.
(Just asking, not thinking at modifying that.)

**Comment by Frenzie** [comment]
The default is something like 16 if I'm not mistaken.

**Comment by WS64** [comment]
Not, it went to 19 when I clicked "use default".
I have no idea what I did, I was never in that menu.
But, I might have edoted in the settings file before, especially since at first I tried to re-use my old settings from the 2014 version.

**Comment by Frenzie** [comment]
19 fits within "something like" (main point being it's a lot larger than 10), but I guess I was wrong then. ^_^
