### ISSUE TITLE
koreader v2021.01 AppImage crashes on start

### ISSUE THREAD

**Issue by nerdboy4200** [koreader/koreader#7190]
* KOReader version: v2021.01
* Device: Linux (Arch Linux and Manjaro - both up to date as of when I posted this)

#### Issue
Starting koreader crashes after popping up a window for a second
I deleted my ~/.config/koreader tree so there was no config

#### Steps to reproduce
just start koreader app image

##### `crash.log` (if applicable)
There was no crash.log file anywhere - so here is the output from the commandline run (cleaned up the path):
```
$ ./koreader-appimage-x86_64-linux-gnu-v2021.01.AppImage 
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/23/21-11:54:00
 [*] Version: v2021.01

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
01/23/21-11:54:00 INFO  platform thirdparty apps
-> Goldendict (goldendict), role: dict, available: false

Starting SDL in /tmp/.mount_koreadRhECg4/
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
01/23/21-11:54:00 WARN  ./ffi/SDL2_0.lua:433: /tmp/.mount_koreadRhECg4/libs/libSDL2.so: undefined symbol: SDL_CreateRGBSurfaceWithFormatFrom
01/23/21-11:54:00 INFO  initializing for device AppImage
01/23/21-11:54:00 INFO  framebuffer resolution: {
    ["w"] = 600,
    ["h"] = 800,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
01/23/21-11:54:00 INFO  /home/XX/.config/koreader/cache/fontinfo.dat [string "/home/XX/.config/koreader/cache/fontinfo.dat"]:1: unexpected symbol near '/' initializing it
./luajit: error loading module 'libs/libkoreader-nnsvg' from file './libs/libkoreader-nnsvg.so':
	./libs/libkoreader-nnsvg.so: undefined symbol: __pow_finite
stack traceback:
	[C]: at 0x00452810
	[C]: in function 'require'
	frontend/ui/renderimage.lua:215: in function 'renderSVGImageFile'
	frontend/ui/widget/imagewidget.lua:173: in function '_loadfile'
	frontend/ui/widget/imagewidget.lua:247: in function '_render'
	frontend/ui/widget/imagewidget.lua:352: in function 'getSize'
	frontend/ui/widget/horizontalgroup.lua:24: in function 'getSize'
	frontend/ui/widget/container/framecontainer.lua:47: in function 'getSize'
	frontend/ui/widget/infomessage.lua:169: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	./reader.lua:217: in main chunk
	[C]: at 0x00405020
$ 
```

The warning about SDL_CreateRGBSurfaceWithFormatFrom is concerning - but the crash on start is the major issue here.

**Comment by Frenzie** [comment]
It works on Debian 10, but I can confirm it not working on Ubuntu 20.10. I'm guessing some libc upgrade is to blame, also see https://stackoverflow.com/questions/61580159/undefined-references-to-libm-symbols-after-upgrading-linux-distro (we use `-lm` so I'm not quite clear on what the problem is). Pinging @NiLuJe in case anything immediately comes to mind.

**Comment by nerdboy4200** [comment]
OK - interesting. I did find this - so I'm not 100% off in what I was seeing:

```
$ nm -gD /usr/lib/libm.so.6 |grep pow_
000000000002ed40 i __pow_finite@GLIBC_2.15
$
```
Which is interesting as I see this (after unpacking the AppImage):
```
$ ldd libs/libkoreader-nnsvg.so 
ldd: warning: you do not have execution permission for `./libkoreader-nnsvg.so'
	linux-vdso.so.1 (0x00007ffdcf299000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f10d26c3000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f10d2b01000)
$
```
which means that that particular library isn't linked to libm - which could be whats causing issues.

I also wondered if it was related to #722 - but that had to do with locking down on glibc version tags - which I think wouldn't be a problem in this case.

**Comment by nerdboy4200** [comment]
Oh - as a quick note - the v2020.12 AppImage does work properly on my system. The library for libkoreader-nnsvg isn't any differently linked - so my ldd on nnsvg might not be as important.

**Comment by poire-z** [comment]
libkoreader-nnsvg.so was included in v2020.12 - but it was not really used, so could hardly cause a crash.
But it is in v2021.1 as we now use it for our SVG icons.

**Comment by NiLuJe** [comment]
I have no idea how nnsvg could end up not being linked to libm, as I think we went over that already, and it definitely should ;p.

**Comment by NiLuJe** [comment]
Indeed it does: https://github.com/koreader/koreader-base/blob/b8ac18ef9f31a76c9a1e8e9de3741908dcb19077/Makefile#L199

Unless the linker is having a sad and prefers it after the `-o` (I mean, I've seen weirder shit as far as Ubuntu is concerned, so, who knows).

**Comment by Frenzie** [comment]
@NiLuJe That's what I said in my first message. :-P

**Comment by NiLuJe** [comment]
@Frenzie: lol, I need sleep :D.
