### ISSUE TITLE
pdf: setting default "Zoom to" lacks description, "Set default Zoom to to 4?"

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#7192]
* KOReader version: v2021.01
* Device: reMarkable 1

#### Issue
The popup to set the default "Zoom to" value just has an integer value for each option, instead of a description/name.

#### Steps to reproduce
When reading a pdf, open the bottom settings and choose the third tab. The second option down is "Zoom to", with 5 icons to choose from. If you press and hold on one of these icons, a popup will appear with, for example, "Set default Zoom to to 4?", as the text (Options are 4,3,2,1,0 from left to right).

Having a name / description in the popup instead of the raw number would also be helpful as clarification if anyone is unsure exactly what each icon means.

**Comment by Frenzie** [comment]
PS Avoid clever programming reflexes. Each type should be a full string.

**Comment by NiLuJe** [comment]
Fixed by #7463
