### ISSUE TITLE
Focus doesn't change for physical keyboards

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#7194]
* KOReader version: 2021-01-1
* Device: debian desktop

#### Issue

Keyboard focus doesn't seem to change when you click on a different field. 

#### Steps to reproduce

1. Go to add a new Cloud Storage account
2. Select Dropbox
2. type the word "KEYBOARD" on a physical keyboard in the dropbox name field,
3. click on the dropbox token field, 
4. type the words "afterClickOnTokenBox" on a physical keyboard, and the characters appear in the top (dropbox name) field

If you then type "onscreen" on the onscreen keyboard without clicking the mouse, those characters appear in the token field as expected.

![koreader keyboard](https://user-images.githubusercontent.com/46451014/105619699-38ed1700-5dc3-11eb-8f64-532922c5a299.png)

##### `crash.log` (if applicable)

There's no crash or exception in crash.log. I can provide it if needed.

**Comment by NiLuJe** [comment]
10 hours too late ;p

https://github.com/koreader/koreader/pull/7183#discussion_r563185118

**Comment by JasonInOttawa** [comment]
This seems to work now
