### ISSUE TITLE
Crash on night mode - Koreader 2021.01

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#7197]
KOReader version: 2021.01
Device: nook glowlight plus 7.8"
Firmware:4.4.2 (rooted)

#### Issue
Koreader crashes when turn on "night mode"

I did not encounter this crash with Koreader 2020.12

I did not encounter this crash with Koreader 2021.01 - device: LG V50 - android 10.

Thank you

**Comment by NiLuJe** [comment]
Fixed in https://github.com/koreader/koreader-base/pull/1293

Not yet in a nightly because pending testing of secondary, better fix in https://github.com/koreader/koreader/discussions/7187?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE1MDkyNTczMTg6MTExOTc0#discussioncomment-306052
