### ISSUE TITLE
First CSS rule right after @namespace ignored

### ISSUE THREAD

**Issue by KrokusPokus** [koreader/koreader#7199]
* KOReader version: v2021.01
* Device: Android (any)

#### Issue
If you have a CSS file like this:

```
@namespace h "http://www.w3.org/1999/xhtml";
.StyleA {
  color: red;
  font-size: 2em;
  font-style: italic;
}
.StyleB {
  color: red;
  font-size: 2em;
  font-style: italic;
}
```

then text that uses StyleA does not receive any formating, while text with StyleB it does.
On the other hand, in Calibre Viewer, both texts are using the specified styling.

#### Steps to reproduce
See attached epub sample:
[GF Tests 3.zip](https://github.com/koreader/koreader/files/5870586/GF.Tests.3.zip)

**Comment by poire-z** [comment]
CSS blocks and statements it seems these things are called at https://developer.mozilla.org/en-US/docs/Web/CSS/Syntax

crengine's stylesheet parser is not super robust with all the `@something` stuff. There was something added recently to ignore `@charset`, but that's all - no `@media` stuff either (#3179)... `@import` is also a bit limited (expected only at start):
https://github.com/koreader/crengine/blob/c4b6b9ee2a5e123f20955b80b29b3a0063863844/crengine/src/lvstsheet.cpp#L4434-L4455

I'm not keen on string parsing :) and neither on reading another parsing spec like https://www.w3.org/TR/css-syntax-3/#tokenizing-and-parsing .
So,, if anyone feels like doing it, or at least making simpler rules like "if meeting this, skip until that"...

**Comment by KrokusPokus** [comment]
If for now we don't want to handle At-rules except for @charset, the parseCharsetRule() should probably be extended to recognize all other @-keywords and skip to their end. Something like this, maybe:

```
bool LVStyleSheet::parseCharsetRule( const char * &str )
{
    if (!str || !*str)
        return false;
    skip_spaces( str );
    if ( *str == '@' ) {
        str++;
        char word[64];
        if ( parse_ident( str, word ) ) {
            lString8 keyword(word);
             // Parse rule '@charset' according https://developer.mozilla.org/en-US/docs/Web/CSS/@charset
            if (keyword == "charset") {
                // skip required space(s)
                if (*str == ' ' || *str == '\t') {
                    skip_spaces(str);
                    if (parse_attr_value(str, word, ';')) {
                        if (_charset.empty()) {
                            _charset = word;
                            return true;
                        }
                    }
                }
            }
            else if((keyword == "media")
                || (keyword == "supports")
                || (keyword == "document")
                || (keyword == "page")
                || (keyword == "font-face")
                || (keyword == "keyframes")
                || (keyword == "viewport")
                || (keyword == "counter-style")
                || (keyword == "font-feature-values")
                || (keyword == "swash")
                || (keyword == "ornaments")
                || (keyword == "annotation")
                || (keyword == "stylistic")
                || (keyword == "styleset")
                || (keyword == "character-variant")
                || (keyword == "property")) {
                // skip required space(s)
                if (*str == ' ' || *str == '\t') {
                    skip_spaces(str);
                    if (parse_attr_value(str, word, ';'))
                       return false;
                }
            }
        }
    }
return false;
}
```
(Maybe also rename parseCharsetRule() to parseAtRule() since this function would start handling At-rules in general.)

I'm not clear on the ending condition, though, since [https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule]() defines the end of any At-rule is "the next semicolon, ';' (U+003B SEMICOLON), or the next CSS block, whichever comes first." Right now, we only look for the semicolon.

**Comment by Frenzie** [comment]
Don't have much time to look, but by next CSS block I'm guessing they mean nested?

```css
@something (something-else) {
  /* nested */
}
```

**Comment by Frenzie** [comment]
See for example over on https://www.w3.org/TR/CSS2/media.html#at-media-rule

> A declaration block starts with a left curly brace ({) and ends with the matching right curly brace (}). In between there must be a list of zero or more semicolon-separated (;) declarations.
