### ISSUE TITLE
Full height of screen not utilized

### ISSUE THREAD

**Issue by medwatt** [koreader/koreader#7200]
* KOReader version:
* Device: Onyx i86 ML

#### Issue

There is a gap between on the bottom of the screen that is not used. [This](https://i.imgur.com/mUKflBQ.jpeg) is an image that shows it.

**Comment by pazos** [comment]
check fullscreen setting in settings - screen

**Comment by medwatt** [comment]
> check fullscreen setting in settings - screen

Fullscreen in enabled. In fact, it is not possible to disable it. When I untick the checkbox, exit, and restart the app, the checkbox is back to being ticked. I also changed the dpi to different values (the device's dpi is 250) and that also didn't do anything.

**Comment by pazos** [comment]
In that case please read https://www.mobileread.com/forums/showthread.php?t=326320

It is a good resume of all the issues and workarounds available.

**Comment by medwatt** [comment]
> In that case please read https://www.mobileread.com/forums/showthread.php?t=326320
> 
> It is a good resume of all the issues and workarounds available.

Setting the height to 1600 fixed the issue. Thanks !
