### ISSUE TITLE
Kobo: Perception Expander enabled -> no changes

### ISSUE THREAD

**Issue by lbesnard** [koreader/koreader#7203]
* KOReader version: 2020.12
* Device: Kobo glo

#### Issue 
Perception Expander plug-in

Although enabled, this plug-in doesn't seem to do anything whatsoever with *.epub files. I tried the default values and many others, however nothing happens. As a matter of fact, the page doesn't even refresh if I disable/enable the plug-in

#### Steps to reproduce
1. Open epub file
2. Enable Perception Expander
3. Observe changes -> nothing
4. Change default values
5. 3. Observe changes -> nothing

**Comment by Galunid** [comment]
I can't replicate, can you try setting below? I'd assume your "Margin from edges" is >1, or "Line thickness" is 0. It should draw two vertical lines on page. I tried it on my Clara HD and it works fine.

Line thickness: 2
Margin from edges: 0.1
Line color intensity: 10
Increase margin after pages: 0

**Comment by NiLuJe** [comment]
Have you actually enabled the *feature*, as opposed to the plugin itself?

(Doc > Speed reading module).

It won't refresh the page until you exit the menu.

**Comment by lbesnard** [comment]
> I can't replicate, can you try setting below? I'd assume your "Margin from edges" is >1, or "Line thickness" is 0. It should draw two vertical lines on page. I tried it on my Clara HD and it works fine.
> 
> Line thickness: 2
> Margin from edges: 0.1
> Line color intensity: 10
> Increase margin after pages: 0

I can replicate this. I have two vertical lines on the page as well. However the text goes beyond this "box" and doesn't change at all if I enable/disable the plugin. Only these vertical lines disappear.

**Comment by NiLuJe** [comment]
Which is [apparently the point](https://github.com/koreader/koreader/wiki/Perception-Expander-plugin).

**Comment by lbesnard** [comment]
> Which is [apparently the point](https://github.com/koreader/koreader/wiki/Perception-Expander-plugin).

I probably completely misunderstood the use of plugin then. I thought this would also change the format, i.e. also change the justification of a pair of lines
