### ISSUE TITLE
Nickel networking doesn't work after closing koreader

### ISSUE THREAD

**Issue by nihilazo** [koreader/koreader#7205]
* KOReader version: 2021.01
* Device: Kobo Aura HD

#### Issue

After closing koreader from being run via nickelmenu, my kobo will no longer connect to wifi. For networks I have the password for, it asks for the password and fails to connect. If I connect to an unsecured network, it just fails to connect. 
NOTE: this does not always seem to happen. Sometimes, it works if I just wait a while.

#### Steps to reproduce

* Run KOReader through fbmon/nickelmenu
* Exit
* Attempt to connect to a network within nickel

**Comment by NiLuJe** [comment]
On which FW version?

This should no longer be an issue no current FW revisions and current launchers/KOReader versions. You only gave details about  the second part of that equation ;).

**Comment by nihilazo** [comment]
> On which FW version?
> 
> This should no longer be an issue on current FW revisions and current launchers/KOReader versions. You only gave details about the second part of that equation ;).

How do I find out what fw version I am running?

**Comment by Frenzie** [comment]
In about Kobo somewhere it'll say 3.11, 4.22, something like that.

**Comment by Frenzie** [comment]
Not in KOReader.

**Comment by nihilazo** [comment]
The firmware version is 4.25.15875.

**Comment by NiLuJe** [comment]
Was KSM ever installed on that device, and, if so, how was it uninstalled?

**Comment by nihilazo** [comment]
> Was KSM ever installed on that device, and, if so, how was it uninstalled?

It was, I can't remember how I uninstalled it.

**Comment by NiLuJe** [comment]
Then off to do a *full* (e.g., the one from the devmenu or with the button gymnastics during boot, not the one in the stock menus) factory reset you go ;).

(Spoiler alert: this may not change anything, but it can't hurt. What I can tell you is that this shouldn't be an issue anymore, and that KSM may have broken it and hampered further updates from fixing it).

**Comment by nihilazo** [comment]
Update - this works after a full reset. Closing
