### ISSUE TITLE
FR: Gemini browser

### ISSUE THREAD

**Issue by kr-cr** [koreader/koreader#7206]
The recent rise of interest for Gemini is making me think a dedicated browser would be a great news for both e-ink devices and the gemini protocol as it would bring more potential readers and a greater diversity of content to be read on these devices.

As I am not a develloper, I don't really know how difficult would it be to make KOReader able to browse the gemini protocol.

What do you think?

**Comment by NiLuJe** [comment]
Wild guess: ranging from "hard" to "pipe-dream"?

**Comment by Frenzie** [comment]
Actually it's supposed to be easy (in the not needing a team working for a
year but one dev working for a few days sense probably). See the Drew
Devault blog post

**Comment by Frenzie** [comment]
@NiLuJe https://portal.mozz.us/gemini/gemini.circumlunar.space/docs/gemtext.gmi

**Comment by NiLuJe** [comment]
Well, that's strictly the ML, which is not quite what the OP was asking, I think ;).

**Comment by kr-cr** [comment]
Ok, I though it might have been easier for an already built reader to add Gemini support than to build a new client from scratch but yes maybe it’s a bit out-of-scope.

Meanwhile I saw that someone is working on a dedicated client for Kobo https://tiny.tilde.website/@nihilazo/105627780797916762

(For me the use case would be to sync bookmarked Gemini capsules at home to read later offline in the same way as for Wallabag.)
