### ISSUE TITLE
macOS: Crash on opening book

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#7207]
* KOReader version: 2021.01-11
* Device: macOS

#### Issue

Opening a book results in the following exception:

```
[!] doShowReader coroutine crashed:
frontend/document/credocument.lua:282: attempt to call method 'getDocumentRenderingHash' (a nil value)
stack traceback:
	frontend/document/credocument.lua:1685: in function 'getDocumentRenderingHash'
	frontend/apps/reader/modules/readerrolling.lua:121: in function 'v'
	frontend/apps/reader/readerui.lua:418: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/reader/readerui.lua:578: in function 'doShowReader'
	frontend/apps/reader/readerui.lua:536: in function <frontend/apps/reader/readerui.lua:535>01/28/21-08:37:41 INFO  FM loaded plugin autosuspend at plugins/autosuspend.koplugin

```

#### Steps to reproduce

Open an epub

[crash.log](https://github.com/koreader/koreader/files/5887542/crash.log)

**Comment by poire-z** [comment]
Mhhh, are you posting from the future ?! :)
getDocumentRenderingHash() is from #7204 , which has not yet been merged (and neither its base counterpart, so #7204 is still incomplete/a draft).
(Unless I miss something ?!)

**Comment by Frenzie** [comment]
#7204 has an auto-generated mac artifact which can be downloaded, but if a base bump isn't included that's the logical consequence. I'm guessing that's what happened. ;-)

**Comment by JasonInOttawa** [comment]
Thank you. I downloaded the artifact from "test #545" (2021.01-03) and that worked. I will avoid downloading anything apart from the "base bump"s.

**Comment by Frenzie** [comment]
@JasonInOttawa Most PRs don't depend on base bumps. But if you want the latest (presumably working) build, you should grab it from https://github.com/koreader/koreader/commits/master

**Comment by JasonInOttawa** [comment]
Thank you. Bookmarked.
