### ISSUE TITLE
Zsync didn't work. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7208]
* KOReader version: latest version on both devices. 
* Device: device (1) Samsung SM-T285, device (2) Samsung sm-g532f

I did exactly what described in https://github.com/koreader/koreader/wiki/Zsync-transport and it didn't work for me. 

I downloaded a book from a telegram group, opened it on device (2), I usually use WiFi direct or Bluetooth to share the files with device (1) to read on it since it's a 7" android tablet, this time I wanted to give the zsync a try.. 
Both devices connected to the same router and as I said I did exactly what described in the wiki. 
I was thinking is there a way to share the files using other methods (Google drive) for example?

**Comment by Frenzie** [comment]
I'm not quite sure if that actually works on Android.

**Comment by Zeyadas** [comment]
I thought about that, so I used the device memory as download directory.

**Comment by pazos** [comment]
> I'm not quite sure if that actually works on Android.

Between android devices I don't know. But [the last time I tested](https://github.com/koreader/koreader/issues/2223#issuecomment-596835555) worked fine between cervantes as publisher and android as suscriber.

> I thought about that, so I used the device memory as download directory.

Mmm. We will need logs for that. And sadly that involves running `adb logcat` on both devices at the same time. It is feasible but a bit painful. If both devices are rooted you can get logs from the device itself using https://f-droid.org/es/packages/com.pluscubed.matloglibre/. We need debug logs enabled in KOReader and filtered by that name, `KOReader`, in the app

Also please identify which log belongs to the publisher and which one is the suscriber log.

**Comment by Galunid** [comment]
I tried it between Clara HD/Onyx Nova 2/Xiaomi Mi A2 lite and it doesn't work. It used to work with my Samsung Galaxy S5 Mini (android 4.4). So it's perhaps something to do with android version?

**Comment by pazos** [comment]
As far as I'm concerned I would be fine removing the plugin :)

**Comment by Zeyadas** [comment]
Removing the plugin?? I'm fine without it since I don't use it but it will be great if I can retrieve files from other cloud storage (Google drive or Microsoft onedrive).

**Comment by Frenzie** [comment]
There's effectively no overlap between zsync and something like that.

**Comment by pazos** [comment]
> Removing the plugin?? I'm fine without it since I don't use it but it will be great if I can retrieve files from other cloud storage (Google drive or Microsoft onedrive).

My suggestion *for you* would be take advantage of the huge Android ecosystem and use whatever app that does the sync for you **outside** KOReader. And then use KOReader to read :)

KOReader also has a import button on the **+** FM menu. You can use it to import documents from content providers like Dropbox, Google Drive or OneDrive, among others, given that that particular app is installed on your device. Remember you can't import documents on non-writable folders, hence my first recommendation.

My suggestion *for people with other, **embedded**, platforms* would be use [rclone](https://rclone.org/) on each device - managed as you want, including running a shell script from KO, as then use KOReader to read :)

**Comment by Zeyadas** [comment]
Didn't know about the import, I'll try it soon.
It'll do the trick if it works. 
And never thought about (sync app), do you recommend one?

**Comment by Zeyadas** [comment]
The import worked perfectly, and as you said it should be on writable folder (device memory).

**Comment by Frenzie** [comment]
> And never thought about (sync app), do you recommend one?

As far as I know just about anything will do. If you're more averse to "the cloud" you could try Syncthing (which incidentally you can also run on your Kobo, but you might need to be a bit technically inclined for that). Otherwise the best choice is probably whatever you're already using? Your message gave me the impression you've already got OneDrive and Google Drive.

**Comment by Zeyadas** [comment]
Syncthing is more than fine. That's exactly what I was thinking about. Thanks. 

> (but you might need to be a bit technically inclined for that).

I don't think I'm going to use this, I wish I have a kobo (or some E-ink reader). All I have is an old android tablet.

**Comment by Frenzie** [comment]
Closing on account of https://github.com/koreader/koreader/commit/a665901c51ffb70003db0b64a54a65f038adc90a.

**Comment by Iey4iej3** [comment]
> (which incidentally you can also run on your Kobo, but you might need to be a bit technically inclined for that).

By the way, is there an up-to-date tutorial for using `syncthing` on Kobo?

**Comment by Frenzie** [comment]
I wrote down how you can run Syncthing in https://www.mobileread.com/forums/showthread.php?p=4007007#post4007007

**Comment by Iey4iej3** [comment]
> I wrote down how you can run Syncthing in https://www.mobileread.com/forums/showthread.php?p=4007007#post4007007

Thanks. I don't know whether I use it incorrectly. I set "ignore permission" and "receive only" in Syncthing, and disabled `sdr` files as in https://github.com/koreader/koreader/issues/4831#issuecomment-475885999. I see that many files are modified (I don't highlight or take notes), probably by koreader, and I have to revert local changes again and again. I don't know whether this is something expected.

**Comment by Frenzie** [comment]
Files are never modified (although you can optionally write highlights into PDF).

**Comment by Iey4iej3** [comment]
Thanks. The real reason for these local changes seems to be the [2 second precision issue](https://forum.syncthing.net/t/raspberry-pi-some-receive-only-files-always-get-marked-as-local-additions/16246/11).
