### ISSUE TITLE
When looking up in the dictionary a crash occurs

### ISSUE THREAD

**Issue by hombretranquilo** [koreader/koreader#7209]
* KOReader version: 2021.01.1-9
* Device: PB740, Kobo Aura HD

Loking up in dictionary results in a segmentation fault. Tested on PB740 and Kobo Aura HD.
I am not a developper, but maybe related to #7166?
[crash.log](https://github.com/koreader/koreader/files/5893481/crash.log)

**Comment by Frenzie** [comment]
Moreover, it was mentioned right there already. ;-) https://github.com/koreader/koreader/pull/7166#issuecomment-769678237

**Comment by poire-z** [comment]
Same stacktrace indeed. I guess this happens when you switch to next result, right? The first result is displayed fine?
(It is followed by a segmentation fault, but may be this is just due to the program exiting abnormally and PocketBook pecularities... or it's another thing.)

**Comment by hombretranquilo** [comment]
I have just seen that @poire-z reported this. Sorry for duplicate issue. 
Yes, switching between dictionaries produces the crash, and yes, segmentation fault seems to be a new peculiarity of the pocketbook, since there is not segmentation fault at the kobo crash.log.
[crashaurahd.log](https://github.com/koreader/koreader/files/5893752/crashaurahd.log)

**Comment by NiLuJe** [comment]
Just got back home, I'll take a look at it later tonight ;).
