### ISSUE TITLE
Failure to export highlight with PDF

### ISSUE THREAD

**Issue by warpedwood** [koreader/koreader#7217]
- KOReader version: 2021.01.1
- Device: Pocketbook InkPad 3

**Issue**

When I transfer a PDF file to my computer, some highlights I made with KOReader are no more available, but they remain visible in KOReader. 

**Steps to reproduce**

Highlight text in a PDF, transfer it by USB cable, open it and some parts are not highlighted while they remain highlighted in KOReader. 

Thank you for your feedback! 

crash.log (if applicable)
[crash.log](https://github.com/koreader/koreader/files/5900243/crash.log)

**Comment by NiLuJe** [comment]
There's a setting (in the Document tab, I would imagine) that essentially says "burn highlights into the PDF", and is not enabled by default, because, duh'.

**Comment by warpedwood** [comment]
Thank you for your answer. I found the setting "Save document (write highlights into PDF)" and mine is set on "Prompt". I tried with "Always" and there were no difference. Maybe I should disable it

**Comment by NiLuJe** [comment]
(Not necessarily directly MµPDF related, just tagging this as "PDF mess" ^^).

**Comment by pazos** [comment]
@warpedwood: you need to add a new change for the actual highlights to be commited

**Comment by warpedwood** [comment]
Thank you for your answer. I'm sorry I'm not sure to understand. What kind of change do I have to add?

**Comment by NiLuJe** [comment]
That option only takes for highlights made *after* it was enabled.

**Comment by warpedwood** [comment]
Thank you for your help, but I enabled it and some highlights were still missing after having transfered the PDF to my computer

**Comment by pazos** [comment]
Take a delorean, go back to the past, enable the setting **before** making highlights, profit. :smile:

**Comment by warpedwood** [comment]
Ahaha alright. It's just that I think it was enabled, that's why I'm a bit lost, but I'll try to fix it. Thanks again
