### ISSUE TITLE
OPDS browser does not show fb2 files in download dialog

### ISSUE THREAD

**Issue by avsej** [koreader/koreader#7218]
It looks like https://github.com/koreader/koreader/commit/1ef6d0b25710ad4cd1a9f963c602db3e99695611 broke the download dialog in OPDS browser. For instance, it does not show download button for `.fb2` files anymore.

Could you add some unit test that `DocumentRegistry:hasProvider` actually returns true for all these MIME types?

https://github.com/koreader/koreader/commit/1ef6d0b25710ad4cd1a9f963c602db3e99695611#diff-d0320bf0f37d184e17e15f5868aa4c9d9283627f73b4df198baa653265b60914L49-L66
```lua
        ["application/epub+zip"] = "EPUB",
        ["application/fb2+zip"] = "FB2",
        ["application/pdf"] = "PDF",
        ["text/html"] = "HTML",
        ["text/plain"] = "TXT",
        ["application/x-mobipocket-ebook"] = "MOBI",
        ["application/x-mobi8-ebook"] = "AZW3",
        ["application/vnd.amazon.mobi8-ebook"] = "AZW3",
        ["application/x-cbz"] = "CBZ",
        ["application/vnd.comicbook+zip"] = "CBZ",
        ["application/zip"] = "CBZ",
        ["application/x-cbr"] = "CBR",
        ["application/vnd.comicbook-rar"] = "CBR",
        ["application/x-rar-compressed"] = "CBR",
        ["application/vnd.rar"] = "CBR",
        ["application/djvu"] = "DJVU",
        ["image/x-djvu"] = "DJVU",
        ["image/vnd.djvu"] = "DJVU",
```

**Comment by NiLuJe** [comment]
Better question: from which OPDS server, and under which mimetype are those usually served?

**Comment by Frenzie** [comment]
Probably `application/fb2+zip`, cf. https://github.com/koreader/koreader/issues/5997. Filibusta breaks the fallback heuristics because it uses `http://www.flibusta.is/b/52079/fb2` (and not `http://www.flibusta.is/b/52079.fb2` or some such).

I'll add a few lines to deal with the sneaky discrepancy that snuck into the temporary workaround, but `["application/zip"] = "CBZ",` seems tough to defend.

**Comment by hius07** [comment]
As we are talking about flibusta, authorization doesn't work.
I entered login and password but couldn't see my account.
login:pwd@flibusta.is/opds doesn't work as well.

**Comment by avsej** [comment]
@Frenzie, @NiLuJe, maybe it would be possible to override mapping per library in the OPDS feed settings? Or even enable/disable formats. Because right now fb2 is disabled for flibusta essentially, while it is primary format of the library, every other format is converted on the fly (unless people used it directly during upload)

**Comment by Frenzie** [comment]
The FB2 thing is not the issue. Anyway, I've stuck a milestone on it; I already prepared a commit last week.

**Comment by hius07** [comment]
Thanks a lot, downloading from Flibusta and saving as fb2.zip, very well.
