### ISSUE TITLE
cannot read epub

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#7219]
* KOReader version: 2021.01
* Device: kobo

I can open the following epub file just fine using calibre's epub reader, but koreader complains about an invalid link when opening any chapter. However, that file is present in the epub...

https://www.dropbox.com/s/64vk2z7606qxrr8/error.epub?dl=0

**Comment by poire-z** [comment]
Sunday evening joys...

It has entries like:
`    <item href="english\0001 - 1.00.html" id="1.00" media-type="text/html"/>
`and in the zip:
```
EPUB/content.opf
EPUB/english/0001 - 1.00.html
EPUB/english/0002 - 1.01.html
```
So possibly the `\` that might need to be `/`, and the space should be `%20` (although I remember we might have fixed that).
Any attempt to fix that manually in the opf:
`    <item href="english/0001%20-%201.00.html" id="1.00" media-type="text/html"/>`
doesn't make it work.
And if I do the replacements as a whole, I get a segfault showing only include/lvstring.h line numbers and ImportEpubDocument as the origin, but without line numbers...

**Comment by NiLuJe** [comment]
Huh, I'll see if I can coerce a better backtrace into existence...

**Comment by Frenzie** [comment]
I think we may have seen some / vs. \ issues before but we should definitely think twice before applying any fix since it might break proper behavior.

**Comment by poire-z** [comment]
We at least did something related in https://github.com/koreader/crengine/commit/fed8da73cfdee016ebf12a32660e2586d564919e.

But in this case, I think it's simpler:
`<item href="english\0001 - 1.00.html" id="1.00" media-type="text/html"/>`
fails, but changine the media-type to the one we explicitely look for makes it all fine:
`<item href="english\0001 - 1.00.html" id="1.00" media-type="application/xhtml+xml"/>`
I get a 1500 pages books, and link from the nav.xhtml above are working.

https://github.com/koreader/crengine/blob/3bdf2e6cf89369f396dc2ff2287a04e84a3b27db/crengine/src/epubfmt.cpp#L1339-L1343

I dunno/haven't checked if the EPUB specs requires media-type="application/xhtml+xml", or if we should parse anything a bit `*/*html*` related.

(I still have to tackle these segfaults I got when hacking the opf...)

**Comment by Frenzie** [comment]
EPUB is XHTML by definition, but it's possible that EPUB3 has relaxed that. I know it tracks the living HTML5 standard, but I thought it was still using the XML serialization of it.

**Comment by Frenzie** [comment]
Also, epubcheck has a very big list of complaints, including, but not limited to:
```
ERROR(OPF-043): error.epub/EPUB/content.opf(12,77): Spine item with non-standard media-type 'text/html' has no fallback.
```
```
ERROR(RSC-001): error.epub(-1,-1): File 'EPUB/english\0001 - 1.00.html' could not be found.
```

**Comment by poire-z** [comment]
`text/html` is nowhere mentionned in:
http://idpf.org/epub/30/spec/epub30-publications.html#sec-core-media-types
https://www.w3.org/publishing/epub3/epub-spec.html#sec-cmt-supported
https://idpf.github.io/epub-cmt/v3/#sec-cmt-supported

I guess there would be no reason to add text/html, but then why note text/xhtml, application/html... :/

**Comment by Frenzie** [comment]
I'd say there's a slight difference between a proper mimetype that we support, even if technically it shouldn't be in an EPUB, and sheer nonsense.

Yet I'm still surprised at how laissez-faire calibre can be. :-)

**Comment by poire-z** [comment]
And the segfaults were cause by some recently added code, triggered when I had removed some item from the manifest, but they were still in the spine. Fixed with:
```diff
--- a/crengine/src/epubfmt.cpp
+++ b/crengine/src/epubfmt.cpp
@@ -1288,12 +1288,12 @@ bool ImportEpubDocument( LVStreamRef stream, ldomDocument * m_doc, LVDocViewCall
                 for ( size_t i=1; i<=EPUB_ITEM_MAX_ITER; i++ ) {
                     ldomNode * item = doc->nodeFromXPath(lString32("package/spine/itemref[") << fmt::decimal(i) << "]");
                     if ( !item )
                         break;
                     EpubItem * epubItem = epubItems.findById( item->getAttributeValue("idref") );
-                    epubItem->nonlinear = lString32(item->getAttributeValue("linear")).lowercase() == U"no";
                     if ( epubItem ) {
+                        epubItem->nonlinear = lString32(item->getAttributeValue("linear")).lowercase() == U"no";
                         // TODO: add to document
                         spineItems.add( epubItem );
                     }
                 }
             }
```

**Comment by zwim** [comment]
I can open the book "error.epub" in calibre (4.22.0) and get the same sort of TOC as in KOReader. But when I want to open any chapter I don't get something like
![grafik](https://user-images.githubusercontent.com/36999612/106396433-22207300-6408-11eb-9806-1d4c367e8402.png)

so I would say: The book is terrible borked.

**Comment by Frenzie** [comment]
We could consider adding a third issue template for document issues, with a reference to tools like epubcheck (i.e., if there are hundreds of reported errors it may just be the document ;-) ).

![Screenshot_2021-01-31_21-10-00](https://user-images.githubusercontent.com/202757/106396517-b8549900-6408-11eb-8e4f-1101d5e160ad.png)

**Comment by poire-z** [comment]
> I'd say there's a slight difference between a proper mimetype that we support, even if technically it shouldn't be in an EPUB, and sheer nonsense.

Well, OK, I won't add text/html - just because properly supporting text/html would mean using the improved HTMLParser instead of the XMLParser we use in the whole doc fragments stuff - so much more work that just accepting mediatype=text/html :)

Even if in this book, the "text/html" stuff might be proper XHTML:
```
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" epub:prefix="z3998: http://www.daisy.org/z3998/2012/vocab/structure/#" lang="en" xml:lang="en">
  <head/>
  <body><h1>1.00</h1>
<div class="entry-content">
<p>The inn was dark and empty.
```
Or is that really bad stuff, combining `<?xml` and `<!DOCTYPE html>` , that even Calibre get confused?

**Comment by Frenzie** [comment]
> just because properly supporting text/html would mean using the improved HTMLParser instead of the XMLParser we use in the whole doc fragments stuff - so much more work that just accepting mediatype=text/html :)

I was afraid of that. Or afraid isn't really the right word, since I'm not entirely sure it'd be a positive change regardless.

> Or is that really bad stuff, combining <?xml and <!DOCTYPE html> , that even Calibre get confused?

No, I think that looks like valid XHTML5. Which takes the `application/xhtml+xml` mimetype. A minimal XHTML5 document looks something like:

```xml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
  <head>
    <title>XHTML5</title>
  </head>
  <body>
    <p>XHTML5.</p>
  </body>
</html>
```

The `<?xml` is optional if you use the default UTF-8 encoding.

**Comment by poire-z** [comment]
Closing as _The book is terrible borked._
