### ISSUE TITLE
K4 - Right move to confirm button impossible

### ISSUE THREAD

**Issue by georgethemarmot** [koreader/koreader#7224]
* KOReader version:2021.01.1
* Device: Kindle 4 NoTouch Black (2012) - B023

#### Issue
Issue seems present in all processes that pop a virtual keyboard from screen bottom.
When input box is filled and keyboard is hidden, right move from cancel to confirm button is not possible
Eg. Cases: 
1.Calibre password entry, 
2.Dictionary lookup 
#### Steps to reproduce
1. Tools -> Calibre -> Wirelesses settings -> Set password -> Select random password in keyboard 
2. Search -> Dictionary lookup -> type word in kb 
common: -> back to hide KB-> move from input form to Cancel -> Impossible to right move to "Set password" button.

**Comment by sdx23** [comment]
Can confirm the issue -- cannot confirm any dialog that has additional inputs.

I'd like to attack this issue but didn't quite get what's going on. Apparently the confirmbox widget works as expected, the multiinputdialog however doesn't.

**Comment by Frenzie** [comment]
In a (Multi)InputDialog you're dealing with text input. Maybe there can be some solution involving the `back` action to switch between inputs and buttons. In combination with FocusManager most building blocks are *probably* there.

**Comment by poire-z** [comment]
Probably solved by #8859 or followups PRs.
