### ISSUE TITLE
Default Fit mode not being applied to manga

### ISSUE THREAD

**Issue by NO-ob** [koreader/koreader#7228]
* KOReader version: 2021.01.1, 2021.01, 2020.12
* Device: Kobo clara hd

#### Issue
When loading a manga with view set as page and Fit set to full, the manga will not be in full mode. when trying to scroll it goes down the page a bit as its not being fit to the screen so changing page requires 2 presses. It is fixed by opening the menu and clicking on full so it is applied but this has to be done for every manga

#### Steps to reproduce
-open manga
-load bottom menu
-set fit to full and hold down to set as default
-set view mode to page and hold down to set as default
-load another manga
-settings will not be applied

**Comment by Frenzie** [comment]
Incidentally, is it possible that there's a bad interaction with another setting like reflow?

**Comment by NO-ob** [comment]
I have reflow set to off so not sure if its that, ive also tried setting page crop to none and margin to small so I dont think its those either

**Comment by Galunid** [comment]
So at a quick glance `ui/data/koptoptions.lua` and `apps/reader/modules/readercropping.lua`, `apps/reader/modules/readerzooming.lua` seem to use different settings.

**Comment by Frenzie** [comment]
It was just a quick thought before testing. I can confirm the problem. It doesn't exist in 2020.11, so it's a regression in #6885.

**Comment by Frenzie** [comment]
@Galunid Concretely, I mean it was a hypothesis related to user settings, not to the code.

**Comment by NO-ob** [comment]
> It was just a quick thought before testing. I can confirm the problem. It doesn't exist in 2020.11, so it's a regression in #6885.
The 2020.11 build doesn't have the fit setting?

**Comment by Frenzie** [comment]
In 2020.11 it's in the top menu. The new part is the quickly customizable row/column navigation, the rest is a UX improvement.

**Comment by Frenzie** [comment]
Where by 2020.11 I mean something like 2012.04 – 2020.11, but that aside.

**Comment by NO-ob** [comment]
Oh okay just got confused as I installed that build and didn't see it there. Will use that older build for now thankyou

**Comment by gbyl** [comment]
> when trying to scroll it goes down the page a bit as its not being fit to the screen so changing page requires 2 presses. It is fixed by opening the menu and clicking on full so it is applied but this has to be done for every manga

I can confirm that this is issue exists with PDFs as well

**Comment by Frenzie** [comment]
It'd be quite surprising if it didn't. ^_^

**Comment by Frenzie** [comment]
Will be closed by #7463 soon.

**Comment by NiLuJe** [comment]
Man, my "avoid anything PDF-related"-fu is *strong*, I have no memory of this one ;p.
