### ISSUE TITLE
Black leftovers when long-pressing bookmarks

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7230]
* KOReader version: v2021.01.1-21-g285fc75a_2021-02-02
* Device: emulator

#### Issue

When long-pressing an entry in the list of bookmarks to get the "delete" option, the entry is highlighted in black, a dialog is shown on top (the black highlight can be seen on the sides), and when the dialog is dismissed the black highlight on the sides remains.

On my device (Kobo Aura, v2021.01.1) it looks almost the opposite: the black highlight that should be covered by the dialog shows on top of it instead, but the sides remain white. Either this has been "fixed" since then, or it's a device-specific behavior?

#### Steps to reproduce

1. Create a few bookmarks (1 is enough, but 2-3 allows more testing).
2. Go to Bookmarks.
3. Long-press one of the entries.
4. Press on Close

The highlight "behind" the dialog.
![Screenshot_1](https://user-images.githubusercontent.com/7943459/106658631-d0a9ec80-659d-11eb-80ec-ed80178845e0.png)

The leftover after closing the dialog.
![Screenshot_2](https://user-images.githubusercontent.com/7943459/106658633-d0a9ec80-659d-11eb-95ad-6e86128d4a72.png)

**Comment by hius07** [comment]
![IMG_20210202_224140~01](https://user-images.githubusercontent.com/62179190/106660002-271c2880-65a8-11eb-8b6a-066aa6893040.jpg)
The black bar is over the dialogue window in the place of the edited bookmark. (Kindle PW2)

**Comment by NiLuJe** [comment]
@Jellby: That's on purpose (-ish) ^^.

If it's properly repainted when closing the dialog, it's working as currently intended.

@hius07: On which version? Nightlies have fixed quite a few instances of theses.

**Comment by NiLuJe** [comment]
And apparently, it's *not* repainted properly when the dialog is closed, I'll look into it ;).

**Comment by Jellby** [comment]
> And apparently, it's _not_ repainted properly when the dialog is closed

That's what I meant. The black stuff left of the W in my 2nd screenshot was not there before the dialog was opened. 1st screenshot is OK, 2nd is wrong.

**Comment by hius07** [comment]
> Nightlies have fixed quite a few instance of these.

Thanks, there is no black bar over the dialogue in the latest nightly build.

**Comment by NiLuJe** [comment]
Do report it if you find other instances of similar glitches, as it's likely I've missed others ;).
