### ISSUE TITLE
FR: Add margin-size input for PDFs

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7233]
#### Current

PDF margin control options `small`, `medium`, `large` barely change the margin size. They change it only by a couple of pixels.

#### Request

CRengine has a "three-dot icon" to input a specific margin size. Is it possible to implement the same for PDFs?

**Comment by gbyl** [comment]
Reported here already: https://github.com/koreader/koreader/issues/4255

Perhaps the pixel-precision tuning feature is not feasible for PDFs. But it might not be necessary if @Frenzie 's [solution](https://github.com/koreader/koreader/issues/4255#issuecomment-427551400) to make it DPI-sensitive  is implemented

**Comment by Frenzie** [comment]
Closing as duplicate. Maybe you'd like to experiment a bit with what I suggested? :-)

**Comment by gbyl** [comment]
> Closing as duplicate.

@Frenzie The issue reported is indeed a duplicate, the solution proposed isn't. I still think it would be great to have the fine tuning option.

> Maybe you'd like to experiment a bit with what I suggested? :-)

I changed:

https://github.com/koreader/koreader/blob/850be52177a08114013fa6af11a36f1e4081918a/frontend/apps/reader/modules/readerzooming.lua#L288

to:

`local margin = Screen:scaleBySize(self.ui.document.configurable.page_margin)`

and I can confirm that the issue remains.

**Comment by Frenzie** [comment]
I was talking more about the extra variation offered by DKOPTREADER_CONFIG_PAGE_MARGIN not currently available in the GUI.

**Comment by gbyl** [comment]
@Frenzie I have set `DKOPTREADER_CONFIG_PAGE_MARGIN = 1.0` and the difference is imperceptible. It must be a DPI issue as you originally suggested.
