### ISSUE TITLE
Smaller font size causes larger (uneven) line separation

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7234]
* KOReader version: v2021.01.1-21-g285fc75a_2021-02-02
* Device: emulator

#### Issue

A `span` with `font-size: 0.8em` disrupts the line spacing and actually creates a larger line separation where it appears.

#### Steps to reproduce

Open the attached file (reaname to `.epub` if necessary) [test.zip](https://github.com/koreader/koreader/files/5920178/test.zip)
Switch between page 1 and 2.

Page 1 has:

    span.smcap {
      font-size: 0.8em;
    }

and the line spacing is uneven.

Page 2 has:

    span.smcap2 {
      font-size: 0.8em;
      line-height: 1.2em;
    }

and the line spacing is even.

The surrounding paragraphs have `line-height: 1.2em;`. One could say that the line height in `smcap2` is actually smaller because of the `0.8em` scaling, but the point is that a _smaller_ size with no explicit `line_height` breaks the texture.

![Screenshot](https://user-images.githubusercontent.com/7943459/106782165-220fb580-664a-11eb-9592-14153ff4054e.gif)

**Comment by Frenzie** [comment]
I don't see any problem? You should use a proper unitless value like `line-height: 1.2` (for example) and not `line-height: 1.2em`. This stuff is inherited.

**Comment by Frenzie** [comment]
Put another way, if you try it in any other non-broken renderer you should observe the exact same result.

**Comment by poire-z** [comment]
Don't want to get my head back into that to be able to tell you why, but Firefox renders your page1 with the same uneven line spacing:

<kbd>![image](https://user-images.githubusercontent.com/24273478/106784941-2d181500-664d-11eb-8e8f-e43bac24e44a.png)</kbd>

So, there must be a reason :) and crengine does as well.
In KOReader, for that kind of things, you have a style tweak to avoid that: `Text> Font and line heights> Enforce steady line heights`.

**Comment by Jellby** [comment]
I would understand it if the span had a larger font size (see https://stackoverflow.com/a/15135142), but not with a smaller size.

(This is, by the way, not my code, I'd never use set the line-height of the main text...)

**Comment by poire-z** [comment]
Tentative explanation - because it puzzles me too, I would think that everything about the SPAN should be smaller or identical than the same things on the surrounding text!

line-height: 1.2em being inherited => same computed value of line-height (say 19px) for the P and the SPAN.
The SPAN having a smaller font-size, and the line-height being ensured, half of (line-height - font-height) is to be put on each side of the glyphes - and the SPAN gets more of that than the P.
**The baselines being kept aligned**, the SPAN gets more of that put below it, so the extra space taken below.

**Comment by Jellby** [comment]
Hmm... You may be right, `vertical-align: text-bottom` fixes it in the calibre viewer (it causes a different issue, of course), and `font-size: 1.1em` doesn't cause the uneven spacing either, but `font-size: 0.1em` creates an even bigger gap.
