### ISSUE TITLE
Kindle: no wifi indicator in the Status bar

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7241]
* KOReader version: 2021.01.1-21
I cannot see the wifi status indicator in the Status bar settings list.
Wifi status is well displayed and managed via checkbox in the menu Gear - Network.

**Comment by hius07** [comment]
Okay, I've added `hasFastWifiStatusQuery = yes` to my `device.lua` and got it.

**Comment by NiLuJe** [comment]
c.f., https://github.com/koreader/koreader/pull/5211#issuecomment-521304139 & https://github.com/koreader/koreader/pull/6656

This *possibly* qualifies as "fast" on FW 5.x (dbus, meh :/), but not on older devices (fork()).

**Comment by hius07** [comment]
I think it'll be good to switch it on for PW2 and upper models.
I'm playing with it all day and it works very well.

**Comment by NiLuJe** [comment]
Meh, I'd like someone to actually bench it first ;).
