### ISSUE TITLE
Activate menu. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7244]
I was reading the https://github.com/koreader/koreader/pull/7242#issuecomment-774088843 and thinking about the (activate menu), it has 3 options (swipe and tab, only swipe, and only tab) the options are for both the bottom menu and the upper menu together. 
I was wondering if you could (separate the options for the menus) I mean using swipe and tab for the upper menu and only swipe for the bottom menu for example. 

And one more thing.
Using the frontlight gesture is annoying somehow it's too (close) to the left screen border. Can you please make it's tapzones (more generous) as you described it in https://github.com/koreader/koreader/pull/6918

**Comment by pazos** [comment]
> I was reading the #7242 (comment) and thinking about the (activate menu), it has 3 options (swipe and tab, only swipe, and only tab) the options are for both the bottom menu and the upper menu together.
I was wondering if you could (separate the options for the menus) I mean using swipe and tab for the upper menu and only swipe for the bottom menu for example.

Looks like [feature creep](https://en.wikipedia.org/wiki/Feature_creep)

IMHO the behaviour of menus should be coherent. No matter if that's a tap, a swipe or both. The same behaviour should be applied to each menu.

> And one more thing.

Please don't mix more than one issue/enhancement/bug report in the same ticket. It makes harder to follow what happens. Also if the feature is rejected nobody can see that as it is buried into closed issues with another, non related, title.

**Comment by Zeyadas** [comment]
Understood, thanks..
I'll add a new feature request for the frontlight thing..

**Comment by poire-z** [comment]
Note that you can tweak  these zones in a defaults.persistent.lua (do a search to find out more about that):
https://github.com/koreader/koreader/blob/cf3fed252a8f515461552e1067d8c926d2f9e95e/defaults.lua#L73-L90

I think DTAP_ZONE_CONFIG  might also be used for swipe, so it might not be a solution to make it 0.
Anyway, that's how lots of us tweak these zones to how they like them.

(But not the left edge swipe area, which is hardcoded to 1/8 screen width, which feels large enough?)
