### ISSUE TITLE
frontlight gesture tapzone. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7246]
Android tablet (Samsung T-285) and 2021.01.1 koreader version. 

Using the frontlight gesture is annoying somehow it's too (close) to the left screen border. Can you please make it's tapzones (more generous) as you described it in #6918

**Comment by pazos** [comment]
The left edge swipe area is 1/8 of the screen width. Seems large enough for most user cases. 

Since you're using a device with multitouch I would suggest you to use two finger vertical swipe to control light level. It works on the entire screen.

**Comment by Zeyadas** [comment]
> Since you're using a device with multitouch I would suggest you to use two finger vertical swipe to control light level. It works on the entire screen.

Worked perfectly. Thanks..
