### ISSUE TITLE
Highlight menu - missing Follow Link

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7248]
* KOReader version: koreader-kindlepw2-v2021.01.1-28-g3b89e32_2021-02-05
* Device: Kindle PW2

#### Issue
No item `Follow Link` in the Highlight menu opened via hold on the footnote number in fb2 book.

![Reader_2021-02-06_073034](https://user-images.githubusercontent.com/62179190/107112345-98d1cc00-685f-11eb-9dba-eb86a554e286.png)

![Reader_2021-02-06_073046](https://user-images.githubusercontent.com/62179190/107112347-9e2f1680-685f-11eb-9b8e-519843636f30.png)

![Reader_2021-02-06_073106](https://user-images.githubusercontent.com/62179190/107112348-a0917080-685f-11eb-816a-9e177a06cf2b.png)

**Comment by hius07** [comment]
`Edit highlight` menu is also missing on any highlight.

**Comment by poire-z** [comment]
Should be fixed with #7250.

**Comment by hius07** [comment]
Fixed, thanks a lot.
