### ISSUE TITLE
Highlight menu - View HTML showing up over html-code window

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7249]
* KOReader version: koreader-kindlepw2-v2021.01.1-28-g3b89e32_2021-02-05
* Device: Kindle PW2

#### Issue
`View HTML` menu item is showing up through the html-code window.

![Reader_2021-02-06_073046](https://user-images.githubusercontent.com/62179190/107112410-24e3f380-6860-11eb-9428-cf5ae4afb9c7.png)

![Reader_2021-02-06_073106](https://user-images.githubusercontent.com/62179190/107112414-28777a80-6860-11eb-87e1-7581b08655a0.png)

**Comment by poire-z** [comment]
Reproducible, but only with flash_ui enabled - only @NiLuJe can fix that :)
