### ISSUE TITLE
Dialog 'Long-press to select' - unnecessary drawing on short-press

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7251]
* KOReader version: koreader-kindlepw2-v2021.01.1-28-g3b89e32_2021-02-05
* Device: Kindle PW2

#### Issue
Bad drawing in the Text editor dialog 'Select file'
#### Steps to reproduce
Text editor - Select a file to open - short tap on any file
Then long tap and cancel

This is a photo because screenshots are ok, without black marks.

![IMG_20210206_144625~01](https://user-images.githubusercontent.com/62179190/107118694-165f0180-688b-11eb-9b87-99b6344e539d.jpg)

**Comment by hius07** [comment]
Switching off `Flash buttons and menu items` fixes the issue.

**Comment by hius07** [comment]
The same in the dialog window Long-press to select directory.

**Comment by NiLuJe** [comment]
Possibly only happens in Classic view?

**Comment by hius07** [comment]
Yes, Classic view only.
