### ISSUE TITLE
inside KOReader, the book reading rotation is added on top of the reading orientation setting in Kindle main system.

### ISSUE THREAD

**Issue by mediter** [koreader/koreader#7252]
* KOReader version: 2021.01.1
* Device: KOA 5.7.4

#### Issue
inside KOReader, the book reading rotation is added on top of the reading orientation setting in Kindle main system.

#### Steps to reproduce
1. open an ePub book in KOReader, and set the rotation to 90º
2. exit KOReader
3. setting rotation to landscape when reading a mobi format book in Kindle main system
4. exit the mobi book
5. open an ePub format book, thus opening the KOReader system again
6. the issue should occur now

![IMG_9099](https://user-images.githubusercontent.com/57368/107118592-df094880-68bc-11eb-8965-0ccb9b0acd69.jpg)
![IMG_9098](https://user-images.githubusercontent.com/57368/107118597-e3356600-68bc-11eb-85a5-90e14e341805.jpg)
![IMG_9097](https://user-images.githubusercontent.com/57368/107118604-e892b080-68bc-11eb-88db-0cdd7ae6a18b.jpg)

In my opinion, one possible solution might be to not use the reading orientation setting of Kindle main system.

**Comment by Frenzie** [comment]
You can disable that btw, otoh I think it's in Settings → Screen. But definitely something to look into for someone other than me. ;-)

**Comment by mediter** [comment]
https://user-images.githubusercontent.com/57368/107118982-7b344f00-68bf-11eb-825f-c3d64e7261d5.mp4

Also, as can be seen in the video, the rotation issue occurs, the system still recognize touch of menu items as where they should be if there is no rotation issue. Thus preventing the normal operation.

On top of this, I want to add: the gyro sensor reading is also causing issues when you hold the device while lying down, the gyro reading would force rotate book 90º. This also happens even if we have the both options enabled in Screen > Rotation

Apologies in advance for mushing 3 seemingly separate issues together. I see the 3 issues as connected with one of their underlying cause as gyro reading

**Comment by hius07** [comment]
> 5\. open an ePub format book, thus opening the KOReader system again

This seems to be KPVBooklet?

**Comment by mediter** [comment]
> > 5. open an ePub format book, thus opening the KOReader system again
> 
> This seems to be KPVBooklet?

in the latest version of KOReader, KPVBooklet is no longer included. And I just did a clean reinstallation

**Comment by hius07** [comment]
From your p.5 I understood that you open epub books directly from the Kindle home screen.
Sorry for misunderstanding.

**Comment by mediter** [comment]
> From your p.5 I understood that you open epub books directly from the Kindle home screen.
> Sorry for misunderstanding.

it is misunderstanding on my part. I thought if I don't see the KPVBooklet in documents library in Kindle main system, then the ePub files are not opened using KPVBooklet.

but
> **via KPV Booklet**
> Just open any book from the native system, all files except for mobi and txt will be opened with KOReader.

**Comment by NiLuJe** [comment]
Then that's quite likely your problem.

KPVBooklet is unmaintained, which makes it unsupported and prone to weird quirks like this one.

It likely never had been tested on a device with a Gyro, FWIW.

Use KUAL to launch KOReader.
