### ISSUE TITLE
"line-height: 0" breaks cover page

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7257]
* KOReader version:
* Device: emulator

#### Issue

Adding `line-height: 0` to the code of an SVG-wrapped cover image (and maybe other images too), breaks the cover in two pages, with just a thin strip of the image on the second page.

![Screenshot_20210207_093454](https://user-images.githubusercontent.com/7943459/107141305-24af2b00-6928-11eb-88bd-3d59c16b9bab.png)

Another line-height issue (like #7234), maybe it's not a bug, but it's not the behaviour most people would expect, I guess, and not what e.g. the calibre viewer does.

#### Steps to reproduce

Open [this file](https://github.com/koreader/koreader/files/5938519/test.zip) (rename to epub). First page is the cover with `div { text-align: center; }`. Second page is the same cover, but with `div { text-align: center; line-height: 0; }`

Any line-height below 0.75 apparently causes the issue (with default font and window size). Interestingly, with 0.75, font size 30 is affected, but not 28 or 34 (rounding error?)

**Comment by poire-z** [comment]
Where the ideas of using `line-height: 0` comes from ? Yours, or found in a real book?
I might see the idea of why, but I'm not sure.

Adding a `border:1px solid red` on the DIV on the first page causes this:
<kbd>![image](https://user-images.githubusercontent.com/24273478/107142532-00efe300-6930-11eb-9918-01238c55006c.png)</kbd>
and I think that's per-specs (or per-Firefox): the gap at the bottom is caused by the "strut" - think of it a zero-width char (so, dependant on the font-size and the line-height) that is supposed to set the minimal height and baseline (hello #7234) for the DIV - and then, the (normal, non-SVG) image has its bottom set on this baseline, so the gap below the image.
So, may be `line-height: 0` is to not have such gap.
Not sure we handle a 0 value for this correctly - and probably not in the SVG wrapper hack.

**Comment by poire-z** [comment]
At least, I thought about this strut when computing the max image height:
https://github.com/koreader/crengine/blob/781a564116af3fd3f5e55dcd8a5e0b6139d87acf/crengine/src/lvtextfm.cpp#L861-L877
```diff
                     // Compute images max height only when we meet an image,
                     // and only for the first one as it's the same for all
                     // images in this paragraph
                     ldomNode * node = (ldomNode *) src->object;
                     if ( node && !node->isNull() ) {
                         // We have to limit the image height so that the line
                         // that contains it does fit in the page without any
                         // uneeded page break
                         m_max_img_height = m_pbuffer->page_height;
                         // remove parent nodes' margin/border/padding
                         m_max_img_height -= node->getSurroundingAddedHeight();
                         // remove height taken by the strut baseline
+                        printf("strut_height - strut_baseline: %d - %d = %d\n", m_pbuffer->strut_height, m_pbuffer->strut_baseline, m_pbuffer->strut_height - m_pbuffer->strut_baseline);
                         m_max_img_height -= (m_pbuffer->strut_height - m_pbuffer->strut_baseline);
                         m_has_images = true;
                     }
```
shows:
```
strut_height - strut_baseline: 28 - 21 = 7
strut_height - strut_baseline: 0 - 7 = -7
```
(Can't reproduce what you saw with line-height: 0.75, but the height/baseline becoming negative may depend on the font and the font size?)

May be I should just ensure there that we don't go negative: an image will sit on the baseline - if the line bottom is above the baseline, we don't care: cap it to the baseline.

Text in such a DIV with `line-height: 0`:
![image](https://user-images.githubusercontent.com/24273478/107143337-d9e7e000-6934-11eb-8ec1-99297aa226ee.png)

**Comment by poire-z** [comment]
This seems to solve this issue:
```diff
--- a/crengine/src/lvtextfm.cpp
+++ b/crengine/src/lvtextfm.cpp
@@ -870,8 +870,13 @@ public:
                         m_max_img_height = m_pbuffer->page_height;
                         // remove parent nodes' margin/border/padding
                         m_max_img_height -= node->getSurroundingAddedHeight();
-                        // remove height taken by the strut baseline
-                        m_max_img_height -= (m_pbuffer->strut_height - m_pbuffer->strut_baseline);
+                        // remove height taken by the strut baseline (but not
+                        // when a small line-height would push the baseline
+                        // below the line box)
+                        int baseline_to_bottom = m_pbuffer->strut_height - m_pbuffer->strut_baseline;
+                        if ( baseline_to_bottom > 0 ) {
+                            m_max_img_height -= baseline_to_bottom;
+                        }
                         m_has_images = true;
                     }
                 }
```

**Comment by Frenzie** [comment]
For reference, Prince avoids a second page so that's probably correct:
[titlepage.zip](https://github.com/koreader/koreader/files/5938699/titlepage.zip)

**Comment by Jellby** [comment]
The `line-height: 0` is my code. I don't remember exactly why I added (it was some time ago, before I had even tried KOReader), probably to fix the bottom gap you showed in your first image, in some other reader/browser. Maybe `vertical-align: bottom`.

**Comment by Jellby** [comment]
See https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image

`display: block`, `vertical-align: middle` and `font-size: 0` are also mentioned as solutions. The only arguments against `line-height: 0` seem to be that it breaks text positioning, but that doesn't matter in this case.
