### ISSUE TITLE
Question: Run script after OTA

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7260]
I would like to run a script right after every OTA update. I know I will have to add either: `os.execute("./custom-script.sh")` or `sh custom-script.sh`. Could anyone point me to the file/location that I should modify?

**Comment by Frenzie** [comment]
The update is done in the launcher script. For example:

https://github.com/koreader/koreader/blob/ac668ecb64aea0a0b6593a864828db29ae7658b2/platform/remarkable/koreader.sh#L19-L60

**Comment by Frenzie** [comment]
But any modification of the sort you're talking about would probably be overwritten by the OTA itself. ;-)

**Comment by gbyl** [comment]
> But any modification of the sort you're talking about would probably be overwritten by the OTA itself. ;-)

True, which is why I was thinking of adding an extra line on the custom script to diff/patch `koreader.sh`. I'll be adding the line after https://github.com/koreader/koreader/blob/ac668ecb64aea0a0b6593a864828db29ae7658b2/platform/remarkable/koreader.sh#L54 We'll see if it works.

**Comment by gbyl** [comment]
**Related question:** How is KOReader triggering restarts?

I assume it is not `systemctl restart koreader` since that is disabled in the service file:
https://github.com/koreader/koreader/blob/ac668ecb64aea0a0b6593a864828db29ae7658b2/platform/remarkable/koreader.service#L13

I found this, but I don't see a way to trigger lua code from bash https://github.com/koreader/koreader/blob/82f0e681186d0107a17ef9bda636b959916e4851/frontend/ui/uimanager.lua#L1565-L1569

**Comment by Frenzie** [comment]
We never leave that script most of the time.
https://github.com/koreader/koreader/blob/ac668ecb64aea0a0b6593a864828db29ae7658b2/platform/remarkable/koreader.sh#L139-L232

**Comment by gbyl** [comment]
Thank you @Frenzie! I think this is what I was looking for:

https://github.com/koreader/koreader/blob/ac668ecb64aea0a0b6593a864828db29ae7658b2/platform/remarkable/koreader.sh#L149

**Comment by NiLuJe** [comment]
What are you trying to do, exactly?

**Comment by gbyl** [comment]
@NiLuJe Two things, I am trying to find a way to:

- restart koreader from the command line
- run a script to customize KOReader immediately after an ota update. I can do it [from my computer](https://github.com/koreader/koreader/issues/7069) already, but now that we have wifi on RM1 it would be great to be able do it entirely from the ereader.

**Comment by NiLuJe** [comment]
>     * restart koreader from the command line
> 

You can, not sanely. You can trigger a restart-via-crash with a SIGTERM, but that's it.

`kill -TERM $(pidof -s reader.lua -o $(pidof -s reader.lua))`

(The pidof dance is because some platforms start a second process to feed synthetic input events).

We could probably use a SIGUSR1 handler to fake some of that more or less sanely?

>     * run a script to customize KOReader immediately after an ota update. I can do it [from my computer](https://github.com/koreader/koreader/issues/7069) already, but now that we have wifi on RM1, it would be great to be able to do it entirely from the ereader.

I'd fake it the other way around:

Start KOReader via a wrapper script that does the tar unpack itself (either reinvent the it, or source the original script, IIRC, it's a function), and then does whatever you want.

**Comment by gbyl** [comment]
> You can't, not sanely

I was starting to suspect that, but I appreciate the confirmation. I'll play around with your suggestion too and see what I can come up with.

@NiLuJe While we are on the subject, do you know why `koreader.service` is configured to not allow restarts? https://github.com/koreader/koreader/blob/ac668ecb64aea0a0b6593a864828db29ae7658b2/platform/remarkable/koreader.service#L13

**Comment by NiLuJe** [comment]
No idea, I avoid systemd like the plague, so I have no idea how/why it works.

**Comment by gbyl** [comment]
Closing this now as all my questions have been answered.
