### ISSUE TITLE
FR: History - tap on deleted file

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7271]
Deleted files in History are greyed so we obviously know they are deleted.

Current behaviour on tap: open last book, show message 'File doesn't exist'

Proposed behaviour on tap: do nothing

**Comment by Zeyadas** [comment]
And maybe show message 'File doesn't exist' after tapping two or three times in case we didn't notice the greyed deleted file?

**Comment by WS64** [comment]
my 2 cents, keep it as it is.
It might be that the file is not deleted anymore and will open since someone did changes to the filesytem without Koreader knowing it.

**Comment by poire-z** [comment]
> will open since someone did changes to the filesytem without Koreader knowing it.

Our of curiosity, what would be a use case ?
Because nowhere we take such precautions, and I believe we should not start doing so - and keep assuming the state of things we have cached is valid.
I understand things may change on Android, but on other devices it's quite rare - and not trusting our cached view of the state means doing lot of checks for nothing.

The current issue is just that when you tap on such a non existant file, you close History and lose your position in it. Not easily solvable at the place where the callback is called, but easy if we do pass a `disabled=not file_exists` very early from where/when we build the history (the first time we use it).

**Comment by WS64** [comment]
Might be an SD card which was not inserted last time Koreader checked.

**Comment by NiLuJe** [comment]
An SD what? What's that? ^^.

**Comment by WS64** [comment]
That's the reason why I don't have a Kindle!

**Comment by poire-z** [comment]
OK, the SDCard use case could make some sense - the greyness/dim of the filename would not be updated after insertion in Classic filebrowser, but it would on Mosaic/detailed list, so, why not.

Normally, we would have the callback itself return true or false whether it has run, so put the check for file existence there. But it's all indirected into Menu/onMenuSelect/onMenuChoice, and the close_callback is called before the callback is run (which might be required by callback doing wifi stuff, dunno) - so, cleaning up all that would require much testing.

Easier solution I can propose:
```diff
--- a/frontend/readhistory.lua
+++ b/frontend/readhistory.lua
@@ -39,6 +39,9 @@ local function buildEntry(input_time, input_file)
+        select_enabled_func = function()
+            return fs.attributes(file_path, "mode") == "file"
+        end,
         callback = function()
+                -- we would normally have here:
+                -- if not fs.attributes(file_path, "mode") == "file" then return false end
             local ReaderUI = require("apps/reader/readerui")
             ReaderUI:showReader(input_file)
--- a/frontend/ui/widget/menu.lua
+++ b/frontend/ui/widget/menu.lua
 function Menu:onMenuSelect(item)
     if item.sub_item_table == nil then
+        if item.select_enabled == false then
+            return true
+        end
+        if item.select_enabled_func then
+            if not item.select_enabled_func() then
+                return true
+            end
+        end
         if self.close_callback then
             self.close_callback()
         end
         self:onMenuChoice(item) -- there we go all the way towards the callbacke
```
A bit ugly, but I don't mind :) Menu is already quite a bit of mess...

**Comment by WS64** [comment]
Just for the record, another use case, you might also have files stored on a network drive, and on some reasons that drive is not available right now...
Not very likely to happen on a dedicated reader, but still possible.
