### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by BeckyDTP** [koreader/koreader#7274]
* KOReader version: 2021.01.1-38
* Device: Redmi Note 9 Pro (Android 10)

#### Issue 1
Some menu items are not translated in the UI, although they exist in the translation files (misc languages).

#### Steps to reproduce 1
1. Launch File Browser.
2. Select the first menu and then "Settings".

![koreader-not-translated-elements](https://user-images.githubusercontent.com/22416021/107588121-5dd6ec00-6c03-11eb-8259-cb08a676340a.png)

#### Issue 2
It is not possible to translate one item in "Developer options".

Here:
https://github.com/koreader/koreader/blob/master/frontend/apps/filemanager/filemanagermenu.lua#L513

![koreader-ui-layout-mirroring](https://user-images.githubusercontent.com/22416021/107588311-bc9c6580-6c03-11eb-9e14-4358e09c9b99.png)

**Comment by poire-z** [comment]
I'll take care of Issue 2.
But Issue 1 seems not an issue:
> Some menu items are not translated in the UI, although they exist in the translation files (misc languages).

They are new, from yesterday, so they were just _not yet_ translated, or their translations wasn't yet done or pushed when the nightly was made this morning: https://github.com/koreader/koreader-translations/commit/ece45735f34865b502f8845fce1c3c78ba4486f3 (made 5 hours ago at the time of my writing).

**Comment by BeckyDTP** [comment]
Ad issue 1. You're right! I'll check in a few hours on the next nightly version.

**Comment by Frenzie** [comment]
Side note, but unless you translated them yourself and/or checked directly on Weblate over at https://hosted.weblate.org/projects/koreader/koreader/ then there's no guarantee those strings will be translated today. It's all a volunteer effort, and you're welcome to help too! ^_^

**Comment by BeckyDTP** [comment]
Of course! New strings are translated into Polish instantly, on an ongoing basis, and any errors noticed are immediately corrected or improved.

**Comment by BeckyDTP** [comment]
I confirm, that Issue 1 is resolved.

**Comment by poire-z** [comment]
Issue 2 resolved as part of #7282.
