### ISSUE TITLE
'Go to Location' vs 'Go to Page'

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7283]
I propose remove 'Go to Location'.
'Go to Page' is OK everywhere.

1. Yes, we have no fixed pages in cre documents. But reading fb2 or epub book I **do have** pages for my font and page settings.
2. Locations are not mentioned anywhere but in the 'Go to' dialog.
3. Looking into `readergoto.lua` - there are no special actions for locations (besides `curr_page`).
4. We are really talking about pages everywhere.
 
![1](https://user-images.githubusercontent.com/62179190/107870835-b8db3e00-6ea4-11eb-9980-7d78b9e509f7.png)

**Comment by poire-z** [comment]
Agreed. And the descriptive text below mentions just "pages numbers" :)

**Comment by Frenzie** [comment]
NB I want page labels some day, see the FRs for PDF and DjVu. EPUB has them
too.

**Comment by poire-z** [comment]
This was done in #1853, but I guess it makes little sense.
Added a commit to #7281 to somehow revert that.

**Comment by NiLuJe** [comment]
It made (some) sense at the time because that's how the Kindle UI exposed a similar widget and concept ;).

But, yeah, not really interesting in practice.
