### ISSUE TITLE
Line is hidden behind the status bar when using the (zoom to) function. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7297]
* KOReader version: 1.1.2021
* Device: android tablet 

When using the (zoom to) function a line (or 2?) is hidden behind the status bar, I don't know what the exact name of that zoom mode I used ( long press on it and it shows set default zoom to 3) - by the way they are all numbers - I'm talking about the one circled in red. 
![IMG_20210216_135948_605](https://user-images.githubusercontent.com/70109540/108055387-f684c600-7060-11eb-8591-51efa63cda04.jpg)
Tried it with all fit settings (full, width, height), same result. 
Tried it with (locked and unlocked) status bar, same result a line is hidden under it. 
I resolved the problem by using the zoom factor set at 0.92%. But I was wondering what is the difference between the two zoom modes (3 and 4, the one on the left) as it's named when long press on the icons. 
And I think the status bar should be considered (out of the page borders) when fitting the zoom especially when it's (locked)

**Comment by NiLuJe** [comment]
It shouldn't, *unless* you have the "reclaim bar height" setting enabled.

That's not to say that there isn't any weird interaction with various zoom modes, as there very well might be. But double-checking that would be a good start :).

**Comment by Frenzie** [comment]
Generally speaking any "full" type of zoom shouldn't be combined with "continuous."

**Comment by Zeyadas** [comment]
> It shouldn't, unless you have the "reclaim bar height" setting enabled.

Worked perfectly after disabling the reclaim bar height,

> check if the issue doesn't magically resolve itself when paging forward/backward a couple of times.

It didn't by the way. 

> Generally speaking any "full" type of zoom shouldn't be combined with "continuous."

I don't use the continuous view mode it's really annoying (at least for me), but it was great on Adobe reader (on windows) combined with (auto scrolling) where you can control the scrolling speed.

**Comment by NiLuJe** [comment]
> > It shouldn't, unless you have the "reclaim bar height" setting enabled.
> 
> Worked perfectly after disabling the reclaim bar height,

Cool, then everything's behaving as expected, then :).

----

>
> > check if the issue doesn't magically resolve itself when paging forward/backward a couple of times.
> 
> It didn't by the way.

For future reference, toggling the "reclaim bar height" settings in a PDF/DjVu *does* require crossing an in-document page-boundary to properly take ;).
