### ISSUE TITLE
Using Android soft keys for flipp/turn page. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7299]
As I know (I wish I'm right) in koreader we can completely ignore the (back) key on android devices. 
Can you make the android soft keys (back and switch apps buttons) to behave as physical keys for flipping/turning pages in koreader? With the ability to invert the keys. 

![IMG_20210216_151245_088](https://user-images.githubusercontent.com/70109540/108062096-5b90e980-706a-11eb-8526-969cbe32d91d.jpg)

**Comment by pazos** [comment]
You can remap the back button.  AFAIK not the recents button.

See https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys
