### ISSUE TITLE
FR: More precise control of paragraph spacing

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7303]
**Does your feature request involve difficulty completing a task?**
Currently paragraph spacing options supported from the menu are `1em` and `0.5em`. However, a variety of other style values (e.g. line height embedded in font) often interact with this making it too wide and I find using a `koreader/styletweaks/paragraph-spacing.css` file with the following content helps:

```css
p + p {
     margin-top: 0.25em !important;
}
```

**Describe the solution you'd like**
An option from the menu to customize paragraph spacing with `0.25em` increments.

**Additional context**
It would be ideal to have a similar solution to the one proposed [here](https://github.com/koreader/koreader/issues/4255#issuecomment-773394002) for the PDF-margin issue (based on [this feature](https://github.com/koreader/koreader/pull/7104))

**Comment by poire-z** [comment]
Mhhh, this will have to stay a style tweak.
The other PRs are about global settings (and so is the line height, a global setting that apply to each line handled by the line layout code).
For paragraphs, the code can't know if a block is what you consider a paragraph or just some random block - and that kind of stuff shouldn't be harcoded. Anyway, this would be much much work, not worth it when it can easily be handled via style tweaks.
So no fine tuning number picker.

(And in my experience - not a fan of spacing between paragraphs, but a fan of text-indentation on first paragraph line - we can't even trust publishers to properly use `<p>`, some put titles as P, some put separators as empty P, some wrap each P in a DIV, so P+P won't apply... I most often have to rely on a custom made Book style tweak after inspecting the HTML...)

So, either this should be left to user style tweaks, or add a few intermediate in that "Spacing between paragraphs" submenu (but there's room for 1 more before we reach the critical 5 items we don't want to exceeed to let room below to show its effect on the book text).
Or let the `No spacing`, and add a `Spacing >` submenu with 0.2em, 0.4em, 0.6em, 0.8em 1em.

**Comment by gbyl** [comment]
> (And in my experience - not a fan of spacing between paragraphs, but a fan of text-indentation on first paragraph line - we can't even trust publishers to properly use <p>, some put titles as P, some put separators as empty P, some wrap each P in a DIV, so P+P won't apply... I most often have to rely on a custom made Book style tweak after inspecting the HTML...)

Very well put. That has been exactly my experience as well.

> add a few intermediate in that "Spacing between paragraphs" submenu (but there's room for 1 more before we reach the critical 5 items we don't want to exceeed to let room below to show its effect on the book text).

If that isn't too much work, please go for it. Having values 0.25em, 0.5em, 0.75em, and 1em would probably be enough. Otherwise, styletweaks is always available.

Sidenote: Thank you for your hard work with the ToC ticks/markers!

**Comment by gbyl** [comment]
FR likely to remain a styletweak
