### ISSUE TITLE
FR: Would it be possible for a psvita port?

### ISSUE THREAD

**Issue by EnglishPatchFanatic** [koreader/koreader#7305]
PSVita is a Handheld Gaming Console released on 2012.

With the PSVita unlocked, it is now possible to make homebrews for it.

The console lacks an app that is able to read e-book files, and I would like to request a port of this amazing app to the psvita, but of course, if you think that this port is an impossible task, I'll concede and never mention any of this again.

Thank you so much for reading my request. Have a great day, and keep up the good work! This app is really a killer app and would like to see this on the Vita someday!

**Comment by NiLuJe** [comment]
Not without *considerable* efforts (albeit somewhat easier if someone already ported SDL2 to the Vita), for a very tiny user base.

In any case, not happening without an actual maintainer to actually maintain it long-term.

**Comment by EnglishPatchFanatic** [comment]
SDL2 and SDL1.2 has been ported to the Vita but the latter about an actual maintainer is something I'm not sure yet.

**Comment by EnglishPatchFanatic** [comment]
SDL2 and SDL1.2 has been ported to the Vita but the latter about an actual maintainer is something I'm not sure yet.

**Comment by EnglishPatchFanatic** [comment]
SDL2 and SDL1.2 has been ported to the Vita but the latter about an actual maintainer is something I'm not sure yet.

**Comment by pazos** [comment]
Porting to new targets is a matter of somebody wanting to do the task and putting the effort until completion. The task at hand *sounds* doable with the hardware, skills, motivation and a lot of time.

If you or somebody else wants to contribute the code we will review it. Sounds fun. Even in that case I'm not sure if we want to publish it, release binaries for it and support it. But sure, if somebody does a decent port and everything works, *why not?*

Keep in mind that the Vita runs a OS based on BSD, so the first step would be check that everything works fine on a native BSD build. Then setup a cross compiler and prepare for the nightmare. (using linux compat for BSD is cheating, as I'm not sure the vita has one of those)
