### ISSUE TITLE
FR: Provide keybindings to zoom in and out

### ISSUE THREAD

**Issue by stormwatch** [koreader/koreader#7308]
**Does your feature request involve difficulty completing a task? Please describe.**
I believe the only way to zoom in or out is to pinch the touch screen. I have a K4 device with buttons and I'd like to be able to zoom in and out.

**Describe the solution you'd like**
 If it wouldn't be too much of a hassle to implement, I'd like to be able to zoom with the buttons too. Maybe bind the zoom functionality to one of:
1. the upper left and right pager buttons.
2. the lower left and right pager buttons.
3. the left pager buttons
4. the right pager buttons 

**Describe alternatives you've considered**
I cannot think of any alternatives right now off the top ff my head except from buying a touch device.

Thank you

**Comment by Frenzie** [comment]
You should be able to select a font size through the bottom menu. Press enter/action to bring it up while in the reader.

**Comment by stormwatch** [comment]
Thank you. Will that also work with pdf and djvu files?

**Comment by Frenzie** [comment]
You should be able to select all available zoom modes that way, yes. But free zoom is not currently supported.
