### ISSUE TITLE
History classic mode - date/time alignment

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7316]
I am not happy with the broken date/time alignment.
Can a leading zero be added to the one-digit hour please?

![1](https://user-images.githubusercontent.com/62179190/108590814-2805d600-736e-11eb-9806-eb62008c7ca9.png)

**Comment by Frenzie** [comment]
You can also add spacing. A 0 is the brutalist option. :-P

**Comment by hius07** [comment]
Okay, let it be spacing.

**Comment by NiLuJe** [comment]
This might require more finagling, since I imagine it's the same code used everywhere, and actually *not* showing padding was a feature-request...

**Comment by NiLuJe** [comment]
Fun fact: Classic History is the sole user of that codepath.
