### ISSUE TITLE
History - page selector greyed

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7317]
At first call of the multipage History 'Page 1 of 4' text is greyed. Should not.

![2](https://user-images.githubusercontent.com/62179190/108592036-7b7b2280-7374-11eb-851c-207aed30c935.png)

**Comment by NiLuJe** [comment]
Huh, that's a weird side-effect from https://github.com/koreader/koreader/commit/6132e8c904c9e019bfd08e6b534306a9decd416d

**Comment by NiLuJe** [comment]
Or... not o_O.

**Comment by NiLuJe** [comment]
Or, yes, actually, but specifically the menu bits, which makes no sense :?.

**Comment by NiLuJe** [comment]
Yep, got it. (setting the enabled flag directly doesn't flip the dim state, we need to use the actual enable/disable method).
