### ISSUE TITLE
Dictionary feature broken: shows empty pages

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#7318]
* KOReader version: v2021.02-1-g995668a_2021-02-18/ 
* Device: KA1

#### Issue
I have 4 dictionaries installed. When I look up a word and then tap forward (not using <</>>), my second and third dictionary show empty results (see picture below) when:

* my first dictionary needs 2 pages to explain a word, my second dictionary is empty.

* my first dictionary needs 3 or more pages to explain a word, my second & third dictionary is empty.

My first & fourth dictionary is never empty.

![Reader_2021-02-20_105959](https://user-images.githubusercontent.com/32645430/108591914-664dc600-736b-11eb-829d-043912a036dc.png)

**Comment by Markismus** [comment]
I've uploaded some Koreader optimized dictionaries [here](https://e.pcloud.link/publink/show?code=kZDhJ7ZBRkwNE50R4hz731AWB2RAb2Gmg3X). Could you please check whether it is your dictionary or Koreader acting up?
They're zipped, so please unzip them first.

**Comment by poire-z** [comment]
You're not saying: is this something new when updating KOReader ? or something that happens with previous versions ?

Can't reproduce.
Can you see what what kind of dicts (text or HTML?) are your 1st, 2nd, 3rd, 4th :) And see if by re-ordering them, you can guess a pattern of the kind of transition with which this happens (say, 1:text > 2:text or 1:html > 2:text). This will help understanding and fixing it.

**Comment by poire-z** [comment]
OK, I can reproduce it: text dict > text dict.
Feels like the scroll position is not reset :/ so if the 1st result has 3 pages and on the 3rd page you tap to go to next result, you're on page 3 of next result: if the result is smaller than that: no content.

Pinging @NiLuJe , and re-mentionning my comments about this ugly, complex, uneeded change :/ https://github.com/koreader/koreader/pull/7212#issuecomment-770263533 https://github.com/koreader/koreader/pull/7166#issuecomment-779794306

**Comment by gerhaher** [comment]
I updated KOReader  a week ago (before that: several months ago (sep, oct, nov?)). Noticed the issue today.
I can reproduce it on my android.

I have used these dictionaries for a long time with no problem. Downloaded from here: http://download.huzheng.org/bigdict/

First dict: Oxford Advanced Learner's Dictionary 8th Ed.
Second: Merriam-Webster's Collegiate 11th Ed. (En-En)
Third: Webster's Third New International Dictionary, Unabridged (En-En)
Fourth: Gcide

After playing with the order: it is the first three that are the problem. If I place gcide or @Markismus Oxford advanced Learner's dictionary in between they are OK.

Questions to @Markismus:
Is the Oxford Advanced Learner's Dictionary on your page the same (except later ed) as the one I have used (as many words)? Your has much much smaller size.
And what about the Webster abridged 3? The formats on your page can't be used on KOreader, can they?

**Comment by NiLuJe** [comment]
Yep, trivial fix because of internal behavior differing between ScrollTextWidget & ScrollHtmlWidget, despite the similar API.

**Comment by Markismus** [comment]
@gerhaher No entries were removed, rather the script removes the nested blockquotes. 

The Oxford dictionaries have a rather large amount of nested blockquote-blocks. So an entry with 3 meanings would have [blockquote][blockquote][blockquote][blockquote]......[/blockquote][/blockquote][/blockquote][/blockquote] around it. It reduces the dictionary size considerably. 

The script also changes the tag involved with text color, which reduces the size a small bit.
