### ISSUE TITLE
Dictionnary vs Wikipedia? + PetitRobert?

### ISSUE THREAD

**Issue by LeClemo** [koreader/koreader#7319]
* KOReader version: 2021.02
* Device: Pocketbook 740/Inkpad 3

Hi everyone!

I'm new to ereaders and I got myself a Pocketbook Inkpad 3 Vivlio rebrand a few days ago. As I was well informed about ereaders and ways to pimp it, I installed the original Pocketbook firmware instead of the Vivlio's one and wanted to get Koreader too.
That done, I started discovering it, doing ajustments here and there.

However, I couln't load any (french) dictionnary from Koreader, even with Wi-Fi enabled. So I went here to get the real thing and downloaded XML Littré in Stardict format. I dragged the files to `applications/koreader/data/dict`.

Everything worked fine until I started research Wikipedia. Koreader asks for Wi-Fi authorization, that I give, and then gets completely bugged (like freezed) when I tap again on the Wikipedia's link. Then, the only way to escape is to go for the home button to Pocketbook's firmware...

When I disinstall `.ifo`, `.idx` and `.dict` in the `/dict` directory everything gets back to normal for a Wikipedia entry search.

That's for that.

What's more, I'd like to install `PetitRobert2007` or `PetitRobert2003` but I only found `.tar.bz2` files [here](https://cod-box.net/boox-onyx-koreader-tutoriel-telecharger-dictionnaire-francais-tiers-xmlittre-french-dictionnaire-de-lacademie-etc/) and I have absolutely no idea how to convert those files into Stardict format. Also, I found `.lua` tweak files in #3585 for those dictionnaries, but no sign of any `.ifo` downloadable files.

@poire-z You seem like you're kind of aware about dictionnaries issues from what I saw. Can you help?

**Comment by Frenzie** [comment]
Setting aside that those sound of questionable legality, bz2 is just
another compression format like zip. 7-zip can presumably deal with it.

**Comment by LeClemo** [comment]
Thanks Frenzie, yes for sure I dealt with that to decompress the file, but the `.tar` format is unusable on Koreader anyway...

**Comment by poire-z** [comment]
Just un'tar this .tar :) In the tar must be the .ifo and other files.
(there's 2 level of compression : bz2 > tar > the final files)

Also put each dict's files in a subdirectory of `koreader/data/dict/` to keep things clean, like shown at:
https://www.mobileread.com/forums/showthread.php?p=4088026&highlight=ifo#post4088026

No idea about the bad interactions between dicts & Wikipedia... Shouldn't happen.

**Comment by NiLuJe** [comment]
The Wi-Fi thing just sounds like the usual "Wi-Fi being terrible on PB" issue?

**Comment by pazos** [comment]
> The Wi-Fi thing just sounds like the usual "Wi-Fi being terrible on PB" issue?

Yep. Wi-Fi don't work in some models (maybe all of them?). The behaviour is described in OP: the system "hangs"  after pressing the confirm button to enable wifi. After a timeout (15s?) the same confirmbox is displayed again. The only way to get out of the loop is to press cancel or return to PB home.

I have a PB sitting here without any use. If somebody has some clue of what's happening I could give it a try.

**Comment by NiLuJe** [comment]
The "retry when Wi-Fi is up" logic is probably not helping here, might want to shortcut those on PB?

(e.g., `runWhenOnline` & friends in frontend/ui/network/manager.lua).

**Comment by LeClemo** [comment]
@poire-z Indeed, I wasn't aware of the second compression level! Thanks for the tip, what's more `PetitRobert2007` looks AND works great with the `.lua` tweak you made ;)

As you mentionned @NiLuJe I found those lines in `koreader/frontend/ui/network/manager.lua` but I don't know which one(s) to tweak or to disable (by deleting?). 

```
-- Helper functions to hide the quirks of using beforeWifiAction properly ;).

-- Run callback *now* if you're currently online (ie., isOnline),
-- or attempt to go online and run it *ASAP* without any more user interaction.
-- NOTE: If you're currently connected but without Internet access (i.e., isConnected and not isOnline),
--       it will just attempt to re-connect, *without* running the callback.
-- c.f., ReaderWikipedia:onShowWikipediaLookup @ frontend/apps/reader/modules/readerwikipedia.lua
function NetworkMgr:runWhenOnline(callback)
    if self:isOnline() then
        callback()
    else
        --- @note: Avoid infinite recursion, beforeWifiAction only guarantees isConnected, not isOnline.
        if not self:isConnected() then
            self:beforeWifiAction(callback)
        else
            self:beforeWifiAction()
        end
    end
end

-- This one is for callbacks that only require isConnected, and since that's guaranteed by beforeWifiAction,
-- you also have a guarantee that the callback *will* run.
function NetworkMgr:runWhenConnected(callback)
    if self:isConnected() then
        callback()
    else
        self:beforeWifiAction(callback)
    end
end

-- Mild variants that are used for recursive calls at the beginning of a complex function call.
-- Returns true when not yet online, in which case you should *abort* (i.e., return) the initial call,
-- and otherwise, go-on as planned.
-- NOTE: If you're currently connected but without Internet access (i.e., isConnected and not isOnline),
--       it will just attempt to re-connect, *without* running the callback.
-- c.f., ReaderWikipedia:lookupWikipedia @ frontend/apps/reader/modules/readerwikipedia.lua
function NetworkMgr:willRerunWhenOnline(callback)
    if not self:isOnline() then
        --- @note: Avoid infinite recursion, beforeWifiAction only guarantees isConnected, not isOnline.
        if not self:isConnected() then
            self:beforeWifiAction(callback)
        else
            self:beforeWifiAction()
        end
        return true
    end

    return false
end

-- This one is for callbacks that only require isConnected, and since that's guaranteed by beforeWifiAction,
-- you also have a guarantee that the callback *will* run.
function NetworkMgr:willRerunWhenConnected(callback)
    if not self:isConnected() then
        self:beforeWifiAction(callback)
        return true
    end

    return false
end

```

**Comment by Frenzie** [comment]
Closing, but feel free to post another comment.
