### ISSUE TITLE
ToC - page selector flash_ui

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7320]
* KOReader version: 2021.02
* Device: Kindle PW2
![1](https://user-images.githubusercontent.com/62179190/108596850-47adf600-7390-11eb-9272-8937160c8a02.png)
---
![2](https://user-images.githubusercontent.com/62179190/108596853-4f6d9a80-7390-11eb-862c-882bcc2c82b4.png)

**Comment by Frenzie** [comment]
I'm guessing you're saying the flash isn't undone? It just looks like an action screenshot. ;-)

**Comment by hius07** [comment]
> flash isn't undone

Exactly.
I've posted a few reports on that, @NiLuJe doesn't need any comments )

**Comment by NiLuJe** [comment]
Will be fixed by #7262 ;).
