### ISSUE TITLE
Skim dialog - possible minor flash_ui issue

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7326]
* KOReader version: 2021.02-20-ge582036_2021-02-21
* Device: Kindle PW2

At first, the new Skim dialog without the header and with the star button looks and works great.

#### Issue
After pressing Next (or Previous) chapter button part of it (vertical line) becomes greyed.

I made a screenshot but the issue is not visible: on the screenshot the full button is black.

**Comment by yparitcher** [comment]
see https://github.com/koreader/koreader/pull/7262#issuecomment-782778411

and #7325

**Comment by NiLuJe** [comment]
I'm going to need more details, because I can't reproduce anything (even on a PW2), and nearly everything is fenced in that widget, so if there's one place were races won't happen, it's there ;).

**Comment by yparitcher** [comment]
I can reproduce some weirdness in the progress bar (the document bleeds through) when the skimto is in transparent mode

**Comment by yparitcher** [comment]
And the button which was pressed last bleeds through to the document also

**Comment by yparitcher** [comment]
ie: part of the widget loses transparency and part does not leading to inconsistencies.

**Comment by hius07** [comment]
The latest nightly, open fb2, call Skim, press Next chapter (upper right), the vertical line inside the button becomes grey. The same with the Previous chapter button.
Immediately after the diagonal swipe the full button becames black, so the screenshot cannot show the issue.

![1](https://user-images.githubusercontent.com/62179190/108635732-9c816780-7489-11eb-8efd-6c08ac65fb4d.jpg)

**Comment by NiLuJe** [comment]
Oh, that's just ghosting.

**Comment by NiLuJe** [comment]
@hius07: On the upside, we can somewhat side-step the issue because we have a lot of other box-drawing characters at our disposal. And, in fact, the Search widget was already doing just that to get a thicker pipe, so I did the same thing here ;).

**Comment by yparitcher** [comment]
the next chapter button was just pressed. it is transparent, along with the part of the progress bar that is supposed to be filled in grey.
![ko](https://user-images.githubusercontent.com/38916402/108642695-cf6d3080-7474-11eb-9f1c-71fa6b5224dc.jpg)

**Comment by yparitcher** [comment]
holding on the skimto will then go to nontransparent (it still thinks it is transparent)

**Comment by NiLuJe** [comment]
Huh. I *definitely* can't reproduce that ;).

Is that on a PW2, too?

**Comment by yparitcher** [comment]
PW4

**Comment by NiLuJe** [comment]
That's... weird.

You don't happen to have anything custom that might squat a weird spot in the window stack on that device?

With debug logging enabled, you should see something along the lines of

```
02/22/21-01:00:39 DEBUG Explicit widgetRepaint: table: 0x48edbea8 @ ( 41 , 415 )
02/22/21-01:00:39 DEBUG setDirty: Marking as dirty widget: ReaderUI because it's below translucent widget: table: 0x46a97e40
02/22/21-01:00:39 DEBUG _refresh: Enqueued ui update for region 41 415 124 52 
02/22/21-01:00:39 DEBUG setDirty ui from widget table: 0x46a97e40 w/ region 41 415 124 52
```

(e.g., that's the unhighlight widgetRepaint, followed by its setDirty on its parent, which UIManager groks as translucent, causing ReaderUI to be repainted).

**Comment by NiLuJe** [comment]
With more context, starting from a translucent SkimTo, a tap on Next chapter does:

```
02/22/21-01:06:27 DEBUG key event => type: 1, code: 330(nil), value: 1, time: 1613952387.377949
02/22/21-01:06:27 DEBUG input event => type: 3, code: 57(nil), value: 0, time: 1613952387.377956
02/22/21-01:06:27 DEBUG input event => type: 3, code: 53(nil), value: 651, time: 1613952387.377960
02/22/21-01:06:27 DEBUG input event => type: 3, code: 54(nil), value: 439, time: 1613952387.377962
02/22/21-01:06:27 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952387.377966
02/22/21-01:06:27 DEBUG in tap state...
02/22/21-01:06:27 DEBUG set up hold timer
02/22/21-01:06:27 DEBUG adjusted ges: touch
02/22/21-01:06:27 DEBUG MovableContainer:onMovableTouch {
    ["ges"] = "touch",
    ["pos"] = {
        ["y"] = 439,
        ["w"] = 0,
        ["h"] = 0,
        ["x"] = 651,
    },
    ["time"] = {
        ["usec"] = 377966,
        ["sec"] = 1613952387,
    },
}
02/22/21-01:06:27 DEBUG key event => type: 1, code: 325(nil), value: 1, time: 1613952387.378731
02/22/21-01:06:27 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952387.378733
02/22/21-01:06:27 DEBUG input event => type: 3, code: 54(nil), value: 438, time: 1613952387.393479
02/22/21-01:06:27 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952387.393481
02/22/21-01:06:27 DEBUG in tap state...
02/22/21-01:06:27 DEBUG input event => type: 3, code: 53(nil), value: 652, time: 1613952387.409352
02/22/21-01:06:27 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952387.409355
02/22/21-01:06:27 DEBUG in tap state...
02/22/21-01:06:27 DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1613952387.473230
02/22/21-01:06:27 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952387.473231
02/22/21-01:06:27 DEBUG in tap state...
02/22/21-01:06:27 DEBUG single tap detected in slot 0 {
    ["y"] = 438,
    ["w"] = 0,
    ["h"] = 0,
    ["x"] = 652,
}
02/22/21-01:06:27 DEBUG adjusted ges: tap
02/22/21-01:06:27 DEBUG Explicit widgetRepaint: table: 0x45f80d00 @ ( 593 , 415 )
02/22/21-01:06:27 DEBUG _refresh: Enqueued fast update for region 593 415 124 52 
02/22/21-01:06:27 DEBUG setDirty fast from widget nil w/ region 593 415 124 52 
02/22/21-01:06:27 DEBUG CreDocument: goto page 9 flow 0
02/22/21-01:06:27 DEBUG update_mode: Update refresh mode fast to partial
02/22/21-01:06:27 DEBUG _refresh: Enqueued partial update for region 0 0 758 1024 
02/22/21-01:06:27 DEBUG setDirty partial from widget ReaderUI w/ NO region 
02/22/21-01:06:27 DEBUG painting widget: ReaderUI
# 02/22/21-01:06:27  readerview painting {
    ["y"] = 0,
    ["w"] = 758,
    ["h"] = 1024,
    ["x"] = 0,
} to 0 0
02/22/21-01:06:27 DEBUG CreDocument: goto page 9 flow 0
02/22/21-01:06:27 DEBUG painting widget: table: 0x45f77938
# 02/22/21-01:06:27  triggering refresh {
    ["mode"] = "partial",
    ["region"] = {
        ["y"] = 0,
        ["w"] = 758,
        ["h"] = 1024,
        ["x"] = 0,
    },
}
02/22/21-01:06:27 DEBUG refresh: partial 0 0 758 1024
02/22/21-01:06:27 DEBUG refresh: wait for completion of (previous) marker 12
02/22/21-01:06:27 DEBUG mxc_update: 758x1024 region @ (0, 0) with marker 13 (WFM: 8 & UPD: 1)
02/22/21-01:06:27 DEBUG refresh: wait for completion of marker 13
02/22/21-01:06:28 DEBUG Explicit widgetRepaint: table: 0x45f80d00 @ ( 593 , 415 )
02/22/21-01:06:28 DEBUG setDirty: Marking as dirty widget: ReaderUI because it's below translucent widget: table: 0x41b65590
02/22/21-01:06:28 DEBUG _refresh: Enqueued ui update for region 593 415 124 52 
02/22/21-01:06:28 DEBUG setDirty ui from widget table: 0x41b65590 w/ region 593 415 124 52 
02/22/21-01:06:28 DEBUG painting widget: ReaderUI
# 02/22/21-01:06:28  readerview painting {
    ["y"] = 0,
    ["w"] = 758,
    ["h"] = 1024,
    ["x"] = 0,
} to 0 0
02/22/21-01:06:28 DEBUG CreDocument: goto page 9 flow 0
02/22/21-01:06:28 DEBUG painting widget: table: 0x45f77938
# 02/22/21-01:06:28  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["y"] = 415,
        ["w"] = 124,
        ["h"] = 52,
        ["x"] = 593,
    },
}
02/22/21-01:06:28 DEBUG refresh: ui-mode 593 415 124 52
02/22/21-01:06:28 DEBUG mxc_update: 124x52 region @ (593, 415) with marker 14 (WFM: 3 & UPD: 0)
02/22/21-01:06:28 DEBUG key event => type: 1, code: 330(nil), value: 0, time: 1613952387.473339
02/22/21-01:06:28 DEBUG key event => type: 1, code: 325(nil), value: 0, time: 1613952387.473340
02/22/21-01:06:28 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952387.473341
```

**Comment by yparitcher** [comment]
```
02/21/21-19:10:23 DEBUG input event => type: 3, code: 57(nil), value: 0, time: 1613952623.86089
02/21/21-19:10:23 DEBUG input event => type: 3, code: 58(nil), value: 32, time: 1613952623.86089
02/21/21-19:10:23 DEBUG input event => type: 3, code: 53(nil), value: 951, time: 1613952623.86089
02/21/21-19:10:23 DEBUG input event => type: 3, code: 54(nil), value: 627, time: 1613952623.86089
02/21/21-19:10:23 DEBUG input event => type: 3, code: 48(nil), value: 32, time: 1613952623.86089
02/21/21-19:10:23 DEBUG input event => type: 3, code: 50(nil), value: 32, time: 1613952623.86089
02/21/21-19:10:23 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952623.86089
02/21/21-19:10:23 DEBUG in tap state...
02/21/21-19:10:23 DEBUG set up hold timer
02/21/21-19:10:23 DEBUG adjusted ges: touch
02/21/21-19:10:23 DEBUG MovableContainer:onMovableTouch {
    ["pos"] = {
        ["x"] = 951,
        ["h"] = 0,
        ["w"] = 0,
        ["y"] = 627,
    },
    ["time"] = {
        ["sec"] = 1613952623,
        ["usec"] = 86089,
    },
    ["ges"] = "touch",
}
02/21/21-19:10:23 DEBUG input event => type: 3, code: 57(nil), value: -1, time: 1613952623.168290
02/21/21-19:10:23 DEBUG input event => type: 0, code: 0(nil), value: 0, time: 1613952623.168290
02/21/21-19:10:23 DEBUG in tap state...
02/21/21-19:10:23 DEBUG single tap detected in slot 0 {
    ["x"] = 951,
    ["h"] = 0,
    ["w"] = 0,
    ["y"] = 627,
}
02/21/21-19:10:23 DEBUG adjusted ges: tap
02/21/21-19:10:23 DEBUG Explicit widgetRepaint: table: 0x72247dd0 @ ( 837 , 589 )
02/21/21-19:10:23 DEBUG _refresh: Enqueued fast update for region 837 589 177 72 
02/21/21-19:10:23 DEBUG setDirty fast from widget nil w/ region 837 589 177 72 
02/21/21-19:10:23 DEBUG CreDocument: goto page 38 flow 0
02/21/21-19:10:23 DEBUG update_mode: Update refresh mode fast to partial
02/21/21-19:10:23 DEBUG _refresh: Enqueued partial update for region 0 0 1072 1448 
02/21/21-19:10:23 DEBUG setDirty partial from widget ReaderUI w/ NO region 
02/21/21-19:10:23 DEBUG painting widget: ReaderUI
02/21/21-19:10:23 DEBUG CreDocument: goto page 38 flow 0
02/21/21-19:10:23 DEBUG painting widget: table: 0x7224c9b8
02/21/21-19:10:23 DEBUG refresh: partial 0 0 1072 1448
02/21/21-19:10:23 DEBUG refresh: wait for completion of (previous) marker 4
02/21/21-19:10:23 DEBUG mxc_update: 1072x1448 region @ (0, 0) with marker 5 (WFM: 4 & UPD: 1)
02/21/21-19:10:23 DEBUG refresh: wait for completion of marker 5
02/21/21-19:10:23 DEBUG Explicit widgetRepaint: table: 0x72247dd0 @ ( 837 , 589 )
02/21/21-19:10:23 DEBUG setDirty: Marking as dirty widget: ReaderUI because it's below translucent widget: table: 0x72241ed0
02/21/21-19:10:23 DEBUG _refresh: Enqueued ui update for region 837 589 177 72 
02/21/21-19:10:23 DEBUG setDirty ui from widget table: 0x72241ed0 w/ region 837 589 177 72 
02/21/21-19:10:23 DEBUG painting widget: ReaderUI
02/21/21-19:10:23 DEBUG CreDocument: goto page 38 flow 0
02/21/21-19:10:23 DEBUG painting widget: table: 0x7224c9b8
02/21/21-19:10:23 DEBUG refresh: ui-mode 837 589 177 72
02/21/21-19:10:23 DEBUG mxc_update: 177x72 region @ (837, 589) with marker 6 (WFM: 257 & UPD: 0)
```

**Comment by yparitcher** [comment]
I have custom plugins, but none that are displaying anything in the window stack

**Comment by NiLuJe** [comment]
That looks sane, weird.

If you disable flash_ui, does the SkimTo widget loses its transparency or something similarly broken when you do the same thing?

**Comment by yparitcher** [comment]
Yes, not related to flash_ui,

the transparency comes and goes if i press the buttons many times

**Comment by yparitcher** [comment]
probably related to #7281, sorry
pinging @poire-z

**Comment by NiLuJe** [comment]
That *feels* like it's the REAGL algo being confused as to which pixels were actually changed or not.

(That would also explain why I can't reproduce it anywhere else).

If you swap force GC16 for partials, does it help (not viable, obviously, just curious ;p).

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index fa821ca7..0d4a3891 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -724,7 +724,7 @@ function framebuffer:init()
             --       Zelda explicitly requests GC16 when flashing an UI element that doesn't cover the full screen...
             --       And it resorts to AUTO when PARTIAL, because GC16_FAST is no more (it points to GC16).
             self.waveform_flashui = C.WAVEFORM_MODE_GC16
-            self.waveform_reagl = C.WAVEFORM_MODE_ZELDA_GLR16
+            self.waveform_reagl = C.WAVEFORM_MODE_GC16
             self.waveform_partial = self.waveform_reagl
             -- NOTE: Because we can't have nice things, we have to account for devices that do not actuallly support the fancy inverted waveforms...
             if isNightModeChallenged then
```

(Or, I guess, enabling nightmode would also swap to the NM waveforms, which might handle that differently, too).

**Comment by yparitcher** [comment]
NM is broken, i will get back to you in an hour or 2 about  GC16

**Comment by NiLuJe** [comment]
FWIW, I can spam-click all day without breaking the transparency ;). (Until the moment my finger slips and triggers a hold, that is ;p).

**Comment by yparitcher** [comment]
Forcing GC16 does fix the issue.
So I guess the REAGL on rex is a little broken

**Comment by NiLuJe** [comment]
@yparitcher: Huh. Thanks for confirming my hunch.

It's still...super weird, though. On which FW version is that (I mean, there's a vague chance it might have been fixed at one point, but Kindle, FW updates, nasty, etc, etc, so it's mostly for posterity's sake ^^)?

**Comment by NiLuJe** [comment]
As another stupid experiment, you can try REAGLD, because it *should* handle mixed content better.

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index fa821ca7..38b75bfb 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -452,7 +452,7 @@ end
 local function refresh_rex(fb, refreshtype, waveform_mode, x, y, w, h, dither)
     local refarea = ffi.new("struct mxcfb_update_data_rex[1]")
     -- only for Amazon's driver, try to mostly follow what the stock reader does...
-    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLR16 then
+    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLR16 or waveform_mode == C.WAVEFORM_MODE_ZELDA_GLD16 then
         -- If we're requesting WAVEFORM_MODE_ZELDA_GLR16, it's REAGL all around!
         refarea[0].hist_bw_waveform_mode = waveform_mode
         refarea[0].hist_gray_waveform_mode = waveform_mode
@@ -474,8 +474,11 @@ local function refresh_rex(fb, refreshtype, waveform_mode, x, y, w, h, dither)
         refarea[0].dither_mode = C.EPDC_FLAG_USE_DITHERING_PASSTHROUGH
         refarea[0].quant_bit = 0;
     end
+    -- REAGLD
+    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLD16 then
+        refarea[0].flags = C.EPDC_FLAG_USE_ZELDA_REGAL
     -- Enable the appropriate flag when requesting a 2bit update, provided we're not dithering.
-    if waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
+    elseif waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
         refarea[0].flags = C.EPDC_FLAG_FORCE_MONOCHROME
     else
         refarea[0].flags = 0
@@ -724,7 +727,7 @@ function framebuffer:init()
             --       Zelda explicitly requests GC16 when flashing an UI element that doesn't cover the full screen...
             --       And it resorts to AUTO when PARTIAL, because GC16_FAST is no more (it points to GC16).
             self.waveform_flashui = C.WAVEFORM_MODE_GC16
-            self.waveform_reagl = C.WAVEFORM_MODE_ZELDA_GLR16
+            self.waveform_reagl = C.WAVEFORM_MODE_ZELDA_GLD16
             self.waveform_partial = self.waveform_reagl
             -- NOTE: Because we can't have nice things, we have to account for devices that do not actuallly support the fancy inverted waveforms...
             if isNightModeChallenged then
```

Not necessarily a great solution easier, because it's barely any better than GC16 in practice, and I've never actually seen anything using it successfully (I mean, the Kobo Aura did, and it was... not great ^^).

**Comment by yparitcher** [comment]
5.10.1.3

I will dust off my KT4 and update its koreader to confirm. it is on 5.11.1

**Comment by yparitcher** [comment]
On the PW4 REAGLD acts like GC16

**Comment by yparitcher** [comment]
Also happens with the KT4 on 5.11.1

So it is a problem with rex's REAGL

**Comment by NiLuJe** [comment]
Well, that's... interesting ^^.

Good to know that my theoretical understanding of what the hell REAGLD is for appears to hold true ;p.

**Comment by NiLuJe** [comment]
@yparitcher: I'd forgotten the `FULL` promotion in my previous patch, so, does this still behave?

```diff
diff --git a/ffi/framebuffer_mxcfb.lua b/ffi/framebuffer_mxcfb.lua
index fa821ca7..99bc7f77 100644
--- a/ffi/framebuffer_mxcfb.lua
+++ b/ffi/framebuffer_mxcfb.lua
@@ -37,6 +37,7 @@ local framebuffer = {
     waveform_full = nil,
     waveform_fast = nil,
     waveform_reagl = nil,
+    waveform_reagld = nil,
     waveform_night = nil,
     waveform_flashnight = nil,
     night_is_reagl = nil,
@@ -80,7 +81,7 @@ end
 -- NOTE: This is to avoid explicit comparison against device-specific waveform constants in mxc_update()
 --       Here, it's Kindle's various WAVEFORM_MODE_REAGL vs. Kobo's NTX_WFM_MODE_GLD16
 function framebuffer:_isREAGLWaveFormMode(waveform_mode)
-    return waveform_mode == self.waveform_reagl
+    return waveform_mode == self.waveform_reagl or waveform_mode == self.waveform_reagld
 end
 
 -- Returns true if the night waveform mode for the current device requires a REAGL promotion to FULL
@@ -416,7 +417,7 @@ end
 local function refresh_zelda(fb, refreshtype, waveform_mode, x, y, w, h, dither)
     local refarea = ffi.new("struct mxcfb_update_data_zelda[1]")
     -- only for Amazon's driver, try to mostly follow what the stock reader does...
-    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLR16 then
+    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLR16 or waveform_mode == C.WAVEFORM_MODE_ZELDA_GLD16 then
         -- If we're requesting WAVEFORM_MODE_ZELDA_GLR16, it's REAGL all around!
         refarea[0].hist_bw_waveform_mode = waveform_mode
         refarea[0].hist_gray_waveform_mode = waveform_mode
@@ -438,8 +439,11 @@ local function refresh_zelda(fb, refreshtype, waveform_mode, x, y, w, h, dither)
         refarea[0].dither_mode = C.EPDC_FLAG_USE_DITHERING_PASSTHROUGH
         refarea[0].quant_bit = 0;
     end
+    -- Enable the REAGLD algo when requested
+    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLD16 then
+        refarea[0].flags = C.EPDC_FLAG_USE_ZELDA_REGAL
     -- Enable the appropriate flag when requesting a 2bit update, provided we're not dithering.
-    if waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
+    elseif waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
         refarea[0].flags = C.EPDC_FLAG_FORCE_MONOCHROME
     else
         refarea[0].flags = 0
@@ -452,7 +456,7 @@ end
 local function refresh_rex(fb, refreshtype, waveform_mode, x, y, w, h, dither)
     local refarea = ffi.new("struct mxcfb_update_data_rex[1]")
     -- only for Amazon's driver, try to mostly follow what the stock reader does...
-    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLR16 then
+    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLR16 or waveform_mode == C.WAVEFORM_MODE_ZELDA_GLD16 then
         -- If we're requesting WAVEFORM_MODE_ZELDA_GLR16, it's REAGL all around!
         refarea[0].hist_bw_waveform_mode = waveform_mode
         refarea[0].hist_gray_waveform_mode = waveform_mode
@@ -474,8 +478,11 @@ local function refresh_rex(fb, refreshtype, waveform_mode, x, y, w, h, dither)
         refarea[0].dither_mode = C.EPDC_FLAG_USE_DITHERING_PASSTHROUGH
         refarea[0].quant_bit = 0;
     end
+    -- Enable the REAGLD algo when requested
+    if waveform_mode == C.WAVEFORM_MODE_ZELDA_GLD16 then
+        refarea[0].flags = C.EPDC_FLAG_USE_ZELDA_REGAL
     -- Enable the appropriate flag when requesting a 2bit update, provided we're not dithering.
-    if waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
+    elseif waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
         refarea[0].flags = C.EPDC_FLAG_FORCE_MONOCHROME
     else
         refarea[0].flags = 0
@@ -724,7 +731,8 @@ function framebuffer:init()
             --       Zelda explicitly requests GC16 when flashing an UI element that doesn't cover the full screen...
             --       And it resorts to AUTO when PARTIAL, because GC16_FAST is no more (it points to GC16).
             self.waveform_flashui = C.WAVEFORM_MODE_GC16
-            self.waveform_reagl = C.WAVEFORM_MODE_ZELDA_GLR16
+            self.waveform_reagl = C.WAVEFORM_MODE_ZELDA_GLD16
+            self.waveform_reagld = C.WAVEFORM_MODE_ZELDA_GLD16
             self.waveform_partial = self.waveform_reagl
             -- NOTE: Because we can't have nice things, we have to account for devices that do not actuallly support the fancy inverted waveforms...
             if isNightModeChallenged then
```

And another question:

* Does it only happen in SkimTo, or can you reproduce this on other translucent widgets (say, the SpinWidgets when setting margins, or any other MovableContainer, like the long-press on a book in the FM?).

(My thinking being that if it's fairly localized, I can easily spike the refresh queue with a REAGLD/GC16 when SkimTo is translucent on Rex/Zelda).

**Comment by yparitcher** [comment]
that patch behave like the other ones, it does flash the grey part of the progress bar black.

I cannot reproduce in the other widgets as the background does not update behind them.
Even in the skim to if i move it around it is fine, only if i change page/chapter (update the page underneath the widget), then i get the weird updates.

**Comment by yparitcher** [comment]
> (My thinking being that if it's fairly localized, I can easily spike the refresh queue with a REAGLD/GC16 when SkimTo is translucent on Rex/Zelda).

Sounds like a good idea, unless there is something else that updates under a translucent widget?

**Comment by NiLuJe** [comment]
@yparitcher: The "Search" popup can do that, I guess, but it's only simple Buttons, so there's a chance it'll behave?

**Comment by yparitcher** [comment]
Search is also broken :(

**Comment by NiLuJe** [comment]
Technically, I guess that the various ConfigDialog SpinWidgets could also actively repaint CRe if the page layout changes, but the hide/show dance we do with those probably makes that a non-issue?

**Comment by NiLuJe** [comment]
On the upside, I can't think of anything else off the top of my head ;).

**Comment by yparitcher** [comment]
> Technically, I guess that the various ConfigDialog SpinWidgets could also actively repaint CRe if the page layout changes, but the hide/show dance we do with those probably makes that a non-issue?

correct. non issue

**Comment by yparitcher** [comment]
but when launching the dialog by clicking on the more button from the bottom menu, the thin grey lines around the close & apply buttons are not drawn

**Comment by NiLuJe** [comment]
> but when launching the margin dialog by clicking on the more button from the bottom menu, the thin grey lines around the close & apply buttons are not drawn
> 
> edit: if i then make it transparent they appear, and they stay even if i make it opaque again

By "not drawn", do you mean they're invisible (and you essentially see a thin line a text peeking through the widget), or that they're drawn in white?

**Comment by yparitcher** [comment]
I think white

**Comment by yparitcher** [comment]
using koreader-kindlepw2-v2021.02-34-g37af0fd6_2021-02-23

when turning pages the letters are fuzzy (aliased) unless i refresh the page with a diagonal swipe

**Comment by yparitcher** [comment]
setting https://github.com/koreader/koreader-base/blob/eaeb52226a16b69e21231e2d85d4e775f1605e86/ffi/framebuffer_mxcfb.lua#L477-L479
```lua
    -- Enable the appropriate flag when requesting a 2bit update, provided we're not dithering.
    if waveform_mode == C.WAVEFORM_MODE_A2 and not dither then
        refarea[0].flags = C.EPDC_FLAG_FORCE_MONOCHROME
```
back to DU instead of A2 to enforce monochrome fixes the fuzzy letters

**Comment by NiLuJe** [comment]
Err, turning pages *where*? This shouldn't affect anything besides essentially menus/buttons *during* a highlight.

**Comment by yparitcher** [comment]
> Err, turning pages _where_? This shouldn't affect anything besides essentially menus/buttons _during_ a highlight.

reading epubs

**Comment by NiLuJe** [comment]
That... doesn't make sense ^^.

**Comment by yparitcher** [comment]
with a diagonal flash being 10 for clarity with `DU` it is 9.5 clear and with `A2` 7 clear.
A screenshot also refreshes so can't capture

**Comment by NiLuJe** [comment]
Still doesn't make sense: ReaderUI never refreshes a page with anything else than partial/full. A2/DU never enters the equation o_O.

**Comment by yparitcher** [comment]
A2:
![broken](https://user-images.githubusercontent.com/38916402/108798212-44b33100-755b-11eb-8cda-856f2a4cc125.jpg)
DU:
![fixed](https://user-images.githubusercontent.com/38916402/108798222-4c72d580-755b-11eb-85ea-5899ecaf0b27.jpg)

**Comment by NiLuJe** [comment]
If that's a menu, sure, but you should never hit FORCE_MONOCHROME anywhere actual ReaderUI content :?

**Comment by yparitcher** [comment]
How do i disable the footer to test if it is that?

**Comment by NiLuJe** [comment]
Err, which footer are we talking about?

**Comment by yparitcher** [comment]
regular bottom status bar

**Comment by NiLuJe** [comment]
Gah, wait, I know.

Notice the fix I sneaked in https://github.com/koreader/koreader-base/pull/1314 where C.WAVEFORM_MODE_A2 became C.WAVEFORM_MODE_ZELDA_A2? That was a very stupid bug, with an extremely harmful effect, because the old A2 constant maps to... `WAVEFORM_MODE_ZELDA_GLR16` on Zelda/Rex (i.e., partial).

Which explains why it was thoroughly screwing over ReaderUI ^^.

**Comment by NiLuJe** [comment]
As for the footer, unless you have the lock enabled, a tap should cycle it until it finally disappears ;).

**Comment by yparitcher** [comment]
> As for the footer, unless you have the lock enabled, a tap should cycle it until it finally disappears ;).

I had lock :) and its not the footer

**Comment by NiLuJe** [comment]
Also, you know what: that's *probably* what broke REAGL in the first place, too. >_<".

(The only reason I had a quick suggestion at the ready w<ith your original screenshot is because it looked *very much* like the FORCE_MONOCHROME issues on Kobo Mk. 7 ;)).

**Comment by NiLuJe** [comment]
The TL;DR being: I have a strong suspicion that https://github.com/koreader/koreader-base/pull/1314 will fix the transparency issue, too ^^.

**Comment by yparitcher** [comment]
I will test.
Do you mind giving a TLDR to the different waveform types (partial/full/REAGL) as i find it interesting and they are mostly undocumented.

**Comment by NiLuJe** [comment]
Sure, I finally did a proper writeup of that in [FBInk](https://github.com/NiLuJe/FBInk/blob/96a2cd6a93f5184c595c0e53a844fd883adfd75b/fbink.h#L196-L263) last month ;).

**Comment by yparitcher** [comment]
koreader/koreader-base#1314 fixes the issues :)

**Comment by yparitcher** [comment]
> Sure, I finally did a proper writeup of that in [FBInk](https://github.com/NiLuJe/FBInk/blob/96a2cd6a93f5184c595c0e53a844fd883adfd75b/fbink.h#L196-L263) last month ;).

how do partial and full intersect with this all?

**Comment by NiLuJe** [comment]
FULL essentially requests a flash on waveform modes that support it (in practice, mostly the G* ones do). (That's what the "will never flash" mentions refer to).

Things get a bit more fancy where REAGL is concerned:

* REAGL doesn't flash.
  * Kindle requires that all REAGL update be flagged FULL nonetheless (this *may* be a software convention to help handle manual fences).
  * That's not the case on Kobo, where we can happily send them as PARTIAL.
  * There's a very specific exception for the Kobo Aura, which was the first device to attempt to use REAGLD, and which followed the same "always FULL" convention.

**Comment by NiLuJe** [comment]
As in, you can ask for A2, FULL all you want, that'll never change its actual behavior ;).

Special mention for GC16, where FULL, in addition to the flash, also enforce the screen to update every pixels in the region, while a partial GC16 won't do anything for unchanged pixels.
