### ISSUE TITLE
Kindle Keyboard 3G US - No screensaver on sleep

### ISSUE THREAD

**Issue by neutralinsomniac** [koreader/koreader#7333]
* KOReader version: 2021.02
* Device: Kindle Keyboard 3G US

#### Issue
I'm not sure if it's supposed to, but when I flip the switch to sleep the device while koreader is open, there is zero indication that the device is asleep. I can tell that it *is* asleep because none of the buttons work until I hit the switch again, but I would've expected some indication of sleep to happen. I've tried checking every option under Screen->Screensaver to no avail.
#### Steps to reproduce
Freshly install KOReader, start it from KUAL, sleep the device with the switch. Expect to see indication that sleep is enabled, but nothing comes.

**Comment by NiLuJe** [comment]
Is it a Special Offers (ad-supported) device?

**Comment by neutralinsomniac** [comment]
It is not. I get normal (non ad) screensavers when I sleep it.

**Comment by neutralinsomniac** [comment]
Nice. Manually applied on my kindle and screensavers work now! Thank you!!
