### ISSUE TITLE
Kindle Keyboard 3G US - Can't select specific options in popover dialogs

### ISSUE THREAD

**Issue by neutralinsomniac** [koreader/koreader#7337]
* KOReader version: 2021.02
* Device: Kindle Keyboard 3G US

#### Issue
This may be user error, and if so I apologize, but I can't for the life of me figure out how to select anything other than the default-selected "Cancel" option in dialog boxes. For example, the "Go to" menu option in a book presents "Cancel/Skim mode/Location" as dialog options, and I can't get anything other than "Cancel" to be selected.

**Comment by neutralinsomniac** [comment]
ahh this is basically a dup of https://github.com/koreader/koreader/issues/7224

**Comment by Frenzie** [comment]
Thanks for the link. Closing this one then.
