### ISSUE TITLE
makefile error

### ISSUE THREAD

**Issue by blantian** [koreader/koreader#7348]
* KOReader version:new
* Device:macOS

When i git clone the code on macOS and bulid environment ready to run the code，I got a bug like this.   `Makefile:29: *** Recursive variable `PATH' references itself (eventually).  Stop.`  I google and [（url）](https://stackoverflow.com/questions/1605623/how-can-i-affect-path-in-a-makefile-variable-why-is-my-example-not-working/1605665) fix that,but  is not work.What should I do？

**Comment by NiLuJe** [comment]
Have you read and followed https://github.com/koreader/koreader/blob/master/doc/Building.md#macos ?

Do you have gnu make installed?
