### ISSUE TITLE
Standardize directory/folder to folder

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#7350]
Two more entries
https://github.com/koreader/koreader/blob/1bd4636a037ee6c8587c706c36d7e96008ec802a/frontend/ui/widget/filechooser.lua#L227-L236

_Originally posted by @hius07 in https://github.com/koreader/koreader/issues/7157#issuecomment-786705021_

**Comment by hius07** [comment]
One more
https://github.com/koreader/koreader/blob/b5de2b2a6017b71e5652f84fa2be6bcfcf106276/frontend/apps/filemanager/filemanagerbookinfo.lua#L67

**Comment by hius07** [comment]
One entry here
https://github.com/koreader/koreader/blob/03885071b97b63d9025871de2f4c16744056f0be/frontend/ui/widget/pathchooser.lua#L113

and 3 entries in
https://github.com/koreader/koreader/blob/03885071b97b63d9025871de2f4c16744056f0be/plugins/opds.koplugin/opdsbrowser.lua#L614
