### ISSUE TITLE
Can't download file from WebDAV (Synology NAS)

### ISSUE THREAD

**Issue by pihokkerr** [koreader/koreader#7354]
Hi! I have a problem with WebDAV, I can connect to my NAS, see all of my files but I cant download it I get an error that cant save the file (I tried: .epub, .mobi, .pdf).
When i checked the directory I saw that the file was downloaded but with 0 KB.

Kindle PaperWhite 3 (PW3)
Firmware version of 5.9.6.1.
KOReader version: v2021.02

crash.log:
--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 96.729/96.729/96.729 ms
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot tell in file
02/26/21-06:32:19 WARN cannot open document /mnt/us/koreader/documents/abc..pdf frontend/document/pdfdocument.lua:35: ./ffi/mupdf.lua:70: libs/libwrap-mupdf.so: undefined symbol: mupdf_error_message
02/26/21-06:32:19 WARN got error waiting for events: Waiting for input failed: 4

What could be the problem?
Thanks for your help!

**Comment by pihokkerr** [comment]
Is there any update in this issue? 
Should I upload my crash.txt file?

**Comment by Frenzie** [comment]
You could try in combination with debug and verbose.

**Comment by Galunid** [comment]
@pihokkerr To add to what NiLuJe said, `File Manager -> Top Menu -> Page 2 -> More tools -> Developer Options -> Enable debug logging -> Enable verbose debug logging`. Do what you did (download and try to open a book) and only then post the logs

**Comment by pihokkerr** [comment]
Thanks you, I enabled it. Here are the logs from crash.txt:

06/11/21-06:15:00 DEBUG refresh: fast 9 1368 80 80
06/11/21-06:15:00 DEBUG mxc_update: 80x80 region @ (9, 1368) with marker 61 (WFM: 1 & UPD: 0)
06/11/21-06:15:00 DEBUG Explicit widgetInvert: table: 0x4f406898 @ ( 9 , 1368 )
06/11/21-06:15:00 DEBUG _refresh: Enqueued fast update for region 9 1368 80 80 
06/11/21-06:15:00 DEBUG setDirty fast from widget nil w/ region 9 1368 80 80 
PING 192.168.0.1 (192.168.0.1): 56 data bytes
64 bytes from 192.168.0.1: seq=0 ttl=64 time=2.292 ms

--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 2.292/2.292/2.292 ms
06/11/21-06:15:00 DEBUG setDirty via a func from widget table: 0x464dba20
06/11/21-06:15:00 DEBUG painting widget: table: 0x46bf0838
06/11/21-06:15:00 DEBUG blitFrom 13 1372 0 0 72 72
06/11/21-06:15:00 DEBUG blitFrom 126 1372 0 0 72 72
06/11/21-06:15:00 DEBUG blitFrom 264 1372 0 0 72 72
06/11/21-06:15:00 DEBUG blitFrom 736 1372 0 0 72 72
06/11/21-06:15:00 DEBUG blitFrom 874 1372 0 0 72 72
06/11/21-06:15:01 DEBUG update_mode: Update refresh mode fast to ui
06/11/21-06:15:01 DEBUG _refresh: Enqueued ui update for region 0 0 1072 1448 
# 06/11/21-06:15:01  triggering refresh {
    ["region"] = {
        ["h"] = 1448,
        ["y"] = 0,
        ["w"] = 1072,
        ["x"] = 0,
    },
    ["mode"] = "ui",
}
06/11/21-06:15:01 DEBUG refresh: ui-mode 0 0 1072 1448
06/11/21-06:15:01 DEBUG refresh: wait for submission of (previous) marker 61
06/11/21-06:15:01 DEBUG mxc_update: 1072x1448 region @ (0, 0) with marker 62 (WFM: 3 & UPD: 0)
06/11/21-06:15:01 DEBUG key event => code: 330 (BTN_TOUCH), value: 1, time: 1623384901.128198
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1623384901.128202
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 45, time: 1623384901.128203
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1401, time: 1623384901.128205
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.128206
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG set up hold timer
06/11/21-06:15:01 DEBUG adjusted ges: touch
06/11/21-06:15:01 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 1, time: 1623384901.128324
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.128325
06/11/21-06:15:01 DEBUG AutoSuspend: onInputEvent
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 44, time: 1623384901.208663
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.208666
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1403, time: 1623384901.224596
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.224599
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1409, time: 1623384901.240682
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.240684
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1412, time: 1623384901.256770
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.256773
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 1413, time: 1623384901.272715
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.272718
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: -1, time: 1623384901.288839
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.288841
06/11/21-06:15:01 DEBUG in tap state...
06/11/21-06:15:01 DEBUG single tap detected in slot 0 {
    ["h"] = 0,
    ["y"] = 1413,
    ["w"] = 0,
    ["x"] = 44,
}
06/11/21-06:15:01 DEBUG adjusted ges: tap
06/11/21-06:15:01 DEBUG key event => code: 330 (BTN_TOUCH), value: 0, time: 1623384901.288957
06/11/21-06:15:01 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 0, time: 1623384901.288958
06/11/21-06:15:01 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384901.288959
06/11/21-06:15:01 DEBUG AutoSuspend: onInputEvent
06/11/21-06:15:01 DEBUG Explicit widgetInvert: table: 0x4f406898 @ ( 9 , 1368 )
06/11/21-06:15:01 DEBUG _refresh: Enqueued fast update for region 9 1368 80 80 
06/11/21-06:15:01 DEBUG setDirty fast from widget nil w/ region 9 1368 80 80 
# 06/11/21-06:15:01  triggering refresh {
    ["region"] = {
        ["h"] = 80,
        ["y"] = 1368,
        ["w"] = 80,
        ["x"] = 9,
    },
    ["mode"] = "fast",
}
06/11/21-06:15:01 DEBUG refresh: fast 9 1368 80 80
06/11/21-06:15:01 DEBUG mxc_update: 80x80 region @ (9, 1368) with marker 63 (WFM: 1 & UPD: 0)
06/11/21-06:15:01 DEBUG Explicit widgetInvert: table: 0x4f406898 @ ( 9 , 1368 )
06/11/21-06:15:01 DEBUG _refresh: Enqueued fast update for region 9 1368 80 80 
06/11/21-06:15:01 DEBUG setDirty fast from widget nil w/ region 9 1368 80 80 
PING 192.168.0.1 (192.168.0.1): 56 data bytes
64 bytes from 192.168.0.1: seq=0 ttl=64 time=1.916 ms

--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.916/1.916/1.916 ms
06/11/21-06:15:01 DEBUG setDirty via a func from widget table: 0x464dba20
06/11/21-06:15:01 DEBUG painting widget: table: 0x46bf0838
06/11/21-06:15:01 DEBUG blitFrom 13 1372 0 0 72 72
06/11/21-06:15:01 DEBUG blitFrom 126 1372 0 0 72 72
06/11/21-06:15:01 DEBUG blitFrom 264 1372 0 0 72 72
06/11/21-06:15:01 DEBUG blitFrom 736 1372 0 0 72 72
06/11/21-06:15:01 DEBUG blitFrom 874 1372 0 0 72 72
06/11/21-06:15:01 DEBUG update_mode: Update refresh mode fast to ui
06/11/21-06:15:01 DEBUG _refresh: Enqueued ui update for region 0 0 1072 1448 
# 06/11/21-06:15:01  triggering refresh {
    ["region"] = {
        ["h"] = 1448,
        ["y"] = 0,
        ["w"] = 1072,
        ["x"] = 0,
    },
    ["mode"] = "ui",
}
06/11/21-06:15:01 DEBUG refresh: ui-mode 0 0 1072 1448
06/11/21-06:15:01 DEBUG refresh: wait for submission of (previous) marker 63
06/11/21-06:15:01 DEBUG mxc_update: 1072x1448 region @ (0, 0) with marker 64 (WFM: 3 & UPD: 0)
06/11/21-06:15:46 DEBUG key event => code: 330 (BTN_TOUCH), value: 1, time: 1623384946.474051
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: 0, time: 1623384946.474059
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 578, time: 1623384946.474062
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 853, time: 1623384946.474065
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.474069
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG set up hold timer
06/11/21-06:15:46 DEBUG adjusted ges: touch
06/11/21-06:15:46 DEBUG key event => code: 325 (BTN_TOOL_FINGER), value: 1, time: 1623384946.474880
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.474882
06/11/21-06:15:46 DEBUG AutoSuspend: onInputEvent
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 577, time: 1623384946.537370
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.537373
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 576, time: 1623384946.553210
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.553213
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 852, time: 1623384946.569252
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.569254
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 853, time: 1623384946.617008
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.617011
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 855, time: 1623384946.632802
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.632804
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 53 (ABS_MT_POSITION_X), value: 578, time: 1623384946.648799
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 54 (ABS_MT_POSITION_Y), value: 857, time: 1623384946.648801
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.648803
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG input event => type: 3 (EV_ABS), code: 57 (ABS_MT_TRACKING_ID), value: -1, time: 1623384946.680670
06/11/21-06:15:46 DEBUG input event => type: 0 (EV_SYN), code: 0 (SYN_REPORT), value: 0, time: 1623384946.680672
06/11/21-06:15:46 DEBUG in tap state...
06/11/21-06:15:46 DEBUG single tap detected in slot 0 {
    ["h"] = 0,
    ["y"] = 857,
    ["w"] = 0,
    ["x"] = 578,
}

Error: Cant save the file.
When i checked the directory I found the file but it is only 0 KB sized.

**Comment by NiLuJe** [comment]
I'd obviously forgotten that the CloudStorage code is hilariously old and sorely lacking in the logging department... :/.

**Comment by pazos** [comment]
Closing old tickets labeled as "need more info" that are not updated anymore. Feel free to open new ones if you can reproduce on the latest release.
