### ISSUE TITLE
Close (exit) the text editor

### ISSUE THREAD

**Issue by stormwatch** [koreader/koreader#7356]
* KOReader version: installed last week probably 2021.02 or 2021.01
* Device: K4

#### Issue
Cannot reach the “Close” button

#### Steps to reproduce
Choose a setting that opens the text editor. See
![20210226_231514](https://user-images.githubusercontent.com/824211/109373036-6d089b80-788b-11eb-8b2b-7df368d5a6bc.jpg)

**Comment by poire-z** [comment]
> Cannot reach the “Close” button

I wonder how usable this TextEditor is on a non-touch device.
If it is not usable, and the only aim of a Non-Touch user would be to close it :), may be it's just simpler to disable this plugin (and may be some others) when `not isTouchDevice()` ?

**Comment by Frenzie** [comment]
It might be (made) usable on certain varieties of non-touch, but I'm not interested, so agreed. ;-)

**Comment by stormwatch** [comment]
When you "press" the button below _Reset_, the one with the up arrow, a soft keyboard pops up but anyway you won't be able to reach the _Close_ button currently

**Comment by poire-z** [comment]
I was just asking the question for now :)
May be it'd be usable if we add some bits of FocusManager here and there, but that might be really complicated (cycle thru the buttons, they the keyboard, then its individual keys?) and FocusManager has never really been our friend :/

**Comment by Thefirebeast** [comment]
Sorry to drag out a closed issue, did you ever find a way to exit the text editor? I made the same mistake and cant exit.

**Comment by stormwatch** [comment]
I never found a way to exit other than reseting the device. Since commit https://github.com/koreader/koreader/commit/a31d9446849b3864ecf425127e49dbe6b5a8a9a8 it is disabled by default so I guess we should just update koreader

**Comment by Thefirebeast** [comment]
I got it, after restarting it for the 100th time it finally went to the home screen. Thanks for the reply.
