### ISSUE TITLE
Fulltext search - flash-ui button show up

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7357]
* KOReader version: 2021.02-30
* Device: Kindle PW2

#### Issue
Forward or backward (which was pressed) button shows up over search results
![1](https://user-images.githubusercontent.com/62179190/109375298-61859680-78c4-11eb-9056-8ff5ec1ba982.png)

**Comment by NiLuJe** [comment]
You'll have to give me more details, because I can't reproduce that ;).

**Comment by hius07** [comment]
Nightly build of 26.02
Start KOReader with the last book (fb2), main menu, Fulltext search, enter any text, button Forward, that's it.

**Comment by NiLuJe** [comment]
Huh. I'll fire up the PW2 later tonight, because I can't repro on Kobo. Not that it ought to behave any differently, but, oh, well ^^.

In the "unlikely" list of things to check: does it happen with an epub?

**Comment by hius07** [comment]
Yes, the same behaviour with epub and txt.

**Comment by NiLuJe** [comment]
Oh, okay, only happens if you launch it via the actual "Fulltext search" menu entry, not DictQuickLookup ;).
