### ISSUE TITLE
Wifi checkbox is on, but menu action offers to turn it on again

### ISSUE THREAD

**Issue by Jellby** [koreader/koreader#7358]
* KOReader version: v2021.02
* Device: Kobo Aura

#### Issue

After disconnecting from a network (but leaving wifi on) the menu checkbox for wifi is activated, but tapping it opens a dialog to turn it on. The only way to turn it off seems to be connecting to a network again and then turning it off.

#### Steps to reproduce

* Activate wifi
* Connect to a network
* Before the network list disappears (if auto-dismiss is enabled), disconnect from the network
* Dismiss the network list
* The wifi checkbox is on, and tapping it doesn't turn it off

**Comment by NiLuJe** [comment]
Yeah, the Menu only checks if the Wi-Fi is *powered up* on Kobo, and I'm guessing the in-NetworkManager disconnect doesn't actually unloads Wi-Fi, unlike the Wi-Fi checkbox itself.

**Comment by Frenzie** [comment]
We do have a separate status since last year but the frontend UI code might not use it ideally in all cases yet.

**Comment by NiLuJe** [comment]
Note that there's a strong argument to be made for the AP disconnect button *not* to murder Wi-Fi (i.e., the current behavior).

Which probably means that more granularity may be needed somewhere to handle the case when isWifiOn but !isWifiConnected somewhere... Possibly in a *sub* menu, because isWifiConnected blocks (which is the whole reason for using isWifiOn in the first place).

**Comment by Jellby** [comment]
With wifi on, but disconnected, I would expect:

* Checkmark on in the menu (current behavior)
* When selecting the menu item, a dialog choice to a) turn wifi off, or b) connect to network
* Maybe some further indication that the wifi is on but not connected to any network (if not already there)

**Comment by NiLuJe** [comment]
Okay, fun twist: that state shouldn't be reachable on Kobo.

The complete_callback already check for isWifiOn but !isConnected, and forcefully kills Wi-Fi. :?

**Comment by NiLuJe** [comment]
Ah, the callback is only run for *successful* connections.

I do not remember why I changed that, besides it making sense given the name (which magically changes from complete_callback to connect_callback...).

**Comment by NiLuJe** [comment]
NetworkSettings also supports a disconnect_callback, so, we could arguably make the disconnect button tear down WiFi.

But, I'm not sure it'd be a great idea in practice? I wouldn't really know, though, I barely ever see the AP panel, I generally only use my regular set-on-stone AP ^^.

**Comment by Jellby** [comment]
For the record, this was the use-case:

* Check for updates
* Enable wifi? Yes... Choose network (not at home, and there are several available networks)
* No updates available
* This was fast, so the AP list is still on screen... choose "disconnect"
* Wifi is still on, and no way to turn it off without connecting again? :thinking:

**Comment by NiLuJe** [comment]
I don't know how prevalent the use-case of hitting disconnect from one AP and connect on another one is, which is why I'm loathe to make the disconnect button tear down Wi-Fi.

But we have the plumbing to do so, FWIW ;).
