### ISSUE TITLE
'Find a file' crashes on ' '

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7361]
* KOReader version: 2021.02-30
* Device: Kindle PW2

#### Issue
KOReader crashes on file search of ' '
#### Steps to reproduce
Filemanager - menu Find a file - enter ' ' (one space) - Current folder
##### `crash.log` (if applicable)
`filemanagerfilesearcher.lua:180: attempt to compare two nil values`

**Comment by hius07** [comment]
Not related to this bug, but maybe can be fixed as well?

Find a file is not case sensitive to latin characters.
But it is case sensitive to non-latin (Cyrillic) chars. This is not good.

BTW, fulltext search in a book is not case sensitive to cyrillic chars.

**Comment by hius07** [comment]
And one more FR for filemanagerfilesearcher:
If we have checked `Show unsupported files` in the filebrowser, we shouldn't check `DocumentRegistry:hasProvider` in the file search.
Tapping on the unsupported file in Search results would call Open with... dialog (where we have Text editor).

**Comment by NiLuJe** [comment]
(Re: non-latin & case)

Unicode case-folding is going to be... somewhat unfun from the Lua side.

I don't recall if we build utf8proc shared, in which case, a bit of FFI magic would be a good start.

**Comment by yparitcher** [comment]
#7362 should fix issue 1 and 3
