### ISSUE TITLE
OPDS - no access to the flibusta mirror

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7370]
OK, flibusta etc. are excluded from the package, but we can add them manually )

flibusta.is works fine, but is blocked in some regions.
The issue: KOReader cannot access the mirror: https://flibusta.appspot.com/opds/
CoolReader can.

**Comment by NiLuJe** [comment]
Looks like a broken mirror: headers say it's gzip encoded and set the length properly (like the master), but it actually serves uncompressed content that's much larger, which fails the length check.

I'm not quite sure where this is failing to get reproted in the Lua stack, but it's visible in HTTPie.

**Comment by NiLuJe** [comment]
Or, well, that's the other way around: it's actually serving gz content directly (c.f., curl).

**Comment by NiLuJe** [comment]
And I can't convince it not to, even via ACcept-Encoding: identity

**Comment by hius07** [comment]
The site seems has gone away so closing the issue.
