### ISSUE TITLE
PB627: KoReader UI rotated by 90' left, but touchpad responds as it was not rotated after PB FW upgrade

### ISSUE THREAD

**Issue by karoisuzvards** [koreader/koreader#7376]
* KOReader version: 2021.02
* Device: PB627, version: v.6.3.499 (released on 25/02/2020)
 
#### Issue

After upgrading PB627 to fw version v.6.3.499 - UI is rotated by 90' left, but touchscreen responds as it should (i.e. if UI wouldnt be rotated)

### Preconditions
* koreader 2021.02 installed
* PB627 firmware v.6.0.1118
 
#### Steps to reproduce

* install PB627 firmware v.6.3.499
* open koreader

### Actual result

* UI rotated by 90' left but touchscreen responds as it should

In order to keep using KOReader I rollbacked PB627 fw to v.6.0.1118 
Can help with testing if needed.

**Comment by NiLuJe** [comment]
Try stuffing

```lua
    isAlwaysPortrait = yes,
    usingForcedRotation = landscape_ccw,
```
 
(or just the first line, to be safe)

in the PB627 device block:

https://github.com/koreader/koreader/blob/master/frontend/device/pocketbook/device.lua#L422-L426

**Comment by karoisuzvards** [comment]
```
    isAlwaysPortrait = yes,
```
did the trick! Thanks!

**Comment by NiLuJe** [comment]
A bit problematic if it breaks it on older FW, though, as there currently isn't a mechanism in place to make those kinds of flags version-dependent... (PRs welcome ;)).

**Comment by karoisuzvards** [comment]
@NiLuJe would it help if I test on latest-1 and latest-2 versions with this change and thus can introduce PR?

**Comment by NiLuJe** [comment]
It would, yeah. I expect it won't work on the previous FW version, and you'd need to actually make the whole thing version dependent, but being sure of that would be a plus nonetheless ;).

**Comment by NiLuJe** [comment]
Duplicated in #7747
