### ISSUE TITLE
How to disable the "Zoom to fit page blah-blah-blah..." message?

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#7383]
* KOReader version: v2019.11
* Device: Kobo Aura H2O and Android devices

#### Issue
I couldn't find a way to disable the very annoying message that pops up every time I switch to a pdf file with Reflow enabled.

#### Steps to reproduce
I map the bottom right corner touch to "Open previous file" function for quick switching between two files. Now imagine that one book is in pdf format with such awful typesetting or large page size or small fontsize that one is forced to use the "Reflow" mechanism of Koreader. Then, every time I switch to the reflown pdf I get the annoying message "Zoom to fit page works best with..." I didn't even bother to read it because "zoom mode" is largely (i.e. unless it is set to something exotic like column, I guess) irrelevant when using Reflow, so the message shouldn't be there anyway. And zoom setting is disabled when reflow is enabled, so one cannot satisfy whatever the message is suggesting. And even if I disable reflow, change the zoom mode to something else and then re-enable reflow, then the message comes back, as long as I use continuous view. And I certainly want to use continuous view with reflow.

Ah, I see in `frontend/apps/reader/modules/readerzooming.lua:ReaderZooming:setZoomMode(mode)` -- I guess I need to comment that call to UIManager:show(InfoMessage:new..... -- but that is only on Kobo. How do I do the same on Android?

**Comment by Frenzie** [comment]
@poire-z tweaked it a bit in a slightly more recent version.

**Comment by poire-z** [comment]
Not sure I did - or I don't remember :)
I've been annoyed a few times by these messages - but PDF/Zoom/Reflow is a bit out of my comfort zone for me to do anything about that :/

**Comment by tigran123** [comment]
Ok, on Android I upgraded to the latest 2021.02 and the annoying message issue disappeared. However, a new annoying thing appeared: the bottom menu gets activated every time I swipe up from the bottom up in the bottom right corner, even when not too close to the bottom. Now think about it: if I mapped the bottom corner touch to "open previous file", that means my right thumb is always in that area of the screen and the natural way for me to scroll the page is use it, but it always opens the bottom menu instead. Is there way to say "only open the menu on bottom TOUCH, not on SWIPE"?

Also, I noticed that scrolling the page forward and then backward dispalsy "nannan" in the timing parts of the status line.

Also, overall, the scrolling seems slower than in 2019.11 so I probably wouldn't replace the old version on the Kobo devices, but my Android tablet is supermodern and ultrafast (Samsung Galaxy Tab S4 -- I only check the technology once in a few years and buy the best, so I hope nothing better has been manufactured on this planet yet :)

**Comment by tigran123** [comment]
UPDATE: Perfect! Found it in Settings/Taps and gestures/Activate menu/Only tap -- if I tick it, then it behaves exactly as I wanted! So I am happy on the Android and will now test on Kobo Aura H2O and see if the first impression was right or not, i.e. is it really slower to scroll or is it acceptable on Kobo as well. Naturally, I want to use the same version across all devices.

**Comment by tigran123** [comment]
Ok, I can close this issue, because the original problem is gone and all subsequent issues were also solved by the appropriate settings. Even on the Kobo Aura H2O I decided to switch to the latest version, but only after heavy editing of `koreader.sh`, i.e. removing about 90% of its code -- after that it became stable and fast. My version of `koreader.sh` looks like this:

```
#!/bin/sh
export LC_ALL="en_US.UTF-8"
KOREADER_DIR="${0%/*}"
cd "${KOREADER_DIR}" || exit

export LD_LIBRARY_PATH="${KOREADER_DIR}/libs:${LD_LIBRARY_PATH}"
export TESSDATA_PREFIX="data"
export STARDICT_DATA_DIR="/mnt/onboard/.adds/vlasovsoft/dictionary"
export EXT_FONT_DIR="/mnt/onboard/fonts"

# fast and dirty way of check if we are called from nickel
# through fmon/KFMon, or from another launcher (KSM or advboot)
# Do not delete this line because KSM detects newer versions of KOReader by the presence of the phrase 'from_nickel'.
export FROM_NICKEL="false"
if pkill -0 nickel; then
    FROM_NICKEL="true"
fi

# fallback for old fmon, KFMon and advboot users (-> if no args were passed to the script, start the FM)
if [ "$#" -eq 0 ]; then
    args="/mnt/sd/.Books"
else
    args="$*"
fi

export PLATFORM="mx50-ntx"
export CPU="mx50"
export PRODUCT="dahlia"
export INTERFACE="eth0"

# we keep at most 500KB worth of crash log
if [ -e crash.log ]; then
    tail -c 500000 crash.log >crash.log.new
    mv -f crash.log.new crash.log
fi

./reader.lua "${args}" >>crash.log 2>&1
exit 0
```

**Comment by NiLuJe** [comment]
Congratulations! It's now actually *slower* because it no longer swaps to a canonical rotation and sane bitdepth ;o).

**Comment by Frenzie** [comment]
I don't think it should really make a noticeable difference (and slower if anything). What problem were you seeing with the original script?

**Comment by tigran123** [comment]
@Frenzie I think I mentioned the problem with the original script a few years ago (at the time it was smaller as there was no "USBMS" -- which is also, in my opinion, unnecessary addition as the USB function is served perfectly by the KSM environment). Namely, its bitdepth setting conflicts with some combinations of the versions of firmware and KSM -- can't remember which ones exactly. If I run unmodified `koreader.sh` then it turns some of the KSM's submenus (USB) upside down. Fortunately, I can operate a Kobo Aura H2O with my eyes closed, i.e. I don't need to actually see the menu to know which part of the screen to touch, but still it is a bit inconvenient, to say the least :)

**Comment by NiLuJe** [comment]
That's a KSM issue ;o}.

**Comment by tigran123** [comment]
@NiLuJe I have version 8 and version 9 of KSM on my two Kobo Aura H2O devices. The one with version 9 works with the long `koreader.sh`, but the one with version 8 does not.
