### ISSUE TITLE
Dispatcher crash when Dispatcher attempts to set Reader settings in the FM

### ISSUE THREAD

**Issue by NiLuJe** [koreader/koreader#7388]
Btw, not sure if this is meant for here, but there is some crash going on when trying to rotate screen with long tap set at left and right corner on Aura One reader. Works ok when you have a book opened, happens just on homescreen.
https://imgur.com/a/c6hs9J7

_Originally posted by @ReaLx3m in https://github.com/koreader/koreader/issues/7304#issuecomment-791396658_

**Comment by ReaLx3m** [comment]
This might help, the bug was introduced in the build that changed the icons look. That was version 20.1 if i recall correctly.

**Comment by NiLuJe** [comment]
It probably roughly matches with when #7116 was introduced ;).

**Comment by NiLuJe** [comment]
For people following at home, this only happens when the gestures uses a *specific* rotation (e.g., one of the four from the rotation submenu).

The invert/swap/+90 entries that come earlier in the menu worked just fine (as they're not tied to a Cre/K Option).
