### ISSUE TITLE
Wrong calculation of horizontal space for the status bar when left-aligned

### ISSUE THREAD

**Issue by tigran123** [koreader/koreader#7390]
* KOReader version: v2021.02
* Device: Android

#### Issue
The status bar displays ellipsis "..." at the right end (instead of the last item(s)), even though there is plenty of space available on the right.

#### Steps to reproduce
Configure the bottom (not alternative) status bar with the following settings:

1. Do NOT display progress bar
2. Display all items at once
3. Display separator
4. Display: current page, current time, pages left in chapter, battery status, bookmark count, progress percentage, book time to read, chapter time to read, frontlight level, koreader memory usage
5. Set alignment to left

Observe that everything fits nicely and there is still quite a bit of space left on the right. So, now increase the status bar's font size from 14 to 15. Observe that the last item is replaced by "..." even though there is more than enough space to fit it and there would still be room left to go to size 16, but perhaps not 17.

**Comment by NiLuJe** [comment]
Does toggling the mode (well, toggling the bar itself in all-at-once ;)) and/or closing and reopening the document affects this in any way?

**Comment by tigran123** [comment]
No, it doesn't, i.e. everything is re-displayed in the same way, with the ellipsis "..." at the end.

**Comment by tigran123** [comment]
here are two screenshots:

![screenshot1](http://www.bibles.org.uk/screenshots/status1.jpg)
![screenshot2](http://www.bibles.org.uk/screenshots/status2.jpg)

**Comment by tigran123** [comment]
The above screenshots are taken on the tablet, where the problem occurs when changing from size 13 to size 14 and not from 14 to 15 as in the issue description (that was on the mobile)>

**Comment by NiLuJe** [comment]
I think that there isn't, actually, enough space for the next item. It might come down to very, very few pixels, though.

Try with another separator (e.g., bullets), as the pipe is one of the widest, ironically enough ;).

**Comment by tigran123** [comment]
With bullets it doesn't work either. Only with "No separator" it works. I suppose, you are probably right. Well, visually, it seems that there is more than enough space for that star and 0 next to it, but maybe not for the extra spaces around the vertical bar. Ok, I'll close the issue as it is a non-issue...

**Comment by NiLuJe** [comment]
The margin handling is super-funky, so, might be on to something... :).
