### ISSUE TITLE
menu.lua - chevrons remain after removing the last item

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7394]
![1](https://user-images.githubusercontent.com/62179190/110232678-d04b9b00-7f27-11eb-964a-b30e4b1e64b3.png)

**Comment by NiLuJe** [comment]
Yep, that was semi on purpose, I don't quite remember why, but it made sense at the time ;D.

**Comment by NiLuJe** [comment]
Yep, probably a bout of momentary insanity ^^.
