### ISSUE TITLE
FR: allow exporting notes to JSON, HTML and text

### ISSUE THREAD

**Issue by Crocmagnon** [koreader/koreader#7399]
**Does your feature request involve difficulty completing a task? Please describe.**
I want to export my highlights to all of the available formats. Currently I need to select each one in turn and tap on "Export all notes in your library" for each format.

**Describe the solution you'd like**
I'd like to be able to select multiple export formats and when tapping on "Export all notes in your library" the exporter would loop through the selected formats to write the appropriate files.

It wouldn't bother me if this were limited to "All notes in your library" since the plain text doesn't work with "all notes in this book". Although it could also just disable the "All notes in this book" option only if plain text is one of the selected formats.

**Describe alternatives you've considered**
I don't see any alternative.

**Additional context**
The export options are available under Tools > Evernote.

**Comment by Frenzie** [comment]
I feel like the subject has come up before, but I can't quite place it atm.

**Comment by Crocmagnon** [comment]
I couldn’t find any related issue but I didn’t search too long either.

**Comment by NiLuJe** [comment]
That usually comes up when discussing ripping some of that out of the Evernote plugin ;).

**Comment by pazos** [comment]
Fixed in https://github.com/koreader/koreader/pull/8944
