### ISSUE TITLE
Koreader crashes on my mobile when use ZSync

### ISSUE THREAD

**Issue by hgrain86** [koreader/koreader#7401]
Device kobo aura one
My phone redminote 8pro
When I choose (share this Document) on phone 
And (subscribe from book share) on kobo kobo crashes every time on phone and send me this report
(
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/begonia/begonia:10/QP1A.190711.020/V12.0.6.0.QGGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-03-09 08:32:44+0200
pid: 5745, tid: 5847, name: Thread-137  >>> org.koreader.launcher <<<
uid: 10678
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    r0  00000000  r1  9d2b595c  r2  b120d908  r3  00000000
    r4  b120d988  r5  dc251720  r6  0000011d  r7  00000000
    r8  00000192  r9  ab6c0620  r10 9d2b591c  r11 00000000
    ip  ee926c50  sp  9b199138  lr  9b3a358d  pc  ee8cf19c

backtrace:
    NOTE: Function names and BuildId information is missing for some frames due
    NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
    NOTE: found under the lib/ directory are readable.
      #00 pc 0005d19c  /apex/com.android.runtime/lib/bionic/libc.so (__memcpy_a53+108) (BuildId: 4f8077b25ed39d70244e32da94907afa)
      #01 pc 00004589  /data/data/org.koreader.launcher/files/libs/libfmq.so.1
      #02 pc 0000466b  /data/data/org.koreader.launcher/files/libs/libfmq.so.1
      #03 pc 0000798f  /data/data/org.koreader.launcher/files/libs/libfmq.so.1
      #04 pc 0002670d  /data/data/org.koreader.launcher/files/libs/libczmq.so.1
      #05 pc 000a61b3  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) (BuildId: 4f8077b25ed39d70244e32da94907afa)
      #06 pc 00060783  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) (BuildId: 4f8077b25ed39d70244e32da94907afa)
)

**Comment by Frenzie** [comment]
Closing on account of https://github.com/koreader/koreader/commit/a665901c51ffb70003db0b64a54a65f038adc90a.
