### ISSUE TITLE
FR: Option to change to another font in the bottom menu 

### ISSUE THREAD

**Issue by thinh105** [koreader/koreader#7407]
Can you allow the user to pick the font in the bottom menu,

Right now, we can change font size, word spacing, and word expansion in the Font option in the bottom menu,

So it may make sense if we can pick another font in this option,

![image](https://user-images.githubusercontent.com/23691294/111019507-42255800-83f2-11eb-84c0-ec63baf35c9e.png)

So the reader can easily pick the font they want, no need to do a lot of step in the top menu,

Thanks,

**Comment by NiLuJe** [comment]
I'm going to throw a pebble in the pond and say right away: highly unlikely ;).

1. The fonts menu is highly non-trivial
2. That bottom tab is already as high as we're willing to let it go
3. We're not in the habit of duplicating settings (there's already enough of them ;)). That would imply *moving* the option from top to bottom, which is kind of another strike against the idea ;).
