### ISSUE TITLE
Question: custom build for Kobo with damaged upper part of the screen

### ISSUE THREAD

**Issue by lwiechec** [koreader/koreader#7420]
I own a working Kobo reader with damaged upper part of the screen - about 2cm - and I was thinking about using KOReader instead.

Would it be possible to build a version that has a custom screen size - and visible part placing?

Thanks for any help,

**Comment by Frenzie** [comment]
You didn't say which Kobo, but we already do that out of the box.

https://github.com/koreader/koreader/blob/0b3747927c1491aabd5d92db20bb963b9951bfdc/frontend/device/kobo/device.lua#L98-L99

**Comment by Frenzie** [comment]
That is, adjust or add as appropriate.

**Comment by lwiechec** [comment]
thanks! excellent. I don't remember which one is it - will check it when @ home.

**Comment by lwiechec** [comment]
following the (excellent) documentation I have now running KoReader on my Kobo Aura - thanks.

I can also see that I can edit the `device.lua` directly on the Kobo device - sweet!

However - the changes that I made in the file don't seem to take effect. I _think_ I am in good section (I can see multiple Kobo Aura's). Which one to choose?...

**Comment by NiLuJe** [comment]
Check the crash.log, it'll print your devic's exact codename on startup.

**Comment by Frenzie** [comment]
Also displayed under Help → Report a bug.

**Comment by Frenzie** [comment]
Btw, just to be sure (always check the plugs first), you will need to restart the program. You can't just edit the file.

**Comment by lwiechec** [comment]
@Frenzie thanks again for the tip.

...but I think changing the `viewport` is not enough, right? I do see the screen smaller, but the touchscreen interface seems to be 'confused'.

Is there a similar setting to `viewport` but for the touch interface?

**Comment by Frenzie** [comment]
If you set a viewport then any touches outside of the viewport are ignored. If the device thinks you're touching within the viewport then there's a small possibility there's a bug specific to your device but I'm afraid it's much more likely that the touch layer is broken beyond what's easily visible.

Is it an IR or capacitive touch device?

**Comment by Frenzie** [comment]
One thing you could quickly try is to make the viewport really undersized, such as only the bottom half or third of the screen. If everything then works as expected it's definitely damage.
