### ISSUE TITLE
WebDAV has stopped working (probably since 2f9db259)

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#7424]
* KOReader version: v2021.02-66-g1cd478fd
* Device: Emulator / Kobo

#### Issue

WebDAV to an HTTPS local server with Basic auth fails, but previously worked.

#### Steps to reproduce

* Start a WebDAV server over HTTPS with Basic auth (Digest auth does not work due to #7331)
* Try to use it with "Cloud Storage"
* You get "Empty Folder" (which is what you are shown on any failure)

There is no debug logging that I can see.

**Comment by NiLuJe** [comment]
Fixed via #7425
