### ISSUE TITLE
FR: Add prev/next entry buttons to dictionary

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#7427]
Many dictionaries have internal references of the kind "see previous", "see next entry", "derived from previous word".  Currently there is no way quickly to get to that word.
Some dictionaries have several entries with identical keywords.  There seems no way to get to the entries that are not shown by default.
Sometimes the precise spelling is unknown, and one wants to to "riffle" through a set of entries to find the word one intended.

All these cases would be solved if the dictionary UI would have buttons for "previous entry" and "next entry" (within the same dictionary - this is orthogonal to the "previous dictionary"/"next dictionary" facility).

**Comment by Frenzie** [comment]
You can hold on a word in the result to get a new popup. Closing it equals back.

**Comment by Biep** [comment]
True - but if I don't know the word, that won't help me, would it?

**Comment by Frenzie** [comment]
Are you talking about an actual feature of the electronic dictionary or simply some text copied from a paper dictionary?

**Comment by Biep** [comment]
One that has it is the OED that has been adapted for KOreader on [this page](https://e.pcloud.link/publink/show?code=kZDhJ7ZBRkwNE50R4hz731AWB2RAb2Gmg3X).
For a trivial instance, see 'arch', sense IV (where the word is actually given at the beginning of the line, but often it isn't).

**Comment by NiLuJe** [comment]
I don't see any better solution than what @Frenzie said. (As in, I don't even know is sd/sdcv has a concept for "related" entries at all, so you're better off with a new search from scratch. And since we're running the CLI, there's no persistent state at all anyway).

**Comment by Biep** [comment]
Ah - you have no API for that, is that it?
Yes, then this can be closed.
Thanks for considering it (and doing all the stuff you all *are able* to do)!

**Comment by poire-z** [comment]
We use [sdcv](https://github.com/Dushistov/sdcv), a program, and it is it which opens/reads/processes the dictionary files: it returns us results.
We have no idea about how the dictionaries themselves are set up - it's even possible an entry containing "see next entry" (digitized from the paper version) is actually, inside the dict computerized/indexed/binarified data, no longer contiguous to this "next entry"...
And sdcv indeed does not provide any way to browse entries linearly, or tell us a entry index, or anything else: it does just search.

But sdcv (or some dicts) have an issue in that they may not return all the results with the same keyword :/ so, you may miss some entries.
(I had to reprocess some dicts to put such multiples entries into a single one... https://github.com/koreader/koreader/issues/5437#issuecomment-536499455 )

**Comment by poire-z** [comment]
> But sdcv (or some dicts) have an issue in that they may not return all the results with the same keyword :/ so, you may miss some entries.

This should be solved since https://github.com/koreader/koreader-base/pull/1431

Closing this issue as there is indeed no prev/next entry API.
