### ISSUE TITLE
Screen rotation buttons counterintuitive

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#7429]
* KOReader version: 2021.02-66
* Device: Kobo Aura One

#### Issue
The buttons seem to show how one must rotate _the device_ in order to see the text upright, rather than how _the text_ will rotate.
To me at least that is highly counter-intuitive: I rotate _my device_ myself, but must tell the device how to rotate _the text_.

If people differ in their intuitions regarding this, then maybe it should be a setting "Natural rotating" (like "natural scrolling") - all it had to do was replace device-rotating icons by text-rotating ones.

#### Steps to reproduce
Click e.g. on the icon with the arcing arrow clockwise, and the text will rotate counterclockwise.

*Maybe* related - the remarks like the one on line 7041  in the [crash.log](https://github.com/koreader/koreader/files/6172569/crash.log).

**Comment by poire-z** [comment]
Discussed at length in: #7306 , #7304 , https://github.com/koreader/koreader/issues/6945#issuecomment-738215400 , #6309.

**Comment by Biep** [comment]
I see.  I don't see the proposal to have it an option - and if all the option does is replace the icons, I'd think it would be rather easy to implement.  And pleasing both sides of an issue is never bad, is it?

**Comment by poire-z** [comment]
>  And pleasing both sides of an issue is never bad, is it?

It can, if we add such kludge because we can't find a good ubiquitous single set of icons that will ~~please everybody~~ will be intuitive to everybody.
I'm not super satisfied with what we have, https://github.com/koreader/koreader/pull/7306#issuecomment-780383417
But 2 toggable sets of icons is not the solution.
The solution is more brain work, or stumbling on a good idea.
And the path is actually reading all these issues to see how people react to the various ideas, and why the 2nd set of icons you may think about has actually issues too :)

**Comment by Biep** [comment]
> And the path is actually reading all these issues to see how people react to the various ideas

I did, but must have missed the proposal and discussion of that option.
For better icons, it seems there ought to be two arrows: an outer one showing how to rotate the device; inside that the device itself; inside that the arrow in the other direction showing how the text will rotate; and if there is still space, inside that a representative letter.

In those discussions I saw mention of a gyro sensitivity.  Does the Aura One have that?  If so, how does KOReader react to it - I have never remarked it reacting to rotations.
What I *have* remarked is that if I put it away perfectly horizontally, it goes in sleep mode very quickly - so it seems to have some sense of its position relative to gravity.

**Comment by NiLuJe** [comment]
We tried the letter approach, it was *more* confusing ;). Two conflicting arrows falls in the same basket in my book.

**Comment by Biep** [comment]
I'd be interested in reading the objections to the *general setting* solution - still looking.  My touchpad has a setting "natural scroll", and people do or do not set it according to taste.  It is only confusing when someone from the other tradition uses my device.
This would be the same, only *less* confusing, since "blind tapping" would still do what one expects, even if using a device set the other way.
Scrolling is linear and rotating is circular, but otherwise it seems very comparable - translate/rotate the document with respect to the device, or translate/rotate the device with respect to the document.

**Comment by NiLuJe** [comment]
I do agree with what @poire-z said about that: it's not a solution, it's a crappy band-aid that only obfuscates the issue even more ;).

**Comment by Biep** [comment]
I highly respect your opinions - but I can also redefine e.g. swipe-left and swipe-right to my tastes.  How would this be different?
People are different, and catering for that seems eminently user-friendly.
Well, I must go now..

**Comment by poire-z** [comment]
> Stuff is exposed as a device rotation on purpose: that's the LinuxFB API.

This is @NiLuJe argument from the start - and I don't buy it :) The internal technicalities of how it's implemented don't have to leak up to the user :) 
But I haven't seen any better idea yet.

To me, everything other "this is the natural way to show it, like everywhere else" are more wrong: that everywhere else (Photoshop, your PC, your mouse), you never rotate it or need to rotate it or its screen; you rotate things inside (a photoshop image, and hardly never text).
And there's the thing that our icons show a STATE - and most people (including me) go intuitively at these rotation button as an ACTION ("rotate what I see 90° this way", which won't work when next, after the rotation, they should represent a state).
And there's the fact our current set of buttons, fine for a device we can rotate, don't work at all on the emulator running on a PC... So, if we ever need 2 sets of buttons, it's for this case.
(Expressed that already at https://github.com/koreader/koreader/pull/7306#issuecomment-780383417, with screenshots).

So, if you have some ideas that pass my above points, please do a quick sketch so we can better see it :) I'm all for new ideas.
(And if nothing static comes to mind, we can think about having them dynamic - different when in portrait or landscape - but only as a last resort, as this would be more coding work.)

**Comment by Frenzie** [comment]
As an aside, with the notion of icon themes we do have an option.

**Comment by Biep** [comment]
> And there's the thing that our icons show a STATE

Maybe this is the core of the problem.  If there were true *actions* - rotate to the left, rotate to the right, and rotate π radians, then there would still be the difference between traditional and natural rotation (names in analogy with scrolling), but the larger counterintuitivity would be gone.  And just showing a square device with some text in it in the resulting orientation would probably suffice to remove the remaining confusingness.

**Comment by NiLuJe** [comment]
c.f., second screenshots in https://github.com/koreader/koreader/pull/7306#issuecomment-780190019

The consensus was that it looked even weirder.

(The fat bottom lip is supposed to convey the same meaning: e.g., this is the physical bottom of the device).

**Comment by Biep** [comment]
Given my new proposal, the device in the icon should be square, with no recognisable orientation.
Just a square with a letter in three orientations, and maybe an arced arrow to show the movement.

**Comment by pazos** [comment]
> Given my new proposal, the device in the icon should be square - maybe with rounded corners, but with no recognisable orientation.

Please make a clean proposal with samples, provide icons and post a screenshot/sketch. Then we can provide feedback and see if your proposal makes more sense than we currently have.

IMHO I'm not bothered by current options but was also fine with the old design with just two buttons *portrait* and *landscape* and pressing the current rotation to reverse it.

**Comment by LucyOne** [comment]
If I may chime in: I've always found the icons of the native Pocketbook app very intuitive. They just show how the text will be displayed, no need to confuse the user with another arrow for the direction of the rotation.

![20210322_100744](https://user-images.githubusercontent.com/15887012/111965967-a59c3d80-8af6-11eb-8037-74a60926d477.jpg)

**Comment by poire-z** [comment]
@LucyOne : can you show a pic of how this menu looks after you have hit the 2nd button, to go into landscape mode ?
(Your pic looks perfect, even more as it's shown rotated by github, so the 2nd button feels exactly like what you want to hit if you had rotated the device like it is shown :) but well, things are easy for the portrait mode view - the aim is that all still make sense in the other modes :)

**Comment by LucyOne** [comment]
It's not rotated in my view of GitHub, but anyway... Here's the requested view:
![20210322_162824](https://user-images.githubusercontent.com/15887012/112015470-232e7080-8b2c-11eb-9a57-60534f8eac99.jpg)

**Comment by hius07** [comment]
Rotation of the icons, not bad!

**Comment by poire-z** [comment]
Thanks,
Feels really nice, simple and clear.

**Comment by NiLuJe** [comment]
Not rotating the shape is an interesting approach, it feels slightly wonky at first, but it does work rather well.

I'll see what I can come up with ;).

**Comment by NiLuJe** [comment]
That would be something like this:

![Portrait_A](https://user-images.githubusercontent.com/111974/112042793-394a2a00-8b48-11eb-8e91-5a482aeae39a.png)

(Haven't done the Landscape variants, or the code to actually be able to do that in the first place ;p. because that doen't work at all when in Landscape.).

**Comment by poire-z** [comment]
Have a try with just passing `rotation_angle = 90/270` to IconWidget (which extends ImageWidget) - although I guess the landscape icons might need some small adjustments like the spacing vs the underline.

**Comment by mergen3107** [comment]
Kindle 4 Non-Touch used some intuitive icons with fixed text right up, but with respectively rotated device shape:
![](https://www.the-ebook-reader.com/images/kindle-4-fonts.jpg)

**Comment by NiLuJe** [comment]
@mergen3107: Yep, that was what I took inspiration from for [this iteration](https://github.com/koreader/koreader/pull/7306#issuecomment-780190019) ;).
