### ISSUE TITLE
Kindle Oasis 3 support

### ISSUE THREAD

**Issue by TrYoLz** [koreader/koreader#7433]
I've recently jailbroken my Kindle Oasis 3. KOReader doesn't support this device yet. 
In a few days, there will be many more jailbroken Oasis 3s because a new method has been discovered.

```
./luajit: frontend/device/kindle/device.lua:943: unknown Kindle model: G000WL
stack traceback:
	[C]: in function 'error'
	frontend/device/kindle/device.lua:943: in main chunk
	[C]: in function 'probeDevice'
	frontend/device.lua:53: in main chunk
	[C]: in function 'require'
	./reader.lua:144: in main chunk
	[C]: at 0x00013ef9
ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
```

**Comment by Frenzie** [comment]
You'll need to add a few device definitions based on G000WL over in
https://github.com/koreader/koreader/blob/1cd478fd704294058a1c03ec46cc5ba4eaafca97/frontend/device/kindle/device.lua#L879-L899

You could quickly try it in koa2_set (Oasis 2), pw4_set or kt4_set as the
most likely to line up but I'm not really at home in the Kindle ecosystem.
Some minor adjustments may be necessary.

**Comment by NiLuJe** [comment]
You might want to look at the PR where Oasis 2 support was introduced for some inspiration ;).

(Or... not, as that was from me without the device. Oh, well. #4016, #4037).
