### ISSUE TITLE
adapt to April 2021 Gutenberg.org http access retirement if needed

### ISSUE THREAD

**Issue by SteadyQuad** [koreader/koreader#7439]
This is posted on gutenberg.org website:

> Planned service change In April 2021, www.gutenberg.org plans to remove unencrypted access (http), and will only offer https. The collection remains available from mirrors, as well as via unencrypted ftp and rsync.

Not sure if this applies to www.gutenberg.org subdomain only or also other subdomains like m.gutenberg.org

Several http url's to gutenberg.org domain are in the sourcecode/tests:

mainly in
`spec/unit/opds_spec.lua`
and also 
`base/thirdparty/kpvcrlib/crengine/android/src/org/coolreader/db/MainDB.java:            "http://m.gutenberg.org/", "Project Gutenberg",`

If current Gutenberg url's break somewhere in April, this is likely why.

related:
https://github.com/koreader/koreader/issues/7007#issuecomment-749726860
https://github.com/koreader/koreader/pull/7437#issuecomment-803645933

**Comment by Frenzie** [comment]
> spec/unit/opds_spec.lua

A simple replace will probably do the trick.

> and also
base/thirdparty/kpvcrlib/crengine/android/src/org/coolreader/db/MainDB.java: "http://m.gutenberg.org/", "Project Gutenberg",

We don't use that, but you could PR for it over at the upstream crengine repo.

**Comment by SteadyQuad** [comment]
Seems too early to replace the url's, https doesn't seem to work everywhere (yet, if they will change at all) e.g.:

```
$ curl https://m.gutenberg.org/
curl: (7) Failed to connect to m.gutenberg.org port 443: Connection refused
```
while http://m.gutenberg.org/ still works atm.

I emailed them for some clarification (involved subdomains and planned date)

**Comment by NiLuJe** [comment]
I'm *pretty* sure `https://m.gutenberg.org` back when I tested #7405, FWIW.

Can't really check right now because *all of it* is nigh unusable ^^.

**Comment by Frenzie** [comment]
Yeah, the https works for me. It just took half a minute.

**Comment by SteadyQuad** [comment]
Below some questions from me, with answers from Greg Newby (gutenberg.org):

> Can you check if the below assumptions are correct?
> - Any existing http gutenberg links can be transitioned to https equivalents at this moment already, because only http will be turned off in April, and the https alternatives are already working, right?

Correct. The entire site is literally the same. We expose the same content, via Apache httpd, as both http and https.

> - Any existing m.gutenberg.org links can be converted to www.gutenberg.org equivalent links because both subdomains are the same now

Correct. m.gutenberg.org is just an alias for www.gutenberg.org now.

> - after turning off http, will requests to http urls fail, or be redirected to the proper https urls, e.g. with a 301 response?

I believe we will simply redirect, at least for some time.

> If you can share a planned date for turning off http yet, that would be nice!

We haven't set a date yet, but it won't be at the start of April. Probably around April 20 or 27 (i.e., early in one of the last days of the month).
