### ISSUE TITLE
FR: [add option to change koreader keyboard to android's default keyboard]

### ISSUE THREAD

**Issue by huronhorn** [koreader/koreader#7441]
Hi all!
I took lot of notes when im reading, and koreader default keyboard is too slow imo, at first i thought this responsiveness issue is because e ink screen, but when i try it on my phone, the issue persist.

I have an e ink android e reader, and when i typed fast on koreader keyboard, the words often jumbled up and miss registering double taps, this doesnt happen when i try to type same sentence with Android's default keyboard.

**Comment by Frenzie** [comment]
Duplicate of https://github.com/koreader/koreader/issues/7423 (and others).
