### ISSUE TITLE
Selecting shrink bookmark after changing TOC entry count results in 0 progress bar ticks

### ISSUE THREAD

**Issue by ptrm** [koreader/koreader#7442]
* KOReader version: 2021.02-66 and -72 == dbb4bbb
* Device: Android (Boox Nova 3) and Kobo Clara HD (though Kobo does not crash, see below)

### Issue

Selecting shrink bookmark after changing TOC entry count results in 0 progress bar ticks

#### Steps to reproduce
In TOC settings:
1. Change toc entry count (e.g. from 16 to 21)
2. Mark as checked the "Shrink bookmark font size" entry
3. Progress bar tick description changes to 0 ticks, on Android clicking it crashes, on Kobo just shows empty submenu (Screenshot below)

Android screencast: https://user-images.githubusercontent.com/366258/112133062-9509c700-8bcb-11eb-9d4f-3c286e802085.mp4

Kobo screen:
![Screenshot_20210323-110817_Photo Editor](https://user-images.githubusercontent.com/366258/112133194-b965a380-8bcb-11eb-9aae-873716106fa0.png)

##### `crash.log` (if applicable)
Not able to provide Android logs atm, Kobo just contains touch debug events, can provide if need be.

**Comment by poire-z** [comment]
On a week old android nightly, I also got the crash: `readertoc.lua:964: attempt to index a nil value`.
This has been solved with #7434 (so, thanks, didn't managed to reproduce it, but now I'll see how/why it happens :) So, the Android crash should be solved on current nightly.

Can reproduce the other strange behaviour... I'll look at it.

**Comment by ptrm** [comment]
> On a week old android nightly, I also got the crash: `readertoc.lua:964: attempt to index a nil value`.
> This has been solved with #7434 (so, thanks, didn't managed to reproduce it, but now I'll see how/why it happens :) So, the Android crash should be solved on current nightly.

Actually, the crash when opening submenu persists (not sure if the reason is the same) on curremt nightly :/

**Comment by poire-z** [comment]
With -72 ? Can't reproduce it on Android, I just get "0 ticks", and an empty submenu (with only the 2 last items greyed out).

OK, the reason for 0 ticks and empty submenu is changing things in the "ToC entries per page", which does `resetToc()` and clears all things, including the ticks list.
I just have to make sure it's actually filled when we use it.

**Comment by ptrm** [comment]
> With -72 ? Can't reproduce it on Android, I just get "0 ticks", and an empty submenu (with only the 2 last items greyed out).
> 

Sorry, just checked again, it shows empty submenu on -72 :)
