### ISSUE TITLE
FR: Make a setting for chapter_time_to_read (words per minute)

### ISSUE THREAD

**Issue by francwalter** [koreader/koreader#7444]
* KOReader version: 2021.02
* Device: Xiaomi Mi A1 with Android 9

Hallo
would it be possible to get a setting for the average words per minute of reading?
I appreciate very much the status bar setting "Chapter time to read", but it is not very accurate for my reading speed. 
I would love a setting for it, e.g. "Reading speed (Average words per minute)" to calculate the chapter_time_to_read individually.
I found in the code in:

` koreader/frontend/apps/reader/modules/readerfooter.lua `

the part:

```
    chapter_time_to_read = function(footer)
        local symbol_type = footer.settings.item_prefix or "icons"
        local prefix = symbol_prefix[symbol_type].chapter_time_to_read
        local left = footer.ui.toc:getChapterPagesLeft(footer.pageno)
        return footer:getDataFromStatistics(
            prefix .. " ", (left or footer.ui.document:getTotalPagesLeft(footer.pageno)))
```

where that is calculated, I guess, but I dont understand where exactly I could change anything about that there.
Anyway, I didnt try to compile KOReader since yet, so I dont know if it would help if I knew where this is done 😄 
I guess it is hard coded somewhere in statistics.

Thanks.
frank

**Comment by poire-z** [comment]
I think none of our engines (PDF, DJVU, EPUB) care and can give us anything about the number of words on a page.
At most, they could give us the plain text of a page, and some frontend code could then split that into words to get the nb of words on current page - and even that, if you want it accurate for all languages (Chinese, Korean,...) you need a proper library like libunibreak to break the text into what are considered words in the various scripts... it might not be just space and punctuation...

This feels quite a bit expensive (in work involved, and in added CPU usage), and uneeded for most readers, so... :/

**Comment by NiLuJe** [comment]
Wat you *can* tweak are the min/max time spent on a time thresholds.

You've not really explained what you meant by "inaccurate" and why you think a wpm metric would work better ;) (spoiler alert: it wouldn't ;p).

**Comment by francwalter** [comment]
Ah!?
But how is it than calculated, this "Chapter time to read", if it is not the remaining words in the chapter, that are counted? 
I thought that it would be that, so now I see better, why I don't find the calculation part in the code :)

But maybe I am wrong with the estimated time as well, I thought I would read slower than that value says.
Thanks!

**Comment by poire-z** [comment]
> But how is it than calculated, this "Chapter time to read", if it is not the remaining words in the chapter, that are counted?

By counting pages :) We have the TOC, that gives us the page the next chapter start at, we know the current page. The code knows (from reading statistics) the average time you spent on a page (I thought it uses only the stats from the "current session", since you opened this book or resumed the device - but I'm not sure, having a glance at the code).
So, nb of pages till end of chapter x average time per page = chapter time to read.

**Comment by NiLuJe** [comment]
It is automatically seeded from the DB ;).

**Comment by francwalter** [comment]
OK, I know now 👍 
So this idea with words per minute is not appropriate for KOReader, as I understand, I will close the issue then 😄
Thank!
