### ISSUE TITLE
How to change the default view mode (page, continuous) for picdocuments?

### ISSUE THREAD

**Issue by telejesus2** [koreader/koreader#7445]
Hi,

I use the app for reading manga on Linux, and it is a bit annoying to have to change the view mode from 'continuous' to 'page' every time that I open a new file (usually one file per chapter so every ~20 pages). 

I have seen in the file 'defaults.lua' that this feature is yet not supported, but could anyone share a hack I could use? Since I never use the 'continuous' mode I would like to hardcode the 'page' mode somewhere in the code. The file 'frontend/document/koptinterface.lua' seems to be the place but I don't see the setting I want.

Thanks!

**Comment by Frenzie** [comment]
You can hold to set default.

**Comment by telejesus2** [comment]
that's great thanks!
