### ISSUE TITLE
Failure to export highlight with PDF and EPUB 

### ISSUE THREAD

**Issue by warpedwood** [koreader/koreader#7455]
- KOReader version: 2021.03
- Device: Pocketbook InkPad 3

I am sorry to repost an issue I had already submitted, but I am still struggling with the same problem. 

**Issue**

When I transfer a PDF or a EPUB file to my computer, the highlights I made with KOReader are not available, but they remain visible in KOReader.

**Steps to reproduce**

Highlight text in a PDF or a EPUB, transfer it by USB cable, open it and the highlights are not available while they remain visible 
in KOReader.

Thank you for your feedback!

crash.log (if applicable)
[crash.log](https://github.com/koreader/koreader/files/6217269/crash.log)

**Comment by Frenzie** [comment]
If you reference an older issue, please also link to it (or just add to the existing one) https://github.com/koreader/koreader/issues/7217

Note that you need two things:

1. The write changes to document setting enabled.
2. To close the document so that changes are actually written into them. If you transfer it in the background over SFTP, you won't have the changed document.

**Comment by warpedwood** [comment]
Thank you for your answer! I'm sorry I'm quite new to github and I don't know how to link issues. 
I actually enable the write changes. I ticked the option "always". 
What do you mean exactly by closing the document (my apologies for the basic question)? I generally suspend my ereader. Does that disable the saving of highlights?

**Comment by NiLuJe** [comment]
FWIW, this will never happen for ePubs ;).

PDFs, on the other hand, have a dedicated setting, as @Frenzie mentioned.

This was touched recently, so, on the off-chance something weird happened, ping @Toromtomtom

**Comment by Frenzie** [comment]
> Thank you for your answer! I'm sorry I'm quite new to github and I don't know how to link issues.

I meant link like past the link, nothing fancy.

> I actually enable the write changes. I ticked the option "always".
What do you mean exactly by closing the document (my apologies for the basic question)? I generally suspend my ereader. Does that disable the saving of highlights?

I don't know otoh whether it might be saved on suspend, probably not, but the document isn't overwritten with every little change. You have to close it for changes to be written.

So if you create a few highlights and transfer files in the background while the document is still open, they won't have been written into the document.

**Comment by warpedwood** [comment]
Thanks for your both answers and help. 
I transfer the book by USB cable, copying the PDF or EPUB file from the directory of my ereader to my computer. I'm not sure if I'm answering completely to the question. By closing the document, do you mean going back to the home menu of KOReader?

**Comment by NiLuJe** [comment]
We have no idea how USBMS behave on PocketBook, but I assume/hope it closes KOReader.

In case it doesn't:

> By closing the document, do you mean going back to the home menu of KOReader?

Yes.

**Comment by warpedwood** [comment]
Did you forget to add something after the colon? 
I tried to exit the app "manually" but I didn't change a thing. I can read the extracts I highlighted in the metadata LUA file, but they don't appear on the file itself.

**Comment by NiLuJe** [comment]
In a PDF:

Top menu, gear  tab > Document > Save document

By default, it's set to "Prompt", which does what it says on the tin: when you go back to (KOReader's) FileManager (or if you sanely exit KOReader), it'll ask you.

That's a good way to check if you're doing the right thing, because that's the only time the change will be saved.

----

For ePubs, on the other hand, that's *never* going to happen.

**Comment by warpedwood** [comment]
Thanks for your answer. I changed the setting from "always" to "prompt" and another issue appears. I tried to open the PDF on my computer and it asked me for a password and KOReader tells me that the file is invalid while I could read it before. Do you know what happened? I attach the crash file in case it could be useful. But it is working for other files, so maybe the option "always" was provoking some issues at the moment of saving the file. 
Besides, I was wondering if I save the file as you say, will the previous highlights I made appear again? Or is there a way to recover them? 
Finally (my apologies for too many questions), what is the difference with EPUBs? Is the saving automatic? 
Thanks again 
[crash.log](https://github.com/koreader/koreader/files/6220441/crash.log)

**Comment by NiLuJe** [comment]
There's no standard for this sort of things in ePubs, so they're not bundled in the file, at all, ever.

**Comment by warpedwood** [comment]
Do you mean I cannot export the highlights I made?

**Comment by NiLuJe** [comment]
[You can](https://www.mobileread.com/forums/showthread.php?t=265433), but not inside the ePub itself. What were you hoping to achieve, exactl?y (i.e., where/with what are you reading the exported ePubs?).

**Comment by warpedwood** [comment]
I understand. Thanks for your answer. I copy the ePubs on my computer and then read them with Calibre. But the highlights don't appear in Calibre.

**Comment by warpedwood** [comment]
Sorry to come back. Do you know how I could export the highlights I made on ePubs? 
And, do you know if there is a way to "recover" the previous highlights I made on PDFs, that appear on KOReader but I cannot read once I transferred the file, while the most recent highlights I made are available? 
Thanks in advance

**Comment by Frenzie** [comment]
See the link above to https://www.mobileread.com/forums/showthread.php?t=265433

**Comment by warpedwood** [comment]
Thanks

**Comment by Toromtomtom** [comment]
> do you know if there is a way to "recover" the previous highlights I made on PDFs, that appear on KOReader but I cannot read once I transferred the file, while the most recent highlights I made are available?

KOReader has its own "database" of highlights. This database is updated when you create, delete, or modify highlights. The database is saved independently from the PDF file itself (in the `.sdr` directory next to the PDF file).

KOReader also renders annotations that are *embedded* in the PDF, but you cannot interact with those in KOReader.

Here is where it gets confusing: If you create a highlight in a PDF file in KOReader and save the PDF file, an annotation in the PDF file is created. The next time you open the file, KOReader will display the highlight from its own database **and** the annotation embedded in the PDF. You can only interact with the former. For example, you can delete the highlight, but not the embedded annotation.

There is currently no way to import embedded annotations from a PDF file and convert them to KOReader's internal highlights.

**Comment by Toromtomtom** [comment]
> Thus, there is no way to transform the annotations saved in the KOReader database into embedded annotations (the reverse operation of you last sentence, if I am correct) in order to be able to read the PDF on my computer with the annotations I made previously but were not saved. Is that right? 

Yes, that is correct. Existing highlights can not be converted to PDF annotations in KOReader. 

**But**: if you set the "Save document (write highlights into PDF)" setting mentioned above to "Always" or "Prompt", all *new* highlights you add in KOReader will also be added as PDF annotations. They are written to the PDF file when you close it.

**Comment by Toromtomtom** [comment]
I think the whole PDF annotation story is quite confusing. As I recently worked on that code, I would volunteer to write some documentation of the current state. @Frenzie @NiLuJe would the Wiki be the right place to do that?

**Comment by warpedwood** [comment]
Thanks for your answer. It is clearer now. The issue I had was that my setting was on "Always" and the new highlights were not added as PDF annotations, as when I transferred the PDF to my computer the annotations did not appear. I changed the setting to "Prompt" and now it seems to work.

**Comment by Frenzie** [comment]
@Toromtomtom On my phone atm, but chaces are the wiki already says a little bit about highlights. (Also yes.)

**Comment by Toromtomtom** [comment]
Just for the record: I finally got around to writing up a [short text](https://github.com/koreader/koreader/wiki/PDF-Annotations) about the state of the feature.
