### ISSUE TITLE
Default zoom fit option not taken into account for CBZ, always fit the width

### ISSUE THREAD

**Issue by lartick** [koreader/koreader#7461]
* KOReader version:v2021.03
* Device: PB740 Pocketbook inkpad 3 (Vivlio firmware) 

#### Issue
For CBZ files, the zoom is set by default to fit the width of the page even though it is supposed to be height or full
#### Steps to reproduce
I select zoom 4 and fit to full by default. Whenever I open a new CBZ file, it behaves as if it is set to fit the width by default, even though when I go to change the zoom option, I can see that my default is selected (i.e. zoom 4 and fit to full). I have to change the fit option and then put it back to full again for it to behave as expected.

**Comment by NiLuJe** [comment]
What do you mean by "Zoom 4"? And Is panel zoom enabled? (Top menu, Document tab).

**Comment by NiLuJe** [comment]
And are your favorite options *actually* set as defaults (e.g., long-press)?

**Comment by NiLuJe** [comment]
Also, the default type is now `full`, yet the default zoom_mode is still  `pagewidth`, so:

```diff
diff --git a/frontend/apps/reader/modules/readerzooming.lua b/frontend/apps/reader/modules/readerzooming.lua
index 0853e8eb8..a1d1c3952 100644
--- a/frontend/apps/reader/modules/readerzooming.lua
+++ b/frontend/apps/reader/modules/readerzooming.lua
@@ -30,7 +30,7 @@ local ReaderZooming = InputContainer:new{
     },
     -- default to nil so we can trigger ZoomModeUpdate events on start up
     zoom_mode = nil,
-    DEFAULT_ZOOM_MODE = "pagewidth",
+    DEFAULT_ZOOM_MODE = "page",
     -- for pan mode: fit to width/zoom_factor,
     -- with overlap of zoom_overlap_h % (horizontally)
     -- and zoom_overlap_v % (vertically).
```

**Comment by Frenzie** [comment]
> Also, the default type is now full

Is it? Well, opinions differ a bit of course but I'm in not in the full page camp.

**Comment by NiLuJe** [comment]
Also, switching from `none` to `auto` crop switches from `pagewidth` to `contentwidth` without updating the ConfigDialog knobs.

**Comment by NiLuJe** [comment]
@Frenzie: No opinion, as I don't use this, but:

https://github.com/koreader/koreader/blob/e33476996acfa9aa2dab2c6e35c8eda4545100ce/frontend/ui/data/koptoptions.lua#L155-L167

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/pull/5170.

**Comment by Frenzie** [comment]
> Set what to fit.

I approved that?

**Comment by lartick** [comment]
OK, maybe I wasn’t clear enough so here are screenshots (from the deb build).
Before taking those screenshots I changed view mode to "page" by default, and I set default zoom mode to "4" (I explain later) and default fit to "full" . To be clear, to set by default I do a long click until a message appears telling me the new default is set.
The following screenshot shows what happens when I open a CBZ for the first time. In the menu, zoom mode and fit are correctly highlighted (so zoom mode "4" is the one most to the left, I don’t know how to name it and "4" is the name given when I set it as default). However the picture is not well fitted.
![screen1](https://user-images.githubusercontent.com/421023/112883962-35ca1c00-90cf-11eb-9a08-9c6de4b6e651.png)
When I change fit to "width" and set it back to "full", then it behaves as expected, as shown below.
![screen2](https://user-images.githubusercontent.com/421023/112883976-38c50c80-90cf-11eb-86e3-b805bcf85c12.png)

**Comment by NiLuJe** [comment]
Okay, that's what I figured out, thanks for the confirmation.

I'd missed the fact that the long-press was not using a human-readable name, I'll see if I can fix that, because it's kind of ridiculous ;).

**Comment by jperon** [comment]
Sorry for my silence on all that: I’m very busy till next monday (when I’ll be on holidays).

**Comment by lartick** [comment]
> Okay, that's what I figured out, thanks for the confirmation.
> 
> I'd missed the fact that the long-press was not using a human-readable name, I'll see if I can fix that, because it's kind of ridiculous ;).

FYI It had been reported in #7192
