### ISSUE TITLE
ReaderFooter: after hold highlights on page aren't recognized

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7464]
#### Steps to reproduce
Navigate to a page wth a highlight.
Hold the footer (doesn't depend on the footer visibility or enabled `Hold to skim`).
Tap a highlight - got no highlight menu, just a page turn.

**Comment by hius07** [comment]
Look like the highlights override lost
https://github.com/koreader/koreader/blob/1f15184bbb7712faa75f83e3a94f14643aef767b/frontend/apps/reader/modules/readerhighlight.lua#L194-L197
Any action restores highlights priority.

**Comment by NiLuJe** [comment]
Note that this is a non-issue w/ "Reclaim bar height", because ReaderHighlight then necessarily finds stuff to highlight, as such ReaderFooter's hold handler never gets called.
