### ISSUE TITLE
FR: Setting to control highlighting brightness

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7476]
#### Current Behavior

Under the highlighting menu, there are currently three options: Lighten, Underline and Invert. Lighten seems to apply a 50% gray.

#### Request

Some devices have a [darker than ideal](https://www.youtube.com/watch?v=jm-YBQMj8Jw) background color. An option to set highlighting to a brighter gray would improve contrast/readability in such devices.

**Comment by gbyl** [comment]
It seems that the highlighting brightness is controlled by the following value:

https://github.com/koreader/koreader/blob/03e9fac15617e63f99dab71fd1ac0d36acf2e148/frontend/apps/reader/modules/readerview.lua#L40

As evidenced by:

https://github.com/koreader/koreader/blob/03e9fac15617e63f99dab71fd1ac0d36acf2e148/frontend/apps/reader/modules/readerview.lua#L547-L548

I tried many different `lighten_factor` values with no visible results. Do we know what range of values are allowed?

**Comment by poire-z** [comment]
> I tried many different lighten_factor values with no visible results. Do we know what range of values are allowed?

Just tried it (changeing the 0.2 on line 40 in readerview), with PDF or EPUB, and it worked - with 0.1 (very light) and 0.5 (darker).
It's only the final highlight that gets this value - while you're making one, and still when the popup is shown, it's still the engine that is doing the selected text highlight (some value for EPUB/crengine, black for PDF). Once it's done, and when visiting pages, only then it's readerview that does it.

**Comment by gbyl** [comment]
> and still when the popup is shown, it's still the engine that is doing the selected text highlight

Ah you are so right! I was not aware of that

> It's only the final highlight that gets this value

Is there a way to have it change the factor for past highlights?

And more importantly, is it possible/reasonable to have a setting to be able to control the `lighten_factor`?

**Comment by poire-z** [comment]
> Is there a way to have it change the factor for past highlights?

The current value for this lighten_factor applies to the drawing of past highlights, for me, tested on EPUBs.

> is it possible/reasonable to have a setting to be able to control the lighten_factor?

I suppose so, one just have to do it.
- Either a simple `lighten_factor = G_reader_settings:readSetting("highlight_lighten_factor") or 0.2,` and interested people can add manually `"highlight_lighten_factor" = 0.1` to their settings.reader.lua. (But we got rid of most of these hidden settings, to make them available in some menu).
- Or by adding some menu + number picker, but that's more work.
- Or just adding a `DHIGHLIGHT_LIGHTEN_FACTOR = 0.2` in defaults.lua that one can override in a defaults.persistent.lua (we already have a lot of them that we won't probably move to menu), and just `lighten_factor = DHIGHLIGHT_LIGHTEN_FACTOR` on line 40:)

I see you already made some PR, so have a go with this last idea :)

**Comment by NiLuJe** [comment]
I'd prefer a hidden setting than another hidden global, FWIW ;).

**Comment by gbyl** [comment]
addressed by https://github.com/koreader/koreader/pull/7497 and https://github.com/koreader/koreader/pull/7505
