### ISSUE TITLE
Opensearch spec without a hostname

### ISSUE THREAD

**Issue by tarioch** [koreader/koreader#7482]
* KOReader version: v2021.03
* Device: Kobo Aura H2O

#### Issue
It looks that the (new) search functionality in opds only works if a full url is specified. In my case (calibre-web) the spec looks like this

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <LongName>Tario Books</LongName>
   <ShortName>Tario Books</ShortName>
   <Description>Calibre-Web eBook Catalog</Description>
   <Developer>Janeczku</Developer>
   <Contact>https://github.com/janeczku/calibre-web</Contact>
   <Url type="text/html"
        template="/opds/search/{searchTerms}"/>
   <Url type="application/atom+xml"
        template="/opds/search?query={searchTerms}"/>
   <SyndicationRight>open</SyndicationRight>
   <Language>en-EN</Language>
   <OutputEncoding>UTF-8</OutputEncoding>
   <InputEncoding>UTF-8</InputEncoding>
</OpenSearchDescription>
```

This then naturally fails as it's missing the host name of the server.

**Comment by tarioch** [comment]
I think the fix would be in opsdbrowser.lua in getSearchTemplate, if template starts with / then use the hostname from osd_url.

**Comment by NiLuJe** [comment]
I don't recall how this is implemented for search, but the `OPDSBrowser:genItemTableFromCatalog` local `build_href` function (which is a simple wrapper around `url.asbolute` does just that.

**Comment by NiLuJe** [comment]
(Ping @ajvpot)
