### ISSUE TITLE
reader cannot start on cervantes after upgrade from v2021.03 to v2021.03-15

### ISSUE THREAD

**Issue by avsej** [koreader/koreader#7485]
BQ Cervantes,

```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 04/02/21-12:45:58
 [*] Version: v2021.03-15-g8a923e3_2021-04-01

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
FB: Enforcing portrait mode by doing an initial BB rotation./luajit: frontend/ui/timeval.lua:31: ./luajit: undefined symbol: clock_getres
stack traceback:
	[C]: in function '__index'
	frontend/ui/timeval.lua:31: in main chunk
	[C]: in function 'require'
	frontend/device/gesturedetector.lua:46: in main chunk
	[C]: in function 'require'
	frontend/device/input.lua:8: in main chunk
	[C]: in function 'require'
	frontend/device/cervantes/device.lua:133: in function 'init'
	frontend/device.lua:54: in main chunk
	[C]: in function 'require'
	./reader.lua:142: in main chunk
	[C]: at 0x00013f31
```

**Comment by Frenzie** [comment]
Cf. https://github.com/koreader/koreader/pull/7478 which supposedly fixed this issue.

**Comment by NiLuJe** [comment]
Going to need the full path to librt on those devices, then :}.

**Comment by NiLuJe** [comment]
(I'd check myself, but the images are down ;)).

**Comment by NiLuJe** [comment]
(There *should* be a `/lib/librt.so.1` symlink, but, apparently not...)

**Comment by pazos** [comment]
@NiLuJe: I have the images available for Cervantes 2013/3/4. They're not useful as they're packaged on a single blob. But since you're the maintainer of KindleTool maybe you can find a way to extract their contents.

Anyways, I have been busy last month. Will check this weekend if nobody beats me

**Comment by NiLuJe** [comment]
I didn't actually come up w/ the package format RE, so, don't hold your breath ;).

That leaves someone with a live BQ and shell access to check, then.

**Comment by avsej** [comment]
```
root@cervantes:~# find / -name '*librt*'
/lib/arm-linux-gnueabi/librt-2.13.so
/lib/arm-linux-gnueabi/librt.so.1
/var/lib/dpkg/info/librtmp0.list
/var/lib/dpkg/info/librtmp0.postrm
/var/lib/dpkg/info/librtmp0.shlibs
/var/lib/dpkg/info/librtmp0.md5sums
/var/lib/dpkg/info/librtmp0.postinst
/var/lib/dpkg/info/librtmp0.symbols

/var/lib/dpkg/info/librtmp0.control
/usr/share/doc/librtmp0
/usr/lib/arm-linux-gnueabi/librtmp.so.0
/usr/lib/arm-linux-gnueabi/librt.so
/usr/lib/arm-linux-gnueabi/librt.a
```

**Comment by NiLuJe** [comment]
Well, that's a funky setup.

Lemme guess, Debian multilib? ^^.

**Comment by NiLuJe** [comment]
I'll handle that in https://github.com/koreader/koreader-base/pull/1346 later tonight, thanks ;).

**Comment by tjaderxyz** [comment]
Just installed 2021.03-26-g03e9fac from the development channel and everything went fine and KOReader is working after the restart. Do you want me to test anything more in particular?

**Comment by NiLuJe** [comment]
That hold gestures and swiping work, maybe, but that's no longer Cervantes-specific ;).

Thanks!

**Comment by tjaderxyz** [comment]
On Sat, Apr 3, 2021 at 6:09 PM NiLuJe ***@***.***> wrote:
> That hold gestures and swiping work, maybe, but that's no longer Cervantes-specific ;).

Just tested a hold corner gesture and the default frontlight gesture
swiping on the left edge, both worked fine.
