### ISSUE TITLE
F-Droid does not have v2021.03 release

### ISSUE THREAD

**Issue by avsej** [koreader/koreader#7486]
Looks like latest release has not been uploaded to F-Droid.

https://f-droid.org/en/packages/org.koreader.launcher/

```
Version v2021.02 (8064) Added on 2021-02-21 
```

**Comment by Frenzie** [comment]
We don't upload anything. F-Droid will eventually pick it up from the automatically created http://ota.koreader.rocks/koreader-android-fdroid-latest, which correctly says:

```
v2021.03
8143
```

It's already been picked up 4 days ago https://gitlab.com/fdroid/fdroiddata/-/blob/8b84da5ecc9aa7b854852ee1e0204b764824b71f/metadata/org.koreader.launcher.yml#L623-643 but some further part of the process apparently hasn't been triggered yet.

**Comment by Frenzie** [comment]
There's probably a build queue somewhere but I'm not overly familiar with the F-Droid ecosystem.
