### ISSUE TITLE
Buggy android scroll

### ISSUE THREAD

**Issue by adelin-b** [koreader/koreader#7487]
* KOReader version: v2021.02
* Device: Android

#### Issue
 The scroll sometime fail when reading a pdf and reset to previous scrolled position, which lead to infinite scrolling while not actually scrolling
#### Steps to reproduce
Scroll on android

https://user-images.githubusercontent.com/23508913/113410163-9b383a00-9367-11eb-98ea-e4c2b83d26ef.mp4

**Comment by Frenzie** [comment]
You didn't specify the version, but please try the current nightly. Pinging @NiLuJe

**Comment by NiLuJe** [comment]
Related to pan/swipe detection.

Android users are used to quick swipes, but the UI is designed to scroll on *pans*, not *swipes*. And pans need to be *very* slow on Android, or they're detected as swipes.

It's easy if you have the swipe for menus enabled, as you'll pop the menus all over the place.

But, if you stick outside of the zones, and quick swipe, it'll indeed do the elastic wraparound like shown above.

I, err, don't use PDF/Android, so, someone interested will have to look into what might be doable ;).

**Comment by NiLuJe** [comment]
The pan rate thingy might be broken or not calibrated properly, haven't tried playing with it.

**Comment by NiLuJe** [comment]
FWIW, I seem to remember this being annoying on eInk, too.

**Comment by Frenzie** [comment]
> I, err, don't use PDF/Android, so, someone interested will have to look into what might be doable ;).

I do (well, Android a bit less), but my POV is kind of that there are other apps that do your typical dragging/zooming type stuff better already, like MuPDF or Bubbles. KOReader's big appeal is being able to just relax and tap now and then.

**Comment by NiLuJe** [comment]
Yeah, I pretty much never use continuous mode anywhere; but I vaguely remember this sort of behavior being confusing/annoying on CBZs on eInk (before switching to paged mode ;p).

I don't think anyone's ever really been happy with how pan behave: IIRC, that's one of the reason @poire-z disabled it in ImageViewer, where swipe == pan, and everything works just fine ;).

**Comment by Frenzie** [comment]
I disagree that continuous is about panning (maybe a bit less on CBZ). ;-)

**Comment by pazos** [comment]
Closing this one. Scroll works the same in all platforms.
