### ISSUE TITLE
FR: Gesture to toggle visibility of bottom status bar

### ISSUE THREAD

**Issue by pickx** [koreader/koreader#7488]
Currently it is only possible to toggle it by tapping it, but it's a small target. I think being able to set an arbitrary gesture instead, would be quite handy.

**Comment by j3dd** [comment]
I believe this is already supported. Select a gesture from the gesture manager then set the action in "Reflowable documents" to "Show buttom menu"
![Uploading 2021_04_10_21_34_36.gif…]()

**Comment by Frenzie** [comment]
I think that's correct. Also don't forget about the forum. :-)

**Comment by NiLuJe** [comment]
Err, I haven't checked, but I assume the gesture refers to ConfigDialog, not ReaderFooter, which is what I think the OP was asking for ;).

**Comment by pickx** [comment]
> Err, I haven't checked, but I assume the gesture refers to ConfigDialog (i.e., the, well, bottom menu ;p), not ReaderFooter (the, well, reader's footer ;p), which is what I think the OP was asking for ;).

Indeed, it shows the menu rather toggling the status bar. I can confirm that there is currently no option to toggle the status bar in the latest build.

**Comment by hius07** [comment]
> I think being able to set an arbitrary gesture instead

How this gesture should work if unchecked `Show all at once`?
Now tapping the footer cycles indicators (+ switching off).

**Comment by Frenzie** [comment]
Personally I find the toggling annoying compared to just showing everything you need but some people like it. So I'm guessing it should in effect call the same action as tap would?

**Comment by hius07** [comment]
> call the same action as tap

Then one more question, for the case of unchecked `Show all at once`.
We have `Hide empty items` option (applicable to Frontlight, Bookmarks number, Wi-fi).
If enabled and when the above indicators are empty, toggling to them shows empty footer.
So, for example, if all 3 are enabled and empty, we will tap the footer 4 times and get it empty, and only the fifth tap shows anything (3 hidden empty indicators + 1 status bar off).

Should this be changed? If yes, it might be
- ignore `Hide empty items` and always show all enabled indicators, or
- skip empty indicators in toggling cycle

**Comment by NiLuJe** [comment]
I'd either skip empty items, or, possibly better: ignore the `Hide empty items` option altogether when not in all-at-once mode.
