### ISSUE TITLE
Installation on remarkable: Failed to start koreader.service: Unit koreader.service not found.

### ISSUE THREAD

**Issue by nicole-brewer** [koreader/koreader#7494]
I was trying to install koreader on my remarkable1.

I installed the Toltec package manager.
I ran `opkg install koreader`
but when I try `systemctl start koreader`
I get the error `Failed to start koreader.service: Unit koreader.service not found.`

Not being a systems guru, I uninstalled and reinstalled koreader, which didn't do anything.
Where do I go from here? Thanks

**Comment by NiLuJe** [comment]
We have no idea/control over the toltec packaging, so I'd ask over there ;).

**Comment by gbyl** [comment]
@nicole-brewer that means that for some reason Toltec did not configure the service. Try the following:

1. ssh into your device
2. `cp -v /opt/koreader/koreader.service /etc/systemd/system/`
3. `systemctl daemon-reload`
4. `systemctl start koreader`

**Comment by nicole-brewer** [comment]
Worked like a charm. Thank you so much!

**Comment by Eeems** [comment]
@nicole-brewer did you open an issue on toltec about this? You shouldn't have to manually do any of this.
