### ISSUE TITLE
FR: Page streaming with OPDS

### ISSUE THREAD

**Issue by MagikarpLaCarpe** [koreader/koreader#7500]
**Does your feature request involve difficulty completing a task? Please describe.**
Well, almost a week ago, i discover Koreader. I start using it for its OPDS support on the Kobo ink-reader.
However, i have also seen that Koreader doesn't have page streaming for OPDS, wich lead me to only be able to download the entire book before reading it.

**Describe the solution you'd like**
Adding page streaming for OPDS

**Describe alternatives you've considered**
I have considered using web browser, wich is not part of koreader and is also way slower and not... very user friendly and ergonomic.

**Additional context**
Adding page streaming will allow people to not only read faster, but also allow people with low storage left to read book, comics and manga without needing to downloading the book. Adding that the wifi of the kobo can be very slow, and the fact that i have personally all my book on my server.

**Comment by Frenzie** [comment]
I'm afraid that'd be unlikely. DjVu as well as MuPDF could support that in principle, but it'd be quite a lot of effort for a very niche use case. PRs welcome of course. :-)
