### ISSUE TITLE
Menu is drawn improperly after font selection

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7502]
* KOReader version: 2021.03
* Device: KPW3

#### Issue
After selecting a font in a fb2.zip book the top menu is redrawn, but only partially. Otherwise, it acts as a usual top menu, so if I tap outside of it, it closes; and if I blindly tap a menu item, it opens properly. 

![](https://user-images.githubusercontent.com/6279855/113503138-e1270680-94fd-11eb-9fe9-c021fcc63225.jpeg)

**Comment by poire-z** [comment]
Is this something new that didn't happen to you before with an older KOReader version?

For me, it always had been like that (#3130): some competition/congestion with eInk refreshes of many things (the text, the menu, the top notification telling you "redrawing with font Blah".
I personally patch this out in readerfont.lua:
```diff
 function ReaderFont:setFont(face)
     if face and self.font_face ~= face then
         self.font_face = face
-        UIManager:show(Notification:new{
-            text = T( _("Redrawing with font %1."), face),
-        })
+        -- avoid refresh competition and messup
+        -- UIManager:show(Notification:new{
+        --     text = T( _("Redrawing with font %1."), face),
+        -- })

         self.ui.document:setFontFace(face)
         -- signal readerrolling to update pos in new height
```

**Comment by hius07** [comment]
Tried with the latest nightly, fb2.zip, PW2.
All OK, font changed, notification shown, menu redrawn perfectly.

**Comment by Frenzie** [comment]
This is indeed "normal" E Ink behavior (that is, I'd consider it a driver bug, but we do try to work around it to some extent), however it's only "supposed" to happen very irregularly as certain timings unluckily coincide. Are you saying this is consistent behavior?

**Comment by NiLuJe** [comment]
Making one of those flashing (the notification might be the easier candidate) might help, although obviously the biggest race isn't there, it's between the menu and the reader ;).

**Comment by mergen3107** [comment]
Honestly, I didn’t change the font that much on previous versions, but such things were rare. 
Yes, it is consistent, I can reproduce it each time. 
I will try to comment it out

**Comment by poire-z** [comment]
I think we could remove this notification: I don't remember if the menu was ever closing when changing font - but as it stays open, we know which font is set when it gets it checkbox.

We could also remove the one when changing font size: it's displayed _after_ the rendering is done - so, it's not even telling us "please wait, rendering with font size 24, might takes some time".
And the font size panels stays open while this is happening, so it's showing the font size we end up with - and we have this little effect (I don't think it's voluntary :) that when changing font size, both he old and the new sizes are underlined while the rendering takes place - and when done, only tne new size is underlined.

**Comment by NiLuJe** [comment]
@poire-z: Definitely agree on both counts, go for it ;).
