### ISSUE TITLE
Multi-search input dialog

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7511]
To be discussed.

(1) KOReader has a powerful translation module (Google translate) invoked via Highlights menu only.
![1](https://user-images.githubusercontent.com/62179190/113664094-d31ae680-96b3-11eb-9afb-5c07daac05e7.png)
**It would be nice to have an option to enter any text for translation.**

(2) If (1) is of interest, input dialogs for Dictionary, Wikipedia and Translate are the same and can be combined to one.
![2](https://user-images.githubusercontent.com/62179190/113664193-fe053a80-96b3-11eb-9a5f-dcf6338da4bb.png)
It can substitute 3 items in the overcrowded Search main menu.

(3) It can substitute the continuous search dialog in the lookup results window
![3](https://user-images.githubusercontent.com/62179190/113664378-50465b80-96b4-11eb-8a18-f58a09682a67.png)
to invoke new search in another domain.

**Comment by poire-z** [comment]
(I'm not much a user of manual lookup.)
I think (2) can be nice when invoked from (3).
I'm not much fond of (2) when invoked from the menu:
- the 4 buttons feel a bit unnatural - and would need a single menu item to do lookups (and this would feel strange, unless you can think of a nice title for it?)
- I prefer 3 menu items, with each a cancel|lookup
- Indeed, looks like we miss a menu item "Translate" just above "Translation settings" :)

**Comment by hius07** [comment]
> menu item "Translate"

Which appears in the file manager menu too, why not.
Thus we get 11 menu items: 3 dict, 3 wiki, 2 translate, calibre, file search, opds.

**Comment by hius07** [comment]
> unless you can think of a nice title for it?

Search for knowledge

**Comment by Frenzie** [comment]
> the 4 buttons feel a bit unnatural - and would need a single menu item to do lookups (and this would feel strange, unless you can think of a nice title for it?)

The menu item could be okay(ish) but the dialog is very overcrowded.

I'd prefer to investigate a little how this kind of problem has been implemented previously, assuming we want to fundamentally change anything at all, which I'm not convinced of. (Of course the dictionary/Wikipedia/whatever settings could be stuck together in their own submenu, that's a different matter.) For example, in browsers you have a concept like search keywords and in DDG you have shebangs, but that's probably less ideal.

`w something to search on Wikipedia`
`w! something to search on Wikipedia`

Another fairly obvious one is to use radio buttons. You'd get an extra tap but less busy visuals.

**Comment by poire-z** [comment]
> Thus we get 11 menu items: 3 dict, 3 wiki, 2 translate, calibre, file search, opds.

I don't like going other 10...
There are a few possible options to reorganize this menu:
Keep the Search Dict/Wiki/Translate as individual menu items (because it's simpler to make the decision of the domain before entering some stuff and hitting go), and have a `Lookup histories>` submenu, and another `Lookup settings>`.
But this might get complicated as each readermodule manage its own stuff.

Also, I have no issues with the current menu and options :)
Logically, yes, a way to do a manual translate is not available anywhere - but how often would one need to translate something that does not come from a book ?

Getting the 4-buttons dialog when invoked from the pencil icon is fine by me: this would allow doing any other lookup/translation from a dict/wiki result without losing this result.
And once you discover this exists, you can do any manual lookup that way by just long-pressing any word to get to this pencil icon.

**Comment by hius07** [comment]
Thank you for the opinions. Have improved the 'pencil' button.

![1](https://user-images.githubusercontent.com/62179190/114170236-4bdfa400-993b-11eb-90ab-4bd1fc30c25b.png)

**Comment by Frenzie** [comment]
At least in English that does have a slightly less busy look to it.

**Comment by poire-z** [comment]
Just commenting here as here is the screenshot.
Can't we just drop the "Search"s ?
There's the title "Enter a word or phrase to lookup", so these buttons might be enough, and more balanced:
```
Translate | Dictionary
  Cancel  | Wikipedia
```

Dunno which of the top or bottom row is the most _finger appealing_ one, and if Dictionary should be on the bottom one.
Translate and Wikipedia requires to go online, unlike Dictionary. So, I guess they should both be in the same row, or same column - and the least appealing :)

```
Translate | Wikipedia
  Cancel  | Dictionary
```

**Comment by hius07** [comment]
> Can't we just drop the "Search"s ?

Can we drop the "Search"s here too?
https://github.com/koreader/koreader/blob/5b996c8ab76ff4d4875b45695627596876017b68/frontend/apps/reader/modules/readerdictionary.lua#L693
https://github.com/koreader/koreader/blob/5b996c8ab76ff4d4875b45695627596876017b68/frontend/apps/reader/modules/readerwikipedia.lua#L52

**Comment by poire-z** [comment]
Guess I wouldn't mind. But I let @Frenzie tell how good/bad UX/grammar it feels :)

**Comment by hius07** [comment]
However, ux design guides mostly say **Rule 1: Use Action Verbs** for button labels.

**Comment by Frenzie** [comment]
Yes as does ours.

**Comment by hius07** [comment]
So, keep "Search" everywhere? I'm okay with that.

**Comment by Frenzie** [comment]
I think it's clearer.

**Comment by poire-z** [comment]
OK then.
What about the ordering, online stuff above, cancel|dict below ?

**Comment by Frenzie** [comment]
Agreed

**Comment by hius07** [comment]
Thanks, done.
