### ISSUE TITLE
Setting the variable STARDICT_DATA_DIR in Android

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#7513]
I want to set the stardict data dir to another location, so that Koreader can share them with Neoreader on my Onyx Boox Note Pro (Android 6 device). 

Normally I would use `defaults.persistent.lua`. However, as the 7-zipped archive containing defaults.lua seems to be deflated at runtime, I don't know where to put it. 

Another approach would be to set the environment variable STARDICT_DATA_DIR since the code also looks for it there. However, since the old bash-script doesn't seem to be available on Android, I also don't know where to put my `export STARDICT_DATA_DIR=...` statement.

I can, of course, just change the code and repack the apk-file. However, I wonder whether there is a more persistent approach?

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/5b996c8ab76ff4d4875b45695627596876017b68/reader.lua#L16-L19
Continue reading at https://github.com/koreader/koreader/issues/7514#issuecomment-814794907

**Comment by Markismus** [comment]
Works as advertised. Thanks!
