### ISSUE TITLE
Replacing dogear icon with another on Android

### ISSUE THREAD

**Issue by Markismus** [koreader/koreader#7514]
Normally I just replace the dogear.svg with an icon of my own preference. However, I cannot find the file in my Android 6 system. I assume, that it is because the 7-zip-file is deflated at runtime. Is there a way to replace the icon, other than repackaging the apk-file?

**Comment by poire-z** [comment]
https://github.com/koreader/koreader/blob/5b996c8ab76ff4d4875b45695627596876017b68/frontend/ui/widget/iconwidget.lua#L9-L14
https://github.com/koreader/koreader/blob/5b996c8ab76ff4d4875b45695627596876017b68/datastorage.lua#L10-L14
So, that would be /sdcard/koreader/ (still not the real external sdcard), where you have screenshots/, data/dicts/ and other stuff.
So, your icon could go at /sdcard/koreader/icons/dogear.svg

**Comment by Markismus** [comment]
Great! I had put it inside `koreader/resources/icons/` instead.

**Comment by Markismus** [comment]
Still not working, though. I've put the file at `/sdcard/koreader/icons/dogear.png`. Could it be that png-files are not really supported anymore? (This is the same file that I used on my Kobo H2O before it cracked. So I expected it to work.)
Could it be that the filenames nowadays are  `dogear.alpha.svg` and `dogear.opaque.svg`?

**Comment by Markismus** [comment]
I remember that the code resized the dogear somewhere. Is there an easy way to tweak the resizing?

**Comment by poire-z** [comment]
GitHub has some search tool, that will tell you which bit of code use which:
https://github.com/koreader/koreader/search?q=dogear.opaque
https://github.com/koreader/koreader/search?q=dogear.alpha

The 32 and 40 are hardcoded and not customizable.
I don't think we should go at making everything customizable because one could now change the icon used :/ or it could become a mess. See what value you would be fine instead of 32 - and we'll see if it's ok for us or really too big.
That kind of tweaks is best left to personal koreader patching - but indeed, on Android it's not as easy as on other devices.

> There is a comment about ' -- This image could be scaled for

That's not a "can", but a "could" that mean: it "could" have been if I had ever bothered :) Might not make much sense now with this min/max.
Or may be it does? Feels indeed strange to make the min/max only dependant on pixel size, which may vary per device. A bit of DPIness might help. But I suck at DPI arithmetic :) I'll let that to @Frenzie.

For the min/max, our comment might not have been updated.
GitHub blame can help you to follow the history of changes:
https://github.com/koreader/koreader/blame/bf6c0cdd6c5b22bbb38497b5df8abe428eb80307/frontend/apps/reader/modules/readerdogear.lua#L14-L21

**Comment by Frenzie** [comment]
> Or may be it does? Feels indeed strange to make the min/max only dependant on pixel size, which may vary per device. A bit of DPIness might help. But I suck at DPI arithmetic :) I'll let that to @Frenzie.

We probably don't currently do it, but in principle we could just take the size of static images as if they're at 160 DPI, same as we do for other pixel values. I can't help but think it sounds more like introducing complications than making things simpler though?

**Comment by Markismus** [comment]
Probably due the DPI. My Onyx Note Pro has a resolution of 1405x1872, with physical dimensions of the viewport of 15.55 x 20.85 cm2 or 6.12"x 8.21". So the horizontal dpi is 230 and the vertical is 228 dots per inch. Reported DPI is 227, so there are probably some pixel under the bezel. 
40 px is 44mm and 32px is 36mm. Measuring the real dogear: It's about 4mm. Is that what's intended? I thought it was bigger on my Kobo H2O.

**Comment by NiLuJe** [comment]
The code explicitly says that it's handling this as a special snowflake.

What I can tell you is that getting constants that mostly behaved on ~265~300dpi devices was not fun.

**Comment by NiLuJe** [comment]
It should *definitely* be 36px (or 44px with larger margins), so I wouldn't mind an actual screenshot to confirm.

**Comment by Markismus** [comment]
![Reader_2021-04-07_183616](https://user-images.githubusercontent.com/5269101/113902723-7f51ef80-97d0-11eb-8741-fd71297bf1a2.png)

**Comment by poire-z** [comment]
Just a thought, in case that's enough to kill the issue: your reference page numbers are wrapped, which means KOReader's left/right margins are small - and the additional large margins you see are from the book, and probably some padding/margin applied on BODY/DIV/P.
Try some style tweaks to disable page margins and paragraphs margins till the text take the full available width. Then, you'll probably want more visible margins: increase KOReader margins, and see if the dogear can now increase.
Or just disable Embedded styles for this quick text, aind incrase KOReader margins.

(As for the main issue, looking at this screenshot : the dogear is quite visible :) you know this page is bookmarked. Of course, if you want to appreciate the grain in your icon, you won't - but well, that has never been the purpose :)

**Comment by NiLuJe** [comment]
I meant a screenshot with the default icon ;o). But, this one is > 37x37, so, perfectly as expected.

**Comment by Markismus** [comment]
No, that isn't the issue. Like I said, it's too small for me. By my eyes are starting to need reading glasses, so I understand the difference in opinion.
Here is a
screenshot from a zero margin book with maximum KOReader margins:
![Reader_2021-04-07_190352](https://user-images.githubusercontent.com/5269101/113906757-e1145880-97d4-11eb-9b01-5fa2d63025f9.png)

**Comment by NiLuJe** [comment]
Yep, that one is 44x44 as expected :).

**Comment by NiLuJe** [comment]
And, no, the thresholds are not user-configurable: https://github.com/koreader/koreader/blame/bf6c0cdd6c5b22bbb38497b5df8abe428eb80307/frontend/apps/reader/modules/readerdogear.lua#L14-L21

**Comment by poire-z** [comment]
These 32 and 40 could be made DDOGEAR_PAGE_RATIO_MIN/MAX in defaults.lua - and we could call it a day (if there wasn't this new religion emerging calling "globals are evil" :) (and it surely should not go needing a menu for a G_reader_setting setting!)

**Comment by Markismus** [comment]
Nice! Just tried to manually change the apk, but of course it failed to install afterwards.

**Comment by poire-z** [comment]
But globals are not that evil ! They've been of good use to us for years, and still are.
This [defaults.lua](https://github.com/koreader/koreader/blob/master/defaults.lua) / defaults.persistent.lua is just the right thing for little tunables like that. There was some attempt by @robert00s at some point to remove some of them - either to put them into setting menu or kill them when they made no sense. But many have to be kept that way, to not clutter our menus.
If we really want to remove such globals, we might do a bit of work to load defaults.lua/defaults.persistent.lua into a `defaults` or `config` module, or a single `DEFAULTS` table global variable, and tweak all the code that accessed them as globals to pick them from this table, `DEFAULTS.DOVERLAPPIXELS`.
(And get rid of the unit test about global variables that has been bothering each of us for years, each time we added or removed such a DSOMETHING default variable.

**Comment by Markismus** [comment]
I agree, but that's [not that unexpected.](https://github.com/koreader/koreader/commit/aaa84808e8c8c1c89218f49baff402deb5da8cbe#diff-64fbd07f8ed92b06eba715c2cfa0616929357a752d5136e73d951c7a77572ab5)

**Comment by NiLuJe** [comment]
Yeah, I'd feel mildly happier about stuffing them in a dedicated table, that feels like a nice compromise ;).

**Comment by Frenzie** [comment]
> But globals are not that evil ! They've been of good use to us for years, and still are.

Accessing globals is a bit slow (relatively speaking; iirc it's like 30% slower). But that just means you should probably map it to a local when initializing something, otherwise what we're doing should be fairly safe. Accessing foreign locals is faster and safer so that sounds like a good thing to do. ;-)
