### ISSUE TITLE
Font size defined in "html" element

### ISSUE THREAD

**Issue by KrokusPokus** [koreader/koreader#7515]
* KOReader version: 202103000035
* Device: Nova3/

Samsung M21

#### Issue

Not sure how this is supposed to render, but I notice a difference between Calibre and KOReader: In the attached Epub, the first and second page render with the same font size in Calibre (definitions in html element and class get multiplied through) while in KOReader the first page renders with halved font size (definition in html element has no effect).
 
#### Steps to reproduce

See attached epub.
[GF Tests 7 - HTML Element Font Size.zip](https://github.com/koreader/koreader/files/6273152/GF.Tests.7.-.HTML.Element.Font.Size.zip)

**Comment by poire-z** [comment]
Ref https://www.mobileread.com/forums/showthread.php?t=338486

For EPUBs, crengine strips the HTML element, and replace it with a DocFragment element.
That's for building a single DOM from the multiple xhtml fragments that make an EPUB.

I don't know why it was stripped, probably because the original authors didn't think it had any purpose and could be styled... (dunno if it's proper to do some styling on HTML rather than on BODY).
Fixing this would cause issues with existing xpath/xpointers for previously made highlights/bookmarks/current position.
We have some tools to migrate DOM versions, but it's not as obvious as with previous case that needed to deal only with internal boxing elements - and the HTML element is a real one that would be inserted in the DOM.
Dunno if it wouldn't be easier to just try to forward the style= attribute from the HTML to the DocFragment, and have `html {}` in CSS match DocFragment too... But this is ugly too.

**Comment by Frenzie** [comment]
It's reasonably common to style some things on HTML (in CSS anyway, dunno
about directly in style attributes). In any case it's standard. :)

**Comment by KrokusPokus** [comment]
I don't know if this means anything, but there is still a difference between how Calibre and koreader interpret the font style tag within the HTML element. 

For the first page in the test epub in the opening post

Calibre:
Html element font size 2rem + Class font size 0.5rem -> Visible font size 1
Html element font size 2rem + Class font size 0.5em  -> Visible font size 1

KOreader:
Html element font size 2rem + Class font size 0.5rem -> Visible font size 0.5
Html element font size 2rem + Class font size 0.5em  -> Visible font size 1

**Comment by Frenzie** [comment]
rem is based on the root element, and `<html>` is the root element, so this one would be wrong based on your description:

```
Html element font size 2rem + Class font size 0.5rem -> Visible font size 0.5
```

**Comment by poire-z** [comment]
Well, for crengine, the root element is not the `<html>` element, but some internal top node that contains the aggregated `<html>` of all the EPUB fragments.
Then, our default font size is set to this top node and inherited by the sub elements.
`rem` is computed from the default font size - it is not fetched from any node : it's the font size the user has set from our UI bottom widget - and it is not overriden by styles.

I think I'll skip fixing this case, as it would make everything a lot more messy than what it is.

**Comment by poire-z** [comment]
Btw, with:
`Html element font size 2rem + Class font size 0.5rem -> Visible font size 0.5`
Then, what's the reference for this 2rem for this HTML element (if it is itself its own reference) for computing 2 x something ?

**Comment by Frenzie** [comment]
The reference is whatever the default is (i.e., often 16px). The difference is that on the root element, the result then becomes the new default for the rest of the document.

> I think I'll skip fixing this case, as it would make everything a lot more messy than what it is.

Is the case only inline styles on the HTML element?

**Comment by poire-z** [comment]
> Is the case only inline styles on the HTML element?

What do you mean ?
I think with the recent PRs, I made these work:
- `<html style="something">`
- in stylesheets: `html { color:blue }` , with inline or block related CSS properties, `float:` might work :)
- in stylesheets: (nearly useless) selectors like `html > body > p` or `html img`

**Comment by Frenzie** [comment]
I mean that `html {}` is very common, `:root {}` is increasingly common, and `<html style="` is fairly rare.

Shouldn't the two situations behave identically though, if we take the root element as unchangeable font-size wise?

**Comment by poire-z** [comment]
Please be more verbose :)

> Shouldn't the two situations

Which two situations ?

> behave identically though, 

And identically in the preference of which different behavious among these two ?

You mean :root should target the nearest html element and not the real top node ?
Looks like it doesn't really target the real top node, there's some tweaks (did what I could :/ :root felt rather academic and not really useful):
https://github.com/koreader/crengine/blob/d33ae2df288d7b4e4104850c1b6c9197dec55308/crengine/src/lvstsheet.cpp#L4640-L4670

We build different kind of DOMs, and our stylesheet targets work normally on this DOM.
The tricks for the HTML element was just targetting the DocFragment internal element with which we replace HTML elements inside EPUBs. Nothing more clever :)

**Comment by Frenzie** [comment]
> Which two situations ?

From the comment above with .5rem vs .5em.

**Comment by poire-z** [comment]
> KOreader:
Html element font size 2rem + Class font size 0.5rem -> Visible font size 0.5
Html element font size 2rem + Class font size 0.5em -> Visible font size 1

Well, for me, this sounded right, and it's Calibre that had a bug :) Until you told me the HTML's computed font size is the new reference for `rem` for elements below it.

This sample feels a bit academic though.
I'm quite ok (in my crappy understanding of HTML and CSS) with the current wrong behaviour: with style tweaks, I know `1rem` restores my default font size, and that I don't have to fight against any other style. With the correct behaviour, I'd have to fight the font size set on the HTML element.

**Comment by poire-z** [comment]
Asked copilot for any magical idea to allow this issue request (have `<html style="font-size: N">` as the base size for units in `rem`) and my (not-per-specs) preference of having its base size be the root node font-size (= the font size set by our UI bottom widget).

```
● Best compromise: make rem root-aware, but only inside a guardrail around the user default. That gives spec-leaning users some effect from html { font-size: ... }, while preserving the
  maintainer’s goal of resisting publisher abuse.

  A practical model would be:

   1. Anchor on user default as today.
   2. Let root font-size modify that base only if it stays within a sane range.
   3. Clamp the effective root factor, e.g. 0.9x .. 1.2x or 0.85x .. 1.3x.
   4. Use that clamped value for rem, rex, rch, maybe rlh.

  So abusive CSS like html { font-size: 62.5% } or 50% no longer destroys sizing, but mild, legitimate document tuning still works.

  If you want both camps truly happy, the cleaner version is a 3-mode user setting:

  ┌───────────────┬─────────────────────────────────────────────────┐
  │ Mode          │ Behavior                                        │
  ├───────────────┼─────────────────────────────────────────────────┤
  │ Protected     │ current behavior: rem tied to user default      │
  ├───────────────┼─────────────────────────────────────────────────┤
  │ Balanced      │ user default modified by clamped root font-size │
  ├───────────────┼─────────────────────────────────────────────────┤
  │ Spec          │ full CSS root-relative behavior                 │
  └───────────────┴─────────────────────────────────────────────────┘

  I’d make Balanced the default. It is the only option that gives both sides something real instead of forcing one philosophy globally.

❯ the issue is not about abuse with big or small size, just that havinf html { font-size: 1.05 em } is enough for the font to look different from what we are used to.
  And we can't really have another tunable in frontend for this "edge" request.
  One idea I had was to introduce a homemade units ("urem") to get the current behaviour :/ Or some other -cr-hint to be set on something to get that behaviour.

● The least-bad “make both camps happy” idea is: keep rem spec-correct for author CSS, but keep the current user-default-anchored behavior for UA/user CSS.

  That splits the two intents cleanly:

   - Publisher CSS gets normal web semantics.
   - Engine/default/user stylesheet CSS keeps the KOReader-friendly “anchor to my chosen base font” behavior.

  So a book’s html { font-size: 1.05em } only changes how the book’s own rem-based rules behave, while your built-in styles and user tweaks can still stay tied to the user default.

  If that origin-dependent behavior feels too magical internally, then urem is actually a decent private escape hatch:

   - make rem spec-correct,
   - add urem = “user root em”,
   - migrate only engine/internal/user styles that really mean “stick to the chosen default”.

  I’d prefer that over a -cr-hint, because a hint only helps when someone opts in. It won’t solve real-world publisher CSS, which is exactly where the complaint comes from. A private unit or
  stylesheet-origin split is the only approach that separates the two meanings without adding frontend settings.
```

We have a few style tweaks that use rem (`Reset main text font size` and some for in-page footnotes).
Not fond of having to edit them to use `urem` :)
What about the UA/styletweaks (our epub.css and html5.css don't have any thing in `rem`) using the root node, and publishers styles using their own `<html font-size>` ? Would it feel too odd ?
(In most cases where the publisher does not set `<html font-size>`, they will be the same.)
