### ISSUE TITLE
When starting app with 'History', automatic re-orientation doesn't work

### ISSUE THREAD

**Issue by Australian-Infomaniac** [koreader/koreader#7518]
* KOReader version: 2021.03
* Device: Libra H20

#### Issue

When you set the device to start with History, the page wont re-orient itself (eg portrait vs inverted portrait) by moving the device physically

#### Steps to reproduce

Self-explanatory as above

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

**Comment by NiLuJe** [comment]
Likely applies to `favorites` and `folder_shortcuts`, too.

But unlike the other two, which I'm unfamiliar with, History does support layout swaps, so it likely just needs a bit of magic in a `SetRotationMode` handler...

**Comment by Australian-Infomaniac** [comment]
I find the History page a great one to open the app onto. I tend to read a few books at a time and its a great way to keep track, esp with all those big lovely covers!
