### ISSUE TITLE
FR: 'suspend', 'reboot' and 'poweroff' routines for remarkable

### ISSUE THREAD

**Issue by gbyl** [koreader/koreader#7519]
KOReader currently relies on `systemd` for suspend, reboot and poweroff functions. According to @pazos it should be possible to [implement our own routines](https://github.com/koreader/koreader/issues/7506#issuecomment-813097010) — which would unlock a few other features for remarkable users.

I am not sure what this would entail, as for example `poweroff` is always controlled by the system. This is true even if the line below is changed to `os.execute("poweroff")` or `os.execute("/sbin/poweroff")`

https://github.com/koreader/koreader/blob/5b996c8ab76ff4d4875b45695627596876017b68/frontend/device/remarkable/device.lua#L189

**Comment by pazos** [comment]
probably `poweroff` and `reboot` and symbolic links to `systemctl`

That would explain why you still see the system screensaver when you execute one of these commands.

Since `busybox` is installed on the Remarkable I would check if reboot/halt/poweroff applets are already available and see what happens with `os.execute("busybox poweroff")` or similar.

If my supposition is true there's a systemd service in charge of updating the poweroff screen. Disabling that service would be another way of preventing that behaviour. It should be as simple as `systemctl disable nameOfService`.

Please check both things and provide feedback. Thanks!

**Comment by gbyl** [comment]
You are right! They are both symlinked to `systemctl`. However, `busybox poweroff` returns `poweroff: applet not found`.

**Comment by snelg** [comment]
Yes, looks like it's systemd stuff:

Pertinent lines from `/etc/systemd/system/poweroff.target.wants/remarkable-shutdown.service`
```
Description=Show shutdown image
```
```
ExecStart=-/usr/bin/remarkable-shutdown
```

And from `/etc/systemd/system/reboot.target.wants/remarkable-reboot.service`
```
Description=Show reboot image
```
```
ExecStart=-/usr/bin/remarkable-shutdown --reboot
```

**Comment by pazos** [comment]
Mistery solved: my suggestion would be to rely on the screensaver (vs the screencover plugin) and disable that systemd service if the user doesn't need it. I think you can include it as a section in https://github.com/koreader/koreader/wiki/Installation-on-ReMarkable

Something like:

## Optional: disable system splashscreen.

The system displays stock images when is powered off and rebooted. If you want to get rid of that behaviour just do ...

**Comment by gbyl** [comment]
@pazos That definitely did it! Two small caveats though:

1. The lines below conflict with the native screensaver — they wipe it right after it loads:
https://github.com/koreader/koreader/blob/ea3fa5c2c7ed7330e8e1e6ef838b780e7998ea51/frontend/device/remarkable/device.lua#L193-L194
The solution would be to remove them, but that will bring back ghosting to users who have not switched to this new workflow. How should we deal with this conflict?

2. The screensaver image loads, but I am unable to remove the "powered off" message on the top right. Is there a setting for this?

**Comment by NiLuJe** [comment]
1. See what's done on Kobo for comparison, and the blame for the reasoning behind this change on the rM side, which I don't quite remember the details of. IIRC, we did move rM to the same power event handler than Kobo, so it should already be doing a white flash before SS. Can't do much better than that.

2. Nnngghh. :D. (c.f., overlay_message in screensaver).

**Comment by gbyl** [comment]
@NiLuJe
>Nnngghh. :D. (c.f., overlay_message in screensaver).

I see down below the purpose of the fallback message. How do you feel about adding a `[ ] Disable fallback message` under the ScreenSaver settings?
https://github.com/koreader/koreader/blob/475f46c427754d692d4a5340ebbcfcb8c407da71/frontend/ui/screensaver.lua#L389-L392

**Comment by NiLuJe** [comment]
1. Possibly with a better label, because that "fallback" nomenclature is kind of an opaque implementation detail seeping through ;).

2. Actually, there's no white flash on poweroff, period ^^. That's handled in `UIManager:init`. Poweroff is such a rare occurrence on devices without broke-ass PM that this was never really noticed before.

**Comment by gbyl** [comment]
> 1. Possibly with a better label, because that "fallback" nomenclature is kind of an opaque implementation detail seeping through ;).

I noticed that there is a top right message on reboot as well, but that one we don't want to get rid of. So, potentially just `[ ] Disable Power Off Message`?

> 2. Actually, there's no white flash on poweroff, period ^^. That's handled in `UIManager:init`. Poweroff is such a rare occurrence on devices without broke-ass PM that this was never really noticed before.

That explains everything! I know, most ereaders last 3+ weeks on suspend, not so with RM… Could we add a white flash on poweroff?

**Comment by NiLuJe** [comment]
> > 1. Possibly with a better label, because that "fallback" nomenclature is kind of an opaque implementation detail seeping through ;).
> 
> I noticed that there is a top right message on reboot as well, but that one we don't want to get rid of. So, potentially just `[ ] Disable Power Off Message`?
> 

Sounds good.

> > 1. Actually, there's no white flash on poweroff, period ^^. That's handled in `UIManager:init`. Poweroff is such a rare occurrence on devices without broke-ass PM that this was never really noticed before.
> 
> That explains everything! I know, most ereaders last 3+ weeks on suspend, not so with RM… Could we add a white flash on poweroff?

c.f., 40a78a ;)

**Comment by gbyl** [comment]
@NiLuJe Excellent! I can confirm that solves the problem once and for all. Have you merged it already? I don't see it as a PR

**Comment by gbyl** [comment]
Ghosting fixed by https://github.com/koreader/koreader/pull/7558
Screensaver override documented in [wiki](https://github.com/koreader/koreader/wiki/Installation-on-ReMarkable#optional)
