### ISSUE TITLE
android 怎么把这个当插件使用

### ISSUE THREAD

**Issue by macloujie** [koreader/koreader#7522]

**Comment by Frenzie** [comment]
"How to use this as a plug-in"

It's unclear what that means, but the relevant links are https://github.com/koreader/koreader-base and https://github.com/koreader/android-luajit-launcher

**Comment by macloujie** [comment]
Project cannot be run
Android NDK: Check that G:/Chrom/android-luajit-launcher-master/jni/luajit/build/armeabi-v7a/lib/libluajit.so exists  or that its path is correct  
![image](https://user-images.githubusercontent.com/15259940/114336744-31e3d280-9b82-11eb-8a32-bf317fe253b5.png)

**Comment by Frenzie** [comment]
Please use the README file. It explains that:

> For now - and probably ever, since Mike Pall recommends strongly to do so - the compilation of LuaJIT is not integrated into the Android build framework and has to be run separately.
>
> A wrapper script for building LuaJIT is provided. It relies on NDK r15c

And additionally it offers up `make update` and `make prepare`.
