### ISSUE TITLE
Crash when trying to delete highlight

### ISSUE THREAD

**Issue by PantsbobSpongesquare** [koreader/koreader#7526]
Kobo Clara HD
FW - 4.26.16704
KOReader v2021.03

Attempting to delete highlighted words in an EPUB file makes KOReader crash. Happens with old highlights and new ones as well. Have not had the chance to check if there's a crash on other file types. 

Crash report:

04/09/21-16:37:59 ERROR failed to call event handler onReaderReady plugins/statistics.koplugin/main.lua:805: bad argument #2 to 'format' (number expected, got nil)
./luajit: frontend/document/pdfdocument.lua:198: attempt to call method '_checkIfWritable' (a nil value)
stack traceback:
	frontend/document/pdfdocument.lua:198: in function 'deleteHighlight'
	frontend/apps/reader/modules/readerhighlight.lua:1448: in function 'deleteHighlight'
	frontend/apps/reader/modules/readerhighlight.lua:561: in function 'callback'
	frontend/ui/widget/button.lua:347: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1106: in function 'sendEvent'
	frontend/ui/uimanager.lua:209: in function '__default__'
	frontend/ui/uimanager.lua:1541: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1609: in function 'handleInput'
	frontend/ui/uimanager.lua:1655: in function 'run'
	./reader.lua:292: in main chunk
	[C]: at 0x00014131
!!!!
Uh oh, something went awry... (Crash n°1: 04/09/21 @ 16:48:14)
Running FW 4.26.16704 on Linux 4.1.15-00089-ga2737fc02713 (#34 SMP PREEMPT Fri Dec 27 17:47:13 CST 2019)
Attempting to restart KOReader . . .
!!!!

**Comment by NiLuJe** [comment]
Dupe (#7520)

**Comment by PantsbobSpongesquare** [comment]
> Dupe (#7456, fixed via #7457)

Forgive me, I'm new and know nothing about programming, what exactly is the fix?

**Comment by NiLuJe** [comment]
It's fixed in current [nightlies](http://build.koreader.rocks/download/nightly/), and a similar regression when renaming *bookmarks* will be fixed in tomorrow's.

**Comment by PantsbobSpongesquare** [comment]
> It's fixed in current [nightlies](http://build.koreader.rocks/download/nightly/), and a similar regression when renaming _bookmarks_ will be fixed in tomorrow's (~7AM UTC).

Thank you. I love you.
