### ISSUE TITLE
Sortwidget footer redesign

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7530]
Sorry for this, but the Sortwidget footer is rather ugly.

![1](https://user-images.githubusercontent.com/62179190/114312389-29948480-9afb-11eb-8394-075127670736.png)
---
Is it worth to redesign it using the standard chevrons and Cancel/Save? Kind of:

![4](https://user-images.githubusercontent.com/62179190/114312969-534eab00-9afd-11eb-9eee-3c38b54075ad.png)
---

Move up/down buttons might be kept.

**Comment by hius07** [comment]
![5](https://user-images.githubusercontent.com/62179190/114315862-9878da00-9b09-11eb-8436-569c618dec49.png)
---
![6](https://user-images.githubusercontent.com/62179190/114315866-a0d11500-9b09-11eb-89bf-c121add45786.png)
---
![7](https://user-images.githubusercontent.com/62179190/114315870-a890b980-9b09-11eb-933a-18080f00ba01.png)

**Comment by Frenzie** [comment]
Be nice. ;-)

Anyway, the second (or is that the third?) proposal looks fine to me.

**Comment by poire-z** [comment]
I agree the look is different from everything else, but I'm not meeting that SortWidget very often.
I'm fine with the proposed changes (including the big black solid triangles, it shows they apply to the solid black highlighted item).

**Comment by hius07** [comment]
> I'm not meeting that SortWidget very often.

Three times only: Status bar, Favorites, Dictionaries.

I'll polish it and make a PR.

**Comment by hius07** [comment]
Any suggestions?

---
(1)
![1](https://user-images.githubusercontent.com/62179190/114429758-65485080-9bc6-11eb-9d53-63fc100eef68.png)
---
(2)
![2](https://user-images.githubusercontent.com/62179190/114429815-73966c80-9bc6-11eb-9d93-54919c2e4bff.png)
---
(3)
![3](https://user-images.githubusercontent.com/62179190/114429874-814bf200-9bc6-11eb-9982-6809b32e5698.png)
---

**Comment by NiLuJe** [comment]
2., definitely ;).

**Comment by poire-z** [comment]
I prefer 2 too.

**Comment by hius07** [comment]
OK, thanks
