### ISSUE TITLE
FR: [add a COPY and a SHARE button to the dictionary window]

### ISSUE THREAD

**Issue by arnoulfos** [koreader/koreader#7532]
When i select a word and don t find an entry in the internal dictionary i would like to search it with an external dictionary 

Thus i d appreciate a COPY or/and SHARE button to send the word to another app without having to type it

**Comment by pazos** [comment]
setup an external dict directly instead of the internal one. Also there's a share button on the contextual menu when you highlight.

Keep in mind not all platforms support external apps, so that's pretty much the way the program works.

**Comment by arnoulfos** [comment]
When we highlight it opens directly the dictionary window. The use of the internal dictionary is faster when it works, but because of the case and accent sensitive, and because i have dictionaries in incompatible format only in some case I need to copy the word to access external dictionary

**Comment by pazos** [comment]
Use https://github.com/koreader/koreader/pull/6114 (enable on single word selection) and press the share button when you need it.

**Comment by arnoulfos** [comment]
It seems the answer but I don t understand where is single word selection option

**Comment by pazos** [comment]
gear -> document ->  highlight action.

Then each highlight will show you a contextual menu with a bunch of options. If you do that on android you'll get a bottom entry saying "share text"  which you can use with any app that can handle plain text.

**Comment by arnoulfos** [comment]
Found thanks, it would be better in the dictionary window but it is better than nothing, as for me i think I will rather not use this option to keep the dictionary window open directly and select 2 words to have the share menu and then erase the second word once in the external program.

**Comment by ater1267** [comment]
Hi, I have version 2023.04 on Android and it doesn't seem to have the "highlight action" in "gear -> document". Was this menu item moved somewhere else? Thank you!

**Comment by hius07** [comment]
Gear - Taps and gestures - Long-press on text
