### ISSUE TITLE
Hyphenation not working in Georgian text (Android)

### ISSUE THREAD

**Issue by arabuli** [koreader/koreader#7539]
* KOReader version: 2021.03
* Device: toco_eea and Boox Poke 3

#### Issue
Enabling hyphenation for Georgian language does nothing. It doesn't even show the hyphens already added with Calibre plugin Hyphenate this!

#### Steps to reproduce
Open any book written in Georgian, try to enable hyphenation.

[Example book (with soft-hyphens already in it)](https://github.com/koreader/koreader/files/6297593/kale.blumkvisti.zip)
Uploading it as .zip because .epub isn't supported.

https://user-images.githubusercontent.com/457700/114413938-b2b8c380-9bae-11eb-8012-033eab9afd46.mp4

![photo5449421455847699683](https://user-images.githubusercontent.com/457700/114412431-615c0480-9bad-11eb-9127-154e4489fc10.jpg)

**Comment by poire-z** [comment]
Reproducible on the emulator. This is really strange.

**Comment by poire-z** [comment]
OK, some bits in the hyphenation code wants to find words boundaries, to try hyphenation on each word:
https://github.com/koreader/crengine/blob/fb2091564b7c5124634a91f2121c489f78d62813/crengine/src/lvtextfm.cpp#L4109-L4127
by using this function, that only knows about latin, greek and cyrillic letters :/
https://github.com/koreader/crengine/blob/fb2091564b7c5124634a91f2121c489f78d62813/crengine/src/lvstring.cpp#L4390-L4466
So, each georgian letter makes out a single-letter word that is too short to be candidate for hyphenation (and so, even soft-hyphens don't get the chance to be checked).
We'll need to rethink this to use some other utility function or library (libunibreak, utf8proc...) that knows about letters and words better.
I won't be able to work on that for the next 2 weeks.

**Comment by poire-z** [comment]
> We'll need to rethink this to use some other utility function or library (libunibreak, utf8proc...) that knows about letters and words better.

Or may be not :)
I don't really like lStr_findWordBounds() (well, I hated it when I needed to fix it), and it would probably deserve a rewrite with proper unicode stuff.
But it's only used for hyphenation, and does its job well enough, and may be it doesn't need to be looked at more than that.
It's also one of the rare users of [getCharProp](https://github.com/koreader/crengine/blob/fb2091564b7c5124634a91f2121c489f78d62813/crengine/src/lvstring.cpp#L4327-L4347), and I was going to suggest to @arabuli to add a range of info for the [Georgian unicode block](https://en.wikipedia.org/wiki/Georgian_(Unicode_block)), some `char_props_10a0` like [char_props_1f00](https://github.com/koreader/crengine/blob/fb2091564b7c5124634a91f2121c489f78d62813/crengine/src/lvstring.cpp#L4087-L4090), distinguishing vowers from consonants, upper from lower, punctuations, etc...
(And I would have been curious to learn more about the Georgian script - although I guess I can learn a lot at https://r12a.github.io/scripts/georgian/ which I'll read later :)

But we might not even need to do that. We can delegate guessing if things among other ranges are letters to utf8proc with just:
```diff
--- a/crengine/src/lvstring.cpp
+++ b/crengine/src/lvstring.cpp
@@ -4327,38 +4327,56 @@ CH_PROP_UPPER | CH_PROP_VOWEL, // GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
 inline lUInt16 getCharProp(lChar32 ch) {
     static const lChar32 maxchar = sizeof(char_props) / sizeof( lUInt16 );
     if (ch<maxchar)
         return char_props[ch];
     else if ((ch>>8) == 0x1F)
         return char_props_1f00[ch & 255];
     else if (ch>=0x2012 && ch<=0x2015)
         return CH_PROP_DASH|CH_PROP_SIGN;
     else if (ch==0x201C) // left double quotation mark
         return CH_PROP_AVOID_WRAP_AFTER;
     else if (ch==0x201D) // right double quotation mark
         return CH_PROP_AVOID_WRAP_BEFORE;
     else if (ch>=UNICODE_CJK_IDEOGRAPHS_BEGIN && ch<=UNICODE_CJK_IDEOGRAPHS_END&&(ch<=UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_BEGIN||
                                                                                   ch>=UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_END))
         return CH_PROP_CJK;
     else if ((ch>=UNICODE_CJK_PUNCTUATION_BEGIN && ch<=UNICODE_CJK_PUNCTUATION_END) ||
              (ch>=UNICODE_GENERAL_PUNCTUATION_BEGIN && ch<=UNICODE_GENERAL_PUNCTUATION_END) ||
              (ch>=UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_BEGIN && ch<=UNICODE_CJK_PUNCTUATION_HALF_AND_FULL_WIDTH_END))
         return CH_PROP_PUNCT;
+#if (USE_UTF8PROC==1)
+    else {
+        // For other less known ranges, fallback to detecting letters with utf8proc,
+        // which is enough to be able to ensure hyphenation for Armenian and Georgian.
+        utf8proc_category_t cat = utf8proc_category(ch);
+        switch (cat) {
+            case UTF8PROC_CATEGORY_LU:
+            case UTF8PROC_CATEGORY_LT:
+                return CH_PROP_UPPER;
+            case UTF8PROC_CATEGORY_LL:
+            case UTF8PROC_CATEGORY_LM:
+            case UTF8PROC_CATEGORY_LO:
+                return CH_PROP_LOWER;
+            default:
+                break;
+        }
+    }
+#endif
     return 0;
 }
```
We would even not need this clumsy upper/lower distinction, that is not used anywhere.
The more precice categorisation of consonant/vowel would only help ensuring "algorithmic hyphenation", which feels not needed (and most probably bad).

Do these look alright?
<kbd>![image](https://user-images.githubusercontent.com/24273478/114449231-0bdf2200-9bc4-11eb-8e7b-8053d5d6e1a4.png)</kbd>
<kbd>![image](https://user-images.githubusercontent.com/24273478/114449268-14cff380-9bc4-11eb-9f35-4612946a1f39.png)</kbd>
(Rarely some differences between Hyph dict georgian vs. Soft-hyphens only, but I found one on this page.)

(These glyphs come from FreeSans - FreeSerif also has some, with some looking quite different:
<kbd>![image](https://user-images.githubusercontent.com/24273478/114450210-42696c80-9bc5-11eb-8d1d-50f6bdc7aead.png)</kbd>
Do these both look ok?)

**Comment by arabuli** [comment]
Hey @poire-z,

Everything is looking fine on your screenshots.

I guess that one difference of Hyph dict georgian vs. Soft-hyphens is caused because the word itself contains hyphen already (her name, which is Eva-Lota).

On the third image, even though they look little bit different both of the characters are same. That symbol with pointed belly is more official and older looking version of წ.

P.S. If you want to know anything about Georgian language I would gladly answer your questions (:
