### ISSUE TITLE
Android night builds are missing

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#7541]
* KOReader version: 2021-03-35
* Device: Android

#### Issue
No recent night builds for Android (neither for ARM nor for x86) on ota.koreader.rocks. Latest apk files available are for version  2021-03-35 from 6th April.  
#### Steps to reproduce
Try OTA upgrade or open [ota.koreader.rocks](https://ota.koreader.rocks) in browser

**Comment by Frenzie** [comment]
A fix is incoming, no need to worry. :)

**Comment by NiLuJe** [comment]
Today's nightly should have been fixed, but connectivity issues (LuaRocks, framagit, among others) left and right mean that most builds didn't complete successfully.
