### ISSUE TITLE
Design improvements in frontlight dialogue and ToC

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#7548]
I have three suggestions for design improvements which hopefully shouldn't be too difficult to do. 

1) This is what the frontlight dialogue looks like now:
![20210414_115748](https://user-images.githubusercontent.com/15887012/114692986-6f2e9880-9d19-11eb-937c-3ab43b21d9b6.jpg)
I would like the scales for brightness and warmth to look the same. Also, it would be great to remove the inconsistency when both brightness and warmth are turned to zero, i.e. the scale for warmth shouldn't show the first square in black.

2) Regarding the ToC, it would be more user-friendly if the next page of the ToC is shown automatically when you expand the item at the bottom. Currently, when you press the item, the arrow points down and shows that there are sub-entries, but you have to go forward manually to see them.
![20210414_115623](https://user-images.githubusercontent.com/15887012/114693771-393de400-9d1a-11eb-8afb-906bca6fd46f.jpg)

3) Finally, I would really appreciate it if the margins in the ToC pop-up would be synced, i.e. the left margin should be the same width as the top margin. The way it is now it looks too small and kind of cramped at the left edge.
![20210414_115705](https://user-images.githubusercontent.com/15887012/114694068-7c985280-9d1a-11eb-9c67-90f4c7d1d042.jpg)

**Comment by NiLuJe** [comment]
IIRC, there may be a semi historical reasoning behind the Warmth bar. Either because it wasn't always [0, 100], or because it doesn't support swiping, or... something. :D.

**Comment by NiLuJe** [comment]
Ah, no, it's that the granularity is much, much lower, and as such the big squares make it slightly easier to make that point across.

**Comment by LucyOne** [comment]
Is that a point a regular user would have in mind? I just find it highly illogical that the first square would stay black on one scale and not on the other with both on zero.

**Comment by NiLuJe** [comment]
No, that's just a design quirk of the widget, which wasn't really designed for this initially ;).

**Comment by hius07** [comment]
> 3\. the left margin should be the same width as the top margin

I changed 0 to 10 and it looks okay
https://github.com/koreader/koreader/blob/7092df7f4e09f595239afee0706ce20609abefd1/frontend/ui/widget/infomessage.lua#L156

**Comment by poire-z** [comment]
> Regarding the ToC, it would be more user-friendly if the next page of the ToC is shown automatically when you expand the item at the bottom. Currently, when you press the item, the arrow points down and shows that there are sub-entries, but you have to go forward manually to see them.

I'm not sure it would be user friendly. It's an edge case for the last item on the page - but having the view auto-jumping to next page might be surprising (and would be an edge-case change of behaviour).
Feels safer/saner with the current behaviour to me.

**Comment by LucyOne** [comment]
If I press the arrow to expand the last item on the page, I expect and want to see something new - not just the arrow pointing to another direction. I find that pretty annoying.

**Comment by NiLuJe** [comment]
A "clever" hack to bypass this would possibly be avoiding putting a collapsed entry as the last entry ofa page. WHich would leave a blank (think widows/orphans).

Stupid off-the-cuff idea, I'm not sure it'd actually be any easier to implement, and it would *also* look somewhat weird ;).
