### ISSUE TITLE
Distinguish files and folders

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7554]
Yes, [Everything is a file](https://en.wikipedia.org/wiki/Everything_is_a_file), but isn't an average user confused with these dialogs?

![del1](https://user-images.githubusercontent.com/62179190/115012283-54def100-9eb8-11eb-939b-3cf2be0d8fb1.png)
---
![del2](https://user-images.githubusercontent.com/62179190/115012298-58727800-9eb8-11eb-90f9-7e79568081ee.png)
---
Shouldn't we show more user-friendly dialogs distinguishing files and folders?

**Comment by NiLuJe** [comment]
Some of these might already be making the distinction in terms of what options to display, which might help.

**Comment by hius07** [comment]
Yes, I'm going to propose some changes in the dialogs soonest (including wordings unification).

**Comment by NiLuJe** [comment]
No rush, as this will involve translation tweaks, so it'll be post-2021.04 anyway ;).

**Comment by hius07** [comment]
Current wordings

![1](https://user-images.githubusercontent.com/62179190/115188851-35310e00-a0ee-11eb-852d-d7c73b0e51b9.jpg)

**Comment by hius07** [comment]
Proposed changes
(1) distinguish file/folders where important
(2) input dialogs: unify titles, deny blank input
(3) ok infomessages: “info” icon, timeout 2 sec to disappear
(4) error infomessages: “exclamation” icon, tap to dismiss
(5) everywhere: show filename in a separate line for easy reading

Screenshots with proposed wordings will follow.

**Comment by hius07** [comment]
A small issue when deleting system hidden files

![2](https://user-images.githubusercontent.com/62179190/115189238-dae47d00-a0ee-11eb-8af3-0c7da466ae5d.png)

File was not deleted, no error message shown. Seems no error returned in
https://github.com/koreader/koreader/blob/9988eab1a17d77dd9307f467ff7ecccc775a7c59/frontend/apps/filemanager/filemanager.lua#L952

**Comment by Frenzie** [comment]
Is the behavior different with a simple shell `rm`?

**Comment by hius07** [comment]
> Is the behavior different with a simple shell `rm`?

I'll try.

**Comment by NiLuJe** [comment]
No, you can't delete ghost fuse files if the fd it's attached to is still live.

**Comment by Frenzie** [comment]
> No, you can't delete ghost fuse files if the inode it's attached to is/was still live.

It wasn't really a genuine question, more of a Socratic basic debugging suggestion, although it's definitely always good to double check. ;-)

**Comment by NiLuJe** [comment]
That happens to be a weird Kindle quirk, which is why I butted in ;).

**Comment by hius07** [comment]
Wordings to discuss.

![00](https://user-images.githubusercontent.com/62179190/115397062-5416c980-a1ee-11eb-8cbb-2e8a9d5019a8.png)

**Comment by hius07** [comment]
Dialogs (unified titles, denied blank input)

![01](https://user-images.githubusercontent.com/62179190/115397132-6c86e400-a1ee-11eb-9bfc-337215c19351.png)

**Comment by hius07** [comment]
OK infomessages (timeout = 2)

![02](https://user-images.githubusercontent.com/62179190/115397185-7f011d80-a1ee-11eb-9949-66ce68ce7b9c.png)

**Comment by hius07** [comment]
Error infomessages (tap to dismiss)

![03](https://user-images.githubusercontent.com/62179190/115397236-8cb6a300-a1ee-11eb-8588-e7b9a6a8a391.png)

**Comment by Frenzie** [comment]
I'd just say

New folder
[…]
Cancel/Create

Instead of "enter new folder name"

Same for the others.

**Comment by hius07** [comment]
> Instead of "enter new folder name"

I try to unify all input dialogs.
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/apps/filemanager/filemanagerfilesearcher.lua#L90
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/apps/reader/modules/readersearch.lua#L41
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/ui/widget/dictquicklookup.lua#L1210
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/ui/widget/menu.lua#L744
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/ui/widget/keyvaluepage.lua#L431
And so on.

**Comment by Frenzie** [comment]
That's not a goal in and of itself, but something like:

* Text to search for/Find text
* Word or phrase to look up/Find word or phrase
* Go to page number or letter
* Go to page number

**Comment by hius07** [comment]
Sure, `title` can be the "name of the operation" or the "verb in imperative mood".
Both are OK, mixing is not.
I thought we had discussed that in the search dialogs PRs and approved the latter.

**Comment by Frenzie** [comment]
A certain degree of consistency is merely a means to attaining a higher degree of predictability, that is the ability for a user to learn the program. Always cancel left, perform action right. If consistency results in a phrase like *enter folder name* or *input folder name* just to abide by some guideline about imperative verbs then consistency be damned.

A mixture is fine provided it's on purpose. That's why `new folder name` can be combined with `go to page number`. Page number? What does that mean exactly? New folder name? Completely clear. Enter new folder name? Unnecessarily wordy at best. Put another way, it's consistent with being short, pleasant and to the point. Consistency is but one part of our arsenal for achieving clarity and predictability. It's always a good thing to consider, but it should not stand in the way.

PS That's no different for any other program.
![Screenshot_20210420_161801](https://user-images.githubusercontent.com/202757/115411768-0ef59600-a1f4-11eb-88d3-f5f8a698ae22.png)

**Comment by hius07** [comment]
So, `New folder`, `Rename folder`, `Rename file`.

**Comment by Frenzie** [comment]
Sounds good to me. :+1:

**Comment by hius07** [comment]
I'll collect other corrections (if any) and make a PR as recommended

> it'll be post-2021.04 anyway

**Comment by hius07** [comment]
I doubt if we need fullpath name in the OK infomessages for `Renamed folder`, `Renamed file`, and for source in `Copied` and `Moved`. Seen 2 sec only.
Maybe just name would be enough?

**Comment by Frenzie** [comment]
Not for renamed and such, but maybe for moved/copied?

**Comment by hius07** [comment]
Recent changes

![01](https://user-images.githubusercontent.com/62179190/115547335-d36bd200-a2ae-11eb-8e57-d2a241a8f0bd.jpg)

**Comment by Frenzie** [comment]
Seems fine to me.

**Comment by Frenzie** [comment]
I believe this is done now? Please reopen if not.
