### ISSUE TITLE
How to read .cbz on KOReader ?

### ISSUE THREAD

**Issue by RAPHCVR** [koreader/koreader#7555]
Hey, can u explain to me how to read .cbz files on KOReader, right now, it shows me "No reader engine for this file or invalid file".
How to proceed ?

**Comment by NiLuJe** [comment]
That means your file isn't actually a CBZ (i.e., a zip file with a fancy extension).

Make sure your file isn't actually lying, and is actually a ZIP, not a RAR, a 7Z or a Tarball.

**Comment by RAPHCVR** [comment]
Ok, thx for the fast answer, i will try

**Comment by RAPHCVR** [comment]
We can unzip the file indeed, so what can I do to read this with KOReader please ?

**Comment by roshavagarga** [comment]
@RAPHCVR Extract the files within that file, use something like PeaZip to create a zip file. Once created - change it from .zip to .cbz

Github isn't meant for questions like these - please close this issue and in the future consult a search engine :)

**Comment by RAPHCVR** [comment]
I tried but no success, I saw that I can convert into a PDF, the easiest way, how to read a PDF with MuPDF, the best reader as I understand (I promise to close this issue after an answer, thanks again for your time).
