### ISSUE TITLE
Bug or Feature?: bottom status bar is shown when charging (device in sleep mode)

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#7556]
* KOReader version: 2021.03-35 (and latest, 3-53)
* Device: KA1

Never seen it before.

If it is a feature - the battery level updates only after disconnect: is that a bug or feature?  :-)

**Comment by NiLuJe** [comment]
That would be a bug ;).

What are your screensaver settings and status bar settings?

**Comment by gerhaher** [comment]
Use last book's cover as screensaver

Alt status bar off

Show all at once, auto refresh, show footer separator, hold footer to skim

Cuttent page, current time, Pages left in chapter, Battery status

**Comment by gerhaher** [comment]
I kind of like it: checking battery level by disconnecting instead of waking the device....it could be argued that it's an improvement :-)

**Comment by NiLuJe** [comment]
I assume this doesn't happen if you disable auto refresh?

**Comment by NiLuJe** [comment]
And, since you've mentioned disconnecting: does it show *before* disconnecting? When/how are you connected (relative to the start of the suspension).

**Comment by NiLuJe** [comment]
And is this *inside* a book, or the FM? (and, if in a book, which kind? ePub? PDF?).

**Comment by gerhaher** [comment]
> I assume this doesn't happen if you disable auto refresh?

Incorrect. It happens.

> And, since you've mentioned disconnecting: does it show before disconnecting? When/how are you connected (relative to the start of the suspension).

1. Device in suspense
2. Connect. Status bar appears immediately.

or

1. Device on
2. Connect. 
3. Start suspension
4. Disconnect. Status bar appears.

> And is this inside a book, or the FM? (and, if in a book, which kind? ePub? PDF?).

It only happens from the Reader (not the browser). Any book (epub, pdf).
