### ISSUE TITLE
[Legacy Kindle/K3GB] Left buttons are bound incorrectly 

### ISSUE THREAD

**Issue by jimbob88** [koreader/koreader#7561]
* KOReader version: 2021.03
* Device: Kindle 3GB [Legacy Kindle]

#### Issue
When reading a book, the button's on a Kindle 3GB are the same on both the left and right sides, as can be seen below ([Source](https://www.amazon.co.uk/Amazon-Kindle-3g-with-Keyboard/dp/B002FQJT3Q)):
![image](https://user-images.githubusercontent.com/9913366/115110937-b31dd980-9f75-11eb-8196-3322875bda83.png)
On the right-side the book turning is correct as the top-most button goes back and the bottom-most button turns the pages forwards. The issue occurs on the left hand side as the top-most button turns forwards and the bottom-most button goes backwards. On the kindle 3GB both the left and right buttons should be addressed in the same way.

#### Steps to reproduce
Open any book (I opened KJV Bible in the `.epub` format as a point of reference), the try the right buttons (which should be correct, top moving backwards, and bottom moving forwards) but the left side currently moves forwards with the top button and backwards with the bottom button (even though it has a forward label)

**Comment by NiLuJe** [comment]
That's... interesting. Are you actually reading in Portrait?

**Comment by NiLuJe** [comment]
The mapping is indeed inverted between the K4 & K3, which is... surprising.
