### ISSUE TITLE
 [Legacy Kindle/K3GB] Update button doesn't stop book movement

### ISSUE THREAD

**Issue by jimbob88** [koreader/koreader#7562]
* KOReader version: 2021.03
* Device: Kindle 3 GB [Legacy Kindle]

#### Issue
When running the update dialogue as part of the Koreader menu, if you have a book open any movement buttons you press (on DPAD in the bottom right hand side) move forward and change the pages of the book.
#### Steps to reproduce
Install a previous version of Koreader, take for example 2021.02-34, and install it to a Kindle 3GB (I am not sure if this effects other legacy kindles because I only own a K3GB) and press the update Koreader button with a book open (I had KJV in the `.epub` format open) and then press the Update Koreader button, after a while a popup will appear that asks if you want to change your version to the latest edition and you press yes. The problem occurs when the secondary popup appears and asks you if you want to download the update as the buttons to move around the book still work and so when moving to check the `yes` button the book reloads in the background as it changes pages and loses your place.

**Comment by jimbob88** [comment]
Error doesn't occur on `202103000000`, closing as fixed

**Comment by NiLuJe** [comment]
Well that's... interesting :D.

I don't think there was a fiverway/pageturn button conflict in the mapping, but, oh, well, I'll take it ;).
