### ISSUE TITLE
Kobo Clara HD (Kobo_nova) battery drain while suspended

### ISSUE THREAD

**Issue by YariFranceschi** [koreader/koreader#7565]
* KOReader version: 2021.03 (also 2021.02)
* Device: Kobo Clara HD (bought on February 2021)

While on suspension (by pressing the button) after a few hours, I found the battery drained, up to about 30% overnight. I am sure I put it on suspension because the screen changes, backlight goes off and its set to go into suspension automatically after 20 min anyway.
Using it once or twice a day, this problem happens about twice a week.
The original software from Kobo is up to date.

**Comment by NiLuJe** [comment]
Check the logs.

I assume you're using a smart cover?

**Comment by YariFranceschi** [comment]
> Check the logs.
> 
> I assume you're using a smart cover?

I did use a smatr cover.
i then disabled all events from the smart cover but the drain still happen.

**Comment by NiLuJe** [comment]
Can't tell you anything without logs ;).

**Comment by YariFranceschi** [comment]
Hi @NiLuJe 
here is the crash.log and the defaults.lua (.txt).
It's the first time I take a look at this file but seems to me there's lots of action in the crash.log.
Maybe someome can figure out the problem? 

[crash.log](https://github.com/koreader/koreader/files/6330790/crash.log)
[defaults.txt](https://github.com/koreader/koreader/files/6330791/defaults.txt)

**Comment by NiLuJe** [comment]
Yep, your smart cover is indeed borked as all hell and keeps waking up the device.

We correct for occasional errors, but after a certain point, we give up and leave the device on.

(As I hinted above, the option to ignore the smart cover doesn't change the fact, it controls whether we wake up *KOReader*, we can't do anything about the fact that it wakes the *device* up, that's too low-level).

**Comment by YariFranceschi** [comment]
Thank you for the suppprt. 👍
I'lm getting rid of my dumb smart cover.
