### ISSUE TITLE
Default menu gestures clash with android

### ISSUE THREAD

**Issue by QJKX** [koreader/koreader#7575]
* KOReader version: V2021.03
* Device: Android 10+ Tablet.  No physical Navigation bar buttons.

#### Issue
Swiping up from the bottom of the screen shows the KOReader menu, but with the Android Navigation Bar on top of it. (After a few moments the navigation bar autohides again). The same thing happens with the top of the screen and the status bar.

#### Proposed Solution
Probably the cleanest solution would be to have a menu-overlay mode toggled by tapping the middle ninth of the screen (the other eight nineths are probably best reserved for page turning).

The menu overlay mode should make the Android navigation bar and top bar appear (like Google drive pdf reader) and make the KOReader menu buttons appear further in than the Android bars. The rendering resolution should not change so that changes made by the rendering controls have exactly the same effect as normal full screen mode.
The Android gestures (Navigation Bar) should be left entact by default, so it's not easy for unfamiliar users to get stuck in the app. It will also keep the standard way of checking Android notifications working as expected.

**Comment by QJKX** [comment]
In fact I can avoid this whole issue by starting my menu swipes not too near the edge of the screen.

**Comment by Frenzie** [comment]
Also note Settings → Taps & gestures → Activate menu.

<img src=https://user-images.githubusercontent.com/202757/115457507-ee91ff80-a224-11eb-9c00-b7aa6f317fc3.png width=50%>

**Comment by ryanwwest** [comment]
> Also note Settings → Taps & gestures → Activate menu.
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/202757/115457507-ee91ff80-a224-11eb-9c00-b7aa6f317fc3.png">

I'm glad this option exists, but should 'swipe' be disabled by default for Android 10+ devices since this is very likely to collide otherwise? It does for all my Android devices until I change it.

**Comment by Frenzie** [comment]
I find it more convenient and less conflicting than tapping myself, but yes, on Android you have to do it near the top/bottom instead of at the top/bottom.

I didn't investigate if it's technically feasible without big changes, but I'd propose to ask the first time you activate the menu with a swipe?

**Comment by ryanwwest** [comment]
If it's not tto difficult to implement, yes that would be ideal.
