### ISSUE TITLE
Wallabag missing example settings file  

### ISSUE THREAD

**Issue by mediaformat** [koreader/koreader#7576]
#### Issue
I would like to [manually configure Client access](https://github.com/koreader/koreader/wiki/Wallabag) to Wallabag server, using `settings/wallabag.lua` as mentioned in the wiki.

**The wiki suggests generating an empty wallabag.lua settings**
> you might prefer to save the empty settings and edit the config file directly in your installation directory's settings/wallabag.lua

However, on legacy Kindle devices attempting to save Wallabag server settings is not possible because the modal action defaults to _Cancel_, and lateral navigation to access _Save_ is not functional. 

**Please add example wallabag.lua settings to the wiki.**
A clear and concise description of what you'd like to happen.

**I unsuccessfully tried to generate my own**
```
return {
    ["server_url"] = "https://wallabag.example.com",
    ["client_id"] = "example123",
    ["client_secret"] = "example123",
    ["username"] = "user1",
    ["password"] = "pass1"
}

```

**Additional context**
Also the downloads directory doesn't seem configurable via settings/wallabag.lua

**Comment by Frenzie** [comment]
Perhaps some other other ones are necessary as well.
```
-- we can read Lua syntax here!
return {
    ["wallabag"] = {
        ["articles_per_sync"] = 30,
        ["client_id"] = "",
        ["client_secret"] = "",
        ["download_queue"] = {},
        ["filter_tag"] = "",
        ["ignore_tags"] = "",
        ["is_archiving_deleted"] = false,
        ["is_auto_delete"] = false,
        ["is_delete_finished"] = true,
        ["is_delete_read"] = false,
        ["is_sync_remote_delete"] = false,
        ["password"] = "",
        ["remove_finished_from_history"] = false,
        ["server_url"] = "",
        ["username"] = "",
    },
}
```

**Comment by mediaformat** [comment]
Thanks for the example!
I have added this (with my own server settings) to the `/koreader/settings/wallabag.lua` file, but when I attempt to _Retrieve new articles from the server_, the modal advises to _Please configure the server settings and set a download folder_.

I also tried placing the file at `/settings/wallabag.lua`, not sure why it's not being recognized.

**Comment by NiLuJe** [comment]
Definitely inside the existing settings folder in koreader's folder (so, `koreader/settings/wallabag.lua`).

You'll need to restart KOReader, too (and, err, possibly do that without KOReader running at all in the first place, actually).

**Comment by mediaformat** [comment]
I restarted KOReader and restarted the Kindle, and it isn't taking.

But the more I think about it, the less comfortable I am storing username and password in clear text like this. 
A token would be better, but I guess that is an upstream issue: https://github.com/wallabag/wallabag/issues/2800

**Comment by Frenzie** [comment]
You'll also need a `["directory"] = "/bla/bla/wallabag-or-something",` then.

**Comment by Commodore64user** [comment]
> However, on legacy Kindle devices attempting to save Wallabag server settings is not possible because the modal action defaults to Cancel, and lateral navigation to access Save is not functional.

If i understand this correctly, this is another ticket that could be closed as well. 

This predates comphill's magnificent updates so should work now...
