### ISSUE TITLE
Unsupported documents: do not add to History

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7577]
Currently there are two ways to add an unsupported document to the History list:
(1) File manager - long-press - Open with... - Cool Reader engine (this invokes ReaderUI)
(2) By changing the extension of a supported document which is already in the History, via File manager - Rename file

Any unsupported document cannot be opened from the History.
Moreover, trying to open the unsupported document via `main menu - Previous` causes KOReader to quit.

These options should be blocked by checking `DocumentRegistry:getProviders(file) ~= nil`.
I wonder where are the best places to check and block?

**(1)** When opening or renaming
https://github.com/koreader/koreader/blob/ea3fa5c2c7ed7330e8e1e6ef838b780e7998ea51/frontend/apps/reader/readerui.lua#L577
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/apps/filemanager/filemanager.lua#L984

**(2)** Or directly in the readhistory
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/readhistory.lua#L269
https://github.com/koreader/koreader/blob/14f9f9d3fcd7a8bd6664bd2dba641efe227f3529/frontend/readhistory.lua#L240

**Comment by Frenzie** [comment]
"Blocking" seems to suggest a very particular solution that may be suboptimal?

**Comment by hius07** [comment]
Do you mean, let History contain unsupported documents?

**Comment by Frenzie** [comment]
I don't know if it currently does so by someone's explicit design or merely as an accident, but not quite, no.

What I mean is that blocking implies denying an attempt to add something to history at some point. The obvious alternative — but perhaps not obvious within the code? — would be to simply avoid trying to add anything until after success.

But now having taken a quick peek, the code already contains this:
https://github.com/koreader/koreader/blob/ea3fa5c2c7ed7330e8e1e6ef838b780e7998ea51/frontend/apps/reader/readerui.lua#L723-L747

Are you saying that's not working?

**Comment by hius07** [comment]
When we open an unsupported document via Open with... dialog, there is no failure.
`one_time_providers` is used to open the document.
https://github.com/koreader/koreader/blob/ea3fa5c2c7ed7330e8e1e6ef838b780e7998ea51/frontend/ui/widget/filechooser.lua#L524-L532

**Comment by Frenzie** [comment]
Then perhaps that should be solved, rather than "blocking" anything. I just don't want to depart from the assumption of a particular solution to the problem.

**Comment by hius07** [comment]
> Then perhaps that should be solved

What exactly do you mean?
I proposed to block one thing only: adding unsupported documents to the History.

Alternative solution is to allow opening unsupported documents from the History.
As I understand, that contradicts to the main conception of the program.

**Comment by NiLuJe** [comment]
What @Frenzie is saying if that if the code is fixed to never actually add unsupported documents to the history (no matter how they were opened), the point becomes moot ;).

**Comment by hius07** [comment]
Excuse me, cannot catch the idea.
Should the History contain unsupported documents or not?

**Comment by Frenzie** [comment]
Let's take a step back. What's the problem exactly?

**Comment by hius07** [comment]
Assume the last opened document is an unsupported document.
(1) Tapping on it in the History doesn't open it.
(2) Pressing menu `Hamburger - Last` forces KOReader to quit.
(3) If selected Start with: last file, on start shows a message "File is not supported" falling back to the file browser.

**Comment by Frenzie** [comment]
Okay, thank you. So if I understand correctly, the problem is that a file in history would assume a provider, but unless you tick the box to set one for the filetype or for the specific file, there won't be one. In other words, there is no failure, only a successfully opened file?

**Comment by hius07** [comment]
> there is no failure

Yes, there is no failure, as I wrote earlier.

So, now we have a document in the History that
cannot be opened from the History
cannot be opened from the Last menu
cannot be opened on start
Is it okay to add such item to the History? It's not an issue, just design.

**Comment by Frenzie** [comment]
Since there is no failure involved business as usual would be expected. That means adding to history and opening from history.

Or is there a reason besides the current behavior not to want them in history?

**Comment by hius07** [comment]
> That means adding to history and opening from history

and opening from menu Last and opening on start if `Start with: last document`.

So, it remains to enable all of that features.

**Comment by Frenzie** [comment]
@yparitcher fixed the one real issue. :+1: The rest is less bad.

**Comment by hius07** [comment]
What do you think, is it a good idea to show Open with... dialog
https://github.com/koreader/koreader/blob/ea3fa5c2c7ed7330e8e1e6ef838b780e7998ea51/frontend/ui/widget/filechooser.lua#L586
instead of the message
https://github.com/koreader/koreader/blob/dde3c80e73800b1e3fbcaff17961c4f76b49922f/frontend/apps/reader/readerui.lua#L495

**Comment by NiLuJe** [comment]
IIRC, the unsupported message is show when we don't have *any* engine for it. As such, showing the Open with dialog for those doesn't really make sense, because you'd still have no engine to open it with?

Unless I'm missing something, in which case, more details about that scenario, please ;).

**Comment by Frenzie** [comment]
@hius07 
> What do you think, is it a good idea to show Open with... dialog

Possibly, but I think it might make more sense to store a last_provider or something. A bit like the "always open this file with…" except at the end rather than the front.

@NiLuJe 
> Unless I'm missing something, in which case, more details about that scenario, please ;).

https://github.com/koreader/koreader/pull/5129

**Comment by Frenzie** [comment]
I'm inclined to think the text should be changed to `unknown`.
