### ISSUE TITLE
FR: A horizontal line indicating where the "bottom" of the last page is for multicolumn pdf reading

### ISSUE THREAD

**Issue by shuhaowu** [koreader/koreader#7587]
Note: I'm interested in trying to add this feature myself and sending a PR. I'm simply documenting the idea here in case it's already a feature that exists that I can't find, or if I don't get around to it.

**Does your feature request involve difficulty completing a task? Please describe.**
Let's say you're reading 2 column PDFs, in the direct of a `N` (common for 2col papers). When you press the next page button on your kobo, it will typically move you downward in the page by a bit (depending on your vertical overlap setting). This for me is extremely disorienting, as I don't really know where is the last line that I read.

You could theoretically set your vertical overlap to zero, but this doesn't help when you're near the bottom of your page, as chances are your device is not a perfect multiple of the actual PDF size. This is especially painful for N-direction reading, as koreader needs to jump to the next column, but at the top of the same page, which means that when you press the next page near the bottom of the first column, koreader can only scroll you to the bottom of the page, which usually means it results in significant vertical overlap (despite having the vertical overlap setting turned to 0).

**Describe the solution you'd like**
When I press the next page button when reading in this mode (may apply to single column PDF as well), I would like to draw a grey line on the page that coincides with where the bottom of the screen were before page transition.

Generalizing this, it may be a good idea to draw a line at where the previous screen was located (horizontal and vertical lines), for PDF reading in other directions.

**Describe alternatives you've considered**
You could theoretically animate, but this is not feasible on low-refresh-rate e-ink devices. The other thing you can do is set-up vertical overlap top 0, then when you scroll to the bottom of the first column, instead of overlapping, simply fill the "bottom" section with blank. This approach has a worse usability tho, because of a different reason: occasionally you want some vertical overlap so certain lines of texts are not cutoff. If we don't implement the hint line approach, then vertical overlap feature remains to not be usable.

**Additional context**
N/A.

**Comment by NiLuJe** [comment]
Sidebar: I assume you meant an upside-down `N`? (i.e., Left column, Top-to-Bottom, back to Top on Right column, to Bottom).

**Comment by NiLuJe** [comment]
I'm not a PDF person, but I don't quite understand what's not working with the current page/arrow overlap setting in this case? (screenshots, maybe?).

**Comment by shuhaowu** [comment]
> Sidebar: I assume you meant an upside-down `N`? (i.e., Left column, Top-to-Bottom, back to Top on Right column, to Bottom).

Yes

> I'm not a PDF person, but I don't quite understand what's not working with the current page/arrow overlap setting in this case? (screenshots, maybe?).

How about this (badly drawn) diagram?

![image](https://user-images.githubusercontent.com/338100/115896640-a3950980-a429-11eb-825b-db5be2b700a5.png)

**Comment by NiLuJe** [comment]
That's precisely what the overlap arrow should be doing?

**Comment by shuhaowu** [comment]
Oh neat. I couldn't find that feature before... Thanks for the help.

It may be nice if we can do both arrow and dim, but that can be done in a separate issue.
