### ISSUE TITLE
0.7 zoom factor overlap: wrong gray-out area

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7590]
* KOReader version: 2021.04
* Device: KPW3

#### Issue
When using 0.7 zoom factor of pan zoom mode (the icon with % in the third bottom tab), the gray-out area is drawn smaller than it should be.

#### Steps to reproduce
Zoom to: pan zoom mode
Zoomfactor: 0.7
Horizontal overlap: 0 (so it should be just 1 column)
Direction: default (the first choice)

Page's top part:
![Reader_2021-04-23_213907](https://user-images.githubusercontent.com/6279855/115944793-09af7a00-a486-11eb-990c-bf81497b6909.png)

Page's bottom part, after a tap:
![Reader_2021-04-23_213917](https://user-images.githubusercontent.com/6279855/115944794-0a481080-a486-11eb-9251-c84c6a28182c.png)

**Comment by NiLuJe** [comment]
Does it magically fixes itself after crossing a (PDF) page boundary?

**Comment by mergen3107** [comment]
If you mean going to the next page, no, it is consistent every page. So every second screen of a page has that smaller grayed-out area. Looks like at zoom level 0.7 it takes 0.7 of pdf page width to gray out. With zoom level 1.5 it grays out the correct width. 

It is also consistent going backwards

**Comment by NiLuJe** [comment]
I meant specifically crossing a PDF page boundary, which may be significantly farther away than a single "page" turn action ;).

**Comment by mergen3107** [comment]
Emm, I can only do two screens on a page because the pages are not that long

**Comment by mergen3107** [comment]
I cannot reproduce this issue anymore :D 
In fact, 0.7 zoom probably now works as it should - it zooms out. Back then it zoomed… in?)
