### ISSUE TITLE
macOS: Must force quit when a book is open

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#7593]
* KOReader version: 2021.04-9
* Device: macOS

#### Issue

You must force-quit Koreader when a book is open. Cmd-Q and hitting the close button do not work.

The window blanks for a moment, then redraws the page, and then goes unresponsive.

All quit options work fine at the File Browser screen.

#### Steps to reproduce

Open a book
Hit Cmd-Q or the close button

##### `crash.log` (if applicable)

Crash log attached. The last lines are:

04/24/21-09:44:14 INFO  initializing for device Mac OS X
04/24/21-09:44:14 INFO  framebuffer resolution: {
    ["h"] = 682,
    ["w"] = 547,
}

[crash.log](https://github.com/koreader/koreader/files/6369722/crash.log)

**Comment by NiLuJe** [comment]
Ah, fun fact: we now require macOS 10.12 because everything is terrible and that's the first version supporting `clock_gettime` (POSIX.1-2001 / SUSv2, good job Apple >_<").

**Comment by NiLuJe** [comment]
And, of course, they're using incompatible constants for the various clock ids... >_<".

**Comment by NiLuJe** [comment]
In case that did not do the trick, post *verbose* debug logs the next time ;).

**Comment by JasonInOttawa** [comment]
This does work for me - thanks very much!

I will post a verbose log next time.
