### ISSUE TITLE
Missing KOReader 2021.04 versions for Remarkable and Sony Reader.

### ISSUE THREAD

**Issue by ludoft** [koreader/koreader#7594]
koreader-remarkable-v2021.04.zip and koreader-sony-prstux-v2021.04.zip are both missing from the [latest release](https://github.com/koreader/koreader/releases/tag/v2021.04).

**Comment by NiLuJe** [comment]
Fixed, thanks for the heads up ;).

**Comment by Frenzie** [comment]
I'm not sure what happened there, my bad. I was probably 30 seconds too fast. ;-)

**Comment by NiLuJe** [comment]
Yeah, the rM one was flagged in-progress, FWIW ;).
