### ISSUE TITLE
OTA update server is down

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#7608]
ota.koreader.rocks is down

**Comment by Frenzie** [comment]
Strange, As a heads up, i can't look at it right now, probably don't want to tonight, and I definitely won't have time tomorrow or the day after tomorrow. It looks like no builds [were triggered](https://gitlab.com/koreader/nightly-builds/-/jobs) either, so my guess would be it has something to do with Azure.

Perhaps a good excuse to play around with Supervisor a bit or some such.

**Comment by NiLuJe** [comment]
Can't SSH in either, FWIW.

**Comment by NiLuJe** [comment]
The VM is accessible at least, but I don't do Docker, so I wouldn't know what to do to fix it ;).

**Comment by Frenzie** [comment]
> The VM is accessible at least, but I don't do Docker, so I wouldn't know what to do to fix it ;).

There are a few management helper scripts you know where. Basically use `docker ps` to ascertain what's running, and `docker logs [container]` to see what's going wrong in case they are actually running. I think we've got three of 'em active normally: the OTA nightswatcher triggering/downloading Python script, the nginx fileserver, and the sync thingy.

**Comment by NiLuJe** [comment]
Not quite sure what might have blown up, as I can't find the nightswatcher logs (if any?).

KOSync/Redis might have run into storage space issues a few days ago, but that's the only weird thing I can see.

Anyway, fixed an nginx config warning, restarted all three of 'em, so far, so good.

**Comment by ilyats** [comment]
It is up now

**Comment by Frenzie** [comment]
> Not quite sure what might have blown up, as I can't find the nightswatcher logs (if any?).

The logs are ephemeral or worse. (The logs are in JSON or something but log rotating cleverly makes it unparseable after a few weeks.) But anyway, they're all three pretty much completely independent really.

But anyway, it is as I suspected:
```
$ uptime
 18:24:28 up 11:41,  1 user,  load average: 0.07, 0.02, 0.00
```

**Comment by NiLuJe** [comment]
Oh, :facepalm: :D.
