### ISSUE TITLE
FR: [Scroll to next panel vertically on comics]

### ISSUE THREAD

**Issue by Nathoufresh** [koreader/koreader#7615]
**Does your feature request involve difficulty completing a task? Please describe.**
When reading comics, next and previous buttons currently do not care about where a panel start or end vertically.
![IMG_20210428_161954](https://user-images.githubusercontent.com/39437515/116419750-a6cf3180-a83d-11eb-8703-e8e7615cda72.jpg)

**Describe the solution you'd like**
After some time I've realized I could zoom on each panel (supposedly brought by [this pull request](https://github.com/koreader/koreader/pull/6511) which means it can detect panels. So the next button could scroll to the beginning of the next panel vertically. If two or more panels are completely shown (see the picture), skip them on next scroll.
![IMG_20210428_163352](https://user-images.githubusercontent.com/39437515/116422171-c23b3c00-a83f-11eb-80c7-ebce9b8680a7.jpg)

**Comment by Frenzie** [comment]
I've thought about asking @Galunid about looking into that, but I just can't see it working reliably. Or more to the point, comics aren't quite that boring and predictable with their layouts.

**Comment by Galunid** [comment]
I was thinking about this, when first implementing #6511, but it just is unreliable as @Frenzie said. Different comics/mangas have different layouts, sometimes with overlapping panels. #6511 works great, with well defined panels, but you rarely find comics like that. You may be interested in trying different zoom modes though (bottom menu). While not exactly what you want it's pretty close.

**Comment by Nathoufresh** [comment]
I see, thank you guys for your input.
