### ISSUE TITLE
Status bar: manage items

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7638]
Is it worth to think about implementation of the combined status bar items management?
Now they are enabled/disabled in the menu and sorted in the SortWidget.
The SortWidget allows enabling as well.

![1](https://user-images.githubusercontent.com/62179190/117339307-44fb7100-aea8-11eb-85ef-35b2769d4d75.png)
--
Pros: unified management.
Cons: we do not see the footer while enabling/disabling indicators.

**Comment by hius07** [comment]
> Could be solved by not having this panel full-screen,

Yeah, good idea!

![2](https://user-images.githubusercontent.com/62179190/117345854-b4c12a00-aeaf-11eb-8caf-c9ea11fbf0b5.png)

**Comment by mergen3107** [comment]
Sorry guys, a quick side question: why am I not able to find "Wi-Fi status" item among the footer items? I have everything except for this one (KPW3 5.9.7, KOReader 2021.04)

**Comment by NiLuJe** [comment]
It's not available on Kindle, because we're unsure of the latency impact of the query.

**Comment by mergen3107** [comment]
@NiLuJe 
Ah, OK! Thanks!

**Comment by hius07** [comment]
Nevertheless, I've added `hasFastWifiStatusQueryry = yes` to my devce section in koreader/frontend/device/kindle/device.lua and it works fine on PW2.

**Comment by mergen3107** [comment]
@hius07 Thank you!

**Comment by NiLuJe** [comment]
It's likely not as bad on FW 5.x

**Comment by mergen3107** [comment]
@NiLuJe 
How would I check if the latency goes bad?

**Comment by mergen3107** [comment]
Yes, it works for PW3 too!
I added `hasFastWifiStatusQuery = yes' to local PW3 section in device.lua (after ca. line 379) and restarted. It is quite responsive too, I have Wi-Fi toggle bind to a gesture and the icon changes accordingly

**Comment by Frenzie** [comment]
Quite responsive is nowhere close to good enough. It needs to be instantaneous or it's a hard block.

**Comment by Frenzie** [comment]
Cf. https://github.com/koreader/koreader/pull/5511

**Comment by mergen3107** [comment]
@Frenzie 
At least, it takes about the same time to switch between the icons as if when I manually hit “Network” toggle in the menu. If I understand it correctly, the icon should change to “positive Wi-F” only if there is a successful connection, right?

**Comment by NiLuJe** [comment]
Wi-Fi is asynchronous on Kindle, so, checking if stuff happens on the UI is the absolute wrong way to check this ;).

If this is enable,d this should be limited to devices with a working lua binding & connection.

Someone just needs to bench that call compared to the sysfs check we do on other platforms.

**Comment by Frenzie** [comment]
It's fine if the accuracy of the icon lags. What can't lag is page turning.
