### ISSUE TITLE
Light goes out,

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#7639]
* KOReader version: 2021-04.44
* Device: Kobo Aura One

#### Issue
Suddenly the light goes off a few seconds after I switch it on. It doesn't know it - toggling again says "Light off", and the light indicator also shows it is on - but it isn't.
This is consistently repeatable (for me, swiping down at the left of the screen toggles the light.)

#### Steps to reproduce
Toggle light, wait a few seconds.

**Comment by NiLuJe** [comment]
You should know the drill by now: verbose crash logs or it didn't happen ;).

**Comment by NiLuJe** [comment]
Err, just in case, because that wasn't terribly clear: you do know that a vertical swipe on the left on the left side of the screen is bound to the light intensity control, right?

**Comment by Biep** [comment]
I changed that to toggle.  I never use other than 1%, and would use less if I could.  Inadvertently changing the brightness is way more of a hassle to correct than inadvertently toggling.
But today I can no longer reproduce it - it happened in the context of trying to reproduce the sleep issue, so it may be a partial going to sleep thing; otherwise it stays awake.
