### ISSUE TITLE
FR: footer (bottom one): add Author as an item

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7642]
**Does your feature request involve difficulty completing a task? Please describe.**
"Author" item is not currently offered to show in footer (bottom one). However, it is available in Alt status (top one).

**Describe the solution you'd like**
Adding the "Author" item among other items for footer

**Describe alternatives you've considered**
Alt status bar is a good option for me as it has everything that I actually need (current/total page numbers, battery, time, book name). However, it is only available for CRengine files, and not for PDF, where I need to use the footer instead.

**Comment by hius07** [comment]
How should it deal with long strings?
Alt status bar alternates long author/title on the odd/even pages.

There is a `Maximum width of items` option which should be applicable for author as well.

BTW, max_width affects alone indicators (when not `Show all at once`), that is not needed imho.

**Comment by mergen3107** [comment]
Now that I have Kindle Scribe, I have more space for progress bar single-line info, especially in landscape. I'll try to see what I can do :D
