### ISSUE TITLE
Special pdf files  display Chinese characters with problem

### ISSUE THREAD

**Issue by whmzsu** [koreader/koreader#7647]
* KOReader version: 2021.04
* Device: sony dpt rp1 

#### Issue
Special pdf files  display Chinese characters with problem, all Chinese characters show very odd symbols.
#### Steps to reproduce
special pdf files always reproduce the same result on sony dpt rp1. 
But the file display OK  on my android phone with the same koreader version without any font customzation.
#############
I think it may be relation to the Chinese font ttf or ttc files lack on the sony dpt rp1  system .
So should I add fonts to the hacked dpt rp1 system(in fact customized android 4.0)  or add fonts to koreader ???

**Comment by Frenzie** [comment]
What do you mean by special? Could you share these files or a sample page or two?

**Comment by whmzsu** [comment]
https://www.dlnu.edu.cn/szb/docs/2012-11/20121108152902434889.pdf
file url   , can you download this ???
This file shows OK with pc  with chrome of MS new edge  browser.
But not OK with pdf xchange viewer , as koreader on  sony  DPT rp1.

**Comment by Frenzie** [comment]
As far as I can tell the document renders correctly. This screenshot is from my desktop, but it also renders fine on my H2O.

![Screenshot_2021-05-08_10-31-06](https://user-images.githubusercontent.com/202757/117532603-a3c80400-afe8-11eb-86d9-bd454b784d22.png)

> I think it may be relation to the Chinese font ttf or ttc files lack on the sony dpt rp1 system .

There are plenty of embedded fonts in the PDF file, and additionally we ship some fallback fonts and don't depend on the system for that. That should not make a difference.

**Comment by whmzsu** [comment]
![2021-05-08 17 30 34](https://user-images.githubusercontent.com/4927222/117534336-86fcf200-b023-11eb-8055-a6dfe047f7fd.jpg)

This is my view of the pdf file  open with pdf xchange viewer , same  as this on  koreader on sony DPT RP1.
The file renders correctly on both my android phones with same koreader version as DPT RP1.

**Comment by Frenzie** [comment]
Does this file work for you? There really shouldn't be anything different about the Sony device though, with regard to how MuPDF works. :-/

[example_038.pdf](https://github.com/koreader/koreader/files/6445627/example_038.pdf)

(From https://tcpdf.org/examples/example_038/)

**Comment by whmzsu** [comment]
I will check it  3-4 hours later  as the device not in hand now.

**Comment by whmzsu** [comment]
[1.pdf](https://github.com/koreader/koreader/files/6445773/1.pdf)

Sorry , my mistake,  the  file attached previously works OK on my Sony device .  And the problem version file attached just now above. 
And by the way  the  example_038.pdf  renders  OK. 
As I had found the worked version pdf files , I think we can close this issue.

**Comment by poire-z** [comment]
> Device: sony dpt rp1

Just curious: which build of KOReader runs on this Sony device?
http://build.koreader.rocks/download/stable/v2021.04/
The Android one ? (Wikipedia does not mention this device's OS is Android :/)
Or the "sony-prstux" one ? Is there some people actually really running this one?

**Comment by Frenzie** [comment]
I can confirm that the attached file is broken in both the latest MuPDF as well as KOReader's slightly older MuPDF. It seems to be working with the Adobe library. That likely means it's a known issue but I'm not on my PC right now.

**Comment by Frenzie** [comment]
@poire-z I believe that's an Android with some custom screen refresh support in luajit-launcher

**Comment by whmzsu** [comment]
> > Device: sony dpt rp1
> 
> Just curious: which build of KOReader runs on this Sony device?
> http://build.koreader.rocks/download/stable/v2021.04/
> The Android one ? (Wikipedia does not mention this device's OS is Android :/)
**Yes , the Android one arm apk file .**
> Or the "sony-prstux" one ? Is there some people actually really running this one?
**No, the DPT RP1 run customized android system. After hacked ,  it can install arm apk  file . 
And Koreader is very suitable on this device for reading, thanks for all you guys  great work !**
