### ISSUE TITLE
Wallabag plugin fails to retrieve some entries

### ISSUE THREAD

**Issue by fradav** [koreader/koreader#7659]
* KOReader version:
* Device: kobo aura h2o (first edition) and koreader android (three devices)

#### Issue
when retrieving some wallabag links as epub with the wallabag plugin, the plugin consistently fails to download the same entries across three devices (kobo aura h2o, onyx note boox air, xiaomi mi 9t)
The epub can be perfectly downloaded by the regular means, like the export function on the wallabag server, or the wallabag android client app.

#### Steps to reproduce

- Add https://pawestadnicki.medium.com/master-net-interactive-with-f-7553adf61350 to your wallabag entries
- Try to get the latest wallabag entries with kobo's wallabag plugin.

##### `crash.log` (if applicable)

kobo aura h2o's relevant part in crash.log with developer's log option ON.

<details>
  <summary>crash.log</summary>
  
```
05/10/21-09:07:44 DEBUG Wallabag: DOWNLOAD: title:  Master .NET Interactive with F#
05/10/21-09:07:44 DEBUG Wallabag: DOWNLOAD: filename:  /mnt/onboard/wallabag/[w-id_321] Master .NET Interactive with F#.epub
05/10/21-09:07:44 DEBUG Wallabag: URL      https://laab.freeboxos.fr:48083/api/entries/321/export.epub
05/10/21-09:07:44 DEBUG Wallabag: method   GET
05/10/21-09:07:54 DEBUG Wallabag: Server error:  wantread
```
</details>

**Comment by Frenzie** [comment]
I can't confirm that on my H2O v1 (nor any other device).

![FileManager_2021-05-10_093158](https://user-images.githubusercontent.com/202757/117622603-1533be00-b173-11eb-8258-af6f3b1fd93d.png)

**Comment by fradav** [comment]
10.8 Kb ? You sure you have an up to date wallabag server ? (I use latest 2.4.2 docker image) How it is rendered ? 
My epub for this is 1.5M large! (it's renrered very nicely with all images with calibre epub reader for example).

**Comment by Frenzie** [comment]
It includes no images, no. But with images it'd clearly be a duplicate of #7650, wouldn't it?

**Comment by Frenzie** [comment]
In any case, your error sounds like an OpenSSL error *from your server*.

**Comment by Frenzie** [comment]
Wallabag is irrelevant to that.

**Comment by fradav** [comment]
You're partly right: I read the wallabag issue https://github.com/wallabag/wallabag/issues/4043 and realized I forgot to activate the local images download for my server... and now it works. I don't know if it simply alleviate the "timeout" problem by just having all images locally. 
Problem solved, at least now. ;-)

**Comment by Frenzie** [comment]
In that case it's probably that the SSL/TLS/whatever handshake times out because of the image download thing rather than a server misconfiguration. So then it's an actual duplicate. ^_^

**Comment by Frenzie** [comment]
PS For future reference, if it were a server misconfiguration you could pass along some options like these (not sure otoh if I got the syntax etc. quite right but just to give an idea):

```
diff --git a/plugins/wallabag.koplugin/main.lua b/plugins/wallabag.koplugin/main.lua
index bde13713..ff7482ac 100644
--- a/plugins/wallabag.koplugin/main.lua
+++ b/plugins/wallabag.koplugin/main.lua
@@ -569,6 +569,7 @@ function Wallabag:callAPI(method, apiurl, headers, body, filepath, quiet)
         request.sink = ltn12.sink.table(sink)
     end
     request.headers = headers
+    request.options = {"no_sslv2", "no_sslv3", "no_tlsv1"}
     if body ~= "" then
         request.source = ltn12.source.string(body)
     end
```

**Comment by matejdro** [comment]
Can you link to the ticket that this is the duplicate of?

I don't think this is really a server side issue. Downloading epub via browser works just fine, but it takes a while of course. Maybe koreader downloading timeout should be increased?

**Comment by Frenzie** [comment]
That's https://github.com/koreader/koreader/issues/7650. Please direct comments related to timeouts there.

> I don't think this is really a server side issue.

NB I didn't say a timeout is a server side issue (although in a different sense it is). I said something like a failed handshake as in the error log in the OP is most likely a server side configuration issue, a typical cause being something like trying to use an obsolete TLS v1.0.
