### ISSUE TITLE
ebook only showing cover page in KOReader

### ISSUE THREAD

**Issue by tjaderxyz** [koreader/koreader#7661]
* KOReader version: 2021.04
* Device: any

#### Issue

I have an epub that works fine in calibre's reader and in SumatraPDF, but when opened in KOReader only the cover page appears. I have attached a scrambled version of the epub which still has the problem.

#### Steps to reproduce
1. download [scrambled.zip](https://github.com/koreader/koreader/files/6453502/scrambled.zip)
2. open in KOReader
3. open in other epub reader

**Comment by poire-z** [comment]
In the opf:
```
    <item href="John Maddox Roberts - [SPQR Roman Mysteries 02] -  The Catiline Conspiracy (v1.0)_split_000.html" id="html2" media-type="application/xhtml+xml"/>
    <item href="John Maddox Roberts - [SPQR Roman Mysteries 02] -  The Catiline Conspiracy (v1.0)_split_001.html" id="html1" media-type="application/xhtml+xml"/>
```
There are 2 spaces before `The Catiline` and the code ends up trying to open:
```
John Maddox Roberts - [SPQR Roman Mysteries 02] - The Catiline Conspiracy (v1.0)_split_000.html
John Maddox Roberts - [SPQR Roman Mysteries 02] - The Catiline Conspiracy (v1.0)_split_001.html
cover.jpeg
cs.js
```
so, with only one space.
Not sure if spaces should collapse in XML attributes or not, but looks like the code does makes these 2 space a single one.

http://validator.idpf.org/ epubcheck complains about these 2 lines (with a bit unclear message):
`Error while parsing file: value of attribute "href" is invalid; must be a URI`

(Previous issues related to the XML parsing of OPFs: #5296 and #7219.)

**Comment by poire-z** [comment]
Well, looks like we took care of keeping consecutive spaces at one point, but just after, we do trimDoubleSpaces() :)
Can you check how calibre and sumatra PDF do if there is a leading or a trailing space in the attribute:
`    <item href=" John Maddox...`
I guess these leading/trailing spaces should still be stripped.

**Comment by poire-z** [comment]
Guess this should solve it:
```diff
--- a/crengine/src/lvxml.cpp
+++ b/crengine/src/lvxml.cpp
@@ -3143,7 +3143,7 @@ bool LVXMLParser::Parse()
                     // Process &#124; and HTML entities, but don't touch space
                     PreProcessXmlString( attrvalue, TXTFLG_PROCESS_ATTRIBUTE );
                 }
-                attrvalue.trimDoubleSpaces(false,false,false);
+                attrvalue.trim();
                 m_callback->OnAttribute(attrns.c_str(), attrname.c_str(), attrvalue.c_str());

                 if (inXmlTag && attrname == "encoding")
```

**Comment by Frenzie** [comment]
> http://validator.idpf.org/ epubcheck complains about these 2 lines (with a bit unclear message):
Error while parsing file: value of attribute "href" is invalid; must be a URI

The error message in all likelihood means it should strictly speaking be encoded as %20 in a context like this.

**Comment by Frenzie** [comment]
Confirmed, if you properly encode the spaces as `%20` it works as intended. However, that doesn't mean we shouldn't deal with this in a more expected manner. ;-)

**Comment by poire-z** [comment]
`DecodeHTMLUrlString()` does convert %20 and co, and is used for href/img src.

https://www.w3.org/TR/xml11/#AVNormalize
For XML attributes, it looks like all spaces should be preserved, so leading and trailing too...
Feels a bit risky to be that strict.
Feels safer to be on the loose side and to trim() spaces at start/end, for attributes likes `valign=" top"`.
I think there's more chances we meet typos like that (that I guess browsers would handle correctly) to happen, that for leading or trailing spaces to have some meaning (and filenames with that must be rare).
Otherwise, there may be a lot of bit of code dealing with attributes that may need to be fixed to do some trimming before doing some comparisons...

**Comment by Frenzie** [comment]
> Feels safer to be on the loose side and to trim() spaces at start/end, for attributes likes valign=" top".

NB Sometimes a single space or two spaces *is* the intended value.
