### ISSUE TITLE
Refresh issue with new Pocketbook Firmware 6.3

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#7663]
* KOReader version: Latest nightlies (problem known for a few weeks now)
* Device: Pocketbook InkPad X (running FW 6.3.798) and other Pocketbook devices running firmware 6.3

#### Issue
I'm reporting this issue for a tech-savvy user in a German forum.
Here's a video of what sceen refreshes look like in KOReader after an update to Pocketbook firmware 6.3:
[YouTube video](https://www.youtube.com/watch?v=hzed2vW9xn0)

The user assumes that there's a new screen driver built into the new Pocketbook firmware starting with 6.3. Other alternative  software (e.g. Vlasovsoft Coolreader) does not show these flashes and functions flawlessly with FW 6.3.

**Comment by LucyOne** [comment]
On the Touch Lux 5, changing the e-ink setting to Level 3 results in a very slow refresh, but prevents the strong ghosting effect as seen in the video. Levels 0, 1 and 2 result in the refresh issues.

Here's the debug crashlog from the Inkpad X:
[InkPadX_crash.log](https://github.com/koreader/koreader/files/6461359/InkPadX_crash.log)

**Comment by LucyOne** [comment]
Here are a couple more crashlogs.

Pocketbook Color, FW 6.1, no refresh issues
[PB_Color_crash.log](https://github.com/koreader/koreader/files/6464697/PB_Color_crash.log)

Pocketbook Inkpad Color, FW 6.3, refresh issues as in the video
[IP_Color_crash.log](https://github.com/koreader/koreader/files/6464704/IP_Color_crash.log)

Pocketbook Touch Lux 5, FW 6.3, see description in the comment above
[TL5_crash.log](https://github.com/koreader/koreader/files/6464720/TL5_crash.log)

**Comment by NiLuJe** [comment]
All of them appear to be using the same crappy SoC, so, at least the weirdness isn't entirely unexpected.

This will *definitely* require someone with an affected device comparing strace outputs; and/or someone complaining loudly enough for PB to put out updated kernel sources & SDKs.

**Comment by LucyOne** [comment]
I'm translating the comments from the German forum, so I hope I get all the technical details right.

Would it be possible to change KOReader so it uses the device's screen driver for a refresh instead of its own engine? This might already be the case for the Touch Lux 5 with a level-3 e-ink setting, using some kind of fallback function which then uses the device's refresh function.

The Vlasovsoft-CoolReader and the blchinezu-CoolReader seem to work this way too, as they show no refresh issues with the current firmware and they are not being developed anymore. The Vlasovsoft-CoolReader even displays color images on the Pocketbook Color readers. Coolreader uses libinkview which KOReader does not.

**Comment by NiLuJe** [comment]
No, we're not an InkView app. In fact, if we could actually get rid of InkView entirely, it'd fix a number of weird shitty PB quirks.

What we *can* do is mimic whatever InkView does, hence the strace log request above ;).

**Comment by LucyOne** [comment]
Could you explain step by step how to do this, so I can translate it?

**Comment by NiLuJe** [comment]
That's basically https://github.com/koreader/koreader/issues/7663#issuecomment-839000541 (and/or any previous issues where I've requested a strace ^^).

**Comment by LucyOne** [comment]
The user has installed koreader-pocketbook-v2020.09 (stable) on his Inkpad 3 Pro and Touch Lux 5 which seems to be one of the last versions with refresh working correctly, without any extra flashes or ghosting. He's trying to find the exact last version for that. He assumes it must be one before the waveform level settings were built-in.

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/compare/v2020.09...v2020.10

I'm guessing it might be the September 20 nightly?
https://github.com/koreader/koreader/pull/6669

A slightly larger archive of older versions than we keep on koreader.rocks can be found at https://gitlab.com/koreader/nightly-builds/-/jobs

**Comment by NiLuJe** [comment]
That one would probably have *introduced* the issues, before the level thingy allowed to "fix" it by enforcing GC16 everywhere at L3.

**Comment by LucyOne** [comment]
The user reports that in v2020.10.1 (stable) refresh is still working correctly. Not anymore in v2020.11 (stable), which causes the following behaviour on the Inkpad 3 Pro: Only in level 3 the refresh is done correctly. On levels 0-2 refresh shows the ghosting and flashes.

Would it be possible to have some kind of "bypass" built in that deactivates the e-ink waveform settings for certain devices?

**Comment by NiLuJe** [comment]
The safe bet would be anything with a B288, probably. There's already such a mechanism in place for hw rota (and I think the fastest wf level, possibly?).

**Comment by NiLuJe** [comment]
Hmm. Actually, the sole culprit *might* be hw rota: it's disabled on B288 *only* @ level 3...

**Comment by NiLuJe** [comment]
i.e., does this patch fix it for *all* wf levels?

```diff
diff --git a/frontend/device/pocketbook/device.lua b/frontend/device/pocketbook/device.lua
index ee12b1222..3c64d586e 100644
--- a/frontend/device/pocketbook/device.lua
+++ b/frontend/device/pocketbook/device.lua
@@ -110,11 +110,9 @@ function PocketBook:init()
             if fb:isB288() then
                 logger.dbg("mxcfb: Disabling hwinvert on B288 chipset")
                 self.canHWInvert = no
-                -- GL16 glitches with hwrot
-                if fb.wf_level == 3 then
-                    logger.dbg("mxcfb: Disabling hwrot on fast waveforms (B288 glitch)")
-                    fb.forced_rotation = nil
-                end
+                -- GL16 glitches with hwrot. And apparently with more stuff on newer FW (#7663)
+                logger.dbg("mxcfb: Disabling hwrot on B288 chipset")
+                fb.forced_rotation = nil
             end
             -- If hwrot is still on, nuke swrot
             if fb.forced_rotation then
```

**Comment by LucyOne** [comment]
First success reported on Inkpad 3 Pro and current nughtly 2021-4.69.

**Comment by LucyOne** [comment]
Here's a list of devices with the patch applied:
IP 3 -- FW.6.1 -- ok
IP 3 Pro -- FW.6.3 -- ok
IP Color -- FW.6.3 -- ok
PB Color -- FW.6.1 -- black flashes on level 3 - rest ok
THD 3 -- FW.6.1 -- ok
TL 5 -- FW.6.3 -- ok
TL 4 -- FW.6.3 -- screen freezes on level 2, which has happened since FW.6.x came out - rest ok
IP X -- FW.6.3 -- ok

A big thank you to the developers!
