### ISSUE TITLE
KO3: Touch screen is reversed

### ISSUE THREAD

**Issue by donamvn** [koreader/koreader#7670]
* KOReader version: KOReader 2021.04 "Gouty Gauss"
* Device:  KO3

#### Issue
See the link:  **https://youtu.be/xSSWLQ3_dHw**

I have been waiting a long time to fix this error since version .01 at hour 0.4 has not been fixed yet. 
Please check, thanks you..

**Comment by NiLuJe** [comment]
Don't start KOReader with the device upside down.

https://github.com/koreader/koreader/blob/f0ecbeb1d5a9a3db4b09acbb5f271e83eb1e433c/frontend/device/kindle/device.lua#L743-L749
