### ISSUE TITLE
kpw2:KoReader UI rotated by 90' left, but touchpad responds as it was not rotated 

### ISSUE THREAD

**Issue by l126t** [koreader/koreader#7672]
* KOReader version:2021.04
* Device:kpw2

#### Issue
UI is rotated by 90' left, but touchscreen responds as it should (i.e. if UI wouldnt be rotated).
Before upgrading(2019.08),no problem. After upgrading to 2021.04, it happens .
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>
  
```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
Don't start KOReader with the device in a non-standard orientation.

**Comment by l126t** [comment]
When I downgrade koreader,this issue vanish completely.When I upgrade KR,it happens again.

**Comment by NiLuJe** [comment]
Let me guess: you're using KPV.

**Comment by l126t** [comment]
I use KUAL

**Comment by NiLuJe** [comment]
Can't reproduce on FW 5.9.7, FWIW.

**Comment by l126t** [comment]
my fw 5.8.9

**Comment by hius07** [comment]
> open a pdf file, rotate it by 90' ,close it then reopen.

Cannot reproduce as well, PW2 5.8.7, starting with KUAL or with KOL.

**Comment by NiLuJe** [comment]
Ditto, even with a full exit and a start_with set to last_file (not that it should make any difference).

Again, not that it should make any difference, but I'd try a clean install after having tucked away your current settings somewhere.

**Comment by l126t** [comment]
When starting with KUAL, it's miraculously healed of "facial paralysis".Originally,I only open file in kindle builtin file manager directly.Now,everything goes right,even if opening file using builtin file manager.thx

**Comment by NiLuJe** [comment]
> Let me guess: you're using KPV.

It's not like I didn't ask you that point-blank...
