### ISSUE TITLE
FR: Render Markdown as HTML

### ISSUE THREAD

**Issue by Laurent-Ca** [koreader/koreader#7680]
**Does your feature request involve difficulty completing a task? Please describe.**
Markdown (MD) files are displayed as ugly TXT

**Describe the solution you'd like**
It would be awesome if we could have markdown files display as HTML

**Describe alternatives you've considered**
The only alternative is to convert the files and then transfer them :(

**Additional context**
HTML support is already so great (thank you KOREADER devs!), I hope this is not too hard to add

**Comment by poire-z** [comment]
> The only alternative is to convert the files and then transfer them :(

You can have them converted to HTML directly by KOReader. Long-press on it in FileBrowser:
<kbd>![image](https://user-images.githubusercontent.com/24273478/118159592-7bdc0480-b41d-11eb-9373-0162e23b0182.png)</kbd>
This creates a new file named `test-README1.md.html`.

**Comment by Laurent-Ca** [comment]
@poire-z oh that's pretty awesome! Tested it with a few files and conversion seems pretty fast. Any chance we can do the conversion in the background and just render MD files as HTML? Was that ever considered and devs decided against it? (also, what other conversions is koreader capable of?)

**Comment by Frenzie** [comment]
> (also, what other conversions is koreader capable of?)

None, unless you count something like page to PNG.

**Comment by Laurent-Ca** [comment]
where is this page to png option?

**Comment by Frenzie** [comment]
Only in the code, but a screenshot (long diagonal swipe) is probably more or less the same thing for most intents and purposes.

**Comment by Laurent-Ca** [comment]
I see, I did find your comment from a few years back https://github.com/koreader/koreader/issues/2632#issuecomment-290985621 but I don't know if it was ever considered

**Comment by Frenzie** [comment]
But… you just used it? ;-)

**Comment by Laurent-Ca** [comment]
oh of course lol I just thought you had suggested the implementation of just supporting markdown natively without conversions involved. Like koreader already does with epubs, htmls, pdfs, etc

**Comment by Laurent-Ca** [comment]
could you please extend the conversion feature to txt files too? TXT > HTML? Right now I find myself changing the extension to MD just to have the 'convert' option available.

**Comment by Frenzie** [comment]
You have a lot of Markdown files with the .txt extension instead of .md?

**Comment by Laurent-Ca** [comment]
not particularly, but I do send quick notes to my ereader often. And the easiest way is as a txt. I suppose I could just start saving them as md instead.
