### ISSUE TITLE
Koreader crashes when opening menu

### ISSUE THREAD

**Issue by enigmasc** [koreader/koreader#7681]
* KOReader version: v2021.04-69-gfeec47d_2021-05-13
* Device: Kobo Touch (N905c) and Kobo Glo HD

#### Issue

Koreader crashes after opening the menu.  It happens to my 2 Kobo e-Readers.

<details>
  <summary>crash.log</summary>
  
```
              launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/14/21-15:23:05
 [*] Version: v2021.04-69-gfeec47d_2021-05-13

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
05/14/21-15:23:05 INFO  initializing for device Kobo_trilogy
05/14/21-15:23:05 INFO  framebuffer resolution: {
    ["w"] = 600,
    ["h"] = 800,
}
[ko-input] Forked off fake event generator (pid: 1127)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
05/14/21-15:23:05 INFO  Performing one-time migration for 20210503 & 20210508
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=1.992 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.992/1.992/1.992 ms
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=2.442 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 2.442/2.442/2.442 ms
05/14/21-15:23:06 INFO  opening file /mnt/onboard/Literature/Fiction/Carroll_ Lewis - Alice's Adventures in Wonderland.epub
05/14/21-15:23:06 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSansCJKsc-Regular.otf>
05/14/21-15:23:06 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/Gentium_Book_Basic_Regular.ttf>
05/14/21-15:23:07 INFO  Loading plugins from directory: plugins
05/14/21-15:23:07 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
05/14/21-15:23:07 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
05/14/21-15:23:07 WARN  Error when loading plugins/kobolight.koplugin/_meta.lua cannot open plugins/kobolight.koplugin/_meta.lua: No such file or directory
05/14/21-15:23:07 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
05/14/21-15:23:07 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
05/14/21-15:23:07 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin calibre at plugins/calibre.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin gestures at plugins/gestures.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin opds at plugins/opds.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin profiles at plugins/profiles.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
05/14/21-15:23:07 INFO  RD loaded plugin zsync at plugins/zsync.koplugin

```
</details>

**Comment by NiLuJe** [comment]
There's no crash in your log excerpt :?

**Comment by NiLuJe** [comment]
And I also can't reproduce it, so you'll have to give us more details: *which* menu, *where*, and *how* you're attempting to trigger it (tap/swipe)?

**Comment by NiLuJe** [comment]
Okay, repro'd with default settings (i.e., show all the things).

**Comment by enigmasc** [comment]
I made a video of this.  https://www.youtube.com/watch?v=b7Gs199V_vc

**Comment by enigmasc** [comment]
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/15/21-12:46:07
 [*] Version: v2021.04-69-gfeec47d_2021-05-13

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
05/15/21-12:46:07 INFO  initializing for device Kobo_trilogy
05/15/21-12:46:07 INFO  framebuffer resolution: {
    ["w"] = 600,
    ["h"] = 800,
}
[ko-input] Forked off fake event generator (pid: 1305)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
05/15/21-12:46:08 INFO  opening file /mnt/onboard/Literature/Fiction/The Sympathizer - Viet Thanh Nguyen.epub
05/15/21-12:46:08 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSansCJKsc-Regular.otf>
05/15/21-12:46:09 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/Gentium_Book_Basic_Regular.ttf>
05/15/21-12:46:09 INFO  Loading plugins from directory: plugins
05/15/21-12:46:09 INFO  Plugin  plugins/autofrontlight.koplugin/main.lua  has been disabled.
ffi.load: sqlite3
05/15/21-12:46:09 INFO  Plugin  plugins/hello.koplugin/main.lua  has been disabled.
05/15/21-12:46:09 WARN  Error when loading plugins/kobolight.koplugin/_meta.lua cannot open plugins/kobolight.koplugin/_meta.lua: No such file or directory
05/15/21-12:46:09 INFO  Plugin  plugins/autostandby.koplugin/main.lua  has been disabled.
05/15/21-12:46:09 INFO  Plugin  plugins/coverimage.koplugin/main.lua  has been disabled.
05/15/21-12:46:09 INFO  RD loaded plugin SSH at plugins/SSH.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin autosuspend at plugins/autosuspend.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin autoturn at plugins/autoturn.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin batterystat at plugins/batterystat.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin calibre at plugins/calibre.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin coverbrowser at plugins/coverbrowser.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin docsettingtweak at plugins/docsettingtweak.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin evernote at plugins/evernote.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin gestures at plugins/gestures.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin goodreads at plugins/goodreads.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin keepalive at plugins/keepalive.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin kosync at plugins/kosync.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin movetoarchive at plugins/movetoarchive.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin newsdownloader at plugins/newsdownloader.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin opds at plugins/opds.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin perceptionexpander at plugins/perceptionexpander.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin profiles at plugins/profiles.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin qrclipboard at plugins/qrclipboard.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin readtimer at plugins/readtimer.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin send2ebook at plugins/send2ebook.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin statistics at plugins/statistics.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin systemstat at plugins/systemstat.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin terminal at plugins/terminal.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin texteditor at plugins/texteditor.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin timesync at plugins/timesync.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin wallabag at plugins/wallabag.koplugin
05/15/21-12:46:09 INFO  RD loaded plugin zsync at plugins/zsync.koplugin
05/15/21-12:46:19 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
./luajit: frontend/ui/geometry.lua:204: attempt to call method 'area' (a nil value)
stack traceback:
	frontend/ui/geometry.lua:204: in function 'notIntersectWith'
	frontend/ui/geometry.lua:221: in function 'intersectWith'
	frontend/ui/widget/configdialog.lua:1455: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
	frontend/ui/uimanager.lua:1110: in function 'sendEvent'
	frontend/ui/uimanager.lua:222: in function '__default__'
	frontend/ui/uimanager.lua:1568: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1648: in function 'handleInput'
	frontend/ui/uimanager.lua:1695: in function 'run'
	./reader.lua:290: in main chunk
	[C]: at 0x00014161
!!!!
Uh oh, something went awry... (Crash n°1: 05/15/21 @ 12:46:35)
Running FW 3.19.5761 on Linux 2.6.35.3-850-gbc67621+ (#617 PREEMPT Mon Apr 22 11:07:47 CST 2013)
Attempting to restart KOReader . . .
!!!!

**Comment by Frenzie** [comment]
Today's nightly should work. ;-)
