### ISSUE TITLE
Crash if there is no lastdocument, but a gesture does "open previous document"

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#7690]
* KOReader version: 2021-04-73
* Device: Emulator

#### Issue
crash

#### Steps to reproduce
Add a gesture to "Open previus document". Then delete `settings.reader.lua*` (or alternatively delete the lastfile entries).
Open KOReader and do the gesture for "Open previous document`. -> crash

If you open the menu one time before applying the gesture, then there is no crash.

It seems that dispatcher uses some events from readermenu, but readermenu is not initialized before the menu is opened one time?

##### A quick and dirty fix could be
Change https://github.com/koreader/koreader/blob/e6027313e97138c21f014f708b6201bc4a64c350/frontend/apps/reader/modules/readermenu.lua#L81 to
```
function ReaderMenu:getPreviousFile()
    if not self.ui.document then
        return require("readhistory"):getPreviousFile(self.ui.document.file)
    else
        return false
    end
end
```

##### `crash.log` (if applicable)
05/15/21-16:54:00 DEBUG ImageWidget: initial offsets 0 0
05/15/21-16:54:00 DEBUG show widget: table: 0x7f38ec7b0dd8
05/15/21-16:54:00 DEBUG setDirty nil from widget table: 0x7f38ec7b0dd8 w/ NO region 
05/15/21-16:54:00 DEBUG setDirty via a func from widget table: 0x7f38ec7b0dd8
05/15/21-16:54:00 DEBUG painting widget: table: 0x7f38edbb7cd0
05/15/21-16:54:00 DEBUG blitFrom 67 341 0 0 36 36
05/15/21-16:54:00 DEBUG _refresh: Enqueued ui update for region 60 309 419 101 
05/15/21-16:54:00 DEBUG refresh on physical rectangle 60 309 419 101
05/15/21-16:54:00 DEBUG show widget: table: 0x7f38ec80e320
05/15/21-16:54:00 DEBUG setDirty nil from widget table: 0x7f38ec80e320 w/ NO region 
05/15/21-16:54:00 DEBUG setDirty via a func from widget table: 0x7f38ec80e320
05/15/21-16:54:00 DEBUG painting widget: table: 0x7f38ee5819e0
05/15/21-16:54:00 DEBUG painting widget: table: 0x7f38edbb7cd0
05/15/21-16:54:00 DEBUG blitFrom 67 341 0 0 36 36
05/15/21-16:54:00 DEBUG _refresh: Enqueued ui update for region 165 5 210 53 
05/15/21-16:54:00 DEBUG refresh on physical rectangle 165 5 210 53
./luajit: frontend/apps/reader/modules/readerfont.lua:214: attempt to index field 'document' (a nil value)
stack traceback:
	frontend/apps/reader/modules/readerfont.lua:214: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/apps/reader/modules/readerfont.lua:205: in function 'onChangeSize'
	frontend/apps/reader/modules/readerfont.lua:358: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/dispatcher.lua:640: in function 'execute'
	plugins/gestures.koplugin/main.lua:1106: in function 'handler'
	frontend/ui/widget/container/inputcontainer.lua:255: in function 'handleEvent'
	frontend/ui/uimanager.lua:1110: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1568: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1648: in function 'handleInput'
	frontend/ui/uimanager.lua:1695: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x55b692c1e7a4
~/work/koreader

**Comment by NiLuJe** [comment]
Possibly just

```lua
function ReaderMenu:getPreviousFile()
    if not self.ui.document then
        return require("readhistory"):getPreviousFile(self.ui.document.file)
    end
end
```

Because apparently code explicitly expect `nil` on failure, not `false` ;).
