### ISSUE TITLE
Greek Polytonic keyboard

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7696]
If possible, please add Greek Polytonic as a language option for keyboard. It means that "Greek Extended" block (U+1F00 to U+1FFF) of Unicode will be added.

Thank you.

**Comment by ichnilatis-gr** [comment]
Is there any hope for that?
Or is there any way I can do it with my limited knowledge?

**Comment by Frenzie** [comment]
Could you perhaps include a few references about what it should look like, for example on Wikipedia? But experimenting a bit with adjusting the Greek layout might be the quickest way to get it.

**Comment by poire-z** [comment]
Your only hope is another Greek user understanding what's needed :)
Or yourself. You could look at and play with:
https://github.com/koreader/koreader/blob/master/frontend/ui/data/keyboardlayouts/el_keyboard.lua
https://github.com/koreader/koreader/blob/master/frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua

If all this is about having more diacritics, you could add them to the popup for each normal key.

For example (on the French or English keyboard), long-press on <kbd>u</kbd> brings this popup with more `u` variations:
<kbd>![image](https://user-images.githubusercontent.com/24273478/118978713-e9d18000-b977-11eb-9929-86e7bc3c1eb7.png)</kbd>

**Comment by ichnilatis-gr** [comment]
> If all this is about having more diacritics, you could add them to the popup for each normal key.

That's exactly what I had in my mind. How could I do this?

**Comment by poire-z** [comment]
Just add some stuff into https://github.com/koreader/koreader/blob/master/frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua
See what a long-press on <kbd>a</kbd> shows - this is:
https://github.com/koreader/koreader/blob/6e1950676a9b30900bece39dd149329b94366820/frontend/ui/data/keyboardlayouts/keypopup/el_popup.lua#L8-L13
Add some `west=` `south=` `southeast=` ... to this section to fill the available directions, and you'll add more options:
https://github.com/koreader/koreader/blob/6e1950676a9b30900bece39dd149329b94366820/frontend/ui/data/keyboardlayouts/keypopup/en_popup.lua#L54-L66

**Comment by ichnilatis-gr** [comment]
Thank you a lot. I think I can do it. I will "play" with it... :wink:

**Comment by ichnilatis-gr** [comment]
I made some additions in el_popup.lua, as below:

return {
    _A_el = {
        "Α",
        northeast = "Ά",
        north = "A",
        northwest = "@",
	east = "Ἀ",
	west = "Ά",
	south = "Ἄ",
	southeast = "Ἁ",
	southwest = "Ἅ",
		
    },
    _a_el = {
        "α",
        northeast = "ά",
        north = "a",
        northwest = "@",
	east = "ἀ",
	west = "ἄ",
	southeast = "ἁ",
	southwest = "ἅ",

and I copy it to my device in order to test it, but KOReader crashes. Should I make any other adjustment?

**Comment by poire-z** [comment]
Not sure what's wrong from what we see (but you just put a extract, may be the problem is after), but look in your crash.log, which should tell you what is wrong at which line number.

**Comment by ichnilatis-gr** [comment]
Finally, after some attempts to use the keyboard, it worked! I had made additions only in these lines, as above.
I just wonder why the popup menu of these two letters (Α,α) doesn't stay stable so as to choose a letter, but it closes immediately (most of the time), unlike the other letters. May be corrected over time... 😄

**Comment by poire-z** [comment]
> I just wonder why the popup menu of these two letters (Α,α) doesn't stay stable so as to choose a letter, but it closes immediately (most of the time), unlike the other letters. 

I can reproduce that.
Somehow, it happens when you long-press and the long-press position is not the on the middle key of the popup. So, for a same key, it might happen or not if you press on its left or right part.
Can be witnessed with the <kbd>L</kbd> of the english QWERTY keyboard (or <kbd>A</kbd> of the french AZERTY keyboard).

**Comment by poire-z** [comment]
^ quite not obvious how to solve this...
https://github.com/koreader/koreader/blob/b938f312a6245f25a2e9713c7da4787603973c43/frontend/ui/widget/virtualkeyboard.lua#L519-L541
might be screwed when we move the panels because the normal popup panel would overflow the screen edges:
https://github.com/koreader/koreader/blob/b938f312a6245f25a2e9713c7da4787603973c43/frontend/ui/widget/virtualkeyboard.lua#L609-L625

@Frenzie : any thought ?

**Comment by Frenzie** [comment]
The most obvious is avoiding west on affected keys.

Btw, are we talking about a *mouse* testing scenario, where hold, release might be more natural or actual on-device where hold, keep holding is much more natural?

**Comment by Frenzie** [comment]
> I long-press and release to see what's available

Yes, that's why I added it that way. :-) But the problem is fairly small provided the popup takes it into consideration.

**Comment by poire-z** [comment]
> the popup takes it into consideration.

You mean making sure we don't add keys on the side near the edges ?
Good luck reducing the amount of popup keys on the <kbd>A</kbd> key on the english QWERTY :)

**Comment by Frenzie** [comment]
The English keyboard takes it into consideration. The A is only a few pixels off but acceptable. Compare it with Q.

**Comment by Frenzie** [comment]
That is, this is a choice I made at the time. ^_^

I note that on my Android phone it's a bit awkward; I didn't quite take that into consideration. But on my H2O and similar devices I think it works out well enough.

**Comment by NiLuJe** [comment]
I've got something that works for the above corner-case (literally ;p) by simply avoiding the initial release event if the popup had to be moved.

Lemme clean that up, because right now it's on top of #7751 ;).

**Comment by NiLuJe** [comment]
```diff
diff --git a/frontend/ui/widget/virtualkeyboard.lua b/frontend/ui/widget/virtualkeyboard.lua
index 5dd2c56db..9bebc7346 100644
--- a/frontend/ui/widget/virtualkeyboard.lua
+++ b/frontend/ui/widget/virtualkeyboard.lua
@@ -520,6 +520,17 @@ function VirtualKeyPopup:init()
                 virtual_key.hold_callback = nil
                 -- close popup on hold release
                 virtual_key.onHoldReleaseKey = function()
+                    -- NOTE: Check our *parent* key!
+                    if parent_key.ignore_key_release then
+                        parent_key.ignore_key_release = nil
+                        return true
+                    end
+                    Device:performHapticFeedback("LONG_PRESS")
+                    if virtual_key.keyboard.ignore_first_hold_release then
+                        virtual_key.keyboard.ignore_first_hold_release = false
+                        return true
+                    end
+
                     virtual_key:onTapSelect(true)
                     UIManager:close(self)
                     return true
@@ -630,13 +641,19 @@ function VirtualKeyPopup:init()
     }
     if position_container.dimen.x < 0 then
         position_container.dimen.x = 0
+        -- We effectively move the popup, which means the key underneath our fnger is no longer parent_key.
+        -- Make sure we won't close the popup right away in order to make thta less confusing.
+        parent_key.ignore_key_release = true
     elseif position_container.dimen.x + keyboard_frame.dimen.w > Screen:getWidth() then
         position_container.dimen.x = Screen:getWidth() - keyboard_frame.dimen.w
+        parent_key.ignore_key_release = true
     end
     if position_container.dimen.y < 0 then
         position_container.dimen.y = 0
+        parent_key.ignore_key_release = true
     elseif position_container.dimen.y + keyboard_frame.dimen.h > Screen:getHeight() then
         position_container.dimen.y = Screen:getHeight() - keyboard_frame.dimen.h
+        parent_key.ignore_key_release = true
     end
 
     self[1] = position_container
```

The double haptic feedback might not be great, I'm not on a platform where I can test this. (It's from the standard onHoldReleaseKey handler).

**Comment by NiLuJe** [comment]
(That doesn't break the fancy quick swipes, provided you know where the key you want will have moved ^^).

**Comment by ichnilatis-gr** [comment]
The popup menu can have only 4 lines maximum, can't it?

**Comment by poire-z** [comment]
Right, you can't get more than this:
![image](https://user-images.githubusercontent.com/24273478/121777010-39c6ef80-cb90-11eb-9da7-3fb09cdc1335.png)

**Comment by ichnilatis-gr** [comment]
So I have to choose the most common combinations of letters and polytonic diacritics. When I have the el_popup.lua file completed with (some) polytonic choices, I will send it to you to check and merge it.

Thanks!

**Comment by poire-z** [comment]
I can't check how they make sense for greek, but as far as Lua, they look fine (except for some TABs that should be converted to spaces, that we can fix later).
For the greek side of checks, pinging @noembryo : does it all make sense to you ? are you fine/agreeing with the additions/changes/positions?

**Comment by noembryo** [comment]
Unfortunately I'm away from my box and the future is uncertain..
I'll check it when I'm back..
