### ISSUE TITLE
PB626: Hold on footer causes dictionary lookup instead showing skim window

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#7697]
* KOReader version: v2021.04-62-gf0ecbeb_2021-05-13
* Device: PocketBook 626 U626.5.20.1157

#### Issue
After hold on footer dictionary lookup is performed instead showing skim window (I have in status bar/settings "tick" on *Hold footer to skim* and in document settings/highlight action "tick" on *Enable on single word selection* and "tick" on *Directory*)

#### Steps to reproduce
1. open PDF file
2. hold finger on footer

-dictionary lookup is performed instead of showing the skim window

##### Crash log
[crash_20210516144242.log](https://github.com/koreader/koreader/files/6489225/crash_20210516144242.log)

**Comment by sonix-github** [comment]
If I disable in document settings highlighting by "unticking" *Allow highlighting* the skim windows is showing again but no dictionary lookup is now possible after holding finger on word :(

**Comment by NiLuJe** [comment]
IIRC, that's a known quirk that only happens in PDF for some weird-ass PDF reason.

Double-check in an ePub, where it *should* behave.

**Comment by sonix-github** [comment]
@NiLuJe 
I have tested it in ePub document and there is everything OK, that means the skim window is shown.

**Comment by NiLuJe** [comment]
I remembered the rest of the weird mess related to this, #7702 ought to fix it properly once and for all.

**Comment by sonix-github** [comment]
@NiLuJe 
I have read #7702 and related stuff about footer and after further testing I have also observed that the highlighted text was in fact overlaid with the footer hence it seems like highlight event has higher priority as skim window when the hold event is in "footers" touch zone. Nightly build from 18th of May is actually not available so I will wait for it and then I will do new testing :)

**Comment by Frenzie** [comment]
That won't be merged for a couple of days yet I'm afraid. Release incoming within 30 minutes. ;-)
