### ISSUE TITLE
KOReader crashes when switching between document view and file browser view or entering history

### ISSUE THREAD

**Issue by Hzj-jie** [koreader/koreader#7706]
* KOReader version: v2021.04-79-gba00f38_2021-05-16
* Device: kindle voyage or pw4

#### Issue

crashes, start happening maybe one week ago. 

#### Steps to reproduce

Likely happens when clicking "file browser" icon in document view or entering history view.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android won't have a crash.log file because Google restricts what apps can log, so you'll need to obtain logs using `adb logcat KOReader:I ActivityManager:* AndroidRuntime:* DEBUG:* *:F`.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>
  
```
./luajit: frontend/readhistory.lua:33: attempt to index field 'document' (a nil value)
stack traceback:
        frontend/readhistory.lua:33: in function 'mandatory_func'
        plugins/coverbrowser.koplugin/listmenu.lua:369: in function 'update'
        plugins/coverbrowser.koplugin/listmenu.lua:178: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        plugins/coverbrowser.koplugin/listmenu.lua:998: in function '_updateItemsBuildUI'
        plugins/coverbrowser.koplugin/covermenu.lua:101: in function 'updateItems'
        frontend/ui/widget/menu.lua:1220: in function 'switchItemTable'
        frontend/apps/filemanager/filemanagerhistory.lua:37: in function '_FileManagerHistory_updateItemTable_orig'
        plugins/coverbrowser.koplugin/main.lua:613: in function 'updateItemTable'
        frontend/apps/filemanager/filemanagerhistory.lua:156: in function 'onShowHist'
        frontend/apps/filemanager/filemanagerhistory.lua:26: in function 'callback'
        ...
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
        frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
        frontend/ui/uimanager.lua:1110: in function 'sendEvent'
        frontend/ui/uimanager.lua:52: in function '__default__'
        frontend/ui/uimanager.lua:1568: in function 'handleInputEvent'
        frontend/ui/uimanager.lua:1648: in function 'handleInput'
        frontend/ui/uimanager.lua:1695: in function 'run'
        ./reader.lua:290: in main chunk
        [C]: at 0x00013f29
```
</details>
stack traces may vary, depending on the crash patterns.

I haven't gone too deep, but the PR https://github.com/koreader/koreader/pull/7658 is suspicious. Last stable release, v2021.04 works fine.

**Comment by NiLuJe** [comment]
No gestures involved?

**Comment by Hzj-jie** [comment]
Nope, but does it not repro on your device? Quite strange, both of my devices have the same issue.

**Comment by poire-z** [comment]
Can't reproduce either (emulator or Android, or with a bit older nightly on my Kobo).
And we just made a release,, so hopefully this is not general :)
Nothing specific to your setup or your own hacks, on _both_ your devices? (With your findhistory plugin, you may have some other tweaks related to these bits of code, that may need update with the recent changes?)

**Comment by NiLuJe** [comment]
Yeah, I couldn't reproduce it either, FWIW.

I mean, if ReaderUI is instantiated on a document that it fails to open, then *maaaaaaybe* this makes sense, but otherwise it'd be quite hard to get a live RD instance without a valid Document handle :s.

**Comment by Hzj-jie** [comment]
Got another repro @ 202105*25

```
05/20/21-22:17:31 ERROR ReaderUI instance mismatch! Opened table: 0x4107f7f0 while we still have an existing instance: table: 0x414c9af8 stack traceback:
        frontend/apps/reader/readerui.lua:455: in function 'init'
        frontend/ui/widget/widget.lua:48: in function 'new'
        frontend/apps/reader/readerui.lua:616: in function 'doShowReader'
        frontend/apps/reader/readerui.lua:574: in function <frontend/apps/reader/readerui.lua:573>
```

**Comment by NiLuJe** [comment]
@Hzj-jie: IIRC, -25 doesn't have the fix ;).

I certainly can't reproduce on master over here.

**Comment by Hzj-jie** [comment]
Sorry, just updated to 35, and it did not reproduce.
