### ISSUE TITLE
Wrong double tap left and right zone

### ISSUE THREAD

**Issue by Mel-kior** [koreader/koreader#7710]
* KOReader version: 2021.05
* Device: : Kobo h2o

#### Issue

Double tap left and right zone are located in top left and right corner instead.

#### Why/Fix

These zones are defined by DDOUBLE_TAP_ZONE_NEXT_CHAPTER and DDOUBLE_TAP_ZONE_PREV_CHAPTER that delimit top corners and not left and right.
https://github.com/koreader/koreader/blob/e70bc60f0fe07ce41f0e0225e030ef32eb82079c/defaults.lua#L91-L92

Should these be deprecated and new DTAP_ZONE_LEFT and DTAP_ZONE_RIGHT be created ? I can do a PR if that help

**Comment by NiLuJe** [comment]
That's... on purpose?

I'm not *quite* sure what you're trying to say/fix?

**Comment by NiLuJe** [comment]
I mean, I wholeheartedly agree that they're super-weird and somewhat non-intuitive and hard to use in practice, but that's arguably another kettle of fish ^^.

**Comment by NiLuJe** [comment]
One could go so far as to say the clunkiness is a roundabout way to make it clear that double taps are terrible and please use gestures instead? ;p.

**Comment by Mel-kior** [comment]
We can configure 6 zones: Top corners, left/right, Bottom corners
But left/right are in fact top corner too. So we don’t have left/right zones and as they are right now they overlap each other.

**Comment by Mel-kior** [comment]
And I get used to double taps and they are quite all right for me. Just the left/right zone are not where they should be

**Comment by NiLuJe** [comment]
Or, well, actually, yeah, it is about the default zone, since GM does setup proper gesture handlers.

**Comment by Mel-kior** [comment]
Yep, I added a new default zone and it’s working fine now.

defaults.lua at line 91
```
DTAP_ZONE_LEFT = {x = 0, y = 1/8, w = 1/2, h = 6/8}
DTAP_ZONE_RIGHT = {x = 1/2, y = 1/8, w = 1/2, h = 6/8}
-- DDOUBLE_TAP_ZONE_NEXT_CHAPTER = {x = 6/8, y = 0, w = 2/8, h = 2/8} -- deprecated
-- DDOUBLE_TAP_ZONE_PREV_CHAPTER = {x = 0, y = 0, w = 2/8, h = 2/8} -- deprecated
```

and in plugins/gesture.koplugin/main.lua at line 803 :

```
    local zone_left = {
        ratio_x = DTAP_ZONE_LEFT.x,
        ratio_y = DTAP_ZONE_LEFT.y,
        ratio_w = DTAP_ZONE_LEFT.w,
        ratio_h = DTAP_ZONE_LEFT.h,
    }
    local zone_right = {
        ratio_x = DTAP_ZONE_RIGHT.x,
        ratio_y = DTAP_ZONE_RIGHT.y,
        ratio_w = DTAP_ZONE_RIGHT.w,
        ratio_h = DTAP_ZONE_RIGHT.h,
    }
```

**Comment by NiLuJe** [comment]
I chose to keep a dedicated "zone", because one could perhaps wish to make 'em different than the single tap zone, even if I can't quite see how that could achieve anything useful ^^.

**Comment by Mel-kior** [comment]
Now that we can chose the action why not name the zone with a more generic name that follow the other naming ( DTAP_ZONE_LEFT ) instead of the NEXT_CHAPTER ?

As well a 50/50 left/right ratio seems better than the 25/75 of the "turn page" zone because we can chose action unrelated to page turning.

And ( If i tested correctly ) if the zone height is 1 ( screen height ) the double tap in the corners don’t work anymore !

**Comment by NiLuJe** [comment]
Mostly backward compat with custom defaults ^^.

Corners zones *should* take precedence over any other zones, so overlap shouldn't be an issue. (They do for tap/hold).
