### ISSUE TITLE
FR: Highlight edit buttons are confusing

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#7713]
**PROBLEM DEFINITON**
Highlight editing buttons which allows adding or removing words from highlighted areas are not intuitive. There are two types of arrows in each icon in different styles with changing order. No offense to the original designer but this dialog looks like a part of an IQ test which you should guess the next pictogram based on the sequence.

![highlight buttons original](https://user-images.githubusercontent.com/84420582/118910348-984bd580-b924-11eb-83c0-88daa931dddb.png)

**OFFERED SOLUTION**
I designed these alternative icons as svg files. If approved I can replace the originals (with some guidance). Also I made the buttons bigger (48px). Considering that an edit to highlighted area needs several button presses (generally to remove the accidentally selected parts of prev/next paragraph) we should aim to make the touch targets bigger (think of people with movement coordination issues).

![highlight buttons mockup](https://user-images.githubusercontent.com/84420582/118910378-a3066a80-b924-11eb-9154-9631f22ea1c8.png)

**Additional context**
I couldn't find these icons under resources folder. Are they rendered as fonts or harcoded ?

**Comment by hius07** [comment]
> Are they rendered as fonts or harcoded ?

https://github.com/koreader/koreader/blob/adf68a178d9c6fc22654236d45b2ac3ba92e5707/frontend/apps/reader/modules/readerhighlight.lua#L620-L623

**Comment by NiLuJe** [comment]
They're unicode arrows, yes.

I'm not a a fan of either approach, but it's way too late for me to articulate exactly why ;D.

(Might be slightly less obscure if the edge arrows were black, to hint that they *expand* the highlights).

**Comment by mergen3107** [comment]
IMO proposed icons are even more confusing.
E.g. the plus sign for left border border is on the right, whereas actually it will add highlight on the left of the border. 
Current icons aren’t perfect, but at least they are consistent once you get used to them

**Comment by NiLuJe** [comment]
IIRC, what was in the back of my mind back when we discussed those would have been something based on bracket-like thingies to represent the HL.

(Keep in mind we didn't have SVG support at the time, so the discussion was very specifically limited to unciode stuff that we had access to).

**Comment by offset-torque** [comment]
> IMO proposed icons are even more confusing.

- This dialog adds and remove words to/from a selection
- Plus and minus signs are universal for adding and removing
- Patterned part shows which side you want to ADD A WORD or REMOVE A WORD

> Current icons aren’t perfect, but at least they are consistent once you get used to them

This button ⇱▷ especially with the small size of e-ink screen looks like minecraft pickaxe. And a triangle is not universal sign for adding or removing too. Sorry but "people will get used to it" is not a valid User Interface design principle.

**Comment by NiLuJe** [comment]
FWIW:

```diff
diff --git a/frontend/apps/reader/modules/readerhighlight.lua b/frontend/apps/reader/modules/readerhighlight.lua
index fb0bdae12..5288493e6 100644
--- a/frontend/apps/reader/modules/readerhighlight.lua
+++ b/frontend/apps/reader/modules/readerhighlight.lua
@@ -617,10 +617,10 @@ function ReaderHighlight:onShowHighlightDialog(page, index)
     }
 
     if not self.ui.document.info.has_pages then
-        local start_prev = "◁⇱"
+        local start_prev = "◀⇱"
         local start_next = "⇱▷"
         local end_prev = "◁⇲"
-        local end_next = "⇲▷"
+        local end_next = "⇲▶"
         if BD.mirroredUILayout() then
             -- Sadly, there's only north west & south east arrow to corner,
             -- north east and south west do not exist in Unicode.
```

![hl](https://user-images.githubusercontent.com/111974/118916115-9b4bc380-b92e-11eb-9518-84f509823cba.png)

**Comment by NiLuJe** [comment]
(Like I said above, I'm not necessarily a fan, but it's mildly less terrible).

**Comment by mergen3107** [comment]
I imagine something like this, but not sure how to easily implement arrows above. Can we do something like letters with arrow on top as a diacritic part? Like in MS Word formula editor
![PROPOSED HIGHLIGHT ARROWS Screenshot 2021-05-19 234214](https://user-images.githubusercontent.com/6279855/118916250-8d7d4a80-b8fc-11eb-9844-953bf887740d.png)

**Comment by NiLuJe** [comment]
Keep throwing stuff at the wall, I'll get back to this tomorrow once I have a working brain ^^.

(One thing we're pretty dead set on is the *order* of the buttons, which the FR's original proposal breaks, regardless of whether we like the design or not).

**Comment by offset-torque** [comment]
I would say even replacing buttons with plain text like **+BEGIN** and **-END** will go further for discoverability. So the users don't have to guess which style of arrow corresponds to what.

**Comment by mergen3107** [comment]
Then maybe:
**<+BEGIN** , **BEGIN->** , **<-END** , **END+>**

**Comment by mergen3107** [comment]
>     * Patterned part shows which side you want to ADD A WORD or REMOVE A WORD
Yes, but plus and minus signs are on the wrong sides of the shaded area in some instances, thus confusing. For example, the first icon set is shade area + plus sign, which slightly implies you want to add the highlight on the right. Second icon set shaded area + minus sign on the right, which is correct, because you will be removing the highlight on the right.

**Comment by offset-torque** [comment]
> **Yes, but plus and minus signs are on the wrong sides of the shaded area in some instances, thus confusing. For example, the first icon set is shade area + plus sign, which slightly implies you want to add the highlight on the right. Second icon set shaded area + minus sign on the right, which is correct, because you will be removing the highlight on the right.**

Yeah I got it. I didn't think that it can be interpreted that way but yes, you are right it can be.

> **Then maybe: <+BEGIN , BEGIN-> , <-END , END+>**

Surely this one is much better (Even better than the icons I proposed. I didn't know this is a text field that's why I made icons.). Even a first time user can understand this without much thinking about it.

**Comment by offset-torque** [comment]
Now I thought about it, if used like in @mergen3107's suggestion, +/- signs become redundant since arrows are now intuitive enough to convey user the movement of highlight so they can be removed for a cleaner look.
So it can be just:

◀ BEGIN | BEGIN ▶  |  ◀ END | END ▶

>  Arrows look orange here but they are:
U+25C0 Black Left-Pointing Triangle / U+25B6 Black Right-Pointing Triangle

**Comment by poire-z** [comment]
> No offense to the original designer

Offense taken :)

> but this dialog looks like a part of an IQ test which you should guess the next pictogram based on the sequence.

I'm sorry that you failed it :/

> Highlight editing buttons which **allows adding or removing words** from highlighted areas are not intuitive

May be because you went on considering this as _adding or removing words_. While, when this feature was being implemented, we considered it more as _extending/shortening the text selection_, so **moving its edges**. #4582

> +/- signs become redundant since arrows are now intuitive enough to convey user the movement of highlight so they can be removed for a cleaner look.
So it can be just:
◀ BEGIN | BEGIN ▶  |  ◀ END | END ▶

So, you end up with what we have :) Test passed!

The issue then is just that the ⇱ and ⇲ symbols for suggesting the begin and end of the current text selection (and that you think plain text "BEGIN" or "END" are better) are indeed a bit ugly/thin/not intuitive, but that's all we found in the Unicode symbols range that are available in our fonts.
May be we can find better ones in the https://www.nerdfonts.com/ nerdfont we now have (dunno if we had it yet at the time).

**Comment by offset-torque** [comment]
> I'm sorry that you failed it :/

**Dude no need for personal attacks. Really ? Is this how you behave towards people who is trying to help the project ?**

> May be because you went on considering this as adding or removing words. While, when this feature was being implemented, we considered it more as extending/shortening the text selection, so moving its edges.

**And you achieve this exactly by adding/removing words. Can you expand without adding words ? Users can't read your mind. From the user perspective it is adding/removing words.**

> So, you end up with what we have :) Test passed!

**It is very different. Word BEGIN is clear for all English language users. No need to learn the association between "minecraft pickaxe look-alike icon"="beginning of selection"**

UI designer has a responsibility to make interface as clear/discoverable/intuitive as possible. Check a cockpit photo. IQ of pilots are among highest of all professions. Yet AIRBUS doesn't slap random icons on buttons and say "Well they will figure it out".

**Comment by Frenzie** [comment]
@offset-torque 
> This button ⇱▷ especially with the small size of e-ink screen looks like minecraft pickaxe. And a triangle is not universal sign for adding or removing too. Sorry but "people will get used to it" is not a valid User Interface design principle.

Well, perhaps you've never used an Apple keyboard (and I'm not particularly fond of them, for different reasons), but it's pretty much the same as home/end.

> Apparently I can't take screenshota while this menu is open. 

You mean with a long diagonal swipe?

@poire-z

**Comment by Frenzie** [comment]
Oops, I meant to reply to something, decided not to, and forgot to remove the mention.

**Comment by offset-torque** [comment]
@Frenzie

> Well, perhaps you've never used an Apple keyboard (and I'm not particularly fond of them, for different reasons), but it's pretty much the same as home/end.

No I never used anything Apple. Linux user for 20 years here. And considering MacOS market share is under 15%, majority of people never seen that keyboard too. I expect even fewer mac users among koreader users. They are generally less technical.

> You mean with a long diagonal swipe?
My screenshot is assigned to corner long tap. That might be blocked while menu is there. Without menu it is working correctly.

**Comment by poire-z** [comment]
> Dude no need for personal attacks. Really ? Is this how you behave towards people who is trying to help the project ?

Well, yes :)
You started it with an all serious, slightly condescending prose, "no offense but..." (which is fine!) - so allow me to answer and strike _a little_ back with a bit of humour (with a good amount of required `:)`), while still explaining our journey to how it currently is (and you might be right on the non-intuitive issue - and _we_ ended up nearly agreeing on our current set of symbols, which _is_ nice and funny).

I expect Airbus and our pilots to be allowed to joke in their offices and cockpits - as long as we end up having a safe trip :)

> My screenshot is assigned to corner long tap. That might be blocked while menu is there. Without menu it is working correctly.

Gestures works only when the Reader is at front - not when there are other widgets in front of it. In that case, only long diagonal swipe (and may be 2 opposite corners taps) works, as they are handled low-level (unlike gestures).

**Comment by offset-torque** [comment]
@poire-z

Don't want to go off topic but the term "IQ test" is not an insult. It is a tool I used in the past due to my profession. That sentence meant buttons are confusing. Here's an example IQ test question next to our buttons. It doesn't look very out of place, isn't it:

![iqtest](https://user-images.githubusercontent.com/84420582/118953782-6c007b00-b95d-11eb-9cbf-63b1e189a0dd.png)

**Comment by Frenzie** [comment]
@offset-torque 
> No I never used anything Apple. Linux user for 20 years here. And considering MacOS market share is under 15%, majority of people never seen that keyboard too. I expect even fewer mac users among koreader users. They are generally less technical.

The point is that it's nowhere close to being as unintuitive as you're making it out to be. We all agree that ⤒ and ⇱ aren't particularly clear when they're small, at least in this particular environment in this particular font. But this *is* the well established European Airbus non-Anglo-centric way of saying "BEGIN" and "END."

![Screenshot_2021-05-20_11-49-59](https://user-images.githubusercontent.com/202757/118958268-8d636600-b961-11eb-9648-e29bfb78e452.png)

**Comment by Frenzie** [comment]
Incidentally, note its look in the font here:
![Screenshot_2021-05-20_11-53-29](https://user-images.githubusercontent.com/202757/118958766-0236a000-b962-11eb-9220-9078d29c7248.png)

**Comment by poire-z** [comment]
Some other idea:

<kbd>![image](https://user-images.githubusercontent.com/24273478/118958937-22665f00-b962-11eb-8f3e-4b36bb600ac5.png)</kbd>

**Comment by Frenzie** [comment]
Would it be particularly difficult to do something like this? That is left/right on both sides with a representation of "selection" in the middle. Something like a fifth inactive button, perhaps.
![Screenshot_2021-05-20_12-01-10](https://user-images.githubusercontent.com/202757/118959979-1af38580-b963-11eb-98d4-d2ab3db671aa.png)

**Comment by offset-torque** [comment]
@Frenzie
> But this is the well established European Airbus non-Anglo-centric way of saying "BEGIN" and "END."

Seriously ? [Even smallest %60 keyboards has HOME written on the HOME key](https://aproxpolska.com/en/blog/news/mechanical-keyboards-size-and-layout-shopping-guide-)

> Its standard symbol ⇱ from ISO/IEC 9995-7, ie. U+21F1 ⇱ NORTH WEST ARROW TO CORNER, is used on some full-size keyboards instead of a possibly localized text label. 

Are you implying koreader users know UNICODE table by heart ? Have you seen mobileread forums ? I am pretty sure 99.9% of users there are unaware of ISO/IEC 9995-7 standard.

@poire-z 
> Some other idea:

Now this looks very logical. Plus aesthetically pleasing. It conveys the meaning extend the block / shrink the block very clearly. Better than text labels even 💯

**Comment by offset-torque** [comment]
@Frenzie
> Seriously, Airbus is European.

I am a sim flyer and spent hundreds of hours in AIRBUS cockpits. All the buttons and fuses in the cockpit has text labels except 5 buttons: 4 navigation keys on MCDU which are four cardinal direction arrows UP/DOWN/LEFT/RIGHT and Swap frequency button on COM/NAV panel which is a double sided arrow. 

I can assure you there are no HOME button (especially with that symbol) nor any ambiguous symbol buttons nor any UNICODE symbols in any of AIRBUS airplanes. You can check for yourself in FCTMs if you don't believe me.

**Comment by hius07** [comment]
> Some other idea:

An optical illusion that the outer greyed rectangles are wider than the inner ones (because of the triangle).

**Comment by Frenzie** [comment]
Regardless, please stop talking about IQ, please stop calling 99.9% of people stupid, and please stop promoting Anglo-centrism as the default option.

**Comment by poire-z** [comment]
> An optical illusion that the outer greyed rectangles are wider than the inner ones (because of the triangle).

Got this impression too :)
Better with some added spacing - but a tad less intuitive about what the arrow means:
<kbd>![image](https://user-images.githubusercontent.com/24273478/118974070-af191900-b972-11eb-9811-0e3d7c7bced4.png)</kbd>

**Comment by offset-torque** [comment]
@Frenzie
> Regardless, please stop talking about IQ, please stop calling 99.9% of people stupid, and please stop promoting Anglo-centrism as the default option.

Dude what you are doing is called gaslighting. I never did what you blamed me of:
- You used the word "STUPID" above first time in this thread. Being technically not proficient doesn't mean stupid. That's like your opinion. I can patch this file as I like once a month, no big deal. I can even automate it. I am opening this topic because I care about people who might be confused by this issue.

- I don't care if you are offended by the word IQ. I am a social scientist and it is part of my job. Do you get offended if someone says gas chromatograph or laser particle analyser ?

- I never promoted Anglo-centrism. I am not even American or European. Should I attack you because your HOME character is Euro-centric. UX design principles are universal. @poire-z last proposal is clearer conveying the function of the button compared to previous version. There's nothing cultural about this.

**Please don't turn a basic user interface usability issue into culture war. I didn't come here for this.**

**Comment by hius07** [comment]
> Got this impression too :)

It's not bad, with the internal buttons we shrink the selection, the illusion becomes reality.

**Comment by poire-z** [comment]
Can someone else test it on his eInk device: [readerhighlight.lua.txt](https://github.com/koreader/koreader/files/6516292/readerhighlight.lua.txt)
On my GloHD (which has minor eInk issues), the hatched rectangles feel a bit dirty, like there's some middle horizontal cut/line - they don't come out as a whole. (Which might also be an optical illusion :)

**Comment by offset-torque** [comment]
**KOBO LIBRA H2O - Perfectly clear here**

![new menu test](https://user-images.githubusercontent.com/84420582/118989752-91ec4680-b982-11eb-9aa4-bfa249b618a4.jpg)

**Comment by Frenzie** [comment]
@offset-torque 
I suggest we drop the matter, but you may wish to reread https://github.com/koreader/koreader/issues/7713#issue-896204403, https://github.com/koreader/koreader/issues/7713#issuecomment-844663185 and https://github.com/koreader/koreader/issues/7713#issuecomment-844833593 when you don't feel like bolding text to see where I'm coming from. ;-)

> Should I attack you because your HOME character is Euro-centric. UX design principles are universal.

You definitely should — just try to avoid "no offense but" and it'll be less attack and more criticism. ^_^

UX design principles may be universal, but the results needn't be. Iconography is somewhat intuitive, but at least partially learned. The universal principle is that representations are reduced to their essence, to simplify them as much as possible. 

The old design not necessarily successfully simplifies "move the beginning/end," where "of the selection" is implied by the context in which the dialog is opened. The new design simplifies "move the beginning/end *of the selection*" directly in the pictogram. Which is a great improvement! But fwiw, the Minecraft pick axe is mostly the result of an oversimplification or a font design choice which obscures the arrow pointing into a corner iconography.

@poire-z I'll check.

**Comment by Frenzie** [comment]
Looks fine on H2Ov1 
![IMG20210520155307](https://user-images.githubusercontent.com/202757/118990883-8ea58a80-b983-11eb-9fbe-988f1d354e55.jpg)

**Comment by offset-torque** [comment]
@Frenzie
Writing over net is a very limited medium that can end up with misunderstandings easily. I will be more careful how my speech comes across. We are cool here.

**Comment by mergen3107** [comment]
> Can someone else test it on his eInk device

Works fine on PW3:
![Reader_2021-05-20_105119](https://user-images.githubusercontent.com/6279855/119001006-9bad8400-b959-11eb-8ea9-f52df79ae927.png)

**Comment by poire-z** [comment]
Quite better. I have checked it at the time of the contrast and zoom to columns/rows SVG icons, and it feels allright. A quick look again now and I notice no "remanence" (might be suggestive, and the hashed black parts may make some stuff lighter, but the other parts are fine - so as a whole, may be that's what makes me not notice it?)

**Comment by mergen3107** [comment]
How about this iteration? I used:

U+2946 | LEFTWARDS ARROW WITH PLUS BELOW | ⥆
U+219B | RIGHTWARDS ARROW WITH STROKE | ↛
U+219A | LEFTWARDS ARROW WITH STROKE | ↚
U+2945 | RIGHTWARDS ARROW WITH PLUS BELOW | ⥅

The arrows look a little shifted downwards and are much smaller, however.

![Reader_2021-05-20_172800](https://user-images.githubusercontent.com/6279855/119051699-7dfc1100-b991-11eb-93b6-9c73abde122e.png)

**Comment by poire-z** [comment]
A bit too small and so hard to grasp I think.
(Guess we're lucky that the current big white arrows have the same height and vertical position as the hatched rectangles :)

**Comment by NiLuJe** [comment]
Possibly a NotoSans vs. FreeSerif fight to the death happening there ;).
