### ISSUE TITLE
InputText: approach to the clipboard

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#7715]
Currently we can copy to the clipboard via highlighting in the reader only.
There is no way to copy anything in the Text editor (and other inputtext boxes).
Holding the text will silently paste the clipboard content.

I would like to:
- copy (at least something) in the Text editor
- take control over the clipboard content
- avoid unwanted paste with an accidental hold

![1](https://user-images.githubusercontent.com/62179190/118959445-ff8c7880-b96a-11eb-8c8e-d80c3219ab8b.png)
--
![4](https://user-images.githubusercontent.com/62179190/118960922-7118f680-b96c-11eb-8ae9-cf3f3fa6dbd3.png)
--
![2](https://user-images.githubusercontent.com/62179190/118959467-04512c80-b96b-11eb-99c2-1b23933355d9.png)
--
![3](https://user-images.githubusercontent.com/62179190/118959485-087d4a00-b96b-11eb-8ab9-a972e86262c5.png)
--

Proposed dialog (available in all input text boxes) is invoked with the hold.
The input box shows current clipboard content and can be edited.
<kbd>Copy</kbd> will copy the edited input to the clipboard.
<kbd>Paste</kbd> will paste the (edited) input into the text.

<kbd>All</kbd> will copy the entire edited text to the clipboard.
<kbd>Line</kbd> will copy the current (pressed) line to the clipboard.
<kbd>Word</kbd> will copy the current (pressed) word to the clipboard.

If the above basic functionality is of interest, the code is ready for PR.

**Comment by hius07** [comment]
Another way is to have a <kbd>Select</kbd> button and hold the start and the end positions of the desired selection.

![1](https://user-images.githubusercontent.com/62179190/118970765-46806b00-b977-11eb-8e09-12213ad12f66.png)
--
![2](https://user-images.githubusercontent.com/62179190/118970775-4a13f200-b977-11eb-8e26-38f2ca9ae7b5.png)
--
![3](https://user-images.githubusercontent.com/62179190/118970791-4da77900-b977-11eb-9f8b-83df687b1868.png)
--
![4](https://user-images.githubusercontent.com/62179190/118970805-5009d300-b977-11eb-8e07-090f70ea2788.png)

**Comment by poire-z** [comment]
> Proposed dialog (available in all input text boxes) is invoked with the hold.
The input box shows current clipboard content and can be edited.

That looks quite fine and clever - a lot better than "hold does paste" that we have.

> <kbd>Copy</kbd> will copy the edited input to the clipboard.

This is a bit non-intuitive, as you're already editing the clipboard content. It means: update clipboard ? 

> Another way is to have a Select button and hold the start and the end positions of the desired selection.

You have this working ?! :) Wow. (Possibly a bit hard to target a precise position with our fat fingers, but that's our fingers' fault, not yours :)

> If the above basic functionality is of interest, the code is ready for PR.

Sure is.

**Comment by hius07** [comment]
> It means: update clipboard ?

Agree, there is no sense to have this button. So, finally (PR will follow):

![1](https://user-images.githubusercontent.com/62179190/118976110-54d18580-b97d-11eb-9746-0efb6f47811e.png)
--
![2](https://user-images.githubusercontent.com/62179190/118976119-58fda300-b97d-11eb-8669-6b685db359a8.png)
--
![3](https://user-images.githubusercontent.com/62179190/118976133-5bf89380-b97d-11eb-9601-68b0f0a15a0e.png)
--
![4](https://user-images.githubusercontent.com/62179190/118976146-5f8c1a80-b97d-11eb-9b4f-3e61feaf32a8.png)
--
![5](https://user-images.githubusercontent.com/62179190/118976159-62870b00-b97d-11eb-9d1f-64a74a7f82c7.png)

**Comment by hius07** [comment]
New article
https://github.com/koreader/koreader/wiki/Clipboard

**Comment by Frenzie** [comment]
Awesome, thanks!
