### ISSUE TITLE
Lost history of SD card's books

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7717]
* KOReader version: 2021/05
* Device: Pocketbook Touch Lux 5 (PB628)

When I open KOReader without having previously inserted the SD card in the device, and insert it later, the SD card's books history is lost.

Could it be fixed?

Thank you.

**Comment by Frenzie** [comment]
Is it possible that you've enabled this setting? That's in the file manager settings (top left icon in the file manager → settings).

![Screenshot_2021-05-20_13-03-08](https://user-images.githubusercontent.com/202757/118968103-cdc7e180-b96b-11eb-88ee-aa88bdeb6eb1.png)

**Comment by poire-z** [comment]
(oups, didn't see @Frenzie 's answer :)

**Comment by ichnilatis-gr** [comment]
Thank you both! It is true that I have enabled this option so that the books whose .sdr file I delete are automatically deleted from the history.

**Comment by poire-z** [comment]
Well, it's indeed a bit dangerous. This setting is used:
- when deleting a file
- when purging .SDR
- in the internal frontend/readhistory.lua `_sort()`, which is used on load and when we add a new item

May be it shouldn't be done in the 3rd case ?

**Comment by ichnilatis-gr** [comment]
>
> Or, use this contrib plugin to rebuild it: https://github.com/koreader/contrib/tree/main/findhistory.koplugin

How can I download the entire folder of the plugin? I can't find a download button...

**Comment by ichnilatis-gr** [comment]
> 
> 
> Well, it's indeed a bit dangerous. This setting is used:
> 
>     * when deleting a file
> 
>     * when purging .SDR
> 
>     * in the internal frontend/readhistory.lua `_sort()`, which is used on load and when we add a new item
> 
> 
> May be it shouldn't be done in the 3rd case ?

I also think it shouldn't...

**Comment by poire-z** [comment]
Get the zip for/from the above directory: https://github.com/koreader/contrib - and just extract the subdirectory you need.

**Comment by Frenzie** [comment]
> May be it shouldn't be done in the 3rd case ?

That seems unlikely? I would assume that removing files and folders using a PC is probably fairly common.
