### ISSUE TITLE
EPUB: In two page mode some highlights do not show up

### ISSUE THREAD

**Issue by WS64** [koreader/koreader#772]
I guess this is related to two pages being shown at the same time, and Koreader just shows the hightlight on the active page, but since there are two pages shown there is a 1:1 chance a highlight will not be displayed.
The highlighting itself works fine, the correct text is selected and everything, it is just that this highlight is not shown in the text. if you switch back to 1 page the hightlight shows up.
Since the drawing of the inverted text before is absolutely fine too I guess this should be very easy to fix, but I cannot find the related part in the source code.

**Comment by smartscripts-nl** [comment]
This issue has been closed, but I have this issue in koreader 2019.2 on my Kobo Forma. So highlights in the second/right column are not shown and only become visible when switching to portrait lay-out.

**Comment by smartscripts-nl** [comment]
Additionally: when I start a highlight in the left column and it continues in the right colum, the first line of text in the right column is shown as not highlighted and the lines below that as highlighted.

**Comment by poire-z** [comment]
Confirmed. It's quite messed up in 2-pages mode.
(I need `DCREREADER_TWO_PAGE_THRESHOLD = 2` in defaults.lua to get them after I resize my emulator to full screen.)

**Comment by smartscripts-nl** [comment]
Hello poire-z,

Thank you for your answer! Changing this setting doesn't solve my problem. Is there any chance this bug will be fixed in an upcoming release?
Sincerely,

Alex Pot
The Netherlands

	versnel en optimaliseer je website
www.smartscripts.nl — www.waalweb.nl  
KVK 34286209 | BTW NL 098677810B01
06 - 420 190 74 | 023 - 5 271 204
Haarlem

Van: poire-z <notifications@github.com>
Beantwoord: koreader/koreader <reply@reply.github.com>
Datum: 7 maart 2019 at 07:46:32
Aan: koreader/koreader <koreader@noreply.github.com>
Cc: smartscripts-nl <info@smartscripts.nl>, Comment <comment@noreply.github.com>
Onderwerp:  Re: [koreader/koreader] In two page mode some highlights do not show up (#772)  

Confirmed. It's quite messed up in 2-pages mode.
(I need DCREREADER_TWO_PAGE_THRESHOLD = 2 in defaults.lua to get them after I resize my emulator to full screen.)

**Comment by poire-z** [comment]
> Is there any chance this bug will be fixed 

There are chances :)
If you are using 2-pages mode (voluntarily? or it just happens you have these 2 pages when switching to landscape orientation?), apart from this highlight issue, is everything else working correctly ?!

I never tested anything in this 2 pages mode - and it seems to work quite OK... but looking at the code, there are only a few places when we check for that - so it's possible that crengine does itself a lot to make it somehow transparent to frontend code, which is surprising.

Of course, there's also the issue when you push text selection up to the top left or bottom right corners and you're switched to one-page scroll mode...

If 2-page mode is really usable (and won't cause many more new bug reports...), it might be interesting to put that as an option, available when width > N*height only.
Currently, it's in 2 pages mode by default in crengine (!), and we switch to 1 page mode under these conditions:
https://github.com/koreader/koreader/blob/dc829d02236d104b43011b77b258e73739b06238/frontend/document/credocument.lua#L194-L197
(with DCREREADER_TWO_PAGE_THRESHOLD = 7 in defaults.lua) which seems strange to me: why dpi matters, why width/height ratio doesn't ?

And [in crengine](https://github.com/koreader/crengine/blob/e68e6b98fd5889a16d0ef57b30438424c6e7dc05/crengine/src/lvdocview.cpp#L3237-L3240):
```c
int LVDocView::getVisiblePageCount() {
	return (m_view_mode == DVM_SCROLL || m_dx < m_font_size * MIN_EM_PER_PAGE
			|| m_dx * 5 < m_dy * 6) ? 1 : m_pagesVisible;
}
```

**Comment by NiLuJe** [comment]
@poire-z : Yeah, that THRESHOLD check is funky.

Traced it back to what was originally a != DXG check.

Implemented in https://github.com/chrox/koreader/commit/865815b42b5033e812ddb8e67085cdd174c65b8d & updated to that logic in https://github.com/chrox/koreader/commit/bcd2c8e8f8d0bafd0f463ce7c4d92ce5c7f6d4a9

For reference, the DXG was using a 824x1200 screen @ 167dpi.

**Comment by NiLuJe** [comment]
I'd indeed be inclined to make that clearer by checking the actual AR with something like min(width, height) / max (width, height).

**Comment by poire-z** [comment]
I think it might as well be nice to have that as a toggle in the bottom menu. Toggling allowed when in landscape mode, and w/h > 1.something, 1.1 or 1.3. crengine won't allow it under 6/5 = 1.2.
So people can still keep landscape mode in 1 page if they prefer that, even on ugly 21/9 phones...

Could keep company to solitary `Orientation: portrait | landscape` - or a 3rd toggle in the one `View mode: scroll | page | 2-pages`
