### ISSUE TITLE
App freeze when WiFi is turned on. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7721]
* KOReader version: latest 5.2021 
* Device:Samsung galaxy Tab A (T-285) android tablet. 

KOReader is freezing when the WiFi is turned on,
And it workes normally after running the WiFi off.

**Comment by Frenzie** [comment]
What exactly is it that you do to turn wifi on/off?

**Comment by Zeyadas** [comment]
The normal way I think.. 

![Screenshot_20210520-174843](https://user-images.githubusercontent.com/70109540/119000331-b270cc80-b993-11eb-99be-121933d32922.png)

**Comment by Frenzie** [comment]
I can't confirm anything like that. You mean unresponsive while just reading a document? Or are you doing something specific?

**Comment by Zeyadas** [comment]
Yes.. That's what I meant, unresponsive (can't turn pages or opening menus until I turn off the wifi and it works normally.

**Comment by NiLuJe** [comment]
We're most likely going to need verbose debug logs to have an idea of what might be happening there.

**Comment by Zeyadas** [comment]
What is verbose debug logs? I'm not familiar with this..

**Comment by pazos** [comment]
Doesn't make sense at all. Maybe is related to https://github.com/koreader/koreader/issues/7651?

Anyways. Debug logs can be enabled from FM -> Tools -> More tools -> dev options -> enable debug logs.
If you wait until the next nightly you can generate a crash.log in Help -> Bug Report.

The proper way of reporting the issue would be.

Uninstall current APK
Install last nightly
Start, enable debug logs
Restart the app, reproduce the bug and go to report bug
Copy the `crash.log` file and paste it here.

**Comment by Zeyadas** [comment]
OK I'll wait for the next nightly and do that as instructed, and now when using the (resent apps soft key) koreader stop working.


![Screenshot_2021-05-21-01-33-09](https://user-images.githubusercontent.com/70109540/119057241-cd176580-b9d4-11eb-9924-20283252e5c3.png)

**Comment by pazos** [comment]
> OK I'll wait for the next nightly and do that as instructed

Well, maybe not tomorrow nightly :P. Very soon :tm:. I'll ping you :)
 
>  when using the (resent apps soft key) koreader stop working.

That's a crash. Easy to see on logs. Hopefully easy to fix. Is the previous stable build affected by this bug?

**Comment by Zeyadas** [comment]
About the crash the previous version did crash sometimes but I thought its a problem with my tablet, restarted it and forgot about testing it after restarting and didn't use the resent soft key.. 

And thanks I'll be waiting for the nightly version..

**Comment by Zeyadas** [comment]
I think that the solution in  https://github.com/koreader/koreader/issues/7720#issuecomment-846273272 worked for this too.. I don't know how it's (connected).
Koreader is not freezing anymore while Wi-Fi is on after deactivating it..

**Comment by pazos** [comment]
@Zeyadas: feel free to reopen if you find the issue again. The log report procedure described in https://github.com/koreader/koreader/issues/7721#issuecomment-845310436 will work in any recent nightly from now on :)
