### ISSUE TITLE
Android update current reading position lost

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#7724]
* KOReader version: 2021.5–24
* Device: Android Tolino

#### Issue
When you read a book. If you update the Android app KOReader reinstalls itself. If you open the book again you are at an old reading positon.

#### Steps
Open koreader in FM. Open book. Read two pages. Update from the menu.
Reinstall ...
Open koreader in FM. Open book. You are on the old readig Position.

**Comment by NiLuJe** [comment]
I'm unsure how how the app killing happens in this case. Do we get anything? If we only "catch" a DESTROY, UIManager:quit() isn't enough, we need to do that same dance than the Generic `Device:install` w/ the Exit CB (or do it by hand like USBMS).

**Comment by pazos** [comment]
> When you read a book. If you update the Android app KOReader reinstalls itself.

I'm assuming you're not talking about the new feature "prompt for update when APK ready". IIRC you get a prompt saying "your device is unable to download the APK, retry using the browser? and, when the APK is downloaded you click on the notification for installing the app.

Please correct me If I'm wrong. That would be awesome (as the retry prompt was written for the Tolinos)

> I'm unsure how how the app killing happens in this case.

The app is killed by the activity manager just when the user confirms it wants to update the APK

>  we need to do that same dance than the Generic Device:install

Yeah, that should work for autoupdates with prompt, but still fails if the user downloaded the APK using the browser.

For now is safe to do the dance each time the app is paused. If/when multiwindow mode is done we might need to save settings on pause in single window mode and on stop in multiwindow mode.

**Comment by pazos** [comment]
Reopening the ticket. Still happens, apparently: https://www.mobileread.com/forums/showthread.php?t=340558

Can somebody read https://github.com/koreader/koreader/blob/master/frontend/device/android/device.lua#L485-L498 and give me ideas?

I'm assuming the whole chunk of lua code is executed before the event is transmitted to all widgets. Is there any way to do a blocking "SaveSettings" before `android.ota.install()`?

**Comment by zwim** [comment]
Maybe UIManager:tickAfterNext(function())

**Comment by Frenzie** [comment]
Yes, I think what @zwim said should do it. You could also consider a scheduleIn 1 or 2 seconds bruteforce method if it doesn't.

**Comment by NiLuJe** [comment]
I'm also not entirely convinced the `SaveSettings` Event actually saves *global* settings... ^^.

c.f., `ReaderUI:saveSettings`

**Comment by Frenzie** [comment]
Current reading position isn't global settings though, or what do you mean exactly?

**Comment by NiLuJe** [comment]
Not sure it does that for DocSettings either, actually ^^.

**Comment by Frenzie** [comment]
That sounds more relevant. ;-D

**Comment by NiLuJe** [comment]
Everything *should* call the relevant stuff on `Close`, though, but I don't think that's viable here because this may fail so we still need the UI or something?

**Comment by pazos** [comment]
@NiLuJe: I don't understand most of what you wrote :p 

Logic before https://github.com/koreader/koreader/pull/7753/commits/7af1505f38b52c3a25a3ea09884d664cae1363b2 was sending `Event:new("FlushSettings")` (called by UIManager's `saveState` function). The new one uses `Event:new("SaveSettings")`.

I don't know if these events are different and can't recall why I changed this so I'm open to revert back for any reason.

AFAICT the bug cannot be reproduced killing the app (as in: 1. open app, 2. read a few pages 3. kill app from recents).

I think the event is fine, but needs to be catched by all relevant widgets (in this case `ReaderUI`) before we call `finish()` on the activity.

**Comment by NiLuJe** [comment]
`FlushSettings` would let `ReaderUI` do the right thing, AFAICT.
