### ISSUE TITLE
FR: Highlighting across pages sends user to previous page

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#7726]
**Firstly thanks to everyone who participated in the HIGHLIGHT EDIT BUTTONS fix. It looks beautiful now !**

**PROBLEM:**
I am reading a paragraph that continues to next page and upon finishing I decide to highlight it. 
I go to previous page and start highlighting. 
When reached to the end of page, koreader turns the page for me so I can continue my highlight. Clever. 
But after finishing highlight it sends me back to the previous page.

Why is it doing this ? I already read the highlighted part. That's how I know it is worth highlighting, right. Do people highlight before reading so this allows them to read the higlighted part ? Am I missing a use case here ?

This behaviour becomes a chore when reading academically because there are lots of highlights, and each highlighting action sends me back one page.

**OFFERED SOLUTION:**
If there is not a legitimate reason for this behaviour, I would much prefer koreader to stay on next page to let me continue reading from the end of highlight (like we do in real books). 

If it is crucial, at least an option under highlight menu to choose the behaviour would be nice.

**Comment by poire-z** [comment]
It's a generic "feature" of text selection across pages, and the need to switch from page mode to scroll mode - and having to restore page mode when done, and having to decide about which page.
It feels right to get back where you started (and show a marker in the margin) after you've been distracted doing other things : Wikipedia, translation, adjusting/deciding what to highlight.

Even for highlighting, it doesn't feel odd to me: it's hard doing precise long-press and precise highlighting; getting you back to the start page allows you to make sure, after you removed your (that's a generic collective "your" :) fat fingers from the screen that your valuable highlights are exactly what you wanted.
The next page is just a tap away.
(You could always start highlighting from the end - and you'll get back to this page - and this even saves you a tap to go to previous page to start highlighting there :)

**Comment by offset-torque** [comment]
> It's a generic "feature" of text selection across pages, and the need to switch from page mode to scroll mode - and having to restore page mode when done, and having to decide about which page.

I was curious about the reason. Now it makes sense (technically).

> Even for highlighting, it doesn't feel odd to me: it's hard doing precise long-press and precise highlighting; getting you back to the start page allows you to make sure, after you removed your (that's a generic collective "your" :) fat fingers from the screen that your valuable highlights are exactly what you wanted.

I have enough line spacing and libra might be fast enough so my selections are accurate. But yes it makes sense for smaller screens or older hardware or less coordinated users I guess.

By the way, if I switch to **CONTINOUS** mode instead of **PAGE** this problem disappears, it stays where it is. So this solves my problem and makes this issue solved. Should I close it or what ?

I wish this info was written somewhere. I don't even know the difference between two modes or if there's a disadvantage to any of them (like rendering overhead or CPU usage). I guess I just lose last line to status bar because now there's no bottom margin.

**Comment by poire-z** [comment]
> By the way, if I switch to CONTINOUS mode instead of PAGE this problem disappears, it stays where it is. So this solves my problem and makes this issue solved. Should I close it or what ?

Continuous = the human name of what we might call "scroll mode" (technically).
I guess nobody really cares about scroll mode, and I may just have forgotten to do any restoring of previous position in scroll mode :) (but rest assured I have no plan to fix that :)
If that's good enough for you, yes, close it :) I just don't wish to work on making that an option.
But may be just spend some time with how it currently is in page mode, now that you know the technical whys and contexts where the current behaviour makes sense - may be you'll get used to it and will appreciate it :)

>  I don't even know the difference between two modes or if there's a disadvantage to any of them (like rendering overhead or CPU usage). I guess I just lose last line to status bar because now there's no bottom margin.

Truncated lines at top or bottom, but the ability to scroll by fraction of pages to adjust the position of a paragraph, etc... But no nice pages with top and bottom margins (and no "in-page footnotes).

**Comment by Frenzie** [comment]
I'd say continuous is mainly a thing that exists. It's unclear if it has any advantages besides the obvious (precisely adjusting your position by the pixel). You lose out on footnotes, you get lines cut in half, etc. It's like all the worst parts of paged media like PDF but you can't even opt for full page! ;-)

**Comment by offset-torque** [comment]
> But may be just spend some time with how it currently is in page mode, now that you know the technical whys and contexts where the current behaviour makes sense - may be you'll get used to it and will appreciate it :)

I use none of the options in highlight menu, just direcly highlight (to export later into my database). Also on e-ink devices page refresh is slow and flashes highlighted part. I wouldn't mind if it was an LCD but 2-3 refresh per highlight got really annoying for me considering I nearly have highlights in every page in some books.

So I think I will sacrifice my margins to avoid this (as long as continous mode is there or I got annoyed by half cut lines :)
Thanks for answers @poire-z @Frenzie

**Comment by Galunid** [comment]
> I go to previous page and start highlighting.
When reached to the end of page, koreader turns the page for me so I can continue my highlight. Clever.
But after finishing highlight it sends me back to the previous page.

Don't go to the previous page to highlight. Start highlighting from the current page and go up (it'll automatically move to the previous page) and it'll send you back to the current page once you finish highlighting
