### ISSUE TITLE
FR: Set "end book at" page in place of last page

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#7729]
I'd like to be able to set an "end book at" page in place of the last page, for books that e.g. contain footnotes (I'm looking at you, Anna Karenina) and "read an excerpt from the author's next book".

My thought is that this would replace the last page number in "pages left/remaining/etc" in the footer and perhaps elsewhere.

I've had a few thoughts on how to implement this, including:

1. Letting the user choose an "end chapter", so "end book at" would be set at the last page of the chapter
2. Letting the user directly enter a last page. This could be converted to a percentage, and recalculated when a book is reflowed.
3. Letting the user set a bookmark, and have "end book at" be set to "next bookmark"

Is there any interest in this sort of thing? If so, I would appreciate any thoughts on how to best implement it.

**Comment by hius07** [comment]
Footnotes can be excluded with checking `Hide non-linear fragments`.

**Comment by zwim** [comment]
@JasonInOttawa 
> and "read an excerpt from the author's next book".

I vote for 1. and 2.

**Comment by NiLuJe** [comment]
That feels like an incredibly niche feature for an issue that's entirely fixable by the ePub flow/non-linear fragment thingy.

**Comment by JasonInOttawa** [comment]
Thanks to all for your comments and input. I'll try the Hide non-linear fragments option and close this for now.

**Comment by poire-z** [comment]
> an issue that's entirely fixable by the ePub flow/non-linear fragment thingy.

(I hope you're suggesting people to go edit their EPUB on their PC ! Because some evil developper might take that as a suggestion it would be a good idea to add some API to crengine so we can manipulate and arbitrary assign "non-linear" attributes to DocFragments via some kind of KOReader UI... :/)
(Which is not a good idea :)

**Comment by poire-z** [comment]
> :eyes: 

I meant that [99% of EPUBs](https://github.com/koreader/koreader/issues/6809#issuecomment-719723694) don't have [any usable non-linear info](https://github.com/koreader/koreader/pull/6847#issuecomment-725380475), so if this FR is to be solved with our existing non-linear support (#6847 #6809), it means users will have to edit their EPUBs on their computer (which is what @Jellby seems to be doing - dunno if calibre can help with that).

By [evil developper](https://github.com/koreader/koreader/pull/7623#discussion_r628466247), I hinted at @zwim, who is not afraid of playing with crengine, and obviously a fan of this FR, to refrain from trying to solve this on the crengine side :)
If this FR would really be needed, a few `total_pages = settings.fake_end_page or document.page_count` in some display-only parts of the frontend code would be a lot easier (although not that easy, we don't want to see 245/192 or "pages read: 112%", or messed up statistics). And it would then also be available with PDFs.

I wouldn't say it's "niche" (I don't care much about % read or time remaining, but I've seen myself sometimes note in my head the book content ends at 92% page 867, and do some substraction to get how many % or real pages I still have to read...) but I agree it's not worth the possibly added complexity and risks in the many little places that deal with total_pages.
