### ISSUE TITLE
syntax error: you disabled math support for  $((arith)) syntax

### ISSUE THREAD

**Issue by Diniboy1123** [koreader/koreader#7732]
* KOReader version: 2021.05
* Device: Pocketbook 624

#### Issue

I had a broken Pocketbook 624 device until today. Its internal SD card was read only and I had to replace it to a brand new 32 GB one. While moving away from the old card I have also noticed many bad and unreadable blocks and corrupted sectors. But the system seems to be all fine and since then I could run a complete firmware upgrade to the latest Pocketbook fw released somewhere in 2016 for this specific model and everything works fine from what I can tell on the base system.

However I wanted to install koreader on it and therefore did, as the wiki suggests here: https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices

So I copied the koreader folder and the koreader.app file to applications/ like I did with other apps and then unplugged the pocketbook from my PC.

Now when I go in the device menu to Applications, I can see the koreader folder and a page after the actual koreader app. However clicking on it seemingly does nothing, other than a screen refresh.

I have then plugged the e-reader back to my PC to see if I see a crash log within applications/koreader, but there was none. Then I tried to look at the app script and figured it should create a /tmp/koreader.pid file as a very first step after starting. Was wondering maybe it fails earlier, like with a trivial issue such as not finding the koreader folder. But nah, since I installed pbterm at the same time as koreader, and that one launches, I could check that the pid file is indeed created correctly. However the app itself never starts or prints or does anything other than a screen refresh. I get thrown back to the app picker.

I am a bit clueless what to do next. I got some ideas for debugging, such as creating another script to call this koreader.app script with an `sh -x` flag to see where exactly does it get stuck, but maybe you have a better idea what could I do.

I could imagine that the fw update I did didn't overwrite certain libs or something koreader depends on and they are still corrupted. 🤷

**Comment by Diniboy1123** [comment]
Actually I figured a way to launch koreader. I did what I said earlier, ran the koreader.app manually with debug symbols so I can see where it fails. First of all I got the error that /mnt/secure/su doesn't exist, but I assumed I could safely ignore that as even the comment above it suggests its a try only. The next error was interesting however:

```
syntax error: you disabled math support for 
$((arith)) syntax
```

So I opened the koreader.app script again on PC and replaced all occurences of (( to a single ( and all )) to ). As my built-in busybox doesn't seem to like the doubled ones. Now it all starts great!

**Comment by NiLuJe** [comment]
Yeah, some old, old FW have a truly terrible busybox ash version. I can't really think of a saner way of handling those.

**Comment by Diniboy1123** [comment]
Yeah I am aware it's not a real fix. But I checked, in most places it should work. How about shipping a minimal sh binary with koreader as well?

**Comment by NiLuJe** [comment]
> What I don't get is that seemingly I am running the latest firmware on this Pocketbook 624 and it is listed as supported within the devices.lua file. And I assume it has been tested before. So either busybox was packaged differently in the earlier versions, or it was never working?

The startup script didn't always require arithmetic support (which, err, is POSIX :/).

Someone with an affected firmware could look into whether replacing the arithmetic expansions with `let`/`expr` shenanigans is doable.

**Comment by Diniboy1123** [comment]
I did some testing. Executing `let x="2+2"` resulted in a no command found error using the shipped busybox. However `expr 2 + 2` worked, and resulted in the intended 4 output.

It seems like expr is simply a symlink on this firmware to busybox, but it's still separate from the shell binary (which is also a busybox symlink) therefore I assume it is slower. But don't think it matters much on our scale for logging...

At this point I believe we have two choices. Relying on expr or shipping a custom version of the shell binary that's for sure compiled with the missing arithmetic functions.

**Comment by Frenzie** [comment]
> At this point I believe we have two choices. Relying on expr or shipping a custom version of the shell binary that's for sure compiled with the missing arithmetic functions.

Maybe it's just me, but compiling an entire shell binary sounds like an incredibly convoluted, overcomplicated option. :-P

**Comment by Diniboy1123** [comment]
It is indeed increasing the size of the package with an extra 500 kb or so, but it would also resolve all the inconsistency issues between the firmware versions. Optionally it could also be detected and downloaded manually once needed during the runtime with a simple check.

**Comment by Frenzie** [comment]
The size of the package is not my concern: the complexity and maintenance burden is. But I'll defer to @pazos and @NiLuJe's thoughts.

**Comment by NiLuJe** [comment]
Oh, yeah, definitely `expr` over shipping busybox or dash ;).

**Comment by Diniboy1123** [comment]
Fair enough. I imagined something like a precompiled static binary you once ship as an asset and then forget about it (or occasionally provide an update for security patches, but I am not sure if that one is even needed on an ebook reader).

But if the expr change could be done I would be happy too.

**Comment by pazos** [comment]
Affects PocketBook840 too: https://github.com/koreader/koreader/issues/6889
