### ISSUE TITLE
Crash with second switching to file manager

### ISSUE THREAD

**Issue by fradav** [koreader/koreader#7738]
* KOReader version: v2021.05-35-gbee2a60_2021-05-22
* Device: Kobo Aura H2O (N250)

#### Issue
Can reproduce on my kobo aura H2O (N250). First opening of the file manager is ok, but second switch is guaranteed crash. 
Does it since 2021-05 release, and in nightly -25, -35 too.
Happens since release 2021-05, and in nightly -25 too.
Looks like #7706

#### Steps to reproduce
Open file manger one time, choose a book, and open file manager again.

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
05/23/21-04:40:23 DEBUG setDirty via a func from widget table: 0x2c055620
# 05/23/21-04:40:23  INFO: invalid widget for setDirty() stack traceback:
	frontend/ui/uimanager.lua:872: in function 'post_guard'
	frontend/dbg.lua:68: in function 'setDirty'
	plugins/coverbrowser.koplugin/covermenu.lua:119: in function 'updateItems'
	frontend/ui/widget/menu.lua:1220: in function 'switchItemTable'
	frontend/ui/widget/filechooser.lua:362: in function 'refreshPath'
	frontend/ui/widget/menu.lua:1025: in function 'init'
	frontend/ui/widget/filechooser.lua:166: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/apps/filemanager/filemanager.lua:179: in function 'setupLayout'
	frontend/apps/filemanager/filemanager.lua:737: in function 'reinit'
	frontend/apps/reader/readerui.lua:494: in function 'showFileManager'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1111: in function 'sendEvent'
	frontend/ui/uimanager.lua:223: in function '__default__'
	frontend/ui/uimanager.lua:1573: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1653: in function 'handleInput'
	frontend/ui/uimanager.lua:1700: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00014161
```
</details>

**Comment by fradav** [comment]
I don't know if it is a separate issue but pinch to zoom in images doesn't work anymore (it worked in 2021.04).

**Comment by NiLuJe** [comment]
Post a full log please, that's completely irrelevant ;).

**Comment by NiLuJe** [comment]
> I don't know if it is a separate issue but pinch to zoom in images doesn't work anymore (it worked in 2021.04).

In which context?

**Comment by fradav** [comment]
Sorry was reluctant to post it because there is "personal" informations in it. Anyway attached it.

Tried start_with both with last document or file manager, but same crash occurs.

[crash (1).log](https://github.com/koreader/koreader/files/6527521/crash.1.log)

**Comment by fradav** [comment]
> > I don't know if it is a separate issue but pinch to zoom in images doesn't work anymore (it worked in 2021.04).
> 
> In which context?
> 
> (Also, yes, completely separate).
> 
> EDIT: Given the very, very few places that actually implement a pinch/spread gesture, I'm going to guess ImageViewer? (e.g., view full size covers). In which case, can't repro. Even on a H2O, where pinch & spread are iffy because IR grid.

Yes, ImageViewer in CRE. Sorry again, didn't investigate much further, I just remember pestering about it while trying it in -35 and just having been relieved to see it working again after downgrading to 2021.04

**Comment by NiLuJe** [comment]
Do you have a timestamp for when you think it crashed? Because I don't see any crashes in that log (at best, I can see a maybe SleepCover faceplant).

**Comment by NiLuJe** [comment]
Definitely can't reproduce any pinch/spread issue, though. More details?

**Comment by fradav** [comment]
> Do you have a timestamp for when you think it crashed? Because I don't see any crashes in that log (at best, I can see a maybe SleepCover faceplant).

Crash is at 8:49:54
Attached video

https://user-images.githubusercontent.com/701587/119251200-a3616880-bba5-11eb-8077-0b0fe0324414.mp4


[crash.log](https://github.com/koreader/koreader/files/6527650/crash.log)

**Comment by fradav** [comment]
> Definitely can't reproduce any pinch/spread issue, though. More details?

Works in -39... ah well forget it, perhaps I hallucinated that.

**Comment by NiLuJe** [comment]
Okay... That's... super-weird.

That's not a crash. That's a sane exit. Worse, that's a *specific* sane exit that *requests* an Exit (otherwise KOReader would restart, instead of dumping your to Nickel).

**Comment by fradav** [comment]
> Okay... That's... super-weird.
> 
> That's not a crash. That's a sane exit. Worse, that's a *specific* sane exit that *requests* an Exit (otherwise KOReader would restart, instead of dumping your to Nickel).
> 
> o_O.

Is there a setting which could be tested, related to something committed between 2021.04 to 2021.05? Git bisecting by myself on a real device is out of question from my part  😙

**Comment by Frenzie** [comment]
Did you create any custom actions or gestures for exit?

**Comment by NiLuJe** [comment]
I mean, sticking a traceback in UIManager:quit would probably be a good start ;).

**Comment by Frenzie** [comment]
You mean for this very specific ticket? That just sounds… weird. ^_^

**Comment by NiLuJe** [comment]
Okay, I'd missed the "no more widgets" warning.

I smell a wonky onCloseWidget handler somewhere, quite likely in a plugin. ReaderUi's onCloseWidget is never fired here, and Wallabag, in particular, appear to be spending that time living its best life doing weird crap in the background?

Does disabling the Wallabag plugin magically fixes this?

**Comment by NiLuJe** [comment]
Yeah, something is stopping onCloseWidget way too early, which means the FM instance is never flagged as gone, so, when exiting ReaderUI, it simply tries to *reinit* the existing FM instance. that doesn't *show* anything, and since the FM instance *has* in fact been closed => no more widgets.

And since true exit is the default, that means back to Nickel.

**Comment by NiLuJe** [comment]
@fradav: Does applying https://github.com/koreader/koreader/pull/7744 help?

**Comment by fradav** [comment]
> @fradav: Does applying #7744 help?

Do I have to setup a build environment to make a kobo binary and test that or is there a simplier way ?

**Comment by NiLuJe** [comment]
It's plain Lua, so, you can just replace the modified files.

Or, if you have shell access and trust that busybox's patch won't break it too much,

```
cd /mnt/onboard/.adds/koreader
wget https://github.com/koreader/koreader/pull/7744.diff
patch -p1 < 7744.diff
```

(I don't actually remember if the stock wget supports HTTPS, but, you get the idea ;)).

**Comment by NiLuJe** [comment]
In case that's easier to deal with, here's a tarball with the files.
[pr7744.tar.gz](https://github.com/koreader/koreader/files/6528668/pr7744.tar.gz)

**Comment by fradav** [comment]
(Thanks for the "live-patching", neat trick)
anyway, same "weirdness", exit to nickel while clicking on file manager.

[crash.log](https://github.com/koreader/koreader/files/6528689/crash.log)

I tried with wallabag extension deactivated as @Frenzie suggested, no effect.

And no, no custom gesture or action configured.

**Comment by NiLuJe** [comment]
Hmm. Let's try without KOSync, then?

Barring that, if you can provide us with your `settings.reader.lua`, I can try to repro that locally...

**Comment by NiLuJe** [comment]
> (Thanks for the "live-patching", neat trick)

Err, just in case that wasn't clear: you will have to restart KOReader after modifying the Lua code, though ;).

**Comment by mergen3107** [comment]
Is Cloud Storage also considered as "plugin"? I noticed that it is the only plugin visible only via FM. So maybe it is being tripped over when @fradav goes to FM?

**Comment by NiLuJe** [comment]
@mergen3107: Nope, it's a very old piece of code that hasn't been modularized.

**Comment by fradav** [comment]
Nailed it: it was the analog clock contributed module... I completely forgot this one, sorry guys.

**Comment by Frenzie** [comment]
Does removing this line fix it then?
https://github.com/koreader/contrib/blob/5ed548336a7d4f0e3af49a14b19c4ab3882a56f0/clock.koplugin/main.lua#L75

**Comment by fradav** [comment]
> Does removing this line fix it then?
> https://github.com/koreader/contrib/blob/5ed548336a7d4f0e3af49a14b19c4ab3882a56f0/clock.koplugin/main.lua#L75

Yes, indeed.
