### ISSUE TITLE
FR: Highlighting action should be optimized for e-ink devices

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#7748]
Current highlight process is a copy of "mouse selection on a computer with a big and fast screen" and it can certainly be improved for our less capable devices. 
**Problems with this approach:**

- A mouse has much higher resolution than finger. That's why even though mobile phones has very high screen resolutions, their buttons as touch targets should be bigger to accomodate touch.

- A computer or tablet screen with LCD or OLED has a high refresh rate starting from 60 going up to 240 Hz. So feedback is instantaneous. E-ink screen refresh rate is abysmal and updating parts of screen leaves artifacts until the full page refresh.

**CURRENT PROCESS VS PROPOSED ACTION**

Currently highlighting text follows this procedure:
1. Long click on a word
2. Move finger to the end of selection while keeping it on the screen

**Moving my finger requires:** 

- Device to calculate the position of my finger continuously
- Determine where it is, related to text continuously
- Highlight the selected part continuously to give me feedback

**Problems with this approach:**
- Finger must be kept on the screen while moving it to the end of highlight. This is harder for older users and young users with various motor control problems
- E-reader screens are not as slick as mobile phone screens because they are generally matte and made of plastic instead of glass. This makes precise finger positioning harder
- E-reader hardware is less capable than tablets or mobile phones. Even my Kobo Libra (which is a last generation device) sometimes interprets as "finger left the screen" during highlighting. I have to delete "half-highlight" and do it again. Older generation devices should be even worse in this aspect
- Constant highlighting and updating screen is a slow process that uses battery because of calculations and e-ink update

**PROPOSED SOLUTION**

For a highlight event KOreader needs only two piece of information from the user:
1. First word of selection
2. Last word of selection

**It doesn't need user's finger moving all over the text. So we can just do this:**
1. Long pressing on a word enters selection mode
2. Clicking on another word ends selection and highlights text

Just two clicks and one screen update. Less work for user, less work for device, less update cycles for e-ink, less battery usage. Win/win for everyone. And I guess the code will be simpler while not doing real time finger position calculation and text correlation and intermediate updates.  For selections that span over multiple pages, swipe can be used to turn page and click can be reserved for "end of selection" action.

**BUT "LONG CLICK ON WORDS" IS USED FOR OTHER OPTIONS TOO (search, dictionary etc.)**
Well that is the brainstorming part. Maybe "long click and move finger a bit" can initiate selection mode. Then user can click the end of highlight. But I don't know how gesture input system works, so I can't comment about possible solutions.

**Comment by hius07** [comment]
Current highlighting with dragging can be kept as is.
Just add the button `Select` to the highlight menu. Pressing it starts the selection from the highlighted word, then waiting for long-pressing on another word, which marks the end of selection.

**Comment by offset-torque** [comment]
> Just add the button Select to the highlight menu. Pressing it starts the selection from the highlighted word, then waiting for long-pressing on another word, which marks the end of selection.

Yes this was what I thought as a menu based solution

**Comment by NiLuJe** [comment]
For inspiration, c.f., Plato's behavior, which I described a few months ago, which is, IIRC: starting a highlight (probably long press) enters "highlight mode" where *every* tap means "update start/end highlight pos" and a long-press ends the session.

(I may be remembering that wrong).

**Comment by Frenzie** [comment]
That must be new? I just checked Plato and it behaves the same as KOReader (if a bit faster and therefore easier to use, in drawing and/or text position/selection).

**Comment by NiLuJe** [comment]
I may have been dreaming that one then ;p. (No idea when I tested this last).

**Comment by Frenzie** [comment]
My Plato isn't the most recent one, but I don't see anything about highlights in the changelogs.

**Comment by offset-torque** [comment]
> For inspiration, c.f., Plato's behavior
I installed latest Plato and it behaves same as KOReader like Frenzie said. But your description is exactly what I was envisioning as a dragless highlight solution.

By the way I am surprised Plato highlighting is much smoother. I wonder if crengine can be optimized to that level or it has inherent overheads that prevents this.

**Comment by hius07** [comment]
> 2\. Clicking on another word ends selection and highlights text

Not clicking but long-pressing (as we can turn pages with a tap).

In details: select starting fragment (or word), press `Extended highlighting` (wordings and buttons placement to be discussed later) in the popup menu, go to any position in a book in any ways, including SkimWidget, select ending fragment (or word) there, get the highlighted text between the fragments (including both fragments).

Highlighting one hundred consecutive pages took about 5 sec on my Kindle (counting from the ending long-pressing until showing up the highlighted text on the last page of selection).

**Comment by hius07** [comment]
Closed with https://github.com/koreader/koreader/pull/8432.
