### ISSUE TITLE
Multiswipe "Go to page" in Browser gone?

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#7752]
Version 2021.05-35

If my memory isn't failing me, I used to multiswipe when I wanted to jump to a certain page or letter in my library. Can't do that anymore. 

Gone by mistake?

And yes, I know I can tap on page at the bottom.

**Comment by Frenzie** [comment]
I don't recall that, but if something was inadvertently broken I guess we'd be talking pre-https://github.com/koreader/koreader/pull/6106?

**Comment by NiLuJe** [comment]
Not *quite* sure what you're decsribing, exactly, to be honest ;).

(Then again, not a swiper, so *multi* swipes? Brrr! :D)

**Comment by gerhaher** [comment]
> I don't recall that, but if something was inadvertently broken I guess we'd be talking pre-#6106?

Oh, that was a long time ago. Strange...

I use down&up to go to page when reading and it just feeeels right to do the same in browser (and like I have always done that).

**Comment by Frenzie** [comment]
Up, down will take you to the file browser by default, same as the file browser icon in the top menu. But there's no go to page involved.

**Comment by gerhaher** [comment]
Haha, no I am right.

I tried my other device with version 2021.03-12 installed. And here this 'go to page' multiswipe works.

So someone has removed it.

Pleeease, hand it back.

**Comment by Frenzie** [comment]
In that case a likely suspect might be https://github.com/koreader/koreader/pull/7609

**Comment by gerhaher** [comment]
Updated my android, version 2021.05
The multiswipe worked here too.

**Comment by NiLuJe** [comment]
> Updated my android, version 2021.05
> The multiswipe worked here too.

Unclear. Worked on 2021.05, or worked on whatever you had before (which is what, exactly?) ^^.

Also, new question: what was the other platform you tested earlier?

**Comment by gerhaher** [comment]
> > Updated my android, version 2021.05
> > The multiswipe worked here too.
> 
> Unclear. Worked on 2021.05, or worked on whatever you had before (which is what, exactly?) ^^.
> 
> Also, new question: what was the other platform you tested earlier?

Work with 2021.05  (and worked before with whatever version I had before, from february)

Kobo Aura

**Comment by gerhaher** [comment]
The change happened with version 2021.05-32

**Comment by Frenzie** [comment]
Nothing jumps out at me at a glance.
https://github.com/koreader/koreader/compare/a7f23ef...0e83551

**Comment by poire-z** [comment]
Probably https://github.com/koreader/koreader/commit/78fdce8e9fb2b0e1efc7a1ff5c4088b06f634bad , and:
https://github.com/koreader/koreader/blob/ad3bc29b1ed5b8a3b8edf1b9e632cb4c5ac8b5e0/frontend/dispatcher.lua#L106
being now tied to working only in Reader.
Please try just removing `, rolling=true, paging=true` from this line.
(May be there are other among them that did also work in FileBrowser.)

**Comment by gerhaher** [comment]
> Please try just removing , rolling=true, paging=true from this line.

Done! And it worked.
