### ISSUE TITLE
FR: bookmark categories

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7756]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently, KOReader only supports "Bookmarks" and "Added notes", which are essentially bookmarks with leading comments. However, in some types of literature it is much more useful to have different categories of bookmarks. For example, categories like "To-do" (implement this in real life, fact-check it, etc), "Curiosities" (interesting stories or funny moments), "Inspiration" (motivating thoughts or triggers to create something), "Raw data" (facts, dates, names, which need heavy repetition to be memorized), "Nice to know's" (like "nice to have's"). I am sure this will be very useful for technical literature.

**Describe the solution you'd like**
1) The (easiest) way I see it, is to have user-defined category labels which will be pasted before comments, by new labeled buttons in "Add note" dialog. To make it short, categories above can be shortened to !TODO, !HAHA, !IDEA, !MEM and !HMM; so that they don't take too much of space before actual comments and in the button labels. 
2) Extra helpful thing might be to have superscripts of category number (or the label itself if possible) for highlighted sections in the text itself, so that they are distinguishable from a first glance.
3) Another useful thing might be to have "tabs" in Bookmarks menu, which essentially will show only comments from respective section. E.g. tabs might be "General" (which shows everything as usual) + these five (or how many we would decide) categories. This might be really useful for remembering multiple dates and names.

**Describe alternatives you've considered**
Right now I am just adding these labels manually to my highlights. I haven't extracted these yet via KoHighlights, but I will most probably just sort all the extracted lines in Notepad++. Unlabeled lines will just sort by "Page ..." word, so I could distinguish them from the rest.

**Additional context**
None.

Thank you for your attention!

**Comment by NiLuJe** [comment]
Add it to the pile #5794

**Comment by hius07** [comment]
> Right now I am just adding these labels manually to my highlights. I haven't extracted these yet via KoHighlights, but I will most probably just sort all the extracted lines in Notepad++. Unlabeled lines will just sort by "Page ..." word, so I could distinguish them from the rest.

Does https://github.com/koreader/koreader/pull/8301 (removing Page from the `text` field) break your sorting routine?

**Comment by mergen3107** [comment]
@hius07 
No, it’s OK! 
I can adapt. Those without `Page` will then move after categories with `!` anyway. I also don’t need to have them sorted alphabetically, so it’s fine.
