### ISSUE TITLE
FR: Progress bar - select heading levels for chapter titles to show

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7758]
**Does your feature request involve difficulty completing a task? Please describe.**
A straightforward example of why this might be useful. In Ken Follett's "Pillars of Earth", there are three levels of headings, h1-h3. For example:
**Part I. 1135-1136 (h1)
--> Chapter 1 (h2)
--> --> I (h3)
--> --> II (h3)
--> --> III (h3)
...**
Because h3 level titles are not so meaningful, I turned them off from progress bar ticks and checked the option "Chapter titles from ticks only", which shows only h2-headings (Chapters). However, the most informative heading is in h1, where the years are shown. So to look it up I need to go to ToC.

**Describe the solution you'd like**
As a solution I see a replacement to "Chapter titles from ticks only" with "Chapter titles from ToC depth 1", etc, with the same number of labels as detected for ToC depth. Right now "Chapter titles from ticks only" by default shows only the lowest level heading among selected in ToC depth.

**Describe alternatives you've considered**
Going to ToC. However, if the current chapter title is on different page than its respective h1, I have to go one page backwards. 

**Additional context**
None.

Thank you for your attention!

**Comment by NiLuJe** [comment]
That's already implemented, IIRC?

(Might be tied to Alt ToC, or not?)

Ping @poire-z

**Comment by mergen3107** [comment]
This has been added a long time ago, with tweaks to ToC levels. Selected ToC levels respectively appear on both progress bars.
