### ISSUE TITLE
OTA: Local package creation failure

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#7763]
* KOReader version: v2021-05 and nightlies, e.g. update from 2021-05 to 2021-05-25, to 2021-05-39, to 2021-05-44
* Device: Pocketbook Touch HD3

#### Issue
Since the May update, when I do the OTA update on my Touch HD3, KOReader first tries to read a local package. It displays the message "Preparing local OTA package" at the bottom and when that fails, I get "Failed to update KOReader". When I press retry, only then does it download the OTA package from the download server.

This has happened with all the May nightlies so far and only on the Touch HD3, not on my two Inkpads 3. I don't remember doing anything different with that device. I always update via OTA, not via PC.

#### Steps to reproduce
Turn on WiFi, start OTA update via menu, press "update". 
"Preparing local OTA package" appears at the bottom, at 100% it fails. Error message "Failed to update KOReader", press retry, OTA update downloads package from server and prompts to install.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/6545041/crash.log)

**Comment by NiLuJe** [comment]
Much like in #7581, someone will have to run this manually to see what exactly it's complaining about:

https://github.com/koreader/koreader/blob/dc0d75914801702ee95b6c9aedfd1ef336b0d7e7/frontend/ui/otamanager.lua#L340-L385

i.e. from within koreader's directoty,

`tar --no-recursion -cf ota/koreader.installed.tar -C .. -T ota/package.index`

**Comment by rjd22** [comment]
Is this still an issue with the latest version? Since the wifi fixes OTA became really reliable for me.

**Comment by Frenzie** [comment]
Now that you mention it, it does sound like it might be some curious wifi issue rather than anything about tar or the download. I'll close it for now; please leave a comment to reopen.
