### ISSUE TITLE
Frontlight notification stays on screen until tap

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#7764]
* KOReader version: v2021-05-44 and previous versions
* Device: Pocketbook Inkpad 3

#### Issue
When changing the frontlight or warmth level by gesture (swipe left/right edge), the notification at the top stays on the screen until a tap is done.
I have a second Inkpad 3 which doesn't have this bug, neither does my Pocketbook Touch HD3. Screen settings should be the same on all devices.

#### Steps to reproduce
Swipe left or right edge to change frontlight/warmth level. Notification appears at the top of the screen and stays there until a tap is done.

##### `crash.log` (if applicable)
Buggy version:
[inkbugcrash.log](https://github.com/koreader/koreader/files/6545417/inkbugcrash.log)

Bug-free version from second Inkpad 3:
[crash.log](https://github.com/koreader/koreader/files/6545416/crash.log)

**Comment by NiLuJe** [comment]
Given the discrepancies, shot in the dark: possibly related to the autostandby plugin?

Does it behave with it disabled?

**Comment by NiLuJe** [comment]
The logs appear to give credence to that theory: the affected device is low on charge, which seems to make that plugin antsy.

**Comment by LucyOne** [comment]
I just tested it again with the battery charged to 78%. It worked in the first book. Then I deactivated the auto standby plugin and restarted Koreader with another book. Aaaand.... the bug is back.

**Comment by rjd22** [comment]
Chances are this is fixed with the new inview rendering. If this issue still persists feel free to reopen.

**Comment by NiLuJe** [comment]
See also #9385

**Comment by pazos** [comment]
Closing in favor of #9493
