### ISSUE TITLE
Selecting test pop up window stays on screen after choosing (copy). 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7772]
* KOReader version:latest 5.2021 
* Device:Samsung galaxy Tab A (T-285) 

The pop up window stays on screen after choosing the (copy) option, after choosing (highlight) it disappear normally (logically maybe). 
I think it should disappear after the (copy) option so the user know that the text is copied.

![Screenshot_2021-05-28-23-33-06](https://user-images.githubusercontent.com/70109540/120040041-9366e000-c00e-11eb-856d-be939acc32e7.png)

**Comment by hius07** [comment]
I agree that the popup menu should be closed and the highlight to be cleared after copy.

Besides, some notification might be shown
https://github.com/koreader/koreader/blob/b8d658b922404974ac5acd20a8843e665133d3c3/frontend/ui/widget/inputtext.lua#L149-L151
