### ISSUE TITLE
No Bookmarks/ToC from .djvu file editied on WinDjvu

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7777]
* KOReader version: 2021.05-35 (nightly)
* Device: KPW3 (5.9.7)

#### Issue
I added a lot of bookmarks to use in lieu of ToC in a scientific djvu textbook. I used "Add bookmark" in WinDjvu.
In KOReader, these do not appear neither as ToC nor as Bookmarks. When I do the same with PDF files edited in Foxit Reader, Bookmarks become Chapters no problem. I attach the djvu file and a successful pdf file here for your reference.
[KOReader - djvu and pdf files.zip](https://github.com/koreader/koreader/files/6565990/KOReader.-.djvu.and.pdf.files.zip)

#### Steps to reproduce
I had this book on KOReader. Then I copied it to PC, added Bookmarks and uploaded again to Kindle. Tried to:
- reopen the book as is
- delete and re-upload
- purge .sdr
- Refresh cached book info
...to no avail.
Right after another trial to open the book, KOReader sort of exited by sending me to Kindle menu.

##### `crash.log` (if applicable)
[crashlog.txt](https://github.com/koreader/koreader/files/6565985/crashlog.txt)
I am not sure whether this applies to this issue specifically, but here is the crashlog since I started this whole thing with bookmarks. Curious things are `Wi-Fi successfully restored (after 15 iterations)!` in the beginning and `Bus error` in the end.

Thank you!

**Comment by NiLuJe** [comment]
> `Wi-Fi successfully restored (after 15 iterations)!`

That's because you have "Restore W-iFi on resume" enabled (and that your connectivity sucks ^^).

> `Bus error`

Usually only seen on Kindle when the fuse proxy gets its panties in a bunch. May translate in "lost" writes.

**Comment by NiLuJe** [comment]
As for your actual issue: I have no idea if we actually support DjVu annotations.

**Comment by mergen3107** [comment]
OK, thank you for your reply about the issue! 

Does “lost” writes mean that my Kindle’s storage is starting to fail?

**Comment by Frenzie** [comment]
No, just that the Kindle's software is really bad in this aspect.

**Comment by mergen3107** [comment]
@Frenzie, thanks! :)
However I wonder what triggered `Bus error`. This is the first time I see it in crash log since January 2021 (I don’t know why I don’t have older logs in the crashlog.txt, maybe it is rotated). Also this is my first KOReader crash in about a year IIRC.

**Comment by NiLuJe** [comment]
My best guess would be via SQLite when you played with the cache info refresh.

SQLite heavily relies on a filesystem behaving in a sane way, especially in WAL mode. This.. isn't really the case on Kindle.

**Comment by mergen3107** [comment]
OK, I see!
For now, I just bookmarked page 284 in that djvu file. It is where ToC is located in the book itself. 
Is there a chance to implement something like "Add this bookmark to ToC"? For example, I can manually go through major Chapter pages, bookmark them and add all of them to ToC on KOReader, so they don't get lost among any other bookmarks/notes.

P.S. In Bookmarks menu, long-tapping an a bookmark shows huge empty window labeled "Bookmark details" with three buttons. Is there supposed to be something useful?

**Comment by NiLuJe** [comment]
> 
> P.S. In Bookmarks menu, long-tapping an a bookmark shows huge empty window labeled "Bookmark details" with three buttons. Is there supposed to be something useful?

Notes.

Bookmarks conflate bookmarks/notes/highlights together.

**Comment by mergen3107** [comment]
Ah, I see. Thanks!
However I noticed that this window only shows highlighted text that goes after `Page x`. The note is only shown in the Bookmarks menu. Shouldn't the window show the note too?
