### ISSUE TITLE
Fit "Full" is not remembered as default for new pdf/djvu documents

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7778]
* KOReader version: 2021.05-35 (nightly)
* Device: KPW3 (5.9.7)

#### Issue
Fit "Full" is not remembered as default for new pdf/djvu documents. It always defaults back to Fit "Width".

#### Steps to reproduce
Open a new pdf/djvu file, go to Bottom menu - select Fit "Full" as well as long tap it and confirm to save as default. Open a new pdf/djvu - the default is back on Fit "Width".

I don't think I can see something related to muPDF defaults settings in the [latest commits](https://github.com/koreader/koreader/compare/v2021.05...master), so I didn't try to update to a more recent nightly. Let me know if I should!

Thank you!

**Comment by Frenzie** [comment]
What about https://github.com/koreader/koreader/commit/2067a16fa1daa65c5eab1ea7cb491f74ea5800e1?

**Comment by NiLuJe** [comment]
Yeah, I should have fixed most (if not all) of the inconsistencies in the latest nightlies.

IIRC, -35 would be too old for that.

**Comment by mergen3107** [comment]
Ah, sorry, I missed that one! However, I updated to 42 nightly and the issue is still there. Fit “Width” is default no matter in what new/purge-sdr’ed pdf and djvu files I set Fit “Full” as default

**Comment by NiLuJe** [comment]
Do you happen to have a `zoom_mode` entry in your global config?

**Comment by mergen3107** [comment]
@NiLuJe Where do you I check that?

**Comment by NiLuJe** [comment]
In your `settings.reader.lua` ;).

**Comment by mergen3107** [comment]
@NiLuJe 
Yes, it says `["zoom_mode"] = "contentwidth"` 
I tried to comment it out, restart KOReader, not luck - still defaults to width

**Comment by NiLuJe** [comment]
You can't edit that file with KOReader running ;).

**Comment by NiLuJe** [comment]
#7780 should fix it without you having to touch your settings.

**Comment by mergen3107** [comment]
OK, I've seen your new commit. I'll try the next nightly then.
Thank you!
P.S. Are there any other global settings overrides that I should be aware of? :')

**Comment by NiLuJe** [comment]
Hopefully not...

**Comment by mergen3107** [comment]
I can see on http://build.koreader.rocks/download/nightly/ that the latest nightly was on May 27. Is everything alright?

**Comment by mergen3107** [comment]
I though they are compiled every night 👀

**Comment by NiLuJe** [comment]
They're currently failing because of some weird shenanigans with the new Docker images, c.f., #7775

**Comment by Frenzie** [comment]
@NiLuJe Er, what, no? They were all green.

**Comment by Frenzie** [comment]
@NiLuJe Apparently some builds are *QUIETLY* broken, which is really, really disturbing. If I'd known I'd have looked at that.

![Screenshot_20210603_091639](https://user-images.githubusercontent.com/202757/120603577-7be38900-c44c-11eb-97cd-dc2699ab10ac.png)

However, the vast majority of builds is business as usual. Again, the new Docker images are working perfectly fine, there's very exclusively a busted issue.

**Comment by mergen3107** [comment]
I confirm that the original issue is solved as for nightly -73.
