### ISSUE TITLE
Calibre metadata (including tags) not reflected on device-side for kindle PW4 in places such as "Calibre Metadata Search" or "Book Information"

### ISSUE THREAD

**Issue by komali2** [koreader/koreader#7790]
* KOReader version: koreader-kindlepw2-v2021.05
* Device: Kindle PW4

#### Issue

Calibre Tags (and other metadata) not properly available / displaying on Koreader. 

#### Steps to reproduce

1. Have calibre catalog with, for example, tags. 

![see said tags](https://user-images.githubusercontent.com/8533113/120348042-693d4880-c2c2-11eb-9715-4578867f95a0.png)

2. Ensure metadata, such as tags, is sent to device, by clicking "update cached metadata on device" in calibre. 
3. Disconnect device
4. Start Koreader
5. Long press book, click "Book Information." 
6. Note the lack of all metadata for said book (I can't manage to take a screenshot with a menu open sorry):

![bunk info](https://user-images.githubusercontent.com/8533113/120348659-fe404180-c2c2-11eb-8d59-79f44de6c398.jpg)
7. Go back, long press book, select "refresh cached book information"
8. Repeat step 5. Note no change. 
9. Go back to main screen. Swipe down from top. Select the search tab. Select "Calibre metadata search." Select "Browse Tags." 
10. Note funky tag information that doesn't come close to reflecting your calibre library:

![weird tags](https://user-images.githubusercontent.com/8533113/120349037-5d05bb00-c2c3-11eb-800f-b1fa4ba688f2.jpg)

**Comment by NiLuJe** [comment]
If Calibre isn't baking the metadata inside the file, the only place you'll see a tag is in the Calibre tag search. Any and all metadata view *only* looks at the file itself.

(e.g., *that* is not a bug; also a properly set up Calibre *will* bake most of it in at Send To Device time, provided that's done via a proper driver).

----

Now, the second bit *does* look like broken metadata cache parsing. I can't really think of a way the JSON parser could lead to something like that, but the legacy parser might... So:  how large is your metadata cache file?

**Comment by NiLuJe** [comment]
> also, a properly set up Calibre _will_ bake most of it in at Send To Device time, provided that's done via a proper driver.

e.g., (if you pardon my French, literally ;p):

![meta](https://user-images.githubusercontent.com/111974/120362733-b09bf700-c30b-11eb-85e0-4c8b0fdc7d9b.png)

**Comment by komali2** [comment]
Ah interesting regarding matching the metadata cache. In all fairness I called this a "bug" mostly to learn exactly that sort of thing. I kinda assumed it was stemming from my misunderstanding :P 

I remember when I first threw koreader onto my kindle my tags library was HUGE, which was matched when I turned on calibre for the first time. It's only after a massive tag cleanup (and trying to "push" metadata changes to the kindle, which seems is not the right way to do things) that it got all funky like that. 

So, would you recommend in my case, wiping documents off the kindle, and then re-"send-to-device"ing them from calibre? 

Sorry, what is the metadata cache file called lol? At root of my kindle I've got `driveinfo.calibre` at 301 bytes, `kindle_collections_path_cache.calibre` at 1.7MB, and `metadata.calibre` at 114MB. Under koreader/cache/calibre, I've got `libraries.lua` at 34 bytes. Are any of those what you meant?

**Comment by NiLuJe** [comment]
> `metadata.calibre` at 114MB.

Yup, that's way over the threshold where we switch to best effort DIY parsing ^^. Unless you're willing to debug this yourself, nothing much we can do without having access to said file, though. (Unless @pazos has an idea?).

**Comment by NiLuJe** [comment]
> So, would you recommend in my case, wiping documents off the kindle, and then re-"send-to-device"ing them from calibre?

Depends on what you want to rely on, really.

If you *really* want up-to-date "Book info" popups, then, yeah. If not, not really necessary, the Calibre metadata search will pick 'em up (assuming the parser gets fixed).

**Comment by komali2** [comment]
Mostly I just want to be able to have my books better organized, and tags seemed the way. Like I've got my math books, my comp sci ones, my specific brand of fiction etc, dunno, I'm an organizing fiend :P Lemme take a poke at this metadata file, i'm going in B)

**Comment by komali2** [comment]
Oh, this is just a huge JSON file. Looks like things in here are perfectly intact.

Something I've suspected: that whole "update/extra metadata" function halts (or takes longer than my go-to-idle time?) on any of my books that contain SQL queries or perl code. I've been wondering if code inside them has been parsed and executed. Lemme poke around this json file see if there's anything funky.

**Comment by komali2** [comment]
Struggling to find the parser, any chance you can point me in the right direction?

**Comment by komali2** [comment]
Also, trying out backing up /documents and that metadata, wiping both off the kindle, and re-sending ish to my kindle. WIll report back.

**Comment by pazos** [comment]
@komali2: the parser is in https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/parser.lua

It worked *at least* once. Was written by @WS64 back in the day and worked for him. Then we switched to json, but that causes OOM on devices with little RAM, so we repurposed back the old code for json files that weight more than 30MB. It worked again for the same user, which provided me a copy of his `metadata.calibre` file. It also worked fine with my own library, whose json file was generated by our wireless client.

> Also, trying out backing up /documents and that metadata, wiping both off the kindle, and re-sending ish to my kindle. WIll report back.

Do also wipe `metadata.calibre` and `driveinfo.calibre`. These files will be generated again by calibre when you send your books again. Please report if the new `metadata.calibre` is now parseable.

> (Unless @pazos has an idea?).

@NiLuJe: my idea is still the same: get rid of the manual parser and use https://rapidjson.org/md_doc_sax.html to read from a stream and execute callbacks on defined entries. Sadly lua-rapidjson doesn't support that.

**Comment by komali2** [comment]
Quick update: weirdly, the tags ended up kinda duplicating a little bit. Also, clicking on any of these tags in the tags browser results in Koreader crashing :(


![Tag browser](https://user-images.githubusercontent.com/8533113/120743941-837a5f00-c52c-11eb-8e14-10ffc604645a.jpg)

**Comment by NiLuJe** [comment]
> Quick update: weirdly, the tags ended up kinda duplicating a little bit. Also, clicking on any of these tags in the tags browser results in Koreader crashing :(

Post the crash.log, please ;).

**Comment by komali2** [comment]
Yup sorry, just gathering info. Ok so, `metadata.calibre` at 125.2MB now. 

As for crash.log, not sure if the information is helpful. The timestamps are off, but that might be because I'm in Taiwan, and the timezones are fucky. I see a lot of this, which looks like me repeatedly trying to search tags and then the thing crashing:

```
06/03/21-18:08:05 WARN  invalid cache: fopen: No such file or directory
06/03/21-18:08:34 INFO  calibre info loaded from disk (search) in 28817.944 milliseconds: 1 books
06/03/21-18:08:35 INFO  Failed to serialize calibre metadata cache: cannot serialize table: 0x6b978df8 (not enough memory)
06/03/21-18:08:35 INFO  metadata: 1 books imported from calibre in 30036.611 milliseconds
06/03/21-18:08:37 INFO  search done in 2527.032 milliseconds (tags, case sensitive: false, title: true, authors: true, path: true)
Killed
```

```
06/03/21-18:10:25 WARN  invalid cache: fopen: No such file or directory
06/03/21-18:10:57 INFO  calibre info loaded from disk (search) in 31797.464 milliseconds: 1 books
Killed
```

```
06/03/21-18:12:17 WARN  invalid cache: fopen: No such file or directory
06/03/21-18:12:47 INFO  calibre info loaded from disk (search) in 29612.633 milliseconds: 1 books
06/03/21-18:12:56 INFO  Failed to serialize calibre metadata cache: cannot serialize table: 0x690fa5c8 (not enough memory)
06/03/21-18:12:56 INFO  metadata: 1 books imported from calibre in 38341.714 milliseconds
06/03/21-18:13:06 INFO  search done in 10433.417 milliseconds (tags, case sensitive: false, title: true, authors: true, path: true)
06/03/21-18:13:09 WARN  Polling for input events returned an error: 32 -> Broken pipe
06/03/21-18:13:09 WARN  Polling for input events returned an error: 32 -> Broken pipe
(... polling x 3,000 lines)
Killed
```

```
06/03/21-18:17:42 WARN  invalid cache: fopen: No such file or directory
06/03/21-18:18:10 INFO  calibre info loaded from disk (search) in 27513.318 milliseconds: 1 books
06/03/21-18:18:14 INFO  Failed to serialize calibre metadata cache: cannot serialize table: 0x6a05a080 (not enough memory)
06/03/21-18:18:16 INFO  metadata: 1 books imported from calibre in 33302.729 milliseconds
06/03/21-18:18:32 INFO  search done in 15809.741 milliseconds (tags, case sensitive: false, title: true, authors: true, path: true)
Killed
```

```
06/03/21-20:56:23 WARN  invalid cache: fopen: No such file or directory
06/03/21-20:56:52 INFO  calibre info loaded from disk (search) in 29285.146 milliseconds: 1 books
06/03/21-20:57:01 INFO  Failed to serialize calibre metadata cache: cannot serialize table: 0x6be97048 (not enough memory)
06/03/21-20:57:06 INFO  metadata: 1 books imported from calibre in 42544.126 milliseconds
06/03/21-20:57:08 INFO  search done in 814.202 milliseconds (tags, case sensitive: false, title: true, authors: true, path: true)
(no killed this time)
```

So I'm guessing the thing is just too damn big. Lemme poke around in the serialize function.

**Comment by komali2** [comment]
Ah, I see

```
    if attr.size > MAX_JSON_FILESIZE then
        books, err = parser.parseFile(self.metadata)
    else
        books, err = rapidjson.load(self.metadata)
    end
```
koreader/plugins/calibre.koplugin/metadata.lua :124

**Comment by komali2** [comment]
I still want to look into using the sax JSON parser @pazos mentioned, but for now, this actually did work for me haha

**Comment by komali2** [comment]
![PXL_20210604_065739899](https://user-images.githubusercontent.com/8533113/120760243-85670280-c4d9-11eb-9c37-e4ce573ccde6.jpg)
![PXL_20210604_065731748](https://user-images.githubusercontent.com/8533113/120760251-87c95c80-c4d9-11eb-8cca-15e7e5991bdd.jpg)

**Comment by NiLuJe** [comment]
Yup, those are OOM kills ;p.
