### ISSUE TITLE
Cannot get opds catalog from Calibre if user/pass is set

### ISSUE THREAD

**Issue by hoodslide** [koreader/koreader#7793]
* KOReader version: 2021.05
* Device: Kobo Forma
* Calibre 5.16

#### Issue

Attempting to open Calibre OPDS catalog results in an error msg, "Cannot get catalog. Server response code 400."

If I disable authentication from Calibre and remove user/pass from koreader, it works fine.

I can browse the catalog using the same settings (with authentication) via Moon+ Reader Pro (android) and Marvin (iOS). 

#### Steps to reproduce

Local catalog @ 192.168.1.127 (static internal IP), port 8192, with a user/pass.

##### `crash.log` (if applicable)

I turned on verbose logging via the app, attempted to open Calibre OPDS again, then looked at the crash.log. No new output. Here's Calibre's access log:

```
192.168.1.129 port-35549 - 01/Jun/2021:16:53:58 -0500 "HEAD /opds HTTP/1.1" HTTPStatus.BAD_REQUEST 126
192.168.1.129 port-35550 - 01/Jun/2021:16:53:58 -0500 "GET /opds HTTP/1.1" HTTPStatus.BAD_REQUEST 159
```

**Comment by NiLuJe** [comment]
We don't support DIGEST auth, only BASIC.

**Comment by hoodslide** [comment]
Looks like this is due to koreader not supporting digest authentication. Drat.

https://www.mobileread.com/forums/showthread.php?t=314524

**Comment by Galunid** [comment]
As a workaround
>As a workaround, you can enable basic authentication support:
Calibre -> Preferences -> Sharing over the net -> Advanced tab and set:
Choose the type of authentication userd: basic and restart content server.

From https://github.com/koreader/koreader/issues/3953#issuecomment-420949393

**Comment by NiLuJe** [comment]
Basic + HTTPS should work, FWIW.
