### ISSUE TITLE
Freezes after coming back from sleep

### ISSUE THREAD

**Issue by davidg192** [koreader/koreader#7798]
* KOReader version: v2021.5
* Device: Onyx boox note2 (Android)
* Android Pie

#### Issue
If i put the device to "sleep" ie. pressing the power button or waiting until the screen turns off by itself and then turn the screen back on again Koreader is frozen and has to be force closed. It only happens if I have a book open, if I turn off the screen from the home screen it works fine. Koreader v2021.4 does not have this issue on my device. I only have this issue on my e-ink device, on my android phone there is no issue.
#### Steps to reproduce
Open any book
Press power button to turn off screen
Press it again to turn screen back on
App is frozen
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by pazos** [comment]
Probably resolved. Try last nightly. If the bug still happens please generate and attach a crash.log

**Comment by davidg192** [comment]
You are right, it works in nightly v2021.05-47.
Thank you
