### ISSUE TITLE
Kindle usb connection while Koreader open

### ISSUE THREAD

**Issue by Monirzadeh** [koreader/koreader#7808]
**Does your feature request involve difficulty completing a task?**
if you connect kindle to PC with USB while koreader open, you can't copy file into kindle.
you should exit koreader to copy your files. 

**Describe the solution you'd like**
when you connect koreader to the PC automatic go to 'USB Drive Mode'

**Describe alternatives you've considered**
any other way that calibre can detect memory and mount that without exit koreader

**Comment by NiLuJe** [comment]
Yep, that's a hard "can"t fix", not happening ;).
