### ISSUE TITLE
FR: regex based alternative TOC

### ISSUE THREAD

**Issue by ImChinaNB** [koreader/koreader#7814]
Currently, the alternative TOC is generated by scanning for `<h1>` `<h2>` elements. However, this won't work when it comes to TXT.

I think that an alternative way that matches titles with regex patterns is a good idea. For example, `^Chapter [0-9]+` matches `Chapter 12. Darkside`.

Would really appreciate it if this could be implemented. Thanks for reading :D

**Comment by pazos** [comment]
This FR is a bit overkill. Alternative TOC is a cool tool to fix broken documents. Applying regex patterns is too much. Fix the document elsewhere and then read it here :)
