### ISSUE TITLE
FR: [margin size customize when in auto crop  mode]

### ISSUE THREAD

**Issue by whmzsu** [koreader/koreader#7816]
**Does your feature request involve difficulty completing a task? Please describe.**
When in page auto crop mode , there are three choice of margin size , but some times the margin size is not big enough while choose "large" option.

**Describe the solution you'd like**
So can  there be custom margin size option  while in auto page crop mode  ??

**Comment by Frenzie** [comment]
Duplicate of #7815. (Within 10 minutes? O.o)

**Comment by huronhorn** [comment]
@Frenzie Lol 🤣
