### ISSUE TITLE
Can't build appimage

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#7817]
* KOReader version: v2021.05-73-g27fa19c9_2021-06-06
* Device: Desktop Ubuntu 20.04.2

#### Issue
Can't build appimage, it can't find libbsd.so.0. When I tried installing it it tells me that I have the latest version.
#### Steps to reproduce
Try building an appimage
##### `crash.log` (if applicable)
[image.log](https://github.com/koreader/koreader/files/6610673/image.log)
<details>
  <summary>crash.log</summary>

```
# also copy libbsd.so.0, cf. https://github.com/koreader/koreader/issues/4627
ln -sf /lib/x86_64-linux-gnu/libbsd.so.0 koreader-appimage-x86_64-linux-gnu/koreader/libs/
cd koreader-appimage-x86_64-linux-gnu && pwd && \
	rm -rf tmp && mkdir -p tmp && \
	cp -Lr koreader tmp && \
	rm -rf tmp/koreader/ota && \
	rm -rf tmp/koreader/resources/icons/src && \
	rm -rf tmp/koreader/spec
/home/+*+*+/koreader/koreader-appimage-x86_64-linux-gnu
cp: cannot stat 'koreader/libs/libbsd.so.0': No such file or directory
```
</details>

**Comment by pazos** [comment]
You'll need libbsd-dev

**Comment by Frenzie** [comment]
No, just `libbsd0` is fine (and standard). The only difference between various Ubuntu versions is to what version `/lib/x86_64-linux-gnu/libbsd.so.0` is a symlink. I'm not sure if the AppImage can be successfully built on Ubuntu 20.04 but if not it shouldn't be for that reason.

For example, on Ubuntu 18.04:
```
$ file /lib/x86_64-linux-gnu/libbsd.so.0
/lib/x86_64-linux-gnu/libbsd.so.0: symbolic link to libbsd.so.0.8.2
```

On Ubuntu 21.04:
```
$ file /lib/x86_64-linux-gnu/libbsd.so.0
/lib/x86_64-linux-gnu/libbsd.so.0: symbolic link to libbsd.so.0.11.3
```

**Comment by Frenzie** [comment]
PS Works for me on 21.04, as it did on 20.04 last year (and nothing relevant has changed since). I'm not sure what could be wrong. Is there anything weird in the part of your path you replaced with `+*+*+`?

**Comment by mendelct** [comment]
Nothing weird on the path, however 
`file /lib/x86_64-linux-gnu/libbsd.so.0`
returns
`/lib/x86_64-linux-gnu/libbsd.so.0: cannot open /lib/x86_64-linux-gnu/libbsd.so.0' (No such file or directory)`

**Comment by NiLuJe** [comment]
Stupid question is stupid: is the host actually an x86_64 machine?

Stupider general question: is everything based on Debian's vision of multilib so hellish? That stuff just lives in /usr/lib over here, FWIW (... on a multilib x86 + x86_64 system ^^).

**Comment by mendelct** [comment]
It's running in VMware on a windows 10 box

**Comment by NiLuJe** [comment]
Then, in the spirit of what @pazos asked:

Is the `libbsd0` package actually installed?

**Comment by mendelct** [comment]
Just to make sure tried installing again.
`apt install libbsd0

Reading package lists... Done

Building dependency tree 

Reading state information... Done

libbsd0 is already the newest version (0.10.0-1).

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by Frenzie** [comment]
@NiLuJe 
> Stupider general question: is everything based on Debian's vision of multilib so hellish? That stuff just lives in /usr/lib over here, FWIW (... on a multilib x86_64 + x86 system ^^).

See https://wiki.ubuntu.com/MultiarchSpec and https://err.no/debian/amd64-multiarch-3

I don't find it hellish. ;-)

@mendelct 
> It's running in VMware on a windows 10 box. Running ls on /lib/x86_64-linux-gnu/ gives me a list of files, libbsd.so.0 is not one of them.

What's your output for `uname -m`?

Also:
```
$ dpkg -L libbsd0:amd64
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libbsd.so.0.9.1
/usr/share
/usr/share/doc
/usr/share/doc/libbsd0
/usr/share/doc/libbsd0/changelog.Debian.gz
/usr/share/doc/libbsd0/changelog.gz
/usr/share/doc/libbsd0/copyright
/usr/lib/x86_64-linux-gnu/libbsd.so.0
```
```
$ dpkg -L libbsd0:i386
/.
/usr
/usr/lib
/usr/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu/libbsd.so.0.9.1
/usr/share
/usr/share/doc
/usr/share/doc/libbsd0
/usr/share/doc/libbsd0/changelog.Debian.gz
/usr/share/doc/libbsd0/changelog.gz
/usr/share/doc/libbsd0/copyright
/usr/lib/i386-linux-gnu/libbsd.so.0
```

PS I don't know what you're trying to do exactly, but you could also just comment out that line. libbsd is included pretty much just for Fedora.

**Comment by mendelct** [comment]
uname gives x86_64,

at any rate I commented out the line and it worked fine, thanks.
