### ISSUE TITLE
KOReader crashes on first run on Linux (because of symlink in system font directory)

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#7818]
* KOReader version: v2021.05
* Device: x86_64 / Linux / KDE Desktop Environment

#### Issue
- KOReader crashes on first run after installation from .deb package or when running as AppImage. 
- It creates config directory hierarchy (with all sub directories empty), then dies. 
- My guess from crash log: KOReader doesn't like some font file in my .fonts directory (I have around 300 fonts installed).

I checked my font directory and all fonts have Latin-1 characters as names, no funny letters in name. There are some PDF and TXT files for font licences. Maybe these confuse KOReader.

#### Steps to reproduce
Install .deb or run AppImage directly

<details>
  <summary>Terminal output</summary>

```
---------------------------------------------
launching...
_  _____  ____                _
| |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
| ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
| . \ |_| |  _ <  __/ (_| | (_| |  __/ |
|_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

It's a scroll... It's a codex... It's KOReader!

[*] Current time: 06/08/21-07:43:33
[*] Version: v2021.05

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
06/08/21-07:43:33 INFO  platform thirdparty apps
-> Goldendict (goldendict), role: dict, available: false

Starting SDL in /tmp/.mount_koreadfagE13/
ffi.load: libs/liblodepng.so
06/08/21-07:43:33 WARN  ./ffi/SDL2_0.lua:437: /tmp/.mount_koreadfagE13/libs/libSDL2.so: undefined symbol: SDL_CreateRGBSurfaceWithFormatFrom
06/08/21-07:43:33 INFO  initializing for device AppImage
06/08/21-07:43:33 INFO  framebuffer resolution: {
["w"] = 600,
["h"] = 800,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
06/08/21-07:43:33 INFO  Performing one-time migration for 20191129
06/08/21-07:43:33 INFO  Performing one-time migration for 20200421
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
06/08/21-07:43:33 INFO  /home/user/.config/koreader/cache/fontlist/fontinfo.dat [string "/home/user/.config/koreader/cache/fontlist/fon..."]:1: unexpected symbol near '/' initializing it
./luajit: frontend/util.lua:703: attempt to index local 'attr' (a nil value)
stack traceback:
frontend/util.lua:703: in function 'scan'
frontend/util.lua:712: in function 'findFiles'
frontend/fontlist.lua:141: in function '_readList'
frontend/fontlist.lua:187: in function 'getFontList'
frontend/ui/font.lua:262: in function 'getFace'
frontend/ui/widget/textboxwidget.lua:87: in main chunk
[C]: in function 'require'
frontend/ui/widget/scrolltextwidget.lua:14: in main chunk
[C]: in function 'require'
frontend/ui/widget/infomessage.lua:38: in main chunk
[C]: in function 'require'
frontend/apps/reader/modules/readertypography.lua:4: in main chunk
[C]: in function 'require'
frontend/ui/data/onetime_migration.lua:35: in main chunk
[C]: in function 'require'
./reader.lua:180: in main chunk
[C]: at 0x00405150
```
</details>

**Comment by Frenzie** [comment]
This might be a regression from <https://github.com/koreader/koreader/commit/a62561e81ec084fd12d6cfacd6b26ebde6c7e73f>.

I imagine you have a `koreader/cache`, but do you have a `koreader/cache/fontlist`?

**Comment by offset-torque** [comment]
Yes
> /home/user/.config/koreader/cache/fontlist/

exists but it is empty like the rest. 

I have these directories created (with their sub-directories) until the crash:
>.config/koreader/cache
.config/koreader/clipboard
.config/koreader/data
.config/koreader/history
.config/koreader/ota
.config/koreader/plugins
.config/koreader/screenshots
.config/koreader/settings
.config/koreader/styletweaks

**Comment by Frenzie** [comment]
Could you run the AppImage with `-d`? It'll give a lot more details about the font names and such.

**Comment by offset-torque** [comment]
Both -d and -v arguments gave exactly the same output as in first post. 
I tried with .dpkg installed version too. Output is same. 

But I tried running it as ROOT and it started without problem. I guess this supports my .fonts folder theory ?

By the way running as root is okay for me and this seems like a very exceptional bug. So I totally understand if no one wants to waste time on it. I wrote it as reference so devs know that this bug exists and if any other user experiences it, you would recognize.

**Comment by Frenzie** [comment]
Are there copyrighted fonts in there or is it a collection of free fonts?

**Comment by Frenzie** [comment]
Actually, could you just give me a list of the filenames, that is, the output of `ls` or something? That should be fine regardless of copyright.

**Comment by Frenzie** [comment]
And I reiterate, you're absolutely sure your username is nothing weird?

**Comment by offset-torque** [comment]
> Easier way to check, just rename it to .fonts_bla. ;-)

Tried this. First deleted .config/koreader then run AppImage again. Same result. Apparently problem is not fonts. I am out of ideas.

> And I reiterate, you're absolutely sure your username is nothing weird?

Surely. It is made of just Latin1 characters, no punctutation or diacritics. And obviously KOReader has no problem with it because it can create .config directories under it properly.

**Comment by NiLuJe** [comment]
Nothing strange in there like symlinks or hard links or sparse files?

If you can apply that patch, that should tell us on what exactly it's dying on, and you can then double-check the state of said file ;).

```diff
diff --git a/frontend/util.lua b/frontend/util.lua
index c93084425..8d3580d07 100644
--- a/frontend/util.lua
+++ b/frontend/util.lua
@@ -699,6 +699,7 @@ function util.findFiles(dir, cb)
         if not ok then return end
         for f in iter, dir_obj do
             local path = current.."/"..f
+            print("util.findFiles on", dir, "current is now", current, "f is now", f, "path is now", path)
             local attr = lfs.attributes(path)
             if attr.mode == "directory" then
                 if f ~= "." and f ~= ".." then
```

**Comment by offset-torque** [comment]
Patch applied. Mystery solved. Analysis:

- KOReader tries parsing **~/.local/share/fonts**
- In my system that directory is empty except one link which points to **~/.local/share/font-manager/Library**
- Pointed target doesn't exist. Culprit is [font-manager](http://manpages.ubuntu.com/manpages/bionic/man1/font-manager.1.html) package. I don't remember installing or using this package. It must be a remnant from older installs.
- After deleting link file KOReader happily starts :)

**Solution (just brainstorming, you know better):** Maybe KOReader can ignore non-existent targets gracefully if it finds a link like this ? Or even parse only known font extensions. 

The mentioned **~/.local/share/fonts** directory is not even in my "system-wide font directory list" in **/etc/fonts/fonts.conf**. I think it is there because of **XDG Base Directory specifications**.

Thanks NiLuJe and Frenzie :+1: 

(Should I edit issue title to reflect correct info or close the issue ?)

**Comment by NiLuJe** [comment]
Yeah, we simply need a nil guard here, `lfs.attributes` is just `stat` in disguise, it *follows* symlinks.

**Comment by Frenzie** [comment]
Don't close, edit is fine.
