### ISSUE TITLE
Calibre wireless plugin not working on Remarkable 2

### ISSUE THREAD

**Issue by StefaanVanDooren** [koreader/koreader#7821]
Running KOReader 2021.05 on a Remarkable 2 version 2.7.1.53. Connected to the same network as my Calibre wireless device connection (calibre 192.168.1.100 9090, remarkable 192.168.1.36.) Entered manual settings for the server in KOReader. 
Trying to connect to the server gives "Cannot connect to calibre server".

SSH to the remarkable and running nc 192.168.1.100 9090 gives 
```
836[9, {"passwordChallenge": "", "serverProtocolVersion": 1, "currentLibraryName": "Calibre Bib", "validExtensions": ["lrf", "rar", "zip", "rtf", "lit", "txt", "txtz", "text", "htm", "xhtm", "html", "htmlz", "xhtml", "pdf", "pdb", "updb", "pdr", "prc", "mobi", "azw", "doc", "epub", "fb2", "fbz", "djv", "djvu", "lrx", "cbr", "cbz", "cbc", "oebzip", "rb", "imp", "odt", "chm", "tpz", "azw1", "pml", "pmlz", "mbp", "tan", "snb", "xps", "oxps", "azw4", "book", "zbf", "pobi", "docx", "docm", "md", "textile", "markdown", "ibook", "ibooks", "iba", "azw3", "ps", "kepub", "kfx", "kpf"], "timestampFormat": "dd MMM yyyy", "lastModifiedFormat": "dd MMM yyyy", "canSupportLpathChanges": true, "currentLibraryUUID": "17e4c5b7-25c8-48b1-b920-fbdae5dfa287", "canSupportUpdateBooks": true, "pubdateFormat": "MMM yyyy", "calibre_version": [4, 23, 0]}]reMarkable: ~/ 
```

Any idea what's going wrong?

**Comment by NiLuJe** [comment]
A look at KOReader's crash.log might be helpful (Fair warning, though: I don't recall how verbose the plugin is; and you might want to enable verbose debug logging, too ([Tools] > More tools > Developer options).

**Comment by StefaanVanDooren** [comment]
Without verbose logging

`--- 192.168.1.254 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 10.143/10.143/10.143 ms
06/09/21-07:13:26 INFO  calibre info loaded from disk in 2.738 milliseconds: 0 books. 0 pruned
06/09/21-07:13:26 WARN  connect to endpoint tcp://192.168.1.100:9090
06/09/21-07:13:26 INFO  connected to calibre 192.168.1.100 9090
06/09/21-07:13:36 INFO  disconnect from calibre
`
It seems it connects and then gives the "Cannot connect to calibre server" message....

I'll set verbose logging on and try again

**Comment by StefaanVanDooren** [comment]
Just forget about it....
I noticed I was far behind with my calibre version (4.23), so I updated calibre and it's plugins and everything is working now.
