### ISSUE TITLE
“start with last file” does not work after restarting koreader (kindle touch)

### ISSUE THREAD

**Issue by techmoan** [koreader/koreader#7822]
* KOReader version: v2021.05
* Device: KindleTouch

#### Issue

  it will open history if set “start with history”, or “start with file browser” etc but not last opened file. just remains closed like if koreader hits “exit” instead of “restart”. then of course needs starting all over again: kual > koreader >start koreader...
 its pain in the ass, some pdfs require often restarting cuz of heavy ram memory usage etc so please fix. tnx

**Comment by Frenzie** [comment]
Sidenote, I'm surprised the popular YouTuber's name Techmoan wasn't taken yet on GH.

It sounds like your exit may not be clean, or maybe one of those weird FUSE issues @NiLuJe often mentions?

**Comment by techmoan** [comment]
beats me.. what should I do? plz bear in mind that i'm not programmer, just average linux user

**Comment by Frenzie** [comment]
One thing that could help is decreasing `DGLOBAL_CACHE_FREE_PROPORTION`. See
https://github.com/koreader/koreader/blob/ba070c24de9a755c34caa3174ff843691e31c3fd/defaults.lua#L29-L36

Save something like this in a *separate* file named `defaults.persistent.lua`.
```
-- proportion of system free memory used as global cache
DGLOBAL_CACHE_FREE_PROPORTION = 0.2
```

It's unclear why you'd get an OOM in the first place, especially in 2021.05.

**Comment by NiLuJe** [comment]
Works for me on a PW2, FWIW.

You might want to double-check if you have the metadata auto-save enabled ([Gear] > Document), as the issue might just be that a kill happens before we've updated whatever last_file uses to figure out what the last file actually is.

(Although I seem to remember this happening on book open, so, I smell a rat ^^).

**Comment by techmoan** [comment]
> Works for me on a PW2, FWIW.
> 
> You might want to double-check if you have the metadata auto-save enabled ([Gear] > Document), as the issue might just be that a kill happens before we've updated whatever last_file uses to figure out what the last file actually is.
> 
> (Although I seem to remember this happening on book open, so, I smell a rat ^^).


tried all 4 settings (every 5/15/60min/only on close suspend exit) ...  still nothing..

**Comment by NiLuJe** [comment]
Yeah, my vague memory was correct: it's updated on *open*, by ReaderUI. So, yeah, I'm going to chuck that one down to broken Kindle mess.

**Comment by NiLuJe** [comment]
The launcher should be irrelevant, the FW version might be; but mostly a not-10-year-old storage device would probably be the actual solution ;).

**Comment by Frenzie** [comment]
@pazos Random hijack, but thanks for doing some cleanup. :+1:
