### ISSUE TITLE
ram memory pop-up notification and auto-restart

### ISSUE THREAD

**Issue by techmoan** [koreader/koreader#7823]
older devices have small amount of ram memory and some pdfs require a lot of it. on my device (kindle touch) if ram hits above 100 or so, whole kindle crashes (5 to 15+ minutes needs to boot up again etc). of course, there's in status bar ram-memory reading and when gets close to 100, we can simple restart koreader manually.
 
 but, making improvement with automation would be nice. 
 ie. making option for pop-up notification. when previously user-set value of ram memory is reached - getting pop-up notification with question “you have been reached max value of memory bla bla, do you wanna restart your koreader? yes / no”.
 this could prevent painfully device crashing if we forgot to check memory in time, and it would be more peaceful reading with no need for bullshiting with status bar checking every few minutes. 

 going one step further more, it would be even nicer if this question could be (optionally) bypassed and restarting koreader automatic and opening again same document when previously user-set value of ram memory is reached.

**Comment by Frenzie** [comment]
You didn't specify if you're using the latest version. But please take a look in defaults.lua.

**Comment by techmoan** [comment]
> You didn't specify if you're using the latest version. But please take a look in defaults.lua.


    KOReader version: v2021.05
    Device: KindleTouch

**Comment by hius07** [comment]
If you wish you can try https://github.com/koreader/koreader/pull/7857, if it works as expected.

**Comment by poire-z** [comment]
Provided by #7857.
