### ISSUE TITLE
Wikipedia does not shows tables and references

### ISSUE THREAD

**Issue by Akshaysinghji** [koreader/koreader#7826]
* KOReader version:koreader-kindlepw2-v2021.05-76
* Device:Kindle Voyage

**Comment by poire-z** [comment]
Well, just consider the EPUB as the best result, and the result in KOReader window as a preview.

We can only render plain text (if we want thumbnails) in the KOReader lookup result window - so tables would be a problem.
And the text we get for this preview is given by the Wikipedia API we use (which strips a lot of things, including list items:

https://en.wikipedia.org/w/api.php?action=query&prop=extracts&format=jsonfm&explaintext=&redirects=&titles=SSB (couldn't guess what "SSB" article you were talking about).
 
https://github.com/koreader/koreader/blob/ba070c24de9a755c34caa3174ff843691e31c3fd/frontend/ui/wikipedia.lua#L42-L62


Which is good enough to get some content. When I need more, I save as EPUB.

Not worth the pain getting the full HTML and trying to convert it to text ourselves by keeping/converting as much content as possible, as there's an API on Wikipedia for this (even if it strips out content, but I guess if they do that, there must be a reason... The Wikipedia articles' source content are not all clean and similar :/

**Comment by Akshaysinghji** [comment]
Is there any direct way to show epub, when i press full article

**Comment by poire-z** [comment]
Nothing more direct than taping 5 more times from `Save as EPUB` to "Would you like to read the downloaded article now?" `OK` - which should be bearable compared to the dozens of seconds needed to download and build the EPUB - and the minutes/hours you'll spend reading what you just downloaded.

**Comment by Akshaysinghji** [comment]
Hahahahaha... Good point.. 
Thank you for your help
