### ISSUE TITLE
[Nova 2]: Can't override refresh mode

### ISSUE THREAD

**Issue by roodling** [koreader/koreader#7830]
* KOReader version: v2021.05-77-gdccd49b6_2021-06-09
* Device: nova2

#### Issue
Since the v2020.11 release I am unable to use any other refresh mode than normal on my Onyx nova 2 device when the app is active.

#### Steps to reproduce
1. Launch KOReader and open a document
2. Change refresh setting to either speed, a2 or x mode
4. Observe the mode updating correctly by looking at the screen (verified by the decrease of screen fidelity)
5. Interact with the app, i.e switch page or open the menu
5. Observe the screen flashing and reverting to normal mode (verified by the obvious "black flashes" introduced when selecting text as an example)

Notes
- It does not matter how the screen mode was set; through global setting, through the app optimization menu or selecting a2 mode using the navigation ball.
- I have only tested this on the latest Onyx Boox firmware 3.1.
- When the mode is changed when interacting with KOReader, the "mode icon" in the navigation ball is refreshed to indicate that the device is running on normal mode. The global and app optimization settings are not affected.
- On v2020.10.1 I do not have these issues 

Is this supposed to be expected behavior? I know that v2020-11 introduced improvements to e-ink rendering, for example the app can override the full refresh which is nice, but the "normal mode" is not optimal to read PDFs

Thanks for all the great work!

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/6630139/crash.log)

**Comment by pazos** [comment]
> I know that v2020-11 introduced improvements to e-ink rendering, for example the app can override the full refresh which is nice, but the "normal mode" is not optimal to read PDFs

Could you paste a couple of videos to see the difference on the same PDF? v2020.10 vs 2021.05. 

> Is this supposed to be expected behavior?

It is up to that specific epd driver. In this case  [QualcommEPDController](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt)

On boyues epd update requests don't affect current setting mode (You'll get a full refresh each X pages, but the rest of updates follow system mode).

Pinging @Galunid, who implemented this driver. If he's ok with current behaviour I'm afraid we won't revert back to system defaults, but a PR to improve the driver is very welcome :+1

**Comment by roodling** [comment]
Thanks @pazos 

> Could you paste a couple of videos to see the difference on the same PDF? v2020.10 vs 2021.05.

Absolutely, this one is from 2020.10.1:
https://user-images.githubusercontent.com/4501110/121532167-63044600-c9ff-11eb-9292-87d33fb25591.mp4

And this one is from v2021.05:
https://user-images.githubusercontent.com/4501110/121532340-8a5b1300-c9ff-11eb-942c-cf3a18195be9.mp4

> On boyues epd update requests don't affect current setting mode (You'll get a full refresh each X pages, but the rest of updates follow system mode).

Ok, that behavior sounds correct.

> Pinging @Galunid, who implemented this driver. If he's ok with current behaviour I'm afraid we won't revert back to system defaults, but a PR to improve the driver is very welcome :+1

Got it, let's see what he thinks.

**Comment by Galunid** [comment]
It works as intended. The EPD driver takes over "onyx refresh settings" and lets KOReader handle it, like it would on other devices. [This part](https://github.com/koreader/android-luajit-launcher/blob/56e4fb5190eba52bcfb44f264b4454d725cd5021/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt#L46-L49) is responsible for this, you can delete those lines and build the app yourself. You can learn how [here](https://github.com/koreader/koreader#development). This will restore the behavior to how it was in v2020.11. So far you're the first person to complain about that since it was introduced ~7 months ago. Is there a reason you have to use KOReader for PDFs specifically? NeoReader seems a bit better when it comes to PDF and you get the advantage of notetaking, granted I rarely read PDFs.

**Comment by roodling** [comment]
> It works as intended. The EPD driver takes over "onyx refresh settings" and lets KOReader handle it, like it would on other devices. [This part](https://github.com/koreader/android-luajit-launcher/blob/56e4fb5190eba52bcfb44f264b4454d725cd5021/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt#L46-L49) is responsible for this, you can delete those lines and build the app yourself. You can learn how [here](https://github.com/koreader/koreader#development). This will restore the behavior to how it was in v2020.11. So far you're the first person to complain about that since it was introduced ~7 months ago. Is there a reason you have to use KOReader for PDFs specifically? NeoReader seems a bit better when it comes to PDF and you get the advantage of notetaking, granted I rarely read PDFs.

Appreciate the explanation @Galunid. I might give the local build a go, thanks for the pointers. I guess a feature toggle through settings to opt out of this behavior would not be worth it? If, as you say, I am the only one who has reported this since the feature was added maybe I am part of a minority here? Note that I haven't used my reader in a while so that's why I noticed this now and not before.
As for reading PDFs in KOReader, it's mostly because I like to manage everything in the same package and I think NeoReader has worse UI. This given that I rarely take notes. I actually also prefer to read regular books in speed mode as well because I like the look and feel of it.

**Comment by Galunid** [comment]
@roodling I had some spare time, so I builid one for you, it should work, but **you have to uninstall whatever version you have installed right now**, because it's signed with my key. When you try to update it in the future you'll have to uninstall it too. [koreader-android-arm-v2021.05-77-gdccd49b_2021-06-09.apk](https://gofile.io/d/8Fh14Q), which is more or less today's nightly
