### ISSUE TITLE
FR: [Calculator plugin]

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#7831]
**A calculator is handy in KOReader**

Would it be of interest for others if I publish my calculator plugin? 
It is a fully featured calculator, which can also use symbolic variables (also with Greek letters), variables can be loaded from a 
file, output may be stored to a file. More than 28 operators (priority like in c++), 25 functions. 

The plugin works fine, but there is quite some work on the keyboard layout to do.

The plugin is ready now: Please see https://github.com/koreader/contrib/tree/main/calculator.koplugin

Some impressions:

https://user-images.githubusercontent.com/36999612/121534189-49fc9480-ca01-11eb-99f1-dd541947caf1.mp4

https://user-images.githubusercontent.com/36999612/121534204-4e28b200-ca01-11eb-8fa8-e9a1a648c06e.mp4

**Comment by hius07** [comment]
I like it very much!

**Comment by Frenzie** [comment]
Btw, we have https://github.com/koreader/contrib now.

**Comment by mergen3107** [comment]
Looks awesome! Currently I use Galculator on my Kindle, which is outside of KOReader. So this plugin will be really handy! :)

**Comment by Galunid** [comment]
Seems really cool, https://github.com/koreader/contrib would definitely appreciate that!

**Comment by zwim** [comment]
I will do it in `contrib`. 
But here the question arises: How can I insert the layout for the virtual keyboard from contrib? Is it right to do two PRs, one for the keyboard layout in koreader/koreader and the plugin in koreader/contrib?

**Comment by Frenzie** [comment]
That's probably fine, but it might need some further consideration. For example, with regard to the keyboard selection menu and popup.

**Comment by zwim** [comment]
Right now I have just added the calculator layout to:
```
    lang_to_keyboard_layout = {
        ar_AA = "ar_AA_keyboard",
        bg_BG = "bg_keyboard",
        de = "de_keyboard",
        el = "el_keyboard",
        en = "en_keyboard",
        es = "es_keyboard",
        fa = "fa_keyboard",
        fr = "fr_keyboard",
        he = "he_keyboard",
        ja = "ja_keyboard",
        ka = "ka_keyboard",
        pl = "pl_keyboard",
        pt_BR = "pt_keyboard",
        ro = "ro_keyboard",
        ko_KR = "ko_KR_keyboard",
        ru = "ru_keyboard",
        tr = "tr_keyboard",
        Calculator = "calc_keyboard", -- Calculator is the first entry
        Σ—Calculator = "calc_keyboard", -- Calculator is the last entry :)
    },
}
```
This would mean that you can select the calculator keyboard from everywhere. Would this be a problem? It would not make much sense to use a calc keyboard in other contexts. But that's in the responsibility of the user. Anyway it might be handy to use a non-calc keyboard in calculator.

On calculator close the previous keyboard layout is restored anyway. So the only drawback would be, that a user selects an unwanted keyboard (but that is similar to almost all layouts:)

Do you have an other suggestion?

**Comment by poire-z** [comment]
Ideally, your calculator keyboard layout should be contained in the plugin (we shouldn't have bits here and there).
But, in a koreader PR, you could add generic hooks to the core virtualkeyboard.lua code so it can accept external/non-core layouts (so, tomorrow someone can create a chemical mollecular compositor plugin with a dedicated keyboard full of atomic element symbols, even if I dont know if such a thing make sense :/)

**Comment by Frenzie** [comment]
Yes, that's what I meant.

**Comment by Frenzie** [comment]
The alternative would be to hide it. It's different from a regular keyboard since this one is presumably 90% broken out of context. ;-)

PS The names are translated.

**Comment by Zeyadas** [comment]
> Would it be of interest for others if I publish my calculator plugin?

Where do I sign up?

**Comment by zwim** [comment]
I solved the keyboard-layout problem now. There is no need to do a PR in KOReader :)

**Comment by zwim** [comment]
Calculator is ready now:
https://github.com/koreader/contrib/tree/main/calculator.koplugin or 
https://github.com/zwim/calculator.koplugin

Have fun with it :)

**Comment by poire-z** [comment]
Nice example of a complex plugin, with its own update mechanism !

**Comment by NiLuJe** [comment]
@zwim: You have a few `prints` left in https://github.com/zwim/calculator.koplugin/blob/master/ui/data/keyboardlayouts/calc_keyboard.lua ;)

**Comment by Frenzie** [comment]
@poire-z 

> with its own update mechanism

What? Where? :laughing:

**Comment by zwim** [comment]
No, no mechanism, its just a notification.

**Comment by Zeyadas** [comment]
> Calculator is ready now:
> https://github.com/koreader/contrib/tree/main/calculator.koplugin or
> https://github.com/zwim/calculator.koplugin
> 
> Have fun with it :)

Didn't work on android, installed it as described in https://github.com/zwim/calculator.koplugin/releases
Downloaded the file (.zip) extracted it to my phone memory (not SD card) koreader/plugins file, restarted koreader and didn't find it in plugins management..

**Comment by zwim** [comment]
@Zeyadas, thank you. I will make the installation instructions more detailed.

The plugin is designed as user plugin. It needs to live in `DataStorage:getDataDir()../plugins/calculator.koplugin` folder. On Android this most probably is `/sdcard/koreader/plugins/`.
One drawback of a user plugin is, that KOReader doesn't ship it automatically and on a reinstallation a user plugin gets deleted (if it is stored in `/data/data/org.koreader.launcher/...`). Therefore, I don't have designed it to work on the app folder in internal memory.
If it is put in `DataStorage:getDataDir()../plugins/calculator.koplugin` it will not be deleted on a KOReader update and you have access to it, when you connect the device over USB with your PC.

**Comment by pazos** [comment]
@zwim @Zeyadas: it works fine with current instructions:

![calc](https://user-images.githubusercontent.com/975883/121809957-32224c00-cc5f-11eb-9f2a-f2d796092278.png)

Maybe @Zeyadas uncompressed the zip directly inside `/sdcard/koreader/plugins`. It could help to new users if user plugins contain their relative path inside the zip (ie: the zip contains `calculator.koplugin` with all its contents inside.

**Comment by mergen3107** [comment]
@zwim 
Thank you for such a great calculator! 
I’ve noticed a few typos:
- on your main page, it says to unpack it to koreader/, however it should be to koreader/plugins/
- 3>4 in the examples should be false. 

I also have a suggestion for functions: I think after you hit a button with function, it should also add opening parenthesis, like `sin(`

**Comment by zwim** [comment]
>     * on your main page, it says to unpack it to koreader/, however it should be to koreader/plugins/ 
>     * 3>4 in the examples should be false.

Yes to both, thanks. 

> 
> I also have a suggestion for functions: I think after you hit a button with function, it should also add opening parenthesis, like `sin(`

I had that in the beginning. But if I put 'asin(' directly on the button the buttons look odd. So I decided to drop the `(`. I did not figure out, how to show a different button symbol to what the button delivers. Maybe I get some hint/help here?

But anyway if you enter something like `sin5pi` the preparser recognizes it as `sin(5*pi)` but this does not work on two functions like `asinsin4` as this could be a very sophisticated variable name :)

**Comment by Zeyadas** [comment]
> Maybe @Zeyadas uncompressed the zip directly inside `/sdcard/koreader/plugins`.

That's exactly what I did.
And I've tried it on another android device the same thing happened, didn't find it in plugins management.

**Comment by Zeyadas** [comment]
![Screenshot_20210613-212933](https://user-images.githubusercontent.com/70109540/121818257-b3450780-cc8e-11eb-88f8-fd887f71841f.png)

**Comment by Frenzie** [comment]
@Zeyadas It should be in a directory, so something like `/sdcard/koreader/plugins/calculator.koplugin`. Not the files directly in `/sdcard/koreader/plugins`.

**Comment by Zeyadas** [comment]
I created a new file named calculator.koplugin extracted the zip file in it and restarted koreader..
Calculator appeared in the plugins management and its (activated), now when selecting the calculator nothing happens.
![Screenshot_20210613-222202](https://user-images.githubusercontent.com/70109540/121819455-d4f5bd00-cc95-11eb-9f12-cfb60de8d4d3.png)

**Comment by Zeyadas** [comment]
Maybe I'm doing something wrong or I just don't understand the process..

**Comment by zwim** [comment]
@Zeyadas Thank you for testing. We will get it!
I have updated the installation instructions on https://github.com/zwim/calculator.koplugin/releases
Have you seen them?
Did you try the release 0.9.1. In that I have a folder named calculator.koplugin.

As a short test: You must have a file '/sdcard/koreader/plugins/calculator.koplugin/main.lua
if not something went wrong (bad instructions).

@Frenzie Thank you for your help (here and elsewhere )

**Comment by zwim** [comment]
Maybe this is a leftover from your past experiments.
Please delete '/data/data/org.koreader.launcher/files/plugus/calculatator.koplugin. Restart KOReader

**Comment by Zeyadas** [comment]
> Maybe this is a leftover from your past experiments.
> Please delete '/data/data/org.koreader.launcher/files/plugins/calculatator.koplugin'. Restart KOReader

Did that and the above, sorry didn't work on both my android devices, 
Samsung galaxy Tab A (T-285) with 5.1.1 android version and Samsung galaxy grand prime plus with 6.0.1 android version.

**Comment by zwim** [comment]
@Frenzie   How can I use gettext for translations in my plugin? I try to use unicode icons to avoid this, but  in text like cancle or save i dont want to use symbols as koreaser itself also does not use symbols.

**Comment by Frenzie** [comment]
I don't think that's currently a supported use case but even if not that
shouldn't be too difficult to add. However, your example doesn't really
make sense to me? Cancel and save are standard strings, as you said.

**Comment by zwim** [comment]
@Zeyadas 
If it is possible for you, can you uninstall koreader and delete /sdcard/koreader (make a backup first for, your settings!)
Then install koreader again. Copy/unpack the calculator to /sdcard/koreader/plugins/
Start koreader ...

**Comment by zwim** [comment]
@Frenzie I have strings like Angle which dont get translated, but Cancle is. 
If you use the plugin this looks strange 'Abbrechen' 'Speichern' 'Scientific'

**Comment by Zeyadas** [comment]
> @Zeyadas
> If it is possible for you, can you uninstall koreader and delete /sdcard/koreader (make a backup first for, your settings!)
> Then install koreader again. Copy/unpack the calculator to /sdcard/koreader/plugins/
> Start koreader ...

Did it.. And it didn't work either. 
![Screenshot_20210613-230651](https://user-images.githubusercontent.com/70109540/121820539-138e7600-cc9c-11eb-9394-8112e6c70456.png)

**Comment by zwim** [comment]
@Frenzie Would it be an option (hack) to add my strings in a file of the koreader repository (maybe contributedstrings.lua in data ) to get the translations work?

**Comment by zwim** [comment]
@Zeyadas Can you give me a logcat or better a  './kodev log android' of your device?

**Comment by Frenzie** [comment]
@zwim Hold on, let's not jump to ugly workarounds too quickly. ;-) (But yes, it's an option.)

**Comment by Zeyadas** [comment]
I would.. But I have no idea what are you talking about.. I'm a civil engineer with no background of programming so please be patient describing how to do that step by step.

**Comment by zwim** [comment]
@Zeyadas Absolute no problem!! I will help you, we can  :)

Tomorow I have a tough day so lets close it for now with some questions, so I can help you.
Do you now what adb is?
Are you working on Linux or Windows?

**Comment by zwim** [comment]
@Zeyadas A last reqest today. Can ou open an issue on 
 https://github.com/zwim/calculator.koplugin/issues this would be easier for me to follow.

**Comment by zwim** [comment]
> I created a new file named calculator.koplugin extracted the zip file in it and restarted koreader.
 
Do you mean file or folder?

**Comment by Zeyadas** [comment]
> Do you now what adb is?

No, am just a regular KOReader user don't know anything but installing and uninstallig the apps

> Are you working on Linux or Windows?

Also no, I don't have a laptop, lost it years ago because of the war here (I live in Northern Syria). 

> Can ou open an issue on
https://github.com/zwim/calculator.koplugin/issues

Sure I'll do that, 

> Do you mean file or folder?

A folder where I unzipped the files in it.
