### ISSUE TITLE
Auto scroll option. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7832]
Years ago, before tablet phones or e-ink readers was common I was reading on my laptop using Adobe acrobat reader, I remember using the auto scroll while reading pdfs and I could control the scrolling speed, so I was thinking about adding this feature to KOReader. 
I'm aware it wouldn't work well for e-ink screens but will be perfect for LCD screens.

**Comment by NiLuJe** [comment]
There's an auto-turn plugin already. No idea whether it behaves in continuous mode, though.

**Comment by poire-z** [comment]
It works ;) You need to long-press on the menu item added to the first top menu panel to set the distance - default = 1 = 1 page, but you can set it to 0.1. Set a delay with a tap of 1s, and you get a bit of what's requested. Might be tweaked to get it more granular if needed.

**Comment by Zeyadas** [comment]
> There's an auto-turn plugin already.

Where??
