### ISSUE TITLE
Bluetooth icon on status bar. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#7841]
Can you please add a Bluetooth icon on the bottom status bar that shown as the Wi-Fi icon (visible when Bluetooth is on). 
I'm using an android tablet..

**Comment by pazos** [comment]
Nope. Not useful at all in most platforms. 

It is a [feature creep](https://en.m.wikipedia.org/wiki/Feature_creep) example.

**Comment by NiLuJe** [comment]
Especially since *we* don't do anything with bluetooth ;).
