### ISSUE TITLE
"Statistics calendar view" doesn't appear in file browser

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7844]
* KOReader version: koreader-pocketbook-v2021.05-83-g6b31b160_2021-06-12
* Device: Touch Lux 5 (PB628)

While in the file browser, I can't find the choice "Statistics calendar view" in upper menu. The gesture I have set for it doesn't work either. I think there was this choice in the file browser upper menu.
Could it come back, please?

**Comment by NiLuJe** [comment]
The whole `Statistics` plugin's menu is missing from the FM since a few days/weeks, I'm not quite sure why...

**Comment by NiLuJe** [comment]
Ah, obviously, the answer is "[Because I broke it](https://github.com/koreader/koreader/pull/7723)". :D
