### ISSUE TITLE
FR: Make “Translate” less confusing

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7851]
**Does your feature request involve difficulty completing a task? Please describe.**
When using dictionary’s edit query function, “Translate” button name is a little confusing. 
1) I actually wanted to look up a highlighted word in the dictionaries. It didn’t find specific word, so I edited the text, then in rush tapped “Translate”. It searched in Google (right?) Translate. 
2) The actual entered query is not displayed in the Google Translate window. So it took me a while to understand that this is not a usual dictionary lookup window. 
3) After I closed this window, my manually entered query was lost and I had to type it again. 

**Describe the solution you'd like**
1) Replace “Translate” with something more specific like “Translate (Online)”, or “Google Translate”, so it is clear that this is not a local lookup. 
2) Show the actual query in the Translate window as it is done in local lookups right now, along with “From:” and “To:” for languages used. Best scenario would have these “From:” and “To:” selectable on the spot, so at least I could select languages and get the translation I needed in the first place. I know I can select these in the top menu, but I wasn’t prepared for such situation beforehand. Moreover, these settings a global and apply to any open document (whether from History or a new one), whereas I read books at least in three languages. 
3) Allow users to reuse manually entered text for other manipulations. E.g. I wanted to lookup in the local dictionaries after my mistake, but I had to re-type the query again. 

Thank you for your attention!

**Comment by hius07** [comment]
> 3\. Allow users to reuse manually entered text for other manipulations

Will it help if the input is automatically copied to the clipboard upon pressing Translate?

**Comment by mergen3107** [comment]
@hius07
Yes, might help!

**Comment by hius07** [comment]
> 2\. The actual entered query is not displayed in the Google Translate window.

Isn't it near the ▣ icon?

**Comment by mergen3107** [comment]
@hius07,
Ah, my bad! Indeed, there it is
