### ISSUE TITLE
KOReader on Kobo Libra H20 freezes with error "unable to allocate memory..."

### ISSUE THREAD

**Issue by huronhorn** [koreader/koreader#7859]
* KOReader version: Latest beta
* Device: Kobo Libra H2O

#### Issue
hi everyone,
i use koreader to read pdf on my kobo libra h20, and when i read this pdf (file attached) with continuous page and auto crop enable, it crashes (i think its around page 5 or 6). I already play around with DHINTCOUNT; DGLOBAL_CACHE_FREE_PROPORTION; and DGLOBAL_CACHE_SIZE_MAXIMUM, but it yields no luck. Anyway, this doesnt happen with my android phone, is it because the ram? 

any help would be much appreciated 😃
thanks in advance

pdf file:
[test.pdf](https://github.com/koreader/koreader/files/6666208/test.pdf)

#### Steps to reproduce
open pdf file  -> auto crop and continuous mode  ->  when hit pages 5 or 6 koreader freezes
 
##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/6666206/crash.log)

**Comment by NiLuJe** [comment]
Possibly super-high resolution images? Those are allocs of ~100MB, which is *a lot* for a single grayscale pixmap.

**Comment by huronhorn** [comment]
@NiLuJe that might be the case, but when i read the rest of the pdf this problem didnt occur. I think its because koreader in continuous crop mode did something weird when it faces a full page blank? (in the test pdf crash happened at page 5/6, while page 7 in the test pdf is a full page blank) because it didn't crash when on no crop full page mode.

Because it happened again when im on other pdf, so i tried to manually remove all the blank pages, and koreader works without problem.

**Comment by Frenzie** [comment]
Nothing strange happens on my H2O.

> I think its because koreader in continuous crop mode did something weird when it faces a full page blank?

Weird how? Note that it contains a full-page images as a watermark. As @NiLuJe said that can take quite a bit of memory, though I'd think the 512 MB should be (just barely) sufficient.

```
06/16/21-20:40:34 INFO  setting zoom mode to contentwidth

[1m[31mCannot allocate enough memory for function bmp_alloc.[0m[37m
    [1m[31m(Needed 92,864,500 bytes.)[0m[37m

    [1m[31mProgram terminated.[0m[37m

!!!!
```

**Comment by huronhorn** [comment]
@poire-z by weird i mean unexpected. so, if its because full images watermark, anything i can do (in the koreader settings or in the pdf itself) to make this issue disappear? the only thing worked for me is to manually remove all the watermarked-blank pages.


> Nothing strange happens on my H2O.

do you test the pdf on your kobo H2O (libra, aura)? is it working fine for you?

**Comment by Frenzie** [comment]
> do you test the pdf on your kobo H2O (libra, aura)? is it working fine for you?

That's what I said. ;-)

> weird i mean unexpected. so, if its because full images watermark, anything i can do (in the koreader settings or in the pdf itself) to make this issue disappear? the only thing worked for me is to manually remove all the watermarked-blank pages.

It's not doing anything unexpected. It's simply allocating 100 MB for the image.

**Comment by huronhorn** [comment]
@Frenzie do you change any of the settings on your kobo? because on my device, generally if there is a watermarked blank pages would be generate this same issue (with continuous and auto crop on)

**Comment by mergen3107** [comment]
I tried this `test.pdf` on Kindle PW3. It definitely hiccups on pages with watermarks, however does not crash.
If I enable Dewatermark, then it crashes. @huronhorn do you by chance have it enabled by default?
Strangely, crash.log did not register this crash.

**Comment by Frenzie** [comment]
@mergen3107 Good call. That's a reliable to make it slow and more memory hungry, and I can also reproduce the same crash that way.

**Comment by Frenzie** [comment]
@huronhorn I suspect you're only seeing it "hiccup" there because it's the end of the chapter and the BAB I/II/III pages are tiny too. So you've got 3 or 4 pages to render all at once. I'm not sure if the preload's intelligent enough to deal with that.

**Comment by huronhorn** [comment]
@Frenzie i presume because of this too, so i change dhintcount value to 5 (i dont know if it made any difference). But if i didnt really skipping over pages (i.e  i "read" the page) this hiccup problem is really minor.

**Comment by mergen3107** [comment]
@huronhorn 
I tried to optimize the file with Foxit Phantom PDF, through Advanced Optimization with these settings:
![pdf_optimizer](https://user-images.githubusercontent.com/6279855/122347739-59577280-cf18-11eb-9eca-963c4766e979.png)

I runs noticeably smoother without Dewatermark, however, still crash with it on.
You might probably want to optimize your PDFs this way.

**Comment by Frenzie** [comment]
You could also try it as a DjVu instead. That being said, on this particular document the difference may be negligible (but I haven't checked).
[test.djvu.zip](https://github.com/koreader/koreader/files/6668106/test.djvu.zip)
