### ISSUE TITLE
FR: automatically scan available OCR datafiles for PDF/djvu documents

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7860]
**Does your feature request involve difficulty completing a task? Please describe.**
I'd like to use OCR with books in Russian and Kazakh. Tesseract data is available from [here](https://github.com/tesseract-ocr/tessdata). Currently there are only English and Chinese available to choose in Bottom menu - Cog - Document Language.

**Describe the solution you'd like**
The easiest solution I could think of is to implement the three-dot button where use can manually type, for example, `rus` or `kaz`, so that the OCR engine will look for `rus.traineddata` or `kaz.traineddata`, respectively. 

**Describe alternatives you've considered**
Main issue is that highlights in Kazakh books have no words in Bookmarks list. Highlighting works, but it is unknown which highlight is this unless you open it. 

Example: [book](https://github.com/koreader/koreader/files/6655187/-.zip)

**Additional context**
Another issue related to this is that I cannot use at least existing words in the book for a fuzzy search. As a workaround I just go straight to the dictionary. However, the dictionary windows cannot be moved, sometimes blocking the words I am about to look up, so I have to memorize them before opening dictionary lookup. 

Thank you!

**Comment by Frenzie** [comment]
Pssht. ;-)
https://github.com/koreader/koreader/blob/e4a333a9805a1668860f0a5d134772e21e7904fb/defaults.lua#L115-L118

**Comment by mergen3107** [comment]
So I just renamed `kaz.traineddata` to 'eng.traineddata' and it works! Quality depends on scan, of course, but at least some words are picked up.
![Reader_2021-06-17_014319](https://user-images.githubusercontent.com/6279855/122338414-a8e47100-cf0d-11eb-9314-edc4da284ff3.png)

Although, even such highlights have non text in Bookmarks menu. So I guess it isn't related to OCR?

**Comment by Frenzie** [comment]
Sorry, what are you referring to exactly?

**Comment by mergen3107** [comment]
@Frenzie 
Thank you! :) 
So I can set these in `defaults.persistent.lua`, right? To survive through KOReader updates.
However, I am a little confused. I have both `defaults.lua` and `defaults.persistent.lua`, however the persistent one quite old. I thought persistent is overwritten any time I long tap a setting to make it default, which I was making quite a lot recently.

**Comment by mergen3107** [comment]
> Sorry, what are you referring to exactly?

So if I highlight the same word I used in the look up:
![Reader_2021-06-17_015114](https://user-images.githubusercontent.com/6279855/122339164-ba7a4880-cf0e-11eb-9f55-93b2630f7abd.png)

it has no text in Bookmarks menu
![Reader_2021-06-17_015130](https://user-images.githubusercontent.com/6279855/122339165-ba7a4880-cf0e-11eb-866c-8707f63b0391.png)

**Comment by Frenzie** [comment]
No, such GUI settings are generally stored in `settings.reader.lua`. `defaults.persistent.lua` is mostly for advanced tweaks not (easily) accessible through the GUI, and a few more sort of early implementation hacks like this one for OCR.

**Comment by Frenzie** [comment]
> it has no text in Bookmarks menu

Could you share the metadata.lua file from the .sdr folder?

**Comment by mergen3107** [comment]
@Frenzie 
OK!

Here you are: 
[Қаржаубай Омарұлы - Ақтөс.sdr.zip](https://github.com/koreader/koreader/files/6667742/-.sdr.zip)

**Comment by Frenzie** [comment]
Indeed, there's no text in there. `["notes"] = "",`

You say this only happens for you with Cyrillic?

**Comment by mergen3107** [comment]
Highlights work with some Cyrillic books. For example, [Д. А. Франк-Каменецкий - Лекции по физике плазмы.zip](https://github.com/koreader/koreader/files/6667845/-.-.zip).
However, all the words are blending into one, but I guess that's because of improper text layer applied on djvu.

![Reader_2021-06-17_021826](https://user-images.githubusercontent.com/6279855/122342382-90c32080-cf12-11eb-8f89-0269469d6036.png)

![Reader_2021-06-17_021847](https://user-images.githubusercontent.com/6279855/122342386-915bb700-cf12-11eb-8825-14b9d502dc1c.png)
[Д. А. Франк-Каменецкий - Лекции по физике плазмы.sdr.zip](https://github.com/koreader/koreader/files/6667834/-.-.sdr.zip)

**Comment by mergen3107** [comment]
By the way, what difference `Forced OCR` makes?

**Comment by Frenzie** [comment]
Normally OCR is only used if there's no text layer. That setting should ignore the text layer.

**Comment by mergen3107** [comment]
@Frenzie 
Thank you! :)

**Comment by mergen3107** [comment]
One more OCR question, please :D
I remember from somewhere that KOReader wants tessdata for tesseract version of at least 3.04. Does that mean it will work with ver. 4.00? 
I just noticed that the link I provided in the OP is has 4.00 files on main page, which I used - and they work.

**Comment by Frenzie** [comment]
We use Tesseract version 3 as mentioned in https://github.com/koreader/koreader/wiki/Dictionary-support#dictionary-lookups-in-scanned-pages

I think that in principle all osd and equ files should work on all versions of Tesseract. As Tesseract phrases it, "osd is compatible with version 3.01 and up, and equ is compatible with version 3.02 and up." But I'd expect the outcome to be slightly suboptimal when the version isn't matched. That is, just because the data format is compatible doesn't mean the data in there targeting 4.0 will also yield better results on 3.0.

On the flip side, chances are you wouldn't notice any difference unless you examined results on over a thousand words.

**Comment by mergen3107** [comment]
@Frenzie 
Thank you so much! 
I'll probably stick to 3.04 just for better compatibility :D

Should I add to Wiki that we also need to tweak the `defaults.lua` in order for these files to work?

**Comment by mergen3107** [comment]
Also, is only *.traineddata file enough? What advantage do cube files provide?

**Comment by mergen3107** [comment]
On the issue of empty-titled highlights, I found another strange thing.

1) So if long-tap a word for the first time as I did in the screenshot above, it picks up the word alright and looks it up.

2) Now, if I highlight it, then press the highlighted word, then go to `...` - `Dictionary` it does not work. I guess that's because it pastes blank to dictionary query. 

So why does it fail to save the recognized word then? Miscommunication between dict look up and highlight saving?

**Comment by mergen3107** [comment]
> doesn't mean the data in there targeting 4.0 will also yield better results on 3.0
I can confirm that 3.04 works significantly better on KOReader. 4.0 Was recognizing way too strange patterns from simple words. 3.04 at least find something similar.

**Comment by Frenzie** [comment]
> Should I add to Wiki that we also need to tweak the defaults.lua in order for these files to work?

Yes, that should be useful. :-)

**Comment by Frenzie** [comment]
> Also, is only *.traineddata file enough? What advantage do cube files provide?

I believe cube is slower but better, or something along those lines. Also it's required for Arabic and Hindi. But other than your basic Latin alphabet languages (Dutch, English, French) I've never done much with OCR. I've merely written some scripts that use Tesseract to apply an OCR text layer to documents *just because*. That is, it takes the script a few seconds more and it adds some (imperfect) searchability, so there's almost no disadvantage to doing it.

**Comment by mergen3107** [comment]
@Frenzie 
Thank you for detailed explanation! :) 
I updated the Wiki
