### ISSUE TITLE
FR: RegEx and Wildcards in Fulltext search

### ISSUE THREAD

**Issue by francwalter** [koreader/koreader#7862]
Hallo

The Fulltext search is very plain, there is no setting at all. I can search only for exact matches.

I would like to get at least wildcards as "*" (for any characters hit) and "?" (for exactly one char.).
Better would be to be able to use RegEx, at least the simple set (without lookarounds etc.).

I think the search could have a setting (e.g. 'Search settings' in top menu, icon 'Magnifying glasses' under 'Fulltext search', or even directly in the search dialog between "Enter text to search for" and the text input line), where I can enable either wildcards or RegEx or none (as it is at the moment).

I use MoonReader on my Android 9 phone at the moment, and even here I can use Regex.

I didnt find any issue here with regex in search, that why I submit this Feature Request now.
Sorry if there is already.

Thanks, frank

**Comment by poire-z** [comment]
Probably hard to do: we delegate the string search to the engines (crengine, koptinterface), and their implementations might be tortuous (at least, for crengine that i know: multiple DOM nodes, skipping soft hyphens...), so it wouldn't be an easy task.

**Comment by zwim** [comment]
I think I found an easy way.
I will look into it the next days (for corner cases, utf8 quirks ...). When the way is doable I will make PR.

**Comment by poire-z** [comment]
I'd rather like you tell a bit more about your idea before going into spending time working on it ;)
Frontend only ? crengine only ? or would it work with all engines ? utf8 quirks again ?

**Comment by zwim** [comment]
@poire-z Thanks for your time, too.
I would work only on crengine (plus a small additional dialog  in the frontend if thing go easy; to let the user enter a regex). In 'lvtinydom' there are the functions findText and fimdTextRev. 
The idea is to use 'regex_search' within those functions.
Softhyphens can be eliminated before applying the regex and added afterwards for an offset.

What do you think? Is it worth the time? Yours and mine?

**Comment by zwim** [comment]
> Because I think we don't really need the feature :/)

Yes, I will only go if it goes easy!

**Comment by poire-z** [comment]
(Well, probably not worth _my_ time :)
A few thoughts:
- bit bothering if it's crengine-only - but I guess that if there's a checkbox that makes it explicite it's optionally available with crengine/EPUB documents only, it could be ok
- I spent some time to make findText & co work ok as they currently do - don't break them or make them more complex ! :)
- _The idea is to use 'regex_search'_ - I think there's no facilities for regex currently in crengine. So, do you think about adding/writing some regex code ? Using an external library ? If the later, it might be a mess, it should be `#ifdef` so others could build without it, and the library would need to be added to base. Not fun work :/
- Not sure if findText() works only in a single text node, or across text nodes (I think single text node). But looking for `re*der`, it could match multiple overlapping segments, possibly spanning multiple pages !
- crengine works in unicode/utf32, so at least, you'd have to utf8tounicode only the input string.

Well, I hope I won't have to think about it more than that ;)
(But that's up to you - I only wish it doesn't add too much and doesn't make these crengine parts more complex/less readable.)

**Comment by NiLuJe** [comment]
There aren't really much choices as far as solid PCRE backends go, AFAICT (e.g., https://github.com/kkos/oniguruma or good old https://www.pcre.org/).
