### ISSUE TITLE
UI: Move "Writing Direction" and "Document Columns" from Cog to Aa? (mupdf engine)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7863]
If I understand correctly, `Writing Direction` and `Document Columns` can only be enabled if `Reflow` is enabled.
In `Aa` menu `Reflow` enables `Font size` and `Word Gap` as well.  So wouldn't it be natural and much less confusing if these two options were moved to `Aa` as well?

**Comment by poire-z** [comment]
There are a few others elsewhere (Line spacing, alignment) that are only enabled when Reflow is on.
The distribution of widgets in the various panels was mostly to have each panel limited to 4 items (so we can see more of the document), while still trying to be logical. #6122 #6131

**Comment by mergen3107** [comment]
Ah, I see.
Thank you for explaining!

**Comment by poire-z** [comment]
(You already requested that at https://github.com/koreader/koreader/issues/6122#issuecomment-624754783 :)

**Comment by mergen3107** [comment]
@poire-z 
How come I forgot this :')
