### ISSUE TITLE
Crash when opening an epub generated from Wikipedia.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#7864]
* KOReader version: master
* Device: Android (emulator)

#### Issue

Crash when opening an epub generated from Wikipedia.

#### Steps to reproduce

Do a wikipedia lookup from the FM
Select full article -> save as epub.
When downloaded and prompted press "read it now"

Cannot be reproduced from the reader.
Cannot be reproduced on the emulator at all.

<details>
  <summary>crash.log</summary>

```
...
succesfully created: /storage/emulated/0/E-reader.EN.epub
Failed to run script: frontend/ui/widget/dictquicklookup.lua:405: attempt to call method 'showReader' (a nil value)
```
</details>

**Comment by poire-z** [comment]
I can reproduce it on the emulator, following your steps:
```
06/17/21-21:19:36 DEBUG refresh on physical rectangle 0 0 600 610
06/17/21-21:19:37 DEBUG close filemanager
06/17/21-21:19:37 DEBUG close widget: table: 0x7f25c1cfd3b0
06/17/21-21:19:37 DEBUG Tearing down FileManager table: 0x7f25c1cfd3b0
./luajit: frontend/ui/widget/dictquicklookup.lua:405: attempt to call method 'showReader' (a nil value)
stack traceback:
 frontend/ui/widget/dictquicklookup.lua:405: in function 'action'
 frontend/ui/uimanager.lua:1194: in function '_checkTasks'
 frontend/ui/uimanager.lua:1592: in function 'handleInput'
 frontend/ui/uimanager.lua:1700: in function 'run'
```
Possibly related to @NiLuJe's recent work on document/fm switching - or an issue there for years because I never tested that from the Filemanager :)
(Happens also with 2021.05 appimage.)
Possibly https://github.com/koreader/koreader/commit/2944d53e7e10e593bccc5cac3172e88c59b113c1#diff-f250b2c70dbfef162af814861c9c2f8cc36c8c7c7f9628ce75286dee13a8e5edL382

**Comment by Frenzie** [comment]
I don't think I've ever tested this one. :-)

**Comment by pazos** [comment]
I would swear I couldn't reproduce on the emulator, but trusting @poire-z. Maybe I did test from the quickstart guide? :facepalm: 

Anyways, happy that the bug happens everywhere. Less tricky bug is it :)

**Comment by NiLuJe** [comment]
> Possibly [2944d53#diff-f250b2c70dbfef162af814861c9c2f8cc36c8c7c7f9628ce75286dee13a8e5edL382](https://github.com/koreader/koreader/commit/2944d53e7e10e593bccc5cac3172e88c59b113c1#diff-f250b2c70dbfef162af814861c9c2f8cc36c8c7c7f9628ce75286dee13a8e5edL382)

Oh, yeah, that hunk is definitely fishy.
