### ISSUE TITLE
Crash in inputtext when using clipboard (maybe just Android)

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#7865]
* KOReader version: 2021.5-90 and prob. before
* Device: Mobile Android

#### Issue
Crash

#### Steps to reproduce
Open a book. Open texteditor (new file). Long tab in the text input field. Crash. Maybe this is due to an empty clipboard?
Can not test more as I am not at home.

**Comment by mergen3107** [comment]
When I long press on the text input field, Clipboard dialog pops up

**Comment by zwim** [comment]
I have not used the clipboard on this (virgin) device yet. So maybe it is just an firsttime init problem.
BTW: This is a new fresh instaal on a mobile.

**Comment by zwim** [comment]
@mergen3107 Thank you for your hint.
I can confirm this is an init problem. After copying some nonsense to the clipbord the problem is solved.
But anyway this issue shoild be solved: No clipboard no crash!

**Comment by NiLuJe** [comment]
A crash.log excerpt would have been helpful ;).

**Comment by zwim** [comment]
@NiLuJe You are right, but this will be on sunday, when I am at home again.

**Comment by zwim** [comment]
I made some more tests. 
1.) There is no crash, when only using the KOReader clipboard.
2.) If I put some text in the clipboard in another android app and try to insert it in KOReader -> crash. But this seems not always to happen.
[clipboard-bug.txt](https://github.com/koreader/koreader/files/6682062/clipboard-bug.txt)

I hope this logcat helps.

**Comment by pazos** [comment]
@zwim: indeed, we asume the stuff placed on the clipboard in plain text. It isn't always the case, it seems.

I wasn't able to reproduce anywhere, but I only use Chrome and Markor as the sources of the copied text to paste in KOReader. Now, if the clipdata can't be coerced to text it will paste and empty string. (Same behaviour as pre https://github.com/koreader/android-luajit-launcher/pull/312)

Could you check if this solves your issue?. If not: could you give me examples of apps where the text copied make KOReader crash on paste?

**Comment by zwim** [comment]
I can force the bug when I put '*' to the clipboard (also from chrome) and try to insert it in koreader.

Have not tested the luajit#312.
