### ISSUE TITLE
Reading Statistics: duplicates for djvu files

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7867]
* KOReader version: 2021.05-90
* Device: Kindle PW3 (5.9.7)

#### Issue
Reading Statistics treats each opening of the same djvu file as a separate book entry. 
Have a look at the screenshot of 'Reset statistics - Reset statistics by book' after re-opening the same books multiple times:
![FileManager_2021-06-18_015845](https://user-images.githubusercontent.com/6279855/122514533-16f66a00-cfda-11eb-89c8-a1f07770ea6c.png)

Seems like fb2 and pdf books have no such issue.
djvu books used in the test:
[Қаржаубай Омарұлы - Ақтөс.zip](https://github.com/koreader/koreader/files/6655187/-.zip)
[Д. А. Франк-Каменецкий - Лекции по физике плазмы.zip](https://github.com/koreader/koreader/files/6667845/-.-.zip)

#### Steps to reproduce
Open a djvu book
Open any other book
Re-open the djvu book with Top Menu - Previous
Repeat multiple times
Go to Reset Statistics

##### `crash.log` (if applicable)
no crash

Where can I find metadata for Reading statistics? It is not in the .sdr directory.

**Comment by NiLuJe** [comment]
That would imply they have a non-stable fast md5 hash, which is... surprising (and only tangentially related to the statistics plugin).

```
https://github.com/koreader/koreader/blob/d2db93431a9bfd2da311894c132cc9a258e2f4d6/plugins/statistics.koplugin/main.lua#L693-L702
```

**Comment by NiLuJe** [comment]
Unless you're baking notes/highlights inside those files?

**Comment by mergen3107** [comment]
The first book already has “ToC”, which is only visible in KOReader’s ToC menu, not in Bookmarks. 
With the second book, I tried to add bookmarks on PC for them to appear in KOReader’s ToC menu, but they didn’t show up neither in ToC nor in Bookmarks menus.

**Comment by NiLuJe** [comment]
Turned out to be related to documents with no author metadata (which just happens to be common for DvJu files ;)).

**Comment by mergen3107** [comment]
@NiLuJe 
Thanks for finding this!! I really have no idea how one would possibly find such overlook :D 
Do you think this might fix #7777 ? The second book here is the same file with modified Bookmarks that this issue had.

**Comment by NiLuJe** [comment]
Highly unlikely (read: no), as this has nothing to do with the statistics plugin and/or SQL?

**Comment by mergen3107** [comment]
Ah, sorry. I should have rephrased that. Do you think no Author issue affects 7777 too? I’ll try add metadata to the file later to see if that fixes missing ToC

**Comment by NiLuJe** [comment]
I wouldn't think so (that's what I meant by not SQL related).

**Comment by mergen3107** [comment]
OK!

**Comment by mergen3107** [comment]
Thank you @NiLuJe !
The fix works perfectly!
