### ISSUE TITLE
90 degree rotated controls.

### ISSUE THREAD

**Issue by rezackacz** [koreader/koreader#7870]
* KOReader version: 2021.05
* Device: Pocketbook Touch Lux 4

Touch controls are rotated 90° counterclockwise from screen orientation.

**Comment by mergen3107** [comment]
https://github.com/koreader/koreader/issues/7747#issuecomment-846971676

Find your device model in that file and try to do the same

**Comment by rezackacz** [comment]
Thx, have the same model.
