### ISSUE TITLE
FR: cursor control using device buttons or on screen buttons.

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#7871]
**Does your feature request involve difficulty completing a task? Please describe.**
I find that it is not so easy to use the cursor accurately with the finger.

**Describe the solution you'd like**
I was wondering if it would be possible to control the cursor (e.g. in the dictionary or in the highlights' text editor, etc.) using the device buttons or if there could be buttons on the screen for this purpose.

Thank you!

**Comment by mergen3107** [comment]
There are four arrow buttons in keyboard’s Sym layer, in the bottom right corner

**Comment by hius07** [comment]
And also some hidden features including clipboard.
https://github.com/koreader/koreader/wiki/Virtual-keyboard
https://github.com/koreader/koreader/wiki/Clipboard

**Comment by ichnilatis-gr** [comment]
Very well! I'm sorry I didn't notice them.
Thank you very much!

(By the way, is there a way to have the KOReader's Wiki in my device, offline?)

**Comment by Frenzie** [comment]
@offset-torque is working on a very nice looking manual. :-)

You can compile a (rather suboptimal) EPUB out of the wiki as I wrote in https://github.com/koreader/koreader/issues/1371#issuecomment-67770674

**Comment by ichnilatis-gr** [comment]
I beg your pardon, I did not understand. Where can I download this EPUB file of wiki?

**Comment by ichnilatis-gr** [comment]
As for the arrows, wouldn't it be more practical if they appeared below the input field? So that we don't need to change the keyboard layer.

**Comment by Frenzie** [comment]
Nowhere, but here you go. (remove the .zip)

[help.epub.zip](https://github.com/koreader/koreader/files/6680843/help.epub.zip)

**Comment by ichnilatis-gr** [comment]
Thanks a lot!

**Comment by poire-z** [comment]
Closing as arrow keys will be on the main layer soon with #7972.
