### ISSUE TITLE
Pan in continuous scroll mode stutters, rather than pans

### ISSUE THREAD

**Issue by aith** [koreader/koreader#7873]
* KOReader version: Yellow Daffodil
* Device: Thinkpad X1 Yoga Gen 6 (Ubuntu)

#### Issue
When panning with the mouse or touchscreen the starting point of the pan is the location that the mouse or finger first clicks. This isn't useful for reading. Instead of teleporting to the clicked location it should start scrolling based on the current position of the pdf.

#### Steps to reproduce
Install Koreader on Ubuntu 20.04 
Use touchscreen or mouse to drag pdf upwards or downwards

Here's a video demo  

https://user-images.githubusercontent.com/62635784/122689273-496cb680-d1d6-11eb-8cf6-38aac7492201.mp4

**Comment by NiLuJe** [comment]
This should be fixed in current nightlies (c.f., #7646).
