### ISSUE TITLE
Kindle 4 "gateway ping failed" Calibre Issues

### ISSUE THREAD

**Issue by Thefirebeast** [koreader/koreader#7881]
* KOReader version:20201.05
* Device: Kindle 4 S/N prefix 902317 Model N:d01100

#### Issue
Tablet gives 2 alternating messages "No default gateway to ping" and "No default gateway to ping" below the name of the network its connected to in wifi info. The internet works when i use the tablets experimental browser and koreaders news downloader feature. But when i try the use the calibre feature(which is part of why i wanted koreader) it gives me a message saying "Do you want to turn on the Wi-Fi?" even though it is connected.

#### Steps to reproduce
Select "Connect" under Calibre in the koreader menu

##### `crash.log` (if applicable)
N/A

####Files used to jailbreak and install koreader 
Jailbreaked using https://wiki.mobileread.com/wiki/Kindle4NTHacking

MKK: "Update_mkk-20141129-k4-ALL_install.bin" from "kindle-mkk-20141129-r18575.tar.xz" https://www.mobileread.com/forums/showthread.php?t=225030

KUAL: "KUAL-KDK-1.0.azw2" from "KUAL-v2.7.24-g9f3694a-20200604.tar.xz" https://www.mobileread.com/forums/showthread.php?t=225030

Koreader: "koreader-kindle-v2021.05.zip" from https://github.com/koreader/koreader/releases

**Comment by Thefirebeast** [comment]
I installed koreader on my phone and found that having username and password enabled prevented me from connected even though i had entered the username/password in koreader. Unfortunately im unable to manually add the ip address/port on my tablet because 
1: after entering the ip address i have to close the keyboard to get to the port box but im unable to reopen the keyboard even after clicking on the port box and pressing the keyboard button
2: even if i could enter the port number im unable to reach the ok/apply buttons in most if not all menus on koreader, i can go to the close button in menus that have it as the button all the way to the left but pressing right does not move me to the buttons to the right so i cant reach the ok, apply, and in some menus the close button like in the text editor

**Comment by Thefirebeast** [comment]
Turns out these were 2 separate issues, the first issue is still a thing, The reply was me dealing with another issue i had for some reason thought was the same thing.

**Comment by NiLuJe** [comment]
The multiple input fields thing sounds vaguely familiar, although possibly more in the context of the emulator and physical keyboards than non-touch devices.

Then again, as was mentioned on MR, quite a few widgets are left that are *not* designed for non-touch devices.

**Comment by Frenzie** [comment]
> The multiple input fields thing sounds vaguely familiar, although possibly more in the context of the emulator and physical keyboards than non-touch devices.

Presumably neither can switch properly between multiple inputs but there's fairly little overlap there. Desktop has a clear way (click mouse in textfield, should perhaps support tab too), straightforward low-priority stuff. While the non-touch devices… they'd require an entirely different paradigm. FocusManager on deselected inputs or something.

**Comment by whatever4kindle** [comment]
Hello, I found a solution for this issue. Investigating the code for some hours and reading the crash report I found out that Kindle 4NT can't handle the ping command with the -w flag (that's the word I saw used). So I located the files that have 'ping -w' and just erased the -w part and now everything works perfectly. The files are two:

/koreader/frontend/device/generic/device.lua
/koreader/frontend/ui/network/manager.lua

I can use OPDS sites and download news with no issue and the "gateway ping failed" issue is no more.

**Comment by NiLuJe** [comment]
Huh. I could have sworn we already had code to handle that...

**Comment by clrizzi** [comment]
> 4NT has `hasDPad = yes,` and doesn't have `hasKeyboard = yes,`

This is the only way to make wifi work on this device. Without these changes, I always get the information "gateway ping failed" and I get no connection. I have to manually change it on every update as the files overwrite this...
