### ISSUE TITLE
Kindle 4 Unable to close text editor

### ISSUE THREAD

**Issue by Thefirebeast** [koreader/koreader#7882]
* KOReader version: 20201.05
* Device: Kindle 4 S/N prefix 902317 Model N:D01100

#### Issue
Am unable to reach the reach the close button in text editor and can not find any other way to exit out of it

![20210623_124247](https://user-images.githubusercontent.com/33950487/123145932-f63b7380-d422-11eb-9cdb-8ab3a496e092.jpg)

This person had/has the same issue but i do not see a solution https://github.com/koreader/koreader/issues/7356

#### Steps to reproduce
Tried editing a .lua file

Not sure how to add kindle label

**Comment by Thefirebeast** [comment]
If i turned off the tablet and deleted the koreader files with my computer then would the tablet go to the home screen when its turned back on?

**Comment by Frenzie** [comment]
> This person had/has the same issue but i do not see a solution #7356

The solution/workaround is that the plugin will be disabled on non-touch devices in the next release.

You'll presumably be able to turn the device off by holding the power button for a few seconds, but I'm afraid you'll have to ask someone with a Kindle.

**Comment by Thefirebeast** [comment]
I see, unfortunately turning off and on the tablet with the power button just brings me back to the text editor.

**Comment by Thefirebeast** [comment]
After turning it off and on repeatedly it finally booted up on the home screen. Thanks
