### ISSUE TITLE
Multiple TOC-related issues for MOBI files

### ISSUE THREAD

**Issue by aik099** [koreader/koreader#7884]
* KOReader version: 2021.05 "Yellow Daffodil"
* Device: Kindle Keyboard

#### Issue

1. TOC provided by a MOBI file doesn't work (show empty page instead of a heading list)
2. attempt to generate heading-based alternative TOC does nothing (still seeing an empty page)
3. the hanging line feature that supposed to start each new chapter with a new page doesn't work
4. the heading font size is too small (compared to how Kindle renders this) and I don't know where to change it in KOReader

#### Steps to reproduce

* download the MOBI file from here: https://predanie.ru/download/uploads/ftp/feofan-zatvornik-svy/chto-est-duhovnaya-zhizn-i-kak-na-nee-nastroitsy/duh-zhizn.mobi
* open it
* try seeing the TOC

I've seen TOC working for MOBI files in general on NeoReader (the reader on Onyx Boox devices), which supposedly also using `crengine` like KOReader, so maybe updating used `crengine` would fix all the issues.

P.S.
I've seen several older issues about TOC in MOBI files, but maybe situation has changed now and it can be fixed.

**Comment by NiLuJe** [comment]
Unlikely, mobi support is very minimal, and basically just a historical artifact. Don't expect anyone working on it.

**Comment by hius07** [comment]
Why not to take fb2 whith perfect ToC?
http://flibusta.is/b/347044

**Comment by pazos** [comment]
> I've seen TOC working for MOBI files in general on NeoReader (the reader on Onyx Boox devices), which supposedly also using crengine like KOReader, so maybe updating used crengine would fix all the issues.

Nah, NeoReader doesn't use crengine at all, just some javascript on top of a webview. They use pdfium for pdfs.

Very old versions of NeoReader (called OReader in that time) were using FBReaderJ as its engine for reflowable epubs. Of course in violation of FBReaderJ license and in violation of Android clausule of not shipping GPL code in userspace.

**Comment by aik099** [comment]
Wasn't aware of that (that NeoReader in past had legal issues). Hopefully, it's all been resolved by now.

I thought about `crengine`, because I saw https://github.com/onyx-intl/boox-opensource/tree/master/code/src/cr3 .

**Comment by aik099** [comment]
> Why not to take fb2 whith perfect ToC?
> http://flibusta.is/b/347044

Thank you @hius07 , I'll try that.

**Comment by pazos** [comment]
> Wasn't aware of that (that NeoReader in past had legal issues). Hopefully, it's all been resolved by now.

They're still shady as hell (they don't release kernel sources, they distribute GMS without certifcation, they distribute app versions in their store without complying with their licenses...)

> I thought about crengine, because I saw https://github.com/onyx-intl/boox-opensource/tree/master/code/src/cr3 .

That's from their pre 2013 devices without android.
