### ISSUE TITLE
FR: Please allow grouping of History items

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7887]
**Does your feature request involve difficulty completing a task? Please describe.**
I started reading manga recently. The problem is that the files are pretty large. One volume epub takes around 100 MB. There could be 30 or more such volumes :D Due to space limitation, I cannot afford having all these volumes in one large epub, so I need to divide them and upload partially to read.

**Describe the solution you'd like**
That also means that each volume gets its own place in the History like "Volume 1.epub", "Volume 2.epub", etc. Which makes History list overwhelmed.
Can you please add an option to able to group items in sorts of folders inside History, manually or based on the directory? 

**Describe alternatives you've considered**
For now I just leave these as they are. I should probably switch based to non-cover image History view to be able to navigate through all the opened books.

**Additional context**
Things get even more complicated when there are multiple of such manga titles and all of them have time same names "Volume N.epub". So ability to group them would make things much more clear.

Thank you!

**Comment by Frenzie** [comment]
You can also do a quick mass rename on your PC before loading it.

**Comment by mergen3107** [comment]
@Frenzie 
You mean, to have just one filename e.g. `Title.epub` for any Volume in the same folder? 
But what if I have a few Volumes uploaded to Kindle at a time?

**Comment by Frenzie** [comment]
I mean that you control the filenames. If you imagine the screenshot below in reverse (I'm being lazy but bear with me), those filenames are a bit unclear out of context. But then when you rename them with `koreader-` in front of it, it's always clear.
![Screenshot_2021-06-25_23-48-19](https://user-images.githubusercontent.com/202757/123488267-dae18b80-d60f-11eb-9d37-0f33a4938ede.png)

**Comment by mergen3107** [comment]
OK, I think I understood you. However, I don't see that should help me with grouping.
This will only help to distinguish them in Detailed mode, but they will overwhelm the History nevertheless..

**Comment by Frenzie** [comment]
In context, maybe not if you use remove deleted items from history. But sure.

**Comment by poire-z** [comment]
This and #7889 ... You're asking us to complicate things in a not-easy-to-make-it-obvous way just because of some strange use case of yours :/ Better fix that use case of yours then :)
For KOReader, a file is a book, period. So many things depend on this assumption.

But one/you could probably hack a user-plugin, similar to https://github.com/koreader/koreader/blob/master/plugins/movetoarchive.koplugin/main.lua from #6101 (+not done #6164), that would after next book open, if in the same direvtory: clean-up history and merge statistics, etc...
(But probably not worth the time involved, and you might soon be fed up with mangas and forget about this use case :)

**Comment by mergen3107** [comment]
OK :)
Thank you for your consideration and time! 
I’ll try your suggestions

**Comment by mergen3107** [comment]
OK, I give up.
1) History will pick up the file with the same name. So I can rename `Volume 1.epub` to `Title.epub`, read it, then rename `Volume 2.epub` to `Title.epub` and overwrite it. The there will be the same History Item.
2) Reading statistics, however, still creates separate entry for the files with the same name. I also tried to edit these files to have the same `Title` in metadata - still new entries. So I ended up with just manually editing the `.sqlite3` file to sum all times of Volumes under one entry after I read the whole mange title.

**Comment by poire-z** [comment]
We support shell scripts in file browser, so I guess that if this was a use case of mine, I'll write one and drop/copy it in each such folder with such multi-volume books. When swithing between such documents, I'll open the next one, close it, and run this script, and it could do what you do manually:
- remove from history all entries in the same directory except the last
- change book_id in page stats for all entries in the same dir, and remove the book entries of other than last document.

Or a user-plugin, as this might be easier to do in Lua.
