### ISSUE TITLE
[NEW DEVICE] Does not launch on Kobo elipsa

### ISSUE THREAD

**Issue by mwt** [koreader/koreader#7890]
* KOReader version: 2021.06
* Device: Kobo Elipsa

#### Issue

The application does not launch on the new Kobo elipsa. The device's stock interface freezes after I try to launch KOReader from nickel menu. The device UI eventually restarts.

#### Steps to reproduce

Install KOReader and nickel menu on the new Kobo elipsa. Click on Nickel Menu > KOReader. The device will freeze and then eventually restart.

##### `crash.log`
[crash.log](https://github.com/koreader/koreader/files/6719564/crash.log)

**Comment by NiLuJe** [comment]
As in, Soon (TM).

(i.e., it'll be ready when it's ready ;)).
