### ISSUE TITLE
FR: The ability for renaming bookmarks

### ISSUE THREAD

**Issue by amir2mi** [koreader/koreader#7893]
I am using Koreader for a long time it is great.
The idea of changing the title of a bookmark can help users to find them easier.

Now my bookmarks are named like this: 
Page [x] in [chapter name] @ [date and time]
e.g page 50 in Hello World! @ 2021-06-28: 18:30

I would say it will be better a lot if I have a feature to rename that untidy name to a custom thingy.

**Comment by NiLuJe** [comment]
You... already can? (From the Bookmarks menu, I don't recall if its bound to a tap or a long-press on an item in there).

**Comment by amir2mi** [comment]
@NiLuJe Thanks that worked! That was a bit tricky probably a three-dot icon will make this clear🤔
