### ISSUE TITLE
FR: More space for better touch experience in Ereaders

### ISSUE THREAD

**Issue by amir2mi** [koreader/koreader#7895]
This is the problem that I have had from the first time I started using Koreader. Touch experience in e-readers is poor enough and a narrow UI makes it worse, at least for me.
This is a typical situation for pages like history, bookmarks, and ...
1 | 2
------|---------
![1](https://user-images.githubusercontent.com/64708228/123579530-4fbdec80-d7ed-11eb-8368-bb9415ea48d8.jpg)|![2](https://user-images.githubusercontent.com/64708228/123579587-6f551500-d7ed-11eb-8b19-d004f1225898.jpg)

So when the user touch there two things might happen:
 1- The user achieves to its wish.
 2- The user wrongly touches a different thing.
The probability of this action is 50/50 if the user does not pay enough attention.

Kobo Nickel has padding for this kind of pages I think it is intended for this reason, what is in my mind is something like this:
![koreader pages padding](https://user-images.githubusercontent.com/64708228/123580801-c825ad00-d7ef-11eb-9238-4634c0c873ab.jpg)

It happens for me that I touch multiple times and nothing happens, then when I touch a bit further something else happens (for example opening a book) I just want to close the page! and that is annoying.

P.S. I changed the direction for the last one but it was not on purpose.

**Comment by hius07** [comment]
I usually close this page with a swipe-down.

**Comment by amir2mi** [comment]
@hius07 You are such a savior! But some edits for this can be great as well.

**Comment by hius07** [comment]
Fixed in the TitleBar
https://github.com/koreader/koreader/blob/6f45c076ecc946ce192e37a86c44bb83e128a0dd/frontend/ui/widget/titlebar.lua#L371
