### ISSUE TITLE
Presence of self-closed <dc:publisher/> tag kills OPDS parsing

### ISSUE THREAD

**Issue by inductiveload** [koreader/koreader#7899]
* KOReader version: 2021-06
* Device: Kobo

#### Issue

Trying to use the French Wikisource OPDS catalog fails (shows only a single entry).

#### Steps to reproduce

* Add the following XML as an OPDS catalog: [Bon_pour_export.xml.txt](https://github.com/koreader/koreader/files/6730110/Bon_pour_export.xml.txt)
* Or use the (much larger) live catalog: https://ws-export.wmcloud.org/opds/fr/Bon_pour_export.xml
* Open in Koreader OPDS browser
* Only one item shown - should be 2 (for the attached file) or very many (for the URL)
* Changing self-closed `<dc:publisher/>` to `<dc:publisher></dc:publisher>` or removing that tag in the first entry fixes it

**Comment by NiLuJe** [comment]
Does changing it to `<dc:publisher />` instead help?

**Comment by inductiveload** [comment]
@NiLuJe yes, that fixes it

**Comment by inductiveload** [comment]
This is working for me now. Thank you!
