### ISSUE TITLE
Can't activate the Wi-Fi

### ISSUE THREAD

**Issue by MaximeAnsquer** [koreader/koreader#7912]
* KOReader version: v2021.06
* Device: PBInkPad3

#### Issue

Hello, I regular notice the creation of crash.log files on me device, so I figure something is wrong.
Moreover, whenever I try to access something over the internet (Wikipedia for example), it asks me if I want to activate the Wi-Fi, I hit "Activate", then the message disappears and nothing happens (I don't know if this is linked to the crash files).
Thank you for your help !

[crash.log](https://github.com/koreader/koreader/files/6740811/crash.log)

**Comment by Frenzie** [comment]
It's just there so you can find it if there is a crash. Otherwise there's just some logging. ^_^

**Comment by MaximeAnsquer** [comment]
Oh OK, so there is no actual error? Weird file name then 😄 
Any insights about my Wi-Fi problems? I see lines like:

> PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known

I guess that's not normal?

**Comment by Frenzie** [comment]
I don't know what is supposed to happen on PB.

**Comment by NiLuJe** [comment]
There are a few Wi-Fi-on-PB issues open, IIRC.

**Comment by andrewshadura** [comment]
Maybe not quite the right issue, but I noticed even with the recent changes touching Wi-Fi, I still can’t get inbuilt network functionality to work. KOReader says "no default gateway configured" when I’m on Wi-Fi, and when I try to run commands like `ping -c4 8.8.8.8`, I can’t get through. I’m not sure how to attack this issue.

@rjd22, since you seem to have direct contact with the PB people, maybe we can get them to help with this too?

**Comment by rjd22** [comment]
@andrewshadura Can you check if the following PR fixes that for you?

https://github.com/koreader/koreader/pull/8730

**Comment by andrewshadura** [comment]
Yeah, I’ve just found it. I will later today.

**Comment by andrewshadura** [comment]
No change. This is what I found in the logs after trying to view network settings and synchronising time:
```
01/28/22-19:01:35 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
sh: ip: not found
28 Jan 19:01:58 ntpdate[1293]: bind() fails: Permission denied
hwclock: RTC_SET_TIME: Permission denied
01/28/22-19:02:42 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
28 Jan 19:02:50 ntpdate[1451]: bind() fails: Permission denied
hwclock: RTC_SET_TIME: Permission denied
sh: ip: not found
```

**Comment by andrewshadura** [comment]
I guess it comes from `frontend/device/generic/device.lua`:
```lua
    if std_out then
        local result = std_out:read("*all")
        std_out:close()
        std_out = io.popen('2>/dev/null iwconfig | grep ESSID | cut -d\\" -f2')
        if std_out then
            local ssid = std_out:read("*all")
            result = result .. "SSID: " .. util.trim(ssid) .. "\n"
            std_out:close()
        end
        if os.execute("ip r | grep -q default") == 0 then
            -- NOTE: No -w flag available in the old busybox build used on Legacy Kindles...
            local pingok
            if self:isKindle() and self:hasKeyboard() then
                pingok = os.execute("ping -q -c 2 `ip r | grep default | tail -n 1 | cut -d ' ' -f 3` > /dev/null")
            else
                pingok = os.execute("ping -q -w 3 -c 2 `ip r | grep default | tail -n 1 | cut -d ' ' -f 3` > /dev/null")
            end
            if pingok == 0 then
                result = result .. "Gateway ping successful"
            else
                result = result .. "Gateway ping FAILED"
            end
        else
            result = result .. "No default gateway to ping"
        end
        return result
    end
```
Indeed, there’s no iproute2 on this device, instead, there are net-tools.

**Comment by andrewshadura** [comment]
I’m preparing a pull request for this.

**Comment by andrewshadura** [comment]
Unfortunately, I still can’t test it properly because:
```
ping: permission denied (are you root?)
ping: permission denied (are you root?)
```

**Comment by andrewshadura** [comment]
See #8739 for a partial fix.

**Comment by andrewshadura** [comment]
I'll see if I can use some alternative. `traceroute`, if available, usually uses UDP and doesn't require suid.

**Comment by andrewshadura** [comment]
Nope, `traceroute` also can’t do anything as non-root (since it apparently also comes from busybox which can’t be suid root).

**Comment by NiLuJe** [comment]
Would InkView have a similar API call, per chance? (I know it pulls in cURL, because it caused us no end of pain ;p).

**Comment by rjd22** [comment]
Can someone confirm if this is still an issue with the latest koreader? I might take a look at solving this by using the native inview api's.

**Comment by andrewshadura** [comment]
I’ll try to test it tomorrow or next week.

**Comment by kimabjorkede** [comment]
> Unfortunately, I still can’t test it properly because:
> 
> ```
> ping: permission denied (are you root?)
> ping: permission denied (are you root?)
> ```

Exact same issue here.

**Comment by NiLuJe** [comment]
Pinging requires the `CAP_NET_RAW` cap, or a 3.0+ kernel setup to allow unprivileged ICMP sockets; there's nothing we can do about that if the host system doesn't provide that.

**Comment by kimabjorkede** [comment]
I created this issue: #10651, since it's more than just pinging that's the issue for me.
