### ISSUE TITLE
PW2 with FW5.12.2.1.1 freeze after few page turns

### ISSUE THREAD

**Issue by HrMitrev** [koreader/koreader#7914]
* KOReader version: 2021.06
* Device: Paperwhite 2

#### Issue
Hi! I am amazed at how great the KOreader is for reading pdfs. I use it on my inkpad3.
However when I read a 200 page (27MB) pdf on my PW2 it always freezes or less often crashes.
#### Steps to reproduce
Start KOReader from latest KUAL on paperwhite 2 with latest firmware 5.12.2.1.1. Open a 212 page compressed to 27MB with online adobe tool - https://www.adobe.com/acrobat/online/compress-pdf.html turn a few pages. At most after page 6 KOReader freezes or crashes. I cannot share the pdf book because it's copyrighted - I own a physical copy and had it scanned.
[crash.log](https://github.com/koreader/koreader/files/6743374/crash.log)

**Comment by mergen3107** [comment]
Can you please go to File Manager - top menu - Tools - more tools - Developer options : and enable both debug and verbose logging. Then make it crash again and upload your new crash.log

**Comment by HrMitrev** [comment]
Unfortunatelly the most common failure mode is freezing which requires hard reboot. This time I got to page 12 after fresh reboot. I presume it has to do with the restricted memory on that device.
[crash.log](https://github.com/koreader/koreader/files/6743544/crash.log)

**Comment by NiLuJe** [comment]
Nothing jumps out in the logs, but, yeah, a PW2 on 5.12 is going to be ridiculously painful.
