### ISSUE TITLE
Highlight menu instead of dict lookup

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#7918]
* KOReader version: v2021.06-12
* Device: KA1

#### Issue
When I press and hold on a word (less than 3 seconds) the highlight menu opens every time.

**Comment by poire-z** [comment]
You might have messed with `Gear > Document > Highlight action >` ? These should be the defaults:
![image](https://user-images.githubusercontent.com/24273478/124087947-c90a4900-da52-11eb-8e15-395c2fdae125.png)

**Comment by gerhaher** [comment]
Indeed I have. :-)
