### ISSUE TITLE
FR: Show page numbers from role="doc-pagebreak"

### ISSUE THREAD

**Issue by tastytea** [koreader/koreader#7919]
**Does your feature request involve difficulty completing a task? Please describe.**
I'm reading an e-book that records page numbers only like this: `<span role="doc-pagebreak" id="pg_15" aria-label="15"></span>`. It has no `epub:type="pagebreak"` attributes.

**Describe the solution you'd like**
It would be wonderful if KOReader would display the page numbers from `doc-pagebreak` page breaks on the side, like it does with `epub:type="pagebreak"` page breaks.

**Comment by poire-z** [comment]
We don't really do it from the `epub:type="pagebreak"` attributes.
We do it from the 3 possible kinds of XML files that a publisher can put inside the EPUB to give the full list of hardcopy page numbers: https://github.com/koreader/crengine/pull/336

Doing it from these attributes would need us to check all nodes and build that list dynamically, which is probably expensive and would have no effect on 99.9% of documents (not mentionning the coding work involved :)
Is there really no other nav/ncx/page-map file in your book that we failed parsing, or another format of document we don't (yet) support ?

(by we/us, I mean crengine :)

**Comment by tastytea** [comment]
> We don't really do it from the epub:type="pagebreak" attributes.
> […]
> Doing it from these attributes would need us to check all nodes and build that list dynamically, which is probably expensive and would have no effect on 99.9% of documents (not mentionning the coding work involved :)

Ah, OK. That makes sense. That explains why I couldn't find code for it. 😄

> Is there really no other nav/ncx/page-map file in your book that we failed parsing, or another format of document we don't (yet) support?

No, there is no list included. 🙁
I can live without knowing the “official” page number, I just thought that it might have been an oversight. 😊

**Comment by poire-z** [comment]
May be calibre can detect these attributes, and process such an EPUB to build one of the classic page-map file ?

**Comment by tastytea** [comment]
I found a [PageList plugin](https://www.mobileread.com/forums/showthread.php?t=265237) for [sigil](https://sigil-ebook.com/). After converting the book to EPUB3 and [modifying the plugin slightly](https://www.mobileread.com/forums/showpost.php?p=4135287&postcount=32), I now have page numbers. 😊

Thanks for the pointer, I would not have thought to look for a plugin!
