### ISSUE TITLE
Dictionary lookup finds nothing on Android x86

### ISSUE THREAD

**Issue by BorisNA** [koreader/koreader#7920]
* KOReader version: release 2021.06 and nightlies 2021.06-12, 2021-06-15
* Device: Teclast Air x86 3G (Android 4.4, x86)

#### Issue

Dictionary lookup finds nothing for any word in any book

#### Steps to reproduce

- Make a clean install
- Download any dictionary (for example GNU Collaborative English, Short English-Russian)
- Open the Quickstart Guide
- Select any word (for example "menu")
- Dictionary lookup fails ("Not available - no results")

Doesn't matter if fuzzy lookup is on or off

The same steps work for the arm build (2021.06-15) on another device and the correct entry for "menu" is shown.

##### `crash.log` (if applicable)

Filtered logcat output with "debug on" (although it looks like there is nothig of interest)
[teclast_filtered.log](https://github.com/koreader/koreader/files/6749879/teclast_filtered.log)

Settings and results screenshots:
[Screenshot_2021-07-01-20-01-53](https://user-images.githubusercontent.com/7961527/124166764-ee777100-daab-11eb-9df5-3d028cc582f9.png)
[Screenshot_2021-07-01-20-01-43](https://user-images.githubusercontent.com/7961527/124166806-fc2cf680-daab-11eb-9173-9fe28ce9793e.png)
[Screenshot_2021-07-01-20-02-09](https://user-images.githubusercontent.com/7961527/124166816-ff27e700-daab-11eb-94df-3fad962a9d1e.png)

**Comment by pazos** [comment]
Do not filter the message. Just use:

1. `adb logcat -c` to clear the buffer
2. uninstall the app and install it again
3. `adb logcat` to retrieve the logs
4. start KOReader for the first time.

It should be an issue with `sdcv` symlink.

**Comment by BorisNA** [comment]
Thanks for the instructions. I'm quite comfortable with the command line (and linux/windows) but not that far into the Android developemnt

Here is the full log
[teclast_full.zip](https://github.com/koreader/koreader/files/6750091/teclast_full.zip)

**Comment by pazos** [comment]
@BorisNA: thanks for the logs.  Your device is very very very verbose :)

The error is:

```logcat
W/System.err( 3657): java.lang.IllegalArgumentException: expected receiver of type libcore.io.ForwardingOs, but got java.lang.reflect.Field
W/System.err( 3657): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 3657): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 3657): 	at org.koreader.launcher.extensions.FileExtensionsKt.symlink(FileExtensions.kt:8)
W/System.err( 3657): 	at org.koreader.launcher.Assets$bootstrap$2$1$1.invoke(Assets.kt:8)
W/System.err( 3657): 	at org.koreader.launcher.Assets$bootstrap$2$1$1.invoke(Assets.kt:1)
W/System.err( 3657): 	at androidx.core.app.AppOpsManagerCompat.forEachLine(AppOpsManagerCompat.java:6)
W/System.err( 3657): 	at org.koreader.launcher.Assets.bootstrap(Assets.kt:17)
W/System.err( 3657): 	at org.koreader.launcher.Assets.extract(Assets.kt:3)
W/System.err( 3657): 	at org.koreader.launcher.MainActivity.extractAssets(MainActivity.kt:1)
W/System.err( 3657): 	at dalvik.system.NativeStart.run(Native Method)
```

I'm going to make a new build for you to test.

**Comment by BorisNA** [comment]
@pazos Thanks! It works flawlessly.
Both normal and fuzzy mode.

**Comment by pazos** [comment]
Great. Thanks for testing!
