### ISSUE TITLE
Custom Sync Server?

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#7921]
Hi

There is a custom sync server option in KOReader. I see that there is a custom sync server but it seems very old. Is there a working custom sync server that can be self hosted?

thanks

**Comment by Frenzie** [comment]
You can host https://github.com/koreader/koreader-sync-server wherever you like.

**Comment by gerroon** [comment]
@Frenzie  thanks. It looks like it has not been updated in years, is it still compatible?

**Comment by Frenzie** [comment]
That's what you get when you go to https://sync.koreader.rocks/ ;-)

**Comment by pazos** [comment]
There're other alternatives which might be easier to deploy or updated recently: have a look at https://github.com/search?q=koreader+sync+server

**Comment by Frenzie** [comment]
Wow, there's even one in Go now? That's cool!

**Comment by Zeyadas** [comment]
> Wow, there's even [one in Go](https://github.com/yeeac/kosyncsrv) now? That's cool!

How can I install and use it?

**Comment by Frenzie** [comment]
See https://golang.org/doc/install for Go, besides that the readme. If there are any more specific questions I'd suggest asking @yeeac on their repo.

**Comment by gerroon** [comment]
There is a binary release in the repo already.  https://github.com/yeeac/kosyncsrv/releases

**Comment by Frenzie** [comment]
Whoops, that's a bit hidden on mobile.
