### ISSUE TITLE
Embedded css directory default doesn't apply on newly opened epub books

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7935]
* KOReader version: 2021-06 stable, 2021-06-15, 2021-06-20
* Device: Kindle PW3 (FW 5.9.7)

#### Issue
Embedded css set in directory defaults option does not apply in newly opened epub books, IF embedded css is set OFF by default by long-tap. So it looks like it cannot override the setting.

#### Steps to reproduce
1) Set Embedded css OFF by default in a book. Close it.
2) Add `["copt_embedded_css"] = 1,` in directory defaults.
3) Then open new epub book from the respective folder.
4) It will show as if it is enabled, but it isn't. I use the same epub files with manga. When embedded css is off, it shows too many pages instead of real ones. So one actual image is shown across multiple pages (3 or 4). When I enable embedded css, 1 image = 1 page as intended. 
5) Disable/enable will actually make it apply properly.

I am not sure what default by long tap I had in 2021-05, so I don't know where this issue starts. Having it ON by long-tap default makes the embedded css apply properly.

**Comment by poire-z** [comment]
Try to duplicate the setting with its other duplicated name. In a metadata.lua, I have:
```lua
    ["embedded_css"] = true,      -- Add this one to your directory default
    ["embedded_fonts"] = true,
    ["copt_embedded_fonts"] = 1,
    ["copt_embedded_css"] = 1,
```
(embedded_css is the one we manage, copt_embedded_css must be the one saved by the bottom widget, it's a bit of a mess for historical reasons I don't want to dig... and while it works...)

**Comment by mergen3107** [comment]
@poire-z 
Thank you! It works!
Yes, the both need to be the same for consistency: `copt` ones are for showing bottom widget selection only, the usual ones are for actually applying it.

Are there other settings that need such duplicate definition? I will add this to wiki

**Comment by poire-z** [comment]
No idea, would need to look at the code - or you to look at a metadata.epub.lua for kinda-duplicates :)
I guess lots of those where you see copt_ may have a copt-less duplicate.

**Comment by mergen3107** [comment]
https://github.com/koreader/koreader/wiki/Tweak-document-settings-by-directory
Wiki page is up.

**Comment by hius07** [comment]
> Wiki page is up.

You haven't mentioned the plugin Tools - More tools - Tweak document settings (if enabled in the Plugin management).

**Comment by mergen3107** [comment]
@hius07 
Indeed! Will fix now, thank you!

**Comment by poire-z** [comment]
>  If you can't find a setting, most probably it is not supported by this feature. For example, Alt Status Bar.

Dunno if you noticed the setting is called `["copt_status_line"] = 1,` and it really doesn't work, or if you didn't see it :)

**Comment by mergen3107** [comment]
@poire-z 
Thank you!
I didn’t know “Alternative status bar” is called “status line” :’) 
I’ll try it

**Comment by mergen3107** [comment]
@poire-z 
I checked it out, and found out that `["copt_status_line"] = 1,` is toggles `Alternative status bar` OFF, and `=0` toggles it ON. Weird, but I'll this to the wiki
