### ISSUE TITLE
Margin 0, Line spacing minimum leave a gap in bottom margin

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7936]
* KOReader version: 2021-06-20
* Device: Kindle PW3 (FW 5.9.7)

I am not sure whether this is intended or is a bug.

#### Issue
Here is the screenshot of a page with 1 image only (you need to open it separately against non-white background to see the bottom gap):
![Reader_2021-07-05_180950](https://user-images.githubusercontent.com/6279855/124523041-49b6a580-ddc3-11eb-96ef-19ea3f52f46d.png)

Here is my counted pixels:
![Reader_2021-07-05_180950_CROP](https://user-images.githubusercontent.com/6279855/124523042-4a4f3c00-ddc3-11eb-8364-197bfc5dbb4b.png)

Kindle PW3 has 1448 px vertically. There are 12 px of gap.

#### Steps to reproduce
Either set top and bottom margin to 0, line spacing - to minimum possible via UI (50) or force via directory defaults (0).
Open a book.
The single-page image will have a gap as in the screenshots above.
I attach here a epub file with only 1 image. I hope it doesn't violate any copyright (remove ".zip"):
[Vagabond - Volume 02.epub.zip](https://github.com/koreader/koreader/files/6766446/Vagabond.-.Volume.02.epub.zip)

If I increase line spacing or bottom margin, the image is shrunk down appropriately.
If I long-tap the image - it will open full screen without any gap as intended.

Am I missing some css styles to tweak?

Thank you!

**Comment by NiLuJe** [comment]
IIRC, you can't get full-height images in CRe without some extra trickery for... reasons?

Sidebar: CBZ is how you should be dealing with this, not ePub ;).

**Comment by poire-z** [comment]
Dunno if 12px would be the height of your footer (seems small), but there is a NiLuJe:tm: tweak to get rid of it as `Status bar > Settings > Reclaim bar height from bottom margin`

**Comment by mergen3107** [comment]
@NiLuJe 
OK, thank you!
Yes, I think I need to switch to CBZ.
It's has great pros:
- MUCH faster file opening
- tile-by-tile zoom
- no need to force line spacing, margins, or render mode `flat` as I did with epub
Compared to cons:
- text happened to be in-between tile cannot be zoomed by taps, but rather width page-width scaling (as in usual pdf)
- no ToC. However, by my fourth mange title I noticed that most of them don't have chapter folder anyway :')

**Comment by mergen3107** [comment]
@poire-z 
Yes, `Reclaim` is ON in this example. Status bar's container height or bottom margin have no effect on these 12 px.
If I turn it off, the gap becomes even larger.

**Comment by poire-z** [comment]
I remember crengine, when finding out the max size for an image, will account for the padding/margin around it (as margin/border/padding/image are all break-avoid, for them all to fit the page height).
So, you might have some DIV container around your images.
Try to disable padding/margins in the various style tweaks menu (might not be all in the same submenu).

**Comment by mergen3107** [comment]
@poire-z 
Thank you! It looks like this issue is related to `copt_` duplicates. I removed all custom directory defaults, opened the book anew and set margin, line spacing and css by hand in the UI. Gap is gone.

Thank you guys for your help! :)
