### ISSUE TITLE
Framabag no longer exists

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#7937]
I was getting issues when i tried to download articles from wallabag plug-in. When i visited framabag.org, it said that service no longer exists.
Does it mean I am no longer able to use wallabag plugin in koreader freely?

**Comment by Frenzie** [comment]
Indeed, they sent out emails that they were stopping I'm afraid.

**Comment by abdrau26** [comment]
@Frenzie 
What is possible solution please?

**Comment by Frenzie** [comment]
Their suggestions are here: https://alt.framasoft.org/en/framabag/

**Comment by abdrau26** [comment]
@Frenzie 
I could not found solution at mentioned link.
Framabag was free. Please help.
