### ISSUE TITLE
2021-07-05 nightly, part of cover image remains over text

### ISSUE THREAD

**Issue by rexkerr** [koreader/koreader#7938]
With the latest nightly, v2021.06-23-gf711f060_2021-07-05, part of the screensaver cover image remains over the text after opening the cover.

I have the screensaver set to the current book cover ("Use last book's cover as screensaver" option), and I have a line of text showing my contact info at the bottom of the screensaver (where the bottom statusline is, "Add message to screensaver" option).  The problem occurs whether using the power button or the sleep cover to wake the device, and can be reproduced on multiple books.

Changing pages, or opening the menu makes it to go away.

Tested on Kobo Clara HD.

![IMG_4084](https://user-images.githubusercontent.com/399845/124654188-1a4f7980-de53-11eb-94d3-4536318faffa.jpg)
![IMG_4083](https://user-images.githubusercontent.com/399845/124654194-1d4a6a00-de53-11eb-9f03-83c33564ce96.jpg)

**Comment by rexkerr** [comment]
After more testing, it seems to be related to the "Add message to screensaver" setting.  Changing to other screensavers still has the problem, but removing the message makes the problem go away.

**Comment by mergen3107** [comment]
I can confirm this on Kindle PW3 with screensaver message set.

**Comment by NiLuJe** [comment]
Yeah, I was mildly afraid of that, I'll look into it Soon(TM).
