### ISSUE TITLE
Selection boundary adjustment buttons not showing up in Boox Nova2

### ISSUE THREAD

**Issue by josereyesjrz** [koreader/koreader#7940]
* KOReader version: 2021-05 / 2021-06
* Device: Boox Nova2 (Android 9)

#### Issue

Cannot change selection boundaries in highlight or while copying to clipboard as demonstrated [in the wiki](https://github.com/koreader/koreader/wiki/Clipboard).

Screenshots:

1) Not working on Nova2:

<img src="https://user-images.githubusercontent.com/11931866/124683155-68d43680-de9a-11eb-9477-364a1526a387.png" width="400" />

2) Working on OnePlus 6 (LineageOS 18.1 / Android 11):

<img src="https://user-images.githubusercontent.com/11931866/124683238-95884e00-de9a-11eb-88c1-ea5509f9e2bb.png" width="400" />

Screenshots are from version 2021-05 (latest one in F-Droid) but same thing also happens with version 2021-06.

#### Steps to reproduce

1) Highlight a block of text
2) Tap highlighted text
3) Menu comes up without selection buttons

**Comment by hius07** [comment]
Is it pdf on the first screenshot? These buttons don't work at pdf.

**Comment by josereyesjrz** [comment]
Ah yes, the first one is a PDF. Thanks, should have checked first with multiple formats. Will close this issue.
