### ISSUE TITLE
FR: Zsync in the browse window

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#7944]
Hi

One has to have something open to to be able to grab a book from another device (tools/zsync/subscribe). Would not make sense that Zsync should also be available in the browse section of the app?

**Comment by dosimple** [comment]
As of v2021.06, Zsync is deprecated. Any updates to such components are unlikely, except removing them.

**Comment by gerroon** [comment]
I see. What is the reason behind it?

**Comment by Frenzie** [comment]
It's complex to maintain and it's mostly just sort of been there for years. It's discussed in part in https://github.com/koreader/koreader/discussions/7215

But the main reason is this:
https://github.com/koreader/koreader/issues?q=is%3Aissue+zsync
https://github.com/koreader/koreader/issues?q=is%3Aissue+zsync+is%3Aclosed

**Comment by Galunid** [comment]
Zsync has been removed and is no longer supported
