### ISSUE TITLE
Extra gray transition in inverted highlight

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#7945]
When highlighting a text with **INVERTED** option there is an unnecessary gray transition. I think this is because **LIGHTEN** highlight mode came first, **INVERTED** was built on it. Interesting thing is, highlight starts black under the finger. As the finger moves, it turns gray and when highlight finishes whole gray block turns into black again.

Instead of this unnecessary **NORMAL TEXT > BLACK > GRAY > BLACK** transition can we just stop at the first black (at least in this inverted mode). I mean the finger would just paint the highlighted text black as its final state. It already works like that when adding/removing a word from a highlight with **HIGHLIGHT EDIT** buttons, text turns inverted in one step instead of this middle gray.

This will make highlighting more fluent (and faster) by reducing this multi-step transition to just final one.

**Comment by poire-z** [comment]
80% related to your previous issue and our answers, like https://github.com/koreader/koreader/issues/7854#issuecomment-861800956 . Summary:
- the initial white > black > gray is eInk
- this gray is from crengine (dunno about PDF), which can't do black with inverted text color (at most, you could get black on black and text unreadable)
- the final gray > black is well, transitionning from crengine gray to your wished black.

**Comment by offset-torque** [comment]
I think there is a misunderstanding. If this is impossible then how HIGHLIGHT EDIT buttons can extend an INVERTED block without first going gray. New words just turn white on black. Is this only available on my device ?

For example when turning to a page with gray highlights it goes BLACK > GRAY as you say (eInk limitation). But when turning to a page with INVERTED highlights there is no middle gray. It just goes black.

What I am saying is obviously text can go INVERTED in one step (try HIGHLIGHT EDIT buttons on an INVERTED highlight if you don't believe me). Problem occurs when gray is introduced into the transition.

**Comment by offset-torque** [comment]
Exhibit A:
As you can see no GRAY > BLACK. Instant inversion:

https://user-images.githubusercontent.com/84420582/124909965-54538380-dfeb-11eb-982f-76bb8ae2e557.mp4

**Comment by poire-z** [comment]
> If this is impossible then how HIGHLIGHT EDIT buttons can extend an INVERTED block without first going gray

Because this is done by frontend.
Finger selection highlight drawing, while the selection is in progress, as long as you haven't released your finger, is done by crengine - so it is gray (with the limitation I mentionned). When you release your finger, crengine is done, gives the final coordinates of the boxes to frontend code, which draws these boxes black.
Boxes extension via the edit buttons aren't much dynamic, and can be done by frontend without involving crengine drawing.

May be we could get rid of crengine dynamic gray drawing and do all this with frontend. But I'm not much interested in spending time on fixing something that works OK (I understand your sensitive about that, but nobody has ever complained that much about it :)
(Also, the level of gray might help distinguishing the current selection from existing frontend-drawn highlights if your current selection overlaps with existing ones.)

**Comment by poire-z** [comment]
> May be we could get rid of crengine dynamic gray drawing and do all this with frontend

I think I had tried that in the past - it's easy to disable crengine drawing, but then, the current selection drawing is left to our ugly ReaderView which is mostly tailored for PDF stuff - and I remember I had a hard time making it work (= getting this bit of code even more ugly) and/or the quality of the results were worse (reminiscance of ugly black boxes and possibly some boxes unwantedly shifted by some pixels).

**Comment by offset-torque** [comment]
I understood the problem. Just curious, where does that moving black section under the finger comes from. I guess frontend turns it black then call crengine for extending while the finger is moving.

> I understand you're sensitive about that, but nobody has ever complained that much about it :)

My average highlight per book goes from ~100 to few hundreds on thick ones, probably that's why I am fed up with it :)

> this gray is from crengine (dunno about PDF), which can't do black with inverted text color (at most, you could get black on black and text unreadable)

This is the only way of getting rid of that gray and it is not feasible I can see.

I thought it might be fixable without much effort (I wasn't aware of frontend process) but as you said it needs big changes and, no need to fix if it's working.

Thanks for answers poire-z !
