### ISSUE TITLE
Dithering in CBZ

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7949]
* KOReader version: 2021-06-24
* Device: Kindle PW3 (FW 5.9.7)

#### Issue (?)
This is more like a question about image dithering in CBZ files (basically, muPDF, I guess).

In a CBZ file, which only consists of images (a manga book),  I can see very sharp gradual stripes of the gradient on some gradient-heavy images. Like the ones with sky going from light to dark shade,
I took a photo with a phone to show this, because it looks like the screenshot dithers it smoothly.
When I long tap the image to zoom, the Image Viewer dithers the image very nicely.
Please see attached photos and screenshots: 
[Dithering in CBZ.zip](https://github.com/koreader/koreader/files/6790548/Dithering.in.CBZ.zip)

Is it possible to make an option to force "the best" dithering in Reader mode? I suppose it must be computationally heavy, since it is disabled by default in Reader and enabled in Image Viewer.
(I remember similar dithering problems with Kindle's screenshots which where not properly converted with Image Magick beforehand...)

The issue is not so common, because most of the manga content is relatively sparse black-and-white structures and sketches.

Thank you!

**Comment by NiLuJe** [comment]
It's only available on devices with hardware dithering support (e.g., Kobo Mk. 7).

The reasoning being it's mostly useful for CBZs, and you probably should be building those yourself in the first place for best result, in which case, that creation pass is the perfect place to [do it right](https://www.mobileread.com/forums/showpost.php?p=3728291&postcount=17) ;).

The other reason is we can't easily guess whether content is purely image or not (well, I guess it's pretty obvious for a CBZ ^^), and the way it's implemented is currently a per-document toggle.

I don't rightly remember all the intricacies, but it might be technically feasible to allow SW dithering on that codepath, so this is not a "nope", it's just low on the todo list because not usually necessary as there are better spots in the workflow for it ;)

**Comment by mergen3107** [comment]
Thank you! :) 

> and the way it's implemented is currently a per-document toggle.

Where can I toggle this?

**Comment by NiLuJe** [comment]
You can't actually *see* the toggle outside of supported devices ;).

**Comment by mergen3107** [comment]
OK, I will doing batch-convert thingy before compiling CBZ in Kindle Comic Converter. Thank you for your support!

**Comment by mergen3107** [comment]
> It's only available on devices with hardware dithering support (e.g., Kobo Mk. 7).
> 
> The reasoning being it's mostly useful for CBZs, and you probably should be building those yourself in the first place for best results, in which case, that creation pass is the perfect place to [do it right](https://www.mobileread.com/forums/showpost.php?p=3728291&postcount=17) ;).
> 
> The other reason is we can't easily guess whether content is purely image or not (well, I guess it's pretty obvious for a CBZ ^^), and the way it's implemented is currently a per-document toggle.
> 
> I don't rightly remember all the intricacies, but it might be technically feasible to allow SW dithering on that codepath, so this is not a "nope", it's just low on the todo list because not usually necessary as there are better spots in the workflow for it ;)

@NiLuJe

Is there something that can be done still on my Onyx Boox Kon-Tiki 2 regarding built-in dithering?

I do my usual dither scripts but I found that the sharpness is quite deteriorated compared to undithered CBZ. So the point of having 300 dpi device is kinda moot now =\

**Comment by NiLuJe** [comment]
First and foremost: we wouldn't be doing any better than preprocessing (unless you're doing it wrong) ;).

That said, software dithering is *available* in the PDF codepaths nowadays (that may not have been the case at the time, I don't remember when this was implemented, but it used to be HW only for a long while for PDFs).

It just requires us actually being *able* to do software dithering *at all*, and that currently requires a grayscale framebuffer (i.e., not on Android) ;).

Doing it right would involve a lot of boring but technically simple extra complexity in the RGB(A) blitters (i.e., either dither three channels, or, better, compute a proper grayscale value first, dither that, and stomp on the three channels with it).

**Comment by NiLuJe** [comment]
> (unless you're doing it wrong)

Re: that

I had a lightbulb moment re-reading [an answer I wrote today](https://www.mobileread.com/forums/showpost.php?p=4300467&postcount=3) about similar queries.

Do *NOT* compress dithered images with a lossy codec (any of 'em). That will absolutely horrendously murder it (and you'll generate much bigger files than expected to boot).

**Comment by mergen3107** [comment]
> currently requires a grayscale framebuffer (i.e., not on Android)

Oh well, bummer :(

OK, I can then continue converting.
Yes, my output is still PNG, that Image Magick one-liner that goes recursively through folders (I think out User Guide has the link to it). 

(maybe unrelated, but Onyx’es NeoReader app has the forced dithering, although I don’t use it :D)

Thanks anyway! :D

**Comment by mergen3107** [comment]
Ok, nevermind. 

Some of the manga originals are in JPG. The script doesn’t change the output format at all, just takes whatever it is (jpg, png, gif) and passes through.
