### ISSUE TITLE
FR: case-sensitive file search in File Manager

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7950]
**Does your feature request involve difficulty completing a task? Please describe.**

I tried the 2012-06-26 nightly with RegEx and case-sensitive search and they both work great so far! Tested on Android.

**Describe the solution you'd like**

Can you please make and option for case-sensitive search in FM as well? This will be super useful for me, when I am not sure whether I “Stylized Every Word Except for Pronouns” in filenames of my 1000+ book collection, or not. 

**Describe alternatives you've considered**

Simply try another case if this one didn’t yield required results. 

**Additional context**
-

Thank you!

**Comment by NiLuJe** [comment]
IIRC, it's available as a legacy global defaults toggle. (Disabled by default because it absolutely murders search performance for a type of search that is already extremely slow).

**Comment by mergen3107** [comment]
OK! Thank you very much :)

**Comment by poire-z** [comment]
I guess that now that we have `[ ] Case sensitive` for full text search, we might have it for file search. Even if it's slow, it could help (searching for books by _John And_ would be give too much crap without it :)
Would probably need to use libutf8proc for proper lowercasing non ascii scripts.

**Comment by zwim** [comment]
For lowercasing we have already https://github.com/koreader/koreader-base/blob/93a57fd0e0e2ad4d69f6cc019935053b1405d4fd/cre.cpp#L3529 (which uses utf8proc)
Maybe we have to delete the second line
 ` CreDocument *doc = (CreDocument*) luaL_checkudata(L, 1, "credocument");`

A quick search in `filemanagerfilesearcher` shows some `string.lower` which would have to be changed to getLowercasedWord.

All in all this case sensitive search does not seem to be too complicated.

**Comment by poire-z** [comment]
> Maybe we have to delete the second line

Could be made a function (part of `cre_func` at the bottom) and not a method (`credocument_meth`).

But I'm not sure design-wise, it's ok to load the full libcrengine.so to just get a better lower() function :) (ok, it will probably be loaded for most users, and case sensitive search is rare). It would be better if it were a standalone ffi wrapper.

**Comment by zwim** [comment]
I have the thing ready (as part of cre_func), had to change a few bits in cre.cpp, readeruserhyph, util, filemangerfilesearcher.

But I want to test it and do a PR this afternoon.

**Comment by NiLuJe** [comment]
I'm, err, not a fan of pulling in CRe internals in the FM when we could simply use an FFI wrapper :/.

**Comment by Frenzie** [comment]
+1 on that one

**Comment by poire-z** [comment]
Fixed by #7956.

**Comment by mergen3107** [comment]
Thank you guys! I really appreciate your kind attitude and support :)
