### ISSUE TITLE
Global freeze when caching new books

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#7953]
* KOReader version: 2021-06-24
* Device: Kindle PW3 (FW 5.9.7)

#### Issue
I got about 3 freezes after uploading multiple books via SFTP.

#### Steps to reproduce
1) With WinSCP, move new books to Kindle
2) In KOReader FM, go the location of new books
3) While it is caching new books (Detailed View), try to interact in any way - tap Plus sign, scroll page, or long tap a new book.
4) Kindle freezes completely. SSH connection aborts. Only hard reset helps.

The issue is not consistent, I cannot reproduce it reliably.
On a second start, after going to new books' location, it caches things much faster.

##### `crash.log` (if applicable)
`crash.log` does not contain anything related to this. Is there a point to try verbose logs?

**Comment by mergen3107** [comment]
One thing to add is that I always do `Compact cache database`. Maybe that's the reason?

**Comment by NiLuJe** [comment]
Given the platform, I smell an OOM kill ;).

**Comment by mergen3107** [comment]
@NiLuJe 
OK, thanks :D I’ll be super patient with new books since this point. 

Unless there is a chance to “pause” auto caching and limit it to manual caching?

**Comment by NiLuJe** [comment]
Nope (short of showing less items per page ;D).
