### ISSUE TITLE
screen timeout options are grey out and can't setting on the android version run on sony DPT RP1

### ISSUE THREAD

**Issue by whmzsu** [koreader/koreader#7959]
* KOReader version: 2021-06
* Device:SONY DPT RP1

#### Issue
Screen timeout options are grey out and can't setting on the android version apk run on sony DPT RP1。So the suspend function config in the Sony offical app setting and android setting not work.

 The suspend function do work if i exit the koreader and run sony offical app.

**Comment by pazos** [comment]
Yep, that model is buggy and doesn't work without a wakelock. Feel free to submit a better patch if you find one ;)

**Comment by whmzsu** [comment]
Thinks for the reply, as it is the intended behavior,  I will close the issue. Thank you all for the great work of the app.
