### ISSUE TITLE
sleep mode and Font saving issue on kindle

### ISSUE THREAD

**Issue by cain916** [koreader/koreader#796]
First I have to say that I love this app. I installed it on my kindle paperwhite and find out some points that need to be improved.
1. press power button while reading, it does not go to sleep mode. But sleep cover works.
2. When I wake up the reader by opening sleep cover, the bottom of the screen remains unchanged. Unchanged area varies depending on progress bar. When progress bar is activated, the leftover of screensaver is bigger. If I tap on the leftover of screensaver or turn pageup pagedown, it will dispear.
3. long taping on menu item to set it as default does not work. When I open a new book that had never been opened before, Font, size and bold setting I made before were lost.

I hope the bug report helps to improve koreader.

**Comment by shezik** [comment]
Creating a dummy LIPC service named "com.lab126.kaf" with an integer property named "frameworkStarted" set to 1 can trick powerd into suspending normally. I've been writing a plugin for Kindle Touch but it's still at an early stage...but the concept is there. I also tried setting screen timeout to 0 seconds, but neither bind mounting t1_timeout file (requires restarting powerd and it'll lose the current state) or tweaking touchScreenSaverTimeout property of powerd (doesn't work at all) was a good idea.

**Comment by NiLuJe** [comment]
I mean, you do you, but I still don't get the obsession with trying to get rid of the framework ;).
