### ISSUE TITLE
FR: [text to speech in look up window]

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#7975]
Can you please add tts for look up window? It  would be good for non-native to listen word for which he is using dictionary.
Thanks

**Comment by pazos** [comment]
@abdrau26: TTS is something very specific of Android and thus out of scope.

You can workaround yourself this limitation by using a 3rd party dict app on android. IIRC all of the supported apps have TTS as an option. At least Aaard2 and Goldendict are able to do that on their own.

Maybe switching between apps is too annoying on e-ink or you loose the "focus" of KOReader lookup window, but it is the best you can get without changing your reader program entirely :)
