### ISSUE TITLE
FR: Time based night mode

### ISSUE THREAD

**Issue by gerroon** [koreader/koreader#7977]
Hi

having a time based dark mode will be super useful. For instance KR will turn the dark mode after 10pm or whatever the user sets it to be. And the other times the mode will be disabled, obviously it can still be enabled and disabled manually.

I am thinking that the user sets the time range for the night mode, and it will be just the regular display the other times.

thanks

**Comment by NiLuJe** [comment]
Pretty sure there's an existing FR for that, and it's *old*. Which should tell you something ;) (hint: PRs welcome).
