### ISSUE TITLE
Wrong date in onetime migration?

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#7979]
* KOReader version: 2021.06.29
* Device: all

#### Issue
https://github.com/koreader/koreader/blob/7eea2ae7cd8b05ae6a77dc89e7033c7d07cfe9fe/frontend/ui/data/onetime_migration.lua#L267-L268

Is there one 0 too much?

**Comment by NiLuJe** [comment]
Yes, there is.

Fortunately the CURRENT constant is correct, so this hasn't actually screw up everyone forever, this just trips that one again and again.
