### ISSUE TITLE
progress sync will crashing when cannot connect network

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#7996]
when I opened progress sync plugin,and config sync per pages, but when the network isnot connected or koreader-sync server endpoint cannot reached,the app will crashed,I mean when plugin cannot reached server,it's a better way outputing a message than crash the app,I am using android app arm 2021.06 version,and it occurs in 2021.05.I hope it can be repaired

**Comment by Frenzie** [comment]
https://github.com/koreader/koreader/issues/7997
