### ISSUE TITLE
progress sync will crashing when cannot connect to network

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#7997]
when I opened progress sync plugin,and config sync per page, but when the network isnot connected or koreader-sync server endpoint cannot reached,the app will crashed,I mean when plugin cannot reached server,it's a better way outputing a message than crash the app,I am using android app arm 2021.06 version,and it occurs in 2021.05.I hope it can be repaired

**Comment by Frenzie** [comment]
Please follow the template so we don't have to ask for device etc.

**Comment by dandelions** [comment]
Thank you very much for your attention.but what's template
meanwhile,the crash mean the android app is holding connect to server,then i can operate nothing but killing background process.i think if app cannot connecting to server,app will show a message instead to connect to server all the way

**Comment by Frenzie** [comment]
The template for reporting a bug.

https://github.com/koreader/koreader/issues/new?assignees=&labels=&template=bug_report.md&title=

Also what do you mean by crash? Does the app close itself or does Android say it's not responding?

**Comment by dandelions** [comment]
Yeah,crash means the app isnot ressponding,i can do nothinig but kill backgroud process

**Comment by Frenzie** [comment]
Maybe @IcedEagle or @Galunid is interested in looking into it. That being said, freezing for 30 seconds or whatever is currently unavoidable without Turbo in many situations.

**Comment by Galunid** [comment]
@dandelions Please post
* Device
* Android version

**Comment by dandelions** [comment]
device:vivo iqoo neo5
android version:Android 11

**Comment by IcedEagle** [comment]
@dandelions Do you get the Android system pop-up to either force quit the app or wait? If you select Wait, does the app respond again after like 30 or 60 seconds?

**Comment by dandelions** [comment]
I tried again,the phenomenon did not appear again,Maybe it's myfault or my phone's config wrong,I will pay attention to the issue soon,thank you for your attention to the issue
