### ISSUE TITLE
regression: "no reader engine for this file or invalid file"

### ISSUE THREAD

**Issue by anarcat** [koreader/koreader#7998]
* KOReader version: 2021.07
* Device: Kobo Clara HD

#### Issue

Opening *any* book gives me the error message:

```
no reader engine for this file or invalid file
```

I found [this forum post](https://www.mobileread.com/forums/showthread.php?p=4140381) which suggests using a long-press to try other readers. The long press actually crashes koreader completely sometimes (see below), but when it actually works, the `open with` doesn't fix the issue: neither Cool reader or mupdf can load the file correctly.

#### Steps to reproduce

Upgrade to 2021.07. Open any book.

##### `crash.log` (if applicable)

Cannot find a `crash.log` file. Here's a screenshot of the long-press crash, which might be a different issue.

![signal-2021-07-20-221155](https://user-images.githubusercontent.com/796623/126419665-bae6cb38-cf5c-4a3b-929e-d6cdbdfb7c4f.jpeg)

#### Notes

I understand such a bug report might be very frustrating because I can't imagine you can reproduce it out of the box... Surely most people using 2021.07 right now can load ebooks fine. But it seems I cannot load *any* with that latest version, which I am very, very surprised about. Koreader releases have been rock solid for a long time now and that's a huge surprise to me as well. I'm going to try 2021.06 next to see if I can reproduce.

**Comment by anarcat** [comment]
looks like this was a fluke, a bad install or something... downgrading to 2021.05, worked, so did 2021.06, and... 2021.07... in other words, it works after reinstalling, sorry for the noise!

**Comment by Frenzie** [comment]
Glad you fixed it. Overwriting in case of file corruption is usually a good thing to try, though I'm not sure how that could've happened.
