### ISSUE TITLE
Bad interaction between KOReader Night Mode and native Dark Mode

### ISSUE THREAD

**Issue by oldman63** [koreader/koreader#8001]
* KOReader version: latest unstable (v2021.07-3-gb31b7728_2021-07-20)
* Device: Kindle PW4 and Kindle Oasis 3

#### Turning the night mode on / off in the “Gesture Manager / Device” section does not work properly if you exit the KOReader and turn on the Dark mode in the Kindle Settings.

Night Mode on => OFF
Night Mode off => ON

When the Kindle Dark Mode is off, the operation is perfect.

Night Mode on => ON
Night Mode off => OFF

**Comment by NiLuJe** [comment]
We don't keep track of native settings. The only thing that tracks happens to be the frontlight level, but that's more by coincidence than by design.

This would be akin to asking us to default to the same font size or something ;).

**Comment by oldman63** [comment]
Ok.

**Comment by NiLuJe** [comment]
This might behave better on current nightlies as we now handle nightmode int he exact same way as the native system, and we restore the startup state on exit. (Stuff might be wonky if NM is disabled in KOReader, though).
