### ISSUE TITLE
Why koreader needs to change system settings ? (question)

### ISSUE THREAD

**Issue by RandomPenguin1778** [koreader/koreader#8005]
Hi !
i was installing koreader from f-droid but when i look at permissions i saw 'changing system settings' . why does koreader need to change settings ?

**Comment by Frenzie** [comment]
I take it you're on Android <5 or <6 or something? I believe you should only see a request to change system settings when you try to change the brightness through the program, except on older versions where it was all or nothing.

**Comment by Frenzie** [comment]
It's fairly useless on phones but it has utility on (some) Android ereaders.
