### ISSUE TITLE
FR: Execute gestures on startup/close/(certain time)

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8020]
**Does your feature request involve difficulty completing a task? Please describe.**
On KOReader start the frontlight level and warmth are often set to random values. Especially after restarting my device. (Tolino)

**Describe the solution you'd like**
I would like to have the possibility to execute a gesture at KOReader start/close. 
These gestures could also be used to start KOReader with a defined state (e.g. set Rotation always to Portrait, Nightmode ...) if a user don't want to start with the last state. Or when starting KOReader show the TOC, open the calculator ...

(Nice to have, but not necessary: If it would be possible to execute a gesture at certain times (of course only if KOReader runs), one could make his auto frontlight :) ... )

**Describe alternatives you've considered**
A fishy startup script: setting frontlight values and tinker with settings.reader.lua.

**Comment by pazos** [comment]
> On KOReader start the frontlight level and warmth are often set to random values. Especially after restarting my device. (Tolino)

That's a platform thingy. On normal android devices there's a fallback (system wide brightness level). For devices whose light controller don't have a fallback it is ok to save/restore brightness or warmth to/from settings.

Everything should be in place, just need to interface with the frontend and to add the code to save each time the frontlight is changed and to restore on Device.init

**Comment by zwim** [comment]
Yes, that would solve the light issue, but not issue to start Koreader in a defined state ( landscape portrait ).

**Comment by pazos** [comment]
Then nothing android specific :)

**Comment by zwim** [comment]
Right, not firmware not Android specific.

**Comment by yparitcher** [comment]
The power of [Dispatcher](https://github.com/koreader/koreader/blob/master/frontend/dispatcher.lua) to the rescue ;)

You can make a plugin based on profiles or gestures that runs on init or when the ReaderUI is loaded (via a `postReaderCallback`) whichever one works better 
It can then set a flag so it only runs once.

**Comment by zwim** [comment]
Thank you. I will look into it when I am back from holiday (in three weeks ).
