### ISSUE TITLE
Pocketbook 616 Frontlight Widget Inoperable

### ISSUE THREAD

**Issue by Arcansiel** [koreader/koreader#8023]
* KOReader version: 2021.07
* Device: Pocketbook 616W

#### Issue
Pocketbook 616 does not have touchscreen, and Frontlight Widget does not take that in account. If you press on it the only way out is through forcefully closing application, as it does not react to button presses from device.

#### Expected behaviour
Frontlight Widget should work correctly with devices without touch screen.

#### Steps to reproduce
Open Frontlight Widget on device without touchscreen.

**Comment by Frenzie** [comment]
Fixed in #11376.

**Comment by Commodore64user** [comment]
> Fixed in #11376.

Another open ticket that should be closed.

**Comment by Frenzie** [comment]
A minor mistake in the PR (should've written fix/fixes/close/closes without adding issue)
