### ISSUE TITLE
unable to input conection data for local calibre library

### ISSUE THREAD

**Issue by L0ric0** [koreader/koreader#8024]
* KOReader version: v2021.07
* Device: Kindle K4

#### Issue

when trying to input the data to connect to a local calibre library it is possible to input the hostfiled but as soon as the on screen keyboard is closed it is impossible to open it again and the keyboard has to be closed to switch to all other fields.

#### Steps to reproduce

use a NT device and try to connect to a calibre library with non default setings

**Comment by pazos** [comment]
pinging @comphilip, is this (multiinput on NT) fixed?

**Comment by comphilip** [comment]
@pazos It is fixed. 

1. Screen keyboard hides on `back` pressed. 
1. Can move focus with array keys
1. Screen keyboard shows again on textbox focused

**Comment by pazos** [comment]
Thank you for the explanation. Closing this ticket then :)
