### ISSUE TITLE
epub:type="endnote" doesn't trigger on-page endnotes

### ISSUE THREAD

**Issue by johnbeard** [koreader/koreader#8033]
* KOReader version: 2021.06-27
* Device: Kobo Clara/Emulator

#### Issue

Footnotes with the `epub:type="doc-endnote"` don't trigger in-page footnotes. `epub:type="doc-rearnote"` does.

According to https://idpf.github.io/epub-vocabs/structure/#endnote `rearnote` is deprecated and `endnote` is the replacement. I have seen `endnote` used on a real document. 

#### Steps to reproduce

Open the attached file, observe only one footnote shown on the page, despite two being defined.

[endnote.epub.zip](https://github.com/koreader/koreader/files/6889196/endnote.epub.zip)
<img width=400 src="https://user-images.githubusercontent.com/5386578/127239267-57561473-6525-4389-910f-be17e925efb7.png" />

I _think_ this could be resolved by just adding to the selectors here: https://github.com/koreader/koreader/blob/acfc5eec2b62196104f779cb7b57b37c80dc01ac/frontend/ui/data/css_tweaks.lua#L731-L741

**Comment by poire-z** [comment]
> I think this could be resolved by just adding to the selectors here: 

Yes, probably (in the 2 similar sections, normal + small).

(There's also a bit about role == doc-rearnote in base/cre.cpp for detecting links to foonotes for popup footnotes that we'll have to update too for consistency.)
