### ISSUE TITLE
FR: Long press on Physical buttons

### ISSUE THREAD

**Issue by Arcansiel** [koreader/koreader#8035]
**Does your feature request involve difficulty completing a task? Please describe.**
Current implementation does not explore ability to add actions to button long-press. This limits number of actions that can be assigned to physical buttons, and this is important for devices without touch-screen. For example on Pocketbook 616, which has d-pad and Previous/Next page buttons (which potentially should be enough for seamless navigation) horizontal d-pad direction is used as back button (left button of d-pad) and menu button (right button of d-pad). This limits direction of movement to left-to-right on any menu items (as left button of d-pad is unconditionally bound to back button).

**Describe the solution you'd like**
If there was an ability to assign long-press functions on buttons, this would allow to assign Back and Menu buttons to long-press calls and allow d-pad to function as directional control in all modes of operation. For example Back button can be bound to long-press of Previous page button, and Menu to the long press of Next page button. This would also allow to solve problem with setting default values for reader (currently you need to long-hold value on touch-screen to set it as default, however it is not possible with non-touch devices) as long-press on Press button can be processed.

**Describe alternatives you've considered**
Keymapping, maybe? However this does not solve the problems with hard-coded reaction to the button press with no ability to override it in any meaningful way.

**Additional context**
Mostly would be useful for devices without touch-screens.

**Comment by NiLuJe** [comment]
Possibly easier/harder if the device generates KeyRepeat events ;p. Regardless, would need some more state tracking between KeyPress and KeyRelease.

**Comment by poire-z** [comment]
Many improvements for NT recently added by #8859 and followups PRs.
(Including support for Hold gesture - dunno if it's real long-press support or just workaround, but it surely the best that was possible :) so closing.)

**Comment by sdasda7777** [comment]
Hi, I'm really sorry, but I am struggling to find any resources on how to bind an action to a long press of a physical button. Could you please elaborate on whether it should be currently possible?

**Comment by NiLuJe** [comment]
It's not.

**Comment by sdasda7777** [comment]
Ah, I see, thanks for the reply. Does that mean this feature is not planned, or did it perhaps just gotten hang up on something?

**Comment by NiLuJe** [comment]
Nobody's been working on it, so, yeah, technically unplanned?

What was mentioned above is specifically tied to one set of navigational widgets, and I have no idea how it's been implemented in practice (because I don't care ;p), but it is definitely not generic. Might be useful as a reference, but that's it.

**Comment by NiLuJe** [comment]
>  I have no idea how it's been implemented in practice

Oh, I see. It actually just allows binding a dedicated key to the generate a "Hold" even on the currently focused item. So, very much not generic, and very much not applicable to anything generic; it's effectively unrelated to what you're thinking of ;).

**Comment by NiLuJe** [comment]
> Possibly easier/harder if the device generates KeyRepeat events ;p. Regardless, would need some more state tracking between KeyPress and KeyRelease.

And would also need to be extremely optional, because we currently act on Key*Press*, not KeyRelease, and I'd be very upset about changing that (because it would tank latency. Reasoning somewhat similar to double-taps being disabled by default).
