### ISSUE TITLE
FR: Vietnamese input method

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#8041]
I need Vietnamese input method. Hope this will be available soon.

_Originally posted by @vietchovui in https://github.com/koreader/koreader/issues/1938#issuecomment-890450478_

**Comment by poire-z** [comment]
Some initial work that needs to be continued in #8294.

**Comment by weijiuqiao** [comment]
I can try and add a restricted Telex IME where the modifying letters can’t be separated from the modified ones. It may not be the most ideal but certainly better than no keyboard at all? 
And someone with more knowledge of Vietnamese syllable structures can always  replace it with a fully fledged one later?

**Comment by poire-z** [comment]
Implemented by #9589.
