### ISSUE TITLE
Night mode on Kobo Aura turn back to normal mode automatically after a long sleep

### ISSUE THREAD

**Issue by supakdee** [koreader/koreader#8043]
* KOReader version: v2021.07
* Device: Kobo Aura (Kobo_dragon)

#### Issue
Night mode on Kobo Aura turn back to normal mode automatically after a long sleep

#### Steps to reproduce
1) Enable night mode
2) Put the device into sleep longer more than 5 mins
3) Activate the device
4) The device wake up in the normal mode

Need to disable / enable night mode to get back to night mode.

**Comment by NiLuJe** [comment]
The Aura's kernel is buggy, nothing we can really do about it without extreme hackery.

**Comment by NiLuJe** [comment]
(Nightmode actually used to *crash* early Aura kernels, so, consider yourself lucky it's only quirky ;)).
