### ISSUE TITLE
Cover image plugin does not work on PocketBook Touch Lux 3

### ISSUE THREAD

**Issue by vita5656** [koreader/koreader#8046]
Cover image plugin saves cover images as bmp file with bit depth 24. But Pocket Book Lux 3 will only process images with 8pp bit depth as an off logo. It ignores images with bit depth higher than 8.
Would it be possible to modify the plugin to have an option "use 8 bit depth"?
Everything else works fine.

**Comment by LucyOne** [comment]
Do you mean the Touch Lux 3 or the Touch HD3? I don't have any problem with the cover image as an off logo on my Touch HD3. Running one of the latest nightlies.

**Comment by vita5656** [comment]
I mean Touch Lux 3. I apologize for the mistake. :-) If I upload an image with 8pp bit depth to the "Off logo" directory and select it as off logo, it works. If I upload the same or any other image with 24pp bit depth, the display flashes and shows the standard "PocketBook" screen instead of the selected off logo.

**Comment by Galunid** [comment]
Pinging @zwim

**Comment by zwim** [comment]
I will look into in on the weekend.

**Comment by zwim** [comment]
@vita5656 : Would a 8bpp grayscale image be enough?

**Comment by vita5656** [comment]
8bpp grayscale or color, it doesn't matter. What matters is 8bpp. I've tried 8bpp color (256 colors) and 8pbb grayscale and they both work. Thank you in advance.

**Comment by vita5656** [comment]
Today's nightly build v2021.07-47 includes a new version of the plugin, and it works with the "grayscale BMP" option on PocketBook Touch LUX 3 like a charm. :-)
Thank You.
