### ISSUE TITLE
FR: Option to go back to last position in bookmarks

### ISSUE THREAD

**Issue by fherrera124** [koreader/koreader#8047]
**Does your feature request involve difficulty completing a task? Please describe.**
When I'm consulting my bookmarks, when I follow one item on my book, later when I want to go back to the bookmarks view, I have to click several times to go back to the exact position in bookmarks. Let say there are multiples pages in bookmarks of book X, and I'm studying my notes, currently, in position 6/20 of bookmarks, I click an entry, visit the position on the book, now I want to go back to page 6 of bookmarks.

**Describe the solution you'd like**
Simply an arrow to go back to page x of the bookmarks of the current book.

**Describe alternatives you've considered**
Maybe add in the menu of the highlighted word an option to go to the exact page in bookmarks

Sorry for my poor English

**Comment by hius07** [comment]
@LTHPKBTE, I am not sure I understand your request correctly.
Regarding the starting post: to find the bookmark connected to the current page of the book, in the bookmark list tap the upper left icon and select "Book current page".

**Comment by LTHPKBTE** [comment]
@hius07 Sorry, what I meant was "the bookmark closest to the page I'm currently reading".
I wish there was an option to make the bookmark page show the closest one to the current page, like table of contents.

**Comment by hius07** [comment]
Got it, thanks.
