### ISSUE TITLE
FR: Larger buttons for "Go to page" & "Go to letter"

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8051]
**Does your feature request involve difficulty completing a task? Please describe.**
In most languages the phrases "Go to page" and "Go to letter" (in "Enter page number or letter" dialog window, in file browser, or in the dialog window of "Go to page" option of Navigation menu) are longer when translated. Since the buttons for these phrases are small enough, in order to fit the English text, only the first words appear in the translations (i.e. only the translation of the verb "Go" and sometimes of the word "to") and not the translation of the words "page" and "letter", which are more important.

**Describe the solution you'd like**
I was thinking about larger buttons for these phrases, so that the text could be in two lines.

Thank you!

**Comment by hius07** [comment]
Two-row-buttons seem a little bit inconsistent with the current design.

What about changing the wordings?

<kbd>![1](https://user-images.githubusercontent.com/62179190/128529534-9f332334-f5f1-4383-9422-276173f35680.png)</kbd>

Or having the buttons in two rows by two buttons (`Cancel` to be double-wide)?

**Comment by ichnilatis-gr** [comment]
Changing the phrases to words is a solution, but I think that the phrase "Go to page" is  also used in other instance and it will not make sense there.

The second solution may be good. We could try it.

**Comment by hius07** [comment]
And one more solution:
to leave one button only `Go to page`, and go to letter on hold of this button.

**Comment by ichnilatis-gr** [comment]
It sounds a bit complicated...

**Comment by hius07** [comment]
<kbd>![1](https://user-images.githubusercontent.com/62179190/128596073-9f46b3a4-2195-42eb-a844-29759b5d9b3d.png)</kbd>

**Comment by hius07** [comment]
Let's have more opinions from the users.

**Comment by poire-z** [comment]
No strong opinion, but I'm fine with the last 2 screenshots. (We prefer to have a verb for the buttons I think.)

I feel many buttons text might be truncated with some languages translations. Dunno if we could have some better strategy than truncation in Button itself, like use a smaller font size + 2 lines - no idea how ugly this would look :)

**Comment by NiLuJe** [comment]
@poire-z: It's definitely truncated in French if you want to check ;p.

**Comment by ichnilatis-gr** [comment]
> 
> 
> ![1](https://user-images.githubusercontent.com/62179190/128596073-9f46b3a4-2195-42eb-a844-29759b5d9b3d.png)

Similar change has to be done in the "Go to page" window, where there also are three buttons, "Cancel", "Skim" and "Go to page".
