### ISSUE TITLE
A way to reorganize (reorder) the plugins menu. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#8055]
I was thinking about about a feature that allows us to reorder the plugins menu. 

![IMG_20210807_221631_949](https://user-images.githubusercontent.com/70109540/128611633-ede56ca9-9ee3-4146-bc00-431fb569c9bf.jpg)
I think I can (turn off) a plugin (I suppose, didn't try it) but for example I use reading statistics more frequently, so I would put it in the first line.

**Comment by Frenzie** [comment]
That's already possible. Create a file named `reader_menu_order.lua` in the settings dir.

Inside, you can reorder these lines:
```
local order = {
    tools = {
        "read_timer",
        "calibre",
        "evernote",
        "statistics",
        "progress_sync",
        "move_to_archive",
        "wallabag",
        "news_downloader",
        "send2ebook",
        "text_editor",
        "qrclipboard",
        "profiles",
        "----------------------------",
        "more_tools",
    },
    more_tools = {
        "auto_frontlight",
        "battery_statistics",
        "synchronize_time",
        "keep_alive",
        "doc_setting_tweak",
        "terminal",
        "----------------------------",
        "plugin_management",
    },
}

return order
```

**Comment by Zeyadas** [comment]
Worked like charm, thanks.

**Comment by Zeyadas** [comment]
What if I deleted the reader_menu_order.lua , will the menu back to default?

**Comment by Frenzie** [comment]
If you delete `settings/reader_menu_order.lua` then the default will be used, yes.

**Comment by mergen3107** [comment]
@Frenzie 
Thank you so much! I didn't know this
