### ISSUE TITLE
it only works when I turn the screen on and off

### ISSUE THREAD

**Issue by Skyggen7** [koreader/koreader#8064]
* KOReader version: KOReader 2021.07 "Box Jumper"
* Device: Nabuk Regal HD- android 4.4.4

#### Issue
the app freezes when it starts, the way it progresses is by turning the screen off and on, then when executing an action, the screen freezes again until I turn the screen off and on again where it "updates" and I can see the action that do before
#### Steps to reproduce
-open de app (it freezes on the logo2
-turn off the screen with block button
-turn on in the same way
the app shows what it should and freezes again

![photo_2021-08-11_00-12-55](https://user-images.githubusercontent.com/9299588/128968814-06de8dc4-2ade-4c1c-b613-9fca69fc14d4.jpg)
![photo_2021-08-11_00-12-53](https://user-images.githubusercontent.com/9299588/128968817-ae0f46bd-2ffd-4da4-8711-b7f59cc88487.jpg)

https://user-images.githubusercontent.com/9299588/128969055-4f851c6a-ed39-4182-9c91-1e82d693f6bc.mp4

**Comment by pazos** [comment]
That's a buggy FW, not our bug.

Have a look at https://github.com/koreader/koreader/issues/4551, where we try to workaround quirks of different eink devices.

I labeled this ticket as "can't fix" as we rely can't. But you (or other device owner) might. Feel free to tinker with :)
