### ISSUE TITLE
Android: OCR files not recognized

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#8068]
* KOReader version: 2021.07 and a [test apk](https://github.com/koreader/koreader/issues/4551#issuecomment-898294641)
* Device: Onyx Boox Kon-Tiki 2 (Android 10, rooted)

#### Issue
OCR files are not recognized. When highlighting in a PDF file, it suggestes to download them.

#### Steps to reproduce
1) I put `eng.`, `rus.`, `kaz.`, and deu.traineddata in `/storage/emulated/0/koreader/data/tessdata` directory. These files are from [here](https://github.com/tesseract-ocr/tessdata/tree/3.04.00), as per Wiki. 
2) `defaults.persistent.lua` from my Kindle PW3 setup in `/data/data/org.koreader.launcher/files/` did not work. So I had to rename it to `defults.lua`. It contains:
```
DKOPTREADER_CONFIG_DOC_LANGS_TEXT = {"English", "Deutsch", "Russian", "Kazakh"}
DKOPTREADER_CONFIG_DOC_LANGS_CODE = {"eng", "deu", "rus", "kaz"}    -- language code, make sure you have corresponding training data
```
3) These options are shown fine in the bottom menu after KOReader restarts.

4) However, with `Forced OCR` on, when highlighting it complains that there is no OCR data and suggests to download. Also, it looks like it still highlights defined text boxes (which are wrong). The PDF document is a German language learning book.

5) I tried to put tessdata into `/data/data/org.koreader.launcher/files/data/`, because some settings files are only here, like cr3.ini and css files which I have my own. It didn't work neither. 

##### `crash.log`
I cannot create a crash log from `Report a bug`. Most probably there is [something wrong](https://github.com/koreader/koreader/issues/4551#issuecomment-897117608) with logcat on the device. However, I have access to adb, so I can run logcat and pidcat. They don't show any specific info, though. `python pidcat.py` shows the running log, but `python pidcat.py org.koreader.launcher` is empty.

**Comment by pazos** [comment]
> 1. I put eng., rus., kaz., and deu.traineddata in /storage/emulated/0/koreader/data/tessdata directory. These files are from here, as per Wiki.

Right. That's the valid prefix.

> 2. defaults.persistent.lua from my Kindle PW3 setup in /data/data/org.koreader.launcher/files/ did not work. So I had to rename it to defults.lua. It contains: ...

Wrong. Put default.persistent.lua in `/storage/emulated/0/koreader`. **Do not override anything in `/data/data`**. Normal users cannot write there.

> 5.  tried to put tessdata into /data/data/org.koreader.launcher/files/data/, because some settings files are only here, like cr3.ini and css files which I have my own. It didn't work neither.

Please don't touch `/data/data`.

Do the following steps:

1. Uninstall the program.
2. Remove (or rename) the folder `/storage/emulated/0/koreader`.
3. Install the program again.
4. Put your tessdata and your defaults.persistent.lua in the right places.
5. Try to reproduce the issue again. If you can repro on android but not on your Kindle there's something fishy here. Not sure if is fixable or not. I don't use tessdata or pdfs in general :p

**Comment by mergen3107** [comment]
@pazos,
I did everything as you suggested.
defaults.persistent.lua worked! However, I still can reproduce this issue on Android, while Kindle is perfectly fine with the new German OCR data.



> Please don't touch `/data/data`.

I only need to put my cr3.ini and two css files which I use. Should I still avoid this?

**Comment by pazos** [comment]
> I only need to put my cr3.ini and two css files which I use. Should I still avoid this?

Yup. `cr3.ini` will be murdered on each new update. If you want to push stuff to `/data/data` use data migration. See https://github.com/koreader/koreader/commit/699ee3efc1fcebe022ec269f97362eeee0fd87bf

You can achieve the same with shell scripts but looks overkill for placing a few files there.

**Comment by mergen3107** [comment]
> Yup. `cr3.ini` will be murdered on each new update.

Is this also true for Kindle? If so, then I was using the default cr3.ini all along...

For css I should probably stick to Style Tweaks, since there are saved in `settings.reader.lua`, right?



Thank you for pointing to data migration! I'll have a look.

> You can achieve the same with shell scripts

That's actually fine by me, I use TotalCMD with script shortcuts on the bottom panel (i.e. to enable adb).

**Comment by NiLuJe** [comment]
> > Yup. `cr3.ini` will be murdered on each new update.
> 
> Is this also true for Kindle? If so, then I was using the default cr3.ini all along...
> 

Yup.

> For css I should probably stick to Style Tweaks, since there are saved in `settings.reader.lua`, right?
> 

Stock ones, yeah, and custom ones live somewhere in settings/, too ;).

**Comment by mergen3107** [comment]
Here are my attempts to "catch" when this "OCR not available" window appears:
[crash.log](https://github.com/koreader/koreader/files/7021529/crash.log)

I am not sure the crash.log is of any good use, this is what I did:
1) Enabled dev + verbose logs
2) Restarted KOReader
3) Opened a PDF book in English, set`EN` and enabled `Forced OCR` in the bottom menu.
4) Tried to select random text. However, it sticks only to a few fixed phrases which are far from the touch input and sends them to Dictionary without spaces. You can see them in the log as `OCRed word:` and those words together without spaces. There are about one such phrase set for each paragraph.
5) Opened a PDF textbook for learning German. Tried to select a text, but first time it again found some long phrase and sent it to Dictionary. This is `OCRed word: Wassollninatun?Wastutsiewirklich?Sprechensie.`. Then I tried again and it complained that there are no OCR files. 

Is there another way I should try to log this?

**Comment by mergen3107** [comment]
If I disable `Forced OCR` then I am able to interact with the predefined text boxes in the English PDF.

**Comment by Frenzie** [comment]
Well yeah, that's logical? You're explicitly telling it to ignore them if you do that.

**Comment by mergen3107** [comment]
Yes, I just reported it for completeness :D To show that at least `Forced OCR` "off" is working fine.

**Comment by mergen3107** [comment]
FWIW, local dictionaries in `koreader/data/dict/` get recognized and work well. So `data/` directory has no issues with permissions

**Comment by pazos** [comment]
sdcard is mounted noexec since the beginning, so you can't run binaries from there.
Also newer versions of android introduced more restrictions based on SELinux. That includes the inhability to run binaries from internal files dir (/data/data/org.koreader.launcher/files).

For each new restriction we make a workaround. A few were needed to get dicts working on new android versions (replace `tar` binary with apache commons, move `sdcv` to `nativeLibraryDir` and link it at runtime...)

What we need here is a proper bug report with steps to reproduce and logs. I don't use OCR so I have no idea if that leaves traces on system log. If that's not the case then adding a few log statements shouldn't hurt.

Catching the whole system log with `pidcat org.koreader.launcher` and verbose logs enabled should, at least, give us a hint if there's something wrong with the android framework.

**Comment by mergen3107** [comment]
> Catching the whole system log with `pidcat org.koreader.launcher` and verbose logs enabled should, at least, give us a hint if there's something wrong with the android framework.

Thank you! I'll get working on it...

**Comment by mergen3107** [comment]
Here is the `pidcat` while I did (from around line 557 onwards):
- open KOReader which was closed before
- Go to bottom menu, select `DE` and `Forced OCR` on
- Close bottom menu, try to select something
- Got the OCR notification popup that I need to download files
- closed popup
- exit KOReader from top menu

Dev and verbose logs were on.

[pidcat_ocr_1.txt](https://github.com/koreader/koreader/files/7086898/pidcat_ocr_1.txt)

**Comment by mergen3107** [comment]
Maybe there is a problem with the file?
Here is just one page extracted via Foxit Phantom PDF. I tried OCR and pidcat on this page in the book.
It is a scanned page.

[one page.pdf](https://github.com/koreader/koreader/files/7086910/one.page.pdf)

**Comment by pazos** [comment]
No idea. But nothing crashed there:

```
                         V   in hold state...
                         V   hold_release detected in slot 0
                         V   adjusted ges: hold_release
                         V   hash ocrword|/storage/emulated/0/Books/DEUTSCH/Schritte 4/Hueber Schritte 4 - Kursbuch & Arbeitsbuch.pdf|121013605172
                         V   word
                         V   OCRed word:
                         V   ImageWidget: _render'ing resources/icons/mdlight/notice-info.svg 77 77
```

**Comment by mergen3107** [comment]
OK, thank you!

As for system wide logs, is it logcat? Or something more verbose? With some specific options maybe?

Meanwhile I'll just OCR the book with desktop k2pdfopt

**Comment by pazos** [comment]
@mergen3107: please do not close opened bug reports that might affect other users, unless they're duplicated :) If you're not interested anymore you can press the "unsuscribe" button. I do it plenty of times :D

**Comment by mergen3107** [comment]
@pazos 

Sorry about that! Just seen you ping.

Moreover, I start to believe this issue is also reproducible on Kindle Scribe. 

I'll try to get more logs and include more logger.dbg messages to retrieve values of functions, but OCR right now is not really usable in my PDFs.

PDFs are LaTeX generated by publishers, so they definitely have a text layer. This text layer is selectable OK when OCR is turned off In bottom menu. However, if I enable OCR and start long tapping words, the selection appears to be way off from the location of the long tap.

**Comment by benoit-pierre** [comment]
NOTE: the Lua code can't differentiate between: OCR was not initialized successfully (missing language data) and OCR failed (but initialization was successful). So the message about missing language data can be deceptive.

**Comment by Frenzie** [comment]
That's an interesting point. In my experience I've always see nonsense rather than failure but maybe it's different with newer versions?

**Comment by benoit-pierre** [comment]
It's true that with 2024.04, it tends to always return something, but you can still get some instances where the returned OCR text is empty.

**Comment by mergen3107** [comment]
@benoit-pierre 
Thanks! Yeah, I believe in this ticket I was chasing down why the string is empty, but got lost in the end. https://github.com/koreader/koreader/issues/11263

**Comment by mergen3107** [comment]
Closing this in favor of the ticket above.

If this OP is reproducible by someone (indeed OCR files not being recognized, that is), please re-open.
