### ISSUE TITLE
FR: Android - Allow adding css from user accessible storage

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#8074]
**Does your feature request involve difficulty completing a task? Please describe.**
I am not sure about difficulty, because this might relate to crengine limitations.

**Describe the solution you'd like**
I would like to b e able to put my own css files in the /koreader directory, which is in the user accessible storage.

**Describe alternatives you've considered**
For now I just copy them manually to /data/data/org.koreader/launcher/files/data/ .
I need to copy them each time I delete and reinstall KOReader. With test apk this is unavoidable (and I suspect I am going to test more apks in the upcoming future...)

**Additional context**
I tried to use Style Tweaks, but they are not that detailed as a custom-tailored css with all classes.

Thank you!

**Comment by poire-z** [comment]
I think this is specific to Android, and as it's a rare use case (indeed, Styletweaks is the way to solve this, override what you don't like, without losing the things we may change), it should probably be left to the Android specific user-shell-scripts (scripts.afterupdate, scripts.always) which can do some copy of your user files into the app install directory.

Otherwise, this might be solved by just handling another directory in the user accessible partition after this:
https://github.com/koreader/koreader/blob/c8a7f526729dcd4f128077ac08876f92ab9b269a/frontend/apps/reader/modules/readertypeset.lua#L226-L231

But then, this would still look a bit edge casey and odd.

**Comment by mergen3107** [comment]
> But then, this would still look a bit edge casey and odd.

Is it more difficult than the method how OCR files are searched in $userdata/koreader/data/tessdata ?

**Comment by pazos** [comment]
>  Styletweaks is the way to solve this

Agree 100%

> I think this is specific to Android

Not really. Debian/AppImage/MacOS have assets in ro storage. If there's no way to load user data from dataDir then these platforms cannot tweak installation or load new resources.

> Is it more difficult than the method how OCR files are searched in $userdata/koreader/data/tessdata ?

tessdata is hardcoded on each platform: https://github.com/koreader/koreader/search?q=TESSDATA_PREFIX
probably makes sense to move it outside start scripts as `Device.tessdata` and leave `TESTDATA_PREFIX` as an optional override.

**Comment by poire-z** [comment]
It's not difficult to add, and I probably will.
It will just stay undocumented, because there is no real reason for it. I guess you want that mainly for fb2.css as with FB2, we're a bit the publisher and need to style it ? Also for other formats.css ?

Also, we have hooks to execute scripts on start or after update to copy stuff from the user dir to koreader install dir. And now, we'll be adding another hook so koreader can read stuff from the user dir and have it overriding its own content.
Hooks, in both directions... flexible but feels a bit messy and hard to remember and maintain what is there :/

Is there other such content a user may want to override ? Because I'll do it in the above snippet - but may be it could be made more generic. like:
```diff
- for f in lfs.dir("./data") do 
+ for f in util.getFilesFromCombinedAppAndUserDirs("./data") do
```

**Comment by mergen3107** [comment]
> > Styletweaks is the way to solve this
> 
> Agree 100%

Sorry guys, I should have properly learned how to use them. So I put my own fb2.css and epub.css to koreader/styletweaks directory and selected them (for respective documents) in Top menu - User style tweaks. Looks like it is the same, because basically these files have almost all common classes defined.
Is this the right way to do it?

Here are the files for the reference.
[custom css files - mergen3107.zip](https://github.com/koreader/koreader/files/6990623/custom.css.files.-.mergen3107.zip)

I should probably combine them into a single file, because they have many common classes.




> I guess you want that mainly for fb2.css as with FB2, we're a bit the publisher and need to style it ? Also for other formats.css ?

Yes, this is mainly for fb2, because majority of fb2 books are barebones, with css definitions being optional. I think this was one of the design goals to make files simpler and be able to run on different hardware.

For epubs, there are most of the times nice css supplied. So I use Bottom menu `Embedded styles` (which does not affect fb2 too much so I just leave it on by default). 



> Also, we have hooks to execute scripts on start or after update to copy stuff from the user dir to koreader install dir. And now, we'll be adding another hook so koreader can read stuff from the user dir and have it overriding its own content.

With style tweaks properly working, I think there is no need for more hooks. 

Sorry for troubles guys :) 
I think the problem is more or less solved now. 
Thank you very much for your support!

**Comment by poire-z** [comment]
> . So I put my own fb2.css and epub.css to koreader/styletweaks directory and selected them (for respective documents) in Top menu - User style tweaks. Looks like it is the same, because basically these files have almost all common classes defined.
Is this the right way to do it?
> I should probably combine them into a single file, because they have many common classes.

Nope, that's not really the right way to do it.

First, you should not have your own versions of the full epub.css and fb2.css. You may have gotten and updated them from the past, and felt like keeping using them and all is good - but it's not. We may make some fixes to these, and these fixes are not all just "styling", color and margins - some may actually fixes bugs and rendering issues (display: block/inline, and other hacks). So, by using your own, you may miss these fixes, and see bugs or different behaviour that what we could see, and report issues that are not ours :)
See https://github.com/koreader/crengine/commits/master/cr3gui/data/fb2.css - for all the fixes that we did and that you probably don't have. Some of these work also with the rendering code - or the rendering code may expect some of them.

Second, if you'd wanted to keep your own css files, you should not use them as style tweaks: style tweaks are expected to be small "overlays" to the main styles epub.css and fb2.css. They should just change small bits.
By using your own big files, you overlay your full styles on all our full styles - you may not override some of our properties, so you'll get some of our owns mixed with yours - and the combinations may not work together or give strange/incoherent results.

I think you'll need to take a moment (once you're done with the keyboards :) to compare your files with ours, bit by bit, and see what you have changed - and if it's still valid. Then keep just these things you need to have changed, and that can end up in a (or multiple) style tweaks.

Btw, [our fb2.css](https://github.com/koreader/crengine/blob/master/cr3gui/data/fb2.css) is still a bit ugly/misorganized/unreadable - compared to [our/my epub.css](https://github.com/koreader/crengine/blob/master/cr3gui/data/epub.css).
It would be nice if @mergen3107 and @hius07 could rework/clean/prettify them. May be you have some fixes and changes in your own fb2.css that could benefit all FB2 readers.

Also see #6344, #6480, #6622 for some FB2 specific CSS updates that may have been fixed - or are still discussed.

Then, with such a clean fb2.css, it will be easier for you to find out the small bits you want changed vs. our main fb2.css if you expect different things that what we all prefer/agreed on - or may be you'll then just don't feel the need for any change :)

**Comment by poire-z** [comment]
> It's not difficult to add, and I probably will.

Given my followup thinking in previous post, I probably won't :)

**Comment by poire-z** [comment]
Looking at your epub.css vs ours, it looks like yours is not that old - but then lags with our fixes. For example, we fixed some issues with HR having a background-image, that you are reverting:
```diff
-hr {
-    border: 1px solid #808080;
-    margin: 0.5em auto;
-}
+
+hr { height: 1px; background-color: #808080; margin-top: 0.5em; margin-bottom: 0.5em; /* 2px */ }
```
Looking at the real differences that may be your style preferences:
```diff
 /* Headings */
 h1, h2, h3, h4, h5, h6 {
-    margin-top: 0.7em;
-    margin-bottom: 0.5em;
+    margin-top: 0.25em;
+    margin-bottom: 0.25em;
     font-weight: bold;
     text-indent: 0;
     hyphens: none;
@@ -41,10 +37,12 @@

 /* Block elements */
 p {
-    text-indent: 1.2em;
+    text-indent: 2.35em;
+       text-align: justify;
     margin-top: 0;
     margin-bottom: 0;
 }
```
you could put in a user style tweaks `my_preferences.css` just:
```css
h1, h2, h3, h4, h5, h6 {
    margin-top: 0.25em;
    margin-bottom: 0.25em;
}
p {
    text-indent: 2.35em;
       text-align: justify;
}
/* + may be some stuff for sup/sub I didn't care checking if they are yours or old code*/
```
Style tweaks are applied after epub.css (appended to it actually), so this small one will override our values with yours.
As for your fb2.css, it looks like there's only just a bit more tweaks than for epub.css - so it may not take much time finding out your small changes.

**Comment by mergen3107** [comment]
OK, thank you for a detailed reply! 
It will take some time for me to actually find those differences :D 

Among style tweaks files, is there a particular order in which they are applied? What if a few files have the same class and the same properties with different value?

**Comment by mergen3107** [comment]
By the way, `Auto` style selects `HTML/epub.css` instead of `fb2.css` for some (or all?) of my fb2.zip books. I haven’t noticed this issue a lot before, because I was using my own fb2.css by default. 
I’ll have a closer look at other books.

**Comment by poire-z** [comment]
> of my fb2.zip books. I haven’t noticed this issue a lot before

No issue on my emulator with a fb2.zip book: fb2.css is used.
May be this unzip call does not work as-is on your new tiki device ?:
https://github.com/koreader/koreader/blob/1a526a33c2ddad2e8f0553826a3c333f0d02e6cc/frontend/document/credocument.lua#L140-L145
https://github.com/koreader/koreader/blob/1a526a33c2ddad2e8f0553826a3c333f0d02e6cc/frontend/document/credocument.lua#L70-L80

> Among style tweaks files, is there a particular order in which they are applied? What if a few files have the same class and the same properties with different value?

Our shipped style tweaks have each a priority value that let us have a consistent order and allow proper overrides.
User style tweaks get all a larger priority so they are included last and can override our shipped tweaks. But there is no way to prioritize user style tweaks among themselves. So, just be sure you don't have and set tweaks that do different things to the same target. (May be they would then be applied in the order they were selected, dunno, haven't checked.)

**Comment by mergen3107** [comment]
> May be this unzip call does not work as-is on your new tiki device ?:

How can I double check that? 
Verbose logs? Or by adding something with `print`?

**Comment by mergen3107** [comment]
Unfortunately I can’t check this on Kindle, I don’t have it with me anymore

**Comment by hius07** [comment]
I have Auto by default and new fb2.zip are opened with fb2.css (PW2, Voyage).

**Comment by poire-z** [comment]
By running in our terminal plugin or over ssh:
`unzip -qql path_to_some.fb2.zip`
and see if it works or output some error.

**Comment by mergen3107** [comment]
From KOReader terminal,
`unzip -qql /storage/emulated/0/koreader/MG.fb2.zip` gives empty output.

From ssh:
```
1|:/storage/emulated/0 # cd koreader
unzip -qql MG.fb2.zip
unzip: couldn't open MG.fb2.zip: Iteration ended
```
`unzip` is in the `/system/bin/unzip` directory.

Tried to rename it just to `MG.zip`, result is the same. Broken `unzip`?


Here is that file:
[MG.fb2.zip](https://github.com/koreader/koreader/files/6996836/MG.fb2.zip)

It is the same book where i mentioned that `Auto` Style selects `HTML/epub` instead of `fb2.css`.

**Comment by mergen3107** [comment]
> I have Auto by default and new fb2.zip are opened with fb2.css (PW2, Voyage).

Any of my `fb2.zip` books opens with `HTML/epub`...

**Comment by mergen3107** [comment]
> Style tweaks are applied after epub.css (appended to it actually),

OK, but what about Embedded styles? I understand, that Embedded styles uses epub's own css instead of KOReader's epub.css, but do the style tweaks append to this as well?

**Comment by mergen3107** [comment]
> It would be nice if @mergen3107 and @hius07 could rework/clean/prettify them.

By "prettify" you mean to structure them in the same way as "Prettify" button does in the style tweaks preview?

**Comment by hius07** [comment]
> By "prettify" you mean

https://github.com/koreader/koreader/issues/6480#issuecomment-670504285

**Comment by mergen3107** [comment]
@hius07 
Thanks! I'll try to make them nice :)

**Comment by poire-z** [comment]
> OK, but what about Embedded styles? I understand, that Embedded styles uses epub's own css instead of KOReader's epub.css, but do the style tweaks append to this as well?

Not "instead of" - but "after". See https://github.com/koreader/koreader/issues/1430#issuecomment-634996740 (and this older post, before we had user style tweaks: https://github.com/koreader/koreader/issues/3411#issuecomment-373937685)

**Comment by mergen3107** [comment]
Thank you!

**Comment by poire-z** [comment]
Dunno about the unzip issue.
Try with a fb2.zip that contains a something_pure_ascii.fb2 instead of cyrillic.

**Comment by mergen3107** [comment]
> Try with a fb2.zip that contains a something_pure_ascii.fb2 instead of cyrillic.

Yes, if the filename inside zip is in Cyrillic, unzip fails. With Latin name it is OK.

**Comment by mergen3107** [comment]
In a PC version of unzip, `-a` option [makes](https://unix.stackexchange.com/a/428089) it choose proper encoding by itself.
However, I only have:
```
usage: unzip [-d DIR] [-lnopqv] ZIP [FILE...] [-x FILE...]

Extract FILEs from ZIP archive. Default is all files.

-d DIR  Extract into DIR
-l      List contents (-lq excludes archive name, -lv is verbose)
-n      Never overwrite files (default: prompt)
-o      Always overwrite files
-p      Pipe to stdout
-q      Quiet
-v      List contents verbosely
-x FILE Exclude files
```

So I guess the issue is in the dead end of the unzip binary. 

For now I just made KOReader's `fb2.css` default for all books + added my tweaks (which turned out to be only a few):
```
/* Headings */

title, h1, h2, h3, h4, h5, h6, subtitle {
    hyphenate: none;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
}

/* Block elements */
p {	text-indent: 2em; }

/* (epub) some images are in the "p.center" class */
p.center {
    text-align: center;
    text-indent: 0 !important;
}

empty-line { margin: 0; }

stanza { margin-left: 2em; }
```

Works fine for now, unless I miss some specific `epub.css` fixes, I guess.

**Comment by mergen3107** [comment]
`unzip` which is bundled with texlive on my PC says this:
```
>unzip -a -qql MG.fb2.zip
   857240  04/06/2013 17:52   ?aaaa ?R<¤?- - ??┐a ae ??ce?.fb2
```

So it could at least find out that the extension is `fb2`.

**Comment by mergen3107** [comment]
Is there a way to update the unzip binary?
Or maybe KOReader can ship an unzip binary that can handle Cyrillic?

If not, then I will have to unzip all my fb2.zip books (around 800), transliterate them, and zip back. 

However, I can’t do that for those I’ve already read in KOReader and got them in the Reader Statistics, because their MD5 will change and they will be treated as new files in Reader Statistics. I wouldn’t like that, since I occasionally open the read ones too. 

If I could just replace the unzip on Android, I think book detection will work fine. 

For now I set fb2.css as default, and just have to remember to switch to epub.css for epubs.

**Comment by mergen3107** [comment]
I understand that having Cyrillic names inside fb2.zip is probably out of spec. I just renamed them about 3 years ago because I wanted them to look beautiful inside too…

**Comment by Frenzie** [comment]
Could you provide some kind of sample?

**Comment by mergen3107** [comment]
The example is the same as above:
[MG.fb2.zip](https://github.com/koreader/koreader/files/7019755/MG.fb2.zip)

If I unzip, rename to Latin-only filename, zip back, `unzip` works correctly:
[MG_test.zip](https://github.com/koreader/koreader/files/7019757/MG_test.zip)

Meanwhile I found similar problem on 4PDA Forum. The recompiled the binaries for zip, unzip and some other. Their `unzip` works well (I renamed it `unzip3` to make sure I am using this one and not the path one):
```
:/data/local/tmp # ./unzip3 -qql MG.fb2.zip
   857240  2013-04-06 17:52   Артур Голден - Мемуары Гейши.fb2
```

Now I just struggle with how to safely replace the `/system/bin/unzip`.
When I try to `mv` it, it says `Device or resource busy`.

**Comment by poire-z** [comment]
Let's wait for @NiLuJe , who knows the best about all that. May be he can get you a static good unzip, or knows about something in what we ship that can list zip content and could be wrapped as a script named unzip (it feels crengine could, but rather not load that big thing just to check that).

Dunno what we can do generically in KOReader:
- still keep using the native unzip, and too bad if it doesn't work
- ship something
- make a lua/ffi list zip content function - we already do have a zipwriter.lua - so may be a limited zipreader.lua is not too had - but it may not be robust and a real unzip is probably better with zip files from the wild

**Comment by Frenzie** [comment]
Quick search result:
https://github.com/unxed/oemcp/blob/master/unzip_oemcpauto_unix.c.patch

**Comment by mergen3107** [comment]
Update: I was able to replace the `unzip` with that from 4PDA, and seems like KOReader works with it well! I set `Auto` style and it finally switched to `fb2.css` in a new fb2.zip book.

I'll see if this replacement survives a reboot...

**Comment by mergen3107** [comment]
Yes, it did!

Thank you guys, I think this particular issue is solved. I hope there are no other people who manually rename their fb2.zip contents :D so this shouldn't be a problem for KOReader per se.

**Comment by Frenzie** [comment]
That's mainly based on https://aur.archlinux.org/cgit/aur.git/tree/unzip-6.0-alt-natspec.patch?h=unzip-natspec

We may not want to include libnatspec for such a niche use case though (both in the sense of wasting a 100 kB and in the sense of effort).

**Comment by mergen3107** [comment]
> We may not want to include libnatspec for such a niche use case though

Yes, I understand :)
Thank you guys for your willingness to help and your time!

I feel like most of my cases are super niche anyway...

**Comment by NiLuJe** [comment]
Ideally we should be using something like minigzip or whatever the zip equivalent is via ffi, but that's a lot of moving parts for a niche use case ;).

**Comment by mergen3107** [comment]
Original FR is not needed anymore: any css modifications should be done with Style Tweaks, while original css files contain actually useful tweaks and shouldn’t be overridden.

**Comment by mergen3107** [comment]
Thank you to everyone who helped with this discussion!
