### ISSUE TITLE
Battery/Memory alert confirm dialog overlaps

### ISSUE THREAD

**Issue by vsim3** [koreader/koreader#8081]
Hi! Thank you all for KOReader.
* KOReader version: v2021.06-30-gbfda4bfc_2021-07-10 with patches from git master
* Device: Kindle PW3

#### Issue
Alert dialog continue to spawn whenever the check interval timeout
#### Steps to reproduce
Open the gear menu > Device > Device status alerts > lower the check interval to 1min to speed up that process

**Comment by hius07** [comment]
Yes, and every new alert shows current (changing) state of memory/battery, waiting for user's reaction.

How it should be?

**Comment by hius07** [comment]
Please note that both alerts do not work while the device is sleeping (suspending).

**Comment by Frenzie** [comment]
> How it should be?

The complaint might be that it's an unexpected surprise after you've interacted with one of them. In which case there are solutions like this:

<img src=https://i.pcmag.com/imagery/encyclopedia-terms/cascading-windows-_cascade.fit_lim.size_1600x.gif>

But otherwise I'm not really sure what else could be expected.

**Comment by hius07** [comment]
> after you've interacted with one of them

They are spawining one exactly above each other, so we can interact with the latest one only.

As I undrestand, @vsim3 would like to stop spawning if the alert has not been interacted.

**Comment by vsim3** [comment]
Yes. It's a bit confused when use with Keep alive plugin, they look alike and stacking up on each other. I think it may look better if the duplicates of dialogs is prevent.

**Comment by vsim3** [comment]
![pic1](https://user-images.githubusercontent.com/50333987/129574430-0a278eb7-1bd7-4700-b6db-f8c78020d2cd.png)

**Comment by hius07** [comment]
> I think it may look better if there is a way to prevent duplicates of dialogs.

That can be done.

Can anybody using this feature confirm the preferred behaviour?

**Comment by Frenzie** [comment]
@hius07 You said there's no such thing as duplicates?

**Comment by poire-z** [comment]
Either don't show a new alert if the previous one is still displayed.
But if a new one may say something different, it might be better to always remove the previous one to display the new instead.
The later one can be done by keeping in that module a ref to the previous shown widget so it can be UIManager:close() when a new one is about to be shown. And may be a dismisscallback that will remove the ref from that module.

(Not sure I fully understand the context - do I ? :)

**Comment by hius07** [comment]
> You said there's no such thing as duplicates?

The interval (for demonstrating) is just 1 min, the battery level has fallen, say, from 78.4 to 78.3 only.

**Comment by Frenzie** [comment]
Yes, that we wouldn't want. I misunderstood the issue to be that you can get a battery and memory alert at the same time, which strikes me as not an issue.

**Comment by vsim3** [comment]
That worked! thanks!
