### ISSUE TITLE
FR: Highlights "behind" the text

### ISSUE THREAD

**Issue by rmuser2** [koreader/koreader#8085]
**Does your feature request involve difficulty completing a task? Please describe.**
KOReader highlights simply cover the text, making it the black text greyscale which I find very difficult to read when the PDF is synced to a computer to read the PDF.

**Describe the solution you'd like**
Highlights to be applied like other PDF readers, where it is "behind" the text.

**Comment by Galunid** [comment]
I'm pretty sure it's already implemented. Top menu -> Second tab -> Highlighting -> Underline

**Comment by rmuser2** [comment]
Thanks for the reply, but don't be too quick to close this. The underline feature is not what I am referring to.

What I want is for text to be highlighted where the colour of the text itself is not manipulated. As it stands now, the KOReader highlight just lightens the area which it covers, which then makes the text lighter in colour. 

The link below is to an image which shows the problematic KOReader behaviour on the left, versus the desired Acrobat/Xodo/etc. highlighting behaviour. This shows that the latter places the highlight colour behind the text, at least with respect to how it is perceived. 

https://ibb.co/VCrvL6p

**Comment by benoit-pierre** [comment]
This is fixed with MuPDF 1.24.2:

| before | ![0_before](https://github.com/koreader/koreader/assets/5104286/0480bead-d79b-4f7d-b683-59fbaea16390) |
| -- | -- |
| **after** | ![1_after](https://github.com/koreader/koreader/assets/5104286/ff64ab67-0d17-4d1d-b7c1-862b37aa1b1d) |
