### ISSUE TITLE
FR: A 'Live' Terminal Emulator

### ISSUE THREAD

**Issue by gsaker** [koreader/koreader#8088]
**Does your feature request involve difficulty completing a task? Please describe.**
Not sure how difficult this would be...
**Describe the solution you'd like**
At the moment it is quite difficult to use the existing Terminal Emulator. The ability to save + run scripts is great but it would be nice to be able to have a 'live' terminal emulator with a support for interactive programs like nano/vi etc. 
**Describe alternatives you've considered**
I am aware of other programs such as [Inkvt](https://github.com/llandsmeer/inkvt/) but it's difficult to switch between it and Koreader. I'd like to have everything in one place. 

Thank You! This is such a great project and has breathed new life into my Kobo!

**Comment by gsaker** [comment]
Added a bounty on [BountySource](https://www.bountysource.com/issues/100442237-fr-a-live-terminal-emulator) to get this moving
:)

**Comment by roygbyte** [comment]
Is the existing terminal emulator a good place to start for this FR? Does that plugin just need, like, the ability to save and run scripts, as well as save output to a file (maybe)? Or is the desired capability beyond what a plugin can fulfill?

**Comment by NiLuJe** [comment]
No, we'd need an actual, well, terminal emulator ;p.

The Terminal plugin is basically just a simple wrapper around popen. That is far, far, far, far from that ;).

**Comment by NiLuJe** [comment]
And, yeah, there isn't really anything existing (design-wise) that could help in *any* way with this.


(TL;DR: Patches welcome, but this is kind of a pie in the sky).

**Comment by NiLuJe** [comment]
(As in, you're much likelier to get something "working" by tackling the interoperability issues mentioned above that trying to reinvent the wheel).

**Comment by roygbyte** [comment]
The interoperability, as in: "it's difficult to switch between it and Koreader. "?

Gotcha.
