### ISSUE TITLE
White blinks in night mode

### ISSUE THREAD

**Issue by abdrau26** [koreader/koreader#8095]
Koreader:2021.1
Device: kobo clara hd
I am using night mode. When i do some action like to open the menu or to see a word in look-up, screen gets white momentarily. After this moment, it settles down to night mode. Please guide how to avoid this white transition in night mode.

**Comment by NiLuJe** [comment]
Unavaoidable, unless you get a device with actual nightmode support (right now, on Kobo, that's the Elipsa).
