### ISSUE TITLE
Highlight Page Scroll Behavior

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8098]
My suggestion is about highlighting behavior when crossing page boundaries.
I think I can explain better with a picture:

![highlight behavior](https://user-images.githubusercontent.com/84420582/129835550-b700d9ba-b274-49c6-be4d-52af0a540382.jpg)

***

I start highlighting and drag my finger to upper left corner. Highlight scrolls the page for me to continue highlighting.

**CURRENT BEHAVIOR:**
- KOReader says **"Oh you want to continue highlighting on previous page. Here is 9 more lines for you"**
But I want to highlight earlier parts and my finger is already at the corner. To indicate that I want to scroll more I have to move my finger to signalize KOReader to scroll more. KOReader gives me another 9-10 lines. Nope not yet there. I have to do finger dance once more. At this point KOReader sometimes thinks I finished highlighting and I have to delete it and start over again. When you have to make maaany highlights in a book, this becomes really annoying.

**EXPECTED BEHAVIOR:**
- KOReader says **"Oh you want to continue highlighting on previous page. Here is the PREVIOUS PAGE"**
Scrolls one full page so I can select text without scrolling bit by bit. Same applies for highlighting the next page too.

**Comment by poire-z** [comment]
> KOReader says "Oh you want to continue highlighting on previous page. Here is 9 more lines for you"

KOReader was probably whispering and you didn't hear it well - but it said: "Here is 1/3 of the previous page" :)
https://github.com/koreader/koreader/blob/1a12e8555eccb65ac2d7d93fd19bbf488bd02804/frontend/apps/reader/modules/readerhighlight.lua#L903

My idea, and and still quite like it, was to keep showing part/all of the highlight on the previous page so you still see the content and context of what you're highlighting.
Highlighting text on a full page would then need 2 more of that little dance - and it feels this must  be rare vs. good context and precision for highlight small sections.

> I have to do finger dance once more. At this point KOReader sometimes thinks I finished highlighting

If going a full page, you'd not kill the need for that finger dance, you'll just be reducing its need by 3 - and if you highlight text on 4 pages, you'll still get this issue.

Also, if going a full page, there wouldn't be any need for switching to scroll mode to show a fraction of a page height, and I think it would really be confusing to not really see the context and continuation of the highlight you're making.

**Comment by offset-torque** [comment]
> My idea, and and still quite like it, was to keep showing part/all of the highlight on the previous page so you still see the content and context of what you're highlighting.

I understand the sentiment and it sounds good. I wish we had some kind of poll to see how other users prefer some options. I can't say my solution is better if other users depends on this context feature.

Can we at least get a compromise like "scroll as much to keep three lines of highlight at the end of page as context".

**To clarify:** In the upper screenshot, page can scroll as much as cyan highlighted "Do you...somewhere." stays visible at the bottom.

` local scroll_distance = math.floor(Screen:getHeight() * 1/3) `

By the way I changed **1/3** to **0.8** on my reader and it looks like it works as I proposed. More of the page is visible so probably I won't need to scroll twice for long highlights.

**Comment by offset-torque** [comment]
Didn't you notice my message or is it being ignored @poire-z ?

**Comment by poire-z** [comment]
I've seen your post, just didn't have anything to answer or add :) Waited for other users to give their thoughts.

But ok, just tried your 0.8 - and for me (not a heavy highlighter), it's really too much - the context/the paragraph surrounding I started the highlight is gone, I'm on a nearly blank page with just 4 lines at the top, and I felt really lost...

But with our 1/3, and having to do that little dance - diagonal swipe back and forth in the corner - was easy, and I didn't have any false finger release, managed to highlight text on 3 pages with ~10 such small diagonal swipes, not being as lost as with your 0.8.

So, I'm not really a user of the feature - but as a newcomer, I think 1/3 is the least bothering.
And highlighting full pages feels like a rarer use case - that should not kill the experience of highlighting small fragments with their context gone.

(false finger release - Think I've asked that before, to you or someone else: how long are your nails ? :) because indeed, going into the corners, finger angle may change quite a bit and the contact may be lost more easily...)
(maybe my GloHD being Infrared is less sensitive to this that capacitive screens)

**Comment by pazos** [comment]
- I like current behaviour. 
- Sounds sensible enough. 
- I'm not against making it tweakable on the UI.
- Please don't change the defaults without a good reason and *if* you change defaults please provide a way to revert back to old defaults.
- Old defaults are, IMHO, the best defaults to keep.
- Introducing new defaults requires people interested in the new feature -  or with a specific problem with current implementation - and a lot of conversation. See, for instance, the convesation with keyboard layouts or the previous conversation about icons.

**Comment by offset-torque** [comment]
Considering that I can patch my reader to tweak this behavior and people using long highlights like me is rare, I think I can close this issue (unless someone wants to keep it open for some reason).

**About false finger release:** I don't have long nails but I have a tempered glass screen protector and I started suspecting that might be the culprit. Although I have been using tempered glass protectors on many touch devices for years without problem, that seems like the most logical explanation. Even multi-swipe gestures works ok on my device. Maybe Libra's capacitive sensing circuit doesn't like this type of protectors, especially on the edges.

If you hear someone else with touch problems+protectors you can tip me in the **USER GUIDE** thread so I can add a heads-up in the guide.
