### ISSUE TITLE
Hidden Folders 2021.07

### ISSUE THREAD

**Issue by mohammed-ishtiyaq** [koreader/koreader#8101]
* KOReader version:2021.07
* Device:Kobo Forma

#### Issue
After enabling shoq hidden files, /mnt/onboard/.Kobo folder is not showing. I have installed an older version 202011000000 of KOReader and it is working.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hius07** [comment]
Not a bug, but a feature
https://github.com/koreader/koreader/blob/1a12e8555eccb65ac2d7d93fd19bbf488bd02804/frontend/ui/widget/filechooser.lua#L29-L35

**Comment by NiLuJe** [comment]
Yeah, still haven't thought a great way to deal with that. I'll see if blacklisting the offending subdirectories makes more sense...

**Comment by pazos** [comment]
> Yeah, still haven't thought of a great way to deal with that. I'll see if blacklisting the offending subdirectories makes more sense...

Windows makes a difference between hidden files and system/protected files. I guess we can make this too if we're interested (I'm not, my device only has KOReader)

Those exclude dirs are both system and hidden dirs so the user would need to check "show hidden files" and "show system files".

Again, not interested in the feature. Just my 2 cts if somebody wants to tackle it.

**Comment by mohammed-ishtiyaq** [comment]
Dear All,
Thank you for all your great work. I'm a fan of KOReader.

In the hidden folders, the important folder is the "dropbox" folder, which
Kobo creates when Dropbox is setup. Can a menu item added "show hidden
Dropbox" in KOReader. So as users don't have to go and play with settings
files? I know, we can add Dropbox sync with KO CloudStorage but it doesn't
see the hidden folder of Kobo, so we end up in 2 sync folders.

Apologies for jumping in tech discussion.

Regards,
Ishtiy
