### ISSUE TITLE
crash !!!

### ISSUE THREAD

**Issue by sany98215** [koreader/koreader#8102]
* KOReader version: pw2-v2021.03
* Device: kindle kw2

#### Steps to reproduce
When I read the pdf book with reformat，and i read next page, then crash! I don't know how and why.

i try to disable all plugins.

**Comment by sany98215** [comment]
here is log 
-------------
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 08/18/21-23:27:39
 [*] Version: v2021.03

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load (warning): libSDL2.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so
ffi.load (warning): libSDL2-2.0.so: cannot open shared object file: No such file or directory
ffi.load: libSDL2-2.0.so.0
ffi.load (warning): libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
SDL2 not loaded:	./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0

**Comment by NiLuJe** [comment]
Given the device, probably an OOM, see the numerous issues about memory constrained platforms.

(Also, that log is useless ;)).

**Comment by sany98215** [comment]
Thanks for reply！
If an OOM, I think there is no way，what i can do is just gived up～～～
Here is information as a reference

1）Memory utilization is about 70% ，which is from koreader plugin。
2）I enabled the debug log，but there is no warning log excepted Loading warning（i.load (warning): libSDL2-2.0.）。

If you have any optimization suggestions,give me some for reference，thanks！

**Comment by NiLuJe** [comment]
Besides potentially having slightly better success with *much* earlier FW versions (say, ~5.6.x), not really, as the PW2 has a laughable amount of RAM to begin with :/.
