### ISSUE TITLE
Standardize select / choose

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8105]
Select or choose?
https://github.com/koreader/koreader/blob/b4ec68d8c07c15130561a4d90e316c98bf01aecc/frontend/ui/widget/pathchooser.lua#L33
https://github.com/koreader/koreader/blob/b4ec68d8c07c15130561a4d90e316c98bf01aecc/frontend/apps/reader/modules/readerwikipedia.lua#L195
https://github.com/koreader/koreader/blob/b4ec68d8c07c15130561a4d90e316c98bf01aecc/plugins/opds.koplugin/opdsbrowser.lua#L658
https://github.com/koreader/koreader/blob/db60ba48b72cfc40697d85bf28197b3dcddb6ed3/frontend/apps/cloudstorage/cloudstorage.lua#L307
https://github.com/koreader/koreader/blob/fa4784cf13756ca6886050539888aa8dd7138120/frontend/ui/widget/screenshoter.lua#L92
https://github.com/koreader/koreader/blob/0e606251600021f5adda07755fa94f6c70b93818/frontend/ui/screensaver.lua#L237
https://github.com/koreader/koreader/blob/2ab31a9a363b97df453555ba949d3819b4399332/frontend/apps/filemanager/filemanagermenu.lua#L309

**Comment by Frenzie** [comment]
Choose.

**Comment by NiLuJe** [comment]
Possibly even choose *a*/*this* thingy?

**Comment by Frenzie** [comment]
Depends of course, not "choose a download folder." ;-)

**Comment by hius07** [comment]
How about to standardize "long-press" to "hold"?

`Long-press to select folder` - `Hold to choose a folder` - `Hold a folder to choose`

(Our new User guide recommend "tap and hold")

**Comment by Frenzie** [comment]
Hold *on* a folder. But sure, why not.

**Comment by hius07** [comment]
> Hold _on_ a folder.

Here too?
https://github.com/koreader/koreader/blob/056c03a2625ea14a935547e0d731df931d438129/plugins/gestures.koplugin/main.lua#L677

**Comment by Frenzie** [comment]
That's a different context, where telegram style is appropriate. :-)

**Comment by hius07** [comment]
<kbd>![1](https://user-images.githubusercontent.com/62179190/130313402-b933c4ef-8b8f-41f2-91bc-257a419c8395.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/130313406-49b84021-8f72-4bf0-a5cb-8bfbb0c99bdc.png)</kbd>

**Comment by poire-z** [comment]
Personal preference from a non native english reader: `long-press` feels clearer than `hold`.
Just because "hold" has more meanings and covers more contexts and is then less precise ("hold your device in your hand", so "hold to select" could result in: "yes, I've been holding my device for 30 seconds, but nothing gets selected!" :)
"long-press" is a lot clearer.

(It can even make translations clearer. The french translation of `long-press to select folder` is actually nearer to `hold to select folder`: "Maintenez votre doigt pour..." - while the litteral "long-press" translation could have been nicer: "Appui long pour...")

But no opinion on select vs. choose, both are fine to me (and the french translation seems to be "choisir" = choose).

**Comment by Frenzie** [comment]
> Personal preference from a non native english reader: long-press feels clearer than hold.

Yes, that's a valid ponit. But NB that's exactly the difference between "hold corner" (= you grab the corner of the device and hold it) and "hold on corner".

You could also call it something like tap & hold or touch & hold.

**Comment by poire-z** [comment]
For the same non native english reader I am, "tap" means "touch & quick release". So, I read "tap & hold" as "touch and quick release, and then long-press" :)
"Touch & hold" feels more adequate - but I still prefer long-press :)

And "tap & hold" will surely make it akward to translators, each will have to understand it just means "long-press" - "Appuyez et maintenez" vs "Appui long" (although "Appui long" does not make it a sentence with a verb - but it would read well and simple).

**Comment by hius07** [comment]
Apple use "long-press" in the guidelines
https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/handling_uikit_gestures/handling_long-press_gestures

Can we standardize all "hold"s to "long-press"?

**Comment by Frenzie** [comment]
Long-press is fine by me.

**Comment by Frenzie** [comment]
> Apple use "long-press" in the guidelines
https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/handling_uikit_gestures/handling_long-press_gestures

That doesn't necessarily follow ftr. One should look at the UI guidelines and/or what actually happens in macOS/iOS; the developer guidelines are reasonably likely to use the same conventions but they may not.

**Comment by Frenzie** [comment]
E.g., here they're calling it "touch and hold" and the HIGs are much closer to what they show end users.
https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/gestures/

**Comment by hius07** [comment]
Okay, this round of standardization will change "select" to "choose" (9 modules), keeping "long-press" as is.
