### ISSUE TITLE
PDF Text Reflow cuts off / skips text

### ISSUE THREAD

**Issue by Kusurisan** [koreader/koreader#8114]
* KOReader version: newest
* Device: Kindle PW4

#### Issue

If i activate the pdf text reflow, the text gets "weird". if a sentence is started at the end of one page, and i switch to the next page, the suddenly is at a completly different sentence and don't completes the started sentence from the previous page. 

**screenshots who show the issue:** https://imgur.com/a/2K8aUrP

picture 1 is page 1, picture 2 the page 2.

it is REALLY confusing and i can't really read like that since i always first need to find the sentence i was again or disable text reflow to be able to read sentences since they sometime get cut off or skipped completly.

#### Steps to reproduce

open a pdf file and activate pdf text reflow, font size 0.8 or 1.0

**Comment by Frenzie** [comment]
What does the original look like? For example:

## Original
![Screenshot_2021-08-22_09-25-36](https://user-images.githubusercontent.com/202757/130346354-80784d49-8ae8-40bc-ab95-5033c2f1e488.png)

## Reflow
![Screenshot_2021-08-22_09-24-00](https://user-images.githubusercontent.com/202757/130346309-e862c6fe-bbb4-4682-aa55-286b41f641d9.png)
![Screenshot_2021-08-22_09-24-08](https://user-images.githubusercontent.com/202757/130346310-0f134823-1382-439a-a08b-c8878d29d45f.png)
![Screenshot_2021-08-22_09-24-14](https://user-images.githubusercontent.com/202757/130346311-e19b6921-bda6-4f6c-b2ac-00e47a2c4a10.png)

**Comment by Kusurisan** [comment]
**reflowed text:**

![Reader_2021-08-22_091102](https://user-images.githubusercontent.com/64882739/130346457-e0588278-41b0-4613-9f4e-f4c9b7da4b08.png)
![Reader_2021-08-22_091116](https://user-images.githubusercontent.com/64882739/130346461-205492cd-36e6-4e62-bcae-26f752c9fe4f.png)


**with reflow disabled it looks like this:**

![Reader_2021-08-22_092739](https://user-images.githubusercontent.com/64882739/130346449-f559ad04-a57d-4034-8e68-582276fa42c4.png)

**Comment by Frenzie** [comment]
Perhaps you just have the overlap set to a rather large value?

**Comment by Kusurisan** [comment]
the overlap setting is greyed out for me while i have the pdf open, so i can't change or look into that option

**Comment by Frenzie** [comment]
You could try creating a defaults.persistent.lua and reducing this setting.

https://github.com/koreader/koreader/blob/3c3361addfda3c5b9c7f32cf412df7ee727256ef/defaults.lua#L65-L66

That normally comes down to an approximation of a line, not 3-4.

**Comment by Kusurisan** [comment]
okay, i tried now around a little by opening other documents and then opened this pdf again and now somehow i could activate the page overlap setting. i could choose arrow or grey out and it now seems to show me where to read / where i was. so this helps a lot thanks!

is there a way to just show text i didn't have read if i flip to the next page? like.. it removes the previous text from the previous page completly from the next page? or is there only the page overlap option for this?

**Comment by Frenzie** [comment]
You can set the global default I mentioned above to 0, but that's guaranteed to cut lines in two. ;-)

**Comment by Kusurisan** [comment]
damn, okay :D
then i will just keep the page overlap setting activated.

thanks for the quick help! <3
