### ISSUE TITLE
Android Gestures: Warmth/Birghtness offsets inconsistent

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#8116]
* KOReader version: 2021.08
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

There are still several issues with Android Glowlight Control from KOReader.

### Issue 1: The Front light dialog and swipe gestures have separate own values for Brightness/Warmth

I understand that KOReader lights and System lights are out of sync due to Onyx'es fault (most probably), but the light levels in the Front light dialog and light levels from gestures are also out of sync.

#### Steps to reproduce issue 1
- Open KOReader
- With default gestures: set both of lights to 0
- Open the Front light dialog: max out both of the lights (from 0)
- Use gestures to increase the lights: both of them will start from 0, which was set before, and not maxed out values.

So it seems that gestures do not read the Front light dialog values before applying the offset. However, after changing the lights with gestures, the Front light dialog reads the values correctly.

---

### Issue 2: Warmth and Brightness offset values have different actual effect
I think this is related to the [recent](https://github.com/koreader/koreader/pull/8104/commits/2875bb76a2e2bd5fc8ceaeeea5ec50627d3ec314) normalization applied only to Warmth, which fixed it.
FYI, the popup notifications report values 0-100 for Brightness, and values 0-255 for Warmth.

##### Part 1: Decrease - work fine (I just show the good example).
- With default gestures, set both light levels to max 255.
- For the left edge down gesture, set two actions: **Decrease** Brightness + **Decrease** Warmth, both by 1.
- Try to decrease with this gesture. In `logcat Lights:V *:S` I can see that both of them change by 2 and by 3 in turns. I suspect this is due to the fact that "offset 1" in gesture settings refers to "1% out of 100%", and 2 and 3 are the results of floor operation which depends on the current index along the 0-255 range. It looks consistent though, so it is always `2 - 3 - 2 - 3 - 2 - 3 - ...`

##### Part 2: Increase - where things get confusing.
- Revert default gestures
- With default gestures, set both light levels to max and then to some lower level (the point is to have them at the same level)
- For the left edge up gesture, set two actions: **Increase** Brightness + **Increase** Warmth, again both by 1.
- Try to increase with this gesture. In `logcat Lights:V *:S` I can see that Warmth does not change at all, while Brightness changes by usual steps of 2 or 3 in turns.

Upon further testing:
- If for Decrease I use these offsets: Brightness (1), Warmth (1); and for broken Increase: Brightness (1), Warmth (3) - both lights change by the same actual offset of `2 - 3 - 2 - 3 ...`, given then start at the same level (i.e. Decrease both from 255 and Increase back).

- However, these offsets result in very slow adjustment of lights. So I tried to multiply it by fixed number. My surprise was that fixed numbers multiplication produces inconsistent results too! My final settings to alter both Warmth and Brightness by consistent patterns of `11 - 10 - 10 - 10 - 10 - ... ` are:
Increase: Brightness (4), Warmth (12)
Decrease: Brightness (4), Warmth (8)

This is my temporary workaround. The idea behind this is to have one slider for "overall light power" (i.e. Brightness + Warmth at the same time), and another slider to adjust only Warmth (or Brightness, does not really matter, since the relative warmth will change anyway).

However, this is still an issue for an average user I think.
@Galunid, I would appreciate your feedback on these issues! 

Thank you :)

**Comment by zwim** [comment]
I don't own a Kon-Tiki device. But looking in your PR #8020 I want to make some assumptions on your device:
a) Is it right, that you really have 256 different warmth steps? (Tolino has 10)
b) Is it right, that you can set brightness to zero and you have frontlight on, so you can read (maybe with warmth > 80)? (On Tolino brightness==0 means no frontlight, it is an overall light power controller).

If a) is right, then we should apply  #8104 only if `self.fl_warmth<100`, and your issue 1 is fixed (and maybe issue 2, too).

if b) is right, your idea of an "overall light power"  would have to be implemented in the android part (LightsFactory). Cannot help you here.

**Comment by mergen3107** [comment]
> a) Is it right, that you really have 256 different warmth steps?

I am not sure that I have 255 **steps**, but I can see **values** from 0 to 255 in the logcat when I adjust the lights from KOReader or from Onyx light control app. They change mostly by the increments of 10, sometimes 5, and occasionally 3 (not sure why< maybe that's just hardcoded in the Onyx app). 

In KOReader's Front light dialog, both of these report to logcat values 0-255.

> b) Is it right, that you can set brightness to zero and you have frontlight on, so you can read

Yes, I can. Onyx light control app has these two toggles separate. I can have either or both ON. There is also a shortcut to toggle the frontlight, which remembers exactly what was on, and returns the same values. For example, if I had Warmth 80% and Brightness 0, it will toggle back and forth to these values.



> and your issue 1 is fixed (and maybe issue 2, too).

No, that PR didn't fix these issues, unfortunately. Both Front light dialog and swipe gestures report values 0-255, but they are separate from each other.

**Comment by mergen3107** [comment]
> I understand that KOReader lights and System lights are out of sync

With `pidcat` I found how to sync these changes with Onyx Light controller!
After changing Brightness/Warmth, in the end it does this:
```
       SettingsProvider  V  Notifying for 0: content://settings/system/screen_warm_brightness
                         V  Notifying for 0: content://settings/system/screen_cold_brightness
```

I double-checked this, and it is equivalent to shell commands:
```
settings put system screen_warm_brightness n
settings put system screen_cold_brightness n
```
where `n` is the value 0-255. Onyx Controller picks up this value upon start, even if you just execute commands without writing to the files `/sys/class/backlight/warm/brightness` and `/sys/class/backlight/white/brightness` (which would actually adjust brightness).

@pazos 
Is there a way we can implement this in KOReader?
This settings alteration does not look like Onyx-proprietary, so it should be OK with other Android devices too?

**Comment by Galunid** [comment]
@mergen3107 The problem why this is not implemented is because it needs `WRITE_SETTINGS` permission. It'd mean other android devices running KOReader would have a popup requesting said permission. You can see some more context here https://github.com/koreader/android-luajit-launcher/pull/248

As for issues you mentioned earlier, you can try to get rid of `math.floor` from `setWarmth`/add it to `setBrightness`, I believe it doesn't have one. I just skimmed this, since I have an interview tomorrow and I'm currently preparing. I'll write more tomorrow evening

**Comment by mergen3107** [comment]
@Galunid 
Thank you for you input! 

Good luck on your interview!

**Comment by Frenzie** [comment]
Good luck! ^_^

**Comment by mergen3107** [comment]
> because it needs `WRITE_SETTINGS` permission. It'd mean other android devices running KOReader would have a popup requesting said permission.

Sorry, I still don't understand why this would be a problem?
- Will it ask every time front light is adjusted? In the reading app [AlreaderX Pro](https://4pda.to/forum/index.php?showtopic=945616), for example, they have write permissions and front light levels are written to Settings. It didn't even ask once the permission to write. Although, it is a system app, so maybe that's why.
- Is this a security concern? That if something goes wrong with KOReader, it would be written to Settings? If it is security, then we should probably fix the issue with Folder Shortcuts too:  https://github.com/koreader/koreader/discussions/7892 . It is when I was able to copy files from user storage to /data/data/koreader.../files/ on a non-rooted phone (which is otherwise impossible).

**Comment by Frenzie** [comment]
> Is this a security concern?

In a manner of speaking. When a user sees a request for that permission, there's a non-negligible chance they'll be unhappy about it.

**Comment by mergen3107** [comment]
> In a manner of speaking. When a user sees a request for that permission, there's a non-negligible chance they'll be unhappy about it.

OK, understood! I am not going to completely turn tables and suggest to change this model, if you already have decided to stick to it.

The only reason I would like to see front light levels in sync with Settings is just convenience after all.
I spend most of the time with Onyx reading in KOReader, so I also adjust the frontlight as well. However, I need to remember approximately what levels I have in daytime and nighttime, and it is always different. Onyx light control can save 3 profiles, but to activate them I need to go outside of KOReader, and then manually adjust them exactly via shell (first I need to look via logcat or gestures what the actual values are). 

So maybe it would be easier to implement front light "profiles"? I've seen I can use profiles plugin to set front light values as well, but I am not sure how this works. Do I need to set all the settings I currently use? Is there a way to disable the profile and go back to settings I have?

Or at least show the actual values and buttons `+` and `-` in the Front light dialog? Interestingly, I've seen in the `frontlightwidget.lua` that `button_plus` and `button_minus` exist (line 301):
```
    if self.powerd.auto_warmth then
        enable_button_plus = false
        enable_button_minus = false
        button_color = Blitbuffer.COLOR_DARK_GRAY
    else
        if math.floor(num_warmth / self.nl_scale) <= self.nl_min then enable_button_minus = false end
        if math.ceil(num_warmth / self.nl_scale) >= self.nl_max then enable_button_plus = false end
    end
```
However, they don't appear in my widget, and AFAIK I don't have `auto_warmth`.

This is how it looks like:
![Screenshot_20210823-173001](https://user-images.githubusercontent.com/6279855/130522291-9c900976-b817-402f-a45b-e2257b450ca3.png)

**Comment by mergen3107** [comment]
Can someone please explain how does `frontlightwidget.lua` actually work on Android? I am a little bit confused.

First, it needs `/frontend/device.lua`:
https://github.com/koreader/koreader/blob/a55837647198a6a1d64aa6b064b0b1fe5e2642a4/frontend/ui/widget/frontlightwidget.lua#L6

which for Android will transfer into `/frontend/device/android/device.lua`:
https://github.com/koreader/koreader/blob/a55837647198a6a1d64aa6b064b0b1fe5e2642a4/frontend/device.lua#L5-L9

OK. Then, the widget is looking for `powerd`:
https://github.com/koreader/koreader/blob/a55837647198a6a1d64aa6b064b0b1fe5e2642a4/frontend/ui/widget/frontlightwidget.lua#L40-L51
specifically, `self.powerd = Device:getPowerDevice()`.

However, `/frontend/device/android/device.lua` does not have the function `Device:getPowerDevice()` . It gets powerd in a slightly different form:
https://github.com/koreader/koreader/blob/a55837647198a6a1d64aa6b064b0b1fe5e2642a4/frontend/device/android/device.lua#L128-L130

So how does it work then? Is it still able to get the proper powerd?

Sorry if this is something from basic programming =/

**Comment by mergen3107** [comment]
> "overall light power"/

From my understanding, this is just the sum of total brightness at any given levels of Brightness and Warmth. When adjusting this power, I would like to have the same color temperature.

I figured out that on my Onyx there are 9 blue LEDs and 8 yellow LEDs in between them, all of them on the bottom of the screen. So in order to adjust the power at the same color temperature, for each `1 point` of blue color I need `9/8 = 1.125 points` of warm color to adjust. I am not sure how well this will play out with `math.floor` though. 

This is assuming that these blue and yellow LEDs conform [general Volt/Ampere characteristics](http://lednique.com/current-voltage-relationships/iv-curves/) of LEDs:
![image](https://user-images.githubusercontent.com/6279855/130528054-db9627d8-b217-4256-b08c-902bf32eefd3.png)
After some minimum threshold, we can assume these curves are more or less linear. So the power increase will also be linear. Also, as seen from the graph, this approach only works well after this threshold.

I'll test it, once I solve bigger issues first.

**Comment by mergen3107** [comment]
> When a user sees a request for that permission

By the way, how KOReader is able to override Screen time out on Android without permissions to write to settings?

**Comment by Galunid** [comment]
OT: Thanks for the wishes, 100/100 on the interview ^_^

>specifically, self.powerd = Device:getPowerDevice().
However, /frontend/device/android/device.lua does not have the function Device:getPowerDevice() . It gets powerd in a slightly different form:

It's inherited from
https://github.com/koreader/koreader/blob/a55837647198a6a1d64aa6b064b0b1fe5e2642a4/frontend/device/generic/device.lua#L231-L233
When you create android device here https://github.com/koreader/koreader/blob/a55837647198a6a1d64aa6b064b0b1fe5e2642a4/frontend/device/android/device.lua#L70-L74

I don't have an opinion on the `WRITE_SETTINGS` permission. IIRC you just need to add some `System.putInt` calls to make it synchronize, in the Kotlin code. I it's for your personal use, you could probably bypass the needed permission by making KOReader a system app (I assume your device was rooted). This used to give apps full permission, not sure if it's still the case

>By the way, how KOReader is able to override Screen time out on Android without permissions to write to settings?

I believe there's a flag that tells the system to keep the app open, there is no need for `WRITE_SETTINGS`. https://developer.android.com/training/scheduling/wakelock#screen

**Comment by mergen3107** [comment]
@Galunid 
Good news! :)

Thank you very much for your answers!

**Comment by pazos** [comment]
@mergen3107: `frontlightwidget.lua` is unused on android. The light dialog used in android is in https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/Device.kt#L192-L254. Values are auto-picked from device's lightsController.

About the permission. The interface for lightsController has a [`needsPermission` method](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/LightsInterface.kt#L8). It hasn't any logic attached as no current controller requires it, but my suggestion would be return `true` on that method and wire that to the permission prompt with a rationale message. That would prompt the user for the required permission the first time it uses the feature (via the frontlight widget or via gestures).

IIRC `putInt` doesn't change the value of the sysfs node, so you'll need to write the sysfs value (as we do now) and then, **if** there's no error writting there, save the appropiate setting using `putInt`.

About changing the sliders: that would be a hard vetto. Please don't. Makes the whole thing impossible to maintain in the long run. If you're interested you can make a custom method that shows an alternate frontlight dialog and invoke it **just on your device**. That would be tolerable, IMHO.

In the same vein, it will be tolerable to rewrite the whole native frontlight dialog as part of `frontlightwidget.lua`. It just happens to be a pain in the ass and that file is already a bit of a hot potato. It doesn't worth the time.

**Comment by mergen3107** [comment]
@pazos 
Thank you for your detailed answer!

About the front light widget, it is a great revelation for me! Thank you, I would have never found out that myself :')

> About changing the sliders: that would be a hard vetto. Please don't.

OK! I will just try to solve these two issues in the OP then, and maybe the permission thing.




> **if** there's no error writting there

that means that the warmth/brightness files (`/sys/class/backlight/warm/brightness` and `/sys/class/backlight/white/brightness`) were successfully overwritten? Currently they are, since the front light levels change properly. Or do I need to put another check to make sure?
