### ISSUE TITLE
Crash on Kindle KT3

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8117]
Kindle KT3 5.11.2

```
[*] Current time: 02/01/19-00:53:49
[*] Version: v2021.08

./luajit: ./ffi/framebuffer_linux.lua:51: cannot open framebuffer
stack traceback:
[C]: in function 'assert'
./ffi/framebuffer_linux.lua:51: in function 'init'
./ffi/framebuffer_mxcfb.lua:627: in function 'init'
./ffi/framebuffer.lua:125: in function 'new'
frontend/device/kindle/device.lua:803: in function 'init'
frontend/device.lua:62: in main chunk
[C]: in function 'require'
./reader.lua:142: in main chunk
[C]: at 0x00013ef9
ffi.load: blitbuffer
```

**Comment by NiLuJe** [comment]
Is that an actual KT3, or a Kid's Edition, or, worse, the weird Android one?

**Comment by NiLuJe** [comment]
(I doubt we can do anything about the weird one, but for the rest, shell access and poking in /dev to see where the actual framebuffer character device is would be helpful ;)).

**Comment by F0KYSNIK** [comment]
this is original Kindle. If you want SN: G000 K905

**Comment by F0KYSNIK** [comment]
> (Я сомневаюсь, что мы сможем что-то сделать с этим странным, но в остальном доступ к оболочке и проникновение в / dev, чтобы увидеть, где находится фактическое символьное устройство фреймбуфера, были бы полезны;)).

ok i can. But I don't have much experience. If you can help me (what needs to be done) I can give you information

**Comment by NiLuJe** [comment]
I have a mild suspicion you might simply not be running a properly jailbroken device...

Let's see what open actually fails with:

```diff
diff --git a/ffi/framebuffer_linux.lua b/ffi/framebuffer_linux.lua
index ce09843a..78195979 100644
--- a/ffi/framebuffer_linux.lua
+++ b/ffi/framebuffer_linux.lua
@@ -48,7 +48,10 @@ function framebuffer:init()
     self._finfo = ffi.new("struct fb_fix_screeninfo")
     self._vinfo = ffi.new("struct fb_var_screeninfo")
     self.fd = C.open(self.device_node, bit.bor(C.O_RDWR, C.O_CLOEXEC))
-    assert(self.fd ~= -1, "cannot open framebuffer")
+    if self.fd == -1 then
+        local errno = ffi.errno()
+        error("cannot open framebuffer:", ffi.string(C.strerror(errno)))
+    end
     self:reinit()
     framebuffer.parent.init(self)
     -- if force rotation is on with no default, the value from parent is a bogus preset, so ask the OS directly.
```

**Comment by F0KYSNIK** [comment]
> У меня есть легкое подозрение, что у вас просто не работает взломанное устройство должным образом ...
> 
> Давайте посмотрим, с чем на самом деле не удается открыть:
> 
> ```diff
> diff --git a / ffi / framebuffer_linux.lua b / ffi / framebuffer_linux.lua
> индекс ce09843a..78195979 100644
> --- a / ffi / framebuffer_linux.lua 
> +++ b / ffi / framebuffer_linux.lua 
> @@ -48,7 +48,10 @@ функция framebuffer: init ()
>      self._finfo = ffi.new ("struct fb_fix_screeninfo")
>      self._vinfo = ffi.new ("struct fb_var_screeninfo")
>      self.fd = C.open (self.device_node, bit.bor (C.O_RDWR, C.O_CLOEXEC))
> -     assert (self.fd ~ = -1, «не удается открыть 
>     буфер кадра ») + если self.fd == -1, то 
> +         local errno = ffi.errno () 
> +         error («невозможно открыть буфер кадра:», ffi.string ( C.strerror (ошибка))) 
> +     конец
>      я: reinit ()
>      framebuffer.parent.init (сам)
>      - если принудительное вращение включено без значения по умолчанию, значение из родительского элемента является фиктивной предустановкой, поэтому спросите ОС напрямую.
> ```

Excuse me, do I need to paste this code somewhere?

**Comment by NiLuJe** [comment]
It's a patch, the filename is at the top, red lines are removed, green lines are added.

(You'll most likely have better luck looking up how patch & diff work in your native language than me trying to explain it again, given the language barrier ;)).

**Comment by F0KYSNIK** [comment]
> Это патч, имя файла вверху, красные линии удалены, добавлены зеленые.
> 
> (Скорее всего, вам больше повезет, если вы узнаете, как работают patch & diff на вашем родном языке, чем мне, пытаясь объяснить это снова, учитывая языковой барьер;)).

understood. I find out. thanks

**Comment by hius07** [comment]
Reinstalling the jailbreak has fixed the issue, thanks.
