### ISSUE TITLE
characters incorrectly displayed in highlight edit box

### ISSUE THREAD

**Issue by richo67** [koreader/koreader#8119]
* KOReader version: 2021.05(06) until now 2021.08
* Device:android, linux, appimage, kindle

#### Issue
![image](https://user-images.githubusercontent.com/9590148/130359498-43e4ce44-fed6-4751-aec9-045bba4ca233.png)

#### Steps to reproduce
Simple: create highlight and then click on it you will see dialog box as displayed above

##### `crash.log` (if applicable)
n/a: no crash

**Comment by Frenzie** [comment]
Could you please be a bit more specific as to what the problem is?

**Comment by poire-z** [comment]
> Simple: create highlight and then click on it you will see dialog box as displayed above

This dialog is just fine :) Tap `Edit` to see the plain text from your highlight.
If you mean you expect to see the text (or some other symbols we used to have) where there is the hatched gray rectangle+arrow, we don't display the start and end bits of text there - these buttons just mean you can extend the highlight's gray area (the hatched rectangle), see #7713  for how it was before and why it was changed.

**Comment by richo67** [comment]
>  see #7713 for how it was before and why it was changed.

@poire-z thanks for this link. I must say the current symbol are much easily understood as missing font/symbol/icon where the 'hatches stripes' are. I see there was some discussion about those symbols. Therefore I give up. 

If I had not seen the original symbols, I would have today no idea what those button do.
