### ISSUE TITLE
FR: Horizontally center-align images

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8125]
**Does your feature request involve difficulty completing a task? Please describe.**
When the style tweaks are enabled and the "justify most text" is selected, in some e-books the cover and images are aligned to left. While there is a "Vertically center-align images relative to text" option, there is no such option for horizontally center-alignment of the images.

**Describe the solution you'd like**
Please, add the option "Horizontally center-align images".

Thank you!

**Comment by mergen3107** [comment]
You can add your own style tweak, but you need to know the exact class where the image is stored. This can be different in epub and in fb2 books.

For example, I have an epub book (Harry Potter) that has images in the chapter beginnings in the `p.center` class. So I apply:
```
p.center {
    text-align: center;
    text-indent: 0 !important;
}
```
The zero `text-indent` makes sure that there is no inherited indent from `p`.

To know exactly, select some text and your image and tap `View HTML`. There you will see the structure. 

(FYI, just create a file `tweak1.css` or whatever and put it in koreader's `styletweaks` directory, then restart and select in the Top menu - Style tweaks - User style tweaks.)

**Comment by poire-z** [comment]
> Please, add the option "Horizontally center-align images".

That's something we can't solve.

When enabling this tweak, you change ALL paragraphs alignments from their original to "justify" - and if a paragraph contains a single image, the paragraph being justified, this image will be put to the left.
The publisher has probably set in is own styles `P.single_image_container { text-align:center }`, and this tweak actually override the publisher choice, and you lose the publisher styling.

We can't detect (at this style tweaks/CSS level) what a paragraph contains (text or a single image) to decide for different behaviours.

Style tweaks are not and can't be full proof. Sometimes, you need to do what @mergen3107 explained, to make specific tweaks tailored for this particular book - which means you need to know a bit about HTML and CSS.

(Tried something like this:
`p > img:first-child:last-child { display: inline-block; width: 100%; margin: 0 auto; }` but we are missing a container to not have the image take the full width... - and from the image, we can't go back up to style the P with CSS.)

**Comment by poire-z** [comment]
Not something we can solve generically - it has to be solved with inspecting the HTML and making the appropriate style tweaks.
