### ISSUE TITLE
Keyboard: low

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8133]
Can it be useful?

<kbd>![1](https://user-images.githubusercontent.com/62179190/130785839-b82d42de-79f5-44ab-b93c-0a4ff5962590.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/130785851-e911f923-b057-4469-9caa-b4c02609d032.png)</kbd>

**Comment by mergen3107** [comment]
Maybe for someone with large screens? Like 10 inch+

**Comment by Frenzie** [comment]
Alternatively maybe a height selector with 2 or 3 presets?
