### ISSUE TITLE
crengine: border style not applied to inline elements

### ISSUE THREAD

**Issue by hachahbar** [koreader/koreader#8156]
* KOReader version: v2021.05
* Device: Pixel 2

#### Issue
CSS rules essential to the text are not applied. 

#### Steps to reproduce

Opening the book in EPUB format "The Joy of Syntax" by June Casagrande

Here is how it looks in KOReader

![Screenshot_20210830-195951](https://user-images.githubusercontent.com/16535919/131390937-2c819dfa-be73-49e5-a03d-872bde97163e.png)

And this is the same page in Calibre

![2021-08-30_195244](https://user-images.githubusercontent.com/16535919/131391062-ec17ba96-fab0-45e4-8196-a53e42f60fa9.png)

Source code from Calibre
```
<p class="ulf">The icing is <span class="u">on</span> <span class="strk">the cake</span>.</p>
<p class="ul">They gave the promotion <span class="u">to</span> <span class="strk">Claire</span>.</p>		
<p class="ul">He served <span class="u">with</span> <span class="strk">honor</span>.</p>
<p class="ul">They are <span class="u">from</span> <span class="strk">South Carolina</span>.</p>
<p class="ul">You’re <span class="u">in</span> <span class="strk">trouble</span>.</p>
<p class="ul">It’s somewhere <span class="u">over</span> <span class="strk">the rainbow</span>.</p>
<p class="ul">Glenn is <span class="u">on</span> <span class="strk">the phone</span>.</p>
<p class="ul">They were talking <span class="u">about</span> <span class="strk">me</span>.</p>
<p class="ull">This is just <span class="u">between</span> <span class="strk">us</span>.</p>
```

You can see the formatting is added with the "u" and "strk" classes.
An embedded css.css style sheet contains the following attributes:

```
span.strk {
	border-bottom:.25em solid #808183;
	}
span.strk-3 {
	border-bottom:.25em solid #333334;
	}
span.u {
	border-bottom:.25em solid #dbdcde;
	}

```
The Issue could be related to the CoolReader engine. I have tried many readers from Google Play store  (Moon+, Prestigio, Librera, EbookDroid, AlReader, FBreader...) and Lithium was the only reader that rendered the formatting correctly.

**Comment by Frenzie** [comment]
Based on the above it looks like border may not be supported on inline elements. Let's put together a minimal testcase.

**Comment by Frenzie** [comment]
Yup, that seems to be the case. Minimal testcase based on the above attached.

[border.html.zip](https://github.com/koreader/koreader/files/7079295/border.html.zip)

**Comment by poire-z** [comment]
Indeed, we don't support any margin/border/padding on inline elements. Thought about it and it felt like it would add quite a bit of kludge in the text rendering code (lvtextfm/lvrend) - for something quite rare.

One thing to try to may be make them work a bit is via `Book style tweaks` to make them `display: inline-block`, which then should have margin/border/padding applied (but then, it would not wrap on the next line as needed, it would be fully pushed to the next line if it does not fit...)
`span.strk, span.strk-3, span.u { display: inline-block }`

(Dunno if this switch to display:inline-block could be made automatic/internal to crengine when meeting a inline element with non-zero margin/border/padding... probably not with the caveat above...)

**Comment by Frenzie** [comment]
@poire-z Does that mean text-decoration: underline isn't supported either?

**Comment by poire-z** [comment]
No, text-decoration is supported, at least for underline/overline/strike-through (with some limitations vs. specs, cf https://github.com/koreader/crengine/issues/417), fortunately, or we wouldn't have underlines for links in book TOCs and footnotes, and in Wikipedia EPUBs :)
They are just stuff we can draw under/over the glyphs as we draw them (unlike margin/padding/border left&right which needs to be accounted when measuring text, and need more complex drawing).

**Comment by Frenzie** [comment]
In that case a potentially nicer style tweak would be something like:
```css
span.strk, span.strk-3, span.u { text-decoration: underline }
.strk { text-decoration-color: text-decoration-color: #808183 }
.strk-3 { text-decoration-color: text-decoration-color: #333334 }
.u { text-decoration-color: text-decoration-color: #dbdcde }
```

**Comment by poire-z** [comment]
(We don't support text-decoration-color :/)

**Comment by Frenzie** [comment]
Well, just a thought. `text-decoration-thickness` would complete the desired look but I assume that's not supported either. :-)

**Comment by poire-z** [comment]
Limited support for inline borders (but none for inline vertical padding/margin) has been added, which will allow to get this for the above sample:
![image](https://user-images.githubusercontent.com/24273478/164467692-100f4461-1ac6-40db-b45a-5346164f27c3.png)
but this with a large line-height:
![image](https://user-images.githubusercontent.com/24273478/167134324-d9c49669-92c8-4ee4-99e9-0192debdd350.png)
