### ISSUE TITLE
CAn't seem to launch KOReader om RM2?

### ISSUE THREAD

**Issue by hunt529** [koreader/koreader#8157]
* KOReader version: 2021.08
* Device: RM2: 2.9.1.217

Package: display
Version: 1:0.0.7-1
Depends: xochitl, rm2fb-client

#### Issue

When trying to start KOReader, RM2 cycles through a reboot but simply returns to RM2 "My Files" display.

#### Steps to reproduce

1. Upgraded display via opkg upgrade display
2. installed KOreader freshest version (2021.08)
3. cp -v koreader/koreader.service /etc/systemd/system/
4. systemctl start koreader

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

Can't find a crashlog on RM2 -- any suggestions?  I am a bit or a linux newbie.
Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by CamilleHbp** [comment]
I think you need to install `remux` to be able to launch KOReader. At least the same thing happened to me, and after I fixed the `remux.service` crash at start using the following [issue](https://github.com/rmkit-dev/rmkit/issues/141), I rebooted the remarkable 2 and managed to launch KOReader through `remux`. Hope this will help!

**Comment by gbyl** [comment]
> 3. cp -v koreader/koreader.service /etc/systemd/system/
> 4. systemctl start koreader

@hunt529 These steps are not compatible with a toltec install. Toltec uses `/home/root/.entware/koreader`, but the steps you followed expect `/home/root/koreader`. I have updated the [toltec section](https://github.com/koreader/koreader/wiki/Installation-on-Remarkable#installation-via-toltec) of the wiki with the appropriate commands.

**Comment by Eeems** [comment]
> I think you need to install `remux` to be able to launch KOReader. At least the same thing happened to me, and after I fixed the `remux.service` crash at start using the following [issue](https://github.com/rmkit-dev/rmkit/issues/141), I rebooted the remarkable 2 and managed to launch KOReader through `remux`. Hope this will help!

Technically you need a launcher, not `remux` specifically. That said, toltec doesn't currently supply a systemd service file to run koreader: https://github.com/toltec-dev/toltec/issues/437. This should be resolved soon as a service file now is being provided in the toltec testing branch.

**Comment by gbyl** [comment]
@Eeems Good point. That is precisely why even after https://github.com/toltec-dev/toltec/pull/441, I decided to add a line on [the wiki](https://github.com/koreader/koreader/wiki/Installation-on-Remarkable#installation-via-toltec) suggesting the use of a launcher. How feasible would it be to have a similar message be displayed by Toltec? I can also open an issue over there to further discuss this.

**Comment by Eeems** [comment]
Opening an issue there would be best.
