### ISSUE TITLE
Standardize: value in touchmenu

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8171]
(1) `Menu item: value` or (2) `Menu item (value)`?

<kbd>![1](https://user-images.githubusercontent.com/62179190/131891482-7255e6c6-faac-4a9c-8d5c-e44b2a670e3d.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/131891494-c7013505-613a-4ed8-b43c-1a789dfe7069.png)</kbd>

<kbd>![3](https://user-images.githubusercontent.com/62179190/131891501-e9b504b3-9505-472d-a8dc-7fae34f53029.png)</kbd>

<kbd>![4](https://user-images.githubusercontent.com/62179190/131891505-69155d57-9cfb-4baa-ae51-38d52abd0f88.png)</kbd>

<kbd>![5](https://user-images.githubusercontent.com/62179190/131891511-524e45f7-1426-49ff-af6a-cad6893c22b6.png)</kbd>

<kbd>![6](https://user-images.githubusercontent.com/62179190/131891518-38dc1dee-8b6c-4bd0-b921-18d2cca417ed.png)</kbd>

**Comment by poire-z** [comment]
I added a few in my own patch, using `Menu item: value >` - which I prefer.

**Comment by hius07** [comment]
I don't think it should be changed right now everywhere, but new items and modules being edited should comply with approved variant.

**Comment by Frenzie** [comment]
The fact that I wrote many of the examples with a colon and none with parentheses probably speaks for itself.

**Comment by poire-z** [comment]
Why close? It's not yet done - so not in v2021.09 :)

**Comment by hius07** [comment]
The decision has been made: a colon approved.
Changing the code is a long story, step by step.
