### ISSUE TITLE
FR: Guide to what format dictionaries can be in

### ISSUE THREAD

**Issue by jmthackett** [koreader/koreader#8173]
Hey, 

I'm looking to add an Esperanto to English dictionary like this one:

https://raw.githubusercontent.com/wildeyedskies/vortaro/master/dictionary-src/espdic.txt

I've looked at how to reformat it into a dict file, and how to make an ifo, but the other dictionaries seem to have an idx file too. Is this mandatory? And, forgive my ignorance, but what is it for? A google tells me idx is for subtitles but checking file contents makes me think otherwise.

**Comment by mergen3107** [comment]
the .ifo is an information file, but it is quite important I think. Here is how it looks like for Longman:
```
StarDict's dict ifo file
version=2.4.2
wordcount=63647
idxfilesize=1217451
bookname=Longman Dictionary of Contemporary English 5th Ed. (En-En)
date=2011.05.19
sametypesequence=h
```
The last line `sametypesequence=` defines how KOReader will render it. Put `h` for html, `x` for something else (I don't remember, but it is usually a default, which might look worse on KOReader).

**Comment by mergen3107** [comment]
The `idx file size` is exactly what properties show (Windows 10 Explorer):
`Size: 1.16 MB (1,217,451 bytes)`
Everything else I guess is optional

**Comment by poire-z** [comment]
Adding some linkes to make this question as answered :)
https://github.com/huzheng001/stardict-3/blob/master/dict/doc/StarDictFileFormat
http://fileformats.archiveteam.org/wiki/StarDict
