### ISSUE TITLE
Underscore in dictionary not shown

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#8179]
* KOReader version:2021.08-39
* Device:Onyx Boox Nova 3 Color

#### Issue
Underscore under etter not shown in dictionary. 
#### Steps to reproduce
Look up .g.the word "gedeihen"in Duden German dictionary. Duden indicates stressed long vowel or diphthong by underscoring the letter. Colordict how's it with the same stardicyt file,but Koreader internal viewer does not.

https://user-images.githubusercontent.com/11670320/132098811-73d4948c-fc9b-4943-bdb2-2a7f585440c2.mp4

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/wiki/Dictionary-support#html-encoding-within-stardict-dictionaries-supported

**Comment by Frenzie** [comment]
Improper HTML will now also be rendered.
