### ISSUE TITLE
Standardize: long-press/hold

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8184]
As this has been approved for filechooser, can we standardize all `hold`s to `long-press`?
There are 6 entries:
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/frontend/ui/elements/common_settings_menu_table.lua#L241
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/plugins/gestures.koplugin/main.lua#L587
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/plugins/gestures.koplugin/main.lua#L593
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/plugins/gestures.koplugin/main.lua#L677
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/frontend/apps/reader/modules/readersearch.lua#L146
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/frontend/apps/reader/modules/readerstyletweak.lua#L362

**Comment by poire-z** [comment]
Fine with that.
Except may be for the two last ones that are a bit long and will get longer, and may get more chance to be truncated with "(long-press for info)" ?

**Comment by hius07** [comment]
In the readerstyletweak (main menu item) it seems there is enough space.
In the readersearch (a checkbutton) it requires to widen the input dialog a little bit (0.9).

**Comment by poire-z** [comment]
^ This depends also on your `Screen> DPI` and size. There is some value at which points lots of things get truncated. We just want this to not be truncated with values before that were only little things get truncated.
But for styletweaks, we have tweak names that are larger than what we get with using "long-press", so it should be ok.
There is also "Book specific tweak (_hold_ to edit)" at the bottom of that same menu.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/71cea5a9f6cfb9961c18346cdee76c78dbc04dcf/frontend/apps/reader/modules/readerstyletweak.lua#L362
Change `info` to `help`? (https://github.com/koreader/koreader/pull/8129#discussion_r702375675)

**Comment by poire-z** [comment]
If you want (that comment was about "infos" with a s/plural - I think @Frenzie taught me somewhere that "info" singular is just fine while "infos" is not, can't find the issue/PR with this english lesson :).

**Comment by hius07** [comment]
I'm fine with both variants so waiting for the doctor.

**Comment by Frenzie** [comment]
Info is informal (used here for space reasons), infos is ungrammatical.

**Comment by Frenzie** [comment]
Informations is French.
