### ISSUE TITLE
A button to quick call a new search

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8188]
A proposition to add a button to call a new search input dialog.
Text or icon label.

<kbd>![1](https://user-images.githubusercontent.com/62179190/132325001-bfe790b5-e112-46de-9239-3c5a279ab8d1.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/132325007-68931975-71a8-4486-ae3c-d561a2f0dfbd.png)</kbd>

**Comment by poire-z** [comment]
Not the first one (ugly text among symbols), but ok with a symbol.
Thought it could include a cursor to signify we'll get back to text input, but there is apparently no cursor symbol in Unicode https://superuser.com/questions/548862/is-there-a-text-caret-unicode-character - unless a vertical bar could just work?

**Comment by hius07** [comment]
> but there is apparently no cursor symbol in Unicode

It's our appbar.search icon on the screenshot.

**Comment by poire-z** [comment]
I'm usually not fond of mixing text symbols and svg icons (could cause sizing or alignment issues).
So, if there's a/some unicode symbol that would look alright instead, that would be nice.

**Comment by zwim** [comment]
Could this be of interest: 🔎 https://www.compart.com/de/unicode/U+1F50E?

**Comment by hius07** [comment]
Icons support is built-in to button.lua, we have a good, standard, already used icon.
I've changed dpi, rotation - all okay.
How can it be tested more for sizing or alignment issues?

**Comment by poire-z** [comment]
@zwim, we also have nerdfont, see the bottom of https://github.com/koreader/koreader/pull/8078#issuecomment-899086618

@hius07 : well, _could cause_ doesn't mean you'll manage to experience any issue in this case - it was more of a generic point.
If there's no unicode symbol, and as our search icon is correctly centered and has a thickness similar to the arrows, you can go with it I guess.

**Comment by hius07** [comment]
> correctly centered and has a thickness similar to the arrows

The screenshot is a real screenshot, no photoshop, with DGENERIC_ICON_SIZE*0.8 which seems can be a default size for icons in buttons, smaller than icons in IconButton.

**Comment by poire-z** [comment]
Well, if that works for you and it looks ok with the other Buttons non-IconButtons that would use icons (dunno which other ones we have), why not.
If our text Buttons all use the Button default face font size that will get the same scaleBySize treatment than DGENERIC_ICON_SIZE gets.
