### ISSUE TITLE
Dialogs width in landscape mode

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8192]
As e-readers are mostly used in the portrait mode, all dialogs are designed to fit the screen width of that mode.
The dialog width is flexible, so when switching to the landscape mode we get unnecessary wide  dialogs.

EG
<kbd>![w1](https://user-images.githubusercontent.com/62179190/132472950-a0f0928e-3a08-42d2-a76b-17e111a4a226.png)</kbd>

<kbd>![w2](https://user-images.githubusercontent.com/62179190/132472971-b29af550-9485-4404-b999-6eaa6f58d0cf.png)</kbd>

Isn't it better to have the dialog width fixed for both modes?

<kbd>![w3](https://user-images.githubusercontent.com/62179190/132473082-9dfbdbd7-51d5-40bc-8761-529a5455d226.png)</kbd>

Inspired by https://github.com/koreader/koreader/pull/8182#issuecomment-914026066.

**Comment by Frenzie** [comment]
Think of the Russians. ;-)

But what do you mean by "fixed", exactly?

**Comment by hius07** [comment]
> But what do you mean by "fixed", exactly?

https://github.com/koreader/koreader/pull/8182#issuecomment-914034127

**Comment by poire-z** [comment]
I would agree: if the portrait mode width is wide enough and nobody complained, it can be used for landscape mode.
(I expect that the scalingByDpi/scaleBySize (ffi/framebuffer.lua) will be the same in portrait and in landscape, so font and sizes shouldn't change.)
There are probably a lot to change (the SpinWidget and DoubleSpinWidgets are the most ugly in landscape mode, like Word Spacing/Expansion)

**Comment by hius07** [comment]
> SpinWidget and DoubleSpinWidgets are the most ugly

Let's start with them (after https://github.com/koreader/koreader/pull/8129).

**Comment by Frenzie** [comment]
Could you provide some more info over where you can find 0.6 to test? I
have some doubts.

**Comment by hius07** [comment]
After starting in landscape mode all dialogs are extra wide:

<kbd>![1](https://user-images.githubusercontent.com/62179190/132495930-6e617e8c-d010-4bc9-924d-c8a458f93f44.png)</kbd>

<kbd>![2](https://user-images.githubusercontent.com/62179190/132495941-23841c44-3352-4f49-91d9-d637f12afc88.png)</kbd>

<kbd>![3](https://user-images.githubusercontent.com/62179190/132495946-84a941c2-a717-4d54-8e1b-57b43d3263c2.png)</kbd>

<kbd>![4](https://user-images.githubusercontent.com/62179190/132495951-2612d23c-e9fe-4862-bf8e-ae48bce8aeba.png)</kbd>

<kbd>![5](https://user-images.githubusercontent.com/62179190/132495956-47608f7d-3954-46e1-a0a3-cfa6d341b197.png)</kbd>

**Comment by Frenzie** [comment]
Sure, it's more that 0.6 itself I have my doubts about.

Think more like

x = max 500 or 0.6
y = min x or 0.9

For example

**Comment by hius07** [comment]
<kbd>![1](https://user-images.githubusercontent.com/62179190/132973339-2998b253-17e6-4013-be24-8b6799d86ce2.png)</kbd>

Bug in the title of DoubleSpinWidget.
Will be fixed in the first round of dialogs width standartization.

A question:
(Double)SpinWidget has a closebutton (rightmost `x` in the title bar).
Most of the non-fullscreen dialogs do not have it: InputDialog, MultiInputDialog, Open with dialog, etc.
Is it needed in SpinWidget?
Doesn anybody close it with this small `x` instead of the `Close` button or just tapping outside of the widget?

**Comment by Frenzie** [comment]
That does seem a bit odd if the others don't have it.

**Comment by hius07** [comment]
All fullscreen dialogs have CloseButton.
Among non-fullscreen dialogs only spinwidgets (spin, double, time, date) and Frontlight widget have it.

**Comment by Frenzie** [comment]
The dictionary does too.

**Comment by hius07** [comment]
I am not against the close button (although it's small and might be uncomfortable https://github.com/koreader/koreader/issues/7895), just for consistency reasons.

**Comment by poire-z** [comment]
I'm fine with not having it on non-(&nearly-non)-fullscreen dialogs (and it's also a bit painful to code and align correctly).
The dictionary is a bit special, has it can be either small or nearly full screen, so it might need the close button in full screen mode - and we devs might want to not have to handle these 2 cases differently :)

(I think I have seen recently a dict title (or wikipedia article) overflow the dialog (or just overflow the x of the close button, I don't remember.)

**Comment by hius07** [comment]
I would remove it from spinwidgets.

**Comment by poire-z** [comment]
> I'm fine with not having it on non-(&!nearly-non)-fullscreen dialogs (and it's also a bit painful to code and align correctly).
The dictionary is a bit special, has it can be either small or nearly full screen, so it might need the close button in full screen mode - and we devs might want to not have to handle these 2 cases differently :)

May be another we to see this:
- full screen and nearly full screen dialogs should have a "x" at top right, and they may have a Close or Cancel button at bottom
- small dialogs which do not have a Close or Cancel button (which is the case of the Dictionary) should have a "x" at top right

(Some small dialogs like InputDialog are not closable by tap outside, but they all have a Cancel or Close button.)

**Comment by hius07** [comment]
Agree in full.
(I see the `Close` button in the small dictionary window, but let it have `x` for consistency with its large window)

**Comment by poire-z** [comment]
> I see the Close button in the small dictionary window

Oh, yes, it does :) (It's possible it didn't have it some years ago.)
(Writing specs after the implementation feels like it would be easy - but it's not :)
