### ISSUE TITLE
FR: Combine 2 steps More tools->Plugin Management into 1 step

### ISSUE THREAD

**Issue by yukari186** [koreader/koreader#8193]
**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.
![IMG_20210908_165348_431](https://user-images.githubusercontent.com/90317108/132488641-aa4a39b6-40e4-4886-aecb-65856130025e.jpg)
![IMG_20210908_165337_378](https://user-images.githubusercontent.com/90317108/132488648-77c4e309-28a6-413f-bf5d-de4ba510c2f9.jpg)

Clicking 2 steps: More tools -> Plugin management is annoying really. This is so much blank space to add other rows, no need to click 2 steps. I hope we can combine 2 steps into 1 step.

**Comment by Frenzie** [comment]
The reason it's so empty in there is that you've disabled everything. That's a valid thing to do, but it seems to me you just want to create a personal menu override.

**Comment by yukari186** [comment]
I've disabled it because I don't need to use them. I try to turn on all plugins and wonder why plugins are in the picture on list 2 instead of the same list 1 as other plugins. We can put them in the same list 1.

![IMG_20210908_212608_015_1_1](https://user-images.githubusercontent.com/90317108/132528664-3248a6eb-93a0-41a3-96e2-3149fadac686.jpg)

**Comment by pazos** [comment]
> I've disabled it because I don't need to use them.

IMHO that's the right thing to do. Disable stuff you don't need. Less clutter in UI :)

> I try to turn on all plugins and wonder why plugins are in the picture on list 2 instead of the same list 1 as other plugins

`More tools` has stuff that is not related to plugins, like advanced settings and developer options. The reason to put other plugins there is to avoid pagination in the case you have all/more plugins enabled.

> We can put them in the same list 1.

In a perfect world we will try to discern between plugins and the `tools` menu. Not all the plugins are placed in the tools menu, like cover browser, autostandby, opds or system stats.

It just happen there isn't a better place to put stuff like calibre, wallabag, cloud storage or the news downloader.

Feedback is very welcome and we might change things if we reach a consensus but a personal menu override is the way to go to get the menu as you want, very quickly and without any kind of agreement.

**Comment by yukari186** [comment]
Thanks for all replies, but I can't search any results with the keyword "personal menu override" 😥 Did I make any mistakes?

**Comment by Frenzie** [comment]
I described it here: https://github.com/koreader/koreader/pull/2601#issuecomment-283677041

I'm not sure if it's been described better since.

Basically, create a file named `filemanager_menu_order.lua` and/or `reader_menu_order.lua` in your settings folder, with something like:
```lua
return {
    tools = {
        "read_timer",
        "calibre",
        "exporter",
        "statistics",
        "progress_sync",
        "move_to_archive",
        "wallabag",
        "news_downloader",
        "send2ebook",
        "text_editor",
        "qrclipboard",
        "profiles",
        -- Remove or comment out unwanted stuff.
        --"----------------------------",
        --"more_tools",
        -- Add what we do want.
        "plugin_management",
    },
    -- You'll probably have to tell the menu to ignore this one.
    ["KOMenu:disabled"] = {
        "more_tools",
    }
}
```

Defaults:
https://github.com/koreader/koreader/blob/084ae1509d258a4ada6bb6e19b0f9d98bb87f7c9/frontend/ui/elements/reader_menu_order.lua
https://github.com/koreader/koreader/blob/084ae1509d258a4ada6bb6e19b0f9d98bb87f7c9/frontend/ui/elements/filemanager_menu_order.lua

**Comment by yukari186** [comment]
Wow, that's a fantastic solution! I have done what I wanted based on the above instructions. I close the issue here. Thanks again for ur help.
