### ISSUE TITLE
Auto hidden key popup after typing

### ISSUE THREAD

**Issue by yukari186** [koreader/koreader#8202]
I am testing a keyboard layout in my language. Replacing the key popups is a simple solution. I rewrote the code completely and everything seems to be working fine. However, when I try to type, the popup keys are not automatically hidden after typing which is very inconvenient. Does anyone of you guys fix this problem? Thank you so much.

![Screenshot_20210910-175356](https://user-images.githubusercontent.com/90317108/132844217-4322d669-eb6e-48d5-a9b0-dd566540961e.png)
![Screenshot_20210910-175406](https://user-images.githubusercontent.com/90317108/132844222-ce250075-a4c7-4ebc-8dd8-22d66ccb81b0.png)

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by hius07** [comment]
Until (if) this will be changed, you can long-press a character to input it and close the popup.

**Comment by yukari186** [comment]
> Until (if) this will be changed, you can long-press a character to input it and close the popup.

Yeah, can only do that for now. But some large key popups will cover some characters on the keyboard (images on the article), and I can't type those characters. I hope it will be fixed soon

**Comment by poire-z** [comment]
> I am testing a keyboard layout in my language

Just curious, what is this language ? :)

But you're still testing/working on some older version of KOReader's keyboard, so your work may need to be reworked :/

We've updated the keyboards layout some weeks ago, with different rules/logic, that your new layout should try to adhere to : see https://github.com/koreader/koreader/pull/8089 for info about all the changes and new rules.

ie: north popup should now be the corresponding uppercase letter:
![image](https://user-images.githubusercontent.com/24273478/132848221-32e4a68d-5198-4fed-951e-641505ed17f3.png)

**Comment by yukari186** [comment]
> > I am testing a keyboard layout in my language
> 
> Just curious, what is this language ? :)
> 
> But you're still testing/working on some older version of KOReader's keyboard, so your work may need to be reworked :/
> 
> We've updated the keyboards layout some weeks ago, with different rules/logic, that your new layout should try to adhere to : see #8089 for info about all the changes and new rules.
> 
> ie: north popup should now be the corresponding uppercase letter:
> ![image](https://user-images.githubusercontent.com/24273478/132848221-32e4a68d-5198-4fed-951e-641505ed17f3.png)

I'm too lazy to take a picture of my kobo, images on the topic are my android phone screenshot, and the picture below is my kobo. All my devices have been installed the latest stable version of koreader 08.2021, I don't have the habit of updating the nightly version.

I just changed the characters displayed on the key popup of 26 alphabets to input Vietnamese, in addition, I did not interfere with any other code, so you update the keyboard layout will not affect it. Maybe Vietnamese users are too few, so the publisher's support for keyboard layout is often not helpful for typing Vietnamese. Right now I just hope key popups can auto-hide after typing to input easier. Please let me know If you have solved this problem in recent nightly versions. Thanks so much!

![IMG_20210910_185225_789_1](https://user-images.githubusercontent.com/90317108/132850731-248f7350-4514-44b3-a96c-b800fec949f9.jpg)

**Comment by Frenzie** [comment]
> We've updated the keyboards layout some weeks ago, with different rules/logic, that your new layout should try to adhere to : see #8089 for info about all the changes and new rules.

This specific behavior remains the same though. It is by design, i.e., hold and let go for auto dismiss, while long-press, let go, and tap will not.

**Comment by yukari186** [comment]
> > We've updated the keyboards layout some weeks ago, with different rules/logic, that your new layout should try to adhere to : see #8089 for info about all the changes and new rules.
> 
> This specific behavior remains the same though. It is by design, i.e., hold and let go for auto dismiss, while long-press, let go, and tap will not.

Long press and let go, the key popup will disappear, but this behavior is not sensitive on "a" character key, both my kobo and android devices (checked on the original version of the publisher). Someone help me check my device or application has a bug, please?

**Comment by NiLuJe** [comment]
Yep, that's the workaround for the much more annoying issue that happens when the pop-up has to be moved when it would do off-screen.
I don't recall having thought of a better way to deal with it :/.

**Comment by mergen3107** [comment]
> Maybe it conflicted with the swipe gesture to +- front light

A side question: are gestures supposed to to be triggered when the keyboard is open?

**Comment by mergen3107** [comment]
> Maybe Vietnamese users are too few, so the publisher's support for keyboard layout is often not helpful for typing Vietnamese.

There was a least one request recently that I know of: #8041 by @vietchovui , so you could probably discuss what is best for you Vietnamese-specific.

Also, I noticed that you on your last screenshot of the `a` popup you have some `a` letter with two diacritics. Is this really what you want? Looking at the Vietnamese [alphabet](https://en.wikipedia.org/wiki/Vietnamese_alphabet), I don't see, for example, the letters that you have on east, west, south. You should probably remove those doubled diacritics - in the text editor they are tricky to find, because they sort of "stack" on top of the blinking cursor, and if you have a letter there, so might easily miss them altogether.

**Comment by Frenzie** [comment]
Not those. Why, are they?

**Comment by mergen3107** [comment]
No, they don't :)

**Comment by yukari186** [comment]
> > Maybe Vietnamese users are too few, so the publisher's support for keyboard layout is often not helpful for typing Vietnamese.
> 
> There was a least one request recently that I know of: #8041 by @vietchovui , so you could probably discuss what is best for you Vietnamese-specific.
> 
> Also, I noticed that you on your last screenshot of the `a` popup you have some `a` letter with two diacritics. Is this really what you want? Looking at the Vietnamese [alphabet](https://en.wikipedia.org/wiki/Vietnamese_alphabet), I don't see, for example, the letters that you have on east, west, south. You should probably remove those doubled diacritics - in the text editor they are tricky to find, because they sort of "stack" on top of the blinking cursor, and if you have a letter there, so might easily miss them altogether.

Using 1 letter with 2 diacritics because I am not professional enough to be able to interfere too much with the code (ex: combine 2,3 key a+w=ă, a+w+r=ẳ). I only use the Vietnamese keyboard to search for file names and lookup dictionaries. I consulted the topic you suggested before doing this and it didn't help much.

**Comment by vietchovui** [comment]
I have no knowledge of coding. But if we change keyboard layout to write Vietnamese, it's very time consuming, not practical because Vietnamese characters have a lot of diacritics in the same words. But I guess it's hard to integrate TELEX or VNI input methods into koreader. Still hope. :))
https://en.wikipedia.org/wiki/Telex_(input_method)#:~:text=Telex%20or%20TELEX%20(Vietnamese%3A%20Qu%E1%BB%91c,and%20touchscreens%20and%20also%20computers.
http://vietunicode.sourceforge.net/inputmethod.html

**Comment by yukari186** [comment]
> I have no knowledge of coding. But if we change keyboard layout to write Vietnamese, it's very time consuming, not practical because Vietnamese characters have a lot of diacritics in the same word. But I guess it's hard to integrate TELEX or VNI input methods into koreader. Still hope. :))
> https://en.wikipedia.org/wiki/Telex_(input_method)#:~:text=Telex%20or%20TELEX%20(Vietnamese%3A%20Qu%E1%BB%91c,and%20touchscreens%20and%20also%20computers.
> http://vietunicode.sourceforge.net/inputmethod.html

I only change some characters displayed, this doesn't affect if typing without accents or English. This way has helped me to input Vietnamese when needed, but I don't want to use it usually because takes more time. I think that we have a right to hope about TELEX or VNI keyboard, although hope is extremely small 😖

**Comment by yukari186** [comment]
I solved the problem, so this topic is close here.
