### ISSUE TITLE
Wrong directions in a message

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8203]
#### Issue
In the message https://hosted.weblate.org/translate/koreader/koreader/en/?checksum=be494311833ed3cd there is the following directions for the option "Invert page turn taps and swipes":
"You may also want to enable, in the top menu → Gear → Navigation →, Invert page turn taps and swipes."

I thing that there is a mistake in these directions, and the correct path to find this option is:
top menu → Gear → Taps and gestures → Page turns → Invert page turn taps and swipes

Could you correct it, please, if you thing I'm right?

Thank you!

**Comment by Frenzie** [comment]
Overlooked in https://github.com/koreader/koreader/pull/8022.
