### ISSUE TITLE
fb2.zip: Segmentation fault on exit

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8221]
Kindle Voyage
v2021.08-77-g0af6500c_2021-09-14
Open fb2.zip, choose Exit - Restart KOReader
```
CRE WARNING: cached rendering is invalid (style hash mismatch): doing full rendering
09/16/21-07:08:49 INFO  quitting uimanager
09/16/21-07:08:49 INFO  no dialog left to show
lipc-wait-event exited normally with status: 0
Segmentation fault

```
Occurs with both Start with: last file and Start with: file browser.
No issue with fb2, epub, txt (haven't tried cbz).

---

Not related, maybe of interest, restarting with pdf opened, restarted well:
```
09/16/21-07:07:18 INFO  setting zoom mode to columns
warning: expected name after CMapName in cmap
09/16/21-07:07:34 INFO  quitting uimanager
09/16/21-07:07:34 INFO  no dialog left to show
lipc-wait-event exited normally with status: 0
warning: ... repeated 3 times ...

```

**Comment by poire-z** [comment]
I don't get this on the emulator or my Kobo with some fb2.zip I had.
Might depend on a specific fb2.zip ?
Or possibly, you had it opened with a previous koreader version, a cache file was made, and you re-opened it with a later koreader version which has new stuff that needs a full re-load or re-rendering, and in these conditions a crash happen ? (really hard to foresee what may go wrong in such cases)
Make a backup of your koreader/cache/cr3cache/ just in case we need to investigate/reproduce, clean this directory, and try again. Any change ?

**Comment by hius07** [comment]
Thanks, will try later.

**Comment by hius07** [comment]
Unfortunately actions with cache gave nothing.
Brand new book, the same issue. Current setting: Start with: file browser.
[1.fb2.zip](https://github.com/koreader/koreader/files/7176791/1.fb2.zip)
[crash.log.txt](https://github.com/koreader/koreader/files/7176794/crash.log.txt)

**Comment by poire-z** [comment]
Got the file, but still can't reproduce on the emulator or my Kobo :/
What's the workflow when you say "start with file browser" ? Your top post mentionning using "Restart", so you are restarted in File browser, and you must open this book in some way (via History, Last file, File browser... ?)

I also nowhere get:
`CRE WARNING: cached rendering is invalid (style hash mismatch): doing full rendering`
which should really not happen in normal circumstances with FB2 given that they don't have much styling.
So, I suspect your own style tweaks :)
Try without any. Try to pinpoint if any specific one cause the issues and others don't...

If someone else with a Kindle can check if he get the crash or not, just so we know if it's general or not.

**Comment by hius07** [comment]
Cache and cr3/cache empty. Current setting: Start with: file browser. No user style tweaks.
Start KOReader, in the filebrowser open 1.fb2.zip, then choose main menu Exit - Restart KOReader.
Segmentation fault.
[crash.log.txt](https://github.com/koreader/koreader/files/7177237/crash.log.txt)
No issue with this (or any) book unzipped.

**Comment by poire-z** [comment]
> then choose main menu Exit - Restart KOReader

A) Is that important ? If you open another and re-open that book in the same session ?
B) And if you Exit > Exit - and relaunch KOReader via another Kindle way (or even after a reboot) ?
C) happens with all fb2.zip ?
D) since when ? Any previous KOReader you're sure it didn't happen?

**Comment by hius07** [comment]
A) It is not important, but interesting to understand.
B) The same issue after rebooting Kindle. Any other ways of launching/opening any books work fine.
C) The same issue with all fb2.zip
D) The same issue on 08 release and the latest nightly **clean install**.

Looking into the log, it seems that the program exits well, and then cannot start.
It is strange for the current setting of Start with: file browser, no need to reopen the book.
So, maybe unzipping (in previous opening) causes some problems in the (Kindle) system.

**Comment by poire-z** [comment]
> It is strange for the current setting of Start with: file browser, no need to reopen the book.

OK, so may be it has nothing to do with crengine (which was my main focus).
So, it's really not a crash on close ? You really need to relaunch KOreader to get the crash?

Hope @NiLuJe gets an idea, and/or can reproduce on a Kindle.

**Comment by hius07** [comment]
> You really need to relaunch KOreader to get the crash?

Exactly.

**Comment by hius07** [comment]
Tried cbz - no issue.

**Comment by hius07** [comment]
segfault in reader.lua can be seen in the kindle syslog (gz)
[messages_00000346_20210916180004.gz.txt](https://github.com/koreader/koreader/files/7179067/messages_00000346_20210916180004.gz.txt)

**Comment by mergen3107** [comment]
Maybe some problems with zip archive’s code page? If you zip the fb2 again with 7z, does it behave?

**Comment by NiLuJe** [comment]
Is the file visible straight away in the file manager?

**Comment by poire-z** [comment]
@ you two Kindle owners (if i'm not mistaken :) there is a sample fb2.zip at https://github.com/koreader/koreader/issues/8221#issuecomment-920766011 - can you try it on your Kindle, so we know if it's a general issue, or if it's only related to @hius07 setup.

**Comment by hius07** [comment]
> Is the file visible straight away in the file manager?

Not sure I understand what you mean.
Usual books from flibusta, visible in file manager in classic or detailed view.

**Comment by hius07** [comment]
A suspicious thing is that immediately after rebooting the Kindle I can restart the program with opened fb2.zip **only once**. After that restarting cases segfault.

**Comment by NiLuJe** [comment]
> > Is the file visible straight away in the file manager?
> 
> Not sure I understand what you mean.
> Usual books from flibusta, visible in file manager in classic or detailed view.

I meant is the file visible from the Home folder's first page (i.e., what KOReader boots into ;p).

**Comment by poire-z** [comment]
@hius07 : one thing you can try: rename this `something.fb2.zip` to `somethingelse.fb2` (remove the .zip extension). This should change nothing for crengine, that will be asked to open the file and will itself find out it's a zip (the extension does not matter for crengine).
Just to see if it's by chance related to the little bit of code that open zip files to look for the extension of the first file to decide which engine to use.

**Comment by NiLuJe** [comment]
I assume it does indeed work, given the above:

> No issue with this (or any) book unzipped.

**Comment by NiLuJe** [comment]
I can't reproduce on a PW2 @ FW 5.9.7 on today's nightly, FWIW.

But since I had launched a debug build before dinner, [here it is](http://files.ak-team.com/niluje/kopub/koreader-kindlepw2-debug-v2021.08-80-ga4763a61_2021-09-16.zip).

You should be able to attach GDB to it via something like `/mnt/us/usbnet/bin/gdb -p $(pidof reader.lua | cut -f2 -d' ')`, it'll stop on attach, so enter `c` to resume, and then `bt full` to get a backtrace when it actually crashes.

**Comment by hius07** [comment]
> remove the .zip extension

No crash on the same files renamed from fb2.zip to fb2.

**Comment by hius07** [comment]
The crash on next restart is caused with this line
https://github.com/koreader/koreader/blob/a4763a613fc79e31f25bcc5e333913d7f8e6ccf3/frontend/document/credocument.lua#L72

**Comment by mergen3107** [comment]
@hius07 
Is the name of the fb2 file itself Cyrillic?

If so, hello [again](https://github.com/koreader/koreader/issues/8074#issuecomment-899498551), unzip... So may it is time KOReader starts shipping with its own unzip?

**Comment by mergen3107** [comment]
(in my case on Android I solved this issue by replacing the unzip binary in the /system/bin/ . I don't have Kindle anymore, so I don't know how to solve it there.)

**Comment by hius07** [comment]
> Is the name of the fb2 file itself Cyrillic?

No, no cyrillic symbols: https://github.com/koreader/koreader/issues/8221#issuecomment-920766011

More testing:
-open fb2.zip, try to restart - crash
-open fb2.zip, switch to filebrowser, try to restart - crash
-open fb2.zip, switch to other non-fb2.zip book, try to restart - **no crash**

**Comment by hius07** [comment]
Kindle PW4, 2021.07-20 the same crash.

**Comment by hius07** [comment]
> open fb2.zip, switch to other non-fb2.zip book, try to restart - **no crash**

Obviously, the issue is something Kindle specific, but ^^ is of interest imo.

**Comment by mergen3107** [comment]
The file name is `Knausgord_Moya-borba_3_Detstvo.CrRzPg.633988.fb2`. Maybe unzip trips because there is more than one periods? So it might just confuse what the extension is. Could you try renaming thee file to just `name.fb2`, zip and try to open again?

**Comment by hius07** [comment]
No, not related.
I created a new file with just one symbol in it, named it 1.fb2.zip, opened it (see just the symbol), restart - crash.

**Comment by yparitcher** [comment]
confirmed crash with PW4 5.10.1.3 ~ latest commit (self built)
Only crashes when on page 2+, on page 1 (cover) it works fine.

**Comment by yparitcher** [comment]
the segfaut is happening here:
https://github.com/koreader/koreader/blob/a4763a613fc79e31f25bcc5e333913d7f8e6ccf3/reader.lua#L364
Possibly a problem with the lua state?

**Comment by poire-z** [comment]
Something to try with this snippet: add propers `std_out:close()`
```lua
function CreDocument:zipContentExt(fname)
    local std_out = io.popen("unzip ".."-qql \""..fname.."\"")
    if std_out then
        for line in std_out:lines() do
            local size, ext = string.match(line, "%s+(%d+)%s+.+%.([^.]+)")
            -- return the extention
           if size and ext then  HERE return string.lower(ext) end
        end
         HERE
    end
end
```

**Comment by yparitcher** [comment]
It also crashes on regular exit

**Comment by hius07** [comment]
> It also crashes on regular exit

Nice point, I haven't looked into the crash.log after exit.

**Comment by poire-z** [comment]
And with a full read() and a static return value ?
```lua
                output = std_out:read("*all")
                std_out:close()
                return "fb2"
```

**Comment by hius07** [comment]
Sorry, I cannot test right now.

**Comment by yparitcher** [comment]
this works with this file, needs some fixup to make sure it works when the zipp doesn't have a matching ext
```lua
-- NuPogodi, 20.05.12: inspect the zipfile content
function CreDocument:zipContentExt(fname)
    local std_out = io.popen("unzip ".."-qql \""..fname.."\"")
    if std_out then
        local size, ext
        for line in std_out:lines() do
            size, ext = string.match(line, "%s+(%d+)%s+.+%.([^.]+)")
            -- return the extention
            if size and ext then break end
        end
        std_out:close()
        return string.lower(ext)
    end
end
```

**Comment by hius07** [comment]
Confirm, `std_out:close()` fixed the issue, thanks.

**Comment by hius07** [comment]
> needs some fixup to make sure it works when the zip doesn't have a matching ext

A brief summary of current behaviour.

**(1)** double-extention zip archives (fb2.zip, html.zip, log.zip, md.zip, txt.zip) are opened with CRE.
If the file inside zip doesn't have supported extention, KOReader quits:
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/apps/reader/readerui.lua#L784-L808
zip with epub inside cannot be opened.

**(2)** single-extention zip archives are opened with MuPDF because of higher weight:
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/document/credocument.lua#L1361
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/document/pdfdocument.lua#L370
If the file(s) inside zip aren't pictures (jpg etc.), we have:
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/apps/reader/readerui.lua#L606
zip with pdf inside cannot be opened.

**(3)** single-extention zip archives with CRE supported files inside can be opened via Open with dialog. Then see (1).

---

After the fix there is no segfault in any case.

Should we change anything in the current handling of zip archives?
Should we increase the weight of CRE to handle single-zip archives with it?
Should we check for supported extention within zip archive earlier? Say, here:
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/apps/filemanager/filemanager.lua#L215-L219

**Comment by poire-z** [comment]
> Say, here: `koreader/frontend/apps/filemanager/filemanager.lua`

Probably not here.
This should better be done in frontend/document/documentregistry.lua : this is the one that should check the content of the zip to decide about which other provider can be used with it (assuming mudpf/pdfdocument works fine with stuff in a zip).

But I never had any document in a zip (except some fb2.zip samples :) - so I don't care much about this issue/enhancement (and the work/testing involded) :/
