### ISSUE TITLE
Screenshot is not saving. 

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#8224]
* KOReader version: latest 8.2021 
* Device: Samsung galaxy Tab A 8" (t295) and android version is 11

#### Issue I tried to use the built-in koreader screenshot using the hold gesture. 
![Screenshot_20210917-205430](https://user-images.githubusercontent.com/70109540/133833436-d8fb5201-457f-4797-9af8-a49d63872e30.jpg)
And I didn't find the file that koreader saved the screenshot in, so tried to change the folder for saving and koreader couldn't access (I think) the device storage or the external storage (I remember changing it to the external storage long time ago) and now I can't get it back to the default saving file. 
![Screenshot_20210917-205411](https://user-images.githubusercontent.com/70109540/133834101-7e01a6db-8c33-4222-9c2d-abc81643c77d.jpg)
And when I try to view the saved file koreader crashes. 
![Screenshot_20210917-204919](https://user-images.githubusercontent.com/70109540/133834216-f0452808-b1c7-44ef-9547-c514a764b10c.jpg)

And I hope you take a look at https://github.com/koreader/koreader/issues/8160

Thank you guys.

**Comment by pazos** [comment]
KOReader can't write in the sdcard.

**Comment by poire-z** [comment]
Dunno how this did happen (you managed to navigate there to select this folder, but now, you can't navigate out of there?).
But you can probably help yourself by deleting this setting in your koreader/settings.reader.lua, the line with `["screenshot_dir"] = ...,`.
Dunno if we need to check it's writable when using it, and fallback if not.
Or provide a hold_callback on all the directory choosing menu items to reset it to the default value.

**Comment by Zeyadas** [comment]
>  (you managed to navigate there to select this folder, but now, you can't navigate out of there?).

Exactly that's the case.
I'll try your suggestions.
