### ISSUE TITLE
crash.log: loaded plugin

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8228]
Every start of the program, then every opening a book, then every switching to file browser and back we have a record in the crash.log
https://github.com/koreader/koreader/blob/859327dea58cfa2b3c634b5ae4ecc1008b8c6f23/frontend/apps/filemanager/filemanager.lua#L528
and the same from reader.
Is it necessary? Can it be changed to the debug info to lighten regular crash.log?

**Comment by poire-z** [comment]
I exactly do this in my own patch.
```diff
-            logger.info("RD loaded plugin", plugin_module.name,
+            logger.dbg("RD loaded plugin", plugin_module.name,
```

No real idea if it can be useful for some users, to know one plugin has loaded correctly - and/or if we need to do something to log them only once for FM and only once for RD.
Pinging @zwim @yparitcher : has this ever been useful to you when developping your own plugins ?

**Comment by zwim** [comment]
The message is/was usefull. But it would be no problem if it is changed from logger.info to logger.dbg

**Comment by NiLuJe** [comment]
Keep in minds that there's one in filemanager and one in reraderui ;).

**Comment by hius07** [comment]
@NiLuJe, I have permanently errors in crash.log about these kindle fonts
`cannot register font </usr/java/lib/fonts/Caecilia_LT_66_Medium_Italic.ttf>`
`cannot register font </usr/java/lib/fonts/Caecilia_LT_76_Bold_Italic.ttf>`

May I change to `true`? (I've tried and the errors have gone)
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/fontlist.lua#L76
https://github.com/koreader/koreader/blob/ed684456264b18d6e71fa3a63a6c86aad028b6a2/frontend/fontlist.lua#L78

**Comment by NiLuJe** [comment]
It possibly depends on FW version, but, sure, go ahead ;).

**Comment by yparitcher** [comment]
> The message is/was usefull. But it would be no problem if it is changed from logger.info to logger.dbg

Same here
