### ISSUE TITLE
In the lasted Kernel 5.4.70 of Remarkable 2  has been removed /opt partition

### ISSUE THREAD

**Issue by bg3qt** [koreader/koreader#8231]
* KOReader version:
* Device: Remarkable 2

#### Issue
Linux reMarkable 5.4.70 #1 SMP PREEMPT Thu Aug 5 23:25:37 UTC 2021 armv7l GNU/Linux
it has been removed  /opt folder, so the scirpt has some issue when create the folder: /opt/tmp

**Comment by gbyl** [comment]
@bg3qt Have you tried running `toltecctl reenable` as described in the [installation guide](https://github.com/koreader/koreader/wiki/Installation-on-Remarkable#installation-via-toltec)? The command was first introduced [here](https://github.com/toltec-dev/toltec/pull/391). If the problem persists, I suggest opening an issue in the [toltec repository](https://github.com/toltec-dev/toltec/issues) as well.

**Comment by bg3qt** [comment]
> @bg3qt Have you tried running `toltecctl reenable` as described in the [installation guide](https://github.com/koreader/koreader/wiki/Installation-on-Remarkable#installation-via-toltec)? The command was first introduced [here](https://github.com/toltec-dev/toltec/pull/391). If the problem persists, I suggest opening an issue in the [toltec repository](https://github.com/toltec-dev/toltec/issues) as well.

I've never updated reMarkable firmware. When installing Toltec, download and run the bootstrap script, I found it need to create /opt/tmp folder, but /opt/ partition has been removed in my reMarkable2 (Linux kernel 5.4.70).

**Comment by gbyl** [comment]
>but /opt/ partition has been removed in my reMarkable2 (Linux kernel 5.4.70).

That usually happens after a firmware update. It is possible that auto-update was on. The `/opt` directory is just a symbolic link of `/home/root/.entware`. You should be able to find all your files there even if `/opt` was removed somehow.

**Comment by bg3qt** [comment]
I did nothing, when I got the device, it is already Kernel 5.4.70.
