### ISSUE TITLE
App Icon Design

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8235]
@Zeyadas in another thread said something about updating the app icon.

I like logos and I am kinda bored right now so I made this for myself to see what I will come up with. 
I liked the result so I am sharing it here. 

It is faithful to the original design with bookmark and icon color. I designed it with a MacOS aesthetic and a clean style. I don't know who decides about this type of changes but here is my design if anyone is interested: 

![logo sizes](https://user-images.githubusercontent.com/84420582/134013524-72f2a0f1-9341-44e6-a6c4-ccc9bc9d38a5.png)

Bottom row: 128, 64, 32 px sizes and grayscale

**Comment by Zeyadas** [comment]
>  I don't know who decides about this type of changes 

Me too, both are awesome.
Maybe we should call @Frenzie

**Comment by poire-z** [comment]
I don't feel we need a logo change, I find the one we have really good (*).
What I like about it and what made it stand out from the other proposals at the time:
> I prefer all those from https://github.com/koreader/koreader/issues/2000#issuecomment-292975919: they look like an e-reader device, they have rounded corners and are smooth - but also like a book, with pages on the right side, and that could evoke an e-reader cover too - and we see the KO, which says it's KOReader - and the left side of the K looks like a bookmark. It expresses quite a bit much more, while still being simple and clean. (from https://github.com/koreader/koreader/issues/3858#issuecomment-381364433)

![3957564](https://user-images.githubusercontent.com/24273478/134053449-50588aa5-2b69-4923-a9bf-8c13e3a3a53f.png)

The other proposals from #2000 and #3858, and the one proposed above, feel just like any other _ordinary icon_, without our current icon expressiveness.

(*: I'm just a bit tired of our pale green color, I prefer it in blue like on the f-droid build , see https://github.com/koreader/android-luajit-launcher/issues/304 :)

**Comment by Frenzie** [comment]
I'm not opposed to a change, but I definitely agree with @poire-z. I think at this point an iterative change (which could be as simple as a mere color change) would at least a priori seem like the best course.

Btw, I hope you guys liked when I drew this one. ;-) 
https://github.com/koreader/koreader/releases/tag/v2020.04

**Comment by offset-torque** [comment]
Yes there is technically no necessity for changing the icon. KOReader would be perfectly usable with a capital K drawn in MS Paint even. But there is a reason we don't all walk around like homeless people despite it is cheaper and easier:
**Appearance is important**

I am not saying my design is perfect but it fits much better in a modern operating system (both desktop and mobile) than the current one which resembles Microsoft Cliparts from the 90s. If you are in the Apple ecosystem you already know how beautiful icons looks like.

**In Linux we have beautiful icons too:**
![kdeicons](https://user-images.githubusercontent.com/84420582/134122439-fd8f3b3d-22cc-463f-9b49-2598fd4c6295.png)

I was always curious about how some open source apps ended up with awful icons. Mystery solved !
Apparently the reason is not **"Well we couldn't find a better alternative"** as I thought. 
Now I see, it is more like **"Nah we are fine with our crudely drawn clipart"**

I would normally close this issue myself. But since I think this is an improvement to the project (which also requires zero effort from anyone), I am leaving this open out of principle. You can close it if you want.

**Comment by solarkite** [comment]
> here is my design if anyone is interested

This is impressive. I enjoy the aesthetic!
