### ISSUE TITLE
Raspberry Pi OS font issue crash

### ISSUE THREAD

**Issue by mvoltz** [koreader/koreader#8236]
The default 32-bit raspberry pi OS does not ship with the Noto Sans fonts, and koreader will not run without them.
To reproduce: 

1. install the default Raspberry Pi OS using rpi-imager (recommended)
2. download the koreader arm hf .deb file
3. sudo dpkg -i <.deb file>
4. run koreader

After installing the fonts manually the issue is resolved, but wanted you to be aware.
p.s. I love koreader!

**Comment by pazos** [comment]
Dependencies are listed in the debian control file. If they are not installed typing `sudo apt -f install` should fix your issue.

Also: GUI tools like Gdebi, ubuntu software etc should be able to read and install deps without problems.

**Comment by Frenzie** [comment]
@pazos is right, I didn't realize you used dpkg (although it should complain about missing dependencies I think)? Since it's 2021 it's easier to use `apt install ./koreader-blabla.deb`.

**Comment by pazos** [comment]
Updated https://github.com/koreader/koreader/wiki/Installation-on-desktop-Linux to use `apt` instead of `dpkg`
