### ISSUE TITLE
Option to download reflowed version as mobi/azw on Android

### ISSUE THREAD

**Issue by deepwilson** [koreader/koreader#8239]
Is there a way we could download the reflowed version from the Android app?

I cannot jailbreak my current Kindle and I would like to convert my pdf to reflowed version and save the reflowed version to mobi/azw etc

Do you'll think it is possible to introduce this feature or does it exists as of now because I couldn't find any option to do so.

Thanks

**Comment by Frenzie** [comment]
No, you'll have to use k2pdfopt separately. The built-in feature is sufficiently performant only because it's on a page by page basis.

**Comment by deepwilson** [comment]
Does koreader use k2pdfopt internally?

**Comment by deepwilson** [comment]
I cannot jailbreak my Kindle since it's the latest version (5.13.6) :(
Any other alternatives for converting heavy math pdfs to mobi?
Tried k2pdfopt but it doesn't render the text properly :(

**Comment by Frenzie** [comment]
> Does koreader use k2pdfopt internally?

For reflow, yes.

I'm not at home in the Kindle ecosystem. You could try loading the PDF in MS Word for example, and subsequently converting that to Mobi in calibre. But I don't know if that'd work out with math formulae.

But I thought Kindles could read PDF out of the box, just badly? Which is where k2pdfopt comes in, so it doesn't have to anything other than turn pages.

**Comment by deepwilson** [comment]
k2pdfopt works with bitmaps during reflow.
As a result the  output quality degrades!
Look like I'm stuck with k2pdfopt.

Another solution is https://www.arxiv-vanity.com/ though not perfect works for most content

**Comment by Frenzie** [comment]
https://www.willus.com/k2pdfopt/help/native.shtml
