### ISSUE TITLE
Crash after press button next page in wikipedia box search

### ISSUE THREAD

**Issue by nikovuksan** [koreader/koreader#8241]
* KOReader version: 2021.09
* Device: Kobo Glo N613

#### Issue
Crash after press button next page in wikipedia box search

#### Steps to reproduce
Being connected to Wifi, I do a Wikipedia search for a word that presents more than one result, the first result is displayed, but when pressing the Next Page (>>) button in the search box Koreader crash .
It also happens to me both if I highlight a word from an epub that I am reading and the dictionary box appears and then I click below on Wikipedia 

##### `crash.log` 
<details>
  <summary>crash.log</summary>

```
dhcpcd[5321]: eth0: executing `/libexec/dhcpcd-run-hooks' BOUND
dhcpcd[5321]: forking to background
dhcpcd[5321]: forked to background, child pid 5346
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in JPEG image
./luajit: frontend/ui/widget/textboxwidget.lua:1091: attempt to index field '_bb' (a nil value)
stack traceback:
	frontend/ui/widget/textboxwidget.lua:1091: in function 'getSize'
	frontend/ui/widget/container/centercontainer.lua:10: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
	frontend/ui/widget/horizontalgroup.lua:49: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:48: in function 'paintTo'
	frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
	frontend/ui/widget/container/centercontainer.lua:24: in function 'paintTo'
	frontend/ui/widget/verticalgroup.lua:52: in function 'paintTo'
	frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
	frontend/ui/widget/container/movablecontainer.lua:144: in function 'paintTo'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1119: in function 'sendEvent'
	frontend/ui/uimanager.lua:227: in function '__default__'
	frontend/ui/uimanager.lua:1580: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1660: in function 'handleInput'
	frontend/ui/uimanager.lua:1707: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00014119
!!!!
Uh oh, something went awry... (Crash n°1: 09/21/21 @ 23:13:11)
Running FW 4.28.18220 on Linux 2.6.35.3-850-gbc67621+ (#619 PREEMPT Thu Dec 22 15:29:00 CST 2016)
Attempting to restart KOReader . . .
!!!!
```
</details>

![IMG_20210922_004354](https://user-images.githubusercontent.com/91172354/134280541-d62ecce6-cef9-4b09-8bed-25b9a8dbf9f3.jpg)

![IMG_20210922_004420](https://user-images.githubusercontent.com/91172354/134280807-6776079a-aa98-4e38-beb8-1e6bfd6748b1.jpg)

**Comment by poire-z** [comment]
Can't reproduce on the emulator or my Kobo :/

(I remember I got these kind of crashes when making the totally unrelated https://github.com/koreader/koreader/pull/8142#issuecomment-907861004 ...)

Also, on the screenshots, the `es > en` button is disabled, which I can reproduce when Wikipedia lookup is invoked from File browser (it is enabled when invoked from Reader).
Tried an old nightly v2020.06, and at the time, this button was working when invoked from File browser.

(Also unrelated, but I'm getting too often some random segfaults on the emulator on my updated Debian 11 :/ that I can't manage to get when re-running with gdb)

**Comment by Frenzie** [comment]
Do you still have a bunch of dependencies around compiled with the old system? Might be worth recompiling them.

**Comment by poire-z** [comment]
(I think I cleaned it all well with:
```
rm -rf base/thirdparty/*/build/*linux* # (keeping just git_checkout)
rm -rf base/build/*
```
and rebuilt everything.)

**Comment by Frenzie** [comment]
Yup, that should do the trick.

**Comment by poire-z** [comment]
> Being connected to Wifi, I do a Wikipedia search for a word that presents more than one result, the first result is displayed, but when pressing the Next Page (>>) button in the search box Koreader crash

@nikovuksan : any specific path taken before this happen ? Do you still get it when just launch koreader > File browser > Wikipedia lookup ? Or do you need some specific previous action to get this crash ?

**Comment by nikovuksan** [comment]
> 
> 
> Can't reproduce on the emulator or my Kobo :/
> 
> (I remember I got these kind of crashes when making the totally unrelated [#8142 (comment)](https://github.com/koreader/koreader/pull/8142#issuecomment-907861004) ...)
> 
> Also, on the screenshots, the `es > en` button is disabled, which I can reproduce when Wikipedia lookup is invoked from File browser (it is enabled when invoked from Reader).
> Tried an old nightly v2020.06, and at the time, this button was working when invoked from File browser.
> 
> (Also unrelated, but I'm getting too often some random segfaults on the emulator on my updated Debian 11 :/ that I can't manage to get when re-running with gdb)

Until version v2020.07 this did not happen to me, it began to happen with version v2020.08 and now also with v2020.09, both updating from Koreader by Wifi to the latest version and installing it directly in the .adds directory in my kobo glo n613. If I copy the version v2020.07 back into .adds, the problem no longer occurs, but I update to version v2020.08 or v2020.09 and it happens again.

**Comment by nikovuksan** [comment]
> 
> 
> > Being connected to Wifi, I do a Wikipedia search for a word that presents more than one result, the first result is displayed, but when pressing the Next Page (>>) button in the search box Koreader crash
> 
> @nikovuksan : any specific path taken before this happen ? Do you still get it when just launch koreader > File browser > Wikipedia lookup ? Or do you need some specific previous action to get this crash ?

It happens to me both if I highlight a word from an epub that I am reading and the dictionary box appears and then I click below on Wikipedia, as if I look for it directly in koreader> File browser> Wikipedia lookup.
This problem happens to me only from v2020.08 and v2020.09, with version v2020.07 and earlier it does not happen to me. And I have reinstalled version v2020.07 and it does not happen.

**Comment by poire-z** [comment]
OK, I managed to reproduce :)
I wondered if it was something with the Spanish UI, then saw the wider spanish "Wikipedia completada", and had to increase my Screen DPI to get it on 2 lines/truncated. Only then, I get a crash. I get the crash too with the English UI and "Wikipedia Full" on 2 lines.
So, possibly related to https://github.com/koreader/koreader/pull/8078 or the stuff around that we did in August, which confirms it did not happen with v2020.07.

Unrelated to the issue itself, but I now can catch the segfault I get after this issue traceback, so might be THE cause for the segfaults I experienced before...
```
./luajit: frontend/ui/widget/textboxwidget.lua:1091: attempt to index field '_bb' (a nil value)
stack traceback:
 frontend/ui/widget/textboxwidget.lua:1091: in function 'getSize'
 frontend/ui/widget/container/centercontainer.lua:10: in function 'paintTo'
 frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
 frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
 frontend/ui/widget/horizontalgroup.lua:49: in function 'paintTo'
 frontend/ui/widget/verticalgroup.lua:48: in function 'paintTo'
 frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
 frontend/ui/widget/container/centercontainer.lua:24: in function 'paintTo'
 frontend/ui/widget/verticalgroup.lua:52: in function 'paintTo'
 frontend/ui/widget/container/framecontainer.lua:96: in function 'paintTo'
 frontend/ui/widget/container/movablecontainer.lua:144: in function 'paintTo'
 frontend/ui/widget/container/widgetcontainer.lua:83: in function 'paintTo'
 frontend/ui/widget/container/inputcontainer.lua:85: in function 'paintTo'
 frontend/ui/uimanager.lua:1433: in function '_repaint'
 frontend/ui/uimanager.lua:1615: in function 'handleInput'
 frontend/ui/uimanager.lua:1707: in function 'run'
 reader.lua:290: in main chunk
 [C]: at 0x55555555d7b1

Thread 1 "luajit" received signal SIGSEGV, Segmentation fault.
0x00007fffdca6fa0f in fz_free (ctx=0x555558174fd0, p=0x5555581ca3e0) at source/fitz/memory.c:204
204   ctx->alloc->free(ctx->alloc->user, p);
A debugging session is active.

 Inferior 1 [process 27267] will be killed.

Quit anyway? (y or n) y
```
@Frenzie @NiLuJe : can you try reproducing it (Large Screen DPI so you get Wikipedia Full on 2 lines, the hit `>>` and get the traceback above - do you get a segfault too ? I want to know if it's just related to my Debian 11, or if it's something more generic (it may be something generic, it's possible I had seen such crashes recently before I updated my debian).
The segfault might not even be a real issue, may be we just can't tear down MuPDF properly when exiting on a traceback...

**Comment by hius07** [comment]
Kindle, the same crash, no segfault.

**Comment by nikovuksan** [comment]
maybe something irrelevant, but in Spanish it should say "Wikipedia completa", not "Wikipedia completada", it sounds bad

**Comment by hius07** [comment]
It crashes on
https://github.com/koreader/koreader/blob/3a01ab78994af9d232b2cd584eec6d5ea8a05b76/frontend/ui/widget/dictquicklookup.lua#L824

**Comment by poire-z** [comment]
Yep. In this DictQuickLookup, @NiLuJe went from re-instantiating everything to re-using what's possible some months ago. So, we're re-using Buttons - which are dumb things with TextWidget, but get a bit more state when using a TextBoxWidget.
TextBoxWidget gets free(self._bb), but the self._bb is used for :getSize() - and it happens to be called during this :update() ...
We could save the _bb.w/h into _bb_width and _bb_height so they are available after the _bb is freed, and use them in :getSize() - but I'm not sure it's the right thing to do (using past dimensions to size something that will later be renderer and may have some new dimensions).
May be TextBoxWidget:getSize() should render the textbox text&images as it's done in :init() - that's what TextWidget:getSize() does, having nearly every method call TextWidget:updateSize() which is the thing that does the measurements/rendering.
(Just realizing that there is not TextWidget:init() :) it's this :updateSize() that must do all the work that we usually do in :init() in most other widgets...)

(A bit too busy with other things these days to give more thoughts about it.)

**Comment by Frenzie** [comment]
> @Frenzie @NiLuJe : can you try reproducing it (Large Screen DPI so you get Wikipedia Full on 2 lines, the hit >> and get the traceback above - do you get a segfault too ?

Yes, that's dependable.

**Comment by NiLuJe** [comment]
@poire-z: That doesn't sound too bad, yeah.

Something like

```diff
diff --git a/frontend/ui/widget/textboxwidget.lua b/frontend/ui/widget/textboxwidget.lua
index 262d213a0..2b6e72742 100644
--- a/frontend/ui/widget/textboxwidget.lua
+++ b/frontend/ui/widget/textboxwidget.lua
@@ -1088,7 +1088,12 @@ function TextBoxWidget:getCharPos()
 end
 
 function TextBoxWidget:getSize()
-    return Geom:new{ w = self.width, h = self._bb:getHeight()}
+    -- Make sure we actually have a BB, in case we're recycling an instance... (c.f., #8241)
+    if not self._bb then
+        self:_renderText(self.virtual_line_num, self.virtual_line_num + self.lines_per_page - 1)
+    end
+
+    return Geom:new{w = self.width, h = self._bb:getHeight()}
 end
 
 function TextBoxWidget:paintTo(bb, x, y)
```

**Comment by poire-z** [comment]
Well, I guess if we haven't seen it crashed until this issue, it's that :getSize() is never called before a self._bb has been created, so this might be an edge case limited for now to multi-lines Buttons, so I guess such a quick hack might be ok.

You might want to re-use the existing `TextBoxWidget:update(scheduled_update)` (which does just that + a few no-ops) to make it look smoother, like if it was a case we thought about :) (and may be it's just that? :)
```lua
if not self._bb then
    self:update()
end
```

**Comment by NiLuJe** [comment]
Yeah, I was going to do that, and then I saw that a lot of other things was just doing the `_renderText` directly, and the rets of :update is indeed a noop in this instance ;).

**Comment by poire-z** [comment]
Following the discussion here, about #8250 : 

> Yeah, I was going to do that, and then I saw that a lot of other things was just doing the _renderText directly, and the rest of :update is indeed a noop in this instance ;).

Most of the lot of other things do that `self:_renderText(self.virtual_line_num, self.virtual_line_num + self.lines_per_page - 1)` after playing with/updating `self.virtual_line_num`, so it's then quite readable in their context.
For your case, we don't play with `self.virtual_line_num`, so it feels a bit out of context.
I'd prefer a simpler `self:update()`, to have it look less scary :)

**Comment by poire-z** [comment]
@NiLuJe : no thought about the bottom of https://github.com/koreader/koreader/issues/8241#issuecomment-924987828 ?
```
Thread 1 "luajit" received signal SIGSEGV, Segmentation fault.
0x00007fffdca6fa0f in fz_free (ctx=0x555558174fd0, p=0x5555581ca3e0) at source/fitz/memory.c:204
204   ctx->alloc->free(ctx->alloc->user, p);
```

**Comment by NiLuJe** [comment]
> @NiLuJe : no thought about the bottom of [#8241 (comment)](https://github.com/koreader/koreader/issues/8241#issuecomment-924987828) ?
> 
> ```
> Thread 1 "luajit" received signal SIGSEGV, Segmentation fault.
> 0x00007fffdca6fa0f in fz_free (ctx=0x555558174fd0, p=0x5555581ca3e0) at source/fitz/memory.c:204
> 204   ctx->alloc->free(ctx->alloc->user, p);
> ```

That's what lead me to the `line_num_to_image` thingy, because it's possibly pinning stale MµPDF contexts around, and a crash might force a Lua state teardown with stale pointers or something :?.
