### ISSUE TITLE
reMarkable : Middle button launch 

### ISSUE THREAD

**Issue by zelomel** [koreader/koreader#8242]
Hi,

I try to set Koreader after an update of my reMarkable tablet.
I did'nt reinstall completly koreader, because it still in ~/koreader and just reconfig the Middle button launch with : 

`cp -v koreader/button-listen.service /etc/systemd/system/`
`systemctl enable --now button-listen`
`reboot`

and it did'nt work.

I can launch koreader with `systemctl start koreader` but when in xochitl it seems to not react to middle button.

xochitl : version 2.9.236 with ddvk patch
koreader : version 2021.08-82

**Comment by snahvalo** [comment]
Same here. I upgraded the reMarkable (rM1) to 2.9.236, then installed koreader 2021.09. The buttons work fine in xochitl (e.g. short press middle button to exit document), so I believe this is a software problem.

When I check the button-listen.service it is listed as loaded, active and running, so this may have something to do with the button-listen binary executable in the koreader directory. 

root@reMarkable:~# systemctl | grep button
  button-listen.service                                                                                            loaded active running   KOReader Button Listener

rM1
xochitl : version 2.9.236
koreader: version 2021.09

**Comment by zelomel** [comment]
it seems it's ddvk patch's bug: https://github.com/ddvk/remarkable-hacks/issues/353

**Comment by snahvalo** [comment]
I am not so sure: I have just updated my rM1 to version 2.10.0.324, and copied the koreader .service files over and enabled button-listen. Np ddvk hacks installed: middle button launch does not work. Something may have changed in the firmware that caused a problem both for ddvk and koreader.

**Comment by zelomel** [comment]
How rM2 users launch koreader ?

**Comment by snahvalo** [comment]
OK, just to rule out interaction effects with ddvk, I reflushed my reMarkable, let it update to a virgin installation of 2.10.0.324, and then installed koreader according to the instructions on the wiki., including activating the button-listen service. Result: long press on the middle button does not launch koreader.

**Comment by zelomel** [comment]
I tried today to update to 2.10.0.324 patched with ddvk. The new patch has a toggle for long home press, but on or off it does not launch koreader. So with or without ddvk you can not launch koreader with middle button.

**Comment by StreetGuru** [comment]
Same issue here. I've Just installed the latest koreader (v. 2021.11) after a factory reset on my remarkable 1 and now there is no way to launch koreader. This obviously makes it unusable. Is this being looked at? Has anyone found a solution? The fact that the latest comment on this thread is from over 2 months ago is disheartening.

**Comment by klapaukh** [comment]
The PR linked in the related issue does actually fix it [for me at least] (it's an upstream bug).

**Comment by StreetGuru** [comment]
Hi @klapaukh, thanks for the prompt reply, and for your work looking into it and submitting a PR.
Is there any way to apply the PR without manually editing the code?
Not surprised at all that this is a bug from remarkable!

**Comment by klapaukh** [comment]
If you can build remarkable binaries - then yes. If you can't then... I have a version of it that I can send you / stick somewhere. And you just replace button-listen in the koreader folder with the one I made and start / stop the listen service and it'll work (and be a good test). Also if you test it and it works, it would be great if you could comment on either the PR or bug thread I linked that it worked, to encourage them to review it, so it can be merged.

**Comment by poire-z** [comment]
Just zip it and drag/drop it here here.
None of us has a remarkable to test - and only @NiLuJe could review your low level C PR #1428 .
So, a bunch of "it works!" might be just enough for it to be merged :)

**Comment by klapaukh** [comment]
[button-listen.zip](https://github.com/koreader/koreader/files/7584795/button-listen.zip)

Instructions for use (assuming you've already set up koreader):
 - Ssh into your remarkable
 - stop / disable the button-listen service (you will get a permission error and it will fail if you do the next steps while it is running)
 - Replace `button-listen` inside the `koreader` folder with the one in the zip provided
 - Enable the button-listen service
 - It should now work. If it doesn't let me know 😁 

That's cool, I didn't realise I could upload things here. Hopefully this is the right thing 😅 

@poire-z  Ah, that makes sense. Supporting both pre/post firmware update remarkables makes the PR much more complex, sorry (you only need a 1 character change to make it only work post update).

**Comment by snahvalo** [comment]
My rM1 is now at 2.10.3.379; will this precompiled butto-listen work with that?

**Comment by StreetGuru** [comment]
Thanks @klapaukh! It works well for me too (same version of xochit and koreader as @snahvalo)

Just a note: because the info on enabling the button-listen service is missing from the install page, for anyone fresh installing KOreader do not forget to copy the button-listen service file to the system directory before enabling it:

`cp /home/root/koreader/button-listen.service /etc/systemd/system/`

Many thanks for your work and prompt help!
