### ISSUE TITLE
Syncing reading status and library with Calibre-web

### ISSUE THREAD

**Issue by rcampusa** [koreader/koreader#8243]
**Is your feature request related to a problem? Please describe.**
I just got a Boox Nova Reader and using the KOReader (or any other android reader for that matter). I wonder if there is a way to sync reading status and library with a calibre-web instance. Highlights/notes would be amazing but I already use joplin for that. 

**Describe the solution you'd like**
Improve connection between calibre-web and koreader. 

**Describe alternatives you've considered**
Manual syncing. But is just too much work :(.

**Comment by Zeyadas** [comment]
I think it's similar to my feature request #8160

**Comment by Frenzie** [comment]
Yes, I'll close it in favor of that one.

**Comment by Zeyadas** [comment]
I was thinking about syncing,
When I bought my new android tablet I simply copied the settings.reader.lua to the new device so I didn't have to re-set the settings manually again. It worked perfectly.
So I was thinking about a full syncing plug in that you can choose what to sync for example syncing taps and gestures or/and status bar settings.

**Comment by rcampusa** [comment]
I'm sorry but I dont understand how its similar to your request @Zeyadas. How do you set up this with calibre-web? Maybe there is a way to make the calibre-web instance to look like as a koreader client for the progress sync plugin to work? THanks for your reply!
