### ISSUE TITLE
[FR] Koreader reading statistics sync.

### ISSUE THREAD

**Issue by Zeyadas** [koreader/koreader#8245]
I'm sorry but I didn't know where to suggest this.
I was wondering if you can make a plugin to sync the reading statistics on two or more devices, something like the progress sync in koreader.
Thank you.

**Comment by Zeyadas** [comment]
Thanks.

**Comment by poire-z** [comment]
Duplicate of #7058

**Comment by myrxhw** [comment]
+1

**Comment by poire-z** [comment]
As it is said in the duplicated issue, this has been implemented by #9709 (via some cloud storage, not directly), and is available since v2022.11.
