### ISSUE TITLE
With boox nova air rotation 180 degrees does not work 

### ISSUE THREAD

**Issue by arooni** [koreader/koreader#8246]
Repro steps 
2021.09 releAse (android)

Open an epub
Ask to rotate 180 degrees so page turning buttons are on the right hand side.  

Koreader appears to refresh and then no rotate happens. 

Both rotations to landscape work fine.  

Would love my page turn buttons to be on the right hand side with the help of rotation

**Comment by pazos** [comment]
we can't fix firmware :p
