### ISSUE TITLE
Download many files at once via Cloud Storage (Dropbox/FTP)

### ISSUE THREAD

**Issue by yukari186** [koreader/koreader#8256]
Is there any way to download many files at once via Cloud Storage (Dropbox/FTP)? Thank you so much.

**Comment by Frenzie** [comment]
Short answer no, long answer there's a WIP over in https://github.com/koreader/koreader/pull/7474 if someone wants to take over.

**Comment by yukari186** [comment]
> Short answer no, long answer there's a WIP over in #7474 if someone wants to take over.

I have done it. Thank you for your reply. Best wishes 💖
