### ISSUE TITLE
"Äéß" key greying

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8260]
* KOReader version: 2021.09

#### Issue
The "Äéß" key on the Greek keyboard does not turn grey when selected.
Could this be fixed, please?

**Comment by poire-z** [comment]
It will probably not be fixed.
The keyboard has been updated recently: #8089 . Fixes and changes will mostly happen on keyboard based on the new stuff.
(Unless we broke `Äéß` just because we thought we didn't need it, @mergen3107 ? and it could easily be resurrected ?)

Anyway, if you have some time and courage, you could try to update your greek keyboard to match the new one, details in #8089.

**Comment by ichnilatis-gr** [comment]
I understand.

> Anyway, if you have some time and courage, you could try to update your greek keyboard to match the new one, details in #8089.

It does take courage and a LOT of time... :-)

Thanks!

**Comment by mergen3107** [comment]
I didn’t do anything specific to that key :)
The thing is that any modifier key is not greying out anyway. The only distinction that could be made is to have different labels like `1/2` and `2/2` for two symbol layers, for example

**Comment by poire-z** [comment]
OK :)
But the modifier keys do grey out, at least Shift and Symbol, on all keyboard, even on the greek one. But the Äéß key doesn't:
![image](https://user-images.githubusercontent.com/24273478/134781629-cb854dec-9a1c-4f94-b616-e6304c876ef4.png)

**Comment by hius07** [comment]
Has it ever been greyed?
https://github.com/koreader/koreader/blob/9ed22df03f642322c48dba0e395187a79e38efb9/frontend/ui/widget/virtualkeyboard.lua#L272-L275

**Comment by poire-z** [comment]
It's possible it was:
https://github.com/koreader/koreader/pull/8089/files#diff-826a4b35ba34af0480d5ecf9eeb08a93336b945ebb856600f39886c7e5f6ab20R270-R271

**Comment by hius07** [comment]
> I didn’t do anything specific to that key :)

Guilty!

**Comment by mergen3107** [comment]
> But the modifier keys do grey out, at least Shift and Symbol

Ah, my bad. 



> Guilty!

The change you guys found was not made by me, I just continued PR in #7972

**Comment by ichnilatis-gr** [comment]
I am touched by your willingness.
Thank you!
