### ISSUE TITLE
Opening book or returning to file browser turns off night mode and warmth

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#8293]
* KOReader version: 2021.09-25
* Device: various (Android, Kobo Forma, Kobo Clara)

#### Issue

Opening a book or returning to file browser turns off night mode and (if applicable) backlight warmth.

#### Steps to reproduce

While in a book, toggle night mode and (if available) turn on backlight warmth
Return to the file browser

OR

While in the file browser, toggle night mode and (if available) turn on backlight warmth
Open a book

Warmth turns off and night mode toggles off. I would expect those settings to be kept.

##### `crash.log` (if applicable)
N/A - no crash

**Comment by NiLuJe** [comment]
Is the new Warmth plugin enabled? (if so, ping @zwim).

**Comment by JasonInOttawa** [comment]
The plugin is turned off on the Clara and I see the same behaviour there. Also on Android (night mode turns off, warmth setting not applicable), where the plugin isn't available

**Comment by NiLuJe** [comment]
As far as night mode is concerned, does it actually toggle off in the menu?

Do you happen to have a gesture set for this or some of the related settings? (And are you actually *using* a gesture to go back to the FM?).

**Comment by JasonInOttawa** [comment]
The toggle item in the menu turns off too, and looking at Settings>>Front Light shows warmth setting itself (from e.g. 100) to 0.

I'm opening a book by tapping on in the file browser, or returning to the file menu by bringing up the top menu and tapping on the icon.

**Comment by NiLuJe** [comment]
I'm assuming it worked in 2021.09-6 and broke in ~19 or ~22?

**Comment by JasonInOttawa** [comment]
I've tried it on 2021.08-80 and things look all right there (at least as far as night mode goes). It doesn't work on 2021.09-19.

Is there someplace I can download old nightly builds for the kobo? Thanks!

**Comment by NiLuJe** [comment]
Old nightlies: http://build.koreader.rocks/download/nightly/

Ping @zwim, as it appears to be related to the warmth changes ;) (I'll try to repro tomorrow).

**Comment by JasonInOttawa** [comment]
Thank you.

Things seem to work fine in 2021.09-6 (night mode sticks in Android on that build).

@zwim, please let me know if you'd like me to do anything

**Comment by zwim** [comment]
@JasonInOttawa I can reproduce the bug on my Tolino. I will fix it tonight or at latest tomorrow evening
