### ISSUE TITLE
FR: [Split screen]

### ISSUE THREAD

**Issue by islam2hamy** [koreader/koreader#8297]
Can you please support Split screen ?
So i can read , and open another app with the book

Thank you

**Comment by Zeyadas** [comment]
I'm not a developer here, just a user (an Arabic one if it makes any difference). 

I'm wondering what device you are using? I thought that the split screen is for big screens (I use two android tablets for reading, Samsung T-285 & T-295), after some search I was wrong, also the smaller screen phones can split the screen.

**Comment by pazos** [comment]
Requires support on the android backend. See https://github.com/koreader/android-luajit-launcher/issues/238

I'm going to label it as won't fix but patches are very welcome :)

**Comment by pazos** [comment]
Also a duplicate of https://github.com/koreader/koreader/issues/7422

:p

**Comment by islam2hamy** [comment]
> I'm not a developer here, just a user (an Arabic one if it makes any difference).
> 
> I'm wondering what device you are using? I thought that the split screen is for big screens (I use two android tablets for reading, Samsung T-285 & T-295), after some search I was wrong, also the smaller screen phones can split the screen.

Hi @Zeyadas 
Yes , smaller screen phones can split the screen.
