### ISSUE TITLE
Unicode quotation marks destroys output

### ISSUE THREAD

**Issue by MasseR** [koreader/koreader#8306]
* KOReader version: 2021.05, 2021.03
* Device: Android, Laptop

#### Issue

Part of the text is "eaten up" by the left and right quotation marks (unicode 8216, 8217). See the attached screenshots from koreader and Calibre respectively.

![image](https://user-images.githubusercontent.com/41126/136153576-3cf52b3f-ab09-4514-8dd3-d66a308fffdf.png)

![image](https://user-images.githubusercontent.com/41126/136153680-dceccb37-c669-498f-bf8f-134b65187199.png)

``` xml
<div class="tx"><span xmlns="http://www.w3.org/1999/xhtml" class="koboSpan" id="kobo.4.1">‘We’re okay?’ </span><span xmlns="http://www.w3.org/1999/xhtml" class="koboSpan" id="kobo.4.2">Bella asked.</span></div>
```

#### Steps to reproduce

Not sure how to reproduce aside from opening this specific book. I tried creating a minimal example with `pandoc` but it rendered the text just fine.

**Comment by Frenzie** [comment]
You can scramble the document using the ScrambleEbook plugin for calibre: https://www.mobileread.com/forums/showthread.php?t=267998

(Minimal examples are almost always preferable, however, so very much thanks for trying regardless! ;-) )

**Comment by MasseR** [comment]
Ok, after a lot of trial and error, I've pinpointed it into a single wrong line in the html. The xml declaration declares the file to be UTF-8, but then there's a separate `<meta` line setting the content to be iso-8859-1. But this probably isn't the entire story, as just changing this value in the pandoc-generated doesn't break the rendering.

**Comment by Frenzie** [comment]
Afaik that should not be parsed for an XHTML document, only when the document is parsed as HTML5. Which is to say, it should be double checked but I suspect we're correct and they're wrong.

**Comment by MasseR** [comment]
Yeah, I think a limited amount of leniency on the parser is good too. However, I can't make such decisions for koreader, so I'll just leave instructions on how I fixed the specific ebook for posteritys sake.

``` console
$ mkdir temp/book
$ cd temp/book
$ unzip ~/originalbook.epub
$ find . -iname '*.html' -exec sed 's/charset=iso-8859-1/charset=utf-8' -i {} \;
$ zip -Xr ~/modifiedbook.epub *
```

**Comment by Frenzie** [comment]
Hold on, if that's the fix then it's the reverse of what I said. We're incorrectly applying the meta charset stuff and they're not.

**Comment by poire-z** [comment]
So, that's 3 different users with I guess 3 different books/sources recently that got this issue.
I can have our HTMLParser trust the encoding , if it is present, from
`<?xml version="1.0" encoding="utf-8"?>`
before trusting:
`<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/`>

Do you think it's really the right thing to do ?
If yes, should this be EPUB only or also with standalone xhtml or if found in CHM?

No idea if the current behaviour has been doing the right thing for ages on books that would have both these tags :)

**Comment by Frenzie** [comment]
The XML declaration takes preference per spec in XHTML: https://www.w3.org/TR/xhtml1/#C_9

**Comment by poire-z** [comment]
Btw, does Wallabag generates EPUBs from web pages ? And if doing so, how does it do with a latin1 page ? Does it convert it to utf8? Does it add the `<?xml>` header with the fixed utf8 encoding?

**Comment by Frenzie** [comment]
I don't know, do you have any links with "normal" encodings to test? :-) All I have in my bookmarks as a text editor stress test is http://computermuseum.informatik.uni-stuttgart.de/pcdisk/h/ASCII/3968.TXT

E.g., Kate passes:
![image](https://user-images.githubusercontent.com/202757/179390193-8af86cf1-7e5c-4cc4-b4ad-25b52eb1381c.png)

As does CudaText:
![image](https://user-images.githubusercontent.com/202757/179390211-941f5334-d98a-4004-b8c9-c99a363753ab.png)

**Comment by Frenzie** [comment]
Notably, VS Code can't even open the file at all.

**Comment by poire-z** [comment]
I mean that if I get what Wallabag does, if you tell it you want to save/get this page:
https://bibliotheque-russe-et-slave.com/Livres/Suares_-_Dostoievski.htm
which has
`<meta http-equiv=Content-Type content="text/html; charset=windows-1252">`
and if you can get iit on your device as an EPUB, what ends up in the EPUB xhtml?

**Comment by Frenzie** [comment]
Here's the EPUB Wallabag creates:
[Suares - Dostoievski.epub.zip](https://github.com/koreader/koreader/files/9127267/Suares.-.Dostoievski.epub.zip)

**Comment by Frenzie** [comment]
So it looks like it's converted it successfully. The guillemets work.
```xml
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
  <head>
    <meta http-equiv="Default-Style" content="text/html; charset=utf-8"/>
    <title>wallabag articles book</title>
  </head>
  <body>
```

**Comment by poire-z** [comment]
OK, so we won't break wallabag. Thanks.
