### ISSUE TITLE
File operations successful infomessages

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8307]
I am a heavy user of the file browser and feel annoyed with the infomessages after successful file operations (delete, rename etc). The results are well observable in the list of files/folders, no need for the messages.
Does anybody like or need them? Can they be removed?

**Comment by hius07** [comment]
Repeating https://github.com/koreader/koreader/pull/8330#issuecomment-944339877 for wider discussion.

After successful copying/deleting/renaming a file we can get
(1) no message at all (like in desktop file managers)
(2) notification (without details, proposed in https://github.com/koreader/koreader/pull/8330)
(3) detailed infomessage with 2 sec timeout (current behaviour)
(4) detailed infomessage without timeout waiting for a tap

**(2)** gives a good balance of informativeness and productivity of the file browser.

Failed operations must show **(4)**.

**Comment by Frenzie** [comment]
There's a difference in kind between messages like ("Cut/Copied to clipboard") and messages that provide verification ("Moved x to y"). I think the desire to make them all either 1 or 3 (cf. #7582) may have caused this issue in the first place.

So I would say: all of the above.

1 or 2. Stuff like "copied to clipboard"
3. Moved x to y, deleted x, etc. (possibly reverted to how it used to be for brevity; the from matters a lot less than the to)
4. Something failed.

**Comment by hius07** [comment]
> > Nobody likes 4. Everything other than 3
> 
> I prefer 4 to 3 :)

Maybe (2)?
When deleting, we check the filename three times: in the list when putting a finger for long-pressing, then in the popup button dialog, then in the confirm box. No need to see it once more in the infomessage.

**Comment by hius07** [comment]
Agree for (1), no news is good news.

**Comment by Frenzie** [comment]
> our InfoMessage is in the middle of screen: it prevents us from continuing working or reading: they are obtrusive

But that *is* an irrelevant technical detail. Make it not do that then! ;-) Heck, get rid of the freaking notification, just make it use InfoMessage so it does multiline when necessary.
