### ISSUE TITLE
Plugin text sizes are too big

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8314]
I am using two plugins most frequently (Reading and Battery Statistics) and their text size is really big, I guess it is around 44 pt. As you can see in the photo, only 10 lines fit in a page and horizontally it is worse like **"Estimated remaining ho"**

I don't know if this is the intended result or a scaling problem but this is unnecessarily big. All plugin information can fit on one page easily. My screen DPI is 240. At this size my menu items are approximately 20-22 pt. I think plugins should follow the rest of GUI regarding text size, if that is possible.

![plugin big letters](https://user-images.githubusercontent.com/84420582/136402716-39445fd9-0b71-4979-9abc-dfffc9c48cf7.jpg)

**Comment by offset-torque** [comment]
> Could you provide more info that's requested in the bug report so we don't have to ask?

I didn't open this as a bug report, just FR because I thought this is the intended behavior, just needs tweaking (I was kinda correct it seems).

NiLuJe is right. Apparently this is related to **"Info lists items per page"** setting in the FM menu. It is unfortunate because when I set that value high enough to make plugin text a reasonable size, my cover images gets unusably tiny.

I guess this is ancient code and big letters are not a big problem for me. 
But maybe plugin system needs its separate font size variable or it may just use the menu font size ?

**Comment by NiLuJe** [comment]
Its tied to the widget being used, whether it's a plugin or not is irrelevant, so, as far as I can tellk, it's doing exactly what it was designed to ;).
