### ISSUE TITLE
Wallabag plugin could not download articles

### ISSUE THREAD

**Issue by Ronnoc** [koreader/koreader#8315]
version 2109
device:kindle
How to debug it?
I configured wallabag on my own server.
My ios application can successfully log in, add articles.
But after my kindle is configured, when I click Sync, there will be a Message ("Connecting...") and the message will end immediately, but no files have been downloaded

**Comment by Frenzie** [comment]
Apologies, I see I lost track of this last year.

The crash.log file that the bug template asks for writes generic logs, somewhat despite the name.

Verbose debug logging can be enabled via the file browser → tools → developer options.

But chances are also that you'll have to add the logging yourself.

Closing as it's probably rather too late to reply, but adding this mainly in case someone lands here while searching.
