### ISSUE TITLE
Joplin/Export highlights crashes on Android

### ISSUE THREAD

**Issue by szebrowski** [koreader/koreader#8321]
* KOReader version: 2021.09
* Device: Android 10

#### Issue
Export highlights crashesh when I'm using it with Joplin.

#### Steps to reproduce
1. Setup Joplin auth token and ip address
2. Checked "Export to Joplin"
3. Click "Export all notes in this book"

##### `crash.log` (if applicable)
[---------.txt](https://github.com/koreader/koreader/files/7317844/---------.txt)

**Comment by Frenzie** [comment]
```

10-10 18:48:20.058 E/NativeThread(31434): Failed to run script: plugins/exporter.koplugin/JoplinClient.lua:37: No response from Joplin Server
```

Apparently these errors aren't used in combination with pcall? That's definitely not nice behavior.

https://github.com/koreader/koreader/blob/903646debef339cea68a23fd91fab9184eb1ac28/plugins/exporter.koplugin/JoplinClient.lua#L36-L44

**Comment by arooni** [comment]
I was trying to set this up today from following along [on mobileread](https://www.mobileread.com/forums/showthread.php?p=4171842#post4171842)

But while I didn't see a hard crash like the above user on my Samsung S21 Ultra (android 11) I did see 

"Multiple errors occurred while trying to export notes from the book, booktitle, and 0 others"

and crash.log doesn't seem to make any mention of this

**Comment by Anderbone** [comment]
Similar issue on kobo sage. Got a "No response from Joplin Server" error.

crash.log:
--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 3.051/3.051/3.051 ms
11/20/21-21:09:03 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
11/20/21-21:09:03 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
11/20/21-21:09:09 INFO  opening file /mnt/onboard/book/Hui Yin Pian  - Bai La Tu.kepub.epub
./luajit: plugins/exporter.koplugin/JoplinClient.lua:37: No response from Joplin Server
stack traceback:
	[C]: in function 'error'
	plugins/exporter.koplugin/JoplinClient.lua:37: in function '_makeRequest'
	plugins/exporter.koplugin/JoplinClient.lua:121: in function 'createNotebook'
	plugins/exporter.koplugin/main.lua:433: in function 'exportClippings'
	plugins/exporter.koplugin/main.lua:340: in function 'exportCurrentNotes'
	plugins/exporter.koplugin/main.lua:238: in function 'action'
	frontend/ui/uimanager.lua:1201: in function '_checkTasks'
	frontend/ui/uimanager.lua:1622: in function 'handleInput'
	frontend/ui/uimanager.lua:1730: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00014119

**Comment by Explorare** [comment]
Same issue confirmed on KOReader v2021.11 runs on Kindle PW3 and Android device

Joplin server runs on a Windows 10 21H1 laptop using wireless network.
I've test Joplin server on localhost and it works.
I've set up the port proxy following the guide and it should work, maybe.
```
netsh interface portproxy>show v4tov4

Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
0.0.0.0         41185       localhost       41184
```
I've checked the local ip address and port and token twice.

Error log
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 11/30/21-12:57:02
 [*] Version: v2021.11

ffi.load: blitbuffer
11/30/21-12:57:02 INFO  initializing for device KindlePaperWhite3
11/30/21-12:57:02 INFO  framebuffer resolution: {
    ["w"] = 1072,
    ["h"] = 1448,
}
[ko-input] Forked off fake event generator (pid: 24900)
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
PING 192.168.0.1 (192.168.0.1): 56 data bytes
64 bytes from 192.168.0.1: seq=0 ttl=64 time=96.734 ms

--- 192.168.0.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 96.734/96.734/96.734 ms
11/30/21-12:57:04 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
11/30/21-12:57:06 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
11/30/21-12:57:06 INFO  opening file /mnt/us/epub/Mixing Engineer's Handbook, 3rd ed., The - Owsinski (497).epub
./luajit: plugins/exporter.koplugin/JoplinClient.lua:37: No response from Joplin Server
stack traceback:
	[C]: in function 'error'
	plugins/exporter.koplugin/JoplinClient.lua:37: in function '_makeRequest'
	plugins/exporter.koplugin/JoplinClient.lua:121: in function 'createNotebook'
	plugins/exporter.koplugin/main.lua:433: in function 'exportClippings'
	plugins/exporter.koplugin/main.lua:340: in function 'exportCurrentNotes'
	plugins/exporter.koplugin/main.lua:238: in function 'action'
	frontend/ui/uimanager.lua:1201: in function '_checkTasks'
	frontend/ui/uimanager.lua:1622: in function 'handleInput'
	frontend/ui/uimanager.lua:1730: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00013ef9
lipc-wait-event exited normally with status: 0
---------------------------------------------
```
Maybe there are some changes made on Joplin side?

**Comment by Explorare** [comment]
Tested on a clean installed Windows 10 device with the same version above, it works as intended. It seems that I messed up my local proxy or firewall settings. The program works just fine.

**Comment by Explorare** [comment]
Append more information:
It seems that the exporter plugin couldn't handle the "no response from server" error, it just crash.
And here is what I did to make it work.

1. Check server's firewall settings. I'm using Windows 10, so I add TCP allow rules for port 41184 and 41185. You can turn off firewall by execute `netsh advfirewall set allprofiles state off` to do a quick test. Do remember to  turn it on again.
2. Make sure there is a correct `joplin_notebook_guid` in `settings.reader.lua`. The exporter plugin wil check if the Joplin server have a notebook named "KOReader Notes", if not, it will create a new one, and save the `joplin_notebook_guid` in `settings.reader.lua`. The issue is the plugin didn't always succeed to find the right id if you try to connect to another Joplin server with different notebook_guid. In this case, you need to add the guid manually using external text editor. You can get this id by copy the external link from Joplin, and add it to `settings.reader.lua`. Here is what it should look like.
```
    ["exporter"] = {
        ["html_export"] = false,
        ["joplin_IP"] = "192.168.0.6",
        ["joplin_export"] = true,
        ["joplin_notebook_guid"] = "8e83b09a134f46d6afbb0847e745d581",
        ["joplin_port"] = 41185,
        ["joplin_token"] = "0349774139066f87b9cada583b68c5afff9efcd67c80772519891f37bae44579a5ba59f4e356c432a5891b03fa2af26046752a4a20d61d2455fe406bf5ddb8f6",
        ["json_export"] = false,
        ["txt_export"] = false,
    },
```
Hope this could help you to fix the issue.

**Comment by Frenzie** [comment]
Pinging @mustafa-001

**Comment by Explorare** [comment]
Some thoughts on the notebook_guid issue:
We could add a new optional field `joplin_notebook_guid` in settings along with `joplin_token`, if it was left empty, the plugin will create a new folder and save its GUID in `settings.reader.lua` as before. And user could also decide which notebook they would like to export to by inputting a existing GUID. In this way the plugin don't need to maintain a list of Joplin server GUID and notebook GUID and works the same as before. When the plugin couldn't find or access the notebook, just throw out a error asking user to fill in the right `joplin_notebook_guid`.

**Comment by Anderbone** [comment]
Thank you @Explorare , there's indeed no guid in `settings.reader.lua`. I added guid manually by copying an external link from a joplin notebook, also turned off all firewall, I also have ran this on win11:
`netsh interface portproxy add v4tov4 listeningaddress:192.168.109.1 listeningport:41185 connectaddress:localhost connectport:41184`

```    ["duration_format"] = "classic",
    ["exporter"] = {
        ["html_export"] = false,
        ["joplin_IP"] = "192.168.109.1",
        ["joplin_export"] = true,
        ["joplin_notebook_guid"] = "147a132aff324ba2952fd51ca0805077",
        ["joplin_port"] = 41185,
        ["joplin_token"] = "f87d30f11e2b1aa4055c2416173fa15abdb5d1e0b7d168a55486f52bb815b3019d067648bebeccaed44d5ca81075e39c8c32c3f907c0b22ab8e9193146cf3cbe",
        ["json_export"] = false,
        ["txt_export"] = false,
    },
```
When I click joplin export highlight in this book, it's not crashing anymore, but saying "multiple errors occurred while trying to export notes from the book:....", and there's no crash log..

**Comment by Explorare** [comment]
@Anderbone Here are two methods may help with the diagnosis:
1. Install Wireshark in your computer and monitor the TCP traffic of port 41184 & 41185 on network interface responds to 192.168.109.1 using filter `tcp.port == 41185 || tcp.port == 41184` . Make sure you've chosen the right interface in case there are multiple network interfaces in your system. BTW, is 192.168.109.1 the gateway of your network or are you connecting to your laptop's hotspot? 
2. There is a verbose debug logging mode hidden in the menu. You can only find it in File Manager page, open the third top menu, second page, More tools, Developer options, Enable debug logging, enable verbose debug logging.

**Comment by 1Eg0d** [comment]
> 

I've met the same thing you described, finally I solved it.  
Here are my exp:  
1. ps `netsh interface portproxy add v4tov4 listeningaddress:0.0.0.0 listeningport:41185 connectaddress:localhost connectport:41184`  
2. make sure the attribute `["joplin_IP"]` of the entry `["exporter"]` is the ip of ur pc,  the attribute  ["joplin_notebook_guid"] is the external link of the notebook named _KOReader Notes_ but a link of a _note_(you can simply new it, and copy the link), and the token is right
3. ebook and ur pc in the same local network  
4. tap the export highlights and u will find them on joplin

That's all. Hope that do something 4 u :P

**Comment by Anderbone** [comment]
@1Eg0d  @Explorare 
Thank you guys so much, and I indeed wrote the wrong IP. But after fixing to the right IP, the issue remains: `multiple errors occurred while trying to export notes from the book: xxx.`
1. I added exception for both 41184 and 41185 in 'Inbound rules' and 'Outbound rules', 
![image](https://user-images.githubusercontent.com/10970596/147419655-f8819b64-2961-43bc-adf2-1054ed9da70a.png)
2. I ran the `netsh interface portproxy add v4tov4 listeningaddress:0.0.0.0 listeningport:41185 connectaddress:localhost connectport:41184` as admin.

The  ["joplin_notebook_guid"] is the external link of a notebook or a note? I tried both but had no luck. I created a notebook named 'KOReader Notes' and created a note 'test' in it, I tried the external link of the notebook and the 'test' note but none of them works.

```json
    ["exporter"] = {
        ["html_export"] = false,
        ["joplin_IP"] = "192.168.0.10",
        ["joplin_export"] = true,
        ["joplin_notebook_guid"] = "961adbc9a16e4a239437538c6f882835",
        ["joplin_port"] = 41185,
        ["joplin_token"] = "f87d30f11e2b1aa4055c2416173fa15abdb5d1e0b7d168a55486f52bb815b3019d067648bebeccaed44d5ca81075e39c8c32c3f907c0b22ab8e9193146cf3cbe",
        ["json_export"] = false,
        ["txt_export"] = false,
    },

This is the wireshark logs, the source 192.168.0.80 is kobo(koread), 192.168.0.10 is my pc.
[wireShark_joplin.txt](https://github.com/koreader/koreader/files/7777581/wireShark_joplin.txt)

**Comment by Explorare** [comment]
According to your wireshark log, there was no response from Joplin server and the TLS handshake didn't happen. Could you please provide the log of Joplin?

>There is also a debug mode for Joplin that can be activated by creating a file named `flags.txt` contains `--debug --log-level debug` in the root folder of Joplin. Restart Joplin and there should be raw and striped logs.

And you can get the value for joplin_notebook_guid by copy the external link of **notebook**.

**Comment by Anderbone** [comment]
@Explorare  Thank you so much, problem is, there's no related log at all in joplin, as if nothing happened. I tried to use joplin web clipper to clip a page in the browser and it works fine.

**Comment by Explorare** [comment]
The web clipper runs at localhost without need to bypass the firewall. So, I think there is still some issue with the configuration of firewall or port forwarding.
To check the port forward settings, run
```
netsh interface portproxy show v4tov4
```
The result in my environment is
```
Listen on ipv4:             Connect to ipv4:

Address         Port        Address         Port
--------------- ----------  --------------- ----------
0.0.0.0         41185       localhost       41184
```
Run `netsh advfirewall set allprofiles state off` to close firewall for a quick test. Remember to enable it again after the diagnosis.

**Comment by Anderbone** [comment]
@Explorare 
![image](https://user-images.githubusercontent.com/10970596/147859942-21fc9d7f-4322-4c28-9d47-1de7b963f1d9.png)
Clicked twice on koreader, really have no idea. Guess I will just use the exporting highlight to text for the moment, thanks again for your help, really appreciate it.

**Comment by Explorare** [comment]
@Anderbone The listening port should be `41185` on `0.0.0.0` and forward (connect) to `41184` on `localhost`. You need to reset port forward settings first by `netsh interface portproxy reset` or `netsh interface portproxy delete`.

**Comment by Anderbone** [comment]
@Explorare  Thank you, my bad! But don't know why it's still not working, even Wireshark doesn't show anything now. They are in the same wifi.
![image](https://user-images.githubusercontent.com/10970596/147889915-23103ddd-f1e1-4c5f-8002-b1837c7bf117.png)

**Comment by Explorare** [comment]
Enable debug mode by creating a file in the root directory of Joplin named `flags.txt` contains `--debug --log-level debug`. Restart Joplin and there will be a log file named `log-clipper.txt` in `C:\Users\foo\.config\joplin-desktop`. Try sending the note again and append the log here.

**Comment by Anderbone** [comment]
[log-clipper.txt](https://github.com/koreader/koreader/files/7804164/log-clipper.txt)
@Explorare  There's no related info in the log.txt or log-clipper.txt, I clicked sending at 21:44.
![image](https://user-images.githubusercontent.com/10970596/147983928-424417cc-4f92-4422-a0e0-d4597362a744.png)
![image](https://user-images.githubusercontent.com/10970596/147984044-17f971fa-8333-4b31-beec-694ad0b23a5c.png)

**Comment by Explorare** [comment]
@Anderbone Well, then you may try it in another computer if you are still interested in it.  Just like our life, when it just doesn't work out, there is not always an obvious way to fix. 😅
