### ISSUE TITLE
Back button for turning next page

### ISSUE THREAD

**Issue by MatteAce** [koreader/koreader#8336]
On the Onyx Nova 3 there's just a single physical button, and right now it can only be configured to exit koreader or go back one page. I think it'd be useful to configure it for next page turning also.

**Comment by mergen3107** [comment]
Outside KOReader, you can try using Button Mapper to assign three actions: single press, double press and long press. 
Try setting Back button to Page down, for example. For the actual back action set it to double or long press.

**Comment by mergen3107** [comment]
Yes, you can :) Just install Button Mapper and try it for yourself. It does not need root for these basic actions you are asking about.
