### ISSUE TITLE
Crash at sleep on Kobo Aura (N514)

### ISSUE THREAD

**Issue by 0ldb34r** [koreader/koreader#8339]
* KOReader version: 2021.10 "Seagull"
* Device: Kobo Aura (N514)

#### Issue
Every time I want to put my Kobo under KOReader on standby, it crashes and restarts on KOReader.
My only way to turn it off is to go back to the original KOBO system to turn it off.
To come back to KOReader, I have to turn on the reader and go back to KOReader from the original KOBO system

#### Steps to reproduce
Try to put KOReader on standby...

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/7360093/crash.log)

**Comment by YariFranceschi** [comment]
> 
> 
>     * KOReader version: 2021.10 "Seagull"
> 
>     * Device: Kobo Aura (N514)
> 
> 
> #### Issue
> 
> Every time I want to put my Kobo under KOReader on standby, it crashes and restarts on KOReader. My only way to turn it off is to go back to the original KOBO system to turn it off. To come back to KOReader, I have to turn on the reader and go back to KOReader from the original KOBO system
> #### Steps to reproduce
> 
> Try to put KOReader on standby...
> ##### `crash.log` (if applicable)
> 
> [crash.log](https://github.com/koreader/koreader/files/7360093/crash.log)

![photo_2021-10-17_16-33-54](https://user-images.githubusercontent.com/10484837/137632202-133cde3e-d059-430b-945e-7a911fa47907.jpg)
Crash on sleep also on my Kobo Clara HD.
When I press the power button to go to sleep the crash happens.
It happens when the screen is on the book. It doesn't crash when the screen is on the "Home" page.

**Comment by hius07** [comment]
Sorry, it's https://github.com/koreader/koreader/pull/8318. I"ll fix it soonest.

**Comment by hius07** [comment]
@Frenzie, it has been merged immediately (sorry, missed changes in github ui after my new status).
Keep it or revert?
https://github.com/koreader/koreader/blob/4ffabcf0871dc3b48e5ee1b545c6c54057a28b1b/frontend/ui/screensaver.lua#L557

**Comment by Frenzie** [comment]
@hius07 You mean you accidentally committed straight to master? Luckily this is exactly the kind of scenario where that's fine (a minor fix/typo), but yes, please try to avoid it. We (I?) like to be informed about what's happening without having to look at the commits, hence for example https://github.com/koreader/koreader/pull/8334 is just an FYI, not meaningfully intended as something to be reviewed by anyone.

The process I'd like you to follow for a minor change like this is closer to:

1. Put it in a PR
2. Wait at least two days, probably a few more

Chances are someone will have dropped by and left an approval, but if not that'll have given you enough time to look at the changes with fresh(er) eyes. If you're still satisfied at that point, you can use "squash and merge." But please, only for minor changes.

**Comment by Frenzie** [comment]
Fixed by 4ffabcf0871dc3b48e5ee1b545c6c54057a28b1b.

**Comment by hius07** [comment]
Noted, thank you.
