### ISSUE TITLE
FR: Allow network actions without being connected to wifi

### ISSUE THREAD

**Issue by rayes0** [koreader/koreader#8345]
**Does your feature request involve difficulty completing a task? Please describe.**

Currently when initiating network actions on a device with wifi turned off, KOReader prompts for whether wifi should be turned on, and there are two options: "Cancel" (which cancels the action entirely), and "Turn on" (which turns wifi on and waits for a connection before the action is started). Some devices have support for ethernet over usb, and forcing wifi to be one before a network action restricts the usefulness of this feature, for example if there is no wifi but an ethernet over usb connection is available. Additionally, some devices like my kindle can only handle one active connection (if ethernet over usb is enabled, wifi doesn't work, and vice versa), meaning that I can't make connections with ethernet over usb at all.

**Describe the solution you'd like**

It would be ideal for there to be an extra "try anyway" option in the popup asking whether or not to enable wifi that will try to connect regardless of whether wifi is on or not. For example like in [Ankidroid](https://github.com/ankidroid/Anki-Android):

![image](https://user-images.githubusercontent.com/70722312/137842790-ab9b1f73-2610-4b4a-952a-f3c8ba897627.png)

This will allow connections with ethernet over usb without needing wifi connected.

**Describe alternatives you've considered**

Any other way of allowing connections without wifi would also work, such as a setting.

**Additional context**

For those wondering why ethernet over usb is useful in the first place, I use it for creating a local connection to my computer when there is no network available, or when local network requests are blocked (eg: shared networks in cafes, libraries, and other public places). I can then do things like run a Calibre server and connect to it from the device, or ssh into the device, all over usb.

**Comment by Frenzie** [comment]
This is currently an Android limitation.
https://github.com/koreader/koreader/blob/6492583e96399e3ef3b628bc5bd4263e8d211155/frontend/ui/network/manager.lua#L227-L250

There's an old API that offers something similar that could probably be plugged in: 
https://developer.android.com/reference/android/net/NetworkInfo

And then there's a newer one:
https://developer.android.com/reference/android/net/ConnectivityManager#getNetworkCapabilities(android.net.Network)
