### ISSUE TITLE
Auto warmth plugin suggestions

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8346]
Thank you @zwim  for this cool plugin. It works very nicely and saved me from constantly adjusting warmth (For some reason original setting never worked on my device). Now my reader behaves like my pc and my phone 🎉

I started writing help information about this plugin for the **User Guide**. When you are trying to explain something to someone else (as in writing a manual) you can see things differently. Here are my suggestions that might make the plugin more user friendly and improve clarity. As the author you are free to ignore some or all of them of course. But "I did my part" at least :)

---

**First a mockup of my suggestions. Explanations continue under the picture:**

![auto warmth suggestion](https://user-images.githubusercontent.com/84420582/138038677-afde0398-7d87-4f15-a62e-506762725c39.png)

First menu item contains usage information so **Usage information** is a better name for it. **About** sections generally contain only author name and version info as in KOReader's about section so users might not expect usage info there.

**Expert mode** should not be the first setting. First action a new user will do is **Activating the plugin** so **Expert mode** can come after that.

Location settings menu item can be renamed to **Set location** or **Set your location** implying a direct action.

The word **Schedule** causes a slight ambiguity in my opinion. Because what this plugin does is adjusting fronlight according to a SCHEDULE whether it is fixed or Sun based. So calling one mode as **Time Schedule** can be confusing because Sun mode changes according to a time schedule too.

So two menu items can be renamed to:
` Sun position based schedule info`
`Fixed schedule info`

Also Active parameters can be renamed to:
`Currently active parameters`
for a bit more clarity

In the Activate sub-menu first two items can be changed to:
Activate...
`According to Sun position`
`According to fixed schedule`
for more clarity

I have a hard time understanding what 3. and 4. items do.
I think **Whatever closer to...** items aim to manually force the current time as if it is day or night.
If I understood correctly items can be renamed as:
`Set as day time`
`Set as night time`

(With these last items above I am not so sure my suggestion is more clear than current version. Trying to start a discussion for better labeling.)

**MAYBE A PROBLEM:** Also there might be a mistake in **Set Warmth and Night Mode** menu because **Daytime** item changes **Sunset** warmth value and considering there is no separate Sunset item I think that one IS the Sunset.

**Comment by zwim** [comment]
Most renamings sound good to me. I will wait for the discussion here, before I do a PR.

*) The first menu entry is often called `About xxx` (Coverimage, css_tweaks, ... I have counted at least 8 occurrences). So I don't want to change that for now. What do the others in here think?

*)
> MAYBE A PROBLEM: Also there might be a mistake in Set Warmth and Night Mode menu because Daytime item changes Sunset >warmth value and considering there is no separate Sunset item I think that one IS the Sunset.

Well, you are right. Actually the sunset and sunrise values are set, so we can name it `Sunset and sunrise` (To be consistent we should call it `Darkest time of day(light)` ;) but that sounds a bit awkward). 

*) Let me explain, what the entries `Closer to noon` and `Closer to midnight` do:
You have two schedules with the same entries but different times
![grafik](https://user-images.githubusercontent.com/36999612/138101572-cc87a277-5e4f-447b-8137-75f93cab8260.png)

As you can see: `Closer to noon` takes the time form the sun schedule and the fixed schedule, which is closer to noon.
`Closer to midnight` does the opposite thing.

You can see in the `Information menus` which schedule is taken (here closer to noon was activated):

![grafik](https://user-images.githubusercontent.com/36999612/138103404-7faebddb-1cd3-4333-84fa-6256912a3c55.png)

**Comment by zwim** [comment]
I am no English doctor, but what about `Details on xxx yyy zzz` (it is only 5 chars longer than `about xxx yyy zzz`)? Is it good English?

**Comment by poire-z** [comment]
Addressed by #8350 (I think).
