### ISSUE TITLE
Closing and opening the reader cover brings up a blank screen

### ISSUE THREAD

**Issue by Glover1969** [koreader/koreader#8352]
* KOReader version: 2021.10.1
* Device: InkPad 3

#### Steps to reproduce
Closing and opening the reader cover brings up a blank screen

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Glover1969** [comment]
Oh sorry I didn't notice.  The same issue, in fact.

**Comment by ReaLx3m** [comment]
Same issue present on Inkpad 3 Pro, with koreader 2021.11
