### ISSUE TITLE
Translate to note

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8375]
Just a pipeline to save translation of highlighted text to the note immediately.
Pressing `Translate to note` we get an Edit note dialog filled with the (marked) translation, can edit and save it.
Can it be of interest to anybody?

![01](https://user-images.githubusercontent.com/62179190/138869174-0314aab9-530c-48ce-9d72-2dccf673ecf8.png)
![02](https://user-images.githubusercontent.com/62179190/138869181-622ce385-cd1a-4213-8088-a72a0946dd73.png)
![03](https://user-images.githubusercontent.com/62179190/138869186-5f89531b-7c1c-4aac-853e-a68bbcbcb0d3.png)
![04](https://user-images.githubusercontent.com/62179190/138869191-62b1f94f-868b-4ecf-b61c-2ec7c29ee206.png)

**Comment by poire-z** [comment]
> BTW, there was an idea for the tenth button, nobody interested: #8375

I'm glad nobody got interested :) But I still think it's a super idea - it was [one of my examples](https://github.com/koreader/koreader/issues/5794#issuecomment-943146728) about what we could do after bookmarks are reworked with proper slots.
Obviously, I don't think it's a super idea putting any crap into a multipurpose "notes" slot in the meantime :) as it will cause more work later if/when trying to sort "notes" into proper dedicated slots.

In any case, I agree with @Frenzie : I don't think it should be a button in this generic highlight dialog - but one in the Translation result widget . And even there, where there can be multiple translation results, I think one should be able to edit or pick one of the results before it is put into the highlight slot (dunno if you took the first/main one in your screenshot - or if you got only one result).

(We could go crazy and add in this highlight dialog: `Wikipedia intro to note` - which I think could be also a good idea :) and probably others.)

**Comment by hius07** [comment]
Okay, waiting for new FR/issues regarding Bookmarks after the November release.
