### ISSUE TITLE
Kindle 3 can't reopen keyboard on select

### ISSUE THREAD

**Issue by mehalter** [koreader/koreader#8377]
* KOReader version: 2021.10.1
* Device: Kindle 3 (Wi-Fi)

#### Issue

When I open a pop up with text fields, it automatically selects the first input and opens the keyboard. After filling it in, I close the keyboard with the back button and scroll down to the next field and select it but the keyboard does not reopen. I have tried everything I can think of and can't get it to let me edit more than just the first text entry box. (i.e. adding a new OPDS Catalog)

#### Steps to reproduce

Open a pop up with more than one text box (example: adding a new OPDS Catalog), enter text, close the keyboard with the back button, move down to the next box and select.

**Comment by EmeraldSnorlax** [comment]
I am also experiencing this issue on my K4.

**Comment by poire-z** [comment]
Probably solved by #8859 or followups PRs.
