### ISSUE TITLE
Kindle 3 Cannot select button in prompts

### ISSUE THREAD

**Issue by mehalter** [koreader/koreader#8378]
* KOReader version: 2021.10.1
* Device: Kindle 3 (Wi-Fi)

#### Issue

When I open a pop up with multiple buttons, I cannot select anything except the left most button. When I try to add an OPDS catalog or even just create a new folder I can only scroll down and select the "Cancel" button, but cannot move to the right to pick the "Create" or "Add" or any other buttons. Also should note, the only dialog box that seems to behave properly is the one to exit Koreader and selecting Cancel or Exit.

#### Steps to reproduce

Open a pop up with more than one button, for example adding a new folder. Type in the new folder name, scroll down to the cancel button. Try to move right to select the "Create" button. Moving left or right has no effect, and scrolling down just wraps the selector back to the top.

**Comment by poire-z** [comment]
Probably solved by #8859 or followups PRs.
