### ISSUE TITLE
FR: Custom sorting order in alt status bar

### ISSUE THREAD

**Issue by rixx** [koreader/koreader#8389]
I'd like to be able to sort the elements of the alt status bar, just like with the bottom status bar as of #5329. In particular, I like to have the time in the outside corner to make it easier to find.

(In general it would be nice to have access to all status bar elements in the alt status bar, for example memory consumption, but I assume there's a reason that the two are so different)

**Comment by zwim** [comment]
Technically spoken the alternate status bar is hard coded in `crengine`. Maybe you can get someone from the CoolReader team to change that.

The bottom bar is handled by our frontend. Changes there can be done more easily.

**Comment by rixx** [comment]
Gotcha, that explains the differences.
