### ISSUE TITLE
Pocketbook 623 - Freezes after a while or when going into sleep mode

### ISSUE THREAD

**Issue by TiberiusRegenschein** [koreader/koreader#8392]
* KOReader version: KOReader 2021.10.1
* Device: Pocketbook 623

#### Steps to reproduce

1. Open koreader app
2. Open epub in koreader
3. push on/off button for sleep mode
4. Pocketbook goes into sleep mode
5. After a while app crashes and reader stays on (LED showing activity permanently on - See attached crash log.
I tried also other ways to switch of the device and koreader by:

1. Automatic switch off
2. Switch off with koreader menu
3. By using the power button
4. Using pocketbook task manager

None of the way worked and the device needed a reset.

In general: I am deeply impressed by the app allowing a very good reading experience on my very old device. Better than the build in reader e.g. for annotations. Unfortunately the freeze, which happens every time I want to switch off the device, forces me to stay with the build in reader. Thank you very much!

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
[crash.log](https://github.com/koreader/koreader/files/7447501/crash.log)

You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>
[crash.log](https://github.com/koreader/koreader/files/7447503/crash.log)

```
<Paste crash.log content here>
```
</details>

**Comment by TiberiusRegenschein** [comment]
Maybe this helps: When I am reconfiguring the long-press home button to trigger sleep-mode on the pocketbook, it does not crash. Only when using the on/off button.
It looks like anything activated via the on-off button is in conflict with ko-readers own events.

**Comment by TiberiusRegenschein** [comment]
In the meantime I found a solution which is working for me based on issue #8053 

modify koreader/frontend/device/pocketbook/device.lua at line 267 :
inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn )
by
inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn or "[nil]")
To avoid crash when there is a nil value for book name.

Thanks for the solution!

**Comment by NiLuJe** [comment]
Oh, no-one actually pushed a final version of this yet? >_<".

**Comment by TiberiusRegenschein** [comment]
Just wanted to say "thank you". Tested since several nightly builds with my old PB623 and firmware 4.4 and with my latest PB741 and latest firmware 6.5. All good an devices are stable. 😊
