### ISSUE TITLE
[ERROR] Filesystem is busy - dropbear/sftp-server

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8394]
- KOReader: **2021.10.1**
- Device: **Kobo Libra H2O**

Rare error which happened once before with the 21.08 version so probably it is not caused by a new change. 
- Happened while accessing File Manager from an open book.
- Wifi and SSH server was off during error (They are both working properly. They were just not enabled during error). 
- USB cable wasn't connected.
- Restarting KOReader didn't help, had to reboot the device.

Only related info in the crash.log:
`KoboUSBMS failed to setup an USBMS session, restarting KOReader . . .`

![mass storage error](https://user-images.githubusercontent.com/84420582/139572761-18277116-2f13-4905-913c-c1ad9bd07784.jpg)

**Comment by NiLuJe** [comment]
Seems pretty straight-forward: You have an old hung transfer lingering ;).

Stopping an SSH server does *not* kill pending sessions, this is why you can actually restart one to update it in a remote box without losing your access if shit goes boom ;).

**Comment by chrisbrasington** [comment]
> Stopping an SSH server does _not_ kill pending sessions, this is why you can actually restart one to update it on a remote box without losing your access if shit goes boom ;).

Why not have stopping an ssh server kill pending sessions? That would avoid this issue.

**Comment by chrisbrasington** [comment]
> Nice necro.
> 
> You forgot to read my second paragraph, though.

I didn't read the paragraph I quoted?

First - I can make a new issue - the original context here is useful - restarting KOReader doesn't fix. 

Second - there's no resolution to encountering this scenario provided that isn't fully reboot the device, which sucks. Just another closed bug and "put up with it I guess". One would reasonably figure that restarting KOReader or turning off SSH would kill this zombie, hung process, but it doesn't. 

Nice engagement with fans I guess.

**Comment by NiLuJe** [comment]
> Stopping an SSH server does _not_ kill pending sessions, this is why you can actually restart one to update it on a remote box without losing your access if shit goes boom ;).

*That* §.

**Comment by NiLuJe** [comment]
To be clear: if you have a stray sftp process alive on your device, it's a *you* problem. e.g. you *actually* have an open client *somewhere* on your network.

(e.g., the fish KIO might still do something like this, possibly sshfs, too).

**Comment by chrisbrasington** [comment]
Of course the problem is me with a zombie ssh process that wasn't closed properly. But then what's the point in KOReader restart? I wouldn't call anything a restart that leaves subprocesses around..

**Comment by Frenzie** [comment]
We're actively opposed to such a hostile idea, but luckily you may be focused on the wrong part of the OP. A regular restart of the program should do no such thing, but while it's very much expected behavior for even a regular stop (sigterm), maybe it should ask if you want to sigkill it in this specific context if it doesn't stop running.

https://github.com/koreader/koreader/blob/89a24dabd8a43767426a1893d14c92bc833f7e3c/plugins/SSH.koplugin/main.lua#L92

**Comment by offset-torque** [comment]
At least this screen should be more helpful for average users. 
Let's go over it:
- `Filesystem is busy! `- I don't know what this means. Is it I/O saturated? I don't think so.
- `Offending processes` - What is their offense? This sounds like something bad happened? (NO)
- `Press the power button to exit.` - To exit what? KOReader? This screen? I guess this will solve the problem (NO).

**A more informative message can be something like this (Frenzie can correct this if some part is wrong):**
```
It seems that you have a stuck SFTP transfer so the filesystem is in a locked down state.
You may need to reboot your device to solve the problem. 
Press the power button to exit this screen.
```

First sentence explains the problem in a non technical way.
Second sentence provides the solution.
Third sentence describes the "next action" for the user.

If the message was written like this, I wouldn't have opened this issue because I would be properly informed of what is going on and how to solve it. 

We have looots of space there to write a proper info message if we shrink that gigantic ancient hard drive. Maybe we can replace it with an SSD to take less space ;)

**Comment by NiLuJe** [comment]
No, the error is generic, that it happens to trip because of sftp is pure
happenstance (and extremely  unlikely unless you have wonky clients).

c.f., man umount for EBUSY

**Comment by NiLuJe** [comment]
The process are offensive in that context because they hold an open fd to
the affected mount point, which is what marks it as "busy".

**Comment by offset-torque** [comment]
Thanks for the explanation NiLuJe, now I know the exact problem. But even if we write this on that screen, it won't make sense for the majority (+90% probably) of our users. So my point stands, that dialog can be improved as I described. Maybe this:

```
It seems that some processes are keeping your filesystem in a locked down state.
You may need to reboot your device to solve the problem. 
Press the power button to exit this screen.

Problematic processes:
1697 --> dropbear
...
```

**Comment by Frenzie** [comment]
> * `Filesystem is busy! `- I don't know what this means. Is it I/O saturated? I don't think so.

Windows gives you the same error without telling you which process is responsible. ;-P

> A more informative message can be something like this (Frenzie can correct this if some part is wrong):

As NiLuJe said, quite wrong. :-) But like I said above, this one specific scenario can probably be prevented with a kill -9 in stop SSH server.

> It seems that some processes are keeping your filesystem in a locked down state.
You may need to reboot your device to solve the problem. 
Press the power button to exit this screen.

I'd say something like:
```
Some programs are still using the filesystem:
```
