### ISSUE TITLE
Academy.KZ font issues

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#8407]
* KOReader version: 2021.10
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
Academy.KZ fonts has issues in KOReader:
- hyphens are different from the font's hyphen symbol
- symbols of hyphen and ellipsis (maybe others too) are rendered way too high in the line height

This was not the issue previously, about mid 2020 I believe, last time when I used the same font for another book.
Also, there was a issue with similar font (Academy) which didn't have such issues: https://github.com/koreader/koreader/issues/1929#issuecomment-333464307
Academy.KZ is the same Academy fonts just with extra glyphs for Kazakh letters.

Here are the screenshots:

Hyphens and ellipses:
![Screenshot_20211101-043745](https://user-images.githubusercontent.com/6279855/140032462-55ab2730-6ab2-4353-b1fd-62d2bb26d3e3.png)

The `?..` combination (question mark and two periods in a row, as well as other punctuation (period, comma, quotation marks) seem fine:
![Screenshot_20211103-043800](https://user-images.githubusercontent.com/6279855/140032601-283497ac-2b81-4444-bb5d-11621e576440.png)

#### Steps to reproduce
Use this font: [AcademyKZ.zip](https://github.com/koreader/koreader/files/7466339/AcademyKZ.zip)
- Hinting, Kerning, Line height, font size, rendering type, or any other settings from the bottom menu have no effect on this issue.
- MS Word (PC) and AlReaderX (Android) render the hyphens and ellipses correctly.
E.g. MS Word:
![Screenshot 2021-11-03 045141](https://user-images.githubusercontent.com/6279855/140032997-701dce4d-4471-44e9-8fae-9435733b9563.png)

**Comment by poire-z** [comment]
I'd say your font is crap. I get this:
![image](https://user-images.githubusercontent.com/24273478/140197048-b72ccf5b-5bed-44d9-9a99-6cf4153a336a.png)

No hyphen shown - where I think any line shorter there is having an hyphen that is taking some space but is not shown. It's possible you get them from another fallback font that I don't have ? Or some combinations different than I have. Or something :/
No issue with other fonts.
How other software do, I dunno. We trust Freetype/Harfbuzz, and if they don't render this font well, I'd say: use another font - rather than having us understand and fix FT/HB :)

Possibly similar issue/conclusion: #8290

**Comment by mergen3107** [comment]
@poire-z 
Thank you for looking! :) 
I’ll try to find a better font then 😅

**Comment by mergen3107** [comment]
@poire-z 
I downloaded another Academy variant, which has no Kazakh letters, but has correct ellipsis.
Hyphens, however, are still substituted by a generic hyphen.
I've looked up the font in FontForge and found out that the hyphen (U+2010) is present, but non-breaking hyphen (U+2011) is not. Does KOReader use U+2011 for the hyphens?

(I tried to copy the glyph of hyphen to non-breaking hyphen and regenerate the font, but it does not show up)

**Comment by mergen3107** [comment]
MS Word shows the U+2011 as U+2010, so it tries to find similar glyph, I think.

**Comment by poire-z** [comment]
crengine looks for UNICODE_SOFT_HYPHEN_CODE 0x00AD https://www.fileformat.info/info/unicode/char/00ad/index.htm
And I guess it finds it in the font (otherwise, it would pick it in a fallback font), and there is a glyph which has a width, but may be the glyph has no bitmap/black pixels.

**Comment by mergen3107** [comment]
Thank you very much! This explains why I didn't see any difference. I added the hyphen and it shows fine in KOReader :)

**Comment by mergen3107** [comment]
I have found some kerning error with this new font. Here is the font I currently use:
[AcademyNEW.zip](https://github.com/koreader/koreader/files/7529001/AcademyNEW.zip)
 
The problem is only when kerning is set to Harfbuzz (`good` or `best`) and only with some letter pairs, like `rс` `rd` `re` `ee` `ro`, and maybe some others which I might not yet encountered. Here are the screenshots:

1) Fast (no issues):
![1_fast](https://user-images.githubusercontent.com/6279855/141502012-4ed8a4a3-807d-44dd-ae9d-43104a1387f5.png)

---

2) Good:
![2_good](https://user-images.githubusercontent.com/6279855/141502033-969f66ac-a55e-4c09-adc0-46e272316e51.png)

---

3) Best (one more `ro`):
![3_best](https://user-images.githubusercontent.com/6279855/141502072-7920bf53-0672-476a-a313-5d1a3c407811.png)

---

Is this an issue related to:
- the font kerning? If so, how do check it in FontForge?
- KOReader's implementation of Harfbuzz? 
- Harbuzz itself? If so, maybe I should be reporting it to https://github.com/harfbuzz/harfbuzz directly?

**Comment by poire-z** [comment]
I remember there are 2 tables for kerning (kern, gpos, and I head about kerx). Freetype (fast) only uses one (kern?), while Harfbuzz may use the other, or both, or fallback to one or other, or not fallback to one or the other, dunno.
I don't know much abount Fontforge.

I checked with the Academy.KZ I downloaded some weeks ago, and there is no issue (actually, there might be no kerning at all as nothing changes when I toggle).
I checked with your AcademyNew (whose name is Academy Old, is that alright?), and I get like you.

I'd probably say again that this new font is new crap :)

> KOReader's implementation of Harfbuzz?
> Harbuzz itself? If so, maybe I should be reporting it to https://github.com/harfbuzz/harfbuzz directly?

Well, you'd have to check with other renderers that use Harfbuzz to see if it's KOReader or Harfbuzz itself that can't do good with this (crappy) font: Chrome may use Harfbuzz internally (but may be only on Linux), Harfbuzz may have some list of users on their pages.
But given the history of crapicity of your font, I wouldn't bother the HB people unless you're really sure of the people who made the font (and if it is you that tweaked it, well, I guess font tweaks need quite some experience we don't have). And I would rather inform the font authors so they can check with Harfbuzz, and let them contact the Harbuzz people if need be.

Some quick check with an older version I had compiled of their tool hp-shape:
```
$ hb-shape AcademyOld.ttf rs
[[r=0+295|s=1+341]]
$ hb-shape AcademyOld.ttf rv
[[r=0+295|v=1+413]]

   These seem good, small advance of 295


$ hb-shape AcademyOld.ttf ro
[[r=0+405|o=1+432]]
$ hb-shape AcademyOld.ttf re
[[r=0+409|e=1+386]]
$ hb-shape AcademyOld.ttf rc
[[r=0+403|c=1+392]]
$ hb-shape AcademyOld.ttf rd
[[r=0+408|d=1+484]]

   These get a large advance > 400 .


$ hb-shape --features=+kern AcademyOld.ttf ro
[[r=0+405|o=1+432]]
$ hb-shape --features=-kern AcademyOld.ttf ro
[[r=0+295|o=1+432]]

    Turning off the use of the "kern" table make it behave


$ hb-shape --features=-kern,+gpos AcademyOld.ttf ro
[[r=0+295|o=1+432]]
$ hb-shape --features=-kern,-gpos AcademyOld.ttf ro
[[r=0+295|o=1+432]]
$ hb-shape --features=+kern,-gpos AcademyOld.ttf ro
[[r=0+405|o=1+432]]

    Not much change with playing with other features.
```
So, I'd say your "kern" table has (bad) stuff for the "ro/rc/re/rd" kerning pairs, that it doesn't have (or it has good ones) for the "rs/rv" pairs. Might want to investigate in this direction.

**Comment by mergen3107** [comment]
> whose name is Academy Old, is that alright

Yeah, that font is a result of my Frankensteining a few variants of Academy together...



> I'd probably say again that this new font is new crap

Understandable :D 



> "kern" table

Thank you! I'll into the table then. 



> Turning off the use of the "kern" table make it behave

Yes, this is what I currently use. It is much more consistent on `fast` and the text is easier to follow.

**Comment by poire-z** [comment]
Closing as I'm confident it's not "our" issue :) But feel free to ask futures related questions in here.
