### ISSUE TITLE
Weird refresh in PDF related to highlighting (papercut refresh glitch)

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#8408]
- KOReader: **2021.10.1**
- Device: **Kobo Libra H2O**

> **CONTEXT:** This is a simple PDF file I generated by directly exporting a text document via Libreoffice. I use highlights for vocabulary learning. Basically I highlight unknown words. Remove the highlights when they are learned later. So there are lots of higlights in some texts.

https://user-images.githubusercontent.com/84420582/140038396-891444d3-fa3a-4d0c-9aca-1b78564fd71f.mp4

This weird refresh behavior happens irregularly. Generally it happens after each highlighted word, sometimes it is every 2-3 words. It also does the same on removing a highlight (press long on highlighted word). It is sometimes triangular as in the video. Other times as half of the screen or a bigger triangle. 

My **E-INK FULL REFRESH RATE** is set to **NEVER**. Also **AVOID MANDATORY BLACK FLASHES IN UI** is enabled.

Interestingly it doesn't refresh like this if I delete highlights by clicking on them and select **DELETE** from the menu.

**Comment by NiLuJe** [comment]
It's a race condition between the fb update and the actual refresh. On mobile right now, but we have an old issue called "papercut refresh glitch" about it ;). I don't quite recall anyone reporting one in these conditions, though.

**Comment by offset-torque** [comment]
This is an already known problem and there are not many reports about it since I opened this issue. So I am renaming the issue for easier finding and closing it.
