### ISSUE TITLE
Kobo Libra 2 & Sage: warmth light - minimum step is 10%

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#8410]
* KOReader version: v2021.10.1-48-gd9fc34cb_2021-11-02/ 
* Device: Kobo Libra 2, Kobo Sage

#### Issue

Warmth light's minimum step is 10%. Can it be changed to 1%?

![FileManager_2021-11-03_143743](https://user-images.githubusercontent.com/32645430/140070607-4261c17d-3861-40f8-93aa-14eb0b9ccd1f.png)

**Comment by Frenzie** [comment]
Nope, sorry.

https://github.com/koreader/koreader/blob/1bba05ff41628fbc7b4fd736ab992c1cf3f2b452/frontend/device/kobo/device.lua#L380

**Comment by NiLuJe** [comment]
There are only 11 actual steps, unfortunately, so we're at the best granularity we can.
