### ISSUE TITLE
Kobo Libra 2: tap corners in landscape don't work

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#8411]
* KOReader version: v2021.10.1-48-gd9fc34cb_2021-11-02/ 
* Device: Kobo Libra 2

#### Issue
When tapping corners in landscape the menus open for me, instead of my designated actions. They work in portrait mode.

**Comment by NiLuJe** [comment]
What do you mean by designed actions, exactly?

**Comment by gerhaher** [comment]
Sorry, bad english. Designated actions. Which you control through the gesture manager.

**Comment by NiLuJe** [comment]
Are the rest of the taps actually accurate in landscape?

**Comment by gerhaher** [comment]
Yeah, I think so.

Now I noticed that they work if I tap with just a little bit of my fingertip from the corner edges.

**Comment by gerhaher** [comment]
Maybe this isn't a bug.

Maybe the sunken screen fooled me. Maybe the high edge made the finger ended up to high.
 
Anyway. It works fairly well now.
I have increased the tap zones' height to 0.05 (from 0.04). And I am careful to hold the finger close to the bottom edge.

**Comment by Frenzie** [comment]
Out of curiosity, which is your old device?

**Comment by gerhaher** [comment]
KA1. And I never used it in lanscape mode.

**Comment by NiLuJe** [comment]
The Elan panel is also fairly verbose (in terms of the amount of events generated), while the KA1 had a truly awful touch panel, so it might take a bit of time to get used to it ;).
