### ISSUE TITLE
PocketBook InkPad 3 White screen after resuming from Sleep

### ISSUE THREAD

**Issue by cassw2** [koreader/koreader#8415]
* KOReader version: v2021.10.1
* Device: PocketBook InkPad 3

#### After updating to the latest firmware of PocketBook InkPad 3 when reader/koreader wakes up from sleep mode the screen is all white, I must touch the screen to things show up (resume book reading). **This didn't happened before the firmware update.** 
I also updated koreader from v2020.10.1 to the latest version v2021.10.1 but problem remains.

**Comment by poire-z** [comment]
Possible duplicate of #8187 ?
