### ISSUE TITLE
Settings and current page not saved for books stored in Books directory of SD Card on Likebook Alita Android 8.1

### ISSUE THREAD

**Issue by squiresque** [koreader/koreader#8423]
* KOReader version: 2021.10.1-51
* Device: Boyue Likebook Alita Android 8.1

##### `crash.log` (if applicable)  - there is no crash.log file, and I have not yet found a setting that allows me to turn debug mode on.   My help-Bug Report directs me to look for a crash log in a directory, but there is no such log that I can see with my File Manager App.  

NB: A prior issue identical to this one was closed due to my having uninstalled the current KO Reader release, and reinstalled an older version that did not have that problem (though it seemed to have far worse other problems not related to this one).  The installation of the prior KO Reader version confirmed to me that this problem with setting persistence on books stored on the SD Card was caused by an update to KO Reader and not caused by some other issue particular to my device.  

Thank you for any assistance you may be able to provide.

**Comment by poire-z** [comment]
> NB: A prior issue identical to this one was closed 

That is #8420.
You didn't need to create a new issue, we would have reopened the other one, as it has more info and tests results from you - I was just waiting for @pazos to confirm it was closed too quickly :)
Best to keep the discussions and investigation results in a single issue.

**Comment by pazos** [comment]
Yup, sorry. Reopened original issue and closed this one.
