### ISSUE TITLE
No word spacing when adding a note on a PDF

### ISSUE THREAD

**Issue by huronhorn** [koreader/koreader#8433]
* KOReader version: latest nightly (59)
* Device: kobo libra 2 / android

#### Issue
hi, i use nightly koreader on my devices, today i face a weird issue. When im highlighting a text to add a note in it, koreader seems cant recognize the spacing between text. I tried to emulate this issue on a stable build (10.1), but it seems stable build didnt have this issue. Ive attached screenshots from each stable and nightly builds to explain better.

<a href="https://ibb.co/6WrZKCd"><img src="https://i.ibb.co/6WrZKCd/stable-build-10-1.jpg" alt="stable-build-10-1" border="0"></a>
Stable build (10.1)

<a href="https://ibb.co/5TvxkWv"><img src="https://i.ibb.co/5TvxkWv/nightly-build-59.jpg" alt="nightly-build-59" border="0"></a>
Nightly build (59)

##############################################
ive also attached sample pages from pdf i use on this issue
[test page.pdf](https://github.com/koreader/koreader/files/7506898/test.page.pdf)

Cheers!

**Comment by Frenzie** [comment]
Pinging @cyphar (if I recall correctly).

**Comment by cyphar** [comment]
Looking at the debug logs, it seems that `getTextFromPositions` is returning the text with some spaces missing (just to note -- there are *some* spaces in the text). While the `selected_text` change did touch the highlighting code, the hold-and-pan selection shouldn't have been affected (and if `getTextFromPositions` itself is returning text with some spaces missing then it's and issue stemming from `getTextFromPositions`).

I'll do some bisecting this evening and try to figure out what's going on.

**Comment by cyphar** [comment]
Interestingly, the regression occurred in 6f1b70e5eb71fed5e1844ba4e39e69411b710d43 (`util.utf8: improve CJK character detection`) and this is definitely the case -- if you revert that commit then everything is fixed. I will look into this a bit more, it's very odd because the key changes should have no impact on non-CJK text (and the most obvious culprit -- `splitToWords` is not called outside of `TextBoxWidget`?!)...

**Comment by cyphar** [comment]
#8438 fixes the issue for me.

**Comment by Frenzie** [comment]
@huronhorn Thanks for testing the nightly! :-)

**Comment by huronhorn** [comment]
Np!, And thanks @Frenzie @cyphar 
It really is a great reader app, fingers crossed for #8414 , hope it got a good progress🤞
