### ISSUE TITLE
FR: Change wording in sizespinner

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8437]
When using a SizeSpinner, at the bottom, there is a button `Use default`.
I am and I was often misleaded. For my understanding `use` means `set`. 
I want to propose a more definite wording: `Show default`.
So, if one is pushing `Show default` the value appears. `Show` does not implicit that something changes, it is just a show.
If one want's this value, it is clear to push the `Set ...` button.

**Comment by poire-z** [comment]
Will need some input from our English scholars - as you and me read English with our own language bias.
I have no problem with `Use default`: it sounds like I'll use it, no confusion with `Set`'ting the current spin value as the default. And as upon hitting it, the spin value is updated but we don't exit the widget, it feels I have to hit `Set` to really apply it.
But `Show default` sounds a bit vague/odd: I would expect it would show it somewhere, as information, and not to replace the current spin value.
`Pick default` would sound better to my eyes/ears.

**Comment by Frenzie** [comment]
Use is better than show (which implies a popup or something), but you can always just call it reset.

**Comment by Frenzie** [comment]
But no, reset is the initial state of the widget, not the default. I see no difference between pick and use though.

**Comment by hius07** [comment]
Maybe put the button first and name it `Default value`, no verb emphasizes that there is no action on it.

![1](https://user-images.githubusercontent.com/62179190/141980138-1f481ad5-7146-4e7a-a101-3048c4dd0ea6.png)

**Comment by zwim** [comment]
I like that!
