### ISSUE TITLE
Wiki: Thank you for style tweaks

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8440]
Currently, I read a book in two column mode. The gap in the middle between the columns is extremly ugly wide.

Style-tweaks saved my life ;): `Style tweaks -> Pages -> Ignore publisher margins. check`

I could not find this hint on the wiki page, but google did.

So I have added a link to https://github.com/koreader/koreader/wiki/Style-tweaks in the navigation menu. I hope this is ok.

Mayby some wizard of styles wants to update that wiki page (it is quite old) and give a few use cases?

**Comment by poire-z** [comment]
Some of them have some description, certain with use cases - that you can get with a long-press on a style tweak in that menu.
We can add more if needed, but it shouldn't be too long and verbose.

But I think the use case you found out is a bit too specific, and obvious :) So, it may be good on the Wiki where we could list the classic style tweaks and have people add the use cases where it helped with. (And yes, this page is old and ugly :/)
(But well, it would be like describing the World :) so many use cases, some obvious that I wouldn't even think about mentionning, some other too specific that I would have a hard time describing and that I would meet only once anyway :)
