### ISSUE TITLE
Bookmarks/highlights in incompatible engines

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8451]
When trying to open a document with non-default engine we get a crash if there are bookmarks or highlights in the document.
This is valid for both engines:
-open epub in crengine, make a highlight, open it in mupdf, crash
-open epub in mupdf, make a highlight, open it in creingine, crash

There is a check for incompatible bookmarks
https://github.com/koreader/koreader/blob/58c4db694e95bfb93d7dd7a6d8aa5268533c6314/frontend/apps/reader/readerui.lua#L553-L577
which proposes to delete all bookmarks to open the document.
There is no check for incompatible highlights, so currently we can get a crash. (https://github.com/koreader/koreader/pull/3653#issuecomment-362339909)
And deleting bookmarks is not the best solution, isn't it?

Having a conversion of bm/hl between cre/pdf formats is not a trivial task (at first glance I haven't found solutions for some difficulties). But I think it is not necessary because of the use case:
usually we read a certain book in one engine. Opening it in another engine may be interesting (how it looks?), but is there a sense to switch engines frequently and make new bm/hl everywhere?

So, the idea is to backup bm/hl when opening a document in incompatible engine:
-check for existing bm/hl
-if any, warn a user that existing bm/hl will not be shown and any new bm/hl will not be saved
-backup bm/hl (flushing to doc_settings and freeing the memory)
-delete bm/hl
-open the document
-while reading, a user can make new bm/hl, but they won't be saved (not an issue, we opened the document in incompatible engine just for a quick view)
-on closing the document, restore bm/hl and delete backup.

**Comment by dosimple** [comment]
I'm curious about previous discussions on the two engines concerning epub. Can someone have links for them?

**Comment by poire-z** [comment]
> There is a check for incompatible bookmarks
> which proposes to delete all bookmarks to open the document.
> There is no check for incompatible highlights, so currently we can get a crash. ([#3653 (comment)]

You mean we just deleted the "bookmarks" setting, and forgot to delete the "highlight" entry ? If we would do that, the crash issue is solved ?

> And deleting bookmarks is not the best solution, isn't it?

Probably :) But for the use case (who really switch between rendered ? at most, one would try it when opening a document and seeing it ugly, trying the other renderer, which I guess wouldn't be better, so back to first), I don't mind the deletion.
But I'm fine if you want to handle that better - as long as it doesn't add much complexity.

> Having a conversion of bm/hl between cre/pdf formats is not a trivial task (at first glance I haven't found solutions for some difficulties). But I think it is not necessary because of the use case: usually we read a certain book in one engine. Opening it in another engine may be interesting (how it looks?), but is there a sense to switch engines frequently and make new bm/hl everywhere?

Nope. And I also agree we don't need any conversion.

> So, the idea is to backup bm/hl when opening a document in incompatible engine: -check for existing bm/hl -if any, warn a user that existing bm/hl will not be shown and any new bm/hl will not be saved -backup bm/hl (flushing to doc_settings and freeing the memory) -delete bm/hl -open the document -while reading, a user can make new bm/hl, but they won't be saved (not an issue, we opened the document in incompatible engine just for a quick view) -on closing the document, restore bm/hl and delete backup.

Sounds a bit complex.
If you can detect from existing bookmarks and highlight entries they are "paging" or "rolling", and the engine is the other one, just rename them to `bookmarks_rolling` and `highlights_rolling` (when switching from crengine to mupdf) - and create new bookmarks into new empty `bookmarks`/`highlight`.
When opening later with crengine, check if `bookmarks_rolling` and `highlights_rolling` exists, and if yes, rename the existing ones to `bookmarks_paging` and `highlights_paging`, and the _rolling ones to the normal names.
Or something like that, in a single docsettings.

> I'm curious about previous discussions on the two engines concerning epub. Can someone have links for them?

Dunno if we really discussed the differences anywhere. It's just something that was possible, so @Frenzie implemented an option to choose a provider/engine.
May be you'll find some micro discussions aming these search results: https://github.com/koreader/koreader/issues?q=sort%3Aupdated-desc+epub+mupdf+renderer

**Comment by hius07** [comment]
> just rename them

Do you mean rename a key in a table?

**Comment by poire-z** [comment]
> Do you mean rename a key in a table?

Yes, just somethings like this:
```lua
settings["bookmarks_rolling"] = settings["bookmarks"]
settings["bookmarks"] = {}
```
Or with our DocSettings indirection:
```lua
prev_bookmarks = config:readSetting("bookmarks")
config:saveSetting("bookmarks_rolling", prev_bookmarks )
config:delSetting("bookmarks")
bookmarks = config:readSetting("bookmarks") or {}
```
