### ISSUE TITLE
Kobo Libra 2 Screen Refresh on Landscape when waking 

### ISSUE THREAD

**Issue by hcors** [koreader/koreader#8453]
Running the nightly build and when my Libra 2 wakes from sleep mode only the left 2/3 of the screen show the book, the Screensaver picture remains on the other third. A manual refresh fixes it easily, just wanted to report the bug.

**Comment by NiLuJe** [comment]
What was your reading orientation before the suspend, and which screensaver mode are you using?

**Comment by hcors** [comment]
I have it locked to landscape mode all the time, and the screensaver mode is when it shows the current book you are reading.

**Comment by NiLuJe** [comment]
Oh, hey, fixed that recently (#8943) ;p.
