### ISSUE TITLE
I cannot justify the text file type (.txt) until updating to 09.2021 or newer versions

### ISSUE THREAD

**Issue by yukari186** [koreader/koreader#8456]
As a title, I cannot justify by style tweak until upgrading to KOReader 09.2021 or newer versions (newest is 11.2021). Everything is ok again when I downgrade to the 08.2021 version. My device is Kobo Clara HD. I would like to update the newer versions but this bug is so inconvenient for me. Please help me fix it. Thank you so much.

**Comment by poire-z** [comment]
Probably similar to #8216.
Please look at it for the reason, and the solution provided (user style tweak containing `* { white-space: normal }`.
If it works for you, may be we should add it among our generic style tweaks (but a bit hard to name and explain).

**Comment by yukari186** [comment]
> Probably similar to #8216. Please look at it for the reason, and the solution provided (user style tweak containing `* { white-space: normal }`. If it works for you, may be we should add it among our generic style tweaks (but a bit hard to name and explain).

I tried but it doesn't work. Please help me check I wrong what step TT_TT
![Uploading IMG_20211120_201336_163_1.jpg…]()

**Comment by yukari186** [comment]
![IMG_20211120_201349_134_1](https://user-images.githubusercontent.com/90317108/142728040-4bbfc891-df61-498e-aa34-67d4a804869d.jpg)

**Comment by yukari186** [comment]
> Probably similar to #8216. Please look at it for the reason, and the solution provided (user style tweak containing `* { white-space: normal }`. If it works for you, may be we should add it among our generic style tweaks (but a bit hard to name and explain).

I tried but it doesn't work. Please help me check I wrong what step TT_TT
![IMG_20211120_201336_163_1](https://user-images.githubusercontent.com/90317108/142728066-fb3805a5-1bae-406d-a25b-9a79a4abe70a.jpg)
![IMG_20211120_201349_134_1](https://user-images.githubusercontent.com/90317108/142728069-5c80aa9e-d4d5-41d5-9a05-623ee34425dc.jpg)

**Comment by yukari186** [comment]
> Probably similar to #8216. Please look at it for the reason, and the solution provided (user style tweak containing `* { white-space: normal }`. If it works for you, may be we should add it among our generic style tweaks (but a bit hard to name and explain).

I fixed it ^^ Thanks for ur support

**Comment by poire-z** [comment]
I think I'll add support in crengine for `-cr-only-if: txt-document` (we already have `epub-document` and `fb2-document`) so we can just add  `* { -cr-only-if: txt-document; white-space:normal }` to the "Justify most/all text" tweaks.

**Comment by poire-z** [comment]
The "Justify most/all text" tweak should work now on txt documents with #8487.
