### ISSUE TITLE
file manager icon freeze

### ISSUE THREAD

**Issue by d3m3t3r** [koreader/koreader#8470]
* KOReader version: v2021.11
* Device: PocketBook 630

#### Issue

Opening the file manager using the icon in the menu completely freezes the application.  The only screen update is that the icon gets "pressed" (inverse).  There is no crash.   

Note, simply putting the device to sleep and immediately waking it up by the power button returns it to the stock Home screen.

#### Steps to reproduce

Open the top menu and click the file manager icon (the rightmost "shelves" icon).

**Comment by utkb** [comment]
I have same device and same problem. Additonally, file maneger starts succesfully at the opening. But when i click menu item, same frezee happen. And there is no crash screen triggerred.There is no information in the crash log.

**Comment by utkb** [comment]
Solar Panel works perfect for me now...

**Comment by Frenzie** [comment]
PocketBook firmware update?

**Comment by utkb** [comment]
> PocketBook firmware update?

No, i have a very old model.

**Comment by Frenzie** [comment]
Possibly fixed a couple of years ago by <https://github.com/koreader/koreader/pull/8823>? It'd be nice to know what did the trick but without a crash.log it's impossible to say. In any case, closing then, thanks for the update.
