### ISSUE TITLE
FR: Ltris set for Kindle version

### ISSUE THREAD

**Issue by treymerkley** [koreader/koreader#8476]
**Does your feature request involve difficulty completing a task? Please describe.**
No difficulty whatsoever, this is purely a nice to have.

**Describe the solution you'd like**
I saw that Ltris was a game that looks like it was planned for the Kindle edition, but that never materialized. If it already exists and is no large effort to implement, I'd really appreciate an implementation.

**Describe alternatives you've considered**
Playing another Tetris clone on another device.

**Additional context**
N/A

**Comment by Frenzie** [comment]
This seems to have been opened on the wrong repo? (NB All of ours would be the wrong repo.) Closing, but feel free to reply with more references.

**Comment by treymerkley** [comment]
Yeah, totally. This is the file in question. If nobody knows anything about this, can it be removed? https://github.com/koreader/koreader/blob/ea3fa5c2c7ed7330e8e1e6ef838b780e7998ea51/platform/kindle/BR-2020.02-config

**Comment by Frenzie** [comment]
No. :-) That's the configuration to build wmctrl. See <https://buildroot.org/>.
