### ISSUE TITLE
Backslash not displayed

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8486]
* KOReader version: v2021.11-21
* Device: PB 628

#### Issue
In the pop-up explanation window of "Regular expressions" the backslash (\) does not appear in the Greek translation. Is it related to the font?

* Even in the above sentence it is omitted. I had put it in brackets!

**Comment by Frenzie** [comment]
Screenshots for reference.
<img src=https://user-images.githubusercontent.com/202757/143772679-36dc98bc-cf93-4a68-94c6-7c05809c23de.png width=30%> <img src=https://user-images.githubusercontent.com/202757/143772680-ef06ad22-1279-4f04-b47c-dd9f8d02630e.png width=30%> <img src=https://user-images.githubusercontent.com/202757/143772752-32d3cafd-739b-4693-b783-5fbf2d8de1d0.png width=30%>
