### ISSUE TITLE
Keyboard layout in device-menu.

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8492]
We have a tiny inconsistency with the keyboard layout display: Different layouts can be set by device-menu -> keyboard -> keyboard layouts.
In there 0-4 layouts can be selected. If _none_ is selected the default (according to the virtual keyboard) is shown there. So far so good.

But you can also select a totally different keyboard in the virtualkeyboardwidget, which is then used as default, **but** not shown in the device-menu. I feel this is misleading.

Now I have a problem: Selected are Deutsch and  English (and therefore two checkmarks in the underlying menu) and in virtualkeyboard select Francais. 
I could now show: `Keyboard layouts: Francais, Deutsch, English` (The currently active keyboard first). This might be right and desirable, **but** we only have two checkmarks in the layout selection menu.
So my proposal would be to add an additional symbol to both layout selection positions (menu and virtualkeyboard) to indicate what is currently active.

Maybe something like: `☆` is indicating the currently active layout.

![grafik](https://user-images.githubusercontent.com/36999612/143905442-ce84b640-0dcb-4bb7-8de9-fa8b40d42dc0.png)

**Comment by zwim** [comment]
Oh and by the way I would swap ☆ and ★
★ shows the active layout 
☆ shows the default fallback layout

**Comment by hius07** [comment]
The issue discussed is applicable for checked `Remember last layout` only.

I see the `Keyboard layouts` menu as a **settings** menu only - to set the globe key configuration (popup language buttons and cycle-switching).
Unchecked language cannot be activated via the globe key so it is not indicated in the menu.

**Comment by zwim** [comment]
>I see the Keyboard layouts menu as a settings menu only - to set the globe key configuration (popup language buttons and cycle-switching).

In this case it might be more consistant to drop the menu at all and include that selection in the Globe->Three-dots menu. Then we would have one place for layouts.

>Unchecked language cannot be activated via the globe key so it is not indicated in the menu.

They can be activated in Globe->Three dots. Then an unchecked language is activated and we don't see what language that is in the device menu.  In the device menu we see our up to four selections, but maybe none of them is active. That might confuse.
