### ISSUE TITLE
Menu "<Gear> -> Status Bar -> Settings -> Page2 -> Duration Format" is missing

### ISSUE THREAD

**Issue by cbckly** [koreader/koreader#8493]
* KOReader version: 2021.11 (updated from 2021.06 where menu was available)
* Device: Libra2 & Aura HD

#### Issue
Duration Format is not configurable anymore.  Status bars are displaying as 00:18, wasting all the space instead of 18'  

#### Steps to reproduce
Updated to latest, and my status bar changed to Classic or whatever.  Tried to fix it, but no menu option.

Saw #8008 but not sure how it relates.  Can't see anything about the menu itself getting removed.

**Comment by poire-z** [comment]
"Duration format" has been moved from the "status bar" menu to the `Gear > Device > Time and date >` as it was indeed applying to a few other things (durations in statistics...). That's #7897.
When doing that, we defaulted (unwillingly) to "modern", which didn't please many people - so #8008 made "classic" back the real default.

**Comment by cbckly** [comment]
Ah, thanks for the quick response.  I didn't have much look searching for Duration Format on the web or in Issues..  I've got it turned on now.
