### ISSUE TITLE
Chinese Large text File Partial (Encoding) Gibberish 

### ISSUE THREAD

**Issue by Inc0n** [koreader/koreader#8500]
* KOReader version: 2021.11
* Device: android R, api 30, sweet_eea

#### Issue

Encoding (?) error resulting in some section of text becoming gibeerish. A screen shot is attached, where the area of concern is circled in black.
<details>
  <summary>Screenshot</summary>

![Screenshot_2021-12-01-18-33-10-593_org koreader launcher fdroid](https://user-images.githubusercontent.com/33980911/144294273-8734cb12-372c-493b-8542-6e437e81819c.jpg)

</details>

#### Steps to reproduce

Use Koreader to open a large (?) chinese text (.txt) file (mine is ~10mb)

#### Details

The page that had this problem will always render this same way, when scrolling forward and back through the book.
The file itself is fine, I have viewed it on other ebook readers.
I used to use koreader on my kindle PW3, where it had this issue while reading some chinese text file as well.

**Comment by Inc0n** [comment]
I just discovered that, this issue is not exclusive to KOReader, it is present in most other ebook readers, the only reader that has not suffered from this problem, is ALReader, which allowed me to set the code page to "Simplified Chinese (936)" entry.

This leads to me thinking, that if KOReader can implement an option to change the encoding that will be cool.

**Comment by poire-z** [comment]
Plain text is a poor format we have nearly not worked on over the last few years - the popular formats are EPUB and FB2.
What you get is the original CoolReader support, which anyway is rather advanced.
It's supposed to detect the encoding (among a few it supports), and I guess it somehow succeed if most of your book renders OK.
It it fails for one or two paragraphs, it's possible that either:
- your document is a bit messed up in these parts, and some other readers are better at handling errors - like if there's 1 unexpected byte, they would skip it while we might try to make chinese codepoints from this one and the next, and then have all the next ones wrong and shifted - until end of paragraph were things get reset to a sane state
- there are small variations in the various historical chinese encodings, and crengine handles "gbk" and "cp936" the same, but a difference between them make it stumble and fall in the above situation.

https://en.wikipedia.org/wiki/Code_page_936_(Microsoft_Windows)

The code involved might be among:
https://github.com/koreader/crengine/blob/master/crengine/src/lvxml.cpp (search for "gbk", various conversion functions)
https://github.com/koreader/crengine/blob/master/crengine/src/crtxtenc.cpp
https://github.com/koreader/crengine/blob/master/crengine/src/cp_stats.cpp

There might be a bug in there, dunno.
But I would probably bet on your document being bad - so you might want to convert it with some (solid) tool to UTF-8 and call it a day :)

Adding an option does not feel that it would help as:
1) autodetection seems to work
2) if it detects "gbk", and "cp936" is different in some way, we don't have "cp936" support yet.
(And only somebody confortable with these chinese encodings could fix/add support for these variations.)

**Comment by Inc0n** [comment]
You are right about recoding this text file, but I recoded it in `gb18030`, I don't know enough about the encodings to know the differences between `cp936` and `gb18030`, but now I would think that adding support for `gb18030` would fix this minor issue.

It would be more convenient that koreader would take care of the encoding issue for me, that is. But of course I understand that I am asking maintainers to add support for perhaps a very small group of users.

Still, it is good to know now I could fix this gibberish by recoding.
