### ISSUE TITLE
FR: Solarized Dark and Light for Linux Laptop and Android

### ISSUE THREAD

**Issue by lamyergeier** [koreader/koreader#8503]
**Describe the solution you'd like**
I use Koreader on my Ubuntu 20.04 Laptop. Can you please add low contrast Solarized Dark and Light themes?

**Comment by NiLuJe** [comment]
That would imply having theme support to begin with ;o).

**Comment by Frenzie** [comment]
Did you try night mode?

**Comment by anishmittal2020** [comment]
@Frenzie Yes, that's very high contrast. I would mainly  like to use Solarized light theme.

**Comment by pazos** [comment]
Duplicate of #3871
