### ISSUE TITLE
FR: Better support for self-made ToC

### ISSUE THREAD

**Issue by mrdk** [koreader/koreader#8512]
I read a lot of PDF files that have no built-in table of content — often they are scanned text with an OCR layer. Many scientific papers are in that form. For them, I can generate a simple ToC by highlighting some or all section and chapter titles and navigate via the bookmarks menu. This works quite well, especially since now the bookmarks are in the right order. But it could be better.

I think of the following improvements:

-  A menu item with which one can move a bookmark or highlighted text to the ToC, where it appears as a chapter title. By default, the text in the ToC should be the highlighted text, but it needs to be editable because OCR sometimes fails.
- As an addition, I would like to see  a possibility to modify the indention level of a ToC entry, to display sections and subsections correctly. This modification would also be useful on its own, since there are a number of ebooks around with errors in the sectioning.

**Comment by Frenzie** [comment]
I think the proposed addition worked on in https://github.com/koreader/koreader/issues/8426#issuecomment-983860643 is doing something very similar.

**Comment by poire-z** [comment]
Not really, #8426 won't automatically make a TOC, and won't really help much if you make bookmarks or highlights to make chapters - actually, #8426 will make the absence of a TOC even more bothering:
![image](https://user-images.githubusercontent.com/24273478/144720828-4a143044-c0fb-4129-a6c9-ee7ef038de99.png)

But I also don't think we should bother having TOC creation/edition in the app - it would be a lot of work, and hard to avoid conflict and mess when there is already a TOC.
(With EPUBs without TOC or a bad TOC, we can override it with some style tweaks by targetting elements and putting their level via CSS, which is obviously not available with PDFs.)

I remember when I used to make photographs of library books pages, and I had a lots of .tiff files, that I was able to build a PDF (either with Acrobat or with some python script), I used to make TOC (and page mapping) via plain text files like:
```
2:III Sommaire
4:VII Avant-propos
5:IX Introduction
8:XIV L'alphabet
11:1 1 Première leçon
12:3 2 Deuxième leçon
13:5
14:7 3 Salut!
15:9
16:11 4 B-A, BA
17:13
18:15 5 Ulysse
```
and I could use that with Javascript in Acrobar or via the python script to make a TOC inside the PDF.
But not everybody can afford Acrobat...

I also think it's easier to work on making such a plain text TOC for a PDF on a computer than having to do it in KOReader. So may be we could load a file of a format to be defined if alongside a `foobar.pdf`, we meet a `foobar.toc` - and use this as the TOC.

**Comment by poire-z** [comment]
Or use some existing free software that allows adding/editing a TOC in a PDF. Some links inside:
https://ebooks.stackexchange.com/questions/107/how-to-create-clickable-table-of-contents-in-a-pdf

**Comment by Frenzie** [comment]
> #8426 will make the absence of a TOC even more bothering:

Well, I tried it in a 300 page EPUB with no TOC (well, technically it has a TOC but it basically just sas Intro p. 1 and Start p. 3) and I thought the way the bookmarks were laid out was more TOC-like than the regular bookmarks overview. :-)

**Comment by poire-z** [comment]
Some discussion about this FR around https://github.com/koreader/koreader/issues/10193#issuecomment-1685376756
