### ISSUE TITLE
How to Actually Import E-books?

### ISSUE THREAD

**Issue by faxotherapy** [koreader/koreader#8516]
Hi, new to e-book reader.

The section “How can I transfer books, articles to my device ?” does not explain how to actually import e-book. Is there a specific folder in KOReader directory to put e-book in there? Or, should I just created an “e-books” folder in my “Home” directory and ask KOReader to read inside this folder to fetch the e-books. In short, what is the clever way to let KOReader manages/read e-books? Thanks for your help.

**Comment by Frenzie** [comment]
> Is there a specific folder in KOReader directory to put e-book in there? 

No, unless you want to.

> Or, should I just created an “e-books” folder in my “Home” directory and ask KOReader to read inside this folder to fetch the e-books.

Yes, unless you don't want to.
