### ISSUE TITLE
FR: bulk delete/copy/cut files

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8524]
It takes a lot of time if someone wants to delete, copy or move many files from one folder to another.
Is a bulk delete/copy/cut option possible, as has been done for bookmarks?

Thank you!

**Comment by poire-z** [comment]
Cross ref: https://github.com/koreader/koreader/discussions/8405 (and probably others :)

**Comment by ichnilatis-gr** [comment]
I'm sorry. So, please ignore this issue.
But, it would be very useful, since it's not possible to see the subfolders (like screenshots etc.) of koreader folder through my ereader UI and do these actions.
