### ISSUE TITLE
FR: Allow turning off highlighting entirely. In a document, and by default.

### ISSUE THREAD

**Issue by autumnyard** [koreader/koreader#8533]
Up until the November update there was an option to turn off highlightning entirely, by document. If I recall correctly, it was on this last November update that the option disappeared, in favour of a "Highlight style" panel with Lighten, Underline, etc. 

I've been trying to look for the commit where the option was removed, but I couldn't find it. Perhaps d652eec2cd2d2bb9f39a482e7c1af5e80bda580a?

Solutions:
- Another option in the "Highlight Style" panel to "Turn off" the highlight mode entirely, as there was before.
- Also, there could be a new option in the File Manager menu to set a default option for highlighting in all books. For the users who aren't gonna use hightlighting at all.

**Additional context**
I like to read moving my thumb below the line. Yeah, it's true.

**Comment by hius07** [comment]
Look at the Gear - Taps and gestures - Long-press on text.

**Comment by autumnyard** [comment]
That solves the first point only in part, because you will still highlight if you long-press and drag. Isn't it possible to disable highlighting completely, as was possible before?

I see that this setting is also shared by all books, so that solves the second point.

In any case, thank you very much!

**Comment by Frenzie** [comment]
That sounds like it's probably a bug, but I don't know otoh who put that menu into place. @poire-z maybe?

**Comment by poire-z** [comment]
It was reworked in #8199.
May be a small oversight: no highligh onHold, but it still highlits once we onHoldPan.
May be this just ought to be duplicated in onHoldPan ?
https://github.com/koreader/koreader/pull/8199/files#diff-db51db4b48e0314c642050876de6cd601d148eaaa00d4511523f811531d63ccfR837
