### ISSUE TITLE
Font weight scale different in gestures

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#8534]
* KOReader version: 2021.11
* Device: all

#### Issue
You can only set font weight per 1; should be per 0.25 just like in the bottom dialog.

Cf. https://www.mobileread.com/forums/showthread.php?t=343521

**Comment by hius07** [comment]
The same reason as https://github.com/koreader/koreader/pull/8344.

**Comment by Frenzie** [comment]
Same for contrast it says there btw. (I didn't want to muddle this issue, but if it's that simple. ;-) )
