### ISSUE TITLE
FR: Export of highlights and notes & paragraph display

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8535]
When exporting highlights, if a highlight has a note, only the note is exported. If the note is just a correction to the original highlighted text, that's fine, but if the note is a comment on the highlighting text, that makes no sense.
![Bookmarks_1_1](https://user-images.githubusercontent.com/76203123/145235040-af057790-d339-4370-b409-e2a5acdce824.jpg)

![Bookmarks_1_2](https://user-images.githubusercontent.com/76203123/145235069-11cf9d71-5f2f-4624-9c5c-5bfe66dc96e7.jpg)

It would be useful to be able to export the notes along with the original highlighted text, as in the image below (it is edited in photoshop).

![Bookmarks_1_3](https://user-images.githubusercontent.com/76203123/145236491-54992952-eb7b-49ae-b4f5-6a1734351e06.jpg)

(I mention in passing that, when I changed the language to English, all the bookmarks were displayed as notes)

![Reader_192121](https://user-images.githubusercontent.com/76203123/145238195-808482c2-deab-48ad-a1b7-7c178383b309.png)

**Comment by Galunid** [comment]
Most likely you'll have to wait for https://github.com/koreader/koreader/issues/5794, and only then will this make sense. Bookmarks/highlights/notes need rework, any "fixes" now don't make much sense and it's not a trivial change, since we store highlight and note text together iirc

**Comment by hius07** [comment]
> when I changed the language to English, all the bookmarks were displayed as notes

Yes, that's because of inserted page numbers in language other than the current one.
It can't be fixed with current system of annotations.

Exporting both highlighted text and note can be done currently, requires changes to the Exporter plugin.

**Comment by hius07** [comment]
I've made changes to the Exporter plugin, to show highlighted text together with a note.
(Star instead of the pencil, because the pencil sign may be absent in a user font)

Example  (the second fragment is a highlighted text without a note)

Before

![1](https://user-images.githubusercontent.com/62179190/145670963-3ff70296-aef7-4d8a-b570-93284dca0a2a.jpg)

After

![2](https://user-images.githubusercontent.com/62179190/145670966-1d218c6d-ec47-40ea-a7cb-aca62cf01c1a.jpg)

The question: will all the users be happy with this change?
Should it be a setting like `Show highlighted text with a note`?

**Comment by poire-z** [comment]
> will all the users be happy with this change?

I guess so: if you export, no reason to not put in there all info.
May be you could make it a bit nicer and clearer: HTML allows to be a bit more fancy that KOReader's own text widgets :)
You could have the user note on a new block below, with some indentation (and background color, but it usually makes it less readable).
```
| 12/02/21
Blah blah blah blah blah blah blah blah blah the original
text blah blah blah blah blah blah.
    My note is indented as a comment about this text
    above, which should make it obvious it's something
    else.
```

(Btw, do you always have the original text in the bookmark? I remember some fields goes blank, is it just the user added note ? You can export from books that are not opened ? All is there in the bookmarks/highlights, no need to query the document ?)

**Comment by hius07** [comment]
Frankly, I do not use export, so not very interested in digging into the template.
And the plugin itself requires more changes, at a quick glance.

It is just a small addition to `parseHighlight`, for bookmarks
https://github.com/koreader/koreader/blob/5ed22cafb5f18aa5a9200a77387669198dd39f78/plugins/exporter.koplugin/clip.lua#L240-L243

**Comment by ichnilatis-gr** [comment]
> I've made changes to the Exporter plugin, to show highlighted text together with a note.
> (Star instead of the pencil, because the pencil sign may be absent in a user font)

I think it would be better if the note was in another paragraph. (the symbol doesn't matter)

By the way, I would like to mention another issue too. If the highlighted text extends in different paragraphs or the note has paragraphs, they are not displayed in the bookmark list and in the exported file.

![Reader_1_1 (Medium)](https://user-images.githubusercontent.com/76203123/145672444-87d6556a-2029-468e-aecf-ea2316fa1be3.png)

![Notes_1_1 (Medium)](https://user-images.githubusercontent.com/76203123/145672450-a0f6c940-e30a-4bd3-83ef-0e326e74c807.png)

![Notes_1_ 2 (Medium)](https://user-images.githubusercontent.com/76203123/145672452-a35a5a61-c123-4ba6-8d87-ee9b98faa7c8.png)

![Notes_1_3 (Medium)](https://user-images.githubusercontent.com/76203123/145672457-6e42b1ef-5f2b-4e50-b1a0-5cfec177375c.jpg)

**Comment by hius07** [comment]
> If the highlighted text extends in different paragraphs or the note has paragraphs, they are not displayed in the bookmark list

@poire-z would explain better why we can't avoid this
https://github.com/koreader/koreader/blob/5ed22cafb5f18aa5a9200a77387669198dd39f78/frontend/ui/widget/menu.lua#L262-L266

**Comment by poire-z** [comment]
Well, the bookmark list (being from our Menu widget), is probably not where you want to read your highlights :)
OK, you allow it to go small and display 5 lines, but you most probably get some truncated. Showing real newlines would just make the truncation happen quicker.

Not doing this `\n` substitution could be made an option of Menu (when we know it will use a TextBoxWidget). I don't think it should be a setting in the Bookmark menu though.

You could also try replacing this `\n` with some Unicode symbol for newline, ir https://www.compart.com/en/unicode/U+23CE - dunno how it would look, but may be it jumps enough to our eyes so our brain gets its multiple paragraphs ?

**Comment by hius07** [comment]
Thanks to the authors of the plugin, they've made a good template! Is this fine?

![4](https://user-images.githubusercontent.com/62179190/145683361-4a6fd4a9-b1dc-4149-8037-1faaacd4b82a.jpg)

**Comment by poire-z** [comment]
The (untranslatable?) `Note:` might be an issue, and add a bit of noise - when the color or indentation can be enough to indicate it's something other than the book text.
But it seems it's already there - is it `#{= htmlescape(notemarks)`) ?

You could also try adding to the `<div style="font-size:11pt; margin-top:0.2em;">` `margin-left: 2em` or `1em` and/or `background-color: #eeeeee`:
`<div style="font-size:11pt; margin-top:0.2em; margin-left: 2em">`

**Comment by hius07** [comment]
> The (untranslatable?) `Note:`

https://github.com/koreader/koreader/blob/5ed22cafb5f18aa5a9200a77387669198dd39f78/plugins/exporter.koplugin/main.lua#L36

**Comment by hius07** [comment]
![5](https://user-images.githubusercontent.com/62179190/145684709-7aab4a0f-da2a-435b-a714-85b387db3a9f.jpg)

![6](https://user-images.githubusercontent.com/62179190/145684710-d4b712eb-57e2-42fb-9ea5-761a72cb260b.jpg)

**Comment by hius07** [comment]
The plugin doesn't parse the note line by line, so no new lines.

**Comment by poire-z** [comment]
(Tell us which you prefer ! :)
I'm not a user of this, so my opinion won't matter - but I think I would prefer some possibly even larger margin-left, no "Note:", text in gray as it is, no background-color. May be some italic instead of the gray (not fond of gray in HTML content, it might make it harder to read, particularly if it's printed on a bad printer).
Pinging the customer @ichnilatis-gr :)

**Comment by poire-z** [comment]
> The plugin doesn't parse the note line by line, so no new lines.

You could always do a `html = text:gsub("\n", "<br/>") ` before giving it to the template (unless the template  replace sthe < and > with `&lt;` and `&gt;` - in which case it's more complicated, but may be the template system has some solution for that.
Or may be juste add to the style= `white-space:pre-line` , https://developer.mozilla.org/en-US/docs/Web/CSS/white-space , and let the browsers display the newlines.

**Comment by hius07** [comment]
> (Tell us which you prefer ! :)

I do not use it, so hoped to just add my lovely `isBookmarkAutoText`, without looking into the design.

**Comment by ichnilatis-gr** [comment]
> Well, the bookmark list (being from our Menu widget), is probably not where you want to read your highlights :)

Yes, I agree.

**Comment by ichnilatis-gr** [comment]
> Pinging the customer @ichnilatis-gr :)

The note could be in grey letters (since it is good to avoid a grey background) and indented.

**Comment by hius07** [comment]
> The note could be in grey letters (since it is good to avoid a grey background) and indented.

With or without **Note:** at the beginning?

**Comment by ichnilatis-gr** [comment]
> With or without **Note:** at the beginning?

I think it's better without. Otherwise, we'll have to translate the word "note" :-).

**Comment by ichnilatis-gr** [comment]
And to make things worse (This guy is a real nuisance!):
What if a note is just an addition to the highlighted text or a correction? Then the highlighted text will be exported almost twice (in two versions: without an d with the addition/correction).
Therefore, consider the possibility of two options instead of the "add note" option: "edit highlight" (only the highlight will be exported) and "add note" (both the highlight and the note will be exported).

Grateful to you!

**Comment by hius07** [comment]
_I'd like to open the exported highlights html in the default reader of my Boox device (to make handwritten notes), but its engine seems to be very picky. Would it be possible to add html and body tags to the template?_
https://www.mobileread.com/forums/showpost.php?p=4180826&postcount=12

**Comment by Frenzie** [comment]
@hius07 The issue there was already fixed in https://github.com/koreader/koreader/pull/8040?

**Comment by poire-z** [comment]
`<!DOCTYPE html>` might be fine with current mainstream web browsers, but old embedded readers might stumble on this (even crengine didn't accept it, we fixed this 1 or 2 years ago only).

**Comment by hius07** [comment]
I don't know what "default reader of my Boox device" requires, maybe just add
`<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">` and `<body>`
to the template?

**Comment by poire-z** [comment]
Also, I don't know if there's a feature of "export all from all books", where these snippets could be concatenated into a single HTML - in which case having HTML/BODY might be problematic.

**Comment by hius07** [comment]
> "export all from all books"

Separate html file for each book.

**Comment by Frenzie** [comment]
@hius07 I'd skip specifying the language but sure, sounds good.

**Comment by ichnilatis-gr** [comment]
Let me give you some screenshots from the Pocketbook e-reader on how the highlights look as well as adding notes, just for ideas... Notice that there are separate options for editing the highlights ("quotes") and notes.

![scr0001 (Medium)](https://user-images.githubusercontent.com/76203123/147119208-d4cffea5-549f-461e-b049-f12cc696fe93.jpg)

![scr0004 (Medium)](https://user-images.githubusercontent.com/76203123/147119207-442b94d5-d5ea-4c05-a0b9-65b151138a22.jpg)

![scr0005 (Medium)](https://user-images.githubusercontent.com/76203123/147119217-821c6d6d-775d-44ca-90a1-a57757fbeb07.jpg)

![scr0006 (Medium)](https://user-images.githubusercontent.com/76203123/147119276-258f855a-46df-4217-aa26-32180a6ec654.jpg)

![scr0007 (Medium)](https://user-images.githubusercontent.com/76203123/147119299-65fcd1e7-bd7d-4062-805c-d04c329891f3.jpg)

![scr0008 (Medium)](https://user-images.githubusercontent.com/76203123/147119320-f7f13351-4010-4257-a2bb-8cbb6efc3d8f.jpg)

![scr0002 (Medium)](https://user-images.githubusercontent.com/76203123/147119338-66b5c975-7598-4b27-8530-c952398e075a.jpg)
