### ISSUE TITLE
Koreader Crashes after tapping on brightness option

### ISSUE THREAD

**Issue by fadedshewrote** [koreader/koreader#8542]
* KOReader version: latest stable november
* Device: Kobo aura one 8GB

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>

[crash.log](https://github.com/koreader/koreader/files/7692429/crash.log)



</details>

**Comment by Frenzie** [comment]
```
./luajit: frontend/util.lua:562: attempt to index local 'text' (a number value)
stack traceback:
	frontend/util.lua:562: in function 'splitToChars'
	frontend/ui/widget/textboxwidget.lua:219: in function '_evalCharWidthList'
	frontend/ui/widget/textboxwidget.lua:155: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/ui/widget/frontlightwidget.lua:185: in function 'setProgress'
	frontend/ui/widget/frontlightwidget.lua:121: in function 'generateProgressGroup'
	frontend/ui/widget/frontlightwidget.lua:434: in function 'update'
	frontend/ui/widget/frontlightwidget.lua:114: in function 'init'
	frontend/ui/widget/widget.lua:48: in function 'new'
	frontend/device/generic/device.lua:359: in function 'showLightDialog'
	frontend/device/devicelistener.lua:217: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1119: in function 'sendEvent'
	frontend/ui/uimanager.lua:227: in function '__default__'
	frontend/ui/uimanager.lua:1603: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1683: in function 'handleInput'
	frontend/ui/uimanager.lua:1730: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00014119
!!!!
Uh oh, something went awry... (Crash n°1: 12/10/21 @ 17:02:53)
Running FW 4.30.18838 on Linux 3.0.35+ (#5031 PREEMPT Tue Mar 30 14:26:27 CST 2021)
Aborting . . .
!!!! ! !!!!
```

**Comment by poire-z** [comment]
Thanks for the report.
But this crash happens only when you have some KOReader old codepath running, when you have disabled our enhanced support for text.
Go to file browser, `Tools > More tools > Developper options >` , and uncheck `Disable enhanced UI text shaping (xtext)`.
Any specific reason for you to have it disabled ?

We should anyway try to fix this crash - strange that it happens only in that specific frontlight dialog and not way earlier :)

**Comment by poire-z** [comment]
OK, just a matter of doing what we do in the other code path :)
https://github.com/koreader/koreader/blob/3deac02b7164279463ebb0c218b422d5b68a7409/frontend/ui/widget/textboxwidget.lua#L241-L247
so:
```diff
--- a/frontend/ui/widget/textboxwidget.lua
+++ b/frontend/ui/widget/textboxwidget.lua
@@ -216,6 +216,11 @@ end
 function TextBoxWidget:_evalCharWidthList()
     -- if self.charlist is provided, use it directly
     if self.charlist == nil then
+        if not self.text then
+            self.text = ""
+        elseif type(self.text) ~= "string" then
+            self.text = tostring(self.text)
+        end
         self.charlist = util.splitToChars(self.text)
     end
     -- get width of each distinct char
```
