### ISSUE TITLE
FR: [Sort books by number of pages]

### ISSUE THREAD

**Issue by fadedshewrote** [koreader/koreader#8543]
**Does your feature request involve difficulty completing a task? Please describe.**
A feature that sorts books by number of pages because i want to finish books that are less in length first.

**Describe the solution you'd like**
A feature that sorts books by number of pages. 

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by poire-z** [comment]
Cross ref #8390
