### ISSUE TITLE
FR: support Readium LCP open source DRM system

### ISSUE THREAD

**Issue by mfortini** [koreader/koreader#8544]
[Readium LCP](https://www.edrlab.org/readium-lcp/) is an open source DRM system which is being adopted in [many public library systems](https://www.edrlab.org/readium-lcp/certified-apps-servers/).

Kobo is not supporting the system out of the box. I was wondering if koreader could help in this sense.

There is an [open source SDK](https://github.com/readium/readium-lcp-client) to integrate the system.

**Comment by Leseratte10** [comment]
Note that the "open source" SDK is not completely open-source. You can access the code, and you can build your own apps that can open the example / test books, but all public books encrypted with that DRM (like in public libraries) use a different encryption that's not available in the open source version and is only provided in obfuscated form to licensed developers, so this public SDK is useless in trying to get KOreader to render LCP-encrypted eBooks.

**Comment by Frenzie** [comment]
Quick search result about that: https://www.edrlab.org/readium-lcp/how-to-lcp-reading-system-provider/

**Comment by poire-z** [comment]
As it would be about filling forms, signing papers, certificates, pre-compiled stuff, and asking "EDRLab to certify the solution" - and that we sucks at filling forms :), closing.

**Comment by moongazer07** [comment]
> As it would be about filling forms, signing papers, certificates, pre-compiled stuff, and asking "EDRLab to certify the solution" - and that we suck at filling forms :), closing.

you just need the lcp.node file from thorium
