### ISSUE TITLE
Menu widget header redesign

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8549]
The reasons to think about this redesign are:
-incosistency with the file manager header
-the only way to call an action in the menu widget is a long-press on an item

Proposed changes:
-close button is an icon, smaller title font and top padding
-optional actions button at the left

File manager (no changes, to compare), proposed and current menu widget:

![04](https://user-images.githubusercontent.com/62179190/145707634-9c9663e9-850d-48ec-8cf4-a5636c575598.png)

![05](https://user-images.githubusercontent.com/62179190/145707635-477928fa-e39a-4a3c-8e93-767ee535067a.png)

![06](https://user-images.githubusercontent.com/62179190/145707636-c7a7fd16-db09-49bd-bf4a-b61e8804e89d.png)

**Comment by poire-z** [comment]
Good idea.
May be try to make it a FullScreenTopTitleBar widget, so we can re-use it in other non-Menu widgets (ie KeyValuePage, or the one I'm working on in the screenshot below), it's always the most boring stuff to work on when making new full screen stuff.
![image](https://user-images.githubusercontent.com/24273478/145708338-30a11c55-5286-4f90-8da2-c851388f40ed.png)

A minor thing that matters to me :) try to make the Close symbol cross align with the top right corner of screen:
![image](https://user-images.githubusercontent.com/24273478/145708468-cb19d90e-378a-415d-b688-260918bea9f2.png)

**Comment by hius07** [comment]
Fixed.

![07](https://user-images.githubusercontent.com/62179190/145815269-bee9800f-cf5e-4016-9245-580bc94f66a1.png)

I am afraid it would be hard to migrate to a separate TitleBarWidget, cannot imagine how to make the migration step by step.
I would be happy to change the close button in the Menu and KVP widgets, and add an extra (left) button to the Menu widget (disabled and not shown by default), so no changes to other modules would be needed (unless a module is going to use the new extra button, Bookmark list is the first candidate).

**Comment by poire-z** [comment]
Mhhh, do we need such a large cross/close button ? On your screenshot, it feels so huge :/ May be it's an optical illusion with not seeing the whole screen, dunno.
And your hamburger icon feels quite near the first menu item.

I guess I wouldn't mind having them smaller: we should kwow they are there, but they may be shouldn't jump that much to the eyes. They could have a larger tap area than the icon itself. They don't need to have the same size as in the touchmenu top icon row.

> I am afraid it would be hard to migrate to a separate TitleBarWidget, cannot imagine how to make the migration step by step.

Well, it's just a matter of creating the widget for at least one candidate user (the File browser/Menu one might be tricky, with its path as subtitle, so it might no be the best first candidate - or may be it is as the most complex) - and step by step substitute it in other widgets.
(Are you still testing solely on your Kindle ? No emulator yet ? :)

**Comment by Frenzie** [comment]
I agree, it should be a bit smaller with sufficient padding.

**Comment by hius07** [comment]
> do we need such a large cross/close button ?

I'll give more screenshots soonest.
That is the same size as home/plus icons in the FM. And the same font size of the title.
Should they be equal?



> creating the widget for at least one candidate user

Most of the candidates use Menu or KPV, so I've started from the Menu and realized it was hard to insert a separate TitleBarWidget into the Menu widget.

**Comment by hius07** [comment]
Also replying to https://github.com/koreader/koreader/pull/8536#discussion_r767769472.

![11](https://user-images.githubusercontent.com/62179190/145830867-ef8e9474-9a86-41e8-b7cf-291c4d5bb74b.png)

![12](https://user-images.githubusercontent.com/62179190/145830876-0177ded3-1ff3-4739-8a40-a856731f032f.png)

![13](https://user-images.githubusercontent.com/62179190/145830888-d9ec7dca-79ed-4d93-995d-958bbf59baa5.png)

Home button in FM looks aligned with the left margin of file names.

**Comment by poire-z** [comment]
> That is the same size as home/plus icons in the FM. And the same font size of the title.
Should they be equal?

In the current file browser, there is some large padding at bottom (for the path/subtitle), so them being larger is fine.
So, it depends on how much of that bottom padding you want to kill (which looks like one of your goal - and I would also like to not waste vertical space in my own widget).
If you don't have much bottom padding below the title, I guess you should reduce the icon size so this compensates and adds some blank space below the icon. This could be computed, or you could just try with a scale ratio that just works :)
So, I don't think they have to be equal - as long as we don't see a mix of the same icon sized differently simultaneously.

> Most of the candidates use Menu or KPV, so I've started from the Menu and realized it was hard to insert a separate TitleBarWidget into the Menu widget.

Yes, it's complex, and would need some bit of refactoring to the Menu widget.
So, I guess it's best in the meantime to change as little as possible (don't attack KVPage yet with adding to it a left icon that we don't need yet).
For the futur, I guess we should have something that work like:
```lua
local title_bar = TitleBarWidget:new{
 title = "Something"
 title_align = "center"
 title_multilines = false
 subtitle = path
 with_bottom_border = false,
 left_icon = "home" -- or nil if no need
 left_text = "+" -- if we prefer some text symbol
 left_callback = function() self:goHome() end
 right_icon = "plus",
 right_callback = function() self:tapPlus() end
}
```
with some `:setLeftIcon()` methods.
We could use that in many modules and remove a lot of code and replace it with just: `title_bar_height = title_bar:getSize().h` .
(I can anticipate the pleasure we'll have removing all that code :)

> Home button in FM looks aligned with the left margin of file names. Or maybe shift to the left a little bit?

As you feel looks right (for the Home icon, depends if what should align is the left wall of the house, or the edge of the roof :)
But there's a bit of optical illusion: your hamburger icons feels like it's too shifted right, that the notes icons goes to the left of it. But looking precisely with a ruler, they aligne properly :/
It would just look odd in the code to not have the left and right icons padding unbalanced.

**Comment by poire-z** [comment]
![image](https://user-images.githubusercontent.com/24273478/145833209-f79caf6c-84f3-4738-9de3-ce7e0dac78f7.png)

This looks OK because your first bookmark is small and centered in its area - so you have some top padding that makes this OK. You should try with a huge first bookmark so it's multilines and takes the whole item height.

**Comment by hius07** [comment]
> So, I don't think they have to be equal

That's the point that breaks my idea.
I'll make some variants with reduced close_button icon.

**Comment by poire-z** [comment]
> That's the point that breaks my idea.

Is that a good, or a bad thing ? :/
Also, I don't know where this cross comes from. Is it text or a SVG icon? If it's an icon, you have the right to make it smaller in its SVG area, it might be an icon designer choice to not have the cross "legs/arms" span up to the borders, to make its optical/subjective weight similar to other icons.

**Comment by hius07** [comment]
It's our "exit" icon and it's not a problem to reduce it in the IconButton.
So, returning to the current close_button. (I just tried to unify the title bars in FM and other windows).

**Comment by poire-z** [comment]
Yes, looks better :)

You might see if it's possible for the tap zone to extend beyond the icon itself, and may be even over the stuff below (as it's sometimes, for some people or on some devices) to hit exactly in the corner):
![image](https://user-images.githubusercontent.com/24273478/145862521-cce1555a-e45b-446c-b624-42ba7429767b.png)
(I believe the corner tap zones are handled by the gestures/dispatcher stuff, so they are not really linked to the icon/button itself - if that's the case, forget my comment :)

**Comment by hius07** [comment]
Menu widget header is ready.
Header buttons tap zones are widened (do not extend them down, as there is a menu item there).

Close button only:

![01](https://user-images.githubusercontent.com/62179190/146187521-8583f2aa-285a-400e-a5d3-df139df08b97.png)

![02](https://user-images.githubusercontent.com/62179190/146187525-3f5f6b8f-a4a7-4b0c-846d-f900926cfff8.png)

![03](https://user-images.githubusercontent.com/62179190/146187528-dd4a5a05-61b2-4437-812a-9bb2a03bc6e8.png)

Close and extra (left, changeable) buttons

![04](https://user-images.githubusercontent.com/62179190/146187581-8a906f9f-7bc6-4dc2-a326-cc30a684de7a.png)

Select mode

![05](https://user-images.githubusercontent.com/62179190/146187583-344c410a-cb6a-446c-ad3e-2e9a1fdd9013.png)

KVP will get the new close button only, screenshots will follow.

**Comment by hius07** [comment]
Non-fullscreen menu widget with new close button

![06](https://user-images.githubusercontent.com/62179190/146374470-2bd9b816-2f23-4ac7-969b-b56eecfd476b.png)

**Comment by hius07** [comment]
Closed with https://github.com/koreader/koreader/pull/8564.

**Comment by poire-z** [comment]
> Yes, looks better :)
> 
> You might see if it's possible for the tap zone to extend beyond the icon itself, and may be even over the stuff below (as it's sometimes, for some people or on some devices) to hit exactly in the corner): ![image](https://user-images.githubusercontent.com/24273478/145862521-cce1555a-e45b-446c-b624-42ba7429767b.png) (I believe the corner tap zones are handled by the gestures/dispatcher stuff, so they are not really linked to the icon/button itself - if that's the case, forget my comment :)

> Header buttons tap zones are widened (do not extend them down, as there is a menu item there).

Had a look at #8564 only this morning, so some comments:

I'm not really a close button user, but it feels my success rate at hitting it has decreased :/ The fact that the tap zone does not extend down might be the reason. Also, often (noticable in History Cover view), there is a dead zone between the close button and the menu content, where nothing happens. I think I wouldn't mind if it extends down, even OVER the menu item there; we can always tap on that menu item in the middle instead of its left or right edge once we know this might trigger the title left and right buttons.

The reduced padding below the title, plus the now larger cross, makes it a little more odd/ugly. I might get used to it :) the space gained by the reduced padding gives more room to the more valuable content below, which is good.

The inconsistency between the 2 types (small x text vs. larger icon) of cross/close buttons is quite noticable. Any plan on this?

**Comment by hius07** [comment]
> it extends down, even OVER the menu item

We can set `padding_bottom = icon_size` for left and close buttons, so the tap zone would be a square with 2*icon_size side.
This does not increase the gap between the title and the first item.

> The inconsistency between the 2 types (small x text vs. larger icon) of cross/close buttons is quite noticable.

Do you mean changing text to icon in the CloseButtonWidget?

![01](https://user-images.githubusercontent.com/62179190/147823756-701a0ea5-d97d-46b6-9854-bb3ce0abe351.png)

![02](https://user-images.githubusercontent.com/62179190/147824123-d7c48b09-3f2f-4fb8-8cce-143ee8322fb3.png)

![03](https://user-images.githubusercontent.com/62179190/147824129-99a167d4-87fb-4552-9ac7-7ef06132b6ab.png)

**Comment by poire-z** [comment]
> We can set padding_bottom = icon_size for left and close buttons, so the tap zone would be a square with 2*icon_size side.
This does not increase the gap between the title and the first item.

Yes, I think this would be better.
(I guess that works because it's an OverlapGroup with a fixed height.)

> Do you mean changing text to icon in the CloseButton widget?

Yes, I guess so.
(I'm not fond of this big `X`, but I'll get used to it :) and consistency matters more :) Or if you can make it smaller when not full screen window.
Dunno if you can just hack the Closebutton - or if it better waits for a generic TitleBarWidget...

**Comment by hius07** [comment]
We can make them smaller everywhere. Is it nice (0.6)?

![04](https://user-images.githubusercontent.com/62179190/147825130-cc085abd-52b3-4a8b-927c-ad12bab2792a.png)

**Comment by poire-z** [comment]
That looks nice to me too - if you're ok with the checkmark and hamburger being that small.
It might also reduce the feeling I had: _The reduced padding below the title, plus the now larger cross, makes it a little more odd/ugly._ 

(Not bothered by the strange effect that the title and the icons don't have the same "baseline" ? There's a kind of `^\_title_/^` wave effect :)

**Comment by hius07** [comment]
Without padding above the title

![06](https://user-images.githubusercontent.com/62179190/147825859-821d1970-cc39-4077-bbc8-b66028a8959e.png)

**Comment by poire-z** [comment]
> Without padding above the title

Yep, looks better (dunno how constraint this would look on a device, with everything that pushed towards the screep top).
