### ISSUE TITLE
ed2519 keys support for SSH

### ISSUE THREAD

**Issue by matejdro** [koreader/koreader#8550]
* KOReader version: 2021.11
* Device: Kobo Glo HD (kobo_alyssum)

#### Issue

Koreader's SSH server does not appear to support ed2519 keys.

[RSA keys were disabled in OpenSSH 8.8](https://dev.to/cloudx/why-openssh-8-8-cannot-find-a-host-key-type-if-ssh-rsa-is-provided-49i) so it is a bit of a chore at the moment to connect to the koreader devices. It would be nice if native support for newer non-blacklisted keys was added.

**Comment by NiLuJe** [comment]
Use a native, up to date & supported alterantive instead (e.g., [KoboStuff](https://www.mobileread.com/forums/showthread.php?t=254214)).

**Comment by matejdro** [comment]
Thanks, I installed KoboStuff, but koreader seems to still use dropbear server when I enable it in the menu. Does that mean that I cannot launch the native sshd server from koreader?

**Comment by NiLuJe** [comment]
Yeah, KoboStuff's SSHD is hogging the default port, you no longer need to use the KOReader plugin *at all*.

**Comment by matejdro** [comment]
Thanks. Closing the issue then.
