### ISSUE TITLE
ButtonDialogTitle title

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8552]
Default ButtonDialogTitle title font style is bold. It may look not good because of:
-too much of boldness
-hard to distinguish title and buttons

![01](https://user-images.githubusercontent.com/62179190/145988189-8f66690b-ee6f-42d0-beae-544c0a2f10f7.png)

There are three types of headers:
(1) pure path/filename
(2) text + path/filename
(3) pure text
Please see below a couple of examples of each type (with one or two buttons in a row).

![04](https://user-images.githubusercontent.com/62179190/145988515-86a55e0e-c031-4deb-81d4-81c10d267667.png)

![05](https://user-images.githubusercontent.com/62179190/145988517-f5ac43ec-17cf-4a41-bcff-401c8d7c7c7d.png)

![06](https://user-images.githubusercontent.com/62179190/145988520-a78f4c75-693b-470a-b5c2-d00b45502f31.png)

![07](https://user-images.githubusercontent.com/62179190/145988523-52d19b62-cecc-4927-86c8-0e8685e9e515.png)

![08](https://user-images.githubusercontent.com/62179190/145988524-eba7b6e0-9476-4752-b941-487873e8cda1.png)

![09](https://user-images.githubusercontent.com/62179190/145988525-d8b8c3ec-8298-4566-b7ad-aafc2c3dcb24.png)

I tend to make the bold style off by default, maybe except of some special cases.
It will look like:

![10](https://user-images.githubusercontent.com/62179190/145988907-fef6382f-da5d-4f7a-ac18-287061d753ea.png)

![11](https://user-images.githubusercontent.com/62179190/145988912-65407600-a9a4-45b0-8b1c-1d9e97ea7506.png)

![12](https://user-images.githubusercontent.com/62179190/145988913-1272b5a8-db79-4adb-8265-56d577c8e45d.png)

Currently there are about a dozen of ButtonDialogTitle's shown and some unification is desirable.
More opinions: https://github.com/koreader/koreader/pull/7767#issuecomment-850353248, https://github.com/koreader/koreader/pull/8536#discussion_r766007491

**Comment by poire-z** [comment]
Well, in all of your screenshots, the "title" feels more like a message than a real window title ; even the book filenames sounds like it's a message, with an implicite "What you wanna do with" :)
So, I'm fine switching all/most to non-bold (and with this bigger font).

**Comment by hius07** [comment]
Okay, thanks. I'll do it (and cleanup) after https://github.com/koreader/koreader/pull/8536.
