### ISSUE TITLE
segmentation faut (core dumped)

### ISSUE THREAD

**Issue by Laar3** [koreader/koreader#8568]
when trying to run koreader on arch linux (x86_64) I recieve the following message 
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 12/20/21-23:33:35
 [*] Version: v2021.12

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
Starting SDL in /tmp/.mount_koreadh1jXlM/
Segmentation fault (core dumped)
```
the same issue occurs whether installing from the aur or running the appimage

**Comment by Frenzie** [comment]
A segmentation fault in SDL? Strange.

One thing you could quickly try is to fall back to your system's libSDL2.*, something like this:
```
./koreader-appimage-x86_64-linux-gnu-v2021.12.AppImage --appimage-extract
cd squashfs-root
rm libs/libSDL2.so
./reader.lua
```

Is there anything "special" on your system, like Wayland for example? (The program works fine in Wayland in principle, albeit a bit blurry even in native Wayland mode.)

**Comment by Laar3** [comment]
Thanks. Extracting the appimage and removing that library solved the issue! Yeah my system is running Wayland with the proprietary nvidia drivers (just in case someone stumbles across this with the same problem and it hapens to be the issue.)
Is there a quick way to rebundle the program into an appimage again?

**Comment by Frenzie** [comment]
> Yeah my system is running Wayland with the proprietary nvidia drivers (just in case someone stumbles across this with the same problem and it hapens to be the issue.)

I doubt that's the issue because I've tested that scenario myself, albeit on (K)Ubuntu 21.10 and it works for me, but it's something worth knowing in case "regular" Arch doesn't easily reproduce the problem for example.

> Is there a quick way to rebundle the program into an appimage again?

From the parent dir, this will probably work:
```sh
appimagetool squashfs-root
```

https://github.com/AppImage/AppImageKit/releases

**Comment by Laar3** [comment]
Thanks again. I'll close the issue now.
