### ISSUE TITLE
USB mass storage directories don't match what I see in KOreader

### ISSUE THREAD

**Issue by deoxal** [koreader/koreader#8572]
Don't know if this has already been reported but I can't find it so sorry if I'm wasting your time.

When I connect my Kobo in mass storage mode I see .kobo, .adds, kfmon.sdr and so on and any files I copy to this main directory show up in /mnt/onboard but kfmon.sdr and the others do not show up in /mnt/oboard or anywhere else yet I can see many other privileged files even the kernel.

Meanwhile I tried using SSH on my PC which shows what files KOreader sees but it said it ran out of storage space copying files over even though they copied successfully using mass storage mode later.

So I guess what I want to know is how I can see all my files on my PC and the tablet and copy to and from without being told one's out of storage when it isn't?

**Comment by Frenzie** [comment]
Files starting with a `.` are hidden by default. You can tick the show hidden files checkbox to see them, tap the top, the leftmost file manager icon, settings.

If you put your files in a directory like `.books` (or `.adds`, but the informal standard on Kobo is to put programs in there) they will remain hidden from Nickel. Additionally, there's an option to show unsupported files.

> So I guess what I want to know is how I can see all my files on my PC and the tablet and copy to and from without being told one's out of storage when it isn't?

If you're talking about the last 100 MB or so, it's not recommended to fill that up since that kind of space is used as cache for various operations by most programs you might run on your Kobo. Whether that's full or not would just be natural fluctuations.

**Comment by deoxal** [comment]
You're saying dot directories can be shown by a ticking a box in Nickel? There are a lot of settings and some are rather hidden so I haven't found it if it exists.

I'm not nearing capacity though, since this is a new device. I tried copying some files over using ssh but it said there wasn't enough space but my the file manager on my PC said there was more than enough so I copied them while wired instead which worked.

**Comment by Frenzie** [comment]
No, I'm saying that most of us like to keep our CR/KOReader/Plato files separated from those that will be scanned by Nickel.

**Comment by deoxal** [comment]
Right same here, I only wanted to do this temporarily as I want to start developing for it. I guess I just missed it because it's a bit different from what I'm use to on phones and desktops.

Is there a way to get /bin /sbin /kernel etc to show up and be writable over USB? That would be much more useful than seeing them on the device itself.

Thanks for your help btw.

**Comment by pazos** [comment]
> Is there a way to get /bin /sbin /kernel etc to show up and be writable over USB? 

Nope. You can't export rootfs over USB. What gets exported are the two partitions `/mnt/onboard` and `/mnt/sd` (if your device has one).

> That would be much more useful than seeing them on the device itself.

For what?. You shouldn't mess with rootfs. All KOReader stuff is placed in `/mnt/onboard/.adds` and you can tinker with using USBMS.

**Comment by deoxal** [comment]
I don't want to edit individual files, I want to compile a new OS image altogether and I was thinking I could dd it to the current root partition because there's no boot menu or fastboot.

Also to install a larger sd card I need to copy the root partition exactly but I suppose I could just back it up externally.

**Comment by pazos** [comment]
> I don't want to edit individual files, I want to compile a new OS image altogether and I was thinking I could dd it to the current root partition because there's no boot menu or fastboot.
> 
> Also to install a larger sd card I need to copy the root partition exactly but I suppose I could just back it up externally.

Then please ask in https://www.mobileread.com/forums/forumdisplay.php?f=247, where a lot of knowledge about Kobos is shared. This is a project that happens to run on Kobos, but's not the proper place to ask such questions.
