### ISSUE TITLE
After a file is moved to another directory, it cannot be opened from the history menu

### ISSUE THREAD

**Issue by mrdk** [koreader/koreader#8574]
* KOReader version:  2021.12
* Device: Kobo

#### Steps to reproduce

* Open an ebook for reading.
* Go to the file manager and move this book to a different directory.
* Open the history menu.
* Try to open the moved ebook for reading - it does not work.

The book can still be opened from the file manager; afterwards it can be used without restrictions again.

**Comment by hius07** [comment]
Seems that if you restart KOReader after moving, you can open the book from History, right?

**Comment by mrdk** [comment]
> Seems that if you restart KOReader after moving, you can open the book from History, right?

Yes, even if this is not a practical workaround...
But it helps with the diagnosis.
