### ISSUE TITLE
Question about cpu governer

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8578]
On the new Kobo Sage there are 4 cpu cores, but in `koreader.sh` the governor is only set for `cpu0`.
See:
https://github.com/koreader/koreader/blob/4d261d29a47ff39d71d9fce566e889657e367e2e/platform/kobo/koreader.sh#L26

Shouldn't this line be changed to `echo "interactive" >"/sys/devices/system/cpu/cpu[0-9]/cpufreq/scaling_governor"`? (and ditto with the other similar lines).

**Comment by Frenzie** [comment]
Probably doesn't matter, we don't really profit from extra cores at all, also see https://github.com/koreader/koreader/pull/8250

But at the same time, probably makes sense to do it for consistency? I'll leave it up to @NiLuJe

**Comment by NiLuJe** [comment]
IIRC, we set the global governor on those, but I may have missed that in that final version of the code. Irrelevant in practice since we use the stock governor, so, no changes ;).
