### ISSUE TITLE
View HTML option is missing from highlighted text actions

### ISSUE THREAD

**Issue by dcruzbosco** [koreader/koreader#8580]
* KOReader version: 2021.12
* Device: Kobo Libra H20

#### Issue
View HTML option is missing from highlighted text.

#### Steps to reproduce
1. Open EPUB document
2. Highlight any text
3. Tap on highlighted text.
4. Available options do not include "View HTML"

**Comment by Frenzie** [comment]
Fixed in https://github.com/koreader/koreader/pull/8573 ^_^

**Comment by dcruzbosco** [comment]
Thanks!
