### ISSUE TITLE
Battery Statistics information always shows 0.00% for Change per hour item

### ISSUE THREAD

**Issue by dcruzbosco** [koreader/koreader#8581]
* KOReader version: 2021.12
* Device: Kobo Libra H20

#### Issue
In Battery Statistics details, "Change per hour" item doesn't show updated values and is always 0.00%

![Battery-Stats-No-Percent-Change](https://user-images.githubusercontent.com/1913687/147259575-c55744d6-7e7a-4206-a5e2-dcfed728fdb7.png)

**Comment by hius07** [comment]
Seems, self.time in seconds, must be in hours, `* 3600`.
https://github.com/koreader/koreader/blob/a024a42289532041938bd90b5d4f238a0fb35d0b/plugins/batterystat.koplugin/main.lua#L50-L56
