### ISSUE TITLE
Crash at start on nova air

### ISSUE THREAD

**Issue by MardukMason** [koreader/koreader#8584]
* KOReader version: Version v2021.12.1-1-g873ceac5_2021-12-23
* Device: Onyx Boox Nova Air

#### Issue
KOreader crash on start

Looks like this comes from this commit #8562 

#### Steps to reproduce
Start KOreader

##### `crash.log` (if applicable)
[24.12.2021 1310.txt](https://github.com/koreader/koreader/files/7774259/24.12.2021.1310.txt)

**Comment by pazos** [comment]
FWIW: cathing exceptions should be mandatory for each driver implementation. 

I guess we should revert the offending commit or, at least revert non tested devices to the previous driver. Pinging @Galunid

**Comment by Galunid** [comment]
Sorry, I wasn't online recently, it's pretty weird that this happens, provided Nova2/Nova Air/Nova Air 2 should use the same soft (and have the same methods available), but it's onyx so who knows...
