### ISSUE TITLE
Appimage not working on Debian 9 Stretch since June 2021 update

### ISSUE THREAD

**Issue by thenoobtester** [koreader/koreader#8585]
* KOReader version:koreader-appimage-x86_64-linux-gnu-v2021.06.AppImage
* Device:Linux Debian 9 Stretch

#### Issue
The Appimage doesn't work on Debian 9 Stretch since June 2021 update (koreader-appimage-x86_64-linux-gnu-v2021.06.AppImage), including updates from August 2021 and the latest version December 2021. The last working version is koreader-appimage-x86_64-linux-gnu-v2021.05.AppImage. 

When I launch the Appimage I get:

> ./koreader-appimage-x86_64-linux-gnu-v2021.06.AppImage 
                launching...
> It's a scroll... It's a codex... It's KOReader!
>
 >[*] Current time: 12/24/21-18:24:29
 >[*] Version: v2021.06
>
>ffi.load: blitbuffer
>ffi.load: SDL2
>ffi.load (assisted searchpath): ./libs/libSDL2.so
>ffi.load: libSDL2-2.0.so
>ffi.load (warning): /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.25' not found (required by /tmp/.mount_koreadA08pVg/libs/libbsd.so.0)
>ffi.load: libSDL2-2.0.so.0
>ffi.load (warning): /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.25' not found (required by /tmp/.mount_koreadA08pVg/libs/libbsd.so.0)
>SDL2 not loaded:        ./setupkoenv.lua:27: Not able to load dynamic library: libSDL2-2.0.so.0
>./luajit: frontend/device.lua:58: Could not find hardware abstraction for this platform. If you are trying to run the emulator, please ensure SDL is installed.
>stack traceback:
>        [C]: in function 'error'
>        frontend/device.lua:58: in function 'probeDevice'
>        frontend/device.lua:61: in main chunk
>        [C]: in function 'require'
>        ./reader.lua:142: in main chunk
>        [C]: at 0x555636f0c750

It seems to be related to my libc.so.6 only supporting up to 2.24, but I thought an appimage allowed resolving that issue and could embed newer GlibC than the host system. I also thought that was the case for previous appimage already (meaning running on GLIBC_2.25, but I don't know how to check that). Did anything particular change since June? 

It's by no means an urgent matter, so whenever you have time :)

Thank you for this great piece of software and Merry Christmas to you and everyone here :)

#### Steps to reproduce
Just run ./koreader-appimage-x86_64-linux-gnu-v2021.06.AppImage on Debian 9 Stretch.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
> Did anything particular change since June?

Yes, effectively we switched it from Debian 9 to 10. I'm a bit surprised anybody noticed actually, but I apologize for not mentioning it in the release notes.

Ubuntu 16.04 reached EOL in April, so we switched to 18.04. 

> but I thought an appimage allowed resolving that issue and could embed newer GlibC than the host system

If you mean static linking, I'd prefer to avoid that here.

Btw, how come you're using Debian 9 on desktop if you don't mind answering?

**Comment by thenoobtester** [comment]
Thank you for the quick reply. 

> I'm a bit surprised anybody noticed actually

Except me 🤣 I'm always that guy.

> but I apologize for not mentioning it in the release notes.

No need to I'm the one lagging behind.

> If you mean static linking, I'd prefer to avoid that here.

I'm actually not that well versed when it comes to software building so I'm not really asking for anything that complicated :) Meaning I don't know what static linking would involve.

> Btw, how come you're using Debian 9 on desktop if you don't mind answering?

And the grand finale, because I'm old unfortunately and I like to keep a system running for as long as I can, upgrades always break things and I don't have the energy nor time to tinker with this stuff anymore. One day you'll understand.

The version that still works on Debian 9 is good enough for me, so don't worry about this. One quick question though once zoomed in on a pdf for example is there a short cut to move around the page or only touch screens can? I ask because with Shift PageUp/PageDown it always zooms in on the same region of the page.

Kindest regards

**Comment by Frenzie** [comment]
> once zoomed in on a pdf for example is there a short cut to move around the page or only touch screens can

All the puzzle pieces are there but that's indeed a missing feature. Other methods are almost always better on eink, but zoom to fit... is pretty neat on desktop too. I also use Evince among others, depends a bit on the document and what I want to do with it.

**Comment by thenoobtester** [comment]
Yes evince is good I use it too. I just like how fast your reader is. I used to use qpdfview but it was slow to zoom and load.

Thanks anyways. Merry Christmas.

**Comment by Frenzie** [comment]
Btw, you could also try Zathura. It's somewhat similar in both used tech and document reading approach, even though this is an app for eink devices that I made into an appimage and that's always been intended for desktop.

Merry Christmas!

**Comment by thenoobtester** [comment]
I will give it a try. I had never heard of it before.
