### ISSUE TITLE
Koreader causes kobo forma to crash and unresponsive while charging

### ISSUE THREAD

**Issue by tokyode** [koreader/koreader#8589]
I have kobo forma 32gb. When charging for a couple hours with sleep cover event enabled and sleep cover closed, the forma went into sleep mode and will not wake up, will not register touch, will not respond to power button press to wake up.
The cause is that the setting on koreader 「turn on led while charging 」is enabled.
When above happens, the only way is to long press power button until the forma is powered off, then power on again.

The work around is by disabling 「turn on led while charging 」

**Comment by NiLuJe** [comment]
That's... interesting, given as this was tested on a Forma (albeit an 8GB one, not that it should matter) ;p.

Which FW version is it running?

**Comment by NiLuJe** [comment]
Also, is the LED still on when it hangs?

**Comment by pazos** [comment]
No more info. Closing.
