### ISSUE TITLE
translation not matched

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8594]
* KOReader version: v2021.12.1
* Device: PB 628

#### Issue
Although the Greek translation of the phrase "too many interruptions or crashes" has be done (as you can see [here](https://hosted.weblate.org/translate/koreader/koreader/el/?q=too+many&sort_by=-priority%2Cposition&offset=2)), it isn't merged.

Could it be fixed, please?
Thanks!

**Comment by Frenzie** [comment]
How do you trigger seeing it?

**Comment by ichnilatis-gr** [comment]
I give you a screenshot of a book entry.

![FileManager_2021-12-27_083319](https://user-images.githubusercontent.com/76203123/147471593-06a3bde7-0496-48cd-9274-3948c564f62a.jpg)

**Comment by Frenzie** [comment]
I can't get it to show. 

If I dump some random nonsense…
```
head -c 1M </dev/urandom >junk.epub
```
It just thinks it's a text file.

If anybody could provide a file that crashes (preferably without being 300 MB), that'd be useful. ;-)

**Comment by Frenzie** [comment]
A quick debug statement seems to suggest it's properly detected.
```
$ ./kodev run | rg gettext | rg "too many interruptions or crashes"
gettext too many interruptions or crashes       teveel onderbrekingen of crashes
gettext too many interruptions or crashes       πάρα πολλές διακοπές ή καταρρεύσεις συστήματος
```

**Comment by Frenzie** [comment]
@ichnilatis-gr @poire-z Having skimmed through the code over in plugins/coverbrowser.koplugin/bookinfomanager.lua I think the reason is stored the first time it goes wrong, in full text rather than as some kind of code that's translated into a string at display time.

**Comment by poire-z** [comment]
Indeed, we seem to store one of these 2 reasons:
https://github.com/koreader/koreader/blob/dd07112de7f8ac6048e6dc4306a169b1eddbf0d1/plugins/coverbrowser.koplugin/bookinfomanager.lua#L442
https://github.com/koreader/koreader/blob/dd07112de7f8ac6048e6dc4306a169b1eddbf0d1/plugins/coverbrowser.koplugin/bookinfomanager.lua#L551
And we only display it in "Detailed list" mode:
https://github.com/koreader/koreader/blob/dd07112de7f8ac6048e6dc4306a169b1eddbf0d1/plugins/coverbrowser.koplugin/listmenu.lua#L577-L579

We could store the english string untranslated (rather than a code), and have it translated only when about to be displayed.

**Comment by Frenzie** [comment]
> We could store the english string untranslated (rather than a code), and have it translated only when about to be displayed.

That'd make the English string the code. ;-) (Not an objection, might as well have a code that plainly says what it is, plus it'll be backwards compatible.)

**Comment by poire-z** [comment]
Any better/simpler idea for the first chunk ? I think we need to have the same string litteral both as the plain string we will insert, and as the litteral wrap in `_()` for it to be extraced and make available to weblate, right ?
```diff
--- a/plugins/coverbrowser.koplugin/bookinfomanager.lua
+++ b/plugins/coverbrowser.koplugin/bookinfomanager.lua
@@ -116,2 +116,6 @@ local BOOKINFO_IN_PROGRESS_SQL = "SELECT in_progress, filename, unsupported FROM

+local UNSUPPORTED_REASONS = {
+    not_readable_by_engine = { string = "not readable by engine", translation = _("not readable by engine") },
+    too_many_interruptions_or_crashes = { string = "too many interruptions or crashes", translation = _("too many interruptions or crashes") }
+}

@@ -441,3 +445,4 @@ function BookInfoManager:extractBookInfo(filepath, cover_specs)
         dbrow.in_progress = 0     -- row will exist, we'll never be called again
-        dbrow.unsupported = _("too many interruptions or crashes") -- but caller will now it failed
+        dbrow.unsupported = UNSUPPORTED_REASONS.too_many_interruptions_or_crashes.string
         dbrow.cover_fetched = 'Y' -- so we don't try again if we're called later with cover_specs

@@ -550,3 +555,4 @@ function BookInfoManager:extractBookInfo(filepath, cover_specs)
     if not loaded then
-        dbrow.unsupported = _("not readable by engine")
+        dbrow.unsupported = UNSUPPORTED_REASONS.not_readable_by_engine.string
         dbrow.cover_fetched = 'Y' -- so we don't try again if we're called later if cover_specs

--- a/plugins/coverbrowser.koplugin/listmenu.lua
+++ b/plugins/coverbrowser.koplugin/listmenu.lua
                 -- Let's show this fact in place of the anyway empty authors slot
-                authors = T(_("(no book information: %1)"), bookinfo.unsupported)
+                authors = T(_("(no book information: %1)"), _(bookinfo.unsupported))
             end
```

**Comment by Frenzie** [comment]
You could consider ["not readable by engine"] = _("not readable by engine")
although that might set a bad precedent for something merely intended as an
exception.
