### ISSUE TITLE
Cloud storage crashes the device

### ISSUE THREAD

**Issue by lormaccone** [koreader/koreader#8597]
I have koreader installed in two devices: a Pocketbook 840 and a Kobo Aura. In both cases accessing cloud storage crashes the device. I'm using a nextcloud server, accessed in webdav mode. The Kobo sometimes works, the Pocketbook sometimes manages to open the nextcloud server, but then crashes consistently every time I open a folder in the nextcloud server. I attach a screenshot. 
![20211228_084218](https://user-images.githubusercontent.com/77665037/147541763-58995cd2-af4f-4aef-994f-67f34deda4bf.jpg)

**Comment by hius07** [comment]
Can you provide crash.log please.

**Comment by lormaccone** [comment]
Doesn't contain much more than the screenshot. Anyhow, here it is.
[crash.log](https://github.com/koreader/koreader/files/7783977/crash.log)

**Comment by hius07** [comment]
Thanks, at least it's clear that the issue is not caused with the latest change to the module (https://github.com/koreader/koreader/pull/8569).
Please enable detailed log, in the file manager menu Tools - Developer options - Enable debug logging.

**Comment by NiLuJe** [comment]
A SIGILL is a bit weird ;/. Would probably require a debug build and gdb backtrace to suss out what might be happening...

**Comment by lormaccone** [comment]
Here it is. It's a bug that has been in my Kobo for a long time, I just installed the latest on my pocketbook. Thanks.
[crash.log](https://github.com/koreader/koreader/files/7784641/crash.log)

I don't know how to do the gdb thing, although I could install gdb on my computer...

**Comment by hius07** [comment]
Cannot it be connected with the AutoSuspend plugin? Try to disable it.

**Comment by lormaccone** [comment]
No change.
[crash.log](https://github.com/koreader/koreader/files/7785911/crash.log)

**Comment by mergen3107** [comment]
> I just installed the latest on my pocketbook

Did you transfer the settings from Kobo to Pocketbook?
