### ISSUE TITLE
Pocketbook Inkpad Color "Wi-Fi Connection" enabled when no connection

### ISSUE THREAD

**Issue by rjd22** [koreader/koreader#8617]
* KOReader version: KOReader 2021.12.1
* Device: Pocketbook Inkpad Color (PB741)

#### Issue

I found this issue when testing #8546

When starting koreader while the wifi on the pocketbook is disconnected the setting "Wi-Fi connection" will report it is connected to the wifi while there is no connection.

This blocks me from enabling the connection again when it is not connected.

#### Steps to reproduce

1. Start pocketbook inkpad color
2. Put it to sleep en enable it again
3. Check the Wifi is now with no bars
4. Start koreader en see `Wi-Fi connection` button is checked
5. Open `Network info` and see there is no connection

#### Information on how to fix

This seems to be an regression in #6559 when to following code changed:

https://github.com/koreader/koreader/pull/6559/files#diff-a8ac72a4e6ad810515185593e3f6f758475e3cea34dbfdac0e0d2fd1888a2414L201-L203

When I change the code to the following I'm able to reconnect with the WiFi again:

```
    function NetworkMgr:isWifiOn()
        if (inkview.GetNetState() ~= 2) then
            return false
        end
    
        return band(inkview.QueryNetwork(), C.CONNECTED) ~= 0
    end
```

If would like to make a patch for this but I need some more info on how `QueryNetwork` is supposed to act. I sadly don't know where to look :(. For completeness I dumped the values of the different states when Wifi is disconnected on the pocketbook.

- `inkview.GetNetState()` returns `cdata<enum 875>: 0`
- `inkview.QueryNetwork()` returns `3`
- `C.CONNECTED` is `2`
- `band(inkview.QueryNetwork(), C.CONNECTED) ~= 0` results into `true`

**Comment by Frenzie** [comment]
Maybe @pazos might know a little more about where to find some references?

**Comment by pazos** [comment]
on mobile right now. Returning back to inkview.GetNetState() is not an option as the symbol is not present on old models.

Just try with returning inkview.QueryNetwork() == C.CONNECTED as the band function just works with return values 1 and 2 from queryNetwork.

I hope it makes sense

**Comment by rjd22** [comment]
@pazos if I make an PR with the following change would that not disturb other PocketBook devices? If so I will make the PR tomorrow:

```
function NetworkMgr:isWifiOn()
    return inkview.QueryNetwork() == C.CONNECTED
end
```

**Comment by pazos** [comment]
@rjd22: yup, it must work.

**Comment by rjd22** [comment]
I've tested it but sadly this change will not be enough. When connected the `inkview.QueryNetwork()` returns a completely other state than expected. These are the returned states when connected:

- `inkview.GetNetState()` returns `cdata<enum 875>: 2`
- `inkview.QueryNetwork()` returns `515`

I make a patch for this but it's kind of a single device only patch. I hope to get some feedback on how to improve it. The patch can be found in #8621

**Comment by pazos** [comment]
Ummmmm, what a shit fest :/

It is expected than the return value matches one of the NET_STATE values from https://github.com/koreader/koreader-base/blob/master/ffi/inkview_h.lua#L109-L113

My assumption was they've added a new value `NOT_CONNECTED = 3` but doesn't make much sense if they also modified previous values.

My new assumption is: they're deprecating `inkview.QueryNetwork`. If that's true the return value of `inkview.QueryNetwork` should never be something <= 2.

In that case the following example should be cleaner and prevent us from introducing new constants without too much knowledge of what they meant :)

```lua
function NetworkMgr:isWifiOn()
    local state = inkview.QueryNetwork()
    if state <= C.CONNECTED then
        return band(state, C.CONNECTED) ~= 0
    else
        return inkview.GetNetState() == C.CONNECTED
    end
end
```

**Comment by rjd22** [comment]
@pazos something worth considering is to split the system into 2 systems. For example pocketbook-legacy and pocketbook.

It seems that pocketbook is deprecating fast and the would free up room to make more improvements for newer pocketbooks while not breaking older ones.

**Comment by rjd22** [comment]
@pazos I've tested you suggestion and this indeed fixes the issue for the PB741. I also like that this might also fix the issue for newer devices. Thank you for the suggestion.

I adapted the PR to the new changes.

**Comment by pazos** [comment]
> something worth considering is to split the system into 2 systems. For example pocketbook-legacy and pocketbook.

Current device abstraction is quite solid. Works well even in android, where we keep a zillion of devices under the same "device". The only reason I could think of to add a new target is a new arch or specific build flags that only work on a subset of devices.

The problem of Pocketbooks is the lack of documentation and the lack of a maintainer. Makes a nightmare to decide what's legacy and what's not.

**Comment by rjd22** [comment]
Yep, I agree. I will at least start on helping out to maintain the PB741. Hopefully we can improve things on the PocketBook side of things. I might send them an email on if they can share more documentation on their API's.
