### ISSUE TITLE
Selecting beginning of word selects characters in word itself

### ISSUE THREAD

**Issue by Issue-maker-9000** [koreader/koreader#8619]
* KOReader version: 2021.12.1
* Device: Kindle paperwhite 4

#### Issue
When reading japanese books and trying to select the beginning of a word to select the full word (for lookups when using the japanese support plugin) it will always select the characters to the right of it, so with the word わたし when pressing character わ it will only select たし instead of the full word.

Getting around this is as simple as holding the letter/space before the word you try to select, which is why I think this might be a bug.

#### Steps to reproduce
Open a japanese epub
enable the japanese support plugin
select the first letter of a word
it will select the characters next to the character you tried to select instead of selecting the full word

Hopefully the bugreport is clear enough else just ask!

**Comment by poire-z** [comment]
Pinging @cyphar

**Comment by cyphar** [comment]
This has been a problem in KOReader for a long time -- I was planning on opening a bug about this but got busy with other things. This was one of the problems I was trying to describe in #8270. As far as I can tell it's some kind of offset issue -- everything appears to be offset to the right when selecting things (this happens in the emulator and on Android).

The reason this is only apparent for CJK text is that for other languages KOReader will select the entire word automatically so it doesn't matter if you started the selection inside the word. But for Japanese (and other CJK languages) you need to accurately select the first character of the word. (A dodgy workaround would be to do a one-character lookbehind in the Japanese plugin but that would just hide the issue and would cause it's own issues.)

There seem to be some other input-related issues as well on my Onyx Boox 3 Air (if you try to start a selection using the stylus  it turns the page instead -- sometimes many pages in a row -- about half the time). But those are probably unrelated and I should open a separate issue for those...

**Comment by poire-z** [comment]
> As far as I can tell it's some kind of offset issue -- everything appears to be offset to the right when selecting things. Effectively if you try to select near the middle of a character in a sentence, KOReader considers this as you starting the selection after that character.

Indeed, there's this, that dates from 2007 (no git history before allows to see if the /2 where fixing something, or if it's just a wrong hunch by the original author), that I never questionned:
```c
lvtinydom.cpp
/// create xpointer from doc point
ldomXPointer ldomDocument::createXPointer( lvPoint pt, int direction )
  at the bottom of it:
aac8cb6d9 (Vadim Lopatin      2007-03-14 11:31:43 +0000)|                lString16 str = node->getText();
68f3de4fd (Vadim Lopatin      2008-09-15 22:10:41 +0000)|                font->measureText( str.c_str()+word->t.start, word->t.len, w, flg, word->width+50, '?', src->letter_spacing);
b37102a22 (Vadim Lopatin      2007-03-18 07:47:22 +0000)|                for ( int i=0; i<word->t.len; i++ ) {
aac8cb6d9 (Vadim Lopatin      2007-03-14 11:31:43 +0000)|                    int xx = ( i>0 ) ? (w[i-1] + w[i])/2 : w[i]/2;
aac8cb6d9 (Vadim Lopatin      2007-03-14 11:31:43 +0000)|                    if ( x < word->x + xx ) {
2f570bcb3 (Vadim Lopatin      2007-12-10 05:41:51 +0000)|                        return ldomXPointer( node, src->t.offset + word->t.start + i );
aac8cb6d9 (Vadim Lopatin      2007-03-14 11:31:43 +0000)|                    }
aac8cb6d9 (Vadim Lopatin      2007-03-14 11:31:43 +0000)|                }
```
The `/2` in `int xx = ( i>0 ) ? (w[i-1] + w[i])/2 : w[i]/2;` makes it consider half of a glyph width, and if your x is in the right part of the glyph, it goes consider the word/glyph after.
And it feels in this context of text selection, if x is near the right edge of the glyph, we want that glyph as a whole. Remove the `/2` and it behave.
With crengine, it's always hard to grasp these xpointers, sometimes, it feels they need to be used as boundaries between text units, like for drawing rectangle for selection, sometimes they reference the text unit... so removing these `/2` might cause other issues. It would need testing and may be tweaks...

With non CJK text, this is mitigated by some gymastic in cre.cpp getTextFromPositions() where we use isVisibleWordChar() / prevVisibleWordStart() to shake/move/grab stuff :) so we end up getting what we want without any noticable issue (ie. a sentence starting with "A number of pieces", no problem selecting the A when hiting its right, the space after that ends up being found,not being a visible word char, have the code pick the prev visible word start, so the A).

**Comment by Issue-maker-9000** [comment]
> The reason this is only apparent for CJK text is that for other languages KOReader will select the entire word automatically so it doesn't matter if you started the selection inside the word. But for Japanese (and other CJK languages) you need to accurately select the first character of the word. (A dodgy workaround would be to do a one-character lookbehind in the Japanese plugin but that would just hide the issue and would cause it's own issues.)
> 
This makes a lot of sense why I never noticed this before, would be nice if someone could pick it up although it is honestly mostly a minor annoyance than anything.
Also thank you for making the Japanese support plugin specifically, it works amazing!

**Comment by poire-z** [comment]
> so removing these /2 might cause other issues. It would need testing and may be tweaks...

Well, it feels risky to change crengine, and I think the current behaviour is rather ok and clever to not have to wonder (is the generic code involved, that is quite far from where we know we are doing text selection) whether we're interested about the start of end of the glyph of the char pointed to.
I think we can more safely hack it into base/cre.cpp. I would go with this:
```diff
--- a/cre.cpp
+++ b/cre.cpp
@@ -1899,23 +1899,55 @@ static int getTextFromPositions(lua_State *L) {
                bool not_panning = r.getStart() == r.getEnd();
                if ( (not_panning || r.getStart().isVisibleWordChar()) && !r.getStart().isVisibleWordStart())
                        r.getStart().prevVisibleWordStart();
                if ( (not_panning || r.getEnd().isVisibleWordChar()) && !r.getEnd().isVisibleWordEnd())
                        r.getEnd().nextVisibleWordEnd();
                if (r.isNull())
                        return 0;

+               // A xpointer references a char in a text node; a char has a width, and getNodeByPoint()
+               // has a trick of returning a xpointer to this char when the point is in the left half of
+               // the glyph, or to the next char when the point is in the right half of the glyph, which
+               // feels clumsy but has the effect that it doesn't need to know and care about whether the
+               // point references the start or the end of the selection.
+               // This is usually hidden by the above code that extends the selection to start and end
+               // of words. But with CJK chars, where each char is a word, this behaviour is noticable.
+               // It's usually OK with multiple chars selection, even if one needs to go over the further
+               // 2nd half of the glyph to have it included in the selection.
+               // But it is less OK with an initial long-press on a glyph, where we get 50% chances of
+               // having the next char selected. Try to handle this case better:
                if (r.getStart() == r.getEnd()) { // for single CJK character
+                       bool grab_prev = false;
+                       lvRect glyph_pt;
+                       if ( tv->getCursorRect(r.getStart(), glyph_pt) ) {
+                               // If the glyph left edge is after both start and end pt x, it's not the right one.
+                               grab_prev = glyph_pt.left > startpt.x && glyph_pt.left > endpt.x;
+                               if (!grab_prev) {
+                                       // If line wrapping, next char might start the next line, so also
+                                       // check y: if the glyph top is below our start and end pt, it is
+                                       // on the next line, and it's not the right one.
+                                       grab_prev = glyph_pt.top > startpt.y && glyph_pt.top > endpt.y;
+                               }
+                               // printf("startpt %d/%d, endpt %d/%d, vs. glyphpt %d/%d => grab_prev=%d\n",
+                               //    startpt.x, startpt.y, endpt.x, endpt.y,  glyph_pt.left, glyph_pt.top, grab_prev);
+                       }
                        ldomNode * node = r.getStart().getNode();
                        lString32 text = node->getText();
                        int textLen = text.length();
-                       int offset = r.getEnd().getOffset();
-                       if (offset < textLen - 1)
-                               r.getEnd().setOffset(offset + 1);
+                       if (grab_prev) {
+                               int offset = r.getStart().getOffset();
+                               if (offset > 0)
+                                       r.getStart().setOffset(offset - 1);
+                       }
+                       else {
+                               int offset = r.getEnd().getOffset();
+                               if (offset < textLen)
+                                       r.getEnd().setOffset(offset + 1);
+                                               // (offset can be 0 .. textlen, textlen means after the last char)+                       }
                }

                int rangeFlags = 0;
                if (drawSelection) // have crengine do native highlight of selection
                        rangeFlags = drawSegmentedSelection ? 0x11 : 0x01;
```
Does this code and my comment look convincing enough? :)

**Comment by Issue-maker-9000** [comment]
Can't read code, but I would love to try it out!
Also thanks so much for looking into it :)

**Comment by Issue-maker-9000** [comment]
> 

Can't read code, but I would love to try it out!
Also thanks so much for looking into it :)

**Comment by Issue-maker-9000** [comment]
Thank you all for fixing this issue!

**Comment by cyphar** [comment]
I finally managed to get the emulator working again. The patch applied does solve the problem though (perhaps for unrelated reasons), now you cannot really select a single character if you want to (more specifically you cannot reduce the selection to a single character if the selection is already larger than 1 character). This happened sometimes in previous KOReader versions but now it seems to consistently not work.

There are cases where you might only want to select a single character, but it should be noted that I personally don't need this to work, so if it's too annoying to get working don't worry about it.

**Comment by poire-z** [comment]
> now you cannot really select a single character if you want to (more specifically you cannot reduce the selection to a single character if the selection is already larger than 1 character). 

This seems to work for me - at least when using a bigger font and a glyph width is larger that some distance threshold in the code - it's indeed harder in small text. I need to go over the first half width of the next glyph.
But trying this on an older KOReader, it works even less well: there, I can't manage to do the "reduce to select 1 character).
