### ISSUE TITLE
koreader is extremely blurry on wayland

### ISSUE THREAD

**Issue by Spagett1** [koreader/koreader#8630]
text on koreader on wayland is very blurry whereas in xorg it is fine. This happens both on the sway and river window managers. 

this happens both in the book and in the ui

![2022-01-09-00:43:39](https://user-images.githubusercontent.com/77225642/148647467-12053e61-36f8-4543-a27b-5d6cf5f932d0.png)
![2022-01-09-00:42:56](https://user-images.githubusercontent.com/77225642/148647469-648eb26f-65de-4c86-bb31-da7ddf8a5efd.png)
 here is the terminal output:
```
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/09/22-00:45:03
 [*] Version: v2021.12.1

ffi.load: blitbuffer
ffi.load: SDL2
ffi.load: SDL2
Starting SDL in /usr/lib/koreader/
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.so
01/09/22-00:45:04 INFO  initializing for device Linux
01/09/22-00:45:04 INFO  framebuffer resolution: {
    ["w"] = 360,
    ["h"] = 695,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
01/09/22-00:45:04 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:179: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
01/09/22-00:45:04 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
01/09/22-00:45:04 INFO  Loading plugins from directory: /home/alarm/.config/koreader/plugins/
01/09/22-00:45:05 ERROR #! Font  NotoSansArabicUI-Bold.ttf  ( NotoSansArabicUI-Bold.ttf ) not supported:  ./ffi/freetype.lua:179: Failed to load font './fonts/NotoSansArabicUI-Bold.ttf', freetype error code: 1
01/09/22-00:45:05 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:179: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
01/09/22-00:45:05 ERROR #! Font  NotoSansArabicUI-Bold.ttf  ( NotoSansArabicUI-Bold.ttf ) not supported:  ./ffi/freetype.lua:179: Failed to load font './fonts/NotoSansArabicUI-Bold.ttf', freetype error code: 1
01/09/22-00:45:05 ERROR #! Font  NotoSansArabicUI-Regular.ttf  ( NotoSansArabicUI-Regular.ttf ) not supported:  ./ffi/freetype.lua:179: Failed to load font './fonts/NotoSansArabicUI-Regular.ttf', freetype error code: 1
01/09/22-00:45:08 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_MONOTONIC
```
These logs and pictures are taken from arch limux arm (i extracted the .deb) but the issue is exactly the same on standard arch linux when using the appimage or aur package.

**Comment by pazos** [comment]
SDL uses X11 by default on Linux. Did you check https://wiki.libsdl.org/FAQUsingSDL#how_do_i_choose_a_specific_video_driver?

**Comment by pazos** [comment]
Also, sdl2 is pulled from distro packages on linux. Make sure the sdl2 lib loaded was built with wayland support.

**Comment by Frenzie** [comment]
When using Wayland it's still not quite right, but yes, by default it uses X.

**Comment by pazos** [comment]
> When using Wayland it's still not quite right, but yes, by default it uses X.

Can you reproduce with SDL2.0.16+?

**Comment by Frenzie** [comment]
I currently seem to have 2.0.14. I'll check again in a year or two.

**Comment by pazos** [comment]
Sad but true. And I guess the only reason to have 2.0.14 is https://security.gentoo.org/glsa/202107-55

**Comment by Frenzie** [comment]
Anyway, you can run the program with `SDL_VIDEODRIVER=wayland` as an environment variable to run SDL in Wayland mode. You can easily verify which it's using with xeyes (i.e., move the mouse there and the eyes will follow if it's X11 and they won't if it's Wayland). There are probably other ways as well.

However, the rendering is very similar or identical (on 2.0.14). The only difference is whether the window manager/Wayland is doing the annoying blurry scaling or whether it's SDL.

I'll probably give 2.0.18 a go to see if it fares any better, but basically this is just one of many issues with Wayland/XWayland that make it pre-alpha quality. Which to be clear is a huge step up from half a year ago when Wayland was utterly unusable, so eh.

**Comment by Laar3** [comment]
thanks. later today ill try those things.

**Comment by Laar3** [comment]
i got a chance to check and it happens when using both xwayland and wayland (confirmed by xeyes) im on sdl 2.0.18.

**Comment by Frenzie** [comment]
See `https://github.com/OpenRA/OpenRA/issues/12777#issuecomment-280730395` for some related discussion.

Reverting https://github.com/koreader/koreader-base/pull/1056 for testing has no effect, for the record.

**Comment by Laar3** [comment]
yeah i found that if i disabled scaling in sxmo sway it works fine.

**Comment by Frenzie** [comment]
> I currently seem to have 2.0.14. I'll check again in a year or two.

Only a year and a half later, ahead of schedule. ;-P
