### ISSUE TITLE
Android: cannot change download path for OPDS after it is set to "/"

### ISSUE THREAD

**Issue by bendardenne** [koreader/koreader#8631]
On Android, when downloading a file from OPDS, I have accidentally hit the "parent directory" button in the file chooser.

Now, my directory is set to "/" and there appears to be no way to change this. 
Since / is not readable, I cannot navigate back to a writeable folder. 
Since / is not writeable, I cannot download files at all. 

I have tried to clear cache and data, as well as reinstalling the app, but this seems to be persisted somewhere.

![Screenshot_20220108-145250](https://user-images.githubusercontent.com/8947051/148647634-aa802da0-a7f1-4456-96c4-5b89060da15d.jpg)

![Screenshot_20220108-145236](https://user-images.githubusercontent.com/8947051/148647631-ed366f08-0687-420f-a42b-487c0f37e6e7.jpg)

**Comment by bendardenne** [comment]
Fixed by modifying  download_dir in koreader/settings.reader.lua via ADB.

**Comment by pazos** [comment]
Requires something like https://github.com/koreader/koreader/pull/6996/files#diff-a1f60b5e8470e49643e8b8eb9d87e15ef3c268d325873a4839fe64f902cb7793

**Comment by hius07** [comment]
I'm going to look if we can add Home (left) button to the pathchooser title.

**Comment by bendardenne** [comment]
Good solution, thanks for the quick fix!
