### ISSUE TITLE
Account for a "Hardware defaulted zone" when displaying on a defaulted screen

### ISSUE THREAD

**Issue by scd75** [koreader/koreader#8635]
**Does your feature request involve difficulty completing a task? Please describe.**
I have a Kobo reader, which has a defaulted screen, with a grey horizontal line (5mm height), right in the midddle of the screen. Buying a new screen is expensive for my model, hence I'm looking for a software way to render files on my reader, without printing lines in the defaulted zone.

**Describe the solution you'd like**
Have the ability to define one or multiple "defaulted zones", maybe in terms of absolute pixel positions, where no text would be printed when rendering files on the reader.

**Describe alternatives you've considered**
I tried to set the line spacing, font size etc.. to values that allow the thing to work, but obvisouly it changes as soon a I switch to another page, or even when the line spacing changes in the original document.

**Additional context**
from what I read on the web, it's fairly common to have screen that detfault with horizontal lines..

**Comment by NiLuJe** [comment]
Sidebar: You surely meant to say "faulty" ;).

It's easy enough to do when said faulty zones are on the edge of the screen: just use a viewport.

It's going to be a hard-pass when said zones are anywhere else, though.

**Comment by scd75** [comment]
yes, "faulty" :)
with wiewport I would basically lose half of my screen in my case..
Any trick you would think of to render the text over 2 "virtual" sections stacked vertically? As my horizontal line is right in the middle of my screen :/

**Comment by Frenzie** [comment]
For epub you could use two column mode plus landscape.

**Comment by Frenzie** [comment]
![Screenshot_2022-01-09-21-36-41-79_1aff61e6bd981aaa4ba9d0245eb6c04f](https://user-images.githubusercontent.com/202757/148699851-e730d93b-225d-4f5a-a365-81b4f9c3bc49.jpg)
