### ISSUE TITLE
KOReader crashes on Pocketbooks

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#8638]
* KOReader version: v2021.12.1
* Device: Pocketbook Inkpad Lite (PB970)

#### Issue
KOReader crashes with a bomb randomly when reading .cbz files. I don't use it for books, so I'm not sure if it's only .cbz or if .epub crashes too. It happens completely randomly, some days it's fine, other days it isn't. It crashed 3 times in the same day, so I thought about reporting this. 

#### Steps to reproduce
Open KOReader (I don't have it set as the default reader)
Open .cbz file
Read for a period of time
Boom, a crash

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/7835479/crash.log)

**Comment by Frenzie** [comment]
I think this may have been mentioned somewhere already.

```
./luajit: frontend/ui/uimanager.lua:1201: attempt to call field 'action' (a nil value)
stack traceback:
	frontend/ui/uimanager.lua:1201: in function '_checkTasks'
	frontend/ui/uimanager.lua:1622: in function 'handleInput'
	frontend/ui/uimanager.lua:1730: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00013f81
Segmentation fault
!!!!
Uh oh, something went awry... (Crash n°1: 01/09/22 @ 16:44:48)
Attempting to restart KOReader . . .
!!!!
```

**Comment by NiLuJe** [comment]
Does it still happen on a current nightly?

**Comment by Danar435** [comment]
I haven't tried. I need to change the update channel to Development for nightly, right?

**Comment by Frenzie** [comment]
Yup. Indeed it's better to check that.

**Comment by Danar435** [comment]
Alright, gonna do that then. I'll let you know if it crashes again.

**Comment by hius07** [comment]
> I think this may have been mentioned somewhere already.

https://www.mobileread.com/forums/showthread.php?p=4187037#post4187037

**Comment by ichnilatis-gr** [comment]
KOReader version: v2021.12.1-41
    Device: PB 628

I would like to mention that the same problem occurs on my device. Suddenly, while I am reading, without any other action, a crash occurs, regardless of the type of the book. I give you a recent relevant extract from the crash file.

[crash 10-1-2022.txt](https://github.com/koreader/koreader/files/7853532/crash.10-1-2022.txt)

**Comment by ichnilatis-gr** [comment]
Today a new crash took place while reading a pdf file. I give you the relevant crash.log
[crashlog 13-1-2022.txt](https://github.com/koreader/koreader/files/7862880/crashlog.13-1-2022.txt)

(The crash.log file I provided yesterday didn't contain the recording of the crash and I had to upload it again with the correct excerpt.)

**Comment by ichnilatis-gr** [comment]
Does this problem have any relation to the Pocketbook system version? Would it help if I reinstalled an older version?

**Comment by Danar435** [comment]
It's been a while, but KOReader started crashing again. I haven't used it much after I opened the issue, so maybe Nightly didn't fix the bug I'm having. I've attached a log which ends the same way the previous log ends. I should also mention that sometimes after I open KOReader and return to use other Pocketbook apps without closing it, it could crash in the background.

[crashes.txt](https://github.com/koreader/koreader/files/7963548/crashes.txt)

**Comment by NiLuJe** [comment]
Does is happen wit the AutoStandby plugin disabled?

If it still does, I wouldn't mind verbose debug logs (Tools > Morer tools > Developer options; in the FM).

**Comment by NiLuJe** [comment]
(And another xref: https://www.mobileread.com/forums/showpost.php?p=4201443&postcount=424)

**Comment by Danar435** [comment]
I'll try disabling autostandby. In the meantime, I should say that I haven't experienced crashes in a while. Instead sometimes while reading, the screen would just register ghost inputs at the bottom left, which remain even in the pocketbook's home screen. A temporary fix is to lock the screen or to restart KOReader. 

I think the same ghost inputs were happening shortly before KOReader crashed. It may be "Touch event timestamps appear to use CLOCK_REALTIME" or "(GetTouchInfoI)NO TOUCH INFO!!! index = 0" from the logs. Also I should mention that I'm using the hack from #4831 to keep my library clean (there should be an option for that), not sure if that affects anything...

**Comment by liberodark** [comment]
Send my crash log here from PB 741.
PS on PB 740 don't have crash
[crash.log](https://github.com/koreader/koreader/files/8193834/crash.log)
.

**Comment by svkytbsld** [comment]
After 2022.02, KOReader has started quitting spontaneously in the middle of reading pdfs. I annotate a lot. So, all my annotations have become lost. It is very annoying. It happens about in 10-15 minutes later after I open the file. The device is Inkpad 3 and here is the last lines of latest crash log.

```
03/10/22-23:27:34 INFO opening file /mnt/ext1/Kitaplar/Oktar Türel Küresel Tarihçe 1945-79 Yordam Kitap-2.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
03/10/22-23:27:34 INFO Loading plugins from directory: plugins
ffi.load: sqlite3
03/10/22-23:27:35 WARN Error when loading plugins/terminal.koplugin/main.lua
03/10/22-23:27:35 INFO setting zoom mode to contentwidth
```

I posted on mobileread and NiLuJe advice me to send verbose debug logs I did what s/he said but I don't know if I did it correctly. Here is the crash log after activate verbose debug log
[crash.log](https://github.com/koreader/koreader/files/8231903/crash.log)

**Comment by rjd22** [comment]
Can you check if this is still an issue with the latest version? It might be fixed now.

**Comment by rjd22** [comment]
Closing this because of no followup. If you feel this is still an issue please tell me and I wl reopen.
