### ISSUE TITLE
Charging percentage change per hour always shows 0.00 since last update (12.2021)

### ISSUE THREAD

**Issue by jonnyl2** [koreader/koreader#8644]
* KOReader version:  koreader-android-arm-v2021.12.1
* Device: Likebook Mars

Even though the necessary data (e.g., charged/used time, percentage added/used) is collected correctly, the corresponding rate per hour always shows 0.00%. This issue has appeared with the latest update (12.2021).

Example screenshot attached.

Of course this is just a minor issue and I thank you all for this outstanding piece of software.

Thanks.
![IMG_20220110](https://user-images.githubusercontent.com/95502269/148830527-9b4c28dc-9773-49d4-8dc4-71879a2a57d4.jpg)

**Comment by hius07** [comment]
Fixed in https://github.com/koreader/koreader/pull/8582.
