### ISSUE TITLE
Night mode period

### ISSUE THREAD

**Issue by Timalex** [koreader/koreader#866]
A time period specifies when night mode should automatically set.

Initially this could even be set automatically.
Say night mode was activated at 22:05 for an _extended_ period while reading (detected by page flip activity). The next day night mode is activated at the same time automatically.

Taking it much further it would follow the day-light cycle like flux.

Just some inspiration, there are probably better ways to implement. 

Another thing to note is that Night Mode (great feature btw) should be more consistently dark to avoid light flickering. I use it to not disturb my partner at night, she have noticed the flickering.

**Comment by arooni** [comment]
Would love to see this happen .. :)

**Comment by Frenzie** [comment]
Something a bit like that is implemented on devices with "natural" light.

**Comment by arooni** [comment]
I wanted to buy a kobo forma but all I could afford was a kindle paperwhite lol...
