### ISSUE TITLE
warm light control in kindle oasis 3

### ISSUE THREAD

**Issue by catalystsitaly** [koreader/koreader#8661]
there is no warmth control in the front light control menu of koreader in kindle oasis3

**Comment by Frenzie** [comment]
That means @NiLuJe's comment here from https://github.com/koreader/koreader/pull/7446 was unfortunately correct. :-)
https://github.com/koreader/koreader/blob/958077364a099f5dd07b23bbc95ad76e09dc5e99/frontend/device/kindle/device.lua#L798-L800

**Comment by catalystsitaly** [comment]
> That means @NiLuJe's comment here from #7446 was unfortunately correct. :-)
> 
> https://github.com/koreader/koreader/blob/958077364a099f5dd07b23bbc95ad76e09dc5e99/frontend/device/kindle/device.lua#L798-L800

Is there a way that I can adjust warm light direct in koreader? thanks in advance

**Comment by Frenzie** [comment]
After someone straces it (or maybe something much easier). It just means it's different than the Oasis 2.

**Comment by catalystsitaly** [comment]
> 

yes, the only difference is that Oasis3 add some warm lights , which need a seperete control panel

**Comment by slimpdev** [comment]
Hello. I make it https://github.com/koreader/koreader/pull/9047

**Comment by catalystsitaly** [comment]
> Hello. I make it #9047

thanks it's perfect
