### ISSUE TITLE
Leading spaces are omissed in a td element

### ISSUE THREAD

**Issue by bunglegrind** [koreader/koreader#8662]
* KOReader version: 2021.12.1

* Device: KOBO Aura One

#### Issue
It looks like KOReader is trimming leading spaces which are used to indent code. See the example in the file attached. The page is formatted as a table (it's taken from a github gist btw).

[test.zip](https://github.com/koreader/koreader/files/7863694/test.zip)

#### Steps to reproduce
1. Rename test.zip in test.epub;
2. Open with KOReader
3. The (JSX) tag are not indented, but if you inspect pages/test.xhtml you'll see they actually are.

**Comment by poire-z** [comment]
A bit unclear just giving this test file, and not showing how some other reader/browser renders it and how you expect it to look, or at least which bit in the table you expect indented - so, assuming you mean these second TD in each TR:
```html
        <tr class="Iz29">
          <td class="As30"></td>
          <td class="As30"><span class="Tj32">const</span> <span class="Tj32">WrappedComponent</span> <span class="Tj32">=</span> <span class="Tj32">(</span>...<span class="Tj32">props</span><span class="Tj32">)</span> <span class="Tj32">=&gt;</span> <span class="Tj32">(</span></td>
        </tr>
        <tr class="Iz29">
          <td class="As30"></td>
          <td class="As30">  <span class="Tj32">&lt;</span><span class="Tj32">EnvProvider</span> <span class="Tj32">{</span> ...<span class="Tj32">props</span> <span class="Tj32">}</span><span class="Tj32">&gt;</span></td>
        </tr>
        <tr class="Iz29">
          <td class="As30"></td>
          <td class="As30">    <span class="Tj32">&lt;</span><span class="Tj32">AuthProvider</span><span class="Tj32">&gt;</span></td>
        </tr>
        <tr class="Iz29">
          <td class="As30"></td>
          <td class="As30">      <span class="Tj32">&lt;</span><span class="Tj32">LoaderProvider</span><span class="Tj32">&gt;</span></td>
        </tr>
```


Looks like KOReader trims them just as any other browser you would give your text.xhtml + style11087.css.
Firefox:
![image](https://user-images.githubusercontent.com/24273478/149363790-06935b9a-0c03-48fd-989e-28cbad737b2b.png)

The HTML specs say (my simplified wording :):
- White spaces at start of end of a text in a block node (like TD) are trimmed, but kept in inline nodes (like SPAN)
- Consecutive white spaces collapse into a single one.
- Remaining collapsed-single white space at start of end of a text node may not be rendered if at start of end of paragraph
- Unless `<PRE>` is used, or some CSS associates to the TD or its inner-content: `white-space: pre`

And looking at the messy CSS, there is indeed nothing of that.
So, we do as told: no indentation preserved.

So, the publisher, or the thing that crawled this github gist and made an EPUB from it, did not specify to keep this indentation, or missed grabbing the thing that does.
But you can help yourself with a book style tweak:
```css
td { white-space: pre; }
   or
td.As30 { white-space: pre; }
```
![image](https://user-images.githubusercontent.com/24273478/149364814-672b9a8d-c08c-472a-8c75-06bce029b608.png)

**Comment by Frenzie** [comment]
For the record, that's what GitHub Gist does too. (With a `.blob-code-inner{white-space:pre}`.)

**Comment by bunglegrind** [comment]
Sorry guys, you're right. I was mislead by the browser representation of the content (the grabber is a browser extension) after the exporting, which is not exactly (but I wasn't aware till now) based on the same css files...

**Comment by poire-z** [comment]
Btw, as I see you've been hacking save-as-ebook, I did some work 2 years ago - not updated/synced since, works for me as good as I want it with KOReader: 
`https://github.com/alexadam/save-as-ebook/pull/33#issuecomment-523331268`
https://github.com/poire-z/save-as-ebook/commits/my_mods
