### ISSUE TITLE
Kobo Libra 2: word highlit stays longer after closing dictionary window

### ISSUE THREAD

**Issue by mandarancza** [koreader/koreader#8664]
* KOReader version: 2021.12.1
* Device: Kobo Libra 2

#### Issue:
I recently upgraded to Libra 2 from Libra H2O and I have immediately noticed that after selecting a word for a dictionary lookup and then closing the dictionary window, the highlited word stays selected (grey background) for much longer on Libra 2. On H2O the word unhighlits immediately but on Libra 2 it takes around 2 seconds. I know it's not very much but it really is irritating after I got used to to the old device. I don't really know if it's a bug or more like a feature of this particular device and it's optimization, but if it could be addressed, it would be fantastic. 

#### Steps to reproduce:
Just highlit a word and then close the dictionary window.

**Comment by poire-z** [comment]
- It's hardcoded to be scheduled and done 0.5s after closing the dict window.
- in the meantime, the eInk screen is refreshed to draw the content + the highlight remaining without the dict window: this may take some excessive time on the Libra2 ?!
- then, after this is done, the 0.5s or 0s remaining has elapsed and:
- the eInk screen is refreshed to draw the content without the highlight: this may take some excessive time on the Libra2 ?!

Do you experience other slow drawing on the Libra2 ? Like slow page turns, slow File browser page turns, slow dict result scroll.... ?

**Comment by mandarancza** [comment]
> * It's hardcoded to be scheduled and done 0.5s after closing the dict window.
> * in the meantime, the eInk screen is refreshed to draw the content + the highlight remaining without the dict window: this may take some excessive time on the Libra2 ?!
> * then, after this is done, the 0.5s or 0s remaining has elapsed and:
> * the eInk screen is refreshed to draw the content without the highlight: this may take some excessive time on the Libra2 ?!
> 
> Do you experience other slow drawing on the Libra2 ? Like slow page turns, slow File browser page turns, slow dict result scroll.... ?

Now that I compared it side by side, the newer model is not much worse, though it is a little slower. I think it's due to a different way the screen refreshes. I guess this problem is just my nitpicking.

Also the libra 2 is not slower, but I do have some problems with lagging. The screen sometimes freezes when I try to flip a page and I have to wait a few seconds.
