### ISSUE TITLE
FM: Refresh content not working

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#8665]
* KOReader version: 2021.12.01
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
“Refresh content” stopped working in FM. I used it with a swipe gesture. What happened before was that an info message appeared with something like “File contents were refreshed” and most importantly metadata was immediately updated. Useful when I overwrite books with new metadata over SSH and then refresh contents to see if the update was good.

**Comment by hius07** [comment]
Infomessage was removed in https://github.com/koreader/koreader/pull/8330. The refresh itself must work.
Please check if you have assigned an action to your gesture in Gesture Manager: `File browser` - `Refresh content`.

**Comment by mergen3107** [comment]
@hius07 
Ah, OK! 

Sorry, my bad. I double checked the issue and the refresh itself works. It just turns out that the Refresh didn't update the metadata before (like series numbers).

**Comment by mergen3107** [comment]
Thank you @hius07 !
