### ISSUE TITLE
Koreader on macOS crashes when opening books (M1 and Intel Macs)

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#8686]
* KOReader version: 2022.01-2
* Device: macOS 12.1

#### Issue

Koreader crashes with a bus error when opening a book

#### Steps to reproduce

Launch koreader
Open an epub (not sure about other formats)

crash.log attached
[crash.log](https://github.com/koreader/koreader/files/7892159/crash.log)

**Comment by Frenzie** [comment]
Hm, that's certainly not very informative.
```
zsh: bus error  ./KOReader.app/Contents/MacOS/koreader
```

**Comment by NiLuJe** [comment]
Did the CI build env change recently? (xcode updates breaking stuff is not entirely uncommon...).

**Comment by Frenzie** [comment]
There was https://github.com/koreader/koreader/pull/8525

Maybe @sayomelu has an idea.

**Comment by sayomelu** [comment]
sorry, i only do the ci/cl, and knowing nothing about lua. i just follow the [doc/Building.md](https://github.com/koreader/koreader/blob/master/doc/Building.md#macos)

**Comment by pazos** [comment]
It seems that LuaJIT, when built with certain Clang/LLVM toolchains, can cause a SIGBUG when an error is raised.

If that's the case it should be trivial to test. Just replace the contents of `reader.lua` (within the app bundle) with:

```lua
error("this is an error")
```

and call the binary in app bundle from the terminal app. It should produce the same error.

**Comment by Frenzie** [comment]
@sayomelu But you don't see the same issue when you run it, right?

**Comment by JasonInOttawa** [comment]
To clarify, I downloaded the macOS artifact from the most recent Action which had the master tag next to it. I didn't build koreader.

**Comment by pazos** [comment]
@JasonInOttawa: could you try https://github.com/koreader/koreader/issues/8686#issuecomment-1016574893 and report if it still crashes the same way?.

**Comment by NiLuJe** [comment]
Oh, right, there were iOS/Apple thingies happening recently in LuaJIT master re: frame unwinding.

We might want to bump LuaJIT, too ;).

**Comment by JasonInOttawa** [comment]
@pazos: I might need a little more instruction :) When I replace the content of reader.lua with what's in your comment (see attached) I get this:

```
./KOReader.app/Contents/MacOS/koreader 
failed to run lua chunk: reader.lua:1: this is an error
```
Thanks,
Jason
[reader.lua.txt](https://github.com/koreader/koreader/files/7900381/reader.lua.txt)

**Comment by JasonInOttawa** [comment]
I'm afraid there's still a crash in macOS (Segmentation Fault now)

Version 2022-01.45


```
% Desktop/KOReader.app/Contents/MacOS/koreader 
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 01/25/22-09:50:01
 [*] Version: v2022.01-45-g21932c24_2022-01-25

ffi.load: blitbuffer
ffi.load (assisted searchpath): ./libs/libblitbuffer.so
ffi.load: libs/libSDL2.dylib
ffi.load: SDL2
Starting SDL in /Users/jason/Desktop/KOReader.app/
SDL: no gamecontrollers connected
ffi.load: libs/liblodepng.dylib
01/25/22-09:50:02 INFO  initializing for device Mac OS X
01/25/22-09:50:02 INFO  framebuffer resolution: {
    ["w"] = 547,
    ["h"] = 676,
}
ffi.load: libs/libmupdf.dylib
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.6.dylib
ffi.load: libs/libharfbuzz.0.dylib
ffi.load: libs/libzstd.1.dylib
ffi.load: libs/libutf8proc.2.dylib
01/25/22-09:50:02 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
01/25/22-09:50:03 INFO  Loading plugins from directory: /Users/jason/Library/Application Support/koreader/plugins/
01/25/22-09:50:04 INFO  GestureDetector:probeClockSource: Touch event clock source detection was inconclusive
01/25/22-09:50:20 INFO  opening file /Users/jason/Documents/Books/file.epub
zsh: segmentation fault  Desktop/KOReader.app/Contents/MacOS/koreader
```

**Comment by JasonInOttawa** [comment]
Actually, I guess I need to wait for a "base bump", right? :)

**Comment by NiLuJe** [comment]
You should be able to get a backtrace of that one, though, and it might be slightly more accurate than after a SIGBUS ;).

**Comment by JasonInOttawa** [comment]
Is the attached helpful?
[koreader-2022-01-25-100041.ips.txt](https://github.com/koreader/koreader/files/7936439/koreader-2022-01-25-100041.ips.txt)

**Comment by JasonInOttawa** [comment]
Is the attac
[log.txt](https://github.com/koreader/koreader/files/7936580/log.txt)
hed helpful?

**Comment by NiLuJe** [comment]
Possibly, although we'd get more details out of a debug build ;).

It appears to be crashing on a CRe alloc, ping @poire-z if that rings a bell.

Fair warning: this is running through Rosetta on an aarch64 mac, so, that's an extra layer of magic involved ;).

**Comment by poire-z** [comment]
Mhhh, not enough info for me to say anything.
Try starting with a PDF ? :) or with File browser.
Does it happen with any EPUB or only a specific one ?
Share this "file.epub" ?

**Comment by JasonInOttawa** [comment]
I've seen the crash happen with several EPUBs.

PDFs are a bit interesting - things seem to work fine (I can open the PDF, and close it back to the file browser) and the Koreader window doesn't close, but I get a "koreader quit unexpectedly" window open alongside. The Koreader window does not close. 

Attached is a copy of the "Problem Report" (log.txt). I've seen this with a couple of PDFs.

I only see the (bogus?) Problem Report window if I launch koreader by double-clicking it - when I run it in Terminal, open a PDF and go back Home, I don't see that behaviour.

[log.txt](https://github.com/koreader/koreader/files/7946035/log.txt)

**Comment by JasonInOttawa** [comment]
I was trying to get a screenshot of the koreader and problem report windows up at the same time, but now I can't duplicate it!  :)

**Comment by JasonInOttawa** [comment]
The crash on closing a PDF while the koreader main window stays open happened again

<img width="894" alt="Screen Shot 2022-02-17 at 2 44 18 PM" src="https://user-images.githubusercontent.com/46451014/154558795-b1d20d7f-8397-4ca5-b32a-4f4395e54284.png">

**Comment by JasonInOttawa** [comment]
I'm seeing a crash on book open on an Intel Mac too. Attached is the crash log. Sadly not very helpful - just shows a segmentation fault

This happened with several books.

[crash.log](https://github.com/koreader/koreader/files/8982482/crash.log)
.

**Comment by JasonInOttawa** [comment]
Attached is the thread crash report

[crash_report.log](https://github.com/koreader/koreader/files/8982491/crash_report.log)

**Comment by JasonInOttawa** [comment]
As on the M1 Mac, there seems to be a crash in crengine. 

```
VM Region Info: 0x7200000047 is not in any region.  Bytes after previous region: 489203802184  Bytes before following region: 105063489994681
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      __LINKEDIT                   19276000-192e6000     [  448K] r--/rwx SM=COW  ...rengine.dylib
--->  GAP OF 0x5fffe6d1a000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libcrengine.dylib                           0x18f4a047 lstring32_chunk_t::alloc() + 471

```

**Comment by poire-z** [comment]
These crash report are not really helpful.
Any other device than Mac you can reproduce the crash on with these books?

Btw, did your previous reports above get fixed/no longer happened at some point ?

**Comment by pazos** [comment]
As far as I am concerned I would be very happy to remove all support for macOS (besides the emulator).

Because:

1. Their aarch64 is not generic.
2. Their SDK breaks stuff randomly.
3. We don't have an "official" release yet.
4. They're incredible hostile to builders outside XCode and their "environment"
5. You need a mac to do mac stuff. If you build outside xcode and their `lipo` facility you need both an `x86_64` and an `arm64le`one.
6. The `brew` package manager just supports a couple of latest versions, making impossible to keep a good-old build environment (based on github actions because `6`) that makes posible to deal with `2` and `4`.

I'm very sorry for adding support for macOS. I should kept it private.

Removing "support" for mac only includes removing github actions and a couple of wiki/doc entries. The rest can stay as is. Someday, somebody might want to tackle the duty of dealing with apple nonsense and all the frontend code is in good shape for all of this.

Just my two cents.

**Comment by Frenzie** [comment]
The GitHub Action is pretty hidden. In fact it's nigh impossible to find the artifacts it generates. So I wouldn't necessarily remove that (although combined with the aforementioned random breaking it's hanging by a pretty thin wire; seeing a red x at random for no reason is annoying at best).

**Comment by JasonInOttawa** [comment]
Unfortunately I haven't had luck fixing my earlier issues. I was hoping to get through a macos release build but never could. If there isn't any interest in maintaining the macos version, please feel free to close these.

**Comment by pazos** [comment]
> If there isn't any interest in maintaining the macos version, please feel free to close these.

I wouldn't say there's no interest. It just happens it is the only platform I know where new stuff breaks old code without us touching a single line. I still have an "El Capitan" VM somewhere that's able to produce working versions of KOReader from 10.09 (With XCode 9 or 10, I don't remember). Or was able the last time I checked, more than a year ago.

If we could, legally, have one build environment like we have for all the rest of the platforms, it should be easier to triage bugs. With the current state of affairs we don't know if this is a hidden bug in CREngine that can be only triggered when building with XCode version X, CLang version Y on macOS version Z or is just X,Y & Z by themselves :/

The issue is ok opened, IMO, as it can catch more eyes but I'm afraid new bug reports that cannot be reproduced elsewhere are left in the void.

> Unfortunately I haven't had luck fixing my earlier issues. I was hoping to get through a macos release build but never could.

I updated my work machine from an Intel Macbook to an M1. Still no interest in tackling the apple thing but some day I will play with virtualizing a debian aarch64 to be able to build the emulator natively outside x86_64. That would be far, far in the future.

**Comment by JasonInOttawa** [comment]
Thanks very much. Trying an older version of macOS and XCode in a virtual machine is a good idea - I'll try it out with (say) Mojave and see if I can build and run the application.

**Comment by pazos** [comment]
Hi, sadly it won't be easy because  

> The brew package manager just supports a couple of latest versions, making impossible to keep a good-old build environment

Currently docs say Catalina or higher but 10.11-10.14 are supported on best-effort basis: https://docs.brew.sh/Installation

But if you're able to install brew dependencies and export a valid MACOSX_DEPLOYMENT_TARGET you shouldn't have any issue to build for intel macs.

**Comment by JasonInOttawa** [comment]
@pazos You are correct - I couldn't get the brew dependencies set up in Mojave. 

I borrowed an Intel Mac, and the KOReader.app built there runs just fine, including on an M1 Mac. The Intel Mac is running current macOS and XCode. 

The "Actions" artifacts run on the Intel Mac as well as on the M1 Mac, but crash when opening a book. I guess the issue is in the build on github.

I feel we can close this issue, and perhaps leave #8797 open, in order to track any progress made in changing the build procedure so it can successfully run on an M1 Mac.

Thanks to everyone for your help!

**Comment by pazos** [comment]
> @pazos You are correct - I couldn't get the brew dependencies set up in Mojave.
> 
> I borrowed an Intel Mac, and the KOReader.app built there runs just fine, including on an M1 Mac. The Intel Mac is running current macOS and XCode.
> 
> The "Actions" artifacts run on the Intel Mac as well as on the M1 Mac, but crash when opening a book. I guess the issue is in the build on github.
> 
> I feel we can close this issue, and perhaps leave #8797 open, in order to track any progress made in changing the build procedure so it can successfully run on an M1 Mac.
> 
> Thanks to everyone for your help!

Thanks for the feedback!

Could you check if the app in https://github.com/koreader/koreader/actions/runs/2601343246 works as well?. It was built using Monterey.

**Comment by JasonInOttawa** [comment]
@pazos I just tried the artifact in the action from your comment and it crashes on my M1 Mac on book open. The stack trace is attached. 

Thanks!

[problem_report.log](https://github.com/koreader/koreader/files/9033603/problem_report.log)

**Comment by pazos** [comment]
@JasonInOttawa: try [this one bullt with catalina](https://github.com/koreader/koreader/actions/runs/2602646252). If that doesn't work I'm out :p

**Comment by JasonInOttawa** [comment]
@pazos It worked!

**Comment by pazos** [comment]
No way!!!

Seriously?

Or are you trying to prevent https://github.com/koreader/koreader/pull/9279#issuecomment-1172951546?

**Comment by JasonInOttawa** [comment]
I downloaded the artifact associated with your action, unzipped it, ran the resulting KOReader app, and opened a book. No crash.

**Comment by tsao-chi** [comment]
> @JasonInOttawa: try [this one bullt with catalina](https://github.com/koreader/koreader/actions/runs/2602646252). If that doesn't work I'm out :p

I can confirm that it work on m1 mac mini

**Comment by JasonInOttawa** [comment]
@tsao-chi Just to confirm, I downloaded the artifact produced by #9279 and it works on my M1 Mac

**Comment by NiLuJe** [comment]
The 10.15 runner is going the way of the dodo: https://github.com/actions/runner-images/issues/5583
