### ISSUE TITLE
Battery Statistics plugin shows wrong remaining time 

### ISSUE THREAD

**Issue by nerdboy4200** [koreader/koreader#8687]
* KOReader version: 2022.01
* Device: Kobo (two different generations)

#### Issue
We upgraded the Kobos from 2021.12.1 to 2022.01 and when we look at the Battery Statistics plugin - the since lst charge - estimated remaining time appears off.

#### Steps to reproduce
* setup koreader on something where you can get battery statistics version 2021.12.1 or earlier
* Look at the battery statistics plugin - specifically "Since Last Charge" -> "Estimated remaining time" - in my case - it was something like 76 days (a bit of a stretch - but I had just charged it a day or so ago - so its a bit creative)
* Upgrade to 2022.01
* Notice that it now shows something like 3 hours.

##### Added in
* c7715aa7d54c0ebafd059faabd86e8cd58891148

##### The specific fix
This is the current line:
``` 
       return 3600 * self.percentage / self.time
```
it needs to be changed to this:
```
        return self.percentage / self.time
```

##### Information on this
The newer KOBO was showing that for about 23 hours of usage and 9 % of battery used - there should be about 8.625 days of time left - which is (23 * 9)/24 - but due to the 3600 multiplier in that statement - the time was only abour 3 minutes or so.

I think that this issue is a bit bigger than just this one change... but I do not know what else needs to be done - you might need to apply that 3600 into the percentage calculations differently.

**Comment by nerdboy4200** [comment]
I should note that this fixed the time in one of the cases that we know of was affected. I am wondering if that 3600 multiplier needs to be put in when its working out the values for the percentage - not for the time.

**Comment by hius07** [comment]
Closed in https://github.com/koreader/koreader/pull/8688 and https://github.com/koreader/koreader/pull/8694.
