### ISSUE TITLE
How to do a short scroll?

### ISSUE THREAD

**Issue by potash** [koreader/koreader#8689]
I'm on an e-ink device (kobo aura one) and sometimes I'd like to scroll a shorter length than the default. For example in a PDF (in continuous or page mode) an image/figure might start at the bottom of the screen and get cut off. If I scroll once (taking the right side of the screen) I'll see the bottom of the figure but not the top. What I'd like is to scroll a short distance to see the whole figure. Is there a way to do this? Thanks!

**Comment by Frenzie** [comment]
It's a little more awkward, but you can "drag" the document around in a similar manner as on a phone (provided scroll mode is enabled in the bottom menu).

**Comment by potash** [comment]
Thanks I seem to remember dragging working at some previous version but it has not worked for me for some time. How can I debug this? Is it possible that my gesture configuration conflicts with it? ---- On Wed, 19 Jan 2022 03:40:24 -0500  ***@***.***  wrote ----
It's a little more awkward, but you can "drag" the document around in a similar manner as on a phone (provided scroll mode is enabled in the bottom menu).

**Comment by Frenzie** [comment]
The gesture configurations are for various types of swipes. Panning can't be configured.

Panning is a lot like a swipe, except you don't let go. On the Kobo Aura One it should work perfectly acceptably afaik.

**Comment by NiLuJe** [comment]
We do have different scroll behaviors available in PDF since...this summer, IIRC?

**Comment by poire-z** [comment]
The finger distance still needs to go over some "pan threshold" (not configurable ? can't find it).
So, for scrolling a distance smaller than that, I guess one can scroll in one direction, and then (without releasing finger) scroll in the other direction by a bit less or a bit more ?

**Comment by potash** [comment]
Thanks for clarifying, I didn't know about about not letting go. It
works!

**Comment by yparitcher** [comment]
> So, for scrolling a distance smaller than that, I guess one can scroll in one direction, and then (without releasing finger) scroll in the other direction by a bit less or a bit more ?

yup

**Comment by yparitcher** [comment]
> The finger distance still needs to go over some "pan threshold" (not configurable ? can't find it).

`gear -> Taps and Gestures -> gesture intervals -> Swipe interval`
