### ISSUE TITLE
reMarkable 2.11.0442, the middle button not working again

### ISSUE THREAD

**Issue by zcy85611** [koreader/koreader#8691]
* KOReader version: 2022.01
* Device: reMarkable1

#### Issue
Middle button not working

could some test it please? I followed wiki instruction but not working

**Comment by VioletVivirand** [comment]
Middle button not working for me either, confirmed.

* Device: reMarkable 1
* reMarkable firmware version: `2.12.2.573`
* KOReader version: `2022.05.1`

**Comment by poire-z** [comment]
So, this issue can be closed ?

@VioletVivirand : I see your are from/in Taiwan. Are you familiar with reading Traditional Chinese, and its expected typography (speficifally, how TC centered punctuation glyphs get adjusted and their expected spacing, and how consecutive punctuations/quotes/brackets are handled) ? If yes, I may ask you some questions in #6162 . If no, do you have some modern quality books or magazines around still using Traditional Chinese punctuations that could you take and share some photos (of pages exhibiting what I mention above)? Thanks.
