### ISSUE TITLE
Not function - Dropbox create folder and upload file

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#8697]
* KOReader version: 2022.01
* Device: kindle ppw4, nook glowlight plus 7.8"

#### Issue
Ver 2022.01 introduce new function for dropbox cloud storage, however I couldn't create new folder or upload file to dropbox with both 02 of my devices.

My intention is to export my highlight to html format , upload to dropbox then import to Notejoy.com so I can easily view it on my phone ( I have issue in making Joplin work, and joplin need a computer in between so I prefer my current approach)

Please kindly take a look. Thank you.

**Comment by hius07** [comment]
At first, can you go to your Dropbox App Console
https://www.dropbox.com/developers/apps
choose the app created, and check the second tab Permissions

![1](https://user-images.githubusercontent.com/62179190/150292846-3d696351-f95c-485a-83cc-c2e66d27baa1.jpg)

**Comment by uphantom89** [comment]
I did check those box as your instruction, however, plugin still didn't allow me to create folder or upload file

**Comment by uphantom89** [comment]
![Screenshot_20220120-191638](https://user-images.githubusercontent.com/27908681/150337174-075b4211-ab54-4816-9bc6-258f632a5469.png)

**Comment by hius07** [comment]
Are there any warnings in the crash.log?
https://github.com/koreader/koreader/blob/7783d9c8e37099fa2e138d660dc76ed4ec5257ca/frontend/apps/cloudstorage/dropboxapi.lua#L124-L126

**Comment by uphantom89** [comment]
![20220120_200326_HDR](https://user-images.githubusercontent.com/27908681/150344251-5138611c-f5c3-4c6c-90e8-4f035fc4ac90.jpg)

**Comment by uphantom89** [comment]
Message box show this, may I ask the location to get the crash.log.
Btw, it just couldn't upload, Koreader still funtioned, no crash.

**Comment by hius07** [comment]
> the location to get the crash.log

mnt/us/koreader/crash.log

**Comment by uphantom89** [comment]
![20220120_201912](https://user-images.githubusercontent.com/27908681/150346541-a77937e5-b707-47d7-89fe-24a28095df8e.jpg)
![20220120_201918](https://user-images.githubusercontent.com/27908681/150346550-bdc6bc91-14c3-4b32-b5f1-d5a1932a9f39.jpg)

**Comment by uphantom89** [comment]
Here is the latest crash log page

**Comment by hius07** [comment]
That's something related to your token and permissions.

_401 - Unauthorized
These errors are due to the bearer token of the associated request being invalid, expired, or lacking sufficient permission to perform the associated API call. These may also be due to temporary suspension, such as an administrator suspending a member within a Dropbox business team._
https://developers.dropbox.com/error-handling-guide

**Comment by uphantom89** [comment]
Let me try another token if it can solve the issue. Thank you very much in advance

**Comment by uphantom89** [comment]
It worked. Thank you!
