### ISSUE TITLE
FR: Docs/help for own hyphenation rules – rather confused about complexity

### ISSUE THREAD

**Issue by Moonbase59** [koreader/koreader#8706]
**Does your feature request involve difficulty completing a task? Please describe.**
Since available hyphenator patterns are all rather old, I created current ones from Dante e.V.’s German wordlist, plus a few minor additions/corrections. I ended up with (3/3) `hyph_de.dic` and `de.js` (for _Hyphenator_) files which seem to be _standard formats recognized by many readers_, and these actually work beautifully on readers like the _Tolinos_. Just drop into a folder and voilà.

Of course I expected this to be as easy with KOReader, but after searching and reading old issues for hours now, I’m more confused than happy. It seems user @zwim has worked on the same stuff (and from the same sources), ending up with a lot of scripts and "after.update" stuff I don’t understand without delving deep into the code.

Why can’t KOReader just use a standard `hyph_xx.dic` file, simply dropped into a `koreader` subfolder, like it works with fonts, for instance? (And why would one have to consider special KOReader versions like "rocks"?)

Also, I could not find any _documentation_ of (or the _files_) things like `German.pattern`. If there is a need to use yet another hyphenation dictionary format, where is the documentation on how it should look like?

**Describe the solution you'd like**
**Support of "just dropping" a standard format hyphenation dictionary into a user folder**, without the need of messing with scripts and Android (or other OS’) system folders.

Somewhere was mentioned "You might be the only user who wants that" (addressed at @zwim). Let me assure you that is _not_ so. For the Tolinos alone, _many_ are already now using my new German hyphenation rules, and pretty happy with these. It seems KOReader evolves to be a noted reader for many reading devices now, so of course replacing/adding hyphenation rules should also be easy for users.

**Describe alternatives you've considered**
Using the built-in German hyphenation. Trying the scripts but to no avail since I lack a properly KOReader-formatted German pattern file.

**Additional context**

**Comment by Frenzie** [comment]
> Why can’t KOReader just use a standard hyph_xx.dic file, simply dropped into a koreader subfolder, like it works with fonts, for instance? (And why would one have to consider special KOReader versions like "rocks"?)

Part of the answer is that crengine predates MySpell/Hunspell .dic files becoming a standard around the late 2000s or early 2010s, another part is that it was written by Russian wizards who were squeezing the absolute maximum performance out of paltry mid-2000s hardware with design decisions that were almost always quite sensible but occasionally leave us scratching our heads. In some ways one of the latter, although like I said we should look at it in its contemporary context as well.

Additionally, it's important to note that there's a bit of an alternate universe over in Russia with widespread standards (such as FB2) that these pattern files are part of. Concretely, they're not some kind of unique crengine pattern files, but it's the widely supported (in Russia) [Alreader](http://alreader.kms.ru/) pattern file standard.

> (And why would one have to consider special KOReader versions like "rocks"?)

I don't think there's anything to consider there. It's just so that on Android you can install our flavor (rocks) side by side with the F-Droid flavor. Besides the signing key (i.e., ours vs F-Droid's) they're identical, except ours exposes a function to download nightly developer builds from within the program.

I'd also prefer to be able to just drop in LaTeX and/or Hunspell pattern files myself, but not nearly enough to undertake an involved rewrite of the relevant code. There's also the problem that Russians might have the exact opposite reaction. ;-)

**Comment by poire-z** [comment]
All the hyphenation work and discussion (that's all there is as documentation) has happened in:
https://github.com/koreader/crengine/issues?q=sort%3Aupdated-desc+hyphenation

We care about hyphenation, and our hyph dicts are not that old, they have been updated.
And the German hyphenation is curated by @zwim more than any other language : https://github.com/koreader/crengine/commits/master/cr3gui/data/hyph/German.pattern . If you're not satisfied with how our german hyphenation works, you should work on that with him (but if you worked from the same sources, it's possible our german hyphenation is just fine - and you're just stuck on trying to re-use some previous work of yours while it's already in :)

For the format, @Frenzie explained.

> (And why would one have to consider special KOReader versions like "rocks"?)

If you mean "rocks" as hardcoded/engraved in stone (and not the Android flavor name), it's not really our decision, but how it's done by crengine - we live with that, not worth spending time making it different.

For allowing _users_ to override the dicts we ship, it's complicated to implement, and it's not needed: our patterns are part of the rendering engine, and we care about them, we update them, and we may have tweaks for them to work with how crengine does it. So, there's no need to allow users to mess with them.

Now, we allow _developpers_ to override them - and they can just do that (drop your test files over the ones shipped, for testing, they will be reset with the shipped ones on next KOReader update) on anything but Android (but sane developpers don't let their life be a nightmare by using Android :).
So, for developpers with Android like @zwim, they allowed to help themselves with these ugly update scripts - so they can test their work on the pattern files while reading for some time on their devices.

> Somewhere was mentioned "You might be the only user who wants that" (addressed at @zwim). 

I think that was about the "user hyphenation" feature, which is not "hyphenation dict replacement by the user". It's about fixing individual words hyphenation via KOReader UI, and injecting/merging dynamically these small corrections into crengine's regular hyphenation rules loaded from the pattern files.

**Comment by Moonbase59** [comment]
Ah, ok, thanks for the explanations! I’ll read up on the mentioned links. Maybe there is a way to collaborate with @zwim or just write a script that generates an updated `German.pattern` file from my data (or the `hyph_de.dic`). My main dictionary is for reformed German spelling but I also have variants for traditional spelling and Swiss German.

And yes, I meant the Android flavour with "rocks"—read about that in the issues here. Supposedly, this is what one gets when downloading from here (or the koreader.rocks site)? Then I use that.

**Comment by Moonbase59** [comment]
Another question: Looking at the `.pattern` files, I see that all "word boundary dot" occurences from the original pattern files have been blindly replaced by a space. Does your hyphenator not understand the dot "." as a word boundary in a pattern?

Rationale: We have a lot of word boundaries that are _not_ spaces, I had to add a lot of extra patterns to cater for these in my version, like

- U+002D - HYPHEN-MINUS
- U+0027 ' APOSTROPHE
- U+2013 – EN DASH
- U+2014 — EM DASH
- U+2019 ’ RIGHT SINGLE QUOTATION MARK
- U+002C , COMMA
- U+003B ; SEMICOLON
- U+003A : COLON
- U+0021 ! EXCLAMATION MARK
- U+003F ? QUESTION MARK
- U+0028 ( LEFT PARENTHESIS
- U+0029 ) RIGHT PARENTHESIS
- U+005B [ LEFT SQUARE BRACKET
- U+005D ] RIGHT SQUARE BRACKET
- U+007B { LEFT CURLY BRACKET
- U+007D } RIGHT CURLY BRACKET
- U+003D = EQUALS SIGN
- U+201E „ DOUBLE LOW-9 QUOTATION MARK
- U+201C “ LEFT DOUBLE QUOTATION MARK
- U+201D ” RIGHT DOUBLE QUOTATION MARK
- U+201A ‚ SINGLE LOW-9 QUOTATION MARK
- U+2018 ‘ LEFT SINGLE QUOTATION MARK
- U+2019 ’ RIGHT SINGLE QUOTATION MARK
- U+00BB » RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
- U+00AB « LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
- U+203A › SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
- U+2039 ‹ SINGLE LEFT-POINTING ANGLE QUOTATION MARK

**Comment by zwim** [comment]
@Moonbase59 As soon as I am at home (thursday), I can show you my script for generating the patterns out of http://projekte.dante.de/Trennmuster

**Comment by Moonbase59** [comment]
@poire-z: Good to know, thanks. So you are saying that, for instance, in the start of a sentence like `»Decomposition, as we mentioned, …«`, the word "Decomposition" is already isolated out of the surrounding characters `»` and `,`, and the hyphenator only ever sees `Decomposition` to work on? Are they also lowercased or not?

So if I made some dumb pattern like ` De3…` (with leading blank) it would actually _only_ catch it and hyphenate if the `De` was at the start, i.e. _not_ include the space?

If so, that would reduce the pattern file somewhat.

@zwim: Great, looking forward to that. Looks easy enough though, but automating things is always good. And using the same tools. I quite like that we independently arrived at the same solution, so there must be something to it. :-)

Maybe we could even `diff` or `wortliste` files, to arrive at a better solution for everyone. I could then issue new `hyph_de.dic` and `de.js` versions while you could care about the patterns being included in KOReader, maybe?

Great to know that there seemingly already _is_ a reader that does good German hyphenation! Dante e.V. did great work publishing their wordlist and tool chain, cheers to them.

**Comment by poire-z** [comment]
> So you are saying that, for instance, in the start of a sentence like »Decomposition, as we mentioned, …«, the word "Decomposition" is already isolated out of the surrounding characters » and ,, and the hyphenator only ever sees Decomposition to work on? Are they also lowercased or not?

Right, and yes, they are lowercased - so all our patterns need to be only lowercase.

> So if I made some dumb pattern like De3… (with leading blank) it would actually only catch it and hyphenate if the De was at the start, i.e. not include the space?

Right.
(Actually, the code gets the word isolated and without spaces - and add itself a space at start and a space at end, before matching patterns - that's why patterns with leading spaces will match isolated word once they get these pre- and post- spaces.)

> If so, that would reduce the pattern file somewhat.

Clever russian engineering :)

**Comment by zwim** [comment]
@Moonbase59 Here we go: First I summarize some things. At the end I will go a bit into detail.

KOReader uses `*.pattern` files for each language, which are hardcoded in crengine. These `pattern` files are almost TeX hyphenation pattern files `*.pat`. The only difference is, that the data is wrapped in an XML structure and the start and end of words are not a `.` but a ` `. These files are space efficient and the algorithm to find hyphenation is fast.

My previous work adds the possibility for an `user-XXX.hyph` file (XXX stands for the language, e.g. `user-German.hyph`), which may contain exceptions to the `pattern` provided by KOReader. Words in the `hyph` file overrides words in the `pattern` files.
The `hyhp` files are **not** space efficient, but the hyphenation is almost as fast as for `patterns`.

Additionally KOReader can honor soft hyphens.

---------------------------------
Details:

Detail about the `pat` files and the hyphenation algorithm can be found in: https://tug.org/docs/liang/liang-thesis.pdf

On an update of KOReader the `pattern` files get overwritten with our files. So be careful, when you change the `pattern` files.

On Android (Tolino) the first thing I added (with a lot of help) was the `script`mechanism (https://github.com/koreader/koreader/pull/6275) to use my own `pattern` files. Patterns provided with the script-dance survive KOReader updates. (But be aware, then you use your own patterns, the upstream patterns get overwritten.). Build your pattern, drop it on `/sdcard/koreader/data/hyph/German.pattern` and voila you can test your thing.

I generate the pattern file with the script `gererate-de-1996-righthyphenmin3.sh` from `https://github.com/zwim/hyphenation-patterns`, using `https://repo.or.cz/wortliste.git`. What this exactly does, you can read in `dokumente/Trennstile.txt`.
Until now, I used `hyphenmin3` but I get more and more convinced, that `righthyphenmin3` is better (especially if you read in two columns mode). Do you have an opinion about this?

The data-format of `user-XXX.hyph` is simple (no spaces!)
```
Muster;Mus-ter
Antilopenknochen;An-ti-lo-pen-kno-chen
```
For testing, you could throw your whole patterns in that file.

**Comment by Moonbase59** [comment]
@zwim: Thanks for all the detailed explanations, much appreciated! I’ll play around and test the next few days, only just rebuilding two broken machines here…

Re opinion: After being disappointed with the old Adobe RMSDK they use in the Tolinos, and _lots_ of discussions all around, I eventually ended up using a 3/3 hyphenation for German. Reasons being:

- Words in German are substantially longer than in English. Duden cites an average word length of 10.6 characters in the "Deutsche Rechtschreibung" Duden, and even 14.43 using only the base forms of the 18-million word Duden corpus. English average word lengths are quoted between average 4.7 to a little over 5 characters/word.
- Many German readers find 2-letter hyphenation a little distracting, especially if it happens often.
- Using a 3/3 instead of 2/2 or 2/3 hyphenation makes for a lot less hyphenated words, and smaller pattern lists. Overall. a more "smooth" reading experience, users tell me. Taking into account German word lengths, this makes sense.
- For older RMSDKs (like in the Tolinos), this makes even more sense, since the RMSDK "counts" non-word boundary characters like punctuation, quotes, etc. into the hyphenator length, thus often resulting in dumb and wrong hyphenations like "Pfer-d." or "kaput-t.«". Using 3/3 instead of 2/2 or 2/3 helps to avoid many of such cases. Sometimes it’s all about fighting bad old software and compromising… Sigh.

Having test-read _a lot_ of German books to find possible errors and the most pleasing reading experience, **yes, I do have formed a strong opinion towards using a 3/3 hyphenation for German.** You loose very little and gain much.

Plus, the same "hyph_de.dic" (in my case) helps reducing errors introduced by dumb hyphenators.

For KOReader, since it already uses the patterns you provided (Thanks! Didn’t realize at first!), one might give 2/3 a try  (instead of using 3/3). Then again, even on small readers, 3/3 might just be sufficient. I think there’s still enough justification white space left. Also KOReader, as opposed to the Tolinos, _does_ hyphenate on the first line of indented paragraphs. Personally, I’d go for 3/3, but at least go for the 3 at the right!

**Comment by zwim** [comment]
@Moonbase59 
> Personally, I’d go for 3/3, but at least go for the 3 at the right!

I will generate 2/3 patterns (word compositions like `Früh-stücks-ei` will be allowed, but `dei-ne` or similar are not be allowed). 
Let's call this internally 2/2.5 patterns. This patterns will be used, even if the user selects 2/2.

A user who doesn't like the seldom hyphenations at the end, or who wants a strict 2/3 or 3/3 can change that in
![grafik](https://user-images.githubusercontent.com/36999612/151817143-6fc582fa-4e80-4190-b53d-fb9058c1b5a8.png)

![grafik](https://user-images.githubusercontent.com/36999612/151817282-35df3991-6dd0-4425-8756-6da736fadfa7.png)


>Re user-XXX.hyph: This is a real brilliant idea! Can these be edited on the device, i.e. by using KOReader’s built-in text editor?

Yes, they can be edited by hand, but to apply the change KOReader has to be restarted.

The usual way would be to activate `Custom hyphenation rules` (first screenshot) and then do a verrrryyy loooonnnng pressssss (>4 sec) on the desired word and select `Hyphenate` on the dialog

![grafik](https://user-images.githubusercontent.com/36999612/151818112-d9c727d9-75dc-4c13-9d92-984706b592f2.png)

Then you can enter your preferred hyphenation positions. Be aware that the `Remove` button only removes the user pattern - the pattern from `German.pattern` can not be changed. The change is applied with `Save` immediately.

>And do they support "normal" (-) and "preferred" (=) hyphenation points? 

No, that is not intended.

**Comment by poire-z** [comment]
Closing as many questions answered and German hyphenation file updated since.
Feel free to continue asking/discussing in here if needed.
