### ISSUE TITLE
FR: Background color, frontlight warmth, (auto) nightmode on TFT displays (smartphones, tablets)

### ISSUE THREAD

**Issue by Moonbase59** [koreader/koreader#8707]
**Does your feature request involve difficulty completing a task? Please describe.**
It’s impressive what auto nightmode can do already (like determine correct sunset times etc.). What I miss on TFT display devices like my smartphone, and my Tolino Tab 8" tablet is a "pseudo frontlight warmth" (by modifying the Background color from white to something warmer) instead of the white on black display which hurts my eyes.

**Describe the solution you'd like**
Ideally, a changing background colour during the phases of the day, based on °K light warmth calculation (I once did that for my home automation, to control the warmth of RGB lighting). If that’s too much effort, probably a means to specify how the "day" and "night" colors (=background color) should be (maybe as hex RGB) instead of the white on black mode. One could then read black on white during the day, black on "something warmer" when auto nightmode hits in.

**Describe alternatives you've considered**
On the Tolino Tab 8", trying to find a "frontlight warmth" setting, but only the brightness is adjustable. Maybe this could be activated and use fake RGB values for the 0..100 on devices that have RGB displays (non-e-ink smartphones, tablets).

**Additional context**

**Comment by pazos** [comment]
Already requested.

Background color: https://github.com/koreader/koreader/issues/3871
Warmth simulation for android/lcd devices: https://github.com/koreader/koreader/issues/5768
