### ISSUE TITLE
False battery level notification

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8714]
* KOReader version: v2022.01-28
* Device: PB 628

#### Issue
I installed the nightly version v2022.01-28 yesterday, but when I enter KOReader the low battery notification appears indicating that the battery level is 0%, when it is not. 

Something is wrong...

**Comment by Frenzie** [comment]
Sounds like https://github.com/koreader/koreader/pull/8694 is wrong after all?

**Comment by hius07** [comment]
ReaderDeviceStatus doesn't use BatteryStats plugin, but does use powerd.
I think of https://github.com/koreader/koreader/commit/dc98384177a5abba7be7082333c5fdf51fab1c17#diff-73a3fdbcc19ef378540019494e8e6a8b75ec330e3f6b3b23f982425c93417bd6

**Comment by Frenzie** [comment]
Ah, well, @NiLuJe? ;-)

**Comment by NiLuJe** [comment]
See the draft pr ;).
