### ISSUE TITLE
colordict not working

### ISSUE THREAD

**Issue by darren4321** [koreader/koreader#8718]
* KOReader version: 2022.01
* Device: oneplus8pro_eea
Android 11

#### Issue
colordict is not working when selected as external dictionary. Nothing happens when a word is selected. The internal dictionary does work (does not have audio pronunciations' though),

#### Steps to reproduce
check 'use external dictionary'
select colordict

**Comment by Frenzie** [comment]
Perhaps there are multiple colordict apps?

https://github.com/koreader/koreader/blob/87dbb9885e4e87efb884e6f78192c26fae982fdf/frontend/device/android/device.lua#L52

You can also add your own in settings/dictionaries.lua btw. See https://github.com/koreader/koreader/pull/5664 for instructions.

**Comment by pazos** [comment]
It used to work just fine with its custom intent but they borked it on last 2021 update.

Reverting to a generic "send" intent makes the dict work again (without transparency, without overlay so a bit of animation overhead).

That's the best thing we can do, as trying to catch how random closed source apps work is an endless task with no joy.

**Comment by Moonbase59** [comment]
Interesting. I played around with ColorDict and GoldenDict (Free) today on my Tolino Tab 8" and it seemed to work ok. Then again, the Tolino only has Android 4.4.4.

**Comment by pazos** [comment]
Can't say. I just reproduced OP issue in A11.

The custom intent is still there, so it's a matter of wrapping up your own dictionaries.lua and revert the commit there.

Cause the old behaviour was waaaaay nicer.
