### ISSUE TITLE
The estimated time remaining on the battery stats hasn't been updated since I updated to the new stable version 2022.01

### ISSUE THREAD

**Issue by yukari186** [koreader/koreader#8719]
* KOReader version: 2022.01
* Device: Kobo Clara HD

The estimated time remaining on the battery stats hasn't been updated since my device has been updated to the new stable version 2022.01. I tried factory reset but nothing has changed.

**Comment by Frenzie** [comment]
Duplicate of https://github.com/koreader/koreader/issues/8714, should be fixed by https://github.com/koreader/koreader/pull/8711 (in tomorrow's nightly).

**Comment by yukari186** [comment]
> Duplicate of #8714, should be fixed by #8711 (in tomorrow's nightly).

Thank you so much. What a perfect support! I very look forward to the nightly ver in tomorrow ^^
