### ISSUE TITLE
Clear History of deleted files, Auto-remove deleted/purged don’t work

### ISSUE THREAD

**Issue by Moonbase59** [koreader/koreader#8723]
* KOReader version: 2022.01
* Device: Tolino Tab 8" (Android, KOReader ".rocks" version)

#### Issue
I have moved around (different folders) and deleted some books. I have set "Auto-remove deleted or purged items from history". The deleted books are stll shown in history as "(deleted)", so I tried "Clear history of deleted files", but that seems to have no effect.

#### Steps to reproduce
Move and/or delete some books, check history (they should still appear), try to clear history.

##### `crash.log` (if applicable)
—

#### Screenshots

![Screenshot_2022-01-24-17-26-47](https://user-images.githubusercontent.com/3706922/150825046-1257609f-6187-40c5-8d99-f011d73562e5.png)

![Screenshot_2022-01-24-17-27-12](https://user-images.githubusercontent.com/3706922/150825103-30700a19-e41e-4eca-8664-1fc15a9b3005.png)

#### EDIT
Further testing shows that after exiting the app and restarting it, the history is cleared of "(deleted)" entries.

**Comment by Frenzie** [comment]
Presumably Android or in a worse/better case device-specific.

**Comment by Moonbase59** [comment]
Will cross-check on Linux tomorrow. I presume most KOReaders will be running on Android-type readers, though?

**Comment by Frenzie** [comment]
It also works for me on Android afaict.

> I presume most KOReaders will be running on Android-type readers, though?

It's certainly a possibility because the barrier to entry is low. Development is mostly cross-platform but with a distinct emphasis on embedded Linux though.

**Comment by Moonbase59** [comment]
On Linux Mint 20.3, KOReader 2022.01 (AppImage), this works ok.

One minor quirk here: When deleting a book (and its .sdr folder) from _outside_ KOReader (while KOReader is running) in the folder KOReader is currently in, the file view doesn’t auto-update (only "next time round"). This isn’t really a problem (can’t have _everything_ on all OSes), but when you then click on the book that was just deleted in KOReader’s file view (to open it), the file manager doesn’t simply say something like "file has vanished" or "can’t open" but instead jumps to some mount point (in my case `.mount_koreadK03iW4` and displays what looks like KOReader’s base folder:

![mount_koreadK03iW4 - KOReader_001](https://user-images.githubusercontent.com/3706922/150978341-026743ce-1279-4059-8d38-ea5e96a1c57e.png)

This is not mission-critical, but might confuse users.

**Comment by Moonbase59** [comment]
Btw, (and a little off-topic): I run KOReader in English language but have its keyboard  set to German (because I have a QWERTZ keyboard).

It’s a little confusing to still get a "QWERTY" sequence shown in everything that offers "quick letter access", like the file manager. Is it possible to adapt that sequence to whatever a user has selected as his keyboard (think of Russian, Greek, French, … keyboards!)? A French user might prefer "AZERTY…", a Russian user maybe "йцукен"…

**Comment by Frenzie** [comment]
Not at this time, though that's making me wonder if the relevant Kindle models came with QWERTZ in Germany.

https://github.com/koreader/koreader/blob/3af268dd7af8050597ad1656ffd0f596e89bf2d4/frontend/ui/widget/menu.lua#L584-L588

https://github.com/koreader/koreader/commit/b47d5b76ebc4199c9996c9815729b00744753d10

**Comment by NiLuJe** [comment]
Remind me to check my k2i when I get back home, but it's quite likely not AZERTY ;).

**Comment by Moonbase59** [comment]
@Frenzie Thanks for the workaround! Would still be nice to see that implemented in keyboard change, not language change. ;-)

Don’t own a Kindle, so can’t try (Kindle software on my smartphone uses whatever Android has set).

**Comment by Moonbase59** [comment]
A Kindle Keyboard 3…  I always wondered where that came from. On touch-enabled devices you’d use touches & taps anyway. My Linux desktop install is actually also more to have a reference handy. Anyways, it’s certainly a minor quirk.

**Comment by NiLuJe** [comment]
Yeah, if my own devices are anything to go by, they were all QWERTY, regardless of the local market's usual kb layout ;).

**Comment by poire-z** [comment]
Possibly fixed with #8813. Re-open if not.
