### ISSUE TITLE
PocketBook: #koreader signature check needs to be dropped from association code

### ISSUE THREAD

**Issue by andrewshadura** [koreader/koreader#8728]
I’m not sure what exactly is the value of this check. It leads to issues like [this](http://www.mobileread.mobi/forums/showthread.php?t=339558) when KOReader can be dissociated by the system and the user cannot associate file extensions back. This happened to me — I switched to the inbuilt reader for a while and wasn’t able to return. It took me half a year to figure this out, and I’m an engineer and I know where to look for stuff, I can’t imagine how it would be for a non-technical user.

_Originally posted by @andrewshadura in https://github.com/koreader/koreader/pull/6617#r791786625_

**Comment by pazos** [comment]
Not sure about the intent, but probably the rest of the code was tested under vanilla conditions (no config file or a config file without koreader in it). If it works fine in the rest of cases then your PR is indeed desiderable.
