### ISSUE TITLE
Unable to add bookmarks 

### ISSUE THREAD

**Issue by mgonzalezm** [koreader/koreader#8732]
* KOReader version: 2021.12.1
* Device: Samsung Galaxy Tab S 

For some reason I've never been able to bookmark the current page tapping on the uper right corner of the screen. I tried different KOReader versions but the gesture is just imposible to trigger in this device.

I found #4262 but it seems than the menu is only available on non-touch devices. Can we have the menu visible in all cases?

**Comment by hius07** [comment]
At first, check if Toggle bookmark is assigned to the tap corner gesture.
Then, if the device doesn't support this gesture, you can reassign it.
Gear - Taps and gestures - Gesture manager

**Comment by Frenzie** [comment]
> The options for both sides of top corners are grayed out, do you know why?

On my phone, that'd be because of the camera that's stuck inside the screen. I haven't cared enough to make it just ignore the camera. But anyway, in that case the top right would be where you see the hamburger menu on your screen, not in the actual top right of the device that's ignored.

**Comment by mgonzalezm** [comment]
This is not the case, this is a tablet and the camera is outside the screen (on the bezel).
I'm pretty sure the tap is just being ignored, I tried ad nauseam in all locations of the top right of the screen

**Comment by hius07** [comment]
> The options for both sides of top corners are grayed out, do you know why?

Are you in reader, not in file manager?

**Comment by mgonzalezm** [comment]
> Are you in reader, not in file manager?

Right, I think I was in file manager, i can see now that while reading a book all 4 options are available.
Does it means that this is a per book setting ?

**Comment by Frenzie** [comment]
Not per book but for book.

**Comment by mgonzalezm** [comment]
> Not per book but for book.
OK.

I suppose this issue should be closed but, even tough it is working now, I still think that the option to toggle the bookmark via a menu on not touch devices is a good idea. this would avoid all this confusion for new users like me.

Thank you all.
