### ISSUE TITLE
FR: no default text when creating new note

### ISSUE THREAD

**Issue by derekvan** [koreader/koreader#8736]
I am often making notes on the text, typically for import into Readwise. When I make a note, I first have to delete the text that is created automatically in the note field. Would prefer an option to have the note field opened as blank.

**Comment by hius07** [comment]
Need more opinions on possible way of fix
(1) open empty input box and have highlighted text (auto text) in the clipboard
(2) keep current behaviour and add `Clear` button to the Edit note dialog
(3) have a setting "Empty new note"

**Comment by poire-z** [comment]
(4) let @derekvan know (in case you didn't) that long-press on the <kbd>backspace</kbd> key erase till start of line (so, just good on single line highlight, but need more long-presses on multiline highlights).

About the other ideas:
(1) not good: it would override any text already in the clipbooard these user wished to paste as his note
(3) not worth a new setting -  I guess some times, even the users wishing blank note would like to have the text to keep some part of it, so it would need (1) also
(2) a <kbd>Clear</kbd> button feels the clearest :) if the backspace trick is not obvious enough

Unless really all users do erase the original text to add their stuff :) I have no idea (I think I would erase it if I were making some notes). In which case: start empty and have a <kbd>Paste selected text</kbd> as the additional button (without having it transit/override the clipboard).

**Comment by derekvan** [comment]
I don’t understand why the note text is added at all. Any app I have used that grabs highlights/notes will grab the text of the highlight. It doesn’t need to be in the note.

**Comment by derekvan** [comment]
@hius07 fantastic! Thanks for addressing this.
