### ISSUE TITLE
device lua for Pocketbook PB623 not suitable and need to be modified with each new version

### ISSUE THREAD

**Issue by TiberiusRegenschein** [koreader/koreader#8743]
* KOReader version: KOReader 2022.01 "Union of Utrecht"
* Device: Pocketbook PB623

#### Issue
There are actually 2 issues with the device.lua

1. Freeze due issue as described in #8053 and #8392
2. crash (see crashlog probably based on the solution described here #8617

#### Steps to reproduce

**Modify line 267** from "inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn )" to "inkview.SetSubtaskInfo(inkview.GetCurrentTask(), 0, title and (title .. " - koreader") or "koreader", fn or "[nil]")"

This addresses issue 1

**Delete**
else
            return band(inkview.GetNetState(), C.CONNECTED) ~= 0
[crash.log](https://github.com/koreader/koreader/files/7962474/crash.log)

This addresses issue 2

As discussed in #8617 There seems to be an issue with GetNetState depending on if the Network was switched on or not. I hope the log helps

##### `crash.log:

**Comment by rjd22** [comment]
@Frenzie AFAIK both issues should be fixed now. The freeze was due to the null variable. And wifi issues were due checking the wrong connected state.
