### ISSUE TITLE
"Strange flashes" after applying the changes of the file "koreader-pocketbook-inkview-rendering"  (see #8727)

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8750]
* KOReader version: v2022.01-51
* Device: PB 628

#### Issue
As a follow-up to comments https://github.com/koreader/koreader/issues/8187#issuecomment-1024869094 and https://github.com/koreader/koreader/issues/8187#issuecomment-1025131583, I give you a related video (I had to reduce the size of the video, with consequences for the quality).

https://user-images.githubusercontent.com/76203123/151700566-8c0ea3f6-66c0-4bdd-9824-9ce7431a3f6c.mp4

**Comment by rjd22** [comment]
This seems like a race condition. The screen refresh is faster than the button highlight and dehighlight.

I'm not sure this is bad behavior because fixing this might mean we have to change button and screen refresh behavior.

/cc @poire-z @NiLuJe

**Comment by poire-z** [comment]
Can't help much on that :/
@rjd22 : can you reproduce it on your own PB ?

Might be (dunno) the PB implementation of:
```lua
function framebuffer:refreshWaitForLastImp()
    if self.mech_wait_update_complete and self.dont_wait_for_marker ~= self.marker then
        self.debug("refresh: inkview waiting for previous update", self.marker)
        -- self:mech_wait_update_complete(self.marker)   -- ours
        inkview.WaitForUpdateComplete()    -- theirs
        self.dont_wait_for_marker = self.marker
    end
end
```
that doesn't take the marker as parameter, so you get less granularity on what you wait (?)

**Comment by rjd22** [comment]
> Can't help much on that :/ @rjd22 : can you reproduce it on your own PB ?

I indeed have the same behavior but I actually liked it 😂. It made the pocketbook feel snappy because it was not waiting for the button deselect partial refresh. I myself rather have the menu sooner than later.

**Comment by Frenzie** [comment]
> I indeed have the same behavior but I actually liked it joy. It made the pocketbook feel snappy because it was not waiting for the button deselect partial refresh.

That looks pretty much like the intended behavior, and if it was doing something slower/less simultaneous it probably wasn't behaving as intended.

**Comment by NiLuJe** [comment]
Okay, I actually missed the video the first time around because I was on mobile/email.

Yep, definitely intended behavior ;).

**Comment by NiLuJe** [comment]
As for the lack of granularity of the IV implementation, it should *hopefully* be mostly harmless, as we don't usually wait on any other marker than the previous ones.

(As an example, a truly great virtual keyboard implementation might want to do things differently, c.f., a native Kindle VK, which does some pretty neat stuff to handle everything -- including a suggestion bar -- live ;)).

**Comment by ichnilatis-gr** [comment]
I would like to point out one more bug about the file. I noticed that, in rotated view (+/- 90°), the text, regardless of type, is distorted; it splits into two strips that do not change the same on page turn. Unfortunately the screenshots I took, surprisingly, do not show the problem.

**Comment by NiLuJe** [comment]
That's possibly hw rota being broken ;).

**Comment by ichnilatis-gr** [comment]
I bag your pardon, I didn't understand what you mean. What is "hw rota"?

**Comment by Frenzie** [comment]
Hardware rotation (meaning something like that we don't have to do any rotating in software but that the hardware has dedicated hardware to do it much faster). ^_^

**Comment by ichnilatis-gr** [comment]
Well... still not understanding... Never mind. 
What does this mean in practice? Is it a problem of the "koreader-pocketbook-inkview-rendering" file changes or something else? It happened after I installed it. I went back to the last nightly I had and everything is OK...

**Comment by NiLuJe** [comment]
Yes, the inkview changes breaks hardware rotation handling (possibly rotation handling, period).

**Comment by rjd22** [comment]
I will look into it next week to solve the hardware rotation. Most likely it's not that difficult to fix but just needs some extra support implemented.
