### ISSUE TITLE
Certain Stardict dictionaries that work with Goldendict on PC don't work with KOReader

### ISSUE THREAD

**Issue by Vuizur** [koreader/koreader#8751]
* KOReader version: 2022.01
* Device: Samsung Galaxy Tab A7

#### Issue
I have ebooks that are in Russian (with added stress symbols, which are represented by the extra unicode character "COMBINING ACCUTE ACCENT" as far as I know). I also created a Stardict dictionary (created using Pyglossary) that contains translations of these words, also with stress symbols. When I look up any stressed word in the Goldendict desktop App, I get the correct translation. However, when I try to use the dictionary with KOReader, I always get "No results." (This is also the case when I look up words without stress marks).
Other dictionaries I tried worked and the name of my dictionary is being recognized.

#### Steps to reproduce
I put an ebook and my dictionary in a folder (both are public domain/CC-BY-SA):
[dictionary-and-ebook.zip](https://github.com/koreader/koreader/files/7965938/dictionary-and-ebook.zip) so that the problem should be easy to reproduce.

What could I try?

**Comment by poire-z** [comment]
Looks like a segfault in sdcv, happening only when using your dictionary:

```
/koreader_stuff/dict/russian $ gdb -ex 'set confirm on' -ex r --args /koreader-emulator-x86_64-linux-gnu-debug/koreader/sdcv -x -2 . $(cat zzz)
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7deeba9 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7deeba9 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00005555555741bd in DictBase::GetWordData (this=this@entry=0x55555567d310, idxitem_offset=19269076, idxitem_size=92)
    at /sdcv-src/src/stardict_lib.cpp:303
#2  0x000055555556f280 in Dict::get_data (index=<optimized out>, this=0x55555567d310)
    at /sdcv-src/src/stardict_lib.hpp:138
#3  Libs::poGetWordData (iLib=0, iIndex=<optimized out>, this=0x7fffffffdac0)
    at /sdcv-src/src/stardict_lib.hpp:196
#4  Library::SimpleLookup (this=this@entry=0x7fffffffdac0, str=..., res_list=...)
    at /sdcv-src/src/libwrapper.cpp:211
#5  0x000055555556fccf in Library::process_phrase (this=this@entry=0x7fffffffdac0, loc_str=<optimized out>, io=..., force=false)
    at /sdcv-src/src/libwrapper.cpp:363
#6  0x000055555556c5dc in main (argc=<optimized out>, argv=<optimized out>)
    at /sdcv-src/src/sdcv.cpp:234
```

https://github.com/Dushistov/sdcv/blob/d054adb37c635ececabc31b147c968a480d1891a/src/stardict_lib.cpp#L297-L303

This happens when I give your cyrillic utf8 input, but not if I just provide "test" or "hého" as utf8 :/

So, a bug in upstream sdcv - but that only triggers on your dict and not on my 15 other dicts.
Not familiar with upstream sdcv, so you might to report the issue to them - and if you're a bit confortable with C++, look at what this codes does to find out on what thing in your dict it stumbles on.

**Comment by Vuizur** [comment]
Thank you for the reply! That really seems to be the reason. 
One possible error source might be the combining accute accent. In Spanish text, which has latin accents like in teléfono, the é is only one unicode character (LATIN SMALL LETTER E WITH ACUTE). However for cyrillic this is not the case, in the accented де́лать the е́ is two unicode characters (CYRILLIC SMALL LETTER IE + COMBINING ACUTE ACCENT). I didn't really understand the linked code, but it possibly seemed to be compatible with this theory.

I will probably open an issue in the repo, I already managed to set it up in WSL, but will have to figure out how to get the breakpoints working before I can really debug anything.

**Comment by poire-z** [comment]
Possibly.
There are indeed different ways to express the same "é" (and your cyrillic equivalents) in Unicode:
https://en.wikipedia.org/wiki/Unicode_equivalence
https://fr.wikipedia.org/wiki/Normalisation_Unicode (nicer table with pictures)

I don't know how sdcv manages the possible different inputs for the same thing - and what's expected to be in the dictionaries word indexes - and if anywhere it decides to convert (input and/or dict entries) to one normalization so it can compares things that are comparable :/

**Comment by Vuizur** [comment]
Thanks for the links, they are very useful. 👍
I guess the one positive thing of accented cyrillic is that no one-unicode-character versions exist, so in theory no normalization would have to be performed to check for equality.

**Comment by Vuizur** [comment]
Dushistov managed to find the mistake, it was that sdcv only supports ifo files with LF line endings and mine were CRLF. 👍
