### ISSUE TITLE
Radio buttons in menu

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#8754]
To discuss once more: should the mutually exclusive checkmarks be changed to the radiomarks?

![01](https://user-images.githubusercontent.com/62179190/151793138-e6975e41-bda0-4ff5-8297-96506914c4d0.png)

![02](https://user-images.githubusercontent.com/62179190/151793143-2b4c716c-c55d-4156-bf51-7cdbc8bc92d7.png)

![03](https://user-images.githubusercontent.com/62179190/151793146-6f763bde-df68-4f69-ac07-97990a28dd5d.png)

**Comment by poire-z** [comment]
I personally don't mind our current usage of a square box for both multi or single selection.
But as it seems you have already coded the change, why not :)

Strangely, on your screenshots, your squares feel a little bit too up. On my side, I have them a bit lower (on my emulator and my Kobo) and it feels they look better:
![image](https://user-images.githubusercontent.com/24273478/151795161-feb803d2-8f1f-49ec-b751-5e23773739eb.png)

So, dunno if this is due to some coding changes of yours.
I also think your circle marks are also a bit too up.

**Comment by hius07** [comment]
![04](https://user-images.githubusercontent.com/62179190/151796215-640f5147-024a-48af-906b-74b5ecbc03e2.png)

![05](https://user-images.githubusercontent.com/62179190/151796219-31725e3b-e907-460f-9425-652f7b218336.png)

**Comment by hius07** [comment]
Checkmarks are not changed absolutely.

**Comment by hius07** [comment]
If keeping the checkmarks, all mutually exclusive groups must be separated

![07](https://user-images.githubusercontent.com/62179190/151797347-ee8a6bc6-b452-4a0c-ab05-efa7bc042191.png)

EG screensaver settings: the first 3 settings are mutually exclusive, the last is not.

**Comment by Frenzie** [comment]
Indeed, if you created the screenshot based on code you might as well stick it in a PR. It's probably a little more proper that way. But there should probably be a separator there regardless of the type of checkbox. :-)

**Comment by hius07** [comment]
Yes, it is a working code.
I just wanted to ask if the idea is interesting, before PR. I remember it has been discussed a couple of times previously without consensus or output.

**Comment by hius07** [comment]
![08](https://user-images.githubusercontent.com/62179190/151829880-bd624166-30e0-42a3-967e-fbc300959e0f.png)

**Comment by poire-z** [comment]
On your screenshots, the small black circle feels a bit odd, vs the larger black circle we are used to (but only a bit :).
But it's really something to be tested on our eInk devices - so please keep one of the 2 symbols/constructs commented out in your code, so we can test both options.

**Comment by poire-z** [comment]
(Keeping the conversation here.)
Tested your PR, and I think I'm fine with both kind of radio buttons :) (at least, the checkmarks are small enough for their black to be bothering or ghosting, on my small reader with normal dpi).
The little one looks ok, if it's the one you prefer.

Font list in CRE are also mutually exclusive. Dunno if you want to go full conradiostency, of if keeping square checkmarks when there is no doubt.

(I think that in the past, when you were hitting a checkmark and a re-rendering happened, we were seeing, by luck, the 2 checkmarks checked while the re-rendering was happening - the new one checked and the old one still not unchecked. Or may be that was only in the bottom menu, where it seems also that this is no longer happening... A bit confused, I liked that, not sure is it was fixed willingly at some point.)

**Comment by hius07** [comment]
More screenshots, to compare, to have more opinions.

![10](https://user-images.githubusercontent.com/62179190/151862223-c4dd61d0-5b3c-4090-a222-1e33f7f0028d.png)

![11](https://user-images.githubusercontent.com/62179190/151862228-9a29a5ec-16c4-4738-86f8-d82de3571514.png)

![12](https://user-images.githubusercontent.com/62179190/151862230-dc32056d-c095-48f4-9d8e-30ebfce37e68.png)

(1) Go with changes?
(2) If yes, small or large dot? *
(3) If yes, everywhere or in the mixed menus only, to emphasize mutually exclusive items?

*(radiomark will be inserted into radiobutton widget, so the same dot will appear in dialogs)

**Comment by offset-torque** [comment]
> Should the mutually exclusive checkmarks be changed to the radiomarks?

Yes, this confused me when I first started using KOReader. I got used to it but it is better to indicate which options are mutually exclusive and which are part of multi-selection. Less confusion for users is always a good goal.

- My vote for large dot (considering small e-ink screens with low contrast ratio)

**Comment by Frenzie** [comment]
The large dot is the one we have right now; I don't recall if I considered a smaller dot when I created it but I assume I chose for the larger one on purpose.

(I don't think the contrast ratio is particularly low though; maybe it's worse on capacitive screens.)

**Comment by solarkite** [comment]
> If yes, small or large dot?

I find the Large Dot more appealing. 
@hius07 and the other work on this adds to the UX. Thanks.

**Comment by poire-z** [comment]
I merged it so we can all see how it looks on our devices.
I still think the radio buttons looks a bit miscentered vs. the text (taller, even if sitting on the baseilne, they look a bit too up to me - a feeling I don't have with the square boxes).

**Comment by offset-torque** [comment]
> I still think the radio buttons looks a bit miscentered vs. the text (taller, even if sitting on the baseilne, they look a bit too up to me - a feeling I don't have with the square boxes).

That is because of how visual system works. The closest example I can think is Kanizsa Triangle (or square in this example):

![kanizsa square](https://user-images.githubusercontent.com/84420582/152113568-ab8f0d03-514b-4d8b-9da7-e48eaf1627f2.jpg)


In check boxes, there is a horizontal bottom line that our eyes automatically aligns with the text's baseline. In other words we perceive both radio box and the text is sitting on the same (virtual) "floor". In radio buttons there is no floor to anchor it to the text beside it. So it is "levitating".

Yes this is just an illusion but we can't see them at the same level even if we force ourselves (as in all other optical illusions).

Solution might be positioning the circle a bit lower (1 or 2 pixels maybe) to make it "look like" it is centered. I don't know if it possible within KOReader UI to adjust position that precisely.

**Comment by mergen3107** [comment]
Yes, I remember asking such question, then Frenzie introduced us to the whole radiobutton/checkbox paradigm :D 

I’d vote for large circles, but agree that they look off-center. 

How about square dots then?

**Comment by hius07** [comment]
> they look a bit too up to me

I've added a `downshift` property to the RadioMark that can be set by the caller.

0 (current)
![20](https://user-images.githubusercontent.com/62179190/152343550-3d671e37-235c-4766-bf94-342235b02bbc.png)

1
![21](https://user-images.githubusercontent.com/62179190/152343553-e231da3b-817e-4a3b-bca1-536156cc205d.png)

2
![22](https://user-images.githubusercontent.com/62179190/152343556-2e0e8032-1fce-4132-b8cc-4ab15c473f9e.png)

3
![23](https://user-images.githubusercontent.com/62179190/152343559-23086f12-851d-482a-a859-b2f3ee4a5551.png)

5
![25](https://user-images.githubusercontent.com/62179190/152343561-46df724c-c88f-429f-a991-ffd246999322.png)

**Comment by poire-z** [comment]
2 and even 1 looks OK.
Is you downshift scaleBySize or something ?

I don't think it should be set by caller: it better be handled by RadioMark itself, which is the one causing the optical illusion :)

An idea: with TextWidget, you can getBaseline() and getHeight(), so you know the space below the baseline. And you can provide a force_baseline and force_height, so you could try forcing the baseline to be in the middle (or another fraction, 1/3, 2/3...) of the height - baseline to force it a bit down.

**Comment by Frenzie** [comment]
Agreed, just let RadioMark set it to 1, optionally to be overwritten I suppose but that should be extremely rare if not completely absent.

**Comment by hius07** [comment]
```lua
local widget = VerticalGroup:new{
        align = "left",
        VerticalSpan:new{
            width = Screen:scaleBySize(self.downshift),
        },
        text_widget,
}
```

**Comment by poire-z** [comment]
Try it with:
```lua
local pad = math.floor( (text_widget:getSize().h - text_widget:getBaseline()) * 1/2)
--and
VerticalSpan:new{ width = pad },
```
Or may be you don't even need this VerticalGroup (dunno how it affects the centering in touchmenu, if it uses the baseline you set in RadioMark).
If it does, just fix the baseline in RadioMark itself:
```diff
- self.baseline = widget:getBaseline()
+ self.baseline = widget:getBaseline() + math.floor( (widget:getSize().h - widget:getBaseline()) * 1/2)
```

**Comment by hius07** [comment]
> ```lua
> pad = math.floor( (text_widget:getSize().h - text_widget:getBaseline()) * 1/2)
> ```

What are the benefits of calculating the pad as above against simple scaleBySize?

On my Kindle
text_widget:getSize().h = 63
text_widget:getBaseline() = 47

**Comment by poire-z** [comment]
> What are the benefits of calculating the pad as above against simple scaleBySize?

Because your 1 (or 2), even if scaleBySized, would be fine only with the font face and size (say 20, also scalebySized)) set on touch menu items that you had tested with.
If we use it elsewhere with another font face or another font size (say 26), your 1 (or 2) would may be need to be 2 (or 3).
By using the font baseline & height, we get a chance to have this work no matter the font face and size, by relying on font metrics. Not saying it's 100% success, may be 1/10 is fine with NotoSans but would be bad with Noto Mono, or some fallback fonts.

> I need a ratio about 1/10 to look good.

So use 1/10 (my 1/2 was some random suggestion :)

**Comment by poire-z** [comment]
May be it doesn't need to be a factor of the height-baseline. A factor of the font real size or height might work just as well.

**Comment by hius07** [comment]
> text_widget:getSize().h = 63
> text_widget:getBaseline() = 47

47/63=0.746
https://github.com/koreader/koreader/blob/cb7e670c4a73a21db0db829f67b8014658ce4bb2/frontend/ui/widget/textwidget.lua#L112-L114
Yes, a ratio to just h would work.
