### ISSUE TITLE
Refactor exporter plugin

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#8755]
- [ ] write a `GenericTarget` that implements common code for exporters.
- [ ] write each exporter as a subclass of `GenericTarget` that implements `exportOne` and `exportAll` functions.
- [ ] write an intermediate representation of the notes (a lua table dumped with persist, maybe?) that can be handled by all targets.
- [ ] handle multiple selection (export to more than one format at the same time)

**long term**
- [ ] each exporter should have a `getMenuTable` function returning a table of its menus.
- [ ] make network dependant code part of `GenericTarget` implementation.
- [ ] address https://github.com/koreader/koreader/issues/8755#issuecomment-1068024857 for local formats (json and html)

It can be fun to play a bit with local formats. Not so fun w/ joplin or readwise.
I'm mostly interested in keeping the same table to fed all exporter functions, no matter if they're going to use all the contents of the table.
Also having an intermediate representation makes easier to write unit test and catch bugs.

**Comment by pazos** [comment]
I've checked current state of affairs :)

If we can avoid keeping compatibility with actual settings I would propose to store a table per format under the "exported" setting.

Something like:

```lua
["exporter"] = {
        ["html"] = {
            ["enabled"] = true,
        },
        ["json"] = {
            ["enabled"] = true,
        },
        ["joplin"] = {
            ["enabled"] = false,
            -- other joplin settings here
        },
    },
```

This way we can have all supported formats under a local table in `main.lua`

```lua
local targets =  {
    json = require("formats/json"),
    html = require("formats/html"),
    joplin = require("formats/joplin"),
    -- more formats here
}
```
Where each key/format of the targets table contains a "settings" table.

Also all formats would inherit from

```lua
local BaseExporter = {}

function BaseExporter:new(o)
    o = o or {}
    o.name = o.name or "dummy"
    o.desc = o.desc or ""
    setmetatable(o, self)
    self.__index = self
    return o
end

-------
-- Load settings for the given format.
function BaseExporter:loadSettings()
    local plugin_settings = G_reader_settings:readSetting("exporter_new") or {}
    self.settings = plugin_settings[self.name] or {}
end

-------
-- Save settings for the given format.
function BaseExporter:saveSettings()
    local plugin_settings = G_reader_settings:readSetting("exporter_new") or {}
    plugin_settings[self.name] = self.settings
    G_reader_settings:saveSetting("exporter_new", plugin_settings)
end


function BaseExporter:isEnabled()
    if not self.settings then
        self:loadSettings()
    end
    print(self.settings, self.settings.enabled)
    return self.settings.enabled

end

function BaseExporter:toggleEnabled()
    if not self.settings then
        self:loadSettings()
    end
    self.settings.enabled = not self.settings.enabled
    self:saveSettings()
end

-------
-- Menu for the given format.
-- @treturn table
function BaseExporter:getMenuTable()
    return {
        text = self.name,
        checked_func = function()
            return self:isEnabled()
        end,
        callback = function()
            self:toggleEnabled()
        end,
    }
end


-------
-- Exports a table of booknotes to a specific format.
-- @tparam table t
-- @treturn bool

function BaseExporter:export(t)
    if not type(t) == "table" then return false end
    return true
end

return BaseExporter
```

So hopefully we can handle settings & menus within each format implementation and leave `main.lua` very easy to read.

**Comment by Frenzie** [comment]
> If we can avoid keeping compatibility with actual settings I would propose to store a table per format under the "exporter" setting.

Users would ideally like a migration I'm sure, but I don't know how important that is. Downwards compatibility probably isn't very important.

**Comment by pazos** [comment]
> Users would ideally like a migration I'm sure, but I don't know how important that is. Downwards compatibility probably isn't very important at all.

I think it is doable but probably a PITA.

I sketched some changes on the menus:

## plugin main menu
![1](https://user-images.githubusercontent.com/975883/152649144-71919a3a-6b22-408f-92bc-6dab4e606767.png)

## formats and services submenu
![2](https://user-images.githubusercontent.com/975883/152649156-5a873910-7bbe-42b4-b831-9e5d45ea5a60.png)

The idea is querying each target `getMenuTable` function. The generic target provides an implementation which is just a checkbox to enable/disable the format, which is mostly fine for local files without tweakable options.

Stuff like joplin or readwise, which require some other settings, should implement a custom `getMenuTable` function to provide their own menu with their own settings.

Also the generic target provides a function called `isEnabled` which returns `self.settings.enabled`. In the case of joplin to should return `self.settings.enabled and self.settings.ip and self.settings.port` as these are required for the plugin to work.

**Comment by pazos** [comment]
Ataching the quick and dirty sketch. Nothing is really implemented yet but you can see how the new code will look after the refactor
[exporter-new.koplugin.zip](https://github.com/koreader/koreader/files/8008342/exporter-new.koplugin.zip)
.

**Comment by Frenzie** [comment]
Looks good to me from the code perspective. :+1:

**Comment by uroybd** [comment]
Currently, I can see that in the case of text and JSON exports are being appended to `KOReaderClipping.json` or `KOReaderClipping.txt`.

While it might not be a problem for text exports, it is a problem for JSON. For example, after 3 exports the clippings JSON file will look like this:

```json
{...export 1 data}
{...export 2 data}
{...export 3 data}
```

It is obviously an invalid format for JSON.

I propose that we create separate files for exports. Here are some examples:

#### For Single Book:
`{timestamp}-{truncated title/filename}.json`

#### For All Books
`{timestamp}-all-notes.json`

A similar scheme can be taken for other formats.

**Comment by pazos** [comment]
@uroybd: indeed. Added to the task pile :p

**Comment by uroybd** [comment]
> @uroybd: indeed. Added to the task pile :p 

I'm willing to work on this it you wish.

**Comment by uroybd** [comment]
I've 2 ideas regarding the new export plugin.

1. *Version number*: a version scheme for every export format. e.g. `json/1.0.0` included in the export file. This will allow the exporter plugin to evolve safely.
2. Exportation Timestamp in the file. Like, for JSON, a top-level field containing it.

**Comment by pazos** [comment]
Also related to json export:

- switch to rapidjson (it's way faster, it supports pretty print, it has a `dump` function that takes care of file writting the contents of the table to a json file)

**Comment by uroybd** [comment]
Organizing data means a lot to me. Therefore, I am very much excited about this refactor and want to work on this. Please let me know how I can help.

**Comment by pazos** [comment]
I need help testing both readwise and joplin exports.

Also feedback about the rest of formats, so nothing breaks after the refactor.

The refactor shouldn't change the behaviour of the plugin (other than fixing the export of multiple documents on non appendable files)

Any other change can be done after the refactor but makes my life harder in between.

If you want to help with the refactor itself I can push a PR for you to test so we can both work on the same codebase without too much trouble.

**Comment by uroybd** [comment]
> I need help testing both readwise and joplin exports.
> 
> Also feedback about the rest of formats, so nothing breaks after the refactor.
> 
> The refactor shouldn't change the behaviour of the plugin (other than fixing the export of multiple documents on non appendable files)
> 
> Any other change can be done after the refactor but makes my life harder in between.
> 
> If you want to help with the refactor itself I can push a PR for you to test so we can both work on the same codebase without too much trouble.

I'm in!

**Comment by uroybd** [comment]
@pazos 
> If you want to help with the refactor itself I can push a PR for you to test so we can both work on the same codebase without too much trouble.

Can you please create a PR? I'm relatively free nowadays and can use the time for this.

**Comment by pazos** [comment]
@uroybd: I need some free time to submit something that makes sense and document how is intended to work. I'm going to push the results to my own branch and accept PRs there, so you can contribute.

In the mean time you can dig and start to play with the sample code I posted earlier.

TBH: I actually spent more time talking about it than working on it and I don't like the experience :/. If you're in a rush I would happily unassign myself from this ticket and step back so you and others can do whatever you want with the plugin.

My intention with the deprecation of the old evernote plugin and this refactor is preventing a hot potato that isn't maintainable anymore. Any work towards this is welcome.

**Comment by uroybd** [comment]
> In the mean time you can dig and start to play with the sample code I posted earlier.

@pazos 
I'll start this since you're kinda busy now. Please don't unassign yourself. If I can do anything substantial, we can take that and use that as a starting point when you create you're branch.

**Comment by uroybd** [comment]
I've created a branch to work on this.

Initially, I've just used the `clip.lua` from the old package to get notes. I've successfully generated valid, timestamped, JSON files from single and all books.

Initially, I thought, I can check for how many books are in the data and determine output file name and structure based on that. However, even if I have only one book with highlights and I choose to export from all books, I should get the data in the structure of all books.

**Comment by uroybd** [comment]
Now I have pushed the HTML export too.

**Comment by uroybd** [comment]
Added a markdown export which is lighter than HTML, richer than text.

**Comment by uroybd** [comment]
1. write a GenericTarget that implements common code for exporters.
2. write each exporter as a subclass of GenericTarget that implements exportOne and exportAll functions.
3. write an intermediate representation of the notes (a lua table dumped with persist, maybe?) that can be handled by all targets.
4. handle multiple selection (export to more than one format at the same time)

No. 1 and No. 4 has already been done by @pazos 

I need some guidance regarding No. 3. Currently, I'm using `clip.lua` from the old plugin with some normalization for a better service development experience. It has some sort of persistence, right?

I've done the No. 2, along with markdown export and other adjustments.

Have to work on readwise. I have Joplin, so I can test that. I will require help for readwise.

**Comment by uroybd** [comment]
I managed to integrate Joplin. There are rough edges though.

**Comment by uroybd** [comment]
Here's a PR: #8944

**Comment by pazos** [comment]
@uroybd: great job! and very quick BTW. 


Just skimmed a bit over your WIP PR and have a few comments based on that (and comments I need to answer here).

> write each exporter as a subclass of GenericTarget that implements exportOne and exportAll functions.

I wrote that before playing with the plugin. I ended up with the idea of a single export that acts like `exportOne` if `#t == 1` and `exportAll` elsewhere.

This might require building a table of a single element when we want to export a single document but reduces the boilerplate everywhere.

> 3. write an intermediate representation of the notes (a lua table dumped with persist, maybe?) that can be handled by all targets.
>I need some guidance regarding No. 3. Currently, I'm using clip.lua from the old plugin with some normalization for a better service development experience. It has some sort of persistence, right?

If you fed all exporters with `clippings` table then we're good with that. I can't remember why I phrased the task the way I did. Maybe because I had the idea of writting unit test on that "intermediate representation"?. You can forget pretty much about that point for now :)

I see you embedded joplinClient inside the exporter. I would like to keep it as is in a separate file (same for readwise). Both exporters could have a `client` loaded at init and work on top of that. Makes easier to understand files if there's only one "class" on them ;)

The other thing I've noticed is that you've added functions to retrieve timestamps and filenames. If they all follow the same pattern you can add a new element of each exporter class called `extension` and add just a function to `BaseExporter` that gets the filename based on `self.extension`

All my comments here can be discussed and addressed latter. Keep the **very** good work :+1:

**Comment by uroybd** [comment]
> >  write each exporter as a subclass of GenericTarget that implements exportOne and exportAll functions.
>
> I wrote that before playing with the plugin. I ended up with the idea of a single export that acts like `exportOne` if `#t == 1` and `exportAll` elsewhere.

I remember agreeing with you on this. :p However, while working on this, I found `exportOne` and `exportAll` are more appropriate. If an exporter uses different representations for `all` and `one`, a single export method can make some confusion. If a user exports all, she/he should get a data structure for `all` even there are only one document exportable. That's why I implemented this approach. If any exporter doesn't handle things that way, it can simply use the way of `html` or `markdown` exporters' approach.

> If you fed all exporters with clippings table then we're good with that. 

I actually normalized a bit here. Remember the unnecessary nested arrays with only one item in them? I've flattened them. Now, for a single book, I feed a single clipping object, and for all, an array-like table for that. This actually costs one less loop in the third level of generation.

I'm moving clients to the `clients` folder, and doing as you have said about extension.

Thanks for your feedbacks @pazos :smile:

**Comment by uroybd** [comment]
Implemented Readwise support. Currently, this plugin is on par, even better than the old one I believe.

**Comment by uroybd** [comment]
Btw, We should take advantage of markdown support in Joplin export. You can test my markdown export's output. It is nicer I guess. We can feed just that to Joplin.

**Comment by uroybd** [comment]
I was toying with the HTML export. I managed to introduce a toggleable bookmark style feature without any need for JavaScript. Here's an example
[2022-03-24 11:17:58-শিক্ষা.zip](https://github.com/koreader/koreader/files/8338635/2022-03-24.11.17.58-.zip)
.
