### ISSUE TITLE
FR: Migrate data from Kobo E-Reader to Koreader

### ISSUE THREAD

**Issue by JVT038** [koreader/koreader#8761]
**Does your feature request involve difficulty completing a task? Please describe.**
I want to transfer my reading data (such as the time read, which books I have read, all the annotations / notes I have made, etc.) to Koreader. This is currently not possible, as far as I know

**Describe the solution you'd like**
Some kind of button, which can trigger a process that imports all the data from the `KoboReader.sqlite` file.

**Comment by NiLuJe** [comment]
(I'm wondering whether this should be tagged as "out of scope", because, duh' ^^).

**Comment by JVT038** [comment]
I actually made that thread on mobileread.com. I opened this issue here, because the only comment in that thread didn't really give me the right solution, so I thought that people here might have a solution to my answer.

**Comment by pazos** [comment]
> I actually made that thread on mobileread.com. I opened this issue here, because the only comment in that thread didn't really give me the right solution, so I thought that people here might have a solution to my answer.

@JVT038: there's no solution, I'm afraid.

From the PoV of KOReader kobo is just another app we cannot control and has no APIs. So I agree with @NiLuJe, it is totally out of scope to be able to import from them.

If somebody writes the code to import highlights and other metadata from a specific program it would be nice to have it documented on the wiki & forum. No matter if the program is Kobo, remarkable, MoonReader or foliate ;)

**Comment by JVT038** [comment]
Alright then, I guess I can look into this myself, as I have some knowledge about SQL and Python. Thank you for your help anyway!

**Comment by Frenzie** [comment]
@JVT038 Note that in this context the Python serves as documentation and of course you could use it as a starting point for modification but you should also be able to do the same thing from Lua in a KOReader plugin.

Most obviously, see the statistics plugin for some sample code.

(fairly random samples from the code that are doing something with SQL, I don't mean to imply these are necessarily the most relevant samples)
https://github.com/koreader/koreader/blob/035b24bb812488ce5506ca01eadf25844f51d7eb/plugins/statistics.koplugin/main.lua#L302-L311

https://github.com/koreader/koreader/blob/035b24bb812488ce5506ca01eadf25844f51d7eb/plugins/statistics.koplugin/main.lua#L596-L687

NB I'm not saying you should use Lua, but it would have the advantage of not having to ensure that you can run Python on your device. (Although in between chroot and @NiLuJe's KoboStuff, that's not particularly hard to do.)

**Comment by JVT038** [comment]
Is it necessary to use Lua? I have absolutely no experience with the language, and it could take a while for me to develop an advanced extension in an unknown language..

Isn't there a way to run Python code?

**Comment by Frenzie** [comment]
As @NiLuJe said, you can just grab [this](https://www.mobileread.com/forums/showthread.php?t=254214). I'm just saying that'll make it very n=1.
