### ISSUE TITLE
KOReader crashing while sleeping/switches screen orientation while sleeping

### ISSUE THREAD

**Issue by LionelHart** [koreader/koreader#8762]
* KOReader version: nightly
* Device: Kobo Clara HD

#### Issue 
I've been reading a large (10mb) book in landscape mode with other innocuous style tweaks. Starting this weekend the orientation would switch, but only in part of the screen and while asleep; I've since determined that it does happen later by checking that the screen is fine when put to sleep only to get wonky when I return later. When I return to the book after rebooting it opens in portrait orientation with the pullup menu indicating portrait as well, but when I hold down the menu it says that the screen orientation is set to 90 degrees (aka landscape). This issue has become system wide, now affecting other PDFs and books in landscape and now, as of an hour ago, even crashing when sleeping in middle of reading a newly-downloaded book being read only in portrait. I've attached a photo below of the issue but with a different file.

Thanks for reading.

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/fi

UPDATED: [crash.log](https://github.com/koreader/koreader/files/7984083/crash.log)
les/7982529/crash.log)

![0](https://user-images.githubusercontent.com/98855049/152067488-34394e38-4fe7-42c7-8de3-5e31b0688bd7.jpg)

**Comment by NiLuJe** [comment]
I'm not seeing any crash in there, what would have been the local timestamp for it?

Also, while we can infer from the snapshot, what are your exact Screensaver settings?

**Comment by LionelHart** [comment]
> I'm not seeing any crash in there, what would have been the local timestamp for it?
> 
> Also, while we can infer from the snapshot, what are your exact Screensaver settings?

Thanks for responding. As is probably evident I'm a total noob and clueless about all this. My friend/jungle-guide guided me to turn on verbose debugging which meant that the log I sent in the OP was already out of date. I'm trying to replicate the crash again and will post an updated crash log.

My screensaver settings are: 'leave screen as is', and 'add message to screen' (the message is "page number", "/", "pages in book", "Ari's Kobo".

**Comment by LionelHart** [comment]
Updated crash log, hope this is more informative.
[crash.log](https://github.com/koreader/koreader/files/7984079/crash.log)


> I'm not seeing any crash in there, what would have been the local timestamp for it?
> 
> Also, while we can infer from the snapshot, what are your exact Screensaver settings?

**Comment by NiLuJe** [comment]
The only weird thing I see in this one is the log being cut-off at `14:55:22`, and then KOReader booting up much later at `15:28:19`.

While the first could be a sign of a hard reboot, it doesn't make much sense, unless you really let the device hung for half an hour ;).

**Comment by LionelHart** [comment]
> The only weird thing I see in this one is the log being cut-off at `14:55:22`, and then KOReader booting up much later at `15:28:19`.
> 
> While the first could be a sign of a hard reboot, it doesn't make much sense, unless you really left the device hung for half an hour ;).

could've totally happened... my wife uses it too sometimes :-)

**Comment by LionelHart** [comment]
Update: On the suggestion of a friend I turned off the auto suspend plugin, which seems (over the past two days) to have stopped the crashing, but the Kobo still doesn't keep the set orientation between readings.

**Comment by NiLuJe** [comment]
Verbose debug logs might help further diagnose this (In the FM: Tools > More tools > Developer options)

**Comment by NiLuJe** [comment]
xref w/ #8842 for the layout issue ;).
