### ISSUE TITLE
FR: Enabling chapter markers with thin progressbar

### ISSUE THREAD

**Issue by molivier-fcms** [koreader/koreader#8765]
Hi,

As I see it, the differences with thick and thin progress bar at the bottom are minors, yet I do prefer the thin version (less attractive to the eye in my case). However I have only one regret: chapter markers can be enabled only with thick version.

Could it be possible to enable markers with thin version as well ? As KOReader is very customizable, the user shouldn't be limited in his choice to enable it or disable, don't you think?

**Comment by offset-torque** [comment]
+1 for this. I would use the thinner one if it had chapter marks.

**Comment by hius07** [comment]
Progress bar style (thin, thick, smth else) is defined with 4 colours: border, background, filler, alt filler.
Maybe users would be happy to have a setting to choose these colours and draw their own lovely bar?

![2](https://user-images.githubusercontent.com/62179190/152151349-f7cc0344-171a-4e6a-8b5c-9908d2cbfc76.png)

**Comment by offset-torque** [comment]
>  Maybe users would be happy to have a setting to choose these colours and draw their own lovely bar?

That would be really cool. There are contrast ratio differences between screens (grayish older ones vs nearly white Carta 1200). This way users can choose colors according to their e-reader and taste (like darker grays for older ones, lighter colors for newer generation).

In this case for example setting `border` to "white" will create the thinner version I guess.

**Comment by molivier-fcms** [comment]
The first step would be to neutralize this limitation : https://github.com/koreader/koreader/blob/035b24bb812488ce5506ca01eadf25844f51d7eb/frontend/apps/reader/modules/readerfooter.lua#L1755-L1757

I tried to dig the "why" of this lock. It seems related to this particular comment (https://github.com/koreader/koreader/pull/5442#issuecomment-537628268) which says : 

> To expand on what @poire-z said, I'd propose Simple for the "thin/line" style, and I don't think it ought to support chapter ticks, as that kind of defeats the simplistic design.

I understand the minimalistic logic, but I don't see any real reason to prevent people to enable the markers.

@hius07 Your suggestion should be studied with care. Don't you take the risk to bloat koreader this way?

**Comment by poire-z** [comment]
> I tried to dig the "why" of this lock. 

Dunno, possibly arbitrary.
But best for you to try hacking it to see how it would look and post a screenshot.

> don't you take the risk to bloat koreader with a such level of customization?

I would indeed find this color tweaking a bit overkill. (But if there's one area where we are already overkill, it's the footer :) and I could understand the need for extreme tweaking to make the footer to one's liking, as it's something one always has under its nose :) so, well, anywhere else I would object more vividly).

> There are contrast ratio differences between screens (grayish older ones vs nearly white Carta 1200). This way users can choose colors according to their e-reader and taste (like darker grays for older ones, lighter colors for newer generation).

It this is really a thing (I don't have different devices, so I can't say), and there's a need for tuning gray, I don't think we should go with color pickesr everywhere (because if we allow that for the footer, why not for each of the 3 or 4 tones of gray in the Skim widget !).
If it's really a thing, we should have a single area (under Screen>) where one would choose some "Gray constrast adjustement", and from this one place, we would tweak the values of each Blitbuffer.COLOR_LIGHTGRAY and al. to have all values lower or upper from the nominal values, so that it applies to every thing that uses these grays.
That is, if it's really a thing :) and people won't come knocking that this gray is good for the footer but not for the Skim widget or "disabled" menu items :)

**Comment by hius07** [comment]
> I guess here is our limitation:

And here
https://github.com/koreader/koreader/blob/cb7e670c4a73a21db0db829f67b8014658ce4bb2/frontend/ui/widget/progresswidget.lua#L203

**Comment by offset-torque** [comment]
> If this is really a thing (I don't have different devices, so I can't say)

**Libra vs my old reader from 2013 side-by-side under sunlight:**
![oldvsnew screen contrast](https://user-images.githubusercontent.com/84420582/152292812-4e78efc7-c823-4e76-8894-2f9d3ea9be98.png)

New `Carta 1200` used in Libra 2 is even better (~15% better contrast ratio than the Libra)

> I don't think we should go with color pickesr everywhere (because if we allow that for the footer, why not for each of the 3 or 4 tones of gray in the Skim widget !).

That's a slippery slope argument. No need to change everything, progress bar is different. I will be repeating myself: **Smaller elements needs higher contrast**. Skim widget is tall, which helps with visibility. If you limit skim widget to 5 pixels vertically, it will be hard to read too.

**This is my Libra screen starting here** ⬇️
![libra progressbar pixel sort](https://user-images.githubusercontent.com/84420582/152293438-54e1f08a-7003-423e-b2e3-cb5226acef93.png)
⬆️ **ending here.** 

Image shows the amount of pixels allocated to a default sized Progress Bar on a 70% read book (light=read/dark=chapter marks).
~0.2 percent of screen estate on a 7" screen is really tiny so even little changes improves usability.

**Comment by molivier-fcms** [comment]
Hi, some updates are. I managed to enabled markers with **thin** progress bar layout:
![progressbar_thin_chapter-markers](https://user-images.githubusercontent.com/39309715/152440506-8857fe32-abb9-42fe-a859-14fc8d572400.png)

Here is the code diff:
```lua
--- /mnt/onboard/.adds/koreader/frontend/apps/reader/modules/readerfooter.lua.backup
+++ /mnt/onboard/.adds/koreader/frontend/apps/reader/modules/readerfooter.lua
@@ -1755,9 +1755,6 @@
                         checked_func = function()
                             return self.settings.toc_markers == true
                         end,
-                        enabled_func = function()
-                            return not self.settings.progress_style_thin
-                        end,
                         callback = function()
                             self.settings.toc_markers = not self.settings.toc_markers
                             self:setTocMarkers()
@@ -1774,9 +1771,6 @@
                             end
                             return T(_("Chapter marker width (%1)"), markers_width_text)
                         end,
-                        enabled_func = function()
-                            return not self.settings.progress_style_thin and self.settings.toc_markers
-                        end,
                         sub_item_table = {
                             {
                                 text = _("Thin"),
@@ -2017,7 +2011,7 @@
 end

 function ReaderFooter:setTocMarkers(reset)
-    if self.settings.disable_progress_bar or self.settings.progress_style_thin then return end
+    if self.settings.disable_progress_bar then return end
     if reset then
         self.progress_bar.ticks = nil
         self.pages = self.ui.document:getPageCount()

```
The 2 firsts removal enabled `Show chapter markers` and `Chapter marker width` options, whereas the last modification ensure enabling is doing something.

Editing `koreader/frontend/ui/widget/progresswidget.lua` did not changed anything.

Do you want submit a PR for deeper checking?

**Comment by poire-z** [comment]
> Do you want I submit a PR for deeper checking?

Depends on how courageous you are at digging into a few other things to make it all perfect :)

![image](https://user-images.githubusercontent.com/24273478/152446598-ed3f0183-b150-4fee-810c-681444f86668.png) thin before

![image](https://user-images.githubusercontent.com/24273478/152446651-6550db2e-0114-4144-8e8a-1ce2eb0aba18.png) thin with chapter markers enabled

![image](https://user-images.githubusercontent.com/24273478/152446750-2b0ebe90-eba9-4307-b652-7956f5168447.png) thick with chapter markers

The gray values are ok when no marker, but the contrast is not too good with markers, so this might need some tweaks (different grays when markers ? Or same lighter gray, dunno.)

Also, when, with chapter markers enabled, you toggle thick>thin, the markers are not shown: you need to uncheck&check "Show chapter markers" to see them. So, possibly something to do in the parts when we handle the menu selection.

**Comment by molivier-fcms** [comment]
> Depends on how courageous you are at digging into a few other things to make it all perfect

Sure, I will take a look on theses points in the incoming days.

**Comment by molivier-fcms** [comment]
Dimming progress bar and background helps a bit.
Before:
![default](https://user-images.githubusercontent.com/39309715/152522730-9a5de05e-411c-4beb-9afb-991299de3d60.png)


After:
![dimmed](https://user-images.githubusercontent.com/39309715/152522427-b6f221c1-460f-4b73-9a27-75a0905707bb.png)

The diff:

```lua
molivier@Laptop:/usr/lib/koreader/frontend/ui/widget$ diff -u progresswidget.lua.backup progresswidget.lua
--- progresswidget.lua.backup   2022-02-04 09:40:20.939908022 +0100
+++ progresswidget.lua  2022-02-04 12:40:01.168636984 +0100
@@ -15,6 +15,7 @@
  * altcolor   -- color of the alt fill bar
  * ticks (list)  -- default to nil, use this if you want to insert markers
  * tick_width
+ * tickcolor  -- color of markers
  * last  -- maximum tick, used with ticks

 Example:
@@ -142,7 +143,7 @@
                          fill_y,
                          self.tick_width,
                          math.ceil(fill_height),
-                         self.bordercolor)
+                         self.tickcolor)
         end
     end
 end
@@ -198,9 +199,9 @@
         self.margin_v = 0
         self.bordersize = 0
         self.radius = 0
-        self.bgcolor = Blitbuffer.COLOR_GRAY
-        self.fillcolor = Blitbuffer.COLOR_DIM_GRAY
-        self.ticks = nil
+        self.bgcolor = Blitbuffer.COLOR_LIGHT_GRAY
+        self.fillcolor = Blitbuffer.COLOR_DARK_GRAY
+        self.tickcolor = Blitbuffer.COLOR_BACK
         self._orig_margin_v = nil
         self._orig_bordersize = nil
         if height then

```

**Comment by poire-z** [comment]
> I'll try to keep bars at they original shades and use LIGHT_GREY or GREY_E for markers then.

Then you risk _when it is crowded, making the past ticks white make it feel like no longer a progresss bar_  https://github.com/koreader/koreader/pull/8195#issuecomment-915172922

May be you got the answer to your "why for this lock" :/
Also see #8400 for some related discussion (I guess, haven't re-read it).

**Comment by molivier-fcms** [comment]
I was aware of #8195. But not #8400 indeed.

I think it is time to reshape the thin progressbar a little bit when chapter marks are enabled. I'll do some tests and show it to you soon.

**Comment by poire-z** [comment]
> (Are diffs useful for you at the moment, or do I only show the visual changes for now?)

Not necessarily - but they give us a preview of what awaits if you make a PR. Ie., you've probably broken the SkimWidget, that uses ticks too, but you don't define a default self.tickcolor.
Other stuff uses the progresswidget.lua you're hacking, so try to be the less disruptive possible, even if you're just testing to see how it looks - the less work later (for you and us) if you keep that in mind :)

But yes, just play and show screenshots, if you managed to get something that is good on linux and your Kobo.
We can work out the proper integration later.

**Comment by molivier-fcms** [comment]
Ok. I admit I never touched lua. To be honest the only code I really know is shell. :D

Here is a new attempt : 
![dimmed_border](https://user-images.githubusercontent.com/39309715/152557690-6dd3fa7c-6cb3-4cd4-92cf-15d72d3d63c7.png)

(before for reminder)
![default](https://user-images.githubusercontent.com/39309715/152522730-9a5de05e-411c-4beb-9afb-991299de3d60.png)

I "decreased" the shades, keeping a large interval of colors so it remains contrasty. For balancing the _almost_ white side on right I added a small border of 1px. It looks better, no?

Here is the settings in the progresswidget.lua:
```lua
        self.margin_h = 0
        self.margin_v = 0
        self.bordersize = 1
        self.radius = 0
        self.bgcolor = Blitbuffer.COLOR_GRAY_E
        self.fillcolor = Blitbuffer.COLOR_DARK_GRAY
        self.bordercolor = Blitbuffer.COLOR_DARK_GRAY
        self.tickcolor = Blitbuffer.COLOR_BLACK
```

**Comment by poire-z** [comment]
> I "decreased" the shades, keeping a large interval of colors so it remains contrasty. For balancing the almost white side on right I added a small border of 1px. It looks better, no?

So, with some borders, a bit taller, lighter gray, you made it a thick progress bar with ticks :) 
You could have started from the thick progress bar, remove rounded corners and margins, and you'd get the same result, no ?

**Comment by molivier-fcms** [comment]
Your're right. In fact the thick design inspired this version.

But I realize that the "before" version (the default thin version) looks nice on kobo, still readable with black ticks on dim grey bar, whereas on computer screen these colors are too close.
![20220204_230028](https://user-images.githubusercontent.com/39309715/152609182-4cc34653-3334-4aa7-a611-0c6661b5c1b1.jpg)

That tolds me ot will be hard to find a unique solution for every display technology.

**Comment by NiLuJe** [comment]
FWIW, the thin design was (heavily) inspired by a Kobo design update (no ticks either).

I don't actually read with the status bar shown, so my opinion doesn't hold much weight, but while I can possibly see the interest in making the colors configurable, I really like the KISS approach of the thin design (in every sense of the word ;p).

**Comment by molivier-fcms** [comment]
Here is what I suggest: I submit a pull request that enable chapter markers for the thin progressbar (current version).
Then we watch if one day someone comes with a better suggestion about contrast issues.

**Comment by poire-z** [comment]
May be use your modifications for a while on your device, to see if you really end up liking it and keep using it.

It feels a bit less pretty that the existing (limited) options, so it feels odd just to propose something not polished that people may not even use  - and have to tweak ReaderFooter to support the various toggling of thick/thin and markers (which felt needing some work when testing your first patch, dunno if you had fixed this since - feels like `ProgressWidget:updateStyle(thick, height)` might need a 3rd parameter: `with_ticks`)

(I get the feeling that this could/should be adressed differently - but I really don't want to think more about it :) or tweak our already fragile ReaderFooter and have to think about migrating settings - but just sharing these thoughts:
- your thin progressbar with markers has already gotten quite tall and thick (so you can see your markers), so the distinction thick/thin might be misleading
- it's the presence/absence of a frame/borders that allows using the color white or not for the unread part - and so the usable palette of grays depends on the frame, not thin/thick - and whether we have markers to show over the read/unread progress bar and distinguish from it
- the rounded corners may feel a bit rustic :) we're used to the current look, so probably hard to kill - but I think if we were adding that progress bar nowadays, we would not go with rounder corners
- the margins+rounded corners make the inner progress bar looks more like a line than in thin mode - so thick is actually a thiner line in a clunky container

)

**Comment by offset-torque** [comment]
> it's the presence/absence of a frame/borders that allows using the color white or not for the unread part - and so the usable palette of grays depends on the frame, not thin/thick - and whether we have markers to show over the read/unread progress bar and distinguish from it

The problem arises from needing three colors as poire-z explained.

But what if 
- we just remove the borders from the thick one
- keep the colors same
- and add this as a third option like "Minimal" without touching other bars

**We will end up with something like this:**
![thin bar](https://user-images.githubusercontent.com/84420582/152662191-f4f7e885-d95e-4062-a39c-f43de2daa3ec.png)

**PROS:**
- Book starts from left border, ends at right border
- Needs just two colors which we already use now
- We don't touch already existing thin bar

**CONS:**
- Might look a bit ugly with floating chapter marks
- Won't look good when used on same line with other items (not full screen width)

But hey why not give users a choice. I would definitely use this.
Maybe moving it under other items so it will be even less distracting/flush with screen bottom. Pretty minimalist, isn't it:
![thin bar 2](https://user-images.githubusercontent.com/84420582/152662347-facf0c06-75dd-46a3-bf13-f052da8a20c3.png)

**Comment by NiLuJe** [comment]
Floating ticks are weird.

**Comment by shuvashish76** [comment]
Please add user patch available label,

**Comment by molivier-io** [comment]
It works well. Thank you @sebdelsol.

I'm adding user manual link about patching, for those who read this issue and want to apply it:
https://github.com/koreader/koreader/wiki/User-patches
