### ISSUE TITLE
New crashes

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8768]
* KOReader version: v. 2022.01-51
* Device: PB 628

#### Issue
After several days without any problem, I give here the relevant file in case someone would like to have a look
[crash 1&2-2-2022.txt](https://github.com/koreader/koreader/files/7993393/crash.1.2-2-2022.txt)
.

**Comment by NiLuJe** [comment]
Possibly harmless, but maybe significant: the AutoStandby stuff triggers a lot of `UIManager:_beforeSuspend` calls, which call `Input:resetState` (visible as the recurrent clock source probes in the logs).

As for the actual crashes, you seem to be tripping on action-less scheduled tasks, which should never happen.

Try to enable debug logging, as this should catch empty actions at *schedule* time, which may shed some light as to the source of these...

**Comment by ichnilatis-gr** [comment]
Today I had another, while reading an epub book.
[crash 4-2-2022.txt](https://github.com/koreader/koreader/files/8001122/crash.4-2-2022.txt)

I'll try to enable debug logging, even though I don't know what it is exactly and how works... :-)

**Comment by NiLuJe** [comment]
In the FM > Tools > More tools > Developer options

**Comment by ichnilatis-gr** [comment]
Where are the data of debug logging saved?

**Comment by Frenzie** [comment]
The same crash.log file, just with a bit more in it.

**Comment by ichnilatis-gr** [comment]
Thank you. I will let you know after the next crash. Sorry for the constant annoyances on is issue.

**Comment by Frenzie** [comment]
Testing is very helpful. Though it doesn't help that we don't have any PB devices. :-)

**Comment by poire-z** [comment]
Closing, as lack of @ichnilatis-gr annoyances indicates this must have been solved :)
