### ISSUE TITLE
Paragraph first-line indentation (style tweak) is not active on epub file format

### ISSUE THREAD

**Issue by yukari186** [koreader/koreader#8770]
* KOReader version: 2022.01-75
* Device: Kobo Clara HD

As title, paragraph first-line indentation (style tweak) is not active on my epub files, it only has been active when I reset document settings to default. I have tried text-indent code in my user style tweak but it is only active on the txt file format. My koreader version is 2022.01-75. Please help me fix it, thank you so much 💕

**Comment by poire-z** [comment]
> is not active on my epub files, it only has been active when I reset document settings to default

Not sure I understand what you mean :/ Does this happen on all your EPUBs? Or just some specific ones?
Things to check:
- `Style>` epub.css or html.css (and not none), or let "auto" as the default
- If you don't have user style tweaks of yours (enabled by default?) that would mess/override our style tweaks
- If on some specific EPUBs, check with View HTML that the text in indeed in `<P>` tags, and not in `<DIV>` tags or others, as our style tweaks for first line indentation apply only on `<P>`.

**Comment by yukari186** [comment]
> > is not active on my epub files, it only has been active when I reset document settings to default
> 
> Not sure I understand what you mean :/ Does this happen on all your EPUBs? Or just some specific ones? Things to check:
> 
> * `Style>` epub.css or html.css (and not none), or let "auto" as the default
> * If you don't have user style tweaks of yours (enabled by default?) that would mess/override our style tweaks
> * If on some specific EPUBs, check with View HTML that the text is indeed in `<P>` tags, and not in `<DIV>` tags or others, as our style tweaks for first line indentation apply only on `<P>`.

I tested many epub files and it is not active at all, including lasted download files and old files I copy again on device. Everything is only normal when I click reset document setting. I always choose style>none when I began to use koreader. My user style tweak is below the picture, it is only active on text files.
![IMG_20220203_205250_876](https://user-images.githubusercontent.com/90317108/152356181-74e0c04e-ad64-4d3d-aef8-bacfe45e562e.jpg)

**Comment by poire-z** [comment]
> My user style tweak is below the picture, it is only active on text files.

Shouldn't have any impact on EPUBs whether it is active or not.
But how do you ensure "it is only active on text files" ? Manually ?

> I always choose style>none when I began to use koreader.

Dunno why you decided that, but I tested that "none" + first line indentation style tweaks, and it works for me.

> Everything is only normal when I click reset document setting.

So, you have something else that sets some style or styletweaks on book opening (or old settings) - and that gets reset by "Reset document setting".
You get to find what this is. docsettingtweak plugin may be?

No other idea :/

**Comment by yukari186** [comment]
> > My user style tweak is below the picture, it is only active on text files.
> 
> Shouldn't have any impact on EPUBs whether it is active or not. But how do you ensure "it is only active on text files" ? Manually ?
> 
Style tweak>>paragraph>>paragraph first-line... is always not working on text file. User style can solve this problem but it does not work on my epubs file.

> > I always choose style>none when I began to use koreader.
> 
I decided that coz I usually read both epub and text files. I cannot apply other fonts on text files if using auto or epub.css.
> Dunno why you decided that, but I tested that "none" + first line indentation style tweaks, and it works for me.
>
 Oh, looks like there is a problem with my device. Maybe I want to check more time for determining where is the problem 😵 
> > Everything is only normal when I click reset document setting.
> 
> So, you have something else that sets some style or styletweaks on book opening (or old settings) - and that gets reset by "Reset document setting". You get to find what this is. docsettingtweak plugin may be?
> 
> No other idea :/

**Comment by poire-z** [comment]
Open a new epub file (never opened before). Check that you get no text-indent, with or without the style tweak.
Close it, exit KOReader, copy the book.sdr/metadata.epub.lua on your computer, rename it metadata.epub.lua.INITIAL.
Launch KOReader, open that same epub file, `Reset document settings to default`. Reload the document if needed. Check that you get your text-indent. Do you? If not, apply the style tweak. Do you ?
Close it, exit KOReader, copy the book.sdr/metadata.epub.lua on your computer.

Compare the 2 files (the content is not sorted, so it might be tricky comparing, you can post both files here if you need some help, I'm rather curious on what's happening to you :)

> I decided that coz I usually read both epub and text files. I cannot apply other fonts on text files if using auto or epub.css.

You could solve this with a style tweak that would apply to all books, just add:
```css
pre {
    -cr-only-if: txt-document; /* this makes everything after apply only if a txt document */
        text-indent: 1.2em;
        font-family: inherit;
}
```

This would override what we have for real PRE in epub.css only with txt documents:
```css
pre, xmp {
    white-space: pre; /* has to be set in fb2def.h to work */
    font-family: "Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono", monospace;
    text-align: left;
    margin-top: 0.5em;
    margin-bottom: 0.5em;
}
```
(May be we should have this kind of trick there in epub.css, as we know that with txt files, PRE are not real pre and just use to keep some plain text feature like consecutive spaces. But oh, yes, Ascii arts fan would be disapointed without a monospace font... So, may be we should have a style tweak to just kill the monospace font with txt documents.)

**Comment by yukari186** [comment]
`>

**Comment by yukari186** [comment]
> Open a new epub file (never opened before). Check that you get no text-indent, with or without the style tweak. Close it, exit KOReader, copy the book.sdr/metadata.epub.lua on your computer, rename it metadata.epub.lua.INITIAL. Launch KOReader, open that same epub file, `Reset document settings to default`. Reload the document if needed. Check that you get your text-indent. Do you? If not, apply the style tweak. Do you ? Close it, exit KOReader, copy the book.sdr/metadata.epub.lua on your computer.
> 
> Compare the 2 files (the content is not sorted, so it might be tricky comparing, you can post both files here if you need some help, I'm rather curious on what's happening to you :)
>
I've compared by app. Please help me check in below pictures.

> > I decided that coz I usually read both epub and text files. I cannot apply other fonts on text files if using auto or epub.css.
> 
> You could solve this with a style tweak that would apply to all books, just add:
> 
> ```css
> pre {
>     -cr-only-if: txt-document; /* this makes everything after apply only if a txt document */
>         text-indent: 1.2em;
>         font-family: inherit;
> }
> ```
> 
> This would override what we have for real PRE in epub.css only with txt documents:
> 
> ```css
> pre, xmp {
>     white-space: pre; /* has to be set in fb2def.h to work */
>     font-family: "Droid Sans Mono", "Liberation Mono", "DeJaVu Sans Mono", monospace;
>     text-align: left;
>     margin-top: 0.5em;
>     margin-bottom: 0.5em;
> }
> ```
> 
I know user style tweak can solve this but I'm I'm too lazy to figure it 🤣 Moreover, I don't think many people will care, so I'm afraid to ask on the forum. I will try according to your instructions 💕
> (May be we should have this kind of trick there in epub.css, as we know that with txt files, PRE are not real pre and just use to keep some plain text feature like consecutive spaces. But oh, yes, Ascii arts fan would be disapointed without a monospace font... So, may be we should have a style tweak to just kill the monospace font with txt documents.)

**Comment by yukari186** [comment]
![01](https://user-images.githubusercontent.com/90317108/152388829-382056ac-dc45-4882-a14e-04558936efd1.PNG)
![02](https://user-images.githubusercontent.com/90317108/152388845-6ec1b4b2-6725-4a0d-a5db-ea4118029ca3.PNG)
![03](https://user-images.githubusercontent.com/90317108/152388849-ab9d400d-f168-4e18-b99b-df7719245178.PNG)
![04](https://user-images.githubusercontent.com/90317108/152388856-7689629e-d8a5-4119-9142-c6ae310540cf.PNG)
![05](https://user-images.githubusercontent.com/90317108/152388860-fc7d5f93-91bd-463f-8709-75a1aded12d6.PNG)

**Comment by poire-z** [comment]
(Hard to compare if you don't sort them.)
But nothing jumps out if I try to look at what has changed on both sides. So, I can't say much :/

**Comment by yukari186** [comment]
> (Thật khó để so sánh nếu bạn không sắp xếp chúng.) Nhưng không có gì nhảy ra nếu tôi cố gắng nhìn vào những gì đã thay đổi ở cả hai bên. Vì vậy, tôi không thể nói nhiều :/



> (Hard to compare if you don't sort them.) But nothing jumps out if I try to look at what has changed on both sides. So, I can't say much :/

Oh sorry, I don't dare to sort it because I'm afraid it's messy or accidentally delete something. I attach word files for you researching. However, no need to focus on solving it, just do it for fun. I love setting up koreader to my own needs, maybe in that process I accidentally made it crazy. Thank you for always supporting so so so enthusiastically!
[metadata.docx](https://github.com/koreader/koreader/files/7996818/metadata.docx)
[metadata.epub (no text indent).docx](https://github.com/koreader/koreader/files/7996819/metadata.epub.no.text.indent.docx)

**Comment by yukari186** [comment]
> (Hard to compare if you don't sort them.) But nothing jumps out if I try to look at what has changed on both sides. So, I can't say much :/

Oh sorry, I don't dare to sort it because I'm afraid it's messy or accidentally delete something. I attach word files for you researching. However, no need to focus on solving it, just do it for fun. I love setting up koreader to my own needs, maybe in that process I accidentally made it crazy. Thank you for always supporting so so so enthusiastically!
[metadata.docx](https://github.com/koreader/koreader/files/7996833/metadata.docx)
[metadata.epub (no text indent).docx](https://github.com/koreader/koreader/files/7996834/metadata.epub.no.text.indent.docx)

**Comment by poire-z** [comment]
OK, the only noticable difference is:
```diff
<["copt_block_rendering_mode"] = 0,
-
>["copt_block_rendering_mode"] = 2,
```
That's Render mode in the bottom menu: 0=legacy, 2 = book.
So, may be something with that ?

**Comment by yukari186** [comment]
> OK, the only noticable difference is:
> 
> ```diff
> <["copt_block_rendering_mode"] = 0,
> -
> >["copt_block_rendering_mode"] = 2,
> ```
> 
> That's Render mode in the bottom menu: 0=legacy, 2 = book. So, may be something with that ?

Yup, that's right. I chosen reset setting, fix ["copt_block_rendering_mode"]=2 -> 0 and reopened ebook, everything is back to normal. But if I chosen reset setting or open new epub file, ["copt_block_rendering_mode"] will be became =2 again, maybe 2 is default value. I need do what for it always =0?😅

**Comment by cameronj86** [comment]
Just a datapoint for future users. I had the same issue but it was upstream based on the ePub having quirky formatting issue from Calibre that were overriding the KOReader settings. My fix was the following book-specific tweak:

```css
div.calibre4, div.calibre_7 {
    margin-top: 0 !important;
    margin-bottom: 0.7em !important;
    text-indent: 1.2em !important;
}
```
