### ISSUE TITLE
After multi-file move, some files cannot be opened from the history menu

### ISSUE THREAD

**Issue by mrdk** [koreader/koreader#8779]
* KOReader version: 2022.01

#### Issue
Almost the same issue as #8575, except for multi-file movement of files. If several files are moved to a different directory, some of them cannot be opened from the history, while others can. It seems that the file with the highest position in the history menu can be opened but others cannot, but I do not know whether this is always the case.

**Comment by hius07** [comment]
Until it is fixed, the same workaround works: restart KOReader.
