### ISSUE TITLE
KOreader crashes after attempting use of Calibre plugin

### ISSUE THREAD

**Issue by solarkite** [koreader/koreader#8783]
* KOReader version: latest nightly 2022.01-82
* Device:KV

In trying to connect to Calibre wirelessly, KOreader crashes. Happens just after tapping the "Calibre" button in the pluggin to activate.
No problem with OPDS for local library transfer.
I reverted to the last stable, and the calibre plugin seemed to connect and transfer files without problems.

[crash.log](https://github.com/koreader/koreader/files/8011178/crash.log)

**Comment by NiLuJe** [comment]
```
./luajit: plugins/calibre.koplugin/metadata.lua:141: error while open file: /mnt/us/epub/.metadata.calibre
stack traceback:
	[C]: in function 'dump'
	plugins/calibre.koplugin/metadata.lua:141: in function 'saveBookList'
	plugins/calibre.koplugin/metadata.lua:210: in function 'cleanUnused'
	plugins/calibre.koplugin/metadata.lua:267: in function 'init'
	plugins/calibre.koplugin/wireless.lua:258: in function 'connect'
	plugins/calibre.koplugin/main.lua:93: in function 'callback'
	frontend/ui/widget/touchmenu.lua:857: in function 'onMenuSelect'
	frontend/ui/widget/touchmenu.lua:202: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:263: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:95: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:113: in function 'handleEvent'
	frontend/ui/uimanager.lua:1119: in function 'sendEvent'
	frontend/ui/uimanager.lua:53: in function '__default__'
	frontend/ui/uimanager.lua:1603: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1683: in function 'handleInput'
	frontend/ui/uimanager.lua:1734: in function 'run'
	./reader.lua:323: in main chunk
	[C]: at 0x00013ef9
```

Seems to be a throughly unhelpful crash in RapidJSON's `dump` function :?.

Is the file (`/mnt/us/epub/.metadata.calibre`) actually still here/sane?

**Comment by solarkite** [comment]
A few days ago, I did try to change the main storage to something different. But the plug-in kept storing in the old location rather than the new location. I deleted the folder. Now what do I do?

**Comment by NiLuJe** [comment]
Main storage of what?

**Comment by solarkite** [comment]
Nothing weird. Every time I tried to set the main folder to a new location it would ignore me and save books at the old location.

**Comment by NiLuJe** [comment]
Main folder of what?

**Comment by solarkite** [comment]
KOREADER’s Home folder
![Uploading image.jpg…]()

**Comment by NiLuJe** [comment]
That's because this isn't how you tell the Calibre plugin to store books elsewhere: the Calibre plugin has a dedicated section for that ;).

**Comment by solarkite** [comment]
I did that too. That makes KOreader crash

**Comment by solarkite** [comment]
I reinstalled KOreader manually. That seems to have helped. It’s now connecting with caliber. No crashes. And using the assigned home folder. Thanks for your attention to the issues @NiLuJe

**Comment by NiLuJe** [comment]
Possibly some shenanigans when switching from one Calibre library to another, then... ping @pazos

**Comment by pazos** [comment]
Nothing actionable here.

If you get a crash again attach the file where it crashs. In your example

`plugins/calibre.koplugin/metadata.lua:141: error while open file: /mnt/us/epub/.metadata.calibre` it would be `/mnt/us/epub/.metadata.calibre`
