### ISSUE TITLE
12 hour format in alt status bar

### ISSUE THREAD

**Issue by mendelct** [koreader/koreader#8790]
* KOReader version:2022 01-82
* Device: emulator

#### Issue
When the device is set to display 12 hour format, during the 12am hour the alt status bar displays 0: instead of 12. This happens on android as well. See #6969
![koreader](https://user-images.githubusercontent.com/67393493/153027108-654d28f8-ab71-4161-b6b3-07c0e073f477.jpg)
#### Steps to reproduce
Set display to 12 hour format and set time to 12am
##### `crash.log` (if applicable)
N/A

**Comment by zwim** [comment]
The alt status bar is showing the correct time. e.g. 12:15 AM -> 00:15 see https://www.freecodecamp.org/news/mathematics-converting-am-pm-to-24-hour-clock/

The alt status bar is always showing the clock in 24h mode. This is hard coded in crengine.

**Comment by mendelct** [comment]
Just tested this the alt status bar shows 12h format in the emulator.

**Comment by mendelct** [comment]
![koreader](https://user-images.githubusercontent.com/67393493/153045154-83013a97-7aa4-47a1-a0cb-0229276c67f9.jpg)

**Comment by zwim** [comment]
Indeed, you are right. Then I have missed something in the past.

**Comment by poire-z** [comment]
(not yet bumped, no hurry)

**Comment by mendelct** [comment]
This corrects the the 0 instead of 12 issue but creates a leading 0 issue. See #6969 mentioned above. Here is a screenshot.
![koreader](https://user-images.githubusercontent.com/67393493/159147066-b62767f3-29c5-4928-8b26-f12f20066f6d.jpg)

See the difference between the status bar below and the alt status bar

**Comment by NiLuJe** [comment]
That is on purpose, doing it the same way requires platform-specific trickery which are harder to justify in CRe's codebase ;).

**Comment by poire-z** [comment]
Can't it be just solved with doing this?:
```diff
 strftime(str, sizeof(str), "%I:%M %p", bt);
+if (*str == '0') str++
```

**Comment by NiLuJe** [comment]
I was under the impression this was a setting in KOReader, but I'm admittedly unfamiliar with this side of the clock ;).

But, yeah, we can certainly do the processing ourselves ^^.
