### ISSUE TITLE
Koreader News Downloader doesn't seem to support rdf(rss 1.0) feeds

### ISSUE THREAD

**Issue by aaronindhouse** [koreader/koreader#8799]
* KOReader version:
* Device: onyx boox

#### Issue
Here is an example of a feed im trying to add, 
https://www.asahi.com/rss/asahi/newsheadlines.rdf

News downloader doesn't support it
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by roygbyte** [comment]
Newsdownloader isn't intended to support RDF, which would be why it isn't working for you. If there a strong use-case for RDF support I can "look into it"...

**Comment by aaronindhouse** [comment]
Thanks for your response. It looks like it's an older implementation of RSS(I'm not familiar with RSS but when I looked it up I think it said it used RSS 1.0?). It is used by a lot of Japanese Newspapers instead of the newer version of RSS. Lots of Japanese websites still use older technology for some reason. They move fast on some innovations and slow on others. Supporting it probably wouldn't be helpful to western users too much, but I think it would be useful to support for any Japanese users you have. If you want me to link to some other RDF feeds let me know and I'll compile a list and post it for you.

**Comment by roygbyte** [comment]
Some people around these parts probably look at RSS and think it is dated technology... 

Anyways, a key piece of NewsDownloaders ability to parse feeds is this line:

https://github.com/koreader/koreader/blob/4ccdbc90a573579d626af47908440d3914960427/plugins/newsdownloader.koplugin/feed_source.lua#L94

If RSF can similarly be parsed then it shouldn't be much trouble to handle the feeds. Further down from that line are the RSS and Atom handler thingys. You'd have to write one for RSF... Shouldn't be much more to it than that.

**Comment by Frenzie** [comment]
Around these parts? Like, greater GitHub? ;-)

**Comment by roygbyte** [comment]
Oh, like within my own head 😛

**Comment by aaronindhouse** [comment]
> If you can send an English RSF my way I'll tinker with it...

Here is the an RDF in English. Site doesn't list it as .rdf so i'm not sure if that makes a difference, but they are the same filetype as the one I originally linked to.

English:
https://rss.dw.com/rdf/rss-en-all
Japanese:
https://www.asahi.com/rss/asahi/newsheadlines.rdf

**Comment by aaronindhouse** [comment]
Thank you for adding .rdf support! Yall are amazing!

**Comment by roygbyte** [comment]
Pinging this thread to see if folks want to contribute ideas towards Newsdownloader's rebuild. [See this thread for more info.](https://github.com/koreader/koreader/issues/9225)
