### ISSUE TITLE
Poor battery performance on Sage

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8804]
* KOReader version: koreader 2022 10.2.22
* Device: Kobo Sage

#### Issue
Verry verrrrrrrry poor battery performance (all plugins disabled) 
Koreader uses 132mA
KoboReader (nickel ) Uses 21mA
(In my values there is an offset of at least 9mA for the charging circuit.)
Similar observations are shown in https://www.e-reader-forum.de/t/kobo-sage.157785/post-2436397
(In German )

This issue shortens the usability time of one charge by the factor of 10!!!! That is inferior and not acceptable. Koreader does not deserve that.

#### Steps to reproduce
use an usb amperemeter to check current.
1. kobo software
2. Koreader.

@NiLuJe The frequency is at 480000Hz:. So this should be OK. Might there be another additional power saving mechanism on sunxi.

**Comment by NiLuJe** [comment]
[Known issue](https://www.mobileread.com/forums/showpost.php?p=4174143&postcount=661).

(Soon is in Valve time, because I have almost zero free time, and this requires extensive annoying testing, which I don't have right now, and am unlikely to have either in the coming months).

**Comment by NiLuJe** [comment]
I'm going to need more details (and, err, English, because my seven years of German are all but useless now), because it's my understanding that the device shouldn't be able to autostandby while charging :?

**Comment by NiLuJe** [comment]
To be clear: this has nothing to do with CPU frequency/voltage scaling (which we/nickel have only minimal control of, anyway).

This has *everything* to do with sunxi being terrible at power efficiency (something we knew already, given the experience on PocketBooks).

So, where does the delta come from? Nickel just happens to aggressively enter suspend-with-the-lights-on after ~6s of input inactivity when unplugged & unconnected. We don't, and I never really bothered to try to replicate that behavior because it's -- for a large part -- responsible for the terrible latency experienced when turning pages in Nickel (because resume takes time).

**Comment by NiLuJe** [comment]
Yeah, input doesn't go to sleep without the `state-extended` write, that's similar on very NTX board ;).

**Comment by zwim** [comment]
@poire-z Thanks I will test it the next days.

@NiLuJe : My "current measurement" (on the Sage) works this way:
Charge the device to 100%. Then connect the device through something like this cheap https://www.amazon.de/Innovateking-EU-Spannungspr%C3%BCfer-Strompr%C3%BCfer-Multifunktionsanzeige-Stromdetektor/dp/B07Q292MMK/ref=sr_1_16?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=3NO62KWWPAJHT&keywords=usb+strom+messen&qid=1644878996&sprefix=usb+strom+messen%2Caps%2C99&sr=8-16

Measure the current with KOReader or/and Nickel running. Any yes: You are right, the current in Nickel drops after a few seconds.
And no: When viewing an epub in Nickel, turning pages is not really slow (maybe a bit slower than in KOReader).

**Comment by Frenzie** [comment]
Really slow is in the eye of the beholder of course. A second or even half a second is really slow compared to 10-50 ms but perhaps not really slow enough to be actively bothersome. (I don't have a Sage, hence why I'm talking in the abstract. :-) )

**Comment by NiLuJe** [comment]
Indeed ;). It's also likely to have become somewhat bearable on the Sage because of the beefier CPU, but it's nigh unusable to my tastes on earlier devices ;).

**Comment by zwim** [comment]
I have to specify "not really slow" means, that I would only notice that Nickel is slower if I know that it has to be slower ;)

Good news (with a full battery, frontlight 40% and my USB-thingy):
1.) Put the Sage in standby (over ssh) with `sleep 10; echo standby > /sys/power/state`. 
2.) Turned off WiFi
3.) Measure the Amp (ca. 150mA)
4.) After the 10 secs the Amps drop to 40mA.

5.) An unrelated suspend would go to 9mA (after 20seconds).

These values are roughly the same in Nickel. So I think this might be a good strategy for power saving.

A few findings/thoughts (which might not be new to the others here):
Standby does not work well with WiFi on.
Suspend does not start, when standby is activated.
Standby should be ended before the next scheduled function is expected to be executed.

**Comment by Frenzie** [comment]
> Standby does not work well with WiFi on.

Yeah, I was wondering about that. It seems really annoying for wifi to be disabled after 10 seconds.

**Comment by NiLuJe** [comment]
Yeah, it probably even crash the kerne of some devices ;o).

(IIRC, that's probably implemented in my branch. Don't remember :D).

**Comment by NiLuJe** [comment]
Okay, fun little device acquired ;o.

At a very quick glance, I'm seeing similar numbers that the poster on a Forma.
Haven't touched the Sage yet, but another recent multicore device that shall remain nameless exhibits hilariously better power efficiency... (significantly better than my Forma, even).

**Comment by NiLuJe** [comment]
Apparently, "gigantic battery" it is ;p. Mystery device draws less power while alive, lit up and idling than a Sage or Elipsa in full suspend -_-". And has much lower spikes when not idling. Oh, well.

**Comment by zwim** [comment]
One thought to your "mystery device". Could it just be, that there is a clever charge logic, which does some kind of hysteresis?
Which means, that the battery is not always charged (so the usb-thing does not measure current). And charging is only started if the battery charge goes under a certain level? 

I have implemented it that way in my electric scooter (which should prolong the battery live substantially).

If there is a possibility to stop charging on our devices by software, we should implement a charge hysteresis too. I haven't looked at this yet.

**Comment by NiLuJe** [comment]
It was flagged as charging, but that's an interesting query, I'll poke at
the sysfs stuff ;).

**Comment by zwim** [comment]
Note to self: On Sage you can dis/enable charging with `/sys/devices/virtual/misc/cilix/glf72120_enable`
