### ISSUE TITLE
Pocketbook: Night mode doesn't work

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8808]
* KOReader version: v2022.01-98 (with patch [#1454](https://github.com/koreader/koreader-base/pull/1454/files))
* Device: PB 628

#### Issue
Night mode doesn't work after applying the changes of the file "koreader-pocketbook-inkview-rendering" (see #8727)

I open this issue as a reminder, following up the comments https://github.com/koreader/koreader/issues/8187#issuecomment-1024828576 and https://github.com/koreader/koreader/issues/8187#issuecomment-1024869094. I don't know if the solution of the comment https://github.com/koreader/koreader/issues/8187#issuecomment-1024886363 is considered final.

**Comment by NiLuJe** [comment]
Should be fixed by the canHWInvert cap flag swapped to no, which I assume will land with the base bump if it hasn't already ;).

**Comment by ichnilatis-gr** [comment]
Well, this solution seems to work. It would be more convenient if this flag was changed to "no" in the next version, so we don't have to change it manually. Unless some other solution is considered better.

**Comment by NiLuJe** [comment]
That's #8803 ;).

**Comment by rjd22** [comment]
This one will be fixed next release.

**Comment by Frenzie** [comment]
Fixed by #8803
