### ISSUE TITLE
Problem with displaying transliterated Arabic and Persian words

### ISSUE THREAD

**Issue by serdar0020** [koreader/koreader#881]
I've already mentioned this before in the koreader thread, but koreader yet isn't able to handle the transliterating of hamzah and ʻayn -modifier letter apostrophe " ' " , but always creates a line-break before and after the " ' ", embedded style on or off makes no difference. Using new 6" Kobo aura, FW 3.8.0, built 2014.04-675

screenshot https://cdn.anonfiles.com/1410066330429.jpg

**Comment by serdar0020** [comment]
I just read another book with Turkish characters inserted as image "ğ, ş, İ" (Midnight at the Pera Palace) and had the same paragraph breaks again. I replaced the character images with unicode letters in sigil and it looks fine now, but I didn't go through the whole book. Sigil and Firefox epub have no problem inserting the images into the text flow. Any news in koreader? (using build 2014.11.154 - had too many crashes with 222)

**Comment by poire-z** [comment]
Closing, as images are now `display: inline` since https://github.com/koreader/crengine/pull/194, which should solve this issue.
