### ISSUE TITLE
koreader crashes when attempting to export highlights

### ISSUE THREAD

**Issue by rkosov** [koreader/koreader#8817]
* KOReader version: 2022.01
* Device: Pinenote

#### Issue
Koreader will crash when Export highlights -> Export All Highlighter

I cannot export the error log because it attempts to connect to bluetooth for some reason. However the relevant line appears to be 

E/NativeThread (1842) Failed to run script: plugins/exporter.koplugin/clip.lua:319 cannot open ./history: No such file or directory.

I also see some warnings of the nature unused DT entry: DT_RPATH (type 0xf arg 0x1ac0) ignoring

I checked and there are metadata.epub.lua with the annotation in there.

**Comment by pazos** [comment]
Fixed in https://github.com/koreader/koreader/pull/8944
