### ISSUE TITLE
Pocketbook: Landscape is broken with the inkview renderer

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#8825]
* KOReader version: v2022.01
* Device: PB970

#### Issue
Using the new inkview renderer, when changing the orientation to landscape, the image updates properly, but then whenever you tap on something, only the right side updates. It's unusable. Also a minor thing, but the page turn buttons should be inverted when in landscape.

#### Steps to reproduce
Use the new renderer from #8727 
Change the orientation to landscape

![IMG_20220219_224055__01](https://user-images.githubusercontent.com/60707126/154820481-1dfd33ab-c036-462f-9692-5e245bdfde50.jpg)
![IMG_20220219_224203](https://user-images.githubusercontent.com/60707126/154820480-a7eb02f9-e692-4d18-8cda-46862795fa5a.jpg)
![IMG_20220219_224252__01](https://user-images.githubusercontent.com/60707126/154820469-3dbb97f2-24f7-4edf-bc7d-7f1bd26683e8.jpg)
![IMG_20220219_224413__01](https://user-images.githubusercontent.com/60707126/154820473-3a49457f-c7c0-417b-a0a8-9dc178cc5f0c.jpg)
![IMG_20220219_224212](https://user-images.githubusercontent.com/60707126/154820474-9e437061-93e2-4f43-b64d-5c9b716c0bc2.jpg)

**Comment by NiLuJe** [comment]
Should be fixed by #8803, which also includes a base bump with the fix for this.
