### ISSUE TITLE
FR: Tachiyomi integration - manga reader / downloader

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#8826]
**Does your feature request involve difficulty completing a task? Please describe.**
Manga chapters are being updated weekly and uploaded on translations sites such as mangadex, but on an e-ink device, the browser is just not convenient. That's why there's Tachiyomi, a manga reader that downloads chapters from such sites (and more via extensions), but it's only for Android devices. 

**Describe the solution you'd like**
My idea is to make a Tachiyomi widget where you can download new chapters from followed series, something like RSS. It could check for new chapters daily and automatically download and delete them after they're read. There are also more features that could be integrated, like the full library manager, downloader, browser and settings. 

**Describe alternatives you've considered**
You can of course make your own manga updater instead of borrowing Tachiyomi's code. It may take more time, but there are already manga downloading scripts on github that you can take a look at and work something out if you wanted to.

**Additional context**
I imagine it would require understanding of Tachiyomi's source code (https://github.com/tachiyomiorg/tachiyomi) and its widgets, but are already rewrites of Tachiyomi to work on a desktop (https://github.com/Suwayomi/Tachidesk-Server), which could be used as a starting point.

**Comment by NiLuJe** [comment]
Not a compatible language (Java).
