### ISSUE TITLE
Koreader on macOS doesn't support macOS Catalina

### ISSUE THREAD

**Issue by imkaihao** [koreader/koreader#8828]
I'm using macOS Catalina. But the application requires macOS 11.0 or later.
<img width="488" alt="Screenshot" src="https://user-images.githubusercontent.com/35647230/154832605-b44f7988-2a12-4d0a-9b57-abe67b94d4fe.png">

**Comment by NiLuJe** [comment]
Because Xcode ;).

You'll have to (try to) the build one that matches your macOS version. And hope it doesn't randomly implode during build because xcode :).

**Comment by pazos** [comment]
Building the application in "El Capitan" (10.11) will return an app compatible with 10.09.

Also the minimum required version is derived from the build machine if not found: https://github.com/koreader/koreader/blob/master/platform/mac/do_mac_bundle.sh#L35-L42

Just 2cts in case somebody is willing to add a GH action to build monthly releases: use the oldest mac version available!

**Comment by NiLuJe** [comment]
There were issues with using an older MACOS_DEPLOYMENT_TARGET (or whatever the actual variable name is ;p), though, which is why we're *not* using the oldest version available ;).

**Comment by pazos** [comment]
Yup. IIRC correctly building on catalina requires `10.14`. I think current build instructions were made when catalina was current os version.

But that doesn't hold true if the build machine is mojave or lower. The problem with that is `brew`, which only maintains binaries for last 2-3? os versions
