### ISSUE TITLE
Can't send book wirelessly to device using Calibre.

### ISSUE THREAD

**Issue by DarkRookie00** [koreader/koreader#8839]
* KOReader version: 2022.07
* Device: Kobo Sage, KOReader (Kobo_cadmus)

#### Steps to reproduce
1. Installed latest version of Calibre available. (5.37)
2. Start the wwireless device connection.
3. Open KOReader on my Sage
4. Successfully connect to home wifi
5. Successfully connects to Calibre. Calibre acts like a device is connected.
6. Attempt to send book to main memory, fails. Get error, 
```
calibre, version 5.37.0
ERROR: No space on device: <p>Cannot upload books to device there is no more free space available in main memory.</p>
<ul><li>Book</li></ul>
```
```
There is insufficient free space in main memory

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/device.py", line 87, in run
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib64/calibre/calibre/gui2/device.py", line 592, in _upload_books
    return self.device.upload_books(files, names, on_card,
  File "/usr/lib64/calibre/calibre/devices/smart_device_app/driver.py", line 58, in _synchronizer
    return func(self, *args, **kwargs)
  File "/usr/lib64/calibre/calibre/devices/smart_device_app/driver.py", line 1489, in upload_books
    sanity_check(on_card='', files=files, card_prefixes=[],
  File "/usr/lib64/calibre/calibre/devices/utils.py", line 34, in sanity_check
    raise FreeSpaceError(_("There is insufficient free space in main memory"))
calibre.devices.errors.FreeSpaceError: There is insufficient free space in main memory
```
7. The Home Directory is set to /mnt/onboard.
8. Switch it to /mnt/user. same issue.
9. IIn Configure Wireless device: KOReader (Kobo_cadmus), I check the box, Ignore device free space. Get a different similar error.
```
calibre, version 5.37.0
ERROR: Failed: Sending book Book.epub to device failed

Can't receive file 1/1: ⁦⁦/⁨mnt⁩/⁨user⁩/⁩Book.epub⁩
No space left on device
```
```
Sending book Book.epub to device failed

Traceback (most recent call last):
  File "/usr/lib64/calibre/calibre/gui2/device.py", line 87, in run
    self.result = self.func(*self.args, **self.kwargs)
  File "/usr/lib64/calibre/calibre/gui2/device.py", line 592, in _upload_books
    return self.device.upload_books(files, names, on_card,
  File "/usr/lib64/calibre/calibre/devices/smart_device_app/driver.py", line 58, in _synchronizer
    return func(self, *args, **kwargs)
  File "/usr/lib64/calibre/calibre/devices/smart_device_app/driver.py", line 1502, in upload_books
    length, lpath = self._put_file(infile, lpath, book, i, len(files))
  File "/usr/lib64/calibre/calibre/devices/smart_device_app/driver.py", line 722, in _put_file
    raise UserFeedback(msg='Sending book %s to device failed' % lpath,
calibre.devices.errors.UserFeedback: Sending book Book.epub to device failed
```
10. There is more than enough free space avaialbe. I can plug in an USB cable and upload books that way with no issue. Ddoesn't matter the book type/format. Doesn't matter the size. Happens with 2MB EPUBs and 200MB PDFs.

Original post I had on the MobileRead forums about this.
https://www.mobileread.com/forums/showthread.php?t=345051

**Comment by DarkRookie00** [comment]
OK. after poking around in the various tools, this started working.
I enable Reading statistics, I can send books, but it doesn't recognize anything already on the device.
I disable it, I get the above errors again.

**Comment by pazos** [comment]
xref: https://www.mobileread.com/forums/showthread.php?t=345051

> OK. after poking around in the various tools, this started working.
I enable Reading statistics, I can send books, but it doesn't recognize anything already on the device.
I disable it, I get the above errors again.

That doesn't make any sense.

> The Home Directory is set to /mnt/onboard.

The home directory is something related to the filemanager and has nothing to do with the **inbox dir** for calibre wireless transfers.

@DarkRookie00: please follow given instructions and setup your inbox dir to a path under /mnt/onboard.

**Comment by pazos** [comment]
xref: https://www.mobileread.com/forums/showthread.php?t=345051

> OK. after poking around in the various tools, this started working.
I enable Reading statistics, I can send books, but it doesn't recognize anything already on the device.
I disable it, I get the above errors again.

That doesn't make any sense.

> The Home Directory is set to /mnt/onboard.

The home directory is something related to the filemanager and has nothing to do with the **inbox dir** for calibre wireless transfers.

@DarkRookie00: please follow given instructions and setup your inbox dir to a path under /mnt/onboard.
