### ISSUE TITLE
Landscape mode crops when waking up

### ISSUE THREAD

**Issue by Biep** [koreader/koreader#8842]
Device: Kobo Aura One
Version: v2022.01

I have set wake-up such that a tap is needed to remove the sleep mode screen.
When I read a PDF in landscape mode (right side of page where on the back is the blue button), close the cover, open it again, and tap the sleep mode screen, only a square of the page is shown - the right (near the button) still shows a strip of the sleep mode screen.
Opening a menu doesn't help, closing it again does.  Likewise, turning a page solves the issue.

I also had a crash, so I include a bit of log, in the hope that it may be useful for both issues.
[Crash.txt](https://github.com/koreader/koreader/files/8140192/Crash.txt)

**Comment by NiLuJe** [comment]
The crash is a segfault, FWIW, so, logs are no use, we'd need a backtrace from a debug build (which means we'd need a repro to make debugging that slightly less nightmarish).

**Comment by Biep** [comment]
If you want me to run a special version with extra debugging info, just provide it and I'll install it.

(Which reminds me - I can no longer run the automatic update - the one via the menu.  It finds an update, I tell it to install, it does the delta, then starts to download the missing parts, and then gives an error, leaving the screen in a dirty state (the download process text on top of the page I was reading.  Is that a known thing?  I add the relevant bit of log text.
[Crash.txt](https://github.com/koreader/koreader/files/8342130/Crash.txt))

**Comment by Frenzie** [comment]
> Is that a known thing? 

Definitely not. Unless possibly if you mean on a version from 2 years ago?

**Comment by Biep** [comment]
No v2022.01
But it played already when trying to install *that* - when I had the custom version that @NiLuJe had created for me.
So instead I just renamed the /.adds/koreader folder, installed a downloaded version manually, and then copied a few files/folders - I believe they were the following:
- koreader/settings/statistics/sqlite3
- history
- defaults.persistent.lua

**Comment by Frenzie** [comment]
That wouldn't affect anything. But you didn't say what the error was. There are of course some perfectly expected errors (in a manner of speaking), like an interrupted wireless connection if you're on the edge of your wifi network.

**Comment by Biep** [comment]
First it says *Cannot find /mnt/onboard/.adds/koreader/./ota/koreader.updated.tar, triggering delta download, using as seed file*

But I now run it at my brother's place (whereas before I did it over a supermarket WiFi), and it seems to work.
Previously, the second row of ### would not get to 100%, with a message that the download failed.  Now I have run *huge* downloads over that supermarket WiFi, so that is not the issue - and I have a very good connection too (which is why I go there in the first place, to save on my data bundle).  I'l try again next time I am there.

**Comment by NiLuJe** [comment]
I've seen that happen when running custom builds, FWIW.

**Comment by Biep** [comment]
...and now it also worked over a public WiFi.
Even with a manually installed stable version that didn't work before.
