### ISSUE TITLE
Crash after trying open terminal session

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8844]
* KOReader version: v2022.01-98
* Device: PB 628

#### Issue
KOreader crashes after tapping on "Open terminal session (not running)".

Discussed in https://github.com/koreader/koreader/discussions/8819

##### `crash.log` (if applicable)

[crash 25-2-2022.log.txt](https://github.com/koreader/koreader/files/8142331/crash.25-2-2022.log.txt)

**Comment by zwim** [comment]
On the first view I don't find anything in your crash.log. I just see that you were doing a `adjusted ges: pan southwest` and then a `adjusted ges: multiswipe southwest northeast` and then the reader gets closed (at 17:20:06).

For me this is not a crash but rather an unexpected termination/quit/exit of KOReader. Could you check your gestures, esp. those two mentioned above? Maybe the later on is set to something like exit/poweroff/restart ...

**Comment by hombretranquilo** [comment]
Also fails on my device. Perhaps my crash.log 
[terminal crash.log](https://github.com/koreader/koreader/files/8146590/terminal.crash.log)
provide more data. The relevant part seems to be this:

02/26/22-13:17:00 DEBUG Terminal: resolution= 60x19
02/26/22/22-13:17:00 ERROR Terminal: can not grantpt
02/26/22/22-13:17:00 ERROR Terminal: can not unockpt
Segmentation fault

**Comment by Frenzie** [comment]
Curious, I thought only Android was missing those.

**Comment by zwim** [comment]
If grantpt and unlockpt are missing on pockerbook, we have a problem with the emulator there. 

Anyway `terminal` should not crash, I will fix at least that.

**Comment by rtiangha** [comment]
I also get this on my Kobo Glo HD. The thing is, it worked once (the first time). After that, it always crashes with the grantpt/unlockpt error. I had to resort to backing up and renaming the old plugin just so I could continue to locally input shell commands.

**Comment by NiLuJe** [comment]
We're not root on PB, which might be an issue here ;).

**Comment by zwim** [comment]
The emulator is also non root. No problems there.

**Comment by rtiangha** [comment]
> @rtiangha : Could you please post a crash log for the new terminal on your Kobo Glo HD and your Firmware version.
> 
> Maybe you can also post your `settings.reader.lua`.

Attached. My firmware version is 4.31.19086. The crash is on line 9846, but I noticed version 2022-02 is now out so I updated to that and the plugin seems to be working now so I'll keep an eye on that.

[crash.log.txt](https://github.com/koreader/koreader/files/8149523/crash.log.txt)
[settings.reader.lua.txt](https://github.com/koreader/koreader/files/8149524/settings.reader.lua.txt)
.

**Comment by poire-z** [comment]
@zwim: has this been fixed - and the issue can be closed?

**Comment by zwim** [comment]
Yes it can be closed.
