### ISSUE TITLE
FR: [Next release should be Ukraine themed]

### ISSUE THREAD

**Issue by FajnB** [koreader/koreader#8846]
I thing, that given the current geopolitical circumstances (Russian - Ukrainian war), the next release theme should be Ukraine.

Like some good name describing them and implement color scheme or flag in the logo.

**Comment by poire-z** [comment]
My thoughts and tears are with you @hius07 :( I hope you are ok.

**Comment by Frenzie** [comment]
Yes, indeed @hius07  :-/

PS Next release would be a bit difficult, unless @bubapet would like to grace us with a quick illustration instead of the one we'd prepared.

**Comment by hius07** [comment]
Thank you dear friends. The hardest time ever. 🇺🇦

**Comment by bubapet** [comment]
@hius07 there isn't much to say that could help, only know that there are people all around the word that are aware of what is happening and I hope you won't feel alone in this.

@Frenzie I can make an illustration on Tuesday soonest, when I am reunited with my drawing station. I hope that is not too late for what you have planned.

**Comment by Frenzie** [comment]
I'll think about it for a few more hours. We could skip a .02 and go straight for .03.

**Comment by Frenzie** [comment]
@hius07 Any thoughts on Vladimir or Yaroslav (or other suggestions)?

![Coin_of_Vladimir_the_Great](https://user-images.githubusercontent.com/202757/155877671-96e0587d-6827-4229-845f-ddb178c4e8c2.jpg)

![Yaroslav_I_of_Russia_(Granovitaya_palata,_1881-2)](https://user-images.githubusercontent.com/202757/155877642-dfb55690-8fd3-4fa1-a281-decb018e7207.jpg)

**Comment by Frenzie** [comment]
@poire-z The colors and the flag speak for itself. What I mean is rather a little extra, like this for example:

![koreader pdf](https://user-images.githubusercontent.com/202757/47815450-adee5500-dd50-11e8-89b5-60decfa81b06.png)

But we could also do something like this:

![koreader](https://user-images.githubusercontent.com/202757/155879716-eef422f2-7a54-4e94-ab35-bbebaa3766f1.png)

![koreader](https://user-images.githubusercontent.com/202757/155879896-f14fb254-25bb-4463-9443-43ddc7c80bb3.png)

**Comment by Frenzie** [comment]
@poire-z 
> (Really asking an ukrainian Any thoughts on Vladimir ? :)

PS I kind of forgot. Everyone calls him Putty.

**Comment by poire-z** [comment]
3rd picture above is strong and nice.

**Comment by mergen3107** [comment]
@hius07 
Stay strong 💪🏻 we are with you ❤️

**Comment by mergen3107** [comment]
Guys I don’t know whether this is the place for this, but can I please share two links for crowd-funding support initiatives in this thread? 

I have recently graduated from a university in Florida and my dear Ukrainian friends from over there asked me to spread these links as much as possible

**Comment by mergen3107** [comment]
Thank you guys! Here are the two crowd funding links: 

Students fundraiser for humanitarian support:
https://www.facebook.com/donate/498356795272938/?fundraiser_source=external_url 

Fundraising for Ukrainian army:
https://savelife.in.ua/en/donate/?fbclid=IwAR34qKRpzW7d3rVmpVpCCpTW7JJ4S_zh6G6yRMt--wzvPgz-dnUIBakkP1w
