### ISSUE TITLE
FR: Support for Pocketbook with 740-3 codename

### ISSUE THREAD

**Issue by uatel** [koreader/koreader#8850]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently support for Pocketbook device with PB740-3 codename is absent from "/application/koreader/device/pocketbook/device.lua" file.

**Describe the solution you'd like**
Please add section for mentioned codename that are copied from 740-2 codename:

-- PocketBook InkPad 3 Pro (740_3)
local PocketBook740_3 = PocketBook:new{
    model = "PBInkPad3Pro",
    display_dpi = 300,
    isAlwaysPortrait = yes,
    usingForcedRotation = landscape_ccw,
    hasNaturalLight = yes,
    raw_input = {
        touch_rotation = -1,
        keymap = {
            [115] = "Menu",
            [109] = "LPgFwd",
            [104] = "LPgBack",
        }
    }
}

and relevant section for codename description:

elseif codename == "PB740-3" then
    return PocketBook740_3

**Describe alternatives you've considered**
As alternative add section for 740-3 codename that linked to 740-2:

elseif codename == "PB740-3" then
    return PocketBook740_2

**Additional context**

**Comment by Frenzie** [comment]
If they are identical in all those properties then there's no reason to duplicate the definition. Everything works as expected with that addition?

**Comment by uatel** [comment]
All wark correctly when description for 740-3 codename is added.
