### ISSUE TITLE
Multiple regressions in news downloader

### ISSUE THREAD

**Issue by Thra11** [koreader/koreader#8867]
Version: v2022.02
Device: Kobo Aura One
 
In v2022.02, there are many regressions which—for me at least—have transformed the news downloader plugin from perfectly functional to essentially unusable.

1. Filenames no longer include dates, so the files are muddled up in the directories.
2. Previously, it would skip articles if the destination file already existed, now it appears to re-download every single item, which wastes an enormous amount of time and bandwidth (As an example, I have 6 feeds in my config, with ~10-25 articles per feed, some more image-heavy than others. I timed it running sync for a 2nd time: It took 7 minutes despite there being no new articles. Previously, it would have finished in ~10 seconds or ~30 seconds if it found a couple of new articles to download.
3. Cannot be interrupted (I think this is a pre-existing issue, but 2. makes it painful). You can abort an individual download, but it'll just start on the next one.
4. Lots of errors notifications, one after another, so very tedious to dismiss. No actual information on what went wrong: e.g. "Error building EPUB KOReader 2022.02 "Україна"" (from the KOReader releases atom feed)
5. New option, "Volumize feed" is on by default even for pre-existing feeds: unexpected change in behaviour for existing users

I don't know how closely the breaking changes are tied to / required by the new "Volumize feed" option. Personally, I don't want to use the "Volumize feed" option: I don't mind it existing for others, as long as it doesn't break things for users who aren't using it. However, I like to:
* Have one epub file per article. This makes it easy to track which articles I've read (even if I don't read them in publication order)
* Have the date stamp in the filename for easy sorting (Sorting by "date added" is liable to break if e.g. you back up and restore your files or transfer them to a new device (also I tried sorting by "Date Added" and it seemed to have some bugs: a file moved to a different position when I opened it).

**Comment by Thra11** [comment]
I assume #8263 is the relevant PR. Based on https://github.com/koreader/koreader/pull/8263#issuecomment-1006057694 I guess the breakage was accidental: it's not supposed to behave differently if you don't use volumization?

**Comment by Thra11** [comment]
Here's my feed_config.lua, in case you need a specific combination of feeds or options to reproduce some of the issues.
[feed_config.lua](https://github.com/koreader/koreader/files/8179574/feed_config.lua.txt)

**Comment by roygbyte** [comment]
Well this is largely my doing. Sorry about that. To implement the feed volumize feature I had to rewrite some other stuff and, well, obviously that didn't go well. Not sure honestly how these regressions passed my testing... But I did the work when I was fairly fresh to Lua, so there's that. 

Anyways... I think NewsDownloader should be reverted to that last version. The plugin is such a slapdash of work that I am half of the mind to just rewrite it and write unit tests along the way so this doesn't happen...

**Comment by roygbyte** [comment]
Heh, thanks for sharing in in the pity party :') I'm not sure what to do moving forward. The main grievance you've raised (i.e.: feeds downloading multiple times) is coming from this block of code, which is supposed to store hashes of the feed URLs as a setting. I don't fully understand how `LuaSetting` works so... it's not working. I probably just need to faff around a bit more and I should get it...

https://github.com/koreader/koreader/blob/36fc981b7cf5b168b064df151409109097fca5fa/plugins/newsdownloader.koplugin/main.lua#L377-L405

As for the other issues, well, those could be ironed out too, I think. But like I said I'm half of the mind to just scrap the changes brought about by this PR and revert to the previous version. 

@Thra11 You worked on it previously... what do you think?

**Comment by NiLuJe** [comment]
`history_for_feed` ifs never flushed, and I'm not sure if flushing a parent automagically flushes every children...

**Comment by roygbyte** [comment]
Pinging this thread to see if folks want to contribute ideas towards Newsdownloader's rebuild. [See this thread for more info.](https://github.com/koreader/koreader/issues/9225)
