### ISSUE TITLE
Wikipedia search not working on Pocketbook Touch HD 3

### ISSUE THREAD

**Issue by DrCat75** [koreader/koreader#8871]
* KOReader version: v2022.02
* Device: Pocketbook Touch HD 3

#### Issue
Hey
If I tap on the 'Wikipedia' button on the smart lookup, it asks me to allow Wifi (which I do), it loads, but then just nothing happens, no search is done or anything. I don't really know how to fix this. Did I forget to configure something or is it really a bug?

Thanks for your help!

#### Steps to reproduce

Tap on the 'Wikipedia' button on the smart lookup

**Comment by DrCat75** [comment]
Just tested v2022.01. The problem persists.

**Comment by lorenzlm** [comment]
Have the same issue with a Pocketbook Inkpad 4. Have there been any progress or helpful hints?

**Comment by pazos** [comment]
Fixed by #11601
