### ISSUE TITLE
KOReader nightly not reachable

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#8874]
On 5. Mar. 2022 at 23:00 `https://build.koreader.rocks/download/nightly/` is not reachable 
```
 Error 521 Ray ID: 6e761e160cf0780d • 2022-03-05 21:59:13 UTC
Web server is down
```

**Comment by Frenzie** [comment]
Cross-ref https://www.mobileread.com/forums/showthread.php?t=345532 and https://www.mobileread.com/forums/showthread.php?t=345532

Someone (or more likely something) seems to have restarted the server, and we never made it so that the relevant parts start automatically.
