### ISSUE TITLE
FR: Bengali Keyboard Layout

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#8883]
I would like to have a Bengali keyboard layout so that we can use that to write Bengali.

It seems like an easy enough task using the existing layout system.

I'll be happy to contribute to this.

**Comment by Frenzie** [comment]
The easiest way to contribute would be to modify the one that most closely matches the desired result.
https://github.com/koreader/koreader/tree/a83a129c401d1af9693c49e3d122959429edc016/frontend/ui/data/keyboardlayouts

**Comment by uroybd** [comment]
I have a question, For every row, do I have to 4 set of inputs? In Bengali, we need only 2.

**Comment by Frenzie** [comment]
You likely do want four, keeping the third and fourth (symbol layer) as is.

<img src=https://user-images.githubusercontent.com/202757/157608439-86c133ee-cb70-4dc8-8e25-5d791848f864.png width=45%> <img src=https://user-images.githubusercontent.com/202757/157608440-d12f3ab5-6f1b-4080-9cc9-b6a5ad73797c.png width=45%> 
<img src=https://user-images.githubusercontent.com/202757/157608443-2ffd1b4e-dea8-4537-b9b0-e4bd50e7c071.png width=45%> <img src=https://user-images.githubusercontent.com/202757/157608442-912e086c-72ef-40c1-bb6d-0c7a08b67580.png width=45%>

**Comment by uroybd** [comment]
What if I need more keys in the 3rd row?

Here's the layout I'm implementing:
![Screenshot from 2022-03-10 15-04-36](https://user-images.githubusercontent.com/4207230/157628437-98a2f0b4-fd59-448c-a864-dfc91faddd96.png)

**Comment by uroybd** [comment]
Since the PR related to this has been merged. I'm closing this issue.
