### ISSUE TITLE
Kobo Mini: unable to connect to Wi-Fi. Wi-Fi is enabled, but not connected to any network

### ISSUE THREAD

**Issue by marcingold22** [koreader/koreader#8886]
* KOReader version: v2022.02 
* Device: Kobo Mini (with Kobo Glo firmware)

#### Issue

The device doesn't connect to the network. When trying to connect to Calibre, a prompt appears asking if I want to turn on Wi-Fi (which is already turned on on Nickel). 

When selecting the option to turn on, KOReaders scans for networks and finds the network connected to Nickel and then shows the message "Connected to *SSID*". Then it asks again if I want to turn on Wi-Fi and the loop begins.

When trying to turn off Wi-Fi in the Network settings of KOReader, a prompt suggests that the Wi-Fi is already enabled but I'm not connected to any network.

The same happens when trying to connect to any online service.

#### Steps to reproduce

Connect to a network on Nickel in the menu (optional).

Open the plugin menu, open the Calibre plugin settings and try to connect to Calibre.

**Comment by NiLuJe** [comment]
Does that network have internet access or is it local connectivity only?

**Comment by NiLuJe** [comment]
Debug logs would be helpful, too :).

**Comment by marcingold22** [comment]
> Does that network have internet access or is it local connectivity only?

It does have internet connectivity 



> Debug logs would be helpful, too :).

Sure. How do I get these? 🤔

**Comment by NiLuJe** [comment]
In the FM : Tools > More tools > Developer options

Restart koreader, try Wi-Fi stuff, then post the crash.log file found in the koreader folder ;).

**Comment by NiLuJe** [comment]
The resume script doesn't log much, so I wouldn't mind you trying with an actual explicit connection; as well as a look at the kernel + system logs (run `klogd` before launching koreader; do stuff, then run `logread`).

**Comment by marcingold22** [comment]
Hi, sorry if I reply just now! How do I do this? Do I need to open a terminal in KOReader?

**Comment by NiLuJe** [comment]
I'd find a real SSH shell less unwieldy, but whatever floats your boat, really ;).

**Comment by NiLuJe** [comment]
See also my comments in https://github.com/koreader/koreader/issues/8895 & https://github.com/koreader/koreader/issues/8896 for more debugging instructions ;).

**Comment by marcingold22** [comment]
Seen, thanks! I tried getting a ssh connection but I have one problem... Since the network doesn't work, I'm unable to create a connection... So, I'm unable to get the log... I'll try to shut the device off and see if the logs are still there...

**Comment by marcingold22** [comment]
Here I am again. Here's the log:

https://bin.snopyta.org/?b6571e55c6747a07#4GzhEaFqKNCCCD5pqsut6DX3wDU6fNTK8xgkWy4U6YAs

**Comment by NiLuJe** [comment]
That seems to have expired ;).

**Comment by marcingold22** [comment]
Sorry messed up with some tests 

Here's the updated link: https://bin.snopyta.org/?1654ce8accfc794a#6Db8T1b8arGHL9ebS75vdXNZjuMrdddSz7DF8tiMWpPU

**Comment by marcingold22** [comment]
Updated link when the one above expires: https://bin.snopyta.org/?256f82ee06c4ff81#ARC4E96F7AkwFGgo1E676nQz9cRL8YEL1S5npi4XUCXJ

**Comment by NiLuJe** [comment]
Much like in #8895, I wouldn't mind actual timestamps of your manual Wi-Fi interactions ;).

**Comment by marcingold22** [comment]
Sure!

I tried to connect to Calibre immediately after waking up the device.

From line 100 to 107 I tried to login to WiFi after the prompt, which failed. The prompt appeared again.

From line 108 to 113 I logged in again, this time (I don't know why) it worked, this sometimes happens (after a lot of tries) but it is a very rare event.

From line 114 to the end I just connected to Calibre, but did not send any file to the device (but it worked flawlessly). Then I just got the log and shut the device off completely.

**Comment by NiLuJe** [comment]
The first attempt appears to have timed out during association, which feels somewhat entirely out of our control ;).

**Comment by NiLuJe** [comment]
(Not entirely sure this is fixed, but I hope to have made it slightly less broken, at least ;p).

**Comment by marcingold22** [comment]
Thank you very much @NiLuJe!
