### ISSUE TITLE
Nightly builds web page is not sorted by release date

### ISSUE THREAD

**Issue by deepinvalue** [koreader/koreader#8888]
Releases published on [nightly builds page](build.koreader.rocks/download/nightly/) are not sorted properly. Perhaps add day number so that the release order is maintained.

![image](https://user-images.githubusercontent.com/98733048/157783969-9d0c6542-c8c8-4fd5-8385-8ca22b2bd361.png)

**Comment by NiLuJe** [comment]
We've discussed it in the last, requires webserver trickeries annoying to do on the master. My mirror at koreader.ak-team.com ought to be naturally sorted ;).

**Comment by Frenzie** [comment]
I'm not sure if that's quite what I said. It's extremely low priority of course though.

**Comment by mergen3107** [comment]
If you want to keep some track, remember that they are sorted “unnaturally”, i. e., lexicographically. See here: https://askubuntu.com/questions/874385/sort-command-not-working-as-intended-on-numbers

**Comment by Frenzie** [comment]
Anyway, I've been meaning to do this for years so I stuck on a custom ngx-fancyindex with natsort bolted on and wrote a few basic styles. Fingers crossed that I'm not giving myself a maintenance nightmare… though disabling fancyindex wouldn't be a very big deal either.

## Desktop
![Screenshot_2022-03-12_00-31-09](https://user-images.githubusercontent.com/202757/158014396-c31a4882-3ff7-4494-b626-8bfd05fd2fb8.png)

## Mobile
![Screenshot_2022-03-12_00-31-28](https://user-images.githubusercontent.com/202757/158014395-e0d2aa4f-438f-4b12-849e-a1f902a64dba.png)

**Comment by Frenzie** [comment]
Plus of course one actually showing natsort at work. ;-)

![Screenshot_2022-03-12_11-31-02](https://user-images.githubusercontent.com/202757/158014487-094d094c-4de5-4879-bb94-752285d1cc85.png)
