### ISSUE TITLE
FR: Make it easier to change books' covers

### ISSUE THREAD

**Issue by deepinvalue** [koreader/koreader#8889]
Some books may lack a proper cover, or have nonstandard ones that make Koreader unable to detect and display them. It would be beneficial to be able to set or change covers with ease. 

Here are some suggestions to make this easier:

1. After touch & hold on a picture inside a book, have the option to set it as the cover.
2. Set the cover from a screenshot of the present page.
3. Automatically pick image files named `cover.png|jpg` inside the book's directory.
4. Have a menu item to browse and select an arbitrary image file as cover.

**Comment by pazos** [comment]
Document **viewer**, not document editor ;)

**Comment by NiLuJe** [comment]
calibre can do that for you in a few clicks ;).
