### ISSUE TITLE
[reMarkable 2] Screensaver stays on screen after wakeup and can't be dismissed

### ISSUE THREAD

**Issue by qubist** [koreader/koreader#8891]
* KOReader version: 2022.01
* Device: reMarkable 2

#### Issue

I'm using KOReader on my reMarkable 2. When I wake the device up using the physical button, I see the screensaver message "(i) Sleeping".

* This happens even though the setting "Keep the screensaver on screen after wakeup" is set to "Disable" (as it is by default), and there's no way for me to dismiss this message and get back to using the app.
* If I set that option to "Until a tap" and wake the device up, I see the same message and sometimes when I tap it it goes away, but most of the time my tap isn't accepted. Even more occasionally, one of my taps does seem to get accepted but puts the reMarkable into a strange sleep state where my suspend-screen is shown with colors inverted. If that happens, I can click the physical button to wake it up and then my next tap seems to always be accepted to turn off the screensaver.
* If I set that option to "For 3 seconds" the screensaver doesn't go away after 3 seconds. The strange behavior described above still happens with taps and inverted suspend-screen.

#### Discussion

Ideally, since the reMarkable has its own sleep feature that works within the launcher I'm using (oxide), I'd like to just disable this feature completely, which is what I thought the "Disable" option would do.

I'd be happy to work on fixing this, but I need some guidance as to where to start, since I'm new to the project. (Otherwise loving KOReader!!)

**Comment by NiLuJe** [comment]
c.f., `supportsScreensavers`  in `frontend/device/kindle/device.lua` for a platform with optional SS support ;).

**Comment by qubist** [comment]
You think changing this to `false` would solve the issue?

https://github.com/koreader/koreader/blob/3e78847c46d54e497fc3b1fce0febd96d0d2f65c/frontend/device/remarkable/device.lua#L146

Or... you're also saying reMarkable has optional screensaver support. When does it not have screensaver support? When it's not being run as part of a launcher, but on its own? I've never tried that. In that case, does KOReader handle device sleep and put up its own screensaver?

**Comment by qubist** [comment]
Does anyone use KOReader on reMarkable without a launcher and could weigh in?

**Comment by qubist** [comment]
Here's a workaround someone posted: https://github.com/Eeems-Org/oxide/issues/135#issuecomment-811633258

And someone mentioned another workaround/solution in this comment: https://github.com/Eeems-Org/oxide/issues/135#issuecomment-780380242

> turning autosuspend plugin via koreader's "Plugin management" menu solved the problem.

I will investigate the second one.

**Comment by NiLuJe** [comment]
The second one is kind of missing a key information: turning it `off` or `on`? ;o).

**Comment by qubist** [comment]
lol yeah. I interpreted it as `off` but I don't know anything about plugins or the autosuspend plugin

**Comment by qubist** [comment]
Another question: should I submit a new issue for KOReader falling asleep even though the setting "Keep the screensaver on screen after wakeup" is set to "Disable"?

**Comment by qubist** [comment]
Related: https://github.com/Eeems-Org/oxide/issues/135

**Comment by qubist** [comment]
> lol yeah. I interpreted it as off but I don't know anything about plugins or the autosuspend plugin. Let me try right now and see what happens

Turning this `off` didn't solve the issue. But I did find if I suspend the device again and the wake it up, the screensaver will go away (second time). Just like what they found in https://github.com/Eeems-Org/oxide/issues/135

**Comment by qubist** [comment]
Cool, changing `/opt/koreader/frontend/device/remarkable/event_map.lua` to


```lua
return {
    [102] = "Home",
    [105] = "LPgBack",
    [106] = "RPgFwd",
    [116] = "noop",
}
-- TODO libremarkable has 143 as "wakeup" - don't know what that corresponds to?
```

Solved this issue for me. I'll submit a PR.

**Comment by qubist** [comment]
See discussion in #8900

**Comment by KeepBotting** [comment]
> Cool, changing `/opt/koreader/frontend/device/remarkable/event_map.lua` to
> 
> return {
>     [102] = "Home",
>     [105] = "LPgBack",
>     [106] = "RPgFwd",
>     [116] = "noop",
> }
> -- TODO libremarkable has 143 as "wakeup" - don't know what that corresponds to?
> 
> Solved this issue for me. I'll submit a PR.

I still have to do this on rM2 (firmware 3.3.2.1666) with Odixe 2.8.4-3 and KOReader 2024.11-1 from Toltec.

Without this change, Odixe and KOReader _both_ appear to try suspending the device which makes waking up difficult. Sometimes I can manage to wake Oxide and then wake KOReader, other times attempting to wake KOReader appears to send Oxide to sleep again (or vice versa, hard to tell).

With the change, Oxide handles suspend/wakeup, KOReader is unaffected, and everything appears to function normally.

I guess the device.lua fix that was added by this PR is no longer working? `systemctl is-active tarnish` returns `active` on my system though so I am not sure what the problem is.

#13795 seems to be another fix but it was just merged and isn't in a KOReader release yet (Toltec repo is also not up to date with 2025.04).

**Comment by landynmj** [comment]
Same issue, would be good to have an option to tell KO not to handle the sleep button at all.
