### ISSUE TITLE
terminal plugin doesn't appear on Kobo Aura HD

### ISSUE THREAD

**Issue by emacsomancer** [koreader/koreader#8893]
* KOReader version: 2022.2
* Device: Kobo Aura HD

#### Issue
terminal does not appear in plugins
[crash.log](https://github.com/koreader/koreader/files/8238158/crash.log)

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by zwim** [comment]
Thank you for the log.

```
03/12/22-11:19:11 WARN  Error when loading plugins/terminal.koplugin/main.lua
``` 
shows, that there might some problem with `/dev/ptmx`, `grantpt` or `unlockpt` on your device.
It seems that KOReader has was not started on that device from 11/22/20 to 03/07/22 and then an update was done.

On which firmware version is the device running?

**Comment by emacsomancer** [comment]
I thought the firmware had updated already, but it seems that it hadn't. After an update, the terminal works.

**Comment by Frenzie** [comment]
@emacsomancer If you happen to remember, could you please share which firmware version didn't work though?

**Comment by emacsomancer** [comment]
I don't remember/didn't see, but it would have been whatever the latest firmware of 22-11-2020 would have been.

**Comment by Frenzie** [comment]
As a data point, the last time I updated the firmware on my H2O was ca. 2018.

While of course that's not the same device, I do have to wonder if it wasn't simply something about properly restarting KOReader (or less likely the device itself). Oh well, glad it's solved.

**Comment by zwim** [comment]
Good to hear terminal is working now.
Just for the records: It could have been an outdated firmware or a device running out of /dev/pts's .

@Frenzie, @NiLuJe : Would it make sense to add the firmware version (if detectable) in addition to the device somewhere in the log, too.

**Comment by Frenzie** [comment]
I find the firmware version a quite unlikely hypothesis, assuming that opening several instances of a shell like Bash does all the same things anyway. (In which case I can safely say that it all worked just fine in 2014 on 3.14.)

I guess you could add it, but generally there aren't really any changes really worth mentioning besides in some cases the first few months.

**Comment by NiLuJe** [comment]
It's logged during actual crashes, FWIW, but not during a standard startup/exit ;).

The way KOReader is started might affect things (and/or whether you have/had an SSHD running), as this may affect relevant system setup.
