### ISSUE TITLE
`Start USB storage` freezes

### ISSUE THREAD

**Issue by JakubGIT** [koreader/koreader#8896]
* KOReader version: v2022.02
* Device: Kobo_io
> Kobo SW Version: 4.31.19086 (2adb3f45ad, 1/20/22)
> Waveform: 400_B044_HH0D01_ED070KH3U3_VD1400-GOB_TC
> Kernel Version: 4.1.15-00756.gdf30b9c5883
> Touch Firmware: 6408
> Status Code: 0
> Bluetooth Firmware: aaa82df5.03

#### Issue
USB Storage connection freezes (always) immediatelly after the computer is connected

#### Steps to reproduce
1. connect the device to a computer
2. confirm USB connection on the device

or

1. menu/<kbd>Start USB storage</kbd>
2. connect the device to a computer

##### `crash.log` (if applicable)
[crash.log](https://github.com/koreader/koreader/files/8239858/crash.log)

**Comment by NiLuJe** [comment]
Freezes on *which* screen?

**Comment by JakubGIT** [comment]
> Freezes on _which_ screen?

"*Starting usb connection*" or "*establishing usb connection*" or how exactly it is called.

Before the last KOReader update an error page was shown ("*could not start usb connection*"), now it simply freezes.

**Comment by NiLuJe** [comment]
I'm going to need live system logs, c.f., https://github.com/koreader/koreader/issues/6582#issuecomment-683297132 this old comment (except, well, with sensible final steps for your own issue ;p).

A `cat /usr/local/KoboUSBMS.log` after the fact might also yield valuable information ;).

**Comment by JakubGIT** [comment]
#### live log
- It doesn't work with the live log (in case I got right, what I should do)
- When I have SSH open and try to connect a computer per usb, this happens:
```bash
Mar 14 07:52:22 usbms[4371]: Initializing USBMS v1.2.6 (2022-02-05 19:03:23 +0100)
Mar 14 07:52:22 usbms[4371]: [FBInk] Detected a Kobo Libra 2 (388 => Io @ Mark 9)
Mar 14 07:52:22 usbms[4371]: [FBInk] Enabled Kobo Mark 7 quirks
Mar 14 07:52:22 usbms[4371]: [FBInk] Clock tick frequency appears to be 100 Hz
Mar 14 07:52:22 usbms[4371]: [FBInk] Screen density set to 300 dpi
Mar 14 07:52:22 usbms[4371]: [FBInk] Variable fb info: 1264x1680, 8bpp @ rotation: 1 (Clockwise, 90°)
Mar 14 07:52:22 usbms[4371]: [FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 9175040 bytes & line length: 1280 bytes
Mar 14 07:52:22 usbms[4371]: [FBInk] Canonical rotation: 0 (Upright, 0°)
Mar 14 07:52:22 usbms[4371]: [FBInk] Fontsize set to 32x32 (IBM (Default) base glyph size: 8x8)
Mar 14 07:52:22 usbms[4371]: [FBInk] Line length: 39 cols, Page size: 52 rows
Mar 14 07:52:22 usbms[4371]: [FBInk] Vertical fit isn't perfect, shifting rows down by 8 pixels
Mar 14 07:52:22 usbms[4371]: [FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Mar 14 07:52:22 usbms[4371]: Initialized FBInk v1.24.0-93-g71760e2 for Kobo
Mar 14 07:52:22 usbms[4371]: [setup_usb_ids:138] USB product ID: 0x4234
Mar 14 07:52:22 usbms[4371]: Initialized libue v1.4.0
Mar 14 07:52:22 usbms[4371]: Initialized libevdev v1.12.0 for device `gpio-keys`
Mar 14 07:52:22 usbms[4371]: [FBInk] Font `/mnt/usbms/resources/fonts/CaskaydiaCove_NF.otf` loaded for style 'Regular'
Mar 14 07:52:22 usbms[4371]: Internal storage partition is busy, can't export it!
Mar 14 07:52:22 usbms[4371]: Listing all offending processes…
Mar 14 07:52:22 fuser-check.sh[4373]: 4332 -> dropbear
Mar 14 07:52:22 fuser-check.sh[4373]: 4350 -> dropbear
Mar 14 07:52:22 usbms[4371]: Waiting for a power button press…
Mar 14 07:52:53 usbms[4371]: It's been 30 sec, giving up
Mar 14 07:52:56 usbms[4371]: Bye!
```

#### `/usr/local/KoboUSBMS.log`
```
+ '[' true '=' true ]
+ set -o pipefail
+ basename /mnt/usbms/scripts/start-usbms.sh
+ SCRIPT_NAME=start-usbms.sh
+ grep -q -e ^g_file_storage -e ^g_mass_storage /proc/modules
+ USB_VENDOR_ID=0x2237
+ VERSION_TAG=/mnt/onboard/.kobo/version
+ '[' -f /mnt/onboard/.kobo/version ]
+ cut -f1 -d, /mnt/onboard/.kobo/version
+ SERIAL_NUMBER=N418190093026
+ cut -f3 -d, /mnt/onboard/.kobo/version
+ FW_VERSION=4.31.19086
+ DISK=/dev/mmcblk
+ PARTITIONS=/dev/mmcblk0p3
+ '[' -e /dev/mmcblk1p1 ]
+ sync
+ echo 3
+ DIR=/mnt/sd
+ grep -q /mnt/sd /proc/mounts
+ DIR=/mnt/onboard
+ grep -q /mnt/onboard /proc/mounts
+ umount /mnt/onboard
+ MODULES_PATH=/drivers/mx6sll-ntx
+ GADGETS_PATH=/drivers/mx6sll-ntx/usb/gadget
+ '[' -e /drivers/mx6sll-ntx/g_mass_storage.ko ]
+ '[' mx6sll-ntx '=' mx6sll-ntx ]
+ PARAMS='idVendor=0x2237 idProduct=0x4234 iManufacturer=Kobo iProduct=eReader-4                                                                                                                                            .31.19086 iSerialNumber=N418190093026'
+ insmod /drivers/mx6sll-ntx/usb/gadget/configfs.ko

```

**Comment by NiLuJe** [comment]
Much like in your other issue, I wouldn't mind having the kernel logs in there (so, run `kloigd` once before everything).

**Comment by NiLuJe** [comment]
Note to self: hell, for all I know, it might be a Libra 2 special EPDC hang because of the status bar refreshes?

**Comment by JakubGIT** [comment]
Ok, I'll try :-)

This is my second installation of KOReader on this device. I updated Nickel, so I had to reinstall.
The first installation on an earlier version of Nickel (I cannot say which one it was) didn't have the problem with usb (but it froze quite often in the dictionary)

**Comment by JakubGIT** [comment]
So.

1. ssh per Kobo Stuff
2. `klogd`
3. `logread -F`
4. <kbd>Start USB Session</kbd>
5. Error: "could not end the session, turning off in 90s"(!) 
6. <kbd>ctrl</kbd> + <c>
7. `logread`

- [puttyAA.log](https://github.com/koreader/koreader/files/8260207/puttyAA.log)

but - this was the second try, the first time I didn't let putty log itself and copied from the screen, which made the earlier messages disappear, that's why I repeated. But the first time, the USB connection worked!!! But nevertheless it crashed after I safely removed the device and plugged off the usb cable

#### also interesting
nickel doesn't connect to pc either has KOReader already run. The device must be rebooted to achieve the normal functionality

**Comment by DongRih** [comment]
> the USB connection worked!!! But nevertheless it crashed after I safely removed the device and plugged off the usb cable

Interesting. #8910

**Comment by NiLuJe** [comment]
Does [this](https://github.com/koreader/koreader/issues/8910#issuecomment-1069571604) help, too?

**Comment by JakubGIT** [comment]
unfortunatelly not

2 times it didn't crash but closed the connection itself very quickly (I believe the conneciton was there for a second or so)
immediatelly after that, koreader has offered a new connection, which I accepted
the third time it crashed

[putty03-17-075935.log](https://github.com/koreader/koreader/files/8282157/putty03-17-075935.log)

**Comment by NiLuJe** [comment]
Err, what do you mean by "the connection"? The actual USB storage pop-up in KOReader? Because that would be fairly orthogonal to the issue I'm looking at ;p'

**Comment by JakubGIT** [comment]
I mean, I think I saw an external drive on my.pc for a sec

**Comment by NiLuJe** [comment]
Oh, hey, a kernel OOPS (what a surprise...).

I don't really have any other Libra 2 logs to compare to, but this one looks super fishy, so much so that I wouldn't exclude a dodgy cable and/or port (on either side of the connection).

**Comment by NiLuJe** [comment]
i.e., this is an open call to Libra 2 users to come and test to see if this is a localized issue or not ;).

**Comment by JakubGIT** [comment]
> Oh, hey, a kernel OOPS (what a surprise...).
> 
> I don't really have any other Libra 2 logs to compare to, but this one looks super fishy, so much so that I wouldn't exclude a dodgy cable and/or port (on either side of the connection).

### I've tested with two cables and two PCs
- the cable is ok
#### PC1
- there are almost no problems with a "simple pc", only once (of 5) the external drive didn't appear, but the USBMS didn't crash

#### PC2
- this is a domain-pc with trend-micro
- this pc was used for the logging
- there is a difference between
    1. starting usbms from the menu and then plugging a cable
    2. plugging a cable and confirm the connection
    - the second option works just fine!
    - the first option works 25/25/50
        - 25: works fine
        - 25: doesn't crash, doesn't create an external drive
        - 50: crashes and turns off

#### so...
- there may be something special about the pc2, but Nickel-USB connection works fine there (only sometimes one has to connect it twice)   
- there is definitely a difference between starting usbms from the menu or first plugging a cable
- the patch you made removed the problem partially

#### great job
- I am not sure whether I've already say thank you in a post: so definitely a huge thank you :-)

**Comment by NiLuJe** [comment]
> 
>     * there is definitely a difference between starting usbms from the menu or first plugging a cable
> 

Ha! That's a *very* interesting distinction, and one I was always wondering why my cowboy method of hoping for the best appeared to behave so far ;).

By which I mean, we currently start the session as soon as the kernel tells us "hey, usb cable!". Knowing NTX boards (and... embedded USB controllers in general, to be honest), that may be a tad optimistic ;).

It would probably not be completely stupid to simply wait for a second or two for things to actually settle properly.

I'll give you a test binary later tonight, thanks for the detailed rundown of your experiments, that was very helpful ;).

**Comment by NiLuJe** [comment]
Okay, realized that we were skipping the charger type check in the "plugged in after startup" case, which was... possibly not great, but not necessarily critical here, because it appears to be set fairly erratically on your device (which, err, might be an issue in and of itself, but possibly not entirely relevant here).

Anyway, here's a test binary that takes a more defensive approach to this use-case (replace the `koreader/data/KoboUSBMS.tar.gz` file w/ it).

[KoboUSBMS.tar.gz](https://github.com/koreader/koreader/files/8312758/KoboUSBMS.tar.gz)

**Comment by JakubGIT** [comment]
> Okay, realized that we were skipping the charger type check in the "plugged in after startup" case, which was... possibly not great, but not necessarily critical here, because it appears to be set fairly erratically on your device (which, err, might be an issue in and of itself, but possibly not entirely relevant here).
> 
> Anyway, here's a test binary that takes a more defensive approach to this use-case (replace the `koreader/data/KoboUSBMS.tar.gz` file w/ it).
> 
> [KoboUSBMS.tar.gz](https://github.com/koreader/koreader/files/8312758/KoboUSBMS.tar.gz)

# YES!

- pc2 works perfect, both cable first and menu first

great job, thanks!

**Comment by NiLuJe** [comment]
Random stupid test, because I switched tacks to handle the initial module loading issue ;).

Does this binary still work?

[KoboUSBMS.tar.gz](https://github.com/koreader/koreader/files/8337215/KoboUSBMS.tar.gz)

**Comment by JakubGIT** [comment]
yes it does.

I had some problems as I tested but I cannot replicate them now though and
I believe it was the pc/trend micro causing them

**Comment by NiLuJe** [comment]
Cool, thanks! (what kind of problems, though?).

**Comment by JakubGIT** [comment]
No connection at all.
usbms stopped the connection immediatelly or said it is only a power source.
Nickel couldn't connect either.

I believe Trend Micro blocked the MAC Address of the device
