### ISSUE TITLE
FR: Reading Progress in Mosaic view

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#8897]
Title is kinda self-explanatory. Is it possible to show reading progress in percentage in the Mosaic view?

If yes, I'm ready to use my rudimentary lua skill to implement this.

**Comment by poire-z** [comment]
Probably possible, and less costly and questionable than #8390.
But it would have to look pretty :)
For the rest, there's not much improvisation possible:
- it should be an option (because not everybody would want to see it), like "hint for opened books" (and then, it becomes an alternative for "hint for opened book" because you could only show some progress indicator for opened books)
- it should get the % from the doc settings, and cache it - just like ListMenu already does it, so possibly reusing its `self.menu.cover_info_cache`
- it should be drawn in `MosaicMenuItem:paintTo()` like the other cosmetic additions

For the look, it could be a progress bar at bottom (no need to use our progressbar widget, a few paintRect/paintBorder should be enough), or some filling of our top right dogear/triangle ? Other ideas ?

**Comment by uroybd** [comment]
> For the look, it could be a progress bar at bottom (no need to use our progressbar widget, a few paintRect/paintBorder should be enough), or some filling of our top right dogear/triangle? Other ideas?

I think dogear will be nicer with progress in percentage.

**Comment by uroybd** [comment]
Currently my Pocketbook P78 shows like this:

![IMG_20220315_000657](https://user-images.githubusercontent.com/4207230/158234179-bc963828-f5ab-4636-a1af-85cc44980603.jpg)

Onyx Boox also show things quite like this.

Is drawing over is harder than creating a progressbar?

**Comment by ichnilatis-gr** [comment]
> Currently my Pocketbook P78 shows like this:

I don't think this is a Pocketbook device. It seems to be a Boyue Likebook P78.
I give you an image of a Pocketbook device where you can see the progress bar they use with the book cover icons. I think it's a good idea.
![touch-lux-5](https://user-images.githubusercontent.com/76203123/158384667-f78abac8-ba8b-4101-97f1-c728a7e8866c.jpg)

**Comment by uroybd** [comment]
> > Currently my Pocketbook P78 shows like this:
> 
> I don't think this is a Pocketbook device. 

Sorry, it was Likebook. My mistake.

**Comment by poire-z** [comment]
Built from scratch.
And the code is the doc :) We all learned it by looking at how other complex widgets work and build on/use lower simpler widgets.
And it's quite complex. And the eInk refreshes/setDirty needed tricks make it even more complex.

But for your case, you don't want to play with widgets:

> it should be drawn in MosaicMenuItem:paintTo() like the other cosmetic additions

The covers/thumbnails are real widgets, that are correctly sized and positionned in some nested containers widgets.
You don't want to mess with all this. You can just "paint" your cosmectic tweaks over/outside the covers when each cover is painted itself.
(ie: you won't make the cover smaller to get room to paint some progress bar: you will paint the progress bar over or outside the cover - and if outside, hoping it will be part of the area refreshed.)

**Comment by Frenzie** [comment]
There are also some clarifying comments in the code, automatically extracted to http://koreader.rocks/doc

http://koreader.rocks/doc/modules/ui.widget.widget.html
http://koreader.rocks/doc/modules/ui.widget.inputdialog.html

**Comment by uroybd** [comment]
Thank you very much. I'll dive in.

**Comment by uroybd** [comment]
I was toying with Progressbar. A problem with the progress bar in the bottom is, in the desktop, there are keyboard marks, and on all platforms, there will be dogear for open books.

![Screenshot from 2022-03-16 11-28-26](https://user-images.githubusercontent.com/4207230/158522859-b6782dd8-c1a6-466e-8392-d7746046ceab.png)

This will make a bottom progress bar both difficult to render and ugly.

We can try a progress bar on top, or, we can go for a dogear. In need of some advice.

**Comment by uroybd** [comment]
I just made it 1/3 of cover image size, aligned it from the bottom-right.

Here's the result:
![Screenshot from 2022-03-16 16-00-42](https://user-images.githubusercontent.com/4207230/158565964-44c2c6af-a4f1-43f1-8bbe-17889b3548f5.png)

**Comment by uroybd** [comment]
That's a good idea. But don't you think it will clutter the bottom? I will try the style you've explained, let's see how it looks.

**Comment by uroybd** [comment]
@poire-z I've tried your idea. It looks like this:

![Screenshot from 2022-03-16 20-09-51](https://user-images.githubusercontent.com/4207230/158609188-50786d4c-ee0b-4a58-8d39-44fcaa7965b7.png)
![Screenshot from 2022-03-16 20-10-07](https://user-images.githubusercontent.com/4207230/158609201-bc0c110a-fc7f-46f9-aea5-12c8ed3d6d1c.png)

**Comment by poire-z** [comment]
Not so nice then :)
Indeed, your initial smaller/thinner progress bar looks better (to me) than the taller one on these 2 screenshots.

What if there wasn't any gap between the bar and the dogear?
Or even, no original dogear, but a new long thin dogear, as on your last screenshot, and a opaque white triangle with only the diagonal border, drawn at its edge ?

But ok, may be just your original thin bar, anchored at the place of the original dogear, is just fine.

**Comment by uroybd** [comment]
> But ok, may be just your original thin bar, anchored at the place of the original dogear, is just fine.

Reverting it then. :smile:

**Comment by uroybd** [comment]
I've opened this PR #8915 8915

**Comment by CaptainLexington** [comment]
I just enabled this feature, and it seems the percentage it calculates doesn't incorporate hidden flows, leading to inconsistent percentages between mosaic view and the book itself.
