### ISSUE TITLE
KOreader doesn’t wake up from sleep on Pocketbook

### ISSUE THREAD

**Issue by ploum** [koreader/koreader#8898]
* KOReader version: 2022-02-16 (development OTA version on March 13th)
* Device: PB632-V632.6x5.1383.

#### Issue
When waking the device from sleep, the screen get blocked on sleep screen with koreader page inverted. A reboot of the device is needed.

Note : this is always reproducible and started with the OTA upgrade to 2022-02 (stable) from 2021-11.

#### Steps to reproduce:
1. open an epub file in koreader
2. close the smart cover
3. open the smart cover

##### `crash.log` (if applicable)
There’s no crash.log. It seems that koreader doesn’t crash but suspend the waking up process.

Here’s a picture of the device after waking up. Note that I use inverted colors so normal koreader is white text on black background. The displayed page is thus inverted.

![IMG_20220313_163251](https://user-images.githubusercontent.com/1233155/158067604-fb498fed-f82f-4d4a-a5be-e2cbbe0df079.jpg)

**Comment by NiLuJe** [comment]
What happens if we take the smart cover out of the equation?

**Comment by NiLuJe** [comment]
Also, as mentioned in the earlier issue, debug logs would be helpful, although it might be tricky on this specific case depending on whether the device fully hangs or not...

**Comment by ploum** [comment]
This is the crashlog with debug enabled. I’m not familiar with koreader source code but I fear this log ends before the freeze.

If there’s anything else I can do to help, just tell me.

[crash.log](https://github.com/koreader/koreader/files/8240208/crash.log)

**Comment by Frenzie** [comment]
Indeed, there's nothing indicating a resume.

**Comment by rjd22** [comment]
@ploum does disabling inversion solve improve things? We did some changes here.

I doubt it will but to just be sure.

**Comment by NiLuJe** [comment]
> If there’s anything else I can do to help, just tell me.
> 

Yes: https://github.com/koreader/koreader/issues/8898#issuecomment-1066129869

(i.e., get it out of the cover entirely, make sure it's never left near strong enough magnets, and just use it as before, but using the power button ;)).

**Comment by NiLuJe** [comment]
That's... strange. nightmode doesn't actually "do" anything anymore since the IV backend change.

**Comment by ploum** [comment]
I can confirm that disabling night mode seems to solve the bug completely while the bug reappear as soon as I enable night mode.

It’s a bit tricky because before the nightly, the bug appeared immediately on closing the lid. Now, it seems that the bug only happen after some time.  If I let the Pocketbook sleeping at least a couple of hours with night mode, then the bug happens. 

I’m really not familiar with the technology used but I remarked that, even without night shift, waking up from sleep induces two "flashs". The screen is inverted then inverted again to go back to normal. (probably a kind of screen refresh).  One hypothesis is that this "flash" hang when in night mode.  But that’s pure guessing.

**Comment by rjd22** [comment]
@ploum could you make a video of what happens when it crashes? Does it completely lock up?

Does removing the smart cover also change the behavior?

**Comment by ploum** [comment]
On 22/03/19 11:54, Robert-Jan de Dreu - notifications at github.com wrote:
***@***.*** could you make a video of what happens when it crashes? Does it completely lock up?
>
>Does removing the smart cover also change the behavior?
>
I’m not sure a video would add anything as it is static. But I did a few 
more tests and I can say that:

- It is definitely enabled by nightmode
- It’s not related to the cover.

Also, I have the feeling that the crash is happening not when waking 
from sleep but when going to sleep.

When going to sleep, a kind of "transluscent screen" is applied on top 
of the current page, fading the letters and displaying the "sleeping 
bubble" on top of it. I feel like this kind of "translucent screen" is 
not playing well with night mode.

(Will try to make and post a video later)

**Comment by ploum** [comment]
I did a few tests. Upgraded the firmware from PB to Vivlio  (the device was sold by Vivlio).  Also upgraded to the latest koreader nightly. This

I can confirm that the bug:

- happens only in night mode  (did multiple weeks without night mode without hitting the bug once). This is definitely related to night mode.
- is not related to cover.
- happens when waking up from sleep (not when sleeping)
- does not happen if you wake up from sleep immediately. You have to let the device sleep at least a few minutes. Then, it will freeze when trying to wake up. (there seems to be a probability of freezing related to the duration of the sleep. It never crash with an immediate wake up, it sometimes crash after a 1 minute of sleep, it always crash after a few hours of sleep)

**Comment by rjd22** [comment]
The only easy fix I can think off is disabling night mode when sleeping and enabling it when waking up. Without and crash logs it's impossible to figure out what causes night mode to crash the system when waking up.

**Comment by ploum** [comment]
Is there a way I could investigate the bug? The freeze seems to not put anything useful in the crash log. I suspect that koreader does not crash at all and that the crashlog only happens because I’m forced to reboot the device.

**Comment by rjd22** [comment]
@ploum sadly I'm too inexperienced to give you a correct answer on that. Maybe @NiLuJe or @Frenzie have a suggestion?

**Comment by Frenzie** [comment]
That's with debug log enabled?

**Comment by NiLuJe** [comment]
That feels like a PB firmware/hardware issue we have no control over, so, nothing we can really do about it.

I'm unfamiliar with PB kernels, but even if it did miraculously log enough to grok what happens, the fact that it crashes around a power managed state makes actually getting at the log kind of a nightmare without serial access.

**Comment by NiLuJe** [comment]
Interested parties might try to work it around in a slightly less "scorched earth" approach by bracketing suspend states with a nightmode toggle to avoid suspending with nightmode, but it's not going to be pretty ;).

**Comment by ploum** [comment]
I mistakenly broke the device and bought the same model (although from a different "brand").  I installed koreader and tested : seems that the bug is gone. Maybe this was something faulty in my device
