### ISSUE TITLE
Wiki: More keyboard shortcuts

### ISSUE THREAD

**Issue by comphilip** [koreader/koreader#8908]
Add more keyboard shortcuts to wiki Keyboard Navigation.

Commit to review: https://github.com/comphilip/koreader-wiki/commit/4ec18ab0185cfd2292264731a28a5fbcc3f8da11

**Comment by Frenzie** [comment]
Looks good to me  👍

**Comment by poire-z** [comment]
No idea how we can merge the above commit in the Wiki.
But feel free to just edit our Wiki and add your changes.
Closing this by anticipation :)
