### ISSUE TITLE
Jagged text on Onyx Boox Note Air and Nova Air

### ISSUE THREAD

**Issue by derekvan** [koreader/koreader#8912]
* KOReader version: 2022.02
* Device: Ony Boox Note Air

#### Issue

Fonts look jagged. Compare photos of text from KO Reader and Kindle app on the same device. 

KOReader:
![IMG_4536](https://user-images.githubusercontent.com/890341/158492550-cce5c5ab-3a6b-448b-9a57-c77745bc5665.jpeg)

Kindle App:
![IMG_4537](https://user-images.githubusercontent.com/890341/158492553-0ca76d3f-e737-4275-9ab1-cd8377b77195.jpeg)

Also see this post on Reddit: https://www.reddit.com/r/Onyx_Boox/comments/t9ksvk/nova_air_with_koreader_bookerly_font_pixelated/

**Comment by pazos** [comment]
disable **all** optimizations for this app. They're not needed for an app actually made for eink devices

**Comment by derekvan** [comment]
Awesome, that's the fix. Thanks!
