### ISSUE TITLE
Frontlight warmth slider doesn't work (Kobo Aura One)

### ISSUE THREAD

**Issue by CalbertAmu** [koreader/koreader#8913]
* KOReader version: 2022.02-21 ... (2022-03-15)
* Device: Kobo Aura One

#### Issue
The slider to set the warmth is not behaving right.
When I set the warmth to about halfway on the slider, the slider shows it being in the middle, but the value is 10, and it shows 10 as well.
If I tap on the farthest block on the slider, it shows that it's maxed out, but the value is 20.

Setting the warmth through the slider is impossible right now as I can't go above 20. I managed to set the desired warmth by tapping Max, then tapping the + and -

I'm on the latest development update

**Comment by NiLuJe** [comment]
What's the actual range on the Aura One usually? Was it 0 to 100?

**Comment by CalbertAmu** [comment]
Yes

**Comment by CalbertAmu** [comment]
Merci

**Comment by NiLuJe** [comment]
Thanks ;).

And since my first thought appears to have been wrong, I'm going to bother you a little bit more and ask for you to enable debug logging, restart KOReader, then try setting the warmth a couple of ways (bar, +/- buttons, eventually the edge swipe gesture if you still have it), and look at your crash.log and post the lines that start with `set light warmth`.

**Comment by CalbertAmu** [comment]
Debug logging was already on, so I restarted koreader then tried to increase warmth in those ways, with edge swipes as well. Not sure if this is what u want: 

03/16/22-03:23:28 DEBUG set light warmth 9 -> 9
03/16/22-03:23:28 DEBUG FocusManager: Move focus position to: 1 , 1
03/16/22-03:23:28 DEBUG setDirty via a func from widget table: 0x2dd2a6f0
03/16/22-03:23:28 DEBUG FocusManager: Move focus position to: 1 , 1
03/16/22-03:23:28 DEBUG setDirty via a func from widget table: 0x2dd2a6f0
03/16/22-03:23:28 DEBUG painting widget: table: 0x2f0b68f0
03/16/22-03:23:28 DEBUG blitFrom 1299 435 0 0 47 47
03/16/22-03:23:28 DEBUG update_mode: Update refresh mode fast to ui
03/16/22-03:23:28 DEBUG _refresh: Enqueued ui update for region 32 410 1339 1051 
03/16/22-03:23:28 DEBUG _refresh: Enqueued ui update for region 32 410 1339 1051 
# 03/16/22-03:23:28  triggering refresh {
    ["region"] = {
        ["y"] = 410,
        ["w"] = 1339,
        ["h"] = 1051,
        ["x"] = 32,
    },
    ["mode"] = "ui",
}

====

03/16/22-18:46:20 DEBUG set light warmth 48 -> 48
03/16/22-18:46:20 DEBUG FocusManager: Move focus position to: 1 , 1
03/16/22-18:46:20 DEBUG setDirty via a func from widget table: 0x2de501a0
03/16/22-18:46:20 DEBUG FocusManager: Move focus position to: 1 , 1
03/16/22-18:46:20 DEBUG setDirty via a func from widget table: 0x2de501a0
03/16/22-18:46:20 DEBUG painting widget: table: 0x2de78eb0
03/16/22-18:46:20 DEBUG blitFrom 1299 435 0 0 47 47
03/16/22-18:46:20 DEBUG _refresh: Enqueued ui update for region 70 1162 1262 82 
03/16/22-18:46:20 DEBUG update_mode: Update refresh mode fast to ui
03/16/22-18:46:20 DEBUG _refresh: Enqueued ui update for region 32 410 1339 1051 
# 03/16/22-18:46:20  triggering refresh {
    ["mode"] = "ui",
    ["region"] = {
        ["y"] = 410,
        ["w"] = 1339,
        ["h"] = 1051,
        ["x"] = 32,
    },
}

I'll attach this newer section from the crash.lo
[crash log.txt](https://github.com/koreader/koreader/files/8275595/crash.log.txt)
g

**Comment by NiLuJe** [comment]
Could you test the changes in #8935?

(I don't have a device to repro this ;)).

**Comment by CalbertAmu** [comment]
I updated today, version 03-21. It's still the same

**Comment by NiLuJe** [comment]
This hasn't hit a nightly, you'll have to app;y the changes manually ;).

**Comment by CalbertAmu** [comment]
YES! It's working correctly now. Thank you

**Comment by CalbertAmu** [comment]
I accidentally found a way to crash koreader through the frontlight widget. It happens when I hold any Warmth bar, but not Brightness.

[crashlog.txt](https://github.com/koreader/koreader/files/8322843/crashlog.txt)
