### ISSUE TITLE
FR: Set Cover Image using Android Intent

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#8928]
The current `coverimage` plugin works only once in Likebook P78. It seems like, upon setting the cover image it copies the file instead of linking to it. Internally it is just wallpaper. You can set any image as a screensaver using `gallery > set wallpaper`.

A solution for this can be setting cover images using `wallpaperManager`. Here's an [implementation](https://www.geeksforgeeks.org/how-to-set-an-image-as-wallpaper-programmatically-in-android/).

This can be an optional feature (user can opt-in if necessary) but it will work on a range of android devices.

**Comment by Frenzie** [comment]
Presumably that device had no other way, despite running on Android 8.1? Kind of weird, admittedly. At a quick glance that example with WallpaperManager will probably only work on API 23 (Android 6.0) and higher. Keep in mind we currently support API 14 (Android 4.0) and higher. That's not at all a mark against implementing it of course, besides implementing a few sanity checks for which we have plenty of existing examples in the code.

**Comment by uroybd** [comment]
> Presumably that device had no other way, despite running on Android 8.1? Kind of weird, admittedly.

You can save the cover image and set it as a screensever. But will not get updated on regeneration.

**Comment by Frenzie** [comment]
Anyway, @zwim is the person to ask. The rest of us don't know much about the device.

**Comment by pazos** [comment]
I think it is something that only works on Boyue.

**Comment by zwim** [comment]
Sorry, I can't help here. Coverimage was designed to save the current image to a certain file. 
If your Android device uses that file you have luck, if not ... 
Maybe you find an app, which can set your "wallpaper" to a certain file on suspend. It seems that there are thousands of wallpaper changer apps out there; or use something like MacroDroid
