### ISSUE TITLE
(CJK typography) spaces between characters in last line of paragraph different from previous lines

### ISSUE THREAD

**Issue by DongRih** [koreader/koreader#8929]
Spaces between characters in last line of paragraph different from previous lines.

![image](https://user-images.githubusercontent.com/35327409/159170095-18a4640c-0dda-4f3e-ae2c-973b975353c0.png)
Last line seems too condensed.

**Expected behavior:**
![image](https://user-images.githubusercontent.com/35327409/159169995-c974ab57-9744-46ee-a12b-809dd98d4be2.png)

**Comment by poire-z** [comment]
I have forgotten much of what I asked (and planned to do) in #6162 - but I think this may be related and possibly one of the points that needed feedback/solving/decision in there (ie. the importance of the grid - I think most of the feedback was that it wasn't that important, although I thought it would be very important).
I don't plan any work on that soon, but please have a look there, and answer the questions if you can, so what can/could/should be done is not scattered around :)

**Comment by DongRih** [comment]
Actually I saw #6162 , and even attempted to answer these questions (before opening up this issue). But there are too many questions and too many comments, which seems a little bit overwhelming to me. 

Any way,  I may gradually compose my answers later. Thank you for your effort.

**Comment by DongRih** [comment]
Thank you for your effort! @poire-z 🎉
