### ISSUE TITLE
wallabag crash: attempt to index upvalue 'tou chmenu_instance' (a nil value)

### ISSUE THREAD

**Issue by anarcat** [koreader/koreader#8930]
* KOReader version: 2022.03
* Device: Kobo Aura

#### Issue

When finalizing the wallabag configuration, koreader completely crashes with

```
03/20/22-21:25:54 INFO  GestureDetector:probeClockSource: Touch event timestamps
 appear to use CLOCK_REALTIME
./luajit: plugins/wallabag.koplugin/main.lua:1084: attempt to index upvalue 'tou
chmenu_instance' (a nil value)
```

#### Steps to reproduce

 1. install koreader 2022.03 with the "nickelmenu" method
 2. configure the credentials by hand in the `.lua` file
 3. create a "wallabag" directory in `/mnt/onboard/`
 4. configure a few other (unrelated?) settings ("send review as tags", "remove fnished articles from history", do *not* "Remotely delete finished articles" (what a dangerous default! :)), "Mark as read instead of deleting", "Process deletions when downloading", "Synchronize remotely deleted files")
 5. tap the "Retrieve new articles from server" menu item
 6. get the "Please configure the server settings and set a download folder" popup, with a star next to the "Server" button, tap the "Folder" button
 7. choose the `wallabag` folder with a long press
 8. crash

You will forgive me for the button names, I might have the exact 

##### `crash.log` (if applicable)

[crash.log](https://github.com/koreader/koreader/files/8312615/crash.log)

**Comment by anarcat** [comment]
i should also mention it's my first time trying the wallabag plugin, so i don't know if it's a regression or what, but things seem kind of broken from my end of the spectrum here. :p

**Comment by anarcat** [comment]
oh yeah, and i just noticed the `wallabag.lua` config file was reset somehow.

**Comment by Frenzie** [comment]
Did you do this from the reader or the file browser?

**Comment by Frenzie** [comment]
Probably not, but I can't immediately reproduce it.

**Comment by Frenzie** [comment]
You could just replace the file with [this one](https://raw.githubusercontent.com/koreader/koreader/eeefc657cbfca22dff9c370b2884d63e20fd4c8f/plugins/wallabag.koplugin/main.lua), or wait until tomorrow's nightly if you want to update on the device itself (development channel). They're usually finished around 6:30 AM CET.

**Comment by anarcat** [comment]
i tested applying the patch by hand and was able to download articles, this works thanks! :)
