### ISSUE TITLE
wallabag plugin shouldn't delete articles by default

### ISSUE THREAD

**Issue by anarcat** [koreader/koreader#8936]
* KOReader version: 2022.03
* Device: Kobo Aura

#### Issue

By default, a well-configured Wallabag plugin will delete remote article when the reader has marked it as "finished". I think that's counter intuitive and dangerous: the file and the remote article will potentially then be deleted and lost forever.

Instead, the default should be to mark the remote article as read and, maybe, delete locally, but do not remotely delete by default unless explicitly opted in b y the user.

**Comment by Frenzie** [comment]
At a quick glance, presumably it would suffice to change this line.

https://github.com/koreader/koreader/blob/eeefc657cbfca22dff9c370b2884d63e20fd4c8f/plugins/wallabag.koplugin/main.lua#L50
