### ISSUE TITLE
PW4: Night Mode does not survive sleep

### ISSUE THREAD

**Issue by yparitcher** [koreader/koreader#8937]
* KOReader version: master
* Device: kindle PW4

Toggle NM on and sleep the device it will wake up with NM off.
Probably fallout from #8856
@NiLuJe

**Comment by yparitcher** [comment]
edit:
I am running a custom screensaver, when using koreaders screensaver, this is not an issue, but this probably happens then on SO devices (can't tes)

**Comment by NiLuJe** [comment]
You're indeed probably missing an `fbink_reinit`... somewhere (at worst, possibly right before that `fbink_set_fb_info` call ;)).

I wouldn't think this would affect SO devices, as pillow has no reason to send a `FBIOPUT_VSCREENINFO` at that point (or, well, ever, actually ^^)?

(And the checks are done inside the kernel, so individual private copies of the fb info are irrelevant).

**Comment by yparitcher** [comment]
> You're indeed probably missing an `fbink_reinit`... somewhere (at worst, possibly right before that `fbink_set_fb_info` call ;)).

Why would i need a reinit? `fbink_set_fb_info` does a `fbink_reinit` The screensaver works fine, and I am keeping the current greyscale so it should not affect koreader. 
The function in question:
https://github.com/yparitcher/kindle-zmanim/blob/f01e32534a9f0320bb691776d7e8ec5df01d77f3/src/kzman.c#L268-L282

> I wouldn't think this would affect SO devices, as pillow has no reason to send a `FBIOPUT_VSCREENINFO` at that point (or, well, ever, actually ^^)?

If one entered the SS while in landscape would pillow correct the rotation?

**Comment by yparitcher** [comment]
```C
	if (rota != KEEP_CURRENT_ROTATE) {
		int ret = fbink_reinit(fbfd, &configCT);
		ret = fbink_set_fb_info(fbfd, rota, KEEP_CURRENT_BITDEPTH, KEEP_CURRENT_GRAYSCALE, &configCT);
		if (ret) {syslog(LOG_INFO, "Error rotating: %d\n", ret);}
	}
```
I fixed it to do a `reinit` before `set_fb_info`. It works now but my screensaver is now in night mode :( 
time to work around this.

**Comment by yparitcher** [comment]
Btw, this might cause the ads on SO devices to be in night mode now. (not like it really matters)

**Comment by NiLuJe** [comment]
> 
> If one entered the SS while in landscape would pillow correct the rotation?

Given that we don't actually rotate the fb (ever), there's nothing to correct ;).

**Comment by NiLuJe** [comment]
> Btw, this might cause the ads on SO devices to be in night mode now. (not like it really matters)

Depending on how smart the SS module is, possibly (I... haven't checked how the stock OS does this, but it *should* behave in the exact same way ;)).

**Comment by NiLuJe** [comment]
@yparitcher: I've added grayscale tracking to `fbink_reinit` ;).
