### ISSUE TITLE
202203 flips the screen upside-down on Aura H2O

### ISSUE THREAD

**Issue by fradav** [koreader/koreader#8941]
* KOReader version: 202203
* Device: Kobo Aura H2O (N250)

#### Issue
screen is flipped upside-down

#### Steps to reproduce
just install 202203

**Comment by Frenzie** [comment]
Could you verify if it's the issue described in https://github.com/koreader/koreader/pull/8931? In that case it'll be fixed in a point release most likely tomorrow or the day after tomorrow, possibly this weekend.

**Comment by NiLuJe** [comment]
That is definitely one of the affected device ;o).
