### ISSUE TITLE
Wallabag: request errors occasionally result in deletion of all articles

### ISSUE THREAD

**Issue by lennonhill** [koreader/koreader#8949]
* KOReader version: 2022.03
* Device: Kobo forma

#### Issue
Occasionally synchronisation of my wallabag client causes all my articles to be deleted. I managed to reproduce this with logging enabled. My web server provides an oauth token when requested, but does not see the second request (presumably because of network issues).

##### `crash.log` (if applicable)

<details>
  <summary>crash.log</summary>

```
03/25/22-21:41:41 DEBUG Wallabag: URL      https://CENSORED/oauth/v2/token
03/25/22-21:41:41 DEBUG Wallabag: method   POST
03/25/22-21:41:44 DEBUG Wallabag: URL      https://CENSORED/api/entries.json?archive=0&page=1&perPage=500
03/25/22-21:41:44 DEBUG Wallabag: method   GET
03/25/22-21:42:04 DEBUG Wallabag: Server error:  host or service not provided, or not known
03/25/22-21:42:04 DEBUG Wallabag: couldn't get page # 1
03/25/22-21:42:04 DEBUG Wallabag: number of articles:  0
03/25/22-21:42:04 DEBUG Wallabag: articles IDs from server:  {}
03/25/22-21:42:04 DEBUG Wallabag: Deleting local file (deleted on server):  /mnt/onboard/wallabag//[w-id_538] CENSORED.epub
03/25/22-21:42:04 DEBUG Wallabag: Deleting local file (deleted on server):  /mnt/onboard/wallabag//[w-id_536] CENSORED.epub
03/25/22-21:42:04 DEBUG Wallabag: Deleting local file (deleted on server):  /mnt/onboard/wallabag//[w-id_535] CENSORED.epub
03/25/22-21:42:04 DEBUG Wallabag: Deleting local file (deleted on server):  /mnt/onboard/wallabag//[w-id_534] CENSORED.epub
```
</details>

**Comment by lennonhill** [comment]
https://github.com/koreader/koreader/blob/c9bfb74d2aa9d9cbdffbcc6cffc3f79ac5f1eec0/plugins/wallabag.koplugin/main.lua#L431-L437 treats this just as like a zero-entry reply. How would you go about this? The simplest approach would probably be to abort as soon as any of the requests fails, returning false to the caller. Error checking is already implemented there, but the empty table evaluates to true here: https://github.com/koreader/koreader/blob/c9bfb74d2aa9d9cbdffbcc6cffc3f79ac5f1eec0/plugins/wallabag.koplugin/main.lua#L670-L671

**Comment by Frenzie** [comment]
> How would you go about this?

Based on your snippets above, something like:

```lua
local articles_json, err = self:callAPI("GET", articles_url, nil, "", "", true) 

if not articles_json and err == "server error" then
    return
end
```

**Comment by lennonhill** [comment]
Thanks, I will give it another go in a few days (well before 2022.04).
