### ISSUE TITLE
Frontlight & warmth slider don't work (PocketBook Touch HD3)

### ISSUE THREAD

**Issue by Leganorm** [koreader/koreader#8955]
Device: PocketBook Touch HD3 (PB632) with firmware U632.6.5.1383 (latest)

Issues

- [KOReader 2022.03.1] : Frontlight & warmth slider don't work
- [KOReader 2022.03] : Frontlight can only be turned ON/OFF, warmth slider has no action
- [KOReader 2022.02.] : Frontlight & warmth slider works OK (no issue)

Maybe related to recent Kobo frontlight warmth slider issue

Thank you

**Comment by NiLuJe** [comment]
Define "don't work" and ;).

Soleone with an affected device will have to double-check my shenanigans.

Debug logs might be helpful to see what values are actually passed to setWarmth, too.

**Comment by Leganorm** [comment]
It now works!!!
 
The problems I had are  maybe related to the upgrade of the PB632 firmware directly followed by the KOReader 2022.03 upgrade. Here is the sequence of what I did : 

- upgrade of PB632 firmware
- upgrade of KOReader to 2022.03 -> Frontlight (white & red) ok, the 'Warmth' slider does not work
- downgrade to KOReader 2022.02 -> everything works fine
- upgrade to KOReader 2022.03.1 -> white frontlight ok, red frontlight (Warmth) stays off
- downgrade to KOReader 2022.02 -> everything works fine again
- test of the Pocketbook reader to see what's new
- upgrade to KOReader 2022.03.1 -> everything works fine now...
I often use the 'Night mode' and almost never the native PB readers because of the lack of 'Night mode' and the bad dictionnaries support.

Thanks for your prompt reply.

**Comment by uvok** [comment]
Maybe this will help others:

I actually did a fresh install of KOReader 2023.08 on my PocketBook HD3, and I adjusting the warmth in the Frontlight settings dialog didn't do anything.

Then I switched to the "regular" PocketBook reader, disabled SmartLight-Auto there, and suddenly I was also able to adjust the warmth in the KOReader settings as well.

So yeah, kinda a usage error. I didn't fully read the docs yet, so maybe it's mentioned somewhere else, but would it make sense to mention this on the PocketBook installation page in the wiki?

**Comment by Frenzie** [comment]
Pinging @offset-torque

**Comment by offset-torque** [comment]
**QUESTIONS:**
- Is this procedure valid for all PocketBook devices or only some models/firmwares.
- Is this sentence clear enough for a PocketBook user or does it need some menu paths and/or more detailed instructions: 
**"If you have a PocketBook device, in order to be able to control your frontlight/warmth in KOReader, you should disable the SmartLight feature in your regular PocketBook reader settings."**
