### ISSUE TITLE
Font not applied

### ISSUE THREAD

**Issue by Raif1** [koreader/koreader#8965]
* KOReader version:Version v2022.03.1 (9017) fdroid
* Device:phh

#### Issue

Font not applied often 
![Screenshot_20220404-112632_KOReader.png](https://user-images.githubusercontent.com/93464125/161479568-779eddea-0b9f-400f-85b6-e54a19a0158c.png)

#### Steps to reproduce

Apply a font

**Comment by Raif1** [comment]
Some files get applied and some dont

**Comment by Frenzie** [comment]
If you go to style tweaks you can ignore publisher fonts.

**Comment by Raif1** [comment]
> If you go to style tweaks you can ignore publisher fonts.

Ohk thank you
