### ISSUE TITLE
FR:  Text Reflow convert ttb-rtl CJK text IN IMAGES to ltr-ttb, or vise versa.

### ISSUE THREAD

**Issue by Schezuk** [koreader/koreader#8969]
As some people may not be accustomed to TTB-RTL text in mainland China, or LTR-TTB text in other regions, it may be convient to Text Reflow from one way to another. E.g.
![image](https://user-images.githubusercontent.com/7524886/161695388-042d343f-d627-4da6-aab4-34962aaafe4a.png)
By text reflowing it does not only mean to arrange text elements, which may be easily done by many other softwares, but to re-arrange text in scanned images.

**Comment by Schezuk** [comment]
@Frenzie By *UPSTREAM* you mean I should post the issue to some other repository, say K2pdfopt?

It may be solved like this. Just rotate every square characters detected 90 degree clockwise/counter-clockwise, and leave other characters be. See
https://github.com/koreader/koreader/issues/4353#issuecomment-561681468

**Comment by Frenzie** [comment]
Something like that, yes. See <https://www.mobileread.com/forums/showthread.php?t=144711>.

**Comment by Schezuk** [comment]
> Something like that, yes. See https://www.mobileread.com/forums/showthread.php?t=144711.

The author of K2pdfopt told me to ask of Koreader developers.

**Comment by Frenzie** [comment]
Either k2pdfopt can do it and there's currently no interface for it in KOReader or it's completely impossible. Those are the only two options. ;-)
