### ISSUE TITLE
Cant look up dictionaries though having dict in dict settings

### ISSUE THREAD

**Issue by phongphuvn1997** [koreader/koreader#8975]
* KOReader version:2022.03.01
* Device: Kobo libra H20

#### Issue
when i look up, it dont see any dict installed through i installed many dict into device.
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
![image](https://user-images.githubusercontent.com/30289613/162012902-1b126a13-2dba-4251-b340-ff838e09da6f.png)
```
</details>

**Comment by phongphuvn1997** [comment]
i copied the sdcv file from another issue but it not work

**Comment by Frenzie** [comment]
The process is described in more detail on https://github.com/koreader/koreader/wiki/Dictionary-support

**Comment by phongphuvn1997** [comment]
So, i need to do add full path to  defaults.persistent.lu.   how about the
sdcv file? i copied the star dict to  .adds/koreader/data/dict/   then i
see these in dict settings but i cant look up dict in epub file.
Could you help me check it?

Tks bro

Vào Th 4, 6 thg 4, 2022 vào lúc 22:43 Frans de Jonge <
***@***.***> đã viết:

**Comment by Frenzie** [comment]
> So, i need to do add full path to  defaults.persistent.lu.

Only if you don't want to use `.adds/koreader/data/dict/`.

> then i
see these in dict settings but i cant look up dict in epub file.
Could you help me check it?

Have you tried what happens if you manually type a word into dictionary search?

**Comment by phongphuvn1997** [comment]
Yes i tried. The result is same with looking up while reading book

**Comment by phongphuvn1997** [comment]
Yes,  i extracted the complete file. i used to look up dict successfully
on last week before i updated koreader or firmware kobo...

Vào Th 5, 7 thg 4, 2022 vào lúc 20:14 Frans de Jonge <
***@***.***> đã viết:

**Comment by poire-z** [comment]
Any news ?
Closing as probably user side messup, and not a general issue.

**Comment by phongphuvn1997** [comment]
Yes, im sure that i extract all. I used dict successfully on last week
