### ISSUE TITLE
WebDAV not work anymore (v2022.03.01)

### ISSUE THREAD

**Issue by pihokkerr** [koreader/koreader#8979]
Hi! I have a problem with WebDAV. In previous version of KOReader I was able to connect to my NAS through WebDAV, but after the update (v2022.03.01) it doesn't work anymore. I didn't get any error or crash, it just do nothing when I click on it. 

Kindle PaperWhite 4 (PW4)
Firmware version of 5.10.1.3.
KOReader version: v2022.03.1

What could be the problem?

Thanks for your help!

**Comment by Frenzie** [comment]
The last change there was back in 2021. Do you happen to know which version you were using previously? 

https://github.com/koreader/koreader/blob/27bf5b59dd980c19439c023356fd039a788c5375/frontend/apps/cloudstorage/webdavapi.lua

**Comment by pihokkerr** [comment]
I am sorry it was a false alarm, I noticed, that I updated the firmware of the rooter at the same day, which mixed my settings up.
