### ISSUE TITLE
Incorrect order of extracted highlights

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#8982]
@hius07 , @Frenzie , @poire-z 
I thought that this issue had been resolved, but I noticed that it hasn't.
I give you (unfortunately for you in Greek) a page containing highlights and their view in the extracted file.
The order of the extracted highlights is the reverse of the order in the book.

![Reader_2022-04-09_140248](https://user-images.githubusercontent.com/76203123/162574371-f8ff231c-f618-4f4c-8e4b-b6e54630cd8d.jpg)
![Reader_2022-04-09_140533](https://user-images.githubusercontent.com/76203123/162574374-23ab1430-8bfc-4e86-8cba-be9d2a17251e.jpg)

_Originally posted by @ichnilatis-gr in https://github.com/koreader/koreader/issues/8601#issuecomment-1093984191_

**Comment by uroybd** [comment]
This is due to the fact that export entries are being sorted by timestamp instead of the location.

**Comment by uroybd** [comment]
@pazos This can be fixed only with two lines of edit. on `ipair` -> `pair` and commenting a sort. Should I do that in #8944 ?

**Comment by pazos** [comment]
@uroybd: please don't.

**Comment by poire-z** [comment]
@ichnilatis-gr : can you confirm they are in the correct order in the "bookmarks" view in KOReader? That's what #8616 was fixing.
There may be an additional issue in the "export plugin" - and if it's really a pairs/ipairs technical issue, this is the obvious fix of using ipairs, and it should and will be fixed (the "please don't" is just about organisation of fixes and enhancements, and not mix everything. We're not ignoring your report :)

**Comment by ichnilatis-gr** [comment]
> @ichnilatis-gr : can you confirm they are in the correct order in the "bookmarks" view in KOReader?

Here is the bookmarks list sorted by largest page number.

![Reader_2022-04-12_033122](https://user-images.githubusercontent.com/76203123/162937559-099d2fcb-39f2-4533-a29a-ec5abbca8ee7.jpg)

**Comment by poire-z** [comment]
Solved by #9021.
