### ISSUE TITLE
FR: Markdown Formatting in Joplin Export

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#8989]
Joplin is predominantly a markdown notetaking app. We can format exported notes nicely to leverage this. Once #8944 is done, we can do this. I would like to work on this.

The general document structure will be like this: 

```markdown
# Book Title
#### Author(s)

## Chapter
### Time: entry 1 time...
highlight content
---
comment
### Time: entry 2 time...
highlight content 2
```

Additionally, I want to introduce some settings to allow users finer formatting:
```lua
{
  -- other settings
  formatting = {
    enabled = true, -- to enable highlight style formatting
    -- available options for following settings will be: underline, italic, bold, strikethrough, bold-italic
    underline = "underline",
    lighten = "italic",
    invert = "bold",
   strikethrough = "strikethrough",
  }
}
```

By enabling formatting users can get formatted content according to the highlight styles they used in the book. Else they will get formatted content only as shown in the example above.

**Comment by pazos** [comment]
Sure. Looks like a good idea :+1:

**Comment by uroybd** [comment]
> Sure. Looks like a good idea :+1: 

I also want to create a markdown export with similar formatting options.

I can take one of two ways:

1. Repeat same settings in both Joplin and Markdown export.
2. Keep the formatting settings in the markdown exporter and add an option to joplin plugin like "enable markdown exporter formatting".

Which one would you prefer?

**Comment by pazos** [comment]
@uroybd:

I would prefeer a 3rd one:

Make a PR with the markdown exporter.
Once merged lets refactor stuff to move the Joplin exporter to markdown (following the exact same rules, no options)

Right now all targets are standalone (each one has its own pipeline) but that isn't a hard requirement. It could be the case when one format act as a parent for different targets. Sadly I cannot tell what's the best way to do it without looking at the md exporter first.

**Comment by uroybd** [comment]
> @uroybd:
> 
> I would prefeer a 3rd one:
> 
> Make a PR with the markdown exporter.
> Once merged lets refactor stuff to move the Joplin exporter to markdown (following the exact same rules, no options)
> 
> Right now all targets are standalone (each one has its own pipeline) but that isn't a hard requirement. It could be the case when one format act as a parent for different targets. Sadly I cannot tell what's the best way to do it without looking at the md exporter first.


Cool! A PR with markdown export is on its way!

**Comment by pazos** [comment]
Done by @uroybd in https://github.com/koreader/koreader/pull/9076
