### ISSUE TITLE
FR: Profile Support in Joplin Export

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#8990]
Unless one is using KOReader in the same device where the Joplin Desktop is running, copying/inputting the Joplin token, IP, and Port are cumbersome. A user with multiple devices using Joplin might have to switch between them often.

Therefore, I propose to add a Profile system in Joplin export. Users can switch between profiles and export to them in a few taps.

**Comment by pazos** [comment]
Not at the moment.

There's a lot of stuff than can be improved before adding more steps to an already painful process:

- reword plugin "help" info.
- update wiki with detailed info about how to setup joplin on the server, forward ports and enable the web clipper.
- add a notice to how unsecure and hackish this method is, no https: notes are sent unencrypted on your LAN.

>  A user with multiple devices using Joplin might have to switch between them often.

I don't think a lot of users are going to setup **more than one** computer to forward the web clipper listening port outside localhost. Honestly looks like a very bad idea.

Joplin has ways to sync content once it reaches its infrastructure. That's the point: setup a server, sync to it, let joplin do its magic and forward the same notes to all linked devices.
