### ISSUE TITLE
Config: any way to disable `GotoPercent` keybindings on Linux?

### ISSUE THREAD

**Issue by d3vr** [koreader/koreader#8992]
- KOReader version: [v2022.03](https://github.com/koreader/koreader/releases/tag/v2022.03)
- Device: GNU/Linux Desktop

Hello,

Is there any way I can disable the numeric keybindings for the `GotoPercent` Event on the linux desktop app?

**Edit**: The reason I ask is that I'm using the `i3` tiling window manager, and the `Mod+number` keybindings switch between workspaces. So each time I switch between the Koreader workspace and the browser workspace for example, Koreader goes to 100% (I usually have it on Workspace 0).

Thank you.

**Comment by poire-z** [comment]
No solution from KOReader itself, you'd have to edit and comment out the related bits in readerpaging/readerrolling.
But shouldn't your window manager consume these events - and not let them propagate to the app in the target workspace that has the focus? Don't you get the number printed in a terminal/text editor if it is it that has the focus?

Or may be you can "kill" all the number keys with an `event_map.lua` that would map them to some other unused keycode ? https://github.com/koreader/koreader/wiki/Keymapping

**Comment by d3vr** [comment]
> But shouldn't your window manager consume these events - and not let them propagate to the app in the target workspace that has the focus? Don't you get the number printed in a terminal/text editor if it is it that has the focus?

That should be the case, I tested with other apps and terminal apps. And even with `xev -event keyboard`. It's not capturing key presses when I'm switching back and forth between its workspace. So I'm not quite sure how is KOReader able to capture the keys 🤔.

> Or may be you can "kill" all the number keys with an event_map.lua that would map them to some other unused keycode ? https://github.com/koreader/koreader/wiki/Keymapping

Thank you for your help, I wasn't aware of this 🙏
This is what I ended up doing. For anyone from the future having the same issue, here's my `~/.config/koreader/settings/event_map.lua`:
```lua
return {
	-- Default keybindings in frontend/device/sdl/event_map_sdl2.lua

	-- Disable numeric keybindings
	[48] = " ", [49] = " ", [50] = " ", [51] = " ", [52] = " ",
	[53] = " ", [54] = " ", [55] = " ", [56] = " ", [57] = " ",
}
```
