### ISSUE TITLE
Android text rendering issue since latest update 

### ISSUE THREAD

**Issue by eldritchgreene** [koreader/koreader#8995]
Hi I use KOReader every day on two different Android e-ink devices. Two days ago I updated one of my devices to v2022.03.1 and noticed that the last text line in EPUB files is now constantly cropped at the bottom. This is an issue that was not present before the update. I tried disabling styles, adjusting margins, changing the status bar settings and it's still there.  It's also not present at all in my other device running v2022.02. I have avoided updating that device because of this, but if needed to check if it replicates there too I can do so.

![koreader](https://user-images.githubusercontent.com/37325367/162787816-b25bb277-eabc-4882-bfd7-cc464e457583.png)

Here is the info for bug report (there is no crash log file for this issue)
Version: v2022.03.1
Detected Device: sp9832e_1h10_oversea
OS: Android Oreo, api 27
Build flavor: rocks

**Comment by poire-z** [comment]
Should be fixed in current nightlies / dev channel updates.
See around and links in https://github.com/koreader/koreader/pull/8916#issuecomment-1090728098

**Comment by poire-z** [comment]
Assuming it is fixed by #8972.
