### ISSUE TITLE
FR: Need to search my book collection by custom metadata set by callibre

### ISSUE THREAD

**Issue by sobkas** [koreader/koreader#9000]
**Does your feature request involve difficulty completing a task? Please describe.**
Searching for books works in my Kobo reader under Collections, using my custom metadata set by callibre. But under KOReader I can't find a place to do that. Under Callibre Metadata Search I can only search by tags, but I can't access Custom Metadata from there.

**Describe the solution you'd like**
I want to be able search books by my custom metadata from callibre.

**Describe alternatives you've considered**
I don't have any idea what I could do to be able to search by custom metadata other than add support for it in KOReader.

**Additional context**
I'm willing to help with this feature and I have sponsored KOReader.

**Comment by NiLuJe** [comment]
The fact that custom metadata can take pretty much any form (in terms of data type and content) that calibre supports, this is easier said than done ;).

We've vaguely discussed it in the past (IIRC), and (again, IIRC), doing that would require telling KOReader excacty how a specific tag is formatted, which severely hampers the functionality.

**Comment by NiLuJe** [comment]
So, better question: which kind of custom metadata are *you* actually concerned with?

**Comment by sobkas** [comment]
I think it's:
    "user_metadata": {
      "#myshelves": {
        "#extra#": null,
        "datatype": "text",
        "name": "My Shelves",
        "rec_index": 22,
        "column": "value",
        "is_csp": false,
        "#value#": [
          "empik",
          "sf"
        ],
        "category_sort": "value",
        "link_column": "value",
        "label": "myshelves",
        "is_multiple": "|",
        "search_terms": [
          "#myshelves"
        ],
        "is_category": true,
        "colnum": 1,
        "kind": "field",
        "is_custom": true,
        "is_editable": true,
        "display": {
          "is_names": false,
          "description": ""
        },
        "table": "custom_column_1",
        "is_multiple2": {
          "list_to_ui": ", ",
          "cache_to_list": "|",
          "ui_to_list": ","
        }
      }
    Is it good enough? I have copied it from my my eReader.

**Comment by NiLuJe** [comment]
Well, there's actually *some* kind of metadata, I thought this was buried somewhere else, my bad ;p.

Still much less trivial to deal with than standard data ;).
