### ISSUE TITLE
PocketBook Touch HD 3 (PB632) Wi-Fi issue

### ISSUE THREAD

**Issue by dmpop** [koreader/koreader#9003]
* KOReader version: 2022.3.1
* Device: PocketBook Touch HD 3 (PB632)

#### Issue

Wi-Fi (somewhat) works:

- Cold start or reboot PB and do not put to sleep or close the cover.
- Launch KOReader.

Wi-Fi works, but gets disabled after a minute or two. So all actions requiring an internet connection prompt (for example, translation) to activate Wi-Fi.

Wi-Fi doesn't work:

- Cold start or reboot PB.
- Put the device to sleep.
- Launch KOReader.
- Wi-Fi will be disabled.
- Choose any action that requires internet access. Press **Activate** when prompted. The action times out after a minute or two.

May or may not be related to https://github.com/koreader/koreader/issues/3458

**Comment by peterrus** [comment]
Related to https://github.com/koreader/koreader/issues/6597 ?

**Comment by rjd22** [comment]
PocketBook wifi is aggressively killed by PocketBook itself to conserve power. I still need to make some time to take a look at this because this is imo the most annoying issue right now.

**Comment by rjd22** [comment]
This should be fixed now. Wifi will be kept alive until you decide to disable it yourself now.
