### ISSUE TITLE
FR: Control KOReader with the physical buttons

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#9006]
**Does your feature request involve difficulty completing a task? Please describe.**
I find myself using the home menu and library of my ereader more than KOReader's offerings, because it's easier to navigate them with the physical buttons on my ereader - one tap to go home (history) and a hold to go to the library. But recently I noticed that KOReader's library is better in some ways, and it would be nice to access it with the buttons.

**Describe the solution you'd like**
A buttom manager that could take advantage of the device's buttons to control KOReader, similar to the gesture manager.

**Describe alternatives you've considered**
An alternative would be changing the lua files manually, but that'd be too difficult in some cases.

**Comment by NiLuJe** [comment]
Which device would that be? ;o)

**Comment by Danar435** [comment]
I myself have a PB970, but I was thinking about most if not all devices with physical buttons.

**Comment by NiLuJe** [comment]
https://github.com/koreader/koreader/wiki/Keymapping ?

**Comment by pazos** [comment]
Yup, use keymappings. Setup once per device and have fun.
