### ISSUE TITLE
two Android packages in F-Droid

### ISSUE THREAD

**Issue by newsgrep** [koreader/koreader#9022]
#### Issue
There are two KOReader packages in the Android repro. Looks like a naming issue to me. Please remove one of them. 

I was not able to figure out a way to contact the maintainer of the KOReader F-Droid package so that is the reason I post here. 

#### Steps to reproduce
Look into:
current:
[https://f-droid.org/de/packages/org.**koreader.launcher.fdroid**/](https://f-droid.org/de/packages/org.koreader.launcher.fdroid/) 

v2021.05 (8302):
[https://f-droid.org/de/packages/org.**koreader.launcher**/](https://f-droid.org/de/packages/org.koreader.launcher/)

**Comment by pazos** [comment]
Related: https://github.com/koreader/koreader/discussions/8651#discussioncomment-1954612

I don't think there's a single package maintainer in Fdroid. Pinging here people who helped us with F-droid MR before: @Rudloff, @linsui, @IzzySoft

Could somebody archive the old `org.koreader.launcher` package?

**Comment by pazos** [comment]
Thanks! Done
