### ISSUE TITLE
FR: enhance battery item in statusbar with "Compact Items" prefix

### ISSUE THREAD

**Issue by molivier-fcms** [koreader/koreader#9023]
Hi,

Among the informations I want in the bottom statusbar, there is the battery status. To keep the bar smallest as possible, I use `Compact items` prefix.

Unfortunately this way battery is shown by a icon only, which is unaccurate.  (See the last item:)

![01-default](https://user-images.githubusercontent.com/39309715/164426425-37db8b40-bf7e-4af7-9de7-990d90b3da10.jpg)

My Kobo Glo is old, and I know that around 20% ~ 15% the battery goes low very quickly. So I would like to push a PR that display the percentage as well.

I could either use the current icon:
(charging)
![03-logo-charging](https://user-images.githubusercontent.com/39309715/164427835-76618447-35a1-4774-b95a-77132271297b.jpg)

(normal)
![04-logo](https://user-images.githubusercontent.com/39309715/164427919-dbfd2e6b-8732-404e-9dc3-3b1d1c05aedc.jpg)

Or using the `B` letter (with a `+` if battery is charging) :
![02-letter](https://user-images.githubusercontent.com/39309715/164428067-54a0f817-e337-4cee-bc7c-351c186e1584.jpg)

First, do you like this idea?
Then which version would you like to have?

**Comment by NiLuJe** [comment]
None of them, to be honest ;).

But you might be interested in the "hide battery icon" threshold setting?

**Comment by molivier-fcms** [comment]
I get the idea. Then I know when the battery load is below specified level.

However, it can be useful to keep an eye on the battery level. As its name suggests, the prefix should define the style of "icon prefix" of an item, not slashing the information away.

**Comment by NiLuJe** [comment]
To expand a bit, if you choose icon prefixes, I'd expect us to show icon prefixes.

If you don't *like* icon prefixes, use letter prefixes ;o).

**Comment by molivier-fcms** [comment]
Fair enough. I'm a bit disappointed, but I understand the underlying logic.
I'll stick to existing solutions (threshold or letter prefixes).

**Comment by NiLuJe** [comment]
Fair warning: I'm, err, not a fan of the compact feature (like, at all). So I'm not really the best person to ask about it, because my first reflex will always to be "burn it. burn it with fire" ;o).
