### ISSUE TITLE
FR: [Add more highlight color options]

### ISSUE THREAD

**Issue by krillin666** [koreader/koreader#9024]
**Does your feature request involve difficulty completing a task? Please describe.**
I use my Kobo to review a lot of academic papers, as such I rely heavily on highlights to retain the content I've read. However, my workflow involves different types of highlight's colour (yellow, green, red, purple). This is because I use Zotero as my ref manager and use this  [script](https://github.com/stefanopagliari/bibnotes) to automatically add comments/tasks to my highlights based on the colour of the highlight.

**Describe the solution you'd like**
It would be fruitful if Koreader added the ability to select highlight colour (even in B/W e-ink reader). With this, we could review the PDFs in other devices without being limited to the rather dull gray highlight, which is the default highlight colour that KOreader adds to pdfs.

**Describe alternatives you've considered**
I could manually add a comment to each highlight with the colour I wanted it to be and then on PC check all highlights and convert them to the colour mentioned in the note of that highlight. But, that would be obviously tedious and labour.

**Additional context**
I've mentioned a specific workflow with Zotero, nevertheless I'm sure many people use highlights of different colour in their workflow. So please comment below if you also find this useful !

**Comment by kauesena** [comment]
My case is slightly different but would also benefit from different colours for highlights. With different colours, I can distinguish between categories of highlighted passages: excerpts I did not understand, definitions, nice phrases, words I did not know, key quotes, etc.

**Comment by mergen3107** [comment]
Sounds similar along the lines of this I think: https://github.com/koreader/koreader/issues/7756 
@kauesena see if some suggestions in the OP might work for you, at least after extraction of notes

**Comment by kauesena** [comment]
@mergen3107 thank you for mentioning that issue. How do you add the labels to the highlights? You add them simply as notes?  Your use case and mine are essentially the same (though the categories would differ, naturally). 

I think another useful thing if colours are difficult to do be implemented, would be creating other highlighting styles such as dashed underline, wobbly underline,  box-like highlighting, etc. Perhaps I should submit a separate issue for this.

**Comment by mergen3107** [comment]
@kauesena 
Yes, these are just words I put manually before highlight "categories".

**Comment by mergen3107** [comment]
@kauesena 
Currently, there are four highlight modes in KOReader: highlight, underline, invert, strikeout. Moreover, you can now indicate whether this is not just a highlight, but also a note. 

Does this work with your script-based workflow now?

**Comment by poire-z** [comment]
Our UI code doesn't support colors, everything uses gray. I once wished we could have colors for the calendar view, https://github.com/koreader/koreader/pull/5854#issuecomment-585216764 - but it would be a pain to update all the blitting code to support colors for the very few places we may actually use it (calendar, highlights), and the very few color devices as most ones are Black and White.
Only our engines (mupdf, crengine) page drawing code, which is C code in libraries, can do it - so we get it for book content on color Pocketbooks and Android.

**Comment by yosoyyognu** [comment]
I use boox ultra C and i bought it because of colors. I would be very happy if you add colors to the highlights!

Regards

**Comment by poire-z** [comment]
We can't have colors in the UI without some really extensive rework :/
We got to have colors in document pages more easily.
But highlights are drawn over the document pages by the UI code.

**Comment by Galunid** [comment]
I played around with this for a bit and had some initial success.

![image](https://github.com/koreader/koreader/assets/10298730/7a5a47a8-2eda-424d-8887-1bf16d969410)

Simple idea was to create `paintColorRect` in `ffi/blitbuffer.lua` and `BB_fill_rect_color` in `blitbuffer.c`. We could have `paintRect` that calls `paintGrayscaleRect` (current implementation) and `paintColorRect` (which would be new implementation). @poire-z Would we be fine with this?

**Comment by poire-z** [comment]
> @poire-z Would we be fine with this?

I'm not the authority on this :) @NiLuJe is.

(The risk is that if we start doing color, we'll want colored text, color hatching... and everything will be duplicated - and in frontend, we'll have to have code paths for color devices, to disable for gray devices - ie. the list of type of highlight will be 4 items for gray devices, but could get 32 items for colors, and the need to have a scrollable container, etc... - and most people, devs & users, won't test and care.)

**Comment by NiLuJe** [comment]
I'd have to see it to judge, but, yeaaaah, I'm also not necessarily enthused about it ;p.

**Comment by smasher816** [comment]
@Galunid would you mind sharing the diff?

**Comment by Galunid** [comment]
@smasher816 Sure
[base.txt](https://github.com/koreader/koreader/files/13164711/base.txt)
[frontend.txt](https://github.com/koreader/koreader/files/13164712/frontend.txt)

Change extension from `.txt` to `.diff`. Github wouldn't let me upload them otherwise. It's just a hacked solution that may break on other devices (it works on emulator)

**Comment by smasher816** [comment]
Thanks Galunid. I took your base and tried polishing it up a bit.

Here is a video showing it off in action on an Onyx Tab Mini C.
https://github.com/koreader/koreader/assets/904012/531f5e86-27a8-4f56-94c3-58fe24054887

Here is a MR with my changes.
https://github.com/koreader/koreader/pull/11044/files
https://github.com/koreader/koreader-base/pull/1680/files

Current implementation now uses a `is_rgb` flag attached to each color type. This lets us keep a single paintRect lua function, that calls into the correct underlying Cbb function depending on if we are passing in an rgb color or not.
For devices without 32bit support or using the legacy lua blitting, no changes occur.

The frontend highlight code will respect the "Use color" setting from the Screen settings menu. If disabled a B&W color is passed in (as before) and if enabled then a ColorRGB32 is passed in causing the new paths to be called.

Additionally, a "Highlight color" option (with translations) was added next to the current opacity option in the settings menu. This provides a few preset values, similar to the kindle app or the native drawing app.

I think the above function shows off the features of koreader on a color e-ink tablet without adding too much feature creep, and without duplicating many functions/code.

**Comment by smasher816** [comment]
Here is a quick photo for those that don't want a video.
![PXL_20231026_170917059](https://github.com/koreader/koreader/assets/904012/d07274a3-4ccf-4547-bd7d-38ff8b980aa1)

I haven't bothered trying to do "different colors per highlight" since it's not personally something I use.
If the above MR's laying the foundation get through, then maybe someone else could work on it in the future.

**Comment by smasher816** [comment]
Individual colors actually wasn't too difficult to accomplish. Thanks @hius07 for the pointer on how "per highlight" styles were saved.
I'll continue to work on getting the MR pushed through.

![PXL_20231028_041158819](https://github.com/koreader/koreader/assets/904012/e023ece6-0be7-483a-b61d-e640cce6dd31)

**Comment by uroybd** [comment]
This is nice. More context to organize one's highlights.

**Comment by Bluemoondragon07** [comment]
How can I generate the apk with these modifications to test on Android?

**Comment by Galunid** [comment]
1. Clone the repo
2. Pull the changes from relevant PRs (https://github.com/koreader/koreader/pull/11044, https://github.com/koreader/koreader-base/pull/1680), see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
3. Follow instructions under https://github.com/koreader/koreader#development

If you are just interested in the app, here it is https://gofile.io/d/u5C5je. It's signed with my key, so you'll have to uninstall KOReader first. It's build directly from the PRs linked, so it won't have changes after November 2023.

**Comment by Bluemoondragon07** [comment]
@Galunid Thank you! Unfortunately, the app linked could not install on my Android 11 Meebook, Android 11 Bigme, or Android 12 Samsung. It crashed when I tried it with on Windows with Bluestacks.

But, I cloned the KOreader repo. Not sure what to do about the KOreader-base modifications, but I'm getting there. Thanks for the direction!

**Comment by Galunid** [comment]
@Bluemoondragon07 Sorry about that. I messed up signing the apk and it doesn't work with android 11+. This one works (at least on my Android 12 device). https://gofile.io/d/GTfm79
Let me know if you need other architectures than the arm.

**Comment by Bluemoondragon07** [comment]
Thank you so much, @Galunid .

I  was able to install on the Bigme Inknote and test things out! I feel so privileged. 

Some minor drawbacks like the color making the note underline invisible, highlight transparency being made void, and other things, but wow--this is a massively helpful implementation. Thanks!

Now I'm gonna try to generate an up-to-date apk with the functions.

**Comment by NiLuJe** [comment]
> Now I'm gonna try to generate an up-to-date apk with the functions.

Don't, this is next on my TODO list after https://github.com/koreader/koreader-base/issues/1729

Your time will be better spent actually testing how it looks like & feels, as I have zero interest in this myself besides merging the PR ;).

**Comment by Bluemoondragon07** [comment]
Ah, okay. Couldn't get build_release.sh to work, anyways. On the other hand, I can definitely give feedback on your current version 👍🏽

**Comment by uroybd** [comment]
Any update on this?

**Comment by poire-z** [comment]
I think @NiLuJe is a bit busy, but may welcome some testing on his updates to the related koreader-base PR https://github.com/koreader/koreader-base/pull/1680.

**Comment by NiLuJe** [comment]
Yup, it was basically ready last I checked, I was just letting it sit before review (I may also have been waiting out a feature freeze at one point, can't recall).

But, sure, if you can test it on an actual device, go ahead, as I don't have the hardware ;).

**Comment by kauesena** [comment]
Is there an apk? I'd happily test it on my colour e-ink device (Boox Note Air 3 C).

**Comment by Aparikk** [comment]
I'd like to test it on my pocketbook inkpad color 3. Is there any way to do so atm?

**Comment by CobriMediaJulien** [comment]
has anybody news on this or can we help with testing e.g. on a inkpad color?

**Comment by NiLuJe** [comment]
I've just finished rebasing and reviewing this, so it should be coming Soon(TM).
