### ISSUE TITLE
FR: Allow export to joplin cloud

### ISSUE THREAD

**Issue by EncroachGradually** [koreader/koreader#9025]
**Does your feature request involve difficulty completing a task? Please describe.**
Joplin has released a service known as joplin cloud allowing it to sync notes between devices without both devices needing to be on at the same time, with the current joplin export you have to have both devices on the same network at the same time.

**Describe the solution you'd like**
Implementing joplin cloud support would make it so nopt only do both devices not need to be on at the same time but they don't need to be on the same network

**Comment by pazos** [comment]
It would be an separate option, not a replacement.

Sadly there're [no free plans](https://joplinapp.org/plans/), so motivation should come from a contributor that's already a member.

Patches welcome!

**Comment by uroybd** [comment]
Joplin Cloud doesn't have a public API at this momment. It's actually a sync server.

These are all the API's we can use: https://joplinapp.org/api/overview/

Plugin API is irrelevant in our case. That left us only with (Data API)[https://joplinapp.org/api/references/rest_api/] and it is being exposed by Joplin Desktop, not Cloud.
