### ISSUE TITLE
Chess symbols (unicode) render with wrong height

### ISSUE THREAD

**Issue by AshenColors** [koreader/koreader#9026]
* KOReader version: 2022.03.1-38
* Device: Kobo Clara HD

#### Issue

Unicode chess symbols, used for notation, are rendered too short/small compared to the font height they're in. This makes reading chess books very difficult without using an impractically large font size.

Additional background:
Unicode chess symbols are commonly used as a part of figurine algebraic notation in chess ebooks. These consist of the normal 12 symbols in the *Miscellaneous Symbols* block (2654-265F), and less commonly used pieces for variants in the *Chess Symbols* block (1FA00-1FA6F). Consider the last line of chess moves in the screenshot below, displaying a copy of "My First Chess Opening Repertoire for White": 

![Reader_2022-04-21_145808](https://user-images.githubusercontent.com/3249074/164533850-f7f866c9-c3ef-4479-9fe9-08ac6916e0e4.png)

The typographic standard, and probably how your browser renders it (14... ♖xh3+!! 15. gxh3 ♗f3#), is for each figurine to be as tall as the cap-height. The easiest comparison in height can be made with the rook, which in the screenshot is rendered incorrectly at x-height.

Temporary workarounds for affected users may include preprocessing to replace these symbols with their letter equivalents (what I'm doing) or possibly creating a user style tweak that edits symbol size, which I haven't managed to do.

#### Steps to reproduce
Any epub I've tried containing_ these chess symbols appears to be affected. For testing purposes, since I can't just ship off a copy of a copyrighted book, I've used calibre to create an abbreviated epub conversion from the original PDF of the CC BY-NC-SA 3.0-licensed classic "Winning with the Bongcloud" (2008). While not a 'serious' chess book, it loosely approximates the way figurine notation and lines or variants generally appear in chess books. It also demonstrates this bug. The file is attached to this report as [Winning with the Bongcloud (Abridged Figurine EPUB Edition)](https://github.com/koreader/koreader/files/8534335/Winning.with.the.Bongcloud.Abr.-.Andrew.Fabbro.andrew%40fabbro.or.epub.zip); simply load and observe.

##### `crash.log` (if applicable)
n/a

**Comment by poire-z** [comment]
We don't (and won't) do any specific char scaling/adaptation.
We trust the font(s) to have the glyphs (letters and symbols) correctly adjusted, which means as the font designer think things shoud look: it's his job to ensure _each figurine to be as tall as the cap-height_ or any such design standard/common sense.

In your case, I guess you are using a main font that does not have the chess symbols included - and KOReader goes picking the missing glyphs in a fallback font.
Our largest coverage font is FreeSerif, which is last, and is known to be a bit smaller than the other fonts. So it's possible your chess symbols come from it.
You might help yourself by trying other fonts and finding one that has chess symbols, and of right proportions - or even one you don't like for the main text, but with large chess symbols that you could use as the first fallback font, which will hopefully feel rightly sized vs your prefered main text font.

Just using FreeSerif, we see they are already small:
![image](https://user-images.githubusercontent.com/24273478/164537815-c9a1a8df-9e73-4669-8fb8-07cba1135c23.png)

With the ugly (but complete) Code2000 font, they are better sized:
![image](https://user-images.githubusercontent.com/24273478/164537714-7ec09fee-bfbb-4b04-92bb-8cbb068ec178.png)

With Unifont:
![image](https://user-images.githubusercontent.com/24273478/164538123-578c29b2-65fc-464c-af79-8a1e31fc8d57.png)

In a font named "Quivira":
![image](https://user-images.githubusercontent.com/24273478/164537992-b3395622-a7f8-44f9-a636-32dad0232af6.png)

And that's the only 4 fonts among the 90 I tried that have these symbols.
But I'm sure there are dedicated chess font, that you could just drop into your koreader/fonts/ dir and select it as the fallback font.
(I tried a few chess fonts found on the web, but they all seemed to map these symbols to classic ascii letter codes... none had them for the correct unicode codepoints used by your EPUB... but some correct font must exist :)

(Given the rarity of the presence of these symbols in classic fonts, I guess any publisher should ship inside the EPUB an embedded font with them, which would be used by KOReader.)

**Comment by AshenColors** [comment]
I thought it was a font thing at first too, but I used Noto Serif above (and tested it with Noto Sans) to try and specifically rule that out. Following up your comment, it turns out that the chess symbols 'in' Noto are *actually* in Noto Sans Symbols 2, which is why the fallback font is coming into use. Adding that font and then rendering in it breaks other text but it should be trivial to create a user style tweak to specify font priorities.

Thank you for your time and help in providing the final clue.

**Comment by poire-z** [comment]
Good.

> you can long-tap on a font and set it as fallback, which is the solution I used.

Yes, that's the way to do it (sorry, forgot to mention how to set a font as first fallback.)

> but it should be trivial to create a user style tweak to specify font priorities.

You couldn't solve this with style tweaks, unless each chess symbol is in its own `<span class="something">♖</span>`, in which case you could associate a font to this class name.
But as these symbols are in nearly no other font, with the fallback font, you don't need to tweak any style, KOReader will pick the symbols where it can.
