### ISSUE TITLE
Cloud Storage bug on Kindle 4NT

### ISSUE THREAD

**Issue by clrizzi** [koreader/koreader#9027]
* KOReader version: 2022.03.1
* Device: Kindle 4NT

#### Issue
The **Cloud Storage** option is empty when I access this menu on my Kindle 4NT. 

I should see the "**Add new Cloud Storage**" button (for use with Dropbox or FTP) but it doesn't. I checked inside the folder "\Koreader\frontend\apps\cloustorage" and all the ".lua" files are there (dropbox.lua; ftpapi.lua; dropboxapi.lua; ftp.lua; webdav.lua; cloudstorage.lua).

I compared these files with those on a newer device and they appear to be the same

Did I miss some configuration?

##### `crash.log` 

```
[crash.log](https://github.com/koreader/koreader/files/8535212/crash.log)

```
</details>

**Comment by NiLuJe** [comment]
In case that might be the issue: it's only available in the file manager, not the reader.

**Comment by clrizzi** [comment]
Even in the file manager I don't see any buttons. The page is completely empy...

**Comment by hius07** [comment]
Adding a storage is done via title left button but it is available for touch devices only.
Needs fixing.
As a temporary workaround: add a storage manually in koreader/settings/cloudstorage.lua.

**Comment by hius07** [comment]
https://github.com/koreader/koreader/blob/08d6fbc9db00dc77ab86da8d575b449008026ee3/frontend/ui/widget/titlebar.lua#L101-L113

Maybe @comphilip can help.

**Comment by hius07** [comment]
Format of koreader/settings/cloudstorage.lua:
```lua
-- we can read Lua syntax here!
return {
    ["cs_servers"] = {
        [1] = {
            ["name"] = "hius07@",
            ["password"] = "xxx",
            ["type"] = "dropbox",
            ["url"] = "/",
        },
        [2] = {
            ["address"] = "ftp://192.168.0.104",
            ["name"] = "ASUS media player hdd",
            ["password"] = "",
            ["type"] = "ftp",
            ["url"] = "/",
            ["username"] = "",
        },
        [3] = {
            ["address"] = "a",
            ["name"] = "Good library with free classic books",
            ["password"] = "",
            ["type"] = "webdav",
            ["url"] = "",
            ["username"] = "",
        },
    },
    ["download_dir"] = "/mnt/us/books/TestFolder",
}
```
For Dropbox token is a password.

**Comment by comphilip** [comment]
After quick search, there are 22 `TitleBar:new` calls. Need times to check everyone and regression test.

**Comment by clrizzi** [comment]
> Format of koreader/settings/cloudstorage.lua:
> 
> ```lua
> -- we can read Lua syntax here!
> return {
>     ["cs_servers"] = {
>         [1] = {
>             ["name"] = "hius07@",
>             ["password"] = "xxx",
>             ["type"] = "dropbox",
>             ["url"] = "/",
>         },
>         [2] = {
>             ["address"] = "ftp://192.168.0.104",
>             ["name"] = "ASUS media player hdd",
>             ["password"] = "",
>             ["type"] = "ftp",
>             ["url"] = "/",
>             ["username"] = "",
>         },
>         [3] = {
>             ["address"] = "a",
>             ["name"] = "Good library with free classic books",
>             ["password"] = "",
>             ["type"] = "webdav",
>             ["url"] = "",
>             ["username"] = "",
>         },
>     },
>     ["download_dir"] = "/mnt/us/books/TestFolder",
> }
> ```
> 
> For Dropbox token is a password.

Thanks, @hius07 this Works for me.

**Comment by clrizzi** [comment]
> After quick search, there are 22 `TitleBar:new` calls. Need times to check everyone and regression test.

Thanks, @comphilip !  I  appreciate your help!

**Comment by clrizzi** [comment]
I found some other bugs for this device. Do I keep reporting?

**Comment by comphilip** [comment]
@clrizzi You are welcomed.

**Comment by clrizzi** [comment]
Oh... After my previosly post, I found something that might be related: Issue #8571

**Comment by clrizzi** [comment]
Thanks, @comphilip ! So should i close this topic now?

**Comment by comphilip** [comment]
Keep it open. Once the PR is reviewed and merged, then you can download the nighty version, close it after your testing.
