### ISSUE TITLE
FR: Share link

### ISSUE THREAD

**Issue by ScootRay** [koreader/koreader#9029]
Hi,

Currently when I come across a link in a book or article I'm reading in Android version of KOReader, clicking on it brings up a dialog that includes COPY LINK.

I'm wondering if it is possible to put SHARE LINK and use Android's built in sharing system so I can share it to other apps, etc.

Thanks!
Ray

**Comment by ScootRay** [comment]
Hi,

Currently when I come across a link in a book or article I'm reading in Android version of KOReader, clicking on it brings up a dialog that includes COPY LINK.

I'm wondering if it is possible to put SHARE LINK and use Android's built in sharing system so I can share it to other apps, etc. 

Thanks!
Ray

**Comment by pazos** [comment]
> I'm wondering if it is possible to put SHARE LINK and use Android's built in sharing system so I can share it to other apps

You can share the link as plain text with:

```diff
diff --git a/frontend/apps/reader/modules/readerlink.lua b/frontend/apps/reader/modules/readerlink.lua
index 87625cba..11893903 100644
--- a/frontend/apps/reader/modules/readerlink.lua
+++ b/frontend/apps/reader/modules/readerlink.lua
@@ -714,6 +714,15 @@ function ReaderLink:onGoToExternalLink(link_url)
             end,
         })
     end
+    if Device:canShareText() then
+        table.insert(alt_handlers_buttons, {
+            text = _("Share link"),
+            callback = function()
+                UIManager:close(dialog)
+                Device:doShareText(link_url)
+            end,
+        })
+    end
 
     -- Check if it is a wikipedia link
     local wiki_lang, wiki_page = link_url:match([[https?://([^%.]+).wikipedia.org/wiki/([^/]+)]])
```

So if you click a link named [koreader](https://koreader.rocks) you're going to be prompted to share the text `https://koreader.rocks` with other apps that can handle plain text (how the text is handled it's up to the specific app you select)

The behaviour would match exactly the one you get if you highlight a sentence in a book and select "share text" in the menu.

Is this **exactly** what you want, @ScootRay?

**Comment by pazos** [comment]
No response. Closing
