### ISSUE TITLE
PocketBook Library Indexing Application Icons

### ISSUE THREAD

**Issue by PatrickNByrne** [koreader/koreader#9030]
* KOReader version: 2022.03.1
* Device: PocketBook Inkpad Color - PB741

#### Issue
The PocketBook library application indexes all books, text files, and images, which include the svg application icons from koreader. This fills the library with needless svg images and crash text files that would be better hidden. 

#### Steps to reproduce
Update PocketBook InkPad color (version U741.6.5.1684 - released 20220201) and install the latest release of koreader to the locations specified in the install instructions found in the wiki. Launch koreader and associate the filetypes as specified. Navigate to the PocketBook library to see the icons.

#### Workaround
This can be mitigated by simply hiding the koreader application directory at /mnt/ext1/applications/koreader and updating the launcher to point to the hidden directory. 

1. Move /mnt/ext1/applications/koreader to /mnt/ext1/applications/.koreader 
2. Edit /mnt/ext1/applications/koreader.app and change `KOREADER_DIR="/mnt/ext1/applications/koreader"` to `KOREADER_DIR="/mnt/ext1/applications/.koreader"`

#### Next Steps
This seems like a simple enough fix. I would be happy to submit a PR for this, but I'm not sure how changing the application directory would work with automatic updates. If someone could please point me to the update documentation, I would be happy to take a crack at this. 

Thanks!

**Comment by pazos** [comment]
> The PocketBook library application indexes all books, text files, and images, which include the svg application icons

The pocketbook library app indexes document mimetypes that have an app associated with them. KO users, following wiki in https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices are the ones that associate all sort of random formats (like svg) with koreader.

>  I would be happy to submit a PR for this

Please don't. Instead update the instructions at wiki. Instead of enabling all file associations users should enable **only** the ones that they want to open in KO.

**Comment by PatrickNByrne** [comment]
> The pocketbook library app indexes document mimetypes that have an app associated with them.
Thank you for pointing this out! I've tested that this works for svg and log files. This reduces the number of new items greatly.

**Comment by pazos** [comment]
Leave it opened until somebody updates the wiki

**Comment by PatrickNByrne** [comment]
Wiki updated: https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices
