### ISSUE TITLE
Kobo Libra 2 freezes when dictionary lookup

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#9038]
* KOReader version: 2022.03.1-41   (Firmware: 4.31.19086)
* Device: Kobo Libra 2

#### Issue
The second time I lookup a word my Libra 2 freezes. A restart is needed.

KA1 & Kobo Sage don't behave like this.

#### Steps to reproduce
Lookup a word. Lookup another from inside the dictionary (or close window and lookup another word). Freeze.

It happens both when I lookup word from a book or when using the dictionary from the menu or a gesture.

Ususally it only takes two lookups to freeze, but sometimes it takes three or four.

Verbose log: 
[crash.log](https://github.com/koreader/koreader/files/8570390/crash.log)

**Comment by NiLuJe** [comment]
On mobile, but xref with a similar report on MR.

Looks like the Libra 2 EPDC hangs, but may not have been as easily reproducible on 2022.03.1 (which... doesn't make much sense given the changes. FW 4.32 happening right at the same time does, though).

**Comment by NiLuJe** [comment]
Except you're on 4.31, so there goes my 4.32 theory ;p.

**Comment by poire-z** [comment]
Given how in the dark we are about these issues, and as you can reproduce it easily, can you try with past nightlies and find out the latest one were this does not happen at all, and the one where this happens easily ?

**Comment by gerhaher** [comment]
It's somewhere between 2022.03.1 and v2022.03.1-28.

Where do I find nightlies before v2022.03.1-28?
I'm just aware of this page https://build.koreader.rocks/download/nightly/

**Comment by gerhaher** [comment]
OK, according to my testing the issue was introduced with v2022.03.1-24

**Comment by poire-z** [comment]
So, bad with v2022.03.1-24-gbd17119d_2022-04-13.
But all ok with v2022.03.1-20-g658991ed_2022-04-11 ?

**Comment by gerhaher** [comment]
Correct.

**Comment by poire-z** [comment]
That makes it 4 commits by @NiLuJe: https://github.com/koreader/koreader/compare/658991ed...bd17119d0704c
which I'm not familiar at all with.
Can you confirm you don't have any autosomething.plugin enabled ? (or if you do, what if you disable them) ?

**Comment by poire-z** [comment]
Random questions (so @NiLuJe has some grain to grind):
- was the power button (assuming the Libra2 has one) also unresponsive when the device "felt" hung?
- does the Libra2 has a capacitive or IR screen ?

(
I've had my own auto power save for years on my GloHD, with IR screen - and sometimes I get the device hung - but the power button works, and enough to put the device into suspend, where I can wait 15s before hitting it again to resume - and I get back my IR layer.
I sometimes think it might be some race condition, for it to happen so rarely (once a week), so may be when I touch the screen while we are about to go into standby or we just are, vs. the way we handle/dequeue input events at this precise moment... or something with the time/TimeVal accounting... Hard to figure all that may be happening :)
)

**Comment by Frenzie** [comment]
Incidentally, I haven't been able to reproduce what I mentioned. But it's never happened to me before.

**Comment by gerhaher** [comment]
> was the power button (assuming the Libra2 has one) also unresponsive when the device "felt" hung?

I had to press the button a long time to stop the hung. Probably more than 5 seconds. 


> does the Libra2 has a capacitive or IR screen

It has a recessed screen, I suppose that means it is IR

**Comment by NiLuJe** [comment]
`Auto power save` is not actually a thing, so could we clarify what the option was, exactly? ;o).

**Comment by NiLuJe** [comment]
Incidentally, #9036 might magically fix it.

**Comment by NiLuJe** [comment]
I'll see if I can repro something on my slow ass H2O this WE.

Were those local dictionary lookups (and if so, how many dicts do you have and are there giant ones in there), or from-wifi-off Wikipedia lookups?

**Comment by NiLuJe** [comment]
> > was the power button (assuming the Libra2 has one) also unresponsive when the device "felt" hung?
> 
> I had to press the button a long time to stop the hung. Probably more than 5 seconds. So yes, unresponsive... a simple press to suspend the device didn't work for me.

A long-press on Power (> 2s) should send us straight to power-off (ourselves if we're alive, e.g., you see your screensaver/poweroff message; or straight to a power cut with no screen changes if held longer and it goes straight to the hardware).

**Comment by NiLuJe** [comment]
(The Libra 2 might be using an elan panel like the Sage/Elipsa, despite its recessed screen. You should be able to discriminate between the two by the presence (or absence) of the actual IR emitters (usually behind a black plastic shield al around the inner bezel)).

**Comment by poire-z** [comment]
> You should be able to discriminate between the two 

Or just touching the screen with a non-human thingy, plastic pen cap, glasses, wood leg: if it reacts, it's IR.

**Comment by gerhaher** [comment]
> Were those local dictionary lookups (and if so, how many dicts do you have and are there giant ones in there), or from-wifi-off Wikipedia lookups?

Local dictionaries. I have 7. 
No giant ones.

**Comment by gerhaher** [comment]
> > You should be able to discriminate between the two
> 
> Or just touching the screen with a non-human thingy, plastic pen cap, glasses, wood leg: if it reacts, it's IR.

Well, in that case it's probably not IR.

**Comment by gerhaher** [comment]
> A long-press on Power (> 2s) should send us straight to power-off (ourselves if we're alive, e.g., you see your screensaver/poweroff message; **or straight to a power cut with no screen changes if held longer** and it goes straight to the hardware).

The bold. That's what happened.

**Comment by NiLuJe** [comment]
Okay, I'd completely forgotten that the *plugin* itself was renamed `Auto power save`, my bad.

(I'm... not completely a fan, but I have yet to think of something better).

**Comment by NiLuJe** [comment]
Which leads me to a similar query as in this post: https://www.mobileread.com/forums/showpost.php?p=4217108&postcount=3432

If it still hangs, I'm hoping we'd be able to get something out of debug + verbose debug logs...

**Comment by NiLuJe** [comment]
Do try on current nightlies, though, as I basically broke things in fun and interesting ways between #8985 and #9009 ;).

**Comment by Frenzie** [comment]
I currently have 08d6fbc9 2022-04-19 (haven't had a chance to update yet) and I just had another lack of response on wakeup. (Sorry, can't provide any kind of debug info atm.)

**Comment by NiLuJe** [comment]
Okay, I had completely missed your logs ;o).

Yeah, there's an obvious snafu in that `AutoSuspend:onAllowStandby` is *always* there, and fails to check whether autostandby is always enabled.
Because Trapper (used by the dict lookup) does the UIManager:preventStandby -> allowStandby dance, that trips an AllowStandby event, which sends the device into standby.

Why that actually appears to randomly lockup on a Libra 2 is another kettle of fish, though (because it shouldn't) ;).

**Comment by NiLuJe** [comment]
(Fixed the software issue in #9036, the reason behind the Libra 2 kernel hangs shall remain a mystery, possibly related to #8414)
