### ISSUE TITLE
Brightness control not working from Gestures

### ISSUE THREAD

**Issue by oldman63** [koreader/koreader#9043]
KOReader version: 2022.03.1-37
Device: Kindle Paperwhite 5
Firmware version: 5.14.2

Problem: Brightness Control not working from gestures (manual from menu is working good)

Reproduction: adding this functions to Gesture Manager:

Gesture: Swipe Up (and Down)

**Screen and lights:**
* Set Frontlight brightness to 15 (7)
* Set Frontlight warmth to 0 (100)
* Set Night mode Off (On)

**Reflowable document:**
* Set Font size to 20 (28)

Warmth, Night Mode and Font Size control is working good

The Frontlight brightness control does not work, neither up nor down!

**Comment by NiLuJe** [comment]
What about the default (I think? :D) vertical swipe along the *right* edge of the screen?

**Comment by oldman63** [comment]
> What about the default (I think? :D) vertical swipe along the _right_ edge of the screen?

The default finger gesture and modification from the menu works.
This error report applies to group finger gestures.

**Comment by NiLuJe** [comment]
Does it work if it's the *only* action for the custom gesture?

**Comment by oldman63** [comment]
Ops...

If deactivate Font size function, the all other function is works good.
If activate Font Size, the brightness control does not works anymore!

**Comment by NiLuJe** [comment]
That.. vaguely ring a bell ;o). (ping @yparitcher & @pore-z).

(What vaguely comes to mind about it is something along the lines of "don't do that , that's not reliable ;p", though ^^)⁾.

**Comment by NiLuJe** [comment]
Random idea: might be related to the CRe `discardEvent` shenanigans?

**Comment by yparitcher** [comment]
> Random idea: might be related to the CRe `discardEvents` shenanigans?

Yup, spot on. caused by this.
BTW only `sendEvent` drops these not `broadcatEvent`.

Is there a way to filter **input** events specifically, coming from the input module or something? the current method might prevent even events triggered by a refresh itself (to update other things) to be ignored.

**Comment by NiLuJe** [comment]
> Is there a way to filter **input** events specifically, coming from the input module or something? the current method might prevent even events triggered by a refresh itself (to update other things) to be ignored.

A couple of ways, at a very quick glance: either nerf the input handlers globally via the newly introduced `Input:inhibitInput`, or, probably worse performance-wise (because the cost is incurred on *every* frame, instead of at both bracketing call sites), clear the table returned by `Input:waitEvent` in `UIManager:handleInput`.

**Comment by NiLuJe** [comment]
Might require revisiting existing `discardEvents` call sites, too, because I would guess most of 'em were intending to block input events only, indeed.

**Comment by yparitcher** [comment]
I think something like this should work (not tested yet), with minimal change. just move the check from `sendEvent` to `handleInputEvent`

```diff
diff --git a/frontend/ui/uimanager.lua b/frontend/ui/uimanager.lua
index 1b20e14a..c836cbc2 100644
--- a/frontend/ui/uimanager.lua
+++ b/frontend/ui/uimanager.lua
@@ -1087,15 +1087,6 @@ which itself will take care of propagating an event to its members.
 function UIManager:sendEvent(event)
     if #self._window_stack == 0 then return end
 
-    -- Ensure discardEvents
-    if self._discard_events_till then
-        if TimeVal:now() < self._discard_events_till then
-            return
-        else
-            self._discard_events_till = nil
-        end
-    end
-
     -- The top widget gets to be the first to get the event
     local top_widget = self._window_stack[#self._window_stack]
 
@@ -1621,6 +1612,14 @@ function UIManager:handleInputEvent(input_event)
     if handler then
         handler(input_event)
     else
+        -- Ensure discardEvents
+        if self._discard_events_till then
+            if TimeVal:now() < self._discard_events_till then
+                return
+            else
+                self._discard_events_till = nil
+            end
+        end
         self.event_handlers["__default__"](input_event)
     end
 end
```

**Comment by yparitcher** [comment]
As we probably still want to get power/suspend/SS/etc events when blocking input. (as i think we currently do)

**Comment by NiLuJe** [comment]
> As we probably still want to get power/suspend/SS/etc events when blocking input. (as i think we currently do)

`inhibitInput` lets those through, FWIW ;).

**Comment by yparitcher** [comment]
It looks to me that `discardEvents` `inhibitInput` and `setIgnoreInput` do very similar things and should probably be consolidated.

Maybe have `discardEvents` & `inhibitInput` merge to using the same implementation (either nerf the handlers or ignore the events), but still allow for permanent blocking (like `inhibitInput`) or time based (like `discardEvents`) as part of this combined implementation it should (on android) call `android.setIgnoreInput` getting rid of the general `setIgnoreInput`.

**Comment by yparitcher** [comment]
Please vote:
1. Nerf the handlers
2. Suppress the events
:)

**Comment by yparitcher** [comment]
Note to self:
   when fixing, please fix the Uimanager Event docs about active_widgets

**Comment by NiLuJe** [comment]
Right, I vaguely glanced at `setIgnoreInput` when working on `inhibitInput`, but it *might* be problematic to merge 'em.

The idea behind `inhibitInput` was to basically avoid random crap happening during suspend on devices with a cover. If this were to call `setIgnoreInput` on Android, wouldn't that prevent us from getting key power-management related events? (I have no idea, I don't really do Android, which is basically why I left the two separate ;p).

But I definitely like the idea ;).

----

Supporting a time-based approach w/ `inhibitInput` would be pretty easy: just schedule/unschedule the "toggle it back on" function. Allows to get rid of the messy interaction with intra-frame timings inside UIManager, too!

**Comment by NiLuJe** [comment]
At a quick glance, yeah, all current `discardEvents` call sites appear to only be concerned with user input.

**Comment by yparitcher** [comment]
See #9065 for a draft version. only the merge for now cleanup to come soon

**Comment by NiLuJe** [comment]
> As a side point the Uimanager Event docs are wrong. (They say all Reader modules are `active_widgets` when only a few that register as one are)

Huh. I think I wrote that bit, so I don't know what I was on at the time, because, yeah, that pretty much currently only applies to the screenshotter module, both in FM & RUI ;D.

**Comment by yparitcher** [comment]
Btw `setIgnoreInput` just ignores the touchscreen so it is a candidate for merge into `inhibitInput`
https://github.com/koreader/android-luajit-launcher/blob/764166d12f681588679ae2c3842b698dc1f63de3/app/src/main/java/org/koreader/launcher/MainActivity.kt#L681-L689
```kotlin
    override fun setIgnoreInput(enabled: Boolean) {
        runOnUiThread {
            if (enabled) {
                window.addFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE)
            } else {
                window.clearFlags(WindowManager.LayoutParams.FLAG_NOT_TOUCHABLE)
            }
        }
    }
```
@pazos 
Please confirm

**Comment by pazos** [comment]
> Btw `setIgnoreInput` just ignores the touchscreen so it is a candidate for merge into `inhibitInput`

Not sure about the intent of `inhibitInput`. `setIgnoreInput` is intended to be called on blocking calls where LuaJIT might be  unable to drain the input queue in 5+ seconds. It does that by making the whole window not touchable until the call ends.
