### ISSUE TITLE
KOReader fails to start on Kindle Oasis 3

### ISSUE THREAD

**Issue by Jack426** [koreader/koreader#9044]
* KOReader version: v2022.03.1
* Device: Kindle Oasis 3 (5.14.1)

#### Issue
KOReader fails to start. When clicking "Start KOReader" the screen returns to the default Home/Library view and flashes once, but otherwise does nothing.

[crash.log](https://github.com/koreader/koreader/files/8591845/crash.log)

**Comment by NiLuJe** [comment]
Your JB is incomplete. Reinstall the hotfix and make sure you reboot a *couple* of times.

**Comment by Jack426** [comment]
> Your JB is incomplete. Reinstall the hotfix and make sure you reboot a _couple_ of times.

Gotcha, thanks! I actually just started to reinstall everything from the beginning to see if I screwed something up.

**Comment by captn3m0** [comment]
Faced a slightly different crash on PW3:

```

./luajit: error loading module 'device/generic/powerd' from file 'frontend/device/generic/powerd.lua':
	frontend/device/generic/powerd.lua:238: function arguments expected near '<eof>'
stack traceback:
	[C]: at 0x0005718d
	[C]: in function 'require'
	frontend/device/kindle/powerd.lua:1: in main chunk
	[C]: in function 'require'
	frontend/device/kindle/device.lua:709: in function 'init'
	frontend/device.lua:62: in main chunk
	[C]: in function 'require'
	./reader.lua:142: in main chunk
	[C]: at 0x00013e9d
ffi.load: blitbuffer
```

Reinstalling the hotfix worked.
