### ISSUE TITLE
FR: battery level in screensaver message

### ISSUE THREAD

**Issue by LeslieFH** [koreader/koreader#9048]
It would be useful to add an escape sequence for displaying battery level in the screensaver.

**Comment by NiLuJe** [comment]
It wouldn't do you much good, as that would be the battery level *at suspend time*, it wouldn't update (because the device is asleep).

**Comment by mariogit99** [comment]
I like the idea from leslie, even as the shown value is from time of suspension. After wakeup you can see how much it degraded during sleep...
