### ISSUE TITLE
Panel Zoom not only for PDF/DJVU document

### ISSUE THREAD

**Issue by fekir** [koreader/koreader#9050]
* KOReader User guide: Created 2021-08-09T09:33:08 CEST (could not find any version info)

#### Issue
According to https://koreader.rocks/koreader-user-guide.pdf

````
This feature makes reading comic books easier on smaller screens. You can enable it while you are reading a
PDF/DJVU document via:

[...]
````

But in practice, the feature is also available when reading cbz comics and can be enabled also for jpg files.

I assume the feature was only available for PDF/DJVU and the documentation has not been updated accordingly

#### Steps to reproduce

Open a cbz comic or single image, and enable Panel Zoom.

**Comment by Frenzie** [comment]
Rather, it's any document opened by MuPDF or DjVuLibre.

**Comment by offset-torque** [comment]
> Rather, it's any document opened by MuPDF or DjVuLibre.

Can I get a list of these types @Frenzie so I can update the Panel Zoom section accordingly.

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/blob/f37699a12b893984690f0e433b7f048af3c621a7/frontend/document/pdfdocument.lua#L359-L397 for the full list of filetypes that our MuPDF can currently open.

But note that for e.g. EPUB you need to long-press, open with.

**Comment by offset-torque** [comment]
@Frenzie

**If I understood correctly:**
- MuPDF can open many file types 
- But not all of them are associated with it (EPUB is one of the exceptions for example)
- Are there other file types which MuPDF **can** open but **not** associated with it (so they require "open with..." if users want to use Panel Zoom feature)

I am trying to determine the intersection of different engines to be able to explain it clearly in the user guide.

**Comment by Frenzie** [comment]
EPUB, FB2 and HTML can be opened by MuPDF. They default to crengine.

Some of the image formats (e.g., jpeg, gif) can be opened both by MuPDF and by our own image viewer, but I think those default to the image viewer.

**Comment by Frenzie** [comment]
Addressed by https://github.com/koreader/koreader/issues/8058

**Comment by Frenzie** [comment]
See
https://github.com/koreader/koreader/blob/f37699a12b893984690f0e433b7f048af3c621a7/frontend/document/pdfdocument.lua#L359-L397
for the full list of filetypes that our MuPDF can currently open.

But note that for e.g. EPUB you need to long-press, open with.
