### ISSUE TITLE
FR: Autoturn >240sec

### ISSUE THREAD

**Issue by fekir** [koreader/koreader#9051]
I would like to set the timeout to 30 or 60 min, but currently the maximum allowed value is 240 second (4 minutes).

Is there a technical limitation why bigger values are not allowed?

**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]

**Describe the solution you'd like**
Automatically change page after a longer period of time (>30min)

**Describe alternatives you've considered**
Not using Autoturn and change page by hand

**Additional context**
I'm showing images, quotes or other pages with little text to read (either single images or pages in a pdf/cbz file) and would like to rotate them automatically.

**Comment by zwim** [comment]
No, it is no technical problem. I will change the input method to allow to enter minutes and seconds.
