### ISSUE TITLE
[question] usb disk won't mount when koreader is running

### ISSUE THREAD

**Issue by xpufx** [koreader/koreader#9056]
My Kindle does not automount when koreader is running. It mounts as soon as I exit koreader. Is this how it functions or is something wrong?

**Comment by hius07** [comment]
https://github.com/koreader/koreader/wiki/Installation-on-Kindle-devices#usb

**Comment by xpufx** [comment]
Thank you. I had read that note but didn't make the connection somehow. I can work around it. Both ssh and calibre wifi work. I wanted a solution because it seems like it's best to stay in koreader instead of exiting and launching it again all the time.
