### ISSUE TITLE
Function of DPAD Keys - can't call Dictionary or Mark Words on Kindle 4NT

### ISSUE THREAD

**Issue by clrizzi** [koreader/koreader#9063]
* KOReader version: 2022.03.1
* Device: Kindle 4NT

#### Issue
On this device the DPAD keys are configured to change pages while reading a book (UP and LEFT to previosly page and RIGHT and DOWN to next page)

It would be better if pressing the DPAD keys and positioning the cursor before a word could call up the dictionary automatically (like the original kindle firmware) and also give me the option to select and mark excerpts from some page.

I noticed that in the menu while reading there is a new entry called **"New: Long-Press on Text"** which would serve well for the purpose I would like, however I think it should work if I could move the cursor through the text.

If I try to long press the central button of the DPAD without "selecting" the text, it will only open the lower reading menu

So far, I haven't found any way on this device to move the cursor in the text or select words.

#### Steps to reproduce
Open a book and try to select words using DPAD keys. It just turn pages.

**Comment by pazos** [comment]
Have a look at current implementation, very well described in https://github.com/koreader/koreader/pull/8877.

**Comment by clrizzi** [comment]
Thanks, @pazos! 

I hadn't seen the "start content selection" option... my mistake! Really, somehow it works. 

I still believe that using the DPAD keys would be more intuitive if they could immediately insert the cursor on the screen instead of flipping pages.

Anyway, thanks for the information. This will help a lot instead of having to manually invoke the dictionary and type the word every time!

**Comment by pazos** [comment]
> I still believe that using the DPAD keys would be more intuitive if they could immediately insert the cursor on the screen instead of flipping pages.

Actually I think current implementation is better. Basic features (page turning and navigation across menus) require no previous knowledge and other advanced stuff are only constrained by the lack of physical keys and by the fact that KOReader was designed with touchscreen devices in mind.

**Comment by Commodore64user** [comment]
for you, or anyone else interested, #11749 should make this soon a reality.

**Comment by clrizzi** [comment]
> for you, or anyone else interested, #11749 should make this soon a reality.

It would be great, @Commodore64user. Thanks!

**Comment by Commodore64user** [comment]
> > for you, or anyone else interested, #11749 should make this soon a reality.
> 
> 
> 
> It would be great, @Commodore64user. Thanks! 

You can already test it if you like, simply download the latest nightly. Would be nice to get some feedback before it goes live in the next stable release.

**Comment by clrizzi** [comment]
> > > for you, or anyone else interested, #11749 should make this soon a reality.
> > 
> > 
> > It would be great, @Commodore64user. Thanks!
> 
> You can already test it if you like, simply download the latest nightly. Would be nice to get some feedback before it goes live in the next stable release.

Sorry for the long delay in responding, @Commodore64user . I was away for a while and couldn't test this feature. 

Today I finally got around to updating my old Kindle and found that it's working very well. I noticed that sometimes the cursor "jumps" a little more between lines, but nothing that makes it difficult to use. This way, it's much more intuitive to use when accessing the dictionary.

 Thanks for this implementation.

And again, sorry for the delay!

**Comment by Commodore64user** [comment]
> Sorry for the long delay in responding,

No worries mate, better late than never ;)

> Today I finally got around to updating my old Kindle and found that it's working very well.

That's what i like to hear. A happy customer 

> I noticed that sometimes the cursor "jumps" a little more between lines, but nothing that makes it difficult to use. This way, it's much more intuitive to call the  dictionary.

You have to adjust that to your specific circumstances `Top menu > Document icon > Selection on text > page 2 of 2` play with the (3) settings there and let me know if you have any questions.


>  Thanks for this implementation.

You're most welcome 🙏

**Comment by clrizzi** [comment]
Thanks, friend. I'll test the rate of movement.

I just realized that the bigger "jumps" that occurred between the lines is because of the "speed-up rate on multiple keystrokes" option.

It looks great!

Greetings!
