### ISSUE TITLE
Can't open books in "Mosaic with cover images" display mode - Kindle 4NT

### ISSUE THREAD

**Issue by clrizzi** [koreader/koreader#9066]
* KOReader version: 2022.03.1
* Device: Kindle 4NT

#### Issue
Unable to open ebooks if **display mode** is selected as **Mosaic With Cover Images** or **Mosaic with Text Covers**. DPAD keys work partially: **UP** arrow selects left book. **DOWN** arrow selects the book on the right.

The middle DPAD key that should be used to open the book does not work. The LEFT and RIGHT keys also do not work.
#### Steps to reproduce
On **Display Mode**, select **Mosaic With Cover Images** or **Mosaic With Text Covers**. Select the book and press the center DPAD key. Nothing happens.

**Comment by comphilip** [comment]
Fixed in #9041
