### ISSUE TITLE
Mosaic view

### ISSUE THREAD

**Issue by walti0** [koreader/koreader#9069]
* KOReader version:2022.03.1
* Device: Kindle 10

#### Issue
I want to have less elements but bigger covers in mosaic mode but when i changed in "mosaic and detailed list settings" option Items per page It makes difference in detailed view only. Nothing changed in mosaic view. Do I something wrong?

**Comment by poire-z** [comment]
You did nothing wrong: items per page only applies to "detailed list" modes.

For Mosaic mode, the nb of cols/rows are hardcoded:
https://github.com/koreader/koreader/blob/54ead5fc887331612d2e57d736c4e1dbde4e2efa/plugins/coverbrowser.koplugin/mosaicmenu.lua#L852-L861

It would be a little complicated/bothering to have to add some UI menu to allow changing them (one set for landscape, another set for portrait), when 3x3 or 2x4 is mostly ok for most people.

You can try editing the numbers in this bit of code on your device to see how it would really look and if it is really fine.
If really fine, we could pick these default values from some hidden settings, that you would manually add to your settings.reader.lua.
(Or we would have a few sets in the menu: normal (3x3, 4x2), smaller (4x4, 5x3), larger (2x2, 3x1), but i have no idea how these other combinations would look and if they would be really usable.)

**Comment by walti0** [comment]
Thanks bro
