### ISSUE TITLE
The top menu does not pop up on the IReader Ocean 2 reader（Android device）

### ISSUE THREAD

**Issue by asuplive** [koreader/koreader#9071]
* KOReader version: 2022.03.1
* Device: IReader Ocean 2

#### Issue

The top menu does not pop up on the IReader Ocean 2 reader (Android device)

**Comment by pazos** [comment]
Swipe gestures near top/bottom might be catched by the framework as a gesture to go out of immersive mode.

Please use tap instead if that's an issue on your device

**Comment by asuplive** [comment]
> Swipe gestures near top/bottom might be catched by the framework as a gesture to go out of immersive mode.
> 
> Please use tap instead if that's an issue on your device

Gesture operation is click not slide, click on the screen above the corresponding menu can not be populated

**Comment by pazos** [comment]
I'm sorry to hear that.

I'm aware some e-ink readers are somehow broken and do not follow android/aosp rules. Never heard of something so much broken. 

I'm afraid we won't be able to fix that. Please ping if you're able to reproduce the issue on any other android device.

**Comment by superliujian** [comment]
I have the same problem, on iReader smart xs, the menu cannot shown no matter tap or swipe.

**Comment by markx** [comment]
I got the same issue on iReader Ocean 3. All the UI widgets like buttons and items in the file browser work fine, but clicks on other non UI areas seemed lost.

Is there any documentation/instructions on how to debug things?

**Comment by ikakaxi** [comment]
I'm having this issue too.

**Comment by plateaukao** [comment]
This issue is fixed in my branch, and binary is available here:
https://github.com/plateaukao/koreader/releases/tag/ireader-v2026.07
