### ISSUE TITLE
KoReader for pocketbook basic lux 2

### ISSUE THREAD

**Issue by Aleromanotkd** [koreader/koreader#9077]
Hi, I've pocketbook basic lux 2 (PB616W if i'm not wrong) and i wanted to install koreader, but it doesn't work. I found out a similar discussion where there was @Frenzie, but i didn't understand if it is possible to use koreader on mine device. Can someone please help me, maybe sending the right folders i must transfer in my PB616W?

**Comment by Frenzie** [comment]
Presumably that should work:

https://github.com/koreader/koreader/blob/4b0f7471f4a38c3371d01a8251d8f9f9f2937eb8/frontend/device/pocketbook/device.lua#L658-L660

For future reference, it'd be helpful to say which discussion that was specifically. ;-)

**Comment by Aleromanotkd** [comment]
Oh Sorry. However, thank you so much, but what i should do? Should i download this file and replace with the One that Is in the folder?

**Comment by Aleromanotkd** [comment]
https://photos.app.goo.gl/JHFqMHAVMwbKVRvB7

**Comment by Frenzie** [comment]
That file is part of the installation. See the instructions on https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices

**Comment by Aleromanotkd** [comment]
Thank you so much and Sorry me

**Comment by Aleromanotkd** [comment]
I deleted local ext_path = "/mnt/ext1/system/config/extensions.cfg" line in device.lua file, but i don't see device menu

**Comment by Aleromanotkd** [comment]
I deleted local ext_path = "/mnt/ext1/system/config/extensions.cfg" line in device.lua file, but i don't see device menu. Is it right or i'm wrong?
