### ISSUE TITLE
koreader on kindle 10th cannot open pdf 

### ISSUE THREAD

**Issue by kietarch123** [koreader/koreader#9081]
* KOReader version: 2022.03.1
* Device: Kindle 10th 

##### `crash.log` (if applicable)

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<token
05/07/22-22:14:33 WARN  cannot open document /mnt/us/sach/Sach lam-giau-mot-cach-khoa-hoc-thuvienPDF.com.pdf frontend/document/pdfdocument.lua:35: ./ffi/mupdf.lua:78: MuPDF found no pages in file.: cannot find startxref (2)
CRE WARNING: zip file truncated: going on with possibly partial content.
CRE WARNING: zip file truncated: going on with possibly partial content.
05/07/22-22:14:44 INFO  opening file /mnt/us/sach/Sach lam-giau-mot-cach-khoa-hoc-thuvienPDF.com.pdf
ffi.load: libs/liblept.so.5
ffi.load: libs/libk2pdfopt.so.2
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
warning: object missing 'endobj'>
```
</details>

**Comment by Frenzie** [comment]
Is there something you're trying to state implicitly? Because I have to say I don't really see the problem here. ;-)

**Comment by Frenzie** [comment]
Try something like `mutool clean -ggg your-broken-file.pdf output-that-might-work.pdf`.

**Comment by kietarch123** [comment]
sorry, im not good in english. 
when i open pdf file in koreader ( Kindle 10th jaibreak ) koreader said: " No reader engine for this file or invalid file" 
please help me this prolemb!!

**Comment by Frenzie** [comment]
Right, and your crash.log says that the document is broken.

```
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
warning: object missing 'endobj'>
```

**Comment by kietarch123** [comment]
i tried with another pdf file, still can not open. :((

**Comment by poire-z** [comment]
See if your PDFs open correctly on a computer with Acrobat.
If yes, see if you copied them correctly on your Kindle, if the file size you see on your Kindle is the exact file size you had on your computer (it's possible the files get corrupted when you transfered them).
If I test with a 0-bytes/empty dummy.pdf, I get:
```
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot tell in file
```

**Comment by kietarch123** [comment]
wow. finally i got it. it fixed.
when i download by dropbox token, the pdf file can not to be open. then i copy from computer to folder, pdf file can open. 
thank so much, all guy!!
