### ISSUE TITLE
P78 crashes when connecting to Calibre

### ISSUE THREAD

**Issue by Pixm79** [koreader/koreader#9085]
* KOReader version: 2022.03.1-57
* Device:P78

#### Issue
Everytime I try to connect to Calibre, Koreader crashes after cliccking on the connect button. 

#### Steps to reproduce
Just click on the Calibre plugin and press "connect"

##### `crash.log` (if applicable)
--------- 
[crash.log.txt](https://github.com/koreader/koreader/files/8647713/crash.log.txt)

**Comment by pazos** [comment]
That log is useless. Try to get one following the bug report template (help -> report a bug, attach file). Hopefully it will contain the error message that lead to a crash.

**Comment by Pixm79** [comment]
Thanks!
I have now uploaded the crash log here.

**Comment by pazos** [comment]
@Pixm79: thank you, that log looks fine but doesn't contain any error (maybe because you didn't reproduce the error and logcat keeps a short log on memory -or much more probably it's flooded with other app's messages).

Could you try to reproduce the issue, restart the crash and get another log?. Thanks!

@NiLuJe: I'm not sure it is android specific. I did a quick googling and found https://lwn.net/Articles/889171/, which mentions the same issue but with a Kobo.

**Comment by NiLuJe** [comment]
@pazos: Noted, thanks ;).

FWIW, as I usually don't use the wireless driver feature, I've just tried it again on a H2O w/ the current nightly & calibre 5.42.0, and everything's okay over here :).

**Comment by tartanpion** [comment]
Same problem with libra 2 when connecting wireless to calibre, and probably not related but usb storage says plugged into a plain power source koreader will restart (the log was available after exiting koreader, under kobo software)

[crash.log](https://github.com/koreader/koreader/files/8647934/crash.log)
![crash](https://user-images.githubusercontent.com/3924779/167319455-12ac9b2f-0bcf-4156-9e42-7dd804380bf9.jpg)

**Comment by pazos** [comment]
ok, thanks!

Timestamp issues.

Caused by https://github.com/koreader/koreader/pull/8999?

**Comment by NiLuJe** [comment]
Whelp, guess I wasn't actually using the latest nightly, then :s.

(Thought I'd updated the H2O, but apparently I forgot :/).

**Comment by NiLuJe** [comment]
@tartanpion: USB issue in unclear, could you clarify that (in a dedicated issue, ideally).
