### ISSUE TITLE
SDL2 and physical touch screens 

### ISSUE THREAD

**Issue by lennonhill** [koreader/koreader#9091]
* KOReader version: 2022.03.1
* Device: PineNote (Arch Linux using the debian package on wayland/sway + X11/XFCE)

#### Issue
I've been trying to make the touch screen work on the Pine64 PineNote, which features both a touchscreen and a pen-based tablet. Pen-based input, which corresponds `SDL_MOUSE*` events, works just fine. Any touch input gets translated into the same sequence `(SDL_MOUSEMOTION, SDL_MOUSEBUTTONDOWN, SDL_FINGERDOWN, SDL_MOUSEBUTTONUP, SDL_FINGERUP)` as soon as the finger touches the screen. Any subsequent motion or the up event do not result in an SDL2 input event, effectively translating all touch input to single taps. When using the hint `SDL.SDL_SetHint("SDL_TOUCH_MOUSE_EVENTS", "0")` I observe all `SDL_FINGER*` events as expected and all gestures and long presses work as expected. The problem and solution apply to both wayland/sway (libinput) and X11/XFCE (xf86-input-libinput).

Does it make sense to set this hint in general? I don't have any other devices with a touchscreen that support the SDL2 build. If not, should this be made configurable?

**Comment by Frenzie** [comment]
If you share your changes I'll test the behavior on my touchscreen. I suspect we want that hint as 0 in principle, but of course we want to actually deal with multiple fingers.

**Comment by Frenzie** [comment]
Oh, I didn't realize that was the full extent of your changes or I wouldn't have asked. :rofl: Suffice it to say I want to do a whole lot more with the finger stuff. ;-)

**Comment by Frenzie** [comment]
That's expected. It's precisely actually handling those events properly that has to be added. I think possibly in front, not in base. But as long as single-touch still works with that flag without any additional changes, it should be harmless.

**Comment by Frenzie** [comment]
Alright, I'll probably be able to give it a try tonight. You can ping me by Friday or Saturday if I didn't get around to it and forgot in the meantime. ^_^

**Comment by Frenzie** [comment]
Is it necessary before init? It feels more in flow to me around line 109 or 115.

It makes no difference either way, on 2.0.20.

**Comment by Frenzie** [comment]
Sorry, I forgot about this one (but you can also submit a PR ;-) ). Done in https://github.com/koreader/koreader-base/pull/1491.

**Comment by Frenzie** [comment]
Incidentally, I added SDL multitouch support in <https://github.com/koreader/koreader-base/pull/1599>.
