### ISSUE TITLE
After the Touch HD3 has woken up, nothing works.

### ISSUE THREAD

**Issue by kryptos1967** [koreader/koreader#9095]
* KOReader version: v2022.03.1-63-g84dd58f9_2022-05-09
* Device: Pocketbook Touch HD3

#### Issue
After the Touch HD3 has woken up, neither the touch nor the page change keys work.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
Going to need a verbose debug log :). (tools > more tools > Developer options).

**Comment by kryptos1967** [comment]
---------------------------------------------
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 05/14/22-06:42:19
 [*] Version: v2022.03.1-63-g84dd58f9_2022-05-09

ffi.load: blitbuffer
ffi.load: inkview
05/14/22-06:42:19 INFO  SoftwareVersion:  U632.6.5.1383
Atached mp shm: id 0 addr a6f2e000 size 17616
attach_shm: mtfb key=251349606 size=1657600
Atached mtfb shm: id 1d0008 addr a4335000 size 1657600
-------------------------
Starting task - KOReader
flags: 0x00000080
gpid: 2662
fb=0xa4335000 xres=1072 yres=1448 scanline=1072 vdepth=8 orient=0
-------------------------
attach_shm: mttempfb key=251308714 size=1584128
Atached mttempfb shm: id 8001 addr a41b2000 size 1584128
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800000; gka2 = 800000
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 10720000 0 -10000 0 10000 0
attach_shm: mtfb key=251349606 size=1657600
Atached mtfb shm: id 1d0008 addr a2b15000 size 1657600
[2666 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: inkview
ffi.load: librt.so
ffi.load: inkview
ffi.load: inkview
05/14/22-06:42:19 INFO  initializing for device PBTouchHDPlus
05/14/22-06:42:19 INFO  framebuffer resolution: {
    ["w"] = 1072,
    ["h"] = 1448,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
05/14/22-06:42:20 INFO  opening file /mnt/ext1/SendToPb/Kongo requiem   Jean Christophe Grange.epub
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSerif-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSerif-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSerif-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSerif-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Amazon Ember Bold Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Amazon Ember Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Amazon Ember Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Amazon Ember Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Andada-Bold-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Andada-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Andada-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Andada-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/AndikaInk Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/AndikaInk BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/AndikaInk Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/AndikaInk Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Bookerly-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Bookerly-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Bookerly-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Bookerly-RegularItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Caecilia-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Caecilia-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Caecilia-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Caecilia.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChareInk-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChareInk-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChareInk-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChareInk-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChartereInk-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChartereInk-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChartereInk-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/ChartereInk-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/CourierPrime-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/CourierPrime-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/CourierPrime-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/CourierPrime.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Delicious Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Delicious Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Delicious Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Lato-Bold-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Lato-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Lato-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Lato-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSans-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSans-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSans-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSans-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSerif-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSerif-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSerif-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LiberationSerif-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LinLibertine_RBIah.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LinLibertine_RBah.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LinLibertine_RIah.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/LinLibertine_Rah.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Merriweather-Bold-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Merriweather-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Merriweather-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Merriweather-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/MerriweatherSans-Bold-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/MerriweatherSans-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/MerriweatherSans-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/MerriweatherSans-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/NotoSerif-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/NotoSerif-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/NotoSerif-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/NotoSerif-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/OpenSans-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/OpenSans-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/OpenSans-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/OpenSans-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Rojarivo-Bold.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Rojarivo-BoldItalic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Rojarivo-Italic.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/Rojarivo-Regular.ttf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/TeXGyreSchola-Bold.otf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/TeXGyreSchola-BoldItalic.otf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/TeXGyreSchola-Italic.otf>
05/14/22-06:42:21 ERROR failed to register crengine font: cannot register font </mnt/ext1/system/fonts/TeXGyreSchola-Regular.otf>
05/14/22-06:42:21 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
05/14/22-06:42:21 WARN  Terminal: can not open /dev/ptmx: Permission denied
05/14/22-06:42:21 WARN  Error when loading plugins/terminal.koplugin/main.lua
GET https://sync.koreader.rocks:443/syncs/progress/fe5ce81b8b68941e3e1aa798165818f9
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
PUT https://sync.koreader.rocks:443/syncs/progress
host or service not provided, or not known
05/14/22-06:42:32 INFO  Inhibiting user input

**Comment by NiLuJe** [comment]
Not verbose, which means I'll have to dig up how Power events are generated on PcketBook ;'(.
