### ISSUE TITLE
Text not rendered outside bounds when line spacing < 100

### ISSUE THREAD

**Issue by stareatmyname** [koreader/koreader#9102]
* KOReader version: 2022.03.1
* Device: Android 9.0

#### Issue
Text overflowing to the bottom and out of the page boundary in crengine no longer renders as it does in previous versions.

#### Steps to reproduce
1. Open any .epub file, possibly also any file recognized by crengine.
2. Set line spacing to any value less than 100 inside the bottom menu, preferably as low as possible.
3. Observe the text on the last line of each column.

Below is a example of this issue in versions 2022.02 and 2022.03.1 respectively. Specifically, the bottom row of the left and right columns in the second image are chopped off:
![koreader  02](https://user-images.githubusercontent.com/33539289/168478768-95c06578-c6de-44dc-8a1e-1d8103c8f634.png)
![koreader  03 1](https://user-images.githubusercontent.com/33539289/168478770-9f9facbe-3ec6-4777-9e8c-853660ce1724.png)

This issue is possibly related to an older issue where the highlight overlay for text selection and highlighting does not accurately represent the shape of the actual text. Below is an example of text selection with low line spacing in 2022.02. The same effect of text being cut off is also apparent where the overlays overlap:
![koreader  02 selection](https://user-images.githubusercontent.com/33539289/168479206-e316515c-04a9-4777-96e8-5b0bd3431e50.png)

**Comment by NiLuJe** [comment]
This should be fixed in current nightlies, please re-open if that isn't the case ;).

**Comment by poire-z** [comment]
Yes, fixed by #8972, so in v2022.05.
