### ISSUE TITLE
Crashes when creating folder shortcut

### ISSUE THREAD

**Issue by ananas-wonders** [koreader/koreader#9105]
* KOReader version: 2022.03.1
* Device: Kindle PW4 - JB 5.14.2

#### Issue
Koreader crashes when I try to create an folder shortcut.

#### Steps to reproduce
create any folder shortcut by pressing the '+' icon on the upper left corner then navigating to the desired folder and pressing the long press tile. Koreader crashes and exits Kual to kindle's homescreen. 

##### `crash.log` 
[crash.log](https://github.com/koreader/koreader/files/8711912/crash.log)

**Comment by hius07** [comment]
It seems to happen after you've finished the dialog "Enter friendly name".
Can you give more details on the folder you are adding the shortcut for, and the friendly name you are entering.

**Comment by ananas-wonders** [comment]
I'm making a shortcut for a folder that contains .cbz files at the path [/mnt/base-us/manga] and the name I'm entering is 'manga'.

**Comment by hius07** [comment]
> /mnt/base-us/manga

Can you try /mnt/us/manga?

**Comment by ananas-wonders** [comment]
Just tried [/mnt/us/manga] , Same result. it crashes.

**Comment by hius07** [comment]
Thank you, confirm crash when adding **the first** shortcut to the empty list.
