### ISSUE TITLE
Kobo libra 2: koreader sometimes freezes after changing brightness/warmth settings

### ISSUE THREAD

**Issue by mandarancza** [koreader/koreader#9110]
* KOReader version: 2022.03
* Device: Kobo Libra 2

#### Issue

Sometimes after I change the brightness or warmth settings by sliding up or down near the edge of the screen, my Libra 2 just freezes. I'm then unable to do anything, tap the screen, click the next page button or even put it to sleep. The only thing that I'm able to do is to hold down the power button for a few seconds till it powers off completely and then hold it down again for it to turn on. 
The issue does not happen every time I change brightness settings, just occasionally. It's been apparent for a very long time, but I have not made a separate ticket before, as I thought the issue might be connected with koreader crashing when jumping chapters using ToC. But that problem has been resolved and my issue still exists on newer koreader versions and kobo firmwares. The last time it happened was 18.05.2022 at around 15:30 as you will be able to see the restart at that time in crash log. But as I have already said it only happens occasionally, so it may not be reproducible for you at the first try or even at all.

#### Steps to reproduce

Use brightness or warmth slider at the edge of the screen.

[crash.log](https://github.com/koreader/koreader/files/8720987/crash.log)

**Comment by NiLuJe** [comment]
Duplicate (in spirit) of #8414
