### ISSUE TITLE
FR: Chapter progress bar

### ISSUE THREAD

**Issue by subnetz** [koreader/koreader#9115]
Hello,  
I am using both the status bar and alt status bar, and I was wondering if I can use one of the two as a progress bar for the current chapter.  
Mockup:
![Reader_2022-05-20_123721](https://user-images.githubusercontent.com/8416994/169516677-c33d7c7d-67ac-45ab-bd31-491f07a25d6f.png)

**Comment by Commodore64user** [comment]
this was added with #11505.
