### ISSUE TITLE
reMarkable 2 crashes with v2022.05

### ISSUE THREAD

**Issue by snelg** [koreader/koreader#9122]
* KOReader version: 2022.05
* Device: reMarkable 2

#### Issue

Crashes immediately with any touch input (finger or stylus)
PR #9121 submitted; I can't remember if I'm supposed to also create an Issue if the PR is for a bug fix.

#### Steps to reproduce

 - Start KOReader
 - Touch screen

##### `crash.log`
<details>
  <summary>crash.log</summary>

```
./luajit: frontend/ui/time.lua:130: attempt to index local 'tv' (a number value)
stack traceback:
        frontend/ui/time.lua:130: in function 'timeval'
        frontend/device/input.lua:714: in function 'handleTouchEv'
        frontend/device/input.lua:1240: in function 'waitEvent'
        frontend/ui/uimanager.lua:1698: in function 'handleInput'
        frontend/ui/uimanager.lua:1754: in function 'run'
        ./reader.lua:324: in main chunk
        [C]: at 0x000140f1
!!!!
Uh oh, something went awry...
```
</details>

**Comment by Frenzie** [comment]
> I can't remember if I'm supposed to also create an Issue if the PR is for a bug fix.

I think the PR provides all the information we need (if it provides enough information, which this one definitely does). But if you prefer opening an issue as well that's fine too.
