### ISSUE TITLE
WebDav

### ISSUE THREAD

**Issue by tjimofbis** [koreader/koreader#9125]
* KOReader version:2022.05.1
* Device:Kobo GloHD, Kobo Forma, Tolino Shine 3, android tablet

#### Issue
When copying from webdav the file is not saved to local storage. If you replace the koreader/frontend/apps/cloudstorage/webdavapi.lua file with an older version from build 2022.03.1 then saving works again.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hius07** [comment]
Can you share here your settings of the WebDAV server from koreader/settings/cloudstorage.lua (delete the password field).

**Comment by tjimofbis** [comment]
-- we can read Lua syntax here!
return {
    ["cs_servers"] = {
        [1] = {
            ["address"] = "https://myrouter.keenetic.pro/webdav",
            ["name"] = "homerouter",
            ["password"] = "password",
            ["type"] = "webdav",
            ["url"] = "",
            ["username"] = "user",
        },
    },
    ["download_dir"] = "/mnt/onboard/books/english",
}

**Comment by tjimofbis** [comment]
the new version of **webdavapi.lua** has this line
             `local item_path = path == "" and item_name or path .. "/" .. item_name`
With it, saving files does not work if you change to
             `local item_path = path .. "/" .. item_name`
then the save works.

**Comment by hius07** [comment]
Can you try to add single slash to the end of the "address" field or to the "url" field.

**Comment by tjimofbis** [comment]
If you add a slash to the address field, then folders in the cloud storage do not open. If you add a slash to the url field, then the folders are opened, but the files are not saved on the eReader.

**Comment by hius07** [comment]
Can you try to replace koreader/frontend/apps/cloudstorage/webdavapi.lua with the attached (remove txt extension).

[webdavapi.lua.txt](https://github.com/koreader/koreader/files/8768861/webdavapi.lua.txt)

**Comment by tjimofbis** [comment]
it works now

**Comment by d0verenny** [comment]
ver. 2024-11.151 (nightly build, as the stable one doesn't work with Winter jailbreak). Can't save file on my Kindle Paperwhite 10th gen from WebDAV.
