### ISSUE TITLE
Crash when creating a highlight near a page break

### ISSUE THREAD

**Issue by rixx** [koreader/koreader#9133]
* KOReader version: 2022.04
* Device: Kobo Libra 2

#### Issue

I created a highlight starting at the beginning of a page. After releasing the press (starting the highlight save), KOReader jumped back a page. The black "saving" rectangle showed up on the last line of that page. After 5-10 seconds, KOReader crashed and my device rebooted.

Memory use was still pretty low, as I had recently rebooted.

#### Steps to reproduce

No easy reproduction I found (after the reboot, the same highlight worked alright). Notably, KOReader was lagging on a recent page turn, but was back to being responsive when I created the highlight.

##### `crash.log` (if applicable)

Checked the crash log, but the last line was just the note that my latest book was opened.

**Comment by poire-z** [comment]
Probably the Libra2 issue #8414 with our little markers in the left margin (one is shown when you're done with a highlight across pages, to show you the position you were starting the highlight at when restoring to the previous page).

This should have been worked around by disabling these little markers on the Libra2, by b2ef81527b1e82f #8775, which should be in v2022.02.
You mention you're using v2022.04, but we didn't make a v2022.04.
So, update to the recent v2022.05.1 release if needed.
And check that in your settings.reader.lua, you indeed have `["followed_link_marker"] = false,` (that a migration should have created on Libra2) - and if not, add it manually (beware comma at end of each setting, except on the last one), and see if this helps.

**Comment by poire-z** [comment]
Closing as related to the other Libra2 issue (and no feedback about KOReader version and the absence/presence of the setting).
