### ISSUE TITLE
FR: Android Launcher

### ISSUE THREAD

**Issue by uroybd** [koreader/koreader#9134]
**I understand that it is a long shot and maybe something that will never be implemented.**

However, I have toyed with flutter and made a rudimentary launcher that has:

1. A library view (like KOReader) which shows reading progress from metadata generated by a book.
2. An app drawer.

I found that generating cover is the most difficult part. It requires one to have the same libraries the ebook readers use. Lots of dependencies.

Also, KOReader has a very efficient library view, I was just reinventing the wheel.

To make KOReader a Launcher we have to have:

1. The Launcher Intent to be added in the Android build.
2. A Bottom bar with buttons for Library and Apps which is shown only on Android on launcher mode.
3. An Android-only app drawer.

**Comment by uroybd** [comment]
I have to find an efficient way to get the book covers then. 😅

**Comment by pazos** [comment]
Revisiting this, from #12626

> I have to find an efficient way to get the book covers then.

@uroybd and other future people interested on this:

It is mostly invented :). There's almost  no need to write new code for skecthing a very basic android launcher for documents.

You'll need to have a grid view of documents. A Document holds metadata for a file. You'll need to use `MediaScanner` or a dir iterator to fetch new files. Then get their metatata.

Metadata depends of the filetype. It is usually easier to aim at single "epub" support at first and write a parser that fetches epub metadata from file.

If somebody starts a "home launcher" project that takes care of basic home launcher stuff, and wants to make it document aware, please ping me. I would be happy to help with that particular part.

**Comment by Crescendo-BLYAT** [comment]
Workaround: use [AnyLauncher](https://github.com/tumuyan/AnyLauncher) & lock it to KOreader.
