### ISSUE TITLE
Calibre does not recognize SD card for storage device

### ISSUE THREAD

**Issue by malamazo** [koreader/koreader#9137]
I have recently installed Koreader, and was downloading books fine until the main storage ran out. I would like to use my 64gb card but I cannot access it. How can I solve this? It is fine if I don't use calibre as long as I have a way to put books in the SD Card without taking it out.

**Comment by NiLuJe** [comment]
It's unclear, but I'm assuming you're using the Calibre plugin as a Smart Wireless Device?

Then just set a new inbox to somewhere on your SD card in the settings?

(I'm assuming you are NOT on Android here. ProTip: The issue template *matters*.).

**Comment by malamazo** [comment]
> It's unclear, but I'm assuming you're using the Calibre plugin as a Smart Wireless Device?
> 
> Then just set a new inbox to somewhere on your SD card in the settings?
> 
> (I'm assuming you are NOT on Android here. ProTip: The issue template _matters_.).

Hey, Sorry. I am using a Kobo Clara HD. The inbox folder is mnt/sd/koboExternalStorage

When using calibre it does not allow to send to storage card a or b. It says there is no SD.
.
I have tried switching the Inbox Folder to no avail

**Comment by malamazo** [comment]
> It's unclear, but I'm assuming you're using the Calibre plugin as a Smart Wireless Device?
> 
> Then just set a new inbox to somewhere on your SD card in the settings?
> 
> (I'm assuming you are NOT on Android here. ProTip: The issue template _matters_.).

I have found a solution to the problem I believe. Thanks for the help.

**Comment by NiLuJe** [comment]
Which would be?

**Comment by pazos** [comment]
All text and no real info makes pazos a dull boy.
