### ISSUE TITLE
FR: [Optional system keyboard]

### ISSUE THREAD

**Issue by JasonMa0012** [koreader/koreader#9140]
**Does your feature request involve difficulty completing a task? Please describe.**
The built-in keyboard language support is not complete, such as unable to enter Chinese

**Describe the solution you'd like**
The system keyboard is optional in the Settings

**Comment by JasonMa0012** [comment]
We usually use powerful third-party keyboards and can use voice input, so a built-in keyboard doesn't seem like a wise choice

**Comment by Frenzie** [comment]
> We usually use powerful third-party keyboards and can use voice input

Well no, only on very specific platforms.

Duplicate of #7423.
