### ISSUE TITLE
Some highlights won't export to HTML 

### ISSUE THREAD

**Issue by djtsorrell** [koreader/koreader#9141]
* KOReader version: 2022.05.1
* Device: Kobo Libra H2O

I've been trying to use the export highlights plugin to get my annotations in an HTML format. So far, only three of my books have had their annotations exported to HTML format in the `.adds/koreader/clipboard` folder, but there are many missing. I have tried the "exporting all notes in your library" and "... in this book" options, but neither seem to be effective. All that happens is a pop up which says it's exporting, which promptly disappears, with no new files in the clipboard directory. I have both epub and pdf books which I would like to export.

Note: I have also tried exporting to plain text and json files, but again, nothing seems to happen.

**Comment by toxayu** [comment]
- KOReader version: 2022.05.1
- Device: Kobo Libra 2

I have the same problem exporting my highlights via any way. It only happens after I upgrage Koreader to the newest version.

Now I need to downgrade to the previous version for my urgent highlights export task.

**Comment by Frenzie** [comment]
Could you see if it's resolved by https://github.com/koreader/koreader/pull/9130?

In update, settings you can opt for the development channel if you want to test it, or overwrite the changed files yourself.

**Comment by djtsorrell** [comment]
I can confirm that all is working as expected after updating to the development channel (v. 2022.05.1-10). Although, there is still no prompt to say where the files are saved, which may be helpful to those who don't already know the directory (especially as it's in a hidden folder). I will close the issue as resolved. Many thanks for your help!

**Comment by toxayu** [comment]
After update to the devolop version, highlights can be output correctly.
But iprompting a finish messenger as the old version would be better for
users to check the exporting.

djtsorrell ***@***.***> 於 2022年5月29日 週日 下午4:44 寫道：
