### ISSUE TITLE
EPUB Chinese vertical text

### ISSUE THREAD

**Issue by xiaoyuzz** [koreader/koreader#9147]
[https://zh.cn1lib.club/book/18766984/6cdfaa](url)
书名資治通鑑（典藏本）繁體豎排294卷全 胡三省註【毛泽东一生读了十七遍的资治通鉴版本！业内首次使用四种辅助线对全书近百万处人名、地名、书名进行区别标识！修正旧版错漏近一万三千处！权威注解！全网独家！阅读再升级！】 (Traditional_chinese Edition)

这本书在kindle上为AZW3  为竖排繁体  用calibre转换为EPUB后 放到koreader里面 就变成乱七八糟的排版了。。。。。。。。。
请问如何排版能让书正常显示？

**Comment by xiaoyuzz** [comment]
使用的版本为KOReader 2022.05.1
设备为富士通QUADERNO A4 GEN2（android9.0）

**Comment by Frenzie** [comment]
Vertical text is not supported, but some people have used a rotated font to achieve a similar result: https://github.com/koreader/koreader/issues/4353#issuecomment-561681468

**Comment by xiaoyuzz** [comment]
> Vertical text is not supported, but some people have used a rotated font to achieve a similar result: [#4353 (comment)](https://github.com/koreader/koreader/issues/4353#issuecomment-561681468)

好的 谢谢您 我去查看一下#4353的解决方法，不过话说回来 不能横排切换直排 其实挺不方便的 希望能考虑加入这个功能

**Comment by Frenzie** [comment]
In the meantime, using calibre to convert the document to a PDF in the desired page and font size might also be a viable solution.

Closing in favor of #4353.
