### ISSUE TITLE
FR: Toggle touch by pressing both pageturn buttons

### ISSUE THREAD

**Issue by felleg** [koreader/koreader#9148]
**Does your feature request involve difficulty completing a task? Please describe.**
I can't easily find a way to disable the touch screen, which would allow me to grip my device more comfortably.

**Describe the solution you'd like**
- Pressing both page turn buttons simultaneously toggles the touch functionality

**Comment by pazos** [comment]
Just a few ereaders have physical buttons.
And we don't support actions based on composed keyevents.

Patches welcome.
