### ISSUE TITLE
ireader Smart XS can't use touching function

### ISSUE THREAD

**Issue by AQUOSZZY** [koreader/koreader#9154]
* KOReader version:2022.05.1
* Device:ireader Smart XS based on Android 9

In file browser, the touching function is all right, but after I open a book, I could only do two things:
1.turn out the bottom menu by swiping from the bottom
2.get screenshot by  swiping from a corner to another corner 

Althought I can't turn the page by tapping the screen, my Smart XS has two button to help me complete my operation.
There are two things I want but can't do:
1.turn out the main menu from the top
2.long-press to select the word 
these things I can do, seems like my devices does not have touchscreen, but in file browser, or other app,  touchscreen does normaly work.

**Comment by AQUOSZZY** [comment]
Thank you for your reply！Does it mean that the problem cannot be solved from the koreader software itself?  And the system restricting touch operation? But the strangest thing is that I can take a normal screen shot in a document by sliding diagonally, and I can call up the bottom menu by tapping on the bottom.
Is it possible that koreader automatically recognizes this device as a non touch screen e-paper book such as the Kindle2?

**Comment by Frenzie** [comment]
> Does it mean that the problem cannot be solved from the koreader software itself?

Just a hypothesis based on your description. ^_^

> Is it possible that koreader automatically recognizes this device as a non touch screen e-paper book such as the Kindle2?

No, however if you look at https://github.com/koreader/koreader/issues/8482 we may be able to support it properly.

**Comment by AQUOSZZY** [comment]
https://user-images.githubusercontent.com/104625197/171614717-f6e16ff4-d841-4931-baaf-b3e2ac13b8be.mp4

**Comment by AQUOSZZY** [comment]
https://user-images.githubusercontent.com/104625197/171616844-0fff20bb-0918-4bcb-8253-c29ad29582e3.mp4


https://user-images.githubusercontent.com/104625197/171616938-8c7689ee-f9e9-49a5-993e-fffcd3685c63.mp4
I repeated the operation problem in the video

**Comment by AQUOSZZY** [comment]
https://user-images.githubusercontent.com/104625197/171617364-50b34cca-dc1e-4450-bd90-44b0a76b51bc.mp4

This video shows how screenshot function work

**Comment by pazos** [comment]
@AQUOSZZY: try https://github.com/koreader/koreader/issues/4430#issuecomment-450594508

**Comment by AQUOSZZY** [comment]
> @AQUOSZZY: try [#4430 (comment)](https://github.com/koreader/koreader/issues/4430#issuecomment-450594508)
Thank you, I have tried it but this method does not work on my devices.
I want to try[https://github.com/koreader/koreader/issues/8482],but I can't find this option
 "Tools" -> "More Tools" -> "Developer options" -> "Start compatibility test"

**Comment by AQUOSZZY** [comment]
Becase I can't turn out the top menu, so I run Koreader on my Android phone, use "Tools" -> "Profiles" to creat a profile witch is "Autostart" with "Show menu", and onnect to the computer, overwrite the file copy in the entire koreader folder under the root directory of the mobile phone to the corresponding Koreader folder on my smart XS, and then open the Koreader on the smart XS. After that, an Koreader crashed
![image](https://user-images.githubusercontent.com/104625197/171629051-5d9a8999-75b7-453e-bd9b-0bfaa9a729cd.png)

**Comment by AQUOSZZY** [comment]
I think that means if I try to turn out the top menu, something wrong

**Comment by AQUOSZZY** [comment]
[crashed.txt](https://github.com/koreader/koreader/files/8823768/crashed.txt)
![image](https://user-images.githubusercontent.com/104625197/171631224-f10d7d34-b0f8-42a4-93f7-fa11730cc377.png)
![image](https://user-images.githubusercontent.com/104625197/171631279-daf769fb-161c-4677-b90b-4fb2b1b960c8.png)
After crash a .html file was generated. Github can't upload .html so I upload a .txt and screenshot

**Comment by pazos** [comment]
No response. Closing as won't fix.

**Comment by nextzhou** [comment]
I have the same issue. ireader xs blocked developer mode. So I can't provide you with debug logs.

**Comment by superliujian** [comment]
@pazos 
I have the same problem, and I found this issue is closed as the requestor didn't provide debug info, is possible repoen it (or create a new one)  as I could help to provide debug info?

**Comment by superliujian** [comment]
I opened another similar issue , see #10293

**Comment by mrdylanyin** [comment]
In my case, I can rotate the device 90 degrees and then enter into Koreader. Then all the functions seem to work correctly. The issue occurred after upgrading the Ireader system. Perhaps, the Ireader system added an abstract layer to the rotate function?

**Comment by ninggu2008** [comment]
> In my case, I can rotate the device 90 degrees and then enter into Koreader. Then the touch functions seem to work correctly. The issue occurred after upgrading the Ireader system. Perhaps, the Ireader system added an abstract layer to the rotate function?

果然，横屏的时候打开触摸功能就一切正常了。我是smart2，koreader和电纸书固件都是最新。

**Comment by plateaukao** [comment]
Fixed in my fork, and binary is here: https://github.com/plateaukao/koreader/releases/tag/ireader-v2026.07
