### ISSUE TITLE
FR: Flat file view?

### ISSUE THREAD

**Issue by strider72** [koreader/koreader#9156]
I keep books in folders by Author name, all inside a "books" directory, e.g. `/books/Clarke, Arthur C`. /books/ is the Home folder.

I would love to have a view that "flattens" the Home folder. That is, it sees everything insider all those folders and shows it all in one big list, rather than having to go in and out of each author folder.

Yes, I know I could move all the books out of the author folders, but it's often very handy to have them sorted out. I want both options just by switching the view.

**Comment by Frenzie** [comment]
I think there may be an issue about some ideas to generate alternative views based on the CoverBrowser database (which would be the only sane/performant way to do something like this).

There's also the calibre collection stuff btw. I forget how it works, @NiLuJe might know some references.

**Comment by NiLuJe** [comment]
If you use Calibre to send books to your devicee, then, yeah, the Calibre plugin's metadata search feature allows you to browse by basic metadata (e.g., tag/author/title/...), which sorta do something like that, although in a much more barebones view than the full FM.

**Comment by peterstamps** [comment]
See plugin for this at https://github.com/peterstamps/All_eBooks_in_single_flat_view_on_KOreader
