### ISSUE TITLE
Crash when deleting words in Vocabulary builder

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9162]
* KOReader version: v2022.05.1-14
* Device: PB 628

#### Issue
While trying to delete a word in the new plugin "Vocabulary builder" a crash occurred.
I give you the crash file
_(deleted)_

**Comment by ichnilatis-gr** [comment]
I would like to point out that the problem only happened with only a few words, not all of them.

**Comment by weijiuqiao** [comment]
Thanks! The bug is being fixed with #9168.
