### ISSUE TITLE
exporter.koplugin improvements

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#9164]
After the great work made by @uroybd.

Mostly self-instructions but I wouldn't mind if somebody else (wink wink) implement some of them :smile: 

Things that users reported as missing vs the previous implementation:

1. ~~after the infoMessage "exporting might take a while" provide a summary of what was exported (and where). It should contain the path to exports if at least one local exporter is enabled. It should also take advantage of the boolean nature of `export` function to report issues exporting.~~

Things that users requested:

1. Hook export document highlights / export all highlights into the dispatcher and add them to gestures. The new "share document highlights" can be hooked too.

Things that I would like:

1. ~~Pretty-print in the json output.~~

~~Related issues that would be awesome to be addressed: https://github.com/koreader/koreader/issues/6974~~

**Comment by uroybd** [comment]
Pretty print should be easy (I guess). I'll work on that first.

**Comment by uroybd** [comment]
@pazos 

Here comes Pretty JSON: #9165

**Comment by uroybd** [comment]
And here is info messages:  #9166

**Comment by uroybd** [comment]
@pazos 

I'm very much interested in #6974 and I need some guidance.

We should get the title, authors, and other metadata from the file and use the filename only as a fallback. Is there any interface in document engines (e.g. crengine) to do that? If so, I think we should get that and cache them in the sidecar.

**Comment by Frenzie** [comment]
Did you check to see if they're not already in there? ;)

**Comment by poire-z** [comment]
The metadata (the same as used bu Book information) is already saved in the docsettings on each book opening:
https://github.com/koreader/koreader/blob/aa4cc6da56d7b5b7f51944a317ada0b2978549a1/frontend/apps/reader/readerui.lua#L453-L456

**Comment by uroybd** [comment]
> The metadata (the same as used bu Book information) is already saved in the docsettings on each book opening:
> 
> https://github.com/koreader/koreader/blob/aa4cc6da56d7b5b7f51944a317ada0b2978549a1/frontend/apps/reader/readerui.lua#L453-L456

Aha! Looking at the wrong place. Thank you. I'll try to use this in export. 😄

**Comment by pazos** [comment]
@WolfgangDpunkt

a gui makes sense and is easy to implement but I have no idea where to place it. Maybe under formats and services?

**Comment by uroybd** [comment]
> @WolfgangDpunkt
> 
> a gui makes sense and is easy to implement but I have no idea where to place it. Maybe under formats and services?

Maybe a top-level menu entry. I don't think many will export different formats to different directories.

**Comment by WolfgangDpunkt** [comment]
> Maybe a top-level menu entry.


Thank you for your comments! Yes, that is a good idea. As with the Wikipeda plugin, I would suggest offering the directory listing at the top level.

And by the way, could I ask you as experts which line of code I can modify in order to change the directory to a selected desired path already now? Thank you very much!



<img src="https://user-images.githubusercontent.com/35533844/176618896-693d7e78-36d2-486c-9897-83649639ef2b.png" width=50% height=50%>

**Comment by uncharted-user** [comment]
Is is correct that Bookmark with Highlight sync is not available for multiple devices in KOReader similar to Kindle app? I am aware of KOHighlight, Progress sync, Export highlights.

**Comment by pazos** [comment]
All done (a long time ago) :p
