### ISSUE TITLE
Many fb2.zip books cannot be opened.

### ISSUE THREAD

**Issue by LazyCat-DS** [koreader/koreader#9172]
* KOReader version: v2022.05.1
* Device: Kinde PW5

#### Many fb2.zip filws cannot be opened
For example attached file cannot be opened with koreader while CoilReader and some other prorams can open it.
More of same files can be found on [http://fantasy-worlds.org/series/id4876/](http://fantasy-worlds.org/series/id4876/) - this and some others series. Many books from same site can be opened, many - not.
#### Steps to reproduce
Just try to open and get error.

[Орлов_-_Плот-призрак.fb2.zip](https://github.com/koreader/koreader/files/8840303/_-_.-.fb2.zip)

**Comment by pazos** [comment]
The file opens fine here (on the emulator). Please check if is not something related to file's filename (ie: rename `_-_.-.fb2.zip` to `test.fb2.zip` and try to open again).

**Comment by LazyCat-DS** [comment]
Actual file name is Орлов_-_Плот-призрак.fb2.zip (russian characters).
And sorry, this file opens, my bad - thout if there is no image for it file is not opening. Can you consider to add some different icons for files without images and for files than cannot be opened?
Attaching file wich is really not opening on kindle ([source](http://fantasy-worlds.org/lib/id23572)):
[01. Orlov_Aleks_[Tomas_Breyn_1]_Igra_bez_pravil.zip](https://github.com/koreader/koreader/files/8840350/01.Orlov_Aleks_.Tomas_Breyn_1._Igra_bez_pravil.zip)

**Comment by pazos** [comment]
That file opens fine too once you rename from .zip to zip.fb2

**Comment by LazyCat-DS** [comment]
Damn, I'm not figured this. CoolReader open them do not relaying on extension (maybe because inside zip file is fb2 file, and this is enough for it).
Now I have big problem - 1127  files to rename, in 476 folders or so :-(
Is there any chances that koreader will handle such files without renaming first?

**Comment by pazos** [comment]
nope, the filemanager opens files by extension

**Comment by LazyCat-DS** [comment]
That's bad (for me).
