### ISSUE TITLE
FR: Tolino Vision 5 buttons dont invert based on rotation

### ISSUE THREAD

**Issue by hasezoey** [koreader/koreader#9175]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently the buttons on a `Tolino Vision 5` do not invert based on document view rotation

**Describe the solution you'd like**
Option to enable invert of tolino's buttons (based on rotation and maybe manually)

**Describe alternatives you've considered**
From what i can tell, there is also currently no button to invert the buttons manually (at least i have not found a setting)

**Additional context**
I am still new to koreader and i use it now on my Tolino Vision 5 (Android 4.4), where koreader is installed through F-Droid, koreader version is `2022.05.1`

I have also already tried the options `Tap and Gestures > Page turns > Invert page turn buttons`, which did not seem to affect the Button page turn

~~Also i have noticed that the manual Rotation is only for the Document Viewer and when going back to the file browser it de-rotates again, is this intentional?~~ found setting "Keep orientation across Views"

PS: is it currently possible to have automatic rotation (preferably asked before rotation) based on the gyroscope? (if available)

Update: from what i can tell, the `Tolino Vision 5` is more or less the same as `Kobo Libra H2O`

**Comment by NiLuJe** [comment]
Possibly Android specific, because IIRC, that works just fine in embedded-Linux land ;).

**Comment by hasezoey** [comment]
> Fair warning: I have no idea how this device looks, and which buttons it actually has, and where.

The Manufacturer site is [tolino vision 5](https://mytolino.com/products/tolino-vision-5/) and the first page is how (i) use it most commonly, but sometimes i just rotate it 180°, but the buttons dont invert

Note: i have (somewhat) confirmed that these 2 buttons are the volume buttons, but they dont invert when rotation changes

**Comment by hasezoey** [comment]
i have updated the title and issue based on what i had found (the buttons do not in fact seem to be volume buttons, but i dont know what else these buttons are or how to find it)

**Comment by hasezoey** [comment]
if anyone could tell me how to get the required information which would actually be useful (to know what buttons the Tolino uses), i would like to provide it

(adb or what app to use to test buttons, needs to be something that works in android 4 and is preferably less than 50mb after installation (the device does not have much app storage))

PS: currently with koreader 2022.07 the buttons still dont work (though i did not really expect anything to have changed)

**Comment by mergen3107** [comment]
@hasezoey 
Try Button Mapper app. You can detect any buttons and re-assign them. Try assigning something generic there and then using those in KOReader's reassignment

**Comment by hasezoey** [comment]
> Button Mapper app

where is that available to download in apk form? (is it google play only?)

**Comment by hasezoey** [comment]
> Try Button Mapper app

i tried version 3.09, but it would not launch, so is there another good way?

**Comment by hasezoey** [comment]
some information i missed from the original report:
KoReader compat test:
- Device already supported
- EPD: freescale
- Lights: tolino
- Test Lights (Tolino (warmth)): frontlight setting works, warmth does not
- Test E-ink (Freescale/NTX): Refreshes screen
Device Info:
- Manufacturer: rakuten kobo inc.
- Brand: rakutenkobo
- Model: tolino
- Device: ntx_6sl
- Product: ntx_6sl
- Hardware: e70k00
- Platform: imx6

---

Misc info:
- Android version: 4.4.2
- Kernel: 3.0.35

**Comment by mergen3107** [comment]
@hasezoey 
Try here: https://4pda.to/forum/index.php?showtopic=807930

**Comment by mergen3107** [comment]
Works for me though

**Comment by mergen3107** [comment]
It says it needs Android 4.3 at least...

**Comment by hasezoey** [comment]
in case it helps, the following gets returned when doing `adb shell` then `getevent` and pressing the "down" button:

```txt
// keydown
/dev/input/event0: 0001 00c0 00000001
/dev/input/event0: 0000 0000 00000000
// keyup
/dev/input/event0: 0001 00c0 00000000
/dev/input/event0: 0000 0000 00000000
```

and the "up" button:

```txt
// keydown
/dev/input/event0: 0001 00bf 00000001
/dev/input/event0: 0000 0000 00000000
// keyup
/dev/input/event0: 0001 00bf 00000000
/dev/input/event0: 0000 0000 00000000
```

**Comment by mergen3107** [comment]
@hasezoey 
Here is an archive with the apk inside, if you still wanna try. Works well on my Onyx Boox Kon-Tiki 2 (a la Nova 3 without a Wacom layer).
[Button+Mapper_v3.09(309).zip](https://github.com/koreader/koreader/files/9489498/Button%2BMapper_v3.09.309.zip)

**Comment by hasezoey** [comment]
As another update the following is from logcat with debug mode in KoReader:

(first pressed the `down` key, then the `up` key)
```txt
D/InputManager-JNI( 2470): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
V/KOReader( 8885):  key event => code: 22 (Right), value: 1, time: 159605.230000
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x64809f80,"Thread-1097"] attached without supplying a name
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x648060f0,"Thread-1098"] attached without supplying a name
D/PhoneWindowManager( 2470): mPstate.get() = 1
D/InputManager-JNI( 2470): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
V/KOReader( 8885):  key event => code: 22 (Right), value: 0, time: 159605.350000
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x647f48f8,"Thread-1099"] attached without supplying a name
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x647f1558,"Thread-1100"] attached without supplying a name
D/PhoneWindowManager( 2470): mPstate.get() = 1
D/InputManager-JNI( 2470): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
V/KOReader( 8885):  key event => code: 21 (Left), value: 1, time: 159605.930000
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x647c10b8,"Thread-1101"] attached without supplying a name
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x64867710,"Thread-1102"] attached without supplying a name
D/PhoneWindowManager( 2470): mPstate.get() = 1
D/InputManager-JNI( 2470): [void android::NativeInputManager::handleInterceptActions(jint, nsecs_t, uint32_t&) 877]
V/KOReader( 8885):  key event => code: 21 (Left), value: 0, time: 159606.060000
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x64848928,"Thread-1103"] attached without supplying a name
W/art     ( 8885): Thread[10,tid=8902,Native,Thread*=0x550a8c88,peer=0x6483b8f0,"Thread-1104"] attached without supplying a name
```

so it seems like KoReader sees these buttons as 22 and 21, which currently map to `DPAD_LEFT` and `DPAD_RIGHT`

---

after some testing setting the following and re-packaging makes "Invert Page Turn Buttons" work correctly, though still not automatically on rotation change:

`frontend/device/android/event_map.lua`
```diff
-    [21] = "Left",  -- DPAD_LEFT
-    [22] = "Right", -- DPAD_RIGHT
+    [21] = "LPgBack",  -- DPAD_LEFT
+    [22] = "LPgFwd", -- DPAD_RIGHT 
```
