### ISSUE TITLE
Ext dictionary app picker always shows app selection dialogue since koreader 2021.06

### ISSUE THREAD

**Issue by norbi24** [koreader/koreader#9178]
* KOReader version:  2021.06 - 2022.05
* Device: BOOX Poke2 (but also on Samsung S7 mobile, Android 8.0.0)

#### Issue
While using an external dict app (not directly supported by Koreader) using customized dictionaries.lua file like this:

return {
{ "Send", "Choose Dict by App picker (send action)", true, nil, "send"
},
{ "Search", "Choose Dict by App picker (search action)", true, nil, "search"
},
{ "TextProcessing", "Choose Dict by App picker (text processing action)",
true, nil, "text"
},
}

(implemented with this PR  https://github.com/koreader/koreader/pull/5664 by Pazos)

up to KOReader 2021.05 on selecting a word it offered an app picker dialogue with the possibility, to mark an app
per "use always" so with all next translations, the dict app is immediately started after selecting a word.
But starting from Koreader 2021.06 it basically works, but in the app picker there is NO use always option, so one needs to 
always go through this app picker dlg to select the dictionary app.

#### Steps to reproduce

1. Take the lua snippet from above and save it as dictionaries.lua into KOReader folder
2. Start KOReader, select Use external directory, and select "Choose Dict by App picker (send action)"
3. Now open any epub, select a word and see the app picker dialogue:
   a.) With koreader up to 2021.05, you can select "use always" 
   b.) From 2021.06 no "use always" option, you always need to go through the app picker on each translation

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by pazos** [comment]
Hi, thanks for the bug report.

Looks easy to fix. I will upload a build that hopefully fixes the issue. We just need to decouple the dictionary lookup methods from the share text ones.

**Comment by pazos** [comment]
@norbi24: I hope mega is ok for you. My dropbox account is full of crap :/

Please check if this build fixes your issue. It is totally untested and just left the roaster. It should behave but if you tell me that it crashed I won't be surprised ;)

https://mega.nz/file/Gi5yjaIB#gyN62GjFLF5jarR-NHxUsR3mpTLfYSRwte20p0CivCo

Please do the usual dance: uninstall the app before installing this one.

**Comment by norbi24** [comment]
@pazos, thanks a lot, I have just tried it and it works as expected !
