### ISSUE TITLE
How can I modify arrow of page overlap function?

### ISSUE THREAD

**Issue by omer-faruq** [koreader/koreader#9181]
When I read PDFs with two columns page overlap function makes it better to read docs. I  want to add some white and black border to arrow to make it more visible at first sight .  Where can I find it? is it customizable?  Is there a way to do this? Thanks .
![Arrow](https://user-images.githubusercontent.com/85738646/172467866-9fc245de-4847-4602-8473-a4bdf48cba1c.png)

**Comment by poire-z** [comment]
There is not setting for this in the menus, the icon and size are hardcoded.

Currently, you could just override the icon used (control.expand.alpha) with something different, which must be a SVG file, that you could drop in a (create this directoty) koreader/icons/ by giving it the name control.expand.alpha.svg.
It will still have the current small size.
![image](https://user-images.githubusercontent.com/24273478/172467393-fd947da2-71fe-4875-a79a-9c060633d811.png)

https://github.com/koreader/koreader/blob/5bcd3d0962f4d62a66f5fe62b1276dc0ef7fae47/frontend/apps/reader/modules/readerview.lua#L114-L120

Once #9104 is merged (soon), you could hack the above bit code that builds the thing to give it another name and size. Something like this, put in `patches/2-my-overlap_arrow.lua` could work:
```lua
local IconWidget = require("ui/widget/iconwidget")
local ReaderView = require("apps/reader/modules/readerview")
local addWidgets_orig = ReaderView.addWidgets
ReaderView:addWidgets = function(self)
    -- Run original code
    addWidgets_orig(self)
    local arrow_size = Screen:scaleBySize(16 * 2)
    self.arrow = IconWidget:new{
        icon = "the_name_of_my_svg_file",
        width = arrow_size,
        height = arrow_size,
        alpha = true, -- or false, if you don't want transparency with your big solid black icon
    }
end
```

**Comment by omer-faruq** [comment]
thanks for the reply, I'll try the modify the image control.expand.alpha , also the size.

**Comment by omer-faruq** [comment]
I made two modifications: 1- fill background with solid white, 2- made arrow %100 black: 
![control expand alpha](https://user-images.githubusercontent.com/85738646/173128594-90492c47-4c50-4022-b8d6-05475db8942d.svg)

**Comment by poire-z** [comment]
> also created the user patch file 

Feel free to share its code here :)

**Comment by omer-faruq** [comment]
Oh, I mean with the code you already shared 
( didn't test it yet )

[2-overlap_arrow_32.lua.txt](https://github.com/koreader/koreader/files/9035095/2-overlap_arrow_32.lua.txt)

**Comment by poire-z** [comment]
Oh, right, I posted some code :) I haven't tested it, I see that it is missing something at top:
`local Screen = require("device").screen`
(still not tested :)

**Comment by omer-faruq** [comment]
To test the user patches I switched  to Developer Upgrade mode,  When  It restarts it said :

```
Error appying patch:
 ./pathes/2-overlap_arror_32.lua 
```
Unfortunately I don't know how to look at the error logs if any.

**Comment by poire-z** [comment]
there should be a file `koreader/crash.log` in which there may be more details (it's actually just the full log)

**Comment by omer-faruq** [comment]
It says:
_WARN  Patching failed: ./patches/2-overlap_arrow_32.lua:5: function arguments expected near '='_

5th line:
`ReaderView:addWidgets = function(self)`

**Comment by poire-z** [comment]
Right. Replace this `:` with `.`, beween `ReaderView` and `addWidgets`
`ReaderView.addWidgets = function(self)`

**Comment by omer-faruq** [comment]
Yes  now it doesnt display an error , however on pdf I see an error image instead of arrow :

![IMG_1315](https://user-images.githubusercontent.com/85738646/177052562-14cce092-bd2c-42e0-9134-5b59b85b8c56.jpg)

in code I write the name as : "control.expand.32.svg"
and placed the icon in the same directory as the original icon : 

![image](https://user-images.githubusercontent.com/85738646/177052612-cd42e2c0-0bb5-47f1-b6de-6e7e88ad1ebe.png)
