### ISSUE TITLE
Koreader Pocketbook and borrwoed books

### ISSUE THREAD

**Issue by Bruninho81** [koreader/koreader#9184]
Hello everyone,

first of all, please excuse my bad english. I have a problem with Koreader and a Pocketbook (3 Pro) and I would appreciate if you could please help me. The installation worked fine and I was able to open Koreader and set it up as I wanted. There were several folders that were divided by language. 
I opened the "Deutsch" folder and found a couple of German books in there that were easy to open. So far everything has worked fine.
There is also an application on the Pocketbook called "Onleihe". I can borrow books from the local library there. In the Koreader, these books appear in the "Downloads" folder.
Now the problem begins: If I open one of the borrwoed books, a page opens, but it is empty. The number of pages is also not given below. It only says 1/0. In the "Downloads" folder, the book title is not followed by the number of pages, but by "%1 pages".
I copied one of the borrowed books from the "Downloads" folder to the other books in the "Deutsch" folder. But after open it, there is a empty page.
Did I miss something, or did I even do something wrong, or is it generally not possible for Koreader to open borrowed books?

Thank you!

Bruno

**Comment by Frenzie** [comment]
> is it generally not possible for Koreader to open borrowed books?

If they're encrypted, that's indeed unlikely I'm afraid.

**Comment by Bruninho81** [comment]
Thank you for your prompt reply. As far as I know, the borrowed books have some sort of DRM protection, but I can read them normally on the Pocketbook using the Adobe account. Do you mean that this kind of protection doesn't make it possible to open with Koreader?

**Comment by Frenzie** [comment]
Indeed, that's currently not supported. I don't think anybody has any plans to either.

**Comment by poire-z** [comment]
> I don't think anybody has any plans to either.

Before anybody get a plan, first, would this really be possible?
The plan with DRM is that no other software that the thing handling the Digital Rights should be able to open it, no? So, KOReader shouldn't be able to open it, even if we wanted to? And if we technically could, may be we are a good citizen and don't want to be involved with breaking these laws/rights.

All that aisde :) technically... could we ?
Couldn't we `ffi.load(libadobe-dll.so)` and `ffi.hack(gimme_the_content)` ?

**Comment by Frenzie** [comment]
> All that aisde :) technically... could we ?

Probably: https://indefero.soutade.fr/p/libgourou/

**Comment by NiLuJe** [comment]
That eats a separate device license, FWIW, so it's not entirely the sake ;).

**Comment by Frenzie** [comment]
It's pretty much the only approach that (maybe) makes sense from a practical and legal pov, should someone wish to spend time on it. ^_^

**Comment by NiLuJe** [comment]
Definitely!

(there's also a calibre plug-in using a python implementation that is also very "helpful" in liberating one's purchases ;)).

**Comment by poire-z** [comment]
So, probably best left to external tools - than getting involded in Digital Rights Mess.
