### ISSUE TITLE
"Communication with server failed. " if wallabag server url ends with /

### ISSUE THREAD

**Issue by rever1and** [koreader/koreader#9187]
I think it's not a FR or a BUG, but it confused me for a long time.

I deployed a wallabag server in subdirectory like http://koreader.rocks/wallabag/ then I think I should write down this in wallabag.

However, the last `/` will just make it not work at all.

I've tried with app.wallabag.it and my self-hosted wallabag instance, all suffered from this problem.

Despite one can check the source and guess what happened like me, or open and  inspect the log to debug this problem, I think it can be better integrated by handle this situation in the plugin or warning in the UI.

**Comment by Frenzie** [comment]
Sounds like a bug to me. :-) Btw, is that also what you get if you copy the URL from the addressbar?

**Comment by rever1and** [comment]
> Sounds like a bug to me. :-) Btw, is that also what you get if you copy the URL from the addressbar?

Yes. But maybe it is related to the way I deploy wallabag, the nginx rule.

![Screenshot from 2022-06-09 19-15-58](https://user-images.githubusercontent.com/53398061/172834624-03fe89e5-bb1c-4c54-84e8-072edc70c8b2.png)

**Comment by clach04** [comment]
I hit this too, and also from copy/pasting URL (I tried out a trial at wallabag.it).
