### ISSUE TITLE
KOReader Startup crashed on Onyx Boox Poke 4

### ISSUE THREAD

**Issue by zyazhb** [koreader/koreader#9196]
* KOReader version:  KOReader 2022.05.1
* Device: Onyx Boox Poke 4

#### Steps to reproduce

just run KOReader 
KOReader crashed

##### `crash.log` (if applicable)

--------- beginning of system
06-11 15:46:17.400 V/ActivityThread( 2909): reportTopResumedActivityChanged - > onActivityTopResumed

**Comment by mergen3107** [comment]
Is the log file complete?
Is this a fresh install or an update? Try going to Settings, Apps and deleting cache for KOReader

**Comment by zyazhb** [comment]
> Is the log file complete? Is this a fresh install or an update? Try going to Settings, Apps and deleting cache for KOReader

1. This is all the message on crashed window. 
2. This is a  fresh install (cause I just bought my device the first day),  I have reboot and tried to deleting cache, but not work at all.

BTW, I tried to enter the test view and succcess, the light ctrl not work, the screen driver seems works well after i changed it to onyx

**Comment by pazos** [comment]
Hi.

Please report the issue to Onyx. They're able to fix whatever bug they've introduced and broke compatibility with Android.

We cannot address issues that are not reproducible on *real* android devices, other than the few specific issues covered in https://github.com/koreader/koreader/issues/8482
