### ISSUE TITLE
Crash on start on Pocketbook Inkpad X

### ISSUE THREAD

**Issue by lauriciu** [koreader/koreader#9199]
* KOReader version: v2022.05.1
* Device: PB1040 (Pocketbook Inkpad X)

#### Issue
When I turn on the ereader, the crash log appears without me touching anything, almost every time. 
My suspicion is that koreader tries to open automatically for some reason and if this is the case, how can I stop this?
Here is part of the crash log and then the full file from today:

  Current time: 06/11/22-16:23:22
  Version: v2022.05.1

ffi.load: blitbuffer
ffi.load: inkview
06/11/22-16:23:22 INFO  SoftwareVersion:  U1040.6.5.1701
Atached mp shm: id 0 addr a6f9c000 size 17616
attach_shm: mtfb key=251348987 size=2808848
Atached mtfb shm: id 12000a addr a4181000 size 2808848
-------------------------
Starting task - koreader.app
flags: 0x00000080
gpid: 2043
fb=0xa4181000 xres=1404 yres=1872 scanline=1408 vdepth=8 orient=0
-------------------------
attach_shm: mttempfb key=251308714 size=2665728
Atached mttempfb shm: id 8001 addr a3ef6000 size 2665728
Atached mqueue: id 8001
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
program_name = [./luajit], basename = [luajit], init_string = [/P7.Sink=Null /P7.Pool=128 /P7.Format="{%ts}[%fs:%fl] %lv %ms"]
program init string = [(null)]
default init string = [(null)]
[hw_setglobalkeymask] gka0 = 4000002; gka1 = c800002; gka2 = 0
OpenTheme: /ebrmain/themes/Line.pbt
Theme real name: Line
ts: loading default calibration values
TOUCHMATRIX: 0 10000 0 0 0 10000
attach_shm: mtfb key=251348987 size=2808848
Atached mtfb shm: id 12000a addr a2748000 size 2808848
[2048 : ./luajit] (hw_nextevent)mq_receive ret -1 (Resource temporarily unavailable)
ffi.load: inkview
ffi.load: librt.so
ffi.load: inkview
ffi.load: inkview
06/11/22-16:23:23 INFO  initializing for device PB1040
06/11/22-16:23:23 INFO  framebuffer resolution: {
    ["h"] = 1872,
    ["w"] = 1404,
}
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
06/11/22-16:23:23 INFO  opening file /mnt/ext1/SendToPb/BBC News  Sat  11 Jun 2022 .epub
CRE: font Odinson Light regular: updated weight from 300 to 400
06/11/22-16:23:24 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
06/11/22-16:23:24 WARN  Terminal: can not open /dev/ptmx: Permission denied
06/11/22-16:23:24 WARN  Error when loading plugins/terminal.koplugin/main.lua
06/11/22-16:23:27 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
06/11/22-16:27:29 INFO  Inhibiting user input
06/11/22-16:27:35 INFO  Restoring user input handling
06/11/22-16:27:36 INFO  GestureDetector:probeClockSource: Touch event timestamps appear to use CLOCK_REALTIME
./tar: gcide: Cannot change mode to rwxrwxr-x: Operation not permitted
./tar: Exiting with failure status due to previous errors
06/11/22-16:28:18 INFO  Inhibiting user input

[crash.log](https://github.com/koreader/koreader/files/8884427/crash.log)

**Comment by rjd22** [comment]
@lauriciu I have a different device from yours so I cannot replicate it but can you make a picture of the screen your PocketBook is showing when crashing?

**Comment by lauriciu** [comment]
As I said, it happens before I touch anything, as it starts up or maybe when it shuts down. There's no crash with the bomb error screen or anything like that

**Comment by pazos** [comment]
Missunderstanding here. He was talking about the "crash.log" file appearing on PB home. Fixed time ago by updating wiki install instructions.
