### ISSUE TITLE
Kobo Libra 2, nonfunctioning warmth adjustment, physical buttons, warmth adjustment, and incorrect battery state. 

### ISSUE THREAD

**Issue by nevuk** [koreader/koreader#9218]
* KOReader version:2022.05.1
* Device: Kobo Libra 2 

#### Issue
1. Battery state is stuck at 0% and charging. 
2. LED charge light remains on even if charge light is disabled, until KOreader is restarted. 
3. Warmth adjustment does not work.
4. Sleep cover sleep/wakuep events do not work.
5. Page turn buttons do not work.

I've checked and all of these work with the device in Nickel, and a factory reset and using a different setup account both had no effect.  

I installed these with the standard one-click powershell script process which I have previously used. 

Kobo OS version - 
4.33.19611 (910ec6c476, 6/8/22)

(Likely related to these Plato bugs:
Plato immediately crashes with issue #237.  
https://github.com/baskerville/plato/issues/237
https://github.com/baskerville/plato/issues/241
)
#### Steps to reproduce
1. Use one touch install script on some Kobo Libra 2 models (both before and after a factory reset). 
2. Open koreader. 
3. Charging light will remain stuck on and battery status will be 0% and charging. 
4. Try to use physical buttons, adjust the warmth, or use the sleep cover. All fail. 

(Per the Plato issue 241 discussion, different system paths are used for the same overall model for battery and warmth adjustment).
##### `crash.log` (if applicable)
Verbose debug logging on : 
[crash.log](https://github.com/koreader/koreader/files/8911813/crash.log)

**Comment by nevuk** [comment]
> 
[lash.txt](https://github.com/koreader/koreader/files/8912778/lash.txt)

Here you go. Output of ls -lash /dev/input/by-path/ 

It's a brand new (as in, ordered and delivered within the past week) Libra 2 so it wouldn't shock me if it's one of a new revision.

As far as stability goes, it flips around via ToC just fine with no crashes when I open some books.

**Comment by AndreasTPC** [comment]
Hi,

I bought a new Libra 2 today, and I appear to have gotten this new revision as well. After finding this issue I messed around with it modifying `KoboIo` in `koreader/frontend/device/kobo/device.lua` to see what I could get it to work.

Here's what I found:

* Setting `battery_sysfs = "/sys/class/power_supply/battery",`makes it read the battery level correctly.
* Setting `frontlight_mixer = /sys/class/leds/aw99703-bl_FL1/color` makes the warmth adjustment work.
* When I changed ntx_dev the touchscreen stopped working, so despite the name that one has the touchscreen events in the current config.
* Setting `touch_dev = "/dev/input/by-path/platform-1-0010-event"`keeps the touchscreen working when messing with ntx_dev.
* Setting `ntx_dev = "/dev/input/by-path/platform-bd71828-pwrkey-event",`makes the physical power button work.
* Setting `ntx_dev = "/dev/input/by-path/platform-gpio-keys-event` makes the physical page turning buttons work.

I don't have the sleep cover so can't test things related to that. But let me know if there's anything else I can check for you.

**Comment by poire-z** [comment]
Can Libra 2 old & new users confirms the changes from #9234 fixes everything ?
Replace your `frontend/device/kobo/device.lua` with : https://github.com/koreader/koreader/blob/480598a302b34eb9a87fdeb5fdf3fe5999a0e6d1/frontend/device/kobo/device.lua

**Comment by NiLuJe** [comment]
Oh, hey, wrong `util` module :D.

**Comment by AndreasTPC** [comment]
Yep, after that change it starts, and battery level, power button, page turn buttons, and warmth adjustment all work fine for me.

**Comment by nevuk** [comment]
Can confirm that sleep cover works. 
Gyroscope also now works.

**Comment by NiLuJe** [comment]
> Note - if you experience slow page turns every 3-8 pages, try turning off wifi. This fixed the issue for me on the new HW revision.

@nevuk: That's... interesting ;). Define "slow"?

**Comment by nevuk** [comment]
> > Note - if you experience slow page turns every 3-8 pages, try turning off wifi. This fixed the issue for me on the new HW revision.
> 
> @nevuk: That's... interesting ;). Define "slow"?
May not be related to Koreader, to be honest. I also haven't tried this out on the new config yet, but before it was like this :

Performance was awful wifi on, but with wifi off it was great. This applied to both Koreader and Plato - every few pages it would take about 3-4 seconds to turn to the next the page if the book was sufficiently complex (a single cover image like those on any standard published novel was enough). It wasn't a consistent number, anywhere from 2 to 8 pages before freezing up. Wifi still worked well to connect and transfer books via calibre. With wifi off it was notably faster in koreader/plato than my Aura h2o 2nd edition. Honestly, even Nickel felt sluggish with it on, slow to rotate pages etc.

**Comment by NiLuJe** [comment]
Huh.

There was a weird power delivery hackery going on on older devices where having Wi-Fi enabled was togglign DVFS on (which usually lead to lower frequencies & voltages).

I don't recall DVFS being accessible on Mk. 7, but this *might* be something to look into...

(Might be a red herring, as what i'm talking about required userspace intervention, though, while this doesn't appear to, since we're certainly not doing anything ^^).
