### ISSUE TITLE
kpw4越狱安装问题

### ISSUE THREAD

**Issue by ITquanh** [koreader/koreader#9221]
kpw4，越狱完了以后，装完Koreader，用kual打开，屏幕就闪了一下，完全无法进入，重装kual，Koreader，都不行，这个是什么情况啊？

**Comment by pazos** [comment]
Using chinese (or any other language) is fine. Ignoring the bug template is not.

Please follow the bug template and attach logs **in this ticket**. I will reopen the issue then.
