### ISSUE TITLE
"Sort by last read" gets reset when Kobo Libra 2 reboots

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#9227]
* KOReader version: Nightly from 6/14/22
* Device: Kobo Libra 2

#### Issue
On the Kobo Libra 2, by "last read" works—until the device is rebooted or there is a crash that reboots the Kobo (which is quite often on this device). The order is preserved in the short-term between KOReader restarts and folder changes. (In contrast, a Kindle's device reboot does not reset this last read date.) After the last read dates get reset, the ordering is identical to when you first open KOReader for the first time.

Anyway, let me know if this is a known thing.

#### Steps to reproduce
Set the file browser ordering to "last read". Reboot the device (manually by pressing the button, or by going to the KOReader hamburger menu → Exit → Reboot device, or by having the device reboot-crash).

**Comment by poire-z** [comment]
If this is a really reproducible issue for you, can you try with the v2022.05.1 stable if this was already the case ?

I also got some strange issues since a few weeks on my GloHD - one happened yesterday when after a clean reboot, my current book started with an old page - I moved to my current reading position page, but no matter how clean I exit koreader or load another book, re-opening that book started with this same old page... Until I did another reboot... (and I don't have the offending setting files any longer to guess what might have been happening...)
I suspect #8999 might have missed a few things... (but it's also possible I forgot to update some things in my own patch that end up being at play). Pinging @NiLuJe @zwim if this evoke something on your sides.

**Comment by melyux** [comment]
I tried it on 2022.05.1 stable and the 6/14 nightly, with the same results. For your GloHD issues, that sounds like something else, I think. Very strange.

**Comment by NiLuJe** [comment]
I'll have to check when I get back home, because I can't recall if I sort by last read or last created or something, but I haven't noticed anything wrong on my end.

That vaguely looks like a clock issue on boot, FWIW. Try to make sure nickel has time to do an ntp sync before starting koreader?

**Comment by melyux** [comment]
Just tried rebooting the Kobo. The Kobo base OS clock was correct upon boot. Turned on Wi-Fi (normally wouldn't have it on). Did a manual Kobo sync since it's supposed to trigger an NTP sync too. Launched KOReader. It was still getting reset.

BUT next time I rebooted, my Kobo updated to firmware 4.33.19611 (it had downloaded it when I synced, I was on the previous 4.33.19608). Now KOReader "last read" is preserved across reboots. A surprise, but a welcome one.

I'll close this for now and re-open if anyone notices any further issues. Though I wonder what it is about the firmware update that made it work. I also wonder if it's temporary.

**Comment by poire-z** [comment]
> I also got some strange issues since a few weeks on my GloHD - one happened yesterday when after a clean reboot, my current book started with an old page

Now, even after just switching books and back.
This has happened 3 times over the last weeks. Am I really the only one getting these random strange bugs?

**Comment by Frenzie** [comment]
Nothing in the crash.log?

**Comment by poire-z** [comment]
Nothing special.
We have this:
https://github.com/koreader/koreader/blob/6e647a6f4d739cd55dbcf71dff63ad554499f72c/frontend/docsettings.lua#L155-L156
so it being dbg() I would not see it. But the .old file wasn't removed.
```
-rw-r--r-- 1 5008 Jun 26 01:27 metadata.epub.lua.old
-rw-r--r-- 1 4012 Jun 26 08:59 metadata.epub.lua
```
But it could have been that somehow, the .old file was read (I think I got at the position I was last night).
(The difference in size is that I removed a highlight, but I don't see how this could have any effect.)

**Comment by Frenzie** [comment]
I haven't seen anything strange on my end.

**Comment by poire-z** [comment]
Hijacking this issue to continue on the above occasional issue of mine, old docsettings being read.
I have added some log in my docsettings.lua, to try to get more info next time this would be happening, and it just did, a few times in a row - and a few minutes later I couldn't reproduce it.

```
11/27/22-16:02:32 INFO    rendering took 10.566 seconds
11/27/22-16:02:32 INFO    opening took 15.503 seconds
11/27/22-16:02:41 INFO  DocSettings write /mnt/onboard/.LIBRARY/some book.sdr/metadata.epub.lua
11/27/22-16:02:41 INFO  DocSettings saved /mnt/onboard/.LIBRARY/some book.sdr/metadata.epub.lua

Switching book: the above has some book.sdr/metadata.epub.lua properly written and sync.

11/27/22-16:02:41 INFO  DocSettings read /mnt/onboard/.LIBRARY/Wikipedia/Alains.FR.sdr/metadata.epub.lua
11/27/22-16:02:41 INFO  opening file /mnt/onboard/.LIBRARY/Wikipedia/Alains.FR.epub
11/27/22-16:02:41 INFO  DocSettings read /mnt/onboard/.LIBRARY/Wikipedia/Alains.FR.sdr/metadata.epub.lua
11/27/22-16:02:42 INFO    loading took 0.206 seconds
11/27/22-16:02:42 INFO    rendering took 0.026 seconds
11/27/22-16:02:42 INFO    opening took 0.466 seconds
11/27/22-16:02:43 INFO  DocSettings renamed /mnt/onboard/.LIBRARY/Wikipedia/Alains.FR.sdr/metadata.epub.lua.old
11/27/22-16:02:43 INFO  DocSettings write /mnt/onboard/.LIBRARY/Wikipedia/Alains.FR.sdr/metadata.epub.lua
11/27/22-16:02:43 INFO  DocSettings saved /mnt/onboard/.LIBRARY/Wikipedia/Alains.FR.sdr/metadata.epub.lua

Switching book again, and the .old is read !!!!!!!!

11/27/22-16:02:43 INFO  DocSettings read /mnt/onboard/.LIBRARY/some book.sdr/metadata.epub.lua.old
11/27/22-16:02:43 INFO  opening file /mnt/onboard/.LIBRARY/some book.epub
11/27/22-16:02:43 INFO  DocSettings read /mnt/onboard/.LIBRARY/some book.sdr/metadata.epub.lua.old
11/27/22-16:02:44 INFO    loading took 0.294 seconds
11/27/22-16:02:44 INFO    rendering took 0.043 seconds
```

These are the bits of code where I added some logger.info (lines marked `20221108`)
```lua
    for _, f in ipairs(serials) do
        local directory_updated = false
        if lfs.attributes(f, "mode") == "file" then
            -- As an additional safety measure (to the ffiutil.fsync* calls used below),
            -- we only backup the file to .old when it has not been modified in the last 60 seconds.
            -- This should ensure in the case the fsync calls are not supported
            -- that the OS may have itself sync'ed that file content in the meantime.
            local mtime = lfs.attributes(f, "modification")
            if mtime < os.time() - 60 then
                logger.dbg("DocSettings: Renamed", f, "to", f .. ".old")
                logger.info("DocSettings renamed", f..".old") -- 20221108 
                os.rename(f, f .. ".old")
                directory_updated = true -- fsync directory content too below
            end
        end
        logger.dbg("DocSettings: Writing to", f)
        logger.info("DocSettings write", f) -- 20221108 
        local f_out = io.open(f, "w")
        if f_out ~= nil then
            f_out:write("-- we can read Lua syntax here!\nreturn ")
            f_out:write(s_out)
            f_out:write("\n")
            ffiutil.fsyncOpenedFile(f_out) -- force flush to the storage device
            f_out:close()
            logger.info("DocSettings saved", f) -- 20221108 

            if self.candidates ~= nil
            and G_reader_settings:nilOrFalse("preserve_legacy_docsetting") then
                for _, t in ipairs(self.candidates) do
                    local candidate_path = t.path
                    if candidate_path ~= f and candidate_path ~= f .. ".old" then
                        logger.dbg("DocSettings: Removed legacy file", candidate_path)
                        logger.info("DocSettings legacy rm", candidate_path) -- 20221108 
                        os.remove(candidate_path)
                        -- We should not remove sidecar folder, as it may
                        -- contain Kindle history files.
                    end
                end
            end

            if directory_updated then
                -- Ensure the file renaming is flushed to storage device
                ffiutil.fsyncDirectory(f)
            end
            break
        end
    end
```

```lua
    local candidates = buildCandidates(candidates_list)

    local ok, stored, filepath
    for _, t in ipairs(candidates) do
        local candidate_path = t.path
        -- Ignore empty files
        if lfs.attributes(candidate_path, "size") > 0 then
            ok, stored = pcall(dofile, candidate_path)
            -- Ignore empty tables
            if ok and next(stored) ~= nil then
                logger.dbg("DocSettings: data is read from", candidate_path)
                logger.info("DocSettings read", candidate_path) -- 20221108 
                filepath = candidate_path
                break
            end
        else -- 20221108 : pour investiguer pourquoi parfois perdu
            logger.info("DocSettings empty", candidate_path)
        end
        logger.dbg("DocSettings:", candidate_path, "is invalid, removed.")
        -- os.remove(candidate_path)
        -- 20221108 : pour investiguer pourquoi parfois perdu
        os.rename(candidate_path, candidate_path .. ".invalid")
        logger.info("DocSettings invalid", candidate_path)
    end
```

So, it looks to me the written and saved (so flush/fsynced) `some book.sdr/metadata.epub.lua`, is just not found when building candidates (it is not found and empty, neither found and invalid)...

@NiLuJe : any reason you could see for this happening (except the classic "FAT32 shenanigans" or "your filesystem is dying" :/
Is there something we missed in our logic ? Could a `ffiutil.fsyncDirectory(f)` be needed even if we don't create a new file ?

**Comment by NiLuJe** [comment]
> Could a `ffiutil.fsyncDirectory(f)` be needed even if we don't create a new file ?

It wouldn't magically disappear, so that's irrelevant when no power cycling is involved ;).

**Comment by NiLuJe** [comment]
Is the `book.sdr/metadata.epub.lua` actually written successfully?

I'd check if the write/close/fsync calls actually return successfully, possibly that's the issue, somehow?

(I... don't recall how "helpful" io.write's error reporting is, though :/).

**Comment by poire-z** [comment]
Too late for now.
As for "check if the write/close/fsync calls actually return successfully", not sure what could happen. And anyway, the io.open() being successful, I should have at least an empty file. That I would notice later.
I'll add logging the list of candidates, I'll see.
Can I assume that the fsync calls would only be useful in case of crash/reboot, and that even without them, the "cached/memory view" of the filesystem by the Linux system is always good/updated?
(I thought that maybe `ffiutil.fsyncOpenedFile(f_out)`, without the 2nd argument `sync_metadata`, not flushing any timestamp, could have cause the new file not having the "now" timestamp. But no, a simple successful io.open() without writting anything updates the timestamp.)

**Comment by NiLuJe** [comment]
Barring kernel/glibc issues, I sure hope the VFS state is consistent regardless of fsync calls, yeah ;).

**Comment by NiLuJe** [comment]
The empty file because of io.open being successful is indeed something I would need to double-check (I *think* it should behave like that, though).

**Comment by Frenzie** [comment]
That probably makes a certain amount of sense. *nix mostly sensibly uses epoch/UTC internally and mostly only converts that to the local timezone for display purposes (emphasis on mostly, RTC still gives me nightmares), but Windows/FAT tends to use local time leading to all manner of fun issues like this.
https://github.com/koreader/koreader/blob/05cd59ebe568d371ef0bab5acbafbbbe6aea7421/frontend/docsettings.lua#L19-L44

I think @NiLuJe's new logic is too sophisticated and a much dumber simple counter would work better. If the old logic couldn't deal with a missing number that's a problem, but it shouldn't disregard that in favor of mtime. Quite the opposite.

**Comment by NiLuJe** [comment]
I don't remember actually changing the logic, just making it work as intended ;o).

A couple of questions:

* Err, how are your ls outputs generated? It's unclear to me what's in UTC and what's in localtime, and why. ls should *always* show you stuff in localtime (well, locla to the ls host, anyway ;p).
* How are you handling your updates, exactly?

**Comment by NiLuJe** [comment]
A shift of 41:47 in the past is... fairly weird, and doesn't look like a DST or local/UTC issue, unless you have serious timekeepingt issues *somewhere*...

**Comment by poire-z** [comment]
> That probably makes a certain amount of sense. *nix mostly sensibly uses epoch/UTC internally 

Does not to me :) these timestamps should only by utc, as they are managed by the OS when creating/updating files - and the one we get in history are from lfs and must be pure utc/unix epoch.
I don't think anything from KOReader/NiLuJe own time stuff (the bootime/monotonic hell) is at play there.

> Err, how are your ls outputs generated? It's unclear to me what's in UTC and what's in localtime, and why. ls should always show you stuff in localtime (well, local to the ls host, anyway ;p).

On Windows, with the onboard fs mounted by Windows via USB (enabled under KSM, without koreader). Then, using cygwin in a terminal, where I have `TZ=CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00`.

> How are you handling your updates, exactly?

onboard fs mounted by Windows via USB (enabled under KSM, without koreader), cygwin, rm -rf .adds/koreader, unzip, patch.
unmount usb via KSM, reboot via KSM, starting koreader via KSM.


As I rm'ed the older koreader, I don't have the previous crash.log anymore to see at what time the last setting was saved before I rebooted...

> A shift of 41:47 in the past is... fairly weird

From where do you make out that value ?

I guess I should look at KSM scripts for mounting/unmount USB, if they don't play with some timezone, or something...

**Comment by NiLuJe** [comment]
> From where do you make out that value ?

From the two consecutive entries for metadata.lua in your log: `1670675932 - 1670673425 == 2507 == 41m47s`

**Comment by poire-z** [comment]
I haven't been fully reading between these 2 times, it was in "standby" a good amount of these 41 minutes. ie I may have read around 12h02, then standby'ed, resumed at 12h38 to exit (so, docsetting saved) and update.

Nothing special in ksm scripts:
**usb_enable.sh**
```sh
#!/bin/sh

# --- change as you see fit (begin)
#PRODUCT_ID=0x4163
VERSION=0.0.0
SN=N000000000000
# --- change as you see fit (end)

MODULE_LOADED=`lsmod | grep -c g_file_storage`


VENDOR_ID=0x2237

DEV="/dev/mmcblk1p1"
if [ -e /dev/mmcblk1p1 ]; then
  LUNS=/dev/mmcblk0p3,/dev/mmcblk1p1
else
  LUNS=/dev/mmcblk0p3
fi

PARAMS="vendor=$VENDOR_ID product=$PRODUCT_ID vendor_id=Kobo product_id=eReader-$VERSION SN=$SN"
sync
sync  # added by me
echo 3 > /proc/sys/vm/drop_caches
#umount -l /mnt/onboard
umount -l /mnt/sd

/sbin/insmod /drivers/$PLATFORM/usb/gadget/arcotg_udc.ko
sleep 2

/sbin/insmod /drivers/$PLATFORM/usb/gadget/g_file_storage.ko file=$LUNS stall=1 removable=1 $PARAMS
sleep 1
```

**usb_disable.sh**
```sh
#!/bin/sh

MODULE_LOADED=`lsmod | grep -c g_file_storage`



DEV="/dev/mmcblk1p1"

        if [ $MODULE_LOADED -eq 0 ]; then
                exit
        fi

        sync  # added by me
        sync  # added by me
        echo 3 > /proc/sys/vm/drop_caches   # added by me
        /sbin/rmmod g_file_storage
        /sbin/rmmod arcotg_udc
        sleep 1
        sync  # added by me
        sync  # added by me

        if [ -e /drivers/$PLATFORM ]; then
                PARTITION=/dev/mmcblk0p3
                MOUNTARGS="noatime,nodiratime,shortname=mixed,utf8"
        fi

#       dosfsck -a -w $PARTITION
#       mount -o $MOUNTARGS -t vfat $PARTITION /mnt/onboard

        if [ -e $DEV ]; then
                mount -r -t vfat -o $MOUNTARGS $DEV /mnt/sd
        fi

#       ( sleep 1
#               rm -rf /mnt/onboard/fsck*
#               rm -rf /mnt/onboard/FSCK*
#       ) &
```
untouched since 2018. These is the old KSM issue that we don't unmount /mnt/onboard when making it available via USB (unlike what you do in koreader's scripts I guess, and what KSM 0.9 did). I guess that's why I also added `echo 3 > /proc/sys/vm/drop_caches` in the usb_disable script.
(Just mentionning that for completeness, not trying to make that old KSM do the right thing better :)
I had never had such issues, until ~ the time where the move away from TimeVal happened - but again, I don't see how this would apply here.

**Comment by Frenzie** [comment]
> Does not to me :) these timestamps should only by utc, as they are managed by the OS when creating/updating files - and the one we get in history are from lfs and must be pure utc/unix epoch.
I don't think anything from KOReader/NiLuJe own time stuff (the bootime/monotonic hell) is at play there.

I thought you said you USB mounted it on your PC?

**Comment by poire-z** [comment]
> I thought you said you USB mounted it on your PC?

That's how I _read_ them, via cygwin `ls` once they are mounted with USB. But I have not touched/updated these docsettings when it was mounted, so all the docsettings files timestamps where done by KOReader when USB was not mounted anywhere.

**Comment by NiLuJe** [comment]
Okay, I'm slow, I just got the 11:57 UTC vs. 12:57 local ;p.

That would implies that *something* touch'ed the metadata though...

**Comment by NiLuJe** [comment]
> These is the old KSM issue that we don't unmount /mnt/onboard when making it available via USB (unlike what you do in koreader's scripts I guess, and what KSM 0.9 did).

That is horribly broken ;o).

Even with sane device behaviors, I've seen Windows (and macOS) seemingly drop or rollback stuff over USBMS for no apparent reason :s.

**Comment by NiLuJe** [comment]
> That would imply that _something_ touch'ed the metadata though...

Is there funky security software running or something, perhaps?

I'd be *inclined* to chuck that one at USBMS shenanigans given the context, but the exact UTC vs. CET shift is... suspiciously suspicious ;).

**Comment by poire-z** [comment]
> Is there funky security software running or something, perhaps?

Nothing else than the standard Windows 10 stuff (Windows defender, or something like that).

It's possible that on a reboot, KSM or the Kobo startup scripts do the DOS equivalent of fsck: `dosfsck -a -w /dev/mmcblk0p3 || dosfsck -a -w /dev/mmcblk0p3 || dosfsck -a -w /dev/mmcblk0p3 || dosfsck -a -w /dev/mmcblk0p3 || FS_CORRUPT=1`
 (sometimes, I see a reboot takes some more time than usual, don't remember if that happened earlier today). Could this cause timestamps to be updated/messed up ?

I'd still prefer to understand what happens, but if:

> I'd be inclined to chuck that one at USBMS shenanigans given the context

shouldn't our candidates sorting give a larger score to metadata.lua than metadata.lua.old, even if the .lua.old is newer than the .lua ? (I can't think of a case where the .old would be more worthy than the .lua - but I also can't think why the .lua could have a timestamp older than the .old :)

**Comment by NiLuJe** [comment]
Whether a fsck could have an effect on this is a very good question indeed! No idea, though ;).

> shouldn't our candidates sorting give a larger score to metadata.lua than metadata.lua.old, even if the .lua.old is newer than the .lua ? (I can't think of a case where the .old would be more worthy than the .lua - but I also can't think why the .lua could have a timestamp older than the .old :)

That's a fair point, and what @Frenzie was hinting at earlier. I think the original mtime logic was there to handle the cases of external storage with legacy sidecars, but, even there, I'm of the mind to just don't bother with it and just use the list as priority?

(The only other solution I can think of would be a gnarlier one where we keep the mtime stuff, but *not* for the {, .old} pairs, where we would always want to prefer the not-a-backup if it exists).

**Comment by poire-z** [comment]
I'll update my dosfsck to your version, and see (or not, dunno how :) if it fixes stuff.

> (The only other solution I can think of would be a gnarlier one where we keep the mtime stuff, but not for the {, .old} pairs, where we would always want to prefer the not-a-backup one if it exists).

I'd prefer just that. We don't know much how the sdr on a external storage, which could go from r/w to r/o for reasons/chronology we can't really know (and even less about their timestamps), so best to trust the most recent for them ?

**Comment by NiLuJe** [comment]
Cool, I'll see what I can come up ;).

Braindump: play with pdd/even numbers for the prop field to track the distinction.

**Comment by NiLuJe** [comment]
I think I settled on a slightly less gnarly trick ;).

(Or not, the idea was jotted down during a bout of insomnia at oh-god-o'clock, so, who knows ;p).
