### ISSUE TITLE
FR: Consistent contrast and font weight between body and footnote

### ISSUE THREAD

**Issue by trungng2006** [koreader/koreader#9229]
Please kindly consider applying the same level of contrast and font weight between body and footnote.
Currently, the font weight too thin, so i need to increase the footnote size.

![16555678311808592403416016496355](https://user-images.githubusercontent.com/71961905/174446605-c6cd53ad-b0f8-40f3-8805-94fb69967102.jpg)

Thank you!

**Comment by poire-z** [comment]
We can't.
The footnote widget is rendered by the MuPDF engine, which has a hardcoded limited set of fonts - and it uses our generic KOReader UI font (Noto Sans). We also can't set any contrast.
Your book is rendered by crengine, which has access to all your fonts, and may use embedded fonts in an EPUB. MuPDF can't use all of these.
The only thing we could do (and are doing) is using the same font size and the same left/right margins (so it looks aligned with the book text blocks).

Oh, well, may be not :) if I believe my old self that wrote this at the time:
https://github.com/koreader/koreader/blob/83453dfd8f718d022783ad3182d068e9a9f28ddd/frontend/ui/widget/footnotewidget.lua#L24-L42
So, it might not be impossible. I might give it a try.

**Comment by trungng2006** [comment]
Thank you so much!
I think this is great.
I can also edit the font metadata from bold to regular. (so the body will not need additional contrast and weight). 
Then both the body and the footnote can be bold :D
