### ISSUE TITLE
Touchmenu is not resized while on the foreground.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#9235]
#### Issue

Touchmenu is not resized to new screen size.

#### Steps to reproduce

On desktop: resize a window with touchmenu opened.
On android: toggle rotation between portrait and landscape modes with touchmenu opened.

#### More info:

I've been aware of the issue for a long time but never bothered me enough to open a ticket. Now I want to refactor the fullscreen behaviour on desktop/android and found it a bit nastier.

Any hint on why it happens is very welcome. Maybe we lack an event that tells the touch menu instance to redraw itself, like both the reader and the filemanager do?

#### Gif:
![Peek 2022-06-19 23-29](https://user-images.githubusercontent.com/975883/174501262-7ce7743a-b29b-4344-b038-a44b6bc6bf58.gif)

**Comment by poire-z** [comment]
May be we can just keep getting lazy and do as for the bottom menu :)
https://github.com/koreader/koreader/blob/bd89ab30bd8de003f4c8e2434eb627762206887c/frontend/apps/reader/modules/readerconfig.lua#L150-L156

```diff
--- a/frontend/apps/reader/modules/readermenu.lua
+++ b/frontend/apps/reader/modules/readermenu.lua
@@ -408,4 +408,8 @@ function ReaderMenu:onCloseReaderMenu()
 end

+function ReaderMenu:onSetDimensions(dimen)
+    self:onCloseReaderMenu()
+end
+
 function ReaderMenu:onCloseDocument()
     if Device:supportsScreensaver() then
```

(When eLastic eInk comes out, we'll rethink about it :)
