### ISSUE TITLE
Night mode does not persist across different books/screens

### ISSUE THREAD

**Issue by aksarkar** [koreader/koreader#9236]
* KOReader version: 20220501
* Device: Kobo Clara HD

#### Issue

When switching between books, or moving from a book to the history screen, or moving from a book to the file browser, if night mode was enabled, it does not remain enabled.

Related, if night mode was enabled and the reader is put into suspend, it does not remain enabled when the reader awakes.

#### Steps to reproduce

1. On any screen, toggle night mode on
2. Switch to any other screen (to/from a book from/to history, file browser, previous document)
3. Night mode does not remain on.

**Comment by NiLuJe** [comment]
Assuming our actual nightmode toggle is still on in the settings, that's a kernel issue on (some) Mk. 7 devices.

c.f., https://github.com/NiLuJe/FBInk/blob/5ecd240af45edadc0efd3da1e995fc6241f8a568/fbink.c#L2527-L2559

**Comment by aksarkar** [comment]
I checked and night mode does not remain on in the settings when switching screens.

**Comment by NiLuJe** [comment]
Then you might want to check your settings to double-check that you don't have a profile or gesture that affects nightmode interacting somewhere...
