### ISSUE TITLE
two lines on the side

### ISSUE THREAD

**Issue by hanzicn** [koreader/koreader#9239]
* KOReader version: 2022.05.1
* Device: MiReaderPro 1.1.8
* 

#### as the picture, there is two lines on screen. on the other devices (phone) doesn't has it. how to fix it ?

![微信图片_20220621055714](https://user-images.githubusercontent.com/59000046/174682702-28e2d35a-b3d2-4fbb-919b-0e5513cf6dc1.jpg)
![微信图片_20220621055721](https://user-images.githubusercontent.com/59000046/174682705-d4b2e4a8-021b-47f3-b954-ade285e13b23.jpg)

##### `[Uploading crash.log…]()g` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>
```
<Paste crash.log content here>
```
</details>

**Comment by pazos** [comment]
disable perception expander plugin
