### ISSUE TITLE
in book images not appearing properly

### ISSUE THREAD

**Issue by tudos4** [koreader/koreader#9240]
* KOReader version: KOReader 2022.05.1
* Device: poco x3 pro 256/8 gb, running crdroid june 15 build, android12.1/12L

#### Issue
i have a specific epub file where the images dont load correctly instead appearing as white  square placeholders only the cover loads correctly. other epubs dont have this problem and it appears correctly in for example read era, or calibre on pc.
#### Steps to reproduce

see attached epub

if it matters all i did was swapped the images using calibre edit book->images->replace illustration with and added a few more sections.

https://drive.google.com/file/d/1JushZFTUVXX1YvmW1VmZgrDP98Wcwdz6/view?usp=sharing

it maybe an issue in that specific epub file but im not expereinced and tought to ask here

**Comment by poire-z** [comment]
Got worried, as everything was looking fine as far as the HTML and filenames were concerned.
But:
```
$ file *
LN_EN_Vol_01-000.jpg:                        RIFF (little-endian) data, Web/P image, VP8 encoding, 1403x2000, Scaling: [none]x[none], YUV color, decoders should clamp
LN_EN_Vol_01-01.jpg:                         RIFF (little-endian) data, Web/P image, VP8 encoding, 2000x1425, Scaling: [none]x[none], YUV color, decoders should clamp
LN_EN_Vol_01-02.jpg:                         RIFF (little-endian) data, Web/P image, VP8 encoding, 2000x1424, Scaling: [none]x[none], YUV color, decoders should clamp
LN_EN_Vol_01-03.jpg:                         RIFF (little-endian) data, Web/P image, VP8 encoding, 2000x1425, Scaling: [none]x[none], YUV color, decoders should clamp
LN_Vol_01-04.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-05.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-06.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-07.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-08.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-09.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-10.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-11.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-12.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01-13.jpg:                            RIFF (little-endian) data, Web/P image
LN_Vol_01_EN_cover1_1.jpg:                   JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, baseline, precision 8, 1436x2048, components 3
Two_Opposites_Put_Together_Illustration.jpg: RIFF (little-endian) data, Web/P image, VP8 encoding, 1114x1600, Scaling: [none]x[none], YUV color, decoders should clamp
```
All your images, except the cover, even if named something.jpg, are not JPEG, but WebP, that we don't support (yet?)

May be you can tell calibre to not output webp, or convert any source webp to jpg or png ?

**Comment by NiLuJe** [comment]
Sidebar: WebP is terrible anyway, so you wouldn't be losing much ;p.

**Comment by Frenzie** [comment]
> Also, I just hate with a fiery passion what the VP* family of codecs tend to do to images ;s.

Yeah, it looks pretty bad, probably always worse than JPEG at the same filesize. It does have the advantage of being somewhat JPEG-like + transparency though.

**Comment by tudos4** [comment]
Thanks for the answer i tought something similar was going on. I try to convert them and see if they will work correctly.

**Comment by tudos4** [comment]
Yes, this was the problem i converted them to jpeg now they are appearing fine, thanks for the help i think i can close this then.
