### ISSUE TITLE
Epub crash on page turn

### ISSUE THREAD

**Issue by drinkfisher** [koreader/koreader#9241]
* KOReader version: 2022.05.1
* Device: Kobo Libra 2 (firmware version 4.33.19611)

When turning to the next page in a particular epub, koreader crashes. It displays a screen with a bomb and the following error message:
<details>
  <summary>crash.log</summary>

```
 ["h"] = 0,
}
06/22/22-15:52:20 DEBUG adjusted ges: tap
06/22/22-15:52:20 DEBUG AutoSuspend: onInputEvent
06/22/22-15:52:20 DEBUG AutoTurn: onInputEvent
06/22/22-15:52:20 DEBUG getLinkFromPosition link_xpointer: 
06/22/22-15:52:20 DEBUG getLinkFromPosition a_xpointer:
06/22/22-15:52:20 DEBUG nearest selected_link {
    ["end_y"] = 978,
    ["a_xpointer"] = "/body/DocFragment[12]/body/section/p[4]/a.0",
    ["start_x"] = 941,
    ["start_y"] = 978,
    ["end_x"] = 963,
    ["segments"] = {
        [1] = {
            ["x0"] = 941,
            ["y0"] = 978,
            ["x1"] = 963,
            ["y1"] = 1025,
        },
    },
    ["section"] = "#_doc_fragment_46_ introduction_en_2",
    ["link_y"] = 1025,
}
Segmentation fault
```
</details>

[crash.log](https://github.com/koreader/koreader/files/8955073/crash.log)

It occurs repeatedly at this particular page, and my illiterate reading of the crash log seems to indicate it being a footnote issue. I've disabled in-page footnotes, but the error still seems to occur. I've encountered this error with other books laden with footnotes.

I found that converting the epub to mobi and back to epub seems to eliminate the issue (so far), but I was hoping others might have more insight into what's occurring and, if possible, a more elegant fix that I may do.

**Comment by poire-z** [comment]
See https://github.com/koreader/koreader/issues/9133#issuecomment-1138381095 and the links mentionned in it for the details.
And please answer:
> And check that in your settings.reader.lua, you indeed have ["followed_link_marker"] = false, (that a migration should have created on Libra2) - and if not, add it manually (beware comma at end of each setting, except on the last one), and see if this helps.

**Comment by drinkfisher** [comment]
> See [#9133 (comment)](https://github.com/koreader/koreader/issues/9133#issuecomment-1138381095) and the links mentionned in it for the details. And please answer:
> 
> > And check that in your settings.reader.lua, you indeed have ["followed_link_marker"] = false, (that a migration should have created on Libra2) - and if not, add it manually (beware comma at end of each setting, except on the last one), and see if this helps.

Thanks for the speedy response! I checked and I do have ["followed_link_marker"] = false, in settings.reader.lua.

**Comment by drinkfisher** [comment]
I just checked and yes, v2022.05.1-59-g4f4b1e52_2022-06-21 is the version I'm running. I read for an hour (about 40 page turns) and no crashes on page turns, which is awesome.

**Comment by drinkfisher** [comment]
I've just tested and the following work fine: frontlight (including warmth), both physical page turn buttons, battery level report (including the top menu and footer), gyroscope and power button. Sadly I don't use a cover so I can't test that.
