### ISSUE TITLE
FR (UX suggestion) Remind that KOReader controls Kobo's many settings

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9246]
I have recently installed KOReader on Kobo Clara HD for my wife. KOReader on Kobo is great and very-well integrated. However, there is one setting that lead to a confusion - the default auto power off after 3 days. Just because I remembered such a possibility on KOReader we could find this setting in KOReader, and the first thing I did intuitively was to look into the Kobo settings - and sure enough the auto power off was disabled there.

So I think new users should know from the first install that KOReader acts as an OS replacement taking control of multitude of settings like Wi-Fi, Frontlight, timers for sleep and power off, screensavers, USB mass storage, and many other (?) things?

The easiest solution would be to have a popup window on the very first KOReader launch that mentions that the user should look into the settings of KOReader for hardware related settings like screen because it is so well integrated. 

Another option is to emphasize this in the User Guide.

I think this will make KOReader friendlier towards new Kobo users from day 1.

Thank you!

P.S. I guess this question is out-of-scope, but is there a possibility to sync the settings that KOReader changes into Kobo settings? Like the auto power off I mentioned.

**Comment by offset-torque** [comment]
I can add this to the **Quickstart Guide**, a suitable place for this kind of "first use" information.

I am using KOReader as an OS replacement and have to clarify the problem, **mergen3107**.
Is this problem description correct:
- Some of the users who install KOReader are not fully aware of KOReader's capabilities so they try to adjust some settings via Kobo settings page. 
- But these settings are active as long as KOReader is active. When you exit KOReader, they revert to the device settings.

**And a question (for anyone knowledgeable):**
Do you think there are many users who use KOReader together with Kobo's native reader (or Kindle's) ? 
There is this library/overdrive feature and DRM'd books purchased from Kobo store,
so I guess some folks use both KOReader and Kobo reader. I am not so sure of Kindles.

**Comment by mergen3107** [comment]
> * Some of the users who install KOReader are not fully aware of KOReader's capabilities so they try to adjust some settings via Kobo settings page.

Yes, this is the trap to which I fell into myself :D From a common user's perspective, IMHO, this makes sense, because I would treat KOReader as an _app_, so I wouldn't think that it can change _device_ sleep settings (among other things).



> * But these settings are active as long as KOReader is active. When you exit KOReader, they revert to the device settings.

Oh, I didn't know this. Then maybe (if it is difficult to sync KOReader and Kobo settings) we should warn about this as well and suggest to make sure to set up some settings in both places?




> I am not so sure of Kindles.

I would think yes, there are some (many?) people using both KOReader and native Kindle environment, for at least azw3 and kfx support. However I also don't remember having such device-specific deep settings as auto power off on my Kindle PW3, unless things have changed from August 2021 :D 

**P.S.** Besides that there is a de-DRM plugin for calibre, of course - but I am not so sure we should suggest using that just for the sake of keeping people in KOReader. Seems a little out-of-scope =\

**Comment by Frenzie** [comment]
You could also use KOReader primarily for CBZ/DjVu/PDF for example.

**Comment by lightmaster** [comment]
I use KOReader on my Kobo Libra 2 and my wife uses KOReader on her Kindle PW4. We both exclusively use KOReader and do not touch the stock e-reader "apps". Any books we purchases from their stores are stripped of DRM and converted to epub using Calibre and sent to KOReader using Calibre. If I could rip out the stock e-reader "apps" and boot directly into KOReader, I would.

On her Kindle, neither the system nor KOReader has any auto power-off setting. Kindle system has "Power Saver" which is like a computer's sleep state, which corresponds to KOReader's "Autosuspend timeout". KOReader on the Kindle also seems incapable of starting USBMS mode, and have to drop back to the stock e-reader to do that.

**Comment by NiLuJe** [comment]
Is... there a question somewhere in there? ;).

**Comment by lightmaster** [comment]
> Is... there a question somewhere in there? ;).

lol, no. One of the earlier comments had mentioned about whether people used the native reader in conjunction with KOReader and someone else had asked about Kindle specific power settings in KOReader. Just putting my 2 cents in since my household uses both a Kindle and Kobo exclusively with KOReader and try to never touch the native readers.
