### ISSUE TITLE
FR: extend grouping/sorting options in File Manager

### ISSUE THREAD

**Issue by didierm** [koreader/koreader#9250]
**Problem** : 
When importing publications from e.g. Calibre, the filename is alike to "Title - Author (number)".
While KR provides an option to show metadata in the File Manager ( _[Detailed list with cover images and metadata]_ ), it does not provide any option to sort by that metadata.

This renders it impossible to sort/group data by e.g. author (= standard sort method in a bricks-and-mortar library, and probably for a reason), which is a pain if : 
- you want to read a book, and don't remember the title (but do remember the author) ;
- you want to read a series of books by the same author ;
- you want to read an author's published works in chronological order ;
- etc.

**Solution** : 
- essential : provide an option to sort (or preferably : group) by author ;
- bonus feature : within the author sorting/grouping, sort by title/series/publication date.

(this last feature may require an option to map metadata fields, but apparently KR already displays series metadata)

**Alternatives** : 
force Calibre into a different file naming pattern, but that does not really seem a valid option .

**Comment by NiLuJe** [comment]
The file manager isn't really built for that (hence the emphasis on file, not metadata).

So, yes, your best bet is to change your Calibre device tree to something like `author/title`, which gets you sorting by author since they'll be folders.

**Comment by didierm** [comment]
Thank you for your input.

I don't intend to change Calibre's default storage behaviour, but I'll have a look whether something can be done in its export configuration settings.

Nevertheless, it is (IMHO) quite peculiar that the KR file manager is able to show basic metadata (author, title, series), but is unable to sort on those fields (and hence forces the end-user to adapt to KR's idea on how information should be organized).

Thanks for an otherwise excellent (the best, IMNSHO) e-book reader.

**Comment by didierm** [comment]
Fixed by #9284 .
