### ISSUE TITLE
Update information not available on stable channel

### ISSUE THREAD

**Issue by pbienst** [koreader/koreader#9251]
* KOReader version: 2022.05
* Device: Kobo Clara

#### Issue

I could update my Android just fine to 2022.06 using the in-app update function, but when I tried the same on my Kobo, it said 'Update information not available on stable channel'. Both devices use the same default settings for server and channel...

**Comment by Frenzie** [comment]
That's probably a network error on your end, insufficiently differentiated in the user-facing messages. (crash.log should say a bit more probably)

**Comment by pbienst** [comment]
As I mentioned, it's the default one (ota.koreader.rocks). I doubt the server is fried though, as I can still contact it without problems from Android...

**Comment by NiLuJe** [comment]
Not that it should matter, but one never knows: which FW version are you running, how are you launching KOReader, and have you ever successfully done an OTA update on this device?

**Comment by NiLuJe** [comment]
(And even less unlikely, is the wifi AP a capture portal or a restricted/filtered network (e.g., enterprise or uni)).

**Comment by pbienst** [comment]
This is a home network, and I religiously update all my devices every month without problems :-)

KOReader is started from the Nickel menu. My firmware is 4.32.19501, dated 4/14/22.

**Comment by pbienst** [comment]
The problem seems to have miraculously disappeared. Perhaps a fluke at our ISP? They manage the firmware on our router....
