### ISSUE TITLE
Freeze on PW3

### ISSUE THREAD

**Issue by vsim3** [koreader/koreader#9260]
* KOReader version: 2022.05.1, 2022.06
* Device: Kindle PW3

#### Issue
UI freeze, koreader can't startup hang at stock home screen.
Downgrade to koreader-kindlepw2-v2022.03.1-64-g118e063a_2022-05-14.zip
#### Steps to reproduce
KUAL > KOReader > Start KOReader

**Comment by vsim3** [comment]
Hi @NiLuJe what information do you need, i forgot to mention that there is no logs in crash.log. The UI freeze completely, i can access via ssh but nothing seem helpful show up in dmesg.

**Comment by NiLuJe** [comment]
The FW version, syslogs age verbose debug logs while be a good start.

**Comment by vsim3** [comment]
FW: 5.13.5
I have no idea how to get syslogs, nothing show up when i run <code>syslog-ng</code> and <code>logread</code>
ls /var/log
![screen-2022-06-27-19-35](https://user-images.githubusercontent.com/50333987/175943106-a75c3ae0-a387-44bf-8dff-44801124ef36.jpg)

**Comment by NiLuJe** [comment]
For future reference, you can dump logs on Kindle with `showlog` :).
