### ISSUE TITLE
FR: Ability to export the reading statistics calendar view

### ISSUE THREAD

**Issue by EncroachGradually** [koreader/koreader#9266]
The calendar view gives a nice easy to understand visual summary of what you've read and when, it would be very nice to be able to export that view to then share, store or even post on social media - I've tried to screenshot it but the gesture I set up for screenshots doesn't seem to respond when on the calendar view

**Comment by Frenzie** [comment]
A long diagonal swipe should always work.

**Comment by EncroachGradually** [comment]
> A long diagonal swipe should always work.
I feel like an idiot I was doing a shorter swipe because I was worried about hitting the X in the top right corner

**Comment by Frenzie** [comment]
Haha, well, the direction doesn't matter. You can just use the top left and bottom right instead. ;-)
