### ISSUE TITLE
WiFi does not stay connected to sync progress

### ISSUE THREAD

**Issue by Justalurker1213** [koreader/koreader#9267]
* KOReader version: 202206000000
* Device: Kobo Sage

#### Issue

WiFi is disabled at some point, usually around 5-10 minutes after start reading, on the Kobo and progress is no longer synced past that point. I would like WiFi to stay connected when the Kobo is NOT sleeping and then disable when it is asleep, not sure if this qualifies as a feature request or not; I thought this was already built-in functionality.

#### Steps to reproduce

Start reading on Kobo. Progress syncs up to the point when WiFi is disabled and no further.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
In settings → network you can untick disable wifi when inactive. But note that on my device (an original H2O, a fair bit older than the Sage) keeping wifi on or off is the only thing that truly has a noticeable impact on how long the battery lasts.

**Comment by scsmartt** [comment]
> In settings → network you can untick disable wifi when inactive. But note that on my device (an original H2O, a fair bit older than the Sage) keeping wifi on or off is the only thing that truly has a noticeable impact on how long the battery lasts.

I'm trying to stay away from leaving it on all the time because of the abttery impact.
I assumed that the option "Restore WiFi on resume" would keep it active while using the device and then the option "Disable WiFi when inactive" would turn it off once you sleep it but this does not seem to be how it works.
It defeats the purpose of having progress sync enabled though if WiFi turns off before you get to your stopping point.

**Comment by Frenzie** [comment]
There's a noise threshold for activity, because there's always a tiny bit of activity. But even something as small as an inactive SSH connection should be enough to cross it.

Anyway, @NiLuJe would it make sense to have the progress sync explicitly state it's doing network activity given that apparently it doesn't exceed the threshold?

**Comment by scsmartt** [comment]
Or would it make sense to have wifi stay on when the screen is on and turn off once put to sleep?

**Comment by Frenzie** [comment]
I don't quite understand what you're saying. To be clear wifi is always turned off when you close the cover or press the suspend button.

**Comment by scsmartt** [comment]
Yes it does that correctly but it isn't staying on when the screen is on (awake).

**Comment by Frenzie** [comment]
Yes, the device can't suspend with wifi on (and even if it could, that wouldn't make any sense).

**Comment by scsmartt** [comment]
Gotcha. I will uncheck "disable wifi connection when inactive" and hope that fixes it. I was hesitant to do that because I thought that meant WiFi would stay on even when sleeping, which I know would kill my battery very fast.

**Comment by NiLuJe** [comment]
IIRC, Sync is... weird. If it's currently not using the required machinery, it's because doing so was overly complex or something (the fact that I don't use the feature at all doesn't help).

**Comment by scsmartt** [comment]
I will pull the logs and attach.
Interestingly, I unchecked the "disabled wifi" option earlier today and when I woke the Kobo from sleep a bit ago, Wifi was off and I had to manually turn it on. So, it seems like even the resume option, which is checked, is not working correctly for me either.

**Comment by NiLuJe** [comment]
Wi-Fi is *always* torn down before entering low power state: first, because: duh', second, because it will hilariously crash the kernel on some device otherwise ;).

If you want Wi-Fi to be broguth up automatically on wakeup, there's a setting for that right near the timeout one ;).

**Comment by uncharted-user** [comment]
I have experienced unmatched progress sync with app image and android app like a chapter difference.

**Comment by NiLuJe** [comment]
Quite likely fixed by the KOSync cleanups of the last few months.
