### ISSUE TITLE
Kobo Aura One auto warmth not working when device is asleep during transition

### ISSUE THREAD

**Issue by gestra** [koreader/koreader#9274]
* KOReader version: 2022.06
* Device: Kobo Aura One

This issue appeared when I upgraded from 2022.02 to 2022.06 so I'm not sure if this was introduced in 2022.06 or before.

I have auto warmth set to fixed schedule. If I put the device to sleep when the warmth is at 0 and wake it up when the warmth should be 100, or vice versa, the actual light warmth level is the same as when the device was put to sleep. The warmth level as indicated in the Frontlight menu does get updated however, so it's just the light itself that's wrong.

I see a a brief flicker of correct warmth light when the device is waking up.

If I put the device back to sleep and wake it up again the light is at the correct warmth level. Just toggling the front light off and on again via a gesture also fixes it.

**Comment by zwim** [comment]
Can you post a crash.log?
Best yould be a crash.log of the working version and one for the not working version.

**Comment by gestra** [comment]
Here's a log from 2022.06. That's me waking the device, waiting for a minute, then toggling the front light off and on.
[2022.06 crash.log](https://github.com/koreader/koreader/files/9030914/2022.06.crash.log)

Here's 2022.02 waking up.
[2022.02 crash.log](https://github.com/koreader/koreader/files/9030918/2022.02.crash.log)

This bug that was fixed in 2019 seemed to have the same issue.
https://github.com/koreader/koreader/issues/8363

**Comment by zwim** [comment]
@gestra  Thanks for the logs. I will fix rhis next week, when I am at home again.

**Comment by zwim** [comment]
@gestra Can you update KOReader to the latest nightly (Version 2022.06-14) and confirm that the bug is fixed. (First set update -> settings -> update channel -> development and then update).

**Comment by gestra** [comment]
Yes, I can confirm that on version 2022.06-14 the bug is indeed fixed. Thank you for working on this great piece of software!

**Comment by zwim** [comment]
Thank you for testing and reporting.
