### ISSUE TITLE
FR: Can KOReader be used to create new PDF files instead of only viewing PDF files?

### ISSUE THREAD

**Issue by efeizbudak** [koreader/koreader#9278]
**Does your feature request involve difficulty completing a task? Please describe.**
KOReader's reflow and text customization features would be great in creating new pdf files to export to devices unsupported by KOReader / devices where it's harder to install KOReader.

**Describe the solution you'd like**
There should be a way to compile the pages into a PDF document as they would appear with the current settings.

Is this already possible via cli? Is there any way to achieve this on my own?

**Comment by pazos** [comment]
nope

**Comment by offset-torque** [comment]
KOReader uses [K2pdfopt](https://www.willus.com/k2pdfopt/) under the hood, which means you can achieve similar results by using this application on your computer to optimize your PDF's.

**Comment by Frenzie** [comment]
Better results really, through a combination of being able to iterate through a few settings very quickly compared to a slow device and by truly having all available knobs at your disposal.
