### ISSUE TITLE
Some pictures doesn't show

### ISSUE THREAD

**Issue by galaxi-the-son** [koreader/koreader#9281]
* KOReader version:v2022.06
* Device:Android Tablet

#### Issue
Some pictures in this file doesn't show.
the pictures in page number 4.5.6.7.14 and there's is more
#### Steps to reproduce
https://drive.google.com/file/d/16pDW_IWipH_4R35GCFGKgy54D7VCT2FQ/view

**Comment by poire-z** [comment]
That's a pretty bad ass EPUB, 150 Mo, 12000 pages, which takes quite a bit of time to load on my emulator - so I guess it may be minutes on a Kobo (but probably less on a powerful android).
Anyway, I don't think pictures are missing. You just get blank pages:

![image](https://user-images.githubusercontent.com/24273478/177001840-4b401403-9d10-4c27-889d-39474cb012ec.png)

All the images I see in SumatraPDF, I see them here - the white pages are not missing pictures, they are just blank pages.
Probably for the same reasons explained at https://github.com/koreader/koreader/issues/9163#issuecomment-1146637205
Given the size and render time, I won't try to find a style tweak to kill the blank pages :)
(but at least on my emulator, switching Zoom (dpi) from 96 to 48 makes the images smaller and avoid blank pages.

**Comment by galaxi-the-son** [comment]
Thank you i can see it now.
i wasn't able to see it because i set the zoom dpi to off .
and i don't have the blank pages you got i don't know why you got it but anyway thank you 
![image](https://user-images.githubusercontent.com/108577460/177003810-369a2eb8-9c6b-461a-ad37-490b32f67841.png)
![image](https://user-images.githubusercontent.com/108577460/177003848-dd186c4a-62ad-4468-aa72-8380355be92e.png)
![image](https://user-images.githubusercontent.com/108577460/177003852-2dd8c4c8-decf-4771-b2b1-3c4afea75647.png)

**Comment by poire-z** [comment]
Indeed, most of these images are not displayed when zoom/dpi is "off". Which is rather strange. It's supposed to act as "old/legacy" coolreader code - dunno if I messed that or if it was already not showing that kind of image layout, and if I should fix that...
