### ISSUE TITLE
filename templates not working when sending books over wireless connection with calibre

### ISSUE THREAD

**Issue by nonameVHSM** [koreader/koreader#9284]
* KOReader version: 2022.06
* Device: Kindle Basic KT4 and Samsung Tab A7 Lite

#### Issue

Unsure if this is an actual issue or if it's how it's supposed to work due to some limitation or if it's just me not knowing how to use KOReader. Basically I've been trying to get my books to sort in a certain way in koreader, since koreader uses filenames to sort, I'm trying to get specific filenames by using filename templates on calibre, and sending the books using the [calibre wireless device connection](https://github.com/koreader/koreader/wiki/Calibre-wireless-connection). I'm reporting the issue here to hopefully get some support.

Problem is, the books sent to koreader do not use the filename template at all, they always follow the format "Book name - Author(some number)" no matter what you put in the template. I tried this on two devices (kindle and a samsung tablet) to see if it was perhaps some limitation with a jailbroken kindle but the result is the same in both devices.

#### Steps to reproduce

Open Calibre > Preferences > Sending book to devices > save a template > connect your device using [wireless connection](https://github.com/koreader/koreader/wiki/Calibre-wireless-connection) > Send to device

I made a video showing exactly what happens which hopefully will help: https://www.youtube.com/watch?v=ECpY2aSveEc

In the video I use the template `{author}{series:| - | }{series_index} - {title}`

**Comment by pazos** [comment]
The calibre plugin needs some love from a real calibre user. There're no many here and those who are are either 1) very basic users who don't care about these things, like me, or 2) hardcore users who have very specific workflows not relying on wireless transfers, like @NiLuJe

IIRC we use `lpath` directly to store books. No real idea if that "template" is transfered during wireless sessions. And probably no one here has idea or cares about to figure out. You could ask in the calibre forum https://www.mobileread.com/forums/forumdisplay.php?f=166. u/chaley should know.

In case you ask you can link there this ticket. If the response is afirmative it should be possible for us to add support given that the fields used to compose the filename [belong to the subset we actually use](https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/metadata.lua#L18-L28) or the server sends the processed filename as one big string.

**Comment by nonameVHSM** [comment]
> The calibre plugin needs some love from a real calibre user. There're no many here and those who are are either 1) very basic users who don't care about these things, like me, or 2) hardcore users who have very specific workflows not relying on wireless transfers, like @NiLuJe
> 
> IIRC we use `lpath` directly to store books. No real idea if that "template" is transfered during wireless sessions. And probably no one here has idea or cares about to figure out. You could ask in the calibre forum https://www.mobileread.com/forums/forumdisplay.php?f=166. u/chaley should know.
> 
> In case you ask you can link there this ticket. If the response is afirmative it should be possible for us to add support given that the fields used to compose the filename [belong to the subset we actually use](https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/metadata.lua#L18-L28) or the server sends the processed filename as one big string.

I don't quite understand what you mean, but from what I understand KOReader has a default format to save filenames from calibre over wireless and doesn't really interact with the template function on calibre, meaning the filename will always have the same format?

But if the "template" data is transferred during wireless connection it would be possible to implement this? And if it isn't then there's nothing that can be done about filenames?

I'll make a thread on mobileread and link this issue there, thanks for the advice.

I have to ask though, if not calibre, what do the other people here use to manage their books? Do they just do it manually keeping the .epub files in "library" folders and editing metadata in the .epub?

**Comment by pazos** [comment]
> KOReader has a default format to save filenames from calibre over wireless and doesn't really interact with the template function on calibre, meaning the filename will always have the same format?

KO uses `lpath` as provided by calibre server.

> But if the "template" data is transferred during wireless connection it would be possible to implement this?

Yes.

> And if it isn't then there's nothing that can be done about filenames?

Nope. Using `lpath` is the sane choice here.

> I have to ask though, if not calibre, what do the other people here use to manage their books? 

> I have to ask though, if not calibre, what do the other people here use to manage their books? Do they just do it manually keeping the .epub files in "library" folders and editing metadata in the .epub?

I do what you suggested. Don't edit metadata too much. If the document is generated by me (well, by pandoc) I make sure it has good metadata to begin with.  If the document is from a thirdparty it usually contains good metadata **or** good filenames. If I need to edit an epub I use sigil.

I just use calibre to deDRM the books I purchase online. And use the wireless transfer to push them into a folder called "calibre". I don't use metadata search, don't add metadata fields and truly believe the best way to organize series is by folder and with good filenames.

It is great that something that calibre exist as many, many people can benefit from it. It is also great that something like this exists for those who don't want to spend time managing stuff :)

**Comment by nonameVHSM** [comment]
> I just use calibre to deDRM the books I purchase online. And use the wireless transfer to push them into a folder called "calibre". I don't use metadata search, don't add metadata fields and truly believe the best way to organize series is by folder and with good filenames.

By wireless transfer do you mean ssh? Or actual calibre wireless transfer? I was thinking of using "save to disk" to get the filenames I want on a local folder, then transferring the files using filezilla. I would also be able to separate series by folder, something I can't do using calibre wireless transfer either. But going through calibre then filezilla is quite cumbersome to do. And the reason I like calibre is that you can easily see which books from your library are or aren't on the device, and that doesn't wouldn't work though this method.

Worst case scenario if what I'm trying to do really isn't possible I'll just give up on having my books be properly sorted on the device.

**Comment by Frenzie** [comment]
> I have to ask though, if not calibre, what do the other people here use to manage their books? Do they just do it manually keeping the .epub files in "library" folders and editing metadata in the .epub?

I never edit metadata, except in the sense of quickly adjusting the filename and which folder I stick it in.

As an aside @poire-z, it just occurred to me that `ignore_cover` and `ignore_meta` are CoverBrowser DB exclusives, so you can't use https://github.com/koreader/koreader/pull/5428 to easily create a metadata-free folder.

**Comment by poire-z** [comment]
> it just occurred to me that `ignore_cover` and `ignore_meta` are CoverBrowser DB exclusives, so you can't use #5428 to easily create a metadata-free folder.

`Out-of-each-plugin-scope` :)

**Comment by cbhaley** [comment]
https://www.mobileread.com/forums/showthread.php?p=4235500#post4235500

**Comment by pazos** [comment]
thank you very much @cbhaley, (I didn't want to bother you with a ping here but ended doing so to give you thanks :p)

@nonameVHSM: do what's suggested in the mobileread thread to setup the smart device app with the template you want, then start again (remove your inbox_dir folder, create a new one and send your documents there). It should pick the correct `lpath`.

We won't plan to add a template processor and will stick with `lpath`.

**Comment by nonameVHSM** [comment]
Thanks @cbhaley @pazos and everyone else. I followed chaley's instructions and it worked. I had even concocted a setup to mount my kindle as a network drive using rclone and ssh so I could "connect to folder" in calibre, but just connecting to the device directly is much better, thanks again everyone.

**Comment by pazos** [comment]
@nonameVHSM: it would be awesome if you could quickly document what you did to use custom templates in the wiki: in https://github.com/koreader/koreader/wiki/Calibre-wireless-connection.

Nothing fancy: just a couple of lines: if you want custom names go to and to that.

If you don't want to I hope somebody else picks the duty ;)

**Comment by nonameVHSM** [comment]
> @nonameVHSM: it would be awesome if you could quickly document what you did to use custom templates in the wiki: in https://github.com/koreader/koreader/wiki/Calibre-wireless-connection.
> 
> Nothing fancy: just a couple of lines: if you want custom names go to and to that.
> 
> If you don't want to I hope somebody else picks the duty ;)

Great idea, will do it later today with a couple of screenshots.
