### ISSUE TITLE
KoReader crashes when SD card is removed

### ISSUE THREAD

**Issue by Danar435** [koreader/koreader#9291]
* KOReader version: 2022.06
* Device: PB970

#### Issue
When a file from the SD card is opened and the SD card is removed, KoReader would crash. I know it's sounds obvious, but I have happened to remove the card without looking at what file was opened, leading to a crash. A better solution would be to display an error code saying that the file is no longer available and / or return you to the library. 

#### Steps to reproduce
Insert an SD card or removable storage and open KoReader
Open a file from the SD card
Remove the SD card

**Comment by NiLuJe** [comment]
A crash.log would be helpful ;).

**Comment by Danar435** [comment]
I decided to leave out the crash log because it didn't say much and I thought it's pretty straight forward, but here you go:
[crash.log](https://github.com/koreader/koreader/files/9035565/crash.log)

**Comment by NiLuJe** [comment]
That... appears to be SIGKILL :?

No idea what the PB OS does on eject, but there's probably nothing we can do about that...
