### ISSUE TITLE
Calibre can't connect to wireless server on mac

### ISSUE THREAD

**Issue by tsao-chi** [koreader/koreader#9293]
* KOReader version: https://github.com/koreader/koreader/commit/1c69958c98223a3c52ad73af5af0c96839e4efe6
* Device: Mac mini 2020

#### Issue

calibre can't connect to wireless server on mac

origin issue: https://github.com/koreader/koreader/issues/9288

https://github.com/koreader/koreader/issues/9288 now addresses another issue

#### Steps to reproduce

1. Fixup some NetworkMgr and dylib load things https://github.com/koreader/koreader/issues/9288#issuecomment-1173157317 https://github.com/koreader/koreader/issues/9288#issuecomment-1173094844
2. Open Calibre plugin
3. Click connect

#### log

```
07/03/22-21:55:00 INFO  disconnect from calibre
07/03/22-21:55:30 INFO  calibre info loaded from disk in 1.000 milliseconds: 0 books. 0 pruned
07/03/22-21:55:30 WARN  connect to endpoint tcp://127.0.0.1:9090
07/03/22-21:55:30 INFO  connected to calibre 127.0.0.1 9090
07/03/22-21:55:40 INFO  disconnect from calibre
```

**Comment by pazos** [comment]
@tsao-chi: please **do not open** the same issue **again**!!

Original issue **is still open**, **unresolved**. The name of the ticket was changed to **reflect** the issue that **needs to be fixed** and contains instructions about how to fix it. The description is still the original an contains a way to reproduce the issue. Not the only one as anything that will call `NetworkMgr` methods will fail the same way.

If you need more info ask/use the original ticket.
