### ISSUE TITLE
Dictionary does not work on v2022.06-14-g05c586c4_2022-07-04

### ISSUE THREAD

**Issue by roaminghawk** [koreader/koreader#9296]
* KOReader version:v2022.06-14-g05c586c4_2022-07-04
* Device:Onyx Magicbook

#### Issue
Dictionary does not work 
#### Steps to reproduce
When you tap a word the dictionary definition of the word is empty.

Dictionaries appears normal in the dictionaries setting menu.
Tried the same files on my mobile phone - can't switch back to stable since this is the first version that supports my device, thank you - and the dictionaries are working fine. Exactly like it used to work on the same device on the stable 2022-06 before.
Tested with other book files. Same issue.

**Comment by Frenzie** [comment]
Worked around in #9340.
