### ISSUE TITLE
Omission of text from Weblate

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9299]
* KOReader version: 2022/06
* Device: PB 268

#### Issue
There isn't the text of the explanatory popup for the "Cover cache folder" option in Weblate, so it can be translated.

**Comment by Frenzie** [comment]
Where is this found exactly? I'm not immediately sure what you're referring to.

**Comment by Frenzie** [comment]
Never mind, found it:
https://github.com/koreader/koreader/blob/16d35f61aa6ccee70fab1b3e70dc4171f75457ac/plugins/coverimage.koplugin/main.lua#L498
