### ISSUE TITLE
Pull-down menu flashes and disappears

### ISSUE THREAD

**Issue by enigmasc** [koreader/koreader#9304]
* KOReader version: v2022.06-27
* Device: Kobo Touch & Kobo Glo HD

#### Issue

Pull-down menu flashes on screen and then disappears. 

##### `crash.log` (if applicable)
                launching...
  _  _____  ____                _
 | |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
 | ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
 | . \ |_| |  _ <  __/ (_| | (_| |  __/ |
 |_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|

 It's a scroll... It's a codex... It's KOReader!

 [*] Current time: 07/07/22-16:26:44
 [*] Version: v2022.06-27-geb883b8a_2022-07-07

ffi.load: blitbuffer
07/07/22-16:26:45 INFO  initializing for device Kobo_trilogy
07/07/22-16:26:45 INFO  framebuffer resolution: {
    ["w"] = 600,
    ["h"] = 800,
}
[ko-input] Forked off fake event generator (pid: 1081)
07/07/22-16:26:45 WARN  Device:getKeyRepeat: EVIOCGREP ioctl failed: Function not implemented
ffi.load: libs/libmupdf.so
ffi.load: libs/libwrap-mupdf.so
ffi.load: libs/libfreetype.so.6
ffi.load: libs/libharfbuzz.so.0
ffi.load: libs/libzstd.so.1
ffi.load: libs/libutf8proc.so.2
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=1.911 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.911/1.911/1.911 ms
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: seq=0 ttl=64 time=1.849 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 1.849/1.849/1.849 ms
07/07/22-16:26:46 INFO  opening file /mnt/onboard/Literature/George Orwell/Homage to Catalonia.kepub.epub
07/07/22-16:26:47 ERROR failed to register crengine font: cannot register font <./fonts/noto/NotoSansCJKsc-Regular.otf>
07/07/22-16:26:47 ERROR failed to register crengine font: cannot register font </mnt/onboard/fonts/Gentium_Book_Basic_Regular.ttf>
CRE: font GenRyuMin TW TTF regular: updated weight from 500 to 400
07/07/22-16:26:48 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
07/07/22-16:26:48 WARN  Error when loading plugins/kobolight.koplugin/_meta.lua cannot open plugins/kobolight.koplugin/_meta.lua: No such file or directory
CRE WARNING: cached rendering is invalid (style hash mismatch): doing full rendering

**Comment by poire-z** [comment]
> Pull-down menu flashes on screen and then disappears.

Is that since today's nightly build ? and it was ok yesterday ?

May be related to https://github.com/koreader/koreader/pull/5863#issuecomment-1175578046 that was added yesterday.
How do you "pull down" the menu ? With a swipe south ? Would it be possible you're doing two swipe south, for some reason or habit ?
May be our new swipe south shouldn't close and just stop at the top level menu.

**Comment by poire-z** [comment]
Oups, no, just swipe to open indeed closes it immediately.
I guess the single swipe south is processed twice :/

**Comment by poire-z** [comment]
I think we can solve this with:
```diff
--- a/frontend/ui/widget/touchmenu.lua
+++ b/frontend/ui/widget/touchmenu.lua
@@ -758,3 +758,3 @@ end

-function TouchMenu:backToUpperMenu()
+function TouchMenu:backToUpperMenu(no_close)
     if #self.item_table_stack ~= 0 then
@@ -773,3 +773,3 @@ function TouchMenu:backToUpperMenu()
         self:updateItems()
-    else
+    elseif not no_close then
         self:closeMenu()
@@ -823,3 +823,6 @@ function TouchMenu:onSwipe(arg, ges_ev)
     elseif direction == "south" then
-        self:onBack()
+        -- We don't allow the menu to be closed (this is also necessary as
+        -- a swipe south will be emitted when done opening the menu with
+        -- swipe, as the event handled for that is pan south).
+        self:backToUpperMenu(true)
     end
```
So that when I'll be used using swipe south to go back - as if I do that instead of close, it's that I want to reach some top menu and go on doing stuff in the menu - I'll be stuck to the top menu - instead of having it closed and having to re-open it with another kind of gesture like tap.

**Comment by enigmasc** [comment]
> Or rather: the menu open on "pan south", while the swipe south is being made, so you don't have to wait for finger release to see the menu appearing. Then, on a quick finger release (does not happen if you wait a bit before lifting up the finger at end of swipe south), a swipe south event is emitted, which is then processed by the newly shown menu, which go back and close itself...

I works. Thanks. I hope this issue will be fixed in the next update. Force of habit is too great.
