### ISSUE TITLE
FR: Sync read progress with pocketbook's library

### ISSUE THREAD

**Issue by xahon** [koreader/koreader#9317]
**Does your feature request involve difficulty completing a task? Please describe.**
[-]

**Describe the solution you'd like**
I want koreader to sync its internal read progress with PocketBook's library as well as its own default reader app

**Describe alternatives you've considered**
[-]

**Additional context**
PocketBook default reader app propagates read percentage to its library application
![image](https://user-images.githubusercontent.com/18731681/178144794-6852f315-d196-4da1-97f8-e0085e7d2a4c.png)

**Comment by rjd22** [comment]
This sounds as easy it implement but it really isn't. Things like pages and percentages are a fluent thing with ebooks especially the epub format. What the page is depends on font size and line height and is impossible to calculate accurately. This will result in a lot of issues on Github for a feature that will most likely never work perfectly.

The added blocker is that we need to implement another library from PocketBook increasing the risk of crashes of older devices.

IMO I would recommend to just pick a reader and stick with it.

**Comment by NiLuJe** [comment]
FWIW, I wrote a dumb KOReader -> Nickel read status migration script, and basically the only thing I move around are vague enough to work (i.e., read/unread; and a percentage).

Then again, it's just a bit of SQL in [this case](https://svn.ak-team.com/svn/Configs/trunk/Kindle/Kobo_Hacks/Scripts/sync_koreader_progress_to_nickel.py) ;).

**Comment by xIUPITERx** [comment]
Too bad, the function actually sounds very useful, maybe with the possibility to sync the reading progress with Calibre.
