### ISSUE TITLE
Android: Rotation Glitch

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9326]
* KOReader version: 2022.06 and 2022.06.33
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
1) When using rotation from the bottom menu, the screen space does not adjust the content. It is rotated "as is", i.e. only portion of the portrait view is visible, the rest is pure black rectangle. Gestures and respective tap zones are fine, they work within the visible portion of the portrait orientation with correct respective directions (tap to turn pages, swipes, etc).

2) If rotated via the Android means, KOReader does nothing. If I then quit KOReader, the Android UI itself is rotated. So KOReader just ignores rotation. However, I guess this is intended anyway.

3) !!! In MuPDF files it is OK! O_o rotation works fine, UI is scaled properly.

This is with or without the setting `Keep orientation across views`.

I remember this definitely was not the case in 2022.05.01 (previous stable) since I remember playing around with two columns in landscape orientation.

#### Steps to reproduce
Open a reflowable book
Rotate screen via bottom menu
Screen rotates, but does not scale the content and the UI
Observe the black rectangle on the right portion of the screen in landscape

#### Screenshot
![Screenshot1](https://user-images.githubusercontent.com/6279855/178647570-e4bfee15-03ba-4f2d-a68f-09f27eb8a99c.png)

##### `crash.log` files
The ending includes rotation to landscape via bottom menu and then back via gestures (left edge swipe up to 0 degree orientation) because the bottom menu is out of reach. I was lucky to be able to set up gesture via top menu :D

Stable version:
[crash1_2022_06_stable.log](https://github.com/koreader/koreader/files/9098784/crash1_2022_06_stable.log)

Current Nightly (33):
[crash2_2022_06_33_nightly.log](https://github.com/koreader/koreader/files/9098786/crash2_2022_06_33_nightly.log)

Current Nightly with verbose logging:
[crash2_2022_06_33_nightly_VERBOSE.log](https://github.com/koreader/koreader/files/9098787/crash2_2022_06_33_nightly_VERBOSE.log)

**Comment by mergen3107** [comment]
Do I need to take more logs?

**Comment by mergen3107** [comment]
I confirm that 2022.05.1 does not have such issue. Currently using that version

**Comment by pazos** [comment]
1. the screen space does not adjust the content. It is rotated "as is", i.e. only portion of the portrait view is visible, the rest is pure black rectangle

Can reproduce on my phone. v2022.06

2. So KOReader just ignores rotation. However, I guess this is intended anyway.

Yes!

3. In MuPDF files it is OK! O_o rotation works fine, UI is scaled properly.

The same happens on the FM. It is crengine specific

**Comment by mergen3107** [comment]
Thank you @pazos for confirming. 
I’ll try to find the culprit commit via comparing  changes between 2022.06 and 2022.05.1 :D

**Comment by poire-z** [comment]
I can't see anything related on the crengine/frontend/document|apps side.
May be try by disabling `FileManager > Tools > More tools > Dev options > [ ] Enable CRE call cache` - and see if the behaviour changes.
It feels it would miss an event to force a rerendering.
So, the content does not rotate ?
What happens when you go to the next page ? Still not rotated, or it is now ok?
And when the slowdown (for rerendering, try with a big book) happens ? When you switch rotation or when you go to the next page?

**Comment by mergen3107** [comment]
`May be try by disabling FileManager > Tools > More tools > Dev options > [ ] Enable CRE call cache - and see if the behaviour changes.`
No changes here.

`It feels it would miss an event to force a rerendering.`
Can this be related (sorry, I couldn't find a way to refer to commit)? 
![image](https://user-images.githubusercontent.com/6279855/178995061-45b1a4aa-a17e-45a6-a5b7-f2045f9ac2a7.png)

`So, the content does not rotate ?`
No, content rotates, but never gets to be scaled up to landscape view. Everything rotates, content, tap zones, gesture zones.

`What happens when you go to the next page ? Still not rotated, or it is now ok?`
Yes, I can keep reading in such view, it stays the same.

`And when the slowdown (for rerendering, try with a big book) happens ? When you switch rotation or when you go to the next page?`
There is no slowdown at all. The rotation is instantaneous both ways.
Further, if I, say, change a font (that time when I know that re-rendering should occur), it changes the font, but it still doesn't redraw.

**Comment by NiLuJe** [comment]
I wouldn't mind a verbose debug log on a working version to compare, yeah ;).

**Comment by NiLuJe** [comment]
Okay, yeah, related to the inhibitInput stuff: we can't kill the EV_MSC handler on Android, it's where the APP_CMD stuff gets sent (among which is `APP_CMD_CONFIG_CHANGED` ;)).

**Comment by poire-z** [comment]
OK, thanks. Well, I could have tested all that on my phone instead of asking :/
Indeed, it feels weird,
Feels like some BlitBuffer doesn't get its dimensions update. The crengine one, but also the main one as even switching to FileManager keeps it bad.

> Can this be related (sorry, I couldn't find a way to refer to commit)?

> Okay, yeah, related to the inhibitInput 

I just tried commenting the 2x Input:inhibitInput() on my (rooted) Android phone, and yes, this solves the issue !

**Comment by NiLuJe** [comment]
If you're still in a testing mood, I haven't actually tested #9335, but it should do the trick ;).

**Comment by poire-z** [comment]
Yep, your #9335 solves this issue.
(Dunno if it would break other things, no idea what else should be tested :)

**Comment by mergen3107** [comment]
@NiLuJe 
Hooray! The issue is solved with your new commit. It flashes right after rotation button press 2x or 3x, but then resolves everything correctly.

Yes, please let me know if I need to test anything else related to this issue :D

**Comment by mergen3107** [comment]
Thank you very much guys! :)

**Comment by mergen3107** [comment]
Gotcha, this is great! Now, I am going back to my double-column landscapies, yeah :D

**Comment by NiLuJe** [comment]
That's a very good question :D.

**Comment by Frenzie** [comment]
There are slightly different not completely identical refresh type events, see SDL resize for some comments (as to Android I dunno, probably copied from SDL?)

**Comment by poire-z** [comment]
> That's a very good question :D.

Not so much, the answer is stupid:
Because we only do inhibitInput() in ReaderRolling :)
(to avoid ANR on Android when a rerendering takes some time).
