### ISSUE TITLE
Annotations saved into PDF file or in SDR folder depending on clicking inside or outside dialog window when closing it

### ISSUE THREAD

**Issue by kirmaha** [koreader/koreader#9328]
* KOReader version: 2022.06 on Android 11
* Device: Onyx Boox Air Note 2 plus

#### Issue
Regarding the way I close a pdf file, annotations get saved in the pdf file (embed) or in the .sdr folder. When it is saved in the .sdr folder, it doesn't seem possible to save it back into the pdf file itself.

#### Steps to reproduce
1. Open a pdf file ("test.pdf") in KOReader. Make some annotations.
2. Open the menu and press "Quit" or go in the library tab in order to open another file. KOReader promps you to choose to save or not to save the test.pdf before closing it. Press any point on the screen, outside of that dialog window. KOReader closes the file.
3. Open test.pdf in KOReader again. The annotations are still there. Make some other annotations.
4. Open the menu and press "Quit" or go in the library tab in order to open another file. KOReader promps you to choose to save or not to save the test.pdf before closing it : choose to save. KOReader closes the file.
5. Rename the file ("test-renamed.pdf"). On that tablet, there is no real file manager : I used Amaze File Manager but I guess it would be the same with any other (as long as you don't use the built-in weird behaving files browser, which is more like a "recent files" menu).
6. Open test-renamed.pdf in KOReader again : annotations made at step 1 are not showing anymore, but annotations at step 3 are showing.
7. Rename the file back to its original name ("test.pdf").
8. Open test.pdf in KOReader again : all annotations (step 1 and 3) are showing again.
9. Move that file to another device and open it in any PDF viewer (I used Okular) : annotations made at step 1 are not showing anymore, but annotations at step 3 are showing.

I suppose that step 8 shows some annotations (step 1) are stored into .sdr folder ? And others (step 3) are embed in the PDF.

Of course, in real life, there is no reason to use those various way to close a pdf file... But I've been using that tablet with KOReader for a short time and I already missed the "save" button several times (for example, if my left hand is holding the tablet and one of the finders touches the edge of the screen...).

If others can reproduce this issue, I'm wondering : 
* in my opinion, touching anywhere out of the "save or not save" dialog window should have no effect or should cancel the process of closing the file
* would it be possible to have a "save" button in order to regularly ensure everything annotated until now is kept safe into the pdf file ?
* or... would it be possible to have a option to get all sdr-stored annotations embed into the pdf file ?

**Comment by poire-z** [comment]
> in my opinion, touching anywhere out of the "save or not save" dialog window should have no effect or should cancel the process of closing the file

Just a matter of adding `dismissable = false,` inside this (if this the right dialog box):
https://github.com/koreader/koreader/blob/e679b00d0a380e2a74512d45e450418b45e32c47/frontend/apps/reader/readerui.lua#L733-L744

> would it be possible to have a "save" button in order to regularly ensure everything annotated until now is kept safe into the pdf file ?

We don't have that, but (in case you didn't see it) there is `Gear > Document> Save document (write highlights into PDF) > Prompt / Always`

> or... would it be possible to have a option to get all sdr-stored annotations embed into the pdf file ?

This is the biggest issue about all this. Some details about why it's a mess in and around:
https://github.com/koreader/koreader/issues/7928#issuecomment-879859250
https://github.com/koreader/koreader/issues/8084#issuecomment-899471911
https://github.com/koreader/koreader/issues/8663#issuecomment-1014602544

**Comment by kirmaha** [comment]
Thanks for your lightspeed answer !

> > would it be possible to have a "save" button in order to regularly ensure everything annotated until now is kept safe into the pdf file ?
> We don't have that, but (in case you didn't see it) there is `Gear > Document> Save document (write highlights into PDF) > Prompt / Always`
Indeed, I missed that setting (I promess I searching before asking... :-s ). Thank you very much. First try : seems to work perfectly. I don't risk to save annotations into SDR folder anymore, if I understand.

> > in my opinion, touching anywhere out of the "save or not save" dialog window should have no effect or should cancel the process of closing the file
> Just a matter of adding `dismissable = false,` inside this (if this the right dialog box):
I don't need that anymore, thanks to your answer, but I still think it would be way more secure for all users who keep the "Save document (write highlights into PDF)" setting untouched. Especially for beginners like me... Still, even if it looks easy, I have no dev skills at all and I'm afraid I can't help implementing your suggestion :-s

Thank you for your advices and explanations, this is really helpful !
