### ISSUE TITLE
[Feature] Calibre Content Server integration

### ISSUE THREAD

**Issue by Visne** [koreader/koreader#9329]
I'm not entirely sure whether this is a question or a feature request, but as far as I understand you have two options to remotely get books on your device:

- Connect to a Calibre GUI instance running on your PC, and upload the books to your device. Then, a local Calibre database is generated and you can use it to search metadata.
- Use OPDS to download books. Then, there is no Calibre database and you can't search metadata.

As far as I know, there is no way to get books from a calibre-server or calibre-web instance. Therefore, it seems like it is not possible to both host books headlessly on a homeserver, and have metadata search in KOReader.

So, if it is actually possible then please let me know, if not I guess this is a feature request.

**Comment by pazos** [comment]
> I'm not entirely sure whether this is a question or a feature request

I think it is both a question and a feature request.

The question: 

> Is possible to have both OPDS and metadata search?

Nope. Metadata search is a feature of the calibre plugin that relies on metadata **as provided** by calibre in wired transfers, which we do replicate on wireless transfers.

The opds plugin is generic and attempt to work against multiple servers. The calibre content server is a "rich" content server that can fallback to yet another opds server but I'm fairly sure there're ways of using special features, like retrieving the same kind of metadata required to do searchs against it.

The feature request:

Please add support for calibre content server, so I can use it to download books and companion metadata.

It is a won't fix on my end. Patches welcome.

Please make it part of the calibre plugin. You'll need to find a way to request the metadata for a given book when downloading it and call various `CalibreMetadata` methods to update the metadata and save it to disk, so it can be used on future searchs.

**Comment by Visne** [comment]
Okay, that makes sense, thanks.

I might have a look at it, but I can't promise anything.

**Comment by pazos** [comment]
Thanks for changing the title!

Closing but still watching. Feel free to ask questions if/when they arrive :)
