### ISSUE TITLE
Strange characters

### ISSUE THREAD

**Issue by Farsuperslime** [koreader/koreader#9331]
* KOReader version: 2022.06
* Device: Kobo Clara HD

#### issue
On a book I am reading when I go to certain pages random characters are there in place of the ones that should be there, for example when there's supposed to be an apostrophe it shows a character that looks like a t and a b combined.

#### steps to reproduce
Open a book named Shades of Grey by Jasper Fforde

This seems to be similar to issue #8034

**Comment by poire-z** [comment]
Hard to guess.
What format is this book ?
If EPUB/TXT/FB2, can you highlight a few words around this apostrophe, and select `View HTML`, and then in the bottom `Switch to (debug... rendering debug...) unicode debug view`, and see what the Unicode codepoints detected (things like `<U+123>`) for the apostrophe. We then may guess if it's an encoding issue.

**Comment by Farsuperslime** [comment]
![Uploading IMG_20220713_115500688.jpg…]()

This is what it shows

**Comment by Farsuperslime** [comment]
This is what it shows 
![Uploading IMG_20220713_115747871.jpg…]()

**Comment by Farsuperslime** [comment]
This is what it shows 
![Uploading IMG_20220713_115747871.jpg…]()

**Comment by poire-z** [comment]
(You clicked the post button before the upload was finished, so we can't see your picture.)

**Comment by Farsuperslime** [comment]
![IMG_20220713_115747871](https://user-images.githubusercontent.com/65824420/178786713-f83b3a10-8729-4a75-8274-ee3380a6704f.jpg)

**Comment by Farsuperslime** [comment]
I attempted to use these commands and the find one returned this error: sed: -e expression #1, char 34: unterminated `s' command

**Comment by poire-z** [comment]
Looks like it is missing a `/` after `utf-8`. Should work with:
`find . -iname '*.html' -exec sed 's/charset=iso-8859-1/charset=utf-8/' -i {} \;`

So, was this the case ? Did you see these `<meta ... charset=iso-8859-1'>` ?

**Comment by Farsuperslime** [comment]
I didn't even look for that string of text, I just attempted the charset conversion to see if that worked and it was in fact the issue. Thanks for the help!

**Comment by poire-z** [comment]
Probably a similar issue for the same reason noticed at https://www.mobileread.com/forums/showthread.php?t=347892 :/
Although putting `&mdash` in a xhtml with whatever meta charset seems to work fine (but other non-&-escaped char can obviously get bad).
