### ISSUE TITLE
Keyboard option to only enable shift for one letter (hold for caps lock)

### ISSUE THREAD

**Issue by Visne** [koreader/koreader#9332]
I'm used to my phone, where I tap once on the shift key to enable shift for one letter, or double tap for caps lock. Because of this muscle memory I keep enabling caps in KOReader accidentally, and then type in caps.

Since typing in caps is relatively uncommon, I think it makes more sense to just hold the shift button for caps and tap once to enable shift for one letter.

Having this option would be nice, and personally I would even make it the default but that's not up to me.

**Comment by NiLuJe** [comment]
This has been discussed before, IIRC, and the consensus was that it would be hard to do because of technical reasons given the current design on the VK ;).

**Comment by Visne** [comment]
Hmm, that's too bad.

**Comment by Commodore64user** [comment]
this was already fixed by #9659
