### ISSUE TITLE
FR: Bump sdcv version to 0.5.4

### ISSUE THREAD

**Issue by ecraven** [koreader/koreader#9346]
A new version of sdcv was released that deals correctly with multiple identical synonyms. Could the version that koreader uses be bumped to this version?

Thanks!

**Comment by Frenzie** [comment]
Unfortunately not, since it's broken on Android and I don't have time to investigate why.

https://github.com/koreader/koreader/pull/9340

**Comment by pazos** [comment]
Done in https://github.com/koreader/koreader-base/pull/1516
