### ISSUE TITLE
[Legacy Kindle/K3GB]  Buttons mapped incorrectly when in landscape mode

### ISSUE THREAD

**Issue by jimbob88** [koreader/koreader#9350]
* KOReader version: 2022.05.1-58
* Device:  Kindle 3GB [Legacy Kindle]

#### Issue
Related to #7561. The buttons are mapped in the wrong way when the screen is rotated to landscape mode.

#### Steps to reproduce

1. Open any document (I opened a PDF)
2. Press Aa on the keyboard
3. Scroll to the rotation setting and set it to landscape 
![photo_2022-07-19_15-53-05](https://user-images.githubusercontent.com/9913366/179781231-72f55d73-7131-477d-8718-16c62c08df2d.jpg)

4. Now when you press the button which is facing downwards, the pages go backwards. And when you press the button pointing upwards, the pdf turns pages forwards. I think it should be the opposite way around on this device.

**Comment by Frenzie** [comment]
Pinging @NiLuJe iirc

**Comment by NiLuJe** [comment]
Yup, will double-check, there might be shenanigans related to different keycodes with the DC...

**Comment by Commodore64user** [comment]
Same with K4, in clockwise landscape mode `FwdPg` goes back and `BackPg` goes forward. Interestingly in counterclockwise landscape, that is not the case...
