### ISSUE TITLE
FR: Create .sdr files as hidden files

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9353]
**Does your feature request involve difficulty completing a task? Please describe.**
On Pocketbook devices, when we search in the "Library", the .sdr folders also appear. Which makes searching tedious. Could these folders be created as hidden folders?
I think a similar request has already been made, but I'm not sure.

Thank you!

**Comment by jimbob88** [comment]
Same/similar to requests #8577 and  #8577
