### ISSUE TITLE
FR: A different look for highlights/bookmarks with and without comments/annotations

### ISSUE THREAD

**Issue by WolfgangDpunkt** [koreader/koreader#9356]
Currently, you can't tell whether a highlight  contains additional text, i.e. a note, or only the autotext.
The great bookmap function already differentiates between the two. But it would be great to display the different types directly in reading mode. For example, by indicating highlights with notes with a small pencil symbol, or by underlining it with a dotted line.

This would make the processing of notes much easier, as it would not be necessary to manually check every passage for annotations.

![grafik](https://user-images.githubusercontent.com/35533844/180091552-8d5fef3e-e9b4-4d8e-a260-77d4830c889a.png)

**Comment by hius07** [comment]
More ideas on how to indicate the notes? Applicable to all 4 styles of highlighting.

**Comment by offset-torque** [comment]
> More ideas on how to indicate the notes? Applicable to all 4 styles of highlighting.

I think it can be an icon in the margin area (like that arrow indicating page overlap in **Continuous Mode**)
It doesn't interfere with the highlight itself so different styles are ok.
Probably it should be on the right side to avoid interfering with that overlap arrow.
And preferably the same pencil icon in the **Book Map** to avoid confusion.

![note_icon](https://user-images.githubusercontent.com/84420582/180114569-5bd5702f-177b-41c5-aab4-9cffe19cdb30.png)

**Comment by WolfgangDpunkt** [comment]
Thank you for the quick response and the great suggestion.
That pencil icon would be a very good solution, in all aspects.

Perhaps, in a further step, the  visibility of the  icon should be switchable in the options, in the submenu of the highlight style selection. Since it could irritate some users, when always shown.

**Comment by hius07** [comment]
Some arguments against a pencil sign in the margin:
-the margin might be small, not enough space to draw the pencil;
-we can have two short highlights in one line
-some difficulties to place the pencil in pdf may occur.

The idea of underlining with an additional solid black line:

![1](https://user-images.githubusercontent.com/62179190/180297680-39611de4-70e1-4290-b199-808bc10c62b7.png)

![2](https://user-images.githubusercontent.com/62179190/180297683-55270b25-8b36-4951-a715-dc7304e60f07.png)

![3](https://user-images.githubusercontent.com/62179190/180297685-8be98431-cccd-48f3-9552-34b335b64efa.png)

![4](https://user-images.githubusercontent.com/62179190/180297686-8f05f849-099d-4bdc-b59f-bd756fed268e.png)

**Comment by zwim** [comment]
Also not using this feature, the first, the second and the last version looks intuitive to me.

@hius07: I am very happy that you are here again. I'll keep fingers crossed for you.

**Comment by mergen3107** [comment]
I am fond of the inverted highlight mode. Will it look the same in the night mode as well?

If the pencil is too large, how about putting the pencil sign as a superscript after the highlighted note? So if the same line contains s few notes, we will easily see them. 

Also, I remember Kindle native ereader shows those superscripts as a number in a box, so all notes are enumerated. Not sure if KOReader should be this thorough

**Comment by hius07** [comment]
> Will it look the same in the night mode as well?

"Invert" highlight style, night mode:

![5](https://user-images.githubusercontent.com/62179190/180314968-5079cdf8-2e19-4157-8cec-b07c8b40e9b0.png)

**Comment by offset-torque** [comment]
**+1 for "underlining with an additional solid black line"**
As an inverted highlight user, it looks clear enough to me.

Another suggestion:
 **A vertical line next to the highlight**
- Can work with tiny margins
- Very unobtrusive, doesn't crowd the text, but still visible

![note_icon 2](https://user-images.githubusercontent.com/84420582/180330316-96e37cb8-b77b-4fcf-838d-368fc1fd38ed.png)

**Comment by WolfgangDpunkt** [comment]
I like the "vertical line next to the highlight" idea.
It is distinct enough from the other highlighting methods and should be easily recognisable even in night mode. And it corresponds to the analogous behaviour with text corrections on paper, you change/add something in the text and then mark on the right with a vertical line that there is a change/addition here. That is therefore very intuitive.

**Comment by hius07** [comment]
Vertical line

![11](https://user-images.githubusercontent.com/62179190/180435853-1dd2cc7b-1ea8-4853-a208-8e15f683ceee.png)

![12](https://user-images.githubusercontent.com/62179190/180435856-5fca80bf-e48e-4e57-8a62-5e0a90cc8a87.png)

![13](https://user-images.githubusercontent.com/62179190/180435860-f5770ead-3015-4cb9-b2f0-1f1f5601b51d.png)

![14](https://user-images.githubusercontent.com/62179190/180435861-5cd96e20-49e4-4fca-90b5-56df0534b666.png)

**Comment by hius07** [comment]
Right margin 70

![15](https://user-images.githubusercontent.com/62179190/180437128-9a847026-590c-43ed-83ba-6a9e372e4589.png)

Right margin 5 (the line is not visible, no room for it)

![16](https://user-images.githubusercontent.com/62179190/180437202-01459167-8343-4bfc-86c1-5843dfb55059.png)

**Comment by hius07** [comment]
Two hl's in a line, cannot distinguish which one is a note

![17](https://user-images.githubusercontent.com/62179190/180437773-bd2bef45-c9d6-43bd-9181-653e16a800db.png)

**Comment by hius07** [comment]
Not very nice for pdf (vertical line position is fixed, as the right edge of the text is flexible depending on the view/zoom mode)

![21](https://user-images.githubusercontent.com/62179190/180442421-4255db89-331c-4bb8-82e5-8705eb7e8c32.png)

![22](https://user-images.githubusercontent.com/62179190/180442425-7fb21495-0ad6-45aa-b366-6afa4f888a5e.png)

![23](https://user-images.githubusercontent.com/62179190/180442427-4654739b-a307-4c3a-84de-71eff97e6d47.png)

**Comment by hius07** [comment]
A pencil sign

![31](https://user-images.githubusercontent.com/62179190/180518150-931da76c-74dc-4471-ac93-0ea0781a4ac8.png)

![32](https://user-images.githubusercontent.com/62179190/180518166-6bd2ffcc-86a9-45ad-a0fc-3a76dc309c52.png)

**Comment by NiLuJe** [comment]
I'd imagine the pencil approach suffers from the same margins constraints, though? ;).

**Comment by hius07** [comment]
Yes, right margin not less than 20 (the fourth square of the scale).

So, to summarize
1) underlining
2) side vertical line
3) side mark (pencil)
4} inside mark drawn over the text (not inserted)

**Comment by offset-torque** [comment]
Since all styles have advantages/disadvantages maybe we can implement them all and leave the decision to the user ?

- For example if they find **extra underline** too crowded they can sacrifice right margin for the minimalistic **vertical line**
- If their eyesight is not very good **OR** they want a glanceable indicator they can choose the **pencil**, most visible of them
- If they are studying language and they need many highlights on the same line **OR** they find margin indicators too ugly, they have the **extra underline** option

**Comment by hius07** [comment]
![51](https://user-images.githubusercontent.com/62179190/181803331-e9589397-2597-44ec-9e4c-093d43ac9d65.png)

![52](https://user-images.githubusercontent.com/62179190/181803335-7fbabc0d-f806-4ee0-82df-91788922119e.png)

![53](https://user-images.githubusercontent.com/62179190/181803337-b1a343f9-3e9b-4bc7-a492-cb54cdade67b.png)

![54](https://user-images.githubusercontent.com/62179190/181803338-e3a89aa6-ca06-4727-a4b1-f040a51e668e.png)

![55](https://user-images.githubusercontent.com/62179190/181803341-d7ba79e1-5aec-473e-8825-f04228989797.png)

**Comment by WolfgangDpunkt** [comment]
Thanks a lot! this looks great, and the flexible settings should suit and benefit everyone. Very excited to try this out.
>

**Comment by offset-torque** [comment]
Wow. All three implemented ! They look very cool :1st_place_medal: 
I will add usage info to the user guide after trying them myself.

One thing:
 **Side Line** might look too faint on e-ink screen, especially when:
- it is next to an **invert** highlighted paragraph 
- in low light conditions 
- it is very close to the bezel due to thin margins

Maybe line can be a bit wider (two more pixels ?)
This would improve glanceability.
(By the way line to text distance looks perfect)

**Comment by poire-z** [comment]
No real opinion as I never add notes. I would have preferred to find a single way (inline, and not in the margin) to show that, but if there isn't any, I'm fine with this multiple options idea.

**Comment by hius07** [comment]
> Maybe line can be a bit wider (two more pixels ?)

More screenshots with a thicker line in the PR thread.

**Comment by WolfgangDpunkt** [comment]
Once again, thank you very much for your great work!
Fast, well thought out, super useful and user friendly, I am very amazed.
