### ISSUE TITLE
UI trap

### ISSUE THREAD

**Issue by aosfan** [koreader/koreader#9366]
* KOReader version: v2022.06
* Device: Kindle 4 D01100

#### Issue
If you open **Typeset → Style tweaks → Book-specific tweak**, it opens an editor from which you cannot exit on a non-touch device.
Rebooting does not help, the device boots with the editor on the screen.
I miraculously managed to reboot my kindle to the original system after several attempts.

#### Steps to reproduce
Typeset → Style tweaks → Book-specific tweak

**Comment by Frenzie** [comment]
I thought you should be able to exit since https://github.com/koreader/koreader/pull/8859

**Comment by NiLuJe** [comment]
> Rebooting does not help,

Nit: That wasn't a reboot ;).

Long-press the power button to actually trigger a hard reboot. (IIRC, "long" is *really* long on early Kindles, ca. 10 or 15s).

**Comment by Commodore64user** [comment]
this should be closed as it is no longer the case. I just tried it, back button twice does it.

**Comment by Frenzie** [comment]
Alright, thanks.
