### ISSUE TITLE
FR: Disable file history

### ISSUE THREAD

**Issue by Forum1877621** [koreader/koreader#9367]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently, when you open a file it's saved to the history. I would like for there to be an option to disable file history completely, which would include not remembering the last page that was read or any other information.

**Describe the solution you'd like**
An option to disable the recently read history

**Comment by poire-z** [comment]
Sounds really too "niche" to be made an option (and having us need to test we haven't broken it in the future).

You can probably help yourself with a user patch https://github.com/koreader/koreader/issues?q=label%3A"User+patch+available".
By overriding/making no-op some functions like these:
https://github.com/koreader/koreader/blob/bbc5652c1d5957d94aaba379bde143ecfa5fa173/frontend/readhistory.lua#L284
https://github.com/koreader/koreader/blob/bbc5652c1d5957d94aaba379bde143ecfa5fa173/frontend/docsettings.lua#L301-L302

**Comment by Forum1877621** [comment]
![image](https://user-images.githubusercontent.com/109703756/181138733-f078ed48-54c2-4e05-a284-8187ddabe74f.png)
