### ISSUE TITLE
Android: Unresponsive touch upon wake up

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9368]
* KOReader version: 2022.06 with landscape fix
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
I am not sure how to reproduce this issues for good. However, I am _pretty_ sure it is due to enabling Battery Statistics plugin.

So after waking up, the touch input seems half responsive or unresponsive at all. Putting the device to sleep and waking up again helps. Usually, if it happens, it only happens right after sleep. And if it hasn't manifested itself right away, it won't show up even in 8 hours reading session. So the issue is minor but I still would like to trace it down, maybe something fundamental is being broken. 

#### Steps to reproduce
Open KOReader
Put device to sleep
Wake up
Touch inputs are half-responsive. Especially in entering device's PIN code.
*If there is no PIN lock, touch to advance pages or swipe do not work. 

*I have the option of delayed PIN lock. So if I unlock now, putting device to sleep within less than 30 minutes won't lock it again. 
This is how I now that the PIN lock screen itself is not to blame: the touch input can have the same misbehavior in the cases of no PIN wake up as well. 

If I disable Battery Statistics plugin, I am not able to encounter this bug at all.
The plugin itself works fine, by the way.

##### `crash.log` (if applicable)
I put verbose logging on and... forgot about it :D. So maybe I was able to catch the issue, or maybe not. Do you see anything suspicious in here?
[crash_Battery_Stat.log](https://github.com/koreader/koreader/files/9180200/crash_Battery_Stat.log)

How about `Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe53fca64 in tid 28619 (Thread-5038), pid 28619 (Thread-5038)` on line 84?

Meanwhile I am trying to catch it for sure.

**Comment by pazos** [comment]
Onyx is **always** pain

https://www.mobileread.com/forums/showthread.php?t=339597

https://github.com/koreader/koreader/issues/7798
https://github.com/koreader/koreader/issues/7052

Some models seem broken by design while others work without problem.

I won't plan to look at it unless you can reproduce elsewhere

**Comment by mergen3107** [comment]
Thanks! I’ll do my best to catch it :D
