### ISSUE TITLE
desktop linux branch cannot open local opds library

### ISSUE THREAD

**Issue by dandelions** [koreader/koreader#9373]
* KOReader version:2022.6
* Device:desktop linux

#### Issue
when I add local opds library,opds plugin shows that "open wifi connection?"
as you know,desktop hasnot a wifi ,so the plugin can support a wired connection?
thanks !
##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Frenzie** [comment]
Wifi just means a connection. You're saying you don't see the message if you try to use one of the predefined defaults?

Btw, Desktop Linux is kind of meaningless to write. ;-)
