### ISSUE TITLE
Ask : How to use SSH for transfert ebook without usb ?

### ISSUE THREAD

**Issue by liberodark** [koreader/koreader#9378]
Hi,

My question is for Pocketbook Inkpad 3.
How to use SSH for transfert ebook without usb on Koreader ? 
And ssh is possible on koreader or have been removed/disabled ?
And why sftp is not supported in cloud add ?

Have read this : https://github.com/koreader/koreader/wiki/SSH
But i dont see SSH Server.
But have see SSH.koplugin in plugin folder.

Probably have missing something...

Best Regards
Thanks for your great work

**Comment by pazos** [comment]
Is not supported on pocketbooks. That's the intended behaviour. You won't see it on the UI

**Comment by pazos** [comment]
probably a good idea to update the wiki

**available on kobo, kindle, cervantes**

**Comment by NiLuJe** [comment]
On the other hand, there are "native" SSH packages offered by hobbyists for PB, check on mobileread ;).

**Comment by offset-torque** [comment]
Noted for **User Guide** update

**Comment by liberodark** [comment]
Yes have try pbsshd 1.6 without success. @NiLuJe

**Comment by liberodark** [comment]
And no have possibility to add SSH on Pocketbook 
[pbsshd_1.3_fwv5.zip](https://github.com/koreader/koreader/files/9212976/pbsshd_1.3_fwv5.zip)
[pbsshd_1.3_fwv6.zip](https://github.com/koreader/koreader/files/9212977/pbsshd_1.3_fwv6.zip)
?

**Comment by pazos** [comment]
no without killing a few hundred puppies :/

pd: wiki updated
