### ISSUE TITLE
ASK: Install on stock bq devices

### ISSUE THREAD

**Issue by tronxi** [koreader/koreader#9379]
I am using a fnac touch plus with the stock firmware,
I know that bq no longer exists, but is there any way to install the developer firmware?
In case there is no way, can koreader be installed in some other way?

Currently the device asks to activate an account in nubico (the web does not work https://www.nubico.es) to use the dictionary, could I bypass that limitation in some way?

**Comment by pazos** [comment]
> but is there any way to install the developer firmware?

yes, https://www.mobileread.com/forums/showpost.php?p=4225738&postcount=36

> can koreader be installed in some other way?

nope
