### ISSUE TITLE
Keep dots in vocabulary builder

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9383]
Personally, I would prefer the three dots to remain in the vocabulary builder throughout the learning process. Spaced repetition may extend over several weeks or months, and it would be helpful to be able to see the context.

Dear @weijiuqiao, what do you think?

**Comment by weijiuqiao** [comment]
Seems legit. Let me try and make some changes over the weekend.

**Comment by Frenzie** [comment]
Fixed by #9393.
