### ISSUE TITLE
Pocketbook: Not able to change time and date without root

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9384]
* KOReader version: v2022.06-44-g9d71333a_2022-07-28
* Device: PocketBook 626

#### Issue
Can not set time and date.

#### Steps to reproduce
1. Invoke top bar
2. Tap gear-wheel
3. Tap Device
4. Tap Time and date
5. Tap set time (set date)
6. Set some time (date)
7. Small window with "new" time appears but it shows the "old" time (date)

##### Crash log 
[crash_20220728201240.log](https://github.com/koreader/koreader/files/9213218/crash_20220728201240.log)

From line 1246 is this:
date: can't set date: Operation not permitted
Thu Jul 28 20:10:00 CEST 2022
hwclock: RTC_SET_TIME: Permission denied

**Comment by Frenzie** [comment]
In that case I doubt we can do it, but that does raise the question if it ever worked on other PB devices?

**Comment by pazos** [comment]
works on rooted devices

**Comment by NiLuJe** [comment]
Possibly doable without root via some sort of `iv_ipc_*` command w/ `MSG_SETTIME`, but someone with a device would have to figure the gory details out ;).
