### ISSUE TITLE
Pocketbook: widgets with timeouts don't disappear with autostandby plugin enabled

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9385]
* KOReader version: v2022.06-44-g9d71333a_2022-07-28
* Device: PocketBook 626

#### Issue
After frontlight toggle the small message "Frontlight disabled" or "Frontlight enabled" on top of the screen is not disappearing until next touch or button press.

#### Steps to reproduce
1. set frontlight toggle "action" for some tap zone e.g. I have set it for left bottom corner
2. open some ebook
3. tap left bottom corner to toggle frontlight
4. small message "Frontlight disabled" or "Frontlight enabled" on top of the screen is shown ... and does not automatically disappear

**Comment by pazos** [comment]
Try to reproduce with autostandby plugin disabled

**Comment by sonix-github** [comment]
Thanks for the hint. After disabling of "autostandby" the message disappears after ~2 seconds or so

**Comment by pazos** [comment]
I'm afraid it's not fixable.

You can tweak the autostandby plugin settings to make the awake time bigger and will fix things below the threeshold but anything above that won't work as expected.

The only way of having a sane delayed execution is to disable autostandby but that hurts battery so bad :/

**Comment by sonix-github** [comment]
Maybe if I can shorten the time for the status message of frontlight to 0.5 seconds it can be "fixed". But I have no idea where is such setting.

**Comment by pazos** [comment]
> Maybe if I can shorten the time for the status message of frontlight to 0.5 seconds it can be "fixed". But I have no idea where is such setting.

That's not a fix. Is a workaround that you'll need to apply to each widget instance that sets a timeout >= 2. Have a look at https://github.com/koreader/koreader/search?p=4&q=timeout+%3D

**Comment by sonix-github** [comment]
@pazos 
I was looking for something like autostandby timer reset, but I have not found a way how to do it. Then I found function _UIManager:preventStandby()_ and _UIManager:allowStandby()_ and added it to function **onShow** in _notification.lua_ widget. Now the message disappears as expected. I do not know if this can be accepted as a fix or workaround, but it helped me to solve the issue.

```
function Notification:onShow()
    -- triggered by the UIManager after we got successfully shown (not yet painted)
    UIManager:setDirty(self, function()
        return "ui", self.frame.dimen
    end)

    if self.timeout then
        UIManager:preventStandby() -- no standby until notification disappears
        UIManager:scheduleIn(self.timeout, function()
        UIManager:close(self)
        UIManager:allowStandby() -- allow standby after notification disappeared
        end)
    end
    return true
end
```

**Comment by NiLuJe** [comment]
Those two functions have *very* specific and tricky semantics, so I'm not entirely sure this is a sane approach ;).
