### ISSUE TITLE
How to remove the gray divider between pages in scroll mode?

### ISSUE THREAD

**Issue by WeihuaGu** [koreader/koreader#9389]
Removing the dividers helps to see certain webtoon comics

**Comment by poire-z** [comment]
There's no menu to tweak that, but it can be done manually (and so it's global).
Add one of these in your koreader/settings.reader.lua
```
["page_gap_color"] = 15, -- black
["page_gap_color"] = 0, -- white
```

**Comment by mergen3107** [comment]
@WeihuaGu 
A general question, do you need help with comics on KOReader? :D What format are you currently using?

**Comment by WeihuaGu** [comment]
@poire-z How to change the width instead of the color

**Comment by WeihuaGu** [comment]
@mergen3107 I use the comand convert of imagemagick to  convert jpg into pdf. If  the pictures could be viewed continuously under a folder，it would better

**Comment by poire-z** [comment]
> How to change the width instead of the color

![image](https://user-images.githubusercontent.com/24273478/181733708-38d940c7-f057-4c9e-8f04-ef1d465d3934.png)

**Comment by mergen3107** [comment]
`If the pictures could be viewed continuously under a folder，it would better`
@WeihuaGu 
Your best option is to pack them into a CBZ file using Kindle Comic Converter. This is in case your pictures are not toooo long vertically

**Comment by WeihuaGu** [comment]
it work and i know how to change the divider color. thinks

**Comment by WeihuaGu** [comment]
@mergen3107 Now it's a picture in a folder. Open the first one, then click Turn Page. You can only click the file browser first, and then click the second picture in the browser. For pictures that can't be in a folder, click Turn Page to automatically next one.

**Comment by mergen3107** [comment]
@WeihuaGu 
Yes, this is what CBZ format is for, just pack your pictures to a zip archive, rename the extension from `zip` to `cbz` and open in KOReader

**Comment by WeihuaGu** [comment]
@mergen3107 I tried the cbz format, which is convenient. Thank you.

**Comment by mergen3107** [comment]
@WeihuaGu 
Great :) ping me if you need more help on manga and conversion
