### ISSUE TITLE
Profiles: UX umprovement suggestions and tips

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9391]
* KOReader version: 2022.06
* Device: Onyx Boox Kon-Tiki 2

#### Profiles are great!
This is not an "issue" ticket, but rather my reflection on the usage with some suggestions on how to improve the UX experience using Profiles overall.

**Thank you very much** to all those who implemented this great feature!

#### But...
1) **Action to apply profiles.** Currently, to apply a profile, we need to long-tap it. However, I had to find this out by trial and error. Just taping it, brings it to the profile settings, which is OK, but there is no suggestion or tip about long-tap. 

As for suggestions, I am not really sure what is actually available technically. My first thoughts are these. Add three dots on the same line, tapping on which will bring to the profile settings, but tapping on the profile itself activates it.

Another suggestion, if the first one is cumbersome/impossible, is to add `(long-tap to apply)` to each of profile names or somewhere at the top (like it is done when choosing a folder). 

Third, more elegant suggestion, is to show tick mark next to the profile if it was activated. Tapping activate a profile, long-tapping brings the settings. Idea here is that users more or less got used to tick marks so that "single tap to apply" is obvious. Tick marks should only be shown, I think, if user actually hit it once, because I think checking the current settings against all profiles is computationally wasteful.

2) **Rename profile.** I wasn't able to find a way to rename a profile in KOReader. Currently I do this by hand, in `koreader/settings/profiles.lua`. 

**A side note** about sorting in Profiles' and Fonts' menu. Is it intentional that lower case is sorted after upper case? For example, I have a font named `inglobal` with lower case, and it is put at the end of the lists. I wondered for a long time why it is like that, then just thinking it must the font's quirks, but I stumbled upon the same thing when I renamed the profile from `Inglobal` to `inglobal` - it was put from the proper place in the alphabet to the very end. I guess I can't understand that better because on Windows there can't be both `Folder` and `folder` directories existing, and I don't know how it is done on Linux ("natural sorting", something-something :D).

3) There should be a mention in the profiles about their **permanent state of applying settings** (not sure how to name it properly). By that I mean, for example, if `Profile 1` sets `Font weight` to, say, `1/2`, then `Profile 2` without `Font weight` is **not** going to revert the `Font weight` to the value before `Profile 1` was applied. So currently I fight this simply by making sure that all same-kind profiles are explicitly setting those settings. These are `Font face`, Font size`, `Font weight` and `Line spacing`.

However, If a new metric is going to be added to font-altering profiles, say `Contrast`, then this must be added to all such profiles. This should be either mentioned the manual or changed somehow. However, I totally understand the point of not reverting it to pre-`Profile 1` state because it is cumbersome to track these settings. Let's discuss :D 

This is it so far. I have set a bunch of font-specific profiles so that each page contains exactly 30 lines of text in each profile. This is on a 7.8-inch screen at 160 dpi in the `Screen` options in the top menu, `Ignore publisher's line spacing` Style tweak enabled, and Alternative status bar. This makes it a little easier to judge the length of the book at any given profile (+/- 5-7% at least) and keeps my OCD triggers off :D 

Here are the profiles for those interested:

<details>
  <summary>koreader/settings/profiles.lua</summary>

```
-- we can read Lua syntax here!
return {
    ["Academy"] = {
        ["font_base_weight"] = 0.5,
        ["font_size"] = 32,
        ["line_spacing"] = 107,
        ["set_font"] = "Academy Old",
    },
    ["Bitter"] = {
        ["font_base_weight"] = 1,
        ["font_size"] = 25.5,
        ["line_spacing"] = 116,
        ["set_font"] = "Bitter",
    },
    ["Bookerly"] = {
        ["font_base_weight"] = 0,
        ["font_size"] = 25.5,
        ["line_spacing"] = 107,
        ["set_font"] = "Bookerly",
    },
    ["Caecilia"] = {
        ["font_base_weight"] = 0,
        ["font_size"] = 26,
        ["line_spacing"] = 102,
        ["set_font"] = "PMN Caecilia LT",
    },
    ["Comic Sans MS"] = {
        ["font_base_weight"] = 0,
        ["font_size"] = 26,
        ["line_spacing"] = 99,
        ["set_font"] = "Comic Sans MS",
    },
    ["Gill Sans"] = {
        ["font_base_weight"] = 0,
        ["font_size"] = 26,
        ["line_spacing"] = 99,
        ["set_font"] = "Gill Sans",
    },
    ["inglobal"] = {
        ["font_base_weight"] = 0.5,
        ["font_size"] = 29,
        ["line_spacing"] = 108,
        ["set_font"] = "inglobal",
    },
    ["Literata"] = {
        ["font_base_weight"] = 0.5,
        ["font_size"] = 24,
        ["line_spacing"] = 99,
        ["set_font"] = "Literata",
    },
}
```

</details>

**Comment by poire-z** [comment]
> For example, I have a font named `inglobal` with lower case, and it is put at the end of the lists. I wondered for a long time why it is like that, then just thinking it must the font's quirks

I guess we just do ASCII-sorting, and never thought it would be best to do it differently :)

A bit related, some thoughts of mine about profiles: https://github.com/koreader/koreader/pull/8713#issuecomment-1024973925
The thing is that currently (the implementation), _a profile is an unordered collection of actions, with a name_ ; it's not a collection of settings, as you (naturally, I think) apprehend it.

(Even if I don't use profiles, I think associating a profile to a gesture might be a nice feature.)

**Comment by Frenzie** [comment]
>  I stumbled upon the same thing when I renamed the profile from Inglobal to inglobal

As someone whose surname starts with "de" I'm intimately familiar with that problem.

**Comment by mergen3107** [comment]
`a profile is an unordered collection of actions, with a name`
Yes, I understood it that way :D like, a macro triggered manually. However, it took me some time to realize

**Comment by offset-torque** [comment]
I think it is time to add **Profiles** to the user guide.
Since I am not using this feature and it seems that a profile can do everything, it is hard to imagine the possibilities.
While everyone is here, can I get some examples for profiles that might be useful for an average user.
I want to tell users **"Here are some cool things you can do with the Profiles feature"** :)

Regarding UX, I think currently only way of triggering a profile is going to the related menu.
In my case this means:
- Swipe down to open top menu
- Tap **Plugins** menu
- Tap **Page 2**
- Tap **Profiles**
- Long tap profile name to trigger

I think this is too cumbersome and a big obstacle for wider adoption.
At least users should be able to trigger profiles with a gesture as **poire-z** said.

For an easier UX I want to remind my [Favorites Menu FR](https://github.com/koreader/koreader/issues/8701#issuecomment-1019253421)
If something like that is implemented, it might be used for triggering profiles too and allow one tap profile changes.

**Comment by mergen3107** [comment]
So far I can think of:
- Night/Day profiles
- Font-specific profiles
- Profiles for PDF reading (crop/contrast, maybe)

**Comment by NiLuJe** [comment]
AFAIU, the preferred method of triggering a profile is via a gesture, not the actual profile list?

**Comment by Frenzie** [comment]
Yup, doesn't mean it can't improve of course. :)

**Comment by mergen3107** [comment]
@NiLuJe 
For myself, it’s OK to switch from the list since in this particular case I do that once a book. 

But for night/day profiles - I’d image gestures are much better

**Comment by mergen3107** [comment]
Two more comments on how to improve the Profiles plugin:
1) When selecting some settings, like `Font`, `Font weight`, the menu with choices stays. However, since the these parameters are not applied right now, there is no point of staying here. So I think it is better to leave the menu once the choice is made. These are not the parameters where multiples things can be selected, right?

2) When selecting `Font size` or `Line spacing`, in the window with size selector it says `Default is 22` for `Font`, for example. However, this is not the default! I previously set the default font size to be 26 in the bottom menu. The same goes for `Font weight`, and some others.

**Comment by hius07** [comment]
See some improvements in https://github.com/koreader/koreader/issues/8701#issuecomment-1249608740.

**Comment by hius07** [comment]
Anyways, the issue is mostly non applicable after https://github.com/koreader/koreader/pull/9526.

**Comment by mergen3107** [comment]
Dear @hius07 ,
Thank you for the implementation! I am going to test this upcoming week. Interestingly, "profiles" got extended to usual actions, not only book-specific :D
