### ISSUE TITLE
FR: Include Vi with terminal emulator

### ISSUE THREAD

**Issue by Ketrel** [koreader/koreader#9401]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently the terminal emulator does not include vi, and if the underlying device doesn't include it, it can't be used.  With it, it would allow for things like creating user style tweaks on the device itself

**Describe the solution you'd like**
Include a vi/vim binary

**Describe alternatives you've considered**
Include some other text editor binary for use with the terminal emulator

**Additional context**
Normally it seems like it'd be outside the scope of an ereader app, but so does a terminal emulator, and """You miss 100% of the shots you don't take." -Wayne Gretzsky" -Michael Scott" -Some IRC dude

**Comment by NiLuJe** [comment]
Well played. Even went the extra mile of going with vi instead of jumping straight to Emacs, because that would have been too obvious ;).

**Comment by poire-z** [comment]
> it would allow for things like creating user style tweaks on the device itself

One can do that with the Text Editor plugin, #4135 (funny seeing these screenshots of that young koreader :)
