### ISSUE TITLE
Progress bar freeze

### ISSUE THREAD

**Issue by roaminghawk** [koreader/koreader#9404]
Hi,

When opening koreader, loading books, changing font sizes or anything that requires a reload of the book, the progress bar freezes at the end before completion. If I tap the screen or use the buttons it resumes loading. When the book file is big (6 megabytes for example) the freezing happens several times during loading. Have to tap or click several times to get the progress bar going. The device is a Boyue T62D with a custom firmware from the Onyx magicbook.
Is this normal? Is there an option to alleviate this behavior? How to go about diagnosing it further?

Thanks.

* KOReader version: 2022.07,2022.06
* Device: Boyue T62D with a custom firmware from the Onyx magicbook.

**Comment by pazos** [comment]
> Is this normal?

no

> Is there an option to alleviate this behavior? 

no

> How to go about diagnosing it further?

go to settings -> screen -> screen timeout and check "keep screen on". See if you can reproduce again.

**Comment by poire-z** [comment]
It's probably not KOReader's fault.
I guess this system/firmware has a trick to suspend the device's cpu N seconds after a touch event on the screen, assuming that when a user tap to change page, the software will need less than N seconds to render the page, and then, we can sleep to save battery life and wait for the next tap/touch/swipe to wake up again and process that event.

There are a few sections in the code that may need a bit of time, possible more than these N seconds, to do their job. I can think of the full book rerendering you mention, but also:
- wikipedia save as EPUB
- Filemanager, top right <kbd>+</kbd> button, `Extract and cache book information` : this will ask you a few questions, and then proceed to read the metadata of all your books, and show the one it is currently dealing with in a popup. It should pause, and resume once you tap it (may be swipe, as tap is used to interrupt the process). Can you check that to see if you get the same behaviour ?

If yes, I guess there's not much we can do.
You could try seeing in this firmware if there's an option to disable this battery-life-saver feature - but then you won't save battery.
Or may be at the Linux OS level, there are /proc/ or /sys/ files to control the behaviour. We won't probably add them to KOReader, but you could "user-patch" your koreader to plug disabling/renabling this in the few methods that we know can need some time (I know some of them, I could provide the hacking points).

Unless all this is Android :) and @pazos knows it better than I do - and my solution may be not usable on Android.

**Comment by roaminghawk** [comment]
Thank you very much for the reply.

Going to settings -> screen -> screen timeout and checking "keep screen on" instead of using "use system settings" does help a lot, but does not remove the problem entirely, it still freezes once in a while, but it's not contestant freezing like before. Setting the screen timeout to anything but "keep screen on" is the same as "use system settings" and brings the freezing back.

Another thing to note, with "keep screen on" enabled, opening books that were previously opened is almost instantaneous, not like when using the "use system settings" for screen timeout which always shows a window saying loading book name and I had to tap it to "unfreeze" it, and when opening KOReader, now it opens instantaneous and does not show that message.

I agree it's not KOReader's fault, I've watched a lot of youtube videos of KOReader on other devices and it does not do that, it also does not do that behavior on my phone. I also agree that there are some suspend cpu instructions built into the firmware.

Trying "Extract and cache book information" freezes every 4th or 5th file, even when "keep screen on" is enabled. It's the same behavior with any option in the screen timeout setting window. But "keep screen on" works almost fine with normal operations.

There is no options visible in the firmware settings to disable battery saver.

Another thing, with "keep screen on" the device turns off the screen after 5 minutes, instead of even the 10 minutes set the system settings. Which is good for me since now I can keep the screen awake option and not worry about the leaving the screen on the going to sleep.

I think you can mark the issue as closed since I don't think it's wise to waste so much time on an issue affecting only one person, and it's mostly resolved using the keep screen awake option.

I have an unrelated question. What device do you guys recommend for KOReader? I've always leaned toward the android ereaders for the freedom of choosing my own reading software. Now with KOReader available for all eink devices, the options are back open to Kobo, kindle or anything else. So what do you recommend?

**Comment by Frenzie** [comment]
Fwiw, I believe most of the devs use a Kobo.

**Comment by offset-torque** [comment]
> I've always leaned toward the android ereaders for the freedom of choosing my own reading software. Now with KOReader available for all eink devices, the options are back open to Kobo, kindle or anything else. So what do you recommend?

That was my dilemma when choosing my reader. But IMHO Android is not suitable for an e-reader device with its memory hogging 400+ google play services, unpredictable and extreme background app behavior (kill everything and prevent multitasking or allow everything and drain battery), mysterious wakelock behaviors which prevents your device going into deep sleep etc. etc.

I don't want to charge my e-reader like my phone. I need a predictable and optimized device, not a generic SOC tablet with Android lazily slapped on. 

I have a Kobo Libra and KOReader works perfectly. I had no problems with this device. No need for custom ROMs, ADB, root, tweaking etc. It just works.

But if you want to use your device more like a tablet than a single purpose e-reader, unfortunately your only option is the Android ecosystem.

**Comment by roaminghawk** [comment]
My thoughts exactly. 
This T62D that I have is the third android based e-reader that I owned. 
Over time I found that I don't use anything more than the e-reader app, Cool reader at first, then AIreader and now thankful KOReader. Also the reason for choosing an android was the ease of side loading epub files, but with KOReader's calibre plugin that's not needed anymore. Or even a file browser.

I just wish that Kobo had a better browser. All the reports say that it's browser is rudimentary at best.
I was leaning towards the Kobo Sage for the form factor and the powerful processor, but all reports say battery life is abysmal on that device, which leaves me the Kobo Libra 2.
Any feedback on those two devices is highly appreciated.

**Comment by NiLuJe** [comment]
The Libra 2 is currently a horribly broken mess (pending reports on a newer hardware revision, which may or may not have anything to do with the original board's issues).

**Comment by roaminghawk** [comment]
Thanks for the heads up. 
Could you please point me where those problems are reported? 
I found this bug :https://github.com/koreader/koreader/issues/9218 but can't find more.

So what now? Wait for an new hardware rev. or wait for a new model? And how would I know if the unit I'm ordering is a new revision or one of the old ones?

**Comment by NiLuJe** [comment]
That would be #9038 (and the various reports on MR of instability even on the stock system).

I'm not aware of a way of identifying the new hardware revision without having shell access to the device (specifically, running `ntx_hwconfig -l -s /dev/mmcblk0` and checking if the PMIC is a BD71828 (new rev).
