### ISSUE TITLE
Strange crash of a book opened a long time ago

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9405]
* KOReader version: 2022.06 with Android landscape fix
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue

The book: 
[Карлос Кастанеда - Учение Дона Хуана Путь Знания Индейцев Яки.fb2.zip](https://github.com/koreader/koreader/files/9253966/-.fb2.zip)

1) So I opened this book more than a year ago in KOReader, on a very older version.
2) I opened the book again. The screen was refreshed to white and the popup was up saying the book is being opened - all this is usual.
3) But then it crashed.
4) I tried to open KOReader again - and because I have `Open last book upon start` setting, it tried to open the book again, and crashed again. Android complaine that the app stops responding and suggested me to Close it, Freeze it and see its info.
5) I wasn't able to get crash.log, so I connected via SSH and did a logcat while opening KOReader.

6) Then I removed the old sdr folder of that book, and `et voilà`! It opened just fine.

I hope that you guys can see what was wrong, so we can fix this for good. But I regret deleted that old sdr folder :(

##### `crash.log` (if applicable)
First, when I wasn't able to fire up KOReader again, I tried to do logcat while tried to open it:
[crash_logcat.txt](https://github.com/koreader/koreader/files/9253945/crash_logcat.txt)

And this the crash log extracted after I renamed the old sdr folder:
[crash.log](https://github.com/koreader/koreader/files/9253944/crash.log)

Unfortunately, I hastily deleted the old sdr folder, sorry guys :(

**Comment by poire-z** [comment]
Looks like a crengine crash, but nothing else insteresting in the log.
I think that without a way to reproduce it (we could have been lucky with the old .sdr/), there's not much I can guess about the cause of the crash :/

Do you remember if there could have been some highlights/bookmarks in that book ?
Do you remember when you first opened that file ? The Statistics plugin may tell you that - and we can guess which cre_dom_version was the current version at the time - and set it manually in a metadata.lua, and see.

**Comment by mergen3107** [comment]
No, definitely there were no highlights and stuff, because I haven’t read the book back then. There is also a minimal chance of having statistics plugin, because I have a habit of removing statistics for books < 5 min (great feature, btw :D). 

I’ll try to recover the deleted file, or try to get another book I opened nearly at the same time back then to see if I can reproduce it =\

**Comment by mergen3107** [comment]
I suppose that might be the same issue as #9961 (wrong, too small, cache size leftover from Kindle on Android)
