### ISSUE TITLE
FR: [Hope to add a built-in web browser]

### ISSUE THREAD

**Issue by thudayu** [koreader/koreader#9407]
Hope to add a built-in web browser, so can browser a web page easily.
Thanks very much!

**Comment by Frenzie** [comment]
Sorry, no. ;-)

Also see #3948 among others. But you can use the likes Links 2/Elinks/Lynx in the terminal emulator if desired.

**Comment by avalonv** [comment]
> Sorry, no. ;-)
> 
> Also see #3948 among others. But you can use the likes Links 2/Elinks/Lynx in the terminal emulator if desired.

Do I need to manually install these? Any pointers for how to do so?

**Comment by Frenzie** [comment]
It depends on the device whether you even really can, but essentially yes. I wrote a little bit about what I do here: https://github.com/koreader/koreader/releases/tag/v2022.02 

Though I don't use the device for web browsing; I merely mean that I find it the easiest way to quickly install a bunch of tools including Elinks. ;-)

**Comment by avalonv** [comment]
Yeah I absolutely don't plan to use it for casual web browsing. I just thought it would be useful for quickly copying a key (in my case I needed a dropbox auth token), without having to fiddle with ssh, although I ended up using wget for that in the end (curl is broken).
