### ISSUE TITLE
Cloud storage missing

### ISSUE THREAD

**Issue by Giorgina83** [koreader/koreader#9413]
Hello.

I installed koreader and nickelmenu with the one-click package on my Libra H2O but there is no cloud storage plugin in koreader.

I uninstalled/reinstalled but it's still the same.

Can you help me please?

![IMG_20220805_200626_1](https://user-images.githubusercontent.com/28791009/183220472-05ef72a1-81fd-4df1-919d-96113ff58078.jpg)

**Comment by mergen3107** [comment]
It is only available from the file manager, not from the opened book

**Comment by Giorgina83** [comment]
> It is only available from the file manager, not from the opened book

I'm sorry, how can I access the file manager? 

I don't understand because I saw on screenshots of other users "Cloud storage" with all others plugins.

**Comment by NiLuJe** [comment]
Tap the "file cabinet" icon (right next to the looking glass).

**Comment by Giorgina83** [comment]
> It is only available from the file manager, not from the opened book

I'm sorry, how can I access the file manager? 

I don't understand because I saw on screenshots of other users "Cloud storage" with all others plugins

> Tap the "file cabinet" icon (right next to the looking glass).

Thank you NiLuje. I did see it before, looked in folders but nothing named "cloud storage".
Can you tell me the path? 

There was a thread in 2019 about the same problem, but no solution found.

**Comment by poire-z** [comment]
![image](https://user-images.githubusercontent.com/24273478/183258004-a082f339-1353-4327-83b7-fb3ce9cfc4ce.png)

![image](https://user-images.githubusercontent.com/24273478/183258028-8638b02d-fa5b-4a8b-85ae-428e9313e8d9.png)

![image](https://user-images.githubusercontent.com/24273478/183258050-536aab08-ddec-4a4a-b1b3-de9de8b3dcc4.png)
(You may have more plugins enabled and multiple pages, and it may be on the next page(s).)

![image](https://user-images.githubusercontent.com/24273478/183258073-d6e53832-2cc1-40cd-afb1-44e68589c7da.png)

**Comment by Giorgina83** [comment]
Thank you poire-z! I would never have guessed without your second image.

I found another way to access Dropbox, it creates an item in nickel nickel menu. Seems a little bit faster :

https://www.mobileread.com/forums/showthread.php?t=344661
