### ISSUE TITLE
Device ratings section according to KOReader compatibility

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#9414]
[This](https://github.com/koreader/koreader/issues/9404) discussion made me realize something.
**I chose my e-reader specifically to be able to run KOReader properly.**
KOReader is now more than an application for some e-ink devices.
It is like a custom OS which adds extensive capabilities to the original device.

Now if we had something like a device rating matrix on the GitHub page, it will be very useful for users who want to buy a new e-reader.

**An example scenario (which is not rare I guess):**
- Someone is using KOReader on their Android phone / PC / very old Kindle and they are happy with it
- They decide to get a new e-ink reader which they can run KOReader on
- They decide to get a Kobo Libra, seller has both the **Original** model and **Libra 2**
- They look nearly identical (feature and price bracket) so the user thinks **"Why not get the newer model ?"**

But if they see something like this on our page, they would definitely get the older one:
![feature matrix](https://user-images.githubusercontent.com/84420582/183157690-2cf85e8e-b0d0-45dd-9d8b-85d4e15cabc8.png)

It doesn't have to be very detailed. Even a very simple device classification like this would be a helpful starting point for users I guess (this is from protondb game compatibility classification):

![protondb classification 2](https://user-images.githubusercontent.com/84420582/183158808-483b5c0c-2e3e-478a-b2cb-2698c31895ac.png)

This will be more like the devs' opinion on which devices they recommend (since they are trying to fix the problems on these devices, they are the ones who know the negatives best). I would trust KOReader devs infinitely more than some random guy on reddit when choosing a device for KOReader.

**Comment by Frenzie** [comment]
> I would trust KOReader devs infinitely more than some random guy on reddit when choosing a device for KOReader.

I'm not sure that follows, provided the random guy on reddit has actually used the device with KOreader of course. Although @NiLuJe does seem to have a rather enormous collection.

**Comment by pazos** [comment]
+1 for random reddit guy, ask on forum or DIY.
-1 for an opinionated list from us.

A feature matrix which contains which KO features are available on which platform is nice to have but a bit offtopic here.

**Comment by NiLuJe** [comment]
The specific case of the Libra 2 is also somewhat moot, because, allegedly, the newer ones appear to behave better, yet they have no outward differences, so you can't really tell which is why without using it.

**Comment by offset-torque** [comment]
@Frenzie 
> I'm not sure that follows, provided the random guy on reddit has actually used the device with KOreader of course.

Problem is, I can't verify that user really has that device, it's exactly the same model, he is capable of giving an informed opinion etc. Lying on the internet has no consequences. Anyone can say **"Yep go for it. That device is perfect."** He can even be a bot these days. 

But seeing a table on the official project page means I can trust it.
Any software project that works on different hardware models has this kind of info.
For example if I want to buy a router to use with the latest version of OpenWRT firmware, I can check this table and click on models to see individual problems:
https://openwrt.org/toh/start?dataflt[Supported+Current+Rel*~]=21.02

@NiLuJe 
> The specific case of the Libra 2 is also somewhat moot, because, allegedly, the newer ones appear to behave better, yet they have no outward differences, so you can't really tell which is which without using it.

It is not limited to Libra. I just went to Pocketbook website. There are 10 different models with exactly this specs:

> Display: 6" E Ink® Carta™ 758 × 1024
> Touchscreen: Capacitive (multisensor)
> Processor: 1 GHz

Can we really say **"You can buy any of them. They all work the same with KOReader."** ?
Ok. Let's assume they are all equal, are they also equal to the Kobo models and Kindle models ?

If all the devices that KOReader can be installed is not totally equal (working features and bugs), it means there is an ordering.
If there is an ordering, why not tell this to the users and save them countless hours of searching for **"Is KOReader working on X without problems ?"**

**Comment by mergen3107** [comment]
I like the idea of having a colorful table of compatibility very much! 

From my experience, this is the order of compatibility, from best to worse, so far:
1) Kobo (expect Libra 2 first rev.), it almost replaces the OS controlling even lights and network, very pleasant and seamless to use. 
2) Kindle, on PW2+ it works very good expect for legacy bugs like native Kindle UI seeping through KOReader UI. 
3) Android, generic devices like smartphones work OK (like even on Blackberry Priv with 6.0) 
4) Almost bronze league: Android, Onyx Boox device. Some of the things are irreversibly borked like upside-down orientation. Lights are not optimized neither, because it is easier to control them using Onyx’es own controls. 

Otherwise, as long as the Android device is added to the list supported device on the luajit for Android, eink part works pretty well. Ah, also the OCR doesn’t work too. 

(I am on mobile right now, but later I’ll try to find respective issues and add them here, for reference). 

I am not sure where exactly to place Pocketbook, since I didn’t use it myself (probably between Kindle and Android generic) and I know nothing about AppImage, Cervantes.

**Comment by Frenzie** [comment]
Cervantes is up there with Kobo, but no longer sold.

Android is basically good unless the device itself is borked. (Which is apparently disturbingly common for Android ereaders; not sure why.)

AppImage works about as well as you can expect. I.e., it's extremely likely to Just Work™ and even paltry old devices are swimming in RAM and CPU compared to just about any ereader. But the UI isn't optimized for desktop use. It's still quite decent though.

**Comment by pazos** [comment]
> Any software project that works on different hardware models has this kind of info.
> For example if I want to buy a router to use with the latest version of OpenWRT firmware, I can check this table and click onmodels to see individual problems:

Openwrt or LineageOS are **OS  replacements**. KOReader is an application that works on top of the software stack of the device.

Document how well KO works on top of each software stack for each platform on each software revision is a nightmare. That excluding documenting special snowflakes that behave differently inside the same platform.

**Comment by offset-torque** [comment]
@pazos 

> Document how well KO works on top of each software stack for each platform on each software revision is a nightmare.

That's exactly why I didn't suggest doing that :)

This list can be very simple and basically convey this level of information:
🟢 This device is ok, you will have a pleasant experience
🟡 This device has minor problems but no dealbreaker (like "page turn is a bit longer")
🔴 This device has major problems affecting usability (like "SOC doesn't enter idle mode so you have to charge it every 2 days instead of 2 weeks")
⚫ This device can run KOReader but we don't support it officially and don't fix problems on this device

So now when a person goes to PocketBook website and sees 10 identical models, he can at least come here and remove the 🟡 and 🔴 models from his decision list and decide between the 🟢 ones.

For the black tier for example, I am recently seeing devices sold in Europe which are produced for China only. KOReader can be installed on them since they are Android. But I guess there is little chance that any bug on them might be resolved because none of the devs own that device. Some of the devices doesn't even have an English GUI. So this device may be listed as **"Theoretically you can run KOReader on this, but you are on your own"**. Which would be enough for some users to avoid it totally.

**Comment by roaminghawk** [comment]
I really love this idea. Being in the market for a new device to replace my aging - albeit still working- T62D.

KOReader is not just an ebook reader app. When launched you don't need to exit it do anything on the devices software, you do everything from reading to wikipedia look ups to importing books and exporting notes and bookmarks from within KOReader, so it's more of a custom ROM if you will.

Following the normal purchase method most of us do, you research your device, look at opinions on reddit and respected reviewers. The reviews for the Libra 2 for example are glowing, most reddit users herald it as the best invention after electricity, almost all the reviewers too. 

But if you dig deeper after getting the hint from [NiLuJe](https://github.com/NiLuJe) - which normally you wouldn't without knowing exactly what you're looking for - you will find a lot of reports about random freezes, random reboots, sluggishness and questions if the new software version will solve those problems.

Another aspect that I don't see mentioned very often is the responsiveness of the device. I know that can be subjective but if a device is being notoriously sluggish, that's something one would need to know before purchasing.

I agree making a list like that would be a nightmare. But at least make a short one with the currently being sold devices with problems and shortcomings. Libra 2 for the freezes and Sage for the abysmal battery life.

**Comment by Frenzie** [comment]
My official rating goes something like this:

* Kobo Mark 5 and older: acceptable
* Kobo Mark 6 onwards: all terrible, the Libra for example has nice buttons though
* Non-Kobo: all atrocious

That's for the hardware though. KOReader works great on all. Now there are some devices that are even more atrocious than others, but that's not related to KOReader. It's like saying the Xbox 360 tends to suffer from a red ring of death when you run KOReader on it.

**Comment by NiLuJe** [comment]
> My official rating goes something like this:
> 
>     * Kobo Mark 5 and older: acceptable
> 
>     * Kobo Mark 6 onwards: all terrible, the Libra for example has nice buttons though
> 
>     * Non-Kobo: all atrocious
> 
> 
> That's for the hardware though. KOReader works great on all. Now there are some devices that are even more atrocious than others, but that's not related to KOReader. It's like saying the Xbox 360 tends to suffer from a red ring of death when you run KOReader on it.

Mk. 7 devices worked out pretty damn well (all in all), which leaves a mostly behaving bunch of devices of each size (Clara HD, Libra, Forma). The least broken of which was the Forma, which still suffers from random epdc hangs (more common with image workflows, but can happen on plain text, too).

The Elipsa & Sage work "fine", once you account for autostandby.

All of those get utterly trounced by a Kindle PW5, though (but that comes with its own set of quirks: you need to be able to JB it, and after that, we live on top of the stock OS like a tick (although there are workarounds now), which eats a good chunk of RAM.

**Comment by NiLuJe** [comment]
Back to the matrix issue: my lengthy post above should already have illustrated that a bit, but, even on a relatively "small" lineup (Kobo's), this is *hard* to maintain.

Once you start hitting PB, all hell breaks loose, because there are seven billions of 'em, we've seen behavior changes after FW updates, and we (mostly) don't have PB maintainers.

So, yeah, it's a nice idea, but I'm not entirely sure how feasible and maintainable it is...

**Comment by roaminghawk** [comment]
Thanks for that [NiLuJe](https://github.com/NiLuJe). Really informative. 
I don't like PW5, imho it looks ugly compared to the libra 2/sage form factor.

So for text you choose the Sage, with autostandby, how long does the battery last or how often do you need to charge it?

**Comment by NiLuJe** [comment]
I'm a weird duck that wasn't really bothered by the pre-autostandby power efficiency, because I just plug it when I need it to ;p.

**Comment by NiLuJe** [comment]
Oh, another Sage/Elipsa quirk with autostandby enabled: https://www.mobileread.com/forums/showpost.php?p=4242885&postcount=4 ;o).

**Comment by Frenzie** [comment]
> Mk. 7 devices worked out pretty damn well (all in all), which leaves a mostly behaving bunch of devices of each size (Clara HD, Libra, Forma). 

But they don't have a microSD slot, in combination with no relevant internal storage until the most recent 32 GB models.

**Comment by NiLuJe** [comment]
True, that's one thing that's always flown over my radar ;).

**Comment by offset-torque** [comment]
> **NiLuJe** - So, yeah, it's a nice idea, but I'm not entirely sure how feasible and maintainable it is...

Yes that is my concern too and I definitely don't want to dump extra workload on devs.
I am even thinking about crowdsourcing it via a github thread or maybe a (semi)publicly editable spreadsheet on google docs, like some projects do.

First effort reduction can be limiting this list only to the **new** devices for now.
And maybe include the recent bestsellers that can be still bought **second hand**.
**Reasoning:**
- New devices have less reviews and more problems (naturally), so focusing on them might bring more benefit
- List can still be extended backwards to include older devices later

---

Here I explored and visualized my ideas. It includes new devices currently I can buy from the 3 big players.
I chose colors depending on explanations in this thread as an example.

With this size it doesn't look that scary I guess:

![feature matrix 2](https://user-images.githubusercontent.com/84420582/183278931-d3988943-a22b-4468-901f-0c8ff40c7058.png)

**Comment by lucius-martius** [comment]
I'm currently in the market for a new reader and have recently been burned in this regard.

After reading countless iterations of "get a kobo, it works great", by the aforementioned random reddit guys, while looking for a good device to run KOReader on, I just went ahead an bought the newest device from Kobo in my price range that has buttons, which ended up being the Libra 2.

After a brief period of anger I started to look through github issues looking for the specific issues I had (crashes when setting display warmth and brightness), and found that an issue existed, but was closed and referencing the one large issue (#8414) with a relatively open "it may work one day, but likely not" outlook.

I have since returned the device and continue looking, but I'm very reluctant due to the fear of running into the same problem again. As it stands it is very hard to know what quirks a device is likely going to have unless you already know what issue to search for.

As an alternative to a full blown device list I suggest to at least tag issues with affected devices and keep "duplicate" issues open that may have the same reason as another issue but describe a separate symptom (or at least edit the description of the main issue to reflect that additional symptom). 

That way I could have filtered for issues tagged for the Libra 2, and would have seen that brightness and warmth controls (may) crash the device.

**Comment by melyux** [comment]
Speaking of tracking compatibility, where are these reports that the newer versions of the Libra 2 *might* be better performing? @mergen3107 @NiLuJe

**Comment by NiLuJe** [comment]
It's using a different PMIC, and all the issues seemed to stem from power delivery snafus. (And the few posters with one haven't reported crashes).

**Comment by melyux** [comment]
@NiLuJe I got the newer revision and still got several reboots/crashes while changing the frontlight (and just randomly out of nowhere too). Rip

**Comment by NiLuJe** [comment]
Still terrible. As are the other devices on similar boards (Nia, Clara 2E).

**Comment by 1over137** [comment]
Does that include the Sage?

**Comment by NiLuJe** [comment]
Nope, different SoC.

**Comment by 1over137** [comment]
> > **NiLuJe** - So, yeah, it's a nice idea, but I'm not entirely sure how feasible and maintainable it is...
> 
> Yes that is my concern too and I definitely don't want to dump extra workload on devs. I am even thinking about crowdsourcing it via a github thread or maybe a (semi)publicly editable spreadsheet on google docs, like some projects do.
> 
> First effort reduction can be limiting this list only to the **new** devices for now. And maybe include the recent bestsellers that can be still bought **second hand**. **Reasoning:**
> 
>     * New devices have less reviews and more problems (naturally), so focusing on them might bring more benefit
> 
>     * List can still be extended backwards to include older devices later
> 
> 
> Here I explored and visualized my ideas. It includes new devices currently I can buy from the 3 big players. I chose colors depending on explanations in this thread as an example.
> 
> With this size it doesn't look that scary I guess:
> 
> ![feature matrix 2](https://user-images.githubusercontent.com/84420582/183278931-d3988943-a22b-4468-901f-0c8ff40c7058.png)

What's wrong with Clara HD? I can't find any specific non-fixable issues about it here.

**Comment by Frenzie** [comment]
I think the epdc driver may just freeze under some very rare circumstances. That is, the screen wouldn't update anymore and you'd have to hold down the power button a few seconds to trigger power off, but forced power off shouldn't be necessary because only the screen is frozen. (But I may be thinking of another model.)

But both yellow and red on that list are very alarmist; I'm not sure if it's that bad. :-)

**Comment by offset-torque** [comment]
> But both yellow and red on that list are very alarmist; I'm not sure if it's that bad. :-)

Hey that's a mockup I made in excel, it is not even real :)
I needed all the colors so I chose some models semi-randomly.
(**Green Libra** is the only one I am sure of, because I am using it currently)

On the other hand, users asking for buying advice here on this obscure thread and trying to use mockups for information shows that we really need something like this on the front page.

So devs, please make a suggestion list at least ;)

**Comment by Frenzie** [comment]
If I had to get a new model without a microSD card slot, I'd probably get a Libra 2. It has a decent screen and the buttons are nice, and 32 GB is inmeasurably inferior to my 2014 H2O but at least it's not a paltry 8 GB.

Any model without a microSD card slot and less than 32 GB gets a big red cross from me, and those with less than 128 GB and no microSD card slot get a yellow. Also I can't stand anything with less than about 250 PPI.

You'll note none of that has much of anything to do with KOReader… ;-)

**Comment by offset-torque** [comment]
> You'll note none of that has much of anything to do with KOReader… ;-)

Literally first sentence of this issue:
> I chose my e-reader specifically to be able to run KOReader properly

So I meant this:
"So devs, please make a suggestion list **(for people who is planning to use their device specifically with KOReader)**"

**Comment by pazos** [comment]
**Do Your Own Research** is the wise counsel.

Other than that, the rest are opinions.

If you want to make this ticket actionable we can create a wiki page of devices/platforms and known issues for each one.

But I would never recommend some device as an official statement. Users will need to do their own research, go to that future wiki page and see how that device fits.

I think we all can agree on a few things: 1) it has to be a touch device 2) It should be newer than 2012.

On the rest of stuff we will disagree **a lot**

So it is better to talk about facts and let users to do their own ratings

**Comment by offset-torque** [comment]
So if your aunt says:
"Hey **pazos** sweetie, I need a book reader to use with your nice program (KOReader). Which one should I get ?"
You would tell her: **"Do Your Own Research auntie !"**
I don't think so.

You would tell her which one to get probably.
Same for other devs too. I am sure you (all the devs) will at least say:
**"Hey don't get that one, that causes headaches with KOReader"**

> If you want to make this ticket actionable we can create a wiki page of devices/platforms and known issues for each one.

First I want to clarify this:
**1.** This is not a personal request. I have a perfectly working device which will serve me for long years.
**2.** I know "how to do my own research" so I can choose a new one if something happens to my device.

I opened this issue to help other (especially less technical) users by starting a discussion.
I guess the "wiki page" is the best offer here compared to my simpler "buy/beware/dont buy" list.
But wiki needs to be updated continuously as the issues are reported and fixed.
So it needs much more work as **NiLuJe** explained in a reply above: https://github.com/koreader/koreader/issues/9414#issuecomment-1207226878

So if nothing can be done about this, I guess this issue can be closed or kept open as a future discussion ground until someone comes up with a better plan. Because as long as companies continue making new models, this will be a relevant topic.

**Comment by Frenzie** [comment]
> "Hey pazos sweetie, I need a book reader to use with your nice program (KOReader). Which one should I get ?"
You would tell her: "Do Your Own Research auntie !"
I don't think so.

Maybe not, but the gist of it would still be identical. Do you want buttons auntie, what size screen do you want auntie, okay, that ends you on this model Kobo auntie the end.

**Comment by pazos** [comment]
@offset-torque: not really interested in arguing when n=1. Instead of that I spent a few minutes sketching my approach to the subject: https://github.com/koreader/koreader/wiki/Which-one-should-I-buy%3F

Comments and criticism on that sketch are very welcome!

**Comment by offset-torque** [comment]
@pazos 
Yep, this is exactly what I am talking about.
Only thing I would add is direct links to the brand tags so users can click and see what issues are open currently.
Like this: [Currently open issues for Kobo readers](https://github.com/koreader/koreader/issues?q=is%3Aissue+is%3Aopen+label%3AKobo)
Even just by saying:
- avoid Pocketbooks.
- avoid Android E-ink devices

You will probably decrease shopping list of a user by 20 devices which is a very good starting point.

**Comment by NiLuJe** [comment]
@pazos: That sounds good to me ;).

**Comment by NiLuJe** [comment]
(FWIW, the Clara HD issues are similar in spirit to all the Mk.7/9/10 issues, but are apparently sneaky enough to mainly happen while @ 8bpp UR, which is a setup we *never* use in KOReader (and Plato stopped doing hardware rotation on that device to sidestep said issues).

For all intents and purposes, it's still a decent device. A bit long in the tooth (it's the first "real" Mk. 7), but hardware-tinkerer-friendly because of its internal SD card and lack of waterproofing.

(Which, to emphasize @pazos' point, is something I couldn't give a rat's ass about personally, but is important for some people, especially in our target audience ;)).

**Comment by 1over137** [comment]
What is 8bpp UR? I don't think I understand why rotation is relevant here.

**Comment by NiLuJe** [comment]
Because the EPDC has a fast-path for the native panel orientation at 8bpp.

**Comment by roaminghawk** [comment]
I know this might be out of the scope of an issues section but I need some advice. There is an offer for a Libra 2 for 135 CAD (100 USD). Brand new sealed in white (would have preferred the black but what you gonna do). I have no idea which iteration of the board it is, or which PMIC it uses. If you buy it with the black Friday sale on kobo's website for 199 CAD it would most likely be the new board, but this one might end up be new old stock of the older board. But price seems too good and it would an upgrade over my aging Boyue T62D. Should I get it?

**Comment by melyux** [comment]
> I know this might be out of the scope of an issues section but I need some advice. There is an offer for a Libra 2 for 135 CAD (100 USD). Brand new sealed in white (would have preferred the black but what you gonna do). I have no idea which iteration of the board it is, or which PMIC it uses. If you buy it with the black Friday sale on kobo's website for 199 CAD it would most likely be the new board, but this one might end up be new old stock of the older board. But price seems too good and it would an upgrade over my aging Boyue T62D. Should I get it?

That's a great price. The white one is nicer looking anyway. I think all the current generation Kobo devices have the same problems, so it's not like there's a better choice if you want a new one. If you don't mind charging it every week and the occasional crash.

**Comment by NiLuJe** [comment]
(The Sage & ELipsa are unaffected by the aforementioned weirdness, because they run on a different SoC (with... another set of quirks, but far less annoying and user-facing ones ;)).

**Comment by offset-torque** [comment]
**PROCEDURE:**
1. We take this useful information:

> The Sage & Elipsa are unaffected by the aforementioned weirdness, because they run on a different SoC (with... another set of quirks, but far less annoying and user-facing ones)

2. Put it in the wiki page **pazos** created
3. And add a link on our homepage to that wiki page

So, much more people can see this and use it as a guide for buying decisions.

**Comment by roaminghawk** [comment]
> (The Sage & Elipsa are unaffected by the aforementioned weirdness, because they run on a different SoC (with... another set of quirks, but far less annoying and user-facing ones ;)).

So [NiLuJe](https://github.com/NiLuJe), Should I go for it or ignore it? No pressure :)

**Comment by NiLuJe** [comment]
I wouldn't touch those with a ten-foot pole, but that's just me ;o).

**Comment by roaminghawk** [comment]
So, You wouldn't touch either iterations of the boards with that ten-foot pole, or just the older PMIC, while you may poke the newer PMIC with a shorter stick?

**Comment by NiLuJe** [comment]
Reports seem inconclusive at best on that front, so, I wouldn't get my hopes up ;).

**Comment by NiLuJe** [comment]
Shouldn't be a concern anymore (and I removed the warnings from the Kobo Install wiki pages a few weeks ago already ;)).

**Comment by Frenzie** [comment]
Also somewhat to my surprise I was gifted a Libra H2O for Sinterklaas so I can confirm it seems to be working flawlessly. (I've only read 1 book on it yet but I figure 400 page turns should be enough to detect some patterns.)

**Comment by NiLuJe** [comment]
The first one or the "new" one?

**Comment by Frenzie** [comment]
Oops, I meant a Libra 2 indeed. Which does say waterproof on the box nonetheless…

**Comment by NiLuJe** [comment]
Cool :}

**Comment by 1over137** [comment]
Has something changed with the EPDC troubles? Is there a bug fix or a workaround being implemented?

**Comment by NiLuJe** [comment]
Yes, someone donated a Clara 2E back in August, which led to https://github.com/koreader/koreader-base/pull/1645 ;).

**Comment by offset-torque** [comment]
Good to hear that Libra 2 works properly now. At least I know what to get in case mine dies.
