### ISSUE TITLE
Menu and book images crash

### ISSUE THREAD

**Issue by RHRGR** [koreader/koreader#9420]
* KOReader version: **v2022.07 (Last)**
* Device: **PocketBook 740 PRO/InkPad 3**
* Software 
    * version **U740-2.6.5.2917**
    * Release date **20220726_063753**

#### Issue
A crash occurs in which you need to hold the on / off button for a long time
Pictures are not loaded (pictures in the menu)

#### Steps to reproduce
I open any book
After a while or when opening another book, it crashes

##### `crash.log` 

[crash.log](https://github.com/koreader/koreader/files/9284205/crash.log)

**Comment by mergen3107** [comment]
Please hide the crash.log content under the spoiler (it was there in the bug report template) or remove it

**Comment by RHRGR** [comment]
> Please hide the crash.log content under the spoiler (it was there in the bug report template) or remove it

corrected

**Comment by NiLuJe** [comment]
I'm not seeing any crashes in there (possibly hangs, but hard to tell).

Pleas enable verbose debugging, that might help.

**Comment by RHRGR** [comment]
> I'm not seeing any crashes in there (possibly hangs, but hard to tell).
> 
> Please enable verbose debugging, that might help.

how? where?

**Comment by RHRGR** [comment]
I have enabled detailed debugging.  I try to cause a crash, (what kind of magic?) But for some reason it doesn’t work out for me. 
One of the visual issues is rendering svg images.
![20220810_004751.jpg](https://user-images.githubusercontent.com/63253896/183738284-f896afaa-cb5d-41cb-9c8c-68567a49d5c4.jpg)

**Comment by pazos** [comment]
@RHRGR: please re-do installation steps, following https://github.com/koreader/koreader/wiki/Installation-on-PocketBook-devices. You can safely overwrite any files when prompted.

Then plase **do not remove** any file inside `applications/koreader` and try to reproduce the issue.

**Comment by NiLuJe** [comment]
Hey, at least now I know that my checkerboard fallback works ;p.

**Comment by RHRGR** [comment]
@pazos, thank you very much. I recently updated my native firmware, and apparently the firmware knocked down some koreader settings. And after reinstalling koreader everything is displayed correctly again

**Comment by RHRGR** [comment]
What do the lines mean

```
08/12/22-16:06:50 WARN  Terminal: can not open /dev/ptmx: Permission denied
08/12/22-16:06:50 WARN  Error when loading plugins/terminal.koplugin/main.lua```

**Comment by pazos** [comment]
https://www.mobileread.com/forums/showpost.php?p=4244551&postcount=2
