### ISSUE TITLE
Automatic Cover Image Working on Nova Air C but not Note Air 2

### ISSUE THREAD

**Issue by mallomar** [koreader/koreader#9424]
* KOReader version:2022.07
* Device: Onyx Note Air 2

#### Issue 
My wife and I both have Boox devices. She has a Nova Air C, I have a Note Air 2. Both are running Android 11 with KOReader 2022.07. I set hers up, including KOReader and noticed that KOReader is automatically changing the cover image on her device but not mine. I double checked and all the settings are the same. I made sure both were using the latest stable KOReader. For the life of me I can not figure this out.  

#### Steps to reproduce
Try turning on cover image on Note Air 2

#### Crash Log
Not sure the crash log will help but when I try to copy and paste it says it's too long to submit. I can't figure out how to attach the log file itself.

**Comment by pazos** [comment]
Hi.

The coverimage plugin just writes the cover of each new document you're opening to a given path.
There's some step outside KO where you setup your OS to use that specific image as your screensaver.

And the big **Onyx disclaimer**, probably not applicable here but just in case:  Very **borked platform** with **no consistency across devices**. Do not expect any kind of sane behaviour there. The only way to be sure two onyx devices are going to behave the same is to have the **same model** running the **same fw version**.

**Comment by mallomar** [comment]
Thanks for the response, @pazos I don't have a separate plug-in installed for cover image on either Boox. Or are you saying it's a plug-in that's built in? And yeah, I know it's a mess. I can usually get it to work how I want to but it's a lot of tinkering.

**Comment by pazos** [comment]
It is bundled with the app, like many other plugins.

It has a wiki entry in https://github.com/koreader/koreader/wiki/Coverimage
