### ISSUE TITLE
2022.07 not remembering frontlight "warmth" settings on Pocketbook Era PB700

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#9426]
* KOReader version:2022.07 
* Device:Pocketbook Era PB700

#### Issue

not remembering frontlight warmth  settings

#### Steps to reproduce

Set frontlight level and warmth for book, close book, re-open warmth level will recall at 0

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by Cellaris** [comment]
On my PocketBook Era I have not been able to verify this problem. I have been using it for two weeks and my settings (colour temperature setting or any other setting) are maintained when I start KOReader again.

**Comment by pazos** [comment]
Closing this one.

Maybe there's an underlying bug somewhere but the steps to reproduce in OP aren't enough to actually reproduce it, it seems.

@zmixnyc: feel free to add more info about your issue. Namely the exact way you're using to close the book and reopen it.
