### ISSUE TITLE
FR: How to create virtual keyboard layout?

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9429]
Dear KOReader team, 

I would like to modify some existing virtual keyboard layout and create new one customized for Slovak language. Unfortunately I have not found any tutorial how to do it correctly. Only by observation from existing languages I am getting little idea how can it be done. But I do not quite understand the syntax. There are three "types" of file content.
One is like:
`keys[2][3][1].east`

and the second is like:
```
return {
    min_layer = 1,
    max_layer = 8,
    shiftmode_keys = {["î´µ"] = true, ["1/2"] = true, ["2/2"] = true},
    symbolmode_keys = {["123"] = true, ["ABC"] = true, ["alt"] = true},
    utf8mode_keys = {["đźŚ"] = true},
    umlautmode_keys = {["ĂŽČ™Č›"] = true},
    keys = {
        -- first row
        {  --  1       2       3       4       5       6       7       8
```
and third (keypopup) is like:

```
return {
    com = {
        ",",
        north = ";",
        alt_label = ";",
        northeast = "(",
        northwest = "Âż",
        east = "â€ž",
        west = "?",
    }, 
```

Could you please advice?
Thanks in advance

**Comment by Frenzie** [comment]
> One is like:
keys[2][3][1].east

This can be done if the layout is extremely similar to some other layout like QWERTY. I think the comments in https://github.com/koreader/koreader/blob/55c0fc6190d1be330b4efb9a8447982b6c52daee/frontend/ui/data/keyboardlayouts/fr_keyboard.lua should explain it. This may also be applicable to Slovak (some form of QWERTZ?), in which case you might want to start from https://github.com/koreader/koreader/blob/55c0fc6190d1be330b4efb9a8447982b6c52daee/frontend/ui/data/keyboardlayouts/de_keyboard.lua.

[2] means the *n*th element in a table, so in keys[2][3][1] that's row 2, key 3, element 1 (display value).

> and the second is like:

If the keyboard is too different from QWERTY to be covered by a few small replacements, that's what you'd have to do. E.g., copy QWERTY and adjust.

> and third (keypopup) is like:

I think that one kind of speaks for itself? It's the popup you get while long-pressing. ;-)

**Comment by sonix-github** [comment]
Thanks for clarification. Could you please clarify what table do you mean by this?
> [2] means the _n_th element in a `table`, so in keys[2][3][1] that's row 2, key 3, element 1 (display value).

Thanks

BTW: As you suggest I would like to start from some QWERTY layout, and adjust (re-arrange) popup for most used letters for Slovak language

**Comment by Frenzie** [comment]
Does this help?
```lua
keys = { -- this is keys[1]
 { -- this is keys[1][1]
  { -- this is keys [1][1][1]
  }
 },
 {} -- this is keys[1][2]
}
```

**Comment by sonix-github** [comment]
Thanks Frenzie. Got it :)

**Comment by sonix-github** [comment]
Created new Slovak virtual keyboard #9440
