### ISSUE TITLE
Onyx Boox Lomonosov Rendering: sharp fonts, blinking (images, videos, explanation)

### ISSUE THREAD

**Issue by maxbaldin** [koreader/koreader#9431]
* KOReader version: 2022.07
* Device: Onyx Boox Lomonosov

#### Steps to reproduce

I was wondering whether there is any set of settings or option that allows me to stop choosing between lags and font quality.

Koreader should be pretty optimized for e-ink displays, so I believe that I am doing something wrong.

This is how I see fonts in the app:
![fonts](https://user-images.githubusercontent.com/9378386/184477821-a3ce5382-ffef-4052-862a-3e9d80ec42b6.jpg)

All the optimisations are disabled:
![opt_1](https://user-images.githubusercontent.com/9378386/184477850-af03ac98-2231-4a60-b5a0-ecf8552353d8.jpg)
![opt_2](https://user-images.githubusercontent.com/9378386/184477852-13a13f91-9300-4e43-9e16-c86cb363fb80.jpg)
![opt_3](https://user-images.githubusercontent.com/9378386/184477854-1eb6928b-7039-42b8-bb1f-1ab58943d302.jpg)

As you can see, the rendering mode is switched to the "Rocket" mode. With this Rocket mode, I got a terrible font experience but a great UX experience with dictionaries and page refreshing.
This is what I mean:
https://user-images.githubusercontent.com/9378386/184477918-b4789cb0-1032-4e6e-bb3f-0ba479d711e3.mp4

When I switch to "Regal" mode, the fonts appear to be OK, but the UI becomes extremely laggy with blinks and re-renders:
https://user-images.githubusercontent.com/9378386/184477973-b80b4ebe-94f0-4d71-8add-a1083017c055.mp4

Could anyone please help me to figure out whether there is anything I can do? Or do I need to choose between those two behaviors?

**Comment by mergen3107** [comment]
1) Lomonosov is not yet supported in KOReader. Go to here and follow the instructions to ask for adding your model: https://github.com/koreader/koreader/issues/8482

2) KOReader ignores any eink modes. If it is supported, it will work in Normal mode despite your setting.

**Comment by maxbaldin** [comment]
@mergen3107 thank you very much!
I did it https://github.com/koreader/koreader/issues/8482#issuecomment-1214132533

**Comment by pazos** [comment]
> Koreader should be pretty optimized for e-ink displays, so I believe that I am doing something wrong.

It is as much a we can. But we cannot beat system overhead, which in some android devices is pretty bad. The same happens on pocketbooks.

The only android devices where we have exclusive control over epd updates are Tolinos and [devices using the same driver](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt#L54)

In that case the android overhead is less than 1ms over a tipical linux board where we use a ioctl syscall to request a screen update.

On the rest of android boards YMMV. I don't have direct experience with most of them but I can tell you that Likebooks are kind of okayish (ie: worst than Kindle, Cervantes, Kobo, maybe Remarkable, much much better than pocketbooks)

OTOH some android devices are a mess. A real mess. That includes onyx, at least some of them. And the worst part is: we cannot fix it unless somebody *with one of this borked devices* figures out a way to tell the system to avoid doing screen updates and take care of all of them. That's exactly what happens on Tolinos.

Adding your device to the base of "supported" devices will make it possible to change frontlight/warmth from KO and will provide you a way to refresh the screen each X pages. It won't change any other thing like performance or responsiveness. As @mergen3107 said including the device in the supported list will forbide you to use faster screen modes while you're using KO. But based on your screenshots I guess you won't miss that.

**Comment by maxbaldin** [comment]
@pazos thank you for a detailed explanation!

> The only android devices where we have exclusive control over epd updates are Tolinos and [devices using the same driver](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt#L54)

As I can see, Onyx [has](https://github.com/onyx-intl) examples and SDKs to ease developers' support of their e-ink devices. Or does this support just wait for a PR?

**Comment by pazos** [comment]
> @pazos thank you for a detailed explanation!
> 
> > The only android devices where we have exclusive control over epd updates are Tolinos and [devices using the same driver](https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/EPDFactory.kt#L54)
> 
> > That includes onyx, at least some of them.
> 
> As I can see, Onyx [has](https://github.com/onyx-intl) examples and SDKs to ease developers' [support](https://github.com/onyx-intl/OnyxAndroidDemo/blob/master/app/src/main/java/com/android/onyx/demo/EpdDemoActivity.java) of their e-ink devices. Or does this support just waits to be implemented in a PR?

We support full updates only, using this driver: https://github.com/koreader/android-luajit-launcher/blob/master/app/src/main/java/org/koreader/launcher/device/epd/qualcomm/QualcommEPDController.kt, which calls the same underlying methods.

The sdk is not useful for us directly but makes easier to figure/explore out which framework methods are used for what.

PR are welcome to add a new driver for Onyx qcom devices that handles the screen entirely (if that is even possible, I dunno).
