### ISSUE TITLE
Pocketbook: Gestures don't work

### ISSUE THREAD

**Issue by LucyOne** [koreader/koreader#9444]
* KOReader version: 2022-07-16
* Device: Pocketbook Inkpad 3 

I updated my Pocketbook Inkpad 3 from 2022-06-16 to 2022-07-16 and the gestures stopped working. I wasn't able to open the menu by swiping up or down. Almost everything was interpreted as a tap forward. Only the tap zones in the corners worked as always.
Downgraded to the current stable version 2022-07 and gestures are working again.

[crash.log](https://github.com/koreader/koreader/files/9365427/crash.log)

**Comment by NiLuJe** [comment]
Is the device rooted?

**Comment by NiLuJe** [comment]
Probably not, I was afraid no device would behave like that, but, alas, PB does :/.

**Comment by poire-z** [comment]
Looks like they also do not work on the emulator (since yesterday's commits that I pulled earlier).
