### ISSUE TITLE
Can't get dropbear to work with a pubkey

### ISSUE THREAD

**Issue by Max1Truc** [koreader/koreader#9450]
* KOReader version: v2022.07
* Device: Kobo Clara HD

#### Issue

I tried adding my SSH key from `~/.ssh/id_rsa.pub` to `/mnt/onboard/.adds/koreader/settings/SSH/authorized_keys`.
I also tried with ed25519 keys and 1024/2048/4096 bits RSA keys

#### Steps to reproduce

Enable SSH without password, then:
```bash
ssh-keygen -N "" -b 2048 -f ~/.ssh/id_rsa_kobo_demo
cat ~/.ssh/id_rsa_kobo_demo.pub | ssh -T -x -p 2222 root@KOBOIPADDRESS 'cat > /mnt/onboard/.adds/koreader/settings/SSH/authorized_keys'
```
Disable SSH without password, and enable normal SSH (only pubkey), then:
```
ssh -p 2222 root@KOBOIPADDRESS
```

It asks for a password...

#### Log

I ran the dropbear server manually to get some logs:
```bash
$ ./dropbear -E -R -p2222 -F -P /tmp/dropbear_koreader.pid
[1889] Aug 20 11:56:44 Not backgrounding
[1894] Aug 20 11:56:51 Child connection from 192.168.1.237:33484
[1894] Aug 20 11:56:51 Pubkey auth attempt with unknown algo for 'root' from 192.168.1.237:33484
[1894] Aug 20 11:56:52 Exit before auth (user 'root', 0 fails): Exited normally
```

**Comment by pazos** [comment]
See https://github.com/koreader/koreader/issues/8313#issuecomment-937858130

**Comment by Max1Truc** [comment]
Ok, thanks, I'm thinking about creating a PR updating the dropbear version with similar patches.

What do you think ?

**Comment by NiLuJe** [comment]
Please, god, no.

**Comment by Max1Truc** [comment]
Oh, well, okay.

I'm closing the issue then ^^
