### ISSUE TITLE
Pocketbook Era current book cover saved as cover.bmp, need to be saved as pb_shutdownlogo.bmp

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#9451]
* KOReader version: 2022.07
* Device: Pocketbook Era

#### Issue

In the Pocketbook software it's possible to have the current book cover displayed as the "screensaver" and in KOReader it's possible to save the current book cover as a file that supposedly can be read and used as the screensaver.

In the Pocketbook Era OS, the user cannot navigate to the folder where the KOReader image is stored to select it manually. 

It's stored in a hidden folder named ~System/Logo/offlogo/ cover.bmp

The PB OS stores it's user selected screensaver "off logo" as a file in that same folder named "pb_shutdownlogo.bmp"

It seems that in order for KOReader to adopt this functionality it would need to save it's cover.bmp as a file named "pb_shutdownlogo.bmp"

**Comment by NiLuJe** [comment]
Is that folder actually accessible/readable from within KOReader, though, or is it a root-only situation?

**Comment by zmixnyc** [comment]
I'm not sure that the user can navigate there from the device, on Mac OS I can see it if I allow Hidden / System files to be seen.  The KOeader software is placing the file in the correct folder, but not using the name that the Pocketbook OS expects to see when shutting down.

**Comment by pazos** [comment]
Just add a comment in https://github.com/koreader/koreader/wiki/Coverimage#pocketbook-devices.

Do not remove current instructions. Just add your findings for your particular device.

**Comment by zmixnyc** [comment]
Thank you for the link.  It has [complete instructions](https://github.com/koreader/koreader/wiki/Coverimage#pocketbook-devices) for using the existing "cover.bmp" file, unfortunately the instructions refer to menu options that do not exist in Koreader 2022.07

The PDF instructions for KOReader also refer to menus that do not exist in the PB version:

TOP BAR > > Screen > Screensaver

However.. I did discover a pathway in 2022.07:

Screen->Cover Image->Set Image path->cover.bmp


It worked once in "standby" mode, but defaulted to the PB OS assigned image "pb_shutdownlogo.bmp" when powered down.


In order for KOReader to correctly display the current cover image reliably it would need to save it's cover.bmp as a file named "pb_shutdownlogo.bmp"

**Comment by pazos** [comment]
Hi @zmixnyc: you've edited the footer, not the article. I've made changes based on your feedback. Please check them out: https://github.com/koreader/koreader/wiki/Coverimage

**Comment by zmixnyc** [comment]
Thanks Martin, I hope I didn't make it more of a mess..!

**Comment by rjd22** [comment]
I feel this issue is solved. If there still some work to be done for this issue?

**Comment by zmixnyc** [comment]
Seems to be working fine in 2022.10

**Comment by panbroggi** [comment]
Hi! I am commenting this issue for interested users, as something has probably changed in the Pocketbook Era OS. As pointed out in [this forum discussion](https://www.mobileread.com/forums/showthread.php?t=355272) the cover should be saved as ``/mnt/ext1/system/resources/Line/taskmgr_lock_background.bmp``.
In this case, when the user locks the screen, the cover of the current book is displayed (which I think is the intended result).

I tested this with KOReader 2025.10 and Pocketbook OS U700.6.8.4183

**Comment by Frenzie** [comment]
It already has a note like that at the bottom (albeit with a slightly different filename): https://github.com/koreader/koreader/wiki/Coverimage#pocketbook-devices

**Comment by panbroggi** [comment]
I have read the guide, but what is mentioned there is in a different location, as it can be used to set the image when the device is powered off completely. In my case, ``/mnt/ext1/system/logo/offlogo/cover.bmp`` (the default) does not work, and I wanted the book cover to be my screen saver. Therefore, I had to set  ``/mnt/ext1/system/resources/Line/taskmgr_lock_background.bmp`` (a path and name that is not shown in the guide nor in this thread).

**Comment by Frenzie** [comment]
I've added that path to the wiki.

**Comment by panbroggi** [comment]
Thanks a lot!
