### ISSUE TITLE
Warm light option reverts back to white light every few minutes 

### ISSUE THREAD

**Issue by ucanzeee** [koreader/koreader#9453]
* KOReader version:2022.07
* Device: Kobo Aura One 7.8 inch

#### Steps to reproduce
Just starting and trying to read a book in koreader 2022.07 version. I increase it's warm light by sliding to the right side, it's light is getting warmer. But, after a minute, it reverts back to white light again. And also, sometimes when I open books, if it was warm light, it reverts back to white light again.

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by zwim** [comment]
This is the expected behavior, if you have AutoWarmth enabled.

So either disable AutoWarmth and swipe every day or set your preferd parameters in AutWarmth.

Before I developed AutoWarmth I have tried which warmth values I like at day, civil dusk, ... and then I have set thise values in AutoWarthm.

**Comment by ucanzeee** [comment]
Oh okay I forgot this was on. Also the other problem about very spesific with kobo aura one is also solved. I used to set full red light sometimes, when I open a book, it went back to full white back again. This is also solved.
