### ISSUE TITLE
Dialog title bar improvement

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#9454]
Firstly I am not saying this is a necessary change.
I don't even know if it is possible with the current dialogs (probably not :).
I made this mockup for myself, liked it and just sharing the idea here.

**Change:**
Titlebar color is inverted and text is centered

**Why:**
- This makes dialogs look more similar to desktop operating systems
- Dialogs pop out from the background better with a dark titlebar
- Also dark color catches the eye to provide an anchor point for scanning the rest of the dialog

It is not very important, but I think it can be a (small) improvement.

---
### LEFT CURRENT - RIGHT PROPOSED

![dialog_titlebar](https://user-images.githubusercontent.com/84420582/185899498-2c22afc1-f0ba-4d7a-b546-b751b03c1c81.png)

**Comment by pazos** [comment]
Dark titlebar means ghosting. Specially on old devices and 99% of android devices where we have no control over partial updates.

**Comment by poire-z** [comment]
> This makes dialogs look more similar to desktop operating systems

Yep, remind of Windows 3.11 :)

> but I think it can be a (small) improvement.

On some devices like my GloHD, any solid black large area wil get the below text clearer when removed, and I would have to manually issue a full refresh. So, it's at least not an improvement on some devices.

**Comment by Frenzie** [comment]
> Dialogs pop out from the background better with a dark titlebar

As a counterpoint, the titlebar isn't really important enough to emphasize that strongly.

Anyway, while I do like how the proposal on the right looks, the main reason we won't do anything like that is simply technical. Lines and letters are fine, big areas of shades of gray or black either ghost or need a lot of flashing.

Otherwise some light gray could also look decent for example:

<img src=https://user-images.githubusercontent.com/202757/185906708-8253be00-52b5-499a-a9f9-709347252629.png width=40%>

**Comment by offset-torque** [comment]
> Dark titlebar means ghosting. Specially on old devices and 99% of android devices where we have no control over partial updates.

> On some devices like my GloHD, any solid black large area wil get the below text clearer when removed, and I would have to manually issue a full refresh.

> Lines and letters are fine, big areas of shades of gray or black either ghost or need a lot of flashing.

Thanks for these explanations. Very valid reasons that I didn't foresee. 
I am closing the issue. At least it will serve as a reference if a similar question/proposal comes up :)

**Comment by NiLuJe** [comment]
On most devices that aren't Wario & up mxcfb Kindles, gray areas will be even *worse*, as they might force a semi-flash on both display & dismiss, which is uglier on display than black, and has the same (or worse) ghosting consequences on dismiss ;).

(There's a good reason most sane eInk UIs are pure B&W ;)).
