### ISSUE TITLE
StarDict files converted from PyGlossary not working in KOreader 

### ISSUE THREAD

**Issue by fxsmthn** [koreader/koreader#9455]
* KOReader version: 2022.07
* Device: Kobo Libra 2, Motorola Moto G8

#### Issue

Greetings,
I noticed that when converting latest FreeDict files (2022.04.06) to StarDict using PyGlossary 4.5.0 (Python 3.10 64-bit on Windows 10), they wont work in KOreader (it typically says "No results"). I noticed that if the lookup is initiated on a word the non-working dictionaries don't have, it will open a dictionary that finds said word. Words that are present on these non-working dictionaries seems to result in "no results", even if those words would be available on other dictionaries (which will be shown when the offending files are either disabled or deleted).

GoldenDict-program on Windows can read these converted StarDict-files without any visible problems. This is the only existing issue I found that describes perhaps somewhat similar situation: https://github.com/koreader/koreader/issues/8751
I unfortunately did not understand the solution said user figured out. 😅 Could it be that my problem is also related to segmentation fault?

I've tested the dictionaries with KOReader 2022.07 on an Android phone and Kobo Libra 2. I tried the PyGlossary conversion from both the .slob files as well as the .tei files - both conversions seem to lead to files that will work in GoldenDict, but not in KOreader. The only difference between the conversions appears to be that with slob files comes additional folder called "res" and the ifo has additional entry called "website=".

Attached are my old dictionary files (eng-fin and fin-eng 2020.10.04; confirmed they still work in KOreader, I believe the source was tei) and the new ones that work in GoldenDict, but not in KOreader. 
[freedict-2020.zip](https://github.com/koreader/koreader/files/9402027/freedict-2020.zip)
[freedict2022.zip](https://github.com/koreader/koreader/files/9402178/freedict2022.zip)

Here is the site I downloaded them from:
https://freedict.org/downloads/

#### Steps to reproduce
1) Download dictionary file (slob or tei) from above source, 2) use PyGlossary to convert the file to StarDict (I have only tested this using Python 3.10 on Windows 10) and 3) once you add the files to KOreader's dict-folder, the dictionary lookup ceases to give any results pertaining to said dictionary files, until the dictionaries are either removed or disabled.

**Comment by poire-z** [comment]
Good you found that other issue, #8751 (I didn't need to spend much time investigating :) - your problem has the same cause : 
> Dushistov managed to find the mistake, it was that sdcv only supports ifo files with LF line endings and mine were CRLF

We are not using the latest "sdcv" from Dushistov, but an older version that still has this bug (we had some issues updating it, so we got back to an old version).

Your `fineng-stardict/fin-eng.ifo` and `engfin-stardict/eng-fin.ifo` both have DOS/Windows line endings. Just convert them to Unix line endings, and it should work :)

![image](https://user-images.githubusercontent.com/24273478/186163654-ad125cdb-a770-4572-b353-e5cff589cdba.png)

(In case you don't know how to convert the line endings, here are just your 2 ifos converted: [ifos-unix-lineendings.zip](https://github.com/koreader/koreader/files/9402669/ifos-unix-lineendings.zip))

**Comment by fxsmthn** [comment]
Hey,
thanks for the swift reply and the explanation regarding sdvc. I found out that Notepad++ also has a function for converting the line endings and that also leads to working ifo-files. The solution seems so simple now, but yesterday I was truly at a loss. :D
