### ISSUE TITLE
FR: Add dictionary support for Mobi format

### ISSUE THREAD

**Issue by gw54300** [koreader/koreader#9456]
I want to use an English Chinese dictionary, but there are very few stardic resources on the Internet. I hope to add dictionary support in Mobi format or PRC format

**Comment by NiLuJe** [comment]
Extremely unlikely, as:

* It's Mobi. It's dead, Jim, get over it ;).
* It's extremely badly documented/RE'd, so, it'd be *extremely* non-trivial (even if the current Mobi support in CRe were actually decent, which it isn't).

So, err, best forget about that, and find a way to convert it instead ;).
