### ISSUE TITLE
Kobo Sage: battery drain over night

### ISSUE THREAD

**Issue by paulrouget** [koreader/koreader#9457]
* KOReader version: 2022.07
* Device: Kobo Sage

#### Issue

I put the device to sleep yesterday (probably around 90% battery). Woke up to an empty battery.

[crash.log](https://github.com/koreader/koreader/files/9421966/crash.log)

**Comment by Frenzie** [comment]
Looks like it woke up immediately. Do you have a sleep cover that might be waking it up?

```
08/25/22-00:59:51 INFO  WakeupMgr: scheduling wakeup in 259200
08/25/22-00:59:51 INFO  Inhibiting user input
08/25/22-01:00:06 INFO  Kobo suspend: going to sleep . . .
08/25/22-01:00:06 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
08/25/22-01:00:08 INFO  Kobo suspend: waited for 2s because of reasons...
08/25/22-01:00:08 INFO  Kobo suspend: synced FS
08/25/22-01:00:08 INFO  Kobo suspend: asking for a suspend to RAM . . .
08/25/22-01:01:47 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
08/25/22-01:01:49 INFO  WakeupMgr: scheduling wakeup in 259200
validateWakeupAlarmByProximity:	
task              @ 1661619591 (2022-08-28 00:59:51 +0800)	
last set alarm    @ 1661619591 (2022-08-28 00:59:51 +0800)	
current rtc alarm @ 1661619591 (2022-08-28 00:59:51 +0800)	
current time is     1661360522 (2022-08-25 01:02:02 +0800)
08/25/22-01:02:02 ERROR Kobo suspend: putting device back to sleep after 1 unexpected wakeups.
08/25/22-01:02:02 INFO  Kobo suspend: going to sleep . . .
08/25/22-01:02:02 INFO  Kobo suspend: successfully asked the kernel to put subsystems to sleep
08/25/22-01:02:04 INFO  Kobo suspend: waited for 2s because of reasons...
08/25/22-01:02:04 INFO  Kobo suspend: synced FS
08/25/22-01:02:04 INFO  Kobo suspend: asking for a suspend to RAM . . .
08/25/22-01:02:18 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!
08/25/22-01:02:20 INFO  WakeupMgr: scheduling wakeup in 259200
validateWakeupAlarmByProximity:	
task              @ 1661619591 (2022-08-28 00:59:51 +0800)	
last set alarm    @ 1661619591 (2022-08-28 00:59:51 +0800)	
current rtc alarm @ 1661619591 (2022-08-28 00:59:51 +0800)	
current time is     1661360553 (2022-08-25 01:02:33 +0800)
```

**Comment by paulrouget** [comment]
> Do you have a sleep cover that might be waking it up?

No.

**Comment by paulrouget** [comment]
> Looks like it woke up immediately

There was no indication that it was awake.

**Comment by Frenzie** [comment]
Or equivalent like magnets?

**Comment by paulrouget** [comment]
> Or equivalent like magnets?

I don't think so. The closest electronics was my laptop (~50cm away).

**Comment by Frenzie** [comment]
> There was no indication that it was awake.

I mean almost immediately.

Went to sleep:
08/25/22-01:00:08

Woke up:
08/25/22-01:01:47

And then something went wrong trying to put it back to sleep:
08/25/22-01:02:04 INFO  Kobo suspend: asking for a suspend to RAM . . .
08/25/22-01:02:18 INFO  Kobo suspend: ZzZ ZzZ ZzZ... And woke up!

**Comment by Frenzie** [comment]
Pinging @NiLuJe

**Comment by NiLuJe** [comment]
Can't tell you more than @Frenzie without verbose debug logs, where we would have seen if it was an actual input event from the hall sensor ;).

At least it's definitely not an rtc alarm, as those looked sane.

**Comment by paulrouget** [comment]
How do I enable and/or retrieve verbose debug logs?

**Comment by NiLuJe** [comment]
Can't do that after the fact, unfortunately ;).

The toggles are in: [Tools] > More tools > Developer tools

**Comment by NiLuJe** [comment]
Might be worth cross-referencing with kernel logs, too (run `klogd` once, so that they end up timestamped in the syslog, because kernels are too old for an actual useful printk implementation).

**Comment by paulrouget** [comment]
Ok! I've enabled verbose debug logs. If this happens again, I'll attach the logs here. Thank you.

**Comment by mkozlows** [comment]
I don't have any actionable logs on this, but I will say that I believe the same thing has happened to me -- twice in the last few weeks (after updating to 2022.07?), I've picked up the Sage and it was completely dead. Before seeing this issue, I didn't think too much about it, and assumed that I must have misremembered where the battery was at.

**Comment by NiLuJe** [comment]
As usual in these sort of cases (pun intended ;p), beware of stray magnets, as the most likely cause for this is a spurious trigger of the hall sensor ;).

**Comment by mkozlows** [comment]
It happened to me again last night, while placed by itself on a wooden desk -- woke up completely dead, booting to Nickel. I don't think there were any magnets nearby. I had enabled the verbose logging, and am attaching the crash.log.
[crash.log](https://github.com/koreader/koreader/files/9523561/crash.log)

**Comment by mkozlows** [comment]
That plugging/unplugging may well be real -- my memory for inconsequential events obviously isn't perfect, but I was probably awake that late, and I probably did plug it in to charge up for a bit before then taking the plug and using it for my phone, leaving the Sage off-the-charger for the rest of the night.

But when I unplugged it, the battery would have been reasonably full and it would have been turned off (I definitely would have noticed the screen glowing at that point) -- and even if it weren't turned off, it should have timed out and turned off before too long. Any theory about what could have caused it to drain out from there?

**Comment by NiLuJe** [comment]
The logs are cut-off fairly soon after the unplug, so I wouldn't know (e.g., the unexpected wakeup is detected, which means the device will be put back into suspend, but it's cut-off at that point).

**Comment by NiLuJe** [comment]
Oh, wait, actually, there's something wonky happening there at the end, I'll have to double-check that tomorrow; the final suspend may not have actually been triggered.

**Comment by NiLuJe** [comment]
Caused by `Device:onUsbPlugOut` since https://github.com/koreader/koreader/pull/9263

Now to remember why I thought that was a good idea...

**Comment by mkozlows** [comment]
Whew, I'm glad there's something real and I'm not totally off my rocker here. Just to confirm, I didn't truncate the log at all -- that's the full thing as I downloaded it once I plugged the Sage back in the next day.

**Comment by NiLuJe** [comment]
Yeah, a hard reboot (or, well, an unexpected shutdown in general, like when running out of power ;p) will lead to truncated logs because of the various layers of buffering involved in the tortuous labyrinth that data follows before actually makeing it to disk ;).
