### ISSUE TITLE
Menu not complete

### ISSUE THREAD

**Issue by dikkied2** [koreader/koreader#9458]
* KOReader version: 2022 7
* Device:

#### i am using koreader on kobo ereader H2O as well ass on my samsun S21
On the KOBO device the menu option Cloud Storage is missing. 
On the android device the menu option progress sync is missing

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by mergen3107** [comment]
Cloud storage is available only from the File Manager, not from the opened book.

**Comment by pazos** [comment]
and progress sync from the reader.
