### ISSUE TITLE
Kobo Libra 2 bug physical button

### ISSUE THREAD

**Issue by saisot2006** [koreader/koreader#9460]
* KOReader version: latest
* Device: Kobo Libra 2

#### Issue: koreader still use the default setup: the top button is prev, the bottom is next even I pick the inverted setup in kobo settings: the top is next, the bottom is prev.

**Comment by NiLuJe** [comment]
We don't honor the Nickel settings, but I'm pretty sure we have our own for that. (Somewhere in, err, [Gear], I'd say).
