### ISSUE TITLE
Vocab builder failed to add context in pdf books?

### ISSUE THREAD

**Issue by proItheus** [koreader/koreader#9461]
* KOReader version:2022.07
* Device:android 12 and 10

#### Issue
In some books, the vocab builder plugin don't add context of a word, while it works fine in others
#### Steps to reproduce
Enable context, lookup words normally. The plugin can't add a word's context in pdf books.
![Screenshot_20220826-185450_KOReader](https://user-images.githubusercontent.com/50539150/186893868-2df511bf-5f45-459a-b3f9-10c1db7a2149.png)
The plugin works fine in my epub,mobi books but can't add context in all my pdf books. Tested this on several android devices ,get the same result.
Example books:
- [Flipped](https://upload.disroot.org/r/FzHaogtf#4NafMro6S2XVttBMi8XoSpDMJHgNm/brIIw+xoxCIds=)(epub,works)
- [Fire and Fury](https://upload.disroot.org/r/UExeW_1f#o6mkOhNxKW6o4T70vgtmDqLsGacBoNLRklPKgpzbwc8=)(pdf,doesn't work)

**Comment by Frenzie** [comment]
To what extent that can work on PDF probably depends on the document in question, but @weijiuqiao should know better.

**Comment by poire-z** [comment]
> To what extent that can work on PDF probably depends on the document in question

In https://github.com/koreader/koreader/issues/9180#issuecomment-1149030997 , I wrote:

> in PDFs, you can't grab any context I think, it's all just rectangles, you can't guess continuity

I don't really know if this could be guesses in "some" PDF.
Unless we switch to reflow mode, but even then, it would be hard if the context is multilines...
I would mark this as "can't fix" :)

**Comment by proItheus** [comment]
Then what about grabbing a fixed range, for example 5 words, of text when we can't guess how long the sentence is? I think this will still be very useful for providing context info when reviewing the words. Maybe this can be an opt-in?

**Comment by poire-z** [comment]
> I think, it's all just rectangles, you can't guess continuity

May be it can happen that this word is part of a longer rectangle with other words (that is: a line :) and we could grab that line.
But none of us is really knowledgable about PDF/MuPDF/Kopt to look and implement this :/
