### ISSUE TITLE
FR: Modify Dpad controls on Pocketbook Basic Lux 3

### ISSUE THREAD

**Issue by gervaklaus** [koreader/koreader#9462]
I have a Pocketbook Basic Lux 3, after a day or two of tinkering I figured out the navigation. My issue is that the left button on the dpad acts as a "go back" option.  Basically in the options you can only scroll right and it can be very time consuming.
Also the top bar menu is toggled by long pressing the right dpad menu. Is there any way I can fix this behaviour?
Thank you so much for your hard work!

**Comment by Commodore64user** [comment]
The problem here is a lack of buttons, in short, not much one can do here. For more info see #4029.

**Comment by Frenzie** [comment]
Yeah, never say never but the way it is is the only way it can be halfway usable.
