### ISSUE TITLE
Can't set KOR to stop treating middle taps as page jumps.

### ISSUE THREAD

**Issue by MarjaE2** [koreader/koreader#9466]
* KOReader version: 2022.07
* Device: Boox Max3

#### Issue

Can't set KOR to stop treating middle taps as page jumps.

#### Steps to reproduce

Several other e-ink-friendly apps use middle taps to open the menus. So it's frustrating to have them jump pages here.

1. Open top menu, settings, "taps and gestures," > "page turns," > "tap zones," > left/right, with 25% right.

2. Tap the middle of the screen. It jumps back a page.

Swipes, instead of taps, may be a workaround for some users, but they can worsen tendon injuries.

**Comment by NiLuJe** [comment]
You'll have to make a hole between the four rectangles yourself by playing with the advanced settings, where you'll have access to an extra pair of rectangles for just these kind of setups.

([Tools] > More tools > Advanced settings).
