### ISSUE TITLE
Android: koreader crashes when switched to from another app

### ISSUE THREAD

**Issue by ptrm** [koreader/koreader#9469]
* KOReader version: 2022.08
* Device: Onyx Boox Nova Air C (color eink)

#### Issue
Koreader crashes hen brought back from the background. I tried disabling / enabling battery optimisation, Onyx screen optimisation  custom dpi, no luck.

*The issue does not occur on a pristine install, only with settings in `koreader` syorage folder migrated from anither boox. Can share relevant files on requests, because some anonimisation is required*

#### Steps to reproduce

1. Launch koreader
2. Switch to other app
3. Switch back to koreader, either by system open app picker or launching it
4. koreader crashes

##### `crash.log` (if applicable)

[---------.txt](https://github.com/koreader/koreader/files/9471893/---------.txt)
[---------.2.txt](https://github.com/koreader/koreader/files/9471894/---------.2.txt)

Screen recording: https://user-images.githubusercontent.com/366258/187971919-28e5b2c6-ce99-470b-b416-21af569bb942.mp4

**Comment by pazos** [comment]
hi, @ptrm

Is not an issue if you cannot reproduce without custom settings. Settings are not safe to copy between devices. Specially on android. Specially on the broken company.

Also logs are useless. You need to grab one yourself with `pidcat org.koreader.launcher`.

**Comment by ptrm** [comment]
Um, so what the crash dialog logs are for? And why would I need to enter all the custom settings through the gui on every new device :o ?

**Comment by ptrm** [comment]
Plus I find it strange that you don't find custom settings breaking the app a bug. If a setting can be set by a user and breaks stuff, that's lack of sanitisation at least, isn't it?

**Comment by ptrm** [comment]
Is the crash.log of any use? Though on android, seems to be richer in content, and it's recommended in the issue description to go to help -> report bug on android and follow the instructions, which instruct to attach it: [crash.log](https://github.com/koreader/koreader/files/9472258/crash.log)

**Comment by ptrm** [comment]
@pazos here is the pidcat log: 
[org.koreader.launcher.log](https://github.com/koreader/koreader/files/9472346/org.koreader.launcher.log)

I would be grateful for help in pinpointing the root of the problem, I've got load of custom settings and dictionaries and fonts I would not like to drop and reinput manually.

**Comment by pazos** [comment]
crash dialogs might be useful on most devices.
the last log you attached is also not useful.

I need info about the context of the crash, not what happens after the crash. All attached logs are missing that info

About your ideas about bugs and such: it is what it is. If you screw settings or defaults the app will crash. No checks. Nothing. Just a crash.

Now I need you to understand that settings valid on one device might be invalid in a different one. If you want help identifying your issue please attach the requested log.

You can also do some diffing between stock settings and your custom ones and triage which specific setting causes the issue. If you choose that route please provide feedback so we can tell you if it is fixable or not.

**Comment by pazos** [comment]
`NativeThread  E  Failed to run script: frontend/apps/reader/modules/readerdevicestatus.lua:326: attempt to call field 'checkHighMemoryUsage' (a nil value)`

On mobile ATM. Just found this. You can grep the log you attached to see if you find different crash reasons.

This specific one I'm not sure if it is a settings issue or any other thing

**Comment by hius07** [comment]
High Memory Usage check should not be available on Android
https://github.com/koreader/koreader/blob/f2b9c5bdaf24531bd0c2379c954d6a856836d20c/frontend/apps/reader/modules/readerdevicestatus.lua#L57-L62

**Comment by ptrm** [comment]
Thank you, removing these lines helped:
```
➜  koreader grep -rni  memory settings.reader.lua settings/
settings.reader.lua:94:    ["device_status_memory_alarm"] = true,
settings.reader.lua:95:    ["device_status_memory_interval_minutes"] = 5,
settings.reader.lua:96:    ["device_status_memory_threshold"] = 192,
```

I had done some diffing before, but missed these lines.



Regarding your first reply regarding crash reports, not all users are aware they own a "broken company" device, and most take the guidance of the gui messages and issue report descriptions (the one in the template when creating a bug report) as sufficient to know what info to attach. There was no information about doing usb debugging along the way, and I assume these would saving you issue management work.

**Comment by pazos** [comment]
requesting more info takes a few seconds. Adding all that info to the bug template is pain, usually not needed and won't save time.

**Comment by ptrm** [comment]
Yup, I am more concerned about the way you did it. I found it simply tactless.

Also, the settings get read and affect the behavior of the app, so isn't this a bug? If there are conditions to omit these checks in one part of the code, it means other parts of the code also shouldn't be run on incompatible devices, right?

**Comment by ptrm** [comment]
Plus, requesting more info takes you you a few seconds. The user spends more time reproducing rhe bug over and over instead of getting the necessary information all at once. I'm not sure whose pain you take into consideration.

**Comment by hius07** [comment]
If you randomly change a bit if code and the program crashes - is it a bug? Definitely no.
The same with the settings file - it is not intended to be edited or substituted manually.

**Comment by pazos** [comment]
@ptrm: I'm not interested in fixing your issues.

But you're welcome at:

1. Writing documentation
2. Submitting patches
3. Raising awareness of the bugs you find
4. Contributing in the forum/wiki
5. aaand much more ;)

Sorry if you found my communication "tactless". It was highly effective from my point of view. Me and @hius07 helped you with your issue in less than an hour. I'm assuming your intention is good so I won't play the entitled user card here.

Feel free to document whichever settings changes that make the program crash. Hopefully some day somebody will attempt to make settings portable, at least some of them. We're not there yet.

**Comment by ptrm** [comment]
Sure, and I do appreciate the feedback and pointers I got. Maybe my assumption that a plaintext file called "settings" is portable and editable was wrong.

I still don't understand why a part of the code decides to run based solely the settings, not being guarded by actual device state and feature checks, but I agree I can write the optimisations myself and it's not critical this way.

Apologies if I was unkind

**Comment by poire-z** [comment]
> I still don't understand why a part of the code decides to run based solely the settings, not being guarded by actual device state and feature checks

Because we didn't think about it :)
When you write a new feature, this seems obvious and enough:
`if device:supportsThisThing() then setting("that_setting") = true end`
and when using it
`if setting("that_setting") then do some stuff end`
It's short, clean, obvious.

Then, you came in and show strange things may happen in the wild :) and indeed, it would be better to be more careful and do sanitization, etc...
But still, we have limited brain bandwidth, and caring that much about such rare cases would make the code heavier, unreadable, prone to errors - if we were to duplicate the `if device:supportsThisThing()` whereever we use the settings.
So, I think it's quite ok to not do this and assume we live in a sane world. (And it's more fun to just do new sane stuff in a sane world, that having to fight wild edge cases and add kludge.)

Yes, it's frustrating when that issue happens to you - and it's frustrating for us to get such bug reports (and even more frustrating when it's on Android :) which is already a big mess).
But in the end, all ends well :) The issue is explainable, we got a new insight about some way to get things messy that we can think about when future issues arise, and we know how a user can solve it himself - and _your_ KOReader works again :)

**Comment by Frenzie** [comment]
> I still don't understand why a part of the code decides to run based solely the settings, not being guarded by actual device state and feature checks

Because that's how bugs work. ;-) Whoever wrote it as well as whoever reviewed it overlooked this particular line. But while this particular edge case has a fairly clear resolution, portability is limited regardless. DPI, font size, paths, margins, etc. They may be "portable" but they're not exactly portable.

**Comment by ptrm** [comment]
True. What comes to my mind is I can try implementing a settings exporter / importer which would fish out the device-agnostic settings, like footer layout and exporter settings and styletweaks. Even if you don't find it pullable, it will save me frustrations ;)

**Comment by Frenzie** [comment]
It might make sense to move OPDS, exporter, styletweaks and a few along those lines into a separate file more akin to settings/gestures.lua, settings/profiles.lua, settings/wallabag.lua and the like. I don't necessarily mean quite as separated as that, but in any case OPDS for example simply dates back a very long time.
