### ISSUE TITLE
Cloud storage not working

### ISSUE THREAD

**Issue by uphantom89** [koreader/koreader#9471]
* KOReader version: 2022.08; 2022.07,2022.06
* Device:
- kindle pw4
- Nook glowlight plus 7.8”
#### Issue
I don’t know if anyone encountered same issue with me: before i could connect with both Dropbox and Box (webdav) but After awhile of not using, I could not reconnect to those service, it showed “could bot fetch file folder…”. I did try to downgrade koreader to version 6,7 but still couldn’t connect.
Then I try ftp sever, it could show folder but could not download (download window said that I could not save to xyz folder).

**Comment by Frenzie** [comment]
See https://github.com/koreader/koreader/pull/9131

**Comment by Frenzie** [comment]
Should be fixed by https://github.com/koreader/koreader/pull/9496
