### ISSUE TITLE
News Downloader: Fails to process RSS XML feed from palladiummag.com

### ISSUE THREAD

**Issue by yoyossef** [koreader/koreader#9477]
* KOReader version: 2022.08
* Device: Kobo Forma

#### Issue
I'm trying to use the news downloader plugin, but after I add palladium magazine's RSS feed: https://www.palladiummag.com/feed/index.xml

I get an error when I try to fetch this feed.

This is the error window I get:

"Could not process some feeds.
Unsupported format in: https://palladiummag.com/feed/index.xml (Reason: Failed to download content). Please review your feed configuration file."

#### Steps to reproduce

- Open "News downloader (RSS/Atom)"
- Edit news feeds
- Add new feed
- Set https://palladiummag.com/feed/index.xml as the URL (don't need to change the other settings)
- Close the menu
- Sync news feeds

**Comment by roygbyte** [comment]
IDK if what could be causing this, but I noticed when visiting the url (https://palladiummag.com/feed/index.xml) that it redirects to this: https://www.palladiummag.com//feed/index.xml. Note the double forward slash.

Maybe try https://www.palladiummag.com/feed/index.xml in the plugin and see if that resolve the issue?

**Comment by yoyossef** [comment]
> Maybe try https://www.palladiummag.com/feed/index.xml in the plugin (note the inclusion of www) and see if that resolve the issue?

I just tried it and it didn't work unfortunately, same error as on the report

**Comment by roygbyte** [comment]
According to the [W3C feed validator,](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.palladiummag.com%2Ffeed%2Findex.xml) the feed isn't valid. This could or could not be the reason for it not working with Newsdownloader.

**Comment by NiLuJe** [comment]
The OPDS code has a hack to deal with a similar issue, IIRC.

**Comment by Frenzie** [comment]
This feed contains the full content. It should therefore use `download_full_article=false`.

I'll reverse the default to prevent this kind of useless issue in the future.

**Comment by Frenzie** [comment]
PS Useless is not directed at you OP, you couldn't know. ;-)
