### ISSUE TITLE
FR: [Hope to add input method in Simplified Chinese for Wikipedia search.]

### ISSUE THREAD

**Issue by UMOAQ** [koreader/koreader#9490]
**Does your feature request involve difficulty completing a task? Please describe.**
Although I can't do it, I think this feature is repetitive as there are already many languages in koreader

**Describe the solution you'd like**
Add input method in zh-cn，It would be great if you could change Wikipedia to something else.

**Describe alternatives you've considered**
like software listary，different websites have different url.
**Additional context**
Hope to add input method in Simplified Chinese for Wikipedia search. If possible, I hope to change the encyclopedia used or directly use a different search engine to search. In mainland China, Wikipedia is sometimes unavailable. It would be great if it could be replaced with a search engine and searched, such as the form in the figure below.
<img width="608" alt="屏幕截图 2022-09-06 201614" src="https://user-images.githubusercontent.com/61657224/188632789-2f17e2c7-a9cf-47bc-a8af-78754a638556.png">
Different websites can replace the keyword "query" in it.
My native language is not English, these are from Google Translate, thank you very much for your careful reading.

**Comment by weijiuqiao** [comment]
I can try and add a stroke-based Chinese keyboard (笔画输入法) that covers both simplified and traditional. It won't be smart but should be usable.
