### ISSUE TITLE
Green tint and messed up rendering following update

### ISSUE THREAD

**Issue by Arc-ene** [koreader/koreader#9497]
* KOReader version:
* Device: Onyx Nova Air C

#### Issue
Black and white images messed up rendering after update. Green tint over certain parts of the UI. Screenshots attached
#### Steps to reproduce

Unsure if reproducible, issue occurred after updating from ~~Ladybug~~ to Tumbleweed. Persists even after uninstalling Koreader and reinstalling older versions.

**EDIT:** I restored to factory reset and installed Hawthorne where there is no issue, after updating to Ladybug the issue is there again. have attached the crash log.

Issue does not occur with other e-reader apps.
![Screenshot_20220909-172330](https://user-images.githubusercontent.com/73619706/189299970-597f2f64-aa64-4f74-be0c-6b99e292d0d9.png)
![Screenshot_20220909-174743](https://user-images.githubusercontent.com/73619706/189299989-0dcc57d8-7707-4446-9828-4eea51df57ff.png)
[crash.log](https://github.com/koreader/koreader/files/9539386/crash.log)

**Comment by mergen3107** [comment]
Wake up, Neo…

**Comment by NiLuJe** [comment]
Logs would be useful, they possibly switched to a funky surface format (... or, just plain broke shit, as it's Onyx ;)).

**Comment by Arc-ene** [comment]
> Logs would be useful, they possibly switched to a funky surface format (... or, just plain broke shit, as it's Onyx ;)).

The issue appears when updating to Ladybug from Hawthorne too, so maybe it's the new light driver? - which I did find helpful for the rest. I've got a crash log after resetting to factory default, but I don't think there has been a crash at all.
[crash.log](https://github.com/koreader/koreader/files/9539395/crash.log)

**Comment by NiLuJe** [comment]
Why, yes, it is a shitty "surprise!" surface format, so it's possible it chooses a semi-random window format, exposes it as something funky (say, RGB565), and actually fails to composite that sanely...

**Comment by pazos** [comment]
Most likely a fw issue, hopefully fixed. Let us know
