### ISSUE TITLE
FR: Update metadata "summary"=>"status" when a book is being read

### ISSUE THREAD

**Issue by lightmaster** [koreader/koreader#9500]
**Does your feature request involve difficulty completing a task? Please describe.**
Metadata stored for book progress is incomplete. When you finish reading a book, metadata is added to indicate that a book's "status" is completed", however koreader does not set that same "status" metadata to something like "in-progress" or "currently-reading" when a book is in progress.

**Describe the solution you'd like**
Add the following metadata when a book is opened and has more than 0% progress:
```
["summary"] = {
    ["status"] = "in-progress",
},
```

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.

**Comment by NiLuJe** [comment]
The very fact that the sidecar exists is usually enough of an indicator (and you can discriminate by checking the percentage completed if need be).

So, new question: what would be the use-case, and why does an explicit status sound better/more practical to you?

**Comment by lightmaster** [comment]
I use the Calibre plugin "KOReader Sync" to sync progress from KOReader into Calibre, and then "Goodreads Sync" to sync progress to Goodreads. KOReader Sync grabs all the sidecar metadata and just dumps the selected metadata fields into Calibre columns. When "Summary"=>"Status" is set to complete, that status gets pulled into Calibre and then pushed to Goodreads and those books also get marked as complete on Goodreads.

The 2 options I see are to either get KOReader to add an "in-progress" metadata to the metadata field that is already in use to indicate the completed status of a book, or to get KOReader Sync to add new functions and logic actually modify the metadata it pulls whereas it currently just parses it.

Adding the functionality to KOReader seems like a simpler solution since it already knows how to modify metadata and a more complete solution to me, and could also be utilized by other plugins in the future as well.

**Comment by NiLuJe** [comment]
Fair enough, that sounds sensible ;).
