### ISSUE TITLE
Device almost completly frozen and unusable after installing KOReader

### ISSUE THREAD

**Issue by Onni3000** [koreader/koreader#9512]
Yesterday I installed KOreader to my Kobo ereader and well...  It only allows me to click a one book, once and then it frozes. I can still restart etc, but I cant use the touchscreen and thats also why I am unable to connect it to my PC.

**Comment by Frenzie** [comment]
You can always force shutdown the device by long-pressing the power button, but how did you install it on which device?

**Comment by Onni3000** [comment]
I already tried force shutdown. I installed it to Kobo Clara. I used this> https://www.mobileread.com/forums/showthread.php?t=314220 to install it.

**Comment by NiLuJe** [comment]
Did the quickstart guide actually behave on the first launch?

What kind of book did you try to open? Have you tried with others?

**Comment by Onni3000** [comment]
The Quick Start worked great on the first launch, but now nothing works. I can click on a few books once and I cant even read it, because it will freeze and the only way to be able to click the screen even once again is to force restart the Kobo ereader.

**Comment by NiLuJe** [comment]
I'd be curious to see verbose debug logs, because that sounds weird as hell.

Does stuff break if you just let it sit for a while without doing anything? What about just moving around in the menus?

Which FW version is the device running?

**Comment by Onni3000** [comment]
I am unable to use any menus. I can only click on one book once. I think it has the latest firmware.

**Comment by NiLuJe** [comment]
Were you actually able to navigate the quickstart guide during the first launch?

**Comment by NiLuJe** [comment]
You could check if the 2022.07 release behaved, as I guess it *could* be some sort of input shenanigans I might have broken in the rework...

**Comment by Onni3000** [comment]
Oh. I didn't know that you could navigate in the quickstart.

**Comment by Onni3000** [comment]
How can I install the new version now that I cant connect it to my PC (I am unable to click the connect button on the Kobo)

**Comment by NiLuJe** [comment]
Oh, wait, are you telling me the touchscreen is also gone in the stock software? (a.k.a. Nickel)

Because that would just be hardware failure, simply at an incredibly bad timing ;).

**Comment by Onni3000** [comment]
![IMG_20220913_071902.jpg](https://user-images.githubusercontent.com/69005390/189807795-beea0d18-0d4a-4765-9c01-d639dd930016.jpg)


I can click on one book and (not even touch the menus or anything) then it just frozes to there

**Comment by NiLuJe** [comment]
I still fail to understand what this has to do with the "Connect" button in Nickel's USB popup?

Unless we're talking about two vastly different things?

**Comment by Onni3000** [comment]
It doesn't allow me to click or do anything with the popup, I can only touch one book once.

**Comment by NiLuJe** [comment]
And that still doesn't answer my question.

**Comment by Onni3000** [comment]
Everything I know is that it launches me to KOReader and then I can only click on one book (cant even open it) and then it freezes.

**Comment by Frenzie** [comment]
It sounds like you didn't actually force the device to turn off. The official help suggests 15 seconds just to be sure.
https://help.kobo.com/hc/en-us/articles/360017605134-Fix-common-Kobo-eReader-problems

**Comment by Onni3000** [comment]
I have did that already multiple times and didn't work.

I was trying to connect it to my PC, but it doesn't let me click connect, because it freezes when the connect pop-up comes.

**Comment by NiLuJe** [comment]
Define "didn't work".

Did it actually reboot or not?

**Comment by Onni3000** [comment]
It boots, but doesn't fix the problem.

**Comment by Onni3000** [comment]
I just rebooted it again and it said ![IMG_20220913_213950.jpg](https://user-images.githubusercontent.com/69005390/189983820-3066bb92-e924-4d49-b396-9add7128e08a.jpg)

**Comment by NiLuJe** [comment]
> It reboots, but doesn't fix the problem.

When doing *what* exactly?

**Comment by NiLuJe** [comment]
> I just rebooted it again and it said ![IMG_20220913_213950.jpg](https://user-images.githubusercontent.com/69005390/189983820-3066bb92-e924-4d49-b396-9add7128e08a.jpg)

That's... also not normal on a cold boot.

**Comment by Onni3000** [comment]
> > It reboots, but doesn't fix the problem.
> 
> When doing *what* **exactly**?

When I force reboot the Kobo (using the 15 second method), it reboots, but I still can't read any books, access any menus or click connect on USB popup 


I fear that installing KOReader might have made my device useless, because I really cant do anything with it atm.


I can only click a book once and then it freezes and U can also put it to sleep mode and shutdown and reboot it .


Thats all I really know about this.

**Comment by NiLuJe** [comment]
Okay, so it *is* broken on Nickel after a col boot; in which case we're back to:

> Because that would just be hardware failure, simply at an incredibly bad timing ;).

Like, *really* bad coincidence.

**Comment by Onni3000** [comment]
> Okay, so it *is* broken on Nickel after a cold boot; in which case we're back to:
> 
> > Because that would just be hardware failure, simply at an incredibly bad timing ;).
> 
> Like, *really* bad coincidence.
> 

Well... Oh no. How would I go to fix that or did I just make my device become a brick?

**Comment by NiLuJe** [comment]
I would point you towards the MobileRead forums to request an SD card image and see if it works any better after a full flash, possibly on a new card, but I don't necessarily think it will, as the system boots mostly okay.

It's still something possibly worth trying, unless you can manage to trip a full factory reset somehow (that's going to be a problem, as all the methods require working touch input).

Unfortunately, this is going to be a bit problematic right now, as @davidfor, the keeper of the scrolls (read: the one who handled distributing the images) passed away :/.

----

For the record, I don't think you did anything wrong, it just died. Possibly simply because the install process involves writing a bit more data than it is used to and that just pushed it to the brink, but really, nobody's fault.

**Comment by Onni3000** [comment]
Could it be that installing KOReader is why this happened

**Comment by NiLuJe** [comment]
> For the record, I don't think you did anything wrong, it just died. Possibly simply because the install process involves writing a bit more data than it is used to and that just pushed it over the edge, but really, nobody's fault.

Like I said, that is exceedingly unlikely. At best the simple stress of writing a burst of data just pushed it over the edge, but that's it.

**Comment by NiLuJe** [comment]
I mean, we'd have heard about it if people were killing devices left and right, and that's assuming the possibility made technical sense to begin with (it doesn't) ;).

**Comment by Onni3000** [comment]
> > For the record, I don't think you did anything wrong, it just died. Possibly simply because the install process involves writing a bit more data than it is used to and that just pushed it over the edge, but really, nobody's fault.
> 
> Like I said, that is exceedingly unlikely. At best the simple stress of writing a burst of data just pushed it over the edge, but that's it.

Would you think that installing KOReader breaks the warranty in it?

**Comment by NiLuJe** [comment]
It's purely software and doesn't affect the host OS, so I'd inclined to say no, but IANAL.

**Comment by Onni3000** [comment]
> It's purely software and doesn't affect the host OS, so I'd be inclined to say no, but IANAL. If it's still under warranty, I'd go for it.

Alr thx.

**Comment by Onni3000** [comment]
I fixed it. I was able to do manual factory reset.
