### ISSUE TITLE
Cant intstall any koreader version on PB626

### ISSUE THREAD

**Issue by spawly** [koreader/koreader#9518]
* KOReader version: tried 2022.06 and 2022.08
* Device: Pocketbook 626

#### Issue
Incorrectly installed new koreader version after 2021 version and now cant install any new version

#### Steps to reproduce
1. Download archive from releases
2. REPLACE instead of merge system/ and applications/ folders

My applications and system folders are attached: 
https://drive.google.com/file/d/1ydN6iyfb6Q4FjWysJ7o4cTqw7-MBGdD3/view?usp=sharing

May be somebody can share his PB system and applications folders, so I can restore my original ones <3

**Comment by effeerre75** [comment]
Sorry but mine is PB627. You can restore all the firmware using this:
[
](https://download.pocketbook-int.com/fw/Yitoa/626/user/20190730/sw_20190730_U626_5.20.1157_user.zip)

Just copy SWUPDATE.BIN on the main folder of the your device and the restart it

**Comment by spawly** [comment]
it helped, thx.

algo:
1. download swupdate
2. put in main folder on PB. the root folder
3. turn off PB
4. Holding left and right buttons on PB turn the PB on.
5. Software updating
6. Copy koreader file after software upd inside system and applications
7. Open low toolbar and start koreader application on PB
