### ISSUE TITLE
FR: Add a back-button from the Compatability report

### ISSUE THREAD

**Issue by hasezoey** [koreader/koreader#9520]
**Does your feature request involve difficulty completing a task? Please describe.**
Adding a button to go back to normal koreader

**Describe the solution you'd like**
Add a back-button in the "Compatability Report Screen" like in Android settings, because not all systems may have android buttons (at least by default)

where the back button is either a separate button, or the header itself (like in android settings)

**Describe alternatives you've considered**
Using the android back buttons if available or third-party button app

**Additional context**
For example in Tolino Vision5 there are no android buttons (and cannot be enabled from what i can tell), so it needs third-party app to provide buttons (which i currently use), but it is currently the only screen in koreader that does not seem to have a back-button

PS: also maybe change the header text from `Test` to something like `Compatibility Report`

**Comment by pazos** [comment]
> PS: also maybe change the header text from Test to something like Compatibility Report

That's probably a nit but patches are welcome. Please do check how it looks on a 600x800 emulator before submiting. Maybe the font needs to be reduced to fit into a single line.
