### ISSUE TITLE
FR: Vocabulary builder: reset progress one step back

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9527]
**Does your feature request involve difficulty completing a task? Please describe.**
Sometimes, using the Vocabulary builder, we accidentally click on an option ("Got it" or "Forgot"). It would be convenient to have an option to return to the immediately previous state. Now there is the option "Reset progress", which cancels all progress in learning the word.

**Describe the solution you'd like**
If possible, add a button with the option "reset last selection" or something similar.

Dear @weijiuqiao, what do you think? Could it be possible?
Thanks!

**Comment by weijiuqiao** [comment]
Theoretically not too hard to achieve, let me see what I can do.
