### ISSUE TITLE
 Converted dictionaries do not work

### ISSUE THREAD

**Issue by ww00xx** [koreader/koreader#9535]
- KOReader 2022.08 "Tumbleweed"
- Kindle PW 11th 5.14.1.1

I have tried converting .BGL, .MDX, .DSL dictionaries from various sources with pyglossary-4.5.0 to StarDict (.IFO), but none worked with KOReader. It showed these dictionaries in the list, but word search resulted in "Not available" (something similar to https://github.com/koreader/koreader/issues/9515)

These converted dictionaries load absolutely fine on GoldenDict-1.5.0-RC2-372, so it looks like a KOReader problem.

Any solution?

**Comment by poire-z** [comment]
Check/convert line endings in the .ifo file, see https://github.com/koreader/koreader/issues/9455#issuecomment-1224042510

**Comment by poire-z** [comment]
Or upgrade to koreader nightly/dev (via the top right menu, upgrade channel or something, or manually http://build.koreader.rocks/download/nightly/), looks like we updated sdcv recently.

**Comment by ww00xx** [comment]
Thanks for a quick reply and help. Updated to 202208000030 via Dev channel, but it have not solved the problem. Converted this [.BGL](https://downloads.freemdict.com/%E5%B0%9A%E6%9C%AA%E6%95%B4%E7%90%86/%E5%85%B1%E4%BA%AB2020.5.11/content/4_others/spanish/A_Spanish_English_Dictionary_Granada_University_Spain.BGL) to StarDict (.IFO) again and it still shows "Not available".

**Comment by poire-z** [comment]
What about line endings in the .ifo .? You can share the .ifo here if you don't know how to look at them.

**Comment by ww00xx** [comment]
Here is .ifo file 
[Spanish_English_Dictionary_Granada_University.zip](https://github.com/koreader/koreader/files/9609852/Spanish_English_Dictionary_Granada_University.zip)

Probably I will manage to convert the line endings in Notepad++, but just in case...

**Comment by poire-z** [comment]
It had DOS/Windows line endings. I converted it, try replacing it with this one:
[Spanish_English_Dictionary_Granada_University_line_endings_unix.zip](https://github.com/koreader/koreader/files/9609953/Spanish_English_Dictionary_Granada_University_line_endings_unix.zip)

**Comment by ww00xx** [comment]
It is very easy to convert in Notepad++ via Edit -> EOL Conversion
It works! Thanks!

**Comment by poire-z** [comment]
Pinging @NiLuJe though - I thought the line ending issue has been solved by some commit in upstream sdcv (read that in some of our issue, haven't checked) - and it looks like we are in sync. So, strange that updating to a nightly does not solve it.

**Comment by NiLuJe** [comment]
https://github.com/Dushistov/sdcv/commit/911fc2f561af7501c2345da9c147c936671fc582 should take care of it, AFAICT, yeah.

**Comment by poire-z** [comment]
OK, we probably have to handle \r\n on our side too :)
This helps with such ifos:
```diff
--- a/frontend/apps/reader/modules/readerdictionary.lua
+++ b/frontend/apps/reader/modules/readerdictionary.lua
@@ -134,7 +134,7 @@ function ReaderDictionary:init()
             if f then
                 local content = f:read("*all")
                 f:close()
-                local dictname = content:match("\nbookname=(.-)\n")
+                local dictname = content:match("\nbookname=(.-)\r?\n")
                 local is_html = content:find("sametypesequence=h", 1, true) ~= nil
                 -- sdcv won't use dict that don't have a bookname=
                 if dictname then
```

**Comment by Frenzie** [comment]
There's also %c btw, but since that includes other things like \t probably not.
