### ISSUE TITLE
fails to wakeup after long sleep on kobo aura since switch to nightly in august

### ISSUE THREAD

**Issue by symphorien** [koreader/koreader#9542]
* KOReader version: v2022.08-1-gf2b9c5bd_2022-09-01

* Device: kobo aura

#### Issue

fails to wake up from sleep, a hard reboot is required

#### Steps to reproduce

does not happen if I sleep and wakeup immediately. Presumably only happens after multi-day sleep.
I started to use koreader in june and it worked perfectly until about a month after I switched to nightly (to benefit from #9337) so since, say, september. It's not isolated to a single nightly version, last time it happened I updated the nightly version and it happened again.

##### `crash.log` (if applicable)

[crash2.log](https://github.com/koreader/koreader/files/9615433/crash2.log)

**Comment by NiLuJe** [comment]
Can't tell anything from a non-verbose debug log ([Tools] > More tools > Developer options), but do make sure it's not simply auto-shutdown kicking in?

(Also, update to the latest nightly first, there was a fix for suspend and plug-in events a few days ago).

**Comment by symphorien** [comment]
it was auto shutdown. I didn't know this existed, and the switch from "en veille" to "éteint" is extremely stealthy. Sorry
