### ISSUE TITLE
Support Media Overlays in EPUB3

### ISSUE THREAD

**Issue by Vintic** [koreader/koreader#9548]
EPUB3 with Media Overlays seems a really cool feature for me, especially integrated in KOReader, with word translation and definition support.

With such feature you could for example:
 1. Start read at breakfast, continue listening while driving, and then again read before sleep.
 2. Listen correct pronunciation again, without finding the correct sentence with blind rewind.
 3. ...

Strange but I didn't found an issue for it here, sorry if it is a duplicate.
Some related links:
1. https://github.com/r4victor/syncabook
2. https://www.readbeyond.it/
4. https://www.w3.org/publishing/epub3/epub-mediaoverlays.html

**Comment by NiLuJe** [comment]
Since we don't have audio support, I'm not quite sure what would KOreader's role be in this scenario?

**Comment by Vintic** [comment]
1.  Pause and play audio reading
2. Highlite reading sentence
3. Start reading from sentence that was clicked

**Comment by pazos** [comment]
Hi. It isn't going to happen anytime soon. Most probably never at all.

Multimedia (as in audio/video, **not** images) is way out of the scope of the program.

We live in a modern world and browsers introduced the mindset that a single program should be able to do whatever. I'm afraid it is not our case.

The same happens with Javascript: please use a browser or get an app built for a specific framework (android, desktop/qt, electron...) that uses a browser or has abstracted away the low-level tinkering required to do multimedia, javascript, webassembly or any other non-trivial task.
