### ISSUE TITLE
FR: "Recall User Default" button needed in all user setting menus

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#9555]
2022.8 "Tumbleweed"

When adjusting various settings there are options to "Apply" or "Set as Default"  but it is missing a very important function: "Recall User Default"  

Very frequently I make an adjustment and then decide I would like to return to my saved default value, but it is not an option.

**Comment by mergen3107** [comment]
Meanwhile you can still see what is the default value by long-tapping the setting

**Comment by hius07** [comment]
Agree, that can be useful

![01](https://user-images.githubusercontent.com/62179190/191984398-070e8139-7cdb-4a03-a28e-bacc1cfed9be.png)

**Comment by hius07** [comment]
Well, not so straightforward for Contrast.
https://github.com/koreader/koreader/blob/46cdf8ed780254c4a94a2b783bb6d75c1f76c05c/frontend/ui/data/creoptions.lua#L594-L597
@poire-z, was https://github.com/koreader/koreader/pull/5413#discussion_r327102153 a good decision?
"Contrast" is the only setting with `args_table`, but requires a lot of code in optionsutil.lua and configdialog.lua.

**Comment by hius07** [comment]
Can we get rid of `args_table` and have a usual array with index starting from 1? Will require just `- 1` in
https://github.com/koreader/koreader/blob/b0d8919399f5a7da451f40cf8718e865c5979861/frontend/apps/reader/modules/readerfont.lua#L167
(Maybe will require a one time migration. Or does anybody feel the gamma shifting by one step?)

**Comment by poire-z** [comment]
I'm fine with the shifting by -1.
And this configdialog/creoptions stuff does not need to be super clean - we all have added some stuff as we needed it, it's a big mess. But as long as it's not broken, let's not fix this mess :)
So, you can do dirty, as long as you don't break anything.
And if we can avoid a one-time migration, it's for the best.
