### ISSUE TITLE
2022.8 page turn buttons need to be reversed when orientation is set to "horizontal"

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#9556]
* KOReader version: 2022.8 Tumbleweed
* Device: Pocketbook Era PB700

#### Steps to reproduce

Pocketbook Era page turn buttons are reversed when orientation is set to "horizontal", (which places the page turn buttons at the bottom of the device). Currently the left button advances the page number and the right button decreases it.

**Comment by NiLuJe** [comment]
That's... uh, surprising, as nothing touched the rotation handling in that timeframe?

Was it, perhaps, fine on a previous * FW* version?

**Comment by zmixnyc** [comment]
It's possible.. however I just updated the PB700 FW today and the problem persists in KOReader, so I thought I'd report.

**Comment by NiLuJe** [comment]
In any case, can't tell you much without verbose debug logs...

It might be as simple as the event_map being wrong and the buttons bounds as left-side instead of right-side, or the rotation_map being wrong because InkView now does the translation for us.

That'll take someone with the device to deal with this ;).

**Comment by zmixnyc** [comment]
I changed the title of this thread for clarification.

The problem - more  specifically - is that the page turn buttons DO NOT reverse when orienting the reader horizontally.   If the reader is oriented in vertical mode the upper button on the left hand side is "next page" and the lower button is "previous page"  and when rotating the orientation 90˚ to the left the buttons will need to be reversed so that they follow the direction of the text.   At the moment in the horizontal orientation the "left" page turn button selects the next page and the "right" button selects the previous page.

**Comment by NiLuJe** [comment]
That doesn't change anything about my previous answer ;).

**Comment by NiLuJe** [comment]
Specifically...

> In any case, can't tell you much without verbose debug logs...

!!!

**Comment by zmixnyc** [comment]
Thanks for the reply, what can (a mere end user) I do to help?

**Comment by NiLuJe** [comment]
You can honor the [issue template](https://github.com/koreader/koreader/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and post some logs ;).

**Comment by zmixnyc** [comment]
Thanks for the link..!  

Does this template apply when it's a mis - implemented feature rather than a "crash"?

**Comment by NiLuJe** [comment]
> If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with verbose debug logging enabled before providing the logs to us. To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both Enable debug logging and Enable verbose debug logging.

**Comment by zmixnyc** [comment]
The issue is probably easier to see directly in the code, and it appears to be a regression.

In 2022.07  changing the orientation from Vertical to Horizontal would reverse the page turn buttons, but 2022.08 does not.

**Comment by NiLuJe** [comment]
Are you *actively* trying to get me to close this issue without response by annoying me?

**Comment by zmixnyc** [comment]
I'm sorry.  

I'm really not trying to annoy you, just trying to understand the protocol when there isn't a an actual "bug" or a crash etc.   

Should I have filed this as a Feature request?

**Comment by NiLuJe** [comment]
> If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with verbose debug logging enabled before providing the logs to us. To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both Enable debug logging and Enable verbose debug logging.

I can't make it any clearer than that.

**Comment by zmixnyc** [comment]
Thanks again. Here is the crash log.

[crash.log](https://github.com/koreader/koreader/files/9883196/crash.log)

**Comment by NiLuJe** [comment]
Aaaand PB is a weird little blackbox and I have no idea how it deals with key events, because I'm not seeing any in your logs, so, someone with a PB device will have to continue this investigation ;).

Just in case that wasn't obvious, the point of the log is for there to be a set of presses of all the affected buttons in *all* of the rotation, in an order *you* remember so we can follow along.

**Comment by NiLuJe** [comment]
That would have been perfectly fine were it any device than a PB (apparently?).

**Comment by zmixnyc** [comment]
Ah, bummer..

Question: Are the key events are passed to Koreader from the host or does Koreader access them directly?

**Comment by NiLuJe** [comment]
They're passed to us by InkView, which is why my hunch is that this is FW-specific, and that InkView just started doing the translation behind our backs at one point ;).

**Comment by NiLuJe** [comment]
Okay, if I untangle the InkView mess, I'm only seeing *two* key presses in that log, so I would mind another try, with a very specific amount of presses in a very specific order of orientations, with duplicates.

For those following at home, we log events before mangling, so remember:

```
ffi/inkview_h.lua
735:static const int EVT_KEYDOWN = 25;
736:static const int EVT_KEYPRESS = 25;
737:static const int EVT_KEYUP = 26;
738:static const int EVT_KEYRELEASE = 26;
739:static const int EVT_KEYREPEAT = 28;
```
 and

```
ffi/inkview_h.lua
815:static const int KEY_POWER = 1;
816:static const int KEY_DELETE = 8;
817:static const int KEY_OK = 10;
818:static const int KEY_UP = 17;
819:static const int KEY_DOWN = 18;
820:static const int KEY_LEFT = 19;
821:static const int KEY_RIGHT = 20;
822:static const int KEY_MINUS = 21;
823:static const int KEY_PLUS = 22;
824:static const int KEY_MENU = 23;
825:static const int KEY_PREV = 24;
826:static const int KEY_NEXT = 25;
827:static const int KEY_HOME = 26;
828:static const int KEY_BACK = 27;
829:static const int KEY_PREV2 = 28;
830:static const int KEY_NEXT2 = 29;
831:static const int KEY_MUSIC = 30;
832:static const int KEY_COVEROPEN = 2;
833:static const int KEY_COVERCLOSE = 3;
834:static const int KEY_ZOOMOUT = 6;
835:static const int KEY_ZOOMIN = 7;
836:static const int KEY_SHIFT = 14;
837:static const int KEY_LANGUAGECHANGE = 15;
838:static const int KEY_KEYBOARDCLOSE = 16;
839:static const int KEY_0 = 48;
840:static const int KEY_1 = 49;
841:static const int KEY_2 = 50;
842:static const int KEY_3 = 51;
843:static const int KEY_4 = 52;
844:static const int KEY_5 = 53;
845:static const int KEY_6 = 54;
846:static const int KEY_7 = 55;
847:static const int KEY_8 = 56;
848:static const int KEY_9 = 57;
```

Which gives us (after `rg 'input event => type: 25'`...

```
6411:10/27/22-17:19:30 DEBUG input event => type: 25 (nil), code: 24, value: 0, time: 1666905570.723817
6439:10/27/22-17:19:34 DEBUG input event => type: 25 (nil), code: 25, value: 0, time: 1666905574.096929
```

**Comment by NiLuJe** [comment]
But, assuming you pressed *next* in both cases, yeah, that confirms my hunch that InkView is doing the translation behind our backs.

(That is unexpected).

The issue with that being unexpected... is that this might be device- or firmware- specific, so, I don't really have a good way or handling this sanely in code (besides making it device-specific, and that ways lies madness because there are seven billion different PB models).

**Comment by zmixnyc** [comment]
Ok that is all very interesting and useful. The PB FW has it's own assign-ability for the hardware buttons, and IIRC these did affect the KOReader assignments so I set them all back to their defaults.

Did those presses appear in the crash log or the other log I uploaded?

I'll be happy to clear those out and perform a specific set of presses you specify.

**Comment by NiLuJe** [comment]
We no longer generate the ev.log file, so it's a remnant from older versions ;).

The only two key presses I've seen are the ones I've quoted above ;).
