### ISSUE TITLE
2022.08 Can not work on Kobo Touch n905c

### ISSUE THREAD

**Issue by ZhFuwe-Github** [koreader/koreader#9560]
* KOReader version:2022.08
* Device:Kobo Touch n905c

#### Issue&Steps to reproduce
I used "Semi-Automated Installation Method" to install koreader.
I tried to open koreader in Nickelmenu, it stuck at "Tap the lower right corner" .
I tapped but it did not response.
Then I downed "[oreader-kobo-v2022.07.zip](https://github.com/koreader/koreader/releases/download/v2022.07/koreader-kobo-v2022.07.zip)" and replaced `.add/koreader` ,it worked.
Then I downed "[koreader-kobo-v2022.08.zip](https://github.com/koreader/koreader/releases/download/v2022.08/koreader-kobo-v2022.08.zip)" and replaced again, I met the same problem.

(I think my English is poor, sorry)

**Comment by NiLuJe** [comment]
This is fixed in current nightlies ;).
