### ISSUE TITLE
Taps sometimes register as long taps or double-taps

### ISSUE THREAD

**Issue by beelzebielsk** [koreader/koreader#9564]
* KOReader version: 2022.08
* Device: Onyx Boox Poke 2

#### Issue

Sometimes I get a double-tap even though I only tapped once. Or a page hold despite a short tap. I'm not sure which is more common, it's harder to detect two page flips than a word highlight.
I'm not getting double-taps when I use another reader or other apps, so I believe it's koreader specific.

#### Steps to reproduce

Keep reading, using tap gestures to turn the page. Eventually either a highlight will happen or two pages will flip instead of one. I don't know how to force it to happen.

**Comment by poire-z** [comment]
In Gear, Taps and gestures, Gesture interval, you can get this:

![image](https://user-images.githubusercontent.com/24273478/192336511-16899d94-3393-4080-bc91-4697d25ad958.png)

I have it set to 400ms on my Kobo, which was needed for me. The need for this depends on people (and devices ?) I guess. When I added this option, people didn't care, so they must have not been affected by this like you and me :)
(If you two taps are separated by some long distances, this would not apply - so you can still quickly browse pages by taping quickly alternatively with two fingers :)

**Comment by beelzebielsk** [comment]
Thanks! I'll tinker with this and let you know if these solve my problems. It'll take a while cause they're infrequent and I may have to try different settings.

**Comment by offset-torque** [comment]
@poire-z
I am adding this information to the **Troubleshooting** section of the User Guide.
Also this feature can be useful for people with motor problems like shaking hands.

**Comment by beelzebielsk** [comment]
I'm closing this. Using a tap interval of 50ms seems to work. I haven't had a single double-tap in a few days. Thanks for the speedy assistance!
