### ISSUE TITLE
util:calcFreeMem  returns nil  for non-linux  OS,  loses  the compile compatibility under macOS

### ISSUE THREAD

**Issue by octavianx** [koreader/koreader#9565]
`frontend/util.lua `

[https://github.com/koreader/koreader/blob/master/frontend/util.lua](https://github.com/koreader/koreader/blob/master/frontend/util.lua)
Line 834: 
``` lua
    else
        -- Not on Linux?
        return nil, nil
 ```

caused   current source could not be compiled under macOS.
v2022.08 still good for macOS compiling.

**Comment by NiLuJe** [comment]
That's not new code, and that's not technically compiled code either, so you're probably mixing things up.

An actual error log of whatever you're talking about would be helpful.

**Comment by NiLuJe** [comment]
Okay, yeah, doccache will crash with the switch to nil, and that's new ;o).
