### ISSUE TITLE
Koreader freezes when pressing f2

### ISSUE THREAD

**Issue by Elkellympia** [koreader/koreader#9567]
* KOReader version: 2022-08
* Device: Arch linux laptop, x86_64

#### Issue
Koreader freezes when pressing f2 and cant close it with my wm shortcuts or buttons, im using awesomewm as my wm
tried with kill and doesnt close neither
#### Steps to reproduce
open Koreader
press f2
cry because you need to open the terminal to close it
##### `crash.log` (if applicable)
doesn't seem to create a crash log, its like frozen 

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by poire-z** [comment]
When pressing F2, I get this:
![image](https://user-images.githubusercontent.com/24273478/192766851-4fce3af3-7cbd-46f4-b631-6033f45b3179.png)

So, what if you press F2 again ? :)

That's for us to test suspend/resume on the emulator - may be this should not get into the AppImage, as there's probablly no purpose having this in a real app ?

**Comment by offset-torque** [comment]
**Can confirm. After pressing F2:**


DEBUG key event => code: 1073741883 (Power), value: 1, time: 17089.381574
DEBUG AutoTurn: onInputEvent
DEBUG key event => code: 1073741883 (Power), value: 0, time: 17089.453575
DEBUG AutoTurn: onInputEvent
DEBUG Rename  /home/user/books/Alice in Wonderland.sdr/metadata.epub.lua  to  /home/user/books/Alice in Wonderland.sdr/metadata.epub.lua.old
DEBUG Write to  /home/user/books/Alice in Wonderland.sdr/metadata.epub.lua
DEBUG ReaderFooter: unschedule autoRefreshFooter
DEBUG ReaderCoptListener.headerRefresh unscheduled
DEBUG AutoTurn: onSuspend
DEBUG BackgroundRunnerWidget:onSuspend() @  1664399878
INFO  Inhibiting user input

**Comment by NiLuJe** [comment]
And pressing f2 *again*?

**Comment by offset-torque** [comment]
When it is frozen it continues registering **key events** and **input events** without any response. F2 has no effect:

This is **F2**
```
key event => code: 1073741883 (Power), value: 1
AutoTurn: onInputEvent
key event => code: 1073741883 (Power), value: 0
```

But in that frozen state, it crashed a couple of times. 
I couldn't reproduce intentionally:
```
stack traceback:
./ffi/SDL2_0.lua:300: in function 'waitForEvent'
frontend/device/input.lua:1241: in function 'waitEvent'
frontend/ui/uimanager.lua:1688: in function 'handleInput'
frontend/ui/uimanager.lua:1744: in function 'run'
./reader.lua:300: in main chunk
[C]: at 0x55cb28008b90
```

**Comment by Elkellympia** [comment]
> When pressing F2, I get this: ![image](https://user-images.githubusercontent.com/24273478/192766851-4fce3af3-7cbd-46f4-b631-6033f45b3179.png)
> 
> So, what if you press F2 again ? :)
> 
> That's for us to test suspend/resume on the emulator - may be this should not get into the AppImage, as there's probablly no purpose having this in a real app ?

Nothing really happens, its just frozen
Frozen like if it was a screenshot of koreader
strangely i cant close it with my windows manager and thats rare, never happened, as mentioned before

i didnt mention i used the koreader-bin aur repo to install the app, maybe that has to do with something

im recieving something, posting on next comment

**Comment by Elkellympia** [comment]
> When it is frozen it continues registering **key events** and **input events** without any response. F2 has no effect:
> 
> This is **F2**
> 
> ```
> key event => code: 1073741883 (Power), value: 1
> AutoTurn: onInputEvent
> key event => code: 1073741883 (Power), value: 0
> ```
> 
> But in that frozen state, it crashed a couple of times. I couldn't reproduce intentionally:
> 
> ```
> stack traceback:
> ./ffi/SDL2_0.lua:300: in function 'waitForEvent'
> frontend/device/input.lua:1241: in function 'waitEvent'
> frontend/ui/uimanager.lua:1688: in function 'handleInput'
> frontend/ui/uimanager.lua:1744: in function 'run'
> ./reader.lua:300: in main chunk
> [C]: at 0x55cb28008b90
> ```

thats also true for me at least in debug run, it still registers key events, they dont do anything tho

About the traceback, i have been able to reproduce it only if i run it in normal mode on terminal, thats the only way the traceback happens and the only way it automatically stops

**Comment by Elkellympia** [comment]
> When pressing F2, I get this: ![image](https://user-images.githubusercontent.com/24273478/192766851-4fce3af3-7cbd-46f4-b631-6033f45b3179.png)
> 
> So, what if you press F2 again ? :)
> 
> That's for us to test suspend/resume on the emulator - may be this should not get into the AppImage, as there's probablly no purpose having this in a real app ?

you probably right, the thing is i use a laptop and barely use the mouse, mostly i use keyboard, so i figured out that f1 opens the top menu, but bc is in a akward position i sometimes miss and hit f2 and now have a eternal floating frozen window i dont know how to close and interrupting my reading time. (maybe theres another shortcut, i did not found anything about shortcuts in the manual or the options)

**Comment by NiLuJe** [comment]
> stack traceback:
> ./ffi/SDL2_0.lua:300: in function 'waitForEvent'
> frontend/device/input.lua:1241: in function 'waitEvent'
> frontend/ui/uimanager.lua:1688: in function 'handleInput'
> frontend/ui/uimanager.lua:1744: in function 'run'
> ./reader.lua:300: in main chunk
> [C]: at 0x55cb28008b90

That's probably a ^C (it requires a double one, IIRC), as in the following log.

I'm not sure why the AppImage would behave differently than the emu, but I'll try to take a look...

**Comment by pazos** [comment]
@NiLuJe: https://github.com/koreader/koreader/blob/4d48b6e2fe9da8bd01bbc7cc13445c04669be772/frontend/ui/screensaver.lua#L67-L70

but showing the same message on other sdl platforms is not the right fix, IMHO.

I think the problem comes from https://github.com/koreader/koreader/blob/b7a27a3db3070b141bda7a8ed999ec206d32b2d0/frontend/device/sdl/event_map_sdl2.lua#L51

We probably should skip handling power events on platforms where it does nothing **or** map F2 to power only on the emulator.

**Comment by NiLuJe** [comment]
(Still doesn't explain why it gets handled for suspend but not for resume, seemingly only on the AppImage, though).

**Comment by pazos** [comment]
> (Still doesn't explain why it gets handled for suspend but not for resume, seemingly only on the AppImage, though).

No idea.

A poor man patch would be

```diff
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -553,7 +553,7 @@ function Input:handleKeyBoardEv(ev)
         return
     end
 
-    if keycode == "Power" then
+    if keycode == "Power" and self.device:canSuspend() then
         -- Kobo generates Power keycode only, we need to decide whether it's
         -- power-on or power-off ourselves.
         if ev.value == EVENT_VALUE_KEY_PRESS then
```

Assuming that the logic makes sense.

**Comment by NiLuJe** [comment]
`simulateSuspend` is only overloaded for the `Emulator` object, not the `AppImage` one, so it ends up using the one from `Generic`, which doesn't flip the `cover_mode` toggle, which breaks resume.

```diff
diff --git a/frontend/device/sdl/device.lua b/frontend/device/sdl/device.lua
index d22db10af..ee0fd2450 100644
--- a/frontend/device/sdl/device.lua
+++ b/frontend/device/sdl/device.lua
@@ -344,6 +344,13 @@ function Device:toggleFullscreen()
 end
 
 function Device:setEventHandlers(UIManager)
+    if not self:canSuspend() then
+        -- If we can't suspend, we have no business trying to, as we may not have overloaded `simulateResume`,
+        -- and since the empty Generic protoype doesn't flip `self.screen_saver_mode`, we'd be stuck if we tried...
+        -- Instead, rely on the default Suspend/Resume handlers, which are sane ;).
+        return
+    end
+
     UIManager.event_handlers.Suspend = function()
         self:_beforeSuspend()
         self:simulateSuspend()
```

ought to fix it.

**Comment by NiLuJe** [comment]
Eh, shit, I have conflicting changes in #9569, Il'l just fold it in there...

**Comment by Elkellympia** [comment]
Great job guys! you were really quick, i appreciate the support.
