### ISSUE TITLE
some ePub files shown as folder structure

### ISSUE THREAD

**Issue by editwentyone** [koreader/koreader#9570]
* KOReader version: 202208 and newest nightly
* Device: pw2 kindle 

#### Issue

some ePub files are shown as folder structure and others are running completely fine.

couldn't find a solution and don't know enough how to fix this. any ideas?

**Comment by Frenzie** [comment]
What does shown as folder structure mean?

**Comment by poire-z** [comment]
We won't be able to say anything without looking at such a badly handled epub file.
Probably something missing in the EPUB that makes it being handled as a ZIP file.
An EPUB **is a** ZIP file, with some specific content - `mimetype`, `META-INF/container.xml` containing the path to a file with suffix .opf, that `.opf` file - that makes it being a proper EPUB files ; without them, it is just a ZIP file.

**Comment by editwentyone** [comment]
can I upload such a file to someone?

**Comment by poire-z** [comment]
Upload it here, zipped.
If it's not free, I'll let you know when I get it, and you can edit your comment and remove the link and delete the previous version of this comment.

**Comment by poire-z** [comment]
OK, got the file, you can delete it.

I don't know how you made this file.
But this zip does not contain an EPUB file. It actually contains its folder structure:

```
Archive:  test.epub.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  12-16-2021 09:50   QualityLand helle Edition.epub/
        0  12-16-2021 09:50   QualityLand helle Edition.epub/META-INF/
       20  12-16-2021 09:50   QualityLand helle Edition.epub/mimetype
        0  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/
      265  12-16-2021 09:50   QualityLand helle Edition.epub/META-INF/container.xml
        0  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/Images/
        0  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/Styles/
    19433  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/content.opf
        0  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/Text/
    18212  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/toc.ncx
     2722  12-16-2021 09:50   QualityLand helle Edition.epub/OEBPS/Images/wecker_fmt.jpeg
[...]
```
So, either you unzipped the EPUB - then made a ZIP back from what was extracted, but one level too up.
If I go inside your `QualityLand helle Edition.epub/` and zip back all its content and rename that to .epub, it works for me.
```
Archive:  test-issue9570-epub-as-folder-fixed.epub
  Length      Date    Time    Name
---------  ---------- -----   ----
      265  2021-12-16 10:50   META-INF/container.xml
       20  2021-12-16 10:50   mimetype
    19433  2021-12-16 10:50   OEBPS/content.opf
        0  2022-10-06 09:31   OEBPS/Images/
     2557  2021-12-16 10:50   OEBPS/Images/chart_fmt.jpeg
   382067  2021-12-16 10:50   OEBPS/Images/cover.jpeg
     2639  2021-12-16 10:50   OEBPS/Images/fabrik_fmt.jpeg
[...]
```

**Comment by JasonInOttawa** [comment]
I haven't done this sort of thing with zip. Perhaps @editwentyone could try epubpack or calibre

**Comment by editwentyone** [comment]
thanks guys, I will check the tools, thanks for your time

**Comment by poire-z** [comment]
> wait, so the book is called "QualityLand helle Edition.epub", all I did was to zip it and renamed it to "test.epub.zip" (on macOS)

Or may be it was indeed really just a directory named `QualityLand helle Edition.epub/` - and on MacOS with its filemanager, may be it _looked_ like it is a file (this could happen on Windows when the directory contains some icon file that's supposed to be used as the directory icon - but could make it look like it's not a classic directory and it's probably a file).
You copied that to your Kindle.
And on your Kindle, for KOReader, when you tap on it, you just entered that directory.

> some ePub files are shown as folder structure and others are running completely fine.

So, in your first post, when you wrote "shown as folder structure", do you mean you stayed in the filebrowser ? Or that it opened like a plain text document showing some directory listing as text?
If you stayed in filebrowser, this confirms the above.

**Comment by editwentyone** [comment]
See example 

![IMG_1591](https://user-images.githubusercontent.com/96262473/194814826-dbcbdcb3-8c1e-4de7-9ca9-6790c900c618.jpeg)
![IMG_1592](https://user-images.githubusercontent.com/96262473/194814839-9ba09c2c-0769-4627-bce6-9293c4858af1.jpeg)
![IMG_1593](https://user-images.githubusercontent.com/96262473/194814843-1d686b51-28f7-4bb3-beb1-8331447a9238.jpeg)

**Comment by mergen3107** [comment]
Yes, KOReader see your book as a folder (woth two more folders in it)

**Comment by poire-z** [comment]
> KOReader see your book as a folder

Because it's really not a book, but a folder.
It was an EPUB file, but has been unzipped, and its content is no longer a book. No plan to support this "user error" :)

**Comment by editwentyone** [comment]
macOS also shows the possibility "to look inside" this **special** / bad epubs

on good epubs it doesn't do it and handles them as normal files

<img width="620" alt="image" src="https://user-images.githubusercontent.com/96262473/194822430-9932bfb5-4645-481c-a392-b66e5e8c64c7.png">

**Comment by minhluuquang** [comment]
Got this issue too. Anyone know how to convert that to epub format that koreader can read?

**Comment by Frenzie** [comment]
If it is a folder with valid EPUB content you can simply zip the contents (and rename to .epub). That's a big if of course. ;-)

**Comment by victor-py4** [comment]
I hope it helps after a while, I found this repository that basically converts to a valid .epub file [apple-books-epub-converter](https://github.com/potateros/apple-books-epub-converter).
Keep in mind that if the book has DRM you wont be able to convert it.
