### ISSUE TITLE
Migration to new defaults config lost STARDICT_DATA_DIR

### ISSUE THREAD

**Issue by ilyats** [koreader/koreader#9573]
I had 'STARDICT_DATA_DIR' defined in defaults.persistent.lua to use the same stardict files directory in Koreader and in ColorDict. With migration to the new config system it was moved to defaults.legacy.lua and stopped working. I added it manually to the new 'defaults.system.lua' file and now it works.

**Comment by NiLuJe** [comment]
Oh, I thought about that one, and then forgot to check, good point.

(It defaults to `nil`, which makes it effectively non-existent ;o).
