### ISSUE TITLE
FR: FileManager, a handler to open "non-document" supported files.

### ISSUE THREAD

**Issue by pazos** [koreader/koreader#9575]
It is mostly a question.

Lets say I have a zip file, named `sample.kop`, which represents an abstract *koreader package* and I have some code that's able to work with that file (ie: read the file, perform sanity checks, extract some files from it, show an status message...)

I can invoke the code that checks the file and shows a widget by hooking on the FM menu (like the "execute shell script" is doing). What I really want is to be able to "open" it like any other supported files, just by taping/clicking on it.

AFAICT all supported files are readable by one of the document engines, inherit from a `Document` and register themselves in the DocumentRegistry.

So, my question(s): how to tell the FM that files with some extension can be opened in spite of not being documents? Is that possible ATM?

**Comment by poire-z** [comment]
I don't think there's anything at the moment.
But adding some support for that could be done by adding a call to some new function in here:
https://github.com/koreader/koreader/blob/8fcc712c76dcb65609fd31226fed85d7298ddd02/frontend/apps/reader/readerui.lua#L554-L559

**Comment by pazos** [comment]
As always thanks for the hints, @poire-z

I would never find that myself lurking in ` apps/filemanager`. ;p

I played a bit today and hooking a function there seems to work fine but doesn't solve the problem of making `x` extension a supported file. So I would like to propose a workaround. It sounds nasty and the implementation is even nastier, so I would like feedback before spending more time with this.

1. A new module, called `FileManagerHandler`, that keeps a table of extensions. Each extension is itself a table with some fields (`mimetype`(string), `open`(function) and optional `priority` (number).

2. A new document type, called `FileManagerDocument` that contains a function like

```lua
function FileManagerDocument:register(registry)                                                                    
36     for k, v in pairs(FileManagerHandler.extensions) do                                                         
37         registry:addProvider(k, v)                                                             
38     end                                                                                                         
39 end
```

3. `FileManagerHandler` could start with an empty extensions table and provide a couple of methods to add/delete extensions.

4. Plugins (or core) would use those functions to add/remove handlers for specific extensions. For example:

```lua
FileManagerHandler:addHandler("foo", {
    mimetype = "application/foobar",
    open = function(file)
        UIManager:show(InfoMessage:new {
            text = T(_("Handling foo extension for file %1"), file),
        }
    end,
})
```

With something like that the changes required on current logic are minimal.

```diff
diff --git a/frontend/apps/filemanager/filemanager.lua b/frontend/apps/filemanager/filemanager.lua
index 4bfa78e4..ec4c75d1 100644
--- a/frontend/apps/filemanager/filemanager.lua
+++ b/frontend/apps/filemanager/filemanager.lua
@@ -13,6 +13,7 @@ local FileManagerBookInfo = require("apps/filemanager/filemanagerbookinfo")
 local FileManagerCollection = require("apps/filemanager/filemanagercollection")
 local FileManagerConverter = require("apps/filemanager/filemanagerconverter")
 local FileManagerFileSearcher = require("apps/filemanager/filemanagerfilesearcher")
+local FileManagerHandler = require("apps/filemanager/filemanagerhandler")
 local FileManagerHistory = require("apps/filemanager/filemanagerhistory")
 local FileManagerMenu = require("apps/filemanager/filemanagermenu")
 local FileManagerShortcuts = require("apps/filemanager/filemanagershortcuts")
@@ -54,6 +55,11 @@ local FileManager = InputContainer:extend{
     mkdir_bin =  Device:isAndroid() and "/system/bin/mkdir" or "/bin/mkdir",
 }
 
+function FileManager:handleFile(t)
+    if type(t) ~= "table" then return end
+    FileManagerHandler:open(t.name)
+end
+
 function FileManager:onSetRotationMode(rotation)
     if rotation ~= nil and rotation ~= Screen:getRotationMode() then
         Screen:setRotationMode(rotation)
@@ -797,7 +803,7 @@ function FileManager:tapPlus()
     UIManager:show(self.file_dialog)
 end
 
-function FileManager:reinit(path, focused_file)
+function FileManager:reinit(path, focused_file, opts)
     UIManager:flushSettings()
     self.dimen = Screen:getSize()
     -- backup the root path and path items
@@ -819,6 +825,7 @@ function FileManager:reinit(path, focused_file)
     if self.select_mode then
         self.title_bar:setRightIcon("check")
     end
+    self:handleFile(opts)
 end
 
 function FileManager:getCurrentDir()
@@ -1269,7 +1276,7 @@ function FileManager:getStartWithMenuTable()
 end
 
 --- @note: This is the *only* safe way to instantiate a new FileManager instance!
-function FileManager:showFiles(path, focused_file)
+function FileManager:showFiles(path, focused_file, opts)
     -- Warn about and close any pre-existing FM instances first...
     if FileManager.instance then
         logger.warn("FileManager instance mismatch! Tried to spin up a new instance, while we still have an existing one:", tostring(FileManager.instance))
@@ -1287,6 +1294,7 @@ function FileManager:showFiles(path, focused_file)
         focused_file = focused_file,
     }
     UIManager:show(file_manager)
+    self:handleFile(opts)
 end
 
 function FileManager:openTextViewer(file_path)
diff --git a/frontend/apps/reader/readerui.lua b/frontend/apps/reader/readerui.lua
index 1b21f1dc..87cd5d4f 100644
--- a/frontend/apps/reader/readerui.lua
+++ b/frontend/apps/reader/readerui.lua
@@ -14,6 +14,7 @@ local DocumentRegistry = require("document/documentregistry")
 local Event = require("ui/event")
 local FileManagerBookInfo = require("apps/filemanager/filemanagerbookinfo")
 local FileManagerCollection = require("apps/filemanager/filemanagercollection")
+local FileManagerHandler = require("apps/filemanager/filemanagerhandler")
 local FileManagerHistory = require("apps/filemanager/filemanagerhistory")
 local FileManagerFileSearcher = require("apps/filemanager/filemanagerfilesearcher")
 local FileManagerShortcuts = require("apps/filemanager/filemanagershortcuts")
@@ -505,9 +506,8 @@ function ReaderUI:getLastDirFile(to_file_browser)
     return last_dir, last_file
 end
 
-function ReaderUI:showFileManager(file)
+function ReaderUI:showFileManager(file, opts)
     local FileManager = require("apps/filemanager/filemanager")
-
     local last_dir, last_file
     if file then
         last_dir = util.splitFilePathName(file)
@@ -517,9 +517,9 @@ function ReaderUI:showFileManager(file)
         last_dir, last_file = self:getLastDirFile(true)
     end
     if FileManager.instance then
-        FileManager.instance:reinit(last_dir, last_file)
+        FileManager.instance:reinit(last_dir, last_file, opts)
     else
-        FileManager:showFiles(last_dir, last_file)
+        FileManager:showFiles(last_dir, last_file, opts)
     end
 end
 
@@ -559,9 +559,15 @@ function ReaderUI:showReader(file, provider)
         return
     end
 
+    provider = provider or DocumentRegistry:getProvider(file)
+    if provider.provider == "filemanagerdocument" then
+        local properties = FileManagerHandler:getProperties(file)
+        self:showFileManager(file, properties)
+        return
+    end
+
     -- We can now signal the existing ReaderUI/FileManager instances that it's time to go bye-bye...
     UIManager:broadcastEvent(Event:new("ShowingReader"))
-    provider = provider or DocumentRegistry:getProvider(file)
     if provider.provider then
         self:showReaderCoroutine(file, provider)
     end
```

**Comment by poire-z** [comment]
Why not. I agree it's better left in filemanager* than polluting Reader.
I don't really understand why you would need the stuff in `ReaderUI:showFileManager(file, opts)` and what is this `opts`. I would let it all in FileManager*, checking its own non-document filetypes before calling ReaderUI.

But it's a bit abstract for now :) So we can get more real about it, can you spoil a bit about your great KOP project (`sample.kop`) ? What is it ?! What's a .kop file ?!!
KOreader Package ? Downloadable KOReader Plugins ? KOReader Origami Pistolero ?!

**Comment by NiLuJe** [comment]
Going through a new `Document` subclass is necessary for the `DocumentRegistry`, so that looks sound, that should take care of making the files "supported".

As for actually doing different stuff, what's wrong with the current `DocumentRegistry` provider approach? You don't actually wantto switch views, is that it?

**Comment by pazos** [comment]
> I don't really understand why you would need the stuff in ReaderUI:showFileManager(file, opts) and what is this opts. I would let it all in FileManager*, checking its own non-document filetypes before calling ReaderUI.

I would like to do it that way, but sadly that requires a refactor. There're a bunch of places in the code that call `doShowReader` directly (ie: drag&drop in sdl, commandline args...). That bypasses the FM and go directly to the chunk of code on your 1st comment saying "File is not supported".

I guess we can make a function that works as a middle-man for `doShowReader` that just checks if the file is one that can be opened with the FM before calling that function.

**Comment by pazos** [comment]
> But it's a bit abstract for now :) So we can get more real about it, can you spoil a bit about your great KOP project (sample.kop) ? What is it ?! What's a .kop file ?!!
KOreader Package ? Downloadable KOReader Plugins ? KOReader Origami Pistolero ?!

It isn't anything yet. At least is not ready for demo time.

I like abstractions so I started playing with the idea of a container and a set of rules that makes the content inside of the container manageable, like a poor's man apt/pacman. It should allow to install/remove/update/list files.

The prototype I have uses a **single zip as the container*** and it is focused on plugins, mostly because that's 90% of the cake but also because plugins already have bundled metadata. With a few more fields they're ready to be managed. Other kind of files can also be managed the same way but requires extra steps to keep package metadata separated from actual files.

Also the other thing I'm playing with is golang. It makes possible to build a binary that helps users to build packages and collection of packages. It is very nice because binaries are all standalone.

Both the tool used to build/check packages and the code used to manage those packages  should follow the same set of rules (aka the spec) which is unknown ATM.

Anyhow, all of this is outside of the scope of this FR. I just wanted to be sure I have a way to test changes quickly. A generic FM file handler does the work for me :)

*:  My intent is to make an opaque container by putting some form of compressed data into a given offset within a file. The file would start with a header (some magic numbers, a bit of metadata and the checksum & offset of the compressed data). But a plain zip file with a different extension works for me if it is in the sake of transparency :)

**Comment by pazos** [comment]
> As for actually doing different stuff on open, what's wrong with the current `DocumentRegistry` provider approach? You don't actually want to switch views, is that it?

I'm afraid I'm not qualified enough to know which is the best way of doing Iit. I'm also a `Document`'s noob :).

I think I'll push the changes I have ATM and a plugin that showcases the expected behaviour by executing shell scripts instead of opening them.
