### ISSUE TITLE
Frontlight Enabled / Disabled on-screen notification persisting

### ISSUE THREAD

**Issue by zmixnyc** [koreader/koreader#9578]
* KOReader version: 2022.08
* Device:Pocketbook Era PB700

#### Issue
Frontlight Enabled / Disabled notification persisting on screen. Requires page refresh or touch to dismiss

#### Steps to reproduce

It sometime requires the KOReader app to be used for several days before the problem appears, sometimes it happens immediately.

Enable  frontlight using tap / gesture  note "Frontlight Enabled" occupies screen until manually dismissed.

This issue was also present in KOReader 2022.07

##### `crash.log` (if applicable)
`crash.log` is a file that is automatically created when KOReader crashes. It can
normally be found in the KOReader directory:

* `/mnt/private/koreader` for Cervantes
* `koreader/` directory for Kindle
* `.adds/koreader/` directory for Kobo
* `applications/koreader/` directory for Pocketbook

Android logs are kept in memory. Please go to Help → Bug Report to save these logs to a file.

Please try to include the relevant sections in your issue description.
You can upload the whole `crash.log` file on GitHub by dragging and
dropping it onto this textbox.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
Vaguely rings a bell, related to standby kicking in before the end of the timeout.

I don't remember if there was a dedicated issue about it or if it was just brought up in another...

**Comment by Cellaris** [comment]
It is indeed an old known problem. 

https://github.com/koreader/koreader/issues/7764

In the current state of development for PocketBook the compromise solution I have found is to assign such actions to a long press. This way the notification window always disappears.
