### ISSUE TITLE
Small cover size in koreader

### ISSUE THREAD

**Issue by saisot2006** [koreader/koreader#9587]
Hi, my cover is so small in koreader though it shows full screen in my default kobo libra 2.

**Comment by poire-z** [comment]
In the filemanager ? When zooming in ?
Or when just displayed in the first page of the book? In which case, it depends on the image itself, the HTML and CSS. You may help yourself with Zoom/DPI 96 => 300 in the bottom menu.

**Comment by poire-z** [comment]
Well, if it's only one book, move on: turn the page and read that book :)
Without seeing the book and the HTML/CSS code for that cover page, it's hard to say if KOReader does it according to the specs (and Kobo not, it may have some tricks), or if we don't (which is possible).

**Comment by saisot2006** [comment]
This is the code in my cover page 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
<title></title>
<meta content="urn:uuid:55482855-a0fd-40d5-b298-665ec7117971" name="Adept.expected.resource"/>
</head>
<body style="margin-top: 0px; margin-left: 0px; margin-right: 0px; margin-bottom: 0px; text-align: center; background-color: #FFFFFF;">
<div><img alt="cover" src="images/cover.jpg" style="height: 100%"/></div>
</body>
</html>

**Comment by poire-z** [comment]
OK, the presence of `style="height: 100%"` with height only, is probably the reason.
We can't do height in % - it's a bug, but hard/impossible to solve.
https://github.com/koreader/crengine/blob/b00cecdf30a684179d16c40b991b0a0b9c8eafa5/crengine/src/lvrend.cpp#L2795-L2801

You can always long-press on the image to see it fullscreen.
