### ISSUE TITLE
You can help support the export of My Clippings in Kindle format Txt format? 

### ISSUE THREAD

**Issue by elain** [koreader/koreader#9592]
You can help support the export of My Clippings in Kindle format Txt format? 

If I use the koreader export format (html or text), I cannot import it into the flomo through the kindle2Flomo
https://tit1e.github.io/kindle2Flomo/

**Comment by arpanghosh8453** [comment]
@pazos There is this information on the documentation page though. Is that by mistake? 

![image](https://github.com/koreader/koreader/assets/26424944/0e0a1cc1-6a7a-4aa9-98e3-90db7cc9d4a5)

**Comment by hius07** [comment]
Why asking in the ancient thread?
Open the plugin menu and you will see.

**Comment by mergen3107** [comment]
We should probably fix the documentation as well.

**Comment by Frenzie** [comment]
What would the fix be? To remove that "Kindle clippings"?

**Comment by mergen3107** [comment]
Ah, sorry. I definitely missed the fact that Kindle Clippings is now a target for export :D

**Comment by Frenzie** [comment]
Okay, so if I understand correctly this 2022 issue became outdated in 2023 and the documentation is completely correct.

**Comment by arpanghosh8453** [comment]
> Okay, so if I understand correctly this 2022 issue became outdated in 2023 and the documentation is completely correct.

Yes! You got that!
