### ISSUE TITLE
macOS: Crash on adding new Dropbox Cloud Storage

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#9599]
* KOReader version: 2022-08-61
* Device: macOS

#### Issue

I am trying to add a new Dropbox Cloud Storage instance. After I enter my refresh token/id and secret, and tap on Save, KOReader crashes. The last line in crash.log is

`failed to run lua chunk: frontend/ui/widget/multiinputdialog.lua:207: bad argument #1 to 'ipairs' (table expected, got nil)
`

**Comment by NiLuJe** [comment]
I'd rather like the full stacktrace ;).

**Comment by hius07** [comment]
I think it is because of 
https://github.com/koreader/koreader/blob/a916a5e8a27c378453c23e1f83e7dcb9c31c88ad/frontend/apps/cloudstorage/dropbox.lua#L145
(6 years old code), shows up after https://github.com/koreader/koreader/pull/9586.

**Comment by hius07** [comment]
And in the module doc
https://github.com/koreader/koreader/blob/a916a5e8a27c378453c23e1f83e7dcb9c31c88ad/frontend/ui/widget/multiinputdialog.lua#L49

**Comment by NiLuJe** [comment]
Ouch, that is very broken indeed.

**Comment by NiLuJe** [comment]
The good news is, my trusty sidekick `rg --pcre2 '[[:alnum:]_\-]*Widget[[:alnum:]_\-]*:(?!new|extend)'` and I haven't found any other offenders ;).

(There's `TextBoxWidget:getFontSizeToFitHeight`, `ScrollableContainer:getScrollbarWidth`, `KeyValuePage:getDefaultKeyValuesPerPag`, but they do intend to poke at the default class value ;p).
