### ISSUE TITLE
macOS: Crash open trying to access new Dropbox 

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#9602]
* KOReader version: 2022.08-65
* Device: macOS

#### Issue

KOReader crashes after I set up a new Dropbox cloud storage instance and try to access it.

I think this only happens when the Dropbox credentials are valid. If I put in bogus ones, I get a "can't fetch folder contents" error, as expected.

This does not happen with my old long-lived access token.

The last line in crash.log is the ever-helpful

`zsh: segmentation fault  ./KOReader.app/Contents/MacOS/koreader
`

The stack trace is attached.

[stacktrace.txt](https://github.com/koreader/koreader/files/9728117/stacktrace.txt)

**Comment by JasonInOttawa** [comment]
Sadly I still haven't managed to build on M1. The Rosetta builds started working again a while ago and I've been using those.

**Comment by JasonInOttawa** [comment]
Further information - I set up a new Dropbox instance on Linux and worked out the bugs (wrong scope, etc) and copied the resulting settings/cloudstorage.lua to the Mac. It works fine on 2022.08-65. 

I also used the same refresh token and app ID/secret to set up a new Dropbox instance and that also worked (no crashes).

I'm closing this issue as it was likely "user error".

**Comment by NiLuJe** [comment]
It's quite plausible the sha2 module is confusing the hell out of Rosetta (after all, it's doing some fairly funky stuff via FFI).

**Comment by JasonInOttawa** [comment]
Happy to continue poking if there is anything you'd like me to try :)

**Comment by NiLuJe** [comment]
The old macOS image is being deprecated by GitHub, so, at one point someone will have to figure out how to get this built on macOS 12+... ;).
