### ISSUE TITLE
End of book - mark as read - not updating History

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9616]
* KOReader version: 2022.08-68
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
When I reach the end of a book, I see a popup with action. If I hit `Mark as read` then this new status will not appear in the History - Sort - Finished.

However, if I go to Book Status window (where you can set rating, add comments and status) via gesture, I can see that the book is marked `Finished`. If I now change the status to `Reading` and back to `Finished` in the same window, then it will appear in the History - Sort - Finished.

So it seems like the end-of-book action to mark the book as read updates the status incorrectly. Another possibility is that History Sort waits for some "trigger" to refresh, so the Book status has such a trigger, and the end-of-book action doesn't.

I only found out this was an issue when I opened History - Sort, and to my surprise found that a lot (30+) books were still marked as `Reading` although I remember marking them as read in the end-of-book actions list.

P.S. Besides, the end of book action `Mark as read` should be changed to `Mark as finished`, IMHO. This would make it consistent with the Book status and History Sort.

##### `crash.log
Verbose crashlog of me doing these things attached.
[crashlog_verb_book_status.txt](https://github.com/koreader/koreader/files/9743583/crashlog_verb_book_status.txt)

**Comment by hius07** [comment]
Please try: after first marking as read close the book and chek the history.

**Comment by mergen3107** [comment]
@hius07 
Exiting to FM after end-of-book mark as read works well! History is properly updated
