### ISSUE TITLE
Translate only one word

### ISSUE THREAD

**Issue by MaximeAnsquer** [koreader/koreader#9625]
* KOReader version: 2022.08
* Device: Vivlio inkpad 3

#### Issue

If I select multiple words, a pop-up window appears and proposes the button "Translate".
But if I select only one word, the pop-up window shows the result in my dictionaries, but the "Translate" button is missing.
I would like to be able to translate just one word.
Thank you.

**Comment by poire-z** [comment]
Multiple solutions:
- keep long-pressing that single word for more than 3-4 seconds, and you'll get the popup (and you can continue doing short long-presses for dictionary lookup)
- `Taps and gestures > Long-press on text > `uncheck `[ ] Dictionary on single word selection` - and you'll get that popup with Translate & all the other buttons

**Comment by MaximeAnsquer** [comment]
Thank you very much !
