### ISSUE TITLE
Koreader disconnects Bluetooth keyboard in Kobo Libra 2 (works 100% in Nickel)

### ISSUE THREAD

**Issue by simsalis** [koreader/koreader#9640]
* KOReader version: 2022.08
* Device: Kobo Libra 2 

#### Issue
Bluetooth keyboard works in Nickel to browse/search/type in general.

Koreader disconnects the keyboard, which becomes unusable to type notes. Connecting the keyboard directly via USB won’t work either (but that’s also the case in Nickel.)

Quitting, Koreader will leave the Bluetooth toggle off in Nickel unless a reboot is performed.

**Comment by hius07** [comment]
Similar to https://github.com/koreader/koreader/issues/9059

**Comment by NiLuJe** [comment]
Killing bluetooth is done on purpose so as not to uselessly murder battery, since we currently can't actually do anything with it.

The fact that it murders bluetooth altogether until a reboot is another kettle of fish, #helpwanted.

Closing in favor of #9059 to avoid dupes, (thanks @hius07!).
