### ISSUE TITLE
FR: Bluetooth & audiobook support

### ISSUE THREAD

**Issue by Amolith** [koreader/koreader#9648]
**Does your feature request involve difficulty completing a task? Please describe.**
I recently bought a Kobo Clara 2E, and though it is supported by KOReader (#9552), I don't see any way to work with its Bluetooth capabilities or play audiobooks. Currently, I have to exit KOReader and go back to Nickel, but even then, I can only play the DRMed Kobo Audiobooks I've bought through their store.

**Describe the solution you'd like**
I'd like to be able to connect my Bluetooth headphones and play DRM-free audiobooks from within KOReader.

**Comment by NiLuJe** [comment]
Extremely unlikely to ever happen ;).
