### ISSUE TITLE
Hardcoded strings (and not translatable) in "Zoom set to" info dialog

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9667]
* KOReader version: v2022.08-90-g23c41034_2022-10-16
* Device: PocketBook 626 U626.5.20.1157

#### Issue
Hardcoded "Mode" strings rows, columns and manual (and not translatable) in "Zoom set to" info dialog.

#### Steps to reproduce
1.. open some pdf document
2.. tap screen bottom to show bottom menu
3.. tap "resize" tab
4a. tap option Columns or Rows in "Zoom to" line
5a. tap some number in Columns or Rows line
6a. info message is shown with not translated Mode strings "columns" or "rows"
or
4b. tap option manual (%) in "Zoom to" line
5b. tap some number in "Zoom factor" line
6b. info message is shown with not translated Mode string "manual"

![ZoomToInfomessage_NotTranslatedString_columns_EN](https://user-images.githubusercontent.com/29783895/197337278-30b9c9a6-b5bf-4f6b-9125-5bde74d6889a.png)
![ZoomToInfomessage_NotTranslatedString_columns](https://user-images.githubusercontent.com/29783895/197336621-200154e4-843a-4afe-b333-b9375dd5d568.png)

The same for "rows" and "manual":
![ZoomToInfomessage_NotTranslatedString_rows](https://user-images.githubusercontent.com/29783895/197336623-1ec8b5be-f84b-4166-9cc2-11c055ecd73d.png)
![ZoomToInfomessage_NotTranslatedString_manual](https://user-images.githubusercontent.com/29783895/197336620-99fa2543-dd59-4752-83cc-cb6e4a9db7c2.png)

I tried to find where the strings are, and found it (except "manual") in 'readerzooming.lua'

https://github.com/koreader/koreader/blob/60a16c7e00ac6ac024ef32b702839f95c070d3a2/frontend/apps/reader/modules/readerzooming.lua#L413
https://github.com/koreader/koreader/blob/60a16c7e00ac6ac024ef32b702839f95c070d3a2/frontend/apps/reader/modules/readerzooming.lua#L415

**Comment by hius07** [comment]
We have these strings translated already
https://github.com/koreader/koreader/blob/e3fd61251811666b4eac99405118b4d147d01548/frontend/ui/data/koptoptions.lua#L275
but they need to be added to the readrezooming module.
