### ISSUE TITLE
Libra2 Frontlight toggle doesn't turn off light with some values.

### ISSUE THREAD

**Issue by mcdenko** [koreader/koreader#9674]
* KOReader version: v2022.10
* Device: Kobo Libra 2 

#### Issue
When Frontlight value is set to 6,7,12, 14,23,24,28... (I didn't check out every value) and when I tap left bottom corner (Frontlight Toggle), the light is not turning off completely. Even if brightness value is set to 0. The same is when I use Menu/Settings/Frontlight and tap Toggle button. Any other values I use 1..5, 8..11, etc.. Work as It should. 

One thing else. If I close my Kobo cover book (with dimmed frontlight), and then (after few seconds) I open it again frontlight is turned off complettely as it should!

Sorry for my english. I just want to help improving this great reading application. 

#### Steps to reproduce
1 Set frontlight brightness to 5 or 6 or 12... on Kobo Libra 2
2 Tap left down corner 
3 Frontlight is dimmed but not turned off complettely

Here is a part i have found on crash.log

error in subprocess:	./ffi/kobolight.lua:28: Wrong brightness value given!
stack traceback:
	[C]: in function 'assert'
	./ffi/kobolight.lua:28: in function 'setBrightness'
	frontend/device/sysfs_light.lua:78: in function 'setNaturalBrightness'
	frontend/device/sysfs_light.lua:41: in function 'setBrightness'
	frontend/device/kobo/powerd.lua:248: in function 'setIntensityHW'
	frontend/device/kobo/powerd.lua:306: in function 'func'
	./ffi/util.lua:348: in function <./ffi/util.lua:319>
	[C]: in function 'xpcall'
	./ffi/util.lua:319: in function 'runInSubProcess'
	frontend/device/kobo/powerd.lua:304: in function 'turnOffFrontlightHW'
	frontend/device/generic/powerd.lua:109: in function 'toggleFrontlight'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:788: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1313: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1407: in function 'handleInput'
	frontend/ui/uimanager.lua:1456: in function 'run'
	./reader.lua:302: in main chunk
	[C]: at 0x000140bd
error in subprocess:	./ffi/kobolight.lua:28: Wrong brightness value given!
stack traceback:
	[C]: in function 'assert'
	./ffi/kobolight.lua:28: in function 'setBrightness'
	frontend/device/sysfs_light.lua:78: in function 'setNaturalBrightness'
	frontend/device/sysfs_light.lua:41: in function 'setBrightness'
	frontend/device/kobo/powerd.lua:248: in function 'setIntensityHW'
	frontend/device/kobo/powerd.lua:306: in function 'func'
	./ffi/util.lua:348: in function <./ffi/util.lua:319>
	[C]: in function 'xpcall'
	./ffi/util.lua:319: in function 'runInSubProcess'
	frontend/device/kobo/powerd.lua:304: in function 'turnOffFrontlightHW'
	frontend/device/generic/powerd.lua:109: in function 'toggleFrontlight'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:788: in function 'sendEvent'
	frontend/ui/uimanager.lua:52: in function '__default__'
	frontend/ui/uimanager.lua:1313: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1407: in function 'handleInput'
	frontend/ui/uimanager.lua:1456: in function 'run'
	./reader.lua:302: in main chunk
	[C]: at 0x000140bd

regards

**Comment by Frenzie** [comment]
@zwim Is #9675 a fix for this?

**Comment by zwim** [comment]
No #9675 is only related to the AutoDim plugin.

@mcdenko Just to rule out that AutoDim has anything to do with your issue. Please disable it (gear-screen-autodim) and see if the issue consists.

**Comment by mcdenko** [comment]
I have AutoDim plugin disabled.

**Comment by NiLuJe** [comment]
Oh, hey, just encountered this myself while looking into some other stuff, lol.

c.f., https://github.com/koreader/koreader/pull/9609#issuecomment-1288187080

**Comment by mcdenko** [comment]
> Oh, hey, just encountered this myself while looking into some other stuff, lol.
> 
> c.f., [#9609 (comment)](https://github.com/koreader/koreader/pull/9609#issuecomment-1288187080)

:)))
Great! So it's almost done! :))Thank You for your reply! :)
