### ISSUE TITLE
Building on macOS 12.x or 13 on Rosetta results in a crashy libcrengine

### ISSUE THREAD

**Issue by JasonInOttawa** [koreader/koreader#9689]
* KOReader version: 2022.10
* Device: macOS 12.X/13

Just wanted to keep track of building on macOS 12.x/13

Building on ARM results in a working emulator and an application which crashes on startup, per #8797

I did a build on my M1 Mac running macOS 13 using Rosetta, after installing brew and setting up the environment as needed. The resulting application starts but crashes in libcrengine.dylib with a bus error.

Copying libcrengine from a working action here on github, built on 10.15, eliminates the crash, and everything seems to work.

Not sure what to try now :)

**Comment by NiLuJe** [comment]
What's the crash log like on `master` for an ARM build?

**Comment by NiLuJe** [comment]
The code changed since that ;).

**Comment by JasonInOttawa** [comment]
Ah, ok :) I'll try building on M1 and running again

**Comment by JasonInOttawa** [comment]
It does look like it's getting past the "Initializing..." print but it just silently crashes. Nothing in Console or the crash.log
[crash.log](https://github.com/koreader/koreader/files/9873775/crash.log)

**Comment by NiLuJe** [comment]
Awesome -_-".

**Comment by JasonInOttawa** [comment]
I've attached two libcrengine.dylibs in a zip file. 

One is from a Github Action, and putting it in the application I built using Rosetta makes the application work. The other is the one generated by the build, and it doesn't work (crashes on book open).

I'd appreciate any pointers on how to look at them to determine why the crashy one crashes.

[libcrengine.zip](https://github.com/koreader/koreader/files/9879106/libcrengine.zip)

**Comment by NiLuJe** [comment]
Debug builds and gdb stack traces of the crashes would be helpful ;).

**Comment by JasonInOttawa** [comment]
Heh. Just did a Rosetta build, MACOSX_DEPLOYMENT_TARGET=12.00, and it works! I opened a book and no crash. I did notice a recent cre bump - maybe that helped. The version is 2022.10-53.

I ran the following command

`./kodev release macos -d
`

Does that produce a debug build?

**Comment by NiLuJe** [comment]
I don't remember if kodev is smart enough to reorder args, in which case: yes, ti's a debug build.

Otherwise, no, ti's a release build (-d ought to come first).

Just check the name of the staging folder, it should tell you that ;).

Regardless, good news. Might just be time to say fuck it and wcitht he CI to macOS12 + MACOSX_DEPLOYMENT_TARGET=12.00...

(Speaking of, had you tried any other values for MACOSX_DEPLOYMENT_TARGET?)

**Comment by JasonInOttawa** [comment]
Getting weirder -- I can confirm that the build I did before was a debug build:

`koreader-macos-x86_64-apple-darwin22.1.0-debug
`

So I did another build without -d

`koreader-macos-x86_64-apple-darwin22.1.0
`

And this one crashes when I open a book! :)

I haven't tried any other MACOSX_DEPLOYMENT_TARGET values. I was going to try 13 but given the above I don't know whether it's worth it. As far as changing to 12 goes, I'd say to do it, since the artifact isn't being built anyway, and there aren't any promises anywhere that it'll work, and one day it may start working all on its own :)

**Comment by JasonInOttawa** [comment]
@NiLuJe I've built on an Intel Mac without making any changes to the downloaded source and a debug build works. A non-debug build crashes in libcrengine on book open. 

Perhaps for now setting the macOS artifact build to debug and MACOSX_DEPLOYMENT_TARGET=12 is a good idea? It may be more useful than a build that just fails near the end.

**Comment by NiLuJe** [comment]
I don't have the hardware to test any of this, but, sure, why not?

**Comment by JasonInOttawa** [comment]
I think I've set up the 12.00/debug build in #9856.

**Comment by CHOCO-LEO** [comment]
Hi just wondering where I can find the guidance on building on macOS.
Is it able to sync between other devices?

**Comment by Frenzie** [comment]
The instructions are [here](https://github.com/koreader/koreader/blob/master/doc/Building.md) but if you click on actions at the top you can find prebuilt mac artifacts:
https://github.com/koreader/koreader/actions/runs/4584196480

**Comment by JasonInOttawa** [comment]
I didn't realize artifacts were working again! That's great! 

I downloaded a recent one and opened a book and it didn't crash. Are the artifacts resulting from debug builds?

I've been building with this script:

```
#!/bin/bash

if [[ ` arch ` != "i386" ]]; then
        echo Rerun in x86_64 shell
        exit 1
fi

if [[ ! -f /usr/local/bin/brew ]]; then
        echo Install brew for x86_64
        exit 2
fi

#brew install nasm ragel binutils coreutils libtool autoconf automake cmake makedepend sdl2 lua@5.1 luarocks gettext pkg-config wget gnu-getopt grep bison

export MACOSX_DEPLOYMENT_TARGET=12.00

export PATH=/usr/local/bin:${PATH}

export PATH="$(brew --prefix)/opt/gettext/bin:$(brew --prefix)/opt/gnu-getopt/bin:$(brew --prefix)/opt/bison/bin:$(brew --prefix)/opt/grep/libexec/gnubin:${PATH}"

cd
rm -fr ~/koreader
git clone https://github.com/koreader/koreader.git
cd koreader && ./kodev fetch-thirdparty && ./kodev release macos -d
```


 For it to work on my M1 Macbook, I have to run a shell as follows:

`arch -x86_64 bash
`
and ensure that the i386 version of Brew is installed.

**Comment by Frenzie** [comment]
It shouldn't be debug:
https://github.com/koreader/koreader/blob/d39cc78f9c5013b79f8c2c9e114164e34b1d2361/.github/workflows/build.yml#L40

M1 should probably also work if you update base to the latest (not bumped here in front yet). https://github.com/koreader/koreader-base/pull/1570

**Comment by ryanwwest** [comment]
I was able to build on my M1 Mac (not sure if it built to M1 or Intel, I didn't change any defaults from the build instructions) but it seems the touch interface might be messed up on 2023.04 and later version. E.g., I use the mouse cursor to tap somewhere and it seems to register a click as if my mouse was a few hundred pixels higher up. 

The reason I wonder if it's a recent bug is because mouse clicking works as expected using the prebuilt artiface from within 2023-03 here: https://github.com/koreader/koreader/actions/runs/4584196480. But then this prebuilt artifact produced earlier today has the same cursor issue above: https://github.com/koreader/koreader/actions/runs/4843953756.
