### ISSUE TITLE
FR: Support Samba Protocol for Network Storage

### ISSUE THREAD

**Issue by LazyGeniusMan** [koreader/koreader#9692]
**Does your feature request involve difficulty completing a task? Please describe.**
Kind of? as far I understand, currently KOReader only support OPDS/Calibre, FTP, SFTP, and WebDav protocol which all of them require 3rd party software to setup. Samba could make setup process easier since it's usually come OOTB on most Desktop/Server OS and integrated into file manager so user just need to right click the folder and click share.

**Describe the solution you'd like**
Implement Samba Protocol

**Describe alternatives you've considered**
I've tried OPDS, WebDav, etc but IMHO setup a samba share is much more simpler and easier than other alternative.

**Additional context**
Would be nice if it's also support reading without downloading the whole file (directly read from samba share), not sure if it's possible for epub, pdf, etc but app that I used for playing video and reading cbz file over samba support this feature.

Thank you.

**Comment by NiLuJe** [comment]
Samba is a nightmare to deal with as a client. (Also, we'd require libsamba, which is also not fun and not particularly small, IIRC).

Extremely unlikely.

**Comment by pazos** [comment]
Do we really need help on that? I mean, do we really consider a samba client a good feature request **within** the program?

The FM can happily browse cifs mountpoints, as well as any other fancy fuse based filesystems, like sshfs. It is up to the user to:

1. Figure if the kernel has CIFS support bundled in.
2. Mount their filesystems wherever it wants.
3. Jump to the mountpoints using the FM. (or assign a nice folder shorcut)

If 1 is fine, 2 and 3 can be easily done with a shell script/user patch/user plugin. There's no need to reinvent the wheel.

**Comment by LazyGeniusMan** [comment]
> The FM can happily browse cifs mountpoints, as well as any other fancy fuse based filesystems, like sshfs. It is up to the user to:
> 
>     1. Figure if the kernel has CIFS support bundled in.
> 
>     2. Mount their filesystems wherever it wants.
> 
>     3. Jump to the mountpoints using the FM. (or assign a nice folder shorcut)

cmiiw, Android device need root to mount that right ?

btw I've tried using File Manager (Samsung My Files and MiXplorer), I can browse the samba share just fine but I can't open it with KOReader unless if I copy the file into internal storage first.

Is it impossible to directly open epub files? VLC for video and CDisplayEx for cbz file can do this (unless it's downloading the file first in the background, but it's unlikely since a few GBs of files can be opened quickly)

**Comment by Frenzie** [comment]
> Android device

Don't need anything built into KOReader. Only embedded devices do. ^_^

**Comment by pazos** [comment]
> btw I've tried using File Manager (Samsung My Files and MiXplorer), I can browse the samba share just fine but I can't open it with KOReader unless if I copy the file into internal storage first.

Somehow expected. KO needs files placed somewhere on the filesystem and be able to read them. It doesnt matter if a given folder is indeed a mountpoint from a remote host.

> Is it impossible to directly open epub files? VLC for video and CDisplayEx for cbz file can do this (unless it's downloading the file first in the background, but it's unlikely since a few GBs of files can be opened quickly)

File streaming is not supported. None of the other ways of accesing remote content lets you bypass that limitation. All of them rely on the entire file placed in a folder somewhere in the filesystem
