### ISSUE TITLE
Brightness gets set to 100% when going into sleep mode

### ISSUE THREAD

**Issue by SKBotNL** [koreader/koreader#9698]
* KOReader version: v2022.10
* Device: Kobo_snow

#### Issue
For 15-20 seconds the brightness gets set to 100% while going into sleep mode

#### Steps to reproduce
Press power button to make the device go into sleep mode
***
I want to note that this didn't happen before `v2022.10`, after upgrading to `v2022.10` I got this issue

**Comment by zwim** [comment]
Similar question here. Do you have any `Autoxxx` plugins enabled? If yes, disable them and tell us which is causing the issue. If not tell us, that the `Autoxxx` plugins are not the cause of your issue.

**Comment by poire-z** [comment]
Aren't these frontlight and brightness values issues the effect of the floating point number problem?
Which should be fixed in current nightlies?

**Comment by SKBotNL** [comment]
> Similar question here. Do you have any `Autoxxx` plugins enabled? If yes, disable them and tell us which is causing the issue. If not tell us, that the `Autoxxx` plugins are not the cause of your issue.

The `Autoxxx` plugins are not causing the issue

**Comment by SKBotNL** [comment]
> Aren't these frontlight and brightness values issues the effect of the floating point number problem? Which should be fixed in current nightlies?

Yep, just installed the latest development release, it's fixed now.
