### ISSUE TITLE
Shipping a default QuickMenu profile

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#9708]
I started using the new QuickMenu feature which is really useful (Thanks again @hius07).
Currently I am preparing an update to the guide so I started writing about this feature too.

I noticed that in order to introduce users to the **QuickMenu**, I have to first send them to the **Profiles** chapter of the guide (which I am also writing currently) to be able to create a QuickMenu.

My suggestion is shipping KOReader with a simple QuickMenu profile which is already assigned to a Gesture with some useful/example items. 

So we can simply say:
1. Do this gesture to open the QuickMenu
2. Go here to add or remove items

Which will:
- Decrease the friction very much
- Provide an already functioning example which people can modify (You know how useful it is when some app provides a sample project instead of an empty interface on the first run)
- And save users the effort of creating a profile and assigning a gesture to it which can be confusing for the non-technical user

**Comment by poire-z** [comment]
> I noticed that in order to introduce users to the QuickMenu, I have to first send them to the Profiles chapter of the guide (which I am also writing currently) to be able to create a QuickMenu.

I haven't really followed the profiles/quickmenu/gesture discussion/PR, but the end result is that you can create a QuickMenu directly from the Gesture menu, without needing any profile (and this works with the Profiles plugin disabled):
Just configure a gesture, add actions to it, and on the 2nd page of the actions list, there is a `[ ] Show as quickmenu` that you can just check: the gesture will then show all the selected actions as a menu, instead of executing them all.

So, may be there's now 2 ways to do that - and I don't really know if there's a difference in features/constraints in the end.

**Comment by hius07** [comment]
There is no need to use Profiles if a user has one QM only.
If there are many QMs, it's more convenient to manage them in Profiles, and the main benefit is showing QM's name in its title.

**Comment by offset-torque** [comment]
Wow, I tried and it is exactly like that. This is much better !
Users don't even need to leave the Gesture Manager.
Since I am adding this to the guide, I will close the issue.
Thanks for the replies **poire-z** and **hius07**.

**Comment by poire-z** [comment]
> If there are many QMs, it's more convenient to manage them in Profiles, and the main benefit is showing QM's name in its title.

May be long-pressing on "Show as QuickMenu" could be made to propose a widget to give this QuickMenu a name :)

**Comment by hius07** [comment]
Currently names can be stored in profiles.lua only, not in gestures.lua.

**Comment by poire-z** [comment]
Couldn't you store something else in the `setting(s)` key, where the ordering is stored ?

**Comment by yparitcher** [comment]
> Couldn't you store something else in the `setting(s)` key, where the ordering is stored ?

Please no ;)
