### ISSUE TITLE
FR: Don't let the device sleep at the end of the update

### ISSUE THREAD

**Issue by tcmtom** [koreader/koreader#9714]
**Does your feature request involve difficulty completing a task? Please describe.**
A clear and concise description of what the problem is. Ex. I think it takes too many steps to [...]
At the end of the update, when I needed to click install, a dialog box popped up for the device to sleep, which affected my ability to click install

**Describe the solution you'd like**
A clear and concise description of what you'd like to happen.
Don't let the device sleep at the end of the update.

**Describe alternatives you've considered**

**Additional context**
Add any additional context or screenshots about the feature request here.
![image](https://user-images.githubusercontent.com/94541098/198884478-423a721b-f407-4cb0-8647-d42157178fe4.png)

**Comment by Frenzie** [comment]
Did it take that long to download the update or did you set such a short timeout for suspend?

**Comment by tcmtom** [comment]
> Did it take that long to download the update or did you set such a short timeout for suspend?

All have.This pop-up window pops up together with the installation of the pop-up window.So I wonder if it is possible not to calculate the sleep time when updating.

**Comment by tcmtom** [comment]
> Did it take that long to download the update or did you set such a short timeout for suspend?

**Comment by NiLuJe** [comment]
It won't actually suspend until the download is done, so it's perfectly harmless, FWIW.

(That means: extremely low priority, especially as this might not be so trivial to actually implement).

**Comment by tcmtom** [comment]
> It won't actually suspend until the download is done, so it's perfectly harmless, FWIW.
> 
> (That means: extremely low priority, especially as this might not be so trivial to actually implement).

I know. Thank you.
