### ISSUE TITLE
AutoWarmth + Night mode + footer Auto refresh

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#9721]
Device: Kindle PW5
Version: 2022.10

Reported short (milliseconds) flashes (of the frontlight?) at the moments when the footer clock changes minutes.
Dunno if it is just an illusion of the screen refresh or a real frontlight flash.
I have no device with autowarmth, cannot reproduce and investigate.

**Comment by NiLuJe** [comment]
Process elimination would imply that the flashing be the frontlight, yeah, as footer refreshes are always non-flashing, so it can't be the usual nightmode+flashing refresh artifacts ;).

**Comment by zwim** [comment]
Just to circle in the issue. Who has reported the short flashes?
Has this person tried the same setting with the AutoWarmth plugin disabled?

**Comment by hius07** [comment]
> Who has reported the short flashes?

https://4pda.to/forum/index.php?s=&showtopic=541019&view=findpost&p=118362572



> Has this person tried the same setting with the AutoWarmth plugin disabled?

Yes, no flashes.

**Comment by zwim** [comment]
Thanks, I will look into it asap.

**Comment by zwim** [comment]
@hius07 OK, I understand that Ukrainian is not so easy to learn. But maybe a verbose debug log would help. Would it be possible to get one? It really might help to track down the problem.

**Comment by hius07** [comment]
Attached. A couple of flashes with interval about 1-2 min.

[crash.zip](https://github.com/koreader/koreader/files/9905560/crash.zip)

**Comment by zwim** [comment]
Thanks for the log. I am wondering why `scheduleNextWarmthChange` is scheduled on every minute. It would be very helpful to get the `settings.reader.lua` file.

**Comment by zwim** [comment]
I think I understand what is going on, but I not reproduce the bug now.

I will post a fix, soon. (For double check the `settings.reader.lua` file could help.)

**Comment by hius07** [comment]
I've asked the user for the settings file.

**Comment by hius07** [comment]
The settings file attached.
(I do not know if the user has checked out the nightly build with the fix).
[settings.reader.lua.txt](https://github.com/koreader/koreader/files/9958298/settings.reader.lua.txt)
