### ISSUE TITLE
Calibre Wireless Client allowing duplicate metadata entries when sending an ebook multiple times

### ISSUE THREAD

**Issue by lightmaster** [koreader/koreader#9722]
* KOReader version: 2022.10
* Device: Kindle PW4 gen 10

#### Issue
When you send the same book to KOReader (like after correcting an issue in the epub), it correctly overwrites the existing file on the filesystem, but creates a duplicate entry in `<library>/.metadata.calibre`. When you next connect to Calibre, that duplicate metadata entry tells Calibre that there are 2 copies of that book on the device, even though they both point to the same file. If you manually edit `.metadata.calibre` and remove the duplicate entry, then connect to Calibre, Calibre will correctly show that the book only exists once on the device. Issue was initially reported to Calibre [here](https://www.mobileread.com/forums/showthread.php?p=4269650), however they said the device client is responsible for creating and maintaining `.metadata.calibre`.
#### Steps to reproduce

1. Connect to Calibre wirelessly through Tools menu
2. Send epub (example.epub) to KOReader
3. Send the same epub (example.epub) to KOReader a second time (doesn't matter if you do it during the same connection or disconnect and then reconnect at a later time).
4. Disconnect from Calibre
5. Reconnect back to Calibre
6. Look at Calibre's "On Device" column. The book you sent twice will say "Main (2 books)". Right clicking and clicking on "Remove books > Remove matching books from device" will show that both copies of the book occupy the same Path.

##### `crash.log` (Verbose)
[crash.log](https://github.com/koreader/koreader/files/9905940/crash.log)

**Comment by pazos** [comment]
Good catch.

That's https://github.com/koreader/koreader/blob/master/plugins/calibre.koplugin/wireless.lua#L573

**Comment by pazos** [comment]
The proper way of fixing this would be:

on `CalibreMetadata:addBook` try to get the the index of `book.lpath` and, if there's one, change book properties at given index.

Not sure if calling `CalibreMetadata:removeBook` unconditionally and then insert the "new" book at the end of the array is any faster.

Both options imply traversing the table once. Any thoughts, @NiLuJe?

**Comment by NiLuJe** [comment]
I would assume the "replace" approach to be marginally better as there would be no table data moving ;).

**Comment by lightmaster** [comment]
Thanks for the quick work on this.
