### ISSUE TITLE
AutoWarmth plugin "Frontlight off during the day" behavior

### ISSUE THREAD

**Issue by offset-torque** [koreader/koreader#9728]
Firstly thanks for implementing this feature @zwim.

I started using it and today I noticed something:
- After sunrise, plugin turned my frontlight off while reading (as expected).
- It was still dark in the room so I turned the light back on.
- Then I opened the **File Browser** to open another book
- And frontlight turned off again.

I guess this is not the intended behavior. Because it leaves the user in the dark (literally :)
And it repeats this behavior if I switch between the **Reader view** and **File Browser** again.

**Expected behavior:** Keeping the last light state when opening the **File Browser**.

---

Also a **long-tap decription** of this feature in the UI can be helpful for users.
This is what I am planning to add to the guide, you can use this or edit it:

> This feature turns your frontlight on at sunset and turns it off at sunrise according to the “Currently active parameters” in this plugin. You can override this change by manually turning the frontlight on/off. On the next sunrise/sunset, AutoWarmth will toggle it again if it is necessary.

**Comment by zwim** [comment]
Thanks for reporting. 
I did not notice that behavior as I am lazy book switcher. I only go to FM if I have finished a book and want to open the next one ;-)

Thanks for the long tap hint.
