### ISSUE TITLE
FR: Fetching book progress when streaming books via OPDS-PS

### ISSUE THREAD

**Issue by Fivefold** [koreader/koreader#9732]
With page streaming via OPDS-PS support now added, it would be nice to be able to efficiently sync progress. Currently pushing progress from koreader to an OPDS server (only tested with Kavita by me) is working already (and is done automatically with no way to disable it as far as I know). What's missing is **fetching book progress when accessing a book via OPDS-PS**.

**Describe the solution you'd like**
When opening a book via OPDS-PS, progress should be fetched from the server and the book opens at the correct page. This could be default behaviour or it could be a choice when opening (e.g. "Start with first page" and "Continue reading")

**Current alternatives**
https://github.com/koreader/koreader/pull/9681 adds a "Stream from page" option, which allows opening a streamed book from a specific page. This still requires actually _knowing_ the page beforehand and thus is no progress fetching.

**Additional context**
Related issue: #9731
@bigdale123 said that different servers [serve their progress on different endpoints](https://github.com/koreader/koreader/issues/9731#issuecomment-1300630767), so proper progress sync would need to accomodate that, complicating the scope of the FR.

**Comment by bigdale123** [comment]
Damnit, you've made me catch the development bug again :). I'm gonna try getting this working for Kavita and then go from there.

**Comment by bigdale123** [comment]
Nevermind, some school project just got announced and it knocked my whole schedule out of whack. I'm not gonna have time to implement this :(.

**Comment by hius07** [comment]
Closed in favor of https://github.com/koreader/koreader/issues/9731.
