### ISSUE TITLE
Crashes after Power off gesture

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9741]
* KOReader version: 2022.10-50
* Device: Pocketbook 628

#### Issue
When I make the gesture I have set for powering off the device, a crash occurs. I set another gesture for this action but I had the same result.

##### `crash.log` (if applicable)
[crash 3-11-2022.txt](https://github.com/koreader/koreader/files/9930676/crash.3-11-2022.txt)

**Comment by NiLuJe** [comment]
Ping me again on Sunday, possibly related to the PB shenanigans I did recently, but can't investigate for a few days.

**Comment by ichnilatis-gr** [comment]
Dear @NiLuJe, I am pinging you as you requested.
Thank you for you time!

**Comment by NiLuJe** [comment]
Whelp, my cursory phone glance was right: I don't see any crash in that log :/.

**Comment by NiLuJe** [comment]
On the upside, it's quite likely https://github.com/koreader/koreader/pull/9569#issuecomment-1304845079 ;).

**Comment by NiLuJe** [comment]
Yup, got it in that one, thanks! Definitely the same issue as https://github.com/koreader/koreader/pull/9569#issuecomment-1304845079 ;).
