### ISSUE TITLE
Kobo: odd interaction with KSM when using power off

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#9748]
* KOReader version: cd693829344413ddc8d5aee7d0cad9a72dcfe747 (current master)
* Device: Kobo Aura H2O

#### Issue
KSM showed `KOReader has exited unexpectedly` after autoshutdown kicked in, but the device still shut down. The same can be reproduced by triggering shutdown from the menu or with a gesture.

Perhaps a regression from https://github.com/koreader/koreader/pull/9104? I almost never shut down my device.

#### Steps to reproduce
Exit → Power off will do the trick. It looks like the device does turn off shortly after the KSM crash message, but it's not the 30 second or so timeout in KSM itself. You actually still have a few seconds to quickly navigate KSM but then it does indeed shut down.

##### `crash.log` (if applicable)
There's nothing to see in it really. The added RTC logging is really nice though. ;-)

```
11/04/22-07:59:58 DEBUG refresh: wait for completion of marker 7 
11/04/22-07:59:58 INFO  quitting uimanager with exit code: 88 
11/04/22-07:59:58 INFO  no dialog left to show 
11/04/22-07:59:58 INFO  quitting uimanager with exit code: 88 
[ko-input] Closed input device with idx=2, fd=7
[ko-input] Closed input device with idx=1, fd=6
[ko-input] Closed input device with idx=0, fd=5
Restoring original fb bitdepth @ 16bpp & rotation @ 2
```

**Comment by Frenzie** [comment]
Or perhaps introduced in https://github.com/koreader/koreader/pull/6880?

**Comment by Frenzie** [comment]
Indeed:

```
  if [ $? -ne 0 ]; then
    echo "koreader exited spontaneously: $(date +%Y%m%d_%H%M%S)" >> $ksmroot/log/koreader_exit_log.txt
    selection=$($ksmroot/kobomenu.sh -autoselectafter=20  -autoselectoption=power_off -infolines=3 "-infotext=KOReader_exited_irregularly" power_off continue)
    if [ ${selection} == "power_off" ]; then
      sync
      $ksmroot/onstart/poweroff.sh
    fi
  fi
```

Although I don't think that condition used to be reached.

**Comment by NiLuJe** [comment]
Yeah, we were killed by init (or never killed at all), now we properly exit, so the exit code gets returned and handled properly.

**Comment by NiLuJe** [comment]
I'm not familiar with KSM, but that branch should possibly ignore our custom exit codes now ;).

**Comment by Frenzie** [comment]
> Yeah, we were killed by init (or never killed at all), now we properly exit, so the exit code gets returned and handled properly.

I'm not sure that sounds better for the purpose?

> I'm not familiar with KSM, but that branch should possibly ignore our custom exit codes now ;).

That'd just give you the same problem with a different coat of paint though, assuming you want it to display the poweroff screen.

That wouldn't change the fundamental problem, other than that it wouldn't say the unexpectedly thing.

**Comment by NiLuJe** [comment]
Ours or KSM's?

**Comment by Frenzie** [comment]
Ours. Like I said, you see the shutdown screen followed by unexpected exit. But in case of expected exit you'd still be in KSM.

**Comment by NiLuJe** [comment]
What does the unexpected exit thing look like in KSM?

What does a sane exit look like?

(Depending on your answer, my thinking would be it would make sense to *not* exit the script at all in this case for KSM).

**Comment by Frenzie** [comment]
Unexpected exit says unexpected exit, and that's mostly it depending on whether other conditions apply. E.g., it'll ask if you want to turn off wifi.

Expected exit will just take you back to the menu, ready to start something else, or if you're in a KOReader/Nickel loop for example it'll start Nickel.

> (Depending on your answer, my thinking would be that it would make sense to not exit the script at all in this case for KSM).

That's what I'm saying. ;-)
