### ISSUE TITLE
More accurate highlighting with on-screen buttons

### ISSUE THREAD

**Issue by Nepetalactone** [koreader/koreader#975]
After using highlights more extensively I noticed that it is sometimes really hard to properly mark what you want to highlight, particularly when the beginning or the ending of the highlight is at the border of the e-reader.

My suggestion is the addition of a small panel with six buttons, which appears once some text is highlighed. The six buttons provide the following functionality 
- move the start of the highlight one line back
- move the start one word back
- move the start one sign back
- move the end of the highlight one sign forward
- move the end one word forward
- move the end one line forward

**Comment by seacatwu** [comment]
when I use chinese-chinese dictionary,I can't lookup the word I really needed.
That's very useful function.
so expect to fix it.

**Comment by Sopheus** [comment]
Any news on the matter? 
Thanks in advance
