### ISSUE TITLE
Highlight boundary controls bug

### ISSUE THREAD

**Issue by SCassidy-UK** [koreader/koreader#9752]
After making a highlight on an epub, tapping on it allows you to manually adjust the boundaries by moving the start- and end-points of the highlight left or right. This is a highly welcome feature. However, it does not behave as I would expect it to. The boundaries only move between strings of letters. Instead they should move between whitespace, as currently there is no way to select the punctuation after a word. You cannot highlight a question or quote and adjust the boundaries to include the question mark or quotation marks, for example.

Example:

> Yet what is the very first thing you need to acquire? The very thing you are putting off...

If I want the first sentence but my fat fingers only highlight "Yet what is the very first thing you need to", then by adjusting the boundaries, I can only highlight "... need to acquire" or "... need to acquire? The". There is no way to get the word acquire and the question mark.

**Comment by poire-z** [comment]
Tap on the `###>` buttons will indeed grab by word. You can **long-press** on them to grab by character one by one (so, picking only your punctuation).

@offset-torque : I didn't find that mentionned in the User Guide in the section showing this widget.

**Comment by offset-torque** [comment]
> I didn't find that mentionned in the User Guide in the section showing this widget.

✅ Added to the to-do list

**Comment by offset-torque** [comment]
Info added to the guide. 
This issue can be closed.
Have a nice day !
