### ISSUE TITLE
FR: Increase space repetition in Vocabulary Builder

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9757]
Using "Vocabulary Builder" plugin I noticed that the maximum repetition interval is thirty days. Couldn't this increase even more for words we remember more easily? I have in mind the Anki app where the repetition intervals go up to months and years.
Dear @weijiuqiao, do you think that's too much?
Thanks!

**Comment by weijiuqiao** [comment]
I was hoping to get users to delete words they've practically remembered, but I too find it hard to delete words I've spent a lot of time remembering. So okay, longer intervals, why not. Also, after the sync PR is done, the next PR will allow reassigning words to other books including virtual ones added by users manually.
(I was hoping to get users to create a "book" named say `Mastered`, toss words into it and deny their reappearance in the list, without actually deleting them, so to solve the problem.)
