### ISSUE TITLE
FR: OS theme

### ISSUE THREAD

**Issue by xmha97** [koreader/koreader#9762]
Please add an option to use OS theme (dark/light)

![Screenshot_2022-11-08-02-08-11-332_org.koreader.launcher.fdroid.jpg](https://user-images.githubusercontent.com/23485114/200433968-fe68eba0-3782-4fc7-adfa-7a69a2928b03.jpg)

**Comment by pazos** [comment]
on android? see https://github.com/koreader/koreader/issues/8868
