### ISSUE TITLE
Can not open epub book in the Kindle （5.13.6）homepage

### ISSUE THREAD

**Issue by Gh9518** [koreader/koreader#9773]
* KOReader version:2022.10
* Device: KPW4 5.13.6

#### Issue
I know that kpvbooklet needs to be installed, but he does not support the latest version of the firmware, I hope to be able to update the kpvbooklet plugin or the next version of KOReader to open the associated epub file on the desktop

**Comment by Gh9518** [comment]
> * KOReader version:2022.10
> * Device: KPW4 5.13.6
> 
> #### Issue
> I know that kpvbooklet needs to be installed, but it does not support the latest version of the firmware, I hope to be able to update the kpvbooklet plugin or the next version of KOReader to open the associated epub file on the desktop

**Comment by Gh9518** [comment]
> * KOReader version:2022.10
> * Device: KPW4 5.13.6
> 
> #### Issue
> I know that kpvbooklet needs to be installed, but it does not support the latest version of the firmware, I hope to be able to update the kpvbooklet plugin or the next version of KOReader to open the associated epub file on the desktop

**Comment by pazos** [comment]
Already reported in https://github.com/koreader/kpvbooklet/issues/50

@NiLuJe: time to archive kpvbooklet?

**Comment by NiLuJe** [comment]
Definitely, didn't think of that ;).

I'll add a big fat warning to the top of the README (because I hate "silent" archived repos), and do that ;).

**Comment by pazos** [comment]
> Definitely, didn't think of that ;).
> 
> I'll add a big fat warning to the top of the README (because I hate "silent" archived repos), and do that ;).

Cool.

I've unpinned the repo and pinned crengine instead.

**Comment by NiLuJe** [comment]
Done w/ https://github.com/koreader/kpvbooklet/commit/6dc233c88631bf3b83316ecceba9ee7c0b6f2bd9
