### ISSUE TITLE
Book information: No folder information available when "Shorten home folder" is enabled

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9782]
* KOReader version: koreader-pocketbook-v2022.10-101-g678d0c91_2022-11-12
* Device: PB626

#### Issue
If option "Shorten home folder" is enabled, there is no folder information shown at "Book information"

#### Steps to reproduce
1. start KOReader
2. enable option "Shorten home folder" at the top menu in filemanager tab
3. open filemanager on home folder
4. pick some book and after holding touch select "Book information"
5. in the shown table there is in "Folder" row no folder information displayed

![book_information_home_folder_issue_0_highlight](https://user-images.githubusercontent.com/29783895/201520953-ec2c5eb6-dc78-45ba-aecf-d50e430a6ae6.png)

![book_information_home_folder_issue_1_highlight](https://user-images.githubusercontent.com/29783895/201520963-92c6633c-5213-4e45-8155-042953f5d34d.png)

#### Suggestion
My idea is to show information that is: Home with absolute path in brackets like below:

![book_information_home_folder_issue_2_highlight](https://user-images.githubusercontent.com/29783895/201521219-f19e2ceb-7b4d-4784-b0f9-ae46a1ea869f.png)

I have added a condition in file filemanagerbookinfo.lua starting at line 67

https://github.com/koreader/koreader/blob/779a8e00de21434a1de2fc66e15acc54fc20b9dd/frontend/apps/filemanager/filemanagerbookinfo.lua#L67

which can fix this behaviour. I have no experience in lua programming, therefore the code is "glued" from another pieces of lua files. It is functional, but maybe there is easier way to do it :)

```
local home_dir = G_reader_settings:readSetting("home_dir") or filemanagerutil.getDefaultDir()  
local len = directory:len()
-- tweak to show folder in book information in case of shorten home folder
if directory:sub(1, len-1) == home_dir then
    table.insert(kv_pairs, { _("Folder:"), BD.dirpath(_("Home") .. " (" .. directory .. ")"), separator = true })
else
    table.insert(kv_pairs, { _("Folder:"), BD.dirpath(filemanagerutil.abbreviate(directory)), separator = true }) 
end
```

**Comment by hius07** [comment]
Thank you, it is a bug in bookinfo.

Your proposition contradicts the rule of home folder shortening:
https://github.com/koreader/koreader/blob/779a8e00de21434a1de2fc66e15acc54fc20b9dd/frontend/apps/filemanager/filemanagermenu.lua#L339-L348

Just "Home" should be displayed, the same as in the header of the file browser. Is it okay for you?

**Comment by hius07** [comment]
Otherwise, the full path can be displayed, without any shortening.

**Comment by poire-z** [comment]
I'd rather just see `Home`.
(I was going to say: or `~/` - but it looks like we got rid of that, it was looking too techy :)

**Comment by Frenzie** [comment]
In a context like this a Home (/full/path) could make some sense, but yes, it should just say Home. :-)

**Comment by sonix-github** [comment]
> Just "Home" should be displayed, the same as in the header of the file browser. Is it okay for you?

Yes, it is OK for me also. Thanks
