### ISSUE TITLE
KOReader md export plugin - Help with export template for md

### ISSUE THREAD

**Issue by zenminimalist** [koreader/koreader#9789]
I'm trying to create a md template that essentially exports a md-file of my clipping with the following very basic format:

```
#Artemis: A Novel

**Book:** Artemis: A Novel
**Author:** Andy Weir 

It’s all part of the life-cycle of an economy. First it’s lawless capitalism until that starts to impede growth. Next comes regulation, law enforcement, and taxes. After that: public benefits and entitlements. Then, finally, overexpenditure and collapse
```

Each highlight would get added below the last one after a paragraph break without any references of pages etc. I took a look at the lua.md file (which is apparently the file that is responsible for any template-based output). 

I'm not really familiar with any coding, hence why I'm asking for help. 

Also, I'm seeing that the exported md-file is named something like 2022-11-14-22-32-00-.md. Is there a were to rename it to the title of the book?

**Comment by Frenzie** [comment]
You might want to try showing some of what you tried? Pinging @uroybd in case they're interested.

**Comment by zenminimalist** [comment]
>You might want to try showing some of what you tried? Pinging @uroybd in case they're interested.
Sorry, your right - forgot about that. Here's the code I changed in the md.lua file (in the folder: template):

`
```
local function prepareBookContent(book, formatting_options, highlight_formatting)
    local content = ""
    local current_chapter = nil
    content = content .. "# " .. book.title .. "\n\n"
    content = content .. "\n"
    content = content .. "**Book:** " .. book.title .. "\n"
    content = content .. "**Author:** " .. book.author:gsub("\n", ", ") .. "\n\n"
    for _, note in ipairs(book) do
        local entry = note[1]
        if highlight_formatting then
            content = content .. string.format(formatters[formatting_options[entry.drawer]].formatter, entry.text) .."\n"
        else
            content = content .. entry.text .. "\n"
        end
        if entry.note then
            content = content .. "\n---\n" .. entry.note .. "\n"
        end
        content = content .. "\n"
    end
    return content
end

return {
    prepareBookContent = prepareBookContent,
    formatters = formatters
}
```

**Output so far:**
```
# The Forever War

**Book:** The Forever War
**Author:** Joe Haldeman

*Modern warfare has become very complex, especially during the last century. Wars are won not by a simple series of battles won, but by a complex interrelationship among military victory, economic pressures, logistic maneuvering, access to the enemy's information, political postures-dozens, literally dozens of factors."*
```

The problem I'm having with the target format I described in my first comment is the following:

1. The **selected highlights come out italic with one ***.  Where is it getting the italic from in the code above? Am I missing something? 
2. The **export file name** is a timestamp of sorts, which I don't like. I rather have it take the book title as the file name output. I'm not finding where I have to change what. 

Again, I'm not a coder. :( I just tried changing it to what made sense to me.

**Comment by pazos** [comment]
Sadly the current behaviour of the plugin requires somebody with a bit of knowledge to tweak things. In your example

1. You get the italics from formatters.formatting_options.
2. You get the file name from [`getFilePath`](https://github.com/koreader/koreader/blob/master/plugins/exporter.koplugin/base.lua#L92)

To solve 1 you can remove everything and leave `entry.text` alone.
To solve 2 you can implement the same function in https://github.com/koreader/koreader/blob/master/plugins/exporter.koplugin/target/markdown.lua and remove the string format part when you prepend a timestamp. It should work as is if you want to export standalone books. You'll get "all-books.md" if you try to export the whole history.



I think we should be able

**Comment by pazos** [comment]
```lua
local function prepareBookContent(book, formatting_options, highlight_formatting)
    local content = ""
    local current_chapter = nil
    content = content .. "# " .. book.title .. "\n\n"
    content = content .. "\n"
    content = content .. "**Book:** " .. book.title .. "\n"
    content = content .. "**Author:** " .. book.author:gsub("\n", ", ") .. "\n\n"
    for _, note in ipairs(book) do
        local entry = note[1]
        content = content .. entry.text .. "\n"
        if entry.note then
            content = content .. "\n" .. entry.note .. "\n\n"
        else
            content = content .. "\n"
        end
    end
    return content
end
```

**Comment by zenminimalist** [comment]
> To solve 1 you can remove everything and leave entry.text alone.

Thanks, I fixed this by unchecking the "Format highlights based on style" option under the format menu option. No code change is necessary, but I used your code anyway :) Don't know why I didn't uncheck that option before, but it was a bit unintuitive.

>To solve 2 you can implement the same function in https://github.com/koreader/koreader/blob/master/plugins/exporter.koplugin/target/markdown.lua and remove the string format part when you prepend a timestamp. It should work as is if you want to export standalone books. You'll get "all-books.md" if you try to export the whole history.
>
>I think we should be able to take advantage of our beloved template function T in the long run and let users to pass a string with a header template (shared for all notes within a book or for all notes for all books in the history) and an note template (shared for each highlight)

That's what I'm really struggling with. I've got the file open.

I found the following snippet in the **markdown.lua**

```
function MarkdownExporter:export(t)
    local path = self:getFilePath(t)
    local file = io.open(path, "w")
    if not file then return false end
    for idx, book in ipairs(t) do
        file:write(md.prepareBookContent(book, self.settings.formatting_options, self.settings.highlight_formatting))
        if idx < #t then
            file:write("\n")
        end
    end
    file:close()
    return true
end
```

**However, in the base.lua I found the follow snippet:**

```
function BaseExporter:getFilePath(t)
    if not self.is_remote then
        local filename = string.format("%s-%s.%s",
            self:getTimeStamp(),
            #t == 1 and t[1].exportable_title or "all-books",
            self.extension)
        return self.clipping_dir .. "/" .. getSafeFilename(filename)
    end
end
```
So in stead of the   ` local filename = string.format("%s-%s.%s",` do I change it to  `local filename = string.format("book.title",` ?

**Comment by pazos** [comment]
Put the following chunk on your markdown target.

```lua
function MarkdownExporter:getFilePath(t)
    local filename = string.format("%s.%s",
        #t == 1 and t[1].exportable_title or "all-books",
        self.extension)
    return self.clipping_dir .. "/" .. filename
end
```

**Comment by zenminimalist** [comment]
@pazos Thanks, now it exports as a .md file. I tried to change it to `local filename = string.format("bool.title",` and it gives me "book.title.md

**Comment by pazos** [comment]
There must be a typo on your code or the book table does **not** have a field named `exportable_title`.

> I tried to change it to [...]

It doesn't work that way. you're asigning a string literal. It is going to use the same string *literally*.

If you want to tweak lua files please spend some time learning some basic lua. It is really a very beginner friendly language :)

**Comment by zenminimalist** [comment]
>There must be a typo on your code or the book table does not have a field named exportable_title.

That made me switch books (would have never thought had to do with a missing book title), and you're right! A different book worked! So it seems this previous book title has title, even though I transferred it via Calibre and all my books have titles. But now I now it works. 

Thanks so much!

Last question: 
Is there a way to export the md clipping file to a specific directory e.g. to a local Dropbox folder on the device instead of the clippings folder? That way I can use Dropbox sync on sync my clippings to Dropbox. 

I'm not sure if this has to be changed in the code as well or if I remember some menu setting where you could change where the clippings are saved. But I couldn'T find that menu setting for some reason. Or I'm getting old...

**Comment by pazos** [comment]
replace `self.clipping_dir` with a string containing the full path to the directory.

Something like "/mnt/onboard/WHATEVER" on a kobo.

Make sure that WHATEVER exists

**Comment by zenminimalist** [comment]
Thanks, that worked. Thanks to all here that helped out. Learned a lot in terms of where things are in the code and what some of it does. Love to see such a helpful community!
