### ISSUE TITLE
FR: [ PocketBook - add KEY_HOME for touch models ]

### ISSUE THREAD

**Issue by kaznelson** [koreader/koreader#9791]
**Does your feature request involve difficulty completing a task? Please describe.**
Allows to quickly go to the "Home" folder.

**Describe the solution you'd like**
Add **[C.KEY_HOME] = "Home"** to /applications/koreader/frontend/device/pocketbook/device.lua

**Describe alternatives you've considered**
(none)

**Additional context**
In a PocketBook the touch screen is traditionally a weak node (bad reaction) - I want to put more functions on the hardware buttons.

**Comment by NiLuJe** [comment]
How common is the Home button on current devices? (Not that it matters, just curious, as I haven't seen one since the original Kindle Touch, like, ten years ago ;))

**Comment by kaznelson** [comment]
The hardware button "Home" is on ALL current PocketBook models.

**Comment by pazos** [comment]
The key isn't fowarded to apps. Very much like android

**Comment by kaznelson** [comment]
But the hardware button "Home" in KOReader works...
[device.zip](https://github.com/koreader/koreader/files/10010448/device.zip)

**Comment by pazos** [comment]
Yup. It works in the sense it does something but the action it does is hardcoded and managed by the OS, not by applications.

**Comment by kaznelson** [comment]
Well, if the action for "Home" in the OS is set to (_none_), but the button in KOReader still works... ???

**Comment by pazos** [comment]
The home button in the OS does whatever. **The home button in apps retuns to the OS**

**Comment by kaznelson** [comment]
The "Home" button opens the KOReader's home folder. It's comfortable...

**Comment by kaznelson** [comment]
PS: Added **[C.KEY_HOME] = "LPgBack"** - makes page backward... ;)

**Comment by pazos** [comment]
lol, something must have changed a lot since the last time I've played with  a pocketbook. Apologies for the missinfo.

Is there any key press that retuns you back to PB launcher?

**Comment by kaznelson** [comment]
Is there a complete list of assignable events (such as "LPgBack", "LPgFwd")? You can also try...

**Comment by pazos** [comment]
I mean.Does the home button returns you back to PB launcher if you don't map it to any particular key? Or that doesn't work anymore?

Pinging @cellaris, since I seem to be very lost ATM

**Comment by kaznelson** [comment]
No. Only assigned to Home-action the "Home" button in the global OS buttons setting returns to the PB-Launcher.

**Comment by Cellaris** [comment]
> No. Only assigned to Home-action the "Home" button in the global OS buttons setting returns to the PB-Launcher.

Right.

**Comment by Cellaris** [comment]
Another example, in case it helps. Pressing the "menu" key (if left disabled for PocketBook) brings up the top and bottom menus of KOReader.

**Comment by NiLuJe** [comment]
Cool, so it should be harmless to handle it. At best, it works, at worst, InkView eats it and do stuff with it and we never get an event anyway ;).
