### ISSUE TITLE
PocketBook - "Menu" button not working when reading on a touch device

### ISSUE THREAD

**Issue by kaznelson** [koreader/koreader#9792]
* KOReader version: koreader-pocketbook-v2022.10-110-g06cec98d_2022-11-14
* Device: PocketBook Touch HD 3 Copper / 632 Bronze

#### Issue
"Menu" button not working  when reading.

#### Steps to reproduce
Open any fb2-book to KOReader, and press "Menu" hardware button - no response to pressing.

##### `crash.log` (if applicable)
Pressed buttons: PgFwd (1 click), PgBack (1 click), Home (1 click), Menu (4 clicks)
[crash.log](https://github.com/koreader/koreader/files/10010118/crash.log)

PS: In a PocketBook the touch screen is traditionally a weak node (bad reaction) - I want to put more functions on the hardware buttons...

**Comment by kaznelson** [comment]
Update^
**[C.KEY_MENU] = "Press"** открывает нижнее меню чтения, однако **[C.KEY_MENU] = "Menu"** не открывает верхнее меню настроек...

**Comment by NiLuJe** [comment]
You *probably* have Menu activation set to swipe only, which possibly prevents this from behaving (that's stupid, though, I'll look into it).

**Comment by kaznelson** [comment]
> You _probably_ have Menu activation set to swipe only

YES! Swipe only! Made a swipe+tap - now the top menu opens.
It's just that my ENTIRE screen turn page forward, and the extra taps are inconvenient...
[settings.reader.lua.zip](https://github.com/koreader/koreader/files/10015033/settings.reader.lua.zip)
