### ISSUE TITLE
FR: Search menu entry

### ISSUE THREAD

**Issue by zwmn-beep** [koreader/koreader#9800]
**Does your feature request involve difficulty completing a task? Please describe.**
Sometime I don't know exactly under which menu a certain entry can be found. Then I have to tap through a lot of menus.

**Describe the solution you'd like**
Something like

![grafik](https://user-images.githubusercontent.com/36999612/202395826-36681f36-1c17-4a81-a500-c218d1277654.png)

and then a keyvalue page to select an entry matching the search.

A tap on such an entry should open the appropriate menu-callback, a hold the hold-callback (or if that's to complicated, open the menu, where the entry is in.

**Comment by Frenzie** [comment]
Possibly, though I would want to investigate whatever you couldn't find first before putting bandaids on.

**Comment by zwim** [comment]
I think the menu structure is good, but after some time some things are hard to remember.

Where can I set 12/24hour?
There is an entry with "margins" but where was it?
I search some "statistics", is that in what menu? Battery/Plugin/ExitMenu(under Help?)
and so on.

**Comment by offset-torque** [comment]
@Frenzie 
I think this might be a good idea.
As KOReader gains new features, its complexity increases (not a bad thing).
Just **zwim**'s **Dimmer** and **Warmth control** features added ~30 entries to the menu system.
I can traverse menus on my computer with a mouse very quickly.
But on an e-ink device it is not a very pleasant experience.

**Comment by Frenzie** [comment]
Alright. How will we trigger it?

**Comment by poire-z** [comment]
Note that many menu items' text and submenus are generated dynamically when needed, with a `text_func`.

**Comment by hius07** [comment]
> A tap on such an entry should open the appropriate menu-callback,

What if it is a parent menu with submenus, without callback?

**Comment by poire-z** [comment]
Yeah, I think it should not open the appropriate menu callback.
It should, in slow motion, open and navigate all the menus to where the menu item is, to show you how to get to it. And, after 3 search & tap for a same menu item, it should open an InfoMessage saying "I've already shown you, stupid!", and refuse to answer the request for a duration based on some Conjugate Gradient Linear formula (over-engineering allowed !).

(I might then request "Search menu entry" to be moved outside the Search menu which contains only useful reading or word related search functions :)

Joking aside, I expect the complexity involved will somehow kill the idea.
