### ISSUE TITLE
exporter.koplugin panic when try to export highlights 

### ISSUE THREAD

**Issue by apletnev** [koreader/koreader#9801]
* KOReader version: 2022.10-112
* Device: kobo-hd

#### Issue

When I try to export highlights, the plugin crashes with a panic. Maybe because I have a lot of SDR files, and format of some of them is incorrect. 
 See a zip file below with all of my SDR directories, it should help.

#### Steps to reproduce
- Select any export formats 
- Select export all library

##### `crash.log` (if applicable)

```
11/17/22-17:00:16 DEBUG mxc_update: 1380x105 region @ (12, 245) with marker 25 (WFM: 1 & UPD: 0) 
./luajit: plugins/exporter.koplugin/clip.lua:290: attempt to compare number with nil
stack traceback:
	plugins/exporter.koplugin/clip.lua:290: in function <plugins/exporter.koplugin/clip.lua:290>
	[C]: in function 'sort'
	plugins/exporter.koplugin/clip.lua:290: in function 'parseHighlight'
	plugins/exporter.koplugin/clip.lua:317: in function 'parseHistoryFile'
	plugins/exporter.koplugin/clip.lua:330: in function 'parseHistory'
	plugins/exporter.koplugin/main.lua:158: in function 'exportAllNotes'
	plugins/exporter.koplugin/main.lua:256: in function 'callback'
	frontend/ui/widget/touchmenu.lua:876: in function 'onMenuSelect'
	frontend/ui/widget/touchmenu.lua:212: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:261: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:861: in function 'sendEvent'
	frontend/ui/uimanager.lua:51: in function '__default__'
	frontend/ui/uimanager.lua:1385: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1483: in function 'handleInput'
	frontend/ui/uimanager.lua:1530: in function 'run'
	./reader.lua:335: in main chunk
	[C]: at 0x000140bd
!!!!
Uh oh, something went awry... (Crash n°1: 11/17/22 @ 17:00:18)
Running FW 4.4.9439 on Linux 3.0.35+ (#5027 PREEMPT Tue May 16 12:37:27 CST 2017)
Attempting to restart KOReader . . .
!!!!
```

My SDR directories
[sdrs.zip](https://github.com/koreader/koreader/files/10032258/sdrs.zip)

**Comment by hius07** [comment]
Number of files doesn't mater.
It would help if you find the exact book on which the plugin crashes and show its metadat.zip.lua.

**Comment by apletnev** [comment]
The problem, that I don't know which one is incorrect, maybe need to "log" at least directory names in the plugin when try to  parse.
I thought, that sdr directories will help to execute them in emulator and see which one is incorrect and make a fix for the whole system.

**Comment by frozencircle** [comment]
Here metadata.epub.lua of a book in which lead to crash when try to export hightlight.
[metadata.epub.lua.txt](https://github.com/koreader/koreader/files/10034171/metadata.epub.lua.txt)

**Comment by hius07** [comment]
Thanks.
Can you delete the line No. 433 (it contains `[206] = {},`) and try if it crashes.

**Comment by frozencircle** [comment]
> Thanks. Can you delete the line No. 433 (it contains `[206] = {},`) and try if it crashes.

It still crashes.

**Comment by hius07** [comment]
> It still crashes.

I do not see your book in the sdrs.zip from the first post.
Do you have the same error?

**Comment by apletnev** [comment]
I think @frozencircle has the same error and provide his incorrect metadata file. :)

**Comment by frozencircle** [comment]
Yeah, same error, but i export hightlight for current (this) book only.

**Comment by hius07** [comment]
@frozencircle, for a while you can try to fix this book issue:
change the seconds in the string "2020-10-29 12:35:11" to 10.

**Comment by poire-z** [comment]
Indeed :)
Would it be fixed by some existing ReaderHighlight/ReaderBookmarks code if this book was re-opened in Reader ? Did we have to fix these past wrong duplicates?
If yes, the Exporter could just call these bits of code to "fix" highlights/bookmarks.
If no, well, no obvious way to reassociate them comes to mlind :/

**Comment by hius07** [comment]
Besides of the Exporter plugin, I think this will not cause a crash anywhere else, the only problem can be orphan highlights/bookmarks or impossibility to delete some items.

For old books there is this full scan:
https://github.com/koreader/koreader/blob/e8983d335db8263ba1cf76ccf81b061d17c6f465/frontend/apps/reader/modules/readerbookmark.lua#L429-L457

**Comment by hius07** [comment]
@apletnev, once the fix is merged, you can find the defect book: in its exported file one (or more) highlights will be not sorted by the position in the book but placed at the end of the list.
