### ISSUE TITLE
dictionary scroll

### ISSUE THREAD

**Issue by bousnah** [koreader/koreader#9805]
Having an old sony ereader I was able to scroll through a dictionary on a dictionary look-up function.  Thus, I could move forwards or backwards in the dictionary from the point of the found headword.
This function is missing in koreadrer with the stardict dictionaries. There would be no need to change any screen formatting. As it stands, the reader stops at the definition end thus ending the search or paging to the next dictionary. Instead, the reader would be able to see the next headword and so on choosing to continue looking at the following(or preceeding)head or key words and their definitions in each dictionary presented.  Hence, "reading" the dictionary like any book in koreader.  With this scrolling function readers may discover new and possibly related words to the word searched on. A great learning tool and vocabulary builder!

**Comment by NiLuJe** [comment]
I don't *think* this is really feasible, we make specific queries to sdcv, and it thens returns what it thinks matches those queries (or not). While you would assume that the dictionary be stored in a linear order, I'm not entirely sure this is technically a guarantee, and sdcv doesn't export that information anyway.

**Comment by bousnah** [comment]
A dictionary is indeed a book as well as a database like all books in an ereader.

What I am suggesting is that the end of file would not be the definition/s end of a particular headword but rather the end of the dictionary's "database".  Thus, all words and definitions become part of any headword searched and found.  The reader knows the end of a definition when the next key or headword appears. 

The code change would involve changing the end-of-file marker.  I think that would work.   Sony did it.

**Comment by poire-z** [comment]
We understand what you are suggesting.
We may not use the same dictionary format as Sony does.
We also don't do the dictionary scan/search/getresults ourselves: we use some external project tool, [sdcv](https://dushistov.github.io/sdcv/) which does the lookup (and the lot of things this involved with the stardict format) right. But it does not allow browsing the headwords and getting the definition for the "next headwords".
We don't really want to get involved in the stardict format scan/search/getresults stuff: we use this tool for that, and are happy. We don't really want to change the tool, or the format. So, what you wish will probably not happen.

(We also have tap left/right browse inside the definition, and when reaching the end of this dict definition, go displaying the result of the next dictionary - so allowing to read that word results as a book :) If we were able to implement what you wish, we would have to kill this feature.)

**Comment by NiLuJe** [comment]
> A dictionary is indeed a book as well as a database like all books in an ereader.

As @poire-z said, as was talking about the technical implications of the dictionary format we use; this wasn't a philosophical debate ;).

**Comment by pazos** [comment]
Even at a philosophical level we would reach to the [Rusell's paradox](https://en.wikipedia.org/wiki/Russell%27s_paradox)

**Comment by bousnah** [comment]
Well, would it be feasible to try it and see since there is not a
definitive not possible?  You may very well be right, however, I think that
it would be interesting to change the end of file to the database end and
thus inclusive to the searched headword and see what happens.  Again, if it
works there would be no need to change formatting.  Is this possible for
someone to modify and test the code?

I wish that I could contribute to the code but I am not a programmer and
have no knowledge in this area except for some familiarity with Dbase 2/3
4th generation code.

cordially

**Comment by bousnah** [comment]
A little confusing, your message.  Your point about browsing is not
correct; koreader(or sdcv)is only jumping to the next dictionary available
that has the headword. You are not "browsing" WITHIN any dictionary.

I still think that the end-of-file code could be modified to point to the
end of the database rather than end of definition.  The operational arrows
for navigation would not need to be modified.

I think that if there is access to the sdcv code it may be worth a try at
modification to see if this works.  As it stands, there is limited access
to dictionnaries.

cordially,

**Comment by pazos** [comment]
Hi.

No, it is not possible with the current backend.

and.

No, we're not interested in developing a new backend to fullfit your request.

So, to make things clearer I would label this FR as rejected and close this ticket.

**Comment by NiLuJe** [comment]
I really can't put it in plainer word than this: that's just not how this works (on a technical level), sorry ;).
