### ISSUE TITLE
FR: [Sync highlights (and maybe notes later) across different KOReader devices]

### ISSUE THREAD

**Issue by zenminimalist** [koreader/koreader#9815]
**Does your feature request involve difficulty completing a task? Please describe.**
Currently KOReader syncs the reading progress (which is really awesome!), but does **not** sync the highlights when reading the same book on different devices.

**Describe the solution you'd like**
It should also sync the highlights (this should also be positional information similar to the progress location. E.g. Highlight pages 23 fron X-Y,...). Later one could expand this feature to notes. 

**Describe alternatives you've considered**
Currently none that enable a seamless sync like the progress sync does. 

**Additional context**
Is this in the work already? Seems like the next logical step, enabling highlights sync by extending the existing progress sync feture. I personally don't use notes, but I can see how that would also be useful in the nest step.

**Comment by pazos** [comment]
Please do check open feature requests before opening duplicates
