### ISSUE TITLE
Autowarmth plugin problem with Kindle Oasis 3

### ISSUE THREAD

**Issue by fw88** [koreader/koreader#9817]
* KOReader version: 2022.10
* Device: Kindle Oasis 3

#### Issue

If night mode is enabled in the autowarmth plugin after sunset, the screen refreshes every 1 minute. The screen flickers from white to black on the minute every minute. 

This also happened in the autowarmth plugin in version 2022.08. This didn't happen in the patched autowarmth plugin in 2022.07 (I previously reported another bug in the autowarmth plugin which needed a slight change in 2022.07 version).

#### Steps to reproduce

Enable autowarmth. Set night mode on after sunset. Read any book.
With autowarmth plugin turned off, this glitch doesn't happen. If I use the patched 2022.07 autowarmth plugin this doesn't happen.

##### `crash.log` (if applicable)
Uploaded.

[crash.log](https://github.com/koreader/koreader/files/10049987/crash.log)

**Comment by hius07** [comment]
Seems to have been fixed, look at https://github.com/koreader/koreader/issues/9721.

**Comment by zwim** [comment]
Can you try a nightly build, to see if it is fixed. There have been a lot of updates to autowarmth since the 2022.10 milestone.

**Comment by fw88** [comment]
Ok I'm downloading and installing the latest nightly build now to see if it gets solved. Thanks for the work and quick responses!
