### ISSUE TITLE
Plugin folder within koreader folder completely empty, BOOX Note Air 2

### ISSUE THREAD

**Issue by zenminimalist** [koreader/koreader#9818]
* KOReader version: 2022.10
* Device: BOOX Note Air 2

#### My plugin folder within the koreader folder is completely empty. 

**Steps I've tried:**
- activating and deactivating the plugins, restarting koreader
- reinstalling koreader
- reinstalling after deleting the complete koreader folder with it, and starting fresh
- reinstalling a 2-version older koreader after deleting the complete koreader folder with it, and starting fresh

However, the plugin folder remains empty even though the plugins are activated in koreader. I can't edit any plugins that I want to change now as there's nothing to edit. 

On my Kindle, I have plugins in my plugin folder. If I copy these plugins over to my NA2, then the plugins show up twice in the plugin menu?! 

![IMG_2404](https://user-images.githubusercontent.com/7798503/202921175-fb9e41c9-6bb3-4e06-84d9-202d95a6b4e4.jpg)

Never encountered this before. Is there any way I can force koreader to install these plugins the right way and not copy them over and have them show up multiple times in my menu?

**Comment by poire-z** [comment]
I assume your Boox is using Android.
On Android, the normal KOReader code is in its own application code directory (`/data/app/org.koreader/` or something like that) which is unaccessible by the user. It's there that our shipped plugins are. Then, there is `/sdcard/koreader/` (or something like that) where your settings, data/dicts and other stuff is. There, we also create an empty `plugins/` subdirectory where a user can drop non-shipped plugins (= user plugins, that can be found in [other github users' repositories](https://github.com/search?q=koplugin&type=repositories)). We do that because you could not drop these among the shipped ones, so we create this empty dir to let you know you can drop them. (And if you drop there a copy of our shipped ones, no wonder they appear twice, and shit can then happen :)

Kobo and Kindle are free of this Android crazyness about security and isolation, they let us run KOReader as root - and let you access the shipped code, because it's you who installed that code anyway.

**Comment by poire-z** [comment]
And if you indeed need to hack our shipped plugins, well, they are like our core code: not hackable by the user on Android.
So you'd need to use user patches, like if you wanted to modify core.
Or copy an existing shipped plugin, and give it another name - and disable our shipped one.

**Comment by zenminimalist** [comment]
Thanks for the info. I'm trying to basically copy this change I made [here](https://github.com/koreader/koreader/issues/9789) for Kindle to my Android BOOX device. I have root on this, but only found two folders and nothing that resembles a plugins folder for data/apps. Am I missing something? 

Or is that what you meant with this?
>And if you indeed need to hack our shipped plugins, well, they are like our core code: not hackable by the user on Android.

If so, Android sucks in that regard. : (

So the only way to achieve the change I want it to?
>Or copy an existing shipped plugin, and give it another name - and disable our shipped one. 

If so, where do I deactivate it? In the menu? Or in the settings.reader file so it doesn't show up twice in the menu? 

Not related: You wouldn't happen to know the root password for the Kindle PW (11gen). Been looking for that : )

**Comment by NiLuJe** [comment]
> Not related: You wouldn't happen to know the root password for the Kindle PW (11gen). Been looking for that : )

root account are locked (have been for a few years now), so even if you had the password, it wouldn't help (but you can get it nonetheless with KindleTool). USBNet's dropbear daemon is patched to bypass this, so I have no idea why you'd want the password in the first place.

**Comment by poire-z** [comment]
> If so, where do I deactivate it? In the menu? 

In `Tools > More tools > Plugin management > [ ] Export highlights` - uncheck it (I assume this is the plugin you want to replace).
I have no idea if "user plugins" will appear there. But you may want to give your copy another `name` and `fullname` (in main.lua and _meta.lua).

The other solution are [user patches](https://github.com/koreader/koreader/wiki/User-patches), but I have no idea if they can work with plugins. They would allow you to just replace the functions you need to hack - so you could mostly benefit from any other update to the module (unless they refactor and your user patch needs to be adapted).

**Comment by zenminimalist** [comment]
>I have no idea if "user plugins" will appear there. But you may want to give your copy another name and full name (in main.lua and _meta.lua).

I did that. It does show up with the other one as well. However, after a restart, it will revert back to unchecked. Am I missing a step?

**Comment by poire-z** [comment]
May be the directory name should also be changed to `mdexporter.koplugin/` ?

**Comment by pazos** [comment]
Late to the party

> I have root on this, but only found two folders and nothing that resembles a plugins folder in data/apps. Am I missing something?

The cannonical path on android is `/data/data/org.koreader.launcher$(optional_number)/files`

> If so, Android sucks in that regard. : (

Android sucks for many other reasons but this one is shared with mac (which also sucks) and Linux apps. Mostly any os that is multiuser capable might have an installation made by an admin (or stored in read-only storage, like appImage) and the user won't have permissions to touch code in there.

Hence dataDir being in a different path from install dir.

> May be the directory name should also be changed to `mdexporter.koplugin/` ?

Indeed. @zenminimalist might also want to do the same in its kindle, otherwise local changes will be overwritten by OTA updates each time the plugin is changed. And that's going to happen soon :)

**Comment by zenminimalist** [comment]
Thanks so helpful with infos. 

>The cannonical path on android is /data/data/org.koreader.launcher$(optional_number)/files
This is the only thing I get. So I don't think I'll get further than that. 
![IMG_2405](https://user-images.githubusercontent.com/7798503/202930401-c2d8db64-4791-4223-b674-d8180ecd4cd9.JPG)

>May be the directory name should also be changed to mdexporter.koplugin/ ?

I did that a now we're getting somewhere. However, when I go to export I get the message "Exporting may take..." Then the message "markdown: Failed to export" I don't see a log or crash in the koreader directory either.

**Comment by pazos** [comment]
> This is the only thing I get. 

That doesn't look like `/data/data` or `/data/user/x`. Anohow that's not needed. I mentioned just for reference.

> ... So it seems to have something to do with the Android setup ....

You cannot expect the same plugin to work on both devices without any change. You did change the path to match a folder that's available on the kindle. You need to do the same on android.

**Comment by zenminimalist** [comment]
>You cannot expect the same plugin to work on both devices without any change. You did change the path to match a folder that's available on the kindle. You need to do the same on android.

Do you mean in the main.lua file of the plugin folder? And which path do you mean? The export location path is the same and exists on both devices.

**Comment by poire-z** [comment]
Probably the export location path.
The "absolute" path of it can't be the same on Kindle and Android - the relative path may be, but you're not sure of where koreader works (the starting point of the relative path). That's why the path should be made absolute using stuff like getDataDir() may be (which I don't know what it is in Android, probably /sdcard/koreader/ or some subdir).

**Comment by zenminimalist** [comment]
@pazos The path that I have was /highlights in the `clipping_dir = DataStorage:getDataDir() .. "/highlights",` I did however change to the path `/storage/emulated/0/koreader/highlights` as you suggested and that did _not_ work. The plugin didn't even get picked up by koreader with the absolute path. So the relative path doesn't seem to be the issue. It must be something else that Android doesn't like. 

Here my current [main.lua.zip](https://github.com/koreader/koreader/files/10057082/main.lua.zip)

Is there a way I can force koreader to give me more info on why the export failed?

**Comment by zenminimalist** [comment]
Mhh...not really familiar woith adb logcat. 

I'm guessing this is the part of the code where it gets an error ` table.insert(statuses, _(v.name .. ": Failed to export.")):` That's the second message I get if I try to export.

```
function Exporter:exportClippings(clippings)
    if type(clippings) ~= "table" then return end
    local exportables = {}
    for _title, booknotes in pairs(clippings) do
        table.insert(exportables, booknotes)
    end
    local export_callback = function()
        UIManager:nextTick(function()
            local timestamp = os.time()
            local statuses = {}
            for k, v in pairs(self.targets) do
                if v:isEnabled() then
                    v.timestamp = timestamp
                    local status = v:export(exportables)
                    if status then
                        if v.is_remote then
                            table.insert(statuses, _(v.name .. ": Exported successfully."))
                        else
                            table.insert(statuses, _(v.name .. ": Exported to " ) .. v:getFilePath(exportables))
                        end
                    else
                        table.insert(statuses, _(v.name .. ": Failed to export."))
                    end
                    v.timestamp = nil
                end
            end
            UIManager:show(InfoMessage:new{
                text = table.concat(statuses, "\n"),
                timeout = 3,
            })
        end)

        UIManager:show(InfoMessage:new {
            text = _("Exporting may take several seconds…"),
            timeout = 1,
        })
```
So was wondering if there's some function that it's calling locally that has to be renamed e.g. `clippings` or something.

Alternatively, I'm not sure if these functions  here:
```
local DataStorage = require("datastorage")
local Device = require("device")
local InfoMessage = require("ui/widget/infomessage")
local MyClipping = require("clip")
local NetworkMgr = require("ui/network/manager")
local UIManager = require("ui/uimanager")
local WidgetContainer = require("ui/widget/container/widgetcontainer")
local logger = require("logger")
local _ = require("gettext")
```
 are also on android or need to be renamed or the path is different.

**Comment by poire-z** [comment]
^ These local require should work, otherwise KOReader wouldn't start. Don't worry about them.

But better get familiar with adb / logcat (look for an app, if you have some app store on your Boox) - or you could continue guessing for weeks :/
But if you are root, I guess you can just run `logcat` in a shell ?

**Comment by zenminimalist** [comment]
I'll try that, thanks.

I did see another lua file on my _kindle_ that seems to reference Android specifically `(-- need low-level mechnism to detect android to avoid recursive dependency)` that I do **not** have in my koreader directory on my Android device. Or is that irrelevant?
```
-- need low-level mechnism to detect android to avoid recursive dependency
local isAndroid, android = pcall(require, "android")
local lfs = require("libs/libkoreader-lfs")

local DataStorage = {}

local data_dir
local full_data_dir

function DataStorage:getDataDir()
    if data_dir then return data_dir end

    if isAndroid then
        data_dir = android.getExternalStoragePath() .. "/koreader"
    elseif os.getenv("UBUNTU_APPLICATION_ISOLATION") then
        local app_id = os.getenv("APP_ID")
        local package_name = app_id:match("^(.-)_")
        -- confined ubuntu app has write access to this dir
        data_dir = string.format("%s/%s", os.getenv("XDG_DATA_HOME"), package_name)
    elseif os.getenv("APPIMAGE") or os.getenv("KO_MULTIUSER") then
        if os.getenv("XDG_CONFIG_HOME") then
            data_dir = string.format("%s/%s", os.getenv("XDG_CONFIG_HOME"), "koreader")
        else
            local user_rw = jit.os == "OSX" and "Library/Application Support" or ".config"
            data_dir = string.format("%s/%s/%s", os.getenv("HOME"), user_rw, "koreader")
        end
    else
        data_dir = "."
    end
    if lfs.attributes(data_dir, "mode") ~= "directory" then
        lfs.mkdir(data_dir)
    end

    return data_dir
end

function DataStorage:getHistoryDir()
    return self:getDataDir() .. "/history"
end

function DataStorage:getSettingsDir()
    return self:getDataDir() .. "/settings"
end


function DataStorage:getFullDataDir()
    if full_data_dir then return full_data_dir end

    if string.sub(self:getDataDir(), 1, 1) == "/" then
        full_data_dir = self:getDataDir()
    elseif self:getDataDir() == "." then
        full_data_dir = lfs.currentdir()
    end

    return full_data_dir
end

local function initDataDir()
    local sub_data_dirs = {
        "cache", "clipboard",
        "data", "data/dict", "data/tessdata",
        "history", "ota", "plugins",
        "screenshots", "settings", "styletweaks",
    }
    for _, dir in ipairs(sub_data_dirs) do
        local sub_data_dir = string.format("%s/%s", DataStorage:getDataDir(), dir)
        if lfs.attributes(sub_data_dir, "mode") ~= "directory" then
            lfs.mkdir(sub_data_dir)
        end
    end
end

initDataDir()

return DataStorage
```

**Comment by pazos** [comment]
@zenminimalist: I'm not too interested on your issue unless you're able to reproduce it without any code changes (just the renamed plugin on `/sdcard/koreader/plugins`)

But others might want to help. Things would be easier if you could

1. attach the diff of your code changes vs the plugin we bundle.
2. (if not 1) attach the entire plugin, not just `main.lua`.

I know. Trying to lurk over a codebase without basic knowledge is a bit of a pain. And remote helping is nor fun nor a pleasant experience. So if either 1 or 2 is fullfited things would be easier for any potential helper hand :)

Anyways, I plan to do a PR this weekend based on your feedback in #9789, mostly just

> I think we should be able to take advantage of our beloved template function T in the long run and let users to pass a string with a header template (shared for all notes within a book or for all notes for all books in the history) and an note template (shared for each highlight)

So things will become much easier for the kind of changes you're attemping to do ;)

In the mean time either learning a bit of lua or helping the people that would like to help you are my recommendations :)

**Comment by zenminimalist** [comment]
>I'm not too interested on your issue unless you're able to reproduce it without any code changes (just the renamed plugin on /sdcard/koreader/plugins)

I did change some of the files within the plugin (template file) and is changed it based on #9789. 

Other than that, I also changed the main.lua and meta file. Find the whole plugin attached (slightly different from the plugin I attached [earlier](https://github.com/koreader/koreader/issues/9818#issuecomment-1321244379). 
[mdexporter.koplugin.zip](https://github.com/koreader/koreader/files/10058202/mdexporter.koplugin.zip)

>Anyways, I plan to do a PR this weekend based on your feedback in https://github.com/koreader/koreader/issues/9789, mostly just
Nice! That would be very helpful. 🚀

**Comment by pazos** [comment]
@zenminimalist: since you're interested in markdown I would ask you a favor:

Please explore both the "single book export" and the "whole history export"  and provide me a minimum sample to be used in the template. I understand they're both different. For instance on single book export it could make sense to have the author on top, while on multiple books it doesn't.

**Comment by pazos** [comment]
Also a note: the new template will get rid of the actual formatter options. All customization will happen on the template itself.

The way for final users to tweak their templates will be something like:

1. copy `plugins/exporter.koplugin/template/markdown-header-single.template` to `settings`
2. edit `settings/markdown-header-single.template` at your like.

**Comment by zenminimalist** [comment]
@pazos Thanks for making this FR in the next release. Here's the input you asked for.

**Single book export template**

#[Book title]

**Book:** [book title]
 **Author:** [author]

Highlight 1
[paragraph break]
Highlight 2
[paragraph break]

**Example**
```
#Artemis: A Novel

**Book:** Artemis: A Novel
**Author:** Andy Weir 

It’s all part of the life-cycle of an economy. First it’s lawless capitalism until that starts to impede growth. Next comes regulation, law enforcement, and taxes. After that: public benefits and entitlements. Then, finally, overexpenditure and collapse.
```

**whole history export**

#[Book title1]

**Book:** [book title]
 **Author:** [author]

Highlight 1
[paragraph break]
Highlight 2
[paragraph break]
[paragraph break]
#[Book title2]

**Book:** [book title2]
 **Author:** [author]

Highlight 1
[paragraph break]
Highlight 2
[paragraph break]

**Example**
```
#Artemis: A Novel

**Book:** Artemis: A Novel
**Author:** Andy Weir 

It’s all part of the life-cycle of an economy. First it’s lawless capitalism until that starts to impede growth. Next comes regulation, law enforcement, and taxes. After that: public benefits and entitlements. Then, finally, overexpenditure and collapse.


#Romeo and Juliet

**Book:** Romeo and Juliet
**Author:** William Shakespeare

That Shakespeare was born is excellent; that he married and had children is pleasant; but that we know nothing about his departure from Stratford to London or about the beginning of his theatrical career is lamentable and must be admitted. We would gladly sacrifice details about his children’s baptism for details

In 1592, thanks to the cantankerousness of Robert Greene, we have our first reference, a snarling one, to Shakespeare as an actor and playwright. Greene, a graduate of St. John’s College, Cambridge, had become a playwright and a pamphleteer in London, and in one of his pamphlets he warns three university-educated playwrights against an

```

Notice, between two books there is a double paragraph break in the _whole history export_.


>The way for final users to tweak their templates will be something like:
>copy plugins/exporter.koplugin/template/markdown-header-single.template to settings
>edit settings/markdown-header-single.template at your like.

I can see this working on Kindle with no problem. However, on Android, there is no exporter.koplugin in the plugins folder.

**Comment by zenminimalist** [comment]
Also, if you need or want the `md.lua` file I'm currently using on my kindle, let me know. This works on kindle, but can't get it to work on Android.

**Comment by pazos** [comment]
Thanks for the feedback :)

>  Ideally, the whole history export would export each book into a separate md-file in the same format as above. If that is not possible, then see below.

I'm afraid it isn't intended that way. The intention is to export everything on a single file. Lets keep it that way for the moment. Of course implementing something like that on the future  as a toggable option shouldn't be too hard.

> I can see this working on Kindle with no problem. However, on Android, there is no exporter.koplugin in the plugins folder.

Good point.

Need to think a bit about that. 

> Also, if you need or want the md.lua file I'm currently using on my kindle, let me know. This works on kindle, but can't get it to work on Android.

No, thanks! The whole point is to get rid of md.lua and use a `templater.lua`  instead.
Also your samples are going to be used as inspiration but I'm going to preverse default format as is.

**Comment by zenminimalist** [comment]
>Need to think a bit about that.

Is there a way to put the template file somewhere that's more or less device independent? Wouldn't that solve that issue? So essentially no matter what device one is on it would also check that location to see if there's a template overriding the default format.

>Also your samples are going to be used as inspiration but I'm going to preverse default format as is.

So can I copy over my format in the `md.lua `to the new `templater.lua` file?

**Comment by zenminimalist** [comment]
@pazos Have you had time to think about [this](https://github.com/koreader/koreader/issues/9818#issuecomment-1328118170). Would be nice to export similarly on both devices on different OSes.
