### ISSUE TITLE
Numbered dictionary entries are not found

### ISSUE THREAD

**Issue by vejkse** [koreader/koreader#9828]
* KOReader version: v2022.10
* Device: Kobo Aura One

#### Issue

Numbered entries (i.e. separate entries for homonyms that are numbered in the index) are not found by the dictionary lookup in koreader.

#### Steps to reproduce

Some dictionaries have numbered entries.  For instance, in the Gaffiot dictionary, “Komarov” edition, Stardict Mobile ([https://cerclelatin.org/wiki/Home#ressources-didactiques_dictionnaires](https://cerclelatin.org/wiki/Home#ressources-didactiques_dictionnaires)), there are two entries “recessus (1)” and “recessus (2)”.  The same in the Georges Latin-German dictionary ([http://download.huzheng.org/de/stardict-georges_lat-de-2.4.2.tar.bz2](http://download.huzheng.org/de/stardict-georges_lat-de-2.4.2.tar.bz2)), but without space before the opening parenthesis: “recessus(1)” and “recessus(2)”.

After installing those dictionaries, searching for “recessus” in the dictionary lookup gives none of the 4 entries mentioned above among the 16 fuzzy results.

On the other hand, searching for “recessus 1” gives 3 out of 4 as the first results, and the 4th is a bit further down, so this could be a work-around when one notices that something should be there but nothing is found.

**Comment by poire-z** [comment]
[sdcv](https://dushistov.github.io/sdcv/), that we use to do the lookup in stardict dictionaries, may have (or have had?) issues when multiple entries/definitions.
But in your case, looking at your Gaffiot dict, it feels it is this dict that is buggy:
It indeed has `recessus (1)` and `recessus (2)` among its headword in the .idx file. It looks to me it shouldn't have that, and only either one headword `recessus` pointing to these 2 definitions (which, themselves, can have (1) and (2) inside the definition), or 2 headwords `recessus` pointing each to a definition (don't really know which of these 2 options is how stardict want them).
These `(1)` and `(2)` have nothing to do in the index, and it's not for the querying code to ignore/skip/fuzzy-ignore them when scanning the index for matches...

**Comment by vejkse** [comment]
So the solution would be to modify the stardict dictionaries.  I removed the numbers using `stardict2txt` and `tabfile` from `stardict-tools` and now all entries are found.  But the formatting (bold, italic) is ignored by koreader (even though it’s still there).

**Comment by poire-z** [comment]
Check (and correct it if different) that the new .ifo (if generated by your tool) has:
`sametypesequence=h` ('h' means the definitions content is HTML).

**Comment by vejkse** [comment]
Thank you!  This restored the formatting. Now everything is fine.

**Comment by poire-z** [comment]
Looks like I've been using that same Gaffiot dict.
I have added alongside its dict files this lua file: [Gaffiot2016Stardict-v1.3.lua.txt](https://github.com/koreader/koreader/files/10087521/Gaffiot2016Stardict-v1.3.lua.txt) (remove the .txt extension, it should have the same base as the .ifo), to tweak its returned HTML before it is displayed by KOReader.
Not exactly sure what these tweaks were for, but may be you'll like them.

```lua
return function(html)
    html = html:gsub('<b>&nbsp;&nbsp;&nbsp;&nbsp;', '<br/><b>◤ ')
    html = html:gsub('<b><i> .%)</i>', '<br/>%1')
    html = html:gsub('¶ ', '<br/><br/> ◆ ')
    html = html:gsub('||', '<br/>■ ')
    html = html:gsub(' ; <i>', ' ;<br/>▫ <i>')
    -- html = html:gsub('</i>  ([^<])', '</i><br/>%1')  
    -- html = html:gsub(' style="font%-variant: small%-caps', ' style="font-size: 0.7em')
    return html
end
```

**Comment by vejkse** [comment]
These tweaks make it much less linear.  I will try a variant of it.  Thank you!
