### ISSUE TITLE
ScreenSaver fortune support.

### ISSUE THREAD

**Issue by greatyingzi** [koreader/koreader#9831]
I want write a screensaver fortune,but I have some doubts ,is it a plugin or screensave text info? @NiLuJe

**Comment by NiLuJe** [comment]
It 100% *should* be a plugin.

Whether it *can* be is another kettle of fish, though.

(i.e., might require heavy refactoring or something, so, beware).

**Comment by Frenzie** [comment]
Possibly not too heavy, or put another way the answer can simply maybe be both without too much effort. But then again I haven't looked at the code. ;-)

**Comment by pazos** [comment]
Feel free to ask questions. Always happy to improve integration with 3rd party plugins :)

Also happy if you want to contribute plugins to https://github.com/koreader/contrib
