### ISSUE TITLE
can't start koreader

### ISSUE THREAD

**Issue by fly2summer** [koreader/koreader#9835]
* KOReader version: koreader-kindlepw2-v2022.10
* Device: kpw3

#### Issue: can't start koreader 

kaul log:
cp: can't preserve ownership of '/var/tmp/koreader.sh': Operation not permitted
cp: can't preserve ownership of '/var/tmp/fbink': Operation not permitted
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 113: can't create /dev/console: Permission denied
sh: write error: Broken pipe
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 197: can't create /dev/console: Permission denied
sh: write error: Broken pipe
iptables v1.4.15: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.
cat: can't open '/dev/fb0': Permission denied
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 295: can't create /dev/console: Permission denied
sh: write error: Broken pipe
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 295: can't create /dev/console: Permission denied
sh: write error: Broken pipe
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 295: can't create /dev/console: Permission denied
sh: write error: Broken pipe
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 295: can't create /dev/console: Permission denied
sh: write error: Broken pipe
killall: can't kill pid 12630: Operation not permitted
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
stop: Name "com.ubuntu.Upstart" does not exist
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 309: can't create /dev/console: Permission denied
sh: write error: Broken pipe
killall: can't kill pid 1878: Operation not permitted
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 312: can't create /dev/console: Permission denied
sh: write error: Broken pipe
[FBInk] [fbink_open] Cannot open framebuffer character device: Permission denied!
[CLI] Failed to open the framebuffer, aborting . . .
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 343: can't create /dev/console: Permission denied
sh: write error: Broken pipe
killall: can't kill pid 1878: Operation not permitted
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
start: Name "com.ubuntu.Upstart" does not exist
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 409: can't create /dev/console: Permission denied
sh: write error: Broken pipe
killall: can't kill pid 12630: Operation not permitted
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 409: can't create /dev/console: Permission denied
sh: write error: Broken pipe
/var/tmp/koreader.sh: line 409: can't create /dev/fb0: Permission denied
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 409: can't create /dev/console: Permission denied
sh: write error: Broken pipe
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 409: can't create /dev/console: Permission denied
sh: write error: Broken pipe
logger: /etc/passwd: bad record
/var/tmp/koreader.sh: line 415: can't create /dev/console: Permission denied
sh: write error: Broken pipe
iptables v1.4.15: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by hius07** [comment]
It's definitely not KOReader but jailbreak issue. Reinstall the jailbreak or at least the hotfix.

**Comment by NiLuJe** [comment]
Yup, you're no longer root, which might happen when crossing a specific FW version threshold with very old bridge code.
