### ISSUE TITLE
Calibre plugin: segmentation fault after return from metadata search with no items found

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9836]
* KOReader version: v2022.10-129-g1c426417_2022-11-22
* Device: PocketBook 626

#### Issue
After calibre metadata search with no items found, empty list is shown. In the bottom left corner is "return" button and after tapping on it KOReader crashes.
![calibre_plugin_issue-button_highlight](https://user-images.githubusercontent.com/29783895/204125460-abbf4790-e63e-4e7d-b6d6-b7e019543a06.png)

#### Steps to reproduce
1. open file manager
2. open top menu and select search tab
3. select "Calibre metadata search"
4. search for some "nonsense" from series, tags or books so no match occurs :-)
5. an empty list will be shown
6. tap on "return" button located at bottom left corner
7. KOReader crash caused by segmentation fault occurs

##### `crash.log` (if applicable)
<details>
  <summary>crash.log</summary>

```
./luajit: plugins/calibre.koplugin/search.lua:419: attempt to index local 'path_entry' (a nil value)
stack traceback:
	plugins/calibre.koplugin/search.lua:419: in function 'onReturn'
	frontend/ui/widget/menu.lua:820: in function 'callback'
	frontend/ui/widget/button.lua:409: in function 'handleEvent'
	frontend/ui/widget/container/inputcontainer.lua:261: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	...
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/widget/container/widgetcontainer.lua:82: in function 'propagateEvent'
	frontend/ui/widget/container/widgetcontainer.lua:100: in function 'handleEvent'
	frontend/ui/uimanager.lua:862: in function 'sendEvent'
	frontend/ui/uimanager.lua:51: in function '__default__'
	frontend/ui/uimanager.lua:1386: in function 'handleInputEvent'
	frontend/ui/uimanager.lua:1484: in function 'handleInput'
	frontend/ui/uimanager.lua:1531: in function 'run'
	./reader.lua:335: in main chunk
	[C]: at 0x00013f5d
Process has been terminated by signal {SIGSEGV::SEGV_MAPERR}
Segmentation fault
!!!!
Uh oh, something went awry... (Crash nÂ°1: 11/27/22 @ 08:51:02)
Attempting to restart KOReader . . .
!!!!
</details>

**Comment by pazos** [comment]
Indeed, it is a bug, introduced with the navigation feature, in https://github.com/koreader/koreader/pull/8869

Easy to fix. But the way to get out of the search results is not pressing that button (it should be disabled) but pressing the close button top right.
