### ISSUE TITLE
Dispatcher/gesture management shows sleep as an option on Android

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#9838]
* KOReader version: 2022.10-132
* Device: Android (Realme 7 Pro, Android 12)

#### Issue
Suspend isn't supported on Android, sleep shouldn't be available as an option.

Reported here: https://www.mobileread.com/forums/showthread.php?p=4276892#post4276892

#### Steps to reproduce
Taps & swipes → gesture manager → device

**Comment by pazos** [comment]
@Frenzie: is this one? https://github.com/koreader/koreader/blob/master/frontend/dispatcher.lua#L79

We should add a condition `Device:canSuspend`

**Comment by Frenzie** [comment]
I suspected it would be that simple. :-)
