### ISSUE TITLE
Android: USB OTG Keyboard mapping

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9840]
* KOReader version: 2022.10
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
I’d like to map keys for an USB OTG keyboard to use in KOReader’s Text editor.

Where should I start?

If possible, I’d like to have the remapping as a patch to keep them across updates. 

I found a few tickets starting in Android, but they have references to SDL, so now I am confused. 

Thanks!

**Comment by pazos** [comment]
https://github.com/koreader/koreader/wiki/Android-tips-and-tricks#customize-keys

**Comment by mergen3107** [comment]
Thank you @pazos ! 

Where can I find the full list of all keys? For example, for inputting a letter A, should I put “A”?

**Comment by NiLuJe** [comment]
That very question is answered in the link posted above ;).

You might also just be able to piggy-back on the ExternalKeyboard's plugin mapping (assuming Android doesn't mangle keycodes, as those are the X11 keycodes): https://github.com/koreader/koreader/blob/master/plugins/externalkeyboard.koplugin/event_map_keyboard.lua

**Comment by mergen3107** [comment]
Thanks @NiLuJe !

`That very question is answered in the link posted above ;).`
Is this about verbose logs?

**Comment by NiLuJe** [comment]
Yup, verbose debug logging outputs the key codes.

**Comment by mergen3107** [comment]
Thank you! And I found all the values I could put in the plugin.

**Comment by mergen3107** [comment]
I updated to current nightly. External keyboard plugin files are there, but the plugin doesn’t work because 1) Android key codes are different; and 2) something else is broken. 

For example, “Q” is reported in crash.log as 45. I created the event_map.lua file with `return [45] = “Q” }`, but it didn’t work. Am I doing something wrong here?

**Comment by NiLuJe** [comment]
The plugin is *not* designed for Android (in fact, I'm pretty sure it should auto-disable itself there), I was just linking to the mapping in the vague hope Android wasn't being a special snowflake (but, that was somewhat to be expected, given that it's not using X11).

**Comment by mergen3107** [comment]
OK! Thank you, I will try more

**Comment by pazos** [comment]
@mergen3107: see https://www.mobileread.com/forums/showthread.php?t=350459

**Comment by anilk714486-blip** [comment]
Hi
