### ISSUE TITLE
cloudstorage: folders not listed for some WebDAV servers

### ISSUE THREAD

**Issue by SteadyQuad** [koreader/koreader#9848]
* KOReader version: 2022.10 (and earlier)
* Device: Android

#### Issue
When listing the files and folders from a particular WebDAV server (TransIP), only the contained files are displayed, not the (sub)folders.

#### Steps to reproduce
Go to cloud storage, select configured WebDAV server, the list displays files, not folders. 

##### details

This WebDAV server returns folder items like this (`pocorgtfo` is the folder that is not shown in the list of files and folders in current 2022.10 version and earlier, `remote.php/webdav/` is part of the configured webdav address):

```
<d:href>/remote.php/webdav/pocorgtfo/</d:href><d:propstat>
    <d:prop>
        <d:resourcetype>
            <d:collection xmlns:d="DAV:" />
        </d:resourcetype>
    </d:prop>
    <d:status>HTTP/1.1 200 OK</d:status>
</d:propstat> 
```
Note that the `<d:collection>`  element has an attribute and whitespace. This attribute is the reason the folder is not currently detected by the relevant code in `webdavapi.lua`: where the regexp only mathes a `<d:collection>` element without attribute and whitespace:
 
https://github.com/koreader/koreader/blob/61364ffc3341f4ee7ff3de0816c4a8e176a4e470/frontend/apps/cloudstorage/webdavapi.lua#L136-L144

Fixed by making the regexp match less strict to allow for attributes and whitespace for `<d:collection>` elements:

I submitted [9847](https://github.com/koreader/koreader/pull/9847) for review.

**Comment by hius07** [comment]
Closed by https://github.com/koreader/koreader/pull/9847.
