### ISSUE TITLE
FR: Display text of the "subject" field in pdf files

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9855]
**Does your feature request involve difficulty completing a task? Please describe.**
In a pdf file, in the "Description" tab of the Properties, if we write a long text in the "Subject" field, in order to have a description of the book, not all the text is displayed in KoReader, but only the first words and various unintelligible symbols appear in place of the other words. Is this something that can be fixed?

Thank you!

**Comment by Frenzie** [comment]
Could you maybe create a PDF showing the problem? For example grab paper.pdf from https://github.com/koreader/test-data, add a description with the issue and attach it here for testing.

**Comment by ichnilatis-gr** [comment]
I give you a sample pdf in which I have put a long text the "Subject" field of the Properties. I also give you a screenshot of the Description window.

![FileManager_2022-12-03_115019 (Medium)](https://user-images.githubusercontent.com/76203123/205436459-34795dbf-c10f-4238-b36a-dddf80064e29.png)



[sample.pdf](https://github.com/koreader/koreader/files/10146169/sample.pdf)

**Comment by Frenzie** [comment]
Excellent! I tagged it MuPDF since there's a chance the issue will resolve itself thanks to @mroethke

In any case, with the PDF in place it'll be easy to check.

**Comment by mroethke** [comment]
Spoiler alert! It will not resolve itself.

But I looked into it (needed to do something fun for a change) and the fix is rather simple. Will create a PR with the fix shortly.

**Comment by poire-z** [comment]
Should have been fixed by https://github.com/koreader/koreader-base/pull/1558, bumped early December.
