### ISSUE TITLE
A UI error of layout switching

### ISSUE THREAD

**Issue by Liushu3** [koreader/koreader#9859]
Be expected to click the button, but the list reflects
https://user-images.githubusercontent.com/75210788/205421912-f9467776-12c0-4c85-8f76-f0d9ba16682c.mp4

**Comment by Frenzie** [comment]
I don't think I see anything unexpected on the video. Could you try to explain what you mean by reflecting?

**Comment by Liushu3** [comment]
![vlcsnap-2022-12-04-11h37m40s331](https://user-images.githubusercontent.com/75210788/205473084-21af2bee-ba75-4064-a353-b07ab850a054.png)
![vlcsnap-2022-12-04-11h37m44s571](https://user-images.githubusercontent.com/75210788/205473087-3f6b3791-e84a-4e07-b8df-3cfc396c5d61.png)
