### ISSUE TITLE
Current cache size:  -1630142464 B

### ISSUE THREAD

**Issue by gerhaher** [koreader/koreader#9860]
* KOReader version: 2022.11
* Device: Kobo Libra2

#### Issue
+10 000 books & Mosaic with cover images.

![InkedFileManager_2022-12-03_092007](https://user-images.githubusercontent.com/32645430/205432152-33ef6399-4022-4cea-a734-adf2f215b44d.jpg)

**Comment by Frenzie** [comment]
That's strange, I wonder if it could be an issue in lfs?

https://github.com/koreader/koreader/blob/fa9f0acf5e58dcc4f68d4effbdaefa795c6b67c4/plugins/coverbrowser.koplugin/bookinfomanager.lua#L149-L153
https://github.com/koreader/koreader/blob/fa9f0acf5e58dcc4f68d4effbdaefa795c6b67c4/frontend/util.lua#L1147-L1167

**Comment by NiLuJe** [comment]
lfs returns a `lua_Integer` (e.g., `ptrdiff_t`), and we then squash that into a Lua number, so there may verywell be an overflow somewhere since we don't have 64bits on precision available *anywhere*.

**Comment by Frenzie** [comment]
An overflow is an obvious thought, but could the cache size really be much larger than a few hundred MB?

**Comment by NiLuJe** [comment]
Err, true, plus, FAT32 means we can't blow past 2GB anyway, which would be the actual overflow threshold for INT32_MAX.

The fact that the size check in getFriendlySize appears to point to the "bytes" branch is doubly weird, and probably points at the overflow happening either directly in lfs during the lua_Integer push, or in the `tonumber` cast?

**Comment by gerhaher** [comment]
> What's the _actual_ size of the db as returned by `stat`?

Where can I see this info?

**Comment by Frenzie** [comment]
I think it's the settings/bookinfo_cache.sqlite3 file.

**Comment by gerhaher** [comment]
OK, that file is 2 674 468 kB.

**Comment by Frenzie** [comment]
In that case I take back what I said, although I thought Lua numbers were closer to 64-bit regardless of architecture.

**Comment by NiLuJe** [comment]
Yup, that'll overflow the lua_Integer cast on 32-bit arches.

**Comment by NiLuJe** [comment]
I mean, we *could* just add `0x0100000000` to the value returned by lfs if it's negative (as, yeah, lua_Number is wider than lua_Integer), but that verges on undefined behavior ;p.

**Comment by NiLuJe** [comment]
Or, better yet, fix lfs to use `lua_pushnumber` instead of `lua_pushinteger` ;).

**Comment by NiLuJe** [comment]
> I mean, we _could_ just add `0x0100000000` to the value returned by lfs if it's negative (as, yeah, lua_Number is wider than lua_Integer), but that verges on undefined behavior ;p.

Well, maybe not so crazy after all...

https://github.com/coreutils/coreutils/blob/aaa306ad76d48b27efd75101d57b6ec5bf90362c/src/stat.c#L1498-L1502

**Comment by NiLuJe** [comment]
See also https://git.busybox.net/busybox/tree/coreutils/stat.c ;).

I'll push an lfs patch to see how it fares first, as it should be slightly less intrusive, ironically ;).

**Comment by NiLuJe** [comment]
Namely,

```diff
diff --git a/src/lfs.c b/src/lfs.c
index e5e5ee4..150396e 100644
--- a/src/lfs.c
+++ b/src/lfs.c
@@ -29,6 +29,7 @@
 #include <stdio.h>
 #include <string.h>
 #include <stdlib.h>
+#include <inttypes.h>
 #include <time.h>
 #include <sys/stat.h>
 
@@ -830,74 +831,74 @@ static void push_st_mode(lua_State * L, STAT_STRUCT * info)
 /* device inode resides on */
 static void push_st_dev(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_dev);
+  lua_pushnumber(L, (uintmax_t) info->st_dev);
 }
 
 /* inode's number */
 static void push_st_ino(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_ino);
+  lua_pushnumber(L, (uintmax_t) info->st_ino);
 }
 
 /* number of hard links to the file */
 static void push_st_nlink(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_nlink);
+  lua_pushnumber(L, (unsigned long) info->st_nlink);
 }
 
 /* user-id of owner */
 static void push_st_uid(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_uid);
+  lua_pushnumber(L, (unsigned long) info->st_uid);
 }
 
 /* group-id of owner */
 static void push_st_gid(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_gid);
+  lua_pushnumber(L, (unsigned long) info->st_gid);
 }
 
 /* device type, for special file inode */
 static void push_st_rdev(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_rdev);
+  lua_pushnumber(L, (unsigned long) info->st_rdev);
 }
 
 /* time of last access */
 static void push_st_atime(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_atime);
+  lua_pushnumber(L, (long) info->st_atime);
 }
 
 /* time of last data modification */
 static void push_st_mtime(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_mtime);
+  lua_pushnumber(L, (long) info->st_mtime);
 }
 
 /* time of last file status change */
 static void push_st_ctime(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_ctime);
+  lua_pushnumber(L, (long) info->st_ctime);
 }
 
 /* file size, in bytes */
 static void push_st_size(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_size);
+  lua_pushnumber(L, (uintmax_t) info->st_size);
 }
 
 #ifndef _WIN32
 /* blocks allocated for file */
 static void push_st_blocks(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_blocks);
+  lua_pushnumber(L, (uintmax_t) info->st_blocks);
 }
 
 /* optimal file system I/O blocksize */
 static void push_st_blksize(lua_State * L, STAT_STRUCT * info)
 {
-  lua_pushinteger(L, (lua_Integer) info->st_blksize);
+  lua_pushnumber(L, (unsigned long) info->st_blksize);
 }
 #endif
```

(casts stolen^Wheavily inspired from busybox, but basically the `uintmax_t` ones are are all the types with a `64` variants).

**Comment by NiLuJe** [comment]
I was mistaken earlier, the FAT32 limit is actually 4GB, but the Lua_Integer overflow happens at 2GB, which explains the fact that we're seeing this at all ;).

**Comment by Frenzie** [comment]
In that case I was running into the 4 GB limit in '04 or '05, making my remark all the more relevant. ;-P
