### ISSUE TITLE
New reading statistics cloud sync does not work

### ISSUE THREAD

**Issue by theboomr** [koreader/koreader#9861]
* KOReader version: 2022.11
* Device: Kobo Forma (and Samsung Galaxy S10e Android phone)

#### Issue
I've just finally got DropBox set up correctly (which was a whole other ordeal, but figured it out in the end), and I can successfully open it and navigate through my DropBox folders with no issues. But after setting the Reading Statistics to a particular directory in my DropBox, when I try to hit the "Synchronize now" button, it throws an error: "Something went wrong when syncing, please check your network connection and try again later."

I've attached crash.log from my Forma with verbose debug logging enabled at the bottom. I notice "DropBoxApi: Download failure: HTTP/1.1 401 Unauthorized" on line 11304, but not sure how to diagnose anything further. This exact same behavior also happens on my phone, so I imagine it's somewhat likely I'm just doing something wrong somewhere, but I'm not sure what. I didn't grab any logs from my phone.

#### Steps to reproduce
1. Have DropBox set up correctly
2. Select a DropBox folder within Reading statistics > Settings > Cloud sync
3. Tap the "Synchronize now" option in Reading statistics
4. Error pops up

##### [crash.log](https://github.com/koreader/koreader/files/10146112/crash.log)

**Comment by hius07** [comment]
I am not familiar to the syncservice module but it seems it tries to use the long-lived token.
@weijiuqiao

**Comment by weijiuqiao** [comment]
Yes, looks like it. I was using the download and upload methods from dropboxapi.lua and overlooked the token stuff.
Do we generate a token at some good timing or do we try to connect first then generate one if the error suggests so?

**Comment by hius07** [comment]
In the CloudStorage interface the short-lived token is always generated once in the beginning of every session, not waiting for the error.
Maybe it is not the best practice but tokens live 4 hours only and getting the new one is cheap.

**Comment by hius07** [comment]
"Session" - I mean opening the Dropbox storage. While we are staying in it, all operations use the same token.

**Comment by weijiuqiao** [comment]
Then it looks to me the easiest solution is to generate a token each time when syncing, since it's cheap and the operation is not so frequent. 
Let me do a PR and I'll need your review :)

**Comment by theboomr** [comment]
Thank you so much for figuring out my issue! Looking forward to this being implemented in a future release!
