### ISSUE TITLE
FR: Disable screensaver

### ISSUE THREAD

**Issue by fekir** [koreader/koreader#9868]
**Does your feature request involve difficulty completing a task? Please describe.**

With a Kindle, I have to exit KOReader for disabling the screensaver, click on the touch bar, and type `~ds`.
KOReader has already different settings for the screensaver, it makes sense that being able to disable it is part of those settings.

**Describe the solution you'd like**
Under Screensaver, maybe after "Leave screen as is" a setting (checkbox) for disabling the screensaver, or the possibility to set a timeout, and make it possible to set values to denote infinity (-1 maybe?)

**Describe alternatives you've considered**
I am not aware of any alternatives except for exiting KOReader, disable the screensaver and the re-execute KOReader.

**Additional context**
I have a "Kindle Touch", so the behavior might differ on other devices.

I want like to disable the screensaver especially when the KOReader is configured to turn pages automatically.
Unfortunately the solution with `~ds` does not persist reboots, thus I have to re-apply it every time.

If KOReader would be able to change the setting persistently, it would be the optimal solution.
If this is not possible, but KOReader can apply the change automatically when started, it would still be great.
If this is also not desired, being still able to apply the setting manually without exiting KOReader would be much appreciated (and much more practical than exiting the app, using the Kindle Keyboard and the non-intuitive shortcut).

**Comment by Frenzie** [comment]
That won't be possible. See https://github.com/koreader/koreader/issues/9866#issuecomment-1336328015

**Comment by hius07** [comment]
Look at the "Keep alive" plugin.

**Comment by fekir** [comment]
@Frenzie I do not se how https://github.com/koreader/koreader/issues/9866#issuecomment-1336328015 clarifies why it is not possible, mine is not a device with ads, adn with `~ds` the screensaver is disabled.

@hius07 I have the keep alive plugin, I need to retest because as far as I remember it did not make any difference....

**Comment by Frenzie** [comment]
I slightly misread the OP. You're saying the Kindle system has an autosuspend/screensaver that activates even when not triggered by KOReader?

**Comment by NiLuJe** [comment]
Braindump: I don't remember how ~ds works exactly, but there *is* a touchScreenSaver (or something to that effect) lipc prop that will re-arm the t1 timer. We could potentially fire that ourselves periodically (say, every t1 - 30s) to make sure the only thing that ever trips suspend is AutoSuspend. (xref: to the open AutoSuspend issue about that that I can't quite find rn ;D).

**Comment by durantian** [comment]
While, I hope I could set "Calendar view" as screensaver but I can't. 
I could use reading progress as screensaver now, but it just shows a week progress.

**Comment by fekir** [comment]
Sorry for the late reply, had to reboot the kindle multiple times before the `~ds` was not active anymore

@Frenzie 
> You're saying the Kindle system has an autosuspend/screensaver that activates even when not triggered by KOReader?

yes (unfortunately)


@NiLuJe 

> What's are actual KOReader ScreenSaver settings?

Keep alive is listed as activated under plugin, under screensaver:

 - [ ] Use last book's cover as screensaver
 - [ ] use book random image from folder as screensaver
 - [ ] use document cover as screensaver
 - [ ] use image as screensaver
 - [ ] use reading progress as screensaver
 - [x] leave screen as it is
 - [x] add message to screensaver

Screensaver message is "test test", and I do not see this message when the screensaver activates.

**Comment by NiLuJe** [comment]
> (xref: to the open AutoSuspend issue about that that I can't quite find rn ;D).

#7874 ;).
