### ISSUE TITLE
Update not successfull; strange message

### ISSUE THREAD

**Issue by zwmn-beep** [koreader/koreader#9875]
* KOReader version: v2022.11 something
* Device: Kobo Sage

#### Issue
An update shows the following message (in German sorry, but I don't know how to provoke the same thing in English)
![grafik](https://user-images.githubusercontent.com/36999612/205743779-a8d5586b-32b6-431d-a40a-a96fa439123b.png)

#### Steps to reproduce
Start update process and get surprised.

##### Description
I got this strange message on updating already some times ago. But now, as I don't want to spend any more time into developing for KOReader, I just send this to you, without any investigations. Maybe you can fix the issue. 

1. The message itself is a bit weird (what means `Abbrechen` on the left side and `Abbrechen` on the right side)?. Maybe it's just a translation thing (in this case the context might got lost?). Anyway if I get such a message, I will delete the app and never install it again.

2. Finally, I got the update (but I can't recall what I did. First I tapped right or was it left. Called another update process. The same thing again. .... I would say this is an awfully mess, someone should fix that soon. For a newcomer this behavior is :-1: )
If I had not spent so much time to that program I would have deleted it at this point.

(I am neither capable nor interested of fixing that.)

((If someone wants to be nasty, he could say this issue is more important than what the date format on a tap on a time looks like. I won't be nasty, this comment will be my last emotional comment you get.))

(((Please allow me a very last friendly remark: I am happy that in the future I don't have to argue about, if a fucking weird unicode U+2212 in a text is the problem of some fucking publisher. The publisher won't even notice what we write and think here (and the time spent here) nor does the publisher notice the outcome of the discussion. If I would want to improve an eBook reader software, I would ask: What are the publishers are doing wrong, and how can I fix this? Similar to the style tweaks, which are awesome. And as a teacher I could correct the publishers; good luck with that.)))

((((Bye over and end here; I will stay tuned and maybe I'll be back in a few months))))

**Comment by zwim** [comment]
Just edited the initial issue, as github was upset about my formulations.

**Comment by zwim** [comment]
@koreader I forgot to mention: Please can you remove me as a member the KOReader community on github? I won't  contribute anything here in the future.

**Comment by NiLuJe** [comment]
That's probably https://github.com/koreader/koreader/blob/b9473fa6004a8e936c3a8ef96ddeea449b97dd1e/frontend/ui/otamanager.lua#L292-L333, so, yeah, TL looks wonky.

The only way I've ever been able to replicate this since the move to zsync2 is if the currently installed version is a custom build. That seems to upset zsync... somehow.
Although in that case the zsync report does show up and says something I can't quite recall.

The main issue is that the retry from scratch (IIRC, the rightmost button) will *also* fail because, and that's... a weird zsync2 quirk that I haven't had a chance to look into.

**Comment by Frenzie** [comment]
@zwim Done. :-/ (There's no obligation to contribute anything.)

**Comment by pazos** [comment]
> If I had not spent so much time to that program I would have deleted it at this point.

If that's what you feel I would strongly suggest to do so.

The time you spent on the program is either upstream or in your brain. That time isn't lost even if you delete this piece of software and move on with your life. This program is just a hobby and your Kobo is more than capable of providing a good reading environment even without KO.

You deserve vacations :) . Find if the program is valuable for you beyond tweaking & fixing it.

And if/when you come back please spent most of the time using it, not improving it. Each one of us is different. My own sanity ratio is 20/1 as user/contributor.

**Comment by pazos** [comment]
> The only way I've ever been able to replicate this since the move to zsync2 is if the currently installed version is a custom build

Exactly the same here. No problems updating from official packages in the last 3 or 4 years, IIRC. The only ones happened with custom builds on my cervantes bumping to the next nightly, where something I've just contributed goes upstream.

As @NiLuJe said, once I found that message retrying didn't work and the solution was to uncompress the zip file overwritting legacy files.

**Comment by NiLuJe** [comment]
I could have sworn the empty seed file case was something I tested extensively while working on the zsync2 port, but apparently not ;o).

Anyway, I'll look into it when/if I update zsync2 (it's... a bit of a mess, as there's a few extra dependencies upstream, and even more fun CMake crap to deal with ;p).
