### ISSUE TITLE
OPDS Catalog

### ISSUE THREAD

**Issue by pyromaker** [koreader/koreader#9879]
Hi.

After the last update when I click to OPDS Catalog -> Local calibre library I get the message "Cannot get catalog info from nil"

**Comment by hius07** [comment]
Long press the "Local calibre library" item. Do you see your server details?

**Comment by KenMaltby** [comment]
I found that the IP address from caliber was changing unexpectedly.  If you check the server in caliber, you can do the long press mentioned, in Koreader, and use the edit option to enter the new IP address.  

Luck;
   Ken

**Comment by pyromaker** [comment]
Oh yes sorry I forgot that I edited the server properties in the past. Thank you

**Comment by ewilan-riviere** [comment]
I've built a package to manage my application's OPDS feeds and if someone has same bug, here a solution:

This link trigger error `cannot get catalog info from nil`:

```html
<link rel="start" href="https://domain.com/opds/latest" type="application/atom+xml;profile=opds-catalog;kind=navigation" title="Latest" />
```

This link works fine:

```html
<link href="https://domain.com/opds/latest" type="application/atom+xml;profile=opds-catalog;kind=navigation" />
```

Just because `rel="start"` is not a valid OPDS link navigation.

**Comment by NiLuJe** [comment]
See also #10871
