### ISSUE TITLE
AutoStandby: Kobo Sage buttons work unreliably

### ISSUE THREAD

**Issue by charlesangus** [koreader/koreader#9882]
* KOReader version: 2022.08
* Device: Kobo Sage

#### Issue

When in standby, the page-turn buttons work most of the time, but occasionally only un-suspend the device without turning the page (visible by the clock updating but the page not turning).

This bug is likely not directly in KoReader, as the stock Kobo reader app has the same issue, but perhaps there is a workaround which could get the buttons working reliably in KoReader. The buttons do work reliably in KoReader when AutoSuspend is off.

#### Steps to reproduce

Enable autostandby, begin reading. Wait for it to standby, then turn the page. Repeat until the page turn button doesn't register.

**Comment by NiLuJe** [comment]
It's a kernel issue on the sunxi SoCs, not much we can do about.

On the upside, I haven't been able to reproduce it on my end since #9569, so do try with an up-to-date version ;).

**Comment by NiLuJe** [comment]
Sidebar: you're talking about auto**standby**, not suspend ;).

**Comment by charlesangus** [comment]
One workaround I considered which I thought I'd throw out there was some kind of key repeat limit option. I personally never hold the button down to turn multiple pages, so it would fix the issue (for me) to just hold the button just long enough to register multiple key presses but only turn the page once.

**Comment by charlesangus** [comment]
I'll try with the latest version of everything and see if it's improved, too :)

**Comment by NiLuJe** [comment]
There's nothing to repeat as the kernel just drops the input event into the
void ;).

**Comment by charlesangus** [comment]
Sorry, I wasn't clear - unless I'm mistaken, holding the button down will
reliably wake up the service and turn the page (repeatedly).

I'm suggesting an option to turn off repeated page turns - not an option to
send repeated turns. Just a thought.

**Comment by NiLuJe** [comment]
That would depend on what the kernel sends us in this instance, as I've never witnessed it myself (and I probably won't ever again, given that I can't repro anymore ;p).

**Comment by charlesangus** [comment]
With a new device and latest software, I can't repro this anymore either so closing the issue, thanks for the quick replies!
