### ISSUE TITLE
[Kobo Clara 2E] Consistently broken setup

### ISSUE THREAD

**Issue by ezuk** [koreader/koreader#9885]
* KOReader version: 2022.11
* Device: Kobo Clara 2E

#### Issue

I'm installing KOReader using the Mac installer and latest zip from the [official thread](https://www.mobileread.com/forums/showthread.php?t=314220). I've previously installed on a Libra H2O and it worked well.

So far I've had the following issues:

1. First install: Constant crashes. Fixed by deleting cache/fontinfo.dat.
2. Then I realized the install was still broken: Gesture Manager did not show up. Reading around, the advise was to install again, so I did.
3. Second install: Glyphs broken for the menus. Wherever there should be a glyph, there's just a checkerboard pattern. Gesture Manager still missing.

This seems device-specific. Any advice?

Many thanks for all of your hard work on KOReader — it does indeed rock, and I miss it! ❤️

**Comment by NiLuJe** [comment]
3. very much sounds like Nickel having deleted the icons because the hidden directory ban didn't take the first time around, FWIW.

**Comment by ezuk** [comment]
An update on this issue after a few weeks: I'm still getting random freezes while reading on the 2E. 

I just read my book, flipping a page every few moments, when all of a sudden the next page won't flip and I discover that the device froze sometime during the last few minutes.

**Comment by ezuk** [comment]
Reading further, this feels like a dupe of #9806. I think we can close this one and focus there. I'm experiencing exactly the freezes described there.
