### ISSUE TITLE
Exit after unable to find last file

### ISSUE THREAD

**Issue by Frenzie** [koreader/koreader#9887]
* KOReader version: master
* Device: emulator

#### Issue
The program automatically exits shortly after showing the file browser.

#### Steps to reproduce
1. Set open with last file
2. Open some file and delete it (or edit the saved settings file)
3. Start the program, see "Cannot open last file."
4. Click cancel.

I don't think it used to do this, but I don't have time to test old AppImages atm.

I believe this may have been recently reported by @Biep, but I can't find it.

**Comment by NiLuJe** [comment]
I assume it quits via https://github.com/koreader/koreader/blob/e026598f728196cd2747d255e0cdc6194d0340ce/frontend/ui/uimanager.lua#L1420-L1426 ?

I'll take a look at it ;).

**Comment by Frenzie** [comment]
Nope, that it does not.

**Comment by NiLuJe** [comment]
Well, that was gnarly. It's a bit of a miracle that this ever worked before, actually ;p.
