### ISSUE TITLE
Can't open Today's timeline

### ISSUE THREAD

**Issue by frozencircle** [koreader/koreader#9892]
* KOReader version: 2022.11-19
* Device: Kobo Libra H2O, Android

#### Issue
On Kobo Libra, Today's timeline couldn't be opened from mene, quickmenu or gesture, but could be accessed from Calender view. 
On Android, even open a day from Calender view lead to crash.
Version 2022.11 stable was fine btw. 
#### Steps to reproduce
- Open Today's timeline from menu, gesture -> nothing happened (no crash).
- On Kobo Libra: open Calender view -> open a day -> no crash
- On Android: open Calender view -> open a day -> crash

**Comment by poire-z** [comment]
Can reproduce. It's a side effect of 192a243b, and CalendarView still getting passed longDayOfWeekTranslation from its parent (the statistics plugin)  - but we moved them in datetime.

Or may be just a forgotten renaming. This solves it:
```diff
--- a/plugins/statistics.koplugin/main.lua
+++ b/plugins/statistics.koplugin/main.lua
@@ -2580,7 +2580,7 @@ function ReaderStatistics:onShowCalendarDayView()
     local title_callback = function(this)
         local day = os.date("%Y-%m-%d", this.day_ts + 10800) -- use 03:00 to determine date (summer time change)
         local date = os.date("*t", this.day_ts + 10800)
-        return string.format("%s (%s)", day, datetime.longDayOfWeekTranslation[CalendarView.weekdays[date.wday]])
+        return string.format("%s (%s)", day, datetime.shortDayOfWeekToLongTranslation[CalendarView.weekdays[date.wday]])
     end
     CalendarView:showCalendarDayView(self, title_callback)
 end
```
But I think the passing described above should be cleaned, now that the names are in datetime and accessible directly by both modules.

Will see to that later today.

**Comment by poire-z** [comment]
(But I can't reproduce the crash on my Android phone.)

**Comment by poire-z** [comment]
While I'm at it, is there a better format (non localized) for this day.month `%d.%m` ?:
![image](https://user-images.githubusercontent.com/24273478/206858259-68151a6c-e00c-4c03-9d48-d3e867d41630.png)

`date_format_show = datetime.shortDayOfWeekToLongTranslation[os.date("%a", diff_time)] .. os.date(" (%d.%m)", diff_time)`

In French, I'd be just fine with %d/%m, ie. `07/12`, as it happens it's just how we want date.
But I guess in English, people wants `12/07` `%m/%d` - so it's strange it's not in this format.

**Comment by Frenzie** [comment]
You could add it to the new DateTime module if you want, but for the moment I'm happy with the state it's in and I'd prefer not to touch it (unless there's a bug). :laughing:

**Comment by NiLuJe** [comment]
We should [*probably*](https://docs.oracle.com/cd/E19455-01/806-0169/overview-7/index.html) make that localized, though?

**Comment by Frenzie** [comment]
Had we but world enough and time…
