### ISSUE TITLE
FR: Develop armeabi64-v8a version

### ISSUE THREAD

**Issue by xmha97** [koreader/koreader#9894]
Please develop a version for armeabi64-v8a

![Screenshot_2022-12-10-22-09-08-336_com.absinthe.libchecker-edit.jpg](https://user-images.githubusercontent.com/23485114/206870423-fddd2ade-3ba1-4071-9040-bd5f448d7c82.jpg)

**Comment by xmha97** [comment]
Why did you close this issue?
(I am using the latest version)

**Comment by Frenzie** [comment]
It should be coming in the next F-Droid release already. :)
