### ISSUE TITLE
FR: Add "edit bookmark text" option

### ISSUE THREAD

**Issue by ichnilatis-gr** [koreader/koreader#9900]
**Does your feature request involve difficulty completing a task? Please describe.**
I'd like to repeat once again (and sorry if I'm being tedious) an [earlier request](https://github.com/koreader/koreader/issues/8535#issuecomment-992271420) about a bookmark text editing feature.
I've given some ideas and explanations [here ](https://github.com/koreader/koreader/issues/8535#issuecomment-999681237)and [here](https://github.com/koreader/koreader/issues/5794#issuecomment-1008032154).
With this option we could make changes/additions etc. to a bookmark text without it appearing as a note and without it being displayed twice (without and with changes, i.e. as original text and as note) in the exported file. It will be displayed only with the changes.
However it's not just about the result after exporting; there may be an addition/correction to the original highlighted text (which in a pdf may not be correctly recognised) to which we may want to add a note.

Thank you for your patience and help.

**Comment by ichnilatis-gr** [comment]
Dear @hius07 what do you think about this?

**Comment by hius07** [comment]
I think it is technically feasible. It can be useful for correcting OCR errors.

**Comment by ichnilatis-gr** [comment]
Is there any hope for this issue?
Dear @hius07, @uroybd, @poire-z and anyone else, what do you think?

Thanks!

**Comment by ichnilatis-gr** [comment]
> I think it is technically feasible. It can be useful for correcting OCR errors.

Dear @hius07 could you perhaps do something about this? I don't see any response from anyone else...

**Comment by poire-z** [comment]
My response would be the same as my previous one https://github.com/koreader/koreader/issues/5794#issuecomment-1020378935.
I have not given it more thoughts, but if we were to really modify the source text, we at least need to add a flag to the highlight/bookmark item, so we know later we can't trust the source text to find the original position if ever needed.
(And we would need some not-super-intrusive UI - as it's really use case specific - to show/edit the source text.)

**Comment by ichnilatis-gr** [comment]
Please consider that OCR is not as perfect as in English. Most of the pdf books I read are in polytonic Greek and I can hardly find a good OCR for them. So in many cases, when I highlight a text, it is not rendered correctly in the bookmarks table and if I just want to read my bookmarks,  I have to tap on each one every time and go to the original text.
Even Pocketbook has added this feature. So since, as @hius07 said, it is not difficult to add this feature, I would implore you to add it. I believe the same problem is faced by readers with other languages that don't have very good OCR.

Thank you for your understanding.
