### ISSUE TITLE
Post-screensaver "Wait for gesture" doesn't accept gestures if "Book progress" or "Book status" are the screensaver types

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#9911]
* KOReader version: 2022.11
* Device: Kindle PW5

#### Issue
Can't enter your gesture to dismiss screensaver. Nothing happens.

#### Steps to reproduce
Set "Reading progress" or "Book status" as screensaver. Set "Wait for gesture" as your screensaver delay. Bam

##### `crash.log` (if applicable)
<details>
  <summary>crash.log</summary>

```
12/13/22-01:37:04 INFO  Inhibiting user input 
12/13/22-01:37:06 INFO  Restoring user input handling 
12/13/22-01:37:20 INFO  Inhibiting user input 
12/13/22-01:37:24 INFO  Restoring user input handling 
12/13/22-01:37:39 INFO  Inhibiting user input 
12/13/22-01:37:41 INFO  Restoring user input handling 
12/13/22-01:39:41 INFO  Inhibiting user input 
12/13/22-01:39:43 INFO  Restoring user input handling
```
</details>

i.e. not much

**Comment by NiLuJe** [comment]
They're both subclasses of InputContainer, so they're probably messing with the ges_events switcheroo done in ScreenSaverWidget...
