### ISSUE TITLE
ui/widget/logindialog BUG on non-touch device

### ISSUE THREAD

**Issue by boypt** [koreader/koreader#9913]
* KOReader version: 2022.11
* Device: Kindle 3 Keyboard

#### Issue
kosync login dialog can not enter password, or refocus on any of the input fields.

#### Steps to reproduce

- Enter kosync plugin (progress sync)
- Register / Login
- Input username (or not)
- CAN NOT enter password, when  press 'BACK', the input wiget lose focus and can never regain focus.

#### Analyze

The kosync plugin is using `ui/widget/logindialog` widget as the input dialog.  

while OPDS plugin is working fine to input multiple value, is using the `ui/widget/multiinputdialog` widget.

I believe these two file code can be viewd as reference.

https://github.com/koreader/koreader/blob/7783d9c8e37099fa2e138d660dc76ed4ec5257ca/frontend/ui/widget/logindialog.lua

https://github.com/koreader/koreader/blob/7783d9c8e37099fa2e138d660dc76ed4ec5257ca/frontend/ui/widget/multiinputdialog.lua

**Comment by hius07** [comment]
There are no reasons to have a separate widget for login, MultiInputDialog can do it.

**Comment by NiLuJe** [comment]
That's what I was wondering after a very very quick glance at both, thanks ;).
