### ISSUE TITLE
Opening djvu document breaks file sorting

### ISSUE THREAD

**Issue by hius07** [koreader/koreader#9918]
**Device**: Kindle Voyage
**Steps to reproduce**:
In file browser select Sort by: filename
Open any djvu document
Close the document
Sorting is broken

In my investigation (limited to the lua modules) I've stopped at finding that after opening a djvu document
https://github.com/koreader/koreader/blob/6f39f6cb7b45a55dd956762f650f51a7feaaf0ee/frontend/document/djvudocument.lua#L37

 `C.strcoll` is broken and returns 0 for any str1 and str2
https://github.com/koreader/koreader-base/blob/master/ffi/util.lua#L120

**Comment by NiLuJe** [comment]
There are a *few* spurious `setlocale` calls in djvulibre that *could* potentially screw with `strcoll` indeed...

(Locales are a mess in POSIX).

**Comment by hius07** [comment]
Latest nightly 2022.11-50.
Unfortunately Sort by: filename is still broken after opening any djvu document.

Is `a.name < b.name` so slow that `ffiUtil.strcoll(a.name, b.name)` is required?

**Comment by NiLuJe** [comment]
base hasn't been bumped, so this isn't in any nightly yet ;).

Why e attempt to use strcoll in the first place is a... good question, though ;). It possibly generates less garbage, is the best I can come up with without looking into it ;).

**Comment by poire-z** [comment]
> base hasn't been bumped, so this isn't in any nightly yet ;).

Is it now ? Has it solved this ?

**Comment by hius07** [comment]
It is fixed, thanks!

**Comment by NiLuJe** [comment]
Yay for wild-ass shot in the darks actually panning out :D.
