### ISSUE TITLE
PDF rendering: unexpected image inversion

### ISSUE THREAD

**Issue by LiuShu3** [koreader/koreader#9927]
PDF渲染问题：意外的图片反色
![screenshot](https://user-images.githubusercontent.com/75210788/208279042-63304c3c-48d7-48bc-8f23-8c5089fc15d3.png)
[科学 九年级下册.pdf](https://github.com/koreader/koreader/files/10253117/default.pdf)

**Comment by NiLuJe** [comment]
Quite likely a duplicate of #5422 ;).

**Comment by Liushu3** [comment]
> Quite likely a duplicate of #5422 ;).
MuPDF said “warning: ICC support is not available”
