### ISSUE TITLE
Indent menu entries

### ISSUE THREAD

**Issue by zwim** [koreader/koreader#9947]
I would like to indent some menu entries (esp. after a disabled hint menu entry)  to demonstrate  / make clear, that the following entries apply to the (disabled) entry above.

But I don't know how to do that right (BIDI, LR ...). In German I would add two or four spaces at the beginning of the entry. But is this (adding spaces) also good in all languages?

![grafik](https://user-images.githubusercontent.com/36999612/209452856-e9c544f2-6d1b-4ed5-91e0-2a3dab958891.png)

**Comment by Frenzie** [comment]
We'll have to ask @weijiuqiao but I think that should be fine.

**Comment by weijiuqiao** [comment]
>I think that should be fine.

I think so, too :) Since space should be in the first of the fallback fonts, the width of the indent should be consistent in all languages. As to Bidi, I wound test under a LR language to be sure.
