### ISSUE TITLE
Incorrect translation on bookmark text

### ISSUE THREAD

**Issue by sonix-github** [koreader/koreader#9950]
* KOReader version: v2022.11-43-g6f39f6cb_2022-12-15
* Device: PB626

#### Issue
Automatically generated text on bookmark creation is not translated.

![bookmark_translation_issue_highlight](https://user-images.githubusercontent.com/29783895/209464657-cb0ac814-1cde-4c38-a067-ff885fb7ef4b.png)

#### Steps to reproduce
1. change UI language e.g. to Slovak
2. open some PDF document
3. add bookmark to some page
4. the bookmark text contains untranslated word "page"

It seems that it can be related to bookmark text generated for "chapter" or "notes". This is also visible in .sdr metadata detail below:
<details>
  <summary>quote from metadata.pdf.lua</summary>

```
    ["bookmarks"] = {
        [1] = {
            ["text"] = "Strana 216 na page 216 @ 2022-12-25 11:12:49",
            ["notes"] = "na page 216",
            ["datetime"] = "2022-12-25 11:12:49",
            ["chapter"] = "page 216",
            ["page"] = 216,
        },
        [2] = {
            ["text"] = "Strana 210 na page 210 @ 2022-12-24 22:58:18",
            ["notes"] = "na page 210",
            ["datetime"] = "2022-12-24 22:58:18",
            ["chapter"] = "page 210",
            ["page"] = 210,
        },
        [3] = {
            ["text"] = "Strana 109 na page 109 @ 2022-12-23 21:37:49",
            ["notes"] = "na page 109",
            ["datetime"] = "2022-12-23 21:37:49",
            ["chapter"] = "page 109",
            ["page"] = 109,
        },
    }, 
```
</details>

**Comment by hius07** [comment]
It's by design. Please see https://github.com/koreader/koreader/pull/8301#issuecomment-939263497 and around.

**Comment by sonix-github** [comment]
> It's by design. Please see [#8301 (comment)](https://github.com/koreader/koreader/pull/8301#issuecomment-939263497) and around.

Thanks @hius07 for [#8301 (comment)](https://github.com/koreader/koreader/pull/8301#issuecomment-939263497) I have read it, but I have not found where is mentioned why it generates automatically "notes" in without translation when i add page bookmark (without any highlight in document). Could you please clarify it? Thanks

**Comment by hius07** [comment]
It seems that in your example "page 216" is the name of a chapter. What do you see in ToC?

**Comment by sonix-github** [comment]
> It seems that in your example "page 216" is the name of a chapter. What do you see in ToC?

Ohh, you are right. In ToC are all chapters with this (page XXX) "names". So now it is all clear. Thanks @hius07 for your patience and clarification.

**Comment by hius07** [comment]
You're welcome!
