### ISSUE TITLE
FR: Change UI Font (Android)

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9951]
Platform: Android 

Hi! Merry Christmas!

Can the UI fonts of KOReader be changed?

**Comment by mergen3107** [comment]
So I was able to forcefully replace the Noto Sans font in the data folder of KOReader, but I know this is not the best idea and they will be overwritten next update. 

Can I do a user patch to replace the system font location?

**Comment by belanger** [comment]
This would be nice.   Currently, with every new release, I have to change the fonts in the various files and repack the apk, it'd be nice if I didn't have to do that.

**Comment by mergen3107** [comment]
Yay! I am not alone in this endeavor :D

**Comment by NiLuJe** [comment]
You might be able to userpatch the fontmap:

https://github.com/koreader/koreader/blob/d6ec1485488ebeb48e46347c8d198849f8fe57ab/frontend/ui/font.lua#L40-L84

This is possibly more viable on Android than just appending a custom fontmap to your settings file manually, which is the "official" way to do that:

https://github.com/koreader/koreader/blob/d6ec1485488ebeb48e46347c8d198849f8fe57ab/reader.lua#L205-L212

**Comment by poire-z** [comment]
It's always fun to hack a user patch, so here's one: [2-font-override.lua.txt](https://github.com/koreader/koreader/files/10324860/2-font-override.lua.txt)

**koreader/patches/2-font-override.lua**
```lua
local Font = require("ui/font")
for k, v in pairs(Font.fontmap) do
    if v == "NotoSans-Regular.ttf" then
        Font.fontmap[k] = "Bitter-Regular.otf" -- change to your preferred font
    elseif v == "NotoSans-Bold.ttf" then
        Font.fontmap[k] = "Bitter-Bold.otf"    -- change to your preferred font
    end
end
```

**Comment by mergen3107** [comment]
Thank you!! I’ll try it

**Comment by mergen3107** [comment]
@poire-z 
Thank you very much! Works like a charm :)

**Comment by sebdelsol** [comment]
And it doesn't work anymore.

**Comment by sebdelsol** [comment]
Here's a [user patch](https://github.com/sebdelsol/KOReader.patches/blob/main/2--ui-font.lua) which _allows changing the UI font **through menus**_, and temporary fix #13925 

<img src="https://github.com/user-attachments/assets/afb782db-f9fc-4e8b-9120-d2da5b50735f" width=50%>

**Comment by emes81** [comment]
Thank you! Works great on desktop; I get an error "! Error applying patch ./patches/2--ui-font.lua" on Kobo Clara BW, anything I can do to help troubleshoot?
Desktop and Kobo both running KOReader 2025.04

**Comment by mergen3107** [comment]
Please share what font you are trying to use and how you refer to it. 

Also, do you actually have the font copied on Kobo?

Also please provide a clean log (crash.log file in koreader folder) which contains logs after KOReader starts. It has information on what fonts are accepted or rejected, so if KOReader didn't like a font for some reason, the patch won't be able to use it.

**Comment by emes81** [comment]
I never got to the point of trying to select a new font for the UI, the plugin didn't execute at all ("! Error applying patch ./patches/2--ui-font.lua"). I've updated KOReader to 2025.08, reinstalled the plugin, and pared back fonts to the default ones. The plugin loads now. I'm slowly going to add my fonts back one by one. Is it possible that some fonts would cause issues? I have some variable fonts from Google Fonts, would the plugin play nice with those?

Edit for clarity: I'm using the user patch posted by [sebdelsol](https://github.com/sebdelsol) on 9 June.

Edit 2: I added back all of my custom fonts. None of them caused the plugin to not execute this time round, so I wasn't able to reproduce my issue from earlier. Although I did have to swap out the variable fonts for static versions for them to be usable as UI fonts.

**Comment by mergen3107** [comment]
I don't think KOReader loves variable fonts :D

**Comment by mergen3107** [comment]
Anyway, should you have concerns later, check the log! It will tell you if it couldn't load the font, and which ones were OK

**Comment by Frenzie** [comment]
> I don't think KOReader loves variable fonts :D

I don't think they should cause any issues (in the crash sense at least).
