### ISSUE TITLE
Newly opened books do not show up in the History right away

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9952]
* KOReader version: 2022.11-56
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue and Steps to reproduce
When new books is opened for the first time, it doesn't show up in the History. They did before.
The way I noticed this is when I opened a new book, skimmed through, didn't like it and wanted to remove it from History, but didn't find the book there.

If I go to previous book or close/open KOReader, it shows up.
So something doesn't trigger in time (in context) when the book is just opened.
The issue is easily reproducible.

Probably regression since #9822 , but I am not sure.

##### `crash.log` (if applicable)
Open a new book go to History via gesture:
[crash1.log](https://github.com/koreader/koreader/files/10301766/crash1.log)

The same + open previous book via gesture.
[crash2.log](https://github.com/koreader/koreader/files/10301767/crash2.log)

**Comment by NiLuJe** [comment]
Possibly specific to the gesture approach, because using the menu works just fine?

**Comment by mergen3107** [comment]
Oh, thanks for the input! Didn't check that.

**Comment by hius07** [comment]
It doesn't depend on menu or gesture way of opening.
Newly opened book has a "New" status until it is closed and the sidecar file is created.
You can find it under the "New" filter.

**Comment by mergen3107** [comment]
But this doesn’t make sense. If I opened a New book, it is not New anymore :D

**Comment by hius07** [comment]
I am not saying it is good, just explaining the technical details of the issue.

**Comment by mergen3107** [comment]
Ah, sorry:) Thank you!

**Comment by NiLuJe** [comment]
Ah, I don't use *any* filter, which might explain my confusion?
