### ISSUE TITLE
FR: adding ‘save to cloud storage’ feature for text editor 

### ISSUE THREAD

**Issue by Lezcool** [koreader/koreader#9954]
I am very surprised that you can add cloud support for vocabulary builder. If it’s possible for vocabulary builder, can you add the same feature for the text editor? That will be very convenient.  @weijiuqiao , sorry I don’t know who’s responsible for the text editor.

**Comment by weijiuqiao** [comment]
I believe you can just manually upload and download to cloud the file you are working with with the text editor? But If you want to merge two files into one, I don't think it's quite possible, not without something similar to git :/

**Comment by Lezcool** [comment]
Upload the file to the cloud will be good enough. Thank you.

**Comment by Lezcool** [comment]
using Cloud server to upload.
