### ISSUE TITLE
Screensaver: "Leave as it is" and "Add message to screensaver" disabled → "Wait for gesture" doesn't wait

### ISSUE THREAD

**Issue by melyux** [koreader/koreader#9955]
* KOReader version: master
* Device: Kindle PW5

#### Issue
When "Wait for gesture" is the screensaver wait type, and "Leave as it is" is the screensaver type, and the "Add message to screensaver" option is turned off, a gesture is not required before the screensaver is dismissed. Using the power button immediately exits the screensaver.

#### Steps to reproduce
Simply set screensaver type to nothing and turn off the screensaver message. Set screensaver exit delay to "Wait for gesture" and set a gesture. Lock the device. Unlock the device. No gesture asked for

Unless I screwed something up in my environment big time...

##### `crash.log` (if applicable)
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by NiLuJe** [comment]
IIRC, there's no widgets at all in this case, so, yeah, makes sense.

Similar in spirit to #9911, except much simpler in effect, as there's just no widget at all to do the screen lock ;).
