### ISSUE TITLE
FR: A simple way to close multiple (nested) dictionary pop-up windows

### ISSUE THREAD

**Issue by dymky** [koreader/koreader#9957]
KOReader is nearly-perfect now: in particular, nearly anything one may not like about the default interface can be tuned to suit the needs.
Thank you for the great reader!

As of now, here is one feature I miss the most. It must be trivial to implement and would be very helpful in some situations.

Dictionary interface allows very simple "nesting": you choose a word from a current dictionary article and it is immediately searched for in a new pop-up window. However, to get back to the book, one has to close all the "nested" dictionary windows one by one.

Please add to the dictionary interface something like "Back to the book" button that would immediately close all opened dictionary windows and take you back to the current book.

Thank you!

**Comment by hius07** [comment]
Long-press the Close button.

**Comment by dymky** [comment]
You made my day, thank you!

Then let me use this opportunity and suggest a small further enhancement: it would make more sense to close also the "context menu" itself on Close long-press. Possible to implement?

**Comment by mergen3107** [comment]
@dymky 
This should be at least optional. I frequently find myself in situations when I selected a phrase and tried dictionary search. Didn’t find it there, and wanted to keep selection to be able to quickly reuse the same selection to go search in online translation.

**Comment by dymky** [comment]
@mergen3107
If I understand your comment correctly, that might be conveniently (and "option-free") addressed by closing the context menu only on the **long-press** of the Close button.

Adding a dedicated option would be fine too, of course.

So, could you please add the possibility to go straight back to the book on the long-press of "Close" in the dictionary window? Thank you!

**Comment by dymky** [comment]
@mergen3107
If I understand your comment correctly, that might be conveniently (and "option-free") addressed by closing the context menu only on the **long-press** of the Close button.

Adding a dedicated option would be fine too, of course.

So, could you please add the possibility to go straight back to the book on the long-press of "Close" in the dictionary window? Thank you!

**Comment by dymky** [comment]
P.S. Sorry, closing then re-opening the issue was my mistake.

**Comment by NiLuJe** [comment]
What are we talking about exactly with this "context menu"?

**Comment by hius07** [comment]
Popup menu after highlighting a piece of text.

**Comment by dymky** [comment]
> Popup menu after highlighting a piece of text.

Right, thank you!

Just have a look at the behaviour: open a book, highlight a word => a menu pops up => open the word in the dictionary (nest the dictionary windows if you wish) => long-press Close: you are back to the book, but the original menu is still shown (in fact, on my device it usually jumps to a different location after the long-press).

Instead, after long-pressing Close I would like to be straight back to reading, without that pop-up menu staying on screen.

**Comment by hius07** [comment]
Yes it jumps: https://github.com/koreader/koreader/pull/9507#issuecomment-1328103992.

**Comment by dymky** [comment]
> Yes it jumps: [#9507 (comment)](https://github.com/koreader/koreader/pull/9507#issuecomment-1328103992).

So, closing the pop-up context menu on Close long-press (from the dictionary) would also address the "jumping issue" mentioned under [#9507](https://github.com/koreader/koreader/pull/9507#issuecomment-1328103992).

**Comment by NiLuJe** [comment]
Except we already have a fix for that, so it's a non-issue. And, while closing all dictionary popups makes sense, you'd have to make your case harder for that to apply to the disambiguation popup, as it's used for more than dictionary lookups, as @mergen3107 mentioned earlier ;).

**Comment by dymky** [comment]
As I said: **_short press (on Close) acting the way it does now; long press taking the user straight back to reading_** is what I'd view as the most natural behaviour in this case.
Please consider implementing, thanks!

**Comment by poire-z** [comment]
Usually, we get this dialog box when selecting multiple words - which is not the most obvious path to do dict lookup (which we usually do/need on a single word, where this dialog does not appear).
When selecting multiple words, and getting the DictQuickLookup window that can end up nested, and that we can close with long-press on the close button or icon, it's because we do Wikipedia lookups - and get lost in the fun world of Wikipedia pages. When getting out of it, we indeed get back on this dialog box. May be 10% of the time, I will do another thing: translation, or just "highlight", as I feel I'll need to look it up again when I'll be on a computer with a real web browser.

So, I think it's better to stay with this dialog, even if we will do another thing only 10% of the time.
Closing it is for you and me just another tap away - and we get to better focus on the highlighted word going unhighlighted after all the windows are closed, after we dismiss that dialog.
In my opinion, Long-press on close does not have to get the orthogonal side effect of closing this dialog. Other actions, ie. Translate, don't have it.

**Comment by dymky** [comment]
> Usually, we get this dialog box when selecting multiple words - which is not the most obvious path to do dict lookup

@poire-z 
It seems that I am missing yet another interface trick here, as I am getting this dialogue every time I use a dictionary to look up a (single) word from the text! :)

How do you look up a highlighted word from the book without seeing that "context menu" dialogue?
Thanks!

**Comment by poire-z** [comment]
You must have changed our defaults, which is:
Gear > Tap and gestures > Long-press on text > ![image](https://user-images.githubusercontent.com/24273478/210083920-bd100d89-63dd-4a32-9623-09b5df62c819.png)
You must have unchecked that top checkbox ? (Or we did mess things in some migration step at some time in the past.)

**Comment by dymky** [comment]
@poire-z 
I can't thank you enough!

Indeed, "dictionary on single word" was unchecked; frankly, I'd hesitate enabling it if there were no "very long press" option!

I am closing my request, as indeed, there is no need to change anything: all one may ever need is already configurable!

Thank you for your answers and sorry for my ignorance!

I think, some of the features that I was unaware of were still not implemented when I started using KOReader (of course, it is still my fault to have ignored "What is new" notes while updating the reader).
