### ISSUE TITLE
Reading statistics crash after deletion

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9972]
* KOReader version: 2022.11-56
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
KOReader crashed after I deleted a bunch of reading statistics entries. 

#### Steps to reproduce
1) Have number of opened books more than number of items that can fit a page in Reading statistics - Reset statistics - Reset per book. Let’s say there are two pages.  
2) Delete there one by one until all items left can fit one page. The page count will still say 1 of 2 pages. 
3) Try to go to page 2 - crash!

I think each deletion should check and recalculate the number of pages?

**Comment by hius07** [comment]
```
./luajit: frontend/ui/widget/keyvaluepage.lua:611: attempt to compare nil with number
stack traceback:
	frontend/ui/widget/keyvaluepage.lua:611: in function '_populateItems'
	frontend/ui/widget/keyvaluepage.lua:750: in function 'removeKeyValueItem'
	plugins/statistics.koplugin/main.lua:2305: in function 'ok_callback'

```
@weijiuqiao

**Comment by weijiuqiao** [comment]
Oops. Let me do a pr to fix it.
