### ISSUE TITLE
Text Editor list update

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9973]
* KOReader version: 2022.11-56
* Device: Onyx Boox Kon-Tiki 2 (Android 10)

#### Issue
Text Editor file list doesn’t update after deletion

#### Steps to reproduce
1) Let’s say there are three files that were opened by Text Editor. They will look like this list in the top menu:
1. File1
2. File2
3. File3 

2) If I now delete File2, the list will have the same numbering, but missing “2”:
1. File1
3. File3 

3) If top menu is closed and opened again, the list numbering will be ok:
1. File1
2. File3

I think such update of numbering should happend after each deletion of file history.

**Comment by poire-z** [comment]
You're so nitpicking these days !

Well, I don't really remember why I felt the need to add a leading number. But it makes out the menu item title - and when we remove one, we just remove the item from the list, keeping all the other items as-is (so, still with their initial number):
https://github.com/koreader/koreader/blob/180cebe7ee7005328cc98dd493302ea23091c8d7/plugins/texteditor.koplugin/main.lua#L239-L243

Updating this number would need to rebuild the whole menu item list, which I don't feel like spending time on :)

> I think such update of numbering should happend after each deletion of file history.

Let's say it's a feature : when looking at the list, a user will remember in its short term memory it would need to remove items 4, 7, 13 - if we shuffle these numbers, we'd be messing with his mind, and KOReader doesn't do that !

**Comment by mergen3107** [comment]
I am sorry! I just feel like it doesn’t feel complete or consistent :D 1) If there are numbers, they should update. 2) Otherwise, if they are not updated, maybe we don’t need them? We can only read them in the list, we don’t get to refer to them like in a cmd query or something.

**Comment by mergen3107** [comment]
> Updating this number would need to rebuild the whole menu item list, which I don't feel like spending time on :)

But isn’t this code of refreshing already there? In the part where the menu gets drawn in the first place. So my proposition was to add this code to the action of deleting an item

**Comment by poire-z** [comment]
Indeed, this seems to work (and makes things simpler):
```diff
--- a/plugins/texteditor.koplugin/main.lua
+++ b/plugins/texteditor.koplugin/main.lua
@@ -206,8 +206,3 @@
                                 self.last_view_pos = {}
-                                -- remove history items from the parent menu
-                                for j = #sub_item_table, 1, -1 do
-                                    if sub_item_table[j]._texteditor_id then
-                                        table.remove(sub_item_table)
-                                    end
-                                end
+                                touchmenu_instance.item_table = self:getSubMenuItems()
                                 touchmenu_instance:updateItems()
@@ -248,3 +243,2 @@
             end,
-            _texteditor_id = file_path, -- for removal from menu itself
             hold_callback = function(touchmenu_instance)
@@ -267,9 +261,3 @@
                         self:removeFromHistory(file_path)
-                        -- Also remove from menu itself
-                        for j=1, #sub_item_table do
-                            if sub_item_table[j]._texteditor_id == file_path then
-                                table.remove(sub_item_table, j)
-                                break
-                            end
-                        end
+                        touchmenu_instance.item_table = self:getSubMenuItems()
                         touchmenu_instance:updateItems()
```

But I'm still partial to keeping the original number for a same text editor history list session, even if it make the counting have holes as you remove items.
(I also think these numbers makes it more obvious that these menu items are a list of files / history of files, and not just regular menu items.)

So, needs others' opinions :)

**Comment by mergen3107** [comment]
Yes, I understand your position. However, it is good mostly for devs’/debugging perspective when digging into css and lua files.

As a mere user, I use Text Editor to edit lists of books, mangas and articles in different files. So I don’t really need any numeration. Let hear what other people use Text Editor for. 

As for the appearance, how about indenting all files and having one item saying “Previously open items:”?

**Comment by poire-z** [comment]
> As for the appearance, how about indenting all files and having one item saying “Previously open items:”?

There's been #9947 - but I'm not really fond of that look. Also, it may work fine on the first page where we see "Previously open items", but on the 2nd++ menu pages, it may be a bit strange to get these indented items without the heading. (And it would waste a valuable menu slot :)

**Comment by hius07** [comment]
I would remove numbers.

**Comment by poire-z** [comment]
> I would remove numbers.

Feels a bit ood to me, having plain filenames as plain menu items:
![image](https://user-images.githubusercontent.com/24273478/210165865-7602898d-6653-4d53-8463-49deb77f8da6.png) ![image](https://user-images.githubusercontent.com/24273478/210165876-a6a89e72-90b5-4c45-8e35-093d90da39b0.png)

Or we could replace the number with a leading symbol ?:
![image](https://user-images.githubusercontent.com/24273478/210166027-5d77300a-1405-41b8-a0a4-df0c794c547f.png) ![image](https://user-images.githubusercontent.com/24273478/210166831-878790c2-1c03-47f9-be3a-8aa0b19a0a3e.png) ![image](https://user-images.githubusercontent.com/24273478/210166882-de19a7a8-8812-4c6b-8114-fd578693ef2c.png)

**Comment by poire-z** [comment]
Went with the last screenshot in #9985.
