### ISSUE TITLE
Extend book deletion warning to include highlights/bookmarks/related data

### ISSUE THREAD

**Issue by rixx** [koreader/koreader#9978]
**Edit:** After the discussion below, this is now a feature request to extend the warning text shown to users when they delete books in the KOReader file manager.

This is somewhere in between a bug report and a feature request:

I just exported my clippings and was surprised (and a bit terrified, admittedly) to see that the export included only books still present on my device. A short dig showed that highlights/clippings up until ~May are still included in the `metadata.sdr.lua` file, but any book I read afterwards and then removed from the device, it seems like highlights were removed with the book.

Questions:

1. Is this an intended change in behaviour? (I searched the issues, but found nothing)
2. Is there a way to retrieve highlights after deleting a book from the device?
3. If the change is intended, and highlights currently are gone when a book is deleted: Would you be open to discussing a feature request to modify this behaviour? I enjoyed the past behaviour a lot (removing books but keeping my highlights).

**Comment by NiLuJe** [comment]
How were the books deleted, exactly?

**Comment by rixx** [comment]
Within KOReader, long-press and delete.

**Comment by NiLuJe** [comment]
That *does* delete the sidecar (and, IIRC, always has; ping @hius07), which is where document-specific stuff (including highlights) are stored.

**Comment by mergen3107** [comment]
Yes, this has been the behaviour since a long time now. 

Maybe we should now also warn that everything will be gone after deletion? Currently it only warns that the book will be gone forever.

**Comment by hius07** [comment]
> metadata.sdr.lua

Strange name, I cannot trace its existence in old versions of the program.

**Comment by rixx** [comment]
Hmm, I'm honestly not sure where it came from. It's in the clippings export directory.

It definitely makes sense for things to be gone when you delete books, and I was only caught out by it because I had seen different behaviour before (maybe I moved books prior to removing them, or removed them a different way?), so now I'm trying to remember the ~60 books I read since then. I think a warning that all related data will be deleted alongside the book would have helped me – let me edit the issue title in that direction.

**Comment by hius07** [comment]
So, it was a result of exporting made prior to deleting.

I think an additional warning for books with metadata can be implemented.
