### ISSUE TITLE
(UX) progress bar(s) improvement

### ISSUE THREAD

**Issue by mergen3107** [koreader/koreader#9979]
* KOReader version: 2022.11-62
* Device: Onyx Boox Kon-Tiki 2 (Android)

Hi guys!
Following items are not issues, but suggestions on bottom and top progress bars' UX.
I am not insisting these to be fixed, but I think if they are fixed it will make KOReader a tad more polished ereader.

(Also, answering the question of me being so picky - yeah, congrats guys! That means KOReader works so good, that only those tiny details are only jumping into view :D )

#### ☐ Item 1 (bottom progress bar): redraw box when margins are tight

![bottom1_clock_redraw](https://user-images.githubusercontent.com/6279855/210125538-ebec3e10-a743-46c3-a06a-f788ea62320c.png)

When `Auto refresh` is on, the bottom progress bar redraws after each minute update.
I set the `Font size` to 12, `Container height` to 7 and `Container bottom margin` to 1.

Now, when it refreshes, the next total width of the whole progress bar string is different. This is because in this font characters `5` and `6` have slightly different widths. This consequently allows to see that there are remnants of previous string after redraw.

So maybe there should be a white box drawn first over the whole progress bar area before the new string is drawn for the refresh?

Temporarily, if I set the font size to 11 or lower, this "fixes" it, but the text is quite tiny.

#### ✅ Item 2 (SOLVED in #9983) (bottom progress bar): redraw box when bottom menu is open

> ![bottom2_bottom_menu](https://user-images.githubusercontent.com/6279855/210125647-221c018d-b086-48ef-a358-791259b529ff.png)
> 
> When `Auto refresh` is on, the bottom progress bar redraws after each minute update and even over the bottom menu.
> 
> In order to keep everything working as intended, here is my suggestion: make bottom menu aware of the bottom progress bar if it's used.
> 1) I suppose a flag like " `Auto refresh`  is on and bottom bar is active" should be passed to the bottom menu before the menu is drawn.
> 2) Bottom menu then suppresses/suspends the progress bar refresh, and then triggers it after it is closed, if necessary, i.e. if the time has changed while the bottom menu was open.

#### ☐ Item 3 (bottom progress bar): left/right alignment margins?

![bottom3_alignment](https://user-images.githubusercontent.com/6279855/210125750-11330214-ef41-4adc-b46b-4d7d6a34e836.png)

In the settings of the bottom progress bar progress line, there is an option to light the text string to right/left/center. However, I don't understand where is the alignment beginning for the progress bar string. It doesn't seem to be affected by the setting and it doesn't align to either of book margins (currently 20 in the picture above) or the default margin (16). By trials, I found that the string and the progress line match when the both book margins are set to 10.

Can the progress bar string be aligned with the progress line?

#### ✅ Item 4 (SOLVED in #9985) (top progress bar): bookmark sign in the corner: start after the top progress bar

> ![top_bookmark icon draw location](https://user-images.githubusercontent.com/6279855/210126954-a89e4ab8-9fd6-4d07-b711-2b034609ac01.png)
> 
> Currently, the bookmark icon drawing area is not affected by the top progress bar.
> Can this be adjusted?

#### ☐ Item 5 (top progress bar): remove it completely?

I remember you guys complaining about the top progress bar being an utter rubbish when it comes to handle it overall.

So maybe with 1) making the bottom progress bar adjustable to be put on the top; and 2) adding the author's name (#7642), we can remove the legacy top progress bar completely? So that it will do the same job if needed, expect there won't be a second progress bar simultaneously.

This will unwind the haywire of the top progress bar from the bottom menu. Haywire, because the top progress bar is strictly related to the settings of the **document layout**, not reader settings. This is the legacy of crengine after all.

UX-wise, this change will make it much easier to set up and actually use the progress bar.

#### ✅  Item 6 (SOLVED in https://github.com/NiLuJe/koreader/commit/cc2b0724831fe7eba2ba724f076aae473f8d0bb2) (bottom progress bar): does not refresh instantly after tap
> 
> In muPDF engine, tapping on the bottom progress bar does not show up instantly. However it works as intended. 
> 
> For example, I have a progress bar which fits it all. Taping once causes it to disappear. Taping another time brings it back. It is fine in crengine, but in mupdf I tap it once, it slightly shifts (redraws?) but the action will be visible upon next page turn. Maybe it is because the zoom is set to Fit the page?
>

**Comment by poire-z** [comment]
Items 1, 2 and 3 sounds like footer refresh dimen bugs (and I will happily let that to @NiLuJe and @zwim).

Item 4 (dogear over top status bar) looks like a regression: I remember ensuring it was drawn below, and it still was in appimage v2022.10 - but not on current master :/

Item 5: not making crengine top status bar available would make some users unhappy, no matter how well we could make parts of the footer (or a clone of it) display at top (and doing that would be quite hellish).

**Comment by NiLuJe** [comment]
2 is a regression, I distincyl remember making sure this behaved way back in the day.

**Comment by poire-z** [comment]
Item 4 is probably due to the event/handles reorganisation of #9651.
Should be solved by just adding:
```lua
function ReaderDogear:onReaderReady()
    self:updateDogearOffset()
end
```

**Comment by zwim** [comment]
IMHO item 2 is a missed `covers_footer` in `readerconfig.lua`, my mistake.

**Comment by NiLuJe** [comment]
The rest are admittedly because of the unstable font metrics (which doesn't happen with Noto). I'm mildly wary of attempting to add funky heuristics just for that, but a fancier refresh function that remembers the last dimen and passes max(prev, dimen) *should* mostly deals with this?

**Comment by NiLuJe** [comment]
Err, barring the alignment thing, which IIRC might be by design to try to cadge a few pixels.

**Comment by mergen3107** [comment]
Thank you guys for your replies and commits! 
Items 2 and 4 are now solved! 

Meanwhile I have observed another issue and described it as Item 6 in the OP. Could you please have a look?

**Comment by NiLuJe** [comment]
Full zoom congig needed ;).

**Comment by mergen3107** [comment]
OK, here is a collection of my settings files, including directory_defaults.lua for manga, as well as an example of mange where this issue mostly happens. (I also got confused, why are there so many default settings files? `defaults.custom.lua`, `defaults.legacy.lua`, `defaults.persistent.lua`?)

Settings: https://disk.yandex.com/d/q7oeYCyAZ2TqjQ
Manga: https://disk.yandex.com/d/q7oeYCyAZ2TqjQ

Mostly is happens in manga (most of the time) and occasionally in other pdf files. Can't get them consistently, but basically what happens is that after I tap the visible bottom progress bar, the bar flickers the same way when it does auto refresh. So it flickers but stay on screen, the page zoom is the same.

Upon page turn, it: either goes away and zoom is properly adjusted; or the zoom level get's cropped and the page shifts just a little bit, as if I set to show 99% of the page height. So this 99% page height get's "highlighted" although I selected the "arrow" method for overlap. Weird!

**Comment by NiLuJe** [comment]
> (I also got confused, why are there so many default settings files? `defaults.custom.lua`, `defaults.legacy.lua`, `defaults.persistent.lua`?)

#9546

(You should no longer have a `defaults.persistent.lua`, unless it was copied manually post-migration).

**Comment by mergen3107** [comment]
Oh, OK! 

Thanks :) 

Sorry, I got some corrections in the above post as I played around more carefully.

**Comment by mergen3107** [comment]
Additional observations to Item 1 (artifacts). After artifacts show up after the minute changes, opening the top menu also makes the progress bar clean and pristine. So maybe the refresh method for auto refresh is different than that used when top menu is opened or page is turned?

**Comment by mergen3107** [comment]
Also, it is there with any font, just that with Noto Sans (default one) it is much less noticeable. But that doesn’t mean it is nonexistent :D

**Comment by NiLuJe** [comment]
> So maybe the refresh method for auto refresh is different than that used when top menu is opened or page is turned?

Nope, it's just that opening a menu might trigger a ReaderUI repaint, effectively fixing the missed slice ;).

**Comment by NiLuJe** [comment]
> Also, it is there with any font, just that with Noto Sans (default one) it is much less noticeable.

Nope, Noto has stable vertical metrics.

Handling these edge-cases would be messy: if the refresh dimension is *smaller*, we'd need to actually keep the bigger refresh dimension, but *also* repaint ReaderUI behind it...

(Currently, the contract that the dimensions is stable ensured by stable vertical metrics ensure we can optimize things a bit by never touching ReaderUI, outside of the obvious case when dismissing the footer ;)).

**Comment by NiLuJe** [comment]
> Settings: https://disk.yandex.com/d/q7oeYCyAZ2TqjQ
> Manga: https://disk.yandex.com/d/q7oeYCyAZ2TqjQ

Both links are identical ;o).

**Comment by mergen3107** [comment]
Oops, sorry! 
here is the new link: https://disk.yandex.com/d/voYZEYPEeBkonQ

I’ll update it in the post in a second

**Comment by mergen3107** [comment]
Yes, the sidecar is included

**Comment by mergen3107** [comment]
`Nope, Noto has stable vertical metrics.`

Here is an example. Have a closer look at the digit `6` in the progress bar's clock.

"Dirty" progress bar, when the minute digit `5` changed to `6`:
![NotoSans1_dirty Screenshot_20230108-141640](https://user-images.githubusercontent.com/6279855/211214876-a8aeedc5-dad8-4308-8fb9-72916780559e.png)

"Clean" progress bar after I opened and closed the top menu:
![NotoSans2_clean Screenshot_20230108-141651](https://user-images.githubusercontent.com/6279855/211214887-b7bc56ad-efc2-4a5d-b775-2a7018828c52.png)

I am not insisting to fix this, I am just making sure my report is true and up to the point :D

**Comment by mergen3107** [comment]
As I said, it is hard to notice this on Noto Sans. But I can definitely see the difference (on these progress bar settings I mentioned) after the forced refresh.

**Comment by NiLuJe** [comment]
That's... stranger; there are more differences that just the 6, including on unchanged characters (e.g., the pipes, or, more visible, the H of Chapter).

**Comment by NiLuJe** [comment]
I can't reproduce 6. either, FWIW (assuming you meant in "Continuous" mode). But if you meant "Page" view mode, I can't either, because that's how I use the Elipsa, and I'd have noticed ;p.

**Comment by NiLuJe** [comment]
I suspect your container height might simply be too small to actually fit the text or something like that...

**Comment by mergen3107** [comment]
Hmm, that’s really weird. 

No, I didn’t mean “continuous” in both crengine or mupdf. Everything is in “paged” mode. 

As far as Android Optimizations go, I disabled all Onyx packages including the main com.onyx, which is responsible for Onyx’es “App Optimization”. So all apps are shown as they would on a non-eink Android. 

The only thing left from intrusions though is manual contrast control. Let me see if it makes a difference.

**Comment by mergen3107** [comment]
`Back to the chopped off glyphs: I suspect your container height might simply be too small to actually fit the text or something like that...`

That was my first guess! However, they somehow are rendered great on the first refresh and on forced ones, but not on Auto refresh. 

Also, the option to draw the separator adds a nice chink of extra white space above the characters’ “ceiling”, giving them a nice breathing room. Gimme a second, I’ll show you what I mean exactly

**Comment by mergen3107** [comment]
`The only thing left from intrusions though is manual contrast control. Let me see if it makes a difference.`
OK, nevermind, the contrast tweaking has been off the whole time.

**Comment by NiLuJe** [comment]
> I can't reproduce 6. either

Hmm, progress, I can trigger some weirdness with reclaim disabled. That was a bitch and a half to deal with, last I remember...

**Comment by mergen3107** [comment]
Good :) That means I am not seeing things xD

**Comment by mergen3107** [comment]
`the option to draw the separator adds a nice chink of extra white space above the characters’ “ceiling”, giving them a nice breathing room`: so here is a good example to illustrate this.

Footer separator OFF:
![Footer_Separator_OFF Screenshot_20230108-144556](https://user-images.githubusercontent.com/6279855/211215897-abdb2f3e-ae70-49f6-8589-27165a795c6b.png)

Footer separator ON:
![Footer_Separator_ON Screenshot_20230108-144619](https://user-images.githubusercontent.com/6279855/211215904-e51c9e15-659b-4f89-b275-4d1cf1a38267.png)

**Comment by mergen3107** [comment]
Now, the reason I made the progress bar so small is that I wanted the bottom progress to replace the top progress bar without makes difference in the page count of the book. This took a while to tweak.

Here is my related question to the footer separator: maybe it is possible to have this extra white space drawn as an option? Like an option to `Show footer separator` but without the separator itself.

**Comment by NiLuJe** [comment]
> `the option to draw the separator adds a nice chink of extra white space above the characters’ “ceiling”, giving them a nice breathing room`:

I can't reproduce that *at all* :?

(container at 7, font at 14 (defaults), bottom marging 6 (not that this last one should matter)).

![container_7_font_14](https://user-images.githubusercontent.com/111974/211221184-2908da97-b429-433b-a75d-def1939c69bd.png)

**Comment by mergen3107** [comment]
I have it on Container 7, Font 11, Margin 1

**Comment by NiLuJe** [comment]
> Font 11

Possibly made more explicit because of the smaller font-size; the separator includes a vertical span (a tiny one), which probably becomes more obvious when we're down to 0px of visible line-height.

**Comment by NiLuJe** [comment]
> Container 7, Font 11

At which point the font overflows the container, which explains your refresh issues ;).

![container_7_font_11](https://user-images.githubusercontent.com/111974/211221919-ba02e382-b14e-46de-8b31-3224837b3cb9.png)

**Comment by NiLuJe** [comment]
The minimum container size is not dynamic, and I'm not entirely sure trying to magic up something that takes the actual content height into account feasible or a good idea at all, so I'm gonna mark that one as "working as intended" ;).

**Comment by mergen3107** [comment]
I tried decreasing the font size to 10, at which point the artifacts are barely visible, but the font itself is already to small to be comfortable :D 

Increasing the container height does not solve the issue of extra white space, because when the height is increased, the extra white space is added more below the string and just a little above it, and the string itself is still more aligned towards the container ceiling. I tried going all the way up to container size 36, where it is obvious that extra white space is added after footer separator is enabled. 

So it looks like that the string is vertically centered only when the footer separator is enabled, which I don't think should be default?

**Comment by mergen3107** [comment]
I mean, if the footer separator is disabled, the height of string should be centered to what is there from the container height above the progress bar.

**Comment by mergen3107** [comment]
`So it looks like that the string is vertically centered only when the footer separator is enabled, which I don't think should be default?`
If this was your intention from the beginning, then yes, it `works as intended` but looks misaligned and doesn't change with regards footer separator.

**Comment by mergen3107** [comment]
`At which point the font overflows the container, which explains your refresh issues ;)`

So the font is overflowing over the container? This is at least weird, because why the font is ever allowed to do that? What is the purpose of "container height" then? Is it not to **contain** the string? :D 

So in my understanding it does this:
1) There are two boxes to refresh. One with **container and footer separator heights**, another with **just the container height**.
2) With footer separator **disabled** and when settings are changed so that the font size is big enough to overflow the container height, it renders the string with overflow and leaves it like that. Like, taking no responsibility to clear this space where the font has overflew before doing the next auto refresh rendering.
3) If the footer separator is **enabled**, there are no such issues, because the whole height consisting of **container and footer separator heights** is being cleared and then string is drawn over there. 

There are no artifacts with footer separator enabled, I tried font sizes 11 and 14 so far and waiting for minute-to-minute auto refresh.

**Comment by NiLuJe** [comment]
> I mean, if the footer separator is disabled, the height of string should be centered to what is there from the container height above the progress bar.

I can't reproduce that, the string doesn't budge whether the separator is enabled or not over here.

e.g., at max (98):

![container_98_font_14](https://user-images.githubusercontent.com/111974/211222746-3bc19b31-8fe9-46fd-8aeb-e39db8f78936.png)

**Comment by NiLuJe** [comment]
> There are no artifacts with footer separator enabled, I tried font sizes 11 and 14 so far and waiting for minute-to-minute auto refresh.

Because the thin vertical span just manages to bridge the gap ;).

As for the rest, that's just how containers and text widget works in KOReader (e.g., where it matters, some stuff have guards in place to reduce the font-size on overflow), but by default, stuff can blow past everything. It's a container in terms of code, not layout ;).

**Comment by mergen3107** [comment]
OK, thank you for your patient explanations :D 

This is where I remember that KOReader is still dev-oriented rather than user-oriented xD 

Not necessarily a bad thing, but I found my self confused more than I needed to be :D

**Comment by NiLuJe** [comment]
Keep in mind ReaderFooter is a giant mess. It's a very old "widget" (read: mess) that was initially very simple, and has grown exponentially into a complex monstrosity over the years as people tacked on features on top of it, not always in the most elegant fashion. The fact that it even behaves at all in most cases is a minor miracle ;o).

**Comment by mergen3107** [comment]
OK, thank you!

Your latest commit above has solved the Issue 6! I marked it as solved in the OP

**Comment by mergen3107** [comment]
Can I please add here that Item 2 happens with the “View HTML” (select text, get a popup) window as well. So the bottom progress bar draws on top of it too.

**Comment by mergen3107** [comment]
The above PR solves the issue with the HTML Viewer by adding `covers_footer = true,` to the `textviewer.lua`.

There is another place where I found this behavior: if I long-press a style tweak and move it to the bottom.

What is the widget I should be tweaking now?

**Comment by poire-z** [comment]
But it was made (not taking the full height) to somehow not cover the footer :)
![image](https://user-images.githubusercontent.com/24273478/213943346-3800bd43-0e59-479e-983d-12b1d76c44f4.png)

But anyway, if we don't find a better solution, I'm fine with flagging it as `covers_footer` - as I guess this just affects the autorefresh of the footer, right?

> There is another place where I found this behavior: if I long-press a style tweak and move it to the bottom.
What is the widget I should be tweaking now?

Well, that's a less acceptable fix if you would hack this TweakInfoWidget (readerstyletweak.lua).
I guess any "movable" widget (ie. any InfoMessage, a DictQuickLookup result window, the SkimWidget and many others) can be moved over the footer and would cause the footer to be autorefresh on them :/
So, if a fix is really needed, it should be more generic (and probably more compicated).

**Comment by mergen3107** [comment]
Yes, that’s only about autorefresh. 

Well, in that case it is not working as intended. 

I have the progress bar to be shown below the items. HTML Viewer goes all the way over the items and leaves the progress bar itself alone. So when time updates, items refresh and cover the HTML Viewer and its buttons. Should the calculation of the whole progress bar height be revised?

As for the movable containers, I’d suggest to prevent them be moved over the progress bar’s full height. Then we don’t have to think about overlaps :D Is this a good solution?

**Comment by NiLuJe** [comment]
> As for the movable containers, I’d suggest to prevent them be moved over the progress bar’s full height. Then we don’t have to think about overlaps :D Is this a good solution?

There's no bounding restriction on a move, IIRC (i.e., you can shove most of a MovableContzainer off-screen), so, err, good luck with that? ;).

**Comment by NiLuJe** [comment]
This is pretty much while I initially took the reverse approach (also, I hate autorefresh with a fiery passion because it's a mess to do right, which kinda steered me towards a defensive approach in the first place ;p) of "no refresh by default" (i.e., whitelist vs. blacklist).

**Comment by NiLuJe** [comment]
> But it was made (not taking the full height) to somehow not cover the footer :)

That sort of stuff not dealing entirely with some ReaderFooter setups vaguely (like, very very faintly) rings a bell, so, yeah, some stuff might need tweaking there...

**Comment by poire-z** [comment]
> As for the movable containers, I’d suggest to prevent them be moved over the progress bar’s full height. Then we don’t have to think about overlaps :D Is this a good solution?

I won't let you do that: I do move stuff 90% outside on the bottom when I want to see again the text, or another widget below it, ie the CSS TextViewer, to see again the HTML TextViewer). I don't want to be limited by a footer I don't care about :)

> That sort of stuff not dealing entirely with some ReaderFooter setups vaguely (like, very very faintly) rings a bell, so, yeah, some stuff might need tweaking there...

Oh, nothing special done there, just a static value (gathered from a study of one customer feedback: me :) - and it has work quite well as no other user has complained !:
https://github.com/koreader/koreader/blob/34f92bc1969cc8a71cf8d68ffffa80b33c250e6e/frontend/ui/widget/textviewer.lua#L77-L78

**Comment by NiLuJe** [comment]
> Oh, nothing special done there, just a static value (gathered from a study of one customer feedback: me :) - and it has work quite well as no other user has complained !:

Oh, right, and I may have tried to switch to self.ui.footer:getHeight() at one point (or whatever thing I added to report the actual footer height) and not been overly fond of the result, I think?

**Comment by NiLuJe** [comment]
I'll reread what we said when we switched to the `covers_footer` approach, because I don't remember the context. I do remember that I was wary of a `dimen` approach, but I'll probably revisit that, because, assuming we *can* rely on `dimen`, it feels like the only sane approach to deal with variable size widgets or movables...

I'll try some stuff later tonight...

**Comment by NiLuJe** [comment]
Okay, everything is indeed terrible: as I feared, most stuff sets its dimen field to the screen size, which makes this unfeasible :/.

**Comment by mergen3107** [comment]
Ah, sorry, the page overlap is OK, it is just I can’t see what’s the last line to be able to follow the arrow on the next tap. 

Also, Clumns, Rows, and just Percent zoom modes all behave the same wrt summoning progress bar.

**Comment by NiLuJe** [comment]
I don't recall the details, but I do remember that it's horribly nightmarish to deal with, especially when you have no idea how the kopt stuff works re: layout (hai!); so, yeah, I fully expect for some things to still be wonky ;).

**Comment by mergen3107** [comment]
(we need a new label named "good enough", ehich is the equivalent of "solved" + "won't fix" :D )
