### ISSUE TITLE
ZIP file support

### ISSUE THREAD

**Issue by clach04** [koreader/koreader#9986]
* KOReader version: 2022.08
* Device: Kindle PaperWhite 2

#### Issue

Documentation mentions ZIP file support but does not explain this in detail

* http://koreader.rocks/koreader-user-guide.pdf
* as does main page http://koreader.rocks/
    * https://github.com/koreader/koreader.github.io/blob/master/index.html#L20

It looks like any supported format can be supported in a ZIP file IF the filename of the zip file is `*.FORMAT.zip`, e.g.:

* `myfile.txt.zip`
* `myfile.rtf.zip`

However https://github.com/koreader/koreader/blob/master/frontend/document/credocument.lua#L155 indicates the file type can be inferred by the first filename in the archive (a feature supported by many softwre ebook readers like FBReader, AlReader, etc). This does not appear to work.

I think there are two issues at play here:

1. ZIP support not working consistently
2. Doc issue, assuming the above is correct I could post a PR to the readme for this repo ([the inde](https://github.com/koreader/koreader.github.io/blob/master/index.html), and also add a comment to https://github.com/koreader/koreader/issues/8058) once this is confirmed.

As always thanks to everyone working to support KoReader!

#### Steps to reproduce

See attached test/demo documents (from https://github.com/clach04/sample_reading_media):

* ✔️ works [test_book.txt.zip](https://github.com/koreader/koreader/files/10329263/test_book.txt.zip)
* ❌ fails with error "No reader engine for this file of invalid file" [test_book_txt.zip](https://github.com/koreader/koreader/files/10329264/test_book_txt.zip) - actually the same file as above but renamed

Both books contain a single file called `test_book.txt`, no other files inside the ZIP archive.

    >"c:\Program Files\7-Zip"\7z l C:\tmp\test_book.txt.zip

    7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

    Scanning the drive for archives:
    1 file, 254 bytes (1 KiB)

    Listing archive: C:\tmp\test_book.txt.zip

    --
    Path = C:\tmp\test_book.txt.zip
    Type = zip
    Physical Size = 254

       Date      Time    Attr         Size   Compressed  Name
    ------------------- ----- ------------ ------------  ------------------------
    2020-09-29 15:47:45 ....A          209           94  test_book.txt
    ------------------- ----- ------------ ------------  ------------------------
    2020-09-29 15:47:45                209           94  1 files

    >"c:\Program Files\7-Zip"\7z l C:\tmp\test_book_txt.zip

    7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

    Scanning the drive for archives:
    1 file, 254 bytes (1 KiB)

    Listing archive: C:\tmp\test_book_txt.zip

    --
    Path = C:\tmp\test_book_txt.zip
    Type = zip
    Physical Size = 254

       Date      Time    Attr         Size   Compressed  Name
    ------------------- ----- ------------ ------------  ------------------------
    2020-09-29 15:47:45 ....A          209           94  test_book.txt
    ------------------- ----- ------------ ------------  ------------------------
    2020-09-29 15:47:45                209           94  1 files

##### `crash.log` (if applicable)

No `crash.log`

Let me know if logging is needed

If your issue doesn't directly concern a Lua crash, we'll quite likely need you to reproduce the issue with *verbose* debug logging enabled before providing the logs to us.
To do so, from the file manager, go to [Tools] → More tools → Developer options, and tick both `Enable debug logging` and `Enable verbose debug logging`.
You'll need to restart KOReader after toggling these on.

If you instead opt to inline it, please do so behind a spoiler tag:
<details>
  <summary>crash.log</summary>

```
<Paste crash.log content here>
```
</details>

**Comment by hius07** [comment]
> indicates the file type can be inferred by the first filename in the archive

This piece of code is not executed, zip files are handled by muPDF due to bigger weight.
https://github.com/koreader/koreader/blob/cbe7775bc89f98b1b6833802499865a453f2774f/frontend/document/credocument.lua#L1490
https://github.com/koreader/koreader/blob/cbe7775bc89f98b1b6833802499865a453f2774f/frontend/document/pdfdocument.lua#L382

**Comment by clach04** [comment]
Thanks @hius07 , that is really neat! I had no idea about the open with. I'll think on this a little before I do anything, I'm thinking about making a wiki page (and maybe guide) update.

**Comment by clach04** [comment]
@hius07 sorry for the delay (been sick :-()

I went ahead and:

* made some minor additions to https://github.com/koreader/koreader/wiki/Features-list
* Created https://github.com/koreader/koreader/wiki/ZIP

I've not yet made a README change yet for https://github.com/koreader/koreader/blob/master/README.md - seeking feedback on the wiki page(s) first. However I'm about to open a small PR to update the supported format list in the readme to match what is now in the wiki

**Comment by clach04** [comment]
https://github.com/koreader/koreader/pull/10004 posted for the non-ZIP note

**Comment by hius07** [comment]
Thank you, your wiki updates look good.
One note: KOReader can open a zip archive without long-pressing if the archive contains graphic files (jpg, png etc). To try it you can just change the extension from cbz to zip.

**Comment by clach04** [comment]
Thanks, made a quick note to that effect in the wiki.
