### ISSUE TITLE
Pressing & Holding Exit Button not Exiting Koreader anymore?

### ISSUE THREAD

**Issue by Maxwell12347842** [koreader/koreader#9999]
* KOReader version: latest
* Device: Kindle Paperwhite 4

#### Issue
I updated today from an 1 Year old Koreader Version to the newest Version over OTA. I always exited it by pressing & holding the Exit tab in the menu, but after the update.. this doesn't works anymore. I always have to manually click exit, then choose "exit". 

How do i get this feature back? It's annoying to have make additional clicks just to exit koreader everytime. Especially if you have to go back and forth between koreader and the normal kindle interface, its annoying.

**Comment by hius07** [comment]
Yup, removed in https://github.com/koreader/koreader/pull/8459.

**Comment by poire-z** [comment]
I guess it was removed by error, and it should be back - or did we dicuss that and there was a reason for its removal ?

This would resurrect it:
```diff
--- a/frontend/ui/elements/common_exit_menu_table.lua
+++ b/frontend/ui/elements/common_exit_menu_table.lua
@@ -8,6 +8,9 @@ local exit_settings = {}
 exit_settings.exit_menu = {
     text = _("Exit"),
     -- submenu entries will be appended by xyz_menu_order_lua
+    hold_callback = function()
+        UIManager:broadcastEvent(Event:new("Exit"))
+    end,
 }
 exit_settings.exit = {
     text = _("Exit"),
```
